### ISSUE TITLE
Name the repository "server"

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1]
Could we name it "server"? This would avoid the confusion ... or directly "nextcloud". Often projects use the same name for the main repo.

**Comment by MorrisJobke** [comment]
cc @karlitschek

**Comment by karlitschek** [comment]
done :-)

**Comment by jancborchardt** [comment]
Yeah, way better than »core«, good call! :) Also better than »nextcloud« since it’s not the only component.

**Comment by jancborchardt** [comment]
Oh and once we should have a »client« repository, we should call it »desktop«. ;)

**Comment by jancborchardt** [comment]
@KurtPfeifle https://github.com/nextcloud/android ;)
