### ISSUE TITLE
Upgrade from Owncloud: a crap load of verification failed

### ISSUE THREAD

**Issue by thefirstofthe300** [nextcloud/server#100]
I am getting a crap ton of file verification failed errors.  This is from an upgrade from Owncloud.  You can see my setup details in issue #99.

https://owncloud.danielseymour.info/s/G68i169PpCdgKfY

**Comment by LukasReschke** [comment]
Please perform the update properly as described in the documentation. You need to remove _ALL_ files first except `data/` and `config/` and then upload the new ones.

**Comment by LukasReschke** [comment]
See also https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551

**Comment by thefirstofthe300** [comment]
Chalk one up to my stupidity.  All checks pass now.
