### ISSUE TITLE
Make trashbin:cleanup clean all users an explicit option not the default

### ISSUE THREAD

**Issue by liamdennehy** [nextcloud/server#10001]
### Steps to reproduce
1. `php ./occ trashbin:cleanup <user>` cleans one user
2. `php ./occ trashbin:cleanup` cleans all users

### Expected behaviour
* Not specifying a user should request which users to clean, or show help, as with other commands

### Actual behaviour
* Failing to specify a user cleans all trash for all users, making file recovery impossible
* This is easy to accidentally invoke, especially when probing for usage as other commands display, risking data loss

### Server configuration
Core component "files" on NC13.0.4

**Operating system**:
All
**Web server:**
All
**Database:**
All
**PHP version:**
All
**Nextcloud version:** (see Nextcloud admin page)
13.0.4

# Comments
The default behaviour (the fall-through) is more dangerous than the specific case. e.g. `user:disable` without parameters doesn't disable all users, but throws an exception. The `trashbin:cleanup` command should also fall through safely without parameters.
* Replace the default "no uid specified" case with an exception
* Only invoke action on all users with `trashbin:cleanup --all(-users)`.

**Comment by liamdennehy** [comment]
I will take a crack at making a PR myself, but I've never worked on a production-grade PHP project so will likely be very poor quality

**Comment by MorrisJobke** [comment]
> I will take a crack at making a PR myself, but I've never worked on a production-grade PHP project so will likely be very poor quality

Don't worry - we can assist once you have questions. Feel free to join IRC at freenode: #nextcloud-dev

**Comment by rullzer** [comment]
Fixed by #10041
