### ISSUE TITLE
Storagelimit is shown as -2 when using external storage app

### ISSUE THREAD

**Issue by ntimo** [nextcloud/server#10011]
### Steps to reproduce
1. Active the external storage App
2. Mount a storage (I only tested webdav)
3. Set the mount point to /
4. Open your iOS Nextcloud App and look at the storage limit

### Expected behaviour
It should show a unlimited max storage like the web version of nextcloud does

### Actual behaviour
It shows -2 here is a screenshot:
![bug](https://user-images.githubusercontent.com/6145026/41924421-43161564-796a-11e8-9718-4fca1b8f3d59.jpg)

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Nginx

**Database:**
Mysql

**PHP version:**
7.2.4-fpm

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh installation

**Are you using external storage, if yes which one:** local/smb/sftp/...
webdav mounted to /

**Are you using encryption:** yes/no
yes

**Comment by MorrisJobke** [comment]
This is an issue within the iOS app. Thus please report it to the maintainers of that app in its repository: https://github.com/nextcloud/ios
