### ISSUE TITLE
Prerequisite for Talk : enabling indicators for Sent/Received/Read text messages

### ISSUE THREAD

**Issue by GLLM** [nextcloud/server#10029]
Hi NC devs !!

I logged a Feature request (https://github.com/nextcloud/talk-android/issues/219) on Android Talk repo but I was told there's a prerequisite on the server side, hence this new issue :+1: 

Could the server enable Talk clients to get status indicators for message : Sent/Received/Read ?
The aim is for Clients to be able to get the same features as Signal/Whatsapp have.

Thanks.

**Comment by MorrisJobke** [comment]
> I logged a Feature request (nextcloud/talk-android#219) on Android Talk repo but I was told there's a prerequisite on the server side, hence this new issue 👍
> 
> Could the server enable Talk clients to get status indicators for message : Sent/Received/Read ?
> The aim is for Clients to be able to get the same features as Signal/Whatsapp have.

Hi @GLLM - thanks for the request, but unfortunately this is again the wrong repo. Just copy your issue to https://github.com/nextcloud/spreed

@Mario Next time just mention the correct repo to make it easier to contribute feature request.

**Comment by GLLM** [comment]
@MorrisJobke Hahaha, sorry !
Done @ https://github.com/nextcloud/spreed/issues/1012

@mario : no worries ;-)
