### ISSUE TITLE
S3 Primary storage backup

### ISSUE THREAD

**Issue by umardraz** [nextcloud/server#10022]
Hello

I am using S3 bucket as primary storage for my NextCloud. I realized NC saving files into S3 bucket as uid:oid:xxx.

Now my question is how I can backup of my S3 bucket on daily basis and then what I need to do so I can download/retrieve a specific file/folder from that backup?

**Comment by MorrisJobke** [comment]
> I am using S3 bucket as primary storage for my NextCloud. I realized NC saving files into S3 bucket as uid:oid:xxx.
> 
> Now my question is how I can backup of my S3 bucket on daily basis and then what I need to do so I can download/retrieve a specific file/folder from that backup?

Usually only via a restored nextcloud instance. The path is stored in the file cache which holds also the folder structure. The files are then stored by their ID in the object storage.

Easiest approach is: restore the nextcloud instance in a separate setup and use that to fetch the needed files
Advanced approach: scrape the oc_filecache table and build the folder structure by hand (parent is the parent element of a file and then you can build the file tree from that) and then fetch the related file IDs from the object storage.
