### ISSUE TITLE
Improve style of whats new drop down

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10047]
Was a remark by @jancborchardt to not use stars in the whats new drop down - ref #9705

![bildschirmfoto 2018-06-29 um 09 07 28](https://user-images.githubusercontent.com/245432/42082473-5fd36420-7b88-11e8-892e-d785baf17ce9.png)

Ideas @nextcloud/designers ?

cc @blizzz

**Comment by skjnldsv** [comment]
We could class the different changes by types? Design, security, bug... And use proper icons?

**Comment by blizzz** [comment]
@skjnldsv there's no further meta information provided. I think simple bullet points are better here.

**Comment by blizzz** [comment]
> Was a remark by @jancborchardt to not use stars in the whats new drop down - ref #9705

We need an icon and when I was working on it there was no bullet point icon, so i took the next best thing. If  some artist can provide a nice svg, this is fixed easily.

**Comment by skjnldsv** [comment]
@blizzz that's what I was saying, we could add this? :)

**Comment by skjnldsv** [comment]
Okay then ^^

**Comment by jancborchardt** [comment]
If we do want an icon, I would say icon-checkmark is much better. That also communicates "fixed" or "done". What do you think?

**Comment by blizzz** [comment]
[New icons](https://www.google.de/search?biw=1504&bih=696&tbm=isch&sa=1&ei=h5M7W_nWKYfWwAK9q67YAQ&q=new&oq=new&gs_l=img.3..0i67k1l10.13306.13306.0.13560.1.1.0.0.0.0.138.138.0j1.1.0....0...1c.1.64.img..0.1.137....0.AIuyA-dhX48) are typically stars with several spikes, or flags.
