### ISSUE TITLE
Mail Buttons not shown in LotusNotes 

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#10052]
The Mail buttons are invisible in LotusNotes:
![grafik](https://user-images.githubusercontent.com/6691165/42088749-f461cf5c-7b9a-11e8-9244-26f152e96254.png)

I think this is because the color is set on the td and not on the table of the button:
```
<table class="button btn default primary float-center" style="Margin:0;border-collapse:collapse;border-spacing:0;display:inline-block;float:none;margin:0;max-height:40px;padding:0;text-align:center;vertical-align:top;width:auto">
	<tr style="padding:0;text-align:left;vertical-align:top">
		<td style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;border-collapse:collapse!important;color:#0a0a0a;font-family:Lucida Grande,Geneva,Verdana,sans-serif;font-size:16px;font-weight:400;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">
			<table style="border-collapse:collapse;border-spacing:0;padding:0;text-align:left;vertical-align:top;width:100%">
				<tr style="padding:0;text-align:left;vertical-align:top">
					<td style="-moz-hyphens:auto;-webkit-hyphens:auto;Margin:0;background:#0089C1;border:0 solid #0089C1;border-collapse:collapse!important;color:#fefefe;font-family:Lucida Grande,Geneva,Verdana,sans-serif;font-size:16px;font-weight:400;hyphens:auto;line-height:1.3;margin:0;padding:0;text-align:left;vertical-align:top;word-wrap:break-word">
						<a href="https://cloud.domain.com/s/id12345678" style="Margin:0;border:0 solid #0089C1;border-radius:2px;color:#ffffff;display:inline-block;font-family:Lucida Grande,Geneva,Verdana,sans-serif;font-size:16px;font-weight:regular;line-height:1.3;margin:0;padding:10px 25px 10px 25px;text-align:left;outline:1px solid #ffffff;text-decoration:none">Öffne »Test«</a>
					</td>
				</tr>
			</table>
		</td>
	</tr>
</table>
```

The logo background color is set on the table. Maybe it's possible to set the button color on the table to?

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
As reference https://www.campaignmonitor.com/css/email-client/ibm-notes-9/

**Comment by MorrisJobke** [comment]
Should be possible to add this to the template - problem here is that this will break with customized email templates :/

**Comment by rullzer** [comment]
@nickvergessen @juliushaertl @MorrisJobke something to look into

**Comment by juliushaertl** [comment]
Created a PR with the proposed change to move the background color to the table at #10291.

@MorrisJobke This will happen with any change we do to the email template. Maybe we should just add a note about that to the release notes, so that people who use a custom email template can fix it for their implementation.

**Comment by MorrisJobke** [comment]
> @MorrisJobke This will happen with any change we do to the email template. Maybe we should just add a note about that to the release notes, so that people who use a custom email template can fix it for their implementation.

See the comment from @nickvergessen
