### ISSUE TITLE
LDAP config not accepted when DN and CN are in lower case

### ISSUE THREAD

**Issue by Alwaysin** [nextcloud/server#10057]
### Steps to reproduce
1. Activate LDAP app
2. Enter your user DN with "DN" and "CN" in lower case.
3. Check

### Expected behaviour
```cn=bind,dc=sub,dc=domain,dc=com```

should be accepted
### Actual behaviour
```cn=bind,dc=sub,dc=domain,dc=com```

is not accepted, only

```CN=bind,DC=sub,DC=domain,DC=com```
### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.4.25

**Database:** Ver 15.1 Distrib 10.1.26-MariaDB

**PHP version:** 7.0.27

**Nextcloud version:** (see Nextcloud admin page) 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** from an earlier 13.0.x version

**Where did you install Nextcloud from:** https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using an external user-backend, if yes which one:** ActiveDirectory

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
@Alwaysin if anything it is your LDAP server that acts up. There's nothing we control on client side.

**Comment by Alwaysin** [comment]
@blizzz this is strange since I have other applications connected to my LDAP and they work when configured in lower cases...
