### ISSUE TITLE
sync error: File name too long

### ISSUE THREAD

**Issue by voxspox** [nextcloud/server#10060]
### Steps to reproduce
1. add file on another computer (macOS) or webinterface
2. Nextcloud sync client (2.3.3) on my computer (Linux) fails with "File name too long"

### Expected behaviour
sync file

### Actual behaviour
- file is not synced
- charaters:
filename: 150
filepath: 211 (inside cloud folder)
absolute filepath: 236 (in the filesystem)

if I reduce the filename to 144 chars the file gets synced as usual.

### Server configuration

**Nextcloud version:**
13.0.4

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
default

**Comment by voxspox** [comment]
do you need more infos?

**Comment by voxspox** [comment]
- The fie is not large: 66kB
- the file was new and it syncs for the max computer. I think it is maybe a Linux client related issue
- the filename is far from 255 limit
- deleting is not my case
- I removed commas -> not fixed

**Comment by MorrisJobke** [comment]
Could I ask you to open this ticket in the desktop client repository: https://github.com/nextcloud/desktop

Thanks

**Comment by voxspox** [comment]
done: https://github.com/nextcloud/desktop/issues/467

**Comment by DineshRefex** [comment]
help me where to find the longfile path in nextcloud
