### ISSUE TITLE
Links to files from url bar do not work

### ISSUE THREAD

**Issue by JanoschDeurer** [nextcloud/server#10067]
### Steps to reproduce

1. Open a file in Nextcloud
2. Reload the site

Alternative Steps:
1. Open a file in Nextcloud
2. Copy URL from address bar
3. Open a new tab
4. Open the saved url

### Expected behaviour
When reloading a page the file should be opened again. The same should happen, when the url is saved and accessed in a new tab.

### Actual behaviour
The parent folder of the file is shown. It seams like the get parameter &fileid=12345 is ignored.

### Server configuration

**Operating system**:
Docker on Ubuntu 16.04

**Web server:**
Nginx proxy
Apache from official image

**Database:** mariadb on docker

**PHP version:** 7.1.17 from official image

**Nextcloud version:** 13.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Dockerhub

**Comment by MorrisJobke** [comment]
Is the case for example for images and the pdfviewer.

@nextcloud/javascript Any ideas how to address this?

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by skjnldsv** [comment]
Nah, fixed already with the introcudtion of the `openfile` in url feature

`https://dev.domain.com/apps/files/?dir=/&openfile=88`
