### ISSUE TITLE
Feature Request: Remove items from trash that are older than xy days/month/years

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/server#10074]
Hey guys,

thank you for your great work. I have a question regarding a new feature.

Is it possible to implement a function into trash view for deleting items that are older than xy Days/Month/Years?

Best Regards,
Artem

**Comment by MorrisJobke** [comment]
> Is it possible to implement a function into trash view for deleting items that are older than xy Days/Month/Years?

This is already implemented ;)

See https://github.com/nextcloud/server/blob/master/config/config.sample.php#L539-L572

**Comment by artemanufrij** [comment]
wow!!! thank you guys!
