### ISSUE TITLE
How to enable LinkedinAuth

### ISSUE THREAD

**Issue by umardraz** [nextcloud/server#10081]
Hello how I can enable linkedin authentication in Nextcloud. I had tried the social login app but it is missing in that app.

**Comment by MorrisJobke** [comment]
> Hello how I can enable linkedin authentication in Nextcloud. I had tried the social login app but it is missing in that app.

There is no LinkedIn authentication in Nextcloud. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

This should then be implemented as a user backend app.
