### ISSUE TITLE
Non-obvious double slash causes HTTP 500 

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#10084]
Steps:
1. Install Nextcloud 13.0.2 at `https://example.com/nextcloud/`
2. Run Linux Desktop client, enter `https://example.com/nextcloud/` (note the trailing slash) as the URL

Observation:
* Desktop client fails to connect with an error message.
* Server has an HTTP 500 in the log.
* caused by this Exception in `lib/private/AppFramework/Http/Request.php`:
```
                if (!empty($path)) {
                        if($path === $pathInfo || strpos($pathInfo, $path.'/') === 0) {
                                $pathInfo = substr($pathInfo, strlen($path));
                        } else {
                                throw new \Exception("The requested uri($requestUri) cannot be processed by the script '$scriptName')");
                        }
                }
```
If works if I do not provide the trailing slash in the URL.

Remedy:
Either client-side, or server-side, be more tolerant. Many users -- like myself -- type trailing slashes when entering URLs in their browser to avoid an extra HTTP round-trip. Alternatively, provide a more meaningful error message, but I'd prefer the more tolerant approach.

**Comment by MorrisJobke** [comment]
> Desktop client fails to connect with an error message.

Is there more detail on this?




> Server has an HTTP 500 in the log.

Could you post the error message?

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Actually the server side is doing what it should because double slashes can't just be removed.

Also this is fixed on the client in current master as far as I know.
