### ISSUE TITLE
migrate file "Nextcloud Manual.pdf" when update Nexcloud to a new versoin

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#10096]
### Steps to reproduce
1. Install a release (ex. NC 12)[ok]
2. Create users -> all user get the "Nextcloud Manual.pdf" in the version for NC 12 in "All Files - homefolder" [ok]
3. Update to next release (ex. NC 13) [ok]
4. Create users -> all user get the current "Nextcloud Manual.pdf" now in the version for NC 13 in "All Files - homefolder" [ok]
5. The user, created in previous version of Nextcloud have still the previous and now outdated version for "Nextcloud Manual.pdf" in "All Files - homefolder" [not ok]

### Expected behaviour
The automatic generated file "Nextcloud Manual.pdf" should be migrated to the current version of Nextcloud, so no user has an outdated "Nextcloud Manual.pdf" in the "All Files - homefolder"

### Actual behaviour
The user, created in previous version of Nextcloud have still the previous version for "Nextcloud Manual.pdf" in "All Files - homefolder"

**Comment by MorrisJobke** [comment]
I would not change files in the user directory. The user could have updated the file in between and we then would overwrite it. :-1: from my side.

@karlitschek @rullzer @skjnldsv @nickvergessen @jancborchardt Opinions on this one?

**Comment by cloud2018** [comment]
@MorrisJobke yes, i agree with  you, that we get problems, when the migration process overwrites the file. 

To bypass the situation, that after long time of running nextcloud a lot of users have an outdated manual at the starting page, perhaps it's better that the pdf is not created by default, but a link in the left sidebar is set, which always refers to the installed version of nextcloud.

**Comment by MorrisJobke** [comment]
This is already the case: it’s the item „help“ on the top right menu ;)

The PDF is in there to showcase PDF files and we have this since years. Your ticket is the first one that reports this. I would close this ticket for now as the user can just delete that file and be happy. Let’s not make things harder than they are. ;)

Thanks for the feedback anyway :+1:
