### ISSUE TITLE
Update 13.0.4 Failed

### ISSUE THREAD

**Issue by squasteel** [nextcloud/server#10095]
### Steps to reproduce
1. Starting Update in Admin Panel
2. Execute Update und Login Page
3. Failed after one second

### Expected behaviour
Succesfull Update

### Actual behaviour
While execute the Update, this Error occured:
Aktualisierung auf 13.0.4
Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_activity AS SELECT activity_id, timestamp, priority, type, user, affecteduser, subject, message, file, link, object_type, object_id, app, subjectparams, messageparams FROM oc_activity': SQLSTATE[HY000]: General error: 14 unable to open database file

Detaillierte Protokollmeldungen 
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Doctrine\DBAL\Exception\ConnectionException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_activity AS SELECT activity_id, timestamp, priority, type, user, affecteduser, subject, message, file, link, object_type, object_id, app, subjectparams, messageparams FROM oc_activity': SQLSTATE[HY000]: General error: 14 unable to open database file

### Server configuration

**Operating system**:
Webhosting

**Web server:**
apache 2.4

**Database:**
sqlite3

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
One before 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from an older Nextcloud

**Where did you install Nextcloud from:**
Webinstaller long before

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => ',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'speicher.salschnig.at',
  ),
  'datadirectory' => '/home/webpages/lima-city/masshome/cloud/data',
  'overwrite.cli.url' => 'http://speicher.salschnig.at',
  'dbtype' => 'sqlite3',
  'version' => '13.0.2.1',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'salschnig.at',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'memcache.local' => '\\OC\\Memcache\\Memcached',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => '/usr/share/lima/php-masshome/memcached.sock',
      1 => 0,
    ),
  ),
  'updater.secret' => '',
);

</details>

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome

**Operating system:**
Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"Udmn1KLnEQaq9BJXIlSj","level":0,"time":"2018-07-03T18:35:19+00:00","remoteAddr":"77.119.234.141","user":"--","app":"core","method":"GET","url":"\/index.php\/settings\/integrity\/failed","message":"Scss is disabled for \/home\/webpages\/lima-city\/masshome\/cloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"Udmn1KLnEQaq9BJXIlSj","level":0,"time":"2018-07-03T18:35:19+00:00","remoteAddr":"77.119.234.141","user":"--","app":"core","method":"GET","url":"\/index.php\/settings\/integrity\/failed","message":"Scss is disabled for \/home\/webpages\/lima-city\/masshome\/cloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"Udmn1KLnEQaq9BJXIlSj","level":0,"time":"2018-07-03T18:35:19+00:00","remoteAddr":"77.119.234.141","user":"--","app":"core","method":"GET","url":"\/index.php\/settings\/integrity\/failed","message":"Scss is disabled for \/home\/webpages\/lima-city\/masshome\/cloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"Udmn1KLnEQaq9BJXIlSj","level":0,"time":"2018-07-03T18:35:19+00:00","remoteAddr":"77.119.234.141","user":"--","app":"core","method":"GET","url":"\/index.php\/settings\/integrity\/failed","message":"Scss is disabled for \/home\/webpages\/lima-city\/masshome\/cloud\/core\/css\/share.scss, ignoring","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:22+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Updater::setDebugLogLevel: Set log level to debug","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:22+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":0,"time":"2018-07-03T18:35:22+00:00","remoteAddr":"77.119.234.141","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"starting upgrade from 13.0.2.1 to 13.0.4.0","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:22+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:22+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Repair::info: Repair info: Not a mysql database -> nothing to do","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:22+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Repair::step: Repair step: Repair SQLite autoincrement","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":3,"time":"2018-07-03T18:35:23+00:00","remoteAddr":"77.119.234.141","user":"--","app":"core","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\ConnectionException\",\"Message\":\"An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_activity AS SELECT activity_id, timestamp, priority, type, user, affecteduser, subject, message, file, link, object_type, object_id, app, subjectparams, messageparams FROM oc_activity':\\n\\nSQLSTATE[HY000]: General error: 14 unable to open database file\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractSQLiteDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(964): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOSqlite\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'CREATE TEMPORAR...')\\n#2 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/lib\\\/private\\\/Repair\\\/SqliteAutoincrement.php(96): Doctrine\\\\DBAL\\\\Connection->query('CREATE TEMPORAR...')\\n#3 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/lib\\\/private\\\/Repair.php(93): OC\\\\Repair\\\\SqliteAutoincrement->run(Object(OC\\\\Repair))\\n#4 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/lib\\\/private\\\/Updater.php(258): OC\\\\Repair->run()\\n#5 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/lib\\\/private\\\/Updater.php(139): OC\\\\Updater->doUpgrade('13.0.4.0', '13.0.2.1')\\n#6 \\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/core\\\/ajax\\\/update.php(212): OC\\\\Updater->upgrade()\\n#7 {main}\",\"File\":\"\\\/home\\\/webpages\\\/lima-city\\\/masshome\\\/cloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractSQLiteDriver.php\",\"Line\":82}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":3,"time":"2018-07-03T18:35:23+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Updater::failure: Doctrine\\DBAL\\Exception\\ConnectionException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_activity AS SELECT activity_id, timestamp, priority, type, user, affecteduser, subject, message, file, link, object_type, object_id, app, subjectparams, messageparams FROM oc_activity':\n\nSQLSTATE[HY000]: General error: 14 unable to open database file","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":3,"time":"2018-07-03T18:35:23+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:23+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
{"reqId":"eUpR0ryRktJVVjtXDf74","level":1,"time":"2018-07-03T18:35:23+00:00","remoteAddr":"77.119.234.141","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=ZBs6eBL6UJ7VKZ%2F82jk5HBLCFrQIz%2FT%2BT6mVjgZpE24%3D%3AMWtuD2a4Ys2SfamU63FzM3nwL%2FllgoOyB%2Baltk4dfgI%3D","message":"\\OC\\Updater::resetLogLevel: Reset log level to Debug(0)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.2.1"}
</details>

**Comment by MorrisJobke** [comment]
> SQLSTATE[HY000]: General error: 14 unable to open database file


There is not much we can do here. Check the DB file for corruption.


As this also seems to be a setup issue I would like to ask you to raise questions for further help in the forums: https://help.nextcloud.com
