### ISSUE TITLE
enhanced shared info  

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#10106]
Nextcloud 13.0.2
who can see/edit a file/directory

- if the file / directory is shared - the current info is sufficient

- if a directory above in the hierarchy is shared - no info is available at a lower level.

Hence: 
the shared info should include ALL user / groups (with users) who are entitled to see/edit the document

**Comment by MorrisJobke** [comment]
Duplicate of #4281 which aims to show the "Who has access to that file?" for each file and folder.
