### ISSUE TITLE
Objectstorage callback wrapper skips wrapped caches

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#10109]
How to test:

1. setup S3 as primary storage
2. add a tag 'test'
3. enable files_automated tagging and have a rule to assing 'test'
4. upload a file

The tag should be added. But it is not added.

The reason for this is in: https://github.com/nextcloud/server/blob/d05469959e9d2f51110ec2692b042e029f28d66d/lib/private/Files/ObjectStore/ObjectStoreStorage.php#L408

When we reach the fopen of the objectstorage we do an fopen with a callbackwrapper.
Now when we perform the fclose we directly land in the writeBack function. If in here we request the cache we just get back the cache at that point. So there are no wrappers around it. Which means that automated tagging can't do its job and add the tag.

**Comment by MorrisJobke** [comment]
new event is in: https://github.com/nextcloud/server/pull/13748

**Comment by MorrisJobke** [comment]
Potential fixes in the tagging: 

* https://github.com/nextcloud/files_automatedtagging/pull/70
* https://github.com/nextcloud/files_automatedtagging/pull/71

**Comment by rullzer** [comment]
Works now :rocket:
