### ISSUE TITLE
Crashing Sync Client for Windows when syncing to a dynamic share/HomeShare

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#10104]
### Steps to reproduce
1.
Install Sync Client, connect with Cloudserver and 
2.
select a dynamically shared drive to be synced with the cloud.
3.

### Expected behaviour
Until we changed from static shares to dynamic shares there was no problem with syncing.

### Actual behaviour
Client crashes with an Visual C++ Runtime Error in nextcloud.exe on most clients. On some it started working again spontanously some days later.
On clients throwing the error it can be reproduced on version 2.3.2.1 2.3.3.1 and 2.5.0.0.Debug

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
13.0.2 to 13.0.4

### Client configuration
**Operating system:**
Windows 10 1709
### Logs
Nextcloud Sync Client logs the following:
07-04 15:43:42:604 11448 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0x8ca6e58) "1"
07-04 15:43:42:634 11448 OCC::Folder::saveToSettings: Saved folder "1" to settings, status 0
07-04 15:43:42:635 11448 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "1" because status() is 1
07-04 15:43:42:646 11448 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://cloudtest.itk-rheinland.de/remote.php/webdav/" :  "Not yet Started"
07-04 15:43:42:665 11448 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.16.1"
07-04 15:43:42:665 11448 OCC::defaultJournalMode: Detected filesystem "NTFS" for "P:/._sync_a164b3061d23.db"
07-04 15:43:42:674 11448 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
07-04 15:43:42:699 11448 OCC::SqlQuery::exec: Sqlite exec statement error: 10 "disk I/O error" in "CREATE TABLE IF NOT EXISTS metadata(phash INTEGER(8),pathlen INTEGER,path VARCHAR(4096),inode INTEGER,uid INTEGER,gid INTEGER,mode INTEGER,modtime INTEGER(8),type INTEGER,md5 VARCHAR(32),PRIMARY KEY(phash));"
07-04 15:43:42:699 11448 OCC::SyncJournalDb::commitTransaction: ERROR committing to the database:  "cannot commit - no transaction is active"
07-04 15:43:42:699 11448 OCC::SyncJournalDb::sqlFail: SQL Error "Create table metadata" "disk I/O error"
07-04 15:43:42:699 11448 OCC::SyncJournalDb::sqlFail: ASSERT: "false" in file /home/user/client/src/libsync/syncjournaldb.cpp, line 182
07-04 15:43:42:700 11448 OCC::SqlDatabase::close: ENFORCE: "_errId == 0" in file /home/user/client/src/libsync/ownsql.cpp, line 154 with message: Error when closing DB

![ncerror0](https://user-images.githubusercontent.com/34368929/42281642-74bb47fc-7fa4-11e8-9843-e16e921de79d.png)
![ncerror1](https://user-images.githubusercontent.com/34368929/42281667-8af47d68-7fa4-11e8-8563-b15404990da7.PNG)

**Comment by MorrisJobke** [comment]
This is an issue within the desktop app. Thus please report it to the maintainers of the desktop client in its repository: https://github.com/nextcloud/desktop
