### ISSUE TITLE
share dialog doesn't show more then two exact matches?

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#10114]
I just noticed that on master only two exact matches are shown in the share dialog.

If I test the guest app (https://github.com/nextcloud/guests/pull/1) or federated group shares (https://github.com/nextcloud/server/pull/9895) always only two exact matches are shown. In case of the guest apps this means the guest email address and the same address with the option to send a federated share (remote) and in case of federated group sharing it shows the option to send a federated share (remote) or a federated group share (remote group) but the "share by mail option" is always missing although the API returns all three results correctly.

Therefore I assume that we limit the list of exact matches to two. Can some of our JS experts check this and remove this limit? Thanks!

@nextcloud/javascript

**Comment by weeman1337** [comment]
@schiessle at least for the guests app it isn't a JavaScript limit. The guests app handles the autocomplete different (https://github.com/nextcloud/guests/blob/make-compatible-with-nextcloud/js/app.js#L171). It doesn't recognize the email shares yet. I'll have a look at this and will update the guests app "make-compatible-with-nextcloud" branch.

**Comment by skjnldsv** [comment]
What is the status of this issue? Still make sense?

**Comment by skjnldsv** [comment]
We show a bit more now I think :)
Fixed with #15719
