### ISSUE TITLE
Audio player should have controls like video player

### ISSUE THREAD

**Issue by cookierebes** [nextcloud/server#10111]
This is not a bug as much as it is a feature/enhancement request.    I feel strongly that audio files should have playback controls in the same way that video files have controls that surface as a modal window within the file app.  Today the experience is simply covered by an icon that overlays the album art icon, which is confusing and not granular enough an experience for a user that wishes to listen to a part of a song or audio file.

**Comment by MorrisJobke** [comment]
The audio file support in the server itself is quite basic. For further features we recommend to use specialized apps for music playback, that also integrate into the files app and the sharing pages to provide additional controls.

Have a look at https://apps.nextcloud.com/apps/audioplayer and https://apps.nextcloud.com/apps/music

**Comment by MorrisJobke** [comment]
I just found https://github.com/Rello/audioplayer/issues/317 ... so maybe we should address the issues to properly integrate both worlds, but for this we would need more feedback, what is breaking and the files app has a planned restructuring for 15 on the roadmap so we will most likely look into this during that phase.

**Comment by cookierebes** [comment]
Yeah I brought it up with the Rello people and they said that it was difficult on their end to integrate directly with the file app screen.  I just think the video preview is so easy to use, there should be an equivalent preview construct with playback controls for audio

**Comment by MorrisJobke** [comment]
> Yeah I brought it up with the Rello people and they said that it was difficult on their end to integrate directly with the file app screen. I just think the video preview is so easy to use, there should be an equivalent preview construct with playback controls for audio

Also the video app is a separate app and not handled in the server itself. https://github.com/nextcloud/files_videoplayer

As we are touching the files app in the next release cycle we try to keep this in mind and think about how to integrate other apps.

Thanks for the feedback.
