### ISSUE TITLE
Access over old URL ../owncloud no longer works

### ISSUE THREAD

**Issue by BurtGummer** [nextcloud/server#10112]
Hello,

NC 13.0.4 on a Debian Stretch with apache2 and mariadb. I have some clients, that uses the old URL ../owncloud/ and other clients uses ../cloud/ to browse NC. The URL with ../cloud/ works well, but the URL with ../owncloud/ show a internal server error:

![image](https://user-images.githubusercontent.com/1249295/42304568-20ee6702-8027-11e8-91cf-877448a37446.png)

The log:

`{"reqId":"YLlqa84GS9PYLvNwXoU0","level":3,"time":"2018-07-05T07:35:14+02:00","remoteAddr":"80.xxx.xxx.xxx","user":"--","app":"index","method":"GET","url":"\/owncloud\/login","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"The requested uri(\\\/owncloud\\\/login) cannot be processed by the script '\\\/cloud\\\/index.php')\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/base.php(951): OC\\\\AppFramework\\\\Http\\\\Request->getRawPathInfo()\\n#1 \\\/var\\\/www\\\/html\\\/nextcloud\\\/index.php(42): OC::handleRequest()\\n#2 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Request.php\",\"Line\":733}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; WOW64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/64.0.3282.189 Safari\/537.36 Vivaldi\/1.95.1077.55","version":"13.0.4.0"}`

The config.php:

```
  'overwrite.cli.url' => 'https://example.org/cloud/',
  'htaccess.RewriteBase' => '/cloud',
```

my /etc/apache2/conf-available/nextcloud.conf contains:

```
Alias /owncloud "/var/www/html/nextcloud/"
Alias /cloud "/var/www/html/nextcloud/"
<Directory "/var/www/html/nextcloud">
  Options +FollowSymLinks
  AllowOverride All

  <IfModule mod_dav.c>
        Dav off
  </IfModule>

  SetEnv HOME /var/www/html/nextcloud
  SetEnv HTTP_HOME /var/www/html/nextcloud
</Directory>

<Directory "/var/www/html/nextcloud/data/">
    Require all denied
</Directory>
```

And the .htaccess:

  RewriteBase /cloud

If i change the htaccess to "RewriteBase /" nothing works anymore. 

Any ideas why ../owncloud/ not work?

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
