### ISSUE TITLE
Total space in quota-field shows wrong value

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#10127]
### Steps to reproduce
1. Look at quota (Picture 1)
2. Upload file
3. Look at quota (Should now show the value set in the usersettings from the admin) (Picture 2)
4. Reload page 
5. Look at quota (Should now show either old, or recalculated max which differs from the usersettings)  (Picture 3)

### Expected behaviour
It should always be the max value set by the admin who created the account/usergroup

### Actual behaviour
The max-quota changes

The same wrong value can be seen in the user-area of the settings

**Nextcloud version:**
13.0.4

**Picture 1**
![screenshot_2018-07-06_08-56-04](https://user-images.githubusercontent.com/25279821/42364335-112c868a-80fb-11e8-9889-b481d003791e.png)

**Picture 2**
(512GB is the value that the user is allowed to fill, as set by an admin)
![screenshot_2018-07-06_08-54-04](https://user-images.githubusercontent.com/25279821/42364329-0bf9210a-80fb-11e8-8f15-9f8a3e86e7f2.png)

**Picture 3**
![screenshot_2018-07-06_08-53-00](https://user-images.githubusercontent.com/25279821/42364326-0738c1f2-80fb-11e8-8447-e1321cd456e6.png)

**Comment by MorrisJobke** [comment]
That is maybe because your server runs out of total space. We take as quota the minimum of "quota set by the admin" and "free space available + already stored files"

**Comment by newhinton** [comment]
That could explain it, but which stored files? generally stored by the whole cloud, or by the user?

If it is the user, the value is still wrong because i would need less than 250Gb free serverspace, but i have more than that available.

Interestingly enough, if i reduce the max value for the user, the expected value shows up.

**Comment by MorrisJobke** [comment]
> That could explain it, but which stored files? generally stored by the whole cloud, or by the user?

The ones of you. A little example:

* your server has 20 GB storage
* the system stores 5 GB on it
* out of those 5 GB you store 2 GB under your account
* you give the user 30 GB
* then it will show you 17 GB of total, because there is only 15 GB left and you already use 2 GB so you have then a quota of 17 GB out of the maximum of 30 - otherwise it would upload a 20 GB file just fine and then notice in the middle: yes theoretically you are allowed to upload (not reached your virtual quota, but it doesn't make sense to allow you to upload them as the server can't store them anyways.

So this is more an expected behavior than a bug.

**Comment by newhinton** [comment]
Thank you for your clarification! I'll check if this adds up to my server, and then close the ticket.

**Comment by newhinton** [comment]
It seems that this behavior does not work consistently.

My OS (ubuntu server 16.04) reports ~600Gb used, ~300Gb free.

This should result in the correct display of 512Gb, since the remaining 250Gb are smaller than the free space, so there is enough serverspace to store everything.


Also, would it make sense to indicate that an amount is missing from your assigned quota?
Something like this, with an tooltip that says there is not enough server space?
![42364335-112c868a-80fb-11e8-9889-b481d003791e](https://user-images.githubusercontent.com/25279821/42392602-b1156fe2-8153-11e8-8274-f1e788ff0f41.jpg)

**Comment by newhinton** [comment]
I tried something. Maybe this is something we want?


![2018-07-07 14_11_14-dateien - nextcloud](https://user-images.githubusercontent.com/25279821/42410765-b28ff756-81ef-11e8-9111-75f3c7a5e4df.png)

**Comment by MorrisJobke** [comment]
> I tried something. Maybe this is something we want?

Not really, as the user can't do anything about it. And if the user can't do anything it doesn't make sense to show it to them. maybe the admin should get a warning.

Let's make a new issue for your proposal and how to trigger it. It is an enhancement of the admin view and might make sense.

**Comment by newhinton** [comment]
What proposal do you mean exactly?

**Comment by MorrisJobke** [comment]
> What proposal do you mean exactly?

To show somewhere that the storage limit is reached for some users (use the user with the biggest number of "quota - used space" and then check against the available space on the storage).

**Comment by tabp0le** [comment]
So, I use thin provisioning (lvm), which will pull from a pool with additional storage when low. But the amount of free space reported to the OS is less than the pool. Therefore, the users are actually shown less space available than there actually is. Need to figure out some way to show users the amount of space provisioned to them, regardless of the space "available" to the OS.

**Comment by Gobytego** [comment]
same issue here... i got 500GB allocated to the user, it says the user is using 20GB but the user has well over 60GB.
if i delete a big chunk of that users data and the user has only 5GB of data it still shows 20GB

![Screenshot from 2023-08-24 10-38-23](https://github.com/nextcloud/server/assets/49170602/2b2e012e-0fd2-46db-a8a1-e64d5dc6ba0c)
![Screenshot from 2023-08-24 10-39-14](https://github.com/nextcloud/server/assets/49170602/2be06281-8dba-47b7-9f30-f17aefe592a8)
