### ISSUE TITLE
Quota in Files-App takes to much space

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#10124]
### Steps to reproduce
1. Set Quota to >100Gb
2. Fill Nextcloud with big Files 
3. Open File-App

**Nextcloud version:**
13.0.4

The Quota can break out of the intended bounds. This breaks the style.
I propose to cut off sub-zero decimal places to gather more space if the used and or available exceeds a given size.

![2018-07-05 19_52_54-](https://user-images.githubusercontent.com/25279821/42339448-4b6ea026-808d-11e8-9680-fce388de3bc3.png)

**Comment by newhinton** [comment]
I could open a pull request for the changes if nessessary.

**Comment by rullzer** [comment]
While I agree the .1GB here is pretty useless. It should also need a more flexible solution as certain langauges might translate it still to to long a string.

**Comment by newhinton** [comment]
What could we do?
Create boundaries which create a linebreak when nessessary?
Show only "5MB of 5GB"
Do not show words at all and reduce it only to "5MB/5GB"?

I have no clue whats best here

**Comment by rullzer** [comment]
Me neither. @nextcloud/designers input please :D

**Comment by juliushaertl** [comment]
I'd say we can just add an ellipsis at the end if the text gets too long or we can just get rid of the verb and use "300GB of 500GB", since it should be clear that this is about the **used** space.

**Comment by newhinton** [comment]
I have an open pull request, which edits the fileapp (and even the file which handles the quota).
Can i include a fix there, or should i open a second pull request?
I can then change this text, after a solution was found

**Comment by skjnldsv** [comment]
@newhinton do it :)

**Comment by MorrisJobke** [comment]
A new PR please. ;)

**Comment by newhinton** [comment]
@MorrisJobke  I already added the commit to the existing pr. ^^
I'll revert it and make a new one ;)

**Comment by jancborchardt** [comment]
> I propose to cut off sub-zero decimal places to gather more space if the used and or available exceeds a given size.

Sounds good, but only if the value is `>= 10`, because below 10, the decimal is actually a big percentage of the whole number. Also good adding the ellipsis of course.


> or we can just get rid of the verb and use "300GB of 500GB", since it should be clear that this is about the used space.

Disagree here @juliushaertl, as that is then way too technical and not so friendly.

Another option would be to make sure that the units are always the same (both GB, or both MB for example), then we only have to show the unit once. So it would be:

> 261 of 500 MB used

or 

> 2.5 of 500 GB used

**Comment by newhinton** [comment]
At the moment, the filesize is reduced in the following cases:
over 100MB and under 1GB
and
over 100GB and under 1TB

this can easily be changed and or expanded to fit our needs

**Comment by jancborchardt** [comment]
@newhinton cool! Could you adjust it as I described then? Would be awesome! :) (Also, it seems your pull request at https://github.com/nextcloud/server/pull/10245 is a bit broken cause it has a ton of commits in there?)

**Comment by newhinton** [comment]
@jancborchardt yes that may indeed be true, i guess i made a mistake as i tried to update my fork. I'll update or redo the PR when i have time to do so :)
(And yes, i'll make the changes too ;) )

**Comment by newhinton** [comment]
@jancborchardt I have recreated the pr. Currently the filesizes are reduced when quota (used and total) shows:
over 10MB and under 1GB
and
over 10GB and under 1TB

> Another option would be to make sure that the units are always the same (both GB, or both MB for example), then we only have to show the unit once. So it would be:

This would be way to complicated for little gain. Consider a combination like this:
200B of 500GB
Any combination of different exponents would create a different case, which we would need to cover. Often you would need to show both exponents as well as the number, and only sometimes not. The behaviour would not be consistent over all sizes
