### ISSUE TITLE
First login for every user with LDAP backend returns "Internal Server Error", second login works.

### ISSUE THREAD

**Issue by ehprivacy** [nextcloud/server#10137]
### Steps to reproduce
1. Install new nextcloud instance, pointing to existing LDAP directory:

 su -m www -c '/usr/local/bin/php /usr/local/www/nextcloud/occ maintenance:install --database "pgsql" --database-name "filesync" --database-host "127.0.1.2" --database-user "filesync" --database-pass '"$db_filesync_pass"' --database-table-prefix "" --admin-user "admin" --admin-pass '"$nc_root_pw"' --data-dir "/usr/local/data"'  

su -m www -c "/usr/local/bin/php /usr/local/www/nextcloud/occ config:system:set trusted_domains 1 --value=$ip"

su -m www -c "/usr/local/bin/php /usr/local/www/nextcloud/occ config:system:set loglevel --value=0"

su -m www -c "/usr/local/bin/php /usr/local/www/nextcloud/occ config:import /usr/local/share/nextcloud/fix-apps_paths.json"

su -m www -c "/usr/local/bin/php /usr/local/www/nextcloud/occ app:enable user_ldap"

su -m www -c "/usr/local/bin/php /usr/local/www/nextcloud/occ ldap:create-empty-config"

ldap_settings=\
'hasMemberOfFilterSupport "1"
ldapAgentName "cn=xxx,dc=xxx"
ldapAgentPassword '"$ldap_filesyncsystem_pass"'
ldapBase "dc=xxx"
ldapBaseGroups "dc=xxx"
ldapBaseUsers "dc=xxx"
ldapConfigurationActive "1"
ldapEmailAttribute "maildrop"
ldapExpertUsernameAttr "cn"
ldapGroupFilter "(&(|(objectclass=groupOfNames)))"
ldapGroupFilterObjectclass "groupOfNames"
ldapGroupMemberAssocAttr "member"
ldapHost "127.0.1.3"
ldapLoginFilter "(&(|(objectclass=person))(|(cn=%uid)))"
ldapLoginFilterAttributes "cn"
ldapLoginFilterUsername "0"
ldapPort "389"
ldapUserDisplayName "cn"
ldapUserDisplayName2 "displayname"
ldapUserFilter "(|(objectclass=person))"
ldapUserFilterObjectclass "person"
turnOnPasswordChange "1"'

echo "$ldap_settings" | while read i 
  do
  su -m www -c "/usr/local/bin/php /usr/local/www/nextcloud/occ ldap:set-config s01 $i"
done

2.  Sign in with existing user from LDAP.  Receive "Internal Server Error".

3.  Sign in again with same user and password.  Get access to the Files App appropriately.

### Expected behaviour
The first login should work with no errors.

### Actual behaviour
As stated above, the first login via LDAP fails, future ones succeed.

### Server configuration

**Operating system**:  FreeBSD 11.2

**Web server:**  nginx 1.14.0

**Database:**  Postgres 9.6.9

**PHP version:** 7.1.19

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh Install

**Where did you install Nextcloud from:** pkg install nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - dav: true
  - federatedfilesharing: true
  - files: true
  - lookup_server_connector: true
  - oauth2: true
  - provisioning_api: true
  - twofactor_backupcodes: true
  - user_ldap: 1.3.1
  - workflowengine: true
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_texteditor
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - gallery
  - logreader
  - nextcloud_announcements
  - notifications
  - password_policy
  - serverinfo
  - sharebymail
  - survey_client
  - systemtags
  - theming
  - updatenotification
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

$CONFIG = array (
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'xxx',
  ),
  'datadirectory' => '/usr/local/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'pgsql',
  'version' => '13.0.4.0',
  'dbname' => 'xxx',
  'dbhost' => '127.0.1.2',
  'dbport' => '',
  'dbtableprefix' => '',
  'dbuser' => 'xxx',
  'dbpassword' => 'xxx',
  'installed' => true,
  'instanceid' => 'xxx',
  'loglevel' => '0',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/local/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/usr/local/www/nextcloud/apps-pkg',
      'url' => '/apps-pkg',
      'writable' => false,
    ),
  ),
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes.  LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+----------------------------------------+  
| Configuration                 | s01                                    |  
+-------------------------------+----------------------------------------+  
| hasMemberOfFilterSupport      | 1                                      |  
| hasPagedResultSupport         |                                        |  
| homeFolderNamingRule          |                                        |  
| lastJpegPhotoLookup           | 0                                      |  
| ldapAgentName                 | cn=xxx,dc=xxx       |  
| ldapAgentPassword             | ***                                    |  
| ldapAttributesForGroupSearch  |                                        |  
| ldapAttributesForUserSearch   |                                        |  
| ldapBackupHost                |                                        |  
| ldapBackupPort                |                                        |  
| ldapBase                      | dc=xxx                          |  
| ldapBaseGroups                | dc=xxx                          |  
| ldapBaseUsers                 | dc=xxx                          |  
| ldapCacheTTL                  | 600                                    |  
| ldapConfigurationActive       | 1                                      |  
| ldapDefaultPPolicyDN          |                                        |  
| ldapDynamicGroupMemberURL     |                                        |  
| ldapEmailAttribute            | maildrop                               |  
| ldapExperiencedAdmin          | 0                                      |  
| ldapExpertUUIDGroupAttr       |                                        |  
| ldapExpertUUIDUserAttr        |                                        |  
| ldapExpertUsernameAttr        | cn                                     |  
| ldapGidNumber                 | gidNumber                              |  
| ldapGroupDisplayName          | cn                                     |  
| ldapGroupFilter               | (&(|(objectclass=groupOfNames)))       |  
| ldapGroupFilterGroups         |                                        |  
| ldapGroupFilterMode           | 0                                      |  
| ldapGroupFilterObjectclass    | groupOfNames                           |  
| ldapGroupMemberAssocAttr      | member                                 |  
| ldapHost                      | 127.0.1.3                              |  
| ldapIgnoreNamingRules         |                                        |  
| ldapLoginFilter               | (&(|(objectclass=person))(|(cn=%uid))) |  
| ldapLoginFilterAttributes     | cn                                     |  
| ldapLoginFilterEmail          | 0                                      |  
| ldapLoginFilterMode           | 0                                      |  
| ldapLoginFilterUsername       | 0                                      |  
| ldapNestedGroups              | 0                                      |  
| ldapOverrideMainServer        |                                        |  
| ldapPagingSize                | 500                                    |  
| ldapPort                      | 389                                    |  
| ldapQuotaAttribute            |                                        |  
| ldapQuotaDefault              |                                        |  
| ldapTLS                       | 0                                      |  
| ldapUserDisplayName           | cn                                     |  
| ldapUserDisplayName2          | displayname                            |  
| ldapUserFilter                | (|(objectclass=person))                |  
| ldapUserFilterGroups          |                                        |  
| ldapUserFilterMode            | 0                                      |  
| ldapUserFilterObjectclass     | person                                 |  
| ldapUuidGroupAttribute        | auto                                   |  
| ldapUuidUserAttribute         | auto                                   |  
| turnOffCertCheck              | 0                                      |  
| turnOnPasswordChange          | 1                                      |  
| useMemberOfToDetectMembership | 1                                      |  
+-------------------------------+----------------------------------------+  
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Multiple; Chromium, Firefox

**Operating system:**
Multiple; FreeBSD, Linux, Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
N/A
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Attached, as it's large.
```

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
N/A

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ehprivacy** [comment]
For some reason github will not allow me to upload the log.  So I posted it on pastebin:

https://pastebin.com/y6hmi4TG

**Comment by ehprivacy** [comment]
I looked at the issues nextcloud-bot suggested, but this seems to be something different.

**Comment by MorrisJobke** [comment]
> As stated above, the first login via LDAP fails, future ones succeed.

This instance looks super fishy:

there seems to be tables missing: the calendar one, which causes the first login to fail as it tries to create a calendar on the first login. Also the shipped apps are in a folder called "apps-pkg", this could cause problems as well and might be the source for the missing calendar table. Please fix this first and then the LDAP setup should work just fine:

```json
{
    "reqId": "mmtNLICqmm2p6oeWnF2k",
    "level": 3,
    "time": "2018-07-06T11:10:08+00:00",
    "remoteAddr": "127.0.1.6",
    "user": "--",
    "app": "no app in context",
    "method": "POST",
    "url": "/login",
    "message": {
        "Exception": "Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException",
        "Message": "An exception occurred while executing 'SELECT \\\"id\\\", \\\"uri\\\", \\\"displayname\\\", \\\"principaluri\\\", \\\"description\\\", \\\"synctoken\\\" FROM \\\"addressbooks\\\" WHERE (\\\"uri\\\" = ?) AND (\\\"principaluri\\\" = ?) LIMIT 1' with params [\\\"system\\\", \\\"principals\\\\\\/system\\\\\\/system\\\"]:\\n\\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \\\"addressbooks\\\" does not exist\\nLINE 1: ..., \\\"principaluri\\\", \\\"description\\\", \\\"synctoken\\\" FROM \\\"addressbo...\\n                                                             ^",
        "Code": 0,
        "Trace": "
        	#0 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))
        	#1 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT \\\"id\\\", \\\"u...', Array)
        	#2 lib/private/DB/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT \\\"id\\\", \\\"u...', Array, Array, NULL)
        	#3 3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT \\\"id\\\", \\\"u...', Array, Array)
        	#4 lib/private/DB/QueryBuilder/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()
        	#5 apps-pkg/dav/lib/CardDAV/CardDavBackend.php(314): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()
        	#6 apps-pkg/dav/lib/CardDAV/SyncService.php(133): OCA\\\\DAV\\\\CardDAV\\\\CardDavBackend->getAddressBooksByUri('principals/syst...', 'system')
        	#7 apps-pkg/dav/lib/CardDAV/SyncService.php(311): OCA\\\\DAV\\\\CardDAV\\\\SyncService->ensureSystemAddressBookExists('principals/syst...', 'system', Array)
        	#8 apps-pkg/dav/lib/CardDAV/SyncService.php(267): OCA\\\\DAV\\\\CardDAV\\\\SyncService->getLocalSystemAddressBook()
        	#9 apps-pkg/dav/lib/HookManager.php(124): OCA\\\\DAV\\\\CardDAV\\\\SyncService->updateUser(Object(OC\\\\User\\\\User))
        	#10 lib/private/legacy/hook.php(106): OCA\\\\DAV\\\\HookManager->changeUser(Array)
        	#11 lib/private/Server.php(409): OC_Hook::emit('OC_User', 'changeUser', Array)
        	#12 [internal function]: OC\\\\Server->OC\\\\{closure}(*** sensitive parameters replaced ***)
        	#13 lib/private/Hooks/EmitterTrait.php(99): call_user_func_array(Object(Closure), Array)
        	#14 lib/private/Hooks/PublicEmitter.php(36): OC\\\\Hooks\\\\BasicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'changeUser', Array)
        	#15 lib/private/User/User.php(456): OC\\\\Hooks\\\\PublicEmitter->emit('\\\\\\\\OC\\\\\\\\User', 'changeUser', Array)
        	#16 lib/private/User/User.php(170): OC\\\\User\\\\User->triggerChange('eMailAddress', 'testuser@mailne...', NULL)
        	#17 apps-pkg/user_ldap/lib/User/User.php(470): OC\\\\User\\\\User->setEMailAddress('testuser@mailne...')
        	#18 apps-pkg/user_ldap/lib/User/User.php(218): OCA\\\\User_LDAP\\\\User\\\\User->updateEmail('testuser@mailne...')
        	#19 apps-pkg/user_ldap/lib/Access.php(898): OCA\\\\User_LDAP\\\\User\\\\User->processAttributes(Array)
        	#20 apps-pkg/user_ldap/lib/Access.php(872): OCA\\\\User_LDAP\\\\Access->batchApplyUserAttributes(Array)
        	#21 apps-pkg/user_ldap/lib/Access.php(831): OCA\\\\User_LDAP\\\\Access->fetchListOfUsers('(&(|(objectclas...', Array)
        	#22 apps-pkg/user_ldap/lib/User_LDAP.php(165): OCA\\\\User_LDAP\\\\Access->fetchUsersByLoginName('testuser@mailne...', Array)
        	#23 apps-pkg/user_ldap/lib/User_LDAP.php(182): OCA\\\\User_LDAP\\\\User_LDAP->getLDAPUserByLoginName('testuser@mailne...')
        	#24 [internal function]: OCA\\\\User_LDAP\\\\User_LDAP->checkPassword(*** sensitive parameters replaced ***)
        	#25 apps-pkg/user_ldap/lib/User_Proxy.php(81): call_user_func_array(Array, Array)
        	#26 apps-pkg/user_ldap/lib/Proxy.php(152): OCA\\\\User_LDAP\\\\User_Proxy->walkBackends('testuser@mailne...', 'checkPassword', Array)
        	#27 apps-pkg/user_ldap/lib/User_Proxy.php(196): OCA\\\\User_LDAP\\\\Proxy->handleRequest('testuser@mailne...', 'checkPassword', Array)
        	#28 lib/private/User/Manager.php(204): OCA\\\\User_LDAP\\\\User_Proxy->checkPassword(*** sensitive parameters replaced ***)
        	#29 core/Controller/LoginController.php(254): OC\\\\User\\\\Manager->checkPasswordNoLogging(*** sensitive parameters replaced ***)
        	#30 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)
        	#31 lib/private/AppFramework/Http/Dispatcher.php(161): call_user_func_array(Array, Array)
        	#32 lib/private/AppFramework/Http/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')
        	#33 lib/private/AppFramework/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')
        	#34 lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)
        	#35 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)
        	#36 lib/private/Route/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)
        	#37 lib/base.php(999): OC\\\\Route\\\\Router->match('/login')
        	#38 index.php(42): OC::handleRequest()
        	#39 {main}",
        "File": "3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractPostgreSQLDriver.php",
        "Line": 76
    },
    "userAgent": "Mozilla/5.0 (X11; FreeBSD amd64; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
    "version": "13.0.4.0"
}
{
    "reqId": "mmtNLICqmm2p6oeWnF2k",
    "level": 3,
    "time": "2018-07-06T11:10:08+00:00",
    "remoteAddr": "127.0.1.6",
    "user": "--",
    "app": "index",
    "method": "POST",
    "url": "/login",
    "message": "Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\TableNotFoundException\",\"Message\":\"An exception occurred while executing 'SELECT COUNT(*) FROM \\\"calendars\\\" WHERE (\\\"principaluri\\\" = ?) AND (\\\"uri\\\" <> ?)' with params [\\\"principals\\\\\\/users\\\\\\/testuser@example.com\\\", \\\"contact_birthdays\\\"]:\\n\\nSQLSTATE[42P01]: Undefined table: 7 ERROR:  relation \\\"calendars\\\" does not exist\\nLINE 1: SELECT COUNT(*) FROM \\\"calendars\\\" WHERE (\\\"principaluri\\\" = $1)...\\n                             ^\",\"Code\":0,\"Trace\":\"#0 3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(128): Doctrine\\\\DBAL\\\\Driver\\\\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(855): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT COUNT(*)...', Array)\\n#2 lib\\/private\\/DB\\/Connection.php(195): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT COUNT(*)...', Array, Array, NULL)\\n#3 3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Query\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT COUNT(*)...', Array, Array)\\n#4 lib\\/private\\/DB\\/QueryBuilder\\/QueryBuilder.php(214): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 apps-pkg\\/dav\\/lib\\/CalDAV\\/CalDavBackend.php(220): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 apps-pkg\\/dav\\/lib\\/HookManager.php(130): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->getCalendarsForUserCount('principals\\/user...')\\n#7 apps-pkg\\/dav\\/lib\\/AppInfo\\/Application.php(107): OCA\\\\DAV\\\\HookManager->firstLogin(Object(OC\\\\User\\\\User))\\n#8 [internal function]: OCA\\\\DAV\\\\AppInfo\\\\Application->OCA\\\\DAV\\\\AppInfo\\\\{closure}(*** sensitive parameters replaced ***)\\n#9 3rdparty\\/symfony\\/event-dispatcher\\/EventDispatcher.php(212): call_user_func(Object(Closure), Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent), 'OCP\\\\\\\\IUser::firs...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher))\\n#10 3rdparty\\/symfony\\/event-dispatcher\\/EventDispatcher.php(44): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->doDispatch(Array, 'OCP\\\\\\\\IUser::firs...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent))\\n#11 lib\\/private\\/User\\/Session.php(509): Symfony\\\\Component\\\\EventDispatcher\\\\EventDispatcher->dispatch('OCP\\\\\\\\IUser::firs...', Object(Symfony\\\\Component\\\\EventDispatcher\\\\GenericEvent))\\n#12 lib\\/private\\/User\\/Session.php(370): OC\\\\User\\\\Session->prepareUserLogin(true, true)\\n#13 core\\/Controller\\/LoginController.php(282): OC\\\\User\\\\Session->completeLogin(*** sensitive parameters replaced ***)\\n#14 [internal function]: OC\\\\Core\\\\Controller\\\\LoginController->tryLogin(*** sensitive parameters replaced ***)\\n#15 lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(161): call_user_func_array(Array, Array)\\n#16 lib\\/private\\/AppFramework\\/Http\\/Dispatcher.php(91): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#17 lib\\/private\\/AppFramework\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OC\\\\Core\\\\Controller\\\\LoginController), 'tryLogin')\\n#18 lib\\/private\\/AppFramework\\/Routing\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OC\\\\\\\\Core\\\\\\\\Control...', 'tryLogin', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#19 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#20 lib\\/private\\/Route\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#21 lib\\/base.php(999): OC\\\\Route\\\\Router->match('\\/login')\\n#22 index.php(42): OC::handleRequest()\\n#23 {main}\",\"File\":\"3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractPostgreSQLDriver.php\",\"Line\":76}",
    "userAgent": "Mozilla/5.0 (X11; FreeBSD amd64; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36",
    "version": "13.0.4.0"
}
```


As this seems to be a setup issue I would like to ask you to raise your further questions in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by ehprivacy** [comment]
You were totally right; this was a setup issue.  Apologies for not doing a more thorough google search.
For people who stumble on this again... the "dav" app needs to be enabled and is not in the package for FreeBSD (perhaps others, but definitely here). 

See:  https://help.nextcloud.com/t/freebsd-an-exception-occurred-while-executing-insert-into-oc-calendars/30574/3
