### ISSUE TITLE
[Windows] Prevent accidental deletion of whole root folders in connected folder

### ISSUE THREAD

**Issue by pke** [nextcloud/server#1014]
### Steps to reproduce

1. Connect a folder
2. Let it finish sync
3. Drag one of the root folders from the connected folder to the Windows Desktop
4. Watch all content of your nextcloud being deleted

### Expected behaviour
The client should install a Windows Explorer ICopyHook to prevent such operations.

See https://msdn.microsoft.com/en-us/library/windows/desktop/cc144063(v=vs.85).aspx

It could request the user to confirm the operation. If the user is made aware of the DELETE operation to happen the copyhook handler can let the OS continue with its operation, otherwise `IDCANCEL` the whole MOVE operation.
It could also notify the user about useless COPY operations, since wherever you copy the content of the nextcloud folder it will not be kept in sync.

### Actual behaviour
The folder was deleted without further confirmation.

### Client configuration

**Operating system:**

Windows 8/10

**Comment by LukasReschke** [comment]
As that's a client request please reopen it at https://github.com/owncloud/client
