### ISSUE TITLE
Recommendation for MariaDB

### ISSUE THREAD

**Issue by riegercloud** [nextcloud/server#10159]
Dear Nextclouders,

MariaDB does not use the transaction isolation level "READ-COMMIT" as default.

![default](https://user-images.githubusercontent.com/20593693/42444990-f2166c88-8371-11e8-915a-04c8165c2bfa.png)

At least two rows should be added to `/etc/mysql/my.cnf` in the mysqld-section:

```
...
[mysqld]
...
transaction_isolation = READ-COMMITTED
binlog_format = ROW
...
```
After having restarted MariaDB the "Read-Commit" persists and can be verified by:
```
MariaDB [(none)]> SELECT @@TX_ISOLATION;
+----------------+
| @@TX_ISOLATION |
+----------------+
| READ-COMMITTED |
+----------------+
1 row in set (0.00 sec)
```
![readcommited](https://user-images.githubusercontent.com/20593693/42444992-f26de56c-8371-11e8-8b5f-d4442d6adf23.png)

My examplarily configuration (`/etc/mysql/my.cnf`) looks like:
```
[server]
skip-name-resolve
innodb_buffer_pool_size = 128M
innodb_buffer_pool_instances = 1
innodb_flush_log_at_trx_commit = 2
innodb_log_buffer_size = 32M
innodb_max_dirty_pages_pct = 90
query_cache_type = 1
query_cache_limit = 2M
query_cache_min_res_unit = 2k
query_cache_size = 64M
tmp_table_size= 64M
max_heap_table_size= 64M
slow-query-log = 1
slow-query-log-file = /var/log/mysql/slow.log
long_query_time = 1

[client-server]
!includedir /etc/mysql/conf.d/
!includedir /etc/mysql/mariadb.conf.d/

[client]
default-character-set = utf8mb4

[mysqld]
character-set-server = utf8mb4
collation-server = utf8mb4_general_ci
transaction_isolation = READ-COMMITTED
binlog_format = ROW
innodb_large_prefix=on
innodb_file_format=barracuda
innodb_file_per_table=1

```
I guess, this could or should be documented in your Nextcloud documentation either?
Best regards, Carsten

**Comment by MorrisJobke** [comment]
@riegercloud Thanks for the hints - could I ask you to open this in the documentation repo at https://github.com/nextcloud/documentation and if you want you could send this in as a pull request directly to the pages in charge of this topic: https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_database/linux_database_configuration.rst

Thanks a lot for your work in the community regarding all the installation guides - they are really nice 🚀

**Comment by riegercloud** [comment]
not sure if i did it correct?! but i tried to ;-)

**Comment by hostingnuggets** [comment]
@riegercloud do you still need the `binlog_format = ROW` parameter if you for example don't use binary logging? and how can I find out if my MariaDB 10.1.37 has binary logging turned on or off?
