### ISSUE TITLE
occ:  user:list missing "numeric" username

### ISSUE THREAD

**Issue by Django-BOfH** [nextcloud/server#10158]
### Steps to reproduce
1. Create a user named john with fullname John Doe
2. Create a user named 666_tnotb with fullname 666 The Number Of The Beast
3. Create a user named 007 with fullname James Bond
4. Use occ-command user:list `# sudo -u apache /usr/bin/php /var/www/html/cloud/occ user:list`
5. Look what happens. 
` - john: John Doe`
` - 666_tnotb: 666 The Number Of The Beast`
` - James Bond`

### Expected behaviour
All user accounts are displayed correctly, i.e. user ID followed by the complete name!

### Actual behaviour
User names are only displayed if they contain alphanumeric names. User names consisting only of numbers, however, will be embezzled! 

### Server configuration

**Operating system**: CentOS7

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 13.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** original sources

**Signing status:**
<details>
<summary>Signing status</summary>
`No errors have been found.'

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```Enabled:
  - activity: 2.6.1
  - admin_notifications: 1.0.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_antivirus: 1.3.1
  - files_downloadactivity: 1.2.0
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - flowupload: 0.0.7
  - gallery: 18.0.0
  - groupfolders: 1.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - ransomware_protection: 1.1.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.de",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "enable_previews": true,
        "log_rotate_size": "104857600",
        "default_language": "de_DE",
        "loglevel": 3,
        "skeletondirectory": "",
        "mail_send_plaintext_only": true
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "notify_email_calendar": "0",
            "notify_email_calendar_event": "0",
            "notify_email_calendar_todo": "0",
            "notify_email_comments": "1",
            "notify_email_favorite": "1",
            "notify_email_file_changed": "1",
            "notify_email_file_created": "1",
            "notify_email_file_deleted": "1",
            "notify_email_file_restored": "0",
            "notify_email_public_links": "1",
            "notify_email_remote_share": "0",
            "notify_email_shared": "1",
            "notify_email_systemtags": "0",
            "notify_setting_batchtime": "0",
            "notify_setting_self": "1",
            "notify_setting_selfemail": "0",
            "notify_stream_calendar": "1",
            "notify_stream_calendar_event": "1",
            "notify_stream_calendar_todo": "1",
            "notify_stream_comments": "1",
            "notify_stream_favorite": "1",
            "notify_stream_file_changed": "1",
            "notify_stream_file_created": "1",
            "notify_stream_file_deleted": "1",
            "notify_stream_file_favorite": "0",
            "notify_stream_file_restored": "1",
            "notify_stream_public_links": "1",
            "notify_stream_remote_share": "1",
            "notify_stream_shared": "1",
            "notify_stream_systemtags": "1",
            "types": "filesystem"
        },
        "admin_notifications": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "no",
            "installed_version": "3.2.1",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "38203"
        },
        "caniupdate": {
            "enabled": "[\"admin\"]",
            "installed_version": "0.1.2",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1523284875.3596",
            "lastcron": "1531129804",
            "lastupdateResult": "[]",
            "lastupdatedat": "1531062302",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "383180dcd88ffe16bef6df7a070dab4c",
            "shareapi_allow_public_upload": "no",
            "shareapi_allow_resharing": "no",
            "shareapi_enable_link_password_by_default": "yes",
            "shareapi_enforce_links_password": "yes",
            "shareapi_only_share_with_group_members": "yes",
            "umgmt_send_email": "true",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "false",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.4.7",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "0 B",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_max_file_size": "-1",
            "av_mode": "socket",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamd.nextcloud\/clamd.sock",
            "av_stream_max_length": "26214400",
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": "filesystem"
        },
        "files_downloadactivity": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.8.4",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.5.0",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "flowupload": {
            "enabled": "[\"Linux\"]",
            "installed_version": "0.0.7",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "1.2.2",
            "types": "filesystem"
        },
        "logreader": {
            "enabled": "[\"admin\"]",
            "installed_version": "2.0.0",
            "levels": "00011",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "[\"G33k5\",\"admin\"]",
            "installed_version": "2.3.2",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "0",
            "enforceNumericCharacters": "0",
            "enforceSpecialCharacters": "0",
            "enforceUpperLowerCase": "0",
            "installed_version": "1.3.0",
            "minLength": "12",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "alert_email": "yes",
            "enabled": "yes",
            "info_email": "yes",
            "installed_version": "1.2.0",
            "repeat_warning": "1",
            "types": "filesystem",
            "warning_email": "yes"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "notes_include_biased": "yes",
            "types": "logging"
        },
        "serverinfo": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "enforcePasswordProtection": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "3.2.2",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "survey_client": {
            "apps": "no",
            "database": "no",
            "enabled": "yes",
            "encryption": "no",
            "files_sharing": "no",
            "installed_version": "1.1.0",
            "php": "no",
            "server": "no",
            "stats": "no",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "[\"Testuser\"]",
            "installed_version": "0.9.6",
            "ocsid": "164356",
            "types": ""
        },
        "theming": {
            "backgroundMime": "image\/png",
            "cachebuster": "12",
            "color": "#FF0000",
            "enabled": "yes",
            "imprintUrl": "https:\/\/www.example.de\/de\/home\/toolbar\/impressum.html",
            "installed_version": "1.4.5",
            "logoMime": "image\/svg+xml",
            "name": "Cloud der top secret agency",
            "privacyUrl": "https:\/\/www.example.de\/de\/home\/toolbar\/datenschutz.html",
            "slogan": "der sichere Datenaustauschraum f\u00fcr Ihre vertraulichen Daten!",
            "types": "logging",
            "url": "https:\/\/cloud.example.de"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "updatenotification": {
            "core": "13.0.4.0",
            "enabled": "[\"admin\"]",
            "files_pdfviewer": "1.2.1",
            "files_rightclick": "0.8.3",
            "groupfolders": "1.2.2",
            "installed_version": "1.3.0",
            "ransomware_protection": "1.1.1",
            "theming": "1.4.5",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
We had something similar in #6580 and @nickvergessen opened #6972 for this thing. 

@nickvergessen Could this be the same root cause or is this something different?

**Comment by nickvergessen** [comment]
#6972 is something completely different.
