### ISSUE TITLE
Open/edit file with local application and re-upload on save

### ISSUE THREAD

**Issue by brusch** [nextcloud/server#10157]
A similar functionality as Box provides would be really a benefit: 
https://app.box.com/services/box_edit 
or also https://goedit.io/ (for Confluence). 

Functionality in a nutshell: 
Browser extension or local application that downloads the file to a local temporary folder and opens the file with the registered default application. As soon as the file gets saved, it should be re-uploaded again.

**Comment by MorrisJobke** [comment]
This is something that the client should do. There is no API as of now in the browsers that would allow this. After the file is downloaded it is out of the scope of the browser.

Could you file this in the needed client repos:

* https://github.com/nextcloud/desktop
* https://github.com/nextcloud/android
* https://github.com/nextcloud/ios

Thanks
