### ISSUE TITLE
db:convert-mysql-charset and MariaDB 10.3

### ISSUE THREAD

**Issue by timm2k** [nextcloud/server#10163]
Dear devs,

I've tried to use `occ db:convert-mysql-charset` with MariaDB 10.3. MariaDB 10.3 doesn't know global variables like `innodb_large_prefix` and `innodb_file_format` because they were removed and deprcated since MariaDB 10.2. These settings are default and hardcoded in MariaDB 10.3. 

So `db:convert-mysql-charset` fails to run with message 
"The database is not properly setup to use the charset utf8mb4.
For more information please read the documentation at https://docs.nextcloud.com/server/13/go.php?to=admin-mysql-utf8mb4"

`db:convert-mysql-charset` needs to check the db server's version. MariaDB 10.3 is ready to use utf8mb4.

### Steps to reproduce
1. install NC without utf8mb4 support. Use MariaDB 10.3
2.  `occ db:convert-mysql-charset` 

### Expected behaviour
Database is converted to utf8mb4

### Actual behaviour
convert fails

Kind regards
Timm :-)

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Can you please run the following query:
```sql
SELECT VERSION();
```
