### ISSUE TITLE
Unnoticed file change on External storage (Local)

### ISSUE THREAD

**Issue by michalmiddleton** [nextcloud/server#1016]
### Steps to reproduce
1. Set up latest version of NC on Ubuntu server 16.04
2. Set up External storage [Local path] and share it with another user
3. Write ~750kB to the file stored in path ^^, wait ~15-30s before sending another ~250kB and closing the file handle.
4. Notice that the file first file portion was synced to client computer (Linux, using the latest OwnCloud client)
5. Notice that the file won't be re-synced to show the rest content in foreseeable future. 
6. Notice that NextCloud web will remain showing the 750kB size
7. Go to NC web and rename the file 
8. Notice that the file size now shows full size and that the client downloaded the full-sized file. 

Note: Unfortunately, this is the behavior of my Network Scanner that saves files via Samba to the local path mentioned above. I seem to suffer from this symptom only when being actively online on the client computer and it doesn't happen every single time. When I'm offline and allow for this file to be completely transferred before checking (ie. letting my oC client sync), all seems to be working fine. 
### Expected behaviour

NC should notice the file change... 
### Actual behaviour

NC ignored the file change.
### Server configuration

**Operating system**: Ubuntu Server 16.04 + all patches 

**Web server:** Apache 2.4.18

**Database:** MariaDB 10.1.16

**PHP version:** PHP 7.0.8

**Nextcloud version:** 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from oC 9

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>

Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.1.1
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - gallery
  - user_external
  - user_ldap
  - user_saml
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/srv\/owncloud",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.53.0",
        "dbname": "owncloud",
        "dbhost": "10.0.3.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "10.0.3.1",
        "mail_smtpport": "25",
        "mail_from_address": "cloud",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updatechecker": false,
        "maintenance": false,
        "theme": "",
        "htaccess.RewriteBase": "\/cloud"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "5"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "1.3.1.0",
            "ocsid": "168708",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1453773022.8185",
            "lastcron": "1471878002",
            "lastupdateResult": "{\"version\":{},\"versionstring\":{},\"url\":{},\"web\":{}}",
            "lastupdatedat": "0",
            "oc.integritycheck.checker": "[]",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "yes",
            "shareapi_default_expire_date": "no",
            "shareapi_enforce_links_password": "no"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "yes",
            "installed_version": "0.12.0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_external": {
            "\/SCAN": "1453775694",
            "enabled": "yes",
            "installed_version": "0.5.2",
            "ocsid": "166048",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "3": "1457390063.9064",
            "4": "1457390063.9807",
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "14.5.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "yes",
            "installed_version": "15.1.1",
            "ocsid": "169116",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "4",
            "enabled": "yes",
            "installed_version": "0.1.0",
            "name": "MM",
            "slogan": "Access restricted.",
            "types": "",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        }
    }
}
```

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chrome

**Operating system:** Linux / Ubuntu 16.04

**Comment by petwri** [comment]
Same problem here with a similar setup, Ubuntu 16.04 with nextcloud 10, both tried the nextcloud client and the owncloud client on windows 7. No file change on the server gets pushed to the client until I go to the web client and browse to the folder containing the file. That is the moment when a sync on the desktop client is triggered.

**Comment by MorrisJobke** [comment]
@icewind1991 I guess this is the same problem we often have with external storage ... it's super hard to properly detect changes and still be performant. Often this is not possible. :/

**Comment by rednaxela-work** [comment]
Same problem here with Nextcloud 11.0.0 on Red Hat EL 7. 
Nextcloud clients on Windows 7 and Windows 10 not getting updates automatically.

Have to go to the web interface and open up changed files, refresh browser afterwards.
For added files in the external storage it seems to me that a refresh on the folder is sufficient. Would have to verify that.

@MorrisJobke Do you see a chance to get a handle on that problem? 
Maybe add another option to the external storage config, e.g., "Use slow and inperformant but accurate update checks" ;-)
Maybe it could be bundled with cron jobs or get a completely separate cron job?

If I'd get a starting point, I might even have a look at it myself. Have some PHP experience.

**Comment by rednaxela-work** [comment]
Or could my problem be homemade? 
I've just found some older ownCloud tickets relating to this problem - mainly this one here: https://github.com/owncloud/core/issues/11797 - and realized that my root folder doesn't have the mtime updated when files or folders below it get added or updated.
So assuming that the external storage plugin works correctly with local directories and their mtime (most of the time), might the fault be actually mine and not Nextcloud's?

**Comment by michalmiddleton** [comment]
@rednaxela-work What file system do you use? I'm still having this issue on the latest NC release. 
My external storage files are on EXT4 of the same server and the only non-default option on my FS are noatime,nodiratime . 

The owncloud/core#11797 is a great find! 

I tested mtime propagation on my computer (ext4) - it seems to work only one level deep. I am not sure what is the expected behavior without doing any more research but this sounds about right to me. 
Eg. updating file1 updates mtime of level1 dir; updating file2 updates mtime of level2 dir...  
/level1/file1
/level1/level2/file2

**Comment by rednaxela-work** [comment]
@michalmiddleton I didn't set up the system and am not enough Linux expert to know where to find info on the file system config. 
Can you give me a hint?

The mtime propagation you're seeing seems logical to me, too. 
In that case one would have a problem anyway, if directory _level1_ is included as external storage but only _file2_ is updated. So Nextcloud is not "notified" of changes, as directory _level1_'s  mtime doesn't get updated, only directory _level2_'s.

**Comment by icewind1991** [comment]
> So Nextcloud is not "notified" of changes, as directory level1's mtime doesn't get updated, only directory level2's.

Correct

**Comment by michalmiddleton** [comment]
That's unfortunate situation. Sounds like this may be a use case for a binary agent monitoring FS changes (for a "local" external storage). Or using gamin /fam. Otherwise a cronned rescan would have to be implemented. 

At least it gives us a workaround option.

**Comment by icewind1991** [comment]
> Sounds like this may be a use case for a binary agent monitoring FS changes (for a "local" external storage).

Ask and you shall receive (when I feel like it)

- install the php pecl extension
- install [files_inotify](https://apps.nextcloud.com/apps/files_inotify)
- figure out the id of the mount point you want to watch using `occ files_external:list`
- run `occ files_external:notify $mountId` is the background somehow (systemd, screen, etc)

**Comment by ymolinet** [comment]
> run occ files_external:notify $mountId is the background somehow (systemd, screen, etc)
How can I run this command by systemd (to start automatically on server startup).

**Comment by rednaxela-work** [comment]
In the meantime I took another approach that was applicable to our specific problem.

As I only need to sync an external folder once a day - and only one direction (from server to clients) - I set up a davfs mount point and am now copying/rsyncing the daily changes to the Nextcloud folder via WebDAV.

**Comment by ymolinet** [comment]
> As I only need to sync an external folder once a day - and only one direction (from server to clients)

You can not preserve NTFS Permission with this method

**Comment by rednaxela-work** [comment]
> You can not preserve NTFS Permission with this method
True, but I don't need to. It's a one way sync, the client users have read only access for the shared folder.
Also I'm on a Linux server and don't care for NTFS permissions ;-)

**Comment by ymolinet** [comment]
In my case, I use external storage to "connect" a CIFS/SMB share using LDAP authentication.

**Comment by MorrisJobke** [comment]
> In my case, I use external storage to "connect" a CIFS/SMB share using LDAP authentication.

Then the only way as of now is to use the solution pointed out by @icewind1991 : https://github.com/nextcloud/server/issues/1016#issuecomment-279032265

Regarding the systemd file: Please consult the systemd manual or ask in the forums: https://help.nextcloud.com
