### ISSUE TITLE
Passwords written (not hidden or hashed) in log files

### ISSUE THREAD

**Issue by bseclier** [nextcloud/server#10175]
Hi,
We are facing some troubles here. Looking into my logfile, I can see all my user's passwords, not hidden. Here is the kind of log (in the text file attached). I replaced the real password by PASSWORD HERE NOT HIDDEN and the true login by MY LOGIN.

It seems that when OC\\User\\Session->createSessionToken is logged, we can see the password.
Here is my log configuration (in WARN mode) :
  'logfile' => '',
  'log_type' => 'syslog',
  'loglevel' => '2',
  'syslog_tag' => 'nextcloud',

Thanks for taking care of it.
Cheers,
[nextcloud.log](https://github.com/nextcloud/server/files/2179864/nextcloud.log)

**Comment by bseclier** [comment]
Hi little bot,
Thank for the advice but no, this is not.

**Comment by MorrisJobke** [comment]
That is where it needs to be added: https://github.com/nextcloud/server/blob/master/lib/private/Log/ExceptionSerializer.php

**Comment by rullzer** [comment]
@MorrisJobke no it is not in that query as there the password is encrytped anyways already

it is in the stacktrace at https://github.com/nextcloud/server/blob/8c47a632e0afc5b38093818f70dcf4cdead42b4d/lib/private/User/Session.php#L620

**Comment by bseclier** [comment]
You're right @rullzer !

**Comment by nickvergessen** [comment]
time to raise priority on a little script which looks for parameter names and checks that the method name is in the block list, he?

Anyway, I guess adding `createSessionToken` to the list of "bad" methods should be good enough?

**Comment by MorrisJobke** [comment]
Fix is in #10193
