### ISSUE TITLE
Uploading small individual files fails

### ISSUE THREAD

**Issue by geotheory** [nextcloud/server#10184]
I'm running latest Nextcloud13 on Apache2.4 on Ubuntu 16.04, with no data folder encryption.  I can upload very small files (including drag-drop with Dropit) but find anything over ~3 Mb gets stuck on the `Uploading..` bar:

![image](https://user-images.githubusercontent.com/1282581/42543523-32a16e8c-84a4-11e8-923b-7238eac9f3ce.png)

I can't think why this would fail for such small files. In my settings it reads `Upload max size: 511 MB`. I'm just uploading single file, not a batch. Any suggestions?

Perhaps linked to `Max Execution Time: 3600`?

**Comment by geotheory** [comment]
Thank you my kind bot, but I don't think think so.  I've added desktop client and tried syncing. It fails with the following log entry:

```
||myfile.pdf|INST_NEW|Up|1525181139||5332492||1|Connection closed|0|0|0|||INST_NONE|
#=#=#=# Syncrun finished 2018-07-11T01:03:10 (last step: 58 msec, total: 218 msec)
#=#=#=# Syncrun started 2018-07-11T01:04:44
#=#=#=#=# Propagation starts 2018-07-11T01:04:44 (last step: 102 msec, total: 102 msec)
#=#=#=# Syncrun finished 2018-07-11T01:04:44 (last step: 10 msec, total: 113 msec)
```

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

We can't reproduce the problems on instances over here. You could also try https://demo.nextcloud.com to check if it is instance or browser related.

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by geotheory** [comment]
Thanks Morris. I've logged it [here](https://help.nextcloud.com/t/uploading-small-individual-files-fails/33924).
