### ISSUE TITLE
Not ending loading circle in file properties when activies were deleted

### ISSUE THREAD

**Issue by H4ndl3** [nextcloud/server#1018]
I set 'activity_expire_days' to 90 and get a neverending loading circle when opening the activities tab of the properties of files that are older than that. Yeah, the activities were deleted by the cronjob, but I think that the loading circle is irritating because it makes the user think that something is still being loaded.

### Server configuration
**Operating system**: Debian 8.5

**Web server:** nginx/1.6.2 

**Database:** MySQL 10.0.25-MariaDB

**PHP version:** PHP 5.6.24

**Nextcloud version:** 9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from ownCloud 9.0.2

**Where did you install Nextcloud from:** Tarball from official website

**Comment by nickvergessen** [comment]
Does the file still have any activities, or are none left?
Also does the browser console/log show any errors?

Please fill out the issue template that is displayed when opening a new issue.

**Comment by H4ndl3** [comment]
There are no activities left for the affected files and folders. Also there is no error in the browser console regarding this issue, only 404 for missing previews of files where no preview can be created. When I drag my mouse over the loading circle the mouse arrow the mouse arrow turns into the windows loading circle.

I noticed an odd behaviour: Right after logging in the properties tab displays "No activities" when selecting an old file or folder, however, after selecting other files and folders for a while the loading circle doesn't go away anymore for all files and folders older than 'activity_expire_days'.

This is a screenshot of said behaviour:
![loading](https://cloud.githubusercontent.com/assets/15052165/17983510/3c2a5ac0-6b0d-11e6-9b79-86c51a8c00ec.jpg)

**Comment by H4ndl3** [comment]
Seems to have vanished after upgrading to Nextcloud 10.0.

**Comment by nickvergessen** [comment]
Thanks for reporting back :)
