### ISSUE TITLE
Installed and activated apps are listed in Javascript on login page

### ISSUE THREAD

**Issue by oggi4711** [nextcloud/server#10191]
![image](https://user-images.githubusercontent.com/39015198/42565733-8fa5a2c8-8504-11e8-9e02-69e42ebdb40b.png)

for security reason Installed and activated apps should not disclosed to an unauthenticated user.

this is nextcloud 13.

**Comment by nickvergessen** [comment]
hmm, yeah I see why it's not very good, but you never know if an app needs this info or something even on the public page. So no strong opinion on this one.

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore (they aren't listed in  oc_webroots anymore as far as I can see), I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
