### ISSUE TITLE
multiple attachments

### ISSUE THREAD

**Issue by fvkn** [nextcloud/server#10194]
it is currently not possible to attach several files from the same folder in a mail at the same time. We have to pick them up one by one, each time starting from the root folder, which is quite annoying when working with files buried deep within the structure.

in some way this is linked to issue #644 but it would be even faster to be able to add several files directly as attachment.

**Comment by MorrisJobke** [comment]
This is an issue within the mail app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/mail
