### ISSUE TITLE
updater.server.url in 'Nextcloud Verifications' needs an update

### ISSUE THREAD

**Issue by hailthemelody** [nextcloud/server#102]
### Steps to reproduce
1. Visit https://docs.nextcloud.org/server/9/admin_manual/configuration_server/config_sample_php_parameters.html#nextcloud-verifications
2. See value for updater.server.url key

### Expected behaviour
Should point to a nextcloud url

### Actual behaviour
Points to an owncloud url

### Server configuration

n/a

### Client configuration

n/a

### Logs

n/a

**Comment by hailthemelody** [comment]
ps - I would happily send a patch or PR with the change but I'm not sure which URL it should go to. Tried replacing `owncloud` with `nextcloud` in the URL but didn't work (I'm guessing because this detail is still being figured out). Whatever is easiest for the team.

**Comment by LukasReschke** [comment]
https://updates.nextcloud.org/server/ would be the current server. Would be awesome if you can send a pull request for config.sample.php here as well as for the documentation repos 🚀

**Comment by hailthemelody** [comment]
Thanks @LukasReschke and yes I will do that.

**Comment by hailthemelody** [comment]
Hi @LukasReschke please see the two above references for the two relevant PRs.

In doing so I discovered several other issues and wanted to run them by here first before addressing. Happy to send PRs on the below:

* in `lib/private/Updater/VersionCheck.php` and `test/lib/Updater/VersionCheckTest.php` the URL references the old URL. Should these be updated as well?

* in `config/config.sample.php`, both `log_type` and `logfile` are pointing to ownCloud. Should the value for `log_type` be `nextcloud` or would that break functionality without changing the referenced code? Should the value for `logfile` be changed from `/var/log/owncloud.log` to `/var/log/nextcloud.log` (and its comment) or is it being preserved for backwards compatibility etc?

* in `config/config.sample.php` there are dozens of references to ownCloud in the comment blocks. Should these be updated or are we doing this as each component is 'updated' etc?

**Comment by hailthemelody** [comment]
(meta: including @mar1u5 who approved the PRs)

**Comment by MorrisJobke** [comment]
> config/config.sample.php

@hailthemelody The config.sample.php is only for documentation purpose. We need to touch the code anyways.



> both log_type and logfile are pointing to ownCloud.

`log_type` needs adjustments in the code as it will assemble to the class `OC\Log\Owncloud` (see https://github.com/nextcloud/server/blob/master/lib/private/Log/Owncloud.php) which then would not be present if it is changed to Nextcloud. Maybe we name it properly `File` because it logs to a file. The `logfile` is the filename of the resulting log file and is fine to change, but then we also need to update all the documentation ;)

**Comment by MorrisJobke** [comment]
The URLs are now also updated in the code. See https://github.com/nextcloud/server/pull/1323 and the backports
