### ISSUE TITLE
Login big bug (autoreconnect 10-15min after logout, without need any password)

### ISSUE THREAD

**Issue by voxdemonix** [nextcloud/server#10200]
Edit : the problem coming from a firefox extension : [floccus](https://addons.mozilla.org/en-US/firefox/addon/floccus/?src=search)

I have a very strange and affraid bug.
On Firefox after have logout the account, wait some minutes and reload (F5 or CTRL+ALT+R) the index page, nextcloud redirect me on the "Files" menu of my own nextcloud account without needed any password.
With another browser (chrome) i can check the Session and Token in user profil => security, but on firefox it's said "Error while loading browser sessions and device tokens".
![capture d ecran_2018-07-11_15-41-30](https://user-images.githubusercontent.com/8572474/42579216-17666594-8528-11e8-8c34-025d40f636dc.png)

On the second browser i can check Session and token, and their is not any session about the firefox. I have check on 2 versions of firefox.
If i m connected on another nextcloud account with firefox, after some minute when i reload, same bug i m redirect on my own account (big security breach). Same if i delete all cookie, data etc with CTRL+MAJ+Delete.

**Comment by voxdemonix** [comment]
https://github.com/marcelklehr/floccus/issues/133

**Comment by MorrisJobke** [comment]
> Edit : the problem coming from a firefox extension : floccus

Closing then.
