### ISSUE TITLE
Submit button of login page should not use `id="submit"`

### ISSUE THREAD

**Issue by hungtcs** [nextcloud/server#10209]
The 57th line of the file `/core/templates/login.php` have a potential bug
```
<input type="submit" id="submit" class="login primary" title="" value="<?php p($l->t('Log in')); ?>" disabled="disabled" />
```
When I run the code `document.querySelector('form[name="login"]').submit()` under login page and an error will be thrown
```
VM78:1 Uncaught TypeError: document.querySelector(...).submit is not a function
    at <anonymous>:1:46
```
I can't submit this form because `document.querySelector('form[name="login"]').submit` is not a function but a HTMLElement of the submit button.

Please fix it and thanks!

Version Of Server: v13.0.4 and v14

**Comment by MorrisJobke** [comment]
cc @skjnldsv @danxuliu @juliushaertl

**Comment by skjnldsv** [comment]
I guess we could yes.
Why are you running this code @hungtcs ?

**Comment by hungtcs** [comment]
@skjnldsv Ha,I Write a simple script to auto login my server, now `document.querySelector('form[name="login"]').dispatchEvent(new Event('submit'))` is work for me, but I think `id="submit"` is not a good idea.

**Comment by kesselb** [comment]
cc @ChristophWurst we don't need `id="submit"` since the vuejs migration?

**Comment by ChristophWurst** [comment]
Dunno. Maybe it's used for some styles. I'm fine with removing :)
