### ISSUE TITLE
[Feature request] Add an option to use the trash of the "sharer"

### ISSUE THREAD

**Issue by Ich5003** [nextcloud/server#10210]
### Situation:
I have a user sharing folders with some other users.
Those users have a limit of "500KB", so only an initial PDF file from the skeleton dir is in die users folder.
When a user tries to delete a file in a shared dir an error is shown "cannot delete file" (the file is deleted, but still throws an error, because the file is too big for the users trash bin).

### Steps to reproduce
1. Try to delete a file of a shared folder which is bigger than your free quota

### Expected behaviour
File should be moved to trash bin of the user who tries to delete the file though it doesn't meet quota requirements
OR
File should be moved to trash bin of the user who shared the folder

### Actual behaviour
An error "cannot delete file" is shown.
File is deleted (but not in any trash bin, so the error message is misleading too, _if required i may create an extra issue for this bug_)

### Possible implementations:
- Add an option in settings to move deleted files to the trash bin of the user who shared a folder instead of the user who deleted a file
- Make quote don't apply to trash bin
- Add an option to add an extra quota for the trash bin.

**Comment by MorrisJobke** [comment]
Similar to #10265 and a proper explanation of why it works how this is also in there. Thus I will close this one in favor of the other one to enhance the behavior of the trash bin to only store the file where it belongs and not duplicate it.
