### ISSUE TITLE
Contacts leads to:  {{ctrl.t.emptySearch}} on daily (14.0.0 alpha)

### ISSUE THREAD

**Issue by frake65** [nextcloud/server#10216]
### Steps to reproduce
1. Install latest-master.zip
2. install contacts app
3. open "contacts"

### Expected behaviour
The content of my address book should be shown as contacts

### Actual behaviour
In the window where names should be listed the following is shown:

{{ctrl.t.emptySearch}}

### Server configuration

Ubuntu 16.04

apache

mySQL

Php 7.2

Nextcloud 14.0.0 alpha daily (18-07-11)

Updated several times from 11.0 up to now - Issue exists for at least a week now

installed from download.nextcloud.com

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - audioplayer: 2.3.1
  - calendar: 1.6.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.5
  - dashboard: 5.0.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.8.2
  - nextcloud_announcements: 1.3.0
  - oauth2: 1.2.1
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - notifications
  - password_policy
  - user_external
  - user_ldap</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.kettenbeil.de",
            "cloud.kettenbeil.de",
            "kettenbeil.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.kettenbeil.de",
        "dbtype": "mysql",
        "version": "14.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "mail_smtpport": "25",
        "theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "loglevel": 0,
        "maintenance": false,
        "enable_avatars": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "daily",
        "filelocking.enabled": true,
        "memcache.locking_kaputt": "\\OC\\Memcache\\Redis",
        "memcache.local_kaputt": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Chrome

**Operating system:**
Mac OSX 10.14 beta

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
{"reqId":"FKr3YaWTGnjykjRmznbr","level":0,"time":"2018-07-12T11:27:21+00:00","remoteAddr":"xx.yyy.zzz.aaa","user":"cccc","app":"no app in context","method":"GET","url":"\/index.php\/apps\/contacts\/","message":"No cache entry found for \/appdata_oc027yyrvmfh\/avatar\/frank\/avatar.jpg (storage: local::\/var\/www\/vhosts\/kettenbeil.de\/owncloud_data\/, internalPath: appdata_oc027yyrvmfh\/avatar\/frank\/avatar.jpg)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.42 Safari\/537.36","version":"14.0.0.10"}
{"reqId":"FKr3YaWTGnjykjRmznbr","level":0,"time":"2018-07-12T11:27:21+00:00","remoteAddr":"xx.yyy.zzz.aaa","user":"cccc","app":"no app in context","method":"GET","url":"\/index.php\/apps\/contacts\/","message":"No cache entry found for \/appdata_oc027yyrvmfh\/theming\/images\/background (storage: local::\/var\/www\/vhosts\/kettenbeil.de\/owncloud_data\/, internalPath: appdata_oc027yyrvmfh\/theming\/images\/background)","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.42 Safari\/537.36","version":"14.0.0.10"}
{"reqId":"hdLihscnFDI8pK6JHfPz","level":0,"time":"2018-07-12T11:27:21+00:00","remoteAddr":"xx.yyy.zzz.aaa","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Command\\CommandJob job with ID 12602","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.42 Safari\/537.36","version":"14.0.0.10"}
{"reqId":"hdLihscnFDI8pK6JHfPz","level":0,"time":"2018-07-12T11:27:21+00:00","remoteAddr":"xx.yyy.zzz.aaa","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Command\\CommandJob job with ID 12602 in 0 seconds","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/68.0.3440.42 Safari\/537.36","version":"14.0.0.10"}

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

angular.js:14199 searchCallback must be a function
(anonymous) @ angular.js:14199
DevTools failed to parse SourceMap: https://cloud.mydomain.xx/apps/contacts/css/vendor/ui-select/select.min.css.map
</details>

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
Wrong repository yes.
@frake65 you need to compile the app, master is not a usable app for nextcloud

**Comment by frake65** [comment]
Nice answer and thank you for your time - but a little hint would help on how to "compile the app".
Thanks!

**Comment by skjnldsv** [comment]
@frake65 the instructions are in the readme on the contacts repo.
https://github.com/nextcloud/contacts/blob/master/README.md#nightly-builds
https://github.com/nextcloud/contacts/blob/master/README.md#building-the-app
