### ISSUE TITLE
Contact link on login page

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#10235]
It would be nice if there would be a configurable Contact link on login page like legal notice and privacy policy.

So you can link it to a contact form or directly with mailto-link.

@MorrisJobke

**Comment by MorrisJobke** [comment]
@nextcloud/theming Does this make sense?

cc @jospoortvliet for the GDPR stuff

**Comment by juliushaertl** [comment]
We should not add more and more links to the theming app. It would be much better if we could extend the external sites app to just add links to the login page. Then we would have the flexibility of adding any number of links and those would not be limited in their use.

**Comment by MorrisJobke** [comment]
@michag86 Could you open this as feature request in https://github.com/nextcloud/external? Thanks
