### ISSUE TITLE
Calender - all shares invalid?

### ISSUE THREAD

**Issue by MBadberg** [nextcloud/server#10232]
### Steps to reproduce
1.Admins creates a few Calendars and share it with a few groups
2.on console type: sudo -u www-data php occ dav:remove-invalid-shares
3. All shared calenders are gone and you have to share it again.

Either this means that all shares are always broken, or the command also removes healthy shares.

Can anyone reproduce this behavior?
I found nothing similar at the issues...
Nextcloud version: 13.0.4.0
latest calendar app
Ubuntu 16.04 LTS
Apache/2.4.18 (Ubuntu)
PHP7.0

**Comment by MorrisJobke** [comment]
cc @rullzer @georgehrke

**Comment by skjnldsv** [comment]
Bump

**Comment by georgehrke** [comment]
@MBadberg Can you still reproduce this issue?

What version of the calendar app did you use to create the shares?

**Comment by georgehrke** [comment]
Also, did you use any user-backend like LDAP, etc.?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
