### ISSUE TITLE
Cannot download PDF files in Chromium

### ISSUE THREAD

**Issue by justin-sleep** [nextcloud/server#10239]
### Steps to reproduce
1. Open Chromium
2. Navigate to your Nextcloud server
3. Attempt to download a PDF file

### Expected behaviour
A file download should be initiated.

### Actual behaviour
Nothing, just a white screen.  In Firefox, the download works as expected.

### Server configuration

**Operating system**:
Gentoo Linux

**Web server:**
Nginx

**Database:**
PostgreSQL 9.6

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
13.0.5 RC1

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - announcementcenter: 3.2.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - caniupdate: 0.1.2
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.0
  - encryption: 2.0.0
  - external: 3.0.3
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_automatedtagging: 1.3.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.2
  - news: 12.0.4
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - ransomware_protection: 1.1.1
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - socialsharing_email: 1.0.3
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - user_external: 0.4
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "quarterfull.com",
            "cloud.quarterfull.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/quarterfull.com\/cloud",
        "dbtype": "pgsql",
        "version": "13.0.5.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "appstore.experimental.enabled": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "forcessl": true,
        "defaultapp": "files",
        "enable_avatars": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "htaccess.RewriteBase": "\/cloud",
        "updater.release.channel": "beta",
        "debug": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
```
</details>

**Are you using external storage, if yes which one:** No.

**Are you using encryption:** Yes.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:**
Chromium 67

**Operating system:**
Arch Linux

#### Web server error log
Nothing is written to the error log when the file is accessed.

#### Nextcloud log (data/nextcloud.log)
Nothing is printed except for admin_audit messages about the files being accessed.

#### Browser log
<details>
<summary>Browser log</summary>

```
Resource interpreted as Document but transferred with MIME type application/pdf: <PDF URL>
```
</details>

**Comment by stratege1401** [comment]
with my chrome, when i directly select a pdf files, it get opened in clear view, witch is the normal behavior.
When specificly asking to download, it just works.

I beleive it is a chrome error, not a nextcloud error.

**Comment by stratege1401** [comment]
you can try to modify chrome pdf option:    chrome://settings/content/pdfDocuments

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.

**Comment by stratege1401** [comment]
@MorrisJobke Very sorry. Seems i never get back to you... The error was fixed temporary playing with options. 

latest chrome version 71.0.3578.98 (Build officiel) (64 bits) works perfectly fine without tweaking the option.

this was chrome related

**Comment by MorrisJobke** [comment]
@stratege1401 Thanks for the feedback 👍
