### ISSUE TITLE
different quantity of users and files between webinterface and console

### ISSUE THREAD

**Issue by familyman-131** [nextcloud/server#10244]
### Steps to reproduce
1. fresh install NC13
2. register 5 users (plus admin at setup)
3. upload files for a few days
4. run #php occ files:scan --all

### Expected behaviour
data same as at page /settings/admin/serverinfo
Storage
Users: 5
Files: 13672

### Actual behaviour
Scanning files for 6 users
Starting scan for user 1 out of 6 (user1)
Starting scan for user 2 out of 6 (user2)
Starting scan for user 3 out of 6 (user3)
Starting scan for user 4 out of 6 (user4)
Starting scan for user 5 out of 6 (adminuser)
Starting scan for user 6 out of 6 (user5)

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 1307    | 11810 | 00:00:19     |
+---------+-------+--------------+

### Server configuration

**Operating system:** Debian 9.5

**Web server:** nginx/1.14.0

**Database:** 10.2.16-MariaDB

**PHP version:** PHP 7.1.18-1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-13.0.4.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.1.0
  - comments: 1.3.0
  - dav: 1.4.7
  - deck: 0.4.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mindmaps: 0.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - registration: 0.4.2
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_external_gdrive
  - files_pdfviewer
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain1.com",
            "domain2.ua"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/domain1.com",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "maintenance": false,
        "updater.release.channel": "stable"
    }
}

```
</details>

**Are you using external storage, if yes which one:** iscsi for /data folder

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by stratege1401** [comment]
Actually, #7926 is totally related to this, but was pass to @blizzz @MorrisJobke @icewind1991 and closed.

Seem it was lost in traslation or in a deep black hole and time travelled..

**Comment by MorrisJobke** [comment]
> Scanning files for 6 users

Those are the user related files. We also have files in the appdata folder where cached assets of CSS and JS are stored. They will most likely show up in the server info stats as well. From my side this looks fine how it is as of now.

cc @rullzer @nickvergessen @icewind1991 Opinions?

**Comment by familyman-131** [comment]
it would be perfect if you make some tip in webinterface, or in the console output
so the newcomers will understand which digits are true, and which are wrong

**Comment by ChristophWurst** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen.
