### ISSUE TITLE
Calendar broken since update from ownc 9.1 to 10.0_beta

### ISSUE THREAD

**Issue by okias** [nextcloud/server#1025]
```json
{
    "app": "webdav",
    "level": 4,
    "message": "Exception: {\"Message\":\"An exception occurred while executing 'SELECT `id`, `uri`, `lastmodified`, `etag`, `calendarid`, `size`, `calendardata`, `componenttype`, `classification` FROM `oc_calendarobjects` WHERE (`calendarid` = ?) AND (`uri` = ?)' with params [\\\"1\\\", \\\"0f84a47c-5cc9-445d-9f01-2c86c15f8b10.ics\\\"]:\\n\\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'classification' in 'field list'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\InvalidFieldNameException\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Connection.php(836): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'SELECT `id`, `u...', Array)\\n#2 \\/var\\/www\\/nextcloud\\/htdocs\\/lib\\/private\\/DB\\/Connection.php(188): Doctrine\\\\DBAL\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array, NULL)\\n#3 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Query\\/QueryBuilder.php(206): OC\\\\DB\\\\Connection->executeQuery('SELECT `id`, `u...', Array, Array)\\n#4 \\/var\\/www\\/nextcloud\\/htdocs\\/lib\\/private\\/DB\\/QueryBuilder\\/QueryBuilder.php(141): Doctrine\\\\DBAL\\\\Query\\\\QueryBuilder->execute()\\n#5 \\/var\\/www\\/nextcloud\\/htdocs\\/apps\\/dav\\/lib\\/CalDAV\\/CalDavBackend.php(537): OC\\\\DB\\\\QueryBuilder\\\\QueryBuilder->execute()\\n#6 \\/var\\/www\\/nextcloud\\/htdocs\\/apps\\/dav\\/lib\\/CalDAV\\/Calendar.php(168): OCA\\\\DAV\\\\CalDAV\\\\CalDavBackend->getCalendarObject('1', '0f84a47c-5cc9-4...')\\n#7 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Tree.php(76): OCA\\\\DAV\\\\CalDAV\\\\Calendar->getChild('0f84a47c-5cc9-4...')\\n#8 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(903): Sabre\\\\DAV\\\\Tree->getNodeForPath('calendars\\/uzivatel...')\\n#9 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/CalDAV\\/Plugin.php(605): Sabre\\\\DAV\\\\Server->getPropertiesForPath('calendars\\/uzivatel...', Array)\\n#10 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/CalDAV\\/Plugin.php(236): Sabre\\\\CalDAV\\\\Plugin->calendarQueryReport(Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport))\\n#11 [internal function]: Sabre\\\\CalDAV\\\\Plugin->report('{urn:ietf:param...', Object(Sabre\\\\CalDAV\\\\Xml\\\\Request\\\\CalendarQueryReport), 'calendars\\/uzivatel...')\\n#12 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#13 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(716): Sabre\\\\Event\\\\EventEmitter->emit('report', Array)\\n#14 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpReport(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#15 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#16 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:REPORT', Array)\\n#17 \\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#18 \\/var\\/www\\/nextcloud\\/htdocs\\/apps\\/dav\\/lib\\/Server.php(176): Sabre\\\\DAV\\\\Server->exec()\\n#19 \\/var\\/www\\/nextcloud\\/htdocs\\/apps\\/dav\\/appinfo\\/v2\\/remote.php(29): OCA\\\\DAV\\\\Server->exec()\\n#20 \\/var\\/www\\/nextcloud\\/htdocs\\/remote.php(164): require_once('\\/var\\/www\\/nextcloud\\/...')\\n#21 {main}\",\"File\":\"\\/var\\/www\\/nextcloud\\/htdocs\\/3rdparty\\/doctrine\\/dbal\\/lib\\/Doctrine\\/DBAL\\/Driver\\/AbstractMySQLDriver.php\",\"Line\":71,\"User\":\"uzivatel\"}",
    "method": "REPORT",
    "remoteAddr": "186.9.12.13",
    "reqId": "4RsVBm5CZTbywN7vH8MV",
    "time": "2016-08-23T14:23:34+00:00",
    "url": "/remote.php/dav/calendars/uzivatel/defaultcalendar/",
    "user": "uzivatel"
}
```

Actual version 10.0_rc
PHP 5.6 & 7 tested
10.0.26-MariaDB

I can see calendars, I cannot synchronize and load entries.

**Comment by LukasReschke** [comment]
Please fill out the issue template and provide the table layout of `oc_calendarobjects`

**Comment by okias** [comment]
```
oc_calendarobjects

Column	Type	Null	Default	Comments
id	bigint(20)	No 	 	 
calendardata	longblob	Yes 	NULL 	 
uri	varchar(255)	Yes 	NULL 	 
calendarid	int(10)	No 	 	 
lastmodified	int(10)	Yes 	NULL 	 
etag	varchar(32)	Yes 	NULL 	 
size	bigint(20)	No 	 	 
componenttype	varchar(255)	Yes 	NULL 	 
firstoccurence	int(10)	Yes 	NULL 	 
lastoccurence	int(10)	Yes 	NULL 	 
uid	varchar(255)	Yes 	NULL 	 
```

**Comment by tcitworld** [comment]
The `classification` column should exist on both oC 9.1 and NC 10.

**Comment by okias** [comment]
maybe some bug while upgrading to oC 9.1, can I somehow run "update" to fill it?

**Comment by okias** [comment]
> Update 3rd-party app: news
> dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB':
> 
> SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists
> Drop old database tables
>  Done                                              
>  31/31 [============================] 100%         
> Remove old (< 9.0) calendar/contact shares
>  Done                                              
>  4/4 [============================] 100%           
> 
I wonder if this error can cause not updated oc_calendarobjects table..

**Comment by Cypouz** [comment]
Same problem here, with the same exception on oc_addressbooks too. Is it related?...

**Comment by nickvergessen** [comment]
The question is, why is it trying to "create" the table instead of "update"

**Comment by Cypouz** [comment]
The same problem of oc_addressbooks exception on every update is here: https://github.com/nextcloud/server/issues/761

**Comment by gmat** [comment]
same problem for me from 9.0.x to 10.0.1 
I add the missing column with this sql statement  
`alter table oc_calendarobjects add classification int(10) unsigned DEFAULT 0;`

Hope that could help

**Comment by okias** [comment]
@gmat : and calendar is fully functional after this change?

**Comment by gmat** [comment]
@okias : yes. No more 500 error. 
In apps/dav/appinfo/database.xml the default value is 0. With this, all the past events are visible to people in a shared calendar, just like before the upgrade. So that's fine for me.

**Comment by nickvergessen** [comment]
@okias do you still have this problem?

If so it would be nice, if you can run the following query:
```sql
SELECT * FROM `oc_appconfig` WHERE `appid` = 'dav'
```

Also I just saw, that you are the same reporter as in #761
#761 should be the reason why you face this issue here.

Instead of an update your instance tried to install, because of #761 
Install failed because the table does already exist.
But table is not updated, because we only try to install and don't update, so of course the new column is missing.

**Comment by okias** [comment]
> SELECT * FROM `oc_appconfig` WHERE `appid` = 'dav';
Empty set (0.00 sec)

**Comment by okias** [comment]
Yes, it seems to be fixed.

Thank you guys!!!

**Comment by nickvergessen** [comment]
@okias can you still execute my query and post the result? This seems to happen every now and then and I want to find the root cause.

**Comment by Cypouz** [comment]
I don't know if it could help you to find the root cause, but just before searching for fixing this problem, I also had to manually set all "remote_" entry in oc_appconfig as suggested here : https://github.com/owncloud/core/issues/23610 Same problem of update in tables?

**Comment by okias** [comment]
@nickvergessen check my previous post, there is executed your query

**Comment by nickvergessen** [comment]
Oh, empty result. Didn't see that. But that certainly helps to reproduce the issue. Now I can easily generate the error as well.

The only question is, why you ended up with it being empty.
Do you recall which version you originally installed and which versions you updated to/from?

**Comment by Cypouz** [comment]
Equally empty by my side. The initial installed version of ownCloud is 4.5 or 5, which version I update from.

**Comment by okias** [comment]
I did ugly update.

I've been updating to 10.0_beta from some 9.1, which has been unsupported at that time (only upgrade from 9.0.x has been OK).

Anyway, I had problem with updating since 8.x -> 9.x, it failed always with problem. I had to manually remove old calendar tables. But calendar worked at least.

**Comment by okias** [comment]
after updating from 10.0.0 to 10.0.1 it throws

dav: An exception occurred while executing 'CREATE TABLE `oc_addressbooks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `principaluri` VARCHAR(255) DEFAULT NULL, `displayname` VARCHAR(255) DEFAULT NULL, `uri` VARCHAR(255) DEFAULT NULL, `description` VARCHAR(255) DEFAULT NULL, `synctoken` INT UNSIGNED DEFAULT 1 NOT NULL, UNIQUE INDEX addressbook_index (`principaluri`, `uri`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_addressbooks' already exists

**Comment by nickvergessen** [comment]
Did you also restore a backup at some point in time?

**Comment by nickvergessen** [comment]
I wrote a little script that should solve the problem:
https://gist.github.com/nickvergessen/c83981bafbbe55e3cf5bde09b901cfcf

Please download it, put into the root of your Nextcloud, run it once and delete it afterwards.

**Comment by ezraholm50** [comment]
@nickvergessen How would one run that php script? just going to https://domain.com/index.php/repair-appconfig.php ?

Else how would I run those mysql commands exactly?

I tried a lot of combinations running the above commands but they all result in errors that the table's dont exists.

**Comment by ezraholm50** [comment]
Anyone?

**Comment by nickvergessen** [comment]
Sorry, I was quite busy last week, so this slipped through...

What is the error you are getting? Can you run this script: https://gist.github.com/nickvergessen/94b57082a5ab83e47bbbd1bef6d13f66
It should help to generate a list of queries for you to execute.

**Comment by ezraholm50** [comment]
@nickvergessen No problem the errors are listed here https://help.nextcloud.com/t/calendar-broke-after-update-to-10-0-1/5272

So forgive me for my ignorance but I upload that scipt to the root folder and visit the url right?
Thanks for your help!

**Comment by nickvergessen** [comment]
Well, seems like the table holding the calendar events is missing for you. Something went wrong on your database update? Anyway, my advice would be to restore your last working backup in a test environment and copy the table from there.

**Comment by ezraholm50** [comment]
He he... there is none... any advice on that? Or how do I delete all the entries en recreate the tables? Thanks for the help @nickvergessen

**Comment by nickvergessen** [comment]
@ezraholm50 manipulate the `oc_appconfig` database table and set the `configvalue` for `appid = 'dav' AND configkey = 'installed_version'` to a lower version then you have currently. Afterwards an update should be triggered which generates the missing tables.

**Comment by ezraholm50** [comment]
@nickvergessen you are the shizznit!!! Finally have a working calendar again, much appreciated!

**Comment by jospoortvliet** [comment]
@nickvergessen is now officially the shizznit... awesome
