### ISSUE TITLE
hello. Hey. sorry for my English. there was such a problem. when connecting through a desktop client, the differentiation of access to folders works. When connecting through the web interface, access rights do not work and there is access to all resources

### ISSUE THREAD

**Issue by arvium** [nextcloud/server#10257]

**Comment by arvium** [comment]
Hey. sorry for my English. there was such a problem. when connecting through a desktop client, the differentiation of access to folders works. When connecting through the web interface, access rights do not work and there is access to all resources

**Comment by arvium** [comment]
13.0.4

**Comment by stratege1401** [comment]
Hello,

- first, please, create short, clear title like: folder acces problem
- secondary: at last, try to give you server info and nextcloud info

Now, this is more looking like:
- a bad apache2 configuration
- a misunderstanding of the way nextcloud synch app or web interfaces works
- worst ( like a total screw-up :) )

You may want to try using the https://help.nextcloud.com/ community i( even in your native tongue ) to reach more help.

Remember, github is developers oriented.

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Thanks @stratege1401 for the good help here 👍
