### ISSUE TITLE
Add build instructions where necessary (like Updatenotifications app which needs make)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#10267]
Because currently no one knows it needs `make`.

cc @skjnldsv @MorrisJobke  as discussed. We should have a readme in the app folder, or have it in the normal readme. cc @blizzz

**Comment by skjnldsv** [comment]
Closing in favour of https://github.com/nextcloud/documentation/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+author%3Askjnldsv

**Comment by jancborchardt** [comment]
So is this covered by the "Building frontend code" part in the readme? https://github.com/nextcloud/server#building-front-end-code-

Cause it should be in the readme directly too for quick access, not only in the documentation.
