### ISSUE TITLE
Inner exception is lost during class injection creating a misleading error message

### ISSUE THREAD

**Issue by PanCakeConnaisseur** [nextcloud/server#10263]
During instantiation of a class during injection if the queried class (or a class inside it) throws an exception this exception is not propagated up and lost.  Instead a misleading error message similar to 

>{index} Exception: {"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve db! Class db does not exist","Code":0,"Trace":"#0 \/var│
Ju│\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(118): OC\\AppFramework\\Utility\\SimpleContainer->resolve('db')\n#1 \/var\/www\/nextcloud\/lib\/private\/ServerConta│
Ju│iner.php(132): OC\\AppFramework\\Utility\\SimpleContainer->query('db')\n#2 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(74): OC\\ServerContainer->query('db'│
Ju│)\n#3 \/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(97): OC\\AppFramework\\Utility\\SimpleContainer->buildClass(Object(ReflectionClass))\n#4 \/var\/www\/next│
Ju│cloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php(118): OC\\AppFramework\\Utility\\SimpleContainer->resolve('OCA\\\\UserBackend...')\n#5 \/var\/www\/nextcloud\/lib\/private\/Ser│
Ju│verContainer.php(132): OC\\AppFramework\\Utility\\SimpleContainer->query('OCA\\\\UserBackend...')\n#6 \/var\/www\/nextcloud\/apps\/user_backend_sql_raw\/lib\/AppInfo\/Application.php(56): OC\│
Ju│\ServerContainer->query('OCA\\\\UserBackend...')\n#7 \/var\/www\/nextcloud\/apps\/user_backend_sql_raw\/appinfo\/app.php(21): OCA\\UserBackendSqlRaw\\AppInfo\\Application->__construct()\n#8 \│
Ju│/var\/www\/nextcloud\/lib\/private\/legacy\/app.php(245): require_once('\/var\/www\/nextcl...')\n#9 \/var\/www\/nextcloud\/lib\/private\/legacy\/app.php(154): OC_App::requireAppFile('user_bac│
Ju│kend_sq...')\n#10 \/var\/www\/nextcloud\/lib\/private\/legacy\/app.php(127): OC_App::loadApp('user_backend_sq...')\n#11 \/var\/www\/nextcloud\/lib\/private\/legacy\/user.php(131): OC_App::loa│
Ju│dApps(Array)\n#12 \/var\/www\/nextcloud\/lib\/base.php(729): OC_User::setupBackends()\n#13 \/var\/www\/nextcloud\/lib\/base.php(1081): OC::init()\n#14 \/var\/www\/nextcloud\/index.php(40): re│
Ju│quire_once('\/var\/www\/nextcl...')\n#15 {main}","File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","Line":103}

is thrown. The class `Db`exists (not `db` as the error message erroneously reports). This happens [in the second branch](https://github.com/nextcloud/server/blob/23785d108d6f1a5641bad2cf91ae3c696aac0ef0/lib/private/AppFramework/Utility/SimpleContainer.php#L81) of `SimpleContainer.php` in the `query()` method. Imho the exception should be rethrown.

# Screenshot of debugger state
![screenshot_20180717_033324](https://user-images.githubusercontent.com/17473656/42791708-45bec79e-8972-11e8-99ec-115b148d3a1f.png)

On line 68 you can see the thrown exception, but still on line 72 the second branch is chosen just because the class name (Db) is known. But returning the actual exception message is much more useful than simply returning the name of the immediate class name.

# Steps to reproduce
I don't have a minimal example but one way would be to install the [User Backend Raw SQL app](https://apps.nextcloud.com/apps/user_backend_sql_raw) and set `db_type` in the [configuration](https://github.com/PanCakeConnaisseur/user_backend_sql_raw#configuration) to e.g. `mysql` which is not a supported string, which leads to the above error.

# Versions
Tested with Nextcloud 13.0.4 and 13.0.5 RC 2 Build:2018-07-16T23:01:35+00:00 43785cf1a80892e35a133b76a087eb52d19d4060.

# Proposed solution
I don't understand the implementation of dependency injection in Nextcloud completely, but I think all  thrown exceptions should be rethrown.

**Comment by PanCakeConnaisseur** [comment]
@nextcloud-bot: not even close :)

**Comment by MorrisJobke** [comment]
> is thrown. The class Dbexists (not db as the error message erroneously reports). This happens in the second branch of SimpleContainer.php in the query() method. Imho the exception should be rethrown.

cc @nickvergessen @rullzer @ChristophWurst didn't we talked about this in the past? Somehow it wasn't too easy to properly detect it, because the DI container of the app has thrown in and then the server one does it as well. So we want to log the app one, but the server one is only available. :/

**Comment by skjnldsv** [comment]
:trumpet:

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
