### ISSUE TITLE
Polishing fixes for Favorites and Shares submenus

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#10261]
- [ ]  The highlight bar of the subentries is floating in mid-air. Should also be on the left side of the viewport. (We need to take the padding from the li and instead add it to the a)
- [x] Even if the menu is collapsed, the li elements are invisible but clickable. (Collapse the share menu and hover/click below it)
- [ ] That’s also a problem when you tab through the elements with a keyboard. They are invisible but seem to receive focus
- [ ] The triangle arrow for collapsing the folder should only show when the folder entry itself is hovered/focused, _not_ when the subentries are hovered (cause the animation is very distracting when wanting to click a subentry)
- [ ] When navigating via keyboard, having focus on the collapse/expand function should visibly show the arrow, just like when you hover

@skjnldsv @juliushaertl @MorrisJobke

**Comment by MorrisJobke** [comment]
@jancborchardt @skjnldsv Move to 15 and maybe we can backport fixes later

**Comment by skjnldsv** [comment]
>  That’s also a problem when you tab through the elements with a keyboard. They are invisible but seem to receive focus

Then we need to drop the animation :)
>  The highlight bar of the subentries is floating in mid-air. Should also be on the left side of the viewport. (We need to take the padding from the li and instead add it to the a)

Looks really weird :/
![peek 06-11-2018 17-43](https://user-images.githubusercontent.com/14975046/48079405-94835800-e1eb-11e8-85a6-9d65df11d072.gif)

**Comment by jancborchardt** [comment]
> Then we need to drop the animation :)

Is there no middle ground? Like applying `display: none;` through JS afterwards`? Yes I know it’s not clean and CSS only, but UX and accessibility is more important than underlying code. And right now it’s really not good for people who can not use a mouse.

> Looks really weird :/

This looks great actually. No floating blue bars in mid-air. :tada: Could you open a pull request?

**Comment by jancborchardt** [comment]
Another idea to make the subentries less weird: Since we only have one level in Files anyway, we don’t need to indent them:
![screenshot from 2018-11-07 12-12-45](https://user-images.githubusercontent.com/925062/48128351-7fa7d280-e286-11e8-95d2-a6b5d8d04267.png) ![screenshot from 2018-11-07 12-12-19](https://user-images.githubusercontent.com/925062/48128353-80406900-e286-11e8-9e28-e59eb4190025.png)

This is also how normal file managers like Finder on macOS or Nautilus on GNOME/Ubuntu do it. Then we don’t have the floating bars either.

And yes I know, it’s adjustment from the standard, but a standard is never set in stone. ;) In the Mail app for example we do it like that already as it would be super weird to have the Inbox, Sent, Trash etc of an account indented already.

**Comment by skjnldsv** [comment]
> Yes I know it’s not clean and CSS only, but UX and accessibility is more important than underlying code.

And that's how we got to the point where no one knows how to maintain our server core code anymore! :)
Nope, clean code and maintainability is always the top priority. Otherwise you end up with crazy complicated thing and poor performances just to have a proper ux. :confused: 

Until we have things properly written in a way css and js are properly working together, I don't want to add separate functions that everyone will forget and overwrite later on. :disappointed: 

Though, your idea of putting everything flat again is not bad at all. The best would be to find a way to indicate that the sub-entries belong to a main one. Indenting was one of the possibilities, but I'm sure we can find others? What about a tiny left border ? :thinking:

**Comment by jancborchardt** [comment]
Take another look at what I posted above, and also now with added comparison and borders for separation.

The left has whitespace to separate the groups – maybe it needs more whitespace. The light border on the right makes it very clear, but looks too boxy for Nextcloud and not light.

![app navigation mockups](https://user-images.githubusercontent.com/925062/48129154-f1811b80-e288-11e8-9f86-f27c330bfdb4.png)

**Comment by juliushaertl** [comment]
@jancborchardt I think the additional spacing works quite well here with removing the indentation. However I don't think this is something for all submenus like in the news/mail app. In files the Favorites/Shares work more as a headline. If we have a folder hierarchy indetation is quite important I think.

**Comment by MorrisJobke** [comment]
Let's move this to 16 and maybe backport some fixes.

**Comment by jancborchardt** [comment]
cc @jenniferpiperek on this regarding mockups and design system exploration. :)

**Comment by MorrisJobke** [comment]
Cleared the milestone.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
