### ISSUE TITLE
Probleme with the preview of new picture

### ISSUE THREAD

**Issue by WikiIUT** [nextcloud/server#10278]
Hello,  #HelpWanted

My new picture don't have a preview, and it necessary to download for see the picture, i have try regenerat the preview with previewgenerator but don't run,

When running whit www user :
`php occ preview:generate-all`
the app's stop and the error is : 

> 2018-07-17T21:18:26+00:00
> 2018-07-17T21:18:26+00:00   [OCP\Files\NotPermittedException]
> 2018-07-17T21:18:26+00:00   No create permission for folder
> 2018-07-17T21:18:26+00:00
> 2018-07-17T21:18:26+00:00

System is UCS with NC13.04
using :
AD integration with Windows Server 2012R2
I have test, modify the permission to the folder to 777, and not resolve the problem,

Thanks for the read,

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Also just setting the permission of one folder could be not enough. Try to set the permission recursively and only for the owner. Changing the owner then to "www-data" (or whatever user your web server is running at) should fix the permission problem.

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
