### ISSUE TITLE
Useradministration grows over browserboundaries and creates vertical scrollbar

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#10287]
### Steps to reproduce
Create div with width=100%
Set margin/padding
See scrollbar

### Expected behaviour
app-content container does not grow.

### Actual behaviour
When using container like a div, which grows to take all the available space, the app-content container grows, and breaks out of the browsers boundaries. Content is "lost" because the user needs to scroll vertically on the page. The containersize should be fixed while the browserwindow is not resized.

This also affects existing columns, those are lost in the scrollbar.

This problem is especially noticable on an 4:3 Monitor with a low Resolution of 1240x1024. (But also happens on 1920x1080)

**Nextcloud version:**

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

@newhinton Do you have a screenshot for what you are experiencing?

**Comment by MorrisJobke** [comment]
> Maybe this behaviour is more or less intended, you can't reduce the size of a column indefinitely, so they may need to scroll, but in this case there should be a clear visible effect to make sure its not missed (like fading to white if its cut off)

Exactly ... it is just a quite wide table with all the options enabled. We look into ways to improve it, but as of now this is the way it was planned. Let me close this for now, but we are aware of the experience here.

cc @skjnldsv @jancborchardt because we talked about the user management recently as well.

**Comment by newhinton** [comment]
![42930678-f55ce858-8b3d-11e8-95c5-6f1f08a6b3ce](https://user-images.githubusercontent.com/25279821/42932735-653ffd72-8b43-11e8-9b91-d9a937ff2f2c.png)


@MorrisJobke Would this be an improvement? I am currently in the process of understanding how the view works there, so i could try to implement this. I dont know if you already have other plans or ideas, but if you want i can take a shot at this, just say so ;)
