### ISSUE TITLE
Inconsistent links from calendar, contacts and files

### ISSUE THREAD

**Issue by wetsixteen** [nextcloud/server#1028]
### Steps to reproduce
1. Rewrite domain.tld to www.domain.tld
2. set 'overwritehost' => 'domain.tld',
3. Acquire links from calendar, contacts and files via 'settings' and displayed url
4. compare links
### Expected behaviour

All three urls should be identical in $scheme://$host/remote.php/..., only the ending should differ
### Actual behaviour

contacts and calendar show the actual url, files somehow takes the 'overwritehost' setting
Example: 
https://domain.tld/remote.php/webdav
https://www.domain.tld/remote.php/dav/principals/users/username/
### Server configuration

**Operating system:** Debian Jessie

**Nextcloud version:** Nextcloud 9.0.53 (stable)**

**Web server:** nginx/1.6.2
<details>
<summary>

server config</summary>

server {
    server_name domain.tld;
    listen *:80;
    listen [::]:80;
    listen *:443 ssl;
    listen [::]:443 ssl;
    location / {
        return 301 $scheme://www.domain.tld$request_uri;
    }
} 

</details>
**The content of config/config.php:**
<details>
<summary>

Config report</summary>

> { 
>     "system": {
>         "instanceid": "...",
>         "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
>         "secret": "**_REMOVED SENSITIVE VALUE**_",
>         "trusted_domains": [
>             "domain.tld",
>             "www.domain.tld"
>         ],
>         "datadirectory": "\/var\/cloud_data",
>         "dbtype": "mysql",
>         "version": "9.0.53.0",
>         "dbname": "ocdb",
>         "dbhost": "localhost",
>         "dbtableprefix": "oc_",
>         "dbuser": "**_REMOVED SENSITIVE VALUE**_",
>         "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
>         "logtimezone": "UTC",
>         "installed": true,
>         "overwritehost": "domain.tld",
>         "mail_smtpmode": "smtp",
>         "mail_smtphost": "127.0.0.1",
>         "mail_smtpport": "25",
>         "mail_smtptimeout": 10,
>         "mail_smtpauthtype": "LOGIN",
>         "mail_domain": "domain.tld",
>         "mail_from_address": "cloud",
>         "memcache.local": "\OC\Memcache\APCu",
>         "default_language": "en",
>         "defaultapp": "files",
>         "knowledgebaseenabled": false,
>         "allow_user_to_change_display_name": true,
>         "enable_avatars": true,
>         "trashbin_retention_obligation": "auto",
>         "versions_retention_obligation": "auto",
>         "remember_login_cookie_lifetime": 1296000,
>         "session_lifetime": 86400,
>         "session_keepalive": true,
>         "skeletondirectory": "\/var\/www\/cloud\/core\/skeleton",
>         "appcodechecker": false,
>         "updatechecker": true,
>         "has_internet_connection": true,
>         "check_for_working_webdav": true,
>         "check_for_working_htaccess": true,
>         "check_for_working_wellknown_setup": true,
>         "config_is_read_only": false,
>         "log_type": "owncloud",
>         "logfile": "\/var\/cloud_data\/cloud.log",
>         "loglevel": 3,
>         "logdateformat": "F d, Y H:i:s",
>         "debug": true,
>         "log_query": false,
>         "cron_log": true,
>         "mail_smtpauth": 1,
>         "mail_smtpname": "**_REMOVED SENSITIVE VALUE**_",
>         "mail_smtppassword": "**_REMOVED SENSITIVE VALUE**_",
>         "enable_previews": true,
>         "preview_max_x": 2048,
>         "preview_max_y": 2048,
>         "preview_max_scale_factor": 10,
>         "preview_max_filesize_image": 50,
>         "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
>         "enabledPreviewProviders": [
>             "OC\Preview\PNG",
>             "OC\Preview\JPEG",
>             "OC\Preview\GIF",
>             "OC\Preview\BMP",
>             "OC\Preview\XBitmap",
>             "OC\Preview\MP3",
>             "OC\Preview\TXT",
>             "OC\Preview\MarkDown",
>             "OC\Preview\Illustrator"
>         ],
>         "asset-pipeline.enabled": false,
>         "blacklisted_files": [
>             ".htaccess"
>         ],
>         "cipher": "AES-256-CFB",
>         "filesystem_check_changes": 0,
>         "maintenance": false,
>         "theme": "",
>         "appstore.experimental.enabled": true,
>         "updater.release.channel": "stable"
>     }
> } >
> </details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Google Chrome   51.0.2704.106 (Official Build) (64-bit)
**Operating system:**
MacOSX 10.11.6

**Comment by MorrisJobke** [comment]
> Nextcloud version: Nextcloud 9.0.53 (stable)**

Should be fixed in a more recent version. Haven't seen any issues in the close past. Closing for now.
