### ISSUE TITLE
Password Recovery screen only prompts for password once

### ISSUE THREAD

**Issue by hailthemelody** [nextcloud/server#103]
### Steps to reproduce
1. Send a password reset request
2. Open link from email client

### Expected behaviour
The password should be entered twice to verify it is entered correctly.

### Actual behaviour
The password is only prompted to be entered once.

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:** Apache2.4.7

**Database:** MySQL

**PHP version:** 5.5.9

**Nextcloud version:** 9.0.50 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tar.gz from website

**Signing status (Nextcloud 9.0 and above):** unsure

```
No errors have been found.
```

**List of activated apps:**

```
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - provisioning_api: 0.4.1
  - updatenotification: 0.1.0
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.0.50.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN"
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)

n/a

### Client configuration
**Browser:** Chromium

**Operating system:** Debian GNU/Linux 8.4 (jessie)

### Logs

n/a

**Comment by LukasReschke** [comment]
Personally I'd more advocate for having a double input field for changing the mail address instead of a double confirmation field for the password.

The password can simply be reset again using the mail address. But if the mail address is wrong it can't.

Thoughts? cc @nextcloud/designers

**Comment by williambargent** [comment]
@LukasReschke  I agree, If the email is wrong a duplicate/new account will be requested or requires input from admin, however you still have to rely on email being configured (I know some installations which it isn't)

**Comment by MorrisJobke** [comment]
I also don't see an advantage of a second password field. If it doesn't worked out in the first try request another reset 🙈

**Comment by jancborchardt** [comment]
Exactly, we will not require people to put in passwords twice.
