### ISSUE TITLE
Breadcrumbs are abbreviated too soon in FireFox

### ISSUE THREAD

**Issue by Germs2004** [nextcloud/server#10304]
In Chrome, the breadcrumb bar displays the full names of each folder and subfolder.  If I shrink the window too much, the responsive UI will change one of the breadcrumb parent folder names to "..." so that it all fits.  This is great.

In Firefox, however, the breadcrumb bar shrinks the names of some parent folders to "..." even when the window is maximized and has plenty of room.  It seems random which folders will be shrunk and which won't, but it happens every time on those folders.  Some long paths are not shrunk while some medium-length paths are shrunk too soon.

FireFox 61.0.1
Chrome 67.0.3396.99
Nextcloud 13.0.4

**Comment by MorrisJobke** [comment]
@Germs2004 Could you post a screenshot?

**Comment by Germs2004** [comment]
Sure thing.  Here are lots of screenshots comparing Chrome with FireFox.  A good example of shrinking when it shouldn't is the file "FF 1B".  An example of the really odd behavior is "FF 2A" and "FF 2B" because it shrinks in 2A but when I go one folder deeper to 2B, it actually unshrinks.

Chrome Root
![chrome root](https://user-images.githubusercontent.com/5519340/43010403-5ce5deb4-8c0e-11e8-88d4-1649fd4ef011.PNG)

Chrome Trunk
![chrome trunk](https://user-images.githubusercontent.com/5519340/43010404-5cf55808-8c0e-11e8-838a-b8b468c3a0f8.PNG)

Chrome 1A
![chrome 1a](https://user-images.githubusercontent.com/5519340/43010398-5c947754-8c0e-11e8-9aec-0d564f0714d6.PNG)

Chrome 1B
![chrome 1b](https://user-images.githubusercontent.com/5519340/43010400-5cb46370-8c0e-11e8-8a6d-6fab0c3f8bf5.PNG)

Chrome 1B Window Shrunk
![chrome 1b window shrunk](https://user-images.githubusercontent.com/5519340/43010399-5ca25900-8c0e-11e8-8465-c26551297d8e.PNG)

Chrome 2A
![chrome 2a](https://user-images.githubusercontent.com/5519340/43010401-5cc5cfca-8c0e-11e8-82eb-514a8c11eaf0.PNG)

Chrome 2B
![chrome 2b](https://user-images.githubusercontent.com/5519340/43010402-5cd60890-8c0e-11e8-8bb5-e2b4264e33a1.PNG)

FF Root
![ff root](https://user-images.githubusercontent.com/5519340/43010409-5d5b14ae-8c0e-11e8-871e-32ff08523f09.png)

FF Trunk
![ff trunk](https://user-images.githubusercontent.com/5519340/43010410-5d6d1e6a-8c0e-11e8-9446-79c801dd3b4b.png)

FF 1A
![ff 1a](https://user-images.githubusercontent.com/5519340/43010405-5d0390b2-8c0e-11e8-9619-221abfa765d6.png)

FF 1B
![ff 1b](https://user-images.githubusercontent.com/5519340/43010406-5d20d9ce-8c0e-11e8-8ebd-54e4b93146d5.png)

FF 2A
![ff 2a](https://user-images.githubusercontent.com/5519340/43010407-5d348bd6-8c0e-11e8-9d8e-df44516f15d8.png)

FF 2B
![ff 2b](https://user-images.githubusercontent.com/5519340/43010408-5d4bd93a-8c0e-11e8-94ba-c69ec71874bc.png)

**Comment by patricksebastien** [comment]
Happening on Chrome / Windows 10 when using the zoom feature in display setting (_Make everything bigger - Change the size of apps and text on the main display_). There's plenty of horizontal space but the folder structure is not visible (replaced by 3 dots / breadcrumbs). Would like to tackle this, but not sure where to start.

Any ideas?

**Comment by patricksebastien** [comment]
Also happening on Mac - Chrome when using the zoom feature of Chrome:
100%: OK
110%: parent = "..."
125%: OK
etc...

https://streamable.com/rmgv4

**Comment by khaytsus** [comment]
I've also seem the same odd behavior with breadcrumbs..  In my browser (Chrome 89 on Linux) the parent is collapsed until the Chrome window is about 1180 pixels wide.  From 1180 to about 2120 the parent flip-flops between collapse and showing the parent directory name as you make the window larger.  Like there are 'breakpoints' every 10 or 20 pixels or something that seem to affect it.  Then at around 2120 until full width of 3840 (4k monitor) it's always collapsed.  It's very odd.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/21263
