### ISSUE TITLE
Shared folder names are not updated when renamed while sharing is disabled

### ISSUE THREAD

**Issue by Germs2004** [nextcloud/server#10305]
If you rename a shared folder while sharing is disabled, the share name "sticks" and the other users do not see the new name.

1) Log in as User1.
2) With File Sharing enabled, share a folder called "Folder1" with User2.
3) Log in as User2 in a different browser and confirm that you can see Folder1.  All is well so far.
4) In the User1 browser, disable all the sharing settings and remove the File Sharing addon.
5) In the User1 browser, rename Folder1 to Folder2.
6) In the User2 browser, notice that you still see the folder as Folder1.  I can browse that folder and its contents as if it were still named Folder1.  Refreshing doesn't fix it.  Only re-enabling File Sharing will let the other users see the folder's new name.

Nextcloud 13.0.4

**Comment by MorrisJobke** [comment]
That is wanted behavior. Once shared the resulting folder is not renamed anymore as it is part of the namespace of user2 and not a folder name of user1. So once the file is shared the root folder name is part of the recipients folder structure and can't be changed by user1 anymore.
