### ISSUE TITLE
Entire NC server froze (maybe) in maintenance mode while updating apps

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/server#10314]
I have no web browser access to my system right now and don't know how to send diagnostics.

Last night I was using the system to update apps. I don't remember what the order was for sure, I was just clicking the update buttons from the top of the list going down. I did the antivirus file checking app first. I thought that was odd because I thought I disabled that app due to system slowdown issues. It was enabled at the time of update. That one finished and I ran the next update which I don't remember what it was. For some reason, I clicked on what I'm fairly certain was the Collabora update button but the second one wasn't finished yet. That was taking so long that I stopped waiting and started to click other things, but the first thing that I clicked off the apps page resulted in this:
![screenshot from 2018-07-20 10-06-49](https://user-images.githubusercontent.com/28640985/43007561-ae257e5e-8c06-11e8-851a-6a50574ef360.png)

I went to bed hoping it would improve by morning. It didn't. About 12 hours after I rebooted the hardware it runs on and it's still stuck. 

Help?!

**Comment by WNYmathGuy** [comment]
It was the radio app that I was updating second! I can't believe I remembered that.

**Comment by WNYmathGuy** [comment]
@nextcloud-bot bad guess on [#5208](https://github.com/nextcloud/server/issues/5208) [#6175](https://github.com/nextcloud/server/issues/6175) [#5789](https://github.com/nextcloud/server/issues/5789) and [#2650](https://github.com/nextcloud/server/issues/2650) but good guess on [#6536](https://github.com/nextcloud/server/issues/6536) however it wasn't useful for this problem.

**Comment by MorrisJobke** [comment]
> I went to bed hoping it would improve by morning. It didn't. About 12 hours after I rebooted the hardware it runs on and it's still stuck.

Go to the config.php and disable the "maintenance" flag. usually app updates should be done once after another. In Nextcloud 14 we improved to not be able to click multiple in a row.

I will close this for now. If you still have problems with the setup as it is please reach out in the forums for those setup related questions. https://help.nextcloud.com

Thanks for the feedback.

**Comment by WNYmathGuy** [comment]
@MorrisJobke will you be my hero? That solved the problem. 

IT work is similar to war. 

In IT you live in monotony and despair broken by moments of painc & extreme elation. 

In war, you have long periods of boredom broken by short periods of near-death experiences.
