### ISSUE TITLE
Shared Group Folder trouble | double display of files and bypass "Deleted files" bin on delete

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/server#10319]
### Steps to reproduce
1. Admin makes group folder with the web interface.
2. Admin uploads many audiobook files in various formats with the web interface.
3. User uploads rest of files with the web interface.
4. User downloads a local copy on a mobile device with the NextCloud app and listens to files with standard android google music app.
5. user finishes and removes local copy with the NextCloud app.
6. Admin notices their's duplicate files of almost all the audio files.
7. Admin deletes the duplicate entries.
8. The user notices no files remain in the group folder.
9. Admin looks in recycle bin (Deleted files) and notices there aren't any files there.
10. The user sees the file folder's Size field entry as "Pending" a month after the problem and remembers it was screwed up.
11. The user checks the details on the folders data size and finds it's claiming to have -487935471 bytes in it.
12. The admin writes up this report.

### Expected behavior
File entries should never display double entries for single files.

### Actual behavior
Files show double entries for single files and if either entry gets removed the file is deleted without reversibility.

## Server configuration detail

**Operating system:** Linux 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64

**Webserver:** Apache/2.4.18 (cgi-fcgi)

**Database:** mysql 10.0.34

**PHP version:** 7.0.30-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.4 - 13.0.4.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh from 13, but updated regularly.

**Where did you install Nextcloud from:** [Installation on Linux](https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html)

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

This current state doesn't necessarily reflect the state it was in when the trouble was experienced.

```
Enabled:
 - activity: 2.6.1
 - admin_notifications: 1.0.1
 - announcementcenter: 3.2.1
 - apporder: 0.4.1
 - audioplayer: 2.3.1
 - bookmarks: 0.11.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - checksum: 0.4.0
 - circles: 0.14.0
 - comments: 1.3.0
 - contacts: 2.1.5
 - data_request: 1.0.1
 - dav: 1.4.7
 - deck: 0.4.0
 - drawio: 0.8.9
 - drop_account: 0.0.11
 - external: 3.0.3
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_downloadactivity: 1.2.0
 - files_pdfviewer: 1.2.1
 - files_retention: 1.2.0
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - flowupload: 0.0.7
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - groupfolders: 1.2.2
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - metadata: 0.6.0
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - ocsms: 1.13.1
 - password_policy: 1.3.0
 - phonetrack: 0.2.7
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - quota_warning: 1.2.0
 - radio: 0.6.1
 - rainloop: 5.1.0
 - ransomware_protection: 1.1.1
 - registration: 0.4.2
 - richdocuments: 2.0.10
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - socialsharing_diaspora: 1.0.2
 - socialsharing_email: 1.0.3
 - socialsharing_facebook: 1.0.2
 - socialsharing_googleplus: 1.0.2
 - socialsharing_twitter: 1.0.2
 - spreed: 3.2.4
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - telephoneprovider: 1.0.1
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - weather: 1.5.1
 - workflowengine: 1.3.0
Disabled:
 - admin_audit
 - encryption
 - files_antivirus
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "MyExample.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "13.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "theme": "",
    "loglevel": 0,
    "default_language": "en",
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_scale_factor": 10,
    "preview_max_filesize_image": 50,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\Font",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Postscript",
        "OC\\Preview\\StarOffice"
    ],
    "tempdirectory": "\/home\/adminuser\/domains\/MyExample.com\/tmp\/nextcloudtemp",
    "overwrite.cli.url": "https:\/\/MyExample.com"
}
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Operating system:** Ubuntu 16.04 LTS

## Logs

<details><summary>Nextcloud log</summary>

```
I don't want to publicly display my log, but I would give it directly to an insider of NextCloud for analysis. 
```
</details>

**Comment by WNYmathGuy** [comment]
@nextcloud-bot Good guess on [#9523](https://github.com/nextcloud/server/issues/9523) because it was related and helpful but not enough, bad guess on [#1708](https://github.com/nextcloud/server/issues/1708) & [#6092](https://github.com/nextcloud/server/issues/6092) and weird guess on [#9696](https://github.com/nextcloud/server/issues/9696) cause that's me! I hope I wouldn't ask how to solve the same problem twice. :smiley:

**Comment by MorrisJobke** [comment]
Known issue of the group folders app. There is no versions and trashbin support yet.

nextcloud/groupfolders#50
nextcloud/groupfolders#99

Regarding the double entries: Please report this to the group folder repo at https://github.com/nextcloud/groupfolders
