### ISSUE TITLE
Theming admin settings doesn't show set values

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#1032]
The theming app admin settings doesn't show set values.

**Steps to reproduce:**
1. Set a new name/slogan/..
2. Wait for it to be saved
3. Reload the admin page
4. Changes are not shown

This bug was introduced by https://github.com/nextcloud/server/pull/1006, as the Admin settings will get an OC_Defaults instance instead of ThemingDefaults even when the app is already enabled.

**Comment by juliushaertl** [comment]
cc @blizzz @rullzer @nickvergessen

**Comment by rullzer** [comment]
O joy... I'll dive into this.

**Comment by rullzer** [comment]
Ah it gets casted down it seems...
