### ISSUE TITLE
OC_User_IMAP supporting only TLSv1

### ISSUE THREAD

**Issue by lsbbs** [nextcloud/server#10328]
### Steps to reproduce
1. Use OC_User_IMAP for authentication
{imapserver:143/imap/tls/readonly}
2. Disable TLSv1 on the IMAP server remaining TLSv1.1 and TLSv1.2

### Expected behaviour
User can log in

### Actual behaviour
User getting an "Wrong password" error
In the imap server logfile:
TLS handshaking: SSL_accept() failed: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol
With TLSv1 enabled:
TLS, TLSv1 with cipher ECDHE-RSA-AES128-SHA (128
/128 bits)

### Server configuration
'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP',
      'arguments' =>
      array (
        0 => '{imapserver:143/imap/tls/readonly}',
        1 => 'domain1',
        2 => '{imapserver:143/imap/tls/readonly}',
        3 => 'domain2',
      ),
    ),
  ),

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.0.34

**PHP version:**
PHP 7.0.30

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 13.0.2

**Where did you install Nextcloud from:**
Dowload from nextcloud

**Comment by MorrisJobke** [comment]
This is an issue within the user_external app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/apps
