### ISSUE TITLE
Enhance version control to folders

### ISSUE THREAD

**Issue by Simonmicro** [nextcloud/server#10324]
Hi,
because I'm using Nextcloud as central file sharing and backup system I would like to see a additional feature to rollback whole folders, not only some files.
Some toughs for implementation:
-> Actual state is B. Want to rollback a folder to state A - but what if some files of A was deleted? Incomplete rollback? A warning? Or simply "cant rollback"?
-> Allow manual set of rollback-points and name them.*
-> Lets create automatic rollbackpoints - every day, week, moth and so on.*
-> Actual state is D. Want to rollback to state C -> but some files wasn't changed since state A/B, so lets use them.
-> If I start a rollback, set an automatic rollback-point for all affected files.

*Not really necessary, because Nextcloud remember all file version timestapms.

I know thats a huge idea and it will cost a lot of time to implement this - but here it is ;)
Best regards,
Simonmicro

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer @schiessle

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
