### ISSUE TITLE
Internet Explorer 11 can't access background-image

### ISSUE THREAD

**Issue by Charburner** [nextcloud/server#10323]
### Steps to reproduce
1. Open login page with Internet Explorer 11 (I tried Win 8.1 and Win 10)
2. Notice background-image configured via theming app is missing
3. Notice you can't access the image via direct link e.g. https://cloud.domain.tld/apps/theming/loginbackground?v=37

Nextcloud 13.0.4

Internet Explorer Devtools says something like "download has been initiated by css property of type background-image (postponed to continue website processing)".

Anyone else having this problem? It works with Firefox and Edge though.

**Comment by MorrisJobke** [comment]
cc @juliushaertl @skjnldsv

**Comment by Charburner** [comment]
Updated to Nextcloud 13.0.6 and could not reproduce this behaviour > closed

**Comment by roguezombi** [comment]
Good Day
I am having the same issue.
Nextcloud version 13.0.7
Background image appears on Google Chrome, Firefox and MS Edge.
Does not appear on IE 11 - debug shows 
"background-image: url(/index.php/apps/theming/loginbackground?v=22);"
