### ISSUE TITLE
UX / UI: Make upload button more visible on upload enabled shares

### ISSUE THREAD

**Issue by ThomasLeister** [nextcloud/server#10332]
### Steps to reproduce
1. Create upload enabled shared folder and share link to friends / ...
2. Ask non-Nextcloud experienced friends to upload files 

### Expected behaviour
Friends should be able to find upload button quickly

### Actual behaviour
Friends spend too much time to figure out how to upload stuff

### Suggestion
Nextcloud experienced users will find the "Create folder" or "upload file" button quite quickly. Users who are not used to Nextcloud seem to have a hard time figuring out how to upload files, because the UI does not really indicate that at first sight. This has happened to my friends / relatives several times, and it's always frustrating to explain to each single person. They do not expect the file upload in a somehow hidden submenu. Upload should be obvious even to my grandma.

**Better: On upload enabled "via link" shares, display a big, colored button for file upload / folder creation.**

**Comment by MorrisJobke** [comment]
We have an ongoing discussion about the upload button in general and how to integrate it into the sharing page in #4011. Let's join forces on this topic in there.
