### ISSUE TITLE
Admin can not change user password

### ISSUE THREAD

**Issue by htttito** [nextcloud/server#10333]
Hi support !
nextcloud 13.04
system: ubuntu 18.04, apache, php7.2
I can not change the user password in the admin panel.
I can edit the user name, email, all but not the password.
There is no error in the log.....
Any ideas ?

**Comment by htttito** [comment]
No, that's not the Problem, the installation is ca. half a year old, and I am the admin,
but I can not edit it!

**Comment by MariusBluem** [comment]
Can you fill out the whole issue template?

Do you use any external user-directories like LDAP or SAML? What error does appear if you try to change your password?

**Comment by alexara** [comment]
> I can not change the user password in the admin panel.

I have a similar issue: When I seemingly change a user's password, it actually won't be changed but the old password remains valid. I wonder if that's the same case for you. (If not, I may open a new issue)

**Comment by Mannshoch** [comment]
Same Problem. If I click on the Password field the textbox blink and disappear instant. If I click on other Elements like Mail the Textbox work and I'm able to change the content.

## Server configuration detail

**Operating system:** Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.34

**PHP version:** 7.2.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, fileinfo, gd, imagick, imap, intl, json, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, soap, sqlite3, sysvmsg, sysvsem, sysvshm, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - admin_audit: 1.3.0
 - apporder: 0.5.0
 - audioplayer: 2.3.1
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.3
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.4.1
 - password_policy: 1.3.0
 - piwik: 0.4.1
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.5
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - activity
 - deck
 - encryption
 - external
 - mindmaps
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbtableprefix": "oc_",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y.m.d, H:i:s",
    "log_query": false,
    "loglevel": 0,
    "installed": true,
    "maintenance": false,
    "default_language": "de",
    "appstore.experimental.enabled": false,
    "knowledgebaseenabled": true,
    "enable_avatars": true,
    "theme": "",
    "allow_user_to_change_display_name": true,
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "token_auth_enforced": false,
    "auth.bruteforce.protection.enabled": true,
    "mail_smtpdebug": false,
    "trashbin_retention_obligation": "300,auto",
    "versions_retention_obligation": "90, auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "has_internet_connection": true,
    "appstoreenabled": true,
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_scale_factor": 10,
    "preview_max_filesize_image": 2,
    "check_for_working_webdav": true,
    "check_for_working_wellknown_setup": true,
    "check_for_working_htaccess": true,
    "config_is_read_only": false,
    "cron_log": true
}
```
</details>

**Are you using encryption:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Operating system: Ubutu** 

## Logs
<details><summary>Nextcloud log</summary>

```
{"reqId":"W2rWJhhbFlLOKm@bwcnVYwAAABI","level":3,"time":"2018.08.08, 13:38:14","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/user\/sharing","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
{"reqId":"W2rWLBhbFlLOKm@bwcnVcQAAABI","level":3,"time":"2018.08.08, 13:38:20","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/user\/ojsxc","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
{"reqId":"W2rWLS1OdXhRgr1n8tw3SgAAAAk","level":3,"time":"2018.08.08, 13:38:21","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/user\/additional","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
{"reqId":"W2rWNJRUH3sTNAwwI@SoWQAAAAo","level":3,"time":"2018.08.08, 13:38:28","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log - How do I do that?
	

</details>

## Server configuration detail

**Operating system:** Linux 3.10.0-862.9.1.el7.x86_64 #1 SMP Mon Jul 16 16:29:36 UTC 2018 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.34

**PHP version:** 7.2.8
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, fileinfo, gd, imagick, imap, intl, json, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_sqlite, Phar, posix, pspell, soap, sqlite3, sysvmsg, sysvsem, sysvshm, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 13.0.2 - 13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - admin_audit: 1.3.0
 - apporder: 0.5.0
 - audioplayer: 2.3.1
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.1
 - comments: 1.3.0
 - contacts: 2.1.5
 - dav: 1.4.6
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_external: 1.4.1
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - gpxedit: 0.0.8
 - gpxmotion: 0.0.6
 - gpxpod: 2.2.2
 - impersonate: 1.0.4
 - issuetemplate: 0.3.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - mail: 0.8.3
 - nextcloud_announcements: 1.2.0
 - notes: 2.3.2
 - notifications: 2.1.2
 - oauth2: 1.1.0
 - ojsxc: 3.4.1
 - password_policy: 1.3.0
 - piwik: 0.4.1
 - polls: 0.8.1
 - provisioning_api: 1.3.0
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - spreed: 3.2.5
 - survey_client: 1.1.0
 - systemtags: 1.3.0
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - workflowengine: 1.3.0
Disabled:
 - activity
 - deck
 - encryption
 - external
 - mindmaps
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "13.0.2.1",
    "dbtableprefix": "oc_",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y.m.d, H:i:s",
    "log_query": false,
    "loglevel": 0,
    "installed": true,
    "maintenance": false,
    "default_language": "de",
    "appstore.experimental.enabled": false,
    "knowledgebaseenabled": true,
    "enable_avatars": true,
    "theme": "",
    "allow_user_to_change_display_name": true,
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "token_auth_enforced": false,
    "auth.bruteforce.protection.enabled": true,
    "mail_smtpdebug": false,
    "trashbin_retention_obligation": "300,auto",
    "versions_retention_obligation": "90, auto",
    "appcodechecker": true,
    "updatechecker": true,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "has_internet_connection": true,
    "appstoreenabled": true,
    "enable_previews": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "preview_max_scale_factor": 10,
    "preview_max_filesize_image": 2,
    "check_for_working_webdav": true,
    "check_for_working_wellknown_setup": true,
    "check_for_working_htaccess": true,
    "config_is_read_only": false,
    "cron_log": true
}
```
</details>

**Are you using encryption:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0

**Operating system: Ubutu** 

## Logs
<details><summary>Nextcloud log</summary>

```
{"reqId":"W2rWJhhbFlLOKm@bwcnVYwAAABI","level":3,"time":"2018.08.08, 13:38:14","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/user\/sharing","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
{"reqId":"W2rWLBhbFlLOKm@bwcnVcQAAABI","level":3,"time":"2018.08.08, 13:38:20","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/user\/ojsxc","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
{"reqId":"W2rWLS1OdXhRgr1n8tw3SgAAAAk","level":3,"time":"2018.08.08, 13:38:21","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/user\/additional","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
{"reqId":"W2rWNJRUH3sTNAwwI@SoWQAAAAo","level":3,"time":"2018.08.08, 13:38:28","remoteAddr":"x.x.x.x","user":"USER","app":"no app in context","method":"GET","url":"\/settings\/admin\/logging","message":"issuetemplate","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.2.1"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log - How do I do that?

</details>

**Comment by DrDimedrol** [comment]
Have a some problem on server V14, there is NO pencil or other thing on password fields of user list. Rolling back to V13 with database recovering from backup, the pencil appear, but however it impossible to click to it and change value.

**Comment by Kaor** [comment]
Same here on 13.0.6 : 
> If I click on the Password field the textbox blink and disappear instant. If I click on other Elements like Mail the Textbox work and I'm able to change the content.

**Comment by DrDimedrol** [comment]
Yes, it look like problem in firefox, in chromium work OK. But when I upgrade my nextcloud installation from 13 to 14, the password input text is missing. when I install new fresh copy of nextcloud with new database, then I be able to edit it in chromium.

**Comment by lisa50469** [comment]
Just installed owncloud via the instructions from digital ocean, and it went perfectly until I added a second user.
When I click the pencil on the new users password field, the field blinks and I can see where I should type, but immediately goes back to the cover dots. 
ii  owncloud-files                  10.0.10-1+1.1                               all          ownCloud - Server

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Comment by rlenorerogers** [comment]
Stop sending all that fucking e mail shit

**Comment by rlenorerogers** [comment]
Stop sending all that fucking e mail shit

**Comment by kesselb** [comment]
@rlenorerogers 

![Screenshot from 2019-05-13 16-29-59](https://user-images.githubusercontent.com/3902676/57630050-302bc180-759d-11e9-85fb-99986e348b15.png)

For some reason you are subscribed to this thread. This is a feature by github. Added you a screenshot howto unsubscribe.
