### ISSUE TITLE
Missing folder incon

### ISSUE THREAD

**Issue by rarapost** [nextcloud/server#10354]
In my Debian NC installation there are missing folder icons in case no sharing, no group ... etc.
If the folder is "pure folder" with no extra attribute (like sharing), it has only transparent space in place of the icon. I would expect the same icon as in case the folder is shared, but with no internal symbol.
Other stuffs (files, shared folders, group folders ...) have icons as expected 

The behaviour described here were observer immediately after installation, without extra apps installed. 

### Steps to reproduce
Pure installation on Debian 9 linux, postgresql 9.6, 

### Server configuration
4core Intel computer, 8GB memory, 

**Operating system**:
Debian 9 

**Web server:**
nginx

**Database:**
PostgreSQL

**PHP version:**
7.0 fpm

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
no

**Where did you install Nextcloud from:**
approx. 2018-06

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js?v=44dd18a1-0:3748 Missing plural form in language file
_generatePluralFunction @ merged-template-prepend.js?v=44dd18a1-0:3748
register @ merged-template-prepend.js?v=44dd18a1-0:3726
(anonymous) @ cs.js?v=44dd18a1-0:1
jsxc.js:184 State changed to INITIATING
jsxc.js:184 State changed to PREVCONFOUND
jsxc.js:184 check master
jsxc.js:184 I am the slave.
jsxc.js:184 UI State changed to INITIATING
jsxc.js:12495 Uncaught TypeError: Cannot read property 'caps' of null
    at Object.jsxc.xmpp.httpUpload.init (jsxc.js:12495)
    at HTMLDocument.<anonymous> (jsxc.js:12781)
    at HTMLDocument.dispatch (core.js?v=44dd18a1-0:3)
    at HTMLDocument.r.handle (core.js?v=44dd18a1-0:3)
    at Object.trigger (core.js?v=44dd18a1-0:3)
    at Object.a.event.trigger (core.js?v=44dd18a1-0:7)
    at HTMLDocument.<anonymous> (core.js?v=44dd18a1-0:3)
    at Function.each (core.js?v=44dd18a1-0:2)
    at a.fn.init.each (core.js?v=44dd18a1-0:2)
    at a.fn.init.trigger (core.js?v=44dd18a1-0:3)
jsxc.xmpp.httpUpload.init @ jsxc.js:12495
(anonymous) @ jsxc.js:12781
dispatch @ core.js?v=44dd18a1-0:3
r.handle @ core.js?v=44dd18a1-0:3
trigger @ core.js?v=44dd18a1-0:3
a.event.trigger @ core.js?v=44dd18a1-0:7
(anonymous) @ core.js?v=44dd18a1-0:3
each @ core.js?v=44dd18a1-0:2
each @ core.js?v=44dd18a1-0:2
trigger @ core.js?v=44dd18a1-0:3
changeUIState @ jsxc.js:1123
init @ jsxc.js:2861
onSlave @ jsxc.js:743
onStorage @ jsxc.js:9978

b) The network log

```
</details>

**Comment by rarapost** [comment]
I observed it little bit more, and when I am trying to display icon itself 
https://cloud.anirad.cz/index.php/apps/theming/img/core/filetypes/folder.svg

which URL I got from styling here: 
background-image:url(/index.php/apps/theming/img/core/filetypes/folder.svg?v=0);

I get HTTP response 304 and the browser (Chrome) displays 
This XML file does not appear to have any style information associated with it. The document tree is shown below.

The same behaviour is in Opera.

**Comment by MorrisJobke** [comment]
> I get HTTP response 304 and the browser (Chrome) displays
> This XML file does not appear to have any style information associated with it. The document tree is shown below.
> 
> The same behaviour is in Opera.

That just means it is working fine. But as this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by mikevh1997** [comment]
I've been having the same issue after reinstalling Nextcloud. In my case, it was fixed by editing the color in the Theming app.

Just change the color to a random value and change it back once its saved. The icon's will be regenerated in the right color and the issue is fixed.
