### ISSUE TITLE
SMB remote storage hidden (starting with dot) files not shown can not be created

### ISSUE THREAD

**Issue by lsbbs** [nextcloud/server#10359]
### Steps to reproduce
1. Mount SMB/CIFS filesystem as remote storage
2. Try to create a file .test

### Expected behaviour
File .test is shown in the directory

### Actual behaviour
Error message "Could not create file .test"

### Server configuration

**Operating system**:
Ubutnu 16.04

**Web server:**
Apache/2.4.18 

**Database:**
10.0.34-MariaDB,

**PHP version:**
7.0.30-0ubuntu0.16.04.1

**Nextcloud version:** (see Nextcloud admin page)
13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 12 to 13.0.2

**Where did you install Nextcloud from:**
Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - audioplayer: 2.3.1
  - bookmarks: 0.11.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_external_gdrive: 0.2.8
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.3.2
  - notifications: 2.1.2
  - oauth2: true
  - ocsms: 1.13.1
  - password_policy: 1.3.0
  - phonetrack: 0.2.8
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_automatedtagging
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "testdomain.local"
        ],
        "tempdirectory": "\/tmp",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/testdomin.local",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "php",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "loglevel": 2,
        "logfile": "\/srv\/log\/nextcloud.log",
        "log_rotate_size": 52428800,
        "asset-pipeline.enabled": true,
        "updater.release.channel": "stable",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": true,
        "htaccess.RewriteBase": "\/",
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "check_for_working_htaccess": true
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local/smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
built in
</details>

### Client configuration
**Browser:**
Chrome 67.0.3396.99, Firefox

**Operating system:**
Ubuntu 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>
196.249.97.46 - - [23/Jul/2018:21:17:38 +0000] "PUT /remote.php/webdav/SMB/test.domain/.test HTTP/2" 404
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"9j1ZcBDJxHQz620NK0t2","level":3,"time":"2018-07-23T18:58:01+00:00","remoteAddr":"196.249.98.58","user":"ta","app":"no app in context","method":"PUT","url":"\/remote.php\/webdav\/SMB\/.test","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\\\/SMB\\\/.test not found while trying to get owner\",\"Code\":0,\"Trace\":\"#0\\\/srv\\\/testdomain.local\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(638):OC\\\\Files\\\\View->getOwner('\\\/SMB\\\/.test')\\n#1\\\/srv\\\/testdomain.local\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(190):OCA\\\\Activity\\\\FilesHooks->getSourcePathAndOwner('\\\/SMB\\\/.test')\\n#2\\\/srv\\\/testdomain.local\\\/apps\\\/activity\\\/lib\\\/FilesHooks.php(146):OCA\\\\Activity\\\\FilesHooks->addNotificationsForFileAction('\\\/SMB\\\/.test','file_created','created_self','created_by')\\n#3\\\/srv\\\/testdomain.local\\\/apps\\\/activity\\\/lib\\\/FilesHooksStatic.php(47):OCA\\\\Activity\\\\FilesHooks->fileCreate('\\\/SMB\\\/.test')\\n#4\\\/srv\\\/testdomain.local\\\/lib\\\/private\\\/legacy\\\/hook.php(106):OCA\\\\Activity\\\\FilesHooksStatic::fileCreate(Array)\\n#5\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(309):OC_Hook::emit('OC_Filesystem','post_create',Array)\\n#6\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(241):OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->emitPostHooks(false)\\n#7\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(156):OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #23)\\n#8\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096):OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('.test', Resource id #23)\\n#9\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(529):Sabre\\\\DAV\\\\Server->createFile('SMB\\\/.test', Resource id #23, NULL)\\n#10 [internal function]:Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request),Object(Sabre\\\\HTTP\\\\Response))\\n#11\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105):call_user_func_array(Array, Array)\\n#12\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479):Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#13\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254):Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#14\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80):Sabre\\\\DAV\\\\Server->exec()\\n#15\\\/srv\\\/testdomain.local\\\/remote.php(164):require_once('\\\/srv\\\/hostingdat...')\\n#16{main}\",\"File\":\"\\\/srv\\\/testdomain.local\\\/lib\\\/private\\\/Files\\\/View.php\",\"Line\":1670}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/67.0.3396.99 Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"} 
{"reqId":"9j1ZcBDJxHQz620NK0t2","level":3,"time":"2018-07-23T18:58:01+00:00","remoteAddr":"196.249.98.58","user":"ta","app":"remote","method":"PUT","url":"\/remote.php\/webdav\/SMB\/.test","message":"Exception:{\"Exception\":\"Error\",\"Message\":\"Call to a member function getChecksum() on boolean\",\"Code\":0,\"Trace\":\"#0\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php(250):OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->getChecksum()\\n#1\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(156):OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #23)\\n#2\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1096):OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('.test', Resource id #23)\\n#3 \\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(529):Sabre\\\\DAV\\\\Server->createFile('SMB\\\/.test', Resource id #23, NULL)\\n#4[internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request),Object(Sabre\\\\HTTP\\\\Response))\\n#5\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105):call_user_func_array(Array,Array)\\n#6\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(479):Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7\\\/srv\\\/testdomain.local\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254):Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(80):Sabre\\\\DAV\\\\Server->exec()\\n#9\\\/srv\\\/testdomain.local\\\/remote.php(164):require_once('\\\/srv\\\/hostingdat...')\\n#10{main}\", \"File\":\"\\\/srv\\\/testdomain.local\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":596}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Ubuntu Chromium\/67.0.3396.99 Chrome\/67.0.3396.99 Safari\/537.36","version":"13.0.4.0"}

</details>

**Comment by lsbbs** [comment]
Forgot: Except hidden files everything is working fine. Synchronizing in all directions etc.

**Comment by MorrisJobke** [comment]
seems to be similar to #9663 as it has the same symptoms and same error message. Let's continue over there.
