### ISSUE TITLE
Lost connection to LDAP server.

### ISSUE THREAD

**Issue by jdadame** [nextcloud/server#10360]
### Steps to reproduce
1. Run the occ upgrade from browser

### Expected behaviour
Should upgrade
### Actual behaviour
Fails

Following Error Occurs: OC\ServerNotAvailableException: Lost connection to LDAP server.
Update failed

Anyway to go around this?

**Comment by MorrisJobke** [comment]
> Following Error Occurs: OC\ServerNotAvailableException: Lost connection to LDAP server.
> Update failed
> 
> Anyway to go around this?

I guess there is not much ... the Nextcloud 14 ldap app already has some improvements to automatically reconnect on failure. That's all we can do :/ Beside that: just run the upgrade step again.

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap in case I have overseen something.
