### ISSUE TITLE
Tasks: New categories are not saved to backend/shared between instances

### ISSUE THREAD

**Issue by hcderaad** [nextcloud/server#10365]
### Steps to reproduce
1. Add a new task and assign a newly created category in one client session (browser)
2. Open another session (private mode/other workstation) try to assign the category created in 1 to a task
3. The instance from 2 will add the category as New.

### Expected behaviour
Task categories that are added through one user session should be shared between sessions.

### Actual behaviour
See 3.

### Server configuration

**Operating system**: openSUSE Tumbleweed

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Since 11ish.

**Where did you install Nextcloud from:** openSUSE build service RPMs

**List of activated apps:**
N.A. this only concerns Tasks.

**Nextcloud configuration:**
N.A. this only concerns Tasks.

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No, full disk encryption on volume level.

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)
N.A. 

### Client configuration
**Browser:** Firefox / Chrome

**Operating system:** Windows / Linux.

#### Web server error log
No usable log info found regarding unstorable categories.

#### Nextcloud log (data/nextcloud.log)
No usable log info found regarding unstorable categories.

#### Browser log
The developer tools show the event being updated in the PUT request with the label and ("Nieuwe categorie" = Dutch) and the new category. The newly added category is not reusable.

**Comment by hcderaad** [comment]
#434 is completely unrelated, this is a Tasks categories issue, not a filesharing issue.
#1895 is completely unrelated, this is a Tasks categories issue, not a filesharing issue.
#6482 is unrelated, that is an installation issue, this is an issue that occurs during regular usage.
#2616 is completely unrelated, this is a Tasks categories issue, not a filesharing issue.
#585 is completely unrelated, this is a Tasks categories issue, not a filesharing issue.

**Comment by MorrisJobke** [comment]
This is an issue within the tasks app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/tasks
