### ISSUE TITLE
Email Client issue - Max Connection exceeds - Top Level Domain access temporarily revoked.

### ISSUE THREAD

**Issue by ankitpsaraogi** [nextcloud/server#10374]
The Top level domain gets temporarily blocked when I open the email client in NextCloud.
### Steps to reproduce
1. Login to Email
2. Open the specific mail containing images
3. Click on Show Images

### Expected behaviour
It should show me the contents of the email

### Actual behaviour
Nothing happens and the domain becomes inaccessible for sometime. I can access the cpanel but not the domain. 
Hi,
I was using mail client today and noted that on clicking of show images for an html mail received, the website stopped working. Infact the access to the top level domain was restricted temporarily. I checked the logs and found out
Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[42000] [1203] User agarwegg_next821 already has more than ‘max_user_connections’ active connections in /home/agarwegg/public_html/files/lib/private/DB/Connection.php:64 Stack trace: #0 /home/agarwegg/public_html/files/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect() #1 /home/agarwegg/public_html/files/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #2 /home/agarwegg/public_html/files/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform() #3 /home/agarwegg/public_html/files/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform() #4 /home/agarwegg/public_html/files/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2) #5 /home/agarwegg/public_html at /home/agarwegg/public_html/files/lib/private/DB/Connection.php#64

Also, today when I reinstalled the Mail app, I got this error Invalid argument supplied for foreach() at /home/agarwegg/public_html/files/lib/private/Installer.php#404

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Softaculous
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ankitpsaraogi** [comment]
Error after sometime when the access is restored:
GuzzleHttp\Exception\RequestException: cURL error 3: <url> malformed
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 103: GuzzleHttp\Exception\RequestException wrapException(Object(GuzzleHttp\Message\Request), Object(GuzzleHttp\Ring\Exception\RingException))
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 132: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/home/agarwegg/public_html/files/3rdparty/react/promise/src/FulfilledPromise.php - line 25: GuzzleHttp\RequestFsm->GuzzleHttp\{closure}(*** sensitive parameters replaced ***)
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/ringphp/src/Future/CompletedFutureValue.php - line 55: React\Promise\FulfilledPromise->then(Object(Closure), NULL, NULL)
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/Message/FutureResponse.php - line 43: GuzzleHttp\Ring\Future\CompletedFutureValue->then(Object(Closure), NULL, NULL)
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/RequestFsm.php - line 134: GuzzleHttp\Message\FutureResponse proxy(Object(GuzzleHttp\Ring\Future\CompletedFutureArray), Object(Closure))
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/Client.php - line 165: GuzzleHttp\RequestFsm->__invoke(Object(GuzzleHttp\Transaction))
/home/agarwegg/public_html/files/3rdparty/guzzlehttp/guzzle/src/Client.php - line 125: GuzzleHttp\Client->send(Object(GuzzleHttp\Message\Request))
/home/agarwegg/public_html/files/lib/private/Http/Client/Client.php - line 138: GuzzleHttp\Client->get(NULL, Array)
/home/agarwegg/public_html/files/apps/mail/lib/Controller/ProxyController.php - line 124: OC\Http\Client\Client->get(NULL)
[internal function] OCA\Mail\Controller\ProxyController->proxy(NULL)
/home/agarwegg/public_html/files/lib/private/AppFramework/Http/Dispatcher.php - line 161: call_user_func_array(Array, Array)
/home/agarwegg/public_html/files/lib/private/AppFramework/Http/Dispatcher.php - line 91: OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Mail\Controller\ProxyController), 'proxy')
/home/agarwegg/public_html/files/lib/private/AppFramework/App.php - line 115: OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\ProxyController), 'proxy')
/home/agarwegg/public_html/files/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\\Mail\\Contro...', 'proxy', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/home/agarwegg/public_html/files/lib/private/Route/Router.php - line 297: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/home/agarwegg/public_html/files/lib/base.php - line 999: OC\Route\Router->match('/apps/mail/prox...')
/home/agarwegg/public_html/files/index.php - line 42: OC handleRequest()
{main}

**Comment by MorrisJobke** [comment]
> Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[42000] [1203] User agarwegg_next821 already has more than ‘max_user_connections’ active connections in

This looks like a setup issue on your DB.




> OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Mail\Controller\ProxyController), 'proxy')
> /home/agarwegg/public_html/files/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OCA\Mail\Contro...', 'proxy',

Could you open this ticket in the mail app?

https://github.com/nextcloud/mail
