### ISSUE TITLE
Copy/move files/directories displays "No files in here" even if there are files

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/server#10379]
### Steps to reproduce
1. have a directory containing at least one file
2. select the copy action for any file
3. navigate to the directory containing at least one file

### Expected behaviour
The app displays something like "No more subfolders in here".

### Actual behaviour
The app displays "No files in here", that isn't correct (see [screenshot](https://user-images.githubusercontent.com/6216686/43159927-082741fa-8f84-11e8-834b-63f679f09094.png) ).

It could lead to confusion as users may think their files are gone ;)

### Server configuration
**Nextcloud version:** 14
**Where did you install Nextcloud from:** git

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/blob/10b33cd5d05f0c266206a25c94db970ecc35f30b/core/js/oc-dialogs.js#L207 this one needs to be made configurable in the `filepicker(...)` call IMO.
