### ISSUE TITLE
Avatar in author row of comments gets resized to 16x16 px

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#10381]
Regression introduced in #10288 

The avatar in the author row should be excluded from the size adjustment, otherwise it is resized too when the comments are reloaded:

![comment-avatar](https://user-images.githubusercontent.com/26858233/43186571-595341d0-8fef-11e8-81a6-1b5fdeb90613.png)

@nextcloud/designers @juliushaertl

**Comment by juliushaertl** [comment]
I'll have a look.
