### ISSUE TITLE
Improve Front-End Error Handling when DB is unreachable

### ISSUE THREAD

**Issue by mrnoisytiger** [nextcloud/server#10380]
### Steps to reproduce
1. Database (MySQL) is unreachable for whatever reason
2. Attempt to load Nextcloud

### Expected behaviour
An error message mentioning that the database is unreachable at the current time

### Actual behaviour
HTTP request hangs and does not complete. No front-end error is generated

### Server configuration

**Operating system**: Ubuntu 14.04 LTS

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 13.0.4

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/8928
