### ISSUE TITLE
Password confirm dialog overlay misplaced

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10387]
The overlay that was shown over the whole page when a dialog is presented is only applied to the app navigation right now:

![image](https://user-images.githubusercontent.com/3404133/43195983-deb35d94-9006-11e8-8f9b-3e809663742d.png)

Maybe caused by #9982 

@nextcloud/designers

**Comment by skjnldsv** [comment]
Fine on my install :/
![capture d ecran_2018-07-25_12-36-36](https://user-images.githubusercontent.com/14975046/43196164-62248856-9007-11e8-960c-190f6ebe6c09.png)

**Comment by skjnldsv** [comment]
Fix: #10388
