### ISSUE TITLE
Unclear which item is currently "active"

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#10393]
> ![bildschirmfoto von 2018-07-25 14-03-15](https://user-images.githubusercontent.com/213943/43199843-9eda97ac-9013-11e8-8c1e-d738055937c7.png)

Actually the "light" one is active and the bold one is the other option.

Also if you scroll in the dropdown, the file list is also scrolled

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Here we should also use the highlight method we use in the navigation and menus, which is the blue bar on the left.

What do you think @nextcloud/designers?
