### ISSUE TITLE
HTTP ERROR 500

### ISSUE THREAD

**Issue by abhijithvijayan** [nextcloud/server#10390]
log from /var/log/nginx/error.log
PHP 7.0.30-0
ubuntu0.16.04.1
nextcloud 13
mysql db
nginx webserver

`2018/07/25 16:39:41 [error] 5667#5667: *39 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'user_name'@'localhost' (using password: YES) in /home/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /home/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(...
PHP message: PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'user_name'@'localhost' (using password: YES) in /home/nextcloud/lib/private/DB/Connection.php:64
Stack trace:
#0 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /home/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /home/nextcloud/3rdparty/doctrine/dbal/lib/Doc
`

**Comment by abhijithvijayan** [comment]
tried reloading nginx, php-fpm but nothing worked

**Comment by MorrisJobke** [comment]
> Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [1045] Access denied for user 'user_name'@'localhost'

Looks like the wrong credentials are used for this.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by abhijithvijayan** [comment]
no no I manually edited it before posting here

**Comment by MorrisJobke** [comment]
> SQLSTATE[HY000] [1045] Access denied for user 'user_name'@'localhost' (using password: YES)

The error log says that the user does not not have access. Nothing PHP could do here. Either credentials are wrong or the DB server refuses this account for whatever reason.

**Comment by abhijithvijayan** [comment]
Yeah I solved it. It was a DB error.
