### ISSUE TITLE
CalDAV Shared calendars: Share as busy / hidden always rendered as if it was set by calendar-owner.

### ISSUE THREAD

**Issue by cmsnstuff** [nextcloud/server#10392]
### Steps to reproduce
1. Create a calendar in nextcloud's webinterface calendar app
2. Share the calendar with a group of e.g. coworkers without "can edit"-attribute
3. Create a calendar-entry in nextcloud's webinterface calendar app with attribute "When shared show only busy"
4. In the coworkers' webinterfaces the calendar-entry shows up as "busy", as desired and expected, also when syncing with OpenSync on Android
5. When synching with CalDAV Synchronizer for Outlook, coworkers get the whole title and description synced to their Outlook-calendars

### Expected behaviour
Unlike described above in step 5, coworkers should only get the calendar-entry's title "busy", as shown in the webinterface, when synching with an arbitrary CalDAV-Client.

### Actual behaviour
Coworkers can see title and description of calendar-entry, despite of the attribute "When shared show only busy"

### Server configuration

**Operating system**: Debian 4.9.110-1 (2018-07-05) x86_64

**Web server:**  apache2 (2.4.25-3+deb9u5)

**Database:**  mysql-server (5.5.9999+default)

**PHP version:**  php7.0 (7.0.30-0+deb9u1)

**Nextcloud version:** 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** debian-repository  https://repo.morph027.de/nextcloud jessie main

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.6.1
  - announcementcenter: 3.2.1
  - audioplayer: 2.3.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - checksum: 0.4.0
  - comments: 1.3.0
  - contacts: 2.1.5
  - dashboard: 5.0.0
  - dav: 1.4.7
  - deck: 0.4.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - limit_login_to_ip: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - metadata: 0.6.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - ojsxc: 3.4.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.50.14"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.50.14",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "default_language": "de_DE",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.6.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "announcementcenter": {
            "enabled": "yes",
            "installed_version": "3.2.1",
            "types": "logging"
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "2.3.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "43"
        },
        "bruteForce": {
            "whitelist_1": "192.168.50.0\/25"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.1",
            "types": ""
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "0.4.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.5",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1508750609.271",
            "lastcron": "1532519101",
            "lastupdateResult": "[]",
            "lastupdatedat": "1532517137",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "321e2180e464d366b70f5071e7ab886b",
            "updater.secret.created": "1532505562",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "enabled": "yes",
            "installed_version": "5.0.0",
            "types": ""
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.4.7",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.4.0",
            "types": ""
        },
        "drawio": {
            "enabled": "no",
            "installed_version": "0.8.9",
            "types": "filesystem"
        },
        "encryption": {
            "enabled": "no",
            "installed_version": "2.0.0",
            "masterKeyId": "***REMOVED SENSITIVE VALUE***",
            "publicShareKeyId": "***REMOVED SENSITIVE VALUE***",
            "recoveryAdminEnabled": "1",
            "recoveryKeyId": "***REMOVED SENSITIVE VALUE***",
            "types": "filesystem",
            "useMasterKey": "0"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_clipboard": {
            "enabled": "no",
            "installed_version": "0.7.1",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.8.4",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.5.0",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.5.1",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.0.0",
            "types": ""
        },
        "impersonate": {
            "enabled": "no",
            "installed_version": "1.0.4",
            "types": ""
        },
        "limit_login_to_ip": {
            "enabled": "yes",
            "installed_version": "1.0.4",
            "types": "filesystem",
            "whitelisted.ranges": ",***REMOVED SENSITIVE VALUE***"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "authentication"
        },
        "metadata": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "mindmaps": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "notification_groups": "[\"admin\",\"Mitarbeiter\"]",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": "authentication"
        },
        "ojsxc": {
            "apiSecret": "***REMOVED SENSITIVE VALUE***",
            "enabled": "yes",
            "installed_version": "3.4.1",
            "ocsid": "162257",
            "types": "prelogin"
        },
        "onlyoffice": {
            "DocumentServerInternalUrl": "",
            "DocumentServerUrl": "***REMOVED SENSITIVE VALUE***",
            "StorageUrl": "",
            "defFormats": "{\"docx\":\"true\",\"xlsx\":\"true\",\"pptx\":\"true\",\"ppsx\":\"true\",\"txt\":\"true\",\"csv\":\"true\"}",
            "enabled": "no",
            "installed_version": "1.3.0",
            "jwt_secret": "",
            "ocsid": "174798",
            "sameTab": "false",
            "settings_error": "Bad Request oder Timeout Fehlermeldung",
            "skey": "***REMOVED SENSITIVE VALUE***",
            "types": "filesystem"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "prevent_group_restriction"
        },
        "quota_warning": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.3.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "sendpasswordmail": "no",
            "types": "filesystem"
        },
        "socialsharing_email": {
            "enabled": "no",
            "installed_version": "1.0.3",
            "types": ""
        },
        "spreed": {
            "enabled": "yes",
            "installed_version": "3.2.5",
            "stun_servers": "[\"stun.nextcloud.com:443\"]",
            "types": "prevent_group_restriction"
        },
        "spreedme": {
            "SPREED_WEBRTC_SHAREDSECRET": "***REMOVED SENSITIVE VALUE***",
            "enabled": "no",
            "installed_version": "0.3.11",
            "types": ""
        },
        "survey_client": {
            "apps": "no",
            "database": "no",
            "enabled": "no",
            "encryption": "no",
            "files_sharing": "no",
            "installed_version": "1.1.0",
            "php": "no",
            "server": "no",
            "stats": "no",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.6",
            "ocsid": "164356",
            "types": ""
        },
        "theming": {
            "backgroundMime": "backgroundColor",
            "cachebuster": "17",
            "color": "#279F9E",
            "enabled": "yes",
            "installed_version": "1.4.5",
            "logoMime": "image\/png",
            "name": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.2.3",
            "types": ""
        },
        "updatenotification": {
            "announcementcenter": "3.1.1",
            "bruteforcesettings": "1.1.0",
            "calendar": "1.5.8",
            "contacts": "2.1.5",
            "core": "13.0.5.2",
            "dashboard": "5.0.0",
            "enabled": "[\"admin\"]",
            "installed_version": "1.3.0",
            "ojsxc": "3.4.1",
            "onlyoffice": "1.2.0",
            "socialsharing_email": "1.0.3",
            "spreed": "2.0.2",
            "tasks": "0.9.6",
            "types": "",
            "update_check_errors": "0"
        },
        "user_ldap": {
            "cleanUpJobOffset": "0",
            "enabled": "no",
            "has_memberof_filter_support": "1",
            "home_folder_naming_rule": "",
            "installed_version": "1.2.1",
            "last_jpegPhoto_lookup": "0",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_attributes_for_group_search": "",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "",
            "ldap_backup_port": "",
            "ldap_base": "***REMOVED SENSITIVE VALUE***",
            "ldap_base_groups": "***REMOVED SENSITIVE VALUE***",
            "ldap_base_users": "***REMOVED SENSITIVE VALUE***",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_default_ppolicy_dn": "",
            "ldap_display_name": "displayName",
            "ldap_dn": "***REMOVED SENSITIVE VALUE***",
            "ldap_dynamic_group_member_url": "",
            "ldap_email_attr": "",
            "ldap_experienced_admin": "0",
            "ldap_expert_username_attr": "",
            "ldap_expert_uuid_group_attr": "",
            "ldap_expert_uuid_user_attr": "",
            "ldap_gid_number": "gidNumber",
            "ldap_group_display_name": "cn",
            "ldap_group_filter": "(&(|(objectclass=group))(|(cn=GL)(cn=Mitarbeiter)))",
            "ldap_group_filter_mode": "0",
            "ldap_group_member_assoc_attribute": "member",
            "ldap_groupfilter_groups": "GL\nMitarbeiter",
            "ldap_groupfilter_objectclass": "group",
            "ldap_host": "ldap:\/\/192.168.50.2",
            "ldap_login_filter": "(&(&(|(objectclass=person)(objectclass=user))(|(|(memberof=CN=***REMOVED SENSITIVE VALUE***)(primaryGroupID=1104))))(samaccountname=%uid))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_attributes": "",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_nested_groups": "0",
            "ldap_override_main_server": "",
            "ldap_paging_size": "500",
            "ldap_port": "389",
            "ldap_quota_attr": "",
            "ldap_quota_def": "",
            "ldap_tls": "0",
            "ldap_turn_off_cert_check": "0",
            "ldap_turn_on_pwd_change": "0",
            "ldap_user_display_name_2": "",
            "ldap_user_filter_mode": "0",
            "ldap_userfilter_groups": "Mitarbeiter",
            "ldap_userfilter_objectclass": "person\nuser",
            "ldap_userlist_filter": "(&(|(objectclass=person)(objectclass=user))(|(|***REMOVED SENSITIVE VALUE***))))",
            "types": "authentication",
            "use_memberof_to_detect_membership": "1"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        }
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "default_language": "de_DE",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}


or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** 
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
not at the moment

</details>

### Client configuration
**Browser:** Firefox 61.0.1 (32-Bit)

**Operating system:** Windows 10 1709

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen @georgehrke @rullzer

**Comment by skjnldsv** [comment]
cc @nextcloud/calendar

**Comment by georgehrke** [comment]
Known issue, related:
https://github.com/nextcloud/calendar/issues/657
https://github.com/nextcloud/calendar/issues/658

I'm think we should just forbid sharees to create events with any class other than public.

**Comment by skjnldsv** [comment]
DOn't forget to change the label ;)

**Comment by georgehrke** [comment]
Proposed solution:

Throw an error when a sharee tries to creates an event that contains a `CLASS` property and the `CLASS` property is not set to `PUBLIC`

**Comment by raimund-schluessler** [comment]
@georgehrke At least from what the issue details say, the issues you linked are not related. I didn’t check or reproduce the issue, but it is says that the whole event is shown although it is set to only busy.

@cmsnstuff Please comment on the above.

**Comment by georgehrke** [comment]
Ah, sorry. In that case i remember this bug and it  was fixed with https://github.com/nextcloud/server/pull/12458
