### ISSUE TITLE
Opening details after coming from favorites view is broken

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10398]
Acceptance tests fail:

```
# /drone/src/github.com/nextcloud/server/tests/acceptance/features/app-files.feature:14
Scenario: viewing a favorite file in its folder does not prevent opening the details view in "All files" section
  Given I am logged in
  And I mark "welcome.txt" as favorite
  And I see that "welcome.txt" is marked as favorite
  And I open the "Favorites" section
  And I open the details view for "welcome.txt"
  And I see that the details view is open
  And I view "welcome.txt" in folder
  And I see that the current section is "All files"
  When I open the details view for "welcome.txt"
  Then I see that the details view is open
    The details view is not open yet after 100 seconds
```

For me the details view opens in Safari, but the error in the console is still there.

JS console:

```
TypeError: undefined is not an object (evaluating 'OCA.Files.App.fileList.changeDirectory(fileModel.get('path'), true, true).then')
```

![bildschirmfoto 2018-07-25 um 17 41 23](https://user-images.githubusercontent.com/245432/43211560-1603c5ba-9032-11e8-87e8-fac96c11b650.png)

cc @skjnldsv @juliushaertl @danxuliu @nextcloud/javascript 

That is now the only failing test and we could maybe look into this.

**Comment by violoncelloch** [comment]
> For me the details view opens in Safari, but the error in the console is still there.
@MorrisJobke for me the details bar doesn't open in Firefox
and it's the same if I'm coming from the shares view as I detected in #10516 in correlation with another bug
if I do the same with recent view and tags view, the details view doesn't open as well

**Comment by skjnldsv** [comment]
@violoncelloch did you cleared your cache?

**Comment by violoncelloch** [comment]
Yes, I even tested it with a fresh firefox installation and it doesen't work for me there with beta2

**Comment by juliushaertl** [comment]
@skjnldsv Doesn't work here either:

1. Open All files
2. Open Details view
3. Open Favorites
4. Open Details view
5. Open All files
6. Open Details view :boom: 

See #10509 for a possible fix

**Comment by skjnldsv** [comment]
Ah, I misread the issue, my bad!
