### ISSUE TITLE
NextCloud / OwnCloud

### ISSUE THREAD

**Issue by Jolg42** [nextcloud/server#104]
Hi!

As a OwnCloud user, I don't see the differences with NextCloud, it is not very clear for me like:
- It looks like a fork of OwnCloud with the name replaced
- Do you plan to have a complete different product & roadmap after this fork?
- What are/will be the main things for NextCloud vs OwnCloud?

Just to know what is your goal 😉

**Comment by LukasReschke** [comment]
Please check https://nextcloud.com/about/ and https://plus.google.com/events/cnntcg90ehkd9j6gdglumj1g708

Also such questions are better suited for our forums: https://help.nextcloud.com

**Comment by Jolg42** [comment]
Great! Thanks!
And keep up the good work 💪👍
