### ISSUE TITLE
Dailysnapshot 2016-08-24: Max File Size  The "Save" button doesn't do anything

### ISSUE THREAD

**Issue by StopTrain** [nextcloud/server#1040]
### Steps to reproduce
1. Update to daily snapshot
2. Update the Max File Size in File Handling
3. Click "Save" and nothing happens

### Expected behaviour
Should update the max upload size

### Actual behaviour
Nothing happens

### Server configuration
**Operating system**: openSUSE Leap 42.1

**Web server:** apache 2.4.16

**Database:** Mysql

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 10.1RC1 (dailysnapshot)

**Updated from an older Nextcloud/ownCloud or fresh install:** no, existing snapshot install

**Where did you install Nextcloud from:** github page

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - bookmarks: 0.8.1
  - comments: 1.0.0
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_mv: 0.8.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - logreader: 1.1.5
  - news: 9.0.2
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - gallery
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
.htaccess config.php config.sample.php
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocfa07uz3wno",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.slackadelic.com"
        ],
        "datadirectory": "\/cloud",
        "overwrite.cli.url": "https:\/\/cloud.slackadelic.com",
        "dbtype": "mysql",
        "version": "9.1.0.15",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "cloud",
        "mail_domain": "slackadelic.com",
        "mail_smtphost": "192.168.1.2",
        "mail_smtpport": "25",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "updatechecker": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
No errors in logs
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
No errors in logs
```
</details>

**Comment by rullzer** [comment]
You should see a `saved` thingy pop up.

If you open the network console do you see requests being made?

**Comment by StopTrain** [comment]
If you could tell me what you mean by the network console, I can sure check!

**Comment by michag86** [comment]
@StopTrain In the most browsers you can start it with F12. There is something like "network analysis"

**Comment by StopTrain** [comment]
@michag86 Thank you!  I looked and don't see it even registering my clicks in the admin interface for Send Email for testing nor that save box, but let me test a few other browsers and  make sure it's not a caching issue of some sort

**Comment by StopTrain** [comment]
Ok, so it's not a browser caching issue.  I might have to pull another daily and apply it to see if that resolves it.

**Comment by StopTrain** [comment]
Well, I upgrade to 10.0 after it was released and the save button did work, and gave an error.
Check the nextcloud.log and it was .htaccess permissions.. no problem.
chown wwrun.www .htaccess
Tried again, this time the button doesn't work or give any feedback.

**Comment by StopTrain** [comment]
Ok, I'm going to close this issue.... what I found was this " typeErro: OCA.Files.fileActions is undefined.

I researched it and found it was related to the files_mv app.  Once I disabled that, everything started working properly!  So, this is NOT an issue with core.
