### ISSUE TITLE
fulltextsearch:index not indexing modified files

### ISSUE THREAD

**Issue by philippe-opendsi** [nextcloud/server#10402]
### Steps to reproduce
1. Make a first index sudo -u www-data php occ fulltextsearch:index
2. Go on your CIFS Server, edit existing file
3. Re-index sudo -u www-data php occ fulltextsearch:index

### Expected behaviour
Indexing a modified file

### Actual behaviour
Nothing append 

### Server configuration

**Operating system**:
Debian9

**Web server:**
Nginx
**Database:**
Mariadb
**PHP version:**
PHP7.0
**Nextcloud version:** (see Nextcloud admin page)
13.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
```

```
</details>

**List of activated apps:**

<details>
<summary>App list</summary>

Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_fulltextsearch: 0.8.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - fulltextsearch: 0.8.1
  - fulltextsearch_elasticsearch: 0.8.0
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bookmarks_fulltextsearch
  - deck
  - encryption
  - files_fulltextsearch_tesseract
  - files_pdfviewer
  - richdocuments
  - spreed
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.17.200.104"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/172.17.200.104",
        "dbtype": "mysql",
        "version": "13.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}

</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

</details>
</details>

**Comment by MorrisJobke** [comment]
This is an issue within the fulltextsearch app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/fulltextsearch
