### ISSUE TITLE
Check for update blocker apps not working for 14

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10412]
There is a section below the update notifications that should tell you if some used apps are not compatible with NC 14, but it says, that the instance is on the latest major version and that it will show information once the next release is upcoming (which is obviously the case ;))

![bildschirmfoto 2018-07-26 um 17 53 16](https://user-images.githubusercontent.com/245432/43273493-d7efe74c-90fc-11e8-9ba4-c4102c95b86e.png)

cc @nickvergessen

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/caniupdate/commit/f52eed36060b9802c91278ded1ed9a4c12d94710 and released a new version 0.1.3 on friday
