### ISSUE TITLE
S3 external storage does not check for changes

### ISSUE THREAD

**Issue by plrunner** [nextcloud/server#10413]
### Steps to reproduce
1. add a global S3 external storage for all users taking care of using "once every direct access" as the "check for changes" option
2. check AWS IAM policies are correctly defined by adding files through Nextcloud and appreciating those files are successfully added and visible to all users
3. add some files using the S3transfer, the S3 admin console or any other tool other than Nextcloud
4. verify that such files are not visible through Nextcloud

### Expected behaviour
We'd expect those files to be visible to Nextcloud users

### Actual behaviour
Files are not visible, even after
1. having removed and added the bucket as external storage again
2. having run "file:scan --all"

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Apache 2.4

**Database:**
MariaDB 5.7

**PHP version:**
5.4

**Nextcloud version:** (see Nextcloud admin page)
13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
No

**Where did you install Nextcloud from:**
Official tarball

**List of activated apps:**
only stock apps

**Are you using external storage, if yes which one:** local/smb/sftp/...
S3

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP user (although local admin is experiencing the same problem)

### Client configuration
**Browser:**
anyone

**Operating system:**
anyone

#### Nextcloud log (data/nextcloud.log)
No relevant log entry

**Comment by plrunner** [comment]
Maybe duplicate of #6954.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
