### ISSUE TITLE
Layout of admin tag management needs adjustments

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#10420]
The "icon buttons" are too close together:
> ![bildschirmfoto von 2018-07-27 08-56-36](https://user-images.githubusercontent.com/213943/43306368-26decfd4-917b-11e8-9047-aaf8949808e6.png)

Even worse with the delete button on edit:
> ![bildschirmfoto von 2018-07-27 08-58-25](https://user-images.githubusercontent.com/213943/43306423-584556a6-917b-11e8-9beb-3ef5c362cdd8.png)

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
In the creation flow, the x is not really necessary. It is much too dangerous to put a destructive action next to the confirm action too.

In the editing process, we should have a Save button (Ideally also with text) and a 3-dot menu with the other options in it.

**Comment by nickvergessen** [comment]
In NC13 we had normal text buttons, so they where a bit bigger and no real problem.
See https://github.com/nextcloud/server/pull/10028 for comparison.

Since that is the "breaking" PR, let's summon the author @juliushaertl

**Comment by juliushaertl** [comment]
> In the creation flow, the x is not really necessary. It is much too dangerous to put a destructive action next to the confirm action too.
> In the editing process, we should have a Save button (Ideally also with text) and a 3-dot menu with the other options in it.

@jancborchardt So should we just move back to the regular buttons again? We don't have any buttons with images anywhere in the settings ui as far as i can tell. 

How about having the create a new tag ui persistent with just a confirm button. That way we could get rid of the reset button when editing and would just have save and delete there. Delete could go into a 3 dots menu. Of course the buttons should all have a width of 44x44px, not small as they are right now.

**Comment by nickvergessen** [comment]
Since we are currently in FF and trying to finalize the product, I'd say let's do the simple step (text-buttons) for 14 and change to whatever is best in 15.
