### ISSUE TITLE
[Feature] User creation: Suggestion of selected group

### ISSUE THREAD

**Issue by Franny203** [nextcloud/server#10428]
Steps to reproduce

    Create a group
    Go to user creation
    Select the group
    Create the user

Expected behaviour

After selecting a group in the user creation menu, that particular group should be suggested in the user creation bar. So no additional selection of the group is necessary.
Actual behaviour

When you select a group, this doesn't have an influence on the creation process. It only shows the existing members.
Server configuration

Operating system:
Linux 3.16.0-6-amd64 #1 SMP Debian 3.16.57-2 (2018-07-14) x86_64

Web server:
Apache (cgi-fcgi)

Database:
mysql 5.7.22

PHP version:
7.1.20
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, htscanner, iconv, session, intl, json, ldap, mbstring, mcrypt, standard, mysqlnd, OAuth, pcntl, mysqli, PDO, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, redis, Reflection, imap, shmop, SimpleXML, soap, sockets, ssh2, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, apcu, imagick, Zend OPcache

Nextcloud version: (see Nextcloud admin page)
13.0.4 - 13.0.4.0

Updated from an older Nextcloud/ownCloud or fresh install:
Updated from NC12

Where did you install Nextcloud from:
https://download.nextcloud.com/server/releases/nextcloud-13.0.4.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment]
It does it for me, if the group is selected, new users will be added to it
