### ISSUE TITLE
All contacts disappears after 4.0.0 Beta 1 update

### ISSUE THREAD

**Issue by Larsene** [nextcloud/server#10429]
After updating to nextcloud 4.0.0 Beta 1, all contacts in the contacts app have disappeared. The contacts app appeareance is strange, too
![contacts](https://user-images.githubusercontent.com/8544729/43325157-41ac2538-91b6-11e8-9510-5a03da105c0b.jpg)

**Comment by rullzer** [comment]
@skjnldsv this is because contacts needs to be updated to the new layout right?

**Comment by skjnldsv** [comment]
Contacts is not compatible with 14 yet.
