### ISSUE TITLE
Add option to automated tagging to tag existing files

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#10425]
### Steps to reproduce
1. login as admin
2. goto settings/workflow and create a new rule, e.g. based on MIME type
3. 

### Expected behaviour
in step 3. I'd like to apply the rule to existing files. This makes only sense for rules based on information available on the server (size, MIME type, system tag, owner, ...)

### Actual behaviour
automatic tagging works only for new files.

**Comment by olantrust** [comment]
Related issue: #4216

**Comment by skjnldsv** [comment]
there's the auotmated tagging app for this

**Comment by schaarsc** [comment]
I don't understand why this issue has been closed

> https://apps.nextcloud.com/apps/files_automatedtagging
> An app for Nextcloud that automatically assigns tags to newly uploaded files based on some conditions.

this issue is  about files that already exist in Nextcloud, before a rule is created. As far as I know this currently not supported.
