### ISSUE TITLE
Since the upgrade from Owncloud to Nextcloud (11 and later), not all groups resolve

### ISSUE THREAD

**Issue by gvansanden** [nextcloud/server#10431]
We are using Nextcloud on Ubuntu 16.04 against OpenLDAP

### Steps to reproduce
1. Install Nextcloud 11 or later
2.Point to openldap

### Expected behaviour
All groups resolve as before

### Actual behaviour
Only a limited amount of groups resolve, command line listing ends in a timeout error after a long time

### Server configuration

**Operating system**: 
Ubuntu server 16.04 LTS

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7.0.15

**Nextcloud version:** (see Nextcloud admin page)
13.0.5 (any version since 11

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from NC 11

**Where did you install Nextcloud from:**
tar file

Issue fixed by editing apps/user_ldap/lib/Group_LDAP.php
change line 831 from
str_replace('%uid', $member, $this->access->connection->ldapLoginFilter),
to
str_replace('%uid', trim($member), $this->access->connection->ldapLoginFilter),

The trim fixes it

**Comment by rullzer** [comment]
@nextcloud/ldap

**Comment by blizzz** [comment]
@gvansanden since you have the fix at hand, could you open a pull request? :)

**Comment by MorrisJobke** [comment]
> @gvansanden since you have the fix at hand, could you open a pull request? :)

See #10775
