### ISSUE TITLE
Undefined isDirectoryHandle() method breaking encryption.

### ISSUE THREAD

**Issue by MartB** [nextcloud/server#10430]
https://github.com/nextcloud/server/blob/3f2a5c9335a0a96858edb65785eec149b16f1a0e/lib/private/Files/Stream/Encryption.php#L198

```
Error: Call to undefined method OC\Files\Stream\Encryption::isDirectoryHandle()
/usr/share/nginx/cloud.familie-boeh.de/lib/private/Files/Stream/Encryption.php - line 181:

OC\Files\Stream\Encryption::wrapSource(null, null, "ocencryption", "OC\\Files\\Stream\\Encryption", "r")
```

**Workaround:**
Disable the **External Files Application** as specified here: https://github.com/nextcloud/server/issues/10430#issuecomment-410657768

**Comment by MartB** [comment]
@nextcloud-bot unrelated, this defect has been there since april i wonder why it didnt pop up during testing. Did someone remove that method lately or is noone using encryption in their test environments?

**Comment by rullzer** [comment]
@nextcloud/encryption please have a look

**Comment by schiessle** [comment]
I can't reproduce it. The method isDirectoryHandle() is implemented in the parent class https://github.com/nextcloud/3rdparty/blob/4b46a9176e392932702be12060a8c5899e092174/icewind/streams/src/Wrapper.php#L47 and gets called as expected on my test system.

Can you double check that this class and this method exists on your system as well?

**Comment by schiessle** [comment]
I just checked the Nextcloud 14 beta1 zip file and it contains the file and the method as well. How did you installed it?

**Comment by MartB** [comment]
I updated it using the official updater on beta channel.
I will edit this comment with the informations you need.

**Comment by TecJon** [comment]
@schiessle I am getting the same error message. I have tested it using a one-click fresh install on shared web space and upgrading to NC 14 beta 1. I also tested it on fresh install on a virtual server, code directly from nextcloud.com.

Indeed the function exists in 3rdparty/icewind/streams/src/Wrapper.php. I double checked.

Here's the detailed nextcloud.log:

```
{"reqId":"W2HSqNUVmbtbtaKMWYZI1AAAAA8","level":3,"time":"2018-08-01T15:32:56+00:00","remoteAddr":"xx.xxx.x.xx","user":"User","app":"remote","method":"PUT","url":"\/cloud\/remote.php\/dav\/files\/User\/AmazonS3\/New%20folder\/test.txt","message":{"Exception":"Error","Message":"Call to undefined method OC\\Files\\Stream\\Encryption::isDirectoryHandle()","Code":0,"Trace":[{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/lib\/private\/Files\/Stream\/Encryption.php","line":184,"function":"wrapSource","class":"OC\\Files\\Stream\\Encryption","type":"::","args":[null,null,"ocencryption","OC\\Files\\Stream\\Encryption","wb"]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/lib\/private\/Files\/Storage\/Wrapper\/Encryption.php","line":468,"function":"wrap","class":"OC\\Files\\Stream\\Encryption","type":"::","args":[null,"New folder\/test.txt","\/User\/files\/AmazonS3\/New folder\/test.txt",[],"User",{"__class__":"OCA\\Encryption\\Crypto\\Encryption"},{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OC\\Files\\Storage\\Wrapper\\Availability"},{"cache":{"__class__":"OC\\Files\\Cache\\Cache"},"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OC\\Files\\Storage\\Wrapper\\Encryption"},{"__class__":"OC\\Encryption\\Util"},{"__class__":"OC\\Encryption\\File"},"wb",0,0,0,true]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":298,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Encryption","type":"->","args":["New folder\/test.txt","wb"]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":168,"function":"fopen","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["New folder\/test.txt","wb"]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["test.txt",null]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["files\/User\/AmazonS3\/New folder\/test.txt",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/example.com\/cloud\/remote.php\/dav\/files\/User\/AmazonS3\/New%20folder\/test.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/example.com\/cloud\/remote.php\/dav\/files\/User\/AmazonS3\/New%20folder\/test.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/example.com\/cloud\/remote.php\/dav\/files\/User\/AmazonS3\/New%20folder\/test.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/example.com\/cloud\/remote.php\/dav\/files\/User\/AmazonS3\/New%20folder\/test.txt","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/dav\/lib\/Server.php","line":293,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/remote.php","line":163,"args":["\/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/www\/htdocs\/w5487967f\/example.com\/cloud\/lib\/private\/Files\/Stream\/Encryption.php","Line":201,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.13"}
```

Followed by the following error:

```
{"reqId":"W2HSrsJfIeHnvm09TQXA6wAAAA8","level":3,"time":"2018-08-01T15:33:02+00:00","remoteAddr":"xx.xxx.x.xx","user":"User","app":"PHP","method":"GET","url":"\/cloud\/index.php\/settings\/user","message":"Uncaught Error: Class 'Aws\\S3\\ObjectUploader' not found in \/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3ClientTrait.php:46\nStack trace:\n#0 \/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3ClientTrait.php(32): Aws\\S3\\S3Client->uploadAsync('containername', 'New folder\/test...', false, 'private', Array)\n#1 \/www\/htdocs\/w5487967f\/example.com\/cloud\/lib\/private\/Files\/ObjectStore\/S3ObjectTrait.php(77): Aws\\S3\\S3Client->upload('containername', 'New folder\/test...', false, 'private', Array)\n#2 \/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php(589): OCA\\Files_External\\Lib\\Storage\\AmazonS3->writeObject('New folder\/test...', false)\n#3 \/www\/htdocs\/w5487967f\/example.com\/cloud\/apps\/files_external\/lib\/Lib\/Storage\/AmazonS3.php(419): OCA\\Files_External\\Lib\\Storage\\AmazonS3->writeBack('\/www\/htdocs\/w01...', 'New folder\/test...')\n#4 [internal function]: OCA\\Files_External\\Lib\\Storage\\AmazonS3->OCA\\Files_External\\Lib\\Storage\\{closure} at \/www\/htdocs\/w5487967f\/example.com\/cloud\/3rdparty\/aws\/aws-sdk-php\/src\/S3\/S3ClientTrait.php#46","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"14.0.0.13"}
```

**Comment by MartB** [comment]
Hypothesis:
This seems to be broken on File shares (by link) and webdav but not in nextcloud itself.

**Comment by schiessle** [comment]
@MartB 

> Hypothesis:
> This seems to be broken on File shares (by link) and webdav but not in nextcloud itself.

I tried it now with a shared folder access/update/upload files by another user, on a public page and via webdav... all operations work here.

I tried it with 14.0.0 beta 1 from git and from the original zip file downloaded here: https://help.nextcloud.com/t/nextcloud-14-0-0-beta-1-is-here/34424

can you please try to describe the exact steps which lead to this error for you? Thanks!

**Comment by MartB** [comment]
The heck...

**Comment by schiessle** [comment]
Ok, what I did now:

1. Install Nextcloud 14 beta2
2. Enable encryption
3. create two more users (user2 and user3)
4. user1 created /folder1/folder2/test.txt
5. user1 shares folder1 to user2
6. login as user2
7. user2 can read folder1/folder2/test.txt
8. user2 shares folder2 to user3
9. login as user3
10. user3 can read folder2/test.txt
11. user3 creates folder2/test2.txt
12. login as user2
13. user2 can read folder1/folder2/test2.txt
14. login as user1
15. user1 can read folder1/folder2/test2.txt

Is this all correct? At which point does it break for you?

To be honest, I also don't see why the server shouldn't find a method in a class based on the way a file was shared.

**Comment by MartB** [comment]
I cant really reproduce this with a fresh install (due to lack of time), but my playground instance on my public facing server which is experiencing said issue was always getting upgraded through the updater.

Did you try to share by public url, thats what seems to be broken for me.
Everything i do inside the actual nextcloud interface while logged in seems to work.

Trust me this is annoying and i totally understand it sounds weird but it only popped up after i updated to beta 14 so it must be related to nextcloud or the update process.

**Comment by schiessle** [comment]
> Did you try to share by public url, thats what seems to be broken for me.

yes, I shared a folder as public link and both downloaded and uploaded files successfully over the public link.

Do you use any special external storage, 3rdparty apps,... etc?

**Comment by schiessle** [comment]
@icewind1991 do you have any idea maybe?

**Comment by d2dyno** [comment]
Simple to reproduce, same as @MartB : 

- Clean install of the stable branch.
- Enable encryption (default options checked).
- Set branch to beta.
- Run updater.
- Profit. (Unable to upload new files, or download any files).
- Tested on uploading a folder, and a .txt file to the root directory.  1 user installation, no sharing enabled.

Using Docker (Linuxserver container) with unRAID here.

**Comment by danielkesselberg** [comment]
There are two versions for Icewind\Streams:
- https://github.com/nextcloud/3rdparty/blob/master/icewind/streams/src/Wrapper.php
- https://github.com/nextcloud/server/blob/master/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php

The version in files_external is older and does not include "isDirectoryHandle". Maybe this is related to this issue.

**Comment by rullzer** [comment]
Do you all run from git?
If so you need to update the submodules when changing branches.

**Comment by MartB** [comment]
@rullzer nope, just used the official updater from beta branch 13 to beta branch 14.

Maybe something is broken in these update archives?

**Comment by rullzer** [comment]
@MartB unlikely as that is what @schiessle is using to test.

**Comment by rullzer** [comment]
@schiessle can you try your steps with the files_external app enabled?

**Comment by schiessle** [comment]
@rullzer that's it. As soon as I enable the external storage app I can reproduce it. Any idea how to fix this? The problem seems to be introduced with Nextcloud 14, I tried Nextcloud 13 and there it works also with external storages enabled.

**Comment by MartB** [comment]
@schiessle @rullzer 🙏 
Glad you can reproduce it now.

**Comment by rullzer** [comment]
@schiessle I think it is related to https://github.com/nextcloud/server/issues/10430#issuecomment-410542502 because they are not the same version.

Let me see if I can update it and get feedback from @icewind1991

**Comment by rullzer** [comment]
Of course it probably make sense to just not ship it in the 3rdparty one... but lets see.

**Comment by icewind1991** [comment]
core also depends on it

**Comment by schiessle** [comment]
This should be fixed now with Nextcloud 1 beta 3. Please re-open the ticket and/or reply here if the problem still persist for you
