### ISSUE TITLE
Contact list broken layout

### ISSUE THREAD

**Issue by wallenium** [nextcloud/server#10442]
### Steps to reproduce
1. Log in
2. Right top corner, click on contacts icon

### Expected behaviour
The contacts should stay in the popup window. 

### Actual behaviour
![nx14_contacts](https://user-images.githubusercontent.com/472139/43380390-5041a8d0-93d1-11e8-8967-2596a4df2dd0.PNG)
The list is too long or the popup to short. Looks a bit strange

### Server configuration

**Operating system**:
NA

**Web server:**
NA

**Database:**
Art: mysql
Version: 5.5.31

**PHP version:**
7.1.18

**Nextcloud version:**
14.0.0 Beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 13.0.5

**Where did you install Nextcloud from:**
Integrated update Tool

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

### Client configuration
Chrome 67

**Operating system:**
Windows 7

**Comment by rullzer** [comment]
@nextcloud/javascript @nextcloud/designers Seems something that broke recently. I also noticed it in the applist on mobile
