### ISSUE TITLE
Allow to duplicate a file by copying it to the same directory

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#10441]
Related to issue #9931.

It is not currently possible, but I'd love to be able to duplicate a text file + re-name it to .md at the same time while using the copy menu.  System notice that appears to the user is:

> Could not copy "Markdown Examples.txt"; target exists.

but it could become

> "Markdown Examples.txt" already exists; Do you want to Duplicate or Rename the copy?

My request is to allow users to duplicate (copy) and re-name a file within the Copy and Move menu when target already exists.
![duplicate](https://user-images.githubusercontent.com/1787238/43370010-67a87d32-932c-11e8-92c3-82801ffb39c3.png)

**Comment by maghog** [comment]
The need to make a copy of a file in the same folder is common. Is this on the roadmap yet?

**Comment by mhow2** [comment]
> The need to make a copy of a file in the same folder is common. Is this on the roadmap yet?

yes, please ? we need this too.

**Comment by szaimen** [comment]
This is still missing in NC21.0.2

**Comment by rickdoesdev** [comment]
This should work for folders as well.
