### ISSUE TITLE
NC14: core/img/places/contacts-dark.svg missing

### ISSUE THREAD

**Issue by team-a2** [nextcloud/server#10443]
I just recognized, that the file core/img/places/contacts-dark.svg is missing in the git-version of nextcloud 14. If You are using a light background, there will be a "hidden" link to the contacts-search in the upper right of Your nextcloud-instance:
![no-contacts-dark svg](https://user-images.githubusercontent.com/40354103/43383472-66efde12-93db-11e8-863b-f6e09442b87b.png)

Would be nice to get the image back ;-)

**Comment by rullzer** [comment]
@skjnldsv

**Comment by skjnldsv** [comment]
This is weird because the class should still exists. Is the icon loaded in css @team-a2 ?

**Comment by team-a2** [comment]
`#contactsmenu .icon-contacts {
	background-image: url('/apps/theming/css/../../../core/img/places/contacts-dark.svg');
}`

**Comment by skjnldsv** [comment]
@juliushaertl theming? :)

**Comment by team-a2** [comment]
In my instance no theming other to the clean install is activated.

**Comment by juliushaertl** [comment]
@team-a2 You have a grey header instead if the nextcloud blue, so the theming app is doing its job there ;)

I'll have a look

**Comment by team-a2** [comment]
Yes, You are right, I just ment that I do not use a separate custom theme...

**Comment by rullzer** [comment]
What version of NC is this?

**Comment by team-a2** [comment]
NC 14.0.0 Beta1, todays git pull
(problem has already existed in git version before beta1)
