### ISSUE TITLE
Linux client does not synchronize automatically after a fresh reinstall using Ubuntu 18.04 with SSL/TLS/https

### ISSUE THREAD

**Issue by GustavoMarcante** [nextcloud/server#10454]
Hi. I'm using Nextcloud since its lauch.
For a long time, it was running with Ubuntu 16.04 on a Digital Ocean droplet without secure connection (http://mydomain.com).
Now I created a new droplet with Ubuntu 18.04 with a Let's Encrypt SSL Certificate and reinstalled Nextcloud (without snap) following the common instructions (importing files and database).
After that, the mobile app is working fine.
But the Linux desktop client, running in desktops with Ubuntu 16.04 and 18.04, does not start synchronizing automatically.
I try to disable and enable the synchronization at the Nextcloud topbar icon (what worked before) and also logging out and in at the Nextcloud settings windows, and does not work. I need to remove the account and include it again each time I turn on the desktop to make the synchronization starts again.
Then it works normally. Until I close the section.
The client server did not change in any desktop.
The server had PHP 7.0 before and 7.2 now.
The problem happens both with http:// and https:// connection.

### Steps to reproduce
1. Install Nextcloud without snap in Ubuntu 18.04 with Let's Encrypt certificate
2. Install Nextcloud client in Ubuntu 16.04 and/or 18.04 as set an account.
3. Restart the client (desktop).

### Expected behaviour
When logged, starts synchronizing.

### Actual behaviour
Just removing the account and putting it in again makes the synchronizing start (says "no connection").

### Server configuration

**Operating system**:
Ubuntu 18.04
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13.0.4 and 13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install with database import
**Where did you install Nextcloud from:**
It was running in a Digital Ocean droplet with the same configuration (2MB)
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.4.1
  - audioplayer: 2.3.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - checksum: 0.4.0
  - cms_pico: 0.9.7
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.0
  - federatedfilesharing: 1.3.1
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_linkeditor: 1.0.5
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.2.1
  - files_rightclick: 0.8.4
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - ownbackup: 17.5.0
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - comments
  - encryption
  - external
  - federation
  - files_external
  - mindmaps
  - nextcloud_announcements
  - notes
  - systemtags
  - tasks
  - theming
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "criamosjuntos.com",
            "baby.criamosjuntos.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/criamosjuntos.com",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "data-fingerprint": "f38c6db764d05a3ad5527a2455b4b409",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
The problem is using the desktop app (I use Firefox).
**Operating system:**
Ubuntu 16.04 and 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
/var/www/nextcloud/datanextcloud.log has 0 bytes.
</details>

#### Browser log
The problem is using the desktop app, not the browser.

**Comment by GustavoMarcante** [comment]
I think this issue is not related with the ones above (but, who knows...).

**Comment by GustavoMarcante** [comment]
In one notebook, I did a complete uninstall of all files of the Nextcloud client and installed it again. But then I got the same as https://github.com/nextcloud/desktop/issues/172.
It is reported also at https://help.nextcloud.com/t/error-message-could-not-read-system-exclude-file-after-login-in-sync-desktop-client/22729.

**Comment by GustavoMarcante** [comment]
In the last two days, one by one, some accounts/machines started do synchronize.
Maybe this error is associated with many connections at the same time, as they have to check all changes again.

**Comment by kesselb** [comment]
Hey @GustavoMarcante, is this still relevant?
