### ISSUE TITLE
Update from 13.0.4 to 13.0.5 with error as usual while trying to enable app notifications

### ISSUE THREAD

**Issue by cpu2910** [nextcloud/server#10453]
As always I updated the nextcloud (and former the ownlcoud) installation .
And as always the same error occured:

Error | updater | \OC\Updater::failure: notifications: Failed to enable app notifications | 2018-07-30T15:56:29+0200
Error | notifications | OC\HintException: Failed to enable app notifications | 2018-07-30T15:56:29+0200

The updater tries to enable the app 'notifications', despite the app is disabled in my configuration.

**Comment by rullzer** [comment]
@nickvergessen any idea?

**Comment by nickvergessen** [comment]
Is there more information in the error log?

**Comment by cpu2910** [comment]
No, that's all... 
But as said, I got this error on every update (on old owncloud too).
The notifications app is disabled in my installation.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/issues/11648#issuecomment-431148222
