### ISSUE TITLE
in gallery, fileslist-button is not entirely right

### ISSUE THREAD

**Issue by violoncelloch** [nextcloud/server#10458]
![grafik](https://user-images.githubusercontent.com/22591354/43423253-3161d8ba-944c-11e8-815d-cb8bdf31e579.png)
the filelist-button should be at the right border and not aligning the invisible upload box

NC 14.0.0 beta1 and beta2

**Comment by weeman1337** [comment]
I take this one.

@skjnldsv here https://github.com/nextcloud/server/commit/e27e430f1fa756c0425b34611dfa16867ba97029#diff-bf0066932907b556b49ffe55b209a501R585 flex for the `#content` has been introduced.

I'm not sure if every app now has to migrate its styles or it should be changed in the server styles.

**Comment by skjnldsv** [comment]
@weeman1337 does the gallery app fit the new layout as well?
If not, we should fix it :)

Then, we can check if we need/have a min-width of 100vw for the content
