### ISSUE TITLE
Enhancements for ui regression testing

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10456]
Summary of what is left to improve the ui regression testing that was merged with #8357 

- [ ] Fix possible failure due to scroll on click behavior on login page
- [ ] Fix possible failure due to changing time in personal settings
- [ ] Fix possible failure of file-unshare test
- [ ] Automatically comment test status on the pull request
- [ ] installation timeout:
	```
	{
	  "title": "runs",
	  "fullTitle": "install runs",
	  "duration": 90794,
	  "currentRetry": 0,
	  "err": {
	    "stack": "Error: Execution context was destroyed, most likely because of a navigation.\n    at rewriteError (node_modules/puppeteer/lib/ExecutionContext.js:135:15)\n    at <anonymous>\n    at process._tickCallback (internal/process/next_tick.js:188:7)",
	    "message": "Execution context was destroyed, most likely because of a navigation."
	  }
	}
	```
- [ ] Comment on github issues about failures https://github.com/nextcloud/server/pull/10507
- [ ] Fix URL in ["_The result can be found at_" message](https://github.com/nextcloud/server/blob/2f3e18a5e137c1cee2b586336865e520b0eec838/.drone.yml#L778)

**Comment by MorrisJobke** [comment]
Let's move this to 16 - it's an ongoing effort anyways and not bound to an milestone.

**Comment by MorrisJobke** [comment]
@juliushaertl 🏓

**Comment by juliushaertl** [comment]
On my list, but let me remove the milestone, since this is nothing that is actually related to a release.

**Comment by szaimen** [comment]
Are some of those points already fixed or is this issue still valid?

**Comment by juliushaertl** [comment]
The initial attempt of UI testing was dropped as puppeteer was causing too much issues and we mostly use cypress these days in apps, so that would be covered in https://github.com/nextcloud/server/issues/7607 for the server. Closing in favor of that one.
