### ISSUE TITLE
update never runs through

### ISSUE THREAD

**Issue by daniu-de** [nextcloud/server#10450]
Hi,

everytime I start the updater from within nextcloud it stips at step 4 "create backup".

I know how to handle this but it annoys very much. I guess that is a timeout problem

**Comment by MariusBluem** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: [https://help.nextcloud.com](https://help.nextcloud.com)

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at [https://nextcloud.com/enterprise/](https://nextcloud.com/enterprise/)
