### ISSUE TITLE
Header issues with small screens

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10452]
The number of app icons is not properly calculated when loading the page on a small screen. Once resizing everything works as exected, but on initial page load, it looks like this, but the icons should hidden in the 3 dots menu and the avatar should be visible, as there is not enough space:

![screenshot from 2018-07-30 01-00-25](https://user-images.githubusercontent.com/3404133/43399836-53cad6da-940c-11e8-9d9d-740f6f7b8d85.png)

**Comment by weeman1337** [comment]
@juliushaertl it works for me using the latest Firefox/Chrome. The three dots show up directly after loading the page without a resize. What browser are you using?
