### ISSUE TITLE
issues with custom color and dark theme

### ISSUE THREAD

**Issue by violoncelloch** [nextcloud/server#10457]
### Steps to reproduce
1. activate dark theme
2. change color in theming and see dark theme being disabled temporarly
3. go back to files and see only folder icons in new color, top bar in nextcloud blue and dark theme being applied in a strange way (see screenshot)
![grafik](https://user-images.githubusercontent.com/22591354/43422228-5d88c1cc-9449-11e8-98d7-37009c027ee5.png)

### Server configuration
**Nextcloud version:** NC 14.0.0 beta1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

### Client configuration
**Browser:** Firefox

**Comment by nickvergessen** [comment]
A hard refresh is needed and should do the trick.

Seems like we are missing an increment on the scss version variable?

**Comment by violoncelloch** [comment]
@nickvergessen what kind of hard refresh do you mean? - a browser refresh dosen't help

after re-setting a different color with dark theme disabled, the top bar stays nextcloud-blue

**Comment by violoncelloch** [comment]
ahh, without having dark theme enabled, adding an app which places an icon in the top bar did the refresh, but this doesn't work for dark theme

**Comment by rullzer** [comment]
@nextcloud/theming

**Comment by juliushaertl** [comment]
We need to inject variables that come from the OCP\Defaults class in the accessibility app as well https://github.com/nextcloud/server/blob/master/apps/accessibility/lib/Controller/AccessibilityController.php#L144  

similar to https://github.com/nextcloud/server/blob/6686ca9b2a222bc972252d86e39c7a0ced62f158/lib/private/Template/SCSSCacher.php#L289

cc @skjnldsv

**Comment by skjnldsv** [comment]
Fix in #10689

**Comment by violoncelloch** [comment]
for me this issue still exists in RC1
it looks still the same as in the screenshot I posted
