### ISSUE TITLE
'Choose password' prompt doesn't appear in IE when password protection enforced

### ISSUE THREAD

**Issue by gristc** [nextcloud/server#10461]
### Steps to reproduce
1. In Settings/Sharing, enable 'Enforce password protection'
2. Using IE, attempt to share a file or folder.
3. Click the checkbox 'Share link'

### Expected behaviour
Tell us what should happen
The text box that appears should have the words 'Choose a password for the public link' appear.

### Actual behaviour
Tell us what happens instead
The cursor is switched to the text box, but the words do not appear unless you click outside the box somewhere else on the form. This only seems to affect IE. It works in Firefox, Chrome and Edge ok.

This is reproducible in the demo version run on your servers. Our users are finding this confusing and logging support tickets because it's not obvious what they should do.

### Server configuration

**Operating system**:
Whatever your demo site runs

**Web server:**
Whatever your demo site runs

**Database:**
Whatever your demo site runs

**PHP version:**
Whatever your demo site runs

**Nextcloud version:** (see Nextcloud admin page)
Whatever your demo site runs
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Whatever your demo site runs

**Signing status:**
<details>
<summary>Signing status</summary>

```
Whatever your demo site runs
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Whatever your demo site runs
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Whatever your demo site runs
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Whatever your demo site runs

**Are you using encryption:** yes/no
Whatever your demo site runs
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Whatever your demo site runs
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
Whatever your demo site runs
```
</details>

### Client configuration
**Browser:**
IE 11

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
@juliushaertl @skjnldsv can one of you verify? (time to use that fancy browserstack stuff)

**Comment by ChristophWurst** [comment]
> Browser log

Could you provide these @gristc?

**Comment by ChristophWurst** [comment]
I tested on IE11 and it has been fixed in the meantime. I could successfully see and use the password prompt.
