### ISSUE TITLE
App update indicator shows but there is no update

### ISSUE THREAD

**Issue by timscha** [nextcloud/server#10477]
### Steps to reproduce
1. I upgraded NC 13.0.5 to 14 B1 over the Web updater

### Expected behaviour
After successful upgrade I see an upgrade indicator, but the page told me that there is no update available.

### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 14 Beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.0.5

***App list***
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_antivirus: 1.3.1
  - files_fulltextsearch: 0.8.2
  - files_fulltextsearch_tesseract: 0.1.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.2.2
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - fulltextsearch: 0.8.1
  - fulltextsearch_elasticsearch: 0.8.0
  - gallery: 18.1.0
  - groupfolders: 1.2.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - piwik: 0.4.1
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0

Disabled:
  - bookmarks_fulltextsearch
  - camerarawpreviews
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_downloadactivity
  - files_external
  - firstrunwizard
  - onlyoffice
  - ransomware_protection
  - socialsharing_email
  - socialsharing_facebook
  - socialsharing_twitter
  - twofactor_totp
  - twofactor_u2f
  - user_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.timscharner.de",
            "cloud.timscharner.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.timscharner.de",
        "dbtype": "mysql",
        "version": "14.0.0.13",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "log_type": "file",
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/www\/cloud.timscharner.de\/data\/nextcloud.log",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox and Chrome

**Operating system:** Windows and Mac
![nc_update](https://user-images.githubusercontent.com/4650393/43508193-8735c156-956f-11e8-9520-fcb96da26e7e.jpg)

**Comment by rullzer** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
Already fixed by https://github.com/nextcloud/server/pull/10508

**Comment by MaxZiebell** [comment]
I am on the Stable (13.0.6) channel and am getting notification on Nextcloud 14 (since 8 days) and when I follow the link it doesn't show the update button. Is this a bug?
