### ISSUE TITLE
Collabora Online - html/css error

### ISSUE THREAD

**Issue by ReinerNippes** [nextcloud/server#10475]
### Steps to reproduce
1. Install Nextcloud & Collabora Online
2. Open a document
3.

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/15212916/43489163-56986088-951c-11e8-9e4d-4241a70fd57b.png)

### Server configuration

curl -s https://raw.githubusercontent.com/ReinerNippes/nextcloud13/devel/prepare_system.sh | /bin/bash
HOME=/root ansible-pull --clean --force --checkout devel -d /root/nextcloud -i 'nextcloud' -U https://github.com/ReinerNippes/nextcloud13.git nextcloud.yml -e "dhparam_numbits=1024" -e "fqdn=$(hostname -f)" -e "ssl_certificate_type=selfsigned"

Update to Beta14

**Comment by rullzer** [comment]
Shoudl be fixed with https://github.com/nextcloud/server/pull/10483
