### ISSUE TITLE
Support invite-rsvp-checkstatus calendar workflow with exchange

### ISSUE THREAD

**Issue by dphi** [nextcloud/server#10488]
It would be great if the nextcloud server caldav component would be more compatible with Exchange(+Outlook) users.

**NC invites Outlook**
1. Invitation is send to Exchange
1. No Accept/ Decline/ Tentative buttons visible that would update 
Expected behavior: Accept/ Decline/ Tentative buttons are visible and these responses are being send back to the inviting user

**Outlook invites NC**
1. Invitation is send to NC
1. Aceept/ Decline/ Tentative buttons are visible
1. The status is visible in the NC client
1. The RSVP status update is send via SMTP to exchange.
1. The iCal-Reply.ics attached to the previous mail is not recognised by Exchange as such and thus not used to update the RSVP status of the calendar entry
Expected behavior: Exchange detects the ical-reply.ics as such and updates the participants RSVP status.

The RSVP buttons developed for NC14 do solve this.

(I tested using macos 10.13 as a client for NC.)

**Comment by dphi** [comment]
which information is missing?

**Comment by kesselb** [comment]
> which information is missing?

:robot: does not work as expected

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
