### ISSUE TITLE
apps.nextcloud.com down makes apps page on NC unusable

### ISSUE THREAD

**Issue by TecJon** [nextcloud/server#10499]
Currently the website apps.nextcloud.com is down. This makes the usage of the apps page of a NC installation impossible. Endless loading only with some luck one can work on locally installed apps and enable/disable them.

NC: 14 beta 1

**Comment by vc7ee** [comment]
apps.nextcloud.com is down again. First priority would be to get the site up, second to make the apps page independent of apps.nextcloud.com
NC: 16.0.1

**Comment by kesselb** [comment]
Thanks for reporting 👍

Closing in favour of https://github.com/nextcloud/server/issues/14926

**Comment by basvandenbrink** [comment]
@kesselb The request you linked is about increasing the timeout for slow connections. This request is about the app list not loading if apps.nextcloud.com is down.

Currently, this is the case. Even if apps.nextcloud.com is down, I would like to manage my installed apps in the admin console.

**Comment by kesselb** [comment]
A proper fix #14926 will work for slowness and unavailability. As said pull requests are always welcome.
