### ISSUE TITLE
Nextcloud Very Weak Password Notification

### ISSUE THREAD

**Issue by sentabi** [nextcloud/server#105]
Fresh install nextcloud 

![very weak password](https://cloud.githubusercontent.com/assets/203196/16073044/33ec0598-330e-11e6-9118-19f18482bb09.png)

UI still said my password very weak, sample of my 'weak password'
```
JAJrHd4B%bKakk*FgUY4d$
```

**Comment by LukasReschke** [comment]
That seems like a bug in the Javascript there. I can reproduce this locally.

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
Obviously this is a very weak password :) ... Just kidding. I will check it our.

**Comment by MorrisJobke** [comment]
Fix is in #111
