### ISSUE TITLE
Bulk import of about 400 randomly fails

### ISSUE THREAD

**Issue by AuspeXeu** [nextcloud/server#10505]
I get the following errors when I try to import around 400 contacts.

![screen shot 2018-08-02 at 09 51 14](https://user-images.githubusercontent.com/2115696/43573518-c9515df0-9639-11e8-9611-99917933add1.png)

I tried the same procedure several times and the contacts that get rejected are not always the same which leads me to believe that there is some rate limiting/queueing maybe needed during imports of larger contact lists?

**Comment by skjnldsv** [comment]
@AuspeXeu Maybe your server is not responding fast enough.
The old contact app was pushing all the files all at once, which could lead to an overflow on the server. The new 3.0.0 have a rate limiter to ensure stability. Could you try again with the 3.0.0 beta?

**Comment by AuspeXeu** [comment]
@skjnldsv I'd rather wait until you are out of beta and have a stable 3.0.0 if that's ok since we are using this in production.

**Comment by MorrisJobke** [comment]
3.0.0 is out: https://apps.nextcloud.com/apps/contacts

Please try again. if this is still happening please reopen this ticket. Thanks
