### ISSUE TITLE
.htaccess warnings after upgrade to 9.1.0.16

### ISSUE THREAD

**Issue by mistersixt** [nextcloud/server#1051]
Hi all,

I have just upgraded from version 9.0.53.0 to version 10.0.0 (although in config.php I can see 9.1.0.16). Anyway, the upgrade itself went without any issues, but within the administration page this warning suddenly shows up:

"Dein Datenverzeichnis und deine Dateien sind wahrscheinlich vom Internet aus erreichbar. Die .htaccess-Datei funktioniert nicht."

I am running lighttpd by the way, the corresponding config part is as follows:

...
$HTTP["url"] =~ "^/nextcloud/data/" {
        url.access-deny = ("")
}
$HTTP["url"] =~ "^/nextcloud($|/)" {
        dir-listing.activate = "disable"
}
...

The .htaccess files located in the /nextcoud/ root directory as well as the one provided in /next/cloud/data/ are the ones shipped with the package.

Is this a false-positive or something? 

Any help is welcome,

kind regards, mistersixt.

**Comment by LukasReschke** [comment]
Please fill out the issue template. Thanks a lot.

**Comment by mistersixt** [comment]
### Steps to reproduce
1. Upgrade from 9.0.53.0 to 9.1.0.16

### Expected behaviour
.htaccess permission should be valid

### Actual behaviour
Warning: "Dein Datenverzeichnis und deine Dateien sind wahrscheinlich vom Internet aus erreichbar. Die .htaccess-Datei funktioniert nicht."

### Server configuration
Debian Wheezy 64 Bit
1.4.31-4+deb7u4
MariaDB 5.5.X
PHP 5.6.25
Nextcloud version: 9.1.0.16 alias 10.0.0
Updated from an older Nextcloud/ownCloud or fresh install: 9.0.53.0
Where did you install Nextcloud from: official website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
$ php occ app:list
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.3.3
  - comments: 1.0.0
  - contacts: 1.3.1.0
  - dav: 1.0.0
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc1c9d0ca8dd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.morbitzer.de"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "nextcloud",
        "mail_domain": "morbitzer.de",
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "log_authfailip": true,
        "trashbin_retention_obligation": "auto",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.release.channel": "stable"
    }
}

</details>

**Are you using external storage, if yes which one:** --

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** --


### Client configuration
**Browser:**
Firefox 48.0

**Operating system:**
Debian Jessie

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

... nothing ...

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

... nothing related to the issue mentioned ...

</details>

**Comment by michag86** [comment]
@mistersixt The test normally tries to access "[url-to-nextcloud]/data/htaccesstest.txt".
What's the result in your case? If protection is working this results in 403.

**Comment by mistersixt** [comment]
Ok, I now know what it is: I have an option in lighttpd.conf to redirect the error handling to a different web page (option "server.error-handler-404" in lighttpd.conf), when disabling that option to get back the default "403 - Forbidden" message the warning in Nextcloud does no longer appear.

So this obviously changed from 9.0.X to 9.1.X.

Thanks for the hint,

Kind regards, mistersixt.

**Comment by michag86** [comment]
@mistersixt So this issue can be closed?

**Comment by mistersixt** [comment]
I recommend to put an additional (or different) check in place as the current functionality in fact returns a wrong value. What about putting some data into that file, and when being able to read the content of htaccesstest.txt then clearly something is wrong.

In all other cases the issue can be closed.

Kind regards, mistersixt.

**Comment by MorrisJobke** [comment]
We changed the way this is handled to the described way.
