### ISSUE TITLE
Transfer ownership of specific files or folders

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#10511]
Would it be possible to add an option to transfer only specific files or folders when using `files:transfer-ownership`? Use cases:

- An employee left, but had personal data that should not be transferred
- An employee left, but had multiple projects that should now be delegated to multiple people (not a single person replacement)

Or is there a good way to accomplish this with the current functionality?

**Comment by rullzer** [comment]
Basically this is in now.
