### ISSUE TITLE
Date picker is not accessible

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10512]
When trying to set a expiration date for share links, the date picker is not accessible, since it is hidden behind the sidebar.

@nextcloud/designers

**Comment by skjnldsv** [comment]
Hum, I'm almost sure I fixed it on the add note to share.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/commit/3a11c26cb49c7d5de3410075d86e165a8452a761#diff-786abfdec65b6ba7b37e0daff7bc3b5eR533

Apparently yes

**Comment by violoncelloch** [comment]
I can confirm the behaviour @juliushaertl describes

**Comment by juliushaertl** [comment]
@skjnldsv Probably it got changed somewhere else then? The app sidebar has a z-index of 1500, so the 500 from the datepicker won't work:
![image](https://user-images.githubusercontent.com/3404133/43630202-e532faf8-96ff-11e8-93e9-a2f99519f43c.png)

**Comment by skjnldsv** [comment]
@juliushaertl fixed in https://github.com/nextcloud/server/pull/10515
