### ISSUE TITLE
strange behaviour of shares view details in sidebar

### ISSUE THREAD

**Issue by violoncelloch** [nextcloud/server#10516]
### Steps to reproduce
1. create a shar to an other user
2. go to "shared by me"
3. click on the profile image of the other user
4. see resharing is not allowed (and other settings missing on clicking on the three dots menu even though I'm the owner of the share) - see screenshot
![grafik](https://user-images.githubusercontent.com/22591354/43611699-46ecd756-96aa-11e8-828d-5d085ba8bc7f.png)

### Server configuration
**Nextcloud version:** 14.0.0 beta2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

### Client configuration
**Browser:** Firefox

**Comment by violoncelloch** [comment]
at least regarding the second part, #10398 seems related

**Comment by violoncelloch** [comment]
as #10398 is fixed and I assume the second part of this issue is fixed with this, I updated this issue removing this part

**Comment by blizzz** [comment]
@violoncelloch https://github.com/nextcloud/server/pull/10700 should fix this. Could you confirm?
