### ISSUE TITLE
Long database names in apps break the update

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10518]
Apps that have a to long identifier name break the update.

So far I found:
- gpxmotion
- groupfolders
- mail https://github.com/nextcloud/mail/issues/1002
- notes
- music

Ref https://github.com/nextcloud/server/pull/10221

Is there anything we could do about that to avoid having the update stopped with those long names? Like can we just enforce the check on oracle and maybe only log a warning on other database types where this is not an issue?

Disabling the app also doesn't work, since the check is executed anyway.

cc @nickvergessen

**Comment by nickvergessen** [comment]
> Like can we just enforce the check on oracle and maybe only log a warning on other database types where this is not an issue?

The thing is that would just obsolete the check all together, because no one of us ever installs oracle or checks the logs.

But yeah I will look into how we can improve the situation, so apps can have a compatibility upgrade going forward.

But also Note, if you make a new migration to fix your database layout, oracle still can't install, because the old table names you are using would need to install because migrations are applied incremental, not all combined into one batch.

**Comment by newsyrom** [comment]
i am having the same problem with ownbackup also.

**Comment by icewind1991** [comment]
A bit problem with this is that it doesn't limit the checks to apps that are currently enabled, meaning that you can't disable the problematic app and continue the upgrade.

**Comment by icewind1991** [comment]
Given how it checks against the entire database for each migration and not just the changed tables, I'm not even sure if you can solve this in the app if a core migration is triggered first.

**Comment by nickvergessen** [comment]
Work around for beta3: https://github.com/nextcloud/server/pull/10553

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/10554 changes it to only check tables that are touched by a migration

**Comment by rullzer** [comment]
Fixed for 14 with #10553 
Lets fix properly for 15 with #10555

**Comment by andyxh** [comment]
Getting this error message 

![image](https://user-images.githubusercontent.com/24574019/43857438-ea45e4d2-9b10-11e8-88bd-bcc638e0fd2c.png)

**Comment by rullzer** [comment]
@andyxh yes it is not released yet. Beta3 will be fixed. Which is scheduled for tomorrow.

**Comment by andyxh** [comment]
Thank you!

**Comment by shiftgeist** [comment]
It's been a while

**Comment by nickvergessen** [comment]
Remove Oracle from support database list to get rid of it.

**Comment by code1x1** [comment]
@nickvergessen 
Where do I have to remove Oracle from support database list?

**Comment by nickvergessen** [comment]
https://docs.nextcloud.com/server/latest/developer_manual/app_development/info.html

Check your info.xml file and add the database dependencies
