### ISSUE TITLE
layout.public.php is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#10528]
Not sure where that file is used, but it spams our sentry instance with quite some log messages:

* Undefined index: header-classes:
https://github.com/nextcloud/server/blame/84c46dd3dd9a9b20d066ea704593a96ff0db0523/core/templates/layout.public.php#L33
* Undefined index: user_displayname
https://github.com/nextcloud/server/blame/84c46dd3dd9a9b20d066ea704593a96ff0db0523/core/templates/layout.public.php#L3
* "Undefined variable: template" see next for details
* Call to a member function getHeaderTitle() on null
https://github.com/nextcloud/server/blame/84c46dd3dd9a9b20d066ea704593a96ff0db0523/core/templates/layout.public.php#L38

@juliushaertl @danxuliu @skjnldsv as authors of the file. Which page is using this?

**Comment by juliushaertl** [comment]
From the sentry log it seems that some public pages like the calendar use 'public' as $renderAs parameter in the TemplateResponse constructor, which leads to loading the layout.public.php file. That should instead only happen if a PublicTemplateResponse is used. I'll look into it.
