### ISSUE TITLE
13.0.5 to 14 beta2 upgrade error

### ISSUE THREAD

**Issue by laurentiu2** [nextcloud/server#10520]
Update to 14.0.0 Beta 2

InvalidArgumentException: Index name "oc_passman_credentials"."passman_credential_vault_id_index" is too long.
Detailed logs
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
InvalidArgumentException: Index name "oc_passman_credentials"."passman_credential_vault_id_index" is too long.

Tried to update today, got this error on screen.

**Comment by MorrisJobke** [comment]
> InvalidArgumentException: Index name "oc_passman_credentials"."passman_credential_vault_id_index" is too long.

We removed this in beta3 again I think to not fail hard, but to show it to the developers of apps instead. So this one can be closed for now.
