### ISSUE TITLE
InvalidArgumentException: Table name "oc_sensorlogger_device_data_types" is too long.

### ISSUE THREAD

**Issue by J0kerFace** [nextcloud/server#10524]
The Upgrade from 13.0.5 to 14.0.0 Beta 2 failed with this Error:

InvalidArgumentException: Table name "oc_sensorlogger_device_data_types" is too long.

PHP  7.1.20
MySQL 5.6.41
nginx/1.11.10

**Comment by nickvergessen** [comment]
See #10518
