### ISSUE TITLE
Update 13.0.5 Error: Specified key was too long

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/server#10535]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by snakyjake1** [comment]
I did follow:
https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html#mariadb-support

It's listed as "This is even more experimental."  Perhaps part of the problem?

**Comment by kevkha** [comment]
I observer the same issue upgrade from 13.0.4 to 13.0.5 on DietPi.
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

Any work around for this issue? Currently, UI stock at Start Upgrade screen. Thanks in advance.

**Comment by brainchild0** [comment]
I am running from a shared Maria cluster.  I only have permissions to change settings within the particular database in the cluster, not global variables.  I currently experience this issue and cannot apply the suggested resolution.  The  above implies the shared case is not supported, but naturally, such support is preferable from a feature standpoint.  I am not aware of whether Nextcloud expressly supports shared hosting, but I have understood that this kind of deployment has an active user base.

**Comment by kesselb** [comment]
Thank you for reporting this issue :tada: 

See this issue for more information https://github.com/nextcloud/server/issues/15058
