### ISSUE TITLE
Email notification is not sent upon directory share to group of users

### ISSUE THREAD

**Issue by abalage** [nextcloud/server#10534]
### Steps to reproduce
1. Create a group of users: foobar
2. Set up email notifications for shared files or directories for every user in group foobar. (either user-by-user or global for new users) 
3. Share a directory with group foobar

### Expected behaviour
Email notification should be sent to every member of group foobar.

### Actual behaviour
No emails are being sent. No connection to SMTP server. (postfix logs checked)

However I also experienced that in case I explicitly add users one by one to the share instead of set the group, email notifications are going to be sent out as expected.
### Server configuration

**Operating system**:
Debian Stretch
**Web server:**
reverse proxy + backend are both nginx:1.14 official images from docker hub
**Database:**
mariadb-10.2.15
**PHP version:**
7.1.20: custom docker image based on official php:7.1-fpm docker image from docker hub
**Nextcloud version:** (see Nextcloud admin page)
13.0.5.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
continuously updated from owncloud since the very first version of nextcloud was available
**Where did you install Nextcloud from:**
Manual install.
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - bruteforcesettings: 1.1.0
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - registration: 0.4.2
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - files_downloadactivity
  - spreed
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR",
            "HTTP_X_REAL_IP"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "trashbin_retention_obligation": "1",
        "default_language": "hu_HU",
        "cache_path": "\/var\/tmp\/",
        "loglevel": 1,
        "theme": "",
        "maintenance": false,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
Firefox 61
**Operating system:**
openSUSE Leap 15
#### Web server error log
<details>
<summary>Web server error log</summary>

```
sorry.. nope. there are nothing exciting
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
sorry... nope. there are nothing exciting or exception compared to normal usage
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
let me know if this is really a must
```
</details>

**Comment by rullzer** [comment]
@nextcloud/sharing @nickvergessen

**Comment by sourabhsaha1989** [comment]
I also have the same problem. Can Someone provide any solution???

**Comment by wiswedel** [comment]
Can still be reproduced in 18b2

**Comment by wiswedel** [comment]
> Can still be reproduced in 18b2

Problem still persists in 18b3

CC @nextcloud/server-triage

**Comment by wiswedel** [comment]
This bug is still present in 18.0.0. Can anyone please pick this up urgently? @nextcloud/server-triage

**Comment by rullzer** [comment]
We never had direct e-mails for group shares.
But once cron ran you should get an activity mail at some point.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
