### ISSUE TITLE
Update from latest 13 branch to Nextcloud 14 Beta 2 crashes

### ISSUE THREAD

**Issue by olliware** [nextcloud/server#10533]
InvalidArgumentException: Index name "oc_mail_collected_addresses"."mail_collected_addr_userid_index" is too long.

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet 
Das Datenbankschema wird aktualisiert
InvalidArgumentException: Index name "oc_mail_collected_addresses"."mail_collected_addr_userid_index" is too long.

**Comment by olliware** [comment]
Neither works via the command line via ./occ upgrade BTW...

**Comment by rullzer** [comment]
Yep lets continue in https://github.com/nextcloud/server/issues/10518
