### ISSUE TITLE
Feature Request: allow image Preview to apply to folders

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#10544]
This request is to apply shared url `/preview` functionality to parent **folders** containing multiple images + shared by URL.  Currently only individual images are supported.  This could create a full screen, possibly embedded, slideshow in the browser, [especially if users can move left or right between photos as mentioned in Gallery issue #310](https://github.com/nextcloud/gallery/issues/310)

[Image shared via url.](https://cloud.disroot.org/s/RSZgiiS4AmpicEF)
![example](https://user-images.githubusercontent.com/1787238/43690946-1f174264-98c8-11e8-891a-13ca7903d568.png)

Image shared via url with `/preview` appended
![](https://cloud.disroot.org/s/RSZgiiS4AmpicEF/preview)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by JackDinn** [comment]
This was the whole reason i spent the last couple of months figuring out how to get it all working. I suppose at least i can manually add the /preview but it sucks real bad each time as i always forget and then have to edit my posts.
