### ISSUE TITLE
NextCloud Themening => CSS/icons/Folder-Icon

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#10540]
Hi,

### Steps to reproduce
1. download Theme
2. implant theme under Config.php 'theme'=>''
3. Start the nextcloud instance
and try to change the Folder Icon onto your theme 

### Expected behaviour
Tell us what should happen
If you build up your Theme and play around, 
can you setting up via css the Icons, which place and icon file it is use
and the place where it is take 

### Actual behaviour
You can not exchange/replace the Directory/Folder Icon via css 
because it is hardcoded .. or not ? Isn't it ?

### Server configuration
**Operating system**:
Updatet OpenMandriva 3.03
**Web server:**
Latest Apache
**Database:**
MariaDB
**PHP version:**
7.2.3 (cli) (built: Mar  6 2018 23:45:47) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.3, Copyright (c) 1999-2018, by Zend Technologies
**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated..
**Where did you install Nextcloud from:**
and original-location

![screen 00002](https://user-images.githubusercontent.com/7925717/43684819-62dd90dc-98a7-11e8-9291-9568ac62075c.jpg)

My NextCloud RealTime cloud theme
http://blackysgate.de/files/folder-root/nextcloud/

**Comment by juliushaertl** [comment]
Changing the icons requires them being named the same way the original icons are. I see no point in renaming them, it is just additional effort without providing any benefit. Therefore, closing.

**Comment by blackcrack** [comment]
@juliushaertl 
jetzt versuch ich es mal auf deutsch,
wie kann ich die Verzeichnissicons setzen ? ich seh aber nur ein verweis direct im code.
soll das via icons.css gehen weil , in dem Bild siehst du, daß der Pfad direct angegeben ist und 
ich habs schon per css probiert, geht aber nicht, wie kann ich die Verzeichnissicons und mime icons ändern über meinem theme-verzeichniss damit ich meine png's einbinden kann als verzeichnissicons ?

liebe Grüße
Blacky

**Comment by danielkesselberg** [comment]
I guess its not possible to use a png as folder icon ([because the icon path is always $identifier.svg](https://github.com/nextcloud/server/blob/7bc28f14de8c3d77ec611a4ffd8ad48dc6093cea/core/js/mimetype.js#L72)). Other themes (e.g. https://github.com/mwalbeck/nextcloud-breeze-dark/tree/master/core/img) just place their own folder.svg in core/img.

**Comment by juliushaertl** [comment]
Yes, mimetype icons need to be svg with the original file name to work properly in themes.

**Comment by blackcrack** [comment]
1. it is svg, take a look on the picture on top where it is show in the IE,
and by side, i have build 2 different themes for KDE/plasma ;)
https://store.kde.org/search?projectSearchText=blacky (just for info)

2nd, something must be buggy or goes wrong in the javascript or in the code, because the 
Folder it is not change if the folder-icon seted up. 
Please take a look in the Picture 

i guess in the code should remove 
``` style="background-image:url(/nextcloud/img/filetypes/folder.svg);"```
and add in the 
```"class"="thumbnail icon-folder svg"``` 
```("class"="thumbnail icon-$filetype svg")```
or an other folder who it is need by folder type

the other file-explorer/filebrowser or .app-files app code should be checked/be reviewed 
to be compatible with the css-themening file and like i guess it is hardcoded (like it show) but @juliushaertl you told, it is a Javascript where set it up the code, well,
this should be checked to works correctly and to be compatible with the css in the theme icon.scss
to be able for change and works more correctly. 
(i hope you have understand now more better like i have now explain it)

![folder-svg-2](https://user-images.githubusercontent.com/7925717/43882521-2c6b319c-9bb0-11e8-883b-6e1b5b9bc4cb.jpg)

As suggestion:
maybe it is better if create a mimetype.scss and a icon.scss and a mimetype folder in the theme-folder
to have the possible for more different mimetypes.. and i guess it will comes to have many different mime-types ;)

**Comment by juliushaertl** [comment]
Please read the documentation regarding changing mime type icons in themes: https://docs.nextcloud.com/server/13/developer_manual/core/theming.html#how-to-update-custom-mimetype-icons
