### ISSUE TITLE
Display image shared urls with /preview appended by default

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#10545]
My request is to append /preview to all shared image URL's by default.  Currently it must be manually added, which feels like a hack.

[Default image shared via url.](https://cloud.disroot.org/s/RSZgiiS4AmpicEF)
![example](https://user-images.githubusercontent.com/1787238/43690946-1f174264-98c8-11e8-891a-13ca7903d568.png)

Image shared via url with `/preview` appended
![](https://cloud.disroot.org/s/RSZgiiS4AmpicEF/preview)

**Comment by szaimen** [comment]
@nextcloud/sharing is this feasible?

**Comment by sunjam** [comment]
At some point it would be nice for sharing photos to display the image
preview by default.  Not a priority by any means

**Comment by JackDinn** [comment]
so whats happening here? Nothing? Can you please implement the attachment of the word /preview to the link URL rather than us having to type the bloody thing? Unless iv missed something in my searching.
