### ISSUE TITLE
Cannot restore deleted files saved on external storage

### ISSUE THREAD

**Issue by tomtomas99911** [nextcloud/server#10547]
When I delete file from external storage (local disk) I cannot restore it from trash because Nextcloud is trying to get this file from my primary storage (S3)...

Error in log, trying to restore file from primary S3 storage which is bad:
"....."php","message":"fopen(https:\/\/s3.[*sensitive value*].com\/nextcloud\/urn%3Aoid%3A2085870): failed to open stream: HTTP request failed! HTTP\/1.1 404 Not Found\r\n at \/var\/www\/nextcloud\/lib\/private\/Files\/Obj...."

### Steps to reproduce
1. Create file on defined external storage (local disk)
2. Delete file
3. Ty to restore file

### Expected behaviour
File restored

### Actual behaviour
Error: "Cannot restore file"

### Server configuration
NX 13.0.0

**Operating system**:
Debian

**Web server:**
Apache 2.4.5.

**Database:**
MariaDB

**PHP version:**
PHP 7

**Comment by tomtomas99911** [comment]
The same problem on Nextcloud 14.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
