### ISSUE TITLE
Feature Request: Add optional message to shared files and folders via email

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#10559]
Nextcloud 13.0.5

It'd be extremely helpful to optionally add a message to a shared file or folder sent from within Nextcloud via email.  Being able to add a message is default behavior in Google Drive, Dropbox and Evernote.

![message](https://user-images.githubusercontent.com/1787238/43739641-9e79d1b0-997d-11e8-803d-fb210e369f09.png)
**or**
![2](https://user-images.githubusercontent.com/1787238/43739821-2fd7804e-997e-11e8-8f2f-460d06cbea2a.png)
![drive](https://user-images.githubusercontent.com/1787238/43739696-ce708364-997d-11e8-8e09-afd069e6d3e6.png)
Here is how it looks to share a note via Evernote...
![evernote-sharing](https://user-images.githubusercontent.com/1787238/43739493-1d62ee40-997d-11e8-823c-7509cff4d734.png)

**Comment by MorrisJobke** [comment]
Was added with #10218 for 14.
