### ISSUE TITLE
"Content-Security-Policy" with CloudFlare persists in version 14 (Beta)

### ISSUE THREAD

**Issue by ykcab** [nextcloud/server#10557]
with DNS behind cloudflare, the same issue of "Content-Security-Policy" is again present in version 14 Beta.
--> 
### Steps to reproduce
1. have your domain on Cloudflare
2. when you go to your browser: hxxps://your[.]domain[.]com, for the first time you will be able to configure/finish the installation but after the initial setup you will, the login button has no effect at all.
3. login with you local IP (internal lan/wifi), no issue
### Actual behavior
see attached image and similarly to this previous version issue (https://github.com/nextcloud/server/issues/4840)

### Server configuration

**Operating system**:
Debian Stretch 9
**Web server:**
NGINX 1.12
**Database:**
MariaDB
**PHP version:**
PHP7.0
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Beta 1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Installation
**Where did you install Nextcloud from:**
Official nextcloud web page

this image show the problem
<img width="1332" alt="screen shot 2018-08-05 at 5 12 32 pm" src="https://user-images.githubusercontent.com/16911521/43733873-08b19684-9984-11e8-9966-94eea3ab686d.png">

**Comment by rullzer** [comment]
As stated in https://github.com/nextcloud/server/issues/4840 this is indeed unsupported and will most likely break.

On top of that this means that cloudflare can do MITM attacks as you allow it to rewrite your html.

**Comment by ykcab** [comment]
@rullzer Cloudflare is a legitimate CDN service, why would you flag them to impersonate with MITM attack?

**Comment by rullzer** [comment]
I'm not saying they are doing it. I'm saying they can do it in your setup. Which is something you should not want with your data.

**Comment by kesselb** [comment]
> As stated in #4840 this is indeed unsupported and will most likely break.
