### ISSUE TITLE
Browser alert box for log in when timed out

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1055]
Some times after returning from suspend I see this:
![capture du 2016-08-25 19-56-13](https://cloud.githubusercontent.com/assets/925062/17980843/70ad7720-6b01-11e6-89a7-6d6fdc1d7842.png)
(»Piwik« is the branded name of my Nextcloud ;)

This should not happen. If not automatically logged in, you should see the log in screen. Never such a browser dialog.

cc @LukasReschke @MorrisJobke

**Comment by jancborchardt** [comment]
Also, when redirected to the log in screen, the username should automatically be prefilled.

**Comment by MorrisJobke** [comment]
Looks like the redirect didn't properly get executed. Was this in the files app?

**Comment by MorrisJobke** [comment]
I have not seen this in the past anymore. So this seems to be gone.
