### ISSUE TITLE
OCSResponse cleanup

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#1056]
Currently we have the OCSResponse in OCP https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Http/OCSResponse.php

However I question the use of this. Since people writing OCS code will use the OCSController which takes a DataResponse: https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Http/OCSResponse.php

On top of that the first OCSResponse parameter is the format string https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Http/OCSResponse.php#L57 which is weird since it is the job of the AppFramework/Controller to set this properly. When I'm writing my endpoint I don't want to care. I just want to return data.

So what I propose:

1. Deprecate OCSResponse in OCP
2. Create an internal OCSResponse type that does the correct magic

Good/bad idea? Comments? @BernhardPosselt @LukasReschke @nickvergessen @MorrisJobke

**Comment by rullzer** [comment]
I assume your silence means go for it ;)
I'll tackle this soonish

**Comment by nickvergessen** [comment]
:+1:

**Comment by nickvergessen** [comment]
But I'd just do 1. now, and waste no more time with it, aka we don't need an OCSResponse you said, so no need to write internal magic code for it?

**Comment by rullzer** [comment]
Well we use it in the middleware etc. But we can clean that up of course as well.
