### ISSUE TITLE
UI and functionality breaks when updating apps one after another 

### ISSUE THREAD

**Issue by realies** [nextcloud/server#10562]
When clicking the `[Update to XX]` app update button on multiple apps quickly one after another, Nextcloud sometimes updates the first couple and leaves the rest of the UI buttons stuck in an `[Updating...]` state.

I have just reproduced this on a 13.0.5 instance (latest linuxserver/nextcloud container + latest official postgres container), but this time it seems that for 5 apps, 2 have updated fine and the remaining 3 had buttons stuck on `[Updating...]`, surprisingly after updating the page not long after noticing the buttons don't change, I was greeted with a "Apps up to date" statement.

Assumed that the process has been completed in the background and the response to the buttons did not occur for some reason, but a few minutes later I went back to the Apps update page and saw the same 3 apps that I thought were updated there.

This time around I brought up the network console and found out that only 1 of the 3 new requests to `index.php/settings/ajax/updateapp.php` returned `200 OK` with more details in the response and the remaining 2 replied with `503 Service Temporarily Unavailable` and HTML with a status message that Nextcloud is in maintenance mode.

My conclusion is that some of the apps request for Nextcloud to go into maintenance mode for them to successfully complete an update. I also think the UI should not break the way it does and these update request should either be queued somewhere or for the buttons to reset their state back to an active `[Update to XX]`, most useful out of all for me would be an auto-updating procedure that could be triggered automatically via the standard background jobs or at least an `[Update all]` button.

**Comment by juliushaertl** [comment]
This has been fixed with the new apps management in 14.
