### ISSUE TITLE
Enhancement: Folder details in Files app + NC app on Android

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#10576]
It would be very beneficial to be able to see some more details of folders, for example how many files that are in if.

![screenshot_20180807-225958_opera touch](https://user-images.githubusercontent.com/1469150/43802458-20801e30-9a96-11e8-8044-5a2104f41194.jpg)
As you see in the screenshot only total size is visible. Here I'd like to have "Contains 1234 files, 7 folders".

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
