### ISSUE TITLE
externalapi.php, xcauth.py, ejabberd

### ISSUE THREAD

**Issue by SparkyNZL** [nextcloud/server#10579]
### Steps to reproduce
1. install xcauth
2.test xcauth with the following
3. 404 error externalapi.php

./xcauth.py --config-file /etc/xcauth.conf --auth-test admin nextcloud password
2018-08-08 19:59:01,591 DEBUG: Start external auth script 1.2.0- for ejabberd with endpoint: https://nextcloud.borty.co.nz/apps/ojsxc/ajax/externalApi.php
2018-08-08 19:59:01,592 DEBUG: Opening database connections
2018-08-08 19:59:01,593 DEBUG: Not a token (len: 6 != 23)
2018-08-08 19:59:01,601 INFO: Starting new HTTPS connection (1): nextcloud
2018-08-08 19:59:01,634 DEBUG: "POST /apps/ojsxc/ajax/externalApi.php HTTP/1.1" 404 317
2018-08-08 19:59:01,636 INFO: UNREACHABLE: Cache says password for admin@nextcloud is False

### Expected behaviour
Tell us what should happen
This should post to the URI above and get a TRUE back if the password is correct. but this is not the case as i know the password i am using is correct. Im trying to problem solve the issue im having with the external xmpp server (ejabberd) and xcauth

### Actual behaviour
Tell us what happens instead
fails
### Server configuration

**Operating system**:
Ubuntu 16.04 LTS
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7.0.30ubuntu
**Nextcloud version:** (see Nextcloud admin page)
13.05
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
Github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Please submit this issue to the related app.

**Comment by SparkyNZL** [comment]
I thought I was, xcauth and ejabberd work fine. It appears there could be an issue at the nextcloud end. Hence why I've posted it here.



Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by danielkesselberg** [comment]
> POST /apps/ojsxc/ajax/externalApi.php

You may ask the people at https://github.com/jsxc/jsxc. Endpoint u posted is not a part of nextcloud server (this repository)
