### ISSUE TITLE
External S3 storage doesnt get connected on NC13

### ISSUE THREAD

**Issue by petrk94** [nextcloud/server#10575]
Hello,
In the hope to find here an answer, Im want to share the issue here.
Im using Nextcloud 13.0.5 and want to use external storage on my NC instance.
As external storage I want to use gridscale S3 compatible object storage. Unfortunately I dont get it successfully connected, but with S3 Browser its working without problems. Even the support from gridscale could not find a solution at the moment.

I have it installed on a Shared Host with CentOS 6
PHP 7.1

I hope you can help me or tell what you need to know, so I can provide the information.

Thanks

**Comment by kesselb** [comment]
Still an issue with Nextcloud 18/19/20?

**Comment by petrk94** [comment]
@kesselb already resolved
