### ISSUE TITLE
Icon "confirm-white" is missing

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#10583]
The icon _confirm-white_ [was removed when the SVG color API was introduced](https://github.com/nextcloud/server/pull/9984/commits/29ff7efe9a5be16b133a1ee4e43d6d2155b6a21c#diff-6f5adedbc57483530f86c1235ef60728). However, [it is still used as the background image of `.icon-confirm-white`](https://github.com/nextcloud/server/blob/49cbd8cd9507992c40e9acbb732721bcb72f1cba/core/css/guest.css#L654-L656), which in turn is used in several places (for example, in the login page, so no confirm icon is shown in the _Log in_ button).

![login-no-confim-icon](https://user-images.githubusercontent.com/26858233/43830198-0b10b22e-9b01-11e8-9e0f-711c48058910.png)

@nextcloud/designers

**Comment by weeman1337** [comment]
This may affect some other icons, too.  
I'll have a look at the style files..
