### ISSUE TITLE
When using the search function, pressing enter should open the first result

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1060]
Whether it’s a folder or a file, pressing enter when performing a search should open the first result so one can quickly navigate.

cc @prastut since you wanted to work on this :)

**Comment by leniquenoralez** [comment]
I can work on this.

**Comment by jancborchardt** [comment]
@leniquenoralez any progress here, or do you need help? :)

**Comment by skjnldsv** [comment]
Fixed nc20
