### ISSUE TITLE
Alignment issue and can no longer delete users in user management screen on 1280x720

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#10622]
At 1280x720, the user admin screen doesn't properly align the different users:
![screenshot_20180809_161353](https://user-images.githubusercontent.com/551757/43904545-3648372a-9bef-11e8-804d-e44b951e6458.png)

Worse, the three-dot menu doesn't show up at all on the right.

This happens only if you have created a group, until then it is fine!

**Comment by skjnldsv** [comment]
@juliushaertl since you worked on the user design.

@jospoortvliet about the hiding of the menu this is on purpose, you r screen is too narrow. This was also like this on the previous one.
