### ISSUE TITLE
Nextcloud 14 Beta 3 The "Referrer-Policy" HTTP header is not set to "no-referrer"

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#10624]
Hello getting this error in NC 14 Beta 3 

![image](https://user-images.githubusercontent.com/24574019/43908181-f3096808-9bbc-11e8-89e1-30858d9c376d.png)

**Comment by rullzer** [comment]
So it is not and error it is a warning as you can see.
It is warning you a header is not set which makes your browser forward any referrer information which is not recommended. So the system is actually doing what it should do. Warning you.

**Comment by andyxh** [comment]
Okay, this is an browser issue? I don’t get this warning on NC 13 ??

Sent from my iPhone X

On Aug 9, 2018, at 1:52 PM, Roeland Jago Douma <notifications@github.com<mailto:notifications@github.com>> wrote:


So it is not and error it is a warning as you can see.
It is warning you a header is not set which makes your browser forward any referrer information which is not recommended. So the system is actually doing what it should do. Warning you.

**Comment by rullzer** [comment]
Ah no. It is a new security header. We only added a check for it in NC14. That si why it shows up in the beta ;)

**Comment by andyxh** [comment]
@rullzer is this warrning always going to show?

**Comment by rullzer** [comment]
Yes. Unless you set the header. Same as for the other security header we recommend

**Comment by andyxh** [comment]
@rullzer Thank you! how do i set the header and where ?

**Comment by andyxh** [comment]
@rullzer any update on this?

**Comment by ShipNecro** [comment]
@andyxh This header needs to be added into your vhost conf.

Ex: <VirtualHost *:443>
    Header add Strict-Transport-Security: "max-age=15768000;includeSubdomains"
    Header always set Referrer-Policy "strict-origin"

**Comment by mathiasconradt** [comment]
> Yes. Unless you set the header. Same as for the other security header we recommend

It should be added to the NC docs as well, not? The location where and what do add, like with this other header that's documented. Currently there is a W3C link, but I think it's not very comprehensive for everyone.

**Comment by penCsharpener** [comment]
I agree with @mathiasconradt. Only figured out what to do with @ShipNecro comment.

**Comment by chriscroome** [comment]
Why not add these headers to the `.htaccess` file that Nextcloud generates (on Apache servers)?
