### ISSUE TITLE
"You can upload into this folder" translation into Brazilian Portuguese

### ISSUE THREAD

**Issue by marcosvfc** [nextcloud/server#10633]
https://github.com/nextcloud/server/blob/e98f4de66a888a70e11bf7964c1a7bb7688e4403/apps/files_sharing/l10n/pt_BR.js#L21

The translation into Brazilian Portuguese should be: "Você pode enviar arquivos para esta pasta"
It was completely the opposite of "you can" and "you cannot".
I'm seeing this message on public shares, with the right permissions to upload files and create folders.
![capturar](https://user-images.githubusercontent.com/36179021/43929027-9da4d918-9c09-11e8-9671-8e2a657c600a.PNG)

**Comment by marcosvfc** [comment]
Not a problem itself, everything works fine when uploading files and creating folders, but the translation to pt_BR is wrong, I think it was typed incorrectly in the translation.

**Comment by rullzer** [comment]
We manage our translations on transifex. Please join there to directly edit the strings.

https://www.transifex.com/nextcloud/nextcloud/dashboard/
