### ISSUE TITLE
Nextcloud 14 Beta 3 update failed

### ISSUE THREAD

**Issue by C439** [nextcloud/server#10631]
### Steps to reproduce
1. Change Nextcloud from stable to beta
2. Upgrade Nextcloud to 14 Beta 3
3. Finish upgrade

### Expected behaviour
Upgrade would finish without issues

### Actual behaviour
Upgrade failed

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** nginx 1.14.0

**Database:** 10.1.34-MariaDB-0ubuntu0.18.04.1

**PHP version:** 7.2.8

**Nextcloud version:** (see Nextcloud admin page) 13.0.5 (before update)

**Updated from an older Nextcloud/ownCloud or fresh install:** Should be 14 Beta 3

**Where did you install Nextcloud from:** The updater in the settings

**Error message:** 
\An unhandled exception has been thrown:
Error: Call to undefined method GuzzleHttp\Client::request() in /var/www/nextcloud/lib/private/Http/Client/Client.php:161
Stack trace:
#0 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
#1 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#2 /var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
#3 /var/www/nextcloud/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
#4 /var/www/nextcloud/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('activity')
#5 /var/www/nextcloud/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Array)
#6 /var/www/nextcloud/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.0.15', '13.0.5.2')
#7 /var/www/nextcloud/core/Command/Upgrade.php(262): OC\Updater->upgrade()
#8 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/nextcloud/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/nextcloud/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/nextcloud/lib/private/Console/Application.php(196): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/nextcloud/console.php(90): OC\Console\Application->run()
#14 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#15 {main}\

**Comment by lefty78** [comment]
The same here

**Comment by rullzer** [comment]
What is the lists of apps you have enabled?

**Comment by lefty78** [comment]
Its our playing ground so there a alot of apps installed ...

accessibility
activity
admin_audit
admin_notifications
announcementcenter
bruteforcesettings
calendar
caniupdate
checksum
cloud_federation_api
comments
contacts
dashboard
dav
encryption
external
federatedfilesharing
federation
files
files_accesscontrol
files_antivirus
files_automatedtagging
files_downloadactivity
files_external
files_external_gdrive
files_pdfviewer
files_retention
files_sharing
files_texteditor
files_trackdownloads
files_trashbin
files_versions
files_videoplayer
firstrunwizard
gallery
groupfolders
logreader
lookup_server_connector
metadata
mindmaps
nextcloud_announcements
notes
notifications
oauth2
ojsxc
password_policy
polls
previewgenerator
provisioning_api
ransomware_protection
serverinfo
sharebymail
socialsharing_diaspora
socialsharing_email
socialsharing_facebook
socialsharing_googleplus
socialsharing_twitter
spreed
support
survey_client
systemtags
theming
twofactor_backupcodes
twofactor_totp
updatenotification
user_external
user_ldap
workflowengine

**Comment by lefty78** [comment]
It comes after the lines:
Checking for update of app activity in appstore
An unhandled exception has been thrown:......

**Comment by rullzer** [comment]
Can you try to remove files_external gdrive. It might have a conflicting dependency

**Comment by rullzer** [comment]
@C439 did we promise t-shirts already?

**Comment by C439** [comment]
@rullzer yeah as mentioned here: https://nextcloud.com/blog/nextcloud-14-beta-3-is-here-time-for-testing-and-a-chance-to-win-a-t-shirt/

**Comment by rullzer** [comment]
In that case let me summon @jospoortvliet ^^

**Comment by jospoortvliet** [comment]
@C439 shoot me an email pls and we'll get you one ;-)

**Comment by C439** [comment]
@jospoortvliet Hi, can you please check your email? I've sent you my address over a week ago. :)

**Comment by XA21X** [comment]
@rullzer Disabling `files_external_gdrive` via `occ` worked for me. But I feel like incompatible apps shouldn't entirely break the upgrade process? :/ Thanks anyways.

**Comment by bibull** [comment]
> Can you try to remove files_external gdrive. It might have a conflicting dependency

Thank you it work for me too !

**Comment by nille02** [comment]
This Problem still exist. I did the Upgrade from 13.0.8.2 to 14.0.4.2 in the production branch. It fails horrible with the same issue. 
The Error Message is not helpful but thanks @rullzer and @XA21X for point at the faulty Addon.

**Comment by jirislav** [comment]
Disabling `files_external_gdrive` have also helped me.

If you're running Nextcloud in a docker like me, then this is the command you're looking for:
```bash
docker exec -u www-data nextcloud ./occ app:disable files_external_gdrive
```
