### ISSUE TITLE
Error in Nextcloud 14 Beta 3 Missing "Enable recovery key" field in the admin settings

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#10630]
Getting this error after updating to NC 14 Beat 3 from NC 13
![image](https://user-images.githubusercontent.com/24574019/43923189-a7b6ff9e-9be6-11e8-9eee-76b59752f7cd.png)

**Comment by rullzer** [comment]
@nextcloud/encryption

**Comment by schiessle** [comment]
@andyxh what was the Nextcloud version you enabled encryption for the first time? Can you execute this query on your database and post the result: `select * from oc_appconfig where appid="encryption";`

**Comment by andyxh** [comment]
@schiessle im sorry I dont remember  the version i think it was 10 or 11
 
mysql> select * from oc_appconfig where appid="encryption";
+------------+----------------------+----------------------+
| appid      | configkey            | configvalue          |
+------------+----------------------+----------------------+
| encryption | enabled              | yes                  |
| encryption | encryptHomeStorage   | 1                    |
| encryption | installed_version    | 2.1.0                |
| encryption | masterKeyId          | master_0c89db0b      |
| encryption | publicShareKeyId     | pubShare_0c89db0b    |
| encryption | recoveryAdminEnabled | 1                    |
| encryption | recoveryKeyId        | recoveryKey_0c89db0b |
| encryption | types                | filesystem           |
| encryption | useMasterKey         | 0                    |
+------------+----------------------+----------------------+
9 rows in set (0.00 sec)

**Comment by skjnldsv** [comment]
@schiessle does that ring a bell to you?
Iirc we decired to remove the password change if encryption was enabled.

https://github.com/nextcloud/server/blob/2afd37331e268e766d5e0c16d67f1d360e16efd3/settings/Controller/UsersController.php#L170-L174

**Comment by schiessle** [comment]
yes, we removed it for Nextcloud 14. The reason was that it was only possible with the recovery key enabled. Which worked fine, but only for relatively small accounts because all files had to be re-encrypted. As this could took really long on larger accounts and often ended in timeouts we decided to remove it in the user management. Users can still change their password in the personal settings.

**Comment by andyxh** [comment]
So what happens to the message I keep getting? And admins are not longer about to change passwords for users ??

Sent from my iPhone X

On Aug 15, 2018, at 8:37 AM, Björn Schießle <notifications@github.com<mailto:notifications@github.com>> wrote:


yes, we removed it for Nextcloud 14. The reason was that it was only possible with the recovery key enabled. Which worked fine, but only for relatively small accounts because all files had to be re-encrypted. As this could took really long on larger accounts and often ended in timeouts we decided to remove it in the user management. Users can still change their password in the personal settings.

**Comment by schiessle** [comment]
> So what happens to the message I keep getting? And admins are not longer about to change passwords for users ??

Yes, the user should change their password by their own. This way the private key can be updated without re-encrypting all files

**Comment by andyxh** [comment]
@schiessle  Okay, so what happens is the case that they dont remember it? Also, will this message keep coming up every time i go under users?

**Comment by schiessle** [comment]
@andyxh there will be a occ command to recover user files in the future: https://github.com/nextcloud/server/pull/10718

**Comment by andyxh** [comment]
@schiessle That's awesome news! Is there going to be a way to take that message out? is very anoyying getting that error every time someone has to click on users.

**Comment by stone212** [comment]
@schiessle I run a server that does not have encryption but I still get this error and the password fields for users is blank.  On NC13 (snap) I could change all users passwords.

**Comment by godfuture** [comment]
I had encryption enabled but never used to encrypt user homes. Short time after I disabled encryption, because I dont like it. Now I get this message, even I do not want to have encryption. What to do?
