### ISSUE TITLE
Add to favorites missing in "Recent" and main "Shares" view

### ISSUE THREAD

**Issue by ogasser** [nextcloud/server#10637]
The "Add to favorites" item in the three dots menu is missing in the "Recent" view.

### Steps to reproduce
1. Click on "Recent" in the left sidebar
2. Click on the three dot menu of any file

### Expected behaviour

The three dot menu in the "Recent" view should contain the "Add to favorites" item, as it does with the "All files" view.

### Actual behaviour

The three dot menu in the "Recent" does not contain the "Add to favorites" item.

**Comment by jancborchardt** [comment]
Yup, same in the main "Shares" view. The entry in the popover menu does not exist while all others do.

cc @icewind1991 @juliushaertl @schiessle, or cc the person who is relevant to this. ;)

**Comment by jancborchardt** [comment]
@nextcloud/javascript this is a quite core inconsistency with the views. Seems like a papercut with a possible easy fix?

**Comment by MorrisJobke** [comment]
Let's look into this for 15.0.1

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.1

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
