### ISSUE TITLE
Two factor authetication is enforced even if no provider is active

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10634]
### Steps to reproduce
1. Enable any Two Factor Provider
2. Generate backup codes
3. Disable all Two Factor Providers
4. Try to login again

### Expected behaviour
It should just login

### Actual behaviour

It asks for a second factor, but as no provider is there, only backup codes are available as an option

> Enhanced security is enabled for your account. Please authenticate using a second factor.

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
> Disable all Two Factor Providers

Are you talking about disabling the provider or the provider app. For the latter, this is the new desired behavior.

**Comment by ChristophWurst** [comment]
Nvm, can reproduce.

Thanks!
