### ISSUE TITLE
Enhancement: more sorting options in file app. 

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#10649]
There should be more options for sorting in the files app. Currently only name sorting is possible, at least in mobile view. In gallery app there is an option to sort by date.

Sort by options:
* name
* size
* type, either category (Video) or file extension (.mp4)
* modified time
* uploaded or added time (i.e. most recent upload)
 
Views:
* simple (file name, size) 
* detailed (file name, size, owner, mtime, ctime, etc.)
* custom columns, for example show how many files are in a folder. 
* option to disable file previews/thumbnails.
* option to load longer file lists, especially with thumbs turned off.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
We already have the core sorting functions, and they work across server and mobile.

These are pretty standard. Also, adding any further sorting option will multiply our testing matrix and we need to maintain all this. So we won’t add any further options for this at the moment.

**Comment by MacGyver27** [comment]
add at least per file extension.. would find that extremely useful as many users use this sorting naively in their devices

**Comment by soniok** [comment]
Hi, I'm also looking for sorting files by file type/extension.

How is this not already implemented?

**Comment by dimyself** [comment]
I agree... It seems odd to me some of the plugins/features I see in this app, yet columns/fields and sorting seems severely lacking??!

There should be at least an option or config to add/change columns and enhanced sorting? What if someone wants to have a name/author field for their movies/books/files?? This doesn't seem possible... Is there a way to do this or code this? Or another similar app like NC with added views/sorting/searching?

**Comment by MacGyver27** [comment]
@dimyself I didnt find any free and with responsive web ui.. however there are tons but trials or with limited use..

anyway this limitation is the only reason why we still use windows explorer to organize through files.. still dont understand what is so complicated about it since I have seen in around :/

**Comment by jancborchardt** [comment]
@MacGyver27 @soniok since you specifically look for only 1 thing, which is file type, could you open a new issue for that? Please include screenshots of how other widely used platforms like Google Drive, Dropbox etc do it.
Thanks! :)

-----------

@dimyself that is because every configuration option needs to be maintained and that takes a lot of resources. Regarding the name/author field, it seems you are rather looking for a specific e-book-reader app? Maybe there is an app on our app store which fulfils your needs, or you can write one: https://apps.nextcloud.com/

**Comment by Gatak** [comment]
> @MacGyver27 @soniok since you specifically look for only 1 thing, which is file type, could you open a new issue for that? 

Is this different than from the request I made in the first post? Should I clarify with some more examples or mock-ups?

`* type, either category (Video) or file extension (.mp4)`

**Comment by nooblag** [comment]
It would also be preferable to have Nextcloud "remember" the sorting view for each folder, at least in the web interface. For example, sorting "Documents" in descending order, but "Photos" ascending, sort by file type in "Programs" and so on. Should I add this as a feature request or leave it as a comment here?

**Comment by jacquesdupontd** [comment]
> It would also be preferable to have Nextcloud "remember" the sorting view for each folder, at least in the web interface. For example, sorting "Documents" in descending order, but "Photos" ascending, sort by file type in "Programs" and so on. Should I add this as a feature request or leave it as a comment here?

Exactly what i'm looking for ... I shared a "Photos" folder with my grand mother who's not a computer genius and she has to click on "Modified" to order then by last added each time she visits the folder ...

So if you could make feature request that would be nice, thanks

**Comment by davinbirdi** [comment]
Requesting Follow up to this Issue, as it's been 5 years since this response. 

> We already have the core sorting functions, and they work across server and mobile.
> 
> These are pretty standard. Also, adding any further sorting option will multiply our testing matrix and we need to maintain all this. So we won’t add any further options for this at the moment.

**Comment by joshtrichards** [comment]
@davinbirdi You're commenting on an Issue that was closed out over 5 years ago based on the then current roadmap/priorities. Maybe look for one of the open relevant ones to vote on. :) Possibly #18426?

Also there's a lot of working going on that is Files UI related with the vue migration.
