### ISSUE TITLE
Apps search should work across categories

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1064]
Currently in the apps management, the search only works in the current category. However one of the most common usecases is to:
1. Open the apps mgmt
2. Wanting to enable a new app
3. Trying to find it through search

– which will not succeed because only the already enabled apps will be searched.

cc @icewind1991 would be a great enhancement. :)

**Comment by MorrisJobke** [comment]
As we now have one big category of installed apps, this is basically done. Please reopen if this is still not yet enough @jancborchardt

**Comment by jancborchardt** [comment]
Yeah, also thought about this and the top usecase is definitely solved.

**Comment by MariusBluem** [comment]
No. We need a „All apps“-category (like on apps.nextcloud.com) which shows all apps (later with filters) ... there you should be able search under all available apps on the App Store.

**Comment by MorrisJobke** [comment]
> No. We need a „All apps“-category (like on apps.nextcloud.com) which shows all apps (later with filters) ... there you should be able search under all available apps on the App Store.

But this was closed in https://github.com/nextcloud/server/issues/126#issuecomment-297185997

Let' continue this in https://github.com/nextcloud/server/issues/3194 and keep this issue here closed.

**Comment by jancborchardt** [comment]
Hmm, I'd rather say that search in whatever category should below also show results in other categories, just like in Files (other folders).

Because an entry "All apps" will be misleading cause it's only all apps from the store.

**Comment by MorrisJobke** [comment]
oops reopened accidentally.
