### ISSUE TITLE
Link sharing broken with enforced password protection

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#10644]
Steps to reproduce
1. In Settings/Sharing, enable 'Enforce password protection'
2. Try to share a file or folder as a link
3. No popovermenu accessible

cc @nextcloud/sharing @nextcloud/javascript 

Likely caused by the new popover menu introduced in https://github.com/nextcloud/server/pull/10218

Found when checking for https://github.com/nextcloud/server/issues/10461

**Comment by skjnldsv** [comment]
@juliushaertl damn! don't we have acceptance tests for that though?

**Comment by rullzer** [comment]
Probably not then :S

**Comment by p5n** [comment]
It looks like share by link with password broken again
It is required to disable password by default and do not enforce it
After sharing password can be added
(nextcloud 30.0.3-1)
