### ISSUE TITLE
Double Entry for Password application when sharing by public URL

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#10647]
![password-entry](https://user-images.githubusercontent.com/1787238/43984038-d9000fec-9cb2-11e8-9917-e8dc38e4547d.png)

While sharing files and folders by URL in Nextcloud 13.0.5 one can optionally create a password for access.  The field is obfuscated, so it isn't clear what password is being written.  I'd like to request the password field require double entry to confirm it is created as intended.  I've always found entering a new password twice is a helpful practice.

**Comment by szaimen** [comment]
You can simply create a new password if the old one had a type error -> closing
