### ISSUE TITLE
[General Q] get logs with uploaded files from all users?

### ISSUE THREAD

**Issue by ETrko** [nextcloud/server#10640]
Hello,

is there a way to get any logs or access to all files that are uploaded by a user/all users?
we need that for security reasons to have any chance to check the files.

many thanks

**Comment by ETrko** [comment]
Any update here?

**Comment by skjnldsv** [comment]
There is currently no way to get a full list of uploaded files.
Though you could probably get that from the access logs.

As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
