### ISSUE TITLE
webmin install and nextcloud stop working: error 503 Internal Server Error - > find where broke. need help

### ISSUE THREAD

**Issue by bgcomrade** [nextcloud/server#10643]
Yestarday my brother install webmin and nextcloud broke with white screen and comment:

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.
This is everything i look in error log in apache2: HTTP/1.1" 500 929 inclue it update apache2u5 and http2 has lost.
Nextcloud was latest stable update 10.13.5

Strange is becouse we have two nextcloud and second nextcloud open, for example:

domain.com/nextcloud - > Internal Server Error
domain.com/nextcloudbrother - WORKS.

How is that possible. My brhother has his nextcloud working he install it maybe from 1 months and my don';t work, so this mean, php7.2 is working, mysql is working for brother nextloud.

And i use this integrated in apache2 443: /etc/apache2/site-enabled/domain.com.conf

               <FilesMatch "\.(cgi|shtml|phtml|php)$">
                                SSLOptions +StdEnvVars
                </FilesMatch>
                <Directory /usr/lib/cgi-bin>
                                SSLOptions +StdEnvVars
                </Directory>
                Alias /zashtita "/var/www/nextcloud/"
<Directory "/var/www/nextcloud/">
                Options +FollowSymlinks
                AllowOverride All
                <IfModule mod_dav.c>
                Dav off
                </IfModule>
                SetEnv HOME /var/www/nextcloud
                SetEnv HTTP_HOME /var/www/nextcloud
</Directory>

And my brother use alia to directory i try it too and again comment http internal error.It is unknown where to find to solve it. My brother less 1 months seek how to enable http2 in apache2-u5 becouse in u5 http2 is dissapeared and there is no decent manuals how to enable it. So please if you know how to solve nextcloud and return http2 please help

**Comment by bgcomrade** [comment]
What... after i copy from my brother config.php from /var/www/nextcloudbrother/config/config.php it open my nextcloud /var/www/nextcloud.

This is my brother config.php:

<?php
$CONFIG = array (
  'instanceid' => 'hi',
  'passwordsalt' => 'hi',
  'secret' => 'hi',
  'trusted_domains' => 
  array (
    0 => 'bgzashtita.es',
  ),
  'datadirectory' => '/var/www/nexcloudbrother/data',
  'overwrite.cli.url' => 'https://bgzashtita.es/rusva',
  'dbtype' => 'mysql',
  'version' => '13.0.2.1',
  'dbname' => 'nextcloudbrother',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloudbrother',
  'dbpassword' => 'andrews',
  'installed' => true,
  'theme' => '',
);


and this is my config.php:

<?php
$CONFIG = array (
  'instanceid' => 'hi',
  'passwordsalt' => 'hi',
  'secret' => 'hi',
  'trusted_domains' => 
  array (
    0 => '192.168.1.32',
    1 => 'domain.com',
  ),
  'filesystem_check_changes' => 1,
  'quota_include_external_storage' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'filelocking.ttl' => 3600,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://192.168.0.32/nextcloud',
  'dbtype' => 'mysql',
  'version' => '13.0.5.2',
  'enable_previews' => true,
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'nextcloud',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updater.release.channel' => 'stable',
  'mail_smtpmode' => 'php',
  'mail_smtpsecure' => 'ssl',
  'mail_from_address' => 'postmaster',
  'mail_domain' => 'domain.com',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '993',
  'mail_smtpauth' => 1,
  'loglevel' => 0,
  'maintenance' => false,
  'theme' => '',
  'data-fingerprint' => '5bd9c662fca8772f51235b0805ad6db7',
  'mysql.utf8mb4' => true,
  'logfile' => '/var/www/nextcloud/data/nextcloud.log',
  'log_rotate_size' => '10485760',

**Comment by danielkesselberg** [comment]
When you create a new issue there is a template with many questions. You might post some of these information to complete your issue. 

From the information you provide this looks more like a question for https://help.nextcloud.com.

**Comment by bgcomrade** [comment]
danielkesselberg and you will not help me. I find where it broke. Need help to solve it.

**Comment by danielkesselberg** [comment]
Sorry @bgcomrade english is not my first language. You provided only a few information about your setup. What is broken exactly?

**Comment by bgcomrade** [comment]
danielkesselberg peoples have to understand when you TRUE help language is not barrier. I;m not german speaker. in nextcloud.com you have to register and didn't have github so i make it and now it comment go to nextcloud.com where more than 2xxx issues are closed and 1120 issues are open. So  danielkesselberg  when some person comment issue tell him: From the information you provide this looks more like a question for https://help.nextcloud.com.

 danielkesselberg have nice day.

**Comment by danielkesselberg** [comment]
Excuse me if I upset you :disappointed:  I'm sure someone with more knowledge will help you soon.

**Comment by Bundesferkel** [comment]
Hi, bgcomrade! I could be totally wrong, but did you see your config.php somehow closer?

You start with:
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => '192.168.**1**.32',

followed by:
'overwrite.cli.url' => 'http://192.168.**0**.32/nextcloud',

Just a guess in the wild.
