### ISSUE TITLE
Allow export of every addressbook into one file

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#10652]
https://github.com/nextcloud/contacts/issues/431
related: https://github.com/nextcloud/server/issues/2864

Currently we can only export the contacts one addressbook at a time.
The suggestion is to allow the export of all of them at once.

**Comment by MorrisJobke** [comment]
Solved by #12004

If not then please reopen.

**Comment by skjnldsv** [comment]
Well it's not exactly that ^^
It allows to export a selection in an addressbook :)

**Comment by szaimen** [comment]
I suppose this issue is still valid?
