### ISSUE TITLE
Class/service 'Tagger' not found.

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#10669]
Steps to reproduce:
1. Share a folder via link
2. Log out or open a private window
3. Open the shared link
4. Change sorting of any column

```
Argument 3 passed to OCA\Files\Service\TagService::__construct() must be an instance of OCP\ITags, null given, called in /var/www/html/apps/files/lib/AppInfo/Application.php on line 94
```

**Comment by ChristophWurst** [comment]
Ref https://sentry.io/share/issue/972b1bf222da4abaa20f4dda0122e0ba/

**Comment by weeman1337** [comment]
I'm working on it.

**Comment by weeman1337** [comment]
The app tries to persist the sort order. But the API endpoint is only available for logged in users.
