### ISSUE TITLE
Update ImageMagick in CI environment to support HEIF/HEIC test cases

### ISSUE THREAD

**Issue by steiny2k** [nextcloud/server#10668]
### Steps to reproduce
1. Submit a pullrequest like https://github.com/nextcloud/server/pull/10526 which requires a recent version of ImageMagick convert tool
2. CI test case fails: https://drone.nextcloud.com/nextcloud/server/9604

### Expected behaviour
Test case should report green.
![grafik](https://user-images.githubusercontent.com/462714/43985377-4e17caaa-9d07-11e8-9a9a-8b5e1e0e4024.png)

### Actual behaviour
Due to older version of ImageMagick which lacks support to read HEIF/HEIC files (the new Apple file format for iPhones) in the CI environment, the test case fails (see log below).

### Server configuration
Running the tests on macOS with ImageMagick 7.0.8-9 installed through Homebrew works:
`brew install --with-libheif imagemagick`

**Operating system**:
macOS 10.13.6

**Web server:**
embedded php webserver

**Database:**
embedded sqlite

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
github master checkout

**Updated from an older Nextcloud/ownCloud or fresh install:**
new install

**Where did you install Nextcloud from:**
github

**Signing status:**
<details>
<summary>Signing status</summary>

```
n/a
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
n/a
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
n/a
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
n/a

**Operating system:**
n/a

#### Web server error log
<details>
<summary>Web server error log</summary>

```
n/a
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
1) Test\Preview\HEICTest::testGetThumbnail with data set #0 (-85, -61)
Failed asserting that false is not equal to false.

/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:141
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

2) Test\Preview\HEICTest::testGetThumbnail with data set #1 (34, 26)
Failed asserting that false is not equal to false.

/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:141
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

3) Test\Preview\HEICTest::testGetThumbnail with data set #2 (-76, 55)
Failed asserting that false is not equal to false.

/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:141
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103

4) Test\Preview\HEICTest::testGetThumbnail with data set #3 (75, -84)
Failed asserting that false is not equal to false.

/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:141
/drone/src/github.com/nextcloud/server/tests/lib/Preview/Provider.php:103
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
n/a
```
</details>

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
