### ISSUE TITLE
Optimize load times of images & icons

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1066]
It would be good to reduce the number of HTTP requests necessary to load the icons. Currently every icon is its own file. Now that we don’t have PNG anymore it’s high time to optimize the SVG delivery.

We could and should optimize that by putting the SVG icons into a sprite. We can use http://iconizr.com for that. (Which uses https://github.com/jkphl/svg-sprite )

cc @nextcloud/designers and especially @juliushaertl @Henni because you seemed interested in that. :)

**Comment by pixelipo** [comment]
I did some more research regarding this problem. I still think that the #5985 is the direction we should head towards. It seems that Github is actually using a very similar solution:
https://github.com/blog/2112-delivering-octicons-with-svg

Can anyone check if that's something that might work for us? From the text it is not clear at which point they are injecting SVG code into HTML...They were using icon fonts before, an approach that I was pondering as well, and didn't notice any performance change after making the switch.

Icon font is still an option for us, but there are some a11y problems related to it.

Is it possible to measure performance impact of #5985 to server?

@skjnldsv  @nickvergessen  @rullzer @MorrisJobke

**Comment by MorrisJobke** [comment]
> Can anyone check if that's something that might work for us? From the text it is not clear at which point they are injecting SVG code into HTML...

They do it in their ruby server. So it's basically the same as #5985

**Comment by MorrisJobke** [comment]
> Is it possible to measure performance impact of #5985 to server?

The only problem I see there is, that the browser can not cache that asset and thus it is loaded all the time. On the other side: the server should have this in memory all the time anyways and just serves it. Only problem is, that we also do a lot of JS injection of icons, which is not possible with that approach. and would require to load the asset via browser anyway. Nevertheless it's worth a try.

**Comment by benediktg** [comment]
> It would be good to reduce the number of HTTP requests necessary to load the icons.

With HTTP/2 this should not be that much of an issue anymore, I think. 😉

**Comment by ChristophWurst** [comment]
> With HTTP/2 this should not be that much of an issue anymore, I think. wink

That, plus the move to Vue and more advanced file loaders like the [url-loader](https://github.com/webpack-contrib/url-loader) that just inlines images smaller than a certain threshold make this less of an issue. I'll therefore close this ticket as there are now de facto standards that make the improvements possible without requiring us to implement these "hacks".

**Comment by jancborchardt** [comment]
No matter the outside technical developments, we still need to make sure to use all of the means we have to optimize performance. Not everyone checks out Nextcloud on a fast landline. :wink:

**Comment by ChristophWurst** [comment]
> fast landline

:snail: 💨

**Comment by MorrisJobke** [comment]
Blowing snail? 🤯

<img width="264" alt="bildschirmfoto 2018-10-03 um 00 17 01" src="https://user-images.githubusercontent.com/245432/46380194-bb58e680-c6a1-11e8-8970-0f8b1c64ce94.png">

**Comment by ChristophWurst** [comment]
well

![bildschirmfoto von 2018-10-03 00-18-10](https://user-images.githubusercontent.com/1374172/46380228-d4fa2e00-c6a1-11e8-9101-5f9c38d408ad.png)

**Comment by pixelipo** [comment]
Looks like some work was done while I was on a "sabbatical" that adds the colour version programatically (e.g. `svg/core/actions/more/fff?v=1`). From a quick glance, that doesn't seem to be very high-performance - it uses up way more data than it should. Compare with the direct fetching of SVG in this table (transferred vs actual size):
![image](https://user-images.githubusercontent.com/4129927/46402893-4ae1b200-c701-11e8-96af-38765d4aa4cf.png)

**Comment by skjnldsv** [comment]
@pixelipo, we add some strings to the svg on the colour api, so it's logical that it's bigger.
Though the caching is working fine, so first load is long, second is instant :)

**Comment by pixelipo** [comment]
it's 10 times the size, which is a bit concerning...

**Comment by skjnldsv** [comment]
> it's 10 times the size, which is a bit concerning...

Hum, it's more like 100Bytes more, or am I misreading your screenshot?

**Comment by pixelipo** [comment]
you're misreading it - in the first line, actual image size is 176bytes, but a total of 1.07 kilobytes were used up to fetch it.
In case of a direct SVG fetch (line 5), that difference is practically negligible.

**Comment by skjnldsv** [comment]
Ah yes! How is that possible then? The data comes from the headers or something?
Packet size?

**Comment by rullzer** [comment]
I don't buy that we add 900kb of headers.

@pixelipo any way to obtain more info on the request?

**Comment by skjnldsv** [comment]
> I don't buy that we add 900kb of headers.

But it's 900 bytes, not KB?
1.07kb => 1070bytes, right?

**Comment by rullzer** [comment]
Right. I should not answer so fast.
That might be. But all of it should be pretty aggressively cached as well

**Comment by juliushaertl** [comment]
I looked at some requests and the ~1kb of header data seems pretty reasonable, but there is not much we could do about this, besides merging icons to a sprite. 

@pixelipo I also don't see any huge difference between the svg api endpoint and the direclty fetched svgs. Probably something related to the webserver setup?

**Comment by pixelipo** [comment]
There's a definitely a visible performance difference - the two icons in the screenshot bellow are very similar in size and the api version takes more than 10 times as long to load:

![image](https://user-images.githubusercontent.com/4129927/46458895-90f94d00-c7b7-11e8-989d-3c11a26bdb56.png)

Here are few more examples of various filesizes:
![image](https://user-images.githubusercontent.com/4129927/46458977-d158cb00-c7b7-11e8-8028-ea72af0b1815.png)

**Comment by skjnldsv** [comment]
@pixelipo I noticed the php script is slowing things down yes!
I could use someone to check how to optimise things :)
I'm guessing since we also get the svg and read the filesystem there is multiple factors here:
- hdd read
- php latency
- php script running
- webserver displaying

That's why we have hard caching :)

**Comment by rullzer** [comment]
Well yes there is overhead of course. But it should be 1 time.

I assume there is some theming going on and that is why we don't ship it as static asset right?

**Comment by juliushaertl** [comment]
Fixed with #12016 (but using inline images in css instead of a sprite)
