### ISSUE TITLE
Incorrect HTML encoding in Move/Copy dialog

### ISSUE THREAD

**Issue by anoadragon453** [nextcloud/server#10662]
### Steps to reproduce
1. Create a folder with some character that needs HTML encoding, such as `'`
2. Attempt to move a file to it
3. Notice that the dialog shows HTML encoded text instead of decoding it

![image](https://user-images.githubusercontent.com/1342360/44005405-dc2efbda-9e27-11e8-82c5-9443d89d9811.png)

### Expected behaviour
The text should read `Grandma's 80th`.

### Actual behaviour
Instead it reads `Grandma&#039;s 80th`.

### Server configuration

**Nextcloud version:** 13.05

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

**Comment by lars-sh** [comment]
Still the same with Nextcloud version 19.0.2. In my case the folders name is "Janina & Lars", while the Move/Copy dialog shows "Kopieren nach Janina &amp; Lars" and "Verschieben nach Janina &amp; Lars" (that's German for "Copy to Janina &amp; Lars" and "Move to Janina &amp; Lars").

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by skjnldsv** [comment]
Fixed on 27.1 and above
