### ISSUE TITLE
Add tags to multiple files at once (bulk edit option)

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/server#10674]
I want to select multiple files and add tags to those files.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by laurentiu2** [comment]
Would be a great feature! What about this approach?

![screenshot 2019-02-26 at 20 00 31](https://user-images.githubusercontent.com/29857699/53435625-e7cf1f80-3a01-11e9-9da3-403e3e28c054.png)

**Comment by jancborchardt** [comment]
@laurentiu2 sure, looks good! :)

- It should say "Tags"
- Be sorted between "Download" and "Delete"
- Use "icon-tag" for the icon instead of the same as Move/copy

**Comment by jancborchardt** [comment]
@laurentiu2 sure, looks good! :)

- It should say "Tags"
- Be sorted between "Download" and "Delete"
- Use "icon-tag" for the icon instead of the same as Move/copy

**Comment by Kurlee** [comment]
Is anyone working on this feature? I am working on a project that would greatly benefit from this feature. I have a dev or two here that can help out if someone wants to point us in the right direction

**Comment by wiswedel** [comment]
@Kurlee Thanks for your initiative. We'll be happy to assist you with the direction.
Do you already have concrete questions?

**Comment by wiswedel** [comment]
> Would be a great feature! What about this approach?
> 
> ![screenshot 2019-02-26 at 20 00 31](https://user-images.githubusercontent.com/29857699/53435625-e7cf1f80-3a01-11e9-9da3-403e3e28c054.png)

@skjnldsv

**Comment by Kurlee** [comment]
> @Kurlee Thanks for your initiative. We'll be happy to assist you with the direction.
> Do you already have concrete questions?

Is there an offline channel I can discuss with you? I am on the dev IRC

**Comment by wiswedel** [comment]
> Is there an offline channel I can discuss with you?

@Kurlee Since we're Open Source, why not discuss here in public?

**Comment by Kurlee** [comment]
> @Kurlee Since we're Open Source, why not discuss here in public?
Sounds good! So we have a good grasp of the API and how to implement bulk tagging using a curl script and webdav, but obviously, this is a bandaid. 
It looks like the client triggers the call to add the tag in the db with the js scripts in the systemtags file. 
We are unsure about how to copy the bulk move/copy function in bulk because we are having an issue figuring out how the multi-select feature and these calls work together, and the function flow path.

We might be over our heads in this but we are dedicated to figuring it out and making a contribution to this project

**Comment by wiswedel** [comment]
@jancborchardt Do you think you can assist here a bit?

**Comment by jancborchardt** [comment]
Sorry but this is out of my expertise – someone from @nextcloud/javascript would have to help @Kurlee here. :)

**Comment by Kurlee** [comment]
So more specifically (after poking around a bit), we just are having a hard time sorting out how the selected files are passed to client.js. Selecting function and menu all seem to be handled by jquery. Stepping through the functions is very difficult with jquery so I am stalled a bit. I think I would only need a few mins of time from someone who knows what they are doing to get over this hump and move forward.

**Comment by jancborchardt** [comment]
Who is the right person to help @Kurlee here @rullzer @MorrisJobke? :)

**Comment by Kurlee** [comment]
Made some progress on this today and answered some of the questions I had yesterday. 
The menu is generated by app/files/js/filelist.js
However I assume that app/files is primarily for handling all file actions, would I be doing this improperly if I simply worked within the app/files directory to add this functionality?

**Comment by grasponcrypto** [comment]
any progress made here?  This would be a huge help to catalogue my pictures.

**Comment by HFranz** [comment]
waiting for this feature too

**Comment by derKroisi** [comment]
any news for this feature? would love to see it, or get some informations on the plans

**Comment by rizerzero** [comment]
Would love to see this feature too !

**Comment by rolandinus** [comment]
I would be happy to spend some developing time on it. May be we could join efforts here.
I am not sure if it is possible to hook into the menu and add an extra menu option via an custom app? Then we could add this functionality without changing the core.

**Comment by rullzer** [comment]
As always. If somebody wants to pick this up and propose a PR this is most welcome.

**Comment by rolandinus** [comment]
Is there someone who could help me with the failed automatic tests?
The failed tests do not seem to be related to code changes I made
I am new to contributiong to nextcloud, so would be thankful if someone could guide me here a bit

**Comment by wiswedel** [comment]
> Is there someone who could help me with the failed automatic tests?
> The failed tests do not seem to be related to code changes I made
> I am new to contributiong to nextcloud, so would be thankful if someone could guide me here a bit

CC @nextcloud/server-triage

**Comment by caseyhoward** [comment]
This would be very helpful especially since even tagging one file is extremely painful. Unless I'm missing something it requires 5 clicks:

1. Context menu button for file
2. "Details" in the menu
3. Menu button for details section
4. "Tags" in the menu
5. The tag input field since it doesn't auto-focus.

**Comment by digititus** [comment]
Would love to see this implemented! Tagging a new system now and it is extremely slow with large data set of files

**Comment by bjoern-tantau** [comment]
For what it's worth, I've been working on a plugin to assign tags to multiple files at once. It hooks into some JS functions in a pretty hacky way and there are some visual glitches and it does not work well on mobile. But I don't have enough time to polish it so I wanted to at least publish the code in the hopes that it's useful for someone or maybe someone could even polish it: https://github.com/bjoern-tantau/massassigntags

Code is licensed under the AGPL. I should actually add a license file to it, but it's reflected in the composer.json.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/28133

**Comment by olaulau** [comment]
as of today, this feature isn't yet on my nextcloud files  (v 29.0.6.1)

**Comment by rolandinus** [comment]
It seems "done" means in this case, it is merged with another issue, which ist still open:
 #45935
