### ISSUE TITLE
Fix remember me behaviour

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#1067]
As discussed with @ChristophWurst the remember me behaviour needs some adjustments and fixes…

**Comment by MorrisJobke** [comment]
@LukasReschke @ChristophWurst I guess this needs to be moved to 10.0.2, right?

**Comment by MorrisJobke** [comment]
> @LukasReschke @ChristophWurst I guess this needs to be moved to 10.0.2, right?

PR #1347 is still WIP -> moving to 10.0.2

**Comment by ChristophWurst** [comment]
@MorrisJobke okidoke, makes sense

**Comment by coderkun** [comment]
Has this already been back-ported to 10.0.2?

**Comment by LukasReschke** [comment]
No and it won't. This will be 11.0 only.

**Comment by urbenlegend** [comment]
That's unfortunate. This is a really annoying regression with the 10 releases.
