### ISSUE TITLE
Installation freezes during "Installing issuetemplate"

### ISSUE THREAD

**Issue by BonziBuddyMonkey** [nextcloud/server#10676]
DISCLAIMER!
---- I used the guide and script:  
https://github.com/nextcloud/vm

 Steps to reproduce

 

1. wget https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh
2. sudo bash nextcloud_install_production.sh
3. Follow the steps on screen. (Not using root)
4. Created new user
5. Disk check
6. Nextcloud is installed
7. installing issuetemplate: 

```
# Install issuetemplate 
-  install_and_enable_app issuetemplate


> install_and_enable_app() {
> # Download and install $1
> if [ ! -d "$NC_APPS_PATH/$1" ]
> then
>     echo "Installing $1..."
>     occ_command app:install "$1"
> fi
> 
> # Enable $1
> if [ -d "$NC_APPS_PATH/$1" ]
> then
>     occ_command app:enable "$1"
>     chown -R www-data:www-data "$NC_APPS_PATH"
> fi
> }
> 

```

8. Ubuntu freezes and I have to forcefully shut it down in esxi.

### Expected behaviour
It should continue, but it dosnt. I have succesfully installed it on hyper v on an other PC.

### Actual behaviour
It freezes and has to be forcefully shutdown.

Server configuration
HP ProLiant DL180 G6
CPU	12 CPUs x Intel(R) Xeon(R) CPU E5645 @ 2.40GHz
Memory	63.99 GB
8TB running in raid 10.

Server version: (see your admin page)
Image profile	ESXi-6.5.0-20170404001-standard (VMware, Inc.)

How did you install the VM? (Scripted install from master OR Released version)
Installed through ESXI using Ubuntu-18.04.1-live-server-amd64.iso

Where it fails in the script.

```
install_and_enable_app() {
# Download and install $1
if [ ! -d "$NC_APPS_PATH/$1" ]
then
    echo "Installing $1..."
    occ_command app:install "$1"
fi

# Enable $1
if [ -d "$NC_APPS_PATH/$1" ]
then
    occ_command app:enable "$1"
    chown -R www-data:www-data "$NC_APPS_PATH"
fi
}
```
Network
Static Ip

Is port 80 and/or 443 open?
both

Screenshoots
![image](https://user-images.githubusercontent.com/42281490/44044406-bf278a26-9f25-11e8-8ce4-8865d447261b.png)

**Comment by enoch85** [comment]
I think it's a timeout to the app store. Happened to me as well, then it suddenly started to work again after some time. 

If not a timeout, then there's a bug in the `occ app:install` command

**Comment by szaimen** [comment]
I suppose at this was a temporary Appstore problem. Please reopen if you can still reprodce this.
