### ISSUE TITLE
Show files details sidebar always 

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/server#10673]
I want to see the File Details Pane as I browse other files.

Current Behavior:
When I change files, the File Details Pane closes.

Requested Behavior:
Continue to display the File Details Pane when selecting a different file.
Do not close File Details Pane.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers 

@jancborchardt Didn't you had this also as an idea for wide screens by default?

**Comment by juliushaertl** [comment]
@MorrisJobke Yes, there is https://github.com/nextcloud/server/issues/7138 about that. I'd say this is a duplicate.
