### ISSUE TITLE
Show file tags in files app

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/server#10675]
I would like to see what tags are assigned to a file when viewing in Details View

![image](https://user-images.githubusercontent.com/8312560/44042631-97b7b38a-9ed5-11e8-85f1-edcfae13393e.png)

There's lots of white space that can be used to see tags.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Wasn't this removed a few years back? @jancborchardt

**Comment by juliushaertl** [comment]
Seems to be a duplicate of https://github.com/nextcloud/server/issues/6424

**Comment by MorrisJobke** [comment]
> Seems to be a duplicate of #6424

Correct 👍
