### ISSUE TITLE
Nextcloud logo not visible when theming color is white

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#10684]
See:
![screenshot from 2018-08-14 13-20-53](https://user-images.githubusercontent.com/925062/44088870-f9032f30-9fc4-11e8-8f86-6b05f281dd61.png)

I would even say to invert the color of the Nextcloud logo as soon as the other header icons are inverted to keep everything looking nice and consistent. What do you think @nextcloud/designers @nextcloud/theming?

**Comment by jancborchardt** [comment]
Same on the redirect page actually, with logo not being visible and header (but not main text) being white:
![screenshot from 2018-08-14 13-28-23](https://user-images.githubusercontent.com/925062/44089146-022a8c42-9fc6-11e8-86a4-bee681906eb3.png)

**Comment by juliushaertl** [comment]
We had some discussion about that in the past, and the conclusion was that we don't want to invert the logo, because the Nextcloud logo should either be blue or white. I don't have a strong opinion on this, but if you use theming you'll probably also replace the logo, so I don't think it is really an issue.

**Comment by skjnldsv** [comment]
@juliushaertl can we use the svg api for the logo?

**Comment by skjnldsv** [comment]
We could move the logo to img though ^^

**Comment by MorrisJobke** [comment]
> Member
> juliushaertl commented 6 days ago
> We had some discussion about that in the past, and the conclusion was that we don't want to invert the logo, because the Nextcloud logo should either be blue or white. I don't have a strong opinion on this, but if you use theming you'll probably also replace the logo, so I don't think it is really an issue.



> We had some discussion about that in the past, and the conclusion was that we don't want to invert the logo, because the Nextcloud logo should either be blue or white. I don't have a strong opinion on this, but if you use theming you'll probably also replace the logo, so I don't think it is really an issue.

I also don't like this special case. If you want a white nextcloud, then also upload an updated logo. Altering the logo only if it is the Nextcloud logo adds quite some logic for not too many use cases IMO. We should focus on real problems and not such artificial ones.

**Comment by MariusBluem** [comment]
I agree with @MorrisJobke 👍

What we could do is forcing a different logo, name etc. or a explicit confirmation from admin since changing name, background etc. could violate the trademark guidelines of Nextcloud.

**Comment by MariusBluem** [comment]
Besides that: white Nextcloud with blue-logo would look awesome 😍

**Comment by MorrisJobke** [comment]
> Besides that: white Nextcloud with blue-logo would look awesome 😍

But then I already see the issue with "I don't want it blue but $COLOR" -.-'

**Comment by weeman1337** [comment]
I think this is more for the _out of the box experience_. If you change the color to a light one, the app icons change. Why not change the _default logo_ also?

If an user uploads a _custom logo_ it's up to him to align it with the color.

**Comment by juliushaertl** [comment]
> I think this is more for the out of the box experience. If you change the color to a light one, the app icons change. Why not change the default logo also?

Yes, I think for having a nice experience it would make sense to just have a blue logo for white colors. :+1: 

> But then I already see the issue with "I don't want it blue but $COLOR" -.-'

As @weeman1337 said, they can still upload one.
