### ISSUE TITLE
Quota: total is wrong calculated, thus relative is also not correct

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#10693]
I have 56G out of 221Gb used and quota shows me:
156G free
5G used
158G total
3.3% relative

When I fill up my device with 150G (using fallocate), I have 206 out of 221G used:
3,5G free
5G used
8 total
59.6% relative

Somehow total is not calculated correctly and thus "relative" is also wrong.
Disk usage was done via (df -h).

**Comment by ashgoodman** [comment]
Quota is wrong. I have a quota of 50GB and am using about 5

It says I have used 600MB of 13GB quote

![quota](https://user-images.githubusercontent.com/21287394/44519380-6bc8e780-a6ff-11e8-8d27-ad0d478145d7.png)

**Comment by JDemmerle** [comment]
@tobiasKaminsky 
Does the bug still exist?
I got the same issue on NC 14/15.

**Comment by tobiasKaminsky** [comment]
I think so:
with curl, I do get: (/ocs/v1.php/cloud/user)
```
"quota": {
        "free": 85381120000,
        "used": 6047777362,
        "total": 91428897362,
        "relative": 6.61,
        "quota": -3
      },
```

on df -h:
```
Total: 190G
Used: 100G
Free: 80G
used%: 56%
```

Now I allocate 60G:
```
"quota": {
        "free": 20956602368,
        "used": 6047777362,
        "total": 27004379730,
        "relative": 22.4,
        "quota": -3
      },
```

on df -h:
```
Total: 190G
Used: 160G
Free: 20G
used%: 90%
```

**Comment by JDemmerle** [comment]
Can you have a look at a specific user file(and really only the "file") dir and compare that with the value on the NC webinterface?

**Comment by tobiasKaminsky** [comment]
My data is located at /srv/http/nc/data/tobi and this is 6G, which maps the "used" of quota.

"free": 85.381.120.000,
"used": 6.047.777.362,
"total": 91.428.897.362,

free seems also to match, but total should be 190G and not 90G, or?

**Comment by JDemmerle** [comment]
Whats the size of /srv/http/nc/data/tobi/**files**?
Files is the dir, which maps used of quota at the NC webinterface.


Yeah total should be 190G in my opinion..

**Comment by tobiasKaminsky** [comment]
> Whats the size of /srv/http/nc/data/tobi/**files**?

6G

**Comment by JDemmerle** [comment]
Is there a public share where everybody can upload stuff?
Maybe there are broken files.

**Comment by tobiasKaminsky** [comment]
Not that I know…There was once a external mount, but this is not there anylonger.

**Comment by tobiasKaminsky** [comment]
Go away…stale bot… ;-)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by devz3r0** [comment]
I am using Nextcloud 24.0.8 the User is only occupying 114MB after deletion, emptying the trash, however the quota is still displaying 5,1 GB in use.

**Comment by cestmoimeme** [comment]
My nextcloud is 25.0.2 and calculation is ok now for me

**Comment by szaimen** [comment]
Thanks for verifying!

**Comment by tflidd** [comment]
There are still 2 users on the forum with this issue:
https://help.nextcloud.com/t/wrong-quota-calculation/152702

**Comment by szaimen** [comment]
Hi, please open a new issue about this with up-to-date information. Thanks a lot!

**Comment by devz3r0** [comment]
Done here: https://github.com/nextcloud/server/issues/36403
