### ISSUE TITLE
Link to markdown file starts download instead of opening editor

### ISSUE THREAD

**Issue by dreamflasher** [nextcloud/server#10699]
### Steps to reproduce
1. Right click on a (shared) file
2. Copy target link
3. Open this link (eg. https://nextcloud.domain/remote.php/webdav/filename.md)

### Expected behaviour
The file should open in the corresponding editor

### Actual behaviour
Download of the file starts

### Additional information
I am looking for a link that I can send around to people who have rights to edit a file, and that opens the editor for them. The "share link" also does not open an editor, but only a viewer, plus I don't want to share it publicly, but only to people who are logged in.

**Comment by DreamFlasher** [comment]
This is the same issue described as here: https://github.com/nextcloud/server/issues/1177 but for markdown files.

**Comment by frankgerhardt** [comment]
E.g. I have two files `first.md` and `second.md` and the first file contains a markdown link like `[link to second file](second.md) then I would like to have the second file opened in the markdown editor. 
This might be simply working once this is fixed, or it might deserve it's own issue.

**Comment by skjnldsv** [comment]
Hey!
This is on purpose. We don't have a way to directly open the default file action (there is an opened issue about this)
We want to keep the link as the direct download file by default.
If you want to get the file link, you can use the internal link in the sidebar :)
