### ISSUE TITLE
Make document tags fall under the same permissions as the document content

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/server#10694]
When you share a document with another user in read-only mode, the recipient user can still edit the tags for this document. 
I understand the idea behind it that the tags might be used for collaboration and it might make sense there, but nevertheless it's quite uncommon (compared to DMS).
I see tags as meta data of a document, similar to the filename, which should only be editable by somebody who also has permissions to edit the actual document content.

Otherwise the tagging system cannot be used for a variety of use-cases. The same goes for workflows. If any user can change tags, they can only be used for workflows in certain cases. And involving an admin to setup invisible tags is not suitable in most cases.

Since the pros and cons can be argued either way, it's best to have an option (i.e. in the share dialog) to allow for tag editing or not.

**Comment by maghog** [comment]
Agree!
Imagine in a school environment when a student can change the name of everyone's tags. It's useless...

**Comment by maghog** [comment]
I see that ownCloud seems to have a group setting to limit rights...
![tag management](https://user-images.githubusercontent.com/1148924/49146359-481acc00-f302-11e8-8985-a3606c256ead.png)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
