### ISSUE TITLE
 Problems with HTML coding of "&" when logging in for the first time

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#10708]
### Steps to reproduce
1. Create a own theme
2. In "public function getSlogan () { return ''; add a "&" or  `&amp;`
3. Login with a new user into Nextcloud

### Expected behaviour
See here -> https://nc3.jaba.hosting/s/yYL8xxf8wxZkkgM

### Actual behaviour
The Slogan must to be with the correct coding of "&" and not `"&amp;amp"`

I have try in the theme with "&" and` "&amp;"`, but no luck.

### Server configuration

**Operating system**:

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** PHP 7.0

**Nextcloud version:** 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** from nextcloud.com

**Comment by skjnldsv** [comment]
Fixed already in the firstrunwizard
