### ISSUE TITLE
Could not order files by modified date in recent view

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#10704]
### Steps to reproduce
1. Open Files
2. Change to Recent
3. Click on modified to change sort order

### Expected behaviour
Files should be ordered by date

### Actual behaviour
Nothing

### Server configuration
**Nextcloud version:** 13.0.5 / 14.0.0 Beta 4

Sorting in recent view disabled with this commit https://github.com/nextcloud/server/commit/2139a031e706e256eee1e4f8cfc6cea06cf8cb9f

**Comment by skjnldsv** [comment]
This is on design, this is unfortunately not available in other views

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
