### ISSUE TITLE
More apps menu not position in the right place

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#10716]
![moreappsposition](https://user-images.githubusercontent.com/45821/44205677-7b708b00-a157-11e8-97a8-243b70cd3eb6.png)

@juliushaertl @skjnldsv

**Comment by weeman1337** [comment]
I'll have a look..

**Comment by raimund-schluessler** [comment]
I still see this issue on screensizes <480px due to https://github.com/nextcloud/server/blob/master/core/css/mobile.scss#L135-L142.

![bildschirmfoto am 2018-08-27 um 15 24 00](https://user-images.githubusercontent.com/2496460/44662333-ce76f780-aa0d-11e8-8989-7e21736c603a.png)

**Comment by skjnldsv** [comment]
#10851
