### ISSUE TITLE
Upload Problem on Web Browsers

### ISSUE THREAD

**Issue by gcivelek** [nextcloud/server#10711]
Hello,

I am using nextcloud on cpanel based hosting.

I installed via web installation.
I can't uploud ".zip, .pdf" files and picture files from web browsers. If I changed file extentios. there is no problem.
Also I can upload all files via desktop software and mobile application.

There aren't any error messages. Just loading bar is freezing.

Thank you. Best regards.

**Comment by kesselb** [comment]
Does this error still occur? If so please edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md). It's much easier to reproduce a problem with the issue template.
