### ISSUE TITLE
Can't create new user trough API without password

### ISSUE THREAD

**Issue by gpredl** [nextcloud/server#10717]
Within NC control panel it's possible to configure 'Send email to new users'. If done so, one can leave password blank when creating new user. Email for activation and password setup will be send to new user.

We'd like to create new users trough the API, without providing password, but email instead. 
This is not possible trough the API.

### Steps to reproduce
1. POST to /ocs/v1.php/cloud/users with parameters 'userid' and 'email'

### Expected behaviour
In control panel we've set up: Send email to new users.
As mentioned in the docs it should be possible to dismiss 'password' and use 'email' instead.
Email should be send to news users to activate account and set password.

### Actual behaviour
API responds with 101: Bad request

### Server configuration
Nextcloud version 13

**Comment by leomelzer** [comment]
@gpredl This is now possible (v14) and landed in https://github.com/nextcloud/server/commit/41b690ed53be36498607c13c2b8b3d84e240c84b

We discovered an issue with our custom password policy (32 characters) as the length and layout of the auto-generated password is currently hardcoded in the provisioning API.

Instead it should reuse the policy like in the sharing app: https://github.com/nextcloud/server/blob/9b9d729acf8a6c46374d1ef55915c6fca988b191/apps/sharebymail/lib/ShareByMailProvider.php#L216

Seems like this would require some more work (making this more general and then pulling it in for different apps).

**Comment by gpredl** [comment]
Some idea about a workaround?
Or is there any way to send the 'Password lost token' to a user by calling the api or something else?

**Comment by szaimen** [comment]
We don't support creating users without password.

**Comment by DylannCordel** [comment]
> We don't support creating users without password.

Too bad. When authentication is provided by SSO, **but** user created by API, we must create user with random password which is worst than creating an user with a blank password which not allow normal auth with it.
