### ISSUE TITLE
Improve 2FA selection screen

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#10728]
Our current 2FA selection screen (if you have multiple providers). Looks like:

![2fa](https://user-images.githubusercontent.com/45821/44255229-9994c480-a205-11e8-96ff-88931a7cca43.png)

Which is not to pretty IMO.

Something like (excuse my awesome artistic skills):

![4096-3072-max](https://user-images.githubusercontent.com/45821/44255248-add8c180-a205-11e8-9336-fe84ba228179.jpg)

Would be nicer I think.
Tiles with a description would also be 'easy' (for somebody with CSS knowledge) to make responsive for the mobile UI.

@nextcloud/designers 
@ChristophWurst as it is 2FA stuff ;)

**Comment by skjnldsv** [comment]
I'm not find of the "blah blah" text, can we change? :thinking: 

Nice improvements btw ;)

**Comment by jancborchardt** [comment]
As discussed with @rullzer & @ChristophWurst – Christoph will create a branch with all that’s needed for the screen and I’ll do the layout. :)
