### ISSUE TITLE
Problem with DFS share mounting remains

### ISSUE THREAD

**Issue by Tigger2121** [nextcloud/server#10720]
### Steps to reproduce
1. Setup 2 windows servers, join them to windows AD domain, create a test folder on each one of them, create a DFS-R replication between that folders.
2. Share one of that folders (any, 
3. Try to mount it on Nextcloud as an external storage.

### Expected behaviour
It should be mounted like it supposed to be,

### Actual behaviour
Behavior depends on provided credentials. If domain account belongs to Domain Admins group, share will be mounted. If domain account doesn't belong to Domain Admins, share will not be mounted with "you've got an empty response from server" error.

### Server configuration

**Operating system**:
Ubuntu 16.04, Windows Server 2016, Windows Server 2012

**Web server:**
apache2

**Database:**
PostgreSQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
14

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 13.5

**Where did you install Nextcloud from:**
Appliance from official site

**Comment by arnydo** [comment]
+1 for this issue.

**Comment by stfast** [comment]
+2 for this issue.

**Comment by moose999** [comment]
+3 for this issue. I have tried http://mattslay.com/connecting-ubuntu-to-windows-shares-and-dfs-trees/ without any change.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
