### ISSUE TITLE
js+css => user-trash~

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#10733]
suggestion for the Trash-icon
it gives in linux , as example 2 different icons for the Trash:
user-trash.png/svg/svgz
and 
user-trash-full.png/svg/svgz

there it is the possible for js to difference, if files in the trash-folder or not,
so full or not full,
why not use the different possibility's 
to let show not full/full 
and on the user-icon/svg 
if hover with the mouse on full-trash, 
:hover => delete-trash.svg (an red icon, like it is already used)
the full icon can have a gray content, 
this be able to show in black background and in white background,
so may be able by trash to work with 3 Icons:
user-trash.svg
user-trash-full.svg
user-trash-empty.svg

this makes able to see if there something in the Trash or not
and with the :hover let show a red icon for empty the trash

best regards
blacky

**Comment by skjnldsv** [comment]
Please be more simpler for your requests and topics @blackcrack 
I'm having a really hard time to understand you.

Are you asking for the ability to see if the trashbin is empty by using a, empty trashbin icon?
If so, you could just have set you title to something like "Empty trashbin icon" :)

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If you wish to  add more details to it, please feel free to reopen.

**Comment by blackcrack** [comment]
Hi @skjnldsv 

yes, an trash.svz and a trash_emty.svz for this, like in kde/plasma

i had no time anymore, btw, i work as security with 12h worktime.. 
so a bit less time for check all mails how in the last jears where i was workless..
best regards
Blacky
