### ISSUE TITLE
Missing "deleted files" in WebGUI of NC 13.0.5

### ISSUE THREAD

**Issue by Krautmaster** [nextcloud/server#10736]
Dear all. 

Im running NC for a year now, coming from V12 and updated version by version on Ubuntu 16.04 + PHP 7.0 + Apache 2 + NC13.0.5.
Any how, my "deleted files" thing is missing and im unable to see and restore deleted files. No idea if I did something wrong but I never customized much.

My complete config is visible here
https://pastebin.com/8LgNGgjx

![image](https://user-images.githubusercontent.com/1076514/44275376-ddf38500-a244-11e8-9ae9-98f132bf7c81.png)

How can i debug into this or is there a setting to disable deleted file management in NC??

Thanksand best regards

Kraut

**Comment by danielkesselberg** [comment]
According to your configuration files_trashbin is disabled. Could you try to enable it?

**Comment by Krautmaster** [comment]
will do, gimme a second.
