### ISSUE TITLE
Shares icon in high contrast theme

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#10742]
I activated the high contrast theme and now the shares icon looks like this:

![image](https://user-images.githubusercontent.com/1869584/44299269-1e114100-a2f3-11e8-8d75-8ff017670026.png)

I´m running the nextcloud:beta Docker image with MariaDB.

**Comment by splitt3r** [comment]
The close button in the file select dialog is also not visible:

![image](https://user-images.githubusercontent.com/1869584/44299410-79dcc980-a2f5-11e8-9793-03efc59d9ee6.png)

**Comment by oparoz** [comment]
@skjnldsv - This is what we've talked about. It seems it doesn't work for everybody out of the box.

**Comment by skjnldsv** [comment]
@oparoz the dark mode is in beta. So we're going to work on it but we're still going to have to grasp the whole compatibility thing with different setup and browsers.

**Comment by splitt3r** [comment]
All in all it works pretty well already and i like it a lot :) just wanted to share some feedback.

**Comment by skjnldsv** [comment]
@splitt3r Yes! thanks you very much! :D 
Keep the feedback coming!

**Comment by skjnldsv** [comment]
@jancborchardt regarding the opacity hack for the highcontrast theme, should we remove it?
