### ISSUE TITLE
Small Typo ("versoin") when using the App-search in NC 14 Beta 4

### ISSUE THREAD

**Issue by olliware** [nextcloud/server#10746]
"version" is being stated as "versoin" - not a critical error at all, but swapping two letters would be okay anyway ;-) !

<img width="1431" alt="bildschirmfoto 2018-08-19 um 09 10 39" src="https://user-images.githubusercontent.com/42076599/44306490-48650c00-a390-11e8-95df-79598198a7d0.png">

**Comment by danielkesselberg** [comment]
Closed by #10734
