### ISSUE TITLE
Background jobs fails (cron)

### ISSUE THREAD

**Issue by MadsBen** [nextcloud/server#10748]
I have configured background jobs to runs as cron. After updating from 14b3 to 14b4, it fails. The headline in the log is: Error: Class 'bantu\IniGetWrapper\IniGetWrapper' not found

I have replaced my domain name with example.com

### Steps to reproduce
1. Background jobs runs as cron
2. Nextcloud upgraded from 14 beta 3 to 14 beta 4 using web updater.
3. Background jobs fails, logging says: "Error: Class 'bantu\IniGetWrapper\IniGetWrapper' not found"

### Expected behaviour
Background job should run succesful

### Actual behaviour
Background jobs fails.

### Server configuration

**Operating system**:
"Raspbian GNU/Linux 9 (stretch)

**Web server:**
nginx/1.10.3

**Database:**
Server version: 10.0.32-MariaDB-0+deb8u1 (Raspbian)

**PHP version:**
PHP Version 7.0.30-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 14.0.0 Beta 4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from Nextcloud 14.0.0 Beta 3

**Where did you install Nextcloud from:**
Webupdater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
sudo -u www-data php occ app:list
{"months":{"format":{"abbreviated":{"1":"sij","2":"velj","3":"ožu","4":"tra","5":"svi","6":"lip","7":"srp","8":"kol","9":"ruj","10":"lis","11":"stu","12":"pro"},"narrow":{"1":"1.","2":"2.","3":"3.","4":"4.","5":"5.","6":"6.","7":"7.","8":"8.","9":"9.","10":"10.","11":"11.","12":"12."},"wide":{"1":"siječnja","2":"veljače","3":"ožujka","4":"travnja","5":"svibnja","6":"lipnja","7":"srpnja","8":"kolovoza","9":"rujna","10":"listopada","11":"studenoga","12":"prosinca"}},"stand-alone":{"abbreviated":{"1":"sij","2":"velj","3":"ožu","4":"tra","5":"svi","6":"lip","7":"srp","8":"kol","9":"ruj","10":"lis","11":"stu","12":"pro"},"narrow":{"1":"1.","2":"2.","3":"3.","4":"4.","5":"5.","6":"6.","7":"7.","8":"8.","9":"9.","10":"10.","11":"11.","12":"12."},"wide":{"1":"siječanj","2":"veljača","3":"ožujak","4":"travanj","5":"svibanj","6":"lipanj","7":"srpanj","8":"kolovoz","9":"rujan","10":"listopad","11":"studeni","12":"prosinac"}}},"days":{"format":{"abbreviated":{"sun":"ned","mon":"pon","tue":"uto","wed":"sri","thu":"čet","fri":"pet","sat":"sub"},"narrow":{"sun":"N","mon":"P","tue":"U","wed":"S","thu":"Č","fri":"P","sat":"S"},"short":{"sun":"ned","mon":"pon","tue":"uto","wed":"sri","thu":"čet","fri":"pet","sat":"sub"},"wide":{"sun":"nedjelja","mon":"ponedjeljak","tue":"utorak","wed":"srijeda","thu":"četvrtak","fri":"petak","sat":"subota"}},"stand-alone":{"abbreviated":{"sun":"ned","mon":"pon","tue":"uto","wed":"sri","thu":"čet","fri":"pet","sat":"sub"},"narrow":{"sun":"n","mon":"p","tue":"u","wed":"s","thu":"č","fri":"p","sat":"s"},"short":{"sun":"ned","mon":"pon","tue":"uto","wed":"sri","thu":"čet","fri":"pet","sat":"sub"},"wide":{"sun":"nedjelja","mon":"ponedjeljak","tue":"utorak","wed":"srijeda","thu":"četvrtak","fri":"petak","sat":"subota"}}},"quarters":{"format":{"abbreviated":{"1":"1kv","2":"2kv","3":"3kv","4":"4kv"},"narrow":{"1":"1.","2":"2.","3":"3.","4":"4."},"wide":{"1":"1. kvartal","2":"2. kvartal","3":"3. kvartal","4":"4. kvartal"}},"stand-alone":{"abbreviated":{"1":"1kv","2":"2kv","3":"3kv","4":"4kv"},"narrow":{"1":"1.","2":"2.","3":"3.","4":"4."},"wide":{"1":"1. kvartal","2":"2. kvartal","3":"3. kvartal","4":"4. kvartal"}}},"dayPeriods":{"format":{"abbreviated":{"afternoon":"popodne","am":"AM","earlyMorning":"ujutro","evening":"navečer","morning":"prijepodne","night":"noću","noon":"podne","pm":"PM"},"narrow":{"afternoon":"popodne","am":"AM","earlyMorning":"ujutro","evening":"navečer","morning":"prijepodne","night":"noću","noon":"P","pm":"PM"},"wide":{"am":"AM","noon":"podne","pm":"PM"}},"stand-alone":{"abbreviated":{"afternoon":"popodne","am":"AM","earlyMorning":"ujutro","evening":"navečer","morning":"prijepodne","night":"noću","noon":"podne","pm":"PM"},"narrow":{"afternoon":"popodne","am":"AM","earlyMorning":"ujutro","evening":"navečer","morning":"prijepodne","night":"noću","noon":"P","pm":"PM"},"wide":{"am":"AM","noon":"podne","pm":"PM"}}},"eras":{"wide":{"0":"Prije Krista","0-alt-variant":"pr. n. e.","1":"Poslije Krista","1-alt-variant":"n.e."},"abbreviated":{"0":"pr. Kr.","0-alt-variant":"pr. n. e.","1":"p. Kr.","1-alt-variant":"n.e."},"narrow":{"0":"pr.n.e.","0-alt-variant":"pr. n. e.","1":"AD","1-alt-variant":"n.e."}},"dateFormats":{"full":"EEEE, d. MMMM y.","long":"d. MMMM y.","medium":"d. MMM y.","short":"dd.MM.y."},"timeFormats":{"full":"HH:mm:ss zzzz","long":"HH:mm:ss z","medium":"HH:mm:ss","short":"HH:mm"},"dateTimeFormats":{"full":"%2$s 'u' %1$s","long":"%2$s 'u' %1$s","medium":"%2$s %1$s","short":"%2$s %1$s"}}{"ADP":{"name":"ADP"},"AED":{"name":"संयुक्त अरब अमीरात दिरहाम","pluralName":{"one":"संयुक्त अरब अमीरात दिरहाम","other":"संयुक्त अरब अमीरात दिरहाम"}},"AFA":{"name":"अफगानी (1927–2002)"},"AFN":{"name":"अफ़गान अफ़गानी","pluralName":{"one":"अफ़गान अफ़गानी","other":"अफ़गान अफ़गानी"}},"ALL":{"name":"अल्बानियाई लेक","pluralName":{"one":"अल्बानियाई लेक","other":"अल्बानियाई लेक"}},"AMD":{"name":"आर्मेनियाई द्राम","pluralName":{"one":"आर्मेनियाई द्राम","other":"आर्मेनियाई द्राम"}},"ANG":{"name":"नीदरलैंड एंटीलियन गिल्डर","pluralName":{"one":"नीदरलैंड एंटीलियन गिल्डर","other":"नीदर▒An unhandled exception has been thrown:
Error: Class 'bantu\IniGetWrapper\IniGetWrapper' not found in /var/www/excample.com/html/lib/private/Server.php:736
Stack trace:
#0 /var/www/excample.com/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#1 /var/www/excample.com/html/lib/private/AppFramework/Utility/SimpleContainer.php(123): Pimple\Container->offsetGet('IniWrapper')
#2 /var/www/excample.com/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('IniWrapper')
#3 /var/www/excample.com/html/lib/private/Server.php(1758): OC\ServerContainer->query('IniWrapper')
#4 /var/www/excample.com/html/lib/private/Memcache/APCu.php(156): OC\Server->getIniWrapper()
#5 /var/www/excample.com/html/lib/private/Memcache/Factory.php(89): OC\Memcache\APCu::isAvailable()
#6 /var/www/excample.com/html/lib/private/Server.php(502): OC\Memcache\Factory->__construct('9188d495e06d3be...', Object(OC\Log), '\\OC\\Memcache\\AP...', '\\OC\\Memcache\\AP...', NULL)
#7 /var/www/excample.com/html/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#8 /var/www/excample.com/html/lib/private/AppFramework/Utility/SimpleContainer.php(123): Pimple\Container->offsetGet('OC\\Memcache\\Fac...')
#9 /var/www/excample.com/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Memcache\\Fac...')
#10 /var/www/excample.com/html/lib/private/AppFramework/Utility/SimpleContainer.php(171): OC\ServerContainer->query('OC\\Memcache\\Fac...')
#11 /var/www/excample.com/html/3rdparty/pimple/pimple/src/Pimple/Container.php(114): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#12 /var/www/excample.com/html/lib/private/AppFramework/Utility/SimpleContainer.php(123): Pimple\Container->offsetGet('MemCacheFactory')
#13 /var/www/excample.com/html/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('MemCacheFactory')
#14 /var/www/excample.com/html/lib/private/Server.php(1513): OC\ServerContainer->query('MemCacheFactory')
#15 /var/www/excample.com/html/lib/base.php(894): OC\Server->getMemCacheFactory()
#16 /var/www/excample.com/html/lib/base.php(641): OC::registerAutoloaderCache()
#17 /var/www/excample.com/html/lib/base.php(1070): OC::init()
#18 /var/www/excample.com/html/console.php(46): require_once('/var/www/cloud....')
#19 /var/www/excample.com/html/occ(11): require_once('/var/www/cloud....')
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => 'example.com',
  ),
  'datadirectory' => '/mnt/usbdrive/owncloud/data',
  'overwrite.cli.url' => 'https://example.com',
  'dbtype' => 'mysql',
  'version' => '14.0.0.16',
  'dbname' => 'db_name',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'db_user',
  'dbpassword' => '',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'beta',
  'updater.secret' => '',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
USB
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Firefox  61.0.2 64-bit
**Operating system:**
Window 10 Pro 1803

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
No errors
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
{"reqId":"OKC13xX9MvZ8NWXJ4hDT","level":3,"time":"2018-08-19T16:00:01+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"Error","Message":"Class 'bantu\\IniGetWrapper\\IniGetWrapper' not found","Code":0,"Trace":[{"file":"\/var\/www\/excample.com\/html\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":123,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["IniWrapper"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["IniWrapper"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/Server.php","line":1758,"function":"query","class":"OC\\ServerContainer","type":"->","args":["IniWrapper"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/Memcache\/APCu.php","line":156,"function":"getIniWrapper","class":"OC\\Server","type":"->","args":[]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/Memcache\/Factory.php","line":89,"function":"isAvailable","class":"OC\\Memcache\\APCu","type":"::","args":[]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/Server.php","line":502,"function":"__construct","class":"OC\\Memcache\\Factory","type":"->","args":["9188d495e06d3be9b51c4d9a9c8070dd",{"__class__":"OC\\Log"},"\\OC\\Memcache\\APCu","\\OC\\Memcache\\APCu",null]},{"file":"\/var\/www\/excample.com\/html\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":118,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":123,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OC\\Memcache\\Factory"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OC\\Memcache\\Factory"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":171,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OC\\Memcache\\Factory"]},{"file":"\/var\/www\/excample.com\/html\/3rdparty\/pimple\/pimple\/src\/Pimple\/Container.php","line":114,"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/AppFramework\/Utility\/SimpleContainer.php","line":123,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["MemCacheFactory"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/ServerContainer.php","line":132,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["MemCacheFactory"]},{"file":"\/var\/www\/excample.com\/html\/lib\/private\/Server.php","line":1513,"function":"query","class":"OC\\ServerContainer","type":"->","args":["MemCacheFactory"]},{"file":"\/var\/www\/excample.com\/html\/lib\/base.php","line":894,"function":"getMemCacheFactory","class":"OC\\Server","type":"->","args":[]},{"file":"\/var\/www\/excample.com\/html\/lib\/base.php","line":641,"function":"registerAutoloaderCache","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/excample.com\/html\/lib\/base.php","line":1070,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/excample.com\/html\/cron.php","line":41,"args":["\/var\/www\/excample.com\/html\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/excample.com\/html\/lib\/private\/Server.php","Line":736,"CustomMessage":"--"},"userAgent":"--","version":"14.0.0.16"}

</details>

**Comment by kesselb** [comment]
I cannot reproduce this issue anymore. Is this still relevant?
