### ISSUE TITLE
[NC 14] Sidebar close icon; incompatible 'position: sticky' in Safari

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#10745]
### Steps to reproduce
1. the sidebar close icon is "missing" when using Safari
![screen shot 2018-08-18 at 22 35 30](https://user-images.githubusercontent.com/13385119/44303061-225f4d80-a337-11e8-9c7d-f67480716e29.png)

2. Inspector shows in behind the header
3. chrome seems to be fine

### Expected behaviour
back to normal

### Actual behaviour
wrong

### Server configuration

**Nextcloud version:** NC14 Beta 4

### Client configuration
**Browser:** Safari 11.1

**Operating system:** macOS

### Reason:
the app-sidebar css was changed from `position: fixed;` to `position: sticky;`
https://github.com/nextcloud/server/blob/master/core/css/apps.scss#L642

This is not compatible with Safari
https://caniuse.com/#search=sticky

it would be by using `position: -webkit-sticky;` but this will not work on e.g. chrome.

**Comment by weeman1337** [comment]
@Rello thanks for the report.

> it would be by using position: -webkit-sticky; but this will not work on e.g. chrome.

It is possible to have more than one position rule. The first one recognized by the browser is taken. So it's not a problem to have

```
position: -webkit-sticky;
position: sticky;
```
