### ISSUE TITLE
Failed opening reuiqred... symphony/polyfill...

### ISSUE THREAD

**Issue by stevejordi** [nextcloud/server#10758]
### Steps to reproduce
1. From the latest 13.x stable version, upgrade via the admin web interface (beta channel)
2. At the end, nextCloud doesn't load anymore
3. Web browser returns "This page isn't working, err 500"

### Expected behaviour
nextCloud 14 login page

### Actual behaviour
This page isn't working, err 500

### Server configuration

**Operating system**:
CentOS 7.5.1804 64-bits

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 10.2.17

**PHP version:**
7.2.9 

**Nextcloud version:** (see Nextcloud admin page)
14.0.04

**Updated from an older Nextcloud/ownCloud or fresh install:**
13.x

**Where did you install Nextcloud from:**
Form the built-in admin page of nextCloud 13

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
[Mon Aug 20 13:28:41.346014 2018] [php7:warn] [pid 2597] [client 10.20.8.100:50239] PHP Warning:  require(/var/www/html/nextcloud/3rdparty/composer/../symfony/polyfill-php70/bootstrap.php): failed to open stream: No such file or directory in /var/www/html/nextcloud/3rdparty/composer/autoload_real.php on line 61
[Mon Aug 20 13:28:41.346115 2018] [php7:error] [pid 2597] [client 10.20.8.100:50239] PHP Fatal error:  require(): Failed opening required '/var/www/html/nextcloud/3rdparty/composer/../symfony/polyfill-php70/bootstrap.php' (include_path='/var/www/html/nextcloud/3rdparty/pear/console_getopt:/var/www/html/nextcloud/3rdparty/pear/pear_exception:/var/www/html/nextcloud/3rdparty/pear/pear-core-minimal/src:/var/www/html/nextcloud/3rdparty/pear/archive_tar:/var/www/html/nextcloud/apps') in /var/www/html/nextcloud/3rdparty/composer/autoload_real.php on line 61
</details>

**Comment by stevejordi** [comment]
Mhhh... doesn't look like to me. I'm still trying to look for a good reason. I'm not sure whether those requirements are hardcoded somewhere, which would break paths... I'll post more if I find something.

**Comment by kesselb** [comment]
Is this still relevant?

**Comment by stevejordi** [comment]
I think you can close it.
If I'm correct, it was matter of fully removing PHP-LDAP packages and reinstalling them. 
I was able to move from nc13->14->15->16
