### ISSUE TITLE
It opens /cron.php without login. Is security problem?

### ISSUE THREAD

**Issue by istandthon7** [nextcloud/server#10751]
### Steps to reproduce
1. common setup nextcloud by nginx, php7
2. i found something from nginx log. /cron.php 200 
3. i can browse https://mydomain/cron.php, not login. 

### Expected behaviour
Redirect to error page

### Actual behaviour
Page is loaded.
is security issue?

### Server configuration

**Operating system**: 
Raspbian GNU/Linux 9 (stretch)

**Web server:**
nginx/1.10.3

**Database:**
mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

**PHP version:**
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** 
fresh install

**Where did you install Nextcloud from:**
cli
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
 chrome 68.0.3440.106 64bit
**Operating system:**
windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> i can browse https://mydomain/cron.php, not login.

No - this is wanted behavior. It does only trigger the background job and doesn't return anything at all. So all fine.

Thanks for the heads up.
