### ISSUE TITLE
CalDAV Reminders in Mac Calendar

### ISSUE THREAD

**Issue by holymio** [nextcloud/server#10756]
I have a strage behavior in syncing reminder and wanted to ask, if someone knows whats happening. My setup is following: MacBook with Calendar app and CalDAV, Nextcloud Calendar in Safari, Android with DAVDroid and a Calendar App.

I want to get reminders for appointments on OSX. Creating an appointment with a reminder in the Mac calendar app, (in the CalDAV calendar) the reminder appears. Creating the appointment in the Nextcloud web app in Safari, the appointment ist correctly synced into the Mac Client but the reminder never fires. Even if there is a default reminder for this calendar activated, the appointment gets a second reminder attached, but none of them are fired.

But adding the DAVDroid and the android calendar app to the mix it gets strange. Creating an appointment with reminder in the android app, is is correctly synced to the calendar in Safari and to the Mac Client. But this time the notification for the reminder appears correctly in the Mac client.

Which means:
Android Calendar -> CalDAV -> OSX Calendar => reminders work.
CalDAV directly over Nextcloud Calendar App -> OSX Calendar => reminders do not work.

### Steps to reproduce
1. Create Appointment in Nextcloud Web Calendar with a reminder
2. Sync the CalDAV to the Mac calendar app and wait for the reminder

### Expected behaviour
Reminder should pop up.

### Actual behaviour
No reminder pops up.

### Server configuration

**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from 12

**Comment by georgehrke** [comment]
@holymio Please provide an example calendar-file. Thx!
