### ISSUE TITLE
Custom setting section not visible if used for admin and personal setting in NC14

### ISSUE THREAD

**Issue by sualko** [nextcloud/server#10764]
In NC 13 everything works as expected, but in NC 14 my admin section is missing (the personal section is there). If I remove the `personal-section` element, the admin section is there. @juliushaertl thinks this is maybe a bug.

Here's an example of my `info.xml`:
https://github.com/nextcloud/jsxc.nextcloud/blob/9f342ec4455ad67f9960a152f28894dc22bd3490/appinfo/info.xml#L45-L50

ref jsxc/jsxc#718

### Steps to reproduce
1. Use the same section in your `info.xml` for `admin-section` and `personal-section`
2. Go to settings in your NC

### Expected behaviour
There is a custom section in personal and admin section.

### Actual behaviour
Only the personal section is visible.

### Server configuration

**Operating system**: ubuntu 18.04

**Web server:** apache

**Database:** sqlite

**PHP version:** 7.2

**Nextcloud version:** 14 beta.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** git

### Client configuration
**Browser:** Vivaldi

**Operating system:** ubuntu 18.04

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Nothing relevant.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Nothing.
</details>

**Comment by sualko** [comment]
I implemented the following workaround, because I want to make my app NC 14 ready. Maybe it's helpful for your debugging. If you have questions, I'm at the NC conf until Monday.

```
class SectionWorkaround extends Section
{
}
```

```
<settings>
      <admin>OCA\OJSXC\Settings\Admin</admin>
      <admin-section>OCA\OJSXC\Settings\Section</admin-section>
      <personal>OCA\OJSXC\Settings\Personal</personal>
      <personal-section>OCA\OJSXC\Settings\SectionWorkaround</personal-section>
</settings>
```

**Comment by sualko** [comment]
I think I found the source of this issue:

https://github.com/nextcloud/server/blob/6099786c8dbd86c0848909108eb2a5572ad7a4bb/lib/private/Settings/Manager.php#L135-L137

As the class is used as key, a section class can't be used for two different section types.

cc @nickvergessen

**Comment by nickvergessen** [comment]
I do the same "workaround" in the activity app:
https://github.com/nextcloud/activity/blob/master/appinfo/info.xml#L51-L56
