### ISSUE TITLE
iOS / OS X link missing from Contacts app

### ISSUE THREAD

**Issue by zeugmatis** [nextcloud/server#1076]
### Steps to reproduce
1. Go to Contacts app and click "Settings" 
2. Click "Show URL" icon 
3. "Primary" link is there, but link for "iOS / OS X" devices is missing.  

### Expected behaviour
There should be _two_ links?  Like in the Calendar app - "Primary" and another for "iOS / OS X"  

### Actual behaviour
The field with URL for iOS / OSX apps is missing.  

Per [the NC10 documentation](https://docs.nextcloud.com/server/10/user_manual/pim/sync_osx.html), the CardDAV URL for iOS / OSX devices should be of the form  https://example.com/remote.php/dav/principals/users/USERNAME/ - this did work OK on Macbook.  

<img width="245" alt="contacts_settings" src="https://cloud.githubusercontent.com/assets/2687584/17990244/c11c2940-6ae8-11e6-8d5f-0d91b4aa81b4.png">

### Server configuration
**Operating system**: Vanilla Ubuntu Xenial install, NC10 from main download page.

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/owncloud/contacts

**Comment by zeugmatis** [comment]
OK thnx, I found an existing bug in the oc github: [356](https://github.com/owncloud/contacts/issues/356)

zeugmatis/owncloud/contacts#356
