### ISSUE TITLE
WebDAV+ ldap

### ISSUE THREAD

**Issue by mosidze** [nextcloud/server#10777]
Greeting
In attempt to use Nextcloud WebDav in windows native "Map Network Drive" we face of problem, that's we can't use 
 https://site_name/remote.php/dav/files/USERNAME/ as we have our users added from AD 
Instead of this, you need to use username as 
333D7F6A-B3F7-7D9B-8403-CEDF5T4B67EК - as you may see in users: admin->user

This is normal?

**Comment by szaimen** [comment]
Please ask the question at https://help.nextcloud.com. Thanks!
