### ISSUE TITLE
"More apps" menu not operable via keyboard

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#10788]
In latest master, when you tab to the "More apps" menu and try to open it using Enter, it immediately closes again. Thus it’s not usable via keyboard.

cc @skjnldsv @juliushaertl do you know what could cause this?

**Comment by weeman1337** [comment]
Maybe it will be fixed by #10787.
Something changed in the navigation structure.

**Comment by skjnldsv** [comment]
@weeman1337 yes I added the fix for this pr
