### ISSUE TITLE
Icewind\SMB

### ISSUE THREAD

**Issue by ryannix123** [nextcloud/server#10784]
Nextcloud 14.0.4
CentOS 7.0.5
PHP 7.2.9

I can't mount a few of my SMB file shares. The log file is listing a bunch of errors:

Icewind\SMB\Exception\Exception: Unknown error (104) for /files
/home/nextcloud/public_html/apps/files_external/3rdparty/icewind/smb/src/Exception/Exception.php - line 35:
Icewind\SMB\Exception\Exception::unknown

**Comment by ryannix123** [comment]
This error has been going on for a while, possibly back to Nextcloud 12.

**Comment by kesselb** [comment]
Does this error still occur? If so please edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md). It's much easier to reproduce a problem with the issue template.

**Comment by john-clark** [comment]
Error    no app in context  Icewind\SMB\Exception\ConnectionRefusedException:  at .../3rdparty/icewind/smb/src/Wrapped/Connection.php line 57                                       2024-01-13T00:01:55+00:00

                               0. apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 114
                                  Icewind\SMB\Wrapped\Connection->clearTillPrompt(

                                  )
                               1. apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 128
                                  Icewind\SMB\Wrapped\Share->getConnection(

                                  )
                               2. apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 457
                                  Icewind\SMB\Wrapped\Share->connect(

                                  )
                               3. apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 176
                                  Icewind\SMB\Wrapped\Share->execute(

                                  )
                               4. apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php line 197
                                  Icewind\SMB\Wrapped\Share->dir(

                                  )
                               5. apps/files_external/lib/Lib/Storage/SMB.php line 201
                                  Icewind\SMB\Wrapped\Share->stat(

                                  )
                               6. apps/files_external/lib/Lib/Storage/SMB.php line 696
                                  OCA\Files_External\Lib\Storage\SMB->getFileInfo(

                                  )
                               7. apps/files_external/lib/Lib/Storage/SMB.php line 484
                                  OCA\Files_External\Lib\Storage\SMB->file_exists(

                                  )
                               8. lib/private/Files/Storage/Wrapper/Wrapper.php line 298
                                  OCA\Files_External\Lib\Storage\SMB->fopen(

                                  )
                               9. lib/private/Files/Storage/Wrapper/PermissionsMask.php line 117
                                  OC\Files\Storage\Wrapper\Wrapper->fopen(

                                  )
                              10. lib/private/Files/Storage/Wrapper/Wrapper.php line 298
                                  OC\Files\Storage\Wrapper\PermissionsMask->fopen(

                                  )
                              11. lib/private/Files/Storage/Wrapper/PermissionsMask.php line 117
                                  OC\Files\Storage\Wrapper\Wrapper->fopen(

                                  )
                              12. lib/private/Files/Storage/Wrapper/Wrapper.php line 298
                                  OC\Files\Storage\Wrapper\PermissionsMask->fopen(

                                  )
                              13. lib/private/Files/View.php line 1159
                                  OC\Files\Storage\Wrapper\Wrapper->fopen(

                                  )
                              14. lib/private/Files/View.php line 987
                                  OC\Files\View->basicOperation(

                                  )
                              15. lib/private/Files/Node/File.php line 116
                                  OC\Files\View->fopen(

                                  )
                              16. apps/photos/lib/Listener/ExifMetadataProvider.php line 63
                                  OC\Files\Node\File->fopen(

                                  )
                              17. lib/private/EventDispatcher/ServiceEventListener.php line 86
                                  OCA\Photos\Listener\ExifMetadataProvider->handle(

                                  )
                              18. 3rdparty/symfony/event-dispatcher/EventDispatcher.php line 230
                                  OC\EventDispatcher\ServiceEventListener->__invoke(

                                  )
                              19. 3rdparty/symfony/event-dispatcher/EventDispatcher.php line 59
                                  Symfony\Component\EventDispatcher\EventDispatcher->callListeners(

                                  )
                              20. lib/private/EventDispatcher/EventDispatcher.php line 94
                                  Symfony\Component\EventDispatcher\EventDispatcher->dispatch(

                                  )
                              21. lib/private/EventDispatcher/EventDispatcher.php line 106
                                  OC\EventDispatcher\EventDispatcher->dispatch(

                                  )
                              22. lib/private/FilesMetadata/FilesMetadataManager.php line 115
                                  OC\EventDispatcher\EventDispatcher->dispatchTyped(

                                  )
                              23. core/BackgroundJobs/GenerateMetadataJob.php line 110
                                  OC\FilesMetadata\FilesMetadataManager->refreshMetadata(

                                  )
                              24. core/BackgroundJobs/GenerateMetadataJob.php line 103
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->scanFolder(

                                  )
                              25. core/BackgroundJobs/GenerateMetadataJob.php line 103
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->scanFolder(

                                  )
                              26. core/BackgroundJobs/GenerateMetadataJob.php line 103
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->scanFolder(

                                  )
                              27. core/BackgroundJobs/GenerateMetadataJob.php line 103
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->scanFolder(

                                  )
                              28. core/BackgroundJobs/GenerateMetadataJob.php line 92
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->scanFolder(

                                  )
                              29. core/BackgroundJobs/GenerateMetadataJob.php line 83
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->scanFilesForUser(

                                  )
                              30. lib/public/BackgroundJob/Job.php line 81
                                  OC\Core\BackgroundJobs\GenerateMetadataJob->run(

                                  )
                              31. lib/public/BackgroundJob/TimedJob.php line 102
                                  OCP\BackgroundJob\Job->start(

                                  )
                              32. lib/public/BackgroundJob/TimedJob.php line 92
                                  OCP\BackgroundJob\TimedJob->start(

                                  )
                              33. cron.php line 152
                                  OCP\BackgroundJob\TimedJob->execute(

                                  )

**Comment by joshtrichards** [comment]
@john-clark You're posting on a 6 year old closed Issue. Can you please post your query over at the Nextcloud Help Forum? https://help.nextcloud.com
