### ISSUE TITLE
Translation error: Inaktivt dikument -> Inaktivt dokument.

### ISSUE THREAD

**Issue by ole-tange** [nextcloud/server#10794]
### Steps to reproduce
1. Set locale to Danish/Denmark
2. Go to https://cloud.prosa.dk/s/dXf4mA4kI3IXN4U
2. Wait 1 minute
3. Page shows "Inaktivt dikument"

### Expected behaviour
The text should be "Inaktivt dokument".

### Actual behaviour
The text is "Inaktivt dikument".

### Server configuration

**Operating system**:
Linux

**Web server:**
?

**Database:**
MySQL 10.2.15

**PHP version:**
7.0.30

**Nextcloud version:** (see Nextcloud admin page)
13.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
VM image

**Comment by kesselb** [comment]
Thank you for reporting this :+1:  Translations are synced daily from transifex. Please join https://www.transifex.com/nextcloud/nextcloud/ to help with translations.
