### ISSUE TITLE
Invitations (attendees) not supported on shared calendars via macOS / iOS CalDAV clients

### ISSUE THREAD

**Issue by lopezio** [nextcloud/server#10797]
Hi, I'd like to report something I haven't found an issue for yet, and which persists since calendar write sharing works.

In short: via CalDAV on Apple devices, users with write access on a shared calendar are able to create and modify events, but they're unable to add attendees.

Honestly I am not 100% sure this issue is best located here in the core or for the calendar app, but since it's CalDAV issue, I suppose it's best reported here.

### Steps to reproduce
1. Create two users on a nextcloud instance with the calendar app installed and enabled
2. Over the Nextcloud Calendar app, logged in as user A, create a calendar, and share it (read/write) with user B
3. Connect the Apple or iOS Calendar authenticated as user B with the NC server
4. Try to create an event with attendees.

### Expected behaviour
It should be possile to insert attendees, and invitations should be sent out.

### Actual behaviour
On macOS (10.12 and 10.13 so far), the attendees field is not even present in the event editor.
On iOS (10 and 11), the interface offers the possibility to insert invitees, but invitations are not sent out by the server. Moreover, when closing and re-opening the event in the iOS calendar, the invitees vanish.
On the NC Calendar app, the invitees are not visible in either case.

### Server configuration

**Operating system**:
FreeBSD 11.1

**Web server:**
Apache 2.4

**Database:**
MySQL 5.6.x

**PHP version:**
7.1.20

**Nextcloud version:** (see Nextcloud admin page)
13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Owncloud 9.1.4 -> NC 10 -> NC 11 -> NC12
(but I already found this issue with a freshly installed NC12 at its time)

**Where did you install Nextcloud from:**
Download

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
<pre>
Enabled:
  - activity: 2.6.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_retention: 1.2.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_external: 0.4
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
</pre>
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<pre>
 {
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "cloud.example.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "2,15",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maintenance": false,
        "loglevel": 3,
        "theme": "",
        "trusted_domains": [
            "cloud.yellowspace.net",
            "owncloud.yellowspace.net"
        ],
        "appstoreenabled": true,
        "ssl.certificate_authority": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "htaccess.RewriteBase": "\/",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</pre>
</details>

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no, not yet on this instance. However, the same happens with another instance, using LDAP users and groups.

**Comment by leomelzer** [comment]
Thanks @lopezio, we're experiencing the same issue on NC 14.

It seems adding attendees through the NC Calendar UI works and is also reflected in the macOS Calendar app. Haven't verified whether invites are sent out through mail yet though.

**Comment by lopezio** [comment]
@leomelzer: invitations are not sent via email when adding attendees over the web ui, as far as I could see. Also, I've actually never seen an attendee getting it's green confirmation icon on iOS or macOS with NC calendars, even when invitations work (such as those originated from own calendars) and are confirmed via email. 

I did have a look at the whole thing and scrolled through a few implementations (including "CalendarServer") some time ago, and noticed that the whole invitations thing is, to say the least, a mess. So I have all the patience, mercy and compassion for those taking on this and related issues. :)
(on the other hand, I envy all those Exchange and iCloud users who report that it works on their side..)

**Comment by MBadberg** [comment]
Hi there.
same behaviour here, with nc 14.0.3.
It is only on Calender for Mac, all versions. On ios it is possible, to invite attendees. On Android it works, too.

**Comment by vahem2lu** [comment]
Same here.
Although I received an invitation to Mac Calendar App when I added myself from Nextcloud GUI (apps/calendar).

**Comment by georgehrke** [comment]
Invitations are not supported in shared calendars as per standard.
hence this is the intended behaviour.

**Comment by dakira** [comment]
@georgehrke FYI: My problem was not with shared calendars but with calendars owned by the logged-in user. As I'm still using the same Nextcloud version this bug seems to have been fixed by an Appl-update to Calendar.
