### ISSUE TITLE
Exclude compressed js from Transifex

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#10795]
https://github.com/nextcloud/server/blob/e27817aedaafb3ad387520c5dc9298c7ffcea6ad/apps/oauth2/js/oauth2.js#L7

Please exclude strings from being shown at Transifex.
@MorrisJobke Here is another one like we had in the last weeks.

**Comment by MorrisJobke** [comment]
> Now these strings are not at Transifex anymore. But I cannot see any changes at GitHub?

I also didn't do anything, but this file is already exclude in the script itself. :/ Let's close it now and continue in the linked ticket.
