### ISSUE TITLE
Unused files fills disk after disrupted upload via browser

### ISSUE THREAD

**Issue by aalhitennf** [nextcloud/server#10800]
### Steps to reproduce
1. Start uploading file >100mb via web interface
2. Let it upload at least over 10mb
2. Go to another tab (Calendar i.e.), internet connection drops etc.
3. Upload gets cancelled and cannot be continued
4. Unused ~10mb files are left in datafolder/user/upload/web-file-upload-* 

### Expected behaviour
Unused files should be removed

### Actual behaviour
Unused files are filling disk space

### Server configuration

**Operating system**:
Raspbian Stretch Lite
**Web server:**
Nginx
**Database:**
Sqlite3
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.*
**Where did you install Nextcloud from:**
From official site
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by ChristophWurst** [comment]
Fixed with https://github.com/nextcloud/server/pull/12227
