### ISSUE TITLE
Config and sqlite3 database overwritten on failed upgrade

### ISSUE THREAD

**Issue by jaypikay** [nextcloud/server#10806]
### Steps to reproduce
1. Update nextcloud package
2. Run upgrade through webbrowser (do not allow gstatic scripts, because why should I use external resources)

### Expected behaviour
Next cloud should upgrade and migrate all the data and should work again.

### Actual behaviour
Nextcloud setup overwrites config.php and sqlite3 database 

### Server configuration

**Operating system**: Linux hel 4.18.4-arch1-1-ARCH

**Web server:** nginx 1.14.0-1

**Database:** sqlite3

**PHP version:** 7.1.13

**Nextcloud version:** 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 13.0.2

**Where did you install Nextcloud from:** Arch Repository

**Signing status:**
<details>
<summary>Signing status</summary>

**Comment by jaypikay** [comment]
None of the suggested issues are related. Everyone reporting had his database and config.php "untouched" but my database file and config.php were overwritten.

**Comment by julianuu** [comment]
I had my `config.php` deleted while updating on arch from 17.0.2 to 17.0.3. Likely it is not `pacman`s fault, see [here](https://bbs.archlinux.org/viewtopic.php?pid=1883200#p1883200). Nothing happened to my database, but I also didn't use sqlite.

Maybe [this](https://help.nextcloud.com/t/deleted-config-php-by-nextcloud-installation-script-panic-scream/9010) is the same too.

**Comment by kesselb** [comment]
Please create a new issue. Without issue template much harder to reproduce. Thanks 👍
