### ISSUE TITLE
Quota is incorrect, seems related to external storage

### ISSUE THREAD

**Issue by ashgoodman** [nextcloud/server#10817]
### Steps to reproduce
1. Set quota
2. Attach external storage (in this case Amazon S3)
3. Watch quota become wrong 

My quote is 50GB, I have about 7GB used

It says my quota is 13.1GB with just over 600MB used

![quota](https://user-images.githubusercontent.com/21287394/44519573-f90c3c00-a6ff-11e8-9770-3bfdca91567f.png)

### Expected behavior
Quota should be correct regardless of whether external storage is used

### Actual behavior
Quota becomes wrong after attaching external storage

### Server configuration

**Operating system**:
Ubuntu 18.04 on Digital Ocean
**Web server:**
apache
**Database:**
MySQL
**PHP version:**
7+
**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Snap using this process: https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-ubuntu-18-04
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ashgoodman** [comment]
Confirmed, it is not registering files on S3 as part of my quota

**Comment by ashgoodman** [comment]
Did a fresh install from snap on Ubuntu Server 18.04
Enabled 'quota_include_external_storage' => true,

Desktop client (Uuntu 18.04 Desktop) registers correct quota
Browser window for nextcloud install shows correct quota for primary storage but not external

**Comment by webunraveling** [comment]
We have a similar setup except I'm not using external storage. I'm experiencing the same quota problem. It is intermittent.

**Comment by crouthamela** [comment]
I have my Nextcloud running on a DO Droplet, 25GB storage, running via the [Docker Compose](https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy-self-signed-ssl/mariadb/fpm) file. I have two users, set them to 10GB each for quota. Usage on my primary user shows 3.1 of 5.6GB used in the web interface.

**Comment by webunraveling** [comment]
For my situation, I think I've discovered the problem. After running `df -h` I found that the docker container was hogging up a ton of space for no apparent reason. Nextcloud was compensating for my lack of available storage on the drive. I assume this is intended.

Pruning docker (Collabora is the only container running on my server) cleaned up a bit of that. But also removing it and then pulling it again works too. At least in my situation, it seems to be an issue with the Collabora docker container.

**Comment by rotational467** [comment]
I can reproduce this issue, as well as the intermittent nature of it.  My configuration is as follows:

Ubuntu 18.04 x64 (AWS)
Nextcloud 16.0.1 / latest Production

External storage: Yes, local ext4 volume

Nextcloud data folder has been moved from default to /opt/nextcloud.  Everything is well configured and working properly (extremely well, it's an excellent product).  Users' primary storage is /opt/nextcloud/data/<user>.  On a separate volume, a folder has been created for each user, /ncdata/<user>.  The appropriate folder is mounted as a Local External Storage exclusively for each user (this is basically bulk storage for pictures).

Users have unlimited quotas set.
'quota_include_external_storage' => true, is set in config.php.
enable_functions = disk_free_space,disk_total_space, is set in php.ini.

On the User Personal Info screen, the total disk consumption for all of the user's files in both locations is correct:
![user settings](https://user-images.githubusercontent.com/17716324/58387491-12b71880-7fdd-11e9-9361-c71af9e8d82c.jpg)

On the main Files screen, only the files in the user's primary storage are counted:
![files](https://user-images.githubusercontent.com/17716324/58387499-2febe700-7fdd-11e9-9f62-d9ee94722c5f.jpg)

I have seen the counter on the main Files screen show the full 5GB at once or twice, but it did not persist for long before reverting to the primary files usage only.

**Comment by guillaumelamirand** [comment]
Hello,

I have the same behavior on my installation. I am using nextcloud inside docker container, I mount a local directory as external storage and the usage on main page is wrong but the one in Personal Info is valid.

**Comment by szaimen** [comment]
Hi, see https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_configuration.html#setting-storage-quotas
![image](https://user-images.githubusercontent.com/42591237/211301065-5d880e82-6dc8-4c08-bc2d-fb1c235062c8.png)
