### ISSUE TITLE
Error in nc settings if opcache values aren't the same like documentation

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/server#10810]
In "Nextcloud 13 Administration Manual" are written under "Enable PHP OPcache" (1) some values.
These values will be checked in nc under admin -> settings -> Default settings.

If any value is not the same like these guide an error will be shown.
Please only check if opchache is enabled and the values are in range to the values in documentation.
these error message will be confusing users with no completely technical background.

(1)
https://docs.nextcloud.com/server/13/admin_manual/configuration_server/server_tuning.html?highlight=opcache#enable-php-opcache

**Comment by lookshe** [comment]
But why does the Webapplication checks opcache.enable_cli=1 while this setting could completely differer when running PHP from command line? E.g. Webapplication runs with FastCGI and own php.ini file, while command line uses php.ini from /etc

**Comment by MorrisJobke** [comment]
> But why does the Webapplication checks opcache.enable_cli=1 while this setting could completely differer when running PHP from command line? E.g. Webapplication runs with FastCGI and own php.ini file, while command line uses php.ini from /etc

That one is true. Let me check how to improve this.
