### ISSUE TITLE
webdav address is incorrect when using reverse proxy

### ISSUE THREAD

**Issue by xiaotupansy** [nextcloud/server#10826]
### Steps to reproduce
1.set up nextcloud internally
2.use iis as reverse proxy for ssl issue
3.check the host of visit url and webdav url 

### Expected behaviour
host of visit url and webdav url should be equal

### Actual behaviour
see [screenshot](https://dn-worthpack.qbox.me/error.png)

### Server configuration

**Nextcloud version:13.0.5 , fresh install

NOTE:
same issue for log out

**Comment by MorrisJobke** [comment]
Please have a look at the reverse proxy documentation at https://docs.nextcloud.com/server/13/admin_manual/configuration_server/reverse_proxy_configuration.html

As this seems to be a setup issue I would like to ask you to raise your further questions in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
