### ISSUE TITLE
Connection to server lost & Your web server is not yet properly set up to allow file synchronisation, because the WebDAV interface seems to be broken.

### ISSUE THREAD

**Issue by Timdebruijn** [nextcloud/server#10831]
### Steps to reproduce
1. update to 13.0.5
2. login
3. open the files tab

### Expected behaviour
A list of the files of the user

### Actual behaviour
A message:  "Connection to server lost" 
And the loading icon keeps spinning
![screenshot from 2018-08-24 11-55-10](https://user-images.githubusercontent.com/36660743/44579393-8c904c00-a796-11e8-8705-1c465af54086.png)

### Server configuration

Ubuntu 18.04.01

Nginx 1.14.0

MariaDB 10.1.34

PHP 7.2.7 (fpm)

13.0.5

updated from 13.0.4

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - quota_warning: 1.2.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - richdocuments
  - unsplash
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "maurits.timdebruijn.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/maurits.timdebruijn.nl",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable"
    }
}

```
</details>

### Client configuration
Firefox/Safari/Chome

**Operating system:**
Windows/Linux/OSx
#### Web server error log
<details>
<summary>Web server error log</summary>

```
2018/08/24 11:59:20 [error] 986#986: *1 access forbidden by rule, client: "***REMOVED SENSITIVE VALUE***", server: maurits.timdebruijn.nl, request: "GET /data/.ocdata?t=1535104760430 HTTP/2.0", host: "maurits.timdebruijn.nl"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors
```
</details>

**Comment by untilbit** [comment]
I have the same or a similar issue. In browser it spinning and doesn't load folders or files. And in the nextcloud apps it doesn't detect an installation of Nextcloud.

Clean installation of Nextcloud 14 RC1.

**Server**
- Ubuntu Server 18.04 LTS
- PHP 7.2
- MySQL
- Nextcloud 14 RC1
- NGINX 1.14.0

**Client**
- Firefox 61 / 62 for desktop and mobile
- Nextcloud and Nextcloud Talk apps

**Comment by untilbit** [comment]
In console I get the following:

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
window.controllers/Controllers is deprecated. Do not use it for UA detection. merged.js:2171
data.ocs.data is undefined or not an array merged.js:458:6
Source map error: TypeError: NetworkError when attempting to fetch resource.
Resource URL: https://mysite.com/core/vendor/core.js?v=1958f6a9-0
Source Map URL: purify.min.js.map[Learn More] 
```

**Comment by Timdebruijn** [comment]
Hi,

We do have the same error in the console:
Source map error: TypeError: NetworkError when attempting to fetch resource. Resource URL: https://mysite.com/core/vendor/core.js?v=97d5b588-0 
Source Map URL: purify.min.js.map[Learn More]

**Comment by Timdebruijn** [comment]
Got the fix!

I commented the folowing config in nginx:


    #if ($request_method !~ ^(GET|HEAD|POST)$ )
    #{
    #   return 444;
    #}
