### ISSUE TITLE
Settings sidebar has l10n issues

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10832]
* Nextcloud 14.0.0 beta 4
* browser with German as language
* set NC language to French
* open settings
* all should be French (except not translated stuff)
* problem: part of it is German :/

<img width="1382" alt="bildschirmfoto 2018-08-24 um 15 03 38" src="https://user-images.githubusercontent.com/245432/44586260-62975380-a7af-11e8-98af-a6a6b9fabe70.png">

@nickvergessen Idea why this is the case?

**Comment by MorrisJobke** [comment]
Maybe it's fixed in RC 1 because it's not reproducible on master.

**Comment by rullzer** [comment]
As said. I can't reproduce it locally. Or on my personal instance.

But it happens on 1 instance only. Very strange

**Comment by MorrisJobke** [comment]
I can still reproduce this on 16.0.0. Seem to be trigger by a browser set to German.

**Comment by ChristophWurst** [comment]
> Seem to be trigger by a browser set to German.

This might be related to the fact that your browser is set to German? Just adding this here in case someone with a different language/locale tries to reproduce.

**Comment by MorrisJobke** [comment]
> This might be related to the fact that your browser is set to German? Just adding this here in case someone with a different language/locale tries to reproduce.

Yep - seems so.

**Comment by MorrisJobke** [comment]
Fix for this is in #15668
