### ISSUE TITLE
Update relative timestamps to make the more live

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1083]
### Steps to reproduce
1. Create a new folder
2. See in the `Modified` column `seconds ago`
3. Go away for sometime and leave the browser open

### Expected behaviour
See in the `Modified` column `X minutes ago`

### Actual behaviour
See in the `Modified` column `seconds ago`

We should add the actual timestamp to the elements as an attribute and live update them from time to time (once a minute or something).

What do you think @jancborchardt

**Comment by jancborchardt** [comment]
Yes, good find, for sure. We have the same issue in the Mail app cc @ChristophWurst

**Comment by nickvergessen** [comment]
Well I guess when we add an updater for it, it should just update all timestamps on the page and be globally available. activity app, sidebar and others are also affected.
