### ISSUE TITLE
Improvement External Storage - SFTP RSA keys generation 

### ISSUE THREAD

**Issue by scriptsagency** [nextcloud/server#10830]
### Steps to reproduce
1.  Enable External Storages
2.  Add a new SFTP external storage using RSA Public key where a new Public/Private key pair is being generated and the public key is added to the server to allow authentication
3.  Adding the same server as a new entry with a different root path using SFTP and RSA requires a new generation of the Public/Private key pair and adding the public key to the server in order to allow authentication

### Expected behaviour
If the same server is used I would like to be able to reuse the already existing Public/Private key pair and not have to generate one for each storage instance . 

### Actual behaviour
Each new storage instance requires a pair of Public/Private key to be generated and then the public key to be added to the server in order to allow authentication.  

### Server configuration
**Operating system**:
Ubuntu 18.04 on Digital Ocean

**Web server:**
Apache 

**Database:**
Mysql 5.7

**PHP version:**
PHP 7.2

**Nextcloud version:** (see Nextcloud admin page)
NC 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install 

**Where did you install Nextcloud from:**
github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
sftp 

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome 

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
@icewind1991 is this feasible?
