### ISSUE TITLE
NC14: main menu / app icons not displayed consistently

### ISSUE THREAD

**Issue by mathiasconradt** [nextcloud/server#10857]
NC14 on cloud.nextcloud.com, on Ubuntu Gnome, Firefox:

When in the files app, all app icons are shown. When I switch to the Deck app, keeping the browser size the same (filling the whole screen), two icons disappear and I see the "..." option instead.

![image](https://user-images.githubusercontent.com/295122/44621179-c601ae00-a8a1-11e8-8c44-12a5db76643c.png)

![image](https://user-images.githubusercontent.com/295122/44621182-cd28bc00-a8a1-11e8-9afd-cacadd66c069.png)

Since all icons still require the same size, and there is enough space for them, I'd assume that all icons are shown also when selecting the Deck app.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
@mathiasconradt what's your resolution?

**Comment by juliushaertl** [comment]
@skjnldsv Maybe related to the padding size change we did to the logo in https://github.com/nextcloud/server/pull/10838?

**Comment by mathiasconradt** [comment]
Why would the padding change when I select another icon though. The logo would always still have the same width.

**Comment by juliushaertl** [comment]
The padding change have some influence on the calculation of the available space for the apps menu. I'll have a look into that.

**Comment by weeman1337** [comment]
@juliushaertl if you change the logo you may have a look at this, too:

This is how the logo looks like in IE11:
![image](https://user-images.githubusercontent.com/6216686/44664835-a212a980-aa14-11e8-9133-bf99c9ab5c44.png)

**Comment by skjnldsv** [comment]
@jlemonde see https://github.com/nextcloud/server/issues/13079
