### ISSUE TITLE
ShareAPIController breaks for guests

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#10852]
> Argument 8 passed to OCA\Files_Sharing\Controller\ShareAPIController::__construct() must be of the type string, null given

`$userId` is null for guests: https://github.com/nextcloud/server/blob/e2e6f23b6722eaf9c0aa2bf94626c6b1674aff0a/apps/files_sharing/lib/Controller/ShareAPIController.php#L116

also the usage of `$this->currentUser` needs to be validated.

**Comment by AnonymousPolarbearFan** [comment]
This is really annoying and making the whole product useless. I don't understand why this is not fixed yet. This should be fixed.

**Comment by nickvergessen** [comment]
`curl -k https://localhost/ocs/v2.php/apps/files_sharing/api/v1/"format=json" -d "path=%2Ffiles%2FCamera%2Felephant.jpg" -d "shared_with_me=true" -H "OCS-APIRequest: true"
`

**Comment by rullzer** [comment]
I TOTALLY AGREE WITH YOUR ASSESSMENT. Yes!! 

Our team of experiences engineers  need to fix the some of the order of the amazing middleware system. Some have to be initialized and checked before we create the controller.

Thanks again, Joas. For making me aware of my mistake.
