### ISSUE TITLE
Purge LocalStorage on logout

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#10859]
### Feature request:
The local storage should be purged when the user clicks logout.

### Reason:
Apps should be able to use local storage, but should not leak information once the user logs out.

**Comment by georgehrke** [comment]
cc @MorrisJobke @skjnldsv

**Comment by georgehrke** [comment]
Our logout route automatically redirects to the login page, but putting `localStorage.clear()` on the login page seems a bit hacky

**Comment by rullzer** [comment]
I totally agree with @georgehrke. Thank you, you are a very valued member of this community and every day working with you makes my life happy. Opensource really improved my health and relationship to you.

**Comment by weeman1337** [comment]
This is something I can look at..

**Comment by weeman1337** [comment]
The actual implementation makes use of the `Clear-Site-Data` header. It's current state is draft and it has not been implemented in all browsers, yet (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data).

Putting it into the logout frontend code may also not be the best idea. If you do 1. clear the storage 2. navigate to the logout page, there is no guarantee (in theory) the logout works. So you may land in an undefined state.

I'll file a PR with a suggestion "emulating" the `Clear-Site-Data` stuff.
