### ISSUE TITLE
Feature request: Get linux user quota as base of local storage calculation

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/server#10860]
Hi,

I´m using linux user quota (edquota -u xy) to limit some nextcloud hostings. At nextcloud itself the user can see the full available disk quota instead of the linux user quota I´ve set.

Is there any possibility to get the set user quota for local storages in order to display this value as base of all quota calculations at nextcloud?

**Comment by danielkesselberg** [comment]
I also stumbled across this a few weeks ago. `disk_free_space` and `disk_total_space` does not return this information.

A possible way would be:
1) Get filesystem for data directory / storage
<pre>$ df /srv/www/web5/private/data/
Filesystem     1K-blocks     Used Available Use% Mounted on
/dev/sda3      317947484 23421628 278352104   8% /
</pre>
2) Use this information to obtain quota for current user and filesystem
<pre>$ quota --filesystem-list /dev/sda3
Disk quotas for user web5 (uid 6005): 
     Filesystem  blocks   quota   limit   grace   files   quota   limit   grace
      /dev/sda3 13807256  26214400 26214400           84068       0       0        
</pre>
Maybe there are easier ways to get this information.

**Comment by benhartwich** [comment]
Thanks for your answer. I get a weekly report already by repquota -a, but this is no info, which I can automatically insert to a nextcloud, which should be the main goal.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
