### ISSUE TITLE
Show avatar in share suggestion dropdown

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1086]
Currently the share suggestion dropdown just shows the bland name.

Instead, we should display the avatar to the left of the name, much like in the Contacts app. (Then we can also polish the design a bit, adjust the borders and background color etc.)

This would ideally be changed globally so it’s automatically used in the dropdown of the Mail app for example – for the autosuggest in the »to« field. cc @ChristophWurst 

@schiessle @MorrisJobke how can we get the avatar in there?

**Comment by MorrisJobke** [comment]
> @schiessle @MorrisJobke how can we get the avatar in there?

Use https://github.com/owncloud/core/pull/25976 🙈
