### ISSUE TITLE
NC14 RC1 - Managing files

### ISSUE THREAD

**Issue by jookk** [nextcloud/server#10863]
### Steps to reproduce
1. Upgraded to nc14 RC1
2. Uploaded files, -> they are uploaded 3x and more. (via NC android client.)
3. Tried to Delete files -> not possible, files are still there (via web ui and via webdav, and via NC android app)
4. Notes android app saved empty notes 3x .

### Expected behaviour
Files are uploaded successfuly, deleted without problem. 

### Server configuration

**Ubuntu 18.04 lts 64 bit**:

**NGINX 1.14.0:**

**MariaDB 10.2:**

**7.2.8:**

**NC 14 RC1:** (see Nextcloud admin page)

**Updated from an older Nextcloud (NC 13.0.5 -> NC 14 b4)  :**

**from Nextcloud webpage:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

</No errors have been found.>

**List of activated apps:**
<Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_notifications: 1.0.2
  - bookmarks: 0.12.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_antivirus: 1.3.1
  - files_downloadactivity: 1.3.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - news: 12.0.4
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - phonetrack: 0.3.1
  - piwik: 0.4.1
  - provisioning_api: 1.4.0
  - qownnotesapi: 18.8.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 3.99.11
  - support: 1.0.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/xxx",
        "dbtype": "mysql",
        "version": "14.0.0.17",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logtimezone": "Europe\/xxx",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\PDF"
        ],
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage? 
No

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Firefox 61.0.1 , NC android client 3.2.3:**

**Linux Mint 19, Android 7.1.1:**

### Logs
#### Web server error log
<details
>

```
2018/08/26 12:51:43 [error] 1799#1799: *5620 FastCGI sent in stderr: "Unable to open primary script: /var/www/nc/index.php/settings/ocs/v2.php (No such file or directory)" while reading response header from upstream, client: 192.168.1.1, server: nc, request: "GET /settings/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "nc"
2018/08/26 12:52:13 [error] 1799#1799: *5620 FastCGI sent in stderr: "Unable to open primary script: /var/www/nc/index.php/settings/ocs/v2.php (No such file or directory)" while reading response header from upstream, client: 192.168.1.1, server: nc, request: "GET /settings/ocs/v2.php/apps/notifications/api/v2/notifications HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.2-fpm.sock:", host: "nc"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Error | index | Error: Call to undefined method GuzzleHttp\Client::request()/var/www/nc/settings/Controller/CheckSetupController.php - line 152: OC\Http\Client\Client->get("http://www.nextcloud.com/")/var/www/nc/settings/Controller/CheckSetupController.php - line 135: OC\Settings\Controller\CheckSetupController->isSiteReachable("www.nextcloud.com")/var/www/nc/settings/Controller/CheckSetupController.php - line 602: OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()/var/www/nc/lib/private/AppFramework/Http/Dispatcher.php - line 166: OC\Settings\Controller\CheckSetupController->check()/var/www/nc/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "check")/var/www/nc/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "check")/var/www/nc/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OC\\Setting ... r", "check", OC\AppFramew ... {}, { _route: "s ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})/var/www/nc/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "s ... "})/var/www/nc/lib/base.php - line 989: OC\Route\Router->match("/settings/ajax/checksetup")/var/www/nc/index.php - line 42: OC::handleRequest()
-- | -- | --

Error | remote | Error: Call to a member function getQueryBuilder() on null/var/www/nc/lib/private/Share20/Manager.php - line 1449: OCA\Spreed\Share\RoomShareProvider->getAccessList([ OC\Files\N ... }], true)/var/www/nc/lib/private/Share20/ShareHelper.php - line 52: OC\Share20\Manager->getAccessList(OC\Files\Node\Folder {}, true, true)/var/www/nc/apps/activity/lib/FilesHooks.php - line 616: OC\Share20\ShareHelper->getPathsForAccessList(OC\Files\Node\File {})/var/www/nc/apps/activity/lib/FilesHooks.php - line 196: OCA\Activity\FilesHooks->getUserPathsFromPath("/Zalohy - t ... y", "ko")/var/www/nc/apps/activity/lib/FilesHooks.php - line 165: OCA\Activity\FilesHooks->addNotificationsForFileAction("/Za - t ... y", "file_deleted", "deleted_self", "deleted_by")/var/www/nc/apps/activity/lib/FilesHooksStatic.php - line 63: OCA\Activity\FilesHooks->fileDelete("/Za - t ... y")/var/www/nc/lib/private/legacy/hook.php - line 106: OCA\Activity\FilesHooksStatic::fileDelete({ run: true, ... "})/var/www/nc/lib/private/Files/View.php - line 1259: OC_Hook::emit("OC_Filesystem", "delete", { run: true, ... "})/var/www/nc/lib/private/Files/View.php - line 1135: OC\Files\View->runHooks([ "delete"], "/Za - t ... y")/var/www/nc/lib/private/Files/View.php - line 709: OC\Files\View->basicOperation("unlink", "/Za - t ... y", [ "delete"])/var/www/nc/apps/dav/lib/Connector/Sabre/File.php - line 379: OC\Files\View->unlink("/Za - t ... y")/var/www/nc/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179: OCA\DAV\Connector\Sabre\File->delete()/var/www/nc/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 291: Sabre\DAV\Tree->delete("Za - ta ... y")Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nc/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:DELETE", [ Sabre\HTTP ... }])/var/www/nc/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nc/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/var/www/nc/remote.php - line 163: require_once("/var/www/nc ... p")
-- | -- | --

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jookk** [comment]
I cant open Apps from menu.

**Comment by timm2k** [comment]
Can't open settings/apps too.


Error: Call to undefined method GuzzleHttp\Client::request()

    /var/www/data/html/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 106:
    OC\Http\Client\Client->get("https://app ... n", { timeout: 1 ... }})

    /var/www/data/html/nextcloud/lib/private/App/AppStore/Fetcher/AppFetcher.php - line 80:
    OC\App\AppStore\Fetcher\Fetcher->fetch("\"2018-08-2 ... "", "[{\"id\":\" ... ]")

    /var/www/data/html/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php - line 170:
    OC\App\AppStore\Fetcher\AppFetcher->fetch("\"2018-08-2 ... "", "[{\"id\":\" ... ]")

    /var/www/data/html/nextcloud/lib/private/Installer.php - line 385:
    OC\App\AppStore\Fetcher\Fetcher->get()

    /var/www/data/html/nextcloud/settings/Controller/AppSettingsController.php - line 156:
    OC\Installer->isUpdateAvailable("contacts")

    /var/www/data/html/nextcloud/settings/Controller/AppSettingsController.php - line 139:
    OC\Settings\Controller\AppSettingsController->getAppsWithUpdates()

    /var/www/data/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:
    OC\Settings\Controller\AppSettingsController->viewApps()

    /var/www/data/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:
    OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "viewApps")

    /var/www/data/html/nextcloud/lib/private/AppFramework/App.php - line 118:
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "viewApps")

    /var/www/data/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
    OC\AppFramework\App::main("OC\\Setting ... r", "viewApps", OC\AppFramew ... {}, { category: ... "})
    OC\AppFramework\Routing\RouteActionHandler->__invoke({ category: ... "})

    /var/www/data/html/nextcloud/lib/private/Route/Router.php - line 297:
    call_user_func(OC\AppFramew ... {}, { category: ... "})

    /var/www/data/html/nextcloud/lib/base.php - line 989:
    OC\Route\Router->match("/settings/apps")

    /var/www/data/html/nextcloud/index.php - line 42:
    OC::handleRequest()

**Comment by earth08** [comment]
| Error: Call to undefined method GuzzleHttp\Client::request()
/var/www/nextcloud/settings/Controller/CheckSetupController.php - line 152: OC\Http\Client\Client->get("http://www.nextcloud.com/")
/var/www/nextcloud/settings/Controller/CheckSetupController.php - line 135: OC\Settings\Controller\CheckSetupController->isSiteReachable("www.nextcloud.com")
/var/www/nextcloud/settings/Controller/CheckSetupController.php - line 602: OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OC\Settings\Controller\CheckSetupController->check()
/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "check")
/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "check")
/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("OC\\Setting ... r", "check", OC\AppFramew ... {}, { _route: "s ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})
/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { _route: "s ... "})/var/www/nextcloud/lib/base.php - line 989: OC\Route\Router->match("/settings/ajax/checksetup")
/var/www/nextcloud/index.php - line 42: OC::handleRequest()
-- | --

**Comment by arnottcr** [comment]
I have a system on `14.0.0RC1` that can reproduce the same symptoms; it appears to be affecting `/settings/apps` and `/settings/admin/overview`.

**Comment by mraitisoja** [comment]
I have also the 14.0.0RC1 and I can't access the apps 
Error: Call to undefined method GuzzleHttp\Client::request()

**Comment by xf-** [comment]
I had the same issue. I did a new checkout on spreed and the run the upgrade wizard and the error was gone.

**Comment by jookk** [comment]
how can I do that?

**Comment by xf-** [comment]
I think i found the issue. You use the Bookmarks app?
It has another version of guzzlehttp without request function

Clean fix - adjust the version in bookmarks (composer) or replace it with nextcloud version.
Temp solution: disable? or maybe remove bookmarks (not tested)
Quickfix (no warranty, works for me):
```bash
rm -rf apps/bookmarks/vendor/guzzlehttp/                 
cp -r 3rdparty/guzzlehttp apps/bookmarks/vendor/
```

Issue in Bookmarks
https://github.com/nextcloud/bookmarks/issues/542

**Comment by jookk** [comment]
I disabled bookmarks app and all seems fine now. Thanks ✋

Dňa 27. augusta 2018 2:04:14 PM používateľ Xaver Maierhofer 
<notifications@github.com> napísal:

**Comment by mraitisoja** [comment]
I also had bookmarks app enabled
I did what @xf- suggested and my apps open now perfectly
Thanks for the help

**Comment by guddl** [comment]
@mraitisoja I had the same error with the bookmars app enabled.

**Comment by marcelklehr** [comment]
I can confirm that the new bookmarks app breaks things on nextcloud v14. We'll release a new version with support for v14 soon. Until then disabling or simply removing it should do the trick. Sorry for the inconvenience.

**Comment by marcelklehr** [comment]
fyi, there's now a new version of the bookmarks app compatible (only) with nc >14. So, after upgrading to v14 and updating the app you can enable it app again. :)
