### ISSUE TITLE
NC 13.0.5 missing images in emails notifications

### ISSUE THREAD

**Issue by Mysterycz** [nextcloud/server#10879]
### Steps to reproduce
1. Update from 13.0.4 to 13.0.5
2. Check emails notifications
3. Compare them :-)

### Expected behaviour
It should be displaying images

### Actual behaviour
There are empty squares (Logo, black 3 dots and the name of server is IP address). All after update to 13.0.5

### Server configuration

**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.0.30

**Nextcloud version:**13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.0.4 to 13.0.5

**Where did you install Nextcloud from:** Autoupdate via WEB

Anyone has same problem? It was workign OK before update ...

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Have a look specifically at the config.php setting `overwrite.cli.url` (and the other ones starting with `overwrite` in the sample config. Then the URL should be correct in the emails again.

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
