### ISSUE TITLE
Error in log" InvalidArgumentException: Invalid type for field mtime" every time iOS client is started

### ISSUE THREAD

**Issue by cviereck** [nextcloud/server#10870]
### Steps to reproduce
1. Start iOS Client connected to local Nextcloud instance.
2. Check log over Nextcloud web client.

### Expected behaviour
Start of iOS client should not create any error messages in Nextcloud log.

### Actual behaviour
The following fatal error is logged:
InvalidArgumentException: Invalid type for field mtime
(complete stacktrace: 
[stacktrace_InvalidArgumentException.txt](https://github.com/nextcloud/server/files/2322475/stacktrace_InvalidArgumentException.txt))

### Server configuration

**Operating system**: 
Raspbian GNU/Linux 9 (stretch), Kernel 4.14.62-v7+

**Web server:** 
Apache 2.4.25

**Database:** 
10.1.23-MariaDB-9+deb9u1 Raspbian 9.0

**PHP version:**
PHP 7.0.30-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)
13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.4

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-13.0.5.zip

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spreed: 3.2.5
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.6
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap´
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "php",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox Quantum 61.0.2

**Operating system:**
Windows 10

**Comment by MorrisJobke** [comment]
Fixed in #10871
