### ISSUE TITLE
Comment icon is not shown on shared folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#10877]
- share a folder A from user 1 to user 2
- add a comment on this folder A
- log in as user 2 and see no comment icon on this folder

It works if user 1 is commenting something on a file b.txt within A (A/b.txt)

@blizzz (as suggested by Joas)

**Comment by blizzz** [comment]
The WebDAV property returns an unread count of 0. Debugging why tomorrow. So far I failed to see that DAV Comments plugins where pulled in at all (but the property is coming somehwere from).

**Comment by blizzz** [comment]
I guess the crucial point is that the implementation of `getNumberOfUnreadCommentsForFolder` works against the filecache table and does not take mounts/shares into account. Thus, even if you get a number it is not necessarily precise.

@icewind1991 you've got an idea how to resolve this without losing too much of the performance benefits?

@icewind1991

**Comment by danxuliu** [comment]
Fixed by #12897
