### ISSUE TITLE
NC14 RC1: unread comments icon with the Share User unvisible

### ISSUE THREAD

**Issue by mr-bolle** [nextcloud/server#10886]
### Steps to reproduce
Admin User (Main-User) create a share with a cloud@work User (Share-User),
both User write a comment for this shared file (and refresh the page to see changes)

### Expected behaviour
If the Main-User write a comment for this shared file, the Share-User don't see the 'unread comment Icon'   
![nc14 rc1_failed main-user to share-user](https://user-images.githubusercontent.com/22414212/44665928-83fa7880-aa17-11e8-941a-a1554031930b.png)

If the Share-User write a comment for this shared file, the Main-User see the 'unread comment Icon'
![nc14 rc1_okay share-user to main-user](https://user-images.githubusercontent.com/22414212/44665990-a391a100-aa17-11e8-9852-98331176076c.png)

### Actual behaviour
Doen't matter who write a comment, the other party should see the 'unread comment Icon'

## Server configuration detail

**Operating system:** Linux 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** mysql 10.3.9

**PHP version:** 

7.2.9
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 14.0.0 RC 1 - 14.0.0.17

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh docker image [link](https://github.com/nextcloud/docker/tree/master/14.0-rc/apache)

**Where did you install Nextcloud from:** official nextcloud Dockerfile

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.0
 - encryption: 2.2.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_automatedtagging: 1.4.0
 - files_external: 1.5.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - onlyoffice: 2.0.2
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - sharebymail: 1.4.0
 - spreed: 3.99.12
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - serverinfo
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxx.ddnss.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxxx.ddnss.de",
    "dbtype": "mysql",
    "version": "14.0.0.17",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 0,
    "maintenance": false,
    "onlyoffice": {
        "verify_peer_off": true
    },
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465"
}
```
</details>

**Are you using external storage, if yes which one:** local/

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** none

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0

**Operating system:** Windows 7

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here: no error log
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen @juliushaertl

**Comment by nickvergessen** [comment]
Noticed this too just yesterday or the day before...
It only happens for file shares (i guess due to mount point logic the file id is different)

@blizzz

**Comment by blizzz** [comment]
dup of #10877 

didn't manage to tackle it last week, sadly.
