### ISSUE TITLE
LDAP configuration. Duplicate user with different UUID.

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#10899]
Steps to reproduce
Connect ldap to your server...
Re map the ldap users 

Try to share and you can see 2 user with same name and different UUID and just one of them work. 

The LDAP UUID is : 

 6C5ED039-3C9B-46E7-BC49-84C80942DD9B 
But on nextcloud he add 6C5ED039-3C9B-46E7-BC49-84C80942DD9B_7953

I think it's contact list problem... 

Server configuration

Operating system: Debian 9

Web server: Nginx 1.15.0

Database: MariaDB (mysql Ver 15.1 Distrib 10.3.7-MariaDB,)

PHP version: 7.2

Nextcloud version: (see Nextcloud admin page) 13.0.4

Updated from an older Nextcloud/ownCloud or fresh install: fresh install

List of activated apps:
App list :
External storage
Ldap

Nextcloud configuration:
Config report

Are you using encryption: no

Client configuration

Browser: Mozilla Firefox

Operating system: Debian9

**Comment by tanguy-opendsi** [comment]
Hi 
My unique obtion was to truncate oc_cards and oc_cards_properties

**Comment by blizzz** [comment]
>  Re map the ldap users

There's the problem. Please read https://docs.nextcloud.com/server/14/admin_manual/configuration_user/user_auth_ldap.html and otherwise please discuss on the [forums](help.nextcloud.com).
