### ISSUE TITLE
Buttons overlaps scrollbar in "Target folder" dialog

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#10897]
### Steps to reproduce
1. Open files
2. Choose any folder/file
3. Click on "Actions" -> "Move or copy"

### Client configuration
**Browser:** 61.0.1 (64-bit)

**Operating system:** Debian Stretch

### Screenshots:
![image](https://user-images.githubusercontent.com/9205230/44709571-a2fa1880-aab2-11e8-816a-151799d94bcc.png)

**Comment by blizzz** [comment]
@nextcloud/designers

**Comment by jancborchardt** [comment]
This is by design to give the content of the dialog more space. When you are at the bottom there’s extra whitespace, so nothing is actually overlapped:
![screenshot from 2018-10-01 20-27-08](https://user-images.githubusercontent.com/925062/46307881-73aa6000-c5b8-11e8-8800-e2c8493f0521.png)
