### ISSUE TITLE
Downloads are aborted

### ISSUE THREAD

**Issue by KojoteGit** [nextcloud/server#10893]
Downloads of directory as zip file are aborted. Also bigger files (>200MB) are not able to sync with nextcloud. The transfer is interrupted after 120s of download.
 
### Steps to reproduce
1. Put several files in a directory (Size should be around 200 - 400 MB)
2. Start the download of directory as zip archive in the web client
OR
1. Upload of bigger files (around 200 - 400MB)

### Expected behaviour
Download should not be interrupted after 120s.

### Actual behaviour
Downloads are cancelled after 120s. The zip file is corrupted.

### Server configuration

**Operating system**:
shared webhosting. I assume Linux.

**Web server:**
Apache

**Database:**
mysql 10.0.34

**PHP version:**
7.2.8 (issue occurs on older version too)

**Nextcloud version:** (see Nextcloud admin page)
13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from an older version of nextcloud (installed spring 2017) and it occurs on a fresh installed version of 13.0.5

**Where did you install Nextcloud from:**
Softaculous Skript installer provided by my webspace provider

**Signing status:**
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.mydomain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/www.mydomain.tld\/cloudtest",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome, Internet Explorer, Syncclient

**Operating system:**
Windows 7 and Windows 10

#### Web server error log
No entries found...

#### Nextcloud log (data/nextcloud.log)
No entries...

#### Browser log
n/a

In the first instance I found two error messages. 

**Message 1;**
[27-Aug-2018 09:28:01 Europe/Berlin] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /mydirectory/nextcloud/lib/private/Files/Filesystem.php:796
Stack trace:
#0 /mydirectory/nextcloud/lib/private/Files/View.php(2055): OC\Files\Filesystem::normalizePath('/kai/uploads/we...')
#1 /mydirectory/nextcloud/lib/private/Files/View.php(1182): OC\Files\View->unlockFile('/web-file-uploa...', 1)
#2 [internal function]: OC\Files\View->OC\Files\{closure}()
#3 /mydirectory/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))
#4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()
#5 {main}
  thrown in /mydirectory/nextcloud/lib/private/Files/Filesystem.php on line 796

**Message 2:**
[27-Aug-2018 10:35:19 Europe/Berlin] PHP Fatal error:  Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /mydirectory/nextcloud/lib/private/Files/Filesystem.php:796
Stack trace:
#0 /mydirectory/nextcloud/lib/private/Files/View.php(2055): OC\Files\Filesystem::normalizePath('/kai/files/Dias...')
#1 /mydirectory/nextcloud/lib/private/Files/View.php(1182): OC\Files\View->unlockFile('/Dias_Scan/PICT...', 1)
#2 [internal function]: OC\Files\View->OC\Files\{closure}()
#3 /mydirectory/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure))
#4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close()
#5 {main}
  thrown in /mydirectory/nextcloud/lib/private/Files/Filesystem.php on line 796

Message 1 was thrown when I tried to upload a bigger file. The file is not displayed in the target directory. A directory with splitted temp files is located in the upload directory.

Message 2 occurred during download a directory as zip file. The download was interrupted after 120 seconds.

## Further information ##
All timeouts are defined bigger than 120 sec. My hosting provider is allowing an execution time of 240s.
Instead of php-fpm lsphp (lsapi) is used according to my provider.

**Comment by juliushaertl** [comment]
> Downloads are cancelled after 120s. The zip file is corrupted.

If it is always 120s it could be a timeout somehwere in your server stack. Mind to check the timeouts of your webserver?
