### ISSUE TITLE
Deprecated php warning

### ISSUE THREAD

**Issue by xf-** [nextcloud/server#10894]
### Steps to reproduce
1. Use nextcloud

### Expected behaviour
No Warning/log entry

### Actual behaviour
Log entry on every page

### Server configuration

**Operating system**: Debian stretch

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.3.0 Beta2

**Nextcloud version:** (see Nextcloud admin page) 14 RC 1

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated at 
```
</details>

-----

**PS: PHP 7.3 works really well & fast!**

**Comment by patschi** [comment]
I was able to see same behavior with 14 RC2 as well. Apparently both flags `FILTER_FLAG_SCHEME_REQUIRED` and `FILTER_FLAG_HOST_REQUIRED` are now deprecated starting with PHP 7.3 and are implied in `FILTER_VALIDATE_URL` anyway. So it should be save just removing the flags from `filter_var()` calls.

Some resources to check:
* https://github.com/php/php-src/commit/79a27ccf3f62e25f3ce5254dbce4cd631fb4e735
* https://wiki.php.net/rfc/deprecations_php_7_3#filter_flag_scheme_required_and_filter_flag_host_required
* http://php.net/manual/en/filter.filters.validate.php
