### ISSUE TITLE
Custom config.php content in fpm chroot gets removed by nc

### ISSUE THREAD

**Issue by k4ffee** [nextcloud/server#10904]
Hello there :), as suggest in the forums: https://help.nextcloud.com/t/custom-config-php-content-in-fpm-chroot-gets-removed-by-nc/34767

as described in the title, if 've a problem with my setup. Background:
Running NC via nginx & php-fpm using the php-fpm chroot option. Everythings works fine so far (eg. Webcron) except using operating system cron.
Because of the fpm chroot settings, php-fpm needs other path settings in config.php eg.
```
'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/chroot-data/public/apps',
      'url' => '/apps',
      'writable' => true,
    ),
  ),
  'datadirectory' =>'/chroot-data/nextcloud_data',
```
Works fine. But running (as nextcoud user)

    php -f /srv/users/nextcloud/chroot/chroot-data/public/cron.php

will fail, because of the different filesystem structure seen by php-cli.
One solution often found on the web is to prepend the data & apps directory option with something like this:
   
    ((php_sapi_name() != 'cli') ? '' : '/srv/users/nextcloud/chroot')

(or setting something like $CUSTOM_ROOT = ... at the top of the config file for more readability)

Sadly this seems to be cleaned out by nc sanitize operations and the only way I see to stop that, is to set 
   
    'config_is_read_only' => true,

but this also stops the Updater from working (need to change config.php manually).

So, long story short, is there any other way (like  'overwrite.cli.url' => )to respect the nc paths in a chrooted environment ?

Thanks in advance :slight_smile:
Michael

### Steps to reproduce
1. Install Nextcloud
2. Put custom code in config.php, like 
``` 'datadirectory' => ((php_sapi_name() != 'cli') ? '' : '/srv/users/nextcloud/chroot') . '/data'```
3. Wait for cronjob

### Expected behaviour
Your manual changes stays untouched

### Actual behaviour
Your manual changes gets cleaned out

### Server configuration

**Operating system**: Gentoo Linux

**Web server:** nginx 1.14.0

**Database:** mysql  Ver 15.1 Distrib 10.1.31-MariaDB, for Linux (x86_64) using readline 7.0

**PHP version:** PHP 7.1.18

**Nextcloud version:** 13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** from 12.x

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
php occ app:list
fails because of chroot
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
php occ config:list system
fails because of chroot
```
</details>

**Are you using external storage, if yes which one:** -

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** -

#### Cron error log
<details>
<summary>Cron error log</summary>

```
Aug 28 17:15:01 localhost CROND[29776]: (domain) CMDOUT (App directory "/data/public/apps" not found! Please put the Nextcloud apps folder in the Nextcloud folder or the folder above. You can also configure the location in the config.php file.)
```
</details>

**Comment by m-behr** [comment]
Today NC told me that the last cronjob ran 15 days ago, ... so the above issue seems to occur even if you add the ` 'config_is_read_only' => true,` line in config.php

So, the only workaround I see at the moment is to remove write permission from config.php ...

**Comment by blizzz** [comment]
place the condition in config/custom.config.php (create it), this should not be overwritten iirc.

**Comment by k4ffee** [comment]
Works. Thank you!
