### ISSUE TITLE
Group dropdown should be closed after a group was (de)selected

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#10907]
1. Group 1 and 2 exist
2. User 1 and 2 are members of Group 1
3. Add User 1 to Group 2 and remove them from group 1
4. Dropdown is still open and shows the group opens of User2

That is very confusing, if you didnt notice that in the background User1 vanished and you might by accident move another (wrong) person from one group to another.

cc @skjnldsv

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
