### ISSUE TITLE
jQuery UI tabs should match the Nextcloud tab style

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#1090]
follow up of #830 

At the moment jQuery UI styles don't match the clean Nextcloud look:
![](https://cloud.githubusercontent.com/assets/2184312/17558773/090041ac-5f1c-11e6-971d-cfa86434b9fc.png)

> actually the color should be removed from jQuery UI. The tabs should be styled like the tabs in the right Files details sidebar instead.

![2016-08-26-160617_290x134_scrot](https://cloud.githubusercontent.com/assets/3404133/18008091/10655bfc-6ba7-11e6-98a7-6cb25969bd23.png)

cc @nextcloud/designers @jancborchardt

**Comment by mar1u5** [comment]
Good :) However: I think the best would be to drop this tabs as we have already done in `user_saml`. Same for `user_ldap` would be great but is something for another issue :wink:

**Comment by jancborchardt** [comment]
@blizzz do you think it’s a good idea to drop the tabs altogether? With the now split admin settings it might be good to use the tabs as h2 elements instead to structure the page.

**Comment by raghunayyar** [comment]
@jancborchardt @blizzz we can use the tabs we once had in the files sidebar here? They happen to be a quick fix and afaik dont rely on jQuery UI.

**Comment by blizzz** [comment]
@jancborchardt it would still need a guided concept. The main idea was to make it easy to configure and do not overwhelm the admin with stuff. So, just placing everything below each other would not suffice, it would still require some logic. Also, Advanced and Expert tabs have a lot of cargo, i.e. also needs extra treatment.


An idea that just comes to my head is to place the wizardy tabs (Server, User, Login, Groups) below each other. On new configurations (and those without valid host and credentials) only the Server part is visible or active. Once this is configured and/or valid other parts are shown. Advanced and Expert settings would stay as tabs, only the appearance change. Tedious work altogether, though, and there are better places to spend efforts.

I'd appreciate just changing the style to follow tabs as in the files sidebar.

**Comment by MorrisJobke** [comment]
Fixed in #771

**Comment by MorrisJobke** [comment]
Regression in #6178

**Comment by MorrisJobke** [comment]
Fixed in #6341
