### ISSUE TITLE
Wrong styles of "Add a new user" button

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#10917]
### Steps to reproduce
1. Go to Users
2. Click on "New user" button in the left menu

Wrong size or/and horizontal alignment
### Server configuration
**Nextcloud version:** 14.0.0 RC1

### Client configuration
**Browser:** 61.0.2 (64-bit)

**Operating system:** Debian Stretch

### Screenshots
![button](https://user-images.githubusercontent.com/9205230/44775123-87a80f80-ab7d-11e8-8e74-29a74a2e1eb0.PNG)

**Comment by MorrisJobke** [comment]
@jancborchardt @skjnldsv I guess this is the wanted style, right?

**Comment by jancborchardt** [comment]
@R0maNNN what are you exactly referring to? The blue checkmark button?

**Comment by skjnldsv** [comment]
@MorrisJobke yes this looks as intended :)

**Comment by MorrisJobke** [comment]
Fixed in #11523
