### ISSUE TITLE
Nextcloud does not respect Apache 2's mod_ratelimit

### ISSUE THREAD

**Issue by kaysond** [nextcloud/server#10928]
I'm trying to use [mod_ratelimit][1] to enable bandwidth limiting on my entire apache server.

I'm using the following lines in my conf files:

    SetOutputFilter RATE_LIMIT
    SetEnv rate-limit 1024
    SetEnv rate-initial-burst 1024

I've added the lines to the nextcloud root folder `<Directory /var/www/nextcloud>`, to the data folder `<Directory /var/www/files/Nextcloud>` and to the `<VirtualHost>` that contains my subdomain `nextcloud.domain.com`. None of these things seem to work. I'm not sure how the file downloading works, but somehow it's causing Apache to ignore these rate limits. I didn't see anything in the `.htaccess` that would override this or cause it not to work... The only thing is the rewrite rules but as far as I know that shouldn't make a difference.

  [1]: https://httpd.apache.org/docs/2.4/mod/mod_ratelimit.html

**Comment by MorrisJobke** [comment]
I'm not aware of anything that would intercept this and work around such limits. On the other side we also don't actively check for such limits, but maybe someone in the forums has more knowledge about this specific module and could help you: https://help.nextcloud.com

If you find anything where the Nextcloud code misbehaves we can check how to change this in the code. Thus I will close this for now. I hope that is okay for you.

**Comment by kaysond** [comment]
According to the Apache maintainers, the mod was "broken", so I'll have to try the latest version and report back.
