### ISSUE TITLE
Permission checker issues wrong path

### ISSUE THREAD

**Issue by danimo** [nextcloud/server#10930]
### Steps to reproduce
1. chown away an directory from `www-data` (e.g. bookmarks)
2. upgrade to NC 14 RC1
3. Check Security & setup warnings

### Expected behaviour

A warning about `/var/www/nextcloud/apps/bookmarks` having wrong permissions.

### Actual behaviour

A warning about `/var/www/nextcloud/apps/bookmarks/bookmarks` having wrong permissions.
(Note the extra dir component)

### Server configuration

**Operating system**: Debian 9 (stretch)

**Web server:** Apache 2.4.25

**Database:** mariadb 10.1

**PHP version:** PHP 7.1.17-1+0~20180505045738.17+stretch~1.gbpde69c6

**Nextcloud version:** 14.0.0 RC 1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade

**Where did you install Nextcloud from:** Updater

**Signing status:**
<details>
<summary>Signing status</summary>
Some app directories are owned by a different user than the web server one. This may be the case if apps have been installed manually. Check the permissions of the following app directories:
/var/www/nextcloud/apps/bookmarks/bookmarks
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**Comment by danimo** [comment]
@nextcloud-bot is wrong

**Comment by MorrisJobke** [comment]
@danimo Thanks for spotting it :)
