### ISSUE TITLE
Util::addStyle pulls css files from nextcloud root

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#10935]
1. Install app normally into the apps folder
2. Copy the same app to nextcloud-root, on the same level as the core
3. Update scripts and or styles of the first copy in the apps folder
4. Reload site

What should happen now:
 - New stlyes are served to clients

What actually happens:
 - Old stlyes from the wrong root-copy of the app are served

**Comment by newhinton** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
Maybe not an issue at all, since the folder is not considered to be there, but let's at least have a look why this happens.

**Comment by MorrisJobke** [comment]
> 2\. Copy the same app to nextcloud-root, on the same level as the core

Just don't do this 😉 

I would close this as this is clearly nothing that we should consider. It's simply unsupported to place a app folder there.
