### ISSUE TITLE
Comments dav requests ignore file id

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#10934]
1. open a file sidebar
2. add a comment
3. open another file sidebar
4. see the comment from the previous file appear on this file as well
5. see the network requests use the second file id and the first comment id still returning a proper response

@rullzer @MorrisJobke @danxuliu

**Comment by RuudschMaHinda** [comment]
The same bug appears with tags, group associations of apps, shared, versions (will try the meta app, to see if it is also affected - depending on what happens this might give further clues)
I have people that use the side panel for a reason, it is generally very good. This bug makes it basically unusable without reloading the entire page.

**Comment by RuudschMaHinda** [comment]
I just observed something interesting:
The Problem with the group-checkmark in the app store is not affected in a completely new installation of NC 14.0.3
When selecting the details for different files it still has some issues, but not as bad as showing only the activities of previous selected files, but showing the current activities AND the previous activities.

That is on a completely fresh install of NC 14.0.3 - I don't have that luxury with the other install though.
