### ISSUE TITLE
Design session

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#10931]
## Settings

- align style of settings
  - check boxes (also in general
  - input boxes
  - tables
  - hints
  - help links
  - link clickability (see also other section)
  - grouping/aligning them
  - as of now only sections and their headers are standardized

## Clickability

- checkboxes at 44px height

## Upload

- progress bar, plus button replacement
- inline upload

## Share links

- setting permissions before creating

## Public sharing page

- long filename overflow
- image previews on mobile
- also add grid view
- show comments in sidebar
- respect personal settings visiblity for display name on public pages

## Work together with mobile/desktop apps

- issue that design is not unified across platforms
- desktop/mobile apps label for issues
- add this to the documentation/manual

## Accessibility

- lighthouse/aXe integration into CI
- make sure we keep the new accessibility stuff working

## Infinite scrolling

- save scroll position

## Unified search

- global search across apps
- integration with fulltextsearch

@nextcloud/designers Could one of you split this into separate tickets? Because I'm basically fully booked until I go on vacation.

**Comment by MorrisJobke** [comment]
I removed all the elements that got their own tickets (see history for details).

**Comment by MorrisJobke** [comment]
How to move this forward?

**Comment by skjnldsv** [comment]
Unified search is already on its own ticker #9917

**Comment by MorrisJobke** [comment]
Moved to 17 for now
