### ISSUE TITLE
Nextcloud customiztion

### ISSUE THREAD

**Issue by Sanjeebtiwari** [nextcloud/server#10941]
I would like to provide Nextcloud access from Internet for my Organization's users. But I would like to do some customization. Can any one guide me that those customization are possible or not.  These customization are given below.

- I would like configure Nextcloud Server such that after successful login of the User, the user's data will be fetched from the database to the Proxy server(e.g. IMAP client) and that data will be visible to the successful user from webInterface which has been copied on proxy server.
### **NextCloud<-->Proxy Server<-->Database**
Edit1: When the user will login from Nextcloud Web Interface then only the user's data should be available on either NextCloud Server or proxy server not other user's data should be available on those server. In the case of IMAP client(e.g. Roundcube ) the data of particular user is copied on IMAP client. What IMAP client does similar feature I want on the Proxy Server or Nextcloud server )

- Is it possible to provide File level security like Extended ACLs of files on linux in Nextcloud.

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
