### ISSUE TITLE
Button to create a new group.

### ISSUE THREAD

**Issue by TomTurnschuh** [nextcloud/server#10945]
It might be a duplicate or is addressed already, but anyway...

In NC 14.0.0 RC1 I have a button saying `New user` in the users panel.
Maybe it would make sense to add a `New group` button?

**Comment by rollanders** [comment]
I am unable to create new groups. There is no button for that in the add new user page.

**Comment by TomTurnschuh** [comment]
#11182

**Comment by skjnldsv** [comment]
Duplicate of #11182
