### ISSUE TITLE
Dark Theme - Text unreadable

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/server#10946]
### Steps to reproduce
1. Install NC14-Beta
2. Under Settings > Accessibility, Select the Dark Theme
3. Navigate to the Monitoring page

### Expected behaviour
One would like to read the numbers at the graph

### Actual behaviour
Text is in black, so is theme, so text is not readable

### Server configuration

**Operating system**:
CentOS Linux release 7.5.1804 
**Web server:**
httpd-2.4.6-80.el7.centos.1.x86_64
**Database:**
mariadb-server-5.5.60-1.el7_5.x86_64
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14-Beta
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Source tar ball
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Most likely an issue with the serverinfo app: https://github.com/nextcloud/serverinfo/issues

cc @skjnldsv

**Comment by hanserasmus** [comment]
Should I leave this here? Or close and re-open there?

**Comment by MorrisJobke** [comment]
> Should I leave this here? Or close and re-open there?

Let @skjnldsv decide this ;)
