### ISSUE TITLE
 An exception occurred while executing 'SELECT * FROM "oc_spreedme_rooms"' during migration

### ISSUE THREAD

**Issue by svenerbe** [nextcloud/server#10948]
I try to migrate my nextcloud db from sqllite to mysql. Nextcloud 13.0.6

php70 /volume1/web/nextcloud/occ db:convert-type --all-apps --port="3307" mysql $USER 127.0.0.1 nextclouddb

What is the database password?
Creating schema in new database

  [Doctrine\DBAL\Exception\TableNotFoundException]
  An exception occurred while executing 'SELECT * FROM "oc_spreedme_rooms"':
  SQLSTATE[HY000]: General error: 1 no such table: oc_spreedme_rooms

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[HY000]: General error: 1 no such table: oc_spreedme_rooms

  [PDOException]
  SQLSTATE[HY000]: General error: 1 no such table: oc_spreedme_rooms

but when i use mysql, all is working fine.

./mysql -u $USER -p nextclouddb
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 6036
Server version: 10.0.34-MariaDB Source distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [nextclouddb]>
MariaDB [nextclouddb]> SELECT * FROM oc_spreedme_rooms;
Empty set (0.01 sec)

MariaDB [nextclouddb]> quit

**Comment by MorrisJobke** [comment]
This is an issue within the spreedme app. Thus please report it to the maintainer of that app in its repository: https://github.com/strukturag/nextcloud-spreedme

Keep in mind that this app is discontinued in order to provide a better working solution with the talk app: https://github.com/nextcloud/spreed
