### ISSUE TITLE
Carddav  error shows first alphabetically user

### ISSUE THREAD

**Issue by ntinti** [nextcloud/server#10940]
### Steps to reproduce
1. Create User "AA_Dummy" or have a look who is on top in alphabetic order  
2. Open Carddav ressource in Browser without username and addressbookname
E.G. `https://cloud.myserver.tld/remote.php/carddav/addressbooks`
3. The first Nextcloud user in the alphabet is shown in the error message :-(
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
<script/>
<s:exception>Sabre\DAV\Exception\NotFound</s:exception>
<s:message>Node with name 'AA_Dummy' could not be found</s:message>
</d:error>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">...</d:error>
```

**Comment by MorrisJobke** [comment]
> But calling this URL you can provoke to show anybody on the internet the first username created on the server. I think it is a **security issue**.

This URL is protected by authentication. If you open it in a browser window it is likely that you are logged in into your Nextcloud and thus it shows the error message. If you open this in a private browser session it will show the authentication prompt.

Thus I will close this issue as it works as it should.
