### ISSUE TITLE
14 RC2: problems with logo and favicon

### ISSUE THREAD

**Issue by stephanedupont** [nextcloud/server#10957]
Hello,

Since 14 RC2, my custom uploaded logo, login image and favicon are not appearing.

To be sure, I reset everything in the theming app settings and uploaded logo, login image and favicon again.

- The logo is not appearing in the top-left of the page
- The login image is not appearing on the login page
- The favicon is correct only when I'm on the theming app page, on all other pages, the Nextcloud icon is displayed instead.

I've got the exact same configuration on a 13.0.5 server and it works perfectly.

Are others having the same problem? What can I do to help?

Best,
Stéphane.

**Operating system**: Debian Jessie

**Web server:** Apache2

**Database:** Mysql

**PHP version:** 7.0.31-1~dotdeb+8.1

**Nextcloud version:** 14 RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** from 14 RC1

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - sharerenamer: 2.1.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - files_pdfviewer
  - user_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.eluna.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.eluna.org",
        "dbtype": "mysql",
        "version": "14.0.0.18",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Tested on Chrome and Firefox.

**Operating system:** Windows 10 64

**Comment by MarcMichalsky** [comment]
I have the same problem.

**Comment by weeman1337** [comment]
I can confirm a custom logo doesn't appear. Will have a look at this!

**Comment by weeman1337** [comment]
@stephanedupont do you expect the favicon to be the same as the logo or did you upload a custom one here:
![image](https://user-images.githubusercontent.com/6216686/44955307-69aa1a00-aeb1-11e8-9ddc-4b4b0c2f728c.png)

For me the favicon is working so far...

**Comment by stephanedupont** [comment]
@weeman1337 Tried both. Did not expect the favicon to be the same, but even when uploading a custom favicon, it works only when in the Theming page, as soon as I leave it disappear.

**Comment by stephanedupont** [comment]
@weeman1337 if you have trouble reproducing this and you want me to provide you an access to my instance, please email me at stephane.dupont.be@gmail.com

**Comment by stephanedupont** [comment]
@weeman1337 The favicon is not working even if it's a PNG file (and imagemagick is installed on my instance)

**Comment by weeman1337** [comment]
@stephanedupont there is another change in that should solve this, too. Please check after the next release.
