### ISSUE TITLE
Settings view shows upgrade that matches existing version (14 rc2)

### ISSUE THREAD

**Issue by vwbusguy** [nextcloud/server#10953]
### Steps to reproduce
1. Upgrade to version 14rc2 from 14rc1 (via "Beta" channel)
2. Open Settings->Administration->Overview
3. Observe current version is "14.0.0 RC2" and an update is available for "14.0.0 RC2" (See screenshot in next comment)

### Expected behaviour
Nextcloud should report that install is at latest version for channel when installed version matches latest in channel.

### Actual behaviour
Nextcloud offers an upgrade for version install is already on.

### Server configuration

**Operating system**: Fedora 28

**Web server:** Apache 2.4.24

**Database:** MariaDB 10.2.16

**PHP version:** 7.2.9

**Nextcloud version:** 14.0.0 RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14.0.0 RC1

**Where did you install Nextcloud from:** Initially from tarball from Nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <apps>
   <element>federation</element>
   <element>user_ldap</element>
   <element>systemtags</element>
   <element>files_texteditor</element>
   <element>files_pdfviewer</element>
   <element>serverinfo</element>
   <element>survey_client</element>
   <element>accessibility</element>
   <element>theming</element>
   <element>user_external</element>
   <element>gallery</element>
   <element>files_trashbin</element>
   <element>files_videoplayer</element>
   <element>admin_audit</element>
   <element>support</element>
   <element>files_sharing</element>
   <element>password_policy</element>
   <element>comments</element>
   <element>sharebymail</element>
   <element>files_external</element>
   <element>nextcloud_announcements</element>
   <element>updatenotification</element>
   <element>files_versions</element>
   <element>logreader</element>
   <element>encryption</element>
   <element>notifications</element>
   <element>firstrunwizard</element>
   <element>activity</element>
   <element>files_markdown</element>
   <element>passman</element>
   <element>bruteforcesettings</element>
   <element>calendar</element>
   <element>external</element>
   <element>deck</element>
   <element>ocsms</element>
   <element>contacts</element>
   <element>socialsharing_facebook</element>
   <element>notes</element>
   <element>tasks</element>
   <element>richdocuments</element>
   <element>files_automatedtagging</element>
   <element>files_downloadactivity</element>
   <element>spreed</element>
   <element>socialsharing_twitter</element>
   <element>bookmarks</element>
   <element>socialsharing_email</element>
   <element>audioplayer</element>
  </apps>
 </data>
</ocs>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 61.0.2

**Operating system:** Fedora 28

**Comment by vwbusguy** [comment]
![screenshot from 2018-08-31 11-27-21](https://user-images.githubusercontent.com/5474941/44930178-501e9c00-ad12-11e8-8783-2ccfda288a34.png)

**Comment by vwbusguy** [comment]
Interestingly, I kept checking back while I was trying to figure out why and it eventually went away after about an hour:
![screenshot from 2018-08-31 12-26-28](https://user-images.githubusercontent.com/5474941/44932156-21f08a80-ad19-11e8-928e-a1737f335994.png)

**Comment by MorrisJobke** [comment]
> I have seen this as well in the NC 14.0.0 RC 1 release. I also got a notification that a new version is available, this is very confusing since I thought to have upgraded just before.

That is weird - usually I can only explain this, that the internal version number has updated, but the readable version was the same.

This is then only a config issue on the updater_server and not in the server I will close this for now. Thanks for the feedback anyways. 👍
