### ISSUE TITLE
home storage not writable

### ISSUE THREAD

**Issue by uglymagoo** [nextcloud/server#1095]
There is a nasty bug in OC 9.1.0 that also affects NC 10: https://github.com/owncloud/core/issues/25755

It was fixed with this commit: https://github.com/owncloud/core/commit/6f4ba321613ddf406fa0fcbb1228e89ca35e8425.patch

I was affected by this bug when I upgraded OC 9.0.x to NC 10 today and just found the above solution.

In a nutshell: some of my users were greeted with "you don't have permission to upload or create files here" in their home folder. These users had files shared with them. Removing these shares resolved the issue. I applied the above patch manually to NC 10 and it also fixed the issue.

**Comment by rullzer** [comment]
CC: @icewind1991
