### ISSUE TITLE
OCC upgrade throws unhandled exception

### ISSUE THREAD

**Issue by YoMamasNerd** [nextcloud/server#10954]
### Steps to reproduce
1. `sudo -u www-data ./occ upgrade`

### Expected behaviour
Updating from RC1 to RC2

### Actual behaviour
An unhandled exception has been thrown

### Server configuration

**Operating system**: Linux 4.4.0-042stab131.1 (Ubuntu)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 14.0.0 RC 1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** official Website

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.3.0
  - apporder: 0.5.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - camerarawpreviews: 0.5.6
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - data_request: 1.1.0
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_downloadactivity: 1.3.0
  - files_external: 1.5.0
  - files_external_gdrive: 0.2.8
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - metadata: 0.7.0
  - mindmaps: 0.1.0
  - news: 12.0.4
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.1
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - sociallogin: 1.10.0
  - spreed: 3.99.12
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - unsplash: 1.1.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - user_usage_report: 1.1.0
  - workflowengine: 1.4.0
Disabled:
  - checksum
  - circles
  - drawio
  - encryption
  - tasks
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "85.214.153.91",
            "cloud.tradena.me"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "overwrite.cli.url": "http:\/\/85.214.153.91",
        "dbtype": "mysql",
        "version": "14.0.0.17",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "beta",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no (but it's enabled)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

`
An unhandled exception has been thrown:
Error: Call to undefined method GuzzleHttp\Client::request() in /var/www/html/lib/
rivate/Http/Client/Client.php:161
Stack trace:
#0 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client
Client->get('https://apps.ne...', Array)
#1 /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppSt
re\Fetcher\Fetcher->fetch('', '')
#2 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStor
\Fetcher\AppFetcher->fetch('', '')
#3 /var/www/html/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->
et()
#4 /var/www/html/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('ac
ivity')
#5 /var/www/html/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Arr
y)
#6 /var/www/html/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.0.18',
14.0.0.17')
#7 /var/www/html/core/Command/Upgrade.php(262): OC\Updater->upgrade()
#8 /var/www/html/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Comman
\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfon
\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(946): Symfony\Component\
onsole\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Obj
ct(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(248): Symfony\Component
Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\
omponent\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\Console
utput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component
Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Obje
t(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Cons
le\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symf
ny\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/console.php(96): OC\Console\Application->run()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')
`

**Comment by timm2k** [comment]
Disable and may remove app ```files_external_gdrive```. It ships an outdated Version of Guzzle.

You can try to update files_external_gdrive's Guzzle on your own like someone else did with bookmarks app described at https://github.com/nextcloud/server/issues/10863#issuecomment-416204566.
