### ISSUE TITLE
Nextcloud 14 RC 2 Monitoring Tab View Issues

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#10951]
Display issues on monitoring tab
![image](https://user-images.githubusercontent.com/24574019/44922721-bce26800-ad0b-11e8-9337-36c7e12169aa.png)

**Comment by andyxh** [comment]
This makes sense now! Well hopefully we get it fixed :)

**Comment by danielkesselberg** [comment]
Duplicate #10950
