### ISSUE TITLE
Creating an app password is not logged in activity stream NC 13.0.6

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/server#10964]
### Steps to reproduce
1. Use 13.0.0 or 13.0.6
2. Create an app password
3. check your activity stream

### Expected behaviour

Important security events like password changes and  2fa backup codes should always be listed in the activity stream and they mostly are. This includes the creation of app passwords. Same goes for revoking passwords.

### Actual behaviour
There is no event for the creation or revocation  of an app password. 

### Server configuration

**Operating system**:
CentOS release 6.10 (Final)

**Web server:**

Apache 

**Database:**

mysql 

**PHP version:**

```
PHP 5.6.37 (cli) (built: Jul 20 2018 17:51:30) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies

```
**Nextcloud version:** (see Nextcloud admin page)
13.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.0 and many previous versions
**Where did you install Nextcloud from:**
official manual install package
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**Are you using encryption:** no

**Comment by MorrisJobke** [comment]
cc @nickvergessen @ChristophWurst
