### ISSUE TITLE
Non-static method OC\Installer::isUpdateAvailable() should not be called statically

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#10966]
1. Set in config.php: 'has_internet_connection' => false, 
2. Go to "Overview" tab
3. Check log

Nextcloud 14 RC 2

![image](https://user-images.githubusercontent.com/9205230/44956691-a6393e00-aed0-11e8-83b3-502cf6dce935.png)

**Comment by danielkesselberg** [comment]
Thank for reporting :+1: There is already a report for isUpdateAvailable here #10950. Is "Using $this when not in object context" gone when you disable serverinfo app?

**Comment by R0maNNN** [comment]
@danielkesselberg, there are no errors if I disable serverinfo app, thx
