### ISSUE TITLE
New "Create your free account.." message (Only Feedback)

### ISSUE THREAD

**Issue by ryan77627** [nextcloud/server#10965]
### Steps to reproduce
1. Share a file using a link and no password
2. Sign out of Nextcloud and go to the file share you created
3. At bottom there is a message: "Get your free account"

### Expected behaviour (No actual behaviour this is only feedback)
I would like an option to disable this message since I don't want people who come onto my file share to think I offer free hosting, then redirect to your page. I don't want the emails saying they can't login to their share if they try to login on my page.

### Server configuration

**Operating system**: Ubuntu 17.10

**Web server:** Apache 2.4.33

**Database:** MYSQL

**PHP version:** 7.1

**Nextcloud version:** 14 RC2

**Comment by t0ny2** [comment]
You can add the line:
`'simpleSignUpLink.shown' => false,`
to your Nextcloud config.php file to disable the signup link.

**Comment by violoncelloch** [comment]
maybe a better way than just letting people deactivating this, the nextcloud.com/signup site could provide information about the possibility of selfhosting and a disclaimer that the share you are coming from has nothing to do with this signup-possibilities? (and explain in general the idea of federation and different hosts?)

**Comment by ryan77627** [comment]
In my opinion, I think that the signup site having all that info would indeed convince less people to turn it off, however I do like having the option. Closed since config option worked. Thanks t0ny2!
