### ISSUE TITLE
Session view - last session must not be in the future

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#1096]
### Steps to reproduce
1. Login
2. Go to personal page

### Actual behaviour
![screenshot44](https://cloud.githubusercontent.com/assets/8111200/18023071/028bc43c-6bf5-11e6-9344-763878a9e867.PNG)

Last activity in the future!

### Expected behaviour
Last activity should not happen in the future.

### Server configuration
**Nextcloud version:** 10

**Comment by rullzer** [comment]
This sounds very much like your system clocks are out of sync. Please run an NTP client on both.

**Comment by tflidd** [comment]
Ok, on my linux system I don't see this problem (is synced via NTP). I have to check the OS X system, but when it's behind a firewall I probably can't reach ntp servers. Not sure about the precision of hardware clocks but a few seconds offset are possible.

Can't you use the server time to do the calculations? Or client?

**Comment by rullzer** [comment]
Well the thing is you will run into nasty bugs with for example the sync client if timestamps differ.

We basically require properly configured clocks.

**Comment by tflidd** [comment]
I checked the OS X client again, it was running 7s ahead.

The environment I was working in has a restricted internet access, so only http and https is allowed. Probably the OS X couldn't sync because it is enabled by default. I just reconnected OS X on my home network and it fixed the time delay.

I haven't seen any problems on the sync client but I haven't synced shared folders where concurrent writes are possible. I'm not sure how sensitive the sync process is, but it should be able to handle a few seconds of time difference to cover my use case of networks blocking ntp-traffic or clients that only sync their clocks periodically (default on Win was once a week?).

If it is very critical, we should perhaps implement some kind of protection to the sync client? Query the server time and stop syncing if the difference is larger than 10 s?

**Comment by rullzer** [comment]
well the thing is if we start hiding stuff like this is becomes arbitraity again. Like what is the max we allow? 10seconds? but then what if it is 11 seconds. It will look weird then.

My point being that any solution we implement either hides the problem always. Or will still look weird in certain situations.

**Comment by tflidd** [comment]
> well the thing is if we start hiding stuff like this is becomes arbitraity again. Like what is the max we allow? 10seconds? but then what if it is 11 seconds. It will look weird then.
> 
> My point being that any solution we implement either hides the problem always. Or will still look weird in certain situations.

True for the session length, that is only a cosmetic problem.

However, how much delay is possible before the client runs into serious bugs? What happens if there is a 5 min difference? Shouldn't the client stop syncing at some point and/or show a warning?

It should be long enough to cover common network delays and that you can set the time manually within this precision.

**Comment by rullzer** [comment]
The client theme is actively working on stuff like that.I might have worded it wrong. But lets assume x people share a big folder and edit it. If all have very skewed clocks things are bound to get nasty at some point ;)

**Comment by nickvergessen** [comment]
Closing as per above
