### ISSUE TITLE
There is no "share" button in list view mode

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#10972]
NC 14 RC 2

Go to any file folder.

Enable tile view. See "share" button.
![image](https://user-images.githubusercontent.com/9205230/44961843-8467a780-af20-11e8-8ec9-87774595ea86.png)

Enable list view. 
![image](https://user-images.githubusercontent.com/9205230/44961838-67cb6f80-af20-11e8-92f5-312e68b1ebd7.png)

BTW the second screenshot shows that there are a lot of free space in bar, but folder hierarchy is compressed. It's a bug too.

**Comment by R0maNNN** [comment]
ouch, it's right near last folder name...

**Comment by MorrisJobke** [comment]
> Enable tile view. See "share" button.

This is a feature of gallery app it is not in the same way implemented in the files list. Nevertheless we merge both views into the files app and then the headers will be the same. #6 

Thus closing this.

**Comment by R0maNNN** [comment]
@MorrisJobke, #6 closed, will this change be implemented?

**Comment by MorrisJobke** [comment]
> @MorrisJobke, #6 closed, will this change be implemented?

The share option is right next to the folder name. ;)
