### ISSUE TITLE
Endless loading animation on element in hierarchy chain (gallery)

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#10971]
NC 14 RC 2

1. Go to gallery, 2-level of hierarchy folder.
2. Click on last word in the chain.
3. See endless loading animation

 For example:
![image](https://user-images.githubusercontent.com/9205230/44961735-b24bec80-af1e-11e8-95f8-3aa757838abd.png)

Click on "Private"
![image](https://user-images.githubusercontent.com/9205230/44961756-fb9c3c00-af1e-11e8-8579-c87957086e65.png)

**Comment by MorrisJobke** [comment]
This is an issue within the gallery app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/gallery

Anyways we want to merge those two with #6 so this is likely to be "solved" by moving the grid view over to the files app where this problem does not exist.

**Comment by R0maNNN** [comment]
@MorrisJobke yes, it works fine in NC 15.0.5, hierarchy chain in files app doesn't have the problem.

But the Gallery app still buggy
https://github.com/nextcloud/gallery/issues/505
