### ISSUE TITLE
Microsoft office online integration

### ISSUE THREAD

**Issue by aqwsez** [nextcloud/server#1100]
Would it be possible to integrate with the microsoft office online apps?
Here is a link with some extra information (http://dev.office.com/programs/officecloudstorage).

**Comment by LukasReschke** [comment]
This is not planned at the moment and likely won't be. Instead please take a look at nextcloud.com/collaboraonline/

**Comment by IwishIcanFLighT** [comment]
Hi, ownCloud recently added [Microsoft Office Online integration in their 10.1 release.](https://owncloud.org/news/owncloud-server-10-1-release-a-big-step-forward-in-digital-collaboration/)

@LukasReschke  While I completely understand that ownCloud and Nextcloud have their own respective development paths, could this previous decision be reconsidered?

We try to use Onlyoffice as much as we can but it doesn't fit our needs and we often have to go back to Google Drive that we wanted to avoid in the first place by switching to Nexctcloud.

Thanks
