### ISSUE TITLE
Can’t change setting on Addional Settings

### ISSUE THREAD

**Issue by aktavor69** [nextcloud/server#1101]
Hi,

Since Nextcloud 10.0, I cant make any change on aditional setting.

For exemple, test sent mail is irresponsive, Documents apply on test button is irresponsive, ect..

When I click on the button, color change from grey to white but nothing happened

Any idea why ?

Thanks

### Steps to reproduce
1. Login in
2. Enter to Admin Panel
3. Enter to Additional Setting subcategory

### Expected behaviour

Making some change, test email, documents, ect..

### Actual behaviour

Changes arent saved. Nothing happens, irresponsive test buton or other butons

### Server configuration
**Operating system**:
Ubuntu 16.04.1

**Web server:** 
Nginx

**Database:** 
Mysql 5.7

**PHP version:** 
7.0

**Nextcloud version:** (see Nextcloud admin page)
10 Stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
Manuel update - I keep only the config.php and made an occ upgrade

**Where did you install Nextcloud from:**
Official Website

**Comment by LukasReschke** [comment]
Please provider your browser logs such as the network console as well as errors in the JS console.

**Comment by aktavor69** [comment]
@LukasReschke 

You need this ? 

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-8UwpdwiuqXJty4DoSWEA9W+FMdXW5Ol0a3ZjF7czsyo='), or a nonce ('nonce-...') is required to enable inline execution.`

`Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' 'unsafe-eval'". Either the 'unsafe-inline' keyword, a hash ('sha256-nC1EIFTfIzbc0hgADWC4Eos+jMRdIaPymHrOT/14N2s='), or a nonce ('nonce-...') is required to enable inline execution.`

`JQMIGRATE: Migrate is installed, version 1.4.0
Uncaught TypeError: Cannot read property 'register' of undefined
Failed to parse SourceMap: https://cloud.domain.ltd/core/vendor/jquery/dist/jquery.min.map`

**Comment by fa-ribeiro** [comment]
same here: when trying to change Password policy settings, changes are not saved

**Comment by LukasReschke** [comment]
I can't reproduce this and the issue is missing more information. As in: the one that the issue template asks for, e.g. the browser (but not limited to this).

To debug this further I do need either those information or access to an instance where I can reproduce this myself.

**Comment by aktavor69** [comment]
@LukasReschke 

I sent you an email to statuscode mail account

**Comment by fa-ribeiro** [comment]
This is the output on the console:

    JQMIGRATE: Migrate is installed, version 1.4.0                      jquery-migrate.min.js?v=2db64d6…:2
    Uncaught TypeError: Cannot read property 'register' of undefined    move.js?v=2db64d6…:29 
    registerFileAction   @ move.js?v=2db64d6…:29
    initialize           @ move.js?v=2db64d6…:50
    (anonymous function) @ move.js?v=2db64d6…:202
    j                    @ jquery.js:3099
    fireWith             @ jquery.js:3211
    ready                @ jquery.js:3417
    I                    @ jquery.js:3433

Server is running on Debian 8, php-fpm 5.6, MariaDB 10.0.26, and nginx 1.9.10.
This started after the manual upgrade of nextcloud from 9.53 to 10.0 (remove old `nextcloud` folder, extract the new version and use the previous `config.php`).
Please let me know if you need other information.
Thanks!

**Comment by aktavor69** [comment]
I have 

nginx version: nginx/1.10.1
ubuntu 16.04.1
php-fpm 7.0
mysql 5.7.13
same as @fa-ribeiro , This started after the manual upgrade of nextcloud from 9.53 to 10.0 (remove old nextcloud folder, extract the new version and use the previous config.php).

**Comment by StopTrain** [comment]
I had a similar issue on my installation and it turned out to be an incompatible app I had enabled.  I see your current enabled app list is missing.  Can you add it to this report?

**Comment by fa-ribeiro** [comment]
```
  sudo -u www-data php /var/www/nextcloud/occ app:list
  Enabled:
    - activity: 2.3.2
    - admin_audit: 1.0.0
    - audioplayer: 1.1.0
    - calendar: 1.3.3
    - comments: 1.0.0
    - contacts: 1.3.1.0
    - dav: 1.0.0
    - documents: 0.13.1
    - federatedfilesharing: 1.0.1
    - federation: 1.0.1
    - files: 1.5.2
    - files_external: 1.0.2
    - files_mv: 0.8.2
    - files_pdfviewer: 0.8.1
    - files_reader: 0.7.2
    - files_retention: 1.0.0
    - files_sharing: 1.0.0
    - files_texteditor: 2.1
    - files_trashbin: 1.0.0
    - files_versions: 1.3.0
    - files_videoplayer: 0.9.8
    - firstrunwizard: 1.1
    - gallery: 15.0.0
    - logreader: 1.1.5
    - mail: 0.5.2
    - notifications: 0.3.0
    - ownbackup: 0.3.8
    - password_policy: 1.0.0
    - provisioning_api: 1.0.0
    - serverinfo: 1.1.1
    - survey_client: 0.1.5
    - systemtags: 1.0.2
    - tasks: 0.9.3
    - templateeditor: 0.1
    - theming: 1.0.1
    - updatenotification: 1.0.1
    - workflowengine: 1.0.1
  Disabled:
    - encryption
    - external
    - files_accesscontrol
    - files_automatedtagging
    - user_external
    - user_ldap
    - user_saml
```

**Comment by StopTrain** [comment]
Disable files_mv and I'll bet money it starts working :)

**Comment by fa-ribeiro** [comment]
You're damn right!
I just disabled `files_move` and everything is working under `Additional Settings` ! 
thank you so much!

**Comment by StopTrain** [comment]
Same exact issue I had.  Not sure who we need to report that to.  That app came from OC originally and not sure if it is still being developed.   I'll see what I can find out.  Love that app!
