### ISSUE TITLE
[Mandatory 2FA] Spec: Admin interface (settings page)

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#11017]
**Mandatory 2FA in Nextcloud 15**

Overview/progress board: https://github.com/orgs/nextcloud/projects/17

:rocket: 

---

# Specification: Admin interface

## Description

Admins should have the possibility to set two-factor authentication as mandatory for parts of the instance users.

## Details

There should be a new *Two-Factor Authentication* section in the admin security settings. A checkbox *Enforce two-factor authentication* activates the enforcement of user's 2FA.

### Limit to groups

Similar to app settings, it should be possible to enforce 2FA just for a subset of users by specifying groups users have to be member in.

### Open questions
* User back-ends that do not allow user enumeration, as in we cannot check if all users of a group have 2FA enabled or not. -> https://github.com/nextcloud/server/issues/11017#issuecomment-424458592

### To-Do
* [x] Mockups

**Comment by go2sh** [comment]
It would be nice to restrict it to certain providers only. E.g. admins need a u2f 2fa and a normal user can use htop. This could be useful for admins, because u2f is the stronger 2fa but needs a hardware device.

**Comment by rullzer** [comment]
I'd say we do baby steps. First enforcement. Then later on we can see about specific providers for groups etc.

**Comment by ChristophWurst** [comment]
> I'd say we do baby steps. First enforcement.

Do you mean a general *enforce for all users*? I'd prefer to start with the option of enabling for all but also just for specific groups.

**Comment by rullzer** [comment]
@ChristophWurst mainly not to fancy stuff like provider X for group A and provider Y or Z for groups B etc. That will be a configuration night mare.

**Comment by rullzer** [comment]
As a small suggestion for a nice to have feature. An indicator on the user page to show who has 2FA enabled

**Comment by rullzer** [comment]
> User back-ends that do not allow user enumeration, as in we cannot check if all users of a group have 2FA enabled or not.

well if the user backend doesn't support it then we are out of luck. Not much we can do to fix that.

**Comment by ChristophWurst** [comment]
Spec is done.

Implementation can be found in the following PRs
- Basic on/off: #11675 
- Group-based enforced 2FA: #11765

**Comment by ChristophWurst** [comment]
FYI: any further enhancement should be filed as regular feature request (ability to select which providers and such).
