### ISSUE TITLE
[Mandatory 2FA] Spec: How to handle existing users

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#11021]
**Mandatory 2FA in Nextcloud 15**

Overview/progress board: https://github.com/orgs/nextcloud/projects/17

:rocket: 

---

# Specification: Handling of existing users with enforced/mandatory 2FA

Enforcing two-factor authentication for a set of users opens the question of how to handle the case that they haven't yet enabled a 2FA provider for their account.

I can basically think of these alternatives.

## Approach A – Simply lock accounts without 2FA

This might not be the best UX for the effected users, but one of the simplest approaches to this open question is to simply lock user accounts that don't use 2FA. It remains unanswered if that only applies to new sessions/logins or also existing sessions.

Implementation effort: low.

## Approach B – Allow users to log in, but force them to set up 2FA

Users will be able to log in as before (via the web interface). They can, however, not access any Nextcloud functionality except for 2FA settings. The tricky part is how to handle this generically since 2FA providers are provided by 3rd party apps and we cannot make any assumptions of how their setup works. This greatly differs from provider to provider.

Implementation effort: high.

## Approach C – Lock user accounts without 2FA but offer admin support provider access

As described in #11020, there are plans/discussions to implement a "support provider" that allows admins to generate a code user can use to log in, e.g. when they lost access to their other second factors.

Once admins enforce 2FA, they could use this provider to help users gain back access to their account. Obviously, this provider access can only be used a single time. On that login, the user *has to* set up 2FA. Otherwise future logins will be blocked again.

Implementation effort: medium.

**Comment by rullzer** [comment]
Option A is not really a solution I think. Yes it solves the problem but doesn't work easily.

Option C would be a good first step. You login via some token you get from an admin. And then the user can properly setup 2FA.
Option B would of course be the best but requires work.

I vote to first work towards option C and see how far we get

**Comment by rullzer** [comment]
Small thing: We should send a notification when 2FA is enforced for an account. Just so people get notified.
