### ISSUE TITLE
Implement IProvider2

### ISSUE THREAD

**Issue by sycophantic** [nextcloud/server#1102]
The Duo 2FA provider (https://github.com/elie195/duo_provider) utilizes IProvider2 (which is preset in owncloud, https://github.com/owncloud/core/commit/d1c9c10fda3afc54e19f24245fd55372c4f48371). It may be beneficial to add this since many users would love to have Duo support and this addon already exists.

**Comment by rullzer** [comment]
cc: @ChristophWurst
