### ISSUE TITLE
FileSummary (filelist) uses JS Eval

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#11030]
For https://github.com/orgs/nextcloud/projects/18

The FileSummary uses handlebars and compiles the templates on the fly. This prevents a stricter CSP.

**Comment by rullzer** [comment]
@nextcloud/javascript seems that the simplest thing here is just moving this to plain javascript. Converting to vue will happen when the whole fiellist is moved to vue.

For now just moving it to plain js is probably easiest and quickest.

**Comment by blizzz** [comment]
thus, handlebars tempalte compilation in general is evil?

**Comment by blizzz** [comment]
we didn't do ship precompiled templates  because $forgotten_issues
