### ISSUE TITLE
Strenghtify uses javascript eval

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#11033]
For https://github.com/orgs/nextcloud/projects/18

The strenghtify plugin we use for jquery toindicate password strength uses eval. This prevents a default stricter CSP.

We should look into how we can fix this properly.

**Comment by rullzer** [comment]
@nextcloud/javascript

**Comment by danielkesselberg** [comment]
Ref: https://github.com/MorrisJobke/strengthify/issues/19

**Comment by MorrisJobke** [comment]
Version 0.5.4 of it solves the issue: https://github.com/MorrisJobke/strengthify/releases/tag/0.5.4
