### ISSUE TITLE
Updating App will enable maintenance in config.php ...

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/server#11038]
App Share-Renamer should be updated to 2.1 and Notes to 2.4.1,

NC is not updating these apps, and will keep maintenance on
Admin-Overwies is not working (internal server error)

### Server configuration

Ubuntu 18.04 LTS
NGINX
MariaDB
PHP 7.2.4

**Comment by MorrisJobke** [comment]
> Admin-Overwies is not working (internal server error)

This means that there is an entry in your Nextcloud log (in data/nextcloud.log) - could you provide that?

**Comment by MorrisJobke** [comment]
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
