### ISSUE TITLE
Duplicate slashes are removed from path parameters.

### ISSUE THREAD

**Issue by Treora** [nextcloud/server#11049]
When processing the requested path, Nextcloud cleans up subsequent slashes paths, such that e.g. `/apps//test` will become `/apps/test`. While usually not an issue, it becomes problematic when you want to keep those double slashes, most commonly when expecting a url as a parameter in apps for redirection, proxying, or archiving.

### Reproduce 

For example, an app could try to use the following URL syntax:

    /apps/redirectme/to/https://example.org

And therefore define a route like this:

    [
      'name' => 'page#redirect',
      'url' => '/to/{target}',
      'requirements' => array('target' => '.+')
    ]

#### Expected behaviour
Parameter `$target` will be `https://example.org`.

#### Actual behaviour
Parameter `$target` is `https:/example.org` (note the single slash).

Even when using a function such as [`IRequest->getRawPathInfo()`](https://docs.nextcloud.com/server/14/developer_manual/api/OCP/IRequest.html#OCP\IRequest::getRawPathInfo), you will obtain the 'cleaned'/corrupted value.

### Cause
This [one line](https://github.com/nextcloud/server/blob/c31632ccdf5c9a76499ad36b40c8cf52c1602754/lib/private/AppFramework/Http/Request.php#L725) seems to be the culprit:

    $requestUri = preg_replace('%/{2,}%', '/', $requestUri);

### Workaround
You can work around this by reading the parameter manually; somewhat hacky, but something like this seems to work: (cleaner solutions welcome!)

    $path = $_SERVER['REQUEST_URI'];
    $routePath = 'apps/redirectme/to/'; // (presumably nobody has this string in their web root)
    $target = substr($path, strpos($path, $routePath) + strlen($routePath));

### Prior discussion

This issue has been traced by and discussed with @nickvergessen and @LukasReschke. The thought thus far was that there was no particularly strong reason for the implemented behaviour, but that changing this behaviour might be problematic due to existing apps that may rely on it.

Reporting the issue nevertheless to have it documented, and perhaps the thoughts on this may change, or it may be worth providing an extra method somewhere to get the parameters without the slash-cleaning step.

**Comment by patschi** [comment]
Just my two cents on this: Shouldn't be URL-like parameters in the actual URL encoded by using `urlencode` anyway? For example [W3C](https://www.w3.org/Addressing/URL/4_URI_Recommentations.html) recommends that slashes always represent a "hierachical structure", which external parameters like external URLs don't do - to be exact.

Sure, it doesn't fix the actual issue here, but probably the app which is using this kind of URLs should do the encoding first?

**Comment by rullzer** [comment]
Yes. Why not do something like `/apps/redirectme?to=https://example.org`

Then encode the url still ofcourse :wink:

**Comment by szaimen** [comment]
Let us track this in https://github.com/nextcloud/server/issues/20935
