### ISSUE TITLE
Uploading, deleting and browsing files in webpage pending takes minutes

### ISSUE THREAD

**Issue by CheerChen** [nextcloud/server#11059]
### Steps to reproduce

1. My company is using nextcloud as private cloud and the folder can be access by both webpage and virtual machine, recently uploading and deleting, sometimes jumping between folders in webpage could caused browser pending a long time (in my case it was 2mins and half) 

2. Then I checked php slow log and went into source code and found out that the **scanChildren** function (in lib/private/Files/Cache/Scanner.php) is recursively scanning files and **scanFile** excuted sql query for >90000 times and each query spend about 0.0012s , so the 2min+ waiting came form that.

3. Then I tried to fix it by selectively scan files if not exists, the code is like above.  It works, the speed become normal BUT it has some side affects, the change of file (create, delete) in VM can not synchronize with webpage , the changes might be update after a few seconds or later (when it triggered to have a full scan I guess). 

`// lib/private/Files/Cache/Scanner.php line 420`
`$existingData = isset($existingChildren[$file]) ? $existingChildren[$file] : null;`
`if (!$existingData) {`
`       $data = $this->scanFile($child, $reuse, $folderId, $existingData, $lock);`
` }`

4. I wonder that is a reliable solution or if there has another way to prevent the long pending problem (except using redis as filecache), thanks.

### Expected behaviour
Uploading, deleting and browsing files in webpage pending in seconds 

### Actual behaviour
Uploading, deleting and browsing files in webpage pending takes minutes

### Server configuration

**Operating system**: ubuntu.16.04.4

**Database:** 8.0.11 MySQL Community Server - GPL

**PHP version:** PHP 7.0.15

**Nextcloud version:** 11.0.2.7

**Comment by danielkesselberg** [comment]
Thanks for reporting this issue :+1: Your nextcloud is a bit outdated. 11.x is already end of life. Could you check if this is happening with a newer version as well?

**Comment by ChristophWurst** [comment]
I'm closing this ticket because it hasn't received any updates in a long time. If this is still relevant, feel free to re-open or file a new ticket.

Thank you.
