### ISSUE TITLE
theming app breaks browser caching on login site

### ISSUE THREAD

**Issue by Florz** [nextcloud/server#1106]
### Steps to reproduce
1. enable theming app with a nice logo and background image
2. load login page
3. reload

### Expected behaviour
on reload the background image should be loaded from browser cache

### Actual behaviour
* images and all scripts/css are loaded from server
* caching header (and other headers?) seem to be wrong / missing

### Server configuration
**Operating system**:
debian jessie (8.4)
**Web server:**
nginx/1.6.2
**Database:**
MySQL 5.5.50-0+deb8u1 (Debian)
**PHP version:**
PHP 5.6.24-0+deb8u1
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated (from Nextcloud)
**Where did you install Nextcloud from:**
Nextcloud website (zip file)
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.3.3
  - comments: 1.0.0
  - contacts: 1.3.1.0
  - dav: 1.0.0
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_mv
  - files_retention
  - shorten
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "oc38b17e2483",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.domain.tld"
        ],
        "datadirectory": "\/var\/www\/owncloud_data",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "smtp",
        "mail_domain": "domain.tld",
        "forcessl": true,
        "loglevel": "2",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "updatechecker": false
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Chromium / Firefox
**Operating system:**
debian testing
#### Web server error log
<details>
<summary>Web server error log</summary>
```
2016/08/27 19:42:52 [error] 21432#0: *4466 upstream sent invalid status "0" while reading response header from upstream, client: 123.321.42.23, server: cloud.domain.tld, request: "OPTIONS /remote.php/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.domain.tld"
2016/08/27 21:31:22 [error] 21434#0: *4632 upstream sent invalid status "0" while reading response header from upstream, client: 46.246.36.94, server: cloud.domain.tld, request: "OPTIONS /remote.php/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.domain.tld"
2016/08/27 23:51:27 [error] 21433#0: *5717 upstream sent invalid status "0" while reading response header from upstream, client: 46.246.36.94, server: cloud.domain.tld, request: "OPTIONS /remote.php/ HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "cloud.domain.tld"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
```
{"reqId":"vXnrvJmzflRvxhviS5y6","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:47:48+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"5wRY7PawaAZHhsvSmAxH","remoteAddr":"77.87.48.191","app":"core","message":"Login failed: 'florz' (Remote IP: '77.87.48.191')","level":2,"time":"2016-08-27T21:48:17+00:00","method":"POST","url":"\/login","user":"--"}
{"reqId":"xy0bShLiXqjdYV5IGJUS","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:48:47+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"ca1O9WZimHqNxNPgoo3t","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:48:49+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"ZMAWpjICscko6Be3eGb6","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:49:47+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"r0RG6zMrow3ocSSAkLYA","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:49:49+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"UpZFFX774Vw0RHVjr6RA","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:50:47+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"P6s4jZYURpx29ZagTM7v","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:50:48+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"trPTWVZDKSFfvZtETD+\/","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:51:47+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
{"reqId":"DdyZWczLdaelrxHchmz0","remoteAddr":"123.321.23.42","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-08-27T21:51:48+00:00","method":"PROPFIND","url":"\/public.php\/webdav\/","user":"--"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Chromium audit log:

Combine external CSS (21)
Combine external JavaScript (51)
Enable gzip compression (4)
Leverage browser caching (80)
Minimize cookie size
Parallelize downloads across hostnames (25)
Serve static content from a cookieless domain (25)
Specify image dimensions (1)
Web Page Performance
Optimize the order of styles and scripts (1)
Remove unused CSS rules (1010)
```
</details>

**Comment by LukasReschke** [comment]
#1103 fixes this.

@karlitschek Backport to stable10? Rather small change (most of it are unit tests).

**Comment by karlitschek** [comment]
absolutely. please backport 👍
