### ISSUE TITLE
After Upgrade to 13.0.6.1 File Not Found in Node.php related to app files_trashbin

### ISSUE THREAD

**Issue by willymiti** [nextcloud/server#11079]
### Steps to reproduce
1. Upgrade from 13.0.5.2 to 13.0.6.1 via WebUpdater

### Expected behaviour
Nextcloud is running as before

### Actual behaviour
Internal Server Error
OCP\Files\NotFoundException
.../lib/private/Files/Node/Node.php
colum: 97

When I disable the app **files_trashbin** via database (enabled = no), nextcloud shows no error page any more and works as desired.

### Server configuration

**Operating system**:

**Web server:**

**Database:** 10.1.35-MariaDB - MariaDB Server

**PHP version: 7.0**

**Nextcloud version:** 13.0.6.1

**Updated from an older Nextcloud**

**Where did you install Nextcloud from:** WebInstaller

**Integrity/failed:** No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

"activity","enabled","yes"
"calendar","enabled","no"
"comments","enabled","no"
"contacts","enabled","no"
"dav","enabled","yes"
"federatedfilesharing","enabled","yes"
"federation","enabled","no"
"files","enabled","yes"
"files_pdfviewer","enabled","yes"
"files_retention","enabled","no"
"files_sharing","enabled","yes"
"files_texteditor","enabled","yes"
"files_trashbin","enabled","yes"
"files_versions","enabled","yes"
"files_videoplayer","enabled","no"
"firstrunwizard","enabled","yes"
"gallery","enabled","yes"
"logreader","enabled","yes"
"lookup_server_connector","enabled","yes"
"nextcloud_announcements","enabled","no"
"notifications","enabled","yes"
"oauth2","enabled","yes"
"password_policy","enabled","yes"
"provisioning_api","enabled","yes"
"serverinfo","enabled","yes"
"sharebymail","enabled","yes"
"survey_client","enabled","yes"
"systemtags","enabled","yes"
"theming","enabled","yes"
"twofactor_backupcodes","enabled","yes"
"updatenotification","enabled","yes"
"workflowengine","enabled","yes"
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

$CONFIG = array (
  'instanceid' => 'removed',
  'passwordsalt' => 'removed',
  'secret' => 'removed',
  'trusted_domains' => 
  array (
    0 => 'removed',
  ),
  'datadirectory' => '/home/removed/nextclouddata',
  'overwrite.cli.url' => 'https://removed',
  'dbtype' => 'mysql',
  'version' => '13.0.6.1',
  'dbname' => 'removed',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'removed',
  'dbpassword' => 'removed',
  'installed' => true,
  'mail_from_address' => 'info',
  'mail_smtpmode' => 'php',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => 'removed',
  'maintenance' => false,
  'loglevel' => 1,
  'theme' => '',
  'debug' => true,
);

</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 61.0.2

**Operating system:**Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"W5BNDNEyOMZRaYW4zjxCiQAAAAY","level":3,"time":"2018-09-05T21:39:25+00:00","remoteAddr":"31.18.236.45","user":"removed","app":"index","method":"GET","url":"\/index.php\/apps\/files\/","message":"Exception: {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(217): OC\\\\Files\\\\Node\\\\Node->getFileInfo()\\n#1 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php(117): OC\\\\Files\\\\Node\\\\Node->getPermissions()\\n#2 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/File.php(62): OC\\\\Files\\\\Node\\\\Node->checkPermissions(2)\\n#3 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Files\\\/SimpleFS\\\/SimpleFile.php(104): OC\\\\Files\\\\Node\\\\File->putContent('\\\/*\\\\n * Copyright...')\\n#4 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(246): OC\\\\Files\\\\SimpleFS\\\\SimpleFile->putContent('\\\/*\\\\n * Copyright...')\\n#5 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Template\\\/SCSSCacher.php(126): OC\\\\Template\\\\SCSSCacher->cache('\\\/home\\\/removed\\\/...', '1980-7378-trash...', 'trash.scss', Object(OC\\\\Files\\\\SimpleFS\\\\SimpleFolder), '\\\/apps\\\/files_tra...')\\n#6 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(109): OC\\\\Template\\\\SCSSCacher->process('\\\/home\\\/removed\\\/...', 'css\\\/trash.scss', 'files_trashbin')\\n#7 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Template\\\/CSSResourceLocator.php(84): OC\\\\Template\\\\CSSResourceLocator->cacheAndAppendScssIfExist('\\\/home\\\/removed\\\/...', 'css\\\/trash.scss', 'files_trashbin')\\n#8 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Template\\\/ResourceLocator.php(78): OC\\\\Template\\\\CSSResourceLocator->doFind('css\\\/trash')\\n#9 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/TemplateLayout.php(270): OC\\\\Template\\\\ResourceLocator->find(Array)\\n#10 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/TemplateLayout.php(186): OC\\\\TemplateLayout::findStylesheetFiles(Array)\\n#11 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/legacy\\\/template.php(207): OC\\\\TemplateLayout->__construct('user', 'files')\\n#12 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/public\\\/AppFramework\\\/Http\\\/TemplateResponse.php(157): OC_Template->fetchPage()\\n#13 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(114): OCP\\\\AppFramework\\\\Http\\\\TemplateResponse->render()\\n#14 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(115): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Files\\\\Controller\\\\ViewController), 'index')\\n#15 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('ViewController', 'index', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#16 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#17 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Route\\\/Router.php(297): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#18 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/base.php(999): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/')\\n#19 \\\/home\\\/removed\\\/public_html\\\/cloud\\\/index.php(42): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/home\\\/removed\\\/public_html\\\/cloud\\\/lib\\\/private\\\/Files\\\/Node\\\/Node.php\",\"Line\":97}","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko\/20100101 Firefox\/61.0","version":"13.0.6.1"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

Interner Serverfehler

Der Server konnte die Anfrage nicht fertig stellen.

Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden.
Technische Details

    Entfernte Adresse: 31.18.236.45
    Anfragekennung: W5BM-nhZzUmGG1T6iItfDgAAABI
    Typ: OCP\Files\NotFoundException
    Code: 0
    Nachricht:
    Datei: /home/willymit/public_html/cloud/lib/private/Files/Node/Node.php
    Zeile: 97

Trace

#0 /home/willymit/public_html/cloud/lib/private/Files/Node/Node.php(217): OC\Files\Node\Node->getFileInfo()
#1 /home/willymit/public_html/cloud/lib/private/Files/Node/Node.php(117): OC\Files\Node\Node->getPermissions()
#2 /home/willymit/public_html/cloud/lib/private/Files/Node/File.php(62): OC\Files\Node\Node->checkPermissions(2)
#3 /home/willymit/public_html/cloud/lib/private/Files/SimpleFS/SimpleFile.php(104): OC\Files\Node\File->putContent('/*\n * Copyright...')
#4 /home/willymit/public_html/cloud/lib/private/Template/SCSSCacher.php(246): OC\Files\SimpleFS\SimpleFile->putContent('/*\n * Copyright...')
#5 /home/willymit/public_html/cloud/lib/private/Template/SCSSCacher.php(126): OC\Template\SCSSCacher->cache('/home/willymit/...', '1980-7378-trash...', 'trash.scss', Object(OC\Files\SimpleFS\SimpleFolder), '/apps/files_tra...')
#6 /home/willymit/public_html/cloud/lib/private/Template/CSSResourceLocator.php(109): OC\Template\SCSSCacher->process('/home/willymit/...', 'css/trash.scss', 'files_trashbin')
#7 /home/willymit/public_html/cloud/lib/private/Template/CSSResourceLocator.php(84): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/home/willymit/...', 'css/trash.scss', 'files_trashbin')
#8 /home/willymit/public_html/cloud/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/trash')
#9 /home/willymit/public_html/cloud/lib/private/TemplateLayout.php(270): OC\Template\ResourceLocator->find(Array)
#10 /home/willymit/public_html/cloud/lib/private/TemplateLayout.php(186): OC\TemplateLayout::findStylesheetFiles(Array)
#11 /home/willymit/public_html/cloud/lib/private/legacy/template.php(207): OC\TemplateLayout->__construct('user', 'files')
#12 /home/willymit/public_html/cloud/lib/public/AppFramework/Http/TemplateResponse.php(157): OC_Template->fetchPage()
#13 /home/willymit/public_html/cloud/lib/private/AppFramework/Http/Dispatcher.php(114): OCP\AppFramework\Http\TemplateResponse->render()
#14 /home/willymit/public_html/cloud/lib/private/AppFramework/App.php(115): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#15 /home/willymit/public_html/cloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#16 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#17 /home/willymit/public_html/cloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#18 /home/willymit/public_html/cloud/lib/base.php(999): OC\Route\Router->match('/apps/files/')
#19 /home/willymit/public_html/cloud/index.php(42): OC::handleRequest()
#20 {main}

</details>

**Comment by willymiti** [comment]
Maybe related to #10373?

The appfolder data/appdata_removed/js only lists the following folders:

- activity
- comments
- core
- files
- files_sharing
- files_texteditor
- gallery
- notifications
- systemtags

Generaing the folders:
- files_trashbin
- files_versions
is not changing anything

**Comment by kesselb** [comment]
Is this still relevant?
