### ISSUE TITLE
Theming message grammar needs change

### ISSUE THREAD

**Issue by iamfool** [nextcloud/server#1107]
### Steps to reproduce
1. Change your application theme to custom theme in config file
2. log in as admin
3. navigate to theme option 
![screenshot-2](https://cloud.githubusercontent.com/assets/5293384/18032736/6d50f8a8-6cc4-11e6-8a93-60741fbff070.png)

4. check for theme message 

### Expected behaviour
The message should be like --> 

"You are already using a custom theme"

### Actual behaviour
Currently it is displaying

"You already use a custom theme"

**Comment by rullzer** [comment]
Nice spot.
Could you create a pull request with a fix?

**Comment by iamfool** [comment]
Sure @rullzer

**Comment by iamfool** [comment]
Created Pull request

**Comment by juliushaertl** [comment]
closed with #1117

Thanks @iamfool.
