### ISSUE TITLE
Rainloop as external site sso autologin logged Nextcloud user 

### ISSUE THREAD

**Issue by DeAlexPesh** [nextcloud/server#11072]
Hi, how I can autologin nextcloud LDAP user by name|email if I use official plugin "external sites" for Rainloop?
SSO Rainloop: https://github.com/RainLoop/rainloop-webmail/issues/103
Thank you.

```
sudo nano .../application.ini
[labs]
allow_external_login = Off
allow_external_sso = On
external_sso_key = "ssokey"

sudo nano .../webmail.php
<?php
```

> OC_Util::checkLoggedIn();
> $sEmail = '';
> $sEncodedPassword = '';
> $sUser = OC_User::getUser();
> $sEmail = OC_User::getUserEmail(?);
> $sDecodedPassword = OC_User::getUserPassword(?);

```
$domains = array(
  "domain.ru"
);
$proto = ((!empty($_SERVER['HTTPS']) &&
                  $_SERVER['HTTPS'] != 'off') ||
                  $_SERVER['SERVER_PORT'] == 443) ? "https://" : "http://";
$url = $_SERVER['HTTP_HOST'];
$domain = join(".", array_slice(array_filter(
  explode('.', $url), function($v) { return $v !== ''; }), -2
));
foreach ($domains as $d) {
  if($d === $domain) {
    $postData = @file_get_contents($proto . 'webmail.' . $domain . '/index.php?ExternalSso&SsoKey=ssokey&Email=' . $sEmail . '&Password=' . $sDecodedPassword . '&Output=Json');
    if($postData === FALSE) {
      \header('Location:' . $proto . 'webmail.' . $domain . '/index.php');
    } else {
      $ssoHash = json_decode($postData);
      \header('Location:' . $proto . 'webmail.' . $domain . '/index.php?sso&hash=' . $ssoHash->{'Result'});
    }
    die();
  }
}
echo('403 Forbidden Error: ' . $url); die();

"external link"
https://domain.ru/cloud/webmail.php

```

**Comment by DeAlexPesh** [comment]
nope.
Can you say me, what can I get username | email | pass (decoded) of active user, and | or create on nextcloud compaitible with rainloop sso hash?

**Comment by nickvergessen** [comment]
This should be solved in https://github.com/pierre-alain-b/rainloop-nextcloud/issues/73

**Comment by DeAlexPesh** [comment]
@nickvergessen, his project does not work in new versions

**Comment by pierre-alain-b** [comment]
The project is back on track and a version has been published for NC14.

**Comment by DeAlexPesh** [comment]
Hi, @pierre-alain-b 
[external sites](https://apps.nextcloud.com/apps/external)
somehow the ability to do autologin in rainloop through this application?
