### ISSUE TITLE
occ app:install works on and off

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#11070]
I've got several reports the about failing app installations since I implemented `occ app:install` in the VM. I've also noticed it myself that apps often fail to install right after installing Nextcloud. ~~Lately I've also got reports that OnlyOffice works if you enable from gui, but not with the `occ` commands (install and enable).~~ Hence this report.

I can't really give you any steps to reproduce since it happens randomly. My own theory is that it's due to one of three things:

1. The App Store is temporarily overloaded
2. Network is temporarily failing
3. The code  for `occ app:install` is buggy 

Could you please give me any guidance on different scenarios to test so that I can give you more accurate steps to reproduce?

ccing @MorrisJobke on this (as I do for everything else ;) )

**Comment by nxtester** [comment]
There is a known DNS issue in Ubuntu 18.04, see https://medium.com/@ahmadb/fixing-dns-issues-in-ubuntu-18-04-lts-bd4f9ca56620.

After modifying DNS entries in /etc/systemd/resolved.conf I was finally able to execute NC script without any issues regarding resolving external server names.

Modifications in /etc/systemd/resolved.conf:

DNS=8.8.8.8 2001:4860:4860::8888
FallbackDNS=8.8.4.4 2001:4860:4860::8844

nxtester

**Comment by blizzz** [comment]
To be fair the app server was not always reliable. We improved the config, that should hopefully help. 

Definitely I bet on 1 &| 2.

**Comment by enoch85** [comment]
The app server got more stable, haven't seen this for a while. Closing.

**Comment by chriscroome** [comment]
FWIW, I have been hitting this issue for the last 15 minutes via `php occ app:install` and searching for the problem found this threa, but it now appears to have resolved itself so I suspect that the app servers were having issues again?

**Comment by mmallejac** [comment]
Sasme for me here. NC 21.0.1 running inside the official Docker image. 
Random.
