### ISSUE TITLE
on 14 RC2 the news app hides the sidepanel

### ISSUE THREAD

**Issue by fvzwieten** [nextcloud/server#11073]
### Steps to reproduce
1. Have NC 13.0.5 with up-to-date news app
2. Upgrade to 14RC2
3. Go to News app

### Expected behaviour
The app should open with in the side panel all RSS feeds to choose from.

### Actual behaviour
The RSS feed panel is only shown during loading of the page. After that, it's gone and only the main pane is shown with all items.

### Server configuration

**Operating system**:
DietPi

**Web server:**
lighttpd

**Database:**
mysql

**PHP version:**
7.0.27

**Nextcloud version:** (see Nextcloud admin page)
14RC2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.0.5.

**Where did you install Nextcloud from:**
the updater from the settings.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by danielkesselberg** [comment]
Thanks for reporting this issue :+1:  Please report the bug in the news app repository https://github.com/nextcloud/news/issues and close this issue here.

**Comment by fvzwieten** [comment]
Done!

**Comment by danielkesselberg** [comment]
Ref https://github.com/nextcloud/news/issues/320
