### ISSUE TITLE
News Reader broken

### ISSUE THREAD

**Issue by Wizlonex** [nextcloud/server#11095]
1.  Enable News App Reader
2.  Try to access Feeds
3.  Fails - gives a list of cards, but no subscription option.  Clicking on cards does nothing.

### Expected behaviour
In 13, I get my RSS feed menu so I can add new folders/subscriptions and view news etc.

### Actual behaviour
No menu on lhs - I just see the standard RSS feed cards, but nothing works.  I tried Chrome and Firefox so I don;t think it's a browser issue.  Of course, it could be the News APP but since that works on Nextcloud 13....

### Server configuration

**Operating system**:  Ubuntu 16.04 in LXC container

**Web server:**  Apache2

**Database:**  Mysql

**PHP version:** 7

**Nextcloud version:** Beta 2

**fresh install:**  (My production server is 13.06, all works fine).

**Where did you install Nextcloud from:**  Nextcloud

</details>

News, Calendar, Notes, Tasks, Contacts.  Everything else works as expected so far, just News feed app/nextcloud is broken.
<summary>App list</summary>

```

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...  No

**Are you using encryption:** yes/no  YES (server, not end to end)

**Are you using an external user-backend, if yes which one:** NO

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Wizlonex** [comment]
![screenshot from 2018-09-06 17-42-39](https://user-images.githubusercontent.com/35621692/45172136-51f9cb00-b1fc-11e8-83ad-05841ae2ab60.png)

**Comment by danielkesselberg** [comment]
Thanks for reporting this issue :+1:  Please report the bug in the news app repository https://github.com/nextcloud/news/issues and close this issue here. It is likely that this error has already been reported (#11073)

**Comment by danielkesselberg** [comment]
Ref https://github.com/nextcloud/news/issues/320

**Comment by danielkesselberg** [comment]
Ref https://github.com/nextcloud/news/issues/320
