### ISSUE TITLE
Can't install any app

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#11092]
After clean install of NC 14 I could not install any additional apps!

i received the following error message:

core | Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT * FROM "oc_appconfig"':  SQLSTATE[HY000]: General error: 1 no such table: oc_appconfig/var/www/servers/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractSQLiteDriver->convertException("An exceptio ... g", Doctrine\DBA ... ]})/var/www/servers/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 855: Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "SELECT * FR ... "", [])/var/www/servers/nextcloud/lib/private/DB/Connection.php - line 195: Doctrine\DBAL\Connection->executeQuery("SELECT * FR ... "", [], [], null)/var/www/servers/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php - line 206: OC\DB\Connection->executeQuery("SELECT * FR ... "", [], [])/var/www/servers/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php - line 214: Doctrine\DBAL\Query\QueryBuilder->execute()/var/www/servers/nextcloud/lib/private/AppConfig.php - line 315: OC\DB\QueryBuilder\QueryBuilder->execute()/var/www/servers/nextcloud/lib/private/AppConfig.php - line 94: OC\AppConfig->loadConfigValues()/var/www/servers/nextcloud/lib/private/AppConfig.php - line 272: OC\AppConfig->getApps()/var/www/servers/nextcloud/lib/private/legacy/app.php - line 874: OC\AppConfig->getValues(false, "installed_version")/var/www/servers/nextcloud/lib/private/TemplateLayout.php - line 148: OC_App::getAppVersions()/var/www/servers/nextcloud/lib/private/legacy/template.php - line 210: OC\TemplateLayout->__construct("error", "")/var/www/servers/nextcloud/lib/private/Template/Base.php - line 132: OC_Template->fetchPage()/var/www/servers/nextcloud/lib/private/legacy/template.php - line 359: OC\Template\Base->printPage()/var/www/servers/nextcloud/index.php - line 69: OC_Template::printExceptionErrorPage(Doctrine\DBA ... {}, 500)
-- | --

NC 14.0
sqlite3
lighttpd 1.4.16
PHP Version 7.0.27-0+deb9u1

How to resolve the situation?
May thanks in advance!

regards, hitam4450

**Comment by timm2k** [comment]
Looks like your database isn't accessible. Can you confirm that Table ```oc_appconfig``` is present and accessible from configured DB user?

**Comment by hitam4450** [comment]
opening the files app ---> the spinner spins continuously.....

**Comment by hitam4450** [comment]
how  can I check, that the table oc_appconfig is present ???

**Comment by hitam4450** [comment]
I am going to revert to a working 13.0.5 istallation!

NextCloud is like Microsoft.....NEVER use a new major upgrade right away on the first day of release, it is for sure a headache! 
Better wait  until .1 or .2 release!

regards, hitem4450

**Comment by helmut72** [comment]
* unzip nextcloud-14.0.0.zip in /var/www/html
* chown -R www-data:www-data /var/www/html/nextcloud
* opened www.mydomain.com/nextcloud
* finished installation with sqlite and setup admin user
* added one app (external storage support)
* works

Please try again, don't do other things.

Ubuntu 18.04 with default Apache and php-fpm

**Comment by timm2k** [comment]
But error says ```General error: 1 no such table: oc_appconfig```. 
If SQLite is in place may permissions of the files are wrong - just an idea.

**Comment by hitam4450** [comment]
@Patschi: I secured my 13.0.5 installation and installed NC 14 into a new directory including new database wit the help of the webinstaller ! I am on Owncloud since version 6 or 7 and on Nextcloud project since day 1!

regards, hitam4450

**Comment by hitam4450** [comment]
@timm2k Thanks for your advice! All permissions are set correctly : www-data !!

**Comment by MorrisJobke** [comment]
This looks really like a setup issue, as the install procedure works quite reliable on our CI setup, which is done multiple dozen times a day.

Could we move this discussion to the forums and once you found the problematic part which should be fixed on the code side open a ticket for this?

Thanks a lot
