### ISSUE TITLE
NC14 Theming: Posibility to switch off "Get your own free account"

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#11101]
On NC 14.0.0.19 on the public share page there is shown a link "Get your own free account" as last line in the footer.

I understand, that advertising nextcloud in this way is an option.

But not only because of GDPR-Reasons I would like to be able to switch of this footer-line without have to modify the code. An option in the theming-app to switch this line off would be fine...

@juliushaertl ?

**Comment by juliushaertl** [comment]
There is a config flag to disable this link: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1643

**Comment by JSoko** [comment]
@juliushaertl 
Thank You, That's great!

**Comment by rcdailey** [comment]
Once you disable this via the above config option, there's still a footer: It shows a Nextcloud link at the bottom. Is there a way to disable this as well? I'm fine doing custom CSS if that's the only option.

**Comment by JB1985** [comment]
Why is this Issue closed?

@rcdaily have you put this in your custom Theme in core/css/server.css? This is not working for me.

**Comment by danielkesselberg** [comment]
> There is a config flag to disable this link: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1643

Issue is closed because question "Posibility to switch off "Get your own free account" is anwered.  I know an issue tracker looks similar to a community board but works different. You usually have one issue per problem.

The issue here: Howto switch off "Get your own free account". How can i remove the nextcloud branding is something different.

**Comment by enoch85** [comment]
Correction; https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1705

Added it but it didn't work, but I guess that's a separate issue...

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/68952306aa3309286b6cd685976c2cdee674268a/config/config.sample.php#L1703

A few people set the value to "false". Maybe you are running into the same issue. `'simpleSignUpLink.shown' => false` should do the trick.

**Comment by enoch85** [comment]
Worked! The `occ` command generated the wrong value.

**Comment by danielkesselberg** [comment]
`--type=bool --value=false` should work for occ. By default a value is considered as string.

**Comment by Oclair** [comment]
dude are you guys serious? nextcloud does not agree with nextcloud
Stop sneaking in code like that

**Comment by Oclair** [comment]
This issue was closed when it should remain open

**Comment by Oclair** [comment]
'simpleSignUpLink.shown' => false
added to config.php
causes a server misconfiguation error


> There is a config flag to disable this link: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L1643

The flag causes a server misconfiguation error
