### ISSUE TITLE
Tabindex of login form inputs

### ISSUE THREAD

**Issue by coderkun** [nextcloud/server#1110]
The current login form does not specify any [tabindex](http://www.w3schools.com/tags/att_global_tabindex.asp) attribute. The tab order is therefore “username”, “password”, “submit”, “stay logged in”.

Wouldn’t it be better to have the “submit button” as last tab index so that the final order would be “username”, “password”, “stay logged in”, “submit”?

### Steps to reproduce
1. Navigate to server login page in a webbrowser
2. Use tab-key on your keyboard

### Expected behaviour
Order of selected fields is expected to be “username”, “password”, “stay logged in”, “submit”.

### Actual behaviour
Order of selected fields is currently “username”, “password”, “submit”, “stay logged in”.

### Server configuration
**Nextcloud version:** 10.0

### Client configuration
**Browser:** Epiphany 3.20.3
**Operating system:** Arch Linux

**Comment by rullzer** [comment]
@jancborchardt
