### ISSUE TITLE
Documentation of "use of the the built in php mailer is no longer supported"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11106]
https://docs.nextcloud.com/server/14/admin_manual/configuration_server/email_configuration.html

here you can see still php in screenshots / text.

**Comment by patschi** [comment]
This issue would probably fit better in the [Issues section of the documentation repo](https://github.com/nextcloud/documentation/issues) as the documentation is not directly related to the server code base.

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/documentation/issues/896
