### ISSUE TITLE
Unable to delete group with a slash in its name

### ISSUE THREAD

**Issue by brknkfr** [nextcloud/server#11110]
### Steps to reproduce
1. Create a group with a slash in its name
2. Delete the group (example "mygroup/afterslash")
3. Refresh the page

### Expected behaviour
Group should be deleted.

### Actual behaviour
Group isn't deleted. It still appears after refreshing the page after a minute.

From the apache log when trying to delete the example group "mygroup/afterslash":
[07/Sep/2018:17:15:24 +0200] "DELETE /settings/users/groups/mygroup%2Fafterslash HTTP/1.1" 404 714 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0"

Not found?

### Server configuration

**Operating system**: Debian Stretch

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** php 7.0.30

**Nextcloud version:** 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

It seems to be the same bug as here: https://github.com/nextcloud/server/issues/2954

**Comment by bpcurse** [comment]
Duplicate of https://github.com/nextcloud/server/issues/6032

**Comment by brknkfr** [comment]
I don't think it's a duplicate of #6032 where a "fix" is already merged (see #9841) into 13.0.5. But I am using 13.0.6 which contains this fix already ...

**Comment by MorrisJobke** [comment]
Fix is in #11200

**Comment by MorrisJobke** [comment]
Fixed in 14.0.5 and 15.0.0
