### ISSUE TITLE
Creating a new app password shows Last activity "In a few seconds"

### ISSUE THREAD

**Issue by Bubu** [nextcloud/server#11118]
### Steps to reproduce
1. Go to security settings
2. Create a new app password

### Expected behaviour
shown Last activity 'never' or '0 seconds ago'

### Actual behaviour
shows last activity: 'in a few seconds'
![image](https://user-images.githubusercontent.com/105185/45254019-89898400-b370-11e8-83ba-f406c8978f7c.png)

**Comment by Bubu** [comment]
btw I just checked server and client time and they are in sync up to a second accuracy :woman_shrugging:.

**Comment by kesselb** [comment]
Looks related to https://github.com/nextcloud/server/issues/14907

Do you still see this issue @Bubu ?

**Comment by Bubu** [comment]
Still seeing this...

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. See
![image](https://user-images.githubusercontent.com/42591237/119647652-d2374300-be20-11eb-95df-5f8129c6c85b.png)
If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
