### ISSUE TITLE
Recopy should provide Skip all existing file and copy new one

### ISSUE THREAD

**Issue by ganeshjkale** [nextcloud/server#11115]
Tested latest stable release. 
Scenario :
1:open nextcloud webpage
2:drag drop folders with files on webpage

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
