### ISSUE TITLE
AmazonS3 ContentType Bug

### ISSUE THREAD

**Issue by RasenFx** [nextcloud/server#11128]
### Steps to reproduce
1. I use AmazonS3 with Route53 and Cloud Front as webserver for HTML files
2. I upload a HTML file to AmazonS3 through Nextcloud
3. When I open the url the file downloads instead of execute like a normal HTML

### Expected behaviour
I reviewed the file uploaded in S3 and the problem it's that NextCloud App (External Files) don't send the metadata that S3 need  to know what do with the file and force to download the file, this happend with (jpg, pdf, html, etc) I fixed the problem in my server, the problem it's in this file: apps/files_external/lib/Lib/Storage/AmazonS3.php, line: 590 and I put the next code to solve the problem:

`

			/*$this->writeObject($path, $source);*/

			/* Start Fix */

			$path = $this->normalizePath($path);

			$mtime = null;

			$metadata = array();

			if (is_null($mtime)) {
				$mtime = time();
			}
			
			$metadata = [
				'lastmodified' => gmdate(\DateTime::RFC1123, $mtime)
			];
			
			$mimeType = \OC::$server->getMimeTypeDetector()->detectPath($path);
			
			$this->getConnection()->putObject([
				'Bucket' => $this->bucket,
				'Key' => $this->cleanKey($path),
				'Metadata' => $metadata,
				'Body' => $source,
				'ContentType' => $mimeType,
				'MetadataDirective' => 'REPLACE',
			]);
			/* End Fix */
`

I hope that this help thanks

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by kesselb** [comment]
Thanks a lot for digging :+1: 

Is this still happening? The code looks like your code already :thinking: For which version do you developed your patch?

**Comment by kesselb** [comment]
@RasenFx Would be cool if you could check that again.

**Comment by MorrisJobke** [comment]
As there is no feedback since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
