### ISSUE TITLE
Allow email association for upload only

### ISSUE THREAD

**Issue by dynamiccreator** [nextcloud/server#11122]
### Enhancement
1. Admin creates an upload only folder **with email association** (new)
2. On the public link, the user have to fill in his email
3. The email contains the actually upload link
4. When the user uploads files, they will be saved into a sub folder of the upload folder, which has the name of his email.
5. Admin can get an email every time the user uploads files with the information who uploaded it (optional)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
