### ISSUE TITLE
Accessibility dark theme unusable

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#11131]
In the new accessibility menu, users are presented with new themes which may cater for their preferences, but unfortunately the dark theme is unusable.

Icons are black on a dark grey background.

It should work out of the box or instructions should be provided and the themes disabled until they have been applied

**Comment by skjnldsv** [comment]
@oparoz As stated, the theme is in beta and may have some issues that are still a work in progress.
A fix for this is already in #10847

**Comment by skjnldsv** [comment]
Ps: do not assign people directly here, please mention them and let them organise the tasks directly.
