### ISSUE TITLE
NC14 - 'lost_password_link' => 'disabled', is not working no more

### ISSUE THREAD

**Issue by MeCias** [nextcloud/server#11146]
Hi,

just noticed after updating from NC 13.0.6 to 14 that the config.php switch 'lost_password_link' => 'disabled', refuses to work.

EDIT
It seems like that the function itself is disabled as expected, but the link itself is not hidden as it used to be in NC 13. More a design issue.

**Comment by tflidd** [comment]
Users in the forum confirmed this bug, seems to be a regression in NC 14:
https://help.nextcloud.com/t/remove-the-possibility-to-reset-password-for-users/27570/5
