### ISSUE TITLE
using NFS-mounted folder as data fails with 'not writable'

### ISSUE THREAD

**Issue by dromer** [nextcloud/server#11145]
So I have mounted a legacy owncloud folder over nfs to this machine. Php is running a pool as the user 'nextcloud' and all files are owned by this user and the group permissions are for 'www-data' (as which the webserver is running). If I ```su nextcloud``` I can read/write everything on this share.

However when I browse to nextcloud I end up with the typical ```Your data directory is not writable``` and I have no idea why this is so.

### Server configuration
**Operating system**: debian/yunohost
**Web server:** nginx
**Database:** mysql
**PHP version:** 7.0
**Nextcloud version:** 13.0.5

**Comment by dromer** [comment]
I'm not using this as 'External storage'. It is mounted on the host machine and used directly as data folder.

**Comment by dromer** [comment]
So, according to folks in #php irc channel the ```is_writable()``` check is "known to return unusable results on sile systems with less than trivial ACL setups." and for a proper check it should "actually try to open a file with write permissions".

So there you go. Hereby I propose that ```is_writable()``` is replaced with a function that actually tries to check write-permissions by writing a file.

**Comment by ChristophWurst** [comment]
cc @icewind1991 :)

**Comment by dromer** [comment]
If this is not marked as fixed then it is still an issue.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/13237
