### ISSUE TITLE
Can I use a pure number as my username? Such as mobile number

### ISSUE THREAD

**Issue by zl59503020** [nextcloud/server#11158]
I tried to use the mobile phone number as the user name, but the user management interface will be wrong, it will report that the user does not exist. After testing, the number is used as the user name. In the process of program processing, the user name is combined with the key array. The digital key (mobile number) will be reset, so it will lead to an error.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/issues/11178 does the pr work for this issue as well?

**Comment by Nils160988** [comment]
@zl59503020 still valid?
