### ISSUE TITLE
occ maintenance:install needs a --adminemail argument

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#11153]
Otherwise, the admin account is set up incompletely and sending e-mail from the account does not work.

**Comment by enoch85** [comment]
Would be a nice improvement, but email is typically something I setup after the installation in GUI.

No need to send any emails during the installation right?

**Comment by jernst** [comment]
We are producing the UBOSbox Nextcloud https://indiecomputing.com/products/ . Part of the proposition for this product is that the user has to do little "administration". So we'd like to automatically set up as much as humanly, eh, computerly, possible.

**Comment by danielkesselberg** [comment]
@jernst @enoch85 could you test pr #11204? https://github.com/nextcloud/server/pull/11204.patch
