### ISSUE TITLE
occ db:add-missing-indices - Exact steps to resolve?

### ISSUE THREAD

**Issue by opgailey** [nextcloud/server#11167]
Hi all,

I've just updated by NC 13 server to NC 14 using the built in updater.

'Security & Set Up Warnings' is reporting: _Missing index "fs_mtime" in table "oc_filecache"_

It is telling me to run 'occ db:add-missing-indices' and according to the the NC 13 documentation the specific command is: **sudo -u www-data php occ db:add-missing-indices**
https://docs.nextcloud.com/server/13/admin_manual/configuration_server/occ_command.html#database-add-indices-label

When I run this command via CLI as ncadmin I get the following response: _Could not open input file: occ_

Any ideas? Am I running this command from the wrong place? Can someone detail the exact steps / commands required to resolve this _Missing index "fs_mtime" in table "oc_filecache"_ issue?

I am a Linux beginner so apologies if the answer is obvious.

Many thanks.

**Comment by JonasT** [comment]
Did you try running this command inside your nextcloud main install folder? (Where there's the files `index.php`, `remote.php`, the `occ` folder, ...) It worked there for me

**Comment by opgailey** [comment]
@JonasT Oh dear. No I didn't. I was running it from the wrong location. :/

Apologies for that. I have run the command and it has worked perfectly. 

Thanks for your help.

**Comment by nickvergessen** [comment]
This should be discussed in https://github.com/nextcloud/server/issues/11491

**Comment by ddi98** [comment]
Thanks a lot to everyone for the availability!
You could provide more details on how to perform queries (for those who are not a web expert like me)

**Comment by necesitod** [comment]
To fix it I made like root (Without ")  "sudo -u www-data php ./occ add-missing-indices" on Debian GNU/Linux 11 (bullseye)
