### ISSUE TITLE
macOS only files get synced with size 0 bytes

### ISSUE THREAD

**Issue by blacs30** [nextcloud/server#11176]
### Steps to reproduce
1. Upload folder with fonts (Adobe PS Fonts) either via the WebUI or the macOS Nextcloud client
2. On the Mac the file is viewable but in the webui and on other Macs where this file should get synced to the file size is 0 bytes and is not recognized as a font file any longer

### Expected behaviour
I expect the file to be the same on the other sync clients

### Actual behaviour
The file size is 0 and it does not have any content.

### Server configuration

**Operating system**:
macOS 10.13.6

**Web server:**
Nginx

**Database:**
MariaDB

**PHP version:**
7.0.x

**Nextcloud version:** (see Nextcloud admin page)
13.5 / 14.0 (tested on both)

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded but also tested on fresh installed

**Where did you install Nextcloud from:**
github repo / official docker 

I can sync the files with _dropbox_ but it does currently not work with Nextcloud which I'd prefer to use, of course. There are no errors in the logs.
The problem is probably how the files are synced? On the Mac the file appears to have 0 bytes when I do an `ls -lah`, when I `cat` the file it is empty.

However xattr shows the attributes the file has
```
xattr AlberMT
com.apple.FinderInfo
com.apple.ResourceFork
com.apple.lastuseddate#PS
```

And xattr -l shows me the content
```
com.apple.FinderInfo:
00000000  4C 57 46 4E 41 53 50 46 21 40 00 00 00 40 00 00  |LWFNASPF!@...@..|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020
com.apple.ResourceFork:
00000000  00 00 01 00 00 00 81 42 00 00 80 42 00 00 01 5A  |.......B...B...Z|
00000010  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000020  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000030  07 41 6C 62 65 72 4D 54 02 00 00 00 4C 57 46 4E  |.AlberMT....LWFN|
00000040  41 53 50 46 21 00 00 00 00 40 00 00 00 01 55 42  |ASPF!....@....UB|
00000050  00 00 4C 57 46 4E 41 53 50 46 21 00 00 00 00 40  |..LWFNASPF!....@|
00000060  00 00 15 23 00 00 00 00 00 00 00 00 00 00 00 00  |...#............|
00000070  00 00 A4 C5 C7 87 00 00 00 00 00 00 82 9C 00 00  |................|
00000080  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000090  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
000000A0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
000000B0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
000000C0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
000000D0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
000000E0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
000000F0  00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  |................|
00000100  00 00 04 6C 01 00 25 21 50 53 2D 41 64 6F 62 65  |...l..%!PS-Adobe|
00000110  46 6F 6E 74 2D 31 2E 30 3A 20 41 6C 62 65 72 74  |Font-1.0: Albert|
00000120  75 73 4D 54 20 30 30 31 2E 30 30 30 0D 25 25 43  |usMT 001.000.%%C|
00000130  72 65 61 74 69 6F 6E 44 61 74 65 3A 20 57 65 64  |reationDate: Wed|
00000140  20 41 75 67 20 20 37 20 31 33 3A 35 37 3A 31 34  | Aug  7 13:57:14|
00000150  20 31 39 39 31 0D 25 25 56 4D 75 73 61 67 65 3A  | 1991.%%VMusage:|
00000160  20 32 39 37 38 31 20 33 36 36 37 33 0D 25 25 20  | 29781 36673.%% |
[...]
```

I attached one zipped example file where this behavior occurs. 
[AlbertusMT.zip](https://github.com/nextcloud/server/files/2372118/AlbertusMT.zip)

I couldn't find same bugs (or would this be an enhancement) created?

**Comment by cmcotte** [comment]
We have the same problem. Part of our fonts (PostScript Type 1) do not synchronize correctly. The files and folders are there, but the size is 0 bytes. Only on the original computer the size is correct. It's very urgent, hour team members rely on the synchronization.

**Comment by blacs30** [comment]
Created the issue in the [Desktop repo]https://github.com/nextcloud/desktop/issues/805)

**Comment by blacs30** [comment]
I think the solution for me is to convert the fonts.
The fonts originally come from Mac OS 9.
I found these guides:
[https://michaelprewitt.com/2015/09/converting-mac-postscript-type-1-suitcase-fonts-2294/](https://michaelprewitt.com/2015/09/converting-mac-postscript-type-1-suitcase-fonts-2294/)

[https://apple.stackexchange.com/questions/8455/how-do-i-convert-a-suitcase-font/200074#200074](https://apple.stackexchange.com/questions/8455/how-do-i-convert-a-suitcase-font/200074#200074)
