### ISSUE TITLE
Safari shows high CPU load

### ISSUE THREAD

**Issue by helmut72** [nextcloud/server#11179]
### Steps to reproduce
1. Login to Nextcloud
2. Wait

### Expected behaviour
Safari is in idle mode when nothing happens

### Actual behaviour
Safari on macOS 10.13.6 shows high CPU load

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache2

**Database:** MariaSQL

**PHP version:** 7.2

**Nextcloud version:** 14.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Web-Updater

**List of activated apps:**
Shouldn't be the problem

**Are you using external storage, if yes which one:** local, smb

**Are you using encryption:** no

### Client configuration
**Browser:** Safari

**Operating system:** macOS 10.13.6

#### Web server error log

No log. I do nothing. Only being logged in.

#### Browser log

I see some lines like this:
```
[324 <private> stream, pid: 33527, url: https://my.nextcloud.domain/ocs/v2.php/apps/notifications/api/v2/notifications, tls] cancelled
	[324.1 BB809A76-3379-4FC8-BE86-F7F9DC8C4630 <private>.50637<-><private>]
	Connected Path: satisfied (Path is satisfied), interface: en0, ipv4, dns
	Duration: 6.359s, DNS @0.000s took 0.010s, TCP @0.013s took 0.011s, TLS took 0.005s
	bytes in/out: 866/1404, packets in/out: 8/8, rtt: 0.010s, retransmitted packets: 0, out-of-order packets: 0
```

<img width="706" alt="bildschirmfoto 2018-09-11 um 21 58 18" src="https://user-images.githubusercontent.com/1388751/45385419-fae76200-b610-11e8-9b78-f0e3cc2fe9be.png">

**Comment by hunter-nl** [comment]
I Do not have high CPU load, But OSX Safari complains about significant energy usage. Safari shows the following above the nextcloud webpage after I logged in. 

![image](https://user-images.githubusercontent.com/5203309/45391308-bd8bd000-b622-11e8-9d6a-859c8af0f7d6.png)

Any page of my nextcloud 14 or nextcloud app or admin settings page result in this high energy consumption. With Nextcloud 13 this issue was not there.

**Comment by helmut72** [comment]
yes, get this image too after some time.

**Comment by jinyu121** [comment]
Same here.

![](https://user-images.githubusercontent.com/5203309/45391308-bd8bd000-b622-11e8-9d6a-859c8af0f7d6.png)

Just logging into NextCloud and wait about 3 minutes.

(Mining? emmmm...🤔)

**Comment by kevin147147** [comment]
If you look in safari web inspector > timelines. Do a record with the red button. You'll see styles invalidated and styles recalculated. This constant load draws performance. It was not there on nc 13. I think its because of the style change in nc 14.

**Comment by nickvergessen** [comment]
cc @skjnldsv

**Comment by MorrisJobke** [comment]
Let me bisect this one.

**Comment by MorrisJobke** [comment]
This seems to be the one: 8977c71f8842f19077fdd0bfe27a4f48f2bc4726 (checking out the parent fixes the issue).

@skjnldsv Do you have any idea what is happening here? Does the `@include` cause some weird side effects?

**Comment by MorrisJobke** [comment]
This commit also causes this behavior on Safari (I guess this is the reason or the high CPU load):

Turning off the browser cache it will re-request all SVGs infinitely - could be one symptom of the re-rendering.

Before (232 requests in total):

![bildschirmfoto 2018-10-08 um 14 52 58](https://user-images.githubusercontent.com/245432/46610302-a4cfe680-cb0a-11e8-8736-3192b16ba2e7.png)

After (3,1K but counts up):

![bildschirmfoto 2018-10-08 um 14 56 42](https://user-images.githubusercontent.com/245432/46610327-bca76a80-cb0a-11e8-8c44-765098b560fd.png)

This is the request (you can see there the 6,4k requests):

![bildschirmfoto 2018-10-08 um 14 57 00](https://user-images.githubusercontent.com/245432/46610335-c16c1e80-cb0a-11e8-9e74-a16b718183c3.png)

**Comment by skjnldsv** [comment]
Oups, forgot to remove the fix keyword!

**Comment by skjnldsv** [comment]
This is coming from the variables, I did not have the time to investigate yet :(
We're not the only one using css4 variables, I'm wondering how YouTube is doing on safari :confused:

**Comment by MorrisJobke** [comment]
> This is coming from the variables, I did not have the time to investigate yet :(
> We're not the only one using css4 variables, I'm wondering how YouTube is doing on safari 😕

So this is only because the CSS4 variable contains a base64 image? Maybe there is a threshold we are passing?

**Comment by skjnldsv** [comment]
No, this is because we have css4 variables containing urls apparently, base64 doesn't change the issue :(

**Comment by jeeves64** [comment]
Disappointed this is been pushed back again (to 14.0.5, currently due by 10/01/19), this was never an issue in NC13 and makes safari pretty much unusable 😕

**Comment by MorrisJobke** [comment]
> Nextcloud 14.0.3

You need to upgrade to 14.0.5 at least, because the fix was added there.

**Comment by pillaib** [comment]
Hi,

Thanks, I upgraded to latest 15.x.
Now looks better, have to test for few days.

Regards,

Badri

**Comment by rawtaz** [comment]
Can those who had this problem please report back with whether or not this is still an issue with the latest stable release of Nextcloud? If the problem is no longer reproducible I suggest that this issue be closed.
