### ISSUE TITLE
"Deleted files" pane is visually rather confusing if I forgot I clicked that - because nothing indicates it in the breadcrumbs

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#11170]
This is a minor UI issue but it just confused me a lot and made me file an invalid bug (already closed by now):

The "Deleted files" pane is visually rather confusing if I forgot I clicked that - because nothing indicates it in the breadcrumbs. Basically, it is really easy to end up in the "Deleted files" view, forget about it, and then be *very confused* because it looks from the breadcrumbs like you're looking at your home, except all the files listed are wrong and there is no "plus" button to add files anymore.

### Steps to reproduce
1. Click "Deleted files" entry at the bottom left
2. Examine breadcrumbs which look the same as if in the home folder, with no indication of the deleted files pane

### Expected behaviour
Clear indication in the breadcrumbs pane I'm in a deleted files view and not a regular view,

### Actual behaviour
Absolutely no indication I can see *(edit: just noticed there is a tiny blue marker at the left of "Deleted files" in the corner, but it's extremely easy to miss)*. As a result, if I don't remember I went into deleted files or look at the URL, I might think I'm in a regular folder

### Server configuration

**Operating system**: official nextcloud docker image, ubuntu host

**Web server:** as in official nextcloud docker image

**Database:** latest mariadb docker image

**PHP version:** `PHP/7.1.18`

**Nextcloud version:** `13.0.4`

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** docker image

(other details left out because this seems like a UI design issue, not a technical bug of sorts. If this is relevant let me know and I'll add it)

**Comment by szaimen** [comment]
I think this is fixed in the meantime -> closing.
