### ISSUE TITLE
User List Not Shown If Any User Has Numeric ID

### ISSUE THREAD

**Issue by tabp0le** [nextcloud/server#11178]
### Steps to reproduce
1. Create user with numeric ID
2. Go to userlist
3. Fail

### Expected behaviour
User list should display

### Actual behaviour
User list does not display

### Server configuration

**Operating system**: CentOS 7

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 14.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official release zip

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
PHP TypeError: Argument 1 passed to OCA\Provisioning_API\Controller\AUserData::getUserData() must be of the type string, integer given, called in /var/www/sprycloud/http/apps/provisioning_api/lib/Controller/UsersController.php on line 180 at /var/www/sprycloud/http/apps/provisioning_api/lib/Controller/AUserData.php#81
```
</details>

This commit fixes the issue: https://github.com/nextcloud/server/pull/11157/commits/3d566dd5aeaf26b8e9d78d17545c27612690895f

**Comment by nickvergessen** [comment]
Thanks for your report, you can try https://github.com/nextcloud/server/pull/11181 and see if it fixes the issue?

**Comment by Lartza** [comment]
#11181 works for me
