### ISSUE TITLE
This server has no working Internet connection

### ISSUE THREAD

**Issue by aktavor69** [nextcloud/server#1118]
Hi,

I have this message on my admin panel 

> This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

> 

Probably because the owncloud certificate on https://owncloud.org is ended - 28/08/2016 , so there is an error.
May be you need to change the site on check connection module

**Comment by Jusix** [comment]
:+1: funny message while connection to my nextcloud instance through the internet :D

**Comment by Echse27** [comment]
I have the same message in admin panel... But all functions working well...

**Comment by thiesschneider** [comment]
I had the same message and restarted my server. Now the message is gone :)

**Comment by ctlui** [comment]
Same here and gone after reboot of the server.
Debian Jessie + apache 2.4 + php 5.6

**Comment by rullzer** [comment]
This is all on NC9? or also on NC10?

**Comment by Echse27** [comment]
It was on NC 10... 
But also here, after rebooting the server, the message gone.

**Comment by aktavor69** [comment]
Message gone without reboot after few hours

NC 10 too

**Comment by rullzer** [comment]
I tought we adjusted that test. CC: @LukasReschke ?

**Comment by LukasReschke** [comment]
Only master has the new logic: https://github.com/nextcloud/server/blob/3647fbe7cd86e743b059889d69b03fcf8207780f/settings/Controller/CheckSetupController.php#L97-L112

So Nc 11 will have this properly addressed.
