### ISSUE TITLE
We want to cancel hard code index.php and modify routing.

### ISSUE THREAD

**Issue by jack9603301** [nextcloud/server#11188]
It is hoped that the hard coded index.php will change the route, so that URL routing will be more beautiful.

**Comment by weeman1337** [comment]
Thanks for creating the issue. @jack9603301 could you give some more information please?  
What is the system doing in your case? And how do you wish it should do?

**Comment by jack9603301** [comment]
I want to arrange URL routing more scientifically and rationally, rather than having a string like `index. php`in the URL routing, which seems more reasonable, otherwise, we'll have to solve this problem by nginx + ob_start handler + modifying some system files, which will become cumbersome and may cause other problems.

**Comment by danielkesselberg** [comment]
https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#pretty-urls does this help? When u use the recommended nginx (https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html) configuration index.php is removed from most visible urls.

**Comment by jack9603301** [comment]
I've temporarily removed the display of index. PHP on the URL by technical means, but I'd prefer to remove this hard-coded routing from the source code

**Comment by danielkesselberg** [comment]
Could you be more specific what hard-coded routing you are referring to? Its pretty common to route all requests through index.php (most frameworks for php works this way). Please let me know if I misunderstood you.

**Comment by jack9603301** [comment]
The default routing for Nextcloud is sure to have `index. php'in the URL, but it's not beautiful. I want to go somewhere in the middle of the URL `index. php'. For example, the default routing for Nextcloud is: 
```
http://cloud.qhjack.cn/index.php/apps/files/?Dir=/&fileid=7
```
We hope that similar routing paths, such as `index.php', will not appear in the middle of the path, but more scientific and reasonable routing should be as follows:
```
http://cloud.qhjack.cn/apps/files/?Dir=/&fileid=7
```

**Comment by danielkesselberg** [comment]
https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#pretty-urls (you need to use the recommended nginx configuration). It does work on my local setup like you suggested.

![image](https://user-images.githubusercontent.com/3902676/45573663-a12fa380-b86d-11e8-9ee5-baaa69c0bfa8.png)

**Comment by jack9603301** [comment]
How to configure on nginx.

**Comment by danielkesselberg** [comment]
We manage software issue with nextcloud here. Please use https://help.nextcloud.com/ for configuration issues. You find the recommended nginx configuration here: https://docs.nextcloud.com/server/13/admin_manual/installation/nginx.html

**Comment by jack9603301** [comment]
However, in Nextcloud, a large number of paths still use `index.php`, such as:
![20180915051346](https://user-images.githubusercontent.com/9047180/45575468-377fbb80-b8a6-11e8-889e-65cdb74f10c6.png)

**Comment by danielkesselberg** [comment]
:+1: Looks like you have configured beautiful urls for your nextcloud. Do you want me to reopen this issue? Could you provide (please edit your first post to keep this clear) more information about your use case and why the remaining links to index.php are a problem for you?

**Comment by jack9603301** [comment]
Part of the URL links and routing styles can be solved by adding the `overwrite. cli. url` field to the `config.php` master configuration file, but a large number of links can still be found in the Nextcloud that have not been converted to new links.

**Comment by danielkesselberg** [comment]
@MorrisJobke @jospoortvliet reopen?

**Comment by MorrisJobke** [comment]
Usually https://docs.nextcloud.com/server/13/admin_manual/installation/source_installation.html#pretty-urls should cover all of the requested stuff. Then Nextcloud will generate only the needed URLs as wanted. Could you check that?

**Comment by jack9603301** [comment]
Who do you want to talk to?

**Comment by MorrisJobke** [comment]
> Who do you want to talk to?

Most likely you, as you have the problem. Did you followed the steps in there? Could you also check if there is a trailing slash in the override.cli.url if it only consists of the domain - something like "https://cloud.example.com/"?

**Comment by jack9603301** [comment]
I checked the corresponding configuration records of config.php:

```
'overwrite.cli.url' => 'http://cloud.qhjack.cn/'
```

**Comment by Nottt** [comment]
Why is there no documentation on how to do this with nginx? :/

I have `'overwrite.cli.url' => 'https://domain.com'` in my `config.php` and I still `php.index` everywhere.

**Comment by MorrisJobke** [comment]
> Why is there no documentation on how to do this with nginx? :/

If you use the config for Nginx that is in our documentation this should work. If not: reach out in the forums.

**Comment by Nottt** [comment]
Your documentation is missing the header `add_header Referrer-Policy no-referrer always;` to pass your own audit. 

And it worked, after I fixed the issue where it couldn't find the cgi params file. You should also add there that this link will give pretty URL, remove `index.php` because when we are googling it doesn't even show up as a possible solution to the issue...
