### ISSUE TITLE
Problems with "digital" usernames

### ISSUE THREAD

**Issue by olegbolden** [nextcloud/server#11197]
1. Create user with any digital username, for example 5555

### Expected behaviour
A user with digital username should be added

### Actual behaviour
On submit you will get error (bad request) and all users became inaccessible from USERS menu item ("no users in here")
As a consequence, on sharing any file or folder you will see two instances of the same user with "digital" username - with email address and without it.

![problem](https://user-images.githubusercontent.com/18537369/45452285-3ef86680-b6e6-11e8-8ff2-3438d6ed2c56.png)

Users with regular usernames have the only instance to select from dropdown list upon object sharing.

### Server configuration

**Operating system**:
Linux Debian Jessie

**Web server:**
Nginx+PHP-FPM and Apache+CGI

**Database:**
MySQL

**PHP version:**
7.0.25 and 7.1.20

**Nextcloud version:** (see Nextcloud admin page)
14.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.6

The problem with users disappearing can be solved by removing hinting from getUserData method signature in abstract class /apps/provisioning_api/lib/Controller/AUserData.php:

`81	protected function getUserData(string $userId): array {`
change to 
`81	protected function getUserData($userId): array {`

The problem with duplicating of the same user with "digital" username when sharing objects is to be solved as yet.

**Comment by danielkesselberg** [comment]
Looks similiar to https://github.com/nextcloud/server/issues/11178. Does https://github.com/nextcloud/server/pull/11181 fix your issue as well?

**Comment by olegbolden** [comment]
> Looks similiar to #11178. Does #11181 fix your issue as well?

Oh, yeah. 
It fixes my issue though duplication of username in dropdown selector remains. 
This duplication is another bug and may be it is related to "digital" usernames.

**Comment by olegbolden** [comment]
An update
Everything what I've described above is happened in Mozilla Firefox.
Now I'm testing in Chromium and everything works fine!
Apparently, FF caching or somewhat else messes things up.

**Comment by danielkesselberg** [comment]
Could you close this issue then?

**Comment by olegbolden** [comment]
Yes, I will.
Though duplicating of one account on selecting users as depicted above still persists.
I'll create another issue to point this out.
