### ISSUE TITLE
Missing Referrer-Policy Header in Docker Image

### ISSUE THREAD

**Issue by k1ngf15h3r** [nextcloud/server#11195]
I think the recommended Referrer-Policy header should be added by default in the Webserver config inside the Docker image

**Comment by danielkesselberg** [comment]
Thank you for reporting this issue :+1:  Could you please report it at https://github.com/nextcloud/docker and close this issue here?

**Comment by k1ngf15h3r** [comment]
Move to nextcloud/docker
