### ISSUE TITLE
"Get your own free account"

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#11198]
Hey guys!

Since Nextcloud 14 I noticed you worked a lot on the marketing side of Nextcloud, great stuff! I find it a bit intrusive though.

If it's my own cloud then I would decide what I want or not, or do you disagree? At the same point I understand that you need the marketing stuff to grow, but things like this for example would be nice to opt out from:

![screenshot from 2018-09-13 07 34 13](https://user-images.githubusercontent.com/4511254/45468911-6facc000-b727-11e8-813c-9cb34daefb5b.png)

Would you add that like an option to the theme app or something, or did I miss that you already can opt out for it?

I think it can be misunderstood like "aah I can get a free account on cloud.xyz.com, but when you click it it's for Owncube.

Thanks for all your hard work! :+1:

**Comment by danielkesselberg** [comment]
See #11101

**Comment by Oclair** [comment]
this issue is far from closed, any event of updating it returns

**Comment by kesselb** [comment]
Please read https://github.com/nextcloud/server/issues/11101

I am not aware of any automatic reset for this config option. If you disable it once through `config.php` it's disabled.
