### ISSUE TITLE
Can't limit applications access to groups into the 14 version 

### ISSUE THREAD

**Issue by CDFem** [nextcloud/server#11190]
### Steps to reproduce
1. Open Apps Menu
2. I can't find any group limitation checkbox

### Expected behaviour
In the 13 version, it was possible to limit an application access by group : 
![image](https://user-images.githubusercontent.com/43204115/45421851-b4d0e380-b68e-11e8-94cc-8758a81e9269.png)

### Actual behaviour
In the 14 version, the possibility no more exists.

### Server configuration

**Operating system**: Debian 8 

**Web server:** Apache/2.4.10

**Database:** mysql  Ver 15.1 Distrib 10.0.32-MariaDB

**PHP version:** PHP 7.0.31-1~dotdeb+8.1

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** manual upgrade from a 13 version

**Where did you install Nextcloud from:** website download

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox 61.0.1 (64 bits)

**Operating system:** Ubuntu 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by supercoil** [comment]
If you click on the app, you'll get a tab to the right that includes the checkbox

**Comment by CDFem** [comment]
Hi,
Ok, i found it. The way to limit access change in the latest version.
Thanks for the tip.
