### ISSUE TITLE
2FA: skip selection screen if there's only one active provider for the user

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#1120]
To improve the 2FA log in UX, it would be nice to skip the 2FA provider selection screen if there's only one active provider for the user. Instead of the selection, we'd directly redirect users to their active 2FA provider's challenge screen.

ref https://github.com/ChristophWurst/twofactor_totp/issues/49#issue-173663146

cc @jancborchardt @LukasReschke @zkvvoob

**Comment by bahhumbug** [comment]
If #1108 is implemented, would it ever be the case anymore that only one 2FA provider is active?

(and thanks for your great work on 2FA providers)

**Comment by ChristophWurst** [comment]
> If #1108 is implemented, would it ever be the case anymore that only one 2FA provider is active?
> 
> (and thanks for your great work on 2FA providers)

Yes, it would, because we'd ignore the backup codes provider when counting active providers for a user.

**Comment by bahhumbug** [comment]
My apologies in advance, because I believe I must not be understanding an important detail.   Let's say I have a U2F provider enabled, and then I accidentally lose my yubikey (woops!).  If this feature skips the selection screen for the backup provider, how would I tell the system that I want to get back in via one of the backup codes?

**Comment by ChristophWurst** [comment]
From #1108
> The backup code provider should not be listed like other providers, but should be a link on the bottom next to the "Cancel log in" link. Something like "Use backup code".

That means that you'll see the U2F page, which has a "Cancel log in" and "Use backup code" link that you can click, which will redirect you to the backup code provider.
