### ISSUE TITLE
Developer question about cookie management (Thunderbird/Lightning)

### ISSUE THREAD

**Issue by jobisoft** [nextcloud/server#11209]
I am currently investigating some lightning issues when users want to connect multiple calendars from the same server but from different users. Lightning fails on that, because it can store only one session cookie per server and thus all connections to the same server will use the same session, but access content from different users, which does not work.

The only way to get around this is to enable a global option to reject all cookies. Now lightning will authenticate each connection and ignores sessions. I guess this increases the load on the auth module of the nextcloud server. Are there any other drawbacks?

Is it worth working on the lightning cookie store to be able to store a session cookie per user/server combination? Is nextcloud actually maintaining different sessions for different users on the same endpoint?

The answer to this will have a great impact on how to fix this issue in lightning.

**Comment by jobisoft** [comment]
To be more precise:

Is it worth working on the lightning cookie store to be able to store a session cookie per user/server combination? Is nextcloud actually maintaining different sessions for different connections from the same endpoint but for different authenticates users?

**Comment by jobisoft** [comment]
ok, I tested with curl and was able to get two different cookies for two different users. I filed a bug at mozilla to get this fixed.

**Comment by j-ed** [comment]
@jobisoft I think this is a well-know trap of Thunderbird. You need to set `calendar.network.multirealm = true` in Thunderbird to be able to fetch multiple calendars from different users from a single server.

**Comment by jobisoft** [comment]
But that does not work with digest auth and i am tired of this long standing stupid bug. 

Problem: The bug is in mozilla-central which is outside of Thunderbirds reach. But they accepted the bug report and we are currently negotiating how to fix this.
