### ISSUE TITLE
Login problems with conflicting usernames in database/LDAP, even with unique mail

### ISSUE THREAD

**Issue by Janfred** [nextcloud/server#11210]
### Steps to reproduce
1. Create an Database User with username `foobar` and mail `foobar@example.com`
2. Configure LDAP login
3. Create an LDAP-User with username `foobar` and mail `somethingdifferent@example.com`
4. Try to login with `foobar@example.com` and use the password for the LDAP user

### Expected behaviour
Since `foobar@example.com` is a unique Identifier for the database backend user `foobar` the credentials should be checked against the database, which (if the passwords differ) should result in an auth failure.

### Actual behaviour
The credentials are checked against the LDAP Backend and I'm logged in as LDAP-User `foobar`

I've seen in `core/Controllers/LoginController.php:255` the method to get a username by a mail if the standard login fails. If an explicit user (with an explicit login source) is found in this way it should definitely be used. Currently the LoginController just calls the function `$this->userManager->checkPassword` which again checks all database backends if the user exists and exits on the first fit of the username, even if the login fails.

### Server configuration

**Operating system**:
Debian 9

**Web server:**
apache2

**Database:**
mysql

**PHP version:**
php 7.0.30-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)
13.9

**Updated from an older Nextcloud/ownCloud or fresh install:**
Tested with updated 13.8 and 13.9

**Where did you install Nextcloud from:**
Release .tgz

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.6.1                                                                                                                                                                     [0/1715]
  - admin_notifications: 1.0.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.1
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - encryption: 2.0.0
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_external: 1.4.1
  - files_external_dropbox: 1.0.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0 
  - impersonate: 1.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - mail: 0.8.3
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0 
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - tasks: 0.9.7
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - twofactor_u2f: 1.5.5
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - user_saml: 1.5.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain"
        ],  
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain",
        "dbtype": "mysql",
        "version": "13.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    },      
    "apps": {
[...]
       "user_ldap": {
            "_lastChange": "1536871087",
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "has_memberof_filter_support": "",
            "installed_version": "1.3.1",
            "ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "ldap_base": "dc=my,dc=domain",
            "ldap_base_groups": "ou=Group,dc=my,dc=domain",
            "ldap_base_users": "ou=People,dc=my,dc=domain",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_display_name": "cn",
            "ldap_dn": "***REMOVED SENSITIVE VALUE***",
            "ldap_email_attr": "mail",
            "ldap_experienced_admin": "0",
            "ldap_group_filter": "(&(|(objectclass=posixGroup)))",
            "ldap_group_filter_mode": "0",
            "ldap_group_member_assoc_attribute": "memberUid",
            "ldap_groupfilter_objectclass": "posixGroup",
            "ldap_host": "***REMOVED SENSITIVE VALUE***",
            "ldap_login_filter": "(&(|(objectclass=inetOrgPerson))(uid=%uid))",
            "ldap_login_filter_mode": "0",
            "ldap_loginfilter_email": "0",
            "ldap_loginfilter_username": "1",
            "ldap_port": "636",
            "ldap_user_filter_mode": "0",
            "ldap_userfilter_objectclass": "inetOrgPerson",
            "ldap_userlist_filter": "(|(objectclass=inetOrgPerson))",
            "types": "authentication"
        },
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
Enabled, but I'm not using it

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP, Shibboleth(unconfigured)

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+---------------------------------------------+
| Configuration                 |                                             |
+-------------------------------+---------------------------------------------+
| hasMemberOfFilterSupport      |                                             |
| hasPagedResultSupport         |                                             |
| homeFolderNamingRule          |                                             |
| lastJpegPhotoLookup           | 0                                           |
| ldapAgentName                 | ***                                         |
| ldapAgentPassword             | ***                                         |
| ldapAttributesForGroupSearch  |                                             |
| ldapAttributesForUserSearch   |                                             |
| ldapBackupHost                |                                             |
| ldapBackupPort                |                                             |
| ldapBase                      | ***                                         |
| ldapBaseGroups                | ou=Group,dc=***                             |
| ldapBaseUsers                 | ou=People,dc=***                            |
| ldapCacheTTL                  | 600                                         |
| ldapConfigurationActive       | 1                                           |
| ldapDefaultPPolicyDN          |                                             |
| ldapDynamicGroupMemberURL     |                                             |
| ldapEmailAttribute            | mail                                        |
| ldapExperiencedAdmin          | 0                                           |
| ldapExpertUUIDGroupAttr       |                                             |
| ldapExpertUUIDUserAttr        |                                             |
| ldapExpertUsernameAttr        |                                             |
| ldapGidNumber                 | gidNumber                                   |
| ldapGroupDisplayName          | cn                                          |
| ldapGroupFilter               | (&(|(objectclass=posixGroup)))              |
| ldapGroupFilterGroups         |                                             |
| ldapGroupFilterMode           | 0                                           |
| ldapGroupFilterObjectclass    | posixGroup                                  |
| ldapGroupMemberAssocAttr      | memberUid                                   |
| ldapHost                      | ***                                         |
| ldapIgnoreNamingRules         |                                             |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                             |
| ldapLoginFilterEmail          | 0                                           |
| ldapLoginFilterMode           | 0                                           |
| ldapLoginFilterUsername       | 1                                           |
| ldapNestedGroups              | 0                                           |
| ldapOverrideMainServer        |                                             |
| ldapPagingSize                | 500                                         |
| ldapPort                      | 636                                         |
| ldapQuotaAttribute            |                                             |
| ldapQuotaDefault              |                                             |
| ldapTLS                       | 0                                           |
| ldapUserAvatarRule            | default                                     |
| ldapUserDisplayName           | cn                                          |
| ldapUserDisplayName2          |                                             |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))              |
| ldapUserFilterGroups          |                                             |
| ldapUserFilterMode            | 0                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                               |
| ldapUuidGroupAttribute        | auto                                        |
| ldapUuidUserAttribute         | auto                                        |
| turnOffCertCheck              | 0                                           |
| turnOnPasswordChange          | 0                                           |
| useMemberOfToDetectMembership | 1                                           |
+-------------------------------+---------------------------------------------+
```
</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
Debian

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing relevant logged
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing relevant logged
```
</details>

**Comment by Janfred** [comment]
> [GitMate.io](https://gitmate.io) thinks possibly related issues are #11197 (Problems with "digital" usernames), #5187 (LDAP users can't be deleted and can still login while marked as deleted in Database), #1995 (LDAP-Import with field mail ), #9494 (mail attribute not synced from LDAP/AD before first login), and #7606 (LDAP login attributes not updating.).

Don't think any of this is related.

**Comment by Janfred** [comment]
I've written a very very ugly patch for this issue (I know this is absolutely nothing that should be merged, but to get an idea what the problem with the current implementation is it should be fine)

**Comment by MorrisJobke** [comment]
This looks weird - maybe @blizzz can have a look why this happens.

**Comment by blizzz** [comment]
@Janfred why would an authentication against LDAP with the other email and the password work? It's not even configured to check against the mail address. In the patch $specific_backend  is always null, because the given $loginName is a string, not a backend class, so the condition is always true.

**Comment by Janfred** [comment]
It actually really does check against LDAP.

In [core/Controller/LoginController.php:300](https://github.com/nextcloud/server/blob/02de67773c5ce1e38a90ce45b60ce249ed9a4042/core/Controller/LoginController.php#L300) the user is determined by the mail address.  
Since my local user `foobar` with mail address `foobar@example.com` tries to login, the return of the function `getByEmail` is the user object for my local user.

But when checking the credentials again in [core/Controller/LoginController.php:304-306](https://github.com/nextcloud/server/blob/master/core/Controller/LoginController.php#L304-L306) the information about the user object is thrown away and just the determined username is passed to the `checkPassword` function.

Since I have a user with username `foobar` in my LDAP and the LDAP is checked before the local database the credentials are now checked against the LDAP `foobar` credentials, although I've entered the mail Adress for the local `foobar` account.

In my patch I've changed the [LoginController.php](https://github.com/Janfred/nextcloud-server/blob/cf8c6e4cb8d2b7f00e2233c112aad0dd1079dbfe/core/Controller/LoginController.php#L303), so they pass the user object instead of just the username. (One of the reasons why my patch is so horrible)

```
- $previousUser = $user;
- $user = $users[0]->getUID();
- if($user !== $previousUser) {
-         $loginResult = $this->userManager->checkPassword($user, $password);
- }
+ $loginResult = $this->userManager->checkPassword($users[0], $password);
```

**Comment by aignerat** [comment]
I looked up another issue with ldap_user_count but I think I know your problem. To my mind you misunderstood the concept of ldap-usermanagement in nextcloud. When you configure ldap, all users of the configured group/-s are loaded as new users in nextcloud, if you want to migrate local users you have to use a occ files:transfer-ownership to get the data from the local user to the ldapuser. nextcloud has no functionality to "automigrate" as far as i know. Another good hint is to use sAMAccountname for referencing. If you use other values it can happen that you have "user" and "user_1234" and "user_2345" when you change the ou of a user especially when you use uniquemember.

**Comment by Janfred** [comment]
@aignerat: Please, don't misunderstand me! I am totally aware that creating a user with the same username on a different backend is not the way to migrate users. This was never my use case.
I did want to migrate to LDAP, but not direct but by copying the data from my local to my LDAP account.

The problem is the following:
Preconditions:
You have an account with username `user`, password `local` and mail `local@example.com` in the internal database.
You have a second account with username `user`, password `ldap` and mail `ldap@example.com` in the LDAP.
Behavior:
You can login with `user:ldap` into your LDAP account, the internal account is not accessible with `user:local`
This is totally the behavior you could expect, nextcloud shouldn't try out all user databases until one accepts the password of the user.
You can login with `ldap@example.com:ldap` into your LDAP account.
This is also the expected behavior.
You can't login with `local@example.com:local` into your local account.
This is the behavior which is the problem. Nextcloud does an internal search for the mail address and translates it to the corresponding username, and retries the authentication as if the username was typed in instead of the mail address in the first place. This doesn't work if a username exists twice in two different authentication backends. I am totally aware of the fact, that having two users with the same username in different authentication backend is a bad practice and it is very rarely happening, but I'd still classify this as a major bug in the login process that you can login with a username-password combination which was never meant to work and a clearly unique combination (which `local@example.com:local` definitely is, because no other user has the mail address `local@example.com` in my case) does not work.

**Comment by aignerat** [comment]
I'm pretty sure you can't have 2 Users with the same name, when i had a local user on v13+ and added a ldap-backend where users had the same name i had user @ local and user_1234 @ ldap. How did you manage to have the same UUID?

**Comment by aignerat** [comment]
sure, that's why you have to migrate the local userdata to the ldap-user. then you can delete the local user. You need to do serveral sql-queries for storages, shares and activities if needed. As allready mentioned occ files:transfer-ownership is the way to go to bring together 2 users to one, but it only "copies" the files, don't forget occ files:scan afterwards.

**Comment by Janfred** [comment]
@aignerat You misunderstood me AGAIN!
Please read my comment before telling me that I can't migrate that way. That is not my target!
The problem is not the migration, the problem is that nextcloud does an internal lookup for the mail address to get the username, then discards all information it gathered about the user but the username and does the authentication with the username. I'd assume that the information in what user database the mail address was found was carried to the password checking, but it isn't.

**Comment by aignerat** [comment]
ok you changed the login to mail-address. I honestly never used that and that's why I didn't think about that possibility, I always use username as login. I had ldapusers with the same mail as local users and the login worked. I have a test-server with mail-login but didn't test ldap there. I still don't get the problem, do you want to keep the local user and the ldap user with the same name as seperated users? That scenario is far from any dsgvo-convention but ok as long as you use it privately. Btw. I maybe still don't get the problem correctly that was just my next guess.

**Comment by Janfred** [comment]
I'll write a comment this evening explaining the problem with direct references to the code.

**Comment by Janfred** [comment]
Sorry for the delay. The problem is the following:

| | Local | LDAP |
|---|---|---|
| Username | `user` | `user` |
| Password | `pwLOCAL` | `pwLDAP` |
| Mail | `local@example.com` | `ldap@example.com` |

I try to login with `local@example.com` and `pwLOCAL`.

This is the trace the login follows:
* The function `tryLogin($user=>'local@example.com', $password => 'pwLOCAL', ...)` of `core/Controller/LoginController.php` is called. See here: [core/Controller/LoginController.php:283](https://github.com/nextcloud/server/blob/fce1ddc04e0ec7253fb34ebdff5f6161e96c4d2a/core/Controller/LoginController.php#L283)
* In Line 313 the Login is tried by using `$user` as username, which fails, because the mail address is not the username.
* In Line 315 the list of users with the mail address `local@example.com` is retrieved. Since I have only one user with this mail address in my databases the check for the length of the list in Line 317 passes.
* **Here is the Problem:** In Line 320 the UID of the user is written in the `$user` variable and used for a password check in Line 321. 
  * The `$users[0]->getUID()` returns in this case `user`. But it is just the username, and all references to where the user was found (in this case the local database) is discarded.
  * In Line 321 the check is now `$this->userManager->checkPassword($user=>'user', $password=>'pwLOCAL')`, but since LDAP is checked first, it checks against the LDAP user `user`, and the password check fails.
  * If I had typed in `pwLDAP` in the first place, I had been able to login to my LDAP account with a mail address which does not belong to my account.

I hope this helps understanding the problem.

In my eyes the main problem is, that when looking up the mail address in Lines 314-324 the information in which user backend the mail address was found is completely discarded. It should be passed to the `checkPassword`-Function, so the function can check the password only in this backend.

**Comment by aignerat** [comment]
ok now I get it, in most software-solutions it's not possible to have 2 users with the same email-address. Allthough it would be technically possible to split ldap and local users with the same email-address for seperated login. If I understood you correct, the username is the same, but that doesn't change a lot to the scenario, it would be possible to add "backendtype" to the login. 

I still don't get the idea why you want to use 2 users for 1 person. As I allready said, I'd migrate the local user to ldap. It's totally bad to my mind, to have 2 repositories for your data when you could have one.

If you really want to go on with this path I'd just rename all local users to "user_local" or "userlocal", then you would need no change in the code. It's absolute worst-practice to have duplicated usernames in a system.

**Comment by Janfred** [comment]
It is definitely absolute worst-practice if you have full control over all backends, but it can happen. (It has happened in my case accidentally and I had to do quite a lot investigation until I found the issue.)
My problem is that the login with mail address seems in this case to behave incorrectly. I even could imagine a scenario where you would allow users of different backends to login into your nextcloud (e.g. 5 different oauths, local ldap, internal admin accounts) which could lead to duplicate username situations, since you don't have full control over all backends.

**Comment by aignerat** [comment]
Yeah, you're right there are scenarios where 20 different LDAPs are connected and usernames are duplicated, but there is no easy workaround for this. The users are both from the backend "LDAP" so you have no chance but the email to get any difference, even with code-based changes you wouldn't have solved the problem in a good way. Such big installations with thousands of users could use federated servers to bypass the problem. Still it would involve likelihood of confusion.

In your case I'd still migrate the local users to the ldap-users. What is your gain of having 2 Users for 1 person? I had the same scenario serveral times and we always migrated local users to the ldapusers. A simple migration is just a copy of the data-folder and a file:scan afterwards on each user to build the file-cache.

**Comment by Janfred** [comment]
The fix for this is quite trivial:
Introduce a new function in the UserManager for the password check which takes a user object instead of the username as argument. In my ugly fix I have overloaded the `checkPassword` function to also accept user objects, but it would be trivial to add a new function which then checks only the backend where the mail address was found

**Comment by aignerat** [comment]
I think this is stale too, but I understand that max.mustermann can work for 2 companies with the same e-mail-address. In this case there could be a problem. I think this issue isn't a bug but an enhancement/feature-request.

**Comment by Janfred** [comment]
It becomes a serious bug at the moment when the first max.mustermann account has the same password as the second one. It is very unlikely, but i still think the information in what user database the user was found should be passed to the password checking function if a lookup was done.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by aignerat** [comment]
it's a possible security-problem, nothing really serious, at least on v19 it's still valid, still not many users should run into this issue

**Comment by szaimen** [comment]
cc @nextcloud/security

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
