### ISSUE TITLE
Share not working on http connection

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11215]
- share a folder to another user on same server
--> Connection could not be established with host 127.0.0.1 [Connection refused #111]
- BUT: the share is correctly added

Android is also affected https://github.com/nextcloud/android/issues/3014

- current master
- http connection

--> this does not happen if I have httpS connection

**Comment by MorrisJobke** [comment]
> * share a folder to another user on same server

Do you mean a federated share?

**Comment by tobiasKaminsky** [comment]
> Do you mean a federated share?

No, within the same instance, e.g. tobi -> admin and both are on http://localhost/nc

**Comment by MorrisJobke** [comment]
What has this then to do with the http/https?

**Comment by tobiasKaminsky** [comment]
I tried it with my local and productive NC14 setup.
Local gave above error and productive worked.
And my only difference is that one has https.

But yes, I have no idea if this is related at all

**Comment by tensberg** [comment]
As noted in https://github.com/nextcloud/android/issues/3014#issuecomment-433339884 the error seems to occur if no email server is configured. Apparently Nextcloud 14 always sends a mail to the persons you're sharing with, see #11216

**Comment by tobiasKaminsky** [comment]
I think with latest versions I do not have this problem any longer.
