### ISSUE TITLE
Email notifications can not be stopped

### ISSUE THREAD

**Issue by olegbolden** [nextcloud/server#11216]
1. Email notifications on sharing files or folders don't stop even if this option is unchecked in personal settings (Events tab).

### Expected behaviour
Mails are not sent anymore

### Actual behaviour
Mails continue come to users

### Server configuration

**Operating system**:
Linux Debian Jessie

**Web server:**
Nginx+PHP-FPM

**Database:**
MySQL

**PHP version:**
7.1.20

**Nextcloud version:** (see Nextcloud admin page)
14.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.6

**Comment by MorrisJobke** [comment]
cc @nextcloud/sharing

**Comment by MorrisJobke** [comment]
> I'd just like to know if this bug will be fixed in 14.0.2?

No - this is more how it was designed. The options to disable emails is only for activity emails. The sharing email is just sent always and can't be turned off for now.

**Comment by olegbolden** [comment]
Oh, really...
Thank you for such an info.
By the way, even your support members from help.nextcloud.com are not aware of this.

**Comment by MorrisJobke** [comment]
> No - this is more how it was designed. The options to disable emails is only for activity emails. The sharing email is just sent always and can't be turned off for now.

@tflidd @rakekniven JFYI ;)



> By the way, even your support members from help.nextcloud.com are not aware of this.

Whom specifically? And those are often also just community people. Not everyone can know everything ;) Maybe point them to my answer here.

**Comment by xylo** [comment]
@olegbolden OK, so it's not a bug.  But can we reopen this issue please, because these mails can be very annoying when coming in masses.  There should be some option to disable this kind of "spam" mails.

**Comment by kkzinger** [comment]
Today I also ran into this problem. Please reopen and consider this function as a feature.

**Comment by Nils160988** [comment]
If you need to share many files, maybe you can share a folder once instead of many single files or use groupfolders. That might be the easier (or at least faster) option.

**Comment by GammaPi** [comment]
Also request this feature for privacy issue. Please reopen and consider this function as a feature.

**Comment by GammaPi** [comment]
@MorrisJobke

**Comment by pc-robelbois** [comment]
I am removing the SMTP configuration of our Nextcloud ONLY because we dont want the damn notification email. Feels bad.

Email notification settings are so basic it's hard to call it a feature but... "Please implement that feature" :)

**Comment by tflidd** [comment]
Could it go in here as an option to not send at all:
https://github.com/nextcloud/server/issues/15736

If not feel free to open a new topic. You can link this, make a feature request for something new, we can then tag it as enhancement.

**Comment by chaosgrid** [comment]
Why has this issue been closed? You cannot be serious that this is by design. In certain setups, a fat finger could cause an automatic email to be sent to a whole organization and there is no way to turn this off short of disabling email alltogether.

**Comment by dajiahao** [comment]
> No - this is more how it was designed. The options to disable emails is only for activity emails. The sharing email is just sent always and can't be turned off for now.

very annyoing those spam messages, so the only solution is to remove the smtp configuration? 
@pc-robelbois thanks for the idea, just removed the smtp config too

**Comment by JB1985** [comment]
Still in 18.0.4.

Will the bug(feature?) be fixed or not?

**Comment by liejuntao001** [comment]
I decided to remove the smtp config for now...

**Comment by MagelanM** [comment]
The problem is **still present** in Nextcloud 22.2.5.
That means that the settings are not working. The user decided by the settings, that he will not get an email notification for new shares. But this has no effect.
This is not the decision of the user who creates the share as mentioned in #15736.

Please reopen the issue.

**Comment by rakekniven** [comment]
@MagelanM This issue is outdated because it was filed for NC14.

Pleasen open a new one and add all necessary information. At NC14 there was no option to disable email notifications for share actions.
