### ISSUE TITLE
14.0.0.19 Hover over User Quota doesn't show used space anymore

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#11217]
### Steps to reproduce
1. As Admin go to Users an hover over the quota

### Expected behaviour
Up to NC 13 there was shown the used space in the Hoverbox:
![hover-nc-13](https://user-images.githubusercontent.com/5583290/45549569-8f77dd00-b828-11e8-88f1-3bc493fe7a4a.jpg)

### Actual behaviour
No hover-box with used space is shown:
![hover-nc-14](https://user-images.githubusercontent.com/5583290/45549609-ab7b7e80-b828-11e8-879a-3889f5e72eec.jpg)

### Server configuration
Tested on different servers.

**Comment by JSoko** [comment]
Persists in 14.0.1.1...

**Comment by MorrisJobke** [comment]
cc @skjnldsv
