### ISSUE TITLE
Password input time for admin reaproval to short

### ISSUE THREAD

**Issue by nextgen-networks** [nextcloud/server#11224]
When changing settings for nextcloud via web interface the timeframe is to short to type in ma password.
This happens if an session exists a couple of time and reaproval of credentials is forced.

In case you have an very long (and hopefully a secure) password the timeframe to type in exeeds an you face an error message.
This feature has been introduced in NC14.

I've found no option to extend the timeframe for the password input in the web interface.

Please make it configureable.

**Comment by Gatak** [comment]
Was just having the same issue when doing it from the phone. It's very difficult to type a long password in time.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/master/settings/src/store/api.js#L89 indeed. 7 seconds are a bit short.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @skjnldsv

**Comment by MorrisJobke** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
> We need to migrate to https://github.com/ChristophWurst/nextcloud-password-confirmation/blob/master/confirmation.js

I think the problem is that the code times our at the wrong layer. There should be a timeout, but on the password confirmation dialogue itself. This timeout error should be propagated to the code that requested password confirmation.

Otherwise you still see the password confirmation dialogue, but the code that requested it might already have considered it as timed out and the callback leads to undefined behavior.

**Comment by skjnldsv** [comment]
@ChristophWurst if we use `await` or `.then` it should be fine, right?

**Comment by ChristophWurst** [comment]
No, because `OC.PasswordConfirmation.requirePasswordConfirmation` only resolves on success and never rejects on error/timeout.

**Comment by skjnldsv** [comment]
@ChristophWurst Ah, I thought you worked around this.
This is the time where we need our modal component, right? :)

**Comment by ChristophWurst** [comment]
Either that or adjust the existing code :wink:

**Comment by FlorianFranzen** [comment]
So let me get this straight: I can only update my apps if I am being able to type my password within seven seconds (as the occ command does not support updating apps, #8773)?

What is the purpose of a timeout in the first place? What is gained by timing out the dialog?

**Comment by TheNomad11** [comment]
Still not fixed?

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/40bb45225a42a48cd9d090e7540f1a8d3986df63/settings/src/store/api.js#L89 is the only place where `requirePasswordConfirmation` is used with a timeout in nextcloud\server. Why is there a timeout for password confirmation in this place? @skjnldsv  @ChristophWurst

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/commit/f33065523d7850d0722282e42f15cae0504a7097#diff-176813153209ad865076f526b3568ae1R65 @skjnldsv  :eyes:

**Comment by skjnldsv** [comment]
@ChristophWurst yes, we just need to migrate to your solution or to nextcloud-axios?

**Comment by danielkesselberg** [comment]
Is there a technical reason why you need the timeout here? Could you just drop it and use it like anywhere else in nextcloud\server?

**Comment by skjnldsv** [comment]
> Is there a technical reason why you need the timeout here? Could you just drop it and use it like anywhere else in nextcloud\server?

Yes there is a valid reason behind.
And yes we can drop by using another implementation

**Comment by ChristophWurst** [comment]
> @ChristophWurst yes, we just need to migrate to your solution or to nextcloud-axios?

Well, https://www.npmjs.com/package/nextcloud-password-confirmation does just call `OC.PasswordConfirmation.requirePasswordConfirmation` and never resolves if the user does not enter a correct password. https://www.npmjs.com/package/nextcloud-axios is unrelated to this issue.

**Comment by skjnldsv** [comment]
> > > Is there a technical reason why you need the timeout here? Could you just drop it and use it like anywhere else in nextcloud\server?
> > 
> > 
> > Yes there is a valid reason behind.
> 
> Care to explain what is the reason? I suppose myself and others dont exactly see the point of it.

Of course :)
It was a technical issue because I did not found a proper way to use an asynchronous callback on the password confirmation and we had to set a limit for the script to wait for the dialog to resolve instead of directly use the user input to detect if the user did something. With @ChristophWurst's implementation it will be all fixed! :hugs:

**Comment by Scorry** [comment]
And, finally, how to disable this behavior?

**Comment by ChristophWurst** [comment]
> [skjnldsv](/skjnldsv) moved this from **To do** to **Priorities (up next)** in [Skjnldsv's Tasks](/orgs/nextcloud/projects/10#card-13367443) [2 days ago](#event-1958359320)

Thanks :raised_hands:

**Comment by MorrisJobke** [comment]
Will be shipped with 14.0.4
