### ISSUE TITLE
occ command throws exception: TypeError: realpath() null given

### ISSUE THREAD

**Issue by svenmauch** [nextcloud/server#11239]
### Steps to reproduce
1. connect to managed webhosting server with ssh
2. change to nextcloud directory
3. run any occ command

### Expected behaviour
occ command should execute without errors, in this case add missing db indexes.

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/24568451/45595078-6715ed00-b9a6-11e8-9cf8-78ca8950bbdf.png)

### Server configuration

**Operating system**: Linux 3.14.x-grsec

**Web server:** Apache 2.4.x

**Database:** MySQL 5.6.x

**PHP version:** 7.2.x

**Nextcloud version:** 14.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from latest 13.x via web updater

**Where did you install Nextcloud from:** installed via web installer (setup-nextcloud.php) downloaded from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
"Files Right Click" and "Tasks" are the only non-official apps enabled.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => '*****',
  'passwordsalt' => '*****',
  'secret' => '*****',
  'trusted_domains' => 
  array (
    0 => '*****',
  ),
  'datadirectory' => '*****/cloud/data',
  'overwrite.cli.url' => '*****/cloud',
  'dbtype' => 'mysql',
  'version' => '*****',
  'dbname' => '*****',
  'dbhost' => '*****',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '*****',
  'dbpassword' => '*****',
  'installed' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => '*****',
  'maintenance' => false,
  'knowledgebaseenabled' => false,
  'overwritehost' => '*****',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/cloud',
  'forwarded_for_headers' => 
  array (
    0 => 'CF_CONNECTING_IP',
  ),
  'tempdirectory' => '*****',
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'updater.secret' => '*****',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'ssl',
  'mail_smtphost' => '*****',
  'mail_smtpport' => '*****',
  'mail_smtpname' => '*****',
  'mail_smtppassword' => '*****',
);
</details>

**Are you using external storage:** no

**Are you using encryption:** no

**Are you using an external user-backend:** no

### Client configuration
**Browser:** Firefox 62

**Operating system:** Microsoft Windows 10 (1803)

#### Web server error log
<details>
<summary>Web server error log</summary>
cannot access
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
empty
</details>

#### Browser log
<details>
<summary>Browser log</summary>
doesn't apply
</details>

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by svenmauch** [comment]
I recently upgraded to Nextcloud 15.0.0 for which the admin panel is suggesting I run the following commands:

- occ db:add-missing-indices
- occ db: convert-filecache-bigint

The error above persists and outputs the same exception for both commands. Running php with command line argument -C yields the same result.

**Comment by danielkesselberg** [comment]
Could you share php -v? The content-type and status header only printed when PHP is running as CGI. CLI would be the right one for occ.

**Comment by svenmauch** [comment]
Darn, I can't believe I've missed this for months! After finding and running the weirdly placed binary for php-cli everything works just fine.

I guess this issue can be closed if there's no need for an exception handler for idiots like me. :)

**Comment by danielkesselberg** [comment]
No worries :sunglasses: In the first place this is a bad server configuration placing a cgi-fcgi binary where you would expect a cli binary.
