### ISSUE TITLE
CalDAV Mail Invitations: Bogus Invite/Accept upon deleted person

### ISSUE THREAD

**Issue by labor4** [nextcloud/server#11230]
A cosmetic issue

### Steps to reproduce (I did via caldav Apple Calendar on Mac)
1. Create Event 
2. Invite person A
2b. Accept/Decline by that person.
3. Delete person A

The following is what that person A gets in an email.

### Expected behaviour
Just a note the person has been kicked out

### Actual behaviour
The note, plus:
Additionally there are still the the "Accept" "Decline" Buttons.

### Server configuration
NC 14.0.0

**Comment by MorrisJobke** [comment]
cc @georgehrke

**Comment by brad2014** [comment]
Note: This is true for any iMip cancel message, which is not only triggered by deleting an invitee from an event, but also from deleting the event.

**Comment by brad2014** [comment]
Also, the email says "The meeting <title> with <organizer> was canceled."  That is not the semantics of an iTip CANCEL message.  It should say that the *invitation* was withdrawn/canceled for the recipient (the meeting itself may or may not have been canceled, or the recipient may have been removed from the attendee list by the organizer).  Also meetings are not *with* the organizer, they are *by* the organizer.  Person A can organize a meeting between person B and person C.

Better:  "The invitation for <title> by <organizer> has been canceled."

**Comment by georgehrke** [comment]
Fixed in #12392
