### ISSUE TITLE
Remember settings in user management

### ISSUE THREAD

**Issue by geotheory** [nextcloud/server#11233]
The options in the settings menu - e.g. "Show last login" are resetting to being unchecked upon logging out and back in. Running NC 14.0.0 on Ubuntu 16.04 with Apache 2.4.18.  Apps running Talk, Circles, File right-click menu, News, Group folders.

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
@geotheory it is remembered on my instance.
Maybe you've disabled the localstorage or your browser doesn't support it?

**Comment by geotheory** [comment]
OK the problem now seems to have gone away. Thanks anyway.

**Comment by bpcurse** [comment]
@skjnldsv Could we please reopen this issue? I have encountered precisely the same problem as described above.

NC 14.0.4.2 upgraded from 13.0.8, shared webhosting Server with limited ssh access (not much config info available except for: Linux 4.4.0-139-generic x86_64, php 7.1.23, mysql 5.7.21, 100+ users, 73 apps)

What further info do you need? Can I actively investigate somehow?

**Comment by blizzz** [comment]
@bpcurse 

> What further info do you need? 

I guess same as he asks in https://github.com/nextcloud/server/issues/11233#issuecomment-425126004

**Comment by bpcurse** [comment]
@blizzz I'm not sure if I understand it correctly. "localstorage" means the browser? So the setting is saved in the browser, not in the nextcloud instance?

**Comment by blizzz** [comment]
Exactly
