### ISSUE TITLE
Spelling mistake in german translation

### ISSUE THREAD

**Issue by lkn94** [nextcloud/server#11241]
### Steps to reproduce
1. Switch to german translation (Deutsch (Persönlich: Du))
2. Go to personal info
3. Take a look at the groups

### Expected behaviour
Translation should be:

Gruppen
Du bist Mitglied folgender Gruppen:

### Actual behaviour
As you can see the german translation is: 

Gruppen
Du bist Miglied folgender Gruppen:

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server**: Apache

**Database**: MySQL (5.7.23)

**PHP version**: 7.2.7

**Nextcloud version:** (see Nextcloud admin page) 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.0.5 (there was also the spelling mistake)

**Where did you install Nextcloud from:** Web Installer

**Signing status:**

**Comment by danielkesselberg** [comment]
Thank you for reporting this +1 Translations are synced daily from transifex. Please join at https://www.transifex.com/nextcloud/nextcloud/dashboard/ to help with translations

**Comment by JSoko** [comment]
Thank you for reporting. I've fixed it.
https://www.transifex.com/nextcloud/nextcloud/translate/#de/$/145522875?q=translation_text%3Amiglied
