### ISSUE TITLE
Reboot Ubuntu Server and Nextcloud didn't 'run

### ISSUE THREAD

**Issue by lopnax** [nextcloud/server#11266]
### Steps to reproduce
1. Reboot Ubuntu Server
2. Start Apache2 (check its running with service apache2 status)
3. Start mysql service (check its running with service mysql status)

### Expected behaviour
Running nextcloud normally when I start apache2 and mysql service.

### Actual behaviour
Only see the apache2 website when I visit my IP and cant see anything when I visit the website domain where I pointed my public IP.

### Server configuration

**Operating system**:
Ubuntu Server 18.04.1 LTS

**Web server:**
[https://lopezdrive.tk](https://lopezdrive.tk)

### Question
It's possible to run all automatically at the startup?

First time creating a server 😅

**Comment by tomtomas99911** [comment]
Of course,
just enable services for mysql and apache2.
"systemctl enable myslq"
"systemctl enable apache2"

**Comment by lopnax** [comment]
> ### Steps to reproduce
> 1. Reboot Ubuntu Server
> 2. Start Apache2 (check its running with service apache2 status)
> 3. Start mysql service (check its running with service mysql status)
> 
> ### Expected behaviour
> Running nextcloud normally when I start apache2 and mysql service.
> 
> ### Actual behaviour
> Only see the apache2 website when I visit my IP and cant see anything when I visit the website domain where I pointed my public IP.
> 
> ### Server configuration
> **Operating system**:
> Ubuntu Server 18.04.1 LTS
> 
> **Web server:**
> https://lopezdrive.tk
> 
> ### Question
> It's possible to run all automatically at the startup?
> 
> First time creating a server 😅

- [x] I solved one of the problem, apache2 its creating conflicts. When apache2 is running the server can't show me the login page of nextcloud.

- [ ] Any solution to run apache2 and nextcloud simultaneously or maybe I don't need to start apache2 to show other websites?

**Comment by Quinity** [comment]
How are you running your Nextcloud instance? Via Docker or is it a local installation? 
If it's the latter, normally if no web server is running, then requests should be denied at all.
