### ISSUE TITLE
Version control indefinitely for certain files.

### ISSUE THREAD

**Issue by githubtefo** [nextcloud/server#11263]
Hi,

Is there any way to change the behaviour of version control? I'd like to maintain **all** the versions for certain important files (particularly .org files for emacs org-mode), without the automatically expiration of old versions.

Thank you in advance,
Stéfano.-

**Comment by szaimen** [comment]
I think you are looking for `D, auto`
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#file-versions

**Comment by githubtefo** [comment]
> I think you are looking for `D, auto` or `disabled`
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#file-versions

Hi @szaimen , thanks for your reply.
I think those parameters applies for all files; I wanted to disable version deletion for a specific file.
