### ISSUE TITLE
Can't assign tags to files

### ISSUE THREAD

**Issue by milu-milu** [nextcloud/server#11267]
### Steps to reproduce
1-  Choose info from one file that has no tags.
2- Apply (or create a new tag) and assign to it.
3- Choose another file without tags.
4- Click on "Tags", nothing happens.

### Expected behaviour
It should open again the TAG's chooser.

### Actual behaviour
Nothing happens when you click on Tags.
If the file already has tags you can edit them without problem.

## Server configuration detail

**Operating system:** Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64

**Webserver:** Apache/2.4.25 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 9.6.10 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516, 64-bit

**PHP version:** 

7.2.9-1+0~20180910100512.5+stretch~1.gbpdaac35
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, json, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.0 - 14.0.0.19

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Downloaded from Nextcloud

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - admin_notifications: 1.0.2
 - announcementcenter: 3.3.0
 - bruteforcesettings: 1.1.0
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dav: 1.6.0
 - deck: 0.4.1
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_accesscontrol: 1.4.0
 - files_automatedtagging: 1.4.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - groupfolders: 1.3.3
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_ldap: 1.4.0
 - workflowengine: 1.4.0
Disabled:
 - dashboard
 - encryption
 - files_external
 - user_external

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "<FQDN>"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "14.0.0.19",
    "overwrite.cli.url": "http:\/\/<FQDN>\/files",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0
    },
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
cleanUpJobOffset: 50enabled: yesinstalled_version: 1.4.0s01_lastChange: 1536908474s01has_memberof_filter_support: 1s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: TWVyY3VyaWFuYTIwMTA=s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: DC=base,DC=locals01ldap_base_groups: DC=base,DC=locals01ldap_base_users: DC=base,DC=locals01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displayNames01ldap_dn: CN=Administrator,CN=Users,DC=base,DC=locals01ldap_dynamic_group_member_url: s01ldap_email_attr: s01ldap_experienced_admin: 0s01ldap_expert_username_attr: s01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: (&(|(objectclass=group)))s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: uniqueMembers01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: groups01ldap_host: 192.168.120.101s01ldap_login_filter: (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))s01ldap_login_filter_mode: 0s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 1s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 0s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: persons01ldap_userlist_filter: (&(|(objectclass=person)))s01use_memberof_to_detect_membership: 1s02_lastChange: 1536843722s02has_memberof_filter_support: 1s02home_folder_naming_rule: s02last_jpegPhoto_lookup: 0s02ldap_agent_password: TWVyY3VyaWFuYTIwMTA=s02ldap_attributes_for_group_search: s02ldap_attributes_for_user_search: s02ldap_backup_host: s02ldap_backup_port: s02ldap_base: DC=base,DC=locals02ldap_base_groups: s02ldap_base_users: s02ldap_cache_ttl: 600s02ldap_configuration_active: 1s02ldap_default_ppolicy_dn: s02ldap_display_name: displayNames02ldap_dn: CN=Administrator,CN=Users,DC=base,DC=locals02ldap_dynamic_group_member_url: s02ldap_email_attr: s02ldap_experienced_admin: 0s02ldap_expert_username_attr: s02ldap_expert_uuid_group_attr: s02ldap_expert_uuid_user_attr: s02ldap_gid_number: gidNumbers02ldap_group_display_name: cns02ldap_group_filter: (&(|(objectclass=group)))s02ldap_group_filter_mode: 0s02ldap_group_member_assoc_attribute: uniqueMembers02ldap_groupfilter_groups: s02ldap_groupfilter_objectclass: groups02ldap_host: 192.168.120.102s02ldap_login_filter: (&(&(|(objectclass=person)))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid))))s02ldap_login_filter_mode: 0s02ldap_loginfilter_attributes: s02ldap_loginfilter_email: 1s02ldap_loginfilter_username: 1s02ldap_nested_groups: 0s02ldap_override_main_server: s02ldap_paging_size: 500s02ldap_port: 389s02ldap_quota_attr: s02ldap_quota_def: s02ldap_tls: 0s02ldap_turn_off_cert_check: 0s02ldap_turn_on_pwd_change: 0s02ldap_user_avatar_rule: defaults02ldap_user_display_name_2: s02ldap_user_filter_mode: 0s02ldap_userfilter_groups: s02ldap_userfilter_objectclass: persons02ldap_userlist_filter: (&(|(objectclass=person)))s02use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** Debian GNU/Linux 9.5

## Logs

<details><summary>Browser log</summary>

```
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
files
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
unreachable code after return statement[Learn More]
merged.js:1498:4
window.controllers/Controllers is deprecated. Do not use it for UA detection.
merged.js:2176
New search handler registered
search.js:66:4
querying Whats New data was successful: nocontent
merged-template-prepend.js:4478:4
undefined
merged-template-prepend.js:4479:4
Navigated to http://pc08088.base.local/files/index.php/apps/files/
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
files
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
unreachable code after return statement[Learn More]
merged.js:1498:4
window.controllers/Controllers is deprecated. Do not use it for UA detection.
merged.js:2176
New search handler registered
search.js:66:4
querying Whats New data was successful: nocontent
merged-template-prepend.js:4478:4
undefined
merged-template-prepend.js:4479:4
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
files
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Deprecated API usage: PDFJS.openExternalLinksInNewWindow, please use "PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK" instead.
util.js:288:2
Password fields present on an insecure (http://) iframe. This is a security risk that allows user login credentials to be stolen.[Learn More]
files_pdfviewer
#Close is undefined.
l10n.js:831:6
#Close is undefined.
l10n.js:903:6
#close_label is undefined.
l10n.js:831:6
#close_label is undefined.
l10n.js:903:6
PDF 320c4cddae6aa56d7308fef09ba99d44 [1.5 pdfTeX-1.40.16 / LaTeX with hyperref package] (PDF.js: 1.9.426)
app.js:1078:6

```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"J8xwL9wD3H8j9LZvbnK1","level":3,"time":"2018-09-18T07:21:31+00:00","remoteAddr":"127.0.0.1","user":"admin@local","app":"PHP","method":"GET","url":"\/files\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/html\/files\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"14.0.0.19"}

```
</details>

<details><summary>Browser log</summary>

Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
files
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
unreachable code after return statement[Learn More]
merged.js:1498:4
window.controllers/Controllers is deprecated. Do not use it for UA detection.
merged.js:2176
New search handler registered
search.js:66:4
querying Whats New data was successful: nocontent
merged-template-prepend.js:4478:4
undefined
merged-template-prepend.js:4479:4
Navigated to http://pc08088.base.local/files/index.php/apps/files/
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Password fields present on an insecure (http://) page. This is a security risk that allows user login credentials to be stolen.[Learn More]
files
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
unreachable code after return statement[Learn More]
merged.js:1498:4
window.controllers/Controllers is deprecated. Do not use it for UA detection.
merged.js:2176
New search handler registered
search.js:66:4
querying Whats New data was successful: nocontent
merged-template-prepend.js:4478:4
undefined
merged-template-prepend.js:4479:4
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing.
files
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Deprecated API usage: PDFJS.openExternalLinksInNewWindow, please use "PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK" instead.
util.js:288:2
Password fields present on an insecure (http://) iframe. This is a security risk that allows user login credentials to be stolen.[Learn More]
files_pdfviewer
#Close is undefined.
l10n.js:831:6
#Close is undefined.
l10n.js:903:6
#close_label is undefined.
l10n.js:831:6
#close_label is undefined.
l10n.js:903:6
PDF 320c4cddae6aa56d7308fef09ba99d44 [1.5 pdfTeX-1.40.16 / LaTeX with hyperref package] (PDF.js: 1.9.426)
app.js:1078:6

</details>

**Comment by olegbolden** [comment]
I've noticed that tags are active only once after page reload.
If you added or selected tag for one object you can not do it for the next object without page reload.

**Comment by milu-milu** [comment]
You're right.

If I choose an already existing TAG I can't assign to a second object.

But if I create a new one even when I refresh the webpage I can't assign more.

With an already existing TAG I can refresh and assign the TAG to another object. I must refresh page each time I need to add a TAG.

Thanks,

**Comment by violoncelloch** [comment]
I can confirm this behaviour on NC 14.0.1
cc @nextcloud/javascript

**Comment by violoncelloch** [comment]
cc @nextcloud/javascript
could someone have a look at this?

**Comment by blizzz** [comment]
Dup of https://github.com/nextcloud/server/issues/10774
