### ISSUE TITLE
Problem with GuzzleHttp

### ISSUE THREAD

**Issue by olegbolden** [nextcloud/server#11278]
Can not open file with Collabora Office (local docker installation)
Collabora online application version is 2.0.13 (richdocuments)

### Expected behaviour
Office format file is opened within Nextcloud window

### Actual behaviour
In case WOPI server field is blank in the settings of the Collabora online (fresh install of this app) we have
`Fatal error: Cannot declare class GuzzleHttp\Handler\CurlFactory, because the name is already in use in /var/www/.../3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 16`

In case WOPI server field is filled in:
`Fatal error: Cannot declare class GuzzleHttp\Exception\RequestException, because the name is already in use in /var/www/.../3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php on line 0`

I suspect that there is no proper connection between nextcloud and Collabora Office in docker container and this causes the last Error.

**Operating system**:
Linux Debian Jessie

**Web server:**
Nginx+PHP-FPM

**Database:**
MySQL

**PHP version:**
7.1.20

**Nextcloud version:**
14.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 13.6

**Comment by olegbolden** [comment]
I found the origin of the problem.
You need to specifiy IP-address of collabora online server explicitly in nginx ssl section like this:

`listen xxx.xxx.xxx.xxx 443 ssl;`

In most internet instructions with nginx reverse proxy settings including [collabora](https://www.collaboraoffice.com/code/) this `listen` directive is specified as

`listen 443 ssl;`

The second error (Cannot declare class GuzzleHttp\Exception\RequestException) appears due to invalid sertificate if IP is not specified. 
Our webserver and nextcloud installation run in LXC Proxmox container with ISPmanager panel. Hope this info helps those who works in the same environment.

Nonetheless I think that the above errors should be properly processed to help nextcloud administrators in Collabora online installation rather then go in blind.

**Comment by apocolocyntos** [comment]
Having the same issue all day long I finally found out that my self-signed certificate was the problem. While my Browser knows the full chain of a letsencrypt certificate the internal curl function of nextcloud does not. Copying the fullchain certificate to my nginx-container solved the Problem.

**Comment by joshp23** [comment]
Having this issue with Nextcloud 14.0.3 updated from 13, Collabora Online (richdocuments) 3.0.1, Ubuntu 16.04, PHP 7.0, Apache.

Using Letsencrypt certs, declaring ip (not `*`) in `Listen` directive and `VirtualHost` conf.
Error:
`PHP Fatal error:  Cannot declare class GuzzleHttp\\Exception\\RequestException, because the name is already in use in /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Exception/RequestException.php on line 0`

**Comment by joshp23** [comment]
Solved! it was an expired certificate for the loolwsd server. Going to update the settings in loolwsd server instead of the hack I did when I set it up ;) Hope this helps someone in a similar spot.

**Comment by danielkesselberg** [comment]
Thank you for reporting back :+1:

**Comment by plepps** [comment]
I had the same issue - in my case it was because my NC was not a native subdomain. "https://server.foo.bar/nc"
I changed NC to run on this URL "https://nc.foo.bar" and start a new collabbora docker with this new domain and it works perfectly now!

**Comment by joshp23** [comment]
this came back after updating to collabora 6.0.0 in NC 14.0.4
All certificates / settings are appropriate and up to date

**Comment by jodoe** [comment]
@joshp23 - I have exactly the same problem since updating from the repo, I had a perfectly working NC14 install until then. Did you manage to resolve yours?

> 
> 
> this came back after updating to collabora 6.0.0 from repo while using collabora NC app v 3.1.0 in NC 14.0.4
> All certificates / settings are appropriate and up to date

**Comment by joshp23** [comment]
@jodoe I snooped about [here](https://www.collaboraoffice.com/code/linux-packages/) paying attention to step 4, and [here](https://www.collaboraoffice.com/code/nginx-reverse-proxy/) paying attention to option 2. 

Therefore, to get it working I updated the config script at `/etc/loolwsd/loolwsd.xml` to contain new options in 6.0 update, then set `net.listen=loopback` for security reasons as I then set `ssl.enable=false`, and `ssl.termination=true`. I made sure that the reverse proxy in Nginx is calling plain all addresses such as `http://localhost:9980;` and so forth. Restarted loolwsd and it worked for me!

**Comment by jodoe** [comment]
@joshp23 thanks for the reply, it ended up being the lo_template_path, it wasn't pointing at collaboraoffice6.0, as it was still using the old config file, it was pointing at collaboraoffice5.3. I changed this and everything's working again :)

**Comment by joshp23** [comment]
@jodoe right on. Glad you mentioned that point. That was the first option that I u reset as well, only it did not result in a functional environment, which happened only after I completed the above steps.

Glad that you got things working.

**Comment by apiraino** [comment]
In my case the problem was a misconfiguration of the Collabora virtualhost. The error `Cannot declare class GuzzleHttp\Handler\CurlFactory` was pretty obscure but I've found better clues on the `nextcloud.log` file.

(hth)
