### ISSUE TITLE
"Note to recipient" API

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11270]
This was introduced in NC14.
Ideally when such features are developed, where clients may benefit from, please also ping the client teams.

Now the question, how can I add this into client? Are there already public API/endpoints?

**Comment by weeman1337** [comment]
@tobiasKaminsky you mean the file sharing, right?
Just send the `note` request data. Could you please try if that works for you?

![image](https://user-images.githubusercontent.com/6216686/45811013-5928da80-bccc-11e8-8175-e64b72dfe7f4.png)
![image](https://user-images.githubusercontent.com/6216686/45811020-5cbc6180-bccc-11e8-9fea-40d753b20dff.png)

**Comment by weeman1337** [comment]
I opened some PRs to get it into the documentation.

There is a changelog for developers: https://nextcloud.com/blog/changes-for-developers-in-nextcloud-14-beta-4-ready-for-testing/

But it's missing the share note info :(
@rullzer is it possible to add it afterwards?

**Comment by tobiasKaminsky** [comment]
@weeman1337 thank you for the hint.

This is a sample curl to put a note to a share:

```
curl --request PUT \
  --url 'https://server.com/nextcloud/ocs/v2.php/apps/files_sharing/api/v1/shares/624?note=%22test123%22' \
  --header 'authorization: Basic 123==' \
  --header 'ocs-apirequest: true'
```

**Comment by tobiasKaminsky** [comment]
@weeman1337 for me this issue can be closed.
Can you maybe link the PR for documentation here and then close the issue.

**Comment by weeman1337** [comment]
@tobiasKaminsky the documentation PRs are linked above.
When they're merged they will close this issue here.

**Comment by rullzer** [comment]
Docs merged.
