### ISSUE TITLE
occ is slow and doesn't support an internal batched mode

### ISSUE THREAD

**Issue by robert-scheck** [nextcloud/server#11275]
As of Nextcloud 14.0.0, `occ` is still slow and it also does not support an internal batched mode or similar:

```
$ time ./occ --no-interaction app:disable richdocuments
richdocuments disabled

real	0m0.714s
user	0m0.537s
sys	0m0.166s
$ 
```

```
$ time ./occ --no-interaction app:enable richdocuments
richdocuments enabled

real	0m0.933s
user	0m0.627s
sys	0m0.188s
$ 
```

```
$ time ./occ --no-interaction app:disable password_policy
No such app enabled: password_policy

real	0m0.736s
user	0m0.561s
sys	0m0.160s
$ 
```

```
$ time ./occ --no-interaction maintenance:update:htaccess
.htaccess has been updated

real	0m0.727s
user	0m0.555s
sys	0m0.158s
$ 
```

```
$ time ./occ --no-interaction background:cron
Set mode for background jobs to 'cron'

real	0m0.717s
user	0m0.534s
sys	0m0.172s
$ 
```

```
$ time ./occ --no-interaction maintenance:mode --off
Maintenance mode already disabled

real	0m0.848s
user	0m0.645s
sys	0m0.190s
$ 
```

```
$ time ./occ --no-interaction integrity:check-core  

real	0m2.395s
user	0m1.716s
sys	0m0.643s
$ 
```

```
$ time ./occ --no-interaction db:add-missing-indices
Check indices of the share table.
Done.

real	0m0.899s
user	0m0.603s
sys	0m0.177s
$ 
```

From my point of view the bad performance of `occ` is caused due to PHP interpreter being loaded including all Nextcloud classes etc. Thus I would like to suggest an internal batched mode which could look like this:

```
$ ./occ config:batch /tmp/commands.txt
richdocuments disabled
richdocuments enabled
No such app enabled: password_policy
.htaccess has been updated
Set mode for background jobs to 'cron'
Maintenance mode already disabled
Check indices of the share table.
Done.
$ 
```

```
$ cat /tmp/commands.txt
app:disable richdocuments
app:enable richdocuments
app:disable password_policy
maintenance:update:htaccess
background:cron
maintenance:mode --off
integrity:check-core
db:add-missing-indices
$ 
```

Note that `config:batch` is *not* intended as dumb shell script-like functionality that calls `occ` per line, but one single `occ` call where all commands are handled internally one after each other without having the need to re-load the PHP interpreter and the Nextcloud classes. I expect a nice speedup of `occ` using such a functionality.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
