### ISSUE TITLE
Theming folder icon color

### ISSUE THREAD

**Issue by eglyn** [nextcloud/server#11279]
Hi :)

I'm creating a theme for Nexcloud, and I'm blocking the color change of the "folder" icon, which remains desperately black...
I disabled the theme app, and create a theme folder with a copy of "example", and add the theme to the config.php.
I changed the SVG property variable "fill" by the desired color, but this only changes it for the left menu.
I read in the doc that it was necessary to change in the file "default.php" the variables "color-primary", etc ... but these changes every color exept the folder color :'(

Someone would have the method to change that color?

Thank you :)

**Comment by juliushaertl** [comment]
If you want replace the mimetype icons, make sure to run the `occ maintenance:mimetype:update-js` after putting the changed mimetype icons into your theme folder: https://docs.nextcloud.com/server/14/developer_manual/core/theming.html?highlight=theme#how-to-update-custom-mimetype-icons
