### ISSUE TITLE
NC 14 app navigation design: active class and nested lists

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#11272]
Perhaps I'm doing something wrong, perhaps the .active class is no longer supported, but when hovering over a a nested item with an active class, this happens: 

![screenshot from 2018-09-18 23-07-56](https://user-images.githubusercontent.com/986878/45716674-e3235700-bb97-11e8-91b1-4d60072df5b1.png)

**Comment by marcelklehr** [comment]
Also note that the nested entries are actually 57px in height, instead of 44px like the rest.

**Comment by weeman1337** [comment]
@marcelklehr it's only inside the bookmarks app, right?

For me it's working with the NC14 release and bookmarks 0.13.0:
![image](https://user-images.githubusercontent.com/6216686/45809586-d3576000-bcc8-11e8-9013-8ef38eeaf9d5.png)


Could you please check whether there is an update for the bookmarks app available for you?

**Comment by marcelklehr** [comment]
I'm a maintainer of the bookmarks app and was working on a new feature when I discovered this. :)

**Comment by weeman1337** [comment]
@marcelklehr oh okay :) Which version of the bookmarks app are you using then?

**Comment by marcelklehr** [comment]
I haven't pushed the code, yet. But basically it looks like this:

```html
<ul>
<li class="collapsible open active">
<a href="#" class="icon-tag" title="tags">tags</a>
<ul>
   <li class="active" id="bar">
   <a href="#" title="bar">bar</a>
   </li>
   <li id="baz">
   <a href="#" title="baz">baz</a>
   </li>
</ul>
</li>
</ul>
```

I was able to find the cause of the faulty height, now. I had added a span inside the a tags.

The only problem left now, is that it's nearly impossible to tell, which sub item of "tags" is active, because (as seen in the screenshots below) the active ribbons for the parent and the sub item overlap

![screenshot from 2018-09-20 22-32-49](https://user-images.githubusercontent.com/986878/45845423-5ad2bc80-bd25-11e8-9dec-7309c7b5113a.png)

In case the active class is removed from the parent menu item to remedy this, the hover effect for the child item becomes sub-optimal:
![screenshot from 2018-09-18 23-07-56](https://user-images.githubusercontent.com/986878/45845484-7f2e9900-bd25-11e8-978e-de5609ad0704.png)

**Comment by weeman1337** [comment]
@marcelklehr I would be happy to help. If you push a branch I can have a look.

Otherwise you may look at the files app where everything is working.

**Comment by marcelklehr** [comment]
The files app doesn't have nested navigation, afaik, but here's the pull request with the nested navigation https://github.com/nextcloud/bookmarks/pull/560 :)

**Comment by marcelklehr** [comment]
I guess this can be closed, now, as I opted to add the active class to all items that have the open class, so this is no longer a problem for me. I'm not sure if this solution is what was originally intended but it works for me :)
