### ISSUE TITLE
Documentation for SSO unclear

### ISSUE THREAD

**Issue by akloster** [nextcloud/server#11289]
According to Release Notes, NextCloud should support authentication via environment variables like with AuthType Basic. It is not quite clear how to actually do that.

This documentation page:
https://docs.nextcloud.com/server/12/admin_manual/configuration_server/sso_configuration.html#configuring-environment-based-authentication

does not exist for NextCloud 13 and 14. It's also not clear to me where I can "choose the “Environment variable” authentication provider in the application and then specify the environment variable. (e.g. REMOTE_USER for Kerberos)".

**Comment by ChristophWurst** [comment]
Please report this at https://github.com/nextcloud/documentation/. Suggestions and pull requests are always welcome :)
