### ISSUE TITLE
Birthday-calendar: properly handle deletion of addressbook

### ISSUE THREAD

**Issue by ulifan** [nextcloud/server#11305]
Steps to reproduce
1. Be a normal user: Open a new nextcloud-acount
2. Enter (or import) some contacts with birthdays entries
3. Verify that birthdays are being displayed in the birthday-calendar
4. Create another contacts-database (e.g. name it "Contacts_2")
5. Enter (or import) more contacts but for now into "Contacts_2".

Remark: The following step is done because in my example i assume, that the entries into "Contacts_2" are more complete and more accurate!

6. Delete the first contacts-database (only "Contacts_2" are left)
7. Check for birthdays in the birthday-calendar: All birthdays (even from "Contacts" and "Contacts_2")
   are still there! No chance to remove the birthdays from the deleted "Contacts". If you
had double entries (one from "Contacts" the second from "Contacts_2" you will see two entries.

Remark: Birthdays can be removed then only if you delete the birthday-calendar, but in this case
you run into the new problem: Not being able to recreate any birthday-calendar (as a user)

### Expected behaviour
With deleting "Contacts", the birthdays should be deleted as well, but the birthday-calendar should remain there!

### Actual behaviour
With deleting "Contacts", all birthday-data is still in the birthday-calendar, and cannot be deleted.

**Nextcloud version:** 13.0.0

**Comment by krleh** [comment]
Still existing in 18.0.0, using the following steps:

- Create an addressbook
- Add contacts with birthday
- Delete addressbook
- Birthday events still available

Reason: birthday-calender sync only iterates existing adressbooks (./apps/dav/lib/CalDAV/BirthdayService.php => function: syncUser)

CC: @nickvergessen

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by dranuhl** [comment]
This issue still exists with NextCloud 26.0.2, Contacts 5.3.0 and Calendar 4.3.5.

**Comment by szaimen** [comment]
Hi, please open a new issue with up-to-date information. Thanks!
