### ISSUE TITLE
Partial calendar export as ICS

### ISSUE THREAD

**Issue by matepate** [nextcloud/server#11301]
Hey, first let me say thanks for your great work.

I'd like to know, if there is an option to export only parts of a calendar via the ?export flag (as ics file).
I'm asking, because i have noticed that, especially on mobile devices with low bandwidth, importing/syncing large calendars via ics takes a huge amount of time and therefore leads to a faster discharge of the battery.

I know other systems, which support calendar sharing via ics that put only a part of the calendar into the exported file. Like events from the last 2 weeks and upcoming events for the next 6 months.

If there is no option in nextcloud for this, where would i've a starting point to dig into the code and maybe figure out by myself which parts needs to be modified to support such a behavior.

thanks in advance, matepate

**Comment by BernieO** [comment]
There is an option like this already. Just append desired start and end times (as unix time stamp) as well as expand=1 to the export link. Have a look at the following example which would export the last 2 weeks (roughly from Sep 10th, 10am to Sep 24th 10am):

https://NEXTCLOUD.EXAMPLE.COM/remote.php/dav/calendars/USERNAME/CALENDARURI?export&start=1536567360&end=1537776960&expand=1

**Comment by georgehrke** [comment]
As @BernieO said, this is already possible.
Closing
