### ISSUE TITLE
Welcome email sent in admin language, not user language on account creation

### ISSUE THREAD

**Issue by Zulan** [nextcloud/server#11306]
### Steps to reproduce
1. Start to create a new account
2. Provide an email address
3. Select a language different than the admin one
4. Create the account

### Expected behaviour
Receive welcome email in language of the user

### Actual behaviour
Receive welcome email in language of the admin

When resending the email, it is sent in the language of the user

### Server configuration

**Operating system**:
Archlinux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.2.10

**Nextcloud version:** (see Nextcloud admin page)
14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated database, fresh source installation

**Where did you install Nextcloud from:**
Archlinux repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
The current PHP memory limit is below the recommended value of 512MB.
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
The current PHP memory limit is below the recommended value of 512MB.
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "removed"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.0.19",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "maintenance": false,
        "loglevel": 2,
        "updatechecker": false,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpauthtype": "LOGIN"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Linux

**Comment by Zulan** [comment]
I wouldn't mind creating a PR for this, seems simple enough, but unfortunately I could only do so under a pseudonym.

**Comment by weeman1337** [comment]
@Zulan thanks for the report. What do you mean in terms of "pseudonym"? You could just fork the repo, fix it there and create a PR here.

Here are some points good to know when start coding: https://docs.nextcloud.com/server/14/developer_manual/general/codingguidelines.html

If you have any further questions, I'm happy to help.

**Comment by Zulan** [comment]
I was referring to https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md

> Use your real name (sorry, no pseudonyms or anonymous contributions).

**Comment by weeman1337** [comment]
@Zulan would it be a problem for you to set your git name/e-mail address?
