### ISSUE TITLE
Add app rating counter next to star visualization

### ISSUE THREAD

**Issue by wiwie** [nextcloud/server#11318]
Right now when browsing apps, there is no rating counter shown next to the average rating of an app.

It seems to me though, that apps without any ratings are visualized with a default of 2.5/5.0 stars.

The current visualization makes it impossible to distinguish between "no ratings" and "more than 0 ratings, and average rating is 2.5".

Either, one should add a rating count next to the stars, or "no ratings" should get a visualization different from cases with ratings count > 0.

**Comment by wiwie** [comment]
Also, currently about half of all apps show up with a rating of 2.5/5.0, which seems really a bad "level of quality". But it does not anymore, if one realizes that it is probably just the default rating for most of them.

**Comment by szaimen** [comment]
I think this was implemented in the meantime -> closing.
Please reopen if this shouldn't be the case!
