### ISSUE TITLE
Move/copy file picker: Should start out in current folder, not root

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11314]
Currently the move/copy file picker always starts out in the root folder. This is very cumbersome and annoying when you want to move some files in some sub/sub/subfolder.

Instead, the file picker should always start out in the current folder.

As a future enhancement, as long as you are in the same folder, we could even remember the folder you then jumped to and remember that.

cc @nextcloud/javascript

**Comment by blizzz** [comment]
Or rather the location where a file was copied/moved to last time.

**Comment by jancborchardt** [comment]
@blizzz yes, what I meant by:

> As a future enhancement, as long as you are in the same folder, we could even remember the folder you then jumped to and remember that.

**Comment by MorrisJobke** [comment]
Solved in #12381
