### ISSUE TITLE
Lower button cut off in the destination folder dialog

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#11315]
## Expected behavior
If files are copied or moved to a new folder, all displayed buttons in the destination folder dialog should be correctly displayed without the requirement to scroll down the dialog window.

## Current behavior
The lower button is cut off in the initially displayed destination folder dialog. You need to scroll down to get it displayed correctly.

![2018092_nc_copy_move_dialog](https://user-images.githubusercontent.com/2572764/45890979-aa1bfa00-bdc4-11e8-9859-42fb1739249f.png)

### Steps to reproduce
1. Select two files to be copied
2. Navigate to the destination folder.
3. Check out how the buttons are displayed.

#### Server Configuration
OS: Linux 3.16.57
Web server: Apache2 2.4.33
Database: MariaDB 10.0.32
PHP version: 5.6.34
Nextcloud version: 13.0.6

#### Client Configuration
Browser: Mozilla Firefox 62.0
Operating system: Windows 10

**Comment by weeman1337** [comment]
@j-ed thanks for the report.

I can confirm the problem with Nextcloud 13.

It's not perfect in dev and 14, but it works:
![image](https://user-images.githubusercontent.com/6216686/45915746-98853180-be5a-11e8-8957-4217b1f94bb4.png)

I'll have a look.

**Comment by skjnldsv** [comment]
@weeman1337 the last one is great I think :)

**Comment by pixelipo** [comment]
Why doesn't the button just simply say one of the following?

- "Move/Copy here"
- "Move/Copy to this folder"
- "Move/Copy to current folder"

**Comment by weeman1337** [comment]
I could imagine the folder name in the buttons is to make it clear where the file goes to.

**Comment by MorrisJobke** [comment]
Fixed by #11522
