### ISSUE TITLE
Move/copy picker: Possible to accidentally choose same folder, receive error

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11313]
Currently when moving/copying a file via the file picker, you can accidentally choose the same folder you are just moving as a target. In that case you just get an error "Could not move folder".

Instead, the current folder that you are moving should be grayed out to make clear that it’s the current folder being moved.

What do you think @nextcloud/designers

**Comment by pixelipo** [comment]
Since we have both "Move" and "Copy" buttons, your approach makes most sense. Otherwise, `Move` action would default to `Copy` in case destination folder == source folder

**Comment by MorrisJobke** [comment]
Should maybe combined with #9931 (copy to same folder should create a duplicate file) and remove/gray out the "Move" button as @pixelipo explained it.

**Comment by szaimen** [comment]
At least copying into the same folder works now as far as I can see on c.nc.c. (it creates a new file which is named the same + (copy))
Please reopen if you still want to implement this for moving.
