### ISSUE TITLE
iOS 12.0 Caldav without sync

### ISSUE THREAD

**Issue by CStuck** [nextcloud/server#11310]
I am driving Nextcloud 13.0.5
PHP 7.1.21
mysql 5.5.60
at our provider 1und1.de Apache with http
now I updated my iPhone to 12.0 and the CalDAV (maybe the CardDAV also) doesn't sync any more.
Any ideas? Is it possible that there must be a SSH?

**Comment by BernieO** [comment]
> Is it possible that there must be a SSH?

You probably mean SSL.
Yes, maybe. I am using SSL and don‘t have any sync problems with CalDAV/carddav since upgrading to iOS12 with 4 different iOS-devices.

**Comment by muzzah** [comment]
I can confirm that MacOS seems to be wanting SSL connections moving forward. Had the same issue. Was accessing my nextcloud instance through a VPN and using HTTP. Once I setup NginX as a proxy infront of it as an SSL terminator, iOS and MacOS started syncing again without issues.

**Comment by muzzah** [comment]
Im am on High sierra but found that my caldav accounts were syncing problematically/intermittently over cleartext. Upgrading to SSL fixed my issues on iOS And MacOS

**Comment by wuast94** [comment]
have the same problem but with ssl activated behind a reverse proxy. 

https://help.nextcloud.com/t/caldav-ios-not-syncing/45464 

cant find out whats wrong .. update all today

when i disale ssl or anything else and click done i get error that the connection is refused. with the right inserts ios say that all works fine but no sync at all ....

**Comment by georgehrke** [comment]
iOS 12 requires an SSL / TLS connection for CardDAV and CalDAV sync.
