### ISSUE TITLE
Where is your data?

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/server#11319]
## Story
As a Nextcloud hoster I want to show the user where his data is stored,
so it makes it transparent for him and increases trustability.

## Background
With Nextcloud you have the freedom to choose where your data is stored at. This means for example if you're uncomfortable with a hoster you could simply choose another one. Other centralized services doesn't offer this option, because there is only one hoster by nature.

To increase transparency/trustability and point out the individual data storage, some info about that will be shown to the user.

## Sketch:
![image](https://user-images.githubusercontent.com/6216686/45916417-30d4e380-be66-11e8-841b-778178fe6961.png)

## Discussion
Also see the PR for that: #13097

**Comment by weeman1337** [comment]
I'm not sure about how to configure/retrieve all the info.

The country lookup may be possible. If there is a public IP a STUN server could be used for that. Then there needs to be a IP ↔ location lookup... That sounds like a huge effort and it leaks data (if external services are used). So maybe it's simpler to just provide a config option or settings for that.

Basically I would suggest:
* It's possible to set all the info in a config file. This is easy for auto deployments. It targets managed systems/hosters.
* Additionally there is a settings page where you can enter all the info. This targets individual instances.

@jospoortvliet @nextcloud/security what do you think about that?

**Comment by nickvergessen** [comment]
This should all be provided manually in my oppinion

**Comment by rullzer** [comment]
I agree with @nickvergessen first manual this is all fine. Just have the admin set it.

Else we use geoip stuff (if installed on the system). But for v1.0 manual is good enough.

**Comment by jancborchardt** [comment]
We could already add the section with the 2 things we can display without any manual data entry: Admin and Data protection level. :)

> ### Where is your data? [ℹ](https://nextcloud.com/yourdata/)
> 👤 **Michael is your admin.** If you have any issues, [contact them](mailto:test@example.com).
> 🔒 Your data is protected by [server-side encryption](https://nextcloud.com/blog/encryption-in-nextcloud/).

@weeman1337 @shironextcloud what do you think? Maybe there’s a better link for server-side encryption than the blog?

@weeman1337 do you want to open a pull request for that? We could do the geolocation and ratings in a separate follow-up.

Icons: https://docs.nextcloud.com/server/14/developer_manual/design/icons.html
- `class="icon-user-admin"` for admin
- `class="icon-password"` for lock/security
- Future: `class="icon-address"` for location, `class="icon-home"` for provider

For the heading and the ℹ icon, we can use this:
```
<h2>Where is your data?</h2>
<a target="_blank" rel="noreferrer noopener" class="icon-info" title="" href="https://nextcloud.com/yourdata/" data-original-title="Open documentation"></a>
```

(Or we leave out the i-icon, but it’s a nice addition and further reading. :)

**Comment by MorrisJobke** [comment]
@weeman1337 I guess you didn't started this yet, right? Looks like we need to move it to 16, because we want to do the first beta on Thursday.

**Comment by weeman1337** [comment]
@MorrisJobke yeah I was busy in the last time - sorry for that :/  
Let's get that in in 16 then.

**Comment by MorrisJobke** [comment]
Most of this is done in #13097
