### ISSUE TITLE
Enable/Disable local external storage mount

### ISSUE THREAD

**Issue by nexus186** [nextcloud/server#11324]
I have to transfer data from one computer to the nextcloud server using an external USB drive. I mount the drive in nextcloud as external storage, transfer data, delete the external storage mount in nextcloud, and disconnect the usb drive.

I have to do this several times which means that I have to recreate the local storage mount and delete it before I disconnect the drive.

It would be nice if there was a enable/disable option so I can just disable it and then disconnect the drive.

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
