### ISSUE TITLE
Option to display deleted files in directory tree

### ISSUE THREAD

**Issue by m1cm1c** [nextcloud/server#11323]
In Dropbox's web interface's directory tree, there is this neat option called "show deleted files":

![](https://i.imgur.com/pziNKSS.png)

When you click it, it shows the files that were deleted in the location you are right now. You can then restore them or look at their versions. This would be an awesome feature for Nextcloud because right now it's very difficult to restore deleted files.

**Comment by m1cm1c** [comment]
This is not a duplicate of any of the mentioned issues.

**Comment by RafalSkolasinski** [comment]
+1 on this - it seems like an awesome things to have!

**Comment by szaimen** [comment]
cc @nextcloud/server is this feasible?

**Comment by m1cm1c** [comment]
Would still be nice. I don't see how this would have gotten stale.
