### ISSUE TITLE
Type in Dutch translation for firstrunwizard

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#11320]
### Steps to reproduce
1. Goto https://<fqdn>/settings/user/sync-clients in Dutch
2. Look for the text: Verbind andere apps met [NAME]
3.

### Expected behaviour
Text in Dutch states:  Verbind andere apps met NAME

### Actual behaviour
Text in Dutch states:  Verbind andere apps met 1NAME

Look for the one.

### Server configuration

**Nextcloud version:** 14.0.0

nextcloud-14.0.0/apps/firstrunwizard/l10n # grep -i "connect other apps to" nl.js
    "Connect other apps to %s" : "Verbind andere apps met 1%s",

The "1" before %s should be removed.

https://www.transifex.com/nextcloud/nextcloud/viewstrings/#nl/firstrunwizard/138894867?q=text%3A'connect+other+apps'

**Comment by rullzer** [comment]
Our translations are synced daily from transifex.
Please join at https://www.transifex.com/nextcloud/nextcloud/dashboard/ to help with translations.

This seems to be already fixed recently. And should be shipped with 14.0.1
