### ISSUE TITLE
Many translations cannot be displayed because of text changes

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/server#11328]
Many translations cannot be displayed because of text changes.
I use Chinese translation, but many translations can't be displayed, most of them are fixable, and they are also fixed in my server, but I have forgotten that those translations need to be fixed, please developers to test the fix as soon as possible.
 
I use 14.0.0.0
thanks.

**Comment by tflidd** [comment]
Please update the translations on transifex.



> please developers to test the fix as soon as possible.

did you already submit them?

**Comment by chiyi4488** [comment]
This is no longer a problem without translation. It is a problem with the translation itself.

**Comment by MorrisJobke** [comment]
@chiyi4488 I don't fully understand what the problem is. Do you say, that the translations that you did on transifex are not shown in 14.0.0? Could you check if they show up in 14.0.1 properly? Do you have screenshots of the problematic translations?

**Comment by chiyi4488** [comment]
![4](https://user-images.githubusercontent.com/30853081/46241043-a818f300-c3e3-11e8-92aa-435b7997b999.png)

**Comment by MorrisJobke** [comment]
That one is actually not translated (a similar one without the `a` before `member` is translated): https://www.transifex.com/nextcloud/nextcloud/translate/#zh_TW/settings-1/145522875?q=text%3Amember

Translating this will result that 14.0.2 has the translation for that string.
