### ISSUE TITLE
Custom CSS on app level not working

### ISSUE THREAD

**Issue by maccarib** [nextcloud/server#11332]
### Steps to reproduce
1. Place a 'server.css' file in the path /themes/<mytheme>/apps/<myapp>/css 
2. In particular I tried it with a  /themes/<mytheme>/apps/contacts/css/server.css and a /themes/<mytheme>/apps/tasks/css/server.css file
3. Reload the given app pages. In the browser inspector you see, that the server delivers the /themes/<mytheme>/core/css/server.css, but none of the css files on app level.
4. I also tried using the path /themes/<mytheme>/contacts/css/, same result

### Expected behaviour
I have a custom 'server.css' file in my theme path /themes/<mytheme>/core/css. That one works fine. Now I want to add some custom css that should apply to certain apps only. Following the documentation that I've found placing a 'server.css' file in the path /themes/<mytheme>/apps/<myapp>/css should do the trick. .

### Actual behaviour
Nothing. None of the mentionned server.css-files is being delivered.

### Server configuration

**Operating system**: Debian 3.16.56-1

**Web server:** Apache 2.0 

**Database:** MySQL

**PHP version:** 7.2.8

**Nextcloud version:** 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
files
activities
galery
contacts
calendar
rainloop
tasks

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/home/www/<mypath>/data',
  'dbtype' => 'mysql',
  'version' => '13.0.6.1',
  'dbname' => '',
  'dbhost' => 'localhost:3306',
  'dbtableprefix' => 'nc_',
  'dbuser' => '',
  'dbpassword' => '!',
  'filesystem_check_changes' => 1,
  'installed' => true,
  'logfile' => '/data/nextcloud.log',
  'loglevel' => '1',
  'log_query' => false,
  'maintenance' => false,
  'theme' => '<mytheme>',
  'trusted_domains' => 
  array (

  ),
  'mail_from_address' => '',
  'mail_smtpmode' => 'php',
  'mail_domain' => '.net',
  'secret' => '',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'overwrite.cli.url' => '',
);
</details>

### Client configuration
**Browser:** Firefox, Opera, Chrome

**Comment by MorrisJobke** [comment]
> Nothing. None of the mentionned server.css-files is being delivered.

You need to place the files named as the ones that we ship within the server. The names have changed. but we are moving away from those themes towards the theming app + the custom css app that is available in the App Store. Give them a try because they are a lot more robust and actively maintained.

**Comment by maccarib** [comment]
Yes, you're right. So when I add app css files like
themes/<mytheme>/apps/tasks/css/style.css
they will be delivered and used. Thanks for the information. I will also have a look at the custom css apps. Just one questions: Are the customizations made through the CSS app compatible with existing manual css adjustments or is it either the one or the other?

**Comment by MorrisJobke** [comment]
> Are the customizations made through the CSS app compatible with existing manual css adjustments or is it either the one or the other?

Themes just load additionally. Same for custom css app.

**Comment by maccarib** [comment]
OK, thank you for the reply!
I've discovered similar problems with theme template files (see https://github.com/nextcloud/server/issues/11585) Could it be another simple deviation from the documentation?

**Comment by MorrisJobke** [comment]
> I've discovered similar problems with theme template files (see #11585) Could it be another simple deviation from the documentation?

Yes - but we are fading out support for this and would like to move everybody over to theming app.
