### ISSUE TITLE
Question: RGB/Chroma theme colors APP (Changing colors)

### ISSUE THREAD

**Issue by ShutAP1337** [nextcloud/server#11331]
### Steps to reproduce
1. Go to settings
2. Go to Theming

### Expected behaviour
This is not a issue but a question. The question is, How i can put RGB/Chroma as a color of the theme.

### Server configuration

**Operating system**: Linux

**Web server:**

**Database:** SQLite

**PHP version:** 7.1

**Nextcloud version:** Latest One

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:** Oficial Website

**Signing status:**
<details>
<summary>Signing status</summary>
</details>

**List of activated apps:**
1. http://prntscr.com/kxp1g7
2. http://prntscr.com/kxp1nm

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 7

**Comment by MorrisJobke** [comment]
> This is not a issue but a question. The question is, How i can put RGB/Chroma as a color of the theme.

This is not possible as of now and also not planned, right @juliushaertl ?

**Comment by juliushaertl** [comment]
I don't understand what exactly you mean with the Chroma part, but you already can specify an rgb color as hex value in the theming settings.
