### ISSUE TITLE
Prior to upgrading, show version of available upgrade, avoiding unwanted branche jumps

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#11349]
Nextcloud upgrading makes unwanted branche jumps. By the time you see what new version has been selected by the Web Updater it is too late, you can't cancel the upgrade anymore.

Nextcloud should not only show the current version, but also the version of available upgrade(s) prior to executing an upgrade.  It might also offer a version in another branche.
Offer the possibility to cancel the action if an unwanted version has been selected.

### Steps to reproduce
1. Settings > (Administration) Overview  (ie. Version **14.0**.1 RC1)
2. Set update channel to "Daily" => "A new version is available"
3. Upgrade via Web Updater.

### Expected behaviour
1. Nextcloud (14.0.1 RC1) should update to a newer version within the same branche.

### Actual behaviour
Nextcloud upgrades to **15.0.0 alpha**, jumping branches and unwillingly takes you from a RC to an Alpha.

**Comment by janvlug** [comment]
I see that there is an update from 13.0.6 to 13.0.7:
![screenshot from 2018-10-11 22-54-45](https://user-images.githubusercontent.com/5903208/46833417-e2ea3600-cda8-11e8-9b34-50d7a7d87b1d.png)
But when I click "Open updater" I see an update from 13.0.6 to 14.0.2:
![screenshot from 2018-10-11 22-55-14](https://user-images.githubusercontent.com/5903208/46833499-175df200-cda9-11e8-8906-6f2d6b6358a0.png)
The update is not immediately started (you have to click "Start update" first, but you have to pay close attention to see that you are switching to a new branch.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
