### ISSUE TITLE
Failure during update extraction, can't unlink

### ISSUE THREAD

**Issue by lowlyocean** [nextcloud/server#11353]
### Steps to reproduce
1. Mount data directory /var/www/owncloud/data to external Windows (SMB/CIFS) share using /etc/fstab
2. Perform upgrade from 13.0.5 to 13.0.6 using web UI
3. Wait until extraction step

### Expected behaviour
Extraction should complete succesfully

### Actual behaviour
```
Extracting
Cant unlink /var/www/owncloud/data/updater-ocd1y205r9dr/downloads//nextcloud
```

### Server configuration

**Operating system**:
PRETTY_NAME="Open Source Media Center"
NAME="OSMC"
VERSION="June 2018"
VERSION_ID="2018.06-1"
ID=osmc
ID_LIKE=debian

ANSI_COLOR="1;31"
HOME_URL="https://www.osmc.tv"
SUPPORT_URL="https://www.osmc.tv"
BUG_REPORT_URL="https://www.osmc.tv"

**Web server:**
nginx version: nginx/1.10.3
**Database:**
mariadb  Ver 15.1 Distrib 10.1.26-MariaDB
**PHP version:**
PHP 5.6.33-0+deb8u1
**Nextcloud version:** (see Nextcloud admin page)
13.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - passman: 2.1.4
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - files_pdfviewer
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "lowlyocean.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/lowlyocean.com\/owncloud",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "dbport": "",
        "enable_previews": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** 
SMB but this should be transparent to NextCloud

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Google Chrome Version 69.0.3497.100
**Operating system:**
Windows 10 Pro version 1803
#### Web server error log
<details>
<summary>Web server error log</summary>

```
2018/09/22 18:31:16 [notice] 7647#7647: signal process started
2018/09/23 11:35:37 [notice] 1891#1891: signal process started
2018/09/23 11:44:24 [notice] 2032#2032: signal process started
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing related to this issue
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Not relevant
```
</details>

**Comment by ChristophWurst** [comment]
Sounds like the web server (or installer) user does not have sufficient permissions to delete that folder.

In general these setup issues are best to ask help for at https://help.nextcloud.com/
