### ISSUE TITLE
Send note to recipient: previously content not visible on shared link

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11352]
- share file A to user
- set note to "123"
- reload page
- re-open "set note" to file A
--> see "123"

do the same for a shared link and do not see the current message.

In my opinion the currently set message should be shown on both cases, as otherwise the user might be led to the impression, that the content was removed.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by tobiasKaminsky** [comment]
Works now.
