### ISSUE TITLE
Restrict specific logins from specific ip address/subnet feature

### ISSUE THREAD

**Issue by nexus186** [nextcloud/server#11359]
In a properly secured installation, admins should not be able to login from outside the network. Please add a feature for this, both synology and qnap already have these options.

**Comment by codesmaker** [comment]
I also would love to see such feature. It would be nice to restrict logins for certain accounts from specific subnets.

**Comment by wiswedel** [comment]
related/duplicate: https://github.com/nextcloud/limit_login_to_ip/issues/20

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/limit_login_to_ip/issues/20
