### ISSUE TITLE
Show QR code when sharing

### ISSUE THREAD

**Issue by gerroon** [nextcloud/server#11360]
Hi

It would be very helpful the sharing link window also can show QR code for sharing, so the mobile user can scan the QR code and be able to use it on the mobile. 

thanks

**Comment by MorrisJobke** [comment]
Nice idea - cc @nextcloud/designers 

Once this is accepted it should also be integrated into the mobile apps. ;)

**Comment by jancborchardt** [comment]
We do have the mobile apps already – simply use them for Android or iOS: https://nextcloud.com/clients/

It doesn’t really make sense to include QR code for this flow just to act as copy-paste mechanism.

**Comment by gerroon** [comment]
@jancborchardt 

The issue is not the mobile app, also the mobile app is not used by everyone, noone is going to install a mobile app to share a Qr code.

I think that there is a misunderstanding here. Let me show you the usage case


I have my browser open, I share a file in the browser, then I want to share that link to a friend via some kind of messenger app on my phone. My options are email, using the app etc however all these require addiitonal steps and email being not so secure. Including a simple QR code next to the shared link display will simplify these steps.

**Comment by lachmanfrantisek** [comment]
I have another use case for that -- printing of the QR code (posters, banners, t-shirts,...).

Now, you have to use some external tool for that. We can also have some nextcloud-branded QR-codes.

Having this in other apps would be also nice -- e.g. contacts, gallery, polls,.. Passwords app has that already.

**Comment by J0000** [comment]
Just now I was looking for exactly this possibility. Sharing a memo from a meeting could be so easy by displaying a qr-code via beamer or print it out and hang it on the wall for the participants :)

**Comment by CrysK** [comment]
I would share documents from the Nextcloud. There should always be the share link printed as a QR code to put it to a hardware to easily find the document at any time. 
Would be very cool if this would work ...

**Comment by bes1002t** [comment]
I agree, just showing a simple QR code would be quite helpful for many use cases. Require users to install a mobile application just to share links via messenger is annoying for users.

**Comment by moeb98** [comment]
plus 1

**Comment by dp081190kds** [comment]
It is very necessary to be able to immediately create a QR code of the general link.

**Comment by SemaphoreOxalis** [comment]
Could be very useful. Each time we create a share link for copy/pasting in a document (onyloffice^^) we want to add a QRCode as img for for offline readers. We do that for now with external tools.

**Comment by massa007** [comment]
+1

**Comment by dartcafe** [comment]
At least [for polls](https://github.com/nextcloud/polls/issues/2243#issuecomment-1445150713), there is a QR code for public links. 

this could easily adopted and optimized as a nextcloud-vue component

**Comment by lgitano** [comment]
+1 for an auto-generated qr-code for public shared folders inside nextcloud!

maybe somewhere around this dropdown menu?

[Screenshot from 2023-11-30 01-52-07](https://github.com/nextcloud/server/assets/99294828/20be17af-409c-4021-9333-be400efdbba9)

i work at a school where we regularly share files for each student individually, often they loose the link to their online folder -> here a little handout paper with a printed qr-code to that share comes in very handy. Right now i am generating this code externally, which can get quite cumbersome :)

**Comment by ruedigerkupper** [comment]
See also https://help.nextcloud.com/t/qr-codes-on-sharing-anonymous-links-again/137009
