### ISSUE TITLE
Nextcloud is sending Emails even if link sharing is disabled once created a share by a user

### ISSUE THREAD

**Issue by f4stb00t** [nextcloud/server#11375]
Hi,

I am wondering why nextcloud is sending emails even if "Allow users to share via link" is disabled by the administrator. I tried to share a picture with some email address and the recepient received an email but the link which has been sent was not valid. Means it leads to nowhere "file not found" 

Why is this? When I disable this option, of course I do not want any user to be able to send useless Links to shares where the user should not be allowed to send them in any way? This is also reproduceable.  Another point is that "allways ask for password" is not working as expected. Actually it sets its own passwort and tries to send it to the user. This seems to be a bug somehow. Because I tested this feature with v13 and it worked ootb without any issues. 

I am running Nextcloud 14.0.1

If you need additional information, please do not hesitate and tell me which.

Note: I have this issue when I try to share a link with a browser via the webUI. With the android app its working as expected. 

Kind Regards

fastboot

![1](https://user-images.githubusercontent.com/17380145/46023216-7a326680-c0e4-11e8-84d8-efb8200328af.png)

**Comment by f4stb00t** [comment]
Okay. I tried it now with an additional browser (chromium) under linux. 
Usually I would expect when I try to share a link:

1. Enter Email
2. Enter Password
3. Expiration date should be set automatically to 30 days

Nothing of this is working. When I enter the email and hit enter or click the arrow I get "Expected response code 250 but got code "550", with message "550-Requested action not taken: mailbox unavailable  550 Sender address is not allowed.  ""

In fact the email is being sent. But I had no possibility to add a password. It seems some random generated password was used, because when I hit the link in the email it asks me for a password.
Seems something is wrong with v14 and file sharing. 

Can anyone confirm this issue?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
