### ISSUE TITLE
Nextcloud not stopping download

### ISSUE THREAD

**Issue by elpedriyo** [nextcloud/server#11376]
Nextcloud version _(eg, 12.0.2)_: 14.0.0
Operating system and version _(eg, Ubuntu 17.04)_: Debian 9.5.0
Apache or nginx version _(eg, Apache 2.4.25)_:  2.4.25
PHP version _(eg, 7.1)_: 7.0.30

The issue you are facing:

Is this the first time you've seen this error? _(Y/N)_: N

I came from last version of nextcloud to see if 14.0.0 solved it, but it doesn't as far as I see. The problem is that I have an external storage NFS and with the official plugin I add it to nextcloud as local, of course the NFS storage is mounted inside the system. Once I start downloading a big file, example: 20GB and then cancel it, seems like the server continues downloading it (don't know where) as the interface of RX is still receiving a lot of data, once the full file is downloaded in the server (I assume) the RX goes down again. If for example I pause a download file, both RX and TX go down, but if I just cancel the download it happens what it is described before.
Any idea?

https://prnt.sc/ky946d

Steps to replicate it:

1. Mount a nfs dataset in debian
2. Activate external storage plugin
3. Config the plugin so that files can be browsed
4. Start downloading and stop the download
5 The interface Rx won't go down until the file is downloaded in the server

The output of your Nextcloud log in **Admin > Logging**:
```
Nothing to paste, everything seems fine
```

The output of your config.php file in `/path/to/nextcloud` (make sure you remove any identifiable information!):
```
<?php
$CONFIG = array (
  'instanceid' => 'ocv3194h6bpq',
  'passwordsalt' => 'VAYAFkQkZpQr7IX2fwCRqTTAzoBLCJ',
  'secret' => 'ravqkxlSe+II4sFNvGbYRwac83ec0mDZCygFR18SgR8874EJ',
  'trusted_domains' =>
  array (
    0 => '192.168.1.203',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '14.0.0.19',
  'overwrite.cli.url' => 'http://192.168.1.203',
  'dbname' => 'nextcloud',
  'dbhost' => '127.0.0.1',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '*****',
  'installed' => true,
  'updater.release.channel' => 'stable',
);



```

The output of your Apache/nginx/system log in `/var/log/apache2/error.log`:
```
[Mon Sep 24 23:15:18.907747 2018] [mpm_prefork:notice] [pid 777] AH00169: caught SIGTERM, shutting down
[Mon Sep 24 23:15:19.591906 2018] [mpm_prefork:notice] [pid 1344] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Mon Sep 24 23:15:19.591956 2018] [core:notice] [pid 1344] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 24 23:34:48.736848 2018] [core:notice] [pid 1344] AH00052: child pid 1563 exit signal Segmentation fault (11)
[Mon Sep 24 23:34:48.737404 2018] [mpm_prefork:notice] [pid 1344] AH00169: caught SIGTERM, shutting down
[Mon Sep 24 23:34:48.858873 2018] [mpm_prefork:notice] [pid 1649] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations
[Mon Sep 24 23:34:48.858919 2018] [core:notice] [pid 1649] AH00094: Command line: '/usr/sbin/apache2'
[Mon Sep 24 23:35:38.088968 2018] [core:notice] [pid 1649] AH00052: child pid 1651 exit signal Segmentation fault (11)
[Mon Sep 24 23:35:38.089332 2018] [mpm_prefork:notice] [pid 1649] AH00169: caught SIGTERM, shutting down
[Mon Sep 24 23:35:38.191625 2018] [mpm_prefork:notice] [pid 1687] AH00163: Apache/2.4.25 (Debian) configured -- resuming normal operations

```

The output of your Apache/nginx/system log in `/var/log/apache2/nextcloud_error.log`:
```

[Mon Sep 24 23:19:25.788683 2018] [authz_core:error] [pid 1358] [client 192.168.1.64:49650] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:26.598217 2018] [authz_core:error] [pid 1365] [client 192.168.1.64:49647] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:27.220860 2018] [authz_core:error] [pid 1376] [client 192.168.1.64:49651] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:36.631662 2018] [authz_core:error] [pid 1404] [client 192.168.1.64:49681] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:37.629213 2018] [authz_core:error] [pid 1363] [client 192.168.1.64:49680] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:38.925246 2018] [authz_core:error] [pid 1358] [client 192.168.1.64:49650] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:39.608312 2018] [authz_core:error] [pid 1404] [client 192.168.1.64:49681] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:40.599377 2018] [authz_core:error] [pid 1364] [client 192.168.1.64:49678] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:41.915558 2018] [authz_core:error] [pid 1365] [client 192.168.1.64:49687] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:43.430706 2018] [authz_core:error] [pid 1358] [client 192.168.1.64:49650] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Sep 24 23:19:44.177766 2018] [authz_core:error] [pid 1350] [client 192.168.1.64:49696] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata


```

**Comment by elpedriyo** [comment]
I have tried also with a snap package mounting my NFS and adding it with the external storage plugin in nextcloud, but the same issue happens all the time, if I download a file from my browser and cancel it at any point my server continues downloading the file as I am monitoring the network interface

**Comment by elpedriyo** [comment]
Ok, I was wondering if it was a bug with the NFS protocol, apache or something else, but I have confirmed that it seems to be a bug of the external storage plugin as with FTP protocol is also happening the same.

Could you please take a look to fix it? :D

Kind regards

**Comment by elpedriyo** [comment]
Hello,

Seems like I have discovered a core bug in nextcloud, I should say, regarding this issue, at which I didn't got any reply, it seems like there is no problem or relation with a NFS mount or the plugin itself.
Nextcloud continues "downloading" the file although it was cancelled because he continues reading it.

I discovered it by trying to download a big file (20GB) from my local storage, and saw that once the download was cancelled, nextcloud continued reading it, just discovered it with a simple iotop:
https://image.prntscr.com/image/ZUwxrsPtQHipMv8zOfDAnw.png

Does anyone have any idea on why is this happenning on a fresh installation?

Kind regards

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by elpedriyo** [comment]
Hello,

Any idea?

Please any help would be appreciated.

Kind regards,

Pedro

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
