### ISSUE TITLE
Top-left logo reaches 1 px beyond the header

### ISSUE THREAD

**Issue by go2sh** [nextcloud/server#11372]
The logo in the top-left corner has a absolute position of 1 px from top. With the 100% height it has the same heigth as the header and thus is shown 1 px beyond the header, if the logo has no space around it.

![Example](https://user-images.githubusercontent.com/150886/46013174-c329f100-c0cb-11e8-8855-876e56c15a4e.png)
I used the browser to zoom in as 1 px is hard to see. ;-)

**Comment by splitt3r** [comment]
A small padding around the logo would be great anyway.
