### ISSUE TITLE
"You can click here to return to ."

### ISSUE THREAD

**Issue by addaitrs** [nextcloud/server#11370]
### Steps to reproduce
1. Create a public share link
2. Delete the public share link
3. Visit the original link

### Expected behaviour
Helpful text to explain the issue and provide link to return to NextCloud correctly

Is it possible to change this text directly without breaking anything?

### Actual behaviour
View screenshot

https://i.snag.gy/F7nkMw.jpg

### Server configuration

Ubuntu

Apache

MySQL

NextCloud 13.02

Fresh install

**Comment by MorrisJobke** [comment]
Looks like your theming has an empty name (usually it prints there the brand name):

<img width="445" alt="bildschirmfoto 2018-10-02 um 22 04 15" src="https://user-images.githubusercontent.com/245432/46373745-22b96b00-c68f-11e8-9b57-4164dfadfe90.png">


But we need to check what to put there.

@jancborchardt just said that he wants to look into make this page a bit more useful.

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/11566, please review. :wink:
