### ISSUE TITLE
php email mode no longer available

### ISSUE THREAD

**Issue by mbiebl** [nextcloud/server#11377]
I'm running nextcloud on a hosted server.
After the upgrade from 13 to 14, emails were no longer working.
It seems php support has been removed. In my case only SMTP support is available as the hosted environment does not have a /usr/sbin/sendmail binary.

Configuring SMTP mode is very inconvenient, as I now need to create a special email account.

Please consider adding back support for php mode.

**Comment by danielkesselberg** [comment]
I'm afraid there's very little chance of that happening :disappointed: Support has been removed upstream from swiftmailer (here is an explanation why https://github.com/swiftmailer/swiftmailer/issues/866#issuecomment-289291228).

**Comment by j-ed** [comment]
@mbiebl I could recommend to install e.g. [sSMTP](https://linuxundich.de/gnu-linux/system-mails-ohne-einen-mail-server-mit-ssmtp-verschicken/) as an easy alternative to PHP mail function.

**Comment by mbiebl** [comment]
This is a hosted environment where I can't install any additional software

**Comment by MorrisJobke** [comment]
Unfortunately we dropped support for it and as @danielkesselberg there is very little chance to add it back.

There is only SMTP as alternative for you to send emails if installing something is not possible.

For further questions have a look at the forums: https://help.nextcloud.com
