### ISSUE TITLE
[Mandatory 2FA] Spec: Enforce generation of backup codes

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#11380]
**Mandatory 2FA in Nextcloud 15**

Overview/progress board: https://github.com/orgs/nextcloud/projects/17

:rocket: 

---

# Specification: Enforce generation of backup codes

Especially with the move to mandatory 2FA, we should make sure people have generated their backup code codes (before) they enable any other 2FA provider.

Since our 2FA architecture is pluggable, we don't have direct control over the settings of an individual implementation. Hence we don't (yet) have a defined flow for enabling 2FA, but it's rather enabled as soon as one provider tells the provider registry about their enabled state.

@rullzer and I have done some initial brainstorming in a private chat. Our basic ideas are the following:

## Approach A – Soft-enforcement and notifications

The Nextcloud server will check users' 2FA state and if they use it without backup codes configured, send a notification about it or show it in a similar way in the UI.

Of course, this is no hard-enforcement and user could simply ignore this. But we also have no guarantee that backup codes are printed or saved on a persistent/secure location, so we actually can never really reason about about the existence of backup codes.

## Approach B – Throw an exception in the provider registry

Since Nextcloud 14, providers have to register their state in a provider registry (aka stateful providers). While not in the original design of that interface, we could add a check that throws an exception when a provider is enabled but backup codes haven't been generated yet.

The (obvious) downside to this is that it would break backwards compatibility (BC) (thrown exception not documented).

## Approach C – Client-side API for providers to check backup codes state

Similar to `OC.PasswordConfirmation.requirePasswordConfirmation()`, we could have an API like `OC.TwoFactor.requireBackupCodes()` that returns a promise which resolves once backup codes have been generated. This would make a nice UX for on-page actions. Since this check is just a hint, we still would have to do the server-side checks when a provider is enabled like in approach B.

The downside here is here is that we don't have a defined client-side API, so I'm always very hesitant making this a de facto public API like this. An alternative would be some proper public APIs via REST or OCI where we offer an optional client lib developers *can* use, but are not required to.

---

Ref https://github.com/nextcloud/twofactor_totp/issues/89

**Comment by rullzer** [comment]
Lets see how far we get with this.

Option C would be the best of course. However if time is short I'm fine with A.
A is still better than B IMO.

**Comment by tessus** [comment]
@ChristophWurst 

> with the move to mandatory 2FA

What does this mean exactly? Are you going to force nextcloud users to use 2FA in the future?
I don't understand the _mandatory_ part.

**Comment by rullzer** [comment]
@tessus no but we'll add the possibility for admins to make 2FA mandatory for all users or some groups.

**Comment by tessus** [comment]
@rullzer Thanks for clearing this up. The above description did not mention this.

This will be a nice feature. 👍

**Comment by rullzer** [comment]
Fixed with https://github.com/nextcloud/server/issues/11462 and https://github.com/nextcloud/server/issues/11549
