### ISSUE TITLE
Can't find "app order" app in the admin panel / user menue

### ISSUE THREAD

**Issue by blu-IT** [nextcloud/server#11382]
### Steps to reproduce
1. Installed app "app order"
2. Searched admin panel for config menue of app order
3. Can not find it

### Expected behaviour
App order should be visible somewhere in the admin panel, at least in "additional settings"

### Actual behaviour
It is not there.

Regards,
Ivan

### Server configuration

**Operating system**:

**Web server:**

**Database:**
MySQL

**PHP version:**
7.1

**Nextcloud version:** (see Nextcloud admin page)
14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
nextcloud.com

**Comment by weeman1337** [comment]
@blu-IT thanks for the report. Unfortunately this tracker is for the basic Nextcloud functions only.

Could you please create an issue here https://github.com/juliushaertl/apporder/issues so it's in the right place and the app author sees it directly?

**Comment by weeman1337** [comment]
@blu-IT I had a quick look: The app isn't compatible with Nextcloud 14. That's the reason why you don't see it. I added an issue for that: https://github.com/juliushaertl/apporder/issues/67

**Comment by blu-IT** [comment]
Hi weeman1337,

thanks for the feedback!

OK, I thought while apporder is displayed in the store, it would be compatible. 
It also gave me no error while installing.

Thanks for your effort!

**Comment by weeman1337** [comment]
@blu-IT could you please re check if it's working now?

**Comment by blu-IT** [comment]
@weeman1337 Hi, works fine now. Thanks!
