### ISSUE TITLE
[Mandatory 2FA] Spec: User settings interface

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#11381]
**Mandatory 2FA in Nextcloud 15**

Overview/progress board: https://github.com/orgs/nextcloud/projects/17

:rocket: 

---

# Specification: User settings interface

Until now, two-factor providers in Nextcloud register their own individual settings on the security page/section. This isn't necessarily bad, but I think we could consolidate their individual sections into a new *Two-Factor Auth* section.

One possible way to implement this would be to not register settings via info.xml by the providers themselves, but offer an interface that extends `IProvider`, like

```php
<?php

namespace OCP\Authentication\TwoFactorAuth;

use OCP\IUser;

interface IProvidesPersonalSettings extends IProvider {

	/**
	 * @return TemplateResponse
	 */
	public function getPersonalSettingsTemplate(IUser $user): TemplateResponse;

}
```

This change would allow us to structure the 2FA settings in a more logical way, e.g. by showing the backup codes on top.

While doing this change, we could also one step further and create a more complex settings mechanism that ensures providers are displayed in a consistent way (as opposed to rendering an arbitrary template and hoping that the structure is okay).

This could looks like this:

```php
namespace OCP\Authentication\TwoFactorAuth;

use OCP\IUser;
use OCP\Template;

interface IProvidesPersonalSettings extends IProvider {

	public function getPersonalSettings(IUser $user): IProviderPersonalSettings;

}

interface IProviderPersonalSettings {

	public function getIcon(): String;

	public function getBody(): Template;

}
```

Then we can use implementation of `IProvidesPersonalSettings` and `IProviderPersonalSettings` to render a (list?) of providers with
* Their icon
* Their name
* Their description
* Their body for the custom settings (the template)

cc @blizzz @jancborchardt @MorrisJobke @rullzer

**Comment by blizzz** [comment]
When it is possible to boil it down to  custom set of elements and behaviour, i am all for providing the second mechanism. For consistency, and easiser/safer implementation.
