### ISSUE TITLE
Workflow examples / extension

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#11388]
We would like to emphasize the use of the workflow engine more. Right now an complete part is the autotagger.  It would be nice and powerful to create other flows, for instance file conversion, auto-sharing, notifications, or others. 

Essentially it is about adding a "Then" to the current UI, which is initiated by the files_autotagging.

I'd propose to move the user facing parts all to the workflowengine, with changing the possible action to a flexible solution by adding an "Add action" button below the rules, withing the rule group.

This will only be shown when at least one WorkflowActionProvider is registered. the files_autotagger will be one. And we write another one (the pdf converter) as a single app as reference example.

Mockup:

![screenshot_20180926_130916](https://user-images.githubusercontent.com/2184312/46076281-60009300-c18d-11e8-83b6-76bc3a8fb362.png)

Reasonable? @nextcloud/designers @nickvergessen @skjnldsv @MorrisJobke

**Comment by nickvergessen** [comment]
The files_accesscontrol currently also uses the workflow_engine as well as the UI parts.
The main problem is how to do the technical implementation of the actions, without too much overhead, iirc that was the reason why it was done in the current way and autotagging and accesscontrol have their own storagewrapper etc.

**Comment by blizzz** [comment]
Thanks for the hint about files_accesscontrol, that's a good point.

In the end they'd still have the custom parts, mostly more of the UI bits would have been moved. It's indeed less than I though in first place, diminishing the advantages.

So after consideration, okay, let's scrap my idea. I'll just add the named examples. They'll get their own sections in the admin settings and the boilerplate code is not soo much after all. The only thing that would be nice would be to convert the javascript code to Vue. Since this sits on a backbone stack, no, thanks, no. Since I am not at home there, it would take me just too long. (fyi @skjnldsv – if you veto find me someone to do it, please…).

**Comment by jospoortvliet** [comment]
Just want to add a few actions I'd like to see.
Especially some very simple file actions like 'move/copy file to folder X' or 'delete file' (a more generic form of the Retention app which deletes based on tag & date). And the share and notifications you mention.
Others are a bit more involved, like the conversion to pdf you mention or the generic 'execute script'... 

In the 'if' part, I'd like to see special folders: a file moved in a certain folder can get auto-tagged or otherwise trigger execution of stuff. That is currently missing.

**Comment by blizzz** [comment]
> Just want to add a few actions I'd like to see.

Sure, we can write any arbitrary other app, after the release.

**Comment by blizzz** [comment]
The PDF converter workflow app resides here https://github.com/nextcloud/pdf_converter

**Comment by blizzz** [comment]
both apps are shipped → closing
