### ISSUE TITLE
Stuck Waiting for cron to finish when upgrading from 14.0 to 14.0.1

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#11392]
I ran into the exact issue as this post here: https://help.nextcloud.com/t/upgrade-to-14-0-1/37679/3

By running `sudo -u www-data php /var/www/nextcloud/update/updater.phar` and going through the steps, on the part where it asks if you want to run occ upgrade, I say yes and it just repeatedly prints "Waiting for cron to finish (checks again in 5 seconds) ..."

Like the original post, I tried the exact same steps:

1. Cancel the updater using Ctrl + C
1. Run `sudo -u www-data php /var/www/nextcloud/occ upgrade` which results in the exact scenario as above
1. Cancel the manual occ upgrade and run `sudo -u www-data php /var/www/nextcloud/cron.php` which runs and exits immediately without errors
1. Try running the updater.phar again with the same results

Following the workaround that was found, I also had success in completing the update. For some reason I had to manually run `UPDATE oc_jobs SET reserved_at=0;` against the database in order to proceed, but now everything is working again.

**Comment by benhartwich** [comment]
Same here.

**Comment by bcutter** [comment]
Mee too :-(

**Comment by linucksrox** [comment]
Oops, I didn't find it before posting this, but issue #10949 already includes details about the problem and discussion about fixing it. I'll close this for now.

**Comment by bcutter** [comment]
Same again when updating from v14.0.1.1 to v14.0.3.0. Needed to work around once again.
