### ISSUE TITLE
Insufficient user feedback / information on vcard import failures

### ISSUE THREAD

**Issue by gohrner** [nextcloud/server#11394]
### Steps to reproduce
1. Import vcard file with several valid and invalid vcards (caused by bugs in the application(s) generating this file)
2. The import for the invalid cards fails, showing only a few-word popup message that the import of some card failed.

### Expected behaviour
The error message should provide understandable information about which card(s) failed to 
import, and optimally, why. This information should be accessible to the user who initiated the import of the faulty file

### Actual behaviour
The error message basically only says "didn't work" a few times, but it does not indicate at all for which vcards the import failed, nor does it give any summary information after the import which tells how many failures we got.

Also the NextCloud error log (which probably is not accessible for the normal user?) visble from the web interface contains an entry for each failed card, but it's still not possibly to derive the actual cards which failed based on the information in the log as the vcard data there is abbreviated in a way which makes them unidentifiable.

(The log file stored on the server contains the necessary information, but really is not accessible to any user except the NextCoud sys admin.)

I understand that it's probably not easy to provide information about which cards failed as just those cards could not be processed and the information within possibly cannot be extracted because of this.

Still, the current behaviour is very unsatisfying. I'm an experienced software developer and (less experienced) sysadmin and could trace the problem down to illegal vcard property names contained in the affected cards, but any less experienced user would be stuck, I fear.

### Server configuration

**Operating system**: Debian GNU/Linux Stretch

**Web server:** Apache 2.4

**Database:** MariaDB 10.1

**PHP version:** 7.0

**Nextcloud version:** 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tar.gz

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - polls: 0.8.3
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.ohrner.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.ohrner.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** currently only local users

### Client configuration
Irrelevant

#### Web server error log
Not relevant

#### Nextcloud log (data/nextcloud.log)
Contains the relevant information, see above.

#### Browser log
Not relevant

**Comment by skjnldsv** [comment]
Invalid repo, should be on the contacts repo.
Existing issue there: https://github.com/nextcloud/contacts/issues/990
