### ISSUE TITLE
Provide avatar URL on share information

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11406]
Currently we "only" get infos on user who shared with "me" separate, via
http://localhost/nc/ocs/v2.php/apps/files_sharing/api/v1/shares?path=/123&reshares=true&subfiles=true&shared_with_me=true

```
…
<uid_owner>test</uid_owner>
<displayname_owner>test</displayname_owner>
…
```

Every client now has to build the avatar url by its own.

As discussed with @schiessle, this should be simplified, so that the avatar url is generated on server side and clients can directly retrieve them.

~~Please with eTags :+1:~~
And, if possible, for all users listed in the response (sharee and share owner)

(planned for NC15)

**Comment by schiessle** [comment]
cc @rullzer maybe also something for you if you have some time. It is probably not that hard, someone "just" need to find the time to do it :wink:

**Comment by rullzer** [comment]
Adding the URL there should not be that hard. But adding the etag is a bit hard and a bit weird. It requires a lot of additonal logic with no real point imo.

I'd vote to just add the link to the avatar.
Then you can do the logic you want yourself. You can show the cached avatar and try to fetch a new one in the back etc.

**Comment by tobiasKaminsky** [comment]
The idea with eTag was that clients then do not have to query the avatar url as they directly know if an avatar is out of date.
But if eTags are too hard, then we can remove it.
(eTag on avatar is already in place, but only when calling/downloading it and we use it there already)

**Comment by tobiasKaminsky** [comment]
Can we have this for NC17? Please :-)

**Comment by skjnldsv** [comment]
Is this still needed?
You have the owner uid, you shouldn't need anything else, no?
We don't use it for the server sidebar, so I guess it's fine now?

**Comment by tobiasKaminsky** [comment]
True, this is already done via nc:sharees.
