### ISSUE TITLE
Error in querying "'ALTER TABLE `activity` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin" during update to 14.

### ISSUE THREAD

**Issue by Toover** [nextcloud/server#11407]
### Steps to reproduce
1. Had migrated from owncloud to nextcloud prior to this.
2. Was on 13.x then.
3. Launched the web update
4. At the end of the preparation phase, disabled command line maintenance mode (went to web-only).
5. Started the update.

### Expected behaviour
Update works.

### Actual behaviour
Fails, with the message:
```Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `activity` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1118 Row size too large. The maximum row size for the used table type, not counting BLOBs, is 65535. You have to change some columns to TEXT or BLOBs```

### Server configuration

**Operating system**:
Synology OS (Linux).

**Web server:**
Apache.

**Database:**
MySQL (MariaDB).

**PHP version:**
5-ish.

**Nextcloud version:** (see Nextcloud admin page)
13 to 14.

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated.

**Where did you install Nextcloud from:**
Can't remember.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/activity/issues/367 for 2 queries to fix the problem. Afterwards the repair step should run fine
