### ISSUE TITLE
The app content width is forced to the app navigation width in IE 11

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#11403]
In IE 11 [the app content width is forced to the app navigation width](https://github.com/nextcloud/server/blob/0274507cb10b53cfd38bd0ae3810c26cdb172ad1/core/css/ie.scss#L5-L7). This looks like a typo; probably the CSS selector should be `app-navigation` instead of `app-content`.

However, maybe the whole rule can be simply removed; I have no idea why those rules are needed (and probably they are not given that currently the width of the navigation bar is not modified in IE 11). [The commit in which they were introduced](https://github.com/nextcloud/server/commit/da0bdd1391d86046662e3e3cee046a48ffb58d22) does not give me any hint either :-( @skjnldsv (and anyone reading this ;-) ) you do not need to be as horribly verbose as I am :-P but please, try to describe what is fixed and why in the commit message, and do not mix fixes for different things in the same commit, use separate commits ;-)

In any case, note that, even if `app-content` is forced to the width of the navigation bar, the issue is not usually visible. The reason is that by default `content`, the parent of `app-content`, [is shown using a flex display](https://github.com/nextcloud/server/blob/8f9571bc3b6f2ced6383e2a617583399f7efbbdd/core/css/apps.scss#L589), which ignores the `width` property and uses the `flex-basis` property instead (or, at least, it does in IE 11; I do not know if all browsers behave like that, but as the rule is applied only in IE 11 it does not matter ;-) ). However, the issue can be seen in the PDF viewer, as in that app [the `display` property of `content` is overriden to `block`](https://github.com/nextcloud/files_pdfviewer/blob/fc4a395a504f3e09e687808c6ffa0e784f0fc4e0/css/style.css#L6).

@nextcloud/designers

**Comment by jancborchardt** [comment]
@danxuliu @skjnldsv so what do we do about this one? :) Change the selector to #app-navigation? Or remove the whole rule?

**Comment by danxuliu** [comment]
>  so what do we do about this one? :) Change the selector to #app-navigation? Or remove the whole rule?

I have no idea, that is why I opened an issue instead of a pull request :-P I gave you the facts, now you make the decision :-P

**Comment by skjnldsv** [comment]
Three devs, 1 line of code!
WHO WIN!? WHO LOOSE!?
