### ISSUE TITLE
User quota show wrong value

### ISSUE THREAD

**Issue by maghog** [nextcloud/server#11415]
When setting a quota value higher than 14 GB it show 14.3 GB.

Example: set user quota to 30 GB. When user login it show max quota as 14.3 GB.

Tested both local and LDAP users.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.30

**Nextcloud version:** 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 13.0.6

**Comment by MorrisJobke** [comment]
> Example: set user quota to 30 GB. When user login it show max quota as 14.3 GB.

Is it possible that your disk is full? The shown quota is always the minimum of the two values: 

* quota - used space
* available space on disk

If the second option is smaller than the remaining space it will only show this. So this is wanted behavior.

**Comment by maghog** [comment]
Quite right, wondering how I could miss this?
Thanks...
