### ISSUE TITLE
create folder icon overlay issue

### ISSUE THREAD

**Issue by pcvengros** [nextcloud/server#11420]
### Steps to reproduce
1. click on "create folder" or "plus" icon
2.
3.

### Expected behaviour
overlay at icon position should be showed

### Actual behaviour
only the top part of overlay is showed, rest is hidden and therefor you are unable to create folder

### Server configuration

**Operating system**:
CentOS7

**Web server:**
NGINX

**Database:**
MariaDB

**PHP version:**
7.1.21

**Nextcloud version:**
14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.0

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - twofactor_u2f: 1.6.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - firstrunwizard
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "trusted_domains": [
            "cloud.grass.sk",
            "cloud.securcom.sk",
            "cloud.uxsolutions.sk",
            "86.110.234.231"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "overwrite.cli.url": "https:\/\/cloud.uxsolutions.sk",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
core.js?v=0852235e-7:7 JQMIGRATE: Migrate is installed, version 1.4.0
merged-template-prepend.js?v=0852235e-7:4478 querying Whats New data was successful: nocontent
merged-template-prepend.js?v=0852235e-7:4479 undefined
search.js?v=0852235e-7:66 New search handler registered
```
</details>

**Comment by pcvengros** [comment]
![nextcloud-bug1](https://user-images.githubusercontent.com/6336945/46162353-4132f700-c288-11e8-846b-6cdae47f5a00.png)

see red "circle"

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
@pcvengros could clear your cache and do a `occ maintenance:repair` on your sever? :)

**Comment by skjnldsv** [comment]
Hi! Before we continue, please do the following steps:
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. run an `occ maintenance:repair` on your server 

Thanks :wink:

**Comment by pcvengros** [comment]
> Hi! Before we continue, please do the following steps:
> 
> 1. [clear your browser's cache](https://www.refreshyourcache.com/)
> 2. run an `occ maintenance:repair` on your server
> 
> Thanks 😉

1. done
2. done
` - Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Remove shares of a users root folder
 - Move .step file of updater to backup location
 - Fix potential broken mount points
     - No mounts updated
 - Repair invalid paths in file cache
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - SCSS cache cleared
     - JS cache cleared
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Repair pending cron jobs
     - No need to repair pending cron jobs.
 - Fix component of birthday calendars
     - 9 birthday calendars updated.
 - Fix broken values of calendar objects
    0 [>---------------------------]
 - Registering building of calendar search index as background job
     - Repair step already executed
 - Delete orphaned ACL rules
 - Write default encryption module configuration to the database
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Purify and migrate collected mail addresses
    0 [>---------------------------]
 - Update OAuth token expiration times`

result: same thing....

**Comment by pcvengros** [comment]
see screenshot
![nexcloud-issue](https://user-images.githubusercontent.com/6336945/46275859-a1fb5180-c55e-11e8-94b2-60cca1b71908.png)

**Comment by skjnldsv** [comment]
Yup, not a design issue, more like a js one :)

**Comment by pcvengros** [comment]
issue still persists
update:
- nextcloud-15.0.2
- php-7.2
- redis used for caching and locking
- nginx-1.14.2

OS: CentOS 7.6.1810

**Comment by skjnldsv** [comment]
@pcvengros Sorry, I really have no idea what's causing this. You don't have anything failing on your console, nor the network log... I need to dig onto it! :confused:

**Comment by pcvengros** [comment]
currently I have nextcloud 15.0.4, same issue
if needed I can give you account there and you can check it out your self and see how it is behaving

**Comment by skjnldsv** [comment]
@pcvengros yes, I would like that. Send it to skjnldsv@protonmail.com please :)
I'll try to dig into it this week!

**Comment by pcvengros** [comment]
> @pcvengros yes, I would like that. Send it to [skjnldsv@protonmail.com](mailto:skjnldsv@protonmail.com) please :)
> I'll try to dig into it this week!

done, sent to your email

**Comment by skjnldsv** [comment]
@pcvengros Hello!
It seems that your webserver is refusing to serve ttf, woff2 and html.
The html is actually what is causing the issue.

Could you post your webserver config please?

**Comment by pcvengros** [comment]
nginx configuration file:

`
server {
        listen 443 ssl http2 default_server;
        listen [::]:443 ssl http2 default_server;
        root /var/www/cloud;

        index index.php;

        server_name XXXXXXXXXXXXXXXX;

        location ~ /.well-known {
                allow all;
        }

        ssl_certificate /etc/letsencrypt/live/XXXXXXXXXXXXXXXX/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/XXXXXXXXXXXXXXXX/privkey.pem;
        ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
        ssl_prefer_server_ciphers on;
        ssl_ciphers EECDH+CHACHA20:EECDH+AES128:RSA+AES128:EECDH+AES256:RSA+AES256:EECDH+3DES:RSA+3DES:!MD5;
        ssl_dhparam  /etc/nginx/ssl/dhparam.pem;

        ssl_session_timeout 1d;
        ssl_session_cache shared:SSL:50m;
        ssl_stapling on;
        ssl_stapling_verify on;
        resolver 8.8.8.8 8.8.4.4;

        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload;" always;
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;
        add_header Referrer-Policy "no-referrer-when-downgrade";

        client_max_body_size 10G; # set max upload size
        fastcgi_buffers 64 4K;

        # Enable gzip but do not remove ETag headers
        gzip on;
        gzip_vary on;
        gzip_comp_level 4;
        gzip_min_length 256;
        gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
        gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+j
son application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

        error_page 403 /core/templates/403.php;
        error_page 404 /core/templates/404.php;

        location = /.well-known/carddav {
                return 301 $scheme://$host/remote.php/dav;
        }

        location = /.well-known/caldav {
                return 301 $scheme://$host/remote.php/dav;
        }

        location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
        }

        location ~ ^/(build|tests|config|lib|3rdparty|templates|data)/ {
                deny all;
        }

        location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
                deny all;
        }

        location / {
                rewrite ^ /index.php$uri;
        }

        location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
                fastcgi_split_path_info ^(.+\.php)(/.*)$;
                include fastcgi_params;
                fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                fastcgi_param PATH_INFO $fastcgi_path_info;
                fastcgi_param HTTPS on;
                #Avoid sending the security headers twice
                fastcgi_param modHeadersAvailable true;
                fastcgi_param front_controller_active true;
                fastcgi_pass unix:/var/run/php-fpm/php.sock;
                fastcgi_intercept_errors on;
                fastcgi_request_buffering off;
        }

        location ~ ^/(?:updater|ocs-provider)(?:$|/) {
                try_files $uri/ =404;
                index index.php;
        }

        # Adding the cache control header for js and css files
        # Make sure it is BELOW the location ~ \.php(?:$|/) { block
        location ~* \.(?:css|js|woff|svg|gif)$ {
                try_files $uri /index.php$uri$is_args$args;
                add_header Cache-Control "public, max-age=15778463";
                access_log off;
        }

        # Optional: Don't log access to other assets
        location ~* \.(?:jpg|jpeg|bmp|ico|png|swf)$ {
                try_files $uri /index.php$uri$is_args$args;
                access_log off;
        }
}

server {
        listen         80;
        listen    [::]:80;
        server_name    cloud.uxsolutions.sk;

        location ~ /.well-known {
                allow all;
        }

        return         301 https://$server_name$request_uri;
}
`

**Comment by skjnldsv** [comment]
Please have a look at https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html?highlight=nginx#nextcloud-in-the-webroot-of-nginx
This is a perfectly working example :)
Try it and keep me updated please :wink:

**Comment by pcvengros** [comment]
> Please have a look at https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html?highlight=nginx#nextcloud-in-the-webroot-of-nginx
> This is a perfectly working example :)
> Try it and keep me updated please 😉
> 
> PS: could you also check that the file `core/search/templates/part.results.html` exists on your server?

Thanks!

problem was in wrong use of "/" instead of correct "\/" in few lines.
