### ISSUE TITLE
loglevel 1 doesn't log sucessful logins even with logging/auditing app installed

### ISSUE THREAD

**Issue by nexus186** [nextcloud/server#11440]
I have the logging/auditing app installed, set the loglevel to 1 and the log location to /var/log/nc.log

I can confirm it is logging to nc.log. However, successful logins are still not being logged. It does not show up in the log. 

Is this a bug?

**Comment by abelmferreira** [comment]
+1 Same with me!
Only failed logins, brutal force, and general system errors and warnings
