### ISSUE TITLE
install fo nc 14.0.1 fails on updating apps

### ISSUE THREAD

**Issue by Danfro** [nextcloud/server#11443]
I tried to install a fresh new nc 14.0.1 to my webspace using the setup-nextcloud.php script.
After filling in the forms at the setup page I was told that I have to update all apps. After doing so I did get the following error message:

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_share` SET `password` = `share_with` WHERE (`share_type` = ?) AND (`share_with` IS NOT NULL)' with params [3]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password' in 'field list'

**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.2
**Nextcloud version:**
14.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
setup-nextcloud.php, downloaded today

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
