### ISSUE TITLE
Make app navigation narrower 

### ISSUE THREAD

**Issue by realies** [nextcloud/server#11469]
It seems excessively wide right now at 300px, reducing by 100 would be great.

<img width="358" alt="screenshot 2018-09-30 at 12 59 26" src="https://user-images.githubusercontent.com/5107843/46256241-af5a0280-c4b0-11e8-819d-c8b3e893c5ee.png">

**Comment by skjnldsv** [comment]
Hi!
Sorry, this was a recent decision to ensure there is enough room for the favourites and the new sharing section on the navigation.
We cannot really make it dynamic because this is too complicated and we think 300 is a good alternative now :)

@jancborchardt

**Comment by pixelipo** [comment]
Personally, I find the Files' app sidebar the least useful of any NC application - you can't add bookmarked folders and none of the predefined items in that list are of much use to me. Mail, Tasks, Desk, Calendar all have way more information-filled sidebars.

Deck has a `toggleSidebar` icon/function which works quite well. The only thing missing is "Remember the last position" feature - sidebar pops back out every time you leave Deck and return to it afterwards.

So maybe something like that should be added as an option to all apps?

**Comment by jancborchardt** [comment]
Having used it for some time I also totally agree that the 300px is too much, also in other apps. Previously it was 250px and it seemed better.

> Deck has a toggleSidebar icon/function which works quite well. The only thing missing is "Remember the last position" feature - sidebar pops back out every time you leave Deck and return to it afterwards.
> So maybe something like that should be added as an option to all apps?

@pixelipo I also agree this is a good idea, given it does indeed remember the last position. However, this is a slightly different topic and the width of the left sidebar itself has to be addressed too.


> We cannot really make it dynamic because this is too complicated and we think 300 is a good alternative now :)

@skjnldsv I’ve been thinking there and while the ability to manually resize it would be over-the-top, making it truly responsive and adjusting to the viewport width would be nice. The right sidebar already does this to a limited extent.

What does everyone think?

**Comment by skjnldsv** [comment]
@jancborchardt Oh I'm all in favor of it being dynamic!
But we have better priorities I think.
The best alternative which is fast and ok imho, would be to set a min/max and set the width to something based on the viewport width. This would do the trick properly!
But the appnav is fixed, so dynamic based on content is out of the equation I guess :/

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
