### ISSUE TITLE
NC 14 div#navigation.menu width

### ISSUE THREAD

**Issue by Gabuzomeuh** [nextcloud/server#11468]
Hi.

Navigation menu needs to be 4px wider in order to avoid horizontal scrollbar.

![navigation](https://user-images.githubusercontent.com/43717831/46254536-4020e600-c491-11e8-964c-793dad3aa348.jpg)

### Server configuration

**Nextcloud version:** 14.0.1

**Updated from:** 13.0.6

**Where did you install Nextcloud from:** webinstall script

**Theme used:** default

### Client configuration

**Browser used:** Firefox 62.0 (64 bits)

**OS used:** Linux Mint 17.3 Cinnamon & Linux Mint 19 Cinnamon

### Temporary workaround

Using the "Custom CSS" app to resize the menu

`#header .header-left > nav > #navigation {
	position: relative;
	left: 25px; /* half the togglemenu */
	transform: translateX(-50%);
	width: 164px;
}`

**Comment by MorrisJobke** [comment]
cc @skjnldsv @jancborchardt

**Comment by weeman1337** [comment]
I'm on it. Additional steps to reproduce the issue:
- Have an app with a long name in the list
- Have that many apps you have to scroll
