### ISSUE TITLE
Missing-index

### ISSUE THREAD

**Issue by TinTinMar515** [nextcloud/server#11463]
Hi,
I recently upgrade my server from Nextcloud 13 to 14 and the warning security configuration told me to run : occ db: add-missing-index
but the command appears to be not the good one.
I ran : 
sudo -u www-data php occ db:add-missing-indices
After it was done, everything seems to be ok.
Sorry for my English and thank you for your work,

**Comment by MorrisJobke** [comment]
> but the command appears to be not the good one.
> I ran :
> sudo -u www-data php occ db:add-missing-indices
> After it was done, everything seems to be ok.
> Sorry for my English and thank you for your work,

Thanks for this feedback. The command then gives you more hints, because depending on your setup the user you need to run this under could be named differently. So I would leave this as it is, because the `occ` command gives you further and more correct hints what to do.

**Comment by TinTinMar515** [comment]
Yes but the errors is the proposal :
occ db: add-missing-index
instead of :
occ db:add-missing-indices

There is a space betwen bd: and add 
and its index instead of indices.
Sorry to insist.

**Comment by danielkesselberg** [comment]
When you report issues with translations it might be good to report the language you use for nextcloud. I did `grep -R "add-missing-index"` but could not find any place. I guess this has been solved but not released yet.

**Comment by MorrisJobke** [comment]
> When you report issues with translations it might be good to report the language you use for nextcloud. I did `grep -R "add-missing-index"` but could not find any place. I guess this has been solved but not released yet. Thank you for reporting 👍

Same here - I could not find it in the code.
