### ISSUE TITLE
/theme/example/default.php

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#11486]
Nextcloud 14

/themes/example/default.php

=> https://www.blackysgate.net/nextcloud/index.php/s/LrWrGfGgT8dxeGw

" get your free Account "  at bottom, should included in themes/example/default.php

because this is foreign advertising for Nextcloud login, 
if anyone hosting his own Cloud and this is into with a wrong link, 
ist es malicious deception and does not refer to the stationary Cloud..
So what must be timely fixed.

Also "Nextcloud - a save place for you Data" this is also a foreign link

best regards
Blacky

**Comment by danielkesselberg** [comment]
Does anyone of the links below help?
https://github.com/nextcloud/server/issues/11198
https://github.com/nextcloud/server/issues/11327
https://github.com/nextcloud/server/issues/11101

**Comment by jancborchardt** [comment]
Thanks @danielkesselberg, indeed the solution is found at this issue (it’s a config setting):
https://github.com/nextcloud/server/issues/11101#issuecomment-419394789

**Comment by blackcrack** [comment]
thank you :+1:

**Comment by jancborchardt** [comment]
@blackcrack yes, best open an issue in the registration app repository.  The app could inject a different link to use for the "Get your own Nextcloud" text.

**Comment by blackcrack** [comment]
@jancborchardt 
mhh, it should be also to able to setting up other links, alone because this should it be 
possible to edit the link to setting up an own config . 
The if this issue it is to give the Admin at hand the possible to setting up this link :)

config.php
```
'nctextlink' => "https://nextcloud.com";
'nclinktext' => "Get your own Nextcloud";
```
and default in the configuration, to give the possible for changing :)
is this not a idea, isn't it ? :)

best regards
Blacky

**Comment by geonom** [comment]
The issue is this link existing on my installation, as I found out just now when I shared a file with a group. I was shocked to be honest that there was an advertisement placed there without my consent.

Please remove this or at least make it optional in a setting and set it off by default. I don't mind advertising for nextcloud, but I want to do it voluntarily, not be forced into it!

**Comment by blackcrack** [comment]
:+1:  this should be able for customizing
