### ISSUE TITLE
OCC commands in shared hosting! "occ db: add-missing-indices"

### ISSUE THREAD

**Issue by ddi98** [nextcloud/server#11491]
### Steps to reproduce
Hi, I use nextcloud on a shared hosting and since I upgraded to version 14.0.1 the indexes are no longer updated in the database and to update them I should launch this command occ db: add-missing-indices, but I can not do it since I use a shared hosting! Could you work on this problem that affects a large slice of users? thank you so much

### Server configuration

**Operating system**: CentOS

**Web server:** Hosting Linux Aruba

**Database:** MySql

**PHP version:** 7.2.8

**Nextcloud version:** 14.0.1

**Comment by realies** [comment]
Can second that. Happened on all instances I have updated.

**Comment by MorrisJobke** [comment]
> Hi, I use nextcloud on a shared hosting and since I upgraded to version 14.0.1 the indexes are no longer updated in the database and to update them I should launch this command occ db: add-missing-indices, but I can not do it since I use a shared hosting! Could you work on this problem that affects a large slice of users? thank you so much

There is a reason why this is a CLI command: it could take a bigger amount of time to complete and getting this command killed by the Webserver would result in a broken DB. Thus we added it to the CLI interface. Also if you run on a shared hosting instance there is not so much performance impact because usually those instances aren't that huge and only serve a handful of users. This optimization is basically for large instances that take advantage when sharing pages have hundreds of thousands of entries.

But we can check on showing the SQL statements that are needed to add those indexes then.

cc @nickvergessen @rullzer

**Comment by ddi98** [comment]
Mine is not a large instance but still hosts 500 users and 200 GB of files. This operation could be completed without problems during web browsing, to avoid the timeout you could separate this operation from the web update and you could allow to run it optionally later "it could be a good solution"

PS: Would there be a way to directly perform this operation from phpMyAdmin?

**Comment by MorrisJobke** [comment]
> to avoid the timeout you could separate this operation from the web update and you could allow to run it optionally later "it could be a good solution"

There is no way to separate this from web requests if there are only web requests possible. The CLI would be the timeout-free approach ;)



> PS: Would there be a way to directly perform this operation from phpMyAdmin?

I will link some resources where SQL statements could be build from so the message can be improved.

**Comment by nickvergessen** [comment]
Current queries to run are:
```sql
ALTER TABLE `oc_share` ADD KEY `share_with_index` (`share_with`) USING BTREE;
ALTER TABLE `oc_share` ADD KEY `parent_index` (`parent`) USING BTREE;
ALTER TABLE `oc_filecache` ADD KEY `fs_mtime` (`mtime`) USING BTREE;
```

**Comment by ddi98** [comment]
Thanks a lot to everyone for the availability!
You could provide more details on how to perform queries (for those who are not a web expert like me)

**Comment by nickvergessen** [comment]
Well you better google that or ask for help in the forums. We can't really give you support on administration side of things in our bugtracker.

**Comment by ddi98** [comment]
you're right, however it was simpler than I thought :)!
PS: when I perform this operation, do I have to put the instance into maintenance? thank you

**Comment by MorrisJobke** [comment]
> PS: when I perform this operation, do I have to put the instance into maintenance? thank you

Not needed. The DB handles this properly.

**Comment by MorrisJobke** [comment]
Let's close this ticket here for now as there are the SQL statements.

**Comment by ddi98** [comment]
I launched the query on the database the result was the following:

ALTER TABLE `oc_share` ADD KEY` share_with_index` (`share_with`) USING BTREE; # MySQL returned an empty set (i.e. zero lines).

ALTER TABLE `oc_share` ADD KEY` parent_index` (`parent`) USING BTREE; # MySQL returned an empty set (i.e. zero lines).

ALTER TABLE `oc_filecache` ADD KEY` fs_mtime` (`mtime`) USING BTREE; # MySQL returned an empty set (i.e. zero lines).

Was this the result to be obtained?

**Comment by realies** [comment]
Assuming there could be code that can estimate if the query could be successful given the maximum script execution time configuration. If that is within the estimated limit, the query could be executed in the browser. In several of the instances, I have updated it took between 2-10 seconds to complete.

**Comment by ddi98** [comment]
Thank you have a nice day !

**Comment by realies** [comment]
@ddi98, is the warning gone from Nextcloud after you ran the query? If not, are you running it against the Nextcloud database?

**Comment by MorrisJobke** [comment]
> Assuming there could be code that can estimate if the query could be successful given the maximum script execution time configuration. If that is within the estimated limit, the query could be executed in the browser. In several of the instances, I have updated it took between 2-10 seconds to complete.

I'm not aware of any estimations like this. :/

**Comment by ddi98** [comment]
the warning was returned by phpmyadmin

**Comment by MorrisJobke** [comment]
> Was this the result to be obtained?

Looks good, because adding an index does not return anything.

**Comment by realies** [comment]
@MorrisJobke, assuming the amount of time required for a query of that type to complete is based on the number of records in the given table. Thinking about it, that doesn't say much about the speed of database procedures (disk IOPS, ram, available CPU time, etc)...

**Comment by ddi98** [comment]
In any case, the request turns out to be much more powerful!

**Comment by FireEmerald** [comment]
The queries are working as expected, adding the indexes and the warning is gone after execution.

**Comment by bunducafe** [comment]
Interesting. After running the DB commands successfully on my 14.0.4 instance I now get an internal server error and cannot access the nextcloud installation at all.

Any hints? Even if it is off-topic here?

**Comment by Tom-2019** [comment]
The three queries mention above  solved three issue. The following remain

    Fehlender Index "owner_index" in der Tabelle "oc_share".
    Fehlender Index "initiator_index" in der Tabelle "oc_share".

**Comment by ddi98** [comment]
> Current queries to run are:
> 
> ```sql
> ALTER TABLE `oc_share` ADD KEY `share_with_index` (`share_with`) USING BTREE;
> ALTER TABLE `oc_share` ADD KEY `parent_index` (`parent`) USING BTREE;
> ALTER TABLE `oc_filecache` ADD KEY `fs_mtime` (`mtime`) USING BTREE;
> ```

Hello, I reopened the discussion to which you gave me solution some time ago :), after updating to nextcloud 15.0.2 a similar problem has resurfaced, would you be so kind to help me? :)

these are the errors:

The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
Missing index "owner_index" in table "oc_share".
Missing index "initiator_index" in table "oc_share".

-----

Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.
filecache.fileid
filecache.storage
filecache.parent
filecache.mimetype
filecache.mimepart
filecache.mtime
filecache.storage_mtime
mimetypes.id
storages.numeric_id

**Comment by FireEmerald** [comment]
> But we can check on showing the SQL statements that are needed to add those indexes then.

@MorrisJobke Is there any open issue which tracks your idea? Because i - any many others, which are unable to use the occ component, would really appreciate if you would provide the required SQL commands right with the error inside the settings page of nextcloud (or at least a link).

**Comment by MorrisJobke** [comment]
> @MorrisJobke Is there any open issue which tracks your idea? Because i - any many others, which are unable to use the occ component, would really appreciate if you would provide the required SQL commands right with the error inside the settings page of nextcloud (or at least a link).

Not really - let's reopen this for now.

**Comment by FireEmerald** [comment]
It's really frustrating to google for the queries after each update. Is there any document available which is always up-to date and lists the queries which must be executed after each update?

As it seems that this is not going to be implemented in the near feature, isn't it?

**Comment by MichaSei** [comment]
ich habe folgende Fehlermeldung (leider keine Lösung ergoogled) wenn ich in meinem phpmyadmin dies hier eingebe:

> ALTER TABLE `oc_share` ADD KEY `share_with_index` (`share_with`) USING BTREE;
> ALTER TABLE `oc_share` ADD KEY `parent_index` (`parent`) USING BTREE;
> ALTER TABLE `oc_filecache` ADD KEY `fs_mtime` (`mtime`) USING BTREE;

Fehler
SQL-Befehl:


ALTER TABLE `oc_share` ADD KEY `share_with_index` (`share_with`) USING BTREE
MySQL meldet: Dokumentation

#1061 - Doppelter Name für Schlüssel vorhanden: 'share_with_index'

Was kann ich noch machen um mein Problem zu lösen?

**english:**

I have the following error message (unfortunately no solution ergoogled) if I enter this in my phpmyadmin this:

> ALTER TABLE `oc_share` ADD KEY` share_with_index` (`share_with`) USING BTREE;
> ALTER TABLE `oc_share` ADD KEY` parent_index` (`parent`) USING BTREE;
> ALTER TABLE `oc_filecache` ADD KEY` fs_mtime` (`mtime`) USING BTREE;

error
SQL command:


ALTER TABLE `oc_share` ADD KEY` share_with_index` (`share_with`) USING BTREE
MySQL reports: Documentation

# 1061 - Duplicate key name exists: 'share_with_index'

What else can I do to solve my problem?

**Comment by kesselb** [comment]
> Duplicate key name exists: 'share_with_index'

The index with the name `share_with_index` is already present. Skip this one and execute the next alter table statment.

**Comment by MichaSei** [comment]
thanxs for tis fast support.
But in the backend of my NC15 i have follow message:#
In der Datenbank fehlen einige Indizes. Auf Grund der Tatsache, dass das Hinzufügen von Indizes in großen Tabellen einige Zeit in Anspruch nehmen kann, wurden diese nicht automatisch erzeugt. Durch das Ausführen von "occ db:add-missing-indices" können die fehlenden Indizes manuell hinzugefügt werden, während die Instanz weiter läuft. Nachdem die Indizes hinzugefügt wurden, sind Anfragen auf die Tabellen normalerweise schneller.

> Fehlender Index "parent_index" in der Tabelle "oc_share".
> Fehlender Index "owner_index" in der Tabelle "oc_share".
> Fehlender Index "initiator_index" in der Tabelle "oc_share".
> Fehlender Index "fs_mtime" in der Tabelle "oc_filecache".

How i solve this?

**Comment by kesselb** [comment]
> Please check here:
> #13578
> I summarized what helped for me.

@MichaSei

**Comment by skjnldsv** [comment]
What about the occ shell app for shared environment?
Does it work?

**Comment by Tom-2019** [comment]
It does work on our Strato hosted website. NC 16.0.1

**Comment by DiagonalArg** [comment]
I see `occ` is supposed to be use "as your HTTP user", and with the http server's version of PHP.  I'm using shared hosting but I do have shell access (webfaction - platform as a service) .  All files in my nextcloud install are owned by my shell user.  

1. Can I use occ?
2. How do I confirm which PHP version nextcloud is using, as the system has many.

Also, I have to second @FireEmerald 's [frustration](https://github.com/nextcloud/server/issues/11491#issuecomment-497043142).

**Comment by nickvergessen** [comment]
In your shell run:
```
php --version
```

if that works, try the following in your nextcloud directory:
```
php occ
```

**Comment by sushidave** [comment]
FYI: If using Plesk the scheduled task feature can be used to run occ commands:

1. Task type: Run a command
2. Command: php /path/to/nextcloud/directory/occ db:add-missing-indices
    (replace “/path/to/nextcloud/directory/” by the actual path)
4. Leave the other settings as they are.
5. Click “Run now”.

https://help.nextcloud.com/t/how-to-execute-an-occ-command-using-scheduled-tasks-on-plesk/134098/2

**Comment by Flix6x** [comment]
You can use FTP access to add your own php file that executes custom `occ` commands. I added `fix-config.php` to my nextcloud directory and browsed to `https://<my nextcloud url>/fix-config.php` to run its contents. I had accumulated 4 different warning over the years, each of which recommended running a separate `occ` command, so my contents are:

```
<?php 
   exec("/usr/bin/php74 -d memory_limit=1024M occ -n db:add-missing-indices > occ-fixed-config.txt 2>&1");
   exec("echo \"Congratulations: Indices fixed!\" >> occ-fixed-config.txt");
   exec("/usr/bin/php74 -d memory_limit=1024M occ -n db:add-missing-primary-keys > occ-fixed-config.txt 2>&1");
   exec("echo \"Congratulations: Primary keys fixed!\" >> occ-fixed-config.txt");
   exec("/usr/bin/php74 -d memory_limit=1024M occ -n db:add-missing-columns > occ-fixed-config.txt 2>&1");
   exec("echo \"Congratulations: Columns fixed!\" >> occ-fixed-config.txt");
   exec("/usr/bin/php74 -d memory_limit=1024M occ -n db:convert-filecache-bigint > occ-fixed-config.txt 2>&1");
   exec("echo \"Congratulations: Filecache fixed!\" >> occ-fixed-config.txt");
   header('Location: occ-fixed-config.txt');
?>
```

This creates the file `occ-fixed-config.txt` containing whatever `occ` returned, among some congratulations. You can also set up a webcron job to trigger this endpoint, if you can't set up cron jobs at your host. You may need to adjust the PHP version to the one that Nextcloud shows under Administration/System (index.php/settings/admin/serverinfo). If your database isn't big, this should complete within the lifespan of a http request.

Is there any reason why such a file shouldn't be part of nextcloud server, to support users that want to fix problems after upgrading, but cannot run `occ` in shared hosting?

**Comment by AyoungDukie** [comment]
It may be worth converting some of these entries to a wiki entry or documentation file, as most existing documentation points to the `occ` command/script.

In a shared-hosting situation, where only the phpMyAdmin access is viable, these queries would be useful.

For the 26.0.X -> 27.0.0 upgrade, I am encountering this issue now:
'''
Missing index "mounts_user_root_path_index" in table "oc_mounts".
```
And digging into the [script for occ db:addissing-indices](https://github.com/nextcloud/server/blob/master/core/Command/Db/AddMissingIndices.php), the new step for this adds index `mounts_user_root_path_index` with columns `user_id`, `root_id`, and `mount_point` to the index, however attempting define these runs into a length issue. I see that the php file seems to define lengths of `null`, `null`, and `128`, respectively, but I cannot seem to translate this to a query syntax well. Is there a different way should be applied? Based on my reading, it seems like the appropriate methods would have either been 
```
ALTER TABLE `oc_mounts` ADD KEY `mounts_user_root_path_index` (`user_id`, `root_id`, `mount_point`) USING BTREE;
```
Or (for the length issue):
```
ALTER TABLE `oc_mounts` ADD KEY `mounts_user_root_path_index` (`user_id`(NULL), `root_id`(NULL), `mount_point`(128)) USING BTREE;
```
However this is the limit of my knowledge here...
