### ISSUE TITLE
.user.ini not passed the integrity check

### ISSUE THREAD

**Issue by hunter-nl** [nextcloud/server#115]
When using nginx and change .user.ini file then the code integrity check complains about a different hash value.

So when you change the following values with different values to allow bigger files to be uploaded:
```
upload_max_filesize=513M
post_max_size=513M
```
Code integrity check complains.

I think .user.ini file should not be included in the code integrity check

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
That should actually work since a longer time. Can you post your whole `.user.ini` file? https://github.com/nextcloud/server/blob/ae8f750039a5a7493a1fa08e8d54773b93cdc48b/lib/private/integritycheck/checker.php#L178-L198 should catch such situations.

**Comment by hunter-nl** [comment]
```
upload_max_filesize=10G
post_max_size=10G
memory_limit=1024M
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0
```
I have also changed the memory_limit value.
The integrity checker produce this output:
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 0a557e3cdca4c2e3675deed761d79d109011dcdebbd9c7f6429f1d3476938ec95729543d7384651d1d0c48e26c5024cc5f517445920915a704ea748bdb903c5f
                            [current] => 7558302f8a5f2dccb117e5c6d9e2e4564553cad44b7edd4df7882fafe39a1f648a9dc806c4afc3cd831be42b177a531b45ddce8635757681d723dee1d37a236e
                        )

                )

        )

)
```

**Comment by LukasReschke** [comment]
That explains it. Adjusting the memory limit is not supported yet. Filed feature request https://github.com/nextcloud/server/issues/new

**Comment by nfguide** [comment]
Getting the same result after upgrade from 16.0.1 to 16.0.3.

Two different domains upgraded and same error;

Domain cld-sa
Contents of .user.ini
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'

Error:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => ad26affa3843f3b9d31e419bfdfa9ec0052e306451c69666ad31358ff5aebd868a3ec42ab90cd838292c100de579651f6d11198b60397e7feae1252c98e4366f
                        )

                )

        )

)

Domain pcg
Contents of .user.ini
mbstring.func_overload=0
always_populate_raw_post_data=-1
default_charset='UTF-8'
output_buffering=0
upload_max_filesize=1G
post_max_size=1G
memory_limit=512M

Error message:
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => 421779918fa61139a4d9393e62715840ec78bc7d37d7aeac81d6a38006204ad28cec0c06f63b8e770573fbd4684efa194dcabce4663c2e60a575e63ad89a3add
                        )

                )

        )

)

**Comment by kesselb** [comment]
@nfguide This issue was closed over 3 years ago. Replace your .user.ini with https://github.com/nextcloud/server/blob/stable16/.user.ini. For further questions visit https://help.nextcloud.com
