### ISSUE TITLE
Favicons for certain pages

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11504]
![Favicons in browser tabs](https://user-images.githubusercontent.com/925062/46282419-bdbc2300-c571-11e8-8b26-e89937b34254.png)

- Apps generally have their app icon as favicon – that’s good :+1: 
- Settings has the Nextcloud logo as favicon – that’s good :+1: 
- Files has the app icon too, file/folder – that’s ok, but since it’s the main part of Nextcloud it would be better if we show the Nextcloud logo too like for settings :question:  :cloud: 
- Share pages show the share icon, which is a bit strange. Normally you send these links to people who don’t even know Nextcloud – it should be the Nextcloud logo here too :cloud: 

What do you think @nextcloud/designers? @juliushaertl it seems to stem from autogenerating the favicon through the theming app, so do you know where to change this?

**Comment by juliushaertl** [comment]
@jancborchardt Having the default logo for sharing pages makes sense to me. For the files app I'd rather keep the auto generated, since although it is the core app of Nextcloud it still is an app where it makes sense to separate from others in the tab list.

**Comment by pixelipo** [comment]
I agree with @juliushaertl 

To add my 2 cents, I think at some point it should be possible to set the Default NC app in the Admin (or Personal?) settings to something other than the Files app, at which point it makes no sense whatsoever for the Files to have a default logo.

**Comment by jancborchardt** [comment]
@juliushaertl good point! Could you open a pull request to fix it for the sharing pages?

@pixelipo yup – the personal settings would be the right place for that. Although currently it’s an instance-wide config setting, so some work would need to be done. → Different issue in any case. :)
