### ISSUE TITLE
New user creation: All inputs are emptied when password is not strong enough

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11512]
When you create a new user in the user management but the password is not strong enough – and gives you this error:

> An error occured during the request. Unable to proceed.
> Password is among the 1,000,000 most common ones. Please make it unique.

Then all the fields you put in with the user details are also emptied. Actually, everything should stay like it is, even the password, with focus being in the field.

(Also, the first line of that error is not informative and very technical – it does not need to be shown.)

**Comment by MorrisJobke** [comment]
@nextcloud/javascript This is still an issue 😉

**Comment by MorrisJobke** [comment]
@skjnldsv @ChristophWurst This is a vue app - might be easier to fix than before, right?

**Comment by skjnldsv** [comment]
Fix https://github.com/nextcloud/server/pull/12587
