### ISSUE TITLE
nextcloud 14.01 link sharing:: password setting vs. Safari 12

### ISSUE THREAD

**Issue by skerbis** [nextcloud/server#11517]
### Steps to reproduce
1. Set a shared link
2. Try to set a password with Safari 12 (here on macOS 10.14) 

### Expected behaviour
It should be possible to disable the suggested password of safari

### Actual behaviour
Dropdown pops out, it is not possible to delete the suggested password or set a desired one. 

### Server configuration

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.2.1

**Nextcloud version:** (see Nextcloud admin page)
14.01

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
This Version inside nextcloud updater

**Comment by skjnldsv** [comment]
14 is EOL, and this have been fixed in newer versions
