### ISSUE TITLE
Files drop: Top right actions (download, connect) do not make sense?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11514]
For a files drop share link, we show the actions like for other share links: Download, Add to your Nextcloud etc.

But since it’s a receiving-only folder, those do not make any sense and we should not show them, right?

![](https://raw.githubusercontent.com/nextcloud/screenshots/master/files/Files%20Drop%20with%20share%20note.png)

cc @nextcloud/sharing

**Comment by weeman1337** [comment]
> But since it’s a receiving-only folder, those do not make any sense and we should not show them, right?

I think so. _Download_ and _Add to your Nextcloud_ are even not working..

**Comment by jancborchardt** [comment]
@weeman1337 feel free to look into it! :) Also, https://github.com/nextcloud/server/issues/11513 is pretty related.
