### ISSUE TITLE
Breadcrumb grouping does not seem to work?

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11520]
The breadcrumbs are supposed to be grouped into a 3-dot-menu when too long, especially on mobile. This doesn’t seem to work at the moment?

![screenshot from 2018-10-01 20-49-22](https://user-images.githubusercontent.com/925062/46309083-a6098c80-c5bb-11e8-819a-d2521c8990fb.png)
(Ellipsizing added by me in a separate pull request.)

Check it out @nextcloud/designers @skjnldsv – this would also have to be backported since it severely impacts navigation on mobile.

**Comment by skjnldsv** [comment]
Your ellipsis is incompatible with the automated calculation of the breadcrumbs 😉

**Comment by skjnldsv** [comment]
@jancborchardt Raah, I tested it like a week ago and it was still working!

**Comment by skjnldsv** [comment]
Well apparently this is broken on 14.0.1... Jesus!

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/11529

**Comment by danxuliu** [comment]
>  Well apparently this is broken on 14.0.1... Jesus!

Specifically, this was broken [when `overflow-x: hidden`was removed from `#app-content`](https://github.com/nextcloud/server/commit/a9e554beeccc479#diff-73946bf60d9717368158f91af1bd7c09L66).

> :grin: was probably me. Or you? Or Julius? We will never know. :wink:

I know :-P

> Fix in #11529

Unfortunately this fixes it in Chromium, but not in Firefox (not even in Firefox 64).

**Comment by MorrisJobke** [comment]
@skjnldsv I guess nothing for 16, right?

**Comment by skjnldsv** [comment]
Well, I cannot reproduce the issue anymore :(
![Peek 11-04-2019 14-00](https://user-images.githubusercontent.com/14975046/55955595-1f1c2780-5c62-11e9-9af3-b0b2aa220fce.gif)

**Comment by jancborchardt** [comment]
Then let’s close it until it comes up again. :)
