### ISSUE TITLE
User icon does not display in the web browser on Android

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/server#11532]
### Steps to reproduce
1. Log in to Nextcloud using the web browser on Android
2. Auto-generated user icon is not displayed (or is missing background)

### Expected behaviour
The auto-generated user icon should be the same as the web interface on other devices.

### Actual behaviour
Using Chrome on Android and logging-in to the web interface, the user icon is not displayed.

### Server configuration

**Operating system**:
Arch

**Web server:**
Apache 2.4.33

**Database:**
MariaDB 10.2.14

**PHP version:**
7.2.5

**Nextcloud version:** (see Nextcloud admin page)
14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older Nextcloud

**Where did you install Nextcloud from:**
Source, Nextcloud website

### Client configuration
**Browser:**
Chrome 69

**Operating system:**
Android 5.0.2

![screenshot_2018-10-02-15-04-08-460_com android chrome](https://user-images.githubusercontent.com/25575702/46334219-dc93e580-c655-11e8-95a7-3d1dd8eb9762.png)

In a web browser on a PC it's displayed as follows:

![screenshot_nextcloud-web_browser](https://user-images.githubusercontent.com/25575702/46334706-afe0cd80-c657-11e8-8257-4cb74d48faac.png)

**Comment by skjnldsv** [comment]
Hi! Before we continue, please do the following step:
1. [clear your browser's cache](https://www.refreshyourcache.com/)

Thanks :wink:

**Comment by terrytibbles** [comment]
I tried that and it has no effect.

**Comment by skjnldsv** [comment]
Thanks. Can you do a long press and open the image to a new tab? Or is it just text? 
Can you compare the image URL and see if they both matches?

**Comment by terrytibbles** [comment]
It looks like the image has been generated with the exact same background as the theme (it's not text). The image in the browser on the PC however looks like its been generated with the auto-generated background. Also, the URLs are not the same:

Phone URL:
https://<host>/index.php/avatar/<user>/128?v=0

PC URL:
https://<host>/index.php/avatar/<user>/32?v=0

**Comment by skjnldsv** [comment]
Does they look the same once opened in a new tab?

**Comment by terrytibbles** [comment]
No, they look like in the screenshots.

**Comment by terrytibbles** [comment]
What do you mean by colour change?

Does the Nextcloud behaviour not need to change?

**Comment by terrytibbles** [comment]
So new users won't be affected?

**Comment by skjnldsv** [comment]
@terrytibbles should not.
Did my fixes worked?
