### ISSUE TITLE
User group selection

### ISSUE THREAD

**Issue by XjeEDK** [nextcloud/server#11543]
### Steps to reproduce
1. Go to the user section
2. Select a user at the bottom of a screen and open the drop down list of the groups

### Expected behaviour
Dropdown list should open with a scroll bar. Like it happens when the user in on top of the screen

### Actual behaviour
Complete list of groups opens and I need to scroll the complete site to the top. Because there is not scrollbar inside the dropdown list.

### Server configuration

**Browser**:FireFox

**Operating system**:CentOS

**Web server:** NginX

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Comment by MorrisJobke** [comment]
cc @skjnldsv
