### ISSUE TITLE
"More apps" menu not working in current master

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11552]
Try clicking the "more apps" menu in the header on current master, it’s not working.

Could you check it out @juliushaertl? cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
Breaking commit: b9806f701228b1ec947e626acf51e6fc7654eab0

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/11553 ;)
