### ISSUE TITLE
Files not accessible after sharing LDAP user was deleted

### ISSUE THREAD

**Issue by gema2007** [nextcloud/server#11551]
### Steps to reproduce
user1 shares files with user2
user1 ist deleted from the LDAP server and appears in the remnants table (php occ ldap:show-remnants)
user2 can’t access all his files until user1 is deleted from nextcloud with “php occ user:delete user1”. The logfile says “OC\User\NoUserException: user1 is not a valid user anymore”.

### Expeted behaviour
user2 can normally access his files

### Actual behaviour
user2 can't access any files
The logfile says “OC\User\NoUserException: user1 is not a valid user anymore”

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 14.01

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
@gema2007 @Zappatron can you check again with 14.0.2 (right now the RC is available)? It has a fix that deals with failed storages.

**Comment by MorrisJobke** [comment]
Let's close it for now until we know that it is still not fixed in 14.0.2

**Comment by jmallach** [comment]
I am seeing this with 14.0.5.

**Comment by MorrisJobke** [comment]
There is no 14.0.5 🤔

**Comment by jmallach** [comment]
Heh, sorry, this is a slow morning here. :stuck_out_tongue: I meant 14.0.3.

**Comment by jmallach** [comment]
I have checked the users that were appearing in the log, and after making sure they were safe to remove, I user:delete'd them. The error log is clean now, but user2 still just gets a spinner and cannot access any of their files.

This might be an unrelated issue though as I have also checked that user1 in our case had never shared anything with user2.

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by jmallach** [comment]
A bit more info. User2 reports:
```
All files: spinner (and nothing else shows up)
Shares - Shared with others: I see files there
Shares - Shared with you: "Nothing shared with you yet" -- not true
Shares - Shared by link: I see 1 file, that's OK
Shares - Deleted shares: "Nothing shared with you yet" probably OK, not sure
```

**Comment by blizzz** [comment]
@jmallach do you have a log (maybe a backtrace)?

**Comment by jmallach** [comment]
No, but I can provide if you point me at docs on how ot get the info you need.

**Comment by sergiomb2** [comment]
In 15.0.7 it is present

**Comment by sergiomb2** [comment]
how I delete the share of non-existing user ?

**Comment by sergiomb2** [comment]
> how I delete the share of non-existing user ?

https://github.com/nextcloud/server/issues/4117#issuecomment-386205139

**Comment by blizzz** [comment]
also cf. https://docs.nextcloud.com/server/16/admin_manual/configuration_user/user_auth_ldap_cleanup.html

**Comment by bluikko** [comment]
Same thing in 16.0.5 and it is so annoying.

The link from @blizzz explains the process I've been using but in a busy environment this really needs to be automated and run often or users are complaining all the time that their Desktop sync does not work.

And of course the `occ` output for `ldap:show-remnants` is in a "fancy" table format. I can of course write a parser for it, but I should not have to. What should be a simple task (deleting a user) is made a huge mountain of work due to #15536, this #11551, and others. In addition to "--no-ansi" parameter there should be a "--brief" or similar option that skips the "fancy" table output and outputs something similar to CSV, hopefully without headers also.

**Comment by blizzz** [comment]
you can try out https://github.com/nextcloud/server/pull/17717, but if it goes in, it won't be backported

**Comment by skjnldsv** [comment]
I guess this is fixed with 17717.
If this is still happening after an upgrade to the latest version, feel free to reopen
