### ISSUE TITLE
Web updater fails when updating from NC13 → 14 if EPUB reader is installed

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#11572]
Details:
https://github.com/nextcloud/updater/issues/187

**Comment by MorrisJobke** [comment]
@nickvergessen: shouldn’t it properly disable the app if it fails to load it?

**Comment by Sanookmakmak** [comment]
Could be that more apps causing the server error while updating from NC13 to 14, here is a bug list of "Not compliant apps":
https://help.nextcloud.com/t/nc-14-0-1-bug-list-deprecated-file-found-app-is-not-compliant/38213

**Comment by nickvergessen** [comment]
Well, I dont understand the issue too good.
Does the updater fail? Or is there just an error afterwards, or …?

**Comment by Sanookmakmak** [comment]
The updater dies with server error when the EPUB reader is installed. Had to disable it manually by executing occ app:disable to continue the web updater.

**Comment by nickvergessen** [comment]
"dies" is not very specific. Any error message?

**Comment by Sanookmakmak** [comment]
>Any error message?

"Internal Server Error"

**Comment by MorrisJobke** [comment]
> > 
> 
> "Internal Server Error"

Could you check the nextcloud.log inside your data directory for more information?

**Comment by Sanookmakmak** [comment]
nextcloud.log is empty unfortunately

Screenshot of web updater:
![nextcloud-server-error-503](https://user-images.githubusercontent.com/24833757/47309203-1db75e00-d634-11e8-9d61-2813281b2642.png)

Could only countinue the web updater by disabling the files_reader app manually.

**Comment by MorrisJobke** [comment]
> nextcloud.log is empty unfortunately

There needs to be something in there - it says "internal server error" which means also that there is something logged while printing this page.

Also as this is long ago: not likely that you still have this problem as you said disabling the 3rdparty app solved it. Thus I will close this for now. if there is more detail on this we can reopen and look into it again.

**Comment by Sanookmakmak** [comment]
Here is one more case with third party apps which were not checked BEFORE updating.

https://help.nextcloud.com/t/internal-server-error-after-16-0-1-update/53552
