### ISSUE TITLE
Frontend validation for Add User form

### ISSUE THREAD

**Issue by pixelipo** [nextcloud/server#11584]
New User form badly needs some frontend validation to match the PHP stuff. While pull request #11581 I had to type in the entire form several times because it would empty it up after failing to comply with password requirements:

1. "password too short" - that error has frontend validation, but it's only displayed as a popover on hover, so it's hard to discover
2. "password too common" - resets the form:
![image](https://user-images.githubusercontent.com/4129927/46406030-7917bf80-c70a-11e8-9b96-48139c0f24c2.png)
3. "user already exists" - same as :arrow_up: 
needs uppercase, lowercase, the list goes on.

What should happen:
1. errors should show where they occur
2. location of the error should be highlighted
3. form should not be cleared
![image](https://user-images.githubusercontent.com/4129927/46406448-de1fe500-c70b-11e8-8418-edba21e89f0e.png)

@nextcloud/designers sorry for my bad "screenshot", but what do you think? Should notifications stay on top (with an "x") to keep the consistency with the rest of the NC?

**Comment by MorrisJobke** [comment]
> New User form badly needs some frontend validation to match the PHP stuff.

And also inline the errors from the backend, because the notification at the top is something we should not use anymore designwise.

**Comment by jancborchardt** [comment]
The errors like "Password too short" should be shown using the `tooltip()` function so the interface is not moved around and it calls enough attention to itself.

(Also, we never ever use italic text in an interface. :)

**Comment by pixelipo** [comment]
That sounds good @jancborchardt - important thing is that these are actually visible for `n` seconds

**Comment by jancborchardt** [comment]
Or until the next interaction? (Or until it’s long enough?) Purely time-based messages are always a pain when you don’t look, or they are gone too quick – which is why we are trying to phase out the top `showNotification()`.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since over 2 years. Please reopen if you still want to implement this.

**Comment by szaimen** [comment]
This will be much improved with https://github.com/nextcloud/server/pull/23529 
So please create a new issue if there should be something to improve. Thanks!
