### ISSUE TITLE
Custom theme template file doesn't override the existing standard file

### ISSUE THREAD

**Issue by maccarib** [nextcloud/server#11585]
### Steps to reproduce
1. Place a custom template file in the path `/themes/<mytheme>/apps/<myapp>/templates`
2. Example: copy the standard calendar colorpick from `apps/calendar/templates/colorpicker.html` to   `/themes/<mytheme>/apps/tasks/templates/colorpicker.html`
3. Reload the tasks app page. No changes will be seen.
4. When I delete the standard tasks colorpicker, no colorpicker wil be shown at all, meaning that definitely the one in the templates folder is being ignored. On the other hand, when I copy the calendar-colorpicker.html to the standard folder apps/tasks/templates/colorpicker.html changes can be seen

### Expected behaviour
Following https://docs.nextcloud.com/server/14/developer_manual/core/theming.html it should be possible to override template files. This doesn't seem to be the case.

### Actual behaviour
Nothing. See steps to reproduce

### Server configuration

**Operating system**: Debian 3.16.56-1

**Web server:** Apache 2.0 

**Database:** MySQL

**PHP version:** 7.2.8

**Nextcloud version:** 13.0.6/14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
files
activities
galery
contacts
calendar
rainloop
tasks

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'datadirectory' => '/home/www/<mypath>/data',
  'dbtype' => 'mysql',
  'version' => '13.0.6.1',
  'dbname' => '',
  'dbhost' => 'localhost:3306',
  'dbtableprefix' => 'nc_',
  'dbuser' => '',
  'dbpassword' => '!',
  'filesystem_check_changes' => 1,
  'installed' => true,
  'logfile' => '/data/nextcloud.log',
  'loglevel' => '1',
  'log_query' => false,
  'maintenance' => false,
  'theme' => '<mytheme>',
  'trusted_domains' => 
  array (

  ),
  'mail_from_address' => '',
  'mail_smtpmode' => 'php',
  'mail_domain' => '.net',
  'secret' => '',
  'appstoreenabled' => true,
  'appstoreurl' => 'http://api.apps.owncloud.com/v1',
  'overwrite.cli.url' => '',
);
</details>

### Client configuration
**Browser:** 
Firefox, Opera, Chrome

**Comment by violoncelloch** [comment]
you need to specify your template in your `config.php`

**Comment by maccarib** [comment]
That's clear. My template is defined and my css-adjustments work. It's just that this (first) custom html-template file is being ignored

**Comment by violoncelloch** [comment]
I am reading this line in your config above:
> 'theme' => '',
So you didn't specifie it as explained in the  documentation you qoted

**Comment by maccarib** [comment]
You read that because I've replaced that theme name in a placeholder-like manner, that is '&lt; mytheme &gt;' (I've entered the symbols in html entity codes to be clear.

**Comment by violoncelloch** [comment]
Ahh, I'm sorry about that

**Comment by maccarib** [comment]
Nevermind! It still might be that I've just done or missed something stupid ;-)

**Comment by violoncelloch** [comment]
have you tried running `sudo -u www-data php occ maintenance:theme:update`? maybe this helps...

**Comment by maccarib** [comment]
No, I haven't tried before, but now. There's no change in behavior. NC only reacts on changes in den app's standard folders.

**Comment by juliushaertl** [comment]
The colorpicker template by the tasks app is not using the Nextcloud template loading but loaded in the angular app itself, therefore it doesn't respect your new template file in the theme folder. This is something the tasks app would need to add support for, so I'd suggest you open an issue in the tasks repository.
