### ISSUE TITLE
Stuck at "a few seconds".

### ISSUE THREAD

**Issue by vishwasnavadak** [nextcloud/server#11598]
### Steps to reproduce
1. Login to Nextcloud
2. Click on **+** and click **Upload File**
3. select any file

### Expected behaviour
It should upload the selected file

### Actual behaviour
The progress bar is stuck at 'a few seconds' forever
![screenshot 2018-10-03 at 9 01 43 pm](https://user-images.githubusercontent.com/13111030/46421844-b2731e00-c750-11e8-99cb-16c1b8978071.png)

### Server configuration

**Operating system**: linux

**Web server:** Apache	2.4.33

**Database:**  MySQL 5.5.61-38.13-log

**PHP version:** 5.6

**Nextcloud version:** (see Nextcloud admin page) 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install 

**Where did you install Nextcloud from:** Softaculous

**Signing status:** 
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chrome, Firefox

**Operating system:** Mac OS 10.14 Mojave

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

> PUT http://internal.webception.in/cloud/index.php/apps/files/ 403 (Forbidden)
send @ core.js?v=9c81b5db-0:4
ajax @ core.js?v=9c81b5db-0:4
send @ merged-index.js?v=9c81b5db-0:2747
(anonymous) @ core.js?v=9c81b5db-0:2
j @ core.js?v=9c81b5db-0:2
add @ core.js?v=9c81b5db-0:2
(anonymous) @ core.js?v=9c81b5db-0:2
each @ core.js?v=9c81b5db-0:2
(anonymous) @ core.js?v=9c81b5db-0:2
a.Deferred @ core.js?v=9c81b5db-0:7
then @ core.js?v=9c81b5db-0:2
_onSend @ merged-index.js?v=9c81b5db-0:2791
(anonymous) @ core.js?v=9c81b5db-0:13
data.submit @ merged-index.js?v=9c81b5db-0:2515
(anonymous) @ merged-index.js?v=9c81b5db-0:591
(anonymous) @ core.js?v=9c81b5db-0:2
j @ core.js?v=9c81b5db-0:2
add @ core.js?v=9c81b5db-0:2
(anonymous) @ core.js?v=9c81b5db-0:2
each @ core.js?v=9c81b5db-0:2
(anonymous) @ core.js?v=9c81b5db-0:2
a.Deferred @ core.js?v=9c81b5db-0:7
then @ core.js?v=9c81b5db-0:2
submit @ merged-index.js?v=9c81b5db-0:590
(anonymous) @ merged-index.js?v=9c81b5db-0:880
_.each._.forEach @ core.js?v=9c81b5db-0:166
submitUploads @ merged-index.js?v=9c81b5db-0:878
onNoConflicts @ merged-index.js?v=9c81b5db-0:1277
checkExistingFiles @ merged-index.js?v=9c81b5db-0:1081
add @ merged-index.js?v=9c81b5db-0:1295
_trigger @ core.js?v=9c81b5db-0:13
(anonymous) @ merged-index.js?v=9c81b5db-0:2878
each @ core.js?v=9c81b5db-0:2
_onAdd @ merged-index.js?v=9c81b5db-0:2871
(anonymous) @ core.js?v=9c81b5db-0:13
(anonymous) @ merged-index.js?v=9c81b5db-0:3076
j @ core.js?v=9c81b5db-0:2
add @ core.js?v=9c81b5db-0:2
always @ core.js?v=9c81b5db-0:2
_onChange @ merged-index.js?v=9c81b5db-0:3066
(anonymous) @ core.js?v=9c81b5db-0:13
u @ core.js?v=9c81b5db-0:13
dispatch @ core.js?v=9c81b5db-0:3
r.handle @ core.js?v=9c81b5db-0:3

> merged-index.js?v=9c81b5db-0:664 Uncaught TypeError: Cannot read property 'documentElement' of undefined
>     at OC.FileUpload.getResponse (merged-index.js?v=9c81b5db-0:664)
>     at HTMLInputElement.fail (merged-index.js?v=9c81b5db-0:1337)
>     at e.(/cloud/index.php/apps/files/anonymous function).(anonymous function)._trigger (http://internal.webception.in/cloud/core/vendor/core.js?v=9c81b5db-0:13:10075)
>     at e.(/cloud/index.php/apps/files/anonymous function).(anonymous function)._onFail (http://internal.webception.in/cloud/index.php/js/files/merged-index.js?v=9c81b5db-0:2717:18)
>     at e.(/cloud/index.php/apps/files/anonymous function).(anonymous function)._onFail (http://internal.webception.in/cloud/core/vendor/core.js?v=9c81b5db-0:13:5077)
>     at Object.<anonymous> (merged-index.js?v=9c81b5db-0:2751)
>     at j (core.js?v=9c81b5db-0:2)
>     at Object.fireWith [as rejectWith] (core.js?v=9c81b5db-0:2)
>     at x (core.js?v=9c81b5db-0:4)
>     at XMLHttpRequest.<anonymous> (core.js?v=9c81b5db-0:4)

</details>

**Comment by axelsimon** [comment]
Just solved this problem by updating my nginx configuration.
Indeed, it's good to remember that while Nexctloud will update itself, it won't update the nginx configuration and this configuration has seen quite a bit of change over the past versions of Nextcloud.
The current one is visible on the [Nextcloud Docs](https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html), i'd recommend putting in a new file on your server and using `vimdiff` to see just how much has changed. Then ideally, recreate your nginx config by moving your specific configuration items to the new version of the config.

Hope this helps.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
