### ISSUE TITLE
Mail App doest not synchronize email

### ISSUE THREAD

**Issue by reynum2** [nextcloud/server#11593]
### Steps to reproduce
1. having a free.fr mail box
2. install Mail App
3. Try to synchronize your mail box
   SMTP port 587
   IMAP port 993

### Expected behaviour
My Email in inbox must be visible

### Actual behaviour
Nothing is showed
But we can see if new messages are present.

### Server configuration
Docker instance on Linux Debian 9
Apache 2.4.25
MariaDB 10.1.26
PHP 7.0.30
Nextcloud 14.0.1 Updated from an older Nextcloud 14.0.0

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

Insert your config.php content here. 
```
$CONFIG = array (
  'instanceid' => '****',
  'passwordsalt' => '*****',
  'secret' => '******',
  'trusted_domains' =>
  array (
    0 => '127.0.0.1:5555',
    1 => 'nextcloud.reynum.eu',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '14.0.1.1',
  'overwrite.cli.url' => 'http://127.0.0.1:5555',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'reynum',
  'dbpassword' => '******',
  'installed' => true,
  'updater.secret' => '******',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);
```
**Are you using encryption:** no

### Client configuration
Firefox 52.8.1 esr

**Operating system:**
No anormal logs in apache or linux

#### Nextcloud log (data/nextcloud.log)
```
{"reqId":"TFJcClVAywoLka5f0ASe","level":3,"time":"2018-10-03T14:01:03+00:00","remoteAddr":"212.129.63.134","user":"reynum","app":"PHP","method":"GET","url":"\/index.php\/apps\/mail\/api\/accounts\/1\/folders\/SU5CT1g%3D\/messages?filter=","message":"Undefined index: count at \/var\/www\/nextcloud\/apps\/mail\/vendor\/pear-pear.horde.org\/Horde_Imap_Client\/Horde\/Imap\/Client\/Socket.php#2551","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:52.0) Gecko\/20100101 Firefox\/52.0","version":"14.0.1.1"}
```

![mail_nextcloud](https://user-images.githubusercontent.com/11191723/46411784-f3513f80-c71c-11e8-8767-607a33887ec8.png)

**Comment by rullzer** [comment]
Please submit this to the repository of the mail app http://github.com/nextcloud/mail
