### ISSUE TITLE
Contact photo from IOS 7 displayed in landscape mode on server web interface

### ISSUE THREAD

**Issue by freechelmi** [nextcloud/server#11605]
Steps to reproduce
create a contact with photo ( from camera) in IOS 7.1.2
Check the contact on nextcloud 14 web interface
Expected behaviour
the photo should be displayed in portrait mode.

Actual behaviour
the photo should is displayed in landscape mode ( needs a 90 degre rotation )

Server configuration detail
Operating system: Linux 4.2.0-38-generic #45~14.04.1-Ubuntu SMP Thu Jun 9 09:27:51 UTC 2016 x86_64

Webserver: nginx/1.15.4 (fpm-fcgi)

Database: mysql 10.3.9

PHP version:

7.2.10 Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

Nextcloud version: 14.0.1 - 14.0.1.1

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

Signing status
List of activated apps
Configuration (config/config.php)
Are you using external storage, if yes which one: local/smb/sftp/...

Are you using encryption:

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...

Client configuration
Browser: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/69.0.3497.81 Chrome/69.0.3497.81 Safari/537.36

Operating system: IOS 7.1.2

![capture du 2018-10-03 22-17-27](https://user-images.githubusercontent.com/446021/46436819-282fb780-c75a-11e8-9494-cc5206dcc126.png)

**Comment by MorrisJobke** [comment]
This is an issue within the contacts app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/contacts
