### ISSUE TITLE
Share Permissions - Can Change allows user to Unshare the folder???

### ISSUE THREAD

**Issue by nexus186** [nextcloud/server#11612]
Without the "Can Change" share permission, users cannot rename files of shared folders. However, if you give this permission, users can unshare the folder that is shared with them!

How do I prevent this? If "Can Change" permission allows unsharing of folder....then it needs to be more granular and have 2 options - Can Change, Can Unshare.

**Comment by rullzer** [comment]
Users are in control of their own data thus they can always unshare folders shared with them.

You might want to consider group folders if you want persistent folders shared between people.
