### ISSUE TITLE
Admin can not create user groups anymore

### ISSUE THREAD

**Issue by olegbolden** [nextcloud/server#11614]
I just updated to 14.0.1 version from 14.0.0 and eventually found that creation of groups is not available anymore. I can see user groups created before update, but no possibility to create more.
Meanwhile I use this console command to add new group instead:
`occ group:add "Newgroup"`

**Comment by ChristophWurst** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
@olegbolden You can create groups in the dropdown of the groups select on a user. Type an unknown group and press enter.
Nonetheless we added back the entry on the navigation for 14.0.2 see #11193
