### ISSUE TITLE
how to add a custom authentication

### ISSUE THREAD

**Issue by evaldobarbosa** [nextcloud/server#11625]
Nextcloud has an interface to create custom authentication?

I saw nextcloud has oauth1, oauth2, openid... but I saw I need to rewrite an AuthManager (or anything like this) to create a constant there.

I want to create it without rewrite any class. How I do this?

**Comment by ChristophWurst** [comment]
What are you trying to achieve?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
