### ISSUE TITLE
occ config:system:set fails if it is expecting a string but finds a string indexed array

### ISSUE THREAD

**Issue by TimMagee** [nextcloud/server#11628]
### Steps to reproduce
1. Rewrite a system config option that should be a string (such as 'overwritehosts') to a string indexed array. The following code will work well for this purpose:
`sudo -u www-data php occ config:system:set overwritehost www.example.com`
2. Attempt to fix your problem by changing setting overwritehost correctly.
`sudo -u www-data php occ config:system:set overwritehost --value=www.example.com`
3. Watch as an exception gets thrown.

##Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

### Expected behaviour
The server overwrites your string indexed array with the string that you attempted to use.

### Actual behaviour
An exception is thrown.
> An unhandled exception has been thrown:
TypeError: Return value of OC\AppFramework\Http\Request::getServerHost() must be of the type string, array returned in /var/www/html/nextcloud/lib/private/AppFramework/Http/Request.php:850
Stack trace:
#0 /var/www/html/nextcloud/lib/private/URLGenerator.php(253): OC\AppFramework\Http\Request->getServerHost()
#1 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(114): OC\URLGenerator->getBaseUrl()
#2 /var/www/html/nextcloud/lib/private/Server.php(969): OC\Template\SCSSCacher->__construct(Object(OC\Log), Object(OC\Files\AppData\Factory), Object(OC\URLGenerator), Object(OC\AllConfig), Object(OCA\Theming\ThemingDefaults), '/var/www/html/n...', Object(OC\Memcache\Factory), Object(OC\Template\IconsCacher), Object(OC\AppFramework\Utility\TimeFactory))
#3 /var/www/html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#4 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php(123): Pimple\Container->offsetGet('OC\\Template\\SCS...')
#5 /var/www/html/nextcloud/lib/private/ServerContainer.php(132): OC\AppFramework\Utility\SimpleContainer->query('OC\\Template\\SCS...')
#6 /var/www/html/nextcloud/lib/private/Repair.php(138): OC\ServerContainer->query('OC\\Template\\SCS...')
#7 /var/www/html/nextcloud/core/register_command.php(143): OC\Repair::getRepairSteps()
#8 /var/www/html/nextcloud/lib/private/Console/Application.php(118): require_once('/var/www/html/n...')
#9 /var/www/html/nextcloud/console.php(95): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')
#11 {main}

### Server configuration

**Operating system**: Raspbian GNU/Linux 9 (stretch)

**Web server:** Apache/2.4.25 (Raspbian)

**Database:** mariadb  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

**PHP version:** PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** 14.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 13.x

**Where did you install Nextcloud from:** The zipfile download on the website

**Signing status:**
<details>
<summary>Signing status</summary>
I currently don't have access to my NextCloud server like this. If this is especially important, I can add this later.
</details>

**List of activated apps:**
<details>
<summary>List of Active Apps</summary>
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - twofactor_u2f: 1.6.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
``
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "www.example.com"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/www.example.com\/nextcloud",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": "['HTTP_X_FORWARDED_FOR']",
        "overwritehost": "www.example.com",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/nextcloud",
        "overwritecondaddr": "^10\\.0\\.0\\.1$",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
p`
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
I am using an external hard drive on my raspberry pi.
**Are you using encryption:** yes/no
I am not using server side at rest encryption
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Not that I know of.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by TimMagee** [comment]
The next time I am configuring my personal nextcloud instance, I'll try to take a look at this.

**Comment by szaimen** [comment]
Thanks!
