### ISSUE TITLE
.well-known/CloudIdVerificationCode.txt not registered with IANA

### ISSUE THREAD

**Issue by virtualdxs** [nextcloud/server#11623]
According to RFC 5785:
 > Applications that wish to mint new well-known URIs MUST register them, following the procedures in Section 5.1.

Verification (https://github.com/nextcloud/server/pull/3869) uses .well-known/CloudIdVerificationCode.txt. which (according to https://www.iana.org/assignments/well-known-uris/well-known-uris.xml) is not registered.

**Comment by My1** [comment]
lol what is that thing even for?

**Comment by danielkesselberg** [comment]
> lol what is that thing even for?

https://github.com/nextcloud/server/commit/cbf5acca45388a44e22410abcd25a19d86fa68ee I suppose this is some kind of "this is really my website" check? :confused:

**Comment by szaimen** [comment]
I think the check if the website is valid was removed so I think that this is not needed anymore. Please reopen if you can still reproduce this. Thanks!
