### ISSUE TITLE
"Disabled users" group is missing

### ISSUE THREAD

**Issue by DmDS** [nextcloud/server#11629]
### Steps to reproduce
1. Log in as Admin (Full Admin not Group Admin)
2. Go to Users and Disable an existing User

### Expected behaviour
On the left pane the Group "Disabled" is visible

### Actual behaviour
On the left pane the Group "Disabled" is missing

**Nextcloud version:*14.0.0.1* 

**Updated from an older Nextcloud/ownCloud or fresh install: upgraded**

**Comment by MorrisJobke** [comment]
I can reproduce this. Browsing `/settings/users/disabled` directly is still working, but it is not shown in the left menu.

Seems to be a regression from the UI rework for 14. cc @skjnldsv
