### ISSUE TITLE
Move/copy target selection, filter as you type and keyboard events

### ISSUE THREAD

**Issue by mrizvic** [nextcloud/server#11621]
In a rather large directory its difficult to find target directory by scrolling up/down. It would be very useful if one could filter out targets by typing like on the on the following link:
https://www.w3schools.com/jquery/jquery_filters.asp

It would also be very helpful if cursor keys would work on displayed items and enter key would open the selected directory.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
