### ISSUE TITLE
having issues with Mail app (Mail, rainloop)

### ISSUE THREAD

**Issue by bibull** [nextcloud/server#11639]
### Steps to reproduce
1. Install a mail app, i.e. Mail or Rainloop
2. Try to activate my mail server (gmail or anyone else) using SSL/TLS protocol
3. Receive error message : 

### Expected behaviour
I should have my mail server in the app (laposte.net or gmail etc)

### Actual behaviour
When activating my mail server laposte.net, it's working, but when i try to activate Gmail or Maxxicloud server, i have error message.

### Server configuration

**Operating system**: Debian GNU/Linux 9

**Web server:** Apache/2.4.25 (Debian)

**Database:** mysql  Ver 15.1 Distrib 10.1.26-MariaDB

**PHP version:** PHP 7.0.30-0+deb9u1 (cli)

**Nextcloud version:** 14

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - audioplayer: 2.4.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - encryption: 2.2.0
  - end_to_end_encryption: 1.0.5
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_downloadactivity: 1.3.0
  - files_fulltextsearch: 1.0.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - fulltextsearch: 1.0.0
  - fulltextsearch_elasticsearch: 1.0.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - ownbackup: 18.8.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - rainloop: 6.0.0
  - ransomware_detection: 0.4.0
  - ransomware_protection: 1.2.0
  - registration: 0.4.3
  - richdocuments: 2.0.13
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - sociallogin: 1.11.1
  - socialsharing_email: 1.0.4
  - socialsharing_facebook: 1.0.3
  - socialsharing_googleplus: 1.0.3
  - spreed: 4.0.0
  - systemtags: 1.4.0
  - terms_of_service: 1.0.1
  - theming: 1.5.0
  - theming_customcss: 1.1.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_saml: 1.6.2
  - workflowengine: 1.4.0
Disabled:
  - federation
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - support
  - survey_client
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "127.0.0.1",
            "2": "my.maxxicloud.fr",
            "3": "office.maxxicloud.fr"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/my.maxxicloud.fr",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "remember_login_cookie_lifetime": 1296000,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "trashbin_retention_obligation": "auto",
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "syslog_tag": "Nextcloud",
        "log_rotate_size": 104857600,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "has_internet_connection": true

</details>

**Are you using encryption:** yes

### Client configuration
**Browser:** Try with Chrome and Edge

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_imap.dll' - /usr/lib/php/20151012/php_imap.dll: cannot open shared object file: No such file or directory in Un$
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_openssl.dll' - /usr/lib/php/20151012/php_openssl.dll: cannot open shared object file: No such file or directory$
[Fri Oct 05 06:25:29.640015 2018] [mpm_prefork:notice] [pid 30452] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Fri Oct 05 06:25:29.640039 2018] [core:notice] [pid 30452] AH00094: Command line: '/usr/sbin/apache2'
[Fri Oct 05 12:12:17.679390 2018] [authz_core:error] [pid 32177] [client 213.44.134.225:57523] AH01630: client denied by server configuration: /var/www/html/data/.ocdata
[Fri Oct 05 12:12:34.286428 2018] [authz_core:error] [pid 28530] [client 213.44.134.225:57532] AH01630: client denied by server configuration: /var/www/html/data/.ocdata
[Fri Oct 05 13:07:13.262869 2018] [authz_core:error] [pid 32312] [client 213.44.134.225:58338] AH01630: client denied by server configuration: /var/www/html/data/.ocdata

</details>

It seems clear that the problem is around php openssl and imap but : 

php7.0-imap is already the newest version (7.0.30-0+deb9u1).
openssl is already the newest version (1.1.0f-3+deb9u2).

![sans titre](https://user-images.githubusercontent.com/43093137/46534962-34c32580-c8aa-11e8-90d4-d879f1897908.png)
![capture](https://user-images.githubusercontent.com/43093137/46535231-00039e00-c8ab-11e8-89ee-cfc6d14bf541.PNG)

**Comment by bibull** [comment]
Ok, i find the problem.

If i replace imap/smtp.gmail.com by the ip adress 108.177.119.108 it's work fine. 

Is it normal ? it's a dns problem...

**Comment by violoncelloch** [comment]
so this is a problem of your DNS resolver and not with nextcloud...
