### ISSUE TITLE
Rename 'enable'-checkbox for linksharing in filesapp-details

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#11634]
Currently if you want to activate a link, you need to tick a checkbox. I think 'enable' is not quiet a good description for sharing a link.

![screenshot from 2018-10-05 11-33-38](https://user-images.githubusercontent.com/25279821/46527911-b60ebe00-c892-11e8-81c6-cf68f0c6f13b.png)

Maybe 'share'/'unshare' would be a better description?

**Comment by newhinton** [comment]
@nextcloud/designers

**Comment by enoch85** [comment]
This is not a Github issue, rather a translation issue. 

Translations are done on [Transifex](https://www.transifex.com/nextcloud/nextcloud/), please join and find the string and Translate it correctly.

Regarding the English wording, I'm nt sure what it says now.

@MariusBluem Do you know?

**Comment by newhinton** [comment]
Also a button instead of a checkbox could improve the share-ability. As of now, it may not be obvious for every user how to share a link with somebody outside of the nextcloud-instance

**Comment by MariusBluem** [comment]
@jancborchardt what do you think?

**Comment by juliushaertl** [comment]
> Also a button instead of a checkbox could improve the share-ability. As of now, it may not be obvious for every user how to share a link with somebody outside of the nextcloud-instance

Why don't we get rid of the checkbox and just make the whole "Share link" entry clickable to enable link sharing. For disabling the link share we could simply add an entry to the popover menu.

**Comment by MorrisJobke** [comment]
AFAIK @jancborchardt or @skjnldsv already worked on a renaming, but I couldn't find the PR that changes this. There is a screenshot in https://github.com/nextcloud/server/pull/11537#issuecomment-426203262

**Comment by jancborchardt** [comment]
We are working on it at https://github.com/nextcloud/server/pull/11537 

The "Enable" part will be removed completely. We will move the checkbox towards the "Share link" part. And "Copy link" will be visible directly, outside of the menu. Also, when you check the "Share link", the link will be copied directly and feedback given in the form of a popover.

@newhinton if you want to check out https://github.com/nextcloud/server/pull/11537 and help you are very welcome! :) @skjnldsv and me are still focused on grid view at the moment.
