### ISSUE TITLE
No upload to shared folder possible after update to 14.0.1 (S3 primary storage)

### ISSUE THREAD

**Issue by bzdega** [nextcloud/server#11637]
Hi,

after updating 3 of my Nextcloud instances to NC 14.0.1, i now have a very bad issue with shared folders.

When uploading or creating files to a shared folder a message occures:

    Could not write file contents

and the upload breaks off.

Here is the output of my Nextcloud.log:

    Fatal webdav Sabre\DAV\Exception: Could not write file contents

/var/www/virtual/bz5/html/apps/dav/lib/Connector/Sabre/Directory.php - line 156:

OCA\DAV\Connector\Sabre\File->put(null)

/var/www/virtual/bz5/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:

OCA\DAV\Connector\Sabre\Directory->createFile("test2.txt", null)

/var/www/virtual/bz5/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 529:

Sabre\DAV\Server->createFile("files/marku ... t", null, null)

Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/virtual/bz5/html/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

/var/www/virtual/bz5/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:

Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])

/var/www/virtual/bz5/html/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/virtual/bz5/html/apps/dav/lib/Server.php - line 293:

Sabre\DAV\Server->exec()

/var/www/virtual/bz5/html/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/virtual/bz5/html/remote.php - line 163:

require_once("/var/www/vi ... p")

This is really bad, because the shared folders are useless now.

Any chance to get this fixed soon?

best regards,

Michael

**Comment by MorrisJobke** [comment]
> after updating 3 of my Nextcloud instances to NC 14.0.1, i now have a very bad issue with shared folders.

I could not reproduce this issue. :/ In https://help.nextcloud.com/t/help-testing-rc1-version-of-14-0-2-13-0-7-and-12-0-12/38359/26?u=morrisjobke it is reported to also don't work in 14.0.2 RC2.

I just tested this again in two different setups and both work fine with old as well as new shares as owner and recipient.

**Comment by MorrisJobke** [comment]
> Could not write file contents

Are the permissions on the filesystem are correct? Is the filesystem also not filled up completely? Maybe some quota is set for the webserver user? Could you try to copy the file to the filesystem as web server user to check that the filesystem works correct?

**Comment by bzdega** [comment]
Hi Morris,

is use only S3-Objectstorage (as primary storage). So there is no chance to set any permission on the S3-Buckets. It worked perfect since the upgrade zo 14.0.1. The permissions are completly handeled by the NC instance.

**Comment by bzdega** [comment]
what about the errors in the nextcloud.log?

> Fatal webdav Sabre\DAV\Exception: Could not write file contents

**Comment by bzdega** [comment]
the upload to all other folders is working well, only when you try to upload/create a file or folder to a folder which is shared by another user, these error occures.

**Comment by MorrisJobke** [comment]
@rullzer @icewind1991 This looks weird 🐟

**Comment by rullzer** [comment]
I can reproduce this.
I'll dive into it.

**Comment by bzdega** [comment]
thank you!!!

**Comment by rullzer** [comment]
Fix should be in https://github.com/nextcloud/server/pull/11764 could you check that?

**Comment by bzdega** [comment]
ahh... what can i do to check this?

**Comment by rullzer** [comment]
@bzdega as you use S3 and seem to administer a few Nextcloud instances I can only imagine they are not your average small home setups. You might want to checkout a [support subscription](https://nextcloud.com/pricing/). That way you are ensured of quick access to our engineers.
