### ISSUE TITLE
Incorrect behavior of "{space} used" tab

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#11635]
14.0.2 RC 1

### Steps to reproduce
1. Go to "Delete files" tab
2. Go to "{space} used" tab

### Expected behaviour
Something

### Actual behaviour
Nothing

### Screenshots:
![image](https://user-images.githubusercontent.com/9205230/46529055-135c3c80-c89e-11e8-94c9-eacedacc1a31.png)

**Comment by R0maNNN** [comment]
reproduced on 15.0.0

**Comment by R0maNNN** [comment]
reproduced on 15.0.5

**Comment by R0maNNN** [comment]
reproduced on 16.0.0

**Comment by kesselb** [comment]
I guess there is no action behind this. What do you suggest?

cc @jancborchardt

**Comment by R0maNNN** [comment]
@kesselb If you're correct, the control must be fully static and have no reaction when hovered or focused.

**Comment by jancborchardt** [comment]
It’s a brandable thing where providers or other instances can link it to a page for e.g. buying more storage.

You’re right – when no link is set, it should not be focusable/hoverable. cc @skjnldsv
