### ISSUE TITLE
Happens on every Update, so does on update from 13.0.6 to 14.0.1

### ISSUE THREAD

**Issue by cpu2910** [nextcloud/server#11648]
Update failed with message:
notifications: Failed to enable app notifications

notifications app wasn't enabled before the update.

I reported this issue many time before, but nothing happened.

And I bet that the error happened on the next update again...

**Comment by violoncelloch** [comment]
without filling in the issue template, we can't even try to reproduce your issue
please give some detailed information

**Comment by cpu2910** [comment]
Sorry, here's some more info:

It's the same error as #6140 and #10453, both reported by me and describing the same behaviour.

Server configuration
debian 9.5 stretch

Apache 2.4.25

Maria-DB 10.1.26

PHP 7.0.30

14.0.1 (after the update)
Updated from 13.0.6

From the log:
Error | notifications | OC\HintException: Failed to enable app notifications-- | -- | --

That's all.
The notification wasn't enabled before the update and isn't after the update.

All other features in my nextcloud are running fine.

My suggestion: Check whether the notification is enabled before the update and do not try to activate it when not necessary?

**Comment by kyaky** [comment]
Error	index	OCP\Files\NotFoundException: 
/home/website/public_html/lib/private/Files/Node/Node.php - line 216:

OC\Files\Node\Node->getFileInfo()

/home/website/public_html/lib/private/Files/Node/Node.php - line 117:

OC\Files\Node\Node->getPermissions()

/home/website/public_html/lib/private/Files/Node/Folder.php - line 176:

OC\Files\Node\Node->checkPermissions(4)

/home/website/public_html/lib/private/legacy/util.php - line 463:

OC\Files\Node\Folder->newFile("Coast.jpg")

/home/website/public_html/lib/private/legacy/util.php - line 461:

OC_Util::copyr("/home/nextc ... s", OC\Files\Node\Folder {})

/home/website/public_html/lib/private/legacy/util.php - line 433:

OC_Util::copyr("/home/nextc ... n", OC\Files\Node\Folder {})

/home/website/public_html/lib/private/User/Session.php - line 505:

OC_Util::copySkeleton("*** sensiti ... *", OC\Files\Node\Folder {})

/home/website/public_html/lib/private/User/Session.php - line 372:

OC\User\Session->prepareUserLogin("*** sensiti ... *", "*** sensiti ... *")

/home/website/public_html/core/Controller/LoginController.php - line 321:

OC\User\Session->completeLogin("*** sensiti ... *")

/home/website/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 166:

OC\Core\Controller\LoginController->tryLogin("*** sensiti ... *")

/home/website/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Cont ... {}, "tryLogin")

/home/website/public_html/lib/private/AppFramework/App.php - line 118:

OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "tryLogin")

/home/website/public_html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("OC\\Core\\C ... r", "tryLogin", OC\AppFramew ... {}, { _route: "c ... "})


OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "c ... "})

/home/website/public_html/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { _route: "c ... "})

/home/website/public_html/lib/base.php - line 987:

OC\Route\Router->match("/login")

/home/website/public_html/index.php - line 42:

OC::handleRequest()

**Comment by danielkesselberg** [comment]
You are running into this case
https://github.com/nextcloud/server/blob/483ad01a0933751732d84f40fab61c45050a7fa8/lib/private/Installer.php#L552-L558

Installer tries to enable the app but table already exist. Could you check your database server for a table `notification` or `notifications_pushtokens`. If the app is disabled but these exist something went wrong. 

If these tables exist i would create a backup before the next update, delete the tables (only `notification` and `notifications_pushtokens`), run update and see what happens :smile:

**Comment by cpu2910** [comment]
There is an empty  table named 'oc_notifications'. Could it be this one?

Then I'll try with the next update...

**Comment by danielkesselberg** [comment]
> There is an empty table named 'oc_notifications'. Could it be this one?

Yes

**Comment by cpu2910** [comment]
Thank you, I'll report after next update.

**Comment by cpu2910** [comment]
Today I dropped empty table 'oc_notifications' from the database.
Then updated from 14.0.1 to 14.0.3 and the update runs flawlessly.
Thanks for your help!
