### ISSUE TITLE
Getting 503 Error While Trying to Access the Shared File

### ISSUE THREAD

**Issue by AbdulkadirKadari** [nextcloud/server#11644]
{“reqId”:“r3EdUjwxPh0M1AqVpnCl”,“level”:3,“time”:“2018-09-11T16:35:29+00:00”,“remoteAddr”:“183.87.126.235”,“user”:“6001_136”,“app”:“no
app in
context”,“method”:“GET”,“url”:"/remote.php/webdav/1536669665614.zip",“message”:“Can
not decrypt this file, probably this is a shared file. Please ask the
file owner to reshare the file with you.”,“userAgent”:“Mozilla/5.0
(Android) ownCloud-android/6.1.106”,“version”:“13.0.4.0”}
{“reqId”:“r3EdUjwxPh0M1AqVpnCl”,“level”:4,“time”:“2018-09-11T16:35:29+00:00”,“remoteAddr”:“183.87.126.235”,“user”:“6001_136”,“app”:“webdav”,“method”:“GET”,“url”:"/remote.php/webdav/1536669665614.zip",“message”:“Exception:
{“Exception”:“OC\\Encryption\\Exceptions\\DecryptionFailedException”,“Message”:“Can
not decrypt this file, probably this is a shared file. Please ask the
file owner to reshare the file with you.”,“Code”:0,“Trace”:”#0
\/var\/www\/html\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php(464):
OCA\\Encryption\\Crypto\\Encryption->decrypt(*** sensitive
parameters replaced ***)\n#1
\/var\/www\/html\/nextcloud\/lib\/private\/Files\/Stream\/Encryption.php(295):
OC\\Files\\Stream\\Encryption->readCache()\n#2 [internal
function]: OC\\Files\\Stream\\Encryption->stream_read(7320)\n#3
\/var\/www\/html\/nextcloud\/3rdparty\/icewind\/streams\/src\/Wrapper.php(83):
fread(Resource id #99, 8192)\n#4
\/var\/www\/html\/nextcloud\/3rdparty\/icewind\/streams\/src\/CallbackWrapper.php(91):
Icewind\\Streams\\Wrapper->stream_read(8192)\n#5 [internal
function]: Icewind\\Streams\\CallbackWrapper->stream_read(8192)\n#6
\/var\/www\/html\/nextcloud\/3rdparty\/sabre\/http\/lib\/Sapi.php(80):
stream_copy_to_stream(Resource id #102, Resource id #104, ‘7320’)\n#7
\/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(498):
Sabre\\HTTP\\Sapi::sendResponse(Object(Sabre\\HTTP\\Response))\n#8
\/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254):
Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request),
Object(Sabre\\HTTP\\Response))\n#9
\/var\/www\/html\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(80):
Sabre\\DAV\\Server->exec()\n#10
\/var\/www\/html\/nextcloud\/remote.php(164):
require_once(’\/var\/www\/html\/n…’)\n#11
**{main}",“File”:"\/var\/www\/html\/nextcloud\/apps\/encryption\/lib\/Crypto\/Encryption.php",“Line”:377,“Hint”:“Cannot
decrypt this file, which is probably a shared file. Please ask the file
owner to reshare the file with you.”}",“userAgent”:“Mozilla/5.0
(Android) ownCloud-android/6.1.106”,“version”:“13.0.4.0”}**

**Getting above error with Sharedwith me Files.
Kindly Advice.**

**Comment by MorrisJobke** [comment]
"Cannot decrypt this file, which is probably a shared file. Please ask the file owner to reshare the file with you"

Could you try this. We think that this solves the issue for you. Thanks
