### ISSUE TITLE
Usercounter not display with activated "LDAP user and group backend"

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/server#11645]
Usercounter not display with activated "LDAP user and group backend"
When I disable the module, the number of users is immediately visible.

When activate "LDAP user and group backend" usercounter not displayed.

**LDAP user and group backend version?:
1.4.0

**Fresh installation or update from a prior version (from which one)?:
Fresh

**How did you install this version?:
Appstore
Information about your Instance of Nextcloud/ownCloud:

Nextcloud

**Which Version?:
14.0.1.1
```
Enabled:
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - announcementcenter: 3.3.0
  - bookmarks_fulltextsearch: 0.99.2
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - deck: 0.4.1
  - external: 3.1.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_fulltextsearch: 0.99.4
  - files_fulltextsearch_tesseract: 0.99.1
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - fulltextsearch: 0.99.3
  - fulltextsearch_elasticsearch: 0.99.2
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - polls: 0.8.3
  - provisioning_api: 1.4.0
  - richdocuments: 2.0.13
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - socialsharing_email: 1.0.4
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - accessibility
  - encryption
  - user_external
```
**Nextcloud configuration:**

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "https:***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "default_language": "de_DE",
        "force_language": "de_DE",
        "default_locale": "de_DE",
        "force_locale": "de_DE",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "allow_user_to_change_display_name": false,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": true,
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "logdateformat": "d.m.Y H:i:s",
        "share_folder": "\/Zugewiesene-Freigaben",
        "skeletondirectory": "\/var\/www\/standard_ordner",
        "updater.release.channel": "production",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_send_plaintext_only": false,
        "ldapUserCleanupInterval": 30,
        "maintenance": false
    }
}

### Server configuration

**Operating system**:
Ubuntu 18.04.1 LTS (GNU/Linux 4.15.0-36-generic x86_64)

**Web server:**:
Apache/2.4.29

**Database:**:
Maria-DB 10.1.34

**PHP version:**:
 7.2.10

```
**Are you using an external user-backend, if yes which one:
LDAP/ActiveDirectory

### Client configuration
**Device:**:
Desktop/mobile phone/ tablet/Web

**Browser:**:
All

**Operating system:**:
W7 / W10

**Comment by PpaiSanchez** [comment]
Can nobody confirm that?

**Comment by blizzz** [comment]
This is intentional. Otherwise you'll have to have a nice coffee break any time when opening the users page when the directory has a serious number of users.
