### ISSUE TITLE
User isn't notified upon sharing by e-mail

### ISSUE THREAD

**Issue by masem** [nextcloud/server#11643]
1. After creating share by e-mail, user who created it isn't notified that e-mail was sent.

### Expected behaviour
Send CC, BCC or notification to user who created share. This way
user have, at least partial confirmation, that e-mail was delivered.

### Actual behaviour
User doesn't know if e-mail was passed to mail server or if it was rejected or lost.

### Server configuration

**Operating system**:
Centos 7

**Web server:**
Apache 2.4.6

**Database:**
Mariadb 5.5.56

**PHP version:**
7.2.5

**Nextcloud version:** (see Nextcloud admin page)
13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Git

**Comment by wiswedel** [comment]
Users should give the server some trust to actually carry out what it's been ordered to do.
Notification and BCCs should be used sparingly.
