### ISSUE TITLE
hope to add Chinese Font.

### ISSUE THREAD

**Issue by chiyi4488** [nextcloud/server#11640]
At present, the English font of nextcloud can be felt to have another design to match the beauty. But with us in Chinese, our fonts are very aesthetic (not usable, it is ugly).

I suggest to add Noto Sans TC (Chinese Traditional) font
This font perfectly fits the aesthetics of Chinese and English. Perhaps you can directly replace the original nextcloud fonts with this one.

I think this font should be copyright-free (http://fonts.gstatic.com/ea/notosanstc/v1/OFL.txt)
If there are copyright issues, I am very willing to look for other fonts again.

This is the font URL
https://fonts.google.com/specimen/Noto+Sans+TC
Https://www.google.com/get/noto/help/cjk/
Https://www.google.com/get/noto/

Also, please add this message to your considerations.

Traditional Chinese (Taiwan, Hong Kong) is different from Simplified Chinese (China)
So you need to distinguish the fonts.

This will make nextcloud more and more perfect. I know this is very difficult. After all, each language has different fonts. I hope to use Chinese as a first step to slowly perfect each language.

Sincere hope can take my opinion, thank you.

**Comment by MorrisJobke** [comment]
Seems similar to #11299 - maybe we need to add more. @chiyi4488 Do you by any chance know if this is included in Open Sans somehow and what are the terms to check for?

cc @jancborchardt because we looked into this last week.

**Comment by chiyi4488** [comment]
2) Original or Modified Versions of the Font Software may be bundled,
redistributed and/or sold with any software, provided that each copy
contains the above copyright notice and this license. These can be
included either as stand-alone text files, human-readable headers or
in the appropriate machine-readable metadata fields within text or
binary files as long as those fields can be easily viewed by the user.

http://fonts.gstatic.com/ea/notosanstc/v1/OFL.txt

I think this should not be in the open sans website, but I think this font should be free to use on the website.

**Comment by chiyi4488** [comment]
另外，Roboto字型似乎沒有支援中文，這點請注意一下。
請看圖
![5](https://user-images.githubusercontent.com/30853081/46712947-2e57f380-cc86-11e8-8acf-5ab6746a7863.png)

**Comment by chiyi4488** [comment]
What does it mean that it can support Chinese?

**Comment by chiyi4488** [comment]
If there is no way to support Chinese, the displayed font will not change. (if the user is Chinese)

I think modifying the font is a good start, but it is recommended to set a multi-point font to support various languages.

**Comment by chiyi4488** [comment]
I have an idea. When you update to the Nunito font, you can also add Noto Sans TC to Nunito. This will not affect the fonts you decide to add, also the Chinese font.
This is my own blog, most of which is written in Chinese, but I want to let you see how Noto Sans TC is displayed on the webpage (all Chinese are Noto Sans TC, English except for blog titles)
I like it myself.

https://jmes311chiyi.blogspot.com

**Comment by jancborchardt** [comment]
@chiyi4488 could you test with the latest release, Nextcloud 15? This is where we added Nunito. It would be great if you can post some screenshots of how it looks for you. :slightly_smiling_face:

**Comment by chiyi4488** [comment]
![15](https://user-images.githubusercontent.com/30853081/50372129-9d958080-0603-11e9-9069-8e8c9cd33a43.png)
![16](https://user-images.githubusercontent.com/30853081/50372130-9d958080-0603-11e9-819f-f7aabbc0268f.png)
![17](https://user-images.githubusercontent.com/30853081/50372132-9d958080-0603-11e9-89ad-a916f4f408b1.png)
![19](https://user-images.githubusercontent.com/30853081/50372133-9e2e1700-0603-11e9-91ed-56965303c4b5.png)
![21](https://user-images.githubusercontent.com/30853081/50372134-9e2e1700-0603-11e9-8041-a85ca67f6956.png)
![22](https://user-images.githubusercontent.com/30853081/50372135-9e2e1700-0603-11e9-92bb-6201452a47f2.png)
![23](https://user-images.githubusercontent.com/30853081/50372136-9ec6ad80-0603-11e9-8c80-2d77bb326791.png)
![24](https://user-images.githubusercontent.com/30853081/50372137-9ec6ad80-0603-11e9-9861-c4ee4cff124a.png)

**Comment by chiyi4488** [comment]
Chinese is completely unchanged, exactly the same as the 14th edition.

**Comment by jancborchardt** [comment]
@chiyi4488 ah right, I must have misread your suggestion:

> When you update to the Nunito font, you can also add Noto Sans TC to Nunito. This will not affect the fonts you decide to add, also the Chinese font.

Would you like to contribute this as a pull request? This would be much appreciated! :)
Also, is it possible to ensure that it’s only loaded for when people actually choose Chinese as language? Because every additional font file which gets loaded will increase load time.

Thanks!

**Comment by chiyi4488** [comment]
I am very willing, but I am not very familiar with the files of Nextcloud, if you are willing to tell me what files should be modified or added.I am willing to try (I don't know how to use the code,  maybe I can't write it out at all.

**Comment by chiyi4488** [comment]
Can I use .otf?
At present, Google seems to only provide .otf...

**Comment by chiyi4488** [comment]
Hey friend, I found that with my current writing program ability, there is really no way to complete. I'm so sorry.QQ
But I can do something else to make amends for it.

But this matter needs your consent, access to permission, before it can proceed. Is that I want to help Nextcloud translate, so that my language (Taiwan Traditional Chinese) can become the third complete translation of the language. Because the current auditor, there are many good translations are not audited, I would like to put these good translations, audit them through, the overall number of outstanding numbers down, and then start the translation.(I have hardly submitted any translation now, that's why)

I am now Nextcloudpi, a translator in traditional Chinese in Taiwan (continuous translation), hoping to complete the translation of Nextcloud together, so that Taiwan users can easily use it. Hope to be able to give me the audit authority. (And then I'm very sorry that I didn't finish it.)

**Comment by jancborchardt** [comment]
We now use a native font stack as per https://github.com/nextcloud/server/pull/16055, this will be in Nextcloud 17. I think adding specific CJK fonts would not be necessary anymore as it will just use the system-provided one, correct?

**Comment by chiyi4488** [comment]
not sure XXD. Chinese font is difficult to set (the computer does not necessarily set automatically)

XXD

**Comment by chiyi4488** [comment]
I haven't tested it yet (I accidentally deleted NC) XD

**Comment by kesselb** [comment]
cc @jancborchardt keep this open?

**Comment by jancborchardt** [comment]
This is fixed already with Nextcloud 17, so we can close this. :) Thanks for the note @kesselb!

**Comment by jancborchardt** [comment]
To clarify, this was fixed by: **Use native font stack** #16055

**Comment by chiyi4488** [comment]
I don't know if I don't understand CSS System Font, but as far as I know, I created this issue because microsoft Windows has set Chinese font sits that don't fit the web page.
This change, no change to the Chinese font...
That's why I wanted to use The Noto Sans TC as web font

But if you want to use native fonts, I think you can change to Microsoft JhengHei.

TKSSS

**Comment by CL-Jeremy** [comment]
@chiyi4488 I have implemented this manually in the past for another project (in Less instead of Sass). The notes on various Chinese/CJK fonts as mentioned in https://github.com/zeripath/gitea/pull/1 generally still apply.

I have been using Nextcloud mostly on macOS and everything looks just fine there: text is rendered to the corresponding variants for Simplified and Traditional Chinese, and for Korean and Japanese anyway. I suppose macOS does the job exceptionally well there. I will try and see if this is still an issue on Windows or an earlier version of macOS/OS X.
