### ISSUE TITLE
Update from 13.0.5.2 to 14.0.1 failed

### ISSUE THREAD

**Issue by MaPhiWe** [nextcloud/server#11652]
### Steps to reproduce
1. Updating Nextcloud from 13.0.5.2 to  14.0.1 using the web updater

### Expected behaviour
The update should run through automatically without errors. 

### Actual behaviour
Update to 14.0.1

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken ADD private_key LONGTEXT DEFAULT NULL, ADD public_key LONGTEXT DEFAULT NULL, ADD version SMALLINT UNSIGNED DEFAULT 1 NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Updating database schema
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken ADD private_key LONGTEXT DEFAULT NULL, ADD public_key LONGTEXT DEFAULT NULL, ADD version SMALLINT UNSIGNED DEFAULT 1 NOT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
The update was unsuccessful. Please report this issue to the Nextcloud community.

### Server configuration

**Operating system**:
Linux xxxxxx.stratoserver.net 4.4.0-042stab133.2 #1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

Ubuntu 16.04.5 LTS

**Web server:**
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03

**Database:**
10.0.36-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:**
PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
13.0.5.2 (source)
14.0.1 (target)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**
Web download

**Signing status:**
<details>
<summary>Signing status</summary>

Sorry, can't log in at the moment

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - calendar: 1.6.1
  - cloud_federation_api: true
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - deck: 0.4.1
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - news: 12.0.4
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - workflowengine: 1.3.0
Disabled:
  - accessibility
  - encryption
  - files_external
  - support
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
               "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "13.0.5.2",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maintenance": true,
        "loglevel": 0,
        "theme": "",
        "trashbin_retention_obligation": "auto",
        "defaultapp": "calendar",
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Safari

**Operating system:**
MacOS

**Comment by ccejbc** [comment]
I had the same problem (using mariadb), fixed by following [Enabling MySQL 4-byte support](https://docs.nextcloud.com/server/13/admin_manual/configuration_database/mysql_4byte_support.html#).
