### ISSUE TITLE
Provide unambiguous reference / more details to events in activity stream / email

### ISSUE THREAD

**Issue by akki42** [nextcloud/server#11659]
### Steps to reproduce
1. Activate email and / or stream notification for activity "event was modified" in settings  
2. Modify an event (or have another user modify an event)

### Expected behaviour
Activity stream and / or email should clearly and unambiguously indicate the modified event (and, if possible, provide a direct link to the relevant event) 

### Actual behaviour
Activity stream and / or email only shows the event's title and gives no further information (e.g. date and time)

Further information (and / or a link to the relevant entry) would be helpful, for instance, if:
- another user has made the modification (you might want to use the email as a "keep up to date" service)
- there are multiple events with the same title in the calendar
- only one instance of a recurring event has been been modified

### Server configuration
**Nextcloud version:** 13.0.6

**Comment by akki42** [comment]
@skjnldsv Some months ago, you flagged this issue (opened by myself in 2018) as needing triage.
By now, there are two further, broadly similar issues (https://github.com/nextcloud/server/issues/11659,  https://github.com/nextcloud/server/issues/23443) which share a common theme:
the details provided in the activity stream in relation to added / modified events are too few to be helpful.

How could we get this addressed?

**Comment by skjnldsv** [comment]
This is from the activity app, no?

**Comment by nickvergessen** [comment]
yes, the calendar activities are in apps/dav/lib/CalDav/Activity

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/23443 since this is needed to be able to implement said features.
