### ISSUE TITLE
Controlling File Versions and Aging

### ISSUE THREAD

**Issue by melsayed91** [nextcloud/server#11657]
According to the documentation mentioned in the below link

[https://docs.nextcloud.com/server/14/admin_manual/configuration_files/file_versioning.html?highlight=versions](url)

i'm editing the file and it's creating a version every two seconds , after that i released the file edit for more than one minute , then started to edit the file again , the versions is only increasing but the deletion pattern is not working with me

when i checked the file versions for example next day , i found that some versions has been deleted automatically 

is there cron job for the deletion operations that's runs periodically , or the deletion pattern should delete the expired files immediately 

i have another question , is there a way to control creating file versions manually , is there a way to disable automatic file versions creation and just call an api manually to do that ?

P.s : I'm using WebDAV

Thanks ,

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be questions, I would like to ask you to raise them in the forums: https://help.nextcloud.com
