### ISSUE TITLE
Annoyed by password dialog

### ISSUE THREAD

**Issue by jgrete** [nextcloud/server#11651]
### Steps to reproduce
Since one or two weeks there's an annoying password dialog popping up when I triy to do something as admin in nextcloud. Whenever I leave the admin's setting page open for a while nextcloud want's me to re-authenticate. Ok, I dislike such behaviour if there's no possibility to switch it off. But now I have to enter it within a distinct and very short time. If I miss that limit the next dioalog tells me I have entered my password not in time. What do you think will be the consequence ?! I'll change my password to sometging short and unsafe. Whatever reason you had to implement such a behaviour - let the user be able to switch it OFF. Most people choose Nextcloud because they don't want to be patronized bny their computers!

### Expected behaviour
No such childish dialogboxes!

### Actual behaviour
see above

## Server configuration detail

**Operating system:** Linux 4.4.155-68-default #1 SMP Tue Sep 11 13:07:19 UTC 2018 (4ecc783) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 10.2.15

**PHP version:** 

7.0.7
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, exif, mcrypt, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, redis, shmop, sockets, sqlite3, tidy, tokenizer, xmlreader, xmlwriter, xsl, zip, zlib, Zend OPcache

**Nextcloud version:** 14.0.1 - 14.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - admin_notifications: 1.0.2
 - announcementcenter: 3.3.0
 - apporder: 0.5.0
 - audioplayer: 2.4.1
 - bookmarks: 0.13.0
 - bruteforcesettings: 1.1.0
 - calendar: 1.6.2
 - carnet: 0.8.3
 - checksum: 0.4.1
 - circles: 0.15.1
 - cloud_federation_api: 0.0.1
 - cms_pico: 0.9.7
 - comments: 1.4.0
 - contacts: 2.1.6
 - data_request: 1.1.0
 - dav: 1.6.0
 - deck: 0.4.1
 - drawio: 0.9.1
 - drop_account: 0.0.11
 - dropit: 0.1.1
 - end_to_end_encryption: 1.0.5
 - external: 3.1.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_accesscontrol: 1.4.0
 - files_antivirus: 1.3.2
 - files_automatedtagging: 1.4.0
 - files_downloadactivity: 1.3.0
 - files_external: 1.5.0
 - files_linkeditor: 1.0.7
 - files_markdown: 2.0.4
 - files_pdfviewer: 1.3.2
 - files_retention: 1.3.0
 - files_rightclick: 0.8.4
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trackdownloads: 1.3.1
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - flowupload: 0.0.8
 - gallery: 18.1.0
 - gpxedit: 0.0.9
 - gpxmotion: 0.0.7
 - gpxpod: 2.3.1
 - groupfolders: 1.3.3
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.10.0
 - metadata: 0.7.0
 - mood: 0.4.0
 - music: 0.9.2
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.2
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - ojsxc: 3.4.2
 - ownbackup: 18.8.1
 - ownpad: 0.6.8
 - password_policy: 1.4.0
 - polls: 0.8.3
 - previewgenerator: 1.1.0
 - provisioning_api: 1.4.0
 - qownnotesapi: 18.8.0
 - quota_warning: 1.3.0
 - radio: 0.6.3
 - ransomware_detection: 0.4.0
 - ransomware_protection: 1.2.0
 - registration: 0.4.3
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - sharerenamer: 2.1.0
 - smb_test: 0.2.0
 - socialsharing_diaspora: 1.0.3
 - socialsharing_email: 1.0.4
 - socialsharing_facebook: 1.0.3
 - socialsharing_googleplus: 1.0.3
 - socialsharing_twitter: 1.0.3
 - spreed: 4.0.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - telephoneprovider: 1.0.1
 - theming: 1.5.0
 - theming_customcss: 1.1.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_external: 0.4
 - user_usage_report: 1.1.0
 - w2g2: 2.2.3
 - weather: 1.5.4
 - workflowengine: 1.4.0
Disabled:
 - bookmarks_fulltextsearch
 - camerarawpreviews
 - encryption
 - files_fulltextsearch
 - files_reader
 - fulltextsearch
 - fulltextsearch_elasticsearch
 - keeporsweep
 - ocdownloader
 - passman
 - phonetrack
 - quicknotes
 - recommendation_assistant
 - spreedme
 - terms_of_service
 - twofactor_gateway
 - twofactor_rcdevsopenotp
 - twofactor_totp
 - twofactor_u2f
 - user_ldap
 - user_pwauth
 - user_saml
 - user_sql

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "grete.dedyn.io",
        "cloud-server.fritz.box",
        "hal",
        "hal.fritz.box"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/grete.dedyn.io\/nextcloud",
    "dbtype": "mysql",
    "version": "14.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "thema1",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 1.5
    },
    "log_rotate_size": 13107200,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible --norestore --convert-to pdf --outdir ",
    "loglevel": 0,
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by danielkesselberg** [comment]
Thank you for reporting :+1: I'm closing this one in favor of https://github.com/nextcloud/server/issues/11224

**Comment by army1349** [comment]
> 
> 
> Thank you for reporting 👍 I'm closing this one in favor of #11224

Should this have been closed?
I still don't see a way to disable that dialog completely.
