### ISSUE TITLE
14.0.2, 13.0.7, 12.0.12

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#11672]
# Release (~2 days before the planned release)

* [ ] prepare blog post, newsletter, social media messages (check the changelog for interesting features/fixes and possible screenshots)
* [x] update the changelog on the website https://github.com/nextcloud/nextcloud.com/pull/969
* [x] prepare "What's new" server - [Example](https://github.com/nextcloud/changelog_server/pull/5)
* [x] create the final packages
* [x] upload the final packages to `/server/prereleases` folder of the download server

## T - 30 minutes

* [x] copy the final packages to `/server/releases` folder of the download server
* [x] update the stable channel of the [updater_server](https://github.com/nextcloud/updater_server) - https://github.com/nextcloud/updater_server/pull/152
* [x] test the updater_server on the internal URL (`https://updates.nextcloud.com/internal_updater_server/`)
* [x] merge the website PR
* [x] deploy the website PR (maybe update caches)
* [x] update [wiki page](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule)
* [x] deploy "What's new" server - [repository](https://github.com/nextcloud/changelog_server/)

## T

* [ ] publish blog posts
* [ ] send newsletter
* [ ] post on social media

# Post processing (non-coding)

* [x] update the milestones in all repos (use the [milestone updater](https://github.com/nextcloud/github_helper/tree/master/milestoneupdater) for this)
* [x] update app store releases (see [documentation](https://nextcloudappstore.readthedocs.io/en/latest/prodinstall.html#sync-nextcloud-releases-from-github))
* [x] update security scanner
* [x] update owncloud-migration config on update server
* [x] update installer script on download server (see [repo](https://github.com/nextcloud/web-installer))
* [x] check wikipedia pages for release information - update pages if necessary
* [x] check wikimedia content for outdated media e.g. screenshots

**Comment by TP75** [comment]
Could be reasonable to re-open or make a rolling new issue for each release...

QM / QC ?!
