### ISSUE TITLE
Pretty URLs: its complicated

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#11673]
I run two instances of Nextcloud 14.0.1. One is run inside Docker using [nextcloud:latest](https://hub.docker.com/_/nextcloud/) image, the other one is run on [Uberspace 6](https://uberspace.de), installed with the web-installer.

Admittedly I did not pay much attention until recently for this issue, so I don't know if it has always been this way, but since upgrade to v14 both instances had `…/index.php/…` in their URLs. I did [add a trailing slash to `overwrite.cli.url`](https://github.com/nextcloud/server/issues/10678), then the Docker instance had pretty URLs, the Uberspace one did not. Questions rose…

Then I found that the Docker one has this part at the very bottom of `.htaccess`:

    <IfModule mod_rewrite.c>
    Options -MultiViews
    RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
    RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
    RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$
    RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
    RewriteCond %{REQUEST_FILENAME} !core/img/manifest.json$
    RewriteCond %{REQUEST_FILENAME} !/remote.php
    RewriteCond %{REQUEST_FILENAME} !/public.php
    RewriteCond %{REQUEST_FILENAME} !/cron.php
    RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
    RewriteCond %{REQUEST_FILENAME} !/status.php
    RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
    RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
    RewriteCond %{REQUEST_FILENAME} !/robots.txt
    RewriteCond %{REQUEST_FILENAME} !/updater/
    RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
    RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
    RewriteRule . index.php [PT,E=PATH_INFO:$1]
    RewriteBase /
    <IfModule mod_env.c>
        SetEnv front_controller_active true
        <IfModule mod_dir.c>
        DirectorySlash off
        </IfModule>
    </IfModule>
    </IfModule>

which the Uberspace one does not. I copied this to the Uberspace `.htaccess` but it did not help.

Now here comes the interesting part:

I ran `php occ maintenance:update:htaccess` on the Uberspace (non-Docker) instance, and this removed the stuff from `.htaccess`. Then I manually removed it from `.htaccess` on the Docker instance, ran `php occ maintenance:update:htaccess` and found all the stuff being back in the file. 0o

So, what is this `maintenance:update:htaccess` actually doing? And why is it doing different stuff on different instances? And why do pretty URLs work on one and not on the other instances?

Sidenote: this is [not the only incidence of different behavior of those two instances](https://help.nextcloud.com/t/custom-logo-in-mail-header/37610)

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/d96adc01b7b5dea20b64777daa04aefbcb9258e3/lib/private/Setup.php#L475-L505

When `htaccess.RewriteBase` is not empty than these rules are written to htaccess. Is this value configured for your uberspace instance?

**Comment by mcnesium** [comment]
yes, both instances have `  'htaccess.RewriteBase' => '/',` in their `config.php`

**Comment by danielkesselberg** [comment]
When you execute `php occ maintenance:update:htaccess` you should either see `.htaccess has been updated` or `Error updating .htaccess file, not enough permissions or "overwrite.cli.url" set to an invalid URL?`

Could you execute `php occ maintenance:update:htaccess; echo $?`? The last part should echo the return code (0 or 1).

**Comment by mcnesium** [comment]
Sorry, I was not specific enough. The Uberspace instance did not have `htaccess.RewriteBase` in the config. But after I added that, it did not change the `…/index.php/…` being in the URL. I did not re-check what happened to the `maintenance:update:htaccess` command. Now I rechecked that, and it now has the `IfModule mod_rewrite.c` part inside as well. Still, no pretty URLs :(

**Comment by danielkesselberg** [comment]
`'htaccess.IgnoreFrontController' => false`
 
You need to set the above when mod_env is not available (https://docs.nextcloud.com/server/13/admin_manual/configuration_server/config_sample_php_parameters.html). Looks like mod_env is not available for uberspace (https://wiki.uberspace.de/webserver:suexec#kompatibilitaet_mit_mod_env).

Please keep in mind that github is for software issues and https://help.nextcloud.com/ for configuration issues.

**Comment by mcnesium** [comment]
I know, but here people actually read and respond to stuff. [My help post is stray for two weeks now](https://help.nextcloud.com/t/custom-logo-in-mail-header/37610)
