### ISSUE TITLE
Feature request: granular permissions for users

### ISSUE THREAD

**Issue by Instagit** [nextcloud/server#11687]
As far as I know, right now it's not possible to have a user that is only allowed to create and delete other users, right?

Use case:

I want to create and delete temporary user accounts through an API call. If the user credentials in that API call are somehow intercepted, all other user data should still be secure. Optimally, the group admin would only be allowed to create and delete users, not list users or change their passwords.

Is there a way to do this that I am not aware of? And if not, what would be the best workaround? Thanks for your time. :)

**Comment by violoncelloch** [comment]
It's already possible to set a user as admin for a specific group. This way he can just manage the users in this group(s), but he doesn't have access to any other admin settings. Is this what you are looking for?

**Comment by violoncelloch** [comment]
hmm, I don't think this is possible atm
So you would like to have a group admin user which can only create and delete users but not change anything?

**Comment by Instagit** [comment]
Yes, exactly. I think it makes sense to have this in an environment where data safety is important.

The Nextcloud API already has a very refined set of actions. It only lacks a way to configure the permissions more precisely.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by szaimen** [comment]
@Pytal please add applicable labels if you are scheduling this for 23 :)

**Comment by Pytal** [comment]
> @Pytal please add applicable labels if you are scheduling this for 23 :)

Added, @CarlSchwan you may add more if you'd like :)

**Comment by szaimen** [comment]
> Added

Thanks! :)
