### ISSUE TITLE
Show color bar in quota column of % used space

### ISSUE THREAD

**Issue by gusta70** [nextcloud/server#117]
in settings/users new feature:
show color bar of % user used space of quota
http://i.imgur.com/ayvNt6L.png

**Comment by mar1u5** [comment]
https://github.com/owncloud/core/issues/12602

cc @MorrisJobke @LukasReschke

**Comment by MorrisJobke** [comment]
The problem here was that it wasn't easy to fetch all the quota without mounting all the home directories of each user. I think we have done a lot there. Maybe worth to look into this again.

**Comment by Spacefish** [comment]
Maybe it´s possible to compute the Quota of each user in a background cronjob? Just add a "last_quota_calc" column to the users table. If last_quota_calc < last_action in activity, the quota is recalculated.

**Comment by linucksrox** [comment]
Assuming the used quota for each user is updated in realtime (whenever they add/change/delete files), don't you know right away what their usage quota is? Isn't that the only way you can enforce the quota? In other words, why would you need to recalculate the used space for every user when the admin goes to the Users page? Could you instead store the user's quota value somewhere in the database, and update it whenever they add/change/delete a file, and then just read from that when you go to the Users page as admin?

**Comment by MorrisJobke** [comment]
@icewind1991 Is it nowadays easier to get the quota?

**Comment by johanehnberg** [comment]
For those looking for a way to at least detect when someone hits their limit, here is a one-liner that you can put in cron.daily or similar:

`grep InsufficientStorage nextcloud.log | grep `date '+%Y-%m-%d' -d yesterday` | jq -r .time,.user | paste - - | uniq`

It checks for any user who maxed out during the previous day. It requires jq to be installed beyond what is usually included in distros.

**Comment by johanehnberg** [comment]
The color bar could have two levels: one for active storage (equivalent of `du -sh username/files`) and another for total storage which includes versions, trashbin and any other app that makes use of remaining quota (somewhat similar to `du -sh username`).

**Comment by enoch85** [comment]
It's possible at least in ownCloud to get user quota via an API call: https://github.com/owncloud/core/issues/26829#issuecomment-268304473

**Comment by soamz** [comment]
is it implemented yet ?

How do we see users usage ?

**Comment by MorrisJobke** [comment]
> is it implemented yet ?

As this ticket is still open: no.



> How do we see users usage ?

Currently not possible.

**Comment by icewind1991** [comment]
PR is here: https://github.com/nextcloud/server/pull/5342

**Comment by linucksrox** [comment]
Thanks @icewind1991! This is totally awesome, and I really like how you can hover to get a more accurate idea of the used space. One small thing I noticed is that the last login column starts to overlap at about 1390px width or less in Chrome, but I bet some CSS magic could fix that.
