### ISSUE TITLE
Dav endpoint: add share note

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11702]
In current file listing (http://localhost/nc/remote.php/webdav/$folder), we do not get the note of a share, which any user can set when creating a share.

So it would be nice, to have a new property <share-note> to get this directly.
Otherwise all clients would have to do another call to server to get this info.

As discussed with @schiessle.

Maybe @rullzer @blizzz have a little spare time, to get this in for NC15 :heart:

**Comment by blizzz** [comment]
> Maybe @rullzer @blizzz have a little spare time, to get this in for NC15 heart

sorry, already having troubles to get my planned stuff in

**Comment by tobiasKaminsky** [comment]
Can we get this into NC16? @rullzer @blizzz? :heart:

**Comment by blizzz** [comment]
@tobiasKaminsky this is supposded to be read only, I guess?

**Comment by tobiasKaminsky** [comment]
Yes. For setting a note we already have an endpoint in share api.

I already tried to start yesterday evening. I can give you my branch.

**Comment by tobiasKaminsky** [comment]
@blizzz I created a PR #12978 if you wanna have a look :-)
