### ISSUE TITLE
Setting start dates for shares (similar to expiration dates)

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/server#11710]
Currently Nextcloud allows to set expiration dates on shares. However, in situations where someone should only get access from a certain starting point on, a "starting date" for the share would be useful.

Use-cases are e.g. calls for any kind of tenders or applications (DE: Ausschreibungen), when recipients are not supposed to see the amount or identities of applications before a certain date.

We might be able to financially contribute to such new feature.

**Comment by MorrisJobke** [comment]
cc @karlitschek @schiessle @nextcloud/sharing

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
