### ISSUE TITLE
Log Spams Errors 

### ISSUE THREAD

**Issue by artemanufrij** [nextcloud/server#11726]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Log spams errors

### Server configuration

**Operating system**: 
UbuntuServer 16.04

**Web server:** 
Apache

**Database:**
MariaDB

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 14.0

**Where did you install Nextcloud from:**
Donwloaded from nextcloud homepage and just unzipped
![screenshot_20181009_223427](https://user-images.githubusercontent.com/16517095/46697140-4131e000-cc14-11e8-86e0-ab195c6e8942.png)

**Comment by danielkesselberg** [comment]
Dup #10655
