### ISSUE TITLE
Can not delete the FOLDER left in "All Files" after deleting the folder using External Storage App

### ISSUE THREAD

**Issue by AnnePH** [nextcloud/server#11729]
### Steps to reproduce
1. Create a folder using the NC External Storage App
2. Delete the Folder you just created using the External Storage App, using the App
3. The Folder is removed from the External Storages App
4. The Folder created has not been deleted from the ALL FILES section of NC
5. The Folder can not be deleted from the ALL FILES section
6. The menu attached to the folder is missing several functions including a delete just as if NC still thinks it is a valid External Storage Folder

### Expected behaviour
The Folder should have been deleted completely from all locations

### Actual behaviour
The folder is removed from the External Storages App but not the All Files  section of NC

### Server configuration

**Operating system**:
linux
**Web server:**
UNRAID
**Database:**
mariadb
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
14
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
Linuxserver.io
**Signing status:**
<details>
<summary>Signing status</summary>
.
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
.```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
.
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
.```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
.
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
.```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
firefox
**Operating system:**
linux
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

**Comment by AnnePH** [comment]
Thanks for the response, but 
10547 -   IF I could delete the Folder in the first place I could try this
6347  -  if I could not enable External Storage, I could not have created the LOCAL Folder 
8931   - I can delete a file within the local Folder created
9170 (redirect) - ?
8241 (image) - ?

It "appears" as if the External Storage App removes the FOLDER from the External Storage App but not the All Files part of NC

**Comment by tomtomas99911** [comment]
Yes, i am facing this issue too.

**Comment by 0x90v1** [comment]
Any update regarding this issue? Also have that issue now using to current version of nextcloud

**Comment by skjnldsv** [comment]
Still occurring ?
