### ISSUE TITLE
Upload to shared folder broken

### ISSUE THREAD

**Issue by nonplusnl** [nextcloud/server#1173]
### Steps to reproduce
1.  User admin creates folder and shares with user1, giving user1 at least permission to create files
2.  User1 tries to upload to shared folder

### Expected behaviour
Upload should complete normaly (as it did in Nextcloud 9.0.53

### Actual behaviour
Upload fails (both Android client, browser and WebDAV). Log complains about InsufficientStorage and quota. Quota and storage however are not constraining (neither for user admin nor for user user1). 
Additionally, changing quota impossible, cannot set default or unlimited quota (a bug filed elsewhere I believe). Setting 'quota_include_external_storage' => false does not help either.

### Server configuration
Ubuntu 16.04
Apache 
MySQL
Php7
Nextcloud 10 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 9.0.53, worked perfectly before upgrade

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - audioplayer: 1.1.0
  - calendar: 1.3.3
  - contacts: 1.3.1.0
  - dav: 1.0.0
  - documents: 0.13.1
  - external: 1.2
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - gpxpod: 1.0.3
  - mail: 0.5.3
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - user_external
  - user_ldap
  - user_saml</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => 'oce252cc5d82',
  'passwordsalt' => DELETED
  'trusted_domains' =>
  array (
    DELETED  ),
  'datadirectory' => DELETED
  'overwrite.cli.url' => 'https://www.nonplus.nl/npc',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'installed' => true,
  'maintenance' => false,
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbuser' => DELETED
  'dbpassword' => DELETED
  'forcessl' => true,
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'nonplus.nl',
  'theme' => '',
  'secret' => DELETED
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'loglevel' => 3,
  'logtimezone' => 'Europe/Berlin',
  'log_authfailip' => false,
  'log_rotate_size' => 10485760,
  'mail_smtphost' => 'www.nonplus.nl',
  'mail_smtpport' => '587',
  'mail_smtpsecure' => 'ssl',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'appstore.experimental.enabled' => true,
  'trashbin_retention_obligation' => 'auto',
  'updatechecker' => false,
  'htaccess.RewriteBase' => '/npc',
  'singleuser' => false,
  'quota_include_external_storage' => false,
);
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local only (not used for uploads)

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by Mitchou** [comment]
If you, like me, got error "507 Insufficient Storage" in your log, then probably you should try this patch:
https://github.com/owncloud/core/issues/25582#issuecomment-241327681

**Comment by rullzer** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/1179

**Comment by nonplusnl** [comment]
Indeed fixed with #1179 , closing.
