### ISSUE TITLE
Blacklisted files error 500

### ISSUE THREAD

**Issue by kevin88000** [nextcloud/server#11735]
### Steps to reproduce
1. Upload a blacklisted file (like the default .htaccess)

### Expected behaviour

Display a message that indicate the file is blacklisted

### Actual behaviour

Server sent a 500 error code and web gui display "Internal server error"

### Server configuration

**Operating system**: Debian 9.5

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1.26

**PHP version:** 7.0

**Nextcloud version:** 14.0.2 RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** From 13.0.6

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - workflowengine: 1.4.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xxxxxx.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.xxxxxxx.fr",
        "dbtype": "mysql",
        "version": "14.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "filelocking.enabled": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{imap.xxxxxx.fr:993\/imap\/ssl}"
                ]
            }
        ],
        "app.mail.accounts.default": {
            "email": "%USERID%",
            "imapHost": "imap.xxxxx.fr",
            "imapPort": 993,
            "imapUser": "%USERID%",
            "imapSslMode": "ssl",
            "smtpHost": "smtp.xxxxxx.fr",
            "smtpPort": 465,
            "smtpUser": "%USERID%",
            "smtpSslMode": "ssl"
        },
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "log_rotate_size": 10485760,
        "enable_previews": false,
        "updater.release.channel": "beta",
        "activity_expire_days": 180,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Yes, IMAP

### Client configuration
**Browser:** Google Chrome v69.0.3497.100

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
XX.XX.XXX.XX - - [10/Oct/2018:12:07:10 +0200] "PUT /remote.php/webdav/.htaccess HTTP/1.1" 500 954 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"n96DJeAWuFgYMrebXyfg","level":4,"time":"2018-10-10T10:07:10+00:00","remoteAddr":"xx.xx.xxx.xx","user":"xxxxx@xxxxxx.fr","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/.htaccess","message":{"Exception":"OCP\\Files\\InvalidPathException","Message":"","Code":0,"Trace":[{"file":"\/home\/sites\/xxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","line":207,"function":"free_space","class":"OC\\Files\\View","type":"->","args":[".htaccess"]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","line":168,"function":"getFreeSpace","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["\/\/.htaccess"]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","line":95,"function":"checkQuota","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["\/\/.htaccess"]},{"function":"beforeCreateFile","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":[".htaccess",null,{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},false]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"},"beforeCreateFile"],[".htaccess",null,{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},false]]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1094,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeCreateFile",[".htaccess",null,{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},false]]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":[".htaccess",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.xxxxx.fr\/remote.php\/webdav\/.htaccess","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.xxxxx.fr\/remote.php\/webdav\/.htaccess","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.xxxxx.fr\/remote.php\/webdav\/.htaccess","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.xxxxx.fr\/remote.php\/webdav\/.htaccess","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/sites\/xxxxx.fr\/cloud\/remote.php","line":163,"args":["\/home\/sites\/xxxxx.fr\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/home\/sites\/xxxxx.fr\/cloud\/lib\/private\/Files\/View.php","Line":1100,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"14.0.2.1"}
</details>

**Comment by timm2k** [comment]
Files with pattern ".ht*" are blocked by default from serving by Apache httpd's configuration. Try to find something like this in your config:
```
<Files ".ht*">
    Require all denied
</Files>
```
You can comment out this block, reload httpd and try to upload a .htaccess file to see if it now works as expected. I absolutly recommend to take this block active again after you finished your testing.

**Comment by kevin88000** [comment]
Your right, .htaccess file is not the best file to make a test.

In config.php, i've set :
```
'blacklisted_files' => array ( '.htaccess', 'test.jpg' )
```
Then, i've uploaded (using web gui) a file test.jpg, bellow you can see nextcloud's log and apache log.

Nextcloud log
```
{"reqId":"AHWpVV8hKsx9zgYBAYxM","level":4,"time":"2018-10-11T08:22:44+00:00","remoteAddr":"XX.XX.XXX.XX","user":"xxxxxxx.xxxxxxx@xxxxxxx.fr","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/test.jpg","message":{"Exception":"OCP\\Files\\InvalidPathException","Message":"","Code":0,"Trace":[{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","line":207,"function":"free_space","class":"OC\\Files\\View","type":"->","args":["test.jpg"]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","line":168,"function":"getFreeSpace","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["\/\/test.jpg"]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","line":95,"function":"checkQuota","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["\/\/test.jpg"]},{"function":"beforeCreateFile","class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin","type":"->","args":["test.jpg",null,{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},false]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"},"beforeCreateFile"],["test.jpg",null,{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},false]]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1094,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeCreateFile",["test.jpg",null,{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"},false]]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["test.jpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/remote.php","line":163,"args":["\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/home\/sites\/xxxxxxx.fr\/cloud\/lib\/private\/Files\/View.php","Line":1100,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/69.0.3497.100 Safari\/537.36","version":"14.0.2.1"}
```

Apache log :
```
XX.XX.XXX.XX - - [11/Oct/2018:10:22:43 +0200] "PUT /remote.php/webdav/test.jpg HTTP/1.1" 500 954 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36"
```

Web gui continue to show "Internal server error"

**Comment by timm2k** [comment]
just reformatting your nextcloud error message...
```
{"reqId":"AHWpVV8hKsx9zgYBAYxM"
"level":4
"time":"2018-10-11T08:22:44+00:00"
"remoteAddr":"XX.XX.XXX.XX"
"user":"xxxxxxx.xxxxxxx@xxxxxxx.fr"
"app":"webdav"
"method":"PUT"
"url":"\/remote.php\/webdav\/test.jpg"
"message":{"Exception":"OCP\\Files\\InvalidPathException"
"Message":""
"Code":0
"Trace":[{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php"
"line":207
"function":"free_space"
"class":"OC\\Files\\View"
"type":"->"
"args":["test.jpg"]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php"
"line":168
"function":"getFreeSpace"
"class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"
"type":"->"
"args":["\/\/test.jpg"]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php"
"line":95
"function":"checkQuota"
"class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"
"type":"->"
"args":["\/\/test.jpg"]}
{"function":"beforeCreateFile"
"class":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"
"type":"->"
"args":["test.jpg"
null
{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}
false]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php"
"line":105
"function":"call_user_func_array"
"args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"}
"beforeCreateFile"]
["test.jpg"
null
{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}
false]]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php"
"line":1094
"function":"emit"
"class":"Sabre\\Event\\EventEmitter"
"type":"->"
"args":["beforeCreateFile"
["test.jpg"
null
{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}
false]]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php"
"line":529
"function":"createFile"
"class":"Sabre\\DAV\\Server"
"type":"->"
"args":["test.jpg"
null
null]}
{"function":"httpPut"
"class":"Sabre\\DAV\\CorePlugin"
"type":"->"
"args":[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg"
"__class__":"Sabre\\HTTP\\Request"}
{"__class__":"Sabre\\HTTP\\Response"}]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php"
"line":105
"function":"call_user_func_array"
"args":[[{"__class__":"Sabre\\DAV\\CorePlugin"}
"httpPut"]
[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg"
"__class__":"Sabre\\HTTP\\Request"}
{"__class__":"Sabre\\HTTP\\Response"}]]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php"
"line":479
"function":"emit"
"class":"Sabre\\Event\\EventEmitter"
"type":"->"
"args":["method:PUT"
[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg"
"__class__":"Sabre\\HTTP\\Request"}
{"__class__":"Sabre\\HTTP\\Response"}]]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php"
"line":254
"function":"invokeMethod"
"class":"Sabre\\DAV\\Server"
"type":"->"
"args":[{"absoluteUrl":"https:\/\/cloud.xxxxxxx.fr\/remote.php\/webdav\/test.jpg"
"__class__":"Sabre\\HTTP\\Request"}
{"__class__":"Sabre\\HTTP\\Response"}]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php"
"line":80
"function":"exec"
"class":"Sabre\\DAV\\Server"
"type":"->"
"args":[]}
{"file":"\/home\/sites\/xxxxxxx.fr\/cloud\/remote.php"
"line":163
"args":["\/home\/sites\/xxxxxxx.fr\/cloud\/apps\/dav\/appinfo\/v1\/webdav.php"]
"function":"require_once"}]
"File":"\/home\/sites\/xxxxxxx.fr\/cloud\/lib\/private\/Files\/View.php"
"Line":1100
"CustomMessage":"--"}
"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML
 like Gecko) Chrome\/69.0.3497.100 Safari\/537.36"
"version":"14.0.2.1"}
```

**Comment by skjnldsv** [comment]
``` json
{
  "reqId": "bgBEWglA4cRQLQOjA0dA",
  "level": 4,
  "time": "2019-06-14T05:53:32+00:00",
  "remoteAddr": "172.21.0.1",
  "user": "admin",
  "app": "webdav",
  "method": "PUT",
  "url": "/remote.php/webdav/.htaccess",
  "message": {
    "Exception": "OCP\\Files\\InvalidPathException",
    "Message": "",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/dav/lib/Connector/Sabre/QuotaPlugin.php",
        "line": 207,
        "function": "free_space",
        "class": "OC\\Files\\View",
        "type": "->",
        "args": [
          ".htaccess"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Connector/Sabre/QuotaPlugin.php",
        "line": 168,
        "function": "getFreeSpace",
        "class": "OCA\\DAV\\Connector\\Sabre\\QuotaPlugin",
        "type": "->",
        "args": [
          "//.htaccess"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/Connector/Sabre/QuotaPlugin.php",
        "line": 95,
        "function": "checkQuota",
        "class": "OCA\\DAV\\Connector\\Sabre\\QuotaPlugin",
        "type": "->",
        "args": [
          "//.htaccess"
        ]
      },
      {
        "function": "beforeCreateFile",
        "class": "OCA\\DAV\\Connector\\Sabre\\QuotaPlugin",
        "type": "->",
        "args": [
          ".htaccess",
          null,
          {
            "__class__": "OCA\\DAV\\Connector\\Sabre\\Directory"
          },
          false
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "OCA\\DAV\\Connector\\Sabre\\QuotaPlugin"
            },
            "beforeCreateFile"
          ],
          [
            ".htaccess",
            null,
            {
              "__class__": "OCA\\DAV\\Connector\\Sabre\\Directory"
            },
            false
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 1094,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "beforeCreateFile",
          [
            ".htaccess",
            null,
            {
              "__class__": "OCA\\DAV\\Connector\\Sabre\\Directory"
            },
            false
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",
        "line": 525,
        "function": "createFile",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          ".htaccess",
          null,
          null
        ]
      },
      {
        "function": "httpPut",
        "class": "Sabre\\DAV\\CorePlugin",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://dev.skjnldsv.com/remote.php/webdav/.htaccess",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php",
        "line": 105,
        "function": "call_user_func_array",
        "args": [
          [
            {
              "__class__": "Sabre\\DAV\\CorePlugin"
            },
            "httpPut"
          ],
          [
            {
              "absoluteUrl": "https://dev.skjnldsv.com/remote.php/webdav/.htaccess",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 479,
        "function": "emit",
        "class": "Sabre\\Event\\EventEmitter",
        "type": "->",
        "args": [
          "method:PUT",
          [
            {
              "absoluteUrl": "https://dev.skjnldsv.com/remote.php/webdav/.htaccess",
              "__class__": "Sabre\\HTTP\\Request"
            },
            {
              "__class__": "Sabre\\HTTP\\Response"
            }
          ]
        ]
      },
      {
        "file": "/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php",
        "line": 254,
        "function": "invokeMethod",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": [
          {
            "absoluteUrl": "https://dev.skjnldsv.com/remote.php/webdav/.htaccess",
            "__class__": "Sabre\\HTTP\\Request"
          },
          {
            "__class__": "Sabre\\HTTP\\Response"
          }
        ]
      },
      {
        "file": "/var/www/html/apps/dav/appinfo/v1/webdav.php",
        "line": 80,
        "function": "exec",
        "class": "Sabre\\DAV\\Server",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/remote.php",
        "line": 163,
        "args": [
          "/var/www/html/apps/dav/appinfo/v1/webdav.php"
        ],
        "function": "require_once"
      }
    ],
    "File": "/var/www/html/lib/private/Files/View.php",
    "Line": 1103,
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.80 Safari/537.36",
  "version": "17.0.0.1"
}
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
