### ISSUE TITLE
Nextcloud Server extremely slow after Upgrade to 14.0.2 RC2

### ISSUE THREAD

**Issue by frake65** [nextcloud/server#11731]
### Steps to reproduce
1. Upgrade from version 14.0.2 RC1 to RC2
2. Try web interface

### Expected behaviour
Speed should be similar to the speed I had before

### Actual behaviour
One server is no longer reachable (timeout) - onother one responses extremely slow

### Server configuration
Ubuntu 16.04.5 LTS‬
apache
mySQL
PHP 7.2

Nextcloud version:14.0.2 RC2

Updated from Nextcloud version:14.0.2 RC1 by internal updater

--- additional info:
top does not show any issues.

**Comment by MorrisJobke** [comment]
Those are the only changes and I couldn't spot why it should be drastically slower: https://github.com/nextcloud/server/pull/11715

Also we don't notice something like that.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
