### ISSUE TITLE
Document supported RFCs

### ISSUE THREAD

**Issue by dilyanpalauzov** [nextcloud/server#11754]
* Fill at https://en.m.wikipedia.org/wiki/Comparison_of_CalDAV_and_CardDAV_implementations -> Server implementatioms what protocols NextCloud supports, possibly adding new columns.

* Create a list of all supported standards by NextCloud, like https://www.cyrusimap.org/imap/rfc-support.html

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer

**Comment by MorrisJobke** [comment]
@schiessle

**Comment by szaimen** [comment]
cc @nextcloud/community-mgmt who would be able to contribute/write such a list? Is this feasible?
