### ISSUE TITLE
external storage naming

### ISSUE THREAD

**Issue by tomfun** [nextcloud/server#11755]
Please add validation for adding external storage:
name should not have '/' symbol.

I've added, but I can't use it. Well, webplayer somehow get known about music, but other parts (wev, android app) can't see it.

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by MasterOfDeath** [comment]
Have added PR https://github.com/nextcloud/server/pull/12049

**Comment by szaimen** [comment]
Actually, this is a feature: baming it '/' will make it the root storage of appicable users. So this is expected. -> closing
