### ISSUE TITLE
Share by mail with added note, french email has &quot; surrounding the filename

### ISSUE THREAD

**Issue by la-fraise** [nextcloud/server#11767]
### Steps to reproduce
1. Activate share by mail app with french translation
2. Share a file by mail
3. Add a quote

### Expected behaviour
Mail with the note should have quotes or « » surrounding the filename

### Actual behaviour
Mail with the note have &quot; (html code) that appears, at least true with thunderbird and outlook 2016

### Server configuration
**Nextcloud version:**14.0.1 (but from sources, same in 14.0.2)

**Possible Fix:**
<details>
<summary>in file apps/sharebymail/l10n/fr.json, line 24</summary>

```
"%1$s shared »%2$s« with you and wants to add:" : "%1$s a partagé \"%2$s\" avec vous et veut ajouter :",
"%1$s shared »%2$s« with you and wants to add" : "%1$s a partagé \"%2$s\" avec vous et veut ajouter ",

replace with :
"%1$s shared »%2$s« with you and wants to add:" : "%1$s a partagé «%2$s» avec vous et veut ajouter :",
"%1$s shared »%2$s« with you and wants to add" : "%1$s a partagé «%2$s» avec vous et veut ajouter ",

```
</details>

<details>
<summary>in file apps/sharebymail/l10n/fr.js, line 26</summary>

```
"%1$s shared »%2$s« with you and wants to add:" : "%1$s a partagé \"%2$s\" avec vous et veut ajouter :",
"%1$s shared »%2$s« with you and wants to add" : "%1$s a partagé \"%2$s\" avec vous et veut ajouter ",

replace with :
"%1$s shared »%2$s« with you and wants to add:" : "%1$s a partagé «%2$s» avec vous et veut ajouter :",
"%1$s shared »%2$s« with you and wants to add" : "%1$s a partagé «%2$s» avec vous et veut ajouter ",
```
</details>

**Comment by medcloud** [comment]
Hello, this workaround seems to work well !

But this needs to follow up I10n files after each NC update

Somebody may know **when it may be possible to fix it definitely** in a next version of NC server ? 

Many thanks for your feedback

**Comment by kurn77** [comment]
PR at #24849

**Comment by kurn77** [comment]
Hello @skjnldsv : for next time, please, would you know how I may add reviewers in PR ? (many thanks, this is my first PR)

Maybe just mentionning names in the PR ? :-)

**Comment by kurn77** [comment]
For illustration (issue seen) : 

![image](https://user-images.githubusercontent.com/74493472/103226409-58139880-492c-11eb-8393-5ba5784771ae.png)

**Comment by skjnldsv** [comment]
Fixed on transifex https://www.transifex.com/nextcloud/nextcloud/translate/#fr/sharebymail/149442098
