### ISSUE TITLE
14.01 does not update to 14.02 if "apps2" is present

### ISSUE THREAD

**Issue by jjholv** [nextcloud/server#11760]
Hello,

reporting issue #8869 reappairing. On a fresh install of 14.0.1 when trying to update to 14.0.2 via web updater the updater halts as "apps2" is present in the extra file/folder check.

My stock config.php:
```
    0 =>
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
```
Changing  `'path' => '/apps2',` to `'path' => '/nextcloud/apps2',` fixes the issue.

**Comment by MorrisJobke** [comment]
> reporting issue #8869 reappairing. On a fresh install of 14.0.1 when trying to update to 14.0.2 via web updater the updater halts as "apps2" is present in the extra file/folder check.

Weird, because 14.0.1 should ship the updated updater: https://github.com/nextcloud/updater/pull/107#issuecomment-423937915



> Changing `'path' => '/apps2',` to `'path' => '/nextcloud/apps2',` fixes the issue.

This also looks weird. How does your folder structure looks like?

**Comment by jjholv** [comment]
Can you elaborate which part? Root, `/nextcloud/` or something else?

**Comment by MorrisJobke** [comment]
How is your folder structure and what folders are served by your Webserver.

**Comment by MorrisJobke** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
