### ISSUE TITLE
Enhancement: Progress during update downloading

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#11768]
Lately the downloading step during the web baser updater is taking very long (~10 Minutes). This might be due to my internet connection, I'm not sure.

That led to the point where I wasn't sure if the the download was even progressing or if it has failed.

My enhancement idea is, to show some sort of progressbar or percentage value to signal, that downloading is still progressing?!

Thanks

**Comment by MorrisJobke** [comment]
This is an issue within the updater. Thus please report it to the repository of the updater: https://github.com/nextcloud/updater.
