### ISSUE TITLE
Nextcloud update deletes .htaccess and thus can't be accessed at all

### ISSUE THREAD

**Issue by sebaki** [nextcloud/server#11774]
### Steps to reproduce
1. Set up your server to use php5 generally
2. Setup your .htaccess in your nextcloud subfolder to use php7 
3. Start update (especially from 13 -> 14 or 14.0.1 -> 14.0.2)

### Expected behaviour
I run my server generally with php5. I set up a nextcloud subfolder to run with php7 using configuration of .htaccess in those subfolder. When I need to update nextcloud, I use my web browser and expect to just update nextcloud files and not to delete some other files. So after the update it should work as expected.

### Actual behaviour
Instead the update process deletes my .htaccess configuration file and the server falls back into php5 which is unfortunately not supported.

### Server configuration

**Operating system**: Hosting package, so I don't know.

**Web server:** Hosting package, so I don't know.

**Database:** Hosting package, so I don't know.

**PHP version:** 7 (fallback 5)

**Nextcloud version:** 14.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Via update

**Comment by MorrisJobke** [comment]
> ###
> Instead the update process deletes my .htaccess configuration file and the server falls back into php5 which is unfortunately not supported.

Editing the .htaccess file is not supported as we overwrite it during the upgrade and then generate a new one to include the needed dynamic values.

Configure the change inside your Webserver for that folder and the issue should be gone.

We could of course also try to extract the manually added stuff, but this could cause also a lot of problem and the requests for this are quite low. Thus there are currently no plans to implement such a feature and I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by sebaki** [comment]
Thanks for information. It's a pity.

And it's even more complicated. The only possibility to set up the php-version is using the htaccess-file. If I change this file after the first part of the update process and add a line to switch the php-version to 7.2, the integrity check fails. So I have to turn off this check, which I would never suggest.
