### ISSUE TITLE
Advertisement "Get your own free account" placed below shared filed page

### ISSUE THREAD

**Issue by geonom** [nextcloud/server#11788]
### Steps to reproduce
1. Share a file via link
2. Click on the link
3. On the bottom of the page a link to nextcloud signup appears

### Expected behaviour
No external advertising without my consent. Even if this flag in the config file were working, which it somehow isn't:
```
'simpleSignUpLink.shown' => true,
```

### Actual behaviour
There is external advertisement added without my consent, potentially confusing users into thinking it was message from me, as it is linked directly to my cloud store name tag, see:
https://cloud.geoadel.net/index.php/s/3aiPpzcGd9A8R9F

### Server configuration

Nextcloud

Version: 14.0.1.1

Installed Apps: 35

Apps updates availlable: 0
PHP Version: 7.0.30

RAM-Limit: 512 MB

Maximum Execution time limit: 3600

Max Size for Uploads: 511 MB

Database: mysql

Version: 5.7.21

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud

**Where did you install Nextcloud from:**
all-inkl.com is the provider

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
<?php
$CONFIG = array (
'trusted_domains' => 
  array (
    0 => 'cloud.geoadel.net',
  ),
 'overwrite.cli.url' => 'http://cloud.geoadel.net',
  'dbtype' => 'mysql',
  'version' => '14.0.1.1',
  'dbhost' => 'localhost',
  'dbport' => '',
  'mysql.utf8mb4' => true,
  'installed' => true,
'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'simpleSignUpLink.shown' => true,
);

```
</details>

**Are you using encryption:** I don't think so

**Comment by danielkesselberg** [comment]
May I ask you why you open a new Issue when you found the one with the solution already?

**Comment by geonom** [comment]
Sure, as I wrote above, the fix does not work on my nextcloud installation. I hope that is not simply my incompetence at implementing the fix in the config file (which is a possibility, though I tried to check as best I can :) ).

For that reason I included my config file (minus the password and salt stuff)...

**Comment by geonom** [comment]
Ah, forget it, stupid me  indeed, thanks!

**Comment by geonom** [comment]
I thought the fix would be to simply copy "the fix", then instead you have to change the flag from true to false, to actually have the fix... that is slightly confusing though of course if you read and understand the comment above, it becomes quite clear, my fault.

To me, that flag not being false by default actually is an issue, but well... at least the "fix" is working :)

**Comment by Sx3** [comment]
https://github.com/nextcloud/server/issues/11327#issuecomment-646726493
