### ISSUE TITLE
/.well-known/caldav and /.well-known/carddav not resolved on port <> 80

### ISSUE THREAD

**Issue by macmeck** [nextcloud/server#11789]
I have Nextcloud 14.0.3 running on a port different than 80. Nginx is configured according to the documentation. Though, `Security & setup warnings` shows up 

> Your web server is not properly set up to resolve "/.well-known/caldav".
> Your web server is not properly set up to resolve "/.well-known/carddav".

I guess that the redirect in the nginx configuration redirects only to the standard ports 80/443. I haven't found out how to add the correct port dynamically yet.

```
Redirect 301 /.well-known/carddav /nextcloud/remote.php/dav
Redirect 301 /.well-known/caldav /nextcloud/remote.php/dav

```

### Steps to reproduce
1. Install Nextcloud
2. setup nginx according to documentation

### Expected behaviour
No warnings should be displayed.

### Actual behaviour
I get two warnings mentioned above:
> Your web server is not properly set up to resolve "/.well-known/caldav".
> Your web server is not properly set up to resolve "/.well-known/carddav".

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** nginx

**Database:** mariaDB

**PHP version:** 7.2

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Comment by macmeck** [comment]
@blackcrack , I don't get your point. The issue here seems to be related to the redirect to the wrong port within the nginx configuration.

**Comment by macmeck** [comment]
@MorrisJobke , one could also argue that one of Nextcloud's tests fails if the system is being set up as suggested by Nextcloud's documentation...

**Comment by blackcrack** [comment]
hey, i have the Pokal of nerving peoples.. !
this is a thing of caldav and cardav ,

the port it is an other thing, you have setting up the port 80,
but the nextcloud should use the ssl port so 443 ..

this have nothing to do with the redirection...

and like MorrisJobke told, it's a thing of configuration of you own Webserver,
if you can not handle that, it's not a thing of Support of Nextcloud lovers 
and Community Peoples who want support the peoples, where understand 
how it works.. so, read the [url=https://help.nextcloud.com/t/how-to-faq-wiki/9068]FaQ[/url] or the [url=https://docs.nextcloud.com/]Documentation[/url]

I be one of the Community out of the net and not a member of the NC-Group peoples,
but my vote is on this step for mark this tread to ro !

best regards
Blacky

**Comment by MorrisJobke** [comment]
> @MorrisJobke , one could also argue that one of Nextcloud's tests fails if the system is being set up as suggested by Nextcloud's documentation... If we find out how to tackle the port issue, the documentation could be improved and address more use cases.

True - for this a ticket in the documentation repository is the best way. Nevertheless this is the bug tracker of the servers code and there is not much we can do here from a code perspective.

**Comment by macmeck** [comment]
Point taken, I haven't seen the issue tracker in the documentation repository. I'll check over there. Thanks!
