### ISSUE TITLE
Upgrade from 13.0.7 to 14.0.2 failed

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#11797]
### Steps to reproduce
1. upgrade 13.0.6 to 13.0.7 via docker
2. upgrade 13.0.7 to 14.0.2.2
3.

### Expected behaviour
Running upgrade but stuck in maintenance mode

### Actual behaviour
When I run upgrade via webinterface it tell me that cloud_federation_api could not found a version in app store. I already deactivated most apps, but is not possible for all.
When I run the upgrade via command line I get following error

Error: Call to undefined method GuzzleHttp\Client::request() in /var/www/html/lib/private/Http/Client/Client.php:161
Stack trace:
#0 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(106): OC\Http\Client\Client->get('https://apps.ne...', Array)
#1 /var/www/html/lib/private/App/AppStore/Fetcher/AppFetcher.php(80): OC\App\AppStore\Fetcher\Fetcher->fetch('', '')
#2 /var/www/html/lib/private/App/AppStore/Fetcher/Fetcher.php(170): OC\App\AppStore\Fetcher\AppFetcher->fetch('', '')
#3 /var/www/html/lib/private/Installer.php(385): OC\App\AppStore\Fetcher\Fetcher->get()
#4 /var/www/html/lib/private/Updater.php(445): OC\Installer->isUpdateAvailable('cloud_federatio...')
#5 /var/www/html/lib/private/Updater.php(256): OC\Updater->upgradeAppStoreApps(Array)
#6 /var/www/html/lib/private/Updater.php(126): OC\Updater->doUpgrade('14.0.2.2', '13.0.7.2')
#7 /var/www/html/core/Command/Upgrade.php(262): OC\Updater->upgrade()
#8 /var/www/html/3rdparty/symfony/console/Command/Command.php(251): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/html/3rdparty/symfony/console/Application.php(946): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/html/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/console.php(96): OC\Console\Application->run()
#14 /var/www/html/occ(11): require_once('/var/www/html/c...')

### Server configuration

**Operating system**
official docker container
**Database:**
mysql 5.7.17

**Comment by CordlessWool** [comment]
ok i found the solution in issue #11199, had to deactivate files_external_gdrive

**Comment by ftoledo** [comment]
> ok i found the solution in issue #11199, had to deactivate files_external_gdrive

This work for me!
