### ISSUE TITLE
Upgrading to new version - what a mess

### ISSUE THREAD

**Issue by nexus186** [nextcloud/server#11799]
I was trying to upgrade to 14.0.3 from 14.0.1 today through the web interface and it got stuck at the "parsing response failed". 

I tried a variety of solutions from google, none of which worked.

Then I tried manually updating by invoking php updater.phar, it worked but then the web interface complained about tons of "EXTRA_FILE" files being found....which I couldn't actually find in the folder.

My 14.0.1 installation was a stock installation, nothing customized other than the data directory being in a different location (the permissions and the configs were set correctly). How can the upgrade fail on a stock installation??? Was this even tested before it was pushed out??

**Comment by danielkesselberg** [comment]
Could you share these "EXTRA_FILE"? (not the files itself only the warning)

**Comment by janvlug** [comment]
Maybe related to #10677. I also got the "parsing response failed" initially. I proceeded by manually setting 'maintenance' => false in the config.php file. Then the update finished.
But now the update from 14.0.2 to 14.0.3 gives me the error message about the ocm-provider extra file.

**Comment by janvlug** [comment]
> Could you share these "EXTRA_FILE"? (not the files itself only the warning)

The error message is:

The following extra files have been found:
- ocm-provider
<br>
ocm-privider is actually a directory, that contains one file: index.php

See also this screenshot: https://github.com/nextcloud/server/issues/10677#issuecomment-429264402

**Comment by wiswedel** [comment]
resolved in #10677
