### ISSUE TITLE
Vue check script does not work with split output

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#11794]
See https://github.com/nextcloud/server/pull/11793

0.js 1.js etc are not checked for differences.
Also. I must admit I don't like those names :P

@skjnldsv please have a look
CC: @juliushaertl @ChristophWurst as our other vue overlords

**Comment by skjnldsv** [comment]
@rullzer we can easily change the chunk names: 
I thought I properly addapted the script to check the other names as well: https://github.com/nextcloud/server/commit/b7d82e9262dca73f05d100fb77ccdea349807c1e

It was working before, @ChristophWurst  just changed the names of my chunks settings here: https://github.com/nextcloud/server/pull/11675

https://drone.nextcloud.com/nextcloud/server/10957/91
> Entrypoint main = settings-vue.js settings-vue.js.map
> Comparing 0.settings-vue.js to the original
> 0.settings-vue.js build is up-to-date
> Comparing 2.settings-vue.js to the original
> 2.settings-vue.js build is up-to-date
> Comparing 3.settings-vue.js to the original
> 3.settings-vue.js build is up-to-date
> Comparing 4.settings-vue.js to the original
> 4.settings-vue.js build is up-to-date
> Comparing settings-vue.js to the original
> settings-vue.js build is up-to-date

**Comment by ChristophWurst** [comment]
> @ChristophWurst I don't think we should use the same webpack config for different settings apps. I think we should have individual apps folder for each settings part and not merge everything in the same location. The big settings pages like users/apps are very different from small settings sections that gets added into the main settings list. I think we need to split the two :)

Why not? This drastically reduces the overall size of script bundles to download and prevents us from having numerous configs to maintain. IMO webpack has multiple entrypoints for exactly this use case.

**Comment by skjnldsv** [comment]
> > @ChristophWurst I don't think we should use the same webpack config for different settings apps. I think we should have individual apps folder for each settings part and not merge everything in the same location. The big settings pages like users/apps are very different from small settings sections that gets added into the main settings list. I think we need to split the two :)
> 
> Why not? This drastically reduces the overall size of script bundles to download and prevents us from having numerous configs to maintain. IMO webpack has multiple entrypoints for exactly this use case.

Good question. I think it's because it looks confusing to me to mix the two of them. Structurally speaking. Especially since this is completely different behaviour and use. 
The overall size of the bundle is indeed important, but for small apps like the one you added, I'm not sure this will matters that much, especially with the agressive caching we're doing :)

**Comment by MorrisJobke** [comment]
I guess #12282 is a try to fix this, right?

**Comment by skjnldsv** [comment]
Yep

**Comment by MorrisJobke** [comment]
Let's move this to 16 as we are running out of time here.
