### ISSUE TITLE
Calendar invite is resent on chaging of the event

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#11796]
1. userA creates an event and invites userB
2. userB accepts the invite
3. userA notices the timeslot has to change and moves the event by half an hour

Now userB receives another invite e-mail saying that userA invites them to eventX etc.

It should say something like. The eventX which you are attending has been rescheduled to time HH:MM on DD/MM/YYYY or something like that.

There can still be buttons to modify your presense. But it should be made clear this is an existing event.

**Comment by georgehrke** [comment]
This is more complex than it sounds. Both new invitations and updated invitations use the `ITIP` message type `REQUEST`. Plus inside the `IMipPlugin` class we don't have access to a diff of changes, but only to the new calendar data, so we don't even know what changed.

Something for Nextcloud 16.

**Comment by rullzer** [comment]
@georgehrke yes fair enough. Lets discuss together next time if/how we can improve this.

**Comment by MorrisJobke** [comment]
@georgehrke @rullzer 🏓  16 or 17?

**Comment by biva** [comment]
How is it progressing? On Thunderbird, if the organiser changes the dates for an event that I already accepted, then I cannot accept or reject the new dates, and the event is not updated in my calendar. I see only a message saying that "This message contains an event that has already been processed"
![image](https://user-images.githubusercontent.com/9964305/70897504-0800b700-1ff3-11ea-8515-61a308a8ff0a.png)
Is it related to this current issue?

**Comment by onny** [comment]
Wasn't this already fixed with?

- https://github.com/nextcloud/server/pull/35743
- https://github.com/nextcloud/server/pull/36661

**Comment by ChristophWurst** [comment]
Probably :)
