### ISSUE TITLE
https windows webdav issue 

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#11804]
### Steps to reproduce
1. Connect with webdavclient  http linux work
2. Connect with windows client http work
3. Connect with linux https work
4. Connect with windows client https NOT work

### Server configuration

**Operating system**: Debian9

**Web server:** : Apache2

**Database:** Mariadb

**PHP version:** php 7

**Nextcloud version:** 14.0.2

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:**  Microsoft-WebDAV-MiniRedir

**Operating system:** windows 10
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"LYt0YTJRVOLr6jMMDV8n","level":0,"time":"2018-10-12T15:10:39+00:00","remoteAddr":"10.15.1.37","user":"--","app":"webdav","method":"PROPFIND","url":"\/remote.php\/webdav","message":{"Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Message":"No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured","Code":0,"Trace":[{"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"→","args":[{"absoluteUrl":"https:\/\/neolye-share.neolye.com\/remote.php\/webdav","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"autoRequireLogin":true,"__class__":"Sabre\\DAV\\Auth\\Plugin"},"beforeMethod"],[{"absoluteUrl":"https:\/\/neolye-share.neolye.com\/remote.php\/webdav","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"→","args":["beforeMethod",[{"absoluteUrl":"https:\/\/neolye-share.neolye.com\/remote.php\/webdav","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"→","args":[{"absoluteUrl":"https:\/\/neolye-share.neolye.com\/remote.php\/webdav","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"→","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":168,"CustomMessage":"--"},"userAgent":"Microsoft-WebDAV-MiniRedir\/10.0.14393","version":"14.0.2.2"}

</details>

</details>

**Comment by Ekleog** [comment]
@tanguy-opendsi You may want to try the procedure I just linked at https://github.com/nextcloud/server/issues/12793

**Comment by MorrisJobke** [comment]
> @tanguy-opendsi You may want to try the procedure I just linked at https://github.com/nextcloud/server/issues/12793

Moved to https://github.com/nextcloud/documentation/issues/1001

**Comment by skjnldsv** [comment]
What is the status here @tanguy-opendsi ?

**Comment by tanguy-opendsi** [comment]
hi,
I did not check the solution, 
I'll come back soon, i think this procedure should work :
https://github.com/owncloud/documentation/pull/2668#issuecomment-260697742
