### ISSUE TITLE
Canceling big upload leads to error

### ISSUE THREAD

**Issue by NickCloudAT** [nextcloud/server#11812]
### Steps to reproduce
1. Take a big file (over 100MB is what I used and i used .zip .exe and .iso files to test it)
2. Start uploading the file
3. Cancel the upload by clicken the cross

### Expected behaviour
Progress bar should disappear immediately and upload should be canceled

### Actual behaviour
The folder where the chunks are stored while the upload is in progress is getting deleted instantly when I hit cancel, but the progress bar will continue for a few seconds and then spit out an "Internal Server error"

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Did update from 14.0.2, but happened there too

**Where did you install Nextcloud from:** Official nextcloud page

**Signing status:** No errors have been found.

**List of activated apps:** 
  - activity: 2.7.0
  - apporder: 0.5.0
  - calendar: 1.6.2
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - impersonate: 1.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.10.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - registration: 0.4.3
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nickcloud.at",
            "www.nickcloud.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "https:\/\/nickcloud.at\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "versions_retention_obligation": "auto,1",
        "trashbin_retention_obligation": "auto,1"
    }
}

**Are you using external storage, if yes which one:** local storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Tested with Opera, FireFox, Chrome, Edge

**Operating system:** Win10

#### Nextcloud log (data/nextcloud.log)
https://nickcloud.at/nextcloud/index.php/s/Q27TKG7LKwWSsKz

If this is only an issue for me, then please help me to fix it.. It's pretty annoying.

**Comment by TheNickSkater** [comment]
> [GitMate.io](https://gitmate.io) thinks possibly related issues are #11339 (Canceling upload of big file leads to "Internal Server error"), #3450 (Missing error message for too big files in public upload), #4392 (Error while syncing/uploading large files), #9801 (Error downloading or uploading large files), and #9795 (Upgrade error).

Yes related to MY other opened issue that never got looked at.

**Comment by ghtux** [comment]
Still not addressed?

**Comment by hottwister** [comment]
same issue on NC 15.0.4

It's not only for big file, choose file > 10 MB and issue will be reproduce
logs shows my 

Fatal | webdav | Sabre\DAV\Exception: Could not rename part file to final file 
Error | webdav | renaming part file to final file failed $renameOkay: false, $fileExists: false) 
Error | core | unable to rename, source directory is not writable : uploads/web-file-upload-d8cfc7df0a9f130ebabbbad690dfdf5a-1551382272411 
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 6476111 got 3448832 
Error | no app in context | Sabre\DAV\Exception\BadRequest: expected filesize 6476111 got 3448832

**Comment by GuyPaddock** [comment]
I'm seeing the same behavior here.

**Comment by HiFiPhile** [comment]
Same on 16.0.1

Fatal | webdav | Sabre\DAV\Exception: Could not rename part file to final file |   | 2019-05-16T15:44:38+0200
Error | webdav | renaming part file to final file failed $renameOkay: false, $fileExists: false) |   | 2019-05-16T15:44:38+0200
Error | core | unable to rename, source directory is not writable : uploads/web-file-upload-22a9cc9f6cfc9fe4e184ef559c41db1d-1558014276066

**Comment by Serrous** [comment]
Same problem on 17.01. (php 7,3 mysql, 5.3.12-arch1-1)

Fatal | webdav | Sabre\DAV\Exception: Could not rename part file to final file | 
December 01, 2019 20:59:18 Error	webdav	renaming part file to final file failed $renameOkay: false, $fileExists: false)	
December 01, 2019 20:59:18 Error	core	unable to rename, source directory is not writable : uploads/web-file-upload-aadb2f852d0e706095c7788a95d771e3-1575223144679	
December 01, 2019 20:59:18 Fatal	webdav	Sabre\DAV\Exception: Could not rename part file to final file

**Comment by Skip75** [comment]
Same problem on NC18.
No impact, but I keep anyway an eye on that issue.

**Comment by stecklars** [comment]
+1 on NC18 with local data storage.

**Comment by harveytj03** [comment]
Still occurs on NC 19.0.1 on a brand new install using a second hard drive for storage.

**Comment by KLEPTOROTH** [comment]
Still occurring on NC 21.0.3.

**Comment by david-kalbermatten** [comment]
Great...
Still happening on NC 23.0.0. Just out of curiosity, anyone else here running Unraid with the linuxserver docker image for Nextcloud? And if so, did anybody ever figure out a solution to the files being created by Nextcloud having the wrong UMASK?
```log
{"reqId":"TUNTyfy04EkBLYblUUqG","level":3,"time":"2021-12-06T15:23:56+00:00","remoteAddr":"172.17.0.1","user":"david","app":"PHP","method":"DELETE","url":"/remote.php/dav/uploads/david/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025","message":"rmdir(/data/david/uploads/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025): Directory not empty at /config/www/nextcloud/lib/private/Files/Storage/Local.php#128","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"23.0.0.10","exception":{"Exception":"Error","Message":"rmdir(/data/david/uploads/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025): Directory not empty at /config/www/nextcloud/lib/private/Files/Storage/Local.php#128","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/private/Files/Storage/Local.php","line":128,"function":"rmdir"},{"function":"rmdir","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/config/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":193,"function":"call_user_func"},{"file":"/config/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":125,"function":"doDelete","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/config/www/nextcloud/lib/private/Files/View.php","line":1171,"function":"rmdir","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/config/www/nextcloud/lib/private/Files/View.php","line":350,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":309,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":80,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/remote.php","line":166,"args":["/config/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"w2mShmxoKiAwlmm0bPvz","level":3,"time":"2021-12-06T15:23:56+00:00","remoteAddr":"172.17.0.1","user":"david","app":"PHP","method":"DELETE","url":"/remote.php/dav/uploads/david/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025","message":"rmdir(/data/david/uploads/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025): Directory not empty at /config/www/nextcloud/lib/private/Files/Storage/Local.php#128","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"23.0.0.10","exception":{"Exception":"Error","Message":"rmdir(/data/david/uploads/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025): Directory not empty at /config/www/nextcloud/lib/private/Files/Storage/Local.php#128","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/config/www/nextcloud/lib/private/Files/Storage/Local.php","line":128,"function":"rmdir"},{"function":"rmdir","class":"OC\\Files\\Storage\\Local","type":"->"},{"file":"/config/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":193,"function":"call_user_func"},{"file":"/config/www/nextcloud/apps/files_trashbin/lib/Storage.php","line":125,"function":"doDelete","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/config/www/nextcloud/lib/private/Files/View.php","line":1171,"function":"rmdir","class":"OCA\\Files_Trashbin\\Storage","type":"->"},{"file":"/config/www/nextcloud/lib/private/Files/View.php","line":350,"function":"basicOperation","class":"OC\\Files\\View","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":309,"function":"rmdir","class":"OC\\Files\\View","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":80,"function":"delete","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":179,"function":"delete","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":281,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/lib/Server.php","line":339,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/config/www/nextcloud/remote.php","line":166,"args":["/config/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/config/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"}}
{"reqId":"zmbPFbWz3ZOtEfYcnyVF","level":3,"time":"2021-12-06T15:23:56+00:00","remoteAddr":"172.17.0.1","user":"david","app":"core","method":"PUT","url":"/remote.php/dav/uploads/david/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025/1090519040","message":"unable to rename, file does not exists : uploads/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025/1090519040.ocTransferId102104909.part","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"23.0.0.10"}
{"reqId":"zmbPFbWz3ZOtEfYcnyVF","level":3,"time":"2021-12-06T15:23:56+00:00","remoteAddr":"172.17.0.1","user":"david","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/david/web-file-upload-8e74ddcc7ed73ba82d0fba7b795d4113-1638804137025/1090519040","message":"renaming part file to final file failed $renameOkay: false, $fileExists: false)","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36","version":"23.0.0.10"}
```

**Comment by estiawan** [comment]
any fix for this?

**Comment by RapidFire05** [comment]
still seeing this issue although sometimes the prog bar disappears immediately sometimes not. but log does show the error related to unexpected size and not empty directory

**Comment by pengs361** [comment]
amazing～～～，still on 25.0.1

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by simonspa** [comment]
It sure still persists on NC25.0.2:

```
{"reqId":"I1r2nAm6lpYJP0ZHQpH2","level":3,"time":"2023-01-09T13:07:39+01:00","remoteAddr":"2001:638:700:1005::1:30","user":"smn","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/smn/web-file-upload-c909eecd6217832454513baa12083662-1673266054427/10485760","message":"Could not rename part file to final file","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0","version":"25.0.2.3","exception":{"Exception":"Sabre\\DAV\\Exception","Message":"Could not rename part file to final file","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":151,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":45,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["10485760",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1098,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["10485760",null]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":504,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/smn/web-file-upload-c909eecd6217832454513baa12083662-1673266054427/10485760",null,null]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->","args":["method:PUT",[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":360,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":171,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":354,"message":"Could not rename part file to final file","exception":[],"CustomMessage":"Could not rename part file to final file"},"id":"63bc03952e04e"}
{"reqId":"I1r2nAm6lpYJP0ZHQpH2","level":3,"time":"2023-01-09T13:07:39+01:00","remoteAddr":"2001:638:700:1005::1:30","user":"smn","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/smn/web-file-upload-c909eecd6217832454513baa12083662-1673266054427/10485760","message":"renaming part file to final file failed $renameOkay: false, $fileExists: false)","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0","version":"25.0.2.3","data":{"app":"webdav"},"id":"63bc03952e073"}
{"reqId":"I1r2nAm6lpYJP0ZHQpH2","level":3,"time":"2023-01-09T13:07:39+01:00","remoteAddr":"2001:638:700:1005::1:30","user":"smn","app":"core","method":"PUT","url":"/remote.php/dav/uploads/smn/web-file-upload-c909eecd6217832454513baa12083662-1673266054427/10485760","message":"unable to rename, source directory is not writable : uploads/web-file-upload-c909eecd6217832454513baa12083662-1673266054427","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:108.0) Gecko/20100101 Firefox/108.0","version":"25.0.2.3","data":{"app":"core"},"id":"63bc03952e0c4"}
```

**Comment by simonspa** [comment]
Two additional bits:

* ...letting the upload finish works like a charm
* Log messages changed w.r.t to @david-kalbermatten 's example with NC23

**Comment by simonspa** [comment]
I don't think so, reading further up others have the same error stack as me.

**Comment by DigiGoon** [comment]
> Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

Same issue persists on 25.0.3

**Comment by LanDaze** [comment]
Well... Same issue persists on 24.0.10, 25.0.4 and 26.0.0.

**Comment by Serrous** [comment]
5 years have passed... 11 major versions have been released... Some things are eternal)

**Comment by RuudschMaHinda** [comment]
Just observed on 26.0.2

```
{"reqId":"8XPe1qEL39bi3MN2kGLI"
"level":3
"time":"2023-05-31T18:28:04+02:00","remoteAddr":"IPv4-ADDRESS"
"user":"USERNAME"
"app":"webdav"
"method":"PUT"
"url":"/remote.php/dav/uploads/USERNAME/web-file-upload-1d906cbe99ad952b2d70cceceea983ec-1685550471708/1"
"message":"renaming part file to final file failed $renameOkay: false, $fileExists: false)"
"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0"
"version":"26.0.2.1"
"data":{"app":"webdav"}}
```

**Comment by skjnldsv** [comment]
Fixed on 28.
We now cancel any ongoing request and react much faster
