### ISSUE TITLE
Support App - Feedback

### ISSUE THREAD

**Issue by Bubu** [nextcloud/server#11811]
@MorrisJobke 

After upgrading an instance I run to NC 14 the new support app got triggered and I got shown a bunch of notifications and sent some emails that I don't have and maybe should get enterprise support.

I have some suggestions for improving the experience.

**Disclaimer:** this is not an enterprise instance, it's run in my spare time for a volunteer project. We don't have any employees which the email kept talking about. We can neither afford nor, I hope, particularly need enterprise support.

1. While this instance nominally has over 500 registered users, these are all imported from another DB. I just checked and only about 150 users ever signed into the instance, over the last 4 years or so this is running. I have no data, but I'd guess the number of users logged in over the last month is in the lower double digits. Maybe the trigger can be improved? But maybe it's also fine the way it is. That's up to you to decide.

2. Neither the email nor the Notification inside Nextcloud left me with a way out. Meaning some small button/link saying "I'm sure I don't need support at this time" and then telling me to go disable the support app. It just kept repeating the notifications without giving me an obvious way to make it stop :).

3. It would be good to get some idea why this is triggering, and why now. I now learned that it was the combination of having over 500 users and upgrading to NC 14. The email has a footer that says 

> You received this email because you are an admin of the Nextcloud instance at https://example.com

It would go a long way just adding something like "which has over 500 registered users" here. And the same for the page the NC notification links to.

**Comment by MorrisJobke** [comment]
@jospoortvliet This feedback makes sense IMO.

**Comment by jospoortvliet** [comment]
I agree, Morris. Thanks @Bubu 

I don't know how to do 1 but that makes sense. I can probably do a PR for the other points - Id say we add the point recommended under 3 and perhaps also note it comes from the support app:

"You received this email because you are an admin of the Nextcloud instance at https://example.com" to
"This mail was sent by the support app on your Nextcloud instance at https://example.com because you have over 500 registered users"
That also hints that disabling the support app means this goes away... Agreed, Morris?

**Comment by MorrisJobke** [comment]
> That also hints that disabling the support app means this goes away... Agreed, Morris?

Yep.

**Comment by MorrisJobke** [comment]
We improved the app and will ship the updated texts with 14.0.4 and 15.0.0 RC 1.
