### ISSUE TITLE
Update from 14.0.1 to 14.0.3 fails

### ISSUE THREAD

**Issue by bisherbas** [nextcloud/server#11827]
### Steps to reproduce
1. Go to adming settings
2. Click overview
3. Click start updates

### Expected behaviour
Update should succeed

### Actual behaviour
Update fails

![image](https://user-images.githubusercontent.com/42714627/46918881-b2232000-cfa5-11e8-8eca-768fdd7062d7.png)

I deleted the log file but it gets regenerated automatically. And it is always empty. I also deleted the contents of the cache folder but I did not attempt to delete the cache folder itself.

### Server configuration

**Operating system**: Ubuntu 18.02

**Web server:** Apache 2.4.29

**Database:** MySQL 5.7.23

**PHP version:** 7.2.10

**Nextcloud version:** (see Nextcloud admin page) 14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Github clone

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>
Calendar, Notes, Tasks, Talk

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx.com",
            "www.xxx.com",
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/cloud\/",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "https:\/\/xxx.com\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "cache_path": "\/var\/www\/xxx.com\/html\/cloud\/cache",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "log_type": "file",
        "logfile": "nextcloud.log",
        "loglevel": 1,
        "logtimezone": "America\/New_York",
        "logdateformat": "F j, Y, g:i a",
        "log_rotate_size": 10485760,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

```
  There are no commands defined in the "ldap" namespace.
```

</details>

### Client configuration
**Browser:** Firefox 62.0.3

**Operating system:** macOS Mojave

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sun Oct 14 06:25:02.494045 2018] [mpm_prefork:notice] [pid 12046] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.0g configured -- resuming normal operations
[Sun Oct 14 06:25:02.494067 2018] [core:notice] [pid 12046] AH00094: Command line: '/usr/sbin/apache2'
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nextcloud.log file only appears in the root folder of Nextcloud installation and it is a 0B empty file.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> I deleted the log file but it gets regenerated automatically. And it is always empty. I also deleted the contents of the cache folder but I did not attempt to delete the cache folder itself.

Those files should not be there. If the nextcloud.log get's regenerated then it seems that you have configured your data dir to be the same as your nextcloud root directory, which is not supported and not recommended as it could lead to data loss.

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by bisherbas** [comment]
@MorrisJobke That's not true. My data directory is in `/home` while nextcloud root directory is in `/var/www` I don't believe this is a setup issue.

**Comment by MorrisJobke** [comment]
> In addition, how about the 'cache` folder error?

I have seriously no idea how the cache folder and the logs should appear there if not via the nextcloud data directory and also have not seen it yet on any setup out there to happen. 

> "cache_path": "\/var\/www\/xxx.com\/html\/cloud\/cache",

Ah - this one. Please move this to a different location. I just noticed it right now. If you move it does it then not get recreated again?

**Comment by MorrisJobke** [comment]
> "logfile": "nextcloud.log",

And there is the other misconfiguration. Change this to something more useful or remove the setting and then also the log file will be properly placed inside the data directory. 

Changing those two values should lead to the correct behavior and you should be able to upgrade properly.

**Comment by bisherbas** [comment]
Thank you for the suggestions. Problem solved!
