### ISSUE TITLE
"Add Group" button has disappeared

### ISSUE THREAD

**Issue by jammon** [nextcloud/server#11824]
### Steps to reproduce
1. Open https://myserver.tld/settings/users

### Expected behaviour
"Add Group" button should be visible as per the [docs](https://docs.nextcloud.com/server/14/admin_manual/configuration_user/user_configuration.html#managing-groups).

### Actual behaviour
It isn't.

The name of the new group has to be written into the "groups" input box of a user, who is to be added to the new group. There is no obvious hint to this behaviour and the docs say differently.

Nextcloud version 14.0.1, fresh install.

This problem was discussed in the [nextcloud forum](https://help.nextcloud.com/t/nextcloud-14-missing-feature-for-add-group-in-user-managament/36712).

**Comment by JB1985** [comment]
Update to 14.0.3

**Comment by jammon** [comment]
Seems to be a duplicate of #10945 and to be fixed in #11193 for 14.0.2. (I cannot check this, because the updater is not working for me: https://help.nextcloud.com/t/updating-fails-at-extracting-error-during-unpacking-zipfile-no-error/39089

**Comment by MorrisJobke** [comment]
> Seems to be a duplicate of #10945 and to be fixed in #11193 for 14.0.2. (I cannot check this, because the updater is not working for me: https://help.nextcloud.com/t/updating-fails-at-extracting-error-during-unpacking-zipfile-no-error/39089

Correct. Fixed in 14.0.2/3
