### ISSUE TITLE
Nextcloud 14.0.3 dont start after Update postgresql 10

### ISSUE THREAD

**Issue by ml94** [nextcloud/server#11821]
I have make a Update about Webmin and now Nextcloud 14.0.3 dont start. I see only a blank site.
And when I start the Ubuntu-System I get the Error: 
`[FAILED] Failed to start PostgreSQL Cluster 10-main.`
How I can fix this?

**Comment by ChristophWurst** [comment]
>  Failed to start PostgreSQL Cluster 10-main

Sounds like your database is unable to start. Please consult help.nextcloud.com for such issues. Thanks.
