### ISSUE TITLE
New Sidebar not working on IE11

### ISSUE THREAD

**Issue by jacestk** [nextcloud/server#11840]
### Steps to reproduce
1.juste clic on the item ion sidebar (Favorite, Shares,...)
2.nothing happens

### Expected behaviour
List of items should appears.

### Actual behaviour
Got an error in JS Debogger

### Server configuration

**Operating system**:
CENTOS 7
**Web server:**
Apache 2.4
**Database:**
MariaDB 10
**PHP version:**
php 7.1

**Nextcloud version:** (see Nextcloud admin page)
14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
NC 12 > NC 13.0.6 > NC 14.0.3
**Where did you install Nextcloud from:**
Official

#### Browser log
SCRIPT438: L’objet ne gère pas la propriété ou la méthode « abort »
Fichier : sharedfilelist.js, ligne : 176, colonne : 5

		reload: function() {
			this.showMask();
			if (this._reloadCall) {
				this._reloadCall.abort();

**Comment by danxuliu** [comment]
The JavaScript error is not related, even if it seems to be ;-) Also note that it does no longer happen since Nextcloud 14.0.4 (specifically, 9801b5af363aa0cc9f8d947709b04901f7bc0b6e).

The fix for the collapse button in Internet Explorer 11 is in #15384.
