### ISSUE TITLE
Deadlock problem with mariadb:latest (docker)

### ISSUE THREAD

**Issue by Tockra** [nextcloud/server#11841]
Hi,

I used docker to setup my nextcloud service with nginx and fpm: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/fpm
I had a lot of problems there with deadlocks: #11734 .
Now I realized, that the Deadlocks Errors, didn't occur with mariadb:10.0, mariadb:10.1, mariadb:10.2 and mariadb:10.3 .
They just occur with mariadb:latest image.
I don't know which version is included in mariadb:latest but I think it should be a new version.

So there must be a error in the newest mariadb implementation or in the newest nextcloud:fpm implementation or in the newest nextcloud documentation (settings for mariadb) .

I hope I could help somebody with this post. That issue cost me nearly 10 hours.

T

**Comment by ChristophWurst** [comment]
Thank you for the feedback. Yes, there are some issues with the latest mariadb as the `dbal` version used in Nextcloud isn't quite up-to-date. It was bumped for Nextcloud 16 already and will be updated again for Nextcloud 17. In the meantime I would suggest to just use an older version of the db. They should work just fine and in your isolated Docker environment this shouldn't be too hard to do.

**Comment by Tockra** [comment]
Of course, it isn't hard but if nobody tells you it is very hard to find the reason of that problem.
Will there a announcement, when we will can use the latest mariadb version?
 
Even at the moment all examples and tutorials says you should install mariadb:latest (although that can't run correct)

**Comment by ChristophWurst** [comment]
Good point. Could you please file a ticket at https://github.com/nextcloud/documentation/issues?

**Comment by ChristophWurst** [comment]
> Even at the moment all examples and tutorials

Unless they are from the official Nextcloud documentation we can't do much about this. I suggest to report this back to the tutorial publishers!

**Comment by Tockra** [comment]
They are from: https://github.com/nextcloud/docker

I made this:
https://github.com/nextcloud/docker/pull/514


But nobody cares...
