### ISSUE TITLE
Upgrade 14.0.3.0 Failed - Autoload path not allowed

### ISSUE THREAD

**Issue by aramilialon** [nextcloud/server#11854]
### Steps to reproduce
1. Have the zimbra plugin installed
2. Perform an upgrade
3. Voila!

### Expected behaviour
Tell us what should happen

The upgrade should have gone smootly

### Actual behaviour
Tell us what happens instead

The server has broken

### Server configuration

**Operating system**:

Debian 9

**Web server:**

Apache 2.4.25

**Database:**

10.1.26-MariaDB-0+deb9u1 Debian 9.1

**PHP version:**

PHP 7.0.30-0+deb9u1

**Nextcloud version:** (see Nextcloud admin page)

14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Upgraded from a 13.0.x Nextcloud version

**Where did you install Nextcloud from:**

Webpage

**Signing status:**
<details>
<summary>Signing status</summary>

Unable do to that, I still receive the Internal Server error even if I try to get to https://xxx/index.php/settings/integrity/failed

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
An unhandled exception has been thrown:
OCP\AutoloadNotAllowedException: Autoload path not allowed: /var/www/html/nextcloud/apps/zimbradrive/lib/auth/zimbrausersbackend.php in /var/www/html/nextcloud/lib/autoloader.php:137
Stack trace:
#0 /var/www/html/nextcloud/lib/autoloader.php(162): OC\Autoloader->isValidPath('/var/www/html/n...')
#1 [internal function]: OC\Autoloader->load('OCA\\ZimbraDrive...')
#2 [internal function]: spl_autoload_call('OCA\\ZimbraDrive...')
#3 /var/www/html/nextcloud/lib/private/legacy/user.php(138): class_exists('OCA\\ZimbraDrive...')
#4 /var/www/html/nextcloud/lib/base.php(721): OC_User::setupBackends()
#5 /var/www/html/nextcloud/lib/base.php(1068): OC::init()
#6 /var/www/html/nextcloud/console.php(46): require_once('/var/www/html/n...')
#7 /var/www/html/nextcloud/occ(11): require_once('/var/www/html/n...')

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
$CONFIG = array (
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'secret' => 'xxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxx',
  ),
  'datadirectory' => '/opt/nextcloud/data',
  'overwrite.cli.url' => 'xxxx',
  'dbtype' => 'mysql',
  'version' => '14.0.3.0',
  'dbname' => 'nextclouddb',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'logfile' => '/var/log/nextcloud.log',
  'loglevel' => '2',
  'log_rotate_size' => '104857600',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'trusted_proxies' =>
  array (
    0 => '10.0.0.2',
  ),
  'overwritehost' => 'xxxx',
  'overwriteprotocol' => 'https',
  'overwritecondaddr' => '^10\\.0\\.0\\.2$',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'xxxx',
  'mail_smtphost' => 'xxxx',
  'mail_smtpport' => '25',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'nextcloud@ctmconsulting.it',
  'mail_smtppassword' => 'xxxx',
  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend',
      'arguments' =>
      array (
      ),
    ),
  ),
  'updater.secret' => 'xxxx',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

Yes, local in /opt/nextcloud/

**Are you using encryption:** yes/no

Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No, but I had configured to use also a Zimbra LDAP 

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

MariaDB [nextclouddb]> SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
Empty set (0.00 sec)

MariaDB [nextclouddb]>

</details>

### Client configuration
**Browser:**

Firefox 62.0.3

**Operating system:**

Windows 10 Pro

#### Web server error log
<details>
<summary>Web server error log</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"BQnC1gKosIb4iJcJ6p9Q","level":3,"time":"2018-10-15T19:14:55+00:00","remoteAddr":"95.229.249.38","user":"--","app":"index","method":"GET","url":"\/","message":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: \/var\/www\/html\/nextcloud\/apps\/zimbradrive\/lib\/auth\/zimbrausersbackend.php","Code":0,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/autoloader.php","line":162,"function":"isValidPath","class":"OC\\Autoloader","type":"->","args":["\/var\/www\/html\/nextcloud\/apps\/zimbradrive\/lib\/auth\/zimbrausersbackend.php"]},{"function":"load","class":"OC\\Autoloader","type":"->","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"function":"spl_autoload_call","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/legacy\/user.php","line":138,"function":"class_exists","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/html\/nextcloud\/index.php","line":40,"args":["\/var\/www\/html\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/html\/nextcloud\/lib\/autoloader.php","Line":137,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}

{"reqId":"kv8ogsY1lOwH1inKZc6V","level":3,"time":"2018-10-15T19:14:56+00:00","remoteAddr":"95.229.249.38","user":"--","app":"index","method":"GET","url":"\/index.php\/js\/core\/merged-template-prepend.js?v=92e07cb2-0","message":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: \/var\/www\/html\/nextcloud\/apps\/zimbradrive\/lib\/auth\/zimbrausersbackend.php","Code":0,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/autoloader.php","line":162,"function":"isValidPath","class":"OC\\Autoloader","type":"->","args":["\/var\/www\/html\/nextcloud\/apps\/zimbradrive\/lib\/auth\/zimbrausersbackend.php"]},{"function":"load","class":"OC\\Autoloader","type":"->","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"function":"spl_autoload_call","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/legacy\/user.php","line":138,"function":"class_exists","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/html\/nextcloud\/index.php","line":40,"args":["\/var\/www\/html\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/html\/nextcloud\/lib\/autoloader.php","Line":137,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:62.0) Gecko\/20100101 Firefox\/62.0","version":"14.0.3.0"}

{"reqId":"QsljJJfrBYALhYYNKk7s","level":3,"time":"2018-10-15T19:15:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"OCP\\AutoloadNotAllowedException","Message":"Autoload path not allowed: \/var\/www\/html\/nextcloud\/apps\/zimbradrive\/lib\/auth\/zimbrausersbackend.php","Code":0,"Trace":[{"file":"\/var\/www\/html\/nextcloud\/lib\/autoloader.php","line":162,"function":"isValidPath","class":"OC\\Autoloader","type":"->","args":["\/var\/www\/html\/nextcloud\/apps\/zimbradrive\/lib\/auth\/zimbrausersbackend.php"]},{"function":"load","class":"OC\\Autoloader","type":"->","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"function":"spl_autoload_call","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/private\/legacy\/user.php","line":138,"function":"class_exists","args":["OCA\\ZimbraDrive\\Auth\\ZimbraUsersBackend"]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":721,"function":"setupBackends","class":"OC_User","type":"::","args":[]},{"file":"\/var\/www\/html\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/var\/www\/html\/nextcloud\/cron.php","line":41,"args":["\/var\/www\/html\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/var\/www\/html\/nextcloud\/lib\/autoloader.php","Line":137,"CustomMessage":"--"},"userAgent":"--","version":"14.0.3.0"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

Errore interno del server

Il server non è stato in grado di completare la tua richiesta.

Se ciò si verifca nuovamente, invia i seguenti dettagli tecnici all'amministratore del server.

Ulteriori dettagli sono disponibili nel log del server.
Dettagli tecnici

    Indirizzo remoto: xx.xx.xx.xx
    ID richiesta: GmUOFtyFb8imfdAUg2nZ

</details>

**Comment by aramilialon** [comment]
I have managed to gain access again to the nextcloud installation enabling the zimbra plugin via database and, lately, removing it from the installation.
The problem seems that it is incompatible with the version 14, but the disable does break something

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer Any idea how to prevent this? I would love to not kill the server here and properly disable the app during the upgrade.

**Comment by Zimeon-** [comment]
> 
> 
> I have managed to gain access again to the nextcloud installation enabling the zimbra plugin via database and, lately, removing it from the installation.
> The problem seems that it is incompatible with the version 14, but the disable does break something. 

Enabling Zimbra Drive (update oc_appconfig set configvalue="yes" where appid="zimbradrive" and configkey="enabled";) fixed the issue for me as well.

**Comment by ChristophWurst** [comment]
Closing as resolved
