### ISSUE TITLE
External storage - Shared folders from external storage (SMB) "does not exist"

### ISSUE THREAD

**Issue by 11harveyj** [nextcloud/server#11866]
### Steps to reproduce
1. Setup SMB external storage with sharing enabled
2. Share a folder in Nextcloud that is located on the external storage (share via a link)
3. Modify the data contained within the shared folder, but not on Nextcloud (e.g directly in Windows)
4. Attempt to access the shared folder again (from above generated link)

### Expected behaviour
The shared folder should continue to load correctly

### Actual behaviour
Nextcloud errors with "This file does not exist"

### Server configuration

**Operating system**: Univention Corporate Server (Docker image)

**Web server:** Apache

**Database:** MySql

**PHP version:** PHP 5 (unsure of the minor version number)

**Nextcloud version:** (see Nextcloud admin page) 13.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Docker image from UCS Software Center

**Signing status:**
No errors have been found.

**Are you using external storage, if yes which one:** Yes, SMB

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Active Directory

### Client configuration
**Browser:** Google Chrome/Edge/Firefox etc.

**Operating system:** Windows

### Logs

*Log file is too big to attach here*

**Comment by jospoortvliet** [comment]
You will need to enable change notification in Samba - https://docs.nextcloud.com/server/14/admin_manual/configuration_files/external_storage/smb.html?highlight=smb#smb-update-notifications

Also @VikDex Nextcloud has had this for a long, long time... Time to migrate :+1:
