### ISSUE TITLE
Nextcloud 14.0.3 only work with chromium/chrome, not work with IE/firefox

### ISSUE THREAD

**Issue by johnwmail** [nextcloud/server#11867]
Nextcloud version (eg, 12.0.2): 14.0.3
Operating system and version (eg, Ubuntu 17.04): debian/sid/amd64
Apache or nginx version (eg, Apache 2.4.25): nginx 1.14.0-1
PHP version (eg, 7.1): php-fpm 7.3.0~rc3-1

The issue you are facing:
I noticed my home server only work on chromium, when I use firefox/IE to login via web interface,
I can not see the files (https://imgur.com/a/0JPd9Jd 3)

When I use chromium/chrome, everything work fine (https://imgur.com/a/q0ny2nl)

https://help.nextcloud.com/t/nextcloud-14-0-3-only-work-with-chromium-chrome-not-work-with-ie-firefox/39212

**Comment by johnwmail** [comment]
How to debug?
Thanks.

**Comment by Knot3n** [comment]
Are you using some Plugins with IE/Firefox? 

Need logs from Nginx / PHP-FPM / Nextcloud Logs.

**Comment by johnwmail** [comment]
> Are you using some Plugins with IE/Firefox?
No plugins/extensions, I tried rm -rf ~/.mozilla, still have the problem.

> Need logs from Nginx / PHP-FPM / Nextcloud Logs.
Nothing in nextcloud.log (really nothing)

no error in nginx.log,  only normal access log like below
"PROPFIND https://cloud.domain.com/remote.php/webdav/works/%E9%9D%92%E9%A6%AC%E5%A4%A7%E6%A9%8B/old/ HTTP/1.1" 207 44649 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.3.0" 0.065
"PROPFIND https://cloud.domain.com/remote.php/dav/files/tuthk/local HTTP/1.1" 207 384 "-" "Mozilla/5.0 (Windows) mirall/2.3.1 (build 8) (Nextcloud)" 0.075

Any idea, how to enable debug log, or something can collect more informatio?
Thanks.

**Comment by Knot3n** [comment]
Hi,

https://docs.nextcloud.com/server/13/developer_manual/general/debugging.html

For the Debugging.

**Comment by johnwmail** [comment]
Very funny, when I enable debug => true,
Firefox can work normal again, (still nothing in nextcloud.log)

When I remove debug => true,
Or debug => false in config.conf,
Then firefox can not work again.

Very funny, enable debug is workaround in my case 😁

**Comment by Knot3n** [comment]
Hm, thats a workaround but not a fine fix ... dont know if others have that problem with 32bit version.

**Comment by enoch85** [comment]
Firefox works here, so it's probably some user configuration error. Does it work from a clean Firefox installation on another computer with `debug mode` off?

**Comment by johnwmail** [comment]
No, it does not work even with clean Firefox installation on another computer

**Comment by torstenbunde** [comment]
You are not the only one having this problem @johnwmail. A colleague of me updated his installation yesterday from version 13 to 14.0.3. After fixing some minor problems with php modules (updating from 5.6 to 7.0) he also has the problem that logins do not work with Firefox but with Google Chrome.

I will ask him again but as far as I know he is using the actual version 63 of this browser and also doesn't use any plugins.

**Comment by johnwmail** [comment]
Hi, please also ask your colleague, is it enable debug can solve the problem?

**Comment by enoch85** [comment]
> (updating from 5.6 to 7.0)

To me that's rather an issue with the PHP config (i-.e missing modules), but I might be wrong.

**Comment by creopard** [comment]
Since you are using nginx (maybe with http2), have a look at
https://help.nextcloud.com/t/nextcloud-12-wont-load-on-firefox-on-http2/20333/3

**Comment by johnwmail** [comment]
No, I tried remove throw, but No luck

**Comment by johnwmail** [comment]
@enoch85 No, I already tried before, php 7.2 still have the problem

**Comment by torstenbunde** [comment]
> Hi, please also ask your colleague, is it enable debug can solve the problem?
@johnwmail: If he uses `debug => true,` in his config the login with Firefox works! If he sets this option to `false` after that (or is removing it from the config), logs out and tries to log in again the login will also work (even one day later).

**Comment by johnwmail** [comment]
@torstenbunde If I remove or disable debug, Firefox still can login, but cannot see the files anymore.

**Comment by torstenbunde** [comment]
> 
> 
> @torstenbunde If I remove or disable debug, Firefox still can login, but cannot see the files anymore.

@johnwmail My colleague still sees all files.

**Comment by johnwmail** [comment]
After upgrade to 14.4, the problem is gone.
So, I close this bugreport.
Thanks.
