### ISSUE TITLE
Allow symlinks configuration property

### ISSUE THREAD

**Issue by cyberb** [nextcloud/server#11879]
Provide configuration setting for allowing symlinked data directory.

Currently it is hardcoded to false:
https://github.com/nextcloud/server/blob/master/lib/private/Files/Storage/Local.php#L55

### Steps to reproduce
1.  Create a directory on linux ext filesystem: mkdir/test
2. Create a symlink to that directory: ln -s /test /data
3. Use /data

### Expected behaviour
I should be able to enable symlinks in a config, not by changing a php file variable.

### Actual behaviour
Canot use symlinked data dir.

### Server configuration

**Operating system**: Linux Debian (amd64, arm)

**Web server:** nginx

**Database:** postgresql

**PHP version:** 7.1.21

**Nextcloud version:** 14.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** Syncloud

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/b88ab75c3a09c6e275735b0bf14108f8add72e5d/config/config.sample.php#L76-L82

Does not work for you?

**Comment by cyberb** [comment]
Do you mean specify absolute path instead of a link in the config?

Not really, on Syncloud device you can activate different external disks and we do not want to change configs of all the apps on a device (not only Nextcloud) to point to.a new device dir.
To simplify that we use /data symlink (can be anything) and change the link to point to a selected disk dir.
Of cause we need to run post disk activate actions still per app, but I thought not changing data dirs in the app configs will be simpler.

It was working fine before v14, that is kind of another reason.

**Comment by Thaodan** [comment]
Would be a great feature when using systemd ProtectHome=yes because nextcloud thinks files inside of it are symlinks.

**Comment by dredkin** [comment]
I run nextcloud on my small server and after EVERY upgrade I have to manually edit this file. This is just ridiculous.
I need symlinks because my files are located out of nextcloud files folder.
And no, I will not move all my files there because nextcloud is not the only cloud engine I use to backup my files. And every single one cloud client I use works fine with symlinks, only nextcloud somehow just does not want to...
Is this because of security concerns? I don't need it. If I know, what I am doing, I have to have a possibility to do this. That's a FOSS spirit!

**Comment by gituser** [comment]
This PR is also relevant if you're running php-fpm in chroot environment.
Any update devs?

**Comment by kesselb** [comment]
A similar issue https://github.com/nextcloud/server/issues/10904. Probably a workaround for some of you: Create `custom.config.php` next to `config.php` like below.

```
<?php

$datadirectory = realpath('/path/to/symlink');
if ($datadirectory === false) {
    exit('failed to resolve datadirectory symlink');
}

$CONFIG['datadirectory'] = realpath($datadirectory);
```

Nextcloud updater (cli or web) do not read custom configuration files. That's usually not a problem because the configuration is merged. But if you use the above way please make sure to check the datadirectory in `config.php` before using the updater. Probably it's not the right path.

**Comment by skjnldsv** [comment]
@kesselb can you open a pr?

**Comment by kesselb** [comment]
No :) That's something for the config files.

**Comment by skjnldsv** [comment]
So, to develop?

**Comment by kesselb** [comment]
I don't know :) For some reason following symlinks is disabled by default. You might ask team storage about that. 

This issue seems to be a request to make follow symlinks on/off a configuration option.

**Comment by dredkin** [comment]
> 
> 
> @kesselb can you open a pr?

@skjnldsv What info do you need?

If I'd only knew the NC core better I'd male a PR myself.

It's clear as vodka: Now in 
https://github.com/nextcloud/server/blob/6aea539745c5c7b7d80525672be5a90dae4028bb/lib/private/Files/Storage/Local.php#L58

$allowSymliks is hardcoded to False. Instead it SHOULD take value form a configuration file (if it exists there, or false by default. 

I just cannot imagine what other info is required?

**Comment by skjnldsv** [comment]
@dredkin missing info from us ;)

cc @rullzer @nickvergessen @blizzz @MorrisJobke ?

**Comment by blizzz** [comment]
Use bind mounts instead?

**Comment by ferdiga** [comment]
please let  me know another way to extend the storage size.
I was running our of space on the disk where the data is stored and had to "move" one very big directory elsewhere and use a symbolic link to reconnect it

**Comment by masterxq** [comment]
> Use bind mounts instead? [#1257 (comment)](https://github.com/nextcloud/server/issues/1257#issuecomment-345342440)

This is a good and working solution, add to your /etc/fstab something like:
`/var/local/nextcloud/user/files/special_path /mnt/big_data/somepath none defaults,bind 0 0`
Then
`mount /var/local/nextcloud/user/files/special_path`
It will be mounted every boot and persist!

This will work in many cases perfectly.

Best Regards
