### ISSUE TITLE
Update fails with "Error during unpacking zipfile: No error"

### ISSUE THREAD

**Issue by jammon** [nextcloud/server#11876]
### Steps to reproduce
1. Upgrade with the updater from 14.0.1 to 14.0.3

### Expected behaviour
Should upgrade smoothly

### Actual behaviour
Stops upgrade process at “Extracting” with the message “Error during unpacking zipfile: No error”.
![noerror](https://user-images.githubusercontent.com/87003/47044231-e8bc8e80-d18f-11e8-8fa3-7c6ab4dd5558.png)

The updater.log says:
```
2018-10-14T05:07:17+0200 XztBje9bsk [info] request to updater
2018-10-14T05:07:17+0200 XztBje9bsk [info] currentStep()
2018-10-14T05:07:17+0200 XztBje9bsk [info] POST request for step "6"
2018-10-14T05:07:17+0200 XztBje9bsk [info] startStep("6")
2018-10-14T05:07:17+0200 XztBje9bsk [info] extractDownload()
2018-10-14T05:07:17+0200 XztBje9bsk [info] storage location: /media/nextcloud/nc_data/updater-oc568k78b4f2/downloads/
2018-10-14T05:08:42+0200 XztBje9bsk [error] POST request failed with other exception
2018-10-14T05:08:42+0200 XztBje9bsk [error] Exception: Exception
Message: Error during unpacking zipfile: No error
Code:0
Trace:
#0 /var/www/nextcloud/updater/index.php(1320): Updater->extractDownload()
#1 {main}
File:/var/www/nextcloud/updater/index.php
Line:779

2018-10-14T05:08:42+0200 XztBje9bsk [info] rollbackChanges("6")
2018-10-14T05:08:42+0200 XztBje9bsk [info] unlink .step
2018-10-14T05:08:42+0200 XztBje9bsk [info] end of  rollbackChanges()
```

In /var/log/nginx/nextcloud.error.log:

2018/10/14 05:08:42 [error] 8093#8093: *7 FastCGI sent in stderr: "PHP message: PHP Warning:  ZipArchive::extractTo(/media/nextcloud/nc_data/updater-oc568k78b4f2/downloads/nextcloud/apps/support/resources/Why the Nextcloud Subscription?.pdf): failed to open stream: No such file or directory in /var/www/nextcloud/updater/index.php on line 777" while reading response header from upstream, ...

### Problem
The question mark in `updater-XXXX/downloads/nextcloud/apps/support/resources/Why the Nextcloud Subscription?.pdf` seems to be a problem for unzip.

See also [the discussion in the forum](https://help.nextcloud.com/t/updating-fails-at-extracting-error-during-unpacking-zipfile-no-error/39089)

### Server configuration

**Operating system**: Ubuntu 18.04.1 LTS
**Web server:** nginx/1.15.5

**Database:** mysql  Ver 15.1 Distrib 10.3.10-MariaDB, for debian-linux-gnu (aarch64) using readline 5.2

**PHP version:** PHP 7.2.10

**Nextcloud version:** 14.0.1 fresh install

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by nunesgh** [comment]
Same error here. Trying to update from Nextcloud 16.0.7 to 17.0.2.

**Comment by kesselb** [comment]
cc @jospoortvliet @rullzer could you rename the file? Seems to be a issue for some people.

**Comment by skjnldsv** [comment]
cc @blizzz @nickvergessen  too :)

**Comment by nickvergessen** [comment]
@MorrisJobke is back :)

**Comment by MorrisJobke** [comment]
> cc @jospoortvliet @rullzer could you rename the file? Seems to be a issue for some people.

It's now named "Why the Nextcloud Subscription.pdf". It was renamed in 15.0.0 and 14.0.4. So this should be okay now.
