### ISSUE TITLE
[Bug] custom Icons ./img/filetypes , not all be used, but i can also be wrong

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#11888]
NextCloud 14.0.0.3
PHP 7.2
Customtheme, my neXtrealTime with icons..

Yeeeehhaaaayyyyyy It works... !!!!!
=> almost \*bg* :\ 
pictures say more as words

best regards
Blacky

The svg exist, Themename it is set, but the svg-picture is not taken, be i am wrong or should it work ? 
i have found the php file 
.\nextcloud\lib\private\Files\Type\Detection.php  :+1: 
but it is not use from my theme folder out :\
```
element {
    background-image: url("https://www.blackysgate.net/nextcloud/core/img/filetypes/folder-external.svg");
    display: inline;
} 
```
take a look : 

![picture](https://user-images.githubusercontent.com/7925717/47100864-c599e980-d238-11e8-9e8b-79f33193e860.jpg)

but in the folder works... take a look :  

![screen 00003](https://user-images.githubusercontent.com/7925717/47101530-a3a16680-d23a-11e8-94ad-5130fbdfe7de.jpg)

i have found the issue where have tell @juliushaertl this : 
```
php occ maintenance:mimetype:update-js
```
at https://github.com/nextcloud/server/issues/5533

and i have reload the nextcloud-files-app in the browser, ,
my own icons flash up briefly and the blue icons re-attach to it ..!

----
by the way, i have upload the Mimetypes and folders from my KDE/plasma-theme
this could you use also for make it able to use themespack from plasma-folders and plasma-mimetypes ..
[blackysgate.de/files/folder-root/nextcloud/Mimetypes&Places/](http://blackysgate.de/files/folder-root/nextcloud/Mimetypes&Places/)
These icons from my own plasmatheme in svg be most of the mimetypes up to 90% or something,
take a look.

may can you support icons by folder-name ? You named a folder, 
hellokitty and you have a hellokitty.svg in the /img/filetypes/ so : 
../img/filetypes/hellokitty.svg
is this folder created, "hellokitty" and it is not a extended/special folder
and it exist a svg-file with the same name "hellokitty.svg" it is the folder with the icon hellokitty.svg
like in plasma .. if exist hellokitty.svg not, it is use default folder.svg
But it's just a idea/suggestion for nextcloud-folders :smile: 

there be so many different icons for themeing:
https://store.kde.org/browse/cat/132/ord/latest/
i guess Frank agrees with me :smiley: 

best regards
Blacky

**Comment by ml31415** [comment]
I got probably the same error with the latest 15.0.4. I created three themes, only changing the primary color and the color of the folder items. Only one of these themes displays the modified folder icons correctly.

**Comment by skjnldsv** [comment]
Sorry, custom themes are not something we want to support.
This will not receive further development :)
