### ISSUE TITLE
In grid view, file type icons are too big compared to image previews

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11902]
In the new grid view, the filetype icons look unelegantly large compared to the image previews (This is actually also the case in the Android app which uses the same previews & folder icons cc @tobiasKaminsky @AndyScherzinger)
![file type icons too big in comparison to normal pictures](https://user-images.githubusercontent.com/925062/47155584-5deda800-d2e5-11e8-942c-a42cd9b5ea6a.png)

In the list view it’s fine, although it would not be bad for the preview images to be bigger:
![thumbnails in list view are fine](https://user-images.githubusercontent.com/925062/47155581-5d551180-d2e5-11e8-96d8-d0a4c76fe23f.png)

How can we reduce the size of the filetype icons / make the image previews larger? @rullzer @nextcloud/designers

**Comment by juliushaertl** [comment]
Should easily doable just with some CSS:

```
[data-has-preview='false'] .thumbnail {
	background-size:50% !important;
}
```

**Comment by tobiasKaminsky** [comment]
What kind of ratio do you think is good? 50% as Julius set?
I can have a look if this is possible on Android

**Comment by juliushaertl** [comment]
I think 50% is already a bit to small, 75% looks good to me. Also I would actually only apply this to the grid view.

**Comment by jancborchardt** [comment]
Sounds good to me @juliushaertl, thanks for the piece of code! :) I'll play around with the values a bit tomorrow, or do you already want to submit a pull request with 75% and we can discuss there?

**Comment by tobiasKaminsky** [comment]
![2018-10-19-083302](https://user-images.githubusercontent.com/5836855/47201292-a060c480-d379-11e8-9270-561ff50feff8.png) ![2018-10-19-083440](https://user-images.githubusercontent.com/5836855/47201363-d7cf7100-d379-11e8-9cf0-22a2497932d7.png)

I am shameless posting an android screenshot here…
As you can see, I only resized the folder, but not generic mimetypes.
How do you do this on webUI?

**Comment by jancborchardt** [comment]
@tobiasKaminsky nice, already looks much better! It's really visible how the folder icon size looks nicer in comparison to the rest.

- The other filetype icons also need to be smaller
- The text below can be moved up a bit (towards the filetype icon)

(And it's absolutely fine posting the Android screenshots here :) It's an issue we have cross-platform and wr should solve it generally. Actually probably similar for the iOS grid view, cc @marinofaggiana)

**Comment by marinofaggiana** [comment]
... continue here : 

@jancborchardt 


![schermata 2018-10-23 alle 15 42 00](https://user-images.githubusercontent.com/8616947/47364846-8ce78d80-d6da-11e8-8e1f-e692bc22ddd3.png)

![schermata 2018-10-23 alle 15 44 53](https://user-images.githubusercontent.com/8616947/47364875-9e309a00-d6da-11e8-8bea-cb5b19327d2b.png)

Considerations:

- it's difficult (but not impossible) calculate the space of items in grid mode ... too many device ipad/iphone and

**Comment by tobiasKaminsky** [comment]
In general, I am not sure if text/filename in grid view is really useful.
According to all screenshots in this issue (Independent from platform), you can always read only ~5 chars at beginning and a few on the end and this does not help to distinguish:
- on first one multiple "Screen…"
- on android multiple nextcl…apk

Unfortunately I do not have a better idea. 
Maybe putting "…" to the end, as you can see the mimetype through icons, but in case of last iOS image, scan 16/43 would then be trimmed…

**Comment by marinofaggiana** [comment]
New grid with more Width for item, generally 3 item for line ... now the filename has more meaning

@jancborchardt margin left and right now are 5 px (?)

<img width="370" alt="schermata 2018-10-24 alle 08 53 06" src="https://user-images.githubusercontent.com/8616947/47411831-3fb2fc80-d76a-11e8-9a46-a376b01890b4.png">

**Comment by AndyScherzinger** [comment]
I agree with @tobiasKaminsky and also @marinofaggiana. Looking through some file managers on Android supporting grid view they:
* default to either 2 or 3 columns (like in the latest iOS screenshot)
* they either use ellipsizing `end` or `marquee` (while marquee is quite hectic, so I'd vote for `end`)
* I'd leave the filenames out for images ("kind of gallery mode") but leave them in for any other type of file. Having looked at several file managers it becomes apparent that grid isn't working well for files in comparison to list views except for media/image folders.

So for Android I vote for 3 columns, ellipsizing `end`, no filenames for images/videos

**Comment by marinofaggiana** [comment]
> So for Android I vote for 3 columns, ellipsizing end, no filenames for images/videos

I don't like no filename for a specific type of file, asymmetric !?

**Comment by AndyScherzinger** [comment]
> I don't like no filename for a specific type of file, asymmetric !?

I get that, just stating the way how the grid view handles image previews in grid view (no filename)

**Comment by jancborchardt** [comment]
@marinofaggiana some feedback specific to the iOS screenshot you showed:
- The filename text should be center-aligned.
- The filename is a bit too close to the image preview. Needs a bit more distance / line height.
- The filetype icons should be a bit smaller. Size of the image previews is good though! :)
- There should be no white margin on the left and right between image previews and the edge of the screen.
- The 3-dot-menu should be on the right of the filename, on the same row. right-aligned.

Ok? :)

**Comment by marinofaggiana** [comment]
@jancborchardt : 

<img width="425" alt="schermata 2018-11-05 alle 11 15 22" src="https://user-images.githubusercontent.com/8616947/47992343-ee512880-e0ec-11e8-8ed4-9626f5033904.png">

**Comment by marinofaggiana** [comment]
@jancborchardt the issue of menu is that are too many option for the order (look) : 

![simulator screen shot - iphone xs max - 2018-11-05 at 11 22 39](https://user-images.githubusercontent.com/8616947/47992442-32442d80-e0ed-11e8-8673-9872a75252bc.png)

Then 3 menu : 

![simulator screen shot - iphone xs max - 2018-11-05 at 11 17 09](https://user-images.githubusercontent.com/8616947/47992459-3ff9b300-e0ed-11e8-8c8a-87cf9d870227.png)

**Comment by skjnldsv** [comment]
@jancborchardt what is this issue about? I'm confused by all the android iOS stuff here?

**Comment by marinofaggiana** [comment]
@skjnldsv sorry !! mea culpa !! I have add here my question grid for iOS.

**Comment by tobiasKaminsky** [comment]
No need to apologize for, Marino. Jan encouraged us to post here also screenshots from Android/iOS as this is a cross-platform problem.

**Comment by skjnldsv** [comment]
@marinofaggiana No worries! I was just confused abou tthe topic of this issue!! :hugs: :wink: 
It's perfectly fine, thanks for the explanation @tobiasKaminsky :hugs:

**Comment by MorrisJobke** [comment]
@jancborchardt What is the status of this? I guess we need to move this to 17 🙈

**Comment by skjnldsv** [comment]
![image](https://github.com/nextcloud/server/assets/14975046/ffbfc9ff-9a38-455f-bb43-f687650aa0e7)
Fixed 28. Much more elegant now

**Comment by tobiasKaminsky** [comment]
I cannot spot any difference? :innocent: 
@jancborchardt as this is also interesting for Android, how small shall e.g. the folder icon be?

**Comment by jancborchardt** [comment]
Might also be the general spacing that makes it look much better. Nice :)

@tobiasKaminsky I just checked Android and the sizing of the icons compared to the previews seems fine to me.
