### ISSUE TITLE
File renaming should not vanish the filetype icon / preview

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#11901]
Currently the filetype icon / preview is hidden when you rename a file. This is not really necessary, and it’s even bad because you lose the context of what the file is.

![rename list view](https://user-images.githubusercontent.com/925062/47155408-efa8e580-d2e4-11e8-918b-2829d68b1c44.png)
------------------------

When renaming:
![rename thumbnail vanishes](https://user-images.githubusercontent.com/925062/47155406-efa8e580-d2e4-11e8-9f59-8e9d28bd4568.png)

This is especially a problem in the upcoming grid view. @nextcloud/javascript could someone help?

**Comment by MorrisJobke** [comment]
Fix is in #12467
