### ISSUE TITLE
See only group contacts for sharing

### ISSUE THREAD

**Issue by bepolymathe** [nextcloud/server#11912]
Hi. Thank you for your efforts to improve Nextcloud! 
However, something bothers me and could be improved (this is a suggestion). With the new DGPS regulations in Europe, this would solve confidentiality issues. 

### Steps to reproduce
1. Share file
2. Click on the search field
3. See all users of instance appear

### Expected behaviour

Have the possibility to display in the contact list (for sharing) only users of the same group (not of the entire server instance). 

### Actual behaviour

We see everyone, which is not very confidential.

**Comment by MorrisJobke** [comment]
> Have the possibility to display in the contact list (for sharing) only users of the same group (not of the entire server instance).

There is a sharing setting. Go to Settings > Admin > Sharing: "Only allow sharing with group members". Then the Nextcloud instance behaves like you described it.
