### ISSUE TITLE
Downloads from the server gets fully throttled on Linux browser

### ISSUE THREAD

**Issue by fwsGonzo** [nextcloud/server#11910]
When I download a big file (1GB+) on Linux it always gets throttled to 100kb/s almost exactly, after a few minutes. Not having the same problem on a Windows machine, on the same network, downloading from the same private cloud.
Server is v14.0.1

My solution so far has been to move the files into its own folder and then syncing that folder with the client (on Linux). I briefly tried to test with wget, but i dont know how to make it authenticate.
Ideas for things to try are welcome.

**Comment by js94x** [comment]
You have to pass both credentials and WebDAV-URL to wget. Instead of wget you also can use curl as described here:
https://docs.nextcloud.com/server/14/user_manual/files/access_webdav.html#accessing-files-using-curl

```curl -u user:pass -o /tmp/testfile_with1GB.txt "https://example.com/nextcloud/remote.php/dav/files/USERNAME/testfile_with1GB.txt"```
