### ISSUE TITLE
Users layout

### ISSUE THREAD

**Issue by XjeEDK** [nextcloud/server#11923]
### Steps to reproduce
1. Go to the users section
2. Resize group column or see at least a mouse over

### Expected behaviour
We have long group names. I would like to be able to resize the group column.
Or at least to see the full name when I mouse over.

### Actual behaviour
I see only the first ~18 characters followed by ...

### Server configuration

**Operating system**:CentOS

**Web server:** NginX

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Comment by jancborchardt** [comment]
@XjeEDK could you provide a screenshot (with all other info censored)?

So a tooltip on hover of the groups would be fine. Resizing the columns is overengineering here. cc @juliushaertl @skjnldsv what do you think?

**Comment by XjeEDK** [comment]
![image](https://user-images.githubusercontent.com/23097645/47279969-57587c80-d5d4-11e8-8d6a-61d213e5d298.png)

I also can't see from which domain the group is.
