### ISSUE TITLE
Not setting order for app with getNavigationManager sorts it in first position

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1192]
In the appinfo/app.php, if an app doesn’t specifically set the order via `\OC::$server->getNavigationManager()->add(` then the app is sorted before all the other apps, even Files.

To prevent this, any app without a specifically set order should have its order set to 100.

cc @LukasReschke because your app does this. ;)

**Comment by LukasReschke** [comment]
As noted at https://github.com/LukasReschke/githubmergetracker/pull/2/files#r76785088 the order parameter seems broken as it spams the log.

**Comment by rullzer** [comment]
PR with fix #1235
