### ISSUE TITLE
LDAP edit query

### ISSUE THREAD

**Issue by XjeEDK** [nextcloud/server#11924]
### Steps to reproduce
1. Go to the LDAP / AD integration under settings
2. Select an existing LDAP connection
3. Go to groups and edit LDAP query

### Expected behaviour
If I don't change anything I should still be able to use the drop down fields.

### Actual behaviour
Dropdown fields are locked.

### Server configuration

**Operating system**:CentOS

**Web server:** NginX

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** 13.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Comment by blizzz** [comment]
It's either using the assisted operation mode using the drop downs OR editing it manually. Click again on the label to switch the mode. It might not be obvious, indeed.
