### ISSUE TITLE
Auditing user login

### ISSUE THREAD

**Issue by squalo80** [nextcloud/server#11936]
After update to 14.0.3 the user login do not appear on the LOG
### Steps to reproduce
1. Log in with a USER
2. If login failed OK the log containt the error
3. If login is OK THERE ISN'T a row on the log

### Expected behaviour
Have a log of correct login

### Actual behaviour
Right now only the wrong login

### Server configuration

**Operating system**: Ubuntu Linux 16.04.2

**Web server:** Apache version 2.4.18 

**Database:**  SQLite

**PHP version:** actually not known

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated  from 13.0.6

**Where did you install Nextcloud from:** Webupdate

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_downloadactivity: 1.3.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - theming_customcss: 1.1.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - files_external
  - groupfolders
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "fs.tecnowerk.it"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/fs.tecnowerk.it",
        "dbtype": "sqlite3",
        "version": "14.0.3.0",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 1,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25"
    }

</details>

**Are you using external storage, if yes which one:** NO

**Are you using encryption:**no

**Are you using an external user-backend, if yes which one:** NO

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

 There are no commands defined in the "ldap" namespace.

</details>

### Client configuration
**Browser:**  Firefox 62.0.3

**Operating system:** Windows 7 64bit SP1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by squalo80** [comment]
Seems that aren't related. this issue only happend after update to 14.0.3

**Comment by violoncelloch** [comment]
this is probably just because of a change of the loglevel
can you change the loglevel to something lower and report if this solved it for you?

**Comment by blizzz** [comment]
audit logs go to audit.log by default on 14. Location can be changed via occ, cf. `https://github.com/nextcloud/server/pull/9293#issue-183851353`.

**Comment by squalo80** [comment]
> 
> 
> audit logs go to audit.log by default on 14. Location can be changed via occ, cf. `https://github.com/nextcloud/server/pull/9293#issue-183851353`.

Thanks a lot! Found it.
I will close.
