### ISSUE TITLE
Onlyoffice not working after update to 14.0.3

### ISSUE THREAD

**Issue by dmitrydrynov** [nextcloud/server#11938]
Onlyoffice not working after update to 14.0.3 (in old version 14.0.1 was ok)

Error
"Error when trying to connect (Error occurred in the document service: Error while downloading the document file to be converted.)"

Config file same as before.
Nginx same as before.
Onlyoffice server config same as before.

**Comment by violoncelloch** [comment]
this is probably more related to the onlyoffice app or onlyoffice itself or it's a misconfiguration. (have you tried if accessing directly the domain under wich onlyoffice runs with your browser works? Otherwise could you report it at https://github.com/onlyoffice/onlyoffice-nextcloud ?

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
