### ISSUE TITLE
Expire date allows any value

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#11930]
As admin one can set "Expire after xxx days" to any value, even strings.
This then kills android capability sync.

![image](https://user-images.githubusercontent.com/5836855/47212584-ee38f500-d398-11e8-81a9-3050c96aa640.png)

**Comment by euku** [comment]
@rullzer Apart from the missing validation there is maybe another issue. I never entered a string there by hand - at least I can't remember and why should I type "admin"... Are there other background processes that can rewrite this value? I know this must have happened with NC 13.0.6.
BTW, you also can't create a new share if this value is invalid.

**Comment by tobiasKaminsky** [comment]
@euku do you use an password auto fill in system? Like keepass, onepass, etc?
Maybe the "day" input field was wrongly recognized as "username" and auto filled? 
(at least this would explain the word "admin")

**Comment by tobiasKaminsky** [comment]
@euku do you use any password auto fill in? This would explain "admin" if the tool is wrongly assuming that the input field is for username?

**Comment by euku** [comment]
@tobiasKaminsky: I use 1Password and was able to trigger this filling in general. But not for the "admin" user, i.e. I can fill it with some of other usernames, but it doesn't work for the "admin" entry.

**Comment by rullzer** [comment]
Should be better with #12125
