### ISSUE TITLE
Hash character (#) in file name via. SFTP

### ISSUE THREAD

**Issue by m0se** [nextcloud/server#1193]
This Issue also exists in nextcloud:
https://github.com/owncloud/core/issues/21301

When syncing a folder from external SFTP storage, files with a hash character in the name cause the sync to fail. 
Unfortunately this causes the sync to stop completely and only files up to the problematic file will be synced,.. the files after that will only be synced when the respective file is deleted or renamed.

**Comment by skjnldsv** [comment]
Fixed already with recents phpseclib updates
