### ISSUE TITLE
LDAP/LDAPS not working with AD after upgrade from 13.02 to 14.03 and again after 14.03 to 14.04

### ISSUE THREAD

**Issue by Der-Marc** [nextcloud/server#11948]
### Steps to reproduce
1. Cannot log in with AD user after upgrade, nothing changed at the AD (windows server 2016). AD user still valid. Checked connection with LDAP browser. Attached is the relevant part of the log:
[nextcloud.log](https://github.com/nextcloud/server/files/2497818/nextcloud.log)

Any ideas what has changed? Kind regards
Marc

#### LDAP configuration (delete this part if not used)

| hasMemberOfFilterSupport      | 1                                                                                                                          |
| hasPagedResultSupport         |                                                                                                                            |
| homeFolderNamingRule          |                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                          |
| ldapAgentName                 | CN=***,CN=Managed Service Accounts,DC=home,DC=intern                                                              |
| ldapAgentPassword             | ***                                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                                            |
| ldapAttributesForUserSearch   |                                                                                                                            |
| ldapBackupHost                |                                                                                                                            |
| ldapBackupPort                |                                                                                                                            |
| ldapBase                      | DC=home,DC=intern                                                                                                          |
| ldapBaseGroups                | DC=home, DC=intern                                                                                                         |
| ldapBaseUsers                 | DC=home, DC=intern                                                                                                         |
| ldapCacheTTL                  | 600                                                                                                                        |
| ldapConfigurationActive       | 1                                                                                                                          |
| ldapDefaultPPolicyDN          |                                                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                                                            |
| ldapEmailAttribute            |                                                                                                                            |
| ldapExperiencedAdmin          | 0                                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                                                            |
| ldapExpertUsernameAttr        |                                                                                                                            |
| ldapGidNumber                 | gidNumber                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                         |
| ldapGroupFilter               |                                                                                                                            |
| ldapGroupFilterGroups         |                                                                                                                            |
| ldapGroupFilterMode           | 0                                                                                                                          |
| ldapGroupFilterObjectclass    |                                                                                                                            |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                               |
| ldapHost                      | ldaps://192.168.145.10                                                                                                     |
| ldapIgnoreNamingRules         |                                                                                                                            |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=OCuser,CN=Users,DC=home,DC=intern)(primaryGroupID=1618))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                            |
| ldapLoginFilterEmail          | 0                                                                                                                          |
| ldapLoginFilterMode           | 0                                                                                                                          |
| ldapLoginFilterUsername       | 1                                                                                                                          |
| ldapNestedGroups              | 0                                                                                                                          |
| ldapOverrideMainServer        |                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                        |
| ldapPort                      | 636                                                                                                                        |
| ldapQuotaAttribute            |                                                                                                                            |
| ldapQuotaDefault              |                                                                                                                            |
| ldapTLS                       | 0                                                                                                                          |
| ldapUserAvatarRule            | default                                                                                                                    |
| ldapUserDisplayName           | displayname                                                                                                                |
| ldapUserDisplayName2          |                                                                                                                            |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=OCuser,CN=Users,DC=home,DC=intern)(primaryGroupID=1618))))                         |
| ldapUserFilterGroups          | OCuser                                                                                                                     |
| ldapUserFilterMode            | 0                                                                                                                          |
| ldapUserFilterObjectclass     | user                                                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                                       |
| turnOffCertCheck              | 1                                                                                                                          |
| turnOnPasswordChange          | 0                                                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------+

```

**Comment by Der-Marc** [comment]
Got it to work again with 14.03 by deleting the old configuration, disabling the plugin, enabling it again, using the same configuration information.
After upgrading to 14.04 LDAP is again broken. This time with the warning

Warning | user_ldap | Configuration Error (prefix s01): login filter does not contain %uid place holder. | 
Warning | user_ldap | Configuration Error (prefix s01): No LDAP Login Filter given!

Trick from above does not work. Any hints?

Kind regards
Marc

**Comment by blizzz** [comment]
First log reports that the connection to the LDAP server failed.

Second output is a about a wrong login filter, this is typically logged on setup (when it is not set yet indeed).

Sounds to me rather that there are networking issues around the upgrade.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
