### ISSUE TITLE
The video player playing mp4 files above 2G will result in the inability to drag the progress bar.

### ISSUE THREAD

**Issue by Baozisoftware** [nextcloud/server#11951]
### Steps to reproduce
1.have a > 2GB size mp4 file (h234+aac)
2.Play and click the progress bar to the end
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. Oe {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}'

### Expected behaviour
seekto and play video

### Actual behaviour
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. Oe {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}

### Server configuration

**Operating system**:openwrt for armv7(kernel 4.14.75)

**Web server:** nginx 1.15.5

**Database:** MariaDB 10.2.17

**PHP version:** 7.2.10 32bit

**Nextcloud version:** nextcloud-14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** official website download

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_markdown: 2.0.4
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 1.3.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - music: 0.9.2
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - unsplash: 1.1.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:** Chrome 70

**Operating system:** Windows 10 

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
fseek() expects parameter 2 to be integer, string given at /xxx/3rdparty/sabre/dav/lib/DAV/CorePlugin.php#181
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
VIDEOJS: ERROR: (CODE:3 MEDIA_ERR_DECODE) The media playback was aborted due to a corruption problem or because the media used features your browser did not support. Oe {code: 3, message: "The media playback was aborted due to a corruption…media used features your browser did not support."}
```
</details>

I think the problem should be in php's **fseek** function, but currently you can't use a 64-bit platform, so you need to find another solution.

**Comment by violoncelloch** [comment]
please report this one in the videplayer-repository (https://github.com/nextcloud/files_videoplayer)

**Comment by Baozisoftware** [comment]
That repo already has the same:
https://github.com/nextcloud/files_videoplayer/issues/39
https://github.com/nextcloud/files_videoplayer/issues/55
It doesn't seem to be a plugin issue.

**Comment by skjnldsv** [comment]
We now have the viewer
Closing
