### ISSUE TITLE
Nextcloud can't be installed: Invalid SSL Certifiacte

### ISSUE THREAD

**Issue by c0ldn3y** [nextcloud/server#11955]
### Steps to reproduce
1. download.nextcloud.com/server/installer/setup-nextcloud.php

### Expected behaviour
File can be downloaded (download starts) 
### Actual behaviour
file can't be downloaded because the SSL Certificate expired

**Comment by Kugeleis** [comment]
seems to be repetition of #10349

**Comment by violoncelloch** [comment]
A new (Let's Encrypt) certificate is valid since 12:53:33, so this was probably just a temporary issue. 
Could you tell when exactly you tried to access the download server? @c0ldn3y 
If this is recurring every three months (as @Kugeleis stated) maybe something could be changed in the server config of the download-server? (Let's Encrypt cronjob?) cc @nextcloud/infrastructure

**Comment by c0ldn3y** [comment]
I tried access the download server at 08:55 UTC after it failed i havn't checked it for a while and at least at 13:00 UTC it worked again

**Comment by MorrisJobke** [comment]
> A new (Let's Encrypt) certificate is valid since 12:53:33, so this was probably just a temporary issue.
> Could you tell when exactly you tried to access the download server? @c0ldn3y
> If this is recurring every three months (as @Kugeleis stated) maybe something could be changed in the server config of the download-server? (Let's Encrypt cronjob?) cc @nextcloud/infrastructure

Weird - the let's encrypt auto renewal should happen already 30 days before the cert expires. Let's have a look why it doesn't do it's job.

**Comment by Kugeleis** [comment]
I tried to start the update minutes before I posted [my comment](https://github.com/nextcloud/server/issues/11955#issuecomment-431654671) on the issue.

**Comment by uusijani** [comment]
I made a note about the failure in my kanban (yesterday) at "13:17:10 GMT+0300 (EEST)", so that would have been 10:17:10 UTC.

**Comment by d3v3l15h** [comment]
SSL certificate expired, again. Update impossible today 19/01/2018.
Could be great to automate your Letsencrypt certificate renewal, no ?

**Comment by MorrisJobke** [comment]
> Could be great to automate your Letsencrypt certificate renewal, no ?

It actually is, but sometimes gets into a state where the cron job finishes fine, but it doesn't reload the web server correctly. We are about to migrate to another server anyways and will completely re-setup that server and hopefully resolve that issue.

**Comment by d3v3l15h** [comment]
Understood, Thanks for the quick resolution yesterday.
