### ISSUE TITLE
docs: Install on Ubuntu: snap vs apt. Please give an advice

### ISSUE THREAD

**Issue by guettli** [nextcloud/server#11971]
According to the docs there are two ways to install nextcloud:

https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html#example-installation-on-ubuntu-16-04-lts-server

It would be very nice if you could guide the average newcomer.

Which version is preferred? Apt or snap?

Please add a line to the docs.

Thank you.

(Usability is "don't make me think")

**Comment by violoncelloch** [comment]
in general, there is no "preferred" way, it's just that apt is more like the manual way with configuring everything vs. snap brings an "all-in-one package" with more things preconfigured.
maybe we could add something to the documentation? cc @nextcloud/documentation

**Comment by MariusBluem** [comment]
It is really depending on your personal use-case. I will have a look into making this more clear and maybe describe the differences.

**Comment by guettli** [comment]
If there is not way to say "if unsure do X" then it would be very nice to guide new comers and support them to make this decision.

**Comment by szaimen** [comment]
Hi @MariusBluem any update here? :)
