### ISSUE TITLE
TypeError: Return value of OC\Http\Client\Response::getHeader() must be of the type string, null returned

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#11999]
It appears that [OC\Http\Client\Response](https://github.com/nextcloud/server/blob/master/lib/private/Http/Client/Response.php#L73) sometimes returns `null`, when it's expected it shouldn't. This happens in the bookmarks app e.g. when adding a bookmark. This is because guzzle6 [returns an empty array](http://docs.guzzlephp.org/en/stable/psr7.html#headers) in case the requested header doesn't exist.

**Comment by rullzer** [comment]
I would suggest to check this and if that is the case to just return the empty string.

**Comment by marcelklehr** [comment]
Thanks :)
