### ISSUE TITLE
Upload of files with comma does not work (TypeError: xml is undefined)

### ISSUE THREAD

**Issue by sedrubal** [nextcloud/server#12002]
### Steps to reproduce
1. on local machine: `touch 'foo,bar'`
2. Upload the file via the web interface (drag and drop or by via the file dialog)

### Expected behaviour
The file should be uploaded as every other file.

### Actual behaviour
After uploading the file, it does not appear in the web interface and the progress bar stops and does not disappear. Instead you can see this error message in the browser console (on Chromium):

```
merged-index.js?v=4e579112-8:1366 Uncaught TypeError: Cannot read property 'message' of undefined
    at HTMLInputElement.fail (merged-index.js?v=4e579112-8:1366)
    at e.(/cloud/apps/files/anonymous function).(anonymous function)._trigger (https://xxx/cloud/core/vendor/core.js?v=4e579112-8:13:10075)
    at e.(/cloud/apps/files/anonymous function).(anonymous function)._onFail (https://xxx/cloud/js/files/merged-index.js?v=4e579112-8:2764:18)
    at e.(/cloud/apps/files/anonymous function).(anonymous function)._onFail (https://xxx/cloud/core/vendor/core.js?v=4e579112-8:13:5077)
    at Object.<anonymous> (merged-index.js?v=4e579112-8:2798)
    at j (core.js?v=4e579112-8:2)
    at Object.fireWith [as rejectWith] (core.js?v=4e579112-8:2)
    at x (core.js?v=4e579112-8:4)
    at XMLHttpRequest.<anonymous> (core.js?v=4e579112-8:4)
```

### Server configuration

**Operating system**: CentOS Linux release 7.5.1804

**Web server:** nginx & ???

**Database:** 10.3.10-MariaDB

**PHP version:** PHP 7.2.11

**Nextcloud version:** (see Nextcloud admin page) 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 1 times upgraded from 14.0.?

**Where did you install Nextcloud from:** WebInstaller

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - sharebymail
  - support
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/xxx\/cloud",
        "htaccess.RewriteBase": "\/cloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": true,
        "trusted_domains": [
            "xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 62.0.3 / Chromium 69.0.3497.100

**Operating system:** Fedora 29 (also happens with other browsers on Windows)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
-
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
-
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
querying Whats New data was successful: nocontent merged-template-prepend.js:4480:4
undefined merged-template-prepend.js:4481:4
GET https://xxx/cloud/svg/core/actions/add/000?v=1 [HTTP/2.0 200 OK 84ms]
GET https://xxx/cloud/apps/theming/img/core/filetypes/folder.svg?v=8 [HTTP/2.0 200 OK 61ms]
GET https://xxx/cloud/svg/core/actions/upload/000?v=1 [HTTP/2.0 200 OK 60ms]
GET https://xxx/cloud/apps/theming/img/core/filetypes/text.svg?v=8 [HTTP/2.0 200 OK 82ms]
GET https://xxx/cloud/svg/core/actions/close/000?v=1 [HTTP/2.0 200 OK 79ms]
TypeError: xml is undefined
(see above)
```
</details>

**Comment by violoncelloch** [comment]
@sedrubal have you tried uploading such a file via sync client?

**Comment by sedrubal** [comment]
Now I tried and as soon as I create a file containing a comma, the file won't be synchronized and I see the error message:

> ... Server replied: Method Not Allowed

I also tried to create a file using the <kbd>+</kbd> Button and "New text file" and it does not work neither (but I can't see any errors in the javascript console).

Maybe I messed something up during installation. Do you have an idea what the "Method" is, that is not allowed?

I tested it with an other nextcloud instance and there everything is working.

**Comment by violoncelloch** [comment]
Could you try if the logs tell more with activated debug mode (in config.php)? Please also check the nextcloud log.

**Comment by sedrubal** [comment]
The nextcloud log remains empty even on log level 0.

I found out, that the browser tries to make a `PUT` request to the following URL and receives a `405 Method not allowed`:

```
https://xxx/cloud/remote.php/dav/files/username/foo%2Cbar.txt
```

I assume there is an issue with the webserver config (which I can't edit, because it is hosted on a shared host).

But however nextcloud should show a meaningful error message and not fail silently with messages in the browser console, that don't tell you anything about the problem...

**Comment by H4ndl3** [comment]
This error seems not to be limited to files with a comma in their name. I'm having the same issue with multiple files that - regardless of their names - trigger the same error. I can't upload them anywhere within my Nextcloud instance. With other files the upload process works as expected.

Syncing with the Nextcloud client also doesn't work. It just states `Error transferring <file> - server replied:` and that's it, no reply is given.

These are the log entries from when I tried to upload one of the files via the web interface:
> {"reqId":"WpObf0axp4fab5oApVXb","level":0,"time":"09.12.2018 16:17:30","remoteAddr":"172.18.0.2","user":"User1","app":"no app in context","method":"MKCOL","url":"\/remote.php\/dav\/uploads\/User1\/web-file-upload-ee1f22289c1116eab155c1f1ca03c910-1544372250013","message":"No cache entry found for \/User1\/uploads\/web-file-upload-ee1f22289c1116eab155c1f1ca03c910-1544372250013 (storage: home::User1, internalPath: uploads\/web-file-upload-ee1f22289c1116eab155c1f1ca03c910-1544372250013)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.4.2"}
{"reqId":"WpObf0axp4fab5oApVXb","level":0,"time":"09.12.2018 16:17:30","remoteAddr":"172.18.0.2","user":"User1","app":"no app in context","method":"MKCOL","url":"\/remote.php\/dav\/uploads\/User1\/web-file-upload-ee1f22289c1116eab155c1f1ca03c910-1544372250013","message":"No cache entry found for \/User1\/uploads\/web-file-upload-ee1f22289c1116eab155c1f1ca03c910-1544372250013 (storage: home::User1, internalPath: uploads\/web-file-upload-ee1f22289c1116eab155c1f1ca03c910-1544372250013)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.4.2"}

Other than multiple other `no app in context [...] No cache entry found for [...]` entries the log doesn't show any errors. The entries keep appearing however.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
