### ISSUE TITLE
Add to favorites not working in IE11 - polyfill needed

### ISSUE THREAD

**Issue by Req** [nextcloud/server#12007]
### Steps to reproduce 1
1. Open Nextcloud in IE11, log in
2. Open file details pane (on the right hand side)
3. Click the star icon

### Steps to reproduce 2
1. Open Nextcloud in IE11, log in
2. Click the three dots in a file entry
3. Click add to favorites

### Expected behaviour
File is added to favorites

### Actual behaviour
File not added to favorites, developer console shows error that object does not support startsWith (merged-index.js 8270,3)

### Server configuration
Ubuntu 18, Apache2, PostgreSQL, PHP 7

**Nextcloud version: 14.0.1** 
Fresh install

**Where did you install Nextcloud from: downloaded from website**

http://example.com/index.php/settings/integrity/failed : No errors have been found

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - openassharepoint: 0.1.2
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "256.256.256.256",
            "foo.example.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "http:\/\/1.1.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "fi",
        "updater.release.channel": "production",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** Files are on local disk
**Are you using encryption:** no

### Client configuration
**Browser:** IE 11.354.17134.0

**Operating system:** Windows 10

#### Web server error log
clear

#### Nextcloud log (data/nextcloud.log)
clear

#### Browser log
Console: object does not support startsWith (merged-index.js 8270,3)
You know the error that I mean - I only have a picture of the error and it's in finnish but you know the one. You'll just need a polyfill.

**Comment by Req** [comment]
Workaround: Add the following polyfill to core/js/js.js: 
`if (!String.prototype.startsWith) { String.prototype.startsWith = function(searchString, position) { position = position || 0; return this.indexOf(searchString, position) === position; }; }`

**Comment by violoncelloch** [comment]
would you like to create a pull request for this?

**Comment by Req** [comment]
Woah now, that thing I posted was just a workaround, definitely not a fix! I have no idea what that core/js/js.js is and if it actually solves all instances of this bug. I'd guess that there is a more official way to do this. Sure it might be that my workaround works accidentally but that doesn't seem like a very methodical way of approaching, surely there is some logic to what javascript goes in to what file and how are they processed, is there not? 

I would have to examine the source very carefully to create a maintainable and elegant solution to actually create a PR that I would be confident in supporting. If the authors agree, go for it, but I stress again that that file was a random guess that happened to work.

**Comment by violoncelloch** [comment]
@Req you are very welcome to create to create a more proper fix for this
