### ISSUE TITLE
User management on 14.0.3

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#12008]
### Steps to reproduce
1. Fresh install of nextcloud 14.0.3

### Expected behaviour
I expect to have the user managment on the admin side

### Actual behaviour
I don't have the user management on admin.

![Validation](https://i.imgur.com/g0Rw2jG.png)

### Server configuration

**Operating system**:
CentOS 7
**Web server:**
apache 2.4.6
**Database:**
MariaDB
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/latest.tar.bz2

**Comment by violoncelloch** [comment]
User management is as always not under settings but directly under users which you find in the menu on klick of your profile avatar at the top right.
