### ISSUE TITLE
(NC14 is broken) Can't update with GUI or manually

### ISSUE THREAD

**Issue by Ammar7347** [nextcloud/server#12014]
I updated from Nextcloud 13 to 14 4 days ago. I tried updating via GUI as usual but I get an error and then maintenance mode stays active. I tried updating via CLI and same problem. Please see screenshots for further clarification. Any help regarding this would be highly appreciated.

![image](https://user-images.githubusercontent.com/19525838/47431986-0b086a80-d795-11e8-9453-c89c08027856.png)

![1540040527](https://user-images.githubusercontent.com/19525838/47432111-473bcb00-d795-11e8-91cf-492c41b0889f.gif)

I'm using Debian 8 and php7.

Regards,
Ammar

**Comment by violoncelloch** [comment]
Could you provide error logs? (As the issue tenplate requests)

**Comment by Ammar7347** [comment]
[nextcloud.log](https://github.com/nextcloud/server/files/2512053/nextcloud.log)

**Comment by danielkesselberg** [comment]
Could you post `ls -al /var/www/nextcloud/apps` (if this is your app directory). I guess we had some similiar reports here:

https://github.com/nextcloud/server/issues/10954
https://github.com/nextcloud/server/issues/11199
https://github.com/nextcloud/server/issues/11166
https://github.com/nextcloud/server/issues/11155

**Comment by Ammar7347** [comment]
> total 448
drwxr-xr-x 112 www-data www-data 4096 Oct 19 21:43 .
drwxr-xr-x  15 www-data www-data 4096 Oct 19 21:43 ..
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 accessibility
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 activity
drwxr-xr-x   5 www-data www-data 4096 Oct 19 21:43 admin_audit
drwxr-xr-x   5 www-data www-data 4096 May 25 11:52 admin_notifications
drwxr-xr-x   9 www-data www-data 4096 May 25 11:57 announcementcenter
drwxr-xr-x  10 www-data www-data 4096 Aug  5 07:31 apporder
drwxr-xr-x  10 www-data www-data 4096 Sep 29 23:26 audioplayer
drwxr-xr-x  11 www-data www-data 4096 Sep 11 10:21 bookmarks
drwxr-xr-x   8 www-data www-data 4096 Oct 19 21:41 bookmarks_fulltextsearch
drwxr-xr-x  10 www-data www-data 4096 Jul  4 15:05 bruteforcesettings
drwxr-xr-x  10 www-data www-data 4096 May 25 11:54 calendar
drwxr-xr-x   8 www-data www-data 4096 Oct 19 21:41 camerarawpreviews
drwxr-xr-x  12 www-data www-data 4096 Sep 11 10:21 circles
drwxr-xr-x   4 www-data www-data 4096 Oct 19 21:43 cloud_federation_api
drwxr-xr-x  12 www-data www-data 4096 May 25 12:08 cms_pico
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 comments
drwxr-xr-x  13 www-data www-data 4096 Aug 20 16:43 dashboard
drwxr-xr-x   9 www-data www-data 4096 Jul  4 15:03 data_request
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 dav
drwxr-xr-x  11 www-data www-data 4096 Aug  5 07:31 deck
drwxr-xr-x   8 www-data www-data 4096 Sep 11 10:21 dicomviewer
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:41 drop_account
drwxr-xr-x   8 www-data www-data 4096 May 25 11:47 dropit
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 encryption
drwxr-xr-x   8 www-data www-data 4096 May 25 11:48 end_to_end_encryption
drwxr-xr-x   9 www-data www-data 4096 Aug 20 16:43 external
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 federatedfilesharing
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 federation
drwxr-xr-x  11 www-data www-data 4096 Oct 19 21:43 files
drwxr-xr-x   9 www-data www-data 4096 Sep 29 23:26 files_antivirus
drwxr-xr-x   6 www-data www-data 4096 May 25 11:47 files_downloadactivity
drwxr-xr-x  11 www-data www-data 4096 Oct 19 21:43 files_external
drwxr-xr-x   7 www-data www-data 4096 Jul  4 15:05 files_external_gdrive
drwxr-xr-x   6 www-data www-data 4096 Aug 20 16:42 files_frommail
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:41 files_fulltextsearch
drwxr-xr-x   7 www-data www-data 4096 Oct 19 21:41 files_fulltextsearch_tesserac                                                                                                                                                             t
drwxr-xr-x   6 www-data www-data 4096 May 25 11:54 files_markdown
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 files_pdfviewer
drwxr-xr-x  10 www-data www-data 4096 May 25 11:50 files_reader
drwxr-xr-x   9 www-data www-data 4096 May 25 12:08 files_retention
drwxr-xr-x   7 www-data www-data 4096 May 25 11:48 files_rightclick
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 files_sharing
drwxr-xr-x   8 www-data www-data 4096 Oct 19 21:43 files_texteditor
drwxr-xr-x   6 www-data www-data 4096 May 25 11:47 files_trackdownloads
drwxr-xr-x  11 www-data www-data 4096 Oct 19 21:43 files_trashbin
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 files_versions
drwxr-xr-x   7 www-data www-data 4096 Oct 19 21:43 files_videoplayer
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 firstrunwizard
drwxr-xr-x   9 www-data www-data 4096 Sep 20 11:32 flowupload
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:41 fulltextsearch
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:41 fulltextsearch_elasticsearch
drwxr-xr-x  12 www-data www-data 4096 Oct 19 21:43 gallery
drwxr-xr-x  10 www-data www-data 4096 May 25 12:07 impersonate
drwxr-xr-x   8 www-data www-data 4096 May 25 12:04 limit_login_to_ip
drwxr-xr-x  12 www-data www-data 4096 Oct 19 21:43 logreader
drwxr-xr-x   5 www-data www-data 4096 Oct 19 21:43 lookup_server_connector
drwxr-xr-x   5 www-data www-data 4096 May 25 11:46 lsd
drwxr-xr-x  11 www-data www-data 4096 Aug  5 07:31 mail
drwxr-xr-x   9 www-data www-data 4096 Aug 20 16:43 metadata
drwxr-xr-x   9 www-data www-data 4096 May 25 11:54 mindmaps
drwxr-xr-x   9 www-data www-data 4096 Aug 20 16:43 mood
drwxr-xr-x  22 www-data www-data 4096 Sep 20 11:32 music
drwxr-xr-x   8 www-data www-data 4096 Oct 19 21:43 nextcloud_announcements
drwxr-xr-x  11 www-data www-data 4096 Sep 20 11:32 notes
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 notifications
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 oauth2
drwxr-xr-x  11 www-data www-data 4096 May 25 12:07 ocdownloader
drwxr-xr-x   9 www-data www-data 4096 Sep 11 10:22 ojsxc
drwxr-xr-x  13 www-data www-data 4096 Sep 11 10:22 onlyoffice
drwxr-xr-x  11 www-data www-data 4096 Aug 20 16:43 ownbackup
drwxr-xr-x  11 www-data www-data 4096 Aug 20 16:43 ownpad
drwxr-xr-x  13 www-data www-data 4096 May 25 12:07 passman
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 password_policy
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:41 passwords
drwxr-xr-x  10 www-data www-data 4096 Sep 11 10:22 polls
drwxr-xr-x   6 www-data www-data 4096 Oct 19 21:43 provisioning_api
drwxr-xr-x   8 www-data www-data 4096 Aug 20 16:43 qownnotesapi
drwxr-xr-x  13 www-data www-data 4096 Sep 11 10:22 quicknotes
drwxr-xr-x   9 www-data www-data 4096 May 25 11:50 quota_warning
drwxr-xr-x  11 www-data www-data 4096 May 25 11:53 radio
drwxr-xr-x  10 www-data www-data 4096 May 25 12:06 rainloop
drwxr-xr-x  10 www-data www-data 4096 Sep 11 10:22 ransomware_protection
drwxr-xr-x  14 www-data www-data 4096 Oct 19 21:41 registration
drwxr-xr-x  11 www-data www-data 4096 Sep 29 23:26 sensorlogger
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 serverinfo
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 sharebymail
drwxr-xr-x   8 www-data www-data 4096 Sep 11 10:22 socialsharing_diaspora
drwxr-xr-x   8 www-data www-data 4096 Sep 11 10:22 socialsharing_email
drwxr-xr-x   8 www-data www-data 4096 Sep 11 10:22 socialsharing_facebook
drwxr-xr-x   8 www-data www-data 4096 Sep 11 10:22 socialsharing_googleplus
drwxr-xr-x   7 www-data www-data 4096 Sep 11 10:22 socialsharing_twitter
drwxr-xr-x   9 www-data www-data 4096 Sep 20 11:33 spreed
drwxr-xr-x  18 www-data www-data 4096 May 25 12:08 spreedme
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 support
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 survey_client
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 systemtags
drwxr-xr-x   9 www-data www-data 4096 Sep 11 10:22 tasks
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 theming
drwxr-xr-x   9 www-data www-data 4096 Oct 19 21:43 twofactor_backupcodes
drwxr-xr-x  10 www-data www-data 4096 Sep 29 23:26 twofactor_rcdevsopenotp
drwxr-xr-x  10 www-data www-data 4096 May 25 12:04 twofactor_totp
drwxr-xr-x  10 www-data www-data 4096 May 25 12:05 twofactor_u2f
drwxr-xr-x  10 www-data www-data 4096 May 25 12:05 twofactor_yubikey
drwxr-xr-x   5 www-data www-data 4096 May 25 11:46 unsplash
drwxr-xr-x  10 www-data www-data 4096 Oct 19 21:43 updatenotification
drwxr-xr-x   5 www-data www-data 4096 Oct 19 21:43 user_external
drwxr-xr-x  12 www-data www-data 4096 Oct 19 21:43 user_ldap
drwxr-xr-x   4 www-data www-data 4096 May 25 11:52 user_usage_report
drwxr-xr-x   9 www-data www-data 4096 Sep 11 10:23 w2g2
drwxr-xr-x   8 www-data www-data 4096 Oct 19 21:43 workflowengine

**Comment by Ammar7347** [comment]
> Disable `bookmarks` and `files_external_gdrive` and try again

Urmm how do I disable these plugins? Thanks for the prompt replies :)

**Comment by violoncelloch** [comment]
With the occ command (see https://docs.nextcloud.com/server/14/admin_manual/configuration_server/occ_command.html#apps-commands)

**Comment by anolting** [comment]
[nextcloud_1.zip](https://github.com/nextcloud/server/files/2512368/nextcloud_1.zip)

**Comment by MorrisJobke** [comment]
> Urmm how do I disable these plugins? Thanks for the prompt replies :)

Either via the occ command (but during upgrade this is most likely not available) or directly in the DB table oc_appconfig. Set the entries with the configkey `enabled` of those apps from `yes` to `no`.

**Comment by MorrisJobke** [comment]
Then the upgrade should continue. Those apps are not yet compatible with 14.

cc @nickvergessen how to deal with this in the future? :/

**Comment by Ammar7347** [comment]
The problem has been resolved by disabling those plugins. Thank you all for the help :)

**Comment by violoncelloch** [comment]
> Then the upgrade should continue. Those apps are not yet compatible with 14.
> 
> cc @nickvergessen how to deal with this in the future? :/

@MorrisJobke Shouldn't Nextcloud just deactivate incompatible apps automatically before upgrading?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Shouldn't Nextcloud just deactivate incompatible apps automatically before upgrading?

It should but those apps just bring in another layer of incompatibility that is not really traceable to them (the exception comes from our code and not their because they overwrite one of our dependencies with an older version of it and our code then fails)
