### ISSUE TITLE
Evaluate dropping php7.0 support

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#12021]
According to https://secure.php.net/supported-versions.php, php7.0 EOL's soon. We should evaluate when to increase the minimum supported version.

- [x] Todo: check major distros and what they currently ship
  * Debian: not yet but in 2019 (with buster: https://tracker.debian.org/pkg/php7.2)
  * Ubuntu: in 18.04
  * RHEL: with software collections https://www.softwarecollections.org/en/scls/rhscl/rh-php71/
  * SLES: SLES 15: https://build.opensuse.org/package/show/Apache:Modules/php7

cc @blizzz @daita @danxuliu @georgehrke @icewind1991 @juliushaertl @MorrisJobke @nickvergessen @rullzer @schiessle @skjnldsv

**Comment by rullzer** [comment]
Ubuntu 18.04 is php7.2 if I'm not mistaken

**Comment by georgehrke** [comment]
Debian Stretch is 7.0: https://packages.debian.org/stretch/php

**Comment by rullzer** [comment]
Debian will ship 7.2 in Buster: https://tracker.debian.org/pkg/php7.2
Which is scheduled for 2019

**Comment by rullzer** [comment]
RHEL has a software collections for php7.1: https://www.softwarecollections.org/en/scls/rhscl/rh-php71/

**Comment by rullzer** [comment]
SLES15 seems to have 7.2: https://build.opensuse.org/package/show/Apache:Modules/php7

**Comment by icewind1991** [comment]
besides it getting eol, are there any 7.1 features that people are waiting to make us of?

**Comment by rullzer** [comment]
More and more of our dependencies are dropping 7.0 support. So not upgrading blocks us from updating those.

**Comment by icewind1991** [comment]
fair enough

**Comment by danopz** [comment]
> besides it getting eol, are there any 7.1 features that people are waiting to make us of?

Nullable and void return types e.g.

**Comment by tflidd** [comment]
It's probably a good idea to be able to run the current Nextcloud version on a current Debian setup. Debian buster comes out in spring 2019. So until end of 2019 (to give some time for migration), it would be great to have php7.0 support so NC can be used with debian stretch.

The current support cycle for a Nextcloud version seems to be around 1 year. So for NC 15 it would be great to still have php 7.0 support.

From the survey tool, do you get any feedback which php versions are used?

**Comment by rullzer** [comment]
15 will support php7, 7.1 and 7.2
This is about future NC versions

**Comment by MorrisJobke** [comment]
Current stats:

Version|Precentage
-- | --
PHP 5.4 | >1 %
PHP 5.5 | >1 %
PHP 5.6 | 8 %
PHP 7.0 | 48 %
PHP 7.1 | 15 %
PHP 7.2 | 29 %

**Comment by blizzz** [comment]
If Debian abandons 7.0 in 2019 only (when exactly?), we should perhaps keep it supported into 2020.

**Comment by georgehrke** [comment]
> If Debian abandons 7.0 in 2019 only (when exactly?), we should perhaps keep it supported into 2020.

But as @rullzer said, Nextcloud 15 is definitely gonna support PHP 7.0.
Given the currently planned release date and our "2 releases + 12 weeks" rule, EOL is gonna be sometime in 2020.

**Comment by blizzz** [comment]
True… well, depends how much pressure we want to put on those admins.  As, I guess Debian, will support this for a long time on that release. They have their full freeze planned for March, which is still far away from a release. This it depends on our future release plannings, but maybe it is reasonable to keep the support until Debian releases.

**Comment by rullzer** [comment]
IF we decide to still support php7.0 after it is EOL I do vote for adding a notification to the admin settings. Because if there are significant security issues with it php won't fix them anymore

**Comment by MorrisJobke** [comment]
> IF we decide to still support php7.0 after it is EOL I do vote for adding a notification to the admin settings. Because if there are significant security issues with it php won't fix them anymore

I'm totally fine with adding a warning to all releases right now to get awareness to the admins.

**Comment by rullzer** [comment]
> I'm totally fine with adding a warning to all releases right now to get awareness to the admins.

Actually not a bad idea. As even users on 13 on php7.0 end of december will run defacto EOL software

**Comment by ChristophWurst** [comment]
How do we proceed for 16?

**Comment by ChristophWurst** [comment]
Just ran into an issue: Mariadb 10.2 (which is used on many Docker images and other installations) is not fully supported by `doctrine/dbal` v2.5 (which we currently use). v2.6 and later (:warning: actually v2.8 is the oldest maintained version) require php7.1 though.

Found at https://github.com/ChristophWurst/twofactor_admin/issues/20#issuecomment-443743465.

**Comment by MorrisJobke** [comment]
Current stats:

Version|Precentage (Change to end of October)
-- | --
PHP 5.4 | >1 %
PHP 5.5 | >1 %
PHP 5.6 | 6 % (-2)
PHP 7.0 | 43 % (-5)
PHP 7.1 | 14 % (-1)
PHP 7.2 | 35 % (+6)
PHP 7.3 | 2 % (+2)

**Comment by rullzer** [comment]
https://github.com/nextcloud/server/pull/13122

NC16 will be >=PHP7.1

**Comment by MorrisJobke** [comment]
Added to #12915

**Comment by TP75** [comment]
Thank you all for the good work and the assessment.  However, just as a note on:
- [comment 25 Oct '18](https://github.com/nextcloud/server/issues/12021#issuecomment-433208552)
- [comment 2 Jan '19](https://github.com/nextcloud/server/issues/12021#issuecomment-450931683)


@MorrisJobke :
Please be aware in both your _current stats_ PHP tables the comparicon of _Percentage_ should be "**<** 1%" for certain values and not "> 1%" as stated.  The meaning should be "lower 1%" if you check the numbers and according sums appropriately.
This may be a minor slip but is a matter of correctness and could get importance while coding.

**Comment by e-alfred** [comment]
@MorrisJobke Are those stats publicly available somwhere?

**Comment by MorrisJobke** [comment]
> @MorrisJobke Are those stats publicly available somwhere?

Nope.
