### ISSUE TITLE
Ability to switch to the old app menu

### ISSUE THREAD

**Issue by benclark06** [nextcloud/server#12023]
It would be nice to have the ability to switch between the current app switcher, with all the icons on the top (nextcloud 12) and the old one (with all the apps in a menu you open) depending on your personal preference.

**Comment by MorrisJobke** [comment]
> It would be nice to have the ability to switch between the current app switcher, with all the icons on the top (nextcloud 12) and the old one (with all the apps in a menu you open) depending on your personal preference.

I don't think that we will maintain two different menus.

cc @nextcloud/designers for further statements on this.

**Comment by jancborchardt** [comment]
Yeah, as @MorrisJobke said we will not maintain two different menus. We did move to the current one for several reasons:
- People didn’t get that Nextcloud was more than Files
- It took too long to switch apps
- It’s no use putting the title of the current app in the header

If you are unhappy with that, there’s most likely a way to adjust it via CSS for your personal installation. An option in the server for this won’t happen as it would have to be maintained by us, and as we have a better design in the first place.
