### ISSUE TITLE
The icon of new comment in the share is missing

### ISSUE THREAD

**Issue by plyaskin** [nextcloud/server#12027]
Hi,
Could you add the icon of new comments in the shares? 
Also the icon is missing anywhere at the recipient if the folder was shared.
1. Add a recipient to the shares
2. To comment from the sender. The sender is have, the recipient is not.
![image](https://user-images.githubusercontent.com/9464550/47483297-1fb33400-d863-11e8-8d75-aafb78f1849c.png)

**Comment by skjnldsv** [comment]
@plyaskin Hey!
I'm not sure I get what you mean, the icon is shown when we have an unread comment, you want to add it all the time, having unread comment or not?

**Comment by rullzer** [comment]
@skjnldsv I could reproduce this (at least on master).

1. `userA` shares a folder to `userB`
2. `userA` adds a comment
3. `userB` refreses sees no comment
4. `userB` adds a comment
5. `userA` refresesh sees no comment

I could get it to show once. But in general it is not visible properly.

**Comment by skjnldsv** [comment]
@rullzer grid view?

**Comment by rullzer** [comment]
List view

**Comment by skjnldsv** [comment]
1. Create a folder as `User0`: ID is `198`
2. Add comment as `User0`
3. Share folder to `User1`
4. As `User1` check files: see folder. ID is `198`

## On load
User0 `getNumberOfUnreadCommentsForFolder` request the node ID `2`
User1 `getNumberOfUnreadCommentsForFolder` request the node ID `191`
🤔 First issue, we don't request the same ID

## On the filecache database
The folder id is properly defined to `198`, we also have a parent column which is set to `2`

The `getNumberOfUnreadCommentsForFolder` join the comment table [on the parent id ](https://github.com/nextcloud/server/blob/bc35bf14f08f6b91065377d4741762ccfba63814/lib/private/Comments/Manager.php#L599)(wtf is this?)

**Comment by skjnldsv** [comment]
More input, I get it now, we get all the unread comments of the content of the parent directory. Make sense.
Then this is the issue. The parent directory of the User1 is not the same as User0, therefore we cannot get the unread count! @rullzer
