### ISSUE TITLE
Support principal property search for calendar-user-address-set

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#12033]
RFC 6638 requires CalDAV servers to allow principal property search based on a principals calendar-user-address-set: 
https://tools.ietf.org/html/rfc6638#section-2.4.1

**Comment by MorrisJobke** [comment]
@georgehrke Let's move this to 16, okay?

**Comment by georgehrke** [comment]
Yes, let's wait till 15 is out. In case of doubt we can still back port it if necessary.

**Comment by MorrisJobke** [comment]
Moved to 17
