### ISSUE TITLE
Long loading user list page

### ISSUE THREAD

**Issue by HattabbI4** [nextcloud/server#12035]
Hi all! 
I have a problem with the long loading of the user list page.
I have about 2k users.

When you open the users page, the browser tab freezes for 15-20 minutes. At the same time, there is a high use of CPU time by the mysqld service.

Can I make a limited number of entries on the page or rework the output algorithm?

### Server configuration

**Operating system**: Debian 9

**Web server:** nginx/1.12.1

**Database:** mariadb

**PHP version:** PHP 7.2.9 (fpm-fcgi) (built: Sep  7 2018 20:37:33)

**Nextcloud version:** 14.0.0

**Where did you install Nextcloud from:** docker

**Comment by violoncelloch** [comment]
Normally the users list should be lazy loading

Of course PRs with optimizations are always welcome

**Comment by jospoortvliet** [comment]
Sorry, github is NOT for support - please use https://portal.nextcloud.com for that.
