### ISSUE TITLE
Grid default after upgrade

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12031]
I noticed that grid view is default after upgrade, which might scare some people ;-)

Looking at Android and what we discussed there:
- on default we have list view
- we remember if a folder is set to grid/list view and this will be used for any subfolder, unless overridden manually again

If you really want to have grid view as default, maybe because it is common on desktop file browser, maybe consider this:
- auto switch from list to grid or vice vera on a threshold (e.g. >90% of files are media files), this then should be in conjunction with "remember state"
- show a little introduction on first login after upgrade:
	- nothing too fancy, but just 
	- text that grid is now default
	- pointing toggle at top right to directly show the user how to switch back
	- (or: "do you want to have grid view as default?" with yes / no)

**Comment by tobiasKaminsky** [comment]
@nextcloud/designers

**Comment by tobiasKaminsky** [comment]
Hehe. For me this not about individual preferences, but about having a smooth transition from NC14 to 15 wrt grid view.

So you do not expect any complaining/surprised user by this big visual change?

**Comment by skjnldsv** [comment]
@tobiasKaminsky surprise is ok if they like it, I expect positive surprise and not bad feedback ;)

**Comment by MorrisJobke** [comment]
> @tobiasKaminsky surprise is ok if they like it, I expect positive surprise and not bad feedback ;)

I would still go for the list view as of now. The switch was always there with the gallery and we got very little complains so far that it is not the default. Let's not change too much.

At least that is my opinion.

**Comment by skjnldsv** [comment]
@MorrisJobke I'm completely fine with both to be honest :)
I'll let you folks decide on this :)

**Comment by tobiasKaminsky** [comment]
I am not against grid at all, it is really cool.
My concern is only that it is default without showing/explaining the user how to go back.
So any notification/popup showing this, would be a good way in my opinion.

(but I am not that used to web users…)
One could also say that there will be an announcement for NC15, but I think not all will read it…

**Comment by karlitschek** [comment]
I think we can make it default IF it is fully polished. Is there a screenshot somewhere?

**Comment by skjnldsv** [comment]
> I think we can make it default IF it is fully polished. Is there a screenshot somewhere?

@karlitschek :)
![capture d ecran_2018-10-28_20-40-50](https://user-images.githubusercontent.com/14975046/47621022-dcbac000-daf1-11e8-9ece-ffa4c13b2666.png)
![47367655-6a587300-d6e0-11e8-9ed0-637af6d051fc](https://user-images.githubusercontent.com/14975046/47621021-dcbac000-daf1-11e8-9c67-20e729e52ddf.png)

**Comment by karlitschek** [comment]
nice 👍

**Comment by jancborchardt** [comment]
I would close this then. The view is very polished, and because of our clean interface the toggle to change the view is quite visible.

And as such, thresholds for changing the view are also not really necessary anymore as they would only be needed when the default is _list_ and you then view an image-only folder.

(Hope that’s ok and the reasoning is good @tobiasKaminsky? We can still work out the details of course.)

**Comment by pixelipo** [comment]
I expect a flurry of bug reports the moment we deploy this, but that is to be expected since it's in human nature to fear anything new (at first).

I'm a bit worried about low-memory installations (such as RPi) - will it kill those servers (rendering thumbnails) the moment they open up a grid view with hundreds of JPG files? From my experience with the Gallery app, it was almost impossible to use on such a system, because it didn't show image title while thumbnail was loading.

I'm really sorry for not having tested the new Grid view (looks great on screenshots, though!), is that handled in a good way?

**Comment by jancborchardt** [comment]
@pixelipo good question about the Raspberry Pi setups. Do you know anything about that @skjnldsv @rullzer @jospoortvliet others?

> I expect a flurry of bug reports the moment we deploy this, but that is to be expected since it's in human nature to fear anything new (at first).

And yep – the usual. :) And people who like stuff never open an issue. :cry:

**Comment by skjnldsv** [comment]
@pixelipo this is not highh-res, but it might be good to create either a cron task or a generation-on-upload for later yes :)

**Comment by tobiasKaminsky** [comment]
@jancborchardt as this was only a discussion, I am fine with closing it.

Maybe you want to think about remembering the preferred view for each folder?
On Android I really like this, as there are quite some folders (e.g. AutoUpload), where I want to have grid in it and all subfolders, and then e.g. Documents, where I never want to have it.

**Comment by jancborchardt** [comment]
> Maybe you want to think about remembering the preferred view for each folder?

@tobiasKaminsky yup, that’s definitely a good improvement! Guess it needs some more changes, so more something for 16. Could you open an issue for that? :)

**Comment by jancborchardt** [comment]
Reopening as we had some discussions (cc @karlitschek) and feedback – grid view is not polished enough for default yet. @skjnldsv @MorrisJobke I don’t know how to change the default, could you adjust it?

**Comment by skjnldsv** [comment]
@jancborchardt could you explain what is missing? :)

**Comment by jospoortvliet** [comment]
@skjnldsv look in our sales folders for example - most of those files would be indistinguishable because the long file names won't be visible and the thumbnails don't differentiate them. We need to figure out how to change that before we can make this default.

**Comment by MorrisJobke** [comment]
> I don’t know how to change the default, could you adjust it?

You did that ;) It's basically assigning a class to the DOM element of the app ;)

**Comment by MorrisJobke** [comment]
Will need to go into the RC 1 then, because beta 2 is out.

**Comment by skjnldsv** [comment]
Not exactly, just toggle the getUserValue and i'll be fine
I'll push a fix
