### ISSUE TITLE
Get rid of index.php/core/js/oc.js 

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#1204]
We should either get rid of index.php/core/js/oc.js or should serve it in a way that it's not reloaded on every request. Probably we could just move all the data to a `data` element in the templates and read it from a static JS file.

**Comment by LukasReschke** [comment]
Should be another 150ms saved per request.

**Comment by rullzer** [comment]
Did you profile what takes so long? I'm guessing most is RTT right?

**Comment by rullzer** [comment]
Done with https://github.com/nextcloud/server/pull/1917
