### ISSUE TITLE
Public uploads functionality

### ISSUE THREAD

**Issue by Manuel5cc** [nextcloud/server#1205]
When using a public upload folder (shared with "allow editing" and "Hide file listing" selected) some features are missing. Most important: progress bar and error notification. No progress bar might be ok as you can monitorize your connection to see if upload is going on, but without error messages, you can't know if there is an error with the upload: maybe the file is too big for the allowed size, maybe there is no left space on the server...
## Steps to reproduce
1. Share a folder publicly and allow editing
2. Upload a file
## Expected behaviour

Should show upload progress and/or error messages
## Actual behaviour

It doesn't
## Server configuration

Ubuntu 14.04
Apache 
MySQL
Php 7.0.10
Full server specs in [https://aws.amazon.com/marketplace/pp/B007IN7GJA](url)
Nextcloud 10

**Comment by umgfoin** [comment]
Notification for uploads in such kind of public folders seems to be broken, too.
I neither get an email nor a stream-entry if somebody uploads to an publicly shared folder. 
++umgfoin.

**Comment by dirkpape** [comment]
also drag and drop file upload onto a publicly shared folder does not work in my case (10.0.1).
Although it works in an authenticated user's folder.

**Comment by MorrisJobke** [comment]
I split this one up:

* error message: #4211 
* upload progress: #4164
