### ISSUE TITLE
Grid view: File previews in other views still low-res (Recent, Favorites, Shared)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#12057]
Compare "All Files":
![filepreviews-normal](https://user-images.githubusercontent.com/925062/47534030-2dde7000-d8b6-11e8-8115-105dfcdbcde3.png)

And another view like "Favorites" (same in Recent and Shared):
![filepreviews in other view are blurry](https://user-images.githubusercontent.com/925062/47534029-2dde7000-d8b6-11e8-9df8-991b8ff69937.png)

cc @nextcloud/designers @nextcloud/javascript

**Comment by rullzer** [comment]
All done for 16 as far as I can tell.
