### ISSUE TITLE
Unable to Change Page while Uploading

### ISSUE THREAD

**Issue by DrEVILish** [nextcloud/server#12055]
While uploading to Nextcloud using the WebUI, if you navigate away from the current page you started the upload on. It cancels the current upload task.

This isn't expected behaviour, there should be an upload queue that should appear in the top right-hand corner of the webpage if you navigate away from the current page and continues the upload process.

On Dropbox, while navigating the current folder structure I am able to edit and move files around while a background upload process takes place. It places an info bar at the bottom of the screen that keeps me updated with the current progress of my upload.

**Comment by DrEVILish** [comment]
Not related issues.

**Comment by skjnldsv** [comment]
Supporting browsing away to other apps is out of scope.
Nonetheless we want to add a warning to avoid breaking an ongoing upload.

**Comment by violoncelloch** [comment]
Indeed, a warning should be presentet to the user to prevent breaking uploads
I also just remarked that clicking on "Recent", "Favorites" or "Shares" doesn't break the upload, but the upload bar disappears. If you click on "All files", the upload bar appears again, but this is quite confusing too.

**Comment by MorrisJobke** [comment]
Yes - changing directories already works fine, but going into a different section is still not properly working (UX wise).

**Comment by skjnldsv** [comment]
Fixed by #12271

**Comment by DrEVILish** [comment]
I accept the fix :D Thanks, guys!!
