### ISSUE TITLE
Share links to an already-shared gallery give error

### ISSUE THREAD

**Issue by mjknowle** [nextcloud/server#12078]
Steps to reproduce
1. From one NC user (let's call them 'User A'), share a directory that includes a subdirectory of images with another NC user (call them 'User B').
2. Log in as NC user B
3. Go to the subdirectory containing images
4. Go to Gallery view on that subdirectory
5. Create a share link and copy it. Close the Share dialog.
6. Reopen the Share dialog. You get a 'Shared with you by User B' dialog, which is incorrect as a) you *are* user B, and b) you just created a share link!
7. Leave Gallery view, delete the share link
8. Reopen Gallery View. You can re-create the share link, but you only get one chance at it. :-)

Expected behaviour
You should get the share dialog on Step 5 on the second and subsequent clicks on the Share button.

Actual behaviour
See repro case. Second and subsequent attempts to show the share link don't work (without substantial effort)

Server configuration

**Operating system**:
Debian stretch

**Web server:**
nginx

**Database:**
MariaDB

**PHP version:**
7.2.10

**Nextcloud version:** (see Nextcloud admin page)
14.0.3 via docker-fpm

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 13.x
**Where did you install Nextcloud from:**

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.2
  - camerarawpreviews: 0.6.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - drawio: 0.9.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - theming_customcss: 1.1.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "client.mkphotomedia.com",
            "nextcloud_webserver",
            "10.0.1.6",
            "192.168.0.1",
            "neutra.mkphotomedia.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/client.mkphotomedia.com",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_scale_factor": 1,
        "onlyoffice": {
            "DocumentServerUrl": "\/ds-vpath\/",
            "DocumentServerInternalUrl": "http:\/\/onlyoffice\/",
            "StorageUrl": "http:\/\/nextcloud_webserver\/"
        },
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "theme": ""
    }
}
</details>

**Are you using external storage, if yes which one:
no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no
### Client configuration
**Browser:**
Safari
**Operating system:**
MacOS 10.13.6

**Comment by violoncelloch** [comment]
reproduced with NC 14.0.3
should this issue be "moved" to the gallery repo?
cc @nextcloud/gallery

**Comment by skjnldsv** [comment]
Fixed since you can have multiple share links now (nc16 iirc)
