### ISSUE TITLE
Could not generate a preview of this file

### ISSUE THREAD

**Issue by duckulaj** [nextcloud/server#12077]
Nextcloud version (eg, 12.0.2) : 14.0.2
Operating system and version (eg, Ubuntu 17.04) : Linux Mint 18.3 (Kernel 4.18.12-041812-generic)
Apache or nginx version (eg, Apache 2.4.25) : nginx version: nginx/1.10.3 (Ubuntu)
PHP version (eg, 7.1) : PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )

The issue you are facing:

Newly uploaded photos do not have a preview generated.
Error Message is "Error! Could not generate a preview of this file

Is this the first time you’ve seen this error? (Y/N) : Y

Steps to replicate it:

    Upload a jpg file using WebUI or Android client
    Click on file in Nextcloud (no thumbnail present)
    Blank screen with error message displayed

The output of your Nextcloud log in Admin > Logging :

|Error|gallery|Exception: Preview generation has failed|2018-10-11T16:02:43+0100|
| --- | --- | --- | --- |
|Error|gallery|OCP\Files\NotFoundException:|2018-10-11T16:02:43+0100|
|Debug|no app in context|No cache entry found for /appdata_ocjakydyp1vm/preview/1003276 (storage: local::/home/jonathan/WD2TB/nextcloud/data/, internalPath: appdata_ocjakydyp1vm/preview/1003276)|2018-10-11T16:02:43+0100|
|Debug|core|OC_Image-&gt;fixOrientation() Orientation: -1|
The output of your config.php file in `/path/to/nextcloud` (make sure you remove any 

Content of config.php

array (
0 => ‘shazjon.hopto.org’,
),
‘datadirectory’ => ‘/home/jonathan/WD2TB/nextcloud/data/’,
‘overwrite.cli.url’ => ‘https://shazjon.hopto.org/nextcloud’,
‘dbtype’ => ‘mysql’,
‘version’ => ‘14.0.2.2’,
‘dbname’ => ‘nextcloud’,
‘dbhost’ => ‘localhost’,
‘dbport’ => ‘’,
‘dbtableprefix’ => ‘oc_’,
‘dbuser’ => ‘ ’,
‘dbpassword’ => ’ ’,
‘logtimezone’ => ‘UTC’,
‘logtype’ => ‘owncloud’,
‘loglevel’ => 0,
‘logfile’ => ‘/var/log/nextcloud/nextcloud.log’,
‘installed’ => true,
‘memcache.local’ => ‘\OC\Memcache\APCu’,
‘memcache.locking’ => ‘\OC\Memcache\Redis’,
‘redis’ =>
array (
‘host’ => ‘localhost’,
‘port’ => 6379,
)

Error | gallery | Exception: Preview generation has failed | 2018-10-26T21:19:06+0100
-- | -- | -- | --
Error | gallery | OCP\Files\NotFoundException: /var/www/nextcloud/lib/private/Files/Node/Node.php - line 216: OC\Files\Node\Node->getFileInfo()/var/www/nextcloud/lib/private/Files/Node/Node.php - line 117: OC\Files\Node\Node->getPermissions()/var/www/nextcloud/lib/private/Files/Node/Folder.php - line 176: OC\Files\Node\Node->checkPermissions(4)/var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php - line 83: OC\Files\Node\Folder->newFile("1288-966-max.jpg")/var/www/nextcloud/lib/private/Preview/Generator.php - line 210: OC\Files\SimpleFS\SimpleFolder->newFile("1288-966-max.jpg")/var/www/nextcloud/lib/private/Preview/Generator.php - line 118: OC\Preview\Generator->getMaxPreview(OC\Files\Sim ... {}, OC\Files\Node\File {}, "image/jpeg")/var/www/nextcloud/lib/private/PreviewManager.php - line 205: OC\Preview\Generator->getPreview(OC\Files\Node\File {}, 2000, 2000, false, "fill", "image/jpeg")/var/www/nextcloud/apps/gallery/lib/Service/PreviewService.php - line 107: OC\PreviewManager->getPreview(OC\Files\Node\File {}, 2000, 2000, false)/var/www/nextcloud/apps/gallery/lib/Controller/Preview.php - line 167: OCA\Gallery\Service\PreviewService->createPreview(OC\Files\Node\File {}, 2000, 2000, true, false)/var/www/nextcloud/apps/gallery/lib/Controller/Preview.php - line 117: OCA\Gallery\Controller\PreviewController->getPreviewData(OC\Files\Node\File {}, true, 2000, 2000, true, false)/var/www/nextcloud/apps/gallery/lib/Controller/PreviewController.php - line 134: OCA\Gallery\Controller\PreviewController->getData(1003278, 2000, 2000)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166: OCA\Gallery\Controller\PreviewController->getPreview(1003278, 2000, 2000)/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99: OC\AppFramework\Http\Dispatcher->executeController(OCA\Gallery\ ... {}, "getPreview")/var/www/nextcloud/lib/private/AppFramework/App.php - line 118: OC\AppFramework\Http\Dispatcher->dispatch(OCA\Gallery\ ... {}, "getPreview")/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App::main("PreviewController", "getPreview", OC\AppFramew ... {}, { fileId: "1 ... "})OC\AppFramework\Routing\RouteActionHandler->__invoke({ fileId: "1 ... "})/var/www/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(OC\AppFramew ... {}, { fileId: "1 ... "})/var/www/nextcloud/lib/base.php - line 987: OC\Route\Router->match("/apps/gallery/preview/1003278")/var/www/nextcloud/index.php - line 42: OC::handleRequest() | 2018-10-26T21:19:06+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003278 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003278) | 2018-10-26T21:19:06+0100
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-10-26T21:19:06+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003278 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003278) | 2018-10-26T21:19:06+0100
Debug | no app in context | Calling getPreview | 2018-10-26T21:19:06+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003271 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003271) | 2018-10-26T21:19:05+0100
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-10-26T21:19:05+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003271 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003271) | 2018-10-26T21:19:05+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003258 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003258) | 2018-10-26T21:19:05+0100
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-10-26T21:19:05+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003258 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003258) | 2018-10-26T21:19:05+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003269 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003269) | 2018-10-26T21:19:05+0100
Debug | core | OC_Image->fixOrientation() Orientation: -1 | 2018-10-26T21:19:05+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003269 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003269) | 2018-10-26T21:19:05+0100
Debug | no app in context | No  cache entry found for /appdata_ocjakydyp1vm/preview/1003267 (storage:  local::/home/jonathan/WD2TB/nextcloud/data/, internalPath:  appdata_ocjakydyp1vm/preview/1003267) | 2018-10-26T21:19:05+0100
Debug | core | OC_Image->fixOrientation() Orientation: -1

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
