### ISSUE TITLE
Loading dark icon not visible enough

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#12091]
![capture d ecran_2018-10-28_09-51-45](https://user-images.githubusercontent.com/14975046/47613884-2de99600-da97-11e8-868b-042a7e7a1211.png)

**Comment by jancborchardt** [comment]
@skjnldsv you don’t think so? It seems fine to me?

But actually what’s wrong with it is that the spinny part (the 1/4 of the circle) should be lighter, not darker than the 3/4. (Guess this is caused by simple inversion of the values?)

**Comment by skjnldsv** [comment]
> @skjnldsv you don’t think so? It seems fine to me?
> 
> But actually what’s wrong with it is that the spinny part (the 1/4 of the circle) should be lighter, not darker than the 3/4. (Guess this is caused by simple inversion of the values?)

That is exactly my point ;)
