### ISSUE TITLE
Exclude memory_limit from .user.ini and .htaccess

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#121]
Ref https://github.com/nextcloud/server/issues/115

**Comment by josh4trunks** [comment]
This would be great to include for Nextcloud 10.
I just noticed after increasing the 'Maximum upload size', owncloud's 'memory_limit' did not increase.

**Comment by MorrisJobke** [comment]
We should address this in master first and then backport

**Comment by mtompkins** [comment]
+1

**Comment by tx7** [comment]
We're currently on 11.0.1, and this issue still doesn't resolve yet.
Come on guys.

**Comment by MorrisJobke** [comment]
> We're currently on 11.0.1, and this issue still doesn't resolve yet.
> Come on guys.

We are happy about pull requests 😉

**Comment by hcderaad** [comment]
Any update? This still seems to be an issue on updates, which reset the value, and the file integrity check keeps complaining.

**Comment by Zakspeed0** [comment]
when updating to the new version 13.06 I gave the following error:
- FILE_MISSING
   - .user.ini

Thanks to @nachoparker
for helping me replace the file ".user.ini-2

`wget https://raw.githubusercontent.com/nextcloud/server/master/.user.ini -o /var/www/nextcloud/.user.ini`

@nachoparker

**Comment by rcdailey** [comment]
@MorrisJobke Can we close this in favor of nextcloud/server#13990?

**Comment by MorrisJobke** [comment]
Closing as duplicate
