### ISSUE TITLE
Allow iframe for trusted domains

### ISSUE THREAD

**Issue by RuudschMaHinda** [nextcloud/server#12101]
I have a request:
I know that `X-Frame-Options` is like it is for a reason. Is it possible though, to maybe have a value in the `config.php` that can specify trusted domains to allow embedding my installation as an iframe?

I have two people who asked me if they can just embed an installation I am adminning for them for their users to have easy access from their own webpage without needing to "remember" another url to use their cloud solution. As of now they just have it open in another tab, which is fine by me. But one of them keeps coming back to me about this.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
