### ISSUE TITLE
Missing icons in Files app after upgrade to 14.0.3

### ISSUE THREAD

**Issue by dorearendil** [nextcloud/server#12115]
![screen shot 2018-10-29 at 4 33 31 pm](https://user-images.githubusercontent.com/3090867/47658994-a8500e00-db9c-11e8-8bf1-a5d3fda890b6.jpg)
![screen shot 2018-10-29 at 4 33 45 pm](https://user-images.githubusercontent.com/3090867/47658996-a8e8a480-db9c-11e8-9fbc-3342c5b9631a.jpg)
![screen shot 2018-10-29 at 4 33 49 pm](https://user-images.githubusercontent.com/3090867/47658999-a8e8a480-db9c-11e8-8105-465a539abc53.jpg)
![screen shot 2018-10-29 at 4 35 37 pm](https://user-images.githubusercontent.com/3090867/47659000-aa19d180-db9c-11e8-86c4-769fad09b519.jpg)
![screen shot 2018-10-29 at 4 49 01 pm](https://user-images.githubusercontent.com/3090867/47659002-aa19d180-db9c-11e8-8ce6-c243edd465a3.jpg)

 
### Steps to reproduce
1. Upgraded NC server from version 13.0.5 to 14.0.3 by command line
2. Opened NC on browser

### Expected behaviour
All icons visible in Files app

### Actual behaviour
Many icons missing (see screenshots)

### Server configuration

**Operating system**: 
Ubuntu 16.04.1

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.32

**Nextcloud version:** (see Nextcloud admin page)
14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Command line

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"No errors have been found."
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - qownnotesapi: 18.8.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - bookmarks
  - encryption
  - files_external
  - user_external
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2
    }
}
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
YES

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

</details>

### Client configuration
**Browser:**
Chrome v49

**Operating system:**
Mac Os X 10.8.3

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\InvalidPath: File name is a reserved word	2018-10-29T16:29:00+0200
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\InvalidPath: File name is a reserved word	2018-10-29T16:24:00+0200
Fatal	webdav	OCA\DAV\Connector\Sabre\Exception\InvalidPath: File name is a reserved word	2018-10-29T16:15:53+0200
</details>

#### Browser log
<details>
<summary>Browser log</summary>
JS console log:

Uncaught TypeError: nodes[Symbol.iterator] is not a function
search.js?v=f75b1b05-0:66 New search handler registered
VM1046 extensions::uncaught_exception_handler:8 Error in event handler for (unknown): TypeError: buttonsToReplace.forEach is not a function
    at replaceIndividualButton (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/socialwidgets.js:305:20)
    at chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/socialwidgets.js:276:7
    at replaceInitialTrackerButtonsHelper (chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/socialwidgets.js:273:15)
    at chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/socialwidgets.js:60:5
    at chrome-extension://pkehgijcmpdhfbdbbnkijodmdjhbjlgp/js/contentscripts/socialwidgets.js:330:7

</details>

**Comment by MorrisJobke** [comment]
The errors in the browser come from an extension. Could you load the page without any extension enabled? Maybe it's blocking something.

**Comment by dorearendil** [comment]
Thanks for your input, Morris.
I tried disabling all extensions in Chrome, but no joy.
In Firefox (v63, Ubuntu 16.04) something weird happened.
At first, the same icons were hidden as on Chrome. So I tried restarting Firefox with all extensions disabled... and the icons appeared! So I tried reactivating the extensions one by one -- but none of them seems to break the page anymore... All of them are now reactivated, and all icons are displayed.

Using the Chrome inspector, I noticed that the background-image paths of non-displayed icons don't seem to be found in the CSS. For instance, the main NC logo, top-left:

#header .logo {
    display: inline-flex;
    background-image: var(--image-logo);
    background-repeat: no-repeat;
    background-size: contain;
    background-position: center;
    width: 62px;
    position: absolute;
    left: 12px;
    top: 1px;
    bottom: 1px;

In Firefox now, this full path is shown for all icons (even though I deleted the cache)

**Comment by juliushaertl** [comment]
@dorearendil Can you check if the /index.php/css/icons/icons-vars.css returns a proper css file with a list of all css variables? The image-logo should be set in there

**Comment by juliushaertl** [comment]
@dorearendil Any other entries in your nextcloud log besides the webdav errors?

**Comment by dorearendil** [comment]
@juliushaertl No, only the webdav errors... :(

**Comment by juliushaertl** [comment]
Can you try to run `occ maintenance:repair` This should empty the css caches and trigger a rebuild on the next page load.

**Comment by dorearendil** [comment]
@juliushaertl I ran the repair command, and things seem to be back to normal on all my browsers except for an old version of Chrome (which my system won't let me update). So I guess the issue can be considered solved. Many thanks for your kind advice.
