### ISSUE TITLE
Order of active apps/hooks

### ISSUE THREAD

**Issue by tomlp** [nextcloud/server#12116]
### Steps to reproduce
1. activate APP´s for different actions. for example: virus scan - watermark - digital sign - encryption
2. upload a file
3. it will - maybe - fail. The **Order of Hooks** can´t be fixed to be sure that the encryption is on the end of the process... Or the Watermark is before digital sign and not afterwards...

### Expected behaviour
in the APP´s all possible/registered hooks are listed and can be reordered to give the expected behaviour

### Actual behaviour
no ordering of Hooks is possible - (if it is there - i don't find a clue where :) )

### Server configuration

**Operating system**:
CentOS 7 (should run under all systems)
**Web server:**
NGinx
**Database:**
MariaDB
**PHP version:**
PHP 7.2
**Nextcloud version:** (see Nextcloud admin page)
>= 14.0.3 
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
bz2 from download

** side not **
i am working currently on digital signing of uploaded documents and the next step will be a watermark on PDF´s / Images...

**Comment by blizzz** [comment]
Would need to pass this information when registering (and having a fallback for compat). What comes to my mind directly:

Simplest thing could be just a priority number, but it still is not very reliable and requires that apps look at each other. 

But, perhaps we can reuse the app types. As some are priorized (e.g. auth, filesystem) over others. It might not be enough, though. 

More complex would be to allow apps to definer some criteria ("after/before:$app/$type"), being in danger to run into cyclic dependencies. Not a fan.

**Comment by rullzer** [comment]
The default event dispatcher of symfony (that we use in a lot of places) already had priority

**Comment by blizzz** [comment]
> The default event dispatcher of symfony (that we use in a lot of places) already had priority

I don't recall seen this in use? Would be an opportunity to migrate over the other 2, 3 mechanisms that we have in place.

**Comment by skjnldsv** [comment]
What's the status here? :)
Still relevant?

**Comment by nickvergessen** [comment]
Let's close it, for the new events this is no longer a problem and the old ones will be fixed by moving to the new event system which @rullzer has on his todo IIRC.
