### ISSUE TITLE
Support for 5.4 and 5.5 was dropped

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1211]
Therefor we can't test on travis against those anymore.

Please help reviewing all the PRs for various apps:
- [x] https://github.com/nextcloud/activity/pull/35
- [x] https://github.com/nextcloud/announcementcenter/pull/36
- [x] https://github.com/nextcloud/files_accesscontrol/pull/34
- [x] https://github.com/nextcloud/files_automatedtagging/pull/16
- [x] https://github.com/nextcloud/files_texteditor/pull/10
- [x] https://github.com/nextcloud/firstrunwizard/pull/15
- [x] https://github.com/nextcloud/networkconfig/pull/1
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/6
- [x] https://github.com/nextcloud/notifications/pull/19
- [x] https://github.com/nextcloud/password_policy/pull/22
- [x] https://github.com/nextcloud/serverinfo/pull/45
- [x] https://github.com/nextcloud/survey_client/pull/28
- [x] https://github.com/nextcloud/files_pdfviewer/pull/11
- [x] https://github.com/nextcloud/files_retention/pull/4
- [ ] https://github.com/nextcloud/templateeditor/pull/9

@MorrisJobke @LukasReschke @mar1u5

**Comment by MorrisJobke** [comment]
@nickvergessen Please check the failing CI stuff ;)

**Comment by nickvergessen** [comment]
All fixed apart from password_policy, which needs a fix on the server PR is awaiting review

**Comment by MorrisJobke** [comment]
All done except templateeditor -> closing nevertheless because it's aCI job PR anyway ;)
