### ISSUE TITLE
mp3 with brackets in name doesn't open in web or preview/download from shared link

### ISSUE THREAD

**Issue by lachlan-00** [nextcloud/server#12136]
Logs don't have anything in nextcloud and apache has a simple 404 on the url

Nextcloud 14.0.3, apache, php 7.2

Preview never starts and file won't download. Other files work fine but it seems like the brackets aren't escaped properly?

**Comment by lachlan-00** [comment]
Just looked at it further and the file is unable to be accessed in any way using the web interface.
![image](https://user-images.githubusercontent.com/1305249/47754613-333d1f80-dce7-11e8-8a06-0775aef71fca.png)

Using the web interface does provide an error in the logs so i'll unshare the public links
![image](https://user-images.githubusercontent.com/1305249/47754663-5f58a080-dce7-11e8-9c0e-066ed8101dc6.png)

**Comment by danielkesselberg** [comment]
Your `datadirectory` is `/mnt/data`? Could you check http://php.net/manual/en/ini.core.php#ini.open-basedir? When php is not allowed to write `/mnt/data` you run into troubles.

**Comment by lachlan-00** [comment]
My data is in /mnt/data

I've added it to the apache conf but the same effect after restarting/reloading
php_admin_value open_basedir "/opt/nextcloud:/mnt/data:/tmp/:/"

I think i see the issue though. the file doesn't have the brackets in my data folder. this was copy/paste from the client.
![image](https://user-images.githubusercontent.com/1305249/47756397-9cc02c80-dced-11e8-9ef7-4188c5a37683.png)

**Comment by lachlan-00** [comment]
I have tested this with a new version of the client and uploads appear to be correctly taking into account the special characters. I was able to upload a file and share it while verifying the file name in the web server
