### ISSUE TITLE
Expired tokens should not trigger bruteforce protection

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#12131]
When a token expires (for example OAuth tokens) and authentication is attempted with it we fail.
This is fine as authentication should fail with expired tokens.

However we should not register this as a bruteforce attempts. As it is actually not that.

CC: @ChristophWurst @Dagefoerde

**Comment by Dagefoerde** [comment]
Yes, those are false positives. Also, as the (attempted, invalid) token is pretty much the same every time this would be a very stupid brute force attempt ;)
