### ISSUE TITLE
/etc/ldap/ldap.conf is not read when installed via snap

### ISSUE THREAD

**Issue by thermionic** [nextcloud/server#12149]
### Steps to reproduce
clean install of Ubuntu 18.0.4 server

sudo add-apt-repository universe
sudo apt-get update
sudo apt-get dist-upgrade
sudo apt-get install inotify-tools
sudo inotifywait -m /etc/ldap/ldap.conf
sudo snap install nextcloud
enable Nextcloud app "LDAP user and group backend"
add LDAP host, credentials and base DN
click Test Base DN

### Expected behaviour
ldap.conf should be read

### Actual behaviour
ldap.conf is not read

### Server configuration

**Ubuntu 18.04**:

**Web server: as installed by sudo snap install nextcloud**

**Database: as installed by sudo snap install nextcloud**

**PHP version: as installed by sudo snap install nextcloud**

**Nextcloud version:13.06  as installed by sudo snap install nextcloud**

**fresh install:**

**Where did you install Nextcloud from:**
 as installed by sudo snap install nextcloud

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
as installed by sudo snap install nextcloud
LDAP user and group backend

**Comment by blizzz** [comment]
Please reopen in https://github.com/nextcloud/nextcloud-snap
