### ISSUE TITLE
Send password when sharing via e-mail

### ISSUE THREAD

**Issue by chagam** [nextcloud/server#1214]
I found this bug report in owncloud : https://github.com/owncloud/core/issues/11682
### Steps to reproduce

Share a folder with a public link and a password.
Send the email by using the "Send link by email" button
### Expected behaviour

Have the possibility to send the password in the email and not in a different one
### Actual behaviour

The mail received doesn't have the password.

**Comment by rullzer** [comment]
This is no longer relevant as the send mail functionality is replaced by the share by mail provider.
