### ISSUE TITLE
Include link to map service next to location in IMip email and contact list Address entries

### ISSUE THREAD

**Issue by brad2014** [nextcloud/server#12157]
Feature request (after an exchange with @georgehrke):

1. Include a Map link next to each contact address on the contact detail view
2. Include a Map link next to the event location in IMIP event invitation emails
3. Allow a system configuration variable *map_service_url* (perhaps a suitable default would be `"https://www.openstreetmap.org/search?query=%s"`), and incorporate it into the UI in those two places. (I think making it a user preference introduces too much complexity, just my opinion).

While I'm not looking, some system admins might change the service their site provides, for example: 
 
```
occ config:system:set map_service_url "https://maps.apple.com/place?address=%s" 
```
Ou si on prefère ses cartes en français, et la capture de tous ses détails privés par le Google Omnipotente, peut-être:
``` 
occ config:system:set map_service_url "https://maps.google.com?hl=fr&q=%s"
```

**Comment by brad2014** [comment]
Ou si on prefère ses cartes en français, et la capture de tous ses details privés par le Goog, par hasard:
``` 
occ config:system:set map_service_url "https://maps.google.com?hl=fr&q=%s"
```

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
