### ISSUE TITLE
Label below app icon in app bar is not clickable

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#12165]
On master, when we hover above the app icons, the shrink and a tiny text label is show. The lable is not clickable, which is bad because the possible area to click got significantly smaller:

![appbar](https://user-images.githubusercontent.com/2184312/47784948-8626cf00-dd07-11e8-9edb-0c3a2798c9f6.png)

@nextcloud/javascript

**Comment by skjnldsv** [comment]
@nextcloud/designers @jancborchardt

**Comment by jancborchardt** [comment]
Good catch! Pull request at https://github.com/nextcloud/server/pull/12181

**Comment by blizzz** [comment]
This is back (current 15) :scream:

**Comment by weeman1337** [comment]
Yep, and solved; see #13566

**Comment by blizzz** [comment]
have not seen it got a new issue. closing therefore, and thanks for fixing @weeman1337  :)
