### ISSUE TITLE
Can't generate apptoken in security settings

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#12176]
Caused by https://github.com/nextcloud/server/pull/12167

1. Go to your security settings
2. Try to generate an apptokens
3. Do not see your actual new apptoken.

The form is actually there it is just hidden.
Probably weird JS/CSS magic at play

**Comment by jancborchardt** [comment]
This is reverted/fixed by https://github.com/nextcloud/server/pull/12196 :)
