### ISSUE TITLE
Offer duplicate/rename when copying into same folder

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12183]
In webUI
- create 1.txt
- select copy/move on 1.txt
- select "/" as target for copy
-> fails with "error 1.txt already exists"

Instead it should offer a rename dialog with "suggest new name", so that one can duplicate the file with a new name.

Currently I have to do this c&p manually on desktop (android also refuses this).

Does this make sense? Then I'll open up an issue also on android/test on iOS.

**Comment by violoncelloch** [comment]
Isn't this already targeted by #10825 which automatically adds ([Xth] copy) to files copied to the same directory?

**Comment by MorrisJobke** [comment]
Duplicate of #9931
