### ISSUE TITLE
Swift Object storage returns 429 Too many requests

### ISSUE THREAD

**Issue by antoinesauray** [nextcloud/server#12189]
### Steps to reproduce
I used French provider OVH to reproduce
1. Setup a Swift object storage container
2. Use it a main storage

### Expected behaviour
It should send file using the same token, and not call the POST https://auth.cloud.ovh.net/v2.0/tokens so often
### Actual behaviour
It seems to be calling the Swift endpoint too often, which leads to http 429
### Server configuration

**Operating system**:
Ubuntu 16.06

**Web server:**
Nginx + fpm
**Database:**
PostGreSQL

**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Comment by Arvi89** [comment]
Can we get updates on this issue? It's becoming a real problem for me, I can't look at my pictures in my auto upload folders because it makes too many requests.

**Comment by Arvi89** [comment]
Hello, anyone here?

**Comment by Arvi89** [comment]
This actually worked, thanks!
