### ISSUE TITLE
[Feature Request] and [Job offer] Social features app - posting news

### ISSUE THREAD

**Issue by freefromconcept** [nextcloud/server#12199]
Hey guys.

Hopefully, this is an appropriate place to post our request.

We are currently aiming to use Nextcloud as an Intranet system, seeking a PHP developer who is much familiar with Nextcloud apps.

The major request among others for now is to develop a new 'social features' app, somewhat similar to the Mood app functionality - https://github.com/daita/mood.

Also, there’re a couple more things we need to implement in relation to the extending of some actual Nextcloud apps functionality.

We can agree with you either on a fixed price or on an hourly pay rate format and enrich the Nextcloud community.

If you’re interested and you have any further questions, let me know in this thread and we can schedule a chat or a call and discuss the further details.

Looking forward.

Have a good day!

**Comment by karlitschek** [comment]
@freefromconcept interesting. Do you have specific features or requirements that you would need? Some specification or mockups? It would be great if you could post them here so that we can see what we can do

**Comment by freefromconcept** [comment]
Hello @karlitschek 

Sure. Gladly.

So, basically we're aiming to have a simple social media app which will include:

* ability to **publish posts** with media files / links attachment (as on social media platforms).
* integration with Nextcloud groups - people will be grouped by i.e. project, region etc. So the post could be shared exactly to the selected group(-s) only.
* the ability to leave comments to the posts.
* integration with the Dashboard app.

For us such functionality will really help to keep the Intranet members even more connected between each other, being more aware in common wide informational field.

Before we were thinking of extending the Mood app. But it may be better to code such an app from scratch.

We don't have any wireframes/mockups yet, since beforehand we need to find and agree with the very developer who will code this.

What do you think?

**Comment by karlitschek** [comment]
Great. Could you send me an email to frank (at) nextcloud ? Thanks 😀

**Comment by karlitschek** [comment]
@freefromconcept Please send me an email to  to frank (at) nextcloud com Happy to discuss what we can do to help :-)

**Comment by freefromconcept** [comment]
Hi Frank.

Just wrote you an email in this relation.

**Comment by szaimen** [comment]
Seems like this has become reality https://apps.nextcloud.com/apps/social
