### ISSUE TITLE
Proposal for enhancement: Allow user defined clear names for shared links

### ISSUE THREAD

**Issue by frake65** [nextcloud/server#1220]
This is a proposal for possible enhancement:
From my point of view it would be nice if the links used for sharing files could possibly contain some clear text defined by the user sharing the file. I am not sure if this has to be a unique id for some specific reason.

### Expected behaviour
The name of the link could be editable to the user sharing it. Alternatively a second field could be used to have the clear text link. - Especially for sharing long term files this feature could be helpful (i. e. I want to share some fixed link referring  to my personal profile)

### Actual behaviour
some unique string is generated each time the shared link is generated - if the link is removed - even by accident - I cannot revert to the original link

**Comment by rullzer** [comment]
There is an app that lets you change the link (in the appstore https://apps.owncloud.com/content/show.php/Files+Share+Link+Renamer?content=174742)
