### ISSUE TITLE
[Feature Request] Add possibility to rename connected devices

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#12203]
### Steps to reproduce
1. Login to Nextcloud
2. Go to "Settings" -> "Security"
3. See the list of connected devices

### Expected behaviour
The user should be able to rename the devices

### Actual behaviour
Names of the devices are fixed

### Server configuration

**Nextcloud version:** 14.0.3

**Comment by danielkesselberg** [comment]
Duplicate #6717
