### ISSUE TITLE
Restore PersonalSection in Database

### ISSUE THREAD

**Issue by unitrav** [nextcloud/server#12220]
How can I restore PersonalSection in my database?

Thank you

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `class` FROM `oc_personal_sections` WHERE `class` = ? LIMIT 1' with params ["OCA\\FederatedFileSharing\\Settings\\PersonalSection"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'timkroeg_next879.oc_personal_sections' doesn't exist

**Comment by johnsonm** [comment]
#12218 shows working around it for the update, but my own #13291 shows that even working around it for the update doesn't make things work again. The Version13000Date20170705121758 migration doesn't seem to run.

**Comment by ChristophWurst** [comment]
AFAIK this db table isn't used anymore.

If you still face this issue, please file a proper [bug report](https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md).

Thank you
