### ISSUE TITLE
Network interface not working in esxi

### ISSUE THREAD

**Issue by stuffedmonkey** [nextcloud/server#1222]
### Steps to reproduce
1. Dell T20 running Dells Esxi6 img
2. Added vm to inventory. Unable to edit network adapter and pre-configured isnt working. 
3. Unable to run the script due to none working network setup. 

### Expected behaviour
Tell us what should happen
Network should work and I would like to install NC. 

### Actual behaviour
Tell us what happens instead
No network. No installation. Keep looking for dhcp and finns none. Interface shows up as ens33 insted of eth0. Adding status IP doesnt help, the script ignores that. Adding another adapter doesnt help either. 

### Server configuration
**Operating system**:
Dells version of Esxi 6 for Poweredge T20
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
Latest from your homepage. 9 i think. 
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh. Have the same issue with boot NC and OC. 

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
cc @oparoz because you asked about ESXi yesterday too

**Comment by MorrisJobke** [comment]
cc @enoch85 for the VM part

**Comment by stuffedmonkey** [comment]
FYI. I gave up and trashed the VMs. Insted I created a new VM with Ubuntu Server 16 and the downloaded the zip (or rar) with all the scripts for github. I then managed to run the installation script after making sure that the network interface was working, and it was from the get go.
So now everything is up and running. Just haveto figure out how to expand the virtual drive, and then install the ssl.

**Comment by oparoz** [comment]
Thanks for the update. We still need to figure out why it doesn't work on ESXi, but it could be network driver related.

**Comment by enoch85** [comment]
FYI, I run ESXI without any issues at all. Cc @ezraholm50 as I'm on vaccation.

**Comment by oparoz** [comment]
Which I think confirms that this may be driver related

**Comment by nickvergessen** [comment]
Closing this, if it is still an issue, please reopen a new one in https://github.com/nextcloud/vm
