### ISSUE TITLE
Hide notification-indicator when no notifications are available

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#12221]
I would suggest to hide the empty notification-element, if there are no things to display.  If there is nothing in there, this element serves no purpose and could be hidden.

Or is there a specific reason why the notification-indicator is always shown? If i remember correctly, it was hidden pre Nextcloud 14.

@nextcloud/designers

**Comment by MorrisJobke** [comment]
> Or is there a specific reason why the notification-indicator is always shown? If i remember correctly, it was hidden pre Nextcloud 14.

We actually added it as "always there" to indicate that this is a UI element and to make it accessible. Also GitHub does it for example like that. I couldn't find the original issue anymore, but we said, that we should show it always and not only in case there is something new.

**Comment by jancborchardt** [comment]
Find the whole discussion at https://github.com/nextcloud/notifications/issues/2 ;)

(I’ll close this as it’s definitely something for the Notifications app.)
