### ISSUE TITLE
Share link menu disappears when setting expiration date

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#12232]
When opening the shared link menu and then opening the date picker and then clicking the left arrow to go back one month, the share link menu disappears and you lose context of what was happening, also making me unsure if the date I'm going to pick will actually save. It actually does save, so that's a bonus.

**Comment by skjnldsv** [comment]
#15719 is merged, go go go Clients :D

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
