### ISSUE TITLE
Feedback for LDAP Quota

### ISSUE THREAD

**Issue by tvannahl** [nextcloud/server#12239]
I am filing this report, because I had problems with this despite recurring similar issue being reported like:
 * "LDAP: Quota issues" (#3068)
 * "Quota overwritten for ldap users if default is set in LDAP settings" (#6886)
 * " Nextcloud resets quota every week" (#7300)

If you have that background the overall behaviour of nextcloud is fine, it's just missing feedback in the UI.

### Steps to reproduce
1. Setup nextcloud with LDAP user management
2. Set the `Quota Default` field under `LDAP Integration/Advanced/Special Attributes`
3. Change the Quota of an LDAP User to a value higher then the `Quota Default`.

### Expected behaviour

Nextcloud notifies the administrator that the value has not been changed due to the LDAP Quota settings.

### Actual behaviour

Nextcloud accepts the admins input but resets it after a while without notice.

### Server configuration

**Nextcloud version:** 14.0.3

**Comment by blizzz** [comment]
> Change the Quota of an LDAP User to a value higher then the Quota Default.

In LDAP or in the built-in user quota settings? If you decide to control quota via LDAP, then it will always override whatever is done in user management.

**Comment by maurerle** [comment]
I ran in this issue today too.
I had something set as "standard quota" in advanced settings in LDAP a long time ago and wondered why my manual quota modification has been reset every few minutes.

As the LDAP quota value gets set on every login it is always winning.

It should be unable (greyed out) to set a quota for a user if its backend is LDAP and a "standard quota" has been set in LDAP.

Same should apply if a mail attribute is set.
(on second thought, this is a little bit trickier, as it could work out to configure a LDAP mail attribute which is empty for a user in LDAP . But I don't think that this is a valid use case so disabling would be good)

**Comment by maurerle** [comment]
found another two related issues: #17154 and #17614

**Comment by romale** [comment]
Here's my issue https://github.com/nextcloud/server/issues/17514

**Comment by romale** [comment]
Here's my issue https://github.com/nextcloud/server/issues/17514

**Comment by skjnldsv** [comment]
If your issues are duplicate, please close them so we can focus on a single one :)
