### ISSUE TITLE
Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/caldav" aufzulösen.

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/server#12235]
Hi Team,

since my upgrade to 14.0.3 im getting following messages in my (german) interface ...

```
Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/caldav" aufzulösen. Weitere Informationen findest Du in der Dokumentation.
Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/carddav" aufzulösen. Weitere Informationen findest Du in der Dokumentation.
```

Yes, I've looked in the Documentation, but I'm not that experienced to fix that without help.
Maybe someone can help me showing the right way ...

System: Ubuntu 18.04LTS / PHP 7.2.9 / NGINX 1.14.0

Thanks a lot,

Tom

**Comment by tflidd** [comment]
The bug tracker is for bugs, if you want support from the community, please use the forum on help.nextcloud.com. If you'd like a better documentation, please use the bug tracker for the documentation (it's important to have feedback from normal users, where they lost track, some minor changes can make a huge difference): https://github.com/nextcloud/documentation/issues
