### ISSUE TITLE
Upgrade to 15.0.0 alpha failed with Undefined column: 7 ERROR:  column "uid" does not exist

### ISSUE THREAD

**Issue by 1div0** [nextcloud/server#12237]
### Steps to reproduce
1. git pull
2. occ upgrade
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'SELECT "id", "carddata" FROM "oc_cards" WHERE "uid" IS NULL LIMIT 1000':

SQLSTATE[42703]: Undefined column: 7 ERROR:  column "uid" does not exist
LINE 1: SELECT "id", "carddata" FROM "oc_cards" WHERE "uid" IS NULL ...
                                                      ^
HINT:  Perhaps you meant to reference the column "oc_cards.id".
Update failed

**Operating system**:
F28

**Web server:**
httpd-2.4.34-10.fc28.x86_64

**Database:**
postgresql-10.5-3.fc28.x86_64

**PHP version:**
php-7.2.11-1.fc28.x86_64

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.reflexion.tv"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "15.0.0.1",
        "overwrite.cli.url": "https:\/\/cloud.reflexion.tv\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "theme": "",
        "loglevel": 2,
        "maintenance": true
    }
}

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by trendzetter** [comment]
exactly same here! First upgrade on a very recent master 410bd9d784..b9783993da.

**Comment by trendzetter** [comment]
Maybe something is wrong with the versioncheck in shouldRun() ?
 lib/private/Repair/NC15/SetVcardDatabaseUID.php

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
