### ISSUE TITLE
Link expiration date formatting by region

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#12233]
On the shared link expiration date, it's in a format that I'm not accustomed to. I live in the US and we do dates backwards, month-day-year. This should ideally be a regional setting, or something, and I would expect to see month-day-year instead of day-month-year because right now I set November 8, 2018 but it looks to me like August 11, 2018 if I didn't know any better. The exact text I'm referring to in this example is 8-11-2018 which is ambiguous to me.

**Comment by 2nutz4u** [comment]
Were you able to resolve this issue?

**Comment by linucksrox** [comment]
No, it still displays "backwards" for me in 17.0.1

**Comment by szaimen** [comment]
I cannot reproduce that as it just displays YYYY-MM-DD no matter which language or locale I choose.

**Comment by linucksrox** [comment]
Thanks, apparently this has been fixed in the last couple years 👍
