### ISSUE TITLE
Enforce two-factor auth UX issues

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#12249]
It is really great that we have the possibility to enforce two factor auth with Nextcloud 15, thanks to everyone who made this happen!

I tested it last week with @MariusBluem and we found some (small) issues we want to document for improvements.

1. I think the settings could need some more spacing, the "Limit to groups" part looks quite squeezed together:

![image](https://user-images.githubusercontent.com/1589737/47969446-1d798280-e078-11e8-9695-862a304e158c.png)

Also it was not obvious to me what this settings mean. If I don't do anything, will it be enforced for everyone? What happens if I explicitly enforce it for groupA and not for groupB and a user is in both groups?

2. ~~Another thing which confuses me is that I can enforce two factor auth even if no single two factor out method is enabled. I think it would make sense to check that at least one is enabled (u2f, totp,...) and otherwise disable the checkbox.~~ -> https://github.com/nextcloud/server/issues/12267

3. OK, I enabled it now, logged out and tried to login again, which lead to this screen

![image](https://user-images.githubusercontent.com/1589737/47969498-e48ddd80-e078-11e8-9ff9-07fbed08082c.png)

As I'm the admin I'm now logged out.
Also I don't understand why I should contact the admin now and what they are supposed to do. ~~What I would expect is that Nextcloud tells me that two-factor auth is required for this account and ask me to scan a Qr code, insert my Nitrokey, whatever. Basically offering a way to complete the setup by myself. I don't think it scales for large installation if everyone has to contact the admin now to do something manually.~~ -> https://github.com/nextcloud/server/issues/12268

**Comment by schiessle** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
> Also it was not obvious to me what this settings mean. If I don't do anything, will it be enforced for everyone? What happens if I explicitly enforce it for groupA and not for groupB and a user is in both groups?

Will add more explanatory text for this as well as documentation, ref https://github.com/orgs/nextcloud/projects/17#card-13042458

>     Another thing which confuses me is that I can enforce two factor auth even if no single two factor out method is enabled. I think it would make sense to check that at least one is enabled (u2f, totp,...) and otherwise disable the checkbox.

I will open an enhancement ticket for this.

> As I'm the admin I'm now logged out.
> Also I don't understand why I should contact the admin now and what they are supposed to do.

This screen is targeted for users when the admin enforced 2FA but individuals had not set up a provider before. This is what we created https://apps.nextcloud.com/apps/twofactor_admin for.

For admins that lock themselves out … well. Should we check if the user enforcing 2FA has 2FA enabled? We could only do that on the web UI though. I can open a ticket for that.

> What I would expect is that Nextcloud tells me that two-factor auth is required for this account and ask me to scan a Qr code, insert my Nitrokey, whatever. Basically offering a way to complete the setup by myself. I don't think it scales for large installation if everyone has to contact the admin now to do something manually.

This was discussed in https://github.com/nextcloud/server/issues/11021.


---



> We could solve this by showing an overview about the users 2FA status in the user-settings (see GitHub organization-settings) ... GitHub is a positive example of 2FA mandatory settings & behavior.

Possible but a bit expensive to query right now. I will create an enhancement ticket for this.

> He should do `sudo -u www-data php occ twofactor:disable <username>` sweat_smile

No, see https://github.com/nextcloud/server/issues/11018

> ⬆ Like GitHub does ... if we want to have it more easy (for now) I could think of blocking those restriction for groups in which not everybody has 2FA enabled already.

Nope 
![bildschirmfoto von 2018-11-05 08-17-08](https://user-images.githubusercontent.com/1374172/47983386-6c083a80-e0d3-11e8-9992-795d695c07db.png)

**Comment by ChristophWurst** [comment]
> As I'm the admin I'm now logged out.

Btw, the admin interface even warned you: *If they do not have a two-factor provider configured, they will be unable to log into the system.* :see_no_evil:

**Comment by ChristophWurst** [comment]
I think so, yes.

**Comment by te-online** [comment]
Just wanted to say, great improvements on this feature! 🎉 I trapped myself into forcing 2fa, while it was not configured for my admin account, so @schiessle was not the only one... 😬
