### ISSUE TITLE
Safari 6.1.6 doesn't render correctly Nextcloud pages.

### ISSUE THREAD

**Issue by kde35** [nextcloud/server#12246]
### Steps to reproduce
1. Use Safari to log in to Nextcloud

### Expected behaviour
The page renders correctly

### Actual behaviour
The page renders as is shown in the attached file (notably header menu is missing, only few letters of file name show up).
![capdemocloud](https://user-images.githubusercontent.com/13499351/47967825-03cd4080-e062-11e8-8dd0-f3548e2e6f30.png)

### Server configuration

This happens with demo server at demo.nextcloud.com

### Client configuration
**Browser:**
Safari 6.1.6
**Operating system:**
MacOS X.7.5

**Comment by juliushaertl** [comment]
I cannot reproduce this. @kde35 Please try again with the latest release and in case it still occurs, feel free to reopen the issue with a complete issue template filled out. Especially errors from the browser console/network tab would be useful in such a case.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>
