### ISSUE TITLE
Generic Bottleneck Detector

### ISSUE THREAD

**Issue by guettli** [nextcloud/server#12241]
This is a feature request.

It would be great to have a generic bottleneck detector.

Why is up/download slow on my server?

There are many things which could slow down things.

Great UX means "don't make me think".

If I search for "nextcloud slow" I get many forum and Q+A posts.

But why think and guess over and over again?

Wouldn't it be great if you could run a benchmark against nextcloud in production
and the result is a nice HTML page with hints what could be the issue in my particular installation?

I think this would add big value to the product.

**Comment by tflidd** [comment]
There is a bit of that idea in the serverinfo-app (https://github.com/nextcloud/serverinfo/issues).

I'm not sure if we could easily add a database-performance check. There are tools that can check your database, I don't know if it is reasonable to add all this, there are dedicated tools that make a better job (you always need to keep them updated).

As a first step it would probably a good idea to gather all the information in the different Q+A posts for the documentation and improve this article: https://docs.nextcloud.com/server/13/developer_manual/general/performance.html and have a step-by-step guide to most of the possible issues.

Give a bit more details and some performance benchmarks for different systems (e.g. RPi3, ....) to know what to expect.

In a second step we can check which of these checks can be integrated in an automated test.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
