### ISSUE TITLE
share dialog checkboxes misbehave 

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#12250]
I just noticed that the checkboxes of the share dialog misbehave on master.

If I create a new group share this is how it looks (same happens for user shares):

![image](https://user-images.githubusercontent.com/1589737/47969627-c1642d80-e07a-11e8-8ca6-07ce6138184c.png)

"Can edit" and "Can reshare" is checked. Now I uncheck "Can reshare" and this is what happens:

![image](https://user-images.githubusercontent.com/1589737/47969632-e0fb5600-e07a-11e8-8a4b-3ef518b57889.png)

"Can edit" is also unchecked! It is not just a front-end issue. If I reload the page, "Can edit" is still unckeched. So it seems we really remove all permission when the user just removes "can reshare"

If I remove "Can edit" instead the dialog behaves correctly and the "can reshare" permissions stays.

This only happens for file shares, for folders the behaviour seems to be correct. My assumption is that this is the case because for folders we have additional "edit permissions" in the '...' menu while for file shares we just have the reshare permission.

Maybe some of our @nextcloud/javascript experts can have a look.

cc @MariusBluem because we discovered and discussed it last week

**Comment by MariusBluem** [comment]
Reproduced with **Firefox** and **Safari** on macOS yesterday - you were faster @schiessle 😅

**Comment by MorrisJobke** [comment]
@skjnldsv @danxuliu @ChristophWurst Any idea?

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
No idea. How is the backend? Are we sure this is only a javascript issue?

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
