### ISSUE TITLE
Server tadd trusted domain link leaks internal ip address for nc instance

### ISSUE THREAD

**Issue by tspr** [nextcloud/server#12274]
Hi,
just tried to debug my nc setup. I requested the login page vie ip (not fqdn) with curl from externally, i got the following:

curl -kv https://xxx.yyy.7.41/nextcloud/     
....
-----
	<p style="text-align:center;">
		<a href="https://192.168.1.zzz/nextcloud/index.php/settings/admin?trustDomain=xxx.yyy.7.41" class="button">
			Add &quot;xxx.yyy.7.41&quot; as trusted domain		</a>
	</p>
-----

Shouldn't the admin link be set to include either the baseurl (fqdn) or as a relative link (as all the other links are)?

Thomas

**Comment by violoncelloch** [comment]
This is neccessary to give the admin the option to easily add the new domain to the trusted domain array...
To not expose the internal IP you can just set an other Domain as default / first trusted domain...
What do you think @nextcloud/security ?

**Comment by tspr** [comment]
Well,
if the admin should operate from outside, the link won't work. 


By the way, i'm running  

NC V 13.0.5 
php Version: 7.0.26 
on freebsd/jail (versions somewhat mangled, unfornately)
nc 

will update to 13.0.7 now to figure out, f problem persists.

**Comment by rullzer** [comment]
We actually killed this in Nextcloud 14. Because it never fully worked.

**Comment by MorrisJobke** [comment]
Also have a look at the overwrite* options in sample config.php to enforce some domains (Nextcloud then stops guessing the domain;))

And as we removed this feature as well it will not occur once the overwrite* options are set.

Closing for now
