### ISSUE TITLE
PDF Viewer not showing changes

### ISSUE THREAD

**Issue by Ninjiner** [nextcloud/server#12279]
### Steps to reproduce
1. Edit a PDF with [Drawboard PDF](https://www.drawboard.com/pdf/)
2. Upload it via Client or Browser
3. Open the file with the pdf viewer on the server

### Expected behaviour
I can still see the changes I made before.

### Actual behaviour
The changes I made before have gone.

### Server configuration

**Operating system**:
openSUSE Leap 42.2
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
14.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.0.0
**Where did you install Nextcloud from:**
Source
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_audit: 1.4.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - encryption
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "nc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": "4",
        "theme": "",
        "maintenance": false,
        "appcodechecker": false,
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** NFS mount

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

</details>

### Client configuration
**Browser:**
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
**Operating system:**
Kubuntu 18.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
a) console log
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
unreachable code after return statement[Learn More] merged.js:1501:4
window.controllers/Controllers is deprecated. Do not use it for UA detection. merged.js:2176
New search handler registered search.js:66:4
querying Whats New data was successful: nocontent merged-template-prepend.js:4480:4
undefined merged-template-prepend.js:4481:4
An iframe which has both allow-scripts and allow-same-origin for its sandbox attribute can remove its sandboxing. files
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”).
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). files_pdfviewer:1:1
Deprecated API usage: PDFJS.openExternalLinksInNewWindow, please use "PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK" instead. util.js:288:2
#Close is undefined. l10n.js:831:6
#Close is undefined. l10n.js:903:6
#close_label is undefined. l10n.js:831:6
#close_label is undefined. l10n.js:903:6
Content Security Policy: The report URI (about:blank) should be an HTTP or HTTPS URI.
Content Security Policy: The page’s settings observed the loading of a resource at https://cloud.ivaris.ch/apps/files_pdfviewer/vendor/pdfjs/build/pdf.worker.js?v=1.3.2 (“worker-src”). A CSP report is being sent.
PDF ea89d78e6f14c1c8c72cb08ed4992d57 [1.6 OmniPage 19 / OmniPage CSDK 18] (PDF.js: 1.9.426) app.js:1078:6
```
</details>

**Comment by violoncelloch** [comment]
Are you sure the changes are written to the file and the file synced back to the server? What kind of changes do you make to the pdf?

**Comment by violoncelloch** [comment]
Are you sure the changes are safed into the pdf itself and not synced by drawbord via microsoft or something?
Maybe it's some special pdf content normal PDF viewers can't display?

**Comment by Ninjiner** [comment]
I have now tested it like this:
Surface (Windows) edits with drawboard and uploads it.
Kubuntu 18.04 either syncs or downloads directly and opens file. 
In this case there is can't be any other kind of sync so it has to be the PDF Viewer I guess...

I also tested it on several other clients containing windows/linux/osx. Everywhere I get the same result.

**Comment by violoncelloch** [comment]
ok, thank you for clarifying.
So concluding it's not changes not synced itself, but the specific additions form drawboard not visible in the viewer.
Can you create an issue in the pdf-viewer repo at https://github.com/nextcloud/files_pdfviewer for this?

**Comment by Ninjiner** [comment]
I opened an issue there:
https://github.com/nextcloud/files_pdfviewer/issues/107
