### ISSUE TITLE
Alfresco WebDav server not usable with files_external

### ISSUE THREAD

**Issue by ebogaard** [nextcloud/server#1228]
### Steps to reproduce
1. Add [Alfresco 5.x](https://wiki.alfresco.com/wiki/Community_file_list_201605-GA) as webdav server to your personal account as external webdav-server
2. Try to access the External storage
3. See the error on screen
4. Check the webserver on the Alfresco server and see a number of 401's and 207's - see log at the bottom of this issue description.

If needed: please let me know if you need access to an Alfresco server to try the webdav-connection against
### Expected behaviour

I expect to see the files and folders available
### Actual behaviour

No files, just an error on screen:

```
No files in here
Upload some content or sync with your devices!
```
### Server configuration

**Operating system**: Centos 7

**Web server:** Httpd 2.4

**Database:** MariaDB

**PHP version:** 5.6.25

**Nextcloud version:** 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 9.0.5x

**Where did you install Nextcloud from:** Tarball

**Signing status:**
<details>
<summary>

Signing status</summary>

```
No problems
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.0
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - user_external
  - user_saml
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
Not really relevant in this case, I think.
```

</details>

**Are you using external storage, if yes which one:** try to use webdav.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No
### Client configuration

**Browser:** Firefox

**Operating system:** Windows 7 x64
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Nothing relevant, no errors
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
{"reqId":"V8f5dkjLjqE@i@JsEtQjBQAAAAo","remoteAddr":"IPADDR","app":"PHP","message":"Undefined index: {DAV:}status at \/var\/www\/html\/nextcloud-10.0.0\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#236","level":3,"time":"2016-09-01 11:48:38","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FExternTest","user":"ncadmin"}
{"reqId":"V8f5dkjLjqE@i@JsEtQjBQAAAAo","remoteAddr":"IPADDR","app":"PHP","message":"Undefined offset: 1 at \/var\/www\/html\/nextcloud-10.0.0\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#237","level":3,"time":"2016-09-01 11:48:38","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FExternTest","user":"ncadmin"}
{"reqId":"V8f5dkjLjqE@i@JsEtQjBQAAAAo","remoteAddr":"IPADDR","app":"PHP","message":"Undefined index: {DAV:}status at \/var\/www\/html\/nextcloud-10.0.0\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#236","level":3,"time":"2016-09-01 11:48:38","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FExternTest","user":"ncadmin"}
{"reqId":"V8f5dkjLjqE@i@JsEtQjBQAAAAo","remoteAddr":"IPADDR","app":"PHP","message":"Undefined offset: 1 at \/var\/www\/html\/nextcloud-10.0.0\/3rdparty\/sabre\/dav\/lib\/DAV\/Xml\/Element\/Response.php#237","level":3,"time":"2016-09-01 11:48:38","method":"GET","url":"\/index.php\/apps\/files\/ajax\/getstoragestats.php?dir=%2FExternTest","user":"ncadmin"}
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Nothing in the browser console
```

</details>
#### Alfresco log

```
IPADDR - - [01/Sep/2016:11:48:34 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 401 - "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:34 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 207 767 "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:35 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 401 - "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:35 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 207 767 "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:38 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 401 - "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:38 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 207 767 "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:38 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 401 - "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:38 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 207 767 "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:38 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 207 401 "-" "sabre-http/4.2.1 (http://sabre.io/)"
IPADDR - - [01/Sep/2016:11:48:38 +0200] "PROPFIND /alfresco/webdav/ HTTP/1.1" 207 401 "-" "sabre-http/4.2.1 (http://sabre.io/)"
```

**Comment by nickvergessen** [comment]
@icewind1991 any idea about that thing? Is it known for problems/to work?

**Comment by heaven73** [comment]
same behaviour on a webdav share on IIS tried to connect to as external storage on a fresh installation. The Webdav share can be reached by various davclients like cyberduck

**Comment by stunivention** [comment]
Similar to the behaviour I've seen while trying to add an OpenXchange Drive via webdav as external storage in Nextcloud 11.0.1.. Folders are partly visible, but no files. Uploaded files are not visible in Nextcloud, but in OX Drive.

**Comment by DanScharon** [comment]
This Alfresco issue may be related: https://issues.alfresco.com/jira/browse/MNT-9939?focusedCommentId=288101&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-288101

When I try to reproduce the testing with litmus it hence fails at 23. lock_shared (412 Precondition Failed). Alfresco passes all other tests.

**Comment by noci2012** [comment]
Using a local storage for alfresco defeats the pupose of using / authorizing people within Alfresco.

**Comment by pieter-groeneweg** [comment]
Unless you have some sso installed.. I can completely understand why one would want to use a bypass. 
Though Alfresco can have great workflows and using Activiti BPM can have added value, sharing is really lowsy. The methods of sharing files and folders within Alfresco is useless for a lot of users. One can only share full sites with users, no public sharing, no expiry dates, no.... 

There is very good reasons to bypass. 
But then again... asmentioned the CIFS/SMP/FTP in Alfresco doesn't even work properly.

**Comment by noci2012** [comment]
Nextcloud offers to remember per user passwords for a remote service
No SSO needed, or available. 
NextCloud 15.0.4 still cannot show content of folders using WebDav.

**Comment by kesselb** [comment]
You can use http://docs.alfresco.com/community/tasks/deploy-docker-compose.html to setup alfresco (without download around 5 minutes).

```
<?xml version="1.0" encoding="UTF-8"?>
<d:propfind xmlns:d="DAV:">
  <d:prop xmlns:x="http://owncloud.org/ns" xmlns:x1="http://open-collaboration-services.org/ns">
    <d:getlastmodified/>
    <d:getcontentlength/>
    <d:getcontenttype/>
    <x:permissions xmlns:x="http://owncloud.org/ns"/>
    <x1:share-permissions xmlns:x="http://open-collaboration-services.org/ns"/>
    <d:resourcetype/>
    <d:getetag/>
  </d:prop>
</d:propfind>
```

I can mount with nautilus but not nextcloud. Above is the response from alfresco.

**Comment by kesselb** [comment]
Did some more testing over here: https://github.com/nextcloud/server/issues/16471

**Comment by skjnldsv** [comment]
Let's move over there then
