### ISSUE TITLE
Lazy loading of files in grid view weird

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#12295]
The lazy loading in grid view looks weird for the initial load of the page because my screen can show at least 32 entries and it only shows 20 items. Then on the first scroll event loads the remaining ones to fill up the space.

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Right, so we probably need to increase a variable somewhere for the initial load to show more? @nextcloud/javascript

**Comment by MorrisJobke** [comment]
> Right, so we probably need to increase a variable somewhere for the initial load to show more? @nextcloud/javascript

Would be the naive approach at least. 😄
