### ISSUE TITLE
Provide linux distribution packages

### ISSUE THREAD

**Issue by CannyDuck** [nextcloud/server#123]
Please provide ready to deploy packages for Debian, Ubuntu, Fedora, RedHat Enterprise Linux, CentOS and openSUSE.

**Comment by MorrisJobke** [comment]
We have struggled with the packaging at ownCloud a lot. 

Let me cite @jospoortvliet from https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551/5:

> we don't have any plans of making packages ourselves (for now). It was a mess in the past, with quality issues and conflicts with the distributions. I hope they pick it up.

Previously we used OBS, which itself seems to be a lot of work to do from a maintainers perspective. 

Beside that I found https://packager.io/ which is also used by GitLab or Dokku for example and needs to be evaluated.

There is an interesting read about why upstream should not maintain packages (disclaimer: it is written by a downstream maintainer) http://kmkeen.com/maintainers-matter/

**Comment by tflidd** [comment]
From supporting users, I had the impression that there is no tolerance for problems and errors on the user side using a package manger. It has to be so reliable that it just works.

Therefore, I think it's a good decision to focus on the principle install/update/upgrade process to make it better and more reliable.

**Comment by davidreher** [comment]
Can you give any information on how to migrate from an owncloud package to a manual nextcloud install?

**Comment by derkostka** [comment]
@davidreher Here is what i did to migrate easily on Ubuntu 16.04:
Step 1: Backup 
Given your owncloud installation is  _"/var/www/owncloud"_, once approach is to backup your **config**: _"/var/www/owncloud/config"_, your **data folder** (if not moved to a separate location) : "/var/www/owncloud/data" and your **third-party-apps** from _"/var/www/owncloud/apps"_.

Now, uninstall owncloud: _"apt remove owncloud*"_

Step 2 Install Nextcloud:

-> If you want it clean, you install into /var/www/nextcloud. Then, you have to adjust the config and apache/ngnix paths also. If you copy files into /var/www/owncloud, you don´t have to change anything.

Download: https://download.nextcloud.com/server/daily/latest.tar.bz2 und deflate to "/var/www/**FOLDER**"

Copy back the files you just have backed up, as root, set the rights by typing _"chown -R www-data:www-data /var/www/"_

Now, you can either upgrade using occ or by opening your cloud url.


Did i miss anything ?

**Comment by MorrisJobke** [comment]
As stated above we for now don't plan to do packages. Therefore I close this here. If there is somebody to help out with packaging we would be more than happy to support the person :)

Thanks

**Comment by M4rtinK** [comment]
Then maybe the docs should be fixed to not point to non-existent OBS package repositories:

https://docs.nextcloud.org/server/9/admin_manual/maintenance/package_upgrade.html#id1

**Comment by MorrisJobke** [comment]
@M4rtinK Thanks for noticing. We already fixed this in the master version of the documentation, but forgot to port this to the stable9 branch. 

Ref https://github.com/nextcloud/documentation/pull/58

**Comment by seefood** [comment]
Howdie, long time user of the Debian OC packages, just found out today about the fork.
Can you at least offer some guide for people migrating from OC packages? should I stick to 8.2.7 till someone packs it, move to tarball as @derkostka mentioned above, or maybe a git clone and occasional pull? Any official or semi-official guide/recommendation will be helpful for more people to adopt this fork.

**Comment by jospoortvliet** [comment]
@seefood http://blog.jospoortvliet.com/2016/06/migrating-to-nextcloud-9.html is what you are looking for with regards to migration.

**Comment by seefood** [comment]
Thanks, I already improvised it and it survived the ordeal. not risking crypto yet, but that too will follow.

**Comment by sixtyfive** [comment]
Did any downstream packagers (Debian, etc.) comment on this, perhaps somewhere else?

**Comment by morph027** [comment]
Hm, just my really easy piece of private work (read: i'm using this):

https://morph027.gitlab.io/post/nextcloud-install-via-packages-on-jessie/

The git repo itself seems to have troubles right now, being displayed as empty). The APT repo has version 10.0.0 right now.

As easy as this can be built, as hard is to go further. The whole stack is really complicated to maintain (Gitlab can do, but they've got a dedicated team of release engineers ;)). The project should stick with good documentation and leave the rest to world out there.
