### ISSUE TITLE
OAuth 2.0 Client list breaks when secret is shown

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#12302]
![nov-06-2018 09-20-11](https://user-images.githubusercontent.com/19711361/48051413-4c414700-e1a5-11e8-8cbd-ef047f68a76a.gif)

We could fix this by not showing the secret and instead only provide a "copy secret to clipboard" link.

**Version:** Master
**Browser:** Firefox

@nextcloud/designers

**Comment by jancborchardt** [comment]
This already is too wide even just with the Client ID and the rest. And it looks like a very bland table.
We should check how others do it – here are examples from Twitter and Github:
![github oauth](https://user-images.githubusercontent.com/925062/48129459-d5ca4500-e289-11e8-8916-872c777eb6ae.png)
![twitter oauth](https://user-images.githubusercontent.com/925062/48129460-d5ca4500-e289-11e8-98a0-af1f8b0d2a51.png)

**Comment by rullzer** [comment]
Well our OAuth is the other way around. We are the server.
Also we can't show the icons since well we do not know.

Of course we could somehow improve here sure. But not for 16 I guess anymore.

**Comment by tcitworld** [comment]
> We could fix this by not showing the secret and instead only provide a "copy secret to clipboard" link.

Sorry to bump into this right now.

I have seen several users creating a token on their laptop to sign-in into DAVx5 for example, and typing it by hand, because they're not used to open Nextcloud into their mobile browser. Unless there's a better flow to create app tokens on mobile apps, I advise against this.

**Comment by rullzer** [comment]
@tcitworld this is not the same as the app password settiungs. Oauth is only for the admins
