### ISSUE TITLE
Upload size to external storage is limited over Webinterface

### ISSUE THREAD

**Issue by helmut72** [nextcloud/server#12305]
Users are not allowed to save files on Nextcloud machine, only on external storage. Therefore quota is set to 0.

### Steps to reproduce
1. Set quota to 0, add SMB external storage
2. Upload a file with more than 20MB with WebDAV -> ok
3. Upload a file with more than 20MB over Webinterface -> fail

### Expected behaviour
Upload a file with more than 20MB over Webinterface should also work.

### Actual behaviour
File won't be uploaded

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 14.0.3

**LDAP**: Yes, LDAP-only with ActiveDirectory, Quota configured in LDAP

**Info**: This works with Nextcloud 13.0.7, but not with 14.0.3

**Comment by MorrisJobke** [comment]
Duplicate of #11485

**Comment by MorrisJobke** [comment]
Fixed by https://github.com/nextcloud/server/pull/12022 and will be shipped in 14.0.4
