### ISSUE TITLE
can't see the warning about a wrong password when sharing by email

### ISSUE THREAD

**Issue by fifh** [nextcloud/server#12308]
### Steps to reproduce
1. click on the share button of a folder or file
2. enter an email address and click on "email (email)"
3. click on ... and "password protect"
4. enter a 4-character password (it must be forbidden)
5. click on the window next to the popup dialog related to the share parameters

### Expected behaviour
The user must be warned that the entered password is invalid

### Actual behaviour
The popup dialog is closed and the user doesn't know that the password is invalid, unless he clicks on... again

## Server configuration detail

**Operating system:** Linux 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.0.31

**PHP version:** 

7.0.22-0ubuntu0.16.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 13.0.4 - 13.0.4.0 (reproduced also with 13.0.6 and 14.0.3)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 12

**Where did you install Nextcloud from:** tar.gz from official site

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - activity: 2.6.1
 - admin_audit: 1.3.0
 - bruteforcesettings: 1.1.0
 - comments: 1.3.0
 - dav: 1.4.7
 - deck: 0.3.1
 - federatedfilesharing: 1.3.1
 - federation: 1.3.0
 - files: 1.8.0
 - files_antivirus: 1.2.0
 - files_downloadactivity: 1.2.0
 - files_pdfviewer: 1.2.1
 - files_sharing: 1.5.0
 - files_texteditor: 2.5.1
 - files_trashbin: 1.3.0
 - files_versions: 1.6.0
 - files_videoplayer: 1.2.0
 - firstrunwizard: 2.2.1
 - gallery: 18.0.0
 - impersonate: 1.0.4
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.1.0
 - nextcloud_announcements: 1.2.0
 - notifications: 2.1.2
 - oauth2: 1.1.1
 - password_policy: 1.3.0
 - provisioning_api: 1.3.0
 - richdocuments: 2.0.9
 - serverinfo: 1.3.0
 - sharebymail: 1.3.0
 - systemtags: 1.3.0
 - tasks: 0.9.6
 - theming: 1.4.5
 - twofactor_backupcodes: 1.2.3
 - updatenotification: 1.3.0
 - user_ldap: 1.3.1
 - workflowengine: 1.3.0
Disabled:
 - encryption
 - files_external
 - survey_client
 - user_external
 - user_saml

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "xxxxx"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxxxx",
    "dbtype": "mysql",
    "version": "13.0.4.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "logtimezone": "Europe\/Paris",
    "loglevel": 1,
    "log_rotate_size": 104857600,
    "cron_log": true,
    "updatechecker": false,
    "check_for_working_htaccess": true,
    "has_internet_connection": false,
    "check_for_working_wellknown_setup": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "session_keepalive": true,
    "session_lifetime": 86400,
    "remember_login_cookie_lifetime": 1296000,
    "quota_include_external_storage": false,
    "default_language": "fr",
    "enable_previews": true,
    "preview_max_filesize_image": 50,
    "skeletondirectory": "",
    "knowledgebaseenabled": true,
    "enable_avatars": true,
    "allow_user_to_change_display_name": true,
    "trashbin_retention_obligation": "20,40",
    "versions_retention_obligation": "auto,40",
    "activity_expire_days": 100,
    "mail_smtpmode": "smtp",
    "mail_smtpport": 25,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": true,
    "appstoreenabled": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "updater.release.channel": "production"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** ActiveDirectory

<details><summary>LDAP configuration (delete this par if not used)</summary>

```

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:62.0) Gecko/20100101 Firefox/62.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
no log
```
</details>

<details><summary>Nextcloud log</summary>

```
no Nextcloud log
```
</details>

<details><summary>Browser log</summary>

no log
</details>

**Comment by MorrisJobke** [comment]
Will be shipped in 14.0.5
