### ISSUE TITLE
app-bashsshclient

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#12304]
Hi,

could be nice if there a possible to connect inside of the Cloud 
with a account-listing to connect ssh-logins,
therewith could it also possible to enable a bash-instance to the local bash.
If example the user have a account on the local System and therewith also 
a direct connect to bash login.
And as extended a possible a ssh connection to different servers
for have a possible to working behind the cloud 
on the system (as example sudo to start services and administrate the system, use screen for have a multitasking in this bash and so on.., if as example if not start a ssh-server behind a warmboot, can this enable via app-bashsshclient instance from the Admin directly in this app-bashsshclient and later can the user again normal login in ssh/sftp )

So a app to have a local bash and ssh-login(listing for other servers) for have the possible to administrating the system over Web via prompt. 

May interesting and as suggestion for info
http://php.net/manual/function.ssh2-connect.php //for have a ssh-connection in a iframe
http://php.net/manual/function.shell-exec.php  //for start a local bash-instance in a iframe with Login(name/pw)maybe or directly administrate the nextcloud via php console.php or occ ..
with this app ..

best regards
Blacky

**Comment by violoncelloch** [comment]
I don't think this makes sense, you can use a normal ssh connection to your server anyways. And it would be very critical in terms of security. 
Also I don't think it's the main focus of nextcloud, however you could implement it as an app, if it's possible with the referenced php lib.
What do you think @nextcloud/security ?

**Comment by rullzer** [comment]
Yes this is not something we'd want. This will all run as the same user that access the files. Thus allowing access to all the files on your nextcloud (of all users). On top of that you connection will most likely be killed often as the php process is terminated.
