### ISSUE TITLE
Activity Notification E-Mail is missing Path

### ISSUE THREAD

**Issue by neoprogger** [nextcloud/server#12309]
Hi,
Since V 14. the default notification E-Mail has changed.
With V13 the Mail contained the full path to each file changed

e.g. : Yesterday 17:27 Mister Name hast changed Folder1/Folder2/File.ext

now it's just
Yesterday 17:27 Mister Name has changed File.ext

Our Partners have more than just one file named "EG_PlanXX.pdf" and would like to know in wich Project it changed without opening the link.

Is the old behaviour still configurable?

**Comment by MorrisJobke** [comment]
cc @nickvergessen
