### ISSUE TITLE
User Management: Make "Display Name" for LDAP-Users non-editable

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#12319]
### Steps to reproduce
1. Login to Nextcloud as Administrator, go to Users
2. Try to change name of LDAP Users

### Expected behaviour
Field is read-only or not readable at all (just a string).
This may apply to other forms of external authentication also (e.g. OAuth, not tested).

### Actual behaviour
You can type in a new display name. 
Information seems to be not saved, on next page reload, old name apperars.

### Server configuration

**Nextcloud version:** 14.0.3

**Comment by MorrisJobke** [comment]
cc @nextcloud/ldap

**Comment by blizzz** [comment]
Our OCS user endpoint returns the backend string per user, but not the backends capabilities. We'd need to extend this first, and then deal with those values in the user settings frontend. cc @skjnldsv

**Comment by blizzz** [comment]
→ to be shipped with Beta **2**
