### ISSUE TITLE
locale error after updating debian-testing

### ISSUE THREAD

**Issue by mer-at** [nextcloud/server#12318]
### Steps to reproduce
install nextcloud 14.3 on debian testing
open a webbrowser

### Expected behaviour
login page should display properly

### Actual behaviour
error is shown:
Setting locale to en_US.UTF-8/fr_FR.UTF-8/es_ES.UTF-8/de_DE.UTF-8/ru_RU.UTF-8/pt_BR.UTF-8/it_IT.UTF-8/ja_JP.UTF-8/zh_CN.UTF-8 failed

Please install one of these locales on your system and restart your webserver.

### Server configuration

**Operating system**:
debian testing

**Web server:**
apache2 2.4.37-1
locales 2.27-8

**Database:**
postgresql     11+194

**PHP version:**
php7.3 7.3.0~rc4-1

**Nextcloud version:** (see Nextcloud admin page)
14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
no, 14.0.3 was already running on this machine.
only updated some system packages, including "locales" package

**Where did you install Nextcloud from:**
downloaded the zip from nextcloud.com
updated since nextcloud 11 if i remember correctly

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
unable to login
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
$ php occ app:list
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap


</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
~/owncloud$ php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "localhost",
            "192.168.123.1",
            "sunnydale.servebeer.com",
            "sunnydale.russenmafia.at",
            "sunnydale.servebeer.com"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updatechecker": false,
        "htaccess.RewriteBase": "\/owncloud",
        "overwrite.cli.url": "\/owncloud",
        "appstore.experimental.enabled": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ]
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

there are absolutely no error messages. even on loglevel "debug" there are none.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
that one is empty too!!!
</details>

**Comment by mer-at** [comment]
these are the available locales for user www-data:

www-data@sunnyserver:~$ whoami
www-data
www-data@sunnyserver:~$ locale -a
aa_DJ
aa_DJ.utf8
aa_ER
aa_ER@saaho
aa_ET
af_ZA
af_ZA.utf8
agr_PE
ak_GH
am_ET
an_ES
an_ES.utf8
anp_IN
ar_AE
ar_AE.utf8
ar_BH
ar_BH.utf8
ar_DZ
ar_DZ.utf8
ar_EG
ar_EG.utf8
ar_IN
ar_IQ
ar_IQ.utf8
ar_JO
ar_JO.utf8
ar_KW
ar_KW.utf8
ar_LB
ar_LB.utf8
ar_LY
ar_LY.utf8
ar_MA
ar_MA.utf8
ar_OM
ar_OM.utf8
ar_QA
ar_QA.utf8
ar_SA
ar_SA.utf8
ar_SD
ar_SD.utf8
ar_SS
ar_SY
ar_SY.utf8
ar_TN
ar_TN.utf8
ar_YE
ar_YE.utf8
as_IN
ast_ES
ast_ES.utf8
ayc_PE
az_AZ
az_IR
be_BY
be_BY@latin
be_BY.utf8
bem_ZM
ber_DZ
ber_MA
bg_BG
bg_BG.utf8
bhb_IN.utf8
bho_IN
bho_NP
bi_VU
bn_BD
bn_IN
bo_CN
bo_IN
br_FR
br_FR@euro
br_FR.utf8
brx_IN
bs_BA
bs_BA.utf8
byn_ER
C
ca_AD
ca_AD.utf8
ca_ES
ca_ES@euro
ca_ES.utf8
ca_ES@valencia
ca_FR
ca_FR.utf8
ca_IT
ca_IT.utf8
ce_RU
chr_US
cmn_TW
crh_UA
csb_PL
cs_CZ
cs_CZ.utf8
C.UTF-8
cv_RU
cy_GB
cy_GB.utf8
da_DK
da_DK.utf8
de_AT
de_AT@euro
de_AT.utf8
de_BE
de_BE@euro
de_BE.utf8
de_CH
de_CH.utf8
de_DE
de_DE@euro
de_DE.utf8
de_IT
de_IT.utf8
de_LI.utf8
de_LU
de_LU@euro
de_LU.utf8
doi_IN
dv_MV
dz_BT
el_CY
el_CY.utf8
el_GR
el_GR@euro
el_GR.utf8
en_AG
en_AU
en_AU.utf8
en_BW
en_BW.utf8
en_CA
en_CA.utf8
en_DK
en_DK.iso885915
en_DK.utf8
en_GB
en_GB.iso885915
en_GB.utf8
en_HK
en_HK.utf8
en_IE
en_IE@euro
en_IE.utf8
en_IL
en_IN
en_NG
en_NZ
en_NZ.utf8
en_PH
en_PH.utf8
en_SC.utf8
en_SG
en_SG.utf8
en_US
en_US.iso885915
en_US.utf8
en_ZA
en_ZA.utf8
en_ZM
en_ZW
en_ZW.utf8
eo
es_AR
es_AR.utf8
es_BO
es_BO.utf8
es_CL
es_CL.utf8
es_CO
es_CO.utf8
es_CR
es_CR.utf8
es_CU
es_DO
es_DO.utf8
es_EC
es_EC.utf8
es_ES
es_ES@euro
es_ES.utf8
es_GT
es_GT.utf8
es_HN
es_HN.utf8
es_MX
es_MX.utf8
es_NI
es_NI.utf8
es_PA
es_PA.utf8
es_PE
es_PE.utf8
es_PR
es_PR.utf8
es_PY
es_PY.utf8
es_SV
es_SV.utf8
es_US
es_US.utf8
es_UY
es_UY.utf8
es_VE
es_VE.utf8
et_EE
et_EE.iso885915
et_EE.utf8
eu_ES
eu_ES@euro
eu_ES.utf8
eu_FR
eu_FR@euro
eu_FR.utf8
fa_IR
ff_SN
fi_FI
fi_FI@euro
fi_FI.utf8
fil_PH
fo_FO
fo_FO.utf8
fr_BE
fr_BE@euro
fr_BE.utf8
fr_CA
fr_CA.utf8
fr_CH
fr_CH.utf8
fr_FR
fr_FR@euro
fr_FR.utf8
fr_LU
fr_LU@euro
fr_LU.utf8
fur_IT
fy_DE
fy_NL
ga_IE
ga_IE@euro
ga_IE.utf8
gd_GB
gd_GB.utf8
gez_ER
gez_ER@abegede
gez_ET
gez_ET@abegede
gl_ES
gl_ES@euro
gl_ES.utf8
gu_IN
gv_GB
gv_GB.utf8
hak_TW
ha_NG
he_IL
he_IL.utf8
hif_FJ
hi_IN
hne_IN
hr_HR
hr_HR.utf8
hsb_DE
hsb_DE.utf8
ht_HT
hu_HU
hu_HU.utf8
hy_AM
hy_AM.armscii8
ia_FR
id_ID
id_ID.utf8
ig_NG
ik_CA
is_IS
is_IS.utf8
it_CH
it_CH.utf8
it_IT
it_IT@euro
it_IT.utf8
iu_CA
ja_JP.eucjp
ja_JP.utf8
kab_DZ
ka_GE
ka_GE.utf8
kk_KZ
kk_KZ.rk1048
kk_KZ.utf8
kl_GL
kl_GL.utf8
km_KH
kn_IN
kok_IN
ko_KR.euckr
ko_KR.utf8
ks_IN
ks_IN@devanagari
ku_TR
ku_TR.utf8
kw_GB
kw_GB.utf8
ky_KG
lb_LU
lg_UG
lg_UG.utf8
li_BE
lij_IT
li_NL
ln_CD
lo_LA
lt_LT
lt_LT.utf8
lv_LV
lv_LV.utf8
lzh_TW
mag_IN
mai_IN
mai_NP
mfe_MU
mg_MG
mg_MG.utf8
mhr_RU
mi_NZ
mi_NZ.utf8
miq_NI
mjw_IN
mk_MK
mk_MK.utf8
ml_IN
mni_IN
mn_MN
mr_IN
ms_MY
ms_MY.utf8
mt_MT
mt_MT.utf8
my_MM
nan_TW
nan_TW@latin
nb_NO
nb_NO.utf8
nds_DE
nds_NL
ne_NP
nhn_MX
niu_NU
niu_NZ
nl_AW
nl_BE
nl_BE@euro
nl_BE.utf8
nl_NL
nl_NL@euro
nl_NL.utf8
nn_NO
nn_NO.utf8
nr_ZA
nso_ZA
oc_FR
oc_FR.utf8
om_ET
om_KE
om_KE.utf8
or_IN
os_RU
pa_IN
pap_AW
pap_CW
pa_PK
pl_PL
pl_PL.utf8
POSIX
ps_AF
pt_BR
pt_BR.utf8
pt_PT
pt_PT@euro
pt_PT.utf8
quz_PE
raj_IN
ro_RO
ro_RO.utf8
ru_RU
ru_RU.cp1251
ru_RU.koi8r
ru_RU.utf8
ru_UA
ru_UA.utf8
rw_RW
sa_IN
sat_IN
sc_IT
sd_IN
sd_IN@devanagari
se_NO
sgs_LT
shn_MM
shs_CA
sid_ET
si_LK
sk_SK
sk_SK.utf8
sl_SI
sl_SI.utf8
sm_WS
so_DJ
so_DJ.utf8
so_ET
so_KE
so_KE.utf8
so_SO
so_SO.utf8
sq_AL
sq_AL.utf8
sq_MK
sr_ME
sr_RS
sr_RS@latin
ss_ZA
st_ZA
st_ZA.utf8
sv_FI
sv_FI@euro
sv_FI.utf8
sv_SE
sv_SE.iso885915
sv_SE.utf8
sw_KE
sw_TZ
szl_PL
ta_IN
ta_LK
tcy_IN.utf8
te_IN
tg_TJ
tg_TJ.utf8
the_NP
th_TH
th_TH.utf8
ti_ER
ti_ET
tig_ER
tk_TM
tl_PH
tl_PH.utf8
tn_ZA
to_TO
tpi_PG
tr_CY
tr_CY.utf8
tr_TR
tr_TR.utf8
ts_ZA
tt_RU
tt_RU@iqtelif
ug_CN
uk_UA
uk_UA.utf8
unm_US
ur_IN
ur_PK
uz_UZ
uz_UZ@cyrillic
uz_UZ.utf8
ve_ZA
vi_VN
wa_BE
wa_BE@euro
wa_BE.utf8
wae_CH
wal_ET
wo_SN
xh_ZA
xh_ZA.utf8
yi_US
yi_US.utf8
yo_NG
yue_HK
yuw_PG
zh_CN
zh_CN.gb18030
zh_CN.gbk
zh_CN.utf8
zh_HK
zh_HK.utf8
zh_SG
zh_SG.gbk
zh_SG.utf8
zh_TW
zh_TW.euctw
zh_TW.utf8
zu_ZA
zu_ZA.utf8

**Comment by mer-at** [comment]
too bad you didn't read anything. i clearly stated, that nothing on the setup changed, yet nextcloud stopped working.

it's especially rich coming from devs, that use this test:
        if ('' === basename('§'))
to determine that setting the locale worked.
i removed this test and my nextcloud works fine again.

I suggest you update your code to work on new systems as well

**Comment by MorrisJobke** [comment]
> too bad you didn't read anything. i clearly stated, that nothing on the setup changed, yet nextcloud stopped working.

I actually read that and it still looked like something under the hood changed.

I double checked with the could you supplied and this seems to be indeed the problem.

Let me look into that.

**Comment by MorrisJobke** [comment]
This whole construct seems to originate in here:

https://github.com/nextcloud/3rdparty/blob/89258b827344d3a5e590910b01b51fa25047030f/patchwork/utf8/src/Patchwork/Utf8/Bootup.php#L126-L130

**Comment by mer-at** [comment]
there's this **default** setting in Debian Buster: 
/etc/apache2/envvars
```
## The locale used by some modules like mod_dav
export LANG=C
## Uncomment the following line to use the system default locale instead:
#. /etc/default/locale

export LANG
```

my /etc/default/locale contains LANG=en_US.UTF-8
therefor i uncommented the line in envvars, restarted the apache2, and now nextcloud 14 is loading normally, even with the check i earlier removed.

**Comment by danielkesselberg** [comment]
https://salsa.debian.org/apache-team/apache2/commit/242822d17e19cdf61f97fa78819c26e660edc316 I suppose something with `setlocale` does not work maybe related to PHP 7.3.

**Comment by MorrisJobke** [comment]
> Outputs string(0) "" string(0) "".

That is the wanted output.

**Comment by mer-at** [comment]
Are you sure? Because when i set apache2's LANG to en_US-utf8, it displays:
`string(2)` "§" string(2) "§"`

**Comment by stweil** [comment]
@MorrisJobke, the wanted output is

    $ LANG=C php test.php
    string(0) ""
    string(2) "§"

I got this issue after a partial upgrade from Debian stretch to Debian buster. Nextcloud 15 still worked after the upgrade of the PHP packages, but failed later after I had upgraded more packages. The workaround with modifying `/etc/apache2/envvars` works, but I'm still searching the real cause of that problem.

**Comment by stweil** [comment]
The problem might be related to a known [bug in Debian package php-apcu-bc (bug 909752)](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=909752): Nextcloud had shown errors loading `acp.so` after I applied the above workaround. I fixed the load order for pcp-apcu-bc. This fixed the error messages for `acp.so`. Then I removed the locale workaround, and Nextcloud still worked as expected.

**Comment by ieleja** [comment]
Debian Buster, up to date
`$ sudo -u www-data locale -a | grep en_US.utf8

en_US.utf8
`

ever upgrade produce this error:

> Setting locale to en_US.UTF-8/fr_FR.UTF-8/es_ES.UTF-8/de_DE.UTF-8/ru_RU.UTF-8/pt_BR.UTF-8/it_IT.UTF-8/ja_JP.UTF-8/zh_CN.UTF-8 failed 

fix is easy, but somewhat brutal and frustrating -
$nexcloudwebfolder/lib/private/legacy/util.php
 add at 1285. row 'return true;'
`        public static function isSetLocaleWorking() {
                \Patchwork\Utf8\Bootup::initLocale();
                if ('' === basename('§')) {
                        return false;
                }
                return true;
        }`

to

`        public static function isSetLocaleWorking() {
                \Patchwork\Utf8\Bootup::initLocale();
                if ('' === basename('§')) {
                        return true;
                        return false;
                }
                return true;
        }`

**Comment by kesselb** [comment]
I believe that changing to code to return true instead of false is not a fix. I'm going to hide your comment to protect other users from that untested workaround. Please try to configure your system properly as discussed earlier in this issue.

**Comment by skjnldsv** [comment]
Closing please configure the os properly :)

**Comment by kakhavk** [comment]
In Fedora I found that problem can be solved by adding LC_TYPE variable to /usr/lib/systemd/system/httpd.service

```
[Service]
...
Environment=LC_CTYPE=en_US.UTF-8
```

After run command 
```
systemctl daemon-reload
service httpd restart
```

**Comment by nailyk-fr** [comment]
Hello, 

Just had the same issue after migrating from Devuan Ascii to Beowulf and Nextcloud 15 to 20.
Just my two cents, this looks like a case issue : 
nextcloud : 
`en_US.UTF-8/fr_FR.UTF-8`
_vs_
Devuan : 
```
$ sudo -u www-data locale -a
C
C.UTF-8
fr_FR.utf8
```

One is uppercase, the other is not. Just my two cents. 

@mer-at workaround : 
>  therefor i uncommented the line in envvars, restarted the apache2, and now nextcloud 14 is loading normally, even with the check i earlier removed.

(Uncomment the import of /etc/default/locales in apache2 configuration)
fixed it for now. 


Thanks all !

**Comment by Vitexus** [comment]
> In Fedora I found that problem can be solved by adding LC_TYPE variable to /usr/lib/systemd/system/httpd.service
> 
> ```
> [Service]
> ...
> Environment=LC_CTYPE=en_US.UTF-8
> ```
> 
> After run command
> 
> ```
> systemctl daemon-reload
> service httpd restart
> ```
It also help me on Debian Buster

```shell
nano /lib/systemd/system/apache2.service
systemctl daemon-reload
systemctl restart apache2.service
```
