### ISSUE TITLE
datepicker: fast switching between years

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#12323]
I'm reporting this on server because what I've read from other issues is that the picker itself is provided by server, no matter where it is used (e.g. calendar, contacts).

### Expected behaviour
Add a possibility to switch the year fast. Here are two examples from a quick search on google images how this could be achieved:
![ex_date_picker_sample](https://user-images.githubusercontent.com/42836313/48097347-f8247a00-e219-11e8-9f67-09940b8b68b8.png)
![date-picker](https://user-images.githubusercontent.com/42836313/48097350-fbb80100-e219-11e8-9872-3a1499382528.png)

### Actual behaviour
In current date picker, scrolling is only possible per month. This is not user friendly when dates in the far past or future must be picked. For example, even picking the same date a year from now needs 12 mouse clicks.

### Server configuration

**Nextcloud version:** 14.0.3

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Let's close then :)

**Comment by SiL3NC3** [comment]
Year picker missing again...
