### ISSUE TITLE
PHP coding style

### ISSUE THREAD

**Issue by danopz** [nextcloud/server#12325]
I am curious if there is still any reason still to go with the PEAR coding standard?
This standard seems not maintained anymore and so there is no standard for new PHP syntax.

Are you still using it because of the mass of code or just prefer the PEAR one over the de facto PSR standards?

**Comment by MorrisJobke** [comment]
> Are you still using it because of the mass of code or just prefer the PEAR one over the de facto PSR standards?

I guess we just sticked to what is in place right now, because changing the whole style of everything makes "git research via git blame" just unnecessarily harder.

@rullzer @blizzz @nickvergessen @icewind1991 Opinions?

**Comment by blizzz** [comment]
I agree with @MorrisJobke. I don't see the need to change it.

**Comment by ChristophWurst** [comment]
Closing as we won't change the coding style in the foreseeable future.
