### ISSUE TITLE
Autocomplete/get needs pagination

### ISSUE THREAD

**Issue by mario** [nextcloud/server#12322]

**Comment by MorrisJobke** [comment]
@mario A little bit more detail would be awesome. I extrapolate you are talking about an OCS API endpoint, right?

**Comment by MorrisJobke** [comment]
cc @blizzz @nickvergessen @rullzer

**Comment by mario** [comment]
@MorrisJobke apologies for the short issue. Indeed, I'm talking about the ocs endpoint that goes by /autocomplete/get which currently only has limit and lacks real pagination.

@nickvergessen maybe wants to take a different approach to this in the client (e.g. not show all users at all, but only when you filter) so if that's the general consensus, feel free to close the issue.

**Comment by blizzz** [comment]
@mario yes, I did not include pagination intentionally. Do you have a use case? If the results are too many, perhaps the search was not specific enough? The purpose was auto-completing, not listing.

**Comment by mario** [comment]
@blizzz @rullzer I understand. In some of the Nc14 installations (I haven't been able to debug this further) the sharing API would return no contacts - this worked prior to 14. 

Switching to autocomplete endpoint solves the problem, but like I said - I can't paginate which is ... problematic :)

**Comment by mario** [comment]
Like I said - you know more about this stuff. Feel free to close if it doesn't make sense.

**Comment by nickvergessen** [comment]
Yeah as the data comes from multiple providers I think it's too complicated to do a proper pagination which is not "get all into an array and then array_slice".
So I don't see this happening.

**Comment by MorrisJobke** [comment]
> Yeah as the data comes from multiple providers I think it's too complicated to do a proper pagination which is not "get all into an array and then array_slice".
> So I don't see this happening.

But isn't this fine? #10880 does it as well. 🤔

**Comment by blizzz** [comment]
We also do it on the user management page. The pagination works per backend. If you have three user sources and request 10 of page 3, you'll get up to 30 results. That's the only reliable way, but it works. 

The question is rather whether we want offer expose an easy way of numerating users to (unauthed?) users.
