### ISSUE TITLE
Cannot upload big files over public shared link

### ISSUE THREAD

**Issue by 0xnor0** [nextcloud/server#12321]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. create a public shared folder with write permissions
2. try to upload a file with a size of 3,5GB
3. wait until the upload should be finishe

### Expected behaviour
The file is accessible through the nextcloud after the upload is finished

### Actual behaviour
no files are in the nextcloud-folder
-> in the temp-folder of the webserver, there grows the php-temp-file until the upload stops 

Server configuration

Operating system: CentOS 7.5
Web server: Apache 2.4
Database: MariaDB
PHP version: PHP 7.2.10
Server version: 14.0.3
Calendar version: 1.6.3

Login as admin user into your cloud and access
http://example.com/index.php/settings/integrity/failed
paste the results here.
`No errors have been found.`

List of activated apps:

Enabled:
  - activity: 2.7.0
  - bookmarks: 0.13.1
  - bruteforcesettings: 1.1.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - contacts: 2.1.6
  - dav: 1.6.0
  - drop_account: 0.0.12
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_automatedtagging: 1.4.0
  - files_downloadactivity: 1.3.0
  - files_pdfviewer: 1.3.2
  - files_retention: 1.3.0
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trackdownloads: 1.3.1
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - lookup_server_connector: 1.2.0
  - metadata: 0.7.0
  - news: 13.0.2
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - accessibility
  - admin_audit
  - admin_notifications
  - announcementcenter
  - checksum
  - comments
  - data_request
  - deck
  - drawio
  - federation
  - files_accesscontrol
  - files_external
  - groupfolders
  - logreader
  - mindmaps
  - radio
  - socialsharing_email
  - spreed
  - support
  - survey_client
  - systemtags
  - twofactor_totp
  - user_external
  - user_ldap

Nextcloud configuration:

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "",
            ""
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/\/",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "updater.release.channel": "stable",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "log_type": "owncloud",
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": 0,
        "logdateformat": "F d, Y H:i:s",
        "maintenance": false,
        "theme": "",
        "trashbin_retention_obligation": "auto, 5",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

Are you using external storage, if yes which one: no
Are you using encryption: yes
Are you using an external user-backend, if yes which one: no
Client configuration

Browser: Firefox 62.0.3
Operating system: Windows 10 Pro

CalDAV-clients:
DAVdroid & ICSdroid
Logs
Web server error log

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
==> /var/log/nextcloud.log <==
`{"reqId":"W@Hc8kHq-SSq8mQmCaM73AAAAAU","level":0,"time":"November` 06, 2018 21:10:18","remoteAddr":"95.90.203.142","user":"--","app":"no app in context","method":"PUT","url":"\/public.php\/webdav\/Abistreich.mpg","message":"No cache entry found for \/ole\/files\/Abivideos\/Abistreich.mpg (storage: home::ole, internalPath: files\/Abivideos\/Abistreich.mpg)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"W@Hc8kHq-SSq8mQmCaM73AAAAAU","level":0,"time":"November 06, 2018 21:10:18","remoteAddr":"95.90.203.142","user":"--","app":"no app in context","method":"PUT","url":"\/public.php\/webdav\/Abistreich.mpg","message":"No cache entry found for \/ole\/files\/Abivideos\/Abistreich.mpg (storage: home::ole, internalPath: files\/Abivideos\/Abistreich.mpg)","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"W@Hc8kHq-SSq8mQmCaM73AAAAAU","level":3,"time":"November 06, 2018 21:10:18","remoteAddr":"95.90.203.142","user":"--","app":"no app in context","method":"PUT","url":"\/public.php\/webdav\/Abistreich.mpg","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/06139e8b7c50b76def78ae786be7276a\" is locked, existing lock on file: none","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":777,"function":"changeLock","class":"OC\\Lock\\MemcacheLockingProvider","type":"->","args":["files\/06139e8b7c50b76def78ae786be7276a",2]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","line":1964,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Node.php","line":359,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/Abistreich.mpg",2]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":210,"function":"changeLock","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":[2]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["Abistreich.mpg",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["Abistreich.mpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php","line":107,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/public.php","line":78,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Lock\/MemcacheLockingProvider.php","Line":129,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"}
{"reqId":"W@Hc8kHq-SSq8mQmCaM73AAAAAU","level":4,"time":"November 06, 2018 21:10:18","remoteAddr":"95.90.203.142","user":"--","app":"webdav","method":"PUT","url":"\/public.php\/webdav\/Abistreich.mpg","message":{"Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Message":"\"Abivideos\/Abistreich.mpg\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["Abistreich.mpg",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["Abistreich.mpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php","line":107,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/public.php","line":78,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":215,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"Abivideos\/Abistreich.mpg\" is locked","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Node.php","line":359,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/Abistreich.mpg",2]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":210,"function":"changeLock","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":[2]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["Abistreich.mpg",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["Abistreich.mpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php","line":107,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/public.php","line":78,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","Line":1970,"Previous":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/06139e8b7c50b76def78ae786be7276a\" is locked, existing lock on file: none","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":777,"function":"changeLock","class":"OC\\Lock\\MemcacheLockingProvider","type":"->","args":["files\/06139e8b7c50b76def78ae786be7276a",2]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":614,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","line":1964,"function":"changeLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["files\/Abivideos\/Abistreich.mpg",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Node.php","line":359,"function":"changeLock","class":"OC\\Files\\View","type":"->","args":["\/Abistreich.mpg",2]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","line":210,"function":"changeLock","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":[2]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["Abistreich.mpg",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":529,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["Abistreich.mpg",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.oleroesler.de\/public.php\/webdav\/Abistreich.mpg","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php","line":107,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/public.php","line":78,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/publicwebdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Lock\/MemcacheLockingProvider.php","Line":129}},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":"14.0.3.0"} `

`==> /var/log/httpd/access_log <==
95.90.203.142 - w25mJ5DQFBdA7tH [06/Nov/2018:19:26:58 +0100] "PUT /public.php/webdav/Abistreich.mpg HTTP/1.1" 423 244 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"
84.182.182.116 - ole [06/Nov/2018:21:10:23 +0100] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
84.182.182.116 - ole [06/Nov/2018:21:10:23 +0100] "PROPFIND /remote.php/dav/files/ole/ HTTP/1.1" 207 364 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
::1 - - [06/Nov/2018:21:10:28 +0100] "OPTIONS * HTTP/1.0" 200 - "-" "Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.10 (internal dummy connection)"
84.182.182.116 - ole [06/Nov/2018:21:10:53 +0100] "PROPFIND /remote.php/dav/files/ole/ HTTP/1.1" 207 364 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
84.182.182.116 - - [06/Nov/2018:21:11:00 +0100] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0"`

**Comment by creopard** [comment]
Until a solution is found for your issue, you could upload the file via FTP in the meantime and run the following command from the command line:

> sudo -u www-data php occ files:scan --all

**Comment by jospoortvliet** [comment]
Sorry, I just tested and this works fine in my local Nextcloud 16.0.1 here and no other users have clearly experienced the same problem so it must be a configuration issue on your side. Or, it has already been fixed - I suggest you update from Nextcloud 14.0.x to 15.0.x and 16.0.x if you haven't already. For help with configuration issues, please check help.nextcloud.com for private use and nextcloud.com/enterprise for business support.

**Comment by martin-rueegg** [comment]
Hi @jospoortvliet 

I just came across this issue and had the very same Symptoms as described by @0xnor0. I'm running NC v16.0.5.

What I have discovered is, that the upload works fine to the very same folder, when I'm logged in. However, when using a private browser session and the public shared link with upload option, then It does not work. Also, the two ways do upload the file distinct significantly!

When uploading logged-in, the file is sent in chunks of 10MB to the following URL:
`/remote.php/dav/uploads/{user}/web-file-upload-079828e8c1d254f98d8b73d8304dbd80-1571255990916/188743680`

However, when uploading from the public upload-enabled link, then the _entire_ file is sent in one single PUT request:
`/public.php/webdav/filename.ext`

Therefore, the maximum client-side post limit is reached (e.g. client_max_body_size for nginx) and the request never even hits PHP or NC but is refused by the web server. Increasing this limit, enables the upload. However, an upload size of 3.5GB is not necessarily the best option and not available from many hosting providers.

That this is a common use case has been documented [here](https://help.nextcloud.com/t/create-client-side-upload-tool-for-anonymous-upload/12184/11) and [here](https://github.com/owncloud/client/issues/3938) (and other places).

So an approach to the solution would be to use the same upload component (or at least approach) of the web interface for public shared links as it is used in the regular logged-in state.

It it is considered a bug or feature request, I don't know. Probably more the latter. However, it would be cool if the web client could give a better error message. Which would be easy, given that the server returns a http status code of _413 Payload Too Large_.

But given that it _is_ indeed a common use case, it would be much better than the suggested approach of creating a common user for third parties.

Thanks,
Martin.

**Comment by jospoortvliet** [comment]
Hi @martin-rueegg 
Thanks for the analysis, I wasn't aware that the public upload link uses a different mechanism, though I've heard engineers refer to this I think.

It might be fixed now (in 17) as I just tried to upload a 2.5gb file in a public link share in an anonymous browsing window without issues ;-)

**Comment by martin-rueegg** [comment]
Hi @jospoortvliet 

I've just tested on my v16 NC and it uploaded the file as one single PUT. Then I've updated to v17.0.1 and reloaded the window and restarted the upload. And it was still uploaded as a single PUT request, and not sliced into 10MB chunks. So the behaviour in v17 is still as described in https://github.com/nextcloud/server/issues/12321#issuecomment-542886827

So I assume that you have configured your server do deal with 2.5GB+ requests. Which would be in line with your https://github.com/nextcloud/server/issues/12321#issuecomment-535506148 saying that it is a configuration issue. So in order to test the issue, you need to configure your server to not allow these big requests. Or you simply check if your browser posts to
`/public.php/webdav/filename.ext` as one PUT request, or to
`/remote.php/dav/uploads/{user}/web-file-upload-{some hex}-{some digits}/{some more digits}` as multiple 10MB PUT requests. You can see that either in the access-log of the server or in the browser's network console (F12 -> Network).

Cheers,
Martin.

**Comment by martin-rueegg** [comment]
Thank you, @kesselb, for reopening the case. Much appreciated.

If you need further information, please let me know.

**Comment by kesselb** [comment]
I updated the labels of this issue. They are now the same as #4109.

**Comment by Tutolex** [comment]
Hi ! I have the same issue meaning I can upload large files on the folder when I am connected but when I log out and try to upload on the public link then it fails with "an unknown error occured".
I wanted to create a shared folder for all my friends to share large videos.

**Comment by apeltauer** [comment]
I am facing the same problem. Uploading big files (over 1GB) while logged in as a user works fine. If i want to upload a the same file over a shared link as guest (not logged in) i get the same error message and the uploads stops immediately.
My version:
Nextcloud 19.0.0

**Comment by xylo** [comment]
Any news on this?  NC 19 is still affected. :cry:

**Comment by smd0709** [comment]
Do we know anything about this?
In version 20.0.2 it is not fixed.
Tkanks!

**Comment by TechGeeksIO** [comment]
Still not fixed in 20.0.7, any news? Upload via shared links with bigger files are not working!

**Comment by Scyten** [comment]
Having same issue here. If I am logged in (direct upload) it works. From shared link it does not work. It's the hole file vs chunks problem. If the normal upload code is reusable it should be a easy fix.

**Comment by kesselb** [comment]
> Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

@xylo @smd0709 @TechGeeksIO @Scyten
