### ISSUE TITLE
Nextcloud 14.0.3 support php 7.3?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#12333]
I would like to upgrade my PHP 7.0 raspbian to PHP 7.3 with the deb.sury.org package. I wanted to ask if it was appropriate to update to php7.2 or can you tell me if nextcloud in version 14.0.3 already supports PHP 7.3? specifically php7.3 armhf

**Comment by timm2k** [comment]
Nextcloud 14.0.4 should been tested against PHP 7.3 (PR #11790).

**Comment by MorrisJobke** [comment]
Nextcloud 14 runs officially on PHP 7.0, 7.1 and 7.2 - see https://docs.nextcloud.com/server/14/admin_manual/installation/system_requirements.html

We will not bring support for newer versions of PHP to existing major versions. Nextcloud 15 (to be released in December) will bring PHP 7.3 support.
