### ISSUE TITLE
OS X Mojave 10.14 ICal caldav sync fails

### ISSUE THREAD

**Issue by deisi** [nextcloud/server#12344]
### Steps to reproduce
1.Configure everything to work under OSX 10.13
2. Update to OSX 10.14

### Expected behaviour
Tell us what should happen
Had a working iCal sync before and after the update it is not working any more.
It fails saying that it can't validate the username and password.
Proem seems to be simar to:  
https://github.com/nextcloud/server/issues/7519
however it was working before with the settings mentioned in the thread.
There is also a thread at the apple forum where people think it's iCal itself but nobody knows for sure jet, so I put this here for visibility purpose.
https://discussions.apple.com/thread/8563910

### Server configuration

**Operating system**:
Ubuntu 18.04 vm
**Web server:**
Apache
**Database:**
Mariadb
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
13
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Default VM
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by deisi** [comment]
hey, I kind of realized the same. I now moved my clients to https and it works.

**Comment by uwealtmann** [comment]
So you may close this issue?

**Comment by bunjes** [comment]
Same problem here (OS X 10.14, Nextcloud 15, OS X 10.13 was working). Using **https**://myserveraddress did not help
