### ISSUE TITLE
problem with update apps

### ISSUE THREAD

**Issue by gabbiano69** [nextcloud/server#12351]
Preparazione dell'aggiornamento
Imposta il livello del log per il debug
Modalità di manutenzione attivata
Aggiornamento schema database
Database aggiornato
Aggiornato "audioplayer" a 2.2.5
Aggiornato "calendar" a 1.5.8
Aggiornato "deck" a 0.2.8
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE `oc_reader_bookmarks` (`id` BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) DEFAULT '' NOT NULL, `file_id` BIGINT UNSIGNED NOT NULL, `type` VARCHAR(32) DEFAULT '' NOT NULL, `name` VARCHAR(512) DEFAULT '' NOT NULL, `value` VARCHAR(512) DEFAULT '' NOT NULL, `content` VARCHAR(4096) DEFAULT NULL, `last_modified` BIGINT UNSIGNED DEFAULT 0, INDEX reader_bookmarks_file_id_index (`file_id`), INDEX reader_bookmarks_user_id_index (`user_id`), INDEX reader_bookmarks_name_index (`name`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8 COLLATE utf8_bin ENGINE = InnoDB': SQLSTATE[HY000]: General error: 1709 Index column size too large. The maximum column size is 767 bytes.
 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by j-ed** [comment]
I think exactly this problem has already been described in #4015. You need to disable the app on the command line.

**Comment by MorrisJobke** [comment]
> I think exactly this problem has already been described in #4015. You need to disable the app on the command line.

Unfortunately yes.

This is a problem of this app. We can't do here anything, because this app creates an index that is too big on mysql only. Please report this to the apps bug tracker.
