### ISSUE TITLE
Grid/List toggle shown when there is no file list in the public share page

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#12356]
This is a regression introduced in #12303.

Public share page for single files:
![public-share-file-toggle-list](https://user-images.githubusercontent.com/26858233/48201858-a6880680-e363-11e8-8074-b79fb08db72a.png)

Public share page for drop folder:
![public-share-drop-toggle-list](https://user-images.githubusercontent.com/26858233/48201864-a851ca00-e363-11e8-9e59-07ac7e44dce5.png)

Please note that I have not checked other file lists.

@nextcloud/designers

**Comment by danxuliu** [comment]
This error message that I have noticed in the logs could be related:
`Undefined index: isIE at /var/www/html/apps/files_sharing/templates/public.php#49`

**Comment by MorrisJobke** [comment]
> `Undefined index: isIE at /var/www/html/apps/files_sharing/templates/public.php#49`

Comes most likely from #12289 and maybe together with #12303
