### ISSUE TITLE
Unneeded scroll bar shown in the public share page

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#12357]
Even if there is enough space a scroll bar is shown in the public share page:
![public-share-scrollbar](https://user-images.githubusercontent.com/26858233/48202261-a9cfc200-e364-11e8-95ae-1e329d823b44.png)

Reducing a few pixels the height of [the content](https://github.com/nextcloud/server/blob/d9387add9ebf57823a1ad5b736830638829c4954/core/css/public.scss#L31) or [the footer](https://github.com/nextcloud/server/blob/d9387add9ebf57823a1ad5b736830638829c4954/core/css/public.scss#L66) makes the scroll bar disappear... although their height is based on the same value, so I do not know what is going on :-)

Tested in both Firefox and Chromium.

@nextcloud/designers

**Comment by weeman1337** [comment]
A nice tiny thing for me..
