### ISSUE TITLE
Little typo in dutch translation in emailadres changed email notification email

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#12361]
### Steps to reproduce
1. Change the emailadres of a user at https://owncloud.domain.tld/settings/users
2. An email is sent
3. That email (in Dutch) contains an small typo in the body and the subject

### Expected behaviour
Tell us what should happen
 E-mailadres voor Name gewijzigd op https://owncloud.domain.tld/

==>> Look at the space between Name and gewijzigd.

### Actual behaviour
Tell us what happens instead

The text now states (subject and body):
 E-mailadres voor Namegewijzigd op https://owncloud.domain.tld/
 

Looks like this file must be updated:

settings/l10n/nl.json:    "Email address for %1$s changed on %2$s" : "E-mailadres voor %1$sgewijzigd op %2$s",
settings/l10n/nl.js:    "Email address for %1$s changed on %2$s" : "E-mailadres voor %1$sgewijzigd op %2$s",

**Comment by violoncelloch** [comment]
translations are handled on transifex (https://www.transifex.com/nextcloud/nextcloud/) you are welcome to improve translations there

**Comment by szaimen** [comment]
as violoncelloCH mentioned: this needs to be changed in the translation on transifex.

**Comment by radoeka** [comment]
OK updated.  Issue can be closed.
https://www.transifex.com/nextcloud/nextcloud/translate/#nl/settings-1/111555396?q=text%3Aaddress
