### ISSUE TITLE
Migration from Nextcloud 10 to Nextcloud 14 failed.

### ISSUE THREAD

**Issue by cpMillingworth** [nextcloud/server#12362]
Scenario:
Origin server running Nextcloud 10.0.6 with PHP 5.4 on CentOS 6.9.
Migrating to target server running Nextcloud 14.0.3 on Centos 7.2 using Remi's PHP 7.2.12 on CentOS 7.5

### Steps to reproduce
1. Copy /var/www/data and owncloud database from origin server. 
2. Export MySQL database from origin and Import database into MySQL on target and set grants accordingly.
3. Set permissions on /var/www/data to be owned by apache
4a: Attempt UI upgrade  via browser, receive alert of apps needing upgrade.  Proceed to upgrade
4b: Attempt occ upgrade
5: Both methods return error

### Expected behaviour
Expected Nextcloud to successfully updated database schema and operate normally with imported data.

### Actual behaviour
Both methods (UI versus occ) returned the same error:

Doctrine\DBAL\Schema\SchemaException: There is no column with name 'remember' on table 'oc_authtoken'.
Update failed

### Server configuration

Target host is CentOS 7
Apache 2.4.6
MariaDB 5.5.60
PHP v 7.2.12 (Remi)
Nextcloud version:   10.0.6 (origin)  14.0.2 (target)
Fresh install on target using imported data from origin.  
- Origin version doesn't run on target with PHP version 7.2.12.
Installed using zip file from Nextcloud.

System integrity passed using newly installed Nextcloud data but stopped working after data import attempt.

**List of activated apps:**
(NOTE:  These were installed as part of the default Nextcloud 14 configuration and only were showing in error after the database import).
Enabled:
  - activity: 2.3.2
  - cloud_federation_api: true
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - lookup_server_connector: true
  - notifications: 0.3.0
  - oauth2: true
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - twofactor_backupcodes: true
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - accessibility
  - admin_audit
  - encryption
  - files_external
  - logreader
  - nextcloud_announcements
  - sharebymail
  - support
  - user_external
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "hou-1.nextcloud.fileshare.staging.whmcs.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "http:\/\/hou-1.nextcloud.fileshare.staging.whmcs.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}

**Are you using external storage, if yes which one:**  
No, all local storage.

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.  Local configuration only.

### Client configuration
**Browser:**
Firefox, Chrome

**Operating system:**
Mac OS X

#### Web server error log
No new logs since import.

#### Nextcloud log (data/nextcloud.log)
No new logs since import

#### Browser log
Not relevant to this issue.

Thanks for your assistance!

**Comment by tflidd** [comment]
Currently, skipping major releases is not fully supported. It is recommended, to go through all major versions (11, 12, and 13):
https://github.com/nextcloud/documentation/issues/909

Problem is they do not support php 5.4 and php 7.2, so you need a version in between.

**Comment by vincentqb** [comment]
I'm getting this error when following after step3 from [here](https://help.nextcloud.com/t/migration-from-owncloud-10-3-0-to-nextcloud/62618/3) to upgrade between owncloud 10.3.2.2 and nextcloud on ubuntu 18.04.

**Comment by j-ed** [comment]
@vincentqb The right place to address this kind of questions is the [Nextcloud help forum](https://help.nextcloud.com/) because this is the bug tracker for the development only. Upgrade problems are reported on a regular base, so you should find several matches if you use the search function of the help forum 😉

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
