### ISSUE TITLE
Remnant LDAP user in a group results in the user settings not being able to list the group members

### ISSUE THREAD

**Issue by chaosgrid** [nextcloud/server#12379]
### Steps to reproduce
1. Have a group with LDAP user in it.
2. Delete user in LDAP.
3. Try to open group in Nextcloud user settings.

### Expected behaviour
The group should still be able to be displayed, with the deleted user possibly automatically removed.

### Actual behaviour
Nextcloud fails to load the group members, with the following log entry:
OC\User\NoUserException: XXX is not a valid user anymore

### Server configuration

Nextcloud version: 14.0.3

To fix this issue, one has to follow the guide [here](https://docs.nextcloud.com/server/14/admin_manual/configuration_user/user_auth_ldap_cleanup.html) and delete the "remnant" ldap user.
However, you should still be able to view a group with a remnant LDAP user in it.

**Comment by skjnldsv** [comment]
@blizzz

**Comment by blizzz** [comment]
oh, this was fixed long ago.
