### ISSUE TITLE
Target folder "/" does not exist any more

### ISSUE THREAD

**Issue by qiuye8023** [nextcloud/server#12373]
Can upload small files (such as the size of a 400 k file), but can't upload large files (such as the size of the 4 m file), I am using Google browser, error message ["Target folder"/" does not exist any more,"](https://img.qiuyee.cn/images/2018/11/09/error.png)

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
