### ISSUE TITLE
native WebDAV connection to NC on OS X fails

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#1237]
### Steps to reproduce
1. Install NC 10
2. Try to connect to NC via webdav on OS X

### Expected behaviour
Should be possible to connect.

### Actual behaviour
Connection is not established ("there was an error connecting to this server myhost.example.org").

### Server configuration
**Operating system**: Debian 8

**Web server:** Apache

**Database:** Maria-DB

**PHP version:** 7.0 (from dotdeb)

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 9.0.53

**Where did you install Nextcloud from:** manually

**List of activated apps:**
```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.3.3
  - comments: 1.0.0
  - contacts: 1.3.1.0
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - mail: 0.5.2
  - news: 9.0.4
  - notes: 2.0.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.0
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1

```

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocx7851qw981",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "data.aspekte.net"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/hostname\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{mailhost:993\/imap\/ssl}"
                ]
            }
        ],
        "updater.release.channel": "beta",
        "loglevel": 2,
        "maintenance": false,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Operating system:** Native WebDAV on OS X 10.9

#### Web server error log
<details>
<summary>Web server error log</summary>
```
ww.xx.yy.zz - - [01/Sep/2016:22:04:30 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 401 5751 "-" "WebDAVLib/1.3"
ww.xx.yy.zz - - [01/Sep/2016:22:04:31 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 401 1835 "-" "WebDAVLib/1.3"
ww.xx.yy.zz - - [01/Sep/2016:22:04:39 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 401 5767 "-" "WebDAVLib/1.3"
ww.xx.yy.zz - user@domain.com [01/Sep/2016:22:04:39 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 200 1718 "-" "WebDAVLib/1.3"
ww.xx.yy.zz - - [01/Sep/2016:22:04:39 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 401 5799 "-" "WebDAVFS/3.0.1 (03018000) Darwin/13.4.0 (x86_64)"
```
</details>

I thought it might be related to the short-urls that I decided to use, so I undid this. Furthermore I used a system user instead of an IMAP-user (perhaps the `@`-symbol).
<details>
<summary>Web server error log</summary>
```
ww.xx.yy.zz - - [01/Sep/2016:22:06:56 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 401 5767 "-" "WebDAVLib/1.3"
ww.xx.yy.zz - test [01/Sep/2016:22:06:56 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 200 1718 "-" "WebDAVLib/1.3"
ww.xx.yy.zz - - [01/Sep/2016:22:06:56 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 401 5799 "-" "WebDAVFS/3.0.1 (03018000) Darwin/13.4.0 (x86_64)"
ww.xx.yy.zz - test [01/Sep/2016:22:06:56 +0000] "OPTIONS /nextcloud/remote.php/webdav/ HTTP/1.1" 503 1285 "-" "WebDAVFS/3.0.1 (03018000) Darwin/13.4.0 (x86_64)"
```
</details>

#### Other setups
Interestingly, I manage to connect via webdav from the same client to setups of OC 8.2.7 and 9.1.1RC1. There are more reports on this issue with other OS X versions and NC 9.0 and NC 10:
https://help.nextcloud.com/t/nextcloud-with-webdav-with-finder-on-os-x-10-11/2748

and

Connection to demo.owncloud.org works, demo.nextcloud.com doesn't!

**Comment by JBoersma360** [comment]
Looks related to this

https://github.com/nextcloud/server/issues/223

**Comment by tflidd** [comment]
Yes, it looks the same. I tried this patch but without success: https://github.com/nextcloud/server/pull/797

**Comment by LukasReschke** [comment]
Please test https://github.com/nextcloud/server/pull/1328 in combination with https://github.com/nextcloud/server/pull/797

**Comment by tflidd** [comment]
Ok, this works :+1: 

It's not very fast and the connection is a bit buggy. And it searches for non-existant files, e.g.
```
"PROPFIND /nextcloud/remote.php/webdav/._. HTTP/1.1" 404 1700 "-" "WebDAVFS/3.0.1 (03018000) Darwin/13.4.0 (x86_64)"
```
and for each file it seems to look for a temporary file by default (file.ext):
```
"PROPFIND /nextcloud/remote.php/webdav/Documents/ttest/._file.ext HTTP/1.1" 404 986 "-" "WebDAVFS/3.0.1 (03018000) Darwin/13.4.0 (x86_64)"
```
Ubuntu doesn't do that and it is much faster. So we probably can't blame nextcloud for it...

**Comment by LukasReschke** [comment]
> It's not very fast and the connection is a bit buggy. And it searches for non-existant files, e.g.

Welcome to the world of OS X. This is just Finder being a silly WebDAV client. See also http://sabre.io/dav/clients/finder/#excessive-requests
