### ISSUE TITLE
Disable password change with SSO

### ISSUE THREAD

**Issue by fri-sch** [nextcloud/server#12386]
When using SSO with user_saml the password change form in the users security settings should not be visible, as the authentication is done via SAML only and no passwords are used within NC.

Also as the user_saml app might be extended to map more user attributes from the IdP to NC, it would be good to have the possibility of disabling the editing of the user attributes such as phone number, etc. For the users display name, this is already possible via `'allow_user_to_change_display_name' => false`, but not for other attributes.

**Comment by violoncelloch** [comment]
Could you report this to the [user_saml](https://github.com/nextcloud/user_saml/issues) repo?

**Comment by violoncelloCH** [comment]
As far as I know most of the user backends do this on their own (either automatically or by preference), so if user_saml repo doesn't do it, report it there. It doesn't make sense to implement this in server, as there is no use in disabling it for local Nextcloud users IMHO.

**Comment by danielkesselberg** [comment]
Ref https://github.com/nextcloud/server/issues/12671 we discussed the password case for `user_ldap` and `user_sql` there. the change password form is visible when the backend reports that a password change is possible.

https://github.com/nextcloud/user_saml/blob/a8f7d16c6a418bf8fce9a9b9ca3b0cef5b6747e0/lib/UserBackend.php#L173-L178 looks right to me. 

Please dont mix bug report and feature request. 

> When using SSO with user_saml the password change form in the users security settings should not be visible, as the authentication is done via SAML only and no passwords are used within NC.

Bug Report

> Also as the user_saml app might be extended to map more user attributes from the IdP to NC, it would be good to have the possibility of disabling the editing of the user attributes such as phone number, etc. For the users display name, this is already possible via 'allow_user_to_change_display_name' => false, but not for other attributes.

Feature Request
