### ISSUE TITLE
When a calendar event is deleted, corresponding calendar_invitation entries are not deleted

### ISSUE THREAD

**Issue by brad2014** [nextcloud/server#12387]
A note for minor cleanup.

When a calendarobject (a particular event) is deleted, any outstanding calendar_invitations for that event should be deleted as well.  Currently, I believe they are left dangling until they expire at the end time of the (now deleted) event, if the event has one.

**Comment by tcitworld** [comment]
So `calendar_invitations` reference `calendarobjects` (though UID) but not `calendars`. Therefore we can remove them when the event is (permanently) deleted, but not when the calendar itself is (permanently) deleted.

I'm not certain that it's a good idea to reference the calendar in `calendar_invitations`, so maybe another cleanup job?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by brad2014** [comment]
Still a bug.

I can confirm that in 25.0.2, when a calendar event is deleted, the calendar event now is moved to a trash bin (so the event object is not deleted, and the token does not refer to a deleted event uid). However, when the calendar trash is emptied, and the deleted calendar object is removed from the database, the calendar_invitation referring to that calendar object is not cleaned up, and is left dangling (its uid now refers to a nonexistant id).

Site Note: installations that have `occ config:app:set dav invitation_link_recipients --value no` are not affected, since invitation tokens are not generated for such systems.

**Comment by SebastianKrupinski** [comment]
Tested on version 30-dev. Confirmed.

Tested with internal NC attendee:
On event delete,
	- More options link still works.
	- Accept/Decline link shows error message.
On event restore.
	- More options link still works.
	- Accept/Decline link still works. 
On trash empty
	- Same behavior as delete and link is NOT removed.

Tested with external attendee only:
On event delete,
	- More options link still works.
	- Accept/Decline link shows error message.
On event restore.
	- More options link still works.
	- Accept/Decline link still works. 
On trash empty
	- Same behavior as delete and link is NOT removed.

Issue 1:
calendar_invitations entries are not deleted, at any stage.

Issue 2:
More options should show error message or notification message that the event no longer exists.

**Comment by SebastianKrupinski** [comment]
Related to #15814
