### ISSUE TITLE
dav is never sending "update" imip emails when event is changed

### ISSUE THREAD

**Issue by brad2014** [nextcloud/server#12393]
When a calendar event is updated (e.g. its start time is changed), an update imip mail should be sent to attendees.

To reproduce:
- create an event
- add an attendee
- notice invite email is received by attendee
- change start time of event

Actual behavior:
- attendee receives another "invite"  email

Expected behavior:
- attendee should receive an "update" email.

**Comment by brad2014** [comment]
According to RFC 5546, 
```
The combination of the "UID" property (unchanged) and the "SEQUENCE" 
(bumped to 1) properties indicate the update.
```

But it looks like the code is incorrectly expecting METHOD to be REPLY instead of checking UID and SEQUENCE (I don't think the server should ever be sending an imip REPLY, only REQUEST and CANCEL.  The client sends REPLY).

**Comment by georgehrke** [comment]
@brad2014 Can you point us to the code you are talking about please?

In case of doubt this has to be fixed upstream at sabre/dav
