### ISSUE TITLE
Same string occurs twice

### ISSUE THREAD

**Issue by keunes** [nextcloud/server#12406]
Hope I'm reporting this in the right component. When translating on Transifex, the same string appears twice:
- /app/apps/comments/lib/Notification/Notifier.php:105
A (now) deleted user mentioned you in a comment on “%s”
- /app/apps/comments/lib/Notification/Notifier.php:109
A (now) deleted user mentioned you in a comment on “{file}”

Can/should these be merged?

**Comment by rullzer** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
This was done with #12349
