### ISSUE TITLE
NO_PROXY 

### ISSUE THREAD

**Issue by rvalle** [nextcloud/server#12402]
### Steps to reproduce
1. install nextcloud in your intranet
2. setup proxy to access external resources such as plugins, etc.
3. install collabora online in your intranet
4. setup no_proxy for colabora

### Expected behaviour
nextcloud shoul use the proxy to access external resources, such as plugins, apps, etc but not to access collabora.

### Actual behaviour
proxy is used for everything incluing collabora.

### Server configuration

I am using the latest nextcloud docker image.

**Nextcloud version:** (see Nextcloud admin page)

14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

fresh

### Additional Description

The custom.config allows to setup a proxy URI that is passe to GuzzleHTTP client as request options. Guzzle has the option to receive an array instead with a richer interface that provides this possibility. However the way in which custom config has been implemented makes it impossible.

On the other hand, GuzzleHTTP is supposed to use NO_PROXY environment variable, but this one is not working either, for some reason.

**Comment by ranying666** [comment]
I have the same problem, no support for no_proxy, not very friendly.Hopefully you can provide this configuration parameter in the future.

**Comment by kesselb** [comment]
> On the other hand, GuzzleHTTP is supposed to use NO_PROXY environment variable, but this one is not working either, for some reason.

:disappointed: 

> Guzzle will automatically populate this value with your environment's NO_PROXY environment variable. However, when providing a proxy request option, it is up to your to provide the no value parsed from the NO_PROXY environment variable (e.g., explode(',', getenv('NO_PROXY'))).

http://docs.guzzlephp.org/en/stable/request-options.html#proxy

https://github.com/nextcloud/server/blob/fd1d85365cb1368fa70263fe3ae3b8e59ab56615/lib/private/Http/Client/Client.php#L64

The proxy option is passed to guzzle by default but there is no support for NO_PROXY yet.

https://github.com/nextcloud/server/blob/fd1d85365cb1368fa70263fe3ae3b8e59ab56615/lib/private/Http/Client/Client.php#L97-L111

This method should return a array (with the elements `http`, `https` and `no`) or null. 

```
Index: lib/private/Http/Client/Client.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Http/Client/Client.php	(revision 77c09252d5333a3665ccd5bf058666d5a26ee3b7)
+++ lib/private/Http/Client/Client.php	(date 1563986948000)
@@ -92,9 +92,9 @@
 	/**
 	 * Get the proxy URI
 	 *
-	 * @return string|null
+	 * @return array|null
 	 */
-	private function getProxyUri(): ?string {
+	private function getProxyUri(): ?array {
 		$proxyHost = $this->config->getSystemValue('proxy', null);
 
 		if ($proxyHost === null) {
@@ -102,12 +102,13 @@
 		}
 
 		$proxyUserPwd = $this->config->getSystemValue('proxyuserpwd', null);
+		$proxyExclude = $this->config->getSystemValue('proxyexclude', []);
 
-		if ($proxyUserPwd === null) {
-			return $proxyHost;
+		if ($proxyUserPwd !== null) {
+			$proxyHost = $proxyUserPwd . '@' . $proxyHost;
 		}
 
-		return $proxyUserPwd . '@' . $proxyHost;
+		return ['http' => $proxyHost, 'https' => $proxyHost, 'no' => $proxyExclude];
 	}
 
 	/**
```

Something like this should do the trick. `config.sample.php` needs some changes and there should be a test case.
