### ISSUE TITLE
jQuery UI inline datepicker theme problem

### ISSUE THREAD

**Issue by pesarkhobeee** [nextcloud/server#12407]
I am developing a simple app for the NexCloud and right now I am trying to put an inline data picker but it seems that there is some problem in the default theme for that, you can see it in the below picture:

![screenshot from 2018-11-11 19-10-09](https://user-images.githubusercontent.com/147461/48316978-fcbaab00-e5ea-11e8-9fa0-8f642ea99d43.png)

I don't have that problem in non-inline mode:

![screenshot from 2018-11-11 19-01-10](https://user-images.githubusercontent.com/147461/48316988-2ecc0d00-e5eb-11e8-8e06-9a1eabcf948f.png)

**Comment by skjnldsv** [comment]
Hello.
We're strongly suggesting to not use inline datepicker. We use popover menus all over newtcloud and it's better/easier for consistency :)

By the way, if you want to create anew app, we have a vue.js repository with various components that are nicely integrated into nextcloud https://github.com/nextcloud/vue-components (including a proper datepicker). 
Feel free to also come in #nextcloud-dev on freenode's irc !
