### ISSUE TITLE
Grid view: multi selection with Shift and Strg keys

### ISSUE THREAD

**Issue by helmut72** [nextcloud/server#12405]
Grid view with thumbnails is really handy, especially for sorting and deleting images and videos taken with the phone.

Please add multi selection with Shift/Strg (Cmd on macOS) key for multi selection.

This is an example with at least Shift key:
https://demo.filerun.co/?username=admin&password=admin#/Photos/Latest

**Comment by juliushaertl** [comment]
Selecting files with Ctrl+Click works fine here. Can you report which browser you are using?

**Comment by helmut72** [comment]
Safari on macOS.

Realized right now that Shift+Click works, but I need to click into the thumbnail and not the checkbox to select the last pic of a selection. A bit confusing because selecting the first pic of a selection is only possible with the checkbox.

Also I never clicked to the thumbnail, because it usually opens the pic. Ok, good to know. Not that much intuitive, but it works. Thanks for the trigger to try it again! 👍
