### ISSUE TITLE
Weblogin: strange submit button

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12404]
Please see this video: https://cloud.nextcloud.com/s/mzESF9wXNsdwZSM

Happens on NC15 beta1 and NC master.

**Comment by tobiasKaminsky** [comment]
@skjnldsv thanks for fixing the first bug (blue button), but I was referring to the last submit button that is shown while you are being redirected:

![image](https://user-images.githubusercontent.com/5836855/48941374-a3704700-ef1b-11e8-92d6-6cf4d96c9069.png)

**Comment by skjnldsv** [comment]
Arrgh :grin:
