### ISSUE TITLE
Improve creating new users' group UX/UI

### ISSUE THREAD

**Issue by pesarkhobeee** [nextcloud/server#12400]
I believe that we should be able to define a new group when we are creating a new user but unfortunately, that is impossible!
So from my point of view, this is a UX/UI problem which I hope somebody fixes that :)

![4b0bb7d609359766bd0671bc7757ad817feb39eb](https://user-images.githubusercontent.com/147461/48306900-fb817380-e541-11e8-9f20-6341b4488d75.png)

**Comment by skjnldsv** [comment]
Already fixed in https://github.com/nextcloud/server/pull/11193 :grin:
