### ISSUE TITLE
Mac OS 10.7.5 - the client does not even start

### ISSUE THREAD

**Issue by plrunner** [nextcloud/server#1240]
The client does not start even if considered compatibile to 10.7.+
Launching it from terminal returns "illegal instruction 4".
I upgrade to El Capitan and it got solved.

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/client_theming/issues, seems like a dupe of https://github.com/nextcloud/client_theming/issues/14 though.

Did you try with 10.8 by any chance?

**Comment by plrunner** [comment]
Ops, sorry, I was on my mobile and did not figured out I was on the wrong project.

No, I didn't try with 10.8 because it got upgraded directly to 10.11.
