### ISSUE TITLE
Error with non-existent file

### ISSUE THREAD

**Issue by Tealk144** [nextcloud/server#1241]
Hallo,

i get this error but in path "/xxx/xxx/xxx/files_versions/Arbeit/PGO" isnt a "Pokemon_GO_Discord_Chat_fur_alle_Fraktionen.docx.*" file

filesize(): stat failed for /xxx/xxx/xxx/files_versions/Arbeit/PGO/Pokemon_GO_Discord_Chat_fur_alle_Fraktionen.docx.v1469520899 at /var/www/nextcloud/lib/private/Files/Storage/Local.php#155

Nextcloud 10
PHP
Version: 7.0.9
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513.0 MB

Database
Type: mysql
Version: 10.0.26
Size:

**Comment by nickvergessen** [comment]
Well that is exactly the error, Nextcloud is trying to read the filesize of the non existing file.

**Comment by nickvergessen** [comment]
Let's continue this in the forum:
https://help.nextcloud.com/t/filesize-stat-failed-for/3662
