### ISSUE TITLE
Shared calendar/tasks are not shown in Apple Reminders App

### ISSUE THREAD

**Issue by d-patch** [nextcloud/server#12423]
### Steps to reproduce
Share a calendar via caldav with another user.  Other users creates caldav account on his/her Apple device (e.g. iPhone, iPad or iMac) using "Passwords & Accounts" from the "Settings" Menu, enabling the "calendar" and "reminders" options. When he/she opens the shared calendar in the Calendar App, the result is as expected, i.e. the shared calendar is shown. If he/she opens the Reminders App, the shared calendar/tasks are not shown, only his/her own calendar/tasks.

### Expected behaviour
The shared calendar/tasks should also be visible in the Reminders App on the Apple device.

### Actual behaviour
The shared calendar/tasks are not visible in the Reminders App on the Apple device.

## Server configuration detail

**Operating system:** Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.23

**PHP version:** 

7.2.11-2+0~20181015120859.6+stretch~1.gbp8105e0
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** NextCloudPi 14.0.3 - 14.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** NextCloudPi 13.x

**Where did you install Nextcloud from:** NextCloudPi Image

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - calendar: 1.6.3
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.6
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_external: 1.5.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.4.2
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - previewgenerator: 1.1.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.7
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - admin_notifications
 - encryption
 - news
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "localhost",
        "5": "nextcloudpi.local",
        "1": "192.168.xxx.xxx",
        "2": "xxx.xxx.xxx.xxx",
        "4": "xxx.xxx.xxx.xxx",
        "7": "nextcloudpi",
        "8": "nextcloudpi.lan"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/xxx.xxx.xxx.xxx\/",
    "dbtype": "mysql",
    "version": "14.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "PLAIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "maintenance": false,
    "loglevel": "2",
    "log_type": "file",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Apple Reminders App

**Operating system:** iOS 12.0, iOS 12.1, MacOS 10.13.6

## Logs

<details><summary>Browser log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by georgehrke** [comment]
If the calendar was only created with the component type VEVENT, it won't show up even if you enable the checkbox in macOS calendar.

If you select Calendars / Reminders in the macOS settings, it has no effect on the component type. It only determines whether macOS will ever use this CalDAV account for tasks or not.
