### ISSUE TITLE
Event privacy level does not work in Thunderbird

### ISSUE THREAD

**Issue by maksemuz** [nextcloud/server#12426]
*Discarded*

**Comment by rullzer** [comment]
@maksemuz could I ask you to report this to our h1 tracker: https://hackerone.com/nextcloud

**Comment by maksemuz** [comment]
> @maksemuz could I ask you to report this to our h1 tracker: https://hackerone.com/nextcloud

https://hackerone.com/bugs?report_id=439828&subject=user
done

**Comment by rullzer** [comment]
Thnx lets continue there
