### ISSUE TITLE
PHP errors when running occ maintenance:repair

### ISSUE THREAD

**Issue by eehmke** [nextcloud/server#12428]
run command
sudo -u www-data php occ maintenance:repair

### Expected behaviour
No errors should accour

### Actual behaviour
On the command line, the command runs without any issues. However, in the log I find several error messages like:

`[index] Error: Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`checksum`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["3", "14", 1542104372, 0, "d6b49f257be038ccc598a9c4d0b5294e", 1542104372, 27, 32, "", "9e18f902887db36237ad7ec210934c1b", "appdata_ocsh7lsutd22\/js\/core\/merged.js", "merged.js", 2, 2, "9e18f902887db36237ad7ec210934c1b"]:

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2-9e18f902887db36237ad7ec210934c1b' for key 'fs_storage_path_hash' at <<closure>>

 0. /var/www/testcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 128
    convertException("An exception oc ... '", Doctrine\DBAL\Dr ... ]})
 1. /var/www/testcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1015
    driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "INSERT INTO `oc ... 0", {1: "3",2: "14", ... "})
 2. /var/www/testcloud/lib/private/DB/Connection.php line 216
    executeUpdate("INSERT INTO `oc ... 0", ["3","14",154210 ... "], [])
 3. /var/www/testcloud/lib/private/DB/Adapter.php line 114
    executeUpdate("INSERT INTO `oc ... 0", ["3","14",154210 ... "])
 4. /var/www/testcloud/lib/private/DB/Connection.php line 254
    insertIfNotExist("*PREFIX*filecache", {mimepart: "3",m ... 2}, ["storage","path_hash"])
 5. /var/www/testcloud/lib/private/Files/Cache/Cache.php line 272
    insertIfNotExist("*PREFIX*filecache", {mimepart: "3",m ... 2}, ["storage","path_hash"])
 6. /var/www/testcloud/lib/private/Files/Cache/Cache.php line 229
    insert("appdata_ocsh7lsutd22/js/core/merged.js", {mimetype: "appl ... "})
 7. /var/www/testcloud/lib/private/Files/Cache/Scanner.php line 292
    put("appdata_ocsh7lsutd22/js/core/merged.js", {mimetype: "appl ... "})
 8. /var/www/testcloud/lib/private/Files/Cache/Scanner.php line 221
    addToCache("appdata_ocsh7lsutd22/js/core/merged.js", {mimetype: "appl ... "}, -1)
 9. /var/www/testcloud/lib/private/Files/Cache/Scanner.php line 336
    scanFile("appdata_ocsh7lsutd22/js/core/merged.js", 3, 32, false, false)
10. /var/www/testcloud/lib/private/Files/Cache/Updater.php line 124
    scan("appdata_ocsh7lsutd22/js/core/merged.js", false, 3, false)
11. /var/www/testcloud/lib/private/Files/View.php line 320
    update("appdata_ocsh7lsutd22/js/core/merged.js", 1542104372)
12. /var/www/testcloud/lib/private/Files/View.php line 1161
    writeUpdate(OCA\Files_Trashb ... }}, "appdata_ocsh7lsutd22/js/core/merged.js")
13. /var/www/testcloud/lib/private/Files/View.php line 567
    basicOperation("touch", "/appdata_ocsh7lsutd22/js/core/merged.js", ["touch","create","write"], null)
14. /var/www/testcloud/lib/private/Files/Node/Folder.php line 181
    touch("/appdata_ocsh7lsutd22/js/core/merged.js")
15. /var/www/testcloud/lib/private/Files/SimpleFS/SimpleFolder.php line 83
    newFile("merged.js")
16. /var/www/testcloud/lib/private/Template/JSCombiner.php line 177
    newFile("merged.js")
17. /var/www/testcloud/lib/private/Template/JSCombiner.php line 103
    cache("/var/www/testcl ... s", "merged.js", OC\Files\SimpleFS\SimpleFolder {})
18. /var/www/testcloud/lib/private/Template/JSResourceLocator.php line 114
    process("/var/www/testcloud", "core/js/systemtags/merged.json", "core")
19. /var/www/testcloud/lib/private/Template/JSResourceLocator.php line 70
    cacheAndAppendCombineJsonIfExist("/var/www/testcloud", "core/js/systemtags/merged.json")
20. /var/www/testcloud/lib/private/Template/ResourceLocator.php line 78
    doFind("js/systemtags/merged")
21. /var/www/testcloud/lib/private/TemplateLayout.php line 321
    find(["vendor/core"," ... "])
22. /var/www/testcloud/lib/private/TemplateLayout.php line 160
    findJavascriptFiles(["vendor/core"," ... "])
23. /var/www/testcloud/lib/private/legacy/template.php line 211
    __construct("user", "files")
24. /var/www/testcloud/lib/public/AppFramework/Http/TemplateResponse.php line 157
    fetchPage({usedSpacePercen ... ]})
25. /var/www/testcloud/lib/private/AppFramework/Http/Dispatcher.php line 119
    render()
26. /var/www/testcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Files\Controller\ViewController {}, "index")
27. /var/www/testcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("ViewController", "index", OC\AppFramework\ ... {}, {_route: "files.view.index"})
28. <<closure>>
    __invoke({_route: "files.view.index"})
29. /var/www/testcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "files.view.index"})
30. /var/www/testcloud/lib/base.php line 987
    match("/apps/files/")
31. /var/www/testcloud/index.php line 42
    handleRequest()

GET /apps/files/
from 2003:84:ae08:58fc:be5f:f4ff:fe79:963a by user at 2018-11-13T10:19:32+00:00`

### Server configuration

**Operating system**: Debian 9.6

**Web server:** Apache 2.4.25

**Database:** MariaDB 10.1

**PHP version:** 7.2

**Nextcloud version:** 15.0.1 beta

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.3

**Where did you install Nextcloud from:** zip file

**Comment by MorrisJobke** [comment]
Fixed by #12411 - will be fixed in 15.0.0 beta 2 and 14.0.4
