### ISSUE TITLE
Rescan/Rebuild file index not possible without SSH

### ISSUE THREAD

**Issue by BierGitte** [nextcloud/server#12435]
Issue:
It doesn't seem to be possible to rebuild the file index without using ssh / occ files:scan command

Problem:
Because of an (unknown) error when trying to delete a file, I deleted it manually with an FTP client.  The file stayed in the Nextcloud index on the server, I can neither remove it via the client nor the web frontend, even re-uploading it via FTP doesn't help.
Because my web hoster doesn't give SSH access, I don't see a way to clean up the file index. I have a red Nextcloud icon in the info area, and constantly get notifications that the file couldn't be synced.

Possible solution:
Add some kind of maintenance mode, either accessible from the client or web frontend, or provide an option via right click on the item in the Activity/Not Synced list of the client.

**Comment by BierGitte** [comment]
Possible workarounds:
If you are allowed to on a shared hosting server you could:
Execute the command via cron job
Execute the command via php script etc., i.e. with shell_exec or similar

Unfortunately, that's not possible on my webspace. I could solve the problem as follows:
In phpMyAdmin, go to _file_locks table. If there is an entry for the problematic file, set "lock" from 1 to 0. Then delete the file via web interface.
----------------------
I still think there should be maintenance options built into Nextcloud for non-privileged people on shared hosting platforms.

**Comment by tylla** [comment]
With the possible risk of hopping on the "+1" bandwagon, this problem affects me as well.
I only have FTP access to the hosted area and this is the umpteenth time when the lack of this feature bites me. There are some file/directory operations which are simply way easier/faster through FTP then on the web GUI.
I understand that there may be technical considerations running the `files:scan` command from the web UI (like timeout), but I don't think this could not be solved. An option could be added to the '...' menu which would set a flag for the given directory for the cron service which could run the command. It can even take longer than one would expect as long as it would solve our (and others') problem.
Thank you for considering this enhancement (and for making this really nice program in the first place).

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers

**Comment by tylla** [comment]
I must disagree with the idea of "provide this feature as a dedicated app".
I think the possibility to rebuild the file index is a base functionality which is a must. If there is a possibility to change the files outside of NC then there should be the possibility to clean up the possible mess. If there is already the corresponding functionality available on the command line, then this functionality should be available from the GUI as well.
Please reconsider closing this issue.
