### ISSUE TITLE
Index identifier `calendarid_calendartype_synctoken` is too long

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#12446]
Oracle install is broken again:
> An exception occurred while executing 'CREATE INDEX calendarid_calendartype_synctoken ON \"oc_calendarchanges\" (\"calendarid\", \"calendartype\", \"synctoken\")':\n\nORA-00972: identifier is too long

Regression from https://github.com/nextcloud/server/pull/10059

cc @georgehrke

**Comment by georgehrke** [comment]
Identifier is just referring to calendarid_calendartype_synctoken, right?
