### ISSUE TITLE
Nested Groups

### ISSUE THREAD

**Issue by DrEVILish** [nextcloud/server#12443]
You're not able to create nested groups for permissions of apps.

"Users" have access to Talk
"ProUsers" are also "Users" so should have access to Talk and Calendar

Currently unable to nest permissions you have to give each User a marathon of groups.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
