### ISSUE TITLE
Enable log rotation per default

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#12451]
Hello, more and more users are meeting Log Rotationg issue, especially on "small" devices.  --> https://help.nextcloud.com/t/3rdparty-icewind-is-spamming-logfile-with-errors-hundreds-of-errors-per-second/35262 
It seems that it could be a good idea to setup log rotation per default in config.php, e.g. for rasperry pi:

    'log_rotate_size' => 104857600,

What you think?

**Comment by rullzer** [comment]
It is actually set to 100MB.
However rotation will only happen when your background job runs.

Which should be at least daily if you use cron

**Comment by GAS85** [comment]
Are you sure? In documentation it is set to - no rotation: [The default is 0, or no rotation](https://docs.nextcloud.com/server/14/admin_manual/configuration_server/config_sample_php_parameters.html#logging)

**Comment by MorrisJobke** [comment]
> Could it be possible to set it to e.g. 100MB per default, if no 'log_rotate_size' is set in config.php? And if it is set - config.php will overwrite this value to user specified. E.g. 0 to no rotation.

It is really set to this value:

https://github.com/nextcloud/server/blob/b841a477c6b96a13ea061df3fc622c3067514bf2/lib/private/Log/Rotate.php#L42

And also the config sample says so: 

https://github.com/nextcloud/server/blob/ad0a2ee1811dd96364dda4d75623e3232a5d811c/config/config.sample.php#L839

And even the documentation does list it:

<img width="1330" alt="bildschirmfoto 2018-12-04 um 00 53 00" src="https://user-images.githubusercontent.com/245432/49408998-0ef9b600-f75f-11e8-9d12-e3bbfae255b4.png">


It was set to this value 8 months ago: https://github.com/nextcloud/server/commit/058f8123e61863f27ca138370853f71f70e90233

Let me close this ticket then.

**Comment by MorrisJobke** [comment]
Closed by https://github.com/nextcloud/server/pull/9137
