### ISSUE TITLE
服务器内部错误

### ISSUE THREAD

**Issue by 1937470700** [nextcloud/server#12463]
![_ _20181115093342](https://user-images.githubusercontent.com/45054049/48524010-8e5f3c80-e8b9-11e8-81b4-0f344cf722c1.png)
内部服务器错误
服务器不能完成你的请求。

如果再次发生，请在下方将技术详情发送给服务器管理员。

更多细节可以在服务器日志中找到.

技术细节
远程地址: 100.125.68.18
请求 ID: cc0yb6CfeeM7kb4k7TVj

错误如上，不是首次安装，是使用了一段时间突然出现这问题了，找了好久也不知道哪的问题

**Comment by MorrisJobke** [comment]
As we are an English speaking community I would like to ask you to file your ticket in English. Just one side note: it looks like you just pasted the default error page. Just look up the ID in the nextcloud.log inside your data directory to learn more about this error.
