### ISSUE TITLE
insert operations under some circumstances refused on postgreSQL (NC14)

### ISSUE THREAD

**Issue by tuxedo-rb** [nextcloud/server#12465]
First of all, i'm inexperienced with the oddities of postgreSQL.
A user of the Dashboard App reported a problem related to postgreSQL.
<https://github.com/nextcloud/dashboard/issues/44>

The root of the problem lies in the postgre specific lastInsertId() method.
These tries to execute:
```sql
SELECT lastval()
```
in class:
<https://github.com/nextcloud/server/blob/master/lib/private/DB/AdapterPgSql.php#L29>
for each insert operation, initiated in class:
<https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Db/Mapper.php#L132>

But it seems, that's under some circumstances not allowed and results in a exception.

Each App relies on AppFramework and if a App needs their own database table(s), then it uses the provided database methods.

**Comment by danielkesselberg** [comment]
https://github.com/owncloud/core/issues/10080


Autoincrement enabled for this table?

**Comment by tuxedo-rb** [comment]
Yes, autoincrement should be enabled:
<https://github.com/nextcloud/dashboard/blob/stable14/appinfo/database.xml>
I don't use postgreSQL, so i can't say for sure. I report only.

QMapper calls the same method:
<https://github.com/nextcloud/server/blob/master/lib/public/AppFramework/Db/QBMapper.php#L122>
Would that make any difference?

**Comment by mikaelfrykholm** [comment]
I got hit with this when trying out the new social app. I guess the ORM has a bug for pgsql. Please let my know if you want the generated ddl.

**Comment by mikaelfrykholm** [comment]
I got hit with this when trying out the new social app. I guess the ORM has a bug for pgsql. Please let me know if you want the generated ddl.

**Comment by danielkesselberg** [comment]
> Please let me know if you want the generated ddl.

Yes.

**Comment by mikaelfrykholm** [comment]
[nextcloud.ddl.txt](https://github.com/nextcloud/server/files/2675825/nextcloud.ddl.txt)
exported it with pg_dump -s

**Comment by danielkesselberg** [comment]
The insert operation for which table fails for you @mikaelfrykholm?

**Comment by mikaelfrykholm** [comment]
I tried creating a new post with the new ActivityPub implementation. 
{"reqId":"gwolK1JSZH4bC69IXOcW","level":2,"time":"2018-12-13T12:09:12+00:00","remoteAddr":"130.239.204.245","user":"mikael","app":"no app in context","method":"POST","url":"\/apps\/social\/api\/v1\/post","message":"500 - {\"status\":-1,\"exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\DriverException\",\"message\":\"An exception occurred while executing 'SELECT lastval()':\\n\\nSQLSTATE[55000]: Object not in prerequisite state: 7 ERROR:  lastval is not yet defined in this session\"}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"15.0.0.10"}

**Comment by danielkesselberg** [comment]
Thank you @mikaelfrykholm 

You are running into owncloud/core#10080. There is no autoincrement flag set for `id` but the value for is defined by https://github.com/nextcloud/social/blob/b7ac669cb3cbd66fb36f1c1100d2508ca846863e/lib/Service/ActivityPub/NoteService.php#L143

1) Create a new item `Note`
2) Set id for item
3) Save item to database
4) Try to return the id from the database :boom: on postgres

https://github.com/nextcloud/server/blob/51f13a7e9ce36abb8a9f8da481e187bf98eba021/lib/public/AppFramework/Db/QBMapper.php#L122

@rullzer @ChristophWurst if the id is already set we should not ask the database for an id again? not sure if this is a save change. maybe some bad code relies on this behaviour. let me know what you think.

```
if ($entity->getId() === null) {
    $entity->setId((int) $qb->getLastInsertId()); 
}
```

**Comment by ChristophWurst** [comment]
Sounds good to me.

@nickvergessen is our expert for all types of database questions :wink:

**Comment by danielkesselberg** [comment]
15.0.1 is scheduled for 2019-10-01 and will ship a fix.
