### ISSUE TITLE
Nextcloud 15 - (in)compatible app checked by Nextcloud

### ISSUE THREAD

**Issue by Larsene** [nextcloud/server#12486]
Nextcloud reported a new beta version, and it said that every apps has an update for this version, so i launched the update system, and before updating, i saw this is totally wrong.

### Steps to reproduce
1. Nextcloud 14.0.3, check update panel, and see that Nextcloud said every app is compatible with this version
2. Start the update process
3. Before the update start, at the last step, see that a lot of apps are disabled before update

### Expected behaviour
Nextcloud should say that these apps will be disabled BEFORE starting the update process, not at this last step !

![nextcloud](https://user-images.githubusercontent.com/8544729/48626407-132d8180-e9b2-11e8-8d1a-bc9a6349c560.jpg)

### Notes
The “App updates available” list seems not working in 14.0.3, so you can’t rely on this when deciding for the update. It always says “All fine - all apps compatible” while they are not.

### Help !!!
Now, how can i go back, and not apply this update ? I need these apps !

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

Also similar issues have been fixed over the last releases iirc
