### ISSUE TITLE
Open favorite folder from sidebar shows root folder content

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#12493]
* have folder `abc`
* mark it as favorite `abc`
* click on the item `abc` in the left sidebar under `favorites`
* expected: see content of `abc` in the file list
* actual: see the content of the home folder in the file list

It is also noticed that there are two webdav requests: first one for the folder `abc` and then one for the home of the user.

Happens on 14.0.4 RC 1, 15.0.0 beta 2 and master

cc @newhinton @skjnldsv @juliushaertl @danxuliu

**Comment by juliushaertl** [comment]
The issue is still not solved in all cases, looks like it worked when testing due to a timing issue, but it is still happening when browsing files from the quickaccess sub-entries.
