### ISSUE TITLE
Retrieving user profile over OCS-API with OAuth2 bearer token fails when using 2FA

### ISSUE THREAD

**Issue by Eisfunke** [nextcloud/server#12498]
### Steps to reproduce
1. Enable Two-Factor-Authentification.
2. Configure an OAuth2-Account (in this case for [CodiMD](https://github.com/hackmdio/codimd)).
3. Authenticate over OAuth2.
4. Try to call `/ocs/v2.php/cloud/user?format=json` using the OAuth2 bearer token as authentication, see [here](https://github.com/hackmdio/codimd/issues/1056#issuecomment-439226358)

### Expected behaviour
The user info should be returned as JSON.

### Actual behaviour
One gets redirected to `/login/selectchallenge?redirect_url=/ocs/v2.php/cloud/user%3Fformat%3Djson`, which shouldn't happen when using the OAuth2 bearer token.

### Server configuration

**Operating system**: Linux

**Web server:** nginx

**Database:** PostgreSQL

**PHP version:** 7.2.12

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated.

**Where did you install Nextcloud from:** Arch Linux repositories

(this is my data, but it the problem occurs for @SISheogorath too, I don't know his setup.)

---

This problem was discovered in an [issue over at CodiMD](https://github.com/hackmdio/codimd/issues/1056). When using Nextcloud as OAuth2 provider signing in fails if 2FA ist enabled, as it turned out, because Nextcloud redirects the profile request to the `selectchallenge` page.

**Comment by stjosh** [comment]
I'm seeing this issue as well. None of the issues referenced above is related. Will try come up with a PR.

**Comment by stjosh** [comment]
I guess [this TODO](https://github.com/nextcloud/server/blob/master/core/Middleware/TwoFactorMiddleware.php#L106) would already be a hint: `// TODO: dont check/enforce 2FA if a auth token is used`
