### ISSUE TITLE
exclude `core/skeleton/` from code integrity checker

### ISSUE THREAD

**Issue by nutzmdm** [nextcloud/server#1249]
Please consider to exclude `core/skeleton/` from code integrity checker like theme folder and some other folders

**Comment by LukasReschke** [comment]
Use https://github.com/nextcloud/server/blob/3209a81e63156b68caa34356630323da4daa4a2f/config/config.sample.php#L217-L222 instead for the skeleton. The themes should already be excluded, can you double check on that?

**Comment by nickvergessen** [comment]
https://help.nextcloud.com/t/need-to-ignore-integrity-check/3041
