### ISSUE TITLE
Update with updater from Nextcloud 15 Beta 1 to Beta 2 not possible

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#12497]
### Steps to reproduce
1. Have Nextcloud 15 Beta 1 installed (manual upgrade from 14.03)
2. Go to settings --> Nextcloud 15 Beta 2 is offered
3. Open the updater, Click on "Start update"
4. Nothing happens

### Expected behaviour
Upgrade to 15 Beta 2

### Actual behaviour
Nothing

I am not sure if the entry in the apache error log is related. It shows up when selecting settings...
I will try a manual upgrade to Beta 2 later.
Edit: Manual upgrade went smooth as usual.

Hope, this information helps.

### Server configuration

**Operating system**: Ubuntu 16.04.5

**Web server:** Apache/2.4.18

**Database:** 10.0.36-MariaDB

**PHP version:** 7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 15.0.0 beta 1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.2.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.7.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - support
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
     XXXXXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "httpsXXXX",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "15.0.0.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "skeletondirectory": "\/var\/www\/default-files",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox 63.0

**Operating system:** Ubuntu 18.04.01

#### Web server error log
<details>
<summary>Web server error log</summary>

[Fri Nov 16 19:37:27.385926 2018] [authz_core:error] [pid 1349] [client IP:PORT] AH01630: client denied by server configuration: /var/www/test-nextcloud/data/.ocdata

</details>

**Comment by MichaIng** [comment]
I ran into the same, trying to update from Beta 2 to RC1.

Browser console shows:
```
overview:332 [Intervention] Images loaded lazily and replaced with placeholders. Load events are deferred. See https://crbug.com/846170
core.js?v=5e08b054:7 JQMIGRATE: Migrate is installed, version 1.4.0
overview:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://my.domain.org/nextcloud/core/fonts/Nunito-Bold.woff2
overview:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://my.domain.org/nextcloud/core/fonts/Nunito-Regular.woff2
overview:1 Failed to decode downloaded font: https://my.domain.org/nextcloud/core/fonts/Nunito-Bold.woff2
overview:1 OTS parsing error: invalid version tag
overview:1 Failed to decode downloaded font: https://my.domain.org/nextcloud/core/fonts/Nunito-Regular.woff2
overview:1 OTS parsing error: invalid version tag
overview:1 [Intervention] Slow network is detected. See https://www.chromestatus.com/feature/5636954674692096 for more details. Fallback font will be used while loading: https://my.domain.org/nextcloud/core/fonts/Nunito-Regular-latin-ext.woff2
overview:1 Failed to decode downloaded font: https://my.domain.org/nextcloud/core/fonts/Nunito-Regular-latin-ext.woff2
overview:1 OTS parsing error: invalid version tag
Resource interpreted as Document but transferred with MIME type application/zip: "https://download.nextcloud.com/server/prereleases/nextcloud-15.0.0RC1.zip".
updatenotification.js?v=5e08b054:1 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

    at HTMLScriptElement.<anonymous> (updatenotification.js?v=5e08b054:1)
    at Function.each (core.js?v=5e08b054:2)
    at a.fn.init.each (core.js?v=5e08b054:2)
    at Object.success (updatenotification.js?v=5e08b054:1)
    at j (core.js?v=5e08b054:2)
    at Object.fireWith [as resolveWith] (core.js?v=5e08b054:2)
    at x (core.js?v=5e08b054:4)
    at XMLHttpRequest.<anonymous> (core.js?v=5e08b054:4)
(anonymous) @ updatenotification.js?v=5e08b054:1
each @ core.js?v=5e08b054:2
each @ core.js?v=5e08b054:2
success @ updatenotification.js?v=5e08b054:1
j @ core.js?v=5e08b054:2
fireWith @ core.js?v=5e08b054:2
x @ core.js?v=5e08b054:4
(anonymous) @ core.js?v=5e08b054:4
load (async)
send @ core.js?v=5e08b054:4
ajax @ core.js?v=5e08b054:4
(anonymous) @ updatenotification.js?v=5e08b054:1
j @ core.js?v=5e08b054:2
fireWith @ core.js?v=5e08b054:2
x @ core.js?v=5e08b054:4
(anonymous) @ core.js?v=5e08b054:4
load (async)
send @ core.js?v=5e08b054:4
ajax @ core.js?v=5e08b054:4
clickUpdaterButton @ updatenotification.js?v=5e08b054:1
t @ updatenotification.js?v=5e08b054:7
e._withTask.e._withTask @ updatenotification.js?v=5e08b054:7
```

Looks like wrong CSP for updater script:
> 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'"

The "failed to decode downloaded font" error shows up on every page, so this is not related and will check and create separate issue in case.

**Comment by Nils160988** [comment]
Fixed for the update from 15 RC2 to RC3, can be closed now!

**Comment by MichaIng** [comment]
Jep worked well now.
