### ISSUE TITLE
[NC15] Videoplayer overlay is missing the close (X)  button to end playback or close the player

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#12508]
The videoplayer overlay is missing the close (X) button.

![1](https://user-images.githubusercontent.com/31093459/48662906-2b240480-ea89-11e8-9460-eaa43bb978ed.png)

**Steps to reproduce**
    Login to Nextcloud, double-click on a video file to start playback. The videoplayer overlay begins to play.

**Expected behaviour**
    When hovering the cursor over the video, the close (X) button should become visible to offer the possibility to end playback.

**Actual behaviour**
    When hovering the cursor over the video, no close (X) button is visible. There are no other options to end the playback, other than to temporary pause playback, refresh the page to start from scratch, or to wait till the video ends. 

**Server configuration**
Operating system: ubuntu 16.04.5
Web server: apache2
Database: mysql
PHP version: 7
Nextcloud version: 15.0.0 beta 2
Updated from an older Nextcloud/ownCloud or fresh install: upgraded from 15.0.0 alpha.

**Comment by timmersr** [comment]
This has been fixed in Nextcloud 15 RC1

**Comment by timmersr** [comment]
This issue has been reintroduced in Nextcloud RC2

**Comment by timmersr** [comment]
Nevermind. Somehow can't reproduce anymore.

**Comment by timmersr** [comment]
NC 15.0.0 - intermittent issue, but I've got a screenshot now:
![6](https://user-images.githubusercontent.com/31093459/49763463-01977b00-fccd-11e8-8b71-de41e1b65bba.png)

**Comment by raneon** [comment]
I miss in Nextcloud 15 as well the close icon. I can click an invisible one by pretending it is there, but it is not visible anymore.

**Comment by rullzer** [comment]
This is fixed with the recent videoplayer fixes in 16

**Comment by timmersr** [comment]
Any possibility to have this fixed in 15?
