### ISSUE TITLE
App Page not available after Upgrade to 15 Beta 2

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#12507]
### Steps to reproduce
1. Log in to your nextcloud with an account with administrative privileges
2. Click on "Apps" in the right hand menu
3. Blank page appears (only the header is visible)

### Expected behaviour
See the usual page with all apps and options to disable, install, remove ... apps

### Actual behaviour
Nothing on the page

It worked with Beta 1. If necessary, I can do further test and provide logs. 
Help will be appreciated.

### Server configuration

**Operating system**: Ubuntu 16.04.5

**Web server:** Apache/2.4.18

**Database:** 10.0.36-MariaDB

**PHP version:** 7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 15.0.0 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.2.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.7.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - support
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
     XXXXXX"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "httpsXXXX",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "15.0.0.6",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta",
        "skeletondirectory": "\/var\/www\/default-files",
        "maintenance": false,
        "loglevel": 2,
        "theme": "",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 63.0

**Operating system:** Ubuntu 18.04.01

**Comment by MorrisJobke** [comment]
@Nils160988 Could you check the web browsers dev tools for errors? Typically you can open them in any browser with F12.

**Comment by MorrisJobke** [comment]
@Nils160988 Just to confirm: This is happening for you in Firefox 63? Could you check with Chrome/Chromium? Could you clear the browser cache and load the page again?

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
Data from server are the same, so yes, clearing cache seems like the issue here.

**Comment by Nils160988** [comment]
Clearing the cache helped for me.

Not sure if this information helps: I am using multiple nextcloud accounts (test.DOMAIN.de and DOMAIN.de) on this laptop. Is it possible that this has to do with the issue?

**Comment by skjnldsv** [comment]
It should not. Only the browser cache would make a difference here :)
