### ISSUE TITLE
[NC15] "File not found" after login, related to avatar

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#12511]
"File not found" after login, related to the avatar.  

An avatar.jpg is referenced, but a avatar.png is present.

![3](https://user-images.githubusercontent.com/31093459/48663806-aab7d080-ea95-11e8-90c5-f33f3f12fa22.png)

_Logging:_
[no app in context] Debug: No cache entry found for /appdata_oc4wpscpy439/avatar/administrator/avatar.jpg (storage: local::/var/www/html/nextcloud/data/, internalPath: appdata_oc4wpscpy439/avatar/administrator/avatar.jpg)

GET /index.php/apps/files/?fileNotFound=1
from (...) by administrator at 2018-11-17T17:08:06+00:00

![4](https://user-images.githubusercontent.com/31093459/48663828-0aae7700-ea96-11e8-962e-810190f0d529.png)

Server configuration
Operating system: ubuntu 16.04.5
Web server: apache2
Database: mysql
PHP version: 7
Nextcloud version: 15.0.0 beta 2
Updated from an older Nextcloud/ownCloud or fresh install: upgraded from 15.0.0 alpha.

**Comment by ChristophWurst** [comment]
Sounds like a duplicate of https://github.com/nextcloud/server/issues/8635
