### ISSUE TITLE
Old background in favicon-fb.png

### ISSUE THREAD

**Issue by splitt3r** [nextcloud/server#12519]
### Steps to reproduce
Have a look at https://github.com/nextcloud/server/blob/master/core/img/favicon-fb.png it's still the old background.

Related to https://github.com/nextcloud/desktop/issues/810

### Server configuration

**Nextcloud version:** Nextcloud 14

**Comment by violoncelloch** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
If anyone would like to pick this up, this is a very easy one, perfect good first issue:
1. Open `core/img/favicon-touch.svg` with a vector editor like [Inkscape](https://inkscape.org/)
2. Export the file with 200 x 200 px size and name it `favicon-fb.png`, replacing the old one
3. Compress the png file by opening the terminal, going to the folder, and running the command `optipng -o6 -strip all favicon-fb.png;`

:tada:
