### ISSUE TITLE
[NC15] Mandatory TOTP 2fa prevents login after upgrade from 15.0.0 alpha to beta 2

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#12510]
Mandatory TOTP 2fa prevents login after upgrade from 15.0.0 alpha to beta 2

**Steps to reproduce**
Upgrade from NC 15.0.0 alpha to beta 2. Then try to login.

**Expected behaviour**
The TOTP functionality should be disabled by default, as TOTP app version 1.50 was unsupported in NC 15.0.0 alpha.

**Actual behaviour**
Using TOTP is mandated, but the app (version 1.50) is disabled. A backup-code is requested. Unless the admin account has stored TOTP backup-codes, he/she is unable to login after the upgrade to NC 15.0.0 beta 2.

And once logged in, upgrading the TOTP app to version 2.00 gives mixed results as seen on 2 different servers, 1 server needed the TOTP app first to be removed and reinstalled for it to function, the other was fine with the upgrade. 

Server configuration
Operating system: ubuntu 16.04.5
Web server: apache2
Database: mysql
PHP version: 7
Nextcloud version: 15.0.0 beta 2
Updated from an older Nextcloud/ownCloud or fresh install: upgraded from 14 beta, to 15.0.0 alpha.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
