### ISSUE TITLE
[NC14] scrolling is broken when moving file

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#12512]
Scrolling is broken (block on the top of the window) when trying to move a file with drag&drop.
Tested on Firefox (ubuntu) and Chromium (ubuntu).

### Steps to reproduce
1.Go to the webui in a folder with more sub-folders and files than window height.
2. Click on a file and try to drag&drop it in a folder in the last of the list.
3. Scroll is kapout, you need refresh the page for it re-work.

**Nextcloud version:** 14.0.3 production

**Updated from an older Nextcloud**

**Comment by ChristophWurst** [comment]
ghost -> close
