### ISSUE TITLE
FTP is not supported - no FTP/FTPS

### ISSUE THREAD

**Issue by martingithub45** [nextcloud/server#12520]
Hi there,

I installed NextCloud 14.0.3 with PHP 7.2.8.

I also activated the app "external storage support". When I want to include an FTP/FTPS-Storage, nextcloud says: "Die FTP-Unterstützung von PHP ist deaktiviert oder nicht installiert. Das Hinzufügen von "FTP" ist nicht möglich. Bitte wende Dich zur Installation an den Systemadministrator." So, there is no FTP-Support, it is not activated. I cannon include FTP.

In the help I found:
https://docs.nextcloud.com/server/14/admin_manual/configuration_files/external_storage/ftp.html

My configuration is (phpinfo()):
> FTP enabled
> FTPS enabled
> allow_url_fopen On

The thing is: IT STILL DOES NOT WORK. CAN ANYONE HELP PLEASE? I need to include an external FTP storage.

Thanks,
  Martin

**Comment by ChristophWurst** [comment]
Could you share your php info? Is that also the php config for your (apache) server?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
