### ISSUE TITLE
[NC15] video player cannot close

### ISSUE THREAD

**Issue by maanloper** [nextcloud/server#12523]
### Steps to reproduce
1. Install NC 14.0.3, and update to NC 15 using web updater
2. Open Chrome on Windows 10 (all latest updates)
3. Play an mp4 (e.g. the standard nextcloud one)

### Expected behaviour
Clicking outside of the player or pressing ESC would close the player, or an X would be present somewhere to close it

### Actual behaviour
Cannot close the player in any (obvious) way

### Server configuration

**Operating system**: Ubuntu 18.10

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** PHP7.2-FPM

**Nextcloud version:** 15

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14.0.3

**Where did you install Nextcloud from:** zip

**Comment by timmersr** [comment]
= #12508

**Comment by maanloper** [comment]
My bad, must have missed it while searching for equal problems, indeed the same error.
