### ISSUE TITLE
Allow hiding of download for folder shares as well

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#12526]
Now that we have the option to hide download for files it would be great if we could also add this to folders.

This will require a bit more JS magic of course.

**Comment by ChristophWurst** [comment]
Fixed in https://github.com/nextcloud/server/pull/12531.

**Comment by ChristophWurst** [comment]
cc @juliushaertl for verification :)

**Comment by juliushaertl** [comment]
Yes, this has been implemented.
