### ISSUE TITLE
The files app stopped working

### ISSUE THREAD

**Issue by codesmaker** [nextcloud/server#12528]
Hi,

I've upgraded NC from v13 to v14.0.3. I have a user "john" who can't access his files anymore. When he logs in, the files app keeps loading and trying to fetch the files. I'm getting this error on the server:

`Nov 19 13:25:15 nextcloud {remote} {"Exception":"TypeError","Message":"Argument 1 passed to OC\\Share20\\Share::setSendPasswordByTalk() must be of the type boolean, null given, called in \/var\/www\/nextcloud\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 981","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/sharebymail\/lib\/ShareByMailProvider.php","line":981,"function":"setSendPasswordByTalk","class":"OC\\Share20\\Share","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/apps\/sharebymail\/lib\/ShareByMailProvider.php","line":1127,"function":"createShareObject","class":"OCA\\ShareByMail\\ShareByMailProvider","type":"->","args":[{"id":"1463","share_type":"4","share_with":"ann@domain.com","uid_owner":"john","uid_initiator":"john","parent":"4618013","item_type":"folder","item_source":"4663359","item_target":null,"file_source":"4663359","file_target":"","permissions":"31","stime":"1540467365","accepted":"0","expiration":null,"token":"QiXRgNQbWmayjkk","mail_send":"0","password":null,"share_name":null,"note":null,"fileid":"4663359","storage":"247","path":"files\/FLIB (G&A)","path_hash":"794621e246e8ddaa31cc9ffb718babe4","name":"FLIB (G&A)","mimetype":"2","mimepart":"1","size":"2699390","mtime":"1540455523","storage_mtime":"1540455522","encrypted":"0","unencrypted_size":"0","etag":"5bd17c634016d","checksum":""}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Share20\/Manager.php","line":1037,"function":"getSharesInFolder","class":"OCA\\ShareByMail\\ShareByMailProvider","type":"->","args":["john",{"__class__":"OC\\Files\\Node\\Folder"},true]},{"function":"OC\\Share20\\{closure}","class":"OC\\Share20\\Manager","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Share20\/Manager.php","line":1046,"function":"array_reduce","args":[[{"__class__":"OC\\Share20\\DefaultShareProvider"},{"__class__":"OCA\\FederatedFileSharing\\FederatedShareProvider"},"*** sensitive parameter replaced ***"],{"__class__":"Closure"},[]]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/SharesPlugin.php","line":149,"function":"getSharesInFolder","class":"OC\\Share20\\Manager","type":"->","args":["john",{"__class__":"OC\\Files\\Node\\Folder"},true]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/SharesPlugin.php","line":187,"function":"getSharesTypesInFolder","class":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin","type":"->","args":[{"__class__":"OC\\Files\\Node\\Folder"}]},{"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\DAV\\Connector\\Sabre\\SharesPlugin"},"handleGetProperties"],[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1059,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":981,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Files\\FilesHome"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files\/john",["{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http:\/\/owncloud.org\/ns}fileid","{http:\/\/owncloud.org\/ns}permissions","{http:\/\/owncloud.org\/ns}size","{DAV:}getcontentlength","{http:\/\/nextcloud.org\/ns}has-preview","{http:\/\/nextcloud.org\/ns}mount-type","{http:\/\/nextcloud.org\/ns}is-encrypted","{http:\/\/open-collaboration-services.org\/ns}share-permissions","{http:\/\/owncloud.org\/ns}tags","{http:\/\/owncloud.org\/ns}favorite","{http:\/\/owncloud.org\/ns}comments-unread","{http:\/\/owncloud.org\/ns}owner-id","{http:\/\/owncloud.org\/ns}owner-display-name","{http:\/\/owncloud.org\/ns}share-types"],1]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":359,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"http:\/\/net.domain.com\/nextcloud\/remote.php\/dav\/files\/john\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"http:\/\/net.domain.com\/nextcloud\/remote.php\/dav\/files\/john\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"http:\/\/net.domain.com\/nextcloud\/remote.php\/dav\/files\/john\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"http:\/\/net.domain.com\/nextcloud\/remote.php\/dav\/files\/john\/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Server.php","line":293,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/lib\/private\/Share20\/Share.php","Line":410,"CustomMessage":"--"}`

The issue was partially fixed by following [https://github.com/nextcloud/server/commit/24a2107e035bf4658f611d070fc2b3f641191430](url)

Basically, I've edited the file apps/sharebymail/lib/ShareByMailProvider.php as follows:
from
`$share->setSendPasswordByTalk($data['password_by_talk']);`
to
`$share->setSendPasswordByTalk((bool)$data['password_by_talk']);`

The user now can see his files but something else has broken. When he shares a folder of a file "by email", not by "user name" from the suggestion list, he gets the following error:

`An exception occurred while executing 'INSERT INTO `oc_share` (`share_type`, `item_type`, `item_source`, `file_source`, `share_with`, `uid_owner`, `uid_initiator`, `permissions`, `token`, `password`, `password_by_talk`, `stime`, `file_target`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [4, "file", 5029462, 5029462, "peter@domain.com", "john", "john", 1, "nQRmYw4KryEz6it", null, false, 1542633137, ""]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password_by_talk' in 'field list'`

I have no idea why that account was affected but after I did the change I mentioned above, the share by email stoped working for all users.

EDIT: one correction is that sharing by email isn't broken because of the change I made. It seems that it was broken because of the upgrade of NC to v14.0.3

**Comment by MorrisJobke** [comment]
Fixed by #11802 in 14.0.4
