### ISSUE TITLE
Stay logged in check box missing in Nextcloud 14

### ISSUE THREAD

**Issue by RandieM** [nextcloud/server#12534]
Unfortunately, I could not find any relevant information anywhere, so it would be great if somebody could share the answer to this.

The "Stay logged in" check box has been removed from the log-in page in Nextcloud 14. On the other hand, $remember_login in the tryLogin() function seems to be set to true, while it was set to false in previous NC versions. What is the actual behaviour? Is there a way to bring back the check box?

Thanks!

**Comment by ChristophWurst** [comment]
This was removed intentionally: https://github.com/nextcloud/server/pull/9109 https://github.com/nextcloud/server/issues/8004
