### ISSUE TITLE
installer could not read or write "/var/www/nextcloud/config/config.php.orig"

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#12549]
Completely new install of NC 14..0.3, Ubuntu 18.0.4

Create backup
Could not copy "/var/www/nextcloud/config/config.php.orig" to "/var/nc_data/updater-ocel8388flt1/backups/nextcloud-14.0.3.0/config/config.php.orig". Source /var/www/nextcloud/config/config.php.orig is not readable. Destination /var/nc_data/updater-ocel8388flt1/backups/nextcloud-14.0.3.0/config/config.php.orig is not writable

### Steps to reproduce
1. Start installer for NC 15.0.0 beta 2
2.Installation stops at Create backup.

**Comment by danielkesselberg** [comment]
I guess you made a backup of config.php while you were logged in as root? config.php.orig does not belong to nextcloud. Move it anywhere else (outside nextcloud directory) and try again.
