### ISSUE TITLE
Password protect button on link shares is too wide

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#12557]
cc @nextcloud/designers on latest master
![password protect submit](https://user-images.githubusercontent.com/925062/48784845-c4e6ee00-ece3-11e8-89b2-d679f86eb719.png)

**Comment by skjnldsv** [comment]
@jancborchardt Hum, there is a rule dedicated to this here: https://github.com/nextcloud/server/pull/12491/files#diff-beb0f4dcc04979e80858de2c3efcc54eR72

Could you make sure your cache is cleared? :)

**Comment by MorrisJobke** [comment]
I also can't reproduce.

**Comment by jancborchardt** [comment]
Right, was a caching issue. Sorry about that! :)
