### ISSUE TITLE
User-menu-dropdown: Full row should be clickable

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#12550]
In the user-menu dropdown, only the text and the icon of the specific row is clickable. It should be the whole row. Tested with Nextcloud 15 beta1.

<img width="146" alt="bildschirmfoto 2018-11-20 um 13 16 33" src="https://user-images.githubusercontent.com/19711361/48773093-a0304d80-ecc6-11e8-84ab-90651e89df22.png">

@nextcloud/designers @skjnldsv

**Comment by jancborchardt** [comment]
This will be addressed in https://github.com/nextcloud/server/pull/9752 which I need to revive. But it’s nothing new so nothing for 15, too much potential for regression.

**Comment by ChristophWurst** [comment]
@jancborchardt now that we branched off you could fix this for 16 :trollface:

**Comment by skjnldsv** [comment]
@ChristophWurst see #12785
