### ISSUE TITLE
Usability of 3-dot "More Apps" Menu with many Apps

### ISSUE THREAD

**Issue by juliusstoerrle** [nextcloud/server#12565]
As admin I lately get mails with "I can't find app X anymore".
It's not a technical problem, as the apps are activated, but the users can't find them. To find them they need to scroll down in the "More Apps" popover, which is not clearly indicated and overseen by some users.

### Steps to reproduce
1. activate many apps (>15)
2. click on the 3 dots "More Apps" Icon in the Top Nav Bar
3. popover with apps is displayed, some apps are not in the "viewport" as the Popover has a max-height.
4. the scrollbar is not clearly visible (in Sarafi only a slim grey bar)

### Expected behaviour
Users should find all apps with ease

### Actual behaviour
As the target should be to make it easily usable to all users, I feel like this popover should be revisited.
I don't think it is good  to get rid of the popover max-height. Maybe we can indicate with some arrow  that more apps are below or redesign the popover to be fullscreen with a grid layout.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
14.0.3

### Client configuration
**Browser:**
Safari mainly, but Firefox sometimes too

**Comment by ChristophWurst** [comment]
cc @skjnldsv @jancborchardt

**Comment by skjnldsv** [comment]
and @juliushaertl for the menu :)

**Comment by jancborchardt** [comment]
@juliusstoerrle could you show a screenshot?

Normally for a scrolling list it is enough to cut it off at a ½ entry to indicate there's more below. Wo do this in other lists like the share list and should do this here too.

I think the value we use for height of container is 5½ rows, is it?

**Comment by juliusstoerrle** [comment]
cutting it of after half an entry sounds like a viable solution.

I can only provide a screenshot of Chrome:
![grafik](https://user-images.githubusercontent.com/25788444/49343601-edb89d00-f66c-11e8-95aa-3d0b95c29ef9.png)

As you can see the scrollbar is there, but melts into the shadow and some users just dont look that closely.

**Comment by skjnldsv** [comment]
@juliusstoerrle That's the issue. We usually try to have an half entry on every menu :)

**Comment by jancborchardt** [comment]
@juliusstoerrle there is a pull request to fix this at https://github.com/nextcloud/server/pull/12785 – could you review and see if this fix works for you? :slightly_smiling_face:

**Comment by MorrisJobke** [comment]
This is how it looks like on Safari:

![bildschirmfoto 2019-01-29 um 12 01 26](https://user-images.githubusercontent.com/245432/51903911-a4ab6d80-23bd-11e9-8d35-aeeb7752a33a.png)

**Comment by skjnldsv** [comment]
What the hell.
Let me fix it!

**Comment by MorrisJobke** [comment]
Sorry - wrong ticket - commented over there.
