### ISSUE TITLE
Folders shared by me to a group containing me behave bad in "shared with me" section

### ISSUE THREAD

**Issue by dirkpape** [nextcloud/server#1256]
### Steps to reproduce
1. create a new folder A on the server in the root dir of your nextcloud account
2. create a new folder B in this folder A
3. share folder B to a group containing yourself and others
4. go to the "shared **with** me" section of the files app.  
5. click on the Folder --> Bug: nextcloud shows the root of you nextcloud
6. click on the share icon --> Bug: share section in info tray opens but will eternally show the spinning circle

### Expected behaviour
Ether the Files app should not show any folders, which I share with a group containing myself in the section "shared with me" or if it does it should behave like the section "shared by me", which does the following:

In 5. the Files app should open the folder.
In 6. the Files app should show the sharing info "shared with group X" instantly.

Section "shared with me" behaves well, if the shared folder is directly in the root (like the Folder B in my example).

### Actual behaviour
5. click on the Folder --> Bug: nextcloud shows the root of you nextcloud
6. click on the share icon --> Bug: share section in info tray opens but will eternally show the spinning circle

### Server configuration
**Operating system**:
Ubuntu 14

**Web server:**
Apache/2.4.7 (Ubuntu)

**Database:**
Type: mysql
Version: 5.5.50 

**PHP version:**
7.0.9

**Nextcloud version:** (see Nextcloud admin page)
10.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
from owncloud 9.0.2 via nextcloud 10RC1

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.3.2
  - announcementcenter: 2.0.0
  - apporder: 0.2.0
  - calendar: 1.3.3
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - direct_menu: 0.9.1
  - documents: 0.13.1
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - html5_videoplayer: 1.0
  - logreader: 1.1.5
  - mail: 0.5.3
  - news: true
  - notifications: 0.3.0
  - polls: 0.7.1
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - spreedme: 0.3.1
  - systemtags: 1.0.2
  - tasks: true
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "518cbe88de454",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "forcessl": true,
        "forceSSLforSubdomains": false,
        "default_language": "de_DE",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "trusted_domains": [
            "oc.drdpc.de",
            "meet.drdpc.de"
        ],
        "mail_smtpmode": "php",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "noreply",
        "mail_domain": "oc.drdpc.de",
        "mail_smtphost": "localhost",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "maintenance": false,
        "enable_avatars": true,
        "appstore.experimental.enabled": true,
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379,
            "timeout": 0
        },
        "trashbin_retention_obligation": "auto",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "asset-pipeline.enabled": false,
        "updater.release.channel": "beta",
        "debug": true
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Safari

**Operating system:**
MacOS X

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
nothing in log level warning
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Ah mmm right. I'll take care of that. They should not show up there in the first place IMO ;)
