### ISSUE TITLE
Time Stamp changes to Unix Timestamp 0 if shared and deleted but still shared 

### ISSUE THREAD

**Issue by MrMarioMichel** [nextcloud/server#12564]
### Steps to reproduce
1. Have two running Nextcloud Server.
2. Share a file via remote (for example : user2@nextcloudserver2.com.
3. Remove/Shutdown/Format ;) the Server where the shared file is stored.
4. Navigate to the server where the shared file should be shared too.
5. Open file details --> see time stamp.

### Expected behaviour
The time stamp shoud be removed or displayed as (not available)

### Actual behaviour
File changes time stamp to the 1. Jan 1970

![capture](https://user-images.githubusercontent.com/30075959/48825018-6020a780-ed66-11e8-8255-852d9bd50a00.PNG)
![captureasd](https://user-images.githubusercontent.com/30075959/48825020-6151d480-ed66-11e8-9741-5745dc4a63f3.PNG)

### Server configuration

**Operating system: Ubuntu 18.04 LTS**

**Web server: Apache2**

**Database: MySQL**

**PHP version: 7.2**

**Nextcloud version: 14.0.3** 

**Just Installed Nextcloud few days and just imported old DB**

**Where did you install Nextcloud from: Official Website**

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.3
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - drawio: 0.9.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_downloadactivity
  - files_external
  - radio
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "michels.duckdns.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "http:\/\/192.168.1.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one: /mnt/nextclouddata**

**Are you using encryption: No**

**Are you using an external user-backend, if yes which one: No**

### Client configuration
**Browser: Chrome Version 67.0.3396.99 (Official Build) (64-bit)**

**Operating system: Microsoft windows 10 Enterprise Version 10.0.16299 Build 16299**

#### Web server error log
<details>
<summary>Web server error log</summary>

[Tue Nov 20 06:25:06.891067 2018] [ssl:warn] [pid 32498] AH01909: michels-server.lan:443:0 server certificate does NOT include an ID which matches the server name
[Tue Nov 20 06:25:06.891322 2018] [mpm_prefork:notice] [pid 32498] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Tue Nov 20 06:25:06.891328 2018] [core:notice] [pid 32498] AH00094: Command line: '/usr/sbin/apache2'

</details>

#### Nextcloud log (data/nextcloud.log)

[Nextcloud.log](https://gist.github.com/MrMarioMichel/440f3e3f870f8b2705ab9a62ebe9a56f)

**Comment by MrMarioMichel** [comment]
Update : I tried to delete this shared file but it is not possible tue to it's not there to unshare. 

Error deleting the File  "<filename>.txt"

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
