### ISSUE TITLE
[NC14] [Webui] "Admin" -> "User" -> "Last Connexion" is out of date

### ISSUE THREAD

**Issue by voxdemonix** [nextcloud/server#12566]
Last connexion displayed in Admin -> User is out of date for some users.
I think, but not totally sur, this problem come from token.
This is just a little bug.

### Steps to reproduce
1. Connect some user via nextcloud apps or webdav remote storage.
2. Connect on your admin user and go to managing user page.
3. Show user last connexion.

Nextcloud 14.0.3 production

**Comment by rullzer** [comment]
It is last login. A login only happens with the username and passwords. Authentication with an app password is not considered a login.

**Comment by voxdemonix** [comment]
Okey thanks.
It can be a good idea to replace "Last connexion" by "Last login (only on webui ?)" for do not disturb nextcloud admin :) (especially when he is deleting inactive accounts)
