### ISSUE TITLE
Opening Folders in "Shares" not possible

### ISSUE THREAD

**Issue by TheElbenreich** [nextcloud/server#12569]
### Steps to reproduce
1. Log in as specific user (user specific problem to some users only)
2. Click on "Shares"
3. Click on any shared folder

### Expected behaviour
Clicked folder should open.

### Actual behaviour
Page reloads without opening the folder. Same view again.

### Workaround found
When right-clicking the folder and select "open folder in new tab", it works and the folder opens its content in a new tab.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Plesk (Apache proxied through Nginx)

**Database:**
MySQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
14.0.3 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 12 to 13 to 14.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_external: 0.4
  - user_saml: 2.0.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "versions": "false",
        "loglevel": 3,
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "forcessl": true,
        "theme": "",
        "trusted_domains": [
            "files.yfu.ch"
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto, auto",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/files.yfu.ch",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
Active-Directory SSO, backend still on MySQL (user needs to be privisioned)

### Client configuration
**Browser:**
Irrelevant, appears on all major browsers.

#### Web server error log
No web server errors. Only access-entries:
![grafik](https://user-images.githubusercontent.com/8981213/48843186-485d1980-ed8e-11e8-9e2f-73b2f878f50b.png)

#### Nextcloud log (data/nextcloud.log)
Nothing is being logged when clicking or reloading the page.

#### Browser log
![grafik](https://user-images.githubusercontent.com/8981213/48843508-26b06200-ed8f-11e8-8b4f-5758dba2f7f6.png)
![grafik](https://user-images.githubusercontent.com/8981213/48844687-76445d00-ed92-11e8-934f-9ebffdfd6ed8.png)

**Comment by Doomas** [comment]
I have exactly the same issue but a slightly different configurationen

**Operating system:**
Debian 9

**Database:**
Postgresql

**PHP version:**
7.0

**Nextcloud version: (see Nextcloud admin page)**
15.0.0 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 12 to 13 to 14 to 15.

I think @TheElbenreich is right that it seems to be an frontend issue. 

This happens only when i try to access the share trough "Shares" . Furthermore the problem seems to affect only folders not files.

Accessing the folder trough "All Files" works without problems

**Comment by Doomas** [comment]
This looks like the same issue #13028

**Comment by kesselb** [comment]
Does this problem still exist?

**Comment by Doomas** [comment]
No, it works now For me the issue is resolved.

Thanks!

**Comment by kesselb** [comment]
Thank you :+1:
