### ISSUE TITLE
Logout keeps old URL as redirect URL in Firefox?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#12568]
@schiessle and me experience this problem in Firefox. Neither Chromium nor Safari suffers from this issue, but we have not idea what's causing it.

1. As an admin log in
2. Go to admin settings
3. Click log out
4. URL is now `index.php/login?redirect_url=/index.php/settings/admin/overview`
5. Log in as a normal user
6. :boom: 
> **Access forbidden**
> Logged in user must be an admin

Actually the mistake is in step 4. After the logout you should not have the redirect_url anymore. Happens in latest 14 + master, not sure when it started.

**Comment by nickvergessen** [comment]
The problem is:
https://github.com/nextcloud/server/blob/85eb43baffac1f5836d08161ced19b98e71189c0/core/Controller/LoginController.php#L134

If I remove this, the redirect works as intended. With this line the current page is reloaded, instead of the login page being loaded as requested by the redirect. This causes the middleware to throw NotLoggedIn error, redirecting to the login page with redirect parameter:
https://github.com/nextcloud/server/blob/8c1e75e0520d0efe51b615952329b1980d21f8b6/lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php#L246-L250

According to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Clear-Site-Data that is exactly what should happen. But https://www.w3.org/TR/clear-site-data/#grammardef-executioncontexts says that is how it should be. Any idea what we could do @rullzer

**Comment by rullzer** [comment]
:see_no_evil: so the reason it works on chrome is that is doen't recognize `executionContext`

**Comment by nickvergessen** [comment]
Well, or they take location into account too

**Comment by nickvergessen** [comment]
Okay, so remove it as a current workaround?

**Comment by rullzer** [comment]
So what I think would make sense:

1. Remove for now.

And as a fix we can do

1. In logout add a session variable
2. In login check this variable if set => clear variable and clear execution context

Does that sound sane?

**Comment by rullzer** [comment]
I'll try to implement that this evening to see if it works.

**Comment by nickvergessen** [comment]
Sounds good

**Comment by tfd0207** [comment]
Excuse me if i react on this one. I am not a developer bu came here from a google search.

I have / had this problem too. Looked at the code an verified it against the Clear-Site-Data Header specs.

It seems to me that the quotation marks in the directives are wrong.

I delete the quotation marks around directives on line 134.  So my code looks like this...

> `		$response->addHeader('Clear-Site-Data', 'cache, storage, executionContexts');`

On my site a have no longer this redirect issue. No errors. Maybe this helps.

By the way... Nextcloud 14.0.4, Firefox 63.0.3 in Linux Mint 19

If it is not the way it should be or i am missing something, ignore my idea :o)

**Comment by BstAA** [comment]
With the changes from [tfd0207 ](https://github.com/nextcloud/server/issues/12568#issuecomment-441400943) it works for me on all browsers.
But even with Nextcloud 15.0.2 it's not fixed ;-)

**Comment by m-i-k-e-y** [comment]
Can confirm the findings of tfd0207 and BstAA:

changing line 134 in LoginController.php in NC 15.0.2 from

>         $response->addHeader('Clear-Site-Data', '"cache", "storage", "executionContexts"');

to

>         $response->addHeader('Clear-Site-Data', 'cache, storage, executionContexts');

solves the issue in Firefox.

**Comment by BstAA** [comment]
> 
> 
> Well the fix works because (as stated in [#12568 (comment)](https://github.com/nextcloud/server/issues/12568#issuecomment-441400943)) the quotation marks are needed per RFC. Without it they are just ignored.

Your right and I've seen you closed  [#13267](https://github.com/nextcloud/server/pull/13267?_pjax=%23js-repo-pjax-container#issuecomment-451107142) just yesterday BUT: Even if the NC code is right as per RFC Firefox users get into trouble. -> As as well Chrome as Edge act right even with the patch. Why not use it as long as Firefox uses it's own interpretation and opening a bug report for Firefox?

By the way, I'm a brand new NC user with nearly no experience in php-programming.

**Comment by nickvergessen** [comment]
The problem is when you remove the quotes, Firefox ignores it and does not clear executeContexts anymore. So that leaves FF users in an even worse state.

**Comment by tgunr** [comment]
Seems to still be an issue, got into a state where FF 87.0 (64-bit) on MacOS 11 could not login due to redirect. Removed the " from addHeader line and now able to see dashboard.
