### ISSUE TITLE
"App up to date" should be plural

### ISSUE THREAD

**Issue by keunes** [nextcloud/server#12574]
Currently the string "App up to date" in  /app/settings/js/apps.js:539 should be plural I think (as in "App*s* up to date"). I just updated multiple apps and then arrived to an empty screen with this string.

I think it should only be singular if admins only have one single app installed (which is hard to imagine).

**Comment by MorrisJobke** [comment]
Wit Nextcloud 14 we changed the behavior there and the empty screen is not visible anymore. As this is only a minor issue I would close this and not look into a fix for Nextcloud 13.

I hope that's okay for you.
