### ISSUE TITLE
Logout issue when using multiple nextcloud instances in parallel with Firefox

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#12575]
### Steps to reproduce
1. Log in to 2 different instances of nextcloud in 2 tabs in firefox browser. Regardless which usernames are used.
2. Log out in one of the instances
3. Try to do anything in the other instance

### Expected behaviour
It should still be possible to use the other nextcloud instance where you didn't log out

### Actual behaviour
You are logged out of both instances

### Server
Nextcloud 13.0.7 and 14.0.3 on different servers (federated)
Instance 1: cloud.[myclouddomain].de (shared webhosting server)
Instance 2: cloud.server.[myclouddomain].de (own physical server)

### Client configuration
**Browser:**
Mozilla Firefox 63.0.1

**Operating system:**
Manjaro Linux

**Comment by MorrisJobke** [comment]
Fixed by #11847

**Comment by MorrisJobke** [comment]
Will be shipped in 13.0.8, 14.0.4 and 15.0.0
