### ISSUE TITLE
 nextcloud14 can't run openwrt v18.06.1 

### ISSUE THREAD

**Issue by cooboyno111** [nextcloud/server#12579]
### Steps to reproduce
1.make openwrt v18.06.1 with php7.2 all depends package and nginx,sqlite3db
2. put setup_nextcloud.php and nc.zip to /www
3. do setup_nextcloud.php an install nextcloud14
4. do first nextcloud14 install page

### Expected behaviour
Tell us what should happen
install page ，choose db,username
### Actual behaviour
Tell us what happens instead
内部服务器错误
### Server configuration
user www www;
worker_processes 1;

#error_log logs/error.log;
#error_log logs/error.log notice;
#error_log logs/error.log info;

#pid logs/nginx.pid;

events {
worker_connections 1024;
}

http {

server {
listen 80;
listen [::]:80;
root /mnt/sda1/nextcloud/;
index index.php index.html index.htm;
server_name example.com www.example.com;

location / {
    rewrite ^ /index.php$uri;
}

location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
    deny all;
}
location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
    deny all;
}

location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+|core/templates/40[34])\.php(?:$|/) {
    fastcgi_pass unix:/var/run/php7.1-fpm.sock;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    include fastcgi_params;
    fastcgi_intercept_errors on;
    fastcgi_request_buffering off;
}

location ~ ^/(?:updater|ocs-provider)(?:$|/) {
    try_files $uri $uri/ =404;
    index index.php;
}

location ~ \.(?:css|js|woff|svg|gif)$ {
    try_files $uri /index.php$uri$is_args$args;
    add_header Cache-Control "public, max-age=15778463";
    # Add headers to serve security related headers (It is intended to
    # have those duplicated to the ones above)
    # Before enabling Strict-Transport-Security headers please read into
    # this topic first.
    # add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    #
    # WARNING: Only add the preload option once you read about
    # the consequences in https://hstspreload.org/. This option
    # will add the domain to a hardcoded list that is shipped
    # in all major browsers and getting removed from this list
    # could take several months.
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    # Optional: Don't log access to assets
    access_log off;
}

location ~* \.(?:svg|gif|png|html|ttf|woff|ico|jpg|jpeg)$ {
    try_files $uri /index.php$uri$is_args$args;
    access_log off;
}

**Operating system**:
openwrt 18.06
**Web server:**
nginx
**Database:**
sqlite3
**PHP version:**
php7.2.8
**Nextcloud version:** (see Nextcloud admin page)
14.03
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
https://nextcloud.com/
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```2018/11/22 07:55:24 [error] 1702#0: *1 FastCGI sent in stderr: "Access to the script '/mnt/sda1/nextcloud/index.php/' has been denied (see security.limit_extensions)" while reading response header from upstream, client: 192.168.1.240, server: example.com, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.1-fpm.sock:", host: "192.168.1.1"
2018/11/22 07:55:24 [error] 1702#0: *1 FastCGI sent in stderr: "Unable to open primary script: /mnt/sda1/nextcloud/index.php/favicon.ico (No such file or directory)" while reading response header from upstream, client: 192.168.1.240, server: example.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://unix:/var/run/php7.1-fpm.sock:", host: "192.168.1.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```{"reqId":"IY9yNfoCHHOwBmSGStX3","level":3,"time":"2018-11-22T08:04:13+00:00","remoteAddr":"192.168.1.240","user":"--","app":"base","method":"GET","url":"\/index.php","message":{"Exception":"ErrorException","Message":"call_user_func_array() expects parameter 1 to be a valid callback, function 'session_name' not found or invalid function name","Code":0,"Trace":[{"file":"\/mnt\/sda1\/nextcloud\/lib\/private\/Session\/Internal.php","line":210,"function":"trapError","class":"OC\\Session\\Internal","type":"->","args":[0,"call_user_func_array() expects parameter 1 to be a valid callback, function 'session_name' not found or invalid function name"]},{"file":"\/mnt\/sda1\/nextcloud\/lib\/private\/Session\/Internal.php","line":53,"function":"invoke","class":"OC\\Session\\Internal","type":"->","args":["session_name",["ocmnn5ynu2or"]]},{"file":"\/mnt\/sda1\/nextcloud\/lib\/base.php","line":424,"function":"__construct","class":"OC\\Session\\Internal","type":"->","args":["ocmnn5ynu2or"]},{"file":"\/mnt\/sda1\/nextcloud\/lib\/base.php","line":656,"function":"initSession","class":"OC","type":"::","args":[]},{"file":"\/mnt\/sda1\/nextcloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/mnt\/sda1\/nextcloud\/index.php","line":40,"args":["\/mnt\/sda1\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/mnt\/sda1\/nextcloud\/lib\/private\/Session\/Internal.php","Line":183,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:63.0) Gecko\/20100101 Firefox\/63.0","version":""}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com Keep also in mind that openwrt is not a supported platform. It should work, but we can't guarantee it.

See https://docs.nextcloud.com/server/14/admin_manual/installation/system_requirements.html for the supported platforms.

**Comment by cooboyno111** [comment]
I looked at the source_installation. HTML page again.
https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html
Prerequisites for manual installation;   There is a problem.
Required:
    PHP (>= 7.0, 7.1 or 7.2)
    PHP module ctype
    PHP module dom
    PHP module GD
    PHP module iconv
    PHP module JSON
    PHP module libxml (Linux package libxml2 must be >=2.7.0)
    PHP module mbstring
    PHP module openssl
    PHP module posix
    PHP module SimpleXML
    PHP module XMLReader
    PHP module XMLWriter
    PHP module zip
    PHP module zlib
In fact, a library is missing.
    PHP module session.
After I added the library, it worked.
Please inform the website editors about this problem.

**Comment by MorrisJobke** [comment]
@cooboyno111 Could I ask you to add it directly to this file here: https://github.com/nextcloud/documentation/blob/master/admin_manual/installation/source_installation.rst

There is a little pencil in the top right of the document which allows editing right here on GitHub.
