### ISSUE TITLE
Batch restore file version

### ISSUE THREAD

**Issue by mrflow** [nextcloud/server#1258]
It would be nice to have an option to restore a selection of files to e.g. their previous version, or a version before a certain point in time.

I just had the issue where I accidently emptied the contents of a few hundered CSV files. I solved the problem by manually grabbing the old versions from the owncloud-storage directory of the server, since clicking every file for restoring version would have taken ages.

**Comment by semiversus** [comment]
If you have direct access to the nextcloud server it's possible to revert the files manually by searching through `data/USER/files_versions`. But yeah, I came here while searching for the exact same functionality. Would be nice to (readonly?) mount a webdav share at a specific version (or point in time) maybe by adding a additional parameter to the url.

**Comment by mrflow** [comment]
As written above, that is exactly what I did.

But you bring in a new interesting point that sounds a bit like the snapshot-function of CoW-filesystems. Maybe you want file a new bug for that one?

**Comment by semiversus** [comment]
I started to write a simple script which is generating a folder tree with soft links to the appropriate files. Two arguments have to be given: path to `nextcloud/data` directory and a timestamp. Seems pretty simple at the moment but maybe it's harder than I think right now...

**Comment by sealne** [comment]
Another helpful related option would be to be able to restore directories

**Comment by biva** [comment]
Probably related to https://github.com/nextcloud/server/issues/7473

**Comment by biva** [comment]
I'd like to recover the former versions in `files_version` folder, but they all have an extension like `v1262190079`. For example, how could I rename `Photo 011.jpg.v1262190079` into `Photo 011.jpg`?
Thank you!

**Comment by biva** [comment]
Solution under Windows to rename files in bulk: www.bulkrenameutility.co.uk tick "subfolders" and chose "remove extension"

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by mrAceT** [comment]
I just thought of something like this exactly.. I luckily haven't the need.. but how would it fix a desaster scenario where a user would get hacked and all his/her hundreds of files would get encrypted for ransom..

How could I restore all (or a selection?) of files to a certain date?

What I fear makes things a bit more difficult is that I use AWS-S3 storage..

Some insights would be greatly appreciated
