### ISSUE TITLE
"An unknown error has occurred" when not enough quota

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#12588]
Happens on master:

1. Set the quota of a user to 0 or a few bytes
1. Upload a file as that user
1. Expected :question: https://github.com/nextcloud/server/blob/a793b1027c6fdf0cade31bf84cf64d378f2727b4/apps/files/js/file-upload.js#L1027-L1030 or https://github.com/nextcloud/server/blob/a793b1027c6fdf0cade31bf84cf64d378f2727b4/apps/files/js/file-upload.js#L947-L955
1. Actually throws :boom: https://github.com/nextcloud/server/blob/a793b1027c6fdf0cade31bf84cf64d378f2727b4/apps/files/js/file-upload.js#L1032-L1040

Works fine in stable14

@skjnldsv can you have a look? You modified the upload stuff in general lately?

**Comment by skjnldsv** [comment]
Ah yes, introduced by a793b1027c6fdf0cade31bf84cf64d378f2727b4

**Comment by ChristophWurst** [comment]
@skjnldsv ping? A fix would be awesome :heart:
