### ISSUE TITLE
Server and client flooded by logs

### ISSUE THREAD

**Issue by vasilko** [nextcloud/server#12591]
Hello, I write some issue, I meet today with nextcloud Server and Client after using it some months.

Server1: Nextcloud 13.0.4
Server2: Nextcloud 14.0.3
Client: Version 2.5.0git
Client OS version: Ubuntu 18.04.1 LTS
Client OS version tested: Windows 7 x64.

I have connected two accounts with one client from two servers with versions (14.0.3 and 13.0.4).
When I disable "activity" application on these servers and restart client appliaction, servers and client start generate a huge load and logs. Servers load rises up to 40% of CPUs and apache generated massive access logs. Client also generate (when I press F12 to view) many requests (up to 20 per second) to the server. Also, the traffic between client and server rises up to 3Mbps constantly.

I think, that if this "activity" is an optional aplication, when I disable it,  it does not generate these problems with enabled and installed client on PC/nb.

Operating system of servers is: Centos 7.5.1804. Web server is apache v. 2.4.6. Selinux enabled and enforced. Php is in version 7.0.32. One server is proxied with Apache, second is not. When I enable this application, everything is back to normal. 

Some log from client:
[OCC::ActivityListModel::startFetchJob 	Start fetching activities for  "xxx@cloud.xxx.sk"
[OCC::AccessManager::createRequest 	2 "" "https://cloud.xxx.sk/ocs/v2.php/cloud/activity?page=0&pagesize=100&format=json" has X-Request-ID "d9d118ef-9f95-496d-84fe-707d7f4954ec"
[OCC::AbstractNetworkJob::start 	OCC::JsonApiJob created for "https://cloud.xxx.sk" + "ocs/v2.php/cloud/activity" "OCC::ActivityListModel"
[OCC::WebFlowCredentials::slotFinished 	request finished
[OCC::AbstractNetworkJob::slotFinished 	QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"GET https://cloud.xxx.sk/ocs/v2.php/cloud/activity?page=0&pagesize=100&format=json\"" QVariant(int, 404)
[OCC::WebFlowCredentials::stillValid 	Still valid?
[OCC::WebFlowCredentials::stillValid 	QNetworkReply::NetworkError(ContentNotFoundError)

Thank you for your time to answering.

**Comment by rullzer** [comment]
Should be fixed by https://github.com/nextcloud/desktop/pull/874

**Comment by vasilko** [comment]
Hello,
Now I tested it with new client on windows (Nextcloud-2.5.0.61570-daily-20181122.exe) and everythink is OK. Thank you for your answers and explanations. In Linux I will test it  with new official package from repositories.
