### ISSUE TITLE
»All apps« category in apps management

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#126]
It has always been confusing that to enable a new app, you need to switch the category. In other apps like Files, Contacts etc there is always some kind of »Everything/All« default view (All files, All contacts etc) to see everything.

Hence for apps, we should have an entry »All apps« on the top of the sidebar which includes both Enabled and Disabled apps.

Enabled apps should be sorted first, then below that disabled apps. (And then the entries »Enabled apps / Disabled apps could simply act as anchors of that view.)

cc @LukasReschke and FYI @BernhardPosselt @hannob

**Comment by blizzz** [comment]
Too late for 10, moving to 11.

**Comment by LukasReschke** [comment]
Also would be easier with the new appstore.

**Comment by jancborchardt** [comment]
cc @BernhardPosselt @janibonnevier @adsworth regarding the new appstore. :) We really need this category for a nicer UX and simpler flow.

**Comment by BernhardPosselt** [comment]
Already possible, fully depends on you guys ;)

**Comment by MorrisJobke** [comment]
Too much change involved to get this in -> 12

**Comment by jancborchardt** [comment]
This will be fixed by @eppfel’s »Make apps settings tabular«: https://github.com/nextcloud/server/issues/3195 – so please help reviewing. :)

**Comment by MorrisJobke** [comment]
> This will be fixed by @eppfel’s »Make apps settings tabular«: #3195 – so please help reviewing. :)

It's not ready for reviewing - please fix it first: https://github.com/nextcloud/server/pull/3195#issuecomment-289945782

**Comment by jancborchardt** [comment]
Merged and fixed with https://github.com/nextcloud/server/pull/3195 :)

**Comment by MorrisJobke** [comment]
Also related to https://github.com/nextcloud/server/issues/6868
