### ISSUE TITLE
[PHP 7.2] count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by scroom** [nextcloud/server#12614]
### Steps to reproduce
1. Upgrade to Nextcloud 14.04
2. Access NC

### Expected behaviour
Normal access to nextcloud without errors in error log

### Actual behaviour
Access to nextcloud works, but there are errors in the log:
count(): Parameter must be an array or an object that implements Countable at /var/www/nextcloud/apps/user_ldap/lib/Access.php#883

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 14.04

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14.03

**Comment by danielkesselberg** [comment]
Fix https://github.com/nextcloud/server/pull/12684 will be part of 14.0.5 :tada:
