### ISSUE TITLE
Enable LDAP password changes per user / FreeIPA (solved - Documentation update needed)

### ISSUE THREAD

**Issue by egandro** [nextcloud/server#12613]
I am using Nextcloud 14 (Docker version) with a Free IPA 4.4.4 Server (also a Docker version).

Login & Mapping of Groups is working.

Howerver when enabling "Enable LDAP password changes per user" this does not work.

I added the bind user to admin/trust_admin default admin groups of IPA. But this still doesn't do the trick.

Can somebody please point me to some documentation?

Thx.

**Comment by egandro** [comment]
Ok i found the issue :)

It's the documentation:

https://www.freeipa.org/page/Owncloud_Authentication_against_FreeIPA

In the "Expert Tab"

Override UUID detection / UUID Attribute for Users

Needs to be "uuid" for Free IPA.

**Comment by violoncelloch** [comment]
cc @nextcloud/documentation

**Comment by ChristophWurst** [comment]
@egandro could you please file this in the documentation repo https://github.com/nextcloud/documentation/? Thanks!
