### ISSUE TITLE
Can't update & enable incompatible apps at once (page reload required)

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#12623]
### Steps to reproduce
1. Run 14.0.2
2. Update to 15 RC1
3. Run into https://github.com/nextcloud/server/issues/11102#issuecomment-441213986 (apps in their current version not compatible with the next major version, but update from app store available which apparently aren't fetched, hence the apps get disabled).

### Expected behaviour
I should be able to update & enable these apps in one go.

### Actual behaviour
I could update all outdated apps but the *Enable* button was disabled. A refresh enabled it.

### Server configuration

**Operating system**:
n/a

**Web server:**
n/a

**Database:**
mysql

**PHP version:**
n/a

**Nextcloud version:** (see Nextcloud admin page)
15 RC1

@nickvergessen @rullzer @skjnldsv ideas?

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/8380 looks like it would fix this but apparently it didn't for me.

**Comment by MorrisJobke** [comment]
Might be solved by fixing it this way: https://github.com/nextcloud/server/issues/11102#issuecomment-443176523

Let's close this ticket here for now and work on the above linked one.
