### ISSUE TITLE
/ocs/v1.php/cloud/users/ stopped working

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#1263]
### Steps to reproduce

https://docs.nextcloud.com/server/10/admin_manual/configuration_user/user_provisioning_api.html?highlight=provision#users-getuser

1. `$I->amHttpAuthenticated("admin","admin")`
1. `$I->sendGET("/ocs/v1.php/cloud/users/tester")`

### Expected behaviour

Should work like on ownCloud
`$I->seeResponseCodeIs(200)`

### Actual behaviour

` [Fail]  Failed asserting that 412 matches expected 200.`

### Server configuration
**Operating system**: Travis CI

**Web server:** Apache

**Database:** Any

**PHP version:** Any

**Nextcloud version:** master

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** admin script

-------
Any idea @LukasReschke

**Comment by rullzer** [comment]
You need to pass the header `OCS-APIREQUEST: true`
I'll make sure this is reflected in the docs.

**Comment by rullzer** [comment]
See https://github.com/nextcloud/documentation/pull/158

**Comment by rullzer** [comment]
Docs merged.

**Comment by oparoz** [comment]
There is still a problem as this deviates from the standard:
https://www.freedesktop.org/wiki/Specifications/open-collaboration-services-1.7/

Which means that any client following the standard will stop working with these changes.

@karlitschek , how do we fix this?

**Comment by LukasReschke** [comment]
The standard as described at https://www.freedesktop.org/wiki/Specifications/open-collaboration-services-1.7/ is anyways not properly implemented in Nextcloud nor ownCloud. The specification at  https://github.com/cernbox/OpenCloudMeshSpecification  is more up-to-date and mentions this fact.

**Comment by oparoz** [comment]
Perfect, thank you.
