### ISSUE TITLE
Users quota does’t work correctly

### ISSUE THREAD

**Issue by optimistic5** [nextcloud/server#12637]
Nextcloud version *(13.0.4)* :
Operating system and version *(Ubuntu 18.04)* :
Apache version *(Apache 2.4.29)* :
PHP version *(7.1.18)* :

[details="The output of `/var/www/html/nextcloud/config/config.php` :"]
```
<?php
$CONFIG = array (
  'instanceid' => 'xx',
  'passwordsalt' => 'xx',
  'secret' => 'xx',
  'trusted_domains' => 
  array (
    0 => '192.168.0.138',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => 'http://192.168.0.138/nextcloud',
  'dbtype' => 'mysql',
  'version' => '13.0.4.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xx',
  'dbpassword' => 'xx',
  'installed' => true,
);
```
[/details]

[details="The output of `/etc/apache2/sites-available/nextcloud.conf` :"]
```
<VirtualHost *:80>
     ServerAdmin admin@example.com
     DocumentRoot /var/www/html/nextcloud/
     ServerName 192.168.0.138
     ServerAlias 192.168.0.138

     Alias /nextcloud "/var/www/html/nextcloud/"

     <Directory /var/www/html/nextcloud/>
        Options +FollowSymlinks
        AllowOverride All
        Require all granted
          <IfModule mod_dav.c>
            Dav off
          </IfModule>
        SetEnv HOME /var/www/html/nextcloud
        SetEnv HTTP_HOME /var/www/html/nextcloud
     </Directory>

     ErrorLog ${APACHE_LOG_DIR}/error.log
     CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
```
[/details]

The output of your Nextcloud log in **Admin > Logging**:
https://paste.debian.net/1045395/

**The issue:**
Quota does not work correctly.
1. Create user in Nextcloud and give him **10mb** quota
![](https://i.imgur.com/djLZM58.png)
2. Add this user to Nexcloud client app and add some big folder (more than 10mb). I added 3.8GB folder.
3. The in NC client synchronization will be successful
![](https://i.imgur.com/chXO319.png)
4. Go to NC interface, you will see files which is less than 10mb
![](https://i.imgur.com/XNtFloe.png)
5. Go to your server when NC is installed and open users folder. You will see all this 3.8GB. You can use **ncdu** command
![](https://i.imgur.com/LWSnGa9.png)

**So all this 10mb quota is nothing** :frowning: 

I have another instance with Nextcloud and issue is the same.

Please, fix it.

**Comment by optimistic5** [comment]
UPD. All folders added to nextcloud as external storage SMB

**Comment by johkoenig** [comment]
quota doesn't apply to external storage

**Comment by violoncelloch** [comment]
exactly, as @johkoenig stated...
