### ISSUE TITLE
really new to nextcloud, please help me translate curl into another language.

### ISSUE THREAD

**Issue by leon846666** [nextcloud/server#12635]
I am trying to edit user quota by user provisioning API .
It works with CURL like
curl -u admin:1232018ll -X PUT http://localhost/nextcloud/ocs/v1.php/cloud/users/test -H "OCS-APIRequest"true" -d key="quota" -d value="2GB"

### it works well,
But I'd like to use it in ajax or postman.
**in ajax :**

$.ajax({
     type:"PUT",
     url:"../../../ocs/v1.php/cloud/users/test",
    username:"admin",
    pssword:"1232018ll",
     data:"key=quota&value=2000MB",
     processData:false,
    contentType:"application/json",
    headers:{ "OCS-APIRequest":"true"},
    success:function(data){
     alert(data);
},error:function(data){
     alert("failed")
}
});

### return: 401 unauthorized;

**using PostMan:**

PUT : http://localhost/nextcloud/ocs/v1.php/cloud/users/test

Params: quota 4gb 

Authentication : Basic Auth
              username:"admin",
              pssword:"1232018ll",

Headers:
              OCS-APIRequestv:true
              ContentType:application/json

### return: 401 unauthorized;

What did  i miss?

Please help

**Comment by violoncelloch** [comment]
maybe you better want to place your question in the forum at https://help.nextcloud.com because this is just an issue tracker for bugs and feature requests...
