### ISSUE TITLE
Some files have not passed the integrity check after upgrade to 14.0.4: .l10nignore, Why the Nextcloud Subscription.pdf, Outbox.php

### ISSUE THREAD

**Issue by 74cmonty** [nextcloud/server#12646]
### Steps to reproduce
1. Start manual upgrade, source release is 14.0.3.0
2. Login to WebUI
3. Check Settings - Administration - Overview

### Expected behaviour
No errros reported.

### Actual behaviour
“Some files have not passed the integrity check.”

### Server configuration

**Operating system**:
Alpine Linux 3.8.0
**Web server:**
Nginx 1.14.1
**Database:**
MariaDB 
**PHP version:**
7.2.12
**Nextcloud version:** (see Nextcloud admin page)
14.0.4.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.3.0

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files
	- EXTRA_FILE
		- .l10nignore
- comments
	- EXTRA_FILE
		- .l10nignore
- support
	- EXTRA_FILE
		- resources/Why the Nextcloud Subscription.pdf
- dav
	- EXTRA_FILE
		- lib/CalDAV/Outbox.php
- oauth2
	- EXTRA_FILE
		- .l10nignore
- notifications
	- EXTRA_FILE
		- .l10nignore
- files_versions
	- EXTRA_FILE
		- .l10nignore
- updatenotification
	- EXTRA_FILE
		- .l10nignore
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_notifications: 1.0.2
  - announcementcenter: 3.3.1
  - bookmarks: 0.14.2
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - carnet: 0.9.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.7
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_accesscontrol: 1.4.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - fulltextsearch: 1.1.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - unsplash: 1.1.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```

I have compared the files existing in NC 14.0.3.0 directory and the following files don't exist there:
.l10nignore
lib/CalDAV/Outbox.php
resources/Why the Nextcloud Subscription.pdf

This means the error is logically correct.
However I consider the upgrade to be inconsistent.

**Comment by ChristophWurst** [comment]
>     1. Start manual upgrade, source release is 14.0.3.0

Please elaborate. Are you sure you fully replaced the previous files, as in, did you make sure removed files were removed? These might be leftovers from previous installations.

**Comment by 74cmonty** [comment]
Hi,
I have created a copy of the "old" NC directory.
Comparing the content of the new NC directory (NC 14.0.4.2) with the old directory revealed that the listed files marked as "failed integrity check" **do not exist in NC 14.0.3.0**.
Therefore I conclude that the files are not leftovers or improperly removed. Instead these files were introduced with NC 14.0.4.2 but not identified correctly by integrity check.

**Comment by ChristophWurst** [comment]
According to @MorrisJobke this is an issue with packaging and some being not being extracted from the archive. This is possibly fixed in 14.0.4.

**Comment by 74cmonty** [comment]
Fine.
But maybe you can provide a solution for this issue until new release is available.

**Comment by MorrisJobke** [comment]
We found the issue. The next release will contain a fix for this. You could as of now only disable the code integrity check in config.php if needed. In 15+ the warning at the top will also not be shown anymore.

**Comment by 74cmonty** [comment]
Fair enough.
I disabled integrity check in config.php and restarted the webservice (nginx).
Then I deleted the relevant parameter in config.php, restarted the webservice... et voila, the error message is gone.

**Comment by MorrisJobke** [comment]
I updated the release script to reflect this. So the next version will not have this anymore.

**Comment by MorrisJobke** [comment]
Thanks for the report anyway :)
