### ISSUE TITLE
Comments sent for a file before changing to another one may be shown in the new one

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#12648]
Note that the comment is actually stored in the server in the proper file; the problem is only related to the visualization of the comment in the browser.

When opening the details view for a different file `CommentsTabView.setFileInfo` is called. Although [this resets the collection](https://github.com/nextcloud/server/blob/master/apps/comments/js/commentstabview.js#L104) and thus removes the existing models/comments, `reset` does not abort the current pending requests (see pull 1325 in https://github.com/jashkenas/backbone (I am not linking it directly to prevent the reference from polluting that thread)). Thus, when the response for [the creation of a new message is received](https://github.com/nextcloud/server/blob/375589b274ad6da55f1a516c953b807105dfd2a4/apps/comments/js/commentstabview.js#L676) it is handled in the regular way, that is, adding the model for the new comment to the collection, which causes it to be rendered in the list of comments, even if the request was originally done before the collection was reset.

@nextcloud/javascript 

**How to test:**
- Make fetching comments a bit slower by adding `sleep(3)` to [the beginning of `getChild()` in _apps/dav/lib/Comments/RootCollection.php_](https://github.com/nextcloud/server/blob/813f0a0f40dd42b28cd35d91616f3f87ef400861/apps/dav/lib/Comments/RootCollection.php#L146)
- Open the Files app
- Create two files (or folders)
- Open the _Comments_ tab in the details view for the first file
- Send a new comment
- Open the details view for the other file immediately after sending the comment, without waiting for it to be shown for the first file

**Expected result:**
The _No comments yet_ message is eventually shown

**Actual result:**
The first message is eventually shown, even if the current file is the second one

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
