### ISSUE TITLE
Web installer still points to Nextcloud 9.0.53

### ISSUE THREAD

**Issue by phsc** [nextcloud/server#1264]
### Steps to reproduce
1. Open URL https://nextcloud.com/install/#tab-web
2. Follow the instructions
3. Check your Nextcloud version either in the Web-GUI under "Settings" or on the server in the "version.php"

### Expected behaviour
Nextcloud 10 should be installed, because it is already marked as stable for some days
Furthermore, it would be very nice, if the Web Installer could show, what version, it will install. Currently, this is not transparent to the user.

### Actual behaviour
Nextcloud 9.0.53 has been installed

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache 2.4

**Database:**
MariaDB 10

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
9.0.53

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Web Installer

**Comment by phsc** [comment]
I've just opened an issue in the Web Installer repo. Probably the better place for this problem...
https://github.com/nextcloud/web-installer/issues/4

**Comment by LukasReschke** [comment]
Changed to 10.0.0 :)
