### ISSUE TITLE
More timely Docker image releases

### ISSUE THREAD

**Issue by spantaleev** [nextcloud/server#12640]
Nextcloud 14.0.4 has been out since yesterday (22nd of November), yet there's still no Docker image released for it.

It's probably not too important for this specific release, but it would be nice if Docker images are pushed in a more timely manner. Maybe it should be set up so that they get built and pushed automatically on tag push?

**Comment by violoncelloch** [comment]
cc @nextcloud/docker

**Comment by tianon** [comment]
It's a pretty major holiday weekend in the US (which is arguably not a great time for software releases in general).

**Comment by tilosp** [comment]
Closing in favor of https://github.com/nextcloud/docker/issues/548

**Comment by J0WI** [comment]
This is not a Docker or NextCloud thing. We have the same "issue" with distros, app stores etc.
