### ISSUE TITLE
Integrations for phabricator on nextcloud

### ISSUE THREAD

**Issue by Serkan-devel** [nextcloud/server#12654]
I was thinking about using nextcloud for file-hosting and integrate phabricator for progect management and collaboration.

**Comment by ChristophWurst** [comment]
Is this a feature request?

**Comment by ChristophWurst** [comment]
Any more info?

**Comment by Tectu** [comment]
This is definitely a feature request that I'd like to second.
We use Phabricator exclusively for all of our internal collaboration needs. We started using NextCloud to share files with customers.

**Comment by MorrisJobke** [comment]
I guess there is very little we can do from our side. Nextcloud provides the WebDAV API that can be used by every tool out there. I guess this needs to be implemented or configured on the Phabricator side to upload files to a Nextcloud account.

Thus I will close this here until there are more details about this missing integration that is requested here.
