### ISSUE TITLE
Always show console.log

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1265]
From https://help.nextcloud.com/t/always-show-console-log/2949

> Right now console.log output will only be shown when the debug mode is enabled.
> This comes with various different issues:
> - I'm constantly running my development instance in debug mode
>
> but much worse:
> - Users on hosted instances can't provide JS logs
> 
> I'd appreciate if we could change this behavior and console.log would be shown all the time.

I agree with @georgehrke on this one. It's always helpful if people can provide you with logs when you try to debug some stuff. Only annoying when they would need to set their live instance to debug, hack core files or can't even do one of those things.

I don't really think it can cause a lot of problems

**Comment by LukasReschke** [comment]
Yes! Also there's not really a performance impact, hiding it is in fact making it even slower :see
