### ISSUE TITLE
Loging out CSRF token expired

### ISSUE THREAD

**Issue by megaxlr** [nextcloud/server#12664]
### Steps to reproduce
1. Log in.
2. Wait until the CSRF token has expired.
3. Press the logout button.

### Expected behaviour
Logging the user out despite their CSRF token being expired.

### Actual behaviour
An error message was shown without a button to return to my previous page.

### Server configuration

**Operating system**:
Debian 9

**Web server:**
NGINX

**Database:**
MariaDB 10.2

**PHP version:**
PHP 7.2

**Nextcloud version:** (see Nextcloud admin page)
14.

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
The installer on your website 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Opera 56
**Operating system:**
Debian 9

Relates to: GH-754 "Log in: Access forbidden, CSRF check failed"

**Comment by ChristophWurst** [comment]
Why does the CSRF token expire in the first place?

**Comment by megaxlr** [comment]
Likely because too much time has passed since the user performed any interaction to refresh it.

**Comment by ChristophWurst** [comment]
There is actually a heartbeat mechanism that tries to keep the session alive.

**Comment by MorrisJobke** [comment]
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
