### ISSUE TITLE
OAuth2 implicit grant

### ISSUE THREAD

**Issue by memen45** [nextcloud/server#12667]
As far as I can see implicit grant is not supported by the OAuth2 app. Will it be supported in the future? 

Secondly, if this feature will not be implemented, how can/should OAuth2 be used safely in JavaScript client code to connect to a Nextcloud instance?

**Comment by rullzer** [comment]
It is not. It is on my list. But I can't promise an ETA

**Comment by rullzer** [comment]
See I should not comment when busy.
Implicit grant will not be support by us as it is deemed unsafe. We'll look into other mechanisms.
