### ISSUE TITLE
PDF zoom blurry in Android browser using nc apps

### ISSUE THREAD

**Issue by jcbdg18** [nextcloud/server#12666]
### Steps to reproduce
1. Open a pdf file with drawing like technical drawing in it. It happens in all apps (Pdf viewer, Onlyoffice, Reader (ebook reader)
2. Zoom in on Andoid in browser (Chrome/Firefix or other)

### Expected behaviour
Text and drawing should shown sharp

### Actual behaviour
Text and drawing shows blurry. If i download the file and open it with for example Foxit PDF, it shows correctly

### Server configuration
**Operating system**:
Ubuntu Linux 18.04

**Web server:**
nginx/1.14.0

**Database:**
psql (PostgreSQL) 10.6 

**PHP version:**
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
with Zend OPcache v7.2.10-0ubuntu0.18.04.1, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
13.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
No errors have been found.

**List of activated apps:**
activity	      files		      groupfolders	       sharebymail
admin_audit	      files_automatedtagging  logreader		       survey_client
admin_notifications   files_external	      lookup_server_connector  systemtags
apporder	      files_pdfviewer	      mail		       theming
bruteforcesettings    files_reader	      nextcloud_announcements  theming_customcss
carnet		      files_rightclick	      notifications	       twofactor_backupcodes
comments	      files_sharing	      oauth2		       twofactor_totp
dav		      files_texteditor	      onlyoffice	       updatenotification
defaultlinkopen       files_trashbin	      password_policy	       user_external
drawio		      files_versions	      previewgenerator	       user_ldap
encryption	      files_videoplayer       provisioning_api	       workflowengine
federatedfilesharing  firstrunwizard	      registration
federation	      gallery		      serverinfo

**Nextcloud configuration:**
<?php
$CONFIG = array (
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' => 
  array (
    0 => 'mysub.mydomain.com',
  ),
  'datadirectory' => '/local/app/nextcloud/mysub.mydomain.com/data',
  'overwrite.cli.url' => 'https://mysub.mydomain.com',
  'dbtype' => 'pgsql',
  'version' => '13.0.5.2',
  'dbname' => '...',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '...',
  'dbpassword' => '...',
  'installed' => true,
  'default_language' => 'no',
  'check_for_working_htaccess' => true,
  'filelocking.enabled' => true,
  'onlyoffice' => 
  array (
    'verify_peer_off' => true,
  ),
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'lost_password_link' => 'disabled',
  'skeletondirectory' => '/local/app/nextcloud/mysub.mydomain.com/skeleton',
);
**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
### Client configuration
**Browser:**
Chrome 68..3440.91
**Operating system:**
Android version 9
Testet with different Andriod devices and Lower Android versions. The problem is the same on all devices.
#### Web server error log
NO logs concerning this problem
#### Nextcloud log (data/nextcloud.log)
NO logs concerning this problem
#### Browser log
NO logs concerning this problem

**Comment by jcbdg18** [comment]
None of these issues are related to my problem.

**Comment by jcbdg18** [comment]
Attachement: Zooming result:
![screenshot_20181126-124919](https://user-images.githubusercontent.com/42866279/49012537-fb0bee00-f179-11e8-848b-5311b5c9a7c1.png)

**Comment by ChristophWurst** [comment]
IMO this is an issue of https://github.com/nextcloud/files_pdfviewer. Please report it there. Thank you for your feedback! :v:

**Comment by jcbdg18** [comment]
No, it's not a problem only of pdf viewer, it is a general problem with ALL apps that can show pdf, like onlyoffice, ebook reader, pdf viewer...

**Comment by jcbdg18** [comment]
Please reopen this issue

**Comment by jcbdg18** [comment]
Hei.


No, it's not a problem only of pdf viewer, it is a general problem with ALL apps that can show pdf, like onlyoffice, ebook reader, pdf viewer..


Von meinem Xperia Smartphone von Sony gesendet


---- Christoph Wurst schrieb ----


IMO this is an issue of https://github.com/nextcloud/files_pdfviewer. Please report it there. Thank you for your feedback! ✌️

**Comment by ChristophWurst** [comment]
IMO there is nothing the server could fix here. It's up to the apps to handle zooming.

Anyway, reopening.
