### ISSUE TITLE
contacts app - navigation with tab key buggy

### ISSUE THREAD

**Issue by koksnuss** [nextcloud/server#1267]
### Steps to reproduce
1. Open contacts app in your nextcloud
2. Click on any existing contact / Or add a new contact
3. Navigate through the input fileds using your tab key

### Expected behaviour
One would expect to navigate from field directly to the next field - exept beside the fileds are other form elements which allow to take action on something.

### Actual behaviour
1. When the cursor is in the field "city" (within adress) and I press tab it jumps to the label of the next field "state / province" and not directly to the input field.
2. When the cursor is in the field "firstname" (within detailed / full name) and I press tab it jumps to the label of the next field "additional name" and not directly to the input field.
3. It is also possible to navigate to the label "detailed name" above all name related input fields.

### Server configuration
**Operating system**: Debian 3.10

**Web server:** Apache 2.4.10

**Database:** MySQL 15.1 Distrib 10.0.26-MariaDB

**PHP version:** PHP 5.6.24-0

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated since owncloud 7

**Where did you install Nextcloud from:** github/nextcloud/server

**Comment by phsc** [comment]
Should be reported to the Contacts app: https://github.com/owncloud/contacts/issues

**Comment by tflidd** [comment]
https://github.com/owncloud/contacts/issues/513
