### ISSUE TITLE
nextcloud 13 fails to load login page after debian upgrade

### ISSUE THREAD

**Issue by froghorn82** [nextcloud/server#12673]
Summary:
I upgraded Debian and then this happened. Nextcloud page doesn't show at all. I get Internal Server Error on the web page it was working before.

apache error log shows:

[Mon Nov 26 14:55:42.168599 2018] [mpm_prefork:notice] [pid 28655] AH00169: caught SIGTERM, shutting down
[Mon Nov 26 14:55:52.885692 2018] [http2:warn] [pid 369] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Mon Nov 26 14:55:52.933387 2018] [mpm_prefork:notice] [pid 369] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Mon Nov 26 14:55:52.933426 2018] [core:notice] [pid 369] AH00094: Command line: '/usr/sbin/apache2'

--> 
### Steps to reproduce
1.
2.
3.

### Expected behaviour
nextcloud web login page should be displayed

### Actual behaviour
the following error when loading previously working page

Internal Server Error

The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.

### Server configuration

**Operating system**: debian 9 stretch

**Web server:**
apache 
**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
An unhandled exception has been thrown:
RedisException: Redis server went away in /var/www/nextcloud/lib/private/Memcache/Redis.php:54
Stack trace:
#0 /var/www/nextcloud/lib/private/Memcache/Redis.php(54): Redis->get('ed3ce3e2cce8368...')
#1 /var/www/nextcloud/lib/private/App/InfoParser.php(57): OC\Memcache\Redis->get('/var/www/nextcl...')
#2 /var/www/nextcloud/lib/private/legacy/app.php(621): OC\App\InfoParser->parse('/var/www/nextcl...')
#3 /var/www/nextcloud/lib/private/AppFramework/App.php(62): OC_App::getAppInfo('files')
#4 /var/www/nextcloud/lib/private/legacy/app.php(220): OC\AppFramework\App::buildAppNamespace('files')
#5 /var/www/nextcloud/lib/private/legacy/app.php(119): OC_App::registerAutoloading('files', '/var/www/nextcl...')
#6 /var/www/nextcloud/lib/base.php(662): OC_App::loadApps(Array)
#7 /var/www/nextcloud/lib/base.php(1081): OC::init()
#8 /var/www/nextcloud/console.php(46): require_once('/var/www/nextcl...')
#9 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

**Comment by tflidd** [comment]
Looks more like a configuration problem with apache:
https://serverfault.com/questions/879734/why-http2-doesnt-work-on-my-apache-2-4-29
https://http2.pro/doc/Apache

For configuration questions, ask in the forum help.nextcloud.com, the bug tracker here is use mainly for bug reports and feature requests.
