### ISSUE TITLE
Enable/Disable users to change their password

### ISSUE THREAD

**Issue by Studna95** [nextcloud/server#12671]
Actually there are no steps to reproduce, we just need some feature that allows us enable/disable users to change their password.

**Comment by violoncelloch** [comment]
why do you need to enable/disable users to change passwords?
passwords can be changed and users enabled/disabled independent from each other

**Comment by Studna95** [comment]
> why do you need to enable/disable users to change passwords?
> passwords can be changed and users enabled/disabled independent from each other

Because people have one password for business system and they could change that only password in some subsystem like Nextcloud. Hopefully you understand what i mean.

**Comment by violoncelloch** [comment]
ahh, sorry, I misunderstood your first post... now I get it
are you using LDAP?

**Comment by danielkesselberg** [comment]
https://docs.nextcloud.com/server/14/admin_manual/configuration_user/user_auth_ldap_api.html#configuration-keys

`turnOnPasswordChange`

**Comment by tomtomas99911** [comment]
Yes, you can disable password change in LDAP (also in user_SQL or SMTP login) but you cannot hide change password dialog - so users are confused.

We want to hide whole change password dialog, not only to disable password change.

**Comment by danielkesselberg** [comment]
I suppose you talk about this page?

![image](https://user-images.githubusercontent.com/3902676/49153120-1e1ed500-f315-11e8-9db1-0fbe3e902db0.png)

Password dialog is displayed when `passwordChangeSupported`.
https://github.com/nextcloud/server/blob/802a978bb5c336edc0369335d1aa5d12807d2bcc/settings/templates/settings/personal/security.php#L40

https://github.com/nextcloud/server/blob/4f75173f113c70660d761bc62742c5dabda2e67c/lib/private/Settings/Personal/Security.php#L70-L73

https://github.com/nextcloud/server/blob/1fd640b40b9129b6b285bcab4ba085129a50836e/lib/private/User/User.php#L326-L328

https://github.com/nextcloud/server/blob/2d30511fa63780d1b2931e1daa37d2f150f6d0d7/apps/user_ldap/lib/User_LDAP.php#L547-L556

The good news: This feature is already there :+1: 
The bad news: It does not work for you :rofl:

**Comment by danielkesselberg** [comment]
I did some testing (used https://www.forumsys.com/tutorials/integration-how-to/ldap/online-ldap-test-server/ as ldap server) and it works for me. 

![image](https://user-images.githubusercontent.com/3902676/49160685-98585500-f327-11e8-8c7c-29f056c8e353.png)

No change password form by default. Only when above checkbox is enabled. You are using nextcloud 14? (i have tested it with 15)

**Comment by tomtomas99911** [comment]
I am using NX 14 with user_sql - so I need to hide password change dialog here...

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/user_sql i see a "change password" checkbox there?

**Comment by tomtomas99911** [comment]
Yes - it disable password change - but it does not hide password change dialog. And author of user_sql said - "hiding password change dialog is feauture of nextcloud core not user_sql addon"

**Comment by danielkesselberg** [comment]
@mlojewski-me would you mind to reopen https://github.com/nextcloud/user_sql/issues/78 and have a second look?

`UserBackend` and `GroupBackend` extend from `ABackend` and both implement `ISetPasswordBackend`. 

https://github.com/nextcloud/server/blob/b723a2b8cada8c742ea1cadbbad2319c737cca9b/lib/public/User/Backend/ABackend.php#L42-L50

Nextcloud asks the backend if a password change is possible (and if so shows the form)
https://github.com/nextcloud/server/blob/1fd640b40b9129b6b285bcab4ba085129a50836e/lib/private/User/User.php#L326-L328

I guess you have to overwrite `implementsActions` and check if the user enabled password change with your backend.

**Comment by danielkesselberg** [comment]
Thank you @tomtomas99911 for reporting this and answering all my questions :+1:

**Comment by mlojewski-me** [comment]
@danielkesselberg issue reopened, I will check it soon

**Comment by tomtomas99911** [comment]
Any advance here please?

**Comment by mlojewski-me** [comment]
> @danielkesselberg issue reopened, I will check it soon

Issue  nextcloud/user_sql#78 resolved

**Comment by phlegx** [comment]
I use the build in user backend management. How can I disable password change so that users cannot change their own password?

**Comment by kesselb** [comment]
@phlegx As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
