### ISSUE TITLE
Disable overwrite NewUserMail

### ISSUE THREAD

**Issue by AlexH01001** [nextcloud/server#12676]
Overwrite of file NewUserMail , configuration trough settings are being overwritten on update and the tryouts of the app i tried to create it stops on update also. If it's not a big deal,hope you could leave to not being overwriten on updates. Thanks.

**Comment by ChristophWurst** [comment]
Please fill out the [issue template](https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE.md). Thanks.

**Comment by AlexH01001** [comment]
**Is your feature request related to a problem? Please describe.**
In this file nextcloud/settings/Mailer/NewUserMailHelper.php  there is a message for new users in which it sends a mail with a certain welcome message.

**Describe the solution you'd like**
I wish if it could be possible on next updates to stop being overwritten and keep it's modifications that i do such as extra information on welcome message and other things.

**Describe alternatives you've considered**
A plugin might do the trick,but in my opinion if it's not that relevant i think if it would be possible to skip it being overwritten.

**Additional context**


Thanks.

**Comment by danielkesselberg** [comment]
I think you could start here: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/email_configuration.html#using-email-templates
