### ISSUE TITLE
Notification about uploaded files are too small. (#filedrop)

### ISSUE THREAD

**Issue by b3nks** [nextcloud/server#12686]
### Steps to reproduce
1. Create Folder and share it with filedrop as "only upload"
2. drop a file
3. overlook the message of "uploaded file" and drop it over and over again

### Expected behaviour
The message should be way bigger by default, maybe even with a huge green okay button.

### Actual behaviour
there is just a pale tiny line of "files uploaded" and the file name so that users keep on uploading the same file over and over again, until they check it's already there.

### Server configuration

**Operating system**:
Debian

**Web server:**
Apache

**Nextcloud version:** (see Nextcloud admin page)
14

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgrade from nextcloud

**Comment by ChristophWurst** [comment]
Could you post a screenshot? That would be very helpful :v:

**Comment by b3nks** [comment]
It's not a bug, It's a design issue. People would ignore the Message of "Uploaded Files"
I propose to have a bigger notification by default:

i changed my template to look like this:


![upload_3_expected](https://user-images.githubusercontent.com/20385436/49375061-84d03400-f703-11e8-8746-d8556bc4d056.png)

**Comment by ChristophWurst** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
There is an open issue about the design issues w/ the file drop #4164 
I'm guessing this is kind of a duplicate as this would solve things :)
