### ISSUE TITLE
Update from 14.0.3 to 14.0.4 fails - error in GuzzleHttp

### ISSUE THREAD

**Issue by Windyo** [nextcloud/server#12695]
Can't update from 14.0.3 to 14.0.4

Web Panel "Admin Overview throws internal Server Errors".
Upgrading via OCC throw error related to Guzzle

### Steps to reproduce
1. try to update
2. fail

### Expected behaviour
Nextcloud gets updated to 14.0.4

### Actual behaviour
Failure to update

### Server configuration

**Operating system**: Raspberry pi

**Web server:** Apache2

**Database:** MysQL

**PHP version:** 7.2.9-1

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade

**Where did you install Nextcloud from:** nextcloudpi

**Signing status:**
<details>
<summary>Signing status</summary>

```No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - admin_notifications: 1.0.2
  - apporder: 0.6.0
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - caniupdate: 0.2.0
  - checksum: 0.4.1
  - cloud_federation_api: 0.0.1
  - cms_pico: 0.9.7
  - comments: 1.4.0
  - contacts: 2.1.7
  - dav: 1.6.0
  - defaultlinkopen: 1.1.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_downloadactivity: 1.3.0
  - files_external: 1.5.0
  - files_external_gdrive: 0.2.8
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.3.2
  - files_rightclick: 0.8.4
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - mail: 0.11.0
  - metadata: 0.8.0
  - news: 13.0.3
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - polls: 0.8.3
  - previewgenerator: 2.0.0
  - provisioning_api: 1.4.0
  - radio: 0.6.3
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - sharerenamer: 2.3.0
  - socialsharing_email: 1.0.4
  - socialsharing_facebook: 1.0.3
  - socialsharing_twitter: 1.0.3
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - twofactor_totp: 1.5.0
  - unsplash: 1.1.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "1": "10.0.4.128",
            "2": "cloud.bessereau.eu",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "https:\/\/cloud.bessereau.eu\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/mnt\/raid0\/ncdata\/nextcloud.log",
        "updater.release.channel": "production",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/

### Client configuration
**Browser:**
fF/chrome

**Operating system:**
windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
empty
```
</details>

**Comment by ChristophWurst** [comment]
Please post the details of the error. This is way too specific. Please enable debug log as described in the admin manual and check your nextcloud.log again.

**Comment by Windyo** [comment]
Thanks for the ping, forgot to update this.
Found it weird that the error was so specific so I restored from a backup - turns out it was disk corruption. Nothing to do with Nextcloud, closing.
