### ISSUE TITLE
Adminstrative Script for bug reporting and documentation

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#127]
To ease bug reporting and for documentation purpose I suggest an administrative script collecting all relevant information about the NextCloud installation, included with a possibility for commenting and special formatting, e.g. html format !

regards, hitam4450

**Comment by MorrisJobke** [comment]
@LukasReschke started an app for this purpose: https://github.com/LukasReschke/issuereporter/tree/initial-import

**Comment by ChristophWurst** [comment]
can we close this in favor of https://github.com/nextcloud/server/issues/2713?
