### ISSUE TITLE
Nextcloud with Onlyoffice Docker behind a Sophos WAF

### ISSUE THREAD

**Issue by Rick26L** [nextcloud/server#12704]
### Steps to reproduce
1. Install Nextcloud with Onlyoffice Docker 
2. Activate WAF on Sophos for the Webservers
3. Try to open a Document

### Expected behaviour
Onlyoffice should open the document to be able to edit/view it 

### Actual behaviour
Onlyoffice App opens, but after a short time you get "Unknown Error. Press OK to return to document list"

### Information 
1. With DNAT, Onlyoffice is working 
2. Communication between Onlyoffice Docker and Nextcloud is ok. 

### Server configuration

**Operating system**:Ubuntu Linux 16.04.1

**Web server:**Apache version 2.4.18

**Nextcloud version:** 14.0.3

**Where did you install Nextcloud from:** Tech and Me

**Signing status:**No errors have been found.

**Nextcloud configuration:**
"system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.146.11",
            "cloud.**********.de",
            "office.**********.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.**********.de\/",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/ncdata\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "auth.bruteforce.protection.enabled": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "25",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "updater.release.channel": "stable"
    }

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

### Client configuration
**Browser:**Chrome/Firefox/IE

**Operating system:** W10

**Comment by ChristophWurst** [comment]
This should be reported at https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues.

Thanks!

**Comment by Rick26L** [comment]
Hi @ChristophWurst , 

done. https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/30 

:) Tanks!
