### ISSUE TITLE
Avatars Letter misaligned after update to 14.0.4

### ISSUE THREAD

**Issue by riccager** [nextcloud/server#12716]
### Steps to reproduce
1. Running nextcloud 13.0.8 server , debian 8.7 
2. Upgrade to Nextcloud 14.0.4 with command line or web based

### Expected behaviour
After upgrade , Avatars Letter misaligned on user menu
![image](https://user-images.githubusercontent.com/45437474/49179843-f12ceb00-f331-11e8-8896-51d421faa0e2.png)

before on nextcloud 13.0.8 work ok 

![image](https://user-images.githubusercontent.com/45437474/49179892-13266d80-f332-11e8-8125-fc91d7a71e0b.png)

### Server configuration
**Operating system**:
debian 8.1
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
PHP 7.0.16-1

**Comment by ChristophWurst** [comment]
What avatars are those?

**Comment by riccager** [comment]
> What avatars are those?



Hi , 
They are those that are created automatically when a user is created.
I understand that they use the function Avatar.php to generate themselves.

If I see the image from the development mode in the browser it looks like this.
<img width="179" alt="captura de pantalla 2018-11-29 a la s 19 10 55" src="https://user-images.githubusercontent.com/45437474/49255409-ae8b1180-f40a-11e8-878c-b72b4ed47ad8.png">

Thks.

**Comment by riccager** [comment]
This is the issue. 

![videonextcloud](https://user-images.githubusercontent.com/45437474/49257534-599ec980-f411-11e8-9d46-e6a691bd1fb3.gif)

**Comment by ChristophWurst** [comment]
Ah, so the users page :wink: 

@skjnldsv fix it ;)

@riccager thank you for your info!

**Comment by skjnldsv** [comment]
@riccager do you have imagemagick enabled on your server?
Do you also have gd? Can you post your php extension list and versions please? :)

**Comment by riccager** [comment]
> @riccager do you have imagemagick enabled on your server?
> Do you also have gd? Can you post your php extension list and versions please? :)



Hi skjnldsv,
I imagemagick  think is  on , i don't know about gd . But attach my php info and maybe you can help me to know if a loss something on my install .
[phpInfo.pdf](https://github.com/nextcloud/server/files/2631617/phpInfo.pdf)

**Comment by ChristophWurst** [comment]
![bildschirmfoto von 2018-11-30 10-35-38](https://user-images.githubusercontent.com/1374172/49280975-b939bb00-f48b-11e8-872b-235c5763c492.png)

**Comment by skjnldsv** [comment]
Thanks @riccager 
Can you post the image that outputs where you access https://yourdomain.xxx/avatar/admin/500

**Comment by riccager** [comment]
> Thanks @riccager
> Can you post the image that outputs where you access https://yourdomain.xxx/avatar/admin/500

here


![image](https://user-images.githubusercontent.com/45437474/49318894-20319100-f4d9-11e8-9cdd-69021cf97bf9.png)

**Comment by skjnldsv** [comment]
Wow, that is really surprising! :O

**Comment by mgoppold** [comment]
I fixed this now with:

find the avatars location:

```sql
select path from filecache where name like 'avatar%' limit 10;
```

With the result you can remove the old generated avatas:

```bash
find $NCSERVERROOT/appdata_oc6f59l0az9t/avatar  -name generated | while read L; do pushd $(dirname $L); rm -f *.png; popd; done
```

If you have redis for nc, flush the db with:

```bash
redis-cli flushdb
```

next, let occ rescan the app-data files with:

```bash
sudo -u wwwrun php $NCSERVERROOT/occ files:scan-app-data
```

and finaly logoff, reload with CTRL+F5 and logon

**Comment by Dennis1993** [comment]
Thank you for your help!

I think we can close this issue now 🙂👌🏼
