### ISSUE TITLE
Feature request: Custom message for Maintenance mode

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/server#12725]
Hi all

We are going to upgrade soon, and whilst thinking of ways to improve our upgrade process, I thought it would be useful if we could put a custom message on our page stating something like: 

**"Nextcloud is scheduled for maintenance on 25 December 2062 from 08:00 to 17:00, sorry for any inconvenience caused."**

This will create transparency with the users, which always goes a long way.

Regards
Hans

**Comment by ChristophWurst** [comment]
This would have to be a hard-coded, non-translatable string because during maintenance we don't have a reliable connection to the db and it would have to be served from the config.php AFAIK.

**Comment by danielkesselberg** [comment]
Ref https://github.com/nextcloud/server/issues/12536 (similar feature request)

**Comment by MorrisJobke** [comment]
Also related to #5789

**Comment by ChristophWurst** [comment]
> Also related to #5789

Indeed. @hanserasmus can we close this ticket?

**Comment by hanserasmus** [comment]
@ChristophWurst Yes, thank you then. Sorry did not see that post when I search github for anything related. My search was probably not well defined enough.  I will comment on that ticket.
