### ISSUE TITLE
Updates clears 'theme' entry in config.php

### ISSUE THREAD

**Issue by greyman-hh** [nextcloud/server#12727]
Every time I update Nextcloud the theme entry in the config.php get cleared.

I use
`'theme' => $_SERVER['HTTP_HOST'],`

after an update the entry is

`'theme' => '',`

**Comment by ChristophWurst** [comment]
I don't think you're "allowed" to use vars in config.php because that file is re-written by Nextcloud when system config changes. cc @MorrisJobke

**Comment by danielkesselberg** [comment]
You could create a new file `theme.config.php` in the same folder like `config.php` and use

```
return [
    'theme' => $_SERVER['HTTP_HOST']
];
```

this should be update save.

**Comment by MorrisJobke** [comment]
With the solution of @danielkesselberg the theme is always also fetched from this additional file and will not be vanished on update.
