### ISSUE TITLE
Closing reminder in thunderbird leads to notification email from NC

### ISSUE THREAD

**Issue by brunt82** [nextcloud/server#12721]
Closing a reminder in Thunderbird leads to an update of the event on the server, which generates an unnecessary notification event. While using a shared calender this leads to extreme many emails.

### Steps to reproduce
1. Create new event in a shared calendar including a reminder
2. Wait until the reminder pops up in Thunderbird
3. Close the reminder in Thunderbird

### Expected behaviour
The described behavior (closing a reminder) should not generate an email notification for the users of the shared calender. 

### Actual behaviour
The server notices the reminder update by Thunderbird as update of the event. Therefore it is generated an 
email notification "User B updates the event test in calender personal".

### Server configuration
**Operating system**: Debian 9
**Web server:** Apache 2.4
**Database:** MariaDB 10.1.26
**PHP version:** 7.0
**Nextcloud version:** 13.0.5

### Logs
See attached log of debug console of Thunderbird:
[thunderbird_log.txt](https://github.com/nextcloud/server/files/2628313/thunderbird_log.txt)

Event is created:
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20181129T081553Z
LAST-MODIFIED:20181129T081617Z
DTSTAMP:20181129T081617Z
UID:63c9dce9-f740-47df-9f7e-53de6b39ea77
SUMMARY:new event
DTSTART;TZID=Europe/Berlin:20181129T091800
DTEND;TZID=Europe/Berlin:20181129T101800
TRANSP:OPAQUE
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT1M
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM
END:VEVENT
END:VCALENDAR

Event is updated after closing the reminder:
BEGIN:VCALENDAR
PRODID:-//Mozilla.org/NONSGML Mozilla Calendar V1.1//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
BEGIN:VEVENT
CREATED:20181129T081553Z
LAST-MODIFIED:20181129T081703Z
DTSTAMP:20181129T081703Z
UID:63c9dce9-f740-47df-9f7e-53de6b39ea77
SUMMARY:new event
X-MOZ-LASTACK:20181129T081703Z
DTSTART;TZID=Europe/Berlin:20181129T091800
DTEND;TZID=Europe/Berlin:20181129T101800
TRANSP:OPAQUE
X-MOZ-GENERATION:1
BEGIN:VALARM
ACTION:DISPLAY
TRIGGER;VALUE=DURATION:-PT1M
DESCRIPTION:Mozilla Standardbeschreibung
END:VALARM
END:VEVENT
END:VCALENDAR

The only difference are the following four attributes:
LAST-MODIFIED
DTSTAMP
X-MOZ-LASTACK:
X-MOZ-GENERATION

When I compare the following link none of these attributes should lead to a notification email:
https://github.com/nextcloud/3rdparty/blob/214c4155f587f5178d792fe4a839044bdc9982f1/sabre/vobject/lib/ITip/Broker.php#L69

**Comment by ChristophWurst** [comment]
cc @georgehrke

**Comment by nickvergessen** [comment]
yeah sure, if we can detect that?

**Comment by brunt82** [comment]
Any new update to this issue...

**Comment by georgehrke** [comment]
Related to #13130

**Comment by gitthangbaby** [comment]
Closing Reminders window causes reminders to be added. It's surprising that simply closing a window actually modifies all events in it despite no user action was taken. The result is: calendar full of events with unwanted extra notifications (now + 5, isn't it actually snooze function?), Reminders window full of event duplicates (even hundreds). There's no way out of this, by changing preferences.

**Comment by gitthangbaby** [comment]
Closing Reminders window causes reminders to be added. It's surprising that simply closing a window actually modifies all events in it despite no affirmative user action was taken. The result is: calendar full of events with unwanted extra notifications (now + 5, isn't it actually snooze function?) on all clients, Reminders window full of event duplicates (even hundreds). There's no way out of this, by changing preferences in Thunderbird.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by p-eti** [comment]
I observed a issue like reported by brunt82 with Thunderbird 115.9.0
