### ISSUE TITLE
files integrity error  `.rnd` files created after upgrade on Arch Linux

### ISSUE THREAD

**Issue by doronbehar** [nextcloud/server#12726]
Hey guys, I hope it's O.K I've discarded the issue template. I just wanted to let you know that after the last upgrade to `14.0.4`, here on an Arch Linux server, I got file integrity errors about files which are not present upstream:

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- .rnd
		- ocs/.rnd

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.rnd] => Array
                        (
                            [expected] => 
                            [current] => 942ab53d1cb685de5dc8632dccbf58638023b66d77d1fa6bfac30a8e8084de89eeea9c35f6271b6dcd9fcc561c3241b581d3f55955d32a7b10e5930948a540ac
                        )

                    [ocs/.rnd] => Array
                        (
                            [expected] => 
                            [current] => c005aa2d18a7e8e929e1206fdac113f58e0cf0751dbb8ac1dbffc675b33683baaf7e00c1ccc57860f7d8c6739a306c8fa0ef0783df1fafa8dd1fc45a254af992
                        )

                )

        )

)
```

I fixed the issue by just deleted these `.rnd` files but it happened to me on previous upgrades as well and as far as I can remember I've encountered similar errors here on the issue tracker.

**Comment by ChristophWurst** [comment]
>  I hope it's O.K I've discarded the issue template

well, now I have no idea about your setup.

How did you install Nextcloud? Via the "official" Arch package or a Nextcloud tarball?

I use Arch btw.

**Comment by ChristophWurst** [comment]
occ does not create these files.

Do you use putty or similar? Ref https://www.openssl.org/docs/man1.1.0/apps/rand.html https://www.howtogeek.com/forum/topic/what-the-heck-is-an-rnd-file

**Comment by ChristophWurst** [comment]
Okay, thanks for your feedback. I'm closing this ticket now.

Should you see those files again, feel free to reopen.

**Comment by andyxh** [comment]
I see this .rnd file as well. I deleted it ran the upgrade and came back. I was on NC15 upgraded to NC15.0.1

**Comment by j-ed** [comment]
Have you seen/read this explanation: https://file.org/extension/rnd
It is created and used by e.g. OpenSSL (binary libcrypto.so.1.1 matches).

**Comment by MorrisJobke** [comment]
> Okay, thanks for your feedback. I'm closing this ticket now.

Closing as per this ^

**Comment by kaistian** [comment]
> Do you use putty or similar? Ref https://www.openssl.org/docs/man1.1.0/apps/rand.html https://www.howtogeek.com/forum/topic/what-the-heck-is-an-rnd-file

It has nothing to do with Putty, Apache is creating them because of Nextcloud and/or its apps
```
sysdig -c spy_file "RW /var/www/owncloud/.rnd"
21:51:34.280607365 /usr/sbin/apach(28597) W 1024B /var/www/owncloud/.rnd

sysdig -c spy_file "RW /var/www/owncloud/ocs/.rnd"
19:59:33.963325783 /usr/sbin/apach(13663) W 1024B /var/www/owncloud/ocs/.rnd
```
