### ISSUE TITLE
Shortlink to files should be automatically copied when user clicks on the button

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#1273]
### Steps to reproduce
1. Activate the sidebar for a file
2. Click on the anchor (next to the title on the right)
### Expected behaviour

The link is shown and is highlighted. It should be copied in memory so that I can paste it right away
### Actual behaviour

The link has not been copied, despite the fact that it's highlighted. This is misleading.

---

@jancborchardt

**Comment by rullzer** [comment]
On the one hand I get it. on the other hand I still feel very uncomfortable with automagically overwriting the clipboard. Same when creating a share link.

**Comment by oparoz** [comment]
I agree, but then we shouldn't highlight that link. Let's do it when the user clicks/taps on it.

**Comment by rullzer** [comment]
I think it would be good to just add the clipboard thingy then. Like we have with the sharedlink. To the right of it. That is a real action (with tooltip copy to clipboard).

**Comment by oparoz** [comment]
Agreed

**Comment by jancborchardt** [comment]
Let's not keep adding more and more things. Simpler solution:

- The link icon should be a clipboard icon instead
- Tooltip: Copy local link
- Should copy link to clipboard on click (with confirmation »Copied to clipboard« via tooltip)
- No link box needed

**Comment by rullzer** [comment]
@jancborchardt that is not really true. For example not all OS X thingies support the clipboard.

**Comment by rullzer** [comment]
Already fixed in master
