### ISSUE TITLE
User userid instead of uid in Mails and Webinterface

### ISSUE THREAD

**Issue by c-0815** [nextcloud/server#12735]
Hello,

I have an issue with displaying the correct login name.

### Steps to reproduce
1. setup Nextcloud 14.0.4 and use ldap backend with Active Directory and default settings so that userid is objectGUID in AD.
2. After LDAP import at the admin users page the username corresponds with the objectGUID of AD. 
3. Login with the AD loginname (cn) and password works fine.
4. In the database table oc_preferences there is a config key uid for the userid (objectGUID)  with the appid user_ldap that corresponds with the loginname.

### Actual behaviour
If I send a welcome Message to the user the loginname in that mail is the userid and not the uid.
If I type a name in the name field of the sharing dialog and hover over an appearing name it also shows the userid and not the uid.

### Expected behaviour
In my opinion the end user should always see the well known uid instead of the cryptic userid in case of ldap backend.

**PHP version:**
7.2
**Nextcloud version:**
14.0.4

best regards

Ralph

**Comment by blizzz** [comment]
> If I send a welcome Message to the user the loginname in that mail is the userid and not the uid.

That rather comes from local user backend assumptions which do not necessarily match with other backends. Valid point to break it up. What's nasty is that we'd need to parse the login filter to figure out which login names are enabled and then even decide for one. Hm.

>  If I type a name in the name field of the sharing dialog and hover over an appearing name it also shows the userid and not the uid.

Uh? The user id should not be exposed, no matter how it looks like. With one exception, but this does not belong to it.

**Comment by c-0815** [comment]
Shall I send you a screenshot for the "hover" behavior?

**Comment by blizzz** [comment]
@c-0815 you can just drop it here on the issue when creating a comment

**Comment by c-0815** [comment]
If I hover over a user in the sharing dialog selection the internal user ID is displayed.
![hovered user](https://user-images.githubusercontent.com/31203975/52411827-5264fd80-2add-11e9-965a-9e3c205252d0.png)

Next Screenshot shows the boarding mail a user received that hasn't logged in yet. The e-mail is in english and the internal user ID is shown as the login name instead of them from the ldap backend.

![boarding-mail](https://user-images.githubusercontent.com/31203975/52412173-44fc4300-2ade-11e9-8405-176a26d11c61.png)


regards

Ralph

**Comment by blizzz** [comment]
@skjnldsv were you working on the sharing dialogue last time or am i mixing it up again?

**Comment by c-0815** [comment]
I worked today with this dialog. I already upgraded to 14.0.7. with the same behavior

**Comment by skjnldsv** [comment]
@blizzz, it doesn't ring a bell :thinking:

**Comment by c-0815** [comment]
Boarding Mail with ldap backend is still buggy, As Username the internal user id is placed in the mail text, but it must be the ldap login name (in Active Directory samAccountname).
