### ISSUE TITLE
Hide "Add group" for Group Admins (subadmins) in user management

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#12758]
As Group Admin (subadmin) you can see "Add group" in the user management.
If you try to add a group, this error occours:
```
An error occured during the request. Unable to proceed.
Logged in user must be an admin
```
If a group admin shouldn't create groups, it would be better to hide the option to do that.

cc @skjnldsv @rullzer

**Comment by szaimen** [comment]
This seems to be still valid.

**Comment by alexbijma** [comment]
any update on this?

**Comment by szaimen** [comment]
PRs are welcome!

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
