### ISSUE TITLE
Upgrade from 14 beta to 15 RC1 and from 15RC1 to 15 RC2 do not work via upgrade button

### ISSUE THREAD

**Issue by tfmm** [nextcloud/server#12759]
I was running the latest 14 beta release, and attempted to upgrade to 15 RC1, and the upgrade button in my Settings -> Admin -> Overview took me to the upgrade page, but the "Start Upgrade" button did nothing when clicking it. 

For this upgrade I manually copied the files over and did the backend upgrade via occ.

The same behavior was present when doing the upgrade from 15 RC1 to 15 RC2, however for that attempt, I visited https://url-here/updater/index.php, and that upgrade worked without issue.

**Comment by xf-** [comment]
Resolved via https://github.com/nextcloud/server/issues/12601 - will work in next update
