### ISSUE TITLE
Nextcloud 15 RC2 Callabora Bug

### ISSUE THREAD

**Issue by andyxh** [nextcloud/server#12761]
Please see below bug on NC15 RC2 when opening a file you can click on exit icon it's together with toggle grid view
![image](https://user-images.githubusercontent.com/24574019/49296911-0fecc800-f47f-11e8-874b-fa6ce5ef1389.png)

**Comment by bpcurse** [comment]
Same issue here on 15 RC2 with Firefox 63

**Comment by MorrisJobke** [comment]
Duplicate of #12797

**Comment by MorrisJobke** [comment]
I closed this one, as the other one is already assigned, in the correct milestone and in a project.
