### ISSUE TITLE
Security scan whitelist 

### ISSUE THREAD

**Issue by jlfranklin** [nextcloud/server#12768]
As part of my deployment process, I have the Nextcloud core code in a git repository.  This adds a `/var/www/nextcloud/.git` directory, which the security scan flags as many extra files.

I know these are essentially false-positives, so I would like to whitelist the .git directory.  Whitelisting individual files and hashes won't be effective as any commit to the repo will flag a new set of object files, plus any repo metadata files that get updated during the commit.

What I'd like to see added to Nextcloud is the following:

* Ignore all `.git` directories during the security scans
* Add a rule in the `.htaccess` file to 404 any attempts to access a `.git` directory.

I expect this will also be useful for app developers who have `/var/www/nextcloud/apps/myapp/.git` directories.

**Comment by MorrisJobke** [comment]
We highly recommend to not ship the `.git` directory inside your production environment. In development environments the code integrity scan will not run and thus not cause any warnings.
