### ISSUE TITLE
Indicator whether comment on file mentioned you

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#12765]
We currently show a regular grey comment icon when there was a comment on a file.

We should distinguish a bit whether there was a comment specifically to you. Just like in Talk, we could color the comment icon primary, which will also make it darker and also kind of work for people with vision deficiency.

What do you think @nextcloud/designers? And would we need an API for this so that mobile apps can also use it? @rullzer @MorrisJobke

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
