### ISSUE TITLE
Change notation of command

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#1276]
Hi,
creating a new identity for  NextCloud the **occ** command should be changed to e.g. **ncc** !

reagrds, hitam4450

**Comment by tflidd** [comment]
you want to change the **o**verall **c**onfiguration **c**ommand?

**Comment by nickvergessen** [comment]
You can also use this other tool: `php console.php` that is also what the `occ` file does.
We should not rename this file, because then scripts that use it, could break.

So I will close this for now.
