### ISSUE TITLE
 External storage registration broken in files_external.  'Unknown storage backend' error

### ISSUE THREAD

**Issue by alexeyvolkoff** [nextcloud/server#12775]
My external storage implemented in separate app stopped working in 14.0.4.
Storage configuration is displayed correctly in External storage configuration UI, it even passes the mount test, but I get 

**Sabre\DAV\Exception\ServiceUnavailable**: Unknown storage backend "mybackend"

while trying to access the storage in Files app. If I move my classes to files_external app and register the my backend there, everything works fine.

The same issue happened to my IMountProvider implementation. Basically, all I need is to create the only one system-wide mount point for my storage and I did it with getMountsForUser in my ConfigAdapter class:

```
public function getMountsForUser(IUser $user, IStorageFactory $loader) {
...
               $mounts = array();
		$mounts[] =  new  \OCA\Files_External\Config\ExternalMountPoint(
					self::MOUNT_CLASS,
					'/' . $user->getUID() . '/files/MyFiles',
					$mountOptions,
					$loader);
		return $mounts;
	}
}
```
Nothing changed, it just stopped working. It is still getting invoked, returns the mount point (I see it with logging) but nothing happens, it is just not displayed in Files app. The same code added to files_external OCA\Files_External\Config\ConfigAdapter works!

I reworked my app to catch post_initMountPoints hook:
 \OCP\Util::connectHook('OC_Filesystem', 'post_initMountPoints', $this, 'createMountPoint');

```
//Create  system-wide mount point	
    public function  createMountPoint($data) {
 	 $mountManager = \OC\Files\Filesystem::getMountManager($data['user']);
	 $mountArgs = array(......);

	$mountPoint =  new  \OCA\Files_External\Config\ExternalMountPoint(
					'\OC\Files\Storage\DAV',
					'/' . $data['user']. '/files/MyFiles',
					$mountArgs);
	$mountManager->addMount($mountPoint);
    }
```
But result is the same, mount point is created but not displayed. I tried to put invalid mount arguments  there, and get mount error in log, while no error with good.

This app worked fine in v 13.0, I was preparing it to publishing, but..
Something major changed?  Some security protection?

**Comment by alexeyvolkoff** [comment]
update:
Signed the app, still not working. Not a security issue.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
