### ISSUE TITLE
Show long group names and email addresses as tooltip

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#12779]
**Is your feature request related to a problem? Please describe.**
On NC 14.0.4 / Firefox 63.0.1: Longer group names (approx. 18-24 chars+) are not shown in the left sidebar. As a workaround you can hover over them and look at the link displayed at the bottom of the browser window. Email addresses in the user management are not fully visible, as well. The workaround here is even worse as you need to click the address field and select the whole address.

EDIT: Same problem with longer assigned group names in the user list but there is no workaround. On the other hand, if you hover over +x (when the user is assigned to more than 2 groups) there already is a working tooltip.

**Describe the solution you'd like**
If you hover over a long group name or email address it should be displayed in full as a tooltip as it is already implemented for group membership (if you are a member of more than 2 groups (e.g. +3)).

**Comment by szaimen** [comment]
Long mail addresses have a tooltip now and long group names are shown completely, hence closing.
