### ISSUE TITLE
Doc Bug re: Redis

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#12777]
### Steps to reproduce

1.  Navigate to https://docs.nextcloud.com/server/14/admin_manual/installation/source_installation.html#ubuntu-installation-label

2. See the section that mentions adding this to config.php

```
'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'memcache.local' => '\OC\Memcache\APCu',
'redis' => array(
  'host' => 'localhost',
  'port' => 6379,
    ),
```

3. See the ambiguity because this is under the `SELinux` section but if it only applies to SELinux servers then what implications do I have to know for making redis work on my server without SELinux?

### Expected behaviour
The page should make two things clear:

A. is this config for SELinux installations only?  Or for all server using redis?

B. What is the context to put this into the config.php file (because appending between `maintenance' => false,` and final `);` leads to `Internal Server Error`

### Actual behaviour
Reader does not know if he should use these instructions.  (And when he tries to he gets `Internal Server Error` and then remove these lines from `config.php` and now he does not know if redis is being used or not).

**Comment by stone212** [comment]
UPDATE:  The doc still sucks for the reasons I say above but the fix for this problem was:

1. `# apt-get install php-apcu`

2. YES add these lines before the final `);` in config.php:

```
'memcache.distributed' => '\OC\Memcache\Redis',
'memcache.locking' => '\OC\Memcache\Redis',
'memcache.local' => '\OC\Memcache\APCu',
'redis' => array(
  'host' => 'localhost',
  'port' => 6379,
    ),
```

This means that the doc should NOT have this info look like it exists under `SELinux`

**Comment by danielkesselberg** [comment]
Please report issues with the documentation here: https://github.com/nextcloud/documentation. Thank you :+1:
