### ISSUE TITLE
Make sure federated sharing accepts @user@cloud.example.com usernames

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#12776]
As services like Mastodon and other ActivityPub-enabled software uses an ID like `@user@cloud.example.com`, we should make sure that our federated sharing also accepts that everywhere to avoid confusion:

- Share link page in top right "Add to your Nextcloud"
- Sharing sidebar when sharing with others
- elsewhere?

**The only difference between our "Federated Cloud ID" and the ActivityPub username seems to be the prepended `@` before the username.**

cc @schiessle @MorrisJobke @rullzer @juliushaertl @daita – not sure how big of a fix is this, but likely a backport  to 15 would be good.

**Comment by skjnldsv** [comment]
IS this still an issue?

**Comment by jancborchardt** [comment]
Just tested (and you can do so too ;) and this is still exactly the same issue, in the places as described above.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
