### ISSUE TITLE
Can’t get app storage, app files_external, user not logged in

### ISSUE THREAD

**Issue by SchroedersKater** [nextcloud/server#12787]
This message may be reported when connecting to an external storage via SFTP, WebDAV etc.

I think this is a bit misleading. In my case it came up when I tried to access a folder with an invalid path that doesn’t exist. A more exact text would help users to find what they’ve done wrong.

**Comment by ManOki** [comment]
Can you describe in more detail what you did.

Seems to me, that you navigate to a 'files_external' directory in nextcloud, then removed this directory outside from nextcloud and tried to access it (or a subdirectory) again inside nextcloud. Is this correct?

**Comment by ChristophWurst** [comment]
No info provided -> closing
