### ISSUE TITLE
App updates are not sent as push notification

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12788]
- add user to group to get notifications for available updates (as admin: settings -> overview)
- have an app with update available
- see this app in notification when using webUI, or when open notifications on client as user
--> but no push notification is sent

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Well the proxy had a lot of hickups recently.

also there is https://github.com/nextcloud/notifications/issues/226

so im closing this
