### ISSUE TITLE
"Security and configuration warnings" after install - wrong links

### ISSUE THREAD

**Issue by schultz-it-solutions** [nextcloud/server#1278]
the "Security and configuration warnings" provide a number of links (e.g. to "Tipps and Tricks" and "Logging"). With the upgrade to version 10, they point to (no-longer-existing) anchors in the administration page.

### Steps to reproduce
1. install nc-10
2. examine the "security and configuration warnings": "Security notes" points to ".../admin#admin-tips" instead of ".../admin#tips-tricks", other links also point to no-longer-existing anchors.

### Expected behaviour
Jump to the respective section of the admin-area

### Actual behaviour
nothing happens, because the link is wrong

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache

**Database:**
MariaDb

**PHP version:**
7

**Nextcloud version:** (see Nextcloud admin page)
10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 9.53

**Where did you install Nextcloud from:**
Nextcloud repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Do you mean "You are accessing this site via HTTP. We strongly suggest you configure your server to require using HTTPS instead as described in our security tips." ?

That was fixed with 10.0.1 and I can't find any other broken link there.
