### ISSUE TITLE
Use separate redis database

### ISSUE THREAD

**Issue by dominic-p** [nextcloud/server#12796]
**Is your feature request related to a problem? Please describe.**
If you have multiple applications sharing the same redis instance it's nice to keep their data in separate databases.

**Describe the solution you'd like**
It looks like the php-redis module includes support for [setting the database](https://github.com/phpredis/phpredis#select). It would be nice if Nexctcloud made this configurable in the main redis config section.

**Describe alternatives you've considered**
The alternative is to leave everything in one database and if any application needs to flush it, data for all applications is lost.

**Additional context**
NA

Thanks, as always, for the great software.

**Comment by MorrisJobke** [comment]
> The alternative is to leave everything in one database and if any application needs to flush it, data for all applications is lost.

We don't flush data AFAIK. Also the data itself is prefixed by the instance ID.

As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by dominic-p** [comment]
Thanks for the quick and informative reply. If it becomes too much of an issue for me, I'll see about opening a PR.
