### ISSUE TITLE
Can't login after upgrading Fedora 27 to 28 and PHP 7.1 to 7.2

### ISSUE THREAD

**Issue by stemid** [nextcloud/server#12795]
### Steps to reproduce
1. Install Nextcloud 14.0.3.0 on Fedora 27
2. Upgrade Fedora 27 to Fedora 28 with dnf
3. Try to login to nextcloud

### Expected behaviour
Login to nextcloud.

### Actual behaviour
Redirected back to login page with no error `/login?redirect_url=/apps/files/`

### Server configuration

**Operating system**: Fedora 28 (Linux 4.19.5-200.fc28.x86_64)

**Web server:** Nginx 1.12.1-8 + php-fpm 7.2.12-1

**Database:**MariaDB 10.2.19-1

**PHP version:** 7.2.12-1

**Nextcloud version:** 14.0.3.0 in config.php because I can't login.

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install.

**Where did you install Nextcloud from:** Source package tarball.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Can't login as any user.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - calendar: 1.6.3
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.6
  - dav: 1.6.0
  - deck: 0.4.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notes: 2.4.2
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - qownnotesapi: 18.8.0
  - quicknotes: 0.1.5
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - tasks: 0.9.7
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.swehack.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "http:\/\/cloud.swehack.local",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "26"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.6.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.0.1",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "2.1.6",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1540634998.6841",
            "lastcron": "1543869901",
            "lastupdateResult": "{\"version\":\"14.0.4.2\",\"versionstring\":\"Nextcloud 14.0.4\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-14.0.4.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/14\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=14.0.4\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1543862702",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "7a173342cb0e112d3b11053e87e64a8e",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarSearchIndex": "yes",
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.3.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.6.2",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.4.1",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.7.1",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.1.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "ocsid": "170871",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "pub_date": "Sat, 10 Dec 2016 00:00:00 +0100",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.4.2",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.2.1",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "prevent_group_restriction"
        },
        "qownnotesapi": {
            "enabled": "yes",
            "installed_version": "18.8.0",
            "types": ""
        },
        "quicknotes": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.7",
            "types": ""
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "types": ""
        },
        "updatenotification": {
            "calendar": "1.6.4",
            "contacts": "2.1.8",
            "core": "14.0.4.2",
            "deck": "0.5.0",
            "enabled": "yes",
            "installed_version": "1.4.1",
            "notes": "2.5.1",
            "qownnotesapi": "18.11.0",
            "tasks": "0.9.8",
            "types": "",
            "update_check_errors": "0"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "filesystem"
        }
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** It appears as a local directory /media/nas/Downloads/nextcloud but /media/nas/Downloads is autofs mounted from a NAS over NFS.

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox 62.0.3

**Operating system:** Fedora 28 (Linux 4.18.14-200.fc28.x86_64)

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothin in error log.
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
nextcloud.log is 0 bytes.
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Console log:
Lösenordsfält på en osäker (http://) sida. Det här är en säkerhetsrisk som gör det möjligt att stjäla inloggningsuppgifter.[Läs mer] login
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542 

The Swedish text complains about being on an insecure site but I'm fine with that because it's in my LAN and I don't have any ports open to the outside so it's hard to get a valid cert.

Network log:
I don't understand how to export the network log so I've attached a screenshot of the POST request.
![shrike-20181203 215703 1543870623](https://user-images.githubusercontent.com/1306529/49401101-79eac300-f746-11e8-9148-f0a1fa6713f5.png)

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by stemid** [comment]
The php-fpm log also has nothing for when this happens.

**Comment by danielkesselberg** [comment]
Try `php occ maintenance:repair`. You could try to upgrade nextcloud to 14.0.4 as well (`php updater.phar` in folder updater)

**Comment by stemid** [comment]
@danielkesselberg I already tried maintenance:repair, did not help. I also checked oc_bruteforce_attempts, no rows. I also tried disabling auth.bruteforce.protection.enabled. 

I also tried updater.phar now, it finished with no reported errors but there were a lot of background errors about operation not allowed on the NFS share.

Didn't help with the overall issue.

The background errors that came up when running updater.phar looked like this.

```
PHP Warning:  rename(/media/nas/Downloads/nextcloud/updater-oc9g01uf228z/downloads/nextcloud/apps/lookup_server_connector/lib/UpdateLookupServer.php,/var/www/nextcloud/updater/../apps/lookup_server_connector/lib/UpdateLookupServer.
php): Operation not permitted in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 886                                                                                                                           
PHP Warning:  rename(/media/nas/Downloads/nextcloud/updater-oc9g01uf228z/downloads/nextcloud/apps/lookup_server_connector/lib/BackgroundJobs/RetryJob.php,/var/www/nextcloud/updater/../apps/lookup_server_connector/lib/BackgroundJobs
/RetryJob.php): Operation not permitted in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 886                                                                                                                 
PHP Warning:  rename(/media/nas/Downloads/nextcloud/updater-oc9g01uf228z/downloads/nextcloud/apps/lookup_server_connector/appinfo/info.xml,/var/www/nextcloud/updater/../apps/lookup_server_connector/appinfo/info.xml): Operation not 
permitted in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 886  
```                                                                                                                                             

I believe that's related to NFS because I get a similar error if I try to change ownership of a file on NFS.

```
$ sudo chown -R nginx /media/nas/Downloads/nextcloud
...
chown: changing ownership of '/media/nas/Downloads/nextcloud/updater-oc9g01uf228z/backups': Operation not permitted                                                                                                                   
```

I did get some log output in nextcloud.log during the update, first I've seen so far. https://paste.fedoraproject.org/paste/OjegEj-oaV7~tcoMeB45NQ

Maybe an issue with the NFS mount as datadirectory? I've tried the following to verify but can't see any issue.

```
$ sudo su -l -s /bin/bash nginx
$ sqlite3 /media/nas/Downloads/nextcloud/owncloud.db
sqlite> .tables
... shows all the table names
$ ls -lat /media/nas/Downloads/nextcloud/
totalt 820
drwxr-xr-x.  6 1024 users   4096 27 okt 14.38 stemid
drwxr-xr-x. 10 1024 users   4096 27 okt 12.15 appdata_oc9g01uf228z
drwxrwxrwx.  4 1024 users   4096 27 okt 12.12 admin
-rw-------.  1 1024 users 729088 27 okt 12.00 owncloud.db
drwx------.  7 1024 users   4096 27 okt 11.56 appdata_ocl5qaebo2km
drwxrwxrwx.  4 1024 users   4096 27 okt 11.56 appdata_ocdeoe8g2cwr
drwxrwxrwx. 12 root root   20480 19 okt 11.27 ..
drwxrwx---.  9 1024 users   4096  6 jan  2000 .
-rw-rw-r--.  1 1024 users  10254  6 jan  2000 updater.log
-rw-r-----.  1 1024 users  34460  6 jan  2000 nextcloud.log
drwxrwxr-x.  4 1024 users   4096  6 jan  2000 updater-oc9g01uf228z
drwx------.  2 1024 users   4096  6 jan  2000 files_external
-rw-r--r--.  1 1024 users    324  6 jan  2000 .htaccess
-rw-------.  1 1024 users      0  6 jan  2000 index.html
-rw-r--r--.  1 1024 users      0  6 jan  2000 .ocdata
```

So even if the files only have rw on user nginx can still access them. And both nginx and php-fpm run as the nginx user.

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by hardhub** [comment]
@MorrisJobke I do not think it is setup issue. Software does not work as expected. I am new for Nextcloud. I have installed it and it worked approximately 1 week. After that it does not allow to login. Nothing except updates of packages are installed on server (Fedora 31).

Now nobody can login using web-site but can login using webdav client app (admin account as well). Changing of password with occ does not help.

**Comment by kesselb** [comment]
I think it's a setup issue. My Nextcloud runs for more than 2 years now and I can still login even after a upgrade from PHP 7.1. to PHP 7.4.

Ask your question at https://help.nextcloud.com and try to figure out whats wrong. You can always come back to GitHub and open a new issue if you found a bug.

**Comment by hardhub** [comment]
I have found solution:

I needed to make `/var/lib/php/sessions` writable for nextcloud web server (I updated ownership to nginx group).

Probably it is changed after some updates.

**Comment by Erycus** [comment]
hardhub is correct.  Faced the exact same problem after upgrading php 7.2 to 7.4 on my Centos 7 installation and could not log in to the web client.  The desktop and mobile clients continued to work fine, just an issue with the web interfaces.

After making /var/lib/php/session writable for nginx, logins via the web client worked fine again.

sudo chown -R nginx:nginx /var/lib/php/session
sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/lib/php/session(.*)?"
sudo restorecon -vR /var/lib/php/session
