### ISSUE TITLE
Select adressbook for birthday calendar (or show only activ calendars)

### ISSUE THREAD

**Issue by omocinteractive** [nextcloud/server#12791]
Expected behaviour
Select adressbook for birthday calendar or show only birthdays from active calendars

Actual behaviour
All birthdays are shown (also of a inactive contact book with archived contacts, so you have to delete the birthday info before you move it to the archive)

Calendar version: (see the apps page)
1.64

**Comment by MorrisJobke** [comment]
@georgehrke @skjnldsv Is this calendar or contacts app?

**Comment by georgehrke** [comment]
@MorrisJobke CalDAV\BirthdayGenerator in the day app :)

**Comment by georgehrke** [comment]
@skjnldsv Is this something that you would want in the Contacts app? (Selecting which address books should be considered for the birthday calendar)

**Comment by skjnldsv** [comment]
@georgehrke not sure :)
Seems complicated for a minimal gain.

Sorry @omocinteractive, too little request for it and we think this does not fit our roadmap. So we'll not invest time into this. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by kosli** [comment]
@omocinteractive I would be interested in such a feature too, as I don't want to have for all of my 1000 contacts the birthdays shown... (even that I have saved the birthdate in the contact)

**Comment by omocinteractive** [comment]
@all: Sorry, i got no mail-notication about new posts.
@georgehrke: yes, this it what i mean.
