### ISSUE TITLE
Grid toggle overlays Collabora view

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#12797]
The top right of the Collabora view is the close icon.

* expected: it is just the close icon
* actual: the grid view toggle is also visible

<img width="137" alt="bildschirmfoto 2018-12-04 um 00 36 50" src="https://user-images.githubusercontent.com/245432/49408519-e4a6f900-f75c-11e8-8acc-f2f2e0c4d982.png">

cc @jancborchardt @skjnldsv because you touched this lately.

**Comment by bpcurse** [comment]
ref. #12761

**Comment by skjnldsv** [comment]
I thought this was fixed! Someone came to ask me and did it on the hackweek iirc. :thinking:

**Comment by rullzer** [comment]
@juliushaertl didn't you work on this?

**Comment by juliushaertl** [comment]
Yes, I have a fix for richdocuments, but I still need to test it across all supported Nextcloud version. On my list for this week.

Let's close this in favor of https://github.com/nextcloud/richdocuments/issues/317
