### ISSUE TITLE
Unnecessary re-scan slows down users listing.

### ISSUE THREAD

**Issue by nininia** [nextcloud/server#12809]
It was detected that some data was displayed very slowly. Investigation has shown that the interruption happened because of '-1' in size of directory. 

- It is checking file info in oc_filecache every time accessing files from DB . (getCacheEntry from lib/private/Files/View.php.)

- If data in oc_filecache is empty or size == -1, attribute re-scan will be started (scan() from lib/private/Files/Cache/Scanner.php)

- In my case it will re-scan directory with settings of specific nextcloud instance every time! 
Because some of subdirs contains empty folders.

- Standard realization in OC\Files\Storage\Common doesn`t return directory size:

```
if ($data['mimetype'] == 'httpd/unix-directory') {
  $data['size'] = -1; //unknown
} else {
  $data['size'] = $this->filesize($path);
}
```

It is supposed that dir size will be counted as summary of files in  handleChildren().
But if at least one subdir is empty, handleChildren  will stop counting! and set -1 to whole directory.
```
 if ($data) {
	if ($data['mimetype'] === 'httpd/unix-directory' and $recursive === self::SCAN_RECURSIVE) {
		$childQueue[$child] = $data['fileid'];
	} else if ($data['mimetype'] === 'httpd/unix-directory' and $recursive === self::SCAN_RECURSIVE_INCOMPLETE and $data['size'] === -1) {
		// only recurse into folders which aren't fully scanned
		$childQueue[$child] = $data['fileid'];
	} else if ($data['size'] === -1) {
		$size = -1;
	} else if ($size !== -1) {
		$size += $data['size'];
	}
}
```

- Workaround :+1: : If to remove all empty folders, problem will gone.

### Steps to reproduce
1. Install nextcloud 13.0.5 or 14.0.4
2. list users
3.  wait 

### Expected behaviour
quick work)

### Actual behaviour
it is sleeping little bit  

### Server configuration

**Operating system**:
CentOS 7.5
**Web server:**
Apache 2.4.6
**Database:**
MariaDB 10.3.8
**PHP version:**
7.0.31
**Nextcloud version:** (see Nextcloud admin page)
13.0.5 ->14.0.4 (reproduced after update)
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
from archive

**Comment by kesselb** [comment]
cc @icewind1991 @rullzer

**Comment by blizzz** [comment]
Hm, it is been a while. Is this still valid?
