### ISSUE TITLE
IE11: user management empty site

### ISSUE THREAD

**Issue by team-a2** [nextcloud/server#12806]
### Steps to reproduce
1. Use nextcloud 14.0.4 with MSIE11 and go to the user management page (/index.php/settings/users)
2. See just the header and an empty page
3. The F12-console says "SCRIPT1002: Syntaxfehler settings-vue.js (129,20679)"

### Expected behaviour
Get an user management page as in Firefox or Chrome

### Actual behaviour
Get an empty page

### Server configuration

**Operating system**:
Ubuntu 16.04.5

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.0.36

**PHP version:**
7.0.32

**Nextcloud version:** 
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.3, 14.0.2, ...

**List of activated apps:**
as base installation

### Client configuration
**Browser:**
InternetExplorer 11.1446.15063.0

**Operating system:**
Windows 10

#### Browser log
<details>
<summary>MSIE11 console</summary>
SCRIPT1002: Syntaxfehler
settings-vue.js (129,20679)

that means:
`!function(e,r){if("object"==typeof exports&&"object"==typeof module)module.exports=r();else if("function"==typeof define&&define.amd)define([],r);else{var n=r();for(var o in n)("object"==typeof exports?exports:e)[o]=n[o]}}(window,function(){return function(e){var r={};function n(o){if(r[o])return r[o].exports;var t=r[o]={i:o,l:!1,exports:{}};return e[o].call(t.exports,t,t.exports,n),t.l=!0,t.exports}return n.m=e,n.c=r,n.d=function(e,r,o){n.o(e,r)||Object.defineProperty(e,r,{enumerable:!0,get:o})},n.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},n.t=function(e,r){if(1&r&&(e=n(e)),8&r)return e;if(4&r&&"object"==typeof e&&e&&e.__esModule)return e;var o=Object.create(null);if(n.r(o),Object.defineProperty(o,"default",{enumerable:!0,value:e}),2&r&&"string"!=typeof e)for(var t in e)n.d(o,t,function(r){return e[r]}.bind(null,t));return o},n.n=function(e){var r=e&&e.__esModule?function(){return e.default}:function(){return e};return n.d(r,"a",r),r},n.o=function(e,r){return Object.prototype.hasOwnProperty.call(e,r)},n.p="",n(n.s=0)}([function(e,r,n){"use strict";function o(){return"undefined"==typeof OC?Promise.reject(new Error("OC not defined")):void 0===OC.PasswordConfirmation?Promise.reject(new Error("OC.PasswordConfirmation not defined")):OC.PasswordConfirmation.requiresPasswordConfirmation()?new Promise((e,r)=>{OC.PasswordConfirmation.requirePasswordConfirmation(e,{},r)}):Promise.resolve()}n.r(r),n.d(r,"default",function(){return o})}])});
//# sourceMappingURL=main.js.map`
</details>

**Comment by TW20-MH** [comment]
I have exactly the same issue with a fresh installed version 14.0.4 with Internet Explorer 11 .134.17763.0
PHP 7.2.10
Ubuntu 18.04
Win 10

In other browsers there are no issues.

**Comment by ChristophWurst** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
Coming from the nextcloud pass confirmation popup
![capture d ecran_2018-12-05_20-46-32](https://user-images.githubusercontent.com/14975046/49539859-e8f32380-f8ce-11e8-98a9-654b68747c00.png)

I'm guessing babel is not transpiling the external modules :'(

**Comment by skjnldsv** [comment]
I guess we can close? :)

**Comment by ChristophWurst** [comment]
Yes, fixed in #12859
