### ISSUE TITLE
Collaborative tags stopped working

### ISSUE THREAD

**Issue by codesmaker** [nextcloud/server#12810]
Hi,

When I create a file or folder and go to details to assign tags, the tags field does not show. That is, when I click on "Tags" nothing happens and for the files and folders that are already tagged, I get the tags field but previously assigned tags aren't showing.

I've recently upgraded from v13 to v14.0.4. It seems that it is a bug in the version that I'm running.

Nextcloud v14.0.4
Collaborative tags v1.4.0

![nextcloud-tags2](https://user-images.githubusercontent.com/6999196/49439251-d7235a80-f7c0-11e8-8ec0-cd574ed2988b.png)
![nextcloud-tags1](https://user-images.githubusercontent.com/6999196/49439252-d7bbf100-f7c0-11e8-9f0b-75b4866eb9fd.png)

**Comment by codesmaker** [comment]
Maybe related to #10774 ? For me, it never works though.

Is there any quick workaround to fix it till v14.0.5 is released?

**Comment by ChristophWurst** [comment]
cc @nickvergessen

**Comment by codesmaker** [comment]
Any updates? It is important because file access control depends on it.

**Comment by ChristophWurst** [comment]
Tested and works on 15 RC3. I see this is Vue multiselect now, @skjnldsv did you work on this?

**Comment by skjnldsv** [comment]
@ChristophWurst not that I remember :thinking:

**Comment by rubbergh** [comment]
Also here no longer works with v14.0.4. With v14.0.3 it was working!

**Comment by nickvergessen** [comment]
Just tested again and it works fine here with stable14 which has no change to 14.0.4 in the systemtags app (which is the collaborative tags)

Please press F12 go to "Console" and see if there are any errors while loading the page or trying to open the tags menu

**Comment by rubbergh** [comment]
This is what I can see in the console after "RELOAD":

Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.
JQMIGRATE: Migrate is installed, version 1.4.0
core.js:7:542
unreachable code after return statement[Weitere Informationen]
merged.js:1501:4
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung.
merged.js:2176
Source-Map-Fehler: SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Ressourcen-Adresse: https://XXX.YYY.ZZZ/nc/apps/notifications/js/notifications.js?v=9bc60c60-5
Source-Map-Adresse: notifications.js.map[Weitere Informationen]
New search handler registered
search.js:66:4
querying Whats New data was successful: nocontent
merged-template-prepend.js:4488:4
undefined
merged-template-prepend.js:4489:4

**Comment by nickvergessen** [comment]
Can you disable the notifications app and see if that solves it?

**Comment by rubbergh** [comment]
Now (notifications disabled) I receive:
Content Security Policy: Die Direktive 'frame-src'  sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'child-src'.  (unbekannt)
JQMIGRATE: Migrate is installed, version 1.4.0  core.js:7:542
unreachable code after return statement[Weitere Informationen]  merged.js:1501:4
New search handler registered  search.js:66:4
querying Whats New data was successful: nocontent  merged-template-prepend.js:4488:4
undefined  merged-template-prepend.js:4489:4

line 1501:			function inFileList($row, result) {
				return false;

				if (! self.fileAppLoaded()) {
					return false;
				}
				var dir = self.fileList.getCurrentDirectory().replace(/\/+$/,'');
				var resultDir = OC.dirname(result.path);
				return dir === resultDir && self.fileList.inList(result.name);
			}

**Comment by nickvergessen** [comment]
I have those warnings too, but do the tags work now?

**Comment by rubbergh** [comment]
No... .sorry.. .forgot to mention that!

**Comment by nickvergessen** [comment]
Can you send me a test account from your instance? Just email it to `<my github username>@nextcloud.com`

**Comment by nickvergessen** [comment]
Strange, the click event is not bound to the item:
https://github.com/nextcloud/server/blob/6957e1f39c68886b15b6b62ca45c89282ab94e7d/apps/systemtags/js/systemtagsinfoviewtoggleview.js#L42-L44

@skjnldsv do you want to have a look, I tried to step with the JS debugger through it, but it does the exact same steps it's doing in my stable14. Could it be that another app is interfering with Backbone?

@rubbergh can you for testing disable all apps that are not shipped by default? as far as I can see its only dropit and groupfolders, from which none should be causing issues.

**Comment by rubbergh** [comment]
Am I safe to disable "group folders" and wont loose my data in the group folders?

**Comment by rubbergh** [comment]
Welll.. also the "favorites star" does not work in detail dialog... should work, or am I wrong?

Well... the star does work if I use the context dialog to active item as favorite... then the star in the detail dialog works again... but only this way.

**Comment by sgofferj** [comment]
I don't have dropit installed and disabled group folders for testing. No change here. I see the same problem since the update from .3 to .4.
I also see another symptom which could be related... The PDF preview in the properties sidebar looks messed up and the "loading" animation never stops for PDFs.

**Comment by rubbergh** [comment]
Same here also.

**Comment by nickvergessen** [comment]
Yeah it seems like something is breaking all JS at some point. Everything that is linked before works (details sidebar can be opened) but everything that would be done after the breaking point does not, e.g. tagging and pdf previews

**Comment by rubbergh** [comment]
Do we need to downgrade?

**Comment by rubbergh** [comment]
Should upgrade on 15.0 help us?

**Comment by aventrax** [comment]
Exactly same issue here. A few days before I updated my installation from 14.0.3 to 14.0.4 and I enabled the group folders. Tags worked before.

**Comment by hlecorche** [comment]
Fixed by #12577 / #12598

**Comment by nickvergessen** [comment]
Okay, so it will be fixed with 14.0.5 which is planned for January.

You can copy teh fix from the linked PRs manually for the time being.

**Comment by rubbergh** [comment]
Thnx. With patch seems to work again.

**Comment by vijaydwivedics** [comment]
Can any give proper solution for this issue? 

Collaborative tags stopped working in version 14.0.4
![image](https://user-images.githubusercontent.com/21194343/50271140-db56a580-0459-11e9-88b3-3e9503f8806e.png)

**Comment by ChristophWurst** [comment]
> Can any give proper solution for this issue?

Did you actually read any of the previous comments before you posted yours? https://github.com/nextcloud/server/issues/12810#issuecomment-447862513

**Comment by vijaydwivedics** [comment]
> > Can any give proper solution for this issue?
> 
> Did you actually read any of the previous comments before you posted yours? [#12810 (comment)](https://github.com/nextcloud/server/issues/12810#issuecomment-447862513)

yes i have read but i don't understand what is the solution.

**Comment by ChristophWurst** [comment]
No worries. 

The fixes are linked at https://github.com/nextcloud/server/issues/12810#issuecomment-447630594. The patch release will be available soonish.
