### ISSUE TITLE
 Authentication problem after upgrade to 10.0.0

### ISSUE THREAD

**Issue by sven3** [nextcloud/server#1282]
### Steps to reproduce
1. Install Nextcloud 9.0.53 with IMAP authentication
2. Upgrade to 10.0.0 via "php occ upgrade" as user www-data
3. Try to login
### Expected behaviour

Files and calendar can be seen, login without error message
### Actual behaviour

Login seems to fail, Web Interfaces says "Problem loading page, reloading in 5 seconds". Files are not displayed.
### Server configuration

**Operating system**: Debian GNU/Linux "jessie" 8.5 on amd64

**Web server:** Apache 2.4.10 (unmodified Debian package 2.4.10-10+deb8u5)

**Database:** MySQL 5.5.50 (unmodified Debian package 5.5.50-0+deb8u1)

**PHP version:** 5.6.24 (unmodified Debian package 5.6.24+dfsg-0+deb8u1)

**Nextcloud version:** Nextcloud 10.0 (stable) as reported on admin site, but reported as 9.1.0.16 in config.php

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from previous stable version 9.0.53, which ran without problems.

**Where did you install Nextcloud from:** Downloaded the Zip file from https://nextcloud.com/install/

**Signing status:**
<details>
<summary>

Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

Enabled:
- admin_audit: 1.0.0
- calendar: 1.3.3
- comments: 1.0.0
- dav: 1.0.0
- federatedfilesharing: 1.0.1
- federation: 1.0.1
- files: 1.5.2
- files_external: 1.0.2
- files_pdfviewer: 0.8.1
- files_sharing: 1.0.0
- files_texteditor: 2.1
- files_trashbin: 1.0.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- notifications: 0.3.0
- password_policy: 1.0.0
- provisioning_api: 1.0.0
- serverinfo: 1.1.1
- survey_client: 0.1.5
- systemtags: 1.0.2
- templateeditor: 0.1
- theming: 1.0.1
- updatenotification: 1.0.1
- user_external: 0.4
- workflowengine: 1.0.1
  Disabled:
- activity
- encryption
- external
- files_accesscontrol
- files_automatedtagging
- files_retention
- files_versions
- gallery
- user_ldap
- user_saml
  </details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

{
    "system": {
        "instanceid": "oc4ddy17c9k5",
        "passwordsalt": "**_REMOVED SENSITIVE VALUE**_",
        "secret": "**_REMOVED SENSITIVE VALUE**_",
        "trusted_domains": [
            "my-domain.de",
            "my-other-domain.de"
        ],
        "datadirectory": "\/var\/www\/my-domain.de\/cloud\/data",
        "overwrite.cli.url": "https:\/\/my-domain.de\/cloud",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "owncloud2",
        "dbhost": "webserver",
        "dbtableprefix": "oc_",
        "dbuser": "**_REMOVED SENSITIVE VALUE**_",
        "dbpassword": "**_REMOVED SENSITIVE VALUE**_",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{localhost:993\/imap\/ssl\/novalidate-cert\/notls\/readonly}"
                ]
            }
        ],
        "htaccess.RewriteBase": "\/cloud"
    }
}
</details>

**Are you using external storage, if yes which one:** yes, local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** yes, IMAP authentication
### Client configuration

**Browser:** Firefox 48.0

**Operating system:** Ubuntu 16.04 on amd64
#### Web server error log

<details>
<summary>

Web server error log</summary>

[Wed Aug 31 19:01:47.479659 2016] [:error] [pid 4522] [client 2001:db8:1:1:ed64:4cb2:c227:b392:40452] PHP Fatal error: Uncaught exception 'Exception' with message 'Session has been closed - no further changes to the session are allowed' in /var/www/my-domain.de/cloud/lib/private/Session/Internal.php:154\nStack trace:\n#0 /var/www/my-domain.de/cloud/lib/private/Session/Internal.php(64): OC\Session\Internal->validateSession()\n#1 /var/www/my-domain.de/cloud/lib/private/Session/CryptoSessionData.php(164): OC\Session\Internal->set('encrypted_sessi...', 'e3b4eba3a833fa5...')\n#2 /var/www/my-domain.de/cloud/lib/private/Session/CryptoSessionData.php(67): OC\Session\CryptoSessionData->close()\n#3 [internal function]: OC\Session\CryptoSessionData->__destruct()\n#4 {main}\n thrown in /var/www/my-domain.de/cloud/lib/private/Session/Internal.php on line 154, referer: https://my-domain.de/cloud/
</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

{"reqId":"O+0RJqz9QDOXkLpQrjyh","remoteAddr":"2001:db8:1:1:ed64:4cb2:c227:b392","app":"core","message":"Login failed: 'sven' (Remote IP: '2001:db8:1:1:ed64:4cb2:c227:b392')","level":2,"time":"2016-08-31T19:14:22+02:00","method":"GET","url":"\/cloud\/index.php\/apps\/files\/","user":"sven"}
</details>
#### Browser log

<details>
<summary>

Browser log</summary>

I don't have a browser log I could paste here.
</details>

**Comment by sven3** [comment]
Unfortunately the problem is still present in 10.0.1. :-(

**Comment by nickvergessen** [comment]
Hmm, seems like one of your apps is causing this issue.
Can you add some code before the following line:
https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/lib/private/Session/Internal.php#L154-L154
```php
throw new \Exception('Session has been closed - no further changes to the session are allowed');
```

If you add the following code before it, there should be useful information in your nextcloud.log file, once this occurred again.
```php
\OC::$server->getLogger()->logException(new \Exception('Session has been closed - no further changes to the session are allowed'));
```

**Comment by sven3** [comment]
Thanks for the answer, nickvergessen. This is what gets logged after making the change you proposed:

{"reqId":"B0+juLgGA1p2CId+1xnu","remoteAddr":"2001:db8:1:1:957f:9801:eb1c:8b47","app":"no app in context","message":"Exception: {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/my-domain.de\\\/cloud\\\/lib\\\/private\\\/Session\\\/Internal.php(64): OC\\\\Session\\\\Internal->validateSession()\\n#1 \\\/var\\\/www\\\/my-domain.de\\\/cloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(164): OC\\\\Session\\\\Internal->set('encrypted_sessi...', 'bbb3151aa79c52d...')\\n#2 \\\/var\\\/www\\\/my-domain.de\\\/cloud\\\/lib\\\/private\\\/Session\\\/CryptoSessionData.php(67): OC\\\\Session\\\\CryptoSessionData->close()\\n#3 [internal function]: OC\\\\Session\\\\CryptoSessionData->__destruct()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/my-domain.de\\\/cloud\\\/lib\\\/private\\\/Session\\\/Internal.php\",\"Line\":154}","level":3,"time":"2016-09-30T13:19:24+02:00","method":"GET","url":"\/cloud\/index.php\/apps\/files\/","user":"sven"}

**Comment by Watchwolf** [comment]
Hello,

I have exactly the same problem, same configuration and same error.

**Comment by Watchwolf** [comment]
{"reqId":"AK74HSlBTbj2rZpto7fs","remoteAddr":"","app":"core","message":"Error while running background job (class: OCA\\Activity\\BackgroundJob\\EmailNotification, arguments: ): {\"Exception\":\"Exception\",\"Message\":\"Session has been closed - no further changes to the session are allowed\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/memory.php(49): OC\\\\Session\\\\Memory->validateSession()\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/security\\\/csrf\\\/tokenstorage\\\/sessionstorage.php(63): OC\\\\Session\\\\Memory->set('requesttoken', '6km4cyDwyk769od...')\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/security\\\/csrf\\\/csrftokenmanager.php(57): OC\\\\Security\\\\CSRF\\\\TokenStorage\\\\SessionStorage->setToken('6km4cyDwyk769od...')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/public\\\/util.php(496): OC\\\\Security\\\\CSRF\\\\CsrfTokenManager->getToken()\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/template.php(75): OCP\\\\Util::callRegister()\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/mailqueuehandler.php(250): OC_Template->__construct('activity', 'email.notificat...', '')\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/backgroundjob\\\/emailnotification.php(134): OCA\\\\Activity\\\\MailQueueHandler->sendEmailToUser('admin', 'support@actecil...', 'fr', 'Europe\\\/Berlin', 1478166314)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/activity\\\/lib\\\/backgroundjob\\\/emailnotification.php(94): OCA\\\\Activity\\\\BackgroundJob\\\\EmailNotification->runStep(500, 1478166314)\\n#8 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OCA\\\\Activity\\\\BackgroundJob\\\\EmailNotification->run(NULL)\\n#9 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/backgroundjob\\\/timedjob.php(53): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#10 \\\/var\\\/www\\\/owncloud\\\/cron.php(141): OC\\\\BackgroundJob\\\\TimedJob->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/session\\\/memory.php\",\"Line\":105}","level":3,"time":"2016-11-03T09:45:15+00:00"}

**Comment by GitHubUser4234** [comment]
@sven3 : Please refer to #1303, not sure whether the fix for it also solves your problem, but it's worth a shot.

**Comment by nickvergessen** [comment]
Closing this. Feel free to reopen, when the above issue does not fix this.

**Comment by sven3** [comment]
I applied commit 028c6682935232c50ec729f38f97b2342f8363ad, but this does not seem to fix my problem. :-( Anyway, thanks for your continued help!

**Comment by sven3** [comment]
@nickvergessen , the symptoms have changed with Nextcloud 11.0.0. I have described them here: https://help.nextcloud.com/t/authentication-problem-after-upgrade-to-10-0-0/2837/8

**Comment by rseabra** [comment]
After upgrading to nextcloud 11, I'm facing inability to login as well.

**Comment by rseabra** [comment]
Logfile with debug level 0, censored values:

{"reqId":"CENSORED1","remoteAddr":"MYIP","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-12-25T12:43:19+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"--","version":"11.0.0.10"}
{"reqId":"CENSORED2","remoteAddr":"MYIP","app":"admin_audit","message":"Login attempt: \"MYLOGIN\"","level":1,"time":"2016-12-25T12:43:22+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documentos","user":"--","version":"11.0.0.10"}
{"reqId":"CENSORED2","remoteAddr":"MYIP","app":"admin_audit","message":"Login successful: \"MYLOGIN\"","level":1,"time":"2016-12-25T12:43:23+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Documentos","user":"MYLOGIN","version":"11.0.0.10"}
{"reqId":"CENSORED3","remoteAddr":"MYIP","app":"admin_audit","message":"Login attempt: \"MYLOGIN\"","level":1,"time":"2016-12-25T12:43:23+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Private","user":"--","version":"11.0.0.10"}
{"reqId":"CENSORED4","remoteAddr":"MYIP","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-12-25T12:43:23+00:00","method":"GET","url":"\/index.php\/apps\/gallery\/config?extramediatypes=1","user":"--","version":"11.0.0.10"}
{"reqId":"CENSORED3","remoteAddr":"MYIP","app":"admin_audit","message":"Login successful: \"MYLOGIN\"","level":1,"time":"2016-12-25T12:43:23+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/Private","user":"MYLOGIN","version":"11.0.0.10"}
{"reqId":"CENSORED5","remoteAddr":"MYIP","app":"admin_audit","message":"Login attempt: \"MYLOGIN\"","level":1,"time":"2016-12-25T12:43:23+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/tmp","user":"--","version":"11.0.0.10"}
{"reqId":"CENSORED5","remoteAddr":"MYIP","app":"admin_audit","message":"Login successful: \"MYLOGIN\"","level":1,"time":"2016-12-25T12:43:23+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/tmp","user":"MYLOGIN","version":"11.0.0.10"}

**Comment by rseabra** [comment]
This appears to only affect the web ui, as caldav requests and carddav requests seem to be working.

**Comment by rseabra** [comment]
Oh, and I don't use IMAP authentication, so sorry if I am causing noise, but the behaviour is somewhat similar.
