### ISSUE TITLE
Jquery autocomplete dropdown entries broken

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#12832]
Just upgraded to master, now it looks off.
Something to do with the latest jQuery ui?

@juliushaertl @nextcloud/designers 
![capture d ecran_2018-12-04_21-55-49](https://user-images.githubusercontent.com/14975046/49472447-c5b56f00-f80f-11e8-9625-fb15e7f86f74.png)

**Comment by MorrisJobke** [comment]
> Just upgraded to master, now it looks off.
> Something to do with the latest jQuery ui?

Most likely 🙈

**Comment by weeman1337** [comment]
I'll have a look.
