### ISSUE TITLE
Drag & drop on long list not working

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12844]
- have a long folder list, must be more than fits on screen
- create a file
- drag file -> first folder is shown
- now try to "scroll down" (move mouse down) -> list flickers, but no scrolling
- after releasing drag, I cannot scroll anylonger

(Chromium, tested on own RC2 and c.nc.c)

**Comment by MorrisJobke** [comment]
@tobiasKaminsky Did this worked before?

cc @skjnldsv @danxuliu

**Comment by MorrisJobke** [comment]
cc @juliushaertl @ChristophWurst

**Comment by skjnldsv** [comment]
> @tobiasKaminsky Did this worked before?
> 
> cc @skjnldsv @danxuliu

No idea :cry:

**Comment by tobiasKaminsky** [comment]
Yes, on NC13 it is working.

**Comment by MorrisJobke** [comment]
> Yes, on NC13 it is working.

But you were talking about a NC 15 setup. Did it worked in NC 14?

**Comment by tobiasKaminsky** [comment]
Yes, NC14 is also working.

**Comment by sehucke** [comment]
For me, it is _not_ working in current NC 14.0.4. Behavior is the same as described by @tobiasKaminsky . Tested in Firefox 63.0.3 (uMatrix, uBlock and PrivacyBadger all disabled on my domain). Same with Chromium Version 70.0.3538.110 (Official Build).

Did the upgrade yesterday, can confirm that it worked in NC 13.

**Comment by hoellen** [comment]
I got the same problem on Nextcloud 15.0.4. Tested in Firefox 65.0.1 and Chromium 72.0.3626.109. If you need more information about it, I'm happy to help.
