### ISSUE TITLE
default_locale --> set to de_DE does not apply for new users

### ISSUE THREAD

**Issue by ETrko** [nextcloud/server#12851]
### Steps to reproduce
1. set default_locale in config to de_DE
2. new created users gets english locale settings

### Expected behaviour
should be de_DE instead of en

### Actual behaviour
is en

### Server configuration

Nextcloud 14.04

**Updated from an older Nextcloud/ownCloud or fresh install:**
 updated from 13

**Comment by ETrko** [comment]
any update here?

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
