### ISSUE TITLE
API for configuration of external storages

### ISSUE THREAD

**Issue by va1entin** [nextcloud/server#12852]
**Is your feature request related to a problem? Please describe.**
There is no really nice way to non-interactively configure external storages en mass. External storages can either be configured via the web interface or via occ on the command line. occ also allows to import external storage configs in JSON format but calls them "legacy". 
My use case is that dozens of SMB shares are regularly created and should be mounted in Nextcloud automatically

**Describe the solution you'd like**
I would love to have an API (maybe as a part of OCS) to configure external storages without relying on occ syntax and the CLI.

**Describe alternatives you've considered**
I have used occ for the time being. It does the job but it's pretty slow and there's too much overhead (Especially because my Nextcloud runs in the official container, which is why I'm using docker exec to execute occ). I'm not using the JSON configs, because they're legacy and always require ALL external storages. So I can't just add one single storage, instead I have to configure all existing ones again + the new one. That's also problematic, because external storage names can't be "used twice", aka. exist already and be configured again. In other words I'd have to remove all existing storages, and import them all again via JSON config just to configure one new storage. For a backup and restore scenario that's probably just what one wants though, so I assume that's what the JSON config was designed for.

**Additional context**

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
