### ISSUE TITLE
Arrow functions cause issues on IE

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#12875]
Similar to fixes like #12340 and https://github.com/nextcloud/server/pull/12860, we have to make sure our scripts and script bundles don't use the arrow function syntax as it's not supported on IE.

### Steps to reproduce
1. Use arrow function in a script
2. Transpile with babel
3. Still get a syntax error

### Expected behaviour
Scripts should work on all supported browsers, including IE. Apps (and server) should use the transformation plugin for Babel like https://github.com/ChristophWurst/nextcloud-password-confirmation/pull/2.

### Actual behaviour
Sytax errors and therefore broken scripts.

### Server configuration

**Nextcloud version:**

Starting somewhere around Nextcloud 14

---

- [ ] Update notification
  * https://github.com/nextcloud/server/blob/v14.0.3/apps/updatenotification/js/updatenotification.js#L26
- [ ] Settings

... not a complete list yet, needs investigation

cc @nextcloud/javascript

**Comment by juliushaertl** [comment]
Seems fixed to me with https://github.com/nextcloud/server/commit/15dc9d8d158f3769b2b72a31f89eb618e56cf01c for updatenotifications and settings has a proper babelrc file as well.
