### ISSUE TITLE
15.0.0 RC 3: links on admin/overview link to version 14

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#12894]
### Steps to reproduce
1. Open Settings | Administration | Overview
2.1 link documentation links to .../docs.nextcloud.com/server/**14**/go.php?to=admin-setup-well-known-URL
2.1 link documentation links to ...docs.nextcloud.com/server/**14**/go.php?to=admin-performance
2.3 link  installation guides  links to  ...docs.nextcloud.com/server/**14**/go.php?to=admin-install

Screenshot of .../nextcloud/index.php/settings/admin/overview:

![screenshot_2018-12-06 settings - nextcloud](https://user-images.githubusercontent.com/34692335/49609936-54a3c200-f99d-11e8-8bc8-b95489009243.png)

### Expected behaviour
The links fits to the installed version , ex.  ......docs.nextcloud.com/server/**15**/...

### Actual behaviour
The links link to ...docs.nextcloud.com/server/**14**/...

**Nextcloud version:**
Nextcloud 15.0.0 RC 3

**Updated from an older Nextcloud/ownCloud or fresh install:**
deleted old folder /var/www/nextcloud
drop old database from nextcloud
then installation with nextcloud-15.0.0RC3.tar.bz2

**Comment by danielkesselberg** [comment]
Fix #12896
