### ISSUE TITLE
Make Notification more configurable

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#129]
Notification could inform the administrator about **available** updates of nextcloud and all apps available (e.g. or "installed" apps only, )

The message window should be more moved to the right since, presently it overlaps with the icons of direct menu (if installed and enabled).

regards, hitam4450

**Comment by MorrisJobke** [comment]
This should maybe introduced as a notification in the notification center ;)

**Comment by autrui** [comment]
Does this mean that the admin will get an email (activity) notification when there's a new version available? (unless this is already possible) 
On the other hand, I've found the version shown on the admin page not to be very reliable many times. Even a week or 2 after a new version had been released it still showed the old one.

**Comment by MorrisJobke** [comment]
> On the other hand, I've found the version shown on the admin page not to be very reliable many times. Even a week or 2 after a new version had been released it still showed the old one.

I guess this was by intention one time, because there was a issue. But I don't remind the actual case anymore. We are working on this. The mechanism itself was totally working, but the release wasn't put into the queue for this mechanism back then.

**Comment by MorrisJobke** [comment]
> This should maybe introduced as a notification in the notification center ;)

It is already there:

<img width="589" alt="bildschirmfoto 2016-12-21 um 15 24 32" src="https://cloud.githubusercontent.com/assets/245432/21392738/a183ab84-c791-11e6-83f0-e910a4d2ac3d.png">

let me try to fix the popover.

**Comment by MorrisJobke** [comment]
Fix for this is in #2803

@hitam4450 Please test the change ;)
