### ISSUE TITLE
Move contactsmenu to vue

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#12905]
The contactsmenu (behind the contact icon on every page on top) should be moved to Vue.

The vue programs from settings are probably a good place to start.

**Comment by mand0ng** [comment]
hi would like to help on this issue

**Comment by rullzer** [comment]
@mand0ng that would be great!

If needed @ChristophWurst @skjnldsv or @juliushaertl can probably get you started

**Comment by skjnldsv** [comment]
Yes :)
@mand0ng if you want, you can join our nextcloud vue dev channel so we can talk a bit about it :rocket:

**Comment by skjnldsv** [comment]
dupe https://github.com/nextcloud/server/issues/15586
