### ISSUE TITLE
simpleSignUpLink.shown not work in 14.0.4

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#12909]
In my config I deactivated the advertisement, but the advertising is still there. If I share a photo and open the link I see the advertisement "Get your own free account" in the footer.

```
# cat config/config.php | grep simpleSignUpLink.shown
  'simpleSignUpLink.shown' => 'false',
```

Workaround: 

Open the core/templates/layout.public.php and delete this part:

```
<?php
		if ($_['showSimpleSignUpLink']) {
			?>
			<p>
				<a href="https://nextcloud.com/signup/" target="_blank" rel="noreferrer noopener">Get your own free account</a>
			</p>
			<?php
```

**Comment by danielkesselberg** [comment]
tl;dr `'simpleSignUpLink.shown' => false,` (remove the single quotes around false)

https://github.com/nextcloud/server/blob/761ba1801b6a932820beacb36f343ec3b07c471c/lib/private/TemplateLayout.php#L129

`showSimpleSignUpLink` is false when value from config !== false. 

![image](https://user-images.githubusercontent.com/3902676/49649786-76975600-fa2a-11e8-845a-99852b46cc74.png)
