### ISSUE TITLE
[NC15 RC3] Set default expiration date / Public link sharing settings misbehaving

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#12900]
The public link sharing settings in NC15 RC3 (and RC1 and RC2 also) are misbehaving. Settings get ignored. Links are duplicated. And links are not removed.

S**teps to reproduce**
Upload a file. After the upload has finished, "Processing files" is now displayed. When the file has been processed, make a public share link, untick the "Set expiration date" and use the icon to copy the link to the copy buffer. Close the Details section. And re-open the Details section.

**Expected behaviour**
A public share link has been created without expiration date.

**Actual behaviour**
**Two** (duplicate) public share links have been created **with** expiration date of 1 month later.

It will take some time to correct this, as the duplicate does not immediatly disappear when you remove it,
Actually, removing one, might create a third link. Afterwards, you still need to untick the expiration date on the left-over shared link. 

And once corrected, you might find hours later that the expiration date has been ticked again and both links have returned! It looks like a mandatory 1 month expiration date is put on all public shares.

![1](https://user-images.githubusercontent.com/31093459/49616513-698a5080-f9b1-11e8-8512-21c0c85f9f81.png)
![2](https://user-images.githubusercontent.com/31093459/49616630-be2dcb80-f9b1-11e8-9cd2-7d65df1aa1e7.png)

**Comment by juliushaertl** [comment]
@nextcloud/sharing

**Comment by timmersr** [comment]
[https://github.com/orgs/nextcloud/teams/sharing] ??

**Comment by timmersr** [comment]
![insta](https://user-images.githubusercontent.com/31093459/49700886-03860f00-fbe5-11e8-9d73-a9d3c13031f1.gif)

**Comment by timmersr** [comment]
I found that this misbehaviour and NC creating duplicate links, comes from the **default expiration date** being **enforced** eventhough this is not configured in the administrator settings.
![4](https://user-images.githubusercontent.com/31093459/49723973-82705b80-fc68-11e8-9395-c535e144f1c6.png)

If I disable the "Set default expiration date" the issue is not experienced,
If I enable it, the link duplication starts again.

**Comment by rullzer** [comment]
@timmersr thanks for the debugging
I'll get somebody to look into this for .1

**Comment by timmersr** [comment]
NOTE: disabling the "Set default expiration date" will also change the links themselves, so none of the former public links will work anymore.

**Comment by MorrisJobke** [comment]
> I'll get somebody to look into this for .1

🙈

**Comment by seblu** [comment]
I confirm. Same issue with 15.0.2.

**Comment by aSiCs2oo1** [comment]
Same issue with 15.0.3 and 15.0.4.

**Comment by xeoslaenor** [comment]
Same here with 15.0.4

"set default expiration date" unchecked : 

I create a public link, I set an expiration date, no problem
then I want to remove expiration link => the link is duplicated
New link is created without expiration date instead of removing expiration date from previous

**Comment by MorrisJobke** [comment]
> "set default expiration date" unchecked :
> 
> I create a public link, I set an expiration date, no problem
> then I want to remove expiration date => the link is duplicated
> New link is created without expiration date instead of removing expiration date from previous

Fixed via #14035 in 15.0.5
