### ISSUE TITLE
theming: unable to override images under core/img/filetypes

### ISSUE THREAD

**Issue by mikesteele81** [nextcloud/server#1290]
I've been working on customizing the "example" theme mainly by replacing colors and images.

I customized `core/img/filetypes/folder.svg` and put it under `themes/mytheme/core/img/filetypes/folder.svg`, but the stock file continued to be used.

I suspect this is because the file is nested within a subfolder of img:
1.  `lib/private/files/Detection.php` contains a line reading `$this->mimetypeIcons[$mimetype] = $this->urlGenerator->imagePath('core', 'filetypes/folder.svg');`
2. the imagePath function in `lib/private/URLGenerator.php` calls `basename` on the supplied path before working through a long decision tree to decide which file to load.
3. The `basename` function in `lib/private/legacy/util.php` splits the supplied path on '/' characters, throwing away all but the filename.

**Comment by mikesteele81** [comment]
I just noticed that my custom `filetypes/folder.svg` is used in the "Activity" app while the stock file is used in the "Files" app.

**Comment by adamcoulombe** [comment]
Any fix for this?

**Comment by MorrisJobke** [comment]
See https://docs.nextcloud.com/server/12/admin_manual/configuration_mimetypes/index.html and the two documentation pages after this. They explain how to theme mimetype icons.
