### ISSUE TITLE
Error when accessing with CarotDAV

### ISSUE THREAD

**Issue by devi69** [nextcloud/server#12904]
### Steps to reproduce
1.Install CarotDAV. (WebDAV client) http://rei.to/carotdav.html
2.Select the WebDAV connection and set the nextcloud server to connect to.
3.In the setting dialog, push connection test button.

### Expected behaviour
No error is displayed, and connection can be made normally.

### Actual behaviour
error was displayed.

No error was displayed until Nextcloud 12.0.2.  
The error is now displayed from Nextcloud 12.0.3 and later versions.  
By the way, no error is displayed in ownCloud 10.0.8.

### Server configuration

**Operating system**:
CentOS 7.3.1611

**Web server:**
Nginx 1.12.1-1

**Database:**
MariaDB 10.0.32-1

**PHP version:**
php 7.0.22-1  

**Nextcloud version:** (see Nextcloud admin page)
nextcloud 13.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
tar.bz2 file from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.6.1
  - calendar: 1.6.1
  - comments: 1.3.0
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - password_policy: 1.3.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - updatenotification: 1.3.0
  - user_ldap: 1.3.1
  - workflowengine: 1.3.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "trusted_domains": [
            "nc_13.0.8"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc_13.0.8",
        "dbtype": "mysql",
        "version": "13.0.8.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
CarotDAV 1.15.5   
http://rei.to/carotdav.html#download

**Operating system:**
Windows 10 Pro

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no error
```

```
nginx access.log(no error)

***.***.***.*** - - [07/Dec/2018:20:02:36 +0900] "OPTIONS /remote.php/webdav/ HTTP/1.1" 200 0 "-" "Rei.Fs.WebDAV/1.15.5" "-"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no logs
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
CarotDAV error log

Rei.Fs.SimpleWebException: The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF
	at Rei.Fs.Webdav.WebdavFs.GetResponse(HttpWebRequest request, Boolean notreqstream)
	at Rei.Fs.Webdav.WebdavFs.GetResourceOptions(Uri target)
	at Rei.Fs.Webdav.ConnectionTestForm.Check()
```
</details>

Thank you in advance.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version of nextcloud. After that, feel free to reopen.

**Comment by skjnldsv** [comment]
Is this still happening? Please make sure to upgrade to the latest version of nextcloud.

**Comment by devi69** [comment]
When I tried with Nextcloud 16.0.2, the connection error was resolved.
Thank you for the advice.
