### ISSUE TITLE
Give Nextcloud users an SSH Access

### ISSUE THREAD

**Issue by rmanibus** [nextcloud/server#12903]
Hi, 
I'm wondering for a while if it could be possible to have a proper ssh access to nextcloud.

For me there is two solution there : 

1) build a php ssh server (for example based on [pssht](https://github.com/fpoirotte/pssht)) However, this doesn't look really secured, as SSH is easilly vulnerable to side chanel attack (like timing attack). 

2) build a nextcloud CLI and configure open SSH to use it.
This one seems cool. with LDAP user we have nothing to do. both nextcloud and the SSH server authenticate users against LDAP.

The only problem is that the PAM file used by openssh is hardcoded in the binary. If I want to have two ssh servers on the host (one for local user with a bash shell and one for nextcloud users with nextcloud shell) It might be necessary to fork openssh and use a custom PAM file location. ( see [superuser.com](https://superuser.com/questions/792804/use-custom-ssh-authentication-mechanism-openssh))

![image](https://user-images.githubusercontent.com/10419172/49641347-2f9c6700-fa10-11e8-8666-d210a54e4418.png)

A cool feature also would be to develop a custom PAM module which allow to authenticate directly against nextcloud user.

It might be possible to authenticate users with a private key if the $HOME variable is set with the user data folder. That way creating a .ssh folder containing a authorized_hosts file would allow the user to connect with his private key.

Do you think this could work ?

**Comment by j-ed** [comment]
@rmanibus Interesting idea. As far as I understood Nextcloud can act as an OAuth2 server. With the right PAM module you should be able to implement this function. Here you will find further information on this:
https://github.com/CyberDem0n/pam-oauth2
https://github.com/shimt/pam-exec-oauth2

Further information on web based ssh shells can be found here:
https://en.wikipedia.org/wiki/Web-based_SSH

**Comment by rmanibus** [comment]
Indeed, Oauth seems the best solution here.

I created a repository for the shell app.

https://github.com/rmanibus/NextcloudShell

for now the user is passed in param
```
php occ nextcloudshell:run loic
```

**Comment by rullzer** [comment]
This is not something we would want in the core of Nextcloud. There are serious security risk with allowing everybody that has an account ssh access.

So if you can do it in app. Sure go for it.
Also indeed we have an OAuth2 server if you want to authenticate your users against the Nextcloud server.
