### ISSUE TITLE
15.0.0 RC 3: /settings/users : "automatic selection" and avatars are not displayed correctly

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#12911]
### Steps to reproduce
1. login as admin, open "Users"
2. You see the list of all users and avatars are displayed 
3. Click (once no double click) in the main window in the "free" part below the list 
4. Click in the left sidebar "Admins" -> avatars are displayed not correctly and all is marked
5. Click in the left sidebar "Users" -> avatars are displayed not correctly and all is marked

Screenshot (Step 2):

![20181207_1](https://user-images.githubusercontent.com/34692335/49647657-895a5c80-fa23-11e8-8e5f-3dcfd9f863cc.png)

Screenshot (Step 4):
![20181207_2](https://user-images.githubusercontent.com/34692335/49647676-98410f00-fa23-11e8-96b5-54e65b0965de.png)

Screenshot (Step 5):
![20181207_3](https://user-images.githubusercontent.com/34692335/49647877-3503ac80-fa24-11e8-8359-dc07bf607e89.png)

### Expected behaviour
Like in NC 14: avatars are displayed correctly

### Actual behaviour
See steps 4 & 5

**Nextcloud version:**
Nextcloud 15.0.0 RC 3

Updated from an older Nextcloud/ownCloud or fresh install:
deleted old folder /var/www/nextcloud
drop old database from nextcloud
then installation with
nextcloud-15.0.0RC3.tar.bz2

** OS**
Ubuntu
**Browser**
Firefox 63.0.3

**Comment by xf-** [comment]
- Avatars are fine (no image, text based and selected). 
- If you click in infinity loading container everything is selected

**Comment by MorrisJobke** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
I really don't understand what is the issue here, the selection ?

**Comment by xf-** [comment]
you click under the list (infinity container) and everything is selected above until the next reload.
