### ISSUE TITLE
sharing .txt (text) files client-side truncation is not obvious

### ISSUE THREAD

**Issue by fermulator** [nextcloud/server#12924]
### Steps to reproduce
1. In any local or external storage, create a text file.
2. Fill the text file to exceed ~30x lines
3. Share the file for public viewing (+password of course)
4. Visit the link through the share

### Expected behaviour
 1. On one hand, I would prefer no truncation at all in the file preview, however I suspect this is by design to avoid accidentally loading huge files.
 2. Possibly we could make the "file previous line count" configurable on server side.
 3. Definitely we need to make it more obvious client-side that the file has been truncated.
 4. Possibly add a "..." button to "load more" (+XX lines at a time)
 5. Possibly add a "previous full file" button

### Actual behaviour

The filename, "shared by User", and content show up! -- however -- the content is TRUNCATED to (30?) lines, and it is not intuitive to the client that the file has been truncated.

There _is_ thankfully a "Download <filename> <size>" button, in order to get the full file contents.

Its very easy for users unfamiliar or non-technical to completely miss the fact that there is missing content.

### Server configuration

**Operating system**: `Ubuntu 16.04 LTS`
**Web server:** `Apache2?`
**Database:** `mysql 14.0.X`
**PHP version:** `7.0.32-0ubuntu0.16.04.1`
**Nextcloud version:**  `Nextcloud 14.0.3`
**Updated from an older Nextcloud/ownCloud or fresh install:** `Upgraded a few times so far`

**Nextcloud configuration:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "SNIPPED"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "SNIP",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/cloud",
        "overwritecondaddr": "^1\\.0\\.0\\.52$",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "https:\/\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable"
    }
}
```

**Are you using external storage, if yes which one:** local/smb/sftp/... `yes but N/A`
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... `no`

### Client configuration
**Browser:** tested both Chromium and Firefox
**Operating system:** Linux Ubuntu 18.04

**Comment by fermulator** [comment]
(feels similar to #7907, but that issue was tagged as "stale" so was not 100% certain, thusly submitted separate ticket)

**Comment by skjnldsv** [comment]
Closing in favour of #7907
