### ISSUE TITLE
nextcloud issue template `occ config:list system` fails to remove all domain sensitive data

### ISSUE THREAD

**Issue by fermulator** [nextcloud/server#12925]
### Steps to reproduce
Per the template (this exact one), later in the template it directs the user to run `sudo -u www-data php occ config:list system`, this is awesome to wipe sensitive data, and things are replaced with "***REMOVED SENSITIVE VALUE***".

### Expected behaviour
config dumper SHOULD also remove DOMAIN/HOST sensitive data.
i.e. in reverse proxy configurations

specifically, I think we're talking about:

1. entries in `trusted_domains`
2. entry for `overwritehost` 

### Actual behaviour
Ran this:
```
root@nextcloud:/srv/nextcloud# sudo -u www-data php occ config:list system
```
, and the output was this:
(!) NOTE: I snipped my domain MANUALLY and replaced it with: "mydomain.snipped.for.reasons.but.was.not.snipped.by.tool"
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud",
            "mydomain.snipped.for.reasons.but.was.not.snipped.by.tool"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "mydomain.snipped.for.reasons.but.was.not.snipped.by.tool",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/cloud",
        "overwritecondaddr": "^1\\.0\\.0\\.52$",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.3.0",
        "overwrite.cli.url": "https:\/\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable"
    }
}
```

### Server configuration

**Operating system**: `Ubuntu 16.04 LTS`
**Web server:** `Apache2?`
**Database:** `mysql 14.0.X`
**PHP version:** `7.0.32-0ubuntu0.16.04.1`
**Nextcloud version:**  `Nextcloud 14.0.3`
**Updated from an older Nextcloud/ownCloud or fresh install:** `Upgraded a few times so far`

**Comment by caugner** [comment]
@nickvergessen In #12944 [you argued](https://github.com/nextcloud/server/pull/12944#issuecomment-445564888):

> I still disagree on the cli url, its the point of trouble for a lot of issues

Would it be a feasible compromise to **anonymize** only the domain parts in the `overwritehost`, `trusted_domains` and `overwrite.cli.url` values, e.g.:

```js
{
    "system": {
        // ...
        "trusted_domains": [
            "removedA",
            "removedB.removedC.removedD"
        ],
        // ...
        "overwritehost": "removedB.removedC.removedD",
        // ...
        "overwrite.cli.url": "https:\/\/removedA",
        // ...
    }
}
```


PS: I stumbled across this issue, because I recently leaked my private instance's host myself by posting my system config and would have preferred not to.

**Comment by szaimen** [comment]
Please see https://github.com/nextcloud/issuetemplate/issues/27
