### ISSUE TITLE
How to docker-compose

### ISSUE THREAD

**Issue by Rillian-Grant** [nextcloud/server#12922]
I run a nextcloud and mariadb container linked together with /var/www/html and /var/www/data of the nextcloud container in volumes.

### Expected behaviour
Recreating the containers doesn't change anything.

### Actual behaviour
When I recreate the containers the initial setup page appears and won't except my username and password saying that the account is already created.

### Server configuration

**Operating system** Docker

**Nextcloud version:  Docker latest**

**Fresh install: Docker**

**Where did you install Nextcloud from: Docker**

**Comment by danielkesselberg** [comment]
Hey @Rillian-Grant,

this sounds like a setup issue to me? Could you ask the community https://help.nextcloud.com/ for help? If you think this is a software issue than please report it https://github.com/nextcloud/docker :+1:

**Comment by Rillian-Grant** [comment]
The problem may have been that I was using :latest docker images and when it worked I was using :13 and :14
