### ISSUE TITLE
core/vendor/.gitignore ignores too much

### ISSUE THREAD

**Issue by tverho** [nextcloud/server#1293]
core/vendor/.gitignore has these lines:

jquery/**
!jquery/dist/jquery.*

the second line has no effect because the parent directory of dist is ignored (see the man page for .gitignore). The same thing with

clipboard/**
!clipboard/dist/clipboard.js

Also the lines

.gitignore
davclient.js/**

cause files to be ignored

### Steps to reproduce
1. git clone https://github.com/nextcloud/server
2. cd nextcloud
3. git rm -r --cached core/vendor
4. git add core/vendor
5. git status --ignored

### Expected behaviour
All files should get added back to the index

### Actual behaviour
the output shows:

```

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    core/vendor/.gitignore
        deleted:    core/vendor/clipboard/dist/clipboard.js
        deleted:    core/vendor/davclient.js/lib/client.js
        deleted:    core/vendor/jquery/dist/jquery.js
        deleted:    core/vendor/jquery/dist/jquery.min.js
        deleted:    core/vendor/jquery/dist/jquery.min.map

Ignored files:
  (use "git add -f <file>..." to include in what will be committed)

        core/vendor/.gitignore
        core/vendor/clipboard/
        core/vendor/davclient.js/lib/
        core/vendor/jquery/dist/
```

If you copy the nextcloud installation package to a fresh git repository, those files will stay out of the index and nextcloud won't work.

**Comment by tverho** [comment]
The fix is simple:
```

diff --git a/core/vendor/.gitignore b/core/vendor/.gitignore
index 5160c2a..7985e73 100644
--- a/core/vendor/.gitignore
+++ b/core/vendor/.gitignore
@@ -1,7 +1,6 @@
 test/
 src/
 bower.json
-.gitignore
 .jshintrc
 .travis.yml
 CHANGELOG*
@@ -36,6 +35,7 @@ moment/templates
 # jquery
 jquery/**
 !jquery/.bower.json
+!jquery/dist
 !jquery/dist/jquery.*
 !jquery/MIT-LICENSE.txt
 
@@ -126,6 +126,8 @@ backbone/backbone-min*
 # davclient.js
 davclient.js/**
 !davclient.js/lib
+!davclient.js/lib/client.js
+!davclient.js/lib
 !davclient.js/LICENSE
 
 # es6-promise
@@ -140,4 +142,5 @@ base64/*min.js
 
 # clipboard
 clipboard/**
+!clipboard/dist
 !clipboard/dist/clipboard.js
```

**Comment by rullzer** [comment]
Thanks for noticing!
Could you submit a PR?

**Comment by tverho** [comment]
Here you go https://github.com/nextcloud/server/pull/1296
