### ISSUE TITLE
app:check-code Element 'types' is not expected

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#12942]
Hello Masters,

In info.xml I am using 
```
	<types>
   		<filesystem/>
 	</types>
```
According the the help forum, this is required to get filehooks working since NC14
`Util::connectHook('OC_Filesystem', 'delete', '\OCA\audioplayer\Hooks\FileHooks', 'deleteTrack');`

but app-checker complains about it:

> Invalid appinfo.xml file found: Element 'types': This element is not expected. Expected is one of ( background-jobs, repair-steps, two-factor-providers, commands, settings, activity, dashboard, fulltextsearch, navigations, contactsmenu ).

was the requirement for the types config removed? or is it still required?

**Comment by matiasdelellis** [comment]
Hi,
We are working on another application, and for trying to do things right, eliminate this node of info.xml, and our code stopped working.. We went crazy doing tests, and now discovered this ..  :disappointed: 

Thanks @Rello 

Please, not only that the report fails, it is not documented anywhere either..

**Comment by skjnldsv** [comment]
cc @rullzer @MorrisJobke @nickvergessen @blizzz :)

**Comment by blizzz** [comment]
The order of the elements in the info.xml is not arbitrary but defined in the XML schema. The `types` for instances has to follow the `namespace` tag. Please see https://apps.nextcloud.com/schema/apps/info.xsd
