### ISSUE TITLE
Folder download as ZIP shouldn't start immediately

### ISSUE THREAD

**Issue by ryan77627** [nextcloud/server#12957]
**Is your feature request related to a problem? Please describe.**
In Google Drive when downloading a folder, it says in the bottom left "Zipping..." then once done zipping it starts the download. In nextcloud when I choose to download a folder, a zip file download is started immediately, however the download is stuck at 0bytes/sec until done zipping, where it updates to 4MB/sec. This caused my users and myself to believe the download has stalled until we were patient enough to not cancel the download.

**Describe the solution you'd like**
Nextcloud should present to the user somehow that the folder is zipping before the download starts so when the download is presented to the user and they choose save, it starts downloading immediately instead of sitting at 0bytes/sec

**Describe alternatives you've considered**
Telling people directly to just wait, even though it looks stalled.

Demo download (Zip file has one file filled with random data for example. Choose download button at top right): https://hub.stoicproductions.org/s/downloadme

**Comment by skjnldsv** [comment]
Our zips are bundled and created on-the-fly. Google is creating the zip on the server side and then sending it for download.
Two different tech, I'm not sure we really gain anything aside fom having the full zip final size. :thinking: 

Though leaving this opened as people might want to take a dive on it one day! :woman_shrugging:

**Comment by ryan77627** [comment]
I'm not entirely sure I know what you mean by on the fly (nextcloud) vs. zipped on the server side (in googles case). Do you mean that Google zips the download package then proceeds to send the download when done zipping and nextcloud simply sends the zip archive as its created?

Another benefit other than full file size is the download not stalling. At least when I download a zip from my server it stalls for a bit while (I presume!) it is creating more of the archive to send. Unless that's a bug/issue I have to fix on my server.

I've been playing around with the nextcloud demos and find that zip downloads start immediately, so perhaps my server is just too underpowered to do zipping on the fly ;) (At least if that's what's happening if I understand correctly)

Thanks!

**Comment by siccovansas** [comment]
I actually prefer Nextcloud's method. I guess @ryan77627's server is underpowered. Zip downloads start immediately on my server (even large zips of dozens of GB). Meanwhile Google takes 30+ minutes to zip 70GB of files (they also split them in 2GB files resulting in 35 download pop-ups and much more effort for non technical users to extract them all and put all folders back together).

**Comment by ryan77627** [comment]
To be honest, it probably was. Lots has changed in my setup between then and now, and it was either an underpowered server or (more likely) a configuration error, but zip files do download right away now.

I have a feeling it was a configuration error because I noticed later on that video files would either download real slow or stall at the beginning as well. I've been messing around with different settings for the past while and got everything to work quickly and reliably now. I totally forgot I had this open, thanks for the help!
