### ISSUE TITLE
Ios11 iPhone 8p APP Recycle Bin Can't See File Android App Normal

### ISSUE THREAD

**Issue by 330201818** [nextcloud/server#12958]
Ios11 iPhone 8p APP Recycle Bin Can't See File Android App Normal

**Comment by MorrisJobke** [comment]
Closing due to missing information what is broken and how to reproduce - most likely this should also go to https://github.com/nextcloud/ios

**Comment by MorrisJobke** [comment]
ref nextcloud/ios#762
