### ISSUE TITLE
Search: which infos should be shown

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#12964]
From https://github.com/nextcloud/android/issues/3331 we should discuss this for all clients.

Android / web ui
![2018-12-10-113827](https://user-images.githubusercontent.com/5836855/49727289-20b3ef80-fc70-11e8-85f6-d2af84a41206.png) ![image](https://user-images.githubusercontent.com/5836855/49727404-7a1c1e80-fc70-11e8-8f33-9b3411fadf53.png) ![image](https://user-images.githubusercontent.com/5836855/49728018-ed726000-fc71-11e8-85f8-bf5175b577af.png)

Android / ios
 - size
 - date
 - no path

web ui
 - no size
 - no date
 - path

I think that on mobile client also the size should be shown as it matters if you download 5mb or 50mb.
Date should also be shown always as for similar named files it is a good indicator.

--> show all 3 params on all platforms?

@nextcloud/designers 
@marinofaggiana

**Comment by skjnldsv** [comment]
Be careful about [this screenshot](https://user-images.githubusercontent.com/5836855/49727404-7a1c1e80-fc70-11e8-8f33-9b3411fadf53.png) because this is not the proper search. This is the results from the global search.
See #9917

**Comment by tobiasKaminsky** [comment]
Hm, it is the only thing I have ;-)
What would change if we have a file "only" search?

**Comment by skjnldsv** [comment]
No idea, we have to discuss what kind of output we want when searching files.
Only the current folder (all my files browsers do that), full recursive search (windows?)
Put the unified search in the header like #9917 says? And then what do we do on mobiles, recursive? just the view?

I have no idea, I did not thought about this yet :)

**Comment by tobiasKaminsky** [comment]
So currently it is a filtering of current folder + with a bit of delay a sever wide search.
I think this is also what we should do on mobile. In most of the times you are already in the correct folder, but you are too lazy to manually find the correct file.

My idea:
- filtering in current folder
- with a bit of delay a server wide file search with
	- file name
	- file size
	- modification date
	- location / remote path

**Comment by marinofaggiana** [comment]
yes, I am agree, the search view should be revisited

**Comment by skjnldsv** [comment]
Closing?

**Comment by tobiasKaminsky** [comment]
Yes, we get all info now via unified search and UI should follow server.
