### ISSUE TITLE
Outlook/OWA import fails due to empty SCHEDULE-AGENT=CLIENT attribute

### ISSUE THREAD

**Issue by faulix** [nextcloud/server#12962]
### Steps to reproduce
Details unknown, but create an calendar invite with an attendee, who has an empty "SCHEDULE-AGENT=CLIENT"

### Expected behaviour
Import is possible in Outlook/OWA

### Actual behaviour
Import error (Content conversion failed)

### Technical information
Nextcloud: 14.0.4
Calendar: 1.6.4
PHP: 7.2

### Reason
Outlook/OWA always needs a value for the attribute "SCHEDULE-AGENT=CLIENT", which makes sense as it is not possible to invite someone without a mail or anything

### Solution
Only create an attendee object if there is a value for "SCHEDULE-AGENT=CLIENT"

**Comment by faulix** [comment]
@georgehrke my bad, I edited the issue, hope this is enough

**Comment by georgehrke** [comment]
Neither the Nextcloud calendar not the Sabre/DAV is every setting `SCHEDULE-AGENT=CLIENT` on an attendee.

This must be related to other client software that you are using.
