### ISSUE TITLE
fresh installation: no files in browser after 1st login

### ISSUE THREAD

**Issue by oz42** [nextcloud/server#12968]
### Steps to reproduce
1. login
2. wait
3. wait
[...]

### Expected behaviour
show these files to admin user:
Documents/
Nextcloud Community.jpeg
Nextcloud Manual.pdf
Nextcloud.mp4
Nextcloud.png
Photos/

### Actual behaviour
spinning circle in browser

### Server configuration

**Operating system**: FreeBSD 11.2-RELEASE-p6

**Web server:** apache24-2.4.37

**Database:** mariadb103-server-10.3.11

**PHP version:** php72-7.2.13

**Nextcloud version:** (see Nextcloud admin page) 14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** FreeBSD ports

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
no errors

**List of activated apps:**
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap

**Nextcloud configuration:**
    "system": {
        "apps_paths": [
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
                "url": "\/apps-pkg",
                "writable": false
            }
        ],
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "daisy.tuxfriends.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "overwrite.cli.url": "https:\/\/daisy.tuxfriends.net\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** any

**Operating system:** any

#### Web server error log
no errors, only debug messages

#### Nextcloud log (data/nextcloud.log)
does not exist

#### Browser log
each @ core.js?v=1eab1b95-0:2
trigger @ core.js?v=1eab1b95-0:3
_onPopState @ merged-index.js?v=1eab1b95-0:299
initialize @ merged-index.js?v=1eab1b95-0:128
(anonymous) @ merged-index.js?v=1eab1b95-0:340
(anonymous) @ core.js?v=1eab1b95-0:781
client.js?v=1eab1b95-0:429 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagNameNS' of null
    at Client._getSabreException (client.js?v=1eab1b95-0:429)
    at client.js?v=1eab1b95-0:493

**Comment by oz42** [comment]
/index.php/apps/files/?dir=/&view=recent works just fine

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
