### ISSUE TITLE
Check update for php versions of apps

### ISSUE THREAD

**Issue by xf-** [nextcloud/server#12966]
**Is your feature request related to a problem? Please describe.**
You integrated the nice check for nextcloud version, and not for PHP. My distribution ships 7.3 default and https://github.com/nextcloud/twofactor_u2f is on 7.2 in release (7.3 repo) and disabled in update process without warning.

**Describe the solution you'd like**
Add same test/hint for PHP.

**Comment by nickvergessen** [comment]
The app supports 7.0 to 7.3, so it should work? 

cc @ChristophWurst

**Comment by ChristophWurst** [comment]
I think this is because we don't actually check the local copy of the app but use the info from the app store.

**Comment by xf-** [comment]
@nickvergessen at the release the support was 7.2 and v15. Nextcloud should check PHP-version before update like the nextcloud version and set it on list incompatible.

**Current behavior is**
1. Nextcloud tests for nextcloud version
2. Update starts
3. Nextcloud tests for php and nextcloud compatibility and disables apps.

**Better behavior**
Same tests in pre-update and update for compability

**Comment by skjnldsv** [comment]
Still relevant @ChristophWurst ?

**Comment by xf-** [comment]
@skjnldsv i think so. Nextcloud should check php-version before updating and disable plugins. Same way as nextcloud version is checked for compatibility and warned.

**Comment by skjnldsv** [comment]
@ChristophWurst

**Comment by ChristophWurst** [comment]
yes

**Comment by szaimen** [comment]
I think this was implemented in the meantime -> closing.
Please reopen if I am wrong.
