### ISSUE TITLE
Make '+' menu more generic

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#12965]
It is possible to register a new item for the '+' menu:

````
var NewFileMenuPlugin  = {

	attach: function(menu) {
		var fileList = menu.fileList;

		// only attach to main file list, public view is not supported yet
		if (fileList.id !== 'files') {
			return;
		}

		// register the new menu entry
		menu.addMenuEntry({
			id: 'NewCustomAction',
			displayName: t('protectr', 'Custom new file'),
			iconClass: 'icon-filetype-text',
			fileType: 'file',
			actionHandler: function() {
				// first create the file
				console.log('hello');
			}
		});
	}
};


OC.Plugins.register('OCA.Files.NewFileMenu', NewFileMenuPlugin);
````

But at the moment we always ask for a input field if you click on the new item:

![image](https://user-images.githubusercontent.com/1589737/49728690-b8ffa380-fc73-11e8-883e-c996ef846fba.png)

For some 3rdparty integration we need a way to trigger the action handler directly, without the input field. One idea would be to add another property "actionType" and depending on the action type we ask for a file name or trigger the action handler directly.

cc @nextcloud/javascript

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
