### ISSUE TITLE
Allow to manipulate the rendering of a '...' menu entry

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#12967]
If I use the API to create a new action item for the file listing I can use the render method do render the icon differently depending on some additional conditions, as show in this example: https://github.com/nextcloud/server/blob/master/apps/comments/js/filesplugin.js#L80

Would be nice if this render method would be also exists for the type `OCA.Files.FileActions.TYPE_DROPDOWN` so that I can for example manipulate the text depending on a file is encrypted or not or hide the action completely if some conditions are met

cc @nextcloud/javascript

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by skjnldsv** [comment]
Done with 28
