### ISSUE TITLE
Groupname with special chars (number sign/hash)

### ISSUE THREAD

**Issue by thorge** [nextcloud/server#12975]
### Steps to reproduce
1. Add user or group with groupname having special chars in it. I tested with a groupname, that's also a hashtag  -> #test
2. When you open the group overview, it won't show any members. Instead it shows error message "
Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden." (I'm using the German version)
3. When trying to delete the group, the same error message appears and the deletion is aborted.

### Expected behaviour
2. Group overview -> List groupmembers
3. Delete group -> Group is deleted

### Actual behaviour
Only showing error messages.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.1

**Nextcloud version:** 14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** website

**Signing status:**
No errors have been found.

**Comment by skjnldsv** [comment]
@gary-kim fixed with your pr, right?

**Comment by gary-kim** [comment]
> @gary-kim fixed with your pr, right?

Yes, this can be closed now.
