### ISSUE TITLE
DB port ignored on mysql

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#12979]
### Steps to reproduce
1. Set up instance with mysql db
2. Change `dbport` in config.php

### Expected behaviour
Nextcloud connects to configured port.

### Actual behaviour
Nextcloud connects to default port.

During setup, the port can be appended to the hostname. When I do so (to an invalid port) I get an expected error. After the setup, however, `dbport` has no effect.

### Server configuration

**Operating system**:
Docker

**Database:**
mysql (mariadb 10.1 Docker)

**Nextcloud version:**
14.0.4 and master

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Docker and git checkout

cc @nickvergessen @rullzer

**Comment by BernieO** [comment]
I am confused: according to the documentation, there is no parameter `dbport` in config.php. Instead it is stated that the port should be specified within parameter `dbhost`:

> 'dbhost' => '',
> Your host server name, for example `localhost`, `hostname`, `hostname.example.com`, or the IP address. To specify a port use `hostname:####`; to specify a Unix socket use `localhost:/path/to/socket`.

Taken from here:
https://docs.nextcloud.com/server/15/admin_manual/configuration_server/config_sample_php_parameters.html#default-parameters

Is the configuration parameter `dbport` missing in the documentation?

**Comment by ChristophWurst** [comment]
You're right. The `dbport` parameter does not exist. For some reason it did on my local setup, possibly copied from an older version.

However, the db port does still not work. I set it to a random number and my Nextcloud will still connect to the default port. Can you confirm that?

**Comment by ChristophWurst** [comment]
Oh :see_no_evil: 

You're right, I hadn't considered the socket connection for a local database. Of course it was using that.

This means Nextcloud actually works as expected and does respect the port when it's specified correctly. I'm closing this ticket now.
