### ISSUE TITLE
occ db:convert-filecache-bigint not possible in automatic instances

### ISSUE THREAD

**Issue by gcommit** [nextcloud/server#12976]
### What is going wrong?
Since i implemented NC 15.0.0 in my Dockerfile. it shows the following message:

> Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.
> filecache.mtime
> filecache.storage_mtime

It can be converted by:
`sudo -u www-data php occ db:convert-filecache-bigint`

BUT you have to accept this manually. So for automatism it is NOT usable. And my instances are created automatically. 

### To Reproduce
1. Start NC 15.0.0
2. Try to convert the database data to bigint automatically

### Expected behavior
A automatic conversion would be the expected behavior. 

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** 10.0.37+maria-1~xenial

**PHP version:** v7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 15.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install AND upgrade vom NC 14.0.4

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

Could you please enable that? Otherwise NC 15.0.0 is not usable for me ... :(

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/17b2827bbf20691dc59721a9c61a225c5fb4e0de/core/Command/Db/ConvertFilecacheBigInt.php#L103-L110

Above is the check if command is executed in an interactive shell. If this does not work you could try `--no-interaction`.

**Comment by gcommit** [comment]
thank you so much. This worked just fine :3

**Comment by Tom-2019** [comment]
I there a way to run this script if you do not have root access like on Strato?
