### ISSUE TITLE
Request: User can request permissions/access on Folder

### ISSUE THREAD

**Issue by David100mark** [nextcloud/server#12983]
It would be handy if a user can request the access on a folder. The request should pop-up on the admin account ( or group-admin account. Equally it should be possible to request permissions on a folder.

**Comment by skjnldsv** [comment]
@David100mark But how the user would know that there is a folder, since there is no access to it? :thinking: :)

**Comment by levonti** [comment]
> @David100mark But how the user would know that there is a folder, since there is no access to it? 🤔 :)

User can get the link in the documentation or from other users in various ways (email,messengers,service desk ticket)

**Comment by skjnldsv** [comment]
I'm not convinced about this :)
If you receive a link into a channel you have access to, then either the one who pasted the link should have shared it with you, either it's a mistake and therefore you should not know anything about this folder.

I would say thi sis not on our roadmap.
@nickvergessen @rullzer ?

**Comment by nickvergessen** [comment]
No this is not on the roadmap also it's undermining security for an uncovered usecase.

**Comment by levonti** [comment]
> No this is not on the roadmap also it's undermining security for an uncovered usecase.
Hmm, how it is undermining security?
This feature works great for example in Atlassian Confluence (https://confluence.atlassian.com/doc/page-restrictions-139414.html)
This is a very useful feature for corporate users.
