### ISSUE TITLE
Allow access to text files raw contents using some kind of preview system?

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/server#12986]
This is a follow up from this feature request: https://github.com/nextcloud/server/issues/2523

The specific scope of that feature request was covered by this merge:  https://github.com/nextcloud/server/pull/6599

While the image issue has been fixed there are other similar uses cases that are not covered by that solution. 

In my instance, I have a styles.css file that I inject into my version of VScode in order to further customize it in ways not supported by their default theming system. I have a setting in settings.json that links to a url where the raw CSS file can be found. It is current stored in a github gist. So I get a url like this gist.github.com/djfklajdklfjdsklaf/raw/styles.css 

I could hypothetically run a bash command using this functionality like this:  `gist.github.com/dsafldjsafdasf/raw/bash-commands.sh | bash`

I think there are some use cases where a raw or whatever type public link creation would be super useful. I read in the original thread there's also some security concerns, but also brought up in that thread are how other services like dropbox etc are able to get around this type stuff. I don't presume to know all the security implications of various solutions but I will say that having this functionality would be useful and I can think of a lot of different things people might want it for!

**Comment by skjnldsv** [comment]
You could already do it if you create a public link and append the /download at the end. You should be able to use it in bash directly `curl -sSL https://domain.com/s/STnC7pn5y9NZgCN/download | bash` :)

**Comment by jcklpe** [comment]
@skjnldsv Cool, thanks. I'll keep this in mind and try this next time I need this use case.
