### ISSUE TITLE
German translation for bigint conversion has a bug

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#12987]
The text shown to admins says:
```occ db: convert-filecache-bigint```

it should be
```occ db:convert-filecache-bigint```

**Comment by JSoko** [comment]
corrected:
https://www.transifex.com/nextcloud/nextcloud/translate/#de/$/159955391?q=text%3Aconvert-filecache-bigint
https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/159955391?q=text%3Aconvert-filecache-bigint
