### ISSUE TITLE
Increase, improve and adjust legibility

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#13008]
Since more and more people using Nextcloud the number of people with impaired vision are increasing as well at the same rate! The text in the admin section is almost non visible for people with impaired vision. When hovering text, it could be read a little bit better.

It would be most advantageous, if each user could change the level of contrast of text to background individually. Not everybody is familiar with twiddling options in CSS sheets ! A simple slider  + and - contrast would be fine to achieve a better legibility easily!

regards, hitam4450

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@hitam4450 are you aware of the Accessibility settings which are there since Nextcloud 14? They include an option for "High contrast" and that aims to satisfy the Web Content Accessibility Guidelines level AAA. :)

![](https://nextcloud.com/media/2018-08-15-Accessibility-Settings.png)

**Comment by skjnldsv** [comment]
Hello @hitam4450, any news?

**Comment by jancborchardt** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please feel free to reopen.
