### ISSUE TITLE
 Nextcloud 15.0.0 does not display password database before installation

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#13002]
In the installation phase when I have to enter the database password it shows me the dots correctly but when I click on the eye icon to display the password just entered,
to my surprise I noticed that the password is not shown in the clear, but always and only the dots.
I refer to the database password field.
this in the first phase of configuration, a bug that does not allow me to know if I entered the password correctly

**Comment by skjnldsv** [comment]
![Capture d’écran_2019-04-30_10-57-36](https://user-images.githubusercontent.com/14975046/56950893-c809c400-6b36-11e9-8d9c-f208891d680e.png)

Fixed since a few minor versions
