### ISSUE TITLE
User list unwanted selection

### ISSUE THREAD

**Issue by xf-** [nextcloud/server#13006]
Original issue report, but closed by reporter #12911

### Steps to reproduce
1. go to issue list
2. click on area under issue list (infinity container)
3. switch group and all rows are selected

### Expected behaviour
No selection on random click (has default cursor)

### Actual behaviour
Selects all entries

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

### Client configuration
**Browser:**
Firefox 65 (happens also in older version see #12911 )

**Operating system:**
Arch Linux

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
