### ISSUE TITLE
Segmentation fault on installation

### ISSUE THREAD

**Issue by Marcool04** [nextcloud/server#13012]
### Steps to reproduce
1. Perform pre-install setup (database, etc.)
2. Run installation : `pacman -S nextcloud`

### Expected behaviour
Installation should complete.

### Actual behaviour
Segmentation fault is thrown:
````
(1/1) installing nextcloud                                                                    [###################################################[203/8235]
warning: directory permissions differ on /etc/webapps/nextcloud/config/
filesystem: 750  package: 755
Optional dependencies for nextcloud
    php-apache: to use the Apache web server
    php-sqlite: to use the SQLite database backend [installed]
    php-pgsql: to use the PostgreSQL database backend
    php-ldap: LDAP authentication [installed]
    php-intl [installed]
    php-apcu [installed]
    mariadb: to use the MySQL database backend [installed]
    smbclient: to mount SAMBA shares
    php-mcrypt
    ffmpeg: file preview
    libreoffice: file preview
:: Running post-transaction hooks...
(1/3) Updating Nextcloud installation
Segmentation fault (core dumped)
error: command failed to execute correctly
(1/3) Updating Nextcloud installation
Segmentation fault (core dumped)
error: command failed to execute correctly
(2/3) Arming ConditionNeedsUpdate...
````

### Server configuration

**Operating system**:
Archlinuxarm on Raspberry Pi B3+
````
uname -a
Linux [HOST] 4.14.86-1-ARCH #1 SMP Fri Dec 7 01:48:56 UTC 2018 armv7l GNU/Linux
````

**Web server:**
````
pacman -Qi apache
Name            : apache
Version         : 2.4.37-1
````
**Database:**
````
pacman -Qi mariadb
Name            : mariadb
Version         : 10.1.37-1
````

**PHP version:**
````
pacman -Qi php
Name            : php
Version         : 7.3.0-1
````

**Nextcloud version:** (see Nextcloud admin page)
````
pacman -Qi nextcloud
Name            : nextcloud
Version         : 15.0.0-1
````

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh installation

**Where did you install Nextcloud from:**
Arch linux package manager pacman which pulls source from:
https://download.nextcloud.com/server/releases/nextcloud-${pkgver}.tar.bz2

**Signing status:**
Unavailable…

**List of activated apps:**
Unavailable

**Nextcloud configuration:**
```
sudo -u http php occ config:list system
Segmentation fault
```
config.php is still empty

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Encrypted hard drive… luks

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Any
**Operating system:**
Any

### Logs
I have a stack trace produced by running:
````
sudo -u http php -d xdebug.auto_trace=ON -d xdebug.trace_output_dir=/tmp/php-trace/ occ maintenance:install --database "mysql" --database-name "nextcloud"  --database-user "nextcloud" --database-pass "[PASS]" --admin-user "mark" --admin-pass "[OTHERPASS]"
````
pasted here: https://framabin.org/p/?cec8a37b411a9c38#wVJ2g3a8CW/karjn1jm6EVqAyXjMhjUucenZGMsA0mY=

Let me know if any more help can be provided for debugging.
Thanks for all the great work on Nextcloud!
Regards,
Mark.

**Comment by ChristophWurst** [comment]
IMO this is a bug in php or similar but not nextcloud itself. This should be reported in the Arch but tracker.

**Comment by Marcool04** [comment]
Indeed, sorry to have wasted your time here. I have also noticed that phpmyadmin produces a similar segfault, the problem is likely with one of php's modules, some of which might not by compatible with the new 7.3 version of php… I need to debug further but Nextcloud is obviously not at fault here.
Thanks for your time.
Regards,
Mark.

**Comment by ChristophWurst** [comment]
Check if you have xdebug enabled. AFAIK php7.3 with xdebug enabled segault's occasionally.

**Comment by Marcool04** [comment]
Wow that was it indeed! You are a wizard :) Thanks a bunch for the tip!
