### ISSUE TITLE
403 error when accessing /.well-known/caldav and /.well-known/carddav

### ISSUE THREAD

**Issue by haziegler** [nextcloud/server#13013]
### Steps to reproduce
1. Install NC 15.0.0 in a subdirectory of the DocumentRoot, such as /nc
2. Update the config for service discovery in .htaccess according to https://docs.nextcloud.com/server/15/admin_manual/issues/general_troubleshooting.html#service-discovery . This is the part from my .htaccess:
~~~~
RewriteRule ^\.well-known/host-meta /nc/public.php?service=host-meta [QSA,L]
RewriteRule ^\.well-known/host-meta\.json /nc/public.php?service=host-meta-json [QSA,L]
RewriteRule ^\.well-known/webfinger /nc/public.php?service=webfinger [QSA,L]
RewriteRule ^\.well-known/carddav /nc/remote.php/dav/ [R=301,L]
RewriteRule ^\.well-known/caldav /nc/remote.php/dav/ [R=301,L]
~~~~
3. Go to settings / overview

### Expected behaviour
If everything is configured in .htaccess as described in the documentation:
- the checks should not complain about incorrect "/.well-known/caldav" and "/.well-known/carddav" configuration
- the server should not return a 403 forbidden error

### Actual behaviour
- Ihr Webserver ist nicht richtig konfiguriert um "/.well-known/caldav" aufzulösen. Weitere Informationen hierzu finden Sie in der Dokumentation.
- Ihr Webserver ist nicht richtig konfiguriert um "/.well-known/carddav" aufzulösen. Weitere Informationen hierzu finden Sie in der Dokumentation.

If I look at the Apache log files, I can see that these checks return a 403 error:
~~~~
10.1.0.1 - - [11/Dec/2018:20:32:35 +0100] "PROPFIND /.well-known/carddav HTTP/1.1" 403 228 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
10.1.0.1 - - [11/Dec/2018:20:32:35 +0100] "PROPFIND /.well-known/caldav HTTP/1.1" 403 227 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:63.0) Gecko/20100101 Firefox/63.0"
~~~~
Also, if I use curl to access the URL, I see the 403 error:
~~~~
$ curl -iLu username:password https://example.com/.well-known/caldav
HTTP/1.1 403 Forbidden
Date: Tue, 11 Dec 2018 19:16:03 GMT
Server: Apache
Content-Length: 227
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /.well-known/caldav
on this server.<br />
</p>
</body></html>
~~~~

### Server configuration

**Operating system**: RHEL 7.6

**Web server:** httpd24-httpd-2.4.34-7.el7.x86_64

**PHP version:** rh-php71-1-1.el7.x86_64

**Nextcloud version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14.0.4

**Where did you install Nextcloud from:** Installed from https://download.nextcloud.com/server/releases/

**Comment by detrout** [comment]
I'm having a similar problem on Debian stable. I tried enabling the social app, and following the instructions to enable the .well-known addresses. They didn't work so I tried directly accessing the public.php?service=host-info or webfinger urls.

That returns an empty page. Not knowing much about php I stuck print statements around the public.php file, and it looks like ```$file```  is empty but it shouldn't be.

```$file = \OC::$server->getConfig()->getAppValue('core', 'public_' . strip_tags($service));```

$service has a value (equal to host-info or webfinger) depending on which I was trying.

My php version is below, I'm using apache 2.4.25-3+deb9u6, and this is with a Nextcloud 15.0.0 installation that had been upgraded from 14.0.4 by following the manual installation instructions. (As well as enabling strong permissions using the script I found back in the nextcloud 9 docs).


```
php --version
PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0+deb9u1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by LukeOwlclaw** [comment]
I had the same problem. It turned out that multiple things have to be set up correctly:

1. mod_rewrite needs to be enabled: ``sudo a2enmod rewrite``
2. RewriteRules need to be placed in `.htaccess` (done by default)
3. Rewriting needs to be enabled: ``AllowOverride All`` in ``apache.conf`` -- see https://www.keycdn.com/support/htaccess-not-working for details (and other potential problems).

The [documentation](https://docs.nextcloud.com/server/15/admin_manual/issues/general_troubleshooting.html#service-discovery) should mention these potential but often occuring issues.

**Comment by kesselb** [comment]
OK. Is there anything to fix? ;) Looks like a configuration issue. Sounds good to me to have some help at https://docs.nextcloud.com/server/latest/admin_manual/issues/general_troubleshooting.html. Could someone of you use "Edit on GitHub" to suggest those changes? Thanks :+1:

**Comment by rmarzocchi84** [comment]
I have a similar problem https://github.com/nextcloud/server/issues/18922
