### ISSUE TITLE
NC15 - Files of external user support (user_external) were not replaced correctly

### ISSUE THREAD

**Issue by JS1982** [nextcloud/server#13011]
Issue after updating to 15.0.0.0:

The files of the app External user support (user_external) were not replaced correctly. Make sure it is a version compatible with the server.

Had to run on command line:

occ app:disbale user_external

occ upgrade

Please fix, so app can be disabled during update and update is not stalling.

**Comment by violoncelloch** [comment]
duplicate of #12506
