### ISSUE TITLE
Nextcloud 14 Upgrade exception

### ISSUE THREAD

**Issue by sschuhmann** [nextcloud/server#13027]
**Operating system**:  Raspbian 9
**Web server:** Apache
**Database:** MySQL
**PHP version:** php-7
**Nextcloud version:** Upgrade to 14.04 
**Updated from an older Nextcloud/ownCloud or fresh install:** From old version

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken ADD private_key LONGTEXT DEFAULT NULL, ADD public_key LONGTEXT DEFAULT NULL, ADD version SMALLINT UNSIGNED DEFAULT 1 NOT NULL':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Update failed

**Comment by MorrisJobke** [comment]
Could you try this here https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

Then the issue should not occur again.
