### ISSUE TITLE
Enable TOTP upon Administrative Actions

### ISSUE THREAD

**Issue by ho1ger** [nextcloud/server#13025]
Currently, NC requires the admin to authenticate herself before certain administrative actions are actually executed. I guess this only applies in case the admin is logged in already a while...

I'd find it quite logical to add a function which additionally (or alternatively to the admin's password) requests a TOTP token.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer @ChristophWurst @karlitschek

**Comment by karlitschek** [comment]
good idea. Not sure how tricky it is

**Comment by j-ed** [comment]
I think this request is similar to the one I raised (https://github.com/nextcloud/server/issues/7288) a while ago, except that I had the idea to use a U2F key. It would be good to implement such a function with a maximum of flexibility and let an administrator decide what mechanism he wants to use for it.

**Comment by MorrisJobke** [comment]
Closing as duplicate of #7288
