### ISSUE TITLE
Nextcloud 15 cron.php: Uncaught error, Call to a member function getLogger()

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#13038]
This issue is related to https://github.com/nextcloud/server/issues/11298

I posted reply there, and @danielkesselberg asked me to submit a new issue for this. So here it goes...

### Steps to reproduce
1. Make fresh install of NC15
2. Run cron.php (or wait for it to be launched automatically)

### Expected behaviour
Cron should run without errors

### Actual behaviour
Cron is not executed and this entry is added to error_log file - Uncaught error, Call to a member function getLogger() on cron.php

### Server configuration

**CentOS 6.10 (kvm)**:
**Apache 2.4.37**
**MariaDB 10.2:**
**PHP 7.2:**
**Nextcloud 15.0:**
**Fresh install:**

I did NOT create config.php file manually (it was mentioned as possible cause in https://github.com/nextcloud/server/issues/11298) and it's a default installation (no modifications were made after installation).

I deleted my current installation of NC after struggling with this error for hours, so I couldn't do any more tests right now, but I will re-install NC15 again and update this ticket.

I also have NC14 (installed months ago) on the same server, and it works perfectly, so it's surely not server's problem.

P.S. I don't know if it's related or not, but I could not upload any file to NC15 using Android client. It connects perfectly, I was able to browser/create folders, but uploads failed with error "Maintenance mode enabled". I even manually added maintenance=>false to config.php, checks server status at mydomain.com/status.php (it reported maintenance: disabled), but no luck. Could successfully work with files via web-based interface, though.

**Comment by toxpal** [comment]
So I performed a new install. Deleted whole cPanel account, re-created it, re-uploaded files, and error_log file gets created again with endless errors:

PHP Fatal error:  Uncaught Error: Call to a member function getLogger() on null in /home/xxx/public_html/cron.php:160
Stack trace:
#0 {main}
  thrown in /home/xxx/public_html/cron.php on line 160

Did some more tests and it only happens when Cronjob option is set to "Cron". If option is set to "AJAX", it works. Since error_log file gets modified every 15 minutes, I know my PHP cronjob command is valid and the cause is NC itself.

**Comment by toxpal** [comment]
AJAX cron continues to work, but Logging module in NC displays these errors:

[core] Error: InvalidArgumentException: Invalid serialized command at <<closure>>

0. /home/xxx/public_html/lib/private/BackgroundJob/Job.php line 61
   run("O:33:\"OCA\\Fil ... }")
1. /home/xxx/public_html/lib/private/BackgroundJob/QueuedJob.php line 44
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
2. /home/xxx/public_html/cron.php line 146
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

GET /cron.php

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/71df6233cfc4c6a02f90a887d57471430fe38dd7/cron.php#L160

Could you insert above `var_dump($ex);`, try to execute the cron from cli again and share the result?

**Comment by toxpal** [comment]
It's a bit difficult to do so because NC aborts cronjob when it's running from CLI as another user, so if I run cronjob command right from the CLI (but I run it as another user), it just stops. So no var_dump results...

If I comment out this snippet in cron.php:

```
// the cron job must be executed with the right user
		/*if (!function_exists('posix_getuid')) {
			echo "The posix extensions are required - see http://php.net/manual/en/book.posix.php" . PHP_EOL;
			exit(1);
		}
		$user = posix_getpwuid(posix_getuid());
		$configUser = posix_getpwuid(fileowner(OC::$configDir . 'config.php'));
		if ($user['name'] !== $configUser['name']) {
			echo "Console has to be executed with the same user as the web server is operated" . PHP_EOL;
			echo "Current user: " . $user['name'] . PHP_EOL;
			echo "Web server user: " . $configUser['name'] . PHP_EOL;
			exit(1);
		}*/
```

and run cron.php from CLI again (still as another user), it completes without any errors and NC Settings window says cronjob was launched seconds ago. So it works.

But if cron.php is executed as a "real" cronjob (via Cronjobs section in cPanel account), it generates the same message in error_log file again. No matter if posix_getpwuid part in cron.php is commented out or not...

**Comment by toxpal** [comment]
Got it now... Here's the error:

Return value of OC\AppFramework\Http\Request::getScriptName() must be of the type string, null returned

**Comment by danielkesselberg** [comment]
@nextcloud/server-triage I'm not sure about this one.

**Comment by kesselb** [comment]
Do you still see this issue? I have no explanation why this method (getScriptName()) is called from the cli. Would you mind to share the config report?

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```



> Sounds like a weird setup to me but i dont know cpanel that well. could you try the code below instead of `var_dump($ex)`? I hope this should log something to webserver log and/or a new file called `logger_error.txt`.

Mind to try this again and use this version? Looks like the script name is empty which is weird because it should be "cron.php".

```
file_put_contents('logger_error.txt', $ex->getMessage(), FILE_APPEND);
file_put_contents('logger_error.txt', print_r($_SERVER, true), FILE_APPEND);
```

If you share the result please remove any sensitive information like domain names.

**Comment by toxpal** [comment]
Tested on 16.01 now. All types of cronjobs work well (no changes to server config), so bug seems to be fixed in recent releases.
