### ISSUE TITLE
App menu overlapping text in Nextcloud 15

### ISSUE THREAD

**Issue by maghog** [nextcloud/server#13047]
The app menu overwrite text when showing app names on hover.

Nextcloud 15.0.0

![nc15](https://user-images.githubusercontent.com/1148924/49928288-2a339680-fec0-11e8-8229-c1cb01ae66ea.png)

**Comment by violoncelloch** [comment]
Do you have any instructions on how to reproduce? on my instance it works fine. Does it depend on the language?

**Comment by maghog** [comment]
Yes in my case it's in Swedish where some strings are longer than in English.

**Comment by violoncelloCH** [comment]
reproduced with current master
cc @nextcloud/designers could someone take a look at this?

**Comment by maghog** [comment]
No the left side should look like this:
<img width="189" alt="nc2" src="https://user-images.githubusercontent.com/1148924/50134559-d266a800-0290-11e9-92cd-ba4c97859af2.png">

**Comment by MorrisJobke** [comment]
@skjnldsv @juliushaertl Didn't one of you a fix for this lately with background added to the highlighted item?

**Comment by skjnldsv** [comment]
@MorrisJobke yes in https://github.com/nextcloud/server/pull/12559/files

**Comment by MorrisJobke** [comment]
Why is it then happening here?

**Comment by skjnldsv** [comment]
z-index is wrong, we need a quick fix

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/13381
