### ISSUE TITLE
Nextcloud 15.0.0 - Theme var(--color-primary-text) not set

### ISSUE THREAD

**Issue by affeldt28** [nextcloud/server#13041]
The color --color-primary-text is not set when changing the color of the theme. 
It's noticeable at the login-page, in the footer the info text

**Comment by MorrisJobke** [comment]
cc @nextcloud/theming @skjnldsv Didn't you ran into this lately? Or is this fixed in the meantime?

**Comment by juliushaertl** [comment]
We don't have css variables available on the login page until now. For 15 this should been fixed in the next release with https://github.com/nextcloud/server/pull/14677
