### ISSUE TITLE
occ db:add-missing-indices - command not found

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#13045]
### Steps to reproduce
1. After upgrade to NC 15 i need to add two missing indices. The instruction tells me  "By running "occ db:add-missing-indices" those missing indexes could be added manually"
2. When I do that I get message "Command 'occ' not found, but there are 21 similar ones.". Running the command with sudo I get  "sudo: occ: command not found"
3. This worked sudo -u www-data php occ db:add-missing-indices
I think the instruction should be revised.

NC15 upgraded from NC14. Ubuntu 18.04. nginx

**Comment by baoang** [comment]
the entire script may look like this, supposing user=www, php cli installed in usr/local/php/bin/php, and ./occ is +x
`sudo -u www /usr/local/php/bin/php ./occ db:add-missing-indices`

For the first few times, I only throw out a bare script like this ./occ da:add-missing-indices when upgrading from 13.x to 14, but failed. 

I think it would be better to obtain php cli's location/dir, and chmod occ with +x before users do the upgrading job.

**Comment by fl2ma** [comment]
Maybe there could be further documentation about the necessary indizes for the table?
Unfortunately I'm unable to use sudo and therefore OCC fails.
If I would know the required indizes, I could create them manually on the DBMS. I tried to get that info from the source code but couldn't find it.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/master/core/Command/Db/AddMissingIndices.php

**Comment by Mannshoch** [comment]
I have the same Problem. My server provider do not allow to use the same user on cli.
I also have a convert Error message which I'm not able to solve because I do not have access to OCC.

Please add a Button next the indizes and the convert error message.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.

**Comment by shot4u** [comment]
We had the same issue in NC 17.0.1 with PHP 7.2.23 and fixed in the following way:

```
yum install php72-php-pdo php72-php-pdo_mysql php72-php-xml php72-php-posix php72-php-gd php72-php-mbstring php72-php-zip 
service httpd restart
sudo -u apache /opt/remi/php72/root/bin/php /var/www/html/drive/occ db:add-missing-indices

```
