### ISSUE TITLE
image cannot be render in correct way

### ISSUE THREAD

**Issue by HelloLemon1992** [nextcloud/server#13044]
### Steps to reproduce
1.enable the gallery apps;
2.open an image, but not wait it to load finish, and click exit button on the upper right corner;
3.when the image load finish, it will throw an exception of typeError; and then ,the index of image cannot be show;

### Expected behaviour
the load event and the render event is different; if render failed, when open the image again, it must load and render again;

### Client configuration
**Browser:** chrome

**Operating system:** windows 10

**Comment by HelloLemon1992** [comment]
at last,I set a array varible  to save the status of render result, if catch the exception ,then not save(if click exit button when the image not loaded finish and render failed, will throw an exception ), to temporarily solve the problem;

**Comment by skjnldsv** [comment]
This should go into the gallery app.
As a new note, we now have the new files viewer that includes a proper view of images. (16)
