### ISSUE TITLE
Nextcloud 14 failed to share by mail - 403

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#13049]
### Steps to reproduce
1.  Click on share button next a file or folder
2. Add an email
3. And try to share the item

### Expected behaviour
The file or folder should be shared

### Actual behaviour
Instead, I have an error 403 and the file/folder isn't shared.

![Err](https://i.imgur.com/YRc4jBB.png)

### Server configuration

**Operating system**:
CentOS 6.10

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.1.23

**Nextcloud version:**
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**config.php**

```
<?php
$CONFIG = array (
  'passwordsalt' => 'SALT',
  'secret' => 'SECRET',
  'trusted_domains' =>
  array (
    0 => 'DOMAIN',
  ),
  'datadirectory' => '/var/www/html/files/data',
  'overwrite.cli.url' => 'https://DOMAIN/files',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'integrity.check.disabled' => true,
  'dbname' => 'nextcloud',
  'dbhost' => 'HOST',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nc_user',
  'dbpassword' => 'PASS',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'HOST',
    'port' => PORT,
    'password' => PASS',
  ),
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'DOMAIN',
  'knowledgebaseenabled' => false,
  0 => 18,
  'loglevel' => 1,
  'maintenance' => false,
  'instanceid' => 'ID',
);

```

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 7

#### Browser log
![Log](https://i.imgur.com/S0GKG0x.png)

**Comment by violoncelloch** [comment]
are you sure the app "Share by mail" is enabled?
`(distant)` means it trys to federate with the user mail at the instance gmail.com and not to send a link by mail. If "Share by mail" is enabled you should see a second option for sharing via email to mail@gmail.com

**Comment by vipera7** [comment]
How can I check if the app "Share by mail" is enabled, without using the web client ?
