### ISSUE TITLE
Parameter to hide usernames for occ group:list

### ISSUE THREAD

**Issue by va1entin** [nextcloud/server#13058]
**Is your feature request related to a problem? Please describe.**
occ group:list gets extremely slow in environments with lots of groups and lots of users in them. In my environment its 28000 users in 81 groups.

**Describe the solution you'd like**
A way to get Nextcloud groups without the users in them such as occ group:list --no-users <group> . A simple group:exists <group name> would even be enough for my use case. The users shouldn't just be hidden, but not even queried in the first place.

**Describe alternatives you've considered**
The groups come from a LDAP in my case. I've considered occ ldap:search to check if a group exists, but this only tells me whether it's found with the configured LDAP filters, not that it actually exists in Nextcloud. This obviously doesn't help anyone with other user/group backends facing this issue.
A workaround is to try adding an (admin) user to the group using occ:adduser <group> <user> and removing it. Adding the user fails and gives back exitcode 1 if the group doesn't exist.

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
