### ISSUE TITLE
Stateless 2FA providers

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13051]
**Is your feature request related to a problem? Please describe.**
Since Nextcloud 14 2FA providers are stateful for enhanced security and performance. This means their enabled/disabled state per user is managed and persisted in the provider registry. Therefore providers can no longer dynamically decide if they should be enabled by the currently logging in user or not, which was possible up to Nextcloud 13.

**Describe the solution you'd like**
We could have a new IStatelessProvider interface where we move/copy over the legacy method IProvider::isTwoFactorEnabledForUser. On login, providers implementing this interface will be checked dynamically. Any failure to load will allow bypassing 2FA.

**Describe alternatives you've considered**
@rullzer proposed an alternative where providers can be made/tagged as "passive" and when their challenge page is shown the form is automatically submit where the provider can just let the user pass.

**Additional context**
n/a

---

Edit: We still have to make sure that if provider apps vanish, we don't let the users log in. Therefore we must have a table with active providers. And offer a command to remove providers from that table. If a users logs in and a stateless provider can't be found we lock down.

**Comment by cornelinux** [comment]
In an enterprise environment you do not want to decide on a per user basis, if a user needs to do 2FA or not.
You might either decide it for *all* users or based on groups memberships.

This is how we do in the [privacyIDEA plugin](https://github.com/privacyidea/privacyidea-owncloud-app) which worked fine up to Nextcloud 13.

If you have a central 2FA system, it makes only limited sense to have a 2nd point of administration, when it comes to two factor authentication.

# Issues with your current implementation

Here are some issues, about dealing with the approach you chose for NC14 and NC15 to store for each single user in Nextcloud whether to use 2FA:

## New user

If a new user enters the scene, he either needs to do 2FA or does not need to do 2FA.
The first time such a user logs in to Nextcloud, Nextcloud can not know, if the user is supposed to provide a second factor or not.
The only one, who knows this, is the 2FA provider. 
So Nextcloud has to pass the control to the 2FA provider, no matter what!

## Existing user changes group

Sometimes you have a group of users, who are supposed to do 2FA. There are many scenarios, let's pick the one, where you have a pilot for enrolling 2FA. You will add user after user to the 2FA group.
In our 2FAprovider for this purpose we check user groups. 
But how could we know that user was added to a group, so how should any component know, that such a user needs a new entry in the database table ``oc_twofactor_providers``?

Is there a hook for a two factor provider to add users into this table?
(And if there was, I think it is not a good design)

## Changes in 2FA backend system

Changes in the 2FA backend system could lead to change, that a user does not need to do 2FA anymore. 
I think there is absolutely no way how to change the database table to change the user settings to 0.

# Implementation suggestion

So if you can not or do not want to allow the ``isTwoFactorEnabledForUser`` function, you could come up with a more generic and thus flexible solution, which is aboslutely necessary when dealing with enterprise setups. 

The key approach is to avoid storing single user information.

Here is a simple suggestion - as low hanging fruit.

Simply go for groups, to check if and which 2FA provider a user has to /can use:

You could very well define a list/database table like this:

* groupname
* 2Factorneeded
* possible provider

This way NC can check
1. In which groups the user is located
2. If the user has to use 2FA and
3. which providers are allowed to use 2FA.

But here is still one thing, that would not be supported by this approach:

Currently our 2FA plugin (which thus only works up to NC13), allows not only to choose for groups which users should do 2FA or not, it allows allows to define on an IP basis, if a user should do 2FA.

Think about a setup where the Nextcloud server is located in your DMZ. Authentication from the itnernet (client IP being the external firewall) would require a 2nd factor, authentication from the LAN (client IP being the internal firewall) would not require a 2nd factor.

Unfortunately the your current implementation for 2FA is not fit to handle enterprise 2FA. But I am happy to be available for discussion.

**Comment by ChristophWurst** [comment]
I don't see how my proposed solution of the *new* `isTwoFactorEnabledForUser` method wouldn't allow all these cases. You can just use that method to dynamically check for group membership or anything else you're interested in. We just cannot make this the default for all providers.

**Comment by rullzer** [comment]
> Think about a setup where the Nextcloud server is located in your DMZ. Authentication from the itnernet (client IP being the external firewall) would require a 2nd factor, authentication from the LAN (client IP being the internal firewall) would not require a 2nd factor.

If this is the only use case that now is not possible then users should just also use their second factor when in the internal network. This is safer anyways.

On top of that users probably don't login every 10 minutes so the overhead is also minimal.

**Comment by cornelinux** [comment]
> > Think about a setup where the Nextcloud server is located in your DMZ. Authentication from the itnernet (client IP being the external firewall) would require a 2nd factor, authentication from the LAN (client IP being the internal firewall) would not require a 2nd factor.
> 
> If this is the only use case that now is not possible then users should just also use their second factor when in the internal network. This is safer anyways.
> 
> On top of that users probably don't login every 10 minutes so the overhead is also minimal.

I - as a techie and nerd - totally agree with you. But you can not assume that your software is only used by technical enthusiasts.

**Comment by cornelinux** [comment]
> I don't see how my proposed solution of the _new_ `isTwoFactorEnabledForUser` method wouldn't allow all these cases. You can just use that method to dynamically check for group membership or anything else you're interested in. We just cannot make this the default for all providers.

OK, but I thought ``isTwoFactorEnabledForUser`` is evil and insecure. So I assumed you wanted to get rid of this.
Can you please elaborate on how having the ``isTwoFactorEnabledForUser`` method in ``IStatelessProvider`` is more secure than having it in ``IPovider``? Thanks!

**Comment by ChristophWurst** [comment]
> Can you please elaborate on how having the `isTwoFactorEnabledForUser` method in `IStatelessProvider` is more secure than having it in `IPovider`? Thanks!

It is evil ;) So we don't want to have this as a default for all providers. Instead, we have a new interface that will only be implemented by providers that rely on the dynamic active/inactive transition where the registry does not fit the needs. As documented in the proposal any failure or bugs in a provider that implements this interface might allow a bypass of 2FA if no other providers are active. All other providers will still fall back to the safe default of just blocking access to the account if the 2FA provider can't be loaded.

**Comment by cornelinux** [comment]
@ChristophWurst Thank a lot. So the old way with the ``isTwoFactorEnabledForUser`` will lead to bypass the 2FA if the provider would run into an error / raise an exception.
Your new way of implementing the provider would simply as a failsafe block, if the provider after all was implemented... ...let's say *sloppy*.

**Comment by cornelinux** [comment]
@ChristophWurst Do you know, when the ``IStatelessProvider`` will be available?

**Comment by ChristophWurst** [comment]
> So the old way with the `isTwoFactorEnabledForUser` will lead to bypass the 2FA if the provider would run into an error / raise an exception.

More specifically, the issue is when the app *disappears*, as in, get's disabled or deleted. Because then we can't even know that there is an app with a provider because we have no info.xml.

> @ChristophWurst Do you know, when the `IStatelessProvider` will be available?

The moment someone implements it, submits a pull request and that gets merged before a feature freeze :wink: 

It's not planned for any specific Nextcloud release at the moment.

**Comment by Mipronimo** [comment]
> More specifically, the issue is when the app _disappears_, as in, get's disabled or deleted. Because then we can't even know that there is an app with a provider because we have no info.xml.

So if an administrator disables all 2fa apps, because he does not want to use them anymore, he has to modify the database and cannot disable it in the settings?

**Comment by ChristophWurst** [comment]
No, they don't: https://github.com/nextcloud/server/blob/7586b19e524761c1e8aab5170375a0d6c9e8f7a2/core/Command/TwoFactorAuth/Cleanup.php#L49

**Comment by skjnldsv** [comment]
to develop or not?

**Comment by ChristophWurst** [comment]
As soon as there is a sponsor :)

So right now I'd say no. Our providers work perfectly fine with the secure way. We don't need nor want the stateless approach for those.

**Comment by susnux** [comment]
Reopen as there is still demand on the feature request by other users.

*by @Furgas*

> We are implementing our own 2FA provider and we ran into a problem. Our 2FA provider is controlled (enabled or disabled) by the user outside the nextCloud app. There are [IProvider::isTwoFactorAuthEnabledForUser](https://github.com/nextcloud/server/blob/master/lib/public/Authentication/TwoFactorAuth/IProvider.php#L76) method but:
> - it's called only when there is no provider state saved in database
> - it looks like marked for removal

**Comment by Furgas** [comment]
Good to see it's reopened. We have to plan next actions at our company, so I need to know what are the next steps to make it happen and how long we would need to wait - weeks, month, years or when-its-done.  I would be grateful for any hints, thank you.

**Comment by susnux** [comment]
@Furgas Well we consider feature requests based on customer but also especially community demand (we use the number of reactions on the initial post (👍) as one of the metrics for that).
So if we see that the community has a high demand on this (or a customer of us) then we consider implementing it.

But we always welcome contributions, as this is open source everyone is welcome to create a PR implementing the `IStatelessProvider` as described in the posts above 😃

**Comment by Roszakos** [comment]
> But we always welcome contributions, as this is open source everyone is welcome to create a PR implementing the `IStatelessProvider` as described in the posts above 😃

I'd like to submit a PR but the issue is still labeled as `0.  Needs triage` so according to your guidelines it hasn't been approved for development yet. Could you please clarify whether i can go ahead and submit the PR?

Also, i wanted to make sure that my approach for this is good. Since i'm not very familiar with the NC codebase i decided to go for the simplest solution, which comes down to not storing user 2FA state in the database for providers that implement `IStatelessProvider`. This way, `isTwoFactorAuthEnabledForUser` is always called within `Managers` `fixMissingProviderStates` method for such providers. Let me know if this solution is acceptable.
