### ISSUE TITLE
[NC15] Retention app 1.4 doesn't display created entries in the web interface

### ISSUE THREAD

**Issue by gixxxerg** [nextcloud/server#13057]
reference from:  https://help.nextcloud.com/t/retention-app-broken-in-15/43152

### Steps to reproduce
1. install Retention app
2. create invisible tag to be used for retention purpose
3. create retention entry

### Expected behaviour
after submitting, the actual entry should be visible in the interface showing the setting

### Actual behaviour
no entry is visible at all in the interface

verified by user Schmu that entry actually ends up in database but is not visible in the GUI

**Operating system**:
Ubuntu 18.04.1 LTS

**Web server:**
Apache2

**Database:**
MySQL 10.1.34

**PHP version:**
7.2.13

**Nextcloud version:** (see Nextcloud admin page)
15.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.04

**Where did you install Nextcloud from:**
Webupdater

**Browser:**
Any

**Operating system:**
Any

**Comment by nickvergessen** [comment]
Closing this one

**Comment by gixxxerg** [comment]
26 days waiting on triage and then closing it to give precedence to a 5 day old bug report in the correct location. Can't it just be moved!?
