### ISSUE TITLE
Warning imagick missing although installed

### ISSUE THREAD

**Issue by WarpinWolf** [nextcloud/server#13059]
Hopefully I'm doing this right....
(Issue template resolves in 404)

Debian 8.11
Nextcloud 15.0.0.10
PHP Version => 7.0.32-1~dotdeb+8.1
imagick
imagick module => enabled
imagick module version => 3.4.3

Nevertheless I receive the following (German) warning:

Dieser Installation fehlen einige empfholene PHP-Module. Für bessere Leistung und bessere Kompatibilität wird dringend empfohlen, diese zu installieren.
imagick

obviously something that has been added here: https://github.com/nextcloud/server/pull/12821

Seems as if the detection does not work in this case?!?!?

**Comment by danielkesselberg** [comment]
Could you share `php -m`?

**Comment by WarpinWolf** [comment]
Here you go...
php -m
[PHP Modules]
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
imap
intl
json

libxml

mbstring

mcrypt

mysqli

mysqlnd

openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache



Am Do., 13. Dez. 2018 um 16:34 Uhr schrieb Daniel Kesselberg <
notifications@github.com>:

**Comment by WarpinWolf** [comment]
Sorry - my fault. I did "apt-get install php7.0-imagick" before but
apparently there is no "phpenmod imagick". And even this won't work until
you "service php7.0-fpm restart" it.

It now does work. Output from test.php "bool(true) bool(true)"

Thanks for the prompt reaction! Great job!!!


Am Do., 13. Dez. 2018 um 17:29 Uhr schrieb Daniel Kesselberg <
notifications@github.com>:
