### ISSUE TITLE
Layout of share suggestions is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#13055]
> ![bildschirmfoto von 2018-12-13 13-58-38](https://user-images.githubusercontent.com/213943/49940378-97a2ef80-fedf-11e8-8a62-d3c61442b71b.png)

Current master, no idea when this happened, stable15 is fine

@skjnldsv @juliushaertl ?

**Comment by skjnldsv** [comment]
Duplicate of #12832

**Comment by nickvergessen** [comment]
sorry a quick search didnt bring it up
