### ISSUE TITLE
Limit to groups working strangly

### ISSUE THREAD

**Issue by iteco** [nextcloud/server#13064]
![selection_649](https://user-images.githubusercontent.com/4575046/49971189-46721a80-ff36-11e8-8d9e-d823223830f3.jpg)

I tried to limit one app to a specific user group, but after checking 'limit to groups' for that app (see attached image) all the apps got the same selection. I would have expected that I can limit only that one app, and would not have to limit all apps. 

Tried on nc 14.0.4 at ubuntu 16.04
https://nc.iteco.fi/index.php/settings/integrity/failed --> No errors have been found.

Btw. Is there any documentation that would tell what to expect ? I looked it, but didn't found anything. Admin guide was only saying that it is possible to limit some apps to groups.

**Comment by skjnldsv** [comment]
Hum I cannot exactly reproduce the issue, but something is weird indeed.
Most likely a key missing in vue to force the data to update the content.

cc @juliushaertl

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by juliushaertl** [comment]
Yes, there was another ticket about it as far as I remember but I cannot find it at the moment.

The current limit to groups setting will block the whole app from being loaded, so the public endpoints are never registered.

Anyway a better error message definitely makes sense from my perspective.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
