### ISSUE TITLE
Provide a public API for alternative logins

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13067]
**Is your feature request related to a problem? Please describe.**
There are many apps that provide "alternative logins". A quick github query reveals that they all use a fragile and private API for that: https://github.com/search?q=registerLogIn+oc_app&type=Code

**Describe the solution you'd like**
I would like to propose a switch to a public API. There should be a service where apps can register their login pages. That should ensure that the API stays stable and that all required parameters are passed in.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

Prominent example: https://github.com/pellaeon/registration/blob/ef3afbab06165bf0e9bcdb4a85a055a71c5df05b/appinfo/app.php#L14-L17

**Comment by szaimen** [comment]
Is this still valid?

**Comment by ChristophWurst** [comment]
yes

**Comment by joshtrichards** [comment]
Fixed in #21850
