### ISSUE TITLE
When appstore disabled, splash screen still displays link to it

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#13061]
Nextcloud 15 (and previous versions).

Context: During install, we run:
```
php occ config:system:set appstoreenabled --type boolean --value false
```
to disable the app store. Which works.

Current behavior: when the user logs in for the first time, the splash screen's 4th tab still shows a link to the app store. When a user discovers this, they are confused, because the splash screen shows a feature that doesn't actually exist in this installation.

Better behavior: the 4th tab is not shown when the app store is disabled.

**Comment by danielkesselberg** [comment]
Can confirm after looking into the code. The firstrunwizard is a own app https://github.com/nextcloud/firstrunwizard on github. Would you mind to open the feature request there? Or even better submit a pull request for it?

1) https://github.com/nextcloud/firstrunwizard/blob/b0f911e2641999e6d7ca328814621a15a1f0b5c9/lib/Controller/WizardController.php#L72  Add a new line `isAppStoreEnabled => $this->config->getSystemValue('appstoreenabled', true),` below `ios`.

2) https://github.com/nextcloud/firstrunwizard/blob/b0f911e2641999e6d7ca328814621a15a1f0b5c9/templates/wizard.php#L34 Change if to `$_['isAppStoreEnabled'] && OC_User::isAdminUser($uid)`.

Thats it :tada:
