### ISSUE TITLE
Get 403 first when createShare for new folder via shares api, second try ok.

### ISSUE THREAD

**Issue by pebosi** [nextcloud/server#13075]
### Steps to reproduce
1. Create sub-folder in one global group folder
2. Try to create a public share link for the new folder -> 403
3. Re-try same request -> 200

### Expected behaviour
Should work on first try

### Actual behaviour
Throws access forbidden

### Server configuration
Ubuntu 16.04

**Web server:**
Apache 2.4.8

**Database:**
MariaDB

**PHP version:**
7.2.13

**Nextcloud version:** (see Nextcloud admin page)
 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 13

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
- "No errors have been found."
```

**List of activated apps:**
<details>
<summary>App list</summary>
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.0
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 2.1.8
  - dav: 1.8.0
  - deck: 0.5.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.1
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - provisioning_api: 1.5.0
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflow_pdf_converter: 1.0.1
  - workflowengine: 1.5.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": false,
        "forcessl": true,
        "knowledgebaseenabled": false,
        "updatechecker": false,
        "maintenance": false,
        "version": "15.0.0.10",
        "loglevel": 2,
        "log_type": "file",
        "logtimezone": "Europe\/Berlin",
        "logfile": "\/var\/log\/nextcloud.log",
        "remember_login_cookie_lifetime": "3600",
        "default_language": "de_DE",
        "trusted_domains": [
            "data.pax.de",
            "box.pax.de"
        ],
        "share_folder": "\/Shared",
        "blacklisted_files": [
            ".htaccess",
            ".gitignore",
            ".DS_Store"
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "log_rotate_size": 104857600,
        "updater.release.channel": "stable",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
PHPGuzzle , Postman

**Comment by pebosi** [comment]
Just realized that it doenst work at all with curl. Postman automatically sends the cookies returned from the first failing request so the second one works...

**Comment by pebosi** [comment]
``curl --request POST   --url 'https://nextcloud-server.de/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json'   --header 'authorization: Basic bXlwYXgxNDo1MU41Y1pYS2c0MrrXBXaEZVQ3R6anhxSzIzMkY4djZDaQ=='   --header 'content-type: application/x-www-form-urlencoded'   --header 'ocs-apirequest: true'   --data 'shareType=3&path=%2FGroupfolder%2FSubfolder'

**Comment by pebosi** [comment]
Ok, this issue is only related to https://github.com/nextcloud/groupfolders

**Comment by fuco809** [comment]
same issue (but always fails) with nextcloud v17 and curl groupfolder share creation - see also https://github.com/nextcloud/groupfolders/issues/271
