### ISSUE TITLE
Toggle Grid View Button overlaps Collabora Close Button

### ISSUE THREAD

**Issue by Aschenbecher** [nextcloud/server#13072]
Since Nextcloud 15 the new Toggle Grid view button is on the same position like the Collabora close Button, its not possible to use the close button anymore. 

I´m using Firefox.
Is it possible to change position of one of the buttons?

Best Regards

**Comment by timmersr** [comment]
Same as #12797

**Comment by Aschenbecher** [comment]
sry, didnt found it
