### ISSUE TITLE
[ Nextcloud 15 ] : Social app missing trigger error about /.well-known/webfinger

### ISSUE THREAD

**Issue by Kitslap** [nextcloud/server#13088]
### Steps to reproduce
1. Update nextcloud 14 to 15
2. Install Social app
3. Disable or uninstall social app

### Expected behaviour
There should be no error in the overview of administration page.

### Actual behaviour
There is the following error.

<details>
<summary>Error from Overview in Administration page</summary>
Security warnings & configuration

It is important for the security and performance of your instance that it is properly configured. In order to help you, your Nextcloud instance performs some automatic checks. For more information, please consult the related documentation.
There are some warnings about your configuration.

     The configuration of the web server does not reach "/.well-known/webfinger". You will find more information in the documentation.

Please consult the installation guides ↗ and check the log errors or warnings.

</details>

### Server configuration

**Operating system**: CentOs 7.6

**Web server:** httpd-2.4.6-88.el7.centos.x86_64

**Database:** mariadb-server-5.5.60-1.el7_5.x86_64

**PHP version:** php72

**Nextcloud version:** Nextcloud 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** From official site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - bookmarks: 0.14.3
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 2.1.8
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 4.99.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - unsplash: 1.1.3
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "213.32.64.170"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/213.32.64.170",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "token_auth_enforced": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "htaccess.RewriteBase": "\/"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

I tried to fix .htaccess file with manual update and with the occ command to generate a new one but I'm not sure it had something to do with that.
I've already open topic on help.nextcloud.com : https://help.nextcloud.com/t/nextcloud-15-update-well-known-webfinger-impossible-to-reach/43082

I'm not alone in this case like you can see in the topic, I don't think it is a big issue but I report it anyway.

Sorry for bad enslish, not my native language.

**Comment by pgeorgi** [comment]
One issue mentioned there is that /.well-known/webfinger returns "missing resource", but that's working as intended (and means that you need to add an argument):

Try https://your.host/.well-known/webfinger?resource=acct:existing-user@your.nextcloud.instance, which should return a json document pointing to /apps/social/@user.

**Comment by Kitslap** [comment]
No if the app is disabled or absent the error is displayed. The error goes if I activate Social App.
The reporting is about the bad displaying, if the app is gone we should'nt have any error linked to the app. Do you understand the point ? The error doesnt concern directly a redirection issue, what I thought in the beggining, it is about the displaying of error about an app I've uninstalled. If I install back social there will be no error in my overview.

**Comment by juliushaertl** [comment]
@daita I think the issue here is that if the social app is not enabled, the webfinger endpoint returns an Internal Server Error, which is considered by the setup check as setup wrongly. Maybe we should just don't throw an error of no app hooks into the webfinger?

**Comment by daita** [comment]
@juliushaertl I guess you're talking about 
https://github.com/nextcloud/server/blob/f64bd62f8e438fe36a6c070ac445a07ad22439e4/public.php#L71

that should be changed to
```
if (!\OC::$server->getAppManager()->isInstalled($app)) {
{
http_response_code(404);
exit;
}
```

**Comment by mannp** [comment]
This still gives an error for me in 15.0.4 when the social app is disabled.

**Comment by wylel** [comment]
This seems to still be an issue. Running 15.0.8 on Debian 9 Stretch. I installed Social, never commented out the line in the nginx conf file, and uninstalled Social, and now I see the warning in the settings saying I need to enable it.

**Comment by daita** [comment]
@MorrisJobke : We need a strategy in here.

right now, the public.php does not returns if there is no settings core/public_<interface> or if the value of the settings point to an app that is not enable anymore. 

Is it a way to execute some code when your app is disabled ? So the social app could reset the settings.

If not, we can:

- set the same error code if the app linked to a public interface is not available.
- or provide the occ command to the admin to reset the setting.

**Comment by msberends** [comment]
> @MorrisJobke : We need a strategy in here

It’s been 2 months and since this issue has closed, please don’t let this stall. There is no long term or sustainable solution to this yet, as I see it.

**Comment by kesselb** [comment]
@msberends https://github.com/nextcloud/server/pull/16997 does not work for you?

**Comment by msberends** [comment]
Sure, for the social app it does. But is it sustainable? I.e. is the solution app UNspecific enough?

**Comment by mannp** [comment]
Doesn't work for me and still have the problem.

Stopped trying apps on both my servers due to the lack of support to resolve issues like this for the early adopters.

**Comment by kesselb** [comment]
> Sure, for the social app it does. But is it sustainable? I.e. is the solution app UNspecific enough?

@daita I don't know :man_shrugging:
