### ISSUE TITLE
php v7.3 caldav and vcard continue break warning.

### ISSUE THREAD

**Issue by cdmlb** [nextcloud/server#13089]
Since updating to php v7.3

I get these two errors constantly, they are just warnings accord to the php documentation, but one day the code might not be backwards compatible anymore, idk???

"continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at 
/3rdparty/sabre/dav/lib/CalDAV/ICSExportPlugin.php#321
/3rdparty/sabre/vobject/lib/Component/VCard.php#514

**Comment by rEnr3n** [comment]
https://github.com/nextcloud/calendar/issues/1064

**Comment by J0WI** [comment]
Backport for NC 15: https://github.com/nextcloud/3rdparty/pull/213

**Comment by MorrisJobke** [comment]
Will be fixed in 15.0.5
