### ISSUE TITLE
Adding trailing slash returns 404 not found

### ISSUE THREAD

**Issue by PhoenixPeca** [nextcloud/server#13084]
Hi,

the shared links on shared files/folders doesn't work with the trailing slash on.

This link works: https://cloud.example.com/s/xxxxxxxxxxxxxxx

But this one doesn't: https://cloud.example.com/s/xxxxxxxxxxxxxxx/

**Comment by skjnldsv** [comment]
Yes, this is a link to a hash, not a directory.
So this is indeed not the same url.
