### ISSUE TITLE
Cannot login to web version

### ISSUE THREAD

**Issue by luntik2012** [nextcloud/server#13083]
Again. No description, you know everything

**Comment by violoncelloch** [comment]
What's that? how should we know everything if you don't provide any information?
If you've already submitted an issue for your problem it's completely useless to submit further ones, it just generates extra work and therefore devs don't have to time to actually fix bugs.

**Comment by luntik2012** [comment]
browser cookies prevent from login, cleaning is neaded.
> how should we know everything if you don't provide any information?
you've seen this issue billion of times. it's really boring to clear cookies once per week

**Comment by violoncelloch** [comment]
However Github tells this is your first issue in this repo. Pleasy provide information on your problem if you want us to look at it.
