### ISSUE TITLE
Add warning if user wants to share files/folders to another outdated Nextcloud installation

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/server#13095]
**Is your feature request related to a problem? Please describe.**
Sadly there are a lot of outdated Nextcloud or Owncloud installations out there. If an organisation runs a professionally set up and secured installation and users want to share files or folders to an outdated and rotten installation from another organisation they get no warning that they potentially expose their data to a system that cloud get easily compromised. This could lead to serious problems if confidential data becomes accessible by unauthorized third parties. Anyway, if somebody runs an outdated version then there could be a chance that it is already compromised.

**Describe the solution you'd like**
Please add a warning message if a user wants to share to another outdated Nextcloud installation so they can make an informed decision if they really want to proceed with potentially exposing their data to a compromised system.

**Describe alternatives you've considered**
Another option would be some setting for the admin to prohibit sharing to an outdated installation by any user.

**Comment by violoncelloCH** [comment]
what do you think @nextcloud/security?

**Comment by nickvergessen** [comment]
Puh, I don't know.
It's just a version number nothing that does qualify a risk in any way.
On the otherhand if there ever is such an issue it would be nice to be able to prevent something like sharing with a specific version, but the user could have patched it themselves too. 

@schiessle what do you think

**Comment by tflidd** [comment]
I have a bit mixed feelings about that. Recently, when NC 12 was still supported, the iOS app generated a warning that the NC 12 is not supported any more (https://github.com/nextcloud/ios/issues/680). If there were now a warning about NC 11, maybe ok. But then again, be careful about false positives, perhaps an enterprise user has extended support, or via federated sharing a different platform is used, ...

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
