### ISSUE TITLE
Nextcloud 14.0.4 . Your version is up to date. 

### ISSUE THREAD

**Issue by jpVm5jYYRE1VIKL** [nextcloud/server#13093]
### Steps to reproduce
1. Go to settings 
2. subscribe to channel stable 
3. update page 
5. Wait for finish
6. You see "Your version is up to date".  

### Expected behaviour
Ready for update to version 15. 

### Actual behaviour
Your version is up to date.  But it is bullshit because it released week ago.

### Server configuration
default

**Comment by danielkesselberg** [comment]
> How do I get 15? 

> As always, you can wait for the updater to help you move to Nextcloud 15. Users on the Nextcloud 14 series will see the new version appear starting end of this week, however, note that we roll out new releases incrementally! This means that it can take several weeks before it becomes available, and if a serious issue is found during roll-out, we will delay or stop the roll-out and wait until 15.0.1 is out with fixes.

> If you wish to wait no longer, you can temporarily switch to our Beta release channel and reload the page. 15 should then be available for you. After the upgrade you can safely go back to stable to receive 15.0.1 once it is out!

> Of course, manual upgrades are always possible. If you use packages on various Linux distributions, use the Snap or use one of our Virtual Machine images, you will have to wait for each of those to upgrade. The Snap typically takes quite a while, the VM comes after the first or second bugfix release and packages depend on your distribution policy.

https://nextcloud.com/blog/nextcloud-15-goes-social-enforces-2fa-and-gives-you-a-new-generation-real-time-document-editing/
