### ISSUE TITLE
Improve backup codes UI/UX

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#1309]
We recently added a new setting to the personal settings page – the ability to generate backup codes, which can be used in case users lose access to their second factor. At the moment, the user interface doesn't look that nice:
![bildschirmfoto von 2016-09-07 17-33-06](https://cloud.githubusercontent.com/assets/1374172/18318366/b9bbf462-7521-11e6-923e-8bad821984cd.png)
![bildschirmfoto von 2016-09-07 17-33-18](https://cloud.githubusercontent.com/assets/1374172/18318367/b9c0811c-7521-11e6-95a1-7b99406b71ff.png)
![bildschirmfoto von 2016-09-07 17-33-27](https://cloud.githubusercontent.com/assets/1374172/18318368/b9c2a7c6-7521-11e6-9fa5-3c8c6da61161.png)
![bildschirmfoto von 2016-09-07 17-33-29](https://cloud.githubusercontent.com/assets/1374172/18318369/b9c511dc-7521-11e6-9f4a-f35445eaa97f.png)

@nextcloud/designers any idea how we could make a prettier user interface out of that? Would be great if someone could create a mockup :art: :rocket: 

ref https://github.com/nextcloud/server/pull/1171

**Comment by MariusBluem** [comment]
- A bit of space between the explanation and the codes. 
- Show only 5 codes in one row instead of 10. 

And for all other 2FA's:

- Put all 2FA stuff into one single menu instead of giving every plugin (and now the codes) an own space on the personal-page.

**Comment by ChristophWurst** [comment]
> Put all 2FA stuff into one single menu instead of giving every plugin (and now the codes) an own space on the personal-page.

If that were possible, I'd dot it :wink:

**Comment by MariusBluem** [comment]
> If that were possible, I'd dot it 😉

Isnt this also possible on admin-page with the encryption stuff. "No Encryption plugin loaded". We could do the same for 2FA - we load all plugins into a single column. 😉

**Comment by ChristophWurst** [comment]
> Isnt this also possible on admin-page

Yes, it is. But AFAIK *only* on the admin page and not for personal settings. cc @blizzz

**Comment by blizzz** [comment]
> > Isnt this also possible on admin-page

> Yes, it is. But AFAIK *only* on the admin page and not for personal settings. cc @blizzz 

Yupp. The intention is to integration personal and admin settings to have just one "settings". We're not there yet and personal settings were not touched.

**Comment by MariusBluem** [comment]
> Yupp. The intention is to integration personal and admin settings to have just one "settings". We're not there yet and personal settings were not touched.

I have some aspects speaking against that - but this is not the right place to discuss 😁

**Comment by comradekingu** [comment]
![2factorbackup](https://user-images.githubusercontent.com/13802408/30779410-666b78ea-a0f0-11e7-8c43-062af44cee78.png)

![2factorbackup2](https://user-images.githubusercontent.com/13802408/30779411-6ca0a78a-a0f0-11e7-87d6-923e1faef5a2.png)

**Comment by jancborchardt** [comment]
@comradekingu looks good, only the "Old codes are lost …" text is a bit big and out of place. Should use a normal p.

Feel free to open a pull request.

**Comment by ChristophWurst** [comment]
Basically done by #11409 and other recent enhancements.
