### ISSUE TITLE
Undefined offset at admin_audit/lib/Actions/Console.php

### ISSUE THREAD

**Issue by reinob** [nextcloud/server#13098]
### Steps to reproduce
1. sudo -u www-data php -f ./occ
2. check last line in log

### Expected behaviour
Nothing should be logged (no error)

### Actual behaviour
```
{"reqId":"W7IFTuV5jg7KxHu2eZLD","level":3,"time":"2018-12-16T17:59:19+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Undefined offset: 1 at \/var\/www\/nextcloud\/apps\/admin_audit\/lib\/Actions\/Console.php#33","userAgent":"--","version":"15.0.0.10"}
```

### Server configuration
Debian stretch, Apache, PostgreSQL 11, PHP 7.2, Nextcloud 15 (fresh install)

$arguments[1] is accessed, which causes an exception if no arguments have been issued.

For an almost no-op module written in 2017 and even made "strict" in 2018, this is unacceptable from the code quality point of view.

**Comment by FvdLaar** [comment]
Same with NC 14 : Undefined offset: 1 at /var/www/cloud/apps/admin_audit/lib/Actions/Console.php#33

No idea what's causing it. Will see if I can reproduce it some how.

**Comment by danielkesselberg** [comment]
I see this error with NC 14 as well but cannot reproduce it locally. 

```
                if (isset($arguments[1]) && $arguments[1] === '_completion') {
                        // Don't log autocompletion
                        return;
                }
```
Isset before access will prevent this message.

**Comment by axiomcs78** [comment]
I am getting this error and can offer my setup for troubleshooting.  Let me know what you would like to know or try.
