### ISSUE TITLE
Dark theme shows light theme when selecting files

### ISSUE THREAD

**Issue by ryan77627** [nextcloud/server#13104]
### Steps to reproduce
1. Turn on dark theme
2. Select some files using the checkboxes
3. Look at the top bar

### Expected behaviour
Top bar shouldn't turn white

### Actual behaviour
Top bar turns white. See: https://ibb.co/PNLkPGN

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache 2.4.29

**Database:** MYSQL

**PHP version:** 7.2

**Nextcloud version:** 14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Tarball from official website
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/DB
</details>

### Client configuration
**Browser:** Firefox 63.0.3

**Operating system:** Fedora 29

#### Browser log
<details>
<summary>Browser log</summary>

```
no errors in console
```
</details>

**Comment by skjnldsv** [comment]
![Capture d’écran_2019-04-30_10-52-07](https://user-images.githubusercontent.com/14975046/56950531-03f05980-6b36-11e9-8e2c-3dfe2735237f.png)

Fixed in latests versions
