### ISSUE TITLE
Password strength indicator blocked by CSP

### ISSUE THREAD

**Issue by Lartza** [nextcloud/server#13102]
### Steps to reproduce
1. Browse to User > Settings > Security
2. Type a password

### Expected behaviour
Password strength should be shown

### Actual behaviour
Password strength isn't shown

### Server configuration

**Operating system**: Arch Linux

**Web server:** Nginx 1.15.7

**Database:** PostgreSQL 11.1

**PHP version:** 7.3

**Nextcloud version:** 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** Manual

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.lagit.in",
            "cloud.ltn.fi"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.lagit.in",
        "dbtype": "pgsql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

### Client configuration
**Browser:** Firefox 64.0

**Operating system:** Windows 10 1803

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
Loading failed for the <script> with source “https://cloud.lagit.in/core/vendor/zxcvbn/dist/zxcvbn.js”. security:1:1
Content Security Policy: The page's settings blocked the loading of a resource at https://cloud.lagit.in/core/vendor/zxcvbn/dist/zxcvbn.js ("script-src").
ReferenceError: zxcvbn is not defined[Learn More]
jquery.strengthify.js:77:21
```
</details>

**Comment by violoncelloCH** [comment]
reproduced with current master

**Comment by rullzer** [comment]
This is fixed in 15.0.1

**Comment by aubreybox** [comment]
actually not for me:
15.0.4
with ldap

path:
/index.php/apps/user_ldap/renewpassword/$uuid

console (sorry for weird language settings - its a vm...):
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://cloud.physsolutions.org/core/vendor/zxcvbn/dist/zxcvbn.js blockiert ("script-src").

csp header:
default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-QTFONE9vZ1JwWjFMZlR4U2af521a563fwlpQ1VOU0hYVT06V1JZNVQ3Qll6NlV1U1hOajc5c0taNEpWN1dkYk5FVXZlTVZ6ZUFRcWRGND0=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self'


html:
<script defer="" src="/index.php/apps/accessibility/js/accessibility?v=0" nonce="QTFONE9vZ1JwWjFMZlR4U25PcDdCczh3Z1FGd1VuVlhMZllpQ1VOU0hYVT06V1JZNVQ3Qll6NlV1U1hOajc5c0taNEpWN1dkYk5FVXZlTVZ6ZUFRcWRGND0="></script>
but:
<script src="/core/vendor/zxcvbn/dist/zxcvbn.js"></script>


I guess that means that the nonce is not provided?

**Comment by aubreybox** [comment]
apps/user_ldap/js/renewPassword.js
$(document).ready(function() {
        $('form[name=renewpassword]').submit(OCA.LDAP.onRenewPassword);

        if($('#newPassword').length) {
                $('#newPassword').showPassword().keyup();
        }
        $('#newPassword').strengthify({
                zxcvbn: OC.linkTo('core','vendor/zxcvbn/dist/zxcvbn.js'),
                titles: [
                        t('core', 'Very weak password'),
                        t('core', 'Weak password'),
                        t('core', 'So-so password'),
                        t('core', 'Good password'),
                        t('core', 'Strong password')
                ],
                drawTitles: true,
                $addAfter: $('input[name="newPassword-clone"]'),
                nonce: btoa(OC.requestToken),
        });
});


alone doesnt seem to fix the issue
