### ISSUE TITLE
Tags are not shown when using external storage and LDAP auth

### ISSUE THREAD

**Issue by winvan** [nextcloud/server#13113]
### Steps to reproduce
1. Mount SMB external storage with option "Log-in credentials, save in session" or "Log-in credentials, save in database"
2. Assign a tag to file or folder as LDAP user who has permission to edit this file in NTFS ACL and in Nextcloud
3. Check file as other LDAP user who has similar permissions

### Expected behaviour
See a previously assigned tags

### Actual behaviour
No tags seed

### Server configuration

**Operating system**: 
Ubuntu 18.04 LTS 
Linux nextcloud 4.15.0-39-generic #42-Ubuntu SMP Tue Oct 23 15:48:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
nginx/1.14.0 (Ubuntu)

**Database:**
mysql  Ver 15.1 Distrib 10.3.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 (cli) (built: Nov 12 2018 09:55:44) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated manually from 14.0.4

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files
	- EXTRA_FILE
		- js/templates/detailsview.handlebars.js
		- .l10nignore
- files_versions
	- EXTRA_FILE
		- .l10nignore
		- download.php
		- ajax/rollbackVersion.php
		- ajax/getVersions.php
- oauth2
	- EXTRA_FILE
		- .l10nignore
- firstrunwizard
	- EXTRA_FILE
		- l10n/ia.js
		- l10n/es_AR.js
		- l10n/eu.js
		- l10n/eu.json
		- l10n/ca.js
		- l10n/ia.json
		- l10n/es_AR.json
		- l10n/ca.json
- notifications
	- EXTRA_FILE
		- .l10nignore
- updatenotification
	- EXTRA_FILE
		- .l10nignore
		- css/admin.css
- user_ldap
	- EXTRA_FILE
		- lib/User/IUserTools.php
- files_trashbin
	- EXTRA_FILE
		- ajax/delete.php
		- ajax/undelete.php
		- ajax/isEmpty.php
		- ajax/list.php
- twofactor_backupcodes
	- EXTRA_FILE
		- js/settingsview.js
- comments
	- EXTRA_FILE
		- .l10nignore

Raw output
==========
Array
(
    [files] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [js/templates/detailsview.handlebars.js] => Array
                        (
                            [expected] => 
                            [current] => e3d7b8cba00c6a4c619dd3a0b26b7b1cbbf19e2c59f88d0dbee640bcf62ede3a3cf9ecee35d4ad1b5ea221eef4d957ad88ddafc20a85f1ea054a036bc89923a4
                        )

                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 8c6094b721532810d5d1a801435e21ff733cea9dc4068fa45c18f6acd835db4a501dddc61f123d432194a676ae3504796152b3ef1075893df7f84ebc509ef606
                        )

                )

        )

    [files_versions] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 8c6094b721532810d5d1a801435e21ff733cea9dc4068fa45c18f6acd835db4a501dddc61f123d432194a676ae3504796152b3ef1075893df7f84ebc509ef606
                        )

                    [download.php] => Array
                        (
                            [expected] => 
                            [current] => 681e215fd1c4cba189abfe16739d30941fa129a74fa0b2215bd2d7f212fe4de4f0e0c5eab21d52015f2f81d4484141805634a88f322f16c4a08e422b83d3390e
                        )

                    [ajax/rollbackVersion.php] => Array
                        (
                            [expected] => 
                            [current] => 41a7b51f9103c0fa45f52ce718628fe08acc9f0712b0a481ec57274fd923b0ee57a63101e8b689fb711e90d438ecc7985640db9cfaf75992dc5bcf362fc3e896
                        )

                    [ajax/getVersions.php] => Array
                        (
                            [expected] => 
                            [current] => e319e4a31be63f017613538d3903fe0f1262173232996b3ddca7d1b1935d2db479810d4095ad98eeb9d47e4ebc2943273118c1da2f0c630f40365753a2ab1813
                        )

                )

        )

    [oauth2] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 92a31b53ec5ef0df43a997f08114a29ed4a5162f7f036ea12fbfdc250133a55059986d0e750e53613ef4488dc30b19f79529280e5ee8f716804d7d1b2b426b0b
                        )

                )

        )

    [firstrunwizard] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [l10n/ia.js] => Array
                        (
                            [expected] => 
                            [current] => e81ab84c98b5f88b34bbba364c17e660b717313ea4027abc6093a68791683dad46eac9bce14de6f717c6080515b1a564a9e50095766632ee633ad4baf522cd51
                        )

                    [l10n/es_AR.js] => Array
                        (
                            [expected] => 
                            [current] => 25761b0d112b4ed11cf42050e41ee1f9cd05abab4c7394c9f2aaef916ec0d62ee7faa24239520e2ebadfeecd3653806429daf4950aa32f17dc8dbcdf36717086
                        )

                    [l10n/eu.js] => Array
                        (
                            [expected] => 
                            [current] => beeb9c78f345f41372d1b15b8f67e43259861690b5ada5eb73a5524ade3e2c82d7684f3e90bab0aa7e10b98c8d1e3bf39c725cf2e7dcacf86d05b4dc6eb9c71e
                        )

                    [l10n/eu.json] => Array
                        (
                            [expected] => 
                            [current] => 7cfc610255d4333e03b4d7c3d1dd7fe7357499c467d57fecab381d3a850d16e46963b983aa5f33c3d966414bcd7dbdd336629ab06f3c7991b47e46dc51d591dc
                        )

                    [l10n/ca.js] => Array
                        (
                            [expected] => 
                            [current] => 8a0fa9f54e00c68d5b6dc7b1676170cf90714e6faf9a82367d883cfb2ca8d108b2161eccec3ad5ba607193d8b2ad3cbee2b9d84bdd1b6bc322c8da2b42a03ad0
                        )

                    [l10n/ia.json] => Array
                        (
                            [expected] => 
                            [current] => 170409127cfabcf4adc2323b8ddbe1252a28ef3be0ddb463f819017ffd3ecb82e6bd3577144333c572e903d805a37d6270477971f336a4aaf27d146b0afb5930
                        )

                    [l10n/es_AR.json] => Array
                        (
                            [expected] => 
                            [current] => 1dc3f720c04d5649f36423587d6a9d823751f672aa7796e779bd3380e5d66fe78160afd7f01e8a5ac973329e049e4a9febcc0388ae255809850dabdf358ef867
                        )

                    [l10n/ca.json] => Array
                        (
                            [expected] => 
                            [current] => 9d898c07c8a29811072e731de68994402a1525b070ccbc781c779e1d9faebe7bfcf29544e6fee6e4e3fb3598a9863f9ba4d0e7f36c609cd2d63f216a13459a86
                        )

                )

        )

    [notifications] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 1972e85572d629ef9173f000c6accd2e1030c35ad41101739c7eadac06c15bfdbae78a1049d792aa602667287e1f4714157b105b2dd736e9096926797b6ee5d3
                        )

                )

        )

    [updatenotification] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 0a3cef4a12a25342a75ae7a161b80164cb59b16fff2501df101963e1783d4036dd72c857e3e8707290a3f654701975d52cb05a0f1e5de49950b954604a169862
                        )

                    [css/admin.css] => Array
                        (
                            [expected] => 
                            [current] => d2bce02dd592b17a0caf0c0a01f2c5cd1144d36d70bdbce1475b736d53d2d01625a5d0feff3b3b9e228d2142be782095498f1115a1d0f27fcd870263f468718e
                        )

                )

        )

    [user_ldap] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/User/IUserTools.php] => Array
                        (
                            [expected] => 
                            [current] => 979bc99619d1f00ce39b6eb706b43b0bd6f0414142ef19aadb791643d3f2e16d400342c00831c3f286a61c265a21f19159b90ed7d1ab2f168e74a8eda7cdec3a
                        )

                )

        )

    [files_trashbin] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [ajax/delete.php] => Array
                        (
                            [expected] => 
                            [current] => ef800b0057cfe3103fc9d89d0af414e50ad37c6b35ee57008870ce1b0e7229d6dadf023aaa3a15fda8cd1902168631742bd4b035f1011747dad1b26c430aa76a
                        )

                    [ajax/undelete.php] => Array
                        (
                            [expected] => 
                            [current] => eab7ffd4627acc87c1952fa3a02c92698eeb1362371c4265c280417f2df70e18dc92dc56995f6f89b89287fe56fd1e3fa73cbdee75f666d4a8744369d598a934
                        )

                    [ajax/isEmpty.php] => Array
                        (
                            [expected] => 
                            [current] => 84048a5ad6e99bfad186c4e4706529b83dc6c378e9cd6e7588cdc2782f9e3bdc949a1d153682ed5db32d4279e3c750688d21b9a5bb466a787bc3a1992516ab80
                        )

                    [ajax/list.php] => Array
                        (
                            [expected] => 
                            [current] => 295298529fa2986fd65e6389ee3cf663324cbdc525aad735acce339a6da663be87fbd7bfcee7267dbd8e620fa9e614da752b7d4a42de23fe510ac946022247c3
                        )

                )

        )

    [twofactor_backupcodes] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [js/settingsview.js] => Array
                        (
                            [expected] => 
                            [current] => 7d199c7cb71c86103fed5e05a2795020aed02a3cca63950b2a382f73750d9646be00bebebe10b6a5570507fbe6bfb736ba2eb003095f74ed2126db06732a2ffa
                        )

                )

        )

    [comments] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.l10nignore] => Array
                        (
                            [expected] => 
                            [current] => 8c6094b721532810d5d1a801435e21ff733cea9dc4068fa45c18f6acd835db4a501dddc61f123d432194a676ae3504796152b3ef1075893df7f84ebc509ef606
                        )

                )

        )

)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.0
  - dav: 1.8.0
  - deck: 0.5.1
  - event_update_notification: 0.3.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_automatedtagging: 1.5.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.1
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.8.4
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - fulltextsearch: 1.2.1
  - fulltextsearch_elasticsearch: 1.2.1
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - metadata: 0.8.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - telephoneprovider: 1.0.2
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_notifications
  - bookmarks_fulltextsearch
  - checksum
  - circles
  - dashboard
  - encryption
  - federation
  - files_frommail
  - firstrunwizard
  - flowupload
  - group_everyone
  - ojsxc
  - richdocuments
  - socialsharing_email
  - survey_client
  - user_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.39.29",
            "cloud.its-sib.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "http:\/\/192.168.39.29",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "3",
        "logdateformat": "F d, Y H:i:s",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
localhost/nextcloud/oc_appconfig/		http://192.168.39.15/phpmyadmin/db_sql.php?db=nextcloud&token=3b0108fa57f24d4c52f0d58a9e17b994
 Отображение строк 0 - 24 (59 всего, Запрос занял 0.0009 сек.)

SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap'


appid	configkey	configvalue	
user_ldap	background_sync_interval	43200	
user_ldap	background_sync_offset	0	
user_ldap	background_sync_prefix	s01	
user_ldap	cleanUpJobOffset	0	
user_ldap	enabled	yes	
user_ldap	installed_version	1.5.0	
user_ldap	s01_lastChange	1545028210	
user_ldap	s01has_memberof_filter_support	1	
user_ldap	s01home_folder_naming_rule	attr:displayname	
user_ldap	s01last_jpegPhoto_lookup	0	
user_ldap	s01ldap_agent_password	
user_ldap	s01ldap_attributes_for_group_search		
user_ldap	s01ldap_attributes_for_user_search		
user_ldap	s01ldap_backup_host		
user_ldap	s01ldap_backup_port		
user_ldap	s01ldap_base	OU=Шоссейная 22,DC=mainoffice,DC=its-sib,DC=ru	
user_ldap	s01ldap_base_groups	OU=Шоссейная 22,DC=mainoffice,DC=its-sib,DC=ru	
user_ldap	s01ldap_base_users	OU=Шоссейная 22,DC=mainoffice,DC=its-sib,DC=ru	
user_ldap	s01ldap_cache_ttl	600	
user_ldap	s01ldap_configuration_active	1	
user_ldap	s01ldap_default_ppolicy_dn		
user_ldap	s01ldap_display_name	displayname	
user_ldap	s01ldap_dn	CN=test,CN=Users,DC=mainoffice,DC=its-sib,DC=ru	
user_ldap	s01ldap_dynamic_group_member_url		
user_ldap	s01ldap_email_attr	mail	

</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Henry-White** [comment]
Affirmative. Collaborative tagging functionality which shares tags among users do not works with SMB-shares. Even if you are using "Collaborative tags" (public), other users can see and use them but cannot see your public tags assignments.

**Comment by robinhoodhimself** [comment]
I have the same problem.  System Tags are not replicated to other users when applied on "External Storage".  You will not be able to use File Access Control with External Folders, 

I was able to fix this using direct query in the DB.  The bug is in the webui that is not taking into account external storage when you applied a system tag to an external folder.

This query will find id to root reference for external storage for all users that are allow to view this external storage. ( I know this SQL has shitty performance.  I should use join instead.  I'm still working on it.  ;-)  )

SELECT fileid FROM oc_filecache WHERE STORAGE IN (SELECT numeric_id from oc_storages where id IN (SELECT CONCAT ('smb::' , oc_external_applicable.VALUE, '@storageu1_r//zslux//') FROM oc_external_applicable WHERE mount_id = (SELECT mount_id FROM oc_external_mounts WHERE mount_point = '/ZSLux'))) AND path ='';

This query will insert the missing id into oc_systemtag_object_mapping.
INSERT INTO oc_systemtag_object_mapping VALUE('5781717','files',4);

I'm still working on those query to fix oc_systemtag_object_mapping in one pass....

**Comment by ploustoc** [comment]
I am having the same issue.
My files are referenced in the oc_systemtag_object_mapping :
select * from oc_systemtag_object_mapping;
+----------+------------+-------------+
| objectid | objecttype | systemtagid |
+----------+------------+-------------+
| 40787    | files      |           2 |
| 47628    | files      |           3 |
| 47631    | files      |           3 |
| 47703    | files      |           3 |
+----------+------------+-------------+
I am not sure where is the missing link.

**Comment by ploustoc** [comment]
can't edit my previous message.
My nextcloud version is 16.0.4
external storage support is 1.7.0
ldap user and group backend is 1.6.0

**Comment by ploustoc** [comment]
the same file from the same external storage with a different user gets a different file_id

**Comment by ploustoc** [comment]
So i have just been studying the database, not the external mounts code nor the tag code nor the group code. I don't know how to navigate among mounts, i have some file that are declared on a mount that doesn't exist at the time i run the query so i can't be sure the file_id is from the right storage (since each user reauthentificate on connect, i guess) but if you accept to define a public tag (let's say the tagid 3 being a objecttype files), that would makes the tag available even if the document is not public, you could run something like :
INSERT INTO oc_systemtag_object_mapping
VALUES (select fileid, "files", "3" FROM oc_filecache WHERE path IN (select PATH FROM oc_filecache WHERE fileid IN (select objectid from oc_systemtag_object_mapping where systemtagid=3)));

**Comment by ploustoc** [comment]
sorry still can't edit in this browser : here is the corrected query :
INSERT IGNORE INTO oc_systemtag_object_mapping ( objectid, objecttype, systemtagid )
    -> SELECT fileid, "files", "3"
    -> FROM oc_filecache
    -> WHERE path IN ( SELECT path
    ->                 FROM oc_filecache
    ->                 WHERE fileid IN ( SELECT objectid
    ->                                   FROM oc_systemtag_object_mapping
    ->                                   WHERE systemtagid=3
    ->                                   )
    ->                 );
Query OK, 9 rows affected, 5 warnings (0.76 sec)
Records: 14  Duplicates: 5  Warnings: 5

**Comment by skjnldsv** [comment]
Still occurring in 18?
