### ISSUE TITLE
Make Activity-Emails more predictable

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#13129]
Emails are sent either hourly, daily or weekly, based on the user preference. But there is no way of predicting when an email is sent out, it happens randomly through the day. It may be an option to give the user the ability to set a rough time in which he wants to recieve the email.  (hourly intervals, like 20:00 to 21:00)

This would allow the user to "review" the day if he chooses so

**Comment by hitam4450** [comment]
I feel the same way! I set the option to hourly, sometimes it takes days, until the activity mail is delivered including sometimes hundreds of messages.

**Comment by rullzer** [comment]
@hitam4450 then you probably need to setup a system cron job.

**Comment by nickvergessen** [comment]
This is possible since quite some time already:
https://docs.nextcloud.com/server/15/admin_manual/configuration_server/activity_configuration.html#better-scheduling-of-activity-emails
