### ISSUE TITLE
Nextcloud Collabora locked files

### ISSUE THREAD

**Issue by gaalos** [nextcloud/server#13136]
### Steps to reproduce
1. Open a file on your browser with word/libreoffice on CIFS TARGET
2. Open this same file with collabora online on nextcloud on CIFS TARGET

### Expected Behaviour
Collaborra  don't know if the file is locked by other program
When you want save collabora respond said "No write to save the file"
Because the file is locked on CIFS server

### Server configuration

**Operating system**:  Debian 9

**Web server:** Apache2

**Database:** Mariadb

**PHP version:** 7.0

**Nextcloud version:** 13

**Are you using external storage, if yes which one:**  CIFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

**Comment by skjnldsv** [comment]
Is this still happening? If so, please make sure to **upgrade** to the **latest** version, then, please update this ticket.
