### ISSUE TITLE
layout error in Chinese language

### ISSUE THREAD

**Issue by whisper1021** [nextcloud/server#13149]
### Steps to reproduce
When I switch to Chinese (zh_TW or zh_CN), the layout will display an error.
![image](https://github.com/whisper1021/demo/blob/master/error.png?raw=true)
![image](https://github.com/whisper1021/demo/blob/master/error3.png?raw=true)
When I use English or other language, no error:
![image](https://github.com/whisper1021/demo/blob/master/error2.png?raw=true)

### Server configuration

**Operating system**: Ubuntu 16.04.5

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page) 15.0.0

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 7 Pro

**Comment by violoncelloCH** [comment]
reproduced with current master

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for this UI glitch

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
