### ISSUE TITLE
PROPFIND Reply is not XML Formatted

### ISSUE THREAD

**Issue by sseneca** [nextcloud/server#13157]
### Steps to reproduce
1. Try to upload large amount of files/folders (1GB)

### Expected behaviour
All files and folders should be uploaded to the server

### Actual behaviour
After uploading some files (usually the majority, actually), I get `PROPFIND Reply is not XML Formatted` and the uploading stops.

### Server configuration

**Operating system**: Debian/Raspbian 9 stretch

**Web server:** Apache 2.4.25, with HTTP2 enabled

**Database:** MariaDB 10

**PHP version:** 7.2

**Nextcloud version:** 15 (happens on 14 as well)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Using [NextCloudPi](https://github.com/nextcloud/nextcloudpi)

**Signing status:**
```
No errors have been found.
```

**List of activated apps:**

```
- Accessibility
- Activity
- Calendar
- Collaborative tags
- Comments
- Contacts
- Deleted files
- Federation
- File sharing
- First run wizard
- Gallery
- Log reader
- Monitoring
- News
- Nextcloud announcements
- Notes
- Notifications
- Password policy
- PDF viewer
- Preview Generator
- Share by mail
- Support
- Tasks
- Text editor
- Themeing
- Update notification
- Usage survey
- Versions
- Video player
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
           ***REDACTED***
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "***REDACTED***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "loglevel": "2",
        "log_type": "file",
        "htaccess.RewriteBase": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:** local usb stick

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Arch Linux

**NC Client Version:** 2.5.1, 2.5. Happens with OC Client 2.5.1 as well

Related discussion on forums: https://help.nextcloud.com/t/propfind-reply-is-not-xml-formatted/

**Comment by alraban** [comment]
I see the same error with the 2.5.1 client and Nextcloud 14, although in my case it is not confined to large uploads: it also occurs with downloads of large numbers of files and directories (in the thousands).  

I see the above-described behavior during uploads (i.e. some files upload and then the client returns the error).  In the download case, however, the client returns the error during the scan for server-side changes, and then begins a new scan for changes from scratch.  This prevents the sync from ever completing because it starts over each time.  The error appears non-deterministically (i.e. it is not triggered by specific files or folders), but in my case will always eventually occur with large numbers of files needing to be synced.  

The issue does not occur with the nextcloud client version 2.3.3 using the same server and the same client systems.

**Comment by sseneca** [comment]
Yeah, I can confirm that using client version 2.3.3 along with NC 14 works fine.

**Comment by LukasSliacky** [comment]
Hm, i can't find 2.3.3 for Ubuntu 18.04 and when i can use OwnCloud client, i have problem with dependencies.
Please, have somebody experiences with install older clients on Ubuntu 18.04?

**Comment by sseneca** [comment]
> Please, have somebody experiences with install older clients on Ubuntu 18.04?

Have you tried [this](https://askubuntu.com/questions/138284/how-to-downgrade-a-package-via-apt-get)? I don't have access to a machine running Ubuntu but just search downgrading packages in Ubuntu online and you should find something.

**Comment by LukasSliacky** [comment]
Yes, but on Ubuntu 18.04 i have problem with dependencies. Maybe when it would be downgrade more packages will be installing okay. But i am afraid it would be more problems for my Ubuntu.

**Comment by AlexMV12** [comment]
I have the same problem with 2.5.1 and I can confirm that with a server with NC 15, the client version 2.3.3 doesn't have this problem.

**Comment by felipeespic** [comment]
I have exactly the same problem uploading 45GB.

**Comment by felipeespic** [comment]
@AlexMV12 
> Yes, but on Ubuntu 18.04 i have problem with dependencies. Maybe when it would be downgrade more packages will be installing okay. But i am afraid it would be more problems for my Ubuntu.

It worked for me by installing this [library](https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client/+build/14764047/+files/libnextcloudsync0_2.3.3-20180415.190957~artful1_amd64.deb), and then this [Nextcloud client]( https://launchpad.net/~nextcloud-devs/+archive/ubuntu/client/+build/14764047/+files/nextcloud-client_2.3.3-20180415.190957~artful1_amd64.deb) by the command ```sudo apt install <package>.deb ```
That shouldn't affect your Ubuntu install.

**Comment by LukasSliacky** [comment]
@felipeespic Man, it works great! 
Really thanks for your hint.

**Comment by Bleuzen** [comment]
Since downgrading the client works, maybe this is not a server bug, but something client side? Should we open an issue on the desktop client repo here on GitHub?

**Comment by jdefoe2** [comment]
Hello, I'm really happy to have found this thread. I recently set up NextCloudPlus on a Raspberry Pi 3B and was having this (and several other) errors when trying to sync a large amount of data (~280GB, ~200,000 files) from a Linux client (Ubuntu 18.04) running the NextCloud 2.5.1 client. Installing the older library/client and running that instead seems to have solved the problem -- at least the sync is starting without issue. I will post an update if I run into any trouble. Seems like it's definitely a client-side problem!

**Comment by danielkesselberg** [comment]
cc @rullzer @camilasan

**Comment by sseneca** [comment]
> Since downgrading the client works, maybe this is not a server bug, but something client side? Should we open an issue on the desktop client repo here on GitHub?

**Comment by sseneca** [comment]
I've opened an issue on the client repo: https://github.com/nextcloud/desktop/issues/1025

**Comment by TuxyMarc** [comment]
Hello all,
In my case, it was a server problem.
I have solved this problem “PROPFIND Reply is not XML Formatted” by replacing NextcloudPi by a clean install of Raspbian and Nextcloud. Now, It works like a charm.
Don't forget to modify the php.ini to increase the upload_max_filesize.

**Comment by mamojdick** [comment]
> upload_max_filesize

what value did you put?

**Comment by TuxyMarc** [comment]
> what value did you put?

1024M

**Comment by SirBoxBoxington** [comment]
> Hm, i can't find 2.3.3 for Ubuntu 18.04 and when i can use OwnCloud client, i have problem with dependencies.
> Please, have somebody experiences with install older clients on Ubuntu 18.04?

I solved this issue (as well as /nextcloud/desktop/issues/908 ) for me on Ubuntu 18.04 by using the 2.3.3 appimage : https://download.nextcloud.com/desktop/releases/Linux/Nextcloud-2.3.3-x86_64.AppImage
