### ISSUE TITLE
Saving KeePass Database in Nextcloud WebDAV mount on Windows 10 fails

### ISSUE THREAD

**Issue by djermann** [nextcloud/server#13159]
### Steps to reproduce
1. Mount Nextcloud via WebDAV on Windows 10
2. Create a new KeePass Database and save it somewhere inside the WebDAV mount.
3. Modify the KeePass Database (e.g. create a new entry)
4. Save the KeePass Database.

### Expected behaviour
The KeePass Database should get saved.

### Actual behaviour
The following error appears:
![keepass_error](https://user-images.githubusercontent.com/20949681/50219956-235dc580-0391-11e9-893c-6833380910a5.png)

When I close KeePass after that and reopen the KeePass Database, the modifications from step 3 do not reappear.

### Server configuration

**Operating system**: Debian

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 13.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 13.0.5

**Where did you install Nextcloud from:** tar file from the website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:** -

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing spezial found in web server log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing special found in Nextcloud log
```
</details>

**Comment by skjnldsv** [comment]
I'm suggesting you start using the nextcloud desktop client instead please.
Webdav mount on windows is known to create issues :)
