### ISSUE TITLE
I can't login to my Nextcloud server using the desktop client

### ISSUE THREAD

**Issue by DanielNNN** [nextcloud/server#13176]
I installed Nextcloud on my server to this address:
https://artlab.co.il/nextcloud

And I can easily access it via browser, but when I try to login via the desktop client, it produces a 404 error:

![image](https://user-images.githubusercontent.com/30571647/50288104-90df2400-046d-11e9-9b81-57a17b585299.png)

How can this be resolved?

Thank you
Daniel

**Comment by Nils160988** [comment]
There is more information needed to help you with this issue. Can you use the issue template for that?

btw, I can not access your login-screen following the link you provided. Are you sure this is the correct address?

**Comment by stratege1401** [comment]
just tried your link, and i get

OOPS. THE PAGE YOU WERE LOOKING FOR DOESN'T EXISTS.
You may have mistyped the address or the page may have moved.


i am thinking of a missled configuration for your server

**Comment by DanielNNN** [comment]
Hi guys

Apparently, the URL is case sensitive and the install directory had a capital N (as in Nextcloud). My bad.
The correct URL is https://www.artlab.co.il/nextcloud/, but going there now suddenly produces:

![image](https://user-images.githubusercontent.com/30571647/50329473-23c89e80-0500-11e9-9bfd-9b0d0904112a.png)

Trying to login via the client produces an error '400 Bad Request':
![image](https://user-images.githubusercontent.com/30571647/50329523-54103d00-0500-11e9-9069-14b330e24dcc.png)

Please help..
Thank you!

**Comment by DanielNNN** [comment]
> There is more information needed to help you with this issue. Can you use the issue template for that?
@Nils160988 - can you point me please to the issue template?

**Comment by Nils160988** [comment]
The issue template shows up automatically when you report a bug (at least, that is, how it works for me)

On the issue itself: Did you try adding "www.artlab.co.il" to your trusted domains? If I try to access "artlab.co.il" it works but "www.artlab.co.il" doesn't...

**Comment by DanielNNN** [comment]
This did the trick :+1: 
Thanks @Nils160988
