### ISSUE TITLE
Theming app should allow the Slogan color to be changed.

### ISSUE THREAD

**Issue by rlitman** [nextcloud/server#13181]
The Theming app (I am running Theming 1.6.0 on Nextcloud 15.0.0) displays a custom Slogan on the login screen, but when a dark Login image is chosen, the black text is unreadable.

![capture](https://user-images.githubusercontent.com/21064159/50294186-5791be80-0443-11e9-8085-30035dad8692.PNG)

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@rlitman what is the primary color of your theming? The text color is based on that, being dark when the primary color is light.

Also, do you have the dark theme enabled?

**Comment by rlitman** [comment]
That makes some sense.  I have the color set to #32F1F2.
At the log in screen, the button shows "Log in" in black text over the primary teal color, but switches to white text (still with a black arrow) when I mouse over.  Below, that "Forgot password?" is in white text.  I've attached a less cropped capture of my login screen for clarity.
![capture](https://user-images.githubusercontent.com/21064159/52582799-0e833880-2dfc-11e9-8975-991f80644a1e.PNG)

**Comment by jancborchardt** [comment]
Hm, the slogan should definitely be displayed in the same color (white) as the "Forgot password" element. @juliushaertl @skjnldsv any idea?

**Comment by skjnldsv** [comment]
Well, it will works ok on dark background, but not on bright ones.
The slogan needs to have something done indeed, but adapting to the primary color does not seems to be the proper thing :thinking: :woman_shrugging:

**Comment by jancborchardt** [comment]
Might be too much magic, but is it possible to check what color the background is and change accordingly?

**Comment by skjnldsv** [comment]
> but is it possible to check what color the background is and change accordingly?

No because the background could be white on top but black on the bottom, and we cannot extract the color under the slogan as the bg position depends on your screen resolution :/

**Comment by juliushaertl** [comment]
I'd say this is actually a good use case for the theming_customcss app, the defaults don't fit well fot every background image and we cannot detect that automatically. Also I don't think we should add another color setting as this will clutter the options got a rather small use case.

**Comment by jancborchardt** [comment]
@juliushaertl good call!
