### ISSUE TITLE
Device & Session List is excessively long

### ISSUE THREAD

**Issue by Wizlonex** [nextcloud/server#13182]
### Steps to reproduce
1.  Connect a webdav client to Nextcloud, make sure the correct syntax and credentials are used
2.
3.

### Expected behaviour
IN the portal under user-->settings-->security, you should see a reasonable list of 'recent connections' under 'Devise & sessions'

### Actual behaviour
It lists EVERY connection, so if you are syncing files via a cron event, you can get a log that looks like this after just a day (see attached file)

### Server configuration
**Operating system**:
Ubuntu 16.04
**Web server:**
Apache
**Database:**
Maria
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14
**Updated from an older Nextcloud/ownCloud or fresh install:**
This is a fresh pre-production install (evaluating and checking it out)

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
[log.txt](https://github.com/nextcloud/server/files/2699807/log.txt)
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
Well it lists the sessions. And since your webdav client probably creates a new session every time the behavior is actually correct.

Try using apppasswords.

**Comment by Wizlonex** [comment]
> Well it lists the sessions. And since your webdav client probably creates a new session every time the behavior is actually correct.
> 
> Try using apppasswords.

I will do.  Funny thing is, I only noticed this as I went to enable 2FA.  But even so, the list should not be endless - maybe put it in a window, or list the most recent X with an option to view more, etc.  Hardly a big deal of course.  Thanks for the app-pw tip.

**Comment by inventionate** [comment]
I have observed that an entry is also created for each OAuth2 client session. For instance, if you log in to Moodle with an existing Nextcloud account using Nextcloud as OAuth2 Provider. I don't think that's a good solution. Isn't it possible to include the expired OAuth sessions in the cleanup CRON job?

**Comment by skjnldsv** [comment]
> I have observed that an entry is also created for each OAuth2 client session.

Seems related to #12377
