### ISSUE TITLE
Not sync files with blanks

### ISSUE THREAD

**Issue by txsastre** [nextcloud/server#13208]
When copying files from shared Windows folder to a nextcloud folder on a linux system they are copied but not moved to the server.

If i put a file with no blanks where the file with blanks is, then all the files are uploaded to the server.

May be is a client problem

Nextcloud 15.0

**Comment by ChristophWurst** [comment]
Please follow the template at https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md.

**Comment by MorrisJobke** [comment]
May be solved by #13468 and due to no feedback I will close this for now.
