### ISSUE TITLE
Use webpack+handlebars-loader for the Handlebars precompilation

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13205]
**Is your feature request related to a problem? Please describe.**
The strict CSP in Nextcloud 15 forced us to precompile our templates. Currently this happens through a custom script.

**Describe the solution you'd like**
Use webpack and the handlebars-loader to precompile and package templates with the server bundle. This will keep all the building in one place and replaces our custom script with a de facto standard tool for this task.

**Describe alternatives you've considered**
Don't change this.

**Additional context**
- [x] Requires https://github.com/nextcloud/server/pull/13156

cc @nextcloud/javascript @rullzer

**Comment by MorrisJobke** [comment]
> * [x]  Requires #13156

This is in now.

Still doable for 16 or something for 17?

**Comment by rullzer** [comment]
Some is done for 16 rest we'll tackle in 17.

**Comment by ChristophWurst** [comment]
I assume this will slowly fade away as more stuff is written in Vue. Files is possibly the only subsystem that heavily makes use of Handlebars templates.

**Comment by susnux** [comment]
There are only two places left:
- legacy files (public share)
- external storage settings
