### ISSUE TITLE
Evaluate need for jsTimezoneDetect

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#13214]
We use jsTimezoneDetect to get the timezone of a user. But I guess momentjs has these capabilities as well.

**Comment by weeman1337** [comment]
Both libs are utilizing the internationalization API in the first place with some fallback:
- http://momentjs.com/timezone/docs/#/using-timezones/guessing-user-timezone/
- https://bitbucket.org/pellepim/jstimezonedetect/src/77effaefe1d26be9f2ddffab82a1d2bc112fb0b4/jstz.main.js?at=default&fileviewer=file-view-default#jstz.main.js-388

So a replacement should be possible (imho).

**Comment by rullzer** [comment]
It is deprecated now so apps should ship their own.
