### ISSUE TITLE
Override UUID not working with objectSid

### ISSUE THREAD

**Issue by flotpg** [nextcloud/server#13221]
### Steps to reproduce
1. go to expert tab in LDAP config
2. choose objectSid as internal username & override UUID detection
3. user list is not populated
4. choose any other **short** attribute like userPrincipalName, sAMAccountName, etc as internal username & override UUID detection
3. user list **is populated**

### Expected behaviour
- user list should be populated with AD/LDAP users and objectSid values of LDAP should be used as user name like S-1-5-21-3549537270-817667619-xxxxx-xxxxxxxx

### Actual behaviour
Nothing happens, user list stays empty

### Server configuration
Ubuntu 18.04 / Apache, PHP 7.2

This happens in NC14, 15, any build up to date...

It's impossible for me at the moment to match SAML users with users from local-AD because their UPNs sometimes differ in terms of upper and lowercase characters in username. The problem here is, that the user_ldap populates the **oc_ldap_user_mapping** table with upper & lower case UserNaMeS - i think this is not necessary because when trying to login with LDAP it sanitizes it anyway and doesn't care / checks username on case sensitivity ...

Any suggestions? Help appreciated...

Best Regards, Flo.

**Comment by skjnldsv** [comment]
cc @blizzz

**Comment by blizzz** [comment]
objectSid contains a binary value that first needs to be transcoded to a string representation (as we do with objectGuid: https://github.com/nextcloud/server/blob/master/apps/user_ldap/lib/Access.php#L1776).

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by blizzz** [comment]
was implemented end of 2020 https://github.com/nextcloud/user_saml/pull/486

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
