### ISSUE TITLE
15.0.0 #filedrop uploaded filenames are not shown in the filelist

### ISSUE THREAD

**Issue by JSoko** [nextcloud/server#13226]
### Steps to reproduce
1. Upload a file to the filedrop

### Expected behaviour
After Uploading the filename should be shown in the filelist

### Actual behaviour
It' only shows "Uploaded files:" but no Filenames
![grafik](https://user-images.githubusercontent.com/5583290/50355283-7a5cc980-054e-11e9-9bfc-19ed43eb910e.png)

### Server configuration

**Operating system**:
 Ubuntu 18.04.1 LTS
**Web server:**
Apache2
**Database:**
Mariadb
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
15.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - bookmarks: 0.14.3
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.0
  - data_request: 1.2.0
  - dav: 1.8.0
  - deck: 0.5.2
  - drop_account: 0.0.13
  - event_update_notification: 0.3.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_linkeditor: 1.0.9
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ownbackup: 18.11.0
  - password_policy: 1.5.0
  - piwik: 0.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - radio: 0.6.4
  - ransomware_detection: 0.4.2
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.3.0
  - spreed: 5.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - telephoneprovider: 1.0.2
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_usage_report: 1.1.1
  - w2g2: 2.2.4
  - workflowengine: 1.5.0
Disabled:
  - carnet
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - terms_of_service
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

    "system": {
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "integrity.check.disabled": false,
        "overwrite.cli.url": "https:\/\/*******\/",
        "default_language": "de_DE",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "simpleSignUpLink.shown": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": "10485760",
        "activity_expire_days": 33,
        "trusted_domains": [
            "localhost",
            "192.168.1.234",
            "o*******",
            "o********"
        ],
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto, 10",
        "versions_retention_obligation": "auto, 21",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": 500,
        "preview_max_y": 500,
        "preview_max_scale_factor": 10,
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "updater.release.channel": "production",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
chrome and firefox
**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

no entries

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

no related entries
</details>

#### Browser log
<details>
<summary>Browser log</summary>
JQMIGRATE: Migrate is installed, version 1.4.0
core.js?v=908cc6f9-227:4 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

</details>

**Comment by t0ny2** [comment]
This appears to have been caused by commit e0ab290 removing the unordered list html tags from `apps/files_sharing/templates/public.ph`

**Comment by weeman1337** [comment]
> by commit e0ab290 removing the unordered list html tags

Jep - they looked quite useless :) I'll put them back with some comment and or id.

**Comment by JSoko** [comment]
https://github.com/nextcloud/server/pull/13286
Fixes this issue! :-)
