### ISSUE TITLE
Error deleting multiple files from Deleted files with NextCloud 15.0.0.10

### ISSUE THREAD

**Issue by Libre4IT** [nextcloud/server#13232]
### Steps to reproduce
1. Go to Files and click 'Deleted files'
2. Select multiple files
3. Click on the triple dots 'Actions' 
4. Click 'Delete'

### Expected behaviour
Selected files shall be deleted

### Actual behaviour
Error shows 'Error while removing files from trashbin'
Of the selected files only one file is being deleted. 

### Server configuration

**Operating system**:
Arch linux, kernel 4.19.8

**Web server:**
Apache 2.4.37

**Database:**
Mariadb 10.1.37

**PHP version:**
PHP 7.3.0

**Nextcloud version:** (see Nextcloud admin page)
NextCloud 15.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from latest version

**Where did you install Nextcloud from:**
Arch linux package repository

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- ocs/.rnd
		- .rnd

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [ocs/.rnd] => Array
                        (
                            [expected] => 
                            [current] => 53379c25bc5d27655048e9c27dad56254a859a95db527e4a7c230c416331f116f50f292097b1cc24841179c2c67ec047a8488aa17be63db910447b2d58ba1e62
                        )

                    [.rnd] => Array
                        (
                            [expected] => 
                            [current] => eccb3e406ecc10541a2411aa233cc361bd5db68a94b6b2194ac3a415b3fabf1393b69028c5f52263100c04a77bd3188e9be9a3c5afb4cde34ee2030d4ff69d2b
                        )

                )

        )

)

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

PHP Warning:  require_once(): open_basedir restriction in effect. File(/<path hidden for privacy>/console.php) is not within the allowed path(s): (/dev/urandom) in /<path hidden for privacy/nextcloud/occ on line 11
PHP Warning:  require_once(/<path hidden for privacy>/console.php): failed to open stream: Operation not permitted in /<path hidden for privacy/occ on line 11
PHP Fatal error:  require_once(): Failed opening required '/<path hidden for privacy>/console.php' (include_path='.:') in /<path hidden for privacy>/occ on line 11

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
Unable to run occ command. See item above. Config.php content: 
<?php
$CONFIG = array (
  'instanceid' => '<hidden>',
  'passwordsalt' => '<hidden>',
  'secret' => '<hidden>',
  'trusted_domains' => 
  array (
    0 => '<hidden>',
    1 => '<hidden>.nl',
    2 => '127.0.0.1',
  ),
  'datadirectory' => '<hidden>/data',
  'overwrite.cli.url' => 'https:<hidden>/nextcloud/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'dbtype' => 'mysql',
  'version' => '15.0.0.10',
  'dbname' => '<hidden>',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<hidden>',
  'dbpassword' => '<hidden>',
  'logtimezone' => 'UTC',
  'installed' => true,
  'appstore.experimental.enabled' => true,
  'mail_from_address' => '<hidden>',
  'mail_smtpmode' => '<hidden>',
  'mail_domain' => '<hidden>',
  'mail_smtpsecure' => 'tls',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '<hidden>',
  'mail_smtpport' => '<hidden>',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Not applicable

### Client configuration
Mozilla Firefox 64.0 (64-bit)

**Operating system:**
Arch linux 

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Libre4IT** [comment]
Fixed the issue by deleting the trashbin using the occ command. After this multiple files can be deleted at once by using the browser as usual. Apparently something didn't went ok after the upgrade to NC 15.0.0. 
Please note that during the upgrade the occ command did not work for me (patch of NC wasn't part of open_basedir of php.ini).

**Comment by johnjgsmith** [comment]
I've got the same issue. When clicking the "deleted files" link in the browser it's just hanging and nothing happens. Though it can be fixed with OCC, it's still an issue that needs to looked into.
Disabling and re-enabling the "Deleted Files" plugin, doesn't make a difference.

**Comment by johnjgsmith** [comment]
If more people can confirm this issue, it should be re-opened. 
I'm using Nextcloud 15.0 on Ubuntu 16.04 LTS

**Comment by johnjgsmith** [comment]
Update: there was also a problem with the occ command:

# sudo -u www-data php occ trashbin:cleanup myusername
Cannot write into "config" directory!

Changed the data ownership to www-data, and then the above occ command worked.

Bin empty, and problem solved.

**Comment by algarih** [comment]
i have the same issue.. some parts of the selected files will not be deleted, then you have to reload the page and select multiple files and delete and redo this process until the files are deleted. that is how i managed to delete multiple files

**Comment by johnjgsmith** [comment]
@libre4IT can you please reopen this issue?

**Comment by Libre4IT** [comment]
Reopened uppon request

**Comment by Peac** [comment]
Same here on 15.0.4.

Issue is not solved be the mentioned command. It just empties the trash bin, but I can also do that by select all files in the trash and delete it. Multiselect and delete is still not working afterwards.

The sorting of the files is also strange for me as mentioned by @GoetheG

**Comment by kesselb** [comment]
If you still see this issue please create a new issue https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md. We need the issue template to reproduce your issue.
