### ISSUE TITLE
2FA with Nextcloud app in NC15 not as stable as in NC14

### ISSUE THREAD

**Issue by fankijo** [nextcloud/server#13235]
### Steps to reproduce
1. fresh NC15 Installation
2. Install and enable app for 2FA with Nextcloud App
3. log of and on again and wait for Notification

### Expected behaviour
On my phone there should be an Android notification as soon as I try to log in, which worked with NC14.

### Actual behaviour
I have to open the app, go to Notification section and have to allow my login there.

### Server configuration

**Operating system**: Ubuntu Server 16.04 LTS
**Web server:** Apache2
**Database:** Mysql
**PHP version:** 7.3
**Nextcloud version:** 15.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by salsysd** [comment]
ya is anyone else having webdav or caldav issues now with NC15 and 2FA enabled?

**Comment by salsysd** [comment]
nevermind I figured it out... just had to create device credentials

**Comment by j-ed** [comment]
This is a Nextcloud Android app problem and not a Nextcloud server problem, isn't it? I would have expected to get this issue opened under the repository https://github.com/nextcloud/android.

**Comment by rullzer** [comment]
This sounds like a temp hiccup with the push proxy. I just tried this again and it works here. Please try again

**Comment by fankijo** [comment]
Works.
