### ISSUE TITLE
can't download video on any browser

### ISSUE THREAD

**Issue by aohanhongzhi** [nextcloud/server#13230]
I can play video on any browser ,but I can't download it .however I can download and play video by android app.

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
