### ISSUE TITLE
link in security & setup warning is wrong

### ISSUE THREAD

**Issue by koppd** [nextcloud/server#13233]
### Steps to reproduce
1. Upgrade to NC 15
2. go to the admin->overview page where the security & setup warning messages are
3. There are some warning messages and one of them is about missing indices (like executing of "occ db: convert-filecache-bigint")
4. Some links are leading to the wrong page

### Expected behaviour

The warning text refers to some pages:
1. Link to a discussion site:
In German: "Diese Operation muss ausgeführt werden, während die Instanz offline ist. Weitere Einzelheiten findest Du auf der zugehörigen *Dokumentationsseite*."
Wrong Link: https://docs.nextcloud.com/server/14/go.php?to=admin-bigint-conversion
Better Link: https://docs.nextcloud.com/server/15/admin_manual/configuration_database/bigint_identifiers.html

2. Link to installation site:
In German: "Bitte überprüfen Sie noch einmal die *Installationsanleitungen* und kontrollieren Sie das Protokoll auf mögliche Fehler oder Warnungen."
Wrong link: https://docs.nextcloud.com/server/14/go.php?to=admin-install
Better link: https://docs.nextcloud.com/server/15/admin_manual/maintenance/upgrade.html#upgrading-to-nextcloud-13

PS: maybe only the German translation is affected. I couldn't test it anymore.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
OpenSUSE Tumbleweed 20181213
**Web server:**
Apache
**Database:**
mysql
**PHP version:**
7.2.12
**Nextcloud version:** (see Nextcloud admin page)
NC 15.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.x
**Where did you install Nextcloud from:**
from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by danielkesselberg** [comment]
Thank you for reporting :+1: 

https://github.com/nextcloud/server/pull/12963 (changed 14 to 15)
https://github.com/nextcloud/documentation/pull/1115 (add missing redirect for `admin-bigint-conversion`)

I'm not sure about the second one link to the admin manual looks right to me in this case.
