### ISSUE TITLE
[NC14]: Update backup fails

### ISSUE THREAD

**Issue by MBfromOK** [nextcloud/server#13241]
### Steps to reproduce
1. Receive notification that a new update is available
    "A new version is available: Nextcloud 14.0.4"
2. Review notification to verify that all active apps are compatible:
    "All apps have an update for this version available"
3. Go to settings
2. Overview
3. Open Updater

### Expected behaviour
NextCloud Auto Updater performs all action to update from my current version to the most recent version

### Actual behaviour
Auto updater "successfully" performs the following steps:
1. Initializes
2. Check for expected files
3. Check for write permissions

Then **Fails** to perform a successful backup:

- **Error(s):**
    Could not copy "/var/www/nextcloud/apps/mindmaps/css/vendor/vis/vis.min_css.old" to "/mnt/cloudpool/updater-ocxgjw80ihlh/backups/nextcloud-14.0.1.1/apps/mindmaps/css/vendor/vis/vis.min_css.old". Source /var/www/nextcloud/apps/mindmaps/css/vendor/vis/vis.min_css.old is not readable. Destination /mnt/cloudpool/updater-ocxgjw80ihlh/backups/nextcloud-14.0.1.1/apps/mindmaps/css/vendor/vis/vis.min_css.old is not writable
- Backup folder for this version (14.0.1.1) sets 0750 folder permissions with 0644 file permissions (previous backup for version 14.0.0.19 has 0755 for all files & folders)

### Server configuration

**Server OS:** Debian 9.5 via ProxMox
**Web Server:** Apache 2.4.25
**Database:** MySQL 10.1.26
**PHP:** 7.1.22
**NextCloud Server:** 14.0.1 - 14.0.4 Update being attempted.
**Updated from an older NextCloud/ownCloud or fresh install:** New
**Where did you install NextCloud from:** zip download, nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>
    No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>Enabled App list</summary>

- accessibility: 1.0.1
- activity: 2.7.0
- audioplayer: 2.5.1
- bruteforcesettings: 1.3.0
- cloud_federation_api: 0.0.1
- comments: 1.4.0
- dav: 1.6.0
- drawio: 0.9.1
- federatedfilesharing: 1.4.0
- federation: 1.4.0
- files: 1.9.0
- files_pdfviewer: 1.3.2
- files_sharing: 1.6.2
- files_texteditor: 2.6.0
- files_trashbin: 1.4.1
- files_versions: 1.7.1
- files_videoplayer: 1.3.0
- firstrunwizard: 2.3.0
- gallery: 18.1.0
- groupfolders: 2.0.2
- issuetemplate: 0.4.0
- logreader: 2.0.0
- lookup_server_connector: 1.2.0
- mindmaps: 0.1.0
- music: 0.9.3
- nextcloud_announcements: 1.3.0
- notifications: 2.2.1
- oauth2: 1.2.1
- password_policy: 1.4.0
- provisioning_api: 1.4.0
- radio: 0.6.4
- serverinfo: 1.4.0
- sharebymail: 1.4.0
- support: 1.0.0
- survey_client: 1.2.0
- systemtags: 1.4.0
- theming: 1.5.0
- twofactor_backupcodes: 1.3.1
- unsplash: 1.1.3
- updatenotification: 1.4.1
- workflowengine: 1.4.0
</details>
<details>
<Summary>Disabled apps list</summary>

Disabled:
- admin_audit
- encryption
- files_downloadactivity
- files_external
- user_external
- user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mycloud.beaslnet.local",
            "beaslnet.local",
            "10.2.6.4"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "skeletondirectory": "",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "overwrite.cli.url": "http:\/\/mycloud.beaslnet.local",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "data-fingerprint": "341f1f396cca8acd4f3d545c1f7a91c7",
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**Google Chrome: 71.0.3578.98

**Operating system:** Win 10 Pro (1803) 17134.472

#### Web server error log
<details>
<summary>Web server error log</summary>

[Sun Dec 23 06:25:11.722781 2018] [http2:warn] [pid 633] AH10034: The mpm module (prefork.c) is not supported by mod_http2. The mpm determines how things are processed in your server. HTTP/2 has more demands in this regard and the currently selected mpm will just not do. This is an advisory warning. Your server will continue to work, but the HTTP/2 protocol will be inactive.
[Sun Dec 23 06:25:12.268141 2018] [mpm_prefork:notice] [pid 633] AH00163: Apache/2.4.25 (Debian) OpenSSL/1.0.2l configured -- resuming normal operations
[Sun Dec 23 06:25:12.268195 2018] [core:notice] [pid 633] AH00094: Command line: '/usr/sbin/apache2'
[Sun Dec 23 13:54:41.370184 2018] [php7:warn] [pid 13829] [client 10.2.6.20:63948] PHP Warning:  copy(/var/www/nextcloud/apps/mindmaps/css/vendor/vis/vis.min_css.old): failed to open stream: Permission denied in /var/www/nextcloud/updater/index.php on line 502

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

3x failed login attempts
</details>

**Comment by violoncelloCH** [comment]
This is a configuration issue.
Please refer to the documentation (https://docs.nextcloud.com) or to the support forum (https://help.nextcloud.com) for this kind of questions.
(you need to change the permissions for the nextcloud directory to the webserver user (probably `www-data`)

**Comment by MBfromOK** [comment]
> 
> 
> This is a configuration issue.
> Please refer to the documentation (https://docs.nextcloud.com) or to the support forum (https://help.nextcloud.com) for this kind of questions.
> (you need to change the permissions for the nextcloud directory to the webserver user (probably `www-data`)

Would you be referring to the folder with the recorded write permission issue (the data directory) or the www folder?

I checked the owner and permissions and don't see anything wrong, I tried to edit the update.php to set the upgrade backup folder permissions to 0755, but something else is immediately re-resetting it to 750.  Hence this bug report.

<details>
<summary>Folder permissions - /var/www/nextcloud/:</summary>
drwxr-xr-x 14 www-data www-data  4096 Oct  4 23:19 .
drwxr-xr-x  5 root     root      4096 Oct  4 23:50 ..
-rw-r--r--  1 www-data www-data  3953 Oct  4 23:19 .htaccess
-rw-r--r--  1 www-data www-data   163 Oct  4 23:19 .user.ini
drwxr-xr-x 33 www-data www-data  4096 Oct  4 23:19 3rdparty
-rw-r--r--  1 www-data www-data 12063 Oct  4 23:19 AUTHORS
drwxrwx--- 49 www-data www-data  4096 Dec 23 13:59 apps
drwxrwx---  2 www-data www-data  4096 Oct  4 23:19 config
-rw-r--r--  1 www-data www-data  3650 Oct  4 23:19 console.php
drwxr-xr-x 18 www-data www-data  4096 Oct  4 23:19 core
-rw-r--r--  1 www-data www-data  4979 Oct  4 23:19 cron.php
-rw-r--r--  1 www-data www-data   179 Oct  4 23:19 index.html
-rw-r--r--  1 www-data www-data  3171 Oct  4 23:19 index.php
drwxr-xr-x  6 www-data www-data  4096 Oct  4 23:19 lib
-rw-r--r--  1 www-data www-data   283 Oct  4 23:19 occ
drwxr-xr-x  2 www-data www-data  4096 Oct  4 23:19 ocm-provider
drwxr-xr-x  2 www-data www-data  4096 Oct  4 23:19 ocs
drwxr-xr-x  2 www-data www-data  4096 Oct  4 23:19 ocs-provider
-rw-r--r--  1 www-data www-data  2971 Oct  4 23:19 public.php
-rw-r--r--  1 www-data www-data  5139 Oct  4 23:19 remote.php
drwxr-xr-x  4 www-data www-data  4096 Oct  4 23:19 resources
-rw-r--r--  1 www-data www-data    26 Oct  4 23:19 robots.txt
drwxr-xr-x 13 www-data www-data  4096 Oct  4 23:19 settings
-rw-r--r--  1 www-data www-data  2232 Oct  4 23:19 status.php
drwxrwx---  3 www-data www-data  4096 Oct  4 23:19 themes
drwxrwx---  2 www-data www-data  4096 Oct  4 22:25 updater
-rw-r--r--  1 www-data www-data   362 Oct  4 23:19 version.php
</details>

<details>
<summary>Folder permissions - /mnt/cloudpool/:</summary>
drwxr-x--- 8 www-data www-data     4096 Oct 13 19:33 .
drwxr-xr-x 7 root     root         4096 Sep 17 22:08 ..
-rw-r----- 1 root     www-data      324 Oct  3 19:36 .htaccess
-rw-r----- 1 www-data www-data        0 Oct  4 23:19 .ocdata
drwxr-xr-x 7 www-data www-data     4096 Oct  3 19:57 __groupfolders
drwxr-xr-x 5 www-data www-data     4096 Oct 13 19:21 appdata_ocxgjw80ihlh
drwxr-xr-x 4 www-data www-data     4096 Oct  3 19:37 cladmin
drwxr-xr-x 2 root     root         4096 Sep 29 13:11 dump
drwxr-xr-x 2 www-data www-data     4096 Oct  4 23:19 files_external
drwxr-xr-x 5 root     root         4096 Sep 16 16:18 images
-rw-r----- 1 www-data www-data        0 Oct  4 23:19 index.html
drwxr-xr-x 4 www-data www-data     4096 Oct 13 12:26 kaitlin
drwx------ 2 www-data www-data    16384 Aug  5 20:57 lost+found
drwxr-xr-x 5 www-data www-data     4096 Oct  4 18:38 micah
-rw-r----- 1 www-data www-data 21982154 Dec 22 13:44 nextcloud.log
drwxr-xr-x 2 www-data www-data     4096 Aug  8 19:35 private
drwxr-xr-x 3 www-data www-data     4096 Oct 13 19:33 suzi
drwxr-xr-x 4 www-data www-data     4096 Aug  8 19:35 template
drwxr-xr-x 2 www-data www-data     4096 Sep 15 21:22 updater
drwxr-xr-x 4 www-data www-data     4096 Dec 23 14:59 updater-ocxgjw80ihlh
-rw-r--r-- 1 www-data www-data    57455 Dec 26 13:59 updater.log
</details>

**Comment by MBfromOK** [comment]
Update: This issue was caused by Mindmaps (as seen in the backup error).  Unfortunately, when I attempted to remove it the first (and second) time(s) it apparently had issues as I still got the same error.  Today, while writing the above reply I attempted removing and updating again; which successfully resolved the error.
