### ISSUE TITLE
After the file is deleted, the ios11 recycle bin can't see the file, and the android recycle bin can see the file

### ISSUE THREAD

**Issue by 330201818** [nextcloud/server#13258]
![az](https://user-images.githubusercontent.com/15013924/50423917-f6c91280-0896-11e9-8a7a-33dd1830eaf7.jpg)
![ios](https://user-images.githubusercontent.com/15013924/50423923-0a747900-0897-11e9-801f-3249abdaf9ef.jpg)

After the file is deleted, the ios11 recycle bin can't see the file, and the android recycle bin can see the file

**Comment by violoncelloCH** [comment]
could you report this in the nextcloud/ios repository?

**Comment by tobiasKaminsky** [comment]
Closing here, as it is now in iOS: https://github.com/nextcloud/ios/issues/762
