### ISSUE TITLE
OCC create shares

### ISSUE THREAD

**Issue by Fastor01** [nextcloud/server#13256]
Hey there,
can you please add a function to OCC to create sharelinks and share folders/directorys beetween users.

Thank you very much

**Comment by coach1988** [comment]
We could use exactly this, as we would like to create "default shares" for new users programmatically (in our case used for email signatures so that customers always have a link to send bigger files to our employees).

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
