### ISSUE TITLE
Thunderbird with cardbook verification failed after update from nextcloud 14.0.3 to 14.0.4

### ISSUE THREAD

**Issue by TinoGlatzel** [nextcloud/server#13260]

**Comment by TinoGlatzel** [comment]
Hi,
i have updated my nextcloud from 14.0.3 to 14.0.4. After the update i want to connect my cardbook plugin from thunderbird to a new useraccout. The verification failes. The verification with version 14.0.3 was succeded. 
This ist the apache log:
192.168.21.100 - jana [25/Dec/2018:16:39:25 +0100] "PROPFIND /remote.php/dav/addressbooks/users/jana/contacts/ HTTP/1.1" 404 2764 "-" "Thunderbird CardBook/33.4 Lightning/5.4.9.1"
192.168.21.100 - jana [25/Dec/2018:16:39:26 +0100] "PROPFIND /remote.php/dav/addressbooks/users/jana/contacts/.well-known/carddav HTTP/1.1" 404 980 "-" "Thunderbird CardBook/33.4 Lightning/5.4.9.1"
192.168.21.100 - jana [25/Dec/2018:16:39:27 +0100] "PROPFIND /remote.php/dav/addressbooks/jana HTTP/1.1" 404 1004 "-" "Thunderbird CardBook/33.4 Lightning/5.4.9.1"
192.168.21.100 - - [25/Dec/2018:16:39:28 +0100] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 881 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0"

Any idea?

Tino

**Comment by j-ed** [comment]
> 192.168.21.100 - jana [25/Dec/2018:16:39:25 +0100] "PROPFIND /remote.php/dav/addressbooks/users/jana/contacts/ HTTP/1.1" 404 2764 "-" "Thunderbird CardBook/33.4 Lightning/5.4.9.1"

Usually you should ask this kind of questions in the Nextcloud help forum at https://help.nextcloud.com/ first. The HTTP 404 code means that the given resource couldn't be found. You should double-check if the address book name of the user "jana" is really named `contacts` and not `Kontakte`?

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
