### ISSUE TITLE
Unset active indicator of "Settings" tab if section collapsed

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13264]
NC 15.0.0
Firefox 64.0
### Steps to reproduce

1. Click on "Settings" tab to expand section.
2. Click on "Settings" tab to collapse section.

### Expected behavior
Inactive indicator

### Actual behavior
Active indicator

![settings_indicator](https://user-images.githubusercontent.com/9205230/50442621-b4dcb280-0910-11e9-99e5-5446a255e262.gif)

**Comment by R0maNNN** [comment]
The same behavior in the Deck app

But in Contacts app the section doesn't collapse when click on "Settings" 🤔

**Comment by R0maNNN** [comment]
reproduced on 16.0.0

**Comment by skjnldsv** [comment]
Well, the button is still active. Press space and you'll open it again.
This is also for keyboard and accessibility usage
