### ISSUE TITLE
Mail design

### ISSUE THREAD

**Issue by bekos77** [nextcloud/server#1326]
Hello, 

When I send a mail through the link sharing, the design is kinda amatuer.
Nextcloud :
![image](https://cloud.githubusercontent.com/assets/677171/18344793/fe505216-75b8-11e6-8200-cdf0cd81195c.png)

Owncloud looking better :
![image](https://cloud.githubusercontent.com/assets/677171/18344895/77f73580-75b9-11e6-9c68-3e3b0552c5b5.png)

Thanks for looking into it.

I use Nextcloud 10.0 stable on ubuntu server 16.04.01 LTS, php7

**Comment by MariusBluem** [comment]
Thank you for your report. Please use the **Issue Template** next time. For now - I think it is OK.

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
True – we can just use the logo now instead of »Mail header«. cc @schiessle 

Or should we also add »Nextcloud« next to it?

**Comment by juliushaertl** [comment]
What was the reason for using a gif instead of a png?

**Comment by bekos77** [comment]
@juliushaertl  I've done a copy/paste from a picture and github did the conversion. Sorry.

**Comment by juliushaertl** [comment]
@bekos77 No worries, I meant using a gif as mailheader image inside the nextcloud source code. ;)

**Comment by MorrisJobke** [comment]
@eppfel I just found https://mjml.io/ - maybe worth a look ;)
