### ISSUE TITLE
Broken link to contact info in top toolbar

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13265]
NC 15.0.0
Firefox 64.0

### Steps to reproduce
1. Click on "i" icon on contact list in top toolbar.
2. See white page instead of real contact info

The hyperlink is:
https://some.url/index.php/apps/contacts#/contact/{contact id}

Correct hyperlink:
https://some.url/apps/contacts#/contact/{contact id}

**Comment by weeman1337** [comment]
Thanks for the report @R0maNNN. What do you mean by "top toolbar"?

**Comment by R0maNNN** [comment]
@weeman1337 
Top toolbar:
![image](https://user-images.githubusercontent.com/9205230/50541428-e8d90180-0bb6-11e9-9270-e81683589ce8.png)

Broken link:
![image](https://user-images.githubusercontent.com/9205230/50541473-c85d7700-0bb7-11e9-8911-8d639431adb7.png)

**Comment by weeman1337** [comment]
@R0maNNN thanks for the info. Not it's clear :)

I think the link is correct. This way it also works if the URL rewriting to `index.php` isn't there. The solution should be that the contacts app also works with the other URL.

**Comment by R0maNNN** [comment]
@weeman1337 the fix is not released yet
https://github.com/nextcloud/contacts/pull/899 in
https://github.com/nextcloud/contacts/milestone/12

but I want to notice that "i" icon after the contact name is not show now. Is it by design?
![image](https://user-images.githubusercontent.com/9205230/53953051-73703c80-40e3-11e9-9394-00ea8844a85c.png)


NC 15.0.5
Contacts 3.0.3

**Comment by R0maNNN** [comment]
@weeman1337 well, it was released, the redirection bug was fixed. But the question above is still relevant - why did the “I” icon disappear?

**Comment by R0maNNN** [comment]
Is anyone alive here?

**Comment by R0maNNN** [comment]
On 16.0.0 (release) the icon came back and all works fine.
