### ISSUE TITLE
Upgrade 13 to 14.0.4 | OCA\DAV\Migration\Version1006Date20180628111625 is unknown

### ISSUE THREAD

**Issue by Hilzerak** [nextcloud/server#13275]
### Expected behaviour
Upgrade vom 13 to 14.0.4 sucessfully 

### Actual behaviour
Upgrade wont succed with following error:
InvalidArgumentException: Migration step 'OCA\DAV\Migration\Version1006Date20180628111625' is unknown

### Server configuration

**Operating system**:
ubuntu LTS 18.04 4.15.0-35-generic 

**Web server:**
apache

**Database:**
mariadb

**Nextcloud version:** (see Nextcloud admin page)
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
13.x

**Where did you install Nextcloud from:**
Docker-Compose

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.7.0
  - calendar: 1.6.1
  - cloud_federation_api: true
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.6
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.5.0
  - files_texteditor: 2.6.0
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.2.1
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.2.0
  - notifications: 2.1.2
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.3.0
  - survey_client: 1.2.0
  - systemtags: 1.3.0
  - theming: 1.4.1
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.3.0
Disabled:
  - accessibility
  - admin_audit
  - encryption
  - files_antivirus
  - support
  - user_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.4:8080",
            "owncloud.rautercast.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/owncloud.rautercast.de",
        "overwritecondaddr": "^192.168.1.4$",
        "overwritewebroot": "",
        "dbtype": "mysql",
        "version": "13.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "theme": ""
    }
}

</details>

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
yes

</details>

**Comment by ArchI3Chris** [comment]
Same problem. Trying to get from 13 to 15. Tried 14 between. Tried all kinds of stuff. No way to get out of this. Same error when trying to upgrade from 13 to 14. The whole upgrading process should severly improve. 14 is not in the repos anymore. So, there is no sense in killing yourself upgrading one version after the other and nothing works.

**Comment by Hilzerak** [comment]
For me Isolved the problem dirty. But since now i can say all is working. Will migrate the Data in the future to an fresh new install.
But the whole problem can be avoided if the just check the installed Version and dont do anything if there is a major version skipped. Cant understand why the Updater is doing anything and dont check it FIRST. that the check exist at all can we see in the message above. but only in a late step.

What i've done to "fix" that issue of the broken installation is following:
(I do NOT recommend that because somday it will be a problem for sure. but its the only possibility i see.) 
I removed under "apps/dav/lib/Migration/"
Version1006Date20180628111625.php
Version1008Date20181030113700.php
Version1008Date20181105104826.php
Version1008Date20181105104833.php
Version1008Date20181105110300.php
Version1008Date20181105112049.php
Version1008Date20181114084440.php

And then i overwrite my files with latest 14 Upgrade. Do the Upgrade. Then do the 15 Upgrade.
After this submit: 
db:convert-filecache-bigint
db:add-missing-indices

thats it.

**Comment by ArchI3Chris** [comment]
> For me I solved the problem dirty. But since now i can say all is working. Will migrate the Data in the future to an fresh new install.
> But the whole problem can be avoided if they just check the installed Version and dont do anything if there is a major version skipped. Cant understand why the Updater is doing anything and dont check it FIRST. that the check exist at all can we see in the message above. but only in a late step.
> 
> What i've done to "fix" that issue of the broken installation is following:
> (I do NOT recommend that because somday it will be a problem for sure. but its the only possibility i see.)
> I removed under "apps/dav/lib/Migration/"
> Version1006Date20180628111625.php
> Version1008Date20181030113700.php
> Version1008Date20181105104826.php
> Version1008Date20181105104833.php
> Version1008Date20181105110300.php
> Version1008Date20181105112049.php
> Version1008Date20181114084440.php
> 
> And then i overwrite my files with latest 14 Upgrade. Do the Upgrade. Then do the 15 Upgrade.
> After this submit:
> db:convert-filecache-bigint
> db:add-missing-indices
> 
> thats it.

Unfortunately, for me it was a bit more tedious than that, since I tried some things before. My theming is gone. So are my apps. Also, since I already had version 14 in the folder, I just deleted the Version1006* and Version1008* files. And after upgrading (in the web interface), I got the login and after the login yet another error.

To make up for that I just extracted version 14 to another folder and copied the one and only Version1006 into the nextcloud folder. At this point the error was gone, and nextcloud opened. But with only the files and gallery icons.

The upgrade to 15 went straight forward and it seem to work afterwards. Nevertheless I did run the 2 things afterwards to be on the save side.

The apps are still missing. Meanwhile I've reinstalled calendar and contacts. And it seems, they recognize the data afterwards. Kind of tedious. Will be some additional work though. Figuring out the apps that are missing. Reinstalling them... also, there is one of the usual error after the upgrade.

But as long as it works. So, BIG THANKS. At least it's back running. So, for me the comment was vital and did help. Also, on first sight I think, there won't be any consequences afterwards.

**Comment by skjnldsv** [comment]
This should be close as we released lots of further migrations patches with new versions. If this is still happening please make sure to upgrade to the latest version.
