### ISSUE TITLE
SMB login error (access denied)

### ISSUE THREAD

**Issue by nortonpt** [nextcloud/server#13274]
I have last version of the nextcoud.

I activate samba through https://ip:4443 and it is running.

I put a simple pw: 1234

When i try to login in windows I put: \\192.168.1.4 and i see the folder that Im sharing.

When I open it ask me the login details and then is my problem. I cant login.. always access denied.

Any idea?

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
