### ISSUE TITLE
"Set your password" text on button in welcome mail out of bounds

### ISSUE THREAD

**Issue by clesmian** [nextcloud/server#13287]
**Steps to reproduce**

1. Set your language for example to German
2. Set the name of your installation to a long name, using the Theming app
3. Add a new user with an e-mail address, but without a password
4. Wait for the first welcome mail to arrive
5. Resend welcome mail using the option in the users panel

**Expected behaviour**
The welcome mail should be well formatted and the text inside of the buttons should stay inside of the buttons bounds. 

**Actual behaviour**
The text inside of the left button exceeds the boundaries of the button.

Server configuration
Nextcloud version: 14.0.4

Examples can be found below. I have verified the formatting of the mail using Thunderbird and different webmail applications like roundcube.

![welcome-mail-passwort-reset](https://user-images.githubusercontent.com/18008727/50538412-ca034c80-0b6f-11e9-8d32-b796f691477b.PNG)
First welcome mail

![welcome-mail-long-instance-name](https://user-images.githubusercontent.com/18008727/50538411-ca034c80-0b6f-11e9-94cd-0a7f68c1af8f.PNG)
Resent welcome mail

**Comment by level420** [comment]
@clesmian off topic question: does the "set your password" link work for your installation? It's not working in my installation. See #12527 

I'm also observing that text overflow you've reported btw.

**Comment by clesmian** [comment]
@level420 the link works for me.

**Comment by johanehnberg** [comment]
I can confirm this bug, it occurs also with default settings and English.

**Comment by tobyps** [comment]
Hi,
I have the same Issue with 15.0.10 and posted it on the forum.

In my case it had no problems in English, only in German.
But it seems also connected to the used Mailapp.

Thunderbird 60.8 produced the error. Another user tried it with Outlook 2010 and reported no problem.
Webmailers of T-Online and GMX also had the error.

**Comment by heldausberlin** [comment]
Changing max-height of the button from 40px to 60px should do it.

**Comment by mroesele** [comment]
can confirm that this bug still exists

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by klemens-u** [comment]
Please fix this ugly layout issue. For many people the welcome mail is the first contact with Nextcloud ever. So this should be "pippifein" perfect and give a nice feeling to new users.

**Comment by MorrisJobke** [comment]
Wrongly closed - reopen.
