### ISSUE TITLE
unknown data type in doctrine: mapping_types needed

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#13282]
When upgrading, I get "Unknown database type jsonb requested" from doctrine. This is a very well known message from doctrine, which is triggered by tables not related to nextcloud that use column types not registered in doctrine.
Apparently this behaviour of doctrine will never be fixed, so all applications using it need some workaround.

To get stuff going, I added my additional types to Postgresql92Platform.php:initializeDoctrineTypeMappings(), but this obviously will lead to failed checksum checks. The correct workaround would be to induce registerDoctrineTypeMapping() calls.
I suggest introducing a "mapping_types" database connection parameter that performe these registrations. In the meantime, I wonder if there's another way instead of patching Postgresql92Platform.php.

**Comment by MorrisJobke** [comment]
Is this because of tables inside the nextcloud database that are not coming from Nextcloud itself?

**Comment by andreas-p** [comment]
Yes, in this case a personal NC app that's using jsonb.

**Comment by MorrisJobke** [comment]
Do you mind to hand in a pull request with those added mappings on our DB code base?

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since over 2 years. Please reopen if you still want to implement this.
