### ISSUE TITLE
Unexpected behavior when resharing to someone who already has the file shared with him

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/server#1329]
1. "user1" shares "folder" with "user2"
2. "user1" shares "folder" with "user3"
3. "user2" can't see that "user3" has access to "folder"
4. "user2" tries to share "folder" with "user3"

Result:

Error with

```
Path already shared with this user
```

Expected result

Share succeeds, both shares are merged on the receiving side for "user3"

cc @rullzer

**Comment by rullzer** [comment]
Yep still on the todo ;)

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
