### ISSUE TITLE
Dark Theme - Federated Cloud Settings - Icons not inverse color

### ISSUE THREAD

**Issue by derOtto** [nextcloud/server#13299]
### Steps to reproduce
1. Enabled Dark Theme in Accessebility
2. Go to Share Tab in private settings

![dark-theme - federated cloud](https://user-images.githubusercontent.com/12304203/50552070-05933900-0c8c-11e9-8029-e87fb52850c7.png)

### Expected behaviour
Icons of buttons to share id should be seeable (inverse color or other)

### Actual behaviour
All really dark

### Server configuration

**Operating system:** Debian GNU/Linux 9 (stretch)

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.2

**Nextcloud version:** 15

**Comment by skjnldsv** [comment]
![Capture d’écran_2019-04-30_11-03-20](https://user-images.githubusercontent.com/14975046/56951243-947b6980-6b37-11e9-9ea7-ad9834693cc3.png)

Fixed since
