### ISSUE TITLE
Translation Wrong in Settings

### ISSUE THREAD

**Issue by quotengrote** [nextcloud/server#13293]
On the Server in Settings -> Apps:
There is a String "Aktualisern" this should be "Aktualisieren"

In Transifex:(dont know how to fix it there):
https://www.transifex.com/nextcloud/nextcloud/viewstrings/#de/settings-1/91001605

![unbenannt](https://user-images.githubusercontent.com/38253905/50546016-18245880-0c21-11e9-8c60-585ea0be5137.png)

**Comment by JSoko** [comment]
Which NC-Version? Seems to be fixed in transifex...

https://www.transifex.com/nextcloud/nextcloud/viewstrings/#de/$?q=translation_text%3Aaktualisiern
https://www.transifex.com/nextcloud/nextcloud/viewstrings/#de_DE/$?q=translation_text%3AAktualisiern

**Comment by JSoko** [comment]
Witch NC-Verion was this issue?
Seems to be fixed.
Can't find it in transifex:
https://www.transifex.com/nextcloud/nextcloud/viewstrings/#de/settings-1/158031492?q=translation_text%3Aaktualisi
https://www.transifex.com/nextcloud/nextcloud/viewstrings/#de_DE/settings-1/91001680?q=translation_text%3Aaktualisier

**Comment by quotengrote** [comment]
Nextcloud 14.0.4

**Comment by JSoko** [comment]
> 
Than it should be solved for You with 14.05 or 15.0.0...
