### ISSUE TITLE
The "action" menu show in the wrong place

### ISSUE THREAD

**Issue by limstash** [nextcloud/server#13292]
### Steps to reproduce
1.Select language to Chinese Simplified or Chinese traditional
2.Back to the file view pages

### Expected behaviour
If I check some files, the "action" menu will appear in the header of the table (near to the "Name")
If I check nothing, nothing will happen

### Actual behaviour
Whether or not I check, the "action" menu will show behind the name of the first file (or folder) and hard to click

### Server configuration

**Operating system**: Centos 7

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
\Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - music: 0.9.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.***REMOVED SENSITIVE VALUE***.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.0.10",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "updater.release.channel": "daily",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser**: Chrome 71

**Operating system**: Windows 10 

#### Browser log
<details>
<summary>Browser log</summary>

```
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at _build (merged-template-prepend.js?v=1b8fc0f6-0:3872)
    at Object.translate (merged-template-prepend.js?v=1b8fc0f6-0:3895)
    at Object.translatePlural (merged-template-prepend.js?v=1b8fc0f6-0:3920)
    at FileSummary.update (merged-index.js?v=1b8fc0f6-0:4072)
    at FileSummary.setSummary (merged-index.js?v=1b8fc0f6-0:4037)
    at FileSummary.calculate (merged-index.js?v=1b8fc0f6-0:4020)
    at FileList.setFiles (merged-index.js?v=1b8fc0f6-0:5818)
    at FileList.reloadCallback (merged-index.js?v=1b8fc0f6-0:6521)
    at Object.<anonymous> (core.js?v=1b8fc0f6-0:2)
    at j (core.js?v=1b8fc0f6-0:2)
```
</details>

**Comment by rullzer** [comment]
Could I ask you to provide some screenshots?

**Comment by hytzongxuan** [comment]
![1](https://user-images.githubusercontent.com/8623449/50629398-54d0b680-0f77-11e9-8196-9ea8b7c802ad.jpg)
![2](https://user-images.githubusercontent.com/8623449/50629399-54d0b680-0f77-11e9-9ab8-f8a2ea743edf.jpg)

Actually, it should be like this

![3](https://user-images.githubusercontent.com/8623449/50629400-54d0b680-0f77-11e9-9394-5a69ed33a276.jpg)
![4](https://user-images.githubusercontent.com/8623449/50629401-54d0b680-0f77-11e9-8058-30e1b97cac55.jpg)

**Comment by zhonger** [comment]
I have this issue too after upgrading the latest nextcloud docker version. The error logs in browser console is like that in file `merged-template-prepend.js?v=76320180-0:3872` :
```shell
 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined   
```

**Comment by hytzongxuan** [comment]
> I have this issue too after upgrading the latest nextcloud docker version. The error logs in browser console is like that in file `merged-template-prepend.js?v=76320180-0:3872` :
> 
> ```shell
>  Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined   
> ```
> 
> ![jietu20190103-195546](https://user-images.githubusercontent.com/12064158/50636591-9c643c00-0f91-11e9-8fe0-7085dca345fa.jpg)
> 
> But when I change my locale to Chinese (Simplified Hans, China), it looks normal again. So I think it should be a bug in certain situation rather than all times.
> @hytzongxuan You may have a try.

Yeah, when I change my locale to Chinese, it works, tks.
Maybe it is a bug in certain situation.

**Comment by max41479** [comment]
Russian locale affected by this bug too. 
Other locales maybe affected by this bug too.

**Comment by yw1994** [comment]
When I change my locale to Chinese, it works too
it may be  a bug

**Comment by skjnldsv** [comment]
Still happening on latests versions?
