### ISSUE TITLE
Additional directory .Contacts-Backup available to NextCloud sync client, which doesn't show up in web GUI

### ISSUE THREAD

**Issue by JochenHWezel** [nextcloud/server#13298]
With the nextcloud sync client, I see a folder .Contacts-Backup which is not available usually:
![image](https://user-images.githubusercontent.com/14078625/50551457-d925ef80-0c80-11e9-9dde-4eeaa8ecc1a4.png)
The folder contains several .vcf files, e.g. "2018-12-17_20-56-50.vcf"

* OwnCloud sync client doesn't show this folder
* nextcloud web GUI doesn't show this folder

## Expected behaviour
The folder doesn't show up in sync client (for me, it seems to be an internal backup folder) - or otherwise (if not an internal folder but somehow user-provided) the web GUI should display it, too.
Therefore, the API for the sync client might somehow present this folder entry to the sync client - which might be the error, already.

## Environment
Nextcloud server v15.0
Nextcloud sync client 2.5.1final (build 20181204)

**Comment by JochenHWezel** [comment]
I just realized: the folder is OwnCloud client is ignored
![image](https://user-images.githubusercontent.com/14078625/50569465-292ab200-0d66-11e9-8620-17437636add2.png)

**Comment by Schmuuu** [comment]
Hi, 

It's not a bug. You can configure the Nextcloud client to ignore hidden files, just like it is the case with the Owncloud client.
In NC client you find the setting here:
![grafik](https://user-images.githubusercontent.com/26191454/50685394-4f2bad00-1019-11e9-9d26-2e6541726645.png)

**Comment by JochenHWezel** [comment]
I wonder why this checkbox is activated by default? 

- I never changed that setting at NC client, so it was checked immediately after setup, I assume
- The OC client has this checkbox unchecked, currently 
- The OC client has this checkbox unchecked by default

@Schmuuu 
=> should the default setting be reviewed/changed at NC client?!

**Comment by Schmuuu** [comment]
It really depends on the user and his use cases. I personally prefer that hidden files are not synched by default. But many users will probably think otherwise :)
As long as there is the option to enable and disable at will, it's fine for me.

By the way: same in the web GUI. You can configure if hidden files should be shown. By default they are hidden there. And, well ... putting this in contrast, it might be more consistent to not sync hidden files by default, yes.

**Comment by skjnldsv** [comment]
cc @nextcloud/desktop

**Comment by JochenHWezel** [comment]
from my side, this issue can be closed :-)
many thanks to @Schmuuu for all clarifications
