### ISSUE TITLE
No way to see who shared a file with someone

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/server#1330]
1. "owner" shares "folder" with "user1"
2. "user1" reshares "folder" with "user2"

Now "owner" has no way of telling how "user2" got access to "folder"

![](https://i.imgur.com/OCoubwT.png)

cc @rullzer

**Comment by MorrisJobke** [comment]
cc @jancborchardt another one for the sharing dialog overhaul ... we have the information in the database, but it's not visible in the UI.

**Comment by rullzer** [comment]
Yeah it is even in the response. I just have no clue how to display it properly

**Comment by jancborchardt** [comment]
We could show it in the tooltip.

> Robin Appelman (shared via Morris Jobke)

Ideally we can add a line break between first full name and parentheses part.

**Comment by rullzer** [comment]
PR in #4280
