### ISSUE TITLE
Error accepting invation by using links from invation email

### ISSUE THREAD

**Issue by sschleic** [nextcloud/server#13317]
### Steps to reproduce
1. Create an event and insert a email address to invite someone
2. Receive the invitation and click on Accept/Akzeptieren or Decline/Absagen

### Expected behaviour
Browser should show something like "Thanks for your Decission" or "Your decision is taken".
Some positive response. 

### Actual behaviour
I see a error message:
"Some error happen while updating the event" The broswer address bar show a plausible address:
nextcloudserveraddress/index.php/apps/dav/invitation/accept/4VLIwrjNDBCNKVEYnt0cZkQy5PHBgfQRuIRN7COH2GCAOn6ForNeQHAD7c3v

## Server configuration detail

**Operating system:** Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l

**Webserver:** Apache/2.4.25 (Raspbian) (apache2handler)

**Database:** mysql 10.1.23

**PHP version:** 

7.0.30-0+deb9u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mcrypt, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - bruteforcesettings: 1.2.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - contacts: 2.1.8
 - dav: 1.6.0
 - federatedfilesharing: 1.4.0
 - federation: 1.4.0
 - files: 1.9.0
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - firstrunwizard: 2.3.0
 - gallery: 18.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - workflowengine: 1.4.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.45.15",
        "byzswmrsbsmsx0r6.myfritz.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "overwrite.cli.url": "http:\/\/localhost\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "session_lifetime": 300,
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\APCu"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0

**Operating system:** 

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"Z0Wiskv9iTCOisr3hY9o","level":0,"time":"2019-01-04T16:05:18+00:00","remoteAddr":"192.168.45.11","user":"sschleic","app":"core","method":"PUT","url":"\/remote.php\/dav\/calendars\/sschleic\/personal\/Nextcloud-4FI5ONQU36WATXMEIJ5QJ6.ics","message":"Sent mail to \"Array\n(\n    [sstephan@posteo.de] => \n)\n\" with subject \"Invitation: TestLog\"","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.0.10"}
{"reqId":"CppZhOXlamiMYRSzPaCu","level":0,"time":"2019-01-04T16:05:54+00:00","remoteAddr":"192.168.45.11","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OC\\Log\\Rotate job with ID 20","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.0.10"}
{"reqId":"CppZhOXlamiMYRSzPaCu","level":0,"time":"2019-01-04T16:05:54+00:00","remoteAddr":"192.168.45.11","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OC\\Log\\Rotate job with ID 20 in 0 seconds","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.0.10"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by sschleic** [comment]
The content of nextcloud.log is:
{"reqId":"YRRsYb7b1cZVnoR6GO7O","level":3,"time":"2018-10-21T16:01:05+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"POST","url":"\/nextcloud\/index.php","message":"mkdir(): Keine Berechtigung at \/var\/www\/nextcloud\/lib\/private\/Setup.php#300","userAgent":"Mozilla\/5.0 (X11; Linux armv7l) AppleWebKit\/537.36 (KHTML, like Gecko) Raspbian Chromium\/65.0.3325.181 Chrome\/65.0.3325.181 Safari\/537.36","version":""}

**Comment by sschleic** [comment]
It is my own calendar.

**Comment by sschleic** [comment]
Did I miss some configurations? I just activated the calendar app from the app store.

**Comment by sschleic** [comment]
With Nextcloud15 the error is still present
I found in the log the following two entries


Debug | cron | Finished OCA\DAV\BackgroundJob\UpdateCalendarResourcesRoomsBackgroundJob job with ID 4 in 0 seconds |

**Comment by sschleic** [comment]
I updated the first comment and added a nextcloud logfile (Debuglevel 0). The logfile was cleared before creating the new event and it was saved after clicking the on the email link.

**Comment by adlh** [comment]
Possible duplicate of #12501

**Comment by sschleic** [comment]
Yes, this issue is a duplicate to #12501
