### ISSUE TITLE
Problem with slash in server URL

### ISSUE THREAD

**Issue by mwahrbi** [nextcloud/server#13311]
![nct](https://user-images.githubusercontent.com/11741909/50564476-6ae73880-0d25-11e9-93ec-50ff526c15ee.PNG)
the server Url in my case needs a slah in the end:
It should always be: 
https://90.152.145.159/nextcloud/
and not
https://90.152.145.159/nextcloud 
the last slash is cut of - so it not works.
i am using the UCS-VM on Windows 10 64 bit Server and 64 bit Client on Windows 10; the "missing slash at the end of the server URL" is in the Windows client.
The server is not all the time reachable with the URL, which has no slash at the end.

**Comment by xf-** [comment]
desktop client not server

**Comment by mwahrbi** [comment]
So this Thread can be deleted here.
