### ISSUE TITLE
Unexpected behaviour when --value= ommitted from nextcloud.occ [Repost from Nextcloud-snap]

### ISSUE THREAD

**Issue by Chrozayis** [nextcloud/server#13314]
[Original report](https://github.com/nextcloud/nextcloud-snap/issues/823)
This is Nextcloud 13, I could not find anything related to this issue in the issues or changelogs, apologies if this has already been fixed.

### Steps to reproduce
These are my steps working with the snap, I expect there to be a few more ways to achieve a similar result.
1. Install Nextcloud-snap
2. Set data directory ommitting --value=
 `sudo nextcloud.occ config:system:set datadirectory /media/nextcloud/data`

### Expected behaviour
There should be a warning that --value= has been ommitted and/or an intelligent assumption made about what the user intended.

### Actual behaviour
Suspicious success message:
`System config value datadirectory => /media/nextcloud/data set to empty string`

Looking at config.php I see that it has overwritten the string value with an array containing an empty string at index /media/nextcloud/data

Attempting to access the server results in an unhelpful message
```
Your data directory is invalid
Ensure there is a file called ".ocdata" in the root of the data directory.
```
I followed the instructions on the nextcloud-snap wiki for data migration and can verify the .ocdata does indeed exist at the expected location.

### Server configuration

**Operating system**: Ubuntu Server 18.04

**Web server:** Default for snap, Apache

**Database:** MySQL probably, unsure how to check

**PHP version:** Default for snap, unsure how to check

**Nextcloud version:** 13.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** snap

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors because I fixed the issue, I can rebrick my install if necessary
</details>

**List of activated apps:**
Almost certainly irrelevant

**Nextcloud configuration:**

**Are you using external storage, if yes which one:** SATA HDD sdb1 mounted at /media/nextcloud

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Any

**Operating system:** Any

### Logs
I've already worked around the issue, if required I can retrigger it and collect logs.

**Comment by skjnldsv** [comment]
Unfortunattely this is a generic handler.
We cannot assume the value is incorrect as it could actually be ok to set it as an empty string for something else.

The `config:system:set` is a shorthand to manage your config in cli, it does not account for human error and you're still expected as a sysadmin to check the result of your changes on the config :)

**Comment by Chrozayis** [comment]
Your response raises more questions than answers.
1. Why is the omission of `--value=` required as an option for setting empty strings when one can use `--value=""` ?
2. What's the point of a config tool if I'm supposed to open the config anyway?
Perhaps the tool is intended for people managing multiple instances? If that's the case, then the documentation should make it clear that it's a tool for advanced users and that casual users should edit the config directly.

**Comment by skjnldsv** [comment]
> 1. Why is the omission of `--value=` required as an option for setting empty strings when one can use `--value=""` ?

This make sense actually, we should maybe enforce `--value`.
@rullzer, @blizzz, thoughts?



> 2\. What's the point of a config tool if I'm supposed to open the config anyway?
>     Perhaps the tool is intended for people managing multiple instances? If that's the case, then the documentation should make it clear that it's a tool for advanced users and that casual users should edit the config directly.

No, but `cat config.php` is always mandatory.
If you're editing a config, you test it before, you don't ship it to production because everything is error prone. You don't have to open it to edit it in another tool, but you should always check an edit you've made on a file with a 3rd party tool. ;)

**Comment by blizzz** [comment]
Yeah, `--value` is currently added as an option (but with value required) and I believe the motivation was a better handling of empty input values back then. But now we do not check for null to see whether value  was provided or not.

**Comment by skjnldsv** [comment]
So, shall we enforce --value?

**Comment by blizzz** [comment]
In general it makes sense, I think, but  only by checking the option value for null, which breaks common usage. Bit it is a strange construct already. Valid it was only if the type option is set to null.

Otherwise hypothetically we could convert it to an argument, which is positional afaik. You might break scripts, and this makes only 18 a possibility. Better to avoid this path.

**Comment by szaimen** [comment]
Do you still want to implement this? If no, please close this issue!

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by szaimen** [comment]
Ah I see. Yeah, this value I would definitely edit by hand.
