### ISSUE TITLE
bug in sharing dialog

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#13323]
I must be missing something here - on my private instance I type "name@nextcloud.com" in an attempt to sent her a shared link by mail, but it tries to use server-to-server-sharing which doesn't work (I have a self-signed certificate, and besides, it would be name@cloud.nextcloud.com).

There seems there is an issue with the cleanup of the entries, so  the name@nextcloud.com email sharing entry gets removed from the list as it is the account email of the local account.

**Comment by lars-becker** [comment]
I have the same problem. Sharing via email is not possible since NC15.

**Comment by skjnldsv** [comment]
Fixed with #15719
