### ISSUE TITLE
Nextcloud 15 internal error

### ISSUE THREAD

**Issue by otaalk** [nextcloud/server#13325]
Hello,

Im using virtualBox on Ubuntu 18.02 and trying to launch nextcloud on VirtualBox using centos7 but im getting the same error "Internal Error"

Im doing all the same like this tutorial: https://docs.nextcloud.com/server/15/admin_manual/installation/source_installation.html

This error shows on nextcloud 12, 13, 14, 15. I tried even owncloud but i get error what server cant write config file, but nothing more.

I am new at this and can someone help? I dont know where to find log's. Thanks.
![nextcloud error](https://user-images.githubusercontent.com/46327526/50606214-a886c580-0ecd-11e9-9f60-a66c283c6b80.jpg)

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
