### ISSUE TITLE
Getting at sharing options in sharing dialog requires 'tab' key (nobody knows that)

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#13324]
In Nextcloud 15, the sharing dialog coalesces multiple results that point to the same user into one preferred option. For example, typing in `username`, given a `username` with email `username@gmail.com` in your address book, a `username` on the server and a federated share to `username@privateserver.com/nextcloud`, gives only "username" as direct share. That's great, but if you wanted to send a public link as share to `username@gmail.com`, you'd need to hit `TAB` to see the options.

There is no visual indication of that, no way to find out - I didn't know and couldn't share the way I needed to.

**Comment by rullzer** [comment]
So what is the issue? Are you trying to send a link to somebody that you can also share to directly? Or is the merging of contacts to greedy?

**Comment by juliushaertl** [comment]
If i understood correctly, it is about sharing a link to someone by mail who is also a user of the Nextcloud instance. I see the use case, for example, if there is a team folder shared with the whole team but I want to inform a co-member of the team about a specific file by email.

**Comment by jancborchardt** [comment]
> gives only "username" as direct share. That's great, but if you wanted to send a public link as share to `username@example.com`, you'd need to hit `TAB` to see the options.

I’m not sure I see the issue here. When we specified this behavior, we said that the recipient will get an email notification anyway, which will in that case go to their email at `username@example.com`.

So the end result should be the same, with the added benefit that it’s not only in their email inbox but actually connected in their Nextcloud.

**Comment by skjnldsv** [comment]
What is the status here, approved? Denied? :)

**Comment by jancborchardt** [comment]
Closing this, can always be reopened with more info. :)
