### ISSUE TITLE
Nextclud MariaDB/MySQL Error

### ISSUE THREAD

**Issue by keating178** [nextcloud/server#13337]
We are at the last few steps of getting our NextCloud environment up and running and I am running into issues with my mariadb cluster. The slave machine is doing just fine as shown in the screenshot below (Purple Text), the Other picture below (Green Text) is the Mariadb Master. I have highlighted the error that is showing up and seems to be causing a problem, I am reaching out to see if anyone has seen this issue or come across it before in hopes someone can better explain what it is trying to tell me.

Mariadb Master error:  
Could not execute Write_rows_v1 event on table nextcloud.oc_preferences; Duplicate entry 'itadmin-login_token-R5kdChkZrADHglI3VuOAeFIs0L2kfQsc' for key 'PRIMARY', Error_code: 1062; handler error HA_ERR_FOUND_DUPP_KEY; the event's master log testhqncmdb-bin.000062, end_log_pos 241468

Thanks in advance.

![mariadb master log error](https://user-images.githubusercontent.com/45406216/50649468-ce928100-0f32-11e9-9fdf-955ad3072776.JPG)
![mariadb slave log error](https://user-images.githubusercontent.com/45406216/50649470-cf2b1780-0f32-11e9-8c62-c47a64e48e9b.JPG)

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
