### ISSUE TITLE
Wrong (zero) inline padding in "Groups" multiselect input field

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13338]
NC 15.0.0
Firefox 64.0

### Steps to reproduce

Open "Users" tab
![untitled4](https://user-images.githubusercontent.com/9205230/50668400-d18f7f00-0fcf-11e9-99c3-86ee2cef4154.png)

**Comment by rullzer** [comment]
@nextcloud/designers

**Comment by skjnldsv** [comment]
Fixed on nextcloud-vue already https://github.com/nextcloud/nextcloud-vue/pull/140
We just need to release and wait for the dependency bot :)

**Comment by jancborchardt** [comment]
Good catch also @R0maNNN! Design detail reports are always welcome! :tada:

**Comment by R0maNNN** [comment]
Still bugged in NC 15.0.5

**Comment by skjnldsv** [comment]
Fixed in #14484
