### ISSUE TITLE
Unify file/folder enclosing across languages

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#13333]
The enclosing across the file or folder name in sharing emails is different in french:

French: «folder/file name»
English/others: »folder/file name«

Is this something that is done differently in french or is it just a mistake?

Also for notifications there is a different style used:

> {user} mentioned you in a comment on “{file}”

Should we unify that to «filename»

**Comment by rullzer** [comment]
Maybe a translation mistake?

**Comment by juliushaertl** [comment]
Probably, maybe someone can check that at transifex as I only have access to german translations there.

**Comment by juliushaertl** [comment]
As discussed on IRC «folder/file name» is the french variant, while »folder/file name« is the english/german one. So we should just unify this with the notifications as well.

**Comment by MorrisJobke** [comment]
> As discussed on IRC «folder/file name» is the french variant, while »folder/file name« is the english/german one. So we should just unify this with the notifications as well.

Does that make sense at all? Why should we handle this different for German if this is the way it is done in German?

**Comment by skjnldsv** [comment]
Still relevant @juliushaertl ?

**Comment by juliushaertl** [comment]
Lets just keep it as it is I'd say since regular quotes also work in french i guess :D
