### ISSUE TITLE
Default Encryption Module: "JSON.parse unexpected character" on the encryption password update form

### ISSUE THREAD

**Issue by thomasfrobieter** [nextcloud/server#13332]
### Steps to reproduce
1. Use a password with comma
2. encrypt the user directory under settings/admin/security
3. Change the password
4. Message "Wrong private key for the encryption app. Please update your private key in your personal settings to get access to the encrypted files again." (translated from german), appears
5. Open the browser (js) console
6. Try to update the password under settings/user/security --> Basic encryption module

(I don't remember the exact steps, but something like this ...)

### Expected behaviour
Tell us what should happen
Save the new password settings.

### Actual behaviour
Tell us what happens instead
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data (settings-personal.js:22:61)

I expect there are special chars in the "old password" which are not escaped >> comma?!

### Server configuration

**Operating system**:
Some Linux
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
14.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
The issue existed before the last update
**Where did you install Nextcloud from:**
Long time ago .. Hoster interface or manualy, not sure.
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
No SSH. I will create a list if needed!
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocmvr7ewdngq',
  'trusted_domains' => 
  array (
    0 => 'cloud.xyz.eu',
  ),
  'passwordsalt' => 'XYZ',
  'secret' => 'XYZ',
  'datadirectory' => '/home/sites/site33/web/nextcloud/data',
  'overwrite.cli.url' => 'https://cloud.xyz.eu',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'dbname' => 'dbXYZ',
  'dbhost' => 'XYZ.net',
  'dbport' => '',
  'dbtableprefix' => 'nextcloud_',
  'dbuser' => 'john',
  'dbpassword' => '123456',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => 'thomas',
  'mail_domain' => 'xyz.eu',
  'updater.secret' => 'XYZ',
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes (just user directory)
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox v. 64.0 (64 Bit)
**Operating system:**
Windows 10
#### Browser log
<details>
<summary>Browser log</summary>

```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data - settings-personal.js:22:61

Trace:
updatePrivateKeyPassword/<
https://cloud.xyz.eu/apps/encryption/js/settings-personal.js:22:61
j
https://cloud.xyz.eu/core/vendor/core.js:2:26920
fireWith
https://cloud.xyz.eu/core/vendor/core.js:2:27738
x
https://cloud.xyz.eu/core/vendor/core.js:4:11276
b/<
https://cloud.xyz.eu/core/vendor/core.js:4:14765
```
</details>

**Comment by thomasfrobieter** [comment]
There is also a [forum topic](https://help.nextcloud.com/t/falscher-privater-schluessel-fuer-die-verschluesselungs-app-bitte-aktualisieren-sie-ihren-privaten-schluessel-in-ihren-persoenlichen-einstellungen-um-wieder-zugriff-auf-die-verschluesselten-dateien-zu-erhalten/22659/3) to this issue.

**Comment by skjnldsv** [comment]
Is this still occurring?
What is the status of this issue?

Can you do a screencast of the process (changing password and see the error happening) please :)

**Comment by thomasfrobieter** [comment]
Oh damn it, missed to answer here sorry.

Its just happened again after a minor update:
The message "Wrong private key for the encryption app. Please update your private key in your personal settings to get access to the encrypted files again." (translated from german)

Went to settings page.. tried to enter my password:
https://ibb.co/jfVYLKg

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data - settings-personal.js:22:66
