### ISSUE TITLE
Mimetypes in the trashbin are wrong

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1337]
* all mimetypes in the trashbin are of type `application/octet-stream`
* I guess this is because they end with `.dUNIXTIMESTAMP`

Any idea how to fix that? cc @schiessle @icewind1991 @rullzer 

I found this while debugging another issue.

**Comment by MorrisJobke** [comment]
To check that just put a file with mimetype (e.g. text file) into the trashbin and check the response of the request to `apps/files_trashbin/ajax/list.php`

**Comment by schiessle** [comment]
I remember that back then when I wrote the code I explicitly removed the `.d4347364783` for the mime type detection. Seems that we lost it at some point in time again... I will have a look.

**Comment by schiessle** [comment]
Here we broke it... https://github.com/nextcloud/server/commit/435cd31fa6a250559b28b32f6185e4fcfc7fdff9

I will revert the line for the mimetype detection
