### ISSUE TITLE
Colors defined in Custom themes do not load

### ISSUE THREAD

**Issue by circlenaut** [nextcloud/server#13378]
### Steps to reproduce
1. Replaced themes/cloud.domain1.com/core with core (nextcloud root folder default)
2.  Disabled themes app
3. Loaded logo/background in core/css/guest.css
4. Defined desired color in themes/cloud.domain1.com/defaults.php
5. Doing this because I have multiple domains I'd like to customize

### Expected behaviour
Loads expected background/logo with defined colors.

### Actual behaviour
Loads only the background and logo. Color is nextcloud's default on login page. Upon login, the banner on top is the desired color but the folders are not.
If I enable the themes app. Then my colors work (defined in themes app) but the logo no longer loads. Backgrounds loads.

Strangely running sudo rpl -R default_color desired_color /var/www/nextcloud doesn't work either! I'd expect that to definitely change all colors. Are colors defined somewhere else?

### Server configuration

**Operating system**:
Ubuntu 16.04.5
**Web server:**
Apache 2.4.18-2ubuntu3.9
**Database:**
Mariadb 10.1
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
15
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14

### Client configuration
**Browser:**
Safari, Chrome, Firefox
**Operating system:**
Ubuntu 18.04 Budgie, iOS12

**Comment by skjnldsv** [comment]
Hi, sorry for the late answer!
Do you have screenshots of the issue?

You're talking about custom themes, not the theming app, right?
