### ISSUE TITLE
Add a thumbnail/grid view to folders shared via public link

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13375]
NC 15

Share folder via public link.
Open the link.

There is no way to choose grid view, only thumbnail view available.
![image](https://user-images.githubusercontent.com/9205230/50715751-b421ea00-108f-11e9-90eb-85a2d76ca808.png)

**Comment by jancborchardt** [comment]
Yeah … @nextcloud/designers any idea where this got lost?

**Comment by myevit** [comment]
same request. otherwise had to share from gallery app. Also would be nice to have grid view open by default for shared image folder

**Comment by jancborchardt** [comment]
@myevit if you have the same request, please use the emoji function on the original post to add your :+1: :) About the "Grid view open by default for shared image folder" → that is a separate request, could you open a separate issue?

**Comment by Bellusterra** [comment]
Curious to know if github is the preferred place to post? I had posted the same issue on the official Nextcloud discourse forum page, but not sure it gets the same visibility? Either way it’s good to see that it’s being noticed. 

https://help.nextcloud.com/t/no-gallery-view-in-nextcloud-15-shared-links/43819

@myevit yeah the previous version, Nextcloud 14, openned right up into gallery view with shared links when it was just a single shared folder, if I remember correctly. I think the introduction of the Gallery view of all files in Nextcloud 15 required enough changes in code to be made requiring a lot of things to be rewritten.

**Comment by skjnldsv** [comment]
> Yeah … @nextcloud/designers any idea where this got lost?

Found the issue.
Fix incoming

**Comment by skjnldsv** [comment]
Fix: https://github.com/nextcloud/server/pull/13514

**Comment by Bellusterra** [comment]
Great! Thank you @skjnldsv
