### ISSUE TITLE
Heterogeneous fonts in the whole interface

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13377]
NC 15.0.0 (Docker)
Firefox 64.0 on Windows 10

#### Difference between English and Russian
![image](https://user-images.githubusercontent.com/9205230/50716919-13cec400-1095-11e9-9c84-d44141ac9cfe.png)

#### 3 different fonts in the sentence
![image](https://user-images.githubusercontent.com/9205230/50717116-3b725c00-1096-11e9-9416-f87a3f47f30f.png)

**Comment by danielkesselberg** [comment]
@nextcloud/designers

**Comment by jancborchardt** [comment]
@R0maNNN thanks a lot for the report! :) It seems that these are many issues which can all be treated separately. Could you open separate issues for them? That will help them getting fixed quicker without one blocking the others. Thanks a lot!

**Comment by jancborchardt** [comment]
Oh and also, could you zoom in a bit when you take the screenshots so it’s easier to see the typeface differences? Thanks! :)

**Comment by R0maNNN** [comment]
@jancborchardt splitted, description of this issue edited (I think it's the same problem).

Digits in the hint: https://github.com/nextcloud/server/issues/13466

**Comment by danielkesselberg** [comment]
> In November 2017 Nunito has been expanded to GF Cyrillic Pro by Manvel Shmavonyan, and Alexei Vanyashin.

https://github.com/googlefonts/nunito :thinking:

**Comment by R0maNNN** [comment]
> Can you check if Open Sans (we used that before) or Noto Sans supports Cyrillic? Maybe this whole switch to Nunito was just a mistake and we need to go back.

I can say that there is no such problem in NC 14

**Comment by juliushaertl** [comment]
@jancborchardt It seems that the fonts added with  https://github.com/nextcloud/server/pull/11932 in server are not the latest ones from the googlefonts/nunito repo

sha256sum core/fonts/Nunito-Regular.ttf 
96a2bf793dd663407f49bcd219fe5abca8d52ce98d47b6063e3843db5d17bcdd
sha256sum ~/Downloads/Nunito-Regular.ttf 
f13b35daecf71d80d0df39e0f7bf6e99108a4516f38f682b52294090729f2fee

**Comment by jancborchardt** [comment]
@juliushaertl good find! @danielkesselberg do you want to update the fonts in the repository? :)

**Comment by danielkesselberg** [comment]
Sure @jancborchardt but after some research this looks more complicated :thinking: 

If you downloaded the font from https://fonts.google.com/specimen/Nunito then we currently serve v3.001 (https://github.com/google/fonts/tree/master/ofl/nunito). That is the version without cyrillic. 

There is already a pull request to update the font to v3.502 (https://github.com/google/fonts/pull/1549) from the upstream repository. This should add cyrillic and solve some other issues (https://github.com/google/fonts/labels/z_Nunito).

Grabbed the fonts from the pull request and used https://github.com/google/woff2 to create .woff2 but this tool does not support unicode range (didnt know that something like that exists pretty cool actually). I read https://developers.googleblog.com/2015/02/smaller-fonts-with-woff-20-and-unicode.html but still dont know the right way to create to woff2 files :confused:

**Comment by skjnldsv** [comment]
@jancborchardt what is the status here, approve or reject! :woman_judge:

**Comment by skjnldsv** [comment]
TODO: bump nunito
TODO: find a font that have cyrillic

**Comment by jancborchardt** [comment]
There is now a pull request to move to Noto Sans to fix all these issues with unsupported character sets. Please review it at https://github.com/nextcloud/server/pull/16040 :)

**Comment by jancborchardt** [comment]
We now use a native font stack as per https://github.com/nextcloud/server/pull/16055, so things will look heterogenous for Nextcloud 17 :tada:
