### ISSUE TITLE
Versions app: assign label(s) to file revisions

### ISSUE THREAD

**Issue by vitaliis** [nextcloud/server#13386]
This is a feature request, I assume for the files_versions app.
When viewing file versions (the details pane for a specific file on the right) I am missing the feature of providing a label for a specific version of the file.

Especially with the introduction of the integration with collabora it becomes essential.
Using labels you can mark different milestones of your work, such as:
* version of term paper sent out to professor,
* asking somebody to review a specific labeled version of a document,
* or marking a released version of the document that became public.

The issue's title says "label(s)". I think it is enough to have a single label per revision with optional description where you can give additional information (like details or links).

Nextcloud already has a notion of stars or tags. It would be nice to be able to tag a specific revision with the option of providing additional information for it.

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by thstyl2000** [comment]
This is indeed a very important feature when it comes to collaborative editing of files/notes/texts, also in conjunction with the new collaborative editor. Would you reconsider on it?

In any case thank you for your great work!!!
