### ISSUE TITLE
Not enough space in rootfs leads to config file getting broken and web installer trying to do it's thing

### ISSUE THREAD

**Issue by jcklpe** [nextcloud/server#13399]
Hi, 

So this has been a reoccuring issue for me across multiple versions of NextCloud. It seems to be a fairly simple issue, and it's in part my fault but I thought I should alert the devs anyway. Here is the latest relevant thread I've posted on the issue for background: https://help.nextcloud.com/t/lets-encrypt-cert-died-i-fixed-it-but-now-webinstaller-is-trying-to-reinstall/44577/3

Basically, when NC tries to update, if my filesystem doesn't have enough room on it, it goes wonky and erases the config.php leading to the web client trying to run the web installer. 

If I copy over the config.php file contents from a back-up over to the www/nextcloud/config/config.php file, after freeing up space then I can successfully run the updater no problem. 

I know that in part this is me being a dummy. I let my server fs get full. I wasn't paying attention, etc. But it's happened to other people, and it's happened to me at least twice, and the solution seems pretty simple. I'm not much of a dev, I'm more of a web designer who knows enough code to get himself in trouble, but it seems to me that it should be fairly trivial to add a check to the updater so that before it updates, it checks to see if there's enough room on the rootfs to run that update. Right? 

Anyway, feel free to close this or whatever, but I just wanted to let ya'll know. I'm going to go clean out my FS now. Thanks.

**Comment by skjnldsv** [comment]
@nextcloud/server-triage we should maybe have a check for this?
At least ensure we have a min of I don't know, 100MB?

**Comment by jcklpe** [comment]
This shouldn't be marked stale as there is no information that I have been asked for that hasn't been provided.

**Comment by skjnldsv** [comment]
@jcklpe it's missing info from us ;)

**Comment by PVince81** [comment]
idea:
- add a free space check in "occ upgrade" (core/Command/Upgrade.php)
- add a free space check in the updater: https://github.com/nextcloud/updater/blob/master/lib/Updater.php (make sure the check runs for both CLI run and web UI run)

the free space in question should be retrieved for the path in which the webroot is, or the config.php file is

tagged as "help wanted" as this should be a fairly easy task for community people to pick up

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
