### ISSUE TITLE
Shared PDF not rechable after change

### ISSUE THREAD

**Issue by CordlessWool** [nextcloud/server#13435]
Logging shows error messages: OC\Encryption\Exceptions\DecryptionFailedException: Encryption module "Default encryption module" is not able to read <filename>

and warning: Encryption module "Default encryption module" is not able to read <filename>

### Steps to reproduce
1. Create PDF
2. Share PDF by linl
3. save PDF with same name again

### Expected behaviour
The PDF should just reachable after saved again

### Actual behaviour
Go to the shared links open the pdf view, but shows an errer, that the pdf could not be load

### Server configuration

**Operating system**:
official Docker Container fpm

**Web server:**
official docker contrainer fpm

**Database:**
MySQL 5.7
Redis

**PHP version:**
7.2.13

**Nextcloud version:** (see Nextcloud admin page)
15.0.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 14.04

**Where did you install Nextcloud from:**
docker hub 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** not write now

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment]
No errors in the logs?
