### ISSUE TITLE
Problems sharing write-protected external storage

### ISSUE THREAD

**Issue by rreichelt** [nextcloud/server#13449]
If you configure a SFTP as write-protected, shareable external source you can share said source via public link, but not with other accounts on the server. Can you confirm this?
Same effect with a write-protected, shareable WebDAV. Probably the same for all external sources? Error message reads something like "can not raise permissions on $source".

### Steps to reproduce
1. configure an external storage (i tried SFTP and WebDAV)
2. mark said external storage as "write protected" and "shareable"
3. try to share with another user (-> does not work)

### Expected behaviour
I should be able to share a write-protected shareable external storage with other registered users. 

### Actual behaviour
I can click share and select another user, however the error message (roughly translated) says "can not raise permissions on $source".
Sharing via public link works.

### Server configuration

**Operating system**:
NC15 docker image running on an ubuntu 18.04 LTS machine (current patchlevel)

**Web server:**
Apache (i think) with nginx SSL proxy

**Database:**
MariaDB (docker image)

**PHP version:**
uh...whatever is shipped with the standard container.

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 14.x

**Where did you install Nextcloud from:**
https://hub.docker.com/_/nextcloud/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
"No errors have been found."
```
</details>

**List of activated apps:**
<details>
<summary>Details</summary>

Accessibility
Activities for shared file downloads
Activity
Brute-force settings
Calendar
Checksum
Collaborative tags
Comments
Contacts
Dashboard
Deleted files
External storage support
File sharing
First run wizard
Gallery
Keep or Sweep
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Polls
Preview Generator
Radio
Social
Support
Text editor
Theming
Two Factor TOTP Provider
Update notification
Usage survey
Versions
Video player
</details>

**config:**
<details>
<summary>App list</summary>

```php
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'XXX',
  'passwordsalt' => 'XXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'XXX',
    1 => 'XXX',
    2 => 'XXX',
    3 => 'XXX',
    4 => 'XXX',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '15.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'mysql:3306',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'XXX',
  'dbpassword' => 'XXX',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'loglevel' => 2,
  'maintenance' => false,
  'overwrite.cli.url' => 'XXX',
  'overwriteprotocol' => 'https',
  'updater.release.channel' => 'stable',
);
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

WebDAV & SFTP

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
currently not

### Client configuration
**Browser:**
Firefox 64.0
Chrome Version 68.0.3440.75

**Operating system:**
Linux Mint 19

#### Nextcloud log (data/nextcloud.log)
this issue is not generating log entries
</details>

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>
