### ISSUE TITLE
Avatar Storage = Bruteforce Potential

### ISSUE THREAD

**Issue by tuzohetoruyu** [nextcloud/server#13447]
/index.php/avatar/adm1nnc/145?v=1
to prevent bruteforce and guessing of login  usernames please change the avatar storage location to and id of the user which u cant use for login tries. the avatar and so the login usernames could be grabbed, please fix

ty

**Comment by tuzohetoruyu** [comment]
the avatar and so the login usernames could be grabbed, please fix

**Comment by danielkesselberg** [comment]
If you think you found a security issue you can report it here: https://hackerone.com/nextcloud

@nextcloud/security

**Comment by nickvergessen** [comment]
User enumeration is possible in many ways. This is also described in on our thread model page:
 https://nextcloud.com/security/threat-model/
