### ISSUE TITLE
Security Scanner False Call  .htaccess

### ISSUE THREAD

**Issue by tuzohetoruyu** [nextcloud/server#13455]
Security Scanner False Call  .htaccess while it is working correctly and respond "403 Forbidden
You don't have permission to access /config/ on this server." 
Possible Cause: only shows up when the root directory of the webserver is an external disk.
NC Setup: Kali Arm64 PHP 7.3

**Comment by tuzohetoruyu** [comment]
Also it calls imagick is not installed while it is. so i guess this is a php / nextcloud problem.
or is this no usable mod for php7.3 because only the package php-imagick is availble

**Comment by skjnldsv** [comment]
Should be fixed I guess?
php imagick is available for 7.3
