### ISSUE TITLE
Rename shared file within read-only external storage fails with error

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#13451]
### Steps to reproduce
1. have userA and userB
2. create an external storage mount that is read-only, does not have any files and is mounted to `/` for userB
3. as userA create a file `foo.txt` and share it with userB
4. as userB try to rename the received shared file `foo.txt` to `bar.txt`

### Expected behaviour

* file should be renamed

### Actual behaviour

* there is an error that says "there is not file 'foo.txt'" and the file is removed from the file list
* after a reload the file `foo.txt` is still there.

cc @icewind1991 @rullzer

**Comment by rullzer** [comment]
Well. One could argue the share should not be mounted in the first place since it is a mountpoint inside a mountpoint.

This really is abusing the system in a way it was not designed to be used.

**Comment by nickvergessen** [comment]
I agree, the correct behaviour should be a decent error message and the file should not disappear, if we at all allow this.

**Comment by MorrisJobke** [comment]
> This really is abusing the system in a way it was not designed to be used.

Actually we allowed to mount external storages on `/`. It's just that it misbehaves somehow weirdly as well. So we need to look into what to fix.

**Comment by rullzer** [comment]
@MorrisJobke that is not what I'm saying is the abuse. The abuse is that we in all other cases forbid mountpoints in mountpoints. Because it is a weird scenario. And incomming shares are exactly that.

**Comment by MorrisJobke** [comment]
But then we need to cut the „mount into /„ feature of external storage. Or do you see an other option? What about external storage amount points in each other? Because I think this is possible nowadays

**Comment by rullzer** [comment]
My point is there is a reason we block this normally. It might work but there might be unexpected side effects. We can look into the reported issue but I guess it is a world of pain to figure out what goes on there.
