### ISSUE TITLE
Proxy support not working in NC 15

### ISSUE THREAD

**Issue by linuxfan3** [nextcloud/server#13450]
Opening "Administration / Overview" results in this error message:

"This server has no working Internet connection: Multiple endpoints could not be reached. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. Establish a connection from this server to the Internet to enjoy all features."

There is a proxy server configured in config/config.php and tcpdump shows NC is connecting to this server and sending a connection request:

CONNECT lookup.nextcloud.com:443 HTTP/1.0

However afterwards NC is sending a get request for "/" that results in a bad request error:

GET / HTTP/1.1

Response:

HTTP/1.1 400 Bad Request
Server: squid/3.3.8
Mime-Version: 1.0
Date: Wed, 09 Jan 2019 14:45:20 GMT
Content-Type: text/html
Content-Length: 3172
X-Squid-Error: ERR_INVALID_URL 0
Vary: Accept-Language
Content-Language: en
X-Cache: MISS from xxx
X-Cache-Lookup: NONE from xxx:3128
Connection: close

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html><head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<title>ERROR: The requested URL could not be retrieved</title>
<style type="text/css"></style>
</head><body id=ERR_INVALID_URL>
<div id="titles">
<h1>ERROR</h1>
<h2>The requested URL could not be retrieved</h2>
</div>
<hr>

<div id="content">
<p>The following error was encountered while trying to retrieve the URL: <a href="/">/</a></p>

<blockquote id="error">
<p><b>Invalid URL</b></p>
</blockquote>

<p>Some aspect of the requested URL is incorrect.</p>

<p>Some possible problems are:</p>
<ul>
<li><p>Missing or incorrec
t access protocol (should be <q>http://</q> or similar)</p></li>
<li><p>Missing hostname</p></li>
<li><p>Illegal double-escape in the URL-Path</p></li>
<li><p>Illegal character in hostname; underscores are not allowed.</p></li>
</ul>

<p>Your cache administrator is <a href="mailto:webmaster?subject=CacheErrorInfo%20-%20ERR_INVALID_URL&amp;body=CacheHost%3A%20xxx%0D%0AErrPage%3A%20ERR_INVALID_URL%0D%0AErr%3A%20%5Bnone%5D%0D%0ATimeStamp%3A%20Wed,%2009%20Jan%202019%2014%3A45%3A20%20GMT%0D%0A%0D%0AClientIP%3A%2083.219.105.172%0D%0A%0D%0AHTTP%20Request%3A%0D%0A%0D%0A%0D%0A">webmaster</a>.</p>
<br>
</div>

<hr>
<div id="footer">
<p>Generated Wed, 09 Jan 2019 14:45:20 GMT by xxx (squid/3.3.8)</p>

</div>
</body></html>

**Comment by kesselb** [comment]
Do you still see this issue?
