### ISSUE TITLE
Strange digits of the datetime in the hint

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#13466]
NC 15.0.0 (Docker)
Firefox 64.0 on Windows 10

For example, strange height of "1" of the datetime in the hint
![image](https://user-images.githubusercontent.com/9205230/50717049-e5051d80-1095-11e9-965c-1725773dcb6d.png)

Reproduced only in 100% scale.

**Comment by jancborchardt** [comment]
That is very strange indeed. I can’t reproduce though:
![tooltip date](https://user-images.githubusercontent.com/925062/50937881-00956d00-1476-11e9-87df-47ae2b778b43.png)

Anyone of @nextcloud/designers seeing the same as @R0maNNN?

**Comment by skjnldsv** [comment]
Not here :/
