### ISSUE TITLE
mobile web does not fit horizontally (files app)

### ISSUE THREAD

**Issue by cyberb** [nextcloud/server#13465]
On mobile screen (Moto G4) files app does not fit horizontally a little bit and can be scrolled.

v14 and v15 are affected.

### Steps to reproduce

1. Open Nextcloud in Firefox
2. Enable Responsive Design mode (Galaxy S9 - 360x740)
3. Observe horizontal scroll

Before version v14 there was no scroll.

![nextcloud-web-issue](https://user-images.githubusercontent.com/885528/50926789-c3b58000-144d-11e9-88cd-d3e934bffe56.jpg)

**Comment by violoncelloCH** [comment]
affects at least gallery and activities too on ff mobile

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by raimund-schluessler** [comment]
This is still an issue with 17.0.0. There are horizontal scrollbars on iPhone 8 for example. With German language settings they appear if the screen width is below 399 px.

One reason ist that this button https://github.com/nextcloud/server/blob/master/core/templates/layout.user.php#L36 is absolutely positioned by 300 px to the left, hence increasing the page width over 400 px.

The second problem is, that the filestable is to wide. But I couldn't figure out yet, how to solve this.

@jancborchardt and @skjnldsv might want to have a look here 😉

**Comment by MorrisJobke** [comment]
@nextcloud/designers What to do here? Still an issue?

**Comment by skjnldsv** [comment]
Cannot reproduce :shrug:

**Comment by raimund-schluessler** [comment]
Seems to be fine now (quickly tested with NC 19.0.1 on iPhone 8).
