### ISSUE TITLE
Shares from SMB AD mount point gets lost on AD account lock

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#13486]
Potential steps to reproduce:

* userA has AD login
* userA has SMB mount point with the same AD login inside Nextcloud
* userA shares something in there to userB
* userA locks his account in AD
* userB cannot access the share (this one is expected, because the account is locked and can't access the SMB mount)
* userA unlocks his account in AD
* userB still cannot access the shares, because they are gone (this one is NOT expected)

cc @icewind1991 @blizzz @rullzer

**Comment by MorrisJobke** [comment]
> * userA has SMB mount point with the same AD login inside Nextcloud

This uses "Credentials stored in DB"

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by MorrisJobke** [comment]
Yes - still valid

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by MorrisJobke** [comment]
I don't have a test setup available anymore. Let's just close this and if this happens for somebody they can reopen it.
