### ISSUE TITLE
Move shared file out of shared folder does not put it in the owner trash bin

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#13487]
* User A shares a folder (with jpgs) with user B with full authorization: can edit, can share, can delete, etc.
* User B moves one file to another folder so that this file isn't anymore in the shared folder of user A.
* User A receives the information in his activities that user B has deleted the file even though it is still present in user B's account. (this one is correct)
* The moved file has disappeared in user A's account. 

## Expected behavior 

* the moved file should show up in User A's trashbin

## Actual

* the moved file doesn't show up in User A's trashbin

In comparison if User B deletes the file, then it properly shows up in User A's and User B's trash bin. But why is for the above case the activity correct, but the file not present in the trashbin?

@schiessle had already a look at this but couldn't find the actual source. Maybe @icewind1991 has some more ideas here.

cc @rullzer

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
