### ISSUE TITLE
Nextcloud 15.0.1 Stable available - Unable to upgrade from 15.0.0

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#13490]
Nextcloud 15.0.1 stable is available, but the upgrade is ignored via CLI and GUI.
Nextcloud 15.0.0 claims to be already the latest version.

**Steps to reproduce** (see screenshots):

![upgrade-bug2](https://user-images.githubusercontent.com/31093459/50979023-ee5b1380-14f5-11e9-8164-1885d134563e.png)

![upgrade-bug](https://user-images.githubusercontent.com/31093459/50978745-53623980-14f5-11e9-85a3-516662b286a8.png)

**Comment by Knot3n** [comment]
See: https://github.com/nextcloud/server/issues/13499

**Comment by MorrisJobke** [comment]
Should be solved now.

**Comment by timmersr** [comment]
It is, but only by manually (removing all but /config and /data) installing 15.0.2
Updating via the GUI or updater.phar continues to fail.
