### ISSUE TITLE
[Bug] Update App to version compatible with installed nextCloud, requires page refresh to "enable"

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#13502]
I saw this issue with nc14 and now nc15, whereby I have some apps that are disabled because they aren't a version high enough to be compatible with the installed version, however when I hit the "update to x.x.x" and it updates it, the Enable button remains greyed out... until I refresh the page.

Seems a bit silly that we have a nice responsive UX here, but it can't re-issue the compatibility check in the same instance after updating.

Just a small UX thing, but it had me worried for a while that something else was wrong that I didn't account for.

Currently on 15.0.1.

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript and especially @juliushaertl

**Comment by skjnldsv** [comment]
Bump :)

**Comment by juliushaertl** [comment]
Yeah we should refetch the app info after updating. I'll look into that.

**Comment by BloodyIron** [comment]
Yes please!

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
