### ISSUE TITLE
"Contact could not be saved" when Contacts shared with "everyone"

### ISSUE THREAD

**Issue by obinine** [nextcloud/server#13505]
⚠I started getting "Contact could not be saved" to every edit. After messing around I traced it to the "Everyone Group" app and that I had opened up read access for "everyone".

I will file a bug report with that module but wanted to post a note here in case others run into this issue.

**Comment by skjnldsv** [comment]
@MorrisJobke @rullzer @georgehrke any clue?

**Comment by obinine** [comment]
The really weird part of it all (at least to me) is that the edit is actually saved, in spite of the message, and is visible if you do an F5 refresh

**Comment by georgehrke** [comment]
```
SELECT `uid`, `displayname` FROM `oc_users` `u` LEFT JOIN `oc_preferences` `p` ON (`userid` = `uid`) AND (`appid` = 'settings') AND (`configkey` = 'email') WHERE (`uid`  COLLATE UTF8_general_ci LIKE ?) OR (`displayname`  COLLATE UTF8_general_ci LIKE ?) OR (`configvalue`  COLLATE UTF8_general_ci LIKE ?) ORDER BY `uid_lower` ASC LIMIT -1 OFFSET 0' with params [\"%%\", \"%%\", \"%%\"]
```

I'm pretty sure `LIMIT -1` is not allowed. 

Didn't check, but my wild guess would be that this is the origin of the -1:
https://github.com/icewind1991/group_everyone/blob/master/lib/GroupBackend.php#L75

cc @icewind1991

**Comment by rullzer** [comment]
Limit should indeed just be ignored when it is set to -1...

**Comment by rullzer** [comment]
(or 0 for that matter)

**Comment by EchoPhalcon** [comment]
I found this issue on https://ovio.org/projects and would love to contribute! [add other relevant info about you]

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
