### ISSUE TITLE
Cumbersome Upgrade 14.0.4. --> 15.0 (not 15.0.1)

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#13504]
I was offered to upgrade my NC 14.0. 4 with Version 14.0.5,so I hit the Updater öffnen button and started the upgrade process! All of a sudden, I received the welcome Message for Nextcloud 15 an not for 15.01 (see enclosed screenshot!) !

What kind of surprise !

I received the following warning:

Der "Referrer-Policy" HTTP-Header ist nicht gesetzt auf "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" oder "same-origin". Dadurch können Verweis-Informationen preisgegeben werden. Siehe die W3C-Empfehlung.

even though I set the appropriate option in the webserver already before the upgrade. It which worked fine already in 14.0.4 !

This is the usual update / upgrade disaster ever since Nextcloud was born 2 years ago !

best regards, hitam4450

![nc15](https://user-images.githubusercontent.com/9738727/51022519-bd75ef80-1584-11e9-9d7b-b788650750ac.png)
![nc15_1](https://user-images.githubusercontent.com/9738727/51022520-bd75ef80-1584-11e9-861c-971a30b65d55.png)

**Comment by Knot3n** [comment]
i upgraded from 14 to 15 and have now some problmes too ... we got redirect loop logins ... without error messages.

**Comment by karloluiten** [comment]
My instance keeps redirecting me to the internal (10.x.x.x) address since this update. Let me know if I can provide logs.

**Comment by danielkesselberg** [comment]
> Der "Referrer-Policy" HTTP-Header ist nicht gesetzt auf "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" oder "same-origin". Dadurch können Verweis-Informationen preisgegeben werden. Siehe die W3C-Empfehlung.

https://github.com/nextcloud/server/pull/12738 (starting with nextcloud 15 but also backported to 14.0.4 referrer-policy is set by nextcloud like many other headers as well for your convencience. if you defined with your apache2 or nginx configuration you need to drop it. the warning is a bit unclear here. its shown when the header is not present or more than once.)

**Comment by karloluiten** [comment]
Setting below things fixed my broken 14->15 ugrade:

```
  'overwrite.cli.url' => 'https://cloud.hostname.nl',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'cloud.hostname.nl',
```

**Comment by kesselb** [comment]
Could you fix the warning?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
