### ISSUE TITLE
Widnows client cannot add files by sync to shared folder

### ISSUE THREAD

**Issue by bakkerl** [nextcloud/server#1352]
### Steps to reproduce
1. Install NextCloud 10
2. Create 2 users (UserA, UserB)
3. UserB shares a folder with UserB, full rights
4. UserB syncs shared folder with windows client
5 UserB places new file in local folder
6. Windows client shows an error:
Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)

### Expected behaviour
The file placed should be synced to nextcloud server

### Actual behaviour
6. Windows client shows an error:
Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)

### Server configuration
**Operating system**: CentOS 7
**Web server: Apache/2.4.23
**Database: mysql  Ver 15.1 Distrib 5.5.41-MariaDB, for Linux (x86_64) using readline 5.1
**PHP version: PHP 7.0.10
**Nextcloud version: Nextcloud 10.0 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-10.0.0.zip
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Comment by joeMJ** [comment]
Same with Mac Client. Have a look onto server logs.

`Exception: {"Message":"HTTP\/1.1 507 Insufficient Storage","Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Code":0,"Trace":"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('\/Test\/Bildschir...', Resource id #72, Object(OCA\\DAV\\Connector\\Sabre\\Directory), false)\n#1 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#3 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('Test\/Bildschirm...', Resource id #72, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/html\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/html\/nextcloud\/remote.php(165): require_once('\/var\/www\/html\/n...')\n#10 {main}","File":"\/var\/www\/html\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","Line":109,"User":"6499DD4F-9078-4527-B93E-2EE9532BBDD4"}`

**Comment by DirkHeinke** [comment]
I have the same problem and it should be fixed with this commit: https://github.com/nextcloud/server/commit/6c365cb06d1aff8d44758be1337ba30acdcc49d7

It will be included in the next update AFAIK.

**Comment by joeMJ** [comment]
Merci Merci Merci ^^ ;-) Works.

**Comment by SonRiab** [comment]
I close this one because it is already fixed with https://github.com/nextcloud/server/commit/6c365cb06d1aff8d44758be1337ba30acdcc49d7.
