### ISSUE TITLE
Uncaught Error: Class 'OC' not found in upload.php

### ISSUE THREAD

**Issue by ss89** [nextcloud/server#1353]
### Steps to reproduce
1. login
2. choose file for uploading
3. internal server error message appears

### Docker Container:
sstruss/nextcloud-fpm-only-armhf (Please note it is for arm processors)
Dockerfile: https://github.com/ss89/docker-nextcloud-fpm-only-armhf

### Expected behaviour
uploading the file, then reloading the file tree

### Actual behaviour
upload progress goes to the end, then an internal server error message appears.
In the php logs (fpm) i see:
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /var/www/html/nextcloud/apps/files/ajax/upload.php:37"
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "Stack trace:"
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "#0 {main}"
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "  thrown in /var/www/html/nextcloud/apps/files/ajax/upload.php on line 37"

### Server configuration
**Operating system**: Ubuntu 14.04

**Web server:**
Nginx **(config: http://pastebin.com/G474S797)**

**Database:**
MySQL 5.5.50

**PHP version:**
PHP 7.0.8

**Nextcloud version:** (see Nextcloud admin page)
10.0 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install via cli

**Where did you install Nextcloud from:**
local copy of nextcloud 10 tar bz2

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "nextcloud",
        "dbhost": "192.168.0.120",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "ocbxfi0nwaiv"
    }
}
**Are you using external storage, if yes which one:** local/smb/sftp/...
local, but possibility to use a docker volume

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 52.x

**Operating system:**
Mac OS X 10.11.6

### Directories:
root@f8159806dcde:/var/www/html/nextcloud# ls -la /data/
total 24
drwxrwx---  5 www-data www-data 4096 Sep 10 08:35 .
drwxr-xr-x 54 root     root     4096 Sep 10 08:27 ..
-rw-r--r--  1 www-data www-data  284 Sep 10 08:21 .htaccess
-rw-r--r--  1 www-data www-data    0 Sep 10 08:21 .ocdata
drwxr-xr-x  4 www-data www-data 4096 Sep 10 08:34 admin
drwxr-xr-x  2 www-data www-data 4096 Sep 10 08:35 files_external
-rw-r--r--  1 www-data www-data    0 Sep 10 08:21 index.html
-rw-r-----  1 www-data www-data 3929 Sep 10 08:47 nextcloud.log
root@f8159806dcde:/var/www/html/nextcloud# ls -la /data/admin/
total 16
drwxr-xr-x 4 www-data www-data 4096 Sep 10 08:34 .
drwxrwx--- 5 www-data www-data 4096 Sep 10 08:35 ..
drwxr-xr-x 2 www-data www-data 4096 Sep 10 08:34 cache
drwxr-xr-x 4 www-data www-data 4096 Sep 10 08:21 files
root@f8159806dcde:/var/www/html/nextcloud# ls -la /data/admin/files/
total 4040
drwxr-xr-x 4 www-data www-data    4096 Sep 10 08:21 .
drwxr-xr-x 4 www-data www-data    4096 Sep 10 08:34 ..
drwxr-xr-x 2 www-data www-data    4096 Sep 10 08:21 Documents
-rw-r--r-- 1 www-data www-data 3645817 Sep 10 08:21 Nextcloud Manual.pdf
-rw-r--r-- 1 www-data www-data  462413 Sep 10 08:21 Nextcloud.mp4
drwxr-xr-x 2 www-data www-data    4096 Sep 10 08:21 Photos

### Logs
nextcloud log doesn't show any error, but php fpm log does:
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /var/www/html/nextcloud/apps/files/ajax/upload.php:37"
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "Stack trace:"
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "#0 {main}"
[10-Sep-2016 08:36:17] WARNING: [pool www] child 35 said into stderr: "  thrown in /var/www/html/nextcloud/apps/files/ajax/upload.php on line 37"

#### Web server error log
2016/09/10 10:36:45 [error] 23856#0: *64 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class 'OC' not found in /var/www/html/nextcloud/apps/files/ajax/upload.php:37
Stack trace:
#0 {main}
  thrown in /var/www/html/nextcloud/apps/files/ajax/upload.php on line 37" while reading response header from upstream, client: 192.168.0.115, server: , request: "POST /nextcloud/apps/files/ajax/upload.php HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:8081"

#### Nextcloud log (data/nextcloud.log)
no entries were made

#### Browser log
JQMIGRATE: Migrate is installed, version 1.4.0
Failed to parse SourceMap: https://localhost:8081/nextcloud/core/vendor/jquery/dist/jquery.min.map
jquery.min.js?v=b039f45…:4 POST https://localhost:8081/nextcloud/apps/files/ajax/upload.php 500 (Internal Server Error)send @ jquery.min.js?v=b039f45…:4ajax @ jquery.min.js?v=b039f45…:4send @ jquery.fileupload.js?v=b039f45…:906(anonymous function) @ jquery.min.js?v=b039f45…:2j @ jquery.min.js?v=b039f45…:2add @ jquery.min.js?v=b039f45…:2(anonymous function) @ jquery.min.js?v=b039f45…:2each @ jquery.min.js?v=b039f45…:2(anonymous function) @ jquery.min.js?v=b039f45…:2a.Deferred @ jquery-migrate.min.js?v=b039f45…:2then @ jquery.min.js?v=b039f45…:2_onSend @ jquery.fileupload.js?v=b039f45…:950(anonymous function) @ jquery-ui.custom.js?v=b039f45…:405data.submit @ jquery.fileupload.js?v=b039f45…:674(anonymous function) @ file-upload.js?v=b039f45…:413each @ jquery.min.js?v=b039f45…:2onNoConflicts @ file-upload.js?v=b039f45…:412checkExistingFiles @ file-upload.js?v=b039f45…:239add @ file-upload.js?v=b039f45…:432_trigger @ jquery-ui.custom.js?v=b039f45…:789(anonymous function) @ jquery.fileupload.js?v=b039f45…:1037each @ jquery.min.js?v=b039f45…:2_onAdd @ jquery.fileupload.js?v=b039f45…:1030(anonymous function) @ jquery-ui.custom.js?v=b039f45…:405(anonymous function) @ jquery.fileupload.js?v=b039f45…:1235j @ jquery.min.js?v=b039f45…:2add @ jquery.min.js?v=b039f45…:2always @ jquery.min.js?v=b039f45…:2_onChange @ jquery.fileupload.js?v=b039f45…:1225(anonymous function) @ jquery-ui.custom.js?v=b039f45…:405handlerProxy @ jquery-ui.custom.js?v=b039f45…:706dispatch @ jquery.min.js?v=b039f45…:3r.handle @ jquery.min.js?v=b039f45…:3

Please note: I am using a local nginx to serve nextcloud having a mysql database on the host and the fpm in a docker container.
Should you need any further information, please don't hesitate to ask.

**Comment by rullzer** [comment]
It seems you are accessing the file directly. Which is not supported.
You are probabaly using pretty URLs but then still it should be accessed via index.php (your webserver should take care of that).

So this most likely is a miss configuration in your webserver.

**Comment by ss89** [comment]
Ahh ok, i will try fixing the nginx config then. Thanks a lot, will report back as soon as i get to it.

**Comment by ss89** [comment]
i wasn't yet able to fix the problem in my config but i can confirm that it is a configuration problem.
Since i switched from nginx to apache everything worked instantly.
Sorry for creating the issue without checking that out.
I would be looking forward if someone could post a working sample config in the nextcloud documentation. 👍 
Please close this issue as it is a configuration issue.

**Comment by ss89** [comment]
Awesome, just resolved the issue by using this nginx config: https://www.rosehosting.com/blog/install-nextcloud-on-ubuntu-16-04/

**Comment by smaug95** [comment]
Could you please describe what difference there was between you old config and the one solving your problem? I am experiencing the same problem with OwnCloud 9.0.4 on Nginx too and don't really know where to look at. I don't want to copy&paste the Nextcloud config.

**Comment by ss89** [comment]
Just watch the difference between the one in the docs for version 9 and the link i posted to rosehosting.com.
I don't have a clue either, because i didn't try it option by option.
