### ISSUE TITLE
occ migrations:migrate failes with 'Migration step ... is unknown'

### ISSUE THREAD

**Issue by mvdnes** [nextcloud/server#13547]
### Steps to reproduce
1. My installation did not have all migrations from the activity app applied, the column `object_type` was missing, amongst others. This prevented an upgrade to 15.0.2. There where also no entries mentioning the app activity in the migrations table.
2. Run `occ migrations:migrate activity`. 

### Expected behaviour
The database tables of the activity app should be updated.

### Actual behaviour
The following error was encountered:

```
user@server /usr/share/webapps/nextcloud % sudo -u http php occ -vvv migrations:migrate activity
The current PHP memory limit is below the recommended value of 512MB.
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade

In MigrationService.php line 431:

  [InvalidArgumentException]
  Migration step 'OCA\Activity\Migration\Version2006Date20170808154933' is unknown


Exception trace:
 OC\DB\MigrationService->createInstance() at /usr/share/webapps/nextcloud/lib/private/DB/MigrationService.php:446
 OC\DB\MigrationService->executeStep() at /usr/share/webapps/nextcloud/lib/private/DB/MigrationService.php:392
 OC\DB\MigrationService->migrate() at /usr/share/webapps/nextcloud/core/Command/Db/Migrations/MigrateCommand.php:64
 OC\Core\Command\Db\Migrations\MigrateCommand->execute() at /usr/share/webapps/nextcloud/3rdparty/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php:946
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /usr/share/webapps/nextcloud/3rdparty/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /usr/share/webapps/nextcloud/lib/private/Console/Application.php:213
 OC\Console\Application->run() at /usr/share/webapps/nextcloud/console.php:96
 require_once() at /usr/share/webapps/nextcloud/occ:11

migrations:migrate <app> [<version>]
```

### Server configuration

**Operating system**: Arch Linux

**Web server:** Nginx 1.14.2

**Database:** Postgresql 11.1

**PHP version:** 7.3.1

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older version

**Where did you install Nextcloud from:** The archlinux repositories

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Potential fix:

In my case, this issue was fixed by adding `\OC_App::loadApp($this->appName);` to the start of the `migrate` function of `nextcloud/lib/private/DB/MigrationService.php`. I am unsure however if this is the correct approach.

**Comment by celber** [comment]
got the same issue FYI

**Comment by nickvergessen** [comment]
The correct fix for this problem is https://github.com/nextcloud/server/issues/13549
