### ISSUE TITLE
Update to 13.0.10 fails, Column not found: 1054 Unknown column 'object_type' in 'where clause'

### ISSUE THREAD

**Issue by eyrinck** [nextcloud/server#13549]
Hi there,
I tried the update to Nextcloud 13.0.10 via the commandline updater. It runs on a debian linux on my netgear homecloud. Since I have only PHP 5.6 at the moment I could not upgrade to 14 or 15.
The updater first worked fine, but the the update ends with this protocol:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Repair step: Fix component of birthday calendars
Repair info: 6 birthday calendars updated.
Repair step: Fix broken values of calendar objects
[0 / 0]: Fix broken values of calendar objects
Repair step: Registering building of calendar search index as background job
Repair info: Repair step already executed
Repair step: Remove activity entries of private events
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'DELETE FROM `oc_activity` WHERE (`affecteduser` <> ?) AND (`object_type` = ?) AND (`object_id` = ?) AND (`subjectparams` LIKE ?)' with params ["Helmut", "calendar", "3", "%{\"id\":\"1ddc7205-de21-42c0-ac14-677612506335\"%"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'

I prooved the file rights and overwrote the installation by hand. My owncloud is many nextcloud updates away.
Somenone an idea that helps?
Thanks, Helmut

**Comment by Daryes** [comment]
Check this previous issue : 
https://github.com/nextcloud/activity/issues/309#issuecomment-436929111
You'll need to run the SQL commands directly on the nextcloud db

In the related [commit](https://github.com/nextcloud/activity/pull/310/commits/6840c638e7f45a08d2146384a29310e777299f57), these indexes might help : 
- on the oc_activity table : index 'activity_time' on 'timestamp' column
- on the oc_activity table : index  'activity_object' on ( 'object_type' ,  'object_id' ) columns

Had the same problem at the time. The indexes are optional, but will help if you are logging the activity

**Comment by eyrinck** [comment]
Thanks a lot, Problem is solved!

**Comment by pierre-alain-b** [comment]
Same problem here, fixed as recommended by running

```
ALTER TABLE `oc_activity` ADD `object_type` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL;
ALTER TABLE `oc_activity` ADD `object_id` bigint(20) NOT NULL DEFAULT '0';
```
in the database.
