### ISSUE TITLE
Failed to restore deleted folder Snafu, because of insufficient storage?

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#1354]
### Steps to reproduce
1. Delete a subfolder of a shared folder
   2 Delete another subfolder of the same shared folder.
2. go to "deleted files" and quickly click on "restore"
### Expected behaviour

The folders should be restored, of course
### Actual behaviour

Tell us what happens instead
the folders vanish, they are neither restored, nor listed under deleted files, they are simply gone without a trace, leading to serious data loss.
### Server configuration

**Operating system**:
Ubuntu Trusty
**Web server:**
apache2-suexec-pristine               2.4.7-1ubuntu4.13 

(apache ftp-suexec chrot)
**Database:**
Mysql
**PHP version:**
 php5                                  5.5.9+dfsg-1ubuntu4.19
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 9.0.53 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from Owncloud 8
**Where did you install Nextcloud from:**

from downloaded tarball

**Signing status:**

??

<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
The URL forwards back to the owncloud main page.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - calendar: 1.3.1
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - documents: 0.12.0
  - external: 1.2
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - galleryplus: 15.1.1
  - notes: 2.0.2
  - notifications: 0.2.3
  - password_policy: 1.0.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - tasks: 0.9.2
  - templateeditor: 0.1
  - theming: 0.1.0
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - files_external
  - files_pdfviewer
  - gallery
  - user_external
  - user_ldap
  - user_saml

```

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

```
</details>

**The content of config/config.php:**


<details>
<summary>Config report</summary>

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)

```

</details>


{
    "system": {
        "instanceid": "ocfe5c436587",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/user_web\/chroot\/htdocs\/***.org\/ocfiles",
        "cron.lockfile.location": "\/var\/www\/user_web\/chroot\/htdocs\/***.org\/ocfiles",
        "dbtype": "mysql",
        "version": "9.0.53.0",
        "dbname": "**_owncloud",
        "dbhost": "mysql",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "",
        "mail_smtpmode": "php",
        "mail_smtphost": "127.0.0.1",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "****",
            "owncloud.****",
            "owncloud.****",
            "owncloud.****"
        ],
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": false,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "updater.release.channel": "stable"
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": null
        },
        "appframework": {
            "enabled": "no",
            "installed_version": "0.104",
            "ocsid": "162405",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "12887"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.3.1",
            "ocsid": "168707",
            "types": ""
        },
        "calendarplus": {
            "enabled": "no",
            "installed_version": "1.1.1",
            "ocsid": "170560",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "contacts": {
            "backend_ldap": "false",
            "enabled": "yes",
            "installed_version": "1.3.1.0",
            "ocsid": "168708",
            "types": ""
        },
        "contactsplus": {
            "enabled": "no",
            "installed_version": "1.0.9",
            "ocsid": "171237",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "queued_tasks",
            "backgroundjobs_task": "OC_Cache_FileGlobal-gc",
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "global_cache_gc_lastrun": "1426723219",
            "installedat": "1380056998.77",
            "lastcron": "1473499803",
            "lastupdateResult": "[]",
            "lastupdatedat": "1473499756",
            "oc.integritycheck.checker": "[]",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_calendarplus": "calendarplus\/share.php",
            "public_calendarplusevent": "calendarplus\/shareevent.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendarplus": "calendarplus\/appinfo\/remote.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactsplus": "contactsplus\/appinfo\/remote.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "umgmt_send_email": "true",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true"
        },
        "dashboard": {
            "enabled": "no",
            "installed_version": "1.1",
            "types": ""
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "documents": {
            "converter": "off",
            "converter_url": "http:\/\/10.0.3.11:16080",
            "enabled": "yes",
            "installed_version": "0.12.0",
            "ocsid": "168711",
            "types": "",
            "unstable": "false"
        },
        "encryption": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "publicShareKeyId": "pubShare_686d31d7",
            "recoveryAdminEnabled": "1",
            "recoveryKeyId": "recovery_aac259b2",
            "types": "filesystem"
        },
        "external": {
            "enabled": "yes",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "fbsync": {
            "enabled": "no",
            "installed_version": "1.7.3",
            "ocsid": "174311",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "620",
            "backgroundwatcher_previous_folder": "2799",
            "cronjob_scan_files": "500",
            "default_quota": "1 GB",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_excel_reader": {
            "enabled": "no",
            "installed_version": "0.1.0",
            "types": "filesystem"
        },
        "files_external": {
            "enabled": "no",
            "installed_version": "0.2.3",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\Dropbox,\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP,\\OC\\Files\\Storage\\DAV"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": null
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.1a",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": null
        },
        "files_pdfviewer": {
            "enabled": "no",
            "installed_version": "0.7.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "110": "1465988041.47",
            "114": "1440790668.09",
            "117": "1468513783.18",
            "118": "1468513783.18",
            "140": "1469116607.56",
            "142": "1438790366.71",
            "220": "1461689587.15",
            "221": "1457271056.58",
            "222": "1468513783.18",
            "223": "1455655927.7",
            "224": "1468690907.97",
            "227": "1441836703.11",
            "228": "1441836703.14",
            "229": "1441826154.61",
            "232": "1446461916.13",
            "233": "1446461916.19",
            "234": "1446461916.21",
            "235": "1446461916.26",
            "237": "1446461916.24",
            "238": "1446461916.35",
            "239": "1442342826.28",
            "240": "1442159523.74",
            "241": "1442335426.14",
            "243": "1443880981.34",
            "246": "1446461916.3",
            "247": "1446461916.4",
            "248": "1450122113.74",
            "249": "1450259159.11",
            "257": "1468513783.18",
            "258": "1468513783.18",
            "261": "1457455881.94",
            "270": "1452876771.97",
            "271": "1457733047.6",
            "272": "1454153967.73",
            "276": "1469116121.14",
            "279": "1468183315.58",
            "280": "1469116211.33",
            "281": "1469116211.33",
            "282": "1469116211.33",
            "284": "1463047342.93",
            "285": "1463047342.93",
            "288": "1455277657.35",
            "289": "1455556943.06",
            "294": "1469113332.18",
            "296": "1459202961.18",
            "313": "1461828245.7",
            "314": "1469095035.02",
            "317": "1464550239.4",
            "318": "1462885220.26",
            "323": "1462885516.26",
            "324": "1462890861.95",
            "327": "1468409384.98",
            "328": "1468409384.98",
            "330": "1466170288.19",
            "331": "1466170288.19",
            "334": "1464166364.54",
            "336": "1469116211.33",
            "340": "1466364026.31",
            "341": "1466008679.63",
            "345": "1469100511.83",
            "346": "1469100511.83",
            "347": "1469091741.04",
            "359": "1468916718.82",
            "enabled": "yes",
            "incoming_server2server_share_enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "14.2.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "yes",
            "installed_version": "15.1.1",
            "ocsid": "169116",
            "types": ""
        },
        "grauphel": {
            "enabled": "no",
            "installed_version": "0.6.4",
            "ocsid": "166654",
            "types": ""
        },
        "html5_videoplayer": {
            "enabled": "no",
            "installed_version": "1.0",
            "ocsid": "173950",
            "types": ""
        },
        "imprint": {
            "enabled": "no",
            "installed_version": "0.1.15",
            "ocsid": "153220",
            "types": "base"
        },
        "journal": {
            "enabled": "no",
            "installed_version": "0.3.2",
            "types": ""
        },
        "mail": {
            "enabled": "no",
            "installed_version": "0.5.2",
            "ocsid": "169914",
            "types": ""
        },
        "media": {
            "enabled": "no",
            "installed_version": "0.4.3",
            "types": null
        },
        "music": {
            "enabled": "no",
            "installed_version": "0.1.7-beta",
            "types": "filesystem"
        },
        "news": {
            "enabled": "no",
            "installed_version": "7.1.2",
            "ocsid": "168040",
            "types": ""
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "2.0.2",
            "ocsid": "174554",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "ocusagecharts": {
            "enabled": "no",
            "installed_version": "3",
            "ocsid": "166746",
            "types": ""
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.07",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "roundcube": {
            "autoLogin": "",
            "enableDebug": "on",
            "enabled": "no",
            "installed_version": "2.5.1",
            "maildir": "\/.DahkuiW0\/",
            "rcHost": "",
            "rcNoCronRefresh": "",
            "rcPort": "",
            "rcRefreshInterval": "30",
            "removeControlNav": "",
            "removeHeaderNav": "",
            "types": ""
        },
        "storagecharts2": {
            "enabled": "no",
            "installed_version": "2.6.1",
            "ocsid": "165528",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "tal": {
            "enabled": "no",
            "installed_version": "0.2.2",
            "types": ""
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.9.2",
            "ocsid": "164356",
            "types": ""
        },
        "tasks_enhanced": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "21",
            "enabled": "yes",
            "installed_version": "0.1.0",
            "name": "Uferwerk e.G.",
            "slogan": "Gemeinsam wohnen am Gro\u00dfen Zernsee",
            "types": "",
            "url": "https:\/\/uferwerk.org"
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_external": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin"
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": null
        },
        "videos": {
            "enabled": "no",
            "installed_version": "1.0",
            "ocsid": "161584",
            "types": ""
        },
        "158433": {
            "enabled": "no"
        },
        "158434": {
            "enabled": "no"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
```

With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT \* FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
```

{"reqId":"aZEAn7ShiduXFt0cgpDu","remoteAddr":"79.199.249.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\DAV\\Exception\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('Schule\\/Mathe\\/AB...', Resource id #352, Object(OCA\\DAV\\Connector\\Sabre\\Directory), false)\n#1 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#3 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('Schule\\/Mathe\\/AB...', Resource id #352, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#9 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/remote.php(138): require_once('\\/var\\/www\\/user_j...')\n#10 {main}\",\"File\":\"\\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/lib\\/connector\\/sabre\\/quotaplugin.php\",\"Line\":108,\"User\":\"milan\"}","level":4,"time":"2016-09-10T08:23:07+00:00","method":"PUT","url":"\/remote.php\/webdav\/Schule\/Mathe\/ABC-Formel.mp4-chunking-1165859358-30-2","user":"milan"}
{"reqId":"2aHfgdu8DOWuxMjyQMF9","remoteAddr":"79.199.249.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\DAV\\Exception\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('Schule\\/Mathe\\/AB...', Resource id #352, Object(OCA\\DAV\\Connector\\Sabre\\Directory), false)\n#1 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#3 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('Schule\\/Mathe\\/AB...', Resource id #352, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#9 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/remote.php(138): require_once('\\/var\\/www\\/user_j...')\n#10 {main}\",\"File\":\"\\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/lib\\/connector\\/sabre\\/quotaplugin.php\",\"Line\":108,\"User\":\"milan\"}","level":4,"time":"2016-09-10T08:23:07+00:00","method":"PUT","url":"\/remote.php\/webdav\/Schule\/Mathe\/ABC-Formel.mp4-chunking-1165859358-30-0","user":"milan"}
{"reqId":"JwxVdshkVYF2anw9QHri","remoteAddr":"79.199.249.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\DAV\\Exception\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('Schule\\/Mathe\\/AB...', Resource id #352, Object(OCA\\DAV\\Connector\\Sabre\\Directory), false)\n#1 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1034): Sabre\\Event\\EventEmitter->emit('beforeCreateFil...', Array)\n#3 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('Schule\\/Mathe\\/AB...', Resource id #352, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#9 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/remote.php(138): require_once('\\/var\\/www\\/user_j...')\n#10 {main}\",\"File\":\"\\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/lib\\/connector\\/sabre\\/quotaplugin.php\",\"Line\":108,\"User\":\"milan\"}","level":4,"time":"2016-09-10T08:23:07+00:00","method":"PUT","url":"\/remote.php\/webdav\/Schule\/Mathe\/ABC-Formel.mp4-chunking-1165859358-30-1","user":"milan"}
{"reqId":"bKqakUBCSudj1Yb7846r","remoteAddr":"79.199.249.29","app":"files_trashbin","message":"trash bin database inconsistent!","level":3,"time":"2016-09-10T08:45:03+00:00","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/undelete.php","user":"milan"}
{"reqId":"bKqakUBCSudj1Yb7846r","remoteAddr":"79.199.249.29","app":"trashbin","message":"can't restore Desy Praktikum","level":3,"time":"2016-09-10T08:45:03+00:00","method":"POST","url":"\/index.php\/apps\/files_trashbin\/ajax\/undelete.php","user":"milan"}
{"reqId":"53wPorV7StxQbAjD2iPT","remoteAddr":"79.199.249.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\DAV\\Exception\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('Schule\\/Deutsch\\/...', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#6 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/remote.php(138): require_once('\\/var\\/www\\/user_j...')\n#7 {main}\",\"File\":\"\\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php\",\"Line\":1107,\"User\":\"milan\"}","level":4,"time":"2016-09-10T08:54:21+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/Schule\/Deutsch\/Praktikum\/Desy%20Praktikum\/Desy","user":"milan"}
{"reqId":"I8xk9ZkHkIG10aNDmLTV","remoteAddr":"79.199.249.29","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 409 Parent node does not exist\",\"Exception\":\"Sabre\\DAV\\Exception\\Conflict\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(588): Sabre\\DAV\\Server->createCollection('Schule\\/Deutsch\\/...', Object(Sabre\\DAV\\MkCol))\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpMkcol(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:MKCOL', Array)\n#4 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#6 \\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/remote.php(138): require_once('\\/var\\/www\\/user_j...')\n#7 {main}\",\"File\":\"\\/var\\/www\\/user_jrweb\\/chroot\\/htdocs\\/rohr.org\\/www\\/oc\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php\",\"Line\":1107,\"User\":\"milan\"}","level":4,"time":"2016-09-10T08:55:05+00:00","method":"MKCOL","url":"\/remote.php\/webdav\/Schule\/Deutsch\/Praktikum\/Desy%20Praktikum\/Desy","user":"milan"}

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```

Insert your Nextcloud log here

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...

```
</details>
```

**Comment by wiswedel** [comment]
Is this still happening on 16.0.1?
