### ISSUE TITLE
Unable to import validated .ics file

### ISSUE THREAD

**Issue by miskovics** [nextcloud/server#13553]
### Steps to reproduce
1. Upload .ics file to https://icalendar.org/validator.html and confirm that it reports "Success! No errors found."
2. Log in to NextCloud installation via browser
3. Open Calendar app
4. Push <kbd>Import calendar</kbd> under `Settings & import` and upload .ics file.

### Expected behaviour
File is imported successfully.

### Actual behaviour
Calendar app report: "File could not be parsed"

### Server configuration

**Operating system**:
Raspbian

**Web server:**
Apache

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
NextCloudPi 14.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
NextCloudPi

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by miskovics** [comment]
Tried to import .ics from test1.zip also on the [NextCloud demo server](https://demo.nextcloud.com/eit5cahb/apps/calendar/), same result, failed with same error message.

**Comment by danielkesselberg** [comment]
Thank you for reporting this issue :+1:

```
BEGIN:VCALENDAR
VERSION:2.0
METHOD:PUBLISH
PRODID:2019 Collective Closing days (2019-01-05 - 2020-01-03)
BEGIN:VEVENT
CREATED:20190110T012345Z
LAST-MODIFIED:20190110T012345Z
DTSTAMP:20190110T012345Z
SUMMARY:COLLECTIVE CLOSING
DTSTART;VALUE=DATE:20190531
DTEND;VALUE=DATE:20190601
URL:
DESCRIPTION:
TRANSP:TRANSPARENT
UID:COLLECTIVE_CLOSING_20190531@somedomain.com
END:VEVENT
```

http://mozilla-comm.github.io/ical.js/validator.html above ics fails when using this validator. ics is missing `END:VCALENDAR` below `END:VEVENT` (https://tools.ietf.org/html/rfc5545#section-3.4). Was this broken ics created by nextcloud calendar?

**Comment by miskovics** [comment]
You are right, I added the missing `END:VCALENDAR` line and in spite of the 'contains incompatible objects' warning now the file is imported successfully. Thank you very much for your help!

The file was not created by NextCloud calendar, but is a file from a website, modified by hand. Probably during this manual edition the last line was accidentally deleted.

The problem reported here is not a bug, so closing it.
