### ISSUE TITLE
Calendar Invitations for plain mail are poorly formattet

### ISSUE THREAD

**Issue by JonasDralle** [nextcloud/server#13555]
First off: it's really nice that NextCloud sends HTML emails as `multipart/mixed` and that they put some thought into the `text/plain` segment. I really appreciate this.
There's still room for improvement IMHO.

## What's wrong and how could it be improved?
Plain invitations look like this:
![plain email displaying "meh" formatting](https://user-images.githubusercontent.com/6533815/51083864-4a55b000-1721-11e9-924f-24c747729f00.png)
(another image: [HTML version of the same invitiation redered via Gecko engine](https://user-images.githubusercontent.com/6533815/51083912-f8f9f080-1721-11e9-807f-b17ffb748d6b.png))

### Personally I see three issues:
- Lacking event title. Sure it's in the mail subject but it's important enough to repeat
   - E-Mail subjects behave more like a micro-promotion to consider "Is this worth reading?"
   - the subject line is usually forgotten upon clicking the mail (test on self, sample size = 1)
- Description of Invitiation-Properties are at the end of the line.
   - a question is answered before asked ("Saturday.", "When?")
   - it's very clear that the reader is regarded as a second thought (especially due to the colons)
- inline URLs which are long and can wrap around.

### Proposed changes:
- Add title
- Format Properties in a more straightforward manner and/or change the wording of the property name
- move the URLs at the end of the mail

This is the current formatting:
```
Hello [contact],

  * Fri, Feb 1, 2019, 8:00 AM - 9:00 AM (Europe/Berlin) (When:)
  * Some cool place (Where:)
  * everyone pls bring some food! (Description:)
Accept: [real long accept url]
Decline: [real long decline url]

More options at [real long more url]


-- 
Nextcloud - a safe home for all your data
This is an automatically sent email, please do not reply.
```

This can be considered to be a better formatting:
```
Hello [contact],

  * What:         Picnic
  * When:         Fri, Feb 1, 2019, 8:00 AM - 9:00 AM (Europe/Berlin)
  * Where:        Some cool place
  * Description:  everyone pls bring some food!

Use the links below to [Accept], [Decline] or see [More options].

[Accept]: [real long accept url]

[Decline]: [real long decline url]

[More options]: [real long more url]

-- 
Nextcloud - a safe home for all your data
This is an automatically sent email, please do not reply.
```

This way of formatting links is in line with the [Markdown link sytnax](https://tools.ietf.org/html/rfc7763#section-1.2) (RFC 7763, page 4) which is a very readable format even for people not fond of markdown.

Please be aware of how spacings are used for indentation since the specific tab character configuration of the reader is unknown.

Perhaps add a linebreak after `Description:` to not folly around with multiline descriptions

Perhaps lose the uppercase for the links. `[accept]` instead of `[Accept]`. Your call.

### Assumptions:
- People who read plain likely use a monospaced font (otherwise the spacing will be off)
- People who read plain are not put off by brace-based markdown syntax

---

I'd like to nominate this issue for being tagged as `good first issue `, `papercut`, `low`, `feature: accessibility`, `feature: emails`.

**Comment by grindlewald9000** [comment]
This ticket is in desperate need of triage

**Comment by brad2014** [comment]
I'd like to integrate the suggestions here into the issue #12391, track progress there, and close this issue.  OK?

**Comment by JonasDralle** [comment]
Sure thing. I copied the description of this issue over to [this comment](https://github.com/nextcloud/server/issues/12391#issuecomment-531575101).
If it's too long I can wrap it into a `<detail>` or rephrase.

I thought about doing this myself but right now I don't have the resources for this, sorry.
