### ISSUE TITLE
External Storage and indexing

### ISSUE THREAD

**Issue by PhieF** [nextcloud/server#13559]
Hi

**Is your feature request related to a problem? Please describe.**
Adding a large hard drive to external storage can fill the database with a lot of files that slows down mysql a lot

**Describe the solution you'd like**
It'd like to be able to disable auto indexing for some external storage, so as it would be indexed only when visiting them, and to forbid users to index their external storages

Thanks for your work ! :)

**Comment by skjnldsv** [comment]
cc @icewind1991 does it make sense?
