### ISSUE TITLE
Allow external image processing libraries

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#13551]
Our default image processing backend if gd. Even if the previews are provided by a 3rdparty provider the scaling is still done by a gd backend. Which is not the fastest.

I was thinking of allowing users to configure an optional different backend to handle the images. For example I have been using https://github.com/h2non/imaginary in other projects. it is fast, scaleable and works as advertised.

Of course the default GD backend should stay as the default. But for people that want more performance out of their nextcloud I think this could be a nice boost (jus the same as we allow people to configure redis for locking).

@MorrisJobke @ChristophWurst @skjnldsv @juliushaertl opionions?

**Comment by rullzer** [comment]
At least partly yes

**Comment by MorrisJobke** [comment]
Sounds sane and allows to pinpoint performance bottlenecks 👍 Separation of concerns often helps to also isolate possible security issues by not allowing this rendering farm to have any external communication.

**Comment by enoch85** [comment]
Not being a PHP dev, why not use the one with better performance as the default one? We all want NC to fly! :)

**Comment by Alexandero89** [comment]
Hello,
was there any progress at this topic? ;)

**Comment by nachoparker** [comment]
Oh! I found this discussion a bit too late. I was playing with extending `OC_Image` with a `OC_Image_JPEG` class that uses Imagick and I was able to achieve better performance.

See https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/

**Comment by acs-ferreira** [comment]
This would be indded a great value for big NC instances with a lot of pictures. A scalable (external) processor is a must-have!

**Comment by maanloper** [comment]
@rullzer any updates on this? Seems to me these days https://github.com/h2non/imaginary supports all relevant formats.

**Comment by pachulo** [comment]
Maybe now that [this has been merged](https://github.com/nextcloud/server/pull/24166) this issue can be closed?

**Comment by solracsf** [comment]
Closing as per https://github.com/nextcloud/server/pull/24166
