### ISSUE TITLE
Can't dismiss "send usage report" notification

### ISSUE THREAD

**Issue by RockyTV** [nextcloud/server#1356]
I recently updated my Nextcloud server to version 10 and I'm getting a notification asking if I want to share setup and usage data to help improve Nextcloud. Clicking any button fails to dismiss the notification.

### Steps to reproduce
Can't find a way to reproduce.

### Expected behaviour
The notification should be dismissed and data should either not be sent (in case the user chose not now), or it should be sent.

### Actual behaviour
Fails with "failed to perform action"

### Server configuration
**Operating system**: Debian 8

**Web server:** nginx

**Database:** mysql 10.0.26

**PHP version:** 5.6.24

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** older Nextcloud install

**Where did you install Nextcloud from:** Nextcloud's website (nextcloud.com)

**Comment by nickvergessen** [comment]
https://help.nextcloud.com/t/my-experience-upgrading-to-nc10rc1/2444/12?u=nickvergessen

**Comment by nickvergessen** [comment]
@schiessle seems like those notifications sometimes get created with invalid URLs (before `overwrite.cli.url` is correctly set). I think we should modify the urls while preparing for display, to avoid this problem in the future.

**Comment by nickvergessen** [comment]
@RockyTV can you check which URL gets called, when you press a button on the notification?
Press `F12` and switch to `Network` before pushing the button.

**Comment by mgiljum** [comment]
FYI, I'm still having this issue and there are no rows in the table [referenced here](https://help.nextcloud.com/t/my-experience-upgrading-to-nc10rc1/2444/12?u=nickvergessen). Any other way to dismiss this notification in the Windows client?

**Comment by nickvergessen** [comment]
Try restarting the sync client. It seems that the sync client does not drop deleted notifications

**Comment by mgiljum** [comment]
Odd, I thought I had tried that, but it's gone now. Thanks, sorry to revive an old issue.

**Comment by vranki** [comment]
NextCloud 19 is doing this - a regression?

**Comment by nickvergessen** [comment]
Anything in your log file?
