### ISSUE TITLE
Update to 14.06: Calendar Repair fails

### ISSUE THREAD

**Issue by Gadget22** [nextcloud/server#13563]
### Steps to reproduce
1. update from 14.0.5 to 14.06 (internal updater)
2. select database upgrade via webinterface
3. upgrade stopped with error massage:
"Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'DELETE FROM `oc_activity` WHERE (`affecteduser` <> ?) AND (`object_type` = ?) AND (`object_id` = ?) AND (`subjectparams` LIKE ?)' with params ["nina", "calendar", "3", "%{\"id\":\"36fa5741cd\"%"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'"

### Expected behaviour
flawless update of database

### Actual behaviour
Stop of update

### Server configuration

**Operating system**: Linux (managed webspace at Webgo.de)

**Web server:** Apache

**Database:** MySQL

**PHP version:7.2

**Nextcloud version: 14.0.5 to .0.6

**Updated from an older Nextcloud/ownCloud or fresh install: update

```
Full error log:
(sorry for German, important massages are in english)


Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Repair step: Fix component of birthday calendars

Repair info: 8 birthday calendars updated.

Repair step: Fix broken values of calendar objects

[0 / 0]: Fix broken values of calendar objects

Repair step: Registering building of calendar search index as background job

Repair info: Repair step already executed

Repair step: Remove activity entries of private events

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'DELETE FROM `oc_activity` WHERE (`affecteduser` <> ?) AND (`object_type` = ?) AND (`object_id` = ?) AND (`subjectparams` LIKE ?)' with params ["nina", "calendar", "3", "%{\"id\":\"36fa5741cd\"%"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

**Comment by rokube** [comment]
I'm experiencing the same issue.

I'm on version 15.0.2.

The SQL error:

```sql
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'object_type' in 'where clause'
```
in the `oc_activity` table complains about the `object_type` column.
However, having a look at the table myself shows no `object_id` column either (the other two columns exist).

```sql
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while 
executing 'DELETE FROM `oc_activity` WHERE (`affecteduser` <> ?) AND 
(`object_type` = ?) AND (`object_id` = ?) AND (`subjectparams` LIKE ?)' with params [....
```

**Comment by rokube** [comment]
It appears this issue may be related to #13549.

**Comment by MorrisJobke** [comment]
cc @rullzer @nickvergessen

**Comment by Gadget22** [comment]
Solution for #13549  worked for me as well. 
Here the link to the comment with the sql commands to clean up the db: 
https://github.com/nextcloud/activity/issues/309#issuecomment-436929111

Thanks a lot, everyone!
