### ISSUE TITLE
Update to 14.0.6, Check for expected files The following extra files have been found: .rnd

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/server#13568]
### Steps to reproduce
Current version is 14.0.4.
Update to Nextcloud 14.0.6 available. (channel: "stable")

### Expected behaviour
The updater works and I have the new version

### Actual behaviour
I get an error message:

Check for expected files
The following extra files have been found: .rnd

## Server configuration detail

**Operating system:** Linux 4.9.0-0.bpo.3-amd64 #1 SMP Debian 4.9.30-2+deb9u5~bpo8+1 (2017-09-28) x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 5.7.20

**PHP version:** 

7.2.13-1+0~20181207100623.13+jessie~1.gbpf57305
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bcmath, bz2, calendar, ctype, curl, dba, dom, enchant, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, interbase, intl, json, ldap, exif, mysqli, odbc, pdo_dblib, PDO_Firebird, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, readline, recode, shmop, SimpleXML, snmp, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh!

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_audit: 1.4.0
 - apporder: 0.6.0
 - bookmarks: 0.15.1
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - contacts: 2.1.8
 - dav: 1.6.0
 - encryption: 2.2.0
 - end_to_end_encryption: 1.0.5
 - external: 3.1.0
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_downloadactivity: 1.3.0
 - files_mindmap: 0.0.11
 - files_pdfviewer: 1.3.2
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - gallery: 18.1.0
 - gpxmotion: 0.0.8
 - groupfolders: 2.0.2
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - metadata: 0.8.0
 - mindmaps: 0.1.0
 - nextcloud_announcements: 1.3.0
 - notes: 2.5.1
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - provisioning_api: 1.4.0
 - serverinfo: 1.4.0
 - spreed: 4.0.2
 - support: 1.0.0
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - tasks: 0.9.8
 - theming: 1.5.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_usage_report: 1.1.1
 - workflowengine: 1.4.0
Disabled:
 - comments
 - federation
 - files_external
 - firstrunwizard
 - ocsms
 - richdocuments
 - sharebymail
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "200604.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "http:\/\/200604.de",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpauth": 1,
    "updater.release.channel": "stable",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:56.0; Waterfox) Gecko/20100101 Firefox/56.2.6

**Operating system:** Windows 7 

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/server/issues/12726#issuecomment-443138344

Those files are wrongly there. Remove it from that directory and then the update should go fine. Have also a look at the linked comment and it's explanation

**Comment by Schneehexe** [comment]
But where are the directoy with the .rnd files? I can not find such files?

Am 14. Januar 2019 09:57:17 MEZ schrieb Morris Jobke <notifications@github.com>:
>See
>https://github.com/nextcloud/server/issues/12726#issuecomment-443138344
>
>Those files are wrongly there. Remove it from that directory and then
>the update should go fine. Have also a look at the linked comment and
>it's explanation 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/13568#issuecomment-453935323

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by MorrisJobke** [comment]
it's right in your Nextcloud root directory. As it is a hidden file you maybe want to use `ls` with an option: `ls -la`

**Comment by meneer** [comment]
This issue may be closed, but it happens at every update. So everytime I have to manually delete the bloody file from my (very default) server.
Where does the file come from? Why?
Can the updater not be configured to either leave the file or remove it on my behalf?

**Comment by expressrussian** [comment]
Nextcloud creates this file. Nobody else. And then nextcloud whines about its own file (does not give its location) and refuses to update. This happens already for 4th time.
Why guys you generate this .rnd file and then hate this file so much, that cannot just ignore or replace it?

**Comment by kesselb** [comment]
https://www.openssl.org/docs/man1.1.0/apps/rand.html
https://www.howtogeek.com/forum/topic/what-the-heck-is-an-rnd-file

These files are related to openssl. Nextcloud use openssl. I'm not sure under which circumstances these files are created. I never noticed this on any of my instances.

You could use find to look for these files: `find . -name "*.rnd"`

**Comment by Akaemeka** [comment]
this is okay

**Comment by proovit** [comment]
still there.. fresh install:
Update to Nextcloud 16.0.7 available. (channel: "production")
