### ISSUE TITLE
Web based updater: Update just possible for admins

### ISSUE THREAD

**Issue by Somebodyisnobody** [nextcloud/server#13560]
**Current situation**
At them moment everyone can start the update, the others have to wait in the maintenance mode.
As admin I want to see what happens, which apps will be deactivated etc.

**Describe the solution you'd like**
My idea to the workflow is following:
Admin clicks in the updater-preperation "No (web based updater)", the maintenance mode will be activated for all users (signed in/signed out) exempt for admins (by reading session cookie?).
Additional a warning for admins which have not inizialized the update but want to update. The warning could be "The admin "$username" started the update. Are you sure to continue?"

That's the way how to ensure that the admin keeps control with the web based updater.

**Comment by danielkesselberg** [comment]
> At them moment everyone can start the update, the others have to wait in the maintenance mode.
As admin I want to see what happens, which apps will be deactivated etc.

I cannot confirm this for Nextcloud 14. Only users in the group admin are able to access the updater. Are u sure that everyone can start the update?

Just as additional hint. You can disable the web based updater: https://github.com/nextcloud/server/blob/54093e2bd6af535e4a70f986f83398b852d49174/config/config.sample.php#L1632-L1635

**Comment by Somebodyisnobody** [comment]
I don't mean this dialog:
![1](https://user-images.githubusercontent.com/35230554/51087905-81e04e80-1759-11e9-9161-655d0d99a26a.png)
That's what I mean with "inizializing" or "preparation".

I mean this dialog **after** preparation (the actual update), I can also access with the browser's private mode:
![2](https://user-images.githubusercontent.com/35230554/51087925-ddaad780-1759-11e9-8b79-b1c1b412b5e1.png)
Everyone can do the update in this status. With a single-user-cloud no problem but with multiple users it will be a problem

**Comment by skjnldsv** [comment]
I mean, what kesselb said, by setting up upgrade.disable-web you will deny the web page you screenshoted above :thinking:

**Comment by Somebodyisnobody** [comment]
Of couse I know that I can disable the web updater but that's not the solution if I want to use the web updater. Is it so complicated to check the client's cookie wether the current user is logged in as admin or not?

**Comment by skjnldsv** [comment]
If the update include database change or login code change, there is no way to authenticate as an admin. The code might be completely different.

**Comment by Somebodyisnobody** [comment]
hmmmm okay. And what if the updater sets an "updatetoken" which will be stored in a temporary file beside the update log? This token could be used as get-argument in the adress bar.

**Comment by skjnldsv** [comment]
That is an interesting idea. Let's ping the appropriate people see if this is something that make sense in the long run or not :)
@rullzer @ChristophWurst @blizzz @nickvergessen ? Thoughts?

**Comment by Somebodyisnobody** [comment]
And if the nerdy admin losts this token (e.g. closing the tab and calling the indexpage directly) he can still upgrade via cli.

**Comment by rullzer** [comment]
If somebody wants to submit a PR be my guest we can always look at it. But this behavior has been there for ages. Use the cli and the config setting if you want to be really sure.

**Comment by skjnldsv** [comment]
There you go!

> As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by skjnldsv** [comment]
Yeah, I guess this is a good example of a feature taht seems to much of a niche :(
Sorry @Somebodyisnobody ! Thank you for suggesting this !
