### ISSUE TITLE
Actions menu order (delete just below download)

### ISSUE THREAD

**Issue by patricksebastien** [nextcloud/server#13562]
Using nextcloud 14.0.4 the "Actions" menu have a dangerous order:
- ...
- Download
- Delete

Some users click on Delete instead of Download, I think it would be better to move Download at the top of this menu.

**Comment by skjnldsv** [comment]
cc @nextcloud/designers

**Comment by GretaD** [comment]
We can either move _download_ one up. Or add a separator for _delete_, i.e 
![menu_separator](https://user-images.githubusercontent.com/12728974/68028018-1ea5b580-fcb4-11e9-88aa-fdb221c081cc.png)

**Comment by ma12-co** [comment]
Nice example @GretaD, I'm a fan of both moving `delete` to the bottom and using a separator :)

**Comment by jancborchardt** [comment]
Yes, let’s add a separator, good call! The order is nice and cross-platform this way so let’s not mess with that. :)

**Comment by CHRINIMUE** [comment]
Is someone at that? If not I could start... 🙃

**Comment by szaimen** [comment]
> Is someone at that? If not I could start... 🙃

Please go ahead 👍

**Comment by patricksebastien** [comment]
It is now one up I think, closing...
