### ISSUE TITLE
Pyocclient and NC 13 don't error on false login

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#13561]
### Steps to reproduce
1. Get `pyocclient`
2. Try connect to your Nextcloud with wrong credentials

```
import owncloud
oc = owncloud.Client("https://example.org/nextcloud")
oc.login("non-existing-user", "randomPw")
```

### Expected behaviour
Like for ownCloud, I expect a 401 authentication error.

### Actual behaviour
Nothing, you can't tell if the login was successful or not.

The login()-procedure tries to gather the capabilities of the server, that is where the ownCloud server throws an error, Nextcloud just returns a result:

```
{'bruteforce': {'delay': '400'},
 'theming': {'background': 'https://example.org/nextcloud/core/img/background.png?v=3',
  'background-default': '1',
  'background-plain': None,
  'color': '#057BC9',
  'color-element': '#057BC9',
  'color-text': '#ffffff',
  'logo': 'https://example.org/nextcloud/core/img/logo.svg?v=3',
  'name': 'Nextcloud',
  'slogan': 'a safe home for all your data',
  'url': 'https://nextcloud.com'}}
```

Is there a reason why this information is available without authentication? It does not seem to include useful information for unauthenticated access like if federated sharing or something is supported.

**Nextcloud version:** NC 13.0.8

**Comment by kesselb** [comment]
Is that still happening? https://github.com/owncloud/pyocclient/pull/222 there is a reports that it works with NC 15.

**Comment by tflidd** [comment]
> Is that still happening? [owncloud/pyocclient#222](https://github.com/owncloud/pyocclient/pull/222) there is a reports that it works with NC 15.

You can login but if you use wrong credentials, you don't get an error. It throws an 401 later, so you will know.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/core/Controller/OCSController.php#L102-L106

Looks intended.

cc @blizzz @rullzer is there anything we can do? I guess this needs to be fixed with pyocclient.

**Comment by tflidd** [comment]
We could check for the `core` entry in the response if a `webdav-root` is sent.

`{'core': {'pollinterval': '60', 'webdav-root': 'remote.php/webdav'},`

Would be nice if we could not just login as a user and also use it just to connect to shared folders (if shared by link).

**Comment by blizzz** [comment]
This should be fixed with pyocclient imho. It's better and more useful to avoid a hack for a strange behaviour of another client tool, especially when it is open source. The capabilities endpoint is not an authentication source.

**Comment by tflidd** [comment]
It is not very active but I like to keep it open until we fixed this issue, even if it's in the pyocclient.

**Comment by tflidd** [comment]
I just looked at the request package in python. You set the username and password in a variable, to verify you must call something that requires authentication to verify if they are correct (e.g. github api: https://realpython.com/python-requests/#authentication). Do we have a suitable end point in Nextcloud to avoid using capabilities?

**Comment by kesselb** [comment]
https://github.com/owncloud/pyocclient/blob/b9e1f04cdbde74588e86f1bebb6144571d82966c/owncloud/owncloud.py#L353-L361

Into the blue: We could call `list` here (which emits a propfind). This should fail due the wrong credentials.

**Comment by tflidd** [comment]
> The capabilities endpoint is not an authentication source

Could you help us what authentication source could be used?

**Comment by blizzz** [comment]
The WebDAV endpoint for instance, `https://my.nextcloud.server/remote.php/webdav/`, it demands auth.

**Comment by szaimen** [comment]
I'd say this needs to be fixed in pyocclient, no?

**Comment by blizzz** [comment]
> I'd say this needs to be fixed in pyocclient, no?

si
