### ISSUE TITLE
When S3 is mounted, all users can see each other`s files

### ISSUE THREAD

**Issue by mistletoe91** [nextcloud/server#13565]
### Steps to reproduce
1. Mount a S3 bucket through admin user
2. Login as User A, create a folder "testa"
3. Login as User B. User B can see folder "testa" 

### Expected behaviour
Each user should have theiw own space in bucket 
Bucket1/userA
Bucket1/userB

### Actual behaviour
 Just like local disk the external disk should produce same behaviour. i.e. each user have their own space in bucket. I cannot create 100s of buckets, 1 per user because AWS has soft limit of 100 buckets and 1000 hard limit. 

### Server configuration

**Operating system**: Ubuntu 

**Web server:**
LAMP

**Database:**
Mysql 
**PHP version:**
5.7
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ulyssesp** [comment]
Seeing this happen. Is there a fix?

**Comment by kesselb** [comment]
> Seeing this happen. Is there a fix?

No.  I see to workarounds:

1) Use [object storage](https://docs.nextcloud.com/server/16/admin_manual/configuration_files/primary_storage.html) to store user files on s3.
2) [Access control](https://docs.nextcloud.com/server/16/admin_manual/file_workflows/access_control.html) might work for simpler use cases.

**Comment by ulyssesp** [comment]
Object storage is exactly what I needed, thanks.

**Comment by kesselb** [comment]
> I cannot create 100s of buckets, 1 per user because AWS has soft limit of 100 buckets and 1000 hard limit.

Yes. For such setups we recommend object storage.
