### ISSUE TITLE
unable to grant access to user with spaces in username. (windows 10 client)

### ISSUE THREAD

**Issue by KBlixt** [nextcloud/server#13569]
so yeah, I'm unable to grant access to my server from my windows 10 machine because I have a space in my user name. I get prmpted to log in after pointing to my server and log in works well but then When I should click "grant access" the loading wheel just spins for ever... logging in to any account without a space in the user name works as expected.

am I missing something or is this a bug? 

I'm running the latest mariadb/nexcloud docker releases on an Ubuntu 18.04 machine and trying to access it from the latest windows 10 client. I don't think that anything that I've configured on my server should affect this since I can login to my server from my android client as well as the browser client. 

I'm watching the log table while the loading wheel spins and the only thing that appear there are two failed login attempts at approximately 30 seconds intervals after pressing the "grant access" button. (although I think the 30 seconds intervals is a result of that my ip address have failed too many log in attempts.)

don't know how to troubleshoot this any further.

**Comment by frhun** [comment]
I can confirm on 15.0.2.0

**Comment by Wikinaut** [comment]
I have the same error here on Linux Mint 19.3 with 

* nextcloud-client 2.5.1-20181204
* Nextcloud server 15.0.4

An existing account on the server with a whitespace (example "John Doe") worked well until today, when I removed the account on the client and wanted to reconnect - but this fails for account names with a space in it!

(Remark: I tested the reinstallation of "John Doe" on my Android: this works as expected.)

Recently, @tobiasKaminsky fixed a whitespace account name issue ( https://github.com/nextcloud/android-library/pull/245 ) for fixing https://github.com/nextcloud/android/issues/3551 .

Perhaps, a similar bug is in the 2.5.1 client?

**Comment by tobiasKaminsky** [comment]
@camilasan @rullzer

**Comment by rullzer** [comment]
Fixed in upcomming 2.5.2
