### ISSUE TITLE
Allow create but not view when sharing

### ISSUE THREAD

**Issue by etlweather** [nextcloud/server#1357]
This is probably a strange scenario, but I'm wondering if it would be possible to add a feature such that:
1. As an administrator, I can create a folder and share it with members of Group A.
2. Members of Group A can add files to the folder, but not view the content (they could view the files they made but not more).

Basically, I have a set of requirements for file sharing which I'm looking to see if Nextcloud can be used for.

I need to set up "drop box" where users can drop files to specific users and only the recipient can pick up the files. Users CANNOT be allowed to share files with all other users. Only to a "drop box" and only the designated user can view what is in the drop box.

**Comment by rullzer** [comment]
We have this `files drop` feature. But that is for link shares. But should allow you to setup a drop box.

**Comment by etlweather** [comment]
@rullzer - Thanks. That would almost work, but I unfortunately need more control.

**Comment by MorrisJobke** [comment]
As we want to slim down the share permissions (see #8479) I would close this ticket here. Sorry for the bad news.
