### ISSUE TITLE
error install php modul to finish install

### ISSUE THREAD

**Issue by lingotacro** [nextcloud/server#13589]
PHP seems to be configured to remove PHPdoc blocks from the code. This makes several basic applications inaccessible.

The reason is probably the use of a cache / accelerator such as Zend OPcache or eAccelerator.

**Comment by MorrisJobke** [comment]
Disable the removal of comments like it is described in the docs: https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html#enable-php-opcache


```
opcache.save_comments=1
```

It is required that they stay in the code.
