### ISSUE TITLE
Upgrade requirement causes issues with restoring a backup

### ISSUE THREAD

**Issue by TheLastProject** [nextcloud/server#13590]
When trying to restore a backup, not all steps can be done if an update is available, making backup restoring more complex and less reliable. 

### Steps to reproduce
1. Restore a backup
2. Run `sudo -u www-data /var/www/nextcloud/occ maintenance:data-fingerprint` to renew the fingerprints as per https://docs.nextcloud.com/server/14/admin_manual/maintenance/restore.html?highlight=data%20fingerprint.

### Expected behaviour
The data-fingerprint command should be run.

### Actual behaviour
The data-fingerprint command is not run and following message is shown:
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
```

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 14.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** NextCloud website

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
