### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#13597]
### Steps to reproduce
1. Upgrade NC from 14 to 15 using the instructions here: https://docs.nextcloud.com/server/15/admin_manual/maintenance/manual_upgrade.html (see bug: https://github.com/nextcloud/documentation/issues/1142)

2. Visit your website

### Expected behaviour

I expect a login screen.

### Actual behaviour

I get this error:

```
The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

    Remote Address: <private>
    Request ID: nI04wIe4C2WrAAVG4KBV
    Type: OCP\Files\NotFoundException
    Code: 0
    Message:
    File: /var/www/nextcloud/lib/private/Files/Node/Node.php
    Line: 97


Trace

#0 /var/www/nextcloud/lib/private/Files/Node/Node.php(216): OC\Files\Node\Node->getFileInfo()
#1 /var/www/nextcloud/lib/private/Files/Node/Node.php(117): OC\Files\Node\Node->getPermissions()
#2 /var/www/nextcloud/lib/private/Files/Node/File.php(64): OC\Files\Node\Node->checkPermissions(2)
#3 /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php(104): OC\Files\Node\File->putContent('/**\n * @copyrig...')
#4 /var/www/nextcloud/lib/private/Template/SCSSCacher.php(309): OC\Files\SimpleFS\SimpleFile->putContent('/**\n * @copyrig...')
#5 /var/www/nextcloud/lib/private/Template/SCSSCacher.php(153): OC\Template\SCSSCacher->cache('/var/www/nextcl...', '339f-319d-jquer...', 'jquery-ui-fixes...', Object(OC\Files\SimpleFS\SimpleFolder), '/core/css')
#6 /var/www/nextcloud/lib/private/Template/CSSResourceLocator.php(109): OC\Template\SCSSCacher->process('/var/www/nextcl...', 'core/css/jquery...', 'core')
#7 /var/www/nextcloud/lib/private/Template/CSSResourceLocator.php(61): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/var/www/nextcl...', 'core/css/jquery...')
#8 /var/www/nextcloud/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/jquery-ui-f...')
#9 /var/www/nextcloud/lib/private/TemplateLayout.php(286): OC\Template\ResourceLocator->find(Array)
#10 /var/www/nextcloud/lib/private/TemplateLayout.php(195): OC\TemplateLayout::findStylesheetFiles(Array)
#11 /var/www/nextcloud/lib/private/legacy/template.php(211): OC\TemplateLayout->__construct('user', 'files')
#12 /var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php(157): OC_Template->fetchPage(Array)
#13 /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(119): OCP\AppFramework\Http\TemplateResponse->render()
#14 /var/www/nextcloud/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#15 /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#16 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#17 /var/www/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#18 /var/www/nextcloud/lib/base.php(987): OC\Route\Router->match('/apps/files/')
#19 /var/www/nextcloud/index.php(42): OC::handleRequest()
#20 {main}
```

The file ` /var/www/nextcloud/lib/private/Files/Node/Node.php` exists.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2

**Database:** mariaDB (& redis)

**PHP version:** 7.0.32

**Nextcloud version:** 15 

**Updated from an older Nextcloud/ownCloud or fresh install:** from 14

**Where did you install Nextcloud from:** What does this question mean?

**Signing status:** What does this question mean?
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
I can't do that because I can't log in.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
root@nextcloud:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
root@nextcloud:/var/www/nextcloud# sudo -u www-data php occ config:list system  
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.mydomain.com",
            "files.mydomain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.mydomain.com",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "loglevel": 2,
        "debug": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
"updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

### Client configuration
**Browser:**

Firefox

**Operating system:**

Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
error.log is blank
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Do you really want this?  It looks like a lot of HTML.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
What do you want here?  I don't get browser errors so do you need this?
```
</details>

**Comment by evertvanvliet** [comment]
Same issue here, I first upgraded from Ubuntu 16.04 to 18.04 then used the upgrader in nextcloud web to upgrade from 13 to 14. I now have exactly the same issues. My mobile nextcloud app although still works fine. So I guess it has something to do with the changes from PHP 7.0 to 7.2.

I'm still stuck. Did you already found a solution?

**Comment by evertvanvliet** [comment]
My message is:


Nextcloud
Interne serverfout

De server was niet in staat je aanvraag te verwerken.

Stuur de hieronder afgebeelde technische details naar de server beheerder wanneer dit opnieuw gebeurt.

Meer details in de serverlogging,
Technische details

    Extern adres: 145.132.79.61
    Aanvraag ID: 5ERGEaxLb1Y47yWch3AX
    Type: OCP\Files\NotFoundException
    Code: 0
    Boodschap:
    Bestand: /var/www/html/nextcloud/lib/private/Files/Node/Node.php
    Regel: 97


Trace

#0 /var/www/html/nextcloud/lib/private/Files/Node/Node.php(216): OC\Files\Node\Node->getFileInfo()
#1 /var/www/html/nextcloud/lib/private/Files/Node/Node.php(117): OC\Files\Node\Node->getPermissions()
#2 /var/www/html/nextcloud/lib/private/Files/Node/File.php(64): OC\Files\Node\Node->checkPermissions(2)
#3 /var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php(104): OC\Files\Node\File->putContent(':root {\n\t\t\t\t--i...')
#4 /var/www/html/nextcloud/lib/private/Template/IconsCacher.php(123): OC\Files\SimpleFS\SimpleFile->putContent(':root {\n\t\t\t\t--i...')
#5 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(298): OC\Template\IconsCacher->setIconsCss('/**\n * @copyrig...')
#6 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(153): OC\Template\SCSSCacher->cache('/var/www/html/n...', '904f-3223-serve...', 'server.scss', Object(OC\Files\SimpleFS\SimpleFolder), '/nextcloud/core...')
#7 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(109): OC\Template\SCSSCacher->process('/var/www/html/n...', 'core/css/server...', 'core')
#8 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(61): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/var/www/html/n...', 'core/css/server...')
#9 /var/www/html/nextcloud/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/server')
#10 /var/www/html/nextcloud/lib/private/TemplateLayout.php(285): OC\Template\ResourceLocator->find(Array)
#11 /var/www/html/nextcloud/lib/private/TemplateLayout.php(201): OC\TemplateLayout::findStylesheetFiles(Array)
#12 /var/www/html/nextcloud/lib/private/legacy/template.php(210): OC\TemplateLayout->__construct('user', 'files')
#13 /var/www/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php(157): OC_Template->fetchPage(Array)
#14 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(119): OCP\AppFramework\Http\TemplateResponse->render()
#15 /var/www/html/nextcloud/lib/private/AppFramework/App.php(118): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'index')
#16 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('ViewController', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#17 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#18 /var/www/html/nextcloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#19 /var/www/html/nextcloud/lib/base.php(987): OC\Route\Router->match('/apps/files/')
#20 /var/www/html/nextcloud/index.php(42): OC::handleRequest()
#21 {main}

**Comment by stone212** [comment]
For me the problem was file permissions and usually it is specifically the data directory.

**Comment by treba123** [comment]
Since today I get the exact same error. Already reset the permissions, upgraded to latest point release.... @stone212, was anything special about you setup to trigger this?

**Comment by stone212** [comment]
@treba123 Nothing special but I found the problem was that the file permissions on the `data` directory were wrong.  Do you have a `data` directory?  Are the file permissions correct?  I have this note written down under "Nextcloud":

```
cd /var/www
chown -R www-data:www-data nextcloud
find nextcloud/ -type d -exec chmod 750 {} \;
find nextcloud/ -type f -exec chmod 640 {} \;
```

**Comment by treba123** [comment]
@stone212: thx for the answer! Yeah that was what I ended up doing, too, on program and data directory. Didn't directly work, but at some point I rebooted again and...well, now it works again :)

The thing is, my data directory is on a smb share, mounted via systemd-automount. So I thought maybe somewhere down that road something is wrong.

**Comment by prezine** [comment]
> @treba123 Nothing special but I found the problem was that the file permissions on the `data` directory were wrong. Do you have a `data` directory? Are the file permissions correct? I have this note written down under "Nextcloud":
> 
> ```
> cd /var/www
> chown -R www-data:www-data nextcloud
> find nextcloud/ -type d -exec chmod 750 {} \;
> find nextcloud/ -type f -exec chmod 640 {} \;
> ```

Of course helpful, this is a perfect fix

**Comment by abrahamboray** [comment]
> @treba123 Nothing special but I found the problem was that the file permissions on the `data` directory were wrong. Do you have a `data` directory? Are the file permissions correct? I have this note written down under "Nextcloud":
> 
> ```
> cd /var/www
> chown -R www-data:www-data nextcloud
> find nextcloud/ -type d -exec chmod 750 {} \;
> find nextcloud/ -type f -exec chmod 640 {} \;
> ```

This one has worked for me.
Saved my time boy, thank you.
