### ISSUE TITLE
calender share link should be generated more generally

### ISSUE THREAD

**Issue by brunt82** [nextcloud/server#13603]
**Is your feature request related to a problem? Please describe.**
See #5881. In described issue it will be possible to change the owner of a calendar. Anyhow I'm afraid that new calendar share links will be generated while using this feature. Currently the calendar share links are generated in the following form:

For the owner:
https://example.com/remote.php/dav/calendars/user1/holidays/
For the users of a (LDAP-)group:
https://example.com/remote.php/dav/calendars/user2/holidays_shared_by_user1/
https://example.com/remote.php/dav/calendars/user3/holidays_shared_by_user1/

After executing the command I expect the following links:
For old owner:
https://example.com/remote.php/dav/calendars/user1/holidays_shared_by_user2/
For the new owner:
https://example.com/remote.php/dav/calendars/user2/holidays/
For all other users:
https://example.com/remote.php/dav/calendars/user3/holidays_shared_by_user2/

Because of the share link change all users of the group calendar needs to change their calendar settings in the CalDAV clients (Thunderbird, Outlook, Android). Only iOS/OS-X may update automatically...

**Describe the solution you'd like**
Maybe it would make sense to generate calendar links, which will not be changed as long as the calendar exist and it is shared to the user. e.g. by generating a random string or only remove the "_by_user2" string at the end of the link. The information about the owner of the calendar should not be hidden inside the url.

**Comment by skjnldsv** [comment]
cc @georgehrke @tcitworld

**Comment by georgehrke** [comment]
I don't think this is really needed. Even if the url changes, calendar clients with automatic calendar discovery will automatically pick up the new calendar and delete the old one.

It only ever affects you if you use calendar clients that don't support automatic calendar detection.
(Like vanilla Thunderbird Lightning, you shouldn't be facing that problem when using TB Sync)

**Comment by brunt82** [comment]
> It only ever affects you if you use calendar clients that don't support automatic calendar detection.
> (Like vanilla Thunderbird Lightning, you shouldn't be facing that problem when using TB Sync)

Unfortunately most of our users uses TB as default mail client. And as administrator you will try to reduce the amount of used software by users. So if you use TB sync (as additional addon in TB) there is an additional error source (NC + TB + Ligthning + TBSync), which must updated regularly.

Anyhow while using the CalDavSynchronizer the same problem exist. You are correct that the url will be detected automatically while creating the new calendar. But this url will be inserted into the calendar settings and not updated automatically. 

FYI: This week I had this "problem" again. I had to switch the calendar owner of two calendars, shared to a domain group. One user seems to copied the url from one calendar A to the calendar B and 10 minutes later I had to restore the calendar. :-( Had be avoided if the url would keep the same.

**Comment by georgehrke** [comment]
>  I had to switch the calendar owner of two calendars, shared to a domain group. 

Moving calendars is generally not recommended. You should only do it if absolutely necessary (e.g. because you want to keep the events, but delete the account.) There is a lot of undefined behavior especially related to invitations.
If you know that a calendar is going to be primarily used by a group and not an individual user, you should have a central account that creates and shares it.

**Comment by brunt82** [comment]
What is the problem to change the share-link from "shared_by_user" to a generated ransom string? What may be the reason that the owner has to be inserted into the share-link?
