### ISSUE TITLE
Update 14.0.4 > 14.0.6 failed

### ISSUE THREAD

**Issue by mfr00t** [nextcloud/server#13605]
Web-Updater Issue:

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Repair step: Repair MySQL collation

Repair info: Not a mysql database -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Repair step: Fix component of birthday calendars

Repair info: 2 birthday calendars updated.

Repair step: Fix broken values of calendar objects

[0 / 0]: Fix broken values of calendar objects

Repair step: Registering building of calendar search index as background job

Repair info: Repair step already executed

Repair step: Remove activity entries of private events

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'DELETE FROM "oc_activity" WHERE ("affecteduser" <> ?) AND ("object_type" = ?) AND ("object_id" = ?) AND ("subjectparams" LIKE ?)' with params ["user", "calendar", 4, "%{\"id\":\"xxx@google.com\"%"]: SQLSTATE[42703]: Undefined column: 7 ERROR: column "object_type" does not exist LINE 1: ...M "oc_activity" WHERE ("affecteduser" <> $1) AND ("object_ty... ^

Via CLI:
sudo -u www-data php /opt/nextcloud/occ upgrade

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Updating <dav> ...
Fix broken values of calendar objects

 Done
    0/0 [>---------------------------]   0%
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'DELETE FROM "oc_activity" WHERE ("affecteduser" <> ?) AND ("object_type" = ?) AND ("object_id" = ?) AND ("subjectparams" LIKE ?)' with params ["user", "calendar", 4, "%{\"id\":\"xxx@google.com\"%"]:

SQLSTATE[42703]: Undefined column: 7 ERROR:  column "object_type" does not exist
LINE 1: ...M "oc_activity" WHERE ("affecteduser" <> $1) AND ("object_ty...
                                                             ^
Update failed
Maintenance mode is kept active
Reset log level

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Argh, this happens when the activity app was disabled for a long time already.
Queries to fix can be found at: https://github.com/nextcloud/activity/issues/309#issuecomment-436929111

We can also only run the repairstep when activity is enabled. What do you think @MorrisJobke

**Comment by MorrisJobke** [comment]
I guess we need to cleanup old tables in the future if the app is disabled for a bit. Because otherwise it's completely uncontrollable, when the app was disabled and what happened in the meantime to the apps code.

**Comment by mfr00t** [comment]
> Argh, this happens when the activity app was disabled for a long time already.
> Queries to fix can be found at: [nextcloud/activity#309 (comment)](https://github.com/nextcloud/activity/issues/309#issuecomment-436929111)
> 
> We can also only run the repairstep when activity is enabled. What do you think @MorrisJobke

Thanks alot, fixing this table helps!
Update to 15.0.2 worked aswell.
