### ISSUE TITLE
Your Nextcloud account  has been disabled

### ISSUE THREAD

**Issue by noemiguzo** [nextcloud/server#13606]
Hi
I create an account on https://nextcloud.com/signup/
I didn't confirm the email, and I received the email (on ~6 hours)

Your Nextcloud account noemi@gmail.com has been disabled because it was not verified in time. | Your Nextcloud account noemi@gmail.com has been disabled because it was not verified in time. |  
-- | -- | --
on signup page I get 'Error: User is already existing'
could you please help me?  I do not want to lose my account, I can login to 'User disabled'
Thanks

**Comment by MorrisJobke** [comment]
Please contact the provider with whom you have created the account. It's most likely written in the confirm email.

**Comment by noemiguzo** [comment]
I used the URL https://nextcloud.com/signup/
Free account
