### ISSUE TITLE
TrashbinTest::testExpireOldFiles fails on CI

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13601]
```
1) TrashbinTest::testExpireOldFiles
Failed asserting that null is identical to 'file2.txt'.

/drone/src/github.com/nextcloud/server/apps/files_trashbin/tests/TrashbinTest.php:186
```

From https://drone.nextcloud.com/nextcloud/server/14721/157 and many other PRs.

**Comment by danielkesselberg** [comment]
Test works for me with `PHP 7.3.0RC6`. Maybe its enough to update the docker image @rullzer?

**Comment by szaimen** [comment]
I think this is fixed in the meantime. Please reopen if this is not the case.
