### ISSUE TITLE
Move from JSCombiner to webpack

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#13608]
Now that we have webpack in the main server already (for the 3rdparty deps etc) it might make sense to move the files we now use to combine with the JSCombiner to packed files by webpack.

For example: https://github.com/nextcloud/server/blob/master/core/js/merged-share-backend.json

This has a few advantages in my book:
* Files can be served directly by the webserver. Especially in clustered environments this saves going to 'slow' disk
* We can have map files for easier debugging.
* Proper minification

Of course the bad thing is that we need to run webpack when one of the files is changed. But I think that is a fair price to pay.

CC: @nextcloud/javascript @MorrisJobke @skjnldsv @ChristophWurst

**Comment by skjnldsv** [comment]
Awesome idea!

**Comment by rullzer** [comment]
Lot is done in this regard. Lets close for now,.
