### ISSUE TITLE
something wrong with the files page display elements

### ISSUE THREAD

**Issue by easyjack** [nextcloud/server#13610]
### Environment
1. Ubuntu 16.04.4
2. Chrome 71.0.3578.98
3. PHP version 7.0.32-0ubuntu0.16.04.1
4. personal locale setting English (Canada)  or English (Australia)

### Actual behaviour
maybe something wrong with the file /core/js/l10n.js  
var _build

![image](https://user-images.githubusercontent.com/24935499/51191209-e3054f00-191e-11e9-90d5-2354e15fa351.png)

![image](https://user-images.githubusercontent.com/24935499/51189160-6c665280-191a-11e9-9a8c-0c86df155ff6.png)

![image](https://user-images.githubusercontent.com/24935499/51191258-f7e1e280-191e-11e9-893c-35879d820203.png)

![image](https://user-images.githubusercontent.com/24935499/51189318-c0713700-191a-11e9-9ec2-a2e7a6ab5c69.png)

![image](https://user-images.githubusercontent.com/24935499/51189396-f3b3c600-191a-11e9-919a-0e91fc63ac6d.png)

![image](https://user-images.githubusercontent.com/24935499/51191964-755a2280-1920-11e9-98f9-3b350727a15a.png)

### Others
when i change the locale setting to others value (such as Chinese) or i comment this line of code, this error will disappear

![image](https://user-images.githubusercontent.com/24935499/51191148-c832da80-191e-11e9-88bb-a4cf38654f4a.png)

### web browser console message

> Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
>     at _build (merged-template-prepend.js?v=dde9fa14-10:3872)
>     at Object.translate (merged-template-prepend.js?v=dde9fa14-10:3895)
>     at Object.translatePlural (merged-template-prepend.js?v=dde9fa14-10:3920)
>     at FileSummary.update (merged-index.js?v=dde9fa14-10:4071)
>     at FileSummary.setSummary (merged-index.js?v=dde9fa14-10:4037)
>     at FileSummary.calculate (merged-index.js?v=dde9fa14-10:4020)
>     at FileList.setFiles (merged-index.js?v=dde9fa14-10:5818)
>     at FileList.reloadCallback (merged-index.js?v=dde9fa14-10:6521)
>     at Object.<anonymous> (core.js?v=dde9fa14-10:2)
>     at j (core.js?v=dde9fa14-10:2)

**Comment by dawidp** [comment]
I have the same problem with "Actions" menu being displayed under first row of directories. This happens when Locale differs from Language settings.

    Locale: Polish
    Language: English (British English)
    Display of Actions Menu: messed

![messed](https://user-images.githubusercontent.com/1435423/51376880-b2353d80-1b09-11e9-9938-6d78a3711cc7.png)

    Locale: Polish
    Language: Polish
    Display of Actions Menu: correct

![correct](https://user-images.githubusercontent.com/1435423/51376896-bb260f00-1b09-11e9-89a3-08dd207ce5ec.png)


Also I have error :

    unreachable code after return statement in merged.js:1566:4

this refers to function `inFileList`

    function inFileList($row, result) {
        return false;
    
    	if (! self.fileAppLoaded()) {
    		return false;
    	}
    	var dir = self.fileList.getCurrentDirectory().replace(/\/+$/,'');
    	var resultDir = OC.dirname(result.path);
    	return dir === resultDir && self.fileList.inList(result.name);
    }

**Comment by zxtwonder** [comment]
Seems fixed in 15.0.7

**Comment by zxtwonder** [comment]
Not in 15.0.5 though

**Comment by skjnldsv** [comment]
Fixed in the late releases versions already :)
