### ISSUE TITLE
Update fails Nextcloud 14.04 to 14.06

### ISSUE THREAD

**Issue by h-gen53** [nextcloud/server#13614]
-->

### Steps to reproduce

only @ my installation (:(

### Expected behaviour

I tried to update my Nextcloud installation.

### Actual behaviour
The installation was aborted with the following error:
------------
Prepare update
Log level set to "debug"
Maintenance mode switched on
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts when migrating from ownCloud
Repair step: Drop account terms when migrating from ownCloud
The database schema is updated
Doctrine \ DBAL \ Schema \ SchemaException: The column 'uid_lower' on table 'oc_users' already exists.
The update failed. Please report this issue to the Nextcloud Community.
----------
Further information is not displayed.
Furthermore, I deleted the database and restored the backup of the DB. Unfortunately, the same error came afterwards. So this has nothing to do with the mistake.

### Server configuration

**Operating system**:Ubuntu(actual Distribution)

**Web server:**apache2

**Database:**mysql 

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page)
14.04
**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Not possible to Login in my Nextcloud
</details>

**List of activated apps:**

- accessibility: 1.0.1
  - activity: 2.7.0
  - apporder: 0.6.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - orcid: 1.0.0
  - password_policy: 1.4.0
  - polls: 0.9.5
  - provisioning_api: 1.4.0
  - quota_warning: 1.3.0
  - registration: 0.4.5
  - serverinfo: 1.4.0
  - survey_client: 1.2.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_versions
  - files_videoplayer
  - sharebymail
  - support
  - systemtags
  - user_external
  - user_ldap

**Nextcloud configuration:**

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
</summary>

?php
$CONFIG = array (
  'instanceid' => 'oc2rdg8k3sbv',
  'passwordsalt' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'secret' => 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',
  'trusted_domains' =>
  array (
    0 => 'xxxxxxx.ddnss.de',
  ),
  'datadirectory' => '/media',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'https://xxxxxxx.ddnss.de',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:5432',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxxxxxxxx',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.0,
    'password' => '',
    'dbindex' => 0,
),
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_from_address' => 'xxxxxxxxxxxxxxx',
  'mail_domain' => 'web.de',
  'mail_smtphost' => 'smtp.web.de',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'xxxxxxx',
  'mail_smtppassword' => 'xxxxxxxxxxxx',
  'maintenance' => false,
  'updater.release.channel' => 'stable',
  'onlyoffice' =>
array (
    'verify_peer_off' => true,
  ),
  'updater.secret' => '$2y$10$Vx/vC19qTwU90kdFxY8EKeo7J4NA36IziLuhtZrnCI.cOlTkjYG2.',
  'theme' => '',
  'loglevel' => 2,
  'data-fingerprint' => '5fae2cf16eba8781185830049fe2e65b',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

smb

**Are you using encryption:** yes/no:  NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

Webdav

### Client configuration
**Browser:**

**Operating system:**

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

Nextcloud log File under /var/www/html/nextcloud/data  is empty!

#### Browser log
<details>
<summary>Browser log</summary>

I hope someone can help me or at least give a good tip on how to fix this problem.

Many Thanks

**Comment by h-gen53** [comment]
By deleting the individual coloums in the mysql database on command line, I was able to delete the erroneous entries and indexes. Thus, the update could be executed.

Greets

h-ge53

**Comment by garbast** [comment]
Still happening in 17.0.10

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Doctrine\DBAL\Schema\SchemaException: The column 'uid_lower' on table 'oc_users' already exists.
