### ISSUE TITLE
CSS variable polyfill doesn't work with vue-style-loader

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#13615]
When migrating the firstrunwizard to vue, I recognized that any stylesheets included into the bundle with vue-style-loader will not be handled by the css variables polyfill. This is actually just an issue with IE11, where the polyfill is used.

I tried adding the watch option https://github.com/jhildenbiddle/css-vars-ponyfill#optionswatch but it doesn't seem to work. 

For now I just ship the css as a separate file, since if loaded via <link> it is actually polyfilled, but ideally it should also work with inlined styles from vue-style-loader, so ideas how we could solve that would be nice. @nextcloud/vue

**Comment by ChristophWurst** [comment]
My bad. I tested it but didn't notice something was broken.

Is it possible that the ponyfill is loaded too late?

**Comment by skjnldsv** [comment]
@juliushaertl strange, I remember having this talk with @rullzer on one of his _independent css file => vue scoped style pr_, and it was working :thinking: 

Is it because of the new npm management of the deps?
Can you try just before the merge see if it was working?

**Comment by skjnldsv** [comment]
@rullzer if we want to make ie unusable, better completely drop it then :p

**Comment by juliushaertl** [comment]
Never mind. My branch was having an outdated package-lock.json, therefore a different version of the polyfill was installed then mentioned in package.json, so watch wasn't available. All fine now.

**Comment by skjnldsv** [comment]
@ChristophWurst see, lockfiles are evil! :O

**Comment by ChristophWurst** [comment]
:innocent:
