### ISSUE TITLE
Accepting a remote share: Failed to perform action

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#13612]
### Steps to reproduce
1. Receive a remote share notification
2. Click on the bell sign on the upper right in the browser
3. Click on "Accept"

### Expected behaviour
The file should land in my home directory, and the notification should go away

### Actual behaviour
"Failed to perform action" appeares on the upper center, the notification window keeps where it stays, and more clicks on "Accept" provoke more "Failed to perform action" messages.

Here is a screenshot of the notification:

![notif](https://user-images.githubusercontent.com/476060/51195371-365ea980-18ed-11e9-8a4a-48b07943b0bc.png)

Note the `https://` right in the middle of the federated cloud-ID? Why is this there? Is this some misconfiguration on the remote side?

When clicking "Accept", the Firefox devtools console returns the following (each time of a click):

    Content Security Policy: The page’s settings blocked the loading of a resource at http://cloud.xxxxx.de/ocs/v2.php/apps/files_sharing/api/v1/remote_shares/pending/16 (“connect-src”).

Note the `http` in the URL? Why is this there? Of course, my instance is running on an A+ rated Letsencrypt certificate.

There are no extra notes appearing in `nextcloud.log`.

May any of those findings lead to the error? What else information is relevant for this?

The sending instance is running '14.0.4.2' on Debian, the receiving runs in Docker using the default `nextcloud:latest` image, currently '15.0.2.0'.

**Comment by mcnesium** [comment]
this also happens with the sending instance updated to latest v15.0.2

**Comment by eMPee584** [comment]
We have the exact same problem on our server, also with an nc 15.0.2 docker container behind an apache reverse proxy.
We just set overwriteprotocol which fixed the image icons, but a remotely shared file still gives an error. Why is an http URL being accessed? should it not rather respect that overwriteprotocol variable?

**Comment by otisdog8** [comment]
I am also having this issue with the nextcloud version of snap. Server is hosted on my pc with cloudflare for only DNS. Letsencrypt cerfificate and A+ rating on security. Switching to http makes it work.

**Comment by Kombustor** [comment]
The notification button url is generated here:
https://github.com/nextcloud/server/blob/master/apps/federatedfilesharing/lib/ocm/CloudFederationProviderFiles.php#L351

`getBaseUrl` (called in `getAbsoluteUrl`) returns the current request's server protocol:
https://github.com/nextcloud/server/blob/master/lib/private/URLGenerator.php#L266

My guess is that this doesn't work in our setup (using nginx as a reverse proxy with letsencrypt).
@schiessle

**Comment by danielkesselberg** [comment]
@Kombustor https://github.com/nextcloud/server/issues/13700#issuecomment-456863838 could that work for you?

**Comment by eMPee584** [comment]
@danielkesselberg I wasn't being asked but overwriteprotocol=https in config did not help on our site..

**Comment by danielkesselberg** [comment]
What about `overwritehost`? You could try to share files with a demo instance https://demo.nextcloud.com and see if that works.

**Comment by Kombustor** [comment]
@danielkesselberg Using `overwritehost => 'cloud.mydomain.tld'` did fix the CSP error. No error is printed out now, but the share is simply not appearing in my nextcloud.

When sharing a folder with a demo.nextcloud.com instance, the sharing worked perfectly and the folder appears in the demo instance.

Any way to debug this?

**Comment by eMPee584** [comment]
> What about `overwritehost`? You could try to share files with a demo instance https://demo.nextcloud.com and see if that works.

Oh we had that set, but not the `trusted_proxies` variable.. That one actually fixed it! It's documented here right in the **nextcloud reverse proxy** guide:
https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by mcnesium** [comment]
Since I had set `'overwriteprotocol' => 'https'` for #13700, I can approve that bypasses this issue as well. I intentionally did not write "fixes", since I consider this a workaround rather than an actual fix.

**Comment by danielkesselberg** [comment]
Most reverse proxies (like nginx or caddy) forward `HTTP_X_FORWARDED_PROTO` and `HTTP_X_FORWARDED_HOST`. If these are forwarded `trusted_proxies` should be enough and you can remove `overwritehost` and `overwriteprotocol` again. Could you validate this? @Kombustor @eMPee584 @mcnesium 

> I intentionally did not write "fixes", since I consider this a workaround rather than an actual fix.

What kind of "fix" do you expect? A valid configuration for `trusted_proxies` is required. The check is (since 15.0.2) more strict then before (HOST and/or PROTO from untrusted proxies are ignored).

**Comment by mcnesium** [comment]
Well, if both remote and local Nextcloud instances are served via `https://`, I assume it to use TLS per default without exception and I consider `'overwriteprotocol' => 'https'` as redundant.

Now, in my case, the receiving instance is served in a Docker container. Requests to the domain are first handled by Apache on the host system and then passed to the container using this virtual host directive:

    ProxyPreserveHost On
    ProxyPass           /  http://localhost:44304/
    ProxyPassReverse    /  http://localhost:44304/

If this unencrypted traffic between host and container is causing Nextcloud to use `http://` anywhere, this should at least be documented more clearly, or better: fixed.

I did set `'trusted_proxies' => ['172.17.0.1']` (the IP address is the `Gateway` that I found out by doing `docker network inspect bridge` – [Credits](https://kopfkrieg.org/2017/06/15/nextcloud-docker-nginx/) – this could also be emphasized in the docs).

This does not make the overwriting obsolete though in my case. When removing `'overwriteprotocol' => 'https'` from the config, the reported error re-appears.

**Comment by danielkesselberg** [comment]
> This does not make the overwriting obsolete though in my case. When removing `'overwriteprotocol' => 'https'` from the config, the reported error re-appears.

Thanks for your feedback :+1: https://httpd.apache.org/docs/2.4/mod/mod_proxy.html#x-headers (looks like apache2 does not forward `HTTP_X_FORWARDED_PROTO`)

**Comment by Hoeze** [comment]
I got this problem as well.
My nextcloud instance runs in a Apache subdirectory and is proxied by nginx.
I also set up my config.php as shown [in the admin manual.](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html)

**Comment by vc7ee** [comment]
Same issue with Docker 16.0.1 behind Traefik

**Comment by Kombustor** [comment]
I'm having no issues with nextlouc 16.0.1 behind traefik with the following configuration:

For docker-compose:
```
    labels:
      - traefik.backend=<name here>
      - traefik.enable=true
      - traefik.docker.network=<network here>
      - traefik.port=80
      - traefik.frontend.rule=Host:cloud.yourhost.tld
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.customResponseHeaders=Strict-Transport-Security:15552000
      - traefik.frontend.redirect.permanent=true
      - traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/
```

config.php
```
  'trusted_domains' =>     
  array (                  
    0 => 'cloud.yourhost.tld',
  ),                       
  'trusted_proxies' =>     
  array (                  
    0 => '<the ip cloud.yourhost.tld is resolving to>',  
  ),                       
  'overwrite.cli.url' => 'https://cloud.yourhost.tld',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'cloud.yourhost.tld',
```

**Comment by vc7ee** [comment]
@Kombustor Same config, current issues:
 - U2F not working at all
 - Can't interact with notifications (fails)

**Comment by kesselb** [comment]
@vc7ee anything in the logs? 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by vc7ee** [comment]
@kesselb I'd note, that I also can't change stuff in Unsplash's app settings.
Opening the settings page: https://pb.c7.ee/fodeqatiho.sql
On refresh, after triggering a manual notification: https://pb.c7.ee/ovihivujeb.sql
Entering aa, pressing Accept (on 2fa notification), entering aa again, pressing cancel, entering aa, pressing the x button: https://pb.c7.ee/wecuyabacu.coffeescript
Probably something wrong with Traefik config?

**Comment by kesselb** [comment]
Looks like some javascript is not loaded. Does the same happen with https://demo.nextcloud.com/?

**Comment by vc7ee** [comment]
I made an another instance on an another domain, seems like there may be an issue with apps.

**Comment by vc7ee** [comment]
I managed to fix it, it was unreliable information from multiple sources. :/
For anyone in the future: domain.tld is your instance domain, machine ip 99.99.99.99. Any passwords and like have been changed.
config.php (mostly autogenerated)
```
<?php
$CONFIG = array (
        'trusted_domains' =>
        array (
                0 => 'domain.tld',
        ),
        'trusted_proxies' => 
  array (
    0 => '99.99.99.99',
  ),
  'overwrite.cli.url' => 'https://domain.tld',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'domain.tld',
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'oc7qz6s05m1n',
  'passwordsalt' => 'Jdq4uuaRsgKTcsPKN36Ckpn6EuFlAl3Qb149Qw2UGKIujxu3BgT44FwlyEx7',
  'secret' => 'e1L1hjRdJklYIKZ89aQdQZxU9vLut52sygtU4wgaqfrXlmwGgj8yPvyv5Hxf',
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '16.0.1.1',
  'overwrite.cli.url' => 'http://domain.tld',
  'dbname' => 'nextcloud',
  'dbhost' => 'db',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '4LamFn1AavVbQy7fGQqdBcfkaaiVdkYW',
  'installed' => true,
  'updater.release.channel' => 'production',
  'mail_from_address' => 'robot',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'domain.tld',
  'has_rebuilt_cache' => true,
  'maintenance' => false,
);
```
docker-compose.yml
```
version: '3'
networks:
  web:
    external: true
  internal:
    external: false

volumes:
  nxcloud:
  nxdb:

services:
  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - nxdb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=4LamFn1AavVbQy7fGQqdBcfkaaiVdkYW
      - MYSQL_PASSWORD=4LamFn1AavVbQy7fGQqdBcfkaaiVdkYW
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal
    labels:
      - traefik.enable=false
  app:
    image: nextcloud
    links:
      - db
    volumes:
      - nxrascloud:/var/www/html
      - /hdds/.dockerstorage/bgnxrs:/var/www/html/hdd
    restart: always
    labels:
      - traefik.backend=mybackendname
      - traefik.frontend.rule=Host:domain.tld
      - traefik.docker.network=web
      - traefik.port=80
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.headers.STSSeconds=315360000
      - traefik.frontend.redirect.permanent=true
      - traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav
      - traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/
    networks:
      - internal
      - web
```

**Comment by kesselb** [comment]
@vc7ee Thanks :+1: You posted some sensitive information. Please change the credentials just in case :lock:

**Comment by vc7ee** [comment]
@kesselb as I mentioned in my comment, I (think it was 60 chars) generated random stuff to replace the sensitive content in the comment. If I would've not had the email from github with your first comment, a stranger might peek in to the edit history and in case of an actual leak use the credentials.
Next time you spot this, try contacting the person directly or leaving a comment of the incident (since the edit history prevails).

**Comment by Kombustor** [comment]
@vc7ee `'overwrite.cli.url'` is twice in your config.php (https/http). Can you confirm which is the relevant one please?

**Comment by kesselb** [comment]
>  a stranger might peek in to the edit history and in case of an actual leak use the credentials.

Was about to delete the history :sunglasses:

**Comment by vc7ee** [comment]
@Kombustor Sorry didn't notice, removed the duplicate.

**Comment by PhilsLab** [comment]
I think this should be handled correctly by nextcloud itself when running as docker container, as using a reverse proxy is common practice. can this issue be fixed, so the relevant parameters can be fixed accordingly without having to manually modify the config.php ?

**Comment by herohamp** [comment]
i am having the same issue. VM497:1 Refused to connect to 'http://cloud.domain/ocs/v2.php/apps/files_sharing/api/v1/remote_shares/pending/2' because it violates the following Content Security Policy directive: "connect-src 'self'".
how can i make it use https
```
'overwrite.cli.url' => 'https://cloud.domain:443',
  'overwriteprotocol' => 'https',
  'overwritehost' => 'cloud.domain',
  'htaccess.RewriteBase' => '/',
```
