### ISSUE TITLE
Hide download hides the note to recipient on link shares

### ISSUE THREAD

**Issue by strelitzer** [nextcloud/server#13617]
### Steps to reproduce
1. Share via link
2. Create a "Note to recipient"
3. Select "Hide download"
4. View link share

### Expected behaviour
I want to see the bubble on the top right side of a link share.
Without a download option/button a note to the recipient of a shared document or picture makes sense to me.

### Actual behaviour
No bubble of "Note to recipient" available.
The complete right menu will be removed, not only the 3 dots menu and the download button.

### Server configuration
**Nextcloud version:** ~15.0.2~ 18.0.3

**Comment by violoncelloCH** [comment]
reproduced on current master

**Comment by MorrisJobke** [comment]
cc @skjnldsv @nextcloud/designers

**Comment by jancborchardt** [comment]
Need to postpone this to Nextcloud 17, maybe even later. Any help is welcome! :)
