### ISSUE TITLE
Enable share calendar in iCal on macOS Mojave

### ISSUE THREAD

**Issue by Inseeker** [nextcloud/server#13620]
### Steps to reproduce
1. set nextCloud account with iCal on macOS Mojave 
2. create a calendar, and share it (read/write) with user B
3. iCal alter an error message

### The iCal error message
The server responded with an error.
The request for account “xxxx” failed.
The server responded with
“501”
to operation CalDAVUpdateShareesQueuableOperation.

### The  log
"message": "Exception: {'Message':'HTTP/1.1 501 There was no plugin in the system that was willing to handle this POST method.",

### Server configuration
**Operating system**:
macOS Mojave version10.14.2
**Calendar Client:**
macOs Calendar Version 11.0 

### Additional Information
When i use the Calendar app of  market ;
I can share calendar normally

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/5050
