### ISSUE TITLE
user_saml breaks on nextcloud 15.0.2

### ISSUE THREAD

**Issue by ChessSpider** [nextcloud/server#13624]
### Steps to reproduce
1. Install nextcloud v15.0.0 with user_saml
2. Verify it works
3. Install nextcloud 15.0.2 

### Expected behaviour
user_saml still works

### Actual behaviour
user_saml breaks

Please see https://github.com/nextcloud/user_saml/issues/296 for more info about the issue

**Comment by MorrisJobke** [comment]
cc @rullzer @schiessle

**Comment by phish108** [comment]
Unlikely to help in this case, but #13591 has been fixed through improved reverse proxy configuration.

**Comment by danielkesselberg** [comment]
Can we close this as well @ChessSpider?

**Comment by ChessSpider** [comment]
yes of course, sorry, i forgot :)
