### ISSUE TITLE
Calender / Share via Ifame / Cookie

### ISSUE THREAD

**Issue by criwe** [nextcloud/server#13627]
### Steps to reproduce
1.  Use iframe to show calender on an other domain (local html file in my case)
2. Firefox: Set your Cookiesetting to "Disallow all from third party..." (see image)

![nextcloud_iframe](https://user-images.githubusercontent.com/7531138/51265788-d5e96e00-19b9-11e9-8803-d272b1d08117.jpg)

Everything works fine!

3. Firefox: change the Cookiesettings to something else and it doesnt work anymore, see image
![nextcloud_iframe_02](https://user-images.githubusercontent.com/7531138/51265936-34165100-19ba-11e9-917b-8a1d86eb04c0.jpg)

A friend send me this (console):

![errors](https://user-images.githubusercontent.com/7531138/51266137-b0a92f80-19ba-11e9-83c5-d8ec112d35c0.jpg)

(I don´t get these errors in the console yet)

### Expected behaviour
Calender should load....

### Actual behaviour
Calender doesnt show up

### Server configuration

**Operating system**:

**Web server:** ? Shared Hosting

**Database:** MySQL

**PHP version:** 7.0

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14.0.6 (completely didn´t work with that version)

**Where did you install Nextcloud from:**  Via Nextcloud Backend (AppStore)

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 64.0.2

**Operating system:** Win7 / Win10

**Comment by violoncelloCH** [comment]
That's a security feature, that Nextcloud doesn't allow itself to be displayed as an iframe (X-Frame-Options). Allowing this would open a possibility for a man-in-the-middle attack.

**Comment by criwe** [comment]
@violoncelloCH: there's an function to include the calendar via iframe, so it's not a security feature. And if it would be, it could be circumvented as described (with certain browsesettings you could use an iframe version of the calender).

**Comment by criwe** [comment]
Hi @violoncelloCH I think it a generell cookie thing... so maybe it better here. May the admin move it if necessary :-)

**Comment by tcitworld** [comment]
Fixed in https://github.com/nextcloud/calendar/pull/2087
