### ISSUE TITLE
Wrong position of "Action" button

### ISSUE THREAD

**Issue by RainCat1998** [nextcloud/server#13622]
Today I upgrade my nextcloud to **15.02.**  And there‘s something wrong with "Action" button.
At first, I think  it is the **cache** that cause the problem. But after I reinstalled my nextcloud, it occurred again. 

Then I launch a **trail instance** on the **official site**, it has the same problem.

It happens when your language setting is **Chinese.**
![snipaste_2019-01-16_21-01-49](https://user-images.githubusercontent.com/36730607/51251422-44d3c080-19d4-11e9-907d-318da6d152e1.png)

English:
![snipaste_2019-01-16_21-03-20](https://user-images.githubusercontent.com/36730607/51251503-7482c880-19d4-11e9-85bc-e2283adede15.png)

**Comment by skjnldsv** [comment]
Fixed in the late releases versions already
