### ISSUE TITLE
Make national holidays available in calendar (just like birthdays)

### ISSUE THREAD

**Issue by matlag** [nextcloud/server#1363]
Hello!

This is a feature request.
### Steps to reproduce

1.Open a calendar front-end
2.Try to add national holidays from the country you're in, or another
### Expected behaviour

Currently, birthdays can be added with just one tick box in Owncloud calendar.
It would be nice if we could display the local national holidays calendar and/or from any other place.

Many thanks!

**Comment by nickvergessen** [comment]
Well I guess that is one of the things, that got dropped by the rewrite.
Anyhow I think this should either be part of the calendar app, or an app in itself.

**Comment by maclag** [comment]
I initially proposed the feature to the calendar app devs, their answer was to ask core/server teams.
See: https://github.com/owncloud/calendar/issues/728
(BTW: I'm still not clear whether NC will have its own calendar app fork or if both projects will use the same app for now. So sorry if I'm not asking the right persons)

**Comment by nickvergessen** [comment]
In the current version it is possible to add webcals manually, using the `+ Subscription` button.
That allows you to add webcals for public holidays, e.g. germany: `webcal://www.webcal.fi/cal.php?id=75&format=ics&wrn=1&wp=4&wf=53&color=%2300AA00&cntr=de&lang=de&rid=wc`

**Comment by georgehrke** [comment]
Calendar implemented a subscription feature
