### ISSUE TITLE
2FA settings icons don’t invert in dark theme

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#13643]
With the dark theme, 2FA settings look like this:
![dark theme 2fa icons](https://user-images.githubusercontent.com/925062/51314791-f1ec1e80-1a50-11e9-97fb-5289b5e08400.png)

That’s because they are loaded in the `<img>` tag. Ideally it should be changed to use a class on the header like `icon-…` so it’s used as background-image.

Documentation on that at: https://docs.nextcloud.com/server/latest/developer_manual/design/css.html#scss-icons-mixins

**Comment by nickvergessen** [comment]
Code in question
https://github.com/nextcloud/server/blob/1f47c6976a203c97f0b60a438da7db98bef0096c/settings/templates/settings/personal/security.php#L76-L82
