### ISSUE TITLE
Preview image in file sidebar does not fill to edges

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#13645]
This is stable15, preview fits nicely inside the sidebar and touches the top and right side:
![files sidebar preview stable15](https://user-images.githubusercontent.com/925062/51315869-7cce1880-1a53-11e9-90aa-72982bbec3b4.png)

And this current master, with the preview being away from top and right side:
![files sidebar preview issue master](https://user-images.githubusercontent.com/925062/51315868-7cce1880-1a53-11e9-83b6-7f01c79c3e97.png)

cc @nextcloud/designers

**Comment by alion300** [comment]
![image](https://user-images.githubusercontent.com/24224502/51477992-c770cd00-1d92-11e9-93a5-dc08966718f8.png)

i see the image is ok, i attached print screen. which browser you used for get this bug
thanks

**Comment by jancborchardt** [comment]
@alion300 happens for me in both Chrome (left) and Firefox (right):
![image margins](https://user-images.githubusercontent.com/925062/51485855-64396780-1d9f-11e9-9fd7-1a9d93d1ea3f.png)


@GoetheG you put a :+1: on my issue – does that mean you can reproduce the issue? :)

**Comment by skjnldsv** [comment]
Cannot reproduce on chrome :)
![capture d ecran_2019-01-29_08-50-11](https://user-images.githubusercontent.com/14975046/51892658-ea0e7180-23a2-11e9-9920-bb5f2d437769.png)

**Comment by jancborchardt** [comment]
Heh, can’t reproduce anymore either. :) Good stuff
