### ISSUE TITLE
Alias feature

### ISSUE THREAD

**Issue by YVES-BENOIT** [nextcloud/server#13659]
Hello,
We are a group of Social economy engineers, alumni of École CentraleSupélec. We are paying-customers of Mère Zaclys, for Nextcloud. I write in their name. I don't know where I should post a request for this new feature: The files are stored in a tree, and sometimes a file (or folder) deserves to be accessible in two different folders. So I need the following :

I have a file Xyz in folder A.
In Folder B, I need a special text File Xyz.specific_extension, in which I write the URL of file Xyz in Folder A, in Nextcloud as I can copy it from my browser.
What I wish is:
when I click on the icon of this Special file in folder B  , it opens directly the url that is written in this file. 
The result will be opening file Xyz in folder A of Nextcloud.
Note 1 :  We want the simplest solution: the naming of Special File and filling of URL could be done manually by me. This is intended to work in cloud. No synchro with desktop is expected.. 
Note 2 : If you create such a file type, it might also open any URL link written in the file, which might be quite useful.
Thank you
Yves

**Comment by MorrisJobke** [comment]
> We are a group of Social economy engineers, alumni of École CentraleSupélec. We are paying-customers of Mère Zaclys, for Nextcloud.

As I don't want to expose customer data: if they have a subscription with Nextcloud GmbH then they also received a way to contact our support team.

Regarding your request: we had a similar request in the past - it was basically using the `.url` file extensions in the proposal and then opened the content. I don't know if this was implemented or just proposed and unfortunately I also can't find it anymore.

This should be implemented as a Nextcloud app and not in the server itself. It then hooks into the actions of the specific url mime type and reads the file content. So this should be doable, but we will not implement in inside the server repo here. Thus I'm closing this.

Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
