### ISSUE TITLE
can’t find the user I have shared a folder and the settings (bearbeiten, löschen etc.)

### ISSUE THREAD

**Issue by fabjoe91** [nextcloud/server#13658]
I can’t find the user I have shared a folder with and the options I have set previously. The Icon has the link sharing symbol on it but the settings (bearbeiten, etc.) don’t show up.

![image](https://user-images.githubusercontent.com/46786119/51348860-073e6880-1aa4-11e9-83ea-03afd1675821.png)

I got this Error
![image](https://user-images.githubusercontent.com/46786119/51348839-f7268900-1aa3-11e9-8448-3fdf9f1c6d4d.png)

It work until a few hours after the installation today

Version: 15.0.2.0
PHP Version: 7.2.14 with apache2 self install
mysql Version: 10.1.37

**Comment by fabjoe91** [comment]
ok, if i deactivate the social sharing via email, it works like a charme.

**Comment by saibotk** [comment]
It is already reported here just for reference:
https://github.com/nextcloud/socialsharing/issues/29

**Comment by fabjoe91** [comment]
Thank you, did not find it yesterday, maybe too tired.
