### ISSUE TITLE
Insufficient Storage when updating File in shared Folder

### ISSUE THREAD

**Issue by lephisto** [nextcloud/server#1365]
### Steps to reproduce
1. Share a Folder in NC
2. Upload a File in NC
3. Let anouther User the File was shared update that file

### Expected behaviour
File should be updated

### Actual behaviour
File won't update via Client / DAV. See Error below. Using the Webinterface to Update works.

### Server configuration
**Operating system**: Ubuntu Xenial

**Web server:** Apache

**Database:** Mysql

**PHP version:** 5.5.9

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Manually updated from Nextcloud 9x

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-10.0.0.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: true
  - comments: 1.0.0
  - contacts: true
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_external
  - firstrunwizard
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '-',
  'passwordsalt' => '-',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
  ),
  'datadirectory' => '/var/www/nc.XXX.de/data',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'oc_XXX_de',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_XXX_de',
  'dbpassword' => '',
  'installed' => true,
  'defaultapp' => 'activity',
  'theme' => '',
  'maintenance' => false,
  'forcessl' => true,
  'secret' => '',
  'mail_from_address' => 'oc',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'XXX.de',
  'filelocking.enabled' => 'true',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    0 => '/tmp/redis.sock',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),

  'user_backends' => array(
    array(
      'class' => 'OC_User_IMAP',
      'arguments' => array(0 => '{mail5.XXX.de:993/imap/ssl}INBOX'),
    ),
  ),

  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updater.release.channel' => 'stable',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
IMAP

### Client configuration
**Browser:**
Palemoon

**Operating system:**
Ubuntu 16.04 LTS 64bit

#### Web server error log
<details>
<summary>Web server error log</summary>
```
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Exception: {"Message":"HTTP\/1.1 507 Insufficient Storage","Exception":"Sabre\\DAV\\Exception\\InsufficientStorage","Code":0,"Trace":"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('xxxFolder\/...', Object(OCA\\DAV\\Connector\\Sabre\\File), Resource id #97, false)\n#1 \/var\/www\/nc.xxx.de\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/var\/www\/nc.xxx.de\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1068): Sabre\\Event\\EventEmitter->emit('beforeWriteCont...', Array)\n#3 \/var\/www\/nc.xxx.de\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(511): Sabre\\DAV\\Server->updateFile('xxxFolder\/...', Resource id #97, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/nc.xxx.de\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/nc.xxx.de\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \/var\/www\/nc.xxx.de\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/nc.xxx.de\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/nc.xxx.de\/remote.php(165): require_once('\/var\/www\/nc.xxx...')\n#10 {main}","File":"\/var\/www\/nc.xxx.de\/apps\/dav\/lib\/Connector\/Sabre\/QuotaPlugin.php","Line":109,"User":"XXX"} 
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by lephisto** [comment]
This is a real showstopper. Reproduced it with a fresh install.

**Comment by lephisto** [comment]
I double checked it: In a clean NC 10 Installation it's not a problem. My Productive Version comes from a owncloud 7x->8x->nc9x->nc10...

**Comment by lephisto** [comment]
Some further research:

https://github.com/owncloud/core/commit/6f4ba321613ddf406fa0fcbb1228e89ca35e8425.patch

This patch fixes the issue in Nextcloud 10. Any clarification when this will go to mainline NC?

**Comment by LukasReschke** [comment]
Linked commit is already in and will be in 10.0.1, see https://github.com/nextcloud/server/pull/1179.

Can you retry with a new daily? THX. 

=> https://download.nextcloud.com/server/daily/latest-stable10.tar.bz2

**Comment by lephisto** [comment]
@LukasReschke it's a productive system, didn't want to get it in the nightlies... a fast release to a stable version would come very hand, since that issue is a real showstopper.

**Comment by LukasReschke** [comment]
> @LukasReschke it's a productive system, didn't want to get it in the nightlies... a fast release to a stable version would come very hand, since that issue is a real showstopper.

Closing then for now, please reopen if 10.0.1 doesn't fix the problem. 10.0.1 will be released soonish.
