### ISSUE TITLE
Numeric files sorting order is wrong

### ISSUE THREAD

**Issue by rahra** [nextcloud/server#13661]
I have a local directory where I store my images. The directories are named <year_month_...> consequently to get a consistent sort order by date.
Now I set up a Nextcloud server and mounted my image directory into it by using the "external storage" feature. It is just a local directory on the same server.
It works, but it does not sort the directories as expected (see screenshot). If I login to the server and do a `ls -l`, the directories are sorted as expected. 
![image](https://user-images.githubusercontent.com/4337999/51376698-3c30d680-1b09-11e9-8b25-47e703d3053b.png)

**Comment by skjnldsv** [comment]
I guess this is the same as any folder right? Not only related to the external storage?

**Comment by rahra** [comment]
No, it is not related to the external storage.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by vodopivecjan** [comment]
Any updates on this, can natural order be disabled somewhere, to use strict alphabetical order?

**Comment by CodeCubeNeo** [comment]
Any updates on this, can natural order be disabled somewhere, to use strict alphabetical order?

**Comment by joskapista44** [comment]
I have the same issue. I user firefox 140.6.0 on macos

Nextcloud Hub25 32.0.3

<img width="837" height="191" alt="Image" src="https://github.com/user-attachments/assets/fbb5ac76-eba3-493e-be63-1e0881b34ccf" />
