### ISSUE TITLE
New account user receives no Groupshares

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/server#13668]
A newly created user receives a group share and cannot download any files.
If the files are then taken from the server and uploaded again, then the newly created user has proper access.
Is anything already known about this?

The upload works flawlessly

Currently Nextcloud 15.02, but I had also seen this phenomenon in earlier versions.

**Comment by rullzer** [comment]
Do you have server side encryption enabled?

**Comment by Schneehexe** [comment]
Yes, is enabled!

**Comment by Schneehexe** [comment]
I have already read somewhere that there are these problems in connection with encryption. But the solution can be impossible to upload all files with every new account you create. Then I can send the files directly to everyone. Nextcloud would then be pointless.

**Comment by rullzer** [comment]
It is not about uploading the files. It is about resharing the share.
This is a known limitation of server side encryption. With master key this should work. But with user keys there is no way around it. Else the whole encryption would be pointless.

In my experince most users are way better of with full disk encryption than with server side encryption.
