### ISSUE TITLE
Add hooks to load scripts

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#13662]
As discussed with @rullzer we should add some hooks to load scripts depending on if the user is on a public page or a logged in one.

E.g. the firstrunwizard doesn't need to load any scripts on the public pages.

**Comment by rullzer** [comment]
so the events. I think it makes most sense to bind them to `OCP\AppFramework\Http\TemplateResponse`

Then we'd have

`OCP\AppFramework\Http\TemplateResponse::loadAdditionalScripts` - generic always
`OCP\AppFramework\Http\TemplateResponse::loadAdditionalScriptsLoggedIn` - only called when logged in

I think those two should be enough to start with right?
