### ISSUE TITLE
Add tags using occ command

### ISSUE THREAD

**Issue by jjsp556** [nextcloud/server#13673]
I'd like to request the ability to add a tag to a file via occ. It is currently possible to have a workflow where files are added to Nextcloud via the command line (add file to the appropriate directory and run occ files:scan), so it would be helpful to also add a tag via the command line as well to account for rule logic that the files_automatedtagging app does not cover.

**Comment by maghog** [comment]
Great idea, that would be very helpful!

**Comment by aventrax** [comment]
I'm have a 90-days auto tagging rule which I use later for file auto-removal. Sometimes I need to exclude some special folder, so I'm using a tag 'retention-excluded' on the folder, doing so the 90-days tag is not being auto-applied.

Unfortunately today I create one of those special folders but I forgot to apply the "retention-excluded" tag manually. The users uploaded 2.000 files on that folder and all of them were auto-tagged with the 90-days tag! I had to remove the tag on 2.000 files, manually! This is a nightmare. 

I ended up doing (after applying the missing 'retention-excluded' tag):

1. Stop users from connecting to nextcloud
2. Downloading all the files manually
3. Deleting all files on my folder 
4. Uploading all the files again

Before doing so, I search for a way to bulk manage the tagged files, but I didn't find any way to do it.
I even tried to manually check the database but I was afraid to modify something directly on the database, so I left it untouched.

Any better way to do it? In my humble opinion, the 'occ' command would be very useful for this task.

Many thanks!

**Comment by szaimen** [comment]
I think this was finally implemented with https://github.com/nextcloud/server/pull/26600 :)

**Comment by Sim0nW0lf** [comment]
> I think this was finally implemented with #26600 :)

I don't see how this is managing file tags.
I just tried these commands and it seems like they manage tags but not corresponding files.
Here is an example:
```
# docker exec --user www-data nextcloud_app php occ tag:add -h                                                                                 Description:
  Add new tag

Usage:
  tag:add [options] [--] <name> <access>

Arguments:
  name                   name of the tag
  access                 access level of the tag (public, restricted or invisible)

Options:
      --output[=OUTPUT]  Output format (plain, json or json_pretty, default is plain) [default: "plain"]
  -h, --help             Display this help message
  -q, --quiet            Do not output any message
  -V, --version          Display this application version
      --ansi             Force ANSI output
      --no-ansi          Disable ANSI output
  -n, --no-interaction   Do not ask any interactive question
      --no-warnings      Skip global warnings, show command output only
  -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug


# docker exec --user www-data nextcloud_app php occ tag:add test public                                                                          - id: 1
  - name: test
  - access: public


# docker exec --user www-data nextcloud_app php occ tag:list                                                                                     - 1:
    - name: test
    - access: public
```

**Comment by noiob** [comment]
I believe that this was closed in error @szaimen

**Comment by toscka** [comment]
Hi,
how can I handle tags of files via the commandline? My UseCase:
After a user has started the "approvla" workflow an the approver rejected the request, I want do delete the "rejected" for restarting the approval-Workflow.

Regards
  Tobias

**Comment by noiob** [comment]
@toscka You can't, there's no command for it

**Comment by Tirguy** [comment]
It's really a shame... We had an identical need ;-)

**Comment by toscka** [comment]
We also need that - my usecase is:
I'm using the approval-workflow and if the approval is rekjected, I want to be able to restart the approval of the same file, after the file has been modified by the user.

**Comment by thekk1** [comment]
I have the same issue here.
After three years, nothing happen in this case?
It's a common thing that you want to remove something that you placed anywhere.
Is it possible to reopen and investigate this issue?

**Comment by mudi0** [comment]
i want to use this feature too

**Comment by gonzalo** [comment]
+1 Also for me, it would be great to have this feature as I create some shared folders from occ and bash scripts and it would be nice to be able to apply tag without having to go through the API or the gui.

**Comment by nwinkelstraeter** [comment]
@szaimen 

I think this issue was closed wrongfully due to a misunderstanding of the feature request.

The PR you mentioned added the ability to create new tags using `occ`  but the request was the ability to tag files with existing tags.  (See quoted message and other comments).
I think that would be a very useful feature.

Could you reopen this issue?

Thank you :)

> > I think this was finally implemented with #26600 :)
> 
> I don't see how this is managing file tags. I just tried these commands and it seems like they manage tags but not corresponding files. Here is an example:
> 
> ```
> # docker exec --user www-data nextcloud_app php occ tag:add -h                                                                                 Description:
>   Add new tag
> 
> Usage:
>   tag:add [options] [--] <name> <access>
> 
> Arguments:
>   name                   name of the tag
>   access                 access level of the tag (public, restricted or invisible)
> 
> Options:
>       --output[=OUTPUT]  Output format (plain, json or json_pretty, default is plain) [default: "plain"]
>   -h, --help             Display this help message
>   -q, --quiet            Do not output any message
>   -V, --version          Display this application version
>       --ansi             Force ANSI output
>       --no-ansi          Disable ANSI output
>   -n, --no-interaction   Do not ask any interactive question
>       --no-warnings      Skip global warnings, show command output only
>   -v|vv|vvv, --verbose   Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
> 
> 
> # docker exec --user www-data nextcloud_app php occ tag:add test public                                                                          - id: 1
>   - name: test
>   - access: public
> 
> 
> # docker exec --user www-data nextcloud_app php occ tag:list                                                                                     - 1:
>     - name: test
>     - access: public
> ```
> 
> I would love to be able to edit file tags in bulk as well with the command line!

**Comment by thekk1** [comment]
> @szaimen
> ..
> Could you reopen this issue?
> ...
> > I would love to be able to edit file tags in bulk as well with the command line!

This will not be happened. Every issue, where I am connected too because of personal interest or having trouble with is closed with a denial or a excuse or a miss understanding and will not be reopened even after many comments that the moderator is wrong.
It's frustrating but the reality.
I saw never even one of my problems solved.

**Comment by XueSheng-GIT** [comment]
While looking for a solution to use occ to tag/untag files, I stumbled over this issue (which was closed for the wrong reason).
Just want to reference the follow up which covers (again) the initial intention of this issue.
https://github.com/nextcloud/server/issues/32735

**Comment by noseshimself** [comment]
So the request was actually too narrow; we needed `tag add [tag]` and `tag remove [tag}`for tag management and `tag mark [file]` and `tag unmark [file]` (or whatever) to make everybody happy...
