### ISSUE TITLE
Try to update to 14.0.6 - An exception occurred while executing 

### ISSUE THREAD

**Issue by Flashdancer1984** [nextcloud/server#13685]
get following massage while updating - now I can't use nextcloud anymore just can update and always get this error :(

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Repair SQLite autoincrement
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_accounts AS SELECT uid, data FROM oc_accounts': SQLSTATE[HY000]: General error: 10 disk I/O error

**Comment by violoncelloCH** [comment]
could you specify from which version you were updating to 14.0.6?

**Comment by Flashdancer1984** [comment]
were I can see that in the database? I can't access the adminpanel anymore, because of the update

**Comment by violoncelloCH** [comment]
depending on the point when the updating process failed, the old version number might be still visible in the config.php ...

**Comment by Flashdancer1984** [comment]
I found in the config.php

 'version' => '13.0.2.1',

**Comment by violoncelloCH** [comment]
hmm seems you were updating from 13.0.2 then...
could you please add more information -- fill in the issue template? without that it's quite impossible to reproduce your issue...

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
