### ISSUE TITLE
Bulk upload triggers `Doctrine\DBAL\Exception\DriverException`

### ISSUE THREAD

**Issue by kmacod** [nextcloud/server#13691]
Bulk uploading image cannot be completed. Keeps returning the error below.

### Steps to reproduce
1. Set up Nextcloud using snap on a $5 Digital Ocean VPS by following [this article.](https://www.digitalocean.com/community/tutorials/how-to-install-and-configure-nextcloud-on-debian-9)
2. Upload a lot of images preferably 300KB on average.
3. Watch system log.

### Expected behaviour
All files should be uploaded to server.

### Actual behaviour
The upload stops after 15 or so images and the below error pops up on the web server log.

```Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `fileid`, `storage`, `path`, `path_hash`, `parent`, `name`, `mimetype`, `mimepart`, `size`, `mtime`, `storage_mtime`, `encrypted`, `etag`, `permissions`, `checksum` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [2, "a27057babd5a2f86f4f4e38cd6da8552"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away```

### Server configuration

**Operating system**
Debian 9

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
PHP 7.1

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 14.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Snap

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Calendar
Default Encryption Module
Restrict login to IP addresses 
Two Factor TOTP Provider 
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/snap/nextcloud/current/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/snap/nextcloud/current/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
  'supportedDatabases' => 
  array (
    0 => 'mysql',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
  'passwordsalt' => 'salt',
  'secret' => 'secret',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => 'example.me',
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '14.0.5.2',
  'overwrite.cli.url' => 'http://localhost',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/sockets/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'user',
  'dbpassword' => 'password',
  'installed' => true,
  'instanceid' => 'ocg263zokca0',
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
None

**Are you using encryption:**
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
None

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu 18.04
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). files:1:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
window.controllers/Controllers is deprecated. Do not use it for UA detection. merged.js:2176
New search handler registered search.js:66:4
querying Whats New data was successful: nocontent merged-template-prepend.js:4488:4
undefined merged-template-prepend.js:4489:4
Loading failed for the <script> with source “https://nc.nyaani.me/index.php/apps/node_modules/vtt.js/dist/vtt.js”. files:1:1
Content Security Policy: The page’s settings blocked the loading of a resource at https://nc.nyaani.me/index.php/apps/node_modules/vtt.js/dist/vtt.js (“script-src”).
AbortError: The operation was aborted. 
too much recursion[Learn More] viewer.js:72:126 
</details>

**Comment by joernhees** [comment]
same version, can confirm that bulk image upload seems wonky, but i get slightly different error messages from time to time:
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`, `mimetype`, `mtime`, `size`, `etag`, `storage_mtime`, `permissions`, `parent`, `checksum`, `path_hash`, `path`, `name`, `storage`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["8", "9", 1547939959, false, "5c43b077338dc", 1547939959, 27, 7462, "", "118d32f7a787a5fb6bdcac67bdef5c68", "appdata_ocj5tktaiun5\/preview\/3804\/1280-394-max.jpg", "1280-394-max.jpg", 2]: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'size' at row 1
```
or
```
Sabre\DAV\Exception\BadRequest: expected filesize 6185311 got 2564096
```

**Comment by ahkuma** [comment]
@joernhees Any idea what might be the problem?
