### ISSUE TITLE
Error when deleting without write access in shared folder not caught

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#13699]
### Steps to reproduce
1. Share a folder with some data in it from account A to another nextcloud account B
2. Accept share in account B
3. Account A removes edit option (write access) for the shared folder
4. Account B tries to delete a file in the shared folder with the three dot menu in the files app

### Expected behaviour
Either the delete icon should not show up at all or at least some error message, that this action is forbidden

### Actual behaviour
The loading animation plays continuously

### Server configuration

**Nextcloud version:** 15.0.2

### Client configuration
**Browser:** Chrome Version 71.0.3578.98 (Official Build) (64-bit) / Safari Version 12.0.2 (13606.3.4.1.4)

**Operating system:** macOS High Sierre 10.13.6 (17G4015)

#### Browser log

```
Failed to load resource: the server responded with a status of 403 (Forbidden)
client.js?v=7f2090a0-0:430 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagNameNS' of null
    at Client._getSabreException (client.js?v=7f2090a0-0:430)
    at client.js?v=7f2090a0-0:715
```
As it happened before I have another error log, but can't really remember what I did different:
```
VM679 core.js:3224 DELETE https://my.nextcloud/remote.php/dav/files/user/Folder/Screen%20Shot%202019-01-20%20at%2019.21.15.png 403 (Forbidden)
request @ VM679 core.js:3224
_simpleCall @ VM692 client.js:707
remove @ VM692 client.js:742
(anonymous) @ VM695 merged-index.js:7433
m.each.m.forEach @ VM679 core.js:18
do_delete @ VM695 merged-index.js:7432
actionHandler @ VM695 merged-index.js:10773
action @ VM695 merged-index.js:10220
_onClickAction @ VM695 merged-index.js:10966
dispatch @ VM679 core.js:3
r.handle @ VM679 core.js:3
19:38:15.530 VM692 client.js:430 Uncaught (in promise) TypeError: Cannot read property 'getElementsByTagNameNS' of null
    at Client._getSabreException (VM692 client.js:430)
    at VM692 client.js:715
```

But as you can see errors deleting seem not to be covered. 

@nextcloud/javascript

**Comment by kesselb** [comment]
Still happening? Sharing is now migrated to Vue ;)
