### ISSUE TITLE
App Menu labels cannot be clicked (again)

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#13698]
### Steps to reproduce
1. Move the cursor slowly on to the App menu from below
2. stop the cursor over the appearing labels
3. click

### Expected behaviour
the app under the cursor should open

### Actual behaviour
nothing

### Server configuration

**Nextcloud version:** 15.0.2

### Client configuration
**Browser:** Chrome Version 71.0.3578.98 (Official Build) (64-bit) / Safari Version 12.0.2 (13606.3.4.1.4)

**Operating system:** macOS High Sierre 10.13.6 (17G4015)

I scanned through other issues but the last fix was included in 15.0.2 and had to do with z-index.
I'm pretty sure this is just a problem, as the `span` element should be inside the `<a>`.

```HTML
<li data-id="files" class="" tabindex="-1" style="">
	<a href="/apps/files/" aria-label="Files">
			<svg width="20" height="20" viewBox="0 0 20 20" alt="">
				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/apps/files/img/app.svg?v=538c09d7" class="app-icon"></image>
			</svg>
		<div class="icon-loading-small-dark" style="display:none;"></div>
	</a>
	<span>Files</span>
</li>
```

This worked for me:
```HTML
<li data-id="files" class="" tabindex="-1" style="">
	<a href="/apps/files/" aria-label="Files">
			<svg width="20" height="20" viewBox="0 0 20 20" alt="">
				<image x="0" y="0" width="20" height="20" preserveAspectRatio="xMinYMin meet" xlink:href="/apps/files/img/app.svg?v=538c09d7" class="app-icon"></image>
			</svg>
		<div class="icon-loading-small-dark" style="display:none;"></div>
		<span>Files</span>
	</a>
</li>
```
@nextcloud/designers

**Comment by danielkesselberg** [comment]
Thank you for reporting this issue :+1: 

There is another issue for that https://github.com/nextcloud/server/issues/13519 Fix is part of 15.0.3 :tada:
