### ISSUE TITLE
http:// action in reset-password form

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#13700]
In the `reset-password` form element I see the action url using `http` instead of `https`, which causes the browser to warn users of the insecure connection:

![screenshot](https://user-images.githubusercontent.com/476060/51443829-09483780-1cef-11e9-9a93-0ecaac1dba17.png)

This is only seen on that instance of Nextcloud, **not** reproduced in another instance. This instance is v15.0.2, official Docker image `nextcloud:latest`.

Why is this `http` there? Can a very old faulty database entry be the cause? The database has been upgraded through all the versions since OC 4 or 5 maybe. There used to be times where it has been run without TLS.

**Comment by danielkesselberg** [comment]
Thank you for reporting this issue :+1: 

Please provide at least the basic information from the issue template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md I guess there are no log entries but configuration, loaded apps, etc are required.

**Comment by apetersson** [comment]
same issue here, this causes the reset password form to not work in our setup (nginx reverse proxy that provides https cert).

**Comment by apetersson** [comment]
it appears that overwrite.cli.url is ignored in this context

**Comment by danielkesselberg** [comment]
See https://github.com/nextcloud/server/issues/13713 for more information if you are running nextcloud **15.0.2**

Workaround 1: https://github.com/nextcloud/server/blob/2767139ca9107b0aff9cfba0e9c0674011bedece/config/config.sample.php#L1561 Add the ip address of your reverse proxy to `trusted_proxies` in your `config.php` 

Workaround 2: https://github.com/nextcloud/server/blob/2767139ca9107b0aff9cfba0e9c0674011bedece/config/config.sample.php#L454 Add your hostname (`overwritehost`) and protocol (`overwriteprotocol`) in your `config.php`

**Comment by mcnesium** [comment]
adding `'overwriteprotocol' => 'https',` to `config.php` works for me. thx @danielkesselberg

**Comment by KaiRo-at** [comment]
Thanks, this also works for us (the case @apetersson mentioned above)!

**Comment by skjnldsv** [comment]
Closing then, please check #13713 as it contains similar reports
