### ISSUE TITLE
Some columns in the database are missing a conversion to big int

### ISSUE THREAD

**Issue by ddi98** [nextcloud/server#13704]
**Operating system**:
Cent OS
**Web server:**
Hosting
**Database:**
mysql
**PHP version:**
7.2.8
**Nextcloud version:** (see Nextcloud admin page)
15.0.2

Hi all, after updating nextcloud to version 15.0.2 I have been returned the following errors in the report:
could you give me the queries to fix these errors from phpMyAdmin? thank you so much

'unfortunately my NextCloud instance being supported on hosting can not execute occ commands'

these are the errors:
The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
Missing index "owner_index" in table "oc_share".
Missing index "initiator_index" in table "oc_share".

Some columns in the database are missing a conversion to big int. Due to the fact that changing column types on big tables could take some time they were not changed automatically. By running 'occ db:convert-filecache-bigint' those pending changes could be applied manually. This operation needs to be made while the instance is offline. For further details read the documentation page about this.
filecache.fileid
filecache.storage
filecache.parent
filecache.mimetype
filecache.mimepart
filecache.mtime
filecache.storage_mtime
mimetypes.id
storages.numeric_id

PS: already in the past to version 14.0.1 I have solved similar errors with these queries that have been reported to me
ALTER TABLE `oc_share` ADD KEY `share_with_index` (`share_with`) USING BTREE;
ALTER TABLE `oc_share` ADD KEY `parent_index` (`parent`) USING BTREE;
ALTER TABLE `oc_filecache` ADD KEY `fs_mtime` (`mtime`) USING BTREE;

but I do not think they are suitable for solving my current problem

**Comment by BernieO** [comment]
I can’t provide the queries, but there is an app available which makes running of occ commands in shared hosting environments possible: occweb
This might be a help for your problem and similar situations in the future,
See here: 
https://help.nextcloud.com/t/how-to-use-occ-commands-on-a-shared-hosting-without-ssh-access/46133

**Comment by beerisgood** [comment]
I have this problem now after update from 17.0.1 to 17.0.2.

Sadly the OCC app is only for Nextcloud 15 and i can't use the OCC command on Uberspace server

**Comment by kesselb** [comment]
> OCC command on Uberspace server

Why? You have ssh access with Uberspace.

**Comment by kesselb** [comment]
Example: `mounts.root_id`

Table: `mounts` 
Column: `root_id` 

Query: `ALTER TABLE $tablePrefix$table MODIFY $column BIGINT NOT NULL`

For example if your prefix is `oc_`: `ALTER TABLE oc_mounts MODIFY root_id BIGINT NOT NULL`
