### ISSUE TITLE
IE 11, where is the checkbox ??

### ISSUE THREAD

**Issue by HelloLemon1992** [nextcloud/server#13706]
### Steps to reproduce
1. just stay in the filelist;

### Client configuration
**Browser: IE 11;

**Operating system: windows10;

![image](https://user-images.githubusercontent.com/10297287/51459354-3c440700-1d93-11e9-9c09-3a0676c3ecec.png)

I can't to see the checkbox ;

**Comment by skjnldsv** [comment]
Hello @HelloLemon1992 
IE11 is not the best experience you can have for nextcloud. A fix have been dispatched recently for that if I recall correctly. Though I will strongly suggest you move to a more recent browser.

Cheers

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/server/issues/11881
