### ISSUE TITLE
URL is rewritten to internal url and logout does not work

### ISSUE THREAD

**Issue by lwt-pressy** [nextcloud/server#13710]
Version: 15.0.2

I have an internal instance of nextcloud with basic domain name nextcloud.internaldomain. All accesses are by the name nextcloud.externaldomain. This worked fine until 15.0.2.

Issue occuring:

* when I logout of nextcloud the url after logout is change to https://nextcloud.internaldomain. So nobody can relogin, because they don't have access to this url. 
* more annoying is, that when I enter the external url I'm still login, even though I just logout. So If someone gets access to my browser he has an open admin login on my server (which I consider a severe security issue).

my own investigation:
* setting overwrite.cli.url to 'https://nexcloud.externaldomain' does not help (as suggested in #12568. The logout page still redirects to https://nextcloud.internaldomain
* removing  https://nextcloud.internaldomain from trusted_domains, makes server inaccessible, because even from https://nexcloud.externaldomain you get "Zugriff über eine nicht vertrauenswürdige Domain"
* all other links I found go to the right url. Only the logout link uses the wrong url.

**Comment by nesnera** [comment]
I have [the same issue](https://github.com/nextcloud/server/issues/13713#issuecomment-464323992).

**Comment by kesselb** [comment]
Dup #13713
