### ISSUE TITLE
Compatibility issue : org.apache.commons.httpclient.HttpClient not found

### ISSUE THREAD

**Issue by hendric-git** [nextcloud/server#13711]
I hope that is the right place for my question. If not i am sorry for my impatience.

I am trying to develop an android application using the Nextcloud Android library. When i try to compile the sample client i get the compiler error: 

"error: cannot access HttpClient
class file for org.apache.commons.httpclient.HttpClient not found"

The README proposes to include 

configurations.all {
    exclude group: "org.slf4j", module: "slf4j-log4j12"
    exclude group: "log4j", module: "log4j"
} 

into my build.gradle file. That changed nothing. I am using minSdkVersion 14, targetSdkVersion 28.

I know that you have already discussed that topic but i can't find a solution. Is there a workaroud?

**Comment by MorrisJobke** [comment]
cc @tobiasKaminsky

**Comment by MorrisJobke** [comment]
Let's close this here as this is for the server repo. Best is to raise such questions in the forum at https://help.nextcloud.com in the future. But maybe @tobiasKaminsky could help in the meantime.

**Comment by tobiasKaminsky** [comment]
Can you open up an issue over here: https://github.com/nextcloud/android-library

**Comment by hgzech** [comment]
I just ran into the same issue.  For me adding the dependencey  `implementation "commons-httpclient:commons-httpclient:3.1@jar"` to the app level build.gradle solved the problem.
