### ISSUE TITLE
Web Updater fails since v14.0.3; ignoring data folder settings

### ISSUE THREAD

**Issue by Schmunzelhummel** [nextcloud/server#13715]
I am not able to update my nextcloud via web updater since version 14.0.3.
I was able to perform updates with the web updater with the versions before.

### Steps to reproduce
1. having your data folder on a usb drive (raspi3B+); handled in config.php > datadirectory
2. start update from NC14.0.3 to 14.0.6 or even NC15 via Web Updater

### Expected behaviour
Update should finish without errors

### Actual behaviour
Update fails at step 9, trying to use default data location /var/www/nextcloud/data

### Server configuration

**Operating system**: raspbian

**Web server:** nginx

**Database:**mariadb

**PHP version:**7.x

Workaround: copy update files from your actual data directory /externalHDD/nc/nc-data/updater-xxxxxxx/downloads/nextcloud to /var/www/ and run occ upgrade

see also topic in the nextcloud forum: [https://help.nextcloud.com/t/update-freeze-could-not-open-input-file-occ/45238](url)

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
