### ISSUE TITLE
file not found in some folders

### ISSUE THREAD

**Issue by van15h** [nextcloud/server#13716]
### Steps to reproduce
1. create a file “original”
2. rename to “ORiginal”
 
![image](https://user-images.githubusercontent.com/28344928/51540372-9063ef80-1e56-11e9-80a2-a13de97fa667.png)

summary still has 4 folders and 2 Files. Two files with same names.

server folder:
![image](https://user-images.githubusercontent.com/28344928/51540383-95c13a00-1e56-11e9-9140-c760dd1d8e82.png)

3. reload page: 4 folders, 3 Files, no error message, files have different names.
Data folder on server is unchanged.
![image](https://user-images.githubusercontent.com/28344928/51540397-a1acfc00-1e56-11e9-94f2-0b9adc4da216.png)

summary showed 4 folders and 3 files, but in data folder we still have one file with the original name.

4. moving or renaming the original file makes the capitalized copy broken. It can not be opened anymore. Our case.
![image](https://user-images.githubusercontent.com/28344928/51540413-ad002780-1e56-11e9-96f4-8e8eaa6329b7.png)
![image](https://user-images.githubusercontent.com/28344928/51540418-affb1800-1e56-11e9-8f2b-0bded5a752b6.png)

Log error: {"reqId":"LQ2p8xuuo2mFRrZhSyC9","level":3,"time":"2019-01-22T14:48:48+01:00","remoteAddr":"ip...","user":"testuser","app":"PHP","method":"GET","url":"\/index.php\/apps\/files_texteditor\/ajax\/loadfile?filename=ORiginal.txt&dir=%2F","message":"file_get_contents(\/mnt\/owncloud\/data\/testuser\/files\/ORiginal.txt): failed to open stream: No such file or directory at \/var\/www\/html\/lib\/private\/Files\/Storage\/Local.php#216","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"14.0.4.2"}

5. Deleting one of the files leaves another entry in web UI, but it is broken, while the file is deleted on the server side.
 
![image](https://user-images.githubusercontent.com/28344928/51540426-b5f0f900-1e56-11e9-9bf9-374cab926993.png)
![image](https://user-images.githubusercontent.com/28344928/51540434-ba1d1680-1e56-11e9-9e38-94eaf954afad.png)

### Expected behaviour
The second file with capitalized characters should never been created.
Each file from the list of files in web UI must be downloadable - should have a real file in data folder on server. 

### Actual behaviour

some files in random folders can not be found on server. Users can not download or open them, but the file is visible in web UI. I checked these files on server side, but they are missing. The data folder is not encrypted. The size of data folder is around 6TB(so i suppose, that we can have more of such missing files). Nextcloud log has no mention about these missing files. 

Some of these missing files i have found with normal Linux `find` command in trash or in versions folder of other users or the owner, some of these files are already renamed and so don't correspond to file names that are visible in web interface.

I suppose, that database has records about these "old" files names, but physically files are not there anymore or are renamed. In this way i can’t use `file:scan` to repair database records, because it does just the opposite (if i understood correctly):
   + adds a new record to database, if new file is found in folder on server, making it visible in web UI;
   + deletes record from database, if no file is found for existing record in database;

what i need - list records from database, if no file is found for existing record, to try to recover them manually later.

the Question is how can i scan and find all these inconsistencies in my data folder on server? 

is there any ready solution (script) or maybe someone has just other good ideas?

### Server configuration

**Operating system:** Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** Mysql 5.7

**PHP version:** 7.0

**Nextcloud version:** 14.04

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from Owncloud 9.0.11. No issues while upgrading or after were detected. 

**Where did you install Nextcloud from:**

**Signing status:** No errors have been found.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
