### ISSUE TITLE
Appdata sub-directories are not created during the update to NC15

### ISSUE THREAD

**Issue by mirkoboehm** [nextcloud/server#13717]
### Steps to reproduce
1. Upgrade on the command line from NC14 to NC15.0.2 using the occ tool.
2. After the update finishes, the web interface shows an "Internal server error".
3.

### Expected behaviour
Tell us what should happen

There should be no error.

### Actual behaviour
Tell us what happens instead

The server produces messages about missing directories like this: 

{"reqId":"kfCilvUDXRqw54dlYLaK","level":3,"time":"2019-01-21T13:47:06+00:00","remoteAddr":"145.94.153.199","user":"...","app":"PHP","method":"GET","url":"\/cloud\/index.php\/settings\/user","message":"touch(): Unable to create file \/var\/www\/html\/cloud\/data\/appdata_<instance>\/css\/settings\/339f-0ce1-settings.css because No such file or directory at \/var\/www\/html\/cloud\/lib\/private\/Files\/Storage\/Local.php#206","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.0.2 Safari\/605.1.15","version":"15.0.2.0"}

for the css/<modulename> and js/<modulename> directories under data\/appdata_<instance>.

Workaround: Once the directories are created manually, it works again.

### Server configuration

**Operating system**:

Linux pi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

**Web server:**

Apache2

**Database:**

MySQL

**PHP version:**

7.0

**Nextcloud version:** (see Nextcloud admin page)

15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

Update from 14

**Where did you install Nextcloud from:**

Official update tool.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by doc-jay** [comment]
to add to this issue, the directory 'avatar' isn't created either after upgrading to 15.0.4

**Comment by kesselb** [comment]
Is this still happening?
