### ISSUE TITLE
share by email - default valid period

### ISSUE THREAD

**Issue by Peterkrijgsman85** [nextcloud/server#13727]
When sharing a file by email, there is no option to be set, that the sharing is valid for like 7 days. 

When you share with link you can (even a default can be configured), but when sharing by mail there is no option to limit the valid period. 

Is this something that will be possible in a next release of Nextcloud?

**Comment by Peterkrijgsman85** [comment]
Sorry for autocorrect. 
Titel should be: share by email - default valid period

**Comment by violoncelloCH** [comment]
this should be possible already... at least it's working for me in NC15...
you have to first share it by mail and then you've got an entry for the email address in the list and on the '...'-menu for the entry you can set for how long the share should be valid...
If this is not working for you and it's a bug, feel free to fill in the issue template and reopen the issue (or create a new, specific one).
