### ISSUE TITLE
Redirect URLs broken if Nextcloud runs in a subfolder

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#13725]
While working on this PR https://github.com/nextcloud/globalsiteselector/pull/18 I realized that the calculation of the redirect_url is broken if Nextcloud runs in a sub-folder.

On my development system Nextcloud is located at `http://localhost/server`. If I create a direct link to a file, e.g. `'http://localhost:70/server/index.php/f/3`, logout and open the URL the login URL looks like this: `http://localhost:70/server/index.php/login?redirect_url=/server/index.php/f/3`, as you can see the 'redirect_url' contains the subfolder '/server'. While I would expect that the URL looks like this: `http://localhost:70/server/index.php/login?redirect_url=/index.php/f/3`

**Comment by skjnldsv** [comment]
Still valid?
