### ISSUE TITLE
Text size of text file previews too big in grid view

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#13720]
![grid view preview text size](https://user-images.githubusercontent.com/925062/51488295-7cac8080-1da5-11e9-9e42-12979ff32680.png)

Probably the text size should maximally be the size of the file name. Where is it possible to reduce this @nextcloud/designers? :)

**Comment by MorrisJobke** [comment]
There you go: https://github.com/nextcloud/server/blob/3259d427eecb5954232ce75cf655d1696783850f/lib/private/Preview/TXT.php#L63-L64

But it should depend on the size it is shown. Problem now: as we don't fetch new previews for the grid, the font would be too small for the list view.
