### ISSUE TITLE
Connection to server lost - When I modify personal information

### ISSUE THREAD

**Issue by fRedW1llim** [nextcloud/server#13729]
### Steps to reproduce
1.Install  nextcloud.
2.Log in with Administrator Account.
3.Modify my personal information（For example, e-mail）or modify the pattern of background tasks.
4.Users can be created normally, but users cannot be deleted（Display information **An error occurred during the request. Cannot continue.**  at the top of the page.）

### Expected behaviour
Modify my personal information.

### Actual behaviour
Display information **Connection to server lost**  at the top of the page.

### Server configuration

**Operating system** :CentOS 7 x86_64_1810

**Web server:** nginx 1.14.2  (In fact, I've tried both Apache and ngnix，the results are the same.)

**Database:** MySQL 5.7.24 （I've tried 5.5/5.6, the results are same）

**PHP version:** PHP 7.1 (I've tried 7.0/7.1/7.2, the results are same)

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** no

**Where did you install Nextcloud from:** https://nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** no

### Client configuration
**Browser:** chrome

**Operating system:** Windows/Android/Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no error log
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
no error log
```
</details>

**Comment by fRedW1llim** [comment]
In addition, every time I log in, I will show Connection to server lost.

**Comment by fRedW1llim** [comment]
I've tried many solutions on github, and they don't seem to work.

**Comment by kesselb** [comment]
Is this still happening?
