### ISSUE TITLE
Nextcloud users group count missing

### ISSUE THREAD

**Issue by rirochet93** [nextcloud/server#13728]
hey, care to check whats my problem is?
why i don't see any groups count? i means how many users in that group?
![image](https://user-images.githubusercontent.com/24819938/51426956-68914380-1c2c-11e9-8f2d-ca3f8a15b00b.png)

EDIT:
so looking at nextcloud doc,
![image](https://user-images.githubusercontent.com/24819938/51427904-19e9a680-1c38-11e9-8c2e-ee3dd3f8d351.png)

so, when im assigning a user to group, the counter works and the count increase as i assign more user into that group.
but when i refresh the page, the counter is missing

please help!

**Comment by skjnldsv** [comment]
Hello, do you use ldap by any chance?

**Comment by rirochet93** [comment]
yes

**Comment by skjnldsv** [comment]
Then this is on purpose.
LDAP doesn't provide user count. Therefore we cannot have that information. :/

**Comment by rirochet93** [comment]
even in groups?
