### ISSUE TITLE
ClamAV Webdav Nextcloud 15.02 not working

### ISSUE THREAD

**Issue by horstvogel** [nextcloud/server#13724]
### Steps to reproduce
On Nextcloud 15 Webdav with active ClamAV you can not create a new documents and you can not store documents you changed.
 
But you can delete documents and you can add new folders. On Browser or Android Client or Windows Client every thing is working. 

### Server configuration

**Ubunt 18.04**:

**NGINX 1.15.:**

**MariaDB 10.3**

**PHP 7.3:**

**Nextcloud version:** 15.02

** fresh install:**

**script https://www.c-rieger.de/nextcloud-using-one-shell-script/**

webdav] Fatal: Sabre\DAV\Exception: Error while copying file to target location (copied bytes: 0, expected filesize: 0 ) at <>

0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
put(null)
1. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
createFile(“Neues Textdokument.txt”, null)
2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
createFile(“Neuer Ordner/Neues Textdokument.txt”, null, null)
3. <>
httpPut(Sabre\HTTP\Reque … “}, Sabre\HTTP\Response {})
4. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
call_user_func_array([Sabre\DAV\CorePlugin {},”httpPut”], [Sabre\HTTP\Requ … }])
5. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
emit(“method:PUT”, [Sabre\HTTP\Requ … }])
6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
invokeMethod(Sabre\HTTP\Reque … “}, Sabre\HTTP\Response {})
7. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
exec()
8. /var/www/nextcloud/remote.php line 163
require_once(“/var/www/nextcl … p”)

PUT /remote.php/webdav/Neuer%20Ordner/Neues%20Textdokument.txt

Reply

**Comment by tstreibl** [comment]
Hi,
guess I have the same problem. See #13639.

**Comment by danielkesselberg** [comment]
Does this patch solve you problem? https://github.com/nextcloud/server/pull/13829

**Comment by nameless62** [comment]
Hello,

Yes it's solve the problem.

Thank you

**Comment by horstvogel** [comment]
Yes hat geklappt!

**Comment by Henk57** [comment]
Same problem. activating ClamAV blocks webdav transfers. 
The 'fix' with if (false && $partStorage->instanceOfStorage(Storage\IWriteStreamStorage::class)) {
in File.php did not work for me.

**Comment by skjnldsv** [comment]
Fixed now that antivirus app is released (for quite a while now)

As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
