### ISSUE TITLE
Action is required to prevent your Let's Encrypt certificate renewals from breaking

### ISSUE THREAD

**Issue by Rick26L** [nextcloud/server#13733]
### Steps to reproduce
1. Have a Let's Encrypt Certificate for your Nextcloud which were created and updated by Certbot with ACME TLS-SNI-01.
2. Receive the Mail from Let's Encrypt "TLS-SNI-01 validation is reaching end-of-life and will stop working on **February 13th, 2019.**"

### Question: 
What do I have to do to change the validating process to HTTP-01, DNS-01 or TLS-ALPN-01.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:**Apache/2.4.37

**Database:**mysql 10.2.19

**PHP version:**7.0.32-0ubuntu0.16.04.1

**Nextcloud version:** 14.0.4

**Where did you install Nextcloud from:** Tech and Me

**Comment by danielkesselberg** [comment]
Please report this issue to https://github.com/nextcloud/vm :+1:
