### ISSUE TITLE
How to get a mail at each login ?

### ISSUE THREAD

**Issue by Bodhiguard** [nextcloud/server#13749]
First all of, Hello !

I was wondering if it was possible to get a mail everytime someone LOG into nextcloud, I tried to check about the login page and edit page to add a php script but couldn't manage to do it due to lack of documentation, so maybe there is a much simpler way of doing it ? 

Thanks.

**Comment by violoncelloCH** [comment]
If you have 2fa enabled, 2fa creates an entry for every successful login in the activity and for the activity you can enable to recieve an email... does this help?

In general: This is an issue tracker for bug reports and feature requests. So either ask your questions in https://help.nextcloud.com / https://portal.nextcloud.com or create a specific feature request here.

**Comment by skjnldsv** [comment]
Closing, please head over the forum for help :)
