### ISSUE TITLE
Upload to an external storage failed with permission errors

### ISSUE THREAD

**Issue by janusn** [nextcloud/server#13756]
### Summary
Uploading a file to a folder created by Nextcloud server on an external storage failed with permissions error.

I have tried to execute the following command as the nextcloud server user, www. It worked successfully. Hence the permission of the destination folder was correct.
`> sudo-u www mv "/mnt/ds918plus/media/shared/temp/19-01-23 10-52-42 1920.png.ocTransferId852991059.part" "/mnt/ds918plus/media/shared/temp/19-01-23 10-52-42 1920.png"`

I have no problem uploading a file to a non-external storage folder in nextcloud. Then I moved those files to the folder in the external storage in nextcloud client successfully.

### Steps to reproduce
1. Launch an iOS nextcloud client app
2. Select a folder under an external storage
2. Press the "+" button at the bottom 
3. Select "upload photos or videos"
4. Select an image and upload.

### Expected behaviour
The image is uploaded to the destination folder

### Actual behaviour
It failed with a "server internal error"

### Server configuration

**Operating system**: 
FreeNAS 12.2-U1

**Web server:** 
NginX 1.4.0

**Database:**
 MySQL 5.6.42

**PHP version:**
 7.1.23

**Nextcloud version:** (see Nextcloud admin page) 
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10.0.1 all the way to 14.0.4
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - user_external
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "htaccess.RewriteBase": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "janusng.asuscomm.com",
            "nextcloud.ngs",
            "10.27.0.23"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/janusng.asuscomm.com",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Asia\/Hong_Kong",
        "installed": true,
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, smb 

**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
WebDAV 
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>
No

### Client configuration
**Browser:**
iOS Nextcloud app 2.22.8.20
**Operating system:**
iOS 12.1.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

Fatal | Sabre\DAV\Exception: Could not rename part file to final file | 2019-01-23T11:25:46+0800
-- | -- | --
Error | unlink(/mnt/ds918plus/media/shared/temp/19-01-23 10-52-42 1920.png.ocTransferId852991059.part): Operation not permitted at /usr/local/www/nextcloud/lib/private/Files/Storage/Local.php#227 | 2019-01-23T11:25:46+0800
Error | renaming part file to final file failed ($run: false, $renameOkay: false, $fileExists: false) | 2019-01-23T11:25:46+0800
Error | Undefined variable: run at /usr/local/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php#223 | 2019-01-23T11:25:46+0800
Error | rename(/mnt/ds918plus/media/shared/temp/19-01-23 10-52-42 1920.png.ocTransferId852991059.part,/mnt/ds918plus/media/shared/temp/19-01-23 10-52-42 1920.png): Permission denied at /usr/local/www/nextcloud/lib/private/Files/Storage/Local.php#272 | 2019-01-23T11:25:46+0800

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Do you still see this issue? I think we fixed `Undefined variable: run` with a newer version.
