### ISSUE TITLE
nc 15 build 15.0.2 deleted files not working properly with end to end encryption enabled

### ISSUE THREAD

**Issue by tscsmith** [nextcloud/server#13759]
### Steps to reproduce
1. running snap version 15.0.2
2. app end-to-end encryption installed and running 
3. deleting files (just one or multiple) and deleting a folder with files inside

### Expected behaviour
The deleted files should go into the trashbin folder ( in gui you will find them in the deleted files section)

### Actual behaviour
The files that you have deleted are just gone. They were deleted immediately and are now unrecoverable. But the deleted folder with files inside are there and recoverable.
The deleted files don't go into the trashbin folder, so it's no gui problem.

All users on the Nextcloud Server are in involved into this issue, wether they have e2e encryption enabled or not. 

### Server configuration

snap install 15.0.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.2

### Workaround:
Remove the e2e encryption app from Nextcloud and it is working again.

Link to reported issue:
#https://github.com/nextcloud/nextcloud-snap/issues/861

**Comment by valmar** [comment]
I am also affected by this problems. Exact symptoms under exact conditions. The bug is still present in version 15.0.5

**Comment by skjnldsv** [comment]
see https://github.com/nextcloud/server/issues/23208
