### ISSUE TITLE
cannot set force_locale

### ISSUE THREAD

**Issue by riddle911** [nextcloud/server#13760]
### Steps to reproduce
1. add ` force_locale` to `config.php`
2.   'force_locale' => 'zh-CN'
3. page doesn't change locale to Chinese.

### Expected behaviour
I want to set default locale to China.

### Actual behaviour
Nothing happens.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.3

**Nextcloud version:**  15 

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**  github.com

I want to know If my settings are right. or how to set locale to China.
Is 'zh_CN' wrong?

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/blob/master/config/config.sample.php#L168

```
'force_language' => 'zh_CN' ,
'force_locale' => 'zh_CN',
```

Does this work for you?

**Comment by danielkesselberg** [comment]
Fix https://github.com/nextcloud/server/pull/13772 (will be part of 15.0.3)

**Comment by riddle911** [comment]
@danielkesselberg 
Thank you for reply.
Finally, I did this and it worked.
`  'force_locale' => 'zh_Hans',`
