### ISSUE TITLE
Error when creating sharing link with enabled (but resetted) expiration time in core-settings

### ISSUE THREAD

**Issue by mFNORD** [nextcloud/server#13787]
### Steps to reproduce
1. Go to settings/admin/sharing
2. "Allow users to share via link" has to be enabled
3. Delete (e.g. backspace) the expiration date / duration time (days)

### Expected behaviour
Default value seems to be 7 days which is shown in the related field via web interface. This value should also be stored in DB when user deletes this field to use the default settings.

### Actual behaviour
Value "7" is shown via the web interface, but the related field "shareapi_expire_after_n_days" (table oc_appconfig / appid: core) is empty in DB and not updated with "7". This leads to an error when creating a sharing-link. After re-entry of e.g. "7" the field is filled correctly and a sharing-link can be created successfully.

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** mySQL

**PHP version:** 7.2.14

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Comment by ricardofrdrc** [comment]
I have this same problem.

[https://imgur.com/VGJc4XQ](https://imgur.com/VGJc4XQ)

**Comment by kruthoff** [comment]
I'm not sure if this is related, but I've a similar problem. The "Share link" checkbox doesn't appear at all anymore. A javascript error is produced (see below) instead.

This happens if the app "Social sharing via email 1.0.5" is enabled. After disabling this app, the Share view works as before.


`Uncaught ReferenceError: link is not defined
    at merged-share-backend.js:2521
    at Function.m.each.m.forEach (core.js:18)
    at child.each (core.js:1157)
    at child.render (merged-share-backend.js:2519)
    at child.render (merged-share-backend.js:4455)
    at child.<anonymous> (merged-share-backend.js:3752)
    at triggerEvents (core.js:1441)
    at triggerApi (core.js:1426)
    at eventsApi (core.js:1225)
    at child.Events.trigger (core.js:1416)`

**Comment by skjnldsv** [comment]
Hi, is this still happening on 16 for any of you?
