### ISSUE TITLE
Cronjob error in combination with files_antivirus and zip files in the datastore

### ISSUE THREAD

**Issue by tgurr** [nextcloud/server#138]
### Steps to reproduce
1. Have the app Antivirus App for files  0.8.0.1 configured for use with clamav
2. Upload a zip file
3. Wait for the cronjob to run and spot an error in the owncloud.log
### Expected behaviour

No error should appear
### Actual behaviour

An error gets logged in the owncloud.log
### Server configuration

**Operating system**: Linux 64bit

**Web server:** Apache 2.4.20

**Database:** MySQL 5.6.30

**PHP version:** 7.0.7

**Nextcloud version:** 9.0.50 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from ownCloud 9.0.2

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-9.0.50.tar.bz2

**Signing status (Nextcloud 9.0 and above):**

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
    - EXTRA_FILE
        - .webapp-nextcloud-9.0.50

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.webapp-nextcloud-9.0.50] => Array
                        (
                            [expected] => 
                            [current] => 
                        )

                )

        )

)
```

**List of activated apps:**

```
Enabled:
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_antivirus: true
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_videoplayer: 0.9.8
  - gallery: 14.5.0
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - activity
  - encryption
  - external
  - files_external
  - files_trashbin
  - files_versions
  - firstrunwizard
  - notifications
  - user_external
  - user_ldap
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "511a3702414abm",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/nextcloud.domain.example\/htdocs\/data",
        "dbtype": "mysql",
        "version": "9.0.50.0",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "versions": "false",
        "maxZipInputSize": 268435456,
        "allowZipDownload": true,
        "forcessl": true,
        "knowledgebaseenabled": false,
        "appstoreenabled": true,
        "updatechecker": false,
        "0": true,
        "maintenance": false,
        "theme": "",
        "default_language": "de_DE",
        "loglevel": "1",
        "trusted_domains": [
            "nextcloud.domain.example"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true
    }
}
```

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chromium/Firefox/IE

**Operating system:** Linux/Windows
#### Web server error log

```
none
```
#### Nextcloud log (data/owncloud.log)

```
[...]
{"reqId":"V2LHDgoBZAcAAAW4is0AAAAQ","remoteAddr":"xxx.xxx.xxx.xxx","app":"core","message":"Error while running background job (class: OC\\BackgroundJob\\Legacy\\RegularJob, arguments: Array\n(\n    [0] => OCA\\Files_Antivirus\\Cron\\Task\n    [1] => run\n)\n): {\"Exception\":\"OCP\\\\Files\\\\NotFoundException\",\"Message\":\"File with id \\\"40157\\\" has not been found.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud.domain.example\\\/htdocs\\\/apps\\\/files_antivirus\\\/lib\\\/backgroundscanner.php(78): OC\\\\Files\\\\View->getPath(40157)\\n#1 \\\/var\\\/www\\\/nextcloud.domain.example\\\/htdocs\\\/apps\\\/files_antivirus\\\/lib\\\/cron\\\/task.php(21): OCA\\\\Files_Antivirus\\\\BackgroundScanner->run()\\n#2 [internal function]: OCA\\\\Files_Antivirus\\\\Cron\\\\Task::run()\\n#3 \\\/var\\\/www\\\/nextcloud.domain.example\\\/htdocs\\\/lib\\\/private\\\/backgroundjob\\\/legacy\\\/regularjob.php(31): call_user_func(Array)\\n#4 \\\/var\\\/www\\\/nextcloud.domain.example\\\/htdocs\\\/lib\\\/private\\\/backgroundjob\\\/job.php(52): OC\\\\BackgroundJob\\\\Legacy\\\\RegularJob->run(Array)\\n#5 \\\/var\\\/www\\\/nextcloud.domain.example\\\/htdocs\\\/cron.php(171): OC\\\\BackgroundJob\\\\Job->execute(Object(OC\\\\BackgroundJob\\\\JobList), Object(OC\\\\Log))\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud.domain.example\\\/htdocs\\\/lib\\\/private\\\/files\\\/view.php\",\"Line\":1677}","level":3,"time":"2016-06-16T15:34:38+00:00","method":"GET","url":"\/cron.php","user":"--"}
[...]
```

The file in question "40157" is a zip file, if I run clamscan manually on the file it works fine:

```
----------- SCAN SUMMARY -----------
Known viruses: 4508245
Engine version: 0.99.2
Scanned directories: 0
Scanned files: 1
Infected files: 0
Data scanned: 11.87 MB
Data read: 5.84 MB (ratio 2.03:1)
Time: 19.107 sec (0 m 19 s)
```

If I delete the file in question from nextcloud, then on the next cron run it hits the next zip file with the same error message (obviously with a different file id though).

**Comment by hunter-nl** [comment]
I have the same issue. But the file(s) are not zip files. It is just random files. When error occurs it is always the same file. When that file has been deleted, the on next random file the error occurs.
Only difference with the above system description above is I upgraded from owncloud 8.0.2 and web server is nginx and php5.5.

**Comment by schiessle** [comment]
This only happens if the anti virus app is enabled, right? In this case it might be a good idea to open a issue in the anti virus repository https://github.com/owncloud/files_antivirus 

Did you checked if there already exists a similar issue?

**Comment by hunter-nl** [comment]
When enabled in owncloud, there is no issue. It only happens when enabled in nextcloud.

**Comment by tgurr** [comment]
Same for me, I didn't spot this error while running ownCloud (9.0.2).

**Comment by schiessle** [comment]
> When enabled in owncloud, there is no issue. It only happens when enabled in nextcloud.

Thanks, good to know. @LukasReschke is it possible that this is somehow related to your security improvements in Nextcloud? Just guessing.

**Comment by hunter-nl** [comment]
After upgrading to 9.0.51 or 9.0.52. This issue has been solved for me.

**Comment by tgurr** [comment]
I still see the error after uprading to 9.0.52.

**Comment by chef2gare** [comment]
for gentoo like distrib, you should include the patch from https://github.com/kaindl/owncloud-core/commit/1395652cae21f2f0e813ad83b4138f2aca2a0f30
file .webapp-nextcloud-version is used by the webapp manager of gentoo.

**Comment by MorrisJobke** [comment]
I can't reproduce this anymore with the latest version of the antivirus app from http://github.com/nextcloud/files_antivirus/ and Nextcloud 11.

Please recheck with a newer version if this is still a problem for you.
