### ISSUE TITLE
Upgrade Nextcloud 15 and error Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload"

### ISSUE THREAD

**Issue by najcardboyz** [nextcloud/server#13808]
I use minio as a gateway for b2, at nextcloud 14 everything works, I know minio deleted the b2 gateway in 2019, but the 2018 release is still working. the problem happened after I upgraded to nextcloud stable 15.2. I am checking the minio gateway and it works properly

following log from nextcloud
-------------------------------------
[webdav] Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "http://103.89.3.55:19991/naja-nextcloud-primary-1/urn%3Aoid%3A604990?uploadId=4_z1214b461af3239bd63320016_f2042285b58d264cc_d20190125_m015039_c002_v0001108_t0057"; AWS HTTP error: Client error: `POST http://103.89.3.55:19991/naja-nextcloud-primary-1/urn%3Aoid%3A604990?uploadId=4_z1214b461af3239bd63320016_f2042285b58d264cc_d20190125_m015039_c002_v0001108_t0057` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Mes (truncated...)
 NoSuchBucket (client): The specified bucket does not exist - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Resource>/naja-nextcloud-primary-1/urn:oid:604990</Resource><RequestId>157CF45D3191B8D0</RequestId><HostId>3L137</HostId></Error> at <<closure>>

 0. /var/najacloud/apps/dav/lib/Connector/Sabre/File.php line 209
    convertToSabreException(Aws\S3\Exception ... {})
 1. /var/najacloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    put(null)
 2. /var/najacloud/apps/dav/lib/Upload/UploadFolder.php line 39
    createFile("0", null)
 3. /var/najacloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
    createFile("0", null)
 4. /var/najacloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
    createFile("uploads/naja/we ... 0", null, null)
 5. <<closure>>
    httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 6. /var/najacloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
 7. /var/najacloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    emit("method:PUT", [Sabre\HTTP\Requ ... }])
 8. /var/najacloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. /var/najacloud/apps/dav/lib/Server.php line 301
    exec()
10. /var/najacloud/apps/dav/appinfo/v2/remote.php line 35
    exec()
11. /var/najacloud/remote.php line 163
    require_once("/var/najacloud/ ... p")

PUT /remote.php/dav/uploads/naja/web-file-upload-5eae7748f494547bf65c26c4975e77f1-1548381025991/0
from 114.125.214.21 by naja at 2019-01-25T01:50:53+00:00

**Comment by asadana** [comment]
Possible duplicate already fixed by PR #14273 
Needs to be retested with 15.0.5

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

**Comment by much-doge** [comment]
> As the version of the software you've reported this for has [reached _end of life_](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen

Hey I'm using the latest Minio as b2 gateway and using it as external storage on my Nextcloud 17.0.5 yet this issue still persist. Here's the detail from the log:

[webdav] Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://**MY NEXTCLOUD SERVER**/nextcloud-at-backblaze/til.jpg?uploadId=4_zc86e0f856a5bf40d6afc011d_f2062c4b0259be743_d20200416_m135517_c000_v0001028_t0041"; AWS HTTP error: Client error: `POST https://**MY MINIO B2 GATEWAY/nextcloud-at-backblaze/til.jpg?uploadId=4_zc86e0f856a5bf40d6afc011d_f2062c4b0259be743_d20200416_m135517_c000_v0001028_t0041` resulted in a `404 Not Found` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Mes (truncated...)
 NoSuchBucket (client): The specified bucket does not exist - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><Key>til.jpg</Key><BucketName>nextcloud-at-backblaze</BucketName><Resource>/nextcloud-at-backblaze/til.jpg</Resource><RequestId>1606514F429DBAFB</RequestId><HostId>25827a70-3301-418d-87dc-de883bc3278e</HostId></Error> at <<closure>>

0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 243
   OCA\DAV\Connector\Sabre\File->convertToSabreException(Aws\S3\Exception ... {})
1. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
   OCA\DAV\Connector\Sabre\File->put(null)
2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
   OCA\DAV\Connector\Sabre\Directory->createFile("til.jpg", null)
3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
   Sabre\DAV\Server->createFile("minio/til.jpg", null, null)
4. <<closure>>
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
5. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
7. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
8. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
   Sabre\DAV\Server->exec()
9. /var/www/nextcloud/remote.php line 163
   undefinedundefinedrequire_once("/var/www/nextcl ... p")

PUT /remote.php/webdav/minio/til.jpg
from **MY IP** by **MY NEXTCLOUD ACCOUNT** at 2020-04-16T13:55:20+00:00
