### ISSUE TITLE
Link to issue template is broken

### ISSUE THREAD

**Issue by DrRSatzteil** [nextcloud/server#13809]
The link to the issue template in CONTRIBUTING.md is broken:

server/.github/CONTRIBUTING.md

Sorry for not using the issue template...

**Comment by DrRSatzteil** [comment]
Created 
https://github.com/nextcloud/server/pull/13810

**Comment by kevgathuku** [comment]
Since this is now fixed in https://github.com/nextcloud/server/pull/13810
Can we close this issue?

**Comment by DrRSatzteil** [comment]
Closed
