### ISSUE TITLE
Document database requirements for autotest.sh

### ISSUE THREAD

**Issue by rummatee** [nextcloud/server#13803]
As I have found from examining the autotest.sh file, it requires a database called 'oc_autotest' and user with the same name that has the same name and the password 'owncloud'.

However I could not find any documentation for this. In my opinion it should be documented here: https://docs.nextcloud.com/server/15/developer_manual/core/unit-testing.html

In my opinion, it would be even better to have a guided installation process that allows to use and save a custom configuration for database and user, similar to the actual Nextcloud installation process.

**Comment by szaimen** [comment]
Looks like this was fixed in https://github.com/nextcloud/documentation/pull/1296
