### ISSUE TITLE
Improved update channels design in settings

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#13806]
Currently the version section has a lot of info (too much) and especially the update channel is a huge amount of text:

![version section and update channels](https://user-images.githubusercontent.com/925062/51710008-3581f200-2028-11e9-846a-5bc931109232.png)

We could do this much better with our [popover menu](https://docs.nextcloud.com/server/latest/developer_manual/design/popovermenu.html) in the version we use also for the federation settings:
(Just a mockup, icons are not adjusted, and we have to decide where to put the warning text about not being able to downgrade.)
![update channel dropdown](https://user-images.githubusercontent.com/925062/51710009-3581f200-2028-11e9-915a-b90b9e71dd62.png)

What do you think @nextcloud/designers @karlitschek?

**Comment by karlitschek** [comment]
Just awesome :+1:

**Comment by skjnldsv** [comment]
Awesome change!!

**Comment by MorrisJobke** [comment]
I love it 👍

**Comment by MorrisJobke** [comment]
Let me do that.

**Comment by MorrisJobke** [comment]
@jancborchardt Could you provide icons for production, stable, beta and one for custom channel (maybe the pencil icon is there enough)?

**Comment by MorrisJobke** [comment]
Fix is in #14168

**Comment by MorrisJobke** [comment]
And I need icon ideas for the channels - @ChristophWurst already proposed a nice one: https://github.com/nextcloud/server/pull/14168#issuecomment-462853821 😉
