### ISSUE TITLE
Make it possible to unregister OCA.Search

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13811]
**Is your feature request related to a problem? Please describe.**
In Mail I would like to only show the app search if the user is on a view that supports it (folder, messages), but hide it on the others (setup, settings).

**Describe the solution you'd like**
I would like to have a method `unregister` that removes the search from the header.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

cc @skjnldsv

**Comment by MorrisJobke** [comment]
Is this something for 16 or should we move it to 17?

**Comment by ChristophWurst** [comment]
I guess 17.
