### ISSUE TITLE
File Verification

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#1381]
I would like to propose a feature:

The ability to have all files that are uploaded to be verified against their source using a hash such as SHA-256 or FNV. I am not sure which hash would be preferred but something that is secure would be great.

**Comment by nickvergessen** [comment]
A checksum feature was introduced in Nextcloud 10

https://github.com/owncloud/core/pull/21997 maybe @rullzer can tell more

**Comment by rullzer** [comment]
No that just stores the checksum. We don't verify server side.
That functionality is not there.

**Comment by c0fe** [comment]
I have had weird things happen during upload with Owncloud, I have now more preference for Nextcloud but I would like to see this feature implemented to give a peace of mind.

**Comment by menaceone** [comment]
would be a great feature and improving data reliability

**Comment by Ninos** [comment]
Also think that such feature could make sense. Hope I'm right :)

**Comment by skjnldsv** [comment]
I think this is something to have an external app.

**Comment by skjnldsv** [comment]
https://apps.nextcloud.com/apps/checksum
