### ISSUE TITLE
Make it possible to programmatically set the current input of OCA.Search

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13812]
**Is your feature request related to a problem? Please describe.**
If apps trigger search programmatically, like an initial render where the search term is part of the URL, they should be able to set the search input value. This allows the user to see and edit the current term.

**Describe the solution you'd like**
A method like `setQuery` or `setTerm` that updates the input field.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

cc @skjnldsv

**Comment by MorrisJobke** [comment]
Is this something for 16 still or should we move it to 17?

**Comment by MorrisJobke** [comment]
I guess this is something completely overhauled and we should maybe close this, right?
