### ISSUE TITLE
OCSExption "Cannot remove yourself from the admin group" is not translatable

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#13820]
Reported at forums.

See https://help.nextcloud.com/t/die-deutsche-ubersetzung-von-nextcloud-hier-diskutieren-und-fehler-melden/32139/120

Source line:

https://github.com/nextcloud/server/blob/b8b650aee697e4ab52f1f28e7e2287ac9a27456c/apps/provisioning_api/lib/Controller/UsersController.php#L751

**Comment by rakekniven** [comment]
Same for another one: "Bad request"

https://github.com/nextcloud/server/blob/b8b650aee697e4ab52f1f28e7e2287ac9a27456c/apps/provisioning_api/lib/Controller/UsersController.php#L333

Should I file separate issue?

**Comment by skjnldsv** [comment]
The api messages should not be translated I think.
@rullzer @blizzz @nickvergessen ?

**Comment by nickvergessen** [comment]
Well, we could turn it into a hintexception and then have english+translated.
But not sure that breaks assumptions on the API users.

**Comment by rakekniven** [comment]
The text is visible to the user so it should be translated IMHO.

**Comment by skjnldsv** [comment]
@rakekniven where did you saw the message? Users management?

**Comment by rakekniven** [comment]
Forum is back online. 
See link from initial post:

https://help.nextcloud.com/t/die-deutsche-ubersetzung-von-nextcloud-hier-diskutieren-und-fehler-melden-was-sollte-ich-wissen-wenn-ich-bei-der-ubersetzung-helfen-mochte-oder-eine-anmerkung-habe/32139/118

**Comment by skjnldsv** [comment]
Ah yes, I recall now. We're indeed using the error message as a notification.
Shall we translate the error message or use a matching code on the request on the users management and translate it from there?

**Comment by szaimen** [comment]
I suppose this issue is still valid?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by susnux** [comment]
I would say we should translate the message as you should rather rely on the exception code for any programmatically usage. Translating in the frontend seems to duplicate logic / code.
