### ISSUE TITLE
External storage admin GUI becomes unusable with a lot of (SMB) storages configured

### ISSUE THREAD

**Issue by va1entin** [nextcloud/server#13828]
### Steps to reproduce
1. Configure a lot (my test env had over 400) of external SMB storages
You can download and import [this file](https://github.com/nextcloud/server/files/2797064/external_storage_demo_config.json.txt)
 using occ to configure 400 demo mounts.
<pre>sudo -u www-data /var/www/html/occ files_external:import file.json</pre>
2. Open external storages admin settings in web UI
3. Tab crashes/takes forever 

### Expected behaviour
Admin UI is still usable even with hundreds of SMB shares
I haven't analyzed it deeper but I believe the problem is that upon opening the external storages admin page, Nextcloud tries to connect to every single SMB share with the currently logged in user. With over 400 storages configured the tab crashes in both Firefox and Chrome. Nextcloud itself is luckily not affected of any crashes. If it's really Nextcloud trying to connect to every single mount to check whether it's reachable causing this I'd suggest to deactivate this behaviour by default and have the user click the red **!** to test the mount manually.
For anyone facing this issue: occ can still be used to manage the mounts in Nextcloud even when the web UI is already unusable.

### Actual behaviour
Tab/browser crashes or the site takes "forever" too load

I'll gladly supply further config/info if needed, but since I'm using the official Nextcloud Docker container (Nextcloud App on UCS) it's probably not related to that.

### Server configuration

**Operating system**: UCS 4.3 (based on Debian 9) / Ubuntu 18.04.1 LTS in container

**Web server:** Apache 2.4.29-1ubuntu4.5

**Database:** PostgreSQL 9.6.10-0+deb9u1

**PHP version:** 7.2+60ubuntu1

**Nextcloud version:** 14.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** UCS App Cente

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox 64 / Chromium 71.0.3578.98

**Operating system:** Linux Mint 19.1 / Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
