### ISSUE TITLE
Redis::connect() expects parameter 2 to be integer, string given at /var/www/html/lib/private/RedisFactory.php#84	

### ISSUE THREAD

**Issue by frankyifei** [nextcloud/server#13848]
### Steps to reproduce
1. setup redis in config.conf, with this line:
```
'memcache.local' => '\OC\Memcache\Redis',
  'redis' => array(
    'host' => 'host.docker.internal',
    'port' => '6379',
  ),
```
2. go to log in settings
3. this error will come every second 
`Redis::connect() expects parameter 2 to be integer, string given at /var/www/html/lib/private/RedisFactory.php#84	`

### Expected behaviour
This should not happen because I just followed manual. After checking the code in RedisFactory.php, I came up with a solution by commenting out the 'port' line in config.conf. Then the error stopped. It should be easy to fix, just convert port to integer before pass it to Redis::connect().

**Comment by danielkesselberg** [comment]
`'port' => 6379,` (no single quotes around the port). Where is this wrong example from?

**Comment by danielkesselberg** [comment]
Documentation (https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/caching_configuration.html#id2) looks correct to me.
