### ISSUE TITLE
Nextcloud uploads files partially while Primary Storage is S3

### ISSUE THREAD

**Issue by ahmedabt** [nextcloud/server#13845]
## issue ##
The resource stream used by S3ClientTrait class is seekable according to stream_get_meta_data function while, in reality, seek(0) doesn't seek the stream to 0 which causes the loss of data.

S3 "ObjectUploader" decides if multipart is required or not, in function requiresMultipart, by copying the stream to another buffer Psr7\copy_to_stream($body, $buffer, MultipartUploader::PART_MIN_SIZE) and then resets the stream position using $body->seek(0) however, in reality, the stream is not adjusted to position 0. Hence, it loses data with size equals MultipartUploader::PART_MIN_SIZE.

The issue is confirmed by adding the following line as a hack in function "promise" in "ObjectUploader.php" and then it is uploaded the file successfully.
$this->body = new Psr7\NoSeekStream($this->body);

### Steps to reproduce
1. Configure your Primary Storage to S3
2. Upload file bigger than MultipartUploader::PART_MIN_SIZE (>5MB) 
3. The file is partially uploaded to S3, for example, if the file size is 5.2 MB then 0.2 MB will be uploaded only. 

### Expected behaviour
The whole file should be uploaded.

### Actual behavior
The file is partially being uploaded.

### Server configuration
Using the latest docker images (ID: 86bc296c676d)

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**Comment by rullzer** [comment]
Fixed with https://github.com/nextcloud/server/pull/13882. Will be in the next release.
