### ISSUE TITLE
After having viewed two mp4 files, these files could neither be moved nor deleted (they appear to be locked - from the view action???)

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#13841]
I viewed (via Firefox Browser) 2 out of 9 mp4 files in a user account. 

I wanted to move all 9 files to subfolder "videos". This worked for 7 files, but the 2 viewed files are locked and cannot be deleted.

I tried this:
* reload (Ctrl F5) and also fully restarted the browser
* Nextcloud user logout and login
* the same on a different computer

Nothing worked; the two viewed files are locked and can neither moved nor deleted. Remark: copying was possible.

* Nextcloud 15.0.2

Log: 
```
[no app in context] Error: OCP\Lock\LockedException: "files/b...f" is locked at <<closure>>

 0. lib/private/Files/Storage/Common.php line 778
    changeLock("files/b...f", 2)
 1. lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    changeLock("files/Fotos von ... 4", 2, OC\Lock\DBLockingProvider {})
 2. lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    changeLock("files/... 4", 2, OC\Lock\DBLockingProvider {})
 3. lib/private/Files/View.php line 1964
    changeLock("files/ ... 4", 2, OC\Lock\DBLockingProvider {})
 4. lib/private/Files/View.php line 1140
    changeLock("/ ... 4", 2)
 5. lib/private/Files/View.php line 709
    basicOperation("unlink", "/ ... 4", ["delete"])
 6. apps/dav/lib/Connector/Sabre/File.php line 388
    unlink("/ ... 4")
 7. 3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    delete()
 8. 3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
    delete("files/ ... 4")
 9. <<closure>>
    httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
10. 3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
11. 3rdparty/sabre/dav/lib/DAV/Server.php line 479
    emit("method:DELETE", [Sabre\HTTP\Requ ... }])
12. 3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. apps/dav/lib/Server.php line 301
    exec()
14. apps/dav/appinfo/v2/remote.php line 35
    exec()
15. remote.php line 163
    require_once("/ ... p")

DELETE /remote.php/dav/files/.../VID...mp4 from ... by ... at 2019-01-26T11:07:30+01:00
```

**Comment by r4sas** [comment]
Have same problem, but with m4a files.

**Comment by pwhack** [comment]
I'm getting the same error during iOS app sync'ing to Nextcloud. Seems to be an overall file/db locking backend causing this. Linking https://github.com/nextcloud/ios/issues/788 here.

**Comment by skjnldsv** [comment]
Still happening on latest versions?

**Comment by r4sas** [comment]
Didn't have that issue in latest versions, but not tested.

**Comment by skjnldsv** [comment]
> but not tested

So you did not tested or you don't have the issue anymore? I'm confused @r4sas :stuck_out_tongue:

**Comment by r4sas** [comment]
I said like this because earlier it can happen by itself when I played any audio track and after that tried delete it or move. Now I haven't meet that issue for year.

**Comment by skjnldsv** [comment]
Awesome closing then :+1: 
If it happens again, please reopen ;)
