### ISSUE TITLE
Warn user if MySQL is not correctly configured

### ISSUE THREAD

**Issue by gloomytrousers** [nextcloud/server#13853]
**Is your feature request related to a problem? Please describe.**
When MySQL is not configured with innodb_file_per_table=1 and utf8mb4 collation, there are problems related to emojis (nextcloud/social#368, nextcloud/social#293). The fix is now mentioned in the README (nextcloud/social#341) but this could easily be missed.

**Describe the solution you'd like**
As per the comment from @9662 in nextcloud/social#341, this could be detected (`select @@innodb_file_per_table;` would be part of it) and displayed in the UI, similar to how the ".well-known/webfinger isn't properly set up" error is displayed. This would link to https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html.

**Comment by nickvergessen** [comment]
Moving to the server because it should be a warning there

**Comment by kesselb** [comment]
Is this fixed by https://github.com/nextcloud/server/pull/14398?

**Comment by gloomytrousers** [comment]
That it's halfway there - it detects if collation is not utf8mb4. It doesn't check innodb_file_per_table though.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
