### ISSUE TITLE
"Password protect by Talk" option not immediatelly shown for link shares

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#13863]
### Steps to reproduce
1. Share a file as link
2. Add a password
3. Try to select "Password protect by Talk"

### Expected behaviour
Option is visible after setting the password and can be selected easily

### Actual behaviour
After setting the password you need to close and reopen the dropdown.
Seems like some model property is not bound correctly.

**Comment by mattronix** [comment]
Same issue

**Comment by skjnldsv** [comment]
@nickvergessen still relevant?

**Comment by nickvergessen** [comment]
No, it's fixed
