### ISSUE TITLE
Feature Request: Multiple emails share

### ISSUE THREAD

**Issue by microsard81** [nextcloud/server#13872]
Hi All,

is it possible share an elements with multiple email address? Could be simple and useful.

Thanks a lot

**Comment by bpcurse** [comment]
If you refer to files and folders you can already do this in Nextcloud 15.

Simply enter an email address in the sharing field and create the share, then repeat the steps with another email address. You can even set different permissions, password protection or an expiry date.

**Comment by MorrisJobke** [comment]
Yes - this is possible with Nextcloud 15.
