### ISSUE TITLE
allow admin to enforce expire date for user shares (as it works for link shares)

### ISSUE THREAD

**Issue by MinIsMin** [nextcloud/server#13898]
### Steps to reproduce

- in settings set the default expiry date to 7 days and enforce it
- share a file to a user and open the expiration date picker

### Expected behaviour

- The user should not be able to choose a date longer than 7 days (like it worked for the last years)

### Actual behaviour

- The user is able to set a date without restriction

### More info
- The restriction applies when sharing via URL but not to a user
- It did work some weeks ago

#### Nextcloud configuration
```
{
    "system": {
        "htaccess.RewriteBase": "\/nextcloud",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "[domain]"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "updater.release.channel": "stable"
    }
}
```

#### Are you using an external user-backend, if yes which one: no

**Comment by violoncelloCH** [comment]
as you already stated in your issue, this setting applies to link shares but not to user shares...
so I would suggest to turn your issue into a feature request...

**Comment by violoncelloCH** [comment]
@MinIsMin you state this has worked in previous versions... are you sure it did (can you test it)? If I'm right this feature didn't exist for user shares... (the setting is explicite for link shares)

**Comment by MinIsMin** [comment]
I have no machine to test it with an older versions but I thought this has worked and was surprised why it didn't work anymore, so I wrote this bug report.

But if this never existed, it would be good if it would become a feature.

**Comment by violoncelloCH** [comment]
added it to the milestone, so it'll eventually be targeted... :)

**Comment by Beeez** [comment]
Will this be added to Nextcloud 18 milestones? I had just started enforcing Expiration on Link shares, however any need shares to internal users now are being Enforced to the value set on Link shares. For the time being i just disabled it for now though.

**Comment by wiswedel** [comment]
The feature is available since Nextcloud 19 (maybe even 18, not sure anymore):

![image](https://user-images.githubusercontent.com/1804221/95567954-e9f1c080-0a23-11eb-94e2-240e97c7f075.png)
