### ISSUE TITLE
ContactManager createorupdate function doesn't care about etag

### ISSUE THREAD

**Issue by ningappa** [nextcloud/server#13890]
see code 
[https://github.com/nextcloud/server/blob/050b9135d50f57c777c157bb7aa8c102524b2c77/apps/dav/lib/CardDAV/AddressBookImpl.php#L130-L155](https://github.com/nextcloud/server/blob/050b9135d50f57c777c157bb7aa8c102524b2c77/apps/dav/lib/CardDAV/AddressBookImpl.php#L130-L155)

Shouldn't be this care for etag?

**Comment by skjnldsv** [comment]
@georgehrke should it?

**Comment by georgehrke** [comment]
@ningappa Can you elaborate on this?
