### ISSUE TITLE
Calender attendees email - missing FROM information, if CalDAV-Clients used

### ISSUE THREAD

**Issue by frank-github** [nextcloud/server#13896]
### Steps to reproduce
create event with attendees
1. from browser (Calender view inside Nextcloud)
2. from thunderbird
3. from Android CalDav
4. any other CalDav-Client

### Expected behaviour
**complete** name should be **part of FROM** in invitation email

### Actual behaviour
FROM only has string "via Nextcloud" if CalDAV Clients are used
Only events created from CalenderView "inside Nextcloud" (Browser) had complete name in FROM, ex. "my name via Nextcloud"

more informations look at: 
https://github.com/nextcloud/calendar/issues/1092

### Server configuration

**Operating system**: Linux
**Web server:** apache
**Database:** mysql
**PHP version:** 7.1
**Nextcloud version:**  15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade
**Where did you install Nextcloud from:**
Web-GUI for Update

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.  **No errors have been found.**

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.2
  - dav: 1.8.1
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - files_external
  - spreed
  - survey_client
  - user_ldap

**Nextcloud configuration:**
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.snowyowl.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.snowyowl.de\/nextcloud",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "files",
        "session_lifetime": 7200,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": 100,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": []
    }

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:**   Caldav

### Client configuration
  Android DavDroid   or  Linux Thunderbird with Lightning

**Comment by akki42** [comment]
Changing $senderName to $meetingInviteeName in line 228 of apps/dav/lib/CalDAV/Schedule/IMipPlugin.php is a temporary workaround to include (at least) the email address (but not the name) when using an external client (e.g. DAVx, Lightning).

BTW: This bug has been reported previously at https://github.com/nextcloud/server/issues/9107 ,,,

**Comment by kesselb** [comment]
> Changing $senderName to $meetingInviteeName in line 228 of apps/dav/lib/CalDAV/Schedule/IMipPlugin.php is a temporary workaround to include the user's email address in the FROM text field (instead of the name - but still better than an empty value) when using an external client (e.g. DAVx, Lightning).
> 
> BTW: This bug has been reported previously at #9107 ,,,

Looks valid to me. Mind to create a pull request for your suggested change?

**Comment by akki42** [comment]
Well, it's not really a fix, but just an interim measure. Unfortunately, I lack the knowledge how to look up the DAV-acting user's full name from nextcloud's database...

**Comment by georgehrke** [comment]
If someone wants to take this up, here are the steps:
1. Add `IUserManager` to constructor
2. Take `$senderName` and feed it onto `IUserManager::getByEmail()`
3. Check if any user match, if yes, take first match.
4. The result of `IUserManager::getByEmail()` is an array of `IUser`, so you can simply call `$user->getDisplayName()`

**Comment by akki42** [comment]
Unfortunately, I once again receive / see invitation emails without user's name (i.e. from is only "via nextcloud"). As far as I can tell, it started again with Nextcloud 22?
