### ISSUE TITLE
Trash bin table sort adds deletion timestamp to file extension

### ISSUE THREAD

**Issue by williambargent** [nextcloud/server#139]
### Steps to reproduce
1. Delete a file
2. Soft deleted by time deleted
### Expected behaviour

Sorts the files into order of deletion
### Actual behaviour

Sorts but also outputs random numbers into the file extension
Edit: Only sorts in the trash seem to be affected
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache /2.4.18

**PHP version:** 7.0.4

**Nextcloud version:** 9.0.50 (stable)

![capture](https://cloud.githubusercontent.com/assets/11518756/16123562/62ff90a4-33e3-11e6-924f-d9ba2e7d263f.PNG)

**Comment by zinks-** [comment]
If this helps, [it's actually a Unix timestamp](https://duckduckgo.com/?q=epoch+1466092386&t=canonical&ia=answer), Probably the time of deletion.

**Comment by zinks-** [comment]
Actually the '.dxxxxxxxx' suffixes appear for me as soon as I try to sort the list, even by "Name". With each subsequent sort, the suffix gets appended again and  again.
This prevents restoring the files too, as the name has changed and cannot be found: `Couldn't restore welcome.txt.d1466109156.d1466109156`

You need to reload the page (thus getting the clean names again) to be able to restore files.

So this is a little bit more serious than it seemed at first

**Comment by williambargent** [comment]
Oh yes, I haven't noticed that and yes I have just converted the timestamp and it was the time of deletion,

**Comment by MorrisJobke** [comment]
cc @blizzz @schiessle

**Comment by MorrisJobke** [comment]
I can't reproduce this with a current 11. Please recheck with a new version.
