### ISSUE TITLE
Implement OpenID Connect provider discovery/metadata

### ISSUE THREAD

**Issue by loxK** [nextcloud/server#13902]
While trying to setup Apache [mod_auth_openidc](https://github.com/zmartzone/mod_auth_openidc) I noticed that Nextcloud isn't exposing an [OpenID Connect Discovery](https://openid.net/specs/openid-connect-discovery-1_0.html) URL.

Examples:
- https://gitlab.com/.well-known/openid-configuration
- https://accounts.google.com/.well-known/openid-configuration

**Comment by zandbelt** [comment]
FWIW: you should be able to configure mod_auth_openidc without an OpenID Connect Discovery URL, nevertheless having one is better.

**Comment by loxK** [comment]
@zandbelt is there an example somewhere ?

**Comment by loxK** [comment]
For those looking at it [Nextcloud doesn't (yet?) support](https://github.com/nextcloud/server/issues/5955) [Openid Connect](https://openid.net/connect/) so the mod_auth_openidc Apache module **won't** work with it.

**Comment by demolitions** [comment]
I have the same issue in trying to use NextCloud as an authentication provider in Gitea, the only thing missing is the discovery URL, is there some workaround, or can I use something other as an authentication provider for both applications?

**Comment by TomG736** [comment]
Has any progress been made on this? @demolitions what did you end up using?

**Comment by demolitions** [comment]
@TomG736 I didn't use anything, I'm keeping separate users for all services, I'm currently trying to find an external authentication source to deploy that can be used with all our services (by now I have 5 different services with separate auth systems), but by now the only source accepted by all of them appears to be LDAP.

**Comment by szaimen** [comment]
Hi, please see https://github.com/nextcloud/user_oidc for this feature. Thanks! :)

**Comment by loxK** [comment]
@szaimen it is not about being able to connect to on an oidc provider but to have nexcloud act as a provider.
