### ISSUE TITLE
Creating event in shared calendar spawns event in every calendar of invited users

### ISSUE THREAD

**Issue by fdellwing** [nextcloud/server#13919]
### Steps to reproduce
1. Have a calendar shared with multiple persons you can edit
2. Invite some people that have an own account in your nextcloud instance
3. Create the event

### Expected behaviour
The event gets created in the shared calendar and every invited person gets a mail

### Actual behaviour
The event gets created in the shared calendar and in every invited persons calendar and every invited person gets a mail

### Server configuration

**Operating system**: Ubuntu Server 18.04.1

**Web server:** apache2 2.4.29

**Database:** mariadb 10.1.34

**PHP version:** 7.2.10

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** .tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- nextcloud.log

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [nextcloud.log] => Array
                        (
                            [expected] => 
                            [current] => af55870c46a69f2648fce26505de80dfbd2a9a38ab7e9c5e8a21f5fdf09968d1def6ef824865a7a7208bc8b4e4fa4e45939ebfbc3f650c35266613a4b2de1311
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.2
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "owncloud",
        "logfile": "nextcloud.log",
        "loglevel": 3,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "csrf.optout": [
            "\/Thunderbird.*Lightning\/"
        ],
        "auth.bruteforce.protection.enabled": false,
        "theme": "",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Thunderbird 60.4.0

**Operating system:** Ubuntu Desktop 14.04.5

### Logs
no related logs

**Comment by fdellwing** [comment]
Any feedback on this topic? I would change this myself, if I had a clue where this happens at all.

**Comment by georgehrke** [comment]
> The event gets created in the shared calendar and in every invited persons calendar and every invited person gets a mail

This is the expected behaviour.
Please elaborate why you think this behaviour is bad

**Comment by fdellwing** [comment]
Ok, lets explain my issue with this some more:

(I'll cut the number of persons in this example to 3, there are more affected in our company)

We have 4 calendars for the 3 people: One team calendar that everyone can see and edit and one personal calendar for each person that everyone can see.

The personal calendars are mostly for semi- or non-workrelated events, so that others know the person is busy. Events like meetings and customer presentations are added to the team calendar and every person that should attend is invited. And there lies the crux of this:

Person A adds an event to the team calendar and invites Person B and Person C. NC now autocreates an event in Person B' and Person C' calendar for the very same event. This makes no sense at all in a shared calendar enviroment.

So my points are:

1. If the person that creates an event is not the owner of the calendar, do not autocreate events in invited persons calendars.
2. If an event already exists in a calendar I can edit, do not autocreate the same event for me if I'm invited.
3. Make all of this optional (default false), so the current state does not change for people liking the current behaviour.

If someone really wants to add the event to his own calendar he still CAN do this with the event attached to the invitation mail.

**Comment by skjnldsv** [comment]
Still happening I guess?

**Comment by georgehrke** [comment]
I still disagree about the expected behavior, also because we just follow the RFC here.

However, I agree that seeing the same event multiple times from different calendars is annoying.
That has to be fixed in the calendar app though: https://github.com/nextcloud/calendar/issues/1329
