### ISSUE TITLE
Login Page Social Login Buttons are not centered

### ISSUE THREAD

**Issue by DominikWA** [nextcloud/server#13910]
Since Nextcloud 15 (still in 15.0.2) the Social Login Buttons are not centered at the Nextcloud login page. In Nextcloud 14 they were still centered. That does not look very nice.

![tmp](https://user-images.githubusercontent.com/27404965/51971991-ca4a7c80-247a-11e9-8c78-116dbd09f146.PNG)

**Comment by violoncelloCH** [comment]
this is an issue with the app social login...
please report it to the corresponding repo at https://github.com/zorn-v/nextcloud-social-login

**Comment by iPaat** [comment]
Don't get me wrong but, writing this is easy but not right!

With a deeper look into the plugin you could see that it does not use its own styles related to the buttons: 
https://github.com/zorn-v/nextcloud-social-login/tree/master/css

The styles used here are located in this repository:
e.g.: https://github.com/nextcloud/server/blob/master/core/css/guest.css#L497-L514

That's why I'm reopening this issue.

**Comment by Stevo99** [comment]
can I work on this?

**Comment by violoncelloCH** [comment]
@Stevo99 sure!

**Comment by Stevo99** [comment]
actually Im not sure I can work on this.  I was unaware that you need linux and a good understanding of PHP.  It seems really complicated to get the development server up and running on my local machine.  I feel like I could fix it if I could just deal with the CSS.  let me know if I'm mistaken.  Thanks

**Comment by violoncelloCH** [comment]
@Stevo99 you don't necessarily need a full developer setup for this css task... if you don't mind, you can just try your changes in a browser or you can edit the respective css file on a live/production installation of nextcloud...
what OS are you running? What you need for Nextcloud to run (if you want a dev setup) is a webserver (apache/nginx) with PHP... For a task like this which only touches css (and/or js) you also don't need any PHP experience at all... :) If you want to setup a dev environment, I can recommend you to look into https://github.com/jancborchardt/nextcloud-scripts or if you're familiar with docker(-compose) https://github.com/juliushaertl/nextcloud-docker-dev
if you have further questions, don't hesitate to ask :)

**Comment by Stevo99** [comment]
@violoncelloCH ok cool.  I was hoping I could work on it like that.  Im running <code>Windows10</code> so I would need to download apache and/or nginx.  Maybe Ill start looking into that setup so I can maybe help on other issues.  For now I will work on centering the **social login button** in login page.  Thanks for your info!

**Comment by violoncelloCH** [comment]
@Stevo99 cool! let me know if you need any further help :) thanks for looking into this!

**Comment by Stevo99** [comment]
hey can you maybe point me in the right direction of finding the area of the website where the `Login` section is.  I was looking all over yesterday but can't seem to find where the problem is.

**Comment by Stevo99** [comment]
it seems like I might have to download something from the website to have access to the login page? not really sure.

**Comment by violoncelloCH** [comment]
> The styles used here are located in this repository:
   e.g.: https://github.com/nextcloud/server/blob/master/core/css/guest.css#L497-L514

those should be the file and the responsible lines...
the file should be loaded something like `nextcloud.example.com/core/css/guest.css?v=614bcb4a-36` by the browser...



> it seems like I might have to download something from the website to have access to the login page? not really sure.

what do you mean with that? don't you have a nextcloud running somewhere? if that's easier for you, you can experiment with an instant trial from https://demo.nextcloud.com/ :)

**Comment by SchauerChristopher** [comment]
I cant reproduce this issue anymore. Either i installed the wrong plugin or the plugin has changed in the meanwhile? I can't even find the string "login with" in the current plugin version.
![Screenshot from 2019-07-04 16-48-40](https://user-images.githubusercontent.com/1949369/60674988-a94be480-9e7b-11e9-957a-8ef49f8a2cb1.png)

**Comment by violoncelloCH** [comment]
looks like this is fixed from the side of the app :)

**Comment by dfduarte78** [comment]
Hello, i have a similar issue on a fresh nextcloud 18 install, but it is way worse than OPs screenshot.
I changed core/css/guest.css #alternative-logins margin to 30px auto 20px and it fixed it for me.
