### ISSUE TITLE
Cronjob for file scan? [DOUBT]

### ISSUE THREAD

**Issue by DataDrug** [nextcloud/server#13925]
Hello,

I have nextcloud running on Ubuntu 16.04 and I have some FTP servers sending some data directly into the the nextcloud folders, however, only after running

`sudo -u www-data php occ files:scan --all`

I get to see the files on both desktop and webclients.

Could anyone kindly point me the required cronjob setup or any alternative to make nextcloud recognize / scan for new files every 15 minutes?

I've tried adding a cronjob where I had this command on a .sh file, making it executable, but even so nothing happened. Perhaps there is another way I am missing?

Thank you so much

**Comment by AndrewwHummer** [comment]
you need to run occ in the right directory, respectively use the right path to the occ script.
in my case this would be
`*/15 * * * * sudo -u www-data php /var/www/nextcloud/occ files:scan --all`

the problem you might get is that the user executing the cronjob needs access rights to the directory, and as far as i know `sudo -u` is not possible with the root account.

**Comment by DataDrug** [comment]
> you need to run occ in the right directory, respectively use the right path to the occ script.
> in my case this would be
> `*/15 * * * * sudo -u www-data php /var/www/nextcloud/occ files:scan --all`
> 
> the problem you might get is that the user executing the cronjob needs access rights to the directory, and as far as i know `sudo -u` is not possible with the root account.

I'll try a few things and report back.

I can run the command with root account manually, I'll try with the cronjob now.

**Comment by DataDrug** [comment]
It doesn't work.

Isn't there any other way this out?

**Comment by AndrewwHummer** [comment]
Well, check the permissions of the new files.
You could and probably should do something like this:
`*/15 * * * * chown -R www-data:www-data /var/www/html/nextcloud && sudo -u www-data php /var/www/nextcloud/occ files:scan --all`

**Comment by skjnldsv** [comment]
Hello, any news?
This is not really a location for help, I would rather have questions like this on the forum :)

Thus, I'm closing this one. If running the command manually works (as it's supposed to), then this is an issue with your cron setup. I'll suggest you check your OS manual then :wink:
