### ISSUE TITLE
Default client behaviour for individual folders to not sync

### ISSUE THREAD

**Issue by Omnimercador** [nextcloud/server#13926]
**Is your feature request related to a problem? Please describe.**
no.

**Describe the solution you'd like**
Currently, where a user uses a client to sync the root folder of his Nextcloud setup, any folders shared with that user will automatically sync to that user's machine via the client. 

As the person sharing the folder, I'd like to be able to provide access to that folder to that user, and allow the user to sync the folder to his machine via a client, on an opt-in basis. In other words: folders that have been shared with a user appear in that user's client with an unchecked box, and will only sync once the user checks the box.

Specific example: I share a large, 10gb images and artwork folder with a user. The folder should be available to the recipient to sync via client, but not by synced automatically. 

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by MorrisJobke** [comment]
Thanks for the request. That is nothing we plan to include in our core system. Feel free to write an app that does this, but in our opinion the recipient should be in charge of what is synced and what not and not the sender.
