### ISSUE TITLE
Group admin settings

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#13936]
**Is your feature request related to a problem? Please describe.**
Nextcloud has support for *group admins*, which are administrators for a group of users. They differ from the system admins as in that they don't get to see any of the admin pages. Hence they also don't have access to admin settings.

For features like https://github.com/ChristophWurst/twofactor_admin/issues/16 I would like to have this ability for both admins and groups admins. However, I don't know where such settings should be placed.

**Describe the solution you'd like**
I would like to have consent on where we put such settings. Should we add a third type of settings in addition to the personal and admin settings?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

cc @nextcloud/designers for input

**Comment by juliushaertl** [comment]
I think we should just put them in the regular settings list, so group admins will then also see the second section with just the group admin settings in there. @ChristophWurst I guess the user is group admin of multiple groups, the selection of which group is affected will happen in the individual settings page like the twofactor_admin one?

**Comment by ChristophWurst** [comment]
With "regular settings" you are referring to the personal ones, right?

twofactor_admin does not have any (personal) settings right now. But of course it would be possible to show the group admin settings there. But since the settings will be visible for admins as well, it's a bit inconsistent – where would those see the settings to administrate other users? On the personal settings like group admins or on the "real" admin pages?
Also, the personal settings are literally labeled as such, hence it's not really logical that admin settings are found there.

**Comment by rullzer** [comment]
I guess it would be better to just have 'limited' admin settings.

Like for a subadmin we would show the admin settings for all settings the implement the ISubAdminSettings interface?

**Comment by ChristophWurst** [comment]
Yeah, something like that could work!

**Comment by jancborchardt** [comment]
Alternative solution, in case it’s easier: Just show a "Group admin" section as last entry of the personal settings.

Yes, it’s weird that it’s under the "Personal" header. Solution: Hide the "Personal" header for non-admin users because it’s not really useful: https://github.com/nextcloud/server/pull/14666

**Comment by skjnldsv** [comment]
Yes, we need to be extra careful here.
Especially with the big argument on the group admin/subadmin thingy.
Let's not add one more weird thing that confuses the users even more on what a group admin is :pray:

**Comment by juliushaertl** [comment]
Done with https://github.com/nextcloud/server/pull/15679
