### ISSUE TITLE
Clicking on `< Shared` in the details of the file list does not open the share tab in the sidebar anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#13939]
Instead the first tab (activity) is opened.

If you manually select the share tab and then switch to another file the tab is kept.

Also selecting the versions tab does not highlight it as active anymore.

cc @skjnldsv @juliushaertl

**Comment by juliushaertl** [comment]
@nickvergessen I cannot reproduce that. Are you on latest master?

**Comment by juliushaertl** [comment]
Ah, probably related to https://github.com/nextcloud/server/pull/13870 ? cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Could you test https://github.com/nextcloud/server/pull/13935? That should fix this issue.

**Comment by nickvergessen** [comment]
Yes, thanks
