### ISSUE TITLE
Sharing a file/folder fails with "Unable to create a link share"

### ISSUE THREAD

**Issue by realies** [nextcloud/server#13933]
### Steps to reproduce
1. Click share on a file or folder
2. Get popup message "Unable to create a link share"

### Expected behaviour
Get link

### Actual behaviour
```
Request URL: https://my.domain/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
Request Method: POST
Status Code: 404 Not Found
```

### Server configuration

**Operating system**: Linux

**Web server:** https://hub.docker.com/r/linuxserver/nextcloud/

**Database:** PostgreSQL

**PHP version:** https://hub.docker.com/r/linuxserver/nextcloud/

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC 14, issue did not occur after update

**Where did you install Nextcloud from:** https://hub.docker.com/r/linuxserver/nextcloud/

**Signing status:**  `No errors have been found.`

**List of activated apps:**
```
Accessibility	1.1.0	Official	
Activity	2.8.2	Official	
Camera RAW Previews	0.6.3		
Checksum	0.4.2		
Collaborative tags	1.5.0	Official	
Comments	1.5.0	Official	
Custom CSS	1.2.0		
Deleted files	1.5.0	Official	
External storage support	1.6.0	Official	
File sharing	1.7.0	Official	
Gallery	18.2.0	Official	
Log Reader	2.0.0	Official	
Music	0.9.3		
Nextcloud announcements	1.4.0	Official	
Notifications	2.3.0	Official	
Password policy	1.5.0	Official	
PDF viewer	1.4.0	Official	
Preview Generator	2.0.0		
Share by mail	1.5.0	Official	
Text editor	2.7.0	Official	
Theming	1.6.0	Official	
Update notification	1.5.0	Official	
Versions	1.8.0	Official	
Video player	1.4.0	Official	
```

**Comment by realies** [comment]
Running this fixed the issue:

```
occ db:add-missing-indices
occ db:convert-filecache-bigint
```

**Comment by tbuytaer** [comment]
I had this same problem after following [these steps to enable 4-byte support](https://docs.nextcloud.com/server/15/admin_manual/configuration_database/mysql_4byte_support.html)

Running
```
occ db:add-missing-indices
occ db:convert-filecache-bigint
```
didn't fix it until I also restarted the MySQL server.
