### ISSUE TITLE
Need API for Share by Mail app

### ISSUE THREAD

**Issue by xeoslaenor** [nextcloud/server#13948]
Hello,

I cannot find how to access ShareByMail app through API
It would be great to have such API as I am working on a project to create shares for differents clients based on their subscriptions on our website

Thanks

**Comment by skjnldsv** [comment]
@ChristophWurst

**Comment by ChristophWurst** [comment]
> I am working on a project to create shares for differents clients based on their subscriptions on our website

This sounds like an enterprise use case. Do you have an active [Nextcloud enterprise subscription](https://nextcloud.com/enterprise/)?

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
