### ISSUE TITLE
allow to enable files versioning on a per folder basis

### ISSUE THREAD

**Issue by geokh** [nextcloud/server#13942]
Dear support,

Is there a way to add the ability o enable file version on a specific folder ( Group Folders). so it can be more controllable.

**Comment by violoncelloCH** [comment]
file versioning support was added to groupfolders 2.0.0 (2.0.2 should be available for NC 14 and 15)

**Comment by geokh** [comment]
Yes notcied but for me I work in a big company with alot of employees and if IAM going to enable file version to everyone, imagine the storage size that I will need. So that's why a good suggestion is to make it on specific files and stop it on others

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer @karlitschek

**Comment by geokh** [comment]
No wait it's not like that , I want to be able to do that . I don't want to enable file version on all Folders. I want to select which files to have the file version enabled and to disable it on others

**Comment by karlitschek** [comment]
@geokh Why not have it for all folders? Are you running out of disk space? I agree with @rullzer that this is strange setting to have.

**Comment by MorrisJobke** [comment]
> When we are speaking about being big shares 1TB that will be used as a shared storage and it's already backed up with 3rd party application. I don't want it to have file version. I want people to work on it without caring about the change they do. So a nice feature is to disable this feature for this kind of share and enable for serious ones that I need to see the changes

So what you actually want is to have versions per storage and not per folder, right? I fully get the use case behind this: saving space from an admin perspective. On the other hand it is super confusing for users why some of their files/folders have versions and some not. This is also to be taken into account.

**Comment by geokh** [comment]
Ok let me tell you my case: I have created a Group Folders shares, and I only want to enable versions on this share not all the other shares and folders.

**Comment by geokh** [comment]
So do we Expect this feature in future updates?

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out. As this discussed shows this needs extensive planning ahead to also count in complexity that will need to be added to the filesystem layer as well as a proper concept of how the user experience for this feature should be. It really is key that the feature is implemented in a way that neither users nor admins are confused about the behavior.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
