### ISSUE TITLE
User management: search in more attributed (displayname, email)

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#13951]
It would be good if search/filter would work on the user management page. To quickly locate users.

CC: @skjnldsv

**Comment by skjnldsv** [comment]
Comes from php!
https://github.com/nextcloud/server/blob/f5137fef6c79509473ddbd0bc9ac1e4e9c6d840d/apps/provisioning_api/lib/Controller/UsersController.php#L127

**Comment by skjnldsv** [comment]
Hum, we can already search by email/displayName/uid https://github.com/nextcloud/server/blob/145eee91fe611a9ae59c5e6d9a8d06104112c1a5/lib/private/User/Database.php#L274-L278

**Comment by MorrisJobke** [comment]
Fixing search in groups could be solved in #21138
