### ISSUE TITLE
Update from 14.04 to 14.06 fails at step 5

### ISSUE THREAD

**Issue by linus-nc** [nextcloud/server#13959]
### Steps to reproduce
1.Go to adming settings (as well on command line)
2. Start Update
3. fail

### Expected behaviour
Nextcoiud should be updated

### Actual behaviour
Update stops with error:

Trying to update via web-updater to v. 14.0.6 gives the error: 
“Verifying integrity 
Parsing response failed. Step 5 is currently in process. Please reload this page later.”

When trying again, a white page is shown telling: “Step 5 is currently in process. Please reload this page later.”

When using updater on command line the error is: “[ ] Verify integrity …Ungültiger Maschinenbefehl” and after trying again also: “Step 5 is currently in process. Please call this command later.”

### Server configuration

**Operating system**: Raspbian GNU/Linux 9 (stretch)

**Web server:**Apache/2.4.25

**Database:** Mysql

**PHP version:** PHP 7.0.33-0+deb9u1 (cli)

**Nextcloud version:** 14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:upgraded

**Where did you install Nextcloud from:** github

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.2.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - contacts: 2.1.7
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - gpxpod: 2.3.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - news: 13.0.3
  - nextcloud_announcements: 1.3.0
  - notes: 2.5.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - ocsms: 2.0.2
  - onlyoffice: 2.0.4
  - password_policy: 1.4.0
  - phonetrack: 0.3.8
  - provisioning_api: 1.4.0
  - richdocuments: 3.0.5
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - spreed: 4.0.1
  - support: 1.0.0
  - systemtags: 1.4.0
  - tasks: 0.9.8
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - external
  - files_external
  - survey_client
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.2.***",
            "*****"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/192.168.2.***",
        "dbtype": "mysql",
        "version": "14.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "php",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/media\/stick\/nextcloud\/nextcloud.log",
        "loglevel": 2,
        "maintenance": false,
        "updater.release.channel": "stable",
        "theme": ""
    }
}


```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes/no: no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... no

### Client configuration
**Browser:** Firefox 64.0 64 bit

**Operating system:** Ubuntu 16.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Jan 29 20:36:22.669041 2019] [core:notice] [pid 818] AH00052: child pid 857 exit signal Illegal instruction (4)
[Tue Jan 29 20:55:57.642970 2019] [mpm_prefork:notice] [pid 818] AH00169: caught SIGTERM, shutting down
[Tue Jan 29 20:56:35.456551 2019] [mpm_prefork:notice] [pid 818] AH00163: Apache/2.4.25 (Raspbian) OpenSSL/1.0.2q configur$
[Tue Jan 29 20:56:35.462378 2019] [core:notice] [pid 818] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
|Warning|l10n|Failed to load /var/www/nextcloud/lib/l10n/sr.json - json error code: 4|2019-01-29T21:14:41+0100|
|---|---|---|---|
|Warning|l10n|Failed to load /var/www/nextcloud/lib/l10n/it.json - json error code: 4|2019-01-29T21:14:41+0100|
|Warning|l10n|Failed to load /var/www/nextcloud/lib/l10n/sr.json - json error code: 4|2019-01-29T20:30:40+0100|
|Warning|l10n|Failed to load /var/www/nextcloud/lib/l10n/it.json - json error code: 4|2019-01-29T20:30:40+0100
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by GAS85** [comment]
It is related to #13484 update could meet timeout at any point and will not use `..nextcloud/data/updater-YOURID/.step` to validate current status when it if finished.
