### ISSUE TITLE
Favorites quick access list is not updated when a favorited file or folder is removed

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#13963]
### Steps to reproduce
- Open the Files app
- Create a new folder
- Favorite the folder
- Delete the folder

### Expected behaviour
The folder is removed from the favorites quick access list in the navigation bar.

### Actual behaviour
The folder is still shown in the favorites quick access list in the navigation bar. If the Files app is reloaded the folder is no longer shown in the favorites quick access list.

@nextcloud/javascript

**Comment by juliushaertl** [comment]
cc @newhinton

**Comment by newhinton** [comment]
Interestingly this is the exact opposite to #11083 :D
I will take a look at it tomorrow if it can wait ;)

**Comment by skjnldsv** [comment]
Bump! :grin:

**Comment by newhinton** [comment]
I have not forgotten about this, i am currently fixing my dev instances, then i'll fix this ;)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
