### ISSUE TITLE
Documentation (user and admin) missing

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#13967]
### Steps to reproduce
1. go to "Help"
2. click on "User Documentation" (also applies to "Administrator documentation")

### Expected behaviour
Documentation is shown in iFrame

### Actual behaviour
Text appears:

> Here goes the user documentation In the meantime go to nextcloud.com/support/

### Server configuration

**Nextcloud version:** 
15.0.2

**Comment by juliushaertl** [comment]
@MorrisJobke Maybe an issue with the build script?

**Comment by wiswedel** [comment]
It acutally seems to be hard-coded that way:  server/core/doc/admin/index.html

**Comment by MorrisJobke** [comment]
It's in all releases after end of November.

**Comment by skjnldsv** [comment]
@MorrisJobke https://sphinx-rtd-theme.readthedocs.io/en/latest/configuring.html?highlight=display_version
This is supposed to be a valid property though.

> display_version Bool. With this disabled, the version number isn’t shown at the top of the sidebar.

I guess this doesn't work. iirc we wanted to remove the ![capture d ecran_2019-02-01_12-06-39](https://user-images.githubusercontent.com/14975046/52119600-d9b3fc00-2619-11e9-8b49-7d8c35ae1e12.png) But I guess we finally went with it :thinking:

**Comment by MorrisJobke** [comment]
> * 
> * click on "User Documentation"

This is done already. Now looking into the admin manual:

```
Could not import extension sphinxcontrib.phpdomain (exception: cannot import name Directive)
```

**Comment by MorrisJobke** [comment]
Found the issue - the phpdomain that is packaged in Ubuntu 16.04 is not suited. Installed via pip solved the issue.

The next releases of Nextcloud will contain the docs again (13.0.11, 14.0.7 and 15.0.3)

**Comment by pierreozoux** [comment]
@MorrisJobke I really think the documentation there is the way to go :)
1st thanks for fixing it ;)
2nd, how is your build pipeline working, I'm trying to figure out, but can't find it, I'd like to add i18n to this logic :)

Thanks for your help!
