### ISSUE TITLE
Selected files metadata does not include the tags of files selected using the "Select all" checkbox

### ISSUE THREAD

**Issue by danxuliu** [nextcloud/server#13964]
The `FileList` prototype does not provide support for tags; this is added by replacing certain functions of the `FileList` with an inherited version that extends the default behaviour. For example, [`elementToFile`](https://github.com/nextcloud/server/blob/5d888984a0db8dfc04be8b398e75f04f6894fa32/apps/files/js/tagsplugin.js#L250-L251).

`elementToFile` is used when a file is selected in the file list, so [the object that stores the metadata of the selected files includes also the tags](https://github.com/nextcloud/server/blob/53fd4997cc4abfbff35276e7b02be1eeca068a41/apps/files/js/filelist.js#L721-L724). However, when the _Select all_ checkbox is clicked [the metadata is gotten directly from the `files` object](https://github.com/nextcloud/server/blob/53fd4997cc4abfbff35276e7b02be1eeca068a41/apps/files/js/filelist.js#L904-L909), which does not seem to contain the tags.

Due to this [it is not possible to implement favouriting by dropping several files at once](https://github.com/nextcloud/server/pull/12917#issuecomment-459569210); currently [dropping several files is handled through the draggable helper in other events](https://github.com/nextcloud/server/blob/6bcc77a7c6575bffd800b5a1d381966c59c1c04a/apps/files/js/navigation.js#L95) due to not being able to get the `FileList` object from the handler, but as [the metadata of the selected files passed to the draggable helper](https://github.com/nextcloud/server/blob/f99ce0d546c8332bb46807eed21fcdf7d5d0ab71/apps/files/js/files.js#L379) would not contain the tags it would not be possible to differentiate between files already favourited or not, which is needed to trigger the action only on those not favourited yet (otherwise they would be removed from favourites).

This may apply to to other plugins too besides tags (although I have not checked).

@nextcloud/javascript

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
