### ISSUE TITLE
Show supported NC version in apps manager

### ISSUE THREAD

**Issue by tomastd** [nextcloud/server#13965]
Hi, it would be helpfull to have the info of the latest supported nextcloud version in the apps view ( https://nextcloud.xxx/index.php/settings/apps ).

It's a must info to have before deciding to upgrade a site in production. To know witch functionalities are going to be missed if upgrading. That info is already available in the store.

 Draw.io                                    0.9.2     Nextcloud 15 All versions
 Reader (ebook reader)           1.2.3      Nextcloud 13 All versions   

That's just a suggestion, but I had some issues with it when upgraded to 15.0.2.

Thank you very much

**Comment by juliushaertl** [comment]
We only show app releases that are supported by the current version, since the apps are filtered by the app store depending on the Nextcloud version: For example: https://apps.nextcloud.com/api/v1/platform/15.0.0/apps.json

CAn you give some more details what the issues were, you had with those apps?

**Comment by juliushaertl** [comment]
This is actually something that has been implemented with 14:
https://github.com/nextcloud/server/pull/8579

If you try to update to a new version, Nextcloud will show the apps that are not compatible with the new version anymore.

**Comment by tomastd** [comment]
Please, can you show me where is it. 
I just upgraded to 15.0.0.4 and didn't read any message regarding the apps.
I did the web upgrade.
Thank you.
