### ISSUE TITLE
Federation settings visible even when federation app is disabled

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#13968]
### Steps to reproduce
1. Go to "Apps"
2. Search for "Federation"
3. Disable "Federation" app
4. Go to Settings > Administration > Sharing
4a. Go to Settings > Personal > Sharing

### Expected behaviour
Settings for "Federated Cloud Sharing" are gone

### Actual behaviour
Settings for "Federated Cloud Sharing" are visible

**Nextcloud version:**

15.0.2

**Comment by juliushaertl** [comment]
Seems the federation app cannot be disabled, just the federatedfilesharing app. @rullzer Are you aware of any reason for that?

**Comment by rullzer** [comment]
@schiessle should know why :wink:

**Comment by skjnldsv** [comment]
PIng

**Comment by juliushaertl** [comment]
So I assume this is due to the fact that there could be other federated sharing providers than files, like calendar for example. In that case it works as expected.

**Comment by skjnldsv** [comment]
So closing?
