### ISSUE TITLE
E-Mail share recipient not identified in Activity stream on upload into folder

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#13973]
### Steps to reproduce
1. Share a folder with some files with an e-mail address (and give them editing rights)
2. Open the link in the invitation e-mail
3. Download one of the files
4. Upload a file into the folder
5. Create a folder within the public folder

### Expected behaviour
Sharee's activity stream identifies the share-recipient's download- and upload actions by their e-mail address.

### Actual behaviour
Only download actions are logged with the recepient's e-mail address ("mail@example.com downloaded file.xyz").
Upload actions are logged as "file.xyz was created in a public folder".

The same action performed with a named registered user fully identifies their actions in both directions as expected above.

**Nextcloud version:**

15.0.2

**Comment by rullzer** [comment]
@nickvergessen

**Comment by nickvergessen** [comment]
The difference is that the download event is done via the ShareController, so the information about the share is available at the point the activity is created. For file creations this is not the case. There is no special event triggered and so we only get the normal "file written" event. ¯\\\_(ツ)\_/¯

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
