### ISSUE TITLE
Personal Two-Factor Authentication settings visible even if no 2FA activated

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#13971]
### Steps to reproduce
1. Disable all 2FA apps (or never have activated one ever before)
2. Go to Settings > Personal > Security

### Expected behaviour
No settings for Two-Factor Authentication visible

### Actual behaviour
Two-Factor Authentication settings for Backup code generation visible

**Nextcloud version:**

15.0.2

**Comment by rullzer** [comment]
Well yes. You can still generate backups codes then.But maybe we could hide it... if there really is no other app available...

@ChristophWurst ?

**Comment by ChristophWurst** [comment]
Sure, we could hide it in that case!

**Comment by MinIsMin** [comment]
Then it should also hide the reminder notification about creating backup codes

**Comment by Keridos** [comment]
This seems to have deeper roots: https://help.nextcloud.com/t/nextcloud-19-canot-properly-disable-2fa/87968

**Comment by ChristophWurst** [comment]
PR is at https://github.com/nextcloud/server/pull/25273
