### ISSUE TITLE
Question about the LDAP App: How are users created?

### ISSUE THREAD

**Issue by iPaat** [nextcloud/server#13974]
Hello community,

I wonder how exactly a user is created if he has never logged in before and the LDAP app is activated?

It seems to me that the user is created automatically. 
What is the CallStack like? I have already found the LoginController. But it didn't help. At which point does the LDAP app it's work?

I would like to reproduce this in the source code.

__The reason for my question is the following:__  
I am using a social login plugin. After the user has successfully logged in using this plugin, the link to his LDAP account is missing. I would like to do this manually.

Thank you for your help!

Best,
Patrick

**Comment by MorrisJobke** [comment]
There is a background job that scans the LDAP server at a rate of 100 users per hour AFAIK. Also the LDAP server is queried on every search (sharing dialog, user management, etc) and then the fetched users are created.

cc @blizzz

**Comment by blizzz** [comment]
two fold:

* on demand, if they are not known yet but appear within a search operation (e.g. search dialogue, browsing users page)
* with the background job as @MorrisJobke described, however the chunk size depends on the settings and the interval depends on the amount of users available (once) known. It adjust to refresh any user one to two times a day, but there are lower and upper boundaries.
* what we do with other apps (e.g. saml) is to perform search when a user is needed and unknown. The LDAP configuration (user search attributes) have to fit depending on what sort of input you receive (a userid? a casual name? email? something else?)
