### ISSUE TITLE
Email Template name errors

### ISSUE THREAD

**Issue by worldoptimizer** [nextcloud/server#13975]
When nextcloud (15.0.2) sends emails it has some missing whitespaces and quotes to many.
See screenshot. Custom Logo and colors set and using SMTP.

<img width="401" alt="20190201-fe6ip" src="https://user-images.githubusercontent.com/1752114/52118997-15e65d00-2618-11e9-988a-3ca250661370.png">

**Comment by kesselb** [comment]
I recall that something like that should be fixed by a swiftmailer (a library used by Nextcloud to send emails) update. Do you still see this issue?
