### ISSUE TITLE
Emoticon follows the logo from Theming settings

### ISSUE THREAD

**Issue by crickxson** [nextcloud/server#13984]
More and more Nextcloud users are interacting with multiple instances of Nextcloud (one for work, one personnal, one for an association or school...)
Currently, all those tabs have the same emoticon. 
If the emoticon follows the logo from Theming settings, it will be helpful to sort which tab is what server.
It could be the current global nextcloud logo, but follows the color defined in Theming.

**Comment by violoncelloCH** [comment]
for me the colour of the logo/(fav)icons adapt to the theming colour...

**Comment by angristan** [comment]
On Debian/Ubuntu, install the `libmagickcore-6.q16-3-extra` package to get dynamic favicons.

**Comment by crickxson** [comment]
Super solution! Will ask to my sys admin. Thanks!
