### ISSUE TITLE
Https fails on redirect ( ex: after login )

### ISSUE THREAD

**Issue by tomtom30** [nextcloud/server#13985]
Hi
I'am on docker with nextcloud and traefik.
I was running nextcloud 13 without any problem but after upgrade to nextcloud 15 I have a little problem
with https.
When I log in **https://xxxx.fr:4444** , it redirect after grant to http://**xxxx.fr:4444** . I need adding "https://" manually to make it correct.
All redirections inside nextcloud are affected by this bug

**Comment by danielkesselberg** [comment]
If you run nextcloud behind a reverse proxy please read https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html.

What you need to do:

- Add the ip addresss (IPv4 or IPv6) of your reverse proxy to your `config.php` as `trusted_proxy`. `HTTP_X_FORWARDED_PROTO` and `HTTP_X_FORWARDED_HOST` are trusted if your reverse proxy is passing them to nextcloud.

- Sometimes it's not possible to detect the right value. In this case you can always overwrite it and force nextcloud to use these. `'overwriteprotocol' => 'https'` would force https. `'overwritehost' => 'example.com'` to force your domain.

Please keep in mind: This is the issue tracker of Nextcloud, if you have any support question please check out https://nextcloud.com/support

**Comment by tomtom30** [comment]
Really thanks for your help. In fact nextcloud 15 need `'overwriteprotocol' => 'https'` added to config.php with reverse proxy.
sorry for the inconvenience I thinked that it was due to upgrade and it was a bug.
