### ISSUE TITLE
"Internal Server Error" When first time I access nextcloud

### ISSUE THREAD

**Issue by XiTongWu** [nextcloud/server#13983]
### Steps to reproduce
1.copy nextcloud to /var/www/html,then configue apache2
2.use firefox first time access the web site
3.the error happens

### Expected behaviour
Tell us what should happen
it should give me a web site to create an admin account for further config.
### Actual behaviour
Tell us what happens instead
It only print"Internal Server Error" on my screen
### Server configuration
apache2
**Operating system**:
Ubuntu18.04
**Web server:**

**Database:**
mariadb
**PHP version:**
php7.2
**Nextcloud version:** (see Nextcloud admin page)
nextcloud15.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
my own Vmware Workstation
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>none</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>I use the defalut config and even didn't have chance to change it.</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox
**Operating system:**
18.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
Back to apache2 dir, the error log said:   chmod( ) no such fie or dir at \\/var\\/www\\/html\\/nextcloud\\/lib\\/private\\/Log\\/File.php\\.
which I check a lot of times just in that dir.

**Comment by XiTongWu** [comment]
@eest9 thanks for your idea
I try your way to solve it,but when I try to change the floder's proprietary to www-data,the shell reply that there is no such user or user group.
I reference your method，vim the apche2's config file,change it user group to my root user(which own the nextcloud folder)...and it's okay.
 I am using Ubuntu18.04 LTS Desktop,maybe is desktop version user problem.
thanks about your help!

**Comment by ShaoboLiu** [comment]
> I could fix this bug in my installation by checking the permission of the nextcloud folder and changing them.
> 
> ```
> ls -la <nextcloud folder>
> sudo chown -R www-data:www-data <nextcloud folder>
> ```

Yes, I fixed the same issue on my computer using the command:
sudo chown -R www-data:www-data <nextcloud folder>

Thanks
