### ISSUE TITLE
(UI) Appmenu collapsing with enough space to show every app

### ISSUE THREAD

**Issue by Zirex4** [nextcloud/server#13997]
### Expected behaviour
Maybe show the apps if there is enough space to show them.

### Actual behaviour
Collapsing into '...More' way too quickly

### Client configuration
**Browser:** Firefox

**Operating system:** ArchLinux

Sorry for not posting more information/fixing this myself, I'm not the sysadmin and my knowledge is very limited as I write this.

![nextcloud-header-appmenu-collapsed](https://user-images.githubusercontent.com/9592009/52168278-1538ee00-2720-11e9-8330-c5e358b3dc64.png)
![nextcloud-header-appmenu-notcollapsed](https://user-images.githubusercontent.com/9592009/52168279-1538ee00-2720-11e9-95e1-dfd1ec7be536.png)

**Comment by skjnldsv** [comment]
Duplicate of #13079
