### ISSUE TITLE
hung cronjob and hung smbclient after killing it [issue with min version SMB2 or higher]

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/server#13992]
### Steps to reproduce
1. use a smbshare 
2. enable authentication
3. min SMB Version 2

### Expected behaviour

cron runs and quits when finished

### Actual behaviour
cron is stuck, high CPU Load, after killing the cron after 9 hr running smbclient uses 100% CPU

### Server configuration

**Operating system**: ubuntu 18.04

**Web server:** Apache 2.4

**Database:** MariaDB10 

**PHP version:** 7.1

**Nextcloud version:** (see Nextcloud admin page)
15.02
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
the image

```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - audioplayer: 2.6.0
  - bookmarks: 0.16.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.2
  - dav: 1.8.1
  - deck: 0.5.2
  - discoursesso: 0.9.15
  - dropit: 0.1.3
  - event_update_notification: 0.3.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.4
  - files_fulltextsearch_tesseract: 1.2.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - fulltextsearch: 1.2.4
  - fulltextsearch_elasticsearch: 1.2.3
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ocsms: 2.1.1
  - password_policy: 1.5.0
  - polls: 0.9.5
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - qownnotesapi: 18.11.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - richdocuments: 3.1.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.3.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - firstrunwizard
  - mood
  - onlyoffice
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": false,
        "blacklisted_files": [
            ".htaccess"
        ],
        "enable_previews": true,
        "preview_max_scale_factor": 10,
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "appstoreenabled": true,
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "7, auto",
        "allow_user_to_change_display_name": true,
        "overwrite.cli.url": "https:\/\/cloud.r-d-w.net",
        "htaccess.RewriteBase": "\/",
        "updatechecker": true,
        "log_type": "owncloud",
        "loglevel": "3",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "remember_login_cookie_lifetime": 1296000,
        "maintenance": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "version": "15.0.2.0",
        "trusted_domains": [

        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "theme": "",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "log_rotate_size": 104857600
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb webdav
**Are you using encryption:** yes/no
no
```

the cronjob hangs at:
```
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29376, si_uid=33, si_status=255, si_utime=0, si_stime=0} ---
close(5)                                = 0
wait4(29376, [{WIFEXITED(s) && WEXITSTATUS(s) == 255}], 0, NULL) = 29376
pipe2([5, 6], O_CLOEXEC)                = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f4e3ae21290) = 29380
close(6)                                = 0
fcntl(5, F_SETFD, 0)                    = 0
read(5, "", 8192)                       = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29380, si_uid=33, si_status=255, si_utime=0, si_stime=0} ---
close(5)                                = 0
wait4(29380, [{WIFEXITED(s) && WEXITSTATUS(s) == 255}], 0, NULL) = 29380
pipe2([5, 6], O_CLOEXEC)                = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f4e3ae21290) = 29384
close(6)                                = 0
fcntl(5, F_SETFD, 0)                    = 0
read(5, "", 8192)                       = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29384, si_uid=33, si_status=255, si_utime=0, si_stime=0} ---
close(5)                                = 0
wait4(29384, [{WIFEXITED(s) && WEXITSTATUS(s) == 255}], 0, NULL) = 29384
pipe2([5, 6], O_CLOEXEC)                = 0
clone(child_stack=NULL, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f4e3ae21290) = 29388
close(6)                                = 0
fcntl(5, F_SETFD, 0)                    = 0
read(5, "", 8192)                       = 0
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=29388, si_uid=33, si_status=255, si_utime=0, si_stime=0} ---
``` 

lsof has this open
```
php     326 www-data    0r  FIFO               0,12      0t0 36771772 pipe
php     326 www-data    1u   REG              252,1 55240070  6815819 /tmp/#6815819 (deleted)
php     326 www-data    2u   REG              252,1 55240070  6815819 /tmp/#6815819 (deleted)
php     326 www-data    3u  IPv4           36773698      0t0      TCP localhost:42700->localhost:mysql (ESTABLISHED)
php     326 www-data    4u  unix 0xffff8eafea6be800      0t0 36773699 type=STREAM
php     326 www-data    5r  FIFO               0,12      0t0 52523240 pipe
php     326 www-data    7w  FIFO               0,12      0t0 36773706 pipe
php     326 www-data    8r  FIFO               0,12      0t0 36773707 pipe
php     326 www-data   10r  FIFO               0,12      0t0 36773708 pipe
php     326 www-data   12u   REG              252,1       47  6819451 /tmp/phpYChuAx
php     326 www-data   15w  FIFO               0,12      0t0 36773709 pipe
php     326 www-data   16r  FIFO               0,12      0t0 36773710 pipe
```

strace on sambaclient is throwing that
```
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=14896584}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=15197285}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=15490355}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=15781792}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=16085348}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=16376475}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=16656084}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=16935681}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=17223856}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=17523770}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=17781201}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99999})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=18061299}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=18375899}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99999})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=18656964}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99999})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=18939414}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
clock_gettime(CLOCK_BOOTTIME, {tv_sec=142960, tv_nsec=19254529}) = 0
select(1, [0], NULL, [0], {tv_sec=0, tv_usec=100000}) = 1 (in [0], left {tv_sec=0, tv_usec=99998})
ioctl(0, FIONREAD, [0])                 = 0
^Cstrace: Process 342 detached
```

and lsof:
```
smbclient 342 www-data  mem    REG    252,1    26376   934351 /usr/lib/x86_64-linux-gnu/gconv/gconv-modules.cache
smbclient 342 www-data    0r  FIFO     0,12      0t0 36773706 pipe
smbclient 342 www-data    1w  FIFO     0,12      0t0 36773707 pipe
smbclient 342 www-data    2w  FIFO     0,12      0t0 36773708 pipe
smbclient 342 www-data    3u   REG    252,1       47  6819451 /tmp/phpYChuAx
smbclient 342 www-data    4r  FIFO     0,12      0t0 36773709 pipe
smbclient 342 www-data    5w  FIFO     0,12      0t0 36773710 pipe
smbclient 342 www-data    7u  IPv4 36775081      0t0      TCP <DOMAIN>:41580-><domain>:microsoft-ds (ESTABLISHED)
smbclient 342 www-data    8r   CHR      1,9      0t0       11 /dev/urandom
smbclient 342 www-data   12u   REG    252,1       47  6819451 /tmp/phpYChuAx
```

the full lines are:

```
www-data   341  0.0  0.0   4628   744 ?        S    Feb01   0:00 sh -c stdbuf -o0 /usr/bin/smbclient --authentication-file=/proc/self/fd/3 -W 'WORKGROUP' '//192.168.122.42/storage'
www-data   342  3.9  0.1 346280 12748 ?        R    Feb01  27:44 /usr/bin/smbclient --authentication-file=/proc/self/fd/3 -W WORKGROUP //192.168.122.42/storage

```

**Comment by cowai** [comment]
@devz3r0 I have the same problem. Are you on alpine linux?

**Comment by devz3r0** [comment]
no, ubuntu

**Comment by cowai** [comment]
is:open @devz3r0 Sorry did not read your full post. Are you using a docker image though?

**Comment by devz3r0** [comment]
not for nextcloud.

**Comment by kesselb** [comment]
We have some reports that https://github.com/eduardok/libsmbclient-php (smbclient bindings for php) improves the performance. This could work for you.

https://github.com/nextcloud/server/issues/6865
https://github.com/nextcloud/server/issues/12505

**Comment by devz3r0** [comment]
@kesselb thanks and how can I force nextcloud using that?

**Comment by kesselb** [comment]
If libsmbclient-php is installed and enabled its used by default.

**Comment by skjnldsv** [comment]
Yes, please use [php-smbclient](https://docs.nextcloud.com/server/19/admin_manual/configuration_files/external_storage/smb.html?highlight=smbclient#smb-cifs)
