### ISSUE TITLE
406 Not Acceptable to PUT at remote.php

### ISSUE THREAD

**Issue by ultradyran** [nextcloud/server#13994]
Just want to know if there’s a solution for this error yet?

Expected behaviour
File should be syncing automatically.

Actual behaviour
Some files were not synced.
ERROR: Server replied 406 Not Acceptable fail to PUT

Steps to reproduce
Sync
Server configuration
Operating system:
Windows

Web server:
BlueHost

Database:
not sure, default database

PHP version:
PHP 7

ownCloud version:
Nextcloud 14.0.6

Storage backend (external storage):

Client configuration
Client version:
ver 2.5.1 final (build 20181204)

Operating system:
Windows 10

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
5.11.1

Client package (From ownCloud or distro) (Linux only):
NEXTCLOUD

Installation path of client:
C:// default path

Logs
Server replied “406 Not Acceptable” to “PUT http://cloud.mydomain.com/remote.php/dav/uploads/myname/124723862/0000000”

**Comment by j-ed** [comment]
I would assume that you tried to sync an unacceptable file type to the server. Ist the used file name "0000000" the original one or are you using it as a place holder?

**Comment by ultradyran** [comment]
The error goes like this:
http://cloud.mydomain.com/remote.php/dav/uploads/myname/124723862/00000000”
myfile/Images/somepictures.png

The last part is always /00000000, with eight zeros.
File name/parh  goes to the next line.

mp3, png, jpg, blend, pdf, m4u, zip, it failed all kinds of file...

I hvn't yet seemed to find the pattern of why some of them works and some failed to sync, definitely not file size related.

> I would assume that you tried to sync an unacceptable file type to the server. Ist the used file name "0000000" the original one or are you using it as a place holder?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
