### ISSUE TITLE
Problem witch ClassLoader.php

### ISSUE THREAD

**Issue by Shucach** [nextcloud/server#13991]
After last update raspberry pi 3b+ I get some error in some functions. 
For example, I can`t get information about my server I get next error in logs.
Sometimes I can get this error when I try go to basic settings.

php: 7.0.3
server: Apache/2.4.25 (Raspbian)
mysql  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnueabihf (armv8l) using readline 5.2

```
ParseError: syntax error, unexpected 'func' (T_STRING), expecting variable (T_VARIABLE)
/var/www/html/nextcloud/lib/composer/composer/ClassLoader.php - line 322:

Composer\Autoload\includeFile("/var/www/ht ... p")

<<closure>>

Composer\Autoload\ClassLoader->loadClass("Psr\\Http\\ ... e")

/var/www/html/nextcloud/3rdparty/guzzlehttp/psr7/src/Request.php - line 12:

spl_autoload_call("Psr\\Http\\ ... e")

/var/www/html/nextcloud/lib/composer/composer/ClassLoader.php - line 444:

include("/var/www/ht ... p")

/var/www/html/nextcloud/lib/composer/composer/ClassLoader.php - line 322:

Composer\Autoload\includeFile("/var/www/ht ... p")

<<closure>>

Composer\Autoload\ClassLoader->loadClass("GuzzleHttp\\Psr7\\Request")

/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 121:

spl_autoload_call("GuzzleHttp\\Psr7\\Request")

/var/www/html/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131:

GuzzleHttp\Client->requestAsync("get", GuzzleHttp\Psr7\Uri {}, { verify: "/ ... }})

/var/www/html/nextcloud/lib/private/Http/Client/Client.php - line 161:

GuzzleHttp\Client->request("get", "http://www.nextcloud.com/", { verify: "/ ... e})

/var/www/html/nextcloud/settings/Controller/CheckSetupController.php - line 157:

OC\Http\Client\Client->get("http://www.nextcloud.com/")

/var/www/html/nextcloud/settings/Controller/CheckSetupController.php - line 140:

OC\Settings\Controller\CheckSetupController->isSiteReachable("www.nextcloud.com")

/var/www/html/nextcloud/settings/Controller/CheckSetupController.php - line 656:

OC\Settings\Controller\CheckSetupController->isInternetConnectionWorking()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

OC\Settings\Controller\CheckSetupController->check()

/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

OC\AppFramework\Http\Dispatcher->executeController(OC\Settings\ ... {}, "check")

/var/www/html/nextcloud/lib/private/AppFramework/App.php - line 118:

OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\ ... {}, "check")

/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

OC\AppFramework\App::main("OC\\Setting ... r", "check", OC\AppFramew ... {}, { _route: "s ... "})

<<closure>>

OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "s ... "})

/var/www/html/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func(OC\AppFramew ... {}, { _route: "s ... "})

/var/www/html/nextcloud/lib/base.php - line 987:

OC\Route\Router->match("/settings/ajax/checksetup")

/var/www/html/nextcloud/index.php - line 42:

OC::handleRequest()
```

**Comment by 1234michi** [comment]
I get also such a error in log when I want to connect Floccus to the bookmark app:

`ParseError: syntax error, unexpected 'const' (T_CONST), expecting variable (T_VARIABLE)

    /var/www/nextcloud/lib/composer/composer/ClassLoader.php - line 322:

    Composer\Autoload\includeFile("/var/www/ne ... p")

    <<closure>>

    Composer\Autoload\ClassLoader->loadClass("Rowbot\\URL\\BasicURLParser")

    /var/www/nextcloud/apps/bookmarks/vendor/rowbot/url/src/URL.php - line 72:

    spl_autoload_call("Rowbot\\URL\\BasicURLParser")

    /var/www/nextcloud/apps/bookmarks/lib/UrlNormalizer.php - line 12:

    Rowbot\URL\URL->__construct("http://blog ... x")

    /var/www/nextcloud/apps/bookmarks/lib/Bookmarks.php - line 440:

    OCA\Bookmarks\UrlNormalizer->normalize("http://blog ... x")

    /var/www/nextcloud/apps/bookmarks/lib/Controller/Rest/BookmarkController.php - line 226:

    OCA\Bookmarks\Bookmarks->bookmarkExists("http://blog ... x", "Michael")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 166:

    OCA\Bookmarks\Controller\Rest\BookmarkController->getBookmarks("bookmark", "", 0, "bookmarks_sorting_recent", "Michael", null, "or", "", [], 10, false, null, "http://blog ... x")

    /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Bookmark ... }}, "getBookmarks")

    /var/www/nextcloud/lib/private/AppFramework/App.php - line 118:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Bookmark ... }}, "getBookmarks")

    /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("BookmarkController", "getBookmarks", OC\AppFramew ... {}, { _route: "b ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "b ... "})

    /var/www/nextcloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "b ... "})

    /var/www/nextcloud/lib/base.php - line 987:

    OC\Route\Router->match("/apps/bookm ... k")

    /var/www/nextcloud/index.php - line 42:

    OC::handleRequest()`

nextcloud: 15.0.10.0
bookmark app: 1.0.8

**Comment by kesselb** [comment]
cc @marcelklehr any idea?

**Comment by marcelklehr** [comment]
Yeah, the latest versions of the bookmarks app require php v7.1+ as well as some additional extensions. You can either upgrade php or downgrade the bookmarks app to [v1.0.6](https://github.com/nextcloud/bookmarks/releases/tag/v1.0.6).
