### ISSUE TITLE
Set Quota total for SUM of group

### ISSUE THREAD

**Issue by cl4x** [nextcloud/server#13993]
Hi, I've read several topics that talk about quota, but I did not find anything for what I would do.

Can i set quota for summary of one group?

User A + User B + User C = MAX 30Gb. Not 10+10+10, and not 30+30+30, but 30 in TOTAL.
The most similar way I found is install OCC_Web and launch usage-report:generate and ad every user in group... but 1) isn't in real time, 2) the users don't see how much space they used and free.

Thanks in advance.

**Comment by cl4x** [comment]
Similar request ref. https://github.com/nextcloud/server/issues/4275 - i found if now.

**Comment by skjnldsv** [comment]
lets use https://github.com/nextcloud/server/issues/4275 then
