### ISSUE TITLE
Virtual folders for sharing

### ISSUE THREAD

**Issue by Arvi89** [nextcloud/server#14000]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to share files (mostly photos) with people, but they are in different folders, and I don't want to share the whole folders. I just want to share like 10 files from 1 or more folder.Now I need to copy these files to a new folder.

**Describe the solution you'd like**
The ability to create a virtual shared folder. So when I decide to share a file, I add it to an existing share. That way, when I give a link, people can see my files from different folders, without me having to copy them somewhere else.

**Describe alternatives you've considered**
An alternative way would be to create a real folder, share it, and being able to ad files from different folders to that share. That way people can also add files to a share it they have the permission, because it actually exists.

**Comment by skjnldsv** [comment]
Yes, this is basically what we did with collections :)

**Comment by Arvi89** [comment]
No, this is not how collection work. I can create an "virtual folder" where I can add files from many different folders and share it to everyone so they can see what's inside.
Let's say I have pictures in 5 different folders, and I want to share these pictures to people outside my cloud, I need to copy them in another folder that I will share.

**Comment by skjnldsv** [comment]
It's a step by step process.
For now you can link multiple files to a *folder* that can contain various types of object (files, calendar, chat rooms...)

You don't need to copy anything for a collection.

The pure idea of a virtual folder as you want it is out of scope. This is not something we will add on our product. Unless someone create and open a fully working feature, we won't spend time on it. But on the collection we will, and it will improve over time ;)
