### ISSUE TITLE
NC 15.0.2: cannot resolve "/.well-known/caldav & carddav (NGINX Reverse Proxy)

### ISSUE THREAD

**Issue by kangaroo72** [nextcloud/server#14007]
Hi,

I've setup a new system on a ARM64-ODROID C2.
NGINX 1.15.8, PHP 7.3.1 & NC 15.0.2

The german messages are ...

Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/caldav" aufzulösen. Weitere Informationen findest Du in der Dokumentation.

and

Dein Web-Server ist nicht richtig eingerichtet um "/.well-known/carddav" aufzulösen. Weitere Informationen findest Du in der Dokumentation.

Actually I'm unable to fix it ... can you help me?

Here's my nextcloud.conf ... https://paste.escher.cc/view/b88e8a9a#L25

Thank you

**Comment by AndrewwHummer** [comment]
Well, same issue with traefik Load Balancer in front of nextcloud 15.0.2
Not that it creates any problems as far as I am concerned at the moment.

**Comment by kangaroo72** [comment]
won a shirt now? :-D

**Comment by j-ed** [comment]
It might be worse to use the search function before opening new issue tickets 😉 
This ticket sound similar to yours: https://github.com/nextcloud/server/issues/11789

**Comment by kangaroo72** [comment]
yep - but was earlier NC-Version?!

**Comment by j-ed** [comment]
I think the essential information is that the issue describes the .well-known link and NGINX problem. The NC version is more or less off relevance.

**Comment by AndrewwHummer** [comment]
> won a shirt now? :-D

Just wanted to add that this is not an nginx exclusive thingy.... ;D

**Comment by danielkesselberg** [comment]
Ngix: https://github.com/nextcloud/server/issues/11850#issuecomment-434320384
Traefik: https://github.com/nextcloud/server/issues/11850#issuecomment-443419867

I think we should add this information to https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/reverse_proxy_configuration.rst. @kangaroo72 @AndrewwHummer do you want to submit a pull request? :grinning:

**Comment by AndrewwHummer** [comment]
Adding this to the documentation is a great idea. Adding it to the list :)
