### ISSUE TITLE
Auto upload doesn't work anymore with 15.03 RC1

### ISSUE THREAD

**Issue by Arvi89** [nextcloud/server#14001]
### Steps to reproduce
1. Activate auto upload on your phone
2. Take a picture
3. That's it. It broke just after I updated from 14.04 to 15.03 RC1.

### Expected behaviour
It should go to the proper directory

### Actual behaviour
On ,y phone it says: "Malformed server configuration"

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4

**Database:**
MySQL 5.7

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
15.03 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Just updated from 14.04

**Where did you install Nextcloud from:**
Web updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - dicomviewer: 1.1.0
  - drawio: 0.9.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - music: 0.9.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ocsms: 2.1.1
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.1.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_facebook: 1.0.4
  - socialsharing_twitter: 1.0.4
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - weather: 1.5.5
  - workflowengine: 1.5.0
Disabled:
  - appdatacleaner
  - circles
  - encryption
  - end_to_end_encryption
  - files_antivirus
  - files_clipboard
  - phonetrack
  - twofactor_totp
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.lefev.re"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.lefev.re",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "15.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\Swift",
            "arguments": {
                "username": "WZTH8Ttqr2zX",
                "password": "***REMOVED SENSITIVE VALUE***",
                "bucket": "nextcloud",
                "autocreate": false,
                "region": "GRA1",
                "url": "https:\/\/auth.cloud.ovh.net\/v2.0\/",
                "tenantName": "7849793796232200",
                "serviceName": "swift"
            }
        },
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "updater.release.channel": "stable",
        "loglevel": 1,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "overwritehost": "cloud.lefev.re",
        "overwriteprotocol": "https",
        "trashbin_retention_obligation": "auto, 180",
        "versions_retention_obligation": "auto, 360",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes: swift

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[webdav] Fatal: Sabre\DAV\Exception: Unable to seek to stream position 0 with whence 0 at <<closure>>

 0. /home/cloud/public_html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 209
    convertToSabreException(RuntimeException {})
 1. /home/cloud/public_html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    put(null)
 2. /home/cloud/public_html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 316
    createFile("IMG_20190202_140204.jpg", null)
 3. /home/cloud/public_html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 130
    copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "IMG_20190202_140204.jpg")
 4. /home/cloud/public_html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 161
    copy("uploads/arvi89/-2107247572/.file", "files/arvi89/In ... g")
 5. /home/cloud/public_html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    move("uploads/arvi89/-2107247572/.file", "files/arvi89/In ... g")
 6. <<closure>>
    httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 7. /home/cloud/public_html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
 8. /home/cloud/public_html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    emit("method:MOVE", [Sabre\HTTP\Requ ... }])
 9. /home/cloud/public_html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
10. /home/cloud/public_html/nextcloud/apps/dav/lib/Server.php line 301
    exec()
11. /home/cloud/public_html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    exec()
12. /home/cloud/public_html/nextcloud/remote.php line 163
    require_once("/home/cloud/pub ... p")

MOVE /remote.php/dav/uploads/arvi89/-2107247572/.file
from 88.164.73.99 by arvi89 at 2019-02-03T09:28:40+00:00
```
</details>

**Comment by bremensaki** [comment]
I can't find the reference now, but I had this come up the other day and found a post somewhere (maybe Reddit? can't find it now) suggesting that having the default encryption module disabled was causing this, which yours seems to be. I did re-enable mine, despite not having ever used it, and the auto-uploads resumed. I don't have any server-side encrypted files, and I'm sure I've had the module disabled on 14.x without issue before.

I've been meaning to dig into this but haven't had time. I hope this points someone in the right direction.

**Comment by MorrisJobke** [comment]
cc @rullzer @tobiasKaminsky

**Comment by bremensaki** [comment]
This matches my experience, web was fine. Because I hadn't uploaded anything from the phone for a while I wasn't able to tell if it was an Android client update our a server update that triggered it - I'd done both before I noticed the issue.

**Comment by rullzer** [comment]
Ah you are using a swift object store. mmmm @icewind1991 could it be the streams need a similar fix as S3?

**Comment by bremensaki** [comment]
Mine was using Google Cloud storage in S3 compatible mode at the time it triggered.

**Comment by Arvi89** [comment]
Btw, enabling the encryption module also works for me (even though I'm not using it).

**Comment by Arvi89** [comment]
I don't know if it is related, but now that I've activated th encryption module and it works (even though I'm not using it), within the last few days, I've got corrupted uploads, like that one:
https://cloud.lefev.re/s/oenF3kKqTwm8oXP
I'm in India right now and internet is not working that well, but even with poor connection before, I've never got something similar.

**Comment by skjnldsv** [comment]
Hey! Is this still happening?

**Comment by Arvi89** [comment]
Upload now works again, perfect!
