### ISSUE TITLE
selecting all files in search/filter view targets whole directory instead of just the visibly selected files -> e.g. wrong files deleted

### ISSUE THREAD

**Issue by xNuno** [nextcloud/server#14016]
### Steps to reproduce
1. Search for something that return multiple results
2. Select all items
3. Actions -> Delete

### Expected behaviour
Delete only the selected items

### Actual behaviour
All items on the folder get deleted

### Server configuration

**Operating system**: Debian with Docker + linuxserver.io Image

**Web server:**

**Database:** Maria DB Latest

**PHP version:**

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by violoncelloCH** [comment]
thank you for reporting
could you please clarify what you select and what gets deleted instead?

**Comment by xNuno** [comment]
Go to any folder with some files, search for something that returns more than one result, select all results with the box select on top bar and go to actions delete... All files of the folder will get deleted and not only the selected ones.

**Comment by danielkesselberg** [comment]
https://github.com/nextcloud/server/issues/1274
https://github.com/nextcloud/server/pull/9925

**Comment by kubco2** [comment]
This breaks also downloading selected files.
Search something with more results in directory. Select all > download, instead downloading selected files, whole directory is downloaded.

**Comment by violoncelloCH** [comment]
managed to reproduce this even with 16.0.0RC2
cc @nextcloud/server-triage

**Comment by loeffelpan** [comment]
I can confirm.
This should have been fixed with NC14 and works for some cases.

**Comment by nickvergessen** [comment]
@skjnldsv  please have a look, this looks quite bad

**Comment by skjnldsv** [comment]
#9925 actually solved the unselect, but not the select part. Which was already there. :/

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/15309
