### ISSUE TITLE
Broken security tips link

### ISSUE THREAD

**Issue by jmdf** [nextcloud/server#14014]
### Steps to reproduce
1. Go to Settings > Security & setup warnings
2. Click on `security tips` in:
```
The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips ↗.
```

### Expected behaviour
Open a documentation page with security tips

### Actual behaviour
Opens a page with `File not found` - [here](https://docs.nextcloud.com/server/15/admin_manual/configuration_server/harden_server.html)

### Server configuration

**Operating system**: Centos 7.6

**Web server:** nginx 1.12.2

**Database:** MariaDB 10.2.21

**PHP version:** 7.2.14

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes

**Where did you install Nextcloud from:** Downloaded from official site

I don't know if this is the right place to report this but, if not, please guide me. Also, if it's not a very complicated fix, I'm available to help.

**Comment by danielkesselberg** [comment]
This would be the right link: https://docs.nextcloud.com/server/15/admin_manual/installation/harden_server.html

https://github.com/nextcloud/documentation/blob/1f60db10a333cb979af201016afdc5933931600e/go.php#L30 This should be "installation" instead of "configuration_server".

**Comment by MorrisJobke** [comment]
Good one - I actually for got that one 🙈 

See https://github.com/nextcloud/documentation/pull/1214/files

Let me fix that.

**Comment by MorrisJobke** [comment]
Fix is in 
https://github.com/nextcloud/documentation/pull/1223
