### ISSUE TITLE
NEXTCLOUD SLOW WITH USER IMAGE FROM LDAP

### ISSUE THREAD

**Issue by cleao01** [nextcloud/server#14011]
### Steps to reproduce

Using an image in personal profile from LDAP server , response from the browser becames slow

### Expected behaviour

Experience speed in browser must be the same as with no image in user profile

### Actual behaviour

Browser experience is to slow, logging in, and in many options

### Server configuration

**Operating system**: centos 7

**Web server:** apache

**Database:** mariadb

**PHP version:** 4.3

**Nextcloud version:**  15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**   NO

**Where did you install Nextcloud from:**   Command line

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

```
</details>

**List of activated apps:**

Files external
External LDAP users

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**   Windwos server 2012

### Client configuration
CHROME

**Operating system:**
WINDOWS / Android

**Comment by rugk** [comment]
Using CAPS-LOCK will not help to get that issue easier fixed/troubleshooted. Please refrain from shouting on the internet.
