### ISSUE TITLE
OCS Share API work incorrect

### ISSUE THREAD

**Issue by Dzialo3** [nextcloud/server#14021]
I created an application to sending and generating public URL. For this to work, I used OCS Share API to create public URL. Few days ago my application stopped working and I found a reason.

Steps to reproduce:
1. Try to send request to create share (in this case public, read only). To debug issue I used curl in cmd:
curl --user "user:password" "https://URL_TO_CLOUD/ocs/v1.php/apps/files_sharing/api/v1/shares" --data "path=/dir/file&shareType=3&permissions=1" -H "OCS-APIRequest: true"

2. Wait for respond  (respond empty, and HTTP response code 200 instead of 100)

To obtain shared URL I had to send a second request (URL must exist). According to the documentation, the URL should be generated in the first answer.

**Comment by violoncelloCH** [comment]
Which Nextcloud version do you use? In general it's a good idea to fill in the issue template providing us the necessary informations about software versions and configuration...

**Comment by ChristophWurst** [comment]
No feedback provided -> closing
