### ISSUE TITLE
Setting of storage class for S3

### ISSUE THREAD

**Issue by chaoszone** [nextcloud/server#14031]
Currently the S3 external storage uploads every object into the standard aws storage class.

I would like to choose between the different storage classes (e.g. standard, glacier, etc.)
As far I know the AWS SDK that is used by Nextcloud already supports this option, but I cant figure out what to modify in the S3Client.php

**Comment by FlorentCoppint** [comment]
Would be great !

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
