### ISSUE TITLE
NC 15 shows hidden folders when netview enabled

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#14034]
### Steps to reproduce
1. Have a hidden folder, e.g. `.Contacts-Backup` and set "Do not show hidden files" in web options.
2. Open your NC in Browser and change to net view
![image](https://user-images.githubusercontent.com/6813635/52289187-e2843500-296d-11e9-8aae-ec3271aa7019.png)
3. See that hidden folder is now shown without name.
![image](https://user-images.githubusercontent.com/6813635/52289329-18c1b480-296e-11e9-95f2-651860f2f201.png)

4. Not seen in "Lines" view:
![image](https://user-images.githubusercontent.com/6813635/52289270-034c8a80-296e-11e9-9e51-f2def7d775fc.png)

### Expected behaviour
Hidden files and Folders are not shown when option disabled.

### Actual behaviour
Hidden files and Folders are shown in a net veiew when option disabled.

### Server configuration

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official

**Comment by violoncelloCH** [comment]
reproduced with 15.0.3RC1
cc @juliushaertl @skjnldsv

**Comment by GAS85** [comment]
Works good in 16.0.6
