### ISSUE TITLE
Changing values of the theming app restyles without accessibility settings

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#14059]
1. Enable dark mode
2. Enable dyslexia font
3. Go to /index.php/settings/admin/theming
4. Change any value
5. Be blinded by the white page :dark_sunglasses:  

cc @juliushaertl @skjnldsv

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by szaimen** [comment]
Yes, still reproducible on NC21.0.2
