### ISSUE TITLE
Multiple Navigation En

### ISSUE THREAD

**Issue by medcloud** [nextcloud/server#14052]
In nextcloud 14 app we can add navigations entries via info.xml.
When I add only one entry everything is working but when I add two or more entries, nothing is appearing in the menu. 
Entry type = settings

**Comment by MorrisJobke** [comment]
Please specify the XML that you have problems with. Or link to your apps repo.

**Comment by medcloud** [comment]
An example who is not working : 
`<?xml version="1.0"?>
<info xmlns:xsi= "http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="https://apps.nextcloud.com/schema/apps/info.xsd">
    <id>medicalcloud</id>
    <name>MC</name>
    <summary>MC</summary>
    <version>0.0.5</version>
    <licence>agpl</licence>
    <namespace>MC</namespace>
    <category>tools</category>
    <dependencies>
        <php min-version="7.0" max-version="7.2"/>
        <nextcloud min-version="14" max-version="14"/>
    </dependencies>
    <navigations>
        <navigation role="all">
            <id>mcaccount</id>
            <name>Account</name>
            <route>mc.page.index</route>
            <order>0</order>
            <icon>info.svg</icon>
            <type>settings</type>
        </navigation>
        <navigation role="admin">
            <id>mcadmin</id>
            <name>Admin</name>
            <route>mc.page.admin</route>
            <order>0</order>
            <icon>info.svg</icon>
            <type>settings</type>
        </navigation>
    </navigations>
    <two-factor-providers>
        <provider>OCA\MC\Provider\SmsProvider</provider>
    </two-factor-providers>
</info>
`

**Comment by kesselb** [comment]
Your example is not valid. There are some attributes missing: https://github.com/nextcloud/appstore/blob/master/docs/developer.rst

**Comment by medcloud** [comment]
That's because I have clean some element before post ; my info.xml is working.
The problem is when you have 2 navigations elements
<navigations>
<navigation role="all">
<id>mcaccount</id>
<name>Account</name> 
<route>mc.page.index</route> 
<order>0</order>
<icon>info.svg</icon> 
<type>settings</type> 
</navigation> 
<navigation role="admin"> 
<id>mcadmin</id> 
<name>Admin</name> 
<route>mc.page.admin</route> 
<order>0</order> 
<icon>info.svg</icon> 
<type>settings</type> 
</navigation> 
</navigations>

**Comment by kesselb** [comment]
Thank you for clarifying :+1: 

Modified the activity app like below and no icon appear anymore.

```
	<navigations>
		<navigation>
			<name>Activity</name>
			<route>activity.Activities.showList</route>
			<icon>activity.svg</icon>
			<order>1</order>
		</navigation>
		<navigation>
			<name>Activity-Test</name>
			<route>activity.Activities.showList</route>
			<icon>activity.svg</icon>
			<order>2</order>
		</navigation>
	</navigations>
```

**One navigation item**
![image](https://user-images.githubusercontent.com/3902676/53249255-f2af4a80-36b7-11e9-80f2-1ae1d4ce9685.png)

**Two navigation items**
![image](https://user-images.githubusercontent.com/3902676/53249314-15416380-36b8-11e9-837d-7eb4c6207084.png)
