### ISSUE TITLE
NC 15.0.2 registered date/time of upload is incorrect

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#14065]
**File was uploaded on February 6th around 5PM, the time registered was 21 hours back.**

![bug](https://user-images.githubusercontent.com/31093459/52355291-6142a600-2a32-11e9-819f-3cdfdece2ef2.png)

![bug2](https://user-images.githubusercontent.com/31093459/52355246-4a9c4f00-2a32-11e9-96da-1c3f30cce11b.png)

**Comment by MorrisJobke** [comment]
That time is the time when the file was last modified. Only in the web browser this is the same time as the upload because this metadata is not provided by browsers. So this works as it should.

**Comment by timmersr** [comment]
I do not understand? The file did not exist before. So it could not be modified before.
It was just uploaded as a new file 6 minutes ago, so there should be no reference to 23 hours before.
