### ISSUE TITLE
occ app:update --all doesn't fail when it doesn't have the permissions to update apps

### ISSUE THREAD

**Issue by baldurmen** [nextcloud/server#14072]
### Steps to reproduce
1. Make sure an app needs to be updated
2. Set the mode on files in `apps` to 440 and on dirs to 550, recursively, while keeping `apps` itself to 750
3. Run `php occ app:update --all` as the owner of those files
4. Get a confirmation  that the app in question has been updated
5. Check the app's `appinfo/info.xml` and see that the app wasn't in fact updated

### Expected behaviour
The command `php occ app:update --all` should fail with an error message saying it doesn't have the permissions to update the app.

### Actual behaviour
A confirmation message that the app has been updated is shown.

### Server configuration

**Operating system**: Debian Stretch

**Web server:** Apache2 2.4.25-3+deb9u6

**Database:** mariadb  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.0.33-0+deb9u1

**Nextcloud version:** 15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** The Nextcloud download page

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - firstrunwizard: 2.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_u2f: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - comments
  - encryption
  - files_external
  - files_videoplayer
  - gallery
  - serverinfo
  - survey_client
  - theming
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "logtimezone": "America\/New_York",
        "log_rotate_size": "1048576",
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud.log",
        "log_type": "file",
        "auth.bruteforce.protection.enabled": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "enable_previews": false,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "config_is_read_only": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox 60.5.0

**Operating system:** Debian Testing

### Logs

None.

**Comment by baldurmen** [comment]
To be clear here, I'm running Nextcloud with a seperate user via PHP-FPM. For security reasons, everything is set to read-only to be sure Nextcloud can't update itself.

I normally give write permissions again on manual update done via the command line, but I forgot this time on this machine and found this bug.

**Comment by skjnldsv** [comment]
It doesn't generate any errors in logs?
I'm surprised :thinking: 

As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
