### ISSUE TITLE
stuck with "There was no plugin in the system that was willing to handle this POST method"

### ISSUE THREAD

**Issue by nunomoreno** [nextcloud/server#14088]
Dear All

I'm trying to upload a few posted files to nextcould 14. I think to be doing everything correctly but it keeps displaying:
There was no plugin in the system that was willing to handle this POST method

url gets is  like this and 20190207.Antibodies.13244 is an existing folder.

https://xxxxxxx/remote.php/dav/files/nextcloudadmin/20190207.Antibodies.13244
 $data is

array (
  'file0' => 
  CURLFile::__set_state(array(
     'name' => '/Users/moreno/www/agendo_next_v3/my/uploads/institute/requests/request_history_60491.csv',
     'mime' => 'text/csv',
     'postname' => 'stats_2019_01_31_11_22_31.csv',
  )),
)

here the code:

$url=$this->baseurl.$this->login ."/". date($this->filedatestructure).$this->separator.$this->resourcename.$this->separator.$this->transid;
        $this->log_debug($url);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_CUSTOMREQUEST, "POST");
        curl_setopt($ch, CURLOPT_USERAGENT, "Mozilla/5.0 (Windows; U; Windows NT 6.1; en-GB; rv:1.9.2) Gecko/20100115 Firefox/3.6 (.NET CLR 3.5.30729)");
        curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, 0);
        curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, 0);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $data);
        curl_setopt($ch, CURLOPT_TIMEOUT, 60);

Many thanks

**Comment by nunomoreno** [comment]
More details 

the response is the following

HTTP/1.1 501 Not Implemented
Date: Thu, 07 Feb 2019 21:25:35 GMT
.....

and, I can add a file via webdav, I can create a folder using MKCOL, and I can share using OCS API.

**Comment by kesselb** [comment]
Do you still see this issue?
