### ISSUE TITLE
changelog for 15.0.3 and 15.0.4 missing

### ISSUE THREAD

**Issue by Bubu** [nextcloud/server#14087]
The in repo changelog only points here: https://nextcloud.com/changelog/

There's no changelog for these versions.

**Comment by j-ed** [comment]
Check it out again, I can see the changes: https://nextcloud.com/changelog/#latest15

**Comment by Bubu** [comment]
This is what I see:

![image](https://user-images.githubusercontent.com/105185/52421164-c9a58c00-2af3-11e9-8c0b-f0eff9a9525f.png)

**Comment by Bubu** [comment]
Force-reloading the page without browser cache fixed that... so mmh, maybe the caching policy needs the be rethought.

**Comment by MorrisJobke** [comment]
> Force-reloading the page without browser cache fixed that... so mmh, maybe the caching policy needs the be rethought.

Mmmmh ... it should update, because the apache server has nothing special there. Also it worked without the force refresh even with cached content :/


Anyways: good that it's working for you now.
