### ISSUE TITLE
Resharing broken

### ISSUE THREAD

**Issue by mikaelh** [nextcloud/server#14082]
### Steps to reproduce
1. As user 1, create folder A and share to user 2.
2. As user 2, login and create Folder B in Folder A to an external e-mail address (example: test@nextcloud.localhost) 
=> No entry is created in activity timeline
3. As user 2, delete share on Folder A/Folder B.
=> UI update and it look like it is removed, but refresh screen and it is still there.
4. Go to the database and set expire date to yesterday.
5. As user 2, go to Folder A/Folder B
=> Loading screen spins forever, not possible to see files or modify share

Step 2 generates the following log error
TypeError: Argument 2 passed to OC\\Activity\\Event::setSubject() must be of the type array, string given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 321 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#208

Step 3 and 5 generate the followng log error
TypeError: Argument 3 passed to OC\\Activity\\Event::setObject() must be of the type string, null given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 323 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#377

### Expected behaviour
After resharing a folder, it should be logged correctly and unsharing should be possible.
When a share expire, it should be removed correctly and loading screen should not spin forever.

### Actual behaviour
See steps to reproduce

### Server configuration
Fresh install using latest docker image with tag15.0.2-apache
### Client configuration
**Browser:** Chrome 71.0.3578.98

**Operating system:** Ubuntu 18.04

#### Nextcloud log (data/nextcloud.log)

nextcloud-log_1  | {"reqId":"oRtAUaI6N1KOy1ZXSsp1","level":3,"time":"2019-02-07T12:18:45+00:00","remoteAddr":"172.25.0.3","user":"user 2","app":"PHP","method":"POST","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares?format=json","message":"TypeError: Argument 2 passed to OC\\Activity\\Event::setSubject() must be of the type array, string given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 321 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#208","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.81 Safari\/537.36","version":"15.0.2.0"}

nextcloud-log_1  | {"reqId":"5nB94sCEarWnzsdPisBp","level":3,"time":"2019-02-07T12:25:35+00:00","remoteAddr":"172.25.0.3","user":"user 2","app":"PHP","method":"DELETE","url":"\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/shares\/3?format=json","message":"TypeError: Argument 3 passed to OC\\Activity\\Event::setObject() must be of the type string, null given, called in \/var\/www\/html\/apps\/sharebymail\/lib\/ShareByMailProvider.php on line 323 at \/var\/www\/html\/lib\/private\/Activity\/Event.php#377","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.81 Safari\/537.36","version":"15.0.2.0"}

**Comment by danielkesselberg** [comment]
> Step 2 generates the following log error
> TypeError: Argument 2 passed to OC\Activity\Event::setSubject() must be of the type array, string given, called in /var/www/html/apps/sharebymail/lib/ShareByMailProvider.php on line 321 at /var/www/html/lib/private/Activity/Event.php#208

Step 2 should work with patch below:

```
Index: apps/sharebymail/lib/ShareByMailProvider.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/sharebymail/lib/ShareByMailProvider.php	(revision 2b224881075bb87025d9f28b565abaeb7ef9d1ae)
+++ apps/sharebymail/lib/ShareByMailProvider.php	(date 1549543719000)
@@ -264,7 +264,7 @@
 			$ownerPath = $nodes[0]->getPath();
 			$this->publishActivity(
 				$type === 'share' ? Activity::SUBJECT_SHARED_EMAIL_BY : Activity::SUBJECT_UNSHARED_EMAIL_BY,
-				Activity::SUBJECT_SHARED_EMAIL_BY,
+				[Activity::SUBJECT_SHARED_EMAIL_BY],
 				[$ownerFolder->getRelativePath($ownerPath), $share->getSharedWith(), $share->getSharedBy()],
 				$share->getShareOwner(),
 				$fileId,

```

**Comment by danielkesselberg** [comment]
I guess @nickvergessen has already a solution for Step 3: https://github.com/nextcloud/server/pull/14083 :sunglasses:

**Comment by nickvergessen** [comment]
Actually my fix is for setSubject and setObject
