### ISSUE TITLE
Feature and bug fix PR

### ISSUE THREAD

**Issue by mmattel** [nextcloud/server#1409]
I hope that I am not doing bad with my referencing to ownCloud pls forgive me if this is unpolite...

There have been two PR´s which may be of interrest to you. One merged feature and one important bug fix. I am in sorry not beeing able to make PR´s myself, I am locked down with regular business.
Maybe somone of the team wants/can do it...

**Feature:**
Exclude Directories (merged, for professional Storage use)
/core/pull/19235

Dokumentation for it (merged)
/documentation/pull/2613 + plus the two small corrections 

**Bug Fix:**
Fix fed share test call to return proper result (merged)
/core/pull/26038
(the issue: /core/issues/25854 killed my nerves)

**Comment by nickvergessen** [comment]
We will take care of porting the pull requests when necessary, thanks for notifying.

> I hope that I am not doing bad with my referencing to ownCloud pls forgive me if this is unpolite...

No problem ;)
