### ISSUE TITLE
OCP\Files\StorageNotAvailableException: File with id

### ISSUE THREAD

**Issue by kpleines** [nextcloud/server#14098]
Seems linked from a file that was deleted by the owner itself, was not correct deleted. So nextcloud tries to find the file.

### Steps to reproduce
1. Open Admin --> Configurations --> protokoll entrys
2. show logs
3.

### Expected behaviour
I expcted the all links from deleted files should be also deleted. 

### Actual behaviour
Instead the nextcloud/desktop app tries to sync the linked file which is already deleted by the owner. 

### Server configuration

Speicher
Benutzer: 10
Dateien: 16142
Speicher: 15
Freier Speicherplatz: 654,9 GB

Nextcloud
Version: 15.0.2.0
Installierte Apps: 46

Apps mit verfügbaren Aktualisierungen: 0

PHP
Version: 7.2.13
Arbeitspeicher-Grenzwert: 5,8 GB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 10 GB

Datenbank
Art: mysql
Version: 10.1.37
Größe: 26,4 MB

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 14 (fresh installed in November 2018)

**Where did you install Nextcloud from:**
I used the NextcloudPi-Docker-Image

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>Accessibility	1.1.0	Offiziell	
Activities for shared file downloads, visible to all admins	1.4.0		
Activity	2.8.2	Offiziell	
Calendar	1.6.4	Offiziell	
Circles	0.16.0	Offiziell	
Collaborative tags	1.5.0	Offiziell	
Comments	1.5.0	Offiziell	
Contacts	3.0.3	Offiziell	
Deck	0.5.2		
Deleted files	1.5.0	Offiziell	
Federation	1.5.0	Offiziell	
File sharing	1.7.0	Offiziell	
First run wizard	2.4.0	Offiziell	
Gallery	18.2.0	Offiziell	
Group folders	2.0.2	Offiziell	
Log Reader	2.0.0	Offiziell	
Monitoring	1.5.0	Offiziell	
News	13.0.3		
Nextcloud announcements	1.4.0	Offiziell	
NextCloudPi	0.0.1		
Notes	2.5.1	Offiziell	
Notifications	2.3.0	Offiziell	
Password policy	1.5.0	Offiziell	
PDF viewer	1.4.0	Offiziell	
Preview Generator	2.0.0		
Quota warning	1.4.0		
Share by mail	1.5.0	Offiziell	
Social	0.1.3		
Support	1.0.0	Offiziell	
Tasks	0.9.8		
Text editor	2.7.0	Offiziell	
Theming	1.6.0	Offiziell	
Two Factor TOTP Provider	2.1.0	Offiziell	
Update notification	1.5.0	Offiziell	
Usage survey	1.3.0	Offiziell	
Versions	1.8.0	Offiziell	
Video player 1.4.0</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary><?php
$CONFIG = array (
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => 'pleines.myqnapcloud.com',
    1 => '10.0.3.2',
    5 => 'nextcloudpi.local',
    7 => 'nextcloudpi',
    8 => '',
    3 => '',
    2 => 'qnap.fritz.box',
  ),
  'datadirectory' => '/data/app/data',
  'dbtype' => 'mysql',
  'version' => '14.0.4.2',
  'overwrite.cli.url' => 'https://kpleines.spdns.de/',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'ncadmin',
  'dbpassword' => '',
  'installed' => true,
  'instanceid' => 'oc2vcrs8jgrj',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
    'password' => '',
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => ',
  'mail_domain' => '',
  'overwriteprotocol' => 'https',
  'mail_smtpauth' => 1,
  'mail_smtpsecure' => 'tls',
  'mail_smtphost' => 'mail.gmx.net',
  'mail_smtpport' => '587',
  'mail_smtpname' => '',
  'mail_smtppassword' => '',
  'maintenance' => false,
  'auth.bruteforce.protection.enabled' =>false,
);
</summary>

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Docker volume:
/data is mapped to host directory

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

### Client configuration
**Browser:** Firefox 65 / Chrome 71.0.xxxx

**Operating system:**
Host OS (Qnap 251 linux based) with NextcloudPi-Container. 
Client OS Windows 10 Professional

#### Web server error log
<details>
<summary>getShares"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"\/data\/nextcloud\/lib\/private\
/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"\/data\/nextclou
d\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares"]},{"file":"\/data\/nextcloud\/ocs\/v2.php","line":24,"args":["\/
data\/nextcloud\/ocs\/v1.php"],"function":"require_once"}],"File":"\/data\/nextcloud\/lib\/private\/Files\/Storage\/FailedStorage.php","Line":197,"Hint":"Storage is temporarily not available","Previous":{"E
xception":"OCP\\Files\\NotFoundException","Message":"File with id \"10349\" has not been found.","Code":0,"Trace":[{"file":"\/data\/nextcloud\/apps\/files_sharing\/lib\/SharedStorage.php","line":128,"functi
on":"getPath","class":"OC\\Files\\View","type":"->","args":[10349]},{"file":"\/data\/nextcloud\/apps\/files_sharing\/lib\/SharedStorage.php","line":482,"function":"init","class":"OCA\\Files_Sharing\\SharedS
torage","type":"->","args":[]},{"file":"\/data\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Jail.php","line":220,"function":"getWrapperStorage","class":"OCA\\Files_Sharing\\SharedStorage","type":"->",
"args":[]},{"file":"\/data\/nextcloud\/apps\/files_sharing\/lib\/SharedStorage.php","line":199,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":[""]},{"file":"\/dat
a\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":215,"function":"getPermissions","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[""]},{"file":"\/data\/nextcloud\/apps
\/files_sharing\/lib\/Cache.php","line":148,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[""]},{"file":"\/data\/nextcloud\/apps\/files_sharing\/lib\/Cache.ph
p","line":114,"function":"formatCacheEntry","class":"OCA\\Files_Sharing\\Cache","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"},""]},{"file":"\/data\/nextcloud\/lib\/private\/Files\/View.ph
p","line":1313,"function":"get","class":"OCA\\Files_Sharing\\Cache","type":"->","args":[""]},{"file":"\/data\/nextcloud\/lib\/private\/Files\/View.php","line":1368,"function":"getCacheEntry","class":"OC\\Fi
les\\View","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"},"","\/mgm\/files\/20190118_182141_FollowBUSchlittschuh
laufen.jpg"]},{"file":"\/data\/nextcloud\/lib\/private\/Files\/Node\/Root.php","line":198,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/mgm\/files\/20190118_182141_FollowBUSchlit
tschuhlaufen.jpg"]},{"file":"\/data\/nextcloud\/lib\/private\/Files\/Node\/Folder.php","line":133,"function":"get","class":"OC\\Files\\Node\\Root","type":"->","args":["\/mgm\/files\/20190118_182141_FollowBU
Schlittschuhlaufen.jpg"]},{"file":"\/data\/nextcloud\/apps\/files_sharing\/lib\/Controller\/ShareAPIController.php","line":684,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->","args":["\/20190
118_182141_FollowBUSchlittschuhlaufen.jpg"]},{"file":"\/data\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"getShares","class":"OCA\\Files_Sharing\\Controller\\ShareAPI
Controller","type":"->","args":["true","false","false","\/20190118_182141_FollowBUSchlittschuhlaufen.jpg","false"]},{"file":"\/data\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"f
unction":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"getShares"]},{"file":"\/data\/nextcloud\/lib
\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"getSha
res"]},{"file":"\/data\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controlle
r\\ShareAPIController","getShares",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"function":"__invoke","class":"OC\\AppFramework\\Ro
uting\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"\/data\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":
[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"\/data\/nextcloud\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\R
outer","type":"->","args":["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares"]},{"file":"\/data\/nextcloud\/ocs\/v2.php","line":24,"args":["\/data\/nextcloud\/ocs\/v1.php"],"function":"require_once"}],"File":
"\/data\/nextcloud\/lib\/private\/Files\/View.php","Line":1725},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}

res"]},{"file":"\/data\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controlle
r\\ShareAPIController","getShares",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"function":"__invoke","class":"OC\\AppFramework\\Ro
uting\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"\/data\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":
[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.ShareAPI.getShares"}]},{"file":"\/data\/nextcloud\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\R
outer","type":"->","args":["\/ocsapp\/apps\/files_sharing\/api\/v1\/shares"]},{"file":"\/data\/nextcloud\/ocs\/v2.php","line":24,"args":["\/data\/nextcloud\/ocs\/v1.php"],"function":"require_once"}],"File":
"\/data\/nextcloud\/lib\/private\/Files\/View.php","Line":1725},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.2.0"}   
{"reqId":"0Tk6L4xar0Oseje204H4","level":3,"time":"2019-02-07T07:15:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 1 passed t
o OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in \/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php on line 154
","Code":0,"Trace":[{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php","line":154,"function":"getVersionsFolder","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type
":"->","args":["1"]},{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/GroupVersionsExpireManager.php","line":53,"function":"getAllVersionedFiles","class":"OCA\\GroupFolders\\Versions\\Versions
Backend","type":"->","args":[{"id":"1","mount_point":"GMgmLeitung","groups":{"MgmLeitung":"31"},"quota":"1073741274","size":0}]},{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/GroupVersionsE
xpireManager.php","line":48,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->","args":[{"id":"1","mount_point":"GMgmLeitung","groups":{"MgmLeitung":"31"}
,"quota":"1073741274","size":0}]},{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/BackgroundJob\/ExpireGroupVersions.php","line":40,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVer
sionsExpireManager","type":"->","args":[]},{"file":"\/data\/nextcloud\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type"
:"->","args":[null]},{"file":"\/data\/nextcloud\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJo
b\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/data\/nextcloud\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobLis
t"},{"__class__":"OC\\Log"}]}],"File":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php","Line":189,"CustomMessage":"--"},"userAgent":"--","version":"15.0.2.0"}                     
{"reqId":"ekHODkZSlUnOOSrfVt9s","level":3,"time":"2019-02-07T19:15:06+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 1 passed t
o OCA\\GroupFolders\\Versions\\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in \/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php on line 154
","Code":0,"Trace":[{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php","line":154,"function":"getVersionsFolder","class":"OCA\\GroupFolders\\Versions\\VersionsBackend","type
":"->","args":["1"]},{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/GroupVersionsExpireManager.php","line":53,"function":"getAllVersionedFiles","class":"OCA\\GroupFolders\\Versions\\Versions
Backend","type":"->","args":[{"id":"1","mount_point":"GMgmLeitung","groups":{"MgmLeitung":"31"},"quota":"1073741274","size":0}]},{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/GroupVersionsE
xpireManager.php","line":48,"function":"expireFolder","class":"OCA\\GroupFolders\\Versions\\GroupVersionsExpireManager","type":"->","args":[{"id":"1","mount_point":"GMgmLeitung","groups":{"MgmLeitung":"31"}
,"quota":"1073741274","size":0}]},{"file":"\/data\/nextcloud\/apps\/groupfolders\/lib\/BackgroundJob\/ExpireGroupVersions.php","line":40,"function":"expireAll","class":"OCA\\GroupFolders\\Versions\\GroupVer
sionsExpireManager","type":"->","args":[]},{"file":"\/data\/nextcloud\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions","type"
:"->","args":[null]},{"file":"\/data\/nextcloud\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJo
b\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/data\/nextcloud\/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobLis
t"},{"__class__":"OC\\Log"}]}],"File":"\/data\/nextcloud\/apps\/groupfolders\/lib\/Versions\/VersionsBackend.php","Line":189,"CustomMessage":"--"},"userAgent":"--","version":"15.0.2.0"}          </summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[no app in context] Error: OCP\Files\StorageNotAvailableException: File with id "10349" has not been found. at <<closure>>

 0. /data/nextcloud/apps/files_sharing/lib/SharedStorage.php line 423
    acquireLock("", 1, OC\Lock\MemcacheLockingProvider {})
 1. /data/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 593
    acquireLock("", 1, OC\Lock\MemcacheLockingProvider {})
 2. /data/nextcloud/lib/private/Files/View.php line 1923
    acquireLock("", 1, OC\Lock\MemcacheLockingProvider {})
 3. /data/nextcloud/lib/private/Files/View.php line 2033
    lockPath("/mgm/files/2019 ... g", 1, false)
 4. /data/nextcloud/lib/private/Files/Node/Node.php line 366
    lockFile("/mgm/files/2019 ... g", 1)
 5. /data/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php line 1119
    lock(1)
 6. /data/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php line 685
    lock(OC\Files\Node\File {})
 7. /data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    getShares("false", "true", "false", OC\Files\Node\File {}, "false")
 8. /data/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OCA\Files_Sharin ... {}, "getShares")
 9. /data/nextcloud/lib/private/AppFramework/App.php line 118
    dispatch(OCA\Files_Sharin ... {}, "getShares")
10. /data/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OCA\\Files_Shar ... r", "getShares", OC\AppFramework\ ... {}, {_route: "ocs.fi ... "})
11. <<closure>>
    __invoke({_route: "ocs.fi ... "})
12. /data/nextcloud/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "ocs.fi ... "})
13. /data/nextcloud/ocs/v1.php line 82
    match("/ocsapp/apps/fi ... s")
14. /data/nextcloud/ocs/v2.php line 24
    require_once("/data/nextcloud/ocs/v1.php")

GET /ocs/v2.php/apps/files_sharing/api/v1/shares?format=json&path=%2F20190118_182141_FollowBUSchlittschuhlaufen.jpg&reshares=true
from 109.250.153.136 by mgm at 2019-02-06T19:49:27+00:00
```
</details>

Is ther something I can do to clean this error?

**Comment by kpleines** [comment]
I found a fix.

1. Delete the Group where the link was given
2. Create the Group again.

It works. Thanx

**Comment by tilllt** [comment]
Thats not a fix, but a workaround i would say.
