### ISSUE TITLE
Create poll with expire date not possible and Doctrine\DBAL\Exception\DriverException 

### ISSUE THREAD

**Issue by captainjoh** [nextcloud/server#14099]
### Steps to reproduce
1. Input of new poll
2. Insert expire date and time via dropdown list
3. Press create poll button

### Expected behaviour
Sucessful created poll.

### Actual behaviour
Enless loop and if you go to the logs you can see the following:

  | Doctrine\DBAL\Exception\DriverException: An  exception occurred while executing 'INSERT INTO  `oc_polls_events`(`title`,`description`,`type`,`is_anonymous`,`full_anonymous`,`allow_maybe`,`access`,`expire`,`owner`,`created`,`hash`)  VALUES(?,?,?,?,?,?,?,?,?,?,?)' with params ["Testpoll", "",  1, 0, 0, 0, "public", "2019-02-07T23:15:00.000Z", "user1",  "2019-02-07 20:06:47", "YEpMhVUVVT2wWEA7"]:  SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value:  '2019-02-07T23:15:00.000Z' for column 'expire' at row 1
-- | --

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
Apache2
**Database:**
SQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
14.07
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
Community Image
**Signing status:**
A
```

**Comment by herrmannsdorfer** [comment]
Wrong repo? Sounds like a duplicate of nextcloud/polls#461 ...

**Comment by captainjoh** [comment]
Yes seems so. Didn't see this duplicate
