### ISSUE TITLE
file version download bug on Nextcloud 15.0.4

### ISSUE THREAD

**Issue by wnabiha** [nextcloud/server#14106]
Hi there,

Upon click on the download button for the older version of files, it download the files without the file name and the extension type. The file downloaded: saved as a file without extension type with unix_epoch_time as the name.

thanks.

**Comment by Beeez** [comment]
Was also posted here too, even after updating I still have the same issue as well.

https://github.com/nextcloud/server/issues/13239

**Comment by violoncelloCH** [comment]
thank you for reporting
closing as duplicate of #13239
