### ISSUE TITLE
Activity log debug

### ISSUE THREAD

**Issue by charwavid** [nextcloud/server#14107]
The newly installed nextcloud, the calendar app is not installed by default, how can I create a calendar Activity log?

url:https://demo.nextcloud.com/uopoj2ei
![20190208142526](https://user-images.githubusercontent.com/7514841/52463169-e8b62380-2bb0-11e9-87d2-60fdbd008751.png)

**Comment by MorrisJobke** [comment]
The CalDav endpoint is part of the server and can be disabled. That one creates the default calendar. The calendar app itself is only a caldav client to show you the content of this. This the entry is fully correct and works as intended.

**Comment by charwavid** [comment]
Even though the CalDav endpoint is part of the server, the calendar application is installed by default, saving data from being mapped. What do you think?

**Comment by MorrisJobke** [comment]
> Even though the CalDav endpoint is part of the server, the calendar application is installed by default, saving data from being mapped. What do you think?

I don't understand this. What do you mean? The activity entry should be avoided to save space?

**Comment by charwavid** [comment]
I just thought that since the calendar application is not there, then this activity log is created out of thin air, a lot.
