### ISSUE TITLE
PHP errors with external storage provider STACK

### ISSUE THREAD

**Issue by Obscurax** [nextcloud/server#14109]
### Steps to reproduce
1. Add STACK as an external storage provider.
2. Upload files to STACK directly.

### Expected behaviour
1. No PHP errors in the logs.
2. Files show up in Nextcloud.

### Actual behaviour
I'm seeing PHP errors repeatedly, making it hard to analyze the logs when something else is wrong.
Once I remove STACK as an external storage provider the errors stop. 

Syncing via clients and downloading/uploading via the Nextcloud web interface to the external provider is working. When files are uploaded to STACK directly they show up as 0kb in Nextcloud (web and clients).

### Server configuration

**Operating system**:
Ubuntu 18.04.1 LTS
**Web server:**
nginx 1.15.8
**Database:**
MariaDB 10.3.12
**PHP version:**
PH 7.3.2-1
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 15.0.2
**Where did you install Nextcloud from:**
Shell script.
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, WebDAV
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Error PHP	Undefined variable: response at /var/www/nextcloud/lib/private/Files/Storage/DAV.php#283
Error PHP	Undefined offset: 1 at /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Xml/Element/Response.php#237
Error PHP	Undefined index: {DAV:}status at /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Xml/Element/Response.php#236
```
</details>

I've found these issues on Github with similar errors:  #11818 #1228

**Comment by noci2012** [comment]
And the WebDav issue with Alfresco was never cleared, now still on15.0.4......
(Sharepoint access also fails)....
Note: the Config screens show a green dot on the left of entries
The File handler complete fails.

**Comment by noci2012** [comment]
AFAICT these error are related:
Error	cron	TypeError: Argument 1 passed to OCA\GroupFolders\Versions\VersionsBackend::getVersionsFolder() must be of the type integer, string given, called in /.../htdocs/apps/groupfolders/lib/Versions/VersionsBackend.php on line 154		21 minutes ago
Error	PHP	Array to string conversion at /.../htdocs/lib/private/App/DependencyAnalyzer.php#356		24 minutes ago
Error	PHP	Undefined offset: 1 at /data/WWW/.../htdocs/3rdparty/sabre/dav/lib/DAV/Xml/Element/Response.php#237		24 minutes ago
Error	PHP	Undefined index: {DAV:}status at /.../htdocs/3rdparty/sabre/dav/lib/DAV/Xml/Element/Response.php#236		24 minutes ago
Error	PHP	Undefined offset: 1 at /.../htdocs/3rdparty/sabre/dav/lib/DAV/Xml/Element/Response.php#237		24 minutes ago
Error	PHP	Undefined index: {DAV:}status at /.../htdocs/3rdparty/sabre/dav/lib/DAV/Xml/Element/Response.php#236		24 minutes ago

**Comment by skjnldsv** [comment]
Still occurring?
