### ISSUE TITLE
[NC 15.04] Password protected shared folder (via link) - Collabora Online document won't load

### ISSUE THREAD

**Issue by Peac** [nextcloud/server#14102]
### Steps to reproduce
1. Create a folder on NC 15.04 with a Collabora Online document in it
2. Share the folder via link with write permissions and set a password to protect it
3. Open the link (in a private window or another browser) and click on the document with in it
4. Type any name in
5. Wait 

### Expected behaviour
The document should load and be displayed.

### Actual behaviour
The document does not load. At the top two "user" circles pop up, like two users would edit the document (but it is only one).

**When I try the same steps without a password protection everything works as expected.**

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.29

**Database:** MariaDB 10.1.38

**PHP version:** PHP 7.2 - 7.2.10

**Nextcloud version:** 15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>

<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>

<summary>App list</summary>

 - activity: 2.8.2
  - audioplayer: 2.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.0
  - serverinfo: 1.5.0
  - spreed: 5.0.2
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0

</details>

**Nextcloud configuration:**
<details>

<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxxxxxxxxxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.peacetm.de",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "check_for_working_webdav": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font",
            "OC\\Preview\\Movie"
        ],
        "cipher": "AES-256-CFB",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "versions_retention_obligation": "auto",
        "updater.release.channel": "production",
        "loglevel": 2,
        "0": "logfile\" => \"nextcloud.log",
        "maintenance": false,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "simpleSignUpLink.shown": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 65

**Operating system:** Ubuntu Desktop 18.04

**Comment by flo269** [comment]
Seems like a duplicate of [this bug](https://github.com/nextcloud/richdocuments/issues/408).

**Comment by Peac** [comment]
True. Will close this one in favour of https://github.com/nextcloud/richdocuments/issues/408
