### ISSUE TITLE
Remote instance autocomplete at federation

### ISSUE THREAD

**Issue by schmidtch89** [nextcloud/server#14110]
### Steps to reproduce
1. Add instance A as federated server in instance B.
2. Add instance B as federated server in instance A.
3. Wait for the magic until both instances will be marked green.
4. Share a file and type a part of the federation address into the search field.

### Expected behaviour
The full federation address should appear from the autocomplete feature while typing.

### Actual behaviour
Some users from the remote instance will not appear in autocomplete feature of the local instance. If you know the full federation address, you can still share files with unknown users.

### Server configuration

**Operating system**: Debian Jessie

**Web server:** Apache/2.4.10

**Database:** MySQL 5.5.62

**PHP version:** 7.2.14

**Nextcloud version:** 15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14

**Where did you install Nextcloud from:** Web-Installer

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bookmarks: 0.16.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - twofactor_u2f: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - spreed
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
 "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "15,30",
        "versions_retention_obligation": "15,30",
        "loglevel": 3,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
```
</details>

**Are you using external storage, if yes which one:** no external storage

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no external user-backend

### Client configuration
**Browser:** Chrome 71, Firefox 65

**Operating system:** Windows 7, Windows 10

#### Web server error log
No relevant errors found.

#### Nextcloud log (data/nextcloud.log)
No errors regarding federation services.

**Comment by aignerat** [comment]
try the occ-commands: sudo -u www-data php -f occ dav:sync-system-addressbook instance1,instance2
sudo -u www-data php -f occ federation:sync-addressbooks instance1,instance2
change www-data to the user your nextcloud uses and the instances, sometimes it also works without using instance1/2

**Comment by skjnldsv** [comment]
Yep, I cannot reproduce the issue.It just require a full sync which you can trigger with the command above :)

**Comment by aignerat** [comment]
just a final sidenode, sometimes it helps to add the server itself in the configuration:

server 1 config:
server1.contoso.com
server2.contoso.com

s2 config:
server1.contoso.com
server2.contoso.com

regards chris
