### ISSUE TITLE
After upgrading from NC 14 to 15 template file not found

### ISSUE THREAD

**Issue by tsybanov** [nextcloud/server#14115]
**Bug report created even a temporary solution exists**
Problem resolved by this idea:
https://forum.owncloud.org/viewtopic.php?p=104222#p104222

### Steps to reproduce
Upgrade NC from 14 to 15 versions

### Expected behaviour
Working conditions

### Actual behaviour
Critical error with the message:
> "Internal Server Error error: "template file not found: template:layout.guest"

**Logs:**
{
“reqId”: “yOdcbRuRou4qk6h2WYB6”,
“level”: 3,
“time”: “2019-01-23T00:20:49+00:00”,
“remoteAddr”: “x.x.x.x”,
“user”: “user”,
“app”: “core”,
“method”: “GET”,
“url”: “/disk/index.php/apps/files/”,
“message”: {
“Exception”: “Exception”,
“Message”: “template file not found: template:layout.guest”,
“Code”: 0,
“Trace”: [
{
“file”: “/var/www/html/disk/lib/private/legacy/template.php”,
“line”: 180,
“function”: “find”,
“class”: “OC\Template\TemplateFileLocator”,
“type”: “->”,
“args”: [
“layout.guest”
]
},
{
“file”: “/var/www/html/disk/lib/private/legacy/template.php”,
“line”: 87,
“function”: “findTemplate”,
“class”: “OC_Template”,
“type”: “->”,
“args”: [
“”,
“core”,
“layout.guest”
]
},
{
“file”: “/var/www/html/disk/lib/private/TemplateLayout.php”,
“line”: 119,
“function”: “__construct”,
“class”: “OC_Template”,
“type”: “->”,
“args”: [
“core”,
“layout.guest”,
“”,
false
]
},
{
“file”: “/var/www/html/disk/lib/private/legacy/template.php”,
“line”: 211,
“function”: “__construct”,
“class”: “OC\TemplateLayout”,
“type”: “->”,
“args”: [
“error”,
“”
]
},
{
“file”: “/var/www/html/disk/lib/private/Template/Base.php”,
“line”: 132,
“function”: “fetchPage”,
“class”: “OC_Template”,
“type”: “->”,
“args”: []
},
{
“file”: “/var/www/html/disk/lib/private/legacy/template.php”,
“line”: 360,
“function”: “printPage”,
“class”: “OC\Template\Base”,
“type”: “->”,
“args”: []
},
{
“file”: “/var/www/html/disk/index.php”,
“line”: 69,
“function”: “printExceptionErrorPage”,
“class”: “OC_Template”,
“type”: “::”,
“args”: [
{
“class”: “Exception”
},
500
]
}
],
“File”: “/var/www/html/disk/lib/private/Template/TemplateFileLocator.php”,
“Line”: 56,
“CustomMessage”: “–”
},
“userAgent”: “Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36”,
“version”: “15.0.2.0”
}

**Comment by danielkesselberg** [comment]
https://github.com/owncloud/core/issues/8071 don't place a folder called templates into the root directory.

**Comment by rbscycle** [comment]
Upgrade from 13.0.6 to 15.0.4 - failed.  Subsequent upgrade from 13.0.6 to 14.0.7 failed.  Now nothing works.

**Comment by Tsybanov** [comment]
@daniel

> [owncloud/core#8071](https://github.com/owncloud/core/issues/8071) don't place a folder called templates into the root directory.

Thank you for the information! Unfortunately, I didn't put and move any folders since installation.

**Comment by tsybanov** [comment]
Since my PR with a suggested fix has been closed, I'm asking for help to figure out why I'm getting the internal error every major upgrade even though I didn't modify the release anyhow and my root folder doesn't have /templates

<img width="1070" alt="87095963-c98d4c80-c20f-11ea-9b64-b0157a5734d6" src="https://user-images.githubusercontent.com/5286992/87097081-56d1a080-c212-11ea-9ec3-088e878c99ba.png">

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
