### ISSUE TITLE
Two factor backup code notifications keep coming back even though enforcing is disabled

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#14125]
### Steps to reproduce
1. After upgrade to 15, I enforced TOTP for the admin group. Maybe I did a mistake, because it was suddenly active for everyone
2. Switched of forced TOTP
3. Deleted the notifications manually from the oc_notifications table

### Expected behaviour
After switching off forced TOTP, the notifications should go away.
At least after deleting them from oc_notifications, there should be no more recurring notifications
### Actual behaviour
With each upgrade of Nextcloud, the notifications somehow come back and I have to manually delete them again from oc_notifications, because they really irritate the users.

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Nginx 1.14.0 
**Database:**
Mariadb 1:10.1.34
**PHP version:**
7.2 FPM 7.2.10

**Version:** (see admin page)
1.5.0.4

**Updated from an older version or fresh install:**
updated

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - keeweb: 0.4.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ocsms: 2.1.1
  - password_policy: 1.5.0
  - piwik: 0.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.2.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.3
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_admin: 0.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.0
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - external
  - files_downloadactivity
  - files_external
  - grauphel
  - polls
  - user_external
  - user_ldap`

**The content of config/config.php:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "cron.lockfile.location": "\/var\/www\/chrooted\/jrweb\/data\/ocfiles\/",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "PLAIN",
        "trusted_domains": [
            "cloud.enip.eu",
            "owncloud.uferwerk.org",
            "owncloud.rohr.org",
            "owncloud.drillisch.info",
            "cloud.uferwerk.org",
            "cloud.rohr.org",
            "cloud.infoe.de",
            "cloud.drillisch.info"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "loglevel": 2,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": false,
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "overwrite.cli.url": "https:\/\/cloud.rohr.org",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
#### Client configuration
(affects all clients)

##### Web server error log
```
Insert your webserver log here
```

##### Server log (data/nextcloud.log)
```
Insert your server log here
```

##### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
```

**Comment by rullzer** [comment]
There is a job run on every update to remind people that have 2FA enabled that they should generate their backup codes. So from that point of view it is working as expected.

Can you double check that users that do not have any 2fa enabled get the warning? Because I have no way to trigger this otherwise.

**Comment by vasyugan** [comment]
Of my 118 users, 4 have 2FA enabled, but there were over 80 notifications.
Did a occ twofactorauth:cleanup for everyone now, hope this helps.

**Comment by rullzer** [comment]
@ChristophWurst something to look into

**Comment by ChristophWurst** [comment]
> Did a occ twofactorauth:cleanup for everyone now, hope this helps.

Was there a provider active before that you had to clean up? What did you pass as provider-id?

**Comment by ChristophWurst** [comment]
>     1. After upgrade to 15, I enforced TOTP for the admin group. Maybe I did a mistake, because it was suddenly active for everyone

FYI: you can only enforce 2FA for all users or have it optional. There is nothing like *enforce TOTP* in Nextcloud.

**Comment by vasyugan** [comment]
> > Did a occ twofactorauth:cleanup for everyone now, hope this helps.
> 
> Was there a provider active before that you had to clean up? What did you pass as provider-id?

Sorry, can't reconstruct it now. Have to see whether it comes back on the next upgrade

**Comment by vasyugan** [comment]
So now the backup code notifications have re-emerged, even without an upgrade. What's going on here?

**Comment by vasyugan** [comment]
I just checked for one of my users who got the notifications, occ twofactorauth:status says:

Disabled providers:
- admin
- backup_codes
- totp
- twofactor_nextcloud_notification


So everything is disabled, and stlll he gets those recurring notifications. Also, not all users are affected, only 80 of my 120 users. But for no group 2FA is enforced and very few people (including myself) have it enabled.

**Comment by vasyugan** [comment]
> > Did a occ twofactorauth:cleanup for everyone now, hope this helps.
> 
> Was there a provider active before that you had to clean up? What did you pass as provider-id?

Not sure what you mean here. When running occ twofactorauth:cleanup I don't pass any ids exect for the user id , or what do you mean?

**Comment by ChristophWurst** [comment]
I checked the code: https://github.com/nextcloud/server/blob/6080d9d80acf0281bfc383b222972346b74e7fe5/apps/twofactor_backupcodes/lib/AppInfo/Application.php#L79-L83 + https://github.com/nextcloud/server/blob/6080d9d80acf0281bfc383b222972346b74e7fe5/apps/twofactor_backupcodes/lib/Listener/ProviderEnabled.php#L58 + https://github.com/nextcloud/server/blob/1a537bc766911a0e56e2f2fe00c4802583078a84/apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php#L64-L88.

This tells me that the backup codes background job is scheduled as soon as a 2FA provider is enabled.

@vasyugan of these affected users, was there anybody that hasn't had 2FA enabled before?

**Comment by ChristophWurst** [comment]
I think we could just listen to the *disable* event (if emitted) and clear all background jobs if the user does not use 2FA anymore. @rullzer would that make sense?

**Comment by vasyugan** [comment]
Am 27.02.19 um 13:31 schrieb Christoph Wurst:
>
> I checked the code:
> https://github.com/nextcloud/server/blob/6080d9d80acf0281bfc383b222972346b74e7fe5/apps/twofactor_backupcodes/lib/AppInfo/Application.php#L79-L83
> +
> https://github.com/nextcloud/server/blob/6080d9d80acf0281bfc383b222972346b74e7fe5/apps/twofactor_backupcodes/lib/Listener/ProviderEnabled.php#L58
> +
> https://github.com/nextcloud/server/blob/1a537bc766911a0e56e2f2fe00c4802583078a84/apps/twofactor_backupcodes/lib/BackgroundJob/RememberBackupCodesJob.php#L64-L88.
>
> This tells me that the backup codes background job is scheduled as
> soon as a 2FA provider is enabled.
>
> @vasyugan <https://github.com/vasyugan> of these affected users, was
> there anybody that hasn't had 2FA enabled before?
>
Probably so, because by mistake, 2FA was enforced for the wrong group.
After that it was immediately switched off. Since then we are plagued by
those recurring notifications

**Comment by ChristophWurst** [comment]
I will have a look in the bugfixing phase of Nextcloud 16.

**Comment by vasyugan** [comment]
@ChristophWurst Where in the database could there be a stale 2FA related entry that triggers the notification to come back all the time? Because it is an annoyance to my users and i would rather not wait for the next major release to fix this.

**Comment by ChristophWurst** [comment]
The job gets schedule when the user enables 2FA. That job can be found in `oc_jobs`.

**Comment by vasyugan** [comment]
> The job gets schedule when the user enables 2FA. That job can be found in `oc_jobs`.

OK, thanks. Found and removed the jobs now. Would be good to see this fixed in a future release. Because it really drives one nuts to see those notifications coming back again and again.

**Comment by rullzer** [comment]
@ChristophWurst yes that would make sense indeed.

**Comment by akaro** [comment]
I got this i I want to login as Admin:

_Zwei-Faktor Authentifizierung
Es konnte nicht eine Deiner Zwei-Faktor-Authentifizierungsmethoden geladen werden. Kontaktiere den Administrator.
Die Zwei-Faktor-Authentifizierung wird erzwungen, wurde jedoch für Dein Konto nicht konfiguriert. Verwende einen Deiner Backup-Codes zum Anmelden, oder wende Dich für Unterstützung an Deinen Administrator.
Backup-Code benutzen_ 

QUESTION: how can i get the Backup-Code?
Because i can`t login as admin.
It is possible to generate it in the CLI for admin? When yes how? :-)

--
sudo -u www-data php occ twofactorauth:admin:generate-code admin
--
result:
There are no commands defined in the "twofactorauth:admin" namespace.                                                                          
  Did you mean this?                                                     
      twofactorauth

**Comment by akaro** [comment]
test

**Comment by akaro** [comment]
test

**Comment by ChristophWurst** [comment]
> There are no commands defined in the "twofactorauth:admin" namespace.

You have to install https://apps.nextcloud.com/apps/twofactor_admin for that to work. You can use the CLI access to download & install the app, then generate a code for the admin user to log in again.

**Comment by ChristophWurst** [comment]
For any other questions, please ask at https://help.nextcloud.com/
