### ISSUE TITLE
Adding CalDAV account fails under macOS High Sierra

### ISSUE THREAD

**Issue by matthias-scheler** [nextcloud/server#14128]
### Steps to reproduce
1. Launch System Preferences under macOS High Sierra
2. Select Internet Accounts
3. Select Add Other Account
4. Select CalDAV Account
5. Change Account Type to Manual
6. Enter User Name, Password and Server Address
7. Click on Sign In

### Expected behaviour
macOS should create a CalDAV account and provide access to the calendar hosted on Nextcloud.

### Actual behaviour
macOS reports "Unable to verify account or password.". The password is however a correct as visible in the web server "access.log" log file:

```
2001:**REST OF IPV6 ADDRESS REMOVED** - - [09/Feb/2019:14:23:28 +0000] "PROPFIND /remote.php/dav/principals/users/**USER NAME REMOVED**/ HTTP/1.1" 401 5418 "-" "Mac+OS+X/10.13.6 (17G5019) CalendarAgent/399.2.2"
2001:**REST OF IPV6 ADDRESS REMOVED**- - [09/Feb/2019:14:23:29 +0000] "PROPFIND /remote.php/dav/principals/users/**USERNAME REMOVED**/ HTTP/1.1" 207 2441 "-" "Mac+OS+X/10.13.6 (17G5019) CalendarAgent/399.2.2"
```

### Server configuration

**Operating system**:
Debian 9.7

**Web server:**
Apache 2.4.25

**Database:**
MariaDB 10.1.37

**PHP version:**
7.0.33

**Nextcloud version:** (see Nextcloud admin page)
15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Originally Owncloud, migrated to Nextcloud a long time ago. Recently updated from Nextcloud 14.0.6

**Where did you install Nextcloud from:**

Originally a manual download from the Owncloud and later Nextcloud website. Recently the updater downloaded the files automatically.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "**HOSTNAME REMOVED**"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/***HOSTNAME REMOVED***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
CalendarAgent/399.2.2

**Operating system:**
macOS 10.13.6 (High Sierra)

#### Web server error log
<details>
<summary>Web server error log</summary>

No recent entries in Apache's ``error.log' logfile for the Nextcloud virtual server

An attempt to login produces the following line in the "access.log" log file:
```
2001:**REST OF IPV6 ADDRESS REMOVED** - - [09/Feb/2019:14:23:58 +0000] "PROPFIND /remote.php/dav/principals/users/**USER NAME REMOVED**/ HTTP/1.1" 207 2443 "-" "Mac+OS+X/10.13.6 (17G5019) CalendarAgent/399.2.2"
```

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

The failed attempt to setup an account does *not* produce any output in "nextcloud.log".
</details>

#### Browser log
<details>
<summary>Browser log</summary>

When I try to setup the account the Internet Account setup dialog reports:

```
Unable to verify username or password.
```
</details>

**Comment by skjnldsv** [comment]
Please head over the documentation and make sure you have set everything properly. macOS is known to behave weirdly with dav.
https://docs.nextcloud.com/server/stable/user_manual/pim/sync_osx.html#troubleshooting
https://docs.nextcloud.com/server/stable/admin_manual/issues/general_troubleshooting.html?highlight=macos#service-discovery
https://help.nextcloud.com/t/high-sierra-address-book-does-not-sync/23007

**Comment by matthias-scheler** [comment]
I've read through these document ands not of the tips help:
- Using the "Advanced" configuration option makes no difference because the "Manual" option detected the correct URLs anyway (there are no 404 errors in the access log).
- My server (only) supports HTTPS and has a valid certificate that Chrome, Firefox and Safari accept.
- I've disabled "mod_dav" and "mod_deflate" but it didn't make a difference.
- Rewrite rules are active on the virtual server and have been before.

The problem is exactly before:
- Authentication works (401 followed by 207)
- macOS's calendar client detects the correct URL (no 404)
- It complains that it is "Unable to verify account name or password."

**Comment by skjnldsv** [comment]
Have you used an app password?

**Comment by matthias-scheler** [comment]
I tried with an app password and the default account password and neither worked.

**Comment by skjnldsv** [comment]
Can you create a new test user and try with that user?
Just saw you were using oc before and upgraded. A working clean user might indicate a broken setting on your account somewhere :)

**Comment by matthias-scheler** [comment]
I've created a new user and get exactly the same problem (except that it takes less time to fail).

Is there a way I can dump out the response that Nextcloud is sending? With HTTPS in place I cannot simply Wireshark it.

About the Owncloud history:
Can I somehow export the data (including all users) and reimport it into a Fresh instance to get rid of legacy problems?

**Comment by skjnldsv** [comment]
> Can I somehow export the data (including all users) and reimport it into a Fresh instance to get rid of legacy problems?

I cannot assume there is a legacy problem actually.
Our migration path is pretty solid and we rarely get issues. But since we're on an issue tracker, of course, the stats are biased and sometimes we want to make sure this is indeed not an issue ;)

Okay, I have a mac vm somewhere, could you post a few screenshot of the account process on macos so I can try and reproduce the issue?
if I can login, then it will narrow the setup to your instance :)

**Comment by skjnldsv** [comment]
Also, one last test: https://github.com/nextcloud/server/issues/7519#issuecomment-480429363

**Comment by matthias-scheler** [comment]
I quit the System Preferences program, tried to configure an account using "Advanced" as described in the post with a shiny new app password. And I still got the exact same error messages. I've attached a screen shot.

![bug14128-1](https://user-images.githubusercontent.com/47478038/58881126-6b6b6d00-86d1-11e9-914c-746645ba3520.png)

**Comment by matthias-scheler** [comment]
BTW: Would it help if I provided a temporary account on my calendar server for testing purposes?

**Comment by skjnldsv** [comment]
@matthias-scheler definitely :)
skjnldsv@protonmail.com

**Comment by matthias-scheler** [comment]
I've sent the login details to the above e-mail address.

**Comment by skjnldsv** [comment]
Sorry, I've been completely overbooked lately!
I'll try to check on it soon! :see_no_evil:

**Comment by matthias-scheler** [comment]
I still have the exact same problem with NextCloud 15.0.11.

**Comment by ph00lt0** [comment]
I am on the latest version (16.0.4) experiencing the exact same issue.

**Comment by skjnldsv** [comment]
> adding the well-known locations fixed the issue for me:

the last two? Or had the other a use for this issue as well?

**Comment by ph00lt0** [comment]
> the last two? Or had the other a use for this issue as well?

I put the whole script because this was the suggested answer from the Nextcloud documentation when using a sub folder for your installation. I have not tried without adding the other lines. It might be needed for Mac/i-OS

**Comment by matthias-scheler** [comment]
My _.htaccess_ contains the necessary entries.

I also highly doubt that this or something similar is the cause of *my* issue because there are no 404 errors in my web server log file. macOS finds the correct URL, succeeds to authenticate and then gives up after receiving a 20x response from the server.

**Comment by kesselb** [comment]
> Is there a way I can dump out the response that Nextcloud is sending? With HTTPS in place I cannot simply Wireshark it.

If you are still interested: https://mitmproxy.org 

https://blogs.msdn.microsoft.com/aaddevsup/2018/04/11/tracing-all-network-machine-traffic-using-mitmproxy-for-mac-osx/ this looks like a decent guide.

**Comment by kesselb** [comment]
The only difference between your screenshot and this one https://github.com/nextcloud/server/issues/7519#issuecomment-360936289 is that you opened  "add caldav account" dialog from internet accounts and the other user from calendar app. I don't think it's connected but ...

**Comment by kesselb** [comment]
> > Is there a way I can dump out the response that Nextcloud is sending? With HTTPS in place I cannot simply Wireshark it.
> 
> If you are still interested: https://mitmproxy.org
> 
> https://blogs.msdn.microsoft.com/aaddevsup/2018/04/11/tracing-all-network-machine-traffic-using-mitmproxy-for-mac-osx/ this looks like a decent guide.

There is a simpler way :tada: [Here](https://github.com/nextcloud/server/issues/16947) is another user with a similar issue. He used [mod_dumpio](https://httpd.apache.org/docs/2.4/mod/mod_dumpio.html) for apache2 to record the traffic.

**Comment by matthias-scheler** [comment]
I remember trying "mod_dumpio". But I couldn't get any useful information with it. I'm afraid I cannot remember the details.

**Comment by skjnldsv** [comment]
So, I was able to directly sync on your instance @matthias-scheler!
Sorry I took so long :(

Just on system settings, click on "internet accounts" > add new > carddav > automatic. Then use `yourUserId@yourDomain.com`, generate an app password on your nextcloud instance, use this app password and that's it! :D

**Comment by matthias-scheler** [comment]
I've tried with an App password several times before. It didn't work for me and still doesn't work.

What client did you use? The iCal application distributed with macOS High Sierra?

**Comment by skjnldsv** [comment]
Yep, no specific app, pure macOS install. Nothing more :)

**Comment by matthias-scheler** [comment]
I've done some more experimentations. If I use a another (non LDAP) account on that Mac it works fine. So it is clearly some problem with that system and/or account.

**Comment by skjnldsv** [comment]
> I've done some more experimentations. If I use a another (non LDAP) account on that Mac it works fine. So it is clearly some problem with that system and/or account.

What do you mean?
You mean it is coming from Macos?
Is this issue only applying to ldap accounts? What type was the account you gave me?

**Comment by matthias-scheler** [comment]
I've got a Linux server which exports UNIX users via LDAP and their home directories via NFS.
The Mac system on which I encountered this bug is configured as an LDAP and NFS client of that Linux server. The account that I'm normally using on that mchine is such an LDAP and NFS account. Accessing the Nextcloud instance from that account doesn't work. If I however use the local macOS account which I use to unlock the Filevault disk encryption I can setup the calendar account without problems. So the problem is almost certainly a problem with macOS's LDAP or NFS support.

My Nextcloud instance does **not** use LDAP. It only uses accounts created and managed via Nextcloud.

BTW: Can I delete your test account or do you still need it?

**Comment by skjnldsv** [comment]
Okay, weird! :)
Yes you can! Glad e figured things out! Thanks for the help!!

**Comment by matthias-scheler** [comment]
> Yes you can! Glad e figured things out! Thanks for the help!!

Thanks a lot for you help with tracking this down!
