### ISSUE TITLE
Old Version of Excel Sheet is sporadically provided

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#14137]
### Actual behaviour
Sometimes I get an old version of an excel file. It's 5 versions old or so. And if you don't regognize it, you will override the following 5 versions. 

I see this behavior on different two servers, with the latest nexcloud version. The problem occurs with collabora and onlyoffice as well as with the nextcloud Anbdroid App. 

### Steps to reproduce
This is a problem, I can't reproduce it. 

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
15.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by skjnldsv** [comment]
Hi,

What do you mean by "Sometimes I get an old version of an excel file." ?
Does it appear? Do you save as excel file and it's an old version that is used as file format?

**Comment by jakobroehrl** [comment]
I work with a group of people on one excel, and sometimes a user got an old version of this excel. 
But I think we could close this for now. In the last month and with onlyoffice it was working really well.
