### ISSUE TITLE
Nextcloud does not always respect `overwriteprotocol`

### ISSUE THREAD

**Issue by zroug** [nextcloud/server#14132]
### Steps to reproduce
1. Setup Nextcloud behind a reverse proxy. It must be configured so that it can only be accessed via https from the public internet. The reverse proxy must access Nextcloud via http internally.
2. Set `overwritehost` and `overwriteprotocol` to the correct values. That means `overwriteprotocol` must be set to `https`.
3. Services discovery for DAV will not work correctly. You will get a warning at `/settings/admin/overview`. This is because Nextcloud tries to redirect to http.

### Expected behaviour
Nextcloud should always redirect to https when  `overwriteprotocol` is set to `https`.

### Actual behaviour
Nextcloud redirects to http for some things.

### Notes
This is related to https://github.com/nextcloud/docker/issues/577. The proposed fix there is to configure `overwritehost` and `overwriteprotocol` in https://github.com/nextcloud/docker/pull/527 but that isn't enough to make service discovery work. https://github.com/nextcloud/docker/issues/577 has various workarounds proposed but I think the real issue is in Nextcloud itself.

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** 15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** Official Docker image

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Default apps.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Default configuration except `overwritehost` and `overwriteprotocol`.
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 65

**Operating system:** Various

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/d40b21ac815b8088a5d0b51a6d48b39ed754631a/.htaccess#L49-L50

Redirect for service discovery is triggered here. If the server is running as http redirect is done to http. We cannot evaluate `overwriteprotocol` at this place. I think we could check in htaccess if some information are forwarded (e.g. HTTP_FORWARDED_HOST, HTTP_FORWARDED_PROTO) from your reverse proxy but this quite complex.

I guess the best way to solve your issue is to setup redirects for service discovery on your reverse proxy.  Would that work for you?

**Comment by ffried** [comment]
Some of us already do that (see the two most recent comments in https://github.com/nextcloud/docker/issues/577 for example). I agree that the `overwriteprotocol` cannot be evaluated in the `.htaccess` itself, but would it be possible to generate a different `.htaccess` based on what `overwriteprotocol` specifies (like the OP mentioned in https://github.com/nextcloud/docker/issues/577)?

I'd still rather have NextCloud handling the redirect correctly. But if that's really too much hassle, than maybe put examples for the necessary configuration somewhere in the installation docs?

**Comment by zroug** [comment]
I agree with @ffried. It also looks like there are more than those two redirects in `.htaccess`. So maybe they are affected too.
Currently the documentation says `overwriteprotocol` affects URLs that are generated by Nextcloud. That sounds like it should work for all URLs and therefore exceptions to this rule should be documented there.

**Comment by kesselb** [comment]
I prepared a pull request for the documentation. Could you share your solutions? https://github.com/nextcloud/documentation/pull/1297

**Comment by SeaLife** [comment]
Hello,

the class `server/lib/private/URLGenerator.php` is generating http:// urls if running behind a reverse proxy regardless of the overwriteprotocol setting. Maybe this will fix many issues?

Regards
SeaLife

**Comment by kesselb** [comment]
> the class `server/lib/private/URLGenerator.php` is generating http:// urls if running behind a reverse proxy regardless of the overwriteprotocol setting.

I cannot confirm that. `URLGenerator` is using the router to generate urls. https://github.com/nextcloud/server/blob/0c77cd21f94dd9922e0e04ec4c7e99eff9376e07/lib/private/Route/Router.php#L84-L85

Router itself use the values from `getServerHost()` and `getServerProtocol()` as context for url generation. 
https://github.com/nextcloud/server/blob/bf167ad3acb2be4083cd96d58bf13fba83ad9e39/lib/private/AppFramework/Http/Request.php#L884

https://github.com/nextcloud/server/blob/bf167ad3acb2be4083cd96d58bf13fba83ad9e39/lib/private/AppFramework/Http/Request.php#L688

Both methods are using the values from overwrite* if you set them in config.php.

**Comment by zroug** [comment]
> I prepared a pull request for the documentation. Could you share your solutions? [nextcloud/documentation#1297](https://github.com/nextcloud/documentation/pull/1297)

Sure. My workaround was to modify the `VirtualHost` config from Apache and add the lines

```
ServerName https://cloud.example.com
ServerAlias *
UseCanonicalName On
```

That makes Apache to act like it was accessed from this URL, works for all redirects and makes `overwriteprotocol` and `overwritehost` obsolete.

Another popular workaround in https://github.com/nextcloud/docker/issues/577 is to modify the `.htaccess` by changing the lines

```
RewriteRule ^\.well-known/carddav /remote.php/dav/ [R=301,L]
RewriteRule ^\.well-known/caldav /remote.php/dav/ [R=301,L]
```

to

```
RewriteRule ^\.well-known/carddav https://%{SERVER_NAME}/remote.php/dav/ [R=301,L]
RewriteRule ^\.well-known/caldav https://%{SERVER_NAME}/remote.php/dav/ [R=301,L]
```

This has the advantage that only the `.htaccess` that is included in Nextcloud needs to be modified but it has to be done for all affected URLs. I haven't tried anything with Nginx.

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html

Added a section about service discovery to the documentation. Okay for you to close this issue?

**Comment by zroug** [comment]
Yes. I think this solution is not perfect but this issue isn't a bug anymore, so I'm okay with closing it.

**Comment by myrdd** [comment]
Thank you for putting the workaround into the docs (https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#service-discovery). The suggested solution for Apache2 worked for me. However, I'm now using the following Apache config line on my reverse proxy, which will change any `Location` response header from `http` to `https`:

    Header edit Location ^http://nextcloud.example/ https://nextcloud.example/

Of course, change `nextcloud.example` to your real domain name.

Found on Stackexchange:  
https://serverfault.com/questions/626335/how-do-you-force-an-apache-load-balancer-to-rewrite-http-302-redirects-to-https  
https://serverfault.com/questions/388927/apache-reverseproxypass-redrects-to-http-rather-than-https

**Comment by kesselb** [comment]
@myrdd why do you prefer this approach? There is a way to tell nextcloud to generate urls with the right protocol: `overwriteprotocol`.

**Comment by myrdd** [comment]
> There is a way to tell nextcloud to generate urls with the right protocol: `overwriteprotocol`.

Yes, I'm using that, but as you said above (https://github.com/nextcloud/server/issues/14132#issuecomment-471188736), `overwriteprotocol` cannot be evaluated in the `.htaccess` file.

> why do you prefer this approach?

I operate both the Nextcloud instance and the reverse proxy. I want the reverse proxy to encrypt everything. So now I use that approach for all the services behind the reverse proxy, just in case any other service ”forgets“ to use https rather than http for `Location` redirections.
