### ISSUE TITLE
Minor german translation bugs in "add" menu in files app

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#14133]
### Steps to reproduce
1. In a "de" localized nextcloud files app click on "+"

A) 2. Choose to create a new text file
B) 2. Choose to create a new draw.io diagram

### Expected behaviour
A) The default file label should be "Neue Textdatei.txt"
B) The default file label should be "Neues Diagramm.xml"

### Actual behaviour
A) The default file label is "Neue Textdatei file.txt"
B) The default file label is "New diagram.xml"

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
15.0.4

**Comment by skjnldsv** [comment]
Hello!
Our translations are managed on [transifex.com](https://transifex.com/nextcloud/nextcloud/translate/)
Please check it there :)
