### ISSUE TITLE
Cannot upgrade from NC13 to NC14

### ISSUE THREAD

**Issue by jiml8** [nextcloud/server#14134]
To begin, I must manually update because the automatic updater does not work on FreeBSD and/or Nas4Free, which is my host.  Historically this has not been a problem.  Now, it is.

I tried in late november to upgrade to 14.0.4 and it failed this way.  Today I tried again with 14.0.7.

### Steps to reproduce
1. download NC14, place in www directory, move in-place nextcloud out of the way, untar NC14, change owner:group to www:www, copy config.php from in-place nextcloud
2. from a web browser, select any Nextcloud function
3. Wait for upgrade to complete after the web browser informs that upgrade has started.

### Expected behaviour
Tell us what should happen
Upgrade should happen

### Actual behaviour
Tell us what happens instead
Upgrade fails claiming database or disk is full.  The disk is a RAID6 with roughly 20TB still available.  The sqlite database occupies 378412032 bytes which is nowhere near the limits.

This is the message:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_filecache AS SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions, checksum FROM oc_filecache': SQLSTATE[HY000]: General error: 13 database or disk is full

Detailed logs 
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Not a mysql database -> nothing to do

Repair step: Repair SQLite autoincrement

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_filecache AS SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions, checksum FROM oc_filecache': SQLSTATE[HY000]: General error: 13 database or disk is full

The update was unsuccessful. Please report this issue to the Nextcloud community.
### Server configuration

**Operating system**:
FreeBSD11

**Web server:**
lighthttpd 1.4.45

**Database:**
sqlite3
**PHP version:**
7.1.8
**Nextcloud version:** (see Nextcloud admin page)
13.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:**
from older nextcloud
**Where did you install Nextcloud from:**
downloaded from nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - apporder: 0.6.0
  - audioplayer: 2.4.1
  - bookmarks: 0.12.2
  - bruteforcesettings: 1.3.0
  - comments: 1.3.0
  - contacts: 2.1.5
  - dav: 1.4.7
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_external: 1.4.1
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - firstrunwizard: 2.2.1
  - gallery: 18.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextcloud_announcements: 1.2.0
  - notes: 2.5.1
  - notifications: 2.1.2
  - oauth2: 1.1.1
  - ownbackup: 18.11.0
  - passman: 2.1.4
  - password_policy: 1.3.0
  - previewgenerator: 1.1.0
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - survey_client: 1.1.0
  - systemtags: 1.3.0
  - theming: 1.4.5
  - twofactor_backupcodes: 1.2.3
  - twofactor_totp: 1.4.1
  - updatenotification: 1.3.0
  - weather: 1.5.5
  - workflowengine: 1.3.0
Disabled:
  - encryption
  - user_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "trusted_domains": [
            "192.168.0.27",
            "jsslan.ddns.net",
            "192.168.2.27",
            "184.176.98.91"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "filesystem_check_changes": 1,
        "overwrite.cli.url": "https:\/\/jsslan.ddns.net:12080\/owncloud",
        "dbtype": "sqlite3",
        "version": "13.0.6.1",
        "installed": true,
        "forcessl": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes.  Local, and I have an NFS mount from another machine which I also handle as local in nextcloud

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
webdav

### Client configuration
**Browser:**
Chromium

**Operating system:**
Mageia Linux 6
### Logs
#### Web server error log
<details>

<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: SQLSTATE[HY000]: General error: 11 database disk image is malformed in /mnt/VD01/www/nextcloud/lib/private/DB/Connection.php:64
Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: PHP Fatal error: Uncaught Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred while executing 'PRAGMA journal_mode = WAL':
Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: #4 /mnt/VD01/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOSqlite\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrin in /mnt/VD01/www/nextcloud/lib/private/DB/Connection.php on line 64
Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: #3 /mnt/VD01/www/nextcloud/lib/private/DB/Connection.php(151): Doctrine\DBAL\Connection->setTransactionIsolation(2)
Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: #2 /mnt/VD01/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): OC\DB\Connection->executeUpdate('PRAGMA read_unc...')
Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: #1 /mnt/VD01/www/nextcloud/lib/private/DB/Connection.php(216): Doctrine\DBAL\Connection->executeUpdate('PRAGMA read_unc...', Array, Array)
Feb 10 11:08:40	jssnas	lighttpd[69564]: (mod_fastcgi.c.2543) FastCGI-stderr: #0 /mnt/VD01/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(992): OC\DB\Connection->connect()
</details>

**Comment by jiml8** [comment]
I was able to update by editing the database.  I removed the NFS mount from the external filesystems, which greatly reduced the size of oc_filecache, then I discovered that oc_activity had approximately 300K entries in it.  I remove about 250K of these.

I then attempted an upgrade of the basic nextcloud, with none of my customization apps applied.  The upgrade went through.

I then manually added my customizations back in, and it is working.  This was, however, a painful exercise.  

It seems to me that activities should get pruned after awhile.  I still don't understand why the database maxxed out on the upgrade attempt; the apparent limits are apparently much higher than what I have in mine.

**Comment by danielkesselberg** [comment]
I'm not sure how this problem is related to nextcloud? :thinking: 

Here is a similar report for owncloud https://forum.owncloud.org/viewtopic.php?t=19413

Looks like the best advice is to use mysql/postgres instead of sqlite https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/db_conversion.html

**Comment by MorrisJobke** [comment]
> Looks like the best advice is to use mysql/postgres instead of sqlite

Looking at the number this is most likely the best advice. Beside that it's a setup issue and more something for the forums at https://help.nextcloud.com

Thanks for the feedback nevertheless.
