### ISSUE TITLE
Nextcloud detects wrong php version

### ISSUE THREAD

**Issue by truelai** [nextcloud/server#14147]
### Steps to reproduce
1. Install php7.2 or 7.3
2. Look at "Overview" in admin
3. Note complaint: You are currently running PHP 7.0.33-1+ubuntu16.04.1+deb.sury.org+1. Upgrade your PHP version to take advantage of performance and security updates provided by the PHP Group as soon as your distribution supports it.

### Expected behaviour
It should detect the version actually installed. 

### Actual behaviour
It shows a different version.  (PHP 7.0.33-1+ubuntu16.04.1+deb.sury.org+1)

` There are some warnings regarding your setup.
You are currently running PHP 7.0.33-1+ubuntu16.04.1+deb.sury.org+1. Upgrade your PHP version to take advantage of performance and security updates provided by the PHP Group as soon as your distribution supports it.
`
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** apache

**Database:** mysql

**PHP version:** 
```root@nextcloud:~# /usr/bin/php -v
PHP 7.3.2-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Feb  8 2019 10:50:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.2, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.2-2+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
```

**Nextcloud version:** 15.0.4

**Comment by j-ed** [comment]
@truelai I assume that you're mixing-up two different things here. Nextcloud primarily uses the Apache webserver PHP module and shows that version and not the PHP CLI version, to which you are referring.
If you want to check which PHP module version has been installed, create a file named e.g. **info.php** with the following line: `<?php phpinfo() ?>` and place it in your  web server root. Then access this file with a web browser to get the details displayed, like `https://<your-server-fqdn/info.php`).

**Don't forget to delete the file afterwards for security reasons!!**

**Comment by danielkesselberg** [comment]
Works here. Looks like a configuration issue to me. Please use https://help.nextcloud.com for configuration issue.

**Comment by truelai** [comment]
Right you are. I forgot to disable the old php-apache mod after enabling the new one.

For anyone else:
```
sudo a2dismod php7.0 
sudo a2enmod php7.3 
```
