### ISSUE TITLE
Nextcloud Content Caching

### ISSUE THREAD

**Issue by AnderCrafter** [nextcloud/server#14145]
It would be cool to localy Cache Data from Remote Nextcloud Server

**Comment by MorrisJobke** [comment]
What do you mean with that? The Nextcloud desktop client does this for whole folders and the mobile apps keep downloaded files to not re-download them.

**Comment by AnderCrafter** [comment]
No, for many local computers in a Network

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Also this ticket is more for the desktop client. There it is often referred to as LAN sync. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
