### ISSUE TITLE
Fresh install of 15 throws DB error

### ISSUE THREAD

**Issue by monochromec** [nextcloud/server#14140]
Error is 
PDOException: SQLSTATE[HY000]: General error: 1 no such table: appconfig in /opt/webapps/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104

Full dump of the first stack trace is on pastebin: https://pastebin.com/79VJ9cD5

DB driver is sqlite. More than happy to provide more details including config.php as required.

Plattform is PHP 7.3.2 running on Alarm.
Also happens on Debian 9.7 running PHP 7.0.33.

Command was: php occ maintenance:install --database=nextcloud (executed as the correct user of course)

**Comment by kesselb** [comment]
`php occ maintenance:install --database=nextcloud`

Are u sure about that? Valid values for database are: sqlite, mysql, pgsql, oci (https://github.com/nextcloud/server/blob/bdf48d8b4ed3d4a78f133331ccf3a536358638f4/lib/private/Setup.php)

**Comment by monochromec** [comment]
Hi Daniel, Thanks for your feedback. Unfortunately, there seems to be something *really* wrong with the code base as "php occ --help" fails with the same error message.

**Comment by monochromec** [comment]
After spending some cycles on a cursory RCA, I noticed an interesting behaviour: occ loads console.php which in turn requires base.php. As part of the execution, base.php executes OC::init() which tries to load the enabled apps for the user by checking the configuration and trying to execute a subsequent query on a DB which has not been created yet. Hence the backtrace. Am I missing something?

**Comment by kesselb** [comment]
Delete your config.php and try again?

**Comment by monochromec** [comment]
Interesting.... 

Normally you would expect to configure an application *before* you ran it the first time and *not* afterwards.  :-)

But In this case it was an oversight on my side: the parameter "installed" in the config.php file was still set to true. That's probably the reason why the stack tried to open a database instead of creating a new one. 

@Daniel: In case you venture to Chemnitz in March: The first beer is on me.

**Comment by monochromec** [comment]
Thanks for the support!
