### ISSUE TITLE
Login image: option to display plain color instead

### ISSUE THREAD

**Issue by StephaneDupont** [nextcloud/server#1414]
About the theme login image: it's really a nice feature! ... but shouldn't there be an option to display a plain color background instead of being force to display an image?

**Comment by juliushaertl** [comment]
@StephaneDupont Thanks for your feature request. 

This is definitely something I'd like to add.

**Comment by jancborchardt** [comment]
Yeah, makes sense. And it should be the main color then as used in the header – which is already used as fallback background color if the image can not be loaded.. @juliushaertl next to the file picker we could have a button saying »Plain color« (or just a button colored in that color with a tooltip, but not sure this is obvious enough).

**Comment by juliushaertl** [comment]
My idea was to add a button with icon-delete with the tooltip "Remove background image". I have a local dev branch with this feature that still need some bug fixing. I'll try to finish this over the week.

**Comment by toddpfaff** [comment]
As a workaround for others who find themselves here after searching for this topic, at least until this feature is available more conveniently in Nextcloud, what I do is generate a small (16x16) solid color image, upload that as the background image, and it is scaled to fill the background, thus providing a solid color background.

**Comment by MorrisJobke** [comment]
@juliushaertl is this still feasible for 12? We plan to do the freeze mid next week. Otherwise I would move this to 13.

**Comment by MariusBluem** [comment]
@juliushaertl @Espina2 What do you think about the color https://github.com/nextcloud/nextcloud.com/pull/434 in the header of this mockup? This would be easy to theme 🤔

**Comment by juliushaertl** [comment]
@MorrisJobke Should be possible, I'll try to open a PR later today.

@MariusBluem Sorry, but I don't get what what you mean in combination to this issue. :thinking:

**Comment by MariusBluem** [comment]
![img_0640](https://cloud.githubusercontent.com/assets/19711361/25573635/a30ac600-2e47-11e7-812d-8688645b8b77.PNG)

@juliushaertl I mean this as a login background (especially the color gradient) 😉 Could be easy to change the color over Theming 😏

**Comment by juliushaertl** [comment]
@MariusBluem I like the idea although we don't have any other gradient anywhere in the server. Any other opinions @nextcloud/designers

**Comment by Espina2** [comment]
@MariusBluem I like the ideia, since I think our image on the server doesn't add any good, its just visual noise. :)

**Comment by MariusBluem** [comment]
Maybe we could also work with the 🌎-like design introduced on Nextclouds homepage (background) @Espina2

**Comment by MariusBluem** [comment]
Done. #4617
