### ISSUE TITLE
[Feature Request] Allow different theming settings based on different domains

### ISSUE THREAD

**Issue by ml31415** [nextcloud/server#14162]
Right now it is possible to have one instance of nextcloud being accessible under different domains. This is useful e.g. when you want to have a single instance directly serving for different projects, companies, services, ... and of course it would also be nice to be able to provide different themes / identities for the different domains.

Right now this is possible by manually providing themes and modifying the config based on the server settings for HTTP_HOST, selecting a different theme for each domain as explained [in the help forum](https://help.nextcloud.com/t/howto-individual-themes-per-domain/27585/2).

The problem with this approach is, that it is overly complicated, when you just want to have simple modifications like the ones possible with the theming addon. It also doesn't seem possible to affect the color and names used within the nextcloud mobile app. And there also seems to be a bug around, when selecting between icons, though, different story.

As I read, that modifying the nextcloud themes direcly by the user is already deprecated, the nicest solution to all this would be, if the theming addon would support different settings based on the different domains mentioned in the trusted_domain config variable. Plus, a default config, if there is nothing set for a certain domain.

I also saw the closed discussion #2601 about having different themes based on different groups / users. Though, I guess the here suggested change is way less invasive and interesting to a larger user base.

**Comment by MorrisJobke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by MorrisJobke** [comment]
FYI @juliushaertl

**Comment by eldelacajita** [comment]
Just wanted to support this use case and feature, for the record. Having a different branding per domain would be very useful for an instance that is shared among different groups or organizations.
