### ISSUE TITLE
Update to Nextcloud 15.0.4 available. (channel: "production") - coming from NC 14.0.6 ?

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#14165]
### Steps to reproduce
i'm using the Channel "updater.release.channel": "production" ! .. so i got a reminder that a new Version is there, NC Version 14.0.7 (was on 14.0.6) .. so i triggered the NC-Update from CLI .. and NC did recommend the Version 15.04 (i did NOT change the Channel) .. so what went wrong here .. ?

### Expected behaviour
NC should not suggest to jump on the last Version of a Major Version, when using the Channel: Production

### Actual behaviour:
Starting Upgrade using the CLI:

/bin/php /var/www/html/nextcloud/updater/updater.phar

NC Updater log --> 
--------------------------------------------------------------------------------------------------
Nextcloud Updater - version: v14.0.2RC2-1-g21ab216								
								
Current version is 14.0.6.								
								
Update to Nextcloud 15.0.4 available. (channel: "production")								
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-15.0.4.zip

## Server configuration detail
Operating System: System Linux 3.10.0-957.5.1.el7.x86_64

Webserver: Apache/2.4.6 (CentOS) OpenSSL1.0.2k-fips

Database: mysql 5.5.60-MariaDB,

PHP version: PHP Version => 7.2.10

[PHP Modules] apcu bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext hash iconv igbinary imagick intl json ldap libxml mbstring mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline redis Reflection session shmop SimpleXML sockets SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlwriter xsl Zend OPcache zip zlib [Zend Modules] Zend OPcache

Nextcloud: - version: 15.0.4.0

## Configuration (config/config.php)
{
"system": {
"memcache.local": "\OC\Memcache\APCu",
"filelocking.enabled": true,
"redis": {
"host": "_**REMOVED SENSITIVE VALUE**_",
"port": 0,
"dbindex": 0,
"timeout": 1.5
},
"instanceid": "_**REMOVED SENSITIVE VALUE**_",
"passwordsalt": "_**REMOVED SENSITIVE VALUE**_",
"secret": "_**REMOVED SENSITIVE VALUE**_",
"trusted_domains": [
],
"datadirectory": "_**REMOVED SENSITIVE VALUE**_",
"htaccess.RewriteBase": "/",
"overwriteprotocol": "https",
"dbtype": "mysql",
"version": "15.0.4.0",
"dbname": "_**REMOVED SENSITIVE VALUE**_",
"dbhost": "_**REMOVED SENSITIVE VALUE**_",
"dbport": "",
"dbtableprefix": "oc_",
"mysql.utf8mb4": true,
"dbuser": "_**REMOVED SENSITIVE VALUE**_",
"dbpassword": "_**REMOVED SENSITIVE VALUE**_",
"installed": true,
"maintenance": false,
"theme": "",
"loglevel": 1,
"updater.release.channel": "production",
"auth.bruteforce.protection.enabled": true,
"check_for_working_htaccess": true,
"mail_from_address": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpmode": "smtp",
"mail_smtpauthtype": "LOGIN",
"mail_domain": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpsecure": "tls",
"mail_smtpauth": 1,
"mail_smtpname": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtppassword": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtphost": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpport": "587",
"session_lifetime": 1200,
"session_keepalive": false,
"logfile": "/media/log/nextcloud.log",
"knowledgebaseenabled": false,
"log_rotate_size": 3145728,
"onlyoffice": {
"verify_peer_off": true
}
},

## List of activated Apps
Enabled:

* accessibility: 1.1.0
* activity: 2.8.2
* admin_audit: 1.5.0
* announcementcenter: 3.4.1
* apporder: 0.6.0
* audioplayer: 2.6.0
* bookmarks: 0.16.2
* bruteforcesettings: 1.3.0
* calendar: 1.6.4
* circles: 0.16.0
* cloud_federation_api: 0.1.0
* comments: 1.5.0
* contacts: 3.0.3
* data_request: 1.2.0
* dav: 1.8.1
* deck: 0.5.2
* drawio: 0.9.2
* drop_account: 0.1.0
* federatedfilesharing: 1.5.0
* federation: 1.5.0
* files: 1.10.0
* files_antivirus: 2.0.0
* files_fulltextsearch: 1.2.5
* files_mindmap: 0.0.11
* files_pdfviewer: 1.4.0
* files_rightclick: 0.11.0
* files_sharing: 1.7.0
* files_texteditor: 2.7.0
* files_trashbin: 1.5.0
* files_versions: 1.8.0
* files_videoplayer: 1.4.0
* firstrunwizard: 2.4.0
* flowupload: 0.0.9
* fulltextsearch: 1.2.4
* gallery: 18.2.0
* logreader: 2.0.0
* lookup_server_connector: 1.3.0
* nextcloud_announcements: 1.4.0
* notes: 2.5.1
* notifications: 2.3.0
* oauth2: 1.3.0
* onlyoffice: 2.1.2
* ownbackup: 18.11.0
* passman: 2.2.1
* password_policy: 1.5.0
* polls: 0.9.5
* provisioning_api: 1.5.0
* quota_warning: 1.4.0
* radio: 0.6.4
* rainloop: 6.0.2
* ransomware_protection: 1.3.0
* serverinfo: 1.5.0
* sharebymail: 1.5.0
* sharerenamer: 2.3.0
* socialsharing_diaspora: 1.0.4
* socialsharing_email: 1.0.5
* socialsharing_facebook: 1.0.4
* socialsharing_googleplus: 1.0.4
* socialsharing_twitter: 1.0.4
* spreed: 5.0.2
* support: 1.0.0
* survey_client: 1.3.0
* systemtags: 1.5.0
* tasks: 0.9.8
* theming: 1.6.0
* twofactor_backupcodes: 1.4.1
* twofactor_totp: 2.1.1
* updatenotification: 1.5.0
* workflowengine: 1.5.0
  Disabled:
* carnet
* encryption
* external
* files_accesscontrol
* files_external
* files_markdown
* impersonate
* jsloader
* phonetrack
* previewgenerator
* richdocuments
* user_ldap
* weather

## Client configuration
**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36

**Operating system:** Windows 10

**Comment by bpcurse** [comment]
afaik it is normal behaviour that the next major release is labeled production after some minor releases have passed, which is the case here.
In our setup we are using production and have been offered the update from 14.0.7 to 15.0.4 by the updater, too. Will perform it in the next days to benefit from v15 features.

**Comment by Githopp192** [comment]
Upon the official Nextcloud Documentation --> 

"We start the incremental rollout to the Production channel after the first bugfix release (for example, 12.0.1). Packages for the Release channels might be available in distributions, this is up to the packagers.

To upgrade in the safest way possible, always update to the latest minor release before upgrading to a new version. As an extreme example, to upgrade from 9 all the way to 12.0.5, upgrade 9.0.x to 9.0.6, then upgrade to 10.0.6, 11.0.7, then 12.0.5."

So when i wish to stay on the Production Channel as long as possible (regarding the official message from Nextcloud "To upgrade in the safest way possible, always update to the latest minor release before upgrading to a new version"), then i had to upgrade from 14.0.6 to 14.0.7, after that to 14.0.8.

Doing so .... i think i had to manually initiate the Upgrade (because NC already suggested the Major Upgrade,which would be the automatic way..).

Or is there a possiblity to manually choose the Version to be upgraded, which could trigger an automated Upgrade, too ?
i.e. in my case .. /bin/php /var/www/html/nextcloud/updater/updater.phar 14.0.7 ??

**Comment by MorrisJobke** [comment]
First we enabled 14.0.7 on the production channel for 14 instances. After 2 days we enabled 15.0.4 on the production channel, because it is ready for this channel. Thus there is as of now only the way to either upgrade to 15.0.4 or to manually upgrade to 14.0.7.


The described behavior is as it should be - only the presentation is maybe due to the cached response in the update notification and may be improved. Beside that everything is as it was designed.

**Comment by MorrisJobke** [comment]
For the other channel described in here there is this ticket: #8799

**Comment by Githopp192** [comment]
Thx Morris for your answer. So .. 1rst of all .. good message that everything is as it was designed. 
the 2nd comment (ticket #8799) is a great discussion about this Topic. Thank you very much for sharing this with me. As you're saying there --> "  guess that makes sense to provide. It would then only switch to the next major release at the EOL of that release. It would also allow people to stay on a version if they know that the next major release still has a bug, that they experience but still want to have a maintenance release."  .. that's exactly one thing, which could be improved for poeple like me .. (Nerds, who want to have the full Control :-) ) .. Maybe someone could add also some Kind of feature request, regarding the possibility to choose manually an upgrade Version, which will be performed in an automatic procdure.

**Comment by MorrisJobke** [comment]
> Maybe someone could add also some Kind of feature request, regarding the possibility to choose manually an upgrade Version, which will be performed in an automatic procedure.

1. automatic updates are in mind, but something separate
2. I commented at https://github.com/nextcloud/server/issues/8799#issuecomment-463102707 that proposes an easier way to my previous comment

Thanks for the feedback

**Comment by Githopp192** [comment]
very welcome :-) just want to mention about my current study case .. why it could make sense for persons like me to stay a Little longer on a 'older' production channel.

After upgrading from 14.0.6 to 15.0.4 there were some Apps with issues (one with the power of data loss) --> 

- Passman: nextcloud/passman#524 (finally i could come over (solve) the issue by myself .. 
  (This issue is open since Dec 19, 2018). At the end i'm not quite sure .. if - finally - this i an issue on the App or it's an issue of the Upgrade Procedure with App Certificates .. ? - (When last would be true, i could open a Server case about)

- Quick Notes matiasdelellis/quicknotes#18 was not anymore functional on Version 15.0.4
  (now it's working, Developper pushed new Version) - some user had fears of data loss !

- twofactor_totp  nextcloud/twofactor_totp#445 no-critical Errors in the NC.log

- nextcloud/issuetemplate#61 - App not Ready yet for 15.0.4

For me there are some Questions popped up .. are new Releases tested against all APPS which are existing in the NC App Store ? - for me the main trigger is .. Some non cores apps were developped from the community .. and finally approved through Nextcloud. Some Apps will overlive within the process of Nextcloud Upgrade processes - some not (due to different reasons). The critical point here are the data. For me, all data from the users (independant of NC-Core data, user files or user App data) .. user data Needs to be protected in any case. Never ever users may be affected by data loss.

**Comment by MorrisJobke** [comment]
> For me there are some Questions popped up .. are new Releases tested against all APPS which are existing in the NC App Store ? - for me the main trigger is .. Some non cores apps were developped from the community .. and finally approved through Nextcloud.

We as server maintainers can't test the over 100 different apps in the App Store. That is the reason why the developer needs to raise the version number to actively indicate that it was tested. We are aware that this is not the best way to deal with this, but currently it's the one that we are somehow able to control in a useful fashion. We are still thinking and discussing on how to improve this experience, because it's quite critical to make apps not break and keep them working for the users (that's why we are doing the whole project here, right? ;)).

Thanks for this feedback - just one more note: usually an update does not delete any data - so it's not really data loss, but it's not accessible anymore via the app. The DB entries and files are never* deleted if an app is disabled during update.

*at least not intentional by the server - if the app implements this then it could happen

**Comment by Githopp192** [comment]
Thanks Morris for this your feedback on this  .. since i'm using Nextcloud since years .. i'm always learning a lot ... also  from other people like you .. so my apologize, when i should be too demanding. I've got a huge respect for the all great work about this great product and philosophy behind and all the people, who are supporting Nextcloud in any manner. By the way .. i'm often in a similar Situation .. my most demanding user on the Cloud is my girlfriend :-) .. who is very demanding about Apps, Functionalities, Speed, Office Integrations and more .. but also this is chance for me to learn and to improve. Nextcloud is the best Product in the Open Source market i know .. i would appreciate to push Nextcloud forward in our Company (we're providing Outsourcing Services for worldwide customers in any area and "Cloud Services" are part of that Business..). Have a great day.
