### ISSUE TITLE
not possible to share dates with participants

### ISSUE THREAD

**Issue by oztranet** [nextcloud/server#14176]
Hallo, 

I'm using Calendar version 1.6.4 with Nextcloud version 15.0.4. 
You can find my webserver-configuration here: https://oztra.net/phpinfo.php

Since nextcloud-version 15 it isn't possible to share dates with participants. There is no email in the inbox... all other emails from nextcloud are arriving.

Greetings, Adrian

**Comment by georgehrke** [comment]
@oztranet Is the user you are inviting by any chance also another user in Nextcloud?

**Comment by oztranet** [comment]
> please use the issue template as described in our contributing guidelines
it was too much required...

> @oztranet Is the user you are inviting by any chance also another user in Nextcloud?
no, I have test it with an nextcloud user in the same cloud but with an different email address. There was no incoming email :/

**Comment by oztranet** [comment]
### Erwartetes Verhalten
Wenn in einem neuen Termin Teilnehmer hinzugefügt werden, sollten diese eine entsprechende Email erhalten.

### Tatsächliches Verhalten
Wenn in einem neuen Termin Teilnehmer hinzugefügt werden, erhalten diese keine Email.

**Betriebssystem**:
keine Ahnung -> Webhoster: Domain Factory (https://www.df.eu/)

** Webserver: **
Apace 2.4.35 

**Datenbank:**
MySQL 5.6.19

** PHP-Version: **
PHP 7.1.23

** Server-Version: ** (sehen Sie Ihre Admin-Seite)
 Nextcloud 15.0.4

** Kalenderversion: ** (siehe Apps-Seite)
Calendar 1.6.4

Melden Sie sich als Administrator in Ihrer Cloud an und greifen Sie darauf zu
http://example.com/index.php/settings/integrity/failed
Fügen Sie die Ergebnisse hier ein.
 `No errors have been found.`

** Liste der aktivierten Apps: **
 Accessibility
1.1.0
Activity
2.8.2
Brute-force settings
1.3.0
Calendar
1.6.4
Collaborative tags
1.5.0
Comments
1.5.0
Contacts
3.0.3
Default encryption module
2.3.0
Deleted files
1.5.0
Federation
1.5.0
File sharing
1.7.0
Files Right Click
0.11.0
First run wizard
2.4.0
Gallery
18.2.0
Log Reader
2.0.0
Monitoring
1.5.0
Nextcloud announcements
1.4.0
Notes
2.5.1
Notifications
2.3.0
OwnBackup
18.11.0
Ownpad
0.6.11
Password policy
1.5.0
Passwords
2019.2.2
PDF viewer
1.4.0
Piwik/Matomo Tracking
0.5.0
Share by mail
1.5.0
Support
1.0.0
Tasks
0.9.8
Text editor
2.7.0
Theming
1.6.0
Update notification
1.5.0
Usage survey
1.3.0
Versions
1.8.0
Video player 
1.4.0

Fügen Sie hier den Inhalt Ihrer config.php ein:
<?php
$CONFIG = array (
  'instanceid' => '**************',
  'passwordsalt' => '**************',
  'secret' => '**************',
  'trusted_domains' => 
  array (
    0 => 'oztra.net',
  ),
  'datadirectory' => '/kunden/**************/websites/**************/**************/data',
  'dbtype' => 'mysql',
  'version' => '15.0.4.0',
  'overwrite.cli.url' => 'http://oztra.net/**************',
  'dbname' => '**************',
  'dbhost' => '**************',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '**************',
  'dbpassword' => '**************',
  'installed' => true,
  'maintenance' => false,
  'updater.secret' => '**************',
  'theme' => '',
  'loglevel' => 2,
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => 'oztra.net',
);

** Verwenden Sie einen externen Speicher, wenn ja welcher: **
sftp

** Verwenden Sie die Verschlüsselung: **
Ja -> https, webdav

### Client-Konfiguration

**Browser:**
Firefox version 60.5.0esr x64

#### Protokolldatei (data / nextcloud.log)
Wenn diese Datei wirklich gebraucht wird, frage per email danach... es scheinen darin einige sensible Daten enthalten zu sein.

**Comment by rullzer** [comment]
Can you fill it out in English please. A lot of people here do not speak german.

**Comment by oztranet** [comment]
done

**Comment by oztranet** [comment]
I guess this is a general bug with the new nextcloud-version 15.x...

**Comment by georgehrke** [comment]
Please go to the admin settings -> Basic settings -> E-Mail Server and try to send yourself a test email, to make sure emails are set up properly.

**Comment by oztranet** [comment]
Okay, it's successful. One test-email is arrived in my postbox. 

This is my email server configuration:
mode: sendmail
sendmail-mode: smtp (-bs)

**Comment by ChristophWurst** [comment]
Assuming this is resolved -> closing
