### ISSUE TITLE
Upgrading to 15.0.4 misses folder creation

### ISSUE THREAD

**Issue by growies** [nextcloud/server#14171]
### Steps to reproduce
1. Upgrade using the UI
2. After successful upgrade, and being logged in, a 500 Internal Server error shows

### Expected behaviour
Page loads successfully

### Actual behaviour
500 error

The logs show
{"reqId":"j9tUPnB7zAtXNvX50XYs","level":3,"time":"2019-02-12T23:19:16+00:00","remoteAddr":"IP","user":"username","app":"PHP","method":"GET","url":"\/index.php\/apps\/files\/","message":"touch(): Unable to create file \/var\/www\/data\/appdata_ocnefgrgmv42\/css\/files_trashbin\/35c3-8ea2-trash.css because No such file or directory at \/var\/www\/html\/lib\/private\/Files\/Storage\/Local.php#206","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:64.0) Gecko\/20100101 Firefox\/64.0","version":"15.0.4.0"}

The error was solved by manually creating the folder. Sitting in /var/www/data/appdata_ocnefgrgmv42/css and running the command
sudo -u www-data mkdir files_trashbin

php -version is

PHP 7.0.33-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by MorrisJobke** [comment]
cc @juliushaertl @rullzer

**Comment by skjnldsv** [comment]
I think we fixed it, it ring a bell!
