### ISSUE TITLE
Upload progress bar design improvement

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#14181]
Follow-up to https://github.com/nextcloud/server/pull/13567 by @weeman1337 :)

We could use the style like the quota bar for the progress bar? Then the text will also be easier to read on the intermediate states, and it doesn’t look like a button or text input.

Quick mockup based on the quota bar:
![file upload progress bar mockup](https://user-images.githubusercontent.com/925062/51486154-30127680-1da0-11e9-9409-f07c2677f13c.png)

cc @nextcloud/designers

**Comment by BloodyIron** [comment]
IMO we need MUCH more info than what we get now, and than the quota bar.

Here's an example alternative tool that not only makes the process "faster" at parts, gives much more feedback about upload progress. Furthermore, it parallelizes the upload process, which is something nextCloud SORELY needs for both the web interface, and sync!

**Comment by skjnldsv** [comment]
@BloodyIron please don't post the same message on multiple issues/pr :)
IIRC, there is an opened issue regarding a better upload screen somewhere

**Comment by BloodyIron** [comment]
@skjnldsv sorry about that, I looked at both threads and wasn't sure which one was best to post in D:

**Comment by szaimen** [comment]
I suppose this issue is still valid.

**Comment by HannesJo0139** [comment]
I also find the upload progress bar ugly as hell. Well, while uploading it is ok, but when chunks are being assembled and the disable button is becoming invisible, it looks like broken. Also the same bar is used when copying files and it just looks awkward.

What's that?:
![image](https://user-images.githubusercontent.com/42114183/209001173-0682f08f-6133-4673-ba7e-57684197f164.png)

**Comment by joshtrichards** [comment]
This still relevant after #39945 being merged? Okay to close?
