### ISSUE TITLE
Locked exception when moving a file via dav

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1419]
### Steps to reproduce
1. As user `test1` upload a file `welcome.txt`
2. Create folder `test/`
3. `cadaver http://localhost/remote.php/dav/files/test1`
4. `MOVE welcome.txt test/welcome.txt`
### Expected behaviour

`200 OK`
### Actual behaviour

`423 Locked`
- `test/welcome.txt` exists :white_check_mark: 
- `welcome.txt` exists :x: 

@icewind1991 can you have a look? And note, DAV move actually does a create+delete, which might be the cause. (parents still locked, or something like that)

**Comment by aronovgj** [comment]
Could that also happen when trying to delete a file? Right now I am running into something similar:

```
	OCA\DAV\Connector\Sabre\Exception\FileLocked: HTTP/1.1 423 "android/twrp/BACKUPS" is locked

    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php - line 179: OCA\DAV\Connector\Sabre\Directory->delete()
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 285: Sabre\DAV\Tree->delete('android/twrp/BA...')
    [internal function] Sabre\DAV\CorePlugin->httpDelete(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 459: Sabre\Event\EventEmitter->emit('method DELETE', Array)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 248: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 60: Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php - line 165: require_once('/var/www/nextcl...')
    {main}
```

**Comment by lamixer** [comment]
I have a problem which might be related, the error:

`
OCA\DAV\Connector\Sabre\Exception\FileLocked: HTTP/1.1 423 "<filename>" is locked`

Upon uploading a very large file (a little over 4GB) via the web interface, I get this error. In Nextcloud, the upload progress bar completes and it pops up "Locked". The file is not written.

Important to note - the whole time the file is uploading (which is a LONG time, like 3 hours, and that is probably related to the problem) I can see the php temp file being written and it grows slowly as expected. This error pops up when the file is supposed to be moved from the temp directory to its final destination. The file disappears from the temp directory.

Interestingly, if I upload the same size file, but on the LAN, which might take only a couple of minutes, it works fine.

No SELinux errors seem to be involved.

Centos 7, up-to-date. Apache, MariaDB. PHP 5.6.29

**Comment by nickvergessen** [comment]
I guess the lock timed out already and therefor it can not be increased for the final movement

**Comment by lamixer** [comment]
Is there any way to control the timing of that?

**Comment by nickvergessen** [comment]
Yes https://github.com/nextcloud/server/blob/98bdef8d83bcc8e43560b735a9a479c981a3b24e/config/config.sample.php#L1277-L1284

**Comment by lamixer** [comment]
I tested a 3GB upload that took about 1.5 hours and that worked, so I think this solved the problem. Thanks.
