### ISSUE TITLE
Make different LDAPs independent

### ISSUE THREAD

**Issue by wanneut** [nextcloud/server#14209]
Hi,

I use different LDAPs as sources for nextcloud-users. One of these has no replica since these Users are not that critical this should be no problem.
But when this LDAP fail even the other users can't log in.
(Log says: OC\ServerNotAvailableException: Lost connection to LDAP server.)
If one connection to one LDAP fails, please try the other User-Sources if this user is realy affected by this error. (Like it is done for local users.)

**Comment by blizzz** [comment]
Sorry, but we won't go this path as there are several bad side effects this could have. For one, a user does not just exist for itself but has interchange with others. Secondly, there are also several background jobs that deal with users, too. 

If you are keen on going that way nevertheless (your responsibility) you can have a monitoring script on the Nc server that disables affected LDAP configuration via occ in case the LDAP server goes down.  I can only discourage from doing so.
