### ISSUE TITLE
Sharing via Document-App does not work when using LDAP

### ISSUE THREAD

**Issue by zeus86** [nextcloud/server#1421]
The sharing via the Document-App does not work when using LDAP. 
The only thing you can do instead is sharing the document via the "files"-app with write permission, and then have the users to move the file in their "files"-view into the designated "documents"-folder. 
After that, the status of with which users the file is shared is also correct then, even in the documents-app. 
This seems only to happen when using LDAP, but affects all users then, also the admin-user. 

This issue seems to be related to [this particular case](http://owncloud.10557.n7.nabble.com/Problem-with-sharing-a-word-file-from-within-the-Documents-app-in-the-web-td16890.html) .

### Steps to reproduce
1. Use Document-App to create a new document and type some characters in
2. click on share
3. choose users and/or groups 

### Expected behaviour
document is shared between selected users/groups and appears in the dedicated, configured Documents-Folder at everyone this is shared with

### Actual behaviour
share-overlay is in "loading" state, and never finishes

### Server configuration
**Operating system**:
ubuntu/lts 16.04/64 bit

**Nextcloud version:** (see Nextcloud admin page)
10.0.25

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - calendar: 1.3.3
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - mail: 0.5.3
  - notifications: 0.3.0
  - ojsxc: 3.0.0
  - ownbackup: 0.3.8
  - ownnote: 1.08
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - password_policy
  - systemtags
  - templateeditor
  - user_external
  - user_saml

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

**Comment by nickvergessen** [comment]
please report to https://github.com/owncloud/documents

**Comment by zeus86** [comment]
ah, did not recognize that there is an extra repo for that
