### ISSUE TITLE
Support the 'client_credentials' grant type for OAuth2 clients

### ISSUE THREAD

**Issue by ivmarkov** [nextcloud/server#14219]
It would've been great if the OAuth2 app implementation supported the `client_credentials` grant type, as that would allow other, trusted servers insisting on using the OAuth2 protocol to upload data to NextCloud in an automated fashion.

Obviously, this is not supported by the `authorization_code` grant type, as this grant type is supposed to be used only with end users, as it presents a login page for authentication.

A possible solution might be as simple as - when configuring an OAuth2 client, the UI to allow the administrator to designate an OAuth 2.0 client as a `client_credentials` type of client, and to allow the administrator to type the NextCloud user, with whom this OAuth2 client would be associated (for authorization purposes).

I realize that the `client_credentials` grant type is probably possible to implement by integrating NextCloud with an IDP provider like KeyCloak, but that kind of defeats for us the whole purpose of choosing NextCloud in the first place, as besides NextCloud, we'll also have to expose on the Internet an IDP provider which increases the attack surface. Not to mention that the OAuth2 implementation in NextCloud does not strictly require an integration with an external IDP, as NextCloud itself can serve as an IDP for OAuth2.

Or in other words, the OAuth2 implementation in NextCloud looks as if you guys have implemented 95% of what is necessary, and only the last 5% (the `client_credentials` grant) are missing.

**Comment by duchangyu** [comment]
vote for this. 

I spent hours to investigate why I get {"error":"invalid_grant"} when using grant_type=client_credentials. I finally find this thread and it made me sad. 

Yes, I need to integrate my app with netcloud as backend, it would not work if grant_type=client_credentials is not supported.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
