### ISSUE TITLE
Share Multiple links failed

### ISSUE THREAD

**Issue by GammaPi** [nextcloud/server#14216]
### Steps to reproduce
1.Select a folder and try to add multiple links

### Expected behaviour
It should add several independent sharing links

### Actual behaviour
If I add more than two links, I cannot create a password protected + read only + no expiration link( Other combination may also fail). When create another link or modify a specific link, all the sharing links config will change.

**Nextcloud version:**
15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.x

**Where did you install Nextcloud from:**
Docker image

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration
Firefox latest version

**Operating system:**
Ubuntu 18.04

**Comment by dj3mu** [comment]
Especially we can confirm this statement:
> When create another link or modify a specific link, all the sharing links config will change.

We're seeing really "weired" behavior of the "Share Link" functionality while as of now no issues have been reported with "named" shares (sharing with people or groups).

We are seeing such behaviour even when only a single link has been created and gets modified.  
By "weired" I mean that we have not really been able to figure out the "logic" of what happens and how to reproduce it. But the following seems at least to be facts as of now:

* By the following steps I can cause the "implicit" creation of a new link share:
  1. Create a link share without password and expiration. Not sure if it matters which rw-mode is chosen.
  2. Open the settings of that link and enable password and expiration date (do NOT set a password)
  3. Open the settings of that link again and disable passward and expiration.
  In step 3 for us a new link share appears that has neither a radio button nor a checkbox enabled.  
  In the following screenshot note that the second "Share link" has NOT be created using the "Add another link" function:
  ![Screenshot after step 3](https://user-images.githubusercontent.com/41773089/52896634-0136c700-31cb-11e9-98dc-f1bbf6d731ea.png)

* Sometimes, when we change the radio buttons for share mode (ro/rw/ul-only) the "Set expiration date" checkbox gets unset while the "Password protect" checkbox gets set. This behavior is not 100% reproducible and it might dependent on the enable or disable default/enforce settings in the "/settings/admin/sharing". But those settings might not be the only "prerequisite" for this to happen.

Our instance and OS is almost same as given in @GammaPi's initial description. Even the instance history: A (fresh) install of 14.x upgraded to now run 15.0.4. Only these two differences:

**Where did you install Nextcloud from:** Tar ball

**Are you using an external user-backend, if yes which one:** yes. LDAP.

We're seeing the issue at least with latest Firefox (Windows) and Chrome (MacOS). With and without Ghostery and Adblock+ extensions.

**Comment by timmersr** [comment]
#12900 and part of the 15.0.5 roadmap.

**Comment by hottwister** [comment]
My steps to reproduce on NC 15.0.4:
1. Create public share link fore some file, add write permissions with Allow editing checkbox
2. Create 2nd  for same file
3. Check the first link - 'Allow editing' checkbox is unchecked, but write permissions are still exist

**Comment by GammaPi** [comment]
In NC 16, the problem is fixed according to my test.
Closing
