### ISSUE TITLE
External Storage -> Add "rescan files" checkbox

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#14217]
Please Add an "enable cron job" checkbox to the external storage app to automatically run rescan files on e.g. a SMB-Share without requiring a manual setup. 

In best case you add also a drop-down menu where you can choose the timespan for rescanning.

**Comment by skjnldsv** [comment]
@icewind1991 @rullzer  does it make sense?
I guess adding a cron job yourself is not that hard though, but this would ease up the setup :thinking:

**Comment by szaimen** [comment]
I think the more easy it gets, the more people will install their own nextcloud.
So ease up the setup is always a good thing.
