### ISSUE TITLE
Set differentiated permissions for shared items

### ISSUE THREAD

**Issue by richard-dg** [nextcloud/server#14222]
When I share items (files, folders, calendars) I can share them either read only or with the "can edit" checkbox. What "can edit" means is defined globally in the admin panel. I know that in former versions I was able to set permission for every share individually, like for example:

[] Can read
[] Can write
[] Can delete

Has this feature disappeared or do I just don't find it? If yes, why has it disappeared?

**Comment by MorrisJobke** [comment]
It's in the drop down menu:

![bildschirmfoto 2019-02-15 um 13 37 12](https://user-images.githubusercontent.com/245432/52857228-d5620580-3126-11e9-8ecf-d8885b1069f0.png)

**Comment by richard-dg** [comment]
Thanks for your reply. 

That was where I expected it to to be. But:

![dropdown](https://user-images.githubusercontent.com/4435520/52857707-2faf9600-3128-11e9-9a3c-d4079d55310a.PNG)

I'm on version 15.0.4 

Any idea where to look?

**Comment by MorrisJobke** [comment]
AFAIK it's only there for folders and not for files, because there it makes very little sense.

**Comment by richard-dg** [comment]
Now it makes sense to me. Thanks for the clarification! Is there anything similar for calendars? (Can add new events but can't delete them)?

**Comment by MorrisJobke** [comment]
> Now it makes sense to me. Thanks for the clarification! Is there anything similar for calendars? (Can add new events but can't delete them)?

No idea - maybe @georgehrke knows more about the UI implications there.

**Comment by georgehrke** [comment]
No, that's not supported. It was years back, but we dropped that when we switched to standardised CalDAV sharing. That only supports read and read-write.

**Comment by richard-dg** [comment]
Thanks for the info!
