### ISSUE TITLE
Allow binlog_format = STATEMENT

### ISSUE THREAD

**Issue by Ninos** [nextcloud/server#1422]
Hey there,
in shared-hosting mysql binlog_format is mostly set to STATEMENT (default value). Since owncloud 8.0.3 binlog_format = STATEMENT is not supported anymore
-> nextcloud & owncloud will not work on some shared-hosting providers

I recommend fixing that :) See also owncloud issue:
https://github.com/owncloud/core/issues/16008

**Comment by pokoli** [comment]
@Ninos do you know which have to be changed in order to fix this issue?

**Comment by Ninos** [comment]
No, just tell me please :D

**Comment by pokoli** [comment]
I don't know how two fix it butt, but I made a resume of the relevant comments in the original issue: 

https://github.com/owncloud/core/issues/16008#issuecomment-98844031
https://github.com/owncloud/core/issues/16008#issuecomment-111064680

The proposed solution by owncloud was to document the error here:

https://github.com/owncloud/documentation/pull/1109/commits/bfce159a1ebaffcc682c05360d59ec48eaf5b056

**Comment by Ninos** [comment]
As I know there was a change for locking files on multiple processing, but I'm not sure

**Comment by MorrisJobke** [comment]
Sorry for the bad news here, but we require the database to be configured like stated in the documentation. See also https://github.com/nextcloud/server/issues/8645#issuecomment-370394443

Thus I will close this ticket.
