### ISSUE TITLE
Text in toolbar icons and "more" menu disappears after opening "more"

### ISSUE THREAD

**Issue by arnowelzel** [nextcloud/server#14220]
### Steps to reproduce
1. Login to Nextcloud
2. Move the mouse to the "..." item in the toolbar and click it once, so the "more" menu opens
3. Without selecting any item in the "more" menu, click outside the toolbar to close it again
4. Hover the toolbar and touch one or more icons without clicking them

### Expected behaviour
The "more" menu closes and the toolbar behaves as before. When hovering the mouse over toolbar items, the text below the icons stays visible.

![grafik](https://user-images.githubusercontent.com/6613614/52844638-4bee0b80-3105-11e9-86de-14cefaa15757.png)

### Actual behaviour
The "more" menu closes and the text below toolbar items become invisible. In some cases even the "more" menu itself is just a white box without visible content.

![grafik](https://user-images.githubusercontent.com/6613614/52844682-6b853400-3105-11e9-81bd-5ebcfb98c1b4.png)

### Server configuration

**Operating system**: Ubuntu Server 18.04 LTS

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.2.14

**Nextcloud version:** 15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 14.0.7

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - defaultlinkopen: 1.2.0
  - drawio: 0.9.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - gpxpod: 3.0.1
  - keeweb: 0.5.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - socialsharing_email: 1.0.5
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.0x0c.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "",
        "overwrite.cli.url": "https:\/\/nextcloud.0x0c.de",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "knowledgebaseenabled": false,
        "theme": "",
        "loglevel": 2,
        "log_authfailip": true,
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production",
        "trashbin_retention_obligation": "auto, 7",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 65.0.1

**Operating system:** Windows 10 Pro 1809

#### Browser log
<details>
<summary>Browser log</summary>

```
Source-Map-Fehler: TypeError: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://nextcloud.0x0c.de/apps/notifications/js/notifications.js?v=025351ae-51
Source-Map-Adresse: notifications.js.map[Weitere Informationen]
```
</details>

**Comment by violoncelloCH** [comment]
reproduced
cc @nextcloud/javascript

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/server/pull/14279
