### ISSUE TITLE
config.php manual settings deleted after upgrade NC15.02->NC15.04

### ISSUE THREAD

**Issue by NBoESFWbVaf** [nextcloud/server#14233]
### Steps to reproduce
1. older NC installation (15.0.2) (Behavior was observed earlier)
2. have manual settings in config.php (theme, defaultpage etc.)
3. make upgrade with webinstaller and maintenance mode over web.

### Expected behaviour
config.php will not be overwritten and manual settings are retained

### Actual behaviour
- config.php all manual entries are deleted (Cache, Theme, Defaultpage etc.)
- Only settings made during the installation are retained.

### Server configuration

**Operating system**: Ubuntu Server 16.04.5

**Web server:** Apache/2.4.18

**Database:** MySql 5.7.25

**PHP version:** PHP 7.1.26

**Nextcloud version:** 15.0.4.0 stable channel

**Updated from an older Nextcloud/ownCloud or fresh install:** 15.0.2

**Where did you install Nextcloud from:** Virtual Server with webinstaller in a subdomainfolder

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

**No errors have been found.**

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - drop_account: 0.1.0
  - encryption: 2.3.0
  - event_update_notification: 0.3.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - telephoneprovider: 1.0.2
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - files_external
  - user_ldap


```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mysub.mydomain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "overwrite.cli.url": "https:\/\/mysub.mydomain.tld",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu"
 
</details>

**Are you using encryption:** yes/no
</details>

### Client configuration
**Browser:** Browser independently

**Operating system:** OS independently

**Comment by GuyPaddock** [comment]
I just encountered something like this myself. But, in our case, we were not upgrading; we were running 15.0.5.3 the whole time and suddenly config.php was erased.

**Comment by j-ed** [comment]
@GuyPaddock I'm running my Nextcloud instance for years now, without ever seeing such a behavior. The only time the *config.php* is being touch is usually when an update was triggered. Could you please provide some more details at what time or by what activity the file was most likely deleted?

**Comment by GuyPaddock** [comment]
It looks like the issue is that the SMB-backed volume containing config.php was intermittently unavailable (transient failure with the provider). This caused Nextcloud to generate a new config.

**Comment by kesselb** [comment]
@NBoESFWbVaf did this happen again?

**Comment by NBoESFWbVaf** [comment]
Hello kesselb,

I just made an update on 15 to 16.0.1 for 2 Servers and it seems to work. There were "only" 2 errors, but they belong in a different topic. (htaccess with headers and the app "Groupfolders").

**Comment by kesselb** [comment]
Thank you :+1:
