### ISSUE TITLE
Updating a non-exist file which name contains '%00' causes internal server error

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#1424]
### Steps to reproduce

1.Try to update file content by passing an non-exist file which name contains '%00'

``` sh
curl -i -X PUT -H 'OCS-APIREQUEST: true' \
-H 'Cookie: xx' -H 'requesttoken: xx' \
-H 'Content-Type: application/x-www-form-urlencoded; charset=UTF-8' \
http://localhost/nextcloud/index.php/apps/files_texteditor/ajax/savefile \
-d 'filecontents=aa&path=%2FDocuments/File%00.txt&mtime=1473993851'
```

2.Check the response body

``` javascript
{"message":"An internal server error occurred."}
```

3.Check nextcloud.log, there is an error message

``` javascript
{
    "reqId": "xx",
    "remoteAddr": "xx",
    "app": "PHP",
    "message": "realpath() expects parameter 1 to be a valid path, string given at /var/www/html/nextcloud/lib/private/Files/Storage/Local.php#360",
    "level": 3,
    "time": "2016-09-16T03:55:24+00:00",
    "method": "PUT",
    "url": "/nextcloud/index.php/apps/files_texteditor/ajax/savefile",
    "user": "admin"
}
```
### Expected behaviour

Handle this error and return more readable error message.
### Actual behaviour

Looks like this is not a functional issue.
### Server configuration

**Operating system**:
CentOS 7 x86_64
Linux 10.211.55.9 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
httpd-2.4.6-40.el7.centos.4.x86_64

**Database:**
sqlite3

**PHP version:**
PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**

**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Firefox ESR 38.3.0

**Operating system:**
CentOS 7 x86_64

**Comment by MorrisJobke** [comment]
This is an issue within the files_texteditor app. Thus please report it to the maintainer of that app in its repository: https://github.com/nextcloud/files_texteditor
