### ISSUE TITLE
ocm-provider end-point doesn't work

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#14247]
Tested with Nextcloud 15.0.4

````
curl -X GET http://localhost:70/server/ocm-provider/
````

should return a JSON object which describes the OCM capabilities. This works on my dev environment but not on productive instances like c.nc.com. I assume that it doesn't work because of the rewrite rules in the .htaccess file. But `/ocs-provider/` works and there is no special rule for this end-point in the .htaccess and I can't spot a obvious reason why it doesn't work for `/ocm-provider/`

@rullzer @MorrisJobke any idea?

**Comment by rullzer** [comment]
Yeah. Seems there need to be an explit rule in https://github.com/nextcloud/server/blob/master/.htaccess#L56-L70

Since with pretty urls we pipe everything trough index.php. Where this does :boom:

**Comment by rullzer** [comment]
And yeah there is a special rule

https://github.com/nextcloud/server/blob/b9f2ce2796a6aab3192033e7d02d9c581eb670b8/lib/private/Setup.php#L519

**Comment by schiessle** [comment]
Ah, I only looked at the .htaccess in the git-repository which doesn't has a special rule. I created a pull request, do you think it is enough to add it to the setup.php or should we also add it to the existing .htaccess?
