### ISSUE TITLE
File sharing download functionality fails after file edit

### ISSUE THREAD

**Issue by orcu** [nextcloud/server#14259]
### Steps to reproduce
1. Create a .txt file
2. Share the file from the web interface
3. Edit the file contents from the local
4. Follow the share link in a browser
5. Click on one of the download buttons to see error

### Expected behaviour
The link shared before the edit should seemlessly let downloading of the edited version

### Actual behaviour
The download button results in the following error
"Error
Can't read file
Can not read this file, probably this is a shared file. Please ask the file owner to reshare the file with you."

Note that the preview works fine in Firefox at step 4:
4.a. Preview in Firefox works correctly
4.b. Preview in Chromium fails

### Server configuration

**Nextcloud version:** 
Nextcloud 15.0.2
Linux Desktop Client Version 2.3.3 (build 1)

**Comment by kesselb** [comment]
That seems to work for me (or I did it wrong). Are you able to reproduce it with a newer nextcloud version? Thanks :+1:

**Comment by orcu** [comment]
I just tried and I am not able to reproduce it with Nextcloud 16.0.7 either. Seems to have been fixed. Thank you.
