### ISSUE TITLE
One-time import of Gravatar image as avatar

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1425]
- to make it easy to have an avatar

cc @nextcloud/designers Do you like the idea?

**Comment by rullzer** [comment]
Meh... most people that use gravatar probably already set their own avatar.

**Comment by tcitworld** [comment]
I never think to upload my own avatar but I'm quite pleased when an app has fetched it from my email address. Of course, this should be a server setting.

**Comment by rullzer** [comment]
So thinking some more about this. If we'd do it in an app i'd be fine with it. But not in core. The app could just add a notification to users so they can chose to use gravatar for their avatar. And then a cron job that runs daily or so to fetch all the avatars from gravatar of users that want it etc.

**Comment by gregharvey** [comment]
+1 for a Gravatar App, that would be nice. We use Gravatar with GitLab, Redmine, Rocket.Chat, etc. so having it work with Nextcloud too would be icing on the cake. :-)

**Comment by jancborchardt** [comment]
@gregharvey would you be down to contribute a pull request to integrate Gravatar support?

How it should work is simply: You put in your email address → You get asked if you want to fetch the associated profile image from Gravatar. :)

**Comment by ArnY** [comment]
Why restrict that feature to gravatar? there are some other avatar hosting platforms that provides similar features. It would be best to default to gravatar but allow the administrators (or users?) to specify an alternative url with placeholders for email, username, etc. so something like this could be used: https://whatever.serv.com/path/?email=%email or example.

**Comment by coliff** [comment]
+1 from me. Gravatar is incredibly popular, according to [article on Wikipedia](https://en.wikipedia.org/wiki/Gravatar) Gravatar was serving approximately 20 billions images per day - and that was back in 2010, I'm sure it must be even higher now.

Gravatar is used by hundreds or big name sites such as WordPress, Stackoverflow, Slack, GitHub etc. I think the best integration method (as used by the sites I just mentioned) is to show the gravatar image (if a users email address has one) by default automatically - and only show a different image if the user uploads a specific one to Nextcloud.

**Comment by gregharvey** [comment]
@jancborchardt Hey, I'm so sorry, I never even realised you replied to this! I don't know why, but I never seem to get sensible notifications from GitHub. Assuming this isn't done yet, we can certainly look at it.

**Comment by jancborchardt** [comment]
@gregharvey no worries! :) There is no further progress on this so far, so please feel free to take a look. Even pull requests with basic work-in-progress are welcome, as we can help and build on it together. :rocket:

**Comment by Fchen48** [comment]
+1 for Gravatar

**Comment by weeman1337** [comment]
I've started building an app for this: https://github.com/weeman1337/nextcloud-gravatar

**Comment by weeman1337** [comment]
I'm currently looking for testers for the Gravatar integration.

You can simply copy the [repo](https://github.com/weeman1337/nextcloud-gravatar) contents into your "apps/gravatar" directory.  
[Any feedback or error reports are highly welcome](https://github.com/weeman1337/nextcloud-gravatar/issues).

**Comment by MariusBluem** [comment]
Separte app is in development by @weeman1337 - no more need to track this feature request in this repo ;) Thanks for the contribution!

**Comment by MorrisJobke** [comment]
@weeman1337 Nice 👍

**Comment by denics** [comment]
Did this app ever made to the store? I cannot find it and I would really like to use it.

**Comment by jancborchardt** [comment]
Doesn’t seem like it is in the store. @weeman1337 do you plan to publish it? :)

**Comment by Mase3206** [comment]
It looks like @weeman1337 archived it on October of 2020.

**Comment by Fuzl** [comment]
Still no app in the Nextcloud store, that's too bad !
May I ping @weeman1337 to see if he could add his app to the store ? That would be awesome ❤
