### ISSUE TITLE
Rename "Castellano" language to "Español (España) / Castellano"

### ISSUE THREAD

**Issue by ngosang** [nextcloud/server#14253]
Rename "Castellano" language to "Español (España) / Castellano". It was a bit hard to find in the language list. Note: I'm from Spain, we use Español/Spanish to refer to the language most of the time.
![imagen](https://user-images.githubusercontent.com/10577978/52913400-222c1480-32be-11e9-84b4-2cbf1fb145a5.png)

NextCloud: 15.0.4

**Comment by skjnldsv** [comment]
cc @danxuliu and @Ivansss 
Does it make sense?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by ngosang** [comment]
I opened the issue 4 years ago. I'm not using this software as today.
