### ISSUE TITLE
Open html file instead of download it.

### ISSUE THREAD

**Issue by nininia** [nextcloud/server#14265]
Need to download html file from nextcloud directory. I see file preview instead of getting file on my system. Only one way to download it is to put html file to directory and download this directory.

### Steps to reproduce
1. Push three points near file name to open list of file possibilities  
2. Check 'Download'
3. 

### Expected behaviour
File is downloaded to my system

### Actual behaviour
Preview of the file appears

**Nextcloud configuration:**

<?php
$CONFIG = array (
  'passwordsalt' => '*',
  'secret' => '*',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => '*',
    2 => '*',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '15.0.0.10',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_apache',
  'dbpassword' => '*',
  'installed' => true,
  'instanceid' => '*',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'updater.release.channel' => 'beta',
  'loglevel' => 0,
  'logfile' => '/var/log/nclog.log',
  'log_type' => 'file',
  'debug' => true,
  'maintenance' => false,
  'theme' => '',
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\Image',
    1 => 'OC\\Preview\\MP3',
    2 => 'OC\\Preview\\TXT',
    3 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\Movie',
    5 => 'OC\\Preview\\Photoshop',
    6 => 'OC\\Preview\\TIFF',
    7 => 'OC\\Preview\\SVG',
    8 => 'OC\\Preview\\OpenDocument',
  ),
 'trusted_proxies' =>
  array (
    0 => '*.*.*.*',
  ),
  'overwrite.cli.url' => 'http://localhost',
  'overwriteprotocol' => 'https',
  'overwritecondaddr' => '^***\\.***\\.***\\.***$',
);

**Comment by violoncelloCH** [comment]
what do you mean with "file preview"? displayed by Nextcloud or the File Preview of the Operation System like MacOS does it?

**Comment by nininia** [comment]
It is displayed by nextcloud I suppose.  I see file content in the same browser tab under address <*.*.*.*>/nextcloud/remote.php/webdav/Chcode/Dog/Form.html?downloadStartSecret=zi0zi3u9a3r
If I push a back arrow in the browser, I will return to my nextcloud directory.

**Comment by j-ed** [comment]
If you select download under the 3-dots menu and the file directly opens, your web browser is most likely configured incorrectly. In Firefox you have to go to **Settings->General->Applications** and set the action to be done for `html` files to **ask each time**.

![grafik](https://user-images.githubusercontent.com/2572764/52998581-ee6aff00-3423-11e9-9404-5b9541637561.png)

**Comment by nininia** [comment]
Thank you for your attention! :) It is really important to me to clarify this issue. 
It stills not clear for me why it is trying to display instead of direct downloading?  I use chrome , but in firefox behavior is the same. And one more moment: I have nothing  for html file under application section :( 
![image](https://user-images.githubusercontent.com/45385367/53001613-22521e80-343c-11e9-9213-7989b0a6a72e.png)

**Comment by j-ed** [comment]
The reason for this behavior is, that you've told your local system to action that kind of file that
way. A similar dialog exists for Chrome and also your Windows PC, as explained in this article: https://smallbusiness.chron.com/change-way-open-files-google-chrome-78706.html

**Comment by nininia** [comment]
**I suspect that something wrong with 'three dots->download' function.**

Look, I run some additional tests and this is my result:

*if i choose file (pdf, css,html,svg) by checkbox and that push 'three dots->download' at **the top** of the page, that everything is working
![image](https://user-images.githubusercontent.com/45385367/53014994-014cf600-345b-11e9-8b9d-fb02ad9df10d.png)

*if I push 'three dots->download' at the **right side** of file , some file type cannot be downloaded  (pdf, css,html,svg)

![image](https://user-images.githubusercontent.com/45385367/53015069-2d687700-345b-11e9-847e-a34517db934c.png)

**Comment by j-ed** [comment]
Unfortunately you've not provided any information about what Nextcloud version you are using, but I cannot replicate the described behavior with v15.0.4. In both cases, using the download function on top of the file list or behind the file, the file is handled based on the configured browser and system setting.

BTW, your screenshot shows that you're choosing the download function for a directory. In this case Nextcloud is providing a zip archive for download which is a different file type than a pdf file 😉 

I still recommend to focus on the Chrome and Windows file system settings for e.g. pdf files. What about that, have you checked it and how are they set?

**Comment by nininia** [comment]
I use Cloud Disk 14.0.4.
Sorry for some mistakes with the last screenshot, I just wanted to show which dots are used:)
Directory is downloaded by zip file, correct.  Problem is with some file format (pdf, css,html,svg).
I can reproduce this problem with Nextcloud 15.0.0.

This is settings of my browser:
![image](https://user-images.githubusercontent.com/45385367/53017073-3a3b9980-3460-11e9-8801-c0d46a489039.png)

**Comment by j-ed** [comment]
That the problem appears with v14.0.4 and v15.0.0 seems to be clear to me because it is not a problem of Nextcloud but a configuration problem of your desktop/browser. Unfortunately I'm not using Chrome support you further. but have you tried to delete the file association as shown in your screenshot? I would expect that it solves the problem.

**Comment by nininia** [comment]
I delete file association on chrome and set all checkboxes for firefox. PDF, SVG files might be downloaded, but as additional action from preview.
![image](https://user-images.githubusercontent.com/45385367/53069067-bf1fc500-34eb-11e9-9bf9-1c7d8f5abaa9.png)
You are right, need to play with browser setting for correct preview. 
I`m only confused why I see the file preview when I push 'download'? May be it make sense to rename 'download' to 'preview and download'?

**Comment by nininia** [comment]
You are right, looks like I have browser problem.
I fixed this problem for PDF file according to your recommendation. Now when I push download for it, PDF file will be opened in adobe flash, and download action is a part of opening application. It is working like 'save as' command. But what I should do for html file. It is opening in browser and no way to save it(. 
NC has 2 button download, but they do different thing. Upper button is downloading, side button is for preview

**Comment by rodriguesvalnison-a11y** [comment]
#55858

**Comment by rodriguesvalnison-a11y** [comment]
[](url)
