### ISSUE TITLE
Remove group from sharing exclusion when deleting a user group

### ISSUE THREAD

**Issue by tkald** [nextcloud/server#14260]
Groups won't get removed from sharing exclusion when deleting a user group. NC 14 & 15.
So when you delete a user group what's excluded from sharing, it brokes group exclusion option.
See #13647

**Comment by skjnldsv** [comment]
Hello, so this is the same issue as #13647?

**Comment by tkald** [comment]
Yes, it is a cause of an issue #13647

**Comment by skjnldsv** [comment]
Then closing as duplicate.
