### ISSUE TITLE
No translation - Restore

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#14274]
### Steps to reproduce
1. Create a file.
2. Delete file.
3. Open `Deleted files`.
4. Select the deleted file.
5. Choose an action `:`.

### Expected behaviour
Translated word `Restore`.

### Actual behaviour
No translated word `Restore`.
![obraz](https://user-images.githubusercontent.com/47037905/52976087-5db30580-33c8-11e9-93dc-aac1126520f8.png)

### Additional information
Translation is in files:
`apps/files_trashbin/l10n/pl.js`
`apps/files_trashbin/l10n/pl.json`

value: `"Restore" : "Przywróć",` 

The translation concerns the code in the file:
`apps/files_trashbin/js/app.js`
```
{
   name: 'restore',
   displayName: t('files_trashbin', 'Restore'),
   iconClass: 'icon-history',
},
```
**No translation exists in different versions of Nexcloud.**

**Nextcloud version:**
15.0.4

**Comment by juliushaertl** [comment]
Already fixed with #14197
