### ISSUE TITLE
Webdav problems with pdf

### ISSUE THREAD

**Issue by Marcello-Schweiz** [nextcloud/server#14271]
### Steps to reproduce
i would like to connect to a nextcloud server which is provided by a hoster while using webdav and then mount the destination- cloud.yyyyy.yyy.ch as a drive within my windows notebook

### Expected behaviour
the setup of a new network drive in order to have access to my files within the cloud- based on nextcloud.

### Actual behaviour
1. There is no problem to setup the nextcloud as a drive within my notebook. i do add a new network drive while using the url 
2. I do verify the account information (username and password) 
3. the new "network drive" is ready and i do have access to it
4. when i do open now a .pdf file, i will be prompted to re-verfiy my login credentials
5. as long as the first pdf i have opened is still on- i can open further pdf files without getting prompted
6. if i do open a .doc or .xlsx, .ppt there is no need to re-verify

### PC Config
Win 10 combined with Office 365
PDF- Foxit- i've tested it with other pdf software with the same result

Hope that fits and looking forward to some response

Marcello

**Comment by Marcello-Schweiz** [comment]
add comment: of course the target would be to use the mapped drive and only verify the credentials once and not all the time if i do open .pdf files after i've closed the last one.

**Comment by violoncelloCH** [comment]
If I'm right that's something specific to Windows and the used applications. For some applications Windows handles the caching of the files (~downloads them to a temporary location to open it and saves it back to the webdav afterwards), but other applications choose to take there own way and download the file directly from the webdav directly and therefore prompt to (re)authenticate...
Or did I misunderstand you?

**Comment by Marcello-Schweiz** [comment]
good morning, first of all thank you for your response. indeed, more or less it is like this. now, is there a workaround to solve this?

**Comment by violoncelloCH** [comment]
hmm, none that I'm aware of... (expect of not using windows but linux ;) ) I can only suggest you to take a look at the support forum at https://help.nextcloud.com and search for or ask your question there :)
ahh, there is a drive client function for the nextcloud sync client planned: https://nextcloud.com/blog/nextcloud-introduces-virtual-drive-in-desktop-client-to-simplify-desktop-integration/ maybe this would/will help there :)

anyway nothing nextcloud could do about here...

**Comment by Marcello-Schweiz** [comment]
thanx for supporting in this case.
Marcel
