### ISSUE TITLE
Check if database user and databases exists before attempting to create them

### ISSUE THREAD

**Issue by ypid** [nextcloud/server#1428]
Sorry for cross posting but I expect that NextCloud is also affected by https://github.com/owncloud/core/issues/26126 ?

**Comment by nickvergessen** [comment]
Yeah I guess we could try to avoid it.

**Comment by harry-7** [comment]
I would like to work on this issue. Can some one guide me on how to start it?

**Comment by MorrisJobke** [comment]
Fixed by #1958
