### ISSUE TITLE
Allow apps to register icons

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#14286]
The SCSS compile is great and the same holds true for the way we use it for accessibility, themeing and apps etc.

However. With the recent app bundling in webpack etc. It has become clear that the mixins pose somewhat of an issue here. As that means that an app that uses them can't have statically compiled SCSS but instead relies on the server to do this. Which causes additional requests, server load etc.

A possible solution would be to have a way for apps to register their icons. These are then injected into the icons.scss we already have (on the fly once it is compiled of course).

We could do some smart things.

1. Invalidate the icons.scss when an app gets enabled/updated/disabled
2. Automatically regenerate it then

For future work we could look at the other mixins but for now I think icons is theone used mosts.

CC: @juliushaertl @skjnldsv @ChristophWurst

**Comment by skjnldsv** [comment]
Cancelled, those icons are deprecated, we mostly use inline svg from the material design icon
