### ISSUE TITLE
Getting different server errors like 503, 0 response when trying to view files through PDF.JS

### ISSUE THREAD

**Issue by Sterlingtech** [nextcloud/server#14295]
Hi

We have PDF.JS integrated with our web application. We are getting the following errors when trying to view files through PDF.JS. This is happening to our users from various locations. They tried with different browsers. When we tried to open the file from our end we are able to open it without any issues. Please let us know the root cause of this issue and why it is happening?

![unexpected server response 0](https://user-images.githubusercontent.com/40163020/53048969-02fad600-34bc-11e9-99ba-0bac7d6834a2.PNG)
![invalide or corrupted file](https://user-images.githubusercontent.com/40163020/53048530-fb86fd00-34ba-11e9-914f-2caa4bb6a8e5.PNG)
![invalide or corrupted file 2](https://user-images.githubusercontent.com/40163020/53048552-093c8280-34bb-11e9-8db0-9c321e8f8420.PNG)

1. Unexpected server response 503 while retrieving PDF.
2. Unexpected Server response 0 while retrieving
PDF.jS V1.9.426 (build 2558a58d)
Message: Unexpected Server Response (0) while retrieving
3. Invalid or corrupted PDF file, When clicked on more information Message: Invalid PDF structure(PDF.jS V1.9.426 (build 2558a58d))

Additional information: A few of our clients enabled Adobe plugins in IE.

**Comment by Sterlingtech** [comment]
Guys any help or update on this issue

**Comment by Sterlingtech** [comment]
Guys any help or update on this issue

**Comment by kesselb** [comment]
Could you explain how this problem is related to nextcloud? The pdf.js viewer is showing a pdf file from a nextcloud instance?

It would be very helpful if you could provide the information from https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md

**Comment by Sterlingtech** [comment]
you can close this raised in a wrong windows
