### ISSUE TITLE
Problems reset admins password

### ISSUE THREAD

**Issue by Fluke667** [nextcloud/server#14294]
> php occ user:resetpassword Fluke667
> Warning: Resetting the password when using encryption will result in data loss!
> Do you want to continue?  
> Enter a new password: 
> Confirm the new password: 
> Error while resetting password!

This is what i get in the terminal and the Password reset Button on web not working too... Its an admin password.

**Comment by oz42** [comment]
I can confirm that the reset password web link does not work. Nothing shows up in the server's log when entering a new password, so the link seems to be broken.

**Comment by ChristophWurst** [comment]
Please use the issue template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md :v:
