### ISSUE TITLE
 Ldap user disable error

### ISSUE THREAD

**Issue by Diego-shi** [nextcloud/server#14296]
**Expected behaviour**

When the ldap user is disabled, the user's share is automatically cancelled.

**Actual behaviour**

Log error after ldap user is disabled:
{"reqId":"41mLi5Sm8pfz6kf6j5pf","level":3,"time":"2019-02-20T03:00:06+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"OC\\User\\NoUserException","Message":"7DC42BE2-****-****-****-E0D7905E4777 is not a valid user anymore","Code":0,"Trace":[{"function":"getHome","class":"OCA\\User_LDAP\\User_LDAP","type":"->","args":["7DC42BE2-****-****-****-E0D7905E4777"]},{"file":"/opt/nextcloud/apps/user_ldap/lib/User_Proxy.php","line":81,"function":"call_user_func_array","args":[[{"__class__":"OCA\\User_LDAP\\User_LDAP"},"getHome"],["7DC42BE2-****-****-****-E0D7905E4777"]]},{"file":"/opt/nextcloud/apps/user_ldap/lib/Proxy.php","line":152,"function":"walkBackends","class":"OCA\\User_LDAP\\User_Proxy","type":"->","args":["7DC42BE2-****-****-****-E0D7905E4777","getHome",["7DC42BE2-****-****-****-E0D7905E4777"]]},{"file":"/opt/nextcloud/apps/user_ldap/lib/User_Proxy.php","line":227,"function":"handleRequest","class":"OCA\\User_LDAP\\Proxy","type":"->","args":["7DC42BE2-****-****-****-E0D7905E4777","getHome",["7DC42BE2-****-****-****-E0D7905E4777"]]},{"file":"/opt/nextcloud/lib/private/User/User.php","line":282,"function":"getHome","class":"OCA\\User_LDAP\\User_Proxy","type":"->","args":["7DC42BE2-****-****-****-E0D7905E4777"]},{"file":"/opt/nextcloud/lib/private/Files/Storage/Home.php","line":53,"function":"getHome","class":"OC\\User\\User","type":"->","args":[]},{"file":"/opt/nextcloud/lib/private/Files/Mount/MountPoint.php","line":147,"function":"__construct","class":"OC\\Files\\Storage\\Home","type":"->","args":[{"user":{"__class__":"OC\\User\\User"}}]},{"file":"/opt/nextcloud/lib/private/Files/Mount/MountPoint.php","line":172,"function":"createStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":[]},{"file":"/opt/nextcloud/lib/private/Files/Filesystem.php","line":321,"function":"getStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":[]},{"file":"/opt/nextcloud/lib/private/Files/Filesystem.php","line":443,"function":"getStorage","class":"OC\\Files\\Filesystem","type":"::","args":["7DC42BE2-****-****-****-E0D7905E4777"]},{"file":"/opt/nextcloud/apps/files_sharing/lib/SharedStorage.php","line":127,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["7DC42BE2-****-****-****-E0D7905E4777"]},{"file":"/opt/nextcloud/apps/files_sharing/lib/SharedStorage.php","line":482,"function":"init","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[]},{"file":"/opt/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":495,"function":"getWrapperStorage","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[]},{"file":"/opt/nextcloud/apps/files_sharing/lib/SharedStorage.php","line":166,"function":"instanceOfStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["OC\\Files\\Storage\\FailedStorage"]},{"file":"/opt/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":495,"function":"instanceOfStorage","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":["OC\\Files\\Storage\\FailedStorage"]},{"file":"/opt/nextcloud/lib/private/Files/Utils/Scanner.php","line":150,"function":"instanceOfStorage","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["OC\\Files\\Storage\\FailedStorage"]},{"file":"/opt/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php","line":88,"function":"backgroundScan","class":"OC\\Files\\Utils\\Scanner","type":"->","args":[""]},{"file":"/opt/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php","line":112,"function":"runScanner","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[{"__class__":"OC\\User\\User"}]},{"file":"/opt/nextcloud/lib/private/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\Files\\BackgroundJob\\ScanFiles","type":"->","args":[null]},{"file":"/opt/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/opt/nextcloud/cron.php","line":123,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/opt/nextcloud/apps/user_ldap/lib/User_LDAP.php","Line":437,"CustomMessage":"--"},"userAgent":"--","version":"15.0.4.0","id":"5c6cc68327984"}

**### Server configuration**

**Operating system**:CentOS 7.2

**Web server:**Nginx

**Database:**MySQL

**PHP version:**7.1.25

**Nextcloud version:** 15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**Updated from 14.0.4

**Where did you install Nextcloud from:**tar.gz from nextcloud site

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by blizzz** [comment]
There is no standardized way of "disabled" in LDAP. So, what is exactly done? It seems the user is not visible for the Nextcloud configuration anymore, thus appears removed.  That's intended in this case.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
