### ISSUE TITLE
Windows WebDAV authentication fails if the NC server has with spaces and "" set in Themes's site name

### ISSUE THREAD

**Issue by osscombat** [nextcloud/server#14303]
NC version: 15.0.4

The setup is a basic NC/Apache install with basic user authentication. I needed to use a WebDAV access on a Windows client, i.e. network drive mapping. After all, it turned out that the windows client fails to authenticate while mapping to the NC server (over https), if the server name in the Themes have spaces or "" signs. When I reset it to the default "Nextcloud", or just one word, the Windows client authenticates fine and maps the drive.

**Comment by skjnldsv** [comment]
Do you have windows logs please?
