### ISSUE TITLE
Save link share expiration date on blur()

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#14307]
If you change the expiration date on a link share by typing, it is only saved if you press enter or select the date in the calender.

If you change the focus and click the three dots again, the changed but not saved date is still shown.

If you open settings of an other link share and open that one again, the original expiration date is shown.

An user created a lots of shares and pasted the date. Now all links are now expired because it was not saved.

So I think it would be good to save the date on blur().

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
Yes - makes sense 👍 

cc @nextcloud/javascript
