### ISSUE TITLE
TOTP button not tinted

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#14317]
![image](https://user-images.githubusercontent.com/5836855/53132758-fab0a280-3570-11e9-924f-cdcf064ac81e.png)

- have custom theme color
- try to login with TOTP
- see wrong button color

@nextcloud/designers

**Comment by skjnldsv** [comment]
@juliushaertl @nextcloud/theming

**Comment by juliushaertl** [comment]
Still happens for non bright colors, as reported in #559

**Comment by tobiasKaminsky** [comment]
Still happens with NC17 RC1

**Comment by Bernd-L** [comment]
Should this issue be migrated to <https://github.com/nextcloud/twofactor_totp/issues>?

**Comment by tobiasKaminsky** [comment]
> Should this issue be migrated to https://github.com/nextcloud/twofactor_totp/issues?

No, it was there once, but as this is provided via a generic site, this is a server repo issue.

**Comment by NewRedsquare** [comment]
Just a note : The issue is still here with Nextcloud 19.0.0.12

**Comment by skjnldsv** [comment]
@NewRedsquare as long as this issue is opened, this is indeed not fixed :)

**Comment by juliushaertl** [comment]
Fixed as part of https://github.com/nextcloud/server/pull/21988

**Comment by eibex** [comment]
I can still reproduce this on Nextcloud 24
