### ISSUE TITLE
Restore federated share on restore from trashbin

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#14328]
It would be good if federated shares would follow the same behaviour as local shares on restore from the trashbin.

1. userA on serverA shares a file to userB on serverB
2. userB accepts the share
3. userA deletes the file
4. userB refreshes and tries to access the share
5. userA restroes the share

There are two issues

At step 4 the share still shows and we get a 404. Which is bad
At step 5 the share should be restored.

**Comment by rullzer** [comment]
At the very least there should be a gracefull error message at 4. :wink:

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
