### ISSUE TITLE
Unable to close tooltip and clear the file name error

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#1433]
### Steps to reproduce

1.Create a file. For example:
`file a.txt`
2.Create a another file. For example:
`file b.txt`
3.Try to rename the second file with the same as the first one. Make sure there is a tooltip appeared.
4.With the tooltip showing, trying to create a file with a duplicate name. There will be error message saying file already exist.
5. Close the new file pop over menu by clicking blank area.
6. Verify that the first tooltip is still there. Press "ESC" key or click blank area or select a different file. Verify that the tooltip will not be closed and the file name error will not be cleared.
### Expected behaviour

Should be able to close the tooltip and clear the file name error.
### Actual behaviour

Unable to close tooltip and clear the file name error
<img width="1238" alt="screen shot 2016-09-17 at 5 16 23 pm" src="https://cloud.githubusercontent.com/assets/19603943/18607351/ad44aee4-7cfc-11e6-9ca1-544edaac3d29.png">
### Server configuration

**Operating system**:
CentOS 7 x86_64
Linux 10.211.55.9 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
httpd-2.4.6-40.el7.centos.4.x86_64

**Database:**
sqlite3

**PHP version:**
PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**

**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Firefox ESR 38.3.0

**Operating system:**
CentOS 7 x86_64

**Comment by nickvergessen** [comment]
You can press the `Esc` key to get rid of it. But yeah I guess some visual way out would be nice.

@nextcloud/designers

**Comment by eppfel** [comment]
No. The problem is, that the first dialog (rename)  is not active anymore. You have to click the input and then ESC works.

I think the rename dialog should be closed when not active (click somewhere else).

**Comment by jancborchardt** [comment]
Seems like something for @nextcloud/javascript :)

**Comment by sagorika1996** [comment]
I'm taking this up.
