### ISSUE TITLE
[core] Error: OCP\Files\NotPermittedException:  after update NC 15.05

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#14334]
[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 62
   delete()
1. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 48
   expireFolder({id: 4,mount_poi ... 0})
2. /var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   expireAll()
3. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   run(null)
4. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/nextcloud/cron.php line 123
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-02-21T20:45:02+01:00

Also have many errors like this:
[PHP] Error: Object of class OCA\GroupFolders\Versions\GroupVersion could not be converted to string at /var/www/nextcloud/apps/groupfolders/lib/Versions/ExpireManager.php#126

Upgraded Groupfolder app today, have version 2.0.3 
at 2019-02-21T19:30:02+01:00

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:**

**PHP version:** Last

**Nextcloud version:** (see Nextcloud admin page) NC15.05

**fresh install:**

**Comment by a1pilot** [comment]
Same issue here.  @rollanders did you manage to fix it?

**Comment by rollanders** [comment]
Still same error:

[core] Error: OCP\Files\NotPermittedException:  at <<closure>>

0. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 62
   delete()
1. /var/www/nextcloud/apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 48
   expireFolder({id: 4,mount_poi ... 0})
2. /var/www/nextcloud/apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
   expireAll()
3. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   run(null)
4. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/nextcloud/cron.php line 123
   execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2019-04-17T19:45:02+02:00
