### ISSUE TITLE
Move Caret and AtWho to proper webpack dependencies so they are kept up to date

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#14344]
See #14227

However it seems they are not maintained so maybe moving to something else makes sense?

CC: @ChristophWurst

**Comment by ChristophWurst** [comment]
cc @blizzz :)

**Comment by blizzz** [comment]
:panda_face: the suggested replacement is TributeJS, available on npm. I understand this is post #14227, right?

**Comment by ChristophWurst** [comment]
Yes!

**Comment by blizzz** [comment]
even missed the 17 milestone 🤦‍

**Comment by blizzz** [comment]
Seems the dep was removed in 21
