### ISSUE TITLE
Login and Registration Issues

### ISSUE THREAD

**Issue by connor1mcdonald** [nextcloud/server#14341]
I have had my NextCloud instance installed for sometime now, with no issues until I updated "group folders" and some other apps - to which is where issues began to arise. However, during registration - through the registration app in the store - users are confronted with an internal server error. Then this morning, I thought that the PHP version may have been to fault. I then set the php version on 7.1 (it was on 7.2 prior) but once attempting the registration process again to see if that had fixed the issue, the internal server error still occurred. I then reverted it back to PHP 7.2 and that is when I noticed that all users were left unable to login to the cloud portal, even myself as the admin of the instance was left locked out with "wrong password" notices being displayed. I then reset the admin password, thinking that would resolve it, but it didn't.

I'm not entirely sure of what this issue could be. My instinct says that it may be a DB issue. Any ideas?

**Comment by j-ed** [comment]
Unfortunately you're not providing enough information to help you on this issue, nor have you provided version numbers, detailed error messages, log files etc. etc., Can you please use the issue template, which is shown by default if you're opening a new issue ticket, and provide the missing information: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
