### ISSUE TITLE
Super slow server. 14.0.4. Loads in 5 + secs on epic hardware

### ISSUE THREAD

**Issue by MarcelDutko** [nextcloud/server#14348]
### Steps to reproduce
My nextcloud (14.0.4) is super slow. It loads in 5 seconds. 

My hardware:
1TB ssd
300MB/s network download; 20MB upload
i7 Intel
32GB ram (for php 4096MB)

I tried reinstalling it, but still the same issue. Please help

### Expected behaviour
It should be way faster. My hardware is good enough for it.

My hardware:
1TB ssd
300MB/s network download; 20MB upload
i7 Intel
32GB ram (for php 4096MB)

### Actual behaviour
My nextcloud (14.0.4) is super slow. It loads in 5 seconds. 

My hardware:
1TB ssd
300MB/s network download; 20MB upload
i7 Intel
32GB ram (for php 4096MB)

I tried reinstalling it, but still the same issue. Please help

## Server configuration detail

**Operating system:** Linux 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:44:00 UTC 2018 i686

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.24

**PHP version:** 

7.2.10-0ubuntu0.18.04.1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, mapi, exif, memcache, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, pspell, readline, recode, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 14.0.4 - 14.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** nextcloud.com

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.0.1
 - activity: 2.7.0
 - admin_notifications: 1.0.2
 - announcementcenter: 3.3.1
 - apporder: 0.6.0
 - bookmarks_fulltextsearch: 1.0.0
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.4
 - cloud_federation_api: 0.0.1
 - comments: 1.4.0
 - dav: 1.6.0
 - drawio: 0.9.2
 - external: 3.1.0
 - federatedfilesharing: 1.4.0
 - files: 1.9.0
 - files_downloadactivity: 1.3.0
 - files_fulltextsearch: 1.1.3
 - files_linkeditor: 1.0.10
 - files_pdfviewer: 1.3.2
 - files_rightclick: 0.11.0
 - files_sharing: 1.6.2
 - files_texteditor: 2.6.0
 - files_trashbin: 1.4.1
 - files_versions: 1.7.1
 - files_videoplayer: 1.3.0
 - fulltextsearch: 1.1.1
 - gallery: 18.1.0
 - gpxedit: 0.0.10
 - group_everyone: 0.1.1
 - groupfolders: 2.0.3
 - impersonate: 1.1.0
 - issuetemplate: 0.4.0
 - jsloader: 1.0.2
 - logreader: 2.0.0
 - lookup_server_connector: 1.2.0
 - mail: 0.11.0
 - metadata: 0.9.0
 - music: 0.9.3
 - nextcloud_announcements: 1.3.0
 - notifications: 2.2.1
 - oauth2: 1.2.1
 - password_policy: 1.4.0
 - phonetrack: 0.4.3
 - provisioning_api: 1.4.0
 - quota_warning: 1.3.0
 - registration: 0.4.5
 - serverinfo: 1.4.0
 - sharebymail: 1.4.0
 - sharerenamer: 2.3.0
 - spreed: 4.0.3
 - survey_client: 1.2.0
 - systemtags: 1.4.0
 - terms_of_service: 1.0.3
 - theming: 1.5.0
 - theming_customcss: 1.2.0
 - twofactor_backupcodes: 1.3.1
 - updatenotification: 1.4.1
 - user_usage_report: 1.1.1
 - workflowengine: 1.4.0
 - xray: 0.2.1
Disabled:
 - admin_audit
 - caniupdate
 - drop_account
 - encryption
 - federation
 - files_antivirus
 - files_external
 - firstrunwizard
 - onlyoffice
 - ownpad
 - polls
 - richdocuments
 - scanner
 - sociallogin
 - socialsharing_email
 - support
 - twofactor_totp
 - unsplash
 - user_backend_sql_raw
 - user_external
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "marcloud.net",
        "192.168.1.143",
        "marcel.ddns.net",
        "89.71.209.171"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "14.0.4.2",
    "overwrite.cli.url": "http:\/\/localhost\/cloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtpsecure": "ssl",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "integrity.check.disabled": true,
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "knowledgebaseenabled": false,
    "allow_user_to_change_display_name": true,
    "syslog_tag": "marCloud",
    "auth.bruteforce.protection.enabled": true,
    "skeletondirectory": "\/var\/www\/html\/cloud-skeletonfiles\/",
    "appcodechecker": false,
    "updatechecker": true
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** true

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.109 Safari/537.36

**Operating system:** Windows 10 PRO latest

## Logs

<details><summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
Please use https://help.nextcloud.com/ for configuration issues. 

There are some issues here about improving the performance in general (like bundling assets, etc..).  We have information about "tuning" in the documentation: https://docs.nextcloud.com/server/stable/admin_manual/installation/server_tuning.html (e.g you are not using memory cache).

I would not call that hardware epic but yes :rocket:
