### ISSUE TITLE
set profile to private/public on new user creation

### ISSUE THREAD

**Issue by rubo77** [nextcloud/server#14358]
I'm always frustrated when I create multiple users and for them not to show up as contact in all other user contact lists, I have to log in as the new user and set the profile to private.

### Solution:

An option box to set the profile private in the user create dialogue

### Alternatives: 

1. set users profile to private per default, but this could lead to frustration if others want to have all users public per default
2. a setting in the config file that defines private or public for new users

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/6582.

@skjnldsv what to do?

**Comment by skjnldsv** [comment]
Pick one, keep one :)
