### ISSUE TITLE
feature suggestion: push server settings  to mobile clients

### ISSUE THREAD

**Issue by jookk** [nextcloud/server#14357]
I have now situation, that I changed server url and it is meals impossible to meet all to set new url.
So if possible, I want suggest some solution to push server settings to clients.

**Comment by alex6480** [comment]
I would set up Apache or NGINX to serve all pages on the old server with a permanent redirect (302) to the new server. I would think that would work.

Nginx:
`server {
  server_name .mydomain.com;
  return 301 http://www.adifferentdomain.com$request_uri;
}`

It would make sense if the clients automatically changed their settings in this situation, I don't know if that is the case. If not, that would have to be implemented on a per client basis.

**Comment by jookk** [comment]
Thank You, redirect is good idea

Dňa 24. februára 2019 19:06:17 používateľ alex6480 
<notifications@github.com> napísal:
