### ISSUE TITLE
In list view, clicking on thumbnail / filetype / folder icon opens sidebar and not file/folder

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#14350]
This seems a regression to something we fixed before? When you click on the thumbnail of a file it opens the sidebar, and only when you click the name it opens the file/folder itself.

Of course it should open the file/folder no matter if you click the name or the thumbnail. Especially for images, people often click on the thumbnail, and then nothing happens (except the sidebar).

cc @nextcloud/javascript

**Comment by szaimen** [comment]
Any update on this?

**Comment by jancborchardt** [comment]
@GretaD is this something you might be interested in looking at? :)

**Comment by reiner-text** [comment]
> Of course it should open the file/folder no matter if you click the name or the thumbnail.

Nevertheless, it is a quick and easy way to open the sidebar without multiple clicks. I like this bug.

**Comment by szaimen** [comment]
@reiner-text I wouldn't say that this isn't a good shortcut, but that is not the most intuitiv way to open the sidebar. I bet, that most of the people just klick on the icon to open the file/folder and have not in mind to open the sidebar and are then just irritated because the the sidebar opens.
BTW: if you want to open the sidebar with one click, you can always click on the "share"-icon. It just opens the share-sidebar and does not share the file immediately.

**Comment by galsondor** [comment]
I brought up NextCloud yesterday.  So, I though I would add a new NextCloud user perspective to this discussion (I am, however, a software engineer).  I reached this topic while searching DuckDuckGo for "NextCloud list view open folder".  I performed this search while wondering why clicking a folder in grid view opens the folder and clicking in list view does not.  This incongruity is a usability issue that should be addressed.

From a training, support, and acceptance perspective, I suggest mimicking the behavior of products with similar functions (e.g. Finder, Explorer, etc.).  Personally, I can deal with this difference, even if I find in inconvenient.  However, when I think of the members my church music group (who only have basic computer skills), I am concerned that this difference from the norm will impede acceptance.  Besides, the details are available on the right click menu.

Thanks.

**Comment by kesselb** [comment]
@GretaD is this fixed with #16969 :thinking:

**Comment by szaimen** [comment]
@kesselb but probably just for Nextcloud 17? 🤔

**Comment by GretaD** [comment]
> @GretaD is this fixed with #16969 thinking

Yes, it is fixed, but only for 17. @juliushaertl @jancborchardt should we backport it for 15 and 16 also?

**Comment by juliushaertl** [comment]
Yes, good one to backport I think.

**Comment by DavidDzl** [comment]
I know it's gonna be a bit of off-topic, but I don't want to create new specific issue for such small problem. 

I need to locate file/template, which is responsible for creating thumbnails/preview on a sidebar. Can somone tell me, where that file might be?

**Comment by jancborchardt** [comment]
@galsondor thanks a ton for your user perspective! :) That really helps a lot to design things to be easily usable. Don’t hesitate to give feedback on other issues too or open issues about things you encounter.

**Comment by jancborchardt** [comment]
Backport to stable16 at https://github.com/nextcloud/server/pull/17091, please review. :)
