### ISSUE TITLE
Install from Snap fails (mysql setup problem)

### ISSUE THREAD

**Issue by mikesi** [nextcloud/server#14359]
Running:
nextcloud.manual-install adminuser somepassword
the command hangs on:
Waiting for PHP...

Checking the system logs:
Feb 23 19:10:57 nextcloud nextcloud.php-fpm[12802]: Waiting for MySQL...
Feb 23 19:10:57 nextcloud nextcloud.mysql[12779]: Starting MySQL
Feb 23 19:10:57 nextcloud nextcloud.apache[12849]: Waiting for PHP...
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: Saving debug log to /var/snap/nextcloud/current/certs/certbot/logs/letsencrypt.log
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: No renewals were attempted.
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: No hooks were run.
Feb 23 19:10:59 nextcloud nextcloud.renew-certs[12794]: - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
Feb 23 19:11:02 nextcloud mysqld_safe[14025]: Starting mysqld daemon with databases from /var/snap/nextcloud/11688/mysql
Feb 23 19:11:02 nextcloud mysqld[14027]: /snap/nextcloud/11688/bin/mysqld (mysqld 5.7.22-log) starting as process 14027 ...
Feb 23 19:11:02 nextcloud mysqld[14027]: failed to set datadir to /var/snap/nextcloud/11688/mysql/
Feb 23 19:11:02 nextcloud mysqld[14027]: Aborting
Feb 23 19:11:02 nextcloud mysqld[14027]: Binlog end
Feb 23 19:11:02 nextcloud mysqld[14027]: /snap/nextcloud/11688/bin/mysqld: Shutdown complete
Feb 23 19:11:02 nextcloud mysqld_safe[14033]: mysqld from pid file /tmp/pids/mysql.pid ended
Feb 23 19:11:03 nextcloud nextcloud.mysql[12779]: ...... * The server quit without updating PID file (/tmp/pids/mysql.pid).
Feb 23 19:11:03 nextcloud nextcloud.mysql[12779]: sed: can't read /var/snap/nextcloud/11688/mysql/root.ini: No such file or directory
Feb 23 19:11:03 nextcloud nextcloud.mysql[12779]: Waiting for MySQL...

Seems that mysql setup fails (can't set owner of data directory) and the install process just hangs and waits.

OS:
Ubuntu 18.04.2 LTS

Snap info:
installed:      15.0.4snap1                  (11688) 196MB -

**Comment by BernieO** [comment]
This is actually in the wrong repository. It should be moved to https://github.com/nextcloud/nextcloud-snap...

`nextcloud.manual-install` requires `sudo` to run successfully. Did you issue the command with `sudo`?
See here: https://github.com/nextcloud/nextcloud-snap/wiki/Included-CLI-utilities

**Comment by mikesi** [comment]
Oh, I see that's the wrong repo, I can open another issue there.
It was run as root.

**Comment by BernieO** [comment]
Running as root is not enough. Even with as root you need to run it with sudo!

**Comment by BernieO** [comment]
Opened also in nextcloud-snap: https://github.com/nextcloud/nextcloud-snap/issues/913
Can be closed here.
