### ISSUE TITLE
Replace Logs in Admin Settings with icewind's Log reader

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#1436]
Since Nextcloud 10 and its split of the admin page, the log reader has enough space to show up more and advanced information ... Like the log reader app (https://github.com/icewind1991/logreader) already does 😉 

I think we should integrate this directly into the administrator page.

cc @icewind1991 @blizzz @nextcloud/designers 

Follow up of: https://github.com/nextcloud/server/issues/712#issuecomment-238607452

**Comment by MorrisJobke** [comment]
Done - see #2134 and #2214
