### ISSUE TITLE
Unable to install new apps from app store on NC 10.0.1RC1

### ISSUE THREAD

**Issue by Florentin68** [nextcloud/server#1437]
### Steps to reproduce
1. Go to App Store page
2. Click on 'Activate' on a non already installed app

### Expected behaviour
Download and install the app

### Actual behaviour
Red error box displaying : "Directory name must not be empty."

### Server configuration
**Operating system**:
Debian 8
**Web server:**
Apache 2.4.10
**Database:**
MySQL 5.6.33
**PHP version:**
5.6.24
**Nextcloud version:** (see Nextcloud admin page)
10.0.1 RC1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 10.0.0 beta (9.1.0.16)
**Where did you install Nextcloud from:**
Updater script
**Signing status:**
<details>
<summary>Signing status</summary>
Integrity checker has been disabled. Integrity cannot be verified.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - keeweb
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ocf68c4d5247",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "dbtype": "mysql",
        "version": "9.1.1.0",
        "installed": true,
        "maxZipInputSize": 838860800,
        "allowZipDownload": true,
        "theme": "",
        "blacklisted_files": [
            ".htaccess"
        ],
        "quota_include_external_storage": false,
        "maintenance": false,
        "forcessl": true,
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "mail_from_address": "noreply",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "loglevel": 2,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "syslog_tag": "Nextcloud",
        "log.condition": {
            "shared_secret": "***REMOVED SENSITIVE VALUE***",
            "users": [],
            "apps": []
        },
        "logdateformat": "d\/m\/Y H:i:s",
        "logtimezone": "Europe\/Paris",
        "log_query": false,
        "cron_log": false,
        "log_rotate_size": false,
        "customclient_desktop": "https:\/\/nextcloud.com\/install\/",
        "customclient_android": "https:\/\/play.google.com\/store\/apps\/details?id=com.nextcloud.client",
        "customclient_ios": "https:\/\/itunes.apple.com\/us\/app\/nextcloud\/id1125420102?mt=8",
        "overwritewebroot": "",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "appcodechecker": true,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "versions_retention_obligation": "auto",
        "trashbin_retention_obligation": "auto",
        "appstoreenabled": true,
        "appstoreurl": "http:\/\/api.owncloud.com\/v1",
        "appstore.experimental.enabled": true,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "cache_path": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": false,
        "check_for_working_htaccess": true,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.org\/updater_server\/",
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### Web server error log
<details>
<summary>Web server error log</summary>
[Sun Sep 18 13:32:08.586459 2016] [:error] [pid 7989] [client 83.141.191.93:32992] PHP Warning:  hash_equals(): Expected user_string to be a string, null given in /var/www/nextcloud/lib/private/Log.php on line 275
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Error	PHP	hash_equals(): Expected user_string to be a string, null given at /var/www/nextcloud/lib/private/Log.php#275	18/09/2016 13:32:08	florentin
Error	core	Directory name must not be empty.	18/09/2016 13:32:08	florentin
Error	PHP	Undefined variable: folder at /var/www/nextcloud/lib/private/App/CodeChecker/CodeChecker.php#91	18/09/2016 13:32:08	florentin
Error	PHP	Undefined variable: folder at /var/www/nextcloud/lib/private/App/CodeChecker/CodeChecker.php#87	18/09/2016 13:32:08	florentin
Error	PHP	Missing argument 2 for OC\App\CodeChecker\CodeChecker::analyseFolder(), called in /var/www/nextcloud/lib/private/Installer.php on line 617 and defined at /var/www/nextcloud/lib/private/App/CodeChecker/CodeChecker.php#79	18/09/2016 13:32:08	florentin
Error	PHP	Undefined variable: folder at /var/www/nextcloud/lib/private/App/CodeChecker/CodeChecker.php#87	18/09/2016 13:32:08	florentin
Error	PHP	Missing argument 2 for OC\App\CodeChecker\CodeChecker::analyseFolder(), called in /var/www/nextcloud/lib/private/Installer.php on line 617 and defined at /var/www/nextcloud/lib/private/App/CodeChecker/CodeChecker.php#79
</details>

**Comment by nickvergessen** [comment]
The app is uploaded incorrectly then.
Nothing we can do about this. Our new app store will take care of things like this, but for the old app store we can't help it.

**Comment by Florentin68** [comment]
I get this message with every app in the store.
Idem with NC 10.0.1

**Comment by ccoenen** [comment]
Me too.

**Comment by ccoenen** [comment]
I solved this by unzipping the apps manually in the `apps/` directory.

**Comment by corwin78** [comment]
The same issue NC10.0.1, Ubuntu server 16.04.1 64bit - after upgrade from NC 10.0 all applications disabled themselves, and can't be enabled again, with error message mentioned in this bug. Manually installed apps are working correctly.

**Comment by Arsimael** [comment]
This bug affects Everyone which downloads the 10.0.1 from the Homepage. 
It still works with the 10.0.0 so whatever you changed in 10.0.1, please revert the changes. 
You can
t even use the official Apps like Calendar and Contacts anymore, which makes nextcloud pretty much USELESS!

**Comment by mightyBroccoli** [comment]
I tested this issue on 5 different machines and it only occurs with the latest app store and the lastest stable release.
Setting the appcodechecker to false seems to fix the issue.

**Comment by nickvergessen** [comment]
I just now installed "Audio Player", "Contacts" and "Calendar" from the app store and it worked.

So I found a little detail: `"appcodechecker": true,` set this to false for now. I will make a patch to fix it in 10.0.2

**Comment by nickvergessen** [comment]
Fix is at https://github.com/nextcloud/server/pull/1683
