### ISSUE TITLE
Drag and Drop a directory to web Console not working IE 11

### ISSUE THREAD

**Issue by geokh** [nextcloud/server#14386]
Dear Developers:

Drag and Drop a directory to web Console not working IE 11 Nextcloud version 15.0.2.

Also, flow upload not showing the folder directory.

Regards
George KHouri

**Comment by tstreibl** [comment]
drag&drop is a browser and not a nextcloud feature. IE 11 is depreciated and doesn't support drag&drop. See https://help.nextcloud.com/t/enable-upload-of-folders-via-button-in-web-frontend/22531

**Comment by skjnldsv** [comment]
Yep, closing. Please use newer browser :)
