### ISSUE TITLE
The background colour of selected items are not consistent

### ISSUE THREAD

**Issue by m00z** [nextcloud/server#1438]
### Steps to reproduce

1.Create two hidden files which name beginning with "." (dot)
2.Create two normal files.
3.Click "Settings", check the "Show hidden files" checkbox
4.Select all the files. Check the background colour of selected items.
5.Uncheck the "Show hidden files" checkbox. Check the background colour of selected items.
### Expected behaviour

The background colour of selected items should keep consistent
### Actual behaviour

The background colour of selected items is not consistent
<img width="1211" alt="screen shot 2016-09-18 at 10 12 26 pm" src="https://cloud.githubusercontent.com/assets/19603943/18616459/af9617f8-7dee-11e6-8cf5-a3cce0bf9291.png">
<img width="1206" alt="screen shot 2016-09-18 at 10 12 58 pm" src="https://cloud.githubusercontent.com/assets/19603943/18616460/b3362df8-7dee-11e6-9574-f6276e6e35f0.png">
### Server configuration

**Operating system**:
CentOS 7 x86_64
Linux 10.211.55.9 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
httpd-2.4.6-40.el7.centos.4.x86_64

**Database:**
sqlite3

**PHP version:**
PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**

**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Firefox ESR 38.3.0

**Operating system:**
CentOS 7 x86_64

**Comment by MorrisJobke** [comment]
Fixed in 11.
