### ISSUE TITLE
Fileactions.js potensional problem.

### ISSUE THREAD

**Issue by nininia** [nextcloud/server#14381]
Last week I opened ticket "Open html file instead of download it. #14265"
It was more less clear what is the problem.
But I have decided to change the code  of download button for my NC .
I have found that side Download button code is located in the files\js\fileactions.js file, upper Download button code is located in the  files\js\filelist.js file.
Both functions look very similar except one thing.
In case of side Download there is no call of **event.preventDefault();**
Could you please advice me how to call it in registerDefaultActions: function() {..}? There is no event object(

**Comment by skjnldsv** [comment]
See an example of a working registerAction here https://github.com/nextcloud/viewer/blob/28a808870354fb34110288556fd0b8016d0c9d23/src/views/Viewer.vue#L439
