### ISSUE TITLE
Files not showing in Web UI, everything else appears to work ok.

### ISSUE THREAD

**Issue by cwhitsbm** [nextcloud/server#14393]
Hello,

We are unable to view files on a newly built webserver.  We can see all of the files from the NFS Share through the OS as www-data, but Nextcloud will not see the files.  On one server they can only be seen in Firefox and the other server will not display any files.  Errors from browser dial log are below.

Data was recently moved from a local VHDX to an NFS Share using NFS from Ubuntu 18.  While I am unable to access the data as root, I seem to have no problems reading or writing data as www-data.

### Steps to reproduce
1. Open Nextcloud in IE or Chrome
2. Files do not display
3. Errors in Browser Debug Log 

### Expected behaviour
Nextcloud should open and show the files in my profile.

### Actual behaviour
Browser window opens and no files are shown.  There seem to be no other issues with the application itself that we have found.

Errors in Browser diag log:
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Loading failed for the <script> with source “https://sbmhqncws-2/index.php/js/files/merged-index.js?v=0db267dc-7”. files:63:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
TypeError: OCA.Files is undefined[Learn More] sharedfilelist.js:30:2

    <anonymous> https://sbmhqncws-2/apps/files_sharing/js/sharedfilelist.js?v=0db267dc-7:30 <anonymous> https://sbmhqncws-2/apps/files_sharing/js/sharedfilelist.js?v=0db267dc-7:10 

TypeError: OCA.Files is undefined[Learn More] mountsfilelist.js:29:2

    <anonymous> https://sbmhqncws-2/apps/files_external/js/mountsfilelist.js?v=0db267dc-7:29 <anonymous> https://sbmhqncws-2/apps/files_external/js/mountsfilelist.js?v=0db267dc-7:10 

TypeError: OCA.Files is undefined[Learn More] filelist.js:44:2
TypeError: OCA.Files is undefined[Learn More] activity-sidebar.js:473:6

    <anonymous> https://sbmhqncws-2/index.php/js/activity/activity-sidebar.js?v=0db267dc-7:473 <anonymous> https://sbmhqncws-2/index.php/js/activity/activity-sidebar.js?v=0db267dc-7:464 

TypeError: OCA.Files is undefined[Learn More] merged.js:498:6
TypeError: OCA.Files is undefined[Learn More] merged.js:232:6

    <anonymous> https://sbmhqncws-2/index.php/js/files_versions/merged.js?v=0db267dc-7:232 <anonymous> https://sbmhqncws-2/index.php/js/files_versions/merged.js?v=0db267dc-7:228 

TypeError: OCA.Files is undefined[Learn More] additionalScripts.js:300:6

    <anonymous> https://sbmhqncws-2/index.php/js/files_sharing/additionalScripts.js?v=0db267dc-7:300 <anonymous> https://sbmhqncws-2/index.php/js/files_sharing/additionalScripts.js?v=0db267dc-7:291 

Loading failed for the <script> with source “https://sbmhqncws-2/index.php/js/files_texteditor/merged.js?v=0db267dc-7”. files:80:1
TypeError: OCA.Files is undefined[Learn More] merged.js:141:2

    <anonymous> https://sbmhqncws-2/index.php/js/systemtags/merged.js?v=0db267dc-7:141 <anonymous> https://sbmhqncws-2/index.php/js/systemtags/merged.js?v=0db267dc-7:124 

New search handler registered search.js:67:4
TypeError: OCA.Files is undefined[Learn More] scripts-for-file-app.js:1308:5

    register https://sbmhqncws-2/index.php/js/gallery/scripts-for-file-app.js?v=0db267dc-7:1308 <anonymous> https://sbmhqncws-2/index.php/js/gallery/scripts-for-file-app.js?v=0db267dc-7:1474 then https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:2 j https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:2 fireWith https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:2 x https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:4 b https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:4 

### Server configuration

**Operating system**:  Ubuntu 16.04

**Web server:** Apache 2.4.5

**Database:** Galera Cluster 10.3.11 (MariaDB)

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 15.02

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** downloaded from Github

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
<details>

Accessibility
--
Activity
Auditing / Logging
Brute-force settings
Calendar
Collaborative tags
Comments
Contacts
Dashboard
Deleted files
External storage support
Federation
File access control
File sharing
Files Right Click
First run wizard
Gallery
Group folders
LDAP user and group backend
Log Reader
Monitoring
Nextcloud announcements
Notifications
ONLYOFFICE
Password policy
PDF viewer
Share by mail
Text editor
Theming
Update notification
Usage survey
Versions
Video player
Default encryption module
Ransomware recovery
SSO & SAML authentication
Support

<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dashboard: 6.0.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.11.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.3
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.2
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - ransomware_detection
  - support
  - user_saml

<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

sudo -u www-data php occ config:list system

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sbmhqncws-1",
            "sbmhqncws-2",
            "sbmbox.domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.2.0",
        "overwrite.cli.url": "https:sbmbox.domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "NTLM",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auth.bruteforce.protection.enabled": true,
        "lost_password_link": "https:\/\/helpdesk.domain.com\/EndUserSelfService.jsp",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "NextCloudUsers"
        ],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false
    }
}

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...  NFS mounted storage

**Are you using encryption:** yes/no NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...  LDAP (Windows)

### Client configuration
**Browser:** IE, Chrome, Firefox

**Operating system:**  Windows 10

#### Web server error log
Errors in Browser diag log:
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Loading failed for the <script> with source “https://sbmhqncws-2/index.php/js/files/merged-index.js?v=0db267dc-7”. files:63:1
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
TypeError: OCA.Files is undefined[Learn More] sharedfilelist.js:30:2

    <anonymous> https://sbmhqncws-2/apps/files_sharing/js/sharedfilelist.js?v=0db267dc-7:30 <anonymous> https://sbmhqncws-2/apps/files_sharing/js/sharedfilelist.js?v=0db267dc-7:10 

TypeError: OCA.Files is undefined[Learn More] mountsfilelist.js:29:2

    <anonymous> https://sbmhqncws-2/apps/files_external/js/mountsfilelist.js?v=0db267dc-7:29 <anonymous> https://sbmhqncws-2/apps/files_external/js/mountsfilelist.js?v=0db267dc-7:10 

TypeError: OCA.Files is undefined[Learn More] filelist.js:44:2
TypeError: OCA.Files is undefined[Learn More] activity-sidebar.js:473:6

    <anonymous> https://sbmhqncws-2/index.php/js/activity/activity-sidebar.js?v=0db267dc-7:473 <anonymous> https://sbmhqncws-2/index.php/js/activity/activity-sidebar.js?v=0db267dc-7:464 

TypeError: OCA.Files is undefined[Learn More] merged.js:498:6
TypeError: OCA.Files is undefined[Learn More] merged.js:232:6

    <anonymous> https://sbmhqncws-2/index.php/js/files_versions/merged.js?v=0db267dc-7:232 <anonymous> https://sbmhqncws-2/index.php/js/files_versions/merged.js?v=0db267dc-7:228 

TypeError: OCA.Files is undefined[Learn More] additionalScripts.js:300:6

    <anonymous> https://sbmhqncws-2/index.php/js/files_sharing/additionalScripts.js?v=0db267dc-7:300 <anonymous> https://sbmhqncws-2/index.php/js/files_sharing/additionalScripts.js?v=0db267dc-7:291 

Loading failed for the <script> with source “https://sbmhqncws-2/index.php/js/files_texteditor/merged.js?v=0db267dc-7”. files:80:1
TypeError: OCA.Files is undefined[Learn More] merged.js:141:2

    <anonymous> https://sbmhqncws-2/index.php/js/systemtags/merged.js?v=0db267dc-7:141 <anonymous> https://sbmhqncws-2/index.php/js/systemtags/merged.js?v=0db267dc-7:124 

New search handler registered search.js:67:4
TypeError: OCA.Files is undefined[Learn More] scripts-for-file-app.js:1308:5

    register https://sbmhqncws-2/index.php/js/gallery/scripts-for-file-app.js?v=0db267dc-7:1308 <anonymous> https://sbmhqncws-2/index.php/js/gallery/scripts-for-file-app.js?v=0db267dc-7:1474 then https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:2 j https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:2 fireWith https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:2 x https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:4 b https://sbmhqncws-2/core/vendor/core.js?v=0db267dc-7:4 
<details>

sudo -u www-data php occ files:scan
Please specify the user id to scan, --all to scan for all users or --path=...
root@sbmhqncws-2:/var/www/html/nextcloud# sudo -u www-data php occ files:scan  --all
Starting scan for user 1 out of 27 (1EA4F62A-F7BF-4FFF-910A-86A91F3124E9)
Starting scan for user 2 out of 27 (1FB8888E-1D16-4391-9F98-BDC5BA57B09B)
Starting scan for user 3 out of 27 (28F1F663-B852-41CD-BA8D-E0C2B6D706EF)
Starting scan for user 4 out of 27 (3689F012-5D5C-4E89-BEDB-20A37E6CF6DA)
Starting scan for user 5 out of 27 (47FF4F7F-4C5D-46F3-920F-3A9D765A1DCE)
Starting scan for user 6 out of 27 (48D9438A-6C98-4313-9F74-C6241393181B)
Starting scan for user 7 out of 27 (51F2C5FF-CB2F-416D-9355-6B914DF3129E)
Starting scan for user 8 out of 27 (550E3E27-CCCE-43AE-8D6C-D4427EC507B7)
Starting scan for user 9 out of 27 (5665FD24-2239-45DF-A769-B1F8453E99E7)
Starting scan for user 10 out of 27 (6BE691AD-1E70-420F-93A3-004C5B21CC5E)
Starting scan for user 11 out of 27 (6DA40FD6-6F63-453B-8F2B-76A1046DF2AE)
Starting scan for user 12 out of 27 (77443B77-66C0-4AA5-9CFB-BBE582C8438A)
Starting scan for user 13 out of 27 (81AEF8DB-444C-4059-A41D-4AF532713D86)
Starting scan for user 14 out of 27 (9B7EB1BC-C3F8-4521-AF00-AF4DFF8C6ADC)
Starting scan for user 15 out of 27 (A50D7F48-AD1A-4C7C-8372-0F0C8FB62129)
Starting scan for user 16 out of 27 (A8C29F77-FD88-4331-9C35-072F8FFE044D)
Starting scan for user 17 out of 27 (A90A2173-6246-4C80-B4C9-00370BAA6CE0)
Starting scan for user 18 out of 27 (AEF27CA5-C635-4DDD-A174-4DECE658F4C0)
Starting scan for user 19 out of 27 (B4B2D119-AC1A-411F-BA9D-D08C1CFBCFC0)
Starting scan for user 20 out of 27 (C4626B44-F0BA-454F-97EC-25315F69975F)
Starting scan for user 21 out of 27 (CDDCEC18-AA5B-4D90-B089-81136E9C17EC)
Starting scan for user 22 out of 27 (D03D4A3C-088E-4FFB-8D3C-D4494FDF4D4F)
Starting scan for user 23 out of 27 (D30CDB08-24B1-4892-AB98-11ECE348ED25)
Starting scan for user 24 out of 27 (E810B011-1F67-42BE-B8E4-1F52B9A73F1F)
Starting scan for user 25 out of 27 (EC04826A-4849-4917-B634-4713931E6593)
Starting scan for user 26 out of 27 (F1EFBD22-2E58-4FB9-9CD3-459143C7C586)
Starting scan for user 27 out of 27 (itadmin)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 350     | 1632  | 00:00:10     |
+---------+-------+--------------+

**Comment by cwhitsbm** [comment]
We had noticed that this was working in Firefox but not IE or Chrome.  In my Firefox session I uploaded a file and then all of a sudden I was no longer able to see my files in Nextcloud in Firefox.  So now I have the same response across all browsers.

If I look at my permissions, they are vastly different between what was there and what was written.  The file I created was Spreadsheet.xlsx.

total 28
drwxr-xr-x 70 www-data www-data 4096 Feb 25 16:11  Documents
drwxr-xr-x  7 www-data www-data 4096 Feb 22 03:38  Personal
drwxr-xr-x  2 www-data www-data 4096 Feb 22 03:32  Photos
-rw-r--r--  1 www-data www-data 6464 Feb 26 20:24  Spreadsheet.xlsx

**Comment by cwhitsbm** [comment]
Just to add a little to the description.  Not only do the files not show up, none of the Favorites or Recent links work either.

But the amount of space I am using in quota does show up.

**Comment by cwhitsbm** [comment]
Also Nextcloud folder perms...

drwxr-xr-x 15 www-data www-data  4096 Feb 20 16:14 .
drwxr-xr-x  3 root     root      4096 Feb 20 15:09 ..
drwxr-xr-x 32 www-data www-data  4096 Jan 11 15:29 3rdparty
drwxr-xr-x 48 www-data www-data  4096 Feb 21 20:02 apps
-rwxr-xr-x  1 www-data www-data 12063 Jan 11 15:25 AUTHORS
drwxr-xr-x  2 www-data www-data  4096 Feb 26 17:39 config
-rwxr-xr-x  1 www-data www-data  3650 Jan 11 15:25 console.php
-rwxr-xr-x  1 www-data www-data 34520 Jan 11 15:25 COPYING
drwxr-xr-x 18 www-data www-data  4096 Jan 11 15:29 core
-rwxr-xr-x  1 www-data www-data  4979 Jan 11 15:25 cron.php
drwxr-xr-x  2 www-data www-data  4096 Feb 26 17:24 data
-rwxr-xr-x  1 www-data www-data  2943 Feb 21 08:48 .htaccess
-rwxr-xr-x  1 www-data www-data   156 Jan 11 15:25 index.html
-rwxr-xr-x  1 www-data www-data  3172 Jan 11 15:25 index.php
drwxr-xr-x  6 www-data www-data  4096 Jan 11 15:25 lib
-rwxr-xr-x  1 www-data www-data   283 Jan 11 15:25 occ
drwxr-xr-x  2 www-data www-data  4096 Jan 11 15:25 ocm-provider
drwxr-xr-x  2 www-data www-data  4096 Feb 21 10:17 ocs
drwxr-xr-x  2 www-data www-data  4096 Jan 11 15:25 ocs-provider
-rwxr-xr-x  1 www-data www-data  2951 Jan 11 15:25 public.php
-rwxr-xr-x  1 www-data www-data  5139 Jan 11 15:25 remote.php
drwxr-xr-x  4 www-data www-data  4096 Jan 11 15:25 resources
-rw-------  1 www-data www-data  1024 Feb 26 19:07 .rnd
-rwxr-xr-x  1 www-data www-data    26 Jan 11 15:25 robots.txt
drwxr-xr-x 12 www-data www-data  4096 Jan 11 15:26 settings
-rwxr-xr-x  1 www-data www-data  2232 Jan 11 15:25 status.php
drwxr-xr-x  3 www-data www-data  4096 Jan 11 15:25 themes
drwxr-xr-x  2 www-data www-data  4096 Jan 11 15:25 updater
-rwxr-xr-x  1 www-data www-data   161 Feb 21 08:48 .user.ini
-rwxr-xr-x  1 www-data www-data   362 Jan 11 15:28 version.php

**Comment by grantemsley** [comment]
> total 28
> drwxr-xr-x 70 www-data www-data 4096 Feb 25 16:11 Documents
> drwxr-xr-x 7 www-data www-data 4096 Feb 22 03:38 Personal
> drwxr-xr-x 2 www-data www-data 4096 Feb 22 03:32 Photos
> -rw-r--r-- 1 www-data www-data 6464 Feb 26 20:24 Spreadsheet.xlsx

I'm assuming that Documents, Personal and Photos were already there from before this happened?  If so, the permissions are functionally the same as the Spreadsheetl.xlsx file - "d" just means it's a directory.  and the "x" (execute) bit in permissions for directories just means you have permission to enter the directory.  It's normal for that to be set on directories and not on files.

**Comment by violoncelloCH** [comment]
have you tried running the occ command `sudo -u www-data php occ files:scan` see https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html?highlight=occ%20files%20scan#file-operations

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by cwhitsbm** [comment]
Yes, I did run scan files.  I upgraded to 15.04 and that seemed to resolve whatever the issue was.

**Comment by hartundweich** [comment]
I had the same issue today - cloud running an 18.0.3 - Friday the cloud was working, today on monday I ran into this issue. Working with Opera and Chrome, not working with actula Firefox, Firefox Developer Edition and MS Edge. 
Truncating the table oc_filecache did the job.

**Comment by MorrisJobke** [comment]
> Truncating the table oc_filecache did the job

Keep in mind, that this means you are deleting our index. Even if it is named "file cache" it is our index and deleting it will make everything related to files (sharing, comments, tags, ...) getting dropped and will be deleted. So don't truncate your file cache if you do not want to loose this information.

**Comment by hartundweich** [comment]
> 
> 
> > Truncating the table oc_filecache did the job
> 
> Keep in mind, that this means you are deleting our index. Even if it is named "file cache" it is our index and deleting it will make everything related to files (sharing, comments, tags, ...) getting dropped and will be deleted. So don't truncate your file cache if you do not want to loose this information.

Yes you are right - I forgot to mention that I restored the table oc_filecache with the backup version from sunday.
