### ISSUE TITLE
Message fails to send when Emoji is included.

### ISSUE THREAD

**Issue by avuton** [nextcloud/server#14394]
### Steps to reproduce
1. Copy emoji from source.
2. Post it in Nextcloud Talk
3. Send

### Expected behaviour
Emoji should send or a more detailed error message would be nice.

### Actual behaviour
'Error occurred while sending message.' is displayed

### Server configuration

**Operating system**:
Debian

**Web server:**
Apache/2.4.38 (Debian)

**Database:**
mariadb  Ver 15.1 Distrib 10.3.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.3.2-3

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Older

**Where did you install Nextcloud from:**
?? Did it some time ago.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - music: 0.9.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - gpxpod
  - issuetemplate
  - phonetrack
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.anpmech.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.anpmech.com",
        "dbtype": "mysql",
        "version": "15.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
There are no commands defined in the "ldap" namespace.
```
</details>

### Client configuration
**Browser:**
Firefox 65.0.1

**Operating system:**
Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing to report
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No related logs, I checked immediately afterwards.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The only thing I found:
Source map error: request failed with status 404
Resource URL: https://nc.anpmech.com/index.php/js/spreed/merged.js?v=d0196843-1
Source Map URL: backbone.marionette.min.js.map[Learn More] 
```
</details>

**Comment by violoncelloCH** [comment]
could you report this to the Talk repo at https://github.com/nextcloud/spreed/ ?

**Comment by avuton** [comment]
I did, thanks!

**Comment by MorrisJobke** [comment]
Most likely related to missing 4-byte support in your DB. If you run MySQL check out https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by avuton** [comment]
Got it, thanks! Surprised this isn't flagged as a issue on the admin page, but I'm sure there's a good reason.

**Comment by MorrisJobke** [comment]
> Got it, thanks! Surprised this isn't flagged as a issue on the admin page, but I'm sure there's a good reason.

Usually it should, but I checked again and also noticed that there is none. Let me add it then.

**Comment by MorrisJobke** [comment]
> Usually it should, but I checked again and also noticed that there is none. Let me add it then.

#14398
