### ISSUE TITLE
Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". 

### ISSUE THREAD

**Issue by nininia** [nextcloud/server#14395]
Hi! I use Cloud Disk 14.0.4,  web interface on chrome.
When I am trying to download jpg file by "side three points->download", I will get picture for preview on browser. F12 shows the next error:
![image](https://user-images.githubusercontent.com/45385367/53471723-acbb0380-3a76-11e9-892a-c3761dc53286.png)
I believe that this is prevent jpg file from downloading.

Could you please assist me. May be need to reset some NC settings?
Thanks in advance!

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
