### ISSUE TITLE
Workflow-related exceptions when changing a file

### ISSUE THREAD

**Issue by it25fg** [nextcloud/server#14401]
### Steps to reproduce
1. change (edit) a file that matches to a tagging rule
2. look at log viewer
3.

### Expected behaviour
No exceptions

### Actual behaviour
Every file change (web interface, or indirectly by syncing a change from a client) causes the following exceptions:
```
array_merge() expects at least 1 parameter, 0 given at /var/www/html/nextcloud/apps/workflowengine/lib/Check/FileSystemTags.php#130
```
```
array_unique() expects parameter 1 to be array, null given at /var/www/html/nextcloud/apps/workflowengine/lib/Check/FileSystemTags.php#131
```
### Server configuration

**Operating system**:
Debian 8

**Web server:**
Apache 2.4.10-10+deb8u13

**Database:**
Postgresql 9.4.21-0+deb8u1

**PHP version:**
PHP-FPM 7.0.33-1~dotde

**Nextcloud version:** (see Nextcloud admin page)
15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated since ~10.x

**Where did you install Nextcloud from:**
tgz from website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bruteforcesettings: 1.3.0
  - checksum: 0.4.2
  - circles: 0.16.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - end_to_end_encryption: 1.1.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_automatedtagging: 1.5.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.5
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.4
  - fulltextsearch_elasticsearch: 1.2.3
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - music: 0.9.3
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - previewgenerator: 2.0.0
  - provisioning_api: 1.5.0
  - radio: 0.6.4
  - richdocuments: 3.2.1
  - scanner: 0.1.1
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharelisting: 0.2.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.1
  - updatenotification: 1.5.0
  - workflow_script: 1.0.0
  - workflowengine: 1.5.0
Disabled:
  - audioplayer
  - encryption
  - files_reader
  - spreed
  - survey_client
  - user_ldap
  - user_saml
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
none

### Client configuration
**Browser:**
does not matter, tried with FF, Chromium, native client 2.3.2 or 2.5.1 on different systems

**Comment by it25fg** [comment]
My understanding of apps/workflowengine/lib/Check/FileSystemTags.php#130
```
$systemTags = call_user_func_array('array_merge', $systemTags);
```
would cause the mentioned exception when $systemTags is an empty array.

**Comment by it25fg** [comment]
While examining the conditions, I found that the exception is only thrown when I have an external script rule that is set to match to a tag. When I change the rule to match on anything else (e.g. regexp on file name) the checks don't seem to be invoked at all.

**Comment by kesselb** [comment]
Do you still see this issue? If yes please explain how to reproduce. I also need the workflow engine rules.  Thanks :+1:
