### ISSUE TITLE
Versions tab shows nothing (15.0.5 RC2)

### ISSUE THREAD

**Issue by bakemonoru** [nextcloud/server#14423]
### Steps to reproduce
1. Change any file
2. Press "Details"
3. Click "Versions" tab
Nothing is here.

### Expected behaviour
Expected versions of the file

### Server configuration

Debian 9: 4.9.0-7-amd64 #1 SMP Debian 4.9.110-3+deb9u2 (2018-08-13) x86_64 GNU/Linux

**Web server:** 
apache2 2.4.25-3+deb9u6
**Database:**
mysql 5.5.9999+default
**PHP version:**
php7.0 7.0.33-0+deb9u1
**Nextcloud version:** 
Nextcloud 15.0.5 RC 2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.0.6 (Stable, versions worked) -> 15.0.4 (Stable, versions broken) -> 15.0.5 RC 2 (Beta, versions broken)

**Where did you install Nextcloud from:**
Installed from packeges 

<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - ransomware_detection: 0.4.3
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - systemtags: 1.5.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - comments
  - encryption
  - files_external
  - files_linkeditor
  - files_videoplayer
  - nextcloud_announcements
  - notifications
  - support
  - survey_client
  - theming
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.crosslab.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.2",
        "overwrite.cli.url": "https://domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "beta"
    }
}

</details>

**Are you using encryption:** no

### Client configuration
**Browser:**
ff 60,64 chrome 70,71,72
**Operating system:**
Linux Manjaro \ Win7
#### Web server error log
<details>
-- open dir

88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /index.php/apps/files/?dir=/tset&fileid=2030 HTTP/1.1" 303 1098 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /index.php/apps/files/?dir=/tset HTTP/1.1" 200 8359 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 1158 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /index.php/apps/files_sharing/api/externalShares HTTP/1.1" 200 903 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /cron.php HTTP/1.1" 200 948 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "PROPFIND /remote.php/dav/files/admin/tset HTTP/1.1" 207 2760 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /ocs/v2.php/core/whatsnew?format=json HTTP/1.1" 204 632 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /index.php/apps/systemtags/lastused HTTP/1.1" 200 1056 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:39:59 +0300] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2Ftset HTTP/1.1" 200 1108 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"

--open file details

88.88.88.88 - - [27/Feb/2019:20:40:04 +0300] "GET /ocs/v2.php/apps/activity/api/v2/activity/filter?format=json&object_type=files&object_id=3529 HTTP/1.1" 200 2164 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:40:04 +0300] "PROPFIND /remote.php/dav/systemtags-relations/files/3529 HTTP/1.1" 207 1199 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:40:04 +0300] "GET /index.php/apps/files_texteditor/ajax/loadfile?filename=New+text+file.txt&dir=tset HTTP/1.1" 206 1031 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
88.88.88.88 - - [27/Feb/2019:20:40:04 +0300] "GET /apps/files_texteditor/js/core/vendor/ace-builds/src-noconflict/theme-clouds.js?_=1551289199373 HTTP/1.1" 200 1210 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.77 Safari/537.36"
-- click Versions
*nothing logged with debug level*

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
*nothing logged*
```
</details>

#### Browser log (got errors)
<details>
<summary>Browser log</summary>

```

in chrome developer console i've got error when clicking Versions:
**core.js?v=23ec51e3:2101 Uncaught TypeError: this.sync is not a function
    at child.fetch (core.js?v=23ec51e3:2101)
    at child.nextPage (merged.js?v=23ec51e3:270)
    at child.setFileInfo (merged.js?v=23ec51e3:360)
    at child.selectTab (merged-index.js?v=23ec51e3:9970)
    at child._onClickTab (merged-index.js?v=23ec51e3:9874)
    at HTMLDivElement.dispatch (core.js?v=23ec51e3:3)
    at HTMLDivElement.r.handle (core.js?v=23ec51e3:3)**
```
</details>

Tried:
 reboot the sever, 
turn on\off Versions APP,
remove all versions (occ versions:cleanup)

**Comment by felixn** [comment]
Duplicate of #13319?

**Comment by bakemonoru** [comment]
> Duplicate of #13319?

duplicate confirmed.
Solution: Enable Comments app.
