### ISSUE TITLE
Problem installing a cluster without LDAP.

### ISSUE THREAD

**Issue by finalls** [nextcloud/server#14427]
### Steps to reproduce
1. Install HAProxy 1-server
2. Install NC 15.04 - 2 nodes
3. NFS mount  2 nodes NC (data)
4. Install Redis (cache + php_ssession) 1 server
5. Postgress - 1 server

### Expected behaviour

switching between nodes

### Actual behaviour
 With two servers. If I log in on the first one and switch to the second one then everything is ok. And no back.
In the logs - Bad Password
And you can login only after password recovery via email

### Server configuration

**Operating system**:  Centos
 
**Web server:** nginx

**Database:** Postgress

**PHP version:**  7.1

**Nextcloud version:**  15.04

**Comment by rullzer** [comment]
Is your config.php identical?
Also try switching to sticky sessions in HAProxy.

**Comment by finalls** [comment]
> Is your config.php identical?
> Also try switching to sticky sessions in HAProxy.

1) Yes.

**Comment by kesselb** [comment]
Are you using the same `instanceid` for both nodes? If no mind to try the same `instanceid`?
