### ISSUE TITLE
Incorrect display of upload time

### ISSUE THREAD

**Issue by ChristianHermsen** [nextcloud/server#1442]
After reinstalling our server and set up the Nextcloud, we realized, that the remaining time is displayed incorrectly during the upload. It always showed somthing like "5 seconds left" ...

After a while, this problem has apparently solved itself and now I figured out why:

When reinstalling the server, I configured a RAID 1 on 2x3TB HD's.  Because the fresh installed system was immediately used extensively, the resync took quite a while. After the resync was completed, the calculation is correct now.

Next time, i'll let the system finish the resync, before i fed the lions :)

I thought this behavior might be interesting for you, but did not know exactly where to post it. So this issue can be closed :)

**Comment by nickvergessen** [comment]
Closing as requested
