### ISSUE TITLE
Error code HTTP 412 (Precondition failed) : Sabre\DAV\Exception\PreconditionFailed An If-None-Match header was specified, but the ETag matched (or * was specified). If-None-Match[exception][message][header]`

### ISSUE THREAD

**Issue by Aurelien-** [nextcloud/server#14428]
When using Evolution mail and accept a calendar invitation, an error message appears with 

`Cannot send element to « Personnel » calendar. Cannot receive the calendar object :  Failed to send (« put ») data : Error code HTTP 412 (Precondition failed) : Sabre\DAV\Exception\PreconditionFailed An If-None-Match header was specified, but the ETag matched (or * was specified). If-None-Match[exception][message][header]`

However the event appears correctly after some time.

It may be similar to https://github.com/nextcloud/server/issues/8110, but here the event is new.

### Steps to reproduce
1. Receive a calendar invitation in Evolution mail
2. Accept it

### Expected behaviour
No error should appear.

### Actual behaviour
The HTTP 412 error is showed by Evolution mail.

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL 5.6

**PHP version:** 7.2

**Nextcloud version:** 15.0.4
**Contacts version: 3.0.3

**Updated from an older Nextcloud or fresh install: fresh install

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:

    * accessibility: 1.1.0

    * activity: 2.8.2

    * bruteforcesettings: 1.3.0

    * calendar: 1.6.4

    * cloud_federation_api: 0.1.0

    * comments: 1.5.0

    * contacts: 3.0.3

    * dav: 1.8.1

    * end_to_end_encryption: 1.1.0

    * federatedfilesharing: 1.5.0

    * federation: 1.5.0

    * files: 1.10.0

    * files_frommail: 0.2.0

    * files_pdfviewer: 1.4.0

    * files_sharing: 1.7.0

    * files_texteditor: 2.7.0

    * files_trashbin: 1.5.0

    * files_versions: 1.8.0

    * files_videoplayer: 1.4.0

    * firstrunwizard: 2.4.0

    * gallery: 18.2.0

    * logreader: 2.0.0

    * lookup_server_connector: 1.3.0

    * mail: 0.11.0

    * nextcloud_announcements: 1.4.0

    * notifications: 2.3.0

    * oauth2: 1.3.0

    * password_policy: 1.5.0

    * phonetrack: 0.4.3

    * provisioning_api: 1.5.0

    * serverinfo: 1.5.0

    * sharebymail: 1.5.0

    * socialsharing_email: 1.0.5

    * spreed: 5.0.2

    * support: 1.0.0

    * survey_client: 1.3.0

    * systemtags: 1.5.0

    * tasks: 0.9.8

    * theming: 1.6.0

    * twofactor_backupcodes: 1.4.1

    * twofactor_totp: 2.1.1

    * twofactor_u2f: 2.1.1

    * updatenotification: 1.5.0

    * user_saml: 2.1.1

    * workflowengine: 1.5.0
      Disabled:

    * admin_audit

    * deck

    * encryption

    * files_external

    * user_ldap

**Nextcloud configuration:**
{
"system": {
"instanceid": "_**REMOVED SENSITIVE VALUE**_",
"passwordsalt": "_**REMOVED SENSITIVE VALUE**_",
"secret": "_**REMOVED SENSITIVE VALUE**_",
"trusted_domains": [
"exemple.com",
"contact.exemple.com",
"cal.exemple.com"
],
"forcessl": true,
"datadirectory": "_**REMOVED SENSITIVE VALUE**_",
"dbtype": "mysql",
"version": "15.0.4.0",
"overwrite.cli.url": "https://exemple.com",
"htaccess.RewriteBase": "/",
"dbname": "_**REMOVED SENSITIVE VALUE**_",
"dbhost": "_**REMOVED SENSITIVE VALUE**_",
"dbport": "",
"dbtableprefix": "oc_",
"dbuser": "_**REMOVED SENSITIVE VALUE**_",
"dbpassword": "_**REMOVED SENSITIVE VALUE**_",
"installed": true,
"filelocking.enabled": "true",
"redis": {
"host": "_**REMOVED SENSITIVE VALUE**_",
"port": 35172,
"password": "_**REMOVED SENSITIVE VALUE**_",
"timeout": 0
},
"memcache.locking": "\OC\Memcache\Redis",
"memcache.local": "\OC\Memcache\Redis",
"mail_from_address": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpmode": "smtp",
"mail_sendmailmode": "smtp",
"mail_domain": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpsecure": "ssl",
"mail_smtpauthtype": "LOGIN",
"mail_smtpauth": 1,
"mail_smtphost": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpname": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtppassword": "_**REMOVED SENSITIVE VALUE**_",
"mail_smtpport": "465",
"updater.secret": "_**REMOVED SENSITIVE VALUE**_",
"maintenance": false,
"theme": "",
"loglevel": 2
}
}
### Client configuration

**Browser:** Firefox 65

**Operating system:** Fedora

**CardDAV-clients:** Evolution
#### _Web server error log_
No error

### Nextcloud log
No error

#### Evolution log
Impossible d’envoyer l’élément à l’agenda « Personnel ». Impossible de recevoir les objets de l’agenda : L’envoi de données (« put ») a échoué : code d’erreur HTTP 412 (Precondition failed) : Sabre\DAV\Exception\PreconditionFailed An If-None-Match header was specified, but the ETag matched (or * was specified). If-None-Match[exception][message][header]

**Comment by hubertbanas** [comment]
Experiencing same issue here as well.

Nextcloud 15.0.5
Calendar 1.6.4
Evolution 3.28.5-0ubuntu0.18.04.1

**Comment by codiflow** [comment]
For me the cause was that I edited this event on my android smartphone with DAVx5 already and didn't sync this change in evolution trying to change exactly the same event with evolution. After clicking on "Refresh" for the affected calendar and syncing the already-changed event the problem was gone.

**Comment by funwhilelost** [comment]
Also seeing the same with Nextcloud 16.0.8 and Evolution 3.34.1-2.  I created an event in Evolution and the error popped up when the event wouldn't save.  Now that the error has occurred the entire calendar fails on every refresh, preventing me from getting the latest events.

**Comment by funwhilelost** [comment]
Edit: May particular case happened when a calendar item was deleted in another calendar app, then I went to Evolution and _also_ deleted the item before it sync'd the delete.  It tried to carry out the delete (with the appropriate ID in the `If-None-Match` header) but that fails because the item doesn't exist any more.

```
< HTTP/1.1 412 Precondition failed
< Soup-Debug-Timestamp: 1582056771
< Soup-Debug: SoupMessage 5 (0x7f6ea4008390)
< Date: Tue, 18 Feb 2020 20:12:51 GMT
< Server: Apache
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate
< Pragma: no-cache
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: default-src 'none';
< Set-Cookie: oc_sessionPassphrase=⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛; path=/; secure; HttpOnly
< Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
< Set-Cookie: ⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛⬛; path=/; secure; HttpOnly
< Strict-Transport-Security: max-age=63072000; includeSubdomains
< X-Content-Type-Options: nosniff
< X-XSS-Protection: 1; mode=block
< X-Robots-Tag: none
< X-Download-Options: noopen
< X-Permitted-Cross-Domain-Policies: none
< Referrer-Policy: no-referrer
< Connection: close
< Transfer-Encoding: chunked
< Content-Type: application/xml; charset=utf-8
< 
  
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\PreconditionFailed</s:exception>
  <s:message>An If-Match header was specified and the resource did not exist</s:message>
  <s:header>If-Match</s:header>
</d:error>
```

**Comment by kesselb** [comment]
Thanks for digging 👍

cc @nextcloud/calendar

**Comment by georgehrke** [comment]
@funwhilelost Can you please provide the full (anonymised) http request?

**Comment by georgehrke** [comment]
@schiessle I feel like I debugged this issue before with you and we came to the conclusion that this is a bug in Evolution?

**Comment by georgehrke** [comment]
@funwhilelost Are you 100% positive it's an `If-None-Match` header and not an `If-Match` header? That error message is only thrown if there is an `If-Match` header present:
https://github.com/nextcloud/3rdparty/blob/b995ca8b8c7f69a180ad6fb49989ad3e35b1367e/sabre/dav/lib/DAV/Server.php#L1338

The error message for `If-None-Match` is different:
https://github.com/nextcloud/3rdparty/blob/b995ca8b8c7f69a180ad6fb49989ad3e35b1367e/sabre/dav/lib/DAV/Server.php#L1383

**Comment by tcitworld** [comment]
> @schiessle I feel like I debugged this issue before with you and we came to the conclusion that this is a bug in Evolution?

https://github.com/nextcloud/server/issues/8110#issuecomment-531482911

**Comment by funwhilelost** [comment]
@tcitworld after digging deeper into this I think my particular case is Evolution, yes.  It is trying to delete an event and is sending an `If-Match` header with it (not `If-None-Match`).  I guess any client should assume that if it's trying to delete and the item isn't found that no operation needs to occur.  Evolution is not correctly handling this error message from NextCloud.

**Comment by szaimen** [comment]
> after digging deeper into this I think my particular case is Evolution, yes. It is trying to delete an event and is sending an `If-Match` header with it (not `If-None-Match`). I guess any client should assume that if it's trying to delete and the item isn't found that no operation needs to occur. Evolution is not correctly handling this error message from NextCloud.

Based on this I suppose this needs to be fixed in the Evolution client. -> closing.
