### ISSUE TITLE
Share overview should allow to unshare

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#14437]
In the right hand sidebar I have the "Shared with other", "Shared with you" and "Shared by link" views.

In "Shared with you" the '...' menu of each file/folder shows a unshare action which performs a unshare from self operation.

For "Shared with others" and "Shared by link" the '...' menu only has a delete action which deletes the file completely. I think, like for "Shared with you" the delete action should be replaced with a unshare actions which allows me to unshare the file again from all recipients as a easy way to cleanup old shares. Having always to open the details few is really cumbersome.

**Comment by jancborchardt** [comment]
Yep, totally agree. In all the "Shared" filters, the destructive action should be "Unshare" instead of "Delete".

@nextcloud/javascript? 

(Also, I guess you mean _left_ hand sidebar. :)

**Comment by szaimen** [comment]
I suppose this issue is still valid?

**Comment by msharp1** [comment]
Hi ! I really need that and I'm pretty sure I'm not alone. There is currently no way to bulk unshare files or folders from the UI...
It seems a fix has been merged a long time ago ? Would love to see that an official release in the coming months ;)

**Comment by blizzz** [comment]
> Hi ! I really need that and I'm pretty sure I'm not alone. There is currently no way to bulk unshare files or folders from the UI... It seems a fix has been merged a long time ago ? Would love to see that an official release in the coming months ;)

The fix is released with 28.0.2 and >=29.
