### ISSUE TITLE
Unsuccessful upgrade from 15.04 to 15.05

### ISSUE THREAD

**Issue by talbaror** [nextcloud/server#14434]
Hello ,

Just had issue while doing web upgrade from NC 15.04 TO 15.05
With following below

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Change row format for oc_addressbooks ...

Repair info: Change collation for oc_addressbooks ...

Repair info: Change row format for oc_authtoken ...

Repair info: Change collation for oc_authtoken ...

Repair info: Change row format for oc_calendarobjects ...

Repair info: Change collation for oc_calendarobjects ...

Repair info: Change row format for oc_calendars ...

Repair info: Change collation for oc_calendars ...

Repair info: Change row format for oc_calendarsubscriptions ...

Repair info: Change collation for oc_calendarsubscriptions ...

Repair info: Change row format for oc_dav_shares ...

Repair info: Change collation for oc_dav_shares ...

Repair info: Change row format for oc_ldap_group_mapping ...

Repair info: Change collation for oc_ldap_group_mapping ...

Repair info: Change row format for oc_ldap_group_members ...

Repair info: Change collation for oc_ldap_group_members ...

Repair info: Change row format for oc_ldap_user_mapping ...

Repair info: Change collation for oc_ldap_user_mapping ...

Repair info: Change row format for oc_migrations ...

Repair info: Change collation for oc_migrations ...

Repair info: Change row format for oc_mimetypes ...

Repair info: Change collation for oc_mimetypes ...

Repair info: Change row format for oc_systemtag_group ...

Repair info: Change collation for oc_systemtag_group ...

Repair info: Change row format for oc_trusted_servers ...

Repair info: Change collation for oc_trusted_servers ...

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Checking for update of app "accessibility" in appstore

Checked for update of app "accessibility" in appstore

Checking for update of app "activity" in appstore

Checked for update of app "activity" in appstore

Checking for update of app "cloud_federation_api" in appstore

Checked for update of app "cloud_federation_api" in appstore

Checking for update of app "comments" in appstore

Checked for update of app "comments" in appstore

Checking for update of app "dav" in appstore

Checked for update of app "dav" in appstore

Checking for update of app "federatedfilesharing" in appstore

Checked for update of app "federatedfilesharing" in appstore

Checking for update of app "federation" in appstore

Checked for update of app "federation" in appstore

Checking for update of app "files" in appstore

Checked for update of app "files" in appstore

Checking for update of app "files_pdfviewer" in appstore

Checked for update of app "files_pdfviewer" in appstore

Checking for update of app "files_sharing" in appstore

Checked for update of app "files_sharing" in appstore

Checking for update of app "files_texteditor" in appstore

Checked for update of app "files_texteditor" in appstore

Checking for update of app "files_trashbin" in appstore

Checked for update of app "files_trashbin" in appstore

Checking for update of app "files_versions" in appstore

Checked for update of app "files_versions" in appstore

Checking for update of app "files_videoplayer" in appstore

Checked for update of app "files_videoplayer" in appstore

Checking for update of app "firstrunwizard" in appstore

Checked for update of app "firstrunwizard" in appstore

Checking for update of app "gallery" in appstore

Checked for update of app "gallery" in appstore

Checking for update of app "logreader" in appstore

Checked for update of app "logreader" in appstore

Checking for update of app "lookup_server_connector" in appstore

Checked for update of app "lookup_server_connector" in appstore

Checking for update of app "nextcloud_announcements" in appstore

Checked for update of app "nextcloud_announcements" in appstore

Checking for update of app "notifications" in appstore

Checked for update of app "notifications" in appstore

Checking for update of app "oauth2" in appstore

Checked for update of app "oauth2" in appstore

Checking for update of app "password_policy" in appstore

Checked for update of app "password_policy" in appstore

Checking for update of app "provisioning_api" in appstore

Checked for update of app "provisioning_api" in appstore

Checking for update of app "serverinfo" in appstore

Checked for update of app "serverinfo" in appstore

Checking for update of app "sharebymail" in appstore

Checked for update of app "sharebymail" in appstore

Checking for update of app "support" in appstore

Checked for update of app "support" in appstore

Checking for update of app "survey_client" in appstore

Checked for update of app "survey_client" in appstore

Checking for update of app "systemtags" in appstore

Checked for update of app "systemtags" in appstore

Checking for update of app "theming" in appstore

Checked for update of app "theming" in appstore

Checking for update of app "twofactor_backupcodes" in appstore

Checked for update of app "twofactor_backupcodes" in appstore

Checking for update of app "updatenotification" in appstore

Checked for update of app "updatenotification" in appstore

Checking for update of app "user_ldap" in appstore

Checked for update of app "user_ldap" in appstore

Checking for update of app "workflowengine" in appstore

Checked for update of app "workflowengine" in appstore

Repair step: Repair MySQL collation

Repair info: Change row format for oc_addressbooks ...

Repair info: Change collation for oc_addressbooks ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by MorrisJobke** [comment]
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

cc @georgehrke @nickvergessen

**Comment by nickvergessen** [comment]
Seems like at least the first step from https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html was not done correctly.
