### ISSUE TITLE
Download deleted file

### ISSUE THREAD

**Issue by biva** [nextcloud/server#14439]
In the deleted files, I can only Restore or Delete the files. I would like to be able to download it instead of restoring it.

Use case: I deleted several documents, and I just need to open one of these. I would like to download it without restoring it.

Thanks!

NC version: 15.0.5

**Comment by joshtrichards** [comment]
Hi @biva:

I'm happy to report that this enhancement was recently implemented as part of #36534 & #37633 and released in NC27.

**Comment by biva** [comment]
Congrats! And thanks!
