### ISSUE TITLE
Translation when updating

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#14443]
I noticed that for a long time there is a very old translation (2 years) during the Nextcloud update. One of them is:
`The update was successful. Redirecting you to Nextcloud in 1%n seconds.`

The problem is **very urgent**, because the old translation misleads users about the failed update. However, the Nexcloud update itself is successful.

App: Nextcloud 15.0.5

**Comment by MorrisJobke** [comment]
> The problem is **very urgent**, because the old translation misleads users about the failed update. However, the Nexcloud update itself is successful.

I don't get it. What is the problem? The translation is wrong? In Which language?

**Comment by Valdnet** [comment]
> The translation is wrong? In Which language?

In Polish:

Correct:
 Aktualizacja przebiegła pomyślnie. Przekieruję Ciebie do Nextcloud w %n sekund.
by Valdnet, 10 days ago 

There is still an incorrect translation in Nectcloud:
 **Aktualizacja się nie powiodła.** Przekierowuję cię do Nextclouda w %n sekund.
by xxxx, **2 years** ago 

Original description:
The update was successful. Redirecting you to Nextcloud in seconds.

**Comment by r2evans** [comment]
Perhaps this is the line you mean?

https://github.com/nextcloud/server/blob/057e81a1e2fb9d2b4fd43904e0eae53f179e3789/core/l10n/pl.json#L263

I don't know that I'd call "mis-translation" *very urgent*. Misleading, certainly. To me, "very urgent" suggests loss of data, egregious visual artifacts, or big gaping security holes.

Fortunately, @Valdnet, a PR should be pretty easy on this. Since there's one wrong one in that file, have you found any other logical mis-translations? That's a pretty big one in my eyes.

**Comment by kesselb** [comment]
Thank you for reporting this :+1:  Translations are synced daily from transifex. Please join at https://www.transifex.com/nextcloud/nextcloud/ to help with translations.

**Comment by Valdnet** [comment]
@r2evans this line is about :wink: 
> Since there's one wrong one in that file, have you found any other logical mis-translations?

There are many erroneous translations that I am slowly correcting in Transifex. In general, there is a big mess in the Polish translation.
> Translations are synced daily from transifex.

@kesselb This translation is old from two years. Among other things, there were other translations.

> Aktualizacja przebiegła pomyślnie. Przekieruję Ciebie do Nextcloud w %n sekund.
> by Valdnet, **10 days ago**
> Aktualizacja przebiegła pomyślnie. Przekierowuję cię do Nextclouda w %n sekund.
> by xxx, **9 months ago**
> Aktualizacja się nie powiodła. Przekierowuję cię do Nextclouda w %n sekund.
> by xxxx, **2 years ago** 

It's probably not downloaded from Transifex.

@MorrisJobke is there any error in the code? Can you check it?

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/53592654-0581bd80-3b97-11e9-9611-d108b1fcca99.png)

I'm not sure what this warning sign means :thinking:

**Comment by Valdnet** [comment]
Ok. The situation is controlled. The translation was only corrected for "other". I went through the translation again and corrected all kinds :grin:

**Comment by kesselb** [comment]
Awesome :100:
