### ISSUE TITLE
security enhancement: different domain for share link with disabled unnecessary API

### ISSUE THREAD

**Issue by mrizvic** [nextcloud/server#14458]
I was wondering if there is any possibility to put different domain in URL when generating share link so that share link domain wouldnt expose login API to the world.
At the moment the solution is to put another domain in trusted_domains  in config.php and block .php stuff on that secondary domain in webserver config. But user stil has to manually change share link.

I believe that way one could not easily expose the main URL for login, webUI and other .php stuff.

For that purpose it would be a nice to have a setting in admin panel for share domain. Disabled unnecessary API on share domain would be nice feature so one would not have to fiddle with webserver config.

**Comment by rullzer** [comment]
There is not.
Also you would still need to expose webdav and this still have a login endpoint.

On top of that there is no real reason to hide the login endpoint. Be sure to setup proper passwords and enable a second factor and there is no real reason not to just use 1 domain.
