### ISSUE TITLE
Custom logo not showing in in share link embed

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/server#14452]
Hi all

Saw [this](https://www.reddit.com/r/NextCloud/comments/avsr5k/custom_logo_not_applied_on_urls_in_apps_like/) on reddit and thought to quickly test it myself. We have theming enabled on our instance with our institutions logo. But when sharing a link via Skype, it does not display as it should (see beneath)
![nc-logo-issue](https://user-images.githubusercontent.com/24249616/53628198-0d7f4300-3c13-11e9-961f-47513bafc409.png)

IMHO the theming of the owner of the NC instance should be honoured at all times. The  question is where do the apps (whatsapp, skype etc) find that logo from?

**Comment by violoncelloCH** [comment]
cc @nextcloud/theming

**Comment by jancborchardt** [comment]
Absolutely, that image should also be themed. We could generate it just like the themed favicon is generated.

cc @juliushaertl @nextcloud/theming

**Comment by juliushaertl** [comment]
Yes, we could do either that or just reuse the existing generated big version of the favicon - iirc the image is just shown if there is no preview available for a file.

**Comment by hanserasmus** [comment]
> Yes, we could do either that or just reuse the existing generated big version of the favicon - iirc the image is just shown if there is no preview available for a file.

Not sure if an external application will be privvied to read the content in order to generate a preview of the contents? From what I have seen so far every time we share by link that logo is generated.

**Comment by BrookeDot** [comment]
I also had this problem and have been replacing `/core/img/favicon-fb.png` within my install to update the sharing icon. [#](https://github.com/nextcloud/server/blob/master/core/img/favicon-fb.png)

https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/Controller/ShareController.php#L410

If this could be updated with Theming that would be amazing. 

See also: https://help.nextcloud.com/t/thumbnail-icon-when-sharing/14145

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/19054
