### ISSUE TITLE
Migration of contacts from one address book to another one

### ISSUE THREAD

**Issue by VLNTNO** [nextcloud/server#14453]
**Is your feature request related to a problem? Please describe.**
I use several addressbooks. In order to remove addressbook 1, I'd like to migrate all contacts from addressbook 1 to addressbook 2. Such a functionality doesn't seem to exist.

**Describe the solution you'd like**
I'd like a functionality to allow me to migrate easily contacts from an addressbook to another one.

**Describe alternatives you've considered**
Otherwise, I'd like a command (located in the Contacts app) allowing me to select/filter contact entries from a given addressbook, thus making me able to migrate them manually to the other addressbook (by changing the value af the addressbook in the contact detailed view).
Currently filters are only possible on the Group property, not on the addressbook one.

**Additional context**
N/A

**Comment by skjnldsv** [comment]
Hello!

If you want to do that, just export the addressbook and import it into the other one?
You can do that with the contacts app directly.
![capture d ecran_2019-03-03_19-23-40](https://user-images.githubusercontent.com/14975046/53699555-ddd66380-3de9-11e9-8e97-61cea57ea7e7.png)
