### ISSUE TITLE
Antivirus app disappeared from app list in nextcloud 10.0

### ISSUE THREAD

**Issue by arjanvs** [nextcloud/server#1445]
I found something similar as for owncloud 9
[https://github.com/owncloud/documentation/issues/2239](https://github.com/owncloud/documentation/issues/2239)

Sorry, if I post it here and not in the files_antivirus.

According to me, it either a documentation thing:
[https://docs.nextcloud.com/server/10/admin_manual/configuration_server/antivirus_configuration.html?highlight=clam](https://docs.nextcloud.com/server/10/admin_manual/configuration_server/antivirus_configuration.html?highlight=clam)
Or programming error, because files_antivirus is not part of the zip file.

Further, I like to make a side remark about the demo website, it crashes a lot.

Cheers, Arjan

**Comment by nickvergessen** [comment]
Yeah you need to download the app first: https://github.com/nextcloud/files_antivirus/archive/stable10.zip

**Comment by nickvergessen** [comment]
Can you open an issue in the documentation repo? Thanks!
https://github.com/nextcloud/documentation/

**Comment by Django-BOfH** [comment]
I'm using nextcloud 10.0.1 (stable)
I've clones the required repo:
`git clone https://github.com/nextcloud/files_antivirus.git files_antivirus`

After looking about my new app, I recedive this error message:

**Diese App kann nicht installiert werden, weil die folgenden Abhängigkeiten nicht erfüllt sind:
Server version 11 or higher is required.**

What now? Is it possible to use files_antivirus-1.0.0.0 and the stabe version 10.0.1?

**Comment by nickvergessen** [comment]
You need to `git checkout stable10`
As mentioned above, master is for nextcloud master, not nextcloud 10

**Comment by Django-BOfH** [comment]
thanx
