### ISSUE TITLE
Update jcrop to a recent version

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#14455]
**Is your feature request related to a problem? Please describe.**
Our jcrop is ancient. We can't easily upgrade because the lib seems to have changed fundamentally.

**Describe the solution you'd like**
Update to a new version or just replace the lib with something more recent. Right now we disabled dependabot updates for that lib: https://github.com/nextcloud/server/pull/14444

**Describe alternatives you've considered**
N/a

**Additional context**
N/a

**Comment by StCyr** [comment]
This may be causing build issue now:

```
npm ci
npm ERR! code 1
npm ERR! git dep preparation failed
npm ERR! command /usr/bin/node /usr/share/nodejs/npm/bin/npm-cli.js install --cache=/home/cyrille/.npm/_cacache --prefer-offline=false --prefer-online=false --offline=false --no-pr                  ogress --no-save --no-audit
npm ERR! npm ERR! code ERESOLVE
npm ERR! npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! npm ERR!
npm ERR! npm ERR! While resolving: jcrop@0.9.12
npm ERR! npm ERR! Found: webpack@4.46.0
npm ERR! npm ERR! node_modules/webpack
npm ERR! npm ERR!   dev webpack@"^4.16.2" from the root project
npm ERR! npm ERR!
npm ERR! npm ERR! Could not resolve dependency:
npm ERR! npm ERR! peer webpack@"^3.1.0" from extract-text-webpack-plugin@3.0.2
npm ERR! npm ERR! node_modules/extract-text-webpack-plugin
npm ERR! npm ERR!   dev extract-text-webpack-plugin@"^3.0.2" from the root project
npm ERR! npm ERR!
npm ERR! npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! npm ERR!
```

and package `extract-text-webpack-plugin` is deprecated (see https://www.npmjs.com/package/extract-text-webpack-plugin)

**Comment by StCyr** [comment]
running `npm ci --legacy-peer-deps` solves the issue

**Comment by arielnmz** [comment]
Where can I find the repo for the Jcrop package? https://www.npmjs.com/package/@nextcloud/jcrop

**Comment by arielnmz** [comment]
Nvm i found it: https://github.com/tapmodo/Jcrop/tree/v0.9.12

**Comment by ChristophWurst** [comment]
Seems fixed
