### ISSUE TITLE
Multiple activity records are being created when copying/moving multiple files

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#14469]
## Expected behavior
If you copy/move mulitiple files to a new folder, one single activity record should be created, as it is done when you e.g. delete multiple files.

## Current behavior
If you copy/move multiple files to a new folder, an activity record is created for every single file.

#### Activities created on copy/move action:

![20190302_nc_activities_move_multiple_times](https://user-images.githubusercontent.com/2572764/53681415-b1d3b900-3ce9-11e9-8066-f03b752b0487.png)

#### Activity created on delete action:

![20190302_nc_activities_delete_multiple_times](https://user-images.githubusercontent.com/2572764/53681440-ee071980-3ce9-11e9-8be5-fcb775419ec8.png)

## Steps to reproduce
1. Open the files app
2. select multiple files and copy/move it to a new folder
3. open the activity app and check the created activity records.

#### Server Configuration
OS: Linux 3.16.62
Web server: Apache2 2.4.37
Database: MariaDB 10.2.19
PHP version: 7.2.14
Nextcloud version: 15.0.5

#### Client Configuration
Browser: Mozilla Firefox 65.0.2
Operating system: Windows 10

**Comment by skjnldsv** [comment]
cc @nickvergessen for activity
