### ISSUE TITLE
Option: Share photos without their EXIF metadata

### ISSUE THREAD

**Issue by ciscam** [nextcloud/server#14474]
Hi!

Just like in Google Photos, you could be able to automatically have sensitive metadata stripped from media files that are accessed via a share.
That could be realized in the interface with a simple check box under the present "Set expiration date" option.

Photos are the most important use case, but also (self-made) videos or even .pdf files could be interesting to include.

**Comment by Spartachetto** [comment]
@MorrisJobke I have the impression that (if @ciscam agrees) this issue could be made broader.

The issue could become **Provide the possibility to share a file without its metadata**.

The metadata could be :

1. Nextcloud internal metadata (creation date, tags, versions, ...)
2. File metadata:

    - EXIF metadata
    - pdf metadata
    - mp3 metadata
    - etc..

I guess that you could consider some file formats (e.g. EXIF) comparable to internal metadata as images are "first class files" in Nextcloud. For other file formats maybe an extension via some apps could be possible..

**Comment by bpcurse** [comment]
This could even be extended to the upload process. Would be an interesting privacy feature if all exif data could automatically be stripped from files uploaded to a certain folder.
Although it probably is already possible through calling of external scripts in NC15+ (yet not so simple). Must admit I did not test it.

**Comment by ciscam** [comment]
Since this is a completely new feature to the user interface, I'd suggest
sticking to the typical use case of removing sensitive data like
geolocational tags from files, in the case that they are served via a
specific share with this new property set.
[image: scrnsht_nc_anonymize-media.png]

Adding other intents to this feature, not only privacy, but also for
example general removal of metadata like @Spartachetto proposed, would be a
higher level of complexity, since you'd want to be able to selectively
choose which metadata from which filetype is to be removed. That's a new
menu in the least.

Permanently removing metadata from files is another topic in my opinion.
That's a possible item in the "file action menu". Realizing that in the
form of a rule and not an action would be yet another complexity level, and
I haven't seen something of the like in other technology.

>

**Comment by MorrisJobke** [comment]
> Since this is a completely new feature to the user interface, I'd suggest sticking to the typical use case of removing sensitive data like geolocational tags from files, in the case that they are served via a specific share with this new property set. ![scrnsht_nc_anonymize-media.png](https://user-images.githubusercontent.com/13006585/53698820-1ffba700-3de2-11e9-8bab-3d50ea5bd903.png)

While I like the general idea adding yet another option to the menu is maybe not the best way to get this feature in. We are a file sharing platform and on demand changing the content of files is not the main way to go here. I guess this is something for a special app that provides this feature. This does not mean we don't want this feature, but it is simply nothing for the server part of Nextcloud - it should be developed as an extension to the server itself as an app. There also the options to either trigger a sanitizer script and create a cleared copy of the file or to do this on demand are totally open. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
