### ISSUE TITLE
Feature request: support for HTTP-based Public Key Pinning

### ISSUE THREAD

**Issue by janipewter** [nextcloud/server#14475]
**Is your feature request related to a problem? Please describe.**
Not necessarily

**Describe the solution you'd like**
Please add support for HTTP-based Public Key Pinning (RFC 7469). I am aware this feature is dangerous and support has been removed from web browsers but I believe there is a use case for applications which require high security.  I would like the ability to pin TLS certificate public key hashes in Nextcloud server so any clients which connect will only communicate with the server if the presented certificate matches one of the pinned keys. This will entirely prevent TLS interception (essentially, man in the middle attacks) when users are behind TLS middleboxes and have CA certificates in their local trust store which can issue certificates for local use (such as filtering etc). 

**Describe alternatives you've considered**
There are no feasible alternatives for what I am trying to achieve. Certificate transparency and DNS CAA have largely replaced HPKP for general web browsing, but they cannot stop anyone issuing a self signed certificate for any domain and showing it to devices which trust that CA.

**Additional context**
Find out more about HPKP
https://en.wikipedia.org/wiki/HTTP_Public_Key_Pinning
https://tools.ietf.org/html/rfc7469

**Comment by kesselb** [comment]
Looks like you have to set some headers. You usually do this with your webserver: https://developer.mozilla.org/en-US/docs/Web/HTTP/Public_Key_Pinning

Are there changes required for the application?

**Comment by janipewter** [comment]
Yes, the key pinning is set usually in a HTTP header. However, I am not sure if desktop and mobile client will honour or even recognise the HPKP header.

**Comment by janipewter** [comment]
I should add, I have HPKP deployed on my Nextcloud instance. I will be happy to help test anything

**Comment by angristan** [comment]
Maybe this issue should be in the clients repositories?

**Comment by rullzer** [comment]
So yes this is not really something the server can solve. As these headers should be set in your webserver (and not by nextcloud).

The network libraries of the clients should take care of this. And if not. Then I guess it is time to try to bug the developers of the network libraries :wink:
