### ISSUE TITLE
No apps found for your version

### ISSUE THREAD

**Issue by jearton** [nextcloud/server#14482]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:

centos7.6

**Web server:**

nginx

**Database:**

mariadb

**PHP version:**

7.3

**Nextcloud version:** (see Nextcloud admin page)

15.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

fresh install

**Where did you install Nextcloud from:**

official website, xx.tar.gz

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by jearton** [comment]
<img width="1294" alt="default" src="https://user-images.githubusercontent.com/10370433/53693441-6699d300-3ddb-11e9-8c2c-6bc1c36ffdfc.png">

**Comment by jearton** [comment]
I find the reason in debug logs. Then I find the hard codes. Could I customize it? Or customize the timeout params in the class Fetcher? 

<img width="904" alt="default" src="https://user-images.githubusercontent.com/10370433/53693957-6a7d2380-3de2-11e9-8fdc-9bbda482ee9c.png">


<img width="1657" alt="default" src="https://user-images.githubusercontent.com/10370433/53693907-cb582c00-3de1-11e9-8568-aadc18f6dff7.png">

**Comment by jearton** [comment]
I just changed the value of endpointUrl to my own proxy url, and then restart php-fpm service. It works! Never timeout!

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/1cfa870821c92bdd6854171c8c073ed16529b6df/config/config.sample.php#L537

It's possible to define a proxy for outgoing connections.

**Comment by esturniolo** [comment]
Hi, I've the same exact issue (No apps found for your version) but I don't have any proxy in my home.
It has direct connection to the internet.
Do you have any idea?

Thanks.

**Comment by jearton** [comment]
> Hi, I've the same exact issue (No apps found for your version) but I don't have any proxy in my home.
> It has direct connection to the internet.
> Do you have any idea?
> 
> Thanks.

You can download the two files in my screenshot above into your local storage. And then modify the endpointUrl in the two class, directly to your local file . Restart, it should works. You can try.

**Comment by jearton** [comment]
> [server/config/config.sample.php](https://github.com/nextcloud/server/blob/1cfa870821c92bdd6854171c8c073ed16529b6df/config/config.sample.php#L537)
> 
> Line 537 in [1cfa870](/nextcloud/server/commit/1cfa870821c92bdd6854171c8c073ed16529b6df)
>  'proxy' => '', 
> 
> It's possible to define a proxy for outgoing connections.

I used my private nexus server to transfer this two files, cached ten days. I didn‘t want to configure a global proxy.  If you could only configure these two urls, it would be fine.

**Comment by kesselb** [comment]
You can't install apps from the store without connectivity. Why adding more complexity here? Sure we could introduce some appstoreProxy. I closed this issue because it's not a bug. Please use this https://github.com/nextcloud/server/issues/new?labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md to create a feature request and describe your case.

**Comment by sealionking** [comment]
followed this guide and apps show up 

https://docs.nextcloud.com/server/15/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by andrewperry** [comment]
This is an issue with the timeout settings on connecting to the appstore as it is happening for me and others who have a server that is directly connected to the appstore but if the https://apps.nextcloud.com server is slow to respond, which other people are reporting it is, then nextcloud is timing out and people are having to hack the timeout.

See https://help.nextcloud.com/t/no-apps-found-for-your-version-nc16/52979/

I upgraded to the latest stable hoping that perhaps even just the timeout value had been increased so I didn't have to go digging for the GitHub post referred to, but it is still happening - which has brought me to here.

This doesn't seem to be the post with the workaround in it for updating the timeout value though....

Please reopen this issue so that nextcloud can cache the file or something for when your server is slow.

> You can't install apps from the store without connectivity. Why adding more complexity here? Sure we could introduce some appstoreProxy. If you don't use the appstore than disable it (there is a option for it in config.php).
> 
> Please use this https://github.com/nextcloud/server/issues/new?labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md to create a feature request and describe your case.
> 
> Closed this issue because it's not a bug.

**Comment by andrewperry** [comment]
I see that https://github.com/nextcloud/server/issues/14926 is the issue where this will hopefully be resolved, so this issue doesn't need reopening.

**Comment by jlord87** [comment]
I'm facing the same problem but I think I've found the real problem (in my situation).

I have several VPS in my infrastructure, all sharing the same hardware and WAN (200/20). Two independent installation of nextcloud, the first one (upgraded from an old owncloud 9 installation) has the problem, the second (installed from nextcloud 16) does not have it.

Both the two installation are "identical", even though the second one is "smaller" in data and users.

Increasing the value from 10 to 300 solve the problem in the firs installation. However I do believe that the problem - in my environment - does not come from WAN connection relate problems but from a bug in the logs:
whenever I visit the app page my /var/log/nextcloud/nextcloud.log log is flooded with garbage from the user interface cfr
[tail.txt](https://github.com/nextcloud/server/files/3932070/tail.txt)

This does not happen in the second installation were everything works great without modifying the Fetcher.php.

Can you please check in the log if you are logging something similar to my situation?

Thank you

**Comment by kesselb** [comment]
> is flooded with garbage from the user interface

@jlord87 Probably less garbage than you think ;) As written earlier and at #14926 if the connection to apps.nextcloud.com times out (limit is 10sec) a exception is thrown. The http abstraction layer includes all information (including the received data) regarding this timeout into the exception and nextcloud logs the exception. Feel free to join https://github.com/nextcloud/server/issues/18203  and probably try the patch. It will not solve the timeout issue but remove the response logging to keep your log clean.

**Comment by jlord87** [comment]
Thank you @kesselb, I've probably missed that post.
What I can't explain is why one VM has this problem and the other is not having it, sharing the same virtualization infrastructure, the same subnet, the same Internet gateway and so on...

Anyway I'll join the other discussion, thank you
