### ISSUE TITLE
File details will not change after redirecting from Favorites page

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#1448]
### Steps to reproduce

1.Make sure there are at least two files.
2.Mark one of them as favorite.
3.Go to "Favorites" page, select the favorite file. Make sure the details view is open.
4.Click the "..." to show popup menu, click "View in folder".
<img width="1186" alt="screen shot 2016-09-19 at 11 16 22 pm" src="https://cloud.githubusercontent.com/assets/19603943/18638100/6edb2680-7ec1-11e6-817a-53ccb8521737.png">
5.Verify it redirects user to the All files page and the details is still showing.
6.Select a different file or click "Details", verify that the details view is not changed accordingly.
<img width="1189" alt="screen shot 2016-09-19 at 11 15 31 pm" src="https://cloud.githubusercontent.com/assets/19603943/18638101/6f84a25a-7ec1-11e6-9282-7f0f70e1f9dd.png">
### Expected behaviour

Should show the details of selected files.
### Actual behaviour

The details does not change
### Server configuration

**Operating system**:
CentOS 7 x86_64
Linux 10.211.55.9 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
httpd-2.4.6-40.el7.centos.4.x86_64

**Database:**
sqlite3

**PHP version:**
PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**

**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Firefox ESR 38.3.0

**Operating system:**
CentOS 7 x86_64

**Comment by nickvergessen** [comment]
If you manually close the sidebar, you see a second sidebar with the information you just clicked on. So I guess there is some destory magic missing.

@MorrisJobke do you have any idea about this?

**Comment by MorrisJobke** [comment]
> @MorrisJobke do you have any idea about this?

Usually it should close the sidebar:

1. call to `changeDirectory()` https://github.com/nextcloud/server/blob/d623763aac3c1c4c0480f0d3ca7182dd2eb68357/apps/files/js/gotoplugin.js#L44-L44
2. that calls the `reload()` method: https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/filelist.js#L1401-L1401
3. that then closes the sidebar: https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/filelist.js#L1546-L1546

Let me debug this.

**Comment by MorrisJobke** [comment]
In this case following block is executed: https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/filelist.js#L490-L496

**Comment by MorrisJobke** [comment]
I just noticed that the sidebar element with the id `sidebar` exists twice. Let me check where this wrong element is added.

**Comment by MorrisJobke** [comment]
The element gets added when this line is executed: https://github.com/nextcloud/server/blob/581227324a8510688c40e9effc8b2fe6a355eba1/apps/files/js/navigation.js#L106-L106

**Comment by MorrisJobke** [comment]
The detailsview is added a second time here: https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/filelist.js#L261-L261

I think the detailsview should be destroyed on all changes between those different views.

**Comment by MorrisJobke** [comment]
> I think the detailsview should be destroyed on all changes between those different views.

It looks like it is done, but somehow there is an issue in this: https://github.com/nextcloud/server/blob/0ecaf8e6023622393090c1f2ff4c728c96eb2718/apps/files/js/filelist.js#L355-L355

**Comment by MorrisJobke** [comment]
That's all I debugged - sorry I'm out - somehow the destroy method needs to be called to properly clean this up, but I have no proper insights into this to fix it. Maybe someone from @nextcloud/javascript could help out here :=
