### ISSUE TITLE
An appeal to translators of the Polish language

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#14485]
Please, **translate** the Polish language to Transifex.
1. Translate honestly.
2. Learn about the application before the translation (if possible) and then start translating.
3. After releasing the new version of the application, see your translation and make the necessary changes.

- Please, make sure that there are no wrong translations, or even opposite translations to the description, as here #14443.
- Please, make sure that there are no translations of this kind:
> discuss this app at https://help.nextcloud.com/c/clients/android
>  dyskutuj na temat tej aplikacji na https://help.nextcloud.com ;-)

- Do not translate word for word. Translations should be as short as possible, but understandable for the user of the application. This is not a recitation contest of English vocabulary.
- You do not need to know English well, all you have to do is know the application's functions well.
- The word "folder" translates to "catalog". It's boring me to change it all the time.
- Do not usually translate words: please, you, yours, etc.

The Nexctcloud application is really a very good application and it should be properly translated, which is lacking in the Polish language version.

Thank you for your attention.

### In the Polish language version:
Proszę **Tłumaczy** języka polskiego na Transifex.
1. Tłumaczcie rzetelnie.
2. Przed tłumaczeniem poznaj aplikację (jeśli jest to możliwe), a później zacznij tłumaczyć.
3. Po wydaniu nowej wersji aplikacji zobacz swoje tłumaczenie i wprowadź konieczne zmiany.

- Proszę, aby nie było błędnych tłumaczeń, a wręcz przeciwnych tłumaczeń do opisu, jak tutaj #14443.
- Proszę, aby nie było tłumaczeń takiego rodzaju: 
> discuss this app at https://help.nextcloud.com/c/clients/android
>  dyskutuj na temat tej aplikacji na https://help.nextcloud.com ;-)

- Nie tłumaczcie słowo w słowo. Tłumaczenia powinny być jak najkrótsze, ale zrozumiałe dla użytkownika aplikacji. To nie jest konkurs recytatorski słownictwa angielskiego. 
- Nie potrzebujesz dobrze znać języka angielskiego, wystarczy dobrze poznać funkcje aplikacji.
- Słowo "folder" tłumacz na "katalog". Nudzi mnie już ciągłe zmienianie tego.
- Nie tłumacz nagminnie słów: proszę, Ty, Twój, Cię, Ciebie, Swój itd.

Aplikacja Nexctcloud naprawde jest aplikacją **bardzo dobrą** i należy się jej prawidłowe tłumaczenie, którego troche brakuje w wydaniu polskojęzycznym.

Dziękuję za uwagę.

**Comment by MorrisJobke** [comment]
I guess this is best posted in the forums on transifex. Maybe @JSoko or @rakekniven can help you where to post this.

Thanks anyways for the effort you put into this :)

**Comment by rakekniven** [comment]
@Valdnet Please make a post in the forums.
Suitable place would be: https://help.nextcloud.com/c/translations

**Comment by Valdnet** [comment]
@rakekniven Thanks. The post was written. I am waiting for its approval.
