### ISSUE TITLE
About automatic backup issues

### ISSUE THREAD

**Issue by qq690712575** [nextcloud/server#14481]
I reset my mobile phone, and the photo is named after DSP_no. But the server already has this photo, and I can't change the name of the phone, resulting in the same image name and backup failure.What should I do to make the server accept my new photos?

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
