### ISSUE TITLE
Official image on Docker Hub

### ISSUE THREAD

**Issue by ovidiub13** [nextcloud/server#145]
Any plans to have an official image of NextCloud server on Docker Hub?

**Comment by MorrisJobke** [comment]
The "official" ownCloud image was maintained by a docker community person. I think we don't aim to provide an official image yet. The current plan is to provide a easy to setup tar ball and based on that packages/images/snaps/applications could be maintained by the community of this platform. We want to focus on providing a robust software - no matter how it is run. And also regarding our limited resources nowadays we need to focus. 

Anyways: If there is somebody who wants to create a docker image: Feel free to do so and we are also open to help. 😃 

@LukasReschke @jospoortvliet @mar1u5 @mikebabb @jancborchardt @blizzz @schiessle @karlitschek @Henni Any more comments on this?

**Comment by MorrisJobke** [comment]
* distribution packages discussion: https://help.nextcloud.com/t/will-nextcloud-be-inviting-to-distribution-packages/89/
* build packages on our on: https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551/5

**Comment by karlitschek** [comment]
Yes. Exactly as @MorrisJobke said. The rule in open source is who codes decides. So if someone does a nice docker image then we have one :-)

**Comment by MorrisJobke** [comment]
I will now close this here. If somebody wants to do an image we would love it :) But we will for now not work on something like that. 

Thanks
