### ISSUE TITLE
Reverse proxy to subdirectory leads to 403 Forbidden

### ISSUE THREAD

**Issue by neunzehnachtneun** [nextcloud/server#14505]
Hi together,
I am trying to fix this since a few days without success. Maybe you can help me out.
Nextcloud is running in a subdirectory using a subdomain, which gives kind of unpretty urls: nextcloud.mydomain.de/nextcloud. I tried to avoid this using the official documentation, which recommends reverse proxy parameters. 
Thanks in advance!

### Steps to reproduce
1. Install nextcloud into a subfolder
2. Set 'overwritewebroot' to '/'
3. Open nextcloud.mydomain.de with a browser

### Expected behaviour
nextcloud.mydomain.de should serve my nextcloud instance.

### Actual behaviour
I get a 403 Forbidden error when trying to resolve nextcloud.mydomain.de and a file not found error when opening nextcloud.mydomain.de/nextcloud.

### Server configuration

**Operating system**: CentOS 7

**Web server:**

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
