### ISSUE TITLE
NC Mail App: Cannot load mailbox (Error: Cannot read property 'toRgb' of null)

### ISSUE THREAD

**Issue by Hanover96** [nextcloud/server#14509]
NC Mail App is no loading the folder/mails in the folder "Inbox" - it returns the error "Cannot read property 'toRgb' of null". All other folders/mails in other folders are loading. 

NC Version: 15.0.5 (stable)
PHP Version: 7.1.26

**Comment by ChristophWurst** [comment]
Please file aticket at https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title= by filling out the issue template.
