### ISSUE TITLE
Uploading a larger file structure with folders and files hangs. Progress of the upload bar hangs and data is not fully uploaded. The upload has to be aborted. 

### ISSUE THREAD

**Issue by chrootENV** [nextcloud/server#14506]
When uploading a folder hierarchy with 3 or more  levels and files in each level, the progress bar freezes and the data is not completely uploaded. Finally you can't leave the window, it uploads data until you stop the upload manually.

This bug occurs in the Nextcloud versions 14.x.x and 15.x.x only via the web interface. The desktop client is not affected. This error is very impractical and makes the software useless. 

### Steps to reproduce
1. Open browser Firefox 65.01, Safari 12.0.3, Google Chrome  72.0.3626.119
2. Upload a folder structure as shown in below e.g

<img width="1032" alt="bildschirmfoto 2019-03-04 um 13 56 19" src="https://user-images.githubusercontent.com/48206383/53734694-00698a80-3e85-11e9-86ec-1df372126a46.png">

3.  The Folder Structure is created but loads infinitely long up to the abort.

### Expected behaviour
The folder structure with any number of levels and files must be fully uploaded.

### Actual behaviour
When uploading a folder hierarchy with more than 4 levels and files in each level, the progress bar freezes and the data is not completely uploaded. Finally you can't leave the window, it uploads data until you stop the upload manually.

![bildschirmfoto 2019-03-04 um 13 34 26](https://user-images.githubusercontent.com/48206383/53734170-6fde7a80-3e83-11e9-83aa-a93513fddf73.png)

The error can be traced on the following Nextcloud partnerpages.
![bildschirmfoto 2019-03-04 um 13 50 09](https://user-images.githubusercontent.com/48206383/53734338-00b55600-3e84-11e9-9b1e-a22129390101.png)
![bildschirmfoto 2019-03-04 um 13 50 18](https://user-images.githubusercontent.com/48206383/53734344-03b04680-3e84-11e9-9693-e78f664e83b1.png)

### Server configuration

**Operating system**:
Debian 9, 4.9.88-1+deb9u1

**Web server:**
Apache/2.4.25 (Debian)

**Database:**
10.1.37-MariaDB

**PHP version:**
7.2.15-1
7.0

**PHP Modules:**
[PHP Modules]
apcu
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
igbinary
imagick
intl
json
ldap
libxml
mbstring
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
Reflection
session
shmop
SimpleXML
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
**Nextcloud version:** (see Nextcloud admin page)
15.0.5
14.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
14.0.4
**Where did you install Nextcloud from:**
Via official Updater, Nextcloud source

**List of activated apps:**
<details>
  - accessibility: 1.1.0
  - admin_audit: 1.5.0
  - audioplayer: 2.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - camerarawpreviews: 0.6.3
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - dav: 1.8.1
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.1
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.0.1
  - files_rightclick: 0.11.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - user_usage_report: 1.1.1
  - workflowengine: 1.5.0
</details>

**Nextcloud configuration:**
<details>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.bks-campus.ch"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.bks-campus.ch",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapUserCleanupInterval": "20",
        "default_language": "de",
        "force_language": "de",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "allow_user_to_change_display_name": false,
        "lost_password_link": "https:\/\/faq.bks-campus.ch\/index.php?action=artikel&cat=4&id=5&artlang=de",
        "skeletondirectory": "",
        "trashbin_retention_obligation": "auto, D30",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "session_lifetime": 86400,
        "session_keepalive": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 1,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "loglevel": 3,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpauthtype": "LOGIN"
    },
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
#### LDAP configuration (delete this part if not used)
<details>
<summary>        "user_ldap": {
            "_lastChange": "1551437897",
            "background_sync_interval": "1800",
            "background_sync_offset": "500",
            "background_sync_prefix": "",
            "cleanUpJobOffset": "500",
            "enabled": "yes",
            "has_memberof_filter_support": "1",
            "installed_version": "1.5.0",
            "ldap_agent_password": "********",
            "ldap_attributes_for_user_search": "",
            "ldap_backup_host": "ldaps:\/\/*******",
            "ldap_backup_port": "636",
            "ldap_base": "DC=*******,DC=ch",
            "ldap_base_groups": "OU=Groups,DC=***DC=ch",
            "ldap_base_users": "OU=people,DC=*****,DC=ch",
            "ldap_cache_ttl": "600",
            "ldap_configuration_active": "1",
            "ldap_display_name": "cn",
            "ldap_dn": "CN=BINDUSERCN=Users,DC=*****,DC=ch",
            "ldap_email_attr": "mail",
            "ldap_experienced_admin": "1",
            "ldap_expert_username_attr": "sAMAccountName",
            "ldap_group_filter": "(&(|(objectclass=group)))",
            "ldap_group_member_assoc_attribute": "member",
            "ldap_groupfilter_objectclass": "group",
            "ldap_host": "ldaps:\/\/*****",
            "ldap_login_filter": "(&(&(|(objectclass=organizationalPerson)(objectclass=person)(objectclass=user)))(|(sAMAccountName=%uid)(uid=%uid)(displayName=%uid)))",
            "ldap_login_filter_mode": "1",
            "ldap_loginfilter_attributes": "sAMAccountName",
            "ldap_port": "636",
            "ldap_quota_attr": "msDS-cloudExtensionAttribute1",
            "ldap_quota_def": "40 GB",
            "ldap_tls": "",
            "ldap_userfilter_objectclass": "organizationalPerson\nperson\nuser",
            "ldap_userlist_filter": "(&(|(objectclass=organizationalPerson)(objectclass=person)(objectclass=user)))",
            "types": "authentication"
        },</summary>

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>No entries</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary></summary>

```
{"reqId":"prdsBzrIAAicH9nzEQPI","level":3,"time":"2019-03-04T08:25:05+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Out of memory (allocated 3391094784) (tried to allocate 555745288 bytes) at \/var\/www\/html\/nextcloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOConnection.php#104","userAgent":"--","version":"15.0.5.3"}
{"reqId":"LC8Y5zm8AehgpEleTANm","level":3,"time":"2019-03-04T10:30:53+00:00","remoteAddr":"10.0.0.243","user":"admin","app":"PHP","method":"GET","url":"\/index.php\/apps\/serverinfo\/update","message":"Invalid argument supplied for foreach() at \/var\/www\/html\/nextcloud\/lib\/private\/Installer.php#388","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10.13; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Content Security Policy: Die Direktive 'child-src' sollte nicht mehr verwendet werden. Bitte verwenden Sie stattdessen die Direktive 'worker-src' zum Kontrollieren von Workern bzw. die Direktive 'frame-src' zum Kontrollieren von Frames.
JQMIGRATE: Migrate is installed, version 1.4.0 core.js:7:542
window.controllers/Controllers sollte nicht mehr verwendet werden. Verwenden Sie es nicht für die Browser-Erkennung. merged.js:2176
MarkDown Apps not available ! script.js:178:7
Switching to alternate markdown renderer script.js:179:7
New search handler registered search.js:67:4
querying Whats New data was successful: nocontent merged-template-prepend.js:4613:4
undefined merged-template-prepend.js:4614:4
TypeError: upload is null[Weitere Informationen] merged-index.js:1849:6

    init https://cloud.bks-campus.ch/index.php/js/files/merged-index.js?v=2a78a8f9-45:1849 dispatch https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:3 handle https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:3 trigger https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:3 trigger https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:7 trigger https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:3 each https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:2 each https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:2 trigger https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:3 _trigger https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:13 _onDone https://cloud.bks-campus.ch/index.php/js/files/merged-index.js?v=2a78a8f9-45:3004 e.widget/</a[t]</< https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:13 jqXHR https://cloud.bks-campus.ch/index.php/js/files/merged-index.js?v=2a78a8f9-45:3050 j https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:2 fireWith https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:2 x https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:4 b https://cloud.bks-campus.ch/core/vendor/core.js?v=2a78a8f9-45:4 
</details>

**Comment by zpintar** [comment]
I agreed.
Problem is very annoying and making Nextcloud web interface pretty useless. 
Of course, missing Upload folder option in menu is another feature lack which must be solved. For example, Pydio Cells (and old Pydio) didn't have this problem and have better web interface for uploading files&folders.

**Comment by ThePetitJean** [comment]
I agree too.

Very big problem for the user...

**Comment by GuyPaddock** [comment]
This is the single most frustrating issue for our user base.
