### ISSUE TITLE
Sharing folder with subfolderstructure

### ISSUE THREAD

**Issue by Freshdouble** [nextcloud/server#14508]
Is it possible to share folders with the whole subfolder structure?

Currently we are having the Problem that we have a media folder in which all videos and photos are stored. This folder shouldn't be fully readable for every user on our system. In this folder the subfolders are related to different projects, with multiple users working on it.

We need a way to share those subfolders with the users that need them, but those users should also see the folder structure and not just the shared folder under their root folder.

For example we have the folders:
media/project1
media/project2
media/project1&2

Users of project1 should now see:
media/project1
media/project1&2

Users of project2 should see:
media/project2
media/project1&2

Scince we have a lot off different folders showing them under the root folder is very messy.

**Comment by wiswedel** [comment]
You might want to have a look at https://apps.nextcloud.com/apps/groupfolders. Especially with the new ACL feature this might be handy for your usecase.

**Comment by franckl** [comment]
+1, we would really like to see this feature available natively in NextCloud.
Allowing each user to move its folders around makes it very difficult to manage. If I tell my coworker "look at the new docs I added to the legal/2020/company1 folder", my coworker has to remember where to look for it as he moved it to a different subfolder.

**Comment by jospoortvliet** [comment]
Groupfolders does this and is supported for custoemrs. This feature will not become a 'native' function as it clashes with the flat sharing model Nextcloud uses and would be confusing for users. See more about this in this recent blog:
https://nextcloud.com/blog/sharing-in-nextcloud/
