### ISSUE TITLE
Update 15.0.5 seem breaking S3 WebUI Uploads

### ISSUE THREAD

**Issue by couchgott** [nextcloud/server#14500]
Uploads / Sync works fine via Desktop/Mobile Clients 
Download works fine for WebGUI
Create Folders work via WebGUI
All was fine with Nextcloud Version 15.0.4 

(edith: i run 4 seperate Nexcloud Instances with the same Setup (15.05 with S3, Nginx, RDS/MariaDB) all of these have the same issue) 

### Steps to reproduce
1. Configure S3 as Primary Storage
2. Try to Upload files via Web UI

### Expected behaviour
Tell us what should happen:
Upload Successfull

### Actual behaviour
Error "Not enough free Space"

### Server configuration

**Operating system**:
Debian 9 (Stretch)

**Web server:**
Nginx 1.14.1

**Database:**
MariaDB // Amazon RDS

**PHP version:**
7.3  (alt: 7.0)

**Nextcloud version:** (see Nextcloud admin page)
15.0.5 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 15.0.4

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - bookmarks: 0.16.2
  - calendar: 1.6.4                                                                                                      
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - event_update_notification: 0.3.3
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - lookup_server_connector: 1.3.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - passwords: 2019.2.2
  - provisioning_api: 1.5.0
  - rainloop: 6.0.2
  - richdocuments: 3.2.2
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_nextcloud_notification: 1.0.3
  - twofactor_totp: 2.1.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "objectstore": {
            "class": "OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "XXXXXXXXXXXXXXX",
                "autocreate": false,
                "key": "XXXXXXXXXXXXXXXXXXX",
                "secret": "XXXXXXXXXXXXXXX",
                "use_ssl": true,
                "region": "XXXXXXXXXXXX"
            }
        },
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 0,
        "theme": "",
        "maintenance": false,
        "loglevel": 3,
        "trusted_domains": [
            "XXXXXXXXXXXXXX"
        ],
        "mail_smtpmode": "smtp",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "XXXXXXXXXXXXXXXXXXXXXXXXXXXX",
                11211
            ]
        ],
        ],
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauthtype": "PLAIN",
        "overwrite.cli.url": "https:\/\/XXXXXXXXXXXXX",
        "mail_sendmailmode": "smtp"
    }
}

```
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:**  no

```
</details>

### Client configuration
**Browser:**
FF 65 // Chrome // Edge 

**Operating system:**
W10

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>


```
No Server Errors. 
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no nextcloud.log entries.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No Errors related in Browser log.
```
</details>

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991

**Comment by couchgott** [comment]
closing this one. it was nginx related. 
even i used the config from the documentation of nextcloud.

i now switched to a working on. 
please don't pin me on why i thought it's S3/nextcloud related.

**Comment by dwaxweiler** [comment]
@couchgott How did you fix your NGINX config? I am experiencing the same issue.

**Comment by couchgott** [comment]
@dwaxweiler 
my current (working) config looks like below.
Note. I am added card/caldav support stuff. 
And i use some variables for the fastcgi pass (as i am using ispconfig)  
Hope that helps ..

`   add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Robots-Tag none;
    add_header X-Download-Options noopen;
    add_header X-Permitted-Cross-Domain-Policies none;
    add_header Referrer-Policy no-referrer;

    # Remove X-Powered-By, which is an information leak
    fastcgi_hide_header X-Powered-By;

    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }

 location ~ \.php$ {
           try_files /b615814d8f2c19dbcb25b1fbae07ce38.htm @php2;
 }

    location = /.well-known/carddav {
      return 301 $scheme://$host/remote.php/dav;
    }
    location = /.well-known/caldav {
      return 301 $scheme://$host/remote.php/dav;
    }

    # set max upload size
    client_max_body_size 20G;
    fastcgi_buffers 64 4K;

    # Enable gzip but do not remove ETag headers
    gzip on;
    gzip_vary on;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
    gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

    location / {
        rewrite ^ /index.php$request_uri;
    }

    location ~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/ {
        deny all;
    }
    location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console) {
        deny all;
    }

    location @php2 {
                        fastcgi_split_path_info ^((?U).+\.php)(/?.+)$;
                        include fastcgi_params;
                        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
                        fastcgi_param PATH_INFO $fastcgi_path_info;
                        fastcgi_param HTTPS $https;
                        {FASTCGIPASS}
                        fastcgi_intercept_errors on;
                        fastcgi_index index.php;
                        fastcgi_buffers 64 64K;
                        fastcgi_buffer_size 256k;
                        fastcgi_param modHeadersAvailable true;
                        fastcgi_read_timeout 7200; 
        }



    location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|ocs-provider\/.+|ocm-provider\/.+)\.php(?:$|\/) {
        fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param HTTPS on;
        #Avoid sending the security headers twice
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        {FASTCGIPASS}
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }

    location ~ ^\/(?:updater|ocs-provider|ocm-provider)(?:$|\/) {
        try_files $uri/ =404;
        index index.php;
    }

    # Adding the cache control header for js and css files
    # Make sure it is BELOW the PHP block
    location ~ \.(?:css|js|woff2?|svg|gif)$ {
        try_files $uri /index.php$request_uri;
        add_header Cache-Control "public, max-age=15778463";
        # Add headers to serve security related headers (It is intended to
        # have those duplicated to the ones above)
        # Before enabling Strict-Transport-Security headers please read into
        # this topic first.
        # add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;";
        #
        # WARNING: Only add the preload option once you read about
        # the consequences in https://hstspreload.org/. This option
        # will add the domain to a hardcoded list that is shipped
        # in all major browsers and getting removed from this list
        # could take several months.
        add_header X-Content-Type-Options nosniff;
        add_header X-XSS-Protection "1; mode=block";
        add_header X-Robots-Tag none;
        add_header X-Download-Options noopen;
        add_header X-Permitted-Cross-Domain-Policies none;
        add_header Referrer-Policy no-referrer;

        # Optional: Don't log access to assets
        access_log off;
    }

    location ~ \.(?:png|html|ttf|ico|jpg|jpeg)$ {
        try_files $uri /index.php$request_uri;
        # Optional: Don't log access to other assets
        access_log off;
    }
`
