### ISSUE TITLE
If 3-dot menu only has one action, show that action directly

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1450]
For a folder which was shared via link without edit permissions, the 3-dot menu only shows the »Download« action. Instead of showing the menu we should directly show the download action where the 3-dot menu would be.

![capture du 2016-09-19 19-37-20](https://cloud.githubusercontent.com/assets/925062/18642400/c56aed12-7ea0-11e6-9b5a-8812c78a0c2d.png)
(Screenshot from mobile)

cc @nextcloud/javascript @schiessle

**Comment by VagishVela** [comment]
@jancborchardt I don't mind taking this on.

**Comment by jancborchardt** [comment]
@VagishVela awesome! :) Just go ahead, and you can simply open a pull request when you are done. If you need help either ask here or in the #nextcloud-dev channel on freenode IRC. :)

**Comment by eppfel** [comment]
@VagishVela Still up for it?

**Comment by VagishVela** [comment]
@eppfel Oh yes, sorry. It fell off my radar since it wasn't assigned to me.

**Comment by rullzer** [comment]
@VagishVela mmm for some reason I can't assign you. But feel free to assign yourself

**Comment by MorrisJobke** [comment]
> @VagishVela mmm for some reason I can't assign you. But feel free to assign yourself

Only contributors can be assigned ;)

**Comment by georgehrke** [comment]
@VagishVela Any progress on this? :)

**Comment by skjnldsv** [comment]
Is this still up?

**Comment by rullzer** [comment]
Feel free to pick up!

**Comment by skjnldsv** [comment]
@rullzer hum, I don't think we use a one item popover in any location on nextcloud now. :)

**Comment by georgehrke** [comment]
@skjnldsv if u share a folder publicly, there is a three dot menu for each file with only one action: Download


We should show the download button instead

**Comment by DJCrashdummy** [comment]
IMHO the only action which makes sense to be hidden behind a 3-dot menu (no matter if it is the only button or not) is the delete-button - especially at public shares, where the user can't access the trash bin! so it is very unlikely that you delete something by accident.

...but yes, hiding the download-button behind the 3-dot menu is completely senseless.

**Comment by skjnldsv** [comment]
This will be integrated into the new vue component :)

**Comment by skjnldsv** [comment]
Now closed in the action component: https://github.com/nextcloud/nextcloud-vue/blob/55d35aef65e056e09a56754c10166365b6c3915c/src/components/Action/Action.vue#L25

**Comment by georgehrke** [comment]
@skjnldsv But does Files already make use of the vue component?

**Comment by skjnldsv** [comment]
@georgehrke ongoing process :)
This issue was more like a general idea for other apps as well
