### ISSUE TITLE
Login failure should log original IP when used with a reverse proxy

### ISSUE THREAD

**Issue by kototama** [nextcloud/server#14507]
**Is your feature request related to a problem? Please describe.**

When using nextcloud behind a reverse proxy and a user enters an invalid password in the login field of the nextcloud login page, the following is logged:

```
Mar 02 14:36:41 nextcloud Nextcloud[460]: {core} Login failed: 'a' (Remote IP: '192.168.0.1')
```

where the Remote IP is the one of the proxy server and not the one of the client issuing the request.

The real IP is stored in the `X-Real-IP` and `X-Forwarded-For` HTTP header fields.

I would like for the real IP to be logged, for security reasons.

**Describe the solution you'd like**
I would like the field `X-Real-IP` to be logged on login failures, if it is presents.

**Describe alternatives you've considered**
I could put nextcloud directly on the network but this would be a security risk.

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#defining-trusted-proxies

You added the ip of your reverse proxy to `trusted_proxies`?

**Comment by kototama** [comment]
Ohh... You are right. Sorry for taking of your time and thanks for the help.
