### ISSUE TITLE
How to update multiple nodes?

### ISSUE THREAD

**Issue by Expeto** [nextcloud/server#14515]
Hello,

I'm running nextcloud in a highly available manner, I have 12 web nodes. I want to upgrade my cluster. I haven't found any documentation on upgrading a cluster.

If I start the upgrade from the node 1, it will upgrade the db also. So when I upgrade the node 2 will it also try to upgrade the db? Am I better of upgrading a single node and creating new nodes with this image?

**Comment by rullzer** [comment]
If you run a setup with 12 web server nodes I assume you have a support subscription as well. You can reach out to support to assist you here.

In any case. You should run the upgrade only once on 1 node. And then copy over the code and config to the other nodes (or create an image form that).

**Comment by MorrisJobke** [comment]
You can find the documentation at https://portal.nextcloud.com/article/how-to-upgrade-a-clustered-environment-39.html - this one is Nextcloud subscription only, but boils down to only upgrade one and copy over the config.

If you wish to support on updating a clustered environment by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
