### ISSUE TITLE
Multiple config.php files are merged

### ISSUE THREAD

**Issue by nblock** [nextcloud/server#14518]
### Steps to reproduce
1. Update to/Install Nextcloud 15.0.5
2. Migrate values from `config.php` to a custom config: `custom.config.php`
4. Enable/disable maintenance mode

### Expected behaviour
Config settings in `custom.config.php` should stay just in this file.

### Actual behaviour
Nextcloud automatically duplicates all variables in `custom.config.php` into `custom.php` upon invocation of eg. maintenance mode (via `occ`).

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:** both

**Where did you install Nextcloud from:** tar.bz2

**Comment by rullzer** [comment]
This is actually a features. We merge this so you can have default config in place.

Just name it `config.custom.php` or `config.php.custom`. Just not `*.config.php`

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file

Hmm. Could you clarify? It looks wrong to me that these files are merged.

**Comment by pgnd** [comment]
@rullzer 
can you clarify?
comment/link by @kesselb make sense to me as well ... reading that, the files shouldn't be merged.

yet, with NC/head (atm v17), still seeing the same behavior @nblock reports
