### ISSUE TITLE
Display Tags as tooltips over files and folders

### ISSUE THREAD

**Issue by fredt34** [nextcloud/server#14525]
I've started adding some Tags to my ClientA, ClientB... folders and to some files - but there is no immediate way to see _if_ an element is tagged or not, and _which_ tags are associated with this folder or file - we must open the Info / Details pane, then the Tag line.

I'd love to see the Tags appearing as a tooltip over the file or folder when I hover the mouse on the element... and with the tuture Color Tags it would be perfect.

Thanks for the amazing job !

**Comment by kesselb** [comment]
Looks like a duplicate of #6424

**Comment by fredt34** [comment]
Yes that's in the same thread as #6424... not exactly a duplicate, but in the same category for sure.

**Comment by fredt34** [comment]
(I had searched about Tags but didn't find #6424 ...)
