### ISSUE TITLE
Group selector dies for a deleted group

### ISSUE THREAD

**Issue by avnkx** [nextcloud/server#14523]
After deleting a group that was enabled "Nextcloud Announcements", the group selector on the settings page dies with

```
TypeError: results.find(...) is undefined       settings.js:58:58
```

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
