### ISSUE TITLE
Uncaught TypeError: OCA.Files.Navigation is not a constructor

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#14556]
When loading files, I sometimes get a blank content and a js error: 
```js
Uncaught TypeError: OCA.Files.Navigation is not a constructor
    at Object.initialize (app.js:52)
    at app.js:344
    at main.js:39
```

`https://dev.skjnldsv.com/apps/files/js/app.js`

```js
		fileList: null,

		/**
		 * Backbone model for storing files preferences
		 */
		_filesConfig: null,

		/**
		 * Initializes the files app
		 */
		initialize: function() {
			this.navigation = new OCA.Files.Navigation($('#app-navigation'));
			this.$showHiddenFiles = $('input#showhiddenfilesToggle');
			var showHidden = $('#showHiddenFiles').val() === "1";
			this.$showHiddenFiles.prop('checked', showHidden);
```

I'm guessing this is a loading error? @ChristophWurst @rullzer 
Most likely after the webpack merging stuff :)

**Comment by ChristophWurst** [comment]
Also cc @MorrisJobke because he noticed that as well

![bildschirmfoto von 2019-03-06 10-55-59](https://user-images.githubusercontent.com/1374172/53872402-75140480-3ffe-11e9-87a5-d4309bf2b31e.png)

**Comment by ChristophWurst** [comment]
> Most likely after the webpack merging stuff

I'm not sure. Both `OCA.Files.Navigation` and that `app.js` are from the files app. We haven't touched the files app, however.

**Comment by ChristophWurst** [comment]
I too think that this is an issue with the loading order. I usually have the dev console open locally and then the caches get disabled. So far this has never occurred to me.

**Comment by ChristophWurst** [comment]
It's unlikely, but if the loading order is incorrect it could mean that one of the apps loads a newer jQuery. Could you check the output of `$.fn.jquery` in your console when that error occurs?

**Comment by skjnldsv** [comment]
```
$.fn.jquery
>  "2.2.4"
```

**Comment by MorrisJobke** [comment]
The `app.js` is from the files app

![bildschirmfoto 2019-03-06 um 11 55 48](https://user-images.githubusercontent.com/245432/53876309-ccb66e00-4006-11e9-9f2c-d9ff157f1199.png)

**Comment by MorrisJobke** [comment]
navigate.js is loaded after app.js

![bildschirmfoto 2019-03-06 um 12 00 57](https://user-images.githubusercontent.com/245432/53876677-9d543100-4007-11e9-80b2-28a89cedf902.png)
![bildschirmfoto 2019-03-06 um 12 01 06](https://user-images.githubusercontent.com/245432/53876678-9d543100-4007-11e9-9d8b-213d905606a2.png)

**Comment by MorrisJobke** [comment]
> navigate.js is loaded after app.js

But the app.js should be executed later, because it has a `document.ready` wrapper :/

**Comment by MorrisJobke** [comment]
Jquery 2.2.4 is loaded from this path: `webpack:///./node_modules/jquery/dist/jquery.js`

**Comment by MorrisJobke** [comment]
> Jquery 2.2.4 is loaded from this path: `webpack:///./node_modules/jquery/dist/jquery.js`

Inside `main.js`

**Comment by lgazo** [comment]
just fyi. I have experienced it recently when migrating from NC25 to more recent versions and as jtr pointed out, I turned off `debug` flag and things went back to normal.

https://help.nextcloud.com/t/oca-files-navigation-is-not-a-constructor-after-upgrade-to-nc-26-and-27/164397/1
