### ISSUE TITLE
no new webdav memory with External storage support 

### ISSUE THREAD

**Issue by Berni-MD** [nextcloud/server#14551]
NC 15.0.4
PHP 7.0.32
MySQL 5.7.25
App External storage support 1.6.0 

In my current nc installations I can no longer include **new** external memory via webdav, ftp or sftp.
Existing connections are still usable.

I have 3 installations, on 2 different servers.
1x productive installation at my hoster (MySQL)
1x fresh new installation at my hoster (SQLite)
1x at ocloud.de

With all 3 installations the same error pattern :-(
But the integration of Nextcloud memory works.

In an OC installation in the company the webdav connections are accepted - so this cannot be the reason.

Translated with www.DeepL.com/Translator

**Comment by Berni-MD** [comment]
Erste Bestätigung zu meinem Fehlerbild gibt es nun auch im Nextcloud-Forum
First confirmation to my error image is now also available in the Nextcloud-Forum

https://help.nextcloud.com/t/externer-speicher-kann-nicht-mehr-eingebunden-werden/48715/3

**Comment by Berni-MD** [comment]
The error persists and is now more than annoying.

**Comment by kesselb** [comment]
Would you mind to use the issue template (https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? I don't know how to reproduce your issue. Is this still broken for you? I think we fixed some issues related to external stora
