### ISSUE TITLE
where does the "InstantUpload" / "AutoUpload" directory live on backend server storage?

### ISSUE THREAD

**Issue by fermulator** [nextcloud/server#14555]
### Steps to reproduce
1. mobile app (i.e. Android)
2. setup "instant upload" (aka "AutoUpload")
3. use it

### Expected behaviour
1. I am unable to find "formal documentation" on the mobile app side that explains the InstantUpload feature
2. When the user is using it, where are these files stored in the backend server? -- ultimately -- I want to discover the correct way -- BY DEFAULT -- for users to have their "InstantUpload" ($HOME) directory attach to EXTERNAL STORAGE

### Actual behaviour
By default, users get an "InstantUpload" directory in their nextcloud "home dir";  this is on the LOCAL server which does not have much storage space

Also I heard about the newer-ish ability to allow users to change the "remote path", but this is confusing for most.  Would like the administrator to be able to configure the default;

### Server configuration

**Operating system**: Ubuntu 16.04
**Database:** MySQL
**PHP version:** php7
**Nextcloud version:** 14.04
**Updated from an older Nextcloud/ownCloud or fresh install:** updated /migrated over time

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by fermulator** [comment]
Any suggestions from the nextcloud team here?

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
