### ISSUE TITLE
Event Registration for Files App

### ISSUE THREAD

**Issue by Elidrake** [nextcloud/server#14577]
**Is your feature request related to a problem? Please describe.**
I'm having difficulty finding a way to make a Files Extension App run after Files is fully finished initializing.  Is there an event I could register with?

**Describe the solution you'd like**
Assuming that there isn't, it would be nice to be able to register listeners to the internal events of the Files App.

**Describe alternatives you've considered**
Right now I'm essentially keeping a particular initialization step on a setTimeout loop that checks if the Files app has finished putting itself together.  This is far from ideal, but functional.

**Additional context**
N/A

**Comment by skjnldsv** [comment]
There is lots of available events. Check existing apps and documentation :+1: 

Not the easiest to find sometimes, sorry about that, but some apps already do what you want to do, so you might find the solution there! :v:
