### ISSUE TITLE
Best practices for a deployment's domain/URL name space

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#14576]
(continuing a conversation from https://github.com/uboslinux/ubos-nextcloud/issues/41)

It would be useful to provide, to user/customers/installers, some guidelines for best practices how to lay out their domain name(s) and URL name spaces. This would be useful for Nextcloud as-is, but would probably spark some feature discussion for future Nextcloud versions. Here are some requirements as I see them:

* If the customer works for `example.com`, they probably want `http*://example.com/` and `http*://www.example.com/` to lead to a publicly facing company page, running something like the pages from a static site generator, WordPress or even a custom web app.
* With Nextcloud social, users at the `example.com` organization probably would like to use `@user@example.com` as their identifiers (not: `@user@something.example.com`)
* If the user organization uses Nextcloud to share data with their customers and/or partners, they would probably also want Nextcloud to be at `example.com` (perhaps `example.com/nextcloud`), rather than `something.example.com` (not as strong as a requirement)
* If somebody interacts with `@user@example.com` in the Fediverse, they probably expect the node to be at `example.com`, rather than `something.example.com`.

I think we should have:

1. A document that describes these and similar scenario(s), and explains them to the customer with their pros and cons
2. A document that explains how to set up some of these alternatives, or at least the preferred structure, in terms of implementation. E.g. provides suitable `htaccess` files etc
3. Implement/validate that some setups work, such as running Nextcloud at `example.com/nextcloud` while mapping Nextcloud's `ocX-*` handlers into the top-level namespace (which might otherwise be owned by Wordpress). Or make sure that redirects on that level to `/nextcloud/ocX-*` actually work.

This is more intended to be a discussion start rather than a specific feature request. Your thoughts?

**Comment by kesselb** [comment]
cc @jospoortvliet @MorrisJobke

**Comment by MorrisJobke** [comment]
> 3\. Implement/validate that some setups work, such as running Nextcloud at `example.com/nextcloud` while mapping Nextcloud's `ocX-*` handlers into the top-level namespace (which might otherwise be owned by Wordpress). Or make sure that redirects on that level to `/nextcloud/ocX-*` actually work.

That is what `/.well-known/...` URLs should be for. Also there were some discussion about those detections by @icewind1991 @schiessle and @rullzer in the past.

**Comment by MorrisJobke** [comment]
also cc @karlitschek

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
