### ISSUE TITLE
Email address from LDAP-Users not imported for contactlist

### ISSUE THREAD

**Issue by aignerat** [nextcloud/server#14575]
### Steps to reproduce
1. Bind LDAP users and check configsettings
2. Check users and look is e-mail is there
3. Press on the contacts-button (upper right) and look up the mail-icon

### Expected behaviour
The email from the ldap-user should be in all tables of the db (oc_accounts, oc_cards, oc_preferences) and in all masks where the user is shown  

### Actual behaviour
The email is shown in the user-list but not in the contact list

### Server configuration

**Operating system**: centos 7.6.1810

**Web server:** Apache 2.4

**Database:** Postgres 9.6.11

**PHP version:** PHP 7.1.26

**Nextcloud version:** (see Nextcloud admin page) 13.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 11.0.1

**Where did you install Nextcloud from:** GIT

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
not possible - redirect
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.6.1
  - admin_audit: 1.3.0
  - admin_notifications: 1.0.1
  - announcementcenter: 3.2.1
  - comments: 1.3.0
  - dav: 1.4.6
  - federatedfilesharing: 1.3.1
  - federation: 1.3.0
  - files: 1.8.0
  - files_accesscontrol: 1.3.0
  - files_antivirus: 1.3.1
  - files_automatedtagging: 1.3.0
  - files_downloadactivity: 1.2.0
  - files_external: 1.4.1
  - files_rightclick: 0.3.1
  - files_sharing: 1.5.0
  - files_texteditor: 2.5.1
  - files_trashbin: 1.3.0
  - files_versions: 1.6.0
  - files_videoplayer: 1.2.0
  - gallery: 18.0.0
  - groupfolders: 1.2.0
  - hreporting: 2.1
  - logreader: 2.0.0
  - lookup_server_connector: 1.1.0
  - nextant: 1.0.10
  - notifications: 2.1.2
  - oauth2: 1.1.0
  - onlyoffice: 2.0.4
  - password_policy: 1.3.1
  - provisioning_api: 1.3.0
  - serverinfo: 1.3.0
  - sharebymail: 1.3.0
  - spacereporting: 1.2
  - systemtags: 1.3.0
  - twofactor_backupcodes: 1.2.3
  - user_ldap: 1.3.1
  - user_saml: 1.5.0
  - workflowengine: 1.3.0
Disabled:
  - bruteforcesettings
  - calendar
  - circles
  - contacts
  - encryption
  - files_pdfviewer
  - firstrunwizard
  - nextcloud-metadata
  - nextcloud_announcements
  - notes
  - polls
  - quota_warning
  - ransomware_protection
  - registration
  - sharepoint
  - spreed
  - survey_client
  - tasks
  - theming
  - updatenotification
  - user_external
  - w2g2

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
 "system": {
        "ssoDefaultLogin": false,
        "defaultDBCredentials": true,
        "onlyAdminShare": true,
        "hideSocialMedia": true,
        "knowledgebaseenabled": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "removed",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "removed",
        "dbtype": "pgsql",
        "version": "13.0.1.1",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 25,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "enable_avatars": true,
        "log_authip": true,
        "log_authfailip": true,
        "loglevel": 2,
        "logtimezone": "Europe\/Vienna",
        "updatechecker": false,
        "appcodechecker": "",
        "theme": "removed",
        "has_internet_connection": false,
        "allowedOrigin": "removed",
        "allowPasswordReset": false,
        "skeletondirectory": "removed/skeleton",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "iscaseinsensitive": true,
        "ldap_maxbadlogoncount": "4",
        "ldap_minutesresetpolicy": "5",
        "ldapIgnoreNamingRules": false,
        "default_language": "de_DE",
        "backgroundjobs_mode": "cron",
        "cron.lockfile.location": "removed/data\/",
        "cron_log": true,
        "tempdirectory": "removed/tmp",
        "logfile": "removed.log",
        "log_rotate_size": 52428800,
        "overwritehost": "removed",
        "overwriteprotocol": "https",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "filelocking.backend": "database",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "singleuser": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 9501,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "enable_previews": true,
        "appstore.experimental.enabled": true,
        "quotaIncludesTrashbin": true,
        "trashbinPercentOfQuota": "10",
        "hideURLShortener": true,
        "excludeExternalStorageFromQuota": true,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "integrity.check.disabled": true,
        "customclient_desktop": "removed",
        "customclient_android": "removed",
        "customclient_ios": "removed",
        "hide_huemer_logo": true,
        "hide_huemer_login_logo": true,
        "transferFilesToRoot": true,
        "huemer_systemuser": "removed",
        "hreporting_public": true,
        "showRememberLogin": false,
        "force_language": "de_DE",
        "getDataPrivacyURL": "removed",
        "quota_include_external_storage": false
    }

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, not relevant for the bug
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                                                              |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                            |
| hasPagedResultSupport         |                                                                                                                                                                                              |
| homeFolderNamingRule          |                                                                                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                            |
| ldapAgentName                 | CN=appadvefss,OU=AppUser,DC=removed,DC=removed,DC=at                                                                                                                                              |
| ldapAgentPassword             | ***                                                                                                                                                                                          |
| ldapAttributesForGroupSearch  | cn                                                                                                                                                                                           |
| ldapAttributesForUserSearch   | displayname;cn;sAMAccountName;givenName;mail                                                                                                                                                 |
| ldapBackupHost                | removed|
| ldapBackupPort                | 389                                                                                                                                                                                          |
| ldapBase                      | dc=removed,dc=removed,dc=at                                                                                                                                                                       |
| ldapBaseGroups                | OU=removed,OU=gruppen,DC=removed,DC=removed,DC=at                                                                                                                                              |
| ldapBaseUsers                 | OU=Benutzer,DC=removed,DC=removed,DC=at                                                                                                                                                           |
| ldapCacheTTL                  | 600                                                                                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                                                                                            |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                              |
| ldapEmailAttribute            | mail                                                                                                                                                                                         |
| ldapExperiencedAdmin          | 1                                                                                                                                                                                            |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                                                                           |
| ldapExpertUUIDUserAttr        | sAMAccountName                                                                                                                                                                               |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                                                               |
| ldapGidNumber                 | gidNumber                                                                                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                                                                           |
| ldapGroupFilter               | (&(|(objectclass=group))(|(CN=removed_*)))                                                                                                                                                     |
| ldapGroupFilterGroups         |                                                                                                                                                                                              |
| ldapGroupFilterMode           | 1                                                                                                                                                                                            |
| ldapGroupFilterObjectclass    | group                                                                                                                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                                       |
| ldapHost                      | removed                                                                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                                                                              |
| ldapLoginFilter               | (&(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf:removed:=CN=removed,OU=removed,OU=gruppen,DC=removed,DC=removed,DC=at)(sAMAccountName=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                                                              |
| ldapLoginFilterEmail          | 0                                                                                                                                                                                            |
| ldapLoginFilterMode           | 1                                                                                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                            |
| ldapNestedGroups              | 1                                                                                                                                                                                            |
| ldapOverrideMainServer        | 0                                                                                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                                                                                          |
| ldapPort                      | 389                                                                                                                                                                                          |
| ldapQuotaAttribute            | extensionAttribute15                                                                                                                                                                         |
| ldapQuotaDefault              |                                                                                                                                                                                              |
| ldapTLS                       | 1                                                                                                                                                                                            |
| ldapUserDisplayName           | displayname                                                                                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                                                                                              |
| ldapUserFilter                | (&(objectClass=user)(!(userAccountControl:1.2.840.113556.1.4.803:=2))(memberOf:removed:=CN=removed,OU=removed,OU=gruppen,DC=removed,DC=removed,DC=at))                      |
| ldapUserFilterGroups          |                                                                                                                                                                                              |
| ldapUserFilterMode            | 1                                                                                                                                                                                            |
| ldapUserFilterObjectclass     | user                                                                                                                                                                                         |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                                                                                         |
| turnOffCertCheck              | 1                                                                                                                                                                                            |
| turnOnPasswordChange          | 0                                                                                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                            |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
+-------------------------------+--------------+
| Configuration                 | s01          |
+-------------------------------+--------------+
| hasMemberOfFilterSupport      | 0            |
| hasPagedResultSupport         |              |
| homeFolderNamingRule          |              |
| lastJpegPhotoLookup           | 0            |
| ldapAgentName                 |              |
| ldapAgentPassword             | ***          |
| ldapAttributesForGroupSearch  |              |
| ldapAttributesForUserSearch   |              |
| ldapBackupHost                |              |
| ldapBackupPort                |              |
| ldapBase                      |              |
| ldapBaseGroups                |              |
| ldapBaseUsers                 |              |
| ldapCacheTTL                  | 600          |
| ldapConfigurationActive       | 0            |
| ldapDefaultPPolicyDN          |              |
| ldapDynamicGroupMemberURL     |              |
| ldapEmailAttribute            |              |
| ldapExperiencedAdmin          | 0            |
| ldapExpertUUIDGroupAttr       |              |
| ldapExpertUUIDUserAttr        |              |
| ldapExpertUsernameAttr        |              |
| ldapGidNumber                 | gidNumber    |
| ldapGroupDisplayName          | cn           |
| ldapGroupFilter               |              |
| ldapGroupFilterGroups         |              |
| ldapGroupFilterMode           | 0            |
| ldapGroupFilterObjectclass    |              |
| ldapGroupMemberAssocAttr      | uniqueMember |
| ldapHost                      |              |
| ldapIgnoreNamingRules         |              |
| ldapLoginFilter               |              |
| ldapLoginFilterAttributes     |              |
| ldapLoginFilterEmail          | 0            |
| ldapLoginFilterMode           | 0            |
| ldapLoginFilterUsername       | 1            |
| ldapNestedGroups              | 0            |
| ldapOverrideMainServer        |              |
| ldapPagingSize                | 500          |
| ldapPort                      |              |
| ldapQuotaAttribute            |              |
| ldapQuotaDefault              |              |
| ldapTLS                       | 0            |
| ldapUserDisplayName           | displayName  |
| ldapUserDisplayName2          |              |
| ldapUserFilter                |              |
| ldapUserFilterGroups          |              |
| ldapUserFilterMode            | 0            |
| ldapUserFilterObjectclass     |              |
| ldapUuidGroupAttribute        | auto         |
| ldapUuidUserAttribute         | auto         |
| turnOffCertCheck              | 0            |
| turnOnPasswordChange          | 0            |
| useMemberOfToDetectMembership | 1            |
+-------------------------------+--------------+

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
tested in chrome + firefox, but it's no client issue
**Operating system:**
win10
### Logs
I got this logentries when using occ ldap:check-user

Warning | user_ldap | Configuration Error (prefix s01): login filter does not contain %uid place holder. | 2 hours ago
-- | -- | -- | --
Warning | user_ldap | Configuration Error (prefix s01): Not a single Base DN given. | 2 hours ago
Warning | user_ldap | Configuration Error (prefix s01): No LDAP Login Filter given! | 2 hours ago
Warning | user_ldap | Configuration Error (prefix s01): No LDAP Port given! | 2 hours ago
Warning | user_ldap | Configuration Error (prefix s01): No LDAP Host given! | 2 hours ago

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by blizzz** [comment]
> 13.0.1

is EOL, plus upgrade. When setting / changing email addresses hooks are thrown accordingly, this works. With the existing data set you might need to resync the system address book (`sudo -u www-data php occ dav:sync-system-addressbook`).

> Configuration Error (prefix s01): Not a single Base DN given.

You have two LDAP configurations and the second one has nothing set. Configure or delete it ;)
