### ISSUE TITLE
Sync check list items in tasks

### ISSUE THREAD

**Issue by achimwagenknecht** [nextcloud/server#14574]
When syncing a shared check list inside a task, items will be lost.
Steps to reproduce:

1.     Create task with OpenTasks on Android
2.     Add check list items a, b and c
3.     share with other user
4.     other user adds check list items d, e, f
5.     sync

Expected behaviour: After sync, list should contain items a, b, c, d, e, f.
Actual behaviour: check list contains items a, b, and c. Items d, e and f are lost.
Server configuration: nextcloud 12
Operating system: Linux, Android
Updated from an older Nextcloud or fresh install: Updated

**Comment by violoncelloCH** [comment]
are you sure the second user has write access to the task list?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
