### ISSUE TITLE
The object shares for the first contact if the field is empty

### ISSUE THREAD

**Issue by 1ndahous3** [nextcloud/server#14582]
NC 15.0.5 (Docker)

The object (file or folder) shares for the first contact from the list if the field is empty.

### Steps to reproduce
1. Open share menu on the object 
2. Press array (don't write symbols in the field)
![image](https://user-images.githubusercontent.com/9205230/53956617-23967300-40ed-11e9-81f7-3d19a452a659.png)

### Expected behavior
No reaction

### Actual behavior
Object shared by email

![image](https://user-images.githubusercontent.com/9205230/53956740-7ec86580-40ed-11e9-81ed-2addff01a6ac.png)

**Comment by MorrisJobke** [comment]
cc @juliushaertl @skjnldsv @danxuliu @ChristophWurst Is this to the new auto complete code?

**Comment by ChristophWurst** [comment]
> Is this to the new auto complete code?

new because of the 16 changes? Don't think so, this is 15.

**Comment by MorrisJobke** [comment]
> new because of the 16 changes? Don't think so, this is 15.

Then it could also be back ported to 15. Need to be verified.

**Comment by R0maNNN** [comment]
reproduced on 16.0.0

**Comment by juliushaertl** [comment]
I cannot reproduce this with 15 or 16

**Comment by R0maNNN** [comment]
@juliushaertl very strange, because it's easy to reproduce. Do you have at least one contact in your contact list?

**Comment by juliushaertl** [comment]
Yes, I tried with and without a contact with one email address

**Comment by szaimen** [comment]
The arrow doesn't get shown anymore before entering a character into the field, hence I cannot reproduce this issue -> closing.
