### ISSUE TITLE
Check for since tags in core/js/public

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1458]
Should check that all methods/namespaces have one of the following tags:
- `@since`
- `@deprecated`
- `@internal`

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/server/blob/master/build/OCPSinceChecker.php already does this for `@since` and `@deprecated`

**Comment by MorrisJobke** [comment]
> https://github.com/nextcloud/server/blob/master/build/OCPSinceChecker.php already does this for @since and @deprecated

....ah got it. For the JS public namespace.

**Comment by MorrisJobke** [comment]
Does anybody have an idea/library/tool that does the parsing of the JSDoc annotation?

**Comment by MorrisJobke** [comment]
I checked manually for 12 and also couldn't find any nice tools to help with that 🙈 

Move to 13.

**Comment by skjnldsv** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
> cc @ChristophWurst

Yep: https://github.com/nextcloud/server/issues/15932

**Comment by skjnldsv** [comment]
Closing this one?

**Comment by ChristophWurst** [comment]
Depends on whether you're accepting or rejecting my proposal.
