### ISSUE TITLE
Missed button which expand left menu on some pages

### ISSUE THREAD

**Issue by R0maNNN** [nextcloud/server#14581]
NC 15.0.5 (Docker)

On each page with the main and additional content, the last one is placed on the left panel. By design, it expands if there is a lot of space and hides otherwise, but instead, an icon appears that allows you to forcefully expand the panel.

![image](https://user-images.githubusercontent.com/9205230/53955717-c3063680-40ea-11e9-9c6a-edfb333fdd10.png)

On some pages there is no icon, so there is no possibility to use some functions.

For example, "right" page:
![1](https://user-images.githubusercontent.com/9205230/53955081-11b2d100-40e9-11e9-821f-a81d247f4c92.png)

And example of page with no icon:
![1](https://user-images.githubusercontent.com/9205230/53955233-7e2dd000-40e9-11e9-99db-fee06532d2e0.png)

Some broken pages:
Contacts
Apps
Users

I think that someone have to review all core pages and official apps and fix this bug.

**Comment by MorrisJobke** [comment]
> Apps
> Users

Those are handled in #14252 and the one for contacts needs to be solved in https://github.com/nextcloud/contacts
