### ISSUE TITLE
Referrer-Policy Warning in "Security & setup warnings" for 2 or more Referrer-policies

### ISSUE THREAD

**Issue by envisionUCSD** [nextcloud/server#14594]
### Steps to reproduce
1. Add a referer policy to my servers default-ssl.conf 
2. Run the security and setup warnings in Nextcloud settings menu
3.

### Expected behaviour
Nextcloud should recognize that I have a global referrer policy set and not throw a warning

### Actual behaviour
The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" or "same-origin". 

Reference #11531

### Server configuration

**Operating system**:
Raspbian Stretch
**Web server:**
Apache 2.4.25
**Database:**
mariadb
**PHP version:**
7.0.33-0+deb9u1
**Nextcloud version:** (see Nextcloud admin page)
15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
command line
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**Comment by kesselb** [comment]
I guess we have enough issues about that. If a header exists twice something is wrong. Nextcloud can not detect if the same header is added to the response by your webserver but there are ways your webserver unset headers.

Feel free to look into:
https://github.com/nextcloud/server/issues/12513
https://github.com/nextcloud/server/issues/8207

**Comment by envisionUCSD** [comment]
> I guess we have enough issues about that.

Not sure why I was asked to open this ticket then (per #11531). I guess I should have been logged into my other account @jthomasdewald 

> If a header exists twice something is wrong

I strongly disagree with this statement. It is much a better security practice to set the header at the server level. Having the dual declaration is the fault of Nextcloud not the Apache Server.

> Feel free to look into:
>#12513
>#8207

These also seemed to have been closed with the same logic. Is the decision to not change this behavior?

**Comment by kesselb** [comment]
> Having the dual declaration is the fault of Nextcloud not the Apache Server.

It's not possible to detect it. Nextcloud does not know that you set this header globally. You can configure your webserver to remove the header set by nextcloud (here are some examples for nginx: https://github.com/nextcloud/documentation/pull/674). 

> Nextcloud should recognize that I have a global referrer policy set and not throw a warning

If your server sends a header twice something is wrong and there should be a warning. 

> Not sure why I was asked to open this ticket then (per #11531). 

Sure @MorrisJobke can reopen the issue but your expected behavior is unworkable.
