### ISSUE TITLE
Ability to a direct download link to a file

### ISSUE THREAD

**Issue by sebastianschauenburg** [nextcloud/server#14593]
**Is your feature request related to a problem? Please describe.**
Currently when I copy the "direct link" to a file and send it to someone (who of course has a valid account and is logged into the same Nextcloud instance) and they click on it, it opens the web interface in the directory where the file resides. Then I still have to explain to them which file I meant and that they need to download it. (Usually I would've expected a direct link to a file (instead of to a directory) to generate a download link for that file.)

**Describe the solution you'd like**
It would be fine if there would be a "copy direct download link" feature. This is quite useful when I want to integrate Nextcloud with a wiki or within documents, where links to specific Nextcloud documents are put (for example).

**Comment by skjnldsv** [comment]
You can append /download at the end.
https://xxxxx/s/niKCpgZ4kWFefJM > 
https://xxxxx/s/niKCpgZ4kWFefJM/download

**Comment by sebastianschauenburg** [comment]
Using the browser I went to the details of a file and clicked "Copy direct link". 
A URL like the following is generated: https://nextcloud.my.domain/index.php/f/231641
Visiting that URL you'll end up in details pane of that document.

Suffixing it with /download would result in a URL such as: https://nextcloud.my.domain/index.php/f/231641/download.
Visiting that URL you'll end up in the directory the file is in and not download it.

Tested with Nextcloud 15.0.8 and 15.0.7 on 2 separate installations.

**Comment by szaimen** [comment]
Please reopen because it doesn't work!

**Comment by skjnldsv** [comment]
Hey!

Sorry, I might have misunderstood :)
You're talking about internal link? not public sharing links?

**Comment by sebastianschauenburg** [comment]
Correct. I'm not talking about public sharing links (haven't enabled anything like that). Just the normal (internal) links.

**Comment by skjnldsv** [comment]
Ahaaah! I get it now :)
Indeed, there is no way to direct download.

@jancborchardt @juliushaertl since we might want to add a way to directly open one of the action (the default for example for collabora direct open), we should maybe consider having a way to add the action id in the url?

For example https://nextcloud.my.domain/index.php/f/231641/download would trigger the download action, https://nextcloud.my.domain/index.php/f/231641/default the default action, https://nextcloud.my.domain/index.php/f/231641/extract, the extract action (if installed?) That would require a simple change on our side to just map the available actions and trigger if one matches :thinking:

**Comment by juliushaertl** [comment]
@skjnldsv Sounds good, ideally we should also make sure that the action is represented in the files app parameters so just reloading the page with the editor open will also show it again:

nextcloud.my.domain/index.php/apps/files/?dir=/&fileid=230&action=default

**Comment by skjnldsv** [comment]
You mean as a js history?

**Comment by juliushaertl** [comment]
History as well, but also so you can just copy the link and open it in a new browser tab/window and you end up on the same editing view as before.

**Comment by thebearon** [comment]
This is more or less the same as #12470, right?

**Comment by skjnldsv** [comment]
Yes @thebearon

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/server/issues/12470

**Comment by RT4U** [comment]
This implements this

https://github.com/nextcloud/server/pull/16377

**Comment by hostingnuggets** [comment]
Where can I find a status of this issue to see when it will be implemented into Nextcloud?

Thanks

**Comment by jakobroehrl** [comment]
@hostingnuggets 
Look at "Milestone"

**Comment by hostingnuggets** [comment]
Ah great, so it will be implemented into Nextcloud 17. Looking forward to that!

**Comment by skjnldsv** [comment]
@hostingnuggets 18 most likely

**Comment by hostingnuggets** [comment]
:( will have to be patient then...

**Comment by BigBen2003** [comment]
== English ==
Hi there,

another method is to go through the browser's web developer tools:

To do this, you can view the source code of the website via web developer tools. Then click on the entry to which the download link is to be searched. You only have to go a little higher in the source code, up to the class "name". The direct download link can be found in this div element.

If the context menu is not changed by the website, a "Copy link address" command is also available.

The copied URL address directly copies the desired file from the Nextcloud.

== German ==
Hallo,

eine andere Methode ist die, über Web-Entwickler-Tools der Browser zu gehen:

Hierzu lässt man sich den Source-Code der Webseite via WebEntwickler-Tools anzeigen. Anschließend klickt man auf den Eintrag, zu dem der Download-Link gesucht werden soll. Im Source-Code muss nu nur etwas höher gegangen werden, bis zur Class "name". In diesem Div-Element gefindet sich der direkte Download-Link.

Wenn das Kontext-Menü von der Webseite nicht verändert wird, steht ein Befehl "Link Adresse kopieren" auch zur Verfügung.

Die kopierte URL-Adresse kopiert direkt ohne Umwege die gewünschte Datei aus dem Nextcloud herunter.

**Comment by thekk1** [comment]
> == English == Hi there,
> 
> another method is to go through the browser's web developer tools:
> 
> To do this, you can view the source code of the website via web developer tools. Then click on the entry to which the download link is to be searched. You only have to go a little higher in the source code, up to the class "name". The direct download link can be found in this div element.
> 
> If the context menu is not changed by the website, a "Copy link address" command is also available.
> 
> The copied URL address directly copies the desired file from the Nextcloud.
> 
> == German == Hallo,
> 
> eine andere Methode ist die, über Web-Entwickler-Tools der Browser zu gehen:
> 
> Hierzu lässt man sich den Source-Code der Webseite via WebEntwickler-Tools anzeigen. Anschließend klickt man auf den Eintrag, zu dem der Download-Link gesucht werden soll. Im Source-Code muss nu nur etwas höher gegangen werden, bis zur Class "name". In diesem Div-Element gefindet sich der direkte Download-Link.
> 
> Wenn das Kontext-Menü von der Webseite nicht verändert wird, steht ein Befehl "Link Adresse kopieren" auch zur Verfügung.
> 
> Die kopierte URL-Adresse kopiert direkt ohne Umwege die gewünschte Datei aus dem Nextcloud herunter.

This method does not work on newer NC versions because there is no link showed in the developer tools anymore.
You can get the link after downloding from your browser but this is a personal link with your user account, not a generic link like ../s/{fileid}

**Comment by KodoGit** [comment]
Please reopen. It was never fixed.

**Comment by phluxi** [comment]
We need this reopened.
If you can't wget the link and get the file, it's not fixed.

**Comment by BigBen2003** [comment]
== german ==

Auf die Schnelle wurde ein AddIn entworfen, welches genau diese Funktion bietet: https://git.soeti.de/nextcloud/internlinkaction

Hinweis: Es befindet sich in einem frühen Alpha Status.
