### ISSUE TITLE
The 'edit' option for folders should be 'upload and edit'

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#146]
Some folks are confused that, to let people upload, you have to allow 'editing' for a folder in the share dialog. Especially now people look for the 'only allow uploading, not viewing of files' ability, they don't think about enabling editing as they DON'T want that!

Renaming it to 'allow upload and editing' would help with this. Or something else... I'm not sure how to do this best but the current options are a bit unclear I think.

**Comment by MorrisJobke** [comment]
@nextcloud/designers for the UX design

**Comment by rullzer** [comment]
Lets tackle that in https://github.com/nextcloud/server/pull/607

**Comment by rullzer** [comment]
Ah never mind this is for link sharing of course.

**Comment by rullzer** [comment]
See #1115
