### ISSUE TITLE
ZIP package

### ISSUE THREAD

**Issue by GlauberF** [nextcloud/server#14608]
I am trying to problem with ZIP package to continue the installation, I have PHP 7.2 and already tried to do several things and it does not work, I rebooted the server, I do not know what to do anymore, if anyone knows how to solve, it responds here.

![Deepin Screenshot_selecionar área_20190309175558](https://user-images.githubusercontent.com/11314585/54077696-eff94b80-429a-11e9-9a3c-37b6f5059c2f.png)

**Comment by BKasin** [comment]
What is the operating system of the host? If you have SSH or console access, can you please post the output of:

`cat /etc/issue` and `uname -a`

That will help a lot with solving your problem and/or determining what needs to be done.

**Comment by tstreibl** [comment]
Hi, 
guess I had same/similar problem (dependency check ok but extracting failed with "can't handle zip file, error code 28). Communyty solved it, so maybe it works for you as well :
https://help.nextcloud.com/t/webupdater-fails-updating-from-15-0-4-to-15-0-5-with-extracting-cant-handle-zip-file-error-code-28/48666

Operating System  according to questions from BKasin:
Raspbian GNU/Linux 9 \n \l
Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

**Comment by kesselb** [comment]
Hey, we track bugs and feature request here on GitHub. Please use https://help.nextcloud.com for questions about configuration and customization. 

You can check the loaded modules with php -m Keep in mind that CLI and Web usually use different configuration files.
