### ISSUE TITLE
writeStream should calcualte checksums

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#14619]
Now that we have write stream I guess adding a wrapper to calculate checksums should be rather trivial.

CC: @icewind1991

**Comment by rullzer** [comment]
Of course we could also do it more generic in the dav put method. Has the advantage that it just works. Disadvantage that it won't work when apps just use the nodeapi to write.

Maybe a simple stream wrapper to calculate cheksums would make most sense for reusable code.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/11138
