### ISSUE TITLE
Error PHP fseek(): stream does not support seeking at

### ISSUE THREAD

**Issue by claymca** [nextcloud/server#14617]
When attempting view a video file I get the following error: " The video could not be loaded, either because the server or network failed or because the format is not supported."

And the following is reported in the logs: “Error PHP fseek(): stream does not support seeking at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#82”

So to make sure the video can be played over the network I access the file from my Plex instance and the mp4 plays without error. I have googled and googled and no real solution has been posted. Is there anybody that has had the same error and have found a solution?

**Comment by Faldon** [comment]
Does your video file reside on external storage mounted in Nextcloud? More specifically, resides it on external storage mounted as smb share in Nextcloud?

**Comment by HelloLemon1992** [comment]
I have the same problem. I find the logs, always happened by request a get method to  remote.php/webdav/xxx.mp3. The files are storaged in S3.

**Comment by claymca** [comment]
> Does your video file reside on external storage mounted in Nextcloud? More specifically, resides it on external storage mounted as smb share in Nextcloud?

The video resides on storage mounted as smb. 
I installed another VM and installed Owncloud and the video plays fine in owncloud. I am getting some stuttering but I need to tune owncloud.

**Comment by Faldon** [comment]
I'm not sure about S3, but SMB mounts definitely do not support fseek or rewind. I didn't have a look into the code responsible for playing videos yet, but obviously it seems to use this method there. Maybe trying to extract metadata.
But just start to stream/play a movie file should work though.

**Comment by claymca** [comment]
Quite a few videos will not even start to stream/play.

**Comment by msumm** [comment]
I observe the same log entries every time I access a txt/md-file using the new Text App where the file is located on an external WebDAV storage.
Anyhow, there is no restriction in functionality - I can view and edit the files.

**Comment by jkroepke** [comment]
Yeah, because instead a seek, nextcloud will download the whole file first. It might be works with images oder textfiles but it wont work with large videos with the in browser video player.

**Comment by juliushaertl** [comment]
Should be fixed since https://github.com/nextcloud/server/pull/20033 for S3
