### ISSUE TITLE
No error message when trying to change the password to a common one via the user management

### ISSUE THREAD

**Issue by knutschneider** [nextcloud/server#1462]
1. Open settings/users
2. Change the password of some user to "admin3"
3. An "API" call to /settings/users/changepassword is made which returns error code 503 Service Unavailable and responds with HTML

Somewhere in the HTML you'll find this error message: "Password is within the 1,000,000 most common passwords. Please choose another one."

**Comment by nickvergessen** [comment]
This works quite fine here.
If it still happens for you with the latest 10.0.1 release, please create a new issue and include all information that is being asked for by the issue template.
