### ISSUE TITLE
Allow encoded slashes in routes by default

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#14624]
Encoded slashes in route URLs are not allowed by default.
A route for `/api/greet/{name}` will not be called if the request URL contains an URI-encoded slash (`%2F`), e.g. `/apps/testapp/api/greet/le%2Fon` will simply redirect to the default app while `/apps/testapp/api/greet/leon` works fine.

Workaround:
Specify a route `requirement` for `name`:

```
[
	'name' => 'Api#greetNameEncoded',
	'url' => '/api/greet-encoded/{name}',
	'verb' => 'GET',
	'requirements' => [
		'apiVersion' => 'v1',
		'name' => '.+',
	],
],
```

This however has the drawback that even unencoded slashes (`/`) are allowed.

Reproducible using the following test app: [testapp.tar.gz](https://github.com/nextcloud/server/files/2951835/testapp.tar.gz)

- `/apps/testapp/api/greet/leon` returns `"Hello leon"` as expected
- `/apps/testapp/api/greet-encoded/leon` returns `"Hello leon"` as expected
- `/apps/testapp/api/greet/le%2Fon` incorrectly redirects to the default app
- `/apps/testapp/api/greet-encoded/le%2Fon` returns `"Hello le\/on"` as expected
- `/apps/testapp/api/greet-encoded/le/on` incorrectly returns `"Hello le\/on"`

**Comment by skjnldsv** [comment]
Doesn't make sense by default.
But you can do that already. Regarding the encoding, thi sis up to the webserver (we have the issue on photos)
