### ISSUE TITLE
Get recent files, shared files, created date of a file using an API 

### ISSUE THREAD

**Issue by SibeeshVenu** [nextcloud/server#14636]
I am just trying to get all the recent files created by the user using the Nextcloud API. I am able to get the files, upload the files, download the files etc (for example using this API `/nextcloud/remote.php/dav/files/{UserName}`). But I could not find any API which can get the recent files. I am using the Nextcloud version 14. I am looking for an API like the following.

- `/nextcloud/remote.php/dav/files/{UserName}/recent`.
- `/nextcloud/remote.php/dav/files/{UserName}/shared`.

I am also trying to get the created date of a particular file [via file properties ](https://docs.nextcloud.com/server/14/developer_manual/client_apis/WebDAV/basic.html?highlight=shared%20files#requesting-properties), but I could find an option to find only the `d:getlastmodified`.

 Any help is really appreciated. Thank you.

**Comment by ChristophWurst** [comment]
Have a look at the APIs used by the files app. I doubt they are available for extern clients, though, so you'll have to write your own app or add these APIs.

**Comment by susnux** [comment]
Can be done with the files library: https://nextcloud-libraries.github.io/nextcloud-files/
