### ISSUE TITLE
stop responding while move multiple files

### ISSUE THREAD

**Issue by aileenfun** [nextcloud/server#14635]
### Steps to reproduce

1.Select 2 files
2. click move button
3. the file you click will not move, and it keeps progressing.

![image](https://user-images.githubusercontent.com/5237624/54178946-469c9a80-44d2-11e9-9923-7f953d27814f.png)

### Expected behaviour

it suppose to move to selected folder
### Actual behaviour
The file will not move.

### Server configuration

**Operating system**:
client: Windows 10, windows 7, chrome 72.0.3626.121.

**Web server:**

nextcloud demo server(v15.04)
my own nextcloud server installed by snap(v15.05),  on Ubuntu 18.04

**Nextcloud version:** (see Nextcloud admin page)
Demo 15.04 and my own 15.05
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**Comment by richard-dg** [comment]
This affects me too. 
Nextcloud 15.05 on CentOS 6 and CentOS 7

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
