### ISSUE TITLE
Object storage folder keep highlighted

### ISSUE THREAD

**Issue by Thorkul** [nextcloud/server#14631]
Hi,

When open nextcloud files apps, the object storage folder keep highlighted during 3 seconds.

![Sans titre](https://user-images.githubusercontent.com/1025754/54156598-96b52780-4414-11e9-9ab3-c75eca04b991.png)

### Server configuration
**Nextcloud version:** 15.0.5.3, updated from an older Nextcloud
**Are you using encryption:** no

### Client configuration
**Browser:**  Firefox 65.0.2 (64 bits)
**Operating system:** Windows 7 Pro

**Comment by skjnldsv** [comment]
Hi, yes, when it's pending some background checks, it will be set as grey.
Until it's set as fully working (otherwise will be red)
