### ISSUE TITLE
Files not automatically deleted after 30 days in trash bin

### ISSUE THREAD

**Issue by ogasser** [nextcloud/server#14633]
### Steps to reproduce
1. Have files_trashbin app enabled
2. Delete files
3. Wait 30+ days

### Expected behaviour

No files older than 30 days are deleted.

### Actual behaviour

Files older than 30 days should be deleted.

### Server configuration

**Nextcloud version:** 15.0.5

When I am deleting files, I was expecting them to be deleted after 30 days as is [hinted in the documentation](https://docs.nextcloud.com/server/15/user_manual/files/deleted_file_management.html). I do not have anything special config entry for this app in the config.php file.

I was quite surprised to see that there are still which have been deleted more than 2 years ago in the trash bin.

The [config.php.sample](https://github.com/nextcloud/server/blob/f2b118a2561952663a9040e2909ff9d20ea60ffc/config/config.sample.php) lays out that files are only deleted if there is not enough space.

While I don't think this is good practice, as ancient files are lingering around on your server, the documentation should at least be updated to reflect the fact, that files may not be deleted using the default setting (as is written in the config.sample.php file.

**Comment by timm2k** [comment]
Hi @ogasser 

a config of ```'trashbin_retention_obligation' => '30,30',``` should fix your needs.
After changing your config you can run ```occ trashbin:expire``` from CLI to force delete outdated files in trashbin.

Regards
Timm

**Comment by ogasser** [comment]
Hi @timm2k 

thanks for pointing that out.

As written in my issue description, I see this as a bug, since the wording in the documentation should reflect the fact, that files may not be deleted with the default setting.

**Comment by skjnldsv** [comment]
@ogasser so you want to edit the the documentation? :)

**Comment by spupuz** [comment]
i the same issue data not deleted from trash.
