### ISSUE TITLE
Sharing permissions of external storage roots

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#14630]
* as admin create an external storage mount and add user1 with resharing permission
* as user1 share this folder with user2 (note that the "can update" and "can delete" is not available in the sharing permissions)
* as user2 create a file in this share and try to delete it 
* :x: not possible to delete the file
* as user1 share a subfolder of that external mount folder with user2 (note that the "can update" and "can delete" permission is now available
* as user2 create a file in this share and try to delete it 
* ✅  possible to delete the file

Problem here is that the share permission code checks the root of the share for permissions, but it actually need to check if there is a permission inside this folder, because external mount points are not editable by users (same applies to group folders for example).

cc @icewind1991 @rullzer @nextcloud/sharing

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening, feel free to reopen.
