### ISSUE TITLE
Lookup server only returns 'federationId' resulting in 'Undefined index' error message in log

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#14647]
We get the following error message in our nextcloud.log:

```
Undefined index: email at \/path\/to\/nextcloud\/settings\/BackgroundJobs\/VerifyUserData.php#213
```

This is because the Lookup server only returns a `federationId` for my
user and [that case isn't handled properly](https://github.com/nextcloud/server/blob/33c34ddafafe5f8f815dbde94dc477758d67db20/settings/BackgroundJobs/VerifyUserData.php#L208-L214). If required, I'll provide my Cloud ID via email.

**Comment by skjnldsv** [comment]
Fixed for a while now https://github.com/nextcloud/server/blob/a5fa9604babdab101357016066ed72b4fcab1d21/apps/settings/lib/BackgroundJobs/VerifyUserData.php#L208-L214
