### ISSUE TITLE
wrong permissions on $dataDirectory

### ISSUE THREAD

**Issue by jniggemann** [nextcloud/server#14642]
### Steps to reproduce
1. Fresh install of nextcloud on shared hosting (uberspace)
2. permissions on directory data are set to 770
3. cron re-sets the permissions to 770 (`lib/private/legacy/util.php: chmod($dataDirectory, 0770);`)

### Expected behaviour
Webserver running under a different username than my own can access the `data `directory and read `.htaccess`

### Actual behaviour
Webserver running under a different username than my own has no access `data/.htaccess` because of 770 permissions:
`drwxrwx---.  6 myuser mygroup  4096 Mar  9 22:10 data`

### Server configuration

**Operating system**:
CentOS release 6.10

**Web server:**
Apache 2.2

**Database:**
MySQL 5.1.73-log

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
15.0.2

**Where did you install Nextcloud from:**
tarball

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - deck
  - encryption
  - files_external
  - gallery
  - survey_client
  - theming
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/33c34ddafafe5f8f815dbde94dc477758d67db20/config/config.sample.php#L719-L729

You can disable this check. I guess you need 777 only on `.htaccess`? Usually php reads the files in data and its not required for apache to access these files (this might change for static assets like css with newer nextcloud versions. I would recommend you to put your datadirectory somewhere else (outside your html folder).

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/33c34ddafafe5f8f815dbde94dc477758d67db20/config/config.sample.php#L76-L82
https://docs.nextcloud.com/server/stable/admin_manual/installation/harden_server.html?highlight=data%20directory#place-data-directory-outside-of-the-web-root

I'm closing this issue because we track bugs and feature requests on github. Please use http://help.nextcloud.com/ for configuration issues.
