### ISSUE TITLE
Lowering log level of GuzzleHttp\Exception\ConnectException from error to info

### ISSUE THREAD

**Issue by Milokita** [nextcloud/server#14649]
**Is your feature request related to a problem? Please describe.**
As some of the places block access to sites listed for internet checking. Error log will overwhelm the log

**Describe the solution you'd like**
Lowering the log level from "error" to "info"

**Describe alternatives you've considered**
It is also feasible to give the error if all sites are not reachable

**Additional context**
N/A

**Comment by kesselb** [comment]
Another alternative:

https://github.com/nextcloud/server/blob/935bb256398a6ebab4e882fc740487dfbd401f73/config/config.sample.php#L659-L677

Change `connectivity_check_domains` to a list of domains which are allowed by your firewall.

**Comment by Milokita** [comment]
thanks

> 
> 
> Another alternative:
> 
> [server/config/config.sample.php](https://github.com/nextcloud/server/blob/935bb256398a6ebab4e882fc740487dfbd401f73/config/config.sample.php#L659-L677)
> 
> Lines 659 to 677 in [935bb25](/nextcloud/server/commit/935bb256398a6ebab4e882fc740487dfbd401f73)
>  /** 
>   * Which domains to request to determine the availability of an Internet 
>   * connection. If none of these hosts are reachable, the administration panel 
>   * will show a warning. Set to an empty list to not do any such checks (warning 
>   * will still be shown). 
>   * 
>   * Defaults to the following domains: 
>   * 
>   *  - www.nextcloud.com 
>   *  - www.startpage.com 
>   *  - www.eff.org 
>   *  - www.edri.org 
>   */ 
>  'connectivity_check_domains' => array( 
>  	'www.nextcloud.com', 
>  	'www.startpage.com', 
>  	'www.eff.org', 
>  	'www.edri.org' 
>  ), 
> 
> Change `connectivity_check_domains` to a list of domains which are allowed by your firewall.

thanks
