### ISSUE TITLE
Debug core Scss is disabled

### ISSUE THREAD

**Issue by Newyork311** [nextcloud/server#14648]
Debug	no app in context	No cache entry found for /appdata_ocx84bwez2nf/avatar/adminutic/avatar.jpg (storage: local::/var/www/html/data/, internalPath: appdata_ocx84bwez2nf/avatar/adminutic/avatar.jpg)	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/css/header.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/css/styles.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/search/css/results.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/css/jquery.ocdialog.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/apps/notifications/css/styles.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/css/css-variables.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/css/server.scss, ignoring	
6 minutes ago
Debug	core	Scss is disabled for /var/www/html/core/css/jquery-ui-fixes.scss, ignoring	
6 minutes ago
Error	index	GuzzleHttp\Exception\ConnectException: cURL error 6: Couldn't resolve host 'nextcloud.com' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)	
6 minutes ago
Error	internet_connection_check	GuzzleHttp\Exception\ConnectException: cURL error 6: Couldn't resolve host 'www.edri.org' (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by Milokita** [comment]
I found the similar logs too, is it normal?

**Comment by MorrisJobke** [comment]
Yes - this is debug log. All as expected.
