### ISSUE TITLE
Internal server error when trying to download a non-exist file

### ISSUE THREAD

**Issue by m00z** [nextcloud/server#1464]
### Steps to reproduce
1. Try to download a non-exist file. For example:
   `http://10.211.55.9/nextcloud/index.php/apps/files_versions/download.php?file=../nonexistfile&revision=111`
2. Internal server error appeared.
3. Check the log. There is an exception saying unable to getOwner
### Expected behaviour

File not found
### Actual behaviour

Internal server error
<img width="1036" alt="screen shot 2016-09-20 at 9 11 39 pm" src="https://cloud.githubusercontent.com/assets/19603943/18671582/3d9bc5c8-7f77-11e6-877e-061e7f673b8d.png">
### Server configuration

**Operating system**:
CentOS 7 x86_64
Linux 10.211.55.9 3.10.0-327.el7.x86_64 #1 SMP Thu Nov 19 22:10:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
httpd-2.4.6-40.el7.centos.4.x86_64

**Database:**
sqlite3

**PHP version:**
PHP 5.4.16 (cli) (built: Aug 11 2016 21:24:59) 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**

**List of activated apps:**

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration

**Browser:**
Firefox ESR 38.3.0

**Operating system:**
CentOS 7 x86_64

**Comment by nickvergessen** [comment]
@schiessle please have a look

**Comment by MorrisJobke** [comment]
Fix is in #2519
