### ISSUE TITLE
LDAP App in Nextcloud 15 Links to Nextcloud 11 Help Docs

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/server#14650]
### Steps to reproduce
1. install the 'LDAP user and group backend' app
2. click Help in the app

### Expected behaviour
Links to: https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap.html

### Actual behaviour
Links to: https://docs.nextcloud.org/server/11/go.php?to=admin-ldap

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Source

**Comment by kesselb** [comment]
Are you using a custom theme? Some custom themes modify `buildDocLinkToKey`. Is every documentation link pointing to 11?

**Comment by terrytibbles** [comment]
Well noticed! I am using a custom theme, but even the default theme points to Nextcloud 12 (server version is 15).
