### ISSUE TITLE
Misleading (wording in) password change confirmation e-mail

### ISSUE THREAD

**Issue by marianoju** [nextcloud/server#14657]
### Steps to reproduce
1. execute lostpassword/reset function
2. open URL sent to user via e-mail 
3. set new password

### Expected behaviour
User receives a confirmation via e-mail that the password was changed. 

### Actual behaviour
User received a misleading confirmation via e-mail that the password was changed *by the administrator*: 

> Your password on [nextcloud's URL] was reset by an administrator. If you did not request this, please contact an administrator.

### Server configuration

**Operating system**:
Debian 

**Web server:**
unknown (hosting service)

**Database:**
mysql 10.1.37

**PHP version:**
7.0.33-0+deb9u3

**Nextcloud version:** 
15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Update from 15.0.2

**Where did you install Nextcloud from:**
unknown (hosting service)

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.</details>

**List of activated apps:**
<details>
<summary>App list</summary>
- Accessibility 1.1.0
- Activities for shared file downloads 1.4.0 
- Activity 2.8.2
- Auditing / Logging 1.5.0
- Brute-force settings 1.3.0
- Calendar 1.6.4
- Collabora Online 3.2.3
- Collaborative tags 1.5.0
- Comments 1.5.0
- Contacts 3.0.5
- Deck 0.5.2
- Deleted files 1.5.0
- Federation 1.5.0
- File sharing 1.7.0
- Files Right Click 0.11.1
- First run wizard 2.4.0
- Gallery 18.2.0
- Group folders 2.0.3
- Log Reader 2.0.0
- Metadata 0.9.0
- Monitoring 1.5.0
- Nextcloud announcements 1.4.0
- Notifications 2.3.0
- OwnBackup 18.11.0
- Password policy 1.5.0
- PDF viewer 1.4.0
- Share by mail 1.5.0
- Support 1.0.0
- Text editor 2.7.0
- Theming 1.6.0
- Two-Factor Admin Support 0.2.0
- Two-Factor TOTP Provider 2.1.2
- Update notification 1.5.0
- Usage survey 1.3.0
- User usage report 1.1.1
- Versions 1.8.0
- Video player 1.4.0
</details>

**Nextcloud configuration:**
<details>
No access to command line or config.php content available.
</details>

**Are you using external storage?** 
no

**Are you using encryption?** 
no

**Are you using an external user-backend?** 
no

### Client configuration
**Browsers:**
- Mozilla Firefox “Quantum” 65.0.1 (64-bit)
- Chromium 72.0.3626.121 

**Operating system:**
- Ubuntu 18.04.2 LTS

#### Web server error log
<details>

No relevant information in the error log for this bug. 
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
No relevant information in the Nextcloud log for this bug. 
</details>

#### Browser log
<details>
No relevant information in the browser log for this bug. 
</details>

**Comment by Faldon** [comment]
It seems, that the hook responsible for sending the email in fact does not distinguish if the password was proactively reset by an administrator or if the user requested  the password reset.
I guess therefore follows the notice/warning if the user requested this.

**Comment by marianoju** [comment]
> [...] the password was reset by an administrator in the widest sense (the system itself) [...] 

Let us not go down that hole. 

    administrator != system 

I am indifferent to the technicalities of the password reset itself. My problem is the misleading wording. This could be solved e.g. by either one of this measures: 

1. 

> Your password on [nextcloud's URL] was reset ~by an administrator~. If you did not request this, please contact an administrator.

2. 

> Your password on [nextcloud's URL] was reset either by yourself or by an administrator. If you did not request this, please contact an administrator to double-check. This could also be the result of an attempt to hijack your account or a technical glitch.

**Comment by Faldon** [comment]
I see your point, although I do not quite comply.
But personally, I would rather prefer your first suggestion. Despite (or even because of) this is a security related message, I wouldn't be to verbose why the password was reset. 

> Your password on [nextcloud's URL] was reset. If you did not request this, please contact an administrator.

or maybe 

> Your password on [nextcloud's URL] was recently reset. If you did not request this, please contact an administrator.

sounds good to me.
Short, terse, precise.

**Comment by Faldon** [comment]
So, the code change itself is no big deal.
But a question remains on my side, how to handle the translations respectively the l10n files.

**Comment by aignerat** [comment]
My findings aren't totally fitting to the problem, but it's still very related to my mind. I didn't test the issue in v16 but in v15 I had the finding, that an e-mail-change in AD/LDAP sends a mail to the user with a random sender-user.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
