### ISSUE TITLE
Undefined index: emal

### ISSUE THREAD

**Issue by HubbyGitter** [nextcloud/server#14651]
### Steps to reproduce
1. Install NextCloud 14.0.4
2. Update to 15.0.5.3
3. Configure AJAX cron
4. Poll /cron.php until email checks are due (at most 61 minutes)
5. Analyse logs

### Expected behaviour
The cron mechanism should check the email configuration flawlessly, according to the applicable check interval

### Actual behaviour
For each account, when the check is due, the following message appears in the log via "cron.php":
"Undefined index: email at \/home\/sites\/site111\/web\/_nxtcld\/settings\/BackgroundJobs\/VerifyUserData.php#213"

### Server configuration

**Operating system**: Gentoo Linux

**Web server:** Apache

**Database:** mariadb-10.1.37

**PHP version:** 7.3.2

**Nextcloud version:** 15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 14.0.4

**Where did you install Nextcloud from:** Hoster one-click

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.3
  - dav: 1.8.1
  - deck: 0.5.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_markdown: 2.0.5
  - files_mindmap: 0.0.11
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - occweb: 0.0.4
  - password_policy: 1.5.0
  - polls: 0.10.1
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "example.com"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "dbtype": "mysql",        "version": "15.0.5.3",        "overwrite.cli.url": "http:\/\/example.com",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "nc_0377_",        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "maintenance": false,        "theme": "",        "loglevel": 2,        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_smtpmode": "smtp",        "mail_smtpsecure": "ssl",        "mail_sendmailmode": "smtp",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_smtpauth": 1,        "mail_smtpauthtype": "PLAIN",        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_smtpport": "465",        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"    }}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox Quantum 65.0.2 (e.g.)

**Operating system:** Windows 8.1 Pro, Linux (e.g.)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
127.0.0.1 - - [11/Mar/2019:20:45:26 +0100] "GET /cron.php HTTP/1.1" 200 20 "-" "Wget/1.18 (linux-gnu)" 605 5655
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XIa61NkLMG0AAGV06k8AAAAH","level":3,"time":"2019-03-11T19:45:26+00:00","remoteAddr":"83.78.70.155","user":"--","app":"PHP","method":"GET","url":"\/cron.php","message":"Undefined index: email at \/web\/_nxtcld\/settings\/BackgroundJobs\/VerifyUserData.php#213","userAgent":"Wget\/1.18 (linux-gnu)","version":"15.0.5.3"}
```
</details>

**Comment by BramVanRensbergen** [comment]
I'm running into the same problem since yesterday. NextCloud 15.0.5.3 as well, running on a Synology (DSM Linux). 

I updated to that version yesterday, and also changed the cron settings (now actual cron rather than AJAX, and with an separate job to email any queued activity). No errors during the day (with regular mails etc.), but then in the evening I started getting the above "Undefined index: email at .../settings/BackgroundJobs/VerifyUserData.php#213"

It still appears to work fine now, so I'm not sure to what extend the error is problematic.

PS. a lot of my users DON'T have an email-adress linked to their account

**Comment by HubbyGitter** [comment]
In case it's relevant: In my setup, all users have an e-mail address configured.

**Comment by leithhobson** [comment]
I am experiencing a similar issue.

running 15.0.5.3
cron being called via system cron
all users have a valid email address (one was created without, but was updated yesterday)

[PHP] Error: Undefined index: email at /var/www/html/nextcloud/settings/BackgroundJobs/VerifyUserData.php#213

at 2019-03-14T13:15:38+00:00

**Comment by StormKMD** [comment]
I'm having this same error.

[PHP] Error: Undefined index: email at /var/www/[redacted]/settings/BackgroundJobs/VerifyUserData.php#213

GET /cron.php
from [redacted] at 2019-03-19T22:50:06+00:00

I am the only user on my server, and I have my email address entered in.

**Comment by BramVanRensbergen** [comment]
Just as an update, this seems to have resolved itself somehow for me; I did not make any changes, the device was not rebooted, no updates installed, yet somehow, the error stopped appearing around the time I made my previous post in this thread (i.e. 6 days ago).

**Comment by denysobukh** [comment]
I'm watching the same:
Undefined index: email at /var/www/[...]/settings/BackgroundJobs/VerifyUserData.php#213
15.0.5 is running

**Comment by ehirt** [comment]
I run into that issue 
[PHP] Error: Undefined index: email at /home_p2/a/r/xxxx/nextcloud/htdocs/settings/BackgroundJobs/VerifyUserData.php#213

GET /cron.php
from xxx at 2019-04-09T05:38:12+00:00
while/after updating from 15.0.5 to 15.0.6 

Any idea where to investigate? 
Thanks

**Comment by LeoCaplin** [comment]
I have the same problem:

Error | PHP | Undefined index: email at /var/XXXXXX/settings/BackgroundJobs/VerifyUserData.php#213
in Nextcloud log but not in my Server log.

I have freshly install nextcloud 15.0.7

Thanks

**Comment by kesselb** [comment]
Does this error still occur?

**Comment by denysobukh** [comment]
> Does this error still occur?

No, it doesn't, version 17.0.1

**Comment by kesselb** [comment]
Thanks :+1:
