### ISSUE TITLE
Allow optional reminders when creating birthday calendar events

### ISSUE THREAD

**Issue by ja573** [nextcloud/server#14653]
**Is your feature request related to a problem? Please describe.**
I love birthday synchronisation with the calendar app, however it's sometimes frustrating not being able to disable notifications (event reminders).

**Describe the solution you'd like**
Ideally you'd be able to toggle notifications at the contact level.

**Describe alternatives you've considered**
Otherwise I'd be happy if could simply toggle notifications at the app level (all or nothing).

**Additional context**
n/a

**Comment by skjnldsv** [comment]
Hello!
Moving the issue to the repo that manage the birthday sync :)

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1505

**Comment by sbrl** [comment]
Suggestion, @georgehrke: Perhaps when closing issues like this, you could give a reason - and maybe add a label that says "duplicate"?
