### ISSUE TITLE
erro app mail

### ISSUE THREAD

**Issue by GlauberF** [nextcloud/server#14669]
I'm having trouble setting up the mail client, it returns error and this doing the demo.

![Captura de Tela_selecionar área_20190313173005](https://user-images.githubusercontent.com/11314585/54314319-247e4780-45ba-11e9-95a2-7a567c7edf62.png)
![Captura de Tela_selecionar área_20190313173016](https://user-images.githubusercontent.com/11314585/54314320-247e4780-45ba-11e9-9af9-1bd13ded9a32.png)

**Comment by ChristophWurst** [comment]
Please use https://github.com/nextcloud/mail/issues/new?assignees=&labels=bug%2C+0.+to+triage&template=bug.md&title=
