### ISSUE TITLE
Sharing Images from slideshow view doesn't work

### ISSUE THREAD

**Issue by EugenVau** [nextcloud/server#14660]
### Steps to reproduce
1. Login to Nextcloud web interface
2. Open Files App
3. Go to a folder containing images
4. Click on an image (image is shown in slideshow)
5. Click on "share" icon in the upper right corner
6. Type at least two characters of an existing user/group into the input field

### Expected behaviour
A list of users and/or groups matching the typed in query is shown and an entry can be selected

### Actual behaviour
The right arrow on the right of the input field ist replaced by a spinner for a moment, nothing else happens. 

### Remarks
In the browser dev-tools I can see the XHR request and the response JSON contains all the matching entries. So I think the server-part is working. The suggest-list does not appear on th UI, though. Doing the same from the Gallery app (i.e. replace step 2 by "Open Gallery app") works fine, so does sharing from file listings / sidebar.

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache

**Database:**
MySQL 5.7

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14.0.8

**Where did you install Nextcloud from:**
Nextcloud Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - apporder: 0.6.0
  - audioplayer: 2.6.1
  - bookmarks: 0.16.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - cospend: 0.0.6
  - dashboard: 6.0.0
  - dav: 1.8.1
  - deck: 0.5.2
  - dicomviewer: 1.2.0
  - drawio: 0.9.2
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_antivirus: 2.0.1
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.0.1
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - gpxpod: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - metadata: 0.9.0
  - news: 13.0.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ocsms: 2.1.1
  - password_policy: 1.5.0
  - phonetrack: 0.4.4
  - photosphereviewer: 0.0.2
  - polls: 0.10.1
  - previewgenerator: 2.1.0
  - provisioning_api: 1.5.0
  - rainloop: 6.0.2
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - workflow_script: 1.0.1
  - workflowengine: 1.5.0
Disabled:
  - admin_notifications
  - caniupdate
  - circles
  - encryption
  - files_reader
  - gpxmotion
  - ojsxc
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1
        },
        "logtimezone": "UTC",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "updater.release.channel": "stable",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "theme": "",
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Epub",
            "OC\\Preview\\FB2",
            "OC\\Preview\\PDF"
        ],
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "587",
        "mail_smtptimeout": "30",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app.mail.imaplog.enabled": true,
        "app.mail.smtplog.enabled": true,
        "app.mail.imap.timeout": 30,
        "app.mail.smtp.timeout": 20,
        "app.mail.transport": "smtp-mail",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** yes, WebDAV

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** all, Chrome, Firefox, Edge, Safari

**Operating system:** Windows 10, Windows 7, Linux Mint

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors in log
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

![image](https://user-images.githubusercontent.com/13468459/54293533-6e623000-45b0-11e9-9371-162c4d6e067b.png)

</details>

**Comment by jancborchardt** [comment]
Note that for Nextcloud 16, the slideshow component is replaced with a new Viewer app :) And that will just open the regular sidebar: https://github.com/nextcloud/viewer/ :slightly_smiling_face:  So I’m closing this.

**Comment by EugenVau** [comment]
Hmm, I updated to Nextcloud 15 yesterday (it's still not in "production" release channel, btw.), NC16 ist in alpha 1. But ok.
