### ISSUE TITLE
User/Group rules for apps

### ISSUE THREAD

**Issue by Hanover96** [nextcloud/server#14667]
***User/Group rules for apps***

Admin can define that a user or a group can use only specific apps.

Example:
User12434 can use only "Mail", "Files", "Calendar";
User56789 can use all apps.

Group123 can use only "Files", "Bookmarks";
Group456 can use all apps.

**Comment by skjnldsv** [comment]
Hi!
You can already do that with Groups :)

We won't add this for uses, that would complicate things far too much!
Thanks for using Nextcloud! :sun_behind_large_cloud:
