### ISSUE TITLE
how to add ngrok to the nextcloud

### ISSUE THREAD

**Issue by KangXiaoan0416** [nextcloud/server#14678]
I have deploy my own nextcloud on a cloud server, but the disk is only have 40G size.I think it's too less for me to use.At least i have more than 500G data.So I want to deploy the nextCloud on my own computer. And I have known that the ngrok is a really good thing ,which can access inner- mess   from internet.But i don,t know how to mix the ngrok And the nextCloud. Is here anyone who knows how to deal with the question?
    I'll thank you very muck for your answer.

**Comment by KangXiaoan0416** [comment]
ngrok

**Comment by rullzer** [comment]
Hi. This sounds more like a question to the forums. https://help.nextcloud.com/
