### ISSUE TITLE
improve internal links, make it more obvious which file was shared

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#1467]
If you open a internal link to a file you get navigated to the folder and the file gets highlighted with a light gray background. But this is really hard to discover.

My suggestion, to make it more obvious which file was linked to:
- open the sidebar for the corresponding file
- have a visual effect on the line. Similar to the the top-left menu if a new app was enabled.

cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
cc @jancborchardt - as we also talked about this during the hackweek

**Comment by jancborchardt** [comment]
If the file is viewable, like if it is a txt, pdf, image, video or other where a viewer is activated for, it should even get opened directly. Is that possible?

**Comment by MorrisJobke** [comment]
I think we are running out of time for this item. I would say we need to move this to 13

**Comment by rullzer** [comment]
@icewind1991 as discussed ;)

**Comment by chaos-prevails** [comment]
@rullzer "as discussed" signifies it's fixed in NC13?

**Comment by rullzer** [comment]
No it does not. I just means I talked about it with him at th conf.

**Comment by chaos-prevails** [comment]
ok, and what was your conclusion? :)

**Comment by jancborchardt** [comment]
@chaos-prevails that it should be done as written here, and any contribution is welcome. :)

**Comment by MorrisJobke** [comment]
Nothing for 14 it seems -> moved to 15

**Comment by quentinDupont** [comment]
Hello,

I have found no other issue on this matter and it seems appropriate here:
I'm looking for the solution to share a PDF as an internal link and that **this PDF opens automatically,** as it does in a public link by the way.
Indeed, the grey highlighting of internal links does not seem very satisfying to me.

Thanks a lot for all the work :clap:

**Comment by juliushaertl** [comment]
@quentinDupont See https://github.com/nextcloud/server/issues/12470#issuecomment-653603657 for first steps towards that.

**Comment by szaimen** [comment]
I think this is implemented in the meantime
