### ISSUE TITLE
NC 13 : What is the webdav path to external storage ?

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/server#14688]
HI,

So i can see the webdav path is:

https://x.y.com/remote.php/webdav/

But i use nextcloud ONLY with external storage e.g

_personalfolder
TeamFolder
etc

So i have tried

https://x.y.com/remote.php/webdav/_personalfolder or https://x.y.com/remote.php/webdav/TeamFolder

No joy

All i can see to get to work (for testing only) is

https://x.y.com/remote.php/webdav/Local

Anybody any ideas ?

Help

ZT

**Comment by j-ed** [comment]
You should ask this question in the official [**help forum**](https://help.nextcloud.com/) and not in this issue tracker.

**Comment by zippytiff** [comment]
ok, sorry

Looks like (as is often the way), after hours of faffing, i found 2 things

- crappy webdav client using cached details
- 2FA was then stopping the client logging in properly

So no issue in the end, 

ZT
