### ISSUE TITLE
Install Nextcloud v 15.0.5

### ISSUE THREAD

**Issue by SamKer** [nextcloud/server#14685]
Hello 
sorry for my poor english
then congratulation for your works on nextcloud, i'm a fan since owncloud 5.0 and i follow, work and fork Nextcloud since a long time

here is my problem:

### Steps to reproduce
1. git clone https://github.com/nextcloud/server.git
2. cd server 
3. git submodule update --init
4. sudo apt install php7.0 php7.0-* posgresql-11
5. sudo su postgres
6. psql
7. CREATE USER nextcloud password '***';
8. CREATE DATABASE nextcloud TEMPLATE template0 OWNER nextcloud;
9. GRANT ALL ON DATABASE nextcloud TO nextcloud;
10. git checkout -b stable15 
11. php occ --version => 15.0.5
12 php maintenance:install --database "pgsql" --database-user "nextcloud" --database-pass "nextcloud" --admin-user "chuck.norris" --admin-pass "god_developper"

###ERROR: 
```bash
Error while trying to create admin user: An exception occured while executing 'ALTER TABLE oc_personnal_settings ALTER id BIGSERIAL';
SQLSTATE[42704]: Undefined object: 7 ERROR: type "bigserial" not exist
```

I don't want to switch to mysql so, i try in graphic mode, same error.
I test with postgresql 9.5, 9.6, 10 & 11, always the same result

could you verify structure database , and the process to proceed?
why , in create mode(first install), do you create table and alter it after?
thanks

### Server configuration

**Operating system**:
Ubuntu 16.04 TLS
**Web server:**
php7.2 built-in server
**Database:**
Postgresql 11
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
1st install

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
redirect to install page...

**List of activated apps:**
<details>
<summary>all the default app i suppose</summary>
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
i keep local storage to subdirectory ./data

**Are you using encryption:** yes/no
no

</details>

### Client configuration
**Browser:**
Firefox 52
**Operating system:**
Ubuntu 16.04 tLS
### Logs
the error reported

**Comment by rullzer** [comment]
This sounds more like a question for the forums: https://help.nextcloud.com/
