### ISSUE TITLE
session.auto_start

### ISSUE THREAD

**Issue by amlette** [nextcloud/server#14698]
### Steps to reproduce
Change php.ini value « session.auto_start » to 1 (session.auto_start = 1)

### Expected behaviour
Nothing wrong.

### Actual behaviour
Home page display an error message like "Server error, ask your administrator"

### Server configuration

**Operating system**:
CentOS Linux release 7.6.1810 (Core) 

**Web server:**
nginx version: nginx/1.14.2

**Database:**
Server version: 10.1.38-MariaDB MariaDB Server

**PHP version:**
PHP 7.3.3 (cli) (built: Mar  5 2019 13:50:38) ( NTS )

**Nextcloud version:**
Nextcloud 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.fabricks.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/cloud.fabricks.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
</details>

**Are you using external storage:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox Quantum 65.0.2 (64 bits)

**Operating system:**
Windows 7 Pro SP1

#### Web server error log
<details>
<summary>Web server error log</summary>
nothing
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"nZEBm8wUnMf39nR44F9M","level":3,"time":"2019-03-14T18:48:55+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#404","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"nZEBm8wUnMf39nR44F9M","level":3,"time":"2019-03-14T18:48:55+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#408","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"nZEBm8wUnMf39nR44F9M","level":3,"time":"2019-03-14T18:48:55+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#412","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"nZEBm8wUnMf39nR44F9M","level":3,"time":"2019-03-14T18:48:55+00:00","remoteAddr":"82.251.248.11","user":"--","app":"base","method":"GET","url":"\/","message":{"Exception":"ErrorException","Message":"session_name(): Cannot change session name when session is active","Code":0,"Trace":[{"function":"trapError","class":"OC\\Session\\Internal","type":"->","args":[2,"session_name(): Cannot change session name when session is active","\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php",207,{"functionName":"session_name","parameters":["oco3gvaxxgx3"],"silence":false}]},{"function":"session_name","args":["oco3gvaxxgx3"]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","line":207,"function":"call_user_func_array","args":["session_name",["oco3gvaxxgx3"]]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","line":53,"function":"invoke","class":"OC\\Session\\Internal","type":"->","args":["session_name",["oco3gvaxxgx3"]]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":424,"function":"__construct","class":"OC\\Session\\Internal","type":"->","args":["oco3gvaxxgx3"]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":656,"function":"initSession","class":"OC","type":"::","args":[]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/index.php","line":40,"args":["\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php"],"function":"require_once"}],"File":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","Line":183,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"nZEBm8wUnMf39nR44F9M","level":3,"time":"2019-03-14T18:48:55+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/fabricks.fr\/cloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"aQ3iDfHHu35EtxjeOTVX","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Regular.woff2","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#404","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"aQ3iDfHHu35EtxjeOTVX","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Regular.woff2","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#408","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"aQ3iDfHHu35EtxjeOTVX","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Regular.woff2","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#412","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"aQ3iDfHHu35EtxjeOTVX","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"base","method":"GET","url":"\/core\/fonts\/Nunito-Regular.woff2","message":{"Exception":"ErrorException","Message":"session_name(): Cannot change session name when session is active","Code":0,"Trace":[{"function":"trapError","class":"OC\\Session\\Internal","type":"->","args":[2,"session_name(): Cannot change session name when session is active","\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php",207,{"functionName":"session_name","parameters":["oco3gvaxxgx3"],"silence":false}]},{"function":"session_name","args":["oco3gvaxxgx3"]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","line":207,"function":"call_user_func_array","args":["session_name",["oco3gvaxxgx3"]]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","line":53,"function":"invoke","class":"OC\\Session\\Internal","type":"->","args":["session_name",["oco3gvaxxgx3"]]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":424,"function":"__construct","class":"OC\\Session\\Internal","type":"->","args":["oco3gvaxxgx3"]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":656,"function":"initSession","class":"OC","type":"::","args":[]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/index.php","line":40,"args":["\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php"],"function":"require_once"}],"File":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","Line":183,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"aQ3iDfHHu35EtxjeOTVX","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Regular.woff2","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/fabricks.fr\/cloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"INZkQOLZeAcabwOKY9Il","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Bold.woff2","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#404","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"INZkQOLZeAcabwOKY9Il","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Bold.woff2","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#408","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"INZkQOLZeAcabwOKY9Il","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Bold.woff2","message":"ini_set(): A session is active. You cannot change the session module's ini settings at this time at \/srv\/www\/fabricks.fr\/cloud\/lib\/base.php#412","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"INZkQOLZeAcabwOKY9Il","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"base","method":"GET","url":"\/core\/fonts\/Nunito-Bold.woff2","message":{"Exception":"ErrorException","Message":"session_name(): Cannot change session name when session is active","Code":0,"Trace":[{"function":"trapError","class":"OC\\Session\\Internal","type":"->","args":[2,"session_name(): Cannot change session name when session is active","\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php",207,{"functionName":"session_name","parameters":["oco3gvaxxgx3"],"silence":false}]},{"function":"session_name","args":["oco3gvaxxgx3"]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","line":207,"function":"call_user_func_array","args":["session_name",["oco3gvaxxgx3"]]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","line":53,"function":"invoke","class":"OC\\Session\\Internal","type":"->","args":["session_name",["oco3gvaxxgx3"]]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":424,"function":"__construct","class":"OC\\Session\\Internal","type":"->","args":["oco3gvaxxgx3"]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":656,"function":"initSession","class":"OC","type":"::","args":[]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php","line":1068,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/srv\/www\/fabricks.fr\/cloud\/index.php","line":40,"args":["\/srv\/www\/fabricks.fr\/cloud\/lib\/base.php"],"function":"require_once"}],"File":"\/srv\/www\/fabricks.fr\/cloud\/lib\/private\/Session\/Internal.php","Line":183,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"INZkQOLZeAcabwOKY9Il","level":3,"time":"2019-03-14T18:48:56+00:00","remoteAddr":"82.251.248.11","user":"--","app":"PHP","method":"GET","url":"\/core\/fonts\/Nunito-Bold.woff2","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/srv\/www\/fabricks.fr\/cloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
nothing
</details>

**Comment by kesselb** [comment]
Logs?

**Comment by ChristophWurst** [comment]
> ini_set(): A session is active. You cannot change the session module's ini settings at this time

Yeah, this won't work I guess. For some settings the session must not be started, hence this fails. Maybe setting `session.cookie_secure` to 1 in your config already resolves this.

**Comment by skjnldsv** [comment]
@rullzer, clues? :)

**Comment by ChristophWurst** [comment]
> Maybe setting `session.cookie_secure` to 1 in your config already resolves this.

@amlette have you tried that?
