### ISSUE TITLE
Hide system mapped external storage from 'All Files'

### ISSUE THREAD

**Issue by williambargent** [nextcloud/server#147]
### Improvement

I have a NextCloud installation with 10 system mapped external storage folders which all users have access to. I don't wan't these to be displayed in the 'All Files' tab only 'External Storage' as they aren't frequently used.

Could we add a checkbox into the sidebar settings menu providing the ability to hide these. (Or something similar)

**Comment by MorrisJobke** [comment]
I don't like the idea to hide random folders. Generally this makes the whole concept a lot more tricky. This then would also be weird in combination with the sync client or a web dav client. Are they also hidden there? Should an admin be able to hide them too? 

As alternative you could put them all into a subfolder. Each user can move mounted folders anywhere he wants.

cc @nextcloud/designers

**Comment by williambargent** [comment]
I just generally don't like seeing these 10 mounts being shown; it makes it look messy. Also I don't think users should be able to sync/webdav these shares (Check boxes in the admin settings to allow/prevent sync/webdav would be nice).

**Comment by jancborchardt** [comment]
»All files« are all files. The other entries are filters on that view. We also don’t hide shared files (or put them in a subfolder, as before …) neither do we hide favorites, or anything else. And then if they are hidden you have no idea if they are synced or not and also need to configure a whole lot more. The way it is now is very simple and expected.

**Comment by kainhofer** [comment]
I can only second that request. I'm managing two next cloud installations for a professional association. Some of the members are licensees for certain data, so I wanted to make the data folder from one installation available to the other installation (users cannot be synced for GDPR reasons). However, as only a small part of the members are actual licensees, I don't want to show the external folder for all members, but only in the 'external shares' tab, so all licensees have an easy way to access the share (after entering the credentials of the other installation), while all non-licensee members are not confused by an external share that is irrelevant to them and which they cannot access anyway.

**Comment by jancborchardt** [comment]
> Some of the members are licensees for certain data, so I wanted to make the data folder from one installation available to the other installation (users cannot be synced for GDPR reasons). However, as only a small part of the members are actual licensees, I don't want to show the external folder for all members, but only in the 'external shares' tab, so all licensees have an easy way to access the share (after entering the credentials of the other installation), while all non-licensee members are not confused by an external share that is irrelevant to them and which they cannot access anyway.

Did you try creating a group "Licensees" and then only enabling the external storage app for that group?

Because this issue:

> while all non-licensee members are not confused by an external share that is irrelevant to them and which they cannot access anyway.

still exists in your case when people look into the external storages section.

**Comment by skjnldsv** [comment]
> »All files« are all files. The other entries are filters on that view. We also don’t hide shared files (or put them in a subfolder, as before …) neither do we hide favorites, or anything else. And then if they are hidden you have no idea if they are synced or not and also need to configure a whole lot more. The way it is now is very simple and expected.
