### ISSUE TITLE
Upload folder menu option

### ISSUE THREAD

**Issue by zpintar** [nextcloud/server#14707]
It will be good and nice to have an "Upload folder" option in Nextcloud's "plus menu" between "Upload file" and "New folder" menu options.

Why? Because isn't intuitive that this option missing. Users can think that Nexcloud can not upload whole folders via web interface (yes, we have drag&drop option but sometime is better to have this option and dialog box to choose folder).  

BTW, drag&drop function sometimes do not work. I drag my folder on browser's screen, but after dropping nothing happened. So, I must repeat my drag&drop several times to success.

And maybe it will be better to rename "Upload file" option into "Upload file(s)" because users can think that only one file can be transferred what is not true!

**Comment by tstreibl** [comment]
the above suggestion additionally might prevents from a drag&drop bug in Chrome, Firefox and Edge:  

prepare folder A with files/subfolder in your local file system. Drag the folder A **on top** of a folder B in the nextcloud browser interface.

Result:  folder A will be uploaded as a subfolder of folder B but all files/subfolders from folder A will be missing. 

The "normal" drag&drop action, where folder b is fully opened before you start drag&drop, certainly works

I support a small nextcloud platform and can confirm that the questions "how do I upload a folder - can only upload files" or "used drag&drop but my data is missing" is quite frequent.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers for this

**Comment by tstreibl** [comment]
designers answer see https://help.nextcloud.com/t/enable-upload-of-folders-via-button-in-web-frontend/22531: incompatibilty with depreciated IE11 does not allow this feature.

**Comment by stefan-niedermann** [comment]
Why not do an progressive enhancement and implement a button for browsers that support this feature? using feature detection?

**Comment by jancborchardt** [comment]
Totally in favor of the progressive enhancement.

The question is: Do we really need a separate "Upload folder" action, or can we just name the label "Upload" and you can then simply also select folders?

**Comment by major-mayer** [comment]
Anything new on this? 
Is there a way to upload a folder using the web frontend, Firefox and a Wayland-based system?
Drag-and-drop doesn't work most of the times on my KDE desktop, even when dealing with regular files and not folders.

One drive for example simply added a dropdown menu to switch between the upload of files and folders:
![grafik](https://user-images.githubusercontent.com/17907799/180666373-bd35a631-5595-4ccc-ae2e-778ef2b38aed.png)

It works flawlessly (tho, i get a browser popup when I want to upload a whole folder).

**Comment by nimishavijay** [comment]
Again came up in the Files gap analysis, already present in all the three: Google Drive, Microsoft OneDrive and Dropbox. Also an cognitive accessibility topic, having an explicit upload button is less mental load than having to figure out if the "Upload" action allows folders. 

It can go right below the "Upload files" item in the action menu, with [the upload folder icon](https://fonts.google.com/icons?selected=Material%20Icons%20Round%3Adrive_folder_upload%3A) Also a possible follow up: clean up that action menu, such that upload actions and new doc/spreadsheet/etc actions are separated by a partition line or an NcActionCaption :)
