### ISSUE TITLE
Maximum upload size resets to 511MB

### ISSUE THREAD

**Issue by AmonBune** [nextcloud/server#14704]
Every time I upgrade my Nextcloud Installation to the next stable version, the Maximum upload size gets reset to "511 MB". I use set the value "50 GB" and adjusted the PHP config file as needed and it works. But the Nextcloud UI setting resets after each update.

Currently I'm on NC 15.0.5

**Comment by MorrisJobke** [comment]
The setting isn't used that actively anymore (only if you use a Windows mount point for example), but the mobile apps, desktop client and web all use chunked upload and don't need this setting anymore. Thus we also removed it in 16 with https://github.com/nextcloud/server/pull/14430

Thanks for the report anyways.
