### ISSUE TITLE
File-type: external URL

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#14708]
I would like to have a file that contains an external URL, so I can refer to external sources. 

Maybe this is more an idea for a new app...

**Comment by blizzz** [comment]
.deaktop files could provide that, but i agree that would need a new app. Or wait for/help with sharing in bookmarks :)

**Comment by MorrisJobke** [comment]
Makes more sense as an app. Thus I will close the ticket here in the server repo. Thanks for the feedback anyways. Maybe the app section in the forums is the better place for seeking help with that app.
