### ISSUE TITLE
Sharing links with https:// not http://

### ISSUE THREAD

**Issue by crackhd** [nextcloud/server#14718]
**Is your feature request related to a problem? Please describe.**
I upload big gigabytes of files to my nextCloud on physical host over local network, say `http://196.168.0.1/`. Upload speed is good and i need this speed everyday i work with docs in this nextCloud.
Later i need to share a public link to a friend. I set up domain, SSL and reverse proxy outside of my NAT/LAN and connect them so nextCloud is actually accessible. However, links generated on website do not include the domain and `https://` schema because i work from LAN address because of better speed.
I try change `overwritehost` to my domain and `overwriteprotocol` to `https` in `config/config.php`  to fix this, but unfortunately these options are only force redirecting **_ALL_** users to this domain and protocol.

**Describe the solution you'd like**
I suggest adding an Admin option to overwrite generated links domain and URL scheme for publicly shared links. At this moment, links are generated using the current browser URL, and this is limitation in non-standard installations where website can have multiple domains or you may need to use HTTP alongsite with HTTPS.

**Describe alternatives you've considered**
I could patching the code to change the behavior of link generation, but this will break ability to update to next versions smoothly, for example.

**Additional context**
If you use nextCloud for small network of people or alone and host it in metal bare, you may still need SSL certificate and domain that will be used to download public documents you share, a reverse proxy second webserver, or more specifically TLS termination that allows to access your nextCloud from internet using https. The best option if you already have a webserver with domain it serving with `https://`.
In this scenario, nextCloud server is separated physically from TLS-termination and the upload/download/ping speed between these two servers can play an important role, making it undesirable or impossible to use SSL for **_ALL_** users.

**Comment by rullzer** [comment]
Yes that is the way it is. We create links via method and url the current user is running as.

You could try to fix this by overwriting your url in the local dns. But this is out of scope for Nextcloud.

**Comment by crackhd** [comment]
Erkkh... Can you explain why the appropriate option to change share-only domain and protocol cannot be added to nextcloud? I am very interested.

Seems like you did not understand the problem. You cannot fix TLS-to-http with dns manipulation.

**Comment by crackhd** [comment]
Seems like you did not understand the problem. 
- You cannot fix TLS-to-http with dns manipulation and there's a reason to access site by http for some users. 
- Administrator of the "cloud" must have control over public links they may need.
- TLS imposes an increased CPU pressure and bandwidth requirements in slow networks, while domain and TLS can be only useful for sharing links to people to download.

This should not be closed and must be feature request with larger discussion (as i asked above).

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/new?labels=enhancement%2C+0.+Needs+triage&template=Feature_request.md

Please use the feature request template to request a feature. I think there is only a little chance that someone will build such a feature.

**Comment by crackhd** [comment]
Done

**Comment by crackhd** [comment]
Thank you, it's done.

**Comment by rullzer** [comment]
No. This is error prone and will introduce code not tested by more than a few people while introducing a shitload of config options. We always try to keep the config options to a minium an work with sane defaults.

You should always use TLS. Even for the local network. The overhead is negligible compared to the php overhead etc.
If you really want to run in an unrecommended setup you should change the links yourself. Or login to the public facing website to copy them.

**Comment by recolic** [comment]
> No. This is error prone and will introduce code not tested by more than a few people while introducing a shitload of config options. We always try to keep the config options to a minium an work with sane defaults.
> 
> You should always use TLS. Even for the local network. The overhead is negligible compared to the php overhead etc.
> If you really want to run in an unrecommended setup you should change the links yourself. Or login to the public facing website to copy them.

No. I have nextcloud running in docker, listening 127.0.0.1:8080. And have nginx running at 0.0.0.0:443. It's not necessary to self-sign a certificate for `127.0.0.1:8080` and trust it. There should be an option to set the url `prefix`.

**Comment by not-a-user** [comment]
I do access the web frontend via https but still my public links are http. My instance is behind an nginx reverse proxy, which is the tls termination point. Are there any special nginx configuration options required that I missed?

**Comment by kesselb** [comment]
@not-a-user https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html

**Comment by not-a-user** [comment]
@kesselb Thanks for the link! I added `'overwriteprotocol' => 'https',` to my `config.php` and it works. Now both the web frontend and the android app generate https links. (Note: I already had `'overwrite.cli.url' => 'https://my-host.com/my-installdir',` but that is not sufficient.)

**Comment by kesselb** [comment]
For nginx as reserve proxy it should be enough to add the ip of your reverse proxy to `trusted_proxies` but `overwriteprotocol` is fine too.

**Comment by olodar** [comment]
> You should always use TLS. Even for the local network.

You gotta be kidding? Why you thind it is should be used for lan?
