### ISSUE TITLE
[PHP] Error: unlink(/var/www/html/ ... : No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#227

### ISSUE THREAD

**Issue by PpaiSanchez** [nextcloud/server#14714]
Hello, in my logfiles I always see similar error messages and can not explain them to me.
NC: 15.0.5.3
PHP: 7.2.15
OS: Ubuntu 18.04 LTS
All updates installed.

1.
[PHP] Error: unlink(/var/www/html/data/appdata_ocra3uc9qczf/css/core/8aae-8b7a-server.css.gzip): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#227

GET /css/core/8aae-8b7a-ie.css?v=1d916a640b4e399006848111f9969bad-314b40b7-23
from 10.1.1.3 by xxx at 2019-03-14T10:18:09+01:00

2.
[PHP] Error: unlink(/var/www/html/data/appdata_ocra3uc9qczf/css/icons/icons-vars.css): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#227

GET /css/notifications/70e2-8b7a-styles.css?v=1d916a640b4e399006848111f9969bad-70e2b24f-23
from 10.1.1.3 by xxx at 2019-03-14T10:18:03+01:00

3. 
...

All messages always refer to CSS files.
Is this a server error?
What can I do?
Thank you.

**Comment by PpaiSanchez** [comment]
In the forum other users have confirmed the error.
==> https://help.nextcloud.com/t/php-error-unlink-var-www-html-no-such-file-or-directory-at-var-www-html-lib-private-files-storage-local-php-227/49594/8

**Comment by skjnldsv** [comment]
Have you tried a maintenance repair?
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:

**Comment by vogelfreiheit** [comment]
Just experienced this too:
```

{"reqId":"XXXX","level":3,"time":"2019-08-19T05:00:49+00:00","remoteAddr":"XXX","user":"admin","app":"PHP","method":"POST","url":"\/apps\/theming\/ajax\/updateStylesheet","message":"unlink(\/nextcloud-data\/appdata_ocfy2a83w3el\/css\/theming\/6a15-a5b4-theming.css.deps): No such file or directory at \/var\/www\/html\/lib\/private\/Files\/Storage\/Local.php#228","userAgent":"Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/XXX (KHTML, like Gecko) Chrome\/XXX Safari\/537.36","version":"XXX"}
data/filestore/nextcloud.log (END)

```

While changing the theme colors.
