### ISSUE TITLE
Every activity is listed twice in notifications

### ISSUE THREAD

**Issue by ddrchs** [nextcloud/server#14710]
This issue exists with all notification mails and notifications in the Nextcloud. It already exists since some versions.

**Nextcloud version:** 15.0.5

**Comment by j-ed** [comment]
Unfortunately you not followed the issue template and provided more useful and detailed information on how to reproduce the problem. I've not yet seen any duplicate notifications on my system.

**Comment by MorrisJobke** [comment]
As there is no report since a while and we can't reproduce the issue I will close this ticket. If this is still happening please feel free to reopen.
