### ISSUE TITLE
call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212

### ISSUE THREAD

**Issue by khalsajing** [nextcloud/server#14728]
### Steps to reproduce
1. Installed docker/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/
2. Switched to the 'beta' channel, which is, at this time the same as the official nextcloud release.
3. No apparent end-user issues, except for the continuous error log entries (shown in the title).

### Expected behaviour
The error log should not be reporting call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 as I had made NO changes to this config file.

### Actual behaviour
Error log reports: call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212

### Server configuration
lscpu: Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                4
On-line CPU(s) list:   0-3
Thread(s) per core:    2
Core(s) per socket:    2
Socket(s):             1
NUMA node(s):          1
Vendor ID:             AuthenticAMD
CPU family:            21
Model:                 56
Model name:            AMD A10-7860K Radeon R7, 12 Compute Cores 4C+8G
Stepping:              1
CPU MHz:               1400.000
CPU max MHz:           3600.0000
CPU min MHz:           1400.0000
BogoMIPS:              7186.62
Virtualization:        AMD-V
L1d cache:             16K
L1i cache:             96K
L2 cache:              2048K
NUMA node0 CPU(s):     0-3
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc extd_apicid aperfmperf pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 popcnt aes xsave avx f16c lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs xop skinit wdt lwp fma4 tce nodeid_msr tbm topoext perfctr_core perfctr_nb bpext ptsc cpb hw_pstate ssbd vmmcall fsgsbase bmi1 xsaveopt arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold overflow_recov
MemTotal:       15430548 kB
MemFree:        12933936 kB
MemAvailable:   14252784 kB
Buffers:           58960 kB
Cached:          1129624 kB
SwapCached:            0 kB
Active:          1097080 kB
Inactive:         704208 kB

**Operating system**: Running in Docker Containers leveraging the example at docker/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/.
uname -a: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

**Web server:**
apache2 -v: Server version: Apache/2.4.25 (Debian)
Server built:   2018-11-03T18:46:19
**Database:**
SELECT VERSION();
+----------------------------------------+
| VERSION()                              |
+----------------------------------------+
| 10.3.13-MariaDB-1:10.3.13+maria~bionic |

**PHP version:**
PHP_VERSION | 7.2.16

**Nextcloud version:** (see Nextcloud admin page)

Version: Nextcloud 15.0.5
Your version is up to date. 

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh.

**Where did you install Nextcloud from:**
docker/.examples/docker-compose/with-nginx-proxy/mariadb-cron-redis/apache/.

**Signing status:**
<details>
<summary>Signing status</summary>
Not sure I know what this is ("Signing Status")?
occ $ status
  - installed: true  - version: 15.0.5.3  - versionstring: 15.0.5  - edition: 

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
occ $ app:list
Enabled:  - accessibility: 1.1.0  - activity: 2.8.2  - audioplayer: 2.6.1  - bruteforcesettings: 1.3.0  - cloud_federation_api: 0.1.0  - comments: 1.5.0  - dav: 1.8.1  - dicomviewer: 1.2.0  - federatedfilesharing: 1.5.0  - federation: 1.5.0  - files: 1.10.0  - files_external: 1.6.0  - files_pdfviewer: 1.4.0  - files_rightclick: 0.11.1  - files_sharing: 1.7.0  - files_texteditor: 2.7.0  - files_trashbin: 1.5.0  - files_versions: 1.8.0  - files_videoplayer: 1.4.0  - firstrunwizard: 2.4.0  - gallery: 18.2.0  - logreader: 2.0.0  - lookup_server_connector: 1.3.0  - music: 0.9.3  - news: 13.1.1  - nextcloud_announcements: 1.4.0  - notifications: 2.3.0  - oauth2: 1.3.0  - occweb: 0.0.4  - password_policy: 1.5.0  - phonetrack: 0.4.4  - photosphereviewer: 0.0.2  - provisioning_api: 1.5.0  - radio: 0.6.4  - serverinfo: 1.5.0  - sharebymail: 1.5.0  - support: 1.0.0  - survey_client: 1.3.0  - systemtags: 1.5.0  - theming: 1.6.0  - twofactor_backupcodes: 1.4.1  - unsplash: 1.1.3  - updatenotification: 1.5.0  - workflowengine: 1.5.0Disabled:  - admin_audit  - encryption  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
occ $ config:list system
{    "system": {        "htaccess.RewriteBase": "\/",        "memcache.local": "\\OC\\Memcache\\APCu",        "apps_paths": [            {                "path": "\/var\/www\/html\/apps",                "url": "\/apps",                "writable": false            },            {                "path": "\/var\/www\/html\/custom_apps",                "url": "\/custom_apps",                "writable": true            }        ],        "memcache.distributed": "\\OC\\Memcache\\Redis",        "memcache.locking": "\\OC\\Memcache\\Redis",        "redis": {            "host": "***REMOVED SENSITIVE VALUE***",            "port": 6379        },        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [            "192.168.86.110",            "xxx.xxx.xxx"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "dbtype": "mysql",        "version": "15.0.5.3",        "overwrite.cli.url": "http:\/\/xxx.xxx.xxx",        "overwritehost": "xxx.xxx.xxx",        "overwriteprotocol": "https",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "mail_smtpmode": "smtp",        "mail_smtpsecure": "ssl",        "mail_sendmailmode": "smtp",        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_smtpauth": 1,        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_smtpport": "465",        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        "updater.release.channel": "beta"    }}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No external. OS is in Raid0 (mdadm) SSDs. Data: Raid0 (mdadm) 8TB mirror.

**Are you using encryption:** yes/no
No. Not yet.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
occ $ ldap:show-config
There are no commands defined in the "ldap" namespace.  
                                                         
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';
ERROR 1046 (3D000): No database selected

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox Quantum 65.0.2(64-bit)
Google Chrome Version 73.0.3683.75 (Official Build) (64-bit)
Chromium Version 72.0.3626.121 (RPMFusion Build) chromium-vaapi (64-bit)

**Operating system:**
uname -a: Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here

Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:25:43-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:25:39-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:25:30-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:24:03-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:14:02-0500
Warning | core | Login failed: 'admin' (Remote IP: '172.20.0.3') |   | 2019-03-16T23:13:55-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:10:24-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T23:03:30-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T22:11:09-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T14:20:17-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T14:20:13-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T14:19:45-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T14:19:22-0500
Error | PHP | call_user_func() expects parameter 1 to be a valid callback, no array or string given at /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php#212 |   | 2019-03-16T14:16:18-0500
Error

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
cat nextcloud.log 
{"reqId":"bxO6qeY1uf3FBHlhpA8S","level":3,"time":"2019-03-16T04:42:26+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"DyLDhD24rMg3ulZ84Bpe","level":3,"time":"2019-03-16T19:02:06+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"LKPisgjKizWvInVC7yUH","level":3,"time":"2019-03-16T19:16:18+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"130I81YudS4MHfZC0U20","level":3,"time":"2019-03-16T19:19:22+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"KXBhMgQTG1mQdrfmkakr","level":3,"time":"2019-03-16T19:19:45+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"2zxIOkrpwYT1Es0fagC3","level":3,"time":"2019-03-16T19:20:13+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"5mJwHfJygMthGAS2akTB","level":3,"time":"2019-03-16T19:20:17+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"GSwsQBMvsBgSjTkrNkGv","level":3,"time":"2019-03-17T03:11:09+00:00","remoteAddr":"172.20.0.2","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"VVNHMIReFVEyzxCRAK8L","level":3,"time":"2019-03-17T04:03:30+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"i2AT2ifOgk7OPTeb4JMt","level":3,"time":"2019-03-17T04:10:24+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"T9Sr6ebTh6tXibvkQFox","level":2,"time":"2019-03-17T04:13:55+00:00","remoteAddr":"172.20.0.3","user":"--","app":"core","method":"POST","url":"\/login?redirect_url=\/index.php\/settings\/integrity\/failed","message":"Login failed: 'admin' (Remote IP: '172.20.0.3')","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"qhtF2wSvUi4iZNbUq2M0","level":3,"time":"2019-03-17T04:14:02+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:65.0) Gecko\/20100101 Firefox\/65.0","version":"15.0.5.3"}
{"reqId":"owpR5MtZkBqXbqGvdjqH","level":3,"time":"2019-03-17T04:24:03+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.121 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"FXQfon7bzQ26CMgLahIt","level":3,"time":"2019-03-17T04:25:30+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"A6eQq7upsnRwoq5p3VhM","level":3,"time":"2019-03-17T04:25:39+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36","version":"15.0.5.3"}
{"reqId":"K1DIdeEcaIX0ECQ2OZrs","level":3,"time":"2019-03-17T04:25:43+00:00","remoteAddr":"172.20.0.3","user":"admin","app":"PHP","method":"GET","url":"\/apps\/files\/","message":"call_user_func() expects parameter 1 to be a valid callback, no array or string given at \/var\/www\/html\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php#212","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.75 Safari\/537.36"
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
core.js?v=7fc9aeb0-0:7 JQMIGRATE: Migrate is installed, version 1.4.0
settings.js?v=7fc9aeb0-0:4 Uncaught TypeError: Cannot read property 'save' of undefined
    at initialize (settings.js?v=7fc9aeb0-0:4)
    at settings.js?v=7fc9aeb0-0:49
    at settings.js?v=7fc9aeb0-0:50
content.min.js:2 [Deprecation] Element.createShadowRoot is deprecated and will be removed in M73, around March 2019. Please use Element.attachShadow instead. See https://www.chromestatus.com/features/4507242028072960 for more details.
(anonymous) @ content.min.js:2
DevTools failed to parse SourceMap: https://xxx.xxx.xxx/custom_apps/dicomviewer/js/app.bundle.js.map
DevTools failed to parse SourceMap: https://xxx.xxx.xxx/apps/notifications/js/notifications.js.map
DevTools failed to parse SourceMap: https://xxx.xxx.xxx/apps/logreader/build/main.css.map
DevTools failed to parse SourceMap: https://xxx.xxx.xxx/apps/logreader/build/main.js.map

</details>

**Comment by kesselb** [comment]
Do you still see this warning?
