### ISSUE TITLE
Collabora with S3 backend fails with fseek() errors

### ISSUE THREAD

**Issue by theopen-institute** [nextcloud/server#14727]
I'm facing some trouble with the Collabora plugin with my otherwise well functioning 15.0.5 install. I am posting here because I think the problem is related to the filesystem backend rather than Collabora itself.

Whenever I try to open a document with Collabora, I get an infinite spinning wheel and piles of fseek() errors. I think this is related to the fact that I am using S3 as a file backend. The error looks like this:

`{"reqId":"QBCv4yaqR8C7sWaBnoIt","level":3,"time":"2019-03-15T10:19:18+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"xxxxx","app":"PHP","method":"GET","url":"/core/preview?fileId=2672&c=5bb70dd063d93&x=500&y=500&forceIcon=0","message":"fseek(): stream does not support seeking at /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/Wrapper.php#82","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36 OPR/58.0.3135.79","version":"15.0.5.3","id":"5c8b7c675f647"}`

I believe that Collabora is otherwise working, as I am able to access the admin page remotely.

### Steps to reproduce
1. Setup a Nextcloud instance with S3 backend. Install the collabora docker.
2. Create a new file and try to open it, or try to open an already existing document file.
3. Watch loading wheel spin interminably, and see the logs fill up.

### Expected behaviour
Document should open in Collabora

### Actual behaviour
Loading wheel spins and every few seconds a new fseek() error is added to the log.

### Server configuration
**Operating system**: Ubuntu 18.0.4

**Web server:** nginx 1.14.0-0ubuntu1.2

**Database:** mariadb 10.2

**PHP version:** php7.2-fpm

**Nextcloud version:** (see Nextcloud admin page) 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** tested and present on both fresh install and old instance

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** no

**Comment by theopen-institute** [comment]
I believe this is linked with [this issue](https://github.com/nextcloud/server/issues/8275), but I'm not sure. The error message does not contain a stack trace.

**Comment by MorrisJobke** [comment]
cc @rullzer @juliushaertl Didn't one of you looked into something like this recently?

**Comment by juliushaertl** [comment]
This should be fixed with https://github.com/nextcloud/richdocuments/pull/506. Please try upgrading to the latest richdocuments version
