### ISSUE TITLE
CSP issues Talk app on password reset

### ISSUE THREAD

**Issue by bonanza123** [nextcloud/server#14720]
1. Enable Talk app and set TURN sever `turn.domain.org:5349`
2. Request password reset for your account
3. Click passsword reset link and try to enter new password. Hit enter

### Expected behaviour
The next page loads, e.g. login or whatever usually is supposed to be viewed when new password is set

### Actual behaviour
I get CSP error

> Refused to connect to 'http://nextcloud.domain.org/lostpassword/set/DWXkLoVkZT1GL7uOcIRwH/testuser' because it violates the following Content Security Policy directive: "connect-src 'self' turn.domain.org:5349".

Please note that it says http, not httpS

---
even when turning off the talk app, it says:

> core.js?v=dd5a11f5-11:4 Refused to connect to 'http://nextcloud.domain.org/lostpassword/set/DWXkLoVkZT1GL7uOcIRwH/testuser' because it violates the following Content Security Policy directive: "connect-src 'self'".

Please note also here that it says http, not httpS

### Server configuration
Nextcloud 15.0.5 via docker (image: `nextcloud:latest`) with `mariadb:latest` (all pulled 3 days ago)

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

I am using a nginx reverse proxy on the debian host, there I did not change any CSP settings or somthing else.

**Comment by rullzer** [comment]
You probably need to specify the overwrite protocol in your config.php to https because you are behind a reverse proxy.

**Comment by bonanza123** [comment]
@rullzer thanks for your fast reply. My config.php says
>   'overwrite.cli.url' => 'https://nextcloud.domain.org',

**Comment by rullzer** [comment]
See https://github.com/nextcloud/server/blob/master/config/config.sample.php#L444-L451

**Comment by bonanza123** [comment]
@rullzer thanks, thats the trick!

**Comment by FunctionDJ** [comment]
I have exactly this issue, but never installed the Talk app. 

> See https://github.com/nextcloud/server/blob/master/config/config.sample.php#L444-L451

I tried both `true` and `false` for this setting but neither worked. And if it's supposed to fix the issue, how does that make sense? How is a supposedly bad CSP config related to rate limiting? I don't understand Q_Q
