### ISSUE TITLE
Style change of app properties needed

### ISSUE THREAD

**Issue by brunt82** [nextcloud/server#14735]
**Is your feature request related to a problem? Please describe.**
With the upgrade from NC 13 to NC15.0.5 I noticed the style change for the properties of the installed apps. The properties are all listed on the right side now.

Anyhow we have two apps, which are restricted to 24 LDAP groups currently. But the new style make it impossible to view the groups on one screen. 
Currently I need a look into the database to get information about group restrictions. :-(

**Describe the solution you'd like**
I don't know. Maybe any kind of possibility to see the whole list of groups to which the app is restricted to.

The following screenshot should help to understand my problem. Every rectangle inside of the text field seems to be a LDAP group:
![group_restriction](https://user-images.githubusercontent.com/26540488/54532174-6f67d880-4987-11e9-9f5a-8d31e14d634e.jpg)

**Comment by MorrisJobke** [comment]
cc @skjnldsv @juliushaertl @ChristophWurst

**Comment by ChristophWurst** [comment]
Either wrong data is passed to multiselect or the styling broke.

**Comment by skjnldsv** [comment]
@ChristophWurst we need to use the vue component multiselect instead of the original library.

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/14935
