### ISSUE TITLE
Cannot access file versions if comments-app is disabled.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#14741]
If I manually disable the comments-app, I can no longer acces the file-versions:

comments-app disabled:
<img width="289" alt="1" src="https://user-images.githubusercontent.com/42591237/54552574-adc5bd80-49b0-11e9-90f2-0784571479a2.PNG">

comments-app enabled:
<img width="282" alt="2" src="https://user-images.githubusercontent.com/42591237/54552593-be763380-49b0-11e9-919a-4b0687d5b54a.PNG">

I am running on Nextcloud snap 15.0.5 on Ubuntu 18.04 LTS.

**Comment by rullzer** [comment]
Yes this is a known issue. It is fixed on 15.0.6 which is scheduled for early April.
