### ISSUE TITLE
Expose (external) mount capabilities

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#14745]
It would be good if we would somehow expose mount capabilities.

With this I mean. If an external storage is mounted with session credentials. We should not allow link sharing. Or editing via Collabora/Only office. As it won't work since those methods won't have access to the credentials.

This to avoid people running into issues when they try to do this and then everything failing.

CC: @MorrisJobke @icewind1991

**Comment by skjnldsv** [comment]
Please update labels

**Comment by szaimen** [comment]
Do you still want to implement this?
