### ISSUE TITLE
Case in username is not used for device and session passwords which results in Webdav issues.

### ISSUE THREAD

**Issue by ArjenR** [nextcloud/server#14742]
### Steps to reproduce
1. Create a user with an uppercase letter in the username.
2. Create a device / session password for that user (notice the username to use is lowercase)
3. Use Nextcloudcmd, Cadaver or DavFS to access nxserver with the lowercase username and the session password. (Winscp does not have this issue)

### Expected behaviour
The client should either show the files, be able to access, upload sync etc,

### Actual behaviour
Nexcloudcmd will not sync. It will sometimes show an error 400 or 500. 403 when syncing to the server. But usually say OK but nothing is synced from the server. Syncing to the server will result in an error. Cadaver will give access error. Same for DavFS. Winscp works.

### Server configuration

**Operating system**:
The official docker nextcloud image. Debian 9.8
Unknown what the hoster uses

**Web server:**
Apache for docker. 
Hoster unknown.

**Database:**
Hoster Unknown
SQLite on docker.

**PHP version:**
Hoster unknown
Docker 7.2.16

**Nextcloud version:** (see Nextcloud admin page)
Docker: 15.0.5
Hoster: 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Docker: fresh install
Hoster: uknown, very probable also using docker.

**Where did you install Nextcloud from:**
docker hub
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Docker image: No errors have been found.
Hoster: No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Accessibility
1.1.0
Officieel
Activity
2.8.2
Officieel
Collaborative tags
1.5.0
Officieel
Comments
1.5.0
Officieel
Default encryption module
2.3.0
Officieel
Deleted files
1.5.0
Officieel
Federation
1.5.0
Officieel
File sharing
1.7.0
Officieel
First run wizard
2.4.0
Officieel
Gallery
18.2.0
Officieel
Log Reader
2.0.0
Officieel
Monitoring
1.5.0
Officieel
Nextcloud announcements
1.4.0
Officieel
Notifications
2.3.0
Officieel
Password policy
1.5.0
Officieel
PDF viewer
1.4.0
Officieel
Share by mail
1.5.0
Officieel
Support
1.0.0
Officieel
Text editor
2.7.0
Officieel
Theming
1.6.0
Officieel
Update notification
1.5.0
Officieel
Usage survey
1.3.0
Officieel
Versions
1.8.0
Officieel
Video player 
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => '...',
  'passwordsalt' => '...',
  'secret' => '...',
  'trusted_domains' =>
  array (
    0 => '10.1.1.100:8080',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'sqlite3',
  'version' => '15.0.5.3',
  'overwrite.cli.url' => 'http://10.1.1.100:8080',
  'installed' => true,
);
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
n/a

**Operating system:**
Windows 10, Alpine 3.7.0

#### Web server error log
<details>
<summary>Web server error log</summary>

10.1.1.59 - - [18/Mar/2019:21:34:12 +0000] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 2027 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:65.0) Gecko/20100101 Firefox/65.0",
10.1.1.59 - arjen [18/Mar/2019:21:37:57 +0000] "PROPFIND /remote.php/dav/files/arjen/ HTTP/1.1" 207 1362 "-" "Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)",
10.1.1.59 - arjen [18/Mar/2019:21:37:54 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 3173 "-" "Mozilla/5.0 (Windows) mirall/2.5.1final (build 20181204) (Nextcloud)",
127.0.0.1 - - [18/Mar/2019:21:37:50 +0000] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.25 (Debian) PHP/7.2.16 (internal dummy connection)"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

nothing in the log except for an earlier wrong password notice for admin.

</details>

#### Browser log 1
<details>
<summary>Console messages for sync from server.</summary>
C:\Program Files (x86)\Nextcloud>nextcloudcmd.exe H:\testmetnx http://10.1.1.100:8080
03-18 22:36:28:988 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_new
03-18 22:36:28:988 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_free
03-18 22:36:28:988 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
03-18 22:36:29:003 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
03-18 22:36:29:013 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_finish
03-18 22:36:29:018 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_cmd
03-18 22:36:29:018 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_set_alpn_protos
03-18 22:36:29:034 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
03-18 22:36:29:034 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_get0_alpn_selected
Please enter user name: arjen
Password for user arjen: 03-18 22:36:35:357 [ info nextcloud.sync.accessmanager ]:      2 "" "http://10.1.1.100:8080/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "74da0b2e-e36e-4f1d-876f-bd7a947948c2"
03-18 22:36:35:387 [ info nextcloud.sync.networkjob ]:  OCC::JsonApiJob created for "http://10.1.1.100" + "ocs/v1.php/cloud/capabilities" ""
03-18 22:36:38:017 [ info nextcloud.sync.networkjob.jsonapi ]:  JsonApiJob of QUrl("http://10.1.1.100:8080/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
03-18 22:36:38:027 [ debug default ]    [ main::::operator() ]: Server capabilities QJsonObject({"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"bruteforce":{"delay":0},"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0"},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"default_permissions":31,"federation":{"expire_date":{"enabled":true},"incoming":true,"outgoing":true},"group":{"enabled":true,"expire_date":{"enabled":true}},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"multiple_links":true,"password":{"enforced":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"sharebymail":{"enabled":true,"expire_date":{"enabled":true},"password":{"enabled":true},"upload_files_drop":{"enabled":true}},"user":{"expire_date":{"enabled":true},"send_mail":false}},"notifications":{"admin-notifications":["ocs","cli"],"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings"],"push":["devices","object-data"]},"ocm":{"apiVersion":"1.0-proposal1","enabled":true,"endPoint":"http://10.1.1.100:8080/ocm","resourceTypes":[{"name":"file","protocols":{"webdav":"/public.php/webdav/"},"shareTypes":["user","group"]}]},"password_policy":{"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"minLength":8},"theming":{"background":"http://10.1.1.100:8080/core/img/background.png?v=0","background-default":true,"background-plain":false,"color":"#0082c9","color-element":"#0082c9","color-text":"#ffffff","logo":"http://10.1.1.100:8080/core/img/logo/logo.svg?v=0","name":"Nextcloud","slogan":"a safe home for all your data","url":"https://nextcloud.com"}})
03-18 22:36:38:104 [ info nextcloud.sync.database ]:    Detected filesystem "NTFS" for "H:/testmetnx/._sync_fb361d7fc09e.db"
03-18 22:36:38:118 [ info nextcloud.sync.engine ]:      There are 237173030912 bytes available at "H:/testmetnx/"
03-18 22:36:38:118 [ info nextcloud.sync.engine ]:      New sync (no sync journal exists)
03-18 22:36:38:118 [ info nextcloud.sync.engine ]:      "Using Qt 5.11.1 SSL library OpenSSL 1.0.1h 5 Jun 2014 on Windows 10 (10.0)"
03-18 22:36:38:148 [ info nextcloud.sync.database ]:    sqlite3 version "3.24.0"
03-18 22:36:38:148 [ info nextcloud.sync.database ]:    sqlite3 journal_mode= "wal"
03-18 22:36:38:182 [ info nextcloud.sync.database ]:    possibleUpgradeFromMirall_1_5 detected!
03-18 22:36:38:198 [ info nextcloud.sync.database ]:    Forcing remote re-discovery by deleting folder Etags
03-18 22:36:38:207 [ info nextcloud.sync.engine ]:      NOT Using Selective Sync
03-18 22:36:38:212 [ info nextcloud.sync.engine ]:      #### Discovery start ####################################################
03-18 22:36:38:212 [ info nextcloud.sync.engine ]:      Server ""
03-18 22:36:38:212 [ info sync.csync.csync ]:   ## Starting local discovery ##
03-18 22:36:38:212 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db excluded  (1)
03-18 22:36:38:229 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db-shm excluded  (1)
03-18 22:36:38:229 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db-wal excluded  (1)
03-18 22:36:38:240 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for H:/testmetnx with read_from_db 0
03-18 22:36:38:249 [ info sync.csync.csync ]:   Update detection for local replica took 0.027 seconds walking 0 files
03-18 22:36:38:254 [ info sync.csync.csync ]:   ## Starting remote discovery ##
03-18 22:36:38:254 [ info nextcloud.sync.accessmanager ]:       6 "PROPFIND" "http://10.1.1.100:8080/remote.php/dav/files/arjen/" has X-Request-ID "7fab54e6-caab-4f80-b0d0-190e4ce06e73"
03-18 22:36:38:259 [ info nextcloud.sync.networkjob ]:  OCC::LsColJob created for "http://10.1.1.100" + "" "OCC::DiscoverySingleDirectoryJob"
03-18 22:36:38:520 [ info nextcloud.sync.networkjob.lscol ]:    LSCOL of QUrl("http://10.1.1.100:8080/remote.php/dav/files/arjen/") FINISHED WITH STATUS "OK"
03-18 22:36:38:524 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for  with read_from_db 0
03-18 22:36:38:524 [ info sync.csync.csync ]:   Update detection for remote replica took 0.279 seconds walking 0 files
03-18 22:36:38:540 [ info nextcloud.sync.engine ]:      #### Discovery end ####################################################  328 ms
03-18 22:36:38:540 [ info sync.csync.csync ]:   Reconciliation for local replica took  0 seconds visiting  0  files.
03-18 22:36:38:550 [ info sync.csync.csync ]:   Reconciliation for remote replica took  0 seconds visiting  0  files.
03-18 22:36:38:555 [ info nextcloud.sync.engine ]:      #### Reconcile end ####################################################  344 ms
03-18 22:36:38:555 [ info nextcloud.sync.engine ]:      Permissions of the root folder:  ""
03-18 22:36:38:555 [ info nextcloud.sync.engine ]:      #### Post-Reconcile end ####################################################  356 ms
03-18 22:36:38:571 [ info nextcloud.sync.database ]:    Closing DB "H:/testmetnx/._sync_fb361d7fc09e.db"
03-18 22:36:38:585 [ info nextcloud.sync.engine ]:      CSync run took  386 ms
03-18 22:36:38:608 [ info nextcloud.sync.database ]:    Closing DB "H:/testmetnx/._sync_fb361d7fc09e.db"

C:\Program Files (x86)\Nextcloud>nextcloudcmd.exe H:\testmetnx http://10.1.1.100:8080
03-18 22:41:22:651 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_new
03-18 22:41:22:657 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_free
03-18 22:41:22:657 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
03-18 22:41:22:657 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
03-18 22:41:22:657 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_finish
03-18 22:41:22:677 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_cmd
03-18 22:41:22:683 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_set_alpn_protos
03-18 22:41:22:688 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
03-18 22:41:22:688 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_get0_alpn_selected
Please enter user name: arjen
Password for user arjen: 03-18 22:41:30:758 [ info nextcloud.sync.accessmanager ]:      2 "" "http://10.1.1.100:8080/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "bff6f050-73ff-45fc-b05d-1de161c52aee"
03-18 22:41:30:773 [ info nextcloud.sync.networkjob ]:  OCC::JsonApiJob created for "http://10.1.1.100" + "ocs/v1.php/cloud/capabilities" ""
03-18 22:41:33:070 [ info nextcloud.sync.networkjob.jsonapi ]:  JsonApiJob of QUrl("http://10.1.1.100:8080/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
03-18 22:41:33:079 [ debug default ]    [ main::::operator() ]: Server capabilities QJsonObject({"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"bruteforce":{"delay":0},"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0"},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"default_permissions":31,"federation":{"expire_date":{"enabled":true},"incoming":true,"outgoing":true},"group":{"enabled":true,"expire_date":{"enabled":true}},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"multiple_links":true,"password":{"enforced":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"sharebymail":{"enabled":true,"expire_date":{"enabled":true},"password":{"enabled":true},"upload_files_drop":{"enabled":true}},"user":{"expire_date":{"enabled":true},"send_mail":false}},"notifications":{"admin-notifications":["ocs","cli"],"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings"],"push":["devices","object-data"]},"ocm":{"apiVersion":"1.0-proposal1","enabled":true,"endPoint":"http://10.1.1.100:8080/ocm","resourceTypes":[{"name":"file","protocols":{"webdav":"/public.php/webdav/"},"shareTypes":["user","group"]}]},"password_policy":{"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"minLength":8},"theming":{"background":"http://10.1.1.100:8080/core/img/background.png?v=0","background-default":true,"background-plain":false,"color":"#0082c9","color-element":"#0082c9","color-text":"#ffffff","logo":"http://10.1.1.100:8080/core/img/logo/logo.svg?v=0","name":"Nextcloud","slogan":"a safe home for all your data","url":"https://nextcloud.com"}})
03-18 22:41:33:191 [ info nextcloud.sync.database ]:    Detected filesystem "NTFS" for "H:/testmetnx/._sync_fb361d7fc09e.db"
03-18 22:41:33:205 [ info nextcloud.sync.engine ]:      There are 237172891648 bytes available at "H:/testmetnx/"
03-18 22:41:33:205 [ info nextcloud.sync.engine ]:      New sync (no sync journal exists)
03-18 22:41:33:205 [ info nextcloud.sync.engine ]:      "Using Qt 5.11.1 SSL library OpenSSL 1.0.1h 5 Jun 2014 on Windows 10 (10.0)"
03-18 22:41:33:221 [ info nextcloud.sync.database ]:    sqlite3 version "3.24.0"
03-18 22:41:33:231 [ info nextcloud.sync.database ]:    sqlite3 journal_mode= "wal"
03-18 22:41:33:270 [ info nextcloud.sync.database ]:    possibleUpgradeFromMirall_1_5 detected!
03-18 22:41:33:281 [ info nextcloud.sync.database ]:    Forcing remote re-discovery by deleting folder Etags
03-18 22:41:33:297 [ info nextcloud.sync.engine ]:      NOT Using Selective Sync
03-18 22:41:33:306 [ info nextcloud.sync.engine ]:      #### Discovery start ####################################################
03-18 22:41:33:311 [ info nextcloud.sync.engine ]:      Server ""
03-18 22:41:33:311 [ info sync.csync.csync ]:   ## Starting local discovery ##
03-18 22:41:33:311 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db excluded  (1)
03-18 22:41:33:311 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db-shm excluded  (1)
03-18 22:41:33:341 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db-wal excluded  (1)
03-18 22:41:33:347 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for H:/testmetnx with read_from_db 0
03-18 22:41:33:356 [ info sync.csync.csync ]:   Update detection for local replica took 0.038 seconds walking 0 files
03-18 22:41:33:361 [ info sync.csync.csync ]:   ## Starting remote discovery ##
03-18 22:41:33:361 [ info nextcloud.sync.accessmanager ]:       6 "PROPFIND" "http://10.1.1.100:8080/remote.php/dav/files/arjen/" has X-Request-ID "6f14e532-11d5-4602-9872-d9504ea6d6dc"
03-18 22:41:33:374 [ info nextcloud.sync.networkjob ]:  OCC::LsColJob created for "http://10.1.1.100" + "" "OCC::DiscoverySingleDirectoryJob"
03-18 22:41:33:612 [ info nextcloud.sync.networkjob.lscol ]:    LSCOL of QUrl("http://10.1.1.100:8080/remote.php/dav/files/arjen/") FINISHED WITH STATUS "OK"
03-18 22:41:33:612 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for  with read_from_db 0
03-18 22:41:33:612 [ info sync.csync.csync ]:   Update detection for remote replica took 0.261 seconds walking 0 files
03-18 22:41:33:633 [ info nextcloud.sync.engine ]:      #### Discovery end ####################################################  325 ms
03-18 22:41:33:637 [ info sync.csync.csync ]:   Reconciliation for local replica took  0 seconds visiting  0  files.
03-18 22:41:33:642 [ info sync.csync.csync ]:   Reconciliation for remote replica took  0 seconds visiting  0  files.
03-18 22:41:33:642 [ info nextcloud.sync.engine ]:      #### Reconcile end ####################################################  343 ms
03-18 22:41:33:658 [ info nextcloud.sync.engine ]:      Permissions of the root folder:  ""
03-18 22:41:33:658 [ info nextcloud.sync.engine ]:      #### Post-Reconcile end ####################################################  356 ms
03-18 22:41:33:672 [ info nextcloud.sync.database ]:    Closing DB "H:/testmetnx/._sync_fb361d7fc09e.db"
03-18 22:41:33:688 [ info nextcloud.sync.engine ]:      CSync run took  382 ms
03-18 22:41:33:688 [ info nextcloud.sync.database ]:    Closing DB "H:/testmetnx/._sync_fb361d7fc09e.db"

C:\Program Files (x86)\Nextcloud>
</details>
#### Browser log 1
<details>
<summary>Console messages for sync to server.</summary>
C:\Program Files (x86)\Nextcloud>nextcloudcmd.exe H:\testmetnx http://10.1.1.100:8080
03-18 22:47:07:766 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_new
03-18 22:47:07:766 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_free
03-18 22:47:07:766 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_set_ssl_ctx
03-18 22:47:07:791 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_set_flags
03-18 22:47:07:797 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_CTX_finish
03-18 22:47:07:803 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CONF_cmd
03-18 22:47:07:803 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_set_alpn_protos
03-18 22:47:07:811 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_CTX_set_alpn_select_cb
03-18 22:47:07:816 [ warning qt.network.ssl ]:  QSslSocket: cannot resolve SSL_get0_alpn_selected
Please enter user name: arjen
Password for user arjen: 03-18 22:47:19:814 [ info nextcloud.sync.accessmanager ]:      2 "" "http://10.1.1.100:8080/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "556f4fb7-de0f-4766-8251-3605e507b230"
03-18 22:47:19:830 [ info nextcloud.sync.networkjob ]:  OCC::JsonApiJob created for "http://10.1.1.100" + "ocs/v1.php/cloud/capabilities" ""
03-18 22:47:22:076 [ info nextcloud.sync.networkjob.jsonapi ]:  JsonApiJob of QUrl("http://10.1.1.100:8080/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
03-18 22:47:22:076 [ debug default ]    [ main::::operator() ]: Server capabilities QJsonObject({"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"bruteforce":{"delay":0},"core":{"pollinterval":60,"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0"},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"default_permissions":31,"federation":{"expire_date":{"enabled":true},"incoming":true,"outgoing":true},"group":{"enabled":true,"expire_date":{"enabled":true}},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"multiple_links":true,"password":{"enforced":false},"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"sharebymail":{"enabled":true,"expire_date":{"enabled":true},"password":{"enabled":true},"upload_files_drop":{"enabled":true}},"user":{"expire_date":{"enabled":true},"send_mail":false}},"notifications":{"admin-notifications":["ocs","cli"],"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings"],"push":["devices","object-data"]},"ocm":{"apiVersion":"1.0-proposal1","enabled":true,"endPoint":"http://10.1.1.100:8080/ocm","resourceTypes":[{"name":"file","protocols":{"webdav":"/public.php/webdav/"},"shareTypes":["user","group"]}]},"password_policy":{"enforceNonCommonPassword":true,"enforceNumericCharacters":false,"enforceSpecialCharacters":false,"enforceUpperLowerCase":false,"minLength":8},"theming":{"background":"http://10.1.1.100:8080/core/img/background.png?v=0","background-default":true,"background-plain":false,"color":"#0082c9","color-element":"#0082c9","color-text":"#ffffff","logo":"http://10.1.1.100:8080/core/img/logo/logo.svg?v=0","name":"Nextcloud","slogan":"a safe home for all your data","url":"https://nextcloud.com"}})
03-18 22:47:22:166 [ info nextcloud.sync.database ]:    Detected filesystem "NTFS" for "H:/testmetnx/._sync_fb361d7fc09e.db"
03-18 22:47:22:182 [ info nextcloud.sync.database ]:    sqlite3 version "3.24.0"
03-18 22:47:22:182 [ info nextcloud.sync.database ]:    sqlite3 journal_mode= "wal"
03-18 22:47:22:182 [ info nextcloud.sync.engine ]:      There are 237172682752 bytes available at "H:/testmetnx/"
03-18 22:47:22:201 [ info nextcloud.sync.engine ]:      Sync with existing sync journal
03-18 22:47:22:201 [ info nextcloud.sync.engine ]:      "Using Qt 5.11.1 SSL library OpenSSL 1.0.1h 5 Jun 2014 on Windows 10 (10.0)"
03-18 22:47:22:201 [ info nextcloud.sync.engine ]:      NOT Using Selective Sync
03-18 22:47:22:214 [ info nextcloud.sync.engine ]:      #### Discovery start ####################################################
03-18 22:47:22:219 [ info nextcloud.sync.engine ]:      Server ""
03-18 22:47:22:228 [ info sync.csync.csync ]:   ## Starting local discovery ##
03-18 22:47:22:231 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db excluded  (1)
03-18 22:47:22:233 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db-shm excluded  (1)
03-18 22:47:22:233 [ info nextcloud.sync.csync.updater ]:       ._sync_fb361d7fc09e.db-wal excluded  (1)
03-18 22:47:22:233 [ info nextcloud.sync.csync.updater ]:       Checking for rename based on inode # 444187
03-18 22:47:22:233 [ info nextcloud.sync.csync.updater ]:       file: TEST new foldrr, instruction: INSTRUCTION_NEW <<=
03-18 22:47:22:255 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for H:/testmetnx/TEST new foldrr with read_from_db 0
03-18 22:47:22:262 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for H:/testmetnx with read_from_db 0
03-18 22:47:22:267 [ info sync.csync.csync ]:   Update detection for local replica took 0.039 seconds walking 1 files
03-18 22:47:22:267 [ info sync.csync.csync ]:   ## Starting remote discovery ##
03-18 22:47:22:267 [ info nextcloud.sync.accessmanager ]:       6 "PROPFIND" "http://10.1.1.100:8080/remote.php/dav/files/arjen/" has X-Request-ID "e0441bac-c272-4ac1-be46-13d6ad0c1b1b"
03-18 22:47:22:288 [ info nextcloud.sync.networkjob ]:  OCC::LsColJob created for "http://10.1.1.100" + "" "OCC::DiscoverySingleDirectoryJob"
03-18 22:47:22:509 [ info nextcloud.sync.networkjob.lscol ]:    LSCOL of QUrl("http://10.1.1.100:8080/remote.php/dav/files/arjen/") FINISHED WITH STATUS "OK"
03-18 22:47:22:514 [ info nextcloud.sync.csync.updater ]:        <= Closing walk for  with read_from_db 0
03-18 22:47:22:514 [ info sync.csync.csync ]:   Update detection for remote replica took 0.251 seconds walking 0 files
03-18 22:47:22:514 [ info nextcloud.sync.engine ]:      #### Discovery end ####################################################  313 ms
03-18 22:47:22:532 [ info nextcloud.sync.csync.reconciler ]:    INSTRUCTION_NEW                client dir:  TEST new foldrr
03-18 22:47:22:541 [ info sync.csync.csync ]:   Reconciliation for local replica took  0.005 seconds visiting  1  files.
03-18 22:47:22:546 [ info sync.csync.csync ]:   Reconciliation for remote replica took  0 seconds visiting  0  files.
03-18 22:47:22:546 [ info nextcloud.sync.engine ]:      #### Reconcile end ####################################################  341 ms
03-18 22:47:22:562 [ info nextcloud.sync.engine ]:      blacklist entry for  "TEST new foldrr"  has expired!
03-18 22:47:22:562 [ info nextcloud.sync.engine ]:      Permissions of the root folder:  ""
03-18 22:47:22:572 [ info nextcloud.sync.engine ]:      #### Post-Reconcile end ####################################################  358 ms
03-18 22:47:22:582 [ info nextcloud.sync.propagator ]:  Starting INSTRUCTION_NEW propagation of "TEST new foldrr" by OCC::PropagateRemoteMkdir(0x115f8f88040)
03-18 22:47:22:592 [ info nextcloud.sync.accessmanager ]:       6 "MKCOL" "http://10.1.1.100:8080/remote.php/dav/files/arjen/TEST new foldrr" has X-Request-ID "08be166b-3768-4c25-92aa-9e6970a3591f"
03-18 22:47:22:592 [ info nextcloud.sync.networkjob ]:  OCC::MkColJob created for "http://10.1.1.100" + "/TEST new foldrr" "OCC::PropagateRemoteMkdir"
03-18 22:47:22:772 [ warning nextcloud.sync.networkjob ]:       QNetworkReply::NetworkError(ContentAccessDenied) "Server replied \"403 Forbidden\" to \"MKCOL http://10.1.1.100:8080/remote.php/dav/files/arjen/TEST new foldrr\"" QVariant(int, 403)
03-18 22:47:22:783 [ info nextcloud.sync.networkjob.mkcol ]:    MKCOL of QUrl("http://10.1.1.100:8080/remote.php/dav/files/arjen/TEST new foldrr") FINISHED WITH STATUS "ContentAccessDenied Server replied \"403 Forbidden\" to \"MKCOL http://10.1.1.100:8080/remote.php/dav/files/arjen/TEST new foldrr\""
03-18 22:47:22:799 [ warning nextcloud.sync.propagator ]:       Probably firewall error:  403 , blacklisting up to 1h only
03-18 22:47:22:799 [ info nextcloud.sync.database ]:    Setting blacklist entry for  "TEST new foldrr" 2 "Server replied \"403 Forbidden\" to \"MKCOL http://10.1.1.100:8080/remote.php/dav/files/arjen/TEST new foldrr\"" 1552945642 125 1552945572 "" "" 0
03-18 22:47:22:814 [ info nextcloud.sync.propagator ]:  blacklisting  "TEST new foldrr"  for  125 , retry count  2
03-18 22:47:22:832 [ warning nextcloud.sync.propagator ]:       Could not complete propagation of "TEST new foldrr" by OCC::PropagateRemoteMkdir(0x115f8f88040) with status 9 and error: "Server replied \"403 Forbidden\" to \"MKCOL http://10.1.1.100:8080/remote.php/dav/files/arjen/TEST new foldrr\""
03-18 22:47:22:861 [ info nextcloud.sync.database ]:    Closing DB "H:/testmetnx/._sync_fb361d7fc09e.db"
03-18 22:47:22:876 [ info nextcloud.sync.engine ]:      CSync run took  662 ms
03-18 22:47:22:876 [ info nextcloud.sync.database ]:    Closing DB "H:/testmetnx/._sync_fb361d7fc09e.db"

C:\Program Files (x86)\Nextcloud>
</details>

**Comment by skjnldsv** [comment]
iirc we fixed user casing in recent versions
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
