### ISSUE TITLE
Add a comment (markdown formated) to shared files that is shown when viewed in browser

### ISSUE THREAD

**Issue by small1** [nextcloud/server#14746]
**Description**
Add a comment/text (markdown formated?) field to shared links.

When you share a link you can always write what you want to say in a post or an email. But sometimes when you spread a link to a file or folder you might want to add a small text what the doc contains or why it was shared to the recipient(s)

So when you only provide the link it is clear why/what a file/folder is shared.

See attached image

![comments_for_shares_concept](https://user-images.githubusercontent.com/317830/54602265-7c490280-4a41-11e9-9919-6aa142b179ea.png)

**Comment by MorrisJobke** [comment]
There is a "set note" feature available for link and email shares. Could you try this? This adds them to the share page as well.

Maybe that's what you are looking for.

**Comment by MorrisJobke** [comment]
![Bildschirmfoto 2019-03-25 um 10 00 34](https://user-images.githubusercontent.com/245432/54907009-da179780-4ee4-11e9-9c3e-372e050d2e68.png)

**Comment by small1** [comment]
That note is a bit invisible for an end user that has zero computer knowledge.  And if it is a shared link and not sent by email the end user would not know that it is there.

My proposal is that it should be shown together with the preview somewhere. Down with the download link perhaps.  Or at least a bit more visible.

**Comment by MorrisJobke** [comment]
> My proposal is that it should be shown together with the preview somewhere. Down with the download link perhaps. Or at least a bit more visible.

This was decided like that by the designers team @nextcloud/designers.

In the future there is also the sidebar planned to be added to this view and there you can embed the comments for better visibility. See https://github.com/nextcloud/server/issues/10931 - it's planned for 17 and might help with your situation.

**Comment by jancborchardt** [comment]
Yep, the note should go into the sidebar, just like future commenting ability for guests etc.
