### ISSUE TITLE
WebDav access with a new Konica copy machine

### ISSUE THREAD

**Issue by jemandanderes** [nextcloud/server#14757]
Hi,

i'm having problems to get a Konica C3351 copy machine to scan with WebDAV protocol. The machine can scan to other webdavs just fine but when i scan to nextcloud it reports "network not available" or a code 1018 (forbidden) and nextcloud logs the following message 

OPTIONS /remote.php/dav/files/USERNAME/**_Connection%20Check_** HTTP/1.1 403

a machine that's one generation older does just fine. since the server uses ssl i had to setup my own webdav without ssl (not nextcloud though) to use wireshark to check what the difference between both machines is. looks like the older model just goes straight to work while the new model does a "connection check" first. it does a complete dns query/handshake/connection check cycle before it does what the older model does.

the server is running nextcloud 14 and sabredav

any ideas how to solve this or where to ask for help? 

Since i'm not allowed to share the servers logs i can only show what a scan on my NAS WebDAV does where the nextcloud server fails. The dns query at the end is where the real scan like the older model does begins.
![naswebdav](https://user-images.githubusercontent.com/48751010/54671916-39e1fd00-4af7-11e9-91f4-cafe242ff749.jpg)

**Comment by skjnldsv** [comment]
> any ideas how to solve this or where to ask for help?

Let's be honest, your use case is very unusual :see_no_evil: 
Any updates since? :)
