### ISSUE TITLE
Index name "comments"."comments_topmost_parent_id_idx" is too long.

### ISSUE THREAD

**Issue by barnettZQG** [nextcloud/server#14756]
server version: 16.0.0
mysql version: 5.7.23
create admin user failure. 
![image](https://user-images.githubusercontent.com/18493394/54670752-526e0980-4b2f-11e9-902e-43ba16f4fbfa.png)

**Comment by ChristophWurst** [comment]
Please file a proper bug report using the template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md
