### ISSUE TITLE
Popup labels in security settings don't disappear

### ISSUE THREAD

**Issue by TobiasMie** [nextcloud/server#14752]
If I revoke browser sessions the 'device settings' labels don't disappear after I click the 'revoke session' button.

![Screenshot_20190319_212241](https://user-images.githubusercontent.com/19272532/54639867-ae348600-4a8e-11e9-8b46-8c6af81f7d3a.png)

This happens in Firefox 65 but not in Chromium 73.

### Steps to reproduce
1. revoke sessions

### Expected behaviour
The popup should disappear

### Actual behaviour
It stays and overlap the other buttons which makes it impossible to click them

### Server configuration

**Operating system**: Raspbian

**Web server:** Apache2

**Database:** Mariadb

**PHP version:** 7.0

**Nextcloud version:** (see Nextcloud admin page)15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** upgraded from Nextcloud 14

**Where did you install Nextcloud from:** installation script

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
- accessibility: 1.1.0

- activity: 2.8.2

- bookmarks: 0.16.2

- bruteforcesettings: 1.3.0

- calendar: 1.6.4

- checksum: 0.4.2

- cloud_federation_api: 0.1.0

- cms_pico: 0.9.7

- comments: 1.5.0

- contacts: 3.0.5

- cospend: 0.0.6

- dav: 1.8.1

- deck: 0.5.2

- end_to_end_encryption: 1.1.0

- external: 3.2.0

- federatedfilesharing: 1.5.0

- federation: 1.5.0

- files: 1.10.0

- files_downloadactivity: 1.4.0

- files_markdown: 2.0.5

- files_pdfviewer: 1.4.0

- files_retention: 1.4.2

- files_rightclick: 0.11.1

- files_sharing: 1.7.0

- files_texteditor: 2.7.0

- files_trashbin: 1.5.0

- files_versions: 1.8.0

- files_videoplayer: 1.4.0

- firstrunwizard: 2.4.0

- gallery: 18.2.0

- logreader: 2.0.0

- lookup_server_connector: 1.3.0

- mail: 0.11.0

- metadata: 0.9.0

- news: 13.0.3

- nextcloud_announcements: 1.4.0

- notifications: 2.3.0

- oauth2: 1.3.0

- password_policy: 1.5.0

- phonetrack: 0.4.4

- polls: 0.10.2

- previewgenerator: 2.1.0

- provisioning_api: 1.5.0

- quota_warning: 1.4.0

- ransomware_protection: 1.3.0

- serverinfo: 1.5.0

- sharebymail: 1.5.0

- sharerenamer: 2.5.0

- socialsharing_diaspora: 1.0.4

- socialsharing_email: 1.0.5

- spreed: 5.0.2

- support: 1.0.0

- systemtags: 1.5.0

- tasks: 0.9.8

- theming: 1.6.0

- twofactor_backupcodes: 1.4.1

- twofactor_nextcloud_notification: 1.0.3

- twofactor_totp: 2.1.2

- twofactor_u2f: 2.1.2

- unsplash: 1.1.3

- updatenotification: 1.5.0

- workflowengine: 1.5.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{

    "system": {

        "passwordsalt": "***REMOVED SENSITIVE VALUE***",

        "secret": "***REMOVED SENSITIVE VALUE***",

        "trusted_domains": [

            "localhost",

            "192.168.178.33",

        ],

        "datadirectory": "***REMOVED SENSITIVE VALUE***",

        "dbtype": "mysql",

        "version": "15.0.5.3",

        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",

        "dbname": "***REMOVED SENSITIVE VALUE***",

        "dbhost": "***REMOVED SENSITIVE VALUE***",

        "dbport": "",

        "dbtableprefix": "oc_",

        "mysql.utf8mb4": true,

        "dbuser": "***REMOVED SENSITIVE VALUE***",

        "dbpassword": "***REMOVED SENSITIVE VALUE***",

        "installed": true,

        "instanceid": "***REMOVED SENSITIVE VALUE***",

        "mail_smtpmode": "smtp",

        "mail_smtpauthtype": "LOGIN",

        "mail_from_address": "***REMOVED SENSITIVE VALUE***",

        "mail_domain": "***REMOVED SENSITIVE VALUE***",

        "overwriteprotocol": "https",

        "maintenance": false,

        "mail_smtpauth": 1,

        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",

        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",

        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",

        "loglevel": 2,

        "log_type": "file",

        "logtimezone": "Europe\/Berlin",

        "log_rotate_size": 104857600,

        "theme": "",

        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",

        "default_language": "de_DE",

        "appcodechecker": true,

        "updatechecker": true,

        "has_internet_connection": true,

        "check_for_working_wellknown_setup": true,

        "check_for_working_htaccess": true,

        "check_data_directory_permissions": true,

        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",

        "enabledPreviewProviders": [

            "OC\\Preview\\PNG",

            "OC\\Preview\\JPEG",

            "OC\\Preview\\GIF",

            "OC\\Preview\\BMP",

            "OC\\Preview\\XBitmap",

            "OC\\Preview\\MP3",

            "OC\\Preview\\TXT",

            "OC\\Preview\\MarkDown",

            "OC\\Preview\\Movie",

            "OC\\Preview\\PDF",

            "OC\\Preview\\SVG"

        ],

        "preview_office_cl_parameters": " --headless --nologo --nofirststartwizard --invisible 
--norestore --convert-to png --outdir ",
        "memcache.local": "\\OC\\Memcache\\Redis",

        "memcache.locking": "\\OC\\Memcache\\Redis",

        "filelocking.enabled": "true",

        "redis": {

            "host": "***REMOVED SENSITIVE VALUE***",

            "port": 0,

            "timeout": 0

        },

        "mail_smtpsecure": "tls",

        "session_keepalive": true,

        "session_lifetime": 86400,

        "htaccess.RewriteBase": "\/",

        "updater.release.channel": "stable"

    }

}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 65

**Operating system:** Kubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>
no regarding log
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no regarding log
</details>

#### Browser log
<details>
<summary>Browser log</summary>
no log
</details>

**Comment by MorrisJobke** [comment]
cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
It's been migrated to vue for 16, right?
@ChristophWurst @rullzer ?

**Comment by ChristophWurst** [comment]
Yes, this was rewritten in Vue for 16.

**Comment by skjnldsv** [comment]
So I'd guess it's fixed in 16 :)

**Comment by MorrisJobke** [comment]
> So I'd guess it's fixed in 16 :)

That explain why I couldn't reproduce in master 🙈

**Comment by MorrisJobke** [comment]
Let's close this then as a won't fix for now. If this is really a dealbreaker we can look into it again.
