### ISSUE TITLE
Disabled addressbooks are listed by CardDAV clients

### ISSUE THREAD

**Issue by marcbp** [nextcloud/server#14754]
### Steps to reproduce
1. Create two addressbooks
2. Disable one of them
3. Query the CardDAV server to get the list of addressbooks

### Expected behaviour
The list of available addressbooks should only returns enabled ones. We expect CardDAV clients to ignore contacts from disabled addressbooks.

### Actual behaviour
All the addressbooks are returned, and CardDAV clients include contacts from disabled addressbooks as if it was enabled.

I can report here my full server configuration if necessary.

**Comment by skjnldsv** [comment]
Hey! Yes, they're disabled, but not hidden.
We won't add this as this would defeat the purpose of it. If you want to ignore the sync with your carddav manager (davx... etc), you can filter out the ones you don't want :)
