### ISSUE TITLE
Search on web vs Android

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#14755]
On web something like
http://localhost/nc/index.php/core/search?query=test&inApps=files&page=1&size=30
is used.
I do not know the internal, but
- it is amazing fast
- supports pagination
- easy to use, only use parameter

On android we use webdav search, which
- is rather complex
- seems to be very slow

Can we also expose the endpoint used by web?

**Comment by tobiasKaminsky** [comment]
I am fine with both ways, as long as they are fast enough ;-)

**Comment by skjnldsv** [comment]
@tobiasKaminsky since you created multiple issues about webdav SEARCH, could you create a meta issue to cleanup this kind of ticket and basically summarize things? :)
- depth support
- fast endpoint
- pagination
- another-issue-you-created-but-I-forgot-:see_no_evil:

**Comment by tobiasKaminsky** [comment]
As far as I remember all of them are independant and should/can be handled individually.
Having another issue will not benefit, I fear.

**Comment by skjnldsv** [comment]
@tobiasKaminsky a project then ?
So we can keep track of what we need to do to deprecate the legacy search endpoint?

**Comment by tobiasKaminsky** [comment]
> So we can keep track of what we need to do to deprecate the legacy search endpoint?

This is beyond my knowledge of the server. 
If you want to do it, feel free.

But as said again, if we tackle the issues one by one it is more than enough.
Deprecating anything is not what I want / need.

**Comment by skjnldsv** [comment]
@tobiasKaminsky closing in favour of unified search?
