### ISSUE TITLE
Gmail requires to enable less secure app access to use as smtp

### ISSUE THREAD

**Issue by Tahvok** [nextcloud/server#14763]
### Steps to reproduce
1. make sure less secure app access on your gmail account is **not** active: https://myaccount.google.com/lesssecureapps
2. configure smtp in nextcloud with your gmail account

### Expected behaviour
nextcloud should be able to use gmail smtp to send email and you should not be required to enable less secure apps access in gmail to configure smtp.

### Actual behaviour
an error is received that authentication is incorrect

### Server configuration

**Operating system**:
docker fpm image

**Web server:**
docker fpm

**Database:**
mariadb

**PHP version:**
7.2.16

**Nextcloud version:** (see Nextcloud admin page)
15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 14.0.3

**Where did you install Nextcloud from:**
official docker fpm image

**Signing status:**
<details>
<summary>No errors have been found.</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>default</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "domain.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**
Firefox

**Operating system:**
Archlinux

#### Web server error log
<details>
<summary></summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Works here just fine with this:

```

$CONFIG = [
	'mail_smtpmode' => 'smtp',
	'mail_smtphost' => 'smtp.gmail.com',
	'mail_smtpport' => 587,
	'mail_smtpsecure' => 'tls',
	'mail_smtpauth' => true,
	'mail_smtpauthtype' => 'LOGIN',
	'mail_smtpname' => 'USERNAME@gmail.com',
	'mail_smtppassword' => 'PASSWORD',
];
```

For further setup related questions I would ask you to open threads in the forum: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Tahvok** [comment]
Have you checked that your less secure app access is **not** active?
I've tried it from multiple gmail accounts, same problem on all of them.

**Comment by dyfet** [comment]
I went thru this, had the long authentication error, hit the url described at the top to allow less secure apps, and it then worked.  This needs to be described somewhere in the settings page.  There may also be another way to do it requesting device specific passwords, though I wonder if this will also make kmail finally happy.

**Comment by nlitz88** [comment]
I have been trying to set this up but can't seem to find a way to enable "less secure apps" anymore--I just get hit with the authentication error like described above. It looks like Google did away with allowing users to enable less secure apps [here](https://support.google.com/accounts/answer/6010255?hl=en). Is it even possible to use the gmail SMTP server anymore without this capability?
