### ISSUE TITLE
AD logins hang on login NC15.0.5

### ISSUE THREAD

**Issue by whositwhatnow** [nextcloud/server#14765]
Hello,

I have a fresh install on NC 15.0.5. Local accounts work fine, AD setup is correct and working.  It pulls groups and users.  When i got to login with the users nextclound hangs and just shows logging in with spinning circle.  Logs are showing:

OC\ServerNotAvailableException: Lost connection to LDAP server.  which doesn't make sense because it can access AD.

[index] Error: OC\ServerNotAvailableException: Lost connection to LDAP server. at <<closure>>

 0. /var/www/html/apps/user_ldap/lib/LDAP.php line 377
    processLDAPError(null)
 1. /var/www/html/apps/user_ldap/lib/LDAP.php line 300
    postFunctionCall()
 2. /var/www/html/apps/user_ldap/lib/LDAP.php line 203
    invokeLDAPMethod("*** sensitive parameters replaced ***")
 3. <<closure>>
    search("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /var/www/html/apps/user_ldap/lib/Access.php line 1076
    call_user_func_array([OCA\User_LDAP\L ... "], ["*** sensitive  ... "])
 5. /var/www/html/apps/user_ldap/lib/Access.php line 1097
    OCA\User_LDAP\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/html/apps/user_ldap/lib/Access.php line 1132
    invokeLDAPMethod("*** sensitive parameters replaced ***")
 7. /var/www/html/apps/user_ldap/lib/Access.php line 1286
    executeSearch("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 8. /var/www/html/apps/user_ldap/lib/Access.php line 980
    search("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 9. /var/www/html/apps/user_ldap/lib/Access.php line 883
    searchUsers("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
10. /var/www/html/apps/user_ldap/lib/Access.php line 858
    fetchListOfUsers("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
11. /var/www/html/apps/user_ldap/lib/User_LDAP.php line 174
    fetchUsersByLoginName("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
12. /var/www/html/apps/user_ldap/lib/User_LDAP.php line 191
    getLDAPUserByLoginName("*** sensitive parameter replaced ***")
13. <<closure>>
    checkPassword("*** sensitive parameters replaced ***")
14. /var/www/html/apps/user_ldap/lib/User_Proxy.php line 108
    call_user_func_array([OCA\User_LDAP\U ... "], ["*** sensitive  ... "])
15. /var/www/html/apps/user_ldap/lib/Proxy.php line 150
    callOnLastSeenOn("*** sensitive parameter replaced ***", "checkPassword", ["*** sensitive  ... "], false)
16. /var/www/html/apps/user_ldap/lib/User_Proxy.php line 196
    handleRequest("*** sensitive parameter replaced ***", "checkPassword", ["*** sensitive  ... "])
17. /var/www/html/lib/private/User/Manager.php line 208
    checkPassword("*** sensitive parameters replaced ***")
18. /var/www/html/core/Controller/LoginController.php line 309
    checkPasswordNoLogging("*** sensitive parameters replaced ***")
19. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
    tryLogin("*** sensitive parameters replaced ***")
20. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    executeController(OC\Core\Controller\LoginController {}, "tryLogin")
21. /var/www/html/lib/private/AppFramework/App.php line 118
    dispatch(OC\Core\Controller\LoginController {}, "tryLogin")
22. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    main("OC\\Core\\Controller\\LoginController", "tryLogin", OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
23. <<closure>>
    __invoke({_route: "core.login.tryLogin"})
24. /var/www/html/lib/private/Route/Router.php line 297
    call_user_func(OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
25. /var/www/html/lib/base.php line 987
    match("/login")
26. /var/www/html/index.php line 42
    handleRequest()

POST /index.php/login?clear=1

**Comment by MorrisJobke** [comment]
This looks like the network connection between Nextcloud and AD is very instable. At some point Nextcloud can do anything further to work around this. Thus I would ask you to check in the forums for help for this setup issue: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
