### ISSUE TITLE
2FA using NextCloud messages can lead to user lockout

### ISSUE THREAD

**Issue by noseshimself** [nextcloud/server#14764]
### Steps to reproduce
1. Enable OTP via NextCloud messages
2. A new user without any installed clients enables only NextCloud Message OTP.
3. There is no step 3.

### Expected behaviour
The user will never be able to log in again.

### Actual behaviour
The user will never be able to log in again.

### Server configuration
(irrelevant)

Observation: While some OTP apps check if the method is working (see the example of TOTP) the OTP by message is just turned on without checking if it is usable at all.

Solution: Either require backup codes to be available before permanently enforcing the use of a 2FA mechanism or make it a policy that a secondary authentication mechanism has to be tested after activation and record the successful test in the database. 

[The problem is magnified by badly written providers:
$ occ twofactorauth:disable dd twofactor_nextcloud_notification
The provider does not support this operation.]

**Comment by rullzer** [comment]
This is not a server issue. But an issue of the app https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/

That app is mostly developed by some devs (including me) in their free time. If you have a PR to fix it that would be awesome :)

**Comment by noseshimself** [comment]
Am Mittwoch, den 20.03.2019, 06:11 -0700 schrieb Roeland Jago Douma:
> This is not a server issue.

It is in a way because a single plug-in/app can't "fix" it. The server
is the only instance which decides which mechanisms apply. The apps are
"stupid" (as they should be).

>  But an issue of the app 
> https://github.com/nickv-nextcloud/twofactor_nextcloud_notification/
> 
> That app is mostly developed by some devs (including me) in their
> free time.

It isn't sufficient to fix an obviously dangerous app if the next one
coming along is able to make the same bad decisions.

>  If you have a PR to fix it that would be awesome :)

It's a governance issue. Apps of a certain kind (authentication
providers) need to satisfy certain criteria (e. g. proof of succesful
testing an authentication using that mechanism) before becoming
eligible for a user. And it is the server utilizing them to check this.
Closing this PR will not make it less the authentication framework's
responsibility to take care of this.


Achim
