### ISSUE TITLE
Nonprivileged account can perform app update during maintenance mode

### ISSUE THREAD

**Issue by robbykotulla** [nextcloud/server#14779]
### Steps to reproduce
1. Create a non-privileged account (customer group)
2. Sign in with this account in the Nextcloud
3. Connect to the server via SFTP (SSH)
4. Increase the version number of an APP by editing (/app/your_app/appinfo/info.xml)

### Expected behaviour
The non-privileged account (the logged in) should see the maintenance window.

### Actual behaviour
The non-privileged account (the logged in) sees the maintenance window. **But he can execute the app update.**

![grafik](https://user-images.githubusercontent.com/16401515/54742918-fa80e280-4bc2-11e9-90c7-24394ce6972a.png)

### Server configuration

**Operating system**:
*    Linux

**Web server:**
Apache 2

**Database:**
MYSQL

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.02

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

### Client configuration
**Browser:** Google Chrome Version 73.0.3683.86 (64-Bit) (incognito mode)

**Operating system:**
Windows 10 PRO 17763.379

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/13560

**Comment by robbykotulla** [comment]
ACK, sorry I did not see that before
