### ISSUE TITLE
Some apps (auto?)disabled after admin login

### ISSUE THREAD

**Issue by syntron** [nextcloud/server#14773]
### Steps to reproduce
1. login as admin
2. do something
3. logout admin
4. login as user - some apps disabled (dashboard, flow upload, mail)

### Expected behaviour
no change to activated apps

### Actual behaviour
after an admin login/logout cycle some apps (observed: dashboard, flow upload, mail) are deactibvated. It does not happens each time but often enough to be noticed.

### Server configuration

**Operating system**:
opensuse leap 15.0

**Web server:**
apache2-2.4.33

**Database:**
mariadb-10.2.22

**PHP version:**
php7-7.2.5

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from older nextcloud versions (since at least 9.1.0.16)

**Where did you install Nextcloud from:**
tar archive

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - announcementcenter: 3.4.1
  - apporder: 0.6.0
  - bookmarks: 0.16.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - checksum: 0.4.2
  - circles: 0.16.1
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dashboard: 6.0.0
  - dav: 1.8.1
  - deck: 0.5.2
  - dropit: 0.2.0
  - event_update_notification: 0.3.3
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_automatedtagging: 1.5.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_mindmap: 0.0.11
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.2
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trackdownloads: 1.4.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - flowupload: 0.0.9
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.0
  - metadata: 0.9.0
  - news: 13.1.3
  - nextcloud_announcements: 1.4.0
  - notes: 2.5.1
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - ojsxc: 3.4.3
  - password_policy: 1.5.0
  - passwords: 2019.3.0
  - phonetrack: 0.4.4
  - polls: 0.10.2
  - previewgenerator: 2.1.0
  - provisioning_api: 1.5.0
  - quota_warning: 1.4.0
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.2
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_usage_report: 1.1.1
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - bookmarks_fulltextsearch
  - encryption
  - files_fulltextsearch
  - files_fulltextsearch_tesseract
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - mindmaps
  - user_ldap
  - weather

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
falkon-3.0.1

**Operating system:**
opensuse leap 15.0

**Comment by ChristophWurst** [comment]
Check your nextcloud.log. It might contain some important info.

**Comment by syntron** [comment]
I found some lines which seems to be related in the log. However, they are quite long ... Is there a tool to display these information in a usefull way?

There seems to be a connection time out fetching some web page - see the extract below:

"app":"appstoreFetcher","method":"GET","url":"\/settings\/apps\/list","message":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Connection timed out after 10002 milliseconds (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html)",

**Comment by ChristophWurst** [comment]
Yes: https://apps.nextcloud.com/apps/logreader

Does your instance have a working internet connection?

**Comment by syntron** [comment]
Currently, I have some problems and the meassage I listed above seems to be connected to these internet problems.

However, the apps state switch is not connected to this. I observed it since a longer time (~3 months). Just now, I checked for the log reader and noticed that the mentioned apps (dashboard, flow upload and mail) there no longer active. They just disapeared.

Regarding the log file app - I have some errors of level 'warning' from the news app. No messages of level 'error' or 'fatal'. The 'info' log level contains to much data from the news app; is there a way to filter by app? or to show all but a selected app?

**Comment by syntron** [comment]
I just observed this again after I restored/activated the apps yesterday.

Is there a way to log app status changes (enabled <=> disabled)?

**Comment by ChristophWurst** [comment]
> Is there a way to log app status changes (enabled <=> disabled)?

you can use `occ app:list` to read it. Just save that to a file regularly.

**Comment by syntron** [comment]
Thanks! Will do and report back ...

**Comment by syntron** [comment]
OK, I have some results ;-)

First I have to state, that the server runs since ~5 weeks on the backup with reduced CPU power. Thus, timeouts can happen. Here it seems to be a timeput in memcached which results in disabling these apps. To much corn jobs running at the full hour. The dashboard app was disabled some time before. However, I'm still not sure why only these apps are affected.

Regarding the logging app: it would be helpfull to have filters for the apps. I my case the news app generates way to much log messages. Thus, it is hard to find the important ones.

Below the relevant log lines:

 {"reqId":"WwjnUhNLwhftvWA9xYN7","level":3,"time":"2019-03-26T01:00:04+01:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Exception","Message":"Error 31 interacting with memcached : A TIMEOUT OCCURRED","Code":0,"Trace":[{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/Memcache\/Memcached.php","line":117,"function":"verifyReturnCode","class":"OC\\Memcache\\Memcached","type":"->","args":[]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/URLGenerator.php","line":226,"function":"set","class":"OC\\Memcache\\Memcached","type":"->","args":["flowupload-flowupload.svg","\/apps\/flowupload\/img\/flowupload.svg"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/apps\/flowupload\/appinfo\/app.php","line":7,"function":"imagePath","class":"OC\\URLGenerator","type":"->","args":["flowupload","flowupload.svg"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/legacy\/app.php","line":261,"args":["\/srv\/www-extern\/apps\/nextcloud\/apps\/flowupload\/appinfo\/app.php"],"function":"require_once"},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/legacy\/app.php","line":154,"function":"requireAppFile","class":"OC_App","type":"::","args":["flowupload"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/legacy\/app.php","line":127,"function":"loadApp","class":"OC_App","type":"::","args":["flowupload"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/cron.php","line":53,"function":"loadApps","class":"OC_App","type":"::","args":[]}],"File":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/Memcache\/Memcached.php","Line":225,"CustomMessage":"--"},"userAgent":"--","version":"15.0.5.3"}
{"reqId":"WwjnUhNLwhftvWA9xYN7","level":3,"time":"2019-03-26T01:00:05+01:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":{"Exception":"Exception","Message":"Error 31 interacting with memcached : A TIMEOUT OCCURRED","Code":0,"Trace":[{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/Memcache\/Memcached.php","line":117,"function":"verifyReturnCode","class":"OC\\Memcache\\Memcached","type":"->","args":[]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/URLGenerator.php","line":226,"function":"set","class":"OC\\Memcache\\Memcached","type":"->","args":["mail-mail.svg","\/apps\/mail\/img\/mail.svg"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/apps\/mail\/appinfo\/app.php","line":43,"function":"imagePath","class":"OC\\URLGenerator","type":"->","args":["mail","mail.svg"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/legacy\/app.php","line":261,"args":["\/srv\/www-extern\/apps\/nextcloud\/apps\/mail\/appinfo\/app.php"],"function":"require_once"},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/legacy\/app.php","line":154,"function":"requireAppFile","class":"OC_App","type":"::","args":["mail"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/legacy\/app.php","line":127,"function":"loadApp","class":"OC_App","type":"::","args":["mail"]},{"file":"\/srv\/www-extern\/apps\/nextcloud\/cron.php","line":53,"function":"loadApps","class":"OC_App","type":"::","args":[]}],"File":"\/srv\/www-extern\/apps\/nextcloud\/lib\/private\/Memcache\/Memcached.php","Line":225,"CustomMessage":"--"},"userAgent":"--","version":"15.0.5.3"}

**Comment by syntron** [comment]
Final feedback after the server is running fine again: no issues anymore. Thus, the reported bug was really cased by the timeput which happend due to a to small server ...
