### ISSUE TITLE
App passwords don't allow users to correctly authenticate

### ISSUE THREAD

**Issue by codesmaker** [nextcloud/server#14789]
Hi,

I'm trying to authenticate a Nextcloud desktop sync client through using an app password I generated for that user but Nextcloud keeps saying that the password is wrong.

Here is what I have in the logs:
`{"reqId":"mHsPXZUBX8gSzjMATjBc","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"initializing paged search for  Filter (&(|(objectclass=inetOrgPerson))(|(uid=luser1)(|(mailPrimaryAddress=luser1)(mail=luser1)))) base Array\n(\n    [0] => ou=People,dc=mydomain,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n    [1] => nsuniqueid\n    [2] => objectguid\n    [3] => guid\n    [4] => ipauniqueid\n    [5] => dn\n    [6] => uid\n    [7] => samaccountname\n    [8] => memberof\n    [9] => mail\n    [10] => cn\n    [11] => jpegphoto\n    [12] => thumbnailphoto\n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Ready for a paged search","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"LDAP error Invalid credentials (49) after calling ldap_bind","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":2,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"initializing paged search for  Filter (&(|(objectclass=inetOrgPerson))(|(uid=luser1)(|(mailPrimaryAddress=luser1)(mail=luser1)))) base Array\n(\n    [0] => ou=People,dc=mydomain,dc=com\n)\n attr Array\n(\n    [0] => entryuuid\n    [1] => nsuniqueid\n    [2] => objectguid\n    [3] => guid\n    [4] => ipauniqueid\n    [5] => dn\n    [6] => uid\n    [7] => samaccountname\n    [8] => memberof\n    [9] => mail\n    [10] => cn\n    [11] => jpegphoto\n    [12] => thumbnailphoto\n)\n limit 500 offset 0","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Ready for a paged search","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"LDAP error Invalid credentials (49) after calling ldap_bind","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":2,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"user_ldap","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Bind failed: 49: Invalid credentials","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"mHsPXZUBX8gSzjMATjBc","level":2,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"POST","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Login failed: 'luser1' (Remote IP: '192.168.0.216')","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery-ui-fixes.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/server.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/css-variables.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Scss is disabled for \/var\/www\/nextcloud\/apps\/firstrunwizard\/css\/firstrunwizard.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/css\/jquery.ocdialog.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"core","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"Scss is disabled for \/var\/www\/nextcloud\/core\/search\/css\/results.scss, ignoring","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"AZY13sYIJ48o6tmMgp2Z","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/login?redirect_url=\/nextcloud\/index.php\/login\/flow\/grant%3FclientIdentifier%3D%26stateToken%3DRDeSGMwkq2foqfwr3eN0DcyeCiWiRjsMXJFB0YKiCq7RjU8It5rT11sucs7oB4Xu&user=luser1","message":"No cache entry found for \/appdata_oco2rtispral\/theming\/images\/logo (storage: local::\/mnt\/data\/ncdata\/, internalPath: appdata_oco2rtispral\/theming\/images\/logo)","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"W7atg3hdZAURY832e2CT","level":0,"time":"2019-03-21T14:11:23+01:00","remoteAddr":"192.168.0.216","user":"--","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/core\/js\/oc.js?v=f8d6383a","message":"No cache entry found for \/appdata_oco2rtispral\/theming\/images\/logo (storage: local::\/mnt\/data\/ncdata\/, internalPath: appdata_oco2rtispral\/theming\/images\/logo)","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}
{"reqId":"W7atg3hdZAURY832e2CT","level":0,"time":"2019-03-21T14:11:24+01:00","remoteAddr":"192.168.0.216","user":"--","app":"no app in context","method":"GET","url":"\/nextcloud\/index.php\/core\/js\/oc.js?v=f8d6383a","message":"No cache entry found for \/appdata_oco2rtispral\/theming\/images\/background (storage: local::\/mnt\/data\/ncdata\/, internalPath: appdata_oco2rtispral\/theming\/images\/background)","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.1git (Nextcloud)","version":"15.0.5.3"}`

Nextcloud: 15.0.5
OS: Debian 9
Desktop client: 2.5.1

**Comment by rullzer** [comment]
You can't use the login flow with an app password. For that you need to press on the alternative login.
You should login with your normal username and password and an app password will be created for you.

**Comment by codesmaker** [comment]
Thanks for your reply and help.

I remember that was possible before. Anyways, I'm actually trying to activate the 2FA and use Nextcloud notifications. The problem is that I'm not receiving any notifications in the Desktop client or on the mobile sync app. I read somewhere that clients need to be authenticated using an app password. Is it another issue?

Another question: if app passwords can not be used to login, why there is the possibility to create them?

**Comment by rullzer** [comment]
Login with 2fa should just work. You get prompted for you 2FA method of input. If you 2FA method is not supported via our login (special key or something). Then you can use an app password but you have to clickthe 'use alternative login'.

> The problem is that I'm not receiving any notifications in the Desktop client or on the mobile sync app

That is a different problem. Try to refresh the notifications in your mobile app manually.

> Another question: if app passwords can not be used to login, why there is the possibility to create them?

Because there could be other reasons you want to create them. For example as above if your 2FA method doesn't work on the login flow. Or if you want to have a script that for example does automatic upload oif something etc.

**Comment by codesmaker** [comment]
Thanks for the explanation!
