### ISSUE TITLE
PDF thumbnailgeneration fails

### ISSUE THREAD

**Issue by VersuchUndIrrtum** [nextcloud/server#14787]
Solution is foud here:
https://www.c-rieger.de/solution-for-imagickexception-in-nextcloud-log/

### Steps to reproduce
1. Activate preview of PDF
2. Install Imagick including Ghostscript

### Expected behaviour
Thumbnails of PDF-documents

### Actual behaviour
PDF-icons

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
mariaDB 10.3

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
15.05

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated and fresh

**Where did you install Nextcloud from:**
ZIP-File from Nextcloud
**Signing status:**

**List of activated apps:**
PDF-Viewer

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb
**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
smb

#### Nextcloud log (data/nextcloud.log)
  | ImagickException: not authorized `/tmp/oc_tmp_RRqGjI-.pdf' @ error/constitute.c/ReadImage/412
-- | --

**Comment by MorrisJobke** [comment]
There is not much we can do. 

> https://www.c-rieger.de/solution-for-imagickexception-in-nextcloud-log/

That seems to do the job - so closing this ticket here.
