### ISSUE TITLE
Separate Admin Login Page

### ISSUE THREAD

**Issue by BMa19** [nextcloud/server#14785]
In case it must not be possible for admins to login to nextcloud from everywhere, there should be a possibility to restrict admin-login to internal (or spezific) IP addresses. 

One way could be separate login urls like other applications have, like https://example.com/[admin|user]. This way a restriction for logins will be possible in the webserver config

An alternative could be a addon like "Restrict login to IP addresses" (or a extension of it) including the possibility to restrict specific user logins to IP addresses (e.g. user: admin; allow_from=192.168.1.137)

It is my first FR. So if there was/is something similar, please let me know :)

**Comment by kesselb** [comment]
Thank you for this feature request :tada: 

Check this feature request: https://github.com/nextcloud/limit_login_to_ip/issues/20
