### ISSUE TITLE
Can not recreate a suer

### ISSUE THREAD

**Issue by Bschalck** [nextcloud/server#14796]
### Steps to reproduce
1.Create a user in LDAP
2.Delete user in ldap
3.Delete user in Nextcloud
4. Recreate user in Nextcloud : 
 Failed addUser attempt: User already exists.

### Expected behaviour
I can not recreate my test user after deleting it

### Actual behaviour
I ve an error   | Failed addUser attempt: User already exists.

### Server configuration

**Operating system**: debian Jessie

**Web server:** apache

**Database:** mysql

**PHP version:**7.033

**Nextcloud version:** (see Nextcloud admin page) 15.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>

**Are you using encryption:** yes
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
> 2.Delete user in ldap
> 3.Delete user in Nextcloud

Have you used the remnant removal feature? See https://docs.nextcloud.com/server/stable/admin_manual/configuration_user/user_auth_ldap_cleanup.html

**Comment by Bschalck** [comment]
Hello,

sorry , I will close this issue. I think there is a delay between the delete of a user in LDAP / local and the recreation of the user.
I try to add the user yesterday, and it works.

By the way , thanks for the hint , I didn't notice this new feature.

Reagrds ,
