### ISSUE TITLE
Translation in the "Sharing" administrator settings

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#14793]
Translation in the "Sharing" administrator settings:

![obraz](https://user-images.githubusercontent.com/47037905/54760954-6f6b1100-4bf1-11e9-85d2-7ce12a20d681.png)

![obraz](https://user-images.githubusercontent.com/47037905/54761076-ae996200-4bf1-11e9-971a-81ab08aba431.png)

They are downloaded from the folder: `settings\l10n` instead of `lib\l10n`.

Or the translation should be moved to: `settings\l10n`.

Below is the code from the file :`lib\private\Settings\Admin\Sharing.php`

```
private function getSharePermissionList() {
		return [
			[
				'id' => 'cancreate',
				'label' => $this->l->t('Create'),
				'value' => Constants::PERMISSION_CREATE
			],
			[
				'id' => 'canupdate',
				'label' => $this->l->t('Change'),
				'value' => Constants::PERMISSION_UPDATE
			],
			[
				'id' => 'candelete',
				'label' => $this->l->t('Delete'),
				'value' => Constants::PERMISSION_DELETE
			],
			[
				'id' => 'canshare',
				'label' => $this->l->t('Share'),
				'value' => Constants::PERMISSION_SHARE
			],
		];
	}

```

App: Nextcloud v15.0.5

**Comment by rullzer** [comment]
Ah joy. Another reason we should move those settings properly over. Let me check this.

**Comment by rullzer** [comment]
mmm @Valdnet do you actually not see the translations? Because they should be in both translation files.

**Comment by Valdnet** [comment]
@rullzer the translation is in the files:
`lib/l10n/pl.js`
`lib/l10n/pl.json`
```
    "Create" : "Utwórz",
    "Change" : "Zmień",
    "Delete" : "Usuń",
    "Share" : "Udostępnij",
```
while where translations in files:
`settings/l10n/pl.js`
`settings/l10n/pl.json`

is located only
`"Delete" : "Usuń",`
and it belongs to the translation for another option.

There are no words in Transifex for translating into "settings-1": Create, Change and Share.

**Comment by Valdnet** [comment]
See also the issue #14607.
