### ISSUE TITLE
Remove accept/decline buttons in invitation canceled emails 

### ISSUE THREAD

**Issue by Ivansss** [nextcloud/server#14791]
Invitation canceled emails have "Accept" and "Decline" buttons in it.

![Screen Shot 2019-03-21 at 13 37 23](https://user-images.githubusercontent.com/4638605/54752683-4ccffc80-4bdf-11e9-9aa7-793ad2d7964a.png)

Clicking on any of those buttons lead to the following site:

![Screen Shot 2019-03-21 at 13 39 39](https://user-images.githubusercontent.com/4638605/54752738-6b35f800-4bdf-11e9-8e14-7985f7a3cbb1.png)

I guess there should be no buttons in "Invitation canceled" emails.

**Comment by georgehrke** [comment]
This was fixed in https://github.com/nextcloud/server/pull/12392
