### ISSUE TITLE
Add extend Pimple feature to IContainer public interface

### ISSUE THREAD

**Issue by Toilal** [nextcloud/server#14799]
**Is your feature request related to a problem? Please describe.**

Pimple container provides an [extend method](https://pimple.symfony.com/#modifying-services-after-definition) that can be very handy to customize internal services using decorator pattern. 

In my own use case, I want to write an App that change default behavior of [IContactsStore](https://github.com/nextcloud/server/blob/v15.0.5/lib/private/Server.php#L1178-L1185) and [\OCP\Collaboration\Collaborators\ISearch](https://github.com/nextcloud/server/blob/v15.0.5/lib/private/Server.php#L1077-L1088) to customize user filtering.

**Describe the solution you'd like**

I wish I could use an official NextCloud API that delegates to `extend` method of Pimple container should be available in IContainer interface

```php
/**
* Extend an already registered service.
*
* @param string $name
* @param \Closure $closure
* @return void
*/
public function extendService($name, Closure $closure);
```

Then I could write the following code in `lib/AppInfo/Application.php` of my app.

```php
<?php

namespace OCA\CustomContactsStore\AppInfo;

use OC\Server;
use OCA\CustomContactsStore\Service\CustomCollaboratorsSearch;
use OCA\CustomContactsStore\Service\CustomContactsStore;
use OCP\AppFramework\App;
use OCP\Contacts\ContactsMenu\IContactsStore;

class Application extends App
{
    public function __construct()
    {
        parent::__construct('CustomContactsStore');

        $server = $this->getContainer()->getServer();

        $server->extendService(IContactsStore::class, function ($defaultContactsStore, Server $c) {
            return new CustomContactsStore($defaultContactsStore);
        });

        $server->extendService(\OCP\Collaboration\Collaborators\ISearch::class, function ($defaultCollaboratorsSearch, Server $c) {
            return new CustomCollaboratorsSearch($defaultCollaboratorsSearch);
        });
    }
}
```

**Describe alternatives you've considered**

It actually works well by using extend method directly available in underlying Pimple container, but It should be available officially in the NextCloud API ([IContainer](https://github.com/nextcloud/server/blob/v15.0.5/lib/public/IContainer.php)).

**Additional context**
N/A

**Comment by kesselb** [comment]
cc @ChristophWurst please review the status of this issue because you closed the related pull request.

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/14800#issuecomment-531588999
