### ISSUE TITLE
Delete of multiple files/folders does not work

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#14807]
### Steps to reproduce
1. create two files
2. select both files and on top "…" -> delete
3. nothing happens
4. delete them manually works

### Expected behaviour
mutliple deletion should work

### Actual behaviour
Deletion does not work

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
master

**Comment by nickvergessen** [comment]
```
TypeError: _.pluck is not a function[Weitere Informationen] filelist.js:1025:13

    _onClickDeleteSelected https://nextcloud16.local/apps/files/js/filelist.js:1025 multiSelectMenuClick https://nextcloud16.local/apps/files/js/filelist.js:452 _onClickAction https://nextcloud16.local/apps/files/js/filemultiselectmenu.js:92 _onClickAction self-hosted:975 dispatch https://nextcloud16.local/core/js/dist/main.js:39 handle https://nextcloud16.local/core/js/dist/main.js:39 
```

**Comment by nickvergessen** [comment]
@skjnldsv mind to have a look?

**Comment by jookk** [comment]
I tried and selected files went to trash.
Upgraded from 15.05

**Comment by tobiasKaminsky** [comment]
Works with beta 2
