### ISSUE TITLE
Option to let a non admin user to create new groups

### ISSUE THREAD

**Issue by praflo** [nextcloud/server#14814]
Why can groups be created only by admin users?
I need to give a user permissions to create new groups and let him add users to these groups, but I don't want to give him "super user" permissions (e.g. add him to the admin group). 
How can I do this?
ty
gian

**Comment by Nils160988** [comment]
Maybe, you can use the circles app for your purpose. Have you had a look at it?

**Comment by praflo** [comment]
Do you mean https://github.com/nextcloud/circles ?
No, I didn't.
But latest version is 0.15.4, not sure it's safe to install it in a production env. Is it?
I'll check it in a sandbox.
Imho, group management should be a feature customizable  in the core system.
ty

**Comment by MorrisJobke** [comment]
We are about to consolidate the group and circle management - see #13478.

I would close this ticket here for now.
