### ISSUE TITLE
Custom favicon not showing up in Mac Safari

### ISSUE THREAD

**Issue by myevit** [nextcloud/server#14818]
Nextcloud 15.0.5
Theming app 1.6.0 

Using theming app. in Firefox all good. Favicon is working properly. In Safari only default all over whole site.
<img width="334" alt="Screen Shot 2019-03-23 at 11 22 33" src="https://user-images.githubusercontent.com/13375246/54869454-18367f00-4d5e-11e9-8fc4-d3196eebd8ec.png">
<img width="334" alt="Screen Shot 2019-03-23 at 11 22 51" src="https://user-images.githubusercontent.com/13375246/54869455-18367f00-4d5e-11e9-80d5-494e574dfe1f.png">

**Comment by kesselb** [comment]
@nextcloud/mac can you confirm?

**Comment by myevit** [comment]
Still there. There are 3 different icons in Safari. Only one I can set.

Should be everywhere which is in address bar.

<img width="303" alt="Screen Shot 2019-06-09 at 10 32 53 AM" src="https://user-images.githubusercontent.com/13375246/59161595-23b65e00-8aa2-11e9-90aa-27cab5657a25.png">
<img width="123" alt="Screen Shot 2019-06-09 at 10 33 01 AM" src="https://user-images.githubusercontent.com/13375246/59161597-2618b800-8aa2-11e9-90dc-1e6d5f942d37.png">

**Comment by georgehrke** [comment]
@skjnldsv Do you know more about theming? I guess we don't replace the apple-touch-icon with the uploaded icon?

**Comment by skjnldsv** [comment]
@georgehrke, @juliushaertl is out theming expert! :heart_eyes:

**Comment by juliushaertl** [comment]
It seems that there are two issues here:
- The uploaded favicon is not used for the apple-touch-icon-precomposed (this should be easy to fix, as the current icon is already coming from the theming app)
- The nextcloud icon in the tab list is actually caused by the mask-icon not being available in the theming app. Since we support various formats to be uploaded as the logo, there is no way we can generate a new mask for that. So I think the best would be to just hide the mask in case the theming app is used?

**Comment by wenz** [comment]
PR adds apple-touch-icon-precomposed for custom favicons. Can we determine whether the theming app is used or not to remove the mask in that case?

**Comment by FloMiLe** [comment]
For me, this is still the case with NC23 and Safari 15.

All other Browser I have tried (Chrome, Firefox, Vivaldi, Brave) do show a favicon corresponding to my logo.

**Comment by crasherwosa** [comment]
I also have the same problem. I have changed the favicon via Settings/Design/Favicon. Now it is attracted in Opera, Firefox or even Chrome. But not in Safari. In Safari, only the favicon color is adjusted to the set color of the navigation. If now the color is changed to purple under Settings/Design, the favicon is also purple with the Nextloud logo. 

Is there any more info in the meantime on what this is? File format? Size? Bug?

I use Nextcloud Hub II (23.0.2) - Safari Version 15.2
