### ISSUE TITLE
 Share link problem

### ISSUE THREAD

**Issue by zzeesstt** [nextcloud/server#14826]
Unable to highlight share link icon:

![bandicam 2019-03-24 23-47-15-566_1](https://user-images.githubusercontent.com/32969232/54886426-85e2c800-4e90-11e9-91ea-8265c370e7f9.gif)

_______________________________________________________________________________________________________

![Безымянный](https://user-images.githubusercontent.com/32969232/54886529-83cd3900-4e91-11e9-9d6a-8fdd88e9606d.png)

_______________________________________________________________________________________________________

Nextcloud 15.0.5
Snap install on raspberry pi

**Comment by MorrisJobke** [comment]
This is most likely due to an adblocker hiding it - see #14616. For the documentation of this issue have a look at #10411
