### ISSUE TITLE
External files - SFTP - Private RSA Key - Unable to load private key

### ISSUE THREAD

**Issue by Eluminae** [nextcloud/server#14820]
Hello there,

I got a simple problem. I really dunno how to setup external files sftp acces with private keys. There is a login method but it just don't work. Browsing the code source did not helped me to understand how to setup.

I'm trying to paste my private key in the "private key" field but I got an "unable to load private key"

Is there anyone who success to setup this ?

Ty !

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by MorrisJobke** [comment]
> I'm trying to paste my private key in the "private key" field but I got an "unable to load private key"

This looks like the key is somehow in a wrong format. Sure - it could be a bug, but I would like to ask you to first verify if there are others with the same problem. We then can reopen this ticket.

**Comment by Eluminae** [comment]
Before trying to says "it does not work", I'd want to know how to use it. There is no questions about it and no documentation covering the use case. I don't really want to create a new user profile in a specific forum just to have the answer. That's why I questioned directly here.

**Comment by MorrisJobke** [comment]
> That's why I questioned directly here.

But this is the wrong place for such stuff - it's the bug tracker not a help forum. We try to organize development of the software here and don't plan to use this as a support system. Thus I send you to the forums. Documentation for this is in https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/external_storage/sftp.html

If there is something unclear or not documented then it needs to go into https://github.com/nextcloud/documentation/issues

Sorry if this is confusing. We just want to keep the topics of each place separated to not loose the overview.

Thanks for the feedback anyways.
