### ISSUE TITLE
File Access Control using Tags

### ISSUE THREAD

**Issue by rpatel-rnits** [nextcloud/server#14828]
![image](https://user-images.githubusercontent.com/5283163/54859192-a9ffa700-4ce0-11e9-8e98-5a52eab98829.png)

I created the above logic and it works, but there is a bug.  I created a folder, called "Project A".  In the folder, I created 3 other folders, "Contracts", "Project Plans", and "Meeting Minutes".  The Contracts folder is restricted to only some users, in this case "Internal users".  So I tagged the "Controcts" folder as Internal users.  I logged in as regular shared user and am able to see the Project folder but not see the "Contracts", which is perfect.  Even when using the desktop sync client it is working perfectly.

But there is a bug here now.  If you go out and go back to the main root directly where you see the "Project A" folder on the web client, and then click the three dots, and then click "Download", this downloads the hole project folder.  In this download, the Contracts folder is also downloaded.  Not sure if this is a bug or I need to update the File Access Control?

Thanks.
Ravi

**Comment by MorrisJobke** [comment]
cc @blizzz

**Comment by blizzz** [comment]
Mh, the archive creation does not go via WebDAV, I think, rather directly against the filesystem circumventing this. cc @nickvergessen

**Comment by rpatel-rnits** [comment]
Will this issue be fixed?

**Comment by nickvergessen** [comment]
Phew, I guess the zipping function doesnt check the read permissions of all files first? That would already solve this.

With Groupfolder ACL permissions the same problem should exist? :thinking: 
cc @icewind1991

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
