### ISSUE TITLE
Address Book: Specify number of backups

### ISSUE THREAD

**Issue by Berni-MD** [nextcloud/server#14836]
With the help of the Android App for Nextcloud the address book can be secured very well. But there are no settings for the number of backups or for a rhythm for deleting backups.

This causes the backup directory to overflow or become confusing at some point.

The most ingenious would be a file rollup where for example the last 5 backups are preserved + one per month.

**Comment by ChristophWurst** [comment]
Is this ticket intended for https://github.com/nextcloud/android/? cc @tobiasKaminsky

**Comment by Berni-MD** [comment]
Oh, thank you. Oh, thank you.
The subject really fits in better!
