### ISSUE TITLE
php-intl extension REQUIRED for federation module?

### ISSUE THREAD

**Issue by michauk** [nextcloud/server#14839]
### Steps to reproduce
1. try to play with two 15.0.5 nextcloud instances, share something to a "federation" account between them. you get the notification but nothing works, no new directory is listed
2. Then try to wonder what's wrong. See the many many many lines of "You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead." messages
3. install php-intl on both servers. Unshare, share again. It works. Coincidence?

### Expected behaviour
php-intl seems to be in many discussions here. It definitely should be at least a warning somewhere when missing, or a pre-requisite in the installation. At least when using federation, which seems not functionnal without (?)

### Actual behaviour
seems to work but doesn't :)

### Server configuration
fresh 15.0.5 installs, debian stable, nothing in particular in the NC instance.
running mariadb/apache/php7.0, all the debian's stable versions

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh on one of the instances. The other one was older and already upgraded from a previous release

**Where did you install Nextcloud from:**
targz

**Signing status:**
<details>
<summary>Signing status</summary>

```
I got: No errors have been found.
```
</details>

**List of activated apps:**
a lot, but standard ones. Shall I detail?
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

need more details? not sure

**Comment by kesselb** [comment]
Anything in the logs if `php-intl` is not enabled?
