### ISSUE TITLE
VCARD import is still broken for UTF8

### ISSUE THREAD

**Issue by FauthD** [nextcloud/server#14830]
Using 15.0.5
Export seems to work as I can see the Umlauts correctly in the vcard file.
A reimport (after deleting existing entries), brings in broken Umlauts (? sign).

NC should be able to reimport its own exports.

An example export:
`BEGIN:VCARD
VERSION:3.0
UID:BF9FA6C2-6CEF3178-08A7A2B2
URL:
TITLE:
ROLE:
X-EVOLUTION-MANAGER:Mr Ü
X-EVOLUTION-ASSISTANT:
NICKNAME:äöü
X-EVOLUTION-SPOUSE:
NOTE:
FN:yet another test for äöü
N:for äöü;another;test;;
X-EVOLUTION-FILE-AS:for äöü\, another
X-EVOLUTION-BLOG-URL:
CALURI:
FBURL:
X-EVOLUTION-VIDEO-URL:
X-MOZILLA-HTML:FALSE
ADR;TYPE=WORK:;;Ü-Straße 5;Öheim;;12345;Germany
LABEL;TYPE=WORK:Ü-Straße 5\nÖheim\n12345\nGermany
CATEGORIES:Restaurants
END:VCARD
`

**Comment by j-ed** [comment]
Unfortunately you're not providing any information in which kind of environment, e.g. a Windows PC, you've stored the exported vcf file and how you've exactly double-checked that the exported and re-imported vcf-file was itf-8 encoded. My own tests are confirming that utf-8 encoded files **are correctly imported**.

Although Nextcloud stores all information utf-8 encoded, this doesn't automatically mean that the exported file will also be **utf-8** encoded. If you save it to a Windows drive it will most likely automatically be converted and stored **iso-8859-1** encoded on your hard drive. If you import an iso-8859-1 encoded file, the characters won't be displayed correctly afterwards within Nextcloud, but if it is an utf-8 encoded file it will definitely imported correctly.

**Comment by FauthD** [comment]
Sorry,
you are completely right.
My environment is Ubuntu 1604 and usually everything is UTF8.
What I found in further tests is that VS-Code might translate to 8859.1 or Win1252.
I then used gedit and it seems to work with UTF8.

So lets close this for now.
Thanks!
