### ISSUE TITLE
Border around mime icon in file list

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#14849]
![image](https://user-images.githubusercontent.com/3404133/54983344-ebc47200-4fac-11e9-8c68-e2f0cb6ffef9.png)

Added by https://github.com/nextcloud/server/pull/14637 but we should limit this to the grid view only.

@nextcloud/designers

**Comment by skjnldsv** [comment]
I thought @jancborchardt fixed it :thinking: 
We need to use the has-preview info to set the border

**Comment by juliushaertl** [comment]
Ah just recognized, this is not happening in the main file list but in all the others (favorites/shares/...)

**Comment by jancborchardt** [comment]
So the issue is that in the other views, seemingly every `tr` gets the `data-has-preview='true'`. It should only be added to those rows which actually have a preview (images, text files etc) but not to folders and where filetype icons are shown.

@nextcloud/javascript?
