### ISSUE TITLE
CROSSPOST: phpseclib SSH2.php Fatal ErrorException line 3821 #257

### ISSUE THREAD

**Issue by unamundan** [nextcloud/server#14848]
Original report filed https://github.com/nextcloud/server/issues/26714 19.03.21.

**Comment by Garfonso** [comment]
I have the same issue and the error message clogs my log, so that a ~160gb nextcloud.log file is created and then drive space is up... urgs... :-/
I did not have this issue previous to an upgrade to nextcloud 19 and / or system Upgrade to Ubuntu 20.04 LTS (from previous LTS) on both systems.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/26714
