### ISSUE TITLE
Steps left for seemless 10.0 updater

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1485]
* [x] remove `data/updater-INSTANCEID/.step` once the upgrade is done (best via single time background job because then we know the cron.php succeeds again -> means upgrade was successful)
* [x] revert 202ae42506e9bbb167889735b2c56ccebace594b (brings back the "Open updater" button)

cc @LukasReschke

**Comment by MorrisJobke** [comment]
* master: #1499
* stable10: #1500 
* stable9: #1501

**Comment by LukasReschke** [comment]
All merged => Close.
