### ISSUE TITLE
Add support for object storage like minio

### ISSUE THREAD

**Issue by jearton** [nextcloud/server#14864]
The minio website：https://min.io

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/15/admin_manual/configuration_files/external_storage/amazons3.html minio is compatible with Amazon s3. Does this work for you?

**Comment by jearton** [comment]
> https://docs.nextcloud.com/server/15/admin_manual/configuration_files/external_storage/amazons3.html minio is compatible with Amazon s3. Does this work for you?

It works. Thanks for the advice.
