### ISSUE TITLE
Webcal address point to another domain

### ISSUE THREAD

**Issue by danicotillas** [nextcloud/server#14862]
Steps to reproduce
I enter into the link to share the calendar.
I click on subscribe --> https://caracol.nodocomun.org/index.php/apps/calendar/p/Xoy8TstZCH9NnCM5/Nodo-Comn-Madrid
It goes to another domain. Instead of caracol.nodocomun.org it goes to pony.nodocomun.org.
NOTE: I use Nextcloud installation through Softacullous on a CPanel. Few months ago I was unable to update my Caracol install so I tried a new one called Pony on that second subdomain. Finally I could update Caracol and delete everything about Pony but now this bug has appeared.

Expected behaviour
When you click on Subscribe it should remain on the caracol.nodocomun.org domain

Actual behaviour
When you click on the Subscribe button it goes to pony.nodocomun.org

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
