### ISSUE TITLE
Update event status while not logged in gives confusing advice

### ISSUE THREAD

**Issue by dosch** [nextcloud/server#14860]
### Steps to reproduce
1. Make sure you are not logged in to your NC account
2. Receive updated calendar invitation in mail
3. Click 'Accept'

### Expected behaviour
When not logged in, NC can't update the calendar status. So it should offer to log-in and then redirect to the calendar or, even better, perform said action (accept) right away.

### Actual behaviour
User is presented with an error and encouraged to contact the event creator (who can't really do anything about this...)\

![Screenshot 2019-03-26 at 13 45 14](https://user-images.githubusercontent.com/5372610/54998251-f3484300-4fcd-11e9-98f1-b913760a18f0.png)

**Nextcloud version:** 15.0.5

**Comment by rullzer** [comment]
Fair enough we should handle that properly.

@georgehrke

**Comment by georgehrke** [comment]
@dosch Is it by any chance a shared calendar?

**Comment by dosch** [comment]
It is indeed
