### ISSUE TITLE
Can't install nextcloud on windows 7 enterprise 32 bit

### ISSUE THREAD

**Issue by whoopsy66** [nextcloud/server#14877]
I tried to install nextcloud executable on windows 7 enterprise 32 bit, but getting it's not compatible with it. :-(
![nextcould](https://user-images.githubusercontent.com/48985535/55067950-f6e8d200-5080-11e9-9290-422b6820e5db.GIF)

**Comment by Faldon** [comment]
You're talking about the desktop sync client?
If so, it seems the build is indeed a 64-bit executable.
But maybe this would better fit in (https://github.com/nextcloud/desktop)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/desktop/issues/840

**Comment by KarelWintersky** [comment]
Excellent solution!

**Closed as duplicate AND original issue closed too.**
