### ISSUE TITLE
Quota for $datadir/$user/upload/ 

### ISSUE THREAD

**Issue by azrdev** [nextcloud/server#14871]
**Is your feature request related to a problem? Please describe.**
Limited quota on nextcloud installation is repeatedly filled by (auto)uploads to external storage which is apparently transferred slowly or not at all, while the client (auto)uploads way faster.

**Describe the solution you'd like**
Allow to limit the size of the upload directory `$datadir/$user/upload` which apparently acts as a cache for external storage.

**Additional context**
Related: #1922 #6680

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
