### ISSUE TITLE
Weblogin flow: login button does not work on Andoid 4.0.4

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#14889]
- try to sign in with Android 4.0.4 and Nextcloud Files Android app
- press login after entering credentials
- nothing happens

NC: 16 beta1

**Comment by Stadou** [comment]
Same behavior on Windows with Firefox and Chrome

**Comment by Lars1963** [comment]
Also on Android 8.0.0

**Comment by Lars1963** [comment]
#14916

**Comment by tobiasKaminsky** [comment]
go away stale bot ;-)

**Comment by tobiasKaminsky** [comment]
4.0.4 is no longer supported by us -> closing.
