### ISSUE TITLE
E-Mail when sharing has no space in German between "via" and Cloud Description

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#14888]
### Steps to reproduce
1. Share some file with user with German Layout
2. User will get notification E-Mail
3. In header no space after word "via" or on German "über"

Screenshot, shows that e.g. in Russian is ok:
![image](https://user-images.githubusercontent.com/6813635/55139534-4b01be00-5136-11e9-829a-ce1139911035.png)

### Expected behaviour
The same as on other Languages

### Actual behaviour
Tell us what happens instead

### Server configuration

**Nextcloud version:** 15.05

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official

**Comment by f2k1de** [comment]
#14904

**Comment by violoncelloCH** [comment]
should be fixed (at least on transifex, so it is either already in 15.0.6 or 15.0.7 or will be in the next release)
