### ISSUE TITLE
Create public link: resharing not allowed

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#14898]
- create a file
- click on sharing
- click on "add link"
- see spinning link
![image](https://user-images.githubusercontent.com/5836855/55148322-42b27e80-5148-11e9-8aff-69b002ad599d.png)
- hit refresh
- see "resharing not allowed"
![image](https://user-images.githubusercontent.com/5836855/55148364-5b229900-5148-11e9-8da2-bb8179002650.png)

**Comment by rullzer** [comment]
Can you double check with beta2?

**Comment by tobiasKaminsky** [comment]
Working now :tada:
