### ISSUE TITLE
v15 php7.2 occ installation fails but web works due to argon

### ISSUE THREAD

**Issue by alpapan** [nextcloud/server#14896]
### Steps to reproduce
1. Download latest stable version nextcloud-15.0.5.tar.bz2
2. Install using occ -> fails when admin logging in with password not recognised
3. Install using web -> works
4. compare databases

### Expected behaviour

I expected the admin user to be able to login after installing with occ using the same data as when installing via the web. The config.php file is the same.

### Actual behaviour
The occ way fails, while the web way works.

**Then I looked at my postgres and the entries from the occ way that didn't work used argon2**

```
ntg_nextcloud=# select * from  oc_users;
  uid   | displayname |                                             password                                              | uid_lower
--------+-------------+---------------------------------------------------------------------------------------------------+-----------
 admin  |             | 2|$argon2i$v=19$m=1024,t=2,p=2$SW1HVmc3NGxsZExQM25wMQ$0SMcbFpJwjGbf0UuxhnUvEh+lXXXXXXXX  | admin
```

the web way used bcrypt and did work (**I don't know why the occ defaults to argon and the web one defaults to bcrypt**:
```
  uid  | displayname |                            password                            | uid_lower
-------+-------------+----------------------------------------------------------------+-----------
 admin |             | 1|$2y$10$ZBdINx6cYzYArpgiiteMXOhsO4ktwD43oDERJyhM4CxaXXXXXX | admin
```

I had installed the php libraries as mentioned in the [installation guide](https://docs.nextcloud.com/server/15/admin_manual/installation/source_installation.html):
```
php7.2-gd php7.2-json php7.2-mysql php7.2-curl php7.2-mbstring php7.2-intl php-imagick php7.2-xml php7.2-zip libapache2-mod-php7.2
```

and libargon2-0 is installed (but only that, no other argon2 packages). My installed crypt packages were

```
libcryptsetup4     libgcrypt11        libgcrypt20        libhcrypto4-heimdal libk5crypto3       libmcrypt-dev      libmcrypt4         mcrypt             php7.0-mcrypt      python-cryptography
```

The postgres is on another server but it has the same above packages installed. THe only difference is that the postgres server is Ubuntu 18.04 not 16.04

Any ideas why this fails with argon passwords?
Why does occ and the web wizard using different hashings? why can we not control it in the occ via the options?

many thanks!
alexie

### Server configuration

**Operating system**:
Ubuntu 16.04

**Web server:**
Apache 2.4.38-2+ubuntu16.04.1+deb.sury.org+8

**Database:**
postgres 9.5.14 on a separate server

**PHP version:**
PHP 7.2  7.2.16-1+ubuntu16.04.1+deb.sury.org+1

**Nextcloud version:** (see Nextcloud admin page)

15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**

fresh install. tried many times

**Where did you install Nextcloud from:**
Where did I install it from? https://nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>None, vanilla</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

{
    "system": {
        "loglevel": 2,
        "maintenance": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ourdata.hortgenomics.science"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/ourdata.hortgenomics.science",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "cache_path": "\/data_storage\/www-cluster\/gpi\/nextcloud_cache",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no

SSL for HTTPS. 
Postgres is not using encryption

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**

Chrome, Microsoft Edge

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XJyHDyNf5WxzctIrF4VQowAAAAI","level":2,"time":"2019-03-28T08:34:26+00:00","remoteAddr":"220.233.79.26","user":"--","app":"core","method":"POST","url":"\/index.php\/login?user=admin","message":"Login failed: 'admin' (Remote IP: '220.233.79.26')","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/72.0.3626.121 Safari\/537.36","version":"15.0.5.3"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
empty
```
</details>

**Comment by kesselb** [comment]
If you run `./occ xxx` the default php version for your system is used https://github.com/nextcloud/server/blob/8898766954fb605b10384270528e342168f16792/occ#L1

`/usr/bin/env php -v` should print the default version. I guess you run the installation with < php7.2 while your webserver uses php7.2. You might use something like `/usr/bin/php7.2 occ`.

**Comment by alpapan** [comment]
Hello

Good question. It's actually the opposite. THe occ is run with 7.2 and the webserver with 7.0

command line
```
/usr/bin/env php -v
PHP 7.2.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Mar  7 2019 20:23:06) ( NTS )
```

Nextcloud web console says:
```
You are currently running PHP 7.0.33-5+ubuntu16.04.1+deb.sury.org+1
```

So this fixes the issue for me but would there be a way to print out an error into the log that the user table is populated with an argon2 php7.2 password but the web is trying to access it with php7.0 ?

The current error (even with loglevel =0) was just user login failed.
