### ISSUE TITLE
Delete of single file works, but not reflected in UI

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#14894]
- create a folder/file 
![image](https://user-images.githubusercontent.com/5836855/55146274-886d4800-5144-11e9-8c60-3dd755c45444.png)
- delete it
![image](https://user-images.githubusercontent.com/5836855/55146308-9ae78180-5144-11e9-8ea8-c6d930bb3e2b.png)

This spins forever…

**Comment by rullzer** [comment]
Can you double check with beta2?

**Comment by tobiasKaminsky** [comment]
Working now, but has a strange partial progress bar while deleting:
https://nextcloud.kaminsky.me/s/gsTtdTpet2g9jxo

**Comment by skjnldsv** [comment]
Can't reproeduce :)
