### ISSUE TITLE
How to handle files which are missing on the harddisk but are inside the db?

### ISSUE THREAD

**Issue by pointhi** [nextcloud/server#14903]
### Steps to reproduce

(likely cause of the issue, due to the behaviour of the system)

1. add files normally
2. delete files available in nextcloud using the normal linux shell (thus without notifying nextcloud)
3. files are still visible in nextcloud and cause the nextcloud-client to not be able to sync (File or Directory not Found). It is also visible in the browser, and clicking on the folder causes the loading-screen to spin indifinitly (server returns 404)

### Expected behaviour

Provide a method in occ to recover from such an issue, and do not cause sync fail due to it in the client. Practically: parse db entries and check if they exist on the harddisk. Could be integrated into ```occ files:scan --all```

### Actual behaviour

browser page shows folder which does not exists and which is no longer accessible, client application is no longer able to sync at all.

Neither of the two commands fix the issue:
```
occ files:scan --all
occ files:cleanup
```

### Server configuration

**Operating system**: Ubuntu Server 16.04

**Web server:** nginx 1.10.3-0ubuntu0.16.04.3

**Database:** postgresql 9.5+173ubuntu0.2

**PHP version:** PHP 7.0.33-0ubuntu0.16.04.3 (cli) ( NTS )

**Nextcloud version:** 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** web installer

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - audioplayer: 2.6.1
  - bookmarks: 0.16.4
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.4
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.0.5
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.1
  - files_external: 1.6.0
  - files_markdown: 2.0.5
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - news: 13.1.4
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.4
  - support: 1.0.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - firstrunwizard
  - survey_client
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.haru.oe5tpo.com",
            "cloud.oe5tpo.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.haru.oe5tpo.com",
        "dbtype": "pgsql",
        "version": "15.0.5.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "data-fingerprint": "0391c8692995aeb8358d3eb8aa4a1d11"
    }
}
```
</details>

**Are you using external storage:** no

**Are you using encryption:** no

</details>

### Client configuration
**Browser:**

Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:**

Linux h4.4.0-143-generic #169-Ubuntu SMP Thu Feb 7 07:56:38 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

#### Web server error log

The Webserver returns 404, there is nothing visible in the nextcloud logs

```
193.*.*.* - - [28/Mar/2019:16:27:14 +0100] "PROPFIND /remote.php/dav/files/user/filepath/target HTTP/2.0" 404 472 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:66.0) Gecko/20100101 Firefox/66.0"
```

**Comment by violoncelloCH** [comment]
cc @nextcloud/server-triage

**Comment by mikerspencer** [comment]
Is there an interim fix for this that I can apply client side? Ta!

**Comment by szaimen** [comment]
You need to run 
`occ files:scan --all` to do clean up missing files inside the database. If this doesn't work for you, it is most likely a setup issue.
