### ISSUE TITLE
Glitch in German Translation "Persönlich: Du"

### ISSUE THREAD

**Issue by axcro7** [nextcloud/server#14907]
### Steps to reproduce
1. Open Settings
2. Change Language to Deutsch (Persönlich: Du)
3. Go to "Sicherheit" (Security)

### Expected behaviour
The string for _Last activity_ for _This Session_ should be "Gerade eben" (seconds ago)

### Actual behaviour
It says "in ein paar Sekunden" (in a few seconds)

I wanted to edit the translation at transifex.com but couldn't find that string...

### Server configuration

**Operating system**: Ubuntu Server 

**Web server:** apache

**Database:** mysql

**PHP version:** 7.2.16

**Nextcloud version:** 15.0.5 

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
Forwards to http://example.com/index.php/settings/integrity/failed
```
</details>

**List of activated apps:**
<details>
<summary>Accessibility	1.1.0	Offiziell	
Activities for shared file downloads	1.4.0		
Activity	2.8.2	Offiziell	
Antivirus for files	2.0.1		
Checksum	0.4.2		
Collaborative tags	1.5.0	Offiziell	
Comments	1.5.0	Offiziell	
Deck	0.5.2		
Deleted files	1.5.0	Offiziell	
Federation	1.5.0	Offiziell	
File sharing	1.7.0	Offiziell	
Files Right Click	0.13.0		
First run wizard	2.4.0	Offiziell	
Gallery	18.2.0	Offiziell	
Group folders	2.0.4	Offiziell	
Log Reader	2.0.0	Offiziell	
Metadata	0.9.0		
Mind Map	0.0.11		
Monitoring	1.5.0	Offiziell	
Nextcloud announcements	1.4.0	Offiziell	
Notifications	2.3.0	Offiziell	
Password policy	1.5.0	Offiziell	
PDF viewer	1.4.0	Offiziell	
Polls	0.10.2		
Quota warning	1.4.0		
Share by mail	1.5.0	Offiziell	
Support	1.0.0	Offiziell	
Talk	5.0.2	Offiziell	
Tasks	0.9.8		
Text editor	2.7.0	Offiziell	
Theming	1.6.0	Offiziell	
Usage survey	1.3.0	Offiziell	
User account deletion	0.1.0		
Versions	1.8.0	Offiziell	
Video player	1.4.0	Offiziell	</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "****"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/cloud.f-sp.at",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_locale": "de_AT",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**no

### Client configuration
**Browser:** Chrome

**Operating system:** Win 10 Pro

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/8709f6b218f16dd71200c715dd37a1d58736d4e4/core/src/OC/util.js#L124-L130

This function is used to format the activity time. Translation for "seconds ago" are good. 

![image](https://user-images.githubusercontent.com/3902676/55221741-7f46ae80-520a-11e9-8b02-a61878d31a23.png)

Looks ok for me in Nextcloud 16.

**Comment by axcro7** [comment]
Okay, weird, sometimes it is correct, sometimes not:

![2019-03-29 10_25_51-Window](https://user-images.githubusercontent.com/33942658/55222853-35ab9300-520d-11e9-9f1e-22f3dc5c667a.png)

**Comment by kesselb** [comment]
Looks like we pass a timestamp newer than current time to moment.js fromNow: https://github.com/moment/moment/blob/develop/locale/de.js#L49 

Maybe your server time is behind your client time (the timestamp itself is coming from the server but the output is generated by your client).

**Comment by axcro7** [comment]
Sounds plausible, but:
The server time (output of `date` on cli) is a few seconds ahead of my client time

Maybe the condition `if (diff >= 0 && diff < 45000) ` should be changed to just `if (diff < 45000) ` ?

**Comment by axcro7** [comment]
Looks like some caching issue.

Now both entries where wrong again:
![2019-03-29 10_58_51-Window](https://user-images.githubusercontent.com/33942658/55225074-1a8f5200-5212-11e9-90cb-de7d466c25b5.png)

I the changed the Language to English, but the time strings were still partialy in German:
![2019-03-29 10_59_27-Window](https://user-images.githubusercontent.com/33942658/55225084-20853300-5212-11e9-8c2e-3c281945caea.png)

after refreshing the page all time strings were German, and the first two are wrong again:
![2019-03-29 10_59_47-Window](https://user-images.githubusercontent.com/33942658/55225090-22e78d00-5212-11e9-828b-cca45f74717b.png)

**Comment by rakekniven** [comment]
@tflidd I do not think this is an translation issue. The strings are ok. More an issue related to time ...

**Comment by skjnldsv** [comment]
What's the status here?

**Comment by rakekniven** [comment]
Just double checked translation strings at Transifex and I am unable to find shown strings.
Should be ok from i18n side.

**Comment by skjnldsv** [comment]
Closing then?

**Comment by rakekniven** [comment]
Yes
