### ISSUE TITLE
trash bin: show user who deleted that file/folder

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#14917]
**Is your feature request related to a problem? Please describe.**
Sometimes when checking the trash, I find files from shared folders, I would like to know why they were deleted. I don't know which user to ask because I don't know who deleted it.

**Describe the solution you'd like**
In trash bin, show username of the user who deleted the file, for example via a sidebar like in the regular file view (where comments, versions etc are shown).

**Additional context**
Related to https://github.com/nextcloud/server/issues/14138

**Comment by sehucke** [comment]
Probably related to #10017

**Comment by alexanderdd** [comment]
Does a deleted file only appear in the trash bin of the person who deleted it? Or in everyone's trashbin?

And how is it for group folders?

**Comment by being-peace** [comment]
Related to https://github.com/nextcloud/server/issues/24544.
