### ISSUE TITLE
NC Don't read S3 files (in S3 external mount mode)

### ISSUE THREAD

**Issue by yroffin** [nextcloud/server#14911]
hi,

i upload my files on S3 side, without NC with S3 api.
and NC don't show them, NC only report S3 files stored with apps (android)

my S3 storage is an external mount.

![image](https://user-images.githubusercontent.com/728040/55263195-7e486800-5270-11e9-90e6-c847ba7eca4a.png)

![image](https://user-images.githubusercontent.com/728040/55263266-b6e84180-5270-11e9-9b6b-ac6ce6e05e04.png)

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/6954
