### ISSUE TITLE
Show All Day Events in Month View

### ISSUE THREAD

**Issue by muellert** [nextcloud/server#14918]
**Is your feature request related to a problem? Please describe.**

When I look at my calendar in the month view, I can't see any of my "All Day" events. As a result, a day may look free when it is instead blocked due that all-day event. Once I zoom into the week view, the event is being shown, so it's just a UI problem.

**Describe the solution you'd like**

I would like to see these events marked in the month view of the calendar, too.

**Describe alternatives you've considered**

**Additional context**

I'm using Nextcloud 15.0.5.

**Comment by szaimen** [comment]
I think this is already implemented -> closing
