### ISSUE TITLE
Allow WebDAV [GET] access for ordinary web browser clients

### ISSUE THREAD

**Issue by paul-hammant** [nextcloud/server#14919]
"This is the WebDAV interface. It can only be accessed by WebDAV clients such as the Nextcloud desktop sync client."

Yes, WebDav is working for me generally - I can connect using MacOS Finder's "Connect to Server" feature. But if I go to the same base URL in a browser the above message i given. There's no need for that. WebDAV came with HTTP 1.1 because the people behind Subversion (among others) brought it into the W3C at more than 18 years ago.

Here's a WebDAV enabled resource accessible through a standard web browser :- http://svn.apache.org/repos/asf/subversion/trunk/CHANGES

You see there's no need to legislate against non DAV clients when the method involved is GET.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
