### ISSUE TITLE
occ db:checkxxx for database charset-related info

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#14921]
MySQL/Mariadb has a ton of charset and collation-related functionality that very people understand (well enough). When an installation has charset-related problems, they show up in strange places (e.g. exceptions in the log), and it's hard to know what needs to be fixed and how.

Proposal: create an `occ` sub-command that checks that the database has all the right charset and collation settings in all the right places. That's probably on the database itself, on various columns in various tables, but also in the PHP database client. It should emit a set of instructions for the administrator so getting stuff fixed is as straightforward as possible.

Alternatively, an umbrella-command `occ db:fix-database` (perhaps with a `--dry-run` option) could do this analysis, and perform the fixes, and perhaps others as well. That's obviously more work. Perhaps the first item first?

**Comment by jernst** [comment]
And which "essential informations" would that be?

**Comment by kesselb** [comment]
> And which "essential informations" would that be?

Don't worry. The bot is not working as expected right now. Only issues with the label "needs info" should be tagged stale after a while. Sorry for the noise.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
