### ISSUE TITLE
Insecure Password Reset Mail

### ISSUE THREAD

**Issue by mandeler** [nextcloud/server#14927]
Hi guys,
I was just trying the e-mail password reset feature, works fine. But what causes me considering is the ***username*** just showing up in the end of the reset link. In cases where user email is mistaken or set to wrong address, it will probably cause a big issue exposing user data because anyone who receives the mail can use the ***username*** and reset password to access data. Hope it will be fixed soon.
Thanks for your work, good job.

**Comment by rullzer** [comment]
If somebody gets access to your e-mail then yes. But you can also login with your e-mail.
To have proper protection make sure you have 2fa enabled.
