### ISSUE TITLE
Folder icon color should be the same as the main owncloud theme colour

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#1492]
A small idea I had after changing my main theme colour.
What do you think?

For now I used css masks, but I need to check all browsers for compatibility. If not, a simple svg as img with a fill value could do the trick.

![files](https://cloud.githubusercontent.com/assets/14975046/18747911/0c96025e-80d0-11e6-9677-4171d5cdcf22.gif)

@nextcloud/theming @nextcloud/designers

**Comment by eppfel** [comment]
This is part of the theming app and is currently worked on.

**Comment by eppfel** [comment]
#840

**Comment by MorrisJobke** [comment]
> #840

It's not merged yet -> reopen

**Comment by nickvergessen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/378

**Comment by skjnldsv** [comment]
Ehehe, My bad guys :)

**Comment by jancborchardt** [comment]
@skjnldsv no worries ;D good to see you back again, hope to see more design improvements from you! :)

**Comment by skjnldsv** [comment]
Will think of it ;)
