### ISSUE TITLE
Do not use ID3Parser for too big files

### ISSUE THREAD

**Issue by schenklklopfer** [nextcloud/server#14922]
**Is your feature request related to a problem? Please describe.**
I host a huge number of MP3 containing webradio-rips produced by icecast.
Everytime I open the folder in Nextcloud Serverload goes crazy, Whole system gets unrelieable.
Pages can't be used, needs to restart apache2 and php7.2-fpm.

**Describe the solution you'd like**
Limit filesize of files to be parsed by ID3Parser, like stopping above 50MB.

**Describe alternatives you've considered**
Provide functionality to entirely disable the ID3Parser.

**Additional context**
As workaround I need to modify the lib/private/Preview/MP3.php after eacht update to get rid of this:
`
INSERT ->        public function isAvailable(\OCP\Files\FileInfo $file) { return false; }
`
Use NextCloud 15.0.5
Problem exists since a few months.

**Comment by ChristophWurst** [comment]
Hi,

could you report this at https://github.com/ChristophWurst/ID3Parser please?

Thanks :)

**Comment by schenklklopfer** [comment]
Hello,

done so :)
