### ISSUE TITLE
Group Admin: group members are listed multiple times

### ISSUE THREAD

**Issue by stekaa** [nextcloud/server#14932]
### Steps to reproduce
1. Create some groups
2. Put several users into the groups. Let some users be member in multiple groups
3. Set one special user to group admin of several groups

### Expected behaviour
In Listing of "everyone" each member of each (administered) group should appear and should appear only once.

### Actual behaviour
Some members appear multiple times. This happens if number of members is over ~60 and the displayed list is incomplete. Scrolling will load more data and now some members apper second (third) time.

### Server configuration

**Operating system**: SUSE SLES12

**Web server:** Apache 2.4.23

**Database:** MariaDB 10.0.35

**PHP version:** 7.0.7

**Nextcloud version:** 14.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** updated (since Version 11)

**Where did you install Nextcloud from:** https://nextcloud.com/install/ 

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.1
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - gallery: 18.1.0
  - groupfolders: 2.0.4
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - onlyoffice: 2.1.2
  - password_policy: 1.4.0
  - piwik: 0.5.1
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - theming_customcss: 1.2.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - user_ldap: 1.4.0
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_automatedtagging
  - files_external
  - files_retention
  - firstrunwizard
  - logreader
  - user_external
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com",
            "10.1.1.2",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/example.com",
        "dbtype": "mysql",
        "version": "14.0.8.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "enable_previews": false,
        "default_language": "de",
        "loglevel": 1,
        "log_type": "syslog",
        "syslog_tag": "nextcloud",
        "updater.release.channel": "production",
        "maintenance": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "proxy": "10.1.1.1:8080",
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "14,28",
        "theme": "private",
        "lost_password_link": "disabled",
        "onlyoffice": {
            "verify_peer_off": true
        },
        "auth.bruteforce.protection.enabled": false,
        "memcache.local": "\\OC\\Memcache\\Memcached",
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
it doesn't matter
```
</details>

### Client configuration
**Browser:** Firefox 65.0.1, IE 11

**Operating system:** Windows10, Windows 7

#### Web server error log
<details>
<summary>Web server error log</summary>

```
it doesn't matter
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
it doesn't matter
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
it doesn't matter
```
</details>

**Comment by ccoenen** [comment]
I just created a similar thing, in my case it was a lowercase/uppercase problem

**Comment by skjnldsv** [comment]
Most likely yes.
Please use same casing groups :)
