### ISSUE TITLE
Files app - "Favorite" not displayed in selected language.

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#14933]
## Expected behavior
The 3-dots menu of a file should display all entries in the selected language.

## Current behavior
The "**Favorite**" entry is not translated into German language ("**Favorit**") although a correct translation exists.

![20190402_nc_file_details_translation_of_-Favorite-](https://user-images.githubusercontent.com/2572764/55398043-dec4f700-5547-11e9-856b-1bc4f592c850.png)

## Steps to reproduce
1. Open the files app
2. open the 3-dots menu of a file.

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 15.0.5

#### Client Configuration
Browser: Mozilla Firefox 66.0.2
Operating system: Windows 10

**Comment by skjnldsv** [comment]
Still happening?

**Comment by Nils160988** [comment]
Just re-checked this behavior at 18.0.3 and the mentioned "Favorite"-entry is missing completely. This makes totally sense because there is already the option "Zu den Favoriten hinzufügen" at the top.
Closing?
