### ISSUE TITLE
Moving file (and other actions) invalidate sharing link

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/server#14930]
### Steps to reproduce
1. Share a file from Nextckoud via a link
2. Move or rename that file inside your Nextcloud instance
3. Observe that the link is now broken

### Expected behaviour
The link refers to the file, surviving renames / movements.

### Actual behaviour
Link invalidates, users I have shared it with are left alone.

### Server configuration

**Ubuntu 18.10 (snap)**:

**Where did you install Nextcloud from:**
snap

**Comment by ruedigerkupper** [comment]
There (to my understandig) two ways a sharing link could work:
1. It refers to a file: like a Unix file table link in a directory refers to a file: the link will survive renames, movements and changes of the file content. If the file is removed, the link invalidates.
2. It refers to a special version of a file:it will survive renames and movements of the file. If the file contents changes, it will refer to the contents at the time the link was created. If the file is removed, the link still refers to the version originally shared.

Which one should Nextcloud implement? It appears, Nextcloud currently does not implement either.

**Comment by ruedigerkupper** [comment]
Either way, links once shard should be protected from invalidating. In all cases, the owner must be asked for consent before a shared link is allowed to invalidate.

**Comment by ruedigerkupper** [comment]
Suggestion:
In the sharing dialog, there should be a choice of options:
1. "This link will refer to the file as it is now, and will not reflect future changes."
2. "This link will always refer to the newest version of this file, reflecting future changes."

**Comment by ruedigerkupper** [comment]
I believe that sharing with another Nextcloud user is bound to be option 2?

**Comment by ruedigerkupper** [comment]
Bug ist in state "needs triage". Please state what information is missing.

**Comment by skjnldsv** [comment]
Still a valid issue?

**Comment by ruedigerkupper** [comment]
Sorry for the late answer:
I cannot reproduce the problem any longer, it appears to have been fixed! Thanks!
