### ISSUE TITLE
legacy/image.php No error handling

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#1494]
### Steps to reproduce
1. call loadFromdata($data) with incorrect data
### Expected behaviour

Wrong data is caught; FALSE is returned
### Actual behaviour

PHP fatal error
imagecreatefromstring(): gd-png: fatal libpng error: bad adaptive filter value\n at \/usr\/share\/webapps\/nextcloud\/lib\/private\/legacy\/image.php#598
### Server Configuration

Linux 4.1.31-1
apache 2.4.23-1
mariadb 10.1.16-2
php 7.0.10-1
Nextcloud "version":"9.1.0.16","versionstring":"10.0"
### Details

App "Audio Player"'s scannercontroller => scanForAudios calls $image->loadFromdata($data), which is a NC standard function to transform the image data from your ID3 file info.

lib/private/legacy/image.php breaks at $this->resource = @imagecreatefromstring($str); with a fatal error because something is wrong with the image data.

I think an error handling should be introduced to return FALSE in case of incorrect string-data

Something like 

```
if( imagecreatefromstring( $yourfile ) !== false ) {
    // image is okay.
}
```

Or do you have other suggestions?

**Comment by Rello** [comment]
https://github.com/Rello/audioplayer/issues/57

**Comment by Rello** [comment]
@nickvergessen , @DeepDiver1975 do you think this would make sence here?
I could do the pull - if you would agree to this way of fixing

**Comment by nickvergessen** [comment]
Does that actually solve the issue? You still call the function, which creates the error?

**Comment by Rello** [comment]
I would give it a try and test ist. 
Just wanted to check back if there is a better suggestion

**Comment by MorrisJobke** [comment]
@Rello I will close this for now. 

Thanks

**Comment by Rello** [comment]
Thank you @MorrisJobke 
sorry for not giving feedback. I was testing a little and could not find a proper solution :-(
