### ISSUE TITLE
time difference in logs files

### ISSUE THREAD

**Issue by nirajvara** [nextcloud/server#14948]
Hi,

I have ubuntu 18.04 server and snap nextcloud 15.  
when I checked logs in browserver it shows the time like ...

[files_antivirus] Fatal: OCA\Files_Antivirus\BackgroundJob\BackgroundScanner::run, exception: Cannot connect to "/var/run/clamav/clamd.ctl": Permission denied (code 13)
**at 2019-04-03T15:25:03+00:00**

My system time is  

Wed Apr  3 11:29:32 EDT 2019 

why time difference in log file  ????

**Comment by kesselb** [comment]
I guess `date.timezone` has the wrong value: https://www.php.net/manual/en/timezones.php
Print the current value: `php -i | grep date.timezone`

**Comment by nirajvara** [comment]
Hi
Thnks for reply, see the output 
root@Cloud:~#  php -i | grep date.timezone
date.timezone => no value => no value

this command run on the terminal  of OS .

For snap any other place need to check ?

**Comment by kesselb** [comment]
We use github to manage code and track software issues. You issue is not related to nextcloud itself. Please use our community (https://help.nextcloud.com/) for configuration questions and/or https://github.com/nextcloud/nextcloud-snap for the snap package.

It's required to configure the timezone for php. Thank you :+1:

**Comment by kesselb** [comment]
Sorry I was wrong! There is a configuration option to adjust the timezone used for logs.

https://github.com/nextcloud/server/blob/dd37d3f01e0edc1d88451d99662d4d1f72ba12c2/config/config.sample.php#L813-L819

**Comment by nirajvara** [comment]
Dear Kesselb,

Thank you, It works.
