### ISSUE TITLE
missing space in apps/sharebymail/l10n/de_DE

### ISSUE THREAD

**Issue by TheULi** [nextcloud/server#14945]
apps/sharebymail/l10n/de_DE.js
apps/sharebymail/l10n/de_DE.json

missing space

"%1$s via %2$s" : "%1$s über%2$s",

have to:

"%1$s via %2$s" : "%1$s über %2$s",

**Comment by go2sh** [comment]
You fixed it already. :) The translations get pulled automatically. So, you can close the issue.

**Comment by violoncelloCH** [comment]
thanks for fixing
