### ISSUE TITLE
How to make the same level folder shared only show the parent in the file list system of the person being shared,

### ISSUE THREAD

**Issue by xiejianlong** [nextcloud/server#14957]
How to make the same level folder shared only show the parent in the file list system of the person being shared, and the permission is not only the nearest parent of the top current folder has the sharing permission, but also the nearest parent. If not, inherit the top

**Comment by xiejianlong** [comment]
I need help. Thank you.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years.
