### ISSUE TITLE
ContactsManager TEL field only has one entry

### ISSUE THREAD

**Issue by nerzhul** [nextcloud/server#1495]
### Steps to reproduce
1. Call contacts manager (IContactsManager OCP/Contacts/IManager)
2. $cm->search('', 'FN');

### Expected behaviour
TEL could be and array or TEL or a single str entry. This is a regression this was working properly on owncloud 9.0.0.

This breaks my app behaviour for contact list: ocsms

### Actual behaviour
TEL result for each entry with TEL only has one phone number instead of the whole list

### Server configuration
**Operating system**: FreeBSD 10.3

**Web server:** Apache 2.4

**Database:** PostgreSQL 9.5

**PHP version:** PHP 7.0.10

**Nextcloud version:** 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from Nextcloud 9.0.0

**Where did you install Nextcloud from:** pkg

**Signing status:**

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - documents: 0.13.1
  - external: 1.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - news: 9.0.3
  - notifications: 0.3.0
  - ocsms: 1.9.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - weather: 1.3.3
  - workflowengine: 1.0.1

```
</details>

**The content of config/config.php:**
No interest here

**Are you using external storage, if yes which one:** local/smb/sftp/...
No interest here

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

**Comment by nickvergessen** [comment]
This was fixed for: 
10.0.1: https://github.com/nextcloud/server/pull/1207
9.0.54: https://github.com/nextcloud/server/pull/1208

When `TEL` is available, it will always be an array now (as the doc already stated before), with 1 or more entries.
