### ISSUE TITLE
How do I decrypt user files when I forget the "recover password"？

### ISSUE THREAD

**Issue by LamCheung** [nextcloud/server#14960]
hello,
I've had some problems with nextcloud lately: 
I forgot my recovery password and could not update my private key.
Tried unsuccessfully to decrypt my file using the "sudo -p apache php occ encryption:decrypt <user>" command.Is there any other way to recover my files?
Thanks!

**Comment by tacruc** [comment]
Which kind of encryption are you using? Or have you just lost your login?
If encryption was enabled and you forgot all secrets (recovery key and password), it would be a mayor bug and a big security issue, if your files cloud be recovered, right?

**Comment by LamCheung** [comment]
> 
> 
> Which kind of encryption are you using? Or have you just lost your login?
> If encryption was enabled and you forgot all secrets (recovery key and password), it would be a mayor bug and a big security issue, if your files cloud be recovered, right?

I used defaulatModule to encrypted.
As admin，I loss "admin recovery password"，but key file not loss.
![图片](https://user-images.githubusercontent.com/49282153/55638749-82d5c900-57fa-11e9-892c-27d3153cf3d6.png)

As user for LDAP,it forget old password,so can't change "recovery key password".it only to login and can't use any files.
![图片](https://user-images.githubusercontent.com/49282153/55638794-a13bc480-57fa-11e9-9e53-7b46b46e725a.png)

**Comment by tacruc** [comment]
I'm confused. But maybe it is just me. Their should be two ways to access the files.
One as user where each user has its own password. To decrept his files. 
The second as admin via the admin recovery password where you can recover all files.

So if the second is lost, the users should still be able to access them.

**Comment by violoncelloCH** [comment]
I'm sorry, but if I understand your situation correctly, this is impossible...
also this is a issue (and feature request) tracker, not a support forum... for support take a look at https://help.nextcloud.com or if you're a Nextcloud GmbH customer https://portal.nextcloud.com
