### ISSUE TITLE
Nextcloud doesn't support Fast Web View (Serving ranges of PDF files)

### ISSUE THREAD

**Issue by mattewan** [nextcloud/server#14969]
Nextcloud doesn't support FastWebView for PDF Documents (Page by Page loading of PDFs).

This is a feature that is implemented by PDF.js, although I imagine that the way the PDF is made available to PDF.js means that this feature doesn't work.  For this feature to work, nextcloud would need to be able to serve byte ranges of files.

For digitally born documents that are mostly text, this isn't an issue.  For scanned documents that are mainly images, for example a 50MB 100 page document, the full 50MB must be downloaded before any page can be viewed.

**Comment by j-ed** [comment]
Unfortunately, your report is missing essential information about your environment, used software versions, etc. Could you see the described behavior when the [**Reader app**](https://apps.nextcloud.com/apps/files_reader) has been installed (which still works after patching the version number)?

**Comment by skjnldsv** [comment]
See pdfviewer repository, existing issue
