### ISSUE TITLE
It should be possible to translate for search

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#14964]
It should be possible to translate words in Transifex for the search function:

results are available, use up and down arrow keys to navigate.
No matches found
Please enter or more character
Please delete character
You can only select item
Loading more results…
Searching…

`\core\vendor\core.js`
```
        formatMatches: function (matches) { return matches + " results are available, use up and down arrow keys to navigate."; },
        formatNoMatches: function () { return "No matches found"; },
        formatInputTooShort: function (input, min) { var n = min - input.length; return "Please enter " + n + " or more character" + (n == 1? "" : "s"); },
        formatInputTooLong: function (input, max) { var n = input.length - max; return "Please delete " + n + " character" + (n == 1? "" : "s"); },
        formatSelectionTooBig: function (limit) { return "You can only select " + limit + " item" + (limit == 1 ? "" : "s"); },
        formatLoadMore: function (pageNumber) { return "Loading more results…"; },
        formatSearching: function () { return "Searching…"; },
```
`core\vendor\select2\select2.js`
```
        formatMatches: function (matches) { return matches + " results are available, use up and down arrow keys to navigate."; },
        formatNoMatches: function () { return "No matches found"; },
        formatInputTooShort: function (input, min) { var n = min - input.length; return "Please enter " + n + " or more character" + (n == 1? "" : "s"); },
        formatInputTooLong: function (input, max) { var n = input.length - max; return "Please delete " + n + " character" + (n == 1? "" : "s"); },
        formatSelectionTooBig: function (limit) { return "You can only select " + limit + " item" + (limit == 1 ? "" : "s"); },
        formatLoadMore: function (pageNumber) { return "Loading more results…"; },
        formatSearching: function () { return "Searching…"; },
```

**Comment by nina-py** [comment]
@Valdnet, @skjnldsv, these strings are in an npm package - they shouldn't be translated directly. From [`package.json`](https://github.com/nextcloud/server/blob/969d4312e2a861f7cc69bc76421a695c953fdf11/package.json#L72):

```json
    "select2": "3.5.1",
```

Looking at the README file for that package, I see the following:

> Internationalization (i18n)
> ---------------------------
> 
> Select2 supports multiple languages by simply including the right language JS
> file (`select2_locale_it.js`, `select2_locale_nl.js`, etc.) after `select2.js`.

Would that be possible with the way this and various other packages are bundled in `main.js`?

**Comment by skjnldsv** [comment]
We're slowly removing those select2 dependencies. 
I's actually not used anymore in the sharing sidebar like it used to for example.

I think we can close

**Comment by nina-py** [comment]
Thanks @skjnldsv, one less issue to think about! :+1:
