### ISSUE TITLE
Upgrade from 15.0.5 fails

### ISSUE THREAD

**Issue by janipewter** [nextcloud/server#14976]
### Steps to reproduce
1. Run updater
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 18.04.2

**Web server:** nginx/1.14.2

**Database:** 10.1.38-MariaDB-0ubuntu0.18.04.1 

**PHP version:** 7.3.3-1+ubuntu18.04.1+deb.sury.org+1

**Nextcloud version:** (see Nextcloud admin page) 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** apt

**Signing status:** cannot access as it says "update in process"
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:** can't remember
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:** occ does not exist
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** E2EE on one folder

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome 73

**Operating system:** Windows 10 1809

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
nothing of interest
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

Update to Nextcloud 15.0.6 available. (channel: "production")
Following file will be downloaded automatically: https://download.nextcloud.com/server/releases/nextcloud-15.0.6.zip

Steps that will be executed:
[ ] Check for expected files
[ ] Check for write permissions
[ ] Create backup
[ ] Downloading
[ ] Verify integrity
[ ] Extracting
[ ] Enable maintenance mode
[ ] Replace entry points
[ ] Delete old files
[ ] Move new files in place
[ ] Done

Start update? [y/N] y

Info: Pressing Ctrl-C will finish the currently running step and then stops the updater.

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[ ] Extracting ...PHP Warning:  require(/var/www/nextcloud/updater/../version.php): failed to open stream: No such file or directory in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 642
PHP Fatal error:  require(): Failed opening required '/var/www/nextcloud/updater/../version.php' (include_path='.:/usr/share/php') in phar:///var/www/nextcloud/updater/updater.phar/lib/Updater.php on line 642

**Comment by cantaeus** [comment]
Hi @janipewter , I have the exact same problem, exact same error on the same line. Did you figure it out?

**Comment by janipewter** [comment]
> Hi @janipewter , I have the exact same problem, exact same error on the same line. Did you figure it out?

Yes in the end I did. In my case it appeared a lot of files were missing, including occ. I'm not sure if this was as a result of the failed upgrade or some other problem with my install which was otherwise working perfectly until I attempted this update. I grabbed a fresh zip of the latest version of Nextcloud from the website, and uploaded the files to my server, overwriting existing files (nothing important gets destroyed). Then I removed the backup folder, disabled the E2EE app for good measure (this step may not be required), and ran the upgrade from the command line. It went through no problem.

**Comment by cantaeus** [comment]
I finally did the same without taking care of the E2EE (I was terrified though). Had some issues connecting with clients (Android, iOS, MacOS), it turned out .htaccess file wasn't copied during the overwrite with the last version (.something files are hidden by default on MacOS).

But the bug is real. For me it was :

1. Nextcloud 15.0.4 updated via the web interface to 15.0.5 without problems
2. Upgrade tentative via the web interface from 15.0.5 to 15.0.7 (should have done a db and htdocs backup here and disabled external apps including E2EE here)
3. Got stuck on various stages with various errors
4. Thought I was going to die

Fix (dirty but functional)
1. Realized that a LOT of files were missing from the nextcloud htdocs root compared to the lastest .zip nextcloud content
2. Downloaded the lastest .zip package from Nextcloud site, checked integrity etc
3. Overwrite everything in the right place
4. double checked the .htaccess and others .xxx files missing + config fixesfrom the web / configuration / global overview
5. survived but extremely worried now about updating the thing now.

This upgrade procedure is incredibly far from plug and play, as it should be on v15 and +

**Comment by violoncelloCH** [comment]
possibly related: #15133
cc @MorrisJobke

**Comment by skjnldsv** [comment]
Hi everyone!
Thanks for reporting this issue!

Where you all using the web updater?
Since we're at 15.0.8, did you upgrade since?
Was there any issues?

**Comment by tufu9441** [comment]
I have encountered the same problem when trying to upgrade from 17.0.3 to 18.0.3, and still cannot solve now after  following the steps above mentioned. Here is the error info:

[✔] Check for expected files
[✔] Check for write permissions
[✔] Create backup
[✔] Downloading
[✔] Verify integrity
[ ] Extracting ...PHP Warning:  require(../nextcloud/updater/../version.php): failed to open stream: No such file or directory in phar:///../nextcloud/updater/updater.phar/lib/Updater.php on line 658
PHP Fatal error:  require(): Failed opening required '../nextcloud/updater/../version.php' (include_path='.:/usr/share/php') in phar:///../nextcloud/updater/updater.phar/lib/Updater.php on line 658

**Comment by janipewter** [comment]
Take a backup of your current install, download 18.0.3 zip from the Nextcloud website and extract it into your directory and then try to run the updater. This is how I eventually fixed it.

What I believe happens is the updater removes files while it's going but if the update fails the files are gone so you can'd do the update again.

**Comment by tufu9441** [comment]
> Take a backup of your current install, download 18.0.3 zip from the Nextcloud website and extract it into your directory and then try to run the updater. This is how I eventually fixed it.
> 
> What I believe happens is the updater removes files while it's going but if the update fails the files are gone so you can'd do the update again.

I think what you believe is right, however some files have already missed such as occ, so I cannot take a complete backup of the current install, and there is always a "Update in progress" when visiting the nextcloud index. At last I have to remove the current folder and re-install the latest version, and finally it can work now. 😂
