### ISSUE TITLE
After upgrading to 14.0.9, subfolders do not open in external shares.

### ISSUE THREAD

**Issue by lvarnava** [nextcloud/server#14977]
After upgrading to 14.0.9, subfolders do not open in external shares.
Nextcloud 14.0.8.2 - 14.0.9
ubuntu 18.04.1
postgresql 10.6
apache 2.4.29
php 7.2.15

**Comment by lvarnava** [comment]
same problem here #14962

**Comment by kesselb** [comment]
Thank you! Duplicate of #14962
