### ISSUE TITLE
 path needs to be relative to the system wide data folder and point to a user specific file

### ISSUE THREAD

**Issue by fs1605** [nextcloud/server#14988]
We have been using the file upload in the groupfolder for some time now. Today's update to version 15.0.6. did not solve the problem.

if we want to upload a file to a group folder the error message appears:

"path needs to be relative to the system wide data folder and point to a user specific file"

after the second try, it usually works.

someone a solution?

yes, encryption is on.

**Comment by lordTobiHD** [comment]
I also have the error with the CLI command encryption:encrypt-all.
I'm using the default encryption module.

**Comment by ukrainer8** [comment]
I have the same problem (path needs to be relative to the system wide data folder and point to a user specific file) + problems:
- (Sabre\DAV\Exception\Forbiden)
- Invalid argument

Do anybody have an idea how to solve them?
Server version 16.0.4, client version 2.5.3. The most files are synced properly, but about 10% of them have these problems...

![1](https://user-images.githubusercontent.com/54291988/63301496-591dca00-c2e3-11e9-905f-c31f7d76198a.JPG)
![2](https://user-images.githubusercontent.com/54291988/63301710-e7924b80-c2e3-11e9-9b65-a5045344bb17.JPG)
![3](https://user-images.githubusercontent.com/54291988/63301711-e7924b80-c2e3-11e9-8194-42af725d4af0.JPG)
![4](https://user-images.githubusercontent.com/54291988/63301712-e7924b80-c2e3-11e9-92dc-199bc5c34d4d.JPG)
![5](https://user-images.githubusercontent.com/54291988/63301713-e82ae200-c2e3-11e9-8786-622e922c9ba8.JPG)

**Comment by phonon112358** [comment]
I have the same issue with NC 18.0.1, group folders 6.0.1 and encryption enabled (default encryption module 2.6.0)... 

Any solution???

**Comment by LukasSchulz** [comment]
Is there a way to disable encryption for the group folders?
Because as it is now it just isn't useable for the end user.
To actually see an uploaded or created file, the user needs to create or upload it twice....
Thank you for any help.

**Comment by Micromegass** [comment]
Same problem for me. Uploading twice works, which is not a solution though

**Comment by SB97** [comment]
Same problem NC 18.0.3
with Group folders 6.0.6 and Default encryption module 2.6.0

After a update also on NC 18.0.4

**Comment by insanity54** [comment]
I had this issue on NC 18.0.4 with Group folders 6.0.5.
I worked around the issue by completely disabling encryption in Nextcloud.

## Step 1-- Disable server side encryption

The following picture shows how it should look on the `.../settings/admin/security` page.
![Screenshot_2020-04-24 Settings](https://user-images.githubusercontent.com/670375/80244424-bb229200-861d-11ea-8511-47df2cd54303.png)

```
occ maintenance:mode --on
occ encryption:disable
occ:maintenance:mode --off
```

I had to do this process twice. The first time I did this, the command completed successfully, but the checkbox in `.../settings/admin/security` still showed checked until I ran the three occ commands again.

## Step 2-- Disable encryption app

I read about this from another issue in this issue tracker. I would link it if I could find it, but I can't find the issue again. It wasn't enough to disable server side encryption, I actually had to completely disable the Default encryption module before I stopped getting the error.

![Screenshot_2020-04-24 Apps](https://user-images.githubusercontent.com/670375/80245841-46048c00-8620-11ea-9bdd-8f0539425b71.png)

**Comment by SB97** [comment]
> I read about this from another issue in this issue tracker.

@insanity54 
Maybe https://github.com/nextcloud/groupfolders/issues/71 ?

**Comment by insanity54** [comment]
> Maybe [nextcloud/groupfolders#71](https://github.com/nextcloud/groupfolders/issues/71) ?

No that's not the one I was thinking of. That comment mentions disabling encryption in the home folder, but the comment I'm thinking of mentions disabling the encryption app. I'm still looking for it, I'll post again when I find it.

**Comment by Micromegass** [comment]
Idk if that helps anyone, but in my case disabling encryption is not an option. I ditched the group folder app completely. Then I create a user group with the admin account and add all users of my choice to the specific group. The I simply share the folder with the particular group. I know there is some behavioural difference to what could be achieved with the group folders, but for me it was sufficient. And I can keep encryption. 

In https://github.com/nextcloud/groupfolders/issues/71 they say that a new release will properly disable encryption for group folders, which I don't think is a solution, since the encryption becomes obsolete in the first place.

**Comment by void-arch** [comment]
Same here on NC 18.0.4 in a docker stup with enabled encryption and groupfolders.

I tried to
 - Share access to a folder with public link to a new user, from there copy/move this public folder to a new private one - failed.
 - Copy this public folder somewhere else - failed
 - Copy/move this public folder to a groupfolder. Thats where I got the most telling logs:

![Move to groupfolder](https://user-images.githubusercontent.com/63976048/82764730-4d7ea700-9e11-11ea-93be-4f2bbf9e2be6.png)

**Comment by Michaelis90** [comment]
i don't know if the problem is still current, but i had the same problem.
but I solved (or bypassed) it.
i integrated the nextcloud in windows explorer as a network drive (webdav) and then moved my folders and files to the shared folder.
But I don't know why it works like that.
I hope I could help.

Nextcloud 18.0.7.1
Group folders 6.0.6
Default encryption module 2.6.0
encryption is on

**Comment by oszilloskop** [comment]
Same problem here. File uploading twice works, which is not a solution though.

Nextcloud 19.0.3
Group folders 7.0.0
Default encryption module 2.7.0
encryption is on

**Comment by gchaincl** [comment]
Same problem here on nextcloud: 19.0.4.2, group folders:  7.1.0 and Default Encryption module:  2.7.0

**Comment by govbetrieb** [comment]
Same here. Double upload/delete is working.

**Comment by strongboy54** [comment]
> Idk if that helps anyone, but in my case disabling encryption is not an option. I ditched the group folder app completely. Then I create a user group with the admin account and add all users of my choice to the specific group. The I simply share the folder with the particular group. I know there is some behavioural difference to what could be achieved with the group folders, but for me it was sufficient. And I can keep encryption.
> 
> In [nextcloud/groupfolders#71](https://github.com/nextcloud/groupfolders/issues/71) they say that a new release will properly disable encryption for group folders, which I don't think is a solution, since the encryption becomes obsolete in the first place.

This is the solution I believe works best. It's not a perfect collab solution, but it's certainly a preference seeing as you can keep encryption. Thanks!
