### ISSUE TITLE
Russian names of folders and files corrupted

### ISSUE THREAD

**Issue by andrewgs67** [nextcloud/server#14981]
When I create the new folder which name begins with russian word and them share it, such folder displays for other users without first word.
For example, If I create folder with name “Папка уровень 1” (“Folder level 1”), users see it as “уровень 1” ("level 1). For files same effect.
Same time, all subfolders with russian names displayed correctly.
For Folder creator all names showes correctly.

### Steps to reproduce
1. Create folder with name on Russian. The name must contain at least two words separated with space.
2. Share folder with other user.
3. Login under other user and see that first word of shared folder is absent - folder name contain only second word. But on bottom level of shared folder all name showes correctly.

### Expected behaviour
Folder names on Russian langauge must shoewes correctly for other users.

### Actual behaviour
First word of multiword folder names is truncated.

### Server configuration

**Operating system**: CentOS 7 x64 1810

**Web server:** Apache 2.4.38

**Database:** MariaDB 5.5.6

**PHP version:** 7.2.14

**Nextcloud version:** (see Nextcloud admin page) 15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 15.00

**Where did you install Nextcloud from:** Official page

**Signing status:**
critical
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found..
```
</details>

**List of activated apps:**
Files Right Click
Accessibility
Activities for shared file downloads, visible to all admins
Activity
Announcement center
Auditing / Logging
Collaborative tags
Comments
Deleted files
Federation
File access control
File sharing
First run wizard
Gallery
Group folders
LDAP user and group backend
Log Reader
Monitoringе
Nextcloud announcements
Notifications
Password policy
PDF viewer
Quota warning
Retention
Share by mail
Support
Text editor
Theming
Update notification
Usage survey
Versions
Video player
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "fs.ctdl.ru"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.5.3",
        "overwrite.cli.url": "https:\/\/fs.ctdl.ru",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "maintenance": false,
        "logfile": "\/var\/www\/html\/nextcloud\/data\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": 1,
        "logdateformat": "Y-m-d H:i:s",
        "logtimezone": "Europe\/Moscow",
        "trashbin_retention_obligation": "auto, 5",
        "enable_previews": false
    }
}

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
ActiveDirectory
#### LDAP configuration (delete this part if not used)
<details>
<summary>
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                                                |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                                  |
| homeFolderNamingRule          |                                                                                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                                  |
| ldapAgentName                 | CN=s-ldap_auth,CN=Users,DC=example,DC=com                                                                                                                                                             |
| ldapAgentPassword             | ***                                                                                                                                                                                                |
| ldapAttributesForGroupSearch  | cn                                                                                                                                                                                                 |
| ldapAttributesForUserSearch   | samaccountName                                                                                                                                                                                     |
| ldapBackupHost                | dc2.example.com                                                                                                                                                                           |
| ldapBackupPort                | 389                                                                                                                                                                                                |
| ldapBase                      | DC=example,DC=com                                                                                                                                                                                     |
| ldapBaseGroups                | OU=Security groups,DC=example,DC=com                                                                                                                                                                  |
| ldapBaseUsers                 | CN=Users,DC=example,DC=com;OU=ExternalUsers,DC=example,DC=com;OU=Contacts,DC=example,DC=com                                                                                                                 |
| ldapCacheTTL                  | 600                                                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                                                  |
| ldapDefaultPPolicyDN          |                                                                                                                                                                                                    |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                                    |
| ldapEmailAttribute            | mail                                                                                                                                                                                               |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       | cn                                                                                                                                                                                                 |
| ldapExpertUUIDUserAttr        | samaccountName                                                                                                                                                                                     |
| ldapExpertUsernameAttr        | samaccountName                                                                                                                                                                                     |
| ldapGidNumber                 | gidNumber                                                                                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                                                                                                 |
| ldapGroupFilter               | (|(cn=groupname))                                                                                                                                                                            |
| ldapGroupFilterGroups         | groupname                                                                                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                                                                                    |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                                             |
| ldapHost                      | dc1.example.com                                                                                                                                                                           |
| ldapIgnoreNamingRules         |                                                                                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=person))(!(UserAccountControl:1.2.840.113556.1.4.803:=2))(|(|(memberof=CN=groupname,OU=Nextcloud,OU=Services,OU=Security groups,DC=example,DC=com))))(samaccountname=%uid))  |
| ldapLoginFilterAttributes     |                                                                                                                                                                                                    |
| ldapLoginFilterEmail          | 0                                                                                                                                                                                                  |
| ldapLoginFilterMode           | 1                                                                                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                                  |
| ldapNestedGroups              | 1                                                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                                                                                |
| ldapPort                      | 389                                                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                                                  |
| ldapUserAvatarRule            | default                                                                                                                                                                                            |
| ldapUserDisplayName           | name                                                                                                                                                                                               |
| ldapUserDisplayName2          |                                                                                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=person))(!(UserAccountControl:1.2.840.113556.1.4.803:=2))(|(|(memberOf:1.2.840.113556.1.4.1941:=CN=groupname,OU=Nextcloud,OU=Services,OU=Security groups,DC=example,DC=com)))) |
| ldapUserFilterGroups          | groupname                                                                                                                                                                                    |
| ldapUserFilterMode            | 1                                                                                                                                                                                                  |
| ldapUserFilterObjectclass     | person                                                                                                                                                                                             |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                                                               |
| turnOffCertCheck              | 1                                                                                                                                                                                                  |
| turnOnPasswordChange          | 0                                                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 60.5.1 ESR
**Operating system:**
MS Windows 10 x64 1803 Standard Rus
[error_log.zip](https://github.com/nextcloud/server/files/3052002/error_log.zip)
[nxt.zip](https://github.com/nextcloud/server/files/3052003/nxt.zip)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by iampikus** [comment]
Hello. We have the same issue with cyrillic shared folder names.
There is something related with _**oc_share**_ table.

1) Create folder with cyrillic symbols and share with another user
2) query **_oc_share_** table and see that field **_file_target_** contains full folder name as it should be
3) log in as another user  and see that folder name missing first word.
4) query **_oc_share_** table and see that field **_file_target_** contains truncated folder name.

Why it is happening?

**Comment by iampikus** [comment]
There is no problems if you added any ASCII character before cyrillic ones...

**Comment by iampikus** [comment]
Any suggestions? =) We use latest 18.0 version

**Comment by iampikus** [comment]
Still have problem in 18.0.1 + tags not working...

**Comment by iampikus** [comment]
Still have problem in 18.0.2
Tags is working now.

**Comment by kesselb** [comment]
Might be related: 
https://github.com/nextcloud/server/issues/12318
https://bugs.php.net/bug.php?id=62119

**Comment by iampikus** [comment]
Just upgraded to 18.0.3, problem still exists
:(

**Comment by vboev** [comment]
19.0 still not work

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by andrewgs67** [comment]
Hello.
I do not using nextcloud now.
I mean this case can be closed.
Thanks,
Best regards,
Andrew

вт, 8 июн. 2021 г., 13:22 szaimen ***@***.***>:
