### ISSUE TITLE
Please stop admin notifications at 3 o'clock in the morning

### ISSUE THREAD

**Issue by inf0rmix** [nextcloud/server#14999]
Dear nextcloud team,
would it be possible to get nextcloud to not inform me about app updates too early in the morning ?

At three times in the last month I had a notification at approx. 3 o'clock that an app is able to update.A feature to delay warnings until the morning hours would be nice!

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Well actually I would want to exactly do it only in the night, to avoid additional load during normal usage times.

I would recomment setting DND on your phone instead, to avoid vibrating there, and after you got up you can update your apps.

Adding a second level of background jobs to push the notifications out later is too much overhead and risk for such a small feature.
