### ISSUE TITLE
Preview route(endpoint) for videos

### ISSUE THREAD

**Issue by aosyatnik** [nextcloud/server#14991]
**Is your feature request related to a problem? Please describe.**
Good day, nextcloud developers!
So, here I should describe my problem or feature request. Fine...

I'm trying to develop some app for nextcloud, running in [UCS](https://www.univention.com/products/ucs/). I do not have any access to nextcloud server directly, because it's running in docker container and installed by ucs user. So NO direct access to nextcloud server.

That's what I see:
![image](https://user-images.githubusercontent.com/8158404/55722332-3c54ba00-5a06-11e9-8098-834ee5a15882.png)

I like this previews for images (small images). And what I like the most, I can get this preview by using this url: https://foobar.com/nextcloud/core/preview?fileId=4
![image](https://user-images.githubusercontent.com/8158404/55722377-673f0e00-5a06-11e9-8922-b9715a2563cd.png)

According to this arcticle previews are also available for videos, images and text documents:
https://docs.nextcloud.com/server/14/admin_manual/configuration_files/previews_configuration.html

But I couldn't find link for videos previews.

**Describe the solution you'd like**
I want some link, like https://foobar.com/nextcloud/core/preview?fileId=9, where 9 is id of video file.

**Describe alternatives you've considered**
It can be any other link, but the main idea: I want to get preview of video.

**Additional context**
@skjnldsv, you helped me a lot last time. Maybe I've missed something? Maybe this preview route/endpoint has been already implemented and I just overlooked it? Thanks!

**Comment by skjnldsv** [comment]
@rullzer ? :D

**Comment by skjnldsv** [comment]
Please have a look at https://www.allerstorfer.at/nextcloud-install-preview-generator/.
It looks like a nice article on how to get mp4 previews :)
