### ISSUE TITLE
Forbiddibg delete in a shared folder disables move within this folder

### ISSUE THREAD

**Issue by grzesiooo** [nextcloud/server#14993]
Forbidding users or group of users to delete files from a shared folder, makes them unable to move files around this particular folder. This makes it very difficult to organize files in a shared folder.

**Comment by violoncelloCH** [comment]
this is intended behaviour, because recipients could otherwise actually delete files for the owner by moving them out of the directory...

**Comment by grzesiooo** [comment]
I understand that moving files out of shared folder is essentially deleting them from the perspective of the owner. That's why i specifically used the words "**within**" and phrase "**this particular folder**".

**Comment by violoncelloCH** [comment]
hmm, I see...
@nextcloud/sharing what do you think? would it be possible to still allow moving within the shared directory?

**Comment by skjnldsv** [comment]
I think this is a job for another app, not sharing.
You need to be in control of what files you have in your home.
check the groupfolder app or the files_external app, you can achieve mounting dedicated folders or maybe get close to what you want
