### ISSUE TITLE
Enable VJOURNAL for CalDav calendars

### ISSUE THREAD

**Issue by ThaChillera** [nextcloud/server#14992]
**Is your feature request related to a problem? Please describe.**
When using Evolution Mail client, it says I can synchronizes memos (notes) using the CalDav format. According to [this forum post](https://help.nextcloud.com/t/synchronazing-notes/1676/8), supporting this requires modifying the database entry of a calendar slightly.

**Describe the solution you'd like**
The ability to synchronise notes using the CalDav standard.

**Describe alternatives you've considered**

**Additional context**

**Comment by ShapeShifter499** [comment]
Any updates with this?

**Comment by georgehrke** [comment]
The Nextcloud CalDAV server supports VJournal. If you want a calendar that supports VJournal, just create it on your local client.

We had plenty of discussions about the default components of calendars before and decided that calendars created by the calendar app should only support VEVENT. Nevertheless that doesn't stop you from creating calendars supporting all components with your local client.

**Comment by georgehrke** [comment]
> According to this forum post, supporting this requires modifying the database entry of a calendar slightly.

If you want to add VJOURNAL support to an existing calendar, just take a look at the table `oc_calendars` and alter the value of components from `VEVENT` to `VEVENT,VJOURNAL`.

**Comment by StefanoWoerner** [comment]
This seems like an unsatisfactory solution, since it is impossible for (non-admin) users to enable VJOURNAL support. What's the reason for excluding VJOURNAL anyway?

**Comment by foss-** [comment]
> This seems like an unsatisfactory solution, since it is impossible for (non-admin) users to enable VJOURNAL support. What's the reason for excluding VJOURNAL anyway?

I would like to know this as well. Can this question be answered? Is VJOURNAL known to cause problems? Are those potential problems documented somewhere?

**Comment by towo** [comment]
Speaking out of the blue here, it's probably just done because the impact to client applications is unknown, and since the userbase for `VJOURNAL` is fairly small, it's a tradeoff in usability for some vs preventing unknown errors popping up for others.

There probably should be a separate issue to allow managing calendar components in the personal settings or something.
