### ISSUE TITLE
occ takes any value starting with hyphen as a command-line switch 

### ISSUE THREAD

**Issue by paualberto** [nextcloud/server#15008]
This should not happen when the value is quoted:

### Steps to reproduce
1. `./occ config:app:set files testkey --value '-a'`
OR  
1. `./occ config:app:set files testkey --value "-a"`
OR  
1. `./occ config:app:set files testkey --value \-a`
OR  
1. `./occ config:app:set files testkey --value -a`

### Expected behaviour
`Config value testkey for app files set to -a`

### Actual behaviour
`The "--value" option requires a value.`

(quoting strings such as `\"-a\"` causes them to end up inside the value.)  
**NOTE**: I needed this to set the x509 certificates and private keys for the SAML app programmatically with OCC. Since certs and keys start with "---". I ended up writing in the database directly, but it's not a great workaround.

### Server configuration

**Operating system**: Ubuntu 18.04

**PHP version:** 7.2.15-0ubuntu0.18.04.2

**Nextcloud version:** 15.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-15.0.5.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by kesselb** [comment]
`./occ config:app:set files testkey --value="-a"`

**Comment by paualberto** [comment]
Thanks!
