### ISSUE TITLE
Web UI - links in Shares section not working

### ISSUE THREAD

**Issue by rtheys** [nextcloud/server#15018]
Hi,

When a user has shared a folder with you and you try to open it in the web UI in the 'Shares' section it fails to open the folder.

When the 'Shares' menu is opened and 'Shared with you' is selected, the shared folders do open.

The same happens for items you've shared with others.

Folders don't open if you go through the 'Shares' section. They do work if you use a submenu of the 'Shares' section.

Regards,
Rik

### Steps to reproduce
1. Have someone share a folder with you
2. Log in on the web UI and click the 'Shares' item on the left.
3. Click on the shared folder

### Expected behaviour
The content of the shared folder should be displayed

### Actual behaviour
The content of the folder is not displayed and the content remains the content after clicking 'Shares'.

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older versions

**Where did you install Nextcloud from:**
Website

**Comment by tiiiecherle** [comment]
We do have the same problem with nextcloud 15.0.6. Don't know about 15.0.7 as it is not available on archlinux yet. All other packages up-to-date, used with nginx, php and mariadb.

**Comment by tiiiecherle** [comment]
Seems to be solved in 15.0.7 for us. Thanks

**Comment by violoncelloCH** [comment]
@rtheys please check if this is solved for you too with 15.0.7... otherwise we can reopen this issue :)
