### ISSUE TITLE
different external usernames after migration

### ISSUE THREAD

**Issue by ayushin** [nextcloud/server#15012]
Hi,
This is regarding Nextcloud-15.0.6 I've migrated my instance and for some reason my external backend '0 => '{mail:993/imap/ssl}' gives me a wrong password error, but what works is this:
```
      array (
        0 => 'mail',
        1 => 993,
        2 => 'ssl',
        3 => '',
      ),
```

Now the problem that with the old backend I had usernames like `7354fb01-282c11e6-8981c441-1281f40c` and with the new one I get usernames like `user@email.domain` so all the user data is lost.

Any ideas how I can rename my old users in the `7354fb01-282c11e6-8981c441-1281f40c` to `user@domain` so that they can keep their data (files cache, calendars, contacts and shared files) or how to keep the old usernames?

mysql/php scripting not a problem

**Comment by violoncelloCH** [comment]
this probably belongs to the nextcloud/user_external repository...
that you had to change your config is due to nextcloud/user_external#49 ...
however I don't get why you had these long random strings as usernames before... this more looks like a LDAP UUID to me...

**Comment by ayushin** [comment]
ah you are actually right! i migrated from LDAP to IMAP before but the UUIDs stayed, then I migrated from postgresql to mysql and now to the new IMAP and that's when it stopped working.

The question remains though: how to migrate data (contacts, calendars, filecache, sharing info) from the UUID users to the new users?

**Comment by ayushin** [comment]
nextcloud transfer data to another user

**Comment by ayushin** [comment]
is there an analogue for `occ files:transfer_ownership` for calendars and address book?

**Comment by violoncelloCH** [comment]
hmm, not one that I'm aware of...
If so it would be documented here: https://docs.nextcloud.com/server/16/admin_manual/configuration_server/occ_command.html

the thing is that "migrating" your users this way between different backends is not supported at all (you're actually lucky, that it worked before)... 

What you actually could do if you have some experience with databases is to manually rename the users in all places... however you would have to make really sure you do everything the correct way, otherwise you could destroy even more...

**Comment by ayushin** [comment]
Yes I solved it by dumping the database and replacing one username with another for all users as text and then reloaded the file. It worked.

**Comment by violoncelloCH** [comment]
Ohh, nice that you could fix it!
is there anything remaining or can we close this issue?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
