### ISSUE TITLE
Suggestion: Add a 3-days-before reminderf or contact birthdays

### ISSUE THREAD

**Issue by sbrl** [nextcloud/server#15024]
**Is your feature request related to a problem? Please describe.** As a user, I have friends and family in my contacts. The reminder on the day of their birthday is helpful, but it doesn't leave me with any time to find a card and/or present for them.

**Describe the solution you'd like**

I propose that an additional reminder 3 days before a contact's birthday is added to the contact birthday event.

In this way, it will be more useful as I will then receive enough notice to get them a birthday card.

**Describe alternatives you've considered**

I could add a duplicate event manually, but this is hard to maintain and results in duplicate events on my calendar.

I can't edit the existing event, as it's generated automatically by Nextcloud.

I could write a program that generates an ical from my contacts list (then I'd have control over the notifications), but this would also produce duplicate events - and would be significantly complicated. It feels rather like reinventing the wheel to be honest....

**Additional context**

Here's a screenshot showing that I can't edit the reminders:
![Selection_144](https://user-images.githubusercontent.com/9929737/55803581-8a36f400-5ad2-11e9-9710-e7e547d4f366.png)

**Comment by evanrich** [comment]
Instead of a hard-coded 3 days, other should be configurable.  Maybe some people want 1 day, some might want 7 days, others might want 2weeks.  3 days is too narrow of a use case

**Comment by violoncelloCH** [comment]
cc @nextcloud/contacts and @nextcloud/calendar

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/issues/1505#issuecomment-256093258
