### ISSUE TITLE
[15.0.7] Integrity check failed vendor/arthurhoaro

### ISSUE THREAD

**Issue by crazy-max** [nextcloud/server#15026]
### Steps to reproduce
1. Upgrade to 15.0.7
2. Go to Settings > Overview

### Expected behaviour

Integrity check should be ok :upside_down_face:

### Actual behaviour

![image](https://user-images.githubusercontent.com/1951866/55828014-caff2f00-5b0b-11e9-9fc8-ef88023b7a4c.png)

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- news
	- EXTRA_FILE
		- vendor/arthurhoaro/favicon/resources/cache/urlcfdc18516d4905c0a217e3a2c24ffdcc
		- vendor/arthurhoaro/favicon/resources/cache/urla1f4f0bae0e2bf53f3231975b69917be

Raw output
==========
Array
(
    [news] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [vendor/arthurhoaro/favicon/resources/cache/urlcfdc18516d4905c0a217e3a2c24ffdcc] => Array
                        (
                            [expected] => 
                            [current] => 649651069e8bb8a65aec075ad098c9976ebfd76d1aa2406223a97dcc01813e18e167814a26e259cfa02834ef562e323b90a5101d26351a17e240b1b7e728e0e5
                        )

                    [vendor/arthurhoaro/favicon/resources/cache/urla1f4f0bae0e2bf53f3231975b69917be] => Array
                        (
                            [expected] => 
                            [current] => 45c5451997b008560b8d4878356c3a1a569fbb653fda50b815df83ab558e6793ec3498235b78d38bd6546e3f41e827c5b6aa0c0db2dd90ba2168fe08cc105c6f
                        )

                )

        )

)
```

### Server configuration

**Operating system**: Alpine 3.9 (Docker)

**Web server:** Nginx

**Database:** MariaDB 10.2 (Docker)

**PHP version:** 7.2.14

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from 15.0.6

**Where did you install Nextcloud from:** https://github.com/crazy-max/docker-nextcloud

**Comment by kesselb** [comment]
https://github.com/search?q=arthurhoaro+org%3Anextcloud&type=Code

Looks like a dependency for news or mail app. Do you have one of them enabled?

**Comment by crazy-max** [comment]
@kesselb News enabled indeed!

**Comment by crazy-max** [comment]
Ok this issue already exists : nextcloud/news#484
