### ISSUE TITLE
Exception: files can't be disabled during upgrading from OC 9 to NC 10.0

### ISSUE THREAD

**Issue by Rowin** [nextcloud/server#1503]
### Steps to reproduce
1. From a OC instance in 9.1.1 deleting all files except /data and /config directories
2. Upload all files from the latest stable version archive (except /config)
3. Accessing server root and running the update

### Actual behaviour
The upgrade screen return an exception : files can't be disabled with the following logs : 

>Preparing update
>Set log level to debug
>Turned on maintenance mode
>Checking whether the database schema can be updated (this can take a long time depending on >the database size)
>[1 / 27]: Checking table oc_appconfig
>[2 / 27]: Checking table oc_storages
>[3 / 27]: Checking table oc_mounts
>[4 / 27]: Checking table oc_mimetypes
>[5 / 27]: Checking table oc_filecache
>[6 / 27]: Checking table oc_group_user
>[7 / 27]: Checking table oc_group_admin
>[8 / 27]: Checking table oc_groups
>[9 / 27]: Checking table oc_preferences
>[10 / 27]: Checking table oc_properties
>[11 / 27]: Checking table oc_share
>[12 / 27]: Checking table oc_jobs
>[13 / 27]: Checking table oc_users
>[14 / 27]: Checking table oc_authtoken
>[15 / 27]: Checking table oc_bruteforce_attempts
>[16 / 27]: Checking table oc_vcategory
>[17 / 27]: Checking table oc_vcategory_to_object
>[18 / 27]: Checking table oc_systemtag
>[19 / 27]: Checking table oc_systemtag_object_mapping
>[20 / 27]: Checking table oc_systemtag_group
>[21 / 27]: Checking table oc_privatedata
>[22 / 27]: Checking table oc_file_locks
>[23 / 27]: Checking table oc_comments
>[24 / 27]: Checking table oc_comments_read_markers
>[25 / 27]: Checking table oc_credentials
>[26 / 27]: Checking table oc_admin_sections
>[27 / 27]: Checking table oc_admin_settings
>Checked database schema update
>Checking updates of apps
>Checked database schema update for apps
>Updating database schema
>Updated database
>Exception: files can't be disabled.

### Server configuration
**Operating system**:
Debian 8 (shared hosting)

**Web server:**
Nginx and Apache 2.4

**Database:**
MySQL

**PHP version:**
5.6.24

**Nextcloud version:** (see Nextcloud admin page)
Something between OC 9.1.1 and NC 10.0.0 

**Updated from an older Nextcloud/ownCloud or fresh install:**
An older ownCloud (9.1.1)

**Where did you install Nextcloud from:**

**Signing status:**
Can't access

**List of activated apps:**
I purge the apps folder before update, so.

**The content of config/config.php:**

```<?php
$CONFIG = array (
  'instanceid' => 'ocd8310f8176',
  'passwordsalt' => 'c2ca1a2ace8491dc01cd908caaa6b9',
  'trusted_domains' => 
  array (
    0 => 'cloud.anhydride-acide.fr',
  ),
  'datadirectory' => '/home/httpd/r/o/w/rowin/cloud.anhydride-acide.fr/data',
  'dbtype' => 'mysql',
  'dbname' => '',
  'dbuser' => '',
  'dbpassword' => '',
  'dbhost' => 'sql.franceserv.fr',
  'dbtableprefix' => 'oc_',
  'version' => '9.1.1.3',
  'installed' => true,
  'forcessl' => true,
  'maintenance' => false,
  'theme' => '',
  'share_folder' => '/Shared',
  'loglevel' => 0,
  'trashbin_retention_obligation' => '15',
  'appstoreenabled' => true,
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'php',
  'mail_domain' => 'anhydride-acide.fr',
  'secret' => '',
  'appstore.experimental.enabled' => false,
  'updater.secret' => '',
);
```
**Are you using external storage, if yes which one:** local/smb/sftp/...
FTP

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Webdav, usually

### Client configuration
**Browser:**
Firefox 48.0

**Operating system:**
Debian 8.0 Jessie

**Comment by oparoz** [comment]
Can you tell us more about: "I purge the apps folder before update, so." ?

You cannot remove or disable apps before an upgrade.

**Comment by Rowin** [comment]
You're right, I wrote too quickly !
I'm not sure how to get the list of apps. Can you tell me how to get this list (without access to the command line) ?

**Comment by oparoz** [comment]
Without access to the command line, you then need to log into your Nextcloud and click on the + sign in the list of apps. There you can see what has been enabled.

Now if you can't access Nextcloud, then there is no other solution that using the command line.

I would also check the permission of your files, it could be that some are missing and interfering with the upgrade process.

**Comment by Rowin** [comment]
I get back to my old Owncloud installation, thanks to my backup. So I have Activity, Collaborative tags, Comments, Deleted files, Federation, First run wizard, Gallery, Mail Template Editor, Notifications, PDF viewer, Provisioning API, Share files, Text editor, Update notifications, Versions, Video player, Calendar and Contacts.

Some files missing ? How can I check this ?

**Comment by oparoz** [comment]
It's going to be impossible to know without using the command line.

So my suggestion would be to use the 10.0.1 RC:
https://help.nextcloud.com/t/help-testing-the-9-0-54rc1-and-10-0-1rc1/3254

And to make sure you start with a clean application folder. The only old folders you want to keep are the config and data folder. Never keep the apps folder from the old installation.

**Comment by nickvergessen** [comment]
Closing as per above
