### ISSUE TITLE
Failed to connect to updates.nextcloud.org port 443

### ISSUE THREAD

**Issue by drexlma** [nextcloud/server#15034]
Apr 10 12:05:13 cloud1 ool[14722]: www: PHP Fatal error:  Uncaught Exception: Could not do request to updater server: Failed to connect to updates.nextcloud.org port 443: Connection timed out in /nextcloud/updater/index.php:575

**Comment by drexlma** [comment]
nextcloud server down

**Comment by MorrisJobke** [comment]
We had a short downtime at shortly before 10 am UTC, which is could be the time when you posted. Just rerun the updater. We fixed the issue.

**Comment by MAPTblHOB** [comment]
Got same problem now...

**Comment by MAPTblHOB** [comment]
Omg, i've opened downloaded nextcloud-12.0.12.zip (1KB):

We noticed that you request many releases once every hour which stressed our download server quite hard. We blocked access for you for now. To resolve the issue and maybe improve the download scripts you can reach out to the Nextcloud team.

WTF? I need to migrate from owncloud my only 1 instance!
