### ISSUE TITLE
Repair in maintenance mode

### ISSUE THREAD

**Issue by Temtaime** [nextcloud/server#15042]
### Steps to reproduce
1. Start maintenance:repair in maintenance mode on

### Expected behaviour
The process completes without an error

### Actual behaviour
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\FixBirthdayCalendarComponent' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\CalDAVRemoveEmptyValue' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\BuildCalendarSearchIndex' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\RefreshWebcalJobRegistrar' is unknown
Failed to load repair step for dav: Repair step 'OCA\DAV\Migration\RemoveClassifiedEventActivity' is unknown

Seems we need backport https://github.com/owncloud/core/pull/25650/files
With this fix the error is gone

**Comment by MonkeySon** [comment]
I am having the same errors, including the following:

Failed to load repair step for files_sharing: Repair step 'OCA\Files_Sharing\Migration\OwncloudGuestShareType' is unknown
Failed to load repair step for files_sharing: Repair step 'OCA\Files_Sharing\Migration\SetPasswordColumn' is unknown
Failed to load repair step for oauth2: Repair step 'OCA\OAuth2\Migration\SetTokenExpiration' is unknown
Failed to load repair step for twofactor_backupcodes: Repair step 'OCA\TwoFactorBackupCodes\Migration\CheckBackupCodes' is unknown

**Comment by ChristophWurst** [comment]
> Seems we need backport https://github.com/owncloud/core/pull/25650/files

@Temtaime could you submit this as PR? Thanks!

**Comment by Temtaime** [comment]
@ChristophWurst done

**Comment by ChristophWurst** [comment]
damn. I just opened a PR as well :see_no_evil:

**Comment by ChristophWurst** [comment]
Thank you @Temtaime!
