### ISSUE TITLE
"CONVERT TO CHARACTER SET utf8mb4"

### ISSUE THREAD

**Issue by emresaracoglu** [nextcloud/server#15058]
Hi,

I encountered an error while updating the database:

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes`

How can I fix this?

_PHP 7.2
Nextcloud V: 16 Beta 3 -> 16 RC1_

**Comment by emresaracoglu** [comment]
Makeshift:

Set the following.

```
INNODB utf8 VARCHAR(255)
INNODB utf8mb4 VARCHAR(191)
```

**Comment by Pasulke** [comment]
Hallo, don't know where to insert these commands.
Would you please explain?
Thank You.

**Comment by emresaracoglu** [comment]
> 
> 
> Hallo, don't know where to insert these commands.
> Would you please explain?
> Thank You.

You can edit of Nextcloud database tables with any database manager _(Adminer, phpMYadmin or etc)_ but firstly you should take a backup of the database.

**Comment by Pasulke** [comment]
Worked, thank you!

**Comment by danxensen** [comment]
I don't have any database managers on my server, is there a way to fix this via the MySQL console? I'm not sure what sort of query would be used.

**Comment by mr-gosh** [comment]
how is this done through the mysql client - so no ssh tunnel is needed to do this on the client

**Comment by shyim** [comment]
Or upgrade your MySQL Server to a newer version

**Comment by mr-gosh** [comment]
I am on mysql 5.5.62 and an upgrade is not necessary if you configure the innodb stiff the right way as I found out now:

Most entries to this error suggest to configure
innodb_large_prerix=true

But this leads to the mentioned error if you have large datasets as we do.

After setting up the 
innodb_large_prerix=1

Everything regarding tha database migration worked like a charm.

**Comment by mentalinc** [comment]
Can you please provide more step by step on where to change the two settings below?
I cant see it in phpMyAdmin

INNODB utf8 VARCHAR(255)
INNODB utf8mb4 VARCHAR(191)

**Comment by mentalinc** [comment]
Looks like updating to the latest version of 10.2 or 10.3 MariaDB from 10.1 will be easier solution
http://mysql.rjweb.org/doc.php/limits#767_limit_in_innodb_indexes

**Comment by skjnldsv** [comment]
Yep, I can also confirm. Please migrate to mariadb as it's actually vastly more supported and documented than mysql and check your `innodb_large_prefix`

Closing as it's irrelevant to nextcloud itself.

**Comment by mr-gosh** [comment]
> Closing as it's irrelevant to nextcloud itself.

sorry - but nextcloud suggested to do that migration - i won't give a shit to emoji support BUT as nextcloud pointed me to do so i did and ran into that problem. I would suggest to check the innodb_large_prefix=1 status during the upgrade preparation tests...

**Comment by olegchensky** [comment]
15.0.7 --> 16.0.1
Stable chanel! The same issue! By production is not normal. What to do?

**Comment by gytisrepecka** [comment]
> Makeshift:
> 
> Set the following.
> 
> ```
> INNODB utf8 VARCHAR(255)
> INNODB utf8mb4 VARCHAR(191)
> ```

Thanks, this helped!

**Comment by iakiakiak** [comment]
I ran into that issue migration Nextcloud 16.0.1 to 16.0.4 on CentOS 7.7 and MariaDB 5.5.64

I fixed with adding these lines to /etc/my.cnf :
innodb_large_prefix=1
innodb_large_prefix=true
innodb_file_per_table=true
innodb_file_format=barracuda

Especially the last line did the trick.

**Comment by Sx3** [comment]
> I ran into that issue migration Nextcloud 16.0.1 to 16.0.4 on CentOS 7.7 and MariaDB 5.5.64
> 
> I fixed with adding these lines to /etc/my.cnf :
> innodb_large_prefix=1
> innodb_large_prefix=true
> innodb_file_per_table=true
> innodb_file_format=barracuda
> 
> Especially the last line did the trick.

Oh Man You Just Saved me....That worked..Thank you.

**Comment by leonardorh** [comment]
> 
> 
> I ran into that issue migration Nextcloud 16.0.1 to 16.0.4 on CentOS 7.7 and MariaDB 5.5.64
> 
> I fixed with adding these lines to /etc/my.cnf :
> innodb_large_prefix=1
> innodb_large_prefix=true
> innodb_file_per_table=true
> innodb_file_format=barracuda
> 
> Especially the last line did the trick.

This worked for me! Thanks!

**Comment by MysterHawk** [comment]
> Makeshift:
> 
> Set the following.
> 
> ```
> INNODB utf8 VARCHAR(255)
> INNODB utf8mb4 VARCHAR(191)
> ```

Just use 
ALTER TABLE `oc_addressbooks` MODIFY COLUMN `principaluri` VARCHAR (191); 
ALTER TABLE `oc_addressbooks` MODIFY COLUMN `displayname` VARCHAR (191);
ALTER TABLE `oc_addressbooks` MODIFY COLUMN `uri` VARCHAR (191);
ALTER TABLE `oc_addressbooks` MODIFY COLUMN `description` VARCHAR (191);

in the mysql cli

**Comment by pr0krastinator** [comment]
Thanks a lot Antonio! It helped me a lot - an additional problem for me is, that I'm working in docker...

For me, the change to the MySQL config had to be:
```
[mysqld]
innodb_file_per_table=true
innodb_large_prefix=1
innodb_file_format=Barracuda
```

Maybe it depends on the MySQL/MariaDB-version. Mine is:
```
root@6705990ae06c:/# mariadb -V
mariadb  Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
```

If anybody else has this problem with Docker (specifically linuxserver/nextcloud & linuxserver/mariadb):
- `docker exec -it mariadb bash`
- install nano (optional)
- find right config-file (did it via mariadb --help); in my case it was /etc/mysql/mariadb.cnf
- `nano /etc/mysql/mariadb.cnf`
- under [client-server] insert:

```
[mysqld]
innodb_file_per_table=true
innodb_large_prefix=1
innodb_file_format=Barracuda
```

- Restart mysql: `service mysql restart`
- Exit from container: `exit`
- Restart docker container: `docker restart mariadb nextcloud`

Back to nextcloud: 
- `docker exec --user abc -it nextcloud bash`
- `cd /config/www/nextcloud/`
- Make sure maintainance mode is on: `php occ maintenance:mode --on`
- Now just repair and disable maintainance mode: `php occ repair --include-expensive` & `php occ maintenance:mode --off`

**Comment by MysterHawk** [comment]
> Thanks a lot Antonio! It helped me a lot - an additional problem for me is, that I'm working in docker...
> 
> For me, the change to the MySQL config had to be:
> 
> ```
> [mysqld]
> innodb_file_per_table=true
> innodb_large_prefix=1
> innodb_file_format=Barracuda
> ```
> 
> Maybe it depends on the MySQL/MariaDB-version. Mine is:
> 
> ```
> root@6705990ae06c:/# mariadb -V
> mariadb  Ver 15.1 Distrib 10.1.47-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2
> ```
> 
> If anybody else has this problem with Docker (specifically linuxserver/nextcloud & linuxserver/mariadb):
> 
>     * `docker exec -it mariadb bash`
> 
>     * install nano (optional)
> 
>     * find right config-file (did it via mariadb --help); in my case it was /etc/mysql/mariadb.cnf
> 
>     * `nano /etc/mysql/mariadb.cnf`
> 
>     * under [client-server] insert:
> 
> 
> ```
> [mysqld]
> innodb_file_per_table=true
> innodb_large_prefix=1
> innodb_file_format=Barracuda
> ```
> 
>     * Restart mysql: `service mysql restart`
> 
>     * Exit from container: `exit`
> 
>     * Restart docker container: `docker restart mariadb nextcloud`
> 
> 
> Back to nextcloud:
> 
>     * `docker exec --user abc -it nextcloud bash`
> 
>     * `cd /config/www/nextcloud/`
> 
>     * Make sure maintainance mode is on: `php occ maintenance:mode --on`
> 
>     * Now just repair and disable maintainance mode: `php occ repair --include-expensive` & `php occ maintenance:mode --off`

If you use the  linuxserver/mariadb docker's container,  you could just change the  config `custom.cnf` mounted with the mariadb config folder in the disk and then restart it (`docker restart mariadb nextcloud`);

The mysql service will reload with the container :)

**Comment by alabiana** [comment]
> 
> 
> Makeshift:
> 
> Set the following.
> 
> ```
> INNODB utf8 VARCHAR(255)
> INNODB utf8mb4 VARCHAR(191)
> ```

How will i do this via mysql console?

**Comment by MootoolsSoftware** [comment]
Hello,

I have no access to the conf file and no way to to modify it.

I first have the following error
      _Étape de réparation : Repair MySQL collation
      Informations de réparation : Change row format for oc_addressbooks ...
      Informations de réparation : Change collation for oc_addressbooks ...
      Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_addressbooks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes_

So I applied :

    _ALTER TABLE oc_addressbooks MODIFY COLUMN principaluri VARCHAR (191);
    ALTER TABLE oc_addressbooks MODIFY COLUMN displayname VARCHAR (191);
    ALTER TABLE oc_addressbooks MODIFY COLUMN uri VARCHAR (191);
    ALTER TABLE oc_addressbooks MODIFY COLUMN description VARCHAR (191);_

Then I launch the update again and now the error is:
      
      _Informations de réparation : Change row format for oc_authtoken ...
      Informations de réparation : Change collation for oc_authtoken ...
      Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
      
I am now stuck with this bug and don't know what to do because when I look at the table I don't know which field has to be promoted to VARCHAR(191)

![2021-04-15_19-43-31](https://user-images.githubusercontent.com/15813085/114914700-eac83c80-9e22-11eb-
922c-07b8595ca6ee.jpg)

Anyone can help ?
Thanks !
