### ISSUE TITLE
stable16 branch-off tasks

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#15056]
- [x] https://github.com/nextcloud/activity/pull/363
- [x] https://github.com/nextcloud/files_pdfviewer/pull/126
- [x] https://github.com/nextcloud/files_rightclick/pull/63
- [x] https://github.com/nextcloud/files_texteditor/pull/146
- [x] https://github.com/nextcloud/files_videoplayer/pull/127
- [x] https://github.com/nextcloud/firstrunwizard/pull/184
- [x] https://github.com/nextcloud/gallery/pull/508
- [x] https://github.com/nextcloud/logreader/pull/164
- [x] https://github.com/nextcloud/nextcloud_announcements/pull/38
- [x] https://github.com/nextcloud/notifications/pull/319
- [x] https://github.com/nextcloud/password_policy/pull/80
- [x] https://github.com/nextcloud/privacy/pull/95
- [x] https://github.com/nextcloud/recommendations/pull/67
- [x] https://github.com/nextcloud/serverinfo/pull/147
- [x] https://github.com/nextcloud/survey_client/pull/90
- [x] https://github.com/nextcloud/viewer/pull/66
- [x] https://github.com/nextcloud/files_antivirus/pull/123
- [x] https://github.com/nextcloud/jsloader/pull/12
- [x] https://github.com/nextcloud/preferred_providers/pull/9
- [x] https://github.com/nextcloud/user_saml/pull/322

**Comment by nickvergessen** [comment]
- [ ] https://github.com/nextcloud/announcementcenter/pull/148
- [ ] https://github.com/nextcloud/data_request/pull/25
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/106
- [ ] https://github.com/nextcloud/external/pull/138
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/126
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/73
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/43
- [ ] https://github.com/nextcloud/files_retention/pull/66
- [ ] https://github.com/nextcloud/impersonate/pull/72
- [ ] https://github.com/nextcloud/quota_warning/pull/42
- [ ] https://github.com/nextcloud/ransomware_protection/pull/48
- [ ] https://github.com/nextcloud/sharepoint/pull/30
- [ ] https://github.com/nextcloud/spreed/pull/1710
- [ ] https://github.com/nextcloud/terms_of_service/pull/166
- [ ] https://github.com/nextcloud/workflow_pdf_converter/pull/22
- [ ] https://github.com/nextcloud/workflow_script/pull/16

**Comment by nickvergessen** [comment]
- [ ] https://github.com/nextcloud/activity/pull/364
- [ ] https://github.com/nextcloud/files_pdfviewer/pull/127
- [ ] https://github.com/nextcloud/files_texteditor/pull/147
- [ ] https://github.com/nextcloud/firstrunwizard/pull/185
- [ ] https://github.com/nextcloud/gallery/pull/509
- [ ] https://github.com/nextcloud/nextcloud_announcements/pull/39
- [ ] https://github.com/nextcloud/notifications/pull/320
- [ ] https://github.com/nextcloud/password_policy/pull/81
- [ ] https://github.com/nextcloud/privacy/pull/96
- [ ] https://github.com/nextcloud/recommendations/pull/68
- [ ] https://github.com/nextcloud/serverinfo/pull/148
- [ ] https://github.com/nextcloud/survey_client/pull/91
- [ ] https://github.com/nextcloud/announcementcenter/pull/149
- [ ] https://github.com/nextcloud/data_request/pull/26
- [ ] https://github.com/nextcloud/end_to_end_encryption/pull/107
- [ ] https://github.com/nextcloud/files_accesscontrol/pull/127
- [ ] https://github.com/nextcloud/files_automatedtagging/pull/74
- [ ] https://github.com/nextcloud/files_downloadactivity/pull/44
- [ ] https://github.com/nextcloud/files_retention/pull/67
- [ ] https://github.com/nextcloud/impersonate/pull/73
- [ ] https://github.com/nextcloud/quota_warning/pull/43
- [ ] https://github.com/nextcloud/ransomware_protection/pull/49
- [ ] https://github.com/nextcloud/sharepoint/pull/31
- [ ] https://github.com/nextcloud/terms_of_service/pull/167
- [ ] https://github.com/nextcloud/workflow_pdf_converter/pull/23
- [ ] https://github.com/nextcloud/workflow_script/pull/17
- [ ] https://github.com/nextcloud/spreed/pull/1711

**Comment by MorrisJobke** [comment]
I went through all of those repos and adjusted the `.drone.yml` on all supported branches. What an amount of drone configs we have laying around 😅
