### ISSUE TITLE
Fiele_share: user can edit expiration date of file share link

### ISSUE THREAD

**Issue by michaG** [nextcloud/server#15059]
**Is your feature request related to a problem? Please describe.**
in the old version until nextCloud 13 you could set the expiration date for a file sharing per link to max. 30 days. The user could leave this at the date or choose a date between Now and 30 days.

**Describe the solution you'd like**
User can set an expiration date of link between now and max expiration date of link.

see: https://help.nextcloud.com/t/fiele-share-file-sharing-per-link-to-max-30-days/51385

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
