### ISSUE TITLE
Cron hangs after NC15 upgrade and utf8mb4 conversion

### ISSUE THREAD

**Issue by brtptrs** [nextcloud/server#15060]
After upgrading to NC 15.0.6 (from 15.0.4) and converting the DB tables to utf8mb4 (converting and compressing took many, many hours), cron jobs hang for hours. It seems that some long running DB queries might de the cause of the problem.

Any hints on solving the problem would be appreciated.

### Steps to reproduce
1. Upgrade to NC15.0.6
2. Convert DB Tables to utf8mb4 following the guide linked to the warning on the admin page

### Actual behaviour
Cron jobs hang for hours. We have found long running SQL processes the seem to match the time slots.
Example:
SELECT `fc`.`fileid`, `mnt`.`user_id` FROM `oc_filecache` `fc` LEFT JOIN `oc_files_antivirus` `fa` ON `fa`.`fileid` = `fc`.`fileid` INNER JOIN `oc_mounts` `mnt` ON `fc`.`storage` = `mnt`.`storage_id` WHERE (`fc`.`mimetype` <> '5') AND ((`fa`.`fileid` IS NULL) OR (`fc`.`mtime` > `fa`.`check_time`)) AND (`fc`.`path` LIKE 'files/%') AND (`fc`.`size` <> '0');

### Server configuration

**Operating system**: CentOS

**Web server:** Apache

**Database:** MariaDB 10.1

**PHP version:**7.1

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated 13>14>15

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by rullzer** [comment]
Could you run the query with EXPLAIN? Because it should (:tm:) run mostly on indexes. And if not we should fix the query.

**Comment by floh116** [comment]
not get confused, i'm one of the administrators on that system.

The EXPLAIN is:
MariaDB [nextcloud]> explain SELECT fc.fileid, mnt.user_id FROM oc_filecache fc LEFT JOIN oc_files_antivirus fa ON fa.fileid = fc.fileid INNER JOIN oc_mounts mnt ON fc.storage = mnt.storage_id WHERE (fc.mimetype <> '5') AND ((fa.fileid IS NULL) OR (fc.mtime > fa.check_time)) AND (fc.path LIKE 'files/%') AND (fc.size <> '0')\G
*************************** 1. row ***************************
           id: 1
  select_type: SIMPLE
        table: mnt
         type: ALL
possible_keys: mounts_storage_index
          key: NULL
      key_len: NULL
          ref: NULL
         rows: 13897
        Extra: 
*************************** 2. row ***************************
           id: 1
  select_type: SIMPLE
        table: fc
         type: ref
possible_keys: fs_storage_path_hash,fs_storage_mimetype,fs_storage_mimepart,fs_storage_size,fs_mtime
          key: fs_storage_path_hash
      key_len: 8
          ref: nextcloud.mnt.storage_id
         rows: 114
        Extra: Using index condition; Using where
*************************** 3. row ***************************
           id: 1
  select_type: SIMPLE
        table: fa
         type: eq_ref
possible_keys: PRIMARY
          key: PRIMARY
      key_len: 4
          ref: nextcloud.fc.fileid
         rows: 1
        Extra: Using where
3 rows in set (0.00 sec)



The Table Structure of the 3 Tables is:
MariaDB [nextcloud]> show create table oc_filecache\G
*************************** 1. row ***************************
       Table: oc_filecache
Create Table: CREATE TABLE `oc_filecache` (
  `fileid` bigint(20) NOT NULL AUTO_INCREMENT,
  `storage` bigint(20) NOT NULL DEFAULT '0',
  `path` varchar(4000) COLLATE utf8mb4_bin DEFAULT NULL,
  `path_hash` varchar(32) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `parent` bigint(20) NOT NULL DEFAULT '0',
  `name` varchar(250) COLLATE utf8mb4_bin DEFAULT NULL,
  `mimetype` bigint(20) NOT NULL DEFAULT '0',
  `mimepart` bigint(20) NOT NULL DEFAULT '0',
  `size` bigint(20) NOT NULL DEFAULT '0',
  `mtime` bigint(20) NOT NULL DEFAULT '0',
  `storage_mtime` bigint(20) NOT NULL DEFAULT '0',
  `encrypted` int(11) NOT NULL DEFAULT '0',
  `unencrypted_size` bigint(20) NOT NULL DEFAULT '0',
  `etag` varchar(40) COLLATE utf8mb4_bin DEFAULT NULL,
  `permissions` int(11) DEFAULT '0',
  `checksum` varchar(255) COLLATE utf8mb4_bin DEFAULT NULL,
  PRIMARY KEY (`fileid`),
  UNIQUE KEY `fs_storage_path_hash` (`storage`,`path_hash`),
  KEY `fs_parent_name_hash` (`parent`,`name`),
  KEY `fs_storage_mimetype` (`storage`,`mimetype`),
  KEY `fs_storage_mimepart` (`storage`,`mimepart`),
  KEY `fs_storage_size` (`storage`,`size`,`fileid`),
  KEY `fs_mtime` (`mtime`)
) ENGINE=InnoDB AUTO_INCREMENT=34593048 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
1 row in set (0.00 sec)

MariaDB [nextcloud]> show create table oc_files_antivirus\G
*************************** 1. row ***************************
       Table: oc_files_antivirus
Create Table: CREATE TABLE `oc_files_antivirus` (
  `fileid` int(10) unsigned NOT NULL,
  `check_time` int(10) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`fileid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
1 row in set (0.00 sec)

MariaDB [nextcloud]> show create table oc_mounts\G
*************************** 1. row ***************************
       Table: oc_mounts
Create Table: CREATE TABLE `oc_mounts` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `storage_id` int(11) NOT NULL,
  `root_id` int(11) NOT NULL,
  `user_id` varchar(64) COLLATE utf8mb4_bin NOT NULL,
  `mount_point` varchar(4000) COLLATE utf8mb4_bin NOT NULL,
  `mount_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `mounts_user_root_index` (`user_id`,`root_id`),
  KEY `mounts_user_index` (`user_id`),
  KEY `mounts_storage_index` (`storage_id`),
  KEY `mounts_root_index` (`root_id`),
  KEY `mounts_mount_id_index` (`mount_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62403 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED
1 row in set (0.00 sec)

**Comment by rullzer** [comment]
Mmm I'm not sure why the query is not using the proper index.
I'll ahve to dive a bit deeper.

I'll setup a mariadb 10.1 as well to verify.

**Comment by rullzer** [comment]
Ok I still don't get why this all of a sudden appeared. But let me see if I can fix the code handling a bit there. As the query is not optimal I'd say.

**Comment by rullzer** [comment]
So I think it happens because the result on your system just gets insanely big. Improvements to the background job are under development at https://github.com/nextcloud/files_antivirus/pull/124

**Comment by floh116** [comment]
sorry for the delay, i did some testings with a copy of the database and the query, it tried to undo the utf8mb4 and so …
it seems the main cause is simply the "COMPRESSED" on oc_filecache  …
with COMPRESSED the query has runtime between 3 and 4 hours.
with DYNAMIC as row format on oc_filecache the same command runs between 12 and 16 minutes

a minimal adjusted version of the command as "count()" is
MariaDB [testDb]> SELECT count(fc.fileid) FROM oc_filecache fc LEFT JOIN oc_files_antivirus fa ON fa.fileid = fc.fileid INNER JOIN oc_mounts mnt ON fc.storage = mnt.storage_id WHERE (fc.mimetype <> '5') AND ((fa.fileid IS NULL) OR (fc.mtime > fa.check_time)) AND (fc.path LIKE 'files/%') AND (fc.size <> '0');
+------------------+
| count(fc.fileid) |
+------------------+
|         49439093 |
+------------------+
1 row in set (12 min 5.76 sec)

**Comment by rullzer** [comment]
@floh116 well that is still a very long time. I hope the queries in https://github.com/nextcloud/files_antivirus/pull/124 run faster.

**Comment by brtptrs** [comment]
Will nextcloud/files_antivirus#124 be back-ported to NC15?

**Comment by rullzer** [comment]
@brtptrs yes the current version of the app is 15-17 compatible

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
