### ISSUE TITLE
Birthday events created while importing contacts should be deleted if addressbook containing the corresponding contact is deleted

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#1506]
_I'm not sure if it's correct in "server" component - but it does not only affect calendar or contacts, so it's either both - or "server", thus I report it here. Feel free to point me to re-insert it somewhere else._
### Steps to reproduce
1. create a dummy address book
2. import "test.vcf" containing a contact that has birthday data to address book "Contacts"
3. delete address book "Contacts"
4. re-create address book "Contacts"
5. (re)import "test.vcf"
### Expected behaviour

Deleting the address book should recursively delete all contacts, and while doing so, delete all previously created birthday events.
### Actual behaviour

Deleting the address book leads to stale birthday events in calendar that cannot be deleted (and, even worse, also have reminders (valarms) set.
### Steps to recover

How to get rid of stale events? Should I edit the nexcloud database. How (without harming consistency)? My idea is to
1. export contacts from address book "Contacts"
2. delete  the address book "Contacts" (this step requires any other address book to exist -> see step 0. above)
3. (re)create address book "Contacts" (empty)
4. delete all birthday events (HERE's where I don't know how)
5. (re)import the contacts to main addressbook "Contacts" (which (re)creates the birthday events).
### Server configuration

Debian jessie fully patched, Apache 2.4.10 prefork, PHP 5.6.24, MySQL 5.5.52, Nextcloud 10.0 (stable) freshly installed via Webinstaller.
### Cross references
- Other people experience this, too: https://help.nextcloud.com/t/contacts-birthday-are-shown-double-in-calendar/3380/4
- Contacts should not create reminders (valarms) or at least the user should be able to opt out while importing: https://github.com/nextcloud/server/issues/1505

**Comment by nickvergessen** [comment]
As written in the forum, the following command should solve the issue:
```
./occ dav:sync-birthday-calendar
```

But since you have no console access, I'm not sure if something is possible to fix this atm.

**Comment by nursoda** [comment]
Thanks!
I do have console access.

Does that command rebuild the birthday calendar from scratch (delete all its events and re-create them from the contacts) or does it search for duplicates and remove them?

I think I found a workaround for those without console access:
- export all contacts
- delete all contacts
- delete the birthday calendar
- import all contacts

**Comment by nickvergessen** [comment]
As far as I can judge from my quick look, it only adds/updates entries

**Comment by Micha-Btz** [comment]
```
owncloud/htdocs$ ./occ dav:sync-birthday-calendar
An unhandled exception has been thrown:
exception 'Doctrine\DBAL\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/virtual/web41856.pfweb.eu/mdomann.tk/owncloud/htdocs/lib/private/DB/Connection.php:59
Stack trace:
#0 /var/www/virtual/SECRET/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /var/www/virtual/SECRET/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /var/www/virtual/SECRET/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /var/www/virtual/SECRET/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /var/www/virtual/SECRET/htdocs/lib/private/DB/Connection.php(142): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /var/www/virtual/SECRET/htdocs/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\DB\Connection->__construct(Array, Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#6 /var/www/virtual/SECRET/htdocs/lib/private/DB/ConnectionFactory.php(123): Doctrine\DBAL\DriverManager::getConnection(Array, Object(Doctrine\DBAL\Configuration), Object(Doctrine\Common\EventManager))
#7 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(415): OC\DB\ConnectionFactory->getConnection('mysql', Array)
#8 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#9 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('DatabaseConnect...')
#10 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('DatabaseConnect...')
#11 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(1029): OC\ServerContainer->query('DatabaseConnect...')
#12 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(220): OC\Server->getDatabaseConnection()
#13 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#14 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#15 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#16 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(224): OC\ServerContainer->query('OC\\Authenticati...')
#17 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#18 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#19 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#20 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(151): OC\ServerContainer->query('OC\\Authenticati...')
#21 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(109): OC\AppFramework\Utility\SimpleContainer->OC\AppFramework\Utility\{closure}(Object(OC\Server))
#22 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('OC\\Authenticati...')
#23 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('OC\\Authenticati...')
#24 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(239): OC\ServerContainer->query('OC\\Authenticati...')
#25 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#26 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('UserSession')
#27 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('UserSession')
#28 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(913): OC\ServerContainer->query('UserSession')
#29 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(698): OC\Server->getSession()
#30 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#31 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('CsrfTokenManage...')
#32 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('CsrfTokenManage...')
#33 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(1382): OC\ServerContainer->query('CsrfTokenManage...')
#34 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(569): OC\Server->getCsrfTokenManager()
#35 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#36 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('Request')
#37 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('Request')
#38 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(780): OC\ServerContainer->query('Request')
#39 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(306): OC\Server->getRequest()
#40 /var/www/virtual/SECRET/htdocs/3rdparty/pimple/pimple/src/Pimple/Container.php(113): OC\Server->OC\{closure}(Object(OC\Server))
#41 /var/www/virtual/SECRET/htdocs/lib/private/AppFramework/Utility/SimpleContainer.php(103): Pimple\Container->offsetGet('L10NFactory')
#42 /var/www/virtual/SECRET/htdocs/lib/private/ServerContainer.php(89): OC\AppFramework\Utility\SimpleContainer->query('L10NFactory')
#43 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(965): OC\ServerContainer->query('L10NFactory')
#44 /var/www/virtual/SECRET/htdocs/lib/private/Server.php(976): OC\Server->getL10NFactory()
#45 /var/www/virtual/SECRET/htdocs/lib/base.php(230): OC\Server->getL10N('lib')
#46 /var/www/virtual/SECRET/htdocs/lib/base.php(663): OC::checkConfig()
#47 /var/www/virtual/SECRET/htdocs/lib/base.php(1059): OC::init()
#48 /var/www/virtual/SECRET/htdocs/console.php(48): require_once('/var/www/virtua...')
#49 /var/www/virtual/SECRET/htdocs/occ(11): require_once('/var/www/virtua...')
```

this exception i get after testing the ooc command. NC 10.0.1 stable

**Comment by Micha-Btz** [comment]
i have do some search and i thought i miss the mysql driver but it seems that it is ok.

> imscp_xxxxxxxxxxx/cloud/htdocs$ php -m | grep -i sql
> mysql
> mysqli
> mysqlnd
> pdo_mysql
> pdo_sqlite
> sqlite3
>

**Comment by Micha-Btz** [comment]
after some tests i can get database access if I use 

> 'dbhost' => '127.0.0.1', localhost didn't work.

so I'm able to run the command

> ich@owncloud/htdocs$ ./occ dav:sync-birthday-calendar
> Start birthday calendar sync for all users ...
>     2 [============================]

sadly the problem did not solve. I still have to birthday entry's in calendar.

**Comment by nickvergessen** [comment]
> sadly the problem did not solve. I still have to birthday entry's in calendar. what if i'am delete the calendar completely and let it create new?

That should work...

**Comment by Micha-Btz** [comment]
for me it is solved with deleting the contact birthday calendar.
and let it create new with ./occ dav:sync-birthday-calendar.

**Comment by nursoda** [comment]
Good to know there's a workaround. The bug is about proper deletion, though. Not sure whether triggering both "delete all birthday calendars" and "./occ dav:sync-birthday-calendar" is is a safe solution.

Another way to solve it could be to provide a selection mechanism for contacts (which is a good idea for other tasks, too, such as putting many contacts in a group, or exporting them) so that users may delete all contacts from their address book. When single contacts are deleted, it sould be possible to trigger deletion of the birthday cal entries the same way as they are created. This would need to be accompained by  a mechanism that prohibits deletion of an address book as long as it still contains contacts.

**Comment by nursoda** [comment]
Should this bug be closed? It's not implemented yet, is it?

**Comment by ThomasLeister** [comment]
Yes, it's not implemented yet. But I'd appreciate very much if automatic deletion of birthdays in calendar was available :)

**Comment by Daryes** [comment]
For those who face the same bug, it might be useful to know the occ command has a different behavior when called globally or with a username.

After deleting the anniversary calendar for a specific user, running occ  globally :
```
$ ./occ dav:sync-birthday-calendar
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Start birthday calendar sync for all users ...
 (...)
``` 
While the command was successful, the deleted calendar isn't rebuilt. Even more, checking the calendars table from the DB will confirm the command didn't work.   


Instead, using it with the username will have the expected result :
```
$ ./occ dav:sync-birthday-calendar 'specific_username'
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Re-enabling birthday calendar for specific_username
Start birthday calendar sync for specific_username
```

**Comment by SUECHTI** [comment]
I´m sorry, but 
./occ dav:sync-birthday-calendar 'specific_username'
did not helped me.
My Birthday Calendar is absent anyway..
i´ve done these Steps:
- export all contacts
- delete default contacts
- delete the birthday calendar
- create new Calendar 'default2'
- import all contacts
- run ./occ dav:sync-birthday-calendar
   (here php is using some processor for a minute, statusbar moving for every NC User)
-run ./occ dav:sync-birthday-calendar 'my_user'
   Start birthday calendar sync for 'my_user'
the process is instant finished, no cpu was used
but my Birthday-Calendar does not appear :(

using NC 13.0.4

**Comment by gohrner** [comment]
I ran into this bug using NextCloud 14.0.1.

For me,

    php occ dav:sync-birthday-calendar 'specific_username'

worked and re-enabled the birthday calender, which I had to delete before as it was messed-up with duplicate entries.

OTOH,

    php occ dav:sync-birthday-calendar

was *not* sufficient.

**Comment by skjnldsv** [comment]
@georgehrke :)

**Comment by georgehrke** [comment]
Ok, so this is not one bug, but multiple ones:
- [ ] deleting a contact does not delete the corresponding birthday entries.
There is code to handle that, need to check why it's not working:
https://github.com/nextcloud/server/blob/master/apps/dav/lib/AppInfo/Application.php#L127L136
https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/BirthdayService.php#L113L132

- [ ] calling `occ day:sync-birthday-calendar` (which uses syncUser) does indeed not delete orphaned birthday entries:
https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/BirthdayService.php#L289

**Comment by cristarta** [comment]
> 
> 
> for me it is solved with deleting the contact birthday calendar.
> and let it create new with ./occ dav:sync-birthday-calendar.

This workaround allowed me to fix this outstanding issue on my Nextcloud v19 installation. I've written up a [novice friendly](https://cristarta.com/computers/2021/01/02/snippet-nextcloud-duplicate-birthday-entries.html) procedure in case others stumble on this thread - like I originally did.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
