### ISSUE TITLE
fulltextsearch:index fails: Call to a member function getUID() on null

### ISSUE THREAD

**Issue by git-ere** [nextcloud/server#15074]
### Steps to reproduce
1. add external storage Amazon S3
2. create folders, files on external storage
3. install elasticsearch & fulltext search
4. start fulltextsearch:index

### Expected behaviour
Files should be indexed

### Actual behaviour
Error: Call to a member function getUID() on null in /var/www/html/lib/private/Share20/Manager.php and index process crashes

### Server configuration
docker image nextcloud:apache
nextcloud 15.0.7 - was the same with previous versions
db: docker image mariadb
ldap authentication, but user which created folder / files is local nextcloud admin user.
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.6
  - files_fulltextsearch_tesseract: 1.2.2
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.5
  - fulltextsearch_elasticsearch: 1.2.4
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - bookmarks_fulltextsearch
  - encryption
  - files_accesscontrol</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.1.50",
            "staff.bridgesolutions.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "overwriteprotocol": "https",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "overwritewebroot": "\/nextcloud",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}
ro</details>

**Are you using external storage, if yes which one:** amazon S3

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
+-------------------------------+---------------------------------------------------+
| Configuration                 | s01                                               |
+-------------------------------+---------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                 |
| homeFolderNamingRule          |                                                   |
| lastJpegPhotoLookup           | 0                                                 |
| ldapAgentName                 | uid=xxx,ou=people,dc=yyy,dc=net       |
| ldapAgentPassword             | ***                                               |
| ldapAttributesForGroupSearch  |                                                   |
| ldapAttributesForUserSearch   |                                                   |
| ldapBackupHost                |                                                   |
| ldapBackupPort                |                                                   |
| ldapBase                      | dc=yyy,dc=net                         |
| ldapBaseGroups                | dc=yyy,dc=net                         |
| ldapBaseUsers                 | dc=yyy,dc=net                         |
| ldapCacheTTL                  | 600                                               |
| ldapConfigurationActive       | 1                                                 |
| ldapDefaultPPolicyDN          |                                                   |
| ldapDynamicGroupMemberURL     |                                                   |
| ldapEmailAttribute            | mail                                              |
| ldapExperiencedAdmin          | 0                                                 |
| ldapExpertUUIDGroupAttr       |                                                   |
| ldapExpertUUIDUserAttr        |                                                   |
| ldapExpertUsernameAttr        |                                                   |
| ldapGidNumber                 | gidNumber                                         |
| ldapGroupDisplayName          | cn                                                |
| ldapGroupFilter               |                                                   |
| ldapGroupFilterGroups         |                                                   |
| ldapGroupFilterMode           | 0                                                 |
| ldapGroupFilterObjectclass    |                                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                      |
| ldapHost                      | 192.168.x.y2                                      |
| ldapIgnoreNamingRules         |                                                   |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson)))(|(uid=%uid))) |
| ldapLoginFilterAttributes     | uid                                               |
| ldapLoginFilterEmail          | 0                                                 |
| ldapLoginFilterMode           | 0                                                 |
| ldapLoginFilterUsername       | 0                                                 |
| ldapNestedGroups              | 0                                                 |
| ldapOverrideMainServer        |                                                   |
| ldapPagingSize                | 500                                               |
| ldapPort                      | 389                                               |
| ldapQuotaAttribute            |                                                   |
| ldapQuotaDefault              |                                                   |
| ldapTLS                       | 0                                                 |
| ldapUserAvatarRule            | default                                           |
| ldapUserDisplayName           | cn                                                |
| ldapUserDisplayName2          |                                                   |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson)))                 |
| ldapUserFilterGroups          |                                                   |
| ldapUserFilterMode            | 0                                                 |
| ldapUserFilterObjectclass     | inetOrgPerson                                     |
| ldapUuidGroupAttribute        | auto                                              |
| ldapUuidUserAttribute         | auto                                              |
| turnOffCertCheck              | 0                                                 |
| turnOnPasswordChange          | 0                                                 |
| useMemberOfToDetectMembership | 1                                                 |
+-------------------------------+---------------------------------------------------+```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment]
@daita :)

**Comment by herrep** [comment]
I experience the same issue with Nextcloud 15.0.8 and fulltextsearch 1.2.9, fulltextsearch - files 1.2.8:

`An unhandled exception has been thrown:
Error: Call to a member function getUID() on null in /var/www/html/lib/private/Share20/Manager.php:1433
Stack trace:
#0 /var/www/html/apps/files_fulltextsearch/lib/Service/LocalFilesService.php(162): OC\Share20\Manager->getAccessList(Object(OC\Files\Node\Folder), true, true)
#1 /var/www/html/apps/files_fulltextsearch/lib/Service/FilesService.php(667): OCA\Files_FullTextSearch\Service\LocalFilesService->getShareUsersFromFile(Object(OC\Files\Node\Folder), Array)
#2 /var/www/html/apps/files_fulltextsearch/lib/Service/FilesService.php(596): OCA\Files_FullTextSearch\Service\FilesService->updateShareNames(Object(OCA\Files_FullTextSearch\Model\FilesDocument), Object(OC\Files\Node\Folder))
#3 /var/www/html/apps/files_fulltextsearch/lib/Service/FilesService.php(570): OCA\Files_FullTextSearch\Service\FilesService->updateDocumentAccess(Object(OCA\Files_FullTextSearch\Model\FilesDocument), Object(OC\Files\Node\Folder))
#4 /var/www/html/apps/files_fulltextsearch/lib/Service/FilesService.php(551): OCA\Files_FullTextSearch\Service\FilesService->updateFilesDocumentFromFile(Object(OCA\Files_FullTextSearch\Model\FilesDocument), Object(OC\Files\Node\Folder))
#5 /var/www/html/apps/files_fulltextsearch/lib/Service/FilesService.php(445): OCA\Files_FullTextSearch\Service\FilesService->updateFilesDocument(Object(OCA\Files_FullTextSearch\Model\FilesDocument))
#6 /var/www/html/apps/files_fulltextsearch/lib/Provider/FilesProvider.php(246): OCA\Files_FullTextSearch\Service\FilesService->generateDocument(Object(OCA\Files_FullTextSearch\Model\FilesDocument))
#7 /var/www/html/apps/fulltextsearch/lib/Service/IndexService.php(303): OCA\Files_FullTextSearch\Provider\FilesProvider->fillIndexDocument(Object(OCA\Files_FullTextSearch\Model\FilesDocument))
#8 /var/www/html/apps/fulltextsearch/lib/Service/IndexService.php(194): OCA\FullTextSearch\Service\IndexService->indexDocuments(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Array, Object(OCA\FullTextSearch\Model\IndexOptions))
#9 /var/www/html/apps/fulltextsearch/lib/Command/Index.php(408): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser(Object(OCA\FullTextSearch_ElasticSearch\Platform\ElasticSearchPlatform), Object(OCA\Files_FullTextSearch\Provider\FilesProvider), 'am', Object(OCA\FullTextSearch\Model\IndexOptions))
#10 /var/www/html/apps/fulltextsearch/lib/Command/Index.php(272): OCA\FullTextSearch\Command\Index->indexProvider(Object(OCA\Files_FullTextSearch\Provider\FilesProvider), Object(OCA\FullTextSearch\Model\IndexOptions))
#11 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/html/core/Command/Base.php(166): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/html/3rdparty/symfony/console/Application.php(946): OC\Core\Command\Base->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 /var/www/html/3rdparty/symfony/console/Application.php(248): Symfony\Component\Console\Application->doRunCommand(Object(OCA\FullTextSearch\Command\Index), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 /var/www/html/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/console.php(96): OC\Console\Application->run()
#18 /var/www/html/occ(11): require_once('/var/www/html/c...')
`

**Comment by herrep** [comment]
This problem occurs when indexing files of a local user, while the other users are from ldap.

**Comment by daita** [comment]
should be fixed in https://github.com/nextcloud/server/pull/15832

**Comment by herrep** [comment]
Thank you very much for pointing me to issue #15832. It appears that issue #15832 is related to indexing a group folder with fulltextsearch.  I verified that I got more or less the same exception.  What I wonder is that I have not any group folder configured. The app "grou folder" is activated in my setup, but I have not any entry in the list of group folders.

**Comment by Omaha2002** [comment]
This bug seems to have returned in NC21:

An unhandled exception has been thrown:
Error: Call to a member function getOwner() on null in /var/www/nextcloud/lib/private/Share20/Manager.php:1651
Stack trace:
#0 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/LocalFilesService.php(163): OC\Share20\Manager->getAccessList()
#1 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(795): OCA\Files_FullTextSearch\Service\LocalFilesService->getShareUsersFromFile()
#2 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(725): OCA\Files_FullTextSearch\Service\FilesService->updateShareNames()
#3 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(699): OCA\Files_FullTextSearch\Service\FilesService->updateDocumentAccess()
#4 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(680): OCA\Files_FullTextSearch\Service\FilesService->updateFilesDocumentFromFile()
#5 /var/www/nextcloud/apps/files_fulltextsearch/lib/Service/FilesService.php(571): OCA\Files_FullTextSearch\Service\FilesService->updateFilesDocument()
#6 /var/www/nextcloud/apps/files_fulltextsearch/lib/Provider/FilesProvider.php(288): OCA\Files_FullTextSearch\Service\FilesService->generateDocument()
#7 /var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php(317): OCA\Files_FullTextSearch\Provider\FilesProvider->fillIndexDocument()
#8 /var/www/nextcloud/apps/fulltextsearch/lib/Service/IndexService.php(204): OCA\FullTextSearch\Service\IndexService->indexDocuments()
#9 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(410): OCA\FullTextSearch\Service\IndexService->indexProviderContentFromUser()
#10 /var/www/nextcloud/apps/fulltextsearch/lib/Command/Index.php(273): OCA\FullTextSearch\Command\Index->indexProvider()
#11 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Command/Command.php(255): OCA\FullTextSearch\Command\Index->execute()
#12 /var/www/nextcloud/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#13 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(1009): OC\Core\Command\Base->run()
#14 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#15 /var/www/nextcloud/apps/bookmarks/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun()
#16 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#17 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#18 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

versions:
![image](https://user-images.githubusercontent.com/3179748/122668994-6e9ffb80-d1bb-11eb-8685-ea22ecdb1b84.png)

Server version:  21.0.2
