### ISSUE TITLE
Deprecate php7.1

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15079]
According to https://secure.php.net/supported-versions.php, php7.1 is not actively maintained anymore and security updates end November 2019. I'm therefore opening this ticket to discuss our deprecation and compatibility timeline.

Should we already show a warning with Nextcloud 17? When will we remove php7.1 support from Nextcloud? 18?19?

**Comment by rullzer** [comment]
Yes agreed. A warning that 7.1 no longer has active support and upgrades are advices can't hurt. :rocket:

**Comment by tflidd** [comment]
If there is no technical reason for deprecation, there has been a bit of a struggle with too tight php support:

Many distributions support php versions in their LTS products longer than the official support and many customers still trust them. Less experienced NC users just update their php some way, it's perhaps a one time compile or buggy 3rd-party source that will never see a bugfix, in that case we made it worse.

If you want to upgrade between major versions, some dependencies get very annoying. There were people who wanted to upgrade from NC 12 (php 5.6) to a new system with NC 15 (php 7.2), they still need an intermediate step on a system with php 7.0. You can't avoid that completely.

If new php versions are so critical for NC, we should reconsider advising using Debian/Ubuntu (installation manual, vm images, snap images, Nextcloud Pi) and Redhat/CentOS. ArchLinux or FreeBSD (and many others) might be a better choice.

**Comment by nickvergessen** [comment]
In this case the idea is to print a warning in the admin interface, not to prevent usage/installation.
While I understand your reasons and fully agree it is annoying when try to update from a 3year old nextcloud version, I don't think it qualifies as an argument to make nextcloud coding annoying and not state of the art.

Also I don't want to start the discussion again, if non-php devs are the best to maintain support for an outdated version...
We shouldn't try to help people run an insecure stack. Php versions are 3 years supported. In that time you have to update, if you run your stuff on the public internet.

**Comment by rullzer** [comment]
Done ;)
