### ISSUE TITLE
files_rightclick integrity check

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#15078]
After upgrading to NC16 RC1, I do get
```
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)
```

**Comment by jookk** [comment]
I have it too

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage

**Comment by kesselb** [comment]
https://github.com/nextcloud/files_rightclick :sunglasses:

**Comment by MorrisJobke** [comment]
It's shipped, but it's weird that it somehow is in the release but not in the signature.json. Typically this is one of the files that is actually removed during build time.

**Comment by MorrisJobke** [comment]
This file is not in the release tar ball, but only in the releases from the appstore. So this needs to be fixed there. cc @NastuzziSamy 

Then it also raises multiple questions:

* the release bundles 0.13 and the appstore also only has 0.13, why is it updated then from the appstore?
* shipped apps are signed in `core/signature.json` and if a shipped app gets updated via appstore the signature of the server is used

cc @nickvergessen @rullzer

**Comment by nickvergessen** [comment]
I would just recommend to remove the README on packaging of the app.
It's one line like https://github.com/nextcloud/files_rightclick/blob/master/Makefile#L40 and solves the issue for now?

**Comment by a1pilot** [comment]
Was this fixed? I see the two similar threads are closed without resolution.

**Comment by jookk** [comment]
No, I have red notification about integrity check.

**Comment by NastuzziSamy** [comment]
Hi guys, I will fix it this week

**Comment by a1pilot** [comment]
@NastuzziSamy Any news?

**Comment by alvVDC1846** [comment]
I get the same error after update.

**Comment by unnilennium** [comment]
+1 on  16.0.3
```
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)

```

**Comment by MorrisJobke** [comment]
@NastuzziSamy 🏓

**Comment by Githopp192** [comment]
did the upgrade from 15.0.10 to 16.0.3 .. same2me .. 

Results
--
=======
#NAME?
- EXTRA_FILE
- README.md
 
Raw output
==========
Array
(
[files_rightclick] => Array
(
[EXTRA_FILE] => Array
(
[README.md] => Array
(
[expected]   =>
[current] =>   cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
)
 
)
 
)
 
)

But .. after two times de-/re Installing the App (and then suddenly starting the CRON-Job) .. the 
Integrity check was fine

**Comment by JoeatMJ** [comment]
Same result here moving from 15.0.11 to 16.0.4. Removed it. Re-ran the scan in NC. Reinstalled from the app store. All is well.

**Comment by a1pilot** [comment]
Not fixed for me. Just retried it and still occuring.

**Comment by kesselb** [comment]
I suppose you have to uninstall and install the app again (or delete the README.md) and trigger the integrity check again. If that does not help we can reopen. We need the issue template for your setup than.
