### ISSUE TITLE
Filesize check before upload.

### ISSUE THREAD

**Issue by jdoubleu** [nextcloud/server#1508]
After investigation of [this bug](https://github.com/Wonderfall/dockerfiles/issues/38#issuecomment-248129288) of a user made docker environment I found out that there's no information if the download fails.

I tried to upload a 2GB file and only at the end it says `504 Gateway Time Out`, although it may already broke at 1GB (as described [here](https://github.com/Wonderfall/dockerfiles/issues/38#issuecomment-249416854)).

The problem over there has something todo with the php settings (e.g. `upload_max_size`, `post_max_size`, etc.) but there should be a check from nextcloud before an upload starts.

E.g.
```
ini_get('upload_max_filesize');
```

**Comment by nickvergessen** [comment]
The uploaded chunks of the sync clients are 5 MB by default. We also check the ini values (against those chunks).

Please provide the information that is being asked for in the issue template, otherwise we can not really help you a lot with this issue.

**Comment by jdoubleu** [comment]
Okay nevermind, thank you for the info!

Some error appeared which I've already resolved. The thing was that this error appeared at the end of an upload so it seemed there wasn't any check.

This issue can be closed.
