### ISSUE TITLE
Everytime a new link when open a share in Windows

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/server#15085]
Hello, 

I have several Nextcloud 15 installations and in all systems is the same problem. When I add a share in Windows, it makes everytime a new share. I can not access the shares I created before. When I look in the web frontend, I can see all the created shares but not in Windows.
In Nextcloud 13, I could see in Windows the created shares. 

System
Nextcloud 15.0.7
Ubuntu 18.04. LTS
Apache 2
Mysql
PHP 7.2
Windows 10 
The Last Version of Windows client

**Comment by violoncelloCH** [comment]
that's probably something for the desktop client repository, isn't it? Could you report it there?
also which Version of the Client are you using?

**Comment by XBrainBug** [comment]
yes, you are right, i post it there!
