### ISSUE TITLE
ERRORS/WARNINGS after  Upgrade OC 9.0.2. to NC 9.0.5 "Some files have not passed the integrity check"

### ISSUE THREAD

**Issue by githubos1** [nextcloud/server#151]
**PROBABLY related to my (much more serious) new ISSUE #169** [https://github.com/nextcloud/server/issues/169](url)

Hi all,

Just did the migration from OwnCloud 9.0.2. to NextCloud 9.0.5

I'm using OC/NC on Hosted Server from ALL-INKL on PHP 7.0 (CGI)

--> upgrade process went fine but now I'm seeing the followin (probably minor) issues on NextCloud when I login as ADmin:

Security & setup warnings
    Some files have not passed the integrity check. 

...and further if I follow the link to https:// "MEINECLOUD"../index.php/settings/integrity/failed:

see below "failed" files:

SHOULD I BE CONCEARNED about these (maybe outdated) files ??<!--

###############################################
core
    INVALID_HASH
        core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
        core/doc/admin/_static/img/note_pencil.svg
        core/doc/admin/_static/img/warning.svg
        core/doc/admin/_static/style.css
        core/fonts/LICENSE.txt
        core/vendor/jquery-migrate/jquery-migrate.js
        core/vendor/jquery-migrate/jquery-migrate.min.js
        core/vendor/jsTimezoneDetect/jstz.js

files_texteditor
    INVALID_HASH
        js/vendor/ace/src-noconflict/mode-diff.js

files_external
    INVALID_HASH
        3rdparty/Dropbox/API.php
####################################################
REGARDS,

Oliver

**Comment by MorrisJobke** [comment]
@githubos1 Could you provide us the above mentioned files from your installation? Then we could check them against the ones, that should be in the release and maybe spot the difference.

**Comment by githubos1** [comment]
Sure...
just downloaded..

but zip file can not be uploaded here.. ??  
"Something went really wrong, and we can’t process that file. "

Any other ways of getting it to you ??

**Comment by githubos1** [comment]
[InvalidHashFiles.zip](https://github.com/nextcloud/server/files/323077/InvalidHashFiles.zip)

sorry, got a script blocked... my fault !!  just uploaded the files

In the zip:
---------------------------------
Results
=======
- core
	- INVALID_HASH
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/img/note_pencil.svg
		- core/doc/admin/_static/img/warning.svg
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jquery-migrate/jquery-migrate.js
		- core/vendor/jquery-migrate/jquery-migrate.min.js
		- core/vendor/jsTimezoneDetect/jstz.js
.....

BUT:
mode.diff.js and API.php i was not able to find/locate in my installation...
--------------------------------------
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php
--------------------------------------------------

Let me know if you need any further infos !!

Oliver

**Comment by schiessle** [comment]
I assume you mean ownCloud 9.0.2... I updated the headline to avoid confusions

**Comment by githubos1** [comment]
ooops ... yes, right !! of course..!

**Comment by githubos1** [comment]
And here the complete output....
The "EXTRA_FILES" are automatically build/saved in my subdomain folder  by my Hoster (ALL-INKL)... and not my concearn of course...


[FailedIntegrityChecks_Output.txt](https://github.com/nextcloud/server/files/323130/FailedIntegrityChecks_Output.txt)

**Comment by githubos1** [comment]
SOLVED by replacing NC 9.0.5  with 9.0.51
