### ISSUE TITLE
After every upgrade is SKELETON back

### ISSUE THREAD

**Issue by kokotko1337** [nextcloud/server#15113]
Env: NC 14, Linux Debian Stretch, Mariadb

**Is your feature request related to a problem? Please describe.**
Removed SKELETON is back after every update.

**Describe the solution you'd like**
If there is no SKELETON in instance, upgrade should not copy new one.

**Describe alternatives you've considered**
No new SKELETON wanted after upgrade.

**Comment by MorrisJobke** [comment]
That is the default skeleton directory. If you want to use an empty one, then create a folder outside of the nextcloud directory and set the config option to use that: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L278
