### ISSUE TITLE
TypeError: Argument 2 passed to OC\Streamer::__construct() must be of the type integer, float given, called in /config/www/nextcloud/lib/private/legacy/files.php on line 166

### ISSUE THREAD

**Issue by theincredibleman** [nextcloud/server#15117]
### Steps to reproduce
1. Try to download 2 files (file 1 is 2,8GB, file 2 just a few KB)  at the same time via share link or logged in as admin.
2. Throws error right away.
3. Does not throw error when 1 file is downloaded at a time. System does not zip the file.
4. Problem does not occur when downloading a smaller (1GB) file together with another file, system creates a ZIP and files are downloaded.

I am wondering if it is possible to turn off the ZIP function when multiple files are downloaded, and whether that would resolve the issue.

### Expected behaviour
Files should both be downloaded

### Actual behaviour
Error is thrown. 

### Server configuration
Alpine 3.9 in Docker

**Web server:**
NGINX

**Database:**
MariaDB

**PHP version:**
7.2.13

**Nextcloud version:** (see Nextcloud admin page)
15.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
https://hub.docker.com/r/linuxserver/nextcloud/

**Comment by RailsViceRoads** [comment]
Same behaviour on my system. Try download a directory greater then (approx) 1GB will result in an error. 

**System**
server version 16.0.5.1
php version 7.3.6
database type mysql
app files version 1.11.0
app files_rightclick version 0.15.1

**Log**

> [index] Error: TypeError: Argument 2 passed to OC\Streamer::__construct() must be of the type int, float given, called in /rootdir/www/cloud.webspace.de/lib/private/legacy/files.php on line 166 at <<closure>>
> 
> 0. /rootdir/www/cloud.webspace.de/lib/private/legacy/files.php line 166
>    OC\Streamer->__construct(OC\AppFramework\Http\Request {}, 2636124555, 2677)
> 1. /rootdir/www/cloud.webspace.de/apps/files/ajax/download.php line 64
>    OC_Files::get("/DirOne", "DirTwo", {head: false})
> 2. /rootdir/www/cloud.webspace.de/lib/private/Route/Route.php line 155
>    undefinedundefinedrequire_once("/rootdir ... p")
> 3. <<closure>>
>    OC\Route\Route->OC\Route\{closure}("*** sensitive parameters replaced ***")
> 4. /rootdir/www/cloud.webspace.de/lib/private/Route/Router.php line 297
>    undefinedundefinedcall_user_func(Closure {}, {_route: "files_ajax_download"})
> 5. /rootdir/www/cloud.webspace.de/lib/base.php line 975
>    OC\Route\Router->match("/apps/files/ajax/download.php")
> 6. /rootdir/www/cloud.webspace.de/index.php line 42
>    OC::handleRequest()
> 
> GET /index.php/apps/files/ajax/download.php?dir=%2FPr%C3%A4sident&files=Alt-1.%20Vorsitzender&downloadStartSecret=tfh2iarlrgm
> from 79.245.161.234 by user at 2019-10-09T19:07:05+00:00

**Comment by CptDayDreamer** [comment]
Same behaviour on my system too. Happens if I want to download more than 2 GB per download with multiple files. Download a single file with a big size is no problem. I tried it with 42 GB.

System
docker version of NextCloud
server version 16.0.5.1
php version 7.3.9
database type mysql 10.3.17

Log
[index] Error: TypeError: Argument 2 passed to OC\Streamer::__construct() must be of the type int, float given, called in /data/nextcloud/lib/private/legacy/files.php on line 166 at <<closure>>

0. /data/nextcloud/lib/private/legacy/files.php line 166
   OC\Streamer->__construct(OC\AppFramework\Http\Request {}, 5831685788, 329)
1. /data/nextcloud/apps/files/ajax/download.php line 64
   OC_Files::get("/Universität/Ba ... )", "IT-Management", {head: false})
2. /data/nextcloud/lib/private/Route/Route.php line 155
   undefinedundefinedrequire_once("/data/nextcloud ... p")
3. <<closure>>
   OC\Route\Route->OC\Route\{closure}("*** sensitive parameters replaced ***")
4. /data/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(Closure {}, {_route: "files_ajax_download"})
5. /data/nextcloud/lib/base.php line 975
   OC\Route\Router->match("/apps/files/ajax/download.php")
6. /data/nextcloud/index.php line 42
   OC::handleRequest()

GET /index.php/apps/files/ajax/download.php?dir=%2FUniversit%C3%A4t%2FBachelor%2F5.%20Semester%20(WS%202018-19)&files=IT-Management%20(Ahlemann)&downloadStartSecret=he6g716gbob
from 132.252.197.182 by user at 2019-10-23T10:50:41+00:00

**Comment by nfp0** [comment]
Exact same thing happens to me too.

Nextcloud 16.0.5 SNAP
Apache 2.4
PHP 7.2
MySQL 5.7
Redis 4.0

**Comment by dpertin** [comment]
Same issue observed.

### System

server version 16.0.5.1
php:
`
database :
`
Type: pgsql
Version: PostgreSQL 12.1 on armv7l-unknown-linux-gnueabihf, compiled by armv7l-unknown-linux-gnueabihf-gcc (GCC) 8.3.0, 32-bit
Size: 33 MB
`
app files version 1.11.0
app files_rightclick version 0.15.1

### Log
`{"reqId":"mFHQwBnn4doFZXwCb9bC","level":3,"time":"2020-03-01T10:36:46+00:00","remoteAddr":"192.168.1.100","user":"dim","app":"index","method":"GET","url":"/index.php/apps/files/ajax/download.php?dir=%2FInstantUpload%2FCamera&files=%5B%2220200131_125453.jpg%22%2C%2220200131_105724.mp4%22%2C%2220200131_110441.jpg%22%2C%2220200131_104941.mp4%22%2C%2220200130_122239.mp4%22%2C%2220200131_105842.mp4%22%2C%2220200131_104313.mp4%22%2C%2220200130_121830.mp4%22%2C%2220200128_150025.mp4%22%2C%2220200130_121323.mp4%22%2C%2220200131_125816.jpg%22%2C%2220200131_112309.jpg%22%2C%2220200131_112313.jpg%22%2C%2220200130_121401.mp4%22%2C%2220200129_132052.jpg%22%2C%2220200131_105141.mp4%22%2C%2220200131_112257.jpg%22%2C%2220200131_105600.mp4%22%2C%2220200130_122311.mp4%22%2C%2220200131_104439.mp4%22%2C%2220200131_110519.jpg%22%2C%2220200131_110515.jpg%22%5D&downloadStartSecret=t1h1q2z32z","message":{"Exception":"TypeError","Message":"Argument 2 passed to OC\\Streamer::__construct() must be of the type int, float given, called in /usr/share/webapps/nextcloud/lib/private/legacy/files.php on line 167","Code":0,"Trace":[{"file":"/usr/share/webapps/nextcloud/lib/private/legacy/files.php","line":167,"function":"__construct","class":"OC\\Streamer","type":"->"},{"file":"/usr/share/webapps/nextcloud/apps/files/ajax/download.php","line":64,"function":"get","class":"OC_Files","type":"::"},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Route.php","line":155,"args":["/usr/share/webapps/nextcloud/apps/files/ajax/download.php"],"function":"require_once"},{"function":"OC\\Route\\{closure}","class":"OC\\Route\\Route","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/usr/share/webapps/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/usr/share/webapps/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/usr/share/webapps/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/usr/share/webapps/nextcloud/lib/private/Streamer.php","Line":55,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0","version":"18.0.1.3","id":"5e5b9053a9d72"}`

**Comment by atoav** [comment]
I have a similar error when sharing a folder that contains eight 2 GB files and one 882 MB files.

## Error Log
(paths and adresses censored for privacy reasons)

```
[index] Error: TypeError: Argument 2 passed to OC\Streamer::__construct() must be of the type integer, float given, called in █████████████/lib/private/legacy/files.php on line 166 at <<closure>>

0. █████████████/lib/private/legacy/files.php line 166
   OC\Streamer->__construct(OC\AppFramework\Http\Request {}, 17680871125, 10)
1. █████████████/apps/files_sharing/lib/Controller/ShareController.php line 605
   OC_Files::get("/HR3", "AE", {head: false})
2. █████████████/lib/private/AppFramework/Http/Dispatcher.php line 166
   OCA\Files_Sharing\Controller\ShareController->downloadShare("wCqm29mARgn4TTz", null, "", "")
3. █████████████/lib/private/AppFramework/Http/Dispatcher.php line 99
   OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sharin ... {}, "downloadShare")
4. █████████████/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sharin ... {}, "downloadShare")
5. █████████████/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Files_Shar ... r", "downloadShare", OC\AppFramework\ ... {}, {token: "wCqm29m ... "})
6. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({token: "wCqm29m ... "})
7. █████████████/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {token: "wCqm29m ... "})
8. █████████████/lib/base.php line 975
   OC\Route\Router->match("/s/wCqm29mARgn4TTz/download")
9. █████████████/index.php line 42
   OC::handleRequest()

GET /index.php/s/wCqm29mARgn4TTz/download
from ████:██:███:████:████:████:████:████ at 2020-03-07T11:24:41+00:00
```

**Comment by manches** [comment]
Same occured:
System
server version 18.0.1.3
php version 7.3.11
database type mysql  Ver 15.1 Distrib 10.3.18-MariaDB

**Comment by RomainTT** [comment]
I have the same issue. Is there any workaround or patch for this yet ?

**System**
server version 18.0.3
php version 7.3.13
database sqlite3

**Comment by trev-dev** [comment]
File uploading/downloading is broken in both directions for me and generally always has been for anything over a GB.

Running nextcloud on a Pi 4, on a docker with PHP limits set to 20Gb and 4Gb of RAM and swap.
`Argument 2 passed to OC\Streamer::__construct() must be of the type int, float given, called in /data/nextcloud/lib/private/legacy/files.php on line 167`

The user experience for anyone receiving the file:
![The User Experience](https://user-images.githubusercontent.com/28788713/87441655-3013c100-c5a8-11ea-9b2a-27cd8e6e4653.png)

**Comment by PStewardYUL** [comment]
Same issue:
Exception: Argument 2 passed to OC\Streamer::__construct() must be of the type int, float given, called in /var/www/nextcloud/lib/private/legacy/files.php on line 167

NextCloudPi version | v1.28.1

**Comment by JonasDaWi** [comment]
Same issue when trying to download >2GB folders with .zip generation

**Comment by Wolfgang1966** [comment]
The fix seems to be a one-liner basically:

In lib/private/Streamer.php

exchange 
public function __construct(IRequest $request, int $size, int $numberOfFiles)

public function __construct(IRequest $request, float $size, int $numberOfFiles)

(line 56 in Nextcloud 19.0.3).

Didn't test that in depth, but at least got rid of the error message. The reason basically seems to be that PHP implicitely converts int to float as soon as a number overflow is about to occur. See https://www.php.net/manual/de/language.types.integer.php

**Comment by j-be** [comment]
Hit by the same issue on Nextcloud 20.0.2.2 and PHP 7.4 (Ubuntu 20.04).

@Wolfgang1966 your fix works on my side, thank you very much for sharing that.

**Comment by Wolfgang1966** [comment]
Please be aware that the fix improves the situation for sizes between 2GB and 4 GB. Above that it will result in corrupted ZIPs. 

So now I patched the constructor this way:

                if ($size > 0 && $size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
                        $this->streamerInstance = new ZipStreamer(['zip64' => false]);
                } else {
                        $this->streamerInstance = new TarStreamer();
                }

Above 4GB it will always create a tar archive. It may be less comfortable on Windows, but at least the archive is valid and there are enough tools out there which are able to handle them.

**Comment by j-be** [comment]
@Wolfgang1966 Thanks again!

I had closer look at the constructor as implemented (https://github.com/nextcloud/server/blob/master/lib/private/Streamer.php#L84) and I'm having a hard time understanding the train of thought there. It has been a while since I used PHP, but I read this as:

- if below 4GB use Zip32
- if above 4GB and `$request->isUserAgent($this->preferTarFor)` (for whatever that means) use TAR
- if above 4GB and **not** `$request->isUserAgent($this->preferTarFor)` do **not** use Zip64 on 32Bit architectutres (which I guess leads to the mentioned corrupted archives) and Zip64  on anything else

I see the point of using Zip32 as default whenever possible, as it is most likely the most widely supported among the three contenders here. What I don't understand is:

- Why is `$request->isUserAgent($this->preferTarFor)` only respected if the file is larger then 4GB? Why can't I always have TAR if I explicitly request it?
- Why doesn't it use Zip64 on 32Bit Architectures? I for one still use an ARMv7 32Bit board as Server for Nextcloud, which is plenty for personal use.

Shouldn't it be something like **(do NOT use the code below as is unless you want to break your Nextcloud!)**:
```php
// Give me TAR no matter what if I say I want that
if ($request->isUserAgent($this->preferTarFor)) {
    $this->streamerInstance = new TarStreamer();
// Zip32 as default if size and numberOfFiles allow it
} elseif ($size > 0 && $size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
    $this->streamerInstance = new ZipStreamer(['zip64' => false]);
// Depending on Zip64 support - not sure how one would determine that
} else {
    if (isZip64Supported) {
        $this->streamerInstance = new ZipStreamer(['zip64' => true]);
    } else {
        $this->streamerInstance = new TarStreamer();
    }
}

**Comment by szaimen** [comment]
Hi, do you mind creating a PR with your patch for further discussion?
Thank you!

**Comment by j-be** [comment]
@szaimen Assuming your comment was referring to my suggestion above: Done, see #27562.

I'd like to add that I'm still successfully running the fix proposed by @Wolfgang1966. I am using only Linux machines, and my Nextcloud is for personal use only. So TAR is no issue for me, I assume that is not true for most Windows users.

**Comment by lnwor** [comment]
This issue is still relevant, I'm still getting this error when trying to download multiple GB of data and setting float instead of int in size seems to completely fix the problem

**Comment by Hightmar** [comment]
> The fix seems to be a one-liner basically:
> 
> In lib/private/Streamer.php
> 
> exchange public function __construct(IRequest $request, int $size, int $numberOfFiles)
> 
> public function __construct(IRequest $request, float $size, int $numberOfFiles)
> 
> (line 56 in Nextcloud 19.0.3).
> 
> Didn't test that in depth, but at least got rid of the error message. The reason most likely is that PHP implicitely converts int to float as soon as a number overflow is about to occur. See https://www.php.net/manual/de/language.types.integer.php

Your answer is still valid with Nextcloud Hub II (23.0.3). 
Thank you!

**Comment by szaimen** [comment]
Closing due to https://github.com/nextcloud/documentation/pull/9071
