### ISSUE TITLE
Theming broken in Nextcloud 15.0.7

### ISSUE THREAD

**Issue by xelan** [nextcloud/server#15121]
### Steps to reproduce
1. Install Nextcloud 14.0.10
2. Ensure that theming works (change logo, slogan, ...)
3. Upgrade to Nextcloud 15.0.7
4. Theming does not work anymore (changes are apparently not applied anymore except for folder icon color)

Alternatively:

1. Install Nextcloud 15.0.7
2. Theming does not work

### Expected behaviour
Theming should continue to work as it did in NC 14

### Actual behaviour
The color is apparently applied to folder icons, but for example not for the header. The custom logos and login page texts are not shown. Changes of theming options are apparently stored in the database, uploaded files (e.g. background and logo) are stored in `data/appdata_ocd3456m7okf/theming/images`.

### Server configuration

**Operating system**:
Debian 9 (Stretch)

**Web server:**
Apache 2.4 (apache2  2.4.25-3+deb9u)

**Database:**
MariaDB 10.1 (mariadb-server-10.1  10.1.37-0+deb9u1)

**PHP version:**
PHP 7.0 (php7.0-common 7.0.33-0+deb9u3)

**Nextcloud version:** (see Nextcloud admin page)
14.0.10 (theming works), 15.0.7 (theming does not work)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Both variants tried, didn't manage to get the theming app work correctly on 15.0.7. I haven't tried older 15.0.x versions yet.

**Where did you install Nextcloud from:**
Source packages from https://download.nextcloud.com/server/releases/
Installation via `sudo -u www-data php occ maintenance:install --database "mysql" --database-name "nextcloud"  --database-user "nextcloud" --database-pass "nextcloud password here..." --admin-user "admin" --admin-pass "admin password here..."` but had the same issue with web-based install before.

Note: the Nextcloud instance is behind a reverse proxy.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => 'B/M2uSS9gZ665nqJZpk6Tpu+99aqhv',
  'secret' => 'w52PJLDjxkYXouDmhAh+H5Bhe68Lxv2EfVW3b66RKZR6pm6n',
  'trusted_domains' =>
  array (
    0 => 'cloud.example.com',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.7.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => 'not_the_real_password',
  'installed' => true,
  'instanceid' => 'ocd3456m7okf',
  'trusted_proxies' =>
  array (
    0 => '192.168.1.111',
    1 => '192.168.1.112',
    2 => '192.168.1.113',
  ),
  'overwritehost' => 'cloud.example.com',
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://cloud.example.com',
  'htaccess.RewriteBase' => '/',
  'maintenance' => false,
  'updater.release.channel' => 'stable',
  'updater.secret' => '$2y$10$7/efNg8.i2ljbrT5C84H5uZtS/l379PBg0w0..FZ15Lc/MQOMcCF6',
  'loglevel' => 2,
);
```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no (for testing/bug repro)

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:**
Current Firefox and Chrome

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Not applicable
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[...]
nfo: Repair info: Fixed 0 vcards","userAgent":"--","version":"14.0.10.0"}
{"reqId":"FcSlQJPAfyTcVFwy5KZo","level":1,"time":"2019-04-15T20:56:15+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::startCheckCodeIntegrity: Starting code integrity check...","userAgent":"--","version":"14.0.10.0"}
{"reqId":"FcSlQJPAfyTcVFwy5KZo","level":1,"time":"2019-04-15T20:56:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::finishedCheckCodeIntegrity: Finished code integrity check","userAgent":"--","version":"14.0.10.0"}
{"reqId":"FcSlQJPAfyTcVFwy5KZo","level":1,"time":"2019-04-15T20:56:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update successful","userAgent":"--","version":"15.0.7.0"}
{"reqId":"FcSlQJPAfyTcVFwy5KZo","level":1,"time":"2019-04-15T20:56:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"15.0.7.0"}
{"reqId":"FcSlQJPAfyTcVFwy5KZo","level":1,"time":"2019-04-15T20:56:19+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"15.0.7.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Not applicable
```
</details>

**Comment by loxK** [comment]
Seems similar to an issue I am facing too #15089

**Comment by xelan** [comment]
Thanks for your comment, I didn't find your issue before. So apparently the PHP version does not matter, and the issue occurs with both fresh installs and upgrades.

As even the theming texts are not shown at the login page, I think we can rule out caching issues or problems with the CSS generation. If I have time, I'll try older 15.0.x versions to see when the issue first occured.

**Comment by loxK** [comment]
And it doesn't happen with Nginx.... Do you direct acces or have an nginx reverse proxy in front of apache (I do)

Here is my apache config:

```
<VirtualHost *:80>
	# The ServerName directive sets the request scheme, hostname and port that
	# the server uses to identify itself. This is used when creating
	# redirection URLs. In the context of virtual hosts, the ServerName
	# specifies what hostname must appear in the request's Host: header to
	# match this virtual host. For the default virtual host (this file) this
	# value is not decisive as it is used as a last resort host regardless.
	# However, you must set it for any further virtual host explicitly.
	ServerName [redacted].io

	ServerAdmin webmaster@localhost
	DocumentRoot /srv/www

	# Available loglevels: trace8, ..., trace1, debug, info, notice, warn,
	# error, crit, alert, emerg.
	# It is also possible to configure the loglevel for particular
	# modules, e.g.
	#LogLevel info ssl:warn

	ErrorLog ${APACHE_LOG_DIR}/error.log
	CustomLog ${APACHE_LOG_DIR}/access.log combined

	Alias /nextcloud "/srv/www/nextcloud/"

	Header always set X-Content-Type-Options nosniff
	Header always set X-Frame-Options SAMEORIGIN
	Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains;"	
	
	<IfModule mod_env.c>
          # Add security and privacy related headers
          # Header set X-Content-Type-Options "nosniff"
          # Header set X-XSS-Protection "1; mode=block"
          # Header set X-Robots-Tag "none"
          # Header set X-Download-Options "noopen"
          # Header set X-Permitted-Cross-Domain-Policies "none"
          SetEnv modHeadersAvailable true
        </IfModule>

	<Directory /srv/www/nextcloud/>
          #Header set X-Content-Type-Options nosniff
	  Options +FollowSymlinks
	  AllowOverride All

	  <IfModule mod_dav.c>
	    Dav off
	  </IfModule>

	  SetEnv HOME /srv/www/nextcloud
	  SetEnv HTTP_HOME /srv/www/nextcloud

	</Directory>

	# For most configuration files from conf-available/, which are
	# enabled or disabled at a global level, it is possible to
	# include a line for only one particular virtual host. For example the
	# following line enables the CGI configuration for this host only
	# after it has been globally disabled with "a2disconf".
	#Include conf-available/serve-cgi-bin.conf
</VirtualHost>
```

**Comment by xelan** [comment]
We're using an apache2 as reverse proxy for HTTPs handling and failover/load balancing. I know, not so common :wink:, but we don't want too many different technology stacks in production.

So you switched from Nginx to Apache for the Nextcloud instance (not the reverse proxy) and now the theming doesn't work anymore?

Here's my apache config of the Nextcloud container:
```
<VirtualHost *:80>
    ServerAdmin webmaster@alpenedv.at
    DocumentRoot /var/www/nextcloud

    Redirect /.well-known/carddav https://cloud.example.com/remote.php/dav
    Redirect /.well-known/caldav https://cloud.example.com/remote.php/dav
    <Directory /var/www/nextcloud>
        Options -Indexes +FollowSymLinks +MultiViews
        AllowOverride All
        Require all granted
    </Directory>

    ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
    <Directory "/usr/lib/cgi-bin">
        AllowOverride None
        Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
        Require all granted
    </Directory>

    ErrorLog /var/log/apache2/cloud-error.log
    LogLevel warn
    CustomLog /var/log/apache2/cloud-access.log combined

    RemoteIPHeader X-Forwarded-For
    RemoteIPTrustedProxy 192.168.1.111 192.168.1.112 192.168.1.113
    RemoteIPInternalProxy 192.168.1.111 192.168.1.112 192.168.1.113

</VirtualHost>
```

Apache configuration of the reverse proxy:
```
<VirtualHost *:443>
        ServerName cloud.example.com

        ServerAdmin webmaster@alpenedv.at

        SSLEngine on
        SSLCertificateFile /etc/certs/cloud.example.com.crt
        SSLCertificateKeyFile /etc/certs/cloud.example.com.key
        SSLCertificateChainFile /etc/certs/letsencrypt_intermediate.crt

        Header always set Strict-Transport-Security "max-age=15552000"

        # don't forward Let's Encrypt challenges to the app
        ProxyPass /.well-known/acme-challenge !
        ProxyPass "/"  "http://vm1234cloudcustomera/"
        ProxyPassReverse "/"  "http://vm1234cloudcustomera/"

        DocumentRoot /var/www/letsencrypt

        <Directory /var/www/letsencrypt>
                Options -Indexes +FollowSymLinks +MultiViews
                Require all granted
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/cloudcustomera-error.log
        CustomLog ${APACHE_LOG_DIR}/cloudcustomera-access.log combined

        ErrorDocument 502 /var/www/html/502.html
</VirtualHost>

<VirtualHost *:80>
        ServerName cloud.example.com
        Redirect permanent / https://cloud.example.com/
</VirtualHost>
```

**Comment by loxK** [comment]
For what it's worth, I got it working with proper apache remoteip configuration:

```
RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 10.0.4.10
```

If I remove those lines the problem is back.

**Comment by xelan** [comment]
Thanks, I'll try to play around with the remoteip settings. So far my configuration worked well for all applications... What I don't get after all is that even the strings on the login page are not changed :confused:

**Comment by kukukk** [comment]
Hi!

I'm facing the same problem: name, slogan, color, logo, login image - none of them are changed.

I'm running Nextcloud dockerized and it is behind an Apache reverse proxy to handle HTTPS. 

I was using Nextcloud 13. Theming worked properly.
First I upgraded to Nextcloud 14.0.10. Theming was still working.
After upgrading to 15.0.7 theming got broken.

The configuration for the reverse proxy was not modified during the upgrade process.

**Comment by kesselb** [comment]
Does this problem still occur? Some of you posted mentioned reverse proxy. Please configure `trusted_proxies` and (e.g. if you are using apache2) define `overwriteprotocol`. https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html for more details.

**Comment by kukukk** [comment]
Seems that setting `trustied_proxies` solves the problem. But it is strange that it worked before.

One small complication is that both reverse proxy and Nextcloud are running dockerized, so I will have to assign static IP for the reverse proxy docker container.

**Comment by kesselb** [comment]
> But it is strange that it worked before.

Sorry. The behavior changed with Nextcloud 15.

**Comment by xelan** [comment]
Thank you for the response, @kesselb. I'll try upgrading to the latest NextCloud Stable and reconfiguring the reverse proxy settings as well as `trusted_proxies`.
