### ISSUE TITLE
NextCloud Migrationtool download broken

### ISSUE THREAD

**Issue by vinzenzh** [nextcloud/server#15126]
If you want to download the migration tool from https://download.nextcloud.com/server/installer/migrator/index.php with wget you get an index.php.1 with the content:

"Could not find config.php. Is this file in the "updater" subfolder of Nextcloud?"

### Steps to reproduce
1. Try to download: wget https://download.nextcloud.com/server/installer/migrator/index.php
2. Open the file with texteditor

### Expected behaviour
I get the migration-tool.

### Actual behaviour
It seems that the server executes the index.php to download instead of getting the source code. Maybe a configuration mistake in apache?

### Server configuration

**Operating system**:
Debian 8 64bit

**Web server:**
apache2.4
**Database:**
MariaDB
**PHP version:**
PHP Version 5.6
**Owncloud version:** (see Nextcloud admin page)
10.0.4

**Comment by rgrae81** [comment]
I have the same problem

I had a look into the index.php file and this line:
"Could not find config.php. Is this file in the "updater" subfolder of Nextcloud?"
is the only content of the file.

Operating system:
Ubuntu 18.04.2 LTS (4.18.0-17 HWE)

Web server:
apache2.4.29
Database:
SQLite
PHP version:
PHP Version 7.1.18
Owncloud version: 10.0.10

**Comment by AdamPerkins** [comment]
I can confirm this bug. The file _index.php.1_ doesn't contain PHP code, insteat it holds an error message.

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure

**Comment by MorrisJobke** [comment]
Should work now again. Sorry for the trouble.
