### ISSUE TITLE
Send a mail to a User to reset his password

### ISSUE THREAD

**Issue by LeoCaplin** [nextcloud/server#15130]
Hello,

I wanted to know if it would be possible to reset a user’s password from the user panel by sending him an email.

I know that currently it is possible to send an email to set the password when an account is created. But it seems to me that to reset a password you have to go through the login page and it can be really anoying if you want to do this for hundreds peoples or more ...

Thank you for your help.

**Comment by ChristophWurst** [comment]
I would suggest to ask at https://help.nextcloud.com/.

Cheers
