### ISSUE TITLE
Change the home icon when looking at the trashbin

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#15155]
**Is your feature request related to a problem? Please describe.**

I find it a bit strange that the "home" icon is being shown when I'm in the trash bin view

**Describe the solution you'd like**

I'd like the Home icon to be replaced with a trash icon when I'm in the trash bin view

**Describe alternatives you've considered**

None. It's not logical to see a home icon there.

**Additional context**

Nothing to add.

**Comment by jancborchardt** [comment]
Absolutely agree. The icon should be `icon-delete` instead of `icon-home` and the alt text `Deleted files` instead of `Home`.

I tried to dig into the code but have not found a way to easily change the icon. This would need to be taken over by @nextcloud/javascript

**Comment by DaniloBenevides** [comment]
Hello is anyone working on this ?

**Comment by jancborchardt** [comment]
@DaniloBenevides not yet, no. You can pick it up if you want. :) Let us know if there are any issues, you can either ask here or in the IRC channel #nextcloud-dev

I think there needs to be input from @nextcloud/javascript here though as I don't know if this is reasonably simple to do.

**Comment by gary-kim** [comment]
Not yet closed.
