### ISSUE TITLE
Usernames: trailing spaces problem (LDAP)

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/server#15167]
### Steps to reproduce
I don't know how the user triggered this bug, I think he logged in with a trailing space after his username on first use. Subsequent logins (with correct user name) failed with the error shown in the Nextcloud log.

### Further analysis
ldap_search and the mysql "=" operator are ignoring trailing spaces, so login also works with trailing spaces. I checked the DB and found the "username_space_" in the table oc_storages (mount_point) and oc_mounts (id, "home::username_space_"). After fixing the 2 entries the error disappeared.
Other occurences (e.g. oc_ldap_user_mapping, oc_preferences) of the username were correct without the trailing space. Also the folder in filesystem has no trailing space and the uid in LDAP is also correct.

### Expected behaviour
Trailing spaces should be removed from username (on mobile devices, its maybe inserted automatically by autocomplete), or the username for creating the home folder should be taken from the LDAP uid field, not from input, so further logins without space should not fail.

### Actual behaviour
Error message on subsequent logins.

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.4

**Database:** MariaDB (Debian package)

**PHP version:** 7.2

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** Updater

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+-----------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                 |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                               |
| homeFolderNamingRule          | attr:uid                                                                                                        |
| lastJpegPhotoLookup           | 0                                                                                                               |
| ldapAgentName                 | cn=proxy-nextcloud,ou=service,o=uni                                                                             |
| ldapAgentPassword             | ***                                                                                                             |
| ldapAttributesForGroupSearch  |                                                                                                                 |
| ldapAttributesForUserSearch   | sn;uid;mail                                                                                                     |
| ldapBackupHost                |                                                                                                                 |
| ldapBackupPort                |                                                                                                                 |
| ldapBase                      | ou=user,o=uni                                                                                                   |
| ldapBaseGroups                | ou=user,o=uni                                                                                                   |
| ldapBaseUsers                 | ou=user,o=uni                                                                                                   |
| ldapCacheTTL                  | 10800                                                                                                           |
| ldapConfigurationActive       | 1                                                                                                               |
| ldapDefaultPPolicyDN          |                                                                                                                 |
| ldapDynamicGroupMemberURL     |                                                                                                                 |
| ldapEmailAttribute            | mail                                                                                                            |
| ldapExperiencedAdmin          | 1                                                                                                               |
| ldapExpertUUIDGroupAttr       |                                                                                                                 |
| ldapExpertUUIDUserAttr        | uid                                                                                                             |
| ldapExpertUsernameAttr        | uid                                                                                                             |
| ldapGidNumber                 | gidNumber                                                                                                       |
| ldapGroupDisplayName          | cn                                                                                                              |
| ldapGroupFilter               |                                                                                                                 |
| ldapGroupFilterGroups         |                                                                                                                 |
| ldapGroupFilterMode           | 0                                                                                                               |
| ldapGroupFilterObjectclass    |                                                                                                                 |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                    |
| ldapHost                      | ldap://localhost                                                                                                |
| ldapIgnoreNamingRules         |                                                                                                                 |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(uid=%uid)(|(mail=%uid)))(|(eduPersonAffiliation=*)(thuEduStatus=XXX))) |
| ldapLoginFilterAttributes     | mail                                                                                                            |
| ldapLoginFilterEmail          | 0                                                                                                               |
| ldapLoginFilterMode           | 0                                                                                                               |
| ldapLoginFilterUsername       | 1                                                                                                               |
| ldapNestedGroups              | 0                                                                                                               |
| ldapOverrideMainServer        |                                                                                                                 |
| ldapPagingSize                | 0                                                                                                               |
| ldapPort                      | 389                                                                                                             |
| ldapQuotaAttribute            |                                                                                                                 |
| ldapQuotaDefault              |                                                                                                                 |
| ldapTLS                       | 0                                                                                                               |
| ldapUserAvatarRule            | default                                                                                                         |
| ldapUserDisplayName           | sn                                                                                                              |
| ldapUserDisplayName2          | givenname                                                                                                       |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(|(eduPersonAffiliation=*)(thuEduStatus=XXX)))                               |
| ldapUserFilterGroups          |                                                                                                                 |
| ldapUserFilterMode            | 0                                                                                                               |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                   |
| ldapUuidGroupAttribute        | auto                                                                                                            |
| ldapUuidUserAttribute         | auto                                                                                                            |
| turnOffCertCheck              | 0                                                                                                               |
| turnOnPasswordChange          | 0                                                                                                               |
| useMemberOfToDetectMembership | 1                                                                                                               |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------+

</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Windows

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"4Qks2A7Egnji7v4dagfx","level":3,"time":"2019-04-18T13:42:18+00:00","remoteAddr":"XXX","user":"alroXXXX","app":"index","method":"GET","url":"\/apps\/accessibility\/js\/accessibility?v=0","message":{"Exception":"RuntimeException","Message":"Storage could neither be inserted nor be selected from the database","Code":0,"Trace":[{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Cache\/Cache.php","line":104,"function":"__construct","class":"OC\\Files\\Cache\\Storage","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"}]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Storage\/Home.php","line":71,"function":"__construct","class":"OC\\Files\\Cache\\Cache","type":"->","args":[{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"}]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":393,"function":"getCache","class":"OC\\Files\\Storage\\Home","type":"->","args":["",{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"}]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":393,"function":"getCache","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["",{"cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\Files_Trashbin\\Storage"}]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Config\/UserMountCache.php","line":92,"function":"getCache","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[]},{"function":"OC\\Files\\Config\\{closure}","class":"OC\\Files\\Config\\UserMountCache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Config\/UserMountCache.php","line":93,"function":"array_filter","args":[[{"__class__":"OCA\\Files_Sharing\\SharedMount"},"*** sensitive parameter replaced ***"],{"__class__":"Closure"}]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Config\/MountProviderCollection.php","line":188,"function":"registerMounts","class":"OC\\Files\\Config\\UserMountCache","type":"->","args":[{"__class__":"OC\\User\\User"},[{"__class__":"OCA\\Files_Sharing\\SharedMount"},"*** sensitive parameter replaced ***"]]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Filesystem.php","line":449,"function":"registerMounts","class":"OC\\Files\\Config\\MountProviderCollection","type":"->","args":[{"__class__":"OC\\User\\User"},[{"__class__":"OCA\\Files_Sharing\\SharedMount"},"*** sensitive parameter replaced ***"]]},{"file":"\/data\/nextcloud_15\/lib\/private\/Files\/Filesystem.php","line":376,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["alroXXXX"]},{"file":"\/data\/nextcloud_15\/lib\/private\/legacy\/util.php","line":308,"function":"init","class":"OC\\Files\\Filesystem","type":"::","args":["alroXXXX","\/alroXXXX\/files"]},{"file":"\/data\/nextcloud_15\/lib\/base.php","line":986,"function":"setupFS","class":"OC_Util","type":"::","args":[]},{"file":"\/data\/nextcloud_15\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/data\/nextcloud_15\/lib\/private\/Files\/Cache\/Storage.php","Line":82,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/73.0.3683.103 Safari\/537.36","version":"15.0.7.0"}

</details>

**Comment by blizzz** [comment]
sounds as if the login controller would not trim the provided loginname.  on the other hand, while it is kept in the session, we don't use the login name for anything like that (you an login with more features), but the user id.

**Comment by alx-tuilmenau** [comment]
fixed by https://github.com/nextcloud/server/pull/18183
