### ISSUE TITLE
Add Opt-Out for "shared by" in link sharing

### ISSUE THREAD

**Issue by Liwindo** [nextcloud/server#15163]
If you share a file by link there is shown by whom the file is shared. I request for an opt-out that strangers can not see what name the sharing person in the cloud has. On the one hand for privacy reason and on the other for security reason.

**Comment by skjnldsv** [comment]
Would you want a global instance setting or user setting?

**Comment by kesselb** [comment]
Looks similar to https://github.com/nextcloud/server/issues/9789

**Comment by skjnldsv** [comment]
@kesselb are you sure, it doesn't look similar to me! :thinking: :smile:

**Comment by Liwindo** [comment]
In my opinion it should be global, so the admin can set restrictions if needed. If it's just for the users there is no control option.

**Comment by Liwindo** [comment]
Can someone please assign this to a milestone? In my opinion all necessary informations are given.

**Comment by kesselb** [comment]
![bildschirmfoto 2018-06-08 um 08 44 23](https://user-images.githubusercontent.com/245432/41143087-5567ecea-6af8-11e8-82ed-815b0c9788f1.png)

You are talking about "von Morris geteilt" right?
