### ISSUE TITLE
"The subscription key had an invalid format." on page load (no key entered at all)

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/server#15160]
### Actual behaviour
![image](https://user-images.githubusercontent.com/22591354/56363176-e47b3780-61eb-11e9-8c91-59884bb3fcb6.png)

"The subscription key had an invalid format." is shown when I open the support settings section even though I've never entered any value there...

### Expected behaviour
This warning should only be shown if I really enter a wrong value there (and press submit?)...

#### Nextcloud: 16.0.0RC2

**Comment by kesselb** [comment]
@MorrisJobke where is the source of the support app? :thinking:

**Comment by MorrisJobke** [comment]
It's currently in a private repo, but I will fix this. Plan is to make it public with 17.

**Comment by MorrisJobke** [comment]
I can't reproduce this. After a page refresh this warning is also typically gone. :/ Anything you did special? I guess it was an upgrade from 15 to 16, right?

**Comment by violoncelloCH** [comment]
Yes it was upgraded from 15 to 16RC1 and now to RC2 but it appears every time I open it... Also after refreshing the page :/

**Comment by MorrisJobke** [comment]
@violoncelloCH Could you check the table `oc_appconfig` for the `support` app then? Maybe I can spot it in there.

**Comment by violoncelloCH** [comment]
this is the output:
```
+---------+-------------------+-------------+
| appid   | configkey         | configvalue |
+---------+-------------------+-------------+
| support | enabled           | yes         |
| support | installed_version | 1.0.0       |
| support | last_error        | 4           |
| support | types             |             |
+---------+-------------------+-------------+
```

**Comment by MorrisJobke** [comment]
I found the issue and fixed it. In the next maintenance releases (14.0.11, 15.0.8 and 16.0.1) this problem is solved.

**Comment by gary-kim** [comment]
> It's currently in a private repo, but I will fix this. Plan is to make it public with 17.

Any update on this? We're way past 17 at this point.
