### ISSUE TITLE
link sharing not possible when expiration date enforced

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/server#15169]
### Steps to reproduce
1. enforce sharing of links to e.g. 7 days
2. try to create a link share

### Expected behaviour
file should be shared with max expiration enforced

### Actual behaviour
the error message: "unable to create a link share" appears and a spinner at a strange position:
![image](https://user-images.githubusercontent.com/22591354/56394715-727d0f80-6238-11e9-84e7-ca977adc5a9c.png)

**Nextcloud version:** 16.0.0RC2

cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
Arf, wrong issue.
This I cannot reproduce on 17 :/

**Comment by violoncelloCH** [comment]
just tested it again on 17 and also on a production 16.0.1 and can't reproduce this any more :)

**Comment by liuxyCN** [comment]
same problem
