### ISSUE TITLE
Idea: "Warning: your version will not be supported after Feb 2019"

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#15174]
**Is your feature request related to a problem? Please describe.**
I don't want to upgrade to any new version right when it is available. I want to wait until ~3 months before the End of Life and then upgrade to the most recent version.
1. In settings, I see my nextcloud version, and the information that a new nextcloud version is available, but **no info until when my version is still supported**.
2. Users in admin group receive notification "nextcloud version is available, but **no info until when my version is still supported**."

**Describe the solution you'd like**
1. In settings, it should show: Nextcloud version XY.YX. supported until DD.MM.YYYY It is insecure to run this version after this date.
2. Users in admin group should receive notification every month starting 6 months before End of Life "Nextcloud version XY.YX. supported until DD.MM.YYYY It is insecure to run this version after this date."

**Describe alternatives you've considered**

- This is reduced implementation of what is proposed at https://github.com/nextcloud/server/issues/14230
- Another alternative is just a link from the version info in settings to this page https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Additional context**
This idea was inspired by this discussion https://www.reddit.com/r/selfhosted/comments/5ybmf1/nextcloud_scanning_peoples_owncloud_and_nextcloud/

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by alexanderdd** [comment]
The minimal implementation would be a link from the version info in settings to this page https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by szaimen** [comment]
> The minimal implementation would be a link from the version info in settings to this page https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

cc @nextcloud/designers is this something we should do?

**Comment by skjnldsv** [comment]
It woulld be nice yes!
But it would mean we should have a date-aware mechanism.

Or maybe we can check when the first beta is released for the upcoming major and start displaying a warning?

Like when 22 beta 1 is released, all 19 show a warning stating `The versions is about to reach end of life, please upgrade to a more recent version` ?

cc @MorrisJobke @blizzz @nickvergessen @ChristophWurst ?
Thoughts?

**Comment by MorrisJobke** [comment]
> But it would mean we should have a date-aware mechanism.
> 
> Or maybe we can check when the first beta is released for the upcoming major and start displaying a warning?

Just a classic dead man switch, right? Build time older than 1 year? Show the warning to admins. More than 1.5 years? Show th e warning to all users. More than 2 years? Disable manipulations like file upload or new users?

All are just ideas but I remember we had a rough plan like this already. Let me check the issue list.

**Comment by MorrisJobke** [comment]
let's close this in favor of #14230 (but maybe with a less aggressive time table. I would warn admins early, but users should not be notified too early as they can't do much then.
