### ISSUE TITLE
Issue with Calender reminder on Mobile Apps

### ISSUE THREAD

**Issue by Mululu** [nextcloud/server#15172]
### Actual behaviour
- The following scenario:

User 1 creates a calendar and shares it with user 2. There are several appointments in this calendar. Each appointment has a reminder 1 day before.

User 1 has an Android phone and uses the Davx5 app and it will display 1 day's reminder

User 2 also uses an Android phone with the Davx5 app. It will not show any reminders.

In the web browser, are the same problem

Either the calendar is not fully shared with reminders, or the Davx5 app can not read anything or is not assigned by nextcloud.

If I give the user 2 a write permission to test and only open the appointment and update without changing anything, the 1-day reminder will also be displayed on the Android user 2.

Enclosed screenshots from Google Calendar once from user 1 and user 2. Both have the same calendar from nextcloud.

With Apple the same problem could be determined

[User1](https://feuerwehr-gebirge.de/wp-content/uploads/2019/04/User-1.png)
[User2](https://feuerwehr-gebirge.de/wp-content/uploads/2019/04/User-2.png)

**Comment by j-ed** [comment]
I think you should export both calendar events directly after they've been created and before any sync activity has been taken place to ics files. Please append the content of these ics files to this issue ticket.

**Comment by georgehrke** [comment]
Nextcloud automatically removes alarms from read-only calendars, because most clients need write access in order to acknowledge the receival of an alarm. So if you have Alarms in a read-only calendar, you end up being spammed by alarms that you can't turn off.

**Comment by Mululu** [comment]
Hello,

it would be really great if you could set whether users without calendar permissions should receive reminders or not.

We share our fire brigade calendar via Nextcloud and everyone should get a reminder 1 day before the fire service. However, I would have to give everyone or the group write access to the calendar. But that does not make sense.

Can you add this feature please?

Or is there a possibility to change this by means of some coding?

Thank you!
