### ISSUE TITLE
Enhance of the post-uploading page of a share folder

### ISSUE THREAD

**Issue by meaz** [nextcloud/server#15176]
I have used the possibility to create a share folder with upload ability only with some colleagues. Like this, there were able to send me there work, but couldn't see other people work.

The problem I faced is that lot of users also wrote me to ask if they did succeed in uploading their file into this folder.

I think the reason why is simple. At the moment, when you upload a file, here is what you get when you succeed:
![nextcloud](https://user-images.githubusercontent.com/13604424/56433407-14503b00-62d1-11e9-8e7a-a977e6bda3ec.png)

The name of the uploaded file appears very small (in the purple rectangle I added for this screencapture) and people that don't pay attention can miss it.

So it would be nice to have something more obvious, for example something like this:
![nextcloudMU](https://user-images.githubusercontent.com/13604424/56433485-4b265100-62d1-11e9-8318-3c0362711d40.png)

**Comment by kesselb** [comment]
@nextcloud/designers

**Comment by skjnldsv** [comment]
I will close ad similar to the solution of https://github.com/nextcloud/server/issues/4164
