### ISSUE TITLE
Remember the sorted column per directory

### ISSUE THREAD

**Issue by synthead** [nextcloud/server#15170]
**Is your feature request related to a problem? Please describe.**
Doesn't remember the sorted column per directory (only globally)

**Describe the solution you'd like**
Remember the sorted column per directory

**Describe alternatives you've considered**
None

**Additional context**
n/a

**Comment by violoncelloCH** [comment]
related to #12161

**Comment by tobiasKaminsky** [comment]
This is not working for me:
- open up files app
- sort by size
-  go into a subfolder, see also sort by size
- sort by name
- go up to root, see sort by name, but should be sort by size

**Comment by skjnldsv** [comment]
We implemented something in that direction for 27 and future, which is remember per view (`trashbin` sorting will be different than `files`, than `shared files`... etc

**Comment by skjnldsv** [comment]
> **Is your feature request related to a problem? Please describe.** Doesn't remember the sorted column per directory (only globally)
> 
> **Describe the solution you'd like** Remember the sorted column per directory
> 
> **Describe alternatives you've considered** None
> 
> **Additional context** n/a
