### ISSUE TITLE
Low memory mode for cron

### ISSUE THREAD

**Issue by YoSijo** [nextcloud/server#15189]
**Is your feature request related to a problem? Please describe.**
The cronjob is running a "SELECT * FROM `oc_filecache`" which is very unpleasant for the memory usage with a table size of 50GB+.

**Describe the solution you'd like**
A low memory option in the configuration that causes the cronjob to read the table in parts. If necessary with dependency to php-sqlite to generate a temporary instance to process the records.

**Describe alternatives you've considered**
Mehr hässlicher swap für den Server.

**Additional context**
I couldn't figure out the reason why he's doing this query. With a tip where to look, I can still pass this information.

**Comment by YoSijo** [comment]
I think the origin of the problem comes from [ownbackup](https://github.com/pbek/ownbackup). See [here](https://github.com/pbek/ownbackup/issues/31).

**Comment by rullzer** [comment]
There is no way we can fix that in the server. That will have to be fixed in ownbackup
