### ISSUE TITLE
User not logged out after browser closed

### ISSUE THREAD

**Issue by dahumph** [nextcloud/server#15190]
**steps to reproduce:**

login via web interface
close browser
open browser
navigate to nextcloud

**expected behavior:**
after closing and reopening, the login page promts for login

**actual behavior:**
user is still logged in, cloud fully useable

NC Version 15.0.2.0
OS Ubuntu 16.04.6
PHP 7.0.33-0ubuntu0.16.04.3

config.php:

    'remember_login_cookie_lifetime' => 0,
    'session_lifetime' => 60*5,
    'session_keepalive' => false,

session times out after 5 minutes as intended by _'session_lifetime' => 60*5,_ but the session is not logged out when browser is closed.

**Comment by kesselb** [comment]
`'remember_login_cookie_lifetime' => 0,` worked for me with nextcloud 16. Do you still see this issue?

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
