### ISSUE TITLE
CSP nonce looks like broken

### ISSUE THREAD

**Issue by JBScoutBerlin** [nextcloud/server#15195]
I'm running some NCs with version 15.0.7 and also some with version 16 RC2.
All apps ( defaults and also from the store ), including our own in house apps, produces a lot of errors regarding CSP / Content-Security-Policy.

Our in house apps, build with Angular 7.x, even broke up and don't work anymore due the CSP.

For my understanding of CSP with nonce the implementation on both NC-trees are broken as the nonce in the policy don't match the nonce that is delivered with the pages NC produced.

According to
https://developers.google.com/web/fundamentals/security/csp/#if_you_absolutely_must_use_it
the nonce must match between the one on a page and the one in the policy. That is not the case with NC. 

And also according to the same page the nonce should be new generated on every page request and that is also not the case with NC.

As I'm right the nonce will be a new one on every request in the policy but only ones for a session for the pages ( as it will be the same during a session ).

**Comment by rullzer** [comment]
I guess this is related to https://github.com/nextcloud/server/issues/15196 and you are not letting nextcloud do the full CSP generation.

The nonce is generated on each page load. As i would be very surprised if the nonces are broken. (because that would mean that Nextcloud is broken for all people in a modern browser).

**Comment by JBScoutBerlin** [comment]
> I guess this is related to #15196 and you are not letting nextcloud do the full CSP generation.
> 
> The nonce is generated on each page load. As i would be very surprised if the nonces are broken. (because that would mean that Nextcloud is broken for all people in a modern browser).

Hm .. strange .... Our Apache soesn't set any CSP-headers anymore. 

Brings be to the stupid question: 
how would I let NC let do the full CSP generation ?

And then the next stupid question:
how came that the nonce in the header is not the same as in the pages NC is generation ? 

And to be honest - I get on every app request for all apps errors due CSP blocking access inline ( 3 to 5 errors depending on the app ) - but the apps still look like to work.

I'm real confused so sorry for the questions.

**Comment by JBScoutBerlin** [comment]
> > I guess this is related to #15196 and you are not letting nextcloud do the full CSP generation.
> > The nonce is generated on each page load. As i would be very surprised if the nonces are broken. (because that would mean that Nextcloud is broken for all people in a modern browser).
> 
> Hm .. strange .... Our Apache soesn't set any CSP-headers anymore.
> 
> Brings be to the stupid question:
> how would I let NC let do the full CSP generation ?
> 
> And then the next stupid question:
> how came that the nonce in the header is not the same as in the pages NC is generation ?
> 
> And to be honest - I get on every app request for all apps errors due CSP blocking access inline ( 3 to 5 errors depending on the app ) - but the apps still look like to work.
> 
> I'm real confused so sorry for the questions.

OK, blame on me. The nonce in the header *is* the same as in the pages - reminder for myself: opening the source view in a browser triggers a new request to the server.

So, both points of my initial post where wrong. 

But that don't solve the problem, that all apps fire errors about CSP is blocking access inline ( ""script-src"") even they look like to work. And that our own Angular7 apps don't work anymore with the same errors. But that's maybe something that can be solved in the forums.

So I will close this bug report myself ;) But maybe someone who reads here has a hint for me how to solve the issues.

**Comment by ovk** [comment]
Info for anyone who is still seeing requests blocked by CSP in Firefox (even without any extensions) - this appears to be a bug in Firefox. 

Details are here https://bugzilla.mozilla.org/show_bug.cgi?id=1591807
