### ISSUE TITLE
Optional opt-out of generating CSP

### ISSUE THREAD

**Issue by JBScoutBerlin** [nextcloud/server#15196]
As Nextcloud sets the CSP on every request I would suggest to make this optional via a config value.

Reason for this is that in some usecases some may need some individual settings for there own apps and so handle the setup of CSP self ( globally or on basis of apps by setting headers on the webserver ).

But to make Nextcloud still be a safe place this should be an optional opt-out-setting.

**Comment by xf-** [comment]
you can remove/replace header with a webserver.
A bad idea to disable CSP and maybe used as workaround for the really problem/incorrect configuration.

**Comment by JBScoutBerlin** [comment]
> you can remove/replace header with a webserver.
Yes, you can always first let do one system the work, and then replace the work with a second system. 

> A bad idea to disable CSP and maybe used as workaround for the really problem/incorrect configuration.

I don't want to disable CSP at all. 
But where do you configure CSP in Nextcloud ?

**Comment by rullzer** [comment]
You can't configure the CSP yourself.
We try to tighten our CSP with each release. But for example if you enable talk the CSP is different (as we need to allow requests to the TURN/STUN servers etc).

Implementing this will result in a functionality that is only used by a hand full of people. And thus can break at any time.

As suggested by @xf- you can just overwrite the header in your webserver. But I would suggest you just let Nextcloud handle it.

**Comment by rullzer** [comment]
Ah no scratch that. (it is early) you can't set your own CSP as the nonce is re-generated on each request.
