### ISSUE TITLE
Google Drive sub folder content not loading up

### ISSUE THREAD

**Issue by hykilpikonna** [nextcloud/server#15191]
When I open the google external drive in nextcloud, the contents in the base folder shows up, however, when I open a sub folder in my google drive, "No files in here" is shown.

### Steps to reproduce
1. Setup google external drive as in the official tutorial. (Create a google api key and etc.)
2. Open a sub folder under the google external drive.

### Expected behaviour
Files under the sub folder would show up.

### Actual behaviour
"No files in here" is shown.

Screenshot: Sub folder that doesn't work:
![image](https://user-images.githubusercontent.com/22280294/56500798-500a2100-64da-11e9-94fe-10e054563003.png)

Screenshot: Base folder that works:
![image](https://user-images.githubusercontent.com/22280294/56500841-631cf100-64da-11e9-80a1-75cbcbb05f99.png)

### Server configuration

**Operating system**: Arch Linux (`x86_64 Linux 5.0.8-arch1-1-ARCH`)

**Web server:** `Nginx/1.14.2`

**Database:** `Mysql Ver 15.1 Distrib 10.3.14-MariaDB, for Linux (x86_64) using readline 5.1`

**PHP version:** `PHP 7.3.4 (cli) (built: Apr  5 2019 12:40:33) ( NTS )`

**Nextcloud version:** `Nextcloud 15.0.7-1`

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Arch Pacman

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
$ sudo -u http php occ app:list
The current PHP memory limit is below the recommended value of 512MB.
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - apporder: 0.6.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - drawio: 0.9.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_external_gdrive: 0.4.0
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.4.0
  - files_readmemd: 1.0.2
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.6
  - password_policy: 1.5.0
  - phonetrack: 0.5.0
  - provisioning_api: 1.5.0
  - quicknotes: 0.1.6
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - social: 0.1.4
  - spreed: 5.0.3
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - cospend
  - encryption
  - ojsxc
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
$ sudo -u http php occ config:list system
The current PHP memory limit is below the recommended value of 512MB.
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.hydev.pw",
            "nc.hydev.org"
        ],
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "https:\/\/nc.hydev.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587"
    }
}
```
</details>

**Are you using external storage, if yes which one:** Google Drive

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** What is that...

### Client configuration
**Browser:** Google Chrome 73.0.3683.103 (x64)

**Operating system:** Windows 10 1809 Build 17763.437

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
It's 36MB large... How can I paste everything here?

All the logs are basically saying:
{"reqId":"***REMOVED SENSITIVE VALUE***","level":3,"time":"2019-04-22T12:24:48+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"hykilpikonna","app":"PHP","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications?format=json","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/usr\/share\/webapps\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.7.0"}

BTW how can I disable this log message?
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
There are no browser logs relating to this issue.
```
</details>

**Comment by violoncelloCH** [comment]
could you specify which official tutorial you cite?
are you using https://github.com/NastuzziSamy/files_external_gdrive ? then please report your problem there...

**Comment by kesselb** [comment]
> BTW how can I disable this log message?

https://github.com/nextcloud/server/issues/10655

**Comment by hykilpikonna** [comment]
> > BTW how can I disable this log message?
> 
> #10655

Thanks

**Comment by hykilpikonna** [comment]
> could you specify which "official tutorial" you cite?
> are you using https://github.com/NastuzziSamy/files_external_gdrive ? then please report your problem there...

I was looking at this tutorial: 
https://docs.nextcloud.com/server/9/admin_manual/configuration_files/external_storage/google.html

I just realized that it's outdated and I'm using `files_external_gdrive`.
I reposted the issue on the `files_external_gdrive` repo: https://github.com/NastuzziSamy/files_external_gdrive/issues/45
