### ISSUE TITLE
OCP\ICache::set not deleted after time to live

### ISSUE THREAD

**Issue by tacruc** [nextcloud/server#15208]
### Steps to reproduce
Use OC\Cache as caching implementation
1. OCP\ICache::set($key, $value, $ttl=120)
2. wait one day
3. Call OCP\ICache::get($key) 
the value is still cached.

### Expected behaviour
I would expect that the value is null

### Actual behaviour
the original value is returned

### Server configuration

**Operating system**:
OpenSuse Tumbleweed

**Web server:**
apache2

**Database:**
sqllite

**PHP version:**
7.3.4

**Nextcloud version:** (see Nextcloud admin page)
git master

**Comment by tacruc** [comment]
There is a second minor issue in the function or the documentation, it says you can store a mixed, but  array's as values are not stored probably, one has to manually json_encode and decode them.

**Comment by rullzer** [comment]
The ttl is a minimum ttl. On user login old files will be cleaned up if I'm not mistaken.

**Comment by tacruc** [comment]
@rullzer  thanks for that hint.
