### ISSUE TITLE
Code integrity check shows extra .htaccess file in not existing folder (15.0.7)

### ISSUE THREAD

**Issue by rw71** [nextcloud/server#15201]
I updated to 15.0.7 and still have the problem described here: https://github.com/nextcloud/server/issues/13842

Now the folder looks different: 

Results
=======
- core
	- EXTRA_FILE
		- lib/private/oc_tmp_aY5Srw-folder/.htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [lib/private/oc_tmp_aY5Srw-folder/.htaccess] => Array
                        (
                            [expected] => 
                            [current] => 1477fdbb30aefd584e8fea6f678deee1aaa61598f5a65023998f60fc76249124729165f7ba51206146de2d42e0d2054b3049ab90bffd04e16736a4aa8f9b3b82
                        )

                )

        )

)

How can I get rid of this?

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
