### ISSUE TITLE
Sharing recommendations causes jquery autocomplete warning

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15217]
### Steps to reproduce
1. Open the sharing sidebar
2. Don't enter anything
3. Wait

### Expected behaviour
No errors, just see recommendations

### Actual behaviour
See recommendations but also `cannot call methods on autocomplete prior to initialization; attempted to call method 'option'`

### Server configuration

**Nextcloud version:** 16 RC2

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
