### ISSUE TITLE
warn when updating an app where the directory is not owned by www-data

### ISSUE THREAD

**Issue by CSchank** [nextcloud/server#15220]
**Is your feature request related to a problem? Please describe.**
I had installed an external plugin (share-renamer in my case) by downloading it from Git, and unpacking the archive. I unpacked with a different user than the www-data user, however. As a result, the app worked fine, until Nextcloud updated and the app stopped working. The update showed up in the web admin panel on Nextcloud, and pressing the update button appeared to update it, until the page was refreshed where it would state once again that there was an update available. This was very confusing as it appeared to work only to fail silently each time. As it turns out, it was because of the messed up file permissions. I finally realized it when I saw the permissions issue was listed on the "overview" tab of the admin settings.

**Describe the solution you'd like**
Instead of failing silently, the admin panel for app updates should grey out the update button (or show some sort of orange warning sign with a !). Upon mousing over, it should state that the folder has incorrect permissions and tell the user to fix the problem before the update can be performed. Nextcloud already knows how to detect when the permissions are wrong (since it shows up on the "Overview" tab), so hopefully this wouldn't be too difficult of a feature to implement.

**Describe alternatives you've considered**
As stated, the alternative was using the "Overview" tab to discover the permission issue.

**Additional context**
This was on Nextcloud 15.0.7, though this bug has spanned many versions. Running on Ubuntu 18.04 Server LTS, through Nginx.

Please let me know if you need additional details.

Best regards.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since over 2 years. Please reopen if you still want to implement this.
