### ISSUE TITLE
Security scan: Incorrect patch level

### ISSUE THREAD

**Issue by joekerna** [nextcloud/server#15228]
### Steps to reproduce
1. Run security scan on Nextcloud 16
2.
3.

### Expected behaviour
A+, everything should be perfect

### Actual behaviour
"NOT on latest patch level"

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page)
16.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**
Website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

I just updated to Nextcloud 16 using the web-based updater and now the security scan at https://scan.nextcloud.com complains, that I am not on the latest patch level.
I just updated 5 minutes ago to 16.0.0.9.
My updater does not provide a newer version.

**Comment by j-ed** [comment]
I can confirm the reported issue:

![grafik](https://user-images.githubusercontent.com/2572764/56732778-a8e9eb80-675e-11e9-909b-de228d64b5e8.png)

**Comment by joekerna** [comment]
Issue is solved with 16.0.3.0

Thanks

**Comment by joekerna** [comment]
Issue reappears with Nextcloud 17
![grafik](https://user-images.githubusercontent.com/23077594/65873610-d37e4700-e383-11e9-8082-7f3513f618d9.png)

**Comment by rondinellepqd** [comment]
> Problema reaparece com o Nextcloud 17
> ![grafik](https://user-images.githubusercontent.com/23077594/65873610-d37e4700-e383-11e9-8082-7f3513f618d9.png)

Hello Friend.
Managed to solve?
I also have the same problem:

![image](https://user-images.githubusercontent.com/20442933/66007559-e62a7600-e480-11e9-9497-33656228d7f3.png)

**Comment by j-ed** [comment]
An issue ticket has already been created to address this issue, see https://github.com/nextcloud/nextcloud.com/issues/1164

**Comment by joekerna** [comment]
Fixed

**Comment by joekerna** [comment]
It's back on Nextcloud 19
![grafik](https://user-images.githubusercontent.com/23077594/84026058-e7575f80-a98c-11ea-994c-960c71659f24.png)

**Comment by theissue** [comment]
It's on v20, too
![image](https://user-images.githubusercontent.com/43711800/96323517-1742fd80-1026-11eb-9c21-e0280d420f81.png)

**Comment by joekerna** [comment]
![grafik](https://user-images.githubusercontent.com/23077594/96501293-797f4680-1250-11eb-9694-81b8b11bfeb1.png)
Now it's correct

**Comment by joekerna** [comment]
![grafik](https://user-images.githubusercontent.com/23077594/126316643-dbde76b1-9212-49bd-bc74-e627c2acc17a.png)

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/nextcloud.com/issues/1499
