### ISSUE TITLE
Moving folders into and out of external storage not possible (15.0.7 and 16.0.0.8)

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/server#15227]
### Setup
NextcloudPi Docker with Apache2, Redis and MariaDB.
Nextcloud files and the data directory are on SSD. Some user data is in a separate "Videos" folder on local HDD.

### Steps to reproduce
1. Enable "external storage" app.
2. In `Settings > Administration > External Storages` add local folder "Videos" for Nextcloud users.
3. Adjust the permissions for the "Videos" folder according to the manual:
https://docs.nextcloud.com/server/16/admin_manual/configuration_files/external_storage/local.html

### Expected behaviour
a) All Nextcloud users should see the external folder "Videos" in their Nextcloud root directory.
b) They should be able to create and edit files and folders inside "Videos".
c) It should be possible to move files and folders into and outside of the "Videos" folder.

### Actual behaviour
a) and b) work as expected.
As for c): Moving selected files into and outside of the external folder works. But moving folders is not possible. An error `Could not move "<folder-name>"` pops up and two exceptions are logged to the Nextcloud log:

```
{"reqId":"XMGjs6wQ7goAAABwQXAAAAAP","level":3,"time":"2019-04-25T12:10:27+00:00","remoteAddr":"172.16.238.1","user":"ncp","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/files\/ncp\/Photos","message":"rename(): The first argument to copy() function cannot be a directory at \/data\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.8"}

{"reqId":"XMGjs6wQ7goAAABwQXAAAAAP","level":3,"time":"2019-04-25T12:10:27+00:00","remoteAddr":"172.16.238.1","user":"ncp","app":"PHP","method":"MOVE","url":"\/remote.php\/dav\/files\/ncp\/Photos","message":"rename(\/\/data\/nextcloud\/data\/ncp\/files\/Photos,\/\/ncdata\/Videos\/Photos): Invalid cross-device link at \/data\/nextcloud\/lib\/private\/Files\/Storage\/Local.php#272","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:66.0) Gecko\/20100101 Firefox\/66.0","version":"16.0.0.8"}
```

The error occurs with Nextcloud version 15.0.7 and persists after update to beta 16.0.0.8

### Server configuration

**Operating system**: Debian GNU/Linux 9

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** PHP 7.2

**Nextcloud version:** 15.0.7 and 16.0.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 15.0.5

**Where did you install Nextcloud from:** NextcloudPi Docker Image

**Signing status:**
```
No errors have been found.
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "11": "77.4.16.90",
            "1": "172.16.238.10",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "6": "192.168.178.64",
            "20": "0.0.0.0"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.0.8",
        "overwrite.cli.url": "http:\/\/localhost\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Comment by danaivehr** [comment]
The same here on 16.0.2 in docker. Able to move folder inside external storage and not able to move it between external storage and data directory

**Comment by kesselb** [comment]
Thank you @langfingaz for this report and kudos for using the issue template :+1:

 I'm closing this in favor of https://github.com/nextcloud/server/issues/15227
