### ISSUE TITLE
app-checker (nc 14/15) fails on ? (Nullable types)

### ISSUE THREAD

**Issue by Grotax** [nextcloud/server#15225]
### Steps to reproduce
1. install nextcloud 14/15 and news app PR https://github.com/nextcloud/news/pull/494
2. run `./occ app:check-code news`
3. error on ?

### Expected behaviour
Nextcloud 14 supports PHP 7.1, so nullable types should be supported by the scanner

### Actual behaviour
Throws error :)

A failed travis build can be found here: https://travis-ci.org/nextcloud/news/builds/524404020

**Comment by kesselb** [comment]
Is this fixed? ;)

**Comment by Grotax** [comment]
I don't think so, but 14 and 15 are eol anyway.
