### ISSUE TITLE
Update to 16.0 - InvalidArgumentException: Primary index name on "xxxxxx_collres_collections" is too long.

### ISSUE THREAD

**Issue by subw0ofer** [nextcloud/server#15229]
Getting following error while updating from 15 to 16 with Web - updater:

Aktualisierung auf 16.0.0

InvalidArgumentException: Primary index name on "xxxxxxxx_collres_collections" is too long.
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

InvalidArgumentException: Primary index name on "xxxxxxxx_collres_collections" is too long.

**Comment by poldixd** [comment]
Same here on MySQL 5.7.25

**Comment by kesselb** [comment]
How long is your table prefix? If possible you may change it to oc_ or something else with two characters.

cc @nickvergessen should we limit the prefix length to 2 characters or something like that?

**Comment by subw0ofer** [comment]
My table prefix was 8 characters (letters and numbers) plus "_" long 
- have changed to "oc_"
- upgrade was successful

Thanks for your hint.

**Comment by poldixd** [comment]
My `dbtableprefix` is 12 characters long. Ok, i'll change the prefix length.

**Comment by nickvergessen** [comment]
> should we limit the prefix length to 2 characters or something like that?

@kesselb the prefix cant be set anymore for new instances IIRC. Also we cant automatically change it for existing instances. So not sure what we could change. But well the prefix should be removed and therefor not cause problems. Will check again after my vacation

**Comment by tessus** [comment]
If you changed the prefix to a different value, the tables wouldn't be found anymore. This means you would also have to change the table names in the database manually, right?

**Comment by kesselb** [comment]
> If you changed the prefix to a different value, the tables wouldn't be found anymore. This means you would also have to change the table names in the database manually, right?

Unfortunately yes.

**Comment by tessus** [comment]
@kesselb thx for the info.

**Comment by BierGitte** [comment]
That's weird, there are some present which are way longer, i.e. xxxxxxxxx_systemtag_object_mapping .
And shouldn't the max length be 64 chars anyways? There is no UTF16-wizardry involved at this place, isn't there?

**Comment by kesselb** [comment]
In Oracle 12.1 and below the maximum object name length is 30 bytes.

**Comment by BierGitte** [comment]
Ah ok. I'm using MySQL.
Oracle 12.1 has reached end of life in mid-2014 and can be removed, can it?
https://en.wikipedia.org/wiki/Oracle_Database#Releases_and_versions

**Comment by nickvergessen** [comment]
Sadly reality is much different. But anyway, the problem results from your non default prefix length and i will fix that soon

**Comment by BierGitte** [comment]
Workaround for the poor souls who can't use occ on their webspace to abort the update:
**!!! Don't use with Oracle databases < 12.2 !!!**
Download the file `%ncdir%\lib\private\DBMigrationService.php`
Change the values in the lines
`if (!$isUsingDefaultName && \strlen($indexName) > 30) {`
and
`if ($isUsingDefaultName && \strlen($table->getName()) > 26) {`
to 64 and 60. Save and upload. Restart the update. Worked for me.

**Comment by nickvergessen** [comment]
Please checkout the following patch https://github.com/nextcloud/server/pull/15289/files
