### ISSUE TITLE
Change visibility for tags

### ISSUE THREAD

**Issue by stereu** [nextcloud/server#15237]
**Is your feature request related to a problem? Please describe.**
In large installations with many users and groups it would be great to be able to choose the visibility for example certain groups or for yourself only.

**Describe the solution you'd like**
Implement a switch in gui to choose tags visibility when creating.

**Describe alternatives you've considered**
Switch tags visibility in user settings.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by Spartachetto** [comment]
This should be related to #15412
