### ISSUE TITLE
16.0.0RC2: no initial calendar created

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/server#15236]
Testing out 16.0.0RC2, installing the calendar app doesn't create an initial calendar. It requires the user to create one before any events can be created. v15 doesn't work this way, so it seems like a regression.

**Comment by georgehrke** [comment]
@MorrisJobke @rullzer Did we change anything about user creation hooks or something about this line?

(While this is a regression, i don't consider it a showstopper bug, since a user can simply create a new calendar themselves. We should fix this in 16.0.1)

**Comment by MorrisJobke** [comment]
> @MorrisJobke @rullzer Did we change anything about user creation hooks or something related?

We reduced the amount they are fired in #15020 by @nickvergessen

**Comment by kyrofa** [comment]
I'm surprised to see this is still an issue in 16.0.3.

**Comment by georgehrke** [comment]
Somewhat related pull-request: https://github.com/nextcloud/server/pull/17148

**Comment by tcitworld** [comment]
This doesn't seem to be an issue in 21. If it still is, please reopen.
