### ISSUE TITLE
Nextcloud is picking IP address from environment when using iframe

### ISSUE THREAD

**Issue by prashant7526** [nextcloud/server#15232]
We have embedded nextcloud in iframe, everything is working fine.

The problem we facing:
Our testing server has local IP as well as public IP, and when the application opens nextcloud, it picks the IP address from the environment. We as of now know how to configure one IP in the config file. 

Is there anyway to allow both IPs in config file (we don't know how to allow multiple IPs)?
Or is there any other solution through programming (java), in which we can force nextcloud not to pick environment IP and use the one we are providing? 

Thanks in advance.

**Comment by godofblack** [comment]
Hey there., Kindly help me to iframe integration in Nextcloud..

**Comment by godofblack** [comment]
I try many ways but it's not working still showing login page only kinldy help me plz

**Comment by prashant7526** [comment]
First of all you either need to have HTTPS protocol on which which nextcloud is running or you have to disable one option

**Comment by szaimen** [comment]
Yes, please use a local DNS server like Pi-hole for this.
