### ISSUE TITLE
Scrolling doesn't work properly on android browsers in NC

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#15233]
Just upgraded to NC16. Now scrolling in gallery or files didn't work properly in the phones browsers. 

Seems several people are having this issue. https://help.nextcloud.com/t/nc-16-android-browser-firefox-chrome-can-t-scroll/52181/3

In addition, I also get many browser errors in Opera browser. This never happened on any previous NC. 

Server configuration detail
Operating system: Linux 5.0.8-gentoo #2 SMP PREEMPT Sun Apr 21 14:34:07 CEST 2019 x86_64

Webserver: Apache 2.4.39 (fpm-fcgi)

Database: mysql 10.3.10

PHP version:
```7.2.16 Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, intl, json, mbstring, session, standard, pcntl, mysqlnd, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, readline, Reflection, mysqli, SimpleXML, sockets, sodium, exif, tokenizer, xml, xmlreader, xmlwriter, zip, cgi-fcgi, apcu, imagick, redis, Zend OPcache```

Nextcloud version: 16.0.0 - 16.0.0.9

Updated from an older Nextcloud/ownCloud or fresh install: NC15

Where did you install Nextcloud from: Updater.phar

Signing status
List of activated apps
``` Enabled: - accessibility: 1.2.0 - activity: 2.9.1 - admin_audit: 1.6.0 - audioplayer: 2.7.0 - bookmarks: 0.17.0 - bruteforcesettings: 1.3.0 - calendar: 1.7.0 - camerarawpreviews: 0.6.5 - checksum: 0.4.2 - cloud_federation_api: 0.2.0 - comments: 1.6.0 - contacts: 3.1.1 - dav: 1.9.2 - dropit: 0.2.1 - event_update_notification: 0.3.4 - extract: 1.1.1 - federatedfilesharing: 1.6.0 - files: 1.11.0 - files_automatedtagging: 1.6.0 - files_downloadactivity: 1.5.0 - files_external: 1.7.0 - files_fulltextsearch: 1.3.0 - files_inotify: 0.1.4 - files_pdfviewer: 1.5.0 - files_rightclick: 0.13.0 - files_sharing: 1.8.0 - files_texteditor: 2.8.0 - files_trackdownloads: 1.4.0 - files_trashbin: 1.6.0 - files_versions: 1.9.0 - files_videoplayer: 1.5.0 - firstrunwizard: 2.5.0 - flowupload: 0.1.0 - fulltextsearch: 1.3.1 - fulltextsearch_elasticsearch: 1.3.0 - gallery: 18.3.0 - group_everyone: 0.1.2 - groupfolders: 3.0.0 - guests: 1.0.0 - impersonate: 1.3.0 - issuetemplate: 0.5.0 - logreader: 2.1.0 - lookup_server_connector: 1.4.0 - mail: 0.14.0 - metadata: 0.9.0 - music: 0.9.4 - news: 13.1.6 - nextcloud_announcements: 1.5.0 - notes: 2.6.0 - notifications: 2.4.1 - oauth2: 1.4.2 - ocdownloader: 1.6.3 - password_policy: 1.6.0 - previewgenerator: 2.1.0 - privacy: 1.0.0 - provisioning_api: 1.6.0 - radio: 0.6.4 - recommendations: 0.4.0 - serverinfo: 1.6.0 - sharebymail: 1.6.0 - sharelisting: 0.2.0 - sharerenamer: 2.6.0 - socialsharing_email: 1.0.5 - spreed: 6.0.0-rc.2 - support: 1.0.0 - survey_client: 1.4.0 - suspicious_login: 1.0.0 - systemtags: 1.6.0 - tasks: 0.10.0-alpha3 - telephoneprovider: 1.0.2 - theming: 1.7.0 - twofactor_backupcodes: 1.5.0 - updatenotification: 1.6.0 - viewer: 1.0.0 - workflowengine: 1.6.0 Disabled: - bookmarks_fulltextsearch - encryption - federation - files_reader - user_ldap - workflow_script ```
Configuration (config/config.php)
``` { "instanceid": "***REMOVED SENSITIVE VALUE***", "passwordsalt": "***REMOVED SENSITIVE VALUE***", "secret": "***REMOVED SENSITIVE VALUE***", "trusted_domains": [ "tnonline.net" ], "datadirectory": "***REMOVED SENSITIVE VALUE***", "overwrite.cli.url": "https:\/\/tnonline.net", "dbtype": "mysql", "version": "16.0.0.9", "dbname": "***REMOVED SENSITIVE VALUE***", "dbhost": "***REMOVED SENSITIVE VALUE***", "dbport": "", "dbtableprefix": "oc_", "dbuser": "***REMOVED SENSITIVE VALUE***", "dbpassword": "***REMOVED SENSITIVE VALUE***", "installed": true, "mail_smtpmode": "smtp", "mail_smtpauthtype": "LOGIN", "mail_smtpsecure": "ssl", "mail_from_address": "***REMOVED SENSITIVE VALUE***", "mail_domain": "***REMOVED SENSITIVE VALUE***", "mail_smtpauth": 1, "mail_smtphost": "***REMOVED SENSITIVE VALUE***", "mail_smtpport": "465", "mail_smtpname": "***REMOVED SENSITIVE VALUE***", "mail_smtppassword": "***REMOVED SENSITIVE VALUE***", "memcache.local": "\\OC\\Memcache\\Redis", "memcache.distributed": "\\OC\\Memcache\\Redis", "memcache.locking": "\\OC\\Memcache\\Redis", "redis": { "host": "***REMOVED SENSITIVE VALUE***", "port": 6379 }, "mysql.utf8mb4": true, "updater.release.channel": "beta", "enable_previews": true, "preview_max_x": 1600, "preview_max_y": 1024, "loglevel": 0, "maintenance": false, "auth.bruteforce.protection.enabled": false, "enabledPreviewProviders": { "0": "OC\\Preview\\PNG", "1": "OC\\Preview\\PDF", "2": "OC\\Preview\\GIF", "3": "OC\\Preview\\BMP", "4": "OC\\Preview\\XBitmap", "5": "OC\\Preview\\TXT", "6": "OC\\Preview\\MarkDown", "7": "OC\\Preview\\Movie", "9": "OC\\Preview\\SVG", "10": "OC\\Preview\\Photoshop", "11": "OC\\Preview\\MSOffice2003", "12": "OC\\Preview\\MSOffice2007", "13": "OC\\Preview\\MSOfficeDoc", "14": "OC\\Preview\\OpenDocument", "15": "OC\\Preview\\TIFF", "16": "OC\\Preview\\Font", "17": "OC\\Preview\\JPEG" }, "jpeg_quality": 60, "log_rotate_size": 52428800, "theme": "", "app_install_overwrite": [ "spreed", "files_trackdownloads", "bookmarks_fulltextsearch", "tasks", "radio", "files_reader" ] } ```

Are you using external storage, if yes which one: local

Are you using encryption:no

Are you using an external user-backend, if yes which:no

**Comment by Gatak** [comment]
In addition I often get rendering error in Opera browser. 
![Screenshot_20190425-163801_Opera](https://user-images.githubusercontent.com/1469150/56746033-b792cb80-677b-11e9-8c46-313e4d792cab.jpg)

**Comment by kesselb** [comment]
Looks interesting. I'm not sure about this error page? @rullzr @ChristophWurst

Do you have Opera Turbo enabled? If so could you try without?

**Comment by koarlmichael** [comment]
At first I thought it was just a bug in the gallery app, but it also happens in the webview.

https://github.com/nextcloud/gallery/issues/515

**Comment by Gatak** [comment]
No VPN or opera. Tried on mobile and on WiFi as well as clearing app cache. Though it does not creak like that on other browsers, the scrolling doesn't work in either files or gallery.

**Comment by DaCryptor** [comment]
If this issue turn out to be true, this one would be a REAL "show-stopper" to prevent me from upgrading to NC16!

**Comment by rullzer** [comment]
What phone are you actually using and what browser? All works as expected here in chromium and firefox mobile.

@skjnldsv @ChristophWurst @juliushaertl any of you in a position to test opera?

**Comment by Gatak** [comment]
I'm using a Samsung A5 2017 with Android 8.0.1.

I tested just now and scrolling initially work but stopps when I scroll so more results show in the bottom of the file list. 

![Screenshot_20190426-154548_Samsung Internet](https://user-images.githubusercontent.com/1469150/56812191-ad83d200-683a-11e9-8f72-eb9371ef07e7.jpg)

When it stops working it isn't possible by touching the orange area. Scrolling continues to work if I scroll using the yellow area.

It is the same in Opera browser, which is based on chromium.

**Comment by Gatak** [comment]
I tried to disable "Right Click" app. Still the same problem.

**Comment by koarlmichael** [comment]
Can confirm the bug on: 
OnePlus 3, Android 8.0.0, Chrome
Moto G5, Android 8.1.0, Chrome and Firefox
Huawei P9 lite, Android 7, Chrome and Firefox

**Comment by DaCryptor** [comment]
Bug confirmed on BQ Aquaris X Pro, Android 8.1, Firefox Mobile

**Comment by AndyFx12** [comment]
Bug confirmed on MotoG4 Play, Android 7.1 and Lenovo TAB2 A10-70F, Android 6

**Comment by ChristophWurst** [comment]
Bug confirmed on FF for Android

**Comment by huzergackl** [comment]
I was able to reproduce the issue using chrome dev tools in mobile view.

The behavior is caused by the css class .ui-draggable-handle that has "tourch-action" set to "none".
If i remove it scrolling works as expected. Also "touch-action" is not disabled on the first column with the checkboxes. (see comment made by @Gatak )

If you remove this property scrolling works:
![grafik](https://user-images.githubusercontent.com/4304911/57177122-30231780-6e61-11e9-9d57-d8437de48cae.png)

For a permanent solution further investigation is required to find out why "touch-action" has been added.

**Comment by skjnldsv** [comment]
My uess is the move of our jquery library into our webpack config? @ChristophWurst 
Maybe we added a new css change from one of our dependency? this seems related to jquery-ui (yeaaaah) :)

**Comment by ChristophWurst** [comment]
> My uess is the move of our jquery library into our webpack config? @ChristophWurst

The jquery libs haven't changed much with the webpack bundling. But we updated jquery-ui a bit: https://github.com/nextcloud/server/pull/11718

**Comment by skjnldsv** [comment]
Yep, this is it:
https://github.com/jquery/jquery-ui/commit/28310ff55f062199fb2f187ea13d3561a879aea8#diff-e8b8fd48040d8abc0af402d340bb1b05R11

**Comment by skjnldsv** [comment]
Fix in #15462
