### ISSUE TITLE
Nextcloud 16.0.0 + PHP 7.3.4 = Broken

### ISSUE THREAD

**Issue by allendustin** [nextcloud/server#15242]
### Steps to reproduce
1. Compile PHP 7.3.4 on Raspberry Pi 3
2. Try upgrading to Nextcloud 16.0.0
3. Cry

### Expected behaviour
Tell us what should happen

Nextcloud should successfully complete the manual upgrade process.

### Actual behaviour
Tell us what happens instead

OCC: Upgrade failed to start.

### Server configuration

**Operating system**:

Raspbian

**Web server:**

**Database:**

MySQL

**PHP version:**
7.0.33 trying to go to 7.3.4

**Nextcloud version:** (see Nextcloud admin page)

15.0.7 trying to upgrade to 16.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Upgrade

**Where did you install Nextcloud from:**

Manual upgrade process.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Schmuuu** [comment]
Why do you think the issue belongs to Nextcloud server on Github?
Sounds like a topic for a unix forum about how to update PHP or the Nextcloud forum (https://help.nextcloud.com) to receive some assistance from the community there, about how to fix your PHP installation.

By the way: the issue template is there for a reason.

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
