### ISSUE TITLE
Settings/App screen not working fully in mobile view

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#15240]
The app store and management screen in all recent  NC versions doesn't fully work in mobile view. Only currently installed apps can be seen. 

![Screenshot_20190426-010227_Opera Touch](https://user-images.githubusercontent.com/1469150/56773600-2e04ed00-67bf-11e9-8eb8-8a502ba557f9.jpg)
The feature request is to make this screen mobile friendly, for example with a drop down menu or swipe in function.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
