### ISSUE TITLE
[remote] Error: TypeError: idn_to_ascii() expects parameter 1 to be string, null given at <<closure>>

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#15243]
### Steps to reproduce
1. Create Calendar entry
2. Entry will not shown; need to logoff; then entry is there
3. Entry did not save properly; some changes - like chaning the Calender Sharing option will not be saved anymore.
4. After logout/login again, the entry was "not confirmed" .. but it was confirmed before
5. This behave is the same or similar with different Browsers (Chrome/Edge) .. 

I never saw such a behave from this app;  since i did the upgrade just some minutes ago to Version: 1.6.5, the behaviour of this app changed completely

### Expected behaviour
All those things obove should not happen

### Actual behaviour
see obove

### Server configuration
<!--
Operating System: System Linux 3.10.0-957.10.1.el7.x86_64

Webserver: Apache/2.4.6 (CentOS) OpenSSL1.0.2k-fips

Database: mysql 5.5.60-MariaDB,

PHP version: PHP Version => 7.2.10

[PHP Modules] apcu bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext hash iconv igbinary imagick intl json ldap libxml mbstring mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline redis Reflection session shmop SimpleXML sockets SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlwriter xsl Zend OPcache zip zlib [Zend Modules] Zend OPcache

Nextcloud: - version: 15.0.7.0

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 1,
        "updater.release.channel": "production",
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "xxx",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "xxx",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "xxx",
        "session_lifetime": 1200,
        "session_keepalive": false,
        "logfile": "\/media\/log\/nextcloud.log",
        "knowledgebaseenabled": false,
        "log_rotate_size": 3145728,
        "onlyoffice": {
            "verify_peer_off": true
        }

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - apporder: 0.6.0
  - audioplayer: 2.7.0
  - bookmarks: 0.17.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - circles: 0.16.3
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - cospend: 0.0.10
  - data_request: 1.2.0
  - dav: 1.8.1
  - deck: 0.6.0
  - dicomviewer: 1.2.0
  - drawio: 0.9.2
  - drop_account: 0.1.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.0.1
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - flowupload: 0.1.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 2.6.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - onlyoffice: 2.1.6
  - ownbackup: 18.11.0
  - passman: 2.2.2
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - quicknotes: 0.1.7
  - quota_warning: 1.4.0
  - radio: 0.6.4
  - rainloop: 6.0.2
  - ransomware_protection: 1.3.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - sharerenamer: 2.6.0
  - socialsharing_diaspora: 1.0.4
  - socialsharing_email: 1.0.5
  - socialsharing_facebook: 1.0.4
  - socialsharing_googleplus: 1.0.4
  - socialsharing_twitter: 1.0.4
  - spreed: 5.0.3
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.9.8
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - carnet
  - dashboard
  - encryption
  - external
  - files_accesscontrol
  - files_external
  - files_fulltextsearch
  - files_markdown
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - impersonate
  - jsloader
  - phonetrack
  - previewgenerator
  - richdocuments
  - user_ldap
  - weather

**Updated from an older installed version**

**Signing status (ownCloud/Nextcloud 9.0 and above):**

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no


### Client configuration
**Browser:**
Chome,Version 73.0.3683.103 (Offizieller Build) (64-Bit) 

**Operating system:**
Windows 10

[remote] Error: TypeError: idn_to_ascii() expects parameter 1 to be string, null given at <<closure>>

 0. /var/www/html/nextcloud/lib/private/Mail/Message.php line 78
    idn_to_ascii(null, 0, 1)
 1. /var/www/html/nextcloud/lib/private/Mail/Message.php line 143
    convertAddresses({Michael: null})
 2. /var/www/html/nextcloud/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php line 233
    setTo({Michael: null})
 3. <<closure>>
    schedule(Sabre\VObject\IT ... e})
 4. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\CalDAV\ ... "], [Sabre\VObject\I ... }])
 5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 384
    emit("schedule", [Sabre\VObject\I ... }])
 6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Schedule/Plugin.php line 430
    deliver(Sabre\VObject\IT ... e})
 7. <<closure>>
    beforeUnbind("*** sensitive parameters replaced ***")
 8. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([OCA\DAV\CalDAV\ ... "], ["*** sensitive parameter replaced ***"])
 9. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 286
    emit("beforeUnbind", ["*** sensitive parameter replaced ***"])
10. <<closure>>
    httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
11. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
12. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    emit("method:DELETE", [Sabre\HTTP\Requ ... }])
13. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
14. /var/www/html/nextcloud/apps/dav/lib/Server.php line 301
    exec()
15. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    exec()
16. /var/www/html/nextcloud/remote.php line 163
    require_once("/var/www/html/n ... p")

DELETE /remote.php/dav/calendars/xxxxxx/personal_shared_by_xxxxx/sabredav-xxxxxxx-a325-41de-ab7d-xxxxxxxxxf.ics
from xxxxxxxxxx by Michael at 2019-04-24T01:18:31+02:00


Error | PHP | Undefined offset: 1 at /var/www/html/nextcloud/lib/private/Mail/Message.php#77
-- | -- | --

**Comment by georgehrke** [comment]
@Githopp192 Did you configure your mail settings via the admin GUI or did you just edit the config.php?

Can you check if the test email is properly delivered? (Go to settings, administration, basic settings)

**Comment by Githopp192** [comment]
did configure via GUI. did the test via (settings,administration, base settings --> test mail) -->
The email could successfully sent. 
The From-Address in that config is a fake email address, but i did not notice any issue about that, also
sending a test email will work ..

**Comment by Nils160988** [comment]
I also see this combination of the two error messages (but for me with circles instead of calendar), not sure if related:

`Exception: idn_to_ascii() expects parameter 1 to be string, null given`
and
`Undefined offset: 1 at /var/www/nextcloud/lib/private/Mail/Message.php#85`

with Nextcloud 18.0.1.

Should I provide the full log messages to help you solve this here or do you think it's unrelated?

**Comment by eyrinck** [comment]
Hi, I have the same error messages on nextcloud 18.0.1 with docker on Synology.
Creating or deleting dates via Webpage hangs up frequently. Two dates that I deleted with acalendar+ and davx on Android disappeared on my handy but are shown in the Webpage and cannot be deleted there. Tried occ maintenance:repair without effect. Invitation mails are send when dates are successfully created via Webpage but not when they are created via acalendar+.  Don't know if these problems stick together.
Hope this helps

**Comment by kesselb** [comment]
```
/var/www/html/nextcloud/lib/private/Mail/Message.php line 143
convertAddresses({Michael: null})
```

Debugged a similar issue today: https://github.com/nextcloud/server/issues/20294. It seems that "Michael" has a invalid email address.

**Comment by LanselotOz** [comment]
I've discovered that this error occur when my caldav client authorized with login (not email). In this case when you create new event they pass your login in email form and nextcloud catch an exception. 

Replacing login with email fixed the problem.

**Comment by jpiron** [comment]
I had the same issue.
Had to remove all attendees from the event before being able to successfully delete the event itself.

**Comment by ChristophWurst** [comment]
See https://github.com/nextcloud/server/pull/25582 for a fix.
