### ISSUE TITLE
NC 16 - breadcrumb menu in user management not shown anymore

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#15246]
## Expected behavior
Behind each user entry a breadcrumb drop-down menu should provide options to delete or disable a user etc.

## Current behavior
The breadcrumb drop-down menu isn't shown anymore although its functions are still functional if clicking on the white background where it is being expected.

![grafik](https://user-images.githubusercontent.com/2572764/56798546-3d178980-6817-11e9-83e3-0c1cb641596d.png)

## Steps to reproduce
1. Open the users menu
2. Check if the breadcrumb menu exists.

#### Server Configuration
OS: Linux 3.16.63
Web server: Apache2 2.4.37
Database: MariaDB 10.2.22
PHP version: 7.2.14
Nextcloud version: 16.0.0

#### Client Configuration
Browser: Mozilla Firefox 66.0.3
Operating system: Windows 10

**Comment by hanserasmus** [comment]
![image](https://user-images.githubusercontent.com/24249616/56812866-13bd2480-683c-11e9-9764-5b9fb1066d62.png)
NC 16.0.0 on CentOS 7.5, PHP 7.2.
Firefox on Fedora 29.

**Comment by j-ed** [comment]
It seems to be a problem with the sizing of the quota element which overlays the breadcrumbs. If I reduce the window zoom level to 90% the breadcrumbs are displayed again.

**Comment by kesselb** [comment]
cc @skjnldsv

**Comment by mmccarn** [comment]
The boxes around the values for the 'Groups' and 'Quota' column are bigger than the columns themselves.
