### ISSUE TITLE
Change redirect target for integrity scan

### ISSUE THREAD

**Issue by karottenbaum** [nextcloud/server#15252]
**Is your feature request related to a problem? Please describe.**
When triggering an integrity rescan from the Overview page `/settings/admin/overview`, I am redirected to the Basic Settings `/settings/admin`, which do not display the result of the scan.

**Describe the solution you'd like**
I would suggest redirecting to `/settings/admin/overview` instead.

**Describe alternatives you've considered**
None.

**Comment by Gatak** [comment]
I only noticed this in NC16. I think it is a regression.

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
