### ISSUE TITLE
Orientation of photos

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/server#15257]
From some time Nextcloud does not visualize my photos in the right orientation. 

They are all visualized as landscape even if that is not correct.

I cannot recall from when it happens (sorry for the unclear bug report). I am using Nextcloud 15.0.4

I opened the issue here in the server because I have the problem both in the web interface and in the android client.

**Comment by Spartachetto** [comment]
@j-ed first of all thank for answering.
I wrote in this repository as the problem is present also in the android client; I think that that client is not influenced by the Gallery app. Maybe @ tobiasKaminsky or @AndyScherzinger could correct me if I am wrong...

**Comment by tobiasKaminsky** [comment]
Android client does only use code from server.
Can you create us a test account, test if the problem occurs also there and if so send the credentials to tobias at nextcloud dot com with a reference to this issue?

**Comment by Spartachetto** [comment]
@tobiasKaminsky I just sent you a test account with some photos as an example.

TIA!!!!!

**Comment by Spartachetto** [comment]
I just noticed a weird thing: if I upload photos taken with the stock camera app of _my mobile_ in Nextcloud, then all of them are shown as landscape. If I upload a portrait photo taken with the Vector Camera of _my mobile_ then it is shown correctly.

The stock camera app is the one of a Samsung phone. Another user has the some issue with another Samsung phone.
The Vector Camera app is version 1.4.2 as downloaded by Fdroid

**Comment by tobiasKaminsky** [comment]
> if I upload photos taken with the stock camera app of _my mobile_ in Nextcloud, then all of them are shown as landscape. If I upload a portrait photo taken with the Vector Camera of _my mobile_ then it is shown correctly.

So this then seems to be camera app related.

I tested it and can verify it on your cloud.
But when I upload one image (20190516_194039.jpg) to our cloud it is shown with correct orientation. We already use NC16.

@juliushaertl do you have an idea? Is this maybe related to imagick, etc.?

**Comment by juliushaertl** [comment]
We use the exif data to rotate images when generating the previews in https://github.com/nextcloud/server/blob/a661f043e1a8764cb7c795f50df77b830d3e352b/lib/private/legacy/image.php#L455 So maybe the exif data is missing on those uploaded images?

**Comment by tobiasKaminsky** [comment]
@juliushaertl was there a change from NC15->NC16? As it works when I upload the problematic image to our cloud.

**Comment by juliushaertl** [comment]
Nothing that I'm aware of.

> I just noticed a weird thing: if I upload photos taken with the stock camera app of my mobile in Nextcloud, then all of them are shown as landscape. If I upload a portrait photo taken with the Vector Camera of my mobile then it is shown correctly.

This sounds pretty much like the stock camera is not providing proper exif data. Can you provide an example file where the issue exists?

**Comment by juliushaertl** [comment]
@Spartachetto Could you also try to enable debug logging on your instance, upload a new image where the orientation goes wrong and share the logs when requesting the preview of the new file? This should have some details about where this fails.

**Comment by Spartachetto** [comment]
I am trying to answer to the different points

on the different apps:
I was wrong by saying that "If I upload a portrait photo taken with the Vector Camera of my mobile then it is shown correctly". If I upload a portrait photo taken with the Vector Camera of my mobile then it is always as portrait, instead that always as landscape.
The photos already uploaded previously are displayed correctly. I do not think I upgraded the stock camera app recently; yet I updated the OS.
Do I have to verify the exact date from which I see the issue?
My stock camera app is version 7.6.39 (I have a Samsung phone)

On EXIF metadata:
I provided @tobiasKaminsky a test access to my cloud. You can find there an example of the files. If (for some weird reason) the metadata in the uploaded files is missing, I can send you via email some other photos.

On the debug logging:
I do not manage my cloud. I pay a provider. Yet I have an administrative user. Can I enable debug logging?

**Comment by juliushaertl** [comment]
@Spartachetto I had a look at the files but there doesn't seem to be an issue. I also tried to add them to my dev instance and they rotate just fine. 

> I do not manage my cloud. I pay a provider. Yet I have an administrative user. Can I enable debug logging?

I would suggest to get in contact with your provider then, since this seems to be rather setup related.

**Comment by rhabacker** [comment]
One reason may be an uninstalled php7-exif package, as it occurs after following this (now corrected) installation guide https://en.opensuse.org/SDB:Nextcloud#Install_from_Source.
