### ISSUE TITLE
Implement a folder tree sidebar

### ISSUE THREAD

**Issue by ongun-kanat** [nextcloud/server#15253]
Nextcloud displays files either in a grid or a list. However this is not convenient / suitable for quickly navigating complex folder trees and long lists of folders. A classic Windows Explorer style sidebar that displays folders as a tree would be a very nice improvement.

I've seen it was proposed in #4994 but the aspect of a tree view seems to be forgotten as the "moving files" feature seems like the main point of that request. I'd like to bring attention to accessibility / usability aspect of tree view.

**Comment by jdhirst1** [comment]
I agree with this, a folder tree would be excellent for users with extensive file collections.

**Comment by kxu1988** [comment]
I suggest the tree sidebar as  "Octotree" https://chrome.google.com/webstore/detail/octotree/bkhaagjahfmjljalopjnoealnfndnagc

**Comment by wdehoog** [comment]
This issue is labeled 'Needs triage'. Really?

If one starts using Nextcloud seriously as in storing documents from multiple projects and edit/share them on a daily basis then the lack of a tree view in the files app becomes apparent immediately.
Don't you think there is a reason all filemanagers have one?

So please add a treeview asap.

**Comment by johny-inc** [comment]
I agree with this. Octotree looks perfect option for this. Even Filerun has simple file tree integrated already.

**Comment by szaimen** [comment]
@nextcloud/designers does this make sense and is it feasible?

**Comment by ongun-kanat** [comment]
@szaimen Nextcloud needs separate GitHub labels too :) . Apparently @nextcloud-bot will close the bug report if somebody doesn't have the time to look at it.

**Comment by bes1002t** [comment]
From my point of view this feature would make totally sense and the octotree implementation looks good from a design point of view. I think the issue is that we need someone who priorize this issue more than other. ;)

**Comment by skjnldsv** [comment]
> Apparently @nextcloud-bot will close the bug report if somebody doesn't have the time to look at it.

Yes, it would mean this is not in our current priorities. Otherwise we'd add this straight away.
I'll make a statement then, sorry if this is not what you wish on a short-term basis.

This is far down the priority list. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

**Comment by brendan-pike** [comment]
Adding my support. I believe this would be a very valuable addition especially for people who are not permitted to use the desktop client which is our situation.

**Comment by CarlSchwan** [comment]
The nice folks at framasoft are working on a prototype https://framablog.org/2022/07/13/nextcloud-sorts-a-nextcloud-application-prototype-to-navigate-your-files-more-easily/ if someone want to help them, I'm sure they would be happy :)

**Comment by sunjam** [comment]
[Now available in the appstore](https://apps.nextcloud.com/apps/sorts)

[Here is the project repository for the Sorts app.](https://framagit.org/framasoft/nextcloud/sorts)

**Comment by vagner-dias** [comment]
+1
As of the appearance, it could be similar to the folder appearance in favorites 

![image](https://user-images.githubusercontent.com/86367839/219982393-bfb858ff-ce49-4217-ab14-ac46bebdceea.png)

**Comment by h2iqcode** [comment]
This is the one thing that is keeping me on Google Docs :/

**Comment by insomnia417** [comment]
+1

**Comment by lafi87** [comment]
I hope release comes out soon, it is a very important functionality.

**Comment by sunjam** [comment]
Amazing!!!!!!

**Comment by jancborchardt** [comment]
Hope everyone is happy to hear that this will come in the Next release (in September). :)
Your upvotes helped decide to go for this, so do keep them coming on other issues you would like to see – we do look at them. :dark_sunglasses:

**Comment by ongun-kanat** [comment]
I'm extremely happy and grateful that this has been implemented! It will be a great usability boost for the deep file hierarchies!

Thank you @Pytal and @jancborchardt for prioritizing and implementing this and thank you all the other members for reviewing and making Nextcloud the leading cloud solution for the privacy-minded people.
