### ISSUE TITLE
In NC16 settings/users, 3-dot-menu (holding e.g. Impersonate) is invisible if window is not wide enough

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#15262]
### Steps to reproduce
1. open settings/user
2. reduce browser window width until 3dot-menu on the right vanishes
3. try to access that 3dot-menu

### Actual behaviour
3dot-menu (holding e.g. Impersonate) is invisible if window is not wide enough (depending on the browser, it can be made accessible by reducing zoom to e.g. 80%, not in most mobile browsers, though)

### Expected behaviour
3dot-menu shouldn't vanish :-)

**System
16.0.0, updated from 15.0.7 from Nextcloud website (though updater)

**Comment by j-ed** [comment]
This issue has already reported here https://github.com/nextcloud/server/issues/15246

**Comment by nursoda** [comment]
Sorry, didn't find that bug report. Closing this one, thanks for the hint.
