### ISSUE TITLE
Can't drag and drop multiple folders/subfolders

### ISSUE THREAD

**Issue by maniac0s** [nextcloud/server#15263]
When I drag and drop a folder into firefox or chrome, it uploads the folder with all files in it. Uploading a list of files works as well. But as soon as the folder contains a subfolder, nothing happens. No error and no upload is sown.

I am running Nextcloud version 15

`<?php 
$OC_Version = array(15,0,7,0);
$OC_VersionString = '15.0.7';
$OC_Edition = '';
$OC_Channel = 'stable';
$OC_VersionCanBeUpgradedFrom = array (
  'nextcloud' => 
  array (
    '14.0' => true,
    '15.0' => true,
  ),
  'owncloud' => 
  array (
  ),
);
$OC_Build = '2019-04-08T21:25:55+00:00 e578672704cc159694dc2cd8e77c208ae84b35d6';
$vendor = 'nextcloud';`

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
