### ISSUE TITLE
NC Changelog is not fixed 

### ISSUE THREAD

**Issue by AMDG2** [nextcloud/server#15276]
### Steps to reproduce
1. Update nextcloud to new version
2. Login to nextcloud
3. Scroll down

### Expected behaviour
The changelog box should stay at bottom left

### Actual behaviour
The changelog box is scrolling with the viewport

### Server configuration

**Operating system**: ArchLinux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.4

**Nextcloud version:** 16.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC 15.x

**Where did you install Nextcloud from:** zip package

If the information below are needed let me know. I will fill them.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox Nightly

**Operating system:** ArchLinux

### Logs
I don't think this needed, if it is let me know.
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by AMDG2** [comment]
Adding `position: fixed` to the following element fix this bug.

![Screenshot_2019-04-28 Fichiers - Feildel Cloud](https://user-images.githubusercontent.com/1136402/56865392-a4773a00-69cd-11e9-866f-2e7decca954c.png)

```
<div class="popovermenu open whatsNewPopover menu-left" style="position: fixed;">
  <ul>
    <li><span class="menuitem"><span class="caption">Nouveau dans Feildel Cloud</span><span class="icon-close"></span></span></li>
    <li><span class="menuitem"><span class="icon-checkmark"></span><p>Smart recommendations for files, sharees</p></span></li>
    <li><span class="menuitem"><span class="icon-checkmark"></span><p>Projects: group files, chats, tasks for easy finding</p></span></li>
    <li><span class="menuitem"><span class="icon-checkmark"></span><p>right-click in Files, new document viewer &amp; more</p></span></li>
    <li><a href="https://nextcloud.com/changelog/#16-0-0" rel="noreferrer noopener" target="_blank"><span class="icon-link"></span><span>Voir le journal des modifications</span></a></li>
  </ul>
</div>
```

**Comment by kesselb** [comment]
cc @skjnldsv 🧙

**Comment by kesselb** [comment]
Hey @AMDG2, 

I think this got lost somehow. Is it still happening? If so would you mind to create a pull request with your changes?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
