### ISSUE TITLE
Provide a "lite" version of Nextcloud

### ISSUE THREAD

**Issue by Ailothaen** [nextcloud/server#15275]
When I wanted to install Nextcloud on my VPS server, I wanted to check the size and noticed it was looking really big (~250 MB), for me who only wants to use the file sharing and sync feature.
So I wondered what was taking so much space, and scanned Nextcloud release directory:

![20190428-123318-000264](https://user-images.githubusercontent.com/11133116/56864978-126d3280-69c9-11e9-9d21-e69927fbed13.png)

We can see here a lot of space is taken by the doc, files related to most used passwords, something related to AWS integration...

The thing is, I don't really need those features, as I only plan to use Nextcloud to store and sync my own files. But, on the other hand, I don't know what I can delete without making Nextcloud buggy.

So, something like a "lite" release of Nextcloud, which only includes the most essential components would be really good, especially for people who don't want them and/or are limited by their material (users on Raspberry Pi, for example)

Thanks in advance!

**Comment by AInteriorB** [comment]
I absolutely agree! Nextcloud is growing with so many features that are not really useful for the basic file sharing. The focus shoud be back on the main functionalities, to make those good and robust again.

**Comment by wiswedel** [comment]
Why don't you just remove the apps you don't need?

**Comment by BurtGummer** [comment]
I agree. In general there is a lot of new development, but the old bugs are not fixed. A "lite version" would certainly be easier to maintain.

**Comment by wiswedel** [comment]
> A "lite version" would certainly be easier to maintain.

I disagree. You'd have another branch to take care of.

Again, Nextcloud is a modular application platform, inviting everyone out there to contribute (open source) to the single modules.
If you want it lean, just kick out everything you don't need on the Apps page (you can even get rid of sharing, versions, comments, right click...).

**Comment by AInteriorB** [comment]
I disagree your disagree. We have so many old bugs that are not fixed but the development is on so many "fancy features" that are not necessary for the daily use. Focus should be back on the core functions.

**Comment by wiswedel** [comment]
> We have so many old bugs that are not fixed yet

You're very welcome to contribute and smash some. Nextcloud is only as good as its contributor community makes it. 

https://github.com/nextcloud/server/issues?utf8=✓&q=is%3Aopen+label%3A%22good+first+issue%22+label%3Abug

**Comment by wiswedel** [comment]
superseded by https://github.com/nextcloud/server/issues/17634
