### ISSUE TITLE
Conflicting Upgrade Information

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#15281]
### Steps to reproduce
1. Visit https://yoursite.com//index.php/settings/admin/overview
2. See :
```
SecureSystemDesign.io NextCloud 15.0.6

A new version is available: Nextcloud 15.0.7
All apps have an update for this version available
```

3. Run upgrade on command line:

```
root@nextcloud:/var/www/nextcloud# sudo -u www-data php occ upgrade
```

4. See `Nextcloud is already latest version`

So is "Nextcloud is already latest version" or is "A new version is available"?

### Expected behaviour

Either the Web UI should not say that an upgrade is available or the command line updater should say that it is.

### Actual behaviour

The WebUI says an update is available but the command line says you are at the latest version.

### Server configuration

**Operating system**:  Ubuntu 16.04

**Web server:**  apache2

**Database:** mariaDB

**PHP version:**  7.0.33

**Nextcloud version:** 15.06

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh install of 15 (incremental upgrades)

**Comment by stone212** [comment]
Here are screenshots.

![ANewVersion](https://user-images.githubusercontent.com/26020999/58455535-79d5e980-8111-11e9-8b2f-a8d0b4c4ac9b.png)

![AlreadyLatest](https://user-images.githubusercontent.com/26020999/58455528-6d519100-8111-11e9-8262-4a1f467dee98.png)

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/16/admin_manual/maintenance/update.html#using-the-command-line-based-updater

**Comment by stone212** [comment]
@kesselb That's for v 16.  I checked v 15 and it has the same instructions but I don't think it did.  Was the documentation for v 15 updated after I opened my issue?  Also possible I am confused.  Anyway thank you.  I do have a new problem after upgrading: https://github.com/nextcloud/server/issues/15807

**Comment by kesselb** [comment]
>  Was the documentation for v 15 updated after I opened my issue?

I don't think so: https://github.com/nextcloud/documentation/blame/stable15/admin_manual/maintenance/update.rst

**Comment by stone212** [comment]
Okay well I guess I was looking at an old link.  Thank you again.
