### ISSUE TITLE
Can't download big files

### ISSUE THREAD

**Issue by oceanwave72** [nextcloud/server#15280]
### Steps to reproduce
1.In external storages
2.download a 10GiB file using chrome native downloader or IDM(internet download manager)

### Expected behaviour
Download the whole file successfully

### Actual behaviour
A few seconds after about 700 MiB data has been downloaded, chrome native downloader abort the download. The same situation happens to IDM. The difference is that IDM will reset the connection and re-download file from the start.

### Server configuration

**Operating system**:
debian 9.6
**Web server:**
caddy 0.11.5
**Database:**
 10.1.37-MariaDB

**PHP version:**
php7.3.3
**Nextcloud version:** (see Nextcloud admin page)
15.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from previous nextcloud version
**Where did you install Nextcloud from:**
Official website
**Signing status:**
<details>
<summary>Signing status</summary>
No errors has been found
**List of activated apps:**
<details>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED SENSITIVE VALUE"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "overwrite.cli.url": "https:\/\/REMOVED SENSITIVE VALUE",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpauthtype": "LOGIN"
    }
}

**Are you using external storage, if yes which one: /var/www/html/nextcloud/data/kid/files/download

**Are you using encryption:  /no


### Client configuration
Chrome

**Operating system:**
Windows 10

### Logs
#### Web server error log

#### Nextcloud log (data/nextcloud.log)
didn't show anything meaningful
#### Browser log
<details>
29/Apr/2019:16:29:21 +0800 [ERROR 502 /remote.php/webdav/local/test.iso] http2: stream closed
29/Apr/2019:16:30:32 +0800 [ERROR 502 /remote.php/webdav/local/test.iso] read tcp 127.0.0.1:58484->127.0.0.1:9000: i/o timeout
29/Apr/2019:16:30:51 +0800 [ERROR 502 /remote.php/webdav/local/test.iso] write tcp 10.138.0.7:443->183.222.251.0:17537: write: connection reset by peer
29/Apr/2019:16:31:00 +0800 [ERROR 502 /remote.php/webdav/local/test.iso] write tcp 10.138.0.7:443->183.222.251.0:17538: write: connection reset by peer


</details>

**Comment by oceanwave72** [comment]
At first, the limit is 200 MB
php7.3-fpm.log report the following warning:
`WARNING: [pool www] server reached pm.max_children setting (5), consider raising it`
i change it to 10 ,the download limit turns to 700 MB
the warning still occur.
After i change it to 20, No changes happened this time.

**Comment by go2sh** [comment]
The children count is definitely not your problem. Check for the php timeout options and your web server timeout options. Both kill connection after some time, so for 10G you need a quiet high timeout.
For setup assistance check https://help.nextcloud.com

**Comment by oceanwave72** [comment]
> The children count is definitely not your problem. Check for the php timeout options and your web server timeout options. Both kill connection after some time, so for 10G you need a quiet high timeout.
> For setup assistance check https://help.nextcloud.com

Thanks for your suggestion. I solve this. 
Here are my ways for futher readers:
1. change php.ini max_execution_time to 1800s
2.change caddy fastcgi connect/read/send timeout to 1800s

P.s I don't know if these changes would lead some side effect.
