### ISSUE TITLE
Share permissions: 17 and 19 magic numbers

### ISSUE THREAD

**Issue by aosyatnik** [nextcloud/server#15284]
### Steps to reproduce
1. Share file, as you usually do it in nextcloud.
2. Make get shares for this file. E.g. `curl --user root:11111111 "http://localhost:8080/ocs/v2.php/apps/files_sharing/api/v1/shares?path=/Nextcloud.png&reshares=true" -X GET -H "OCS-APIRequest: true"`
3. Get confused by line `<permissions>17</permissions>` or `<permissions>19</permissions>`.

Screenshot:
![image](https://user-images.githubusercontent.com/8158404/56893289-70118580-6a82-11e9-8a85-fe2ad581b1f2.png)

### Expected behaviour
I'm expecting here to have: permissions - (int) 1 = read; 2 = update; 4 = create; 8 = delete; 16 = share; 31 = all (default: 31, for public shares: (c) [documentation](https://docs.nextcloud.com/server/latest/developer_manual/core/ocs-share-api.html).

I don't know whether it's a mistake in the documentation or in nextcloud server. As far as I understand 17 stands for "user cannot edit the file" and 19 stands for "user can edit the file". But I could find this info neither in the official documentation nor in the [source code](https://github.com/nextcloud/server/blob/master/lib/public/Constants.php).

### Actual behaviour
I'm getting next XML:
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>200</statuscode>
  <message>OK</message>
 </meta>
 <data>
  <element>
   <id>79</id>
   <share_type>0</share_type>
   <uid_owner>root</uid_owner>
   <displayname_owner>root</displayname_owner>
   <permissions>17</permissions>
   <stime>1556527752</stime>
   <parent/>
   <expiration/>
   <token/>
   <uid_file_owner>root</uid_file_owner>
   <note></note>
   <displayname_file_owner>root</displayname_file_owner>
   <path>/Nextcloud.png</path>
   <item_type>file</item_type>
   <mimetype>image/png</mimetype>
   <storage_id>home::root</storage_id>
   <storage>2</storage>
   <item_source>12</item_source>
   <file_source>12</file_source>
   <file_parent>7</file_parent>
   <file_target>/Nextcloud (2).png</file_target>
   <share_with>anna</share_with>
   <share_with_displayname>Anna Melashkina</share_with_displayname>
   <mail_send>0</mail_send>
  </element>
 </data>
</ocs>
```

### Server configuration

**Operating system**: UCS

**Web server:** ??

**Database:** postgres

**PHP version:** ??

**Nextcloud version:** nextcloud/univention-app:14.0.6-0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** ucs app center

### Client configuration
**Browser:** Chrome

**Operating system:** windows 10

**Comment by ChristophWurst** [comment]
It's a bitmask. 17 = 1 + 16 -> read + share, 19 = 1 + 2 + 16 -> read + write + share.

**Comment by aosyatnik** [comment]
I see. So, it's just the sum of several permissions ... I think it's worth to write in the documentation. Thank you for clarifying, @ChristophWurst .

**Comment by ChristophWurst** [comment]
> I think it's worth to write in the documentation.

A ticket or even a pull request for that to https://github.com/nextcloud/documentation/ would be highly appreciated :raised_hands:
