### ISSUE TITLE
Set Default Expiration Date Not Being Enforced

### ISSUE THREAD

**Issue by eatyourpeas747** [nextcloud/server#15283]
### Steps to reproduce
1.  Go to administration > Sharing > Set default expiration date
2.  Go to your files and share a file or folder and the checkbox is unchecked and not enforced
3.

### Expected behaviour
the file or folder would have an expiration date that the user cant edit

### Actual behaviour
there is not expiration date and the user can set it to whatever they want

### Server configuration

**Operating system**:
Ubuntu 16.04.4 LTS

**Nextcloud version:** (see Nextcloud admin page)
15.0.7

*Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Comment by wiswedel** [comment]
Did you try to share with a user or an email recipient?

**Comment by eatyourpeas747** [comment]
I believe both but definitely an active directory user who authenticated.






On Sat, May 4, 2019 at 10:32 AM -0400, "wiswedel" <notifications@github.com> wrote:












Did you try to share with a user or an email recipient?

**Comment by skjnldsv** [comment]
We do not enforce expiration on user sharing. Only public sharing
![Capture d’écran_2019-05-22_10-48-58](https://user-images.githubusercontent.com/14975046/58160682-37c72680-7c7f-11e9-84d0-e87ff4347a1b.png)


There is already an opened issue about this for the email sharing here: #11547
