### ISSUE TITLE
error when I share folder with "id" federated cloud nextcloud 16

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#15298]
I updated two instances of nextcloud 15 to version 16, but I encountered a problem when from a nextcloud v16 I share one folder to another nextcloud 16 via federated cloud id links.

the folder is seen after giving consent, but does not allow access. giving me the following error

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR IS NULL) AND `fileid` = ? ' with params ["698"]: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens
`

How could I solve it?

I attach photo of the problem
![Immagine](https://user-images.githubusercontent.com/35575744/56916402-17a9aa80-6ab9-11e9-8b8a-97babd44697e.png)
![Immagine2](https://user-images.githubusercontent.com/35575744/56916403-18424100-6ab9-11e9-8ae2-fdfac8d27fd1.png)

**Comment by Fake4d** [comment]
same here - I share a webhoster space with another guy on the same server but with different users and installs and we cannot exchange data anymore.. 

Both on Version 16 Nextcloud!

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: There is already another report for it: https://github.com/nextcloud/server/issues/15211
