### ISSUE TITLE
shares duplicate with inheritance

### ISSUE THREAD

**Issue by kronflux** [nextcloud/server#1529]
If a file/folder is shared with a specific user, and later shared with the entire group that user is a part of, the shared item will show multiple times if the specific user share is not removed.
### Steps to reproduce
1. Create a shared item to an individual user
2. Share that item with the group the individual is a part of without removing the individual user share
3. Items show multiple times
### Expected behaviour

A check should be performed to see whether a user is in a particular group that has access. If that user already has access, the share should not be shown multiple times.

(This would also be useful in a case where an outside source is controlling users and groups which allows users to be part of multiple groups (such as the openmediavault plugin))
### Actual behaviour

Shares are shown multiple times to users who already have access via another share.
### Server configuration

**Operating system**: Ubuntu/Linaro 16.04.1 (DietPi)

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.0

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Yes, OwnCloud 9.1.1

**Comment by nickvergessen** [comment]
@rullzer I think we do that for 11, right?

**Comment by rullzer** [comment]
I'll double check. it should.

**Comment by MorrisJobke** [comment]
Fixed in the meantime.
