### ISSUE TITLE
Update to 16.0.0: The table with name 'nextcloud.oc_login_flow_v2' already exists.

### ISSUE THREAD

**Issue by zwergneun** [nextcloud/server#15299]
### Steps to reproduce
1. Update the Apps for 16.0.0
2. Click on update
3.

### Expected behaviour
Update the Apps

### Actual behaviour
Doctrine\DBAL\Schema\SchemaException: The table with name 'nextcloud.oc_login_flow_v2' already exists.

### Server configuration

**Synology DSM 6.2.1-23824 Udate 6**:

**Docker Container**

**Docker Container MariaDB**

**7.3.4**

**N16.0.0** (see Nextcloud admin page)

**Updated from an older Nextcloud 15 something**

**Docker Hub**

**Signing status:**
not possible

**Comment by edvnet** [comment]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: Change row format for oc_addressbooks ...

Reparaturinformation: Change collation for oc_addressbooks ...

Reparaturinformation: Change row format for oc_authtoken ...

Reparaturinformation: Change collation for oc_authtoken ...

Reparaturinformation: Change row format for oc_bookmarks_tags ...

Reparaturinformation: Change collation for oc_bookmarks_tags ...

Reparaturinformation: Change row format for oc_calendarobjects ...

Reparaturinformation: Change collation for oc_calendarobjects ...

Reparaturinformation: Change row format for oc_calendars ...

Reparaturinformation: Change collation for oc_calendars ...

Reparaturinformation: Change row format for oc_calendarsubscriptions ...

Reparaturinformation: Change collation for oc_calendarsubscriptions ...

Reparaturinformation: Change row format for oc_dav_shares ...

Reparaturinformation: Change collation for oc_dav_shares ...

Reparaturinformation: Change row format for oc_migrations ...

Reparaturinformation: Change collation for oc_migrations ...

Reparaturinformation: Change row format for oc_mimetypes ...

Reparaturinformation: Change collation for oc_mimetypes ...

Reparaturinformation: Change row format for oc_systemtag_group ...

Reparaturinformation: Change collation for oc_systemtag_group ...

Reparaturinformation: Change row format for oc_trusted_servers ...

Reparaturinformation: Change collation for oc_trusted_servers ...

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Das Update ist fehlgeschlagen.

**Comment by kesselb** [comment]
@edvnet https://github.com/nextcloud/server/issues/15058

**Comment by zwergneun** [comment]
I sovled my problem by deleting the table oc_login_flow_v2 in the database via the mysql konsole and also the oc_login_flow_v2.ibd file in the filesystem via the file explorer.
Then i started the App Update again and everything works fine now.
Hope this helps.
