### ISSUE TITLE
Email activity notification for (public uploads) - problem with special characters (quotes)?

### ISSUE THREAD

**Issue by autrui** [nextcloud/server#153]
I know it's a very minor issue. I've hesitated to report it at all. But anyway, here it is:

### Steps to reproduce
1. Make sure **activity notifications via _email_** are enabled for files/folders that were uploaded, created
2. Create a _folder_ for public uploads and share it with these settings: shared by **link**, allow editing, hide file list, password protected
2. Log out and upload some file(s) to that folder
3. Wait for the email with the activity notification

### Expected behaviour
Normal plain text email.

### Actual behaviour
Email does not convert `&quot;` to `"`

* **\&quot;**remote user**\&quot;** created Uploads/somepic.jpg

### Server configuration
**Operating system**: CENTOS6
**Web server:** APACHE
**Database:** SQL
**PHP version:** 5.6.21
**Nextcloud version:** 9.0.50
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh owncloud/nextcloud folder with old config.php and previous SQL database
**Where did you install Nextcloud from:** tar ball from nextcloud.com
**Are you using encryption:** no

### Remarks
I think I have set UTF-8 for php etc., it shouldn't be that.
Maybe the user name for people who upload somthing to a public folder could be stripped of the quotes?

**Comment by MorrisJobke** [comment]
This seems to be activity related.

**Comment by nickvergessen** [comment]
Please open a new issue in the activity repository:
https://github.com/nextcloud/activity/issues/new
