### ISSUE TITLE
Some of your Link Shares have been removed

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#15318]
I just upgraded to Nextcloud 16 stable release.
I received a notification that [due to this linked security risk](https://nextcloud.com/security/advisory/?id=NC-SA-2019-003) some of my link shares have been removed.

So, which shares were removed?  All of them?  I see no further information in the Activity app or anywhere else.  This is frustrating, because I do not have further information.  If you decide to remove file shares users have created in the future, please work with the Activity app so users can also confirm exactly what changes were made in addition to the received Notification.

**Comment by rullzer** [comment]
Yes this would have been nicer. But would also have made the repair step less reliable and orders of magnitude slower. I did think about it but I could not come up with a proper scaleable solution in time.

But you are of course right and in the future we will take better care of this.

**Comment by sunjam** [comment]
@rullzer Another quick answer is to warn the user before the shares were actually force removed, perhaps as an earlier notification.

**Comment by radarlog** [comment]
This message pops up quite often and become annoying

**Comment by sunjam** [comment]
The message did not pop up for me until after the shares were removed.

**Comment by radarlog** [comment]
But I have no shares! Moreover I completely disable that functionality!

**Comment by lindhe** [comment]
@rullzer Where can I read more about what links this concerns, and will you automatically restore them?

**Comment by gboisvert** [comment]
In my case, it turned worse: Lost of data... Found the missing data in __groupfolders... Yeah i used this and it seemed it was an error... Upgrading to (damn, when i click "about" under my user, no verion infos..)  16.0.1.  I rsync the __groupfolders on another server, my trust to Nextcloud took a big hit...  Now, how to stop the annoying message, it's driving me crazy to see it all the time...

**Comment by kesselb** [comment]
@gboisvert #15643 (a fix for the misleading message will be released with nextcloud 16.0.2).

**Comment by gboisvert** [comment]
@kesselb Fine but the message doesn't seem to be *that* misleading in my case, because there is still a problem on our server.  Is there any way to remove the "definition" of the shared directory which is really missing (i found it under __groupfolders)?  I don't see it under my account, do i have to fool around inside the SQL database?  Here is the message in the log (1st line):
(real name and share changed for securit7)

Error | index | OCP\Files\NotFoundException: /user/files/Folder1

**Comment by kesselb** [comment]
Would you mind to create a new issue and use the issue template?
