### ISSUE TITLE
Unexpected icon-close in "All files" ui

### ISSUE THREAD

**Issue by xh3n1** [nextcloud/server#15317]
### Steps to reproduce
1. Click "All Files"

### Expected behaviour
The icon-close should not be displayed

### Actual behaviour
icon-close icon is displayed alongside "new" icon

### Server configuration

**Operating system**:
Ubuntu

**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 17.0.0 alpha

**Where did you install Nextcloud from:**
GitHub
<img width="958" alt="Screenshot 2019-04-30 at 22 39 20" src="https://user-images.githubusercontent.com/9008509/56995642-37fd6600-6b9a-11e9-842d-89e55958b220.png">

**Comment by ChristophWurst** [comment]
Sounds like the first issue of the *Files* section of https://github.com/nextcloud/server/issues/14639. I added a reference as there was no ticket for this before.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
