### ISSUE TITLE
update fail from 13.0.6.1 to  14.0.10

### ISSUE THREAD

**Issue by pwgen** [nextcloud/server#15310]
i am using the  ldap backend and can not update

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Not a mysql database -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX ldap_dn_users ON oc_ldap_user_mapping ("ldap_dn")': SQLSTATE[23505]: Unique violation: 7 ERROR: could not create unique index "ldap_dn_users" DETAIL: Key (ldap_dn)=(cn=ajust,ou=people,o=ifa) is duplicated.

**Comment by kesselb** [comment]
`DROP INDEX ldap_dn_users` and try again ;)

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
