### ISSUE TITLE
help.nextcloud.com is down

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#15324]
Please, note, that help.nextcloud.com is down and there's no address the issues to the community and to get answers. Please, fix ASAP! Thank you

**Comment by kesselb** [comment]
@nextcloud/infrastructure :boom:

**Comment by rullzer** [comment]
Yes it is already being worked on. But today is a public holiday. And retrieving the data from the crashed server takes time.

Long story short it is being worked on and will be up as fast as we can make it happen.

**Comment by VGerris** [comment]
this is down currently it seems ?

**Comment by jospoortvliet** [comment]
yeap. Old issue, but we've been working on it on and off - some ipv6 issues I believe.

**Comment by ostasevych** [comment]
I have constant issues with accessing to help.nextcloud.com... The only way, how I manage it is to use TOR baked in Brave :/
