### ISSUE TITLE
Add phone number info to user

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#15322]
Add a phone number input and info to the personal settings

@schiessle  Does it requires any change to the federation?
Is it hard to do?

**Comment by wiswedel** [comment]
Phone number is already there. 
By Info do you mean some textarea for a let's say 140 character slogan?

**Comment by skjnldsv** [comment]
No I meant the one that was already there.
Damn, how did I miss it :grimacing: :see_no_evil:
