### ISSUE TITLE
error while enabling MYSQL 4-byte support

### ISSUE THREAD

**Issue by nephilim75** [nextcloud/server#15328]
### Steps to reproduce
1. sudo -u www-data php occ maintenance:repair

### Expected behaviour
Convert all existing tables to the new collation by running the repair step (step 5):

### Actual behaviour
![grafik](https://user-images.githubusercontent.com/19992865/57022980-1d2a0080-6c31-11e9-8e11-6c0db2b19aec.png)

### Server configuration

**Operating system**: Debian 9 (stretch)

**Web server:** nginx\1.10.3

**Database:** MriaDB 10.1.38

**PHP version:** 7.3.4

**Nextcloud version:** 16.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh installation

**Where did you install Nextcloud from:** Nextcloud release server

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.0.9",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** not yet

**Are you using an external user-backend, if yes which one:** No

I tried the folowing to get it solved as found [here](https://github.com/nextcloud/server/issues/9423):

```
ALTER TABLE oc_activity MODIFY activity_id bigint(20) AUTO_INCREMENT;
ALTER TABLE oc_activity MODIFY subjectparams longtext;
ALTER TABLE oc_activity MODIFY messageparams longtext;
ALTER TABLE oc_activity MODIFY object_id bigint(20);
```

but it did not solve the issue. The result of `sudo -u www-data php occ maintenance:repair` is the same as above.

Kind regards
//neph

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: Check this issue for further information: https://github.com/nextcloud/server/issues/15058
