### ISSUE TITLE
New user Welcome message doesn't honor html codes set by slogan phrase.

### ISSUE THREAD

**Issue by shelterx** [nextcloud/server#15337]
### Steps to reproduce
1. Set a slogan with an ' sign, like I'm the boss of cloud storage!
2. Login as a new user, the welcome message now contains:
`I&#039;m the boss of cloud storage!`

### Expected behaviour
Should display "I'm the boss of cloud storage!"

Nextcloud 15.0.7

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/server/issues/7460
