### ISSUE TITLE
[Nextcloud 15.0.7]  CAS user and group backend 1.6.2 don't work

### ISSUE THREAD

**Issue by narutobaka** [nextcloud/server#15349]
### Steps to reproduce
1. On Nextcloud web interface / Apps menu / type Cas to get CAS user and group backend 1.6.2
2. I click on download and activated
3. 

### Expected behaviour
I would access to CAS user and group backend configuration

### Actual behaviour
I get a white page. Erreur in apache log : 
[Thu May 02 15:48:28.938239 2019] [php7:error] [pid 57592] [client monIP] PHP Fatal error:  Declaration of OCA\\UserCAS\\User\\Backend::checkPassword($uid, $password) must be compatible with OCP\\User\\Backend\\ICheckPasswordBackend::checkPassword(string $loginName, string $password) in /var/www/html/nextcloud/apps/user_cas/lib/User/Backend.php on line 45

### Server configuration

**Operating system**: 

cat /etc/redhat-release
CentOS Linux release 7.6.1810 (Core)

**Web server:**
httpd-2.4.6-89.el7.centos.x86_64

**Database:**
MariaDB-server-10.3.14-1.el7.centos.x86_64

**PHP version:**
php71w-gd-7.1.27-1.w7.x86_64
php71w-xml-7.1.27-1.w7.x86_64
php71w-pecl-apcu-5.1.9-1.w7.x86_64
php71w-common-7.1.27-1.w7.x86_64
php71w-opcache-7.1.27-1.w7.x86_64
php71w-pdo-7.1.27-1.w7.x86_64
php71w-mcrypt-7.1.27-1.w7.x86_64
php71w-ldap-7.1.27-1.w7.x86_64
php71w-devel-7.1.27-1.w7.x86_64
php71w-pear-1.10.4-1.w7.noarch
php71w-mysql-7.1.27-1.w7.x86_64
php71w-cli-7.1.27-1.w7.x86_64
php71w-mbstring-7.1.27-1.w7.x86_64
php71w-process-7.1.27-1.w7.x86_64
php71w-intl-7.1.27-1.w7.x86_64
mod_php71w-7.1.27-1.w7.x86_64

**Nextcloud version:** (see Nextcloud admin page)
15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
update from nextcloud 12

**Where did you install Nextcloud from:**
Initial installation from : curl -o nextcloud-12-latest.tar.bz2 https://download.nextcloud.com/server/releases/latest-12.tar.bz2
I use web interface to update to nextcloud 15.0.7

**Signing status:**
<details>
<summary>Signing status</summary>

```
I can't loggin even when using administrateur account
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - onlyoffice
  - user_cas
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "Mondomaine1.fr",
            "Mondomaine2.fr",
            "Mondomaine3.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/Mondomaine.fr\/nextcloud",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "proxy": "proxy.fr:8080",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "lost_password_link": "disabled",
        "login.alternatives": [
            {
                "href": "\/index.php\/apps\/user_cas\/login",
                "name": "CAS Login",
                "img": "\/apps\/user_cas\/img\/cas-logo.png"
            }
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** I have desactivate LDAP configuration to configure CAS

### Client configuration
**Browser:**
Firefox 60.0.1
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Thu May 02 15:48:31.193149 2019] [php7:error] [pid 57593] [client MonIP] PHP Fatal error:  Declaration of OCA\\UserCAS\\User\\Backend::checkPassword($uid, $password) must be compatible with OCP\\User\\Backend\\ICheckPasswordBackend::checkPassword(string $loginName, string $password) in /var/www/html/nextcloud/apps/user_cas/lib/User/Backend.php on line 45
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by narutobaka** [comment]
Hi 

I go back to Nextcloud 14.0.3 with user_cas 1.5.6 and user_ldap 1.4.0.

user_cas work well now.

But I don't success to use ldap_userlist_filter with user_cas. (cf my post on forum here : https://help.nextcloud.com/t/cas-authentication-with-ldap-filter/53195 )

It seems that all ldap config is ignore since user_cas is enable.

How to limit user granted to connect with user_cas enable? 
Is that possible?

cordialy

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
