### ISSUE TITLE
invalid SQL statement during creation of admin account

### ISSUE THREAD

**Issue by scottfagg** [nextcloud/server#15344]
### Steps to reproduce
1. Using Fedora 30, nextcloud-10.0.4-7.fc30.noarch.rpm 
2. install nextcloud
3. visit http://server/nextcloud 
4. provide new admin account details
5. click (Finish Setup) button

error returned is :
Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE "oc_storages" ("id" VARCHAR(64) DEFAULT NULL, "numeric_id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL PRIMARY KEY AUTOINCREMENT, "available" INTEGER DEFAULT 1 NOT NULL, "last_checked" INTEGER DEFAULT NULL)':

SQLSTATE[HY000]: General error: 1 table "oc_storages" has more than one primary key

( note the mention of PRIMARY KEY twice in the SQL statement)
					

### Expected behaviour

* admin account should be created with out error

### Actual behaviour

* error thrown when hitting (Finish Setup)

### Server configuration

**Operating system**: Fedora 30

**Web server:** Apache

**Database:** SQLite

**PHP version:** 7.3.4

**Nextcloud version:** 10.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** Fedora 30 repositories

**Signing status:**

**List of activated apps:**

unknown

**Nextcloud configuration:**

Nextcloud is not installed - only a limited number of commands are available

                                                                  
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  There are no commands defined in the "config" namespace.  

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox

**Operating system:** macos

**Comment by kesselb** [comment]
Nextcloud 10.x is end of life for a long time. Could try a newer version? I'm afaid but there is no rpm package for newer versions :disappointed: (there are some issues with packaging nextcloud afaik)

**Comment by scottfagg** [comment]
Tried the current source install and that worked fine. I'd switch from source to RPM hoping it would take care of the install for me (although install from source isn't that complicated anyway).
