### ISSUE TITLE
Nextcloud 16 - Trash is not accessible

### ISSUE THREAD

**Issue by Larsene** [nextcloud/server#15356]
After upgrading to Nextcloud 16, the trash is not accessible

### Expected behaviour
Opening the trash folder

### Actual behaviour
error message --> to read the logs

### Server configuration

**Operating system**: NextcloudPi

**PHP version:** 7.2

**Nextcloud version:** 16

**Updated from an older Nextcloud:**

###logs :

Error | remote | TypeError: Return value of OCA\Files_Trashbin\Sabre\AbstractTrash::getSize() must be of the type integer, float returned/var/www/nextcloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php - line 78:OCA\Files_Trashbin\Sabre\AbstractTrash->getSize()/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php - line 98:OCA\Files_Trashbin\Sabre\PropfindPlugin->OCA\Files_Trashbin\Sabre\{closure}("*** sensiti ... *")/var/www/nextcloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php - line 79:Sabre\DAV\PropFind->handle("{http://owncloud.org/ns}size", Closure {})<<closure>>OCA\Files_Trashbin\Sabre\PropfindPlugin->propFind(Sabre\DAV\PropFind {}, OCA\Files_Tr ... {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ OCA\Files_ ... "], [ Sabre\DAV\ ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1059:Sabre\Event\EventEmitter->emit("propFind", [ Sabre\DAV\ ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 981:Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\Files_Tr ... {})/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1666:Sabre\DAV\Server->getPropertiesIteratorForPath("trashbin/admin/trash", [ "{http://n ... "], 1)/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 355:Sabre\DAV\Server->generateMultiStatus(Generator {}, false)<<closure>>Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:Sabre\Event\EventEmitter->emit("method:PROPFIND", [ Sabre\HTTP ... }])/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/nextcloud/apps/dav/lib/Server.php - line 316:Sabre\DAV\Server->exec()/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:OCA\DAV\Server->exec()/var/www/nextcloud/remote.php - line 163:require_once("/var/www/ne ... p")
-- | -- | --

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Please check this report for further information: https://github.com/nextcloud/server/issues/13160
