### ISSUE TITLE
[Nextcloud 16.0.0] logout does not finish

### ISSUE THREAD

**Issue by zxtwonder** [nextcloud/server#15352]
### Steps to reproduce
1. Create a demo Nextcloud 16.0.0 instance at https://demo.nextcloud.com/
2. Log in
3. Log out

### Expected behaviour
Logout finishes and user is redirected to login page.

### Actual behaviour
Logout circle keeps spinning and the user is never redirected.

The session seems to be terminated though. Refreshing the page will trigger redirection.

**Comment by andrewborell** [comment]
I have this issue as well and found that by clicking the logout button a second time will immediately log the user out, but if they attempt to log back in under any account, the URI is still set to the logout uri so upon login I get a CSRF error, even with the csrf checking setting in the config set to false.  

This happens on the three last versions of chrome and in MS Edge ( version not available right now ) so far in my testing. In the case of Edge however, I found even clicking files hangs so I think edge has its own set of issues.  For chrome however this is unusual.

**Comment by zxtwonder** [comment]
Interestingly, it seems that logout works fine in Chrome Incognito mode, but not in normal mode - might be related to states from earlier versions?

**Comment by DrRSatzteil** [comment]
I've got the same issue here. I think it was already there with nc 15 but I cannot reproduce that anymore.

**Comment by bluewhitetobi** [comment]
Same here. Second click on logout does it but after logout I try the login and get csfr error because in this url is the logout tag behind the domain

**Comment by Dennis1993** [comment]
Maybe this problem?
https://github.com/nextcloud/server/issues/4151

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

Tried to reproduce this issue with https://try.nextcloud.com but no luck. I suspect you run nextcloud as docker and have an invalid reverse proxy configuration but without the issue template can't say.

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by actyler555** [comment]
I seem to be experiencing this issue also.  Logout takes about 30 seconds to a minute.  See the attached screenshot for the Chrome console data..  The following is some basic info on the server, a dedicated Ubuntu server 18.04 VMware VM.

Nextcloud
Version: 16.0.4.1
Apps installed: 40
Apps updates available: 1

PHP
Version: 7.2.19
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 1000 MB

Database
Type: pgsql
Version: PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit
Size: 12.5 MB

![Snap67](https://user-images.githubusercontent.com/9203016/64982737-c33e7600-d873-11e9-9f6c-2054afa39c88.jpg)

**Comment by kesselb** [comment]
Could you check with firefox?

**Comment by actyler555** [comment]
> Could you check with firefox?

Hmm..  Having trouble re-creating the issue now for some reason.  I will keep trying and get back soon.

Regards,
Adam Tyler

**Comment by jizichun** [comment]
hmm do we got a fix? I also got this issue

**Comment by jizichun** [comment]
Just find the fix for this problem, I clear the cache for chrome and everything work without a problem. So if you have the same issue and are using chrome just go to settings and clear the cache
