### ISSUE TITLE
does not work, can't remove warning message, steps unclear, steps ineffective

### ISSUE THREAD

**Issue by Oclair** [nextcloud/server#15358]
If the instructions and messages are unclear leading to inconclusive steps how can we expect it to actually work?

1. does not work
2. warning message indicates vague steps to setup
3. setup ineffective with vague steps to enable for user

how is this an official app?

should be documented as not ready for production

**Comment by kesselb** [comment]
Mind to use the issue template if reporting a bug?

**Comment by Oclair** [comment]
I believe the same standard should apply to code submissions

**Comment by kesselb** [comment]
Sorry, what are you referring to?

**Comment by skjnldsv** [comment]
Please read https://nextcloud.com/code-of-conduct/ and open a new issue while following the report template.

Thanks a lot!
John
