### ISSUE TITLE
Content Security Policy blocks piwik.js (script-src)

### ISSUE THREAD

**Issue by criegerde** [nextcloud/server#15351]
Nextcloud is working as expected.
  - installed: true
  - version: 16.0.0.9
  - versionstring: 16.0.0

Having the Matomo/piwik app installed and enabled leads to CSP errors that are thrown in the browser console (F12  // Firefox 66.0.3 // no addons)
- Nextclud 16
- PHP7.3
- MariaDB
- Debian 9.9 stretch
- NGINX 1.16 TLSv1.2
- Firefox 66.0.3

![grafik](https://user-images.githubusercontent.com/47498887/57106810-a1ae7900-6d2e-11e9-8845-8e8131a729d3.png)

Matomo/PIWIK was installed properly, my list of apps:

`Enabled:
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - apporder: 0.7.1
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - keeweb: 0.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - piwik: 0.5.1
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - rainloop: 6.0.2
  - recommendations: 0.4.0
  - sharebymail: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 2.1.2
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - accessibility
  - comments
  - encryption
  - federation
  - files_versions
  - firstrunwizard
  - nextcloud_announcements
  - serverinfo
  - support
  - survey_client
  - systemtags
  - user_ldap

All of the previous mentioned [fixes](https://github.com/sualko/cloud_piwik/issues/30#issuecomment-488836701) causes the app to change its state from being enabled to disabled.
[Xqua](https://github.com/sualko/cloud_piwik/issues/30#issuecomment-488836701) gave up.

May i ask you Nextclouders to investigate further? If you are interested in i could grant access to my environment - please let me know.

NGINX is configured properly for Nextcloud and as well for Matomo/Pwik
the vhost looks like:

`server {
server_name subdomain.c-rieger.de;
listen 80 default_server;
location ^~ /.well-known/acme-challenge {
proxy_pass http://127.0.0.1:81;
proxy_set_header Host $host;
}
location / {
return 301 https://$host$request_uri;
}
}
server {
server_name subdomain.c-rieger.de;
listen 443 ssl http2 default_server;
root /var/www/nextcloud/;
access_log /var/log/nginx/access.log main;
error_log /var/log/nginx/error.log warn;
location = /robots.txt {
allow all;
log_not_found off;
access_log off;
}
location = /.well-known/carddav {
return 301 $scheme://$host/remote.php/dav;
}
location = /.well-known/caldav {
return 301 $scheme://$host/remote.php/dav;
}
client_max_body_size 10240M;
location / {
rewrite ^ /index.php$request_uri;
}

location ^~ /piwik {
location /piwik {
rewrite ^ /piwik/index.php$request_uri;
}
location ~ ^/piwik/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
fastcgi_split_path_info ^(.+\.php)(/.*)$;
include fastcgi_params;
include php_optimization.conf;
fastcgi_pass php-handler;
fastcgi_param HTTPS on;
}
location ~ \.(?:png|html|ttf|ico|jpg|jpeg|css|js|woff2?|svg|gif)$ {
try_files $uri /piwik/index.php$request_uri;
access_log off;
expires 360d;
}
}
location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
deny all;
}
location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
deny all;
}
location ~ \.(?:flv|mp4|mov|m4a)$ {
mp4;
mp4_buffer_size 100M;
mp4_max_buffer_size 1024M;
fastcgi_split_path_info ^(.+\.php)(/.*)$;
include fastcgi_params;
include php_optimization.conf;
fastcgi_pass php-handler;
fastcgi_param HTTPS on;
}
location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
fastcgi_split_path_info ^(.+\.php)(/.*)$;
include fastcgi_params;
include php_optimization.conf;
fastcgi_pass php-handler;
fastcgi_param HTTPS on;
}
location ~ ^/(?:updater|ocs-provider)(?:$|/) {
try_files $uri/ =404;
index index.php;
}
location ~ \.(?:css|js|woff2?|svg|gif|png|html|ttf|ico|jpg|jpeg)$ {
try_files $uri /index.php$request_uri;
access_log off;
expires 360d;
}
}

Looking forward to your response...
Cheers, Carsten (https://www.c-rieger.de)

**Comment by rullzer** [comment]
Please report that to the app.
The app should set the allowed host in the CSP.

**Comment by criegerde** [comment]
solved by [#70](https://github.com/sualko/cloud_piwik/issues/30)
