### ISSUE TITLE
Recheck Database after upgrade for correct structure

### ISSUE THREAD

**Issue by Ang3er** [nextcloud/server#15361]
Iam following Owncloud/Nextcloud since version 4 or 5. Scince then a lot of stuff has changed, regarding apps, and features also the structure of the database. I got several issues regarding the db structure of tables resolved due to upgrades and errormessages, but now for example i got stuck with the activity_mq table, which will not hold any data. To put it better I am not able to send mails on changes with the activitiy:send-mails feature. 
I would like to generally check the current database schemas and columns (shouldnt be to hard, as all apps define their intended structures) via an occ command, similar to db conversion  and db-update indicies.
Currently Iam not aware of any comparison database which shows the correct and new strutcture for the tables. As well I would like to clean the database from old tables (of old apps) which are not used anymore.

Thanks in advance

![image](https://user-images.githubusercontent.com/12126245/57138851-006a0600-6db4-11e9-90ae-cf9e730e4b81.png)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
