### ISSUE TITLE
Auto update apps feature request

### ISSUE THREAD

**Issue by auberginepop** [nextcloud/server#15360]
It would be nice to have a feature (perhaps checkbox in preferences) to allow apps to update automatically when an update is available.

**Comment by bpcurse** [comment]
It might be even better if this would be a per app setting, as some apps have more impact on the whole instance's usability and a "buggy" new version would cause major issues up to rendering the whole instance unusable.

A possible way to mitigate this issue, could be an auto update that doesn't update immediately, but uses a "grace period" (individually configurable?), e.g. 3 days before updating.

**Comment by auberginepop** [comment]
I suspect the per app feature would be much more difficult to implement.
If people are running "buggy" apps then upgrading is always likely to be a manual process for them with more control required and this auto update feature would not be useful to those users.
I thought the feature would be better for those users with very standard installs who want to minimise the amount of time spent on sys admin.

**Comment by auberginepop** [comment]
I agree that this feature request is covered by #15416 .

**Comment by YouveGotMeowxy** [comment]
Not to sound rude, but based on the date of the OP, I guess this is never gonna happen?

**Comment by szaimen** [comment]
If you have root access to your server you could create a cronjob with:
`occ app:update --all`

**Comment by YouveGotMeowxy** [comment]
@szaimen ty. I'm running NC in a container though, so I'm not sure how to do that?

**Comment by szaimen** [comment]
maybe this helps?
https://help.nextcloud.com/t/adding-a-cronjob-via-dockerfile/57317

**Comment by YouveGotMeowxy** [comment]
Thank you for your consideration. @szaimen . I will try that, but this is part of the problem; I'm not a real techy type person, so having to create an entirely different container that I build myself to run a cron, including another container's overhead, seems kinda ridic just to have an auto-update app function, no?

Hopefully in the upcoming NC 19 they added this basic functionality in.

**Comment by davidszpak** [comment]
Frank Karlitschek
@fkarlitschek - 12h
If you want all your Nextcloud Apps updated automatically then Christoph has a solution for you:

https://github.com/ChristophWurst/unattended_upgrades

**Comment by brianjmurrell** [comment]
That project says, right in it's [README](https://github.com/ChristophWurst/unattended_upgrades/blob/main/README.md):

>The app is still under development, so it’s time for you to get involved! 
>…
>Commonly asked questions.
>
>Should I run this in production?
>No, this app is an experiment. However, if you like living on the edge you may of course deploy the app anyway.

How does that qualify to close this issue?  Please re-open this issue until there is a production-quality solution.
