### ISSUE TITLE
CardDAV / DAVdroid / Contacts-App issue

### ISSUE THREAD

**Issue by AndyScherzinger** [nextcloud/server#1537]
The following review/issue has been reported on the Play store for the Android app but is not related to the app itself, since we "just" help setting up DAVdroid, so this is rather related to a combination of CardDAV / DAVdroid / Contacts-App. So looping in @rfc2822 for the DAVdroid side of life.

> Very chic but CardDAV problems The new integration with DavDroid must still be considered an experiment as long as the interaction with the Contacts app are shot to pieces on the server Before / surnames and birthdays
> 
> Original review
> 
> Sehr schick aber CardDAV Probleme Die neue Integration mit DavDroid muss noch als Experiment angesehen werden solang im Zusammenspiel mit der Contacts-App auf dem Server Vor/Nachnamen und Geburtstage zerschossen werden

**Comment by nickvergessen** [comment]
I guess there is no further information what was "shot to pieces"?

**Comment by AndyScherzinger** [comment]
Unfortunately no, I replied to the play store review also referencing to this tracker issue and can ask if he would be willing to join this discussion here.

**Comment by Po2le** [comment]
Hi,

I'm the original reviewer. I wanted to point out that the combination of DAVdroid/NextCloud 
might damage contacts.

The bugs seem to be well known, but it might not be clear which component is causing them in all cases.

https://github.com/owncloud/contacts/issues/466
https://github.com/owncloud/contacts/issues/276
https://github.com/owncloud/contacts/issues/324

Even if this is all the fault of owncloud/contacts or DAVdroid, it is still the solution the 
nextcloud-android-app is "advertising" at the moment.

**Comment by AndyScherzinger** [comment]
Hi @Po2le thanks for joining the discussion. I didn't intent to leave the impression that the Android development team is explaining away, rather than pushing the discussion/search into the right direction as in server-side/app-related. @jancborchardt know anyone who could get involved here? The contacts app doesn't seem to be maintained by the Nextcloud community but to some extend by oC

**Comment by nickvergessen** [comment]
I will have a look at those 3 issues

**Comment by tessus** [comment]
Yep, the contacts app is a mess. I opened an issue https://github.com/owncloud/contacts/issues/435, where I explained the problems, but guess what. It was closed and all my valid points ignored.

This is one of the reasons why I still use oc 8.2.7. I can't afford to screw up my contacts. Otherwise I would have migrated to oc 9.x (back then) or nextcloud (now) a long time ago.

**Comment by Po2le** [comment]
Hi, just tested with NC11 and DAVdroid 1.3.4.1 and as far as I am concerned all issues solved  :smiley:

Thanks for the great work you are doing

**Comment by jancborchardt** [comment]
@Po2le awesome, great to hear! :)

@AndyScherzinger As far as I know @LukasReschke and @rullzer work on the server side of this. And the Contacts app is done by @nextcloud/contacts :)

**Comment by jancborchardt** [comment]
@tessus the correct link to the Contacts app is https://github.com/nextcloud/contacts ;)

**Comment by tessus** [comment]
@jancborchardt Great, thanks. This looks very promising. I will try to do a test migration from oc 8.2.7 to nc 11.0.0. I hope I find a way to do this somehow. Cheers.

**Comment by MorrisJobke** [comment]
This issue seems to be resolved -> closing :)
