### ISSUE TITLE
User management: automatically delete accounts that have never been used

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#15371]
**Is your feature request related to a problem? Please describe.**
In some settings there might be a lot of accounts that have been created but were never used. If these accounts contain personal data, there might be legal implications regarding EU GDPR Art. 17 (1)(a)

**Describe the solution you'd like**
A configurable auto deletion of accounts that have not been used for a long time or have never been used at all.

For accounts that have been used in the past and contain data there should be a multi-step approach, before the account is deleted. 
For example:

- Step one: inform the user that the account has been inactive for a long time and inactive accounts will be deleted after x months. 

- Second step: warn the user some time later that the account has been scheduled for deletion at date x and all data will be lost. 

- Third step: warn the user a last time that the account will be deleted in 3 days.
At step 3 the admin should probably be informed as well.

- Finally, send a confirmation that the account and all data has been deleted

**Additional context**
Legal ref.:
https://eur-lex.europa.eu/legal-content/EN/TXT/HTML/?uri=CELEX:32016R0679&from=EN

**Comment by bpcurse** [comment]
FTR: There seems to be an app for this, but judging by the app description I don't think it has the above features (send warnings the user before deletion).
https://github.com/nextcloud/user_retention

**Comment by szaimen** [comment]
Please see https://github.com/nextcloud/user_retention/issues/30 and https://github.com/nextcloud/user_retention/issues/29. Thanks!
