### ISSUE TITLE
unlimited quota still shows space usage bar

### ISSUE THREAD

**Issue by tessus** [nextcloud/server#15380]
### Steps to reproduce
1. Open Users page
2. Change a user to unlimited quota
3. Check the space usage bar

### Expected behaviour
The space usage bar should not be shown

### Actual behaviour
The bar is shown, but the percentage of the bar makes no sense. First I thought it might show the remaining space on the server, but this is not the case:

```
Filesystem        Size  Used Avail Use% Mounted on
/dev/mapper/XXX  3.7T  1.4T  2.4T  37% /XXX
```
(As you can see, more than 50% are available, yet the bar is showing more than 50% used.)

It seems it still shows the usage against the previous quota.

<img width="181" alt="image" src="https://user-images.githubusercontent.com/223439/57186942-9b96d480-6eb5-11e9-8ee6-9e33c4c65159.png">

## Server configuration detail

**Operating system:** Linux

**Webserver:** Apache/2.4.39

**Database:** mysql 5.6.25

**PHP version:** 

7.2.18
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gnupg, SPL, hkct, ibm_db2, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, PDFlib, mysqli, PDO, pdo_ibm, pdo_mysql, pdo_sqlite, Phar, posix, readline, Reflection, imap, shmop, SimpleXML, sockets, exif, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, zip, cgi-fcgi, apcu, imagick, mongodb, igbinary, sodium, redis, mcrypt, luasandbox, Zend OPcache

**Nextcloud version:** 15.0.7 - 15.0.7.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.10

**Where did you install Nextcloud from:** updater.phar

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - announcementcenter: 3.4.1
 - apporder: 0.6.0
 - bookmarks: 1.0.2
 - bruteforcesettings: 1.3.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dav: 1.8.1
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - phonetrack: 0.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - systemtags: 1.5.0
 - tasks: 0.9.8
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - twofactor_totp: 2.1.2
 - twofactor_u2f: 2.1.3
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - activitylog
 - encryption
 - files_markdown
 - support
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "15.0.7.0",
    "installed": true,
    "forcessl": true,
    "loglevel": 2,
    "maintenance": false,
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "share_folder": "\/Shared",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logdateformat": "Y-m-d H:i:s O",
    "logtimezone": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "appstore.experimental.enabled": true,
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "production",
    "htaccess.RewriteBase": "\/",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": false,
    "theme": "",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:66.0) Gecko/20100101 Firefox/66.0

**Operating system:** macOS 10.14.4

## Logs

Nothing in the logs.

**Comment by andyxh** [comment]
Yes i agree with this post! I have the same thing under my server 

![image](https://user-images.githubusercontent.com/24574019/57251097-9d27e000-700e-11e9-8740-ac5252d7fa55.png)

**Comment by tessus** [comment]
@andyxh in that case, please add a tumbs-up 👍 reaction to my post above.

**Comment by tessus** [comment]
Anyone? Is this a bug or is it working as designed that a random bar is shown for an unlimited quota?

**Comment by kesselb** [comment]
> Anyone? Is this a bug or is it working as designed that a random bar is shown for an unlimited quota?

It's not random (at least not for nextcloud 16) :sunglasses: 

https://github.com/nextcloud/server/blob/c6a69ba92514587814d0f03b51e1d1f026a49350/lib/private/legacy/helper.php#L527-L541

Bar is the `relative usage` of the file system. Weird is the calculation of the total space. Its `usage` + `free_space` where `usage` is the sum of your files. Could that explain your number? `relative usage` is  `used` / `total`.

I would vote for "hide the bar if quota is unlimited".

**Comment by tessus** [comment]
@kesselb I'm not quite sure, I understand that logic. 

That's the filesystem I use:

```
Filesystem        Size  Used Avail Use% Mounted on
/dev/mapper/XXX   3.7T  1.4T  2.4T  37% /XXX
```

The data directory for nextcloud is on that filesystem. So how shall I calculate what you want me to calculate? I'm not sure I follow.

I agree, the bar should not be shown, especially since the value that is shown makes no sense. (As I mentioned before, 37% are used, but the bar shows more than 50% used. Thus no matter how you calculate, the bar is just wrong.)

**Comment by kesselb** [comment]
Mind to test #16049 if you have time?

**Comment by tessus** [comment]
Will do, later tonight. I'm on my way to a bbq...

Btw, I'm using 15.0.x, so the fix is hopefully not only for nc 16. (I haven't checked the fix on my mobile)
-- 
regards Helmut K. C. Tessarek

(sent from a mobile device)

**Comment by kesselb** [comment]
> The data directory for nextcloud is on that filesystem. So how shall I calculate what you want me to calculate? I'm not sure I follow.

It's a bit confusing indeed :roll_eyes: and looks wrong to me.

$1 Take your available space: 1.4TB 
$2 Change into your data directory `data/tessus/files` and run `du -hs .`

Total Space = $1 + $2 (which is not the total space but yes ...)
Usage = $2 / Total Space

And usage is used as value for the bar. I think we can ignore this for the moment because we are not showing the bar anymore ...

> Btw, I'm using 15.0.x, so the fix is hopefully not only for nc 16. (I haven't checked the fix on my mobile)

It's for Nextcloud 17 actually but `appnavigation.php` for 16 and 15 look similar so we might backport it. 

> I'm on my way to a bbq...

Have a good time :beers:

**Comment by tessus** [comment]
The fix is not working for me. The bar is still shown.

I'm using redis. Is it possible that this part is cached? I certainly do not want to flush my entire redis cache, especially since my redis is not used for nextcloud exclusively.

Or maybe the fix does not work on 15.0.x.

**Comment by tessus** [comment]
@kesselb please advise what I shall do/test next.

**Comment by kesselb** [comment]
> @kesselb please advise what I shall do/test next.

Thanks :+1: The pull request is currently under review so some of the core developers will test it :sunglasses:

**Comment by tessus** [comment]
Ok, but I still could need some info why the bar is still shown with the patch.

**Comment by tessus** [comment]
@kesselb I think we might have talked passed each other. I was actually talking about the space usage bar in the users overview: `https://example.com/settings/users`
Your change was apparently for the Files app.

The thing is that they look completely different on my system (your fix is not applied):

**Settings -> Users**

<img width="177" alt="image" src="https://user-images.githubusercontent.com/223439/60056521-2c688000-96af-11e9-846b-565a248361b9.png">

**Files app**

<img width="292" alt="image" src="https://user-images.githubusercontent.com/223439/60056544-3e4a2300-96af-11e9-8972-194d9c9059f0.png">

**Comment by tessus** [comment]
@kesselb did you see my last comment? the issue I opened was clearly about the user page. The 1st step to reproduce states:

> Open Users page

**Comment by kesselb** [comment]
Indeed :rofl: :see_no_evil: Are the usage and total values in the files app more plausible?

**Comment by tessus** [comment]
It looks that way. 16.3 GB used and 2.4 TB available...

<img width="292" alt="image" src="https://user-images.githubusercontent.com/223439/60056544-3e4a2300-96af-11e9-8972-194d9c9059f0.png">

**Comment by tessus** [comment]
So what now? What are the next steps?

**Comment by tessus** [comment]
Ping

**Comment by tessus** [comment]
Well, I guess showing a space quota bar with a random usage is normal for Nextcloud.
