### ISSUE TITLE
Nextcloud Mise à jour vers 13.0.2

### ISSUE THREAD

**Issue by Nadaillat** [nextcloud/server#15382]
Nextcloud
Mise à jour vers 13.0.2

Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_file_locks (id, lock, "key", ttl) SELECT id, lock, "key", ttl FROM __temp__oc_file_locks': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_file_locks.key
Journaux détaillés
Préparation de la mise à jour
Réglage du niveau de journalisation à "déboguage"
Mode de maintenance activé
Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'INSERT INTO oc_file_locks (id, lock, "key", ttl) SELECT id, lock, "key", ttl FROM __temp__oc_file_locks': SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: oc_file_locks.key
La mise à jour a échoué. Veuillez reporter le problème à la communauté Nextcloud.

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
