### ISSUE TITLE
Nextcloud Client Unshare does not work

### ISSUE THREAD

**Issue by manu1214** [nextcloud/server#15396]
### Steps to reproduce
1.  Windows Nextcloud Client: create a Public Link
2. Unshare
3. Nothing Happens

### Expected behaviour
The Checkbox should be unmarked

### Actual behaviour
The Checkbox is still marked.

**Nextcloud version:**
16.0.0.9 stable/ Client 2.5.2

![share](https://user-images.githubusercontent.com/30651212/57236197-c7849800-7024-11e9-9585-9bc40d1904a1.PNG)

![share2](https://user-images.githubusercontent.com/30651212/57236296-031f6200-7025-11e9-86b8-5907e895e714.PNG)

![share3](https://user-images.githubusercontent.com/30651212/57236298-04e92580-7025-11e9-930d-3144f609e67e.PNG)

**Comment by camilasan** [comment]
Hi, this is fixed in 2.5.3 rc1. This was a problem in the client because it was not handling multiple share links.
