### ISSUE TITLE
Federated Cloud share from NC 16.0 to NC 15.0.7 not working

### ISSUE THREAD

**Issue by DominikWA** [nextcloud/server#15393]
### Steps to reproduce
1. Create a federated cloud share (folder) from a NC 16.0 to a NC 15.0.7 instance.
    Alternatively update a NC instances to16.0 with existing federated cloud shares to a older       instance
2. Destination NC instance will show internal server error in the latest windows desktop client
    and will not show/sync the files, even in the web interface

### Expected behaviour
The federated share should be backward compatible and working in this scenario

#### Nextcloud log (data/nextcloud.log)

> {"reqId":"2RqOrHykBAEDolyTpXZc","level":4,"time":"2019-05-06T12:31:58+00:00","remoteAddr":"--IP--","user":"--USER--","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/--USER--\/--FOLDER--","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ' with params [\"11422518\"]:\n\nSQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens","Code":0,"Trace":[{"file":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":128,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ' with params [\"11422518\"]:\n\nSQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens",{"errorInfo":["HY093",0],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"}]},{"file":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":855,"function":"driverExceptionDuringQuery","class":"Doctrine\\DBAL\\DBALException","type":"::","args":[{"__class__":"Doctrine\\DBAL\\Driver\\PDOMySql\\Driver"},{"errorInfo":["HY093",0],"__class__":"Doctrine\\DBAL\\Driver\\PDOException"},"UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",{"1":"*** sensitive parameter replaced ***"}]},{"file":"\/var\/www\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"],[],null]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Cache.php","line":333,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":111,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":111,"function":"put","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":97,"function":"addResult","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",""]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":44,"function":"scanAll","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":[]},{"file":"\/var\/www\/lib\/private\/Files\/View.php","line":1332,"function":"scan","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["",false]},{"file":"\/var\/www\/lib\/private\/Files\/View.php","line":1376,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"mountPoint":"\/--USER--\/files\/--FOLDER--\/","cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\RansomwareProtection\\StorageWrapper"},"","\/\/--FOLDER--"]},{"file":"\/var\/www\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":223,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/--USER--\/files\/--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":967,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/--USER--\/--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files\/--USER--\/--FOLDER--",["{DAV:}resourcetype","{DAV:}getlastmodified","{DAV:}getcontentlength","{DAV:}getetag","{http:\/\/owncloud.org\/ns}id","{http:\/\/owncloud.org\/ns}downloadURL","{http:\/\/owncloud.org\/ns}dDC","{http:\/\/owncloud.org\/ns}permissions","{http:\/\/owncloud.org\/ns}checksums","{http:\/\/owncloud.org\/ns}share-types"],1]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/apps\/dav\/lib\/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/remote.php","line":163,"args":["\/var\/www\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":115,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDOException","Message":"SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens","Code":"HY093","Trace":[{"file":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":849,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"],[],null]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Cache.php","line":333,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":111,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":111,"function":"put","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":97,"function":"addResult","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",""]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":44,"function":"scanAll","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":[]},{"file":"\/var\/www\/lib\/private\/Files\/View.php","line":1332,"function":"scan","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["",false]},{"file":"\/var\/www\/lib\/private\/Files\/View.php","line":1376,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"mountPoint":"\/--USER--\/files\/--FOLDER--\/","cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\RansomwareProtection\\StorageWrapper"},"","\/\/--FOLDER--"]},{"file":"\/var\/www\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":223,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/--USER--\/files\/--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":967,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/--USER--\/--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files\/--USER--\/--FOLDER--",["{DAV:}resourcetype","{DAV:}getlastmodified","{DAV:}getcontentlength","{DAV:}getetag","{http:\/\/owncloud.org\/ns}id","{http:\/\/owncloud.org\/ns}downloadURL","{http:\/\/owncloud.org\/ns}dDC","{http:\/\/owncloud.org\/ns}permissions","{http:\/\/owncloud.org\/ns}checksums","{http:\/\/owncloud.org\/ns}share-types"],1]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/apps\/dav\/lib\/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/remote.php","line":163,"args":["\/var\/www\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":107,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens","Code":"HY093","Trace":[{"file":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","line":105,"function":"execute","class":"PDOStatement","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php","line":849,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDOStatement","type":"->","args":[["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/lib\/private\/DB\/Connection.php","line":195,"function":"executeQuery","class":"Doctrine\\DBAL\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"],[],null]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Cache.php","line":333,"function":"executeQuery","class":"OC\\DB\\Connection","type":"->","args":["UPDATE `oc_filecache` SET =? WHERE ( <> ? OR  IS NULL) AND `fileid` = ? ",["*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Cache","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":138,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":111,"function":"update","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":111,"function":"put","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":["","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":97,"function":"addResult","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["*** sensitive parameter replaced ***",""]},{"file":"\/var\/www\/apps\/files_sharing\/lib\/External\/Scanner.php","line":44,"function":"scanAll","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":[]},{"file":"\/var\/www\/lib\/private\/Files\/View.php","line":1332,"function":"scan","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->","args":["",false]},{"file":"\/var\/www\/lib\/private\/Files\/View.php","line":1376,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"mountPoint":"\/--USER--\/files\/--FOLDER--\/","cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\RansomwareProtection\\StorageWrapper"},"","\/\/--FOLDER--"]},{"file":"\/var\/www\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":223,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/--USER--\/files\/--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":967,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files\/--USER--\/--FOLDER--"]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files\/--USER--\/--FOLDER--",["{DAV:}resourcetype","{DAV:}getlastmodified","{DAV:}getcontentlength","{DAV:}getetag","{http:\/\/owncloud.org\/ns}id","{http:\/\/owncloud.org\/ns}downloadURL","{http:\/\/owncloud.org\/ns}dDC","{http:\/\/owncloud.org\/ns}permissions","{http:\/\/owncloud.org\/ns}checksums","{http:\/\/owncloud.org\/ns}share-types"],1]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/--DST-NC--\/remote.php\/dav\/files\/--USER--\/--FOLDER--","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/apps\/dav\/lib\/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/remote.php","line":163,"args":["\/var\/www\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/var\/www\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php","Line":105}},"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.1final (build 20181204) (Nextcloud)","version":"15.0.7.0"}

**Comment by alie2n** [comment]
We are experiencing the same issue. We had (in the past) external shares working. As of late one instance was updated to NC16 and now we have the same problem as the op.
Shares from 15.0.7 to 16.0 are working. Shares from 16.0 to 15.0.7 show an internal server error in the mobile app and the desktop client.
The web interface shows displays an error message: "the remote directory is not available" (translated from german).

**Comment by nicokaiser** [comment]
This may be related to #15211 and #15245. Don't know (yet) if this is a bug in NC 15.0.7 or 16.0.0.

**Comment by stefang84** [comment]
I also have problems with federated share. But for me it is now between two 16.0.0 (updated from 15).
When I set it up the share shows up in the notifications but accepting fails.
As far as I found it the share cannot be found as it seems to look for an entry in table share with share type 6 but in database it is share type 9.
So for I didn't have enoought time to go deep enough to find out where the 9 comes from.

**Comment by hcderaad** [comment]
I had similar issues, applying the following PR manually fixed it for me: https://github.com/nextcloud/server/pull/15385/files/471827cb3143fc55f4e280128dad063c9e876a59 also valid for #15245

**Comment by kesselb** [comment]
Thank you @hcderaad

**Comment by nicokaiser** [comment]
Can confirm #15385 fixed it for NC 16.0.0.
