### ISSUE TITLE
Comments: Replace CommentEntityEvent with a registration-bases solution within CommentsManager.

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#1539]
Currently, adding DAV support to other than 'files' type of comments, a dispatcher is being used to register a closure, which is handled by the comments RootCollection.

The CommentsManager should take this over and offer a possibility to register SubCollections as such. The RootCollection would query it let the corresponding instance continue.

The new API and switch from the Dispatcher shall be communicated with the release notes and possibly on Discourse.

As discussed with @nickvergessen while working at https://github.com/nextcloud/server/pull/1449

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by nickvergessen** [comment]
It not has those dedicated event. Sounds good enough for me atm. What do you think @blizzz

**Comment by blizzz** [comment]
if there is no need, we can just close it, instead of keeping it open eternally. can always reopen.

**Comment by nickvergessen** [comment]
PR at https://github.com/nextcloud/server/pull/39304 *cough*
