### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes Update failed

### ISSUE THREAD

**Issue by youzengwei** [nextcloud/server#15406]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Update failed

**Comment by Sebastian-Maier** [comment]
I had the same problem with my installation during Update to 16.0.0

**Comment by OlliZabal** [comment]
I'm having the same issue... ;(

**Comment by kesselb** [comment]
Thank you for reporting this issue :tada: 

See this issue for more information https://github.com/nextcloud/server/issues/15058

**Comment by OlliZabal** [comment]
> I'm having the same issue... ;(

I'm running on MySQL database and was able to solve the issue now for me.
I had set the following in the config: 'mysql.utf8mb4' => true,

So I removed this temporarily and the database updater went on without any issues. After that, the backend then will show some info and you will need to update some tables (what I did via ssh). After that I added again the 'mysql.utf8mb4' => true, in the config and all is fine!

Hope this helps for someone having the same issue...

**Comment by melo1** [comment]
same here - the config chnage didn't solve the problem.
Upgrade to 16.0.0 is not possible at the moment.
