### ISSUE TITLE
Integration with Protocol Infinote

### ISSUE THREAD

**Issue by valessiobrito** [nextcloud/server#15400]
I would like a support for the [Infinite protocol](https://www.infinote.org/), so I could use it to navigate the notes managed by [Gobby Desktop](https://github.com/gobby).

There is already a [LibJS: jinfinote](https://github.com/sveith/jinfinote
) that implements web support for this protocol. I imagine that for NextCloud it would be an integration feature for some existing note system or as "External Source"

This would be a solution as a free version for decentralized notes.

There is a demand from the [Gobby community to have a Web version](https://github.com/gobby/gobby/issues/9) to navigate the notes; I imagine it could be a joint effort. "Gobby support for NextCloud".

Thanks

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
