### ISSUE TITLE
last login column not showing correctly

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/server#15401]
### Steps to reproduce
1. click on users
2. click on settings
3. show last login

### Expected behaviour
correct column view of last login users

### Actual behaviour
column half under limit column
### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** NGINX

**Database:** Mariadb

**PHP version:** 7.3-FPM

**Nextcloud version:** 16.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** manual

![image](https://user-images.githubusercontent.com/3179748/57274053-2df7cd80-709a-11e9-8f34-14f2fd20acb3.png)

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/15246, fixed in https://github.com/nextcloud/server/pull/15301
