### ISSUE TITLE
NC16.0/17.0/18.0 local external storage sharing link disappeared automatically after some time

### ISSUE THREAD

**Issue by GammaPi** [nextcloud/server#15411]
Nextcloud Version 16.0.0

Steps to reproduce:
1.Mount a local folder using external files app
2.share one file in that folder
3. wait for 30 minutes
4.sharing link disappeared

Logs:
I can see multiple errors in logging app:
Could not find resource core/vendor/marked/marked.min.js to load

**Comment by GammaPi** [comment]
The problem seems to have no relation to "Could not find resource core/vendor/marked/marked.min.js to load" 

The sharing link removed immediately after a cron job is executed
cron_1   | crond: USER www-data pid   7 cmd php -f /var/www/html/cron.php

**Comment by GammaPi** [comment]
It's very strange because I've installed nextcloud for quite some time and the problem didn't shown till today.

**Comment by pauxus** [comment]
I am encountering the same issue with 15.0.7

**Comment by GammaPi** [comment]
> I am encountering the same issue with 15.0.7

Me too. I upgraded from 15.0.7 to 16.0 and the problem still exists.

**Comment by ddaumiller** [comment]
still happens on 18.0.0 for me

**Comment by kesselb** [comment]
I'm not able to reproduce. Still an issue?

**Comment by ddaumiller** [comment]
I have external storage (local on the host, mounted as volume into the docker container).
when creating a share link to a folder there, the link disappears after some few to 15 minutes. Hard to say when exactly. One moment I see a 200, the next it's a 404

To be sure to see the change, i had set up periodic check of the url uring curl and watch
`$ watch -n 5 curl https://.... `
But I'm not sure where I have to look (plus my log aggregation doesn't yet work so well either).

Any pointers?

**Comment by GammaPi** [comment]
17 also have such problem

**Comment by GammaPi** [comment]
@J0WI Could you add the 17-feedback,18-feedback tags? Because some user are encountering the same problem.

**Comment by GammaPi** [comment]
When the sharing link disappears, I refresh the page, and it shows file not found.
My external storage is "local storage backend".
Maybe in every cornjob local storage is "remounted" and share link related is cancelled because the share is unmounted? It's just my random guessing.
No logs available.

**Comment by GammaPi** [comment]
Problem seems fixed after upgrading to 18.0.3.

**Comment by ddaumiller** [comment]
In a quick check, it's still there on my system (18.0.3).
tried creating a link to a shared storage. After some time (<2min) the link stops working and also disappears from the shares overview.

**Comment by rwakcjr** [comment]
I am experiencing the same bug

Ubuntu 18.04.5 LTS
Docker version 20.10.0, build 7287ab3
image: nextcloud:20.0.4-fpm

I have a docker installation of Nextcloud, a NFS share mounted to: /mnt and added through External storages as Local storage.

Share links that are not from External storages paths work normally.

**Comment by LucaTNT** [comment]
Same bug here, docker install of Nextcloud 21 and a local directory (bind-mounted from Docker).
Files shared out of the share expire out of nowhere.
Their internal URL changes as well, and in the activity section I can see the sharing activity which now points to a non-existent directory (even though it is still there on disk, it just gets a different URL).

**Comment by rwakcjr** [comment]
> Same bug here, docker install of Nextcloud 21 and a local directory (bind-mounted from Docker).
> Files shared out of the share expire out of nowhere.
> Their internal URL changes as well, and in the activity section I can see the sharing activity which now points to a non-existent directory (even though it is still there on disk, it just gets a different URL).

I later found out, that you need to mount external storage to the same location in nextcloud cron container and then the links persisted.

**Comment by LucaTNT** [comment]
> I later found out, that you need to mount external storage to the same location in nextcloud cron container and then the links persisted.

That was it! Thanks for your help!
