### ISSUE TITLE
Chrome - Cannot edit sharing options - bug 

### ISSUE THREAD

**Issue by elievischel** [nextcloud/server#15419]
Hi all, I still have a problem while using chrome (Version 74.0.3729.131) on window. 
The sharing option next to a folder or document still not appear, however it works on firefox

any help ?

![image](https://user-images.githubusercontent.com/25434540/57314758-8eb2f480-70f2-11e9-9e13-dcce00a4bff3.png)

### Steps to reproduce
1. click on sharing button next to folder or file
2. select the user
3. want to change his right or stop the sharing of the folder

### Expected behaviour
Tell us what should happen

being able to see a box with all options as follow (screenshot from firefox)
![image](https://user-images.githubusercontent.com/25434540/57314906-d89bda80-70f2-11e9-88cf-eb586e866fd5.png)

### Actual behaviour
Tell us what happens instead

nothing shown

Looking forward to your help
Thanks

**Comment by kesselb** [comment]
Try to disable adblock for nextcloud.

**Comment by jeromeLB** [comment]
I had this issue with firefox, but works with chromium.
I disabled adBlockPlus plugin for Firefox, and it works now on firefox

**Comment by elievischel** [comment]
yes it's because of adblock, thanks for your help
