### ISSUE TITLE
Provide link to "What's new" before upgrading an app...

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#15435]
... like Wordpress is doing

![whats_new](https://user-images.githubusercontent.com/24833757/57349368-2566cc00-715a-11e9-96c9-8e906d301dcf.png)

**Comment by wiswedel** [comment]
This request seems to be better located at https://github.com/nextcloud/appstore/issues

**Comment by Sanookmakmak** [comment]
See https://github.com/nextcloud/appstore/issues/607
