### ISSUE TITLE
Unfocus of password input for share link should save password

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#15431]
### Steps to reproduce

1. Open Sharing UI for a folder
2. Click "Add Link Share"
3. Click "Add Password protection"
4. Enter a password
5. Leave the sharing UI. Normally all changes in Nextcloud are saved automatically when the input focus ist lost so the user can assume that it's the same with the password
6. Open sharing UI again to verify that the password is saved -> it looks like the password has been saved correctly
7. Only after reloading the page you can see that the password is lost (not saved).

### Expected behaviour
* password should be saved

Regression from NC 14. Reproducible in NC 15+

@nextcloud/javascript

**Comment by MorrisJobke** [comment]
> Iirc, this was removed on purpose, this is no mistake 🤔

On the other side there are some security implications if this is not clearly stated, that the unfocus does not save anymore. If people are used to this behavior they could get into trouble. Additionally we do not destroy the input on this close and it looks like the password is set properly when the user reopens the drop down menu.

**Comment by jancborchardt** [comment]
Tend to agree with @MorrisJobke here. Changes should be saved automatically.

(And yeah, adding a "Save" button doesn’t really fix this cause even then people might forget or not see the save button and be frustrated too.)

**Comment by skjnldsv** [comment]
Let's go for that then :)

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
