### ISSUE TITLE
Allow to add Mailaddress and Username to forgotten Password link.

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#15445]
See also discussed Idea: https://github.com/nextcloud/user_external/issues/60
(config.php in Dok: [https://docs.nextcloud/...](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=lost_password_link#default-config-php-examples)

![grafik](https://user-images.githubusercontent.com/7795891/57381092-933ae400-71aa-11e9-8545-c495b60e190a.png)

From this Entry detect the username and allow me to setup in config.php kind of:
`'lost_password_link' => 'https://example.org/link/to/password/reset.php?UID=$MAILADRESS&mail=$MAILADRESS&Username=$USERNAME',`

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
