### ISSUE TITLE
am I the only one having WebDAV problems?

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [nextcloud/server#15458]
Having my Calendar of Nextcloud synced via webDAV with my Android phone for month without problems. 
A few days ago (didnt change anything) Im getting error messages from my App, saying something like "illegal instruction from the server". I dont know if the problem is located in the app or on the server.

Does anyone else have these Problems too?

**Comment by j-ed** [comment]
To get this question answered, you should check the [**Nextcloud help forum**](https://help.nextcloud.com/)  first, which exists to answer these kind of questions. See e.g. https://help.nextcloud.com/search?q=webdav%20access

**Comment by acs-ferreira** [comment]
Please ask server related questions at https://help.nextcloud.com/
