### ISSUE TITLE
Stuck on step 6 : update nextcloud 15.0.6 to 15.0.7

### ISSUE THREAD

**Issue by vacichv** [nextcloud/server#15450]
### Steps to reproduce
1. Try to update nextcloud from 15.0.6 to 15.0.7 (stable) with graphical updater

### Expected behaviour
Normal update

### Actual behaviour
The update stop at step 6 (Verifying integrity) with error : "Parsing response failed.".
I have tried to launch the upgrade many times but that always stop at this step.
### Server configuration

**Operating system**:
Debian GNU/Linux 8

**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7.0

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```php
$CONFIG = array (
  'instanceid' => 'REALVALUE',
  'passwordsalt' => 'REALVALUE',
  'secret' => 'REALVALUE',
  'trusted_domains' => 
  array (
    0 => 'REALVALUE',
  ),
  'datadirectory' => '/home/REALVALUE/cloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.6.1',
  'overwrite.cli.url' => 'https://REALVALUE',
  'dbname' => 'REALVALUE',
  'dbhost' => 'REALVALUE',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'REALVALUE',
  'dbpassword' => 'REALVALUE',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpport' => '465',
  'mail_from_address' => 'REALVALUE',
  'mail_domain' => 'REALVALUE',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'REALVALUE',
  'mail_smtpname' => 'REALVALUE',
  'mail_smtppassword' => 'REALVALUE',
  'force_language' => 'fr',
  'maintenance' => false,
  'tempdirectory' => '/home/REALVALUE/cloud/tmp',
  'theme' => '',
  'loglevel' => 2,
  'updater.secret' => '$2y$10$8jsoidhuazeEh5X3U/5FL..kxwMK2aA9G2raiP0Wsn/1WovBdK1S6',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Firefox Quantum 66.0.5 
**Operating system:**
Windows 10

**Comment by vacichv** [comment]
Anybody have an idea please ?

**Comment by iamdoubz** [comment]
I don't have the "updater.secret" in my config.php file. So, comment that out and maybe try to add `'debug' => true,` to the file as well with help diagnose some errors.

**Comment by Grishnackh** [comment]
For me the solution was described in [this thread](https://help.nextcloud.com/t/upgrading-from-15-0-7-to-16-0-1-verifying-integrity-fails/53456/9). Set `php_value memory_limit 256M` in `.htaccess` file. Place the setting under the comment `#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####`. That should prevent it from getting overridden when updating.
