### ISSUE TITLE
Timestamps are not displayed in the preferred language

### ISSUE THREAD

**Issue by MeCias** [nextcloud/server#15457]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

Hi,

I first noticed this [issue](https://github.com/nextcloud/mail/issues/1232) with the email app and just today that the [contacts app](https://github.com/nextcloud/contacts/issues/1096) and the file app show the same behavior.

![screenshot](https://user-images.githubusercontent.com/4476171/57431959-b8743480-7234-11e9-96ca-66fd7d2291f8.jpg)

The timestamps within Nextcloud are displayed in German even if my preferred language is English.

![screenshot](https://user-images.githubusercontent.com/4476171/57431998-d772c680-7234-11e9-8eff-6d3ce68f297d.jpg)

I am using NC 16.0 and all apps up to date (mail 0.14.0, contacts 3.1.1)

**Comment by MeCias** [comment]
I just got informed that nickvergessen already works on that [issue](https://github.com/nextcloud/server/pull/14784).
Thank you.

**Comment by mrbenjoi** [comment]
Some people are experiencing similar issues in the calendar app. The date in the week view is shown in the locale of the language instead of the one for date and time formats. This is very annoying and can even lead to date confusions at the beginning of the year is language is set to en-US and date and time to en-UK, because they have date and month swapped.

The issue can be found here: [nextcloud/calendar#2777](https://github.com/nextcloud/calendar/issues/2777)

The work started by @nickvergessen seems to be stale. Is it possible to reopen and restart the work on that problem?

**Comment by Daksol** [comment]
Having worked this sort of issue elsewhere, can I suggest that there be an "unconfusable" default option for the date format - else changing the format will confuse either Americans or Europeans. And many organisations are international, so you don't always know your audience in detail.
So idea is to use a default format which cannot be mistaken
Example would be for the first of August 2022
* ISO-8601 - yyyy-mm-dd  (2021-08-01)
* with three letter month, dd-mmm-yyyy   01-Aug-2021

**Comment by MeCias** [comment]
Hi,
I am on 25.0.2, the language in English and the locale is German as initial posted and I see the same as mentioned four years ago.

![Screenshot_20230109_174148](https://user-images.githubusercontent.com/4476171/211361861-f85dddca-2637-4759-9712-1cda86323b45.png)

**Comment by chenasraf** [comment]
Also have the same issue, on v25.0.3
![image](https://user-images.githubusercontent.com/167217/216038881-09b7b16e-5879-4b61-bd7f-592a84b6455a.png)

**Comment by AlexLJordan** [comment]
> Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

I'm on 25.0.4 observing the same issue that ghost described above in calendar as well what MeCias and chenasraf above me are seeing in the file browser.
