### ISSUE TITLE
Web Updater: Das Datenbankschema wird aktualisiert  InvalidArgumentException: Primary index name on "nc_7325_collres_collections" is too long.

### ISSUE THREAD

**Issue by tho-wa** [nextcloud/server#15463]
Aktualisierung auf 16.0.0

InvalidArgumentException: Primary index name on "nc_7325_collres_collections" is too long.
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

InvalidArgumentException: Primary index name on "nc_7325_collres_collections" is too long.

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/15229

**Comment by tho-wa** [comment]
Is there any fix available?

**Comment by kesselb** [comment]
> Is there any fix available?

A proper fix will be part of Nextcloud 16.0.1. In the meantime you can apply the patch from https://github.com/nextcloud/server/pull/15289/files

**Comment by tho-wa** [comment]
Thanks.
