### ISSUE TITLE
Potential issue - S3 External Storage Error: fclose(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by mlshapiro** [nextcloud/server#15486]
### Steps to reproduce
1. Enable S3 External storage with default options, except:
  - Disable default option "Enable Encryption"
  - NOTE: I am using an S3 compliant API (wasabi) not an actual S3 bucket
2. Add file to the external storage directory either from the desktop app or the browser client

### Expected behaviour

The file should be added to the bucket in the external storage without issues.

### Actual behaviour

The file is added successfully to the bucket and syncs correctly. While the file is added, it throws a log message:

```
Error    PHP    fclose(): supplied resource is not a valid stream resource at /snap/nextcloud/13144/htdocs/apps/files_external/lib/Lib/Storage/AmazonS3.php#641
```

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4

**Database:** MySQL 5.7, Redis 4.0

**PHP version:** PHP 7.2

**Nextcloud version:** 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** [nextcloud-snap](https://github.com/nextcloud/nextcloud-snap)

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

No extra configuration beyond snap defaults.

</details>

**Are you using external storage, if yes which one:** yes, Wasabi (via Amazon S3 API) 

**Are you using encryption:** yes for the local server. No for the external storage

**Are you using an external user-backend, if yes which one:** No

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Not accessible
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Error | PHP | fclose():  supplied resource is not a valid stream resource at  /snap/nextcloud/13144/htdocs/apps/files_external/lib/Lib/Storage/AmazonS3.php#641
-- | -- | --
```
</details>

**Comment by baskraai** [comment]
Have the same issue with a full Amazon S3 backed Nextcloud instance running 16.0.0. It's running inside the official Docker container from Nextcloud. Files have size 0 when uploaded through the web interface. When uploaded through the client the file shows up with the right size and readable from other devices and the web interface. (Tested with text file and foto PNG)

**Comment by craysiii** [comment]
Also experiencing the same issue. Wasabi backend. Windows client. Running NC 16 installed manually.

**Comment by beanaroo** [comment]
Experiencing the same issue on NC 16 with S3 bucket added as external storage

**Comment by neomed** [comment]
Experiencing the same issue on NC 16.0.2 with S3 bucket added as external storage

**Comment by goldo** [comment]
same issue with same v16 inside a docker with a wasabi/s3 sotage

**Comment by kesselb** [comment]
Could be a regression from https://github.com/nextcloud/server/pull/14210

https://github.com/nextcloud/server/blob/0d667d18bb9d76e8ffad48b270545dde76fc156e/apps/files_external/lib/Lib/Storage/AmazonS3.php#L639-L641

Starting with the referenced pull request the stream is closed in `writeObject`.


```
Index: apps/files_external/lib/Lib/Storage/AmazonS3.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/files_external/lib/Lib/Storage/AmazonS3.php	(revision 7b8ddd7e958bfbf7dbddf38aca2c789310e3d1a4)
+++ apps/files_external/lib/Lib/Storage/AmazonS3.php	(date 1565546526475)
@@ -638,7 +638,6 @@
 			$source = fopen($tmpFile, 'r');
 			$this->writeObject($path, $source);
 			$this->invalidateCache($path);
-			fclose($source);
 
 			unlink($tmpFile);
 			return true;
```

A) Remove `fclose($source)` or B) `feof` before `fclose($source)` 

cc @rullzer @icewind1991

**Comment by jasonkuehl** [comment]
Seeing this as well with  16.0.3

**Comment by acsfer** [comment]
Observing the same beahviour on 19.0.3 @kesselb 

`"fclose(): supplied resource is not a valid stream resource at /lib/private/Files/ObjectStore/S3ObjectTrait.php#107"`

**Comment by kesselb** [comment]
Please create a new issue.
