### ISSUE TITLE
"X" display of the loading bar

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#15481]
### Steps to reproduce
1. Choose "All files" from the menu.
2. Choose "Deleted files" from the menu.
3. Again choose "All files" from the menu.

### Actual behavior
"X" display of the loading bar.
![obraz](https://user-images.githubusercontent.com/47037905/57456754-6c45e600-726e-11e9-9589-8fd191bb3b7f.png)

### Expected behavior 
The cancel uploading button (X display) should be shown only when something is uploading. 

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
16.0.0

### Client configuration
**Browser:**
Firefox 66.0.5
Opera 58.0.3135.132

**Operating system:**
Win10

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/nextcloud/server/issues/16137 which is newer but is already linked in some places. :)
