### ISSUE TITLE
S3 primary storage sharing option not available

### ISSUE THREAD

**Issue by s4n4s** [nextcloud/server#15492]
**Steps to reproduce**

Setup S3 as a primary storage in config.php

```
'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\S3',
    'arguments' =>
    array (
      'bucket' => 'bkt-toc-test-nextcloud',
      'autocreate' => true,
      'key' => 'Hided',
      'secret' => 'Hided',
      'hostname' => 'Hided',
      'port' => Hided,
      'use_ssl' => false,
      'region' => 'eu-west-1',
      'use_path_style' => true,
    ),
```

**Expected behaviour**

Should be abale to share files and folders

**Actual behaviour**

Can't share files and folders because the option are not available.

<a href="https://www.noelshack.com/2019-19-5-1557486702-capture.png"><img src="https://image.noelshack.com/minis/2019/19/5/1557486702-capture.png" border="0" alt="1557486702-capture.png - envoi d'image avec NoelShack" title="1557486702-capture.png"/></a>

**Server configuration**

**Operating system**: Red Hat Enterprise Linux Server release 7.5 

**Web server:** Apache

**Database:** MySql Ver 8.0.15 for Linux on x86_64 

**PHP version:**  7.3.3 

**Nextcloud version:** 15.0.5.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:**  Nextcloud officiel website - zip file

**Signing status:**
No errors have been found.

**Are you using external storage, if yes which one:** Yes, S3

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Active Directory

**Browser:** Firefox

**Operating system:** Windows 10
**Logs**

Log file is too big to attach here

**Comment by s4n4s** [comment]
Fixed with upgrade to the laste version of nextcloud. 16.0.0

**Comment by dwehrmann** [comment]
I am also seeing this on Nextcloud 17 with S3 primary storage. Only the user who creates a file can share even though they are in the same group and the file has been shared by the owner. Person 2 cannot re-share.
