### ISSUE TITLE
Obsolete table: authtoken?

### ISSUE THREAD

**Issue by nblock** [nextcloud/server#155]
I am using ownCloud/Nextcloud since 3.0 and have updated the instance from this version up until Nextcloud 9.0.50. I now want to migrate from SQLite to PostgreSQL and want to get rid of old tables before the actual migration.

### Steps to reproduce
1. Upgrade to Nextcloud 9.0.50
2. Find a list of tables that are part of the migrated instance but not part of core/server + bundled apps + active 3rdparty apps

### Expected behaviour
No diff between the two list.

### Actual behaviour
Found oc_authtoken to be present.

A quick grep revealed the following:
8b01286a5d14bae90607d5192c89b5f9d72d8bc2 removes the table (2012)
d8cde414bd13c327ec2edaf1ae38380073c93e3e adds the table again (2016, part of 9.1)

I assume that this old table should be removed before upgrading to 9.1, is this assumption correct?

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @LukasReschke

**Comment by MorrisJobke** [comment]
Fix is in #192

**Comment by MorrisJobke** [comment]
@nblock Thanks for noticing
