### ISSUE TITLE
It would be nice to be able to specify a custom external page to redirect to upon logout.

### ISSUE THREAD

**Issue by 4nanook** [nextcloud/server#15503]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by wiswedel** [comment]
Your headline is quite clear but please get into some detail including your motivation. There are only placeholder texts up here.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since over 2 years. Please reopen if you still want to implement this.
