### ISSUE TITLE
Allow editing of public share(s) link label(s) in WebUI

### ISSUE THREAD

**Issue by lopezio** [nextcloud/server#15500]
**Is your feature request related to a problem? Please describe.**
Related to (possibly in order of importance):  #12178, #11844. #11169: 

The new label field for public share links has been implemented in API and backend, and while definitively not a use case for most of us, there are several use cases (otherwise: why was it implemented in the first place..?). But I can't find a way (as of 16.0.0) to edit the labels in the webUI (unless I run into an upgrade / cache problem and the link is not shown for some reason).

**Describe the solution you'd like**

.. two simple ideas (not looking at the code - just at the UI.. ;)) come to mind:

1) add a pencil button near to the public share when at least one is made (or, even better, when at least 2 public links are made), something like this..:

![nc_edit_in_place](https://user-images.githubusercontent.com/1156208/57529677-c5c51800-7335-11e9-95e5-c5e5a302cb00.jpg)

2) or otherwise just add a menu item such as the one used for the note..:

![nc_edit_label](https://user-images.githubusercontent.com/1156208/57529695-d4abca80-7335-11e9-9892-72919d013d50.jpg)

Just a few ideas.. I love the new functionality, but without being able to change it in the webui, really, what's the use of it.

**Additional context**
I have upgraded my nextcloud coming from 15.0.7 and am running 16.0.0.

Thanks for reading. Best Regards.

**Comment by wiswedel** [comment]
@schiessle any update on this?

**Comment by wiswedel** [comment]
@skjnldsv Maybe something for https://github.com/orgs/nextcloud/projects/32 ? Groundwork is already done in https://github.com/nextcloud/server/pull/11844.

**Comment by alexbijma** [comment]
just curious, is this added to nextcloud 19 version? Because it's on the "leave for now" column? https://github.com/orgs/nextcloud/projects/32

**Comment by skjnldsv** [comment]
No it is not

**Comment by alexbijma** [comment]
that's sad. i got asked by a couple of customers about this. what's the expectation? will you try to add it onto the next version again or will it may'be added after all?

**Comment by jospoortvliet** [comment]
> that's sad. i got asked by a couple of customers about this. what's the expectation? will you try to add it onto the next version again or will it may'be added after all?

Hi Alex - we know about the request and we'll get there at some point... If any of your customers or prospects are quite big and there's a need to make them happy, perhaps discuss it with Markus - I think he's your account manager - we could maybe speed up a feature like this. At the moment, due to the Corona thing, 19 is pretty full already hence it getting delayed.  But if there's a lot of interest - talk to Markus.

**Comment by wiswedel** [comment]
closed by https://github.com/nextcloud/server/pull/21357
