### ISSUE TITLE
Data of deleted user still there

### ISSUE THREAD

**Issue by meras1894** [nextcloud/server#1551]
### Steps to reproduce
1. Delete User via Admin-Panel
2. Create same User again via Admin Panel
3. Login at User account, loading Contacts App

### Expected behaviour
New user, there should not be any datas from the deleted user

### Actual behaviour
- Data from database (contacts) is still there
- Also, nextcloud asked for two factor auth for the new user. Two factor auth was activated at the deleted user. After disabling two factor auth, I could login.

### Server configuration
**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** 10.0.27-MariaDB

**PHP version:** PHP 7.0.8

**Nextcloud version:** 10.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** download from web

**Signing status:**
No errors have been found.

**List of activated apps:**
standard list
+
contacts
calendar
two factor auth 
mail
tasks

**The content of config/config.php:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'instanceid' => 'ocr3jwxw0325',
  'passwordsalt' => '....',
  'secret' => '....',
  'trusted_domains' => 
  array (
    0 => 'example.eu:444',
  ),
  'datadirectory' => '/mnt/nfs/webserver_daten/nextcloud_data',
  'overwrite.cli.url' => 'https://example.eu:444',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '.....',
  'logtimezone' => 'UTC',
  'installed' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'hosts' => 'localhost',
    'port' => 6379,
  ),
  'appstore.experimental.enabled' => false,
);
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 49.0.1

**Operating system:** Windows 10

No errors in logs

**Comment by nickvergessen** [comment]
Fix is at https://github.com/nextcloud/server/pull/1545

**Comment by meras1894** [comment]
Thx!

**Comment by meras1894** [comment]
Just forgot about the second issue with the two factor auth.

"Also, nextcloud asked for two factor auth for the new user. Two factor auth was activated at the deleted user. After disabling two factor auth, I could login."

Is this fixed with #1545 as well?

**Comment by nickvergessen** [comment]
The backup codes are not deleted, I reported that in https://github.com/nextcloud/server/issues/1557
Other then that 2FA is always enabled for all users by default.

**Comment by meras1894** [comment]
I use the following 

https://apps.owncloud.com/content/show.php/TOTP+TwoFactor+(Google+Authenticator)?content=174726
