### ISSUE TITLE
Option to disable sending passwords for mail shares with password protection

### ISSUE THREAD

**Issue by CamZie** [nextcloud/server#15515]
When files are shared to an email address with password protection, a mail will be automatically sent to the email with the share's password in clear text.

Unfortunately, there is currently no option to disable this feature for security reasons.

It would be better if there is an option where we can choose if we want the password to be sent via mail or not. Like maybe a confirmation "Send the password per email?" with yes or no as an option. Or like a check box in the Sharing settings, where we can enable/disable this feature.

**Comment by wiswedel** [comment]
Actually, that very feature has been there ever since, or am I missing something?

![image](https://user-images.githubusercontent.com/1804221/57634184-168e7800-75a5-11e9-9b3c-ef72345e3007.png)

**Comment by CamZie** [comment]
@wiswedel Thank you very much for the helpful answer!

Just a suggestion: since this setting is set globally by the admin, it would be better if the users can also decide if they want this option enabled or not.

**Comment by wiswedel** [comment]
> it would be better if the users can also decide if they want this option enabled or not.

@CamZie I'm closing this issue then. Please open another one if you want to pursuit the feature request. Thanks.
