### ISSUE TITLE
Can anyone explain why the “upload and memory setting” has been removed?

### ISSUE THREAD

**Issue by MAT-WEISS-2017** [nextcloud/server#15512]
[See it on git…](https://github.com/nextcloud/server/commit/c6a69ba92514587814d0f03b51e1d1f026a4935)

I did the update to version 16 today.
Unfortunately, I can no longer set the “Maximum upload size”.
The point is simply no longer available in the WebUi for me.

Manually setting the parameters in the “.user.ini”
upload_max_filesize=50M
post_max_size=50M

or

php_value upload_max_filesize 50M
php_value post_max_size 50M
in the “.htaccess”

did not help either.

No errors in the log but also no upload-limit :flushed:

**Comment by wiswedel** [comment]
see https://github.com/nextcloud/server/pull/14430#issue-257004536
