### ISSUE TITLE
Webdav error : "Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable" with "Error: Call to a member function instanceOfStorage() on null"

### ISSUE THREAD

**Issue by dlm73** [nextcloud/server#15519]
Some users have noticed that the Nextcloud client displays a message "Server xxx is temporarily unavailable. 
Some PROPFIND requests are returning the 503 error code in the Apache logfile
There are errors in the Nextcloud logfile : "Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Error: Call to a member function instanceOfStorage() on null"

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Postgresql 9.5

**PHP version:** 7.0.33-0ubuntu0.16.04.4

**Nextcloud version:** (see Nextcloud admin page) 15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older nextcloud/owncloud versions

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
root@cloud:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "version": "15.0.7.0",
        "installed": true,
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shares",
        "loglevel": "2",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto,15",
        "activity_expire_days": 30,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updatechecker": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "production"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+----------------------------------------------------------------+
| Configuration                 |                                                                |
+-------------------------------+----------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                              |
| homeFolderNamingRule          |                                                                |
| lastJpegPhotoLookup           | 0                                                              |
| ldapAgentName                 | *** sensitive parameters replaced ***        |
| ldapAgentPassword             | ***                                                            |
| ldapAttributesForGroupSearch  |                                                                |
| ldapAttributesForUserSearch   | uid;displayName;mail;cn;sn;givenName;gecos;description         |
| ldapBackupHost                |                                                                |
| ldapBackupPort                |                                                                |
| ldapBase                      | dc=company,dc=com                                           |
| ldapBaseGroups                | ou=groups,dc=company,dc=com                                 |
| ldapBaseUsers                 | dc=company,dc=com                                           |
| ldapCacheTTL                  | 600                                                            |
| ldapConfigurationActive       | 1                                                              |
| ldapDefaultPPolicyDN          |                                                                |
| ldapDynamicGroupMemberURL     |                                                                |
| ldapEmailAttribute            | mail                                                           |
| ldapExperiencedAdmin          | 1                                                              |
| ldapExpertUUIDGroupAttr       | entrydn                                                        |
| ldapExpertUUIDUserAttr        | uid                                                            |
| ldapExpertUsernameAttr        |                                                                |
| ldapGidNumber                 | gidNumber                                                      |
| ldapGroupDisplayName          | cn                                                             |
| ldapGroupFilter               | (objectClass=posixGroup)                                       |
| ldapGroupFilterGroups         |                                                                |
| ldapGroupFilterMode           | 1                                                              |
| ldapGroupFilterObjectclass    |                                                                |
| ldapGroupMemberAssocAttr      | member                                                         |
| ldapHost                      | ldaps://ldap.company.com                                |
| ldapIgnoreNamingRules         |                                                                |
| ldapLoginFilter               | uid=%uid                                                       |
| ldapLoginFilterAttributes     |                                                                |
| ldapLoginFilterEmail          | 0                                                              |
| ldapLoginFilterMode           | 1                                                              |
| ldapLoginFilterUsername       | 1                                                              |
| ldapNestedGroups              | 0                                                              |
| ldapOverrideMainServer        | 0                                                              |
| ldapPagingSize                | 500                                                            |
| ldapPort                      | 636                                                            |
| ldapQuotaAttribute            |                                                                |
| ldapQuotaDefault              |                                                                |
| ldapTLS                       | 0                                                              |
| ldapUserAvatarRule            | default                                                        |
| ldapUserDisplayName           | displayname                                                    |
| ldapUserDisplayName2          |                                                                |
| ldapUserFilter                | (&(mail=*)(|(gidNumber=900)(gidNumber=1019)(gidNumber=20481))) |
| ldapUserFilterGroups          |                                                                |
| ldapUserFilterMode            | 1                                                              |
| ldapUserFilterObjectclass     |                                                                |
| ldapUuidGroupAttribute        | auto                                                           |
| ldapUuidUserAttribute         | auto                                                           |
| turnOffCertCheck              | 0                                                              |
| turnOnPasswordChange          | 0                                                              |
| useMemberOfToDetectMembership | 1                                                              |
+-------------------------------+----------------------------------------------------------------+
</details>

### Client configuration
**Browser:**
Nextcloud client desktop

**Operating system:**
Windows
#### Web server error log
<details>
<summary>Web server error log</summary>
xx.xx.xx.xx - xxxx[13/May/2019:18:43:33 +0200] "PROPFIND /remote.php/dav/files/8c8ecc5a-ede4-1031-822c-210182a5eb60/ HTTP/1.1" 503 945 "-" "Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)"
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"4M40TTPB17oX2JkNYQz3","level":4,"time":"2019-05-13T16:43:33+00:00","remoteAddr":"xx.xx.xx.xx","user":"8c8ecc5a-ede4-1031-822c-210182a5eb60","app":"webdav","method":"PROPFIND","url":"\/remote.php\/dav\/files\/8c8ecc5a-ede4-1031-822c-210182a5eb60\/","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"Error: Call to a member function instanceOfStorage() on null","Code":0,"Trace":[{"function":"{closure}","args":["*** sensitive parameters replaced ***"]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[{"__class__":"Closure"},["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":466,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["beforeMethod",["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"\/var\/www\/nextcloud\/remote.php","line":72,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":168,"function":"handleException","args":[{"__class__":"Error"}]}],"File":"\/var\/www\/nextcloud\/remote.php","Line":70,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows) mirall\/2.3.3 (build 1) (Nextcloud)","version":"15.0.7.0"}
</details>

**Comment by dlm73** [comment]
In fact, this error is caused by another one : 
{"reqId":"hzG7T6c9lWSsOKN5N4tX","level":3,"time":"2019-05-13T19:35:49+00:00","remoteAddr":"10.11.14.195","user":"57a0d040-b1ae-1037-9d79-9f70029bc533","app":"no app in context","method":"PROPFIND","url":"/remote.php/webdav/","message":{"Exception":"OC\\User\\NoUserException","Message":"a80bbef8-3697-1035-8374-730ecbca6404 is not a valid user anymore (deletion)","Code":0,"Trace":[{"function":"getHome","class":"OCA\\User_LDAP\\User_LDAP","type":"->","args":["a80bbef8-3697-1035-8374-730ecbca6404"]},{"file":"/var/www/nextcloud/apps/user_ldap/lib/User_Proxy.php","line":108,"function":"call_user_func_array","args":[[{"__class__":"OCA\\User_LDAP\\User_LDAP"},"getHome"],["a80bbef8-3697-1035-8374-730ecbca6404"]]},{"file":"/var/www/nextcloud/apps/user_ldap/lib/Proxy.php","line":150,"function":"callOnLastSeenOn","class":"OCA\\User_LDAP\\User_Proxy","type":"->","args":["a80bbef8-3697-1035-8374-730ecbca6404","getHome",["a80bbef8-3697-1035-8374-730ecbca6404"],false]},{"file":"/var/www/nextcloud/apps/user_ldap/lib/User_Proxy.php","line":227,"function":"handleRequest","class":"OCA\\User_LDAP\\Proxy","type":"->","args":["a80bbef8-3697-1035-8374-730ecbca6404","getHome",["a80bbef8-3697-1035-8374-730ecbca6404"]]},{"file":"/var/www/nextcloud/lib/private/User/User.php","line":282,"function":"getHome","class":"OCA\\User_LDAP\\User_Proxy","type":"->","args":["a80bbef8-3697-1035-8374-730ecbca6404"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Home.php","line":53,"function":"getHome","class":"OC\\User\\User","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Files/Mount/MountPoint.php","line":147,"function":"__construct","class":"OC\\Files\\Storage\\Home","type":"->","args":[{"user":{"__class__":"OC\\User\\User"}}]},{"file":"/var/www/nextcloud/lib/private/Files/Mount/MountPoint.php","line":172,"function":"createStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":321,"function":"getStorage","class":"OC\\Files\\Mount\\MountPoint","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":443,"function":"getStorage","class":"OC\\Files\\Filesystem","type":"::","args":["a80bbef8-3697-1035-8374-730ecbca6404"]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php","line":127,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::","args":["a80bbef8-3697-1035-8374-730ecbca6404"]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php","line":482,"function":"init","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Jail.php","line":220,"function":"getWrapperStorage","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/SharedStorage.php","line":199,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Jail","type":"->","args":[""]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":215,"function":"getPermissions","class":"OCA\\Files_Sharing\\SharedStorage","type":"->","args":[""]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Cache.php","line":148,"function":"getPermissions","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[""]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Cache.php","line":114,"function":"formatCacheEntry","class":"OCA\\Files_Sharing\\Cache","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"},""]},{"file":"/var/www/nextcloud/lib/private/Files/FileInfo.php","line":359,"function":"get","class":"OCA\\Files_Sharing\\Cache","type":"->","args":[""]},{"file":"/var/www/nextcloud/lib/private/Files/FileInfo.php","line":206,"function":"updateEntryfromSubMounts","class":"OC\\Files\\FileInfo","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Node/Node.php","line":189,"function":"getMTime","class":"OC\\Files\\FileInfo","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Node.php","line":158,"function":"getMTime","class":"OC\\Files\\Node\\Node","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":790,"function":"getLastModified","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":98,"function":"Sabre\\DAV\\{closure}","class":"Sabre\\DAV\\CorePlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":794,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{DAV:}getlastmodified",{"__class__":"Closure"}]},{"function":"propFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"propFind"],[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1059,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":981,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\DAV\\Connector\\Sabre\\Directory"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["",["{DAV:}getlastmodified"],0]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.company.com/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https://cloud.company.com/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https://cloud.company.com/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.company.com/remote.php/webdav/","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":163,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/user_ldap/lib/User_LDAP.php","Line":437,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/2.3.3 (build 1) (Nextcloud)","version":"15.0.7.0","id":"5cd9c787b0d64"}

**Comment by skjnldsv** [comment]
@blizzz :)

**Comment by blizzz** [comment]
Hm, this look familiar… does it also happen on a current Nc release? Might have been fixed inbetween.
