### ISSUE TITLE
Do OPcache recommendations based on actual cache usage

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#15522]
**Is your feature request related to a problem? Please describe.**
- Currently OPcache settings (`opcache.memory_consumption`, `opcache.interned_strings_buffer`, `opcache.max_accelerated_files`) recommendations on Nextcloud admin panel are fixed values that match the current PHP defaults: https://php.net/manual/en/opcache.configuration.php
- For Nextcloud-only servers, based on tests with all available apps installed, those are never reached and could be halved.
- If other large PHP sites are present, those could be too low.

**Describe the solution you'd like**
- It makes sense to prompt recommendations for each setting separately, based on the actual OPcache usage.
- The [opcache_get_status()](https://www.php.net/manual/en/function.opcache-get-status.php) function could be used for this. It could then be recommended to raise a value if e.g. more than 80% of the limit is reached.

**Describe alternatives you've considered**
- Having failsafe high recommendations (current implementation) does not hurt much either, especially since there seems to be no negative performance impact when having "too" high values.
- The main benefit of the requested change is then that most users (with default OPcache values active) will not face any warning while in rare cases, where higher values are required, those are covered by the warning(s) as well. Also shared hosting users, that have no access to the PHP settings, will not be bothered by the warnings, or, can do requests to their hosting provider based on a real measure.

**Additional context**
Related discussion has been done here: https://github.com/nextcloud/documentation/issues/1439

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by MichaIng** [comment]
I opened a PR to address this: #27403
Own tests and polishing will be done tomorrow. I leave this issue as closed regardless, discussions can be done in the PR.
