### ISSUE TITLE
File Hook on volume level

### ISSUE THREAD

**Issue by codepushr** [nextcloud/server#15528]
Dear Nextcloud team,

please feel free to immediately close this issue. I'm here to ask if the File Hooks are also triggered if there is an activity on the file system level, OR only if files are created/moved inside the Nextcloud web interface.

I'm currently building an app that uses post_create hooks to send stats to an ouside integration and currently my Hooks are only triggered if I drag&drop files into the web interface, but never if I move the file into the data folder directly.

I didn't find any documentation regarding the scope of File Hooks.

Thanks

**Comment by rullzer** [comment]
This is indeed similar to https://github.com/nextcloud/server/issues/15530
