### ISSUE TITLE
settings: no error dialog on web UI when saving settings fails

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#15527]
### Steps to reproduce
1. On the settings page (`/settings/user`), configure an invalid email address (e.g. `test`)

### Expected behaviour
An error message should be shown on the web UI.

### Actual behaviour
`PUT /settings/users/admin/settings` returns an error `{"status":"error","data":{"message":"Invalid mail address"}}` but no error message is shown.

### Server configuration
Latest master (`c41aa7a20929118ce1092c603f709d06aef1da57`) without additional apps and only a single user which has just been set up.

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
