### ISSUE TITLE
Minor typo in web admin pop-up after upgrade to v16

### ISSUE THREAD

**Issue by mrdaftpunk** [nextcloud/server#15534]
After upgrading to v16, the web admin had a pop-up in the lower left-hand corner with a small typo in the first 'bullet point':

![ncloud typo](https://user-images.githubusercontent.com/34904824/57720014-e3b5b400-7678-11e9-944c-6c9da3bb54ae.PNG)

"Smart recommendations for files, sharees"

Recommend editing to read "shares".

Thanks

**Comment by skjnldsv** [comment]
> Recommend editing to read "shares".

No, this is sharees. We're talking about share recipients :)
