### ISSUE TITLE
As soon as utf8mb4 is enabled adding a new user is broken

### ISSUE THREAD

**Issue by MeCias** [nextcloud/server#15535]
Hi,

I did a fresh install of NC 16 and it works so far. I did enable right from the start utf8mb4 in the config.php and tried to create new user. I am able to create the new user but those disappear with an error message on top and an error message in the log. The names that I used had no special characters or any funny symbols just simple names.

![Capture](https://user-images.githubusercontent.com/4476171/57723829-c76e4300-7689-11e9-8681-8c990d904726.JPG)

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` `u` LEFT JOIN `oc_preferences` `p` ON (`userid` = `uid`) AND (`appid` = 'settings') AND (`configkey` = 'email') WHERE (`uid` COLLATE utf8mb4_general_ci LIKE ?) OR (`displayname` COLLATE utf8mb4_general_ci LIKE ?) OR (`configvalue` COLLATE utf8mb4_general_ci LIKE ?) ORDER BY `uid_lower` ASC LIMIT 25 OFFSET 0' with params ["%%", "%%", "%%"]: SQLSTATE[42000]: Syntax error or access violation: 1253 COLLATION 'utf8mb4_general_ci' is not valid for CHARACTER SET 'utf8'

As soon I switch utf8mb4 to false it works all as expected.

**Comment by rotational467** [comment]
I can reproduce this exactly on a fresh install of 16.0.1.1 + mariadb 10.1 + php7.2 + apache on a new Ubuntu 18.04 EC2 instance.

**Comment by MeCias** [comment]
The first part is clear, just struggle with the second error since I am just on a hosted environment and do not have full access.

**Comment by kesselb** [comment]
> The first part is clear, just struggle with the second error since I am just on a hosted environment and do not have full access.

If your database server is not configured for utf8mb4 don't enable it ;) Here are some details: https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by MeCias** [comment]
Probably not. Thanks though.
