### ISSUE TITLE
Docker on Mac doesn't sync data folder contents to web interface

### ISSUE THREAD

**Issue by codepushr** [nextcloud/server#15530]
### Steps to reproduce
1. Start Docker Image with mounted data volume (/var/www/html)
2. Place file via Finder into data folder
3. Check in Web Interface for newly added file

### Expected behaviour
File should appear in the Web Interface

### Actual behaviour
File never appears

### Server configuration

**Operating system**:
macOS 10.13.6

**Web server:**
See Docker Image

**Database:**
MariaDB

**PHP version:**
See Docker Image

**Nextcloud version:** (see Nextcloud admin page)
15

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Docker Image

**Where did you install Nextcloud from:**
Docker

**Comment by rullzer** [comment]
That si now how nextcloud works.
You need to scan your files via occ then.

But in general all data should pass trough Nextcloud when written or read.

**Comment by codepushr** [comment]
@rullzer Does this also apply to this quesion? #15528
