### ISSUE TITLE
NC 15.0.7: check all tables for Barracuda format BEFORE updating to 16.0.0 

### ISSUE THREAD

**Issue by Sanookmakmak** [nextcloud/server#15549]
![nc_update_fehlgeschlagen](https://user-images.githubusercontent.com/24833757/57781914-71ea7280-772b-11e9-8b8b-f43d29a92215.png)

https://help.nextcloud.com/t/update-von-15-0-7-auf-16-0-0-funktioniert-nicht-1071-specified-key-was-too-long-max-key-length-is-767-bytes/53340

**Comment by berdosi** [comment]
If anyone else founds this thread just looking for a quick solution:
1. set the below values in your database's config file:
```INI
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=1
```
2. restart the database server

My issue was that these values were set in the wrong config file.

**Comment by Sanookmakmak** [comment]
But in the admin settings of the Nextcloud UI the MySQL 4-byte check was succesful BEFORE updating to NC 16.0.0.

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.
