### ISSUE TITLE
File icon not tinted

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#15541]
- have theming enabled
- set it to different color
- share a file via link
- open this link
- see file icon not tinted
- file icons in file list (when logged in) is tinted

![image](https://user-images.githubusercontent.com/5836855/57761369-a8a99400-76fd-11e9-8a68-1eb461863f97.png)

**Comment by skjnldsv** [comment]
@marcelklehr this kind of stuff would be perfect for the Icon component ;)

**Comment by marcelklehr** [comment]
yep

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by tobiasKaminsky** [comment]
Working now.
