### ISSUE TITLE
Unable to set quota for users if root path for users is on external storage

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#15558]
Hello,

If I set the root path for a user onto external storage, I am not able to set a quota for that user. Because if I set it up and reload the page it gets back to its default value: umlimited.
But if I remove the root path from external storage back to default for that user, I am afterwards able to set a quota permanently.

I think that is a bug and should get fixed.

My Setup is currently a Nextcloud-Snap (15.0.7) on Ubuntu 18.04 LTS if that is important.

**Comment by CSchank** [comment]
Out of curiosity, how are you setting the root path per-user? I was never able to figure it out.

**Comment by wiswedel** [comment]
>Out of curiosity, how are you setting the root path per-user? I was never able to figure it out. 

@CSchank just name the storage **/**

**Comment by CSchank** [comment]
Ah, so you create one external storage per user, name them all `/` and then assign the permission to that user to use it?

**Comment by CSchank** [comment]
@wiswedel Ah, so you create one external storage per user, name them all `/` and then assign the permission to that user to use it? I feel like this should be built into NC/OC itself.

**Comment by wiswedel** [comment]
> I feel like this should be made to be built into NC/OC itself.

@CSchank  What exactly should be built in? You can do three things, all _are_ built in:

1. Every user has their own root directory (standard)
2. There is an external storage as root for everyone (described above)
3. You set a group folder for everyone as root (via Group Folders app, also official)

Or am I missing something?

**Comment by CSchank** [comment]
Sorry, I wasn't clear. I mean being able to, for example, store different users' data on different hard drives. Maybe I'm just missing how to easily do this. Currently it seems like you can only have one global data directory for everyone (in which all of the users' folders reside).

**Comment by szaimen** [comment]
@wiswedel 
Any update on this? 
I think it is not a big problem but there should definitely be an error message, that having quotas for users with a root-path on external storage is not supported if that is the case here.

**Comment by wiswedel** [comment]
@szaimen I was now able to reproduce it and found the issue to be also applying when setting a config entry to count external storages into users' quotas.
Hence, I opened a new dedicated issue for both phenomenons: https://github.com/nextcloud/server/issues/16943.
Thanks for reporting in the first place.
