### ISSUE TITLE
Update 16.0.1 failed  - SQL oc_addressbooks problem

### ISSUE THREAD

**Issue by rmobpierre** [nextcloud/server#15562]
Have a problem with 16.0.1 update
update stopped
--------------------------------------------------
Présence de mise à jour vérifiée pour l'application "workflowengine" dans l'appstore

Étape de réparation : Repair MySQL collation

Informations de réparation : Change row format for oc_addressbooks ...

Informations de réparation : Change collation for oc_addressbooks ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by jpyrat** [comment]
Same here with upgrade from 15.0.7 to 15.0.8

Stuck :(

**Comment by jpyrat** [comment]
This is because of MB4 that store 4× bytes.
See https://stackoverflow.com/questions/1814532/1071-specified-key-was-too-long-max-key-length-is-767-bytes

**Comment by jpyrat** [comment]
Solved by commenting in config.php
#'mysql.utf8mb4' => true, 

Not a good solution, but it works ;-)

**Comment by rmobpierre** [comment]
Solved with same solution !
thank's @jpyrat

**Comment by wiswedel** [comment]
See also https://docs.nextcloud.com/server/16/go.php?to=admin-mysql-utf8mb4

**Comment by rmobpierre** [comment]
yes  I see but probably doesn't work for me...

sudo -u www-data php occ maintenance:repair
 - Repair MySQL collation
     - Change row format for oc_accounts ...
     - Change collation for oc_accounts ...
     - Change row format for oc_activity ...
     - Change collation for oc_activity ...
     - Change row format for oc_activity_mq ...
     - Change collation for oc_activity_mq ...
     - Change row format for oc_addressbookchanges ...
     - Change collation for oc_addressbookchanges ...
     - Change row format for oc_addressbooks ...
     - Change collation for oc_addressbooks ...

In AbstractMySQLDriver.php line 125:
                                                                               
  An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVER  
  T TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':                            
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
  oo long; max key length is 767 bytes                                         
                                                                               

In PDOStatement.php line 143:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
  oo long; max key length is 767 bytes                                         
                                                                               

In PDOStatement.php line 141:
                                                                               
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was t  
  oo long; max key length is 767 bytes                                         
                                                                               

maintenance:repair [--include-expensive]

**Comment by wiswedel** [comment]
@rmobpierre Have you also carried out all other steps in the manual, not only the occ command?
