### ISSUE TITLE
Setting to remove "recent files" from the files app

### ISSUE THREAD

**Issue by DecaTec** [nextcloud/server#15565]
In Nextcloud 16, there is a top space where the recently edited files are shown (immediately when you open the files app). Personally, I wouldn't use this feature, because it just eats up space on the screen.

It would be great to disable the recent files. A possible solution would be to integrate such an option in the settings which can be reached in the files app in the bottom left corner (where you can enable/disable "show hidden files"). 
This way, every user can decide on his own, if the recent files overview is of any use or if it should be disabled.

An alternative/add on would be that this can be configured by the admin - or at least the default behavior.

**Comment by wiswedel** [comment]
Just disable the _Recommendations_ app, that's been shipped with Nextcloud 16.

**Comment by kesselb** [comment]
> This way, every user can decide on his own, if the recent files overview is of any use or if it should be disabled.

> Just disable the Recommendations app, that's been shipped with Nextcloud 16.

Does not work. There should be a way to enable / disable recent files per user.

**Comment by DecaTec** [comment]
I think that it's not really clear that you have to disable an app for it.
Better would be an setting - maybe the app can be extended by a settings page in personal settings.

**Comment by wiswedel** [comment]
The Recommendations app has its own issue tracker.
There's already a similar feature request over there. Please join the discussion over there:
https://github.com/nextcloud/recommendations/issues/72
