### ISSUE TITLE
latest.zip, latest-16.zip & latest-15.zip need to be updated at https://download.nextcloud.com/server/releases/

### ISSUE THREAD

**Issue by holta** [nextcloud/server#15574]
Thanks for updating {latest.zip, latest-16.zip, etc} to the latest released version at https://download.nextcloud.com/server/releases/ &mdash; as a _core_ part of the e.g. 16.0.1 + 15.0.8 +14.0.11 release process please &mdash; as has been a very helpful part of the actual release process for years!

Ref: #15502

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure

**Comment by MorrisJobke** [comment]
@roeland - looks like the cronjob wasn’t migrated to the new server

**Comment by rullzer** [comment]
It is... and it ran fine as far as I can tell...  
https://download.nextcloud.com/server/releases/latest-16.zip gets me 16.0.1
