### ISSUE TITLE
2FA auth backup codes not removed on user deletion

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1557]
### Steps to reproduce
1. Create a new user
2. Login as that user
3. Generate backup codes
4. As admin delete the user
### Expected behaviour

Backup codes should be deleted
### Actual behaviour

They are still there

@ChristophWurst

**Comment by ChristophWurst** [comment]
1. What exactly is the problem there?
2. We also keep other auth related stuff when a user is deleted, e.g. device passwords, session tokens and TOTP secrets of the TOTP app.

**Comment by LukasReschke** [comment]
> What exactly is the problem there?

That some people believe it should be possible to recreate a user with the same UID. To be honest, I'd just plain simple forbid that for now 🙈

**Comment by ChristophWurst** [comment]
If only there was something like *on delete cascade* …

**Comment by nickvergessen** [comment]
Well, deleting a user should remove all of their data, now?
Those things belong to the user data in my opinion and therefor should be deleted, yes.

**Comment by rullzer** [comment]
So the emitter emits stuff for user deletion. But this is not part of OCP which means that getting apps to use it will be a real pain.

**Comment by ChristophWurst** [comment]
So do we have a clean solution for data removal like this? It feels really bad to add 50 hook listener for any data that is somehow related to a specific user. As mentioned above, usually I would let the database handle it with referential actions, but unfortunately we don't have that in nc.

**Comment by rullzer** [comment]
Best would be I think to dispatch a pre and post delete event with the user object. (note that we use our own emitter thingy for the \OC\User preDelete etc. But I feel the event dispatcher is cleaner.

Apps can then just listen to that event. And do stuff accordingly. Not ideal but the best we have I think as the server can't know what to delete. Also we can't handle this is in all cases on a DB (ldap etc)

**Comment by MorrisJobke** [comment]
and it happened also with other info: #4848
