### ISSUE TITLE
Nextcloud extreme Slow

### ISSUE THREAD

**Issue by gnilebein** [nextcloud/server#15589]
### Steps to reproduce
1. Update to Nextcloud 16.0.1
2. Open any Page in Nextcloud

### Expected behaviour
Nextcloud should run with normal performance

### Actual behaviour
The call is many times slower than expected. It sesems files_external is responsible for this (See Xdebug Infos)

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4

**Database:** MySQL 5.7

**PHP version:** 7.2 FPM

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** tar.gz and Updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - cloud_federation_api: 0.2.0
  - dav: 1.9.2
  - event_update_notification: 0.3.4
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.5.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - rainloop: 6.0.2
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_external: 0.6.1
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - activity
  - admin_audit
  - apporder
  - calendar
  - camerarawpreviews
  - comments
  - contacts
  - deck
  - encryption
  - previewgenerator
  - qownnotesapi
  - ransomware_protection
  - richdocuments
  - twofactor_totp
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.gnilebein.de",
            "www.nextcloud.gnilebein.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.gnilebein.de",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "defaultapp": "rainloop",
        "loglevel": 0,
        "debug": false,
        "appstoreenabled": true,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "theme": "",
        "remember_login_cookie_lifetime": 2592000,
        "session_lifetime": 604800,
        "session_keepalive": true,
        "user_backends": [
            {
                "class": "OC_User_IMAP",
                "arguments": [
                    "{localhost:143\/imap\/tls\/novalidate-cert}"
                ]
            }
        ],
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "app_install_overwrite": [
            "apporder"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
No error in Log. Only Access logs.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No Logfile entries
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No errors
```
</details>

#### XDEBUG Logs
<details>
<summary>Xdebug log</summary>

```
Download of XDEBUG Files and screeshot: https://download.gnilebein.de/NextCloudXdebug/
```
</details>

**Comment by AInteriorB** [comment]
Could php-xdebug itself be the issue? Remove (not only disable) the entire package and try again.

**Comment by gnilebein** [comment]
No. I installed it after the problem occurred.

**Comment by kesselb** [comment]
I've seen some reports from smb users about high cpu load. Mind to try https://github.com/eduardok/libsmbclient-php?

**Comment by gnilebein** [comment]
The problem only occurs if the SMB share is unreachable.

**Comment by kesselb** [comment]
> The problem only occurs if the SMB share is unreachable.

What behaviour would you expect when the smb share is unreachable? I guess we could lower (or make configurable) the timeout for smb connections ...

**Comment by gnilebein** [comment]
In the last version, a banner was displayed in the upper area if a share was not available. But it was usable. 

But in version 16 nextcloud seems unusable until a certain timeout is reached. And this regardless of whether you are in the file browser, calendar or contacts.

**Comment by kesselb** [comment]
Not related to that issue but you might have to update your user_external configuration: https://github.com/nextcloud/user_external/issues/52

**Comment by gnilebein** [comment]
> Not related to that issue but you might have to update the user_external configuration: [nextcloud/user_external#52](https://github.com/nextcloud/user_external/issues/52)

Yes, but this does not affect the original problem.

**Comment by zocker-160** [comment]
> I've seen some reports from smb users about high cpu load. Mind to try https://github.com/eduardok/libsmbclient-php?
> 
> #6865
> #12505

@kesselb OMG thank you that solved my issue!!
after 3hours of debugging and desparation I finally have a fast NC instance again :tada: :tada: :D

**Comment by kesselb** [comment]
@gnilebein https://github.com/nextcloud/server/pull/16836 mind to try this patch?

**Comment by gnilebein** [comment]
> @gnilebein #16836 mind to try this patch?

I tried. But nextcloud ist still very slow and the page load time ist very high when the mount is not available.

**Comment by kesselb** [comment]
Is the same happening with https://github.com/eduardok/libsmbclient-php?

cc @blizzz @icewind1991 smb fun ;) Do you remember any changes to the timeout logic? Is this "storage not available" message gone?

**Comment by gnilebein** [comment]
> Is the same happening with https://github.com/eduardok/libsmbclient-php?

Yes it seems so. IIRC in earlier version the message "storage not available" appears. But now it seems that NC does not try to connect in background. It seems that the connection is blocking the complete process.

**Comment by blizzz** [comment]
@kesselb nope, contrary: with the php-smbclient module it should be handled now correctly, if it fais for auth issues. The best  solution would be if the underyling lib would act in a consistent way, indepent of what way of talking to the SMB storage was used.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
