### ISSUE TITLE
Update to NC 15.0.8 failed

### ISSUE THREAD

**Issue by ChrischanKl** [nextcloud/server#15581]
After the http-Update, pushed up message:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

this are the message at the occ upgrade:

Checked for update of app "workflowengine" in appstore
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Update failed

### Server configuration

**Operating system - Ubuntu 18.04**:

**Web server: Apache 2.4**

**Database: Maria DB 10.3**

**PHP version: 7.3**

**Nextcloud version: bevore Update 15.0.7** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install: fresh**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

now NC are in the maintenance an i can not use it.

**Comment by aagavin** [comment]
@ChrischanKl this solved it for me 
https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740?u=moonlies

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html
