### ISSUE TITLE
issue while updating to 16.0.1

### ISSUE THREAD

**Issue by mkriegl** [nextcloud/server#15583]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Updater says:
Authentication
To login you need to provide the unhashed value of "updater.secret" in your config file.
If you don't know that value, you can access this updater directly via the Nextcloud admin screen or generate your own secret:
`php -r '$password = trim(shell_exec("openssl rand -base64 48"));if(strlen($password) === 64) {$hash = password_hash($password, PASSWORD_DEFAULT) . "\n"; echo "Insert as \"updater.secret\": ".$hash; echo "The plaintext value is: ".$password."\n";}else{echo "Could not execute OpenSSL.\n";};'`
Sercret -> Login

**Comment by wargus85** [comment]
Also having the same problem: "SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes"

**Comment by wargus85** [comment]
After yet more googling, found the solution here:
https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/stable/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by mkriegl** [comment]
Hi guys. I already did that before the upgrade, so I am a little confused. But let me check again tonight, when I am back from work. Thanks so far  ;-)
