### ISSUE TITLE
Vue apps menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15585]
**Is your feature request related to a problem? Please describe.**

The apps menu in the navigation bar is plain old jQuery.

**Describe the solution you'd like**

I would like to replace that with a Vue component.

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/orgs/nextcloud/projects/31

---

@nextcloud/javascript @nextcloud/vue objections?

**Comment by rullzer** [comment]
I guess here the only thing to consider is talking to the app reorder app https://apps.nextcloud.com/apps/apporder

But I guess we can find a way to integrate that

**Comment by skjnldsv** [comment]
I'd say integrate it into core yes.
Into theming?

**Comment by MorrisJobke** [comment]
> I'd say integrate it into core yes.
> Into theming?

I would be unsure about this. But if we need an API, then it's maybe easier to integrate it instead of having it attached. But keep in mind, that some people want to forbid this feature. :/

**Comment by juliushaertl** [comment]
Related issue about integrating the app rearangement: https://github.com/nextcloud/server/issues/4917

Besides then, when rewriting we could also try to look into https://github.com/nextcloud/server/issues/13079 in the same run.

**Comment by skjnldsv** [comment]
> But keep in mind, that some people want to forbid this feature. :/

Well, I meant as a default global feature. Bu I forgot it was request by users as well, not just admin. I guess we could have the same ui on user and admin and one can override the other with an option?

**Comment by MorrisJobke** [comment]
> I guess we could have the same ui on user and admin and one can override the other with an option?

🤧 *cough* featuritis *cough*

**Comment by bpcurse** [comment]
Are there any possible prerequisites for potentially implementing https://github.com/nextcloud/external/issues/132 that could be considered while there's work done on this anyway?

**Comment by ChristophWurst** [comment]
I wouldn't change that in one go (I'm a big fan of keeping refactorings, bugfixes and feature changes separate) but I think we can easily add this as a follow-up :)

**Comment by joshtrichards** [comment]
Fixed in #33728
