### ISSUE TITLE
Vue main menu

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15587]
**Is your feature request related to a problem? Please describe.**

The main menu on the top right is plain old jQuery.

**Describe the solution you'd like**

I would like to replace that with a Vue component.

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/orgs/nextcloud/projects/31

---

@nextcloud/javascript @nextcloud/vue objections?

**Comment by rullzer** [comment]
Just do it. Any app that hacks into there should use a proper provided API IMO.

**Comment by MorrisJobke** [comment]
> Just do it. Any app that hacks into there should use a proper provided API IMO.

external is the only app I know of and it does it via the PHP API we have AFAIK.

**Comment by joshtrichards** [comment]
Fixed by #36232
