### ISSUE TITLE
Vue login page

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15584]
**Is your feature request related to a problem? Please describe.**

The login page is plain old jQuery.

**Describe the solution you'd like**

I would like to replace that with a Vue component.

**Describe alternatives you've considered**

n/a

**Additional context**

https://github.com/orgs/nextcloud/projects/31

---

@nextcloud/javascript @nextcloud/vue objects? Could this break any third party apps that inject random stuff into that page? If so, should we add proper APIs for that stuff?

**Comment by rullzer** [comment]
> @nextcloud/javascript @nextcloud/vue objects? Could this break any third party apps that inject random stuff into that page? If so, should we add proper APIs for that stuff?

I would like this very much. It would also allow us to kill all extra JS etc beging served (with posisble preloading of the main file etc later).

Of course we'd have to know if some apps inject stuff here (imprint app maybe?).
But like you said I'd much rather add a nice API to do this properly. Than to support random hacks.

**Comment by georgehrke** [comment]
If I'm not completely mistaken, the [registration app](https://github.com/pellaeon/registration/) is also hooking into the login page.

**Comment by MorrisJobke** [comment]
> Of course we'd have to know if some apps inject stuff here (imprint app maybe?).
> But like you said I'd much rather add a nice API to do this properly. Than to support random hacks.

There shouldn't be that much that injects into the setup page, right?

**Comment by MorrisJobke** [comment]
> If I'm not completely mistaken, the [registration app](https://github.com/pellaeon/registration/) is also hooking into the login page.

But it does this via the "alternative login" API, right?

**Comment by MorrisJobke** [comment]
Same goes for user_saml.

**Comment by skjnldsv** [comment]
Yep, I agree with @MorrisJobke 
I would actually try to limit a lot what can be added there. :)
Or at least make the design very consistent and not let anyone add anything.

**Comment by georgehrke** [comment]
> But it does this via the "alternative login" API, right?

cc @pellaeon

**Comment by ChristophWurst** [comment]
WIP PR is at #15647
