### ISSUE TITLE
External Storage: More granular permissions

### ISSUE THREAD

**Issue by riesinger** [nextcloud/server#15580]
**Is your feature request related to a problem? Please describe.**
In our college dorm, we use Nextcloud with the 'External Storage' plugin to share files between the house's floors and other groups.
We have a storage VM with ZFS volumes which are mounted into the VM running Nextcloud. Via the 'External Storage' plugin, we then assign groups access to the mounted drives.
Our problem is, that we'd like to disable deleting files from those shares. The plugin 'Group Folders' provides this more granular control. 

**Describe the solution you'd like**
A solution would be to implement the granular permissions of 'Group Folders' into the 'External Storage' plugin.

**Describe alternatives you've considered**
Another solution would be to implement the mounting functionality of 'External Storage' into the 'Group Folders' plugin.

**Comment by riesinger** [comment]
Do you have any feedback on this? Would it be better to open an issue with the GroupFolders plugin?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
