### ISSUE TITLE
On the update page »Update was successful …« also show spinner for feedback

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1559]
When the update was successful, first the spinner and all the info shows. Then when it’s finished, a checkmark appears and it says »redirecting you to Nextcloud now«. But there’s no real loading feedback.

It’s a bit tricky/strange but next to the checkmark there should also be a loading spinner. Or next to the redirect message. Because currently there’s 3–5 seconds where you don’t really notice if something happens.

**Comment by marncz** [comment]
Would like to work on that.

**Comment by marncz** [comment]
Could not see the checkmark but made it so the loading circle is still there to send feedback that the redirect is in progress.

![image](https://cloud.githubusercontent.com/assets/9304594/23225560/2ae411d8-f92a-11e6-9fe8-2ac3e88a37d9.png)

**Comment by MorrisJobke** [comment]
Fixed in #3624
