### ISSUE TITLE
Create share link for external storage (SMB) not working

### ISSUE THREAD

**Issue by Int32Overflow** [nextcloud/server#15595]
I added a SMB external storage to Nextcloud. I enabled the setting "Enable sharing". 

![grafik](https://user-images.githubusercontent.com/20139038/57922021-13460580-789f-11e9-8865-292e24d514d3.png)

But I cannot create a public download link for a network shared file! 

![grafik](https://user-images.githubusercontent.com/20139038/57922986-6456f900-78a1-11e9-8522-0db9416ddb8f.png)

The message "Resharing is not allowed" appears!
![grafik](https://user-images.githubusercontent.com/20139038/57923087-98cab500-78a1-11e9-9128-6bba886e0bae.png)

**System information:**
- **OS:** Ubuntu 18.04 x64 Server
-  **Webserver:** Apache/2.4.29 (Ubuntu)
- **Nextcloud:** 16.0.0  **AND** 16.0.1

**Comment by newkit** [comment]
Same issue here, seems to be related when sharing from SMB, on native FS it works :(

**Comment by guillaumedsde** [comment]
Hi, also having this issue with Nextcloud `19.0.0` and SMB

**Comment by szaimen** [comment]
Based on guillaumedsde's comment, I am closing this issue.
