### ISSUE TITLE
Text color in search box is black with darktheme (should stay white)

### ISSUE THREAD

**Issue by GretaD** [nextcloud/server#15598]
### Steps to reproduce
1. i.e  https://cloud.nextcloud.com
2. On settings, change your theme into dark
3. Click on search icon and type something

### Expected behaviour
The font color should stay white (or color-primary-text)

### Actual behaviour
The font color is black ( color-primary-text seems to get inverted for some reasons)

### Server configuration

**Operating system**:
Ubuntu 18
**Nextcloud version:** (see Nextcloud admin page)
Latest master

@nextcloud/theming 
![font_darktheme](https://user-images.githubusercontent.com/12728974/57927107-73dc3f00-78ad-11e9-99dc-06023d5c5658.png)

**Comment by ostasevych** [comment]
No changes in the 16.0.3 version. The frame, the icon and the text are to be white like other icons, when using the dark theme. http://prntscr.com/ocres6
