### ISSUE TITLE
4 byte unicode characters in filenames with MariaDB causes severe bugs

### ISSUE THREAD

**Issue by jaller94** [nextcloud/server#1560]
Uploading files with 4 byte unicode in their filename can still cause severe problems on ownCloud 10.0.0 (version: 9.1.0.16) with MariaDB 10:
* All files with a 4 byte unicode character can't be edited, downloaded or deleted via ownCloud.
* "Share" a Internal Server Error to other users
* Share your own root folder

This issue was created back in 2013 over here: https://github.com/owncloud/core/issues/4513.

## Preparation
1. Install ownCloud
2. Create user "Romeo" and "Juliet" (names don't matter)
3. Create a non-empty text file on your Desktop

## Share your own root folder
4. Name that file "🐦love letter.txt" (4 byte unicode as the first character)
5. Upload it to Romeo's root folder. (Don't reload the page as it might break your ability to share the file.)
6. Share it with Juliet.

**The result:** After reloading the page Romeo sees this file as "files". Juliet sees a folder called "(2)". This folder contains all files from Romeo. Juliet also sees the file as "(2)" inside that folder "(2)". After reloading Romeo does not see this "file" being shared and can't unshare, delete nor edit it.

## Server
**Operating system**: ubuntu-16.04.1-server-i386

**Web server:** Apache/2.4.18 (Ubuntu)

**Database:** 10.0.27-MariaDB-0ubuntu0.16.04.1

**PHP version:** 7.0.8-0ubuntu0.16.04.2

**Nextcloud version:** 10.0.0 (version: 9.1.0.16)

**Updated from an older ownCloud or fresh install:** fresh install

**Where did you install ownCloud from:** nextcloud.com

**phpinfo:** https://gist.github.com/jaller94/92fe27758d2394ba6cf2442d6e9578c0

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client
**Browser**: Firefox 45.2.0 and IE 11 on Windows 7

**Comment by nickvergessen** [comment]
4byte support is currently not fully implemented, it's however on the todo for [Nextcloud 11](https://github.com/nextcloud/server/issues/745)

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/server/pull/1773
