### ISSUE TITLE
Group add notification sent repeatedly

### ISSUE THREAD

**Issue by woodychuck** [nextcloud/server#15600]
We added ~1000 users in batches via occ to nextcloud, grouped in some 80 groups. Now almost all of them get an email notification that they have been added to a group every 12 hours (at 16:00 and at 4:00), and it is always the same email. They start to get annoyed by these mails, which is totally understandable. I failed to find a activity/notify setting for that specific event, also I could not quite understand the source code in an attempt to fix it myself.

### Steps to reproduce
1. add local groups and users via "occ" (in batches) to NC
2. wait for notification mails...

### Expected behaviour
One notification mail for each group added to.

### Actual behaviour
One notification mail for each group added to every 12 hours.

### Server configuration

**Operating system**:
CentOS 7.6.1810

**Web server:**
nginx-1.12.2-2.el7

**Database:**
MariaDB-server-10.1.38-1.el7.centos.x86_64

**PHP version:**
rh-php71-runtime-1-1.el7.x86_64

**Nextcloud version:** (see Nextcloud admin page)
15.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from previous version

**Where did you install Nextcloud from:**
NC Homepage

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - systemtags: 1.5.0
  - terms_of_service: 1.1.1
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - survey_client
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "share.handler-group.com",
            "share.handlerbau.at"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/share.handler-group.com",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "maintenance": false,
        "theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": ""
    }
}
```
</details>

**Are you using external storage, if yes which one:**
local

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
hasMemberOfFilterSupport: 1
homeFolderNamingRule: lastJpegPhotoLookup: 0
ldapAgentName: CN=sysu_nextcloud,CN=Users,DC=hbc,DC=local
ldapAgentPassword: ***
ldapAttributesForGroupSearch: ldapAttributesForUserSearch: ldapBackupHost: ldapBackupPort: ldapBase: OU=HandlerUser,DC=hbc,DC=local
ldapBaseGroups: OU=HandlerUser,DC=hbc,DC=local
ldapBaseUsers: OU=HandlerUser,DC=hbc,DC=local
ldapCacheTTL: 600
ldapConfigurationActive: 1
ldapDefaultPPolicyDN: ldapDynamicGroupMemberURL: ldapEmailAttribute: mail
ldapExperiencedAdmin: 1
ldapExpertUUIDGroupAttr: ldapExpertUUIDUserAttr: ldapExpertUsernameAttr: ldapGidNumber: gidNumber
ldapGroupDisplayName: cn
ldapGroupFilter: ldapGroupFilterGroups: ldapGroupFilterMode: 0
ldapGroupFilterObjectclass: ldapGroupMemberAssocAttr: uniqueMember
ldapHost: ldaps://1.2.3.4
ldapIgnoreNamingRules: ldapLoginFilter: (&(&(|(objectclass=person))(|(|(memberof=CN=NextCloud,OU=HandlerUser,DC=hbc,DC=local)(primaryGroupID=5193))))(samaccountname=%uid))
ldapLoginFilterAttributes: ldapLoginFilterEmail: 0
ldapLoginFilterMode: 0
ldapLoginFilterUsername: 1
ldapNestedGroups: 0
ldapOverrideMainServer: ldapPagingSize: 500
ldapPort: 636
ldapQuotaAttribute: ldapQuotaDefault: ldapTLS: 0
ldapUserAvatarRule: default
ldapUserDisplayName: displayname
ldapUserDisplayName2: ldapUserFilter: (&(|(objectclass=person))(|(|(memberof=CN=NextCloud,OU=HandlerUser,DC=hbc,DC=local)(primaryGroupID=5193))))
ldapUserFilterGroups: NextCloud
ldapUserFilterMode: 0
ldapUserFilterObjectclass: person
ldapUuidGroupAttribute: auto
ldapUuidUserAttribute: auto
turnOffCertCheck: 1
turnOnPasswordChange: 0
useMemberOfToDetectMembership: 1

```
</details>

### Client configuration
**Browser:**
Firefox, Chrome, ...

**Operating system:**
Windows, Mac...

#### Web server error log
<details>
<summary>Web server error log</summary>

```
-
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
-
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
-
```
</details>

**Comment by skjnldsv** [comment]
Hey, sorry this issue slept through :(
Hope thing got resolved in between.

As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
