### ISSUE TITLE
Upgrade from 15.0.7 -> 16.0.1.1 broke my installation

### ISSUE THREAD

**Issue by Gmentsik** [nextcloud/server#15614]
I wanted to upgrade to the newest :stable image from docker hub, the version before was 15.0.7 and now it wants to upgrade to 16.0.1.1 but this fails with error below.

My problem is that restoring a DB backup does not work, because nextcloud says it can't downgrade from 16.0.1.1 to 15.0.7 ...

I also tried to alter the version.php but then I get a lot of errors regarding incompatible app versions.

What can I do?

### Steps to reproduce
1. Run NX 15.0.7
2. Change docker image to stable (16.0.1)
3. setup fails

### Expected behaviour
upgrade works

### Actual behaviour
I get an error:

```
An unhandled exception has been thrown:
5/19/2019 1:19:42 AMError: Call to a member function getUsers() on null in /var/www/html/lib/private/Repair/RemoveLinkShares.php:218
5/19/2019 1:19:42 AMStack trace:
5/19/2019 1:19:42 AM#0 /var/www/html/lib/private/Repair/RemoveLinkShares.php(230): OC\Repair\RemoveLinkShares->repair(Object(OC\Repair))
5/19/2019 1:19:42 AM#1 /var/www/html/lib/private/Repair.php(100): OC\Repair\RemoveLinkShares->run(Object(OC\Repair))
5/19/2019 1:19:42 AM#2 /var/www/html/lib/private/Updater.php(272): OC\Repair->run()
5/19/2019 1:19:42 AM#3 /var/www/html/lib/private/Updater.php(128): OC\Updater->doUpgrade('16.0.1.1', '15.0.7.0')
5/19/2019 1:19:42 AM#4 /var/www/html/core/Command/Upgrade.php(258): OC\Updater->upgrade()
5/19/2019 1:19:42 AM#5 /var/www/html/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
5/19/2019 1:19:42 AM#6 /var/www/html/3rdparty/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
5/19/2019 1:19:42 AM#7 /var/www/html/3rdparty/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(OC\Core\Command\Upgrade), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
5/19/2019 1:19:42 AM#8 /var/www/html/3rdparty/symfony/console/Application.php(145): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
5/19/2019 1:19:42 AM#9 /var/www/html/lib/private/Console/Application.php(213): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
5/19/2019 1:19:42 AM#10 /var/www/html/console.php(97): OC\Console\Application->run()
5/19/2019 1:19:42 AM#11 /var/www/html/occ(11): require_once('/var/www/html/c...')
```

### Server configuration

Ubuntu - Docker:stable tag
Postgres 10.6 alpine docker image

**Nextcloud version:** 15.0.7 upgrade to 16 

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade

**Where did you install Nextcloud from:** official docker hub

**Signing status:**
<details>
<summary>Signing status</summary>

`

**Comment by fabricedev** [comment]
Hi

Got exactly the same issue doing upgrade from 15.0.7 to 16.0.1

 - Repair MySQL collation
     - All tables already have the correct collation -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Remove shares of a users root folder
 - Move .step file of updater to backup location
 - Fix potential broken mount points
     - No mounts updated
 - Repair invalid paths in file cache
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - SCSS cache cleared
     - JS cache cleared
 - Clear every generated avatar on major updates
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Repair pending cron jobs
     - No need to repair pending cron jobs.
 - Extract the vcard uid and store it in the db
 - Remove potentially over exposing share links
     - Removing potentially over exposing link shares
    0 [>---------------------------]
An unhandled exception has been thrown:
Error: Call to a member function getUsers() on null in ........./Repair/RemoveLinkShares.php:218

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/093c308b584a35a6cc276d65db9db06d21a00ab6/lib/private/Repair/RemoveLinkShares.php#L217-L221

For some reason `$adminGroup` is null. Are you using ldap or any other external user provider? (would be helpful to provide all the information from the issue template). To continue with the update you might comment Line 218 - 221.

cc @nickvergessen @rullzer

**Comment by Gmentsik** [comment]
thanks for your reply, sorry it was late and had no nerves filling out the full issue template.

Also I'm running the docker-image so pretty much of the questions are obsolete, at least I thought so.

I have no LDAP configuration or any external user management.

Thankfully I was able to restore my installation and stay on 15.0.7
I will try the workaround later!

**Comment by Gmentsik** [comment]
Ok so this is strange:
in "Users" Setting I have no Users under "Administratoren" on the installation that fails upgrading.
I guess this is the problem, how could this happen? How can i fix this? My user is the admin user I created during setup, the user is in the group "admin"

**Comment by skjnldsv** [comment]
That is indeed weird.
Please make sure your database `oc_groups` have the `admin` group and that the `oc_group_user` also have the matching `admin` to user entry.

**Comment by fabricedev** [comment]
I confirm : my `oc_groups` table is completely empty but my `oc_group_user` table still have all the users with correct group assigned.
The `oc_groups` table may have been emptied long ago as it doesn't seems to change the behavior of the cloud if you don't need to play with user list...

**Comment by skjnldsv** [comment]
Well, `oc_groups` should ad least contain one entry named `admin`. For the `oc_group_user`, make sure you have your admin user assigned to the admin group.

**Comment by Gmentsik** [comment]
Sorry for the delay!

Actually, I don't a have a table called `oc_groups` only `groups`

There are 5 rows in it:

```
nextcloud=# select * from groups;
      gid       
----------------
 admin
 Tier1
 Tier2
 Adminisztracio
 Administrator
(5 rows)
```

my `group_user` looks like this (redacted a little bit):

```
nextcloud=# select * from group_user;
      gid       |       uid       
----------------+-----------------
 admin          | admin
 Tier1          | user.nameX
 Tier1          | user.nameY
 Tier2          | user.nameY
 Adminisztracio | user.nameX
 Tier1          | admin
 Tier2          | admin
 Administrator  | admin
```

When I visit the page `Administratoren` (my NX is german) no user is in the table

**Comment by skjnldsv** [comment]
@blizzz is it valid to not have a db prefix? (`oc_`) :thinking: 

You still get errors in the nextcloud.log? Do you have more errors than the one you linked in the first post?

**Comment by blizzz** [comment]
> @blizzz is it valid to not have a db prefix? (oc_) thinking

@skjnldsv yes, if it was setup like this. In the old days there was a GUI option in the installer. And you still can set it.

**Comment by skjnldsv** [comment]
> You still get errors in the nextcloud.log? Do you have more errors than the one you linked in the first post?

@Gmentsik

**Comment by skjnldsv** [comment]
@Gmentsik was the error still ocurring?
If not, we can leave it closed, otherwise let's re-open :)
