### ISSUE TITLE
Probably after Installing 16.0.1 loading users by ldap stuck

### ISSUE THREAD

**Issue by mr2017x** [nextcloud/server#15610]
Hi Guys,

after Installing 16.0.1 of Nextcloud the loading of users (in Userpanel as also sharing) stucks and loads to death. when disabling ldap integration app everything is fine, but couldn't be the way to disable it. may you can take a look at? (do you need further infos? please give me a hint)

**Comment by kesselb** [comment]
> do you need further infos? please give me a hint

https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md it's not possible to guess whats wrong without the issue template.
