### ISSUE TITLE
Delete apptoken after account removal

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#15624]
Starting with NC17 clients can/should remove their created app tokens upon account removal.
As clients create "always" their own app tokens via web login, this should no harm.

- [x] Android @tobiasKaminsky https://github.com/nextcloud/android/pull/8577
- [x ] Desktop @nextcloud/desktop 
- [x] iOS @marinofaggiana 
- [x] Server https://github.com/nextcloud/server/pull/15590
- [x] Documentation: https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html?highlight=login#deleting-an-app-password

**Comment by szaimen** [comment]
I suppose this is still valid? Or was it implemented with #15590?

**Comment by tobiasKaminsky** [comment]
This is an overview ticket, so we can track progress on Desktop, iOS and Android.
We will close it once it is done.
