### ISSUE TITLE
IE/Edge NC 15 /users can't remove user from group

### ISSUE THREAD

**Issue by Lephisto85** [nextcloud/server#15625]
Under IE/Edge when I go to Users page, click on groups not working. I can't add or remove user from group.

Also CSS is going crazy in that page, but main issue is adding or removing user from groups.

**Comment by skjnldsv** [comment]
It seems that the issue you have created is lacking the essential informations to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
