### ISSUE TITLE
 Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by bobloghu** [nextcloud/server#15621]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/15058

**Comment by paolo-pedaletti** [comment]
mee too
