### ISSUE TITLE
Search in apps view broken, if multiple authors are specified

### ISSUE THREAD

**Issue by irgendwie** [nextcloud/server#1563]
The search function is broken for the apps view, if an app has multiple authors specified.
This seems to be allowed? according to https://nextcloudappstore.readthedocs.io/en/latest/developer.html#info-xml (@BernhardPosselt)

The reason for this is the following line:
https://github.com/nextcloud/server/blob/master/settings/js/apps.js#L516

In case of multiple ```<author>``` in a `appinfo/info.xml` file, at the specified line, author is an **array**, instead of a **string** and therefore ```toLowerCase()``` fails.

One example app, which is using multiple ```<author>```: https://gitlab.com/eneiluj/gpxpod-oc

**Comment by vgvenkat** [comment]
Can I try this one? I guess adding an isString check would do?

**Comment by juliushaertl** [comment]
@vgvenkat Sure, that would be great.

**Comment by vgvenkat** [comment]
Does this commit https://github.com/nextcloud/server/commit/acd90669ff4ea542091697056a6b24af5be02dc9 handle this issue? It seems to have been committed 10 days ago.

**Comment by nickvergessen** [comment]
Yes this is already fixed
