### ISSUE TITLE
Problem: change number of buckets after first connection in multi bucket setup

### ISSUE THREAD

**Issue by kaystrobach** [nextcloud/server#15633]
## current implementation

```php
public function getHomeMountForUser(IUser $user, IStorageFactory $loader) {
	$config = $this->getMultiBucketObjectStoreConfig($user);
	...
	return new MountPoint('\OC\Files\ObjectStore\HomeObjectStoreStorage', '/' . $user->getUID(), $config['arguments'], $loader);
}
```

[ObjectHomeMountProvider.php](https://github.com/nextcloud/server/blob/master/lib/private/Files/Mount/ObjectHomeMountProvider.php)

- Multi Bucket Object Store Configuration for mount point aus *getMultiBucketObjectStoreConfig*

```php
private function getMultiBucketObjectStoreConfig(IUser $user) {
	$config = $this->config->getSystemValue('objectstore_multibucket');
	...
	$bucket = $this->config->getUserValue($user->getUID(), 'homeobjectstore', 'bucket', null);
	if ($bucket === null) {
		...
		$mapper = new \OC\Files\ObjectStore\Mapper($user);
		$numBuckets = isset($config['arguments']['num_buckets']) ? $config['arguments']['num_buckets'] : 64;
		$config['arguments']['bucket'] .= $mapper->getBucket($numBuckets);
		$this->config->setUserValue($user->getUID(), 'homeobjectstore', 'bucket', $config['arguments']['bucket']);
	} else {
		$config['arguments']['bucket'] = $bucket;
	}
	...
	return $config;
}
```

[ObjectHomeMountProvider.php](https://github.com/nextcloud/server/blob/master/lib/private/Files/Mount/ObjectHomeMountProvider.php)

- relation bucket <->  user via *$mapper->getBucket*
- each user gets a static bucket relation based on his user id
- the system does not save, in which bucket the data is persistet

```php
public function getBucket($numBuckets = 64) {
	$hash = md5($this->user->getUID());
	$num = hexdec(substr($hash, 0, 4));
	return (string)($num % $numBuckets);
}
```

[Mapper.php](https://github.com/nextcloud/server/blob/master/lib/private/Files/ObjectStore/Mapper.php)

- modulo operation depends on the number of buckets

## resulting problem

- the number of buckets can't be changed after initial connection, as the bucket is not saved in the file properties
- this makes scaling harder
- this makes the usage of multiple cloud providers harder than it should be

## ideas

- migrate data and save the bucket name or number in the database
- allow to have multiple buckets and ensure, that it's clear, where a file is saved
- balance the buckets based on the usage, not based on other metrics
- allow a user to store data in multiple buckets, instead of binding the user to just one bucket
- allow easy migration from single bucket configuration to multi bucket configuration

/cc @jonasknobloch

**Comment by kaystrobach** [comment]
@schiessle positive effects of having multiple cloud providers is, that you:

*  do not have a vendor login.
* additionally this may help during a migration, you can start copying and then switch the other cloud provider
* you may use some kind of proxy to copy the files into 2 cloud storages to ensure, that atleast one is up and running (reability)

> The trend is overwhelmingly moving towards multi-cloud. A recent Microsoft study found that 79% of organizations surveyed use a multi-cloud approach, with a whopping 29% responding that they use four or more different cloud providers. Additionally, a 2016 IDC survey found that just over 10% of single cloud organizations have no plans for multi-cloud, while nearly 80% of respondents are either currently using multi-cloud or are working to implement a multi-cloud environment over the next 12 months. 
> https://www.stratoscale.com/blog/it-leadership/cloud-clouds-choose-single-multi-cloud-approach/

**Comment by kaystrobach** [comment]
Also you may save data in the near to the user if you can control, which bucket is used. (Works for public file access only)

**Comment by schiessle** [comment]
@kaystrobach thanks for elaborating on the use case!

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
