### ISSUE TITLE
Delete Button missing on browsing pictures.

### ISSUE THREAD

**Issue by Brakelmann** [nextcloud/server#15639]
Hi,

after upgrading from NC 15 to NC 16 I am missing the delete button on browsing pictures.
There are only the "share link" the "play slideshow" and the "close" buttons left.
In NC 15 there was a delete button delete the displayed picture.

Best regards, Stefan.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/viewer/issues/483
