### ISSUE TITLE
More granular Share Link Permission Settings like for regular users

### ISSUE THREAD

**Issue by Pecadis** [nextcloud/server#15656]
Hi,

i just wanted to share a link with the permissions to Read and Upload but not to delete the files. Unfortunately, it wasn't possible with the current settings because either you just can read the files (or not since NC16), Upload and edit (that includes Delete) or Drop the files.
![image](https://user-images.githubusercontent.com/5543829/58095611-b4043000-7bd3-11e9-8ca5-9e357fb214bf.png)

What i would like to achieve in this case?
I have the case that i would like to share this folder for an Event but don't want the Users to accidentally (or intentionally) delete the Files. They should only be able to Up- and Download the files.

Using a workaround by sharing with a user and set up the Permissions to just read/Change and share allowed me to work around this.
![image](https://user-images.githubusercontent.com/5543829/58095591-a8186e00-7bd3-11e9-912c-d591a0507e95.png)
![image](https://user-images.githubusercontent.com/5543829/58095648-ca11f080-7bd3-11e9-9715-dc4600a4119c.png)

So my Feature request would be the following:
Could you implement a more granular way to share links in the WebUI so that every link can have it's own rules in read/write(upload)/delete as needed as we already have it for regular Users.
![image](https://user-images.githubusercontent.com/5543829/58095827-19582100-7bd4-11e9-9c7d-ac4724a18a0b.png)

I hope this Feature Request is so far understandable. If not, please let me know.
Best Regards
Pecadis

**Comment by tobiasKaminsky** [comment]
If we do this, please inform me / aka create a ticket for client feature parity

**Comment by nickvergessen** [comment]
Closing in favor of #21776
