### ISSUE TITLE
Nexcloud 16.01 wont let hard drive spin down

### ISSUE THREAD

**Issue by OOmatrixOO** [nextcloud/server#15652]
The hard drive from my Unraid server where is the nextcloud folder won’t spin down, even if I’m not using them. It still worked with NC 15.

Nextcloud writes to the nextcloud.log and audit.log files every 15 minutes. These are in the normal folder where all files are located and not in the appdata folder. Is that always the case? I would have suspected these log files in the appdata folder, which is located on the Unraid cache drive.

**Comment by rullzer** [comment]
The log file is by default in the main data folder.
You can have it write to another location using https://github.com/nextcloud/server/blob/master/config/config.sample.php#L757
