### ISSUE TITLE
Sharee list should not show federation first

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#15665]
When entering an email address of a local user the first suggestion is still a federated share. This should not be the case.

![sharing_order](https://user-images.githubusercontent.com/45821/58121487-dc0d8680-7c07-11e9-8ef6-52b003e0bca0.png)

Changes are high if the users enters `user@bar.com` they want to share with user0 that has set that as their email instead of a fedeated share.

**Comment by MorrisJobke** [comment]
Could be partly solved by #16035

**Comment by MorrisJobke** [comment]
I can't reproduce this anymore in master nor in stable16. Seems to be fixed.

**Comment by MorrisJobke** [comment]
Found it - if not the full email is entered this is still happening. Sorting up the local user first would solve this.

**Comment by skjnldsv** [comment]
Not sure if still happening after #15719

**Comment by ChristophWurst** [comment]
> Not sure if still happening after #15719

It is. Now showing

```
user
on bar.com
```
