### ISSUE TITLE
Add option which makes "Deleted files" count towards user quota

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#15661]
It would be nice to have an option which makes "Deleted files" count towards user quota (which is how your OS' trash behaves). Right now, deleted files are _not_ part of the overall user quota, allowing shenanigans such as https://github.com/nextcloud/server/issues/504.
Also, this would prevent automatically deleting files from the trash (which can be really frustrating!)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
