### ISSUE TITLE
error message "There was an error retrieving the share. Maybe the link is wrong, it was unshared, or it was deleted."

### ISSUE THREAD

**Issue by tekmedm** [nextcloud/server#15662]
### Steps to reproduce
1. situation appears since upgrade from 15.0.2 to 15.0.3
2.situation remain as is after upgrade from 15.0.3 to 15.0.8
3.

### Expected behaviour
Share a folder to a user in same nextcloud instance or a public link

### Actual behaviour
error message "There was an error retrieving the share. Maybe the link is wrong, it was unshared, or it was deleted."
Real message is Access Forbidden, CSRF check failed 
looking deeper in debug I found NC-SA-2019-003 message : Nextcloud Server remove links mistakenly considered sensitive without any warning, neither message in nextcloud log. 
NC-SA-2019-003 is related to Nextcloud 15.0.0, my server is 15.0.8.1 which is not in scope.

### Server configuration

**Operating system**: CentOS Linux release 7.6.1810 (Core) 

**Web server**: nginx 1.15.12

**Database:**Type : MariaDB 14
mysql Version : 10.4.4
MariaDB-client-10.4.4-1.el7.centos.x86_64
MariaDB-backup-10.3.15-1.el7.centos.x86_64
MariaDB-common-10.4.4-1.el7.centos.x86_64
MariaDB-compat-10.4.4-1.el7.centos.x86_64
MariaDB-server-10.4.4-1.el7.centos.x86_64

**PHP version:**Version : 7.2.18

**Nextcloud version: 15.0.8.1

**Updated from 15.0.3

Where did you install Nextcloud from: 

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_downloadactivity: 1.4.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trackdownloads: 1.4.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - encryption
  - files_external
  - files_videoplayer
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "myserver.domain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "forcessl": true,
        "dbtype": "mysql",
        "version": "15.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "log_type": "owncloud",
        "logfile": "\/userdata\/data\/nextcloud.log",
        "loglevel": 3,
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "updater.release.channel": "production",
        "theme": "",
        "data-fingerprint": "4c8f7eb5b3ab1976c8e2ed0e36e2d61e",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_sendmailmode": "smtp",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
There are no commands defined in the "ldap" namespace. 
```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** MacOS 10.12.6 / Windows 10 / Android
Same behaviour with nextcloud Android App

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no error related 
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no error related
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Header is this : 
En-têtes de la réponse (416 o) | En-têtes bruts
-- | --
Cache-Control | no-cache, no-store, must-revalidate
XHRPOSThttps://server.mydomain/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
[HTTP/1.1 403 Forbidden 109ms]


notification_id | 17
-- | --
app | core
user | admin
datetime | 2019-05-20T21:33:45+00:00
object_type | repair
object_id | exposing_links
subject | Certains de vos liens partagés ont été supprimés.
message | En  raison d'une faille de sécurité, nous avons supprimé certains de vos  liens partagés. Consultez le lien ci-dessus pour plus d'information.
link | https://nextcloud.com/security/advisory/?id=NC-SA-2019-003



Full message error 403 here :
XHRPOSThttps://myserver.domain/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
[HTTP/1.1 403 Forbidden 109ms]

URL de la requête :https://myserver.domain/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json
Méthode de la requête :POST
Adresse distante :xx.yy.zz.tt:443
Code d’état :
403
Version :HTTP/1.1
	
En-têtes de la réponse (416 o)	
En-têtes bruts
Cache-Control	
no-cache, no-store, must-revalidate
Connection	
keep-alive
Content-Length	
178
Content-Security-Policy	
default-src 'none';base-uri 'none';manifest-src 'self'
Content-Type	
application/json; charset=utf-8
Date	
Tue, 21 May 2019 17:28:48 GMT
***Expires	
Thu, 19 Nov 1981 08:52:00 GMT***
Pragma	
no-cache
Server	
nginx
X-Frame-Options	
SAMEORIGIN
X-Powered-By	
PHP/7.2.18
En-têtes de la requête (1,121 Ko)	
En-têtes bruts
Accept	
application/json, text/javascript, */*; q=0.01
Accept-Encoding	
gzip, deflate, br
Accept-Language	
fr,de;q=0.8,fr-FR;q=0.6,en-US;q=0.4,en;q=0.2
Connection	
keep-alive
Content-Length	
60
Content-Type	
application/x-www-form-urlencoded; charset=UTF-8
Cookie	
sessionLang=en; __Host-nc_same…id=lrue9o50gjrn3h5n4f8nuvdoic
Host	
myserver.domain
OCS-APIREQUEST	
true
Referer	
https://myserver.domain/apps/files/?dir=/&fileid=2
requesttoken	
W0WR8z5xgB0O33I1BUtLLJkRl/8S70…DbSMyeKhEuI0g3Bparyj653dVSAE=
User-Agent	
Mozilla/5.0 (Windows NT 10.0; …) Gecko/20100101 Firefox/62.0
X-Requested-With	
XMLHttpRequest


```
</details>

**Comment by tekmedm** [comment]
every hour I have 2 or 4 this kind of message in log : No app context
{"reqId":"ZsuNzMV4Q609UKN5foig","level":3,"time":"2019-05-22T12:16:06+02:00","remoteAddr":"192.168.10.90","user":"emma","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/emma/969491895/00000009","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 10000000 got 2899968","Code":0,"Trace":[{"file":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":39,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["00000009",null]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["00000009",null]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/emma/969491895/00000009",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://paris.eocengineers.com/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https://paris.eocengineers.com/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https://paris.eocengineers.com/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://paris.eocengineers.com/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/usr/share/nginx/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/usr/share/nginx/html/nextcloud/remote.php","line":163,"args":["/usr/share/nginx/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":222,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/2.3.2 (build 1) (Nextcloud)","version":"15.0.8.1","id":"5ce52eef4c189"}

**Comment by tekmedm** [comment]
every hour I have 2 or 4 this kind of message in log : No app context
{"reqId":"ZsuNzMV4Q609UKN5foig","level":3,"time":"2019-05-22T12:16:06+02:00","remoteAddr":"192.168.10.90","user":"emma","app":"no app in context","method":"PUT","url":"/remote.php/dav/uploads/emma/969491895/00000009","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 10000000 got 2899968","Code":0,"Trace":[{"file":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Upload/UploadFolder.php","line":39,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["00000009",null]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["00000009",null]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/emma/969491895/00000009",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://myserver.domain/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https://myserver.domain/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https://myserver.domain/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/usr/share/nginx/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://myserver.domain/remote.php/dav/uploads/emma/969491895/00000009","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Server.php","line":301,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/usr/share/nginx/html/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/usr/share/nginx/html/nextcloud/remote.php","line":163,"args":["/usr/share/nginx/html/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/usr/share/nginx/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php","Line":222,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/2.3.2 (build 1) (Nextcloud)","version":"15.0.8.1","id":"5ce52eef4c189"}

**Comment by tekmedm** [comment]
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 10000000 got 81920
-- | -- | --
Fatal | webdav | Sabre\DAV\Exception\BadRequest: expected filesize 10000000 got 147456
-- | -- | --

**Comment by tekmedm** [comment]
I've fixed by chance my issue :) since I have found that database was corrupted. 
Can't be repaired said "database created on mysql 5 and using mysql 10'
Done backup 
Removed mariadb 10.4 from my server and processed with a fresh clean install of mariadb 10.3 which is for production. 
restored database 
All is now fixed. 
Sharing working again 👍

**Comment by avanc** [comment]
I had the same problem. It was caused as I forgot to upgrade the database:

    systemctl restart mariadb.service && mariadb-upgrade -u root -p

**Comment by tekmedm** [comment]
And don't forget checking database
# Find out path to datadir
echo "show show variables like 'datadir'" | mysql
mysqlcheck --no-defaults --check-upgrade --auto-repair --databases mysql
mysql_fix_privilege_tables
mysqlcheck --no-defaults --all-databases --fix-db-names --fix-table-names 
--write-binlog
mysqlcheck --no-defaults --check-upgrade --all-databases --auto-repair 
--write-binlog


The connect options given to mysql_upgrade are passed along to mysqlcheck 
and mysql.
