### ISSUE TITLE
Nextcloud claims no OPCache enabled even though it's working

### ISSUE THREAD

**Issue by dnv** [nextcloud/server#15672]
### Steps to reproduce
1. Install 16.0.1 as a fresh install
2. Go to Settings / Administration / Overview

### Expected behaviour
OPCache should be shown as enabled / suggestion to enable OPCache should NOT be present

### Actual behaviour
OPCache is shown as disabled / suggestion to enable OPCache is present.

This is despite the fact that OPCache is, in fact, enabled and working. Per phpinfo():

Zend OPcache

Opcode Caching	Up and Running
Optimization	Enabled
SHM Cache	Enabled
File Cache	Disabled
Startup	OK
Shared memory model	mmap
Cache hits	105017
Cache misses	1169
Used memory	34706960
Free memory	99509360
Wasted memory	1408
Interned Strings Used memory	2847872
Interned Strings Free memory	5540736
Cached scripts	1168
Cached keys	2239
Max keys	7963
OOM restarts	0
Hash keys restarts	0
Manual restarts	0

The cache hits/misses numbers keep growing as Nextcloud is used.

### Server configuration

**Operating system**:
RHEL8

**Web server:**
 Apache/2.4.37

**Database:**
mariadb 10.3.11

**PHP version:**
PHP 7.2.18 (Remi)

**Nextcloud version:**
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
latest.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.1.55",
            "nextcloud.systems.dance",
            "cloud.systems.dance"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "http:\/\/192.168.1.55",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows Server 2019

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No new entries appear in the error.log after the refresh of the page.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No new entries appear in nextcloud.log after the refresh of the page.
```
</details>

**Comment by dnv** [comment]
For good measure I have just tried updating from PHP 7.2 to PHP 7.3, while simultaneously moving from using modular packages that live under /opt, to base packages. The situation is the same, Nextcloud is running, OPCache is alive and well, but Nextcloud admin panel tells me it's off and asks me to enable it.

**Comment by kesselb** [comment]
Mind to share the exact warning?

**Comment by dnv** [comment]
![warning](https://user-images.githubusercontent.com/1187555/58191119-9e236780-7cc6-11e9-8dfc-a1a9d8e94291.JPG)

**Comment by kesselb** [comment]
Is opcache configured like in the warning?

**Comment by dnv** [comment]
Yes:

![nano](https://user-images.githubusercontent.com/1187555/58192434-64079500-7cc9-11e9-977b-c8f6a64b001d.JPG)

![php](https://user-images.githubusercontent.com/1187555/58192598-ca8cb300-7cc9-11e9-8390-3450e45734b3.JPG)

![opcache](https://user-images.githubusercontent.com/1187555/58192608-d11b2a80-7cc9-11e9-8088-86110f83164d.JPG)

**Comment by kesselb** [comment]
Check your phpinfo (there is also a section with opcache and the configuration). I guess the values from php.ini are overwritten in /etc/php.d/10-opcache.ini.

**Comment by dnv** [comment]
This solved the issue. I edited /etc/php.d/10-opcache.ini and the warning is now gone even if I remove the recommended settings from /etc/php.ini altogether.

Suggestion: take note of the possibility of this occuring in the text shown by the warning. Staring blindly at the php.ini doesn't help when the problem is elsewhere. The warning ONLY mentions the php.ini file.

**Comment by kesselb** [comment]
Usually people say thank you but blaming the warning is also fine ;) How to configure php and change such values depends on the operation system and the package maintainers for php there. The php.ini is usually a good starting point. Did you know about https://help.nextcloud.com/? It's nextclouds community for people running nextcloud.
