### ISSUE TITLE
InvalidArgumentException","Message":"The given user id is invalid

### ISSUE THREAD

**Issue by harryabel** [nextcloud/server#15677]
### **I want upgarde 16.0.1 ,but Update failed ,log shows like this:**

`{"reqId":"jTrC7noPG06A7lQ8Co8M","level":1,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Repair::info: Repair info: Sending notifications to admins and affected users","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":3,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"InvalidArgumentException","Message":"The given user id is invalid","Code":0,"Trace":[{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":199,"function":"setUser","class":"OC\\Notification\\Notification","type":"->","args":[203]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":224,"function":"sendNotification","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair\/RemoveLinkShares.php","line":230,"function":"repair","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Repair.php","line":100,"function":"run","class":"OC\\Repair\\RemoveLinkShares","type":"->","args":[{"__class__":"OC\\Repair"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Updater.php","line":272,"function":"run","class":"OC\\Repair","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Updater.php","line":128,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["16.0.1.1","15.0.0.10"]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/core\/Command\/Upgrade.php","line":258,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Command\/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":901,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":262,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"installer":{"__class__":"OC\\Installer"},"__class__":"OC\\Core\\Command\\Upgrade"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/symfony\/console\/Application.php","line":145,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Console\/Application.php","line":213,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/console.php","line":97,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"\/usr\/share\/nginx\/html\/nextcloud\/occ","line":11,"args":["\/usr\/share\/nginx\/html\/nextcloud\/console.php"],"function":"require_once"}],"File":"\/usr\/share\/nginx\/html\/nextcloud\/lib\/private\/Notification\/Notification.php","Line":160,"CustomMessage":"--"},"userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":3,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::failure: InvalidArgumentException: The given user id is invalid","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":3,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::updateEnd: Update failed","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":1,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::maintenanceActive: Maintenance mode is kept active","userAgent":"--","version":"15.0.0.10"}
{"reqId":"jTrC7noPG06A7lQ8Co8M","level":1,"time":"2019-05-22T07:53:59+00:00","remoteAddr":"","user":"--","app":"updater","method":"","url":"--","message":"\\OC\\Updater::resetLogLevel: Reset log level to Warning(2)","userAgent":"--","version":"15.0.0.10"}`

**Comment by kesselb** [comment]
```
Index: lib/private/Repair/RemoveLinkShares.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Repair/RemoveLinkShares.php	(revision ac92603014268a13a9b31beb8bd9dd26cbd84282)
+++ lib/private/Repair/RemoveLinkShares.php	(date 1558543159000)
@@ -196,8 +196,13 @@
 
 		$users = array_keys($this->userToNotify);
 		foreach ($users as $user) {
-			$notification->setUser($user);
-			$this->notificationManager->notify($notification);
+			try {
+				$notification->setUser($user);
+				$this->notificationManager->notify($notification);
+			} catch (\InvalidArgumentException $e) {
+				echo PHP_EOL . 'could not set ' . $user . ' as user for the notification' . PHP_EOL;
+				throw $e;
+			}
 		}
 	}
 

```

Could you try the following patch and share the output? There should be warning like "could not set xxx as user for the notification". Do you have users with long usernames (> 64 characters).

**Comment by karl-in-office** [comment]
@kesselb

I also have the same issue and have tried the above patch in our environment. 

```
$ php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
(snip)
Checked for update of app "workflowengine" in appstore
Remove potentially over exposing share links

 Done
    0/0 [>---------------------------]   0%

could not set USER_ID as user for the notification
InvalidArgumentException: The given user id is invalid
Update failed
Maintenance mode is kept active
Reset log level

```
> Do you have users with long usernames (> 64 characters).

The above USER_ID is only 7 digits of numbers, also it's valid in LDAP server.  
In addition, All of our user IDs are 7 chars. 
If you mean username is as display name, most of our users have very long display name. Because it includes company name and dept name.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Notification/Notification.php#L159-L161

If you user ids only numeric `!is_string(1234)` is true.

```
Index: lib/private/Notification/Notification.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Notification/Notification.php	(revision b968987ed4bf9f3bdcbe423935dd41a36b15ad3d)
+++ lib/private/Notification/Notification.php	(date 1559940119000)
@@ -156,7 +156,7 @@
 	 * @since 8.2.0
 	 */
 	public function setUser($user) {
-		if (!is_string($user) || $user === '' || isset($user[64])) {
+		if ($user === '' || isset($user[64])) {
 			throw new \InvalidArgumentException('The given user id is invalid');
 		}
 		$this->user = $user;

```

@nickvergessen :sos:

**Comment by omysurya** [comment]
You can just trial to disable throw method, like this:

`public function setUser($user) {
                //if (!is_string($user) || $user === '' || isset($user[64])) {
                //      throw new \InvalidArgumentException('The given user id is invalid');
                //}
                $this->user = $user;
                return $this;
        }`

**Comment by karl-in-office** [comment]
@kesselb 
You are right. In my case, !is_string($user) causes InvalidArgumentException in https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Notification/Notification.php#L159-L161

I applied your 2nd patch and then 'occ upgrade' has been finished successfully!

**Comment by kwisatz** [comment]
My comment is probably superfluous, but users that are all integers haven't been prevented in the past, so they probably need to remain allowed (or people given a deprecation warning). 
Or maybe this just needs a more specific check, depending on what you actually wanted to prevent the variable from containing.

**Comment by kesselb** [comment]
> My comment is probably superfluous, but users that are all integers haven't been prevented in the past, so they probably need to remain allowed

There are no plans to disallow users with digits only. The code is in place since owncloud 8.2 (more than 4 years). A typecast to `string` might be enough like suggested here: https://github.com/nextcloud/server/commit/24d6a28f809278c7f31223ff656cd6b1c83a57ff#r33528462

@nextcloud/server-triage will know.

**Comment by skjnldsv** [comment]
I'm actually thinking it is more an error than a feature.
@ChristophWurst @juliushaertl @blizzz what do you think?

**Comment by juliushaertl** [comment]
Yes, as array_keys is causing a cast to integer, adding a string-typecast is fine here I think.
