### ISSUE TITLE
"Add to project" as share option

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#15673]
- [ ] Android
- [ ] Desktop @camilasan 
- [ ] iOS @marinofaggiana 
- [x] Server
- [ ] as projects can be disabled there will be a capability we have to check

Like seen here, we do not have "add to project" in any client.
![](https://user-images.githubusercontent.com/925062/58114636-7796fb00-7bf8-11e9-8b27-16fd4c89918f.png)

**Comment by tobiasKaminsky** [comment]
I wanted to implement this, but I do not get how or where I can create a new project?
This one allows me only to add it to an existing project or link it to a file…

**Comment by tobiasKaminsky** [comment]
@daita maybe, as you implemented this AFAIR?

**Comment by daita** [comment]
No, I don't think I did :) 

@skjnldsv is re-designing the right panel, any idea about implementing this ?

**Comment by skjnldsv** [comment]
No, this is @juliushaertl tha handle the project :ping_pong:

**Comment by juliushaertl** [comment]
For reference, the implementation was added in https://github.com/nextcloud/server/pull/11871

@tobiasKaminsky I'll try to come up with a quick summary of the API endpoints

**Comment by tobiasKaminsky** [comment]
Will be done in a different way.
