### ISSUE TITLE
Error when navigating to shared file upload link

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#15689]
### Steps to reproduce
1. Create a new share link on a folder and set the option File Drop (upload only)
2. Navigate to that link
3. Check the logs

### Expected behaviour
No errors in the logs

### Actual behaviour
`jsresourceloader Could not find resource core/vendor/marked/marked.min.js to load` appears in the log. I don't notice any visible errors when browsing to the page, and upload seems to work fine whether I use the upload dialog or drag and drop.

This is referenced in issue #14986 but that has been closed and this is different because upload works, just with error messages.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache 2.4

**Database:** Mariadb 10.3

**PHP version:** 7.2

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** From .tar.gz package

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - drawio: 0.9.3
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_downloadactivity: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - groupfolders: 4.0.0
  - impersonate: 1.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - files_external
  - files_pdfviewer
  - firstrunwizard
  - recommendations
  - survey_client
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "check_for_working_htaccess": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "maintenance": false,
        "share_folder": "\/Shared With You",
        "theme": "",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "files_downloadactivity",
            "groupfolders",
            "impersonate"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** Active Directory

### Client configuration
**Browser:** Firefox 60.7.0esr 64-bit

**Operating system:** Windows 10 Enterprise 64-bit

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"axb8lMUN89nPMp1fHbIv","level":3,"time":"2019-05-22T13:23:49+00:00","remoteAddr":"REDACTED","user":"--","app":"jsresourceloader","method":"GET","url":"\/s\/EpLFkMdgJfz7SpN","message":"Could not find resource core\/vendor\/marked\/marked.min.js to load","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"16.0.1.1"}
```
</details>

**Comment by stratege1401** [comment]
Hello.

Since update 16.0.1, i get an internal server error when downloading a share files from a link.

Nextcloud version _16.0.1
Operating system and version _Debian10.0
Apache or nginx version _Apache 2.4.25
PHP version _7.3.5

The issue you are facing:

On a share link like :

https://nextcloud.rkn.ovh/index.php/s/test_dwnld
The link is active, you can use it to test !

see the result:
https://help.nextcloud.com/uploads/default/optimized/2X/e/e119c3c73c3105f42176f94e954c8fed730c8de7_2_1035x549.png

**Comment by J0WI** [comment]
This seems to be a duplicate of #15411

**Comment by linucksrox** [comment]
Hm. The log message is the same but I'm not using external storage or even experiencing any noticeable issues other than wondering why this message appears in the log when browsing to a shared link. Perhaps they're related but not isolated to  external storage.

**Comment by skjnldsv** [comment]
Can't reproduce on 17

**Comment by linucksrox** [comment]
@skjnldsv nope, I'm not seeing this error in the logs anymore and I can't reproduce it on version 16.0.3, so closing this out.
