### ISSUE TITLE
Add expiration date on sharing notification mail

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#15680]
When the first share notification mail is sent, it would be nice to have the expiration date on it.

**Comment by AdrianaTobon** [comment]
Hi @skjnldsv I can try to take a stab at this one, this would be my first issue, could you elaborate a bit more?

**Comment by skjnldsv** [comment]
@AdrianaTobon awesome! :)
Yes, when you create a mail share, a mail is sent to the mail you entered.
It could be nice to have the expiration date (if set) in the first mail itself :wink: 

![Capture d’écran_2019-05-29_06-31-10](https://user-images.githubusercontent.com/14975046/58529520-61320600-81db-11e9-9f53-1dcffaf69672.png)

> admin shared »Notes« with you. Click the button below to open it.

Something like "admin shared »Notes« with you. It will expire in xxx days" Use relative date or if over a certain amount use the default absolute date (01/12/2019) :thinking: ?

**Comment by skjnldsv** [comment]
@AdrianaTobon any news?  :)

**Comment by Neelrayal** [comment]
I would like to work in this issue, This is my first issue can you help me a little bit more.

**Comment by skjnldsv** [comment]
@Neelrayal go for it :)

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
