### ISSUE TITLE
Paragraphs should be center aligned on the Admin Support page

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#15692]
On the Admin Community Support page (cloud.example.com/settings/admin/support), the paragraph text for Forum, Github and Chat are left aligned, and might look better if they were center aligned. I think this would be a trivial change, but I'm not sure where the style is defined otherwise I would submit a pull request.

Currently it looks like this:
![image](https://user-images.githubusercontent.com/5169868/58201380-f34d8200-7ca2-11e9-82d4-dd2ffeaf2b5a.png)

I'm proposing to change it to this:
![image](https://user-images.githubusercontent.com/5169868/58201395-fa749000-7ca2-11e9-96de-e0e2dbcb8836.png)

**Comment by MorrisJobke** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
The left-alignment is intentional as centering text is not so good for readability and legibility.

Also see https://en.m.wikipedia.org/wiki/Typographic_alignment

> Centered text is considered less readable for a body of text made up of multiple lines because the ragged starting edges make it difficult for the reader to track from one line to the next.


So it's fine for the headlines in this case, also to align them with the logos, or on the empty content views (e.g. empty folder) with just 1 line of text.

But longer text should be left-aligned, like here and on update pages. (And right-aligned for right-to-left languages.)

**Comment by linucksrox** [comment]
@jancborchardt Thanks for the information, I didn't know that! So does it make sense for the other text on this page to be center aligned (Subscription key, System information, and News) although they span multiple lines?
![image](https://user-images.githubusercontent.com/5169868/58252933-48d26f00-7d35-11e9-8ce4-41d2ca8f6386.png)

**Comment by jancborchardt** [comment]
> So does it make sense for the other text on this page to be center aligned (Subscription key, System information, and News) although they span multiple lines?

@linucksrox as they are only 2 rows each, it is not so bad. But you are right, it’s strange to have it differently here. Looking at it, it would be nice to put the 3 sections as 3 columns side-by-side instead just like the elements above. Do you want to make a mockup for that? :)

**Comment by linucksrox** [comment]
The headers for the System information section is different, so that would need to be updated for consistency (or maybe come up with icons for subscription key and news). Here's the mockup. It still doesn't seem right to me...
![image](https://user-images.githubusercontent.com/5169868/58509657-11b0f300-8165-11e9-9b50-c6362749b1e4.png)

**Comment by jancborchardt** [comment]
Looks good to me! For subscription key I think we do have an icon, at least when it’s enabled it shows. And for "News" you could use the `icon-comment`.

Also make sure that "System information" in the middle has the same heading level as the other headings "Subscription key" and "News".

Lastly could you open a new issue about this, or directly a pull request? :) Thank you!

**Comment by MorrisJobke** [comment]
> Lastly could you open a new issue about this, or directly a pull request? :) Thank you!

Not possible as the repo is not public yet. Let me do the changes then.

**Comment by MorrisJobke** [comment]
The plan was to move this to public after NC 17.
