### ISSUE TITLE
Upgrade to 10.0.1 fails on Remove shares of a users root folder

### ISSUE THREAD

**Issue by compuguy** [nextcloud/server#1569]
This is a similar error to owncloud/core#25621
### Steps to reproduce

Steps to reproduce
1. ran dist upgrade on server
2. ran php occ upgrade as www-data in a screen session
3. fails on Remove shares of a users root folder with this error:

7/283 _percentage bar_ InvalidArgumentException: Invalid recipient
Update failed
Maintenance mode is kept active
Reset log level
### Expected behaviour

 Upgrade succeeds
### Actual behaviour

Errors out with InvalidArgumentException (see step 3 for exact error).
### Server configuration

Operating System: Ubuntu 14.04.5
Web server: apache 2.4.7 (Ubuntu)
Database: Mysql 5.5.52
nextcloud version: 10.0.1
Attempted update/upgrade from 9.0.53
Originally upgraded from owncloud 9.0.3 ---> nextcloud 9.0.53
Installed using zip from nextcloud site

**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, local (openstack attached disks)

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP - will need to sanitize that
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment]
@rullzer

**Comment by compuguy** [comment]
@nickvergessen I'm no longer working for the company for which the nextcloud/owncloud instance had a issue with. You can try to contact @JamesonFinney about this issue for more information.

**Comment by mr-bolle** [comment]
Hi, 

today i upgrade from 10.0.1 to 10.0.2 with the Nextcloud Updater. After the successful update, inow recognize that all shared Files / Folder to some Nextcloud User / Groups disappear.

I have a look into the sql database from Nextcloud an into the table oc_share all entrys still exist.
How i can recover, or refresh this shared files / folders with the current stable Server installation.

MySQL-MariaDB v10.0.28 

thanks Raiko

**Comment by mr-bolle** [comment]
Hi, 

unfortunately after the update to Nextcloud 12, i had to find again that all shared order / files with groups / users had disappeared again. Since I restored the backup (with [OwnBackup](https://apps.nextcloud.com/apps/ownbackup)) of the oc_share from the Nextcloud 11 installation, I had to find errors when sharing links with an expiration date or with a password.

> An exception occurred while executing 'UPDATE `oc_share` SET `password` = ?, `uid_owner` = ?, `uid_initiator` = ?, `permissions` = ?, `item_source` = ?, `file_source` = ?, `token` = ?, `expiration` = ? WHERE `id` = ?' with params [null, "Raiko", "Raiko", 1, 73774, 73774, "dt5b2raoH02oGZj", null, "25"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'password' in 'field list'

![share link with expiration date](https://user-images.githubusercontent.com/22414212/26987709-e0e311de-4d4c-11e7-987a-ff810e03609c.jpg)

**Solution:** After I restored the oc_share backup, i add a new field in the table.
Field name: password
DataType: varchar
Type with: 255

![nextcloud_oc_share additional db field](https://user-images.githubusercontent.com/22414212/26987959-d96a0970-4d4d-11e7-9709-0f42676250c1.jpg)

**Comment by nickvergessen** [comment]
Well of course if you restore a backup from before an update, the structure and data needs to be updated again.

**Comment by mr-bolle** [comment]
Hi @nickvergessen, the post should only be as info for other users. Is it possible after the update to have the shared folders / files with users / groups available. Or am I the only one who has this error?

[Update History](https://github.com/nextcloud/server/issues/1569#issuecomment-267761879)
