### ISSUE TITLE
16.0.0 Multiselect - rows goes up and down

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#15696]
### Steps to reproduce
1. Upgraded from 15 to 16.0.0

### Expected behaviour
The elements doesn't move on v15

### Actual behaviour
When I select all items? the rows goes up by 1px

### Server configuration

**Operating system**:
CentOS 7
**Web server:**
Apache
**Database:**
MySQL
**PHP version:**
PHP 7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
from 15 or fresh install
**Where did you install Nextcloud from:**
From git repo
of activated apps:**

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.0.57"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "http:\/\/192.168.0.57\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "maintenance": false
    }
}
```

I tried it on several browser (opera, firefox, chrome...)

Here is the picture to describe : 

When I don't select all 

![step1](https://i.imgur.com/Oei08hZ.png)

And when I select rows goes up by 1px or something

![step2](https://i.imgur.com/qvTWexf.png)

On version 15, the rows doesn't move.

I also tested with version 16.0.1 and it doesn't work

**Comment by kesselb** [comment]
cc @skjnldsv :sunglasses:

**Comment by skjnldsv** [comment]
@kesselb will you be there at the next contributor week in End of June? :)
Would be awesome to see you there!!!
