### ISSUE TITLE
glitch in email display when using french translation

### ISSUE THREAD

**Issue by JulesDelar** [nextcloud/server#15690]
### Steps to reproduce
1. create a user without password
2. check the received email
3.

### Expected behaviour
display ok

### Actual behaviour
can not see the sentence 
![Capture](https://user-images.githubusercontent.com/50917163/58187547-3fa2bd00-7cb7-11e9-9e07-62e54322a4b1.PNG)

### Server configuration

**Operating system**: Debian

**Web server:** Apache

**Database:** MariaDB 10.1

**PHP version:** 7.3

**Nextcloud version:** 16.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 15

**Where did you install Nextcloud from:** official website

### Client configuration
**Browser:** every email client (gmail, thunderburd,...)

**Comment by jancborchardt** [comment]
This is the same issue as https://github.com/nextcloud/server/issues/13287, closing as duplicate → let’s continue there. :)
