### ISSUE TITLE
NextCloud update to 16.0.1 failed, Database issue

### ISSUE THREAD

**Issue by Neurozone** [nextcloud/server#15698]
### Steps to reproduce
1. Use MariaDB 10.3
2. Use nextcloud version 15.7
3.

### Expected behaviour
Update version to 16.0.0 goes fine

### Actual behaviour
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_collres_collections (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1005 Can't create table `cloud`.`oc_collres_collections` (errno: 140 "Wrong create options")
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_collres_collections (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1005 Can't create table `cloud`.`oc_collres_collections` (errno: 140 "Wrong create options")

### Server configuration

**Operating system**:
CentOS 7.6
**Web server:**
nginx with php-fpm
**Database:**
MariaDB 10.3
**PHP version:** 
7.3

**Nextcloud version:** (see Nextcloud admin page)
15.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
uptdate from 15.7 to 16.0.1
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Neurozone** [comment]
Related to ROW_FORMAT = compressed:

MariaDB [cloud]> 
CREATE TABLE oc_collres_collections (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed;
ERROR 1005 (HY000): Can't create table `cloud`.`oc_collres_collections` (errno: 140 "Wrong create options")

MariaDB [cloud]> 
CREATE TABLE oc_collres_collections (id BIGINT AUTO_INCREMENT NOT NULL, name VARCHAR(64) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB;  Query OK, 0 rows affected (0.251 sec)

**Comment by Neurozone** [comment]
Same for:

CREATE TABLE oc_collres_resources (collection_id BIGINT NOT NULL, resource_type VARCHAR(64) NOT NULL, resource_id VARCHAR(64) NOT NULL, UNIQUE INDEX collres_unique_res (collection_id, resource_type, resource_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed

CREATE TABLE oc_collres_accesscache (user_id VARCHAR(64) NOT NULL, collection_id BIGINT DEFAULT 0, resource_type VARCHAR(64) DEFAULT '', resource_id VARCHAR(64) DEFAULT '', access SMALLINT DEFAULT 0 NOT NULL, UNIQUE INDEX collres_unique_user (user_id, collection_id, resource_type, resource_id), INDEX collres_user_res (user_id, resource_type, resource_id), INDEX collres_user_coll (user_id, collection_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed';

CREATE TABLE oc_login_flow_v2 (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, timestamp BIGINT UNSIGNED NOT NULL, started SMALLINT UNSIGNED DEFAULT 0 NOT NULL, poll_token VARCHAR(255) NOT NULL, login_token VARCHAR(255) NOT NULL, public_key TEXT NOT NULL, private_key TEXT NOT NULL, client_name VARCHAR(255) NOT NULL, login_name VARCHAR(255) DEFAULT NULL, server VARCHAR(255) DEFAULT NULL, app_password VARCHAR(1024) DEFAULT NULL, UNIQUE INDEX poll_token (poll_token), UNIQUE INDEX login_token (login_token), INDEX timestamp (timestamp), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed;

**Comment by Neurozone** [comment]
When I create the last table oc_login_flow_v2 without compressed, i get the following error:

Doctrine\DBAL\Schema\SchemaException: The table with name 'cloud.oc_login_flow_v2' already exists.

**Comment by Neurozone** [comment]
Problem solved.
I've actived global compression for mariaDB and it seems it's uncompatible when table compression is specified
After disabling global compression in my.cnf update goes fine

so table compression enabled is not compatible with global compression

**Comment by stratege1401** [comment]
Hello,

is it closed ??

**Comment by Neurozone** [comment]
You or I can close it, yes.
I just let it open until next day to help someone who have the same issue. (and to be indexed by google)

**Comment by graczu0x0x0x0x0** [comment]
`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_filecache_extended (fileid INT UNSIGNED NOT NULL, metadata_etag VARCHAR(40) DEFAULT NULL, creation_time BIGINT DEFAULT 0 NOT NULL, upload_time BIGINT DEFAULT 0 NOT NULL, UNIQUE INDEX fce_fileid_idx (fileid), INDEX fce_ctime_idx (creation_time), INDEX fce_utime_idx (upload_time)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[HY000]: General error: 1005 Can't create table `nextcloud`.`oc_filecache_extended` (errno: 140 "Wrong create options")
`

Have the same issue in 17.0.1, don't have this before. I can't disable global compression in my.cnf, is there any other way to fix it?

**Comment by kesselb** [comment]
```
CREATE TABLE `oc_filecache_extended` (
  `fileid` bigint(20) unsigned NOT NULL,
  `metadata_etag` varchar(40) COLLATE utf8mb4_bin DEFAULT NULL,
  `creation_time` bigint(20) NOT NULL DEFAULT '0',
  `upload_time` bigint(20) NOT NULL DEFAULT '0',
  UNIQUE KEY `fce_fileid_idx` (`fileid`),
  KEY `fce_ctime_idx` (`creation_time`),
  KEY `fce_utime_idx` (`upload_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin


```

**Comment by graczu0x0x0x0x0** [comment]
> ```
> CREATE TABLE `oc_filecache_extended` (
>   `fileid` bigint(20) unsigned NOT NULL,
>   `metadata_etag` varchar(40) COLLATE utf8mb4_bin DEFAULT NULL,
>   `creation_time` bigint(20) NOT NULL DEFAULT '0',
>   `upload_time` bigint(20) NOT NULL DEFAULT '0',
>   UNIQUE KEY `fce_fileid_idx` (`fileid`),
>   KEY `fce_ctime_idx` (`creation_time`),
>   KEY `fce_utime_idx` (`upload_time`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
> ```

Yes you can remove row format, but its not resolution becouse on next tables it will stop with "arledy exists". In my case i fixed this with changing innodb tyle format to barracuda, previous format not supporting compression.
