### ISSUE TITLE
Security Risk Question WAF needed?

### ISSUE THREAD

**Issue by jonathanmmm** [nextcloud/server#15703]
Hi,

I read some articles to strengthen the security of nginx or nextcloud.

Is a Web Application Firewall (WAF) e.g. ModSecurity or NASXI actually needed and brings benefits? 

I have many Apps activated and don't want that it breaks my nextclous installation multiple times a week e.g. when an uldate comes.

I have also other webservices running.

Is this a risk for a private nextcloud that somebody hacks? I mean they can't get much money or value data like from a company.

Also if you have other suggestions would be great if we could discuss them here :)

**Comment by MorrisJobke** [comment]
As this seems to be a general discussion I would like to raise your question in the forums: https://help.nextcloud.com
