### ISSUE TITLE
Group folders App seems to conflict with OnlyOffice App if Advanced Permissions are applied on a group folder

### ISSUE THREAD

**Issue by TomGem** [nextcloud/server#15702]
## Steps to reproduce

- Enable Group folders
- Enable OnlyOffice
- Test both
- Create a group folder and enable 'Advanced Permissions'
- As an admin set a custom permission on an element inside a group folder, e.g. deny delete.

Now OnlyOffice stops working, server wide, not just for files within group folders.
The error message in the browser is: "Download Failed. 'OK'"

The log file 'data/documentserver/converter/out.log' on the OnlyOffice server says:
[2019-05-22T12:09:38.384] [ERROR] nodeJS - error downloadFile:url=https://host.domain.com/apps/onlyoffice/download?doc=some.very.long.string;attempt=1;code:null;connect:null;(id=123456789)
Error: Error response: statusCode:500

A standard Nextcloud 500 page follows in this log.

Strange thing is, if you copy the url https://host.domain.com/apps/onlyoffice/download?doc=some.very.long.string to a browser the download works fine.

Now disable advanced permissions on the group folder again.
OnlyOffice will get back to work immediately, on the whole server.

Involved Apps:
https://apps.nextcloud.com/apps/groupfolders
https://apps.nextcloud.com/apps/onlyoffice

### Expected behaviour

Working OnlyOffice :)

### Actual behaviour

OnlyOffice not working if advanced permissions are applied on a group folder. 
It is no big deal though. 

## Server configuration detail

**Operating system:** Linux 4.4.0-148-generic #174-Ubuntu SMP Tue May 7 12:20:14 UTC 2019 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.26

**PHP version:** 

7.2.18-1+ubuntu16.04.1+deb.sury.org+1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Web Installer

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - bruteforcesettings: 1.3.0
 - circles: 0.17.3
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dav: 1.9.2
 - deck: 0.6.2
 - drawio: 0.9.3
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_linkeditor: 1.0.10
 - files_markdown: 2.0.6
 - files_mindmap: 0.0.13
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.0.1
 - issuetemplate: 0.5.0
 - keeweb: 0.5.1
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - music: 0.9.5
 - nextcloud_announcements: 1.5.0
 - notes: 2.6.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - onlyoffice: 2.1.10
 - password_policy: 1.6.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - socialsharing_email: 1.0.5
 - spreed: 6.0.1
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - user_ldap: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - calendar
 - contacts
 - encryption
 - external
 - impersonate
 - news

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "htaccess.RewriteBase": "\/",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "circles"
    ]
}
```
</details>

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

## Client configuration

**Browser:** Various

**Operating system:** Various

**Comment by thecube13** [comment]
Similar behavior.
Webserver nginx.
But in out.log statusCode:404.

**Comment by Nils160988** [comment]
Is this still valid for recent versions of nextcloud/onlyoffice/groupfolders?

**Comment by TomGem** [comment]
No, this works fine with current versions. Thanks!
