### ISSUE TITLE
"No apps found for your version" at Nextcloud 16.0.1

### ISSUE THREAD

**Issue by MorimotoShimei** [nextcloud/server#15709]
### Steps to reproduce

1. move to Apps Page
1. No items in Apps page.
3. Log shows as below
```
GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 10000 milliseconds with 1650304 out of 3023319 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
### Expected behaviour
download apps.json from AppStore, and show many items.

### Actual behaviour
only display "No apps found for your version" 

### How to fix

nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php

```
@@ -95,7 +95,7 @@
 		}
 
 		$options = [
-			'timeout' => 10,
+			'timeout' => 300,
 		];
```

**Comment by kesselb** [comment]
Thank you for your bug report :+1: 

Duplicate of #14926

**Comment by sealionking** [comment]
thanks，solved the problem
！

**Comment by robertowest** [comment]
GRACIAS, solucionaste mi problema ;)
