### ISSUE TITLE
Unable to download Collabora Online Connector

### ISSUE THREAD

**Issue by refresher** [nextcloud/server#1570]
### Steps to reproduce
1. Login as admin
2. Go to Apps
3. Check experimental apps
4. Click "Enable" button on Collabora Online Connector
### Expected behaviour

Download / install the app
### Actual behaviour

Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174727-richdocuments.zip [status code] 400 [reason phrase] Bad Request
### Server configuration

**Operating system**:
CentOS 7.2

**Web server:**
Apache 2.4

**Database:**
MariaDB

**PHP version:**
PHP 5.5

**Nextcloud version:** (see Nextcloud admin page)
10.0 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
zip file from official website

**Signing status:**
<details>
<summary>

Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1

```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => '<redacted>',
  'secret' => '<redacted>',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '<redacted-ip-address>',
    2 => '<redacted-domain>',
  ),
  'datadirectory' => '/mnt/nextcloud-nfsimage/nextcloud-data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '<redacted>',
  'dbpassword' => '<redacted>',
  'logtimezone' => 'UTC',
  'installed' => true,
  'instanceid' => 'oc1jtbogxp98',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
  'appstore.experimental.enabled' => true,
);

```

</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no
### Client configuration

**Browser:** Chromium 52

**Operating system:** Linux
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
10.11.0.118 - - [29/Sep/2016:12:18:51 +0300] "POST /index.php/settings/ajax/enableapp.php HTTP/1.1" 200 191 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 Safari/537.36"

- no errors -
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
{"reqId":"V@zcxHRjAWxp7a@vdhOXhgAAAAE","remoteAddr":"10.11.0.118","app":"core","message":"Client error response [url] https:\/\/apps.owncloud.com\/CONTENT\/content-files\/174727-richdocuments.zip [status code] 400 [reason phrase] Bad Request","level":3,"time":"2016-09-29T09:20:07+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"372c8082-1dd211b2-b68f8b55-b2129815"}
```

</details>

**Comment by nickvergessen** [comment]
Please try again, that should have been a temporary failure.

**Comment by refresher** [comment]
Last week I downloaded the zip file manually and unpacked it, then in the "Not enabled" tab I enabled it. Now it says there is an update to 1.1.6.
I disabled the app, clicked update to 1.1.6 and I am still getting the same error.
![screenshot_20161003_123332](https://cloud.githubusercontent.com/assets/553226/19033205/e91e1d90-8965-11e6-8e0f-d600fd155805.png)

**Comment by myzpat** [comment]
Hi like 'refresher' I have the same issue. Both with 1.1.6 and today with 1.1.7.

the error message is: Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174727-richdocuments.zip [status code] 400 [reason phrase] Bad Request

Thank you 

Pat

**Comment by thw26** [comment]
Also experiencing this issue when installing 1.1.7.

```
CentOS 7.2
Apache 2.4, running Event, ruid2 and suexec
PHP 7.0, FCGI
NextCloud 10.0.1
```

> Client error response [url] https://apps.owncloud.com/CONTENT/content-files/174727-richdocuments.zip [status code] 400 [reason phrase] Bad Request

Occurred yesterday and today.

**Comment by artin1998** [comment]
Check firewall configuration!!

**Comment by refresher** [comment]
Firewalld is disabled mate, iptables is running with default ACCEPT policy for the sake of resolving the issue.

**Comment by myzpat** [comment]
Hi, for me, no firewall, no iptables no selinux at all. I have a hardware perimetral firewall in front of datacenter. The linux server has no problems to connect to HTTP/HTTPS destinations.

To resolve the problem, I have disabled the collabora-online app, remove the old 1.1.4, unzip the last 1.1.7 and then I have launched the occ upgrade manually. 

Now I have the same issue with collabora 1.1.8 update.

Thank you 

Patrick

**Comment by thw26** [comment]
Still seeing this issue. Using CSF for a software firewall and port 9980 and others are all open.

**Comment by macwinnie** [comment]
I cannot find any Collabora App within the Apps rider.
Just reinstalled and updated my NextCloud to 10.0.1.

**Comment by MorrisJobke** [comment]
For 11 it is here: https://apps.nextcloud.com/apps/richdocuments
For 10 it is here: https://apps.owncloud.com/content/show.php/Collabora+Online+connector?content=174727
