### ISSUE TITLE
Apps management Sidebar not compliant

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#15712]
@juliushaertl we forgot to update the AppSidebar to the new nextcloud-vue standards when migrating #15506 

@nextcloud/designers

**Comment by juliushaertl** [comment]
I can have a look next week.

**Comment by blizzz** [comment]
I think is stumbled over it today

**Comment by blizzz** [comment]
Although … i think the referenced #15506 is not correct. The files were all generated and commit back then. Today, I am missing the sidebar after rebuilding.

**Comment by MorrisJobke** [comment]
@skjnldsv Didn't you solved this last week with #18969?

**Comment by skjnldsv** [comment]
Yes
