### ISSUE TITLE
Text editor not available on editable shared links

### ISSUE THREAD

**Issue by rgawenda** [nextcloud/server#1571]
### Steps to reproduce
1. Create a folder with a file.txt so default open action es edit using the internal editor
2. Share the folder with link and check the edit checkbox (optional password)
3. Open the link in an incognito window
### Expected behaviour

Clicking on file.txt should open the internal editor
### Actual behaviour

file.txt is downloaded
### Server configuration

**Operating system**: Gentoo GNU/Linux (Base System release 2.2)

**Web server:** nginx/1.11.4 

**Database:** 10.0.22-MariaDB-log - Source distribution

**PHP version:** 7.0.10-pl0-gentoo

**Nextcloud version:** 10.0 (stable)

**Updated from an ownCloud 9**

**Where did you install Nextcloud from:** Distribution package

**Comment by e-alfred** [comment]
This would be a good feature to add. For now Collabora CODE could work with public link editing:

https://nextcloud.com/blog/nextcloud-introduces-anonymous-editing-with-collabora-online/

**Comment by jc97** [comment]
This is currently not possible in NC 12 too. Is there any new information about this? 
Are changes on the core or changes on text editor app required for this?

**Comment by MorrisJobke** [comment]
This is being worked on in https://github.com/nextcloud/files_texteditor/pull/71

**Comment by MorrisJobke** [comment]
Let's move it over to the text editor repo. We have worked on it, but I'm not 100% sure if it already is done or still WIP. cc @danxuliu @rullzer
