### ISSUE TITLE
NC 16 additional settings show a 1

### ISSUE THREAD

**Issue by JDemmerle** [nextcloud/server#15713]
### Steps to reproduce
1. Upgrade from 15.0.7 to stable 16.0.1

### Expected behaviour
Some useful output i guess ;)

### Actual behaviour
Additional settings display "1" and no other information.

### Server configuration

**Operating system**:
Debian 9

**Web server:**
Apache

**Database:**
Maria

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Updater

**Comment by rullzer** [comment]
Could you post a screenshot?

**Comment by JDemmerle** [comment]
Here is the screenshot:
![screenshot](https://user-images.githubusercontent.com/48822360/58397953-619f9500-8053-11e9-8f1d-150b707579dc.png)

**Comment by wiswedel** [comment]
What's that last app in the top bar?

**Comment by kesselb** [comment]
@wiswedel https://passman.cc/

**Comment by wiswedel** [comment]
Seems like a bug from that app: https://github.com/nextcloud/passman/issues/481#issuecomment-415451379

Please jump onto that linked issue at the passman app repo.
