### ISSUE TITLE
Ability to use display name as subfolder for SMB share

### ISSUE THREAD

**Issue by Yomanz** [nextcloud/server#15721]
**Is your feature request related to a problem? Please describe.**
LDAP/AD Integration creates users with some sort of ID for the username and the normal username under Display name -- https://objects.black-out.xyz/56a90ec

**Describe the solution you'd like**
The ability to use something like `$displayname` for the subfolder of an SMB/CIFS share

**Describe alternatives you've considered**
I do not see any alternatives.

**Additional context**
https://objects.black-out.xyz/0ffb703 - Screenshot of the config with the new variable
I tried `$user` but that didn't seem to work.

**Comment by Yomanz** [comment]
Just to add,

Without this it makes it very hard to use LDAP integration together.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
