### ISSUE TITLE
Allow for a "home screen" style view as the first screen.

### ISSUE THREAD

**Issue by ShapeShifter499** [nextcloud/server#15731]
I'm not sure if this is already possible but I'd like to see a way to make a "home screen" style view as the first screen you see after login. This coupled with "External sites" app could extend the Nextcloud to a place to organize all the links to services running on the same server.

This would be a view that would take all the icons in the taskbar and show them as a "home screen" that can be scrolled up and down. Something that can be toggled in settings in case a user wants "show files as home screen" or "show icons as home screen".

**Comment by violoncelloCH** [comment]
This could be implemented as an app I guess... (like the Dashboard app which puts itself at the first position, so it's the app which gets opened by default...)

**Comment by wiswedel** [comment]
https://github.com/nextcloud/dashboard
https://github.com/juliushaertl/apporder

Do these two go into your direction @ShapeShifter499 ?

**Comment by ShapeShifter499** [comment]
@wiswedel can I add clickable icons or links to other Nextcloud apps with https://github.com/nextcloud/dashboard    ?

https://github.com/juliushaertl/apporder  Might help but, it's only for rearranging the icons in the app bar up top?

**Comment by jancborchardt** [comment]
> can I add clickable icons or links to other Nextcloud apps with https://github.com/nextcloud/dashboard ?

These icons / links to other Nextcloud apps are already in the header bar, no need to duplicate that. :)

The dashboard / home screen you are looking for is basically https://github.com/nextcloud/dashboard, even though it’s early days. Please try it out and open issues there for feedback. :)
