### ISSUE TITLE
The icon of exe file can't display for normal

### ISSUE THREAD

**Issue by nxuem** [nextcloud/server#15742]
System version: Ubuntu 18.04 LTS
WebServer: OpenLiteSpeed 1.4.46
Nextcloud version: 16.0.1
Browser: Firefox 67.0

In the url (index.php/apps/files/?dir=/&fileid=6) ,I upload a exe file and when it done, the file icon display nothing, refresh the web page is also.
在文件管理界面，我上传了一个exe文件，当上传完成后，文件图标不显示任何内容，刷新网页也是一样。

![problem_1](https://user-images.githubusercontent.com/4443813/58399127-b6f69900-8089-11e9-83f8-2ba69131d0f6.png)

**Comment by skjnldsv** [comment]
![Capture d’écran_2019-06-05_09-15-46](https://user-images.githubusercontent.com/14975046/58937382-8e9a2900-8772-11e9-9b85-f02e5334276c.png)
I cannot reproduce the issue :/

**Comment by skjnldsv** [comment]
@nxuem maybe you could clear your cache? 
1. [clear your browser's cache](https://www.refreshyourcache.com/)
2. [run](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#run-occ-as-your-http-user) an [`occ maintenance:repair`](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#maintenance-commands-label) on your server

Thanks :wink:
