### ISSUE TITLE
[Feature Request] Add configuration for "Sharing URL"

### ISSUE THREAD

**Issue by OneLogicalMyth** [nextcloud/server#1575]
Would be great to see a parameter something like;

`'sharingurl' => 'https://example.com'`

I run a reverse proxy via cloudflare, so anything externally shared I give out my reverse proxy address. Internal requests go via my internal address.

The only way I can see to do this is to enable all requests to go via 1 url using the parameter;

`'overwritehost' => 'example.com',`

However this simply causes a redirect which is not what I want.

Technically it all works if I just change the URL before sending it to the intended recipient, however the less technical using my cloud keep sending out an internal URL which is not going to work and also exposes the internal DNS address name.

Just a though something simple as that would probably be handy to many people. 👍 
Sorry if its a duplicate request, I did search the documents and on here to see if it has been implemented but couldn't find this documented so assumed it is not.

**Comment by MorrisJobke** [comment]
> I run a reverse proxy via cloudflare, so anything externally shared I give out my reverse proxy address. Internal requests go via my internal address.

Different URL is by definition a different ressource. We only support to run Nextcloud from one URL - if you want two different URLs maybe setup an internal and an external Nextcloud.

> Just a though something simple as that would probably be handy to many people.

Currently we have this request for the very first time. Adding yet another option would only cause more confusion and makes the whole product more complex.

I will close this for now. We maybe re-evaluate this feature if there are more requests for this use case.
