### ISSUE TITLE
Misleading group individual unshare activities

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#15759]
### Steps to reproduce
1. Create two new users and add them to a new group
2. Share a folder with the group
3. Remove the received share as one of the new users

### Expected behaviour
* Admin gets notification `<user> removed themselves from the share named <name>`
* Other user gets `<user> removed themselves from the share named <name>`

### Actual behaviour
* Admin gets `<user> removed you from the share named <name>` (unshared_group_self)
* Other user gets `<user> removed you from the share named <name>` (unshared_by)

### Server configuration

**Nextcloud version:** 15 & 16

**Comment by ChristophWurst** [comment]
cc @nextcloud/sharing

**Comment by ChristophWurst** [comment]
> cc @nextcloud/sharing

:ping_pong: any opinion? Can you confirm this is bugged?

**Comment by nickvergessen** [comment]
Fix is at https://github.com/nextcloud/activity/pull/379
