### ISSUE TITLE
Add note to share

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#15751]
- [x] Android @tobiasKaminsky 
- [x] Desktop @camilasan 
- [x] iOS @marinofaggiana 
- [x] Server @nextcloud/server-triage 

Add note to share

@camilasan @marinofaggiana

**Comment by tobiasKaminsky** [comment]
@misch7 this is just missing on Desktop, then we have this feature complete across all platforms :heart:

**Comment by rullzer** [comment]
@tobiasKaminsky care to double check but I think it is there?

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/76932183-9c2c3400-68ea-11ea-8de2-b830f8143f79.png)

At least not with latest 2.6.4.

**Comment by er-vin** [comment]
For the record: this is done for public link shares, but missing for shares with users or groups.
