### ISSUE TITLE
Error 500 - "RewriteBase: argument is not a valid URL" 

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#1576]
### Steps to reproduce
1. install nextcloud.

### Expected behaviour
Working Nextcloud

### Actual behaviour (web server protocol)
500	GET /status.php HTTP/1.1
[core:alert] /nextcloud/.htaccess: RewriteBase: argument is not a valid URL
Website show a Error 500

### Server configuration - RewriteBase looks correct in my opinion
**.htaccess**
 RewriteBase SUBDOMAIN.DOMAIN.TLD

**PHP version:**
5.6.25

**Comment by MorrisJobke** [comment]
This is a apache issue https://httpd.apache.org/docs/current/mod/mod_rewrite.html

RewriteBase doesn't contain the domain, but only the path.

RewriteBase / for example

**Comment by MorrisJobke** [comment]
https://docs.nextcloud.com/server/10/admin_manual/configuration_server/config_sample_php_parameters.html <- search for rewritebase for more information
