### ISSUE TITLE
Push notification should contain translated app and subject

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#15764]
The "app" and "subject" data should be translate.  

Look https://github.com/nextcloud/ios/issues/868

@nickvergessen

**Comment by MorrisJobke** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Subject should indeed be translated but that should be done in the app that sends it. For me this is the case for all default apps.

Note that we take your configured language by default. So if this is set to english we use that.

Regarding your app name. You should not show that.
See also the webUI. We also do not show it there.
