### ISSUE TITLE
Add publiccode.yml

### ISSUE THREAD

**Issue by nemobis** [nextcloud/server#15760]
**Is your feature request related to a problem? Please describe.**

I get frustrated every time I see a public administration waste money on Google Docs or, even worse, SharePoint.

**Describe the solution you'd like**

Would you be interested in a patch to add a metadata file like https://github.com/globaleaks/GlobaLeaks/blob/master/publiccode.yml ? It's necessary to be included in https://developers.italia.it/en/software/ , the list of free software which the Italian state will heavily advertise to the public sector in Italy.

**Describe alternatives you've considered**

Contacting administrations one by one can be tedious.

**Additional context**
(see website)

**Comment by MorrisJobke** [comment]
cc @karlitschek @jospoortvliet

**Comment by karlitschek** [comment]
I'm a bit skeptical that a lobbying, political and policy problem can be solved with a text file. But we can try. @nemobis Do you want to try and create a pull request with such a file?
@jospoortvliet FYI

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
