### ISSUE TITLE
Prevent federation client server being flooded by NC 16.0 cloud share issue

### ISSUE THREAD

**Issue by hcderaad** [nextcloud/server#15765]
### Steps to reproduce
1. Make a federated share from an NC 16.0 server to a federation client (other server) of any other version
2. The logs will be flooded with Doctrine issues regarding problems with queries on the oc_filecache not being prepopulated with the right query parameters
3. Other shares will stop working on the guest/client NC server and it is impossible to delete the federated share.

### Expected behaviour
The receiving NC server should not be impacted by a problem of a federated share from another server.

### Actual behaviour
The receiving NC server is severely impacted by the problem created by the remote federated share host.

### Server configuration

**Operating system**:
openSUSE Tumbleweed (most recent version)

**Web server:**
Apache 2.4

**Database:**
MariaDB latest version

**PHP version:**
PHP 7.x

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated, but irrelevant

**Where did you install Nextcloud from:**
openSUSE package, yet I have reproduced this problem with tar.gz instances as well.

**Signing status:**
?

**List of activated apps:**
NA

**Nextcloud configuration:**
NA

**Are you using external storage, if yes which one:** local/smb/sftp/...
Only federated shares

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No 

### Client configuration
**Browser:**
Firefox, but also relevant for others as it is a server issue.

**Operating system:**
NA

#### Web server error log
NA

#### Nextcloud log (data/nextcloud.log)
The relevant error is Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_filecache` SET =? WHERE ( <> ? OR IS NULL) AND `fileid` = ? ' with params ["199247"]: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens

#### Browser log
NA

**Comment by hcderaad** [comment]
The issue was fixed on the side of the federation server by this PR. Yet on the federation client apparently not enough input filtering is applied to prevent malformed JSON (or doubly nested) message bodies to escalate on to a Doctrine error. Will perform some debugging later. https://github.com/nextcloud/server/pull/15399

**Comment by hcderaad** [comment]
Looking at the cache update function, it appears that no input checking/validation is done on the $data attribute. This should be checked before propagating an update:
https://github.com/nextcloud/server/blob/master/lib/private/Files/Cache/Cache.php#L235

**Comment by hcderaad** [comment]
And also looking at the files external app, there is no input validation being performed on whatever response is given by the remote server.
This would probably be a good place to automatically disable a misbehaving remote server to prevent further propagation of issues on the local/client server.
https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/External/Scanner.php#L110

**Comment by hcderaad** [comment]
On second thought, it probably makes more sense to add checking the validity of a server response on individual file level in this method:
https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/External/Storage.php#L208

As this misbehavior should actually result in a StorageInvalidException or a StorageNotAvailableException

**Comment by kesselb** [comment]
Does this error still occur?
