### ISSUE TITLE
Files - Deleted Files shows an Error in Headline

### ISSUE THREAD

**Issue by RailsViceRoads** [nextcloud/server#15762]
### Steps to reproduce
1. Click on "Deleted Files" on Files app

### Expected behaviour
Show deleted files

### Actual behaviour
An error message on top of the page. Sorry, I know only the German message: "Dieses Verzeichnis ist nicht verfügbar, bitte die Logdateien überprüfen oder den Administrator kontaktieren."

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** mysql Version: 5.6.19

**PHP version:** Version: 7.1.15

**Nextcloud version:** Version: 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 16.0.0

**Where did you install Nextcloud from:** Tar ball from nextcloud.com

**Are you using encryption:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XOw-8ITYDMtgOxMwfZrJzwACBAY","level":3,"time":"2019-05-27T19:52:16+00:00","remoteAddr":"91.62.171.49","user":"frank","app":"remote","method":"PROPFIND","url":"\/remote.php\/dav\/trashbin\/frank\/trash","message":{"Exception":"TypeError","Message":"Return value of OCA\\Files_Trashbin\\Sabre\\AbstractTrash::getSize() must be of the type integer, float returned","Code":0,"Trace":[{"file":"\/xyz\/www\/cloud\/apps\/files_trashbin\/lib\/Sabre\/PropfindPlugin.php","line":78,"function":"getSize","class":"OCA\\Files_Trashbin\\Sabre\\AbstractTrash","type":"->","args":[]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropFind.php","line":98,"function":"OCA\\Files_Trashbin\\Sabre\\{closure}","class":"OCA\\Files_Trashbin\\Sabre\\PropfindPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/xyz\/www\/cloud\/apps\/files_trashbin\/lib\/Sabre\/PropfindPlugin.php","line":79,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->","args":["{http:\/\/owncloud.org\/ns}size",{"__class__":"Closure"}]},{"function":"propFind","class":"OCA\\Files_Trashbin\\Sabre\\PropfindPlugin","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\Files_Trashbin\\Sabre\\TrashFolder"}]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"OCA\\Files_Trashbin\\Sabre\\PropfindPlugin"},"propFind"],[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\Files_Trashbin\\Sabre\\TrashFolder"}]]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1059,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["propFind",[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\Files_Trashbin\\Sabre\\TrashFolder"}]]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":981,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Sabre\\DAV\\PropFind"},{"__class__":"OCA\\Files_Trashbin\\Sabre\\TrashFolder"}]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["trashbin\/frank\/trash",["{http:\/\/nextcloud.org\/ns}trashbin-filename","{http:\/\/nextcloud.org\/ns}trashbin-deletion-time","{http:\/\/nextcloud.org\/ns}trashbin-original-location","{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http:\/\/owncloud.org\/ns}fileid","{http:\/\/owncloud.org\/ns}permissions","{http:\/\/owncloud.org\/ns}size","{DAV:}getcontentlength","{http:\/\/nextcloud.org\/ns}has-preview","{http:\/\/nextcloud.org\/ns}mount-type","{http:\/\/nextcloud.org\/ns}is-encrypted","{http:\/\/open-collaboration-services.org\/ns}share-permissions"],1]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.xyz.de\/remote.php\/dav\/trashbin\/frank\/trash","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https:\/\/cloud.xyz.de\/remote.php\/dav\/trashbin\/frank\/trash","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https:\/\/cloud.xyz.de\/remote.php\/dav\/trashbin\/frank\/trash","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/xyz\/www\/cloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.xyz.de\/remote.php\/dav\/trashbin\/frank\/trash","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/xyz\/www\/cloud\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/xyz\/www\/cloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/xyz\/www\/cloud\/remote.php","line":163,"args":["\/xyz\/www\/cloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/xyz\/www\/cloud\/apps\/files_trashbin\/lib\/Sabre\/AbstractTrash.php","Line":59,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
```
</details>

**Comment by RailsViceRoads** [comment]
Additional Note: I use the Group folders App 4.0.2 and as far as I remember, the last deleted files was removed from group folders.

**Comment by RailsViceRoads** [comment]
Same behaviour with NC 16.0.2.1 (and Group folders  4.0.3)

![DeletedFilesResponse](https://user-images.githubusercontent.com/36618192/60758316-42166780-a016-11e9-87da-bbabd8a002fb.png)
**The error-log shows this message:**
[remote] Error: TypeError: Return value of OCA\Files_Trashbin\Sabre\AbstractTrash::getSize() must be of the type integer, float returned at <<closure>>

 0. /www/cloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php line 78
    OCA\Files_Trashbin\Sabre\AbstractTrash->getSize()
 1. /www/cloud/3rdparty/sabre/dav/lib/DAV/PropFind.php line 98
    OCA\Files_Trashbin\Sabre\PropfindPlugin->OCA\Files_Trashbin\Sabre\{closure}("*** sensitive parameters replaced ***")
 2. /www/cloud/apps/files_trashbin/lib/Sabre/PropfindPlugin.php line 79
    Sabre\DAV\PropFind->handle("{http://owncloud.org/ns}size", Closure {})
 3. <<closure>>
    OCA\Files_Trashbin\Sabre\PropfindPlugin->propFind(Sabre\DAV\PropFind {}, OCA\Files_Trashbin\Sabre\TrashFolder {})
 4. /www/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([OCA\Files_Trash ... "], [Sabre\DAV\PropF ... }])
 5. /www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1059
    Sabre\Event\EventEmitter->emit("propFind", [Sabre\DAV\PropF ... }])
 6. /www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 981
    Sabre\DAV\Server->getPropertiesByNode(Sabre\DAV\PropFind {}, OCA\Files_Trashbin\Sabre\TrashFolder {})
 7. /www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("trashbin/frank/trash", ["{http://nextcl ... "], 1)
 8. /www/cloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 9. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
10. /www/cloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
11. /www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
12. /www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
13. /www/cloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
14. /www/cloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
15. /www/cloud/remote.php line 163
    undefinedundefinedrequire_once("/www/cloud/ ... p")

**Comment by kesselb** [comment]
Thank you for reporting this issue +1

Please check this report for further information: #13160
