### ISSUE TITLE
External FTP - Normalizing Failed

### ISSUE THREAD

**Issue by seederp2p** [nextcloud/server#15787]
### Steps to reproduce
1. Mount an External FTP Server
2. Make sure it has special characters like ç ã á é, etc
3. Nextcloud will fail to list that

### Expected behaviour
It should work with files and folders with special characters

### Actual behaviour
It won't list those folders and files.

Log:

Warning | core | normalizing failed for "formação"
-- | -- | --

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache2 

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 16.01

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 16.00

**Comment by jannessm** [comment]
I have noticed that it has to do with invalid characters in filenames. Actually, I do have the problem, that I wanted to setup a nextcloud instance with a lot of files. I copied them to my raspberry-pi but now I can't update the filecache because of this warning. I don't know what this normalization is, but I would suggest that the command not quits but rather log this error and ignore this file. Otherwise deleting and so on takes quite a while...

**Comment by t-markmann** [comment]
I have this issue as well in 17.0.2 with groupfolders.

**Comment by remydev** [comment]
Same error !

**Comment by remydev** [comment]
Has someone any idea or solution ?
Thanks

**Comment by mellow2012** [comment]
Has someone any idea or solution ?
Thanks

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by vincentstans** [comment]
i only have a sugestion try normalizing the folder by yourself.

Ex. For formação use forma%C3%A7%C3%A3o'

Encoding can be found link below
[Use Url encode on (w3schools.com)](https://www.w3schools.com/tags/ref_urlencode.ASP)

**Comment by seederp2p** [comment]
I don't use nextcloud anymore so I'll close this ticket.

However it never got solved.

**Comment by ruedigerkupper** [comment]
This problem is still present in NC 22 and I need a solution. Can we reopen this ticket, please?

**Comment by ruedigerkupper** [comment]
Thank you!

**Comment by inode64** [comment]
Same problem with nextcloud 22.2..0 too
But they only fail with directories, with files show fine.
---------------

{"reqId":"xxxx","level":2,"time":"2021-10-05T15:31:10+00:00","remoteAddr":"xx.xx.xx.xx","user":"Marcos","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/Marcos/CLIENTESHD%20Escritura/La%20Liga/2021/FOTOS","message":"normalizing failed for \"/Marcos/files/CLIENTESHD Escritura/La Liga/2021/FOTOS/acreditaci\u00f3n\"","userAgent":"Mozilla/5.0 (Windows) mirall/3.3.4stable-Win64 (build 20210920) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"22.1.1.2"}

{"reqId":"YVxvvIDHZgqYQxBSTygmDQAAAJI","level":2,"time":"2021-10-05T15:31:09+00:00","remoteAddr":"xx.xx.0.xx","user":"Marcos","app":"core","method":"PROPFIND","url":"/remote.php/dav/files/Marcos/CLIENTESHD%20Escritura/WEB%20TEST%202021","message":"normalizing failed for \"/Marcos/files/CLIENTESHD Escritura/WEB XXXX 2021/ROTULACI\u00d3N COCHES\"","userAgent":"Mozilla/5.0 (Windows) mirall/3.3.4stable-Win64 (build 20210920) (Nextcloud, windows-10.0.19042 ClientArchitecture: x86_64 OsArchitecture: x86_64)","version":"22.1.1.2"}

**Comment by jonathanmmm** [comment]
I have the same issue.
I put sftp external folder in. It didn't pick some files up, so I ran occ files:scan --all.
After that many folders that showed correctly files before where now empty.
So somehow in the initial scan it worked (not completely) and files:scan --all removed them.

https://help.nextcloud.com/t/occ-does-not-accept-accents-is-this-a-bug/107296

**Comment by ruedigerkupper** [comment]
Do those files that throw errors come from an Apple device? I see this ptoblem on our NC for MAC users. Apple uses diffetent UTF-8 encoding. (Yes, there are different UTF-8 encodings…)

**Comment by jonathanmmm** [comment]
I don't think so, but I wisk ask the person that uploads the files, if an Apple device was involved.

Toggling the "Compatibility with MAC NFD encoding (slow)" on and after running occ scan:files --all it seems no files are missing.

**Comment by ruedigerkupper** [comment]
Yes, that's the switch to use, that will convert apple-UTF to the rest-of-the-world-UTF. But as thre switch sais, it slows all file access down.

**Comment by ruedigerkupper** [comment]
Congrats, Apple, you are messing up things. That's what we know you for!!

**Comment by remydev** [comment]
This help, but it's not perfect,

`convmv -f utf-8 -t utf-8 -r --notest --nfc <nextcloud-data-folder>`

 sometime, not all files are scan by this, and  i didn't know why.

**Comment by jonathanmmm** [comment]
> Yes, that's the switch to use, that will convert apple-UTF to the rest-of-the-world-UTF. But as thre switch sais, it slows all file access down.

> Congrats, Apple, you are messing up things. That's what we know you for!!

I have asked, as far as this person knows only Windows machines (in German Language, with German keyboards, with German letters ä,ö,ü,ß and spaces, -, _ in file names, the file names are mp3, pdf, pptx, mp4) are included in uploading.

**Comment by ruedigerkupper** [comment]
How does the person upload files? Through the web interface or sync client? Or by accessing the FTP share by some other means? As far as I know, NC web and sync client take care for proper conversions. But this will not work when accessing external shares directly.

**Comment by jonathanmmm** [comment]
Via a ftp client (filezilla or so on Windows).
We wanted to sace space right now on the server and not import them directly into nextcloud. These files are on another server in an upload folder of Wordpress.
Later it gets probably migrated into nextcloud. But the whole usecase of an external share is that it can still be used via the method that doesn't involve nextcloud (of course with the downside that a regular scan is needed to pickup changes).

**Comment by ruedigerkupper** [comment]
When accessing the share directly make sure that all filename encoding is done in UTF-8. That German person might have encoding set to "latin-1" or "latin-9" or "ISO 8859-15" (all these encodings habe been used for German Umlauts). Your NC instance is likely working with UTF-8, so the person should switch to this encoding.

**Comment by ruedigerkupper** [comment]
Or the other way round: your FTP server should convert filename encoding to UTF-8 when talking to your NC.

**Comment by jonathanmmm** [comment]
That could be right, but as this sftp server is a hosted on of strato (server hoster) there is possibly no way to change that.
Is there a way to identify in which coding an sftp sends the filenames and nextcloud would receive them? (Like linux command or tool)?

**Comment by ruedigerkupper** [comment]
`convmv` should be the right tool. To be clear: we're talking about the encoding of file *names*, not the file *contents*. There are several tools that check and convert the encoding of file contents, but they won't help you here.

**Comment by ruedigerkupper** [comment]
And if all fails, there's still one way out: Have the person rename all files to not use special characters like umlauts or accents. And tell them to never use special characters in file names. It will be inconvenient at first but it *will* save them from many troubles in the future. To my experience that's the only way of being sure things will work when you switch platforms or services.

**Comment by WorksAtAUni** [comment]
Seeing this issue in 23.0.0.0. We DO NOT have that level of access to the remote SFTP share. It belongs to a vendor. Can we please resolve this....

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by jonathanmmm** [comment]
> And if all fails, there's still one way out: Have the person rename all files to not use special characters like umlauts or accents. And tell them to never use special characters in file names. It will be inconvenient at first but it _will_ save them from many troubles in the future. To my experience that's the only way of being sure things will work when you switch platforms or services.

Done that. I renamed all files, created a script that would rename all files and files are now in nextcloud.
