### ISSUE TITLE
Developer Feature: Public Direct Links

### ISSUE THREAD

**Issue by yward** [nextcloud/server#15782]
I wrote an app to allow Office Documents to be viewed without Collabora or OnlyOffice using Microsoft Viewer public API "https://view.officeapps.live.com/op/view.aspx?src=yourdoclink"

The app mechanism is very simple, when you click the file it opens a new window with the link:
https://view.officeapps.live.com/op/view.aspx?src=https://yourwebsite.com/remote.php/webdav/FolderName/Document.docx"

The URL is generated programatically as follows:
```

var downloadUrl = context.fileList.getDownloadUrl(fileName);
var onedrive = "https://view.officeapps.live.com/op/view.aspx?src=";
var linkElement = onedrive + downloadUrl;
```
		
However "downloadUrl" generates "emote.php/webdav/FolderName/Document.docx" which is not a public link.

Is there any way we can generate a public direct download link through the app?

**Comment by wiswedel** [comment]
https://docs.nextcloud.com/server/16/developer_manual/core/ocs-share-api.html

@yward Have you checked the Share API's docu?

**Comment by yward** [comment]
@wiswedel I'll take a look, thanks so much for your input!

**Comment by yward** [comment]
@wiswedel  I have a small issue still, when you create a share, it gives you a link to a download page, not a direct link to the file, any way to get a direct download link of the file?

**Comment by wiswedel** [comment]
@yward You can just add _/download_ to the link and it starts downloading instantly.

**Comment by yward** [comment]
@wiswedel  Oh perfect! one last question, is there is a way to use the API in javascript or it's only PHP or curl?

**Comment by wiswedel** [comment]
CC @skjnldsv

**Comment by skjnldsv** [comment]
There is a rest api available yes. 

``` js
fetch("/ocs/v2.php/apps/files_sharing/api/v1/shares?format=json", {
    "body": "expireDate=11-07-2019&hideDownload=false&password=&passwordChanged=false&sendPasswordByTalk=false&permissions=31&shareType=3&path=/file/to/share",
    "method": "POST",
    "mode": "cors"
});
```
