### ISSUE TITLE
Duplicate file / create copy inside same folder

### ISSUE THREAD

**Issue by jlord87** [nextcloud/server#15785]
It would be really helpful if we were able to create a copy of a file from the web interface with just one click.

Whenever I need to edit a model file from the web interface I need to copy to another folder, change the name and copy back to the original location. I think there should be an option in the file menu, right under the "Move or Copy" option.

For a file named "example.docx" it could create a copy named "example-copy.docx" (or example-copy1 if example-copy already exist, and so on)

thank you

PS. I've looked for this request and haven't found anything similar; sorry if it's a duplicate

**Comment by georgehrke** [comment]
This app is probably what you are looking for? 
https://apps.nextcloud.com/apps/files_clipboard

**Comment by georgehrke** [comment]
Recent versions of Nextcloud even support that natively:
![53333FBE-257D-4E37-B2BF-915B04A25F0E](https://user-images.githubusercontent.com/1250540/58573203-8a837e00-823d-11e9-8b04-70a913e9f9c1.jpg)

**Comment by georgehrke** [comment]
Sorry, misunderstood your issue.

**Comment by skjnldsv** [comment]
cc @jancborchardt for UX

**Comment by jancborchardt** [comment]
Copying inside the same folder works just fine by going to the file → Move or Copy → just press "Copy" in the same folder. Result:
![image](https://user-images.githubusercontent.com/925062/91157368-8571e080-e6c5-11ea-86f6-a84c87b97f03.png)
