### ISSUE TITLE
Proposing Complete Design Overhaul

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#15798]
My suggestion here is a complete design overhaul to the Nextcloud design, the current one honestly just feels dated and fairly basic. It made sense back when there was no Nextcloud and Owncloud was a small project but it has grown quite a bit and is enterprise ready but the design is just lacking in my opinion. Maybe I have bad tastes but this is just my proposal. What do you all think?

If this is agreeable, then I would suggest having some proposed designs submitted by the community, selecting 5 of them and then having a vote by the community which one to implement.

**Comment by georgehrke** [comment]
> but the design is just lacking in my opinion. 

If you have specific design issues that you would like to see addressed, please file them as individual issues. There is even a dedicated label for design issues: https://github.com/nextcloud/server/issues?q=is%3Aopen+is%3Aissue+label%3Adesign

> If this is agreeable, then I would suggest having some proposed designs submitted by the community, selecting 5 of them and then having a vote by the community which one to implement.

I'm sorry, but that's not how we do design here. There is a design team that dedicates their time to continuously develop and improve Nextcloud's design. On Github they are @nextcloud/designers, on IRC you can find them on `#nextcloud-design` (Freenode).
