### ISSUE TITLE
Limit a user's visibility of other users and Groups based on their own Group assignment.

### ISSUE THREAD

**Issue by colinosullivan** [nextcloud/server#15795]
**Is your feature request related to a problem? Please describe.**
Currently a user can search users across any Group in Nextcloud. Our organisation requires some separation of Groups for conflict of interest reasons due to business function. _A practical example might be, two divisions. One division doing corporate accounts for organisations, a second division auditing accounts for possibly the same organisations._ Currently a user in Group A can see / search users across the whole Nextcloud instance. 

The features where this occurs that come to mind include (you may think of other areas):

- Sharing files or folders 
- Searching users in the Talk App
- Searching users in the Chat app
- 'Search contacts' feature in Nextcloud

Ideally a user can only see contact information for those people in their assigned Group. 

See forum thread: https://help.nextcloud.com/t/limit-the-contacts-that-appear-to-a-user-when-sharing-to-contact-only-within-their-groups/53328

**Describe the solution you'd like**
By default or via a Nextcloud admin setting: A user should only be able to see / search the users in the Groups of which they are a member. **they should not be able to see through type ahead any users that may exist on the instance outside their assigned Groups.** 

**Describe alternatives you've considered**
The only alternative at the moment the only other alternative is we have an instance per Group which is not really feasible long term.

**Additional context**
I am hoping if the user search feature is a shared class throughout the Nextcloud server and apps, then this implementation may not be overly complex but very useful.

Thank you for considering this feature request.

**Comment by szaimen** [comment]
I suppose you are looking for the configuration value `Restrict username autocompletion to users within the same groups`
https://docs.nextcloud.com/server/stable/admin_manual/configuration_files/file_sharing_configuration.html?highlight=limit%20group#file-sharing
