### ISSUE TITLE
Avoid "Internal Server Error"  if there is no permission

### ISSUE THREAD

**Issue by guzi42** [nextcloud/server#15792]
**Is your feature request related to a problem? Please describe.**
If a share permission is removed, the user that like to access get an error message :

Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
.....
**Describe the solution you'd like**
The message should show a clear status like "you have no permission to access" or "file does not longer exist"

**Additional context**
It should be clear, that it's not a system failure and that Nextcloud works well.

**Comment by skjnldsv** [comment]
@nextcloud/sharing don't we throw a 403, Aren't 403 displayed to the user then?

**Comment by rullzer** [comment]
We need a bit more use case.
When does this happen exactly?

**Comment by guzi42** [comment]
Procedure to reproduce 
- Share a document with an other user
- the server will send an e-mail with the link to the document
- Un-share the document
- Let the other user click on the link

The server will shown an error message like 

---------------------------------------------
`
Internal Server Error

The server was unable to complete your request.

If this happens again, please send the technical details below to the server administrator.

More details can be found in the server log.
Technical details

 Remote Address: 10.3.3.6
 Request ID: RXqXmWaKcC4HYuEaiMo1
 Type: OCP\Files\NotFoundException
 Code: 0
 Message:
 File /var/www/owncloud/apps/files/lib/Controller/ViewController.php
 Line : 327

Trace
#0 /var/www/owncloud/apps/files/lib/Controller/ViewController.php(141): OCA\Files\Controller\ViewController->redirectToFile('1772339')
#1 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(166): OCA\Files\Controller\ViewController->showFile('1772339')
#2 /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php(99): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\Files\Controller\ViewController), 'showFile')
#3 /var/www/owncloud/lib/private/AppFramework/App.php(126): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Files\Controller\ViewController), 'showFile')
#4 /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Files\\Contr...', 'showFile', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#5 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#6 /var/www/owncloud/lib/private/Route/Router.php(297): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#7 /var/www/owncloud/lib/base.php(975): OC\Route\Router->match('/f/1772339')
#8 /var/www/owncloud/index.php(42): OC::handleRequest()
#9 {main}
-------------------------------------------------------------
`

**Comment by Lartza** [comment]
I feel like this was closed on accident. I had another user ask about a similar case on IRC, accessing shares that don't exist OR that you have no access to show internal server error, instead of a 403?

**Comment by kesselb** [comment]
I guess this is fixed by https://github.com/nextcloud/server/pull/15993

**Comment by Lartza** [comment]
Ah yes, I can confirm that the change does fix it on 16.0.4
