### ISSUE TITLE
CSRF check failed!

### ISSUE THREAD

**Issue by GovetaXV** [nextcloud/server#15797]
![2019-05-29](https://user-images.githubusercontent.com/26822488/58571842-2b7f3280-8258-11e9-8852-261346174dc7.png)

Some of my users are getting this message!

**Comment by georgehrke** [comment]
please use the [issue template](https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE/Bug_report.md) when reporting bugs.

How do you expect us to reply to such a report if you give us no reproduction steps and not even tell us the version you are using?

**Comment by stratege1401** [comment]
Hello,

most of csrf ( cross-sire request forgery ) check error are due to bad browser caching.
Try to clear/clean cache.

**Comment by georgehrke** [comment]
No response from original reporter, closing.
We can reopen once we original reporter uses the issue template.
