### ISSUE TITLE
Nextcloud Apache2.4 bug

### ISSUE THREAD

**Issue by hanhanwen-github** [nextcloud/server#15808]
Nextcloud程序支持apache2.4吗？
如果支持，是不是支持的不够完善?
因为这边检查到在Apache2.4环境中，nextcloud上传包含中文字符命名的文件时是错误的，
这个错误表现为无法上传。

这边技术员说是nextcloud只支持到apache2.2。
对apache2.4的支持不够完善。
我想问问。的确如此吗？

**Comment by hanhanwen-github** [comment]
![Snipaste_2019-05-30_12-07-10](https://user-images.githubusercontent.com/44543537/58629266-90955f80-830e-11e9-8fc2-043c039362ab.jpg)

![Snipaste_2019-05-30_12-06-54](https://user-images.githubusercontent.com/44543537/58629272-9a1ec780-830e-11e9-8f78-2a19caa4eeca.jpg)
上传中文字符命名的文件就出现如上问题。无法上传。

你们是不是只支持apache2.2？用2.4出问题。
如果用Nginx环境就没问题。

感谢回复。

**Comment by kesselb** [comment]
Thank you @hanhanwen-github for your bug report :+1: 

Mind to rephrase your question in english and use the issue template https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md?

I use Nextcloud with apache2.4 and it does work for german umlauts (öüü). Do you have some example file which is not working? You might use https://demo.nextcloud.com/ to reproduce the issue.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
