### ISSUE TITLE
Move files in shared folder with RO

### ISSUE THREAD

**Issue by SebSeifert** [nextcloud/server#15805]
### Steps to reproduce
1. Move an File in an shared Folder with Read Rights Only

### Expected behaviour
Move an File in a shared Folder to another inside or outside the shared folder.

### Actual behaviour
Getting Error: Could not move "xxx.xx"

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
nginx

**Database:**
MariaDB

**PHP version:**
7.3.5

**Nextcloud version:** (see Nextcloud admin page)
15.0.7.0 (16.0 also not working)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.1
  - deck: 0.6.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - gallery: 18.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - richdocuments: 3.3.6
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - firstrunwizard
  - groupfolders
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.7.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:**
Chrome

**Operating system:**
Windows 10

**Comment by wiswedel** [comment]
I don't understand the expectation. When the folder is RO, what other than am error do you expect?

**Comment by SebSeifert** [comment]
Sorry i wrote it wrong! Its Not Read only.
The owner can edit every file. But the groups that have Access to the folder with the rights:
Can edit: true
Can change: true
Can delete: false
Is not able to move files.

**Comment by Nils160988** [comment]
But still: If the user is not allowed to delete, it should not be able to move a file, because move is like "copy and delete"
So everything works as expected

**Comment by SebSeifert** [comment]
But for me "move != copy&delete" so for me it is not working as expected. After an successfull copy the source file can be deleted.

**Comment by SebSeifert** [comment]
Also for edit.

**Comment by wiswedel** [comment]
> But for me "move != copy&delete" so for me it is not working as expected.

Sorry, but that's your problem if you don't agree with the basics. 

Therefore no bug here.

**Comment by SebSeifert** [comment]
So how about an Feature request? Everyone has different basics.

**Comment by Nils160988** [comment]
Sorry, but there are no different basics in this case...

From a perspective of the owner, if you want your file to stay where it is, you do not grant others the permission to delete the file
If the other user then moves the file somewhere else or deletes it, it makes exactly no difference for the owner, so it has to work exactly as it does.
