### ISSUE TITLE
Move theming to a register based approach

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#15815]
Right now we do a lot of weird magic to make theming work. because it overwrite the defaults (in part). In doing this weird magic we also intialize a lot of classes that might not even be required (for example if you do a pure API request).

Long story short we should move this to how we handle Sentry/Support.
Theming can register itself in the server if it is there. And then the requests for data are proxied.

That way initialization of the Defaults is trivial and quick. And the loading of theming can be lazy and only done when actually required.

CC: @MorrisJobke @ChristophWurst

**Comment by rullzer** [comment]
So I bumped into some theming init today again. So probably good to look into this.

also cc @juliushaertl since you also worked on this.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
