### ISSUE TITLE
App restricted-to list keeps usergroups that no longer exist [NC 16.0.1]

### ISSUE THREAD

**Issue by DBJRdev** [nextcloud/server#15823]
### Steps to reproduce
1. Restrict any app to a specific user group.
2. Delete the user group in the user management.
3. The restricted-to list of the app still contains the non-existant group.

### Expected behaviour
1. The app's restricted-to list should no longer contain a non-existant usergroup.
2. If it was the last group in the restricted-to list, then probably the app should be deactivated. (I was thinking about that for a while, but so far no better solution came to my mind.)

### Actual behaviour
When installing a Nextcloud app, it is possible to restrict it to certain user groups. Yet after a group ceases to exit (=deleted in user management), the non-existant usergroup still appears in the restricted-to list of that app.

### Server configuration

**Operating system**: Ubuntu (Shared hosting)

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** NC 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrades since 12.x

**Where did you install Nextcloud from:** web installer

**Comment by violoncelloCH** [comment]
cc @nextcloud/server-triage

**Comment by MorrisJobke** [comment]
We might need to clean that up on group deletion. 🤔 (and add a repair job for existing ones)
