### ISSUE TITLE
In china, how to add ICP number

### ISSUE THREAD

**Issue by nxuem** [nextcloud/server#15824]
在中国，建立一个网站必须获取一个ICP备案号，并将其添加到网站首页的页脚，就像"鄂ICP备15018658号"，我已经有一个了。
但是，我没有找到怎么添加到Nextcloud中.

In china, build a website should get a ICP record number, and add it to footer of homepage. It's like "鄂ICP备15018658号", and i have it.
But i'm not found how to add it to Nextcloud.

In the capture, it's at footer of page.
![火狐截图_2019-05-31T08-56-00 929Z](https://user-images.githubusercontent.com/4443813/58694181-01974e80-83c5-11e9-8980-a626e6fe028e.png)

**Comment by DBJRdev** [comment]
Just an idea: in the administration panel, Nextcloud has a section called "Design"/"Theming". There you can edit a slogan, which appears in the footer. Wouldn't it be a possible solution to use that for the ICP record number?

**Comment by nxuem** [comment]
> 
> 
> Just an idea: in the administration panel, Nextcloud has a section called "Design"/"Theming". There you can edit a slogan, which appears in the footer. Wouldn't it be a possible solution to use that for the ICP record number?

Yeah,it's solved,and it's so fun,thank you.But i also want to edit html code,haha.

**Comment by violoncelloCH** [comment]
why would you need to edit html code? (you could do so by editing nextclouds source but would need to redo the changes after every update)
as the original issue is solved I guess we can close this, right?

**Comment by GanZiheng** [comment]
> Just an idea: in the administration panel, Nextcloud has a section called "Design"/"Theming". There you can edit a slogan, which appears in the footer. Wouldn't it be a possible solution to use that for the ICP record number?

But according to the regulation, there should be a link under the ICP number, how to add it?

**Comment by guilinonline** [comment]
我也收到通知了，必须要添加，我发现除了改源码好像没有方法可以实现
