### ISSUE TITLE
UI gives incomplete information

### ISSUE THREAD

**Issue by stone212** [nextcloud/server#15825]
On Nextcloud 15 (and now 16) my `index.php/settings/admin/overview` gives this information:

```
The database is missing some indexes. Due to the fact that adding indexes on big tables could take some time they were not added automatically. By running "occ db:add-missing-indices" those missing indexes could be added manually while the instance keeps running. Once the indexes are added queries to those tables are usually much faster.
```

When I log into my server and run `occ db:add-missing-indices` it says `command not found`.  

Probably the UI is giving me incomplete information.  I need to go to a specific directory, maybe even `sudo -u` as a different user?

**Comment by stone212** [comment]
HINT:  Solution is to change it to say:  `sudo -u www-data /nextcloud/directory/occ db:add-missing-indices`

**Comment by violoncelloCH** [comment]
the thing is this depends on your specific setup how you need to execute the occ command... therefore all occ commands are referred to as such... 
only thing I see here would be a general hint with a link to the documentation on how to execute occ commands...
what do you think @nextcloud/documentation ?

**Comment by wiswedel** [comment]
>HINT:  Solution is to change it to say:  `sudo -u www-data /nextcloud/directory/occ db:add-missing-indices`

Almost. 

`sudo -u www-data php /nextcloud/directory/occ db:add-missing-indices`
(_/nextcloud/directory_ is of course here only a placeholder for the real path to your Nextcloud directory)

**Comment by stone212** [comment]
@wiswedel I ran the command as I typed it.  It looked successful.  Do you think I should run it your way.  The exact command I used (from `/var/www/nextcloud`) is `sudo -u www-data ./occ db:add-missing-indices`

Also why close this?  Did you fix the code so other people do not experience this bug?

**Comment by wiswedel** [comment]
> Also why close this? Did you fix the code so other people do not experience this bug?

occ's usage is documented under https://docs.nextcloud.com/server/16/admin_manual/configuration_server/occ_command.html.

I don't see any bug here.

**Comment by stone212** [comment]
@violoncelloCH 

> the thing is this depends on your specific setup how you need to execute the occ command

Maybe but the docs have centered on one way of presenting the occ command, and the UI breaks that.  So the solution would be consistant usage in the docs and UI

> occ's usage is documented

That is not related to this Issue

> I don't see any bug here.

I don't know if that is because you don't understand what a UI bug is, or because you are not seeing well.  But if you re-read this Issue carefully you will understand what needs to be fixed if you want to produce good UI.
