### ISSUE TITLE
Files-app not showing files after cleaning up trash

### ISSUE THREAD

**Issue by oresch** [nextcloud/server#15826]
### Steps to reproduce
1. App/files -> open trashbin
2. Deleting all files with "select all" and than delete
3. Now click on "all files" on the left menu (app-navigation) 
4. No file is shown. I need to click in the header on the main "files app" icon to get the root folder to be shown

### Expected behaviour
Files on root should be shown

### Actual behaviour
empty list

### Server configuration

Operating system: Linux 4.19.0-0.bpo.5-amd64 #1 SMP Debian 4.19.37-3~bpo9+1 (2019-05-18) x86_64

Webserver: nginx/1.10.3 (fpm-fcgi)

Database: mysql 10.2.24

PHP version: 7.0.33-0+deb9u3

Nextcloud version: 15.0.8 - 15.0.8.1 (already recognized in earlier versions)

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown  => manually 

Enabled:
 - accessibility: 1.1.0
 - activity: 2.8.2
 - admin_audit: 1.5.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - comments: 1.5.0
 - contacts: 3.1.1
 - dav: 1.8.2
 - deck: 0.6.2
 - encryption: 2.3.0
 - federatedfilesharing: 1.5.0
 - federation: 1.5.0
 - files: 1.10.0
 - files_external: 1.6.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_texteditor: 2.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - files_videoplayer: 1.4.0
 - firstrunwizard: 2.4.0
 - gallery: 18.2.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notes: 2.6.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - serverinfo: 1.5.0
 - sharebymail: 1.5.0
 - support: 1.0.0
 - survey_client: 1.3.0
 - systemtags: 1.5.0
 - tasks: 0.10.1
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - theming
 - user_ldap

### Client configuration
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0

**Comment by violoncelloCH** [comment]
Thanks for reporting!
However I can't reproduce this with NC 16.0.1
can you test if this issue persists for you with NC 16.0.1?

**Comment by oresch** [comment]
Unfortunately I cannot test beyond v15.

Am 31. Mai 2019 21:20:52 schrieb "violoncello.ch" <notifications@github.com>:

**Comment by kesselb** [comment]
Still an issue?

**Comment by oresch** [comment]
No. Can be closed

Am 27. Januar 2020 21:34:30 schrieb kesselb <notifications@github.com>:
