### ISSUE TITLE
apple-touch-icon-precomposed > apple-touch-icon

### ISSUE THREAD

**Issue by coliff** [nextcloud/server#15828]
Currently the Apple Touch icon is defined with:
`<link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">`
It'd be better to use:
`<link rel="apple-touch-icon" href="/core/img/favicon-touch.png">`

`core/templates/layout.base.php`
`core/templates/layout.guest.php`
`core/templates/layout.public.php`
`core/templates/layout.user.php`

the `-precomposed` hasn't been needed since iOS 6.
REF: https://developers.google.com/web/fundamentals/design-and-ux/browser-customization/?utm_source=lighthouse&utm_medium=extension#safari

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by gary-kim** [comment]
I noticed this is marked as a `good first issue`. Can I try it?

**Comment by skjnldsv** [comment]
@gary-kim of course!!
Thanks for your help! :hugs:
