### ISSUE TITLE
Multiple 400 errors while editing/saving text files

### ISSUE THREAD

**Issue by ghtux** [nextcloud/server#15847]
**Steps to reproduce**

1. Open text file
2. Edit file
3. Changes are saved
4. Multiple nginx 400 errors in access log:

IP - - [03/Jun/2019:07:51:15 +0200] "PUT /nextcloud/apps/files_texteditor/ajax/savefile HTTP/2.0" 400 644 "-" "Mozilla/5.0 (Linux; Android 9;...

IP - - [03/Jun/2019:07:51:15 +0200] "PUT /nextcloud/apps/files_texteditor/ajax/savefile HTTP/2.0" 400 644 "-" "Mozilla/5.0 (Linux; Android 9; ...

IP - - [03/Jun/2019:07:51:14 +0200] "PUT /nextcloud/apps/files_texteditor/ajax/savefile HTTP/2.0" 400 644 "-" "Mozilla/5.0 (Linux; Android 9;...

IP - - [03/Jun/2019:07:51:12 +0200] "PUT /nextcloud/apps/files_texteditor/ajax/savefile HTTP/2.0" 400 644 "-" "Mozilla/5.0 (Linux; Android 9;...

**Expected behaviour**

No errors in access log while editing/saving file. 

**Actual behaviour:**

Lots of Nginx errors

**Server configuration**

Operating system: Raspbian

Webserver: nginx/1.10.3 (fpm-fcgi) Reverse proxy, Nextcloud in subdir. 

Database: mysql

PHP version: 7.3

Nextcloud version: 16.0.1

Updated from an older Nextcloud/ownCloud or fresh install: update from 15.0.8 to 16.0.1

Where did you install Nextcloud from: official Nextcloud stable release

**Comment by kesselb** [comment]
Still see that issue? `files_texteditor` is replaced with `text` now.
