### ISSUE TITLE
9.0.54 Release Archive missing 3rdparty Folder content

### ISSUE THREAD

**Issue by jpaechnatz** [nextcloud/server#1584]
Tried to Upgrade our 9.0.53 to 9.0.54. No download via Download on the nextcloud download page.
No Link like: https://download.nextcloud.com/server/releases/nextcloud-10.0.1.tar.bz2

Via github releases, the 9.0.54.tar.gz, 3rdparty Folder is empty. So no upgrading...

**Comment by LukasReschke** [comment]
We don't publish our released code on GitHub. Try https://download.nextcloud.com/server/releases/nextcloud-9.0.54.zip and https://download.nextcloud.com/server/releases/nextcloud-9.0.54.tar.bz2
