### ISSUE TITLE
Swiftmailer broken

### ISSUE THREAD

**Issue by dl8bh** [nextcloud/server#15844]
### Steps to reproduce
1. Trigger an event, that invokes swiftmailer for sending an email
2.
3.

### Actual behaviour
If an event is triggered, that sends an e-mail, this will fail because of swiftmailer "normalizing" correct e-mail-adresses (like nextcloud@example.org) to broken ones (nextcloud@ (domain part missing) ).
Those events include:
- Inviting other users on the same instance to appointments (invitations do not work because of this bug)
- even sending the smtp-test-email in the admin-panel fails because of the very same reason.

### Server configuration

**Operating system**:

**Web server:**
nginx 1.15.9
**Database:**
postgresql
**PHP version:**
PHP 7.1.29
**Nextcloud version:** (see Nextcloud admin page)
16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
From github
**Signing status:**
<details>
<summary>Signing status</summary>

```
empty output
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
root@www-1:~ # sudo -u www php /usr/local/www/nextcloud/occ app:list
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.7.0
  - bookmarks: 1.0.5
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.1
  - dav: 1.9.2
  - deck: 0.6.2
  - encryption: 2.4.0
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_accesscontrol: 1.6.0
  - files_automatedtagging: 1.6.0
  - files_external: 1.7.0
  - files_markdown: 2.0.6
  - files_pdfviewer: 1.5.0
  - files_retention: 1.5.1
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trackdownloads: 1.5.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.1
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - radio: 0.6.5
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.1
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
root@www-1:~ # sudo -u www php /usr/local/www/nextcloud/occ config:list system                                                                                                  
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.de",
            "cloud.example.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.example.de",
        "dbtype": "pgsql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "maintenance": false,
        "loglevel": 4,
        "theme": "",
        "share_folder": "\/Shared",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>
{"reqId":"WtAX2XBqznJuvx1a1cBm","level":4,"time":"2019-06-02T19:54:14+00:00","remoteAddr":"2a02::SNIP","user":"peter","app":"webdav","method":"PUT","url":"\/remote.php\/dav\/calendars\/peter\/personal\/810E01FF-89B8-418B-BDEC-2519DAA90779.ics","message":{"Exception":"Swift_RfcComplianceException","Message":"Address in mailbox given [nextcloud@] does not comply with RFC 2822, 3.6.2.","Code":0,"Trace":[{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php","line":272,"function":"assertValidAddress","class":"Swift_Mime_Headers_MailboxHeader","type":"->","args":["nextcloud@"]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php","line":117,"function":"normalizeMailboxes","class":"Swift_Mime_Headers_MailboxHeader","type":"->","args":[{"nextcloud@":"Peter Muller \u00fcber Nextcloud"}]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/Headers\/MailboxHeader.php","line":74,"function":"setNameAddresses","class":"Swift_Mime_Headers_MailboxHeader","type":"->","args":[{"nextcloud@":"Peter Mueller \u00fcber Nextcloud"}]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleMimeEntity.php","line":600,"function":"setFieldBodyModel","class":"Swift_Mime_Headers_MailboxHeader","type":"->","args":[{"nextcloud@":"Peter Muller \u00fcber Nextcloud"}]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/swiftmailer\/swiftmailer\/lib\/classes\/Swift\/Mime\/SimpleMessage.php","line":213,"function":"setHeaderFieldModel","class":"Swift_Mime_SimpleMimeEntity","type":"->","args":["From",{"nextcloud@":"Peter Muller \u00fcber Nextcloud"}]},{"file":"\/usr\/local\/www\/nextcloud\/lib\/private\/Mail\/Message.php","line":101,"function":"setFrom","class":"Swift_Mime_SimpleMessage","type":"->","args":[{"nextcloud@":"Peter Muller \u00fcber Nextcloud"}]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/dav\/lib\/CalDAV\/Schedule\

</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Is there anything special about your `mail_domain`? Like umlauts, non utf8 characters, many characters or so?

**Comment by dl8bh** [comment]
Really nothing special, 13 normal characters + 3 chars tld (org). The problem appeared after updating to Nextcloud 16. It happens for both from-addresses (invitations in the calendar) and to-addresses (smtp testing tool in the admin panel).

**Comment by dl8bh** [comment]
The only workaround I could find was to deactivate mail notifications for appointments and sharing.

**Comment by kesselb** [comment]
Mind to remove `mail_from_address` and `mail_domain` from your `config.php` and try again?

https://github.com/nextcloud/server/blob/14e8930a5fc4bb27409777866f66911be45936c3/lib/public/Util.php#L258-L288

The code above is used to generate the value for from. Something does not work for your setup.

**Comment by dl8bh** [comment]
That worked for me after purging the redis-cache AND restarting php-fpm.
Don't know, if this has to be considered a bug. 
IIRC I did not put that in the config by hand, maybe a broken migration path somewhen in the past?
Thanks for taking care of this!
