### ISSUE TITLE
External storage quota used

### ISSUE THREAD

**Issue by elpedriyo** [nextcloud/server#15843]
### Steps to reproduce
1. Make a local folder
2. Add that folder with external storage app
3. Modify user quota

### Expected behaviour
If I am not wrong, at the moment the actual size of a external storage folder is not counted in user quota. This is happening only when adding unlimited quota to the user, if not, weird things happends

### Actual behaviour
When setting up a user with 10TB of quota:

![image](https://user-images.githubusercontent.com/3207791/58763939-ba929000-8561-11e9-8116-a2f8568b55b6.png)
Why is there 34.6GB used, when there is nothing on the actual folder of that user? The only thing that user has is the external storage on his dashboard

![image](https://user-images.githubusercontent.com/3207791/58763950-de55d600-8561-11e9-9c01-1ca47e23ef30.png)

Also this message is appearing no matter what quota I select for each user, unlimited or limited:

![image](https://user-images.githubusercontent.com/3207791/58764062-1a3d6b00-8563-11e9-82c5-cf732d19a81d.png)

### Server configuration

**Operating system**: Debian 9.1

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.casamonstruosa.tk:81"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "http:\/\/cloud.casamonstruosa.tk:81",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

**Comment by wiswedel** [comment]
@elpedriyo looks like the following constellation:

* Your primary storage has only about 35 GB capacity, so no matter what you principally grant users (10 TB), they'd never be able to.use it. 
* Thst primary storage is by 95% full with other stuff already (OS etc), that's why you get the warning. 

Can you please check your machine and the capacity of the storage location you configured under 'datadirectory'?

**Comment by elpedriyo** [comment]
Hello,

I have checked and it seems I have plenty of space in where I configured datadirectory:

![image](https://user-images.githubusercontent.com/3207791/58767951-30631f80-8593-11e9-9a68-5fb4ba4d0d52.png)

But yes, the ongoing problem with the space storage of my machine seems to be that I only have 35G left in where the datadirectory is. But the problem with the 95% of storage is almost full is not because of that, it seems to because of this:

![image](https://user-images.githubusercontent.com/3207791/58768516-bc2d7980-859c-11e9-9639-2ab211ce5e76.png)

It seems to be a permissions issue, as inside of that dataset no one is able to write until you go deeper inside of the folder, but nextcloud seems to detect that as a space issue. Is there any way to solve that, by nextcloud guessing that correctly?

Kind regards

**Comment by wiswedel** [comment]
Does the _www-data_ user have full access to those mounted volumes?

**Comment by elpedriyo** [comment]
mmm, no it does not because I do not want people uploading files on that directory, also it is not allowed because it is just the middle dataset of the system storage

**Comment by wiswedel** [comment]
When people aren't supposed to upload files there, what's wrong with the message then?

Also you might wanna have a look at the ACL feature in the Group Folders app. That might be interesting for you regarding special permissions on deeper folders.

**Comment by elpedriyo** [comment]
Well,

The problem is not with the permissions message I last posted. The problem is that when accessing that folder that doesn't have permissions, the 95% of  storage is almost full pops up, when indeed is not a problem of storage, it is just only a permissions problem.

Can we solve this?

Kind regards

**Comment by wiswedel** [comment]
@skjnldsv Do you have a clue?

**Comment by skjnldsv** [comment]
Hum :mag_right: :thinking: 
There is a config to include or not the external storage in the quota iirc.
`quota_include_external_storage` but it's experimental
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=quota_include_external_storage#all-other-configuration-options

**Comment by wiswedel** [comment]
> There is a config to include or not the external storage in the quota iirc.
> `quota_include_external_storage` but it's experimental
> https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=quota_include_external_storage#all-other-configuration-options

@rullzer Is this still experimental? This remark has been in the docs since day one.

**Comment by skjnldsv** [comment]
@wiswedel Roelans is in vacation ;)
cc @blizzz

**Comment by elpedriyo** [comment]
mmmm, sorry guys, but including the external storage in the quota should solve this? This message of full storage, is not poping up on the other external folders in which permissions are allowed, it just pops up when the folder doesn't have permissions.

Kind regards

**Comment by blizzz** [comment]
No idea here and don't have the time to  dive in currently. @icewind1991?

**Comment by elpedriyo** [comment]
BUMP

**Comment by elpedriyo** [comment]
Sorry I do not get it, there is an issue on nextcloud, and you do not have time to solve it?

**Comment by kesselb** [comment]
Mind to add some more information about your setup? I read the description several times but no idea how to reproduce this issue locally. 

- Where is the `datadirectory` located (this is usually part of the config export)
- What are the permissions of `/mnt/archivos`?
- A user with access to `/mnt/archivos` should be able to read `/mnt/archivos/mama`, `/mnt/archivos/paula` and `/mtn/archivos/pedro` but not `/mnt/archivos`?
- Have you tried to add `/mnt/archivos/mama`, `/mnt/archivos/paula` and `/mtn/archivos/pedro` as external storage?

**Comment by elpedriyo** [comment]
Can you please reopen this?

This has not been solved.

Kind regards

**Comment by blizzz** [comment]
@elpedriyo can you add information as asked by @kesselb https://github.com/nextcloud/server/issues/15843#issuecomment-513927968? Then we'll reopen.
