### ISSUE TITLE
Change security handling so ex. Polls can be integrated as Widget in Riot.im

### ISSUE THREAD

**Issue by natrius** [nextcloud/server#15842]
I got redirected here from the Polls Github https://github.com/nextcloud/polls/issues/588#issuecomment-498014524

### What is going wrong?

When trying to include a custom widget where i have to input the URL of the homepage i get the following error:

`This content can not be embedded: X-Frame-Options: SAMEORIGIN`

**Expected behavior**

Allow me to add the poll so users of a channel can vote for something directly instead of having to send the link all the times in case someone new joins the channel, for example.

### Information about your polls installation

**Polls version**  0.10.2
**How did you install this version?** Appstore

### Information about your Instance of Nextcloud/ownCloud
**Nextcloud**
**Which Version?** 16.0.0

I don't think there is much to add, if more info is needed, just ask.

**Comment by skjnldsv** [comment]
This is something for polls directly. Sorry for the ping pong :wink:
