### ISSUE TITLE
Print files since frontend nexcloud. It´s posible?

### ISSUE THREAD

**Issue by ivanozone** [nextcloud/server#15850]
It´s posible to print files jpg and pds in bulk action form frontend of nexcloud?? 
I don´t like use the clientPc .

  

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by j-ed** [comment]
You usually should address this kind of questions in the Nextcloud help forum and not the bug tracker 😉
Nevertheless Nextcloud doesn't contain a print function yet and relies on the web browsers function. So the only way to handle print requests, is to download the files to your desktop and print it there.

**Comment by violoncelloCH** [comment]
as @j-ed said
also I don't think printing functionality for Nextcloud makes much senses...
something like that could be implemented as an app though...

**Comment by ivanozone** [comment]
Thanks but i resolved the problem with add a webdav folder in pc.

---
IVÁN LAFUENTE 
Dirección 
683 173 443 
mail: direccion@aragonmarketing.es

_Aragón__ Marketing Solution S.L._

_Este mensaje y sus adjuntos contienen información confidencial y
reservada dirigida exclusivamente a su destinatario. Si ha recibido este
mensaje por error, se ruega lo notifique inmediatamente por esta misma
vía y borre el mensaje de su sistema. Nótese que el correo electrónico
vía Internet no permite asegurar ni la confidencialidad de los mensajes
que se transmiten ni la correcta recepción de los mismos. Los datos
derivados de su correspondencia se incluyen en un fichero de titularidad
de __Aragón Marketing Solution S.L.__ cuya finalidad exclusiva es
gestionar las comunicaciones de la empresa entendiéndose que usted
consiente el tratamiento de los mismos con dicha finalidad al mantener
tal correspondencia. El ejercicio de sus derechos de acceso,
rectificación, cancelación u oposición puede realizarlo dirigiéndose por
escrito a la dirección Avd. Cesareo Alierta 4, Local 7 - Pasaje
Miraflores | 50008 Zaragoza._ 
_ _ 
_This message and any attachments are confidential and privileged and
intented for the use of the addressee only. If you have received this
communication in error, please notify the sender by replay email and
delete this message from your system. Please note that Internet e-mail
guarantees neither the confidentiality nor the proper receipt of the
message sent. The data deriving from our correspondence with you are
included in a file of  Aragón Marketing Solution_ S.L._ which exclusive
purpose is to manage the communications of the company; under the
understanding that, in maintaining said  correspondence, you authorize
the treatment of such data for the mentioned purpose. You are entitled
to exercise your rights of access, rectification, cancellation and
opposition by addressing such written application to address Avd.
Cesareo Alierta 4, Local 7 - Pasaje Miraflores | 50008 _Zaragoza. 

El 2019-06-03 12:14, violoncello.ch escribió:

> as @j-ed [1] said
> also I don't think printing functionality for Nextcloud makes much senses...
> something like that could be implemented as an app though... 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].
 

Links:
------
[1] https://github.com/j-ed
[2]
https://github.com/nextcloud/server/issues/15850?email_source=notifications&amp;email_token=AGS4AEFOLT3CUSJB7VIGKF3PYTVITA5CNFSM4HSF4Z32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWY6NEA#issuecomment-498198160
[3]

**Comment by ivanozone** [comment]
Thanks but i resolved the problem with add a webdav folder in pc.

---
IVÁN LAFUENTE 
Dirección 
683 173 443 
mail: direccion@aragonmarketing.es

_Aragón__ Marketing Solution S.L._

_Este mensaje y sus adjuntos contienen información confidencial y
reservada dirigida exclusivamente a su destinatario. Si ha recibido este
mensaje por error, se ruega lo notifique inmediatamente por esta misma
vía y borre el mensaje de su sistema. Nótese que el correo electrónico
vía Internet no permite asegurar ni la confidencialidad de los mensajes
que se transmiten ni la correcta recepción de los mismos. Los datos
derivados de su correspondencia se incluyen en un fichero de titularidad
de __Aragón Marketing Solution S.L.__ cuya finalidad exclusiva es
gestionar las comunicaciones de la empresa entendiéndose que usted
consiente el tratamiento de los mismos con dicha finalidad al mantener
tal correspondencia. El ejercicio de sus derechos de acceso,
rectificación, cancelación u oposición puede realizarlo dirigiéndose por
escrito a la dirección Avd. Cesareo Alierta 4, Local 7 - Pasaje
Miraflores | 50008 Zaragoza._ 
_ _ 
_This message and any attachments are confidential and privileged and
intented for the use of the addressee only. If you have received this
communication in error, please notify the sender by replay email and
delete this message from your system. Please note that Internet e-mail
guarantees neither the confidentiality nor the proper receipt of the
message sent. The data deriving from our correspondence with you are
included in a file of  Aragón Marketing Solution_ S.L._ which exclusive
purpose is to manage the communications of the company; under the
understanding that, in maintaining said  correspondence, you authorize
the treatment of such data for the mentioned purpose. You are entitled
to exercise your rights of access, rectification, cancellation and
opposition by addressing such written application to address Avd.
Cesareo Alierta 4, Local 7 - Pasaje Miraflores | 50008 _Zaragoza. 

El 2019-06-03 12:00, j-ed escribió:

> You usually should address this kind of questions in the Nextcloud help forum and not the bug tracker 😉
> Nevertheless Nextcloud doesn't contain a print function yet and relies on the web browsers function. So the only way to handle print requests, is to download the files to your desktop and print it there. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/nextcloud/server/issues/15850?email_source=notifications&amp;email_token=AGS4AEA6SNJHQRKHXJ5BQVLPYTTSBA5CNFSM4HSF4Z32YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWY5IOQ#issuecomment-498193466
[2]
