### ISSUE TITLE
Typo on spanish translation

### ISSUE THREAD

**Issue by gmag11** [nextcloud/server#15851]
### Steps to reproduce
1. Log into Nextcloud server
2. Disconnect Internet conection
3. Wait for reconnection message

### Expected behaviour
Message should say "Problema al cargar la página, volverá a cargar en %n segundo","Problema al cargar la página, volverá a cargar en %n segundos"

### Actual behaviour

Message say "Problema al cargar la página, volverá a cargar en %n segundo","Problema al **cagar** la página, volverá a cargar en %n segundos"

An 'r' is missing in https://github.com/nextcloud/server/blob/a44bb8bdcd9907406c018328cfe171dcb4b0844e/core/l10n/es.json#L96

### Server configuration

**Operating system**: Any

**Web server:** Any

**Database:** Any

**PHP version:** Any

**Nextcloud version:** (see Nextcloud admin page) 

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** 16.0.0.9

**Comment by violoncelloCH** [comment]
translations are handled on transifex
please report this there or better change it directly yourself :)
https://www.transifex.com/nextcloud/
