### ISSUE TITLE
folder namechanges dont apply to shares

### ISSUE THREAD

**Issue by fcmildef** [nextcloud/server#15857]
### Steps to reproduce
1. share a folder with a user 
2. change the name of the folder

### Expected behaviour
The folder should have the same name for both the user that shares it and the one  that receives the share

### Actual behaviour
The name of the folder doesnt change for the user that receives the share, leading to all kinds of problems, ie not being able to revert documents in the folder because the file path is now incorrect.

### Server configuration

**Operating system**:
Ubuntu18.04
**Web server:**
apache2                               2.4.29-1ubuntu4.6  
**Database:**
mariadb-server                        1:10.1.38-0ubuntu0.18.04.1 
**PHP version:**
php7.2-common                         7.2.17-0ubuntu0.18.04.1 
**Nextcloud version:** (see Nextcloud admin page)
16.01
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
tarbal from website

**Comment by skjnldsv** [comment]
@blizzz @juliushaertl @ChristophWurst iirc this is on purpose to avoid confusion, right?

**Comment by juliushaertl** [comment]
Yes, this is actually a feature, that the share recipients can have a different name from the original file. This also helps that sharing a file/folder can also work when the user already has a file/folder with the same name.
