### ISSUE TITLE
Reminders for "Contact Birthdays"?

### ISSUE THREAD

**Issue by steckerhalter** [nextcloud/server#1585]
Since the "Contact Birthdays" calendar is read-only it is also not possible to set reminders for the birthdays which makes it easy to still miss these birthdays.

Could there be added a default reminder like one day in advance or something? I mean it's good to have the calendar but it's main purpose for me should be to help me not to forget birthdays which it now more or less only does by accident.

**Comment by nickvergessen** [comment]
I guess this is similar to https://github.com/nextcloud/server/issues/1505 ?

**Comment by steckerhalter** [comment]
@nickvergessen I have just checked and it seems that now birthdays do have a reminder set "at the start of the event". I guess that should suffice for me. #1505 seems to want to make that configurable if I understand it right so that would be a further plus of course.

Ideally I would be able to configure reminders for contact birthdays freely, probably having the default like now and also allowing to add more reminders or to remove them completely like @nursoda suggests.

I'm closing this in favor of #1505

**Comment by zeigerpuppy** [comment]
setting the default time for reminder of birthdays would be great.
It may also be nice to have the option of disabling reminder or editing the time for each individual contact (perhaps that setting would be logical to put in the contacts app).
