### ISSUE TITLE
Set storage quotas for group

### ISSUE THREAD

**Issue by zerocoolb** [nextcloud/server#15852]
Hi Guys

i know there are couple of Requests regarding the possibility to set a "group quota".

why do i need such a option?
Because i use a shared Nextcloud-Instance without any groupadmins just because of this missing feature.
Groupadmin can actually subscribe as much GB as they want. On a shared-instance this fact enabled groupadmins to oversubscribe quotas to theyr users inside a group.

that is a big issues, since i want to make sure that a group can only use as much GB as i want them to use.
per Example: Customer1 hat 10 Accounts in the Group Customer1Group with a quota of 100GB.
i now want to have a groupadmin in it to manage the group and the accounts. The Groupadmin should be able to change quotas of the Users but only within his GROUP-QUOTA (100GB).

this is today not possible as he can subscribe as much GB as the Storage is available. For a Sharedinstance with different Customers this is not what i want. i want to have full access of how much a Groupadmin can subscribe to a account.

**Comment by violoncelloCH** [comment]
take a look at this app which handles quotas per group: https://apps.nextcloud.com/apps/groupquota

**Comment by zerocoolb** [comment]
Note: configuring quota is only possible trough the API, no admin interface is currently available

i think that needs to be implemented in the Interface

**Comment by violoncelloCH** [comment]
yeah, it's only possible via API... until now this app targets admins who want to configure this and they should be able to use the cli (occ)... there is not enough time/money to implement everything sadly...
if you want a GUI for this app, feel free to contact it's maintainer, implement it and create a PR :)
