### ISSUE TITLE
Webdav access with application password and restricted folders

### ISSUE THREAD

**Issue by kaystrobach** [nextcloud/server#15863]
**Is your feature request related to a problem? Please describe.**

I want to allow an application the access to a defined folder within my account.
Other folders should be restricted

**Describe the solution you'd like**

let me created application passwords for webdav, which allow to restrict the published folders and the permissions on that folder

**Describe alternatives you've considered**
second account, does not scale and creates a lot of overhead

**Additional context**
used to provide the folders to lern management systems or others third party systems.

**Comment by skjnldsv** [comment]
Ideally that should go with theshare link and is already possible.
You can share a folder and you'll be able to access it via webdav with the url `https://cloud.domain.com/public.php/webdav/` and the combo username = token, pasword = share password.

**Comment by skjnldsv** [comment]
This crosses https://github.com/nextcloud/server/issues/19700 as well
As it would make snse to be able to get the share with something like 

https://cloud.domain.com/public.php/dav/TOKEN
