### ISSUE TITLE
VerifyMountPoint doesnt allow to place a share within a share

### ISSUE THREAD

**Issue by landryb** [nextcloud/server#15860]
in the context of #12548, i want to "place" a share within a share, so that i can present a nice folder tree to users which have access to a group share.

Looking at the code in https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/SharedMount.php#L89, if i create a share and manually update `file_target` to point at '/subdir/foo/bar' where subdir is another share, the code in VerifyMountPoint doesnt see it as an existing dir (recipientView->is_dir returns false) and thus tries to update `file_target` with a new mount point at the root of the user dir.

I can hack my way around the current code, but to me the fact that recipientView->is_dir() in https://github.com/nextcloud/server/blob/master/apps/files_sharing/lib/SharedMount.php#L97 returns false on '/subdir/foo' (where subdir is another mountpoint) is a bug. The user sees '/subdir/foo' in his hierarchy...

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
