### ISSUE TITLE
Deactivate sharing link

### ISSUE THREAD

**Issue by mupfin** [nextcloud/server#15864]
Hello together =)

I think there is currently no way to set a sharing link as active or not.
This might be helpful if you share something but the file(s) have to be reviewed suddenly.
If you can switch off the link, it don't have to be sent several times.

Not a must-have but maybe a nice feature =)

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, there is currently no plans to implement such a feature. Thus I will close this ticket for now. This is simply not on our roadmap for the near future. 

We already have [far too options](https://github.com/nextcloud/server/issues/12178) for public links and sharing in general.
Such option would receive too little use from our users. :/
It is better to directly remove the link share, you will avoid forgetting about disabled shares and it will avoid cluttering the ui with unused entries. :)

Thanks a lot for the suggestion anyway, I really appreciate it. :hugs:
