### ISSUE TITLE
Problem to open Contacts etc. with Edge Browser

### ISSUE THREAD

**Issue by XBrainBug** [nextcloud/server#15887]
Hello,

i can not open galery, contacts, activitys, talk or else with the edge browser…..when i click on it, i see only the waiting symbol but nothing happens. Only files or configurationlink is working. The Problem is since Nextcloud 16. I have 4 installations on Ubuntu 18.04 with Plesk, using Apache or Nginx. On all servers the same problem.

Nextcloud 16.0.1
Server-Version: 10.1.38-MariaDB-0ubuntu0.18.04.2 - Ubuntu 18.04 
Windows 10 Pro 1809
![Anmerkung 2019-06-06 144509](https://user-images.githubusercontent.com/38700928/59033754-b6b88380-8869-11e9-8e98-4aeafa3e2b4c.jpg)

**Comment by skjnldsv** [comment]
Hello!
I will need your browser console log to investigate this issue.
Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by XBrainBug** [comment]
Hello, here is the log:

HTML1300: Navigation wurde ausgeführt.
files (1,1)

2CSP14309: Unbekannte Direktive manifest-src in Content-Security-Policy. Die Direktive wird ignoriert.

CSS3121: Die Medienabfrage -ms-viewport ist veraltet.

JQMIGRATE: Migrate is installed, version 1.4.1
main.js (278,474)

OCA.Viewer initialized
viewer.js (154,31)

Legacy browser detected, applying css vars polyfill
merged-template-prepend.js (2121,3)

New search handler registered
search.js (67,4)

37The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

2The select2 library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

19The humanFileSize library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

15The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

could not load recommendation preview [object Event]

HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - https://nextcloud.incova.de/index.php/core/preview?fileId=173860&x=32&y=32

OR

HTML1300: Navigation wurde ausgeführt.
activity (1,1)

2CSP14309: Unbekannte Direktive manifest-src in Content-Security-Policy. Die Direktive wird ignoriert.

CSS3121: Die Medienabfrage -ms-viewport ist veraltet.

JQMIGRATE: Migrate is installed, version 1.4.1
main.js (278,474)

Legacy browser detected, applying css vars polyfill
merged-template-prepend.js (2121,3)

126The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - https://nextcloud.incova.de/index.php/core/preview.png?file=/PCVisit/Leistungsbericht/2019-06-06-120907_96583939.pdf&c=f089de555c1c3ebe13cfa18db4bddaa1&x=150&y=150

HTTP404: NICHT GEFUNDEN: Der Server hat keine Übereinstimmungen für den angeforderten URI (Uniform Resource Identifier) gefunden.
GET - https://nextcloud.incova.de/index.php/core/preview.png?file=/PCVisit/Leistungsbericht/2019-06-06-102219_16723993.pdf&x=150&y=150&c=6029023c3bca33f51a7ddce28076ddce

**Comment by Lars1963** [comment]
I can confirm this with MS Edge on Windows10 Pro 1809
Server: Debian 9.9
NGINX: 1.15.9
PHP: 7.3.5
MariaDB: 10.3.15
Nextcloud: 16.01.1

````HTML1300: Navigation wurde ausgeführt.
files (1,1)

2CSP14309: Unbekannte Direktive manifest-src in Content-Security-Policy. Die Direktive wird ignoriert.

CSS3121: Die Medienabfrage -ms-viewport ist veraltet.

JQMIGRATE: Migrate is installed, version 1.4.1
main.js (278,474)

OCA.Viewer initialized
viewer.js (154,31)

Legacy browser detected, applying css vars polyfill
merged-template-prepend.js (2121,3)

New search handler registered
search.js (67,4)

2The escapeHTML library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)

querying Whats New data was successful: nocontent
main.js (223,1257)

undefined
main.js (223,1257)

11The humanFileSize library is deprecated! It will be removed in nextcloud 19.
main.js (750,43)`````

**Comment by skjnldsv** [comment]
Yep, I can reproduce as well.
Clicking the text works, but the icon not.

**Comment by XBrainBug** [comment]
Yes, the text works, i do not know that is different between text and icon and i do not test it!
