### ISSUE TITLE
Can't Update Server on Mac

### ISSUE THREAD

**Issue by Justintime50** [nextcloud/server#15885]
### Steps to reproduce
1. Try updating Nextcloud via the web interface. Any browser, any update, server hosted on Mac.

### Expected behaviour
The update process should go through without getting caught at this step shown.

### Actual behaviour
Every time I've tried updating Nextcloud via the web interface, it gives me the following error. I always have to update manually. It states there is a `.DS_Store` file hindering the update process. This has been the case since Nextcloud 12 at least.

![Screen Shot 2019-06-05 at 9 47 19 PM](https://user-images.githubusercontent.com/39606064/59005974-e9686a80-87dc-11e9-83f3-0492c020dad0.png)

### Server configuration

**Operating system**:
MacOS 10.14.5

**Web server:**
Nginx

**Database:**
MySQL

**PHP version😘*
7.2

**Nextcloud version:** (see Nextcloud admin page)
14.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Trying to update

**Where did you install Nextcloud from:**
Official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.0.1
  - activity: 2.7.0
  - cloud_federation_api: 0.0.1
  - comments: 1.4.0
  - dav: 1.6.0
  - federatedfilesharing: 1.4.0
  - federation: 1.4.0
  - files: 1.9.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - support: 1.0.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "justinpaulhammond.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/justinpaulhammond.com\/nextcloud",
        "dbtype": "mysql",
        "version": "14.0.1.1",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "filelocking.enabled": false,
        "debug": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no - hard drive is encrypted with FileVault though

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
There are no commands defined in the "ldap" namespace.
```
</details>

### Client configuration
**Browser😘*
Safari

**Operating system:**
MacOS 10.14.5

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Failed to load resource: the server responded with a status of 500 ()
/updater/index.php
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
The updater checks for unexpected files and `.DS_Store` is not expected (it's created by macos). I guess the right place to report this "issue" is: https://github.com/nextcloud/updater. If you want to help https://github.com/nextcloud/updater/pull/183 might be a starting point.

**Comment by Justintime50** [comment]
Thank you, I'll try over there. Didn't realize there was an updater repo!
