### ISSUE TITLE
GDPR: Implementation of the right to data portability

### ISSUE THREAD

**Issue by Shen** [nextcloud/server#15883]
According to GDPR every user has the right to "receive the personal data concerning him or her, which he or she has provided to a controller, in a structured, commonly used and machine-readable format and have the right to transmit those data to another controller without hindrance from the controller to which the personal data have been provided" (https://gdpr-info.eu/art-20-gdpr/).
Currently, Nextcloud offers the possibility to send the cloud manager a data export request or a data deletion request via the App Data Request. However, it is not possible to export or completely delete all of a user's data easily.

A menu item in the settings would be useful where you can choose a complete/partial data export as well as a complete data deletion for a single user. In the case of a data export, a link would have to be sent to the user by e-mail, via which he can download the data export. In the case of data deletion, the last action before e-mail deletion would be to send the user an e-mail of successful deletion.

In addition, there should be a data import function so that the previously exported user data can be re-imported in another or the same instance.

Related: https://github.com/nextcloud/data_request/issues/17

**Comment by Utopiah** [comment]
I'm shocked that this does not receive any attention. NextCloud references in `/settings/user/privacy/` that "Users should always be able to extract their data from the service at any time without experiencing any vendor lock-in." from the [User Data Manifesto 2.0](https://userdatamanifesto.org) and also showcases [GDPR compliance](https://nextcloud.com/gdpr/) but in practice using NextCloud own suggestions from https://nextcloud.com/signup/ one ends up locked within a provider with no easy way out, practical speaking locked-in.

For example a NextCloud provider replied that "requires admin and root access to the server. On your Nextcloud Single account, you do not have admins rights and you cannot access the database." again being against the very quote showcase on NextCloud website and instances.

**Comment by Utopiah** [comment]
Apparently there is an app for that https://apps.nextcloud.com/apps/data_request so it's technically feasible but a design decision not to be in core by default?

**Comment by szaimen** [comment]
Related: #15216

**Comment by joshtrichards** [comment]
Fixed a long time ago via https://github.com/nextcloud/user_migration
