### ISSUE TITLE
Make NextCloud Token Valid for RocketChat

### ISSUE THREAD

**Issue by SibeeshVenu** [nextcloud/server#15886]
### Description:

I have both @RocketChat and @nextcloud installed on my Virtual Machine. I understand that there is a mutual partnership between NextCloud and RocketChat, is there any way I can make the token I get from NextCloud valid for RocketChat as well. In this way I can make sure that user have to login only one time to my custom application.

I tried to do the SSO using SAML configuration but I was not able to achieve the same, that is the reason why I am trying this way. Any help is really appreciated.

### Server Setup Information:

Version of Rocket.Chat Server: 1.0.2
Operating System: Linux, UCS (4.4-0 errata0 (Blumenthal))
Number of Running Instances: 1
NodeJS Version: v8.11.4
MongoDB Version: 3.6.12

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. 
 If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
