### ISSUE TITLE
Help Required: OCS Share API (for an APP)

### ISSUE THREAD

**Issue by yward** [nextcloud/server#15884]
Can someone help me with a snippet to get a forced download public link for a file?

here's my current code using webdav, which obviously doesn't work as webdav links are not public:
```
 OCA.MSOfficeViewer.FileClick = function (fileName, context) {
        var downloadUrl = context.fileList.getDownloadUrl(fileName);
        var currentUrl = encodeURI(context.fileList.linkTo() + '?path=' + context.dir);
        var onedrive = "https://view.officeapps.live.com/op/view.aspx?src=https://yournextcloud.com";
	var linkElement = onedrive + downloadUrl;
//rest of the code goes here, basically uses var linkElement to display the file in an external office viewer
```

What I need basically is for the current file, generate a public link and make a variable = the generated link.
I saw OCS share documentation but it's not very helpful.

**Comment by kesselb** [comment]
Please don't open a new issue for every question. Github is not a chat ...
