### ISSUE TITLE
Size of folders is not showing when Storage is on Amazon S3

### ISSUE THREAD

**Issue by jfha73** [nextcloud/server#15882]
Hey guys,

I'm putting this as a Feature Request instead of a bug because I think it just needs to be improved.

When we have External Storage configured for Amazon S3, the folders are not showing their size, instead they show Pending, I see the same behavior in Amazon S3, but I can see the sizes if I click on Action and then click to see the see the total size, so I think it has to do with the API.

Thanks.

**Comment by jfha73** [comment]
Let me add to this that even though NextCloud . does creates folders/files properly in S3, when you try to delete them, in some cases it won't delete them and it locks the folder/file so it can't be deleted, so the folder/file has to deleted using the S3 console.

This is what the Log says about it:

Aws\S3\Exception\S3Exception: Error executing "DeleteObjects" on "https://s3.us-east-1.amazonaws.com/bucketname.s3.amazon.com?delete"; AWS HTTP error: Client error: `POST https://s3.us-east-1.amazonaws.com/bucketname.s3.amazon.com?delete` resulted in a `400 Bad Request` response: <?xml version="1.0" encoding="UTF-8"?> <Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed (truncated...) MalformedXML (client): The XML you provided was not well-formed or did not validate against our published schema - <?xml version="1.0" encoding="UTF-8"?> <Error><Code>MalformedXML</Code><Message>The XML you provided was not well-formed or did not validate against our published schema</Message><RequestId>1ED1DAF32775DC8E</RequestId><HostId>6GV2L+P6Cat0dCdD7rdl1UJ142aixn/unbueG794xvqZiD+OplezsjMF04LwJjK3V6d/MlU5s/A=</HostId></Error>

**Comment by zarko-a** [comment]
bump, anyone? 

@jfha73 Did you ever find a resolution for `DeleteObjects` ... `MalformedXMLThe XML you provided was not well-formed` issue? 

We are encountering the same problem running the latest version as of now (18.0.3.0) for a external S3 storage.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by santosh-goundar** [comment]
we are having same issue, folder size and modified date doesn't show for the folders with S3 as backend,  even we checked by upgrading NC version to 21.0.4, let me know if any further information required 

Server configuration
Operating system: Linux 5.4.0-1039-aws x86_64
PHP version: 7.4.16
Nextcloud version: 20.0.8

**Comment by santosh-goundar** [comment]
can we have update please
