### ISSUE TITLE
Version is not the same as versionstring

### ISSUE THREAD

**Issue by biva** [nextcloud/server#1589]
### Steps to reproduce
1. Install the last version from scratch
2. Type this in the command line: sudo -u www-data php /var/www/html/nextcloud/occ status

### Expected behaviour
Something like this:
  - installed: true
  - version: 10.0."something"
  - versionstring: 10.0.1
  - edition:

### Actual behaviour
  - installed: true
  - version: 9.1.1.5
  - versionstring: 10.0.1
  - edition:

The version number indicates v9. Why ?
In addition, why is there an empty "edition" line?

I found some related issues and pages but I didn't find the answer:
- https://github.com/nextcloud/server/issues/537
- https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

### Server configuration
Ubuntu 16.04.1 LTS - x86_64
Server version: Apache/2.4.18 (Ubuntu)
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )
mysql  Ver 14.14 Distrib 5.7.15, for Linux (x86_64) using  EditLine wrapper

**Comment by LukasReschke** [comment]
> The version number indicates v9. Why ?

v9.1 is the internal code for 10.0

> In addition, why is there an empty "edition" line?

That was used by ownCloud for the enterprise edition.

**Comment by biva** [comment]
Thank you!
That's fine for me, but would we want to explain that on https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule or somewhere else in the documentation?
