### ISSUE TITLE
Vue dialogs

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#15891]
cc @ChristophWurst 

Relevant: https://github.com/nextcloud/nextcloud-vue/issues/408

Closes #6601

**Comment by georgehrke** [comment]
@skjnldsv Shouldn't this ticket be in the nextcloud-vue repo?

**Comment by skjnldsv** [comment]
No, because this is about the OC.Dialog implementation.
The nextcloud-vue repo is about the component itself ;)

**Comment by ChristophWurst** [comment]
We can still have them in nextcloud-vue and re-export in server if really needed. I would keep the number of OC.Dialog APIs as minimum as possible.

**Comment by ChristophWurst** [comment]
Maybe we just need more description to understand what this ticket is about @skjnldsv :wink:

**Comment by skjnldsv** [comment]
@ChristophWurst well, just replace OC.Dialog? What can I tell more? :thinking:

**Comment by georgehrke** [comment]
Shouldn't we try to deprecate OC.Dialog and let it die eventually?
It's enough if there is an equivalent in vue-components, i don't see a need to ship it in the server

**Comment by georgehrke** [comment]
(I forgot there is `OC.dialogs.filepicker`. That we should definitely keep)

**Comment by skjnldsv** [comment]
> It's enough if there is an equivalent in vue-components, i don't see a need to ship it in the server

Well, I'll agree against it by saying this would force everyone to use vue.
If I have a tiny script with pure javascript (which is far better than having a full vue app to compile) that takes 10 lines because it require two checkboxes and a dialog, I would say we should keep a standard.

The dialog component could contain lots of things, and therefoe require a vue component (standard)
But the use cases on server are simple and should be something like: password input, confirm dialog, duplicate file dialog. (anything else?)

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/nextcloud-dialogs/issues/301
