### ISSUE TITLE
php-imagick on RHEL 8 removed

### ISSUE THREAD

**Issue by E-Fail** [nextcloud/server#15900]
Hi Guys,

I have opened a support ticket at RedHat to officially confirm that "php-imagick" was removed from RHEL 8. It was removed and never come back because the weak security. Is there anything else that Nextcloud could use?

**Comment by j-ed** [comment]
It might be of interest, that the use of imagick is already discussed [**here**](https://github.com/nextcloud/server/issues/13099).
