### ISSUE TITLE
Updating user settings is quite slow

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#15915]
### Steps to reproduce

1. Get a demo Nextcloud instance at https://demo.nextcloud.com/ (or simply use your own)
2. Log in as `admin` / `admin`
3. Head over to your user settings (`/settings/user`)
4. Enter your email address in the `Email` field
5. Wait for it to finish the saving process (`PUT /settings/users/admin/settings`)

### Expected behaviour

- Updating the settings should be reasonably fast (< 1 second)

### Actual behaviour

- Saving is extremely slow (7 – 10 seconds)

**Comment by markuman** [comment]
The entire users menu (just list, filter/search when doing sharing) is very slow.  
We got ~150 users.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by markuman** [comment]
It's improved with NC21, but searching is still slow (~300 users).  
The user status api is also slow.

`https://box.lekker.de/ocs/v2.php/apps/user_status/api/v1/statuses/<username>`  
sometimes the request is fast, sometimes (with the same username) the request took ~10 seconds

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
