### ISSUE TITLE
[NC 15.0.8] On close Videoplayer, current position in file list is forgotten

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#15914]
[NC 15.0.8] On close Videoplayer, the current position in the file list is not remembered. 
It is very annoying when playing successive video files

### Steps to reproduce
1. Use a folder with lots of video files (long enough to force a vertical scrollbar and scrolling of the file list).   
2. Select and Play a video file near the bottom of the file list.
3. Stop the video file.

### Expected behaviour
Current position in the file list is remembered and therefore the ability to play the successive video file. 

### Actual behaviour
The file list is reset and returned to the top position. So you need to search for the next video to play in the file list.

**Comment by skjnldsv** [comment]
Fixed with newest viewer
