### ISSUE TITLE
Translation Error in German

### ISSUE THREAD

**Issue by quotengrote** [nextcloud/server#15910]
### Steps to reproduce
1. Goto Files App
2. Select Folder
3. Share Folder through Icon to 1(one) Account
4. Goto Activity Stream
5. Let the Account download the Folder either trough Web or with Desktop Client
6. let the User delete/cut the folder

### Expected behaviour
In activity stream the following text should appear:
"<account_name> hat sich selbst entfernt von <folder_name>"

### Actual behaviour
In activity stream the following text appears:
"<account_name> haben sich selbst entfernt von <folder_name>"

This case is only correct if more than 1 user does that, if only 1 user does that the correct form should be:

### Server conf
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)
</details>

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/59966666-dd401500-951f-11e9-83eb-b4aae14a6df5.png)

https://github.com/nextcloud/server/blob/72f8a58f89312f3fe2d740150491e7b0924a4122/apps/files_sharing/lib/Activity/Providers/Users.php#L97

We should change `{actor} removed themselves from {file}` to `{actor} removed themselve from {file}` because for each user there is a own activity.
 
cc @nickvergessen does that make sense?

**Comment by nickvergessen** [comment]
Fixed with https://github.com/nextcloud/activity/pull/379
