### ISSUE TITLE
files_external notiy raises fclose fwrite errors

### ISSUE THREAD

**Issue by theroch** [nextcloud/server#15917]
### Steps to reproduce
1. create external files with smb, store credentials in db.
2. occ files_external:notify -u myuser -p my_secret 1

### Expected behaviour
Notify if changes are detected

### Actual behaviour
[PHP] Error: fwrite() expects parameter 1 to be resource, boolean given at /path/to/nextcloud/lib/private/Files/Storage/Common.php#204
[PHP] Error: fclose() expects parameter 1 to be resource, boolean given at /path/to/nextcloud/lib/private/Files/Storage/Common.php#205

### Server configuration

**Operating system**:
Ubuntu 18.04.2 LTS

**Web server:**
Apache 2.4

**Database:**
MariaDb

**PHP version:**
PHP 7.2

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
All tests passed
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_accesscontrol: 1.5.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.8
  - files_pdfviewer: 1.4.0
  - files_retention: 1.4.2
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.9
  - fulltextsearch_elasticsearch: 1.2.5
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.4
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:**
LDAP/ActiveDirectory

**Comment by dst21** [comment]
Same issue here with a very similar environment. Even after Upgrading to Nextcloud V. 16.0.1. After starting files_external:notify, somtimes it worked for a minute and then it stopped working.

**Comment by acsfer** [comment]
Closing as it concerns and old Nextcloud version.
Please open a new issue if problem stills in newer Nextcloud versions. 👍
