### ISSUE TITLE
Cannot remove files_external_gdrive

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#15916]
I have installed and tried Google Drive external storage but decided to remove it. I have deleted all the folders both in G-drive and in NC. Deactivated  and removed files_external_gdrive. 
Deactivated files_external. When reactivating files_external - the Google drive reappears with a read error - unknown backend. It and cannot be removed.

**Comment by kesselb** [comment]
Mind to report this issue to https://github.com/NastuzziSamy/files_external_gdrive?
