### ISSUE TITLE
E-mail notification of activities despite deactivation

### ISSUE THREAD

**Issue by Mululu** [nextcloud/server#15929]
### Steps to reproduce
1. Deactivate e-mail notification
2. Other users share with me a file / folder
3. E-mail will get a file shared with me. (This should not be because emails are disabled)

### Expected behaviour
E-mails about activities should not be sent at all if these are deactivated in the general settings or the respective user.

### Actual behaviour
Activity mails are sent though disabled in the settings

**Nextcloud version:** 16.0.1

**Are you using encryption:** no

**Comment by kesselb** [comment]
Seems related to: https://github.com/nextcloud/server/issues/10312
