### ISSUE TITLE
You don't have permission to upload or create files here

### ISSUE THREAD

**Issue by CHazz** [nextcloud/server#15941]
everything worked long years ok, but since the update i have this error .. everything is set up fine

I'm sorry I'm not writing down details ... but I think they're not that important

both php and nginx are set to www-data, this is also the data folder of nextcloud and everything at 777

NC 15 + 16

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you think this is some bug use the issue template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md (it's impossible to reproduce any issue without it - your)

**Comment by cfranz** [comment]
I have the same issue after upgrading to 16.0.2. Changed the permissions of the data-folder to 777, nothing changed. Also tried with a fresh user, same problem. After some trial and error I noticed the following:

- drag and drop of files into nextcloud is not working, I get the message "You don’t have permission to upload or create files here"
- creating a new folder via menu works fine, I also see this via ftp
- drag and drop a file into the new folder brings the same error message as above
- when I upload a file using the menu everything works without error

Maybe there is something wrong with the drag and drop. Have you checked uploading a file through menu?

**Comment by kesselb** [comment]
@cfranz https://github.com/nextcloud/server/issues/16238

**Comment by cfranz** [comment]
Thanks, haven't found this before. Seems to be the problem I have ;)

**Comment by kesselb** [comment]
Yes. I renamed the other issue now to make it easier to find.
