### ISSUE TITLE
Exception on automatic unsharing when encryption is activated

### ISSUE THREAD

**Issue by frlan** [nextcloud/server#15945]
When encryption is activated I'm getting an exception with JSON-log to my logfile in case of an share expires. Example:

{index} {"Exception":"Error","Message":"Call to a member function getPath() on null","Code":0,"Trace":[{"file":"\/srv\/nc\/lib\/private\/Encryption\/Update.php","line":104,"function":"getPath","class":"OC\\Files\\Filesystem","type":"::","args":[557348]},{"file":"\/srv\/nc\/lib\/private\/Encryption\/HookManager.php","line":39,"function":"postUnshared","class":"OC\\Encryption\\Update","type":"->","args":[{"id":"324","itemType":"file","itemSource":557348,"shareType":3,"shareWith":"","itemparent":null,"uidOwner":"xxx","fileSource":557348,"fileTarget":"\/mypicture.jpg","deletedShares":[{"id":"324","itemType":"file","itemSource":557348,"shareType":3,"shareWith":"","itemparent":null,"uidOwner":"xxx","fileSource":557348,"fileTarget":"\/mypicture.jpg"}]}]},{"file":"\/srv\/nc\/lib\/private\/legacy\/hook.php","line":106,"function":"postUnshared","class":"OC\\Encryption\\HookManager","type":"::","args":[{"id":"324","itemType
 ":"file","itemSource":557348,"shareType":3,"shareWith":"","itemparent":null,"uidOwner":"frlan","fileSource":557348,"fileTarget":"\/mypicture.jpg","deletedShares":[{"id":"324","itemType":"file","itemSource":557348,"shareType":3,"shareWith":"","itemparent":null,"uidOwner":"xxx","fileSource":557348,"fileTarget":"\/mypicture.jpg"}]}]},{"file":"\/srv\/nc\/lib\/private\/Share20\/LegacyHooks.php","line":80,"function":"emit","class":"OC_Hook","type":"::","args":["OCP\\Share","post_unshare",{"id":"324","itemType":"file","itemSource":557348,"shareType":3,"shareWith":"","itemparent":null,"uidOwner":"xxx","fileSource":557348,"fileTarget":"\/mypicture.jpg","deletedShares":[{"id":"324","itemType":"file","itemSource":557348,"shareType":3,"shareWith":"","itemparent":null,"uidOwner":"frlan","fileSource":557348,"fileTarget":"\/IMG_20190603_153746_927.jpg"}]}]},{"file":"\/srv\/nc\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php","line":212,"functi
 on":"postUnshare","class":"OC\\Share20\\LegacyHooks","type":"->","args":[{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"},"OCP\\Share::postUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"\/srv\/nc\/3rdparty\/symfony\/event-dispatcher\/EventDispatcher.php","line":44,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[[{"__class__":"OC\\Share20\\LegacyHooks"},"postUnshare"]],"OCP\\Share::postUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"\/srv\/nc\/lib\/private\/Share20\/Manager.php","line":986,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Share::postUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"\/srv\/nc\/lib\/private\/Share20\/Manager.php","line":1295,"function":"deleteShare","class":"OC\\Share20\\Manager","type":"->","args":[{"_
 _class__":"OC\\Share20\\Share"}]},{"file":"\/srv\/nc\/lib\/private\/Share20\/Manager.php","line":1279,"function":"checkExpireDate","class":"OC\\Share20\\Manager","type":"->","args":[{"__class__":"OC\\Share20\\Share"}]},{"file":"\/srv\/nc\/apps\/files_sharing\/lib\/Controller\/PublicPreviewController.php","line":69,"function":"getShareByToken","class":"OC\\Share20\\Manager","type":"->","args":["rYJJoXJSyYoQM96"]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/Middleware\/PublicShare\/PublicShareMiddleware.php","line":50,"function":"isValidToken","class":"OCA\\Files_Sharing\\Controller\\PublicPreviewController","type":"->","args":[]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/Middleware\/MiddlewareDispatcher.php","line":95,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\PublicShare\\PublicShareMiddleware","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\PublicPreviewController"},"directLink"]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/
 Http\/Dispatcher.php","line":98,"function":"beforeController","class":"OC\\AppFramework\\Middleware\\MiddlewareDispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\PublicPreviewController"},"directLink"]},{"file":"\/srv\/nc\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\PublicPreviewController"},"directLink"]},{"file":"\/srv\/nc\/lib\/public\/AppFramework\/App.php","line":140,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\PublicPreviewController","directLink",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"}]},{"file":"\/srv\/nc\/core\/routes.php","line":179,"function":"dispatch","class":"OCP\\AppFramework\\App","type":"->","args":["PublicPreviewController","directLink"]},{"function":"{closure}","class":"OC\\Route\\Router","type":"->","args":["*** sensit
 ive parameters replaced ***"]},{"file":"\/srv\/nc\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"Closure"},"*** sensitive parameter replaced ***"]},{"file":"\/srv\/nc\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/s\/rYJJoXJSyYoQM96\/preview"]},{"file":"\/srv\/nc\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/srv\/nc\/lib\/private\/Files\/Filesystem.php","Line":896,"CustomMessage":"--"}

Seen it at least at 15.x with Debian Stable and it appears that the share link is not working anymore. So maybe just some cleanup that fails.

**Comment by frlan** [comment]
I still can see this kind of issue with 18.0.3

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
