### ISSUE TITLE
Does not work in Microsoft Edge or Internet Explorer

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#15957]
### Steps to reproduce
Log in to site in one of these browsers. Files opens. Klick on any other Icon 

### Expected behaviour
The other app should be activated and opened

### Actual behaviour
I get only a spinning wheel

## Server configuration detail

**Operating system:** Linux 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64

**Webserver:** nginx/1.15.9 (fpm-fcgi)

**Database:** mysql 10.3.14

**PHP version:** 

7.3.4-1+ubuntu18.04.1+deb.sury.org+3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.1 - 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** No - fresh install

**Where did you install Nextcloud from:** I used script from c-rieger

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.7.1
 - audioplayer: 2.7.0
 - calendar: 1.7.0
 - carnet: 0.16.2
 - circles: 0.17.3
 - cloud_federation_api: 0.2.0
 - cms_pico: 0.9.8
 - comments: 1.6.0
 - contacts: 3.1.3
 - dashboard: 6.0.0
 - dav: 1.9.2
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - files: 1.11.0
 - files_clipboard: 0.7.1
 - files_external: 1.7.0
 - files_markdown: 2.0.6
 - files_pdfviewer: 1.5.0
 - files_readmemd: 1.0.4
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - gallery: 18.3.0
 - groupfolders: 4.0.2
 - guests: 1.0.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.15.1
 - notes: 2.6.0
 - oauth2: 1.4.2
 - ojsxc: 3.4.4
 - onlyoffice: 2.1.10
 - password_policy: 1.6.0
 - polls: 0.10.2
 - provisioning_api: 1.6.0
 - registration: 0.4.6
 - richdocuments: 3.3.8
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.2
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.10.1
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_notifications
 - afterlogic
 - data_request
 - drawio
 - dropit
 - encryption
 - event_update_notification
 - federation
 - files_antivirus
 - files_external_gdrive
 - files_videoplayer
 - group_everyone
 - groupquota
 - news
 - nextcloud_announcements
 - notifications
 - ownbackup
 - phonetrack
 - privacy
 - quicknotes
 - recommendations
 - social
 - sociallogin
 - socialsharing_email
 - support
 - user_ldap
 - user_sql
 - workflow_pdf_converter

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "ununtu1804bas",
        "korskyrkan-intra.dedyn.io"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.1.1",
    "overwrite.cli.url": "https:\/\/korskyrkan-intra.dedyn.io",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 14,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\PDF",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "log_rotate_size": 104857600,
    "logfile": "\/var\/nc_data\/nextcloud.log",
    "logtimezone": "Europe\/Berlin",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "preview_max_x": 1024,
    "preview_max_y": 768,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "rewrite_url": true,
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "trashbin_retention_obligation": "auto, 7",
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "external",
        "admin_notifications",
        "ransomware_detection",
        "files_clipboard"
    ],
    "data-fingerprint": "8c86ffd3d78ad5e9797e9f5bea084b9a",
    "has_rebuilt_cache": true
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36 Edge/17.17134

**Operating system:** Windows 10, updated

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here[PHP] Error: Undefined index: log-detail at /var/www/nextcloud/apps/issuetemplate/lib/Detail.php#59

POST /apps/issuetemplate/render
from 192.168.1.1 by NCadmin at 2019-06-14T09:20:36+02:00
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by terrytibbles** [comment]
Does it work in other browsers? What if you use the [demo](https://demo.nextcloud.com/), do you get the same problem?

**Comment by rollanders** [comment]
I use Chrome and my sites - and the Demo site - works instantly as expected. 
 
The demo-site does not work in Edge or Internet Explorer. I get the same result as described above. The Files app opens, but for the other apps I get a spinning wheel.

**Comment by georgehrke** [comment]
> The Files app opens, but for the other apps I get a spinning wheel.

Then please open tickets in the corresponding apps. If the files app works, Nextcloud itself works with IE.

Please not that all apps aim to support IE and or Edge

**Comment by skjnldsv** [comment]
@georgehrke No, this is about https://github.com/nextcloud/server/issues/15887
This is not an issue with the app itslef

**Comment by georgehrke** [comment]
Ahhh ok. I didn't get what spinning wheel @rollanders is talking about.

@rollanders Screenshots are always helping when talking about UI bugs :) 

Anyway, as @skjnldsv pointed out. Duplicate of #15887
