### ISSUE TITLE
Cannot delete any files uploaded to S3 external storage

### ISSUE THREAD

**Issue by alexboly** [nextcloud/server#15950]
### Steps to reproduce
1. Upload file
2. Check file is available online
3. Delete file

### Expected behaviour
File should be deleted

### Actual behaviour
An error "Error deleting "filename"" is displayed

I tried running sudo nextcloud.occ files:scan --all but the output is 
"Exception during scan: A non-numeric value encountered"

### Server configuration

**Operating system**: Ubuntu 18.04.2 LTS

**Web server:** from snap

**Database:** from snap

**PHP version:** from snap

**Nextcloud version:** 15.06

**Updated from an older Nextcloud/ownCloud or fresh install:** I think updated from ownCloud

**Where did you install Nextcloud from:** snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - bookmarks: 1.0.5
  - bookmarks_fulltextsearch: 1.2.0
  - calendar: 1.6.5
  - camerarawpreviews: 0.7.0
  - carnet: 0.15.6
  - checksum: 0.4.2
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.1
  - dav: 1.8.2
  - deck: 0.6.2
  - drawio: 0.9.3
  - dropit: 0.2.1
  - encryption: 2.3.0
  - end_to_end_encryption: 1.1.0
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_antivirus: 2.1.0
  - files_external: 1.6.0
  - files_fulltextsearch: 1.2.6
  - files_fulltextsearch_tesseract: 1.2.3
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.4.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - fulltextsearch: 1.2.6
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - metadata: 0.9.0
  - news: 13.1.6
  - nextcloud_announcements: 1.4.0
  - notes: 2.6.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - polls: 0.10.2
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.3
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.10.1
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - twofactor_u2f: 2.1.3
  - unsplash: 1.1.3
  - workflow_pdf_converter: 1.0.1
  - workflow_script: 1.0.1
  - workflowengine: 1.5.0
Disabled:
  - dashboard
  - files_inotify
  - flowupload
  - sociallogin
  - user_ldap
  - user_saml

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.mozaicworks.com",
            "mozaicworks.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.8.1",
        "overwrite.cli.url": "https:\/\/cloud.mozaicworks.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "maintenance": false
    }
}

</details>

**Are you using external storage, if yes which one:** s3

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 67

**Operating system:** Ubuntu 18.04.2 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Hey, still seeing this issue?

**Comment by alexboly** [comment]
I solved it by changing the s3 permissions. It's still happening intermittently though, but I imagine it's a different issue.
