### ISSUE TITLE
Do not truncate shared .txt files when displayed

### ISSUE THREAD

**Issue by gerroon** [nextcloud/server#15951]
Hi

It would be so nice if the shared .txt files are not trucated when browsed via a shared link. This happens with text files that are a bit longer and it  makes it inconvenient for the viewer

thanks

**Comment by kesselb** [comment]
Sounds similar to https://github.com/nextcloud/server/issues/7907. Would you mind to describe your feature request or problem in more detail? A screenshot could help. Thank you :+1:

**Comment by gerroon** [comment]
@kesselb

Just share a .txt file that is long enough that it does not fit into the screen space. Share it, and open the share url. You will see that the page only shows little bit of the text file, and you need to download the file to see the whole thing.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/acf0ca15414fa17ae5ccc2a7d123f83cf5a2192d/apps/files_sharing/js/public.js#L161-L169

We only request the first 1000 bytes for a text file. I guess we should limit it (because it's only a preview) but a higher value sounds good to me. Most of the image previews are much bigger than 1kb so something like 10000 bytes should be fine for text files. 

cc @jancborchardt @skjnldsv what do you think?

**Comment by gerroon** [comment]
HI
Yeah that kind a limit makes sense for binary type files but it would be really nice if basic text file can be seen in the given url fully.

Imagine you share a longish text hoping that person you share to will see the whole thing. So she shares the link, the other person opens it on their phone. Now they have to download the txt file open in a text editor etc. This doesn ot have to be a longish process for such simple format.


thanks

**Comment by jancborchardt** [comment]
Since the share is text, why do we truncate it at all? I’d say we should show the whole txt file. cc @MorrisJobke @rullzer

**Comment by kesselb** [comment]
Sounds good to me. I can only think of one case:

1) Take nextcloud-16.0.1.zip and rename to nextcloud-16.0.1.txt
2) Upload and share it
3) Your browser tries to preview a 100mb text file ...

**Comment by MorrisJobke** [comment]
> Since the share is text, why do we truncate it at all? I’d say we should show the whole txt file. cc @MorrisJobke @rullzer

At some point we need to truncate it. But yes 1 kB is quite low.

**Comment by jancborchardt** [comment]
@kesselb do you want to open a pull request for it then? :)
