### ISSUE TITLE
Theming app does not allow header logo to be resized

### ISSUE THREAD

**Issue by terrytibbles** [nextcloud/server#15955]
**Nextcloud version:** 15.0.8

Using the default logo or the header logo in the theming app results in an over-sized logo. It'd be useful to be able to set some of the dimensions of this image file, especially if it is SVG.

I'd suggest using the 'height' attribute.

**Comment by terrytibbles** [comment]
I'm not sure the number of upvotes is an indication of how important an issue is. This version of Nextcloud is no longer supported, but the issue may still be there. If it does exist, I might issue a PR and fix it myself.

The issue you linked to is not related to this issue.

**Comment by szaimen** [comment]
> I might issue a PR and fix it myself.

Would be great if you could do that! :)

**Comment by skjnldsv** [comment]
Fixed on 25, this is contained in the header now
