### ISSUE TITLE
Save files as random filename and store the filename elsewhere (maybe database)

### ISSUE THREAD

**Issue by BH4EHN** [nextcloud/server#15953]
**Is your feature request related to a problem? Please describe.**
As I know, currently Nextcloud stores file on disk using the real filename. This commonly won't cause problem. 
But in some case
- when use external storage, I don't want the external storage provider knows what I'm storing. Of course I can use server side encryption, but I want to make it further to the filename
- some filename may contains invalid character for the hosting filesystem or the filename length exceeds the hosting filesystem limit

**Describe the solution you'd like**
Maybe provider an option to save file as random filename (like UUID, and store the real filename in database) and can not turn off after turns on (just like the server side encryption).

**Describe alternatives you've considered**
Or make it an option of the server side encryption module.

**Additional context**
N/A

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years.
