### ISSUE TITLE
Mail app doe not send, shouldn't use "pilelining"

### ISSUE THREAD

**Issue by Bubbelb** [nextcloud/server#1596]
### Steps to reproduce
1. Nextcloud 10.0.[0 & 1], mail app (Nginx)
2.OpenSMTPD mail server behind Nginx mail proxy.
2. SMTP Server uses STARTTLS on port 587
3. Sending mail renders error message: "Server error"

### Expected behaviour
Mail should send...

### Actual behaviour
Mail not sent...
Error message:
`500 5.5.1 Invalid command: Pipelining not supported`
Error message from horde_smtp.log

Rainloop mail functions OK

### Server configuration
**Operating system**: ArchLinix

**Web server:** Nginx (Reverse Proxied through another Nginx Host)

**Database:** MariaDB

**PHP version:** 7.0

**Nextcloud version:** 10.0.0 and 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Owncloud 6

**Where did you install Nextcloud from:** Archlinux User Repository (Package NextCloud)

**Signing status:**
<details>Bas Bleeker
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
Mail
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MariusBluem** [comment]
Hi @Bubbelb,

Thank you for reporting issues back to Nextcloud 👊 You'll find the **mail**-repository (where the issue should be opened) here: https://github.com/nextcloud/mail

In this repository (and its issue-tracker) we are only collecting issues from the Nextcloud server (the files-app, the DAV-backend, ...) 😉

**Comment by Bubbelb** [comment]
Oh, I missed that. Sorry. Will open a bug report on the mail app. Thanx.
