### ISSUE TITLE
Restrict capabilities and access rights by device

### ISSUE THREAD

**Issue by mmccarn** [nextcloud/server#15968]
**Is your feature request related to a problem? Please describe.**
I believe that support for "approved devices" or "full access devices" could improve data security and decrease data leakage by reducing accidental download or offline caching of cloud content on unapproved devices.

"unapproved devices" might be user cell phones, personal computers, office computers that do not have full disk encryption enabled, etc.

**Describe the solution you'd like**
I would like to have the ability to define "full access" devices.  This list should support
* manual entries - so that server admins can manage the list
* enable/disable LDAP integration - should devices joined to the server's LDAP domain (if configured) be given full access?
* IP addresses and networks - allowing admins to 'allow' their local LAN, or to 'allow' systems connecting through a VPN with a known IP address, etc.
* blacklisted items - items included in one or more of the groups above that should not have full access
* New device default - should new devices be given full access by default, or restricted access? (Or should the default be controlled by group membership of the user?)
* ability to view a list of approved devices that have connected in the past, with a button to add any device listed to the blacklist.  Moving a system from 'approved devices' to 'blocked devices' should generate a notification to admins reminding them that they may need to perform a data audit on the device.

Effective user access to any content would be the user's personal access masked by the device's access.

"full access" devices would have the same level of access that all devices now have by default - controlled by the users' rights.

"unauthorized devices" would have access rights restricted to prevent data leak to the local device.  These devices should be unable perform any function that leaks data onto the local device (download, edit, print, etc) (Should this list include 'share'?)

**Describe alternatives you've considered**
I have not seen anything controlling access rights at the device level yet.

I suspect that end-to-end encryption gets me close to this but still leaves control in the hands of the user instead of the admin.

I've customized the onlyoffice app on my testbed system to prevent downloading, printing or editing ([Expose Onlyoffice document permissions in config](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/93) ) -- but I'd like those restrictions to apply only for unapproved devices.  That is, users should be able to use Onlyoffice to the full on their work computer, while being unable to edit the same documents on their personal computer or cell phone.

**Additional context**
I have a group of users that wants to share detailed PII among themselves.  They have historically done this with word documents attached to emails, and now want to switch to using NextCloud.  I am foreseeing data leakage since the sharing is done using msword documents, which get downloaded by default to whatever system the user is using when they look at the document.

Currently, on an iPhone with both the nextcloud app and Microsoft Mobile Word installed, selecting a doc opens a preview -- I don't know if this constitutes a data leak or not.

A complete solution would also require a device identification system that would prevent users from copying the "full access" device id to another device.

**Comment by wiswedel** [comment]
@mmccarn Have you considered using the File Access Control app?

https://apps.nextcloud.com/apps/files_accesscontrol

**Comment by mmccarn** [comment]
@wiswedel I looked at it a year or more ago, but did not reconsider it for this project.  I'll take a look and see if it's a fit.

**Comment by wiswedel** [comment]
@mmccarn Could you please close this issue if you found your requirements covered by File Access Control?
Thanks.

**Comment by szaimen** [comment]
I am going to close this issue since File Access Control should cover this usecase.
Please feel free to reopen if it doesn't.
