### ISSUE TITLE
Is webcal link a "live" link or only a copy of current state? 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#15967]
This has been asked for many times. In the issue "Share NC Calendar with Google Calendar - No Updates! #706" it is claimed that the "https://mydomain.com/nextcloud/remote.php/dav/public-calendars/XXXXXXXXXXXXXXXX?export link is always up to date."
This may be true, but it is still an export link, which I suppose means it is not "live", ie does not provide new events.
Google claims that if there is a "prenumeration" to a link that provide "live" information it should work.
Is there any such possibility in NC? Does the webcal link provide additional live information about changes done or only a copy of the current state at the moment it was constructed?  

**Is your feature request related to a problem? Please describe.**
1. I create a calendar in NC. I share it with Google calendar through a webcal link. The events from  the calendar appears in the Google calendar OK. 
2. I add new event to the NC calendar. I assume they should appear in the Google calender. But they do not. I have to create a new Google calendar based on a new webcal link. 
3. This issue has been discussed many times. There is a misunderstanding that the Google calendar is slow to react because of  a "cache". The change does not appear.
4. According to Google the Google calendar shoul automatically update if the webcal link is changed. I wonder if the webcal link only gives the current state and does not change when new events are added.

**Describe the solution you'd like**
I wouöd like the Google calendar to be synced with the NC calendar

**Describe alternatives you've considered**
I can do the other way - make a Google calendar that is imported to NC and that shows the new events that is added to the Google calendar. It works. But It would be better for the group if the other way around would work.

**Comment by kesselb** [comment]
Would you mind to check the referenced issue again? Is "706" the right one? Looks unrelated to your question for me.

**Comment by rollanders** [comment]
Correct it is https://github.com/nextcloud/calendar/issues/706

I got an answer that this issue is related to the server and not the calendar

**Comment by kesselb** [comment]
Mind to edit your initial post and use the feature request template: https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE/Feature_request.md?

**Comment by kesselb** [comment]
curl -I "https://demo.nextcloud.com/looj8eiw/remote.php/dav/public-calendars/z4sdNJW2MH33j3pW?export"

```
HTTP/1.1 200 OK
Date: Sat, 15 Jun 2019 13:24:47 GMT
Server: Apache
Strict-Transport-Security: max-age=15768000
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Security-Policy: default-src 'none';
X-Frame-Options: SAMEORIGIN
Content-Disposition: attachment; filename="z4sdNJW2MH33j3pW-2019-06-15.ics"
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Download-Options: noopen
X-Permitted-Cross-Domain-Policies: none
Referrer-Policy: no-referrer
Content-Type: text/calendar;charset=UTF-8
```

Compared to a calendar from another application (which works fine with google calendar):

1) A proper expires header
2) `X-PUBLISHED-TTL:PT4H` in `VCALENDAR` (https://stackoverflow.com/questions/538081/set-update-limits-on-icalendar-feed)

This might be a starting point for further triage ...

cc @georgehrke

**Comment by georgehrke** [comment]
We should probably have both. `X-PUBLISHED-TTL` and the new standard `REFRESH-INTERVAL`
https://tools.ietf.org/html/rfc7986#section-5.7

**Comment by georgehrke** [comment]
I'm not really sure what refresh rate we should propagate. It heavily depends on the use-case.
There will be calendars updated multiple times an hour and that should at most be cached one hour.
Others are updated merely once in a couple of months and a refresh rate of one hour would just cause unnecessary load on the server.

cc @tcitworld

**Comment by georgehrke** [comment]
> https://github.com/nextcloud/server/issues/15967#issuecomment-502596363

ping @tcitworld :)

**Comment by tcitworld** [comment]
I think we should always follow the `X-PUBLISHED-TTL` and `REFRESH-INTERVAL` properties for individual calendars so that people are able to have an always up-to-date calendar if needed, and set a high enough default (something like 6h ?) value.
Admins should be able to override this value through `config.php` for instance.

I feel like people will ask for a per-subscription setting in the calendar app though, I don't know of clients supporting either properties.

**Comment by georgehrke** [comment]
@tcitworld This is not about subscribing to remote calendars, it is about the webcal feed of public shared calendars from Nextcloud. :)

**Comment by tcitworld** [comment]
Oops, should have read the entire issue. 😑

Since there's currently no value I think it should be set too high in case people notice and complain. What about a value of 3 hours ? Of course, still configurable by the admin through `config.php`.
