### ISSUE TITLE
OAuth provider not returning to the correct redirection URL

### ISSUE THREAD

**Issue by SibeeshVenu** [nextcloud/server#15962]
I have configured the OAuth provider in Nextcloud with the redirect URL of my RocketChat application. But the redirection is not happening after I login. It is redirecting to the `https://{FQDN}/nextcloud/apps/files/?dir=/&fileid=61` instead of `https://{FQDN}/rocketchat/_oauth/nextcloud`. Please see the images below. 

**Nextcloud**

![nextcloud](https://user-images.githubusercontent.com/4262147/59515632-d54cf900-8ebf-11e9-984e-547e2b040983.png)

**RocketChat**

![rocketchat](https://user-images.githubusercontent.com/4262147/59515634-d847e980-8ebf-11e9-88e3-8664912666f9.png)

### Expected behaviour

Should redirect to the redirect URL set in the settings

### Actual behaviour

 It is redirecting to the `https://{FQDN}/nextcloud/apps/files/?dir=/&fileid=61` instead of `https://{FQDN}/rocketchat/_oauth/nextcloud`

### Server configuration

**Operating system**: Linux

**Database:** PostgreSQL 9.6.13 on x86_64-pc-linux-gnu, compiled by gcc (Debian 6.3.0-18 + deb9u1) 6.3.0 20170516, 64-bit

**PHP version:** 7.2.15

**Nextcloud version:**  15.0.7

**Comment by skjnldsv** [comment]
cc @rullzer
