### ISSUE TITLE
File picker dialog shows empty create action box

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#15966]
![https://user-images.githubusercontent.com/925062/59440105-b2a2dd80-8df6-11e9-9b45-4a6157db791a.png](https://user-images.githubusercontent.com/925062/59440105-b2a2dd80-8df6-11e9-9b45-4a6157db791a.png)

When the actions list is empty, we should not show it at all. This seems to be files app related, as it works fine in the avatar picker of the personal settings.

**Comment by szaimen** [comment]
@juliushaertl could you please advice where this would need to be fixed in the code? Maybe it is simple enough so that I can fix it...

**Comment by juliushaertl** [comment]
Could be enough to just make sure the hide() is not called on `.button-add` but on the parent `.actions.creatable` in  https://github.com/nextcloud/server/blob/3e624dc39966f54c6d418eee2e8141fc5c21f751/core/src/OC/dialogs.js#L322-L325 but just a quick guess and not tested.

**Comment by juliushaertl** [comment]
Seems fixed
