### ISSUE TITLE
Hide "Direct Login" when using SSO/SAML

### ISSUE THREAD

**Issue by markymark171** [nextcloud/server#15978]
**Is your feature request related to a problem? Please describe.**
We primarily use SSO/SAML with Azure AD. We only have 3 admin accounts that can login directly. It would be great to hide this option but still be able to login locally. It would prevent confusion for other users trying to direct login.

**Describe the solution you'd like**
To be able to login direct by appending something to the URL, ie nextcloud.example.com?=direct=true

**Describe alternatives you've considered**
Placing a small link elsewhere on the page that's not as pronounced.

**Additional context**
N/A

**Comment by ChristophWurst** [comment]
Please report at https://github.com/nextcloud/user_saml
