### ISSUE TITLE
Lock updates to only current major release

### ISSUE THREAD

**Issue by markymark171** [nextcloud/server#15979]
**Is your feature request related to a problem? Please describe.**
Currently no matter which update option you pick, it's possible you will eventually be forced to use the built-in updater to move to the next major release even though updates to the existing major version are still released.

**Describe the solution you'd like**
To be able to lock updates to the current major version, ie 15.x

**Describe alternatives you've considered**
N/A

**Additional context**
Currently 15.x updates still appear as 16.x is released, but soon I will have to update to 16.x even though additional 15.x updates may still be released.

**Comment by kesselb** [comment]
cc @MorrisJobke I think there is a discussion about this topic somewhere on github?

**Comment by MorrisJobke** [comment]
That's what the production channel does. Always provide the minor version and if on the latest minor version provide the next major. In this way you can be always on the latest minor but simply do not update when a major update is provided.
