### ISSUE TITLE
Microdata in invite mail

### ISSUE THREAD

**Issue by hydrargyrum** [nextcloud/server#15989]
It would be nice if HTML messages for event invite contained markup microdata with event info. Microdata is specific HTML attributes containing event metadata, like accept/refuse URLs, event description and date.

It doesn't change the mail view, it's metadata that some email clients will interpret to show event info without having to open the email, for example.

See https://developers.google.com/gmail/markup/reference/rsvp-action (despite this doc being on a google site, it's an open standard named JSON-LD https://en.wikipedia.org/wiki/JSON-LD, see also https://diveintohtml5.info/extensibility.html)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
