### ISSUE TITLE
Installation with Postgres Fails With Authentication Error

### ISSUE THREAD

**Issue by mxkramer** [nextcloud/server#15986]
### Steps to reproduce
1. Install PostgreSQL from repositories
2. Create db user and database, with appropriate permissions
3. Copy nextcloud files to the appropriate location
4. Run occ maintenance:install

### Expected behaviour
Nextcloud should be installed.

### Actual behaviour
Installation failed with the following message:

```
Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL:  password authentication failed for user "nextcloud"
FATAL:  password authentication failed for user "nextcloud"
```

Note that password authentication was allowed, and I was able to log in manually to the `nextcloud` database with the `nextcloud` user with `sudo -u www-data psql -U nextcloud nextcloud` using the password.

### Server configuration

**OS:** Armbian (based on Ubuntu 18.04)

**Server:** Odroid HC1 (modified XU4), ARMv7 8-core big.LITTLE

**Database:** PostgreSQL 10.8 (Ubuntu 10.8-0ubuntu0.18.04.1)

**PHP version:** 7.2.19-0ubuntu0.18.04.1

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Official download

**Comment by kesselb** [comment]
How do you call occ maintenance:install?

**Comment by mxkramer** [comment]
I called it with:

```
sudo -u www-data php occ maintenance:install --database "pgsql" --database-name "nextcloud" --database-user "nextcloud" --database-pass "{database pass}" --admin-user "miakramer" --admin-pass "{admin pass}" --data-dir "/data/www/nextcloud/data"
```

**Comment by kesselb** [comment]
Mind to try this patch https://github.com/nextcloud/server/pull/15187?

**Comment by mxkramer** [comment]
No luck, still gives the same error.

**Comment by mxkramer** [comment]
However, I was able to use the web installer. The request times out after filling out the information, but running (my database name is `nextcloud` and db user is `nextcloud`):

```
GRANT ALL PRIVILEGES ON DATABASE nextcloud TO nextcloud;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO nextcloud;
```

Worked, and I have now successfully logged in.
