### ISSUE TITLE
at the end of installation I got Internal Server Error

### ISSUE THREAD

**Issue by znbn** [nextcloud/server#15982]
### Steps to reproduce
1. upload the .zip file on your hosting.aruba.it web space
2. unzip the archive
3. browse the folder and do a fresh install of NC (I used mysql)

### Expected behaviour
to be redirected to /nextcloud/index.php/apps/files/ without any error

### Actual behaviour
Internal Server Error

and reading the error logs:

[Mon Jun 17 12:24:30 2019] [alert] [client 159.xx.xx.xx] /web/htdocs/www.example.com/home/drive/.htaccess: Expected but saw ###> 

### Solution
there is a problem in .htaccess file at line: 

    </IfModule>#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

You have to add a new line character before ####

now it works:

    </IfModule>

    #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

### Server configuration

**Operating system**:

**Web server:** Apache

**Database:** MySql 5.7

**PHP version:** 7.1

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by kesselb** [comment]
Still an issue? Seems to be correct with Nextcloud 18.
