### ISSUE TITLE
Problem Sharing files (NextCloud 16 - Debian 8.11) - Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services sharing 

### ISSUE THREAD

**Issue by Laederlappen** [nextcloud/server#15990]
### Steps to reproduce
1. Upload file
2. press share button
3. try typing in a username to share with

### Expected behaviour
auto fill in...add one or more users

### Actual behaviour
Error Message on top of screan (see title of this issue)

### Server configuration
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.11 (jessie)
Release:	8.11
Codename:	jessie

**Web server:**
Server version: Apache/2.4.10 (Debian)

**Database:**
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 1181033
Server version: 10.0.38-MariaDB-0+deb8u1 (Debian)

**PHP version:**
PHP 7.2.14-1+0~20190113100657.14+jessie~1.gbpd83c69 (cli) (built: Jan 13 2019 10:30:36) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
16.0.1 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
started with 14....a while ago

**Where did you install Nextcloud from:**
official download and install from scratch

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - bruteforcesettings
  - encryption
  - files_external
  - user_ldap
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxx",
            "xxx2"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/xxx2",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "maintenance": false,
        "mysql.utf8mb4": true,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "trashbin_retention_obligation": 1,
        "0": 3,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": 1,
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Related to: https://github.com/nextcloud/server/issues/15058

I run into the same issue today. It's related to utf8mb4. Please read https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html to learn more about this topic.

A) **Database server support utf8mb4** enable it `'mysql.utf8mb4' => true,` in `config.php`.

B) **Database server do not support utf8mb4** disable it `'mysql.utf8mb4' => false,` in `config.php`.

After A or B run `php occ maintenance:repair` to fix the broken tables.

**Comment by sebastienserre** [comment]
if I disable utf8mb4, it's working but in the main settings I've the error message as I do not use the 4bytes. 
So How to make the both working together ?

**Comment by kesselb** [comment]
> So How to make the both working together ?

- Change the mariadb or mysql configuration to support utf8mb4
- Enable utf8mb4 in nextcloud again and run occ maintenance:repair

> I've the error message

Emojis are very common these days. If you want to use these in calendar or somewhere else you need utf8mb4. That's the reason for the warning. 

I've seen many of these reports lately and most of them are mysql.utf8mb4 enabled without a proper database setup. Do you have any idea how we could improve our documentation (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html) to make this more clear?

**Comment by sebastienserre** [comment]
I think we can improve by saying in which file we can find these mariadb or Mysql settings (in main server or linux distro)

As I followed this page and continue to not working.

**Comment by sebastienserre** [comment]
it's OK
here for example
you should add path to the right file
https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html#mariadb-10-2-or-earlier

I added
innodb_large_prefix=true
innodb_file_format=barracuda
which was missing on /etc/mysql/mariadb.conf.d/50-server.cnf

**Comment by kesselb** [comment]
Thanks :+1: 

@Laederlappen feel free to reopen the issue if it does not work for your.
