### ISSUE TITLE
Nextcloud docker image untrusted domain

### ISSUE THREAD

**Issue by Mehrez27** [nextcloud/server#15991]
Hi!
I tried to deploy nextcloud in a cluster kubernetes I used this helm chart: “https://gitlab.com/kanzari.1993/nextcloud.git” with ingress controllers enabled that I have set it with the necessary configurations (DNS update, hostname and the certificate provider https) but when I access through the hostname that I indicated in the ingress.yaml file I receive this warning : 
![e626995e76969bd14c9c1530fc696f616bc5a231](https://user-images.githubusercontent.com/36052172/59674240-cbc2da00-91ba-11e9-942d-6603c7d3e24a.jpeg)
 Does anyone have an idea about how to solve this issue?
Thanks in advance!

**Comment by da3dsoul** [comment]
in ./data/config/config.php, there is a trusted server setting, where you may add domains (with wildcard support). Note that the ./data depends on how you mapped your volumes.

**Comment by da3dsoul** [comment]
It should look something like this:
![screenie](https://i.imgur.com/Cf7XFBh.png)

**Comment by tikoflano** [comment]
Take notice that Nextcloud docker (https://github.com/nextcloud/docker) lets you set this with the environment variable `NEXTCLOUD_TRUSTED_DOMAINS`

> One or more trusted domains can be set by environment variable, too. They will be added to the configuration after install.
>
> * NEXTCLOUD_TRUSTED_DOMAINS (not set by default) Optional space-separated list of domains

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
