### ISSUE TITLE
Unable to upload new favicon via theming app

### ISSUE THREAD

**Issue by nextclouduser** [nextcloud/server#15998]
### Steps to reproduce
1. Fresh install of Centos 7.6, cPanel v80.0.18 and Nextcloud 16.0.1
2. Trying to upload a favicon.ico file from the Theming app
3. Infinite loading turning wheel, failure

### Expected behaviour
A new favicon.ico file should be uploaded and seen in the browser

### Actual behaviour
Infinite loading turning wheel, failure

### Server configuration

**Operating system**:
Centos 7
**Web server:**
Apache 2.4.39(cPanel)
**Database:**
mysql 5.7.26
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Web installer via setup-nextcloud.php
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 2.1.2
  - twofactor_u2f: 3.0.0
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.casa.energy"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "loglevel": 2,
        "log_type": "file",
        "logfile": "nextcloud.log",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/nextcloud.casa.energy"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.9.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "373"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "0.2.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.3",
            "types": ""
        },
        "core": {
            "installedat": "1559738900.2443",
            "lastcron": "1560886015",
            "lastupdateResult": "[]",
            "lastupdatedat": "1560883910",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "a26b5800395a495317c8b3ab704db300",
            "shareapi_default_expire_date": "yes",
            "shareapi_enable_link_password_by_default": "yes",
            "shareapi_enforce_links_password": "yes",
            "shareapi_expire_after_n_days": "90",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "generateBirthdayCalendar": "no",
            "installed_version": "1.9.2",
            "sendInvitations": "no",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.13.0",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.3.0",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.1.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.4.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.4.2",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.6.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.4.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "enforcePasswordProtection": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "theming": {
            "cachebuster": "7",
            "color": "#99CA3C",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "name": "CaSA",
            "privacyUrl": "https:\/\/casa.energy\/legal\/privacy-policy\/",
            "slogan": "Smart Electricity",
            "types": "logging",
            "url": "https:\/\/nextcloud.casa.energy"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "2.1.2",
            "types": ""
        },
        "twofactor_u2f": {
            "enabled": "yes",
            "installed_version": "3.0.0",
            "types": ""
        },
        "unsplash": {
            "enabled": "yes",
            "installed_version": "1.1.3",
            "types": "",
            "unsplash\/style\/header": "0"
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "",
            "update_check_errors": "0"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome Version 74.0.3729.157 (Official Build) (64-bit)
**Operating system:**
Windows 10 Pro
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```

Error | index | Error: Call to undefined function OCA\Theming\Controller\mime_content_type()/home/nc/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 166:OCA\Theming\Controller\ThemingController->uploadImage()/home/nc/public_html/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Theming\ ... {}, "uploadImage")/home/nc/public_html/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Theming\ ... {}, "uploadImage")/home/nc/public_html/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Themin ... r", "uploadImage", OC\AppFramew ... {}, { _route: "t ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "t ... "})/home/nc/public_html/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { _route: "t ... "})/home/nc/public_html/lib/base.php - line 975:OC\Route\Router->match("/apps/themi ... e")/home/nc/public_html/index.php - line 42:OC::handleRequest()
-- | -- | --

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
settings-admin.js?v=e5ab9020-7:140 Uncaught TypeError: Cannot read property 'data' of undefined
    at HTMLInputElement.fail (settings-admin.js?v=e5ab9020-7:140)
    at e.<computed>.<computed>._trigger (jquery-ui.js:697)
    at e.<computed>.<computed>._onFail (jquery.fileupload.js?v=e5ab9020-7:879)
    at e.<computed>.<computed>._onFail (jquery-ui.js:144)
    at Object.<anonymous> (jquery.fileupload.js?v=e5ab9020-7:913)
    at u (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at k (jquery.js:8266)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by gary-kim** [comment]
Is your issue similar to #15954?

**Comment by nextclouduser** [comment]
Not exactly, uploading any file yields the same result.

**Comment by terrytibbles** [comment]
Are you experiencing any other problems? Can you make any changes in the theming app?

**Comment by nextclouduser** [comment]
I can make plenty of changes that work, namely to the name, web link, slogan, color, legal notice and privacy policy links, those all work. As far as uploading images, that lets me select a file and then I get the never ending circle of loading.

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by nextclouduser** [comment]
Here is the output of me trying to upload a favicon.ico file:

jquery.js:8630 POST https://nextcloud.***.***/index.php/apps/theming/ajax/uploadImage 500 (Internal Server Error)
send @ jquery.js:8630
ajax @ jquery.js:8166
send @ jquery.fileupload.js?v=e5ab9020-7:909
_onSend @ jquery.fileupload.js?v=e5ab9020-7:971
(anonymous) @ jquery-ui.js:144
data.submit @ jquery.fileupload.js?v=e5ab9020-7:677
(anonymous) @ jquery.fileupload.js?v=e5ab9020-7:218
u @ jquery.js:3099
add @ jquery.js:3145
add @ jquery.fileupload.js?v=e5ab9020-7:217
_trigger @ jquery-ui.js:697
(anonymous) @ jquery.fileupload.js?v=e5ab9020-7:1040
each @ jquery.js:374
_onAdd @ jquery.fileupload.js?v=e5ab9020-7:1033
(anonymous) @ jquery-ui.js:144
(anonymous) @ jquery.fileupload.js?v=e5ab9020-7:1238
u @ jquery.js:3099
add @ jquery.js:3145
always @ jquery.js:3246
_onChange @ jquery.fileupload.js?v=e5ab9020-7:1228
(anonymous) @ jquery-ui.js:144
a @ jquery-ui.js:606
dispatch @ jquery.js:4435
_.handle @ jquery.js:4121
settings-admin.js?v=e5ab9020-7:140 Uncaught TypeError: Cannot read property 'data' of undefined
    at HTMLInputElement.fail (settings-admin.js?v=e5ab9020-7:140)
    at e.<computed>.<computed>._trigger (jquery-ui.js:697)
    at e.<computed>.<computed>._onFail (jquery.fileupload.js?v=e5ab9020-7:879)
    at e.<computed>.<computed>._onFail (jquery-ui.js:144)
    at Object.<anonymous> (jquery.fileupload.js?v=e5ab9020-7:913)
    at u (jquery.js:3099)
    at Object.fireWith [as rejectWith] (jquery.js:3211)
    at k (jquery.js:8266)
    at XMLHttpRequest.<anonymous> (jquery.js:8605)

**Comment by kesselb** [comment]
I don't need your browser console sorry :see_no_evil: Do you see the `The PHP module "fileinfo" is missing. It is strongly recommended to enable this module to get the best results with MIME type detection.` warning?

https://github.com/nextcloud/server/blob/d63de5471bf3c8a40bdc9f9e3b5332d2f0b1f2a9/apps/theming/lib/Controller/ThemingController.php#L269

The function `mime_content_type` is related to the `fileinfo` extension. You need this extension to upload an image. 

cc @nextcloud/server-triage @juliushaertl I think its time to make `fileinfo` a required extension :ping_pong:

**Comment by nextclouduser** [comment]
Thank you, that did the trick. However, it still does not accept a file with a .ico extension for the favicon, it tells me it is an unsupported format.

https://docs.nextcloud.com/server/13/developer_manual/core/theming.html states to use .svg/.png to ensure future updates to favicon format, has .ico extension been deprecated?

**Comment by kesselb** [comment]
> has the .ico extension been deprecated?

No but there are some issues with `ico` files: https://github.com/nextcloud/server/pull/15999#issuecomment-503453294

**Comment by nextclouduser** [comment]
Very well, I will follow that. Thank you.
