### ISSUE TITLE
Screenshot Capture from webui

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#15996]
Nextcloud does not have a built-in method for taking screenshots directly from the webui.  Selecting and Capturing a screenshot within the browser would be both extremely useful and flexible, especially if combined with a method for annotating or commenting on any file or folder within Nextcloud ala #2426.  Some possible PHP-based screen capture tools include:

* [PHP documentation on capturing screenshots](https://www.php.net/manual/en/function.imagegrabscreen.php)
* [Myazo](https://github.com/migueldemoura/myazo) is a really nice capture tool that uses PHP and  Python.  [See this post on possible Nextcloud integration](https://github.com/migueldemoura/myazo/issues/10).
* [Screenshotter](https://github.com/lukaswhite/screenshotter) for PhantomJS and PHP

**Comment by kesselb** [comment]
>     * [PHP documentation on capturing screenshots](https://www.php.net/manual/en/function.imagegrabscreen.php)

This would create a screenshot on the server not the client. Something like Myazo could work (or anything else with a webdav integration). I think there is only a little chance that a screenshot from webui feature will be part of nextcloud server in the near feature. The right way to add this feature would be an app.
