### ISSUE TITLE
INSTALL file

### ISSUE THREAD

**Issue by gorankav** [nextcloud/server#16]
An INSTALL file would come in handy in order to ease the installation and lower the support questions about installation.

**Comment by mar1u5** [comment]
There are several ways of installation. For this purpose there is a documentation and our website (https://nextcloud.com) where it is described in detail for several setups (shared hosting, server and appliances) . An INSTALL file is not necessary in my opinion.

**Comment by gorankav** [comment]
I've got this idea earlier. I was not able to find the info then.
Will have to check.

**Comment by jancborchardt** [comment]
Closing because the documentation should be there. Let us know if there’s questions left.

**Comment by jancborchardt** [comment]
Actually a quick-installation process should be listed in the README directly. Something dead-simple which shows how easy it really is like:
1. Download
2. Adjust permissions
3. Finish installation via web interface

**Comment by gorankav** [comment]
This was my idea.

BTW: the web page says: _Tutorials or how-to's	We're working on this! Stay tuned._
...until then some short notes as jancborchardt mentioned would be welcome

**Comment by rullzer** [comment]
Fixed in #1496
