### ISSUE TITLE
CalDAV - Cancelled events are not hidden for users if they do not own the calender

### ISSUE THREAD

**Issue by HerrDietz** [nextcloud/server#16003]
This issue is coupled with the calender app, but since this seems to be an issue with caldav (at least it occures only on synchronized devices) I'm reporting it here, as suggested in the calender bug template.

### Steps to reproduce
1. Create a series  of events in nc calender app as user A
2. Share the calender with another user B
3. for both users: sync calender with their respective android devices using davx5
4. User A deletes an event of the series using androids calender app. The event is hidden in the calendar app (android) and marked as canceled in nc
5. User B syncs calendars. The deleted/canceled event is still shown in googles calendar app in android.

Now this could be an issue with user Bs android device. But switching roles of user A and B will reveal the behavior is exact the same.  

### Expected behaviour
Cancelled events should not be shown on android devices of people the original calender is shared with

### Actual behaviour
cancelled events are hidden only for the owner of the calender but not for other people the calender is shared with (for example family members)

### Server configuration

System is hosted by hetzner.de

**Operating system**: unkown

**Web server:** unkown

**Database:** unkown

**PHP version:** unkown

**Nextcloud version:**16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** unkown

**Where did you install Nextcloud from:** cloud deployment by hetzner

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Calendar version**
```
Calendar 1.7.0
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:** Android

**Comment by georgehrke** [comment]
@HerrDietz What makes you sure this is not a bug in Google calendar?

Generally speaking, unless you set a privacy class to only share events as busy, the event the owner receives via CalDAV is exactly the same event a sharee receives. It is not modified or altered in any way by Nextcloud.

cc @rfc2822

**Comment by rfc2822** [comment]
As far as I know, this should work. For reliable diagnosis on DAVx⁵ side, the exact iCalendar files and logs would be required…

**Comment by georgehrke** [comment]
@HerrDietz Please provide logs as requested by @rfc2822

**Comment by HerrDietz** [comment]
I'm deeply sorry I didn't reply earlier. The issued was indeed resolved when I bought a new device. I suppose it was a bug in the Google calendar version I used.
