### ISSUE TITLE
Chunk files background cleanup task

### ISSUE THREAD

**Issue by J-Doc** [nextcloud/server#16019]
Hello,

First of all long life to Nextcloud, great piece of code 👍 

Could it be possible to adjust background cleanup task for failed uploads ?
It is hardcoded to 1 day, despite value of 'cache_chunk_gc_ttl' setting.

/apps/dav/lib/BackgroundJob/UploadCleanup.php 
line 72
>$time = $this->time->getTime() - 60 * 60 * 24;

>$ttl = \OC::$server->getConfig()->getSystemValue('cache_chunk_gc_ttl', 60 * 60 * 24);
$time = $this->time->getTime() - $ttl;

I think that will be more logical.

Regards,
N.

**Comment by kesselb** [comment]
Makes sense. Mind to share your use case? Do you need a lower or higher value?

**Comment by J-Doc** [comment]
Thanks for your answer @kesselb 

I'm not actually concerned by this use case because all my instances are still in NC15, and I don't have this feature, but I'm preparing future migration. It may be usefull to have a separate setting.

Actually I'm only concerned by the current bug in NC15 that prevent those chunks being correctly purged despite login/logout from webui.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. 
Please reopen if you still want to implement this.
