### ISSUE TITLE
Exposing the default app configuration on the UI

### ISSUE THREAD

**Issue by Croydon** [nextcloud/server#16022]
**Is your feature request related to a problem? Please describe.**
It seems to be possible to set another default app as files via the Nextcloud config file, but I would like to see such an option in the UI exposed.

**Describe the solution you'd like**
Expose an option in the UI which allows to set the default app when opening Nextcloud in the browser. E.g. instead of always seeing the files app I would like to set my calendar default as this is what I want most of the time.

**Describe alternatives you've considered**
- none - 

**Additional context**
This increases productivity and reduces frustration of constantly having to switch the app first and setting specific bookmarks etc.
Also having options exposed on the UI is much more user friendly than only in the config files

**Comment by juliushaertl** [comment]
You can already achieve that by installing the apporder app and making it the default app on your Installation. After that the first app in the list will be opened. I don't think this is something in the server. cc @nextcloud/designers

**Comment by Croydon** [comment]
The app order app let's me rearrange the symbols, but when I'm going to `cloud.example.com` I'm still landing in the files app, despite having the calendar app at the beginning.

**Comment by kesselb** [comment]
Works for me as described by @juliushaertl: https://github.com/juliushaertl/apporder#use-first-app-as-default-app

**Comment by Croydon** [comment]
According to the readme I still need to edit the config file manually to change the default app to app order: https://github.com/juliushaertl/apporder#use-first-app-as-default-app

My entire point was to expose it on the UI

**Comment by kesselb** [comment]
> My entire point was to expose it on the UI

Copy that :see_no_evil: As far as i know only the most common configuration variables are exposed. You need basic linux administration skills anyway so you should be familiar with configuration files.

I'm afraid but in a few months someone will close this issue with a statement like :disappointed:

> As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will keep this ticket closed for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
> 
> If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

You study computer science? If you are familiar with programming you might implement the feature yourself.

1) Setup your development environment https://github.com/nextcloud/server#development-setup-
2) We already change some configuration values from the webui like here: https://github.com/nextcloud/server/blob/92675a606e90a57745ee1059e56d264a3213c954/settings/Controller/MailSettingsController.php#L109

**Comment by jancborchardt** [comment]
How about this: @juliushaertl and I will sit down at the Contributor Week next week (@kesselb will you be there too? :) and talk about if and how we can handle this.

We do keep configuration low, but I do agree that the ability to set the default app is something quite useful, and also pushes our app ecosystem. We can also look into possibly polishing the apporder app and shipping it, much like we did the direct_menu. :)

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
