### ISSUE TITLE
Missing CSS css/settings/xxxx-xxxx-settings.css

### ISSUE THREAD

**Issue by Haelle** [nextcloud/server#16034]
### Steps to reproduce
I have no idea how to recreate it.

### Expected behaviour
http://cloud.example.com/settings/users should display correctly. Other "settings" pages are impacted but this one is unusable :/

### Actual behaviour
The page is not displayed correcty ; one CSS file is having a 404 issue : 
https://cloud.example.com/css/settings/3a76-1b32-settings.css?v=2751cded0383f5e81f895fea4f57766f-c14e52f3-4

Nextcloud.log (full down there)
```
{
  "url":"\/settings\/users",
  "message":"filesize(): stat failed for \/media\/data\/nextcloud\/appdata_ocbiopqso25j\/css\/settings\/3a76-1b32-settings.css at \/opt\/nextcloud\/lib\/private\/LargeFileHelper.php#171"
  [...]
}
```

**The same for `settings.css`, `settings.css.deps` & `settings.css.gzip`. And indeed in `nextcloud/appdata_ocbiopqso25j/css/` the whole `settings` directory is missing.**

I tried `occ maintenance:repair` without any success

### Server configuration

**Operating system**: Raspbian (Debian Stretch)
**Web server:** Nginx
**Database:** Postgres
**PHP version:** 7.3
**Nextcloud version:** Nextcloud 16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh
**Where did you install Nextcloud from:** with this Ansible https://github.com/aalaesar/install_nextcloud
**Signing status:** No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

Defaults' one
```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.alxs.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "https:\/\/cloud.alxs.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "2",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "open_basedir": "\/dev\/urandom",
        "mysql.utf8mb4": "true",
        "updater.release.channel": "production",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "0"
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Ubunut 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
19107:X.X.X.X - - [21/Jun/2019:14:26:49 +0100] "GET /css/settings/3a76-1b32-settings.css?v=2751cded0383f5e81f895fea4f57766f-c14e52f3-4 HTTP/2.0" 404 514 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"saI0T8mAbTyrLIOJVyP1","level":3,"time":"2019-06-21T13:22:46+00:00","remoteAddr":"X.X.X.X","user":"admin","app":"PHP","method":"GET","url":"\/settings\/users","message":"filesize(): stat failed for \/media\/data\/nextcloud\/appdata_ocbiopqso25j\/css\/settings\/3a76-1b32-settings.css at \/opt\/nextcloud\/lib\/private\/LargeFileHelper.php#171","userAgent":"Mozilla\/5.0 (X11; Ubuntu; Linux x86_64; rv:67.0) Gecko\/20100101 Firefox\/67.0","version":"16.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Request URL :https://cloud.example.com/css/settings/3a76-1b32-settings.css?v=2751cded0383f5e81f895fea4f57766f-c14e52f3-4
Method :GET
Address :X.X.X.X:443
HTTP Code : 404 
Version :HTTP/2.0
referent :no-referrer-when-downgrade
```
</details>

**Comment by skjnldsv** [comment]
Hey! :)
Please clear your redis or memcache setup and report back here.
This can happen when there is a file cache conflict.

**Comment by Haelle** [comment]
I spotted in my `config/config.php` maybe a mistake :
`"memcache.local": "\\OC\\Memcache\\APCu"` I changed it to `"memcache.local": "\\OC\\Memcache\\Redis"` (I have Redis installed and a `redis` section setup in `config.php`)

My Nextcloud uses Redis when I stop the service it stop working ;)
So I tried to clear Redis cache with : `redis-cli flushall` & `redis-cli flushdb`

But the problem's still there.

**Comment by skjnldsv** [comment]
Actually memcache.local to apcu should be fine as well.
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/caching_configuration.html?highlight=memcache%20local#id2

Can you do an occ maintnance:repair ?

**Comment by Haelle** [comment]
Done (but already tried), nothgin changed
<details>
<summary>occ maintenance:repair</summary>
Command result

```
 - Repair MySQL collation
     - Not a mysql database -> nothing to do
 - Repair mime types
 - Clean tags and favorites
     - 0 tags of deleted users have been removed.
     - 0 tags for delete files have been removed.
     - 0 tag entries for deleted tags have been removed.
     - 0 tags with no entries have been removed.
 - Repair invalid shares
 - Remove shares of a users root folder
 - Move .step file of updater to backup location
 - Fix potential broken mount points
     - No mounts updated
 - Repair invalid paths in file cache
 - Add log rotate job
 - Clear frontend caches
     - Image cache cleared
     - SCSS cache cleared
     - JS cache cleared
 - Clear every generated avatar on major updates
 - Add preview background cleanup job
 - Queue a one-time job to cleanup old backups of the updater
 - Repair pending cron jobs
     - No need to repair pending cron jobs.
 - Extract the vcard uid and store it in the db
 - Cleanup invalid photocache files for carddav
 - Add background job to cleanup login flow v2 tokens
 - Remove potentially over exposing share links
     - No need to remove link shares.
 - Fix component of birthday calendars
     - 3 birthday calendars updated.
 - Regenerating birthday calendars to use new icons and fix old birthday events without year
     - Repair step already executed
 - Fix broken values of calendar objects
    0 [>---------------------------]
 - Registering building of calendar search index as background job
     - Repair step already executed
 - Registering background jobs to update cache for webcal calendars
     - Added 0 background jobs to update webcal calendars
 - Clean up orphan event and contact data
     - 0 events without a calendar have been cleaned up
     - 0 properties without an events have been cleaned up
     - 0 changes without a calendar have been cleaned up
     - 0 contacts without an addressbook have been cleaned up
     - 0 properties without a contact have been cleaned up
     - 0 changes without an addressbook have been cleaned up
 - Remove activity entries of private events
     - Removed 0 activity entries
 - Fix the share type of guest shares when migrating from ownCloud
 - Copy the share password into the dedicated column
 - Update OAuth token expiration times
 - Add background job to check for backup codes
```
</details>

**Comment by skjnldsv** [comment]
> Done (but already tried),

ah, my bad! :)
Okay, another try then

1. Delete the following: `nextcloud/appdata_ocbiopqso25j/css/`
2. Then do an `occ files:scan-app-data` again
3. Clear redis
4. And restart your webserver (nginx/apache/php)

**Comment by Haelle** [comment]
Nice it came back !

So just for history, command results:
<details>
<summary>occ files:scan-app-data</summary>

```
Scanning AppData for files

+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 73      | 151   | 00:00:02     |
+---------+-------+--------------+
```
</details>

<details>
<summary>Old CSS folder vs newly generated CSS folder</summary>

`tree -LAC 1 css*`
```
css
├── activity
├── core
├── files
├── files_texteditor
├── icons
├── notifications
└── settings
css_old
├── activity
├── core
├── federatedfilesharing
├── files
├── files_texteditor
├── icons
├── notifications
├── privacy
├── support
└── theming
```
</details>

The folders inside are quite different, maybe a Nextcloud update didn't cleared the cache ?

Also `occ files:scan-app-data` help isn't helpful, when I searched by myself, I encountered it via `occ list` I looked at all operations and this one didn't seems helpful at the time maybe changing the description would help ?
Current description : `files:scan-app-data                 rescan the AppData folder`
Right now I suppose it scanned the `nextcloud/appdata_xxxx` and tried to fix it, and it's where CSS files are supposed to be.

**Comment by skjnldsv** [comment]
> I looked at all operations and this one didn't seems helpful at the time maybe changing the description would help ?

what description do you suggest? :)

**Comment by Haelle** [comment]
I don't know what it exactly does, but no only "rescan", but maybe it's also a misunderstanding on me of what imply the word "rescan".
I though a (re)scan would only imply a report and no action, or maybe "indexing" the files.

I would suggest : 
"regenerate/rebuild the AppData folder"

**Comment by skjnldsv** [comment]
@Haelle well, the rescan only index the appdata folder.
But the server autogenerate and populate the appdata folder.
So removing the css and re-indexing the appdata made the server know it had to recompile the css files that were missing (somehow broken in your config)

I'd say the description is good like that then :)
It doesn't re-generate it.
