### ISSUE TITLE
Deleted shares list headers are overlapping the first row of the table

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#16032]
Using Chromium on current master

> ![Bildschirmfoto von 2019-06-21 12-32-21](https://user-images.githubusercontent.com/213943/59916912-c49d0580-9420-11e9-8d76-04011ac70010.png)

cc @skjnldsv

**Comment by GretaD** [comment]
I cannot reproduce this bug anymore. @nickvergessen can you see if exist anymore? Maybe this pull fixed it: https://github.com/nextcloud/server/pull/16366

**Comment by MorrisJobke** [comment]
> I cannot reproduce this bug anymore. @nickvergessen can you see if exist anymore? Maybe this pull fixed it: #16366

Closing. If this is still an issue feel free to reopen it.
