### ISSUE TITLE
Editing text files in mobile browsers doesn't work right. 

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#16047]
### Steps to reproduce
1. Open files 📂 
2. Create a new text file
3. Open text file in a mobile browser
4. Try to type

### Expected behaviour
Should be easy to type and enter text like in any normal text editor. 

### Actual behaviour
New lines disappear when starting to type on the new line. Characters are removed, typed text disappears. 

I'd guess that the problem is that the text editor tries to save the file every typed character. Saving is slower than you type so it reverts to the saved state when saving is done. 

### Server configuration

**Operating system**:
Gentoo
**Web server:**
Apache 2.4.39
**Database:**
Mariadb 10.3.15
**PHP version:**
7.3.6
**Nextcloud version:** (see Nextcloud admin page)
16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Gentoo Portage, then using occ updater
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors found
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - audioplayer: 2.7.1
  - bookmarks: 1.0.6
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - camerarawpreviews: 0.7.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.2
  - dropit: 0.2.1
  - event_update_notification: 0.3.4
  - extract: 1.2.0
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_automatedtagging: 1.6.0
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_external_gdrive: 0.4.0
  - files_fulltextsearch: 1.3.2
  - files_inotify: 0.1.4
  - files_mindmap: 0.0.13
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trackdownloads: 1.5.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - flowupload: 0.1.2
  - fulltextsearch: 1.3.4
  - fulltextsearch_elasticsearch: 1.3.3
  - gallery: 18.3.0
  - group_everyone: 0.1.2
  - groupfolders: 4.0.3
  - impersonate: 1.3.0
  - issuetemplate: 0.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.1
  - metadata: 0.9.0
  - music: 0.9.5
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ocdownloader: 1.7.0
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quickaccesssorting: 1.0.1
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - sharelisting: 0.2.0
  - sharerenamer: 2.6.0
  - socialsharing_email: 1.0.5
  - spreed: 6.0.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - suspicious_login: 1.0.0
  - systemtags: 1.6.0
  - tasks: 0.10.1
  - telephoneprovider: 1.0.2
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - bookmarks_fulltextsearch
  - encryption
  - federation
  - guests
  - radio
  - user_ldap
  - workflow_script
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local, but not where this text file is stored. 

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Opera browser on Android 
**Operating system:**
Android 8
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Gatak** [comment]
![Screenshot_20190623-162515_Opera](https://user-images.githubusercontent.com/1469150/59977737-5a799180-95d5-11e9-9a05-cfc446b2f172.jpg)

**Comment by jospoortvliet** [comment]
Ah, this is for Nextcloud Text? Please report bugs in the right repo:
https://github.com/nextcloud/text/issues - so the developer can track the problem!

Thanks!

**Comment by Gatak** [comment]
Alright. Will do. :)

**Comment by Gatak** [comment]
Update. apparently this belongs to files. https://github.com/nextcloud/text/issues/120#issuecomment-506686156 or?
