### ISSUE TITLE
Create directory button

### ISSUE THREAD

**Issue by artiomn** [nextcloud/server#16042]
When I copy or move files into the directory, I often want to create subdirectory for these files.
Now I need to open another tab in a browser go to the target directory, create subdirectory, return to the previous tab and then move or copy files.
It's very inconvenient.

Please, add "Create directory" button in the copy/move dialog.

**Comment by szaimen** [comment]
I think it is already there. At least in my installation (16.0.1).
![Anmerkung 2019-06-23 132120](https://user-images.githubusercontent.com/42591237/59975635-8e938900-95ba-11e9-9ed6-d13f4b47268a.jpg)

**Comment by artiomn** [comment]
Thanks. It's good. I haven't noticed that, because I use stable version 15.
