### ISSUE TITLE
Privacy: External Connection List

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#16046]
All Connection to devices are listed in a Menu where you are able to add a token for devices.
But if other Add-ons which to use resources from third server these connection are no where listed.

Please add an application part where Nextcloud User and Admin could accept and remove the access from Nextcloud to third resources.

May Add-on writer have to somehow register domains the which to connect in Nextcloud and Ask user if they are agreed with that.

**Comment by Mannshoch** [comment]
I'm not sure If you could reduce this case to up votes and responses. This is more a matter of security and may involve DSGVO (Only that way you are shure (or nextcloud) could be sure about the connections)

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/26089
