### ISSUE TITLE
Nextcloud reporting it is up to date whereas it is not / report wrong version

### ISSUE THREAD

**Issue by Icantcodeatall** [nextcloud/server#1604]
This issues was inspired by my post on the Nextcloud forum : https://help.nextcloud.com/t/confusion-and-problems-regarding-update/3773/5

### Steps to reproduce
Check the version section of the administration page 

Or

Issue : `sudo -u www-data php updater/application.php ` in the next cloud folder

### Expected behavior
It should tell that the 10.0.1 has been release and ask for update.

With updater/application.php it should report version 10.0

If the updater is broken an official statement should be issued to prevent security issues.

### Actual behaviour
It reports it is up to date (10.0) on stable channel on the administration page.

It echoes:` Nextcloud is already latest version` with the cli

updater/application.php echoes:
```
ownCloud updater 1.0 - CLI based ownCloud server upgrades
Checking system health.
 - file permissions are ok.
Current version is 9.1.0.16
No updates found online.
Done
```

### Server configuration
**Operating system**:
Ubuntu Server 14.04
**Web server:**
Nginx
**Database:**
MariaDB/Mysql
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
10.0 or 9.1.0.16 ?
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install.
**Where did you install Nextcloud from:**
From Nextcloud website.
**Signing status:**
???????
**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - external: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - mail: 0.5.3
  - news: 9.0.4
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - piwik: 0.1.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "ocj4ltu5hez3",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/cloud\/data",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "custom_csp_policy": "default-src 'self' stats.flcloud.ovh; script-src 'self' stats.flcloud.ovh 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * stats.flcloud.ovh; font-src 'self' data:; media-src *"
    }
}
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Update log</summary>
```
[info] Execution of upgrade:start command stopped. Exit code is 0
[info] Execution of upgrade:start command started
[info] Execution of upgrade:info command started
[info] Execution of upgrade:info command stopped. Exit code is 0
[info] Execution of upgrade:checkSystem command started
[info] Execution of upgrade:checkSystem command stopped. Exit code is 0
[info] Execution of upgrade:detect command started
[info] ownCloud 9.1.0.16 found
[info] Execution of upgrade:detect command stopped. Exit code is 4
[info] Execution of upgrade:start command stopped. Exit code is 0
```
</details>

**Comment by tflidd** [comment]
@Icantcodeatall : Can you separate the issues? Thirst thing here is a feature request that the occ-command should also check for available updates.

Second thing is the update-notifier. Do a separate issue therefore, it's especially important to provide the list of apps (if the updater-notifier app is enabled). And if there is anything in your logfiles (Nextcloud and webserver).

**Comment by Icantcodeatall** [comment]
Okay let's focus on the actual problem before requesting a feature for the occ-command, I though it was already implemented but obviously I misread the docs.
I have edited the original issue.

I have already given the list of the apps in the issue, do you need something more ?
There is nothing in the Nextcloud or Nginx logs about upgrade.

Manually triggering cron.php doesn't output anything in Nextcloud or Nginx logs.

**Comment by nickvergessen** [comment]
The old updater has problems and therefor does not receive any updates.
With 10.0.1 we replaced the updater and it will in the future notify about updates and be able to perform them. Unluckily due to the nature of the updater code being the problem, there is nothing we can do retro-actively.
Also adding a block post or something and recommend not to use the updater doesn't help. When people see an update button, they will press it.

So bad luck this time. Will work better from 9.0.54, 10.0.1 and 11.0.0 onwards.

**Comment by Icantcodeatall** [comment]
Ok thanks for the reply.
I'm sorry but I find that just
> So bad luck this time.
is a bit deceiving about security. If I'm not wrong, people using pre-10.0.1 version will never get an update ? So you expect them to find out there is an update by themselves.
If you think that's ok then fine, but a short tweet or Facebook post and news on the front page / in the doc could help other admin.

**Comment by nickvergessen** [comment]
Well we have been promoting updates through all of those channels. Nothing more we can do, and as said was fixed with the current cycle, so notifications will be done for the next releases.

**Comment by dajusc** [comment]
@nickvergessen I think you did everything completely right. Bugs happen, and you handled and communicated this one well. Thx!

@Icantcodeatall Thank you too for reporting this issue! This thread saved me quite some time, searching for a solution myself. :)
