### ISSUE TITLE
decryption does not preserve file modification timestamp

### ISSUE THREAD

**Issue by jknockaert** [nextcloud/server#16053]
Running occ encryption:decrypt to decrypt files of a user results in the file modification timestamp being updated. This file metadata should be preserved. File modification time is handled pretty consistently when syncing files, just when decrypting it gets overwritten.
Also a pretty meaningless item is created in the user activity log.
Most likely this should be fixed together with #7283.
@nextcloud/encryption

**Comment by sammo2828** [comment]
Does this help? #19246

**Comment by jknockaert** [comment]
@sammo2828 Thanks. I couldn't test it as I already worked around the issue. And I didn't expect it to be a one-line fix.
Remotely related: decryption adds a lot of nonsense to the activity feed. Perhaps you see a one-line fix to hide these entries?

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by jknockaert** [comment]
I think it's solved by #19246, but I didn't test the solution and neither did I check if it was ever merged in a release.

**Comment by szaimen** [comment]
Then let's close this for now. If it shouldn't work then somebody can create a new issue :)
