### ISSUE TITLE
Notifications shows OC-version-numbers

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#1605]
### Steps to reproduce
1. Install and use NC 10.0.0 (upgraded from NC 9.0.53)
2. Put the new-updater-app-string in config/config.php
```
'updater.server.url' => 'https://updates.nextcloud.org/updater_server/',
```

3. Notification app shows update available for Nextcloud core to version 9.1.1.5, see screenshot:

<img width="308" alt="screen shot 2016-10-01 at 1 04 27 pm" src="https://cloud.githubusercontent.com/assets/8111200/19013674/5580e92a-87d8-11e6-8aef-dd398b8949d2.png">

### Expected behaviour
Show correct version string 10.0.1

### Server configuration
**Operating system**: Debian 8, php7.0 (dot-deb), mariadb, apache

sorry, I don't have full access to the server at the moment to provide all information. Perhaps it's enough like that.

**Comment by MorrisJobke** [comment]
cc @nickvergessen - please use versionString instead of the internal version number ;)

**Comment by nickvergessen** [comment]
Adjusted the milestone, because the notifications are only there starting NC 10
