### ISSUE TITLE
Misleading message in Apache logs about "open_basedir restriction" when directory is not mounted

### ISSUE THREAD

**Issue by JShabtai** [nextcloud/server#16050]
### Steps to reproduce
1.Set "datadirectory" to a location within a mount (e.g. from a NAS)
2. Ensure this path is allowed by the open basedir restrictions 
3. Unmount the mount used in step 1
4. Access the webapp

### Expected behaviour
A useful, or at least less misleading, error message about being unable to access the files

### Actual behaviour
```
[Sun Jun 23 09:26:05.961011 2019] [php7:warn] [pid 800] [client <IP_REMOVED>:39062] PHP Warning:  fileperms(): open_basedir restriction in effect. File(/mnt/nas/media/services/nextcloud/nextcloud.log) is not within the allowed path(s): (/mnt/nas/media/media:/srv/http/:/dev/urandom:/tmp/:/usr/share/pear/:/usr/share/webapps/nextcloud/:/etc/webapps/nextcloud:/mnt/nas/media/services/nextcloud/) in /usr/share/webapps/nextcloud/lib/private/Log/File.php on line 140
```

Notice that the path that is being accessed is actually in the paths allowed by the restriction

Note: These are in the apache logs, there ar no Nextcloud logs as that file was not accessible to be written to

### Server configuration

**Operating system**:
Arch (up to date)

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.3.16

**PHP version:**
PHP 7.3.6

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Arch official package repo

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - extract: 1.2.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 2.6.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.2.4
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MYDOMAIN.COM"
        ],
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "https:\/\/MYDOMAIN.COM",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "loglevel": 0,
        "maintenance": false,
        "theme": ""
    }
}

```
</details>

**Are you using external storage, if yes which one:** NAS mounted locally with NFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:**
Firefox

**Operating system:**
Arch

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Sun Jun 23 09:26:05.961011 2019] [php7:warn] [pid 800] [client <IP_REMOVED>:39062] PHP Warning:  fileperms(): open_basedir restriction in effect. File(/mnt/nas/media/services/nextcloud/nextcloud.log) is not within the allowed path(s): (/mnt/nas/media/media:/srv/http/:/dev/urandom:/tmp/:/usr/share/pear/:/usr/share/webapps/nextcloud/:/etc/webapps/nextcloud:/mnt/nas/media/services/nextcloud/) in /usr/share/webapps/nextcloud/lib/private/Log/File.php on line 140
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No logs
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
```
No logs as the page does not load in this case
</details>

**Comment by kesselb** [comment]
Warning is generated by PHP. I don't know if we can fix anything here. You figured out what's wrong?

**Comment by JShabtai** [comment]
Ah, sorry, if the message is generated by PHP then it probably makes sense to close this, as it's not a Nextcloud issue. 

As for resolving my problem, all I had to do was remount the NFS share. I just thought a more clear error message may help others, but I guess that's a PHP issue. Thanks.
