### ISSUE TITLE
Login button doesn't work

### ISSUE THREAD

**Issue by dr0nygames** [nextcloud/server#16065]
Hi, I'm using nextcloud since a while now and from one moment to the other the login button stoped working in every browser without edge, the funny thing is, if I connect direct on the ip to nextcloud the button works, but when I do it with my domain, it doesn't work. I disabled all non-official apps and it still soesn't work, I have the newest version from nextcloud (16.0.1.). Does anybody have an idea what I can do?

greetings

Patrick

**Comment by kesselb** [comment]
Sounds similar to https://github.com/nextcloud/server/issues/14471

**Comment by dr0nygames** [comment]
Nope, I`m not using an provider, it's my homeserver, so it's one server with one operating system and only one user, other ideas?

**Comment by skjnldsv** [comment]
@dr0nygames Hey!
Can you check the html element of the button?

Right click, inspect and copy paste it here? :)
