### ISSUE TITLE
webdav reports wrong disk capacity and usage

### ISSUE THREAD

**Issue by twatzl** [nextcloud/server#16077]
So I have nc set up on my server, there is about 700GB remaining disk space of a total of 5TB, however when mounting the cloud using webdav under Windows it reports a total capacity of 149GB and usage of 147GB. Both values are complete rubbish.

How did I mount it?
Windows Explorer -> Map Network Drive:
Drive Letter: X:
Folder: The webdav url of nextcloud
And `connect using different credentials` enabled.

When mounting the share under Linux with
`$ sudo mount -t davfs https://cloud.myserver.org/remote.php/webdav/ ./cloud -o rw,uid=1000,gid=1000`

then `df -h` reports a disk space of `4.1TB` and a disk usage of `4.1TB`.

However uploading using the web interface works just fine.

UPDATE: While writing this issue I updated NC from version 15 to version 16 (to make sure the version was not the problem) set a quota and removed the quota again from my user.

Now at least Linux shows a maximum usable disk space of `16E`, which is still completely wrong, but at least it is no longer reported as full. I started the file transfer and I will see if it actually works.

Windows still reports the 149GB capacity.

## Server configuration detail

Operating system: Linux 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 29 14:49:43 UTC 2018 x86_64
Webserver: nginx/1.15.12 (fpm-fcgi)
Database: mysql 10.4.5
PHP version: 7.3.6
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, pdo_sqlite, session, posix, readline, Reflection, standard, SimpleXML, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, exif, gd, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache
Nextcloud version: 16.0.1 - 16.0.1.1

This issue is possibly related to:
#2311
#15865

**Comment by wulfgar93** [comment]
Hello! I can confirm this issue. Got the same problem.

**Comment by cogliostro** [comment]
Can also confirm this issue. Reports as 191GB in windows fwith only 44,9 GB Free. Quota set to 500GB. 

Actual Disk size 500GB. Actual Disk usage 29GB.

**Comment by FLiPp3r90** [comment]
Same problem with NC18. Reports in Windows 65GB free of 199GB. The storage real size is 1,5TB.

**Comment by icewind1991** [comment]
webdav does not provide a way for the client to get the free space from the server, it seems that windows will instead show the used/available space from a local disk instead.

I'm assuming that the linux mounting has a similar fallback.

Either way there isn't anything Nextcloud can do to change this client behaviour
