### ISSUE TITLE
CardDav vcf error 404 if contact was uploaded by carddav client

### ISSUE THREAD

**Issue by allofmex** [nextcloud/server#1607]
### Steps to reproduce
1. connect carddav client (tested on thunderbird (sogo connector) and emClient)
2. create new contact in client
3. contact appears in Nextcloud webinterface
4. try to download vcard by url (get uid from url when contact is clicked in webinterface): (http://example.org/remote.php/dav/addressbooks/users/username/default/123456-abcd-1234-cdef-23847923.vcf)

### Expected behaviour
Download vcf file should start
(its working if contact is created in NextCloud webinterface)

### Actual behaviour
Nextcloud says: "HTTP Error 404 (in Version 9.0 was "Not Found, Card not found, Technical details, Remote Address: ....
Request ID...")
Happens only if contact was created in external carddav client

### Server configuration
Ubuntu 16.04.01

**Web server:**
nginx
**Database:**
10.1.16
**PHP version:**
7.0.11
**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
9.0 before (same behavior)

**Where did you install Nextcloud from:**
docker wonderfall/nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**
calendar, contacts

```

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

$CONFIG = array (

  'datadirectory' => '/nextcloud/data',
  'overwrite.cli.url' => 'http://****.com:8013',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'logtimezone' => 'UTC',
  'installed' => true,
  'maintenance' => false,
  'dbname' => 'nextcloud',
  'dbhost' => '*****',
....
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/nextcloud/apps2',
      'url' => '/apps2',
      'writable' => true,
    ),
  ),
  'theme' => '',
  'loglevel' => 2,
);

**Comment by nickvergessen** [comment]
Will see if I can reproduce this.

I guess you have the contacts app enabled? Which version are you using there?

**Comment by allofmex** [comment]
Contacts app version is 1.4.0.0
(and is enabled)

**Comment by nickvergessen** [comment]
Worked quite fine here with a contact I created on my phone:
`curl -v http://localhost/remote.php/dav/addressbooks/users/admin/contacts/ba3943d3-b3a4-422e-a477-3219d2d6befc.vcf -u admin:admin`

Also the Download button in the contacts app works for me: ⬇️ in the right part of the contact header.

**Comment by allofmex** [comment]
![nextcloud_carddav](https://cloud.githubusercontent.com/assets/22577004/19107367/25f24890-8aec-11e6-9c73-ecfd7e872647.png)
The download button reports different uid than url and carddav response!

**Comment by nickvergessen** [comment]
Well you must use the url that is specified by the parent.
So you should first make a propfind request on the parent:
`curl -X PROPFIND http://localhost/remote.php/dav/addressbooks/users/allofmex/default -u allofmex:<yourpassword>`
The response contains the `href` where you can download the full vcard:
```xml
<?xml version="1.0"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:cal="urn:ietf:params:xml:ns:caldav" xmlns:cs="http://calendarserver.org/ns/" xmlns:card="urn:ietf:params:xml:ns:carddav" xmlns:oc="http://owncloud.org/ns" xmlns:nc="http://nextcloud.org/ns">
 <d:response>
  <d:href>/remote.php/dav/addressbooks/users/admin/contacts/</d:href>
  <d:propstat>
   <d:prop>
    <d:resourcetype>
     <d:collection/>
     <card:addressbook/>
    </d:resourcetype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
 <d:response>
  <d:href>/remote.php/dav/addressbooks/users/admin/contacts/ba3943d3-b3a4-422e-a477-3219d2d6befc.vcf</d:href>
  <d:propstat>
   <d:prop>
    <d:getlastmodified>Wed, 05 Oct 2016 07:11:46 GMT</d:getlastmodified>
    <d:getcontentlength>223</d:getcontentlength>
    <d:resourcetype/>
    <d:getetag>&quot;23c3cdb96029f0f2ae3ca6a0a0f14b69&quot;</d:getetag>
    <d:getcontenttype>text/vcard; charset=utf-8</d:getcontenttype>
   </d:prop>
   <d:status>HTTP/1.1 200 OK</d:status>
  </d:propstat>
 </d:response>
</d:multistatus>
```

In my case above it's:
```xml
<d:href>/remote.php/dav/addressbooks/users/admin/contacts/ba3943d3-b3a4-422e-a477-3219d2d6befc.vcf</d:href>
```
So `http://locahost/remote.php/dav/addressbooks/users/admin/contacts/ba3943d3-b3a4-422e-a477-3219d2d6befc.vcf` downloads the vCard.
