### ISSUE TITLE
Cannot Login after Upgrade

### ISSUE THREAD

**Issue by MVTec** [nextcloud/server#16079]
I wanted to secure docker daemon using TLS,  did following 

- created Certificates
-  restarted docker Server
- containers did not start themselves, so used docker-compose up -d 
- Nextcloud 15.07 got upgraded to 15.08, no issues but I am no more able to login using existing accounts. 

Meanwhile I have tried several options like deleting everything from /var/www/html except data and installing Nextcloud, upgrading to 16 without success. I hope my data is still available.
 
Getting Error
"Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[08006] [7] FATAL: permission denied for database "nextcloud" DETAIL: User does not have CONNECT privilege."

In database users table my users don't exist anymore
Help Please

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: Check https://github.com/nextcloud/server/issues/11311 for more details.
