### ISSUE TITLE
cannot increase permissions

### ISSUE THREAD

**Issue by dajusc** [nextcloud/server#1608]
At first: The bug is probably the same as (or related to) this owncloud-bug:
https://github.com/owncloud/core/issues/25542

**Steps to reproduce:**
1. Add a user named "test1", assign to group "testgroup".
2. Add a user named "test2", assign to group "testgroup".
3. Login as user "test1" and create a folder named "xyz".
4. Share "xyz" with group "testgroup" and take away permissions to edit.
5. Share "xyz" with user "test2" and take away permissions to edit.
6. Try to give back editing-permissions for "xyz" to user "test2"...
--> Box with error message appears:
**"Fehler beim Teilen: Cannot increase permissions"** 

PS.: Tested on Nextcloud 10.0.
PPS.: My german version says "Fehler beim Teilen: Berechtigungen können nicht erhöht werden"

**Comment by MorrisJobke** [comment]
Fixed in 9.0.54 and 10.0.1 - see https://github.com/nextcloud/server/pull/1376

**Comment by dajusc** [comment]
Uups, seems that I failed using the search correctly. But good thing, that its already fixed. :)
