### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [nextcloud/server#16103]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/nextcloud/server/blob/master/tests/ui-regression/package.json#L12

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by kesselb** [comment]
cc @nextcloud/security @nextcloud/javascript 

luckily it's just a dummy package: https://www.npmjs.com/package/fs

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Thanks @DanielRuf - PR is at #16168
