### ISSUE TITLE
Server sends too much data

### ISSUE THREAD

**Issue by patagfa** [nextcloud/server#16100]
When syncing via the NextCloud App for Mac, our loadbalancer in front of nextcloud throws 4 errors errors every 30 seconds , .  This does not occur with Windows App

### Steps to reproduce
1. Install NextCloud App
2. configure to sync 
3. errors on Loadbalancer are shown

### Expected behaviour
No errors are shown

### Actual behaviour
Loadbalancer shows:
http_process_state_prepend - Invalid action:0x109010 Server sends too much data. serverside (*.*.*.*:443 -> *.*.*.*:49576) clientside (*.*.*.*:49576 -> *.*.*.*:443) (Server side: vip=/Graphics/agfabox-qa-agfa-net-https profile=http pool=/Graphics/agfabox-qa-agfa-net-https server_ip=*.*.*.*)
http_process_state_prepend - Invalid action:0x109010 Server sends too much data. serverside (*.*.*.*:443 -> *.*.*.*:49578) clientside (*.*.*.*:49578 -> *.*.*.*:443) (Server side: vip=/Graphics/agfabox-qa-agfa-net-https profile=http pool=/Graphics/agfabox-qa-agfa-net-https server_ip=*.*.*.*)
http_process_state_prepend - Invalid action:0x109010 Server sends too much data. serverside (*.*.*.*:443 -> *.*.*.*:49579) clientside (*.*.*.*:49579 -> *.*.*.*:443) (Server side: vip=/Graphics/agfabox-qa-agfa-net-https profile=http pool=/Graphics/agfabox-qa-agfa-net-https server_ip=*.*.*.*)
http_process_state_prepend - Invalid action:0x109010 Server sends too much data. serverside (*.*.*.*:443 -> *.*.*.*:49580) clientside (*.*.*.*:49580 -> *.*.*.*:443) (Server side: vip=/Graphics/agfabox-qa-agfa-net-https profile=http pool=/Graphics/agfabox-qa-agfa-net-https server_ip=*.*.*.*)
corresponding apache logs:
*.*.*.* - xxxxx [26/Jun/2019:10:57:24 +0200] "GET /owncloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 801
*.*.*.* - xxxxx [26/Jun/2019:10:57:24 +0200] "GET /owncloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 801
*.*.*.* - xxxxx [26/Jun/2019:10:57:24 +0200] "GET /owncloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 801
*.*.*.* - xxxxx [26/Jun/2019:10:57:24 +0200] "GET /owncloud/ocs/v2.php/core/navigation/apps?absolute=true&format=json HTTP/1.1" 304 801

### Server configuration

**Operating system**: CentOS Linux release 7.4.1708 (Core)

**Web server:**   Apache/2.4.6

**Database:** 

**PHP version:** PHP 7.1.25

**Nextcloud version:** 15.0.7

**Updated from an older ownCloud :**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

**List of activated apps:**
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.1
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 2.0.4
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - bruteforcesettings
  - encryption
  - user_saml

**Comment by kesselb** [comment]
I think this could be fixed by https://github.com/nextcloud/server/pull/15714/files (which will be part of Nextcloud 15.0.9)

**Comment by patagfa** [comment]
problem is no longer reproduced on Nextcloud 16.0.2
