### ISSUE TITLE
Sort order

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#16108]
- [x] Android
- [x] Desktop
- [x] iOS
- [x] Server

As on Android the sort order should be a popup with better descriptive names:
:exclamation: Additionally: show as last point: "List folders on top", enabled by default.

![2019-06-27-111718](https://user-images.githubusercontent.com/5836855/60253873-29e37180-98cd-11e9-97cc-7867e086d561.png)

@nextcloud/designers

**Comment by jancborchardt** [comment]
Yep, exactly.

For server @nextcloud/designers 
- This means that we can get rid of the table header in Files which takes one full row
- On multiselect, we need to then use the controls bar for the multiselect info and actions (just like Android does it)

For iOS @nextcloud/ios 
- The available options should be adjusted to be what we have on Android
- It should use the same wording and order as on Android

**Comment by marinofaggiana** [comment]
![Simulator Screen Shot - iPhone Xʀ (develop) - 2019-09-02 at 18 44 38](https://user-images.githubusercontent.com/8616947/64127385-bc166300-cdb1-11e9-805a-420c1310835a.png)

**Comment by jancborchardt** [comment]
@marinofaggiana could you use the exact wording as we use on Android? It’s much shorter and more understandable. :) Also for the size-based sorting, the order is "Biggest first" and then "Smallest first".

**Comment by tobiasKaminsky** [comment]
@jancborchardt do we also want to sort by mimetype? 
I guess this is something people are used to from file manager?

**Comment by jancborchardt** [comment]
@tobiasKaminsky did we specifically have requests for that in Android? Because I would say that the 3 grouping options should be removed to make it simpler to find the important stuff.

One useful thing is the "Show folders on top", which we probably should also have in the server as this is something quite common we don’t do. Probably even enabled by default, and maybe not even as a a setting.

What do you think @nextcloud/designers?

**Comment by tobiasKaminsky** [comment]
> @tobiasKaminsky did we specifically have requests for that in Android? Because I would say that the 3 grouping options should be removed to make it simpler to find the important stuff

Yes, but only one requests. However this only means that only one took the time to report it.



> One useful thing is the "Show folders on top", which we probably should also have in the server as this is something quite common we don’t do. Probably even enabled by default, and maybe not even as a a setting.

Maybe as default, but still possible to deselect it, as i (and maybe others) are used to it. And then forcing them to use something else…?

**Comment by tobiasKaminsky** [comment]
@marinofaggiana what is left on iOS is discussed:
- put all the sort options into one entry in the menu, opening a bottom sheet for sort options
- remove all group options
