### ISSUE TITLE
Share By Mail Spelling Mistake

### ISSUE THREAD

**Issue by Beeez** [nextcloud/server#16119]
### Steps to reproduce
1. Share file with Email with Password being sent to the Sender first
2. Receive Email including the password to view the file
3. Email body should use the word "sent" instead of "send" in this section "The share was already send to the recipient." 

### Expected behaviour
The email body should say "sent"

### Actual behaviour
The email body says "send"

**Comment by Beeez** [comment]
https://github.com/nextcloud/server/blob/26d3a2d48cac9e3b8d500027436bddd75a5021b2/apps/sharebymail/lib/ShareByMailProvider.php#L590

**Comment by wernerfred** [comment]
Looking forward to take care of this but is this really the only line to change? Where do i find the translations to adapt them (if needed) properly too?
> https://github.com/nextcloud/server/blob/26d3a2d48cac9e3b8d500027436bddd75a5021b2/apps/sharebymail/lib/ShareByMailProvider.php#L590

Anything else to consider before submitting a PR?
