### ISSUE TITLE
Add additional error message for files:transfer-ownership

### ISSUE THREAD

**Issue by JLueke** [nextcloud/server#16115]
**Problem**
While updating a share it is checked if the share is still valid ([see Manager.php](https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L828)). If you already restricted the users to only share with users in their groups and didn't added the transfer target user to the groups the source user is a member of, you'll get an exception with "Sharing is only allowed with group members" if the target user isn't in a group with the share receiver.

But this exception is not shown when it happens during the ownership transfer.
It'll only output the generic message ["Could not restore share with id ..."](https://github.com/nextcloud/server/blob/master/apps/files/lib/Command/TransferOwnership.php#L287).

**Describe the solution you'd like**
Add the exception message to the current generic message e.g.
```php
$output->writeln('<error>Could not restore share with id ' . $share->getId() . ': ' . $e->getMessage() . '</error>');
$output->writeln('<error>' . $e->getTraceAsString() . '</error>');
```

**Describe alternatives you've considered**
- Add the exception message to the current generic message only if a verbose output is desired.
- Add an general info text with possible problems to check if the transfer failed.
- Check if all shares can be transferred beforehand.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years.
