### ISSUE TITLE
Can't upload from mobile app to NC 16.0.1

### ISSUE THREAD

**Issue by AdamPerkins** [nextcloud/server#16111]
After update to 16.0.1 from 15.x everything works perfect except I can't upload files from mobile app to the server.

- I'm using: Huawei Android App 3.6.2 / Apache 2.4 - PHP 7.3 - Ubuntu Server 19.04 - NFS4
- I have no errors in Apache error log nor in Nextcloud log.
- All NC checks are ok, no errors, requirements seems fulfilled.

On Desktop uploads works. On Mobile I also can access to everything as before. But uploads hangs in a queue 'Waiting for upload' (Warte auf Hochladen).

Edit:
I just installed a complete new Nextcloud for testing. Same issue.
Therefore I change the title, it's not related to update process.

**Comment by MaximusMagnusMagnuson** [comment]
Maybe the same here. My nextcloud instance (admin account -> protcols) is spamed by postgresql fatal errors.
Here are some examples:
`
Fatal | webdav | Doctrine\DBAL\Exception\SyntaxErrorException: An  exception occurred while executing 'INSERT INTO "oc_file_locks" ("key",  "lock", "ttl") VALUES(?, ?, ?) ON CONFLICT DO NOTHING' with params  ["files\/88f23e310a1dbea2e7633be0173e01fe", 1, 1561638514]:  SQLSTATE[42601]: Syntax error: 7 FEHLER:  Syntaxfehler bei »ON« LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON  CONFLIC...                                                              ^/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 184: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException("An exceptio ... ^", Doctrine\DBA ... ]})/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 158: Doctrine\DBAL\DBALException::wrapException(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "An exceptio ... ^")/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1088: Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBA ... {}, Doctrine\DBA ... ]}, "INSERT INTO ... G", { 1: "files/ ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/Connection.php - line 216: Doctrine\DBAL\Connection->executeUpdate("INSERT INTO ... G", [ "files/88f ... 4], [ 2,2,2])/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/AdapterPgSql.php - line 49: OC\DB\Connection->executeUpdate("INSERT INTO ... G", { dcValue1:  ... 4}, { dcValue1:  ... 2})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/Connection.php - line 261: OC\DB\AdapterPgSql->insertIgnoreConflict("file_locks", { key: "file ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Lock/DBLockingProvider.php - line 139: OC\DB\Connection->insertIgnoreConflict("file_locks", { key: "file ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Lock/DBLockingProvider.php - line 185: OC\Lock\DBLockingProvider->initLockField("files/88f23 ... e", 1)/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Common.php - line 715: OC\Lock\DBLockingProvider->acquireLock("files/88f23 ... e", 1)/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 593: OC\Files\Storage\Common->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 593: OC\Files\Storage\Wrapper\Wrapper->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/View.php - line 1927: OC\Files\Storage\Wrapper\Wrapper->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/View.php - line 2037: OC\Files\View->lockPath("/.Contacts- ... f", 1, false)/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/lib/Connector/Sabre/Node.php - line 378: OC\Files\View->lockFile("/.Contacts- ... f", 1)/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 153: OCA\DAV\Connector\Sabre\Node->acquireLock(1)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile("2019-06-26_23-44-37.vcf", null)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile(".Contacts-B ... f", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/var/www/virtual/veuu35z5/html/nextcloud/remote.php - line 163: require_once("/var/www/vi ... p")Verursacht vonDoctrine\DBAL\Driver\PDOException: SQLSTATE[42601]: Syntax error: 7 FEHLER:  Syntaxfehler bei »ON« LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON CONFLIC...                                                              ^/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1079: Doctrine\DBAL\Driver\PDOStatement->execute()/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/Connection.php - line 216: Doctrine\DBAL\Connection->executeUpdate("INSERT INTO ... G", [ "files/88f ... 4], [ 2,2,2])/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/AdapterPgSql.php - line 49: OC\DB\Connection->executeUpdate("INSERT INTO ... G", { dcValue1:  ... 4}, { dcValue1:  ... 2})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/Connection.php - line 261: OC\DB\AdapterPgSql->insertIgnoreConflict("file_locks", { key: "file ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Lock/DBLockingProvider.php - line 139: OC\DB\Connection->insertIgnoreConflict("file_locks", { key: "file ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Lock/DBLockingProvider.php - line 185: OC\Lock\DBLockingProvider->initLockField("files/88f23 ... e", 1)/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Common.php - line 715: OC\Lock\DBLockingProvider->acquireLock("files/88f23 ... e", 1)/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 593: OC\Files\Storage\Common->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 593: OC\Files\Storage\Wrapper\Wrapper->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/View.php - line 1927: OC\Files\Storage\Wrapper\Wrapper->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/View.php - line 2037: OC\Files\View->lockPath("/.Contacts- ... f", 1, false)/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/lib/Connector/Sabre/Node.php - line 378: OC\Files\View->lockFile("/.Contacts- ... f", 1)/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 153: OCA\DAV\Connector\Sabre\Node->acquireLock(1)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile("2019-06-26_23-44-37.vcf", null)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile(".Contacts-B ... f", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/var/www/virtual/veuu35z5/html/nextcloud/remote.php - line 163: require_once("/var/www/vi ... p")Verursacht vonPDOException: SQLSTATE[42601]: Syntax error: 7 FEHLER:  Syntaxfehler bei »ON« LINE 1: ..._locks" ("key", "lock", "ttl") VALUES($1, $2, $3) ON CONFLIC...                                                              ^/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php - line 141: PDOStatement->execute(null)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php - line 1079: Doctrine\DBAL\Driver\PDOStatement->execute()/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/Connection.php - line 216: Doctrine\DBAL\Connection->executeUpdate("INSERT INTO ... G", [ "files/88f ... 4], [ 2,2,2])/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/AdapterPgSql.php - line 49: OC\DB\Connection->executeUpdate("INSERT INTO ... G", { dcValue1:  ... 4}, { dcValue1:  ... 2})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/DB/Connection.php - line 261: OC\DB\AdapterPgSql->insertIgnoreConflict("file_locks", { key: "file ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Lock/DBLockingProvider.php - line 139: OC\DB\Connection->insertIgnoreConflict("file_locks", { key: "file ... 4})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Lock/DBLockingProvider.php - line 185: OC\Lock\DBLockingProvider->initLockField("files/88f23 ... e", 1)/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Common.php - line 715: OC\Lock\DBLockingProvider->acquireLock("files/88f23 ... e", 1)/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 593: OC\Files\Storage\Common->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 593: OC\Files\Storage\Wrapper\Wrapper->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/View.php - line 1927: OC\Files\Storage\Wrapper\Wrapper->acquireLock("files/.Cont ... f", 1, OC\Lock\DBLockingProvider {})/var/www/virtual/veuu35z5/html/nextcloud/lib/private/Files/View.php - line 2037: OC\Files\View->lockPath("/.Contacts- ... f", 1, false)/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/lib/Connector/Sabre/Node.php - line 378: OC\Files\View->lockFile("/.Contacts- ... f", 1)/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 153: OCA\DAV\Connector\Sabre\Node->acquireLock(1)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile("2019-06-26_23-44-37.vcf", null)/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile(".Contacts-B ... f", null, null)<<closure>>Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])/var/www/virtual/veuu35z5/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})/var/www/virtual/veuu35z5/html/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80: Sabre\DAV\Server->exec()/var/www/virtual/veuu35z5/html/nextcloud/remote.php - line 163: require_once("/var/www/vi ... p")
`

**Comment by kesselb** [comment]
@AdamPerkins please edit your initial post and provide the issue template: https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

@MaximusMagnusMagnuson https://github.com/nextcloud/server/issues/15613

**Comment by MaximusMagnusMagnuson** [comment]
Thx, try to upgrade to >=9.5 postgresql

**Comment by AdamPerkins** [comment]
@kesselb What info is missing ?

**Comment by AdamPerkins** [comment]
Additionally I checked now that Apache access file and had thousand of requests like that:
```
"HEAD /remote.php/webdav/IMG_20190613_155522%20(16993).jpg HTTP/1.1" 302 1022 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
"HEAD /index.php/apps/files/ HTTP/1.1" 200 822 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
"HEAD /remote.php/webdav/IMG_20190613_155522%20(16994).jpg HTTP/1.1" 302 1022 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
"HEAD /index.php/apps/files/ HTTP/1.1" 200 822 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
"HEAD /remote.php/webdav/IMG_20190613_155522%20(16995).jpg HTTP/1.1" 302 1022 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
"HEAD /index.php/apps/files/ HTTP/1.1" 200 822 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
"HEAD /remote.php/webdav/IMG_20190613_155522%20(16996).jpg HTTP/1.1" 302 1022 "-" "Mozilla/5.0 (Android) ownCloud-android/3.6.2"
```

**Comment by AdamPerkins** [comment]
Today I set the debug level to 0 and could see these errors while trying to upload:
```
Debug | webdav | Sabre\DAV\Exception\NotFound: File with name IMG_20190613_155522 (86).jpg could not be located
Debug | webdav | Sabre\DAV\Exception\NotFound: File with name IMG_20190613_155522 (85).jpg could not be located
Debug | webdav | Sabre\DAV\Exception\NotFound: File with name IMG_20190613_155522 (84).jpg could not be located
```

**Comment by AdamPerkins** [comment]
Thank you dear fucking bot for your desinterest to fix dangerous failures in your project after ONLY 1 month of time.
If your project doesn't have enough manpower for debugging and fixing you shouldn't invite people to report bug and waste their time.

I reported a critical bug that generates an endless loop of upload trys from a mobile phone to the NC server. That means from starting the upload every failed connection cost the mobile user some amount of mobile internet bandwidth. Very nice if you try to upload your holiday pictures from abroad and when you come back you see 1500000 missing connection attempts you have to pay for.

To find the fault we have installed NC on 4 different system in various manner. In a VM, with and without NFS and so on. We deinstalled and reinstalled the app on 2 mobile devices. We updated NC from 16.0.1 to 16.0.3. There was updates on Android app. Nothing worked.

I gave you detailed log reports and detailed descriptions. We invest a lot of time. Thank you for ignoring it! Thank you for no feedback or help!

Good luck for your project!
