### ISSUE TITLE
NC 16 - Using external storage, getting error while deleting a folder

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#16123]
I'm using docker nextcloud. I created a clean instance and I want to use the application external storage. I managed to configure successfully a local storage using the following command : 

    mount_id=$(docker exec --user 1000 nextcloud php occ files_external:create Home local null::null -c datadir=/var/www/data --output=json)
    docker exec --user 1000 nextcloud php occ files_external:applicable --add-user=foo "$mount_id"

I can create/move/copy folder and files but when I want to delete  a created folder I got the following error :

> Error deleting file "folderfoo".

It's says it's a file but actually it was a folder. After refreshing the browser the folder is deleted. By the way I can successfully delete files.
I'm using this image https://hub.docker.com/_/nextcloud/
I added the right user permission on the docker container and the data folder.

I tried to disable locking file but it doesn't change anything, using : 

`'filelocking.enabled' => false,`

The folder data is under the right user (1000).

I also configured a redis container and linked it to my nextcloud container with `-e REDIS_HOST="redis"` and it give me the following in `config.php` : 

```
'memcache.distributed' => '\\OC\\Memcache\\Redis',
'memcache.locking' => '\\OC\\Memcache\\Redis',
'redis' =>
 array (
        'host' => 'redis',
        'port' => 6379,
    ),
```

I don't know what I'm supposed to do, thanks for any help

**Comment by kesselb** [comment]
> I don't know what I'm supposed to do,

What are you trying to do? Usually https://help.nextcloud.com/ is the better place for configuration related questions.

**Comment by vipera7** [comment]
I'm expecting to remove the error message I'm receiving when I'm deleting a folder : 

> Error deleting file "somefolder".

The folder is actually deleted when I refresh the page

**Comment by flower1024** [comment]
I have the same issue also with external storage.
While removing a directory it always shows an error - but removes it anyway.
I have the same error while moving big files. It moves them but shows an error

**Comment by lrkwz** [comment]
Same on NC 18

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
