### ISSUE TITLE
file/folder name corrupt after rename with "." 

### ISSUE THREAD

**Issue by kyhuynhduc** [nextcloud/server#16140]
step 1: folder name : "PAYMENT QLYCHT (Phase3) - BongTeam"
step 2: rename to:  "PAYMENT.**QLYCHT** (Phase3) - BongTeam"

nextcloud recognize .**QLYCHT (Phase3) - BongTeam** is file extension
=> folder coruppted => nolonger access (even though rename)

**Comment by palto42** [comment]
Can't reproduce this bug on Ubuntu 18.04 server with Nextcloud 15.0.9

**Comment by kyhuynhduc** [comment]
> Can't reproduce this bug on Ubuntu 18.04 server with Nextcloud 15.0.9
FYI
#16393

**Comment by Mululu** [comment]
#https://github.com/nextcloud/server/issues/16468

**Comment by juliushaertl** [comment]
Duplicate of https://github.com/nextcloud/groupfolders/issues/518
