### ISSUE TITLE
language

### ISSUE THREAD

**Issue by chummumm** [nextcloud/server#16152]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Ubuntu18.04
**Web server:**
caddy
**Database:**
mariadb
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16
**Updated from an older Nextcloud/ownCloud or fresh install:**
no
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files
	- INVALID_HASH
		- l10n/zh_CN.js
		- l10n/zh_CN.json
- privacy
	- FILE_MISSING
		- l10n/zh_CN.js
		- l10n/zh_CN.json

Raw output
==========
Array
(
    [files] => Array
        (
            [INVALID_HASH] => Array
                (
                    [l10n/zh_CN.js] => Array
                        (
                            [expected] => 410dfe609dba2d285b2e032c9d90a73033050473e05f63ce44773747b92ef07a23eda2fbbecc1df63fdbebcc75259b19b12a9f73fc583e73904edf1e276fea81
                            [current] => f73998ab6114e1f436e42cbf1a4006786a72def8fc48388a47b08f3d99164cee5a5f64c205e0c469883d320d0c100c57ae28d92cfa98686ead7b7e21dd3be21d
                        )

                    [l10n/zh_CN.json] => Array
                        (
                
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
