### ISSUE TITLE
Unable to open/download some files from external SMB share

### ISSUE THREAD

**Issue by flattermann** [nextcloud/server#16171]
### Steps to reproduce
Try to open (WebUI), or download (WebUI/Desktop sync) some specific files (see description below)

### Expected behaviour
It should open/download the whole file.

### Actual behaviour
The download always stops at the same position.
This position varies from file to file (a ~9MiB file stops at exactly 7MiB, a ~74MiB file stops at exactly 50MiB).

### Server configuration

**Operating system**: Debian Linux 9.9

**Web server:** apache 2.4.25

**Database:** mariadb 10.1.38

**PHP version:** 7.3.6

**Nextcloud version:**  15.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Updater

**Signing status:** No errors have been found.

**List of activated apps:**
<details>
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - admin_audit: 1.5.0
  - announcementcenter: 3.4.1
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.3
  - dav: 1.8.2
  - deck: 0.6.2
  - external: 3.2.0
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trackdownloads: 1.4.0
  - files_trashbin: 1.5.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - mail: 0.11.1
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - richdocuments: 3.3.10
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - spreed: 5.0.4
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - tasks: 0.11.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
</details>

**Nextcloud configuration:**
<details>{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "15.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "debug": true,
        "filelocking.enabled": true,
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 29,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5
        },
        "filesystem_check_changes": 1,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "skeletondirectory": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "production"
    }
}
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

#### LDAP configuration 
Not posting the LDAP config here because the output is messy, it contains sensitive informations and is probably not needed. I can upload a copy later if necessary.

### Client configuration
**Browser:** Chrome/Firefox/Nextcloud App...

**Operating system:** Windows 10 Pro x64

#### Web server error log
no errors logged

#### Nextcloud log (data/nextcloud.log)
no errors logged

#### Browser log
https://MYSERVER/remote.php/webdav/Projects_Software/Test/1.jpg?downloadStartSecret=REMOVED:1 GET https://MYSERVER/remote.php/webdav/Projects_Software/Test/1.jpg?downloadStartSecret=REMOVED net::ERR_CONTENT_LENGTH_MISMATCH 200 (OK)

### Description
**I've a Nextcloud 15.0.8 with around 60 users and a lot of files (oc_filecache has ~4 million entries).
Most of the files are on external shares mounted via SMB (Debian 9/Samba 4.5.16).**

I've set up a cronjob that rescans the SMB shares for changed files regularily for all users.

This works ok for most of the files, but for **some specific files**, it does not work.

**E.g. I have a JPG file with a size of 9.050.095 bytes.
I'm not able to open/download this file in the WebUI or via Desktop Sync.**
Other files work just fine.

In the WebUI, no thumbnail is shown and it will download exactly 7 MiB (7.340.032‬ bytes) and then stall for 20 seconds until it reaches a timeout and cancels the download).

In the Desktop Sync, the same will happen (it creates a temp file with 7MiB) and then, after some seconds, it fails with "Connection lost".

No errors/warnings are logged in nextcloud.log or samba log, even with log level turned all the way up.

It does not always fail at exactly 7MB.
Another file with this issue is exactly 77.534.535 bytes big. This one always fails at exactly 50MiB.

**It is reproducible for the affected files, i.e. if I copy the file to another location/share on the SMB server, I'm still unable to open/download it via NC.
If I copy it to a local nextcloud directory (not an external share), it works.**

I even tried to copy it on another NC server, but there it works even if I put it on external SMB storage... I'm not sure how I can further debug it....

Any help or hints are appreciated.

**Comment by aignerat** [comment]
hey, do you still have the original file and tried to reupload it? This could help to point out where the corruption is starting.

**Comment by flattermann** [comment]
Yeah, sure, all the files are available on the Samba server and I can access them without problems using Windows Explorer/MacOS Finder/ssh...

I copied one of the files to my computer and renamed it to 1.jpg.
Then I created some more copies of the same file: 2.jpg ... 9.jpg.
Each file has 9.050.095 bytes.

Then I reuploaded the files to NC via WebUI.
This actually worked, and it created the **full files** on the **SMB share**.

But I'm **not able to download any of files** afterwards.
It stalls and timeouts at exactly 7MiB for every of these files.
The same happens with the Nextcloud Desktop Sync: 
It creates a 7MiB temp file and after a while I get a "Connection closed" error.

I also tried to reupload the files via NC Desktop Sync.
This also worked (the full files were created on the SMB share), but I cannot download them via WebUI either.

BTW: It is not related to the file type. I get this problem with all kinds of files: JPG, XLS, PDF...

At least I got some debug logging in NC while uploading the files:
<details>
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"Couldn't stat smb:\/\/storage.domain.REDACTED\/Projects_Software\/Test3\/9.jpg: Does not exist at \/daten\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php#179","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"No cache entry found for \/REDACTED\/files\/Projects_Software\/Test3\/9.jpg (storage: shared::\/Projects_Software, internalPath: Test3\/9.jpg)","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"Couldn't stat smb:\/\/storage.domain.REDACTED\/Projects_Software\/Test3\/9.jpg: Does not exist at \/daten\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php#179","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"Couldn't stat smb:\/\/storage.domain.REDACTED\/Projects_Software\/Test3\/9.jpg: Does not exist at \/daten\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php#179","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"No cache entry found for \/REDACTED\/files\/Projects_Software\/Test3\/9.jpg (storage: shared::\/Projects_Software, internalPath: Test3\/9.jpg)","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"Couldn't stat smb:\/\/storage.domain.REDACTED\/Projects_Software\/Test3\/9.jpg: Does not exist at \/daten\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php#179","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"PHP","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"Couldn't stat smb:\/\/storage.domain.REDACTED\/Projects_Software\/Test3\/9.jpg: Does not exist at \/daten\/nextcloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Native\/NativeState.php#179","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
{"reqId":"McluCTlFOycxB4S4sFxt","level":0,"time":"2019-07-01T11:06:09+00:00","remoteAddr":"REDACTED","user":"REDACTED","app":"no app in context","method":"PUT","url":"\/remote.php\/dav\/files\/REDACTED\/Projects_Software\/Test3\/9.jpg","message":"No cache entry found for \/appdata_ocryg95sdn3e\/preview\/6105779 (storage: local::\/daten\/nc_data\/, internalPath: appdata_ocryg95sdn3e\/preview\/6105779)","userAgent":"Mozilla\/5.0 (Windows) mirall\/2.5.2git (build 20190319) (Nextcloud)","version":"15.0.8.1"}
</details>

**Comment by flattermann** [comment]
It seems that this problem is caused by our firewall setup (ipfire with Suricata as IPS).

When I disable the EmergingThreats rules "Current Events", it suddenly works.
The strange thing is that  Suricata has not actually logged any dropped packets, but it somehow interfered with Nextcloud.

Anyway, this issue can be closed.

**Comment by kesselb** [comment]
Thanks for your feedback :+1:
