### ISSUE TITLE
File locks nginx

### ISSUE THREAD

**Issue by XjeEDK** [nextcloud/server#16172]
Nextcloud version: 15.0.7
Operating system and version: CentOS 7.5
Apache or nginx version: Nginx 1.12
PHP version: 7.1.23

The issue you are facing:
/var fills up because of file locks
nginx 1580 nginx 21u REG 253,4 268435456 430373 /var/lib/nginx/tmp/fastcgi/7/20/0000000207 (deleted)
Only restarting nginx releases the files and free up disk space.

Also tried to change the directory to a separate disk:
In /usr/share/nginx/html/nextcloud/.user.ini
upload_tmp_dir=/var/big_temp_file/php_upload_tmp_dir

In /etc/nginx/conf.d/nextcloud.conf
server {
…
client_body_temp_path /var/big_temp_file/client_body_temp 1 2;

But this is also not working. Files still created in /var/lib/nginx/tmp/fastcgi

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
