### ISSUE TITLE
Optional Setting: Requiring the new password to be entered twice when changing password

### ISSUE THREAD

**Issue by jbrrrr** [nextcloud/server#16176]
In a school environment, younger children often mistype when changing their password. That means unnecessary work for the cloud administrator.

These incidents could be reduced by optionally requiring in the settings the new password to be entered twice when changing password.

This request was sent to us by teachers.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
