### ISSUE TITLE
Reject new user IDs for which there exists a file or folder inside Nextcloud's data directory

### ISSUE THREAD

**Issue by leonklingele-work** [nextcloud/server#16196]
#14652 was incomplete in that it didn't reject user IDs for which there exists a file or folder inside the data directory.

Also, `index.html`, `owncloud.db`, `owncloud.db-shm` and `owncloud.db-wal` were missing.
In addition to that, please also honor `config.php`s `blacklisted_files`.

See discussion @ https://github.com/nextcloud/server/pull/14652#pullrequestreview-214609165

**Comment by MorrisJobke** [comment]
cc @rullzer @ChristophWurst @blizzz

**Comment by nickvergessen** [comment]
Actually this was fixed by https://github.com/nextcloud/server/pull/18130
