### ISSUE TITLE
FIRST login with internet explorer won't work for all User Backends

### ISSUE THREAD

**Issue by klm46** [nextcloud/server#1620]
### Steps to reproduce
1. set up LDAP-Backend (here Windows Server 2012 AD)
2. login FIRST TIME with IE11 (Windows10)

### Expected behaviour
Tell us what should happen
The Popup should appear, were the apps are shown. Then, my folders should appear. 
### Actual behaviour
Tell us what happens instead
The popup don`t appear, the folders as well not. Only the left part of the frontpage appears. 
When logging in the first time with another browser, then logging in with IE, everythink works.
### Server configuration
**Operating system**: RHEL 7

**Web server:** Apache 2.4

**Database:** MySQL 5.5

**PHP version:** 5.5

**Nextcloud version:** (see Nextcloud admin page)
10.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
CLI
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** IE 11

**Operating system:** Windows10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
Please provide additional information such as the LDAP config.

**Comment by klm46** [comment]
Hi, and thanks for the quick reply.

here`s my config.php. Which information is additional needed?


`<?php
$CONFIG = array (
  'passwordsalt' => '*',
  'secret' => *',
  'trusted_domains' =>
  array (
    0 => 'localhost',
    1 => 'datenportal',
    2 => 'datenportal.*',
    3 => '*',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'http://localhost',
  'dbtype' => 'mysql',
  'version' => '9.1.0.16',
  'dbname' => 'nextcloud_db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_admin',
  'dbpassword' => '*',
  'logfile' => '/var/log/nextcloud.log',
  'installed' => true,
  'instanceid' => '*',
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'mailserver01.*',
  'mail_smtpport' => '25',
  'mail_from_address' => 'datenportal',
  'mail_domain' => '*',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => '\\OCA\\User_LDAP\\LDAPProviderFactory',
);`

**Comment by LukasReschke** [comment]
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

**Comment by klm46** [comment]
sudo -u apache php occ ldap:show-config
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| hasPagedResultSupport         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| homeFolderNamingRule          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapAgentName                 | CN=auth_nextcloud,OU=Technische                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| ldapAgentPassword             | ***                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ldapAttributesForGroupSearch  |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapAttributesForUserSearch   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapBackupHost                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapBackupPort                |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapBase                      | DC=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ldapBaseGroups                | DC=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ldapBaseUsers                 | DC=                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ldapConfigurationActive       | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapEmailAttribute            | mail                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ldapExperiencedAdmin          | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapExpertUsernameAttr        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| ldapGroupFilter               |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapGroupFilterGroups         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapGroupFilterMode           | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapGroupFilterObjectclass    |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       |
| ldapHost                      | e                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           |
| ldapIgnoreNamingRules         |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapLoginFilter               | (&(&(|(objectclass=user))(|(|(memberof=CN=GRUPPE DATENPORTAL,CN=Users,DC=,DC=de)(primaryGroupID=28487))(|(memberof=CN=proxy_Betriebsbezogen,OU=Groups,OU=Proxy,OU=CheckpointDefinitionen,DC=,DC=de)(primaryGroupID=27615))(|(memberof=CN=proxy_offen,OU=Groups,OU=Proxy,OU=CheckpointDefinitionen,DC=,DC=de)(primaryGroupID=27617))(|(memberof=CN=proxy_offen_ohneSocialMedia,OU=Groups,OU=Proxy,OU=CheckpointDefinitionen,DC=,DC=de)(primaryGroupID=27616))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapLoginFilterEmail          | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapLoginFilterMode           | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapLoginFilterUsername       | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapNestedGroups              | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapOverrideMainServer        |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapPagingSize                | 500                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ldapPort                      | 389                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                |
| ldapQuotaAttribute            |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapQuotaDefault              |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapTLS                       | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapUserDisplayName           | displayname                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
| ldapUserDisplayName2          |                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
| ldapUserFilter                | (&(|(objectclass=user))(|(|(memberof=CN=GRUPPE DATENPORTAL,CN=Users,DC= DC=de)(primaryGroupID=28487))(|(memberof=CN=proxy_Betriebsbezogen,OU=Groups,OU=Proxy,OU=CheckpointDefinitionen,DC=,DC=de)(primaryGroupID=27615))(|(memberof=CN=proxy_offen,OU=Groups,OU=Proxy,OU=CheckpointDefinitionen,DC=,DC=de)(primaryGroupID=27617))(|(memberof=CN=proxy_offen_ohneSocialMedia,OU=Groups,OU=Proxy,OU=CheckpointDefinitionen,DC=,DC=de)(primaryGroupID=27616))))                                                                   |
| ldapUserFilterGroups          | GRUPPE DATENPORTAL;proxy_Betriebsbezogen;proxy_offen;proxy_offen_ohneSocialMedia                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
| ldapUserFilterMode            | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| ldapUserFilterObjectclass     | user                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| ldapUuidUserAttribute         | auto                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
| turnOffCertCheck              | 0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
| useMemberOfToDetectMembership | 1                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by klm46** [comment]
Do you need any further information? I only ask because of teh flag. Cheers

**Comment by nickvergessen** [comment]
Any error in the browser console? You can open that with `F12`. Then refresh the page.
I suspect the problem being caused by a JS error, because both, the loading of the first-run-wizard as well as the loading of the file list is done via javascript.
LDAP authentication should be unrelated.

**Comment by klm46** [comment]
You are right! It`s not an LDAP-Issue. I just createt an DB-User, and the same issue. 

Here is the Screenshot from the Konsole-Output of IE11.
![ie11_first_login](https://cloud.githubusercontent.com/assets/7510750/19107570/2db20f06-8aed-11e6-87a9-3d796ca0d0ca.png)

**Comment by nickvergessen** [comment]
@MorrisJobke any idea?

**Comment by MorrisJobke** [comment]
I have seen this too - I will look into this once my laptop is back (there I have some IE virtual boxes)

**Comment by klm46** [comment]
any news about your laptop @MorrisJobke

**Comment by MorrisJobke** [comment]
Okay ... works with master. I will retest with stable10.

**Comment by klm46** [comment]
master = 11.0 alpha?

**Comment by MorrisJobke** [comment]
> master = 11.0 alpha?

yes.

**Comment by MorrisJobke** [comment]
Okay. I can reproduce this on stable10

**Comment by MorrisJobke** [comment]
The stack trace of when it happened:

<img width="504" alt="bildschirmfoto 2016-10-13 um 10 55 35" src="https://cloud.githubusercontent.com/assets/245432/19342794/9fe8faac-9133-11e6-9f33-ce351a602218.png">

**Comment by MorrisJobke** [comment]
Once the first run wizard is disabled the issue is gone. This only happens in stable10 - master and stable9 works fine.

**Comment by MorrisJobke** [comment]
Fix is in https://github.com/nextcloud/firstrunwizard/pull/21

**Comment by klm46** [comment]
thanks @MorrisJobke 
Can i do the changes manually?

**Comment by MorrisJobke** [comment]
Yes: Apply the patch: https://patch-diff.githubusercontent.com/raw/nextcloud/firstrunwizard/pull/21.patch

`patch -p1 < 21.patch` inside the `apps/firstrunwizard` folder.

**Comment by klm46** [comment]
works great! thanks again
