### ISSUE TITLE
Wrong OC.webroot deduced by js.js

### ISSUE THREAD

**Issue by eguiraud** [nextcloud/server#16203]
### Steps to reproduce
I'm running nextcloud within docker with docker-compose (using the version with the apache web server). The docker host also acts as reverse proxy. I want nextcloud to be reachable at `serverurl/nextcloud`.

1. Setup reverse proxy

the host's apache2's configuration contains:

```
ProxyPass "/nextcloud" "http://127.0.0.1:9000"
ProxyPassReverse "/nextcloud" "http://127.0.0.1:9000"
ProxyPassReverseCookiePath /nextcloud /
ServerAlias *
UseCanonicalName On
```
 
2. Start nextcloud server (via docker-compose)

I'm using the "base apache" configuration [here](https://hub.docker.com/_/nextcloud/) -- I only changed port 8080 with 9000.

3. Add webroot to nextcloud's config.php to make it work behind a reverse proxy

I followed the instructions [here](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html) and created a `config.php` file with the following content:

```
<?php
$CONFIG = array (
  'trusted_proxies'   => ['10.0.0.1'], # assuming 10.0.0.1 is serverurl's docker-facing ip
  'overwritehost'     => 'serverurl',
  'overwriteprotocol' => 'https',
  'overwritewebroot'  => '/nextcloud',
  'overwritecondaddr' => '^10\.0\.0\.1$',
);
```

4. Connect to `serverurl/nextcloud` from my browser

### Expected behaviour

When accessing `serverurl/nextcloud`, the setup page should load and function properly.

### Actual behaviour

The setup page loads, but **clicking the "Finish setup" button wrongly redirects to `serverurl/index.php` instead of `serverurl/nextcloud/index.php` which breaks the setup procedure.**

Firefox's console shows an error:

```
Loading failed for the <script> with source “https://serverurl/core/vendor/zxcvbn/dist/zxcvbn.js”.
```

From which one can see that the resource is being loaded from `serverurl/core` instead of `serverurl/nextcloud/core`.

The host's `var/log/apache2/access.log` confirms this is the case:

```
...snip...
90.114.17.5 - - [02/Jul/2019:23:17:45 +0000] "GET /core/vendor/zxcvbn/dist/zxcvbn.js*HTTP/1.1" 404 675 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
90.114.17.5 - - [02/Jul/2019:23:17:45 +0000] "GET /nextcloud/core/js/dist/main.js.map HTTP/1.1" 200 1060911 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0"
```

### Server configuration

I'm using docker-compose with the "Base version - apache" configuration. I only changed the docker container port number from 8080 to 9000. The server's `config.php` is posted above.

See above for the reverse proxy configuration.

### I did some digging

The problem seems to be the logic that sets `OC.webroot` at the top of `core/js/js.js`, in particular:
```javascript
oc_webroot = oc_webroot.substr(0, oc_webroot.lastIndexOf('/'));
```
which results in an empty `oc_webroot` since `oc_webroot` at this line is `/nextcloud`.

Indeed, accessing `serverurl/nextcloud/` (note the trailing `/`) works correctly!

Is this a bug? If not, what's the correct setup to not have to always add the extra trailing slash to access nextcloud behind an apache2 reverse proxy (I only found nginx examples)?

**Comment by kesselb** [comment]
@nextcloud/docker is this a issue with server or configuration? :thinking:

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
