### ISSUE TITLE
Can't add domain name with specific port to trusted_domains

### ISSUE THREAD

**Issue by iWangJiaxiang** [nextcloud/server#16205]
Hello there,

As described in official doc for configuring [trusted_domains](https://docs.nextcloud.com/server/16/admin_manual/installation/installation_wizard.html#trusted-domains), I can add domain names as well as ip addresses to it.

However, when I add a domain name with specific port (like **www.example.org:1234**) and visit it, it will throw internal error saying accessing server from untrusted domains.

And, when I add an ip address with specific port (like **12.34.56.78:1234**) and visit it, it will work perfectly.

Could you plz add support for domain names with specific port?

Thank you.

**Comment by MorrisJobke** [comment]
Having a quick look at the code doesn't show anything obvious:

https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Security/TrustedDomainHelper.php#L51-L99

cc @ChristophWurst @rullzer

**Comment by MorrisJobke** [comment]
cc @kesselb

**Comment by iWangJiaxiang** [comment]
> Having a quick look at the code doesn't show anything obvious:
> 
> https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/Security/TrustedDomainHelper.php#L51-L99
> 
> cc @ChristophWurst @rullzer

Thanks for your quick reply!

In my case, My NC server is behind the nginx proxy server and the public server is not hosted at 80/443 port for security reason. (So the public url in the browser should look like "https://nc.example.org:1234") And in the **config.php**, the `trusted_domains` property is set to a domain name **without** port.

It worked perfectly until I tried to add my NC in NC desktop app. I was trying to setup server url in NC desktop app with the url "https://nc.example.org:1234" but the "login" button in the app was linked to the target url without port "https://nc.example.org/login/flow/grant?clientIdentifier=&stateToken=XX". So the authentication was impossiple to succeed because of incorrect url.

Thus, I think the problem might be the domain name without port in trusted_domains property. And this issue was opend...

I don't know much about php so I can not find more info for now. I hope you could help me plz. :D

Thank you!

**Comment by ChristophWurst** [comment]
Sounds like the login flow does not work with custom ports @rullzer.

**Comment by jegged** [comment]
in my case, only customer https port without 443 will face the problem, in my case ,the ssl port set to 4444, the trusted_domain set "www.abc.com", when page to www.abc.com in brower it will redirect to "https://www.abc.com/login" not "https://www.abc.com:4444/login", i change the location url, it will display the login page, but after login ,it will redirect to "https://www.abc.com/apps/files/" not "https://www.abc.com:4444/apps/files/".

**Comment by iWangJiaxiang** [comment]
Is there any walkaround for now?

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html

Port is not important for `trusted_domains`. You are looking for `overwritehost` (because the urls are wrong). For nextcloud behind a reverse proxy add the ip (of the reverse proxy) to `trusted_proxies`. Forwarded headers like the host or protocol are accepted then. 

- Nginx and Traefik provide "X-FORWARED-HOST" and "X-FORWARDED-PROTO"
- Apache2 provide "X-FORWARDED-HOST". `overwriteprotocol` is required in this case.

Sometimes the detection does not work (e.g. headers named different, wrong values for trusted proxies). In this case add this to config.php
```
'overwritehost' => 'nc.example.org:1234',
'overwriteprotocol' => 'https',
```
