### ISSUE TITLE
Update changelog accordingly!

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/server#16227]
Hello. :-)

In the past there have been some issues because of the changelog. Now it is linked to nextcloud.com/changelog, but not up-to-date.
Also with today's new release the changelog has not been updated.

**Please integrate the changelog update into the rollout process.**

So my question for today: What's new in 15.0.9?

Thanks

**Comment by kesselb** [comment]
> What's new in 15.0.9?

https://github.com/nextcloud/server/pull/16219

cc @MorrisJobke
