### ISSUE TITLE
Make specifying the admin password consistent across occ commands

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#16225]
From https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html:

```
sudo -u www-data php occ maintenance:install ... --admin-user "admin" --admin-pass "password"
```
vs.
```
su -s /bin/sh www-data -c 'php occ user:resetpassword --password-from-env
  layla'
```

If there is a security reason for not passing the password in ARGV for password resets, the same reason exists when setting it in the first place. But currently only ARGV is supported during installation, and only ENV is supported during password reset. (At least according to this documentation.)

Personally, I think both should support both, but that's just me.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
