### ISSUE TITLE
Improve gd-image resize quality

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#16237]
Nextcloud uses `gd-image` function `imagecopyresampled() `to resize images to thumbnails. This uses by default a pretty fast, but blurry resizing algorithm.

Since images mostly reduced I suggest that Nextcloud should use ` IMG_MITCHELL`  or` IMG_SINC` as they are generally very good at retaining details and sharpness with fewer artifacts (than bilinear/bicubic) when reducing size.

https://php.net/manual/en/function.imagesetinterpolation.php

Other resources:
https://www.cambridgeincolour.com/tutorials/image-resize-for-web.htm
http://www.bvdwolf.nl/foto/resample/down_sample.html
http://www.imagemagick.org/Usage/filter/ (ImageMagick information on scaling filters)

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
