### ISSUE TITLE
Can not go back from the files list anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1623]
### Steps to reproduce
1. Open activity app or settings or ...
2. Open files app
3. Hit the "back" button of your browser multiple times
### Expected behaviour

Should be activity again
### Actual behaviour

Staying on the files app

The problem is, that you have to "jump over" the `http://localhost/index.php/apps/files/` step. However, that one always pushes a new entry `http://localhost/index.php/apps/files/?dir=/&fileid=44` to the history, so the next "back" brings you to `apps/files/` again.
### Fix

The redirect from `apps/files/` to `apps/files/?dir=/&fileid=44` should not push to history, or at least not when we are coming back.

On Nextcloud 10 you can do the jump when you are fast enough. But on master it looks impossible to me.

**Comment by wiswedel** [comment]
closing because super-stale and NC version no longer supported
