### ISSUE TITLE
Basic Theming: "login image" always converted to JPEG format

### ISSUE THREAD

**Issue by despens** [nextcloud/server#16232]
### Steps to reproduce
1. Find great GIF animation to be used as a login image
2. Under "Theming" settings, upload as "Login image"
3. Log out of nextcloud to examine login image

### Expected behaviour
The GIF should stay animated.

### Actual behaviour
The GIF is converted to a JPEG image and becomes static.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** Postgres

**PHP version:** 7.2

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from v15

**Where did you install Nextcloud from:** Downloaded tgz from nextcloud.com

### Example image to use

![44ydfcun](https://user-images.githubusercontent.com/571494/60671336-2888ea80-9e73-11e9-8eac-7dfbb78443ed.gif)

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
We convert the image to reduce it to a maximum size. But I'd say to not do this for gifs as we also don't convert svgs.

If someone wants to look into this, the relevant code is here https://github.com/nextcloud/server/blob/3f1b6e2ce903dc53633adb09527b6977bd2e930b/apps/theming/lib/Controller/ThemingController.php#L276

**Comment by despens** [comment]
I'd suggest that GIFs and PNGs should be left untouched. When using a graphical/logo-like image (for branding purposes), JPEG can introduce ugly artifacts around otherwise clear lines and surfaces.
