### ISSUE TITLE
You don’t have permission to upload or create files here

### ISSUE THREAD

**Issue by timmersr** [nextcloud/server#16238]
I am unable to upload a file in a folder _that I just created myself_, due to permissions...

However, putting it in a subfolder of the newly created folder gives no issues at all, and then moving it a level up is allowed. 

I'm fortunate to run this as VM and made a snapshot of the 15.0.8 production release, so I could revert back to it. 

![afbeelding](https://user-images.githubusercontent.com/31093459/60687056-6e15d980-9eac-11e9-881e-53fe30093c03.png)

![afbeelding](https://user-images.githubusercontent.com/31093459/60687064-78d06e80-9eac-11e9-9a23-ae7b5d43fdf5.png)

![afbeelding](https://user-images.githubusercontent.com/31093459/60687090-a61d1c80-9eac-11e9-9cf5-83b6d05ade59.png)

![afbeelding](https://user-images.githubusercontent.com/31093459/60687351-5f302680-9eae-11e9-9941-8dcd68f07454.png)

![afbeelding](https://user-images.githubusercontent.com/31093459/60687102-b3d2a200-9eac-11e9-9d33-9e91d63127bd.png)

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Would you mind to edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)?

**Comment by timmersr** [comment]
> Would you mind to edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)?

No problem, this was just the quick-and-dirty "warn everyone as soon as possible". 
Will try to have it updated by tomorrow.

**Comment by AaronADev** [comment]
I am facing this issue as well starting immediately after I upgraded Nextcloud 16.0.1 to 16.0.2. Does anyone have any feedback on this issue yet?

Thanks in advance!

**Comment by Andandaran** [comment]
I can't upload to any folder, always get "you don't have permissions"
Before upgrade to 15.0.9 I uploaded as normal user two files - no problem.
Then I login as admin and do the upgrade to 15.0.9, login again as normal user and I can't upload files, I can create folders and notes, but I can't upload files to the newly created folder or the existing ones.

Is there any fast workaround?

**Comment by timmersr** [comment]
This shouldn't happen in a Production-branch.<div>
</div><div>
</div><div>-------- Oorspronkelijk bericht --------</div><div>Van: Andandaran <notifications@github.com> </div><div>Datum: 05-07-19  11:12  (GMT+01:00) </div><div>Aan: nextcloud/server <server@noreply.github.com> </div><div>Cc: timmersr <info-from-github@leesme.nu>, Mention <mention@noreply.github.com> </div><div>Onderwerp: Re: [nextcloud/server] NC 15.0.9 Access-right issues (reverted back to 15.0.8) (#16238) </div><div>
</div>I can't upload to any folder, always get "you don't have permissions"
Before upgrade to 15.0.9 I uploaded as normal user two files - no problem.
Then I login as admin and do the upgrade to 15.0.9, login again as normal user and I can't upload files, I can create folders and notes, but I can't upload files to the newly created folder or the existing ones.

Is there any fast workaround?

**Comment by AaronADev** [comment]
> This shouldn't happen in a Production-branch.<div> </div><div> </div><div>-------- Oorspronkelijk bericht --------</div><div>Van: Andandaran <notifications@github.com> </div><div>Datum: 05-07-19 11:12 (GMT+01:00) </div><div>Aan: nextcloud/server <server@noreply.github.com> </div><div>Cc: timmersr <info-from-github@leesme.nu>, Mention <mention@noreply.github.com> </div><div>Onderwerp: Re: [nextcloud/server] NC 15.0.9 Access-right issues (reverted back to 15.0.8) (#16238) </div><div> </div>I can't upload to any folder, always get "you don't have permissions" Before upgrade to 15.0.9 I uploaded as normal user two files - no problem. Then I login as admin and do the upgrade to 15.0.9, login again as normal user and I can't upload files, I can create folders and notes, but I can't upload files to the newly created folder or the existing ones. Is there any fast workaround?
> […](#)
> -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#16238 (comment)](https://github.com/nextcloud/server/issues/16238#issuecomment-508690329)

Dragging and dropping a file "directly onto a folder" seems to work for now but the blank space below fails. Is yours failing trying to do both? Just curious...

**Comment by Andandaran** [comment]
> > This shouldn't happen in a Production-branch.  -------- Oorspronkelijk bericht --------Van: Andandaran [notifications@github.com](mailto:notifications@github.com) Datum: 05-07-19 11:12 (GMT+01:00) Aan: nextcloud/server [server@noreply.github.com](mailto:server@noreply.github.com) Cc: timmersr [info-from-github@leesme.nu](mailto:info-from-github@leesme.nu), Mention [mention@noreply.github.com](mailto:mention@noreply.github.com) Onderwerp: Re: [nextcloud/server] NC 15.0.9 Access-right issues (reverted back to 15.0.8) (#16238)  I can't upload to any folder, always get "you don't have permissions" Before upgrade to 15.0.9 I uploaded as normal user two files - no problem. Then I login as admin and do the upgrade to 15.0.9, login again as normal user and I can't upload files, I can create folders and notes, but I can't upload files to the newly created folder or the existing ones. Is there any fast workaround?
> > […](#)
> > -- You are receiving this because you were mentioned. Reply to this email directly or view it on GitHub: [#16238 (comment)](https://github.com/nextcloud/server/issues/16238#issuecomment-508690329)
> 
> Dragging and dropping a file "directly onto a folder" seems to work for now but the blank space below fails. Is yours failing trying to do both? Just curious...

I had not tried it, but I do now and it works just as you say: dropping a file on top of a folder name works, but not if you are inside the folder.

**Comment by ChristophWurst** [comment]
@juliushaertl is this possibly related to https://github.com/nextcloud/server/pull/15992?

**Comment by AaronADev** [comment]
> @juliushaertl is this possibly related to #15992?

I'm not entirely sure but I did reproduce the problem cited in #15992 . See the gif below:

![dragndropandpdftest2](https://user-images.githubusercontent.com/12901914/60713941-979c2880-9edf-11e9-90e8-a47b0ea19b5e.gif)

Neither of these problems were there before upgrading from 16.0.1 to 16.0.2, so I imagine they are linked considering they both seem permission based in order to function properly. Any ideas?

**Comment by ChristophWurst** [comment]
@AaronADev backup your `apps/files/js/filelist.js` and apply patch https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/15992.patch then we'll know if the two problems are related and the patch fixes both ;)

**Comment by juliushaertl** [comment]
Hm let me check that.

**Comment by AaronADev** [comment]
> @AaronADev backup your `apps/files/js/filelist.js` and apply patch https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/15992.patch then we'll know if the two problems are related and the patch fixes both ;)

Is there anything to be done to ensure this loads outside of rebooting the server. I restarted the server and both issues still appear.
@ChristophWurst

**Comment by juliushaertl** [comment]
@AaronADev Have you tried a force reload/clear of the browser cache?

**Comment by AaronADev** [comment]
@ChristophWurst AH! It seems to work only when the session is logged out from the browser after the patch is applied. Can ya'll verify this as well?

**Comment by ChristophWurst** [comment]
@AaronADev you just have to force a full page reload. Otherwise the strong caching headers will make your browser use old .js files. Sorry for not mentioning this.

Thanks for testing. Let's get this patch merged and backported then.

**Comment by AaronADev** [comment]
> @AaronADev you just have to force a full page reload. Otherwise the strong caching headers will make your browser use old .js files. Sorry for not mentioning this.
> 
> Thanks for testing. Let's get this patch merged and backported then.

Not a problem. I appreciate ya'lls work.

**Comment by iMoshi** [comment]
Should I wait for an update to NC..? No access to my server, just my cloud :)

**Comment by AaronADev** [comment]
> Should I wait for an update to NC..? No access to my server, just my cloud :)

@iMoshi if you follow the instructions that Christopher posted:

> @AaronADev backup your `apps/files/js/filelist.js` and apply patch https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/15992.patch then we'll know if the two problems are related and the patch fixes both ;)

It should work fine, if you know how to edit those files that is. It is really simple. If you can't access the server you might have to wait until they send it out in an update.

**Comment by kesselb** [comment]
Renamed the issue so that it is easier to find via search

**Comment by extreme-sysadminning** [comment]
> Is there any fast workaround?

Don't upload via Drag+Drop, use the + in the circle instead. Also, Windows desktop client and Android client still work.

**Comment by kyrofa** [comment]
This is an issue in the snap as well.

**Comment by EukalyptusX** [comment]
Sorry, didn't see that at first glance.

Same issue [here](https://github.com/nextcloud/server/issues/16272).

**Comment by arnowelzel** [comment]
> 
> 
> @AaronADev backup your `apps/files/js/filelist.js` and apply patch https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/15992.patch then we'll know if the two problems are related and the patch fixes both ;)

This patch fixed the problem for me. Thanks!

**Comment by a1pilot** [comment]
@kesselb @skjnldsv So these are closed, but when will a real fix be issued in the form of an update?

I note my related bug has also been closed, but it isn't fixed and so is still a live bug.

**Comment by kesselb** [comment]
Fix is merged, Backports to 15 and 16 are merged. I would expect a release today or tomorrow.

**Comment by a1pilot** [comment]
@kesselb Thanks

**Comment by budachst** [comment]
This fix does lead to a blank page - no files listed, on our NC 15.0.9 using FF on Mac. Tried force-reload and logout, force-reload…

**Comment by arnowelzel** [comment]
@budachst Can you open a browser developer console and check if there are any JavaScript errors?

**Comment by budachst** [comment]
Well… if these one count:

TypeError: OCA.Files is undefinedmerged.js:232:24
    <anonym> https://cloudnine.jvm.de/js/files_versions/merged.js?v=6a366de8-10:232
    <anonym> https://cloudnine.jvm.de/js/files_versions/merged.js?v=6a366de8-10:423

I am getting a lot of those…

**Comment by arnowelzel** [comment]
@budachst thanks for the feedback.

**Comment by kayvanaarssen** [comment]
> @AaronADev backup your `apps/files/js/filelist.js` and apply patch https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/15992.patch then we'll know if the two problems are related and the patch fixes both ;)

I can confirm that this fix worked for us in Nextcloud v16.0.2.1

**Comment by carlosgeos** [comment]
Fixed in 16.0.3 :+1:  !

**Comment by arnowelzel** [comment]
JFTR: Fixed for me in 15.0.10 and 16.03 on about 5 different servers
