### ISSUE TITLE
Updater from 13.0.5 fails on missing target version 14.0.13

### ISSUE THREAD

**Issue by StefanGerl** [nextcloud/server#16230]
Steps to reproduce
Updating Nextcloud from 13.0.5 to 14.0.13 using the web updater
Expected behaviour
The update should run through automatically without errors.

Actual behaviour
Verifying integrity
Download failed - Not Found (HTTP 404) - URL: https://download.nextcloud.com/server/releases/nextcloud-14.0.13.zip

And there really is no file for 14.0.13. I looked into the sources and it seems like the version 14.0.13 is returned by an update server.

**Comment by soundzofstatic** [comment]
+1  - Same issue here. Upgrading from 13.0.0 to 14.0.13.

I'm trying to figure out what provides the pointer to the newest version available. If we can override that, we can point it to 14.0.12, which does exist.

**Comment by soundzofstatic** [comment]
I found where the version displayed on /index.php/settings/admin comes from. It's held in the database: oc_appconfig table, held in the lastupdateResult configkey record. However, **don't bother changing it** to a version where a download exists. Upon clicking on "open updater" it would appear that it phones home and then grabs the latest version anyway, which would then point it back to 14.0.13.  Sigh.

**Comment by segdy** [comment]
+1 :-(

**Comment by stevenobird** [comment]
Same issue here. Download still missing.

**Comment by pjb-mcc** [comment]
Same problem exactly. nextcloud-14.0.12.zip file is there but not nextcloud-14.0.13.zip. We should wait for it ?

**Comment by StefanGerl** [comment]
You could edit the updater/index.php file and hardcode the link to 14.0.12 to the "downloader method", and also add a early return true to the "validation method" which is checking a hash, retrieved from update server, corresponding to 14.0.13, and so will fail otherwise, and than remove that code after update. But that is a really dirty workaround solution.

I guess it is very easy for nextcloud people to fix the "update" server which is returning version 14.0.13 and its hash, to just return the same for 14.0.12?

**Comment by StefanGerl** [comment]
... or to upload 14.0.13 if it is an existing version. But I guess there would be more bug reports if a official release download is missing on the official download server? I guess its more that the update server returns a wrong version for version 13 updater?

Are all having this issue trying to upgrade from a nextcloud major version 13?

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure @MorrisJobke

**Comment by skerbis** [comment]
how can I fix it? ..

**Comment by kesselb** [comment]
> how can I fix it? ..

You can't. For some reason nextcloud 14.0.13 is not uploaded yet but announced by the updater. This might be a technical problem or the update is delayed for some reason (e.g. some problems with instances). I recommend you to postpone the update for the moment.

**Comment by skerbis** [comment]
What happens when I upgrade manually to 14.0.13 is an update to 15 possible?

**Comment by skerbis** [comment]
Yepp! it is possible

**Comment by stevenobird** [comment]
> 
> 
> > how can I fix it? ..
> 
> You can't. For some reason nextcloud 14.0.13 is not uploaded yet but announced by the updater. This might be a technical problem or the update is delayed for some reason (e.g. some problems with instances). I recommend you to postpone the update for the moment.

It is uploaded, but in the prereleases folder... https://download.nextcloud.com/server/prereleases/

**Comment by anlx-sw** [comment]
is there any way to bypass the missing 14.0.13 version and go directly from 13.0.12 to 15.x oder 16.x with the cli updater? 

I updated php to 7.3 for another application and now try to get nextcloud running with the newer php version (nc 13 is not supporting php 7.3). as the upgrade process is broken now I can't do that step.

 or is there already any eta when the updater problem is fixed? (as the update is not working now for already  two days).

**Comment by kesselb** [comment]
Try the https://docs.nextcloud.com/server/14/admin_manual/maintenance/manual_upgrade.html and upgrade to https://download.nextcloud.com/server/releases/nextcloud-14.0.12.tar.bz2. After that you can upgrade to 15 with the updater.

**Comment by J-Doc** [comment]
@kesselb Unfortunately, it's not that simple. You must edit index.php and force version & signature validation because update from 14.0.12 still try to dl 14.0.13.

**Comment by kesselb** [comment]
> Unfortunately, it's not that simple. 

It depends on the selected update channel. Let's assume you're using 14.0.12

- Update channel `production`: 14.0.13
- Update channel `stable`: 15.0.9

**Comment by computersalat** [comment]
What is the difficulty to publish the missing files on [download.nextcloud.com](https://download.nextcloud.com/server/releases/) ???
Why not referencing the ```Updater``` to make use of the github Release files ??? Would be one Error less.
BTW I do not really see the benefit of having the files **away** from github on an **extra** download source ..

**Comment by computersalat** [comment]
> 
> It is uploaded, but in the prereleases folder... https://download.nextcloud.com/server/prereleases/

clever solution :-1:

**Comment by stevenobird** [comment]
I just got an answer via Twitter from them:

> [...] our script which publishes tarballs failed. We will look into that later today and push it. Sorry, this went wrong just before the weekend...

**Comment by MorrisJobke** [comment]
The files are now in place. Sorry for the inconvenience. Start the updater again and it should properly fetch the files.
