### ISSUE TITLE
Web based update to 16.0.2 stuck in loading animation

### ISSUE THREAD

**Issue by foxable** [nextcloud/server#16242]
I just tried to install the update to 16.0.2 through the web based updater. The first phase of the update process within the admin succeeded without any errors. I then switched to the final update page (which is available after the question "Keep maintenance mode active?"), but when I hit the "Start update" button, I was stuck in a loading animation, with nothing happening ("Detailed logs" were empty):

![grafik](https://user-images.githubusercontent.com/12152164/60705567-bca49180-9f07-11e9-9e91-cfe0afa062a9.png)

### Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MySQL

**PHP version:** PHP 7.3.6

**Nextcloud version:** 16.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 16.0.1.1

**Where did you install Nextcloud from:** Web based updater (nextcloud.com) 

**Signing status:**
Unknown (cannot login anymore)

**List of activated apps:**

<details>
<summary>App list</summary>

```
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bookmarks: 1.0.6
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.4
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 2.1.2
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwritewebroot": "\/",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "installed": true,
        "log_rotate_size": 10485760,
        "activity_expire_days": "365",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "updater.release.channel": "stable",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar",
            "tasks"
        ],
        "defaultapp": "deck",
        "trashbin_retention_obligation": "auto, 30",
        "versions_retention_obligation": "auto, 30",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 67

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Not available
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{
  [...],
  "app":"jsresourceloader",
  "method":"GET",
  "url":"\/index.php",
  "message":"Could not find resource js\/config.js to load",
  "version":"16.0.1.1",
  [...]
}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
There is a 404 for the file `merged-template-prepend.js`, which is requested for the path `/js/core/` but is actually located under `/core/js/`.
```
</details>

**Comment by ChristophWurst** [comment]
It seems that the issue you have created is lacking the essential informations to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by foxable** [comment]
Sorry for the missing information, I updated my first comment and tried to add all information that is available to me. If you need any more information, please let me know. Thank you in advance.

**Comment by foxable** [comment]
Since the update didn't get far enough to modify the database, I decided to update manually and replace all files. This allowed to complete the update process. It seems that there were some files missing after the download through the web based updater,
