### ISSUE TITLE
Your server has no Nextcloud Subscription

### ISSUE THREAD

**Issue by GanimanSwift** [nextcloud/server#16258]
### Steps to reproduce
1. Have over 500 registered users
2. Be an administrator
3. Get spammed by the system with emails: "Your server has no Nextcloud Subscription."

### Expected behaviour
Maybe get 1 of these e-mails instead of one every 15 minutes. Or have a way to shut them off.

### Actual behaviour
I get an e-mail every 15 minutes.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 16.01

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

PLEASE PROVIDE A WAY TO DISABLE THESE EMAILS

**Comment by Nils160988** [comment]
It will probably help if you disable the support app (see #11811).

**Comment by kesselb** [comment]
cc @MorrisJobke

**Comment by MorrisJobke** [comment]
> Maybe get 1 of these e-mails instead of one every 15 minutes. Or have a way to shut them off.

Ummm ... really? It should once per month or so.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
