### ISSUE TITLE
Integrate LDAP-users as contacts

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#16261]
**Is your feature request related to a problem? Please describe.**
Nextcloud users from an ldap backend do not show up as contacts in the contacts app which would be nice.

**Describe the solution you'd like**
I would like an option within the LDAP configuration like "Show ldap users in contacts app".

**Describe alternatives you've considered**
Manually exporting the ldap data, convert it to a format readable to the contacts app and import it, maybe using a cron job to keep changes in the ldap.

**Additional context**
Not sure if this is correct here or needs to be moved to the contacts or ldap app, please move if necessary.

**Comment by skjnldsv** [comment]
https://apps.nextcloud.com/apps/ldap_contacts_backend
