### ISSUE TITLE
update error Nextcloud 16.02

### ISSUE THREAD

**Issue by fireeater112** [nextcloud/server#16266]
Hi there,

I've tried to update from NC 16.01 to 16.02 via the Web Updater
Unfortunatelly, the update failed with the following note:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

I've had this behavior not before for an update via the web updater

regards
fireeater

**Comment by Nils160988** [comment]
Which database (and version) do you use? Please have a look at the existing issues, there are a few which might be related to your issue.

**Comment by fireeater112** [comment]
10.1.35-MariaDB FreeBSD Port
I remeber that I've updated Maria DB with the latest NC update to utf8mb4
with the following commands.
ALTER DATABASE Nextcloud Character set utf8mb4..........
I'm sorry but I'm not so familiar with the database settings, but Nextcloud has worked like a charm till the try to update to 16.02

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: Please check the reports below for more information. I'm sure one of the solutions will work for you.

https://github.com/nextcloud/server/issues/15739
https://github.com/nextcloud/server/issues/15058

If you want to use utf8mb4 please make sure that your database server is setup properly: https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html
