### ISSUE TITLE
Errors, bugged functionality somewhere

### ISSUE THREAD

**Issue by dEROZA** [nextcloud/server#16263]
loss connection with files after folder renaming, and folder was broken, cloud start detects it as simple file. and other types of bugs..

`

Level | App | Message |   | Time
-- | -- | -- | -- | --
Fatal | webdav | Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'UPDATE `oc_filecache` SET `storage` = ?, `path` = ?, `path_hash` = ?, `name` = ?, `parent` = ? WHERE `fileid` = ?' with params [4, "__groupfolders\/4\/\u0412\u0423\u0417\u042b\/\u0418\u0420\u041a\u0423\u0422\u0421\u041a\/\u0418\u0420\u041d\u0418\u0422\u0423", "cc1fb22f1b9887f73d837c1a3ee54a67", "\u0418\u0420\u041d\u0418\u0422\u0423", 2952, 2951]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '4-cc1fb22f1b9887f73d837c1a3ee54a67' for key 'fs_storage_path_hash' |   | 2019-07-06T22:57:23+0800
-- | -- | -- | -- | --
Error | PHP | file_get_contents(/var/www/nextcloud/external/data/nextcloud/data//__groupfolders/4/ыы г. /вв/данных-backup-codes.txt): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216 |   | 2019-07-06T22:57:11+0800
Error | PHP | file_get_contents(/var/www/nextcloud/external/data/nextcloud/data//__groupfolders/4/ыы г. /вв/данных-backup-codes.txt): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#216

Level | App | Message |   | Time
-- | -- | -- | -- | --
Error | remote | Error: Call to a member function getDisplayName() on null |   | 2019-07-06T22:08:42+0800
-- | -- | -- | -- | --
Error | remote | Error: Call to a member function getDisplayName() on null |   | 2019-07-06T22:05:26+0800
Error | remote | Error: Call to a member function getDisplayName() on null |   | 2019-07-06T22:03:50+0800
Error | remote | Error: Call to a member function getDisplayName() on null |   | 2019-07-06T22:03:11+0800

Error | core | OCP\Files\NotPermittedException: |   | 2019-07-06T10:23:30+0800
-- | -- | -- | -- | --
Error | core | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:30+0800
Error | public | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:30+0800
Error | no app in context | OCP\Files\NotFoundException: /🗽 Администрация///512x512bb.jpg not found while trying to get owner |   | 2019-07-06T10:23:30+0800
Error | core | OCP\Files\NotPermittedException: |   | 2019-07-06T10:23:23+0800
Error | core | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:23+0800
Error | public | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:23+0800
Error | no app in context | OCP\Files\NotFoundException: /🗽 Администрация///Центр хранения данных-backup-codes.txt not found while trying to get owner |   | 2019-07-06T10:23:23+0800
Error | core | OCP\Files\NotPermittedException: |   | 2019-07-06T10:23:11+0800
Error | core | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:11+0800
Error | public | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:11+0800
Error | no app in context | OCP\Files\NotFoundException: /🗽 Администрация///vss_shot.wav not found while trying to get owner |   | 2019-07-06T10:23:11+0800
Error | core | OCP\Files\NotPermittedException: |   | 2019-07-06T10:23:07+0800
Error | core | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:07+0800
Error | public | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:07+0800
Error | no app in context | OCP\Files\NotFoundException: /🗽 Администрация///cc_20190427_212745.reg not found while trying to get owner |   | 2019-07-06T10:23:07+0800
Error | core | OCP\Files\NotPermittedException: |   | 2019-07-06T10:23:01+0800
Error | core | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:01+0800
Error | public | Error: Call to a member function getChecksum() on boolean |   | 2019-07-06T10:23:01+0800
Error | no app in context | OCP\Files\NotFoundException: /🗽 Администрация///php-fpm installed log.txt not found while trying to get owner |   | 2019-07-06T10:23:01+0800
Error | no app in context | Swift_TransportException: Connection could not be established with host 127.0.0.1 [Connection refused #111] |   | 2019-07-06T07:59:16+0800
Error | no app in context | Swift_TransportException: Connection could not be established with host 127.0.0.1 [Connection refused #111] |   | 2019-07-05T22:21:07+0800
Error | PHP | TypeError: Argument 2 passed to OC\Core\Controller\CollaborationResourcesController::removeResource() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 166 at /var/www/nextcloud/core/Controller/CollaborationResourcesController.php#145 |   | 2019-07-05T21:04:57+0800
Error | PHP | TypeError: Argument 2 passed to OC\Core\Controller\CollaborationResourcesController::removeResource() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 166 at /var/www/nextcloud/core/Controller/CollaborationResourcesController.php#145 |   | 2019-07-05T21:04:57+0800
Error | PHP | TypeError: Argument 2 passed to OC\Core\Controller\CollaborationResourcesController::removeResource() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 166 at /var/www/nextcloud/core/Controller/CollaborationResourcesController.php#145 |   | 2019-07-05T21:04:56+0800
Error | PHP | exif_read_data(Березка.jpg): Process tag(x010D=DocumentNam): Illegal components(0) at /var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php#215 |   | 2019-07-05T21:03:07+0800
Error | PHP | exif_read_data(Березка.jpg): Process tag(x010D=DocumentNam): Illegal components(0) at /var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php#215 |   | 2019-07-05T20:44:06+0800
Error | PHP | exif_read_data(Схема для Кирхгофа.jpg): Process tag(x010D=DocumentNam): Illegal components(0) at /var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php#215 |   | 2019-07-05T20:34:24+0800
Fatal | webdav | OCP\Lock\LockedException: "Video/VID_20190616_081451.mp4" is locked |   | 2019-07-05T20:28:27+0800
Error | no app in context | OCP\Lock\LockedException: "files/298e7dab501cd4639e6fc1032b3b8d38" is locked, existing lock on file: 2 shared locks |   | 2019-07-05T20:28:27+0800
Fatal | webdav | OCP\Lock\LockedException: "Video/VID_20190616_081451.mp4" is locked |   | 2019-07-05T20:28:21+0800
Error | no app in context | OCP\Lock\LockedException: "files/298e7dab501cd4639e6fc1032b3b8d38" is locked, existing lock on file: 2 shared locks |   | 2019-07-05T20:28:21+0800
Fatal | webdav | OCP\Lock\LockedException: "Video/VID_20190616_081954.mp4" is locked |   | 2019-07-05T20:26:10+0800
Error | no app in context | OCP\Lock\LockedException: "files/d98d81165f29f6b263e27ff163a2bb87" is locked, existing lock on file: 2 shared locks |   | 2019-07-05T20:26:10+0800
Fatal | webdav | OCP\Lock\LockedException: "Video/VID_20190703_182240.mp4" is locked |   | 2019-07-05T20:25:24+0800
Error | no app in context | OCP\Lock\LockedException: "files/f03b5ca904438a9c2e697d91935c504d" is locked, existing lock on file: 3 shared locks |   | 2019-07-05T20:25:24+0800
Fatal | webdav | OCP\Lock\LockedException: "Video/VID_20190703_182240.mp4" is locked |   | 2019-07-05T20:25:16+0800
Error | no app in context | OCP\Lock\LockedException: "files/f03b5ca904438a9c2e697d91935c504d" is locked, existing lock on file: 2 shared locks |   | 2019-07-05T20:25:16+0800
Error | index | Swift_TransportException: Connection could not be established with host 127.0.0.1 [Connection refused #111] |   | 2019-07-05T20:14:37+0800
Error | index | Swift_TransportException: Connection could not be established with host 127.0.0.1 [Connection refused #111]

`

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
