### ISSUE TITLE
Trusted domain error. "xx.xx.xx.x" tried to access using "*.*.com" as host.

### ISSUE THREAD

**Issue by rbmanian75** [nextcloud/server#16264]
I have installed the . nextcloude docker image and its working fine when i am trying to access nextcloud from local network. If i go to public network access the same site. It is giving the above mentioned error.

added the above ip and host ton trustedips section of config.php. thats also giving the same error.

Is there anyway to solve the issue?

Thanks

**Comment by gary-kim** [comment]
Welcome!
Just to clarify, did you actually use wildcards or the FQDN?
Would you mind pasting in your `config.php`? Its part of the issue template.

**Comment by rbmanian75** [comment]
Yes i am using FQDN. i have nextcloud docker container running on synology. when i try to reach the nextcloud from my local network it works fine. In  synology i am using reverseproxy that points to the container and my dns server points to the synology. I am hosting the gitea server the same way and it worked. But with this i have problem.

my confg.php looks like this
 'trusted_domains' =>
  array (
      0 => '10.0.0.**:400',
      1 => 'xxxxx.xxxxxxx.com:400',
      2 => '77.zz.zz.120:400',
      4 => 'localhost:400',
  ),

**Comment by rbmanian75** [comment]
I have this error on in the console.

![image](https://user-images.githubusercontent.com/1324600/60755217-7bce7a80-9fe4-11e9-9b11-ec1da054d7e0.png)

**Comment by rbmanian75** [comment]
some how I made it to work by adding custom header host in the reverse proxy. But I am not able to make it work for mobile and desktop clients. I am getting  Access Forbidden State token does not match with user/password, and CSRF check failed if I use app token. 

Could you please let me know how can I modify the server address shown in the Settings/Mobile/Desktop page

Thanks

**Comment by gary-kim** [comment]
> some how I made it to work by adding custom header host in the reverse proxy. But I am not able to make it work for mobile and desktop clients. I am getting Access Forbidden State token does not match with user/password, and CSRF check failed if I use app token.

If you don't mind, could you let me know how your reverse proxy is set up?

> Could you please let me know how can I modify the server address shown in the Settings/Mobile/Desktop page

To modify the address, you can add `overwritehost` to your `config/config.php` file. Take a look [here](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations).

**Comment by rbmanian75** [comment]
sorry I did not know that you can overwrite the host in the config.php if proxy is used. Now everything works fine. Thank you very much.

If you don't mind, could you let me know how your reverse proxy is set up?

![Selection_002](https://user-images.githubusercontent.com/1324600/60757727-1d19f880-a006-11e9-9652-f2f12291731d.png)
