### ISSUE TITLE
How to remove the ridiculous footer ads ?

### ISSUE THREAD

**Issue by akhilleusuggo** [nextcloud/server#16278]
I mean , I'm new user to nextcloud , but it's ridiculous to make advertisement on the MAIN page on the login section . I mean c'mon , you don't even offer a plugin or something to remove it . I've been reading and looking for some solution 2h now , and people thinking the same way , that this is ridiculous .

''Nextcloud a safe home for all your data'' . Let me tell something to the admins of this project : This is a stupid way to advertise and look so unprofessional . Just make your own storage server and enough with this .

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/theming.html

Please use the [forum](https://help.nextcloud.com) for setup related question. Thank you :+1:
