### ISSUE TITLE
Drag and Drop File Upload Permission Error

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/server#16289]
Nextcloud 16.0.2 (updated 2019-07-08)
Debian 10

Updated to Nextcloud 16.0.2 and now the drag and drop upload feature fails due to "you don't have permission to create files here".

![image](https://user-images.githubusercontent.com/665111/60803645-97b45680-a173-11e9-99c7-d2575dcfbf58.png)

This occurs when dragging a file from Windows 7 File Explorer and dropping it within the folder, or onto the folder in the tree (Chrome 75.0.3770.100).

If I click the plus icon and choose "upload file", this works without errors.

No errors in Nextcloud.log, nor in the console (at least, not in relation to this function).

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Please check this report for more information: https://github.com/nextcloud/server/issues/16238
