### ISSUE TITLE
Updater failing cause of Download file missing

### ISSUE THREAD

**Issue by computersalat** [nextcloud/server#16281]
Updater is failing to update from 14.0.8 to 14.0.13 cause it simply can't find a file for installation.
See attached screenshot for more info
![20190707_Updater_failing_cause_of_missing_file](https://user-images.githubusercontent.com/161880/60767976-a0e3eb80-a0bf-11e9-858f-6fab7a361625.jpg)

### Steps to reproduce
1. Try to update your 14.0.x version to latest announced version 14.0.13
2.
3.

### Expected behaviour
Updater should find the download file for update

### Actual behaviour
There is no nextcloud ZIP of 14.0.13 at download location

Release the missing file to download location please

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Please see https://github.com/nextcloud/server/issues/16230 for more information. I have no information why 14.0.13 is missing. This could be a problem with the release process or the update failed on some instances and were postponed. Sorry for the noise.
