### ISSUE TITLE
passwords app 500 Internal Error after update to 16.0.2

### ISSUE THREAD

**Issue by maxileith** [nextcloud/server#16280]
I've updated Nextcloud to version 16.0.2 and now the passwords app reports a 500 error.

sudo -u www-data php occ app: check-code passwords returns:

Analysing /var/www/nextcloud/apps/passwords/lib/Hooks/FolderHook.php
 1 errors
    line  135: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Hooks/TagHook.php
 2 errors
    line   70: != - is discouraged
    line  124: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Hooks/PasswordHook.php
 2 errors
    line  103: != - is discouraged
    line  176: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Controller/Api/FolderApiController.php
 1 errors
    line  192: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Controller/Api/Legacy/LegacyPasswordApiController.php
 1 errors
    line  244: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Middleware/ApiSessionMiddleware.php
 2 errors
    line   81: != - is discouraged
    line  116: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Cron/CheckPasswordsJob.php
 2 errors
    line  107: != - is discouraged
    line  113: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Migration/DatabaseRepair/AbstractModelRepair.php
 1 errors
    line   96: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Migration/Legacy/LegacyPasswordMigration.php
 1 errors
    line  280: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Services/Object/AbstractService.php
 2 errors
    line  152: == - is discouraged
    line  152: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Services/Object/PasswordTagRelationService.php
 1 errors
    line  100: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Services/WebsitePreviewService.php
 2 errors
    line  224: != - is discouraged
    line  226: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Services/WordsService.php
 2 errors
    line   78: == - is discouraged
    line  153: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Services/ValidationService.php
 1 errors
    line  149: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Services/EnvironmentService.php
 1 errors
    line  422: OC_User - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/User/DeleteUserDataHelper.php
 1 errors
    line  128: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/ApiObjects/AbstractObjectHelper.php
 3 errors
    line   90: != - is discouraged
    line  135: != - is discouraged
    line  136: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Words/SnakesWordsHelper.php
 7 errors
    line   65: == - is discouraged
    line   66: == - is discouraged
    line   67: == - is discouraged
    line   71: == - is discouraged
    line   72: == - is discouraged
    line   76: == - is discouraged
    line   80: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Words/LocalWordsHelper.php
 1 errors
    line   56: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Token/ApiTokenHelper.php
 1 errors
    line  183: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Survey/ServerReportHelper.php
 1 errors
    line  183: OC_App - private class must not be instantiated
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/SecurityCheck/AbstractSecurityCheckHelper.php
 1 errors
    line  134: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/SecurityCheck/BigLocalDbSecurityCheckHelper.php
 2 errors
    line  125: == - is discouraged
    line  132: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Http/FileDownloadHelper.php
 2 errors
    line   44: == - is discouraged
    line   57: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Http/RequestHelper.php
 1 errors
    line  276: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Image/AbstractImageHelper.php
 4 errors
    line   64: != - is discouraged
    line   74: != - is discouraged
    line   92: == - is discouraged
    line   92: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Image/GdHelper.php
 5 errors
    line  176: != - is discouraged
    line  177: == - is discouraged
    line  182: == - is discouraged
    line  184: == - is discouraged
    line  188: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Image/ImagickHelper.php
 4 errors
    line  172: != - is discouraged
    line  187: == - is discouraged
    line  189: == - is discouraged
    line  191: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Icon/FallbackIconGenerator.php
 1 errors
    line  177: OC_Image - private class must not be instantiated
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Preview/PageresCliHelper.php
 1 errors
    line   54: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Preview/AbstractPreviewHelper.php
 1 errors
    line  154: != - is discouraged
Analysing /var/www/nextcloud/apps/passwords/lib/Helper/Sharing/ShareUserListHelper.php
 2 errors
    line   98: == - is discouraged
    line  118: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/templates/admin/settings.php
 2 errors
    line  178: == - is discouraged
    line  197: == - is discouraged
Analysing /var/www/nextcloud/apps/passwords/templates/partials/https.php
 1 errors
    line   17: OC_User - Static method of private class must not be called
Analysing /var/www/nextcloud/apps/passwords/templates/partials/https_debug.php
 1 errors
    line   12: OC_User - Static method of private class must not be called
Database schema error: Name of table *dbprefix*passwords_entity_password is too long (25), max. 27 characters (21
Database schema error: Name of table *dbprefix*passwords_entity_password_revision is too long (34), max. 27 chara
Database schema error: Name of table *dbprefix*passwords_entity_password_revision is too long (34), max. 27 chara
Database schema error: Name of table *dbprefix*passwords_entity_folder is too long (23), max. 27 characters (21 c
Database schema error: Name of table *dbprefix*passwords_entity_folder_revision is too long (32), max. 27 charact
Database schema error: Name of table *dbprefix*passwords_entity_folder_revision is too long (32), max. 27 charact
Database schema error: Name of table *dbprefix*passwords_entity_tag_revision is too long (29), max. 27 characters
Database schema error: Name of table *dbprefix*passwords_entity_tag_revision is too long (29), max. 27 characters
Database schema error: Name of table *dbprefix*passwords_relation_password_tag is too long (31), max. 27 characte
Database schema error: Name of table *dbprefix*passwords_relation_password_tag is too long (31), max. 27 characte
Database schema error: Name of table *dbprefix*passwords_entity_share is too long (22), max. 27 characters (21 ch
Database schema error: Name of table *dbprefix*passwords_entity_session is too long (24), max. 27 characters (21
Database schema error: Name of table *dbprefix*passwords_entity_keychain is too long (25), max. 27 characters (21
Database schema error: Name of table *dbprefix*passwords_entity_challenge is too long (26), max. 27 characters (2
App is not compliant

Before the update, the long database names did not cause any problems.

I  hope someone can help me. Thanks in advance.

OS: Debian 9
Web Server: apache2

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Please check https://github.com/marius-wieschollek/passwords/issues/163 for more information.
