### ISSUE TITLE
How to view o list with occ command line, the shared forder or files?

### ISSUE THREAD

**Issue by AGDELTA** [nextcloud/server#16291]
I like nextcloud and I use it a lot. But I have a question, could the folders shared by a user be listed from the command line? I've been looking at the documentation to do it with "occ", but I can not find anything. Greetings and thank you

**Comment by kesselb** [comment]
There is no command to list shared folders or files with occ.

**Comment by szaimen** [comment]
Please see this app: https://apps.nextcloud.com/apps/sharelisting

**Comment by Saakshi-aa** [comment]
> I like nextcloud and I use it a lot. But I have a question, could the folders shared by a user be listed from the command line? I've been looking at the documentation to do it with "occ", but I can not find anything. Greetings and thank you

Are you able to list the files or folder in the Shared folder..?If yes. Please provide me the steps.
