### ISSUE TITLE
[Bug] Admin Users Panel is blank

### ISSUE THREAD

**Issue by LoHub** [nextcloud/server#16299]
### Steps to reproduce
1. I installed the 15.0.9 NextCloud Version
2. I obtained the error describe here and followed instructions to solve it with sucess. https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740?u=moonlies
3. As admin, when I try to show Users panel,  I obtain a blank page like on screen shot below.
4. I tried to repair with `sudo -u www-data php occ maintenance:repair` without success.

![screenshot](https://user-images.githubusercontent.com/11139973/60835229-e3422100-a1c2-11e9-83ec-c1ccd3c06d39.png)

### Server configuration

**Operating system**: Linux vps695183 4.9.0-9-amd64 #1 SMP Debian 4.9.168-1+deb9u2 (2019-05-13) x86_64 GNU/Linu

**Web server:** Apache/2.4.25 (Debian) 2019-04-02T19:05:13

**Database:** mysql  Ver 15.1 Distrib 10.1.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group

**Nextcloud version:** (see Nextcloud admin page) 15.0.9 NextCloud Version

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from an older NexCloud Production channel

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - registration: 0.4.6
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - twofactor_totp: 2.1.2
  - twofactor_u2f: 2.1.3
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.9.1",
        "overwrite.cli.url": "https:\/\/cloud.krhacken.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "production",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

~~**Are you using external storage, if yes which one:** local/smb/sftp/...~~

**Are you using encryption:** no

~~**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...~~

### Client configuration
**Browser:** Safari Version 12.1.1 (14607.2.6.1.1)

**Operating system:** macOS Mojave 10.14.5 (18F132)

#### Web server error log
<details>
<summary>Web server error log</summary>
```
[Mon Jul 08 20:52:27.214483 2019] [authz_core:error] [pid 18336] [client ***REMOVED SENSITIVE VALUE***:52381] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
[Mon Jul 08 20:52:34.837183 2019] [authz_core:error] [pid 14929] [client ***REMOVED SENSITIVE VALUE***:52384] AH01630: client denied by server configuration: /var/www/nextcloud/data/.ocdata
```
</details>

Thank you for your help.

**Comment by nicogodet** [comment]
Clear your browser cache.
https://github.com/nextcloud/server/issues/16252

**Comment by LoHub** [comment]
That's right. Thank you.
