### ISSUE TITLE
Chromecast loading a shared url, 302 returned

### ISSUE THREAD

**Issue by Zuikkis** [nextcloud/server#16298]
### Steps to reproduce
1. Share a video url, append /download to get direct link to media
2. Try to play that with Chromecast, with any software, for example pychromecast python api

### Expected behaviour
Video should play!

### Actual behaviour
Video does not play. When looking at apache access log, it shows that apache is giving "302" response to Chromecast's request. When wgetting the same file on command line, I get "200" and the file loads.

### Server configuration

**Operating system**:
Debian 10

**Web server:**
Apache 2.4.38-3

**Database:**
mariadb 10.3

**PHP version:**
php 7.3

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com

**Comment by Zuikkis** [comment]
Here's snippet from access.log.. first my wget, then Chromecast on the same url. Chromecast keeps trying but always gets 302. 

The link in question is https://zuik.org/nextcloud/index.php/s/7r3AbTQzAyjmBN5/download
Feel free to try it. :)


```
85.76.7.94 - - [08/Jul/2019:22:14:12 +0300] "GET /nextcloud/index.php/s/7r3AbTQzAyjmBN5/download HTTP/1.1" 200 1318285 "-" "Wget/1.19.4 (linux-gnu)"

85.76.7.94 - - [08/Jul/2019:22:15:18 +0300] "GET /nextcloud/index.php/s/7r3AbTQzAyjmBN5/download HTTP/1.1" 302 4442 "https://www.gstatic.com/cast/sdk/default_receiver/1.0/app.html?skin=h
ttps://www.gstatic.com/eureka/player/0000/skins/cast/skin.css" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.47 Safari/537.36 CrKey/1.36.159268"
85.76.7.94 - - [08/Jul/2019:22:15:18 +0300] "GET /nextcloud/index.php/s/7r3AbTQzAyjmBN5/download HTTP/1.1" 302 1195 "-" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.47 Safari/537.36 CrKey/1.36.159268"
85.76.7.94 - - [08/Jul/2019:22:15:19 +0300] "GET /nextcloud/index.php/s/7r3AbTQzAyjmBN5/download HTTP/1.1" 302 1195 "-" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.47 Safari/537.36 CrKey/1.36.159268"

```

**Comment by Zuikkis** [comment]
I noticed that if I reboot chromecast, I can get it to stream correctly but only once! A second attempt fails. 

public links with "/download" fail with 302, links generated with android app's "stream to"-function fail with 503.

Here's again bit of a log:

```
85.76.32.60 - - [09/Jul/2019:09:14:17 +0300] "GET /nextcloud/remote.php/direct/mxmPtKwmrvKVmYcsB0M4nO2om5Xz3XsjVmvqwGFZ6s17ycS2Q6KmZxl8KkdN HTTP/1.1" 206 65357069 "https://www.gstatic.com/cast/sdk/default_receiver/1.0/app.html
?skin=https://www.gstatic.com/eureka/player/0000/skins/cast/skin.css" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.47 Safari/537.36 CrKey/1.36.159268"
85.76.32.60 - - [09/Jul/2019:09:17:13 +0300] "GET /nextcloud/remote.php/direct/mxmPtKwmrvKVmYcsB0M4nO2om5Xz3XsjVmvqwGFZ6s17ycS2Q6KmZxl8KkdN HTTP/1.1" 503 1349 "https://www.gstatic.com/cast/sdk/default_receiver/1.0/app.html?ski
n=https://www.gstatic.com/eureka/player/0000/skins/cast/skin.css" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.47 Safari/537.36 CrKey/1.36.159268"
```

First is the  successful streaming. I interrupted it to start again, and that time it failed.

It might be that Chromecast keeps several connections open, perhaps that triggers the bruteforce protection? I tried whitelisting my ip but it had no effect, but perhaps the old ban is still present and not removed by whitelisting? Bruteforce protection's documentation is a bit vague..

**Comment by Zuikkis** [comment]
It is a cookie issue. After rebooting Chromecast and requesting a file, it performs HTTP GET without any cookies set. This works and it gets a file.

Later (even hours later!) if trying to play another (or same) file, Chromecast does HTTP GET but this time it has two cookies set in the request headers.. Session cookie and the instanceid=xxx cookie. But NextCloud responds with 302 and Chromecast does not get a file.

I guess Nextcloud gives the cookies on the first request, then Chromecast continues to use those on the second request.

I tried csrf.optout setting to disable same site cookie protection for Chromecast, but that didn't help.

**Comment by Zuikkis** [comment]
Ok, I found the bug. Can be reproduced with wget. 

`wget -d --save-cookies cookies.txt --keep-session-cookies https://zuik.org/nextcloud/index.php/s/7r3AbTQzAyjmBN5/download`

Cookies.txt now contains four cookies: 

nc_sameSiteCookiestrict, mc_sameSiteCookielax, oc_sessionPassphrase and the instanceid. 

Chromecast doesn't seem to like the samesite cookies, it does not send them. Apparently it only likes session cookies. So we delete those lines from cookies.txt, so it only includes sessionpassphrase and instanceid.

Now wget again, this time with --load-cookies so they get loaded:

`wget -d --load-cookies cookies.txt --keep-session-cookies https://zuik.org/nextcloud/index.php/s/7r3AbTQzAyjmBN5/download`

Now we get the 302! NextCloud notices that samesite cookies are missing and resends them, and send Location: header with the same page so client reloads it. Even chromecast DOES reload the page, but it still won't use the samesite cookies so it gets the same redirect over and over again. After a few tries it gives up.

Now, let's try csrf.output in the config.php:

```
  'csrf.optout' => array(
        '/^WebDAVFS/', // OS X Finder
        '/^Microsoft-WebDAV-MiniRedir/', // Windows webdav drive
        '/Wget/', // Wget    
  ),

```

This should disable samesite checks for Wget, right?

`wget -d --save-cookies cookies.txt --keep-session-cookies https://zuik.org/nextcloud/index.php/s/7r3AbTQzAyjmBN5/download`

cookies.txt now only contains two cookies, sessionpassphrase and instanceid.. Promising! Now let's try --load-cookies:

`wget -d --load-cookies cookies.txt --keep-session-cookies https://zuik.org/nextcloud/index.php/s/7r3AbTQzAyjmBN5/download`

... we get 302 again. Nextcloud sends the samesite cookies and forces redirect.

So, csrf.optout config option is broken. It does not disable samesite cookies completely, it only works if no other cookies are being used at the same time!

In file "lib/private/AppFramework/Http/Request.php" line 508 is a function "cookieCheckRequired()". If you force that to return false, chromecast is able to stream. But that's not a correct fix of course, since it disables cookie checks completely..

A few lines below is a comment:
```
         * Checks if the strict cookie has been sent with the request if the request
         * is including any cookies.

```

... That is the problem exactly. Chromecast sends session cookies but not same site cookies. Perhaps all cookies should be cleared if same site cookies are not present? That would work, and wouldn't require using csrf.optout which is not really very safe because user agent can be easily faked.

**Comment by Zuikkis** [comment]
Just tested, the Android app's "stream to.." function works fine if Chromecast's samesite cookie check is disabled, with this in config:

  'csrf.optout' => array(
        '/^WebDAVFS/', // OS X Finder
        '/^Microsoft-WebDAV-MiniRedir/', // Windows webdav drive
        '/CrKey/', // Chromecast
  ),

I'm not closing this issue because the other bug with public /download link is still present.

**Comment by kesselb** [comment]
cc @rullzer @tobiasKaminsky

**Comment by Zuikkis** [comment]
Any chance to fix this?

This also seems to break hotlinking shared images to forums, with recent Firefox or Chrome.

Nextcloud always sends the samesite cookies and session cookies, even for publicly shared links. This already is a bit weird and unnecessary, but read on..

Samesite cookies are sent as permanent cookies, which are then ignored for a hotlinked image because modern browsers don't allow 3rd party cookies. 

Then, in the next request, browser sends only session cookies but no samesite cookies. This results in redirect loop, Nextclouds send 302 redirect to the same file over and over again. This is bad, as it results in huge server traffic.. There's easily like 20 redirects before Firefox gives up on the url.

I made a "hack" to make it work for me for a while, so the above wget example no longer bugs.. But you can test it yourself on your own nextcloud. Any /download or /preview link will do.

wget -d --save-cookies cookies.txt --keep-session-cookies https://nextcloudlink/download

(edit cookies.txt to remove samesite cookies)

wget -d --load-cookies cookies.txt --keep-session-cookies https://nextcloudlink/download

will result in a 302 instead of download.

**Comment by Zuikkis** [comment]
I dig it further, although this seems a bit pointless as no one else seems to be interested. :)

The problem is that all "oc*" cookies are missing SameSite=Lax. Then when the file is hotlinked or streamed by Chromecast etc, the SameSite cookies are not passed. So only oc* session cookies are sent. This then triggers the function cookieCheckRequired() because of this rule:

 * Checks if the strict cookie has been sent with the request if the request is including any cookies.

This causes nextcloud to send 302 redirect to the current page, trying to set SameSite cookies. But obviously SameSite cookies still won't be passed on the next request, so this results in a redirect loop.

Although this redirect loop probably is a bug by itself, it can be circumvented by adding SameSite=Lax to session cookies. Then the browser (or chromecast) does not send any cookies on the request..

**So, everything in this issue is complelety fixed by adding this single line to apache config:**

`Header edit Set-Cookie ^(oc.*)$ $1;SameSite=Lax`

Could someone please comment if there are any possible problems or side effects? 
@rullzer or @tobiasKaminsky care to comment? Should this be included in the default .htaccess?

**Comment by tobiasKaminsky** [comment]
@rullzer is the right person to answer about possible side effects

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by Zuikkis** [comment]
I'm pretty sure it's still valid.

I have run my Nextcloud now for 1.5 years with this line added to apache config:
`Header edit Set-Cookie ^(oc.*)$ $1;SameSite=Lax`

.. and it has worked without issues, even after several nextcloud version updates etc. Both chromecast and hotlinking works fine.

I have to admit I haven't tried removing the line to see what is does in current version, but since no one from Nextcloud team has commented anything here I assume no change has been done.

**Comment by szaimen** [comment]
Could you create a PR with this proposal? Then you might get a bit more response on that. Thanks!

**Comment by Zuikkis** [comment]
Thanks, but I think this should be fixed in nextcloud code instead of Apache? 

Nextcloud is generating incorrect cookies, and I'm simply using Apache's header rewrite feature to fix the cookie before passing it to client. That's just like a bandage, not a real fix.

Fixing the Nextcloud code is probably above my level, sorry. :( I tried to look and couldn't really see where the oc.* cookies are even generated? It should be enough if ";SameSite=Lax" was added to end of the line.

Also I'm a bit afraid that there's perhaps some side effect that I just haven't encountered yet, but might break it for someone else. Perhaps there is a reason for Nextcloud omitting the SameSite header for some cookies? It does add it to some others..

**Comment by szaimen** [comment]
> I tried to look and couldn't really see where the oc.* cookies are even generated? It should be enough if ";SameSite=Lax" was added to end of the line.

Maybe @nextcloud/server-triage can shed some light on this?

> Also I'm a bit afraid that there's perhaps some side effect that I just haven't encountered yet, but might break it for someone else.
> Perhaps there is a reason for Nextcloud omitting the SameSite header for some cookies? It does add it to some others..

I guess in this case we should test if this is the case and close this issue if yes. cc @nextcloud/server-triage
