### ISSUE TITLE
German plural of file vs. files on link shared site

### ISSUE THREAD

**Issue by danielh84** [nextcloud/server#16296]
### **Steps to reproduce**

1. Goto Files App
2. Select Folder with one file / select folder with at least two files
3. share folder by link
4. visit the two different links

### **Expected behaviour**
"1 file" / "2 files" in english (US) translation.
"1 Datei" / "2 Dateien" in German translation (Persönlich: Du)
"1 Datei" / "2 Datei**en**" in German translation (Förmlich: Sie)

### **Actual behaviour**
"1 Datei" / "**2 Datei**" in German translation (Förmlich: Sie)

### **Server conf**
**Nextcloud version:** 16.0.2
Updated from an older Nextcloud/ownCloud or fresh install:
Updated

I searched on transifex but wasn't successful

**Comment by rullzer** [comment]
Our translations are synced daily from transifex.
Please join at https://www.transifex.com/nextcloud/nextcloud/dashboard/ to help with translations.
