### ISSUE TITLE
Custom icon for folders (or for files by given criterias)

### ISSUE THREAD

**Issue by ratermir** [nextcloud/server#16309]
I would really appreciate to be able to set my own icons for certain (concrete) folders. Such functionality dramatically increases ability to orient in large filesystems.

 Icons can be "contrast" like standard icons (black-transparent), or full collored.

**Comment by Lars1963** [comment]
Usefull, I'd like too see that too.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest and no respond since around 2 years. Please reopen if you still want to implement this.
