### ISSUE TITLE
Files from deactivated users will still be shared

### ISSUE THREAD

**Issue by mritzmann** [nextcloud/server#16302]
### Steps to reproduce
1. Create new Nextcloud User and login
2. Upload a file (e.g. a picture) and share it via public url
3. Deactivate the previously created account
4. The publicly shared file is still accessible

### Expected behaviour
Publicly shared files should not be available if an account is disabled.

Reason why publicly shared files from deactivated accounts should no longer be available:

* The account was deactivated due to abuse: Shared files are still retrievable.
* As a user, I have no way to deactivate a shared file if the account is deactivated. For security reasons, shared files should not be available if the user no longer has control over it.
* Expected behavior.

### Actual behaviour
Publicly shared files are still available.

### Server configuration

**Nextcloud version:** 16.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated since 14.x

**Where did you install Nextcloud from:** Download as zip from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - drop_account: 0.1.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.1
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.4.0
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.3.12
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 2.1.2
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - end_to_end_encryption
  - files_external
  - nextcloud_announcements
  - support
  - survey_client
  - updatenotification
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "localhost",
            "2": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "mysql",
        "version": "16.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "app_install_overwrite": [
            "end_to_end_encryption"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by sblaisot** [comment]
Another point is removing a user from LDAP breaks client sync if the user had shares.
see https://github.com/nextcloud/desktop/issues/819

**Comment by mritzmann** [comment]
Can no longer reproduce the problem. Apparently fixed in Nextcloud 17 or 18.
