### ISSUE TITLE
NC 16 docker - Using external storage, getting error while deleting a folder

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#16306]
I post here because I can't find any help on the official forum or on the nextcloud docker repo.
I have created a user named foo. He has the following folders : 

----------------

```
home
│
└───foo
    │
    └───nextcloud
    │   │  
    │   └───keys
    │   │   │ cert.crt
    │   │   │ cert.key
    │   │
    │   └─── log
    |   |    |
    |   |    └───nginx
    │   |    │   │ access.log
    │   |    │   │ error.log
    |   |    |
    |   |    └───php
    │   |         │ error.log
    │   │
    │   └───nginx
    │   │   │ nginx.conf
    │   │   │   
    │   │   └───site-confs
    │   |       │ default
    │   |  
    │   └───php
    │   │   │ php-local.ini
    │   │   │ www2.conf
    |   | 
    |   └───www    
    │       │ index.html
    │       │
    │       └───nextcloud
    │           │ index.php
    │           │ occ
    │           │ ...
    │
    └───data
        │  file1
        |  file2
        |  folder1
        │  folder2
        |  folder3
```

The folder `/home/foo/nextcloud` is coming from the volume from a nextcloud container. When I create a container I'm using the local external storage to map my data folder (`/home/foo/data`). I successfully did it but when I delete folder, I'm having an error message : 

> Error deleting file “folderfoo”.

I can create/move/copy folder and files.

It’s says it’s a file but actually it was a folder. After refreshing the browser the folder is deleted. By the way I can successfully delete files.
I’m using this image https://hub.docker.com/r/linuxserver/nextcloud
I added the right user permission on the docker container and the data folder.

The folder data is under the right user (1000).

I also tested to add a redis container and linked it to my nextcloud container with `-e REDIS_HOST="redis"` and it give me the following in config.php :

```
'memcache.distributed' => '\\OC\\Memcache\\Redis',
'memcache.locking' => '\\OC\\Memcache\\Redis',
'redis' =>
 array (
        'host' => 'redis',
        'port' => 6379,
    ),
```
But the issue is the same.

Here is my command line to create a container :

```
docker run -d \
  --name=nextcloud \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=Europe/Paris \
  -p 443:443 \
  -p 8080:80 \
  -v /home/foo/nextcloud:/config \
  -v /home/foo/data:/data \
  --restart unless-stopped \
  linuxserver/nextcloud
```

I also tried with the official docker nextcloud, I get the same issue.
I would like to map an empty folder on the container side, to map my data folder.
I don't have my error message if I use the `/data` folder but there is data (nextcloud files) I don't want to show these files : 

![alt text](https://i.imgur.com/YnUz0wj.png)

Log I got when I delete a folder (when my host `/home/foo/data` folder is mapped to `/data/foo/files` for e.g.) : 

```
unable to rename, destination directory is not writable : /data/admin/files_trashbin/files

rename(//data/admin/files/test,//data/admin/files_trashbin/files/test.d1562660279): Cross-device link at /config/www/nextcloud/lib/private/Files/Storage/Local.php#289

rename(): The first argument to copy() function cannot be a directory at /config/www/nextcloud/lib/private/Files/Storage/Local.php#289

unable to rename, destination directory is not writable : /data/admin/files_trashbin/files
```
Permission I have on those folders : 

```
drwxrwx--- 4 abc abc 4096 Jul  9 10:37 files
drwxr-xr-x 5 abc abc 4096 Jul  9 10:17 files_trashbin
```

I don’t know what I’m supposed to do, thanks for any help

**Comment by eubanks718** [comment]
I also have this issue. I am running Nextcloud 18.0.4 on Freebsd with Php 7.4 and Apache 2.4. I am also running redis. I see this is already labeled a bug but I'm happy to provide any additional information that could help

**Comment by Nils160988** [comment]
This issue should better be posted on help.nextcloud.com or at the nextcloud-docker repository because it does not seem to be a bug in nextcloud server.
Please discuss your issue there and provide further information here, if you still think it is a server bug.

**Comment by jackgray** [comment]
Also unable to write or move data with S3 external storage on completely open IAM policy. Reading and downloading is fine, and no problems with the primary storage, but external storage will not modify any files through the client or web browser. Using the s3 api, I can upload and view the files in nextcloud, but there seems to be permission issues with nextcloud api.
