### ISSUE TITLE
PostgreSQL: no schema has been selected to create in

### ISSUE THREAD

**Issue by leo-lb** [nextcloud/server#16315]
### Steps to reproduce
1. Run SQL: `revoke usage on schema public from public;`
2. Try to install Nextcloud

### Expected behaviour
Install successful

### Actual behaviour
```
Error while trying to create admin user: An exception occurred while executing 'CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version))':

SQLSTATE[3F000]: Invalid schema name: 7 ERROR:  no schema has been selected to create in
LINE 1: CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, versi...
                     ^
```

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
apache2
**Database:**
postgresql 9.6
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
15
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

I am hitting this problem as described:
https://dba.stackexchange.com/questions/106057/error-no-schema-has-been-selected-to-create-in

I use a managed database delegating maintenance to my hosting provider for less burden, however, they're restricting down privileges for strict isolation and Nextcloud does not seem to like it, I think you have to prefix every table name with the database name like: `db_name.table_name`.

**Comment by leo-lb** [comment]
Collaborator had not given the db user any privilege, issue solved and wasnt due to the guessed problem.

**Comment by afshinrahmati** [comment]
you should Query in postgresql===>create schema public;
