### ISSUE TITLE
Update 16.0.1 -> 16.0.3 failed cause of .rnd file check due updater 

### ISSUE THREAD

**Issue by thprim** [nextcloud/server#16317]
I'll try to update version 16.0.1 -> 16.0.3 with the integrated GUI updater as I upgraded from 15.0.7 a.s.o up to 16.0.1.

### Steps to reproduce
1. After starting the updater, the error message "Check for exptected files" - The following extra file have beed found * .rnd will be displayed
2. The update process stops
3. I found a file .rnd in the installation directory /var/wwwNextcloud owned by www-data

I never recognized this file, nor do I know by what process this file will be created, but it's new and from today.
Question is know, could this file be deleted without any impact? I searched the issues, but did not really find a hint for this issue.

### Server configuration
**Operating system**..: Ubuntu 18.04.02 LTS
**Web server**..: Apache2/2.4.29
**Database**..: MariaDB 10.1.40
**PHP version**...: 7.2.19

**Nextcloud version** ...: 16.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Originally updated from v.15.0.7 to 16.0.1 with the GUI updater
**Where did you install Nextcloud from:** It was manually installed, source was downloaded from http://download.nextcloud.com/server/releases

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => cf73849388838de5037624e53303618579b164ec69fd55834ce4c5332ae33f778839e36298cbcc8ede90620927e076dbb8883479754e4c09b0491b15bf7653f3
                        )

                )

        )

)

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:  - accessibility: 1.2.0  - activity: 2.9.1  - admin_audit: 1.6.0  - bruteforcesettings: 1.3.0  - cloud_federation_api: 0.2.0  - comments: 1.6.0  - dav: 1.9.2  - external: 3.3.0  - federatedfilesharing: 1.6.0  - federation: 1.6.0  - files: 1.11.0  - files_external: 1.7.0  - files_pdfviewer: 1.5.0  - files_sharing: 1.8.0  - files_texteditor: 2.8.0  - files_trashbin: 1.6.0  - files_versions: 1.9.0  - files_videoplayer: 1.5.0  - firstrunwizard: 2.5.0  - gallery: 18.3.0  - groupfolders: 4.0.3  - keeweb: 0.5.1  - logreader: 2.1.0  - lookup_server_connector: 1.4.0  - nextcloud_announcements: 1.5.0  - notifications: 2.4.1  - oauth2: 1.4.2  - occweb: 0.0.4  - ownbackup: 19.5.0  - password_policy: 1.6.0  - polls: 0.10.2  - privacy: 1.0.0  - provisioning_api: 1.6.0  - recommendations: 0.4.0  - registration: 0.4.6  - serverinfo: 1.6.0  - sharebymail: 1.6.0  - support: 1.0.0  - survey_client: 1.4.0  - systemtags: 1.6.0  - tasks: 0.11.0  - theming: 1.7.0  - theming_customcss: 1.3.0  - twofactor_backupcodes: 1.5.0  - updatenotification: 1.6.0  - user_usage_report: 1.1.2  - viewer: 1.0.0  - workflowengine: 1.6.0Disabled:  - calendar  - contacts  - deck  - encryption  - end_to_end_encryption  - files_mindmap  - files_rightclick  - files_trackdownloads  - flowupload  - mail  - quota_warning  - user_ldap  - workflow_pdf_converter**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{    
"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",        
		"passwordsalt": "***REMOVED SENSITIVE VALUE***",        
		"secret": "***REMOVED SENSITIVE VALUE***",        
		"trusted_domains": 
		[            
			"****removed****.ddns.net"        
		],        
		"datadirectory": "***REMOVED SENSITIVE VALUE***",        
		"dbtype": "mysql",        
		"version": "16.0.1.1",        
		"overwrite.cli.url": "http:\/\/localhost\/nextcloud",        
		"dbname": "***REMOVED SENSITIVE VALUE***",        
		"dbhost": "***REMOVED SENSITIVE VALUE***",        
		"dbport": "",        
		"dbtableprefix": "oc_",        
		"dbuser": "***REMOVED SENSITIVE VALUE***",        
		"dbpassword": "***REMOVED SENSITIVE VALUE***",        
		"installed": true,        
		"memcache.local": "\\OC\\Memcache\\APCu",        
		"mail_smtpmode": "smtp",        
		"mail_smtpsecure": "tls",        
		"mail_sendmailmode": "smtp",        
		"mail_from_address": "***REMOVED SENSITIVE VALUE***",        
		"mail_domain": "***REMOVED SENSITIVE VALUE***",        
		"mail_smtphost": "***REMOVED SENSITIVE VALUE***",        
		"mail_smtpport": "587",        
		"mail_smtpauthtype": "LOGIN",        
		"mail_smtpauth": 1,        
		"mail_smtpname": "***REMOVED SENSITIVE VALUE***",        
		"mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        
		"maintenance": false,        
		"theme": "",        
		"loglevel": 2,        
		"app_install_overwrite": 
		[            
		    "occweb"        
		],        
		"updater.secret": "***REMOVED SENSITIVE VALUE***"    
	}
}

**Are you using external storage, if yes which one:** local/smb/sftp/... ### not used ###

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... ### not used ###

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox 67.0.4 (64-Bit)
**Operating system:**: Ubuntu 18.04.02 LTS

#### HINT: Logs could be delivered, but not sure if this helps at the moment. the log file is pretty big 777k

partly, the update.log is included below:
2019-07-09T19:19:31+0200 VL2Tl3hv6M [info] checkForUpdate() Array
(
    [version] => 16.0.3.0
    [versionstring] => Nextcloud 16.0.3
    [url] => https://download.nextcloud.com/server/releases/nextcloud-16.0.3.zip
    [web] => https://docs.nextcloud.com/server/16/admin_manual/maintenance/upgrade.html
    [changes] => https://updates.nextcloud.com/changelog_server/?version=16.0.3
    [autoupdater] => 1
    [eol] => 0
    [signature] => TYiUB/+l2uXNpiHGuMhchHzzyMn8eiL2mzBD+fmwqUXU29UYK4FFvTbDEWWXxXF9
XeOXXBTkWltQ6A5K+nwFx4Phf4VPznaGn3U/1hsLSLBy9p9qqBMQdmDvCxl4dJmP
R0Ttz6sGcC1AsYwW2Q5Z1lywpmk1Ax5YcJesbjOFTU9HXIOI2s9YyPX4bP3L1rkH
CaZqjW7yCedKhj64F/SuXnUwaPhqTNNoDdhCN14IKvXCFYKLxm5UoGXrddwIcRrL
rHSv7h5818aTjmj4sB1jsVrxNf32PgrUED8PUqgMYx1FxEzGyct4yj+GbIBi4D+K
b813iKq4+cn3CjTunREm6A==
)

2019-07-09T19:19:31+0200 VL2Tl3hv6M [info] getChangelogURL()
2019-07-09T19:19:31+0200 VL2Tl3hv6M [info] end of checkForUpdate() Update to Nextcloud 16.0.3 available. (channel: "stab
le")<br /><span class="light">Following file will be downloaded automatically:</span> <code class="light">https://downlo
ad.nextcloud.com/server/releases/nextcloud-16.0.3.zip</code><br /><a class="external_link" href="https://nextcloud.com/c
hangelog/#16-0-3" target="_blank" rel="noreferrer noopener">Open changelog ↗</a>
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] request to updater
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] currentStep()
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] POST request for step "1"
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] startStep("1")
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] checkForExpectedFilesAndFolders()
2019-07-09T19:19:36+0200 cTYTYz7VPr [error] POST request failed with UpdateException
2019-07-09T19:19:36+0200 cTYTYz7VPr [error] Exception: UpdateException
Message:
Code:0
Trace:
#0 /var/www/nextcloud/updater/index.php(1327): Updater->checkForExpectedFilesAndFolders()
#1 {main}
File:/var/www/nextcloud/updater/index.php
Line:393
Data:
Array
(
    [0] => .rnd
)

2019-07-09T19:19:36+0200 cTYTYz7VPr [info] rollbackChanges("1")
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] unlink .step
2019-07-09T19:19:36+0200 cTYTYz7VPr [info] end of  rollbackChanges()

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Check https://github.com/nextcloud/server/issues/13568 or https://github.com/nextcloud/server/issues/12726

**Comment by thprim** [comment]
Deletion of the file helped. Update successful done
Thanks a lot

**Comment by thprim** [comment]
Issue now is, that after the update the app list in the browser is empty and nothing could be displayed

**Comment by thprim** [comment]
After deleting the browser-cache the page is displayed. Funny issue

**Comment by Tas-sos** [comment]
I had the same problem!
### Server configuration

**Operating system**:  Ubuntu server 16.04.6 LTS

**Web server:**  Apache/2.4.39 (Ubuntu)

**Database:** MariaDB - 10.0.38-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

**PHP version:** HP 7.3.7-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Jul 25 2019 11:44:40) ( NTS )

**Nextcloud version:** Nextcloud 16.0.3

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - audioplayer: 2.7.2
  - bruteforcesettings: 1.4.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - deck: 0.6.5
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.0
  - updatenotification: 1.6.0
  - video_converter: 0.1.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```
</details>


In my administration page (https://.../settings/admin/overview) had appears this problem:

> Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)

If I clicked it the "List of invalid files…" (https://.../settings/integrity/failed) it has returned me the following :

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- ocs/.rnd
		- .rnd

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [ocs/.rnd] => Array
                        (
                            [expected] => 
                            [current] => ba5e1470b8d155b86002c2a90a47ee4e32ed756cf085c957691358ccb39f20c02515998c1bed5ea06595f9b8b9311e0d60a92913878ad54be43b224e99f6df67
                        )

                    [.rnd] => Array
                        (
                            [expected] => 
                            [current] => e13bd19ae53da42ad7aaa3eafeee059da94ae309b1ca21eccddf95edefab3a61e9499e8462962a541e9e2b918b9ee0cbe730406c541509cdeec60d6651ecb76f
                        )

                )

        )

)
```
So, because there are many issues with this problem (_I got confused somewhere in different approaches_), I decided to simply **delete** the two above files from the installation directory of the Nextcloud ( _/var/www/nextcloud/_ ).

To be honest, at first I just moved them outside of the nextcloud directory ( _so that I can recover_ ).

So, what I noticed is that there was no problem anymore! **The issue fixed**!
Thank you!
