### ISSUE TITLE
Update Check disabled the Social Login 

### ISSUE THREAD

**Issue by emad-ramlawi** [nextcloud/server#16319]
### Steps to reproduce
1. NC Checks for update and that disabled the Social Login 
2.
3.

### Expected behaviour
Social Login should always be enabled 

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system**:
Ubuntu 18.04
**Web server:**
Apache latest from ubuntu 18.04 repo
**Database:**
mysql  latest from ubuntu 18.04 repo
**PHP version:**
7.2 
**Nextcloud version:** (see Nextcloud admin page)
16.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
2 apps caused this passman and passwords

Auditing / Logging
1.6.0
Official
Brute-force settings
1.3.0
Official
Deleted files
1.6.0
Official
Log Reader
2.1.0
Official
Monitoring
1.6.0
Official
Notifications
2.4.1
Official
Password policy
1.6.0
Official
Passwords
2019.7.1
Social Login
1.16.2
Text editor
2.8.0
Official
Theming
1.7.0
Official
Versions 
 1.9.0
Passman

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/18312
