### ISSUE TITLE
Share link password dialog doesnt go away

### ISSUE THREAD

**Issue by fcmildef** [nextcloud/server#16327]
**Is your feature request related to a problem? Please describe.**
When a user clicks the share link button, a password entry dialog appears. When the users decides they dont want to use the share link functionallity becaue for example they misclicked, they click somewere else to make the dialog go away, but it doesnt go away.

**Describe the solution you'd like**
Clicking anywere except for the password entry dialog should close the dialog.

**Comment by GretaD** [comment]
Tested and confirmed. I'll will check this out

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
