### ISSUE TITLE
Remote.PHP/CalDAV does not send HTTP Status Header

### ISSUE THREAD

**Issue by Vaultpls** [nextcloud/server#1632]
### Steps to reproduce
1. I don't know how
### Expected behaviour

When signing in with a client that is not part of the Nextcloud applications like DAVdroid, it should sign in.
### Actual behaviour

DAVdroid isn't able to connect due to Status Header not being sent as "0".
### Server configuration

**Operating system**: Linux

**Web server:** Caddy

**Database:** SQLite

**PHP version:** 7.0

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Official Website(tarball)

**Signing status:**
<details>
<summary>

Signing status</summary>

```
No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>

Activity
Collaborative tags
Comments
Default encryption module
Deleted files
External sites
External storage support
Federation
File sharing
First run wizard
Gallery
Mail
Notifications
PDF viewer
Provisioning API
Server info
Text editor
Theming
Update notification
Usage report
Versions
Video player Calendar
Documents</summary>

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
  'trusted_domains' =>
  array (
    0 => website',
  ),
  'datadirectory' => '/var/www/data',
  'overwrite.cli.url' => 'https://website',
  'dbtype' => 'sqlite3',
  'version' => '9.1.1.5',
  'logtimezone' => 'UTC',
  'installed' => true,
  'loglevel' => 0,
  'mail_smtpmode' => 'smtp',

```

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Oct 06 05:21:01 website caddy[13483]: IP  - [06/Oct/2016:05:21:01 +0000] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
Oct 06 05:21:01website  caddy[13483]: IP - [06/Oct/2016:05:21:01 +0000] "PROPFIND /.well-known/caldav HTTP/2.0" 301 0
Oct 06 05:21:01 website  caddy[13483]: IP  - [06/Oct/2016:05:21:01 +0000] "PROPFIND /remote.php/caldav HTTP/2.0" 207 471
Oct 06 05:21:02 website  caddy[13483]: IP  - [06/Oct/2016:05:21:02 +0000] "OPTIONS /remote.php/caldav/principals/Kyle/ HTTP/2.0" 0 7396

```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Nothing appears in log even if in Debug mode
```

</details>

**Comment by tcitworld** [comment]
Can you give the full DAVdroid logs ?

**Comment by Vaultpls** [comment]
[davdroid-debug1535759906.txt](https://github.com/nextcloud/server/files/514596/davdroid-debug1535759906.txt)

**Comment by rfc2822** [comment]
> EDIT : Also, DAVdroid version (the last ones are buggy)

Which bugs do you mean?

**Comment by tcitworld** [comment]
> Which bugs do you mean? Every release is successfully tested with Nextcloud.

I got my own instance and a few more of my users have had trouble to connect this month. Couldn't get to have more informations however, sorry.

**Comment by nickvergessen** [comment]
Can you try remote.php/dav/calendars/<username> instead?

**Comment by Vaultpls** [comment]
>According to the logs, it's a HTTP/2 server problem (sending no :status).

I disabled HTTP/2 and the problem still exists.

**Comment by MorrisJobke** [comment]
This works in many setups and is therefore not a bug within Nextcloud, but within the setup. Please check for help in our forums: https://help.nextcloud.com/

Thanks
