### ISSUE TITLE
Drag & Drop not working with group folders

### ISSUE THREAD

**Issue by assysttest** [nextcloud/server#16320]
### Steps to reproduce
1. Install Nextcloud 16.0.2
2. Set up group folders
3. Create a group folder with full access for yourself
4. Open the group folder in Firefox
5. Drag & Drop a file from explorer into Firefox drop area of your folder
6. Watch the error message: You don’t have permission to upload or create files here
7. Verify that you may upload files by "+" icon on top of folder view

### Expected behaviour
It should be possible to upload by drag & drop like in a normal folder

### Actual behaviour
Error appears, upload possible by "+" icon only.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/16238? Do you have the same error in your home directory?

**Comment by assysttest** [comment]
I confirm, looks like  #16238
