### ISSUE TITLE
AdBlock blocks UI elements for sharing

### ISSUE THREAD

**Issue by derBobby** [nextcloud/server#16337]
### Steps to reproduce
1. Open file details
2. Click sharing
3. Not seeing the "+" to the right of "Share link" (my translation)

### Expected behaviour
The "+" should be visible although AdBlock Plus Firefox Plugin enabled

### Actual behaviour
**The "+" seems to be blocked by AdBlock Plus**

### Server configuration

**Operating system**:
NC runs in docker containers, host is debian 
Linux NextNAS 3.16.0-9-amd64 #1 SMP Debian 3.16.68-2 (2019-06-17) x86_64 GNU/Linux

**Web server:**
nginx:1.14.0-alpine (reverse proxy, fpm routing to:)
nextcloud:16.0.3-fpm-alpine (php-fpm)

**Database:**
docker container:
mariadb:10.4.0-bionic

**PHP version:**
7.3.7

**Nextcloud version:** (see Nextcloud admin page)
16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
docker container

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bruteforcesettings: 1.3.0
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - forms: 1.0.3
  - gallery: 18.3.0
  - groupfolders: 4.0.3
  - impersonate: 1.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.4.0
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - registration: 0.4.6
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 2,
        "mail_sendmailmode": "smtp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "allow_user_to_change_display_name": false,
        "auth.bruteforce.protection.enabled": true,
        "trashbin_retention_obligation": "auto, D",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "onlyoffice": {
            "verify_peer_off": true
        }
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
docker volume mount

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
Firefox 67.0.4 (64-Bit)

**Operating system:**
Win 7 Prof 64bit

**Comment by ColinFinck** [comment]
Confirmed. I'm suffering from the same problem on both Nextcloud 15 and 16 with AdBlock Plus enabled. Works fine when disabling it for my cloud.

**Comment by kesselb** [comment]
Apart from renaming classes there is not much we can do. Usually theses ad blockers looks for specific elements (by some kind of selector) and remove them. There is some selector matching the "+". Mind to report this issue to the matching filter list?

**Comment by yawicz** [comment]
Thanks for reporting this, I also experienced the problem of the missing share options in Firefox and just recently found out how to resolve it (just generally unblocking my nextcloud in AdBlock Plus).
> 
> Apart from renaming classes there is not much we can do. Usually theses ad blockers looks for specific elements (by some kind of selector) and remove them. There is some selector matching the "+". Mind to report this issue to the matching filter list? https://help.getadblock.com/support/solutions/articles/6000087883-how-can-i-see-what-adblock-is-blocking-hiding-and-whitelisting-

Reporting it to ABP will hopefully help one day. Wouldn't it be otherwise maybe also an idea to resolve this issue by changing the "+"-sign into a different one? I guess the + button is mistaken for the Google + share button.
Interestingly, in Chrome, the same options menu shows as "..."-button, that's probably also the reason why there's no problems in Chrome.

Thus, my questions would be: Why is there different buttons in Chrome and Firefox?
And would it maybe make sense/be possible to implement the "..."-button for Firefox, too?

**Comment by tiiiecherle** [comment]
I'm having the same issue with latest Firefox and Safari on latest macOS using Adguard Filter "Widgets for social media". Any news or new ideas for a fix?
