### ISSUE TITLE
OpenStack Swift (and others) Streaming support

### ISSUE THREAD

**Issue by leo-lb** [nextcloud/server#16336]
**Note:** I have OpenStack Swift as Primary Storage

**Is your feature request related to a problem? Please describe.**
It causes a misunderstanding to users when they are waiting for the server to download files from object storage to then only start the download in their web browser

**Describe the solution you'd like**
It would be better if Nextcloud could start downloading the object from the object storage store at the same time as it offers the download to the user (streaming the data through)

**Comment by adrb** [comment]
Fixed in pull request #18883

**Comment by leo-lb** [comment]
@adrb Super cool! Thanks a lot.
