### ISSUE TITLE
Assign a theme color for buttons

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#16360]
### Expected behaviour
Assign button colors to themes.

### Actual behaviour
The theme colors for the "Upload" and "Delete" buttons are not assigned.

1. **Personal info**
![obraz](https://user-images.githubusercontent.com/47037905/61042069-c4ff3f80-a3d3-11e9-9956-1bc60cde71a4.png)

2. **Theming**
![obraz](https://user-images.githubusercontent.com/47037905/61040998-f24aee00-a3d1-11e9-9340-3c69b5e67de1.png)
![obraz](https://user-images.githubusercontent.com/47037905/61041333-65546480-a3d2-11e9-8953-92302e990a88.png)

3. **Files**
![obraz](https://user-images.githubusercontent.com/47037905/61041483-ab112d00-a3d2-11e9-9864-1505c1e4c2d8.png)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
16.0.3

### Client configuration
**Browser:**
Firefox 67.0.4
**Operating system:**
Win10

**Comment by violoncelloCH** [comment]
that is the intended behaviour... those buttons are always black (white in case you use the black theme); it wouldn't make sense to change every icon to use the theming colour... just everything that is "nextcloud-blue" by default will change its colour...

**Comment by Valdnet** [comment]
@violoncelloCH In my opinion, it looks a bit strange in eg "Personal info". There is no consistency. It is multi-colored and in addition only the active icon "Trash" changes to the color of the theme.

![obraz](https://user-images.githubusercontent.com/47037905/61381150-eb791b00-a8aa-11e9-8fef-a2ae2484aa01.png)

In contrast, "Upload new" behaves differently.
![obraz](https://user-images.githubusercontent.com/47037905/61381232-08ade980-a8ab-11e9-9439-7cc170e983d1.png)

**Comment by violoncelloCH** [comment]
hmm, the trash icon always uses the red color (as "danger colour" when active/hovered... 
But the border of the button is always the theming colour when hovering...

what's your opinion/argument here @jancborchardt ?

**Comment by jancborchardt** [comment]
Fully agree with @violoncelloch here. Only folder icons and primary actions have the primary color.

We use color sparingly as it calls for attention. If everything competes for attention it would be horrible.
