### ISSUE TITLE
Web UI issue after trying to watch large files

### ISSUE THREAD

**Issue by waip2Ohng9oh** [nextcloud/server#16365]
### Steps to reproduce
1. Upload large .txt file, i.e. > 2 GB
2. Open the file in the web UI with inline viewer
3. Error message dialogue appears telling that the file is too large to view
4. Close dialogue
5. Date of the file is incorrect

### Expected behaviour
Show the correct date

### Actual behaviour
shows 50 years. Probably date is not set, defaulting to 1/1/1970 and rounding up

### Server configuration

**Operating system**: Debian 9.5

**Web server:** apache2

**Database:** mariadb

**PHP version:**

**Nextcloud version:** Ver 15.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 14.0.4

**Where did you install Nextcloud from:** occ

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bruteforcesettings: 1.3.0
  - calendar: 1.6.5
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.3
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - impersonate: 1.2.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - user_ldap: 1.5.0
  - user_saml: 2.0.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - files_automatedtagging
  - files_external
  - user_external

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.***REMOVED SENSITIVE VALUE***",
            "nextcloud.***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "15.0.8.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "lost_password_link": "disabled",
        "maintenance": false,
        "proxy": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 60.7.2-ESR

**Operating system:** Debian

![Screenshot-2019-7-11 Documents - Files - Nextcloud](https://user-images.githubusercontent.com/52789930/61057827-597a9980-a3f6-11e9-8dfc-4837cda708af.png)
![Screenshot-2019-7-11 Files - Nextcloud](https://user-images.githubusercontent.com/52789930/61057840-5f707a80-a3f6-11e9-89fc-fe594c461091.png)
![Screenshot-2019-7-11 Files - Nextcloud(1)](https://user-images.githubusercontent.com/52789930/61057841-5f707a80-a3f6-11e9-850f-f284896c2e06.png)

**Comment by wiswedel** [comment]
@waip2Ohng9oh Is the file modification date on the storage also modified? Can you please check that?
And is the web UI ok again after refresh or does the wrong info persist?

**Comment by waip2Ohng9oh** [comment]
Hi

On storage the timestamps are still unchanged and show the expected time. After reload the timestamp is correct.

Seems to be an issue with some javascript

**Comment by wiswedel** [comment]
CC @nextcloud/server-triage

**Comment by szaimen** [comment]
I thinks this is the same issue like https://github.com/nextcloud/viewer/issues/894
