### ISSUE TITLE
2 errors: Inconsistency in Spanish localization.

### ISSUE THREAD

**Issue by maxlinux2000** [nextcloud/server#16368]
Español abajo
--------------

If you set the language in Configuration/Personal Info, the language "Castellano" appears in the list.

More low there are in the list other Spanish languages, such as
Español-Argentina
Español-Chile
Español-Colombia
....

The problem is that Castellano is spoken only in one little region of Spain, while the rest of the country speaks Spanish exactly equal to the rest of the Spanish-speaking countries.
Also it is not said in which country the "Castellano" is spoken ... and it should be:
"Castellano-España"

But if we do so, it would be, by coherence, to change all the references to the other Spanish-speaking countries, translating:
Castellano-Argentina
Castellano-Chile ....
Castellano-Colombia

But this would bother the other countries a lot, because they know they speak Spanish and not Castellano.

Also in any multi-language software there is "Español-España" and not "Castellano"

Always for consistency look at the other menu next to "Locale" in US. There comes "Spanish (Spain)"

So please remove the "Castellano" and put "Español-España"

Other error. 
It has translated "Locale" string into "Region" and is completely wrong. 
"Locale" in the other software translates to "Localización".

Español
---------------
Inconsistencia en Español localization.

Si vas en la configuración de Nextcloud/Informaciones personales, aparece en la lista el idioma "Castellano".

Más a bajo hay en la lista otros idiomas españoles, como por ejemplo
Español-Argentina
Español-Chile
Español-Colombia
....

El problema es que el Castellano se habla solo en una pequeña región de España, mientras que el resto del país habla Español.
Además no se dice en que país se habla el "Castellano"... y tendría que ser :
"Castellano-España" 

Pero si lo hacemos así habría, por coherencias, cambiar todas las referencias a los otros países hispanos hablantes, traduciendo:
Castellano-Argentina
Castellano-Chile
Castellano-Colombia
....

Pero esto molestaría mucho a los demás paises, porqué ellos saben que hablan el español y no el castellano.

Además en cualquier software con idioma múltiple, hay "Español-España" y no "Castellano"

Siempre por coherencia mirar al otro menú al lado "Locale" en Inglés . Allí sale "Spanish (Spain)"

Así que por favor quitar el "Castellano" y poner "Español-España"

Otro error. Se ha traducido "Locale" en "Región" y está equivocado por completo. Locale en los demás software se traduce en "Localización"

**Comment by kesselb** [comment]
I think you can changes this value in transifex: https://www.transifex.com/nextcloud/

- Goto languages and select "Spanish (es)"
- In the next step pick the resource "lib and click "View strings online"
- Search for `__language_name__`

The translations synced daily from transfix to github.

**Comment by maxlinux2000** [comment]
Done!
First error done.

But now I don't  find the next error: Locale -> Localización

Can you help me to find the correct file?

**Comment by maxlinux2000** [comment]
Ok find it. It's in "settings-1"
This string is "revised" so I proposed a new translation.
I think that this bug can be closed

**Comment by kesselb** [comment]
Thank you :+1:
