### ISSUE TITLE
Shared with button does not provide accessible name / state information for assistive technologies

### ISSUE THREAD

**Issue by javido** [nextcloud/server#16373]
### Steps to reproduce
1. Access Nextcloud Files application
2. Press tab key to reach unlabelled button 1
3. Press enter key or space bar to expand / collapse

### Expected behaviour

Screen reader should present this component as a "Shared with" button with state expanded / collapsed

### Actual behaviour
Screen reader only present it as "button 1" and users don't know button functionality or state.

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache 2

**Database:**
Maria DB 

**PHP version:**
PHP 7.2

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Tarballs source code

**Comment by javido** [comment]
HTML code where this issue appears:
					<button class="collapse app-navigation-noclose"></button>
			<ul id="sublist-shareoverview">
					<li data-id="sharingout" class="nav-sharingout						">

		<a href="#" class="nav-icon-sharingout svg">Compartido con otros</a>


			</li>


		<li data-id="sharingin" class="nav-sharingin						">

		<a href="#" class="nav-icon-sharingin svg">Compartido conmigo</a>


			</li>


		<li data-id="sharinglinks" class="nav-sharinglinks						">

		<a href="#" class="nav-icon-sharinglinks svg">Compartido por enlace</a>


			</li>


		<li data-id="deletedshares" class="nav-deletedshares						">

		<a href="#" class="nav-icon-deletedshares svg">Recursos compartidos eliminados</a>


			</li>

</ul>

A possible solution would be:
					<button aria-label="Shared with" aria-expanded="false" class="collapse app-navigation-noclose"></button>

```

We need to update aria-expanded attribute value to true / false when expanding or collapsing the shared with options and mark aria-label content for translation.

**Comment by javido** [comment]
HTML code where this issue appears:
```

<button class="collapse app-navigation-noclose"></button>
			<ul id="sublist-shareoverview">
					<li data-id="sharingout" class="nav-sharingout						">

		<a href="#" class="nav-icon-sharingout svg">Compartido con otros</a>


			</li>


		<li data-id="sharingin" class="nav-sharingin						">

		<a href="#" class="nav-icon-sharingin svg">Compartido conmigo</a>


			</li>


		<li data-id="sharinglinks" class="nav-sharinglinks						">

		<a href="#" class="nav-icon-sharinglinks svg">Compartido por enlace</a>


			</li>


		<li data-id="deletedshares" class="nav-deletedshares						">

		<a href="#" class="nav-icon-deletedshares svg">Recursos compartidos eliminados</a>


			</li>

</ul>

```

A possible solution would be:
```

					<button aria-label="Shared with" aria-expanded="false" class="collapse app-navigation-noclose"></button>

```


We need to update aria-expanded attribute value to true / false when expanding or collapsing the shared with options and mark aria-label content for translation.

**Comment by kesselb** [comment]
cc @nextcloud/accessibility

**Comment by skjnldsv** [comment]
Once we upggraded the filelist to vue, it will be automatically fixed :)
In the meantime we could do something to easily fix it yes :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
