### ISSUE TITLE
Improve documentation for thumbnail and preview generation

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#16376]
Hi!

Following a thread on [GitHub](https://github.com/rullzer/previewgenerator/issues/167) regarding the **jpeg_quality** setting of the **previewgenerator** app.

I found that the `jpeg_quality` setting in `config.php` **is not used** by Nextcloud (files/gallery) itself but only the **previewgenerator** app. This means that all thumbnails and previews will be generated at the default **quality level 90**. Only previews rendered with the previewgenerator app through `occ preview: generate-all` command will use `jpeg_quality` setting in `config.php`.

As far as I can tell by the [source code](https://github.com/nextcloud/server/blob/master/lib/private/legacy/image.php#L383), this snippet is used to set the quality level:
```
protected function getJpegQuality() {
		$quality = $this->config->getAppValue('preview', 'jpeg_quality', 90);
		if ($quality !== null) {
			$quality = min(100, max(10, (int) $quality));
		}
		return $quality;
	}
```

It is clear that Nexctcloud core is looking for a very similar **jpeg_quality** setting as the one used by the previewgenerator app. This is not , however, set in the [config.php](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html) file. Instead, it has to be set with the following **occ** command:
 **`occ config:app:set preview jpeg_quality --value="60"`**
This setting (for the Nextcloud core) is not documented anywhere as far as I can tell.

*Is this a bug, a feature, or a mistake* in *previewgenerator* app or in the *Nextcloud core*? Was the intent to use the same name for **jpeg_quality**, but it is a bug that it isn't used?

As far as I know this has been the same in all recent Nextcloud instances from NC12 to NC16.

**Comment by kesselb** [comment]
cc @rullzer

**Comment by Gatak** [comment]
Hi. I just checked again for Nextcloud 19. This jpeg_quality setting is still not documented. Should it not be?

https://docs.nextcloud.com/server/19/admin_manual/search.html?q=jpeg_quality

**Comment by rullzer** [comment]
The preview generator is not using any value it is is not even generting previews it just requests them from the system causing them to be generated.

As for the documentation. Feel free to propose a PR in https://github.com/nextcloud/documentation

**Comment by Gatak** [comment]
OK. Did a pull request. https://github.com/nextcloud/documentation/pull/2203

**Comment by kesselb** [comment]
Thanks :+1:
