### ISSUE TITLE
Incorrect protocol in WebDAV link in files web application

### ISSUE THREAD

**Issue by ratermir** [nextcloud/server#16370]
The WebDAV link shows incorrect protocol in "Setup" -> WebDAV field in file application (bottom left corner). It offers "HTTP" version of URL (instead of HTTPS which the server is really accessed through). 

I have such setup:

Internet <--https--> Public_NGINX  <--http--> In_Docker_NGINX  <--unix_socket--> Nextcloud_PHP_fpm

Public NGINX serves miltiple virtual sites (it acts as a reverse proxy), In_Docker NGINX serves set of nextcloud / onlyoffice, since I want to keep Public NGINX to unaware of internal nextcloud structure 

On the Public_NGINX there is redirection set from HTTP to HTTPS, but this does not work in case of Windows DAV client (it must obtain direct = HTTPS - address type).

Nextcloud 16.0.3

It is minor issue (I know that this setup is not too common). I put it here to inform you.

**Comment by kesselb** [comment]
Thank you for reporting :+1: 

Add the internal ip of Public_NGINX to `trusted_proxies`. Check https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html for more information.

**Comment by ratermir** [comment]
Thank you for very fast reaction :)

**Comment by wiswedel** [comment]
@ratermir So is this resolved?

**Comment by ratermir** [comment]
@wiswedel Thank you for quick response, I didn't have a time so far.

**Comment by mauvm** [comment]
For me changing `overwrite.cli.url` in `config/config.php` did the trick.
