### ISSUE TITLE
uploads fail from android with certain files since upgrade to 16.0.3

### ISSUE THREAD

**Issue by darmbrust** [nextcloud/server#16383]
### Steps to reproduce
1. Record a video on phone (android)
2. Attempt to sync (either automatically, or manually)

### Actual behaviour
The phone fails, with a message that the server is in maintenance mode.
When taking photos, these still seem to sync fine.
The photos are syncing from a different folder than the videos.
The video that fails to sync is around 60 MB.

This was all working fine on my server prior to the upgrade to 16.0.3, which was done through the web interface.

My android app is at version 3.7.0

### Server configuration

**Operating system**:
Linux webserver-vm 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:26:28 UTC 2019 i686 i686 i686 GNU/Linux

**Web server:**
Apache/2.4.29 (Ubuntu)

**Database:**
Type: mysql
Version: 10.1.40
Size: 31.9 MB

**PHP version:**
Version: 7.2.19
Memory Limit: 512 MB
Max Execution Time: 3600
Upload max size: 2 GB

**Nextcloud version:** (see Nextcloud admin page)
16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.1 (I think)

**Signing status:**
No error found

**List of activated apps:**
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.3.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**  no
#### Web server error log

```
No errors logged
```

#### Nextcloud log (data/nextcloud.log)

```
[PHP] Error: fopen(/mnt/nextCloudStorage/data/phone/uploads/3fae32019120c97d7480ce6b8ecec114/0000000000000000-0000000010239999): failed to open stream: No such file or directory at /nextcloudInstall/nextcloud/lib/private/Files/Storage/Local.php#301

MOVE /nextcloud/remote.php/dav/uploads/phone/3fae32019120c97d7480ce6b8ecec114/.file
from 192.168.10.1 by phone at 2019-07-13T14:16:27+00:00


[no app in context] Error: Sabre\DAV\Exception\ServiceUnavailable: Could not open file at <<closure>>

 0. /nextcloudInstall/nextcloud/apps/dav/lib/Upload/AssemblyStream.php line 292
    OCA\DAV\Connector\Sabre\File->get()
 1. /nextcloudInstall/nextcloud/apps/dav/lib/Upload/AssemblyStream.php line 142
    OCA\DAV\Upload\AssemblyStream->getStream(OCA\DAV\Connector\Sabre\File {})
 2. <<closure>>
    OCA\DAV\Upload\AssemblyStream->stream_read(8192)
 3. /nextcloudInstall/nextcloud/3rdparty/icewind/streams/src/Wrapper.php line 91
    undefinedundefinedfread(null, 8192)
 4. /nextcloudInstall/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php line 98
    Icewind\Streams\Wrapper->stream_read(8192)
 5. <<closure>>
    Icewind\Streams\CallbackWrapper->stream_read(8192)
 6. /nextcloudInstall/nextcloud/lib/private/Files/Storage/Local.php line 488
    undefinedundefinedfile_put_contents("/mnt/nextCloudS ... t", null)
 7. /nextcloudInstall/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 630
    OC\Files\Storage\Local->writeStream("files/Phone ... t", null, null)
 8. /nextcloudInstall/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 190
    OC\Files\Storage\Wrapper\Wrapper->writeStream("files/Phone ... t", null)
 9. /nextcloudInstall/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    OCA\DAV\Connector\Sabre\File->put(null)
10. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 316
    OCA\DAV\Connector\Sabre\Directory->createFile("VID_20190712_163957.mp4", null)
11. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 130
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "VID_20190712_163957.mp4")
12. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 161
    Sabre\DAV\Tree->copy("uploads/phone ... e", "files/phone ... 4")
13. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("uploads/phone ... e", "files/phone ... 4")
14. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
15. /nextcloudInstall/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
16. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
17. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
18. /nextcloudInstall/nextcloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
19. /nextcloudInstall/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
20. /nextcloudInstall/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/opt/storage/we ... p")

MOVE /nextcloud/remote.php/dav/uploads/phone/3fae32019120c97d7480ce6b8ecec114/.file
from 192.168.10.1 by phone at 2019-07-13T14:16:27+00:00



[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Could not open file at <<closure>>

 0. /nextcloudInstall/nextcloud/apps/dav/lib/Upload/AssemblyStream.php line 292
    OCA\DAV\Connector\Sabre\File->get()
 1. /nextcloudInstall/nextcloud/apps/dav/lib/Upload/AssemblyStream.php line 142
    OCA\DAV\Upload\AssemblyStream->getStream(OCA\DAV\Connector\Sabre\File {})
 2. <<closure>>
    OCA\DAV\Upload\AssemblyStream->stream_read(8192)
 3. /nextcloudInstall/nextcloud/3rdparty/icewind/streams/src/Wrapper.php line 91
    undefinedundefinedfread(null, 8192)
 4. /nextcloudInstall/nextcloud/3rdparty/icewind/streams/src/CallbackWrapper.php line 98
    Icewind\Streams\Wrapper->stream_read(8192)
 5. <<closure>>
    Icewind\Streams\CallbackWrapper->stream_read(8192)
 6. /nextcloudInstall/nextcloud/lib/private/Files/Storage/Local.php line 488
    undefinedundefinedfile_put_contents("/mnt/nextCloudS ... t", null)
 7. /nextcloudInstall/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 630
    OC\Files\Storage\Local->writeStream("files/Phone ... t", null, null)
 8. /nextcloudInstall/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 190
    OC\Files\Storage\Wrapper\Wrapper->writeStream("files/Phone ... t", null)
 9. /nextcloudInstall/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    OCA\DAV\Connector\Sabre\File->put(null)
10. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 316
    OCA\DAV\Connector\Sabre\Directory->createFile("VID_20190712_163957.mp4", null)
11. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 130
    Sabre\DAV\Tree->copyNode(OCA\DAV\Upload\FutureFile {}, OCA\DAV\Connector\Sabre\Directory {}, "VID_20190712_163957.mp4")
12. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 161
    Sabre\DAV\Tree->copy("uploads/phone ... e", "files/phone ... 4")
13. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 642
    Sabre\DAV\Tree->move("uploads/phone ... e", "files/phone ... 4")
14. <<closure>>
    Sabre\DAV\CorePlugin->httpMove(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
15. /nextcloudInstall/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpMove"], [Sabre\HTTP\Requ ... }])
16. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:MOVE", [Sabre\HTTP\Requ ... }])
17. /nextcloudInstall/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
18. /nextcloudInstall/nextcloud/apps/dav/lib/Server.php line 316
    Sabre\DAV\Server->exec()
19. /nextcloudInstall/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
20. /nextcloudInstall/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/opt/storage/we ... p")

MOVE /nextcloud/remote.php/dav/uploads/phone/3fae32019120c97d7480ce6b8ecec114/.file
from 192.168.10.1 by phone at 2019-07-13T14:16:27+00:00
```

**Comment by darmbrust** [comment]
Here are the log entries from the apache access log from another attempt of the same file (so the time stamps don't line up)

myhost.com:443 192.168.10.1 - phone [13/Jul/2019:09:45:06 -0500] "MKCOL /nextcloud/remote.php/dav/uploads/phone/3fae32019120c97d7480ce6b8ecec114 HTTP/1.1" 405 962 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.7.0"
myhost.com:443 192.168.10.1 - phone [13/Jul/2019:09:45:06 -0500] "PROPFIND /nextcloud/remote.php/dav/uploads/phone/3fae32019120c97d7480ce6b8ecec114 HTTP/1.1" 207 7747 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.7.0"
myhost.com:443 192.168.10.1 - phone [13/Jul/2019:09:45:06 -0500] "MOVE /nextcloud/remote.php/dav/uploads/phone/3fae32019120c97d7480ce6b8ecec114/.file HTTP/1.1" 503 875 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.7.0"

**Comment by darmbrust** [comment]
Still failing with latest versions - client still erroneously reports:
Upload refused because of maintenance-mode

**Comment by havenoclu** [comment]
Seeing the same issue. Just started today it looks like. Let me know if I can provide any specific info or debug.

**Comment by darmbrust** [comment]
As far as I've been able to tell, its a timeout / lock issue of some sort.  When the phone is on wifi, it keeps retrying quite frequently, always failing, never letting the lock clear.
What usually works for me, is turning off my wifi over night (its setup to only upload on wifi) and then magically, the next day it works again.  I'm guessing there is some sort of lock on the server having its time reset by each failed attempt...

**Comment by citizenserious** [comment]
same issue here

**Comment by qguv** [comment]
This may be the same issue as #23552.

**Comment by darmbrust** [comment]
> This may be the same issue as #23552.

They are the same issue - 23552 was previously filed against the client, and this bug was against the server.  Someone moved the other bug to the server, so now there are two....

**Comment by bartpolot** [comment]
I see the same behavior. After a server update, my filesystem permissions were messed up for two days. All the files that the android client tried to upload during this two day window, cannot be uploaded anymore. I cleared the cache on the client to I imagine the server is remembering the hashes.

This is trying to upload on the 17th (permissions fixed) a photo taken on the 16th (permissions broken back then)
```
172.24.0.248 - bart [17/Jun/2021:01:03:36 +0200] "HEAD /remote.php/webdav/InstantUpload/Camera/2021/06/20210616_192656.jpg HTTP/1.1" 404 -
172.24.0.248 - bart [17/Jun/2021:01:03:36 +0200] "MKCOL /remote.php/dav/uploads/bart/46d3d577796d563e91bbb4069056c052 HTTP/1.1" 405 247
172.24.0.248 - bart [17/Jun/2021:01:03:36 +0200] "PROPFIND /remote.php/dav/uploads/bart/46d3d577796d563e91bbb4069056c052 HTTP/1.1" 207 1063
172.24.0.248 - bart [17/Jun/2021:01:03:37 +0200] "MOVE /remote.php/dav/uploads/bart/46d3d577796d563e91bbb4069056c052/.file HTTP/1.1" 503 221

```
On the MKCOL step the server refuses to play ball.

This is taking a picture afterwards and the picture uploading fine:

```172.24.0.248 - bart [17/Jun/2021:01:05:03 +0200] "HEAD /remote.php/webdav/InstantUpload/Camera/2021/06/20210617_010409.jpg HTTP/1.1" 404 -
172.24.0.248 - bart [17/Jun/2021:01:05:03 +0200] "MKCOL /remote.php/dav/uploads/bart/48dc46f9bd62c05d4057b6bf99442864 HTTP/1.1" 201 -
172.24.0.248 - bart [17/Jun/2021:01:05:03 +0200] "PROPFIND /remote.php/dav/uploads/bart/48dc46f9bd62c05d4057b6bf99442864 HTTP/1.1" 207 770
172.24.0.248 - bart [17/Jun/2021:01:05:04 +0200] "PUT /remote.php/dav/uploads/bart/48dc46f9bd62c05d4057b6bf99442864/0000000000000000-0000000003069110 HTTP/1.1" 201 -
172.24.0.248 - bart [17/Jun/2021:01:05:04 +0200] "MOVE /remote.php/dav/uploads/bart/48dc46f9bd62c05d4057b6bf99442864/.file HTTP/1.1" 201 -
172.24.0.248 - bart [17/Jun/2021:01:05:04 +0200] "PROPFIND /remote.php/webdav/InstantUpload/Camera/2021/06/20210617_010409.jpg HTTP/1.1" 207 901
172.24.0.248 - bart [17/Jun/2021:01:05:05 +0200] "GET /index.php/apps/files/api/v1/thumbnail/256/256/InstantUpload/Camera/2021/06/20210617_010409.jpg HTTP/1.1" 200 15202```

All my pictures from the 15th and 16th refuse to be uploaded, reason given "server is in maintenance mode" although the server is (no longer) broken. I have 120 files in limbo right now.

What is the MKCOL step doing? I don't see any files, is it writing metadata to the DB? Could I delete this cache somehow, to process the files as new?

**Comment by bartpolot** [comment]
Seems the [Sabre DAV Server](https://github.com/nextcloud/3rdparty/blob/feb132082446377099f8ef2cbae59e7f5b7c8793/sabre/dav/lib/DAV/Server.php#L1183) indicate with 405 that a "resource exists", but where? It isn't in the file system, I think:
```
[root@cassini nextcloud]# find -name 46d3d577796d563e91bbb4069056c052
[root@cassini nextcloud]# ls bart/uploads/ -l
total 20
drwxrwxr-x 2 http http 4096 Mar 27  2020 28f70cd3318f8a3e0b4caaa8ee8b81be
drwxrwxr-x 2 http http 4096 Mar 28  2020 804ede5167727f6a1ced6a08d046590f
drwxrwxr-x 2 http http 4096 Mar 27  2020 c91ea3c66eec0962f117980be71a7476
drwxrwxr-x 2 http http 4096 Mar 28  2020 f335675c0f6acfc2e318b0aee655d4f6
drwxrwxr-x 2 http http 4096 Mar 27  2020 f3eb706070d0f76a2c25ff404cb12fb9

```
My DAV knowledge is null, I have no idea where this Sabre DAV Tree is located and I ran out of time to read the code. I'll try to continue tomorrow but I'd appreciate any hints about this DAV Tree. It also seems I have some leftover upload from March 2020.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.4? If not, please close this issue. Thanks! :)

**Comment by AeroSteveO** [comment]
Things I tried: 
- clearing out the file locks table (there were 600,000 entries in it, and i'm the only user on the server)
- occ db:add-missing-columns
- occ db:add-missing-indices
- occ db:add-missing-primary-keys
What finally worked:
- occ files:scan --all
Finally with the files:scan --all it started working again and my app was able to start uploading to the server.

Details:
NextCloud version 22.1.0 running in the official container on unraid
Android app version 3.16.1 from FDroid

**Comment by szaimen** [comment]
> * clearing out the file locks table (there were 600,000 entries in it, and i'm the only user on the server)

Honestly, this sounds like a misconfiguration to me if you have that many file locks...

**Comment by darmbrust** [comment]
bump.
From the other bug, that got moved to server (and should be duped with this one now) someone noted that this cleans the issue when it happens:
./occ files:scan --all, 

But there is still no fix or understanding of why the server is getting confused by a broken upload, and staying "locked" on that file for long periods of time and not cleaning up properly.

**Comment by szaimen** [comment]
> From the other bug, that got moved to server

which one?

**Comment by darmbrust** [comment]
bug 23552 started as a client bug, and had some investigation along its life... then it got moved to server, and went dormant like this one.  I'm sure they are the same issue.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/23552 then.

**Comment by darmbrust** [comment]
duplicate of #23552
