### ISSUE TITLE
Unauthorized user can delete data in shared folders he's not autorized to access

### ISSUE THREAD

**Issue by jlord87** [nextcloud/server#16381]
### Steps to reproduce
1. create a group folder named TEST and share with "admin group" and "test group", marking the advanced permission flag
2. create two folders inside the main share: visible and invisible
3. inside "invisible" folder create a test file (let's say something like "test.txt")
4. set the advanced folder permission to deny everything to "test group" for the "invisible" folder (deny read, deny write, deny share, deny create, deny delete...)
5. log in with test user (member of test group). The invisible folder is not shown, you can only see the visible one. That's great.
6. if you try to create a folder named "invisible" you get an error (that's good too)
7. sync the new external share to your pc (in my case win7 with 2.5.2 client). Only the "visible" folder is synced.
8. create a folder named "temp" and create inside this new folder a new file (lets say "test2.txt"). This folder will be synced online
9. rename temp to invisible
10. the folder gets synced online overwriting the originale "invisible" folder

### Expected behaviour
The sync client should keep denying the syncronization of "invisible" folder to the unauthorized users

### Actual behaviour
The folder is synced, the original one and all its content (that should be inaccessible to test user) are overwritten and lost

### Server configuration

**Operating system**: Ubuntu 18.04.02

**Web server:** Server version: Apache/2.4.29 (Ubuntu); Server built:   2019-06-28T16:49:35

**Database:** mysql  Ver 14.14 Distrib 5.7.26, for Linux (x86_64) using  EditLine wrapper

**PHP version:** PHP 7.2.19-0ubuntu0.18.04.1

**Nextcloud version:** 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated. (first install was owncloud 7.0.4.2

**Where did you install Nextcloud from:** I don't remember.

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.4
  - extract: 1.2.0
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_accesscontrol: 1.6.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - forms: 1.0.3
  - groupfolders: 4.0.3
  - impersonate: 1.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.4.0
  - password_policy: 1.6.0
  - passwords: 2019.7.1
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - ransomware_detection: 0.5.2
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.2
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_texteditor
  - gallery
  - socialsharing_email
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "overwriteprotocol": "https",
        "theme": "",
        "maintenance": false,
        "log_type": "file",
        "log_authfailip": true,
        "auth.bruteforce.protection.enabled": true,
        "log_rotate_size": 52428800,
        "logtimezone": "Europe\/Rome",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 1,
        "activity_expire_days": 180,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "trusted_domains": [
            "my.domain.it",
            "my.domain.org",
            "192.xxx.yyy.zzz"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "updatechecker": false,
        "trashbin_retention_obligation": "auto",
        "0": 60,
        "versions_retention_obligation": "auto",
        "1": 60,
        "overwrite.cli.url": "https:\/\/my.domain.org",
        "updater.release.channel": "production",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 68.0

**Operating system:** Windows 7

**I know, duplicating issues is not the answer, I'm trying to raise attention to this situation that seems to be ignored in https://github.com/nextcloud/groupfolders/issues/505**
If you do believe this ticket should not exists feel free to delete it.

PS. If you do really need log I'll try to get you some. I'm in a production environment so it was difficult for me to isolate relevant portion of logs, being the system in use by other users

Thank you

**Comment by kesselb** [comment]
For security related issues: https://hackerone.com/nextcloud

This should be faster than duplicating the issue here.

**Comment by jlord87** [comment]
ok, thank you, sorry for all this noise, opened a security issue as suggested
