### ISSUE TITLE
Internal Server Error when `config_is_read_only` is set and config is not writable by www-data

### ISSUE THREAD

**Issue by leonklingele** [nextcloud/server#16395]
### Steps to reproduce
1. Add `'config_is_read_only' => true,` to your `config.php`
2. `chown -R root: /path/to/nextcloud/config/`

### Expected behaviour
Nextcloud should work fine

### Actual behaviour
Nextcloud doesn't work fine, shows `Internal Server Error` page, yet doesn't log anything.

### Server configuration

**Operating system**:
`Linux nextcloud 4.19.0-5-amd64 #1 SMP Debian 4.19.37-5 (2019-06-19) x86_64 GNU/Linux`

**Web server:**
`nginx version: nginx/1.14.2`

**Database:**
`mariadb-server                  1:10.3.15-1`

**PHP version:**
`php-fpm                         2:7.3+69`

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Release tarball

**Web server error log:**

```
[..]
2019/07/14 16:54:47 [error] 150#150: *2086 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 140PHP message: {"reqId":"5lHfVz3djClauspgcb7a","level":3,"time":"2019-07-14T14:54:47+00:00","remoteAddr":"fd42:6345:e3f8:de3e:216:3eff:fef8:baa9","user":"--","app":"PHP","method":"GET","url":"\/core\/img\/manifest.json","message":"touch(): Utime failed: Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#240","userAgent":"Mozilla\/5.0 (X11; U; Linux i686) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.84 Safari\/537.36","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 140PHP message: {"reqId":"5lHfVz3djClauspgcb7a","level":3,"time":"2019-07-14T14:54:47+00:00","remoteAddr":"fd42:6345:e3f8:de3e:216:3eff:fef8:baa9","user":"--","app":"PHP","method":"GET","url":"\/core\/img\/manifest.json","message":"fopen(\/var\/www\/nextcloud\/config\/config.php): failed to open stream: Permission denied at \/var\/www\/nextcloud\/lib\/private\/Config.php#241","userAgent":"Mozilla\/5.0 (X11; U; Linux i686) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.84 Safari\/537.36","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 140PHP message: {"reqId":"5lHfVz3djClauspgcb7a","level":3,"time":"2019-07-14T14:54:47+00:00","remoteAddr":"fd42:6345:e3f8:de3e:216:3eff:fef8:baa9","user":"--","app":"PHP","method":"GET","url":"\/core\/img\/manifest.json","message":"chmod(): Operation not permitted at \/var\/www\/nextcloud\/lib\/private\/Config.php#244","userAgent":"Mozilla\/5.0 (X11; U; Linux i686) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/71.0.3578.84 Safari\/537.36","version":""}PHP message: PHP Warning:  fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.lo
[..]
```

**Comment by kesselb** [comment]
Mind to check the permission of the log file? Looks like it's not writeable.

**Comment by wiswedel** [comment]
> Mind to check the permission of the log file? Looks like it's not writeable.

With chown on root it's not even readable for www-data. That's the problem here.

Try ```setfacl -m u:www-data:r config.php```

**Comment by leonklingele** [comment]
The log file (`/srv/nextcloud-data/nextcloud.log`) is owned by `www-data`:
`-rw-r-----  1 www-data www-data 3079618 Jul 15 23:40 nextcloud.log`

The Nextcloud installation resides at `/var/www/nextcloud`, but the data directory lives under `/srv/nextcloud-data`. The relevant `config.php` excerpt:

```
  'datadirectory' => '/srv/nextcloud-data',
```

Might this be the problem here?

**Comment by kesselb** [comment]
> fileperms(): stat failed for /var/www/nextcloud/data/nextcloud.log in /var/www/nextcloud/lib/private/Log/File.php on line 140

A) `logfile` in config points to another location
B) config file is not readable

**Comment by leonklingele** [comment]
Sorry for the trouble! @wiswedel was right, Nextcloud apparently made `config.php` world-un-readable.
Solved by chowning it to `root:www-data`:

`
-rw-r-----  1 root www-data  1632 Jul 15 23:43 config.php
`
