### ISSUE TITLE
Change auto-commit of changes in admin settings

### ISSUE THREAD

**Issue by waip2Ohng9oh** [nextcloud/server#16407]
**Is your feature request related to a problem? Please describe.**
The auto-commit of changed settings in the Web UI without an explicit Apply button already led to a few unnecessary service interruptions in situation where I needed to change different settings at once. Especially the LDAP app and Theming are candidates to easily mess things up.

**Describe the solution you'd like**
Every settings page should have a "Apply changes" button

**Comment by violoncelloCH** [comment]
cc @nextcloud/designers

**Comment by MorrisJobke** [comment]
Similar to #13805, #4097 and #14327

**Comment by jancborchardt** [comment]
LDAP has a specific save button already.

Theming shouldn't be unnecessarily complicated, and the changes are directly shown.

Many times people forget to press the save button and that's much more frustrating. As said, in the case of LDAP we have the save button cause it's quite a special config.
