### ISSUE TITLE
Can't enable server-side encryption on Nextcloud 16.0.2 and 16.0.3

### ISSUE THREAD

**Issue by arv4** [nextcloud/server#16410]
### Steps to reproduce
1. Install a new Nextcloud 16.0.3 or 16.0.2
(you can use the docker image, the archive file or use an instant trial on https://demo.nextcloud.com/)
2. Enable the app 'Default encryption module'
3. Enable server-side encryption in settings

### Expected behaviour
Server-side encryption should be enabled.
New keys should be generated in 'data/files_encryption'

### Actual behaviour
Server-side encryption is not enabled.
You get no error message on the GUI.
After refreshing the site (pressing F5) the tick at the box "Enable server-side encryption" disappeared.
No new keys got generated in the '/data/' directory.

When activating server-side encryption in settings an XHR POST request will be sent to '/ocs/v2.php/apps/provisioning_api/api/v1/config/apps/core/encryption_enabled'
The response of this XHR request is "The given key can not be set"

Nextcloud 16.0.1 works without problems.
A few hours https://demo.nextcloud.com/ got updated to Nextcloud 16.0.3
(Yesterday it was still Nextcloud 16.0.1)
The problem also occurs there.

---

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache 2.4.29

**Database:** PostgreSQL and SQLite

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 16.0.3 and 16.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** archive file and web installer from https://nextcloud.com/install/#instructions-server
docker container via 'docker pull nextcloud'

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - encryption: 2.4.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_external_onedrive: 0.1.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "16.0.1.1",
        "overwrite.cli.url": "REMOVED",
        "installed": true
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** I would like to

**Are you using an external user-backend, if yes which one:** no

**Comment by kesselb** [comment]
Thank you :+1: 

Looks like a regression from https://github.com/nextcloud/server/pull/16121

cc @nickvergessen

**Comment by nickvergessen** [comment]
Fix is at https://github.com/nextcloud/server/pull/16423
