### ISSUE TITLE
Create new External Storage for Nextcloud

### ISSUE THREAD

**Issue by Indrajit05** [nextcloud/server#16436]
I want to create a new external storage for Nextcloud like amazonS3, FTP, OwnCloud.. but with my own storage API. But there is no documentation Nextcloud to do that.

**Comment by clementduveau** [comment]
Hi,

You can find the source of every implemented backend in server/apps/files_external/lib/Lib/Backend/. If you succesfully make your own connector, please fill the doc.

Nextcloud give access to a lot of existing standards, which one is missing for you ?

Regards

**Comment by blizzz** [comment]
As this seems not to be an issue with out code I would like to ask you to raise your question in the forums: https://help.nextcloud.com 

Another app that adds support for a different storage is the sharepoint app. You can check out the code as example. https://github.com/nextcloud/sharepoint

Also, if you don't find enough information in the [developer docs](https://docs.nextcloud.com/server/16/developer_manual) you can file a bug on that repo https://github.com/nextcloud/documentation/ (or even better improve it :) )
