### ISSUE TITLE
Nextcloud 15 - Can’t login and getting no err message on web interface

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#16435]
I have a nextcloud instance installed on a CentOS 7 server. I'm using apache and mariadb. Since today I can no longer login with my admin account or user account. When I try to login I get redirected to the login page with no error. My nextcloud folder is under the web server permission and same for`/var/lib/php/session` so `apache:apache`

Here is my config.php

    <?php
    $CONFIG = array (
      'passwordsalt' => 'SECRET',
      'secret' => 'SECRET',
      'trusted_domains' =>
      array (
        0 => 'SECRET',
      ),
      'datadirectory' => '/var/www/html/files/data',
      'overwrite.cli.url' => 'https://SECRET/files',
      'dbtype' => 'mysql',
      'version' => '15.0.0.10',
      'integrity.check.disabled' => true,
      'dbname' => 'SECRET',
      'dbhost' => 'SECRET',
      'dbport' => '',
      'dbtableprefix' => 'oc_',
      'dbuser' => 'SECRET',
      'dbpassword' => 'SECRET',
      'logtimezone' => 'UTC',
      'installed' => true,
      'memcache.local' => '\\OC\\Memcache\\Redis',
      'memcache.locking' => '\\OC\\Memcache\\Redis',
      'redis' =>
      array (
        'host' => 'SECRET',
        'port' => SECRET,
        'password' => 'SECRET',
      ),
      'mail_smtpmode' => 'sendmail',
      'mail_from_address' => 'noreply',
      'mail_domain' => 'SECRET',
      'knowledgebaseenabled' => false,
      0 => 18,
      'loglevel' => 1,
      'maintenance' => false,
      'instanceid' => 'SECRET',
    );

I also don't understand why I can no longer record new logs error on `data/nextcloud.log`

**Comment by vipera7** [comment]
My disk was full so PHP was not able to create PHP session file

**Comment by violoncelloCH** [comment]
that's most possibly a configuration issue: with no remaining space in the log / session partition
