### ISSUE TITLE
stat(): stat failed for appdata

### ISSUE THREAD

**Issue by Happyfeet01** [nextcloud/server#16449]
Hello, 

Has anyone an idea how can I solve this error? 

`stat(): stat failed for /var/www/html/data/appdata_ocy0lsrwx5ys/preview/someimage.jpg at /var/www/html/lib/private/Files/Storage/Local.php#143`

Nextcloud 16.0.3
Ubuntu 18.04
PHP 7.3.7
Docker Installation

**Comment by SlavikCA** [comment]
I have same error for External Storage => Local mount.

There is no error while accessing files in the default location.

**Comment by JakobPP** [comment]
Dont know if theyre related, but.

https://github.com/nextcloud/nextcloud-snap/issues/452

**Comment by kesselb** [comment]
@Happyfeet01 for files in appdata i would try to rescan the app folder. occ has a command for that.

**Comment by Happyfeet01** [comment]
The scan command is executed as an Cronjob, But i scan with the Command 
occ files:scan-app-data and look into my logfiles for the next error message. Maybe lsolved...
