### ISSUE TITLE
HTML injection and javascript url

### ISSUE THREAD

**Issue by 1Jesper1** [nextcloud/server#16446]
It is possible to inject HTML into the login page from the Theme => weblink input: ">'><input type="text" />.
It's also possible to fill in javascript as protocol in the contacts custom field => website input.

**Comment by kesselb** [comment]
Thanks for reporting this issue :+1: 

Mind to use the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? Skip the server related stuff (like config, apps, etc.) but some information like affected version and how to reproduce would be nice.

> It is possible to inject HTML into the login page from the Theme => weblink input: ">'>.

![image](https://user-images.githubusercontent.com/3902676/61412279-be4b5d80-a8e8-11e9-9a2f-68abccce5cc2.png)

This one right?

> It's also possible to fill in javascript as protocol in the contacts custom field => website input.

Can you elaborate a bit?

Do you think this a security vulnerability? 
For such issues https://hackerone.com/nextcloud is the better way.

cc @nextcloud/security @juliushaertl @skjnldsv

**Comment by 1Jesper1** [comment]
@kesselb You are right!
Reproduce problem 1:
Fill "`">'><input type="text">`" into the input

>  Web link

Reproduce problem 2:
I think the javascript protocal should not be valid in the url validation.
Use the contacts plugin.
Create contact => fill in `javascript:123` into the 

> Website

 input field (custom field)
Browser:
Chrome

Version:
Nextcloud 16.0.3

**Comment by rullzer** [comment]
Thanks for the report @1Jesper1 
While you are right that we should fix this theming is only available for admins (which can do a lot worse already ;) ).

@juliushaertl could you look into this?

**Comment by skjnldsv** [comment]
@nickvergessen please do not remove a status label :)

**Comment by nickvergessen** [comment]
well removing triage was correct, not sure I forgot to check develop or if it was a github hickup
