### ISSUE TITLE
[Feature Request] Easy to access "log-in via qr code" button

### ISSUE THREAD

**Issue by Aurnytoraink** [nextcloud/server#16469]
**Is your feature request related to a problem? Please describe.**
There is so many steps to add a new device. Let's make it clear !

**Describe the solution you'd like**
Add a button in the "profile quick actions list" that allow the user to easily connect a new device by generating a QR code. Adding this button perform this action must faster than going in Settings>Security>Scroll down the page>New Device>Via QR code.

For better explanation, I leave here a picture
![picture](https://user-images.githubusercontent.com/28545669/61536716-93225480-aa35-11e9-84c3-fe231cf27422.png)

**Describe alternatives you've considered**
Well, that's an alternative so...

**Additional context**
Nothing special to add. Maybe we can add a prevention message like "You can check all your active sessions in the setting panel

**Comment by skjnldsv** [comment]
cc @ChristophWurst @rullzer

**Comment by ChristophWurst** [comment]
I see how that is a neat shortcut for the first setup. But quite frankly, you'll hardly need this again afterwards. Like I need this setting once every three years when I get a new phone. YMMV but this is not the right place to put it :)
