### ISSUE TITLE
 NC17 admin setup check incorrectly reports 'nosniff' header is not set

### ISSUE THREAD

**Issue by pgnd** [nextcloud/server#16476]
I'm running
```
NC 17
	git log | head
		commit 602a48c411cb242840a25f59e5eff44e40d0094c
		Author: Nextcloud bot <bot@nextcloud.com>
		Date:   Sat Jul 20 02:14:33 2019 +0000

		    [tx-robot] updated from transifex

		commit a085a88205ccf833c347c1b0a5021ca2ee8db484
		Merge: c00d6f4eac 2c5ebac458
		Author: Morris Jobke <hey@morrisjobke.de>
		Date:   Fri Jul 19 18:03:37 2019 +0200

php -v
	PHP 7.4.0-dev (cli) (built: Jul 20 2019 07:05:36) ( NTS )
	Copyright (c) The PHP Group
	Zend Engine v3.4.0-dev, Copyright (c) Zend Technologies
	    with Zend OPcache v7.4.0-dev, Copyright (c), by Zend Technologies

nginx -v
	nginx version: nginx/1.17.1 (Local Build)
```

on the NC 17/head's admin setup-check page,

>	/admin/overview

it currently reports here,

>	The "X-Content-Type-Options" HTTP header is not set to "nosniff". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.

in my webserver config, I've
```
	add_header X-Content-Type-Options "nosniff" always;
```

checking document response headers on that NC admin page,
```
	HTTP/2.0 200 OK
	date: Sat, 20 Jul 2019 14:55:39 GMT
	content-type: text/html; charset=UTF-8
	vary: Accept-Encoding
	x-powered-by: PHP/7.4.0-dev
	expires: Thu, 19 Nov 1981 08:52:00 GMT
	pragma: no-cache
	x-frame-options: SAMEORIGIN
	cache-control: no-cache, no-store, must-revalidate
	content-security-policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'nonce-UjB...ST0=';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self';frame-ancestors 'self'
	nextcloud: App
>>	x-content-type-options: nosniff
	strict-transport-security: max-age=315360000; includeSubDomains; preload
	x-content-type-options: nosniff
	x-xss-protection: 1; mode=block
	x-robots-tag: none
	x-download-options: noopen
	x-permitted-cross-domain-policies: none
	content-encoding: br
	X-Firefox-Spdy: h2
```

**Comment by kesselb** [comment]
Warning is shown because `X-Content-Type-Options` is there 2x.

**Comment by pgnd** [comment]
twice?

It's set only once in my config.
It's show only once in the response headers, above.

Can you clarify?

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/61581178-3731fb80-ab1b-11e9-8393-5715e070346f.png)

**Comment by pgnd** [comment]
ok, now that we've established that I'm blind as a bat ...

my bad. sry.

**Comment by pgnd** [comment]
although, that doesn't explain WHY there are 2x in the response headers.

there's only one instance of the header-set in my config ...

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/3b1e16458d59ea53b170d6099df3454d0590e87a/lib/private/legacy/response.php#L101-L103

`X-Content-Type-Options` is added by nextcloud to the response if `modHeadersAvailable` is not true. https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html for more details about the nginx configuration.

**Comment by eehmke** [comment]
I have this problem since upgrading to 17.0.0 Beta1 with Apache. X-Content-Type-Options is set to nosniff in .htaccess, as can be checked by https://www.webconfs.com/http-header-check.php. There are no double entries.

**Comment by eehmke** [comment]
Please reopen the issue. This is still a problem when the apache configuration has set the header. In Debian 10.1, Apache Apache 2.4.38, the header is set in
/etc/apache2/conf-available/security.conf
The statement in .htaccess should be conditional, so it is only set when not already present.

Header setifempty X-Content-Type-Options "nosniff"
in .htaccess does the trick. It works whether the option is set in the apache config or not.

Beside of this, the error message is misleading. If the option is set twice, it should not say "header is not set".

**Comment by kesselb** [comment]
> Header setifempty X-Content-Type-Options "nosniff"
in .htaccess does the trick. It works whether the option is set in the apache config or not.

Looks good to me. Would you mind to create a pr with your changes? https://github.com/nextcloud/server/edit/master/.htaccess

**Comment by eehmke** [comment]
That's fine, thanks for quick response. Alert: this problem might apply for other headers too.

**Comment by cyBea** [comment]
I have the same issue using apache on buster. Since there is no change in master and no pull request the issue is not resolved.
@kesselb Do you think replacing every occurence of "always set" with "setifempty" in .htaccess is a good solution? Could it have any side effects?

**Comment by kesselb** [comment]
>  Could it have any side effects?

I don't know. Fixing your setup is probably the better way. There are some threads at https://help.nextcloud.com about this warning.

**Comment by zertrin** [comment]
After upgrading to NC 17 I had the case that the headers were set twice. That is because in by case the server admin has configured the apache host server to already set these headers site-wise (across all virtualhosts, not only nextcloud). Then the .htaccess of nextcloud adds them again...

Solved the warnings and double setting of headers by replacing every occurrence of `always set` with `setifempty` in `.htaccess`. This works well.

I think here Nextcloud is being too aggressive with header setting. When the host server already has a security policy in place, and already set those headers, Nextcloud should not `always set` its own headers on top.

Thus I also petition to change the default `.htaccess` to use `setifempty`.

**Comment by zertrin** [comment]
> Looks good to me. Would you mind to create a pr with your changes? https://github.com/nextcloud/server/edit/master/.htaccess

Opened PR #19002 😉

**Comment by eehmke** [comment]
This is still an issue with NC 19.0.0 beta 4. The "onsuccess unset" line is not in .htaccess.

**Comment by zertrin** [comment]
The pull request is ready to merge but was not yet included in the latest beta apparently.

Hope it can make it this round.
