### ISSUE TITLE
Theming - Nextcloud won't display custom favicon unless logged in

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#16504]
### Steps to reproduce
0. Make sure you're using custom favicon (settings->theming->favicon)
1. Load nextcloud instance in say, incognito window, where you won't be logged in automatically
2. Notice the favicon is default Nextcloud logo
3. Log in, only then it changes to your own favicon

Picture: default favicon
![Screenshot_1](https://user-images.githubusercontent.com/36133540/61647315-5eb8cd80-acad-11e9-9e91-afcd127cc836.png)

### Expected behaviour
Customized favicons should be displayed for non logged-in users as well as for logged-in

### Server configuration

**Operating system**: ubuntu 19
**Nextcloud version:** 15 snap

**Comment by GretaD** [comment]
hey @pilsnerbeer, i cannot reproduce this bug, I changed my favicon and logged out, I used chrome and firefox and also incognito and the favicon its the same when I'm logged out. Can you please check if this problem still exist for you?\

I tested it on nextcloud 15, 16 and 17.

**Comment by pilsnerbeer** [comment]
Hi, thanks for checking. I have to say that the issue's no longer present, the favicon loads properly now. Perhaps my server was overloaded at the time or something. Closing the issue for now.
