### ISSUE TITLE
Table: oc_file_locks has TTL set for too long, or values don't get removed correctly

### ISSUE THREAD

**Issue by zontreck** [nextcloud/server#16508]
### Steps to reproduce
1. Sync a huge amount of files (upwards of 500k should do?)
2. Modify a chunk of those files
3. While the app is syncing, modify a few other files
4. Occasionally you'll get the error indicating the files are locked. 
5. Check oc_file_locks table, the values are indeed still locked, and the TTL would expire in a few hours. 

### Expected behaviour
Tell us what should happen
TTL should be less than this, 2 minutes max. Additionally, the cron.php task should remove expired locks. The TTL length should be customizable though, and i see no way to change this without digging deep into the code.

### Actual behaviour
Tell us what happens instead
The files remain locked for hours. Sometimes i have had to go in and flush the file_locks table.

### Server configuration

**Operating system**: Ubuntu

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 7.2.19 (Jan 4, 2019)

**Nextcloud version:** 16.0.3

**Updated from an older Nextcloud install* 

**Where did you install Nextcloud from: ** Release downloads

**Signing status:**
<details>
<summary>Signing status</summary>

```
Results
=======
- core
	- EXTRA_FILE
		- .rnd

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [.rnd] => Array
                        (
                            [expected] => 
                            [current] => 478571eb43830b922bb3ce5fcec384f1eddcd9440851407412346e63338961ca71fe3128a6a4862ebf48b0df019f643e24192ef4a12ec46f27e7bbfbed107f8c
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.1
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ownpad: 0.6.13
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.xsinode.net:2590"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "overwrite.cli.url": "http:\/\/cloud.xsinode.net:2590",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local storage in data folder

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chrome

**Operating system:**  Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Too long to paste
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
http://xsinode.net:2589/cloud.log
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The errors occured in the database and in the client app, not the browser
```
</details>

**Comment by szaimen** [comment]
Hi, you can modify the timelocking value in the config.php file in this way:
![image](https://user-images.githubusercontent.com/42591237/119644302-014bb580-be1d-11eb-925e-dcff461a4611.png)
