### ISSUE TITLE
Fresh install NC 16.0.3 (docker), cannot change theme. Nothing happens...

### ISSUE THREAD

**Issue by okoester** [nextcloud/server#16501]
Cannot change theme settings to customize Nextcloud installation.
I'd like to use custom logo and links to privacy policy and legal notice. I'd also like to "rename" the instance with a custom name .

I've already tried this and similar things:
https://github.com/nextcloud/server/issues/8888 

Neither
`occ maintenance:theme:update`
nor installing "unsplash" app does work for me...

### Steps to reproduce
1. Login as Nextcloud Admin
2. Settings / Theming
3. Change Theming Settings

### Expected behaviour
Text and Images on Login Page should show new Logo/Background and texts/links to legal notice and privacy policy. Name shall appear in browser site name (tab)

### Actual behaviour
Texts inside theming are changed to new values. Images (logo, background do not appear in preview. Checking login page does not show any changes. Browser tab (site name) is changed temporarily, but when relaoding page or switch to another, its gone.

### Server configuration

**Operating system**:
Official docker image nextcloud:latest

**Web server:**
see docker image 

**Database:**
mariadb

**PHP version:**
see docker image
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install 

**Where did you install Nextcloud from:**
docker image

**Signing status:**
?

```
No errors found
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - forms: 1.0.3
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 2.1.2
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - firstrunwizard
  - survey_client
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.3.0",
        "overwrite.cli.url": "https:\/\/sensitive-cloud.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "default_locale": "de_DE",
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 86400,
        "session_lifetime": 86400,
        "auth.bruteforce.protection.enabled": true,
        "skeletondirectory": "\/var\/www\/html\/config\/skeleton",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "3, auto",
        "versions_retention_obligation": "auto",
        "updatechecker": true,
        "loglevel": "0",
        "logdateformat": "d. F Y H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 104857600,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "activity_expire_days": 14,
        "maintenance": false,
        "upgrade.disable-web": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": []
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 68.0 (Quantum) x64

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"EYlvuAQd96aleAtsX5zv","level":3,"time":"2019-07-19T13:39:58+00:00","remoteAddr":"***REMOVED***","user":"nc-admin","app":"index","method":"GET","url":"\/apps\/theming\/img\/core\/filetypes\/folder.svg?v=0","message":{"Exception":"OCP\\Files\\NotPermittedException","Message":"Could not create folder","Code":0,"Trace":[{"file":"\/var\/www\/html\/lib\/private\/Files\/AppData\/AppData.php","line":155,"function":"newFolder","class":"OC\\Files\\Node\\Folder","type":"->","args":["0"]},{"file":"\/var\/www\/html\/apps\/theming\/lib\/ImageManager.php","line":155,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["0"]},{"file":"\/var\/www\/html\/apps\/theming\/lib\/ImageManager.php","line":170,"function":"getCacheFolder","class":"OCA\\Theming\\ImageManager","type":"->","args":[]},{"file":"\/var\/www\/html\/apps\/theming\/lib\/Controller\/IconController.php","line":87,"function":"getCachedImage","class":"OCA\\Theming\\ImageManager","type":"->","args":["icon-core-filetypes_folder.svg"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"getThemedIcon","class":"OCA\\Theming\\Controller\\IconController","type":"->","args":["core","filetypes\/folder.svg"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Theming\\Controller\\IconController"},"getThemedIcon"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Theming\\Controller\\IconController","getThemedIcon",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"app":"core","image":"filetypes\/folder.svg","_route":"theming.Icon.getThemedIcon"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"app":"core","image":"filetypes\/folder.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"app":"core","image":"filetypes\/folder.svg","_route":"theming.Icon.getThemedIcon"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/apps\/theming\/img\/core\/filetypes\/folder.svg"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/lib\/private\/Files\/Node\/Folder.php","Line":162,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"***REMOVED***"}
```

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by okoester** [comment]
Here's the log from Firefox console as described.

I've changed the domain name due to security reasons, but left everythin else unchanged...
[firefox-console.log](https://github.com/nextcloud/server/files/3420474/firefox-console.log)

Just to mention: 
I did the same with Chrome browser (75.0.3770.142 x86). This is the log:
[chrome-1563863149156.log](https://github.com/nextcloud/server/files/3420505/chrome-1563863149156.log)

With Chrome browser, same behaviour appeared.

Second to mention:
As far as I can say, the text strings I had changed were saved but not promoted.
I changed the site name several times, the green "saved" appeared, and when I left the theming page and came back, the changes are still in the forms. But theme stays same as described in first post...

**Comment by kesselb** [comment]
Mind to check the permission for your `data` directory? Nextcloud tried to create a folder inside `data/appdata_xxxx` and failed.

**Comment by okoester** [comment]
Permissinos of data folder look like this:
![grafik](https://user-images.githubusercontent.com/8364976/61767955-2963cb00-ade6-11e9-91f0-868f05ecb89e.png)
From my point this looks like apache can access all folders with write permission...

Permissions of data/appdata_xxx:
![grafik](https://user-images.githubusercontent.com/8364976/61767886-eace1080-ade5-11e9-9190-e59c06d59ee3.png)

I can't see any errors, but maybe you can?

I was wondering that some files/dirs are having www-data:www-data while most have www-data:root

Different time stamps of folders and files may come from docker. I started first with only apps, data, config folders in docker-compose.yml, later I added /var/www/html as a whole

**Comment by alexcustos** [comment]
I'm running Nextcoud on Apache Docker container. I updated my 14.0.3 old instance up to 15.0.9 version first (I didn't test it very well), then to the latest 16.0.3 and ran into this weird issue. When I'm updating theming app settings, I get /data/appdata_xxxx/css/theming/yyyy-zzzz-theming.css file removed, and get it back in a few minutes (usually it takes 2-4 minutes unless I restart the Apache container). During this time website looks broken because it can't load that CSS. The issue doesn't connect to Cron job which is scheduled to start every 15 minutes. I tried to disable all third-party apps then official apps too except ones that come within the initial package, but it didn't help. I'm also getting nothing in /data/nextcloud.log file.

**Comment by vogelfreiheit** [comment]
```
[index] Error: OCP\Files\NotPermittedException: Could not create folder at <<closure>>

 0. /var/www/html/lib/private/Files/AppData/AppData.php line 155
    OC\Files\Node\Folder->newFolder("2")
 1. /var/www/html/apps/theming/lib/ImageManager.php line 155
    OC\Files\AppData\AppData->newFolder("2")
 2. /var/www/html/apps/theming/lib/ImageManager.php line 170
    OCA\Theming\ImageManager->getCacheFolder()
 3. /var/www/html/apps/theming/lib/Controller/IconController.php line 87
    OCA\Theming\ImageManager->getCachedImage("icon-core-filetypes_video.svg")
 4. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Theming\Controller\IconController->getThemedIcon("core", "filetypes/video.svg")
 5. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Theming\Controller\IconController {}, "getThemedIcon")
 6. /var/www/html/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Theming\Controller\IconController {}, "getThemedIcon")
 7. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Theming\\C ... r", "getThemedIcon", OC\AppFramework\ ... {}, {app: "core",ima ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({app: "core",ima ... "})
 9. /var/www/html/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {app: "core",ima ... "})
10. /var/www/html/lib/base.php line 975
    OC\Route\Router->match("/apps/theming/i ... g")
11. /var/www/html/index.php line 42
    OC::handleRequest()

GET /apps/theming/img/core/filetypes/video.svg?v=2
from XXX by admin at 2019-08-19T08:13:36+02:00
```

And:

```
[PHP] Error: unlink(/nextcloud-data/appdata_oc4rfoxcgiaf/css/privacy/47cd-a5b4-style.css.gzip): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#228

POST /apps/theming/ajax/updateStylesheet
from XXX by admin at 2019-08-19T08:13:27+02:00
```

Also:

`unlink(/nextcloud-data/appdata_oc4rfoxcgiaf/css/privacy/47cd-a5b4-style.css): No such file or directory at /var/www/html/lib/private/Files/Storage/Local.php#228`

There is another issue reporting the same problems, mentioning Redis as the potential culprit but I tested without it as local caching and the same situation comes up...

**Comment by szaimen** [comment]
Thank you for taking the time to report a problem 👍

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
