### ISSUE TITLE
SMB authorizations refresh

### ISSUE THREAD

**Issue by iwacky** [nextcloud/server#16519]
Steps to reproduce
1. Mount SMB volume
2. Access a folder / file with user
3. Forbid user to access folder any longer (SMB server side)

### Expected behaviour
Folder is visible but no longer browsable
No content operation can be performed

### Actual behaviour
Folder is visible and always browsable (cache)
Folder content operations can be performed (not synced)

### Server configuration
**Operating system**: Ubuntu 18
**Web server:** Apache
**Database:** MySQL
**PHP version:** 7.2
**Nextcloud version:** 16.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

Thank you for your work,
Regards

**Comment by tigernero79** [comment]
Try installing the latest smbclient version

procedure:
`sudo apt install libsmbclient-dev`

`sudo pecl channel-update pecl.php.net`

if it is not installed sudo PECL come on

`sudo apt install php7.2-dev`

then run the command:

`sudo pecl install smbclient`

if you don't worry about a segmentation error

but you will have a smbclient change from 0.9 to 1.0.0 and you will see that you are back

**Comment by szaimen** [comment]
Thank you for taking the time to report a problem 👍

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
