### ISSUE TITLE
user_ldap's ldap_agent_password not effectively tagged as sensitive data

### ISSUE THREAD

**Issue by CyrilBrulebois** [nextcloud/server#16529]
Hi,

Spotted while finalizing an installation, I wanted to dump the whole configuration for later reference.

### Steps to reproduce
1. Enable the `user_ldap` application.
1. Configure a single LDAP connection, with a client DN (as opposed to anonymous) and its associated password.
1. Dump the config **without** the `--private` flag: `occ config:list`
1. Check the value of the `s01ldap_agent_password` key under `user_ldap`.

### Expected behaviour
The LDAP agent password is replaced with `"***REMOVED SENSITIVE VALUE***"`.

### Actual behaviour
The LDAP agent password appears unedited.

This should only happen with `occ config:list --private`

As a side note: `occ ldap:show-config` and `occ ldap:show-config --show-password` behave properly.

### Server configuration

**Operating system**: Linux

**Web server:** Apache2

**Database:** MySQL/MariaDB

**PHP version:** 7.3.4

**Nextcloud version:** 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**User-LDAP configuration:** Single configuration called `s01`, with agent DN and password.

### Hunch

It seems [ce7836378cf973ecebdd6d7790f9b3994f0e88f4](https://github.com/nextcloud/server/commit/ce7836378cf973ecebdd6d7790f9b3994f0e88f4#diff-cdb763d0bc05b09a392296fde32add1d) aimed at fixing this issue.

It might not be effective because this field is actually prefixed with `s01` in my case, likely because that's the first server being configured (confirmed by my reading of `getNextServerConfigurationPrefix()` in `apps/user_ldap/lib/Helper.php`). I'm going to assume that's why it escapes the sensitive-ness check?

**Comment by wiswedel** [comment]
CC @blizzz

**Comment by blizzz** [comment]
that's probably not being caught by the mechanism as the key is prefixed
