### ISSUE TITLE
Storage wrapper warnings

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1652]
I see following two warnings in the logs:

```
Storage wrapper 'readonly' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.
```

They are added in https://github.com/owncloud/core/pull/24335

They are registered in https://github.com/nextcloud/server/blob/0215b004da6af887b3e3efa28c425d41a1c76b9b/apps/files_sharing/ajax/shareinfo.php#L66 and https://github.com/nextcloud/server/blob/1fef5d3d06752f1a2a686681ae81fd13d88e535a/apps/dav/appinfo/v1/publicwebdav.php#L79

I talked with @nickvergessen about this and he proposed to change the check to 

``` php
if (self::$logWarningWhenAddingStorageWrapper && $wrapperName !== 'readonly') {
```

@icewind1991 What do do here? Is this the correct approach or should it be done somehow differently?

**Comment by icewind1991** [comment]
Easiest sollution seems to be to disable the warning with `logWarningWhenAddingStorageWrapper` from where the wrappers are added (with a comment describing that we know what we're doing here)

**Comment by MorrisJobke** [comment]
> Easiest solution seems to be to disable the warning with logWarningWhenAddingStorageWrapper from where the wrappers are added (with a comment describing that we know what we're doing here)

Then I will do this tomorrow

**Comment by nickvergessen** [comment]
At least the one from `sharePermissions` seems to be a problem?
https://github.com/nextcloud/server/issues/1708

**Comment by MorrisJobke** [comment]
I added the part of the readonly part: #1722

**Comment by enoch85** [comment]
And this is one reason I just <3 Nextcloud. Things get fixed.

**Comment by enoch85** [comment]
@MorrisJobke No backport?
