### ISSUE TITLE
Allow to create and open website.url files

### ISSUE THREAD

**Issue by rasos** [nextcloud/server#16520]
We have organized projects in file folders and sometimes would simply like to add a URL which links to a web resource. 

## Proposal to allow to add a Web-Link in folder

In a folder's `+` menu, offer an option `Web-Link` . This creates a file dailynews.url file in the format like Windows is used to create it for the desktop, see https://fileinfo.com/extension/url 

```
[InternetShortcut]
URL=[URL Address]
```

## Open website.url in Web browser as external site

When clicking on a website.url file, nextcloud should interpret the content of the file, and not offer downloading the file, but open a new browser tab with the web resource. 

![URLopener](https://user-images.githubusercontent.com/485723/61730653-1d422400-ad7a-11e9-89b1-bd7f68678114.png)

## Alternative approaches

- Create an InterestingLink.txt file with the standard tex teditor and paste the URL(s) 
- Use the bookmark app and share with same group

Both are either not user friendly or you loose the context of the project folder structure.

**Comment by bpcurse** [comment]
Did you take a look at this app? It should provide the functionality you need.
https://apps.nextcloud.com/apps/files_linkeditor

**Comment by rasos** [comment]
@bpcurse indeed, the `files_linkeditor` app does exactly what we have been looking for. I was browsing the app store's categories when looking for solutions, expecting it under `Files`, but it is listed in `Tools`.

**Comment by te-online** [comment]
I'm a little confused – the `category` field has always been set to `files`. And I can find the app listed in `Files` on the appstore. Must have been an issue with the appstore not showing it in the specified category? Can you confirm that it's in the right category now, @rasos?

**Comment by rasos** [comment]
I can confirm that the `files_linkeditor app` is in the `Files` category, checked in two instances NC 16.0.1 and NC 15.0.8. Not sure what had confused me, sorry for the noise.

**Comment by te-online** [comment]
@rasos That's alright, thanks for confirming :-)
