### ISSUE TITLE
Delete all notfications

### ISSUE THREAD

**Issue by jgrete** [nextcloud/server#16535]
Sometimes I'm getting a heap of notifications (hundreds++) and I would like to delete them all with one click. The situation now is a little bit - hm - exhausting... One have to delete one by one
Recently I discoverred a "Delete all notification" in the Nextcloud-App - aaaahhh, wonderfull!
It would be very nice to have such a button on the Nextcloud menu...
Regards
Jürgen

**Comment by MorrisJobke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/notifications/pull/389

The button was missing, functionality is still there (e.g. in the android app).
We jsut discovered this after the 16.0.3 release. So it will come with 16.0.4 again.
