### ISSUE TITLE
'proxy' settings in config.php need an exclusion list

### ISSUE THREAD

**Issue by marcogaio** [nextcloud/server#16531]
I was testing Collabora's LOOL in a container, and i was struggling why NC does not even contact the LOOL server...

After fiddling a bit, i've found that... request get redirected to my proxy!

In config.php i've:

`  'proxy' => 'proxy:8080',`

and so all request, even the LOOL ones, get redirected to the proxy (yes, the NC container have no direct access to Internet).

I think NC need an 'exclusion' list, like the 'no_proxy' environment variable:
  https://wiki.archlinux.org/index.php/Proxy_server#Environment_variables

Thanks.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/16531
