### ISSUE TITLE
Was updating to v15 and got this error

### ISSUE THREAD

**Issue by chriskh13** [nextcloud/server#16545]
Hi guys, got this error [below] during my update. For context, I was trying to follow the instructions here for HTTPS redirect (https://docs.nextcloud.com/server/14/admin_manual/configuration_server/harden_server.html) and may have messed up the file. At the same time, I was also trying to unmount my hard drive and remount it so files were stored on the hard drive instead of the SD card. Either of those steps could've caused the issue.

Thank you !

Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: Not a mysql database -> nothing to do
Repair step: Repair SQLite autoincrement
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_filecache AS SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions, checksum FROM oc_filecache': SQLSTATE[HY000]: General error: 11 database disk image is malformed

**Comment by skjnldsv** [comment]
Please use the repository bug issue template
