### ISSUE TITLE
appstoreFetcher GuzzleHttp Exception with tremendous length

### ISSUE THREAD

**Issue by Charburner** [nextcloud/server#16552]
I just discovered a really long exception in the nextcloud.log which breaks our logwatch monitoring: **2.570.703** characters in a single line. 

It starts with `"reqId":"W04DzDL63ZUJaut4wUdH","level":1,"time":"2019-07-26T08:00:12+02:00","remoteAddr":"","user":"--","app":"appstoreFetcher","method":"","url":"--","message":{"Exception":"GuzzleHttp\\Exception\\ConnectException","Message":"cURL error 28: Operation timed out after 10000 milliseconds with 3047424 out of 3281392 bytes received` followed by a giant trace info.

Complete line: [nextcloud.log](https://github.com/nextcloud/server/files/3435236/nextcloud.log)

I'm not sure how or when the app appstoreFetcher triggers curl requests, I guess it checks for apps and updates when opening the app menu and/or via cronjob.

Could anyone guide me to what caused the exception and how to prevent it if it is an Nextcloud issue at all?

Thanks in advance

### Server configuration

**Operating system**: CentOS 7

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** PHP 7.1.8 (FPM)

**Nextcloud version:** 16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated step by step since 11.0.3

**Comment by kesselb** [comment]
> I'm not sure how or when the app appstoreFetcher triggers curl requests, I guess it checks for apps and updates when opening the app menu and/or via cronjob.

Yes

> Could anyone guide me to what caused the exception and how to prevent it if it is an Nextcloud issue at all?

The trace contains the response. That explains the size. Check https://github.com/nextcloud/server/issues/14926 for more details about timeouts and possible solutions.
