### ISSUE TITLE
Share via link: support autogenerated password

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#16589]
- [ ] Android @tobiasKaminsky 
- [ ] Desktop @camilasan 
- [ ] iOS @marinofaggiana 
- [ ] Server @nextcloud/server-triage 

When "enforce password is set" and password policy app is installed & has capability to check/generate password, we should use this:

- click on share via link
- show button "suggest password"
- fill & show it

**Comment by skjnldsv** [comment]
@tobiasKaminsky https://github.com/nextcloud/server/issues/12171

**Comment by tobiasKaminsky** [comment]
Closing in favor of #12171
