### ISSUE TITLE
Underscores (_) not allowed in admin username

### ISSUE THREAD

**Issue by MadDogDean** [nextcloud/server#16588]
### Steps to reproduce
1. Install NextCloud using Softaculous installer on cPanel
2. Change admin username on setup to any valid combination using at least one '_' underscore
3. Complete the installation 
4. Once completed if you attempt to login using your newly created admin username you will receive an "Incorrect username or password" error
5. The installation cannot be recovered as there is no means to reset the admin username as no email address is on file for the admin account (you need to login to the admin account to enter the email). This is a Catch-22 as you cannot login to change your email because the username/password combination is not recognized.

### Expected behaviour
The username should allow underscore characters

### Actual behaviour
Underscore characters break the admin login

### Server configuration

**Operating system**: 
Win7 x64

**Web server:**
Linux x86_64; 
Kernel version:  3.10.0-962.3.2.lve1.5.25.10.el7.x86_64
Apache version: 2.4.39

**Database:** 
MySQL version: 10.3.16; MariaDB

**PHP version:**
7.3

**cPanel version:** 
80.0 (build 22)

**Nextcloud version:** (see Nextcloud admin page)
16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
Softaculous app installer on cPanel

**Comment by blizzz** [comment]
@MadDogDean this is not a restriction by us. Underscores are allowed and work. I guess there is something happening on the glue code of Softaculous or c-panel. Best reach out to them.

**Comment by MadDogDean** [comment]
Yo @blizzz , thanks for the follow up.
Cheers
