### ISSUE TITLE
sidebar popover keeps displaying even though sidebar and text app are closed again

### ISSUE THREAD

**Issue by violoncelloCH** [nextcloud/server#16587]
**To Reproduce**
1. refresh your browser and go to Nextcloud files
2. Open a Nextcloud Text file in the Text app
2. click on the "share" icon in the top bar to open the sidebar by clicking at the bottom of the icon so while the sidebar is opening you're hovering the preview area
3. see a popover appearing with the filename
4. see the popover staying even though you don't hover the preview area any more; it also stays if you close the sidebar or the text app

**Screenshots**
![image](https://user-images.githubusercontent.com/22591354/62005624-48d85c00-b136-11e9-96a8-45048a8ab37b.png)
![image](https://user-images.githubusercontent.com/22591354/62005629-5db4ef80-b136-11e9-9a71-1ee17fc02d5d.png)
![image](https://user-images.githubusercontent.com/22591354/62005632-71f8ec80-b136-11e9-9eb6-8539b26b19ba.png)
after scrolling: 
![image](https://user-images.githubusercontent.com/22591354/62005641-84732600-b136-11e9-9e00-ef368a6f94c0.png)

**Client details:**
 - OS: Ubuntu 19.04
 - Browser: Firefox
 - Version: 68

<details>
<summary>Server details</summary>
**Text app version:** 1.0.1

**Nextcloud version:** 16.0.3

</details>

<details>
<summary>Logs</summary>
#### Browser log
```
Unhandled promise rejection TypeError: "e[n] is undefined"
    r https://nc.violoncello.ch/apps/files_sharing/js/dist/additionalScripts.js?v=3b89b802-37:1
    o https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:230
    H https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:230
    u https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:235
main.js:230:27763
    t https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:230
    exports https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:235
    O https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:230
    exports https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:230
    <anonymous> https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:181
    v https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:181
    y https://nc.violoncello.ch/core/js/dist/main.js?v=3b89b802-37:181
```
</details>

**Comment by skjnldsv** [comment]
Fixed with new sidebar

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
