### ISSUE TITLE
"PHP Parse error:  syntax error" with PHP 5.3.10

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#1659]
### Steps to reproduce
1. Setup nextcloud with php 5.3.10 (shipped by default in Ubuntu Precise)
2. Access /

### Expected behaviour
According to https://github.com/nextcloud/server/blob/9e7824f3edcb498447915a396e93678ddb6f5768/index.php#L28 I should see an error about a too old PHP.

### Actual behaviour
A syntax error is logged:
```
[Fri Oct 07 16:59:24 2016] [error] [client X.X.X.X] PHP Parse error:  syntax error, unexpected '[' in /path/to/nextcloud/server/index.php on line 43, referer: http://server.domain.invalid/
```

I know my PHP is way too old :see_no_evil: but imho the message from `index.php` should be reported to the browser (or it could be removed if it's not working anyway).

**Comment by georgehrke** [comment]
It's supposed to be reported to the browser, but your PHP is even too old to parse the index.php 🙈 
But I think we are able to fix this.
