### ISSUE TITLE
Files still encrypte after decrypt-all

### ISSUE THREAD

**Issue by pierreyves258** [nextcloud/server#16597]
Hi evryone,

I have activateur le default encryption module for local files at the beginning of my NC instance, after that I desactivated the local encryption for new files without turning off encryption for external storage, and evrything was fine.
When I tryed to descativate the encryption module witc occ encryption:decrypt-all, the command ran wihout any issues but some files like .pdf's are still encrypted, impossible to open them on the web interface or the application and some errors show up:
"OC\Encryption\Exceptions\DecryptionFailedException: Can not decrypt this file, probably this is a shared file. Please ask the file owner to reshare the file with you." (even if I logged as owner's account)

If il look at the file manually it begins with 
"HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:HEND"
I tryed running  sudo -u www-data php occ files:scan username1
but still nothing, and now when I run decrypt-all it returns "Imposible to decrypt files for username1."

It seem to use master key, wich is still present in data/files_encryption/OC_DEFAULT_MODULE, and all files_encryption folders in users folders are present too.

How can I decrypt the still encrypted files ? 

Regards

**Comment by ChristophWurst** [comment]
Please use the issue template from https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md

**Comment by ChristophWurst** [comment]
But only if you want to report a bug. For general questions it's better to consult https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md ;)

**Comment by the-sane** [comment]
@ChristophWurst Those are the same link.  Did you mean https://help.nextcloud.com/?  :)

@pierreyves258 I've been researching serverside encryption before deploying it on my instance and, from what I've seen, there are still some issues with the process so it doesn't always work reliably.

Bugs aside, my understanding is that any shared files will only be visible by the owner after encryption or decryption and they will need to be re-shared in order for others to see them again.  If that's not the case for you, then you may have run into a bug and the devs here will need some more details to help.

**Comment by skjnldsv** [comment]
@the-sane I'm not sure I get this then, did you fix your issue?
What is the current status?

**Comment by the-sane** [comment]
@skjnldsv I don't have the OP's issue myself, I was just trying to be helpful  :)

@pierreyves258 did that help fix your problem?
