### ISSUE TITLE
Nexcloud 16 error 

### ISSUE THREAD

**Issue by volga629** [nextcloud/server#16600]
I am not sure if it error or bug.

Not sure

### Steps to reproduce
1.
2.
3.

### Expected behavior
Tell us what should happen

Page right now give 500 error.

### Actual behavior
Tell us what happens instead

### Server configuration
Fedora Server 29

**Operating system**:

**Web server:**

**Database:**

**PHP version:**

7.2

**Nextcloud version:** (see Nextcloud admin page)

16.01

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"OkCjQTwc0BjlG7eTGSCI","level":3,"time":"2019-07-29T15:12:00+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 4 passed to OCA\\Theming\\ThemingDefaults::__construct() must be an instance of OC_Defaults, instance of OC\\Memcache\\Factory given, called in \/usr\/share\/nextcloud\/lib\/private\/Server.php on line 965","Code":0,"Trace":[{"file":"\/usr\/share\/nextcloud\/lib\/private\/Server.php","line":965,"function":"__construct","class":"OCA\\Theming\\ThemingDefaults","type":"->","args":[{"__class__":"OC\\AllConfig"},{"__class__":"OC\\L10N\\L10N"},{"__class__":"OC\\URLGenerator"},{"__class__":"OC\\Memcache\\Factory"},{"__class__":"OCA\\Theming\\Util"},{"__class__":"OCA\\Theming\\ImageManager"},{"__class__":"OC\\App\\AppManager"},{"__class__":"OC\\NavigationManager"}]},{"file":"\/usr\/share\/php\/Pimple\/Container.php","line":118,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/usr\/share\/nextcloud\/lib\/private\/ServerContainer.php","line":125,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["ThemingDefaults"]},{"file":"\/usr\/share\/nextcloud\/lib\/private\/Server.php","line":1885,"function":"query","class":"OC\\ServerContainer","type":"->","args":["ThemingDefaults"]},{"file":"\/usr\/share\/nextcloud\/lib\/private\/Server.php","line":1143,"function":"getThemingDefaults","class":"OC\\Server","type":"->","args":[]},{"file":"\/usr\/share\/php\/Pimple\/Container.php","line":118,"function":"OC\\{closure}","class":"OC\\Server","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/usr\/share\/nextcloud\/lib\/private\/ServerContainer.php","line":125,"function":"offsetGet","class":"Pimple\\Container","type":"->","args":["OCP\\Defaults"]},{"file":"\/usr\/share\/nextcloud\/lib\/private\/legacy\/util.php","line":735,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCP\\Defaults"]},{"file":"\/usr\/share\/nextcloud\/lib\/base.php","line":653,"function":"checkServer","class":"OC_Util","type":"::","args":[{"__class__":"OC\\SystemConfig"}]},{"file":"\/usr\/share\/nextcloud\/lib\/base.php","line":1056,"function":"init","class":"OC","type":"::","args":[]},{"file":"\/usr\/share\/nextcloud\/cron.php","line":41,"args":["\/usr\/share\/nextcloud\/lib\/base.php"],"function":"require_once"}],"File":"\/usr\/share\/nextcloud\/apps\/theming\/lib\/ThemingDefaults.php","Line":58,"CustomMessage":"--"},"userAgent":"--","version":"16.0.1.1"}
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by volga629** [comment]
What information is required to  provide ?

**Comment by j-ed** [comment]
@volga629 This is usually not the Nextcloud support forum, where installation issues are discussed. If you have trouble getting Nextcloud 16 installed, you should first check if the [**Nextcloud help forum**](https://help.nextcloud.com/) provides the relevant information to solve your problem. If you couldn't find a solution there, what is very unlikely, you could ask for help and a solution will be found.

**Comment by volga629** [comment]
Do you think it miss configuration ?


```

[root@canext00 nextcloud]# sudo -u nginx php occ files:scan --all
An unhandled exception has been thrown:
TypeError: Argument 4 passed to OCA\Theming\ThemingDefaults::__construct() must be an instance of OC_Defaults, instance of OC\Memcache\Factory given, called in /usr/share/nextcloud/lib/private/Server.php on line 965 and defined in /usr/share/nextcloud/apps/theming/lib/ThemingDefaults.php:58
Stack trace:
#0 /usr/share/nextcloud/lib/private/Server.php(965): OCA\Theming\ThemingDefaults->__construct(Object(OC\AllConfig), Object(OC\L10N\L10N), Object(OC\URLGenerator), Object(OC\Memcache\Factory), Object(OCA\Theming\Util), Object(OCA\Theming\ImageManager), Object(OC\App\AppManager), Object(OC\NavigationManager))
#1 /usr/share/php/Pimple/Container.php(118): OC\Server->OC\{closure}(Object(OC\Server))
#2 /usr/share/nextcloud/lib/private/ServerContainer.php(125): Pimple\Container->offsetGet('ThemingDefaults')
#3 /usr/share/nextcloud/lib/private/Server.php(1885): OC\ServerContainer->query('ThemingDefaults')
#4 /usr/share/nextcloud/lib/private/Console/Application.php(71): OC\Server->getThemingDefaults()
#5 /usr/share/nextcloud/console.php(94): OC\Console\Application->__construct(Object(OC\AllConfig), Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(OC\AppFramework\Http\Request), Object(OC\Log), Object(OC\MemoryInfo))
#6 /usr/share/nextcloud/occ(11): require_once('/usr/share/next...')

```

**Comment by volga629** [comment]
I opened new topic in forum
