### ISSUE TITLE
Sabre\DAV\Exception\BadRequest: Content-Range on PUT requests are forbidden.

### ISSUE THREAD

**Issue by Zmmfly** [nextcloud/server#16604]
Hi, when i use 'Raidrive' mount to local disk, and upload file, it's will caused this error.

Nextcloud 16.0.3
<details>
<summary>Error Log</summary>
[webdav] Fatal: Sabre\DAV\Exception\BadRequest: Content-Range on PUT requests are forbidden. at <<closure>>

0. <<closure>>
   Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
1. /nextcloud/docroot/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
2. /nextcloud/docroot/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
3. /nextcloud/docroot/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
4. /nextcloud/docroot/apps/dav/appinfo/v1/webdav.php line 80
   Sabre\DAV\Server->exec()
5. /nextcloud/docroot/remote.php line 163
   undefinedundefinedrequire_once("/nextcloud/doc ... p")

PUT /remote.php/webdav/STM32/Keil/ARM.CMSIS-FreeRTOS.10.2.0.pack
from *** by admin at 2019-07-29T11:26:24+00:00
</details>

**Comment by szaimen** [comment]
Thank you for taking the time to report a problem 👍

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
