### ISSUE TITLE
Login Flow for Browser Extensions

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#16603]
I'd like to ask for Nextcloud Login Flow support for web browser extensions in Firefox and Chrome. This way, users can log into their accounts using their regular credentials and optional 2-factor authentication rather than generating one time passwords.

[See this related request](https://github.com/marcelklehr/floccus/issues/297).

It is great how Login Flow simplifies user experience, which is especially important for non-technical users accustomed to inputting credentials for Google Drive and Dropbox related extensions.

[Possible related PR](https://github.com/nextcloud/server/pull/17136)
[Possible related issue](https://github.com/nextcloud/server/issues/17165)

**Comment by szaimen** [comment]
I think it is already possible to do that because https://github.com/floccusaddon/floccus/issues/297 was implemented -> closing.
