### ISSUE TITLE
Ldap multiple DN base Not Working

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#16606]
### Steps to reproduce
1. Enable LDAP
2. Insert server port, user and password
3 Insert Multiple base dn seperated with line return

### Expected behaviour
Inside the attribute configuration you can normaly get all groups from all base dn 
Same problem when i refer multiple filtre to multiples base dn

### Actual behaviour
Only the first base dn groups are showed 
### Server configuration

**Operating system**: Debian 9

**Web server:** Nginx 

**Database:** Mariadb

**PHP version:** fpm 7.3

**Nextcloud version:** 15.0.10

Multiple filter like : 
(&(|(objectclass=person))(|(memberof=CN=XX1_NextCloud,OU=XX1,DC=XXX,DC=XXX)(primaryGroupID=3603)(memberof=CN=XX2_NextCloud,OU=XX2,DC=XXX,DC=XXX,DC=XXX)))

there is a main active directory containing subdomains.

The user used to connect work on all subdomains

Best regards

**Comment by blizzz** [comment]
Oh it does work, really. 

But probably those entries are not directly available, but not also as referrals. We don't support those. There should be hints in the log file about that. In that case it might help to connect to the Global Catalog https://portal.nextcloud.com/article/active-directory-with-multiple-domain-controllers-via-global-catalog-43.html

**Comment by tanguy-opendsi** [comment]
@blizzz Thx for reply.
What do you mean about directly available ? 
If do 1 ldap connexion per subdomain it's work .

**Comment by blizzz** [comment]
Sorry, had a mixup in the sub clause. When the AD does not own the entries, just has references.

**Comment by tanguy-opendsi** [comment]
@blizzz thx for reply.
If the AD not own the entries but if we use only one base DN this i supposed to work ?

**Comment by blizzz** [comment]
Any user base that the AD owns is supposed to work, it does not matter how many.

Please understand, as this seems to be a configuration issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
