### ISSUE TITLE
Federated shares reshared with local users are not accessible

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#16617]
I just encountered the following issue:
- Share a file from userA1@instanceA to userB1@instanceB using federated sharing
- as user B1@instanceB reshare the file to userB2 on instanceB as a user share
- the file is added
- downloading the file fails, as it is mounted as a SharedStorage which tries to access the file by path which doesn't exist

@schiessle @rullzer How should we handle this properly? Should we make sure the local share is working properly or should we instead try to initiate another remote share to the original file on instanceA?

**Comment by rullzer** [comment]
I vote for a two stage solution

1. Fix it how it works now

But in the long run we should indeed have a mechanism to initiate a new remote share.

**Comment by skjnldsv** [comment]
Still relevant? Please update labels.

**Comment by juliushaertl** [comment]
Yes, need to find some time to look into https://github.com/nextcloud/server/pull/16632 again for this.
