### ISSUE TITLE
Split devices and session-overview add logintype

### ISSUE THREAD

**Issue by markushub** [nextcloud/server#16614]
1st of all nextcloud ist great. 
devices and sessions is a weak overview of the least sessions.
Additional I miss an overview of all devices that are configured with this nextcloud user.
The kind of password security (username/password or app-password)

Why do I need this.
Real overview of the devices/apps are using my nextcloud user.
Overview how big is the effort is I change user password.
In my view it's an important security information.

**Comment by ChristophWurst** [comment]
Please use either of the two templates you can choose from https://github.com/nextcloud/server/issues/new/choose so we get a clear overview of what you're missing :)

**Comment by markushub** [comment]
Suggest an idea for this project

Is your feature request related to a problem? 
The problem is to find all my devices which connected with this account and in which way.
e.g. to get an overview how big is the effort if I would/have to change my nextcloud password.

Describe the solution you'd like A clear and concise description of what you want to happen.
There is a common (mixed) list of devices/session under Settings/personal like a log of last connection.
Please separate this in 2 parts. A logging part add an additional part as device overview. Where each device is only once listed with devicename, and the logiontype (username/password or app-password). With the possibility to activate/deactivate/delete/rename/set an app password the device.

Describe alternatives you've considered A clear and concise description of any alternative solutions or features you've considered.
Scroll down the complete history of the last device connection can give me a overview of my device but not of the logintype.
Alternatively write down each new device manuel to a list with the logging type.

Additional context Add any other context or screenshots about the feature request here.

**Comment by kesselb** [comment]
Just curious: How many items do you have in the list?

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/70805988-90e0de00-1dba-11ea-8173-4f8a4cd2398d.png)

Like this?

**Comment by markushub** [comment]
Your image shows the place what I mean.

![ncsession](https://user-images.githubusercontent.com/53473792/70817157-4880ea80-1dd1-11ea-8bc3-6bf5bc041402.jpg)
I have far in excess of 100 entries.
A nextcloud account is used with some devices like pc, notebook, smartphone, tablet ...
synced with several apps like davdroid, passwords, notes, phonetrack, talk...

e.g. active cal sync with 10 calendars over davdroid creates a lot of entrys.

I'm on nc version 17.0.1

**Comment by kesselb** [comment]
Oh. I've added a "Type" column to my list (like in the screenshot). Would that help? ;)

**Comment by markushub** [comment]
yeah adding the type as column and splitting device into a own table where each app/device is only once present would help extreme. 
@kesselb thank you for supporting this idea and your screenshot

**Comment by szaimen** [comment]
cc @nextcloud/designers is this feature feasible?

**Comment by tcitworld** [comment]
So basically the `Type` column would be whether the token expires or not?

**Comment by juliushaertl** [comment]
Showing the type might make sense though these days most of the apps (including DAVx5) would get an app password through the login flow anyways, so not sure how relevant that is.

**Comment by markushub** [comment]
Thank you for your additional comments. In the meantime it happends a lot inside nextcloud. 
Yes please add a column with information about the logintype. In view of 2FA it could also be helpfull to see where a 2nd factor is neccessary.
