### ISSUE TITLE
系统接入cas问题，客户端使用wen'ti

### ISSUE THREAD

**Issue by qw3672939** [nextcloud/server#16621]
您好，我咨询一下，nextcloud接入cas后，客户端登录认证是否能cas认证登录。

**Comment by georgehrke** [comment]
@qw3672939 Can you please create bug reports and feature requests in english? 
Thx!

**Comment by qw3672939** [comment]
Hello, I would like to consult, after the nextcloud accesses the CAS, the client login authentication can log in through CAS authentication.
I am testing the use of owncloud when accessing the CAS can only be accessed through the web, the client APP can not be used, so I would like to ask, does nextcloud support access to the CAS after the client login?

**Comment by j-ed** [comment]
An initial description of the "CAS user and group backend" app can be found [here](https://apps.nextcloud.com/apps/user_cas). A more detailed description can be found on the [main project page](https://github.com/felixrupp/user_cas) of the project or in the [administrator guide](https://github.com/felixrupp/user_cas/blob/master/README.md).
