### ISSUE TITLE
Moving shared folder to external storage does not keep shared permissions

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#16634]
### Steps to reproduce
1. User 1 create Folder 1 and share it with user 2 and 3
2. Move Folder 1 via GUI to external Storage
3. Folder being moved, but not shared with user 2 and 3 anymore.
3. Event page of Folder 1 is "clean" starting with "you move this folder to external"

### Expected behaviour
As in "local" NC installation, shared folder being moved and keeps shared setups.

### Actual behaviour
User need to share folder again with users if it was moved to external Storage

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache2 2.4.39

**Database:** MariaDB

**PHP version:** 7.0.33

**Nextcloud version:** 15.0.10

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Official Website

**Comment by cju77** [comment]
Same here! Please help!

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by GAS85** [comment]
Just tested it in 20.0.10 and it works fine. Thanks you!
