### ISSUE TITLE
External Storage - "modified" date bug

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#16640]
### Steps to reproduce
1. Add an external storage to another nextcloud server, it will be visible in the "Files" list
2. Notice the "Modified" date, let's say it's something like "2 minutes ago"
3. Open the external storage, then go back. Do not edit anything - You will notice the "modified" date has been changed to "seconds ago" as if modifications were made.

### Expected behaviour
The "modified" data should not be changed if you merely open the storage. - change it only when modifications were done inside that storage.

### Actual behaviour
Modification data updates after opening the storage and not really editing anything inside it

**Comment by deusoz** [comment]
I just noticed same thing, except some say minutes ago, and some say thousands of years in the future LOL
![image](https://user-images.githubusercontent.com/3331362/69907047-e1753600-13cd-11ea-9c13-bc4eaf9c4d82.png)

**Comment by pjft** [comment]
Same here. NextCloud 19.0.2, upgraded from NC 18.

This seems to be a regression from 18. The "Modified Date" is shown as the date it was scanned at, and not the actual filesystem modification date now. Has there been a change?

**Comment by pjft** [comment]
-- Apologies for double posting, just noticed that this only happens for the _folders_ modified date. The actual files stay with their original date, as expected. 

@pilsnerbeer @deusoz let me know if your issue is the same, otherwise I'll create a separate one instead of hijacking yours, which may be a different one altogether.

**Comment by szaimen** [comment]
> The "Modified Date" is shown as the date it was scanned at, and not the actual filesystem modification date now.

I can reproduce this on NC21.0.2.
Was it ever differently, though?

**Comment by meonkeys** [comment]
Any relation to https://github.com/nextcloud/text/issues/3543 ?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by pjft** [comment]
25.0.2 seems fixed. Just scanned old files, it immediately updated the date to the expected date.

**Comment by szaimen** [comment]
Great! Thanks for verifying! :)
