### ISSUE TITLE
Ensure text remains visible during webfont load

### ISSUE THREAD

**Issue by Nutomic** [nextcloud/server#16655]
**Is your feature request related to a problem? Please describe.**
Google Pagespeed Insights reports the following performance problem:

```
Ensure text remains visible during webfont load

Leverage the font-display CSS feature to ensure text is user-visible while webfonts are loading.
```

**Describe the solution you'd like**

[Information about this optimization is available here](https://developers.google.com/web/updates/2016/02/font-display)

**Additional context**
[Here is a link to the analysis](https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fecloud.global%2F&tab=mobile) on Nextcloud 15, and I get the same issue with Nextcloud 16.

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/16055
