### ISSUE TITLE
The "view shares" screen is counter intuitive and could lead to unintentional data deletion.

### ISSUE THREAD

**Issue by KimTheFirst** [nextcloud/server#16660]
Let's say that I have just installed nextcloud and shared 3 or 4 files from my uploaded collection. If I follow the workflow from the Nextcloud homepage of clicking on "Files" and then clicking on "Shares" - I am presented with a nice, neat, uniform list of file shares: 

![nc1](https://user-images.githubusercontent.com/14975046/62865901-ed01fb80-bd0f-11e9-8824-3811fedc3d17.PNG)

Particularly with only shared folders displayed on this screen, it appears to me as though all functions on this page pertain directly to the file shares. Therefore it seems as though the "delete" function here relates only to the share, and clicking it is going to delete the share.

In this case the delete button actually deletes the file, which is probably not what I want to do. I think that most users deleting an object from this screen will be thinking "delete the share", so in my opinion this UI is counter-intuitive and will probably lead to accidental data destruction.

I can foresee a case in which someone has accidentally emailed their boss an inflammatory document / image / etc, and just wants to unshare it - they go to the share screen in a panic and then just hit "delete" - boom!

**Comment by jospoortvliet** [comment]
@nextcloud/designers something to think about perhaps? I understand what the user means, perhaps when it is removing the share, the 'delete' text should say 'unshare' instead. I know that 'deleting' a share means unsharing it but that is of course only when it is a share that came from somebody else, so that is confusing...

**Comment by skjnldsv** [comment]
Good question. I can understand the confusion, but we're still listing files.
We could change the delete string to something like `delete file` ?
cc @jancborchardt

**Comment by jancborchardt** [comment]
> We could change the delete string to something like `Delete file` ?

That seems like a good, minimal change! Also then of course `Delete folder` in case it’s a folder.

**Comment by skjnldsv** [comment]
see https://github.com/nextcloud/server/pull/16741
