### ISSUE TITLE
Welcome Email Header Logo

### ISSUE THREAD

**Issue by sdismukes** [nextcloud/server#16669]
### Steps to reproduce
1.Resend Welcome Email
2.
3.

### Expected behaviour
Default welcome email with logo displayed.

### Actual behaviour
Email received, but logo not present.

### Server configuration

**Operating system: Ubuntu 18.04

**Web server: Apache 2.4.29

**Database: MariaDB 10.3

**PHP version: 7.3.7

**Nextcloud version: 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install: Yes

**Where did you install Nextcloud from: download.nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by wiswedel** [comment]
Cannot reproduce this. Do you have a custom logo via Theming enabled?

**Comment by sdismukes** [comment]
I did, but even when I reset everything to default, the NextCloud logo does
not come through.

**Comment by wiswedel** [comment]
Is the Nextcloud server reachable for the email recipient (and not behind a VPN or so)?
The logo in the HTML email is only included from its actual address. 
You may check the email's source code for the following passage:

```<img class="logo float-center" src=```

**Comment by sthag** [comment]
I'm also having this issue.
The URL of the missing image within the email is: https://<domain.tld>/index.php/apps/theming/image/logo?useSvg=0&v=9

If I browse the URL I get the file `logo`, which is the correct PNG image file.
I can see this on the apache access log when opening the mail in the clients:

```
<ip> - - [06/Apr/2020:23:22:45 +0200] "GET /index.php/apps/theming/image/logo?useSvg=0&v=9 HTTP/1.1" 302 1271 "<request url>" "<user-agent>"
immediately followed by many of:
<ip> - - [06/Apr/2020:23:22:45 +0200] "GET /index.php/apps/theming/image/logo?useSvg=0&v=9 HTTP/1.1" 302 1133 "-" "<user-agent>"
```

I also have a custom logo set via theming option.

I tried Mailbird desktop client and roundcube web client to request/display the mail.
