### ISSUE TITLE
Error deleting multiple files from Deleted files with NextCloud 16.0.3.0

### ISSUE THREAD

**Issue by antonol68** [nextcloud/server#16665]
### Steps to reproduce
1. Go to Files and click 'Deleted files'
2. Select multiple files
3. Click on the triple dots 'Actions'
4. Click 'Delete'

### Expected behaviour
Selected files shall be deleted

### Actual behaviour
Only one file is deleted the others return an error 'Error while removing files from trashbin'

### Server configuration
**Operating system:** FreeBSD 11.2-RELEASE-p10 FreeBSD 11.2-RELEASE-p10 #0 r349200M: Wed Jun 19 20:26:53 CEST 2019     root@dev.xigmanas.com:/usr/obj/xigmanas/usr/src/sys/XIGMANAS-amd64 amd64

**Webserver:** lighttpd/1.4.53 (cgi-fcgi)

**Database:** mysql 8.0.15

**PHP version:** 7.3.4
Modules loaded: Core, date, libxml, pcre, Reflection, SPL, hash, session, cgi-fcgi, standard, apcu, ctype, curl, dom, mbstring, fileinfo, filter, gd, gettext, mysqlnd, iconv, imagick, intl, json, ldap, exif, openssl, pcntl, PDO, posix, SimpleXML, sqlite3, tokenizer, xml, xmlwriter, zip, zlib, pdo_mysql, pdo_sqlite, Phar, redis, xmlreader, xmlrpc, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**  Updated

**Where did you install Nextcloud from:** Internet

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - previewgenerator: 2.1.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.2.20",
        "acloud68.asuscomm.com",
        "acloud68.dynip.sapo.pt"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/192.168.2.20",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "log_rotate_size": 10485760,
    "mysql.utf8mb4": true,
    "preview_max_x": 2048,
    "preview_max_y": 2048,
    "app_install_overwrite": [
        "calendar"
    ]
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** Debian 4.19.37-4~bpo9+1 (2019-06-19) x86_64 GNU/Linux

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
2019-08-05 12:43:01: (server.c.1464) server started (lighttpd/1.4.53) 
2019-08-05 19:33:07: (mod_openssl.c.1746) SSL: 1 error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request 
2019-08-05 19:33:07: (mod_openssl.c.1746) SSL: 1 error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request 
2019-08-05 19:33:07: (mod_openssl.c.1746) SSL: 1 error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request 
2019-08-05 19:59:00: (mod_openssl.c.1746) SSL: 1 error:1407609C:SSL routines:SSL23_GET_CLIENT_HELLO:http request 
2019-08-05 23:32:30: (mod_openssl.c.1746) SSL: 1 error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol 
2019-08-05 23:38:53: (mod_openssl.c.1746) SSL: 1 error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol 
2019-08-05 23:51:40: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:41: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:42: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:43: (mod_openssl.c.1645) SSL: renegotiation initiated by client, killing connection 
2019-08-05 23:51:44: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:52: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:54: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:55: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:58: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:51:59: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:52:00: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:52:00: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:52:02: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-05 23:52:04: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-06 00:41:55: (server.c.2059) server stopped by UID = 0 PID = 4086 
2019-08-06 00:41:55: (server.c.1464) server started (lighttpd/1.4.53) 
2019-08-06 02:52:29: (mod_openssl.c.1746) SSL: 1 error:1408A10B:SSL routines:ssl3_get_client_hello:wrong version number 
2019-08-06 02:52:48: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher 
2019-08-06 02:53:31: (mod_openssl.c.1746) SSL: 1 error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"gNcZAO87BNh3hgYTaR2C","level":4,"time":"2019-08-06T09:13:44+00:00","remoteAddr":"194.117.40.96","user":"Antonio","app":"webdav","method":"DELETE","url":"\/remote.php\/dav\/trashbin\/Antonio\/trash\/file011.bin.d1565079637","message":{"Exception":"OCP\\Lock\\LockedException","Message":"\"files\/702f21b2cea2b34eeb6646d6f6cec48c\" is locked, existing lock on file: exclusive","Code":0,"Trace":[{"file":"\/usr\/local\/www\/nextcloud\/lib\/private\/Files\/Storage\/Common.php","line":715,"function":"acquireLock","class":"OC\\Lock\\MemcacheLockingProvider","type":"->","args":["files\/702f21b2cea2b34eeb6646d6f6cec48c",2]},{"file":"\/usr\/local\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":593,"function":"acquireLock","class":"OC\\Files\\Storage\\Common","type":"->","args":["scanner::files_trashbin\/versions",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/usr\/local\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":593,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["scanner::files_trashbin\/versions",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/usr\/local\/www\/nextcloud\/lib\/private\/Files\/Cache\/Scanner.php","line":331,"function":"acquireLock","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":["scanner::files_trashbin\/versions",2,{"__class__":"OC\\Lock\\MemcacheLockingProvider"}]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/files_trashbin\/lib\/Trashbin.php","line":868,"function":"scan","class":"OC\\Files\\Cache\\Scanner","type":"->","args":["files_trashbin\/versions"]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/files_trashbin\/lib\/Trashbin.php","line":614,"function":"getVersionsFromTrash","class":"OCA\\Files_Trashbin\\Trashbin","type":"::","args":["\/file011.bin",1565079637,"Antonio"]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/files_trashbin\/lib\/Trashbin.php","line":579,"function":"deleteVersions","class":"OCA\\Files_Trashbin\\Trashbin","type":"::","args":[{"__class__":"OC\\Files\\View"},"\/file011.bin.d1565079637","\/file011.bin",1565079637,"Antonio"]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/files_trashbin\/lib\/Trash\/LegacyTrashBackend.php","line":90,"function":"delete","class":"OCA\\Files_Trashbin\\Trashbin","type":"::","args":["\/file011.bin","Antonio",1565079637]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/files_trashbin\/lib\/Trash\/TrashManager.php","line":69,"function":"removeItem","class":"OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend","type":"->","args":[{"__class__":"OCA\\Files_Trashbin\\Trash\\TrashItem"}]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/files_trashbin\/lib\/Sabre\/AbstractTrash.php","line":83,"function":"removeItem","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->","args":[{"__class__":"OCA\\Files_Trashbin\\Trash\\TrashItem"}]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Tree.php","line":179,"function":"delete","class":"OCA\\Files_Trashbin\\Sabre\\AbstractTrash","type":"->","args":[]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":287,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["trashbin\/Antonio\/trash\/file011.bin.d1565079637"]},{"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/acloud68.dynip.sapo.pt\/remote.php\/dav\/trashbin\/Antonio\/trash\/file011.bin.d1565079637","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpDelete"],[{"absoluteUrl":"https:\/\/acloud68.dynip.sapo.pt\/remote.php\/dav\/trashbin\/Antonio\/trash\/file011.bin.d1565079637","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:DELETE",[{"absoluteUrl":"https:\/\/acloud68.dynip.sapo.pt\/remote.php\/dav\/trashbin\/Antonio\/trash\/file011.bin.d1565079637","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/usr\/local\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/acloud68.dynip.sapo.pt\/remote.php\/dav\/trashbin\/Antonio\/trash\/file011.bin.d1565079637","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/dav\/lib\/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/usr\/local\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"\/usr\/local\/www\/nextcloud\/remote.php","line":163,"args":["\/usr\/local\/www\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php"],"function":"require_once"}],"File":"\/usr\/local\/www\/nextcloud\/lib\/private\/Lock\/MemcacheLockingProvider.php","Line":80,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"16.0.3.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by the-sane** [comment]
Possibly a duplicate of https://github.com/nextcloud/server/issues/16491

**Comment by antonol68** [comment]
For now with version 17.0.1 is working correctly, tank you.

**Comment by danieltuzes** [comment]
I have the same issue with 19.0.3

**Comment by kitzler-walli** [comment]
This issue persists in 20.0.5

**Comment by oceanaeon** [comment]
This issue persists in 22.2.3

**Comment by 4abhinavjain** [comment]
Facing the same issue on 22.2.3 as well.
