### ISSUE TITLE
Technical/unnecessary errors on federated sharing

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1667]
@schiessle I just helped a friend set up Nextcloud. Roughly 10 minutes after installation I wanted to share a file with him via federated sharing. Typing in his whole address brought up this error notification:

```
cURL error 51: SSL: no alternative certificate subject name matches target host name 'cloud.example.com'
```
- [ ] this should be more understandable. Like: »**cloud.example.com** could not be reached. Please try again later.« Right @schiessle?

Then refreshing and trying it again gave me an error notification up top like:

```
Error sharing because it’s already shared with this user
```

Even though the user didn’t show up as an entry in the list. But it was apparently shared.
- [ ] When shared, the federated user should show up directly in the list as feedback. And there should be a tooltip instead of a notification saying »Already shared with user@example.com«

And now when I try to share the file with the same user it’s already shared with, I get a tooltip:

```
No users or groups found for user@cloud.example.com
```
- [ ] Instead it should show the same tooltip as said above: »Already shared with user@example.com«

**Comment by rullzer** [comment]
> ```
cURL error 51: SSL: no alternative certificate subject name matches target host name 'cloud.example.com'
```
- [ ] this should be more understandable. Like: »**cloud.example.com** could not be reached. Please try again later.« Right @schiessle?

Well. no because it could be reached but the certificate is invalid. I mean we could print that. But saying it could not be reached is simply false. But a more understandable error message is a good idea.

>Then refreshing and trying it again gave me an error notification up top like:
```
Error sharing because it’s already shared with this user
```
Even though the user didn’t show up as an entry in the list. But it was apparently shared.
>
>- [ ] When shared, the federated user should show up directly in the list as feedback. And there should be a tooltip instead of a notification saying »Already shared with user@example.com«

Not showing up sounds like a bug. Tooltip also better indeed.

**Comment by jancborchardt** [comment]
@rullzer it should be a more explanatory message, but the question also is if the certificate of my friends’ server being invalid is even relevant to me. Because sharing was apparently successful after all.

**Comment by rullzer** [comment]
@jancborchardt yes that part I agree on.

Also we need better error handling there. because sharing was not succesfull. We could not talk securely to your friends server. So we error out half way. When that happens we should cleanup things. CC: @schiessle

**Comment by jancborchardt** [comment]
Aah ok so that's why all the errors happen. The user is shown in the list but sharing was actually not successful.
