### ISSUE TITLE
Failed installation 404

### ISSUE THREAD

**Issue by mikygee** [nextcloud/server#16688]
Version: 16.0.3

Hello,
I followed the nginx configuration to install nextcloud but it doesn't work
Just after the mysql tables have been populated the page displays without the css

After checking the html  source code i see
href="/css/core/b583-9111-server.css?v=db81cddf52fdb3c8ca1e4c859e214124-00314feb-0"
However the system path is /core/cssand not /css/core
I also checked in /nextcloud/data/appdata_ocg854ytyej0/css/core and I can see this file b583-9111-server.css

So the file is not properly located although I followed
https://docs.nextcloud.com/server/16/admin_manual/installation/nginx.html

    # Adding the cache control header for js and css files
    # Make sure it is BELOW the PHP block
    location ~* .(?:css|js|woff|svg|gif|map)$ {
        try_files                 $uri /index.php$request_uri;
        #add_header                Cache-Control "public, max-age=15778463";
        #add_header                X-Content-Type-Options nosniff;
        #add_header                X-XSS-Protection "1; mode=block";
        #add_header                X-Robots-Tag none;
        #add_header                X-Download-Options noopen;
        #add_header                X-Permitted-Cross-Domain-Policies none;
        # Optional: Don't log access to assets
        access_log                off;
    }

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by mikygee** [comment]
After a fresh install it doesn't work, how is this not a bug ?

Did
# cp /var/www/htdocs/nextcloud/data/appdata_ocee1vaiac6l/js/core/merged-template-prepend.js /var/www/htdocs/nextcloud/js/core/
# cp /var/www/htdocs/nextcloud/data/appdata_ocee1vaiac6l/js/core/merged-login.js /var/www/htdocs/nextcloud/js/core/

To be able to log in

**Comment by kesselb** [comment]
Is nextcloud installed to `mydomain.com/nextcloud` or `mydomain.com`?

**Comment by mark99i** [comment]
I copied the nginx configuration file from help.nextcloud.com and it really doesn't work as written
