### ISSUE TITLE
Exception thrown while sending notification for federated share

### ISSUE THREAD

**Issue by taradiddles** [nextcloud/server#16685]
### Steps to reproduce
- on server a.example.com, share a folder to user `xyz@b.example.com/nc`
- on server b.example.com, accept the share (click "accept" in the notification popup)

[edit: in reality servers `a` and `b` have different domain names, if that matters]

### Expected behaviour
No exception is thrown in the log files.

### Actual behaviour
Exceptions are thrown in both servers' logs.

Also (not sure if it's relevant to this issue - if it isn't I'll file separate issues):
- address books don't seem to be exchanged - I have to type `xyz@b.example.com/nc` manually each time I test share a folder. I'd expect there would be some auto completion. For info all configuration check boxes are ticked under "federate cloud sharing" on both servers; both servers are also trusted - ie. shown with a green dot (fwiw it took some time - days ? - from them to go from yellow to green).
- [EDIT - likely not relevant to issue here - see #16701]
   * ~~the folder size of the shared folder on server b.example.com is not shown ("pending") if the shared folder is large (eg. tested with a 20+ GB folder). It is is properly shown for smaller folders.~~
   * ~~I can't see the content of large shared folders (eg. same 20+ GB test folder as above) on server b.example.com  - I'd get a "Storage is temporarily not available" error some time after clicking on the folder. Smaller folders work OK though.~~

Notes:
- AFAICT both servers are identically configured and running the same version of nextcloud.
- no exceptions nor relevant info are present in the log files of both servers for any of the issues above. 
- [EDIT - likely not relevant to issue here - see #16701] ~~the servers are geographically far away - one is in Asia, the other in Europe (both in Linode data centers), with approx. 200ms RTT. I noticed weird behavior when the link wasn't optimal and trying to use the server located in Asia from Europe, even if the server could be reached (eg. I'd get timeouts and would then be blacklisted when trying to log in nextcloud, while I could log into other services running on that server without problem).~~

## Server configuration detail

**Operating system:** Linux 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi) [added: apache 2.4.34 from RH software collections]

**Database:** mysql 5.5.60

**PHP version:** 

7.2.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, zip, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, Zend OPcache

**Nextcloud version:** 16.0.3 - 16.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** regularly updated (all the way back from 11.x.y and owncloud)

**Where did you install Nextcloud from:** Signed package from nextcloud's web site

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - bruteforcesettings: 1.4.0
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.13.0
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.0.4
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.0.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "b.example.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.3.0",
    "overwrite.cli.url": "https:\/\/b.example.com\/nc",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logtimezone": "UTC",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "asset-pipeline.enabled": true,
    "enable_avatars": false,
    "session_lifetime": 14400,
    "remember_login_cookie_lifetime": 172800,
    "trashbin_retention_obligation": "auto,2",
    "maintenance": false,
    "loglevel": 2,
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "log_rotate_size": 10485760,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "preview_max_x": 1024,
    "preview_max_y": 1024
}
```
</details>

**Are you using external storage, if yes which one:** no external storage

**Are you using encryption:**  no

**Are you using an external user-backend, if yes which one:** no external user backend

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** Fedora 30

## Logs

<details><summary>Web server error log</summary>

```
[nothing relevant in the logs]
```
</details>

<details><summary>Nextcloud log</summary>

```
on server a.example.com (sharing the folder):

{"reqId":"kCKZtgx7nn8ZXhKHs9Zd","level":3,"time":"2019-08-07T15:46:23+00:00","remoteAddr":"a.b.c.d","user":"--","app
":"index","method":"POST","url":"\/nc\/\/index.php\/ocm\/notifications","message":{"Exception":"Exception","Message":"The requested uri(\/nc\/index.php\/ocm\/notifications) cannot be processed by the script '\/nc\/\/index.php')","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/base.php","line":918,"function":"getRawPathInfo","class":"OC\\AppFramework\\Http\\Request","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Request.php","Line":780,"CustomMessage":"--"},"userAgent":"GuzzleHttp\/6.3.3 curl\/7.29.0 PHP\/7.2.10","version":"16.0.3.0"}


on server b.example.com (user xyz is accepting the share):

{"reqId":"IA05C3qXBUL2k7FrS8lj","level":3,"time":"2019-08-07T15:46:23+00:00","remoteAddr":"1.2.3.4","user":"xyz","app":"no app in context","method":"POST","url":"\/nc\/ocs\/v2.php\/apps\/files_sharing\/api\/v1\/remote_shares\/pending\/21","message":"error while sending notification for federated share: Server error: `POST https:\/\/a.example.com\/nc\/\/index.php\/ocm\/notifications` resulted in a `500 Internal Server Error` response:\n<!DOCTYPE html>\n<html class=\"ng-csp\" data-placeholder-focus=\"false\" lang=\"en\" data-locale=\"en\" >\n\t<head\n data-requesttok (truncated...)\n","userAgent":"Mozilla\/5.0 (X11; Fedora; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.3.0"}

```
</details>

<details><summary>Browser log</summary>

[nothing shown while accepting the share on server b.example.com ; the log below is when refreshing the files page]

Content Security Policy: Ignoring ‘x-frame-options’ because of ‘frame-ancestors’ directive.
nsLoginManager: searchLogins: `formSubmitURL` or `httpRealm` is recommended LoginManager.jsm:392:13
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
OCA.Viewer initialized viewer.js:154:262
New search handler registered search.js:67:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 main.js:750:58
The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:750:58
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 8 main.js:750:58
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 6 main.js:750:58
</details>

**Comment by kesselb** [comment]
Still an issue? Looks like the request going to a wrong address. Probably the protocol is wrong.
