### ISSUE TITLE
lastSeen / lastLogin

### ISSUE THREAD

**Issue by markuman** [nextcloud/server#16697]
I wonder where the value comes from?

* https://github.com/nextcloud/server/blob/5382eeccb053ecf17bb8f7aacd57ae3cc4518d27/lib/private/DB/QueryBuilder/QueryBuilder.php#L834
* https://github.com/nextcloud/server/blob/3308c4092269b39c5038fc61075a61302a28a79c/lib/private/User/User.php#L179

Furthermore I don't fine any colums this a value like '%seen%' or '%login%'.  
Is it determined by last activity?

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/3308c4092269b39c5038fc61075a61302a28a79c/lib/private/User/User.php#L93

https://github.com/nextcloud/server/blob/2cc411862912b2e890c0d500b5ba1ce13a6013b6/lib/private/AllConfig.php#L310-L311

https://github.com/nextcloud/server/blob/2cc411862912b2e890c0d500b5ba1ce13a6013b6/lib/private/AllConfig.php#L410-L411

`preferences` is the table your are looking for. There is a configkey `lastlogin` for the appid `login` and the given `userid`.

**Comment by markuman** [comment]
Wow, that's not intuitive :) Thx!
