### ISSUE TITLE
	GuzzleHttp\Exception\ClientException: Client error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `400 Bad Request` response:

### ISSUE THREAD

**Issue by CHazz** [nextcloud/server#16694]
*Operating system**:
ubuntu 16.04

**Web server:**
nginx
**Database:**
madriadb
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
16.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated drom oldel nextcloud

GuzzleHttp\Exception\ClientException: Client error: `POST https://push-notifications.nextcloud.com/notifications` resulted in a `400 Bad Request` response:
/var/www/html/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 66:

GuzzleHttp\Exception\RequestException::create(GuzzleHttp\Psr7\Request {}, "*** sensiti ... *")

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 203:

GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 156:

GuzzleHttp\Promise\Promise::callHandler(1, "*** sensiti ... *", [ GuzzleHttp ... l])

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/TaskQueue.php - line 47:

GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 246:

GuzzleHttp\Promise\TaskQueue->run(true)

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 223:

GuzzleHttp\Promise\Promise->invokeWaitFn()

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 267:

GuzzleHttp\Promise\Promise->waitIfPending()

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 225:

GuzzleHttp\Promise\Promise->invokeWaitList()

/var/www/html/apps/files_external_gdrive/vendor/guzzlehttp/promises/src/Promise.php - line 62:

GuzzleHttp\Promise\Promise->waitIfPending()

/var/www/html/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131:

GuzzleHttp\Promise\Promise->wait()

/var/www/html/lib/private/Http/Client/Client.php - line 231:

GuzzleHttp\Client->request("post", "https://pus ... s", { verify: "/ ... e})

/var/www/html/apps/notifications/lib/Push.php - line 143:

OC\Http\Client\Client->post("https://pus ... s", { form_param ... }})

/var/www/html/apps/notifications/lib/App.php - line 50:

OCA\Notifications\Push->pushToDevice(83, OC\Notification\Notification {})

/var/www/html/lib/private/Notification/Manager.php - line 208:

OCA\Notifications\App->notify(OC\Notification\Notification {})

/var/www/html/apps/updatenotification/lib/Notification/BackgroundJob.php - line 203:

OC\Notification\Manager->notify(OC\Notification\Notification {})

/var/www/html/apps/updatenotification/lib/Notification/BackgroundJob.php - line 165:

OCA\UpdateNotification\Notification\BackgroundJob->createNotifications("mail", "0.15.2")

/var/www/html/apps/updatenotification/lib/Notification/BackgroundJob.php - line 87:

OCA\UpdateNotification\Notification\BackgroundJob->checkAppUpdates()

/var/www/html/lib/private/BackgroundJob/Job.php - line 61:

OCA\UpdateNotification\Notification\BackgroundJob->run(null)

/var/www/html/lib/private/BackgroundJob/TimedJob.php - line 55:

OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

/var/www/html/cron.php - line 123:

OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

**Comment by kesselb** [comment]
I'm not sure if related but the "wrong" guzzle library is used. This should be fixed with a newer release of https://github.com/NastuzziSamy/files_external_gdrive (afaik there are no update via the app store yet).
