### ISSUE TITLE
Feature request: Select multiple files in one go

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#167]
At the moment in the webui I seem to have to click on each file I want to select one by one.
I thought holding down shift or trying a click + drag will select multiple but it does not.

Can this be added please?

**Comment by MorrisJobke** [comment]
This works here in Chrome. Selecting a file and then holding shift and clicking another file will select all files in between. Is this what you want?

**Comment by jasonbayton** [comment]
It certainly is, and I'm sure oc had it, but on 3 devices running chrome (Windows, ChromeOS and Linux) it doesn't do it. I just selected 100 images by hand!

It's a fresh install of NC with no missing dependencies except for the cache option.

**Comment by MorrisJobke** [comment]
I checked again:

- current master (Nextcloud 10) works ✅ 
- current stable9 (Nextcloud 9) doesn't work :x:
- v9.0.2 (ownCloud 9.0.2 - latest release) doesn't work :x:
- v9.0.0 (ownCloud 9.0.0) doesn't work :x:

Sadly I can't find the fixing commit anymore. I will close this as already fixed in the upcoming Nextcloud 10.

Thanks anyways for the feature request.

**Comment by Zegorax** [comment]
@MorrisJobke Is this implemented in current version of Nextcloud ? I tried with Safari, Chrome, Brave and Firefox and Maj + click doesn't work.

**Comment by ant0nwax** [comment]
> @MorrisJobke Is this implemented in current version of Nextcloud ? I tried with Safari, Chrome, Brave and Firefox and Maj + click doesn't work.
> 
> EDIT : It is in fact working. Just in a counter-intuitive way. You have to check (using the checkbox) the first file, and then Maj-Click on the second file but NOT on the checkbox and it works.

@MorrisJobke i think this is worth a Feature Request, why do i need to read an issue tracker about Nextcloud in order understand how multi select works... I vote for a feature request, please could be someone be so kind and name the URL where to report the feature?
