### ISSUE TITLE
Ask for confirmation when someone wants to share a folder with you

### ISSUE THREAD

**Issue by Ezwen** [nextcloud/server#16703]
**Is your feature request related to a problem? Please describe.**

We have two users *A* and *B* on the same Nextcloud server. *A* creates a new folder, puts files in there, and shares the folder with *B*.
*B*, later, discovers a new folder in her storage, but decides she does not want these files at all: not only she would prefer to not have these files automatically downloaded on her computer (through the desktop client), but having new folders appearing in her storage messes with her folder organization. She would have preferred to "accept" the share offered by *A*, instead of having it automatically accepted.

**Describe the solution you'd like**
As a nextcloud user, a solution would be to have in the settings a checkbox box "Ask for confirmation when another user wants to share something with you.".

Then, if ticked, when a share is created with the user, the user receives an email and/or a notification on the web app, and must accept the share before it is added to her storage.

**Describe alternatives you've considered**
I have no other alternative in mind, but there must be some for sure, as I am not a UX expert at all :)

**Comment by taradiddles** [comment]
While not exactly what you're looking for, the [share_folder](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#all-other-configuration-options) config option may help: that way the users won't have their root folder filled with unwanted stuff and they can "untick" the configured folder in the nextcloud client to avoid auto-download. Your users would then move folders shared with them to a "declined" folder if they don't want the share, or to an "OK" folder (or whatever other folder(s) suit their needs).

**Comment by Ezwen** [comment]
Indeed, thanks! That's definitely a good way to avoid being "cluttered" and/or surprised by shared folders at the root of the storage. I'll ask my users what they think about that. Yet I still believe that what I describe above would be useful to many.

**Comment by taradiddles** [comment]
(note that the "share_folder" config option won't move existing shared folders, it applies only to newly shared folders)

> Yet I still believe that what I describe above would be useful to many

I agree - my reply was meant as a temporary workaround. That said an issue I have with accept/reject notifications is people clicking by mistake on "reject" (it already happened to some of my users when using federated shares). There should definitely be a way to undo the reject action and/or have a way to "recover" dismissed folders later on without bothering the sender(s) to unshare/re-share (which is annoying when the recipient is a group).

**Comment by jospoortvliet** [comment]
We have this accept/reject workflow planned/scheduled for a future release. On top, once we have the Virtual Drive ready in the desktop client, files wouldn't get downloaded automatically. And last but not least, I personally would love to be able to designate a share_folder as user but that's a different thing :D

**Comment by Ezwen** [comment]
> We have this accept/reject workflow planned/scheduled for a future release. 

Fantastic :)

> On top, once we have the Virtual Drive ready in the desktop client, files wouldn't get downloaded automatically. 

I was not aware of this planned feature, this sounds neat.

> And last but not least, I personally would love to be able to designate a share_folder as user but that's a different thing :D
> 
> See #4471 4471 for the user-chosen incoming share_folder

I've added my +1 there in case that helps to make it a case for the feature :)

and thank you both for your answers!

**Comment by rullzer** [comment]
This is basically done
