### ISSUE TITLE
Tooltips remain present

### ISSUE THREAD

**Issue by elysium3** [nextcloud/server#16705]
### Steps to reproduce
1. Share a folder
2. Check the "protect by password" box
3. Type 'toto' as password
4. A tootlip appears and remains present even if I change page

I see an error in the javascript console : "Deprecated call $.tooltip('destroy') has been deprecated and should be removed"

**Nextcloud version:** 16.0.3

**Comment by kesselb** [comment]
cc @nextcloud/javascript

**Comment by skjnldsv** [comment]
Yep, weird glitches :thinking: 
Ii will be fixed in 18 anyway  :)

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
