### ISSUE TITLE
Support more libsmbclient options

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#1670]
### Steps to reproduce
1. Configure external storage to connect to Samba servers
### Expected behaviour

NC should connect
### Actual behaviour

Red square and no useful feedback for one of the servers.

I initially thought this had something to do with encryption, but I've enabled the same settings on one of the servers which could connect and that didn't break things.

It might be difficult to support an option field as everything would have to be parsed and converted into smbclient commands, so maybe the most important ones should be added to an advanced config panel.
### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7

**Nextcloud version:** (see Nextcloud admin page) 10

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** snap

---

@icewind1991

**Comment by MorrisJobke** [comment]
We improved a lot for SMB mounts in the past 1,5 year. Also there is now a smb test app to check for potential problems: https://apps.nextcloud.com/apps/smb_test

Let's close this for now and work on specific issues we notice.
