### ISSUE TITLE
Allow application in WebDav access

### ISSUE THREAD

**Issue by JakubOnderka** [nextcloud/server#16709]
**Is your feature request related to a problem? Please describe.**

Hello, I am trying to create a new application (plugin) for Nextcloud, that will generate a preview for Office documents. Currently, it is possible to generate previews for Office documents with installed LibreOffice or OpenOffice on the same machine, but I want to use OnlyOffice.

I am using OnlyOffice integration, so OnlyOffice is already running on that machine, it also generates previews that will look the same as when I open the document in OnlyOffice. I also think it is safer because OnlyOffice runs in a container (sandbox).

OnlyOffice provides [Conversion API](https://api.onlyoffice.com/editors/conversionapi) that I use in my app. I [registered new provider in PreviewManager](https://github.com/nextcloud/server/blob/v16.0.3/lib/private/PreviewManager.php#L106) and everything works well, previews are generated and showed in Nextcloud interface, but not in the main folder view, just in Recommendentations or in Last activity view.

I think the problem is that main folder view takes the information about files from WebDav interface and in WebDav are loaded only specific applications (see https://github.com/nextcloud/server/blob/v16.0.3/remote.php#L146-L148). 

So then my application is not loaded, the provider is not registered and `has-preview` property in WebDav is false (see https://github.com/nextcloud/server/blob/v16.0.3/apps/dav/lib/Connector/Sabre/FilesPlugin.php#L355-L357).

**Describe the solution you'd like**

Allow some plugins to be loaded also in WebDav access by some parameter in `info.xml` file. It can be useful also for example [sentry application](https://github.com/ChristophWurst/nextcloud_sentry) that can catch exceptions also in WebDav code or for other preview generator plugins.

**Comment by szaimen** [comment]
I think onlyoffice has now the ability to create previews -> closing.
