### ISSUE TITLE
Add support for socks5 proxy

### ISSUE THREAD

**Issue by balki** [nextcloud/server#16700]
**Is your feature request related to a problem? Please describe.**
Supporting socks5 proxy will allow to use tor. This helps running nextcloud as a hidden service. Nextcloud news makes requests to arbitrary sites for fetching feed. Using a socks proxy will help improve privacy.

**Describe the solution you'd like**
Add a config option 'socks5proxy' similar to 'proxy'. 
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#proxy-configurations

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by balki** [comment]
Actually it looks like it is supported. I just had to set with proper full url `socks5://proxy.server:port`. 
I wish the documentation mentioned this explicitly. Feel free to close this issue if I am too dumb to get this from the documentation.

**Comment by rullzer** [comment]
Please submit a PR to the documentation extending it :)

**Comment by cs224** [comment]
Sorry for posting to this old issue, but I also would like to use a socks5 proxy for the Nextcloud news server side application.

@balki : did you simply set the global proxy configuration for the overall Nextcloud server or is there a way to configure a socks5 proxy for the Nextcloud news app separately? I could not find any info in the documentation: https://nextcloud.github.io/news/

Thanks!

**Comment by balki** [comment]
@cs224 I set the global proxy for nextcloud. I don't use nextcloud now, so not sure if there is a setting for news app alone.
