### ISSUE TITLE
integrity check: check write access to temporary folder

### ISSUE THREAD

**Issue by stefan-schilling** [nextcloud/server#16719]
**Is your feature request related to a problem? Please describe.**
I was wondering, why Nextcloud did not create previews for the images I had uploaded. Turns out: Nextcloud (aka. the Apache)
had no write access to the temporary folder configured by default (/tmp/something). This is due this is a shared hosted environment.
Since I had not checked all configuration options, I had not noticed this might be a problem.

**Describe the solution you'd like**
Include a check in the integrity check, if Nextcloud has write access to the temporary folder.

**Describe alternatives you've considered**
naaa ... who reads a manual? ;)

**Additional context**
None

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/0eebff152a177dd59ed8773df26f1679f8a88e90/lib/private/TempManager.php#L237

There is already a check if the temp directory is writable. Do you see a warning like "Temporary directory {dir} is not present or writable" in your logs? I'm not sure how the preview generator uses the temp directory.

cc @rullzer

**Comment by stefan-schilling** [comment]
Hello Daniel,

correct, such a message showed up in the logs. But it took me some time to even notice I had a problem. 
It would be nice, if the general configuration check (which talks e.g. about missing ".well-known/..." entries could include this check. So the administrator would be notified by Nextcloud, rather than having to wait for that problem to occur and then check the log file.

Thanks.
Stefan

**Comment by bpcurse** [comment]
I just stumbled upon this as well. Wanted to file an issue but then I found this one.
My private Nextcloud (17.0.2) was logging the "Temporary directory {dir} is not present or writable" error multiple times per second after a disk migration, but the overview in the GUI just said all is fine.

Displaying such misconfiguration errors in the admin overview is crucial.
While Nextcloud is even bothering users with app recommendations as notifications I'd rather like to be informed about important errors by notification instead.

And layman users won't even take a look at the logs.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by stefan-schilling** [comment]
Hello Szaimen,

yeah, problem persists. I just changed the config.php to direct the tmp-directory to non-accessible dir /tmp. The Configuration & Security scanner did not pick this problem up.

Thanks.
Stefan

**Comment by stefan-schilling** [comment]
no change made - removing stale label

@szaimen is the info given sufficient?

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is it feasible to introduce such a check in the admin overview?

**Comment by stefan-schilling** [comment]
waiting for response from @nextcloud/server-triage

**Comment by artonge** [comment]
Hello @stefan-schilling,

This seems like a good first issue. Would you like to give it a try ?

I think the related files are:

- [Backend] https://github.com/nextcloud/server/blob/master/apps/settings/lib/Controller/CheckSetupController.php#L721
- [Frontend] https://github.com/nextcloud/server/blob/master/core/js/setupchecks.js#L178

**Comment by stefan-schilling** [comment]
Hello @artonge 

question: what exactly do I need to to? Copy those files over? Since they havent been changed for a couple of weeks, I think, my current installation 20.0.11 (another installation: 21.0.3) should have those already - right?
Otherwise, just copy them?

Then I would need to add another directory somewhere and change the setup to use that directory, which Apache does not have write access to - correct?

Thanks.

**Comment by artonge** [comment]
Hello @stefan-schilling,

No, my suggestion was that you try to make a pull request with the tmp folder check added into the configuration check.

The linked files are the files you will probably need to edit for that.

**Comment by stefan-schilling** [comment]
Hey there,
I just tried to create a pull request with that change. But since I'm not a PHP developer, I failed creating the tests for CheckSetupController.php. 
I'm also not really able to create the pull request for nextcloud's repo - I created a pull request for my master instead (*grrrr*).

I attached the patch file - since Github does not accept .patch-files, I had to rename it to .patch.csv - remove the .csv appendix.
[Issue_16719__CheckSetupController_php_now_checks_configured_temporary_directory_for_existe.patch.csv](https://github.com/nextcloud/server/files/7155211/Issue_16719__CheckSetupController_php_now_checks_configured_temporary_directory_for_existe.patch.csv)

Please comment, if this helps you out.

Thanks.
Stefan

**Comment by stefan-schilling** [comment]
@szaimen 
Update: I just noticed, I can create a pull request using Github's UI (tried it using PhpStorm), comparing my fork with nextcloud's original code. 
If you're interested, I can create such a pull request, but I'm still lacking the test for CheckSetupController.php.

Thanks.
Stefan

**Comment by artonge** [comment]
> @szaimen
> Update: I just noticed, I can create a pull request using Github's UI (tried it using PhpStorm), comparing my fork with nextcloud's original code.
> If you're interested, I can create such a pull request, but I'm still lacking the test for CheckSetupController.php.
> 
> Thanks.
> Stefan

Please do, we'll see what is missing then :)

**Comment by artonge** [comment]
Just saw that the PR was merged!
Thanks a lot @stefan-schilling for taking care of this issue from reporting to PR!
