### ISSUE TITLE
Aggregation of shared folder permissions - Possible? Feasible? Wanted?

### ISSUE THREAD

**Issue by kvoit** [nextcloud/server#1671]
I am using Nextcloud to share pictures with my family aside from a lot of other stuff. A common situation is that I give people who participated in an event write access to the photo folder - to help tag and this sort of stuff -, and a more or less fixed group of people read-only access. (Some also with technical competence issues, so I would prefer keeping it like that for the safety of the data.)

Right now, people will see two shares in that case, one read-only from the group and one writable. This is quite annoying, especially for the technically semi-competent people. 

Would it be possible to aggregate permissions derived from different access paths (personal, groups) and just provide one share with maximal permissions?

Right now, I essentially had to kick my wife out of the family group because she almost always gets double shares else.

**Comment by MorrisJobke** [comment]
@rullzer @schiessle Isn't this already implemented? I thought that we already group shares and the recipient gets the combined permissions (or the higher one)

**Comment by MorrisJobke** [comment]
I created a user `abc` who is member of the group `test`.

Then I shared a folder `test` with the group `test` in read-only mode and added `abc` to the share with read-write permissions. When `abc` logs in there is only one folder `test` where the proper write permissions are granted:

<img width="358" alt="bildschirmfoto 2016-10-10 um 11 22 59" src="https://cloud.githubusercontent.com/assets/245432/19231770/1c543930-8edc-11e6-8464-62e09a3750d8.png">


@kvoit Which version of Nextcloud are you using? How does it look, when there are multiple shares  received for one element?

**Comment by kvoit** [comment]
That is strange. My wife had a few
Folder (rw)
Folder (2) (ro)
When I removed her from the group, Folder (2) when away. 

But now, I cannot reproduce the behavior. She is back in the group and still has just one folder. I am on Nextcloud 10.0.0 BTW.
Seems to be solved, sorry to have bothered you. Awesome reaction time to feature requests :D

**Comment by rullzer** [comment]
This *should* (tm) be fixed.
Maybe we missed a corner case somewhere but without preciece steps to reproduce finding that is going to be hard.

**Comment by MorrisJobke** [comment]
> Maybe we missed a corner case somewhere but without preciece steps to reproduce finding that is going to be hard.

Correct. I will close this.
