### ISSUE TITLE
Mount point of external storage

### ISSUE THREAD

**Issue by archont00** [nextcloud/server#16720]
**Is your feature request related to a problem? Please describe.**
When admin sets up external storage, he defines the mount point for the nextcloud users (which actually may be a full path like `External storage/Project Santa Fe`.
For any eligible user (defined by admin and there is no opt-out), such a path is created and the user cannot move the external folder mount point to anywhere else in the hierarchy.

**Describe the solution you'd like**
The user should be given a choice where to mount the external share.

**Describe alternatives you've considered**
Options are:
* Allow the user to change the mount point in user's settings (now, the available shares are non-editable).
* Allow the user to move the mount point anywhere else within Files app.

**Additional context**
A workaround is:
* Define external storage as admin and set only a single user for that storage - e.g. admin as well.
* In admin's Files, share the mount point `Project Santa Fe` with the eligible users.
* For the users, the new share will appear in the top-level folder. However, the user may move that shared folder to anywhere in the folder hierarchy.
EDITE: unfortunately, this workaround is good only for read-only access (event that folder is shared with "can change" permission, the user can only create files, but not edit nor delete them).

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
