### ISSUE TITLE
Nextcloud App Password Not Accepted in Thunderbird

### ISSUE THREAD

**Issue by gretaneal** [nextcloud/server#16738]
Steps to reproduce:

In the Nextcloud web client at cloud.example.com

Settings > Security > "Thunderbird" --> Create new app password

Gives a password. I enter this in Thunderbird and I get:

"Login to server mail.example.com with username greta@example.com failed."

Tried in a VM with a fresh install of Thunderbird, same issue.

Used an app password in Nextcloud Dev for Android successfully.

Also previously to trying the app password I have been using my regular password in Thunderbird without any problem.

I used this tutorial to set up my server 123qwe.com

Operating system: ARMBIAN 5.83 Debian GNU/Linux 9 (stretch)

Web server: apache2

Database: postgresql

PHP version: 7.0.33-0+deb9u3

Nextcloud version: 15.0.9

Updated from an older Nextcloud/ownCloud or fresh install: Fresh

I looked in logs and there's nothing relevant to this.

**Comment by rullzer** [comment]
Nextcloud is not a mail server. So thunderbird can't talk properly to it.
You could use app passwords to connect to your contacts or calendar.
