### ISSUE TITLE
How to get rid of additional line (last edited files) in file app.

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/server#16734]
*Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.3 on Debian 10 with PHP 7.3.

How can i get rid of the new addition line with "last edited files"? See red circle.
It appeared after upgrade fom NC15 to 16.

It is annoyingly and takes a lot of space on small (laptop) display.
I can not find any configuration item to remove this. 

Please advice how to remove it.

Thanks.
![mc16filesaddline](https://user-images.githubusercontent.com/47995430/62955973-4cd0d300-bdf2-11e9-8487-776baabed83e.png)

**Comment by kesselb** [comment]
Look at https://github.com/nextcloud/server/issues/15565

**Comment by pm-pm** [comment]
That's crazy. :-/ 
"So you should ask your brother where your sister hid the books."

Thank you for your advice. :-)
