### ISSUE TITLE
Reset password form for new users has an action that switches to http

### ISSUE THREAD

**Issue by mihailstoynov** [nextcloud/server#16730]
## The issue
When a new user is created a link is sent with a url to setup the initial password for that user.

The form inside this page looks like this:
`<form action="http://domain.com/lostpassword/set/lllHFuikfdAAAAAAu8Df/username" id="reset-password" method="post">
`
The problem is that the action contains the scheme and the domain name. 
For me that means that the scheme is changed from https to http (nginx in front) and the form cannot be submitted. I don't want to rewrite the urls.

## Other forms don't have this issue

I checked other forms.
Login form:
`<form method="post" name="login">`
Forgot password form:
`<form method="post" name="login" action="lostpassword/email">`

They don't exibit this isuue.

## Possible solution

Can we make the change password form be like:
`<form action="/lostpassword/set/lllHFuikfdu8Df/username" id="reset-password" method="post">`
or
`<form action="../../../set/lllHFuikfdu8Df/username" id="reset-password" method="post">`

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/4dea089ed36304a1b8c92608a88a057302562471/core/Controller/LostController.php#L172

@juliushaertl do you know why we use the absolute url here?

> For me that means that the scheme is changed from https to http (nginx in front) and the form cannot be submitted. I don't want to rewrite the urls.

Nextcloud can obtain the correct scheme and host from your reverse proxy: https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html. Absolute urls are correct then.

**Comment by rullzer** [comment]
We could probably us relative routes. But the issue here is that probably indeed a reverse proxy.

Look into 'overwriteprotocol' and friends.
