### ISSUE TITLE
stable16: upgrade failes with "UnexpectedValueException: The files of the app "activity" were not correctly replaced before running the update

### ISSUE THREAD

**Issue by kyrofa** [nextcloud/server#16754]
Using the snap on Ubuntu 18.04, testing out the upgrade process from Nextcloud 15 to the head of stable16, and the upgrade fails with the above error. I've traced it back to `getAppPath` returning false, but I'm not sure what's causing it yet. Whatever it is, it's new, because the daily build from yesterday doesn't have this problem. Still investigating, but thought I'd log the bug in case other folks can pinpoint the issue faster.

**Comment by kyrofa** [comment]
Ah, this may just be a difference between how the daily builds are published in https://download.nextcloud.com/server/daily/ and the apps that are included in this repo, this issue is probably invalid.

Is the process for generating the daily tarballs documented so that I can duplicate it?

**Comment by balodja** [comment]
The same issue here. Even moving the apps don't help. Is there a possibility to workaround that somehow?

**Comment by szaimen** [comment]
Looks to me like the tarball was just built incompletely. Please reopen if you can still reproduce this error. Thanks!

**Comment by DoDelivery** [comment]
We are getting this error when trying to upgrade to the latest v24.0.5 release
