### ISSUE TITLE
File list scroll bar spanning whole page and triggered too early

### ISSUE THREAD

**Issue by jarednjames** [nextcloud/server#16757]
Just updated to 16.0.4. Debian 10, PHP 7.3, Chrome browser.

Two issues with the scroll bar.

Firstly, when the file list length triggers the need for a scroll bar, it spans the whole screen (including the header bar):
![image](https://user-images.githubusercontent.com/665111/63153891-50897300-c007-11e9-9b4e-6cca54786468.png)

The tfoot element also appears to be oversized, resulting in the scroll bar being required prior to the list length exceeding available room:
![image](https://user-images.githubusercontent.com/665111/63153856-38195880-c007-11e9-99f9-441685482e42.png)

**Comment by tony4212** [comment]
This also is an issue in NC 17 both chrome and firefox. The scroll bar also stays when using pdf viewer. 
![Capture](https://user-images.githubusercontent.com/41548037/67986024-839fd380-fc00-11e9-8dd6-58e581b7da37.PNG)

**Comment by szaimen** [comment]
> The tfoot element also appears to be oversized

This by design to make file uploads by dragging into this section easier.

---

> This also is an issue in NC 17 both chrome and firefox. The scroll bar also stays when using pdf viewer.

I cannot reproduce this on NC21.0.2

---

> Firstly, when the file list length triggers the need for a scroll bar, it spans the whole screen (including the header bar):

@nextcloud/designer Is this something that was made intentionally or does it need to be fixed?
