### ISSUE TITLE
set_time_limit(): Cannot set max execution time limit due to system policy at [...]

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/server#16752]
### Steps to reproduce
1. Rent a webspace using a hoster where set_time_limit() is disabled to be changed and set to 50 using the php ini file (for example one.com)
2. Install Nextcloud using the Web installer
3. Get tremendous amounts of errors dumped in the log file

### Expected behaviour
Nextcloud should notice that the setting cannot be changed and move on or atleast not dump this message into the error file

### Actual behaviour
The Error file gets spammed multiple times a second with the message 

> set_time_limit(): Cannot set max execution time limit due to system policy at [...]

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** mysqlnd 5.0.12-dev - 20150407

**PHP version:** 7.3.8

**Nextcloud version:** Nextcloud 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://nextcloud.com/

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- setup-nextcloud.php

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [setup-nextcloud.php] => Array
                        (
                            [expected] => 
                            [current] => dd6c6a96aaf61c57538551689ca2cbbf131c20bcb935221a3dbec1eb409329ef801582f97501d78550ee32dbfbe30a3d606d3e1dfb04a79ffdf327ddc765c428
                        )

                )

        )

)

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Can't easily dump this due to web installation but can be provided if needed
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '-',
  'passwordsalt' => '-',
  'secret' => '-',
  'trusted_domains' => 
  array (
    0 => 'next.*.*',
  ),
  'datadirectory' => '*/httpd.www/next/data',
  'dbtype' => 'mysql',
  'version' => '16.0.3.0',
  'overwrite.cli.url' => 'https://next.*.*',
  'dbname' => '*',
  'dbhost' => '*.*.mysql',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '*',
  'dbpassword' => '*',
  'installed' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauth' => 1,
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '*.*',
  'mail_smtphost' => '*.*.*',
  'mail_smtpport' => '587',
  'mail_from_address' => 'next',
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'next@*.*',
  'mail_smtppassword' => '-',
  'maintenance' => false,
  'updater.secret' => '-',
);

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
-
```
</details>

### Client configuration
**Browser:** Firefox, Chrome

**Operating system:** Win 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Can't access it atm
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Sensitive Information, domain and User Path removed,
Around 150 MB of those Messages:
```
{"reqId":"-","level":3,"time":"2019-08-15T19:37:16+00:00","remoteAddr":"-","user":"-","app":"PHP","method":"GET","url":"\/index.php\/apps\/logreader\/poll?lastReqId=-","message":"set_time_limit(): Cannot set max execution time limit due to system policy at *httpd.www\/next\/lib\/base.php#615","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"16.0.3.0"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) I tried opening the console in Firefox but it started to lag instantly and i did not want to lose this ticket so i will provide it later if needed

```
</details>

**Comment by JDillmann** [comment]
Got the same Problem with one.com! Have no idea how to fix it...

**Comment by kesselb** [comment]
```
<?php

var_dump(ini_get('disable_functions'));
```

Mind to run this script? 

> Got the same Problem with one.com! Have no idea how to fix it...

@JDillmann Please edit your post and add a error message from the log

@ThorgerJ are you also using one.com?

> Nextcloud should notice that the setting cannot be changed and move on or atleast not dump this message into the error file

https://github.com/nextcloud/server/blob/5898e87e0f69ed4a3be73cd044c19d7c4872b639/lib/base.php#L614-L616

There is a check if set_time_limit is disabled.

**Comment by JDillmann** [comment]
Fixed it by adding
`Header set Strict-Transport-Security 'max-age=31536000' env=HTTPS`
to htaccess!

**Comment by ThorgerJ** [comment]
I will try the htaccess fix. Can you maybe explain furthermore why this works? @JDillmann 

@kesselb i dont know why one.com makes such problems with nextcloud but ive run the script:
`string(100) "disk_total_space, diskfreespace, exec, system, popen, proc_open, proc_nice, shell_exec, passthru, dl" `

**Comment by kesselb** [comment]
Did you ask one.com support about that? I'm checked the php-src and have no idea how to trigger this kind of warning. I found some reports that this happens if php safe_mode is enabled but the php safe_mode is gone for long. 

As long term goal we should remove these set_time_limit (and most of the ini_set) calls and add a check for a acceptable php configuration.

**Comment by ThorgerJ** [comment]
They insisted it was a nextcloud problem but i can contact them with this issue again.

**Comment by kesselb** [comment]
```
Index: lib/private/Log/ErrorHandler.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Log/ErrorHandler.php	(revision 1a7310f4b34a6665ced59b6e1d2a0598243462d9)
+++ lib/private/Log/ErrorHandler.php	(date 1567886322566)
@@ -83,7 +83,7 @@
 
 	//Recoverable errors handler
 	public static function onError($number, $message, $file, $line) {
-		if (error_reporting() === 0) {
+		if (error_reporting() === 0 || strpos($message, 'set_time_limit()') !== false) {
 			return;
 		}
 		$msg = $message . ' at ' . $file . '#' . $line;
```

We could modify the error handler like this. Every message with "set_time_limit" is ignored then. I still think that one.com patched php to limit max_execution_time or set_time_limit. Nextcloud needs some of the functions listed in `disable_functions`. I guess one.com is not the best place to run nextcloud :disappointed:

**Comment by ThorgerJ** [comment]
I contacted the one.com support but it seems like they are unwilling to get into it. All answers (Chat and Email) so far refer to the issue that set_time_limit() cant be changed. They seem to ignore that other functions as you mentioned are needed as well. It seems very unlikely that server policys of one.com will be changed in the future or that this issue even has been forwarded.

I contacted the one.com support but it seems like they are unwilling to get into it. All answers (Chat and Email) so far refer to the issue that set_time_limit() cant be changed. They seem to ignore that other functions as you mentioned are needed as well. It seems very unlikely that server policys of one.com will be changed in the future or that this issue even has been forwarded.

> [...]We have tried to open the link you have provided and it seems that you are referring to the max execution time that needs to be changed on one of the domains here. If that is correct, then kindly take note that it is not possible to change max execution time on our servers due to server limitations. We have a constant number of it which is set to 50 at the moment.
> 
> If you have any questions or need any help at all, please do not hesitate to contact us again. We will be happy to help you[...]

and

> [...] I understand that but due to server limitations this can no longer be changed. [...]

I will try @JDillmann htaccess fix later on

@kesselb im not a fan of one.com in general. I think the best way to handle this issue is to for now disable the notification as you proposed and later on implement the check for acceptable php configuration.

I think a lot of support and issues could be resolved if in the future there are more strict checks on where nextcloud can run and where it cant. This might limit some hosters to run Nextcloud but enhances the user experience.

**Comment by kesselb** [comment]
Hmm. If changing the max_execution_time is not allowed they might add set_time_limit to the disable_functions.

> It is important to remember that the standard PHP error handler is completely bypassed for the error types specified by error_types unless the callback function returns FALSE. error_reporting() settings will have no effect and your error handler will be called regardless - however you are still able to read the current value of error_reporting and act appropriately. Of particular note is that this value will be 0 if the statement that caused the error was prepended by the @ error-control operator. 

As https://www.php.net/manual/en/function.set-error-handler.php describes. I think this logic is missing for the nextcloud ErrorHandler or this might be intended.

cc @rullzer @ChristophWurst

**Comment by zone31** [comment]
I have the same provider (one.com) and also had the log spamming issue. I simply put the set_time_limit() in a comment. 
I also tried the header set solution:
`Header set Strict-Transport-Security 'max-age=31536000' env=HTTPS` 
but it did not work.

And adding to that, i get undefined errors that i suspect are because of one.com throttling the connections. It happens when uploading multiple files. First it uploads ~20 files per second, after 10 min then 1 per second, an then it halts after ~15 min.
If i initially index more than ~40000 files, it will not even get to the uploading stage, and halt in the
"Checking for changes in local xxxxx"

I suspect this is one.com's fault? 
@ThorgerJ @JDillmann Is this something you also have problems with?

**Comment by ThorgerJ** [comment]
I havent looked into that issue yet as i usually dont upload many files at once and rather small ones. But that might be one.coms fault too.
