### ISSUE TITLE
Update 16.0.3 -> 16.0.4 failed cause of .rnd file check due updater 

### ISSUE THREAD

**Issue by Shorty365** [nextcloud/server#16759]
Hello,

It may sound if I'am whining about something little but during  the last updates of Nextcloud complains about the .rnd file.
There are already many complaints form other users and none of them have resulted in a real solution. Users have to manually delete the .rnd file and the updater is happy. Why can't the updater delete or just ignore this file since it has nothing to do with the working of NextCloud. Thus file is automatically recreated when needed, as far as I can tell it's created on user-logon.
For the average user/administrator it is a little annoyance  to first loging on the server and manually delete the .rnd-file.

### Steps to reproduce
1. Start the updater from withinNextCloud
2. Updater complains about .rnd-file
3.

### Expected behaviour
Updater deletes the .rnd-file or doesn't complain about it.

### Actual behaviour
Updater complains about the .rnd-file and holds the update. The .rnd-file must be manually deleted after which the update can be retried. Updates runs smoothly after deletion of the .rnd-file.
Tell us what happens instead

### Server configuration

**Operating system**: Ubuntu 18.04 (all updates applied)

**Web server:** Apache 2.4.29

**Database:** MySQL

**PHP version:** 7.2.19

**Nextcloud version:** (see Nextcloud admin page) 16.0.4 (after update)

**Updated from an older Nextcloud/ownCloud or fresh install:** update form 16.0.3

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Nils160988** [comment]
This is fixed with #16492, but only for Nextcloud 17...
Maybe backport the fix? @MorrisJobke

**Comment by kesselb** [comment]
> This is fixed with #16492, but only for Nextcloud 17...

Not exactly. It excludes the .rnd files from the integrity check. This one is about the updater https://github.com/nextcloud/updater/pull/236 and backported to Nextcloud 16 but i don't know how the updater is updated ;)

**Comment by rullzer** [comment]
Well the updater only gets updated on update.
So the update to 16.0.5 should no longer complain :wink:

**Comment by Shorty365** [comment]
Great, Thanks!

Op 19-08-19 om 15:01 schreef Roeland Jago Douma:
