### ISSUE TITLE
ALTER TABLE Error when upgrading from 16.0.3 to 16.0.4

### ISSUE THREAD

**Issue by greenorca** [nextcloud/server#16750]
Update to 16.0.4

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

running Nextcloud (since 2 or 3 years) on an Ubuntu 18.04.3 LTS on odroid XU4

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Please check the [other issues with this error](https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+Specified+key+was+too+long%3B+max+key+length+is+767+bytes+) for a solution.
