### ISSUE TITLE
Nextcloud 16.0.4 - 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by rbesland** [nextcloud/server#16751]
### Steps to reproduce
1. Update from 16.0.3 to 16.0.4 using mariadb

### Actual behaviour
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE
 utf8mb4_bin;':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Update fail

### Server configuration

**Operating system**:
CentOs 7

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5.60

**PHP version:**
PHP 7.2.10

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.3

**Comment by greenorca** [comment]
Same Problem here, the solution of altering mysql_config works: https://github.com/nextcloud/server/issues/10535

**Comment by rbesland** [comment]
Ok it works for me too. Thanks
