### ISSUE TITLE
Provide a user to view a specific group in LDAP group

### ISSUE THREAD

**Issue by jseong309** [nextcloud/server#16769]
Nextcloud : 16.0.3
OS: Ubuntu 18.04.3
Nginx

Is it possible to give a normal user access to view a specific LDAP group, along with the list of users in that group on Nextcloud web interface?

As an admin I can view all the LDAP groups/users but when logged in to a normal user that option is not there.

**Comment by blizzz** [comment]
make her group admin, i expect this should work

**Comment by szaimen** [comment]
@jseong309 As this is more of a question, please ask your question at https://help.nextcloud.com if you still don't have an answer. Thanks!
