### ISSUE TITLE
Please make pretty URLs to the default

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#16764]
**Is your feature request related to a problem? Please describe.**
I think pretty URLS should be the standard for nextcloud, because it is nicer and prettier and also more userfriendly: you do not have to see index.php, which could be confusing for non-technical users when it is part of the URL. 

**Describe the solution you'd like**
Please make pretty URLs to the default configuration.

**Describe alternatives you've considered**
An option to opt-out via config.php sounds great.

**Additional context**
Especially for Nextcloud Snap it is important to have it as default.

**Comment by kesselb** [comment]
Would you mind to use the [feature request](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md) template?

**Comment by szaimen** [comment]
Thank you for your response.
I added the feature request template to the issue description.
And BTW: An option to opt-out via config.php sounds great!

**Comment by kesselb** [comment]
> Especially for Nextcloud Snap it is important to have it as default.

Would you mind to explain why it's important especially for snap to enable it by default? I guess the maintainer of nextcloud snap could decide to enable it by default if they want (but i might be wrong).

**Comment by kesselb** [comment]
https://github.com/nextcloud/nextcloud-snap/issues/412 pretty urls are not enabled for nextcloud-snap because it's not enabled by default and `.htaccess` is not writeable.

**Comment by szaimen** [comment]
Yes I know, but if it was the default, then the only missing part would be making `.htacces` writeable.
And there have been first tests enabling that.

**Comment by sndrr** [comment]
You can host nextcloud on Nginx too, and then .htaccess only will not work. Rewriting is possible, but will need a different setup.

@szaimen did you take this into account?

**Comment by szaimen** [comment]
Seems like this is not feasible.
