### ISSUE TITLE
Sharing setting for share visibility

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#16760]
In early version only the owner and the person who shared a file saw with whom the file was shared. This was changed in one of the last releases due to a lot of requests.

### Example 1

user1 shared a file with user2 and user3.

**Result:**

* user1 sees that file is shared with user2 and user3
* user2 sees *not* that the file is also shared with user3
* user3 sees *not* that the file is also shared with user2

## Example 2

user1 shared a file with user2 and user3. User3 reshares the file with user4.

**Result:**

* user1 sees that file is shared with user2, user3 and user4
* user2 sees *not* that the file is also shared with user3 and user4
* user3 sees *not* that the file is also shared with user2 but sees that the file is shared with user4 (because he re-shared it)

## Today's behavior

every user sees all the other users with whom the file was shared.

## desired behavior?

It is hard to say what's the desired behavior.  We changed it because many users asked us to change it. But for privacy reasons you can also come up with many use cases where you don't want to expose all the other users who have access to a file.

Therefore I think we should have a config switch to decide if all recipients should be exposed or not.

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!
