### ISSUE TITLE
NC17Beta1: falsley "all apps have an update"

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#16771]
![image](https://user-images.githubusercontent.com/5836855/63207668-6449dd80-c0ca-11e9-9a87-0da4f356ed53.png)

Updater says that all apps are ready to update to NC17.
For example Talk and News do not have a stable NC17 release yet.

@nextcloud/server-triage

**Comment by nickvergessen** [comment]
Does that also happen when you are on 16.0.4?

**Comment by tobiasKaminsky** [comment]
Unfortunately yes. 

![image](https://user-images.githubusercontent.com/5836855/63345076-38d92400-c352-11e9-9a1d-1ae277a1e901.png)
