### ISSUE TITLE
How to build/package nc server

### ISSUE THREAD

**Issue by grizzly-monkey** [nextcloud/server#16773]
Hello 
We have done some code changes  and want to package the code from git as its done 
``` 
nextcloud.tar.bz2 \ "https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2"; \
"https://download.nextcloud.com/server/releases/nextcloud-${NEXTCLOUD_VERSION}.tar.bz2.asc"; \
```

so that we can build docker images of those  bzip pacakges
could not find the documentation or script which build these bzip pacakges can someone please give some pointers how to package from source like done and pushed here https://download.nextcloud.com/server/releases/

**Comment by kesselb** [comment]
Similar to https://github.com/nextcloud/server/issues/3582

**Comment by grizzly-monkey** [comment]
@kesselb Thanks for your reply Have already scanned those repos and scripts all of them build from the released bzip package I was looking on how to build those bzips or tars from git source.

**Comment by kesselb** [comment]
> I was looking on how to build those bzips or tars from git source.

I don't know :disappointed: I would go this way: Extract your changes into patch files and write a script that downloads the bzip, apply your patches and build the docker image.

**Comment by grizzly-monkey** [comment]
Any pointers would help greatly

**Comment by kesselb** [comment]
Closed as per https://help.nextcloud.com/t/build-bzip-and-package-from-git/58341
