### ISSUE TITLE
Nextcloud Security Scan "NOT on latest patch level", but it is

### ISSUE THREAD

**Issue by maxileith** [nextcloud/server#16800]
Hello,

Unfortunately, the Nextcloud Security Scan says that my Nextcloud server is not on the latest version (16.0.0.9). He is actually up to date (16.0.4).

![Anmerkung 2019-08-20 024443](https://user-images.githubusercontent.com/44269066/63308771-7eff9a80-c2f4-11e9-923b-23549229243f.png)

![Anmerkung 2019-08-20 024406](https://user-images.githubusercontent.com/44269066/63308772-7eff9a80-c2f4-11e9-9a64-e334381bdaeb.png)

There are two domains on the server. Only for one domain does the test say that the server is not up-to-date.

OS: Debian 10
Nextcloud: 16.0.4, Channel: Stable
CPU: 1 Core
RAM: 1GB
HDD: 750GB
Webserver: Apache 2.4

I hope someone can help me.

many Greetings
Maximilian Leith

**Comment by JSoko** [comment]
That's not a bug, it's a feauture ;-)

You should retrigger a scan, wait 5 Minutes and than go back to teh secrurety-scan. 
The result you've posted is from Mai:
![grafik](https://user-images.githubusercontent.com/5583290/63323211-7ecbc300-c325-11e9-9d2b-c36844bb601c.png)

**Comment by ib54003** [comment]
Not fixed.

![Unbenannt](https://user-images.githubusercontent.com/6258536/109139534-ea34f300-775b-11eb-8431-0238a3ddf6f4.JPG)
