### ISSUE TITLE
Automatically delete old files in certain folders

### ISSUE THREAD

**Issue by tomdereub** [nextcloud/server#16805]
Hi,
How about an option to delete files older than xx days in specifics folders? For example, I'm using "Nextcloud for filelink" in Thunderbird with my personal server, wich uses a specific folder in nextcloud to upload big linked files in emails. In such a folder, I would like to delete automatically files older than a few months.
Thanks for the work!

**Comment by Nils160988** [comment]
Can you use the files_retention app? I think it should serve your needs.

**Comment by tomdereub** [comment]
Ok, it does not exactly what I thought (impossible to tag automatically files from a specific folder, or I didn't find how), but about thunderbird filelink, it seems that it'll soon do the job: https://github.com/nextcloud/nextcloud-filelink/issues/49.
Thanks!
