### ISSUE TITLE
Theming App does not work behind Reverse Proxy

### ISSUE THREAD

**Issue by Linuxfabrik** [nextcloud/server#16807]
### Steps to reproduce
1. Put your Nextcloud behind a Apache Reverse Proxy using SNI
2. Configure Theming App with a custom title etc.
3. Load the login page

### Expected behaviour
Theming App should print the custom properties on the Login page.

### Actual behaviour
Theming App just prints all its defaults, customization is not possible at all.

### Server configuration
```'overwritecondaddr' => '^ip\\.of\\.nextcloud\\.instance$',
  'overwritehost' => 'cloud.example.com',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'trusted_proxies' =>
  array (
    0 => 'ip-of-reverse-proxy',
  ),
```

**Comment by JohnXLivingston** [comment]
I have the same bug, behind a nginx reverse proxy. Nextcloud version: 17.0.1

**Comment by JohnXLivingston** [comment]
I just try without using a reverse proxy, using directly the nginx config (as in the documentation). Same bug : theming doesn't apply, except the color of folder's icons.

**Comment by JohnXLivingston** [comment]
Just found a workaround: in my nginx reverse proxy config, I had to remove: `proxy_set_header Host $host;`
I don't know why it works...

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
