### ISSUE TITLE
Feature Request: Let's encrypt and auto https support

### ISSUE THREAD

**Issue by JamborJan** [nextcloud/server#1681]
Don't know if feature request go here or not.

### Actual behavior
When I setup a nextcloud instance I have to take care about getting certificates and a domain when I ant to access my nextcloud instance when not being in the same network.

### Expected behavior
When setting up my nextcloud server I'm getting a setup wizard which guides me to setup a Let's Encrypt based certificate and a domain name. 

### possible technical solution
Take a look at https://github.com/sandstorm-io/sandcats. They have solved the issue quite nice. There is no web setup wizard but the command line setup wizard works very well. Maybe its quite easy possible to use this as a basis for a improved web setup wizard included in nextcloud.

Additional documentation: https://docs.sandstorm.io/en/latest/administering/sandcats/

### benefit
Having a setup wizard including domain and certificates allows even none-tech users to set up an own instance or the nextcloud box including the possibility to access files from everywhere. 

### problems / downside
Routers still need to be configured. I'm not sure if there is a plug and play option which some users support which can help here. This can still be a show stopper for some none-tech users.

**Comment by MariusBluem** [comment]
- Possible with the Nextcloud Snap (https://github.com/nextcloud/nextcloud-snap) or as part of other appliances ;)

- Not possible with the native-server, because of the different instances (shared hosting, OS, ...)

**Comment by JamborJan** [comment]
Thanks for your feedback @MariusBluem. I absolutely agree that it is not a solution for hosting services, they have other options for that.

But for small instances e.g. small companies, families or individuals this should be a pretty good way of solving the issue. The main point why I see involvement of the nextcloud team here is, that there needs to be small service. In the example I have mentioned the service is also run by the development team.

I see great benefit from the nextcloud perspective maybe also in combination with a directory for federation. It should become very easy to setup a new server and access it from anywhere plus connect to other users with own instances in no time.

What do you think?

**Comment by mkoppmann** [comment]
You can run Nextcloud on Caddy (https://github.com/mholt/caddy) which automatically configures HTTPS and retrieves certificates from Let’s Encrypt.

**Comment by JamborJan** [comment]
Thanks for the hint @mkoppmann. I'm not sure if I described my thoughts well enough, I'm not looking for a solution for me, I can perfectly run my system as I have the infrastructure for it.

My goal with this request is to improve the "out-of-the-box" experience for none-technical users especially for consumer products like the next cloud box. Right now it is very easy to setup nextcloud as long as you want to use it only in your local LAN and not when you are away which is nice but not enough when you want to compete with dropbox google and Co.

Imagine the user story: My father who is not a tech guy hears about the nextcloud box and buys one. He sets it up at home and is totally exited. He gets the mobile app everything is fine. Now he visits his friend and wants to show the cool stuff but nothing works. He asks me why it's not working when not at home, I'm telling him that he has to set up scripts and web servers and stuff. Totally crap user experience,

Better: My father gets the box, hooks it up with his network, connects to the box and gets a setup screen. Enters some stuff like desired name etc. He goes to his friend, everything is still working. Awesome, the friend buys a box too. Does the same. And now due to the fact that both have registered with the DNS directory at nextcloud they can search for each other in the list of known servers for federation and can share immediately files. Awesome user experience!

**Comment by nickvergessen** [comment]
for the "out of the box" experience a lot of things need to be done, including opening a port in your router, setting up dyndns, etc. This is all out of scope of the actual product. If at all, your webserver should handle such stuff. But since they don't other things have been created, nextcloud snap being one of them.

So I'm closing this, since I feel it's out of scope for us.

**Comment by benyanke** [comment]
I'm confused... using Let's Encrypt is in the webserver config and shell scripting realm, not a PHP web app scope, where nextcloud sits. It's not really a feature that would be built into NextCloud

**Comment by JamborJan** [comment]
When you talk about the normal Nextcloud server I understand your confusion :-)

This topic is more relevant when we talk about consumer products like the Nextcloud Box is one which has been released earlier this year by nextcloud.
