### ISSUE TITLE
.well-known check behind proxy using path is requesting a wrong URL

### ISSUE THREAD

**Issue by tikoflano** [nextcloud/server#16817]
The .well-known check tries to check  at https://my.domain.com/.well-known/carddav when my installation is behind a proxy at https://my.domain.com/nextcloud, it should make the request to https://my.domain.com/nextcloud/.well-known/carddav.

If I try to check manually the configuration (redirection) is ok. I'm using Traefik as reverse proxy.

Right now my solution is to skip this checks with `occ config:system:set check_for_working_wellknown_setup --value=false` but I would like to have the checks working.

It looks like the issue is that the URLs at https://github.com/nextcloud/server/blob/master/settings/js/admin.js#L251 are hard coded.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/11787#issuecomment-429239543

**Comment by tikoflano** [comment]
Thanks, maybe this should be added to de docs?

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html#service-discovery

Sure. You can use the Edit on Github link on the page above to suggest changes. It might be good to have some general information about .well-known or a link to https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers there.
