### ISSUE TITLE
Expiration date enforcing for email share

### ISSUE THREAD

**Issue by GuiGuiSoft** [nextcloud/server#16810]
**Is your feature request related to a problem? Please describe.**
I'd like to enforce an expiration date for every external share (email or link) in order to be compliant with my security requirements.

**Describe the solution you'd like**
In Parameters > Administration > Sharing options. For link sharing options we have this possibility :  
![image](https://user-images.githubusercontent.com/8069239/63347168-dfbfbf00-c356-11e9-955d-6c0d41f6f0fd.png)

Is it possible to add the same possibility for email sharing option ?  
![image](https://user-images.githubusercontent.com/8069239/63347218-f82fd980-c356-11e9-9d9d-332f32cb3dd5.png)

Regards.

**Comment by wiswedel** [comment]
The link share settings you showed here apply to email shares already.
I'm closing this issue for now. 
@GuiGuiSoft Could you please test with the latest Nextcloud version and re-open this issue if the problem persists on your side anyway?

**Comment by G33rt-hub** [comment]
> The link share settings you showed here apply to email shares already.
> I'm closing this issue for now.
> @GuiGuiSoft Could you please test with the latest Nextcloud version and re-open this issue if the problem persists on your side anyway?

Unfortunately those settings don't appear to do anything for email shares... which has its own settings on the bottom of that page and expiration date enforcement is not part of those settings.  (I am running Nextcloud 21.0.1)

This is a major issue in a controlled environment. Can this please be fixed?
