### ISSUE TITLE
Sabre DAV Exception ServiceUnavailable

### ISSUE THREAD

**Issue by ClepToManix** [nextcloud/server#16827]
### Steps to reproduce
Nothing to reproduce, think this is only in our environment 

### Server configuration

**Operating system**: Ubuntu Server 16.04

**Web server:** Apache (newest)

**Database:**MySQL (10.0.38)/MariaDB

**PHP version:**7.3.8

**Nextcloud version:** (see Nextcloud admin page)
16.0.4.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from an older version, but this strange behavior is since Version 15
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Can I Update
Default encryption module
External sites
External storage support
Files clipboard
first run wizard
ldap user and group backend
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '***',
    1 => '***',
    2 => '***',
  ),
  'datadirectory' => '/media/nextcloud',
  'overwrite.cli.url' => '***',
  'dbtype' => 'mysql',
  'version' => '16.0.4.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '***',
  'dbpassword' => '***',
  'logtimezone' => 'UTC',
  'installed' => true,
  'skeletondirectory' => '/media/new_owncloud_user_files',
  'enable_previews' => false,
  'default_language' => 'de_DE',
  'default_locale' => 'de_DE',
  'knowledgebaseenabled' => false,
  'enable_avatars' => true,
  'mail_smtpmode' => 'smtp',
  'mail_from_address' => 'cloud',
  'mail_domain' => '***',
  'mail_smtphost' => '192.168.1.182',
  'mail_smtpport' => '25',
  'mail_smtpauthtype' => 'LOGIN',
  'auth.bruteforce.protection.enabled' => false,
  'has_internet_connection' => true,
  'check_for_working_webdav' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'production',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\APCu',
  'htaccess.RewriteBase' => '/',
  'check_for_working_htaccess' => true,
  'versions_retention_obligation' => 'auto',
  'onlyoffice' => 
  array (
    'verify_peer_off' => true,
  ),
  'trashbin_retention_obligation' => '3, 7',
  'simpleSignUpLink.shown' => false,
  'app_install_overwrite' => 
  array (
    0 => 'groupfolders',
    1 => 'external',
  ),
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Nextcloud Client Android
**Operating system:**
Android
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Sabre\DAV\Exception\ServiceUnavailable: OC\User\LoginException: Nutzer deaktiviert
/var/www/kwolkemk/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 200:

OCA\DAV\Connector\Sabre\Auth->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/kwolkemk/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php - line 150:

Sabre\DAV\Auth\Plugin->check(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

<<closure>>

Sabre\DAV\Auth\Plugin->beforeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/kwolkemk/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:

call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])

/var/www/kwolkemk/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:

Sabre\Event\EventEmitter->emit("beforeMethod", [ Sabre\HTTP ... }])

/var/www/kwolkemk/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})

/var/www/kwolkemk/apps/dav/appinfo/v1/webdav.php - line 80:

Sabre\DAV\Server->exec()

/var/www/kwolkemk/remote.php - line 163:

require_once("/var/www/kw ... p")
```
</details>

Let me explain our problem:

some of our android users (nextcloud app - newest) getting the login screen from nextcloud. again and again. If i retype username and password the account is still logget in but after a moment the login screen appiers again. This failure is since over 6 month, i might think i have opend a github issue, but idk, maybe not.

In nextcloud interface there are 2 notifications who pop up every 10 - 20 seconds:

Sabre\DAV\Exception\ServiceUnavailable: OC\User\LoginException: Nutzer deaktiviert (fatal - webdav)
and 
OC\User\LoginException: Nutzer deaktiviert (error - no app in context)

it it mean the user was disabled. But the user can still log in via webinterface and via nc app, but in the nc app there is the loop with the login.

Hope anyone can help us. If you need more information, please ask for it, i try my best :)

Best Regards,

Philipp

**Comment by kesselb** [comment]
Please add the error message to your initial post. Anything in the logs? Usually for setup issues https://help.nextcloud.com is the better place.

**Comment by kesselb** [comment]
Edited the issue report because most of the information were hidden inside the signing status detail block.

**Comment by kesselb** [comment]
I would try to delete the app tokens for the user. Login as user, go to settings, delete all devices and connect the devices again. 

cc @nextcloud/server-triage
