### ISSUE TITLE
No translations in Security

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#16821]
No translations of active time in Security -> Devices & sessions.

- English version:

![obraz](https://user-images.githubusercontent.com/47037905/63415765-7eebc180-c3fe-11e9-8438-9bf0430daa6d.png)

- Polish version

![obraz](https://user-images.githubusercontent.com/47037905/63415852-a5a9f800-c3fe-11e9-85f2-771e123472e8.png)
![obraz](https://user-images.githubusercontent.com/47037905/63415910-beb2a900-c3fe-11e9-9a52-e94b4240fdf2.png)

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Comment by kesselb** [comment]
cc @nextcloud/javascript

**Comment by blizzz** [comment]
Seems like a dup of https://github.com/nextcloud/server/issues/15457, WIP fix in https://github.com/nextcloud/server/pull/14784

**Comment by Valdnet** [comment]
In my opinion, this is not the same problem as #15457. The translation, e.g. in "Files", is correct and the time indicated is correct. Screen below:

![obraz](https://user-images.githubusercontent.com/47037905/63429571-b8322a80-c41a-11e9-8176-c96b94c23e30.png)

The language and region settings have no effect on the content displayed. In my opinion, this is a typical failure to download a translation from the l10n catalog.

**Comment by blizzz** [comment]
@nickvergessen you've got a clue?

**Comment by nickvergessen** [comment]
It is exactly the same problem, it just only breaks in some places where the "live timestamp" feature is (not) used.

**Comment by Valdnet** [comment]
@nickvergessen Is there any solution to this problem?
Closing the issue will bring nothing new :wink:.

**Comment by nickvergessen** [comment]
See above from Blizzz
> Seems like a dup of #15457, WIP fix in #14784
