### ISSUE TITLE
Login  button disabled 

### ISSUE THREAD

**Issue by Marsupilani** [nextcloud/server#16838]
### Steps to reproduce
Try to login

### Expected behaviour
Login should be progresssed by pressing the login button after input of username and password.

### Actual behaviour
No reaction on pressing the login button or the reset password link. It seems the buttons are disabled by the Application. 
Only the register link work.
Sync of already existing Nextcloud-Clients still work.

### Server configuration

**Operating system**:
Debian stretch
**Web server:**
nginx 1.14.1
**Database:**
ysql  Ver 15.1 Distrib 10.1.38-MariaDB
**PHP version:**
PHP 7.3.8-1+0~20190807.43+debian9~1.gbp7731bf
**Nextcloud version:** (see Nextcloud admin page)
16.0.4.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 16.0.x
**Where did you install Nextcloud from:**
www.nextcloud.com and update by webinstaller

**Signing status:**
<details>
<summary>Signing status</summary>
occ integrity:check-core
  - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: dc48de7ad4baa030c5e563350c9a80b274bad783f6f5adbf1595ecef6c6a32e52890a24cb26cddb0aa20193ba52c001150c68d8bfb567f0aed566f4029a190a3
      - current: 6a05a7a2bd52651177dc54170f94c7ccf1966c421f30540be49d64770d71c71731052565c2f8e00406a579e7c78dad16673202051231626f1e6d4e656046e6fc
</details>

**List of activated apps:**
same problem with disabled all Apps
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - apporder: 0.7.1
  - audioplayer: 2.7.2
  - bookmarks: 1.1.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - dicomviewer: 1.2.0
  - drawio: 0.9.3
  - encryption: 2.4.0
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_accesscontrol: 1.6.0
  - files_automatedtagging: 1.6.0
  - files_downloadactivity: 1.5.0
  - files_external: 1.7.0
  - files_frommail: 0.3.0
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - flowupload: 0.1.2
  - gallery: 18.3.0
  - gpxedit: 0.0.11
  - gpxpod: 4.0.5
  - groupfolders: 4.0.5
  - keeweb: 0.5.1
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.2
  - metadata: 0.9.0
  - music: 0.10.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.1
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.8.1
  - phonetrack: 0.5.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - radio: 0.6.5
  - rainloop: 6.0.3
  - recommendations: 0.4.0
  - registration: 0.4.7
  - sensorlogger: 0.1.1
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - socialsharing_email: 1.0.5
  - spreed: 6.0.4
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.1
  - theming: 1.7.0
  - twofactor_admin: 0.4.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_gateway: 0.14.0
  - twofactor_totp: 3.0.1
  - twofactor_u2f: 3.0.1
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
--nothing--
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"yLPhKp6R1krr2HAi0LpS","level":0,"time":"2019-08-22T18:32:16+00:00","remoteAddr":"92.50.113.37","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions job with ID 853","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.100 Safari\/537.36","version":"16.0.4.1"}
{"reqId":"yLPhKp6R1krr2HAi0LpS","level":0,"time":"2019-08-22T18:32:16+00:00","remoteAddr":"92.50.113.37","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\GroupFolders\\BackgroundJob\\ExpireGroupVersions job with ID 853 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.100 Safari\/537.36","version":"16.0.4.1"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

</details>

####  Login Page Source code
<details>

  | <!DOCTYPE html>
-- | --
  | <html class="ng-csp" data-placeholder-focus="false" lang="de-DE" data-locale="de_DE" >
  | <head
  | data-requesttoken="d81yROl0a745MnLR1Pvz+swrDteZv2XNELtltx45UEY=:DpU7D6JMLt9cRgOJvJOV1b5JS5nThim8W/UQg1UPAQM=">
  | <meta charset="utf-8">
  | <title>
  | TABALEN CLOUD		</title>
  | <meta http-equiv="X-UA-Compatible" content="IE=edge">
  | <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
  | <meta name="apple-itunes-app" content="app-id=1125420102">
  | <meta name="theme-color" content="#0082c9">
  | <link rel="icon" href="/core/img/favicon.ico">
  | <link rel="apple-touch-icon-precomposed" href="/core/img/favicon-touch.png">
  | <link rel="mask-icon" sizes="any" href="/core/img/favicon-mask.svg" color="#0082c9">
  | <link rel="manifest" href="/apps/theming/manifest?v=6">
  | <link rel="stylesheet" href="/apps/apporder/css/apporder.css?v=638ee240-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/viewer.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/sidebar.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/bootstrap_accordion.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/viewerMain.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/viewerMainDialog.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/captureImageDialog.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/annotationDialogs.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/dicomviewer/css/external/font-awesome/font-awesome.min.css?v=62abc69f-6">
  | <link rel="stylesheet" href="/apps/files_pdfviewer/css/style.css?v=35c36e89-6">
  | <link rel="stylesheet" href="/apps/gpxedit/css/style.css?v=eacd15be-6">
  | <link rel="stylesheet" href="/core/css/guest.css?v=55954715-6">
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/js/dist/main.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/js/core/merged-template-prepend.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/search/js/search.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/l10n/de_DE.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/js/backgroundjobs.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/encryption/l10n/de_DE.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/encryption/js/encryption.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/js/dist/share_backend.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/apporder/l10n/de_DE.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/apporder/js/apporder.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/dicomviewer/l10n/de_DE.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/dicomviewer/js/app.bundle.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/files_pdfviewer/js/previewplugin.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/files_videoplayer/js/main.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/gallery/l10n/de_DE.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/gpxedit/l10n/de.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/gpxedit/js/filetypes.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/apps/rainloop/js/rainloop.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/search/js/searchprovider.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/js/files/fileinfo.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/core/js/files/client.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=" defer src="/js/core/merged-login.js?v=55954715-6"></script>
  | <script nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0=">
  | var oc_debug=false;
  | var oc_isadmin=false;
  | var backendAllowsPasswordConfirmation=true;
  | var oc_dataURL=false;
  | var oc_webroot="";
  | var oc_appswebroots={"accessibility":"/apps/accessibility","activity":"/apps/activity","admin_audit":"/apps/admin_audit","announcementcenter":"/apps/announcementcenter","apporder":"/apps/apporder","audioplayer":"/apps/audioplayer","bookmarks":"/apps/bookmarks","bruteforcesettings":"/apps/bruteforcesettings","calendar":"/apps/calendar","checksum":"/apps/checksum","cloud_federation_api":"/apps/cloud_federation_api","comments":"/apps/comments","contacts":"/apps/contacts","dav":"/apps/dav","dicomviewer":"/apps/dicomviewer","drawio":"/apps/drawio","encryption":"/apps/encryption","external":"/apps/external","federatedfilesharing":"/apps/federatedfilesharing","federation":"/apps/federation","files":"/apps/files","files_accesscontrol":"/apps/files_accesscontrol","files_automatedtagging":"/apps/files_automatedtagging","files_downloadactivity":"/apps/files_downloadactivity","files_external":"/apps/files_external","files_frommail":"/apps/files_frommail","files_markdown":"/apps/files_markdown","files_mindmap":"/apps/files_mindmap","files_pdfviewer":"/apps/files_pdfviewer","files_rightclick":"/apps/files_rightclick","files_sharing":"/apps/files_sharing","files_texteditor":"/apps/files_texteditor","files_trashbin":"/apps/files_trashbin","files_versions":"/apps/files_versions","files_videoplayer":"/apps/files_videoplayer","firstrunwizard":"/apps/firstrunwizard","flowupload":"/apps/flowupload","gallery":"/apps/gallery","gpxedit":"/apps/gpxedit","gpxpod":"/apps/gpxpod","groupfolders":"/apps/groupfolders","keeweb":"/apps/keeweb","logreader":"/apps/logreader","lookup_server_connector":"/apps/lookup_server_connector","mail":"/apps/mail","metadata":"/apps/metadata","music":"/apps/music","nextcloud_announcements":"/apps/nextcloud_announcements","notes":"/apps/notes","notifications":"/apps/notifications","oauth2":"/apps/oauth2","password_policy":"/apps/password_policy","passwords":"/apps/passwords","phonetrack":"/apps/phonetrack","privacy":"/apps/privacy","provisioning_api":"/apps/provisioning_api","radio":"/apps/radio","rainloop":"/apps/rainloop","recommendations":"/apps/recommendations","registration":"/apps/registration","sensorlogger":"/apps/sensorlogger","serverinfo":"/apps/serverinfo","sharebymail":"/apps/sharebymail","socialsharing_email":"/apps/socialsharing_email","spreed":"/apps/spreed","support":"/apps/support","survey_client":"/apps/survey_client","systemtags":"/apps/systemtags","tasks":"/apps/tasks","theming":"/apps/theming","twofactor_admin":"/apps/twofactor_admin","twofactor_backupcodes":"/apps/twofactor_backupcodes","twofactor_gateway":"/apps/twofactor_gateway","twofactor_totp":"/apps/twofactor_totp","twofactor_u2f":"/apps/twofactor_u2f","updatenotification":"/apps/updatenotification","user_ldap":"/apps/user_ldap","viewer":"/apps/viewer","workflowengine":"/apps/workflowengine"};
  | var datepickerFormatDate="dd.MM.yy";
  | var nc_lastLogin=0;
  | var nc_pageLoad=1566498932;
  | var dayNames=["Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"];
  | var dayNamesShort=["Son.","Mon.","Die.","Mit.","Don.","Fre.","Sam."];
  | var dayNamesMin=["So","Mo","Di","Mi","Do","Fr","Sa"];
  | var monthNames=["Januar","Februar","M\u00e4rz","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"];
  | var monthNamesShort=["Jan.","Feb.","M\u00e4r.","Apr.","Mai","Jun.","Jul.","Aug.","Sep.","Okt.","Nov.","Dez."];
  | var firstDay=1;
  | var oc_config={"session_lifetime":1440,"session_keepalive":true,"version":"16.0.4.1","versionstring":"16.0.4","enable_avatars":true,"lost_password_link":null,"modRewriteWorking":true,"sharing.maxAutocompleteResults":0,"sharing.minSearchStringLength":0,"blacklist_files_regex":"\\.(part\|filepart)$"};
  | var oc_appconfig={"core":{"defaultExpireDateEnabled":true,"defaultExpireDate":7,"defaultExpireDateEnforced":false,"enforcePasswordForPublicLink":false,"enableLinkPasswordByDefault":false,"sharingDisabledForUser":false,"resharingAllowed":true,"remoteShareAllowed":true,"federatedCloudShareDoc":"https:\/\/docs.nextcloud.com\/server\/16\/go.php?to=user-sharing-federated","allowGroupSharing":true},"files":{"max_chunk_size":10485760},"comments":{"maxAutoCompleteResults":10},"shareByMailEnabled":true,"shareByMail":{"enforcePasswordProtection":false}};
  | var oc_defaults={"entity":"TABALEN CLOUD","name":"TABALEN CLOUD","title":"TABALEN CLOUD","baseUrl":"https:\/\/cloud.tabalen.org","syncClientUrl":"https:\/\/nextcloud.com\/install\/#install-clients","docBaseUrl":"https:\/\/docs.nextcloud.com","docPlaceholderUrl":"https:\/\/docs.nextcloud.com\/server\/16\/go.php?to=PLACEHOLDER","slogan":"For private use only...","logoClaim":"","shortFooter":"<a href=\"https:\/\/cloud.tabalen.org\" target=\"_blank\" rel=\"noreferrer noopener\" class=\"entity-name\">TABALEN CLOUD<\/a> \u2013 For private use only...","longFooter":"<a href=\"https:\/\/cloud.tabalen.org\" target=\"_blank\" rel=\"noreferrer noopener\" class=\"entity-name\">TABALEN CLOUD<\/a> \u2013 For private use only...","folder":""};
  | var oc_capabilities={"core":{"pollinterval":60,"webdav-root":"remote.php\/webdav"},"bruteforce":{"delay":0},"activity":{"apiv2":["filters","filters-api","previews","rich-strings"]},"ocm":{"enabled":true,"apiVersion":"1.0-proposal1","endPoint":"https:\/\/cloud.tabalen.org\/ocm","resourceTypes":[{"name":"file","shareTypes":["user","group"],"protocols":{"webdav":"\/public.php\/webdav\/"}}]},"dav":{"chunking":"1.0"},"files_sharing":{"api_enabled":true,"public":{"enabled":true,"password":{"enforced":false},"expire_date":{"enabled":true,"days":"7","enforced":false},"multiple_links":true,"send_mail":false,"upload":true,"upload_files_drop":true},"resharing":true,"user":{"send_mail":false,"expire_date":{"enabled":true}},"group_sharing":true,"group":{"enabled":true,"expire_date":{"enabled":true}},"default_permissions":31,"federation":{"outgoing":true,"incoming":true,"expire_date":{"enabled":true}},"sharebymail":{"enabled":true,"upload_files_drop":{"enabled":true},"password":{"enabled":true},"expire_date":{"enabled":true}}},"files":{"undelete":true,"bigfilechunking":true,"blacklisted_files":[".htaccess"],"versioning":true},"notifications":{"ocs-endpoints":["list","get","delete","delete-all","icons","rich-strings"],"push":["devices","object-data"],"admin-notifications":["ocs","cli"]},"theming":{"name":"TABALEN CLOUD","url":"https:\/\/cloud.tabalen.org","slogan":"For private use only...","color":"#0082c9","color-text":"#ffffff","color-element":"#0082c9","logo":"https:\/\/cloud.tabalen.org\/apps\/theming\/image\/logo?useSvg=1&v=6","background":"https:\/\/cloud.tabalen.org\/apps\/theming\/image\/background?v=6","background-plain":false,"background-default":false},"external":{"v1":["sites","device","groups","redirect"]},"password_policy":{"minLength":8,"enforceNonCommonPassword":true,"enforceNumericCharacters":true,"enforceSpecialCharacters":true,"enforceUpperLowerCase":false},"spreed":{"features":["audio","video","chat-v2","guest-signaling","empty-group-room","guest-display-names","multi-room-users","favorites","last-room-activity","no-ping","system-messages","mention-flag","in-call-flags","notification-levels","invite-groups-and-mails","locked-one-to-one-rooms","read-only-rooms"],"config":{"chat":{"max-length":32000}}},"registration":{"enabled":true,"apiRoot":"\/ocs\/v2.php\/apps\/registration\/api\/v1\/","apiLevel":"v1"}};
  |  
  | </script>
  | <link rel="stylesheet" href="/apps/theming/styles?v=6"/><script defer src="/apps/theming/js/theming?v=6" nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0="></script><script defer src="/apps/accessibility/js/accessibility?v=0" nonce="ZDgxeVJPbDBhNzQ1TW5MUjFQdnorc3dyRHRlWnYyWE5FTHRsdHg0NVVFWT06RHBVN0Q2Sk1MdDljUmdPSnZKT1YxYjVKUzVuVGhpbThXL1VRZzFVUEFRTT0="></script><meta property="og:title" content="TABALEN CLOUD"/><meta property="og:description" content="For private use only..."/><meta property="og:site_name" content="TABALEN CLOUD"/><meta property="og:url" content="https://cloud.tabalen.org/"/><meta property="og:type" content="website"/><meta property="og:image" content="https://cloud.tabalen.org/core/img/favicon-touch.png"/>	</head>
  | <body id="body-login">
  | <noscript>
  | <div id="nojavascript">
  | <div>
  | Diese Anwendung benötigt JavaScript zum ordnungsgemäßen Betrieb. Bitte <a href="https://www.enable-javascript.com/" target="_blank" rel="noreferrer noopener">aktivieren Sie JavaScript</a> und laden Sie die Seite neu.		</div>
  | </div>
  | </noscript>
  | <div class="wrapper">
  | <div class="v-align">
  | <header role="banner">
  | <div id="header">
  | <div class="logo">
  | <h1 class="hidden-visually">
  | TABALEN CLOUD								</h1>
  | <img src="/apps/theming/image/logo?useSvg=1&amp;v=6"/>
  | </div>
  | </div>
  | </header>
  | <main>
  |  
  | 
  | <form method="post" name="login">
  | <fieldset>
  | <div id="message" class="hidden">
  | <img class="float-spinner" alt=""
  | src="/core/img/loading-dark.gif">
  | <span id="messageText"></span>
  | 
  | <div style="clear: both;"></div>
  | </div>
  | <p class="grouptop">
  | <input type="text" name="user" id="user"
  | placeholder="Benutzername oder E-Mail"
  | aria-label="Benutzername oder E-Mail"
  | value=""
  | autofocus				autocomplete="on" autocapitalize="none" autocorrect="off" required>
  | <label for="user" class="infield">Benutzername oder E-Mail</label>
  | </p>
  |  
  | <p class="groupbottom">
  | <input type="password" name="password" id="password" value=""
  | placeholder="Passwort"
  | aria-label="Passwort"
  | autocomplete="on" autocapitalize="none" autocorrect="off" required>
  | <label for="password" class="infield">Passwort</label>
  | </p>
  |  
  | <div id="submit-wrapper">
  | <input type="submit" id="submit" class="login primary" title="" value="Anmelden" disabled="disabled" />
  | <div class="submit-icon icon-confirm-white"></div>
  | </div>
  |  
  |  
  |  
  | <div id="reset-password-wrapper" style="display: none;">
  | <input type="submit" id="reset-password-submit" class="login primary" title="" value="Passwort zurücksetzen" disabled="disabled" />
  | <div class="submit-icon icon-confirm-white"></div>
  | </div>
  |  
  | <div class="login-additional">
  | <div class="lost-password-container">
  | <a id="lost-password" href="">
  | Passwort vergessen?				</a>
  | <a id="lost-password-back" href="" style="display:none;">
  | Zur Anmeldung wechseln				</a>
  | </div>
  | </div>
  |  
  | <input type="hidden" name="timezone_offset" id="timezone_offset"/>
  | <input type="hidden" name="timezone" id="timezone"/>
  | <input type="hidden" name="requesttoken" value="d81yROl0a745MnLR1Pvz+swrDteZv2XNELtltx45UEY=:DpU7D6JMLt9cRgOJvJOV1b5JS5nThim8W/UQg1UPAQM=">
  | </fieldset>
  | </form>
  | <form id="alternative-logins">
  | <fieldset>
  | <ul>
  | <li><a class="button" href="/apps/registration/" >Registrieren</a></li>
  | </ul>
  | </fieldset>
  | </form>
  | </main>
  | </div>
  | </div>
  | <footer role="contentinfo">
  | <p class="info">
  | </footer>
  | </body>
  | </html>
  |  

</details>

**Comment by kesselb** [comment]
Looks like a duplicate of #14471
