### ISSUE TITLE
.htaccess generation rewrite error

### ISSUE THREAD

**Issue by rinchen** [nextcloud/server#16831]
This may be a stupid user issue but it's got me stumped. When I run update:htaccess it takes my site down. I've narrowed it to rewrite rules. All the information below, minus the domain name & overwritewebroot were taken directly from the v16 admin manual. The webroot override was taken from a previous version. Removed, it makes no difference, htaccess still hoses the site. Running repair finds and fixes no errors.

> $ sudo -u www-data php /var/www/nextcloud/occ config:list |grep htaccess
>             ".htaccess"
>         "check_for_working_htaccess": true,
>         "htaccess.RewriteBase": "\/nextcloud",

> $ sudo -u www-data php /var/www/nextcloud/occ config:list |grep overwrite
>         "overwritehost": "",
>         "overwriteprotocol": "",
>         "overwritewebroot": "\/nextcloud",
>         "overwritecondaddr": "",
>         "overwrite.cli.url": "https:\/\/ournextcloud.org\/nextcloud",

Running update:htaccess yields the following .htaccess file

```
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
</ifModule>

# section for Apache 2.2 and 2.4
<ifModule mod_autoindex.c>
IndexIgnore *
</ifModule>
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

ErrorDocument 403 /nextcloud/
ErrorDocument 404 /nextcloud/
<IfModule mod_rewrite.c>
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg)$
  RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
  RewriteCond %{REQUEST_FILENAME} !core/img/manifest.json$
  RewriteCond %{REQUEST_FILENAME} !/remote.php
  RewriteCond %{REQUEST_FILENAME} !/public.php
  RewriteCond %{REQUEST_FILENAME} !/cron.php
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
  RewriteCond %{REQUEST_FILENAME} !/status.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
  RewriteCond %{REQUEST_FILENAME} !/robots.txt
  RewriteCond %{REQUEST_FILENAME} !/updater/
  RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
  RewriteCond %{REQUEST_FILENAME} !/ocm-provider/
  RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /nextcloud
  RewriteEngine on
  RewriteRule ^\.well-known/host-meta /nextcloud/public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /nextcloud/public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /nextcloud/public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/carddav /nextcloud/remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /nextcloud/remote.php/dav/ [R=301,L]
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>
```

For thoroughness, this is straight copy from the admin manual:

> $ cat nextcloud.conf
> Alias /nextcloud "/var/www/nextcloud/"
> 
> <Directory /var/www/nextcloud/>
>   Require all granted
>   Options FollowSymlinks MultiViews
>   AllowOverride All
> 
>  <IfModule mod_dav.c>
>   Dav off
>  </IfModule>
> 
>  SetEnv HOME /var/www/nextcloud
>  SetEnv HTTP_HOME /var/www/nextcloud
> 
> </Directory>

### Steps to reproduce
1. sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess
2. refresh web site

### Expected behaviour
Site should be live.

### Actual behaviour
I see an (empty) directory listing in the browser.

### Server configuration
**Operating system**:
Ubuntu 18.04

**Web server:**
apache2 2.4.29

**Database:**
mysql 5.8

**PHP version:**
7.2.19

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from ownCloud ages ago. Currently updates using settings/admin/overview button.

**Where did you install Nextcloud from:**
source from nextcloud following the ownCloud to Nextcloud upgrade instructions, years ago.

**Comment by kesselb** [comment]
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

Please add the nextcloud configuration and check the logs for error messages. 

> Running update:htaccess yields the following .htaccess file

The result looks like the .htaccess for the data directory with the additional rules for pretty urls and redirects for well known. There is no code that generates such a file.

**Comment by rinchen** [comment]
> {
    "system": {
        "installed": true,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "forcessl": true,
        "blacklisted_files": [
            ".htaccess"
        ],
        "overwritehost": "",
        "overwriteprotocol": "",
        "overwritewebroot": "\/nextcloud",
        "overwritecondaddr": "",
        "overwrite.cli.url": "https:\/\/ournextcloud.org\/nextcloud",
        "trusted_domains": [
            "ournextcloud.org",
            "www.ournextcloud.org"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "default_language": "en",
        "3rdpartyroot": "",
        "3rdpartyurl": "",
        "defaultapp": "files",
        "knowledgebaseenabled": true,
        "appstoreenabled": true,
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": false,
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "mail_smtpauthtype": "LOGIN",
        "trashbin_retention_obligation": "auto",
        "allow_user_to_change_display_name": true,
        "appcodechecker": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "check_for_working_webdav": true,
        "check_for_working_htaccess": true,
        "log_type": "nextcloud",
        "logfile": "",
        "loglevel": 2,
        "logdateformat": "F d, Y H:i:s",
        "logtimezone": "America\/Denver",
        "log_query": false,
        "log_authfailip": true,
        "log_rotate_size": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "custom_csp_policy": "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *",
        "xframe_restriction": true,
        "maintenance": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "customclient_desktop": "",
        "customclient_android": "",
        "customclient_ios": "",
        "enable_previews": false,
        "preview_max_scale_factor": 10,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "preview_office_cl_parameters": "",
        "enable_avatars": true,
        "openssl": [],
        "singleuser": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "version": "16.0.4.1",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/nextcloud",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true
    }
}

**Comment by rinchen** [comment]
@kesselb The pretty URLs come from https://docs.nextcloud.com/server/16/admin_manual/installation/source_installation.html#pretty-urls

**Comment by kesselb** [comment]
Could you share the value of your datadirectory? Is your datadirectory the same as your nextcloud directory? It's not possible that the .htaccess file is generated by nextcloud. 

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

What about the integrity check? Any modified files?

**Comment by rinchen** [comment]
The data directory is /srv/owncloud    Nextcloud lives in /var/www/nextcloud 

The integrity is the .htaccess file because I've removed the rewrite clauses so the site works (I removed everything below the DO NOT CHANGE warning).

> Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
	- EXTRA_FILE
		- .htaccess.old

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f30494d88fc2d7caf0be8b27629cb246483cea0203696e44fd376bff19db51bb89c9f4076b1f849627ef3cb011f4a20088116e7b0d10ce467a3dde5db71e108b
                            [current] => e4db9834dbd2604ea05574d21fe1a185e87f2e254c78caae80c9bec43e6001315e16864efca1c38a456bdb11a3c6392d284e41038ab0fa1d2fc3b27bd84d8f9f
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.htaccess.old] => Array
                        (
                            [expected] => 
                            [current] => 9091112687d34cc7a1950c62322777462a8ae2769487e868c0a469e02c64ebb57587bc7d26a95614530ef8221ad2edf94f145834e18a7451411acb2114198a86
                        )

                )

        )

)

**Comment by kesselb** [comment]
I'm confused :confused:  

Is "the site" referring to nextcloud or another site in the web root?

Let me add some technical information: If you run `maintenance:update:htaccess` the following code is executed: https://github.com/nextcloud/server/blob/3ef1780646bc00d3fc5f836dd74243ecc1e260d9/lib/private/Setup.php#L471-L539

1) Try to determine the webroot from the config
2) Read the content from https://github.com/nextcloud/server/blob/master/.htaccess (actually its a local copy shipped with nextcloud)
3) Append "#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####" 
4) If pretty urls enabled append rewrite rules
5) Write the result back as .htaccess

>   RewriteEngine on
  RewriteRule ^\.well-known/host-meta /nextcloud/public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /nextcloud/public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /nextcloud/public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/carddav /nextcloud/remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /nextcloud/remote.php/dav/ [R=301,L]

These rules are never appended automatically. They are part of the shipped .htaccess. For your setup (nextcloud in a subdirectory) the rules are wrong anyway. You need to place them in the parent directory (because .well-known is always mydomain.com/.well-known by convention).

If you restore the orginal .htaccess and run the `maintenance:update:htaccess` is /nextcloud still working and if not anything in the webserver logs?

**Comment by rinchen** [comment]
```
# root @ ournextcloud in /var/www/nextcloud [13:40:41]
$ sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess
.htaccess has been updated

# root @ ournextcloud in /var/www/nextcloud [13:40:59]
$ cat .htaccess
# line below if for Apache 2.4
<ifModule mod_authz_core.c>
Require all denied
</ifModule>

# line below if for Apache 2.2
<ifModule !mod_authz_core.c>
deny from all
</ifModule>

# section for Apache 2.2 and 2.4
<ifModule mod_autoindex.c>
IndexIgnore *
</ifModule>
#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####

ErrorDocument 403 /nextcloud/
ErrorDocument 404 /nextcloud/
<IfModule mod_rewrite.c>
  Options -MultiViews
  RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
  RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
  RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg)$
  RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
  RewriteCond %{REQUEST_FILENAME} !core/img/manifest.json$
  RewriteCond %{REQUEST_FILENAME} !/remote.php
  RewriteCond %{REQUEST_FILENAME} !/public.php
  RewriteCond %{REQUEST_FILENAME} !/cron.php
  RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
  RewriteCond %{REQUEST_FILENAME} !/status.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
  RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
  RewriteCond %{REQUEST_FILENAME} !/robots.txt
  RewriteCond %{REQUEST_FILENAME} !/updater/
  RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
  RewriteCond %{REQUEST_FILENAME} !/ocm-provider/
  RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
  RewriteRule . index.php [PT,E=PATH_INFO:$1]
  RewriteBase /nextcloud
  <IfModule mod_env.c>
    SetEnv front_controller_active true
    <IfModule mod_dir.c>
      DirectorySlash off
    </IfModule>
  </IfModule>
</IfModule>

```

![Screen Shot 2019-08-29 at 13 43 37 ](https://user-images.githubusercontent.com/44416/63971118-066eab80-ca63-11e9-94dc-49ee2d9f7991.png)

Nothing in the logs.

**Comment by rinchen** [comment]
If I move those rewrite rules under /var/www I get the following screenshot.

![Screen Shot 2019-08-29 at 13 46 48 ](https://user-images.githubusercontent.com/44416/63971425-a3c9df80-ca63-11e9-9487-4e7ee50cba84.png)

What I'm expecting to see is the following (with the stripped .htaccess file).

![Screen Shot 2019-08-29 at 13 48 36 ](https://user-images.githubusercontent.com/44416/63971473-c3610800-ca63-11e9-96cd-f68aba101cb3.png)

**Comment by rinchen** [comment]
I've replaced the .htaccess file the contents of https://github.com/nextcloud/server/blob/master/.htaccess and this works as expected.  However on the admin overview I get an error 
>The "X-Frame-Options" HTTP header is not set to "SAMEORIGIN". This is a potential security or privacy risk, as it is recommended to adjust this setting accordingly.

**Comment by rinchen** [comment]
If I then run update:htaccess on that, the site now still works.

```
# root @ ournextcloud in /var/www/nextcloud [13:53:44]
$ diff .htaccess .htaccess.github
69,100d68
< #### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####
<
< ErrorDocument 403 /nextcloud/
< ErrorDocument 404 /nextcloud/
< <IfModule mod_rewrite.c>
<   Options -MultiViews
<   RewriteRule ^core/js/oc.js$ index.php [PT,E=PATH_INFO:$1]
<   RewriteRule ^core/preview.png$ index.php [PT,E=PATH_INFO:$1]
<   RewriteCond %{REQUEST_FILENAME} !\.(css|js|svg|gif|png|html|ttf|woff2?|ico|jpg|jpeg)$
<   RewriteCond %{REQUEST_FILENAME} !core/img/favicon.ico$
<   RewriteCond %{REQUEST_FILENAME} !core/img/manifest.json$
<   RewriteCond %{REQUEST_FILENAME} !/remote.php
<   RewriteCond %{REQUEST_FILENAME} !/public.php
<   RewriteCond %{REQUEST_FILENAME} !/cron.php
<   RewriteCond %{REQUEST_FILENAME} !/core/ajax/update.php
<   RewriteCond %{REQUEST_FILENAME} !/status.php
<   RewriteCond %{REQUEST_FILENAME} !/ocs/v1.php
<   RewriteCond %{REQUEST_FILENAME} !/ocs/v2.php
<   RewriteCond %{REQUEST_FILENAME} !/robots.txt
<   RewriteCond %{REQUEST_FILENAME} !/updater/
<   RewriteCond %{REQUEST_FILENAME} !/ocs-provider/
<   RewriteCond %{REQUEST_FILENAME} !/ocm-provider/
<   RewriteCond %{REQUEST_URI} !^/\.well-known/(acme-challenge|pki-validation)/.*
<   RewriteRule . index.php [PT,E=PATH_INFO:$1]
<   RewriteBase /nextcloud
<   <IfModule mod_env.c>
<     SetEnv front_controller_active true
<     <IfModule mod_dir.c>
<       DirectorySlash off
<     </IfModule>
<   </IfModule>
< </IfModule>
```

**Comment by rinchen** [comment]
With this setup I see the following:

![Screen Shot 2019-08-29 at 13 56 29 ](https://user-images.githubusercontent.com/44416/63971904-d9bb9380-ca64-11e9-86fd-0fa09d877c84.png)

with the validation errors being

```
Results
=======
- core
	- INVALID_HASH
		- .htaccess

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => f30494d88fc2d7caf0be8b27629cb246483cea0203696e44fd376bff19db51bb89c9f4076b1f849627ef3cb011f4a20088116e7b0d10ce467a3dde5db71e108b
                            [current] => c40a8aa3bc7cf52f5629fb78c9976259902400398957404824e904845f40a676cb683af11606ed95857c206baef4b3b22328a8218acd307ea8f6fbbc3dca077c
                        )

                )

        )

)
```

**Comment by kesselb** [comment]
Yes. The right version for Nextcloud 16 is: https://github.com/nextcloud/server/blob/stable16/.htaccess

**Comment by rinchen** [comment]
Downloading that and running update:hataccess got rid of the X-Frame error AND the integrity warning. Woot.

 **So it looks like the core issue for me is that somehow my .htaccess file got out of sync with master.** 

Thanks @kesselb - which I could give you karma here. You've been very helpful!

I have a related .htaccess issue that remains...
With the following being the contents of /var/www/.htaccess as sourced from https://docs.nextcloud.com/server/16/admin_manual/issues/general_troubleshooting.html#service-discovery, I still have two errors left. 

```
<IfModule mod_rewrite.c>
  RewriteEngine on
  RewriteRule ^\.well-known/host-meta /nextcloud/public.php?service=host-meta [QSA,L]
  RewriteRule ^\.well-known/host-meta\.json /nextcloud/public.php?service=host-meta-json [QSA,L]
  RewriteRule ^\.well-known/webfinger /nextcloud/public.php?service=webfinger [QSA,L]
  RewriteRule ^\.well-known/carddav /nextcloud/remote.php/dav/ [R=301,L]
  RewriteRule ^\.well-known/caldav /nextcloud/remote.php/dav/ [R=301,L]
</IfModule
```

and the errors 

```
* Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.

* Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.
```

The docs say "For the first case the .htaccess file shipped with Nextcloud should do this work for you when you’re running Apache." but it doesn't since I get the error without the .htaccess file in /var/www/. 

For what it's worth, I've had these errors since the dawn of time. I've never found a way to resolve them.

**Comment by kesselb** [comment]
> For the first case the .htaccess file shipped with Nextcloud should do this work for you when you’re running Apache.

Is a reference to 

> If Nextcloud is running at the document root of your Web server the correct URL is:

Yes the wording could be improved. Feel free to use the "Edit on GitHub" button (top right) on the docs page to suggest a better version. 


> If your Nextcloud instance is installed in a subfolder called nextcloud and you’re running Apache create or edit the .htaccess file within the document root of your Web server and add the following lines:

Actually the docs needs to be improved. I assume (from your domain) that your are using the domain only for nextcloud so there is no reason to put nextcloud into /nextcloud. I have no idea why we suggest `Alias /nextcloud`. You can either put nextcloud into the document root or change the document root. Maybe its related to the debian default configuration. For configuration issues the forums (it's possible to signup with your github account there) is the better place: https://help.nextcloud.com

**Comment by Faisal-rapist4** [comment]
@rinchen https://lnkr.fun/7235812
