### ISSUE TITLE
Add the ability to verifiy if an app is disable or not from occ command

### ISSUE THREAD

**Issue by yodatak** [nextcloud/server#16830]
**Is your feature request related to a problem? Please describe.**
When developing an ansible role , i need to make it idempotent so , i want to check with a occ command the status of an app an then activate it or disable if need.

**Describe the solution you'd like**
Develop a command like this : 
```
sudo -u www-data php /var/www/html/nextcloud/occ app:status user_ldap
disabled
```
Or inprove the app:list command
```
sudo -u www-data php /var/www/html/nextcloud/occ app:list:disabled
  - admin_audit
  - encryption
```

Maybe why not develop a nextcloud module for ansible or an official nextcloud role ;)

**Comment by blizzz** [comment]
Perhaps it is easier to process as json ``--output=json``?

> Maybe why not develop a nextcloud module for ansible or an official nextcloud role ;)

Are you stepping up? :)

**Comment by yodatak** [comment]
I just test , json output do the work but we have to filtrate json so it can be done but i think it's more usefull with the command line but it depend on what we want and i don't know how to code it so :)

**Comment by szaimen** [comment]
Do you still want to implement this? If no, please close this issue. Thanks!

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by skjnldsv** [comment]
`occ app:list --output=json | jq .disabled` already covers that
