### ISSUE TITLE
News app update via cron results in a value != 0 in reserved_at on oc_jobs table

### ISSUE THREAD

**Issue by r3pek** [nextcloud/server#1684]
### Steps to reproduce
1. Install News app
2. configure the update to use the cron.php file

### Expected behaviour
Feeds should update normally

### Actual behaviour
Feeds don't update.
After following the [Feeds not Updating FAQ](https://github.com/nextcloud/news#feeds-are-not-updated), o noticed that the _reserved_at_ value in the _oc_jobs_ tables was different of 0, and, according to the FAQ, it should be 0. So, setting it to 0, and running the cron job locally (sudo -u http /usr/bin/php -f /path/to/cron.php), just never finishes and the value which I previously changed to 0, is now different than 0 again (and the feeds don't update).

### Server configuration
**Operating system**: Arch Linux

**Web server:** nginx 1.10.1

**Database:** MariaDB 10.1.18

**PHP version:** php 7.0.11

**Nextcloud version:** (see Nextcloud admin page) 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from ownCloud 9.0.0 -> NextCloud 9.0.0 -> NC 10.0.0 -> NC 10.0.1

**Where did you install Nextcloud from:** official site

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: 9.0.4
  - notes: 2.0.2
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - passwords: 19
  - provisioning_api: 1.0.0
  - qownnotesapi: 16.09.0
  - serverinfo: 1.1.1
  - shorten: 0.0.15
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - encryption
  - external
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocg4w2lbke5t",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "oc.r3pek.org"
        ],
        "datadirectory": "\/storage\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/oc.r3pek.org",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Lisbon",
        "installed": true,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "loglevel": 2,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chome

**Operating system:** Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"DCx+1dewCXNBMzPZd5Sd","remoteAddr":"","app":"cron","message":"Run OC\\BackgroundJob\\Legacy\\RegularJob job with ID 24","level":0,"time":"2016-10-10T15:06:12+01:00","method":"--","url":"--","user":"--"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Well none zero value on reserved_at means the job didn't finish. Maybe it ran into a time out, inifinite loop or hang up in any other way. Do other cron jobs run correctly? If so this is an issue within the news app and needs to be solved there.

**Comment by r3pek** [comment]
Yes, other cron jobs run normally. It's just this one that blows. And by blows, it actually blows... the memory. I had to up the mem-per-script on php.ini to run it via command line (was 128MB). After I made that, it did finish the refresh so it should be something specific to the News app.

**Comment by r3pek** [comment]
OK, just discard this. It could be just some feed misbehaving. It's working fine now.
