### ISSUE TITLE
Share page does not respect the accessibility settings

### ISSUE THREAD

**Issue by gerroon** [nextcloud/server#16841]
Hi

I use dark theme for my account. I always assumed that the users who are looking at my shares had the same experience. Well appearantly not. The share pages of my shares from  account seems to default to the white theme. Is it possible to make it so that the share page theme is also what the user sets in the accessibility?

I share a lot of photos and videos and white background tends to kill the focus in my personal view.

thanks
thanks

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
