### ISSUE TITLE
Ensure that occ/updater.phar and web are using the same php version

### ISSUE THREAD

**Issue by boydhako** [nextcloud/server#16852]
**Is your feature request related to a problem? Please describe.**
I just updated the install using the `php updater.phar` command and it went fine. Until I pulled up the web page that died stating that my version of PHP is does not meet the required.

**Describe the solution you'd like**
Check the version of PHP that's being used and if it's not within the required to exit error out of updating.

**Describe alternatives you've considered**
Disable ability to do major version updates via CLI and force Web UI updates to validate PHP version being used.

**Additional context**
On shared Bluehost, multiple versions of PHP are installed. The CLI reports using 7.2 while the server is using 7.0.31.

**Comment by kesselb** [comment]
Sounds like a nice feature request :+1: 

Technically there is no simple way to determine the php version used by the webserver from the cli (especially if multiple php versions are available). As workaround we could write the latest used php version by webserver to `config.php` (e.g. from the checksetup method) and compare the version numbers if occ or updater.phar is executed. I don't think that `config.php` is the right place but appconfig is not available to updater.phar so there are no other options (at least none i know). 

So there are some challanges to solve but using a different php versions for cli and webserver looks danger (e.g. different password hashing on php7.2+) and a warning seems valid. But some people might do this on purpose and will ask for a option to disable this check so we should only compare the major version. 

These kind of feature requests are hard to judge. They seems valid from a user perspective but this is also part of your job as admin. It's somehow obvious (at least for me) that using different php versions is not the best idea. 

cc @nextcloud/server-triage for further input :man_shrugging:

**Comment by rullzer** [comment]
There is no way for us to know this.  We could do what @kesselb described but then we'd still be unsure in edge cases.

Bottom line it the responsibility of the admin to ensure this works. Mixing php versions can indeed lead to weird issues with code that is no compatible or the new password hashing etc.
