### ISSUE TITLE
Add support for getting direct links

### ISSUE THREAD

**Issue by NightMachinary** [nextcloud/server#16858]
When I try to download files shared on Nextcloud instances via `aria2c`, I get the attached file. It'd be nice if Nextcloud was more shell-friendly.
[downloadShare.zip](https://github.com/nextcloud/server/files/3537976/downloadShare.zip)

**Comment by kesselb** [comment]
Good idea :+1: 

It's possible to download a share by appending /download but a redirect if user agent is wget, curl or aria2 would be nice.

Probably a bit tricky to implement because shares can have a password. We need to return 401 for such shares then.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by NightMachinary** [comment]
I no longer use `nextcloud`; I just use a static HTTP file server. Much lighter, when `nextcloud`'s features are not needed.
