### ISSUE TITLE
End-to-End Encryption error in nextcloud 16.0.x

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#16857]
End-to-End Encryption turns out to be incompatible with nextcloud 16.0.x why?

From application entry not verified. why to date this application by warning in red?

![63599170-53650480-c5c1-11e9-9192-5d07d9dd3ca5](https://user-images.githubusercontent.com/35575744/63646867-b10c6480-c719-11e9-9fea-11d7e9d51458.png)

**Comment by szaimen** [comment]
https://github.com/nextcloud/end_to_end_encryption/issues/108#issuecomment-505347157
