### ISSUE TITLE
Expiry date/period for device passwords

### ISSUE THREAD

**Issue by ohreally** [nextcloud/server#16868]
**Is your feature request related to a problem? Please describe.**
Not really a problem; more like a nuisance. Still, Nextcloud could help me solve it.
My list of device passwords often contains too many passwords that should no longer exist. On the one hand this is messy, and on the other hand this isn't a good idea security-wise.

**Describe the solution you'd like**
I would like to be able to set an expiry period for passwords that are unused. Example: "Delete this password if not used for 4 weeks.".
Obviously, a default value would be nice ("Unless set otherwise, always expire passwords after X weeks of not being used.").

And I would like to be able to set an exact date for expiry. Example: my current work contract is valid until 31 December 2019, so the passwords for desktop sync client and webdav access at work should expire the evening of 31 December 2019.

**Describe alternatives you've considered**
Currently I create an appointment in my calendar for the day after my work contract ends (I always work temporary jobs; it allows me to travel). This then also triggers me to check the list to see whether there are any passwords that have not been used for a while.

**Additional context**
Thank you for considering.

**Comment by szaimen** [comment]
cc @nextcloud/security is this something that makes sense security wise or should it already work?
