### ISSUE TITLE
Very high resources usage after recent updates

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#16860]
After recent updates (can't tell if it was 16.0.3 or 16.04 exactly, but one of these) server resource usage went crazy.

I have 2 NC installations. 1st installation for my personal needs, so I'm the only user. I use it to only auto-upload photos (with the help of NC client for Android) and sync calendars/contacts (with the help of NC Calendar/Contacts plugins and DavX for Android).

2nd installation has more plugins and 6 users total, 3 of which are active. They mainly use NC via browser to upload files from time to time.

My server is configured to send alert when some app uses more than 600 MB of RAM, and it was never a problem. Until recent updates. Now, I receive alerts about NC using 700+ MB RAM about 50 times a day. It happens for both installations, and very often it happens when I don't even use NC (for example, when I sleep). Usage goes high randomly - sometimes no alerts are sent for hours (even if I use NC), sometimes alerts are sent every 15 minutes for several hours in a row.

Is it normal that "sleeping" installation with only 1 user needs that much resources after updates? I found a similar issue related to resources at https://github.com/nextcloud/server/issues/16054 but I'm not sure if it's related. I also use CentOS (v6) if that helps.

**Comment by benneti** [comment]
The same happened for me, I think it started with version 16.0.4

**Comment by kesselb** [comment]
> Is it normal that "sleeping" installation with only 1 user needs that much resources after updates

For such questions / discussion https://help.nextcloud.com is usually the better place. I did not notice  more reports about this topic in the last weeks.

> app uses more than 600 MB of RAM

Do you monitor this on a user base (like a process with user1 consumes more than 600 mb of ram)? 

> alerts are sent every 15 minutes for several hours in a row.

Are you using the system cron? We recommend to run it every 15 minutes. Is the alert related to the cron?

**Comment by toxpal** [comment]
Thanks for the response.

> Do you monitor this on a user base (like a process with user1 consumes more than 600 mb of ram)?

Yes, this is correct. I monitor this on a user base. Just to clarity, each user on server only has only 1 script installed/running.

> Are you using the system cron? We recommend to run it every 15 minutes. Is the alert related to the cron?

I use AJAX cron. High resource usage is not related to cron. As I mentioned in first post, _Usage goes high randomly - sometimes no alerts are sent for hours (even if I use NC), sometimes alerts are sent every 15 minutes for several hours in a row._

**Comment by benneti** [comment]
I too checked whether it is correlated with cron running and can confirm it is not. (I use system cron.)

**Comment by kesselb** [comment]
Without the issue template i can only guess (if you want to add it please edit your post). Maybe there is something in your logs, some app is responsible (e.g. the news app needs some resources if you have many feeds), sometimes a php update could be the reason or a new bug in nextcloud. 

If you are able to track this down to a particular action i'm happy to look into but for such a general issue don't know where to start :man_shrugging:

**Comment by benneti** [comment]
### Steps to reproduce
1. Nextcloud 16.0.4 on apache2 with mariadb on a system with
2. let the server run for a few hours
3. wait until the swapping starts

### Expected behaviour
Bevore the latest update the ram usage did not spike like that.

### Actual behaviour
High ram usage that results in the server being unresponsive and timeout errors in the sync clients.
Looking into htop it seems like the ram usage is coming from an apache2 process.

### Server configuration

**Operating system**:
Debian 4.19.67-2+deb10u1 (armv5tel)

**Web server:**
apache2 2.4.38-3+deb10u1 armel

**Database:**
mariadb (innodb)

**PHP version:**
php7.3 (7.3.9-1~deb10u1)


**Nextcloud version:** (see Nextcloud admin page)
16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
update (starting from version 14 if I remember correctly)

**Where did you install Nextcloud from:**
official zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bookmarks: 2.1.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - drop_account: 0.1.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - music: 0.10.1
  - news: 14.0.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.tissot.de\/nextcloud",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "3",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox/Safari/Nextcloud client

**Operating system:**
Linux/MacOS

### Logs
#### [Web server error log](https://gist.github.com/benneti/2a42b04626f4cbeac3e7da49f3b5107a#file-apache2-error-log)

#### [Nextcloud log (data/nextcloud.log)](https://gist.githubusercontent.com/benneti/2a42b04626f4cbeac3e7da49f3b5107a/raw/1949dbe4103c02b1d76118b956a5b0a9859b440d/nextcloud.log)

**Comment by kesselb** [comment]
1) Please provide some details about your system. CPU and Memory for example. How does apache2 runs php (mod_php, php-fpm, etc.).

2) There are many errors related to mariadb (e.g.  `General error: 2006 MySQL server has gone away` or `SQLSTATE[HY000] [1040] Too many connections`). Is mariadb running out of memory?

**Comment by benneti** [comment]
1. Very underpowered system: CPU Marvell 6282 1.6GHz 512MB DDRIII RAM 
and php is run via mod_php.
2. Yeah, but these are kinda expected as mariadb is set up not to exceed a total memory of about 450MB.

Thank you for looking into it.

**Comment by kesselb** [comment]
It looks like (from the logfile) the situation got worse after the upgrade to 16. I remember that the recommendations app needs more resources.

**Comment by benneti** [comment]
Thanck you, I will try wether disabling the app "fixes" the problem and report back.

**Comment by benneti** [comment]
So I disabled it and the spikes are still happening.

**Comment by kesselb** [comment]
I think we found the issue at https://github.com/nextcloud/server/issues/17447.

**Comment by kesselb** [comment]
Could you check if https://github.com/nextcloud/server/issues/17447 or https://github.com/nextcloud/server/issues/17241 helps?

**Comment by benneti** [comment]
Sorry for the late reply, I changed my server completely, so I can not check whether they help or not.
