### ISSUE TITLE
Error installing custom app after extract it to /apps/

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#16869]
### Steps to reproduce
I moved an app into the /apps/ folder and extracted it. Then I clicked "Enable" on the Settings/App page in my Nextcloud installation

### Expected behaviour
The app is being enabled

### Actual behaviour
I got an error message that the app could not be installed because it could not been downloaded from the AppStore. I generated the skeleton from within the AppStore but I never downloaded the app to the AppStore.
The subpoint "Server configuration detail" lists my app as activated (user_imap) but it isn't...?

## Server configuration detail

**Operating system:** Linux 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.6.44

**PHP version:** 

7.2.19
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dom, hash, filter, ftp, gettext, SPL, iconv, json, mbstring, posix, Reflection, session, standard, shmop, SimpleXML, soap, exif, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, propro, raphf, http, mysqlnd, PDO, curl, dba, fileinfo, gd, gender, gmp, htscanner, imagick, imap, interbase, intl, ldap, mailparse, mongodb, mysqli, OAuth, odbc, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, pspell, recode, sodium, SourceGuardian, sqlite3, tidy, xsl, ionCube Loader

**Nextcloud version:** 15.0.11 - 15.0.11.1

**Updated from an older Nextcloud/ownCloud or fresh install:** From 14.x

**Where did you install Nextcloud from:** Web based updater

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - admin_audit: 1.5.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - contacts: 3.1.3
 - dav: 1.8.2
 - external: 3.2.0
 - federatedfilesharing: 1.5.0
 - files: 1.10.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - firstrunwizard: 2.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - rainloop: 6.0.3
 - serverinfo: 1.5.0
 - sharerenamer: 2.7.0
 - shorten: 0.0.15
 - support: 1.0.0
 - systemtags: 1.5.0
 - tasks: 0.11.1
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - workflowengine: 1.5.0
Disabled:
 - activity
 - activitydefaults
 - admin_notifications
 - comments
 - disablerememberlogin
 - encryption
 - federation
 - files_automatedtagging
 - files_clipboard
 - files_external
 - files_texteditor
 - files_videoplayer
 - gallery
 - mail
 - sharebymail
 - survey_client
 - theme_switcher-2.1
 - user_external
 - user_imap
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "15.0.11.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "O39jE_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "imap_host": "***REMOVED SENSITIVE VALUE***",
    "imap_inHost": "***REMOVED SENSITIVE VALUE***",
    "imap_inPort": 143,
    "imap_inSSL": "tls",
    "imap_outHost": "***REMOVED SENSITIVE VALUE***",
    "imap_outPort": 587,
    "imap_outSSL": "tls",
    "imap_ud_host": "https:\/\/***REMOVED SENSITIVE VALUE***",
    "appstore.experimental.enabled": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "tempdirectory": "\/www\/htdocs\/w013e4e2\/die-herzogs.com\/cloud\/STATIC_DATA_DIR\/tmp",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** IMAP. It worked fine until version 14

## Client configuration

**Browser:** Firefox 60.0 

**Operating system:** Win7

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"XWPWA1UNgrgAAH0neSIAAAAB","level":3,"time":"2019-08-26T12:52:19+00:00","remoteAddr":"165.225.73.84","user":"admin","app":"settings","method":"POST","url":"\/index.php\/settings\/apps\/enable","message":{"Exception":"Exception","Message":"Could not download app userimap","Code":0,"Trace":[{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/settings\/Controller\/AppSettingsController.php","line":438,"function":"downloadApp","class":"OC\\Installer","type":"->","args":["userimap"]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"enableApps","class":"OC\\Settings\\Controller\\AppSettingsController","type":"->","args":[["userimap"],[]]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/private\/AppFramework\/App.php","line":118,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Settings\\Controller\\AppSettingsController"},"enableApps"]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Settings\\Controller\\AppSettingsController","enableApps",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"settings.AppSettings.enableApps"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"settings.AppSettings.enableApps"}]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"settings.AppSettings.enableApps"}]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/base.php","line":987,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/settings\/apps\/enable"]},{"file":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/www\/htdocs\/w013e4e2\/MYDOMAIN\/cloud\/LIVE\/lib\/private\/Installer.php","Line":352,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.11.1"}
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by alve89** [comment]
I'm also not able to delete the app from within the apps-section of the site.

`{"reqId":"XWP8tVUNgrgAAGY8jsEAAAAM","level":3,"time":"2019-08-26T15:37:25+00:00","remoteAddr":"165.225.73.84","user":"admin","app":"core","method":"GET","url":"\/index.php\/settings\/apps\/uninstall\/userimap","message":"can't remove app userimap. It is not installed.","userAgent":"Mozilla\/5.0 (Windows NT 6.1; WOW64; rv:60.0) Gecko\/20100101 Firefox\/60.0","version":"15.0.11.1"}`

**Comment by kesselb** [comment]
I guess the app folder is derived from the app id. Try to rename `user_imap` to `userimap`.

**Comment by alve89** [comment]
I tried that and now I can enable it but I still get the same error message that the user backend could not be found:

`{"reqId":"XWQ6RVUNgrgAAEv@IDAAAAAK","level":3,"time":"2019-08-26T20:00:05+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/index.php\/settings\/apps\/installed\/userimap","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
{"reqId":"XWQ6SFUNgrgAAEv@IDEAAAAK","level":3,"time":"2019-08-26T20:00:08+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/index.php\/core\/js\/oc.js?v=8743f525","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
{"reqId":"XWQ6SFUNgrgAAEv@IDIAAAAK","level":3,"time":"2019-08-26T20:00:08+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v2\/notifications","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
{"reqId":"XWQ6SFUNgrgAADaL998AAAAD","level":3,"time":"2019-08-26T20:00:08+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/cron.php","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
{"reqId":"XWQ6SFUNgrgAAElxHG8AAAAH","level":3,"time":"2019-08-26T20:00:08+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/index.php\/settings\/apps\/categories","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
{"reqId":"XWQ6SFUNgrgAAElyHbkAAAAI","level":3,"time":"2019-08-26T20:00:08+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/index.php\/settings\/apps\/list","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
{"reqId":"XWQ6SFUNgrgAACQCyK0AAAAV","level":3,"time":"2019-08-26T20:00:08+00:00","remoteAddr":"95.91.240.247","user":"admin","app":"core","method":"GET","url":"\/ocs\/v2.php\/cloud\/groups?offset=0&search=&limit=5","message":"User backend OC_User_IMAP_wUD not found.","userAgent":"Mozilla\/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit\/605.1.15 (KHTML, like Gecko) Version\/12.1.1 Safari\/605.1.15","version":"15.0.11.1"}
`

and I really don't get it because the app worked until the upgrade properly.

I'm using this in config.php
`  'user_backends' =>
  array (
    0 =>
    array (
      'class' => 'OC_User_IMAP_wUD',
      'arguments' =>
      array (
        0 => '{w013e4e2.kasserver.com:143}',
      ),
    ),
  ),`

and this in my appinfo/app.php
`OC::$CLASSPATH['OC_User_IMAP_wUD']='userimap/imap.php';`

The files base.php and imap.php are placed in userimap/lib/ (as in user_external app). And finally imap.php contains
`class OC_User_IMAP_wUD extends \OCA\userimap\Base {......}`

so I don't understand why the class can't be found. Do you see a problem here?

**Comment by alve89** [comment]
That worked for me, thanks. But now I don't know how to get the system config values because the "old" way `\OCP\Config::getSystemValue(xxx)` doesn't work anymore and I don't really get how to implement [this from documentation](https://docs.nextcloud.com/server/15/developer_manual/app/storage/configuration.html)?
