### ISSUE TITLE
Recent files is missing entries

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#16876]
With https://github.com/nextcloud/server/pull/16424 some entries in the recent files might be missing. This issue is to keep track of further improving the situation:

> This makes sure we do not get more than 3 times the limit we search for
or more than 5 queries.

> This means we might miss some recent entries but we should fix that
separatly. This is just to make sure the load on the DB stays sane.

cc @rullzer

**Comment by rullzer** [comment]
I actually have a patch but it is blocked currently by https://github.com/doctrine/dbal/issues/3640

**Comment by ChristophWurst** [comment]
Considered for 3.0 but I've asked about a backport https://github.com/doctrine/dbal/pull/3772#issuecomment-577285095

**Comment by ChristophWurst** [comment]
Waiting for https://github.com/doctrine/dbal/pull/3843, then we can upgrade to 2.10.

**Comment by ChristophWurst** [comment]
> I actually have a patch but it is blocked currently by [doctrine/dbal#3640](https://github.com/doctrine/dbal/issues/3640)

Updated in https://github.com/nextcloud/server/pull/21208

**Comment by ChristophWurst** [comment]
@rullzer what is the plan with this?
