### ISSUE TITLE
Option to automatically inform people about changes of shares

### ISSUE THREAD

**Issue by UserXH726** [nextcloud/server#16873]
Hello,
I wish an option in the share-menu, that activates an automatic inform routine which informs the users, with which I shared a folder, when a new files created, files changed or files deleted.
Or does this function already exists and i overlooked it.

**Comment by wiswedel** [comment]
> Or does this function already exists and i overlooked it.

Try this:

![image](https://user-images.githubusercontent.com/1804221/63757391-421a4180-c8ba-11e9-9965-3a3ee124e8bf.png)

**Comment by UserXH726** [comment]
Okay, thank you.
But I missing the option that I get actitivity information over the notification-center.
I opened a issue [here](https://github.com/nextcloud/activity/issues/223)
