### ISSUE TITLE
Voice in Italian not centered in the button stores the credentials

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#16878]
In version 16.0.4 localized in Italian, when you go to the setting menu -> basic setting -> mail server the voice saves credentials does not come out completely written in the button area can you fix it? I attach screenshot
![Immagine](https://user-images.githubusercontent.com/35575744/63754743-a8e92c00-c8b5-11e9-85aa-aac12dadfdf3.png)

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by GretaD** [comment]
This problem happens in all the languages that have long words. @nextcloud/designers what do you propose, longer button, or this?
![credenziali](https://user-images.githubusercontent.com/12728974/63765809-1f902480-c8ca-11e9-89e5-ccd0a87d19da.png)

**Comment by madalinignisca** [comment]
Why were buttons constrain on width from the beginning? Also, using long strings on buttons is also something hard to understand why. Buttons should have a simple action related string like (in english) "OK", "Send", "Cancel", "Reset" etc. and have some explanation block that helps people understand what will this form/input/action will do.

**Comment by GretaD** [comment]
TBH I'm a fan of simple actions too. In this case - SAVE would be enough

**Comment by tigernero79** [comment]
Ok for save in italiano language for me

**Comment by jancborchardt** [comment]
Yep @GretaD, "Save" is enough in this case as a label. But also, there’s an issue in the CSS which limits the width:
`settings/css/settings.scss` line 1196 should not be only `input`, but `input:not([type='button'])` so the button is not restricted.

------------------

For the record though: Normally like in modals or other actions, short actions like "OK" and "Cancel" and "Save" are difficult to understand. Instead it should spell out what it relates to like "Move file" or "Delete folder" etc. Nothing is worse than a lot of text in a modal and having "OK" "Cancel", or even the dreaded:
> Do you want to cancel the installation?
> [ Cancel ]      [ Abort ]

**Comment by GretaD** [comment]
> Yep @GretaD, "Save" is enough in this case as a label. But also, there’s an issue in the CSS which limits the width:
> `settings/css/settings.scss` line 1196 should not be only `input`, but `input:not([type='button'])` so the button is not restricted.
So, just for the record, should I go ahead and change the word into _save_, but also change the scss file, just in case if in some languages the word _save_ its still long?
> For the record though: Normally like in modals or other actions, short actions like "OK" and "Cancel" and "Save" are difficult to understand. Instead it should spell out what it relates to like "Move file" or "Delete folder" etc. Nothing is worse than a lot of text in a modal and having "OK" "Cancel", or even the dreaded:
> 
> > Do you want to cancel the installation?
> > [ Cancel ]      [ Abort ]
This is evil :)

**Comment by jancborchardt** [comment]
> So, just for the record, should I go ahead and change the word into save, but also change the scss file, just in case if in some languages the word save its still long?

Yup, that sounds good! :) :+1:

**Comment by madalinignisca** [comment]
> Do you want to cancel the installation?
> [ Cancel ] [ Abort ]

Could be better:
```
Do you want to cancel the installation?
[ No ] [ Yes ]
```
It's just about choosing the best words. You did remind me of some app.

**Comment by jancborchardt** [comment]
The best option is:

> Do you want to cancel the installation?
> [ Resume ]     [ Cancel installation ]

As said – descriptive labels. "Yes" and "No" necessitate reading the entire text of the modal, something which is rarely done and then misclicks happen.
