### ISSUE TITLE
add tags in logs

### ISSUE THREAD

**Issue by lalebarde** [nextcloud/server#16885]
**Is your feature request related to a problem? Please describe.**
We would like to alert suspect activities on NextCloud usage with a SIEM, as for example:

- DLP

- Personal use, possibly with illegal files

Alerting would depends on data criticality set by users with the help of tags. So we would need that tags are included into the logs. For example: 'Confidential'

**Describe the solution you'd like**

- For every log regarding a file transaction, add into the log the tags associated to the file

- Enable to define default tags

- Enable to set tags easily

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
