### ISSUE TITLE
Cannot create or access to folder with name "css"

### ISSUE THREAD

**Issue by Dragofafmir** [nextcloud/server#16887]
### Steps to reproduce
1. Try to create a folder with name "css" or try to access to a folder with name "css"

### Expected behaviour
If I want to create a folder with name is "css", it should be created. Same if I want access to a folder with name "css".

### Actual behaviour
If I want to create a folder with name "css" : 
![1566911880](https://user-images.githubusercontent.com/14051341/63774781-43f5fc00-c8de-11e9-82a8-3a45d4deeb19.png)
If I want to access a folder with name "css" : 
![1566912110](https://user-images.githubusercontent.com/14051341/63774859-7142aa00-c8de-11e9-9948-34cfe1ac9089.png)
On the windows client :
![1566912186](https://user-images.githubusercontent.com/14051341/63774933-9a633a80-c8de-11e9-86a9-4c2858649ebd.png)

### Server configuration

**Operating system**: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-54-generic x86_64)

**Web server:** Nginx 1.14.2

**Database:** 10.1.41-MariaDB

**PHP version:** 7.2.19

**Nextcloud version:** 16.0.2.1

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - apporder: 0.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - drawio: 0.9.3
  - extract: 1.2.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_downloadactivity: 1.5.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - impersonate: 1.3.0
  - keeweb: 0.5.1
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 2.4.0
  - password_policy: 1.6.0
  - provisioning_api: 1.6.0
  - quota_warning: 1.5.0
  - rainloop: 6.0.3
  - recommendations: 0.4.0
  - secsignid: 0.2.3
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - sharerenamer: 2.7.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_admin: 0.4.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_nextcloud_notification: 1.1.2
  - twofactor_totp: 3.0.1
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - viewer: 1.0.0
  - workflowengine: 1.6.0
Disabled:
  - accessibility
  - encryption
  - files_external
  - files_markdown
  - firstrunwizard
  - flowupload
  - news
  - nextcloud_announcements
  - polls
  - privacy
  - scanner
  - spreed
  - support
  - survey_client
  - tasks
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.2.1",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "stable",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app_install_overwrite": [
            "files_downloadactivity"
        ],
        "default_language": "fr",
        "defaultapp": "files",
        "knowledgebaseenabled": false,
        "skeletondirectory": "",
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto"
    }
}
```
</details>

**Are you using encryption:** no

### Client configuration
**Browser:** any

**Operating system:** Windows 10 v1903

#### Web server error log
<details>
<summary>Web server error log</summary>

```
no errors in the logs
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
no errors in the logs related to this issue
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
If I want to create a folder with name "css" : 
![1566911880](https://user-images.githubusercontent.com/14051341/63774781-43f5fc00-c8de-11e9-82a8-3a45d4deeb19.png)
If I want to access a folder with name "css" : 
![1566912110](https://user-images.githubusercontent.com/14051341/63774859-7142aa00-c8de-11e9-9948-34cfe1ac9089.png)
On the windows client :
![1566912186](https://user-images.githubusercontent.com/14051341/63774933-9a633a80-c8de-11e9-86a9-4c2858649ebd.png)
```
</details>

**Comment by Dragofafmir** [comment]
Ok... I find someting. If I remove this Nginx directives, it solves the problem :

ssl_prefer_server_ciphers On;
ssl_protocols TLSv1.1 TLSv1.2;
ssl_ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:ECDH+3DES:DH+3DES:RSA+AESGCM:RSA+AES:RSA+3DES:!aNULL:!MD5;

gzip_proxied any;
# enable gzip compression
gzip on;
gzip_min_length 20;
gzip_buffers 4 32k;
gzip_types text/plain text/javascript application/javascript application/x-javascript text/xml text/css application/js;
gzip_vary on;
location ~* .(ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|css|rss|atom|js|jpg|jpeg|json|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf|OGG|OGV|SVG|SVGZ|EOT|OTF|WOFF|MP4|TTF|CSS|RSS|ATOM|JS|JPG|JPEG|JSON|GIF|PNG|ICO|ZIP|TGZ|GZ|RAR|BZ2|DOC|XLS|EXE|PPT|TAR|MID|MIDI|WAV|BMP|RTF)$ {
	expires max; log_not_found off;
	# time out settings
	proxy_connect_timeout 3600s;
	proxy_send_timeout   3600s;
	proxy_read_timeout   3600s;
	fastcgi_read_timeout 3600s;
	# webdav rewrite
	rewrite ^/.well-known/carddav /remote.php/dav/ permanent;
	rewrite ^/.well-known/caldav /remote.php/dav/ permanent;
	rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
	rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;
}


if anyone has an idea why it's causing this problem ...

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
