### ISSUE TITLE
Unable to upgrade from 15.0.11 to 16.0.4

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#16888]
### Steps to reproduce
Click Update in settings->administration

OR

run php updater.phar in terminal
-> continue update [y/n]: y
-> "Update of code successful"
Should the "occ upgrade command be executed? [y/n]: n (because I need to run php directly to use the latest version [>=7.x])
->cd ..
-> php73 (for PHP 7.3) occ upgrade
-> "Nextcloud is already latest version"

If I try the commands in OCC Web app without special PHP versions it doesn't work neither.

### Expected behaviour
Update is running properly

### Actual behaviour
The checkmarks at the single checking steps are set all at once and instantly (both web updater and terminal). Then I click "Back to Nextcloud to finish update" OR running php occ upgrade in terminal and both isn't working.

## Server configuration detail

**Operating system:** Linux 3.13.0-170-generic #220-Ubuntu SMP Thu May 9 12:40:49 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.6.44

**PHP version:** 

7.3.6-nmm1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, calendar, ctype, dom, hash, filter, ftp, gettext, SPL, iconv, json, mbstring, posix, Reflection, session, standard, shmop, SimpleXML, soap, exif, sysvsem, sysvshm, tokenizer, wddx, xml, xmlreader, xmlwriter, zip, cgi-fcgi, propro, raphf, http, mysqlnd, PDO, curl, dba, fileinfo, gd, gender, gmp, htscanner, imagick, imap, interbase, intl, ldap, mailparse, mongodb, mysqli, OAuth, odbc, pdo_dblib, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, pspell, recode, sodium, sqlite3, tidy, xsl, ionCube Loader

**Nextcloud version:** 15.0.11 - 15.0.11.1

**Updated from an older Nextcloud/ownCloud or fresh install:** From 14.x

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/doc/admin/_static/img/note_pencil.svg] => Array
                        (
                            [expected] => 78b9df57afe9468145e6e375cd1f61274b269b9c3019726a99e043ae952367acf53cf471cbc5b3dcca2e68367c2c4422d4a9f9a9fdbb11f9b962845ac77857de
                            [current] => 97117ce2827cc1b742678b52fc100de1e7d3fdb1adeea04a301c012e7f95b66e10a369c6a83ba89a707c4232b5e31fba3d5e58b0e0d970f22031d0704eebb5a9
                        )

                    [core/doc/admin/_static/img/warning.svg] => Array
                        (
                            [expected] => e8647b47ef1531b8c2fcdd51f76996fe85476467fc694540f3dcf8ce7e7da489e99edae5a158742da71c07dc09ccfaf721f01c1c4bda3f5bae9b711981b71a1b
                            [current] => 85687f19cf204716e9b1c608682aa22c045b6f8284a3496db07f13200952491bfea54deee7ef11115c0dedfd87443c7022ef05792892a8a984866752c8ec5726
                        )

                    [core/vendor/jsTimezoneDetect/jstz.js] => Array
                        (
                            [expected] => ece74dd6f5fc9587cf167dd17df51b66f70bd711f445da8d1d21bb1b0570f3c97b25d3ece110b08e2f2b294369d9b775cc169b666840a5b769ba338aa6d73d48
                            [current] => beae737d18aae6e8c5fdfb0bf3389b687ec746e6b334185710cc5b8f45b73b3c57442db541807ab440b55517ef2d138f4c40148abafcb6462481016b617e1f53
                        )

                )
        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.1.0
 - admin_audit: 1.5.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.6.5
 - cloud_federation_api: 0.1.0
 - contacts: 3.1.3
 - dav: 1.8.2
 - external: 3.2.0
 - federatedfilesharing: 1.5.0
 - files: 1.10.0
 - files_pdfviewer: 1.4.0
 - files_sharing: 1.7.0
 - files_trashbin: 1.5.0
 - files_versions: 1.8.0
 - firstrunwizard: 2.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.0.0
 - lookup_server_connector: 1.3.0
 - nextcloud_announcements: 1.4.0
 - notifications: 2.3.0
 - oauth2: 1.3.0
 - occweb: 0.0.4
 - password_policy: 1.5.0
 - provisioning_api: 1.5.0
 - rainloop: 6.0.3
 - serverinfo: 1.5.0
 - sharerenamer: 2.7.0
 - shorten: 0.0.15
 - support: 1.0.0
 - systemtags: 1.5.0
 - tasks: 0.11.1
 - theming: 1.6.0
 - twofactor_backupcodes: 1.4.1
 - updatenotification: 1.5.0
 - userimap: 0.0.1
 - workflowengine: 1.5.0
Disabled:
 - activity
 - activitydefaults
 - admin_notifications
 - comments
 - disablerememberlogin
 - encryption
 - federation
 - files_automatedtagging
 - files_clipboard
 - files_external
 - files_texteditor
 - files_videoplayer
 - gallery
 - mail
 - sharebymail
 - survey_client
 - theme_switcher-2.1
 - user_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "update.cloud.MYDOMAIN",
        "cloud.MYDOMAIN"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/update.MYDOMAIN",
    "overwriteprotocol": "https",
    "dbtype": "mysql",
    "version": "15.0.11.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "O39jE_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "imap_host": "MYDOMAIN",
    "imap_inHost": "XXXX.kasserver.com",
    "imap_inPort": 143,
    "imap_inSSL": "tls",
    "imap_outHost": "XXXX.kasserver.com",
    "imap_outPort": 587,
    "imap_outSSL": "tls",
    "imap_ud_host": "https:\/\/ud.MYDOMAIN",
    "appstore.experimental.enabled": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "updater.release.channel": "stable",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "sendmail",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "tempdirectory": "\/www\/htdocs\/xxxx\/MYDOMAIN\/cloud\/STATIC_DATA_DIR\/tmp",
    "updater.secret": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "pipe"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Firefox 60.0 

**Operating system:** Win7 x64

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

EMPTY!
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
Mind to share the permissions of your nextcloud directory? `ls -al nextcloud`. Looks like the updater does not replace the files.

**Comment by alve89** [comment]
Actually this could not be the problem because it always worked. 
In the meanwhile I did it myself and updated everything,. So I can’t tell what the problem was but I fixed it.

**Comment by baoang** [comment]
Actually I want to upgrade from 15.0.11, my current ver to 15.0.12, the current official release of v15, rather than directly to v16.0.4, but the openUpdater in Nextcloud UI seems skipped v15.0.12. Any workaround because I for the time being just want to keep with v15?

**Comment by shawe** [comment]
> Actually I want to upgrade from 15.0.11, my current ver to 15.0.12, the current official release of v15, rather than directly to v16.0.4, but the openUpdater in Nextcloud UI seems skipped v15.0.12. Any workaround because I for the time being just want to keep with v15?

Same problem here. The only error that I can found is this on Apache error log:

Failed opening required '/home/XXX/public_html/cloud/apps/settings/composer/composer/autoload_real.php'
And yes, file not exists.
```

# /opt/cpanel/ea-php71/root/usr/bin/php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
# /opt/cpanel/ea-php71/root/usr/bin/php occ app:update --all
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
# 

```
