### ISSUE TITLE
Please let us remove the "/apps"-part of the URL

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#16889]
**Is your feature request related to a problem? Please describe.**
I think the shorter an URL is, the better it is. 
Also for sharing links e.g. from the gallery app or other apps, the links look much cleaner then.

**Describe the solution you'd like**
Please let us remove the "/apps"-part of the URL

**Describe alternatives you've considered**
Maybe add an option to config.php to remove the "/apps"-part of the URL.

**Additional context**
An example for that (also with enabled pretty-URLs) would be: 
The URL of the files app is then "https://domain.com/files/..." and not "https://domain.com/apps/files/...".
BTW: the settings are (also with enabled pretty-URLs) already acessible over "https://domain.com/settings".

**Comment by kesselb** [comment]
You cannot assign the same url to both app folders. What are you trying to achieve? I don't think its possible to change the urls like that.

**Comment by szaimen** [comment]
I just want to ged rid of unnecessary parts of the URL.
The strange thing is, that also just changing the first or the second part to:
```
            "url": "\/",
```
does not result in making the files app accessible over "https://domain.com/index.php/files/..."
so I think it is not respecting this entry at all.
Also other not official apps are not accessible over "https://domain.com/index.php/extra-apps/..." as I would expect it (while looking at the configuration) but also accessible over "https://domain.com/index.php/apps/..." which is really strange to me.
Do you have an explanation for that?

**Comment by kesselb** [comment]
> Do you have an explanation for that?

Yes. Every request through nextcloud is processed by `index.php` and /apps/appId is the route for every app. It's fixed and isn't  intended to be changed.

**Comment by szaimen** [comment]
okay, then please consider my issue as a feature-request.

**Comment by kesselb** [comment]
Would you mind to edit your first post and add https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md

I don't see the point of changing /apps/ to / which can lead to conflicts and requires a blacklist of app names but you must have a good reason if you create a issue here :)

**Comment by szaimen** [comment]
Yes, I have. 👍
My first post is now edited.

**Comment by szaimen** [comment]
@kesselb When after https://github.com/nextcloud/server/pull/17182 everything is an app now, why not removing the `/apps` part altogether?
