### ISSUE TITLE
Unable to login with Webkit on Android on git master

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#1689]
### Steps to reproduce
1. Use any Android Webkit-powered browser (Chrome, Stock, Gello, Opera)
2. Try to login
### Expected behaviour

Login successful
### Actual behaviour

Redirected to login view, no error message.

This **doesn't** happen with Firefox on Android, neither with Chrome or any browser on desktop.

The console log shows : 

```
ReferenceError: oc_appconfig is not defined
```

and points to https://github.com/nextcloud/server/blob/master/core/js/shareconfigmodel.js#L24
All the files are properly fetched.
### Server configuration

**Operating system**: Android 6.0.1 (Cyanogen OS)

**Web server:** Build-in server

**Database:** SQLite

**PHP version:** 7.0.11-1, but it happens too with 5.6

**Nextcloud version:** (see Nextcloud admin page) git master

**Updated from an older Nextcloud/ownCloud or fresh install:** doesn't matter

**Where did you install Nextcloud from:** git
### Client configuration

**Browser:** Chrome Beta 54, Gello 42, Opera 37

**Operating system:** Android 6.0.1
#### Server log

Current user is not logged in
#### Nextcloud log (data/nextcloud.log)

```
{"reqId":"13CArjahgomj\/Dyxfd6P","remoteAddr":"192.168.1.31","app":"no app in context","message":"Current user is not logged in","level":0,"time":"2016-10-11T07:55:51+00:00","method":"GET","url":"\/index.php\/apps\/files\/","user":"--","version":"9.2.0.4"}
```
#### Browser log

```
ReferenceError: oc_appconfig is not defined
```

**Comment by MorrisJobke** [comment]
Works here for me in Chrome on Android, I only have the problem with Opera on Android. Maybe my chrome is too new and already uses the Blink engine.

**Comment by MorrisJobke** [comment]
I use Chrome 53.0.2785.124 on my Nexus 7 with Android 6.0.1

**Comment by MorrisJobke** [comment]
> Works here for me in Chrome on Android, I only have the problem with Opera on Android. Maybe my chrome is too new and already uses the Blink engine.

I just retested with latest master and Opera and it is now working.

Please reopen if this issue still happens for you
