### ISSUE TITLE
Tags are lost when copying files

### ISSUE THREAD

**Issue by sophocles1942** [nextcloud/server#16907]
### Steps to reproduce
1.Upload files to NextCloud and tag them
2. Copy the files into a random location/folder
3. Tags disappear on the new copied files
Apparently this has been an issue before? I could not find a resolution to this:
https://help.nextcloud.com/t/tags-are-lost-for-copies-of-files/52085

### Expected behaviour
I believe the tags should be copied over?

### Actual behaviour
The tags are missing from the copied files.

### Server configuration

**Operating system**:
CentOS 6.10

**Web server:**
Nginx/Apache

**Database:**
10.3.17-MariaDB

**PHP version:**
7.3.8

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**
Nextcloud.com Download install script

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Just the default apps 
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '****',
  'passwordsalt' => '******',
  'secret' => '*******',
  'trusted_domains' => 
  array (
    0 => '*****',
	1 => '********',
	2 => '******',
  ),
  'datadirectory' => '/home/******/public_html/data',
  'overwrite.cli.url' => 'https://*******.com',
  'dbtype' => 'mysql',
  'version' => '16.0.3.0',
  'dbname' => '*******',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '**********',
  'dbpassword' => '*********',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** This issue seems to be appearing on the latest versions of Chrome, FireFox, and Edge.

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing about this error appears
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing about this error appears
```
</details>

**Comment by rspierenburg** [comment]
Has there been no update on this? Or is this by design?

**Comment by creshal** [comment]
I'd argue as well that this is should be considered a bug, we make heavy use of tags and effectively cannot copy files at all unless this gets fixed.

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
