### ISSUE TITLE
Password policy error message stays open and overlaying after closing input field

### ISSUE THREAD

**Issue by itkama** [nextcloud/server#16914]
Wenn man versucht einen Link zu teilen und dieser mit einem Passwort versehen muss, kommt (wenn das Passwort noch nicht den Anforderungen entspricht) die Meldung "Das Passwort muss einen Klein- und einen Großbuchstaben enthalten". Allerdings verschwindet diese Meldung an dieser Stelle nicht nach erfolgreicher Wahl eines geeigneten Passwortes. Damit blockiert die Meldung andere Bedienelemente darunter. Erst ein Neuladen der Seite schafft Abhilfe.

**Comment by kesselb** [comment]
Mind to rephrase your bug report in english?

**Comment by wiswedel** [comment]
If you try to share a link and need to password it, you will see (if the password does not meet the requirements yet) the message "The password must contain a lowercase letter and an uppercase letter". However, this message does not disappear at this point after successful selection of a suitable password. Thus the message blocks other control elements below it. Only a reload of the page will solve the problem.

_Translated with www.DeepL.com/Translator_

**Comment by wiswedel** [comment]
CC @skjnldsv

**Comment by skjnldsv** [comment]
Fixed for 18

**Comment by itkama** [comment]
Thanks for translating @wiswedel . Couldn't have done it better :)

**Comment by skjnldsv** [comment]
Fixed with https://github.com/nextcloud/server/pull/15719
