### ISSUE TITLE
LDAP: User seems to be identified not by UUID (or samAccountName) but by complete DN

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#16923]
### Steps to reproduce
1. Create "CN:user1" with "OU:service" in your LDAP/AD within the group of NC users
2. login to NC as user1 
3. change "OU:service" to "OU:admins". 

### Expected behaviour
Nothing. "user1" should still exist b/c LDAP users are identified by their UUID (or, in our case, samAccountName), which did not change

### Actual behaviour
"user1" disappears in user:list and appears in ldap:show-remnants along with the old DN, a new user "user1_xxxx" with "xxxx" being an arbitrary four digit number and "last-seen: never" in user:info appears.
After changing OU:admins back to OU:service, user1_xxxx becomes member of ldap:show-remnants and user1 w/o the random number comes back to life.

### Server configuration

Open SUSE 15.1:

Apache2 2.4.33

mySql 5.7

PHP 7.2

NC 16.0.3.0

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

 hasMemberOfFilterSupport       1                                                                                                                                                                        
 homeFolderNamingRule                                                                                                                                                                                    
 lastJpegPhotoLookup            0                                                                                                                                                                        
 ldapAgentName                  CN=clouduser, OU=accounts, OU=central, DC=company, DC=tld                                                                                                              
 ldapAgentPassword              ***                                                                                                                                                                      
 ldapAttributesForGroupSearch   name;description                                                                                                                                                         
 ldapAttributesForUserSearch    sn;givenname                                                                                                                                                             
 ldapBackupHost                 ldaps://domaincontroller2.company.tld                                                                                                                                       
 ldapBackupPort                 636                                                                                                                                                                      
 ldapBase                       DC=company,DC=tld                                                                                                                                                          
 ldapBaseGroups                 DC=company,DC=tld                                                                                                                                                          
 ldapBaseUsers                  DC=company,DC=tld                                                                                                                                                          
 ldapCacheTTL                   600                                                                                                                                                                      
 ldapConfigurationActive        1                                                                                                                                                                        
 ldapDefaultPPolicyDN                                                                                                                                                                                    
 ldapDynamicGroupMemberURL                                                                                                                                                                               
 ldapEmailAttribute             mail                                                                                                                                                                     
 ldapExperiencedAdmin           0                                                                                                                                                                        
 ldapExpertUUIDGroupAttr                                                                                                                                                                                 
 ldapExpertUUIDUserAttr         sAMAccountName                                                                                                                                                           
 ldapExpertUsernameAttr         sAMAccountName                                                                                                                                                           
 ldapExtStorageHomeAttribute                                                                                                                                                                             
 ldapGidNumber                  gidNumber                                                                                                                                                                
 ldapGroupDisplayName           cn                                                                                                                                                                       
 ldapGroupFilter                (&((objectclass=group))((cn=NC-Users)))                                                                                                                         
 ldapGroupFilterGroups          NC-Users                                                                                                                                                          
 ldapGroupFilterMode            0                                                                                                                                                                        
 ldapGroupFilterObjectclass     group                                                                                                                                                                    
 ldapGroupMemberAssocAttr       member                                                                                                                                                                   
 ldapHost                       ldaps://domaincontroller.company.tld                                                                                                                                             
 ldapIgnoreNamingRules                                                                                                                                                                                   
 ldapLoginFilter                (&(&((objectclass=person))(((memberof=CN=NC-Users,OU=UHD,OU=Groups,OU=central,DC=company,DC=tld)(primaryGroupID=12345))))((samaccountname=%uid)((mail=%uid)))) 
 ldapLoginFilterAttributes      mail                                                                                                                                                                     
 ldapLoginFilterEmail           0                                                                                                                                                                        
 ldapLoginFilterMode            0                                                                                                                                                                        
 ldapLoginFilterUsername        1                                                                                                                                                                        
 ldapNestedGroups               0                                                                                                                                                                        
 ldapOverrideMainServer                                                                                                                                                                                  
 ldapPagingSize                 500                                                                                                                                                                      
 ldapPort                       636                                                                                                                                                                      
 ldapQuotaAttribute                                                                                                                                                                                      
 ldapQuotaDefault                                                                                                                                                                                        
 ldapTLS                        0                                                                                                                                                                        
 ldapUserAvatarRule             default                                                                                                                                                                  
 ldapUserDisplayName            displayname                                                                                                                                                              
 ldapUserDisplayName2                                                                                                                                                                                    
 ldapUserFilter                 (&((objectclass=person))(((memberof=CN=NC-Users,OU=UHD,OU=Groups,OU=central,DC=company,DC=tld)(primaryGroupID=12345))))                                          
 ldapUserFilterGroups           NC-Users                                                                                                                                                          
 ldapUserFilterMode             0                                                                                                                                                                        
 ldapUserFilterObjectclass      person                                                                                                                                                                   
 ldapUuidGroupAttribute         auto                                                                                                                                                                     
 ldapUuidUserAttribute          auto                                                                                                                                                                     
 turnOffCertCheck               0                                                                                                                                                                        
 turnOnPasswordChange           0                                                                                                                                                                        
 useMemberOfToDetectMembership  1                                                                                                                                                                        

</details>

Same behaviour as in https://github.com/nextcloud/server/issues/7430 and https://github.com/nextcloud/server/issues/8764

**Comment by blizzz** [comment]
well, are the known uuids identical? `select * from oc_ldap_user_mapping where owncloud name like "user1%";`

**Comment by Volker-K** [comment]
Stranger things:
```
+--------------------------------------------------------------------+---------------+--------------------------------------+
| ldap_dn                                                            | owncloud_name | directory_uuid                       |
+--------------------------------------------------------------------+---------------+--------------------------------------+
| cn=user1,ou=user,ou=company,ou=xx,dc=yyy,dc=local                  | user1         | B6BDE6F5-xxxx-xxxx-xxxx-xxxxxxxxxxxx |
| cn=user1,ou=userfunktion,ou=company,ou=xx,dc=yyy,dc=local          | user1_4794    | user1                                |
+--------------------------------------------------------------------+---------------+--------------------------------------+
```
That samAccountName should be used as cloud ID has been configured from day 1. I've taken a look at the oc_ldap_user_mapping and found about 1/3rd of all accounts identified by UUID, 2/3rd by samAccountName. Mostly "older" accounts are identified by UUID. 

We've tried the change of the OU with two accounts, one with UUID and one with samAccountName in the last column. If we change the "UUID-account", a new account with the samAccountName in Col 3 appears and the old account is disabled,.
If we change the "samAccountName-account" everything works as expected.

Could it be that the behaviouir (which value to be used as directory_uuid?) as changed with a version? Oder is ths an artefact that was created before we migrated from OwnCloud to NextCloud?

**Comment by blizzz** [comment]
It looks live as if the UUID attribute was changed in production. There's a lot of explanatory documentaiton about it.

**Comment by rasos** [comment]
There are several more users who reported an issue on duplication of users https://github.com/nextcloud/server/issues/7430#issuecomment-350707994 without changing the UUID attribute.
Our use case was letting users authenticate with SAML, but get the group attributes from LDAP. Every week we had few users which got duplicated and we had to switch back to LDAP auth only.
Since an upgrade to php 7.2.24 we are suffering from very high CPU load when hashing the LDAP password https://github.com/nextcloud/server/issues/17241#issuecomment-556287530 and we would like to revive SAML auth. So how can we minimize risks, that users are not again duplicated?

**Comment by Volker-K** [comment]
Did you check within the database if there's the UUID used to identify users, @rasos ?

**Comment by wscheicher** [comment]
Just run into the same Problem (NC 20.0.5)
DN changed because user was moved to different OU, Nextcloud "created" a new user with 4-digit-suffix despite the field which was specified as UUID in the Nextcloud LDAP config did not change.
Now i gotta figure out how to clean up this mess ...

**Comment by blizzz** [comment]
> Just run into the same Problem (NC 20.0.5)
> DN changed because user was moved to different OU, Nextcloud "created" a new user with 4-digit-suffix despite the field which was specified as UUID in the Nextcloud LDAP config did not change.
> Now i gotta figure out how to clean up this mess ...

Then the UUID does not match the LDAP record's.

**Comment by wscheicher** [comment]
> Then the UUID does not match the LDAP record's.

I don't understand what you mean.

In the nextcloud ldap config, "UUID Attribute for Users" is set to sAMAccountName.
This is and was something like "jdoe"
In Nextcloud i have now 2 entries in oc_ldap_user_mapping:
* "jdoe" with the old ldap_dn
* "jdoe_1234" with the new ldap_dn

There is no "jdoe_1234" on the LDAP Server.

So obviousely Nextcloud does not respect the UUID setting.

**Comment by blizzz** [comment]
> > Then the UUID does not match the LDAP record's.
> 
> I don't understand what you mean.
> 
> In the nextcloud ldap config, "UUID Attribute for Users" is set to sAMAccountName.
> This is and was something like "jdoe"
> In Nextcloud i have now 2 entries in oc_ldap_user_mapping:
> 
>     * "jdoe" with the old ldap_dn
> 
>     * "jdoe_1234" with the new ldap_dn
> 
> 
> There is no "jdoe_1234" on the LDAP Server.
> 
> So obviousely Nextcloud does not respect the UUID setting.

what's the directory_uuid value in each of those rows?

**Comment by wscheicher** [comment]
> what's the directory_uuid value in each of those rows?

"jdoe" (old): F1EDF67E-EF50-4433-84CC-A3C6ED75C7BB
"jdoe_1234": jdoe

Aaah ... so the "directory_uuid" field is the actual UUID field ... i start to understand.

And ... does that possibly mean that when setting up the Server (years ago), accounts were read from the LDAP server and directory_uuid values were generated before "UUID Attribute for Users" was set to sAMAccountName ..?

Note: Probably the clear mapping buttons in the LDAP config have never been pushed because of the "Clearing the mappings will have leftovers everywhere" ... and "Never clear the mappings in a production environment" ...
( But i probably should ... )

**Comment by blizzz** [comment]
> Aaah ... so the "directory_uuid" field is the actual UUID field ... i start to understand.

Exactly

> And ... does that possibly mean that when setting up the Server (years ago), accounts were read from the LDAP server and directory_uuid values were generated before "UUID Attribute for Users" was set to sAMAccountName ..?

correct

> Note: Probably the clear mapping buttons in the LDAP config have never been pushed because of the "Clearing the mappings will have leftovers everywhere" ... and "Never clear the mappings in a production environment" ...
> ( But i probably should ... )

that might have worked, but i if the sAMAccountName has changed for a user, they would have got a fresh account, too, since user ids in nextcloud are immutable. therefore we default for a stable value there as well (also the UUID).

**Comment by wscheicher** [comment]
Ok.
And i now also found the old directory_uuid value on the LDAP Server as "objectGUID".
Makes sense.

So i basically have a mess and should clean up.
Any hints/suggestions for that?

**Comment by blizzz** [comment]
> Ok.
> And i now also found the old directory_uuid value on the LDAP Server as "objectGUID".
> Makes sense.
> 
> So i basically have a mess and should clean up.
> Any hints/suggestions for that?

update the directory_uuid in the tables directly. should be easy to script, since you have the DN, you can fetch the attribute (for instance with ldapsearch) from  the LDAP server and write it into the db.

**Comment by szaimen** [comment]
So is this something that should be fixed or is it a configuration issue?
