### ISSUE TITLE
Nextcloud did not find an application suitable for the current version

### ISSUE THREAD

**Issue by chyff** [nextcloud/server#16931]
Hello, the version I used is 16.0.4. After the installation with docker, I found that the management application displayed "application with current version not found".

**Comment by juliushaertl** [comment]
Please fill out the complete issue template. Is the error related to a specific application? Could you share a screenshot as I'm not aware of that message actually.

**Comment by chyff** [comment]
The following picture shows that I can't see the application in nextcloud application


2238848271@qq.com
 
From: Julius Härtl
Date: 2019-09-02 21:59
To: nextcloud/server
CC: chyff; Author
Subject: Re: [nextcloud/server] Nextcloud did not find an application suitable for the current version (#16931)
Please fill out the complete issue template. Is the error related to a specific application? Could you share a screenshot as I'm not aware of that message actually.

**Comment by juliushaertl** [comment]
Github doesn't show images attached to emails. As mentioned, please use the issue template.
