### ISSUE TITLE
Can't require_once autoload.php -> wrong path ? in the legacy app file

### ISSUE THREAD

**Issue by nicolas-san** [nextcloud/server#16935]
### Steps to reproduce
1. download last Nextcloud and install locally
2. clone the app mail repo
3. execute make dev-setup
4. try to enable the mail app

### Actual behaviour
In the log: Cannot include autoload. Did you run install dependencies using composer?
And the mail app is disabled automatically.

### Server configuration

**Operating system**: 
ubuntu 19.04
**Web server:**
apache 2.4
**Database:**
Mariadb
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
16.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
dl the zip on the website
**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- mail
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [mail] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.15.99
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "http:\/\/localhost\/phpStorm\/nextcloud_dev\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
NO
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

**Complete explanation**

I try to test the app mail from the source, I have installed normally Nextcloud, no trouble with that, I have cloned the app mail repo, and launch the make process.
Composer as running, installing all the vendors.
When I try to enable the app, I have the error message about autoload.php, but the file exists.
I have checked the file access, owner, group, mode, all good.

To understand, I have dig into the code, I don't know if I miss something, but in lib/private/legacy/app.php at line 151 the check is :
```php
if (is_file($appPath . '/appinfo/app.php')) {
```
But at line 154 the call of the requireAppFile is:
```php
self::requireAppFile($app)
```
With the app name, and not with the app path, and in the function:
```php
private static function requireAppFile(string $app) {
		// encapsulated here to avoid variable scope conflicts
		require_once $app . '/appinfo/app.php';
	}
```

The app name is used to require_once the app.php

To test, I have changed the call for:
```php
self::requireAppFile($appPath)
```

And now the app mail is enabled, and works fine
I do not new if I miss something, but the code is the same since a long time (I have take a look at the older tags - 13.xx ... ), and I can't understand what is wrong

**Comment by kesselb** [comment]
Above code works for me without your change. Indeed we call `require_once 'mail/appinfo/app.php'` here but somehow its resolved properly. The warning "Cannot include autoload. Did you run install dependencies using composer?" is coming from https://github.com/nextcloud/mail/blob/ee5235a1b1f78924090e9043cd97a111b6fb0372/appinfo/app.php#L26-L28 so the file is properly included.

cc @rullzer autoloader magic ;)

**Comment by rullzer** [comment]
You need to install the dependies of the mail app. But I recommend you install releases from the appstore

**Comment by nicolas-san** [comment]
@rullzer I want to try a different branch, from a PR of the app mail.
I have installed the dependencies, when I run make dev-setup it runs composer and  npm to install everything.
The trouble could be from the mail app build or my nextcloud installation ?
(I have the vendor subdir in mail, and the autoload.php)

**Comment by rullzer** [comment]
Where did you clone the app?

This is a bit puzzling as I have it working like a charm here...

**Comment by nicolas-san** [comment]
this one https://github.com/StCyr/mail/tree/StCyr-Issue786
from this https://github.com/nextcloud/mail/pull/1753
Thanks :)

**Comment by kesselb** [comment]
The branch is 337 commits behind master. I would try to merge master into your local copy.

**Comment by nicolas-san** [comment]
@kesselb after the source branch was rebased, the problem was resolved, thanks for your time

**Comment by kesselb** [comment]
Happy hacking :+1:
