### ISSUE TITLE
NC17Beta do not work with libreoffice nor collabora

### ISSUE THREAD

**Issue by ralfi** [nextcloud/server#16933]
Hi Nextcloudies,

i can not properly connect to libreoffice or collabora with latest NC17-Beta.

I have a complete "dockerized" environment with latest images. If i switch to NC16 (my productive environment) everything works fine with the connectivity to libreoffice or collabora.

Regards

**Comment by juliushaertl** [comment]
Please use the issue template when reporting a bug
