### ISSUE TITLE
Quota settings applied but not shown in certain constellations with External Storage

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#16943]
### Steps to reproduce
1. set config entry ```'quota_include_external_storage' => true,```
2. Go to users page
3. Set a quota for a user
4. Refresh the users page => quota shows the value before the setting in 3.
5. set config entry ```'quota_include_external_storage' => false,```
6. Refresh the users page => quota shows the value that has been set in 3.

Same as under 1. and 5. applies if you configure an external storage as root ```/```and set it back to anything else afterwards.

### Server configuration

**PHP version:**
7.3.8

**Nextcloud version:**
16.0.4
17.0.0 Beta 3

**Comment by wiswedel** [comment]
@nextcloud/server-triage

**Comment by wiswedel** [comment]
related: https://github.com/nextcloud/server/issues/10817

**Comment by skjnldsv** [comment]
> Same as under 1. and 5. applies if you configure an external storage as root `/`and set it back to anything else afterwards.

Because external storage as root is not compatible with quota management :)

**Comment by szaimen** [comment]
> Because external storage as root is not compatible with quota management :)

So then an error message would be great. In the current state it seems like an error.

**Comment by skjnldsv** [comment]
@szaimen I will add this to the documentation

**Comment by szaimen** [comment]
@skjnldsv I don't know if that is enough. I think additionally disabling the quota settings completely for users with external storage as root would also be necessary.
