### ISSUE TITLE
Update NextCloud 16.0.1 > 16.04

### ISSUE THREAD

**Issue by wtpritz** [nextcloud/server#16958]
### Steps to reproduce
1. Update to 16.0.4 through Web Updater
2. After download an update continue to update via web
3. Update to 16.0.4 Failed

### Expected behaviour
Update should have succeeded

### Actual behaviour
Update to 16.0.4 failed with error:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### Server configuration

**Operating system**:
Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-58-generic x86_64)
**Web server:**
 Apache/2.4.29 (Ubuntu)
**Database:**
mysql  Ver 15.1 Distrib 10.1.41-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
16.0.1 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older (multiple versions) last fresh install was v15
**Where did you install Nextcloud from:**
Manual Linux Install from Nextcloud.com
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Unable to login to Nextcloud as only able to re-run the Update
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - bookmarks: 2.0.3
  - bruteforcesettings: 1.4.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.6
  - drawio: 0.9.3
  - event_update_notification: 0.3.4
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_antivirus: 2.1.1
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.5.0
  - files_readmemd: 1.1.1
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - jsloader: 1.0.2
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - music: 0.10.0
  - news: 13.1.6
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.2
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - passwords: 2019.8.1
  - polls: 0.10.2
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - text: 1.0.2
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - unsplash: 1.1.3
  - updatenotification: 1.6.0
  - user_usage_report: 1.1.2
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - announcementcenter
  - apporder
  - calendar
  - dashboard
  - data_request
  - encryption
  - files_downloadactivity
  - files_external
  - files_trackdownloads
  - impersonate
  - mail
  - ocsms
  - quota_warning
  - radio
  - ransomware_detection
  - ransomware_protection
  - richdocuments
  - spreed
  - tasks
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.citation.no-ip.org",
            "lccsvmnxtcld01.citation.no-ip.org",
            "lccsvmnxtcld01.local",
            "10.1.0.56",
            "citation.no-ip.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.1.1",
        "overwrite.cli.url": "https:\/\/nextcloud.citation.no-ip.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "memcache.local": "OC\\Memcache\\APCu",
        "knowledgebaseenabled": true,
        "allow_user_to_change_display_Name": true,
        "skeletondirectory": "\/srv\/nextcloud\/skeleton",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "drawio"
        ],
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Google Chrome Version 76.0.3809.132 (Official Build) (64-bit)
**Operating system:**
macOS 10.15 Beta (19A546d)
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Change row format for oc_addressbooks ...

Repair info: Change collation for oc_addressbooks ...

Repair info: Change row format for oc_announcements ...

Repair info: Change collation for oc_announcements ...

Repair info: Change row format for oc_announcements_groups ...

Repair info: Change collation for oc_announcements_groups ...

Repair info: Change row format for oc_appconfig ...

Repair info: Change collation for oc_appconfig ...

Repair info: Change row format for oc_authtoken ...

Repair info: Change collation for oc_authtoken ...

Repair info: Change row format for oc_bookmarks ...

Repair info: Change collation for oc_bookmarks ...

Repair info: Change row format for oc_bookmarks_folders ...

Repair info: Change collation for oc_bookmarks_folders ...

Repair info: Change row format for oc_bookmarks_tags ...

Repair info: Change collation for oc_bookmarks_tags ...

Repair info: Change row format for oc_bruteforce_attempts ...

Repair info: Change collation for oc_bruteforce_attempts ...

Repair info: Change row format for oc_calendar_invitations ...

Repair info: Change collation for oc_calendar_invitations ...

Repair info: Change row format for oc_calendar_resources ...

Repair info: Change collation for oc_calendar_resources ...

Repair info: Change row format for oc_calendar_rooms ...

Repair info: Change collation for oc_calendar_rooms ...

Repair info: Change row format for oc_calendarchanges ...

Repair info: Change collation for oc_calendarchanges ...

Repair info: Change row format for oc_calendarobjects ...

Repair info: Change collation for oc_calendarobjects ...

Repair info: Change row format for oc_calendarobjects_props ...

Repair info: Change collation for oc_calendarobjects_props ...

Repair info: Change row format for oc_calendars ...

Repair info: Change collation for oc_calendars ...

Repair info: Change row format for oc_calendarsubscriptions ...

Repair info: Change collation for oc_calendarsubscriptions ...

Repair info: Change row format for oc_cards ...

Repair info: Change collation for oc_cards ...

Repair info: Change row format for oc_cards_properties ...

Repair info: Change collation for oc_cards_properties ...

Repair info: Change row format for oc_collres_accesscache ...

Repair info: Change collation for oc_collres_accesscache ...

Repair info: Change row format for oc_collres_collections ...

Repair info: Change collation for oc_collres_collections ...

Repair info: Change row format for oc_collres_resources ...

Repair info: Change collation for oc_collres_resources ...

Repair info: Change row format for oc_comments ...

Repair info: Change collation for oc_comments ...

Repair info: Change row format for oc_comments_read_markers ...

Repair info: Change collation for oc_comments_read_markers ...

Repair info: Change row format for oc_credentials ...

Repair info: Change collation for oc_credentials ...

Repair info: Change row format for oc_dashboard_events ...

Repair info: Change collation for oc_dashboard_events ...

Repair info: Change row format for oc_dashboard_settings ...

Repair info: Change collation for oc_dashboard_settings ...

Repair info: Change row format for oc_dav_shares ...

Repair info: Change collation for oc_dav_shares ...

Repair info: Change row format for oc_deck_assigned_users ...

Repair info: Change collation for oc_deck_assigned_users ...

Repair info: Change row format for oc_deck_attachment ...

Repair info: Change collation for oc_deck_attachment ...

Repair info: Change row format for oc_deck_board_acl ...

Repair info: Change collation for oc_deck_board_acl ...

Repair info: Change row format for oc_deck_boards ...

Repair info: Change collation for oc_deck_boards ...

Repair info: Change row format for oc_deck_cards ...

Repair info: Change collation for oc_deck_cards ...

Repair info: Change row format for oc_deck_labels ...

Repair info: Change collation for oc_deck_labels ...

Repair info: Change row format for oc_deck_stacks ...

Repair info: Change collation for oc_deck_stacks ...

Repair info: Change row format for oc_directlink ...

Repair info: Change collation for oc_directlink ...

Repair info: Change row format for oc_file_locks ...

Repair info: Change collation for oc_file_locks ...

Repair info: Change row format for oc_filecache ...

Repair info: Change collation for oc_filecache ...

Repair info: Change row format for oc_files_avir_status ...

Repair info: Change collation for oc_files_avir_status ...

Repair info: Change row format for oc_files_trash ...

Repair info: Change collation for oc_files_trash ...

Repair info: Change row format for oc_flow_checks ...

Repair info: Change collation for oc_flow_checks ...

Repair info: Change row format for oc_flow_operations ...

Repair info: Change collation for oc_flow_operations ...

Repair info: Change row format for oc_group_admin ...

Repair info: Change collation for oc_group_admin ...

Repair info: Change row format for oc_group_user ...

Repair info: Change collation for oc_group_user ...

Repair info: Change row format for oc_groups ...

Repair info: Change collation for oc_groups ...

Repair info: Change row format for oc_jobs ...

Repair info: Change collation for oc_jobs ...

Repair info: Change row format for oc_login_flow_v2 ...

Repair info: Change collation for oc_login_flow_v2 ...

Repair info: Change row format for oc_mail_accounts ...

Repair info: Change collation for oc_mail_accounts ...

Repair info: Change row format for oc_mail_aliases ...

Repair info: Change collation for oc_mail_aliases ...

Repair info: Change row format for oc_mail_attachments ...

Repair info: Change collation for oc_mail_attachments ...

Repair info: Change row format for oc_mail_coll_addresses ...

Repair info: Change collation for oc_mail_coll_addresses ...

Repair info: Change row format for oc_migrations ...

Repair info: Change collation for oc_migrations ...

Repair info: Change row format for oc_mimetypes ...

Repair info: Change collation for oc_mimetypes ...

Repair info: Change row format for oc_mounts ...

Repair info: Change collation for oc_mounts ...

Repair info: Change row format for oc_music_albums ...

Repair info: Change collation for oc_music_albums ...

Repair info: Change row format for oc_music_ampache_sessions ...

Repair info: Change collation for oc_music_ampache_sessions ...

Repair info: Change row format for oc_music_ampache_users ...

Repair info: Change collation for oc_music_ampache_users ...

Repair info: Change row format for oc_music_artists ...

Repair info: Change collation for oc_music_artists ...

Repair info: Change row format for oc_music_cache ...

Repair info: Change collation for oc_music_cache ...

Repair info: Change row format for oc_music_playlists ...

Repair info: Change collation for oc_music_playlists ...

Repair info: Change row format for oc_music_tracks ...

Repair info: Change collation for oc_music_tracks ...

Repair info: Change row format for oc_news_feeds ...

Repair info: Change collation for oc_news_feeds ...

Repair info: Change row format for oc_news_folders ...

Repair info: Change collation for oc_news_folders ...

Repair info: Change row format for oc_news_items ...

Repair info: Change collation for oc_news_items ...

Repair info: Change row format for oc_notes_meta ...

Repair info: Change collation for oc_notes_meta ...

Repair info: Change row format for oc_notifications ...

Repair info: Change collation for oc_notifications ...

Repair info: Change row format for oc_notifications_pushtokens ...

Repair info: Change collation for oc_notifications_pushtokens ...

Repair info: Change row format for oc_oauth2_access_tokens ...

Repair info: Change collation for oc_oauth2_access_tokens ...

Repair info: Change row format for oc_oauth2_clients ...

Repair info: Change collation for oc_oauth2_clients ...

Repair info: Change row format for oc_ocsms_config ...

Repair info: Change collation for oc_ocsms_config ...

Repair info: Change row format for oc_ocsms_conversation_read_states ...

Repair info: Change collation for oc_ocsms_conversation_read_states ...

Repair info: Change row format for oc_ocsms_sendmessage_queue ...

Repair info: Change collation for oc_ocsms_sendmessage_queue ...

Repair info: Change row format for oc_ocsms_smsdatas ...

Repair info: Change collation for oc_ocsms_smsdatas ...

Repair info: Change row format for oc_ocsms_user_datas ...

Repair info: Change collation for oc_ocsms_user_datas ...

Repair info: Change row format for oc_passwords_entity_challenge ...

Repair info: Change collation for oc_passwords_entity_challenge ...

Repair info: Change row format for oc_passwords_entity_folder ...

Repair info: Change collation for oc_passwords_entity_folder ...

Repair info: Change row format for oc_passwords_entity_folder_revision ...

Repair info: Change collation for oc_passwords_entity_folder_revision ...

Repair info: Change row format for oc_passwords_entity_keychain ...

Repair info: Change collation for oc_passwords_entity_keychain ...

Repair info: Change row format for oc_passwords_entity_password ...

Repair info: Change collation for oc_passwords_entity_password ...

Repair info: Change row format for oc_passwords_entity_password_revision ...

Repair info: Change collation for oc_passwords_entity_password_revision ...

Repair info: Change row format for oc_passwords_entity_session ...

Repair info: Change collation for oc_passwords_entity_session ...

Repair info: Change row format for oc_passwords_entity_share ...

Repair info: Change collation for oc_passwords_entity_share ...

Repair info: Change row format for oc_passwords_entity_tag ...

Repair info: Change collation for oc_passwords_entity_tag ...

Repair info: Change row format for oc_passwords_entity_tag_revision ...

Repair info: Change collation for oc_passwords_entity_tag_revision ...

Repair info: Change row format for oc_passwords_relation_password_tag ...

Repair info: Change collation for oc_passwords_relation_password_tag ...

Repair info: Change row format for oc_phonetrack_devices ...

Repair info: Change collation for oc_phonetrack_devices ...

Repair info: Change row format for oc_phonetrack_filtersb ...

Repair info: Change collation for oc_phonetrack_filtersb ...

Repair info: Change row format for oc_phonetrack_geofences ...

Repair info: Change collation for oc_phonetrack_geofences ...

Repair info: Change row format for oc_phonetrack_points ...

Repair info: Change collation for oc_phonetrack_points ...

Repair info: Change row format for oc_phonetrack_proxims ...

Repair info: Change collation for oc_phonetrack_proxims ...

Repair info: Change row format for oc_phonetrack_pubshares ...

Repair info: Change collation for oc_phonetrack_pubshares ...

Repair info: Change row format for oc_phonetrack_sessions ...

Repair info: Change collation for oc_phonetrack_sessions ...

Repair info: Change row format for oc_phonetrack_shares ...

Repair info: Change collation for oc_phonetrack_shares ...

Repair info: Change row format for oc_phonetrack_tileserver ...

Repair info: Change collation for oc_phonetrack_tileserver ...

Repair info: Change row format for oc_polls_comments ...

Repair info: Change collation for oc_polls_comments ...

Repair info: Change row format for oc_polls_events ...

Repair info: Change collation for oc_polls_events ...

Repair info: Change row format for oc_polls_notif ...

Repair info: Change collation for oc_polls_notif ...

Repair info: Change row format for oc_polls_options ...

Repair info: Change collation for oc_polls_options ...

Repair info: Change row format for oc_polls_votes ...

Repair info: Change collation for oc_polls_votes ...

Repair info: Change row format for oc_preferences ...

Repair info: Change collation for oc_preferences ...

Repair info: Change row format for oc_preview_generation ...

Repair info: Change collation for oc_preview_generation ...

Repair info: Change row format for oc_privacy_admins ...

Repair info: Change collation for oc_privacy_admins ...

Repair info: Change row format for oc_properties ...

Repair info: Change collation for oc_properties ...

Repair info: Change row format for oc_radio_stations ...

Repair info: Change collation for oc_radio_stations ...

Repair info: Change row format for oc_ransomware_detection ...

Repair info: Change collation for oc_ransomware_detection ...

Repair info: Change row format for oc_richdocuments_assets ...

Repair info: Change collation for oc_richdocuments_assets ...

Repair info: Change row format for oc_richdocuments_direct ...

Repair info: Change collation for oc_richdocuments_direct ...

Repair info: Change row format for oc_richdocuments_member ...

Repair info: Change collation for oc_richdocuments_member ...

Repair info: Change row format for oc_richdocuments_wopi ...

Repair info: Change collation for oc_richdocuments_wopi ...

Repair info: Change row format for oc_schedulingobjects ...

Repair info: Change collation for oc_schedulingobjects ...

Repair info: Change row format for oc_share ...

Repair info: Change collation for oc_share ...

Repair info: Change row format for oc_share_external ...

Repair info: Change collation for oc_share_external ...

Repair info: Change row format for oc_storages ...

Repair info: Change collation for oc_storages ...

Repair info: Change row format for oc_systemtag ...

Repair info: Change collation for oc_systemtag ...

Repair info: Change row format for oc_systemtag_group ...

Repair info: Change collation for oc_systemtag_group ...

Repair info: Change row format for oc_systemtag_object_mapping ...

Repair info: Change collation for oc_systemtag_object_mapping ...

Repair info: Change row format for oc_talk_commands ...

Repair info: Change collation for oc_talk_commands ...

Repair info: Change row format for oc_talk_guests ...

Repair info: Change collation for oc_talk_guests ...

Repair info: Change row format for oc_talk_participants ...

Repair info: Change collation for oc_talk_participants ...

Repair info: Change row format for oc_talk_rooms ...

Repair info: Change collation for oc_talk_rooms ...

Repair info: Change row format for oc_talk_signaling ...

Repair info: Change collation for oc_talk_signaling ...

Repair info: Change row format for oc_text_documents ...

Repair info: Change collation for oc_text_documents ...

Repair info: Change row format for oc_text_sessions ...

Repair info: Change collation for oc_text_sessions ...

Repair info: Change row format for oc_text_steps ...

Repair info: Change collation for oc_text_steps ...

Repair info: Change row format for oc_trusted_servers ...

Repair info: Change collation for oc_trusted_servers ...

Repair info: Change row format for oc_twofactor_backupcodes ...

Repair info: Change collation for oc_twofactor_backupcodes ...

Repair info: Change row format for oc_twofactor_providers ...

Repair info: Change collation for oc_twofactor_providers ...

Repair info: Change row format for oc_usage_report ...

Repair info: Change collation for oc_usage_report ...

Repair info: Change row format for oc_users ...

Repair info: Change collation for oc_users ...

Repair info: Change row format for oc_vcategory ...

Repair info: Change collation for oc_vcategory ...

Repair info: Change row format for oc_vcategory_to_object ...

Repair info: Change collation for oc_vcategory_to_object ...

Repair info: Change row format for oc_whats_new ...

Repair info: Change collation for oc_whats_new ...

Repair info: Change row format for oc_bookmarks_folders_bookmarks ...

Repair info: Change collation for oc_bookmarks_folders_bookmarks ...

Repair info: Change row format for oc_deck_assigned_labels ...

Repair info: Change collation for oc_deck_assigned_labels ...

Repair info: Change row format for oc_federated_reshares ...

Repair info: Change collation for oc_federated_reshares ...

Repair info: Change row format for oc_files_antivirus ...

Repair info: Change collation for oc_files_antivirus ...

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Updated "files_rightclick" to 0.13.0

Updated "viewer" to 1.1.0

Checking for update of app "accessibility" in appstore

Checked for update of app "accessibility" in appstore

Checking for update of app "activity" in appstore

Checked for update of app "activity" in appstore

Checking for update of app "admin_audit" in appstore

Checked for update of app "admin_audit" in appstore

Checking for update of app "bookmarks" in appstore

Update app "bookmarks" from appstore

Checked for update of app "bookmarks" in appstore

Checking for update of app "bruteforcesettings" in appstore

Checked for update of app "bruteforcesettings" in appstore

Checking for update of app "checksum" in appstore

Checked for update of app "checksum" in appstore

Checking for update of app "cloud_federation_api" in appstore

Checked for update of app "cloud_federation_api" in appstore

Checking for update of app "comments" in appstore

Checked for update of app "comments" in appstore

Checking for update of app "contacts" in appstore

Checked for update of app "contacts" in appstore

Checking for update of app "dav" in appstore

Checked for update of app "dav" in appstore

Checking for update of app "deck" in appstore

Checked for update of app "deck" in appstore

Checking for update of app "drawio" in appstore

Checked for update of app "drawio" in appstore

Checking for update of app "event_update_notification" in appstore

Checked for update of app "event_update_notification" in appstore

Checking for update of app "federatedfilesharing" in appstore

Checked for update of app "federatedfilesharing" in appstore

Checking for update of app "federation" in appstore

Checked for update of app "federation" in appstore

Checking for update of app "files" in appstore

Checked for update of app "files" in appstore

Checking for update of app "files_antivirus" in appstore

Checked for update of app "files_antivirus" in appstore

Checking for update of app "files_markdown" in appstore

Checked for update of app "files_markdown" in appstore

Checking for update of app "files_mindmap" in appstore

Checked for update of app "files_mindmap" in appstore

Checking for update of app "files_pdfviewer" in appstore

Checked for update of app "files_pdfviewer" in appstore

Checking for update of app "files_readmemd" in appstore

Checked for update of app "files_readmemd" in appstore

Checking for update of app "files_rightclick" in appstore

Update app "files_rightclick" from appstore

Checked for update of app "files_rightclick" in appstore

Checking for update of app "files_sharing" in appstore

Checked for update of app "files_sharing" in appstore

Checking for update of app "files_texteditor" in appstore

Checked for update of app "files_texteditor" in appstore

Checking for update of app "files_trashbin" in appstore

Checked for update of app "files_trashbin" in appstore

Checking for update of app "files_versions" in appstore

Checked for update of app "files_versions" in appstore

Checking for update of app "files_videoplayer" in appstore

Checked for update of app "files_videoplayer" in appstore

Checking for update of app "firstrunwizard" in appstore

Checked for update of app "firstrunwizard" in appstore

Checking for update of app "gallery" in appstore

Checked for update of app "gallery" in appstore

Checking for update of app "jsloader" in appstore

Checked for update of app "jsloader" in appstore

Checking for update of app "logreader" in appstore

Checked for update of app "logreader" in appstore

Checking for update of app "lookup_server_connector" in appstore

Checked for update of app "lookup_server_connector" in appstore

Checking for update of app "metadata" in appstore

Checked for update of app "metadata" in appstore

Checking for update of app "music" in appstore

Checked for update of app "music" in appstore

Checking for update of app "news" in appstore

Checked for update of app "news" in appstore

Checking for update of app "nextcloud_announcements" in appstore

Checked for update of app "nextcloud_announcements" in appstore

Checking for update of app "notes" in appstore

Update app "notes" from appstore

Checked for update of app "notes" in appstore

Checking for update of app "notifications" in appstore

Checked for update of app "notifications" in appstore

Checking for update of app "oauth2" in appstore

Checked for update of app "oauth2" in appstore

Checking for update of app "password_policy" in appstore

Checked for update of app "password_policy" in appstore

Checking for update of app "passwords" in appstore

Checked for update of app "passwords" in appstore

Checking for update of app "polls" in appstore

Checked for update of app "polls" in appstore

Checking for update of app "previewgenerator" in appstore

Checked for update of app "previewgenerator" in appstore

Checking for update of app "privacy" in appstore

Checked for update of app "privacy" in appstore

Checking for update of app "provisioning_api" in appstore

Checked for update of app "provisioning_api" in appstore

Checking for update of app "recommendations" in appstore

Checked for update of app "recommendations" in appstore

Checking for update of app "serverinfo" in appstore

Checked for update of app "serverinfo" in appstore

Checking for update of app "sharebymail" in appstore

Checked for update of app "sharebymail" in appstore

Checking for update of app "support" in appstore

Checked for update of app "support" in appstore

Checking for update of app "survey_client" in appstore

Checked for update of app "survey_client" in appstore

Checking for update of app "systemtags" in appstore

Checked for update of app "systemtags" in appstore

Checking for update of app "text" in appstore

Checked for update of app "text" in appstore

Checking for update of app "theming" in appstore

Checked for update of app "theming" in appstore

Checking for update of app "twofactor_backupcodes" in appstore

Checked for update of app "twofactor_backupcodes" in appstore

Checking for update of app "unsplash" in appstore

Checked for update of app "unsplash" in appstore

Checking for update of app "updatenotification" in appstore

Checked for update of app "updatenotification" in appstore

Checking for update of app "user_usage_report" in appstore

Checked for update of app "user_usage_report" in appstore

Checking for update of app "viewer" in appstore

Checked for update of app "viewer" in appstore

Checking for update of app "workflowengine" in appstore

Checked for update of app "workflowengine" in appstore

Repair step: Repair MySQL collation

Repair info: Change row format for oc_addressbooks ...

Repair info: Change collation for oc_addressbooks ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

The update was unsuccessful. Please report this issue to the Nextcloud community

**Comment by wtpritz** [comment]
Seems I need to specify a higher max key length to allow the conversion to take place. Unfortunately I see no place to set that within the contacts app app.php. Any assistance is greatly appreciated. Thank you!

**Comment by kesselb** [comment]
Thank you for reporting this issue +1 Please check #15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by kesselb** [comment]
Thank you for reporting this issue +1 Please check #15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by wtpritz** [comment]
Thank you so very much! The problem was with only a single table after converting to utf8mb4. All other tables converted, but for some reason this table would not convert. Upgrading from MariaDB 10.1. to 10.4 allowed the table to convert successfully and then the Nextcloud upgrade completed as expected (of course). Thank you again and I really appreciate your time. I should have just dug deeper before crying’ for help.
