### ISSUE TITLE
What happens when an LDAP user changes login in Active Directory?

### ISSUE THREAD

**Issue by strelkovandreyvalerievich** [nextcloud/server#16959]
Good day, in our Active Directory as the login full name is used, for example: **strelkov.av**

When a woman gets married, she takes her husband's name, because in Active Directory also changes her login. 
The question is, if the user initially logged into nextcloud under one login, and after a while when he changed his login, what happens when you log in?
How does the LDAP module, it takes a unique value for an identifier, such as objectsid, or it uses a login?

If the login, it turns out when you change the login, for nextcloud it will be as a new user in the system, and it turns out it will not have any relation to their old data? (folders, files)

**Comment by juliushaertl** [comment]
Thanks for your report, but this is more of a support request. If you are an enterprise user, please report the problem through https://portal.nextcloud.com and we will help you debug the issue with priority. If you do not have a support contract yet, see https://nextcloud.com/enterprise for more information on a Nextcloud Subscription. If you are a home user, you can ask for help on our private user forums on https://help.nextcloud.com.

Note that a bug report is a clear description of a bug in Nextcloud, including the steps to reproduce it on a fresh Nextcloud developer instance. Example code, curl examples or example apps are good ways of showing what is wrong, ad we very much welcome patches. Also, please make sure you have tested if the issue also happens on the latest daily build of Nextcloud. You can learn how to set up a developer instance here: https://docs.nextcloud.com/server/16/developer_manual

I will close this now, feel free to re-open if you have debugged the problem and can provide information.
