### ISSUE TITLE
Error when adding new user over web or occ

### ISSUE THREAD

**Issue by uwewiest** [nextcloud/server#16966]
Hi all,

I have an issue when adding a new user or trying to set a password etc.

Always get the error:

PHP Fatal error:  A void function must not return a value in /var/www/nextcloud/apps/password_policy/lib/Validator/HIBPValidator.php on line 71

nextcloud version 17.0.0 Beta 3

Any ideas?

Thanks 

Uwe

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

We already have a solution for this: https://github.com/nextcloud/password_policy/commit/63fefe846b0d31ec3e83b0d5f801a2e735ca5664
