### ISSUE TITLE
Add a on/off switch for file zipping in Nextcloud

### ISSUE THREAD

**Issue by HigH-HawK** [nextcloud/server#16971]
**Current behaviour:**

If a user wants to download several files via the web interface, the user selectes several files and clicks on Download. Nextcloud now creates a ZIP file first and than offers to download this ZIP file.

This behaviour could cause a server memory problem/crash. If the server has a memory size of 2GB and the user is selecting files of a total bigger than the server memory, it just crashes because it exceeds the server memory during the zipping process.

**Wanted behaviour:**

If a user selects several files via the web interface and clicks on "Download", the browser should just start a download process for each file.

**How could this be realised?:**

Let the administrator chose with a on/off switch in the admin settings, whether a multiple file download is being zipped, or if the files are being downloaded separately.

Maybe this could also be administrated via user groups?

Would it be possible to implement this in one of the future releases?

**Comment by juliushaertl** [comment]
I don't think that starting multiple downloads will work properly as browsers nowadays have lots of mechanisms to block multiple page opens happening though one click event. 

Regarding the error, are there any log entries? Are you by any change on a 32bit system?

**Comment by HigH-HawK** [comment]
Hey @juliushaertl 

To be honest I don't really have that problem, I just opened the request for a forum member who doesn't have a Github account. (https://help.nextcloud.com/t/disable-zipping/59279)

I forwarded your questions regarding possible log files and what system he is using.

Now that you mention the browser mechanism nowadays, I kind of agree that multiple downloads would probably cause issues.

**Comment by Milokita** [comment]
The user should have the selection to download file seperately while admin has the right to allow it or not. for multi files, there could be a max parallel download file number before next batch

**Comment by juliushaertl** [comment]
> Now that you mention the browser mechanism nowadays, I kind of agree that multiple downloads would probably cause issues.

Besides causing issues i would not consider this as an expected behavior, a single click should trigger a single action and if the browser ends up with adding hundreds of files to the download queue this is probably more giving the feeling of a maleware attack than expected behavior. Also with individual downloads the structure of downloaded folders will be lost, so I don't see this being implemented.

**Comment by ezaquarii** [comment]
Hi,

I recently tried to backup large directory using zip download and it caused memory exhaustion.
This problem can be caused either by PHP trying to create zip file in memory or by the http server that tries to allocate entire response body or something similar.

Can you tell how the zipping process is implemented? Ideally file contents should be streamed to the client with minimal buffer allocated for transfer (nginx has support for this using some response header shenanigans, not sure about others). This is not happening in my case for some reason.

**Comment by Milokita** [comment]
Meanwhile it seems that bandwidth control can't be implemented according to zip size as downloading this zip has unknown size

**Comment by zaniar** [comment]
I also need this. My server is not powerful enough to zip gigabytes of data.
What I need is just option to disable downloading folder/multiple files, not automatically downloading all files separately.

I prefer breaking "expected behavior" than breaking my server.

**Comment by verybadsoldier** [comment]
I also think it would be great if zipping could be disabled. Even if it means that basically the possibility to download multiple files at once will be disabled. It makes imo no sense for nextcloud trying to zip like 3 GB of files upfront before the download even starts.

Or maybe introduce a size limit in megabytes. So when the user marked files that summed up are larger than like 100 MB then yield an error instead of starting the process?

**Comment by h-2** [comment]
I have opened a new issue on this
https://github.com/nextcloud/server/issues/33730

Please give it a :+1:
