### ISSUE TITLE
Porblem with downloading/generating >1GB zip file

### ISSUE THREAD

**Issue by 80kk** [nextcloud/server#16979]
I found it earlier in previous versions of Nextcloud as well as random users have the same issue, but no solution has been provided.
The problem is if I select all files in folder to download and Nextcloud server generates massive ZIP file. For some reason (I can't find anything about that in logs) it stops generating or not allowing to download more than 1GB zip file. It doesn't look like a PHP/Nginx/Apache configuration issue, because I am able to download (from Nextcloud) files like 7GB big.

**Comment by errotu** [comment]
I can confirm this issue in the context of public shares. The maximum size of the downloaded zip file is 1GB. The file itself is useless, since I cannot open it with an archive manager.

**Comment by skjnldsv** [comment]
What system architecture are you on? 32-bit ? 64-bit?

**Comment by errotu** [comment]
Since my nextcloud is running on a shared webhosting, I don't know where I can found that information. Sorry!

What might help: I just checked /settings/admin/serverinfo. Here are some information:

>**Storage**
>Users: 3
>Files: 206759
>Storages: 4
>Free Space: 402.7 GB
>
>**Nextcloud**
>Version: 16.0.4.1
>Apps installed: 44
>Apps updates available: 0
>
>**PHP**
>Version: 7.1.2
>Memory Limit: 1 GB
>Max Execution Time: 3600
>Upload max size: 256 MB
>
>**Database**
>Type: mysql
>Version: 5.7.22
>Size: 175.1 MB

**Comment by 80kk** [comment]
I have two Nextcoud instances one installed on bare metal Dell server:

`root@cloud:~# lscpu `
`Architecture:        x86_64`
`CPU op-mode(s):      32-bit, 64-bit`
`Byte Order:          Little Endian`
`CPU(s):              8`
`On-line CPU(s) list: 0-7`
`Thread(s) per core:  2`
`Core(s) per socket:  4`
`Socket(s):           1`
`NUMA node(s):        1`
`Vendor ID:           GenuineIntel`
`CPU family:          6`
`Model:               44`
`Model name:          Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz`
`Stepping:            2`
`CPU MHz:             1810.419`
`CPU max MHz:         2395.0000`
`CPU min MHz:         1596.0000`
`BogoMIPS:            4787.95`
`Virtualization:      VT-x`
`L1d cache:           32K`
`L1i cache:           32K`
`L2 cache:            256K`
`L3 cache:            12288K`
`NUMA node0 CPU(s):   0-7`
`Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm` `constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca` `sse4_1 sse4_2 popcnt aes lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid dtherm ida arat flush_l1d`

`root@cloud:~# arch`
`x86_64`

And the other one installed as VM on Proxmox, both VM host and VM guest are 64bit as the one above and both are suffering the same issue.

**Comment by 80kk** [comment]
I didn't see anything, but I can try again later today. What log files exactly I should look for?

**Comment by skjnldsv** [comment]
> nextcloud.log but also php and webserver logs

errors logs preferably ;)

**Comment by 80kk** [comment]
That's very interesting but it seems that the problem has fixed itself. I have checked on 1Gbit link and then at home on 80Mbit to confirm or rule out timeout based on session. I suspect the problem was in PHP/Apache as I haven't changed anything.
