### ISSUE TITLE
Live search Deleted files breaks interface

### ISSUE THREAD

**Issue by hanscomps** [nextcloud/server#16978]
### Steps to reproduce
1.  Login and go to Deleted files (ensure there is a couple of 10000s files listed)
2.  Begin to type a search term
3.

### Expected behaviour
The list is filtered in "realtime" depending on search term typed.

### Actual behaviour
With many files listed (10000s) typing one/two letters breaks the web UI (or at least stalls the site interface).
Can be solved by copy-paste a longer term into the search field.

Suspect that one/two characters results in too many results.
Suggest to limit the results to single page at a time; OR; only search when more than 3 char is typed.

### Server configuration

**Operating system**:
Ubuntu 16.04.3 LTS

**Web server:**
Apache 2.4.18-2ubuntu3.12

**Database:**
5.7.27-0ubuntu0.16.04.1

**PHP version:**
PHP 7.0.33-0ubuntu0.16.04.6 

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 12.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Manual

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no 

**Are you using encryption:** yes/no
no 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 68.0.2 (64-bit)

**Operating system:**
Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Still an issue with a more recent Nextcloud version?

**Comment by skjnldsv** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to **upgrade** to the **latest** version. After that, feel free to reopen.
