### ISSUE TITLE
Apps popover menu empty when installing new app

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#16986]
When installing/enabling a new app, all entries in the "more apps" menu including and below the just enabled app are not visible:
![empty popover when app just enabled](https://user-images.githubusercontent.com/925062/64190676-30ffa080-ce77-11e9-9b79-bef22393c5cb.png)

cc @juliushaertl maybe?

**Comment by szaimen** [comment]
I remember that there was a fix to this -> closing.
Please reopen if this should still happen!
