### ISSUE TITLE
NC17Beta do not connect to LOOL / collabora/online

### ISSUE THREAD

**Issue by ralfi** [nextcloud/server#16983]
### Steps to reproduce
1. Start NC17Beta latest docker image
2. Start LOOL or collabora/code latest docker image
3. Configure NC17Beta with add. app to connect both images
4. Try to create new LOOL file

### Expected behaviour
Open od* file in the browser

### Actual behaviour
No od* file opened, "failed to connect" error at web-interface. Loglevel 0 in NC and debug in LOOL but NO error appears - mystic 

### Server configuration

**Operating system**:
Linux
**Web server:**
Apache
**Database:**
Postgresql
**PHP version:**
latest in docker image

**Nextcloud version:** (see Nextcloud admin page)
17. Beta

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh docker install 

**Where did you install Nextcloud from:**
hub.docker.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No results for failed apps, 
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Default docker image list, no additional apps

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "172.18.1.2"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "17.0.0.5",
        "overwrite.cli.url": "http:\/\/172.18.1.2",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "calendar",
            "deck",
            "socialsharing_email",
            "spreed",
            "polls",
            "ransomware_protection",
            "socialsharing_twitter",
            "external",
            "impersonate",
            "metadata",
            "files_retention"
        ]
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

</details>

### Client configuration
**Browser:**
FF 68.0.2 64Bit
**Operating system:**
Linux Debian 10

### Logs
No relevant entries in nextcloud.log or LOOL log or Browser Logs

</details>

**Comment by ralfi** [comment]
![Bildschirmfoto vom 2019-09-03 14-00-03](https://user-images.githubusercontent.com/294423/64180592-5388be00-ce65-11e9-84f6-e13cb4d504aa.png)


Content Security Policy Error related to CSP form-action ???

**Comment by ralfi** [comment]
Shutting down NC17Beta docker image and starting NC16.0.4 docker image let everything works. Do not restart LOOL docker container oder collabora/code container.

**Comment by kesselb** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Please try the latest beta of richdocuments which should be available for 17 already.

**Comment by ralfi** [comment]
Thanks, i will try this

**Comment by juliushaertl** [comment]
Closing as it is not a server issue. If you still encounter issues please open a bug report at the richdocuments repo: https://github.com/nextcloud/richdocuments
