### ISSUE TITLE
Talk and Text are not in the Groupware bundle

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#16987]
![Add Talk and Text to Groupware bundle no](https://user-images.githubusercontent.com/925062/64190783-62786c00-ce77-11e9-97fd-a00bb296413d.png)

Should Talk and Text not be added to that bundle? cc @karlitschek @jospoortvliet @juliushaertl @skjnldsv

**Comment by karlitschek** [comment]
Well if we want to have this consistent with our website products then Talk is independent from Groupware. And Text is nowhere because it will be in the release. We should delete it from the app store once Nc16 is out of support. @jospoortvliet

**Comment by juliushaertl** [comment]
Text is shipped with the server so no need to have it in the bundle.

**Comment by jancborchardt** [comment]
Alright, so then "Communication bundle" with Talk and Social? (No need to repeat Mail?)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
