### ISSUE TITLE
Icon and tooltip of personal settings verification is off, and content not copyable

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#16988]
In personal settings we have ability to verify website and Twitter account. Some issues here:
- [ ] The icons overlap with the next field
- [ ] The popup doesn’t show at the correct position (the one of the website shows below the Twitter account)
- [ ] Content of the popover is not copyable, so it’s not possible to actually copy the long hash you need to paste to get your website verified

![verification tooltips off position and not copyable](https://user-images.githubusercontent.com/925062/64190868-9784be80-ce77-11e9-9e72-329cc7950e86.png)

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. (no popup is showns anymore)
Please reopen if you can still reproduce this.
