### ISSUE TITLE
Brute force protect triggers  server error upgrade to 16.0.4

### ISSUE THREAD

**Issue by Milokita** [nextcloud/server#16998]
### Steps to reproduce
1. Input the wrong password 

### Expected behaviour
Web page shows wrong password

### Actual behaviour
**This happens after upgrading**
Web page returns server error and has to refresh before shows the page says wrong password 

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache 2.7.3

**Database:** Mysql 10.3.15

**PHP version:** 7.3

**Nextcloud version:** 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade

**Where did you install Nextcloud from:** N/A

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
,"app":"index","method":"POST","url":"\/login","message":{"Exception":"Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException","Message":"An exception occurred while executing 'INSERT INTO `oc_bruteforce_attempts` (`action`, `occurred`, `ip`, `subnet`, `metadata`) VALUES(?, ?, ?, ?, ?)' with params [\"login\", 1567594207, \"137.189.241.15\", \"137.189.241.15\\\/32\", \"{\\\"user\\\":\\\"xingz\\\"}\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value","Code":0,"Trace":[{"file":"\/var\/www\/html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php","line":184,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'INSERT INTO `oc_bruteforce_attempts` (`action`, `occurred`, `ip`, `subnet`, `metadata`) VALUES(?, ?, ?, ?, ?)' with params [\"login\", 1567594207, \"137.189.241.15\", \"137.189.241.15\\\/32\", \"{\\\"user\\\":\\\"xingz\\\"}\"]:\n\nSQLSTATE[HY000]: General error: 1364 Field 'id' doesn't have a default value",{"errorInfo":["HY000",1364,"Field 'id' doesn't have a default value"],
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
> General error: 1364 Field 'id' doesn't have a default value

https://github.com/nextcloud/server/blob/348d9cba06ddd28e757e237cdb94955737a54c33/core/Migrations/Version13000Date20170718121200.php#L531-L536

`id` should have the autoincrement flag? Is it not the case on your instance?

**Comment by Milokita** [comment]
+----+--------------------+------------+-----------------+--------------------+--------------------------------+
| id | action             | occurred   | ip              | subnet             | metadata                       |
+----+--------------------+------------+-----------------+--------------------+--------------------------------+
if you mean the id in the first row then it's not every entry is 0

**Comment by Milokita** [comment]
the property of the table
+----------+---------------------+------+-----+---------+-------+
| Field    | Type                | Null | Key | Default | Extra |
+----------+---------------------+------+-----+---------+-------+
| id       | bigint(20) unsigned | NO   |     | NULL    |       |
| action   | varchar(64)         | NO   |     |         |       |
| occurred | int(10) unsigned    | NO   |     | 0       |       |
| ip       | varchar(255)        | NO   |     |         |       |
| subnet   | varchar(255)        | NO   |     |         |       |
| metadata | varchar(255)        | NO   |     |         |       |
+----------+---------------------+------+-----+---------+-------+

**Comment by Milokita** [comment]
After using following code
`
delete from oc_bruteforce_attempts WHERE  id = 0;
 ALTER TABLE oc_bruteforce_attempts ADD PRIMARY KEY (id);
 ALTER TABLE oc_bruteforce_attempts MODIFY COLUMN id BIGINT(20) not null AUTO_INCREMENT;
`
now the table shows 

`
+----------+------------------+------+-----+---------+----------------+
| Field    | Type             | Null | Key | Default | Extra          |
+----------+------------------+------+-----+---------+----------------+
| id       | bigint(20)       | NO   | PRI | NULL    | auto_increment |
| action   | varchar(64)      | NO   |     |         |                |
| occurred | int(10) unsigned | NO   |     | 0       |                |
| ip       | varchar(255)     | NO   |     |         |                |
| subnet   | varchar(255)     | NO   |     |         |                |
| metadata | varchar(255)     | NO   |     |         |                |
+----------+------------------+------+-----+---------+----------------+
`
and the problem seemed to have resolved
**but it really wonders why the table haven't been alterred since my migration since NC13 and now comes the bug with around 900 entry with ID of zero**

**Comment by kesselb** [comment]
cc @nickvergessen @rullzer

**Comment by rullzer** [comment]
Well that is a good question how that happened. Since it adds it properly in the migration as far as I can see...

**Comment by Milokita** [comment]
> 
> 
> Well that is a good question how that happened. Since it adds it properly in the migration as far as I can see...

Back then the migration, the database is also mysql. This error never occurs untill now, maybe adding code to verify after migration?
