### ISSUE TITLE
Window title does not change during slideshow

### ISSUE THREAD

**Issue by Modanung** [nextcloud/server#17000]
### Steps to reproduce
1. Click on an image, starting the slide show
2. Change slide
3. Look at window title

### Expected behaviour
I think it would make sense if the window title were to be updated to match current image filename.

### Actual behaviour
Currently the Window title stays the same throughout the slide show.

**Comment by kesselb** [comment]
You got the #17000 ;) Would you mind to edit your post and add the [feature request template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Feature_request.md)?

**Comment by skjnldsv** [comment]
Which nextcloud version?

**Comment by Modanung** [comment]
@skjnldsv Indeed that seems like the same issue.
I'm not the one running the instance and would now where to find a version number, but the manual is from Aug 14, 2019.

**Comment by skjnldsv** [comment]
Then it's fixed already :)
Just wait for the next version ;)
