### ISSUE TITLE
NextCloud 10.0.0 shown as 9.1.0.16 in config

### ISSUE THREAD

**Issue by eniac111** [nextcloud/server#1700]
### Steps to reproduce
1. Fresh install of NextCloud from "https://download.nextcloud.com/server/releases/nextcloud-10.0.0.tar.bz2"

### Expected behaviour
'version' must be set to "10.0.0" in config.php

### Actual behaviour

'version' is set to "9.1.0.16" in config.php

### Server configuration
**Operating system**: Alpine Linux, Docker 

**Web server:** Nginx

**Database:** MariaDB 10.1.18

**PHP version:** 7.0 FPM

**Nextcloud version:** 10.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Fresh install

**Where did you install Nextcloud from:** 
https://download.nextcloud.com/server/releases/nextcloud-10.0.0.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tflidd** [comment]
Internally, it still must work with the old owncloud-versioning scheme in order to use the owncloud app store. But you should have a correct `$OC_VersionString = '10.0.1';`

**Comment by nickvergessen** [comment]
As explained by @tflidd above, there is a difference between the internal and the visible version number. This will change mostlikly in the future.
