### ISSUE TITLE
Can't see the file after replacing ldap

### ISSUE THREAD

**Issue by bobt2018** [nextcloud/server#17015]
#### 1.The original ldap
1.1 Create an ldap server in nextcloud

1.2 In advanced, User Home Folder Naming Rule is left blank

1.3 Experts are also default Settings

1.4 Log in ldap user test and create a folder

#### 2.The new ldap
2.1 Create a new ldap server, which is freeipa, and migrate the original ldap users to the new freeipa

2.2 Disable the old ldap and use the new freeipa

2.3 Log in and test,it works well but The original uploaded file could not be found and you can see that a new folder with a different name is created in the server

2.4 The user list also shows that the user names of the two users are different

2.5 Switch back to the original ldap, and you can see the original uploaded files

### Expected behaviour
The hope is that when we go to the new ldap, the old user records will be visible.I have tried it out if the original home foulder is set to uid, so that the two ldap directories are consistent, it is ok.But the current situation is that the previous Settings are created by default with UUID

### Actual behaviour
In fact, after connecting to the new ldap, using the default Settings will cause the creation of a new folder. How can you switch and see the original files and share records

**Comment by blizzz** [comment]
> 2.4 The user list also shows that the user names of the two users are different

Yupp, the name collision protection to avoid data leaking. You'd have to adjust the user id subsequently, manually.
