### ISSUE TITLE
Edit color for birthday calendar

### ISSUE THREAD

**Issue by hubertmeier** [nextcloud/server#17019]
Hi,

editing the color of the birtday calender is not possible, like in the of the online documentation described. Standard is bright yellow, the Nextcloud webapp shows a black text with bright yellow background. Thats ok.

The Android APP DAVx5 takes the color of the calendar and the very bright yellow of the calendar with white text is not readable ... i can choose that the color of the Nextcloud calendar is ignored but thats for all calendars.

We need a setting to change the color of the birthday calendar ...

Thank you.

**Comment by szaimen** [comment]
I think this was implemented in the meantime -> closing.
