### ISSUE TITLE
other apps are interfering during occ command

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#17027]
Audio Player is using its own version of getID3 in the ScannerController
https://github.com/Rello/audioplayer/blob/master/lib/Controller/ScannerController.php#L149-L152

Music is including its version in the app/music.php
https://github.com/owncloud/music/blob/master/app/music.php#L55

when doing an `occ audioplayer:scan -v --all` errors are reported coming from the modified getID3 version of the **Music app**

> Error	PHP	get_resource_type() expects parameter 1 to be resource, int given at /var/www/domains/tnonline.net/htdocs/nextcloud/apps/music/3rdparty/getID3/getid3/getid3.php#437

Problem is, that music has a local modification of the original getID3 which renders it incompatible with any other app using it

- When accessing the AP's `scanForAudios` from the **web-ui**, the Audio Player version is used without issues
- When accessing the AP's `scanForAudios` from the **occ**, the Music version is used and fails

Where is the reason, that two apps interfere on occ level?

**Comment by kesselb** [comment]
Not sure if i can explain it properly :see_no_evil: 

owncloud/music includes the getid3 dependency outside the class: https://github.com/owncloud/music/blob/master/utility/extractorgetid3.php#L17

If the `ExtractorGetID3` dependency is resolved (autoloaded) their getid3 dependency is loaded. The class_exists statement https://github.com/Rello/audioplayer/blob/master/lib/Controller/ScannerController.php#L149-L152 is false then.

Why is this happening from occ and not from web? occ looks for a https://github.com/owncloud/music/blob/master/appinfo/register_command.php file for every app. At this stage the scan command is initialized, the scanner and extractorId3 dependency resolved. For web only the app code (and the nextcloud appframework) are resolved.

**Comment by Rello** [comment]
thank you for the quick answer.
so including the dependency **inside** the class would love it?

**Comment by kesselb** [comment]
I'm not sure :( If they move the include statement inside the constructor we have the same situation. ExtractorGetID3 has a few public methods. I think it should work if they move the include and initialization of getID3 to a "initGetId3" method and call it from every public method.

**Comment by ChristophWurst** [comment]
Hmmmm yeah, composer autoloading can be hard to predict. And as I don't see an explicit include in  Music I assume the autoloader interferes with the manual include of the audio player.

As to the difference between web and CLI is that the bootstrap code is a bit different. I haven't checked in details but it's very well possible that we lazy load apps on the web, while everything's loaded by default on the CLI because in the past apps had to actively register their commands (which is done via info.xml nowadays).

**Comment by ChristophWurst** [comment]
And for the dependency hell problem: there is no real solution. Either both apps use the exact same version, one app drops the dependency or it's shipped with the Nextcloud server.

**Comment by rullzer** [comment]
Yeah nothing we can do about that here. That is the way PHP works.

**Comment by Rello** [comment]
In fact getID3 was once shipped with core. But Lukas replaced it by a minimized own version. 

...anyway. I guess Paul and me will sort this one out...

**Comment by Rello** [comment]
solved by an update of music
https://github.com/owncloud/music/issues/715
