### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long;

### ISSUE THREAD

**Issue by tenchiki** [nextcloud/server#17025]
### Steps to reproduce
1. Using the automated updater to 15.0.11
2.
3.

### Expected behaviour
It should update without errors

### Actual behaviour
Doing the GUI updater, it ended with this error message:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Full log:
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: Change row format for oc_addressbooks ...
Repair info: Change collation for oc_addressbooks ...
Repair info: Change row format for oc_appconfig ...
Repair info: Change collation for oc_appconfig ...
Repair info: Change row format for oc_authtoken ...
Repair info: Change collation for oc_authtoken ...
Repair info: Change row format for oc_bookmarks ...
Repair info: Change collation for oc_bookmarks ...
Repair info: Change row format for oc_bookmarks_folders ...
Repair info: Change collation for oc_bookmarks_folders ...
Repair info: Change row format for oc_bookmarks_tags ...
Repair info: Change collation for oc_bookmarks_tags ...
Repair info: Change row format for oc_bruteforce_attempts ...
Repair info: Change collation for oc_bruteforce_attempts ...
Repair info: Change row format for oc_calendar_invitations ...
Repair info: Change collation for oc_calendar_invitations ...
Repair info: Change row format for oc_calendar_resources ...
Repair info: Change collation for oc_calendar_resources ...
Repair info: Change row format for oc_calendar_rooms ...
Repair info: Change collation for oc_calendar_rooms ...
Repair info: Change row format for oc_calendarchanges ...
Repair info: Change collation for oc_calendarchanges ...
Repair info: Change row format for oc_calendarobjects ...
Repair info: Change collation for oc_calendarobjects ...
Repair info: Change row format for oc_calendarobjects_props ..
Repair info: Change collation for oc_calendarobjects_props ...
Repair info: Change row format for oc_calendars ...
Repair info: Change collation for oc_calendars ...
Repair info: Change row format for oc_calendarsubscriptions ...
Repair info: Change collation for oc_calendarsubscriptions ...
Repair info: Change row format for oc_cards ...
Repair info: Change collation for oc_cards ...
Repair info: Change row format for oc_cards_properties ...
Repair info: Change collation for oc_cards_properties ...
Repair info: Change row format for oc_comments ...
Repair info: Change collation for oc_comments ...
Repair info: Change row format for oc_comments_read_markers ...
Repair info: Change collation for oc_comments_read_markers ...
Repair info: Change row format for oc_credentials ...
Repair info: Change collation for oc_credentials ...
Repair info: Change row format for oc_dav_shares ...
Repair info: Change collation for oc_dav_shares ...
Repair info: Change row format for oc_directlink ...
Repair info: Change collation for oc_directlink ...
Repair info: Change row format for oc_external_applicable ...
Repair info: Change collation for oc_external_applicable ...
Repair info: Change row format for oc_external_config ...
Repair info: Change collation for oc_external_config ...
Repair info: Change row format for oc_external_mounts ...
Repair info: Change collation for oc_external_mounts ...
Repair info: Change row format for oc_external_options ...
Repair info: Change collation for oc_external_options ...
Repair info: Change row format for oc_file_locks ...
Repair info: Change collation for oc_file_locks ...
Repair info: Change row format for oc_filecache ...
Repair info: Change collation for oc_filecache ...
Repair info: Change row format for oc_files_trash ...
Repair info: Change collation for oc_files_trash ...
Repair info: Change row format for oc_flow_checks ...
Repair info: Change collation for oc_flow_checks ...
Repair info: Change row format for oc_flow_operations ...
Repair info: Change collation for oc_flow_operations ...
Repair info: Change row format for oc_gpxpod_options_values ...
Repair info: Change collation for oc_gpxpod_options_values ...
Repair info: Change row format for oc_gpxpod_tile_servers ...
Repair info: Change collation for oc_gpxpod_tile_servers ...
Repair info: Change row format for oc_gpxpod_tracks ...
Repair info: Change collation for oc_gpxpod_tracks ...
Repair info: Change row format for oc_group_admin ...
Repair info: Change collation for oc_group_admin ...
Repair info: Change row format for oc_group_folders ...
Repair info: Change collation for oc_group_folders ...
Repair info: Change row format for oc_group_folders_groups ...
Repair info: Change collation for oc_group_folders_groups ...
Repair info: Change row format for oc_group_folders_trash ...
Repair info: Change collation for oc_group_folders_trash ...
Repair info: Change row format for oc_group_user ...
Repair info: Change collation for oc_group_user ...
Repair info: Change row format for oc_groups ...
Repair info: Change collation for oc_groups ...
Repair info: Change row format for oc_jobs ...
Repair info: Change collation for oc_jobs ...
Repair info: Change row format for oc_migrations ...
Repair info: Change collation for oc_migrations ...
Repair info: Change row format for oc_mimetypes ...
Repair info: Change collation for oc_mimetypes ...
Repair info: Change row format for oc_mounts ...
Repair info: Change collation for oc_mounts ...
Repair info: Change row format for oc_notes_meta ...
Repair info: Change collation for oc_notes_meta ...
Repair info: Change row format for oc_notifications ...
Repair info: Change collation for oc_notifications ...
Repair info: Change row format for oc_notifications_pushtokens ...
Repair info: Change collation for oc_notifications_pushtokens ...
Repair info: Change row format for oc_oauth2_access_tokens ...
Repair info: Change collation for oc_oauth2_access_tokens ...
Repair info: Change row format for oc_oauth2_clients ...
Repair info: Change collation for oc_oauth2_clients ...
Repair info: Change row format for oc_preferences ...
Repair info: Change collation for oc_preferences ...
Repair info: Change row format for oc_properties ...
Repair info: Change collation for oc_properties ...
Repair info: Change row format for oc_schedulingobjects ...
Repair info: Change collation for oc_schedulingobjects ...
Repair info: Change row format for oc_share ...
Repair info: Change collation for oc_share ...
Repair info: Change row format for oc_share_external ...
Repair info: Change collation for oc_share_external ...
Repair info: Change row format for oc_storages ...
Repair info: Change collation for oc_storages ...
Repair info: Change row format for oc_systemtag ...
Repair info: Change collation for oc_systemtag ...
Repair info: Change row format for oc_systemtag_group ...
Repair info: Change collation for oc_systemtag_group ...
Repair info: Change row format for oc_systemtag_object_mapping ...
Repair info: Change collation for oc_systemtag_object_mapping ...
Repair info: Change row format for oc_talk_guests ...
Repair info: Change collation for oc_talk_guests ...
Repair info: Change row format for oc_talk_participants ...
Repair info: Change collation for oc_talk_participants ...
Repair info: Change row format for oc_talk_rooms ...
Repair info: Change collation for oc_talk_rooms ...
Repair info: Change row format for oc_talk_signaling ...
Repair info: Change collation for oc_talk_signaling ...
Repair info: Change row format for oc_trusted_servers ...
Repair info: Change collation for oc_trusted_servers ...
Repair info: Change row format for oc_twofactor_backupcodes ...
Repair info: Change collation for oc_twofactor_backupcodes ...
Repair info: Change row format for oc_twofactor_providers ...
Repair info: Change collation for oc_twofactor_providers ...
Repair info: Change row format for oc_users ...
Repair info: Change collation for oc_users ...
Repair info: Change row format for oc_vcategory ...
Repair info: Change collation for oc_vcategory ...
Repair info: Change row format for oc_vcategory_to_object ...
Repair info: Change collation for oc_vcategory_to_object ...
Repair info: Change row format for oc_whats_new ...
Repair info: Change collation for oc_whats_new ...
Repair info: Change row format for oc_bookmarks_folders_bookmarks ...
Repair info: Change collation for oc_bookmarks_folders_bookmarks ...
Repair info: Change row format for oc_federated_reshares ...
Repair info: Change collation for oc_federated_reshares ...
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Fix component of birthday calendars
Repair info: 1 birthday calendars updated.
Repair step: Fix broken values of calendar objects
[0 / 0]: Fix broken values of calendar objects
Repair step: Registering building of calendar search index as background job
Repair info: Repair step already executed
Repair step: Registering background jobs to update cache for webcal calendars
Repair info: Added 0 background jobs to update webcal calendars
Repair step: Clean up orphan event and contact data
Repair info: 0 events without a calendar have been cleaned up
Repair info: 0 properties without an events have been cleaned up
Repair info: 0 changes without a calendar have been cleaned up
Repair info: 0 contacts without an addressbook have been cleaned up
Repair info: 0 properties without a contact have been cleaned up
Repair info: 0 changes without an addressbook have been cleaned up
Repair step: Remove activity entries of private events
Repair info: Removed 0 activity entries
Updated "dav" to 1.8.2
Checking for update of app "accessibility" in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app "activity" in appstore
Checked for update of app "activity" in appstore
Checking for update of app "bookmarks" in appstore
Update app "bookmarks" from appstore
Checked for update of app "bookmarks" in appstore
Checking for update of app "bookmarks_fulltextsearch" in appstore
Checked for update of app "bookmarks_fulltextsearch" in appstore
Checking for update of app "bruteforcesettings" in appstore
Update app "bruteforcesettings" from appstore
Checked for update of app "bruteforcesettings" in appstore
Checking for update of app "calendar" in appstore
Update app "calendar" from appstore
Checked for update of app "calendar" in appstore
Checking for update of app "cloud_federation_api" in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app "comments" in appstore
Checked for update of app "comments" in appstore
Checking for update of app "contacts" in appstore
Update app "contacts" from appstore
Checked for update of app "contacts" in appstore
Checking for update of app "dav" in appstore
Checked for update of app "dav" in appstore
Checking for update of app "federatedfilesharing" in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app "federation" in appstore
Checked for update of app "federation" in appstore
Checking for update of app "files" in appstore
Checked for update of app "files" in appstore
Checking for update of app "files_external" in appstore
Checked for update of app "files_external" in appstore
Checking for update of app "files_pdfviewer" in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app "files_sharing" in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app "files_texteditor" in appstore
Checked for update of app "files_texteditor" in appstore
Checking for update of app "files_trashbin" in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app "files_versions" in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app "files_videoplayer" in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app "firstrunwizard" in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app "gallery" in appstore
Checked for update of app "gallery" in appstore
Checking for update of app "groupfolders" in appstore
Checked for update of app "groupfolders" in appstore
Checking for update of app "logreader" in appstore
Checked for update of app "logreader" in appstore
Checking for update of app "lookup_server_connector" in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app "nextcloud_announcements" in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app "notes" in appstore
Update app "notes" from appstore
Checked for update of app "notes" in appstore
Checking for update of app "notifications" in appstore
Checked for update of app "notifications" in appstore
Checking for update of app "oauth2" in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app "password_policy" in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app "provisioning_api" in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app "qownnotesapi" in appstore
Checked for update of app "qownnotesapi" in appstore
Checking for update of app "serverinfo" in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app "sharebymail" in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app "support" in appstore
Checked for update of app "support" in appstore
Checking for update of app "survey_client" in appstore
Checked for update of app "survey_client" in appstore
Checking for update of app "systemtags" in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app "theming" in appstore
Checked for update of app "theming" in appstore
Checking for update of app "twofactor_backupcodes" in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app "updatenotification" in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app "workflowengine" in appstore
Checked for update of app "workflowengine" in appstore
Repair step: Repair MySQL collation
Repair info: Change row format for oc_addressbooks ...
Repair info: Change collation for oc_addressbooks ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

The update was unsuccessful. Please report this issue to the Nextcloud community.

### Server configuration

**Operating system**:
Debian9 Stretch
**Web server:**
Apache2 2.4.25-3+deb9u7
**Database:**
Mariadb 10.1.38-0+deb9u1
**PHP version:**
php7.0 7.0.33-0+deb9u3

**Nextcloud version:** (see Nextcloud admin page)
15.0.3 (I think) upgrade to 15.0.11
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated a few times
**Where did you install Nextcloud from:**
I didn't log it, probably from the website
**Signing status:**
<details>
????
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
that page won't show as it is stuck in update mode
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.1.0
  - activity: 2.8.2
  - bookmarks: 2.0.3
  - bookmarks_fulltextsearch: 1.2.0
  - bruteforcesettings: 1.4.0
  - calendar: 1.6.6
  - cloud_federation_api: 0.1.0
  - comments: 1.5.0
  - contacts: 3.1.3
  - dav: 1.8.2
  - federatedfilesharing: 1.5.0
  - federation: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.4.0
  - files_sharing: 1.7.0
  - files_texteditor: 2.7.0
  - files_trashbin: 1.5.0
  - files_versions: 1.8.0
  - files_videoplayer: 1.4.0
  - firstrunwizard: 2.4.0
  - gallery: 18.2.0
  - groupfolders: 3.0.2
  - logreader: 2.0.0
  - lookup_server_connector: 1.3.0
  - nextcloud_announcements: 1.4.0
  - notes: 3.0.2
  - notifications: 2.3.0
  - oauth2: 1.3.0
  - password_policy: 1.5.0
  - provisioning_api: 1.5.0
  - qownnotesapi: 19.4.0
  - serverinfo: 1.5.0
  - sharebymail: 1.5.0
  - support: 1.0.0
  - survey_client: 1.3.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - updatenotification: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - admin_audit
  - encryption
  - gpxpod
  - rainloop
  - spreed
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.tenchiki.net",
            "web.tenchiki.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/www.tenchiki.net\/nextcloud",
        "dbtype": "mysql",
        "version": "15.0.6.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
I'm running it in a VM with local storage, mariadb is running in another VM also with local storage

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
none
### Client configuration
**Browser:**
firefox 69.0
**Operating system:**
ArchLinux (x86_64)
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20151012/php_mysqli.dll' - /usr/lib/php/20151012/php_mysqli.dll: undefined symbol: mysqlnd_connect in Unknown on line 0                                                                [Thu Sep 05 07:43:45.818034 2019] [ssl:warn] [pid 6613] AH01909: www.tenchiki.net:443:0 server certificate does NOT include an ID which matches the server name           [Thu Sep 05 07:43:45.818958 2019] [ssl:info] [pid 6613] AH01914: Configuring server www.tenchiki.net:443 for SSL protocol
[Thu Sep 05 07:43:45.819442 2019] [ssl:info] [pid 6613] AH02568: Certificate and priv
ate key www.tenchiki.net:443:0 configured from /etc/letsencrypt/live/www.tenchiki.net
-0001/fullchain.pem and /etc/letsencrypt/live/www.tenchiki.net-0001/privkey.pem
[Thu Sep 05 07:43:46.001405 2019] [mpm_prefork:notice] [pid 6613] AH00163: Apache/2.4
.25 (Debian) mod_scgi/1.13 OpenSSL/1.0.2r mod_gnutls/0.8.2 GnuTLS/3.5.8 configured --
 resuming normal operations
[Thu Sep 05 07:43:46.001464 2019] [core:notice] [pid 6613] AH00094: Command line: '/u
sr/sbin/apache2'
[Thu Sep 05 07:43:49.891013 2019] [ssl:info] [pid 10656] [client 104.149.35.146:44372
] AH01964: Connection to child 0 established (server www.tenchiki.net:443)
....
[Thu Sep 05 11:35:48.765615 2019] [ssl:info] [pid 12440] SSL Library Error: error:140
8F10B:SSL routines:SSL3_GET_RECORD:wrong version number                              
[Thu Sep 05 11:35:48.765642 2019] [ssl:info] [pid 12440] [client 110.249.212.46:58093
] AH01998: Connection closed to child 4 with abortive shutdown (server www.tenchiki.n
et:443)
...
[Thu Sep 05 11:35:48.845483 2019] [ssl:info] [pid 12095] SSL Library Error: error:140
8F10B:SSL routines:SSL3_GET_RECORD:wrong version number                              
[Thu Sep 05 11:35:48.845497 2019] [ssl:info] [pid 12095] [client 110.249.212.46:22381
] AH01998: Connection closed to child 1 with abortive shutdown (server www.tenchiki.n
et:443)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
uh, this is a 14MB file, sure you want the whole thing? Here is the last few entries (which seem to be all identical except for the timestamp)
```
Insert your Nextcloud log here
```
{"reqId":"XXFZ6cComwsAAC82lHUAAAAA","level":3,"time":"2019-09-05T18:54:33+00:00","remoteAddr":"104.149.35.146","user":"--","app":"PHP","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/files\/scotty\/","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.3git (Nextcloud)","version":"15.0.6.1"}
{"reqId":"XXFZ78ComwsAADCYNVAAAAAE","level":3,"time":"2019-09-05T18:54:40+00:00","remoteAddr":"104.149.35.146","user":"--","app":"PHP","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/files\/scotty\/","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.3git (Nextcloud)","version":"15.0.6.1"}
{"reqId":"XXFZ9MComwsAACmhelwAAAAD","level":3,"time":"2019-09-05T18:54:45+00:00","remoteAddr":"104.149.35.146","user":"--","app":"PHP","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/files\/scotty\/","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.3git (Nextcloud)","version":"15.0.6.1"}
{"reqId":"XXFZ@cComwsAABnTQQAAAAAA","level":3,"time":"2019-09-05T18:54:49+00:00","remoteAddr":"104.149.35.146","user":"--","app":"PHP","method":"PROPFIND","url":"\/nextcloud\/remote.php\/dav\/files\/scotty\/","message":"You are using a fallback implementation of the intl extension. Installing the native one is highly recommended instead. at \/var\/www\/nextcloud\/3rdparty\/patchwork\/utf8\/src\/Patchwork\/Utf8\/Bootup\/intl.php#18","userAgent":"Mozilla\/5.0 (Linux) mirall\/2.5.3git (Nextcloud)","version":"15.0.6.1"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by tenchiki** [comment]
It seems that the real, unfixable problem is that the update process tries to create tables with varchar(255) and utf8mb4, which this release of mariadb doesn't support that big. I've been fixing the "alter table' ones as they happen, but I can't figure out how to fix the 'create table' ones...

**Comment by kesselb** [comment]
I'm not sure how to respond :confused: You can configure mariadb to support tables with varchar(255) and utf8mb4 (=> A) or if not possible or you don't want to turn it off (=> B). What else can I do?
