### ISSUE TITLE
[Feature] Sharing with external email ( not federated )

### ISSUE THREAD

**Issue by freechelmi** [nextcloud/server#1703]
### Steps to reproduce
1. type an email address with a domain not federated like user@gmail.com
### Expected behaviour

User expect that a custom share link would be generated and sent to this email, later on , the share could be deactivated so this link would not work anymore.
### Actual behaviour

Error is returned : federated domain cannot be reach
### Server configuration

**Operating system**: Any

**Web server:** Any

**Database:** Any

**PHP version:** Any

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** NO

**Where did you install Nextcloud from:** zip file

</details>

**Are you using external storage : NO 

**Are you using encryption:** yes/no

**Are you using an external user-backend,  : NO

Already discussed here : 

https://github.com/owncloud/core/issues/20074

**Comment by nickvergessen** [comment]
Work in progress for this in https://github.com/nextcloud/server/pull/657

**Comment by freechelmi** [comment]
Just Great to see this WiP . even if this is not the prettiest, this should work.

I have to say that on OC side this has been stalled ...
