### ISSUE TITLE
Is Nextcloud planning Fido2 authentication?

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#17038]
I know that nextcloud today supports the U2F standard, I was wondering if it could be extended with the Fido2 / Webauthn standard in particular with the Yubico keys.
Thanks

**Comment by rullzer** [comment]
So this is an answer with multiple layers.

1. We have been looking into webauthn in general and it certainly is on the list of things to look at
2. There is no clear roadmap right now for this.
3. We are still debating what part of webauthn to support
  * right now we are mostly looking at using full passwordless

So the plans are there but I can't give any sensible ETA ;)

**Comment by awesome-manuel** [comment]
https://nextcloud.com/blog/nitrokey-and-nextcloud-collaborate-on-securing-private-clouds/

**Comment by tigernero79** [comment]
I use yubico 5 nfc top, yubico otp openpgp, fido2, u2f, oath etc etc top key

**Comment by sunjam** [comment]
[Webauthn has been released](https://apps.nextcloud.com/apps/twofactor_webauthn) to the app store.  Haven't had a chance to test it, but [here is the Github page](https://github.com/michib/nextcloud_twofactor_webauthn/).

**Comment by tigernero79** [comment]
i will test it but you know it will become an official plugin like u2f, will it replace it?  or they can go hand in hand.

**Comment by tigernero79** [comment]
I can't find it in applications, should it be loaded manually in the app folder?

**Comment by g6094199** [comment]
should be fixed in [NC 19](https://github.com/nextcloud/server/pull/19858). For me it works out of the box.
