### ISSUE TITLE
User changing password disconnects other accounts.

### ISSUE THREAD

**Issue by cooljacob204** [nextcloud/server#17035]
### Steps to reproduce
1. Two users logged in
2. One user changes their password
3. Other user gets disconnected

### Expected behaviour
No one should get disconnected

### Actual behaviour
Other user will often get disconnected. A quick test I do is open the admin monitoring app which polls the server often. Then when I have a user change their password the admin get disconnected.

### Server configuration
Happens on a fresh snap/docker install. Tested with snap on ubuntu and centos and on the official docker image.

**Operating system**:
Centos, Ubuntu

**Web server:**
Apache

**Database:**
Mysql3, sqlite

**PHP version:**
Whatever ships with latest docker & snap versions.

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Docker / Snap

**Other**

Forgive me for deleting the rest of the sections that you are asking for. It's literally a fresh run of the snap/docker image that is failing and I am not seeing any errors. From what I can tell, it is dumping sessions.

docker run -d -p 8081:80 nextcloud

My docker daemon is running on Ubuntu 18.04. Tested snap on Centos and Ubuntu.

Thanks!

**Comment by rullzer** [comment]
I assume they are connected on the same account.
Because then it is expected. When you change your passwords the apptokens are updated. But all other active websessions are killed.

**Comment by cooljacob204** [comment]
When user1 changes the password user2, user3 and user4 will be booted out if they attempt to change passwords or do any actions for a little bit.

For example:

Kate is online and looking at the monitoring page. Bob then changes their password on a separate device. Bob's session remains and is fine but Kate is disconnects and must log in again. Other users also usually get booted off.

Out of 5-6 users 4 will usually get booted off if one user updates their password.

**Comment by kesselb** [comment]
cc @skjnldsv the bot is going wild :see_no_evil:
