### ISSUE TITLE
Capabilities - theming - dark mode 

### ISSUE THREAD

**Issue by marinofaggiana** [nextcloud/server#17030]
- [x] Android @tobiasKaminsky 
- [x] Desktop @camilasan 
- [x] iOS @marinofaggiana 
- [x] Server @nextcloud/server-triage 

Under iOS we have implemented the dark mode, it would be nice to have the darkmode settings on server side under the theming for possible automatic client-side activation.

theming = {
    "dark-mode" = 1 or 0;
    ......
}

**Comment by rullzer** [comment]
While I guess we can easily expose this @juliushaertl 
I guess it would make more sense to follow the OS preference here. So if dark mode is set on iOS use that. If not then not. Or am I missing something?

**Comment by marinofaggiana** [comment]
The dark mode on iOS well be available from the next iOS 13, and the old devices will not have this os feature, and, independently of OS, the theming capabilities should contain this setting

**Comment by juliushaertl** [comment]
Note that the dark-mode is no theming but an accessibility setting, but I agree that we should also expose those though the capabilities. However we should always respect system settings first, same for Android and Desktop. 

cc @tobiasKaminsky @misch7 @nextcloud/accessibility

**Comment by tobiasKaminsky** [comment]
As chatted with @jancborchardt we agree with @rullzer and dark mode should only follow os settings, but not server side options.
