### ISSUE TITLE
Nextcloud bad share & webdav URL

### ISSUE THREAD

**Issue by BedoM** [nextcloud/server#17041]
Hello !

I have a little problem on my fresh install of nextcloud ( replace owncloud !!)

Here is my infra:
I have an apache listening on port 443 and 80 and redirecting to my dockers who turns them on 127.0.0.1:XXXX

All work perfectly except sharing and webdav on nextcloud.

I have a problem with my Nextcloud instance.
When I want to share files with a URL, the generic url uses ip or walks nextcloud (http://127.0.0.1:8080/s/D6FkbYiCsd5izTo) and not http://mydomainname.com/s/D6FkbYiCsd5izTo

Problem simalary for webdav

I changed this value on config.php:

 'overwrite.cli.url' => 'http://mydomainname.com'

and

0 => 'mydomainname.com'

And that did not solve the sharing problem.

On my owncloud y don't have this bug.. 

Do you have an idea ?

Thank you for your help

Nextcloud 16.0.4** on docker (latest stable version)
Server version: Apache/2.4.38 (Debian 10)

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/16/admin_manual/configuration_server/reverse_proxy_configuration.html

You need to ensure trusted_proxies are set and overwriteprotocol (because apache2 does not forward the protocol)

**Comment by BedoM** [comment]
I set the overwritehost and overwriteprotocol

its work, thank you so much
