### ISSUE TITLE
macOS calendar: Can't search for delegates to add

### ISSUE THREAD

**Issue by labor4** [nextcloud/server#17053]
I'm trying to test the new proxy delegation feature in NC17b3 with iCal Mojave Macos. No success.

According to [sabredav](http://sabre.io/dav/caldav-proxy/) there are sub-principals needed. Do I need to activate/configure something in NC in advance?

Following are apache2 access logs. No entries in apache2 error log. No entries in NC log.

**iCal request which wants to display the current access ("Which accounts do I have access to?")**
`1.2.3.4 - - [08/Sep/2019:02:53:53 +0200] "REPORT /nc/11/remote.php/dav/principals/users/MYUSER/calendar-proxy-write/ HTTP/1.1" 401 450 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)
1.2.3.4 - - [08/Sep/2019:02:53:53 +0200] "REPORT /nc/11/remote.php/dav/principals/users/MYUSER/calendar-proxy-write/ HTTP/1.1" 207 537 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)
1.2.3.4 - - [08/Sep/2019:02:53:53 +0200] "REPORT /nc/11/remote.php/dav/principals/users/MYUSER/calendar-proxy-read/ HTTP/1.1" 401 450 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)
1.2.3.4 - - [08/Sep/2019:02:53:53 +0200] "REPORT /nc/11/remote.php/dav/principals/users/MYUSER/calendar-proxy-read/ HTTP/1.1" 207 536 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)`

**iCal request which wants to autocomplete/search against existing user, to share my account to (Try to set up new)**
`1.2.3.4 - - [08/Sep/2019:02:55:38 +0200] "REPORT /nc/11/remote.php/dav/principals/calendar-resources/ HTTP/1.1" 401 450 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)
1.2.3.4 - - [08/Sep/2019:02:55:38 +0200] "REPORT /nc/11/remote.php/dav/principals/calendar-resources/ HTTP/1.1" 207 282 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)
1.2.3.4 - - [08/Sep/2019:02:55:38 +0200] "REPORT /nc/11/remote.php/dav/principals/calendar-resources/ HTTP/1.1" 207 282 "-" "Mac+OS+X/10.14.6 (18G87) CalendarAgent/416.5.1" (proxy:10.24.62.1)`

**via iCal/Calendar Macos**
- Tested against an older user
- Tested AGAINST a fresh user from an old one (fresh is NC17b3 created)
- Tested FROM a fresh user against an old one.

**Expected**
Some kind of content feedback/ index/ search result.

**Actual**
Error displayed by iCal: roughly translated, "You cannot give SEARCHUSER access to your account because SEARCHUSER could not be found on server".

**Comment by georgehrke** [comment]
Sadly Nextcloud will need further patches for macOS, because macOS is not implementing a couple of things correctly. (Principal property search for multiple principal collections and proper handling of response code 204 for PropPatch)

The calendar app will introduce its own configuration interface for delegates.

**Comment by labor4** [comment]
ah the old macos caldav special case. why am i not surprised. 
thanks a lot!

**Comment by ChristophWurst** [comment]
> [georgehrke](/georgehrke) added this to the [Nextcloud 18](/nextcloud/server/milestone/77) milestone [on 8 Sep](#event-2616937035)

@georgehrke please check if this is doable for 18 or if we should move to 19 :)

**Comment by georgehrke** [comment]
Not doable for 18 anymore. For whatever reason, macOS calendar ever only searches one out of multiple principal collections. This would require further debugging. 

My current approach for this would be adding a special plugin that checks for the macOS calendar user agent and automatically sets "apply-to-principal-collection-set" to true. That change might very well break other things for macOS, so we should do it later and properly test it.

**Comment by labor4** [comment]
didn't they do the same with contacts?
i think there was never a multi-abook-same-account capability on macos even though i think it was the carddav concept.

**Comment by georgehrke** [comment]
> i think there was never a multi-abook-same-account capability on macos even though i think it was the carddav concept.

As far as I'm aware of there is a similar issue with calendar-homes and address-book-homes. CalDAV and CardDAV allow multiple homes, macOS ever only picks one.

**Comment by labor4** [comment]
may I ask if this is planned for NC 19?

**Comment by georgehrke** [comment]
This is not planned for a release any time soon, I don’t have time for it. 
If someone wants to contribute a PR I’d be happy to give pointers

**Comment by rotdrop** [comment]
> This is not planned for a release any time soon, I don’t have time for it. If someone wants to contribute a PR I’d be happy to give pointers

#36800
