### ISSUE TITLE
Migration from OwnCloud to NextCloud does not work

### ISSUE THREAD

**Issue by onknows** [nextcloud/server#17054]
The migration guide offers a number of paths for migrating from OwnCloud to NextCloud. At this point I can confirm that the first two options do not work.

### Steps to reproduce
Migration from OwnCloud 10.0.0 to NextCloud 12.0.0 
1. Install fresh OwnCloud 10.0.0 with PostgreSQL database
2. Upgrade to NextCloud 12.0.0

### Expected behaviour
Upgrade

### Actual behaviour
Error

> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_addressbooks ALTER id TYPE BIGSERIAL': SQLSTATE[42704]: Undefined object: 7 ERROR: type "bigserial" does not exist

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache2

**Database:**
PostgerSQL
**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
12.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
tar.gz from downloads

**Signing status:**

**Comment by j-ed** [comment]
Similar PostgreSQL problems have already been reported and solved in the past. It might work for you too: https://github.com/nextcloud/server/issues/4504

**Comment by skjnldsv** [comment]
As the version of the software you've reported this for has [reached *end of life*](https://nextcloud.com/changelog/), I will close this ticket. If this is still happening after an upgrade to the latest version, feel free to reopen
