### ISSUE TITLE
Owncloud 10 to Nextcloud 12 migration issue

### ISSUE THREAD

**Issue by gennari-dkt** [nextcloud/server#17069]
Hi there,
I am trying to migrate my Owncloud to Nextcloud. Actually I have Owncloud 10.0, so I downloaded Nextcloud 12 as from documentation. I use LDAP authentication and I am trying manual procedure.

Unfortunately during the procedure I get this error:

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DROP INDEX ldap_dn_groups':

SQLSTATE[42704]: Undefined object: 7 ERROR:  index "ldap_dn_groups" does not exist
Update failed`

I checked on database and the index is present. I tried to delete it manually but no way.

Without LDAP installation I managed to migrate Owncloud to Nextcloud.

Can anyone help me please?

Very kind regards.

Alessio

**Comment by kesselb** [comment]
cc @blizzz @nickvergessen

**Comment by nickvergessen** [comment]
Should require a similar hack like https://github.com/nextcloud/server/blob/master/lib/private/Repair/Owncloud/SaveAccountsTableData.php#L81

**Comment by gennari-dkt** [comment]
For the moment I resolved deleting oc_ldap_group tables in my Postgres instance.

**Comment by szaimen** [comment]
As there is now a way to migrate from any recent owncloud version to Nextcloud 20, I am closing this issue.
