### ISSUE TITLE
apps "files_rightclick" and "support" not compatible with Nextcloud 18

### ISSUE THREAD

**Issue by jameslao** [nextcloud/server#17073]
> sudo nextcloud.occ app:enable support
> App "Support" cannot be installed because it is not compatible with this version of the server.
> sudo nextcloud.occ app:enable files_rightclick
> App "Right click" cannot be installed because it is not compatible with this version of the server.

**Comment by rullzer** [comment]
Well 18 development just started so this is not really a bug.
