### ISSUE TITLE
File / Folder search result should allow bulk actions

### ISSUE THREAD

**Issue by mark-orion** [nextcloud/server#17083]
**Is your feature request related to a problem? Please describe.**
I want to search for and delete multiple files / folders. It is annoying that I only get a folder list as result that does not allow simple bulk actions.

**Describe the solution you'd like**
Search results should appear in EXACTLY the same way as the standard file / folder view that includes checkboxes and the action menu.

**Describe alternatives you've considered**
Deleting the files from within the local folder on the Desktop computer. However this does not work in this case as I have put these files that were synced by accident on the ignore list. I want to delete them from the server but keep them in the local folder.

**Comment by kesselb** [comment]
Is this still relevant? If so could you try to rephrase the request. I have the option to select multiple files from a search result and delete them. Probably you mean something different?

**Comment by neufeind** [comment]
> Is this still relevant? If so could you try to rephrase the request. I have the option to select multiple files from a search result and delete them. Probably you mean something different?

In the list-view I see checkboxes to select files (or all) and perform an action on them. But if I do a search I get a list without checkboxes / actions. I can only click on the file/folder and get transfered there, where I have a list with chechboxes again (but not a search-result anymore).

**Comment by kesselb** [comment]
![Peek 2020-03-03 09-41](https://user-images.githubusercontent.com/3902676/75757726-2abd8480-5d33-11ea-8f8f-47b8a43e4707.gif)

Bulk actions are allowed for files in the same folder but not for search results in other folders.

**Comment by szaimen** [comment]
Now that we have unified search, the search looks pretty different. Please open a new issue if you should experience any problem with that. Thanks!
