### ISSUE TITLE
List Apps with and without updates

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#17088]
It would be very useful if the updater would list not only apps with updates, but also **currently installed apps with_out_** updates.

![Screenshot_20190910-130539_Opera](https://user-images.githubusercontent.com/1469150/64608998-35264380-d3cc-11e9-811c-ac75062fae0c.jpg)

**Comment by kesselb** [comment]
I think this is already the case.

cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah, as you can see above, the list it says `All apps have an update for this version available`.
Otherwise you would see a list there of course.

**Comment by Gatak** [comment]
How could I have missed that ;)

Anyway, wasn't there a bug in 16.0.4 that showed all apps as having an update to NC17?

**Comment by nickvergessen** [comment]
Not sure if it was fixed in 16.0.4 or is coming with 16.0.5, but yeah there was a bug.

**Comment by Gatak** [comment]
The bug is still there. :( it should really be fixed quickly...

**Comment by nickvergessen** [comment]
Yeah its in the 16.0.5 release:
https://github.com/nextcloud/server/pull/16818
