### ISSUE TITLE
use Push notification instead of fetch

### ISSUE THREAD

**Issue by IanNicki** [nextcloud/server#17081]
### Offer push-notification for updating all devices
Nextcloud Calendar should offer Push-notification to be used in groups. When an Nextcloud member changes it's event time other should be notified directly and don't have to manually update their calendar app on their iPhone for example.

Thank you guys a lot for your great work until now

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
