### ISSUE TITLE
Fatal errors in the log about file sizes

### ISSUE THREAD

**Issue by jfha73** [nextcloud/server#17096]
Hey guys,

We are getting this on NextCloud 16.0.4:

> {"reqId":"itTQd7XqdC6bK607quyV","level":4,"time":"2019-09-10T20:02:49+00:00","remoteAddr":"23.240.220.239","user":"Lauren Cabanas","app":"webdav","method":"PUT","url":"/remote.php/dav/uploads/Lauren%20Cabanas/web-file-upload-a498e1805e928b7dea71d3aa52672743-1568145398607/10485760","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 10485760 got 8175616","Code":0,"Trace":[{"file":"/var/www/html/apps/dav/lib/Connector/Sabre/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"/var/www/html/apps/dav/lib/Upload/UploadFolder.php","line":45,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["10485760",null]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Upload\\UploadFolder","type":"->","args":["10485760",null]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["uploads/Lauren Cabanas/web-file-upload-a498e1805e928b7dea71d3aa52672743-1568145398607/10485760",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://example.com/remote.php/dav/uploads/Lauren%20Cabanas/web-file-upload-a498e1805e928b7dea71d3aa52672743-1568145398607/10485760","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https://example.com/remote.php/dav/uploads/Lauren%20Cabanas/web-file-upload-a498e1805e928b7dea71d3aa52672743-1568145398607/10485760","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https://example.com/remote.php/dav/uploads/Lauren%20Cabanas/web-file-upload-a498e1805e928b7dea71d3aa52672743-1568145398607/10485760","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://example.com/remote.php/dav/uploads/Lauren%20Cabanas/web-file-upload-a498e1805e928b7dea71d3aa52672743-1568145398607/10485760","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/html/apps/dav/lib/Server.php","line":316,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/html/remote.php","line":163,"args":["/var/www/html/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/html/apps/dav/lib/Connector/Sabre/File.php","Line":228,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36","version":"16.0.4.1","id":"5d780afd5c2ce"}

> 

What is this about?

**Comment by kesselb** [comment]
Hey, 

unfortunately without the issue template there is not much we can do. We have some of these reports and did a lot of testing. Would you mind to look at the other issues https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+expected+filesize+got? For some mod_reqtimeout was a problem for others http2. I don't know a reliable way how to fix this error.
