### ISSUE TITLE
Update failed; "core/shipped.json is not available"

### ISSUE THREAD

**Issue by haverholm** [nextcloud/server#17092]
### Steps to reproduce
Update from v 16.0.1 to 16.0.4 using the updater app

### Expected behaviour
The system should successfully update.

### Actual behaviour
The update process stalls at "Delete old files" with the comment "core/shipped.json is not available"

### Server configuration

**Operating system**: Linux (Vague, I know. It's a shared server)

**Web server:** Apache

**Database:** MySQL  5.6

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated (or tried)

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

**The system is stalled mid-update and I cannot access my admin panel**
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
**The system is stalled mid-update and I cannot access my admin panel**
```

**Comment by niowniow** [comment]
I'm having the same/similar issue updating from
Current version is 18.0.1.
Update to Nextcloud 18.0.3 available. (channel: "beta")

**Comment by skjnldsv** [comment]
Looks like a wrongly done update.
The file is present in the release archives.

Please make sure to tests against stable. Latest is 19.0.2

**Comment by Klench** [comment]
I also have this issue. I am currently on 18.0.1.
A core folder did not exist but a core file instead, with the same data as in shipped.json. I created a core folder and added a shipped.json file from the Nextcloud archive but I still get the same error. What can I do?
