### ISSUE TITLE
Support for Emoji codes from Github flavored markdown

### ISSUE THREAD

**Issue by Salokyn** [nextcloud/server#17094]
**Describe the solution you'd like**
Having shortcodes like `:thumbsup:` printed as 👍  (it works on github 😄) in cards titles and descriptions

**Describe alternatives you've considered**
Any, UTF8 works well but you have to copy/paste the emoji from elsewhere

**Comment by Salokyn** [comment]
Since a lot of Nextcloud app uses Markdown (text, notes, deck...). Does it exists a common Markdown module every app could rely on instead of developping the same thing everywhere?

**Comment by Salokyn** [comment]
I thought I created this issue in nextcloud/deck project ... Was I innatentive or has my issue been moved here 🤔

**Comment by skjnldsv** [comment]
Done for quite some time already :)
