### ISSUE TITLE
Cannot manage users in Android phone in NC17.0. Users list does not slide sideways in Chrome web browser 

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#17109]
NC17.0, Ubuntu 18.04, Nginx
In the Chrome web browser in Android phone the users list is not responsive. Cannot slide sideways. Can therefore not delete a user. And not give permissions. Only the coloúmns Username and Shown name are accessible.

**Comment by Octopus2** [comment]
I can confirm this on my Android-Smartphone with chrome and Nextcloud 17.0.1 RC. It only works when you slide sideways in the Menue-header.

On 16.0.5 it works, but there is no burgermenue in usermanagement...

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
@GretaD :)

**Comment by szaimen** [comment]
I can still reproduce this on NC21.0.2

**Comment by GretaD** [comment]
> I can still reproduce this on NC21.0.2

Hi, which device did you use to reproduce it?

**Comment by szaimen** [comment]
> Hi, which device did you use to reproduce it?

On an Android (11) Smartphone with a Chromium 90 based browser.

**Comment by rollanders** [comment]
Sine at least NC 17  I can not add users from my Android phone. The user interface is just not adapted to the screen of mobile devices. I have not tried it on iPhone but I doubt it is different.

**Comment by GretaD** [comment]
thank you both, i will try to investigate. I asked about the device because I'm trying to reproduce it on small screen and it works fine, so i dont think its a screen-size problem.

**Comment by szaimen** [comment]
Did you try on Android with a Chromium based browser? I suppose it is this combination specifically that doesn't work...

**Comment by GretaD** [comment]
> Did you try on Android with a Chromium based browser? I suppose it is this combination specifically that doesn't work...

No, I dont have it set it up on my android, but will do.

**Comment by rollanders** [comment]
Chromium is the default browser on Android. I have not tried it since a long time. I did it again and found it does work but badly.

**Comment by rollanders** [comment]
This behaviour is present in the default webbbrowser in Android (Chrome, Android10, Huawei P20 Pro). I cannot slide the user sideways and change Group or Memory space. But it works in Firefox. Same behaviour in NC19, NC20, NC21

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by rollanders** [comment]
It is working ok in 25.0.2.Roland

Skickat från Yahoo Mail på Android 
 
  På mån, jan. 2023 klockan 15:58, Simon ***@***.***> skrev:   


Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by szaimen** [comment]
Thanks for verifying!
