### ISSUE TITLE
Speed shaping per user/group

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#17104]
**Is your feature request related to a problem? Please describe.**
Feature request

**Describe the solution you'd like**
We provide S3 access to our storage. We have several groups of users. It will be nice to configure speed shaping levels for every group.  
f.e. group 1 will guaranteed have 50% of all bandwidth (inside this channel the speed will be divided equally for every active user)  
group 2 will have 30%, group 3 else.  
Or to manually set the maximum speed to every group.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
