### ISSUE TITLE
Back button navigation broken

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#17108]
I just noticed that the back button navigation in the filelist is broken.

1. Go to your 17 nextcloud
2. Go into a random floder
3. Press the back button

expected: going back

actual: url changes but not navigating back

@juliushaertl @skjnldsv

**Comment by skjnldsv** [comment]
Again? Was fixed in https://github.com/nextcloud/server/pull/15640
Ref #15265

**Comment by weeman1337** [comment]
It looks like the `OC.Util.History` is missing the wiring to the browser's pop state.

@ChristophWurst introduced https://github.com/nextcloud/server/blob/master/core/src/OC/util-history.js. Maybe he knows best where to wire the event.

e.g. putting

```
window.addEventListener('popstate', OC.Util.History._onPopState.bind(OC.Util.History));
```
into the file's `app.js` makes it working.

**Comment by ChristophWurst** [comment]
I just moved some code around for cleanup.

What went missing is the code from https://github.com/nextcloud/server/commit/0d43ef06f5dbd05edfe61e9c78461e15312834ea#diff-c493b80ad1a9bcfa6b69637097972371R1349-R1351, I guess.

**Comment by GretaD** [comment]
it's also broken on my 18 alfa instance

**Comment by JackVen** [comment]
Same here when Im inside a folder and press the back button the url changes but not the page inside the folder.
