### ISSUE TITLE
DetailsView ScrollContainer - "Add to project" + "Federated-Box" disable / hide

### ISSUE THREAD

**Issue by krayzie0x10** [nextcloud/server#17118]
**Server configuration**
Operating system: Linux Ubuntu x64
Web server: Apache
Database: mysql
PHP version: 7.1
Nextcloud version: 16.0.4

**Feature Request**
In the "DetailsView ScrollContainer", the right section which opens when you share a File or Folder, the "Add to Project" as well as the "Federated / Name - Box" should be hideable.

In our company we want to make as lean as possible because we only use the "share by link" function for external communication. 

![nextcloud-details](https://user-images.githubusercontent.com/39626044/64838915-a6950a80-d5f5-11e9-9102-20b903f1c426.png)

**Comment by szaimen** [comment]
Hi, as a workaround you are free to hide this feature with the custom_css app.
