### ISSUE TITLE
remote.php/dav/ not working for syncing calendar events

### ISSUE THREAD

**Issue by stratoss** [nextcloud/server#17119]
### Steps to reproduce
1. Install the Calendar app
2. Install the DAVx5 on android phone
3. Try to fetch the calendar lists

### Expected behaviour
We have 2 deployments of NextCloud. On the first, everything works like a breeze. However, on the second we expected to see a list with calendars, with ability to sync them.

### Actual behaviour
The new calendars aren't being shown, therefore can't sync

### Server configuration

**Operating system**: Gentoo Base System release 2.2

**Web server:** Apache/2.4.39

**Database:** MySQL Ver 14.14 Distrib 5.6.43

**PHP version:** 7.2.16 

**Nextcloud version:** Nextcloud 16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Both fresh install and upgrade from 16.0.3

**Where did you install Nextcloud from:** ZIP package from the website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - apporder: 0.7.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - event_update_notification: 0.3.4
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - loginviapost: 1.0.6
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - spreed: 6.0.4
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "app_install_overwrite": [
            "loginviapost"
        ],
        "defaultapp": "spreed",
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** N/A

**Operating system:** N/A

#### Web server error log
<details>
<summary>Web server error log</summary>

[Fri Sep 13 06:03:36.493088 2019] [authz_core:error] [pid 3265] [client ***REMOVED SENSITIVE VALUE***:58752] AH01630: client denied by server configuration: ***PATH_TO_NEXTCLOUD***/nextcloud/data/.ocdata
[Fri Sep 13 06:04:03.324394 2019] [authz_core:error] [pid 29728] [client ***REMOVED SENSITIVE VALUE***:58780] AH01630: client denied by server configuration: ***PATH_TO_NEXTCLOUD***/nextcloud/config
[
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Too much sensitive information here. No errors / exceptions related to the Calendar or DAV.
</details>

#### Browser log
<details>
<summary>Browser log</summary>
N/A
</details>

**Comment by wiswedel** [comment]
@stratoss Do you see any errors regarding DAV config from the check under Settings -> Administration -> Overview?

**Comment by stratoss** [comment]
No, just some performance ones, like no caching (memcache etc).

**Comment by wiswedel** [comment]
Can DAVx5 connect after all and just doesn't list the calendars, or does authentication already fail?

Also, please try seting the server's loglevel to "0" (debug) in the config.php to make the logs more chatty.

**Comment by stratoss** [comment]
It connects properly, just the list is empty. Changing the log level now, will update here in case that something pops up.

**Comment by stratoss** [comment]
In DAVx5 I have deleted the account in question and tried again to connect. After the "Configuration detection" I select "Groups are per-contact categories". Then I go into the account, selecting "Refresh calendar list" under "CalDAV" and no calendar appears.

Restarted the web server prior the test, the loglevel is set to "0" and no new entries in data/nextcloud.log

**Comment by wiswedel** [comment]
@stratoss Does one of these apply to your case?

https://github.com/nextcloud/server/issues/16947#issuecomment-533100857
https://github.com/nextcloud/server/issues/11310#issuecomment-530273338

**Comment by stratoss** [comment]
@wiswedel 

I've tried on both WiFi and 4G multiple times, even deleting the account prior the network change, but it doesn't make any difference.

Regarding the 2nd suggestion, I'm using Android 9.1 (not iOS) but the 1st 'account' (the older instance) is still sync'ing properly. It is just the 2nd one (newer instance) which doesn't show any calendars.

**Comment by wiswedel** [comment]
@georgehrke any ideas?

**Comment by stratoss** [comment]
@wiswedel I've tried something cardinal - uninstalled the app and re-installed it from the store, then all out of a sudden it works out... I have no idea what the issue was but it was resolved by re-installation.

Thank you for your time! Great app btw, cheers!

**Comment by wiswedel** [comment]
> out of a sudden it works out

odd...
![image](https://user-images.githubusercontent.com/1804221/65325882-577c4600-dbb0-11e9-9ceb-59c75403e718.png)


> Thank you for your time! Great app btw, cheers!

Thanks @stratoss! 🚀

**Comment by stratoss** [comment]
Yeah, good, old advice, seems to still work in 2019 :)
