### ISSUE TITLE
THEMING : Unpair 'Color' parameter with  the homepage text color.

### ISSUE THREAD

**Issue by J-Doc-Hugues** [nextcloud/server#17125]
Noted on NC version 15  apps setting>theming

### Present behaviour : 
When you set the 'color' parameter, the color of the homepage text (forgot password ?, name and slogan) is automatically paired : « white » if the chosen  color is a dark one or « black » if the chosen color is a light one. 

### Inconvenience : 
If one set a login image, the color of the homepage text can be conflicting with the choosed image.  
Yet it is very comfortable to choose a dark color for heandband and folder icons, then the paired backgroud color of the home page and/or the white color of the text generally mismatch with the logo or with the login image.

### Considered alternative :
Always set the ‘color’ parameter with a light value, which makes black the text colour in the home page. Change the background colour with a white image .png which fit with the logo better that the mandatory background light colour.
If the colour parameter where dark, another mismatch would appears with the mandatory white colour of homepage texts.
 

### Desired behaviour :
At least to unpair the ‘color’ parameter with the homepage text color.
Present Color parameter should be splitted in two parameters :
**Color** (same as present)
**Homepage text color** : can be set to white or Black or choosable like the color parameter.

To be perfect, would be nice to also unpair the color of the homepage background with the color parameter.
Present Color parameter should be splited in three :
**Icon Color** : Set the color of the internal heandband and folder icons and home page « log in » button. 
**Background homepage color** : To set independently the homepage background color  alternatively to login image.
**Homepage text color** : can be set to white ou Black or choosable like the present color parameter.

**Comment by kesselb** [comment]
cc @jancborchardt @juliushaertl

**Comment by jancborchardt** [comment]
We try to keep the theming options simple and understandable. The primary color setting works nicely for the header bar, primary buttons, favicons, etc.

In this specific case I would recommend to use the [Custom CSS app](https://apps.nextcloud.com/apps/theming_customcss) to adjust the color of the log in text.

Maybe we can also have some sort of slight shadow or something similar to make it more readable in the future.

**Comment by juliushaertl** [comment]
I fully agree with @jancborchardt that we should keep the theming settings as simple as possible. The custom css app is a perfect candidate for adjusting small details to your needs.

**Comment by J-Doc-Hugues** [comment]
Ok, I understand and respect your position.
In fact that "custom css" app is not as simple as possible (you need to have css skills) to make this very current kind of setting : to control the colour of the home page text. I'm able to do it, but Mr everybody cannot.
