### ISSUE TITLE
Update notifier slows Nextcloud web ui to a crawl for admin users

### ISSUE THREAD

**Issue by mediqonmartyt** [nextcloud/server#17128]
### Steps to reproduce
1. *.nextcloud.com shows server errors like slow connections or no connections at all.
2. Enable Update Notifier app on your Nextcloud server.
3. Log in as an admin user on the Nextcloud web ui.

### Expected behaviour
Nextcloud is fast and responsive.

### Actual behaviour
Network requests from the browser to the Nextcloud web ui time out or are extremely slow (20000 ms plus). 
There are no relevant log entries. The Nextcloud server itself and its operating system are working without any problem and appear to be idle. A proxy in front of Nextcloud might show connection errors and timeouts. 
After disabling the update notifier app all the issues disappear.

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
15.0.11

**Comment by kesselb** [comment]
Is there a high latency to the nextcloud servers? `ping download.nextcloud.com`

**Comment by rollanders** [comment]
I can verify this issue. Admin had slow respons. Ordinary user had not. When ordinary user was given admin rights the response was slow. Everything got normal after deactivating Update notifier. Found ttajt doc.nextcloud.com was down at this moment. This response was seen in NC 16.0.3 but not in NC 17.0 beta 3 (on a nother server).

**Comment by mediqonmartyt** [comment]
> 
> 
> Is there a high latency to the nextcloud servers? `ping download.nextcloud.com`
Not right now. But Nextcloud servers seem to be very responsive for the moment, which makes this unlikely to be an issue right now. 

Until last week our Nextcloud instance was running without any problems for months.
