### ISSUE TITLE
S3MultipartUploadException

### ISSUE THREAD

**Issue by irCecco** [nextcloud/server#17133]
### Steps to reproduce
1. Install nextcloud via snap
2. Select s3-compatible storage as destination
3. Try to load a >150mb file with either the web UI or the windows client

### Expected behaviour
The file should be uploaded to the server

### Actual behaviour
The upload fails. I did upload even larger files in the past, i don't know what changed

### Server configuration

**Operating system**: Ubuntu 18.04.3 LTS

**Web server:** Apache 2.4

**Database:** MySQL 5.7

**PHP version:** PHP 7.2

**Nextcloud version:** 15.0.11

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 14, if i remember correctly

**Where did you install Nextcloud from:** Snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

```
I haven't installed any app 
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
?php
$CONFIG = array (
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/snap/nextcloud/current/htdocs/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/snap/nextcloud/current/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
  ),
  'supportedDatabases' =>
  array (
    0 => 'mysql',
  ),
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => '/tmp/sockets/redis.sock',
    'port' => 0,
  ),
  'instanceid' => 'redacted',
  'objectstore' =>
  array (
    'class' => 'OC\\Files\\ObjectStore\\S3',
    'arguments' =>
    array (
      'bucket' => 'redacted',
      'autocreate' => false,
      'key' => 'redacted',
	  'secret' => 'redacted',
      'hostname' => 'redacted',
      'use_ssl' => true,
      'use_path_style' => true,
      'legacy_auth' => true,
    ),
  ),
  'passwordsalt' => 'redacted',
  'secret' => 'redacted',
  'trusted_domains' =>
  array (
    0 => 'redacted',
    1 => 'redacted',
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'overwrite.cli.url' => 'http://redacted',
  'dbtype' => 'mysql',
  'version' => '15.0.11.1',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost:/tmp/sockets/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'redacted',
  'installed' => true,
  'loglevel' => 2,
  'maintenance' => false,
);
</details>

**Are you using external storage, if yes which one:** s3-compatible

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Browser:** Firefox

**Operating system:** Win10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
[objectstore] Error: Aws\S3\Exception\S3MultipartUploadException: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 1: Error executing "UploadPart" on "https://redacted"; AWS HTTP error: Client error: `PUT https://redacted` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message></Message>
<BucketName>redacted</B (truncated...)
 EntityTooLarge (client):  - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message></Message>
<BucketName>redacted</BucketName>
</Error>

[no app in context] Error: Aws\S3\Exception\S3MultipartUploadException: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 1: Error executing "UploadPart" on "https://redacted"; AWS HTTP error: Client error: `PUT https://redacted` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message></Message>
<BucketName>redacted</B (truncated...)
 EntityTooLarge (client):  - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message></Message>
<BucketName>redacted</BucketName>
</Error>

[webdav] Fatal: Sabre\DAV\Exception: An exception occurred while uploading parts to a multipart upload. The following parts had errors:
- Part 1: Error executing "UploadPart" on "https://redacted"; AWS HTTP error: Client error: `PUT https://redacted` resulted in a `400 Bad Request` response:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message></Message>
<BucketName>redacted</B (truncated...)
 EntityTooLarge (client):  - <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>EntityTooLarge</Code>
<Message></Message>
<BucketName>redacted</BucketName>
</Error>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
Don't know where to find it
</details>

Thanks for the help

**Comment by irCecco** [comment]
Hello, i tried to make a new virtual server and install everything from scratch. The issue persists (can't load big files)

I can share the virtual webserver and the temporary s3-compatible storage account for testing purpose, if needed

Thanks

**Comment by bkmgit** [comment]
Are you able to produce the error with any other storage backend?

**Comment by Cinerar** [comment]
I believe this is same issue as #288 you should try this patch https://github.com/nextcloud/server/issues/288#issuecomment-533892009

**Comment by irCecco** [comment]
> 
> 
> Are you able to produce the error with any other storage backend?

Hello, sorry for the late reply

I've tryed with FTP and it's working without issues

> 
> 
> I believe this is same issue as #288 you should try this patch [#288 (comment)](https://github.com/nextcloud/server/issues/288#issuecomment-533892009)

Thank you, i'll try to make it work in the next few days. I'm not sure about how to implement it since i'm using the snap package

**Comment by irCecco** [comment]
I wasn't able to apply patch #288 since i'm using the snap package.

I also discovered that my provider uses Scality to implement the s3-compatible storage, if this information is of any utility. Owncloud puts scality among the certified s3 object storages, so that might help to fix this bug

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
