### ISSUE TITLE
Device specific passwords include the dash

### ISSUE THREAD

**Issue by rmsc** [nextcloud/server#17132]
This is related to issue 16964, but the report is old and closed.

### Steps to reproduce
1. Generate a device specific password
2. The password includes dashes every 5 characters

### Expected behaviour
The convention (for example Google's app passwords or MS Windows keys) dictates that the dashes are only there for readability, and aren't part of the key. Introducing just the letters or numbers should work.

If for any reason the idea is to go against convention, the user should be informed.

### Actual behaviour
Entering just the letters and numbers in the password fails with error 401 in the logs. The error is pretty much silent to the user.

Entering the dashes as well makes it work. Copy/pasting the password or using the QR code works.

### Server configuration

**Operating system**:
Linux
**Web server:**
Nginx
**Database:**
Mariadb
**PHP version:**
7.3
**Nextcloud version:** 16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
From the tarball.

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
