### ISSUE TITLE
Strange APP-config-Issue, Logging-Errors

### ISSUE THREAD

**Issue by rgl1234** [nextcloud/server#17139]
Hell since a while I have strange error-messages inside nextcloud-log, where I am not sure where they come from. The errors often happens, when I try to configure app-settings such as onlyoffice, collabora or others. When I press the "save"-buttons, it turns endlessly and the settings are never saved.....I am working with  V16.0.4 and postgresql-DB.

Does someone maybe can give me a hint how to solve such errors or where they could come from?
Thanks René

**Error | PHP | implode(): Invalid arguments passed at /var/www/nextcloud/apps/onlyoffice/templates/settings.php#261 |   | 2019-09-14T09:56:19+0200
-- | -- | -- | -- | --
Error | PHP | implode(): Invalid arguments passed at /var/www/nextcloud/apps/onlyoffice/templates/settings.php#220 |   | 2019-09-14T09:56:19+0200
Error | PHP | implode(): Invalid arguments passed at /var/www/nextcloud/apps/onlyoffice/templates/settings.php#212 |   | 2019-09-14T09:56:19+0200**

**Comment by kesselb** [comment]
For onlyoffice please follow this report: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/135

Do you see any other errors?

**Comment by rgl1234** [comment]
other errors:


Error | jsresourceloader | Could not find resource core/js/oc-backbone-webdav.js to load |   | 2019-09-16T10:04:45+0200
-- | -- | -- | -- | --
Error | PHP | implode(): Invalid arguments passed at /var/www/nextcloud/apps/onlyoffice/templates/settings.php#261 |   | 2019-09-16T10:04:45+0200
Error | PHP | implode(): Invalid arguments passed at /var/www/nextcloud/apps/onlyoffice/templates/settings.php#220 |   | 2019-09-16T10:04:45+0200
Error | PHP | implode(): Invalid arguments passed at /var/www/nextcloud/apps/onlyoffice/templates/settings.php#212 |   | 2019-09-16T10:04:45+0200
Error | PHP | explode() expects parameter 2 to be string, array given at /var/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776 |   | 2019-09-16T10:04:45+0200
Error | PHP | explode() expects parameter 2 to be string, array given at /var/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776 |   | 2019-09-16T10:04:45+0200
Error | PHP | explode() expects parameter 2 to be string, array given at /var/www/nextcloud/apps/onlyoffice/lib/appconfig.php#776 |   | 2019-09-16T10:04:45+0200

**Comment by kesselb** [comment]
Do you see any other error not related to onlyoffice? :see_no_evil:

**Comment by rgl1234** [comment]
Also when I try to change/save settings for Collabora:


Error | PHP | Undefined index: wopi_url at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:29+0200
-- | -- | -- | -- | --
Error | PHP | Undefined index: types at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:29+0200
Error | PHP | Undefined index: installed_version at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:29+0200
Error | PHP | Undefined index: enabled at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:29+0200
Error | PHP | Undefined index: disable_certificate_verification at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:29+0200
Error | PHP | Undefined index: wopi_url at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:26+0200
Error | PHP | Undefined index: types at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:26+0200
Error | PHP | Undefined index: installed_version at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:26+0200
Error | PHP | Undefined index: enabled at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:26+0200
Error | PHP | Undefined index: disable_certificate_verification at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:29:26+0200
Error | PHP | Undefined index: wopi_url at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:28:52+0200
Error | PHP | Undefined index: types at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:28:52+0200
Error | PHP | Undefined index: installed_version at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:28:52+0200
Error | PHP | Undefined index: enabled at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:28:52+0200
Error | PHP | Undefined index: disable_certificate_verification at /var/www/nextcloud/apps/richdocuments/lib/AppConfig.php#69 |   | 2019-09-16T11:28:52+0200

**Comment by kesselb** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Tracked in https://github.com/nextcloud/richdocuments/issues/641 fixed in https://github.com/nextcloud/richdocuments/pull/645
