### ISSUE TITLE
Right click update to 0.15.1 error. Nextcloud 16.0.0 docker version

### ISSUE THREAD

**Issue by vohaha7** [nextcloud/server#17137]
Update to 16.0.0
Doctrine\DBAL\Exception\LockWaitTimeoutException: An exception occurred while executing 'DROP TABLE oc_accounts': SQLSTATE[HY000]: General error: 5 database is locked

Detailed logs 
The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by skjnldsv** [comment]
Is it solved now? Usually locking goes away after a few moments :)

**Comment by vohaha7** [comment]
Hi, John

Sorry, but actually I don't know. I've installed an ordinary VM and a
full-featured nextcloud version.

Best regards

вт, 24 сент. 2019 г., 10:16 John Molakvoæ <notifications@github.com>:

**Comment by skjnldsv** [comment]
Ok, thnaks for the feedback :)
Closing then
