### ISSUE TITLE
Video player - show previews

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#17142]
A simple suggestion - generate video previews of recognized video files. This will help with organizing & finding the right files.

Current state: (Nextcloud 15)

![Screenshot_3](https://user-images.githubusercontent.com/36133540/64913013-bd3b7e80-d727-11e9-810c-0796847d9be5.png)

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/5218

https://www.allerstorfer.at/nextcloud-install-preview-generator/
