### ISSUE TITLE
OnlyOffice Editor frontend is trying to access 127.0.0.1 instead of configured domain

### ISSUE THREAD

**Issue by KarimGeiger** [nextcloud/server#17140]
I am trying to integrate OnlyOffice into my Nextcloud instance. For examples sake, let's assume I run Nextcloud at example.com. I configured the onlyoffice/documentserver docker to listen to onlyoffice.example.com via 443 through an nginx proxy with a valid Let's Encrypt certificate.

The application seems to be configured and working properly, however, when I try to edit a document through the NextCloud webinterface, it fails with an `"Unknown error"`. The reason being is, it's trying to access the following URL through the JS frontend:

`https://127.0.0.1:4433/cache/files/3426957769/Editor.bin/Editor.bin?md5=xxxxx&expires=1567759383&disposition=attachment&ooname=output.bin`
 
### Steps to reproduce

1. Install onlyoffice with docker
```
docker run --name=ONLYOFFICEDOCKER -i -t -d -p 4433:443 -e JWT_ENABLED='true' -e JWT_SECRET='xxxxxx' --restart=always -v /app/onlyoffice/DocumentServer/data:/var/www/onlyoffice/Data onlyoffice/documentserver:latest
```
2. nginx:
```
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name onlyoffice.example.com;
    [ssl-foo]
    ssl_prefer_server_ciphers on;
    add_header Strict-Transport-Security max-age=31536000;
    proxy_set_header X-Forwarded-For $remote_addr;
    server_tokens off;

    location / {
        proxy_pass    https://127.0.0.1:4433;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_ssl_session_reuse off;
        proxy_ssl_verify off;

        access_log      /var/log/nginx/onlyoffice.access.log;
        error_log       /var/log/nginx/onlyoffice.error.log;
    }
}
```
3. Install OnlyOffice extension in NextCloud.
4. Configure it to access OnlyOffice at: `https://onlyoffice.example.com/` with the secret key properly set.

### Expected behaviour
When opening a word document through the NextCloud interface, it should load the OnlyOffice editor.

### Actual behaviour
Loading the editor fails with an `Unknown error`. The network monitor reveals a failed request to:
```https://127.0.0.1:4433/cache/files/xxxx/Editor.bin/Editor.bin?md5=xxxx&expires=1571047766&disposition=attachment&ooname=output.bin```

I am expecting the editor to request the file at `https://onlyoffice.example.com/cache/files/...`.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** 16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Update

**Where did you install Nextcloud from:** The Internet

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - drawio: 0.9.3
  - encryption: 2.4.0
  - external: 3.3.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_fulltextsearch: 1.3.6
  - files_markdown: 2.0.6
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - fulltextsearch: 1.3.6
  - fulltextsearch_elasticsearch: 1.3.6
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.2
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 3.0.0
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.2
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_nextcloud_notification: 1.1.2
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - event_update_notification
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
no thanks
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** All of them

**Operating system:** Web

#### OnyOffice Access Log
<details>
<summary>OnlyOffice Access Log</summary>

```
185.230.127.233 - - [14/Sep/2019:12:18:41 +0200] "GET /web-apps/apps/api/documents/api.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /web-apps/apps/documenteditor/main/index.html?_dc=5.4.0-21&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor HTTP/2.0" 302 154 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /5.4.0-21//web-apps/apps/api/documents/api.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /5.4.0-21//web-apps/apps/documenteditor/main/index.html?_dc=5.4.0-21&lang=en&customer=ONLYOFFICE&frameEditorId=iframeEditor HTTP/2.0" 200 29118 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:42 +0200] "GET /5.4.0-21//web-apps/apps/api/documents/api.js HTTP/2.0" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:43 +0200] "GET /5.4.0-21//doc/3723508311/c/info?t=1568456323463 HTTP/2.0" 200 96 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
185.230.127.233 - - [14/Sep/2019:12:18:44 +0200] "GET /5.4.0-21//spellchecker/doc/3723508311/c/info?t=1568456324407 HTTP/2.0" 200 97 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.1 Safari/605.1.15"
```
</details>

**Comment by kesselb** [comment]
As reference: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/137

**Comment by szaimen** [comment]
Seems like the problem was solved with https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/137
