### ISSUE TITLE
Option to disable remote wiping

### ISSUE THREAD

**Issue by Moini** [nextcloud/server#17152]
### Is your feature request related to a problem? Please describe.

I'm worried that if someone hacks my nextcloud server, they can use this new 'feature' to not only delete my files online, but also to delete all my files on my devices, leaving me with no data at all.

On hosted servers, I'm worried about a rogue / revengeful administrator. There have been cases of people being angry with their employers...

### Describe the solution you'd like

I would like to be able to deactivate remote wiping on the client, possibly transparently and only with agreement of the server owner, so that the intended functionality of the new feature is untouched, and its availability can be controlled by the server owner.

### Describe alternatives you've considered

Local backups, both on the device and on a different device. Those are made much harder now that adb says its backup functionality is deprecated. Also, the nextcloud thing already *is* the backup. I use it to store files and to have them accessible, not to restrict access to them.

I assume DAV syncing does not have that feature of a push sync (which I guess this is, in essence). So that would probably still work normally.

Implementing a backup solution for a backup solution because of a new feature in that is a bit over the top, to me, though.

### Additional context

Thanks for reading, I know this being a new feature, this complaint is perhaps not something one wants to read. Maybe it's also a misunderstanding - if so, I would really like to understand how to prevent a malicious attacker from remote deleting my files.

**Comment by Moini** [comment]
Thank you, @tobiasKaminsky . I wasn't sure about where to put this.

**Comment by Moini** [comment]
Have there been any discussions at all about this or is this real danger being ignored away?

Just think of what will happen if a server of one of your enterprise customers is hacked, and all data is remote-wiped from all devices by the attacker. Are you so sure that nobody can hack into your server?

**Comment by KopfKrieg** [comment]
> Just think of what will happen if a server of one of your enterprise customers is hacked, and all data is remote-wiped from all devices by the attacker.

Well, of course it would be followed by a small downtown … until the backup is restored.

I get your point, and I too hope this gets implemented in a transparent way (e.g. client requests to disable this feature → server admin can allow this or can deny it, maybe with a system/group wide setting), but don't forget that a nextcloud instance is not a backup, especially because nothing is 100% secure.

**Comment by szaimen** [comment]
If anyone hacks into to your server and can trigger the remote wipe, it will be the smallest thing that you should worry about because he might just delete all files manually which would do the same on your client devices.
Hence this doesn't make sense to get implemented -> closing.

**Comment by Moini** [comment]
Would that really be exactly the same thing, @szaimen? 

Personally, I also wouldn't want a malicious admin who just doesn't like me be able to delete all my data.

**Comment by Moini** [comment]
(and isn't there an option for unidirectional syncing for clients? If not... it probably should exist.)

**Comment by szaimen** [comment]
cc @nextcloud/security what is your opinion on this feature? Does it makes sense to get implemented from a security perspective?

**Comment by nickvergessen** [comment]
I would say no, as this is basically just working around backups.
The "hacker" could also just delete all your files online and from the trashbin and wait for your sync client to delete all the files with the next sync. Whether it's done via a push or via a pull doesn't matter here.

**Comment by Gahia123** [comment]
I think this issue must be reopened, the reason is not a hacker; As an example I want to give a user administrative privileges over certain group of people:  create or delete accounts, assign space, reset password among other no so compromising tasks, but I don't want this person to being able of whether by mistake or premeditatedly delete the work of those people. Currently I can not do this.

**Comment by nickvergessen** [comment]
They can do this also by deleting the user. That is also final compared to remote wiping a device which still keeps the files on the server.

**Comment by Gahia123** [comment]
Ok, we need to rely on external backups and give superuser permission only to trusted administrators. Is there any other safety measure to tackle this issue? maybe by disabling remote wipe option for an administrator those files could be kept in client machines despite of being deleted on the server, it could be a very simple to implement safety measure.

**Comment by nickvergessen** [comment]
> and give superuser permission only to trusted administrators

You should anyway as they could install any app or change any password and access all the data
