### ISSUE TITLE
LDAP: Custom quota is overwritten by default quota

### ISSUE THREAD

**Issue by Venice-89** [nextcloud/server#17154]
### Steps to reproduce
1. Setup a LDAP Connection with a default quota
2. Change the quota for a LDAP user
3. Login with the user
4. the quota is changed back to default quota from LDAP Settings

### Expected behaviour
Quota should not be overwritten 

### Actual behaviour
Quota is changed back to default quota from LDAP settings

### Server configuration

**Operating system**:
Ubuntu 1809

**Web server:**
apache

**Database:**
mysql
Version: 10.1.41

**PHP version:**
Version: 7.2.19

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - circles: 0.17.7
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - deck: 0.6.6
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - groupfolders: 4.1.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.2
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - text: 1.0.2
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - twofactor_u2f: 3.0.1
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - end_to_end_encryption
  - files_fulltextsearch
  - fulltextsearch
  - richdocuments
  - spreed
  - user_saml

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.firma.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/XXXX",
        "auth.bruteforce.protection.enabled": false,
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "255",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+---------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                         |
+-------------------------------+---------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                           |
| homeFolderNamingRule          |                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                           |
| ldapAgentName                 |                                                                                             |
| ldapAgentPassword             | ***                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                             |
| ldapAttributesForUserSearch   |                                                                                             |
| ldapBackupHost                |                                                                                             |
| ldapBackupPort                |                                                                                             |
| ldapBase                      | ou=People,ou=OU2,o=firma,c=de                                                          |
| ldapBaseGroups                | ou=People,ou=OU2,o=firma,c=de                                                          |
| ldapBaseUsers                 | ou=People,ou=OU2,o=firma,c=de                                                          |
| ldapCacheTTL                  | 600                                                                                         |
| ldapConfigurationActive       | 1                                                                                           |
| ldapDefaultPPolicyDN          |                                                                                             |
| ldapDynamicGroupMemberURL     |                                                                                             |
| ldapEmailAttribute            | mail                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                           |
| ldapExpertUUIDGroupAttr       |                                                                                             |
| ldapExpertUUIDUserAttr        |                                                                                             |
| ldapExpertUsernameAttr        | fhgUID                                                                                      |
| ldapExtStorageHomeAttribute   |                                                                                             |
| ldapGidNumber                 | gidNumber                                                                                   |
| ldapGroupDisplayName          | cn                                                                                          |
| ldapGroupFilter               |                                                                                             |
| ldapGroupFilterGroups         |                                                                                             |
| ldapGroupFilterMode           | 0                                                                                           |
| ldapGroupFilterObjectclass    |                                                                                             |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                |
| ldapHost                      | ldaps://dirseka.bi.firma.de                                                            |
| ldapIgnoreNamingRules         |                                                                                             |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(|(mailPrimaryAddress=%uid)(mail=%uid))(|(fhgUid=%uid)))) |
| ldapLoginFilterAttributes     | fhgUid                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                           |
| ldapLoginFilterMode           | 0                                                                                           |
| ldapLoginFilterUsername       | 0                                                                                           |
| ldapNestedGroups              | 0                                                                                           |
| ldapOverrideMainServer        |                                                                                             |
| ldapPagingSize                | 500                                                                                         |
| ldapPort                      | 636                                                                                         |
| ldapQuotaAttribute            |                                                                                             |
| ldapQuotaDefault              | 25 GB                                                                                       |
| ldapTLS                       | 0                                                                                           |
| ldapUserAvatarRule            | default                                                                                     |
| ldapUserDisplayName           | displayName                                                                                 |
| ldapUserDisplayName2          |                                                                                             |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                              |
| ldapUserFilterGroups          |                                                                                             |
| ldapUserFilterMode            | 0                                                                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                        |
| turnOffCertCheck              | 0                                                                                           |
| turnOnPasswordChange          | 0                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                           |
+-------------------------------+---------------------------------------------------------------------------------------------+
+-------------------------------+--------------------------------------------------------------------------+
| Configuration                 | s02                                                                      |
+-------------------------------+--------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                        |
| homeFolderNamingRule          |                                                                          |
| lastJpegPhotoLookup           | 0                                                                        |
| ldapAgentName                 |                                                                          |
| ldapAgentPassword             | ***                                                                      |
| ldapAttributesForGroupSearch  |                                                                          |
| ldapAttributesForUserSearch   |                                                                          |
| ldapBackupHost                |                                                                          |
| ldapBackupPort                |                                                                          |
| ldapBase                      | ou=OU3,o=firma,c=de                                                 |
| ldapBaseGroups                | ou=OU3,o=firma,c=de                                                 |
| ldapBaseUsers                 | ou=OU3,o=firma,c=de                                                 |
| ldapCacheTTL                  | 600                                                                      |
| ldapConfigurationActive       | 1                                                                        |
| ldapDefaultPPolicyDN          |                                                                          |
| ldapDynamicGroupMemberURL     |                                                                          |
| ldapEmailAttribute            | mail                                                                     |
| ldapExperiencedAdmin          | 0                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                          |
| ldapExpertUUIDUserAttr        |                                                                          |
| ldapExpertUsernameAttr        |                                                                          |
| ldapExtStorageHomeAttribute   |                                                                          |
| ldapGidNumber                 | gidNumber                                                                |
| ldapGroupDisplayName          | cn                                                                       |
| ldapGroupFilter               |                                                                          |
| ldapGroupFilterGroups         |                                                                          |
| ldapGroupFilterMode           | 0                                                                        |
| ldapGroupFilterObjectclass    |                                                                          |
| ldapGroupMemberAssocAttr      | uniqueMember                                                             |
| ldapHost                      | ldaps://dirseka.bi.firma.de                                         |
| ldapIgnoreNamingRules         |                                                                          |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(mailPrimaryAddress=%uid)(mail=%uid))) |
| ldapLoginFilterAttributes     |                                                                          |
| ldapLoginFilterEmail          | 1                                                                        |
| ldapLoginFilterMode           | 0                                                                        |
| ldapLoginFilterUsername       | 0                                                                        |
| ldapNestedGroups              | 0                                                                        |
| ldapOverrideMainServer        |                                                                          |
| ldapPagingSize                | 500                                                                      |
| ldapPort                      | 636                                                                      |
| ldapQuotaAttribute            |                                                                          |
| ldapQuotaDefault              | 25 GB                                                                    |
| ldapTLS                       | 0                                                                        |
| ldapUserAvatarRule            | default                                                                  |
| ldapUserDisplayName           | displayName                                                              |
| ldapUserDisplayName2          |                                                                          |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                           |
| ldapUserFilterGroups          |                                                                          |
| ldapUserFilterMode            | 0                                                                        |
| ldapUserFilterObjectclass     | inetOrgPerson                                                            |
| ldapUuidGroupAttribute        | auto                                                                     |
| ldapUuidUserAttribute         | auto                                                                     |
| turnOffCertCheck              | 0                                                                        |
| turnOnPasswordChange          | 0                                                                        |
| useMemberOfToDetectMembership | 1                                                                        |
+-------------------------------+--------------------------------------------------------------------------+
+-------------------------------+---------------------------------------------------------------------------------------------+
| Configuration                 | s03                                                                                         |
+-------------------------------+---------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                           |
| homeFolderNamingRule          |                                                                                             |
| lastJpegPhotoLookup           | 0                                                                                           |
| ldapAgentName                 |                                                                                             |
| ldapAgentPassword             | ***                                                                                         |
| ldapAttributesForGroupSearch  |                                                                                             |
| ldapAttributesForUserSearch   |                                                                                             |
| ldapBackupHost                |                                                                                             |
| ldapBackupPort                |                                                                                             |
| ldapBase                      | ou=People,ou=OU1,o=firma,c=de                                                         |
| ldapBaseGroups                | ou=People,ou=OU2,o=firma,c=de                                                          |
| ldapBaseUsers                 | ou=People,ou=OU2,o=firma,c=de                                                          |
| ldapCacheTTL                  | 600                                                                                         |
| ldapConfigurationActive       | 1                                                                                           |
| ldapDefaultPPolicyDN          |                                                                                             |
| ldapDynamicGroupMemberURL     |                                                                                             |
| ldapEmailAttribute            | mail                                                                                        |
| ldapExperiencedAdmin          | 0                                                                                           |
| ldapExpertUUIDGroupAttr       |                                                                                             |
| ldapExpertUUIDUserAttr        |                                                                                             |
| ldapExpertUsernameAttr        | fhgUID                                                                                      |
| ldapExtStorageHomeAttribute   |                                                                                             |
| ldapGidNumber                 | gidNumber                                                                                   |
| ldapGroupDisplayName          | cn                                                                                          |
| ldapGroupFilter               |                                                                                             |
| ldapGroupFilterGroups         |                                                                                             |
| ldapGroupFilterMode           | 0                                                                                           |
| ldapGroupFilterObjectclass    |                                                                                             |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                |
| ldapHost                      | ldaps://dirseka.bi.firma.de                                                            |
| ldapIgnoreNamingRules         |                                                                                             |
| ldapLoginFilter               | (&(|(objectclass=inetOrgPerson))(|(|(mailPrimaryAddress=%uid)(mail=%uid))(|(fhgUid=%uid)))) |
| ldapLoginFilterAttributes     | fhgUid                                                                                      |
| ldapLoginFilterEmail          | 1                                                                                           |
| ldapLoginFilterMode           | 0                                                                                           |
| ldapLoginFilterUsername       | 0                                                                                           |
| ldapNestedGroups              | 0                                                                                           |
| ldapOverrideMainServer        |                                                                                             |
| ldapPagingSize                | 500                                                                                         |
| ldapPort                      | 636                                                                                         |
| ldapQuotaAttribute            |                                                                                             |
| ldapQuotaDefault              | 25 GB                                                                                       |
| ldapTLS                       | 0                                                                                           |
| ldapUserAvatarRule            | default                                                                                     |
| ldapUserDisplayName           | displayName                                                                                 |
| ldapUserDisplayName2          |                                                                                             |
| ldapUserFilter                | (|(objectclass=inetOrgPerson))                                                              |
| ldapUserFilterGroups          |                                                                                             |
| ldapUserFilterMode            | 0                                                                                           |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                               |
| ldapUuidGroupAttribute        | auto                                                                                        |
| ldapUuidUserAttribute         | auto                                                                                        |
| turnOffCertCheck              | 0                                                                                           |
| turnOnPasswordChange          | 0                                                                                           |
| useMemberOfToDetectMembership | 1                                                                                           |
+-------------------------------+---------------------------------------------------------------------------------------------+

</details>

**Comment by kesselb** [comment]
cc @blizzz is it supported to set quote per user in nextcloud with ldap? I guess this should be done through `ldapQuotaAttribute`?

**Comment by drybjed** [comment]
I can also confirm this behaviour. Setting the quota via the LDAP attribute would probably solve this, but I'm not sure if there are good candidates for that in standard LDAP schemas. Any suggestions? Perhaps there's a Nextcloud LDAP schema somewhere with useful object and attribute definitions?

**Comment by blizzz** [comment]
> Change the quota for a LDAP user

where? in the users page? It's eihter you let LDAP control the user quota, or you use the built in mechanisms.

**Comment by Venice-89** [comment]
Yes, on the user page while a default quota is set in LDAP profile... 

mhh I am sure that it was possible in older versions.... I have to define a special quota for different LDAP Sources and there is no way to modify entries in that LDAP-directory so I can't define the quota in my LDAP directory (it's a Corporate LDAP where I don't have write permissions)
But sometimes, some users need more space.... thats why I modified the user quota on the users page. 
After an upgrade, all individual quotas from the user page are reseted to the LDAP quota....

**Comment by blizzz** [comment]
> mhh I am sure that it was possible in older versions...

nope

And I don't have a work around unfortunately, besides managing is entirely from within Nextcloud's user management, with the drawbacks it has. And/or having an own small app that listens for `assignedUserId` (happens after mapping) and does it's own logic for setting the quota.
