### ISSUE TITLE
[activity] OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/server#17153]
I'm having this error message (many lines of it) with NC 16.0.4.1.
Don't know how to reproduce it.

```
[activity] Error: OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined at <<closure>>

 0. /var/www/html/nextcloud/apps/activity/lib/GroupHelper.php line 91
    OC\RichObjectStrings\Validator->validate("Vous avez créé  ... }", {user: {type: "u ... }})
 1. /var/www/html/nextcloud/apps/activity/lib/Data.php line 257
    OCA\Activity\GroupHelper->addActivity({activity_id: "6 ... "})
 2. /var/www/html/nextcloud/apps/activity/lib/Controller/APIv1.php line 83
    OCA\Activity\Data->get(OCA\Activity\GroupHelper {}, OCA\Activity\UserSettings {}, "user", 0, 71, "desc", "all")
 3. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 166
    OCA\Activity\Controller\APIv1->get(0, 100)
 4. /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Activity\Controller\APIv1 {}, "get")
 5. /var/www/html/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity\Controller\APIv1 {}, "get")
 6. /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("APIv1Controller", "get", OC\AppFramework\ ... {}, {_route: "ocs.activity.APIv1.get"})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "ocs.activity.APIv1.get"})
 8. /var/www/html/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "ocs.activity.APIv1.get"})
 9. /var/www/html/nextcloud/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/cloud/activity")
10. /var/www/html/nextcloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/html/nextcloud/ocs/v1.php")

GET /ocs/v2.php/cloud/activity?start=0&count=100&format=json
from 176.180.93.121 by user at 2019-09-12T08:00:54+02:00
```

In RAW:

`{"reqId":"AMpU7TYvcrhlHcyNuUX5","level":3,"time":"2019-09-16T08:16:44+02:00","remoteAddr":"2a01:e35:2e8e:9e80:cd1a:5647:44de:511c","user":"user","app":"activity","method":"GET","url":"/ocs/v2.php/cloud/activity?start=0&count=100&format=json","message":{"Exception":"OCP\\RichObjectStrings\\InvalidObjectExeption","Message":"Parameter is undefined","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/activity/lib/GroupHelper.php","line":91,"function":"validate","class":"OC\\RichObjectStrings\\Validator","type":"->","args":["Vous avez créé un nouveau tableau {tableau}",{"user":{"type":"user","id":"user","name":"User"},"board":{"type":"highlight","id":1,"name":"Personnel","link":"https://cnc.cloudeezy.com/apps/deck/#!/board/1"}}]},{"file":"/var/www/html/nextcloud/apps/activity/lib/Data.php","line":257,"function":"addActivity","class":"OCA\\Activity\\GroupHelper","type":"->","args":[{"activity_id":"6802","timestamp":"1568224595","priority":"30","type":"deck","user":"user","affecteduser":"user","app":"deck","subject":"board_create","subjectparams":"{\"author\":\user\"}","message":"","messageparams":"[]","file":"Personnel","link":"","object_type":"deck_board","object_id":"1"}]},{"file":"/var/www/html/nextcloud/apps/activity/lib/Controller/APIv1.php","line":83,"function":"get","class":"OCA\\Activity\\Data","type":"->","args":[{"__class__":"OCA\\Activity\\GroupHelper"},{"__class__":"OCA\\Activity\\UserSettings"},"user",0,66,"desc","all"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"get","class":"OCA\\Activity\\Controller\\APIv1","type":"->","args":[0,100]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Activity\\Controller\\APIv1"},"get"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Activity\\Controller\\APIv1"},"get"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["APIv1Controller","get",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.activity.APIv1.get"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.activity.APIv1.get"}]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.activity.APIv1.get"}]},{"file":"/var/www/html/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/activity"]},{"file":"/var/www/html/nextcloud/ocs/v2.php","line":24,"args":["/var/www/html/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/lib/private/RichObjectStrings/Validator.php","Line":73,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/2.5.2git (build 20190319) (Nextcloud)","version":"16.0.4.1","id":"5d7f4ac892fce"}`

**Comment by stefanocarotenuto** [comment]
Hi, I've just found this post through search engine and wanted to let you know that I've got same error here, many lines. Can't understand actually how to reproduce it and how it's affecting our users.
We are on Nextcloud 17.0.1. 

```
[activity] Error: OCP\RichObjectStrings\InvalidObjectExeption: Parameter is undefined at <<closure>>

 0. /var/www/nextcloud/apps/activity/lib/GroupHelper.php line 91
    OC\RichObjectStrings\Validator->validate("{user1} ha ripristinato {file}", {file: {type: "f ... }})
 1. /var/www/nextcloud/apps/activity/lib/Data.php line 257
    OCA\Activity\GroupHelper->addActivity({activity_id: "1 ... "})
 2. /var/www/nextcloud/apps/activity/lib/Controller/APIv1.php line 83
    OCA\Activity\Data->get(OCA\Activity\GroupHelper {}, OCA\Activity\UserSettings {}, "HIDDEN USERNAME", 0, 49, "desc", "all")
 3. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Activity\Controller\APIv1->get(0, 100)
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Activity\Controller\APIv1 {}, "get")
 5. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Activity\Controller\APIv1 {}, "get")
 6. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("APIv1Controller", "get", OC\AppFramework\ ... {}, {_route: "ocs.activity.APIv1.get"})
 7. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "ocs.activity.APIv1.get"})
 8. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "ocs.activity.APIv1.get"})
 9. /var/www/nextcloud/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/cloud/activity")
10. /var/www/nextcloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/nextcloud/ocs/v1.php")

GET /ocs/v2.php/cloud/activity?start=0&count=100&format=json
from HIDDEN IP by HIDDEN USERNAME at 2019-11-28T10:23:24+01:00
```

**Comment by kesselb** [comment]
nextcloud/deck: `Vous avez créé un nouveau tableau {tableau}` (should be `{board}`)
nextcloud/server: `{user1} ha ripristinato {file}` (should be `{user}`)

Everything between `{` and `}` are placeholder. It seems that the translators accidently translated the placeholders. 

Could you fix that at https://www.transifex.com/nextcloud/nextcloud/? Thanks :+1:

**Comment by kesselb** [comment]
cc @rakekniven could you forward that?

**Comment by rakekniven** [comment]
Fixed that on TX.
