### ISSUE TITLE
IE11 / vue-multiselect mousedown event incompatility

### ISSUE THREAD

**Issue by J-Doc** [nextcloud/server#17160]
### Actual behaviour
In all multiselect components (Adding a user to a group, Adding a group to a group filtered function like restricting two-factor auth to a group of user, ...) I can add a group if there is none, but can't modify it after using mouse.

If I want to change anything, I need to click on email field and use TAB key in order to move the focus to Group field. At this point, group list is displayed and I can change things.

### Expected behaviour
Like in Firefox or Chrome browser, I wish to be able to modify those fields using mouse. I think that something is preventing mouse-down event to be launched.

### Server configuration
Centos 7 fully updated
Apache 2.4
MariaDB 5.5.60
PHP 7.3.6
Nextcloud 15.0.11 or 16.0.4

### Client configuration
Internet Explorer 11
Windows 10

**Comment by J-Doc** [comment]
Seems to be related to #https://github.com/shentao/vue-multiselect/issues/380 but it seems that CSS hack founded at https://github.com/shentao/vue-multiselect/issues/380#issuecomment-462985331 has already been done in core.

**Comment by J-Doc** [comment]
Adding **onclick="this.querySelector('input').focus();"** on div.multiselect appears to correctly fix this behaviour... weird

**Comment by skjnldsv** [comment]
Still happening?
