### ISSUE TITLE
Adding more sorting to trash bin

### ISSUE THREAD

**Issue by Milokita** [nextcloud/server#17168]
**Is your feature request related to a problem? Please describe.**
It is always trobulesome to seek deleted file without remembering the date, user just have to scroll through

**Describe the solution you'd like**
Adding more sorting options such as file extension, size, file path (before deleted)

**Describe alternatives you've considered**

**Additional context**

**Comment by alexanderdd** [comment]
why did you close this? It was not implemented...

related: https://github.com/nextcloud/server/issues/14917#issuecomment-499087946
-> please leave a :+1: there

**Comment by alexanderdd** [comment]
looks like part of it is implemented https://github.com/nextcloud/server/issues/14138
