### ISSUE TITLE
Cannot upload files with size > 8k

### ISSUE THREAD

**Issue by BstAA** [nextcloud/server#17179]
### Steps to reproduce
1.Try to upload file with filesize > 8192 via:

* NC Windows Client
* Browser "Upload File" Dialog
* Browser Drag & Drop

Browser with HTML2 enabled or disabled

### Expected behaviour
Just upload the file

### Actual behaviour

Error  PHP curl_exec():  Unable to create temporary file, Check permissions in temporary files  directory. at  /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php#40
Fatal WEBDAV i.e. "Sabre\DAV\Exception\BadRequest: expected filesize 529008 got 8192" 

This error has been reported earlier / Issue #16318. But the solution discussed there isn't applicable.

### Server configuration

**Operating system**:
Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l

**Web server:**
Apache (fpm-fcgi)

**Database:**
mysql 10.3.15

**PHP version:**
7.3.4-2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** (see Nextcloud admin page)
16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
via NC-PI updater

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - issuetemplate: 0.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - nextcloudpi: 0.0.1
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - calendar
  - contacts
  - encryption
  - files_external
  - files_texteditor
  - files_videoplayer
  - news
  - notes
  - password_policy
  - previewgenerator
  - sharebymail
  - tasks
  - twofactor_totp
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "trusted_domains": {
            "0": "localhost",
            "11": "<!DOCTYPE HTML PUBLIC \"-\/\/IETF\/\/DTD HTML 2.0\/\/EN\">\n<html><head>\n<title>302 Found<\/title>\n<\/head><body>\n<h1>Found<\/h1>\n<p>The document has moved <a href=\"https:\/\/icanhazip.com\/\">here<\/a>.<\/p>\n<\/body><\/html>",
            "1": "192.168.10.53",
            "5": "nextcloudpi.local",
            "7": "nextcloudpi",
            "8": "nextcloudpi.lan",
            "9": "cloud",
            "10": "cloud.fritz.box",
            "20": "cloud.beckstette-aalen.de",
            "4": "cloud.beckstette-aalen.de"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "https:\/\/cloud.beckstette-aalen.de\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/media\/nc-data\/ncdata\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "logfile": "\/media\/nc-data\/ncdata\/nextcloud.log",
        "loglevel": 2,
        "jpeg_quality": "60",
        "data-fingerprint": "dec234ee1c3167834b3a3707c0a741b6"
    }
}</details>

**Are you using encryption:** yes/no
No

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Operating system:**
Windows 10 Pro 1809 (Build 177636.737)
[error.zip](https://github.com/nextcloud/server/files/3621046/error.zip)
[nextcloud.zip](https://github.com/nextcloud/server/files/3621047/nextcloud.zip)

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Tue Sep 17 11:42:48.529011 2019] [mpm_event:notice] [pid 21064:tid 1995670032] AH00491: caught SIGTERM, shutting down
[Tue Sep 17 11:43:22.503194 2019] [ssl:warn] [pid 557:tid 1995457040] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Sep 17 11:43:22.674023 2019] [ssl:warn] [pid 805:tid 1995457040] AH01909: localhost:4443:0 server certificate does NOT include an ID which matches the server name
[Tue Sep 17 11:43:22.679384 2019] [mpm_event:notice] [pid 805:tid 1995457040] AH00489: Apache/2.4.38 (Raspbian) OpenSSL/1.1.1c configured -- resuming normal operations
[Tue Sep 17 11:43:22.679517 2019] [core:notice] [pid 805:tid 1995457040] AH00094: Command line: '/usr/sbin/apache2'
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XYC5gQXFBFoZv1w1-lYZvQAATA4","level":3,"time":"2019-09-17T10:46:25+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"PUT","url":"\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","message":"fread(): file created in the system's temporary directory at \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/Wrapper.php#91","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC5gQXFBFoZv1w1-lYZvQAATA4","level":3,"time":"2019-09-17T10:46:25+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"PUT","url":"\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","message":"fread(): Unable to create temporary file, Check permissions in temporary files directory. at \/var\/www\/nextcloud\/3rdparty\/icewind\/streams\/src\/Wrapper.php#91","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC5gQXFBFoZv1w1-lYZvQAATA4","level":3,"time":"2019-09-17T10:46:25+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"no app in context","method":"PUT","url":"\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 529008 got 8192","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["issuetemplate.tar.gz",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["Documents\/issuetemplate.tar.gz",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":228,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC5gQXFBFoZv1w1-lYZvQAATA4","level":4,"time":"2019-09-17T10:46:25+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"webdav","method":"PUT","url":"\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"expected filesize 529008 got 8192","Code":0,"Trace":[{"file":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","line":156,"function":"put","class":"OCA\\DAV\\Connector\\Sabre\\File","type":"->","args":[null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":1096,"function":"createFile","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["issuetemplate.tar.gz",null]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["Documents\/issuetemplate.tar.gz",null,null]},{"function":"httpPut","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"\/var\/www\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https:\/\/cloud.beckstette-aalen.de\/remote.php\/webdav\/Documents\/issuetemplate.tar.gz","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php","line":80,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/remote.php","line":163,"args":["\/var\/www\/nextcloud\/apps\/dav\/appinfo\/v1\/webdav.php"],"function":"require_once"}],"File":"\/var\/www\/nextcloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":228,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC5yAXFBFoZv1w1-lYZ5AAAVAI","level":3,"time":"2019-09-17T10:47:37+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"GET","url":"\/index.php\/settings\/apps","message":"curl_exec(): Unable to create temporary file, Check permissions in temporary files directory. at \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlHandler.php#40","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC5ygXFBFoZv1w1-lYZ9QAAUwk","level":3,"time":"2019-09-17T10:47:40+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"GET","url":"\/index.php\/settings\/apps\/list","message":"curl_exec(): Unable to create temporary file, Check permissions in temporary files directory. at \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlHandler.php#40","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC5ygXFBFoZv1w1-lYZ9QAAUwk","level":3,"time":"2019-09-17T10:47:41+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"GET","url":"\/index.php\/settings\/apps\/list","message":"curl_exec(): Unable to create temporary file, Check permissions in temporary files directory. at \/var\/www\/nextcloud\/3rdparty\/guzzlehttp\/guzzle\/src\/Handler\/CurlHandler.php#40","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9hBBoCklRjWdeKOTwZwAAAB4","level":3,"time":"2019-09-17T11:03:32+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: client-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9hBBoCklRjWdeKOTwZwAAAB4","level":3,"time":"2019-09-17T11:03:32+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: client-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9hBBoCklRjWdeKOTwZwAAAB4","level":3,"time":"2019-09-17T11:03:32+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9hBBoCklRjWdeKOTwZwAAAB4","level":3,"time":"2019-09-17T11:03:32+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9hBBoCklRjWdeKOTwZwAAAB4","level":3,"time":"2019-09-17T11:03:32+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9whBoCklRjWdeKOTwbwAAFhA","level":3,"time":"2019-09-17T11:04:34+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9whBoCklRjWdeKOTwbwAAFhA","level":3,"time":"2019-09-17T11:04:34+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}
{"reqId":"XYC9whBoCklRjWdeKOTwbwAAFhA","level":3,"time":"2019-09-17T11:04:34+00:00","remoteAddr":"2001:16b8:a4ac:8101:b175:22ad:656e:b713","user":"ncp","app":"PHP","method":"POST","url":"\/index.php\/apps\/issuetemplate\/render","message":"Undefined index: log-detail at \/var\/www\/nextcloud\/apps\/issuetemplate\/lib\/Detail.php#59","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"16.0.4.1"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by BstAA** [comment]
Regarding: [https://github.com/nextcloud/server/issues/9471](url)
> This is to confirm that disabling Apache's reqtimeout module
_**Tested: Didn't work for me**_

[https://forum.owncloud.org/viewtopic.php?f=17&t=32517](url)
It's a summary of possible reasons.

Other issues seen, **but all without a solution** 
#15200 
#14884

**Comment by kesselb** [comment]
Thanks for reporting this issue :+1: 

https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22expected+filesize%22

Please pick one of the issues (with similar setup) from the list above and append your issue template.

**Comment by BstAA** [comment]
Hi Daniel I don't think it makes sense to append this issue to one of the others, as I already checked for the discussed reasons:

- timeout
- large files
- Win 10 specific
- ...
So if I really should add my issue to one of the others, please advise

**Comment by BstAA** [comment]
Hi Daniel I don't think it makes sense to append this issue to one of the others, as I already checked for the discussed reasons:

*	timeout
*	large files
*	Win 10 specific
*	...
*	 

So if I really should add my issue to one of the others, please advise

Klaus

 

--

Dr. Klaus F. Beckstette

Geierweg 32

73434 Aalen

Tel.: +49 (7361) 943144

 

 

 

 

Von: Daniel Kesselberg <notifications@github.com> 
Gesendet: Dienstag, 17. September 2019 21:23
An: nextcloud/server <server@noreply.github.com>
Cc: Klaus F. Beckstette <klaus@beckstette.de>; Author <author@noreply.github.com>
Betreff: Re: [nextcloud/server] Cannot upload files with size > 8k (#17179)

 

Thanks for reporting this issue 👍

https://github.com/nextcloud/server/issues?utf8=%E2%9C%93 <https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+%22expected+filesize%22> &q=is%3Aissue+is%3Aopen+%22expected+filesize%22

Please pick one of the issues (with similar setup) from the list above and append your issue template.

**Comment by kesselb** [comment]
Fine by me. Please update your issue template and add config, apps and logs. There could be many reasons for this kind of error. I was running into that issue myself with a quota defined for www-data for example.

**Comment by BstAA** [comment]
Thanks! Data has already been there, but a format error hided it :-(

**Comment by kesselb** [comment]
> Unable to create temporary file, Check permissions in temporary files directory.

Leads to the question: Is /media/nc-data/ncdata/tmp writeable to www-data?

**Comment by BstAA** [comment]
` drwxrwxrwt 1 www-data www-data       0 Sep 17 09:13 tmp`
yes, but empty all the time
as told meanwhile I changed the `tempdirectory `variable and created a new directory without result

**Comment by kesselb** [comment]
cc @nachoparker any idea?

**Comment by BstAA** [comment]
Closed because I had to restore from backup to NC 16.0.2 to get system running again.
Did some further experiments, but nne of them showed positiv results.
Additionally the apps-store seams to be empty.
