### ISSUE TITLE
Failed update from 15 (whatever) to 16.0.4

### ISSUE THREAD

**Issue by HeavyThumper** [nextcloud/server#17170]
### Steps to reproduce
1.  Upgraded from 14 (production) to 15.
2.  Upgrade from 15 to 16
3.  Fail

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DELETE FROM `oc_collres_accesscache`': SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (NextCloud.oc_collres_accesscache) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'DELETE FROM `oc_collres_accesscache`': SQLSTATE[HY000]: General error: 1105 Percona-XtraDB-Cluster prohibits use of DML command on a table (NextCloud.oc_collres_accesscache) without an explicit primary key with pxc_strict_mode = ENFORCING or MASTER

The update was unsuccessful. Please report this issue to the Nextcloud community.

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** nginx

**Database:** mysql/Percona XtraDB 14.14

**PHP version:**  7.3.6

**Nextcloud version:** (see Nextcloud admin page)
15

**Updated from an older Nextcloud/ownCloud or fresh install:**
14

**Where did you install Nextcloud from:**
web updater

**Comment by kesselb** [comment]
Looks similar to https://github.com/nextcloud/server/issues/16311

**Comment by HeavyThumper** [comment]
Yes, it does look the same - in my case it was going from 15.x instead of 16.0 but the same.
I simply changed the Unique index for that table to a Primary - and the upgrade succeeded.

**Comment by kesselb** [comment]
I'm not sure if this is a good idea but at least it works for you again :+1:
