### ISSUE TITLE
Deadlock detected

### ISSUE THREAD

**Issue by BetaLeaf** [nextcloud/server#17176]
### Steps to reproduce
unknown

### Expected behaviour
should be syncing fine

### Actual behaviour
doesn't sync because of deadlock

## Server configuration detail

**Operating system:** Linux 4.15.0-62-generic #69-Ubuntu SMP Wed Sep 4 20:55:53 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.19-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, json, igbinary, apcu, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, redis, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud/vm script

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - apporder: 0.7.1
 - audioplayer: 2.8.4
 - audioplayer_editor: 0.1.0
 - audioplayer_sonos: 1.0.1
 - bookmarks: 2.1.1
 - calendar: 1.7.1
 - camerarawpreviews: 0.7.0
 - checksum: 0.4.3
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - cookbook: 0.4.2
 - dav: 1.9.2
 - drawio: 0.9.3
 - event_update_notification: 0.3.4
 - external: 3.3.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_fulltextsearch: 1.3.6
 - files_markdown: 2.1.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trackdownloads: 1.5.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - forms: 1.0.3
 - fulltextsearch: 1.3.6
 - fulltextsearch_elasticsearch: 1.3.6
 - gallery: 18.3.0
 - groupfolders: 4.1.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - mail: 0.17.0
 - metadata: 0.9.0
 - music: 0.10.1
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.2
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - ocsms: 2.1.3
 - onlyoffice: 3.0.0
 - password_policy: 1.6.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - printer: 0.0.1
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - radio: 0.6.5
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - social: 0.2.101
 - socialsharing_diaspora: 1.0.4
 - socialsharing_email: 1.0.5
 - socialsharing_facebook: 1.0.4
 - socialsharing_twitter: 1.0.4
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - talk_simple_poll: 1.0.0
 - tasks: 0.11.2
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - video_converter: 0.1.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "192.168.86.20",
        "cloud.betaleaf.net",
        "office.betaleaf.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "1800",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 180",
    "versions_retention_obligation": "auto, 365",
    "simpleSignUpLink.shown": "false",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "Etc\/UTC",
    "htaccess.RewriteBase": "\/",
    "enable_previews": true,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Operating system:** Windows 10 1809 Build 17763.737

## Logs

<details><summary>Web server error log</summary>
<a href="https://github.com/nextcloud/server/files/3620760/error.log">error.log</a>
</details>

<details><summary>Nextcloud log</summary>
<a href="https://github.com/nextcloud/server/files/3620763/nextcloud.log">nextcloud.log</a>
</details>

<details><summary>Browser log</summary>
None, Used win32 client.
</details>

<details><summary>Postgres log</summary>
<a href="https://github.com/nextcloud/server/files/3620765/postgresql-10-main.log">postgresql-10-main.log</a>
</details>

I have a 7.9 GB modsec_audit.log file if y'all need it

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

These deadlocks are hard to tackle. Mind to append your issue template with the relevant information to https://github.com/nextcloud/server/issues/15047? There are some first ideas how to fix it.

> ModSecurity: Request body (Content-Length) is larger than the configured limit (13107200). 

Please check your mod security rules.

**Comment by BetaLeaf** [comment]
I had a feeling that would be the case. I'm still in the testing phase so I ended up wiping down everything on the server and starting from scratch again.
