### ISSUE TITLE
Deleting Two-Factor Apps do not disable function

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#17188]
I installed these for testing:

- Two Factor e-mail provider 
- Two-Factor TOTP Provider 

and enable it for one single user. 
When I deleted the apps, the test user can't login because a second Auth is needed. So the user is look out of the system. 

I think deleting the app should disable the user setting, too. 

Nextcloud 16.0.4

**Comment by kesselb** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Nope, it should not, for obvious security reasons. Otherwise an attacker could trigger an error in the app, where Nextcloud can also disable an app. And thus they could gain access to the system.

Use the ``occ twofactorauth:cleanup <provider id>`` command.

**Comment by HannesJo0139** [comment]
> Use the `occ twofactorauth:cleanup <provider id>` command.

@ChristophWurst could you point me to the docs where I can find info about that command? I cannot find anything about occ twofactorauth.

**Comment by kesselb** [comment]
@HannesJo0139 

https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#two-factor-authentication

**Comment by HannesJo0139** [comment]
> @HannesJo0139
> 
> https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html#two-factor-authentication

That is about `occ twofactor:disable` and `occ twofactor:enable` only. Nothing about `occ twofactorauth:cleanup` or `occ twofactorauth` in general. That's why I ask. It seems undocumented to me.
