### ISSUE TITLE
iOS 13 not syncing tasks

### ISSUE THREAD

**Issue by ximum** [nextcloud/server#17190]
Hi out there,
i have just updated my iPhone to iOS 13 GM and recognized that my tasks weren’t syncing anymore, same with iPadOS 13 Beta 8
Devices with 12.x.x still sync flawlessly, other clients like thunderbird work too.
Calendar events are synced on iOS 13 with no problems instead. 

Deleting and reconfiguring the CalDAV account was no success, now even the different calendars don’t show up in the iOS tasks app again.

I was wondering if now one already had this problem? Please excuse me if i’m in the wrong area, but i didn’t know if it’s a core or a tasks issue. And just before doing intense research for a solution, i wanted to know if i’m the only one with this problem. Please let me know if you need more Details.

**Nextcloud version:** 16.0.4 / 15.x.x

**Tasks version:** 0.11.3

**Updated from an older Nextcloud or fresh install:** updated everything as a attempt for a solution...

**Comment by raimund-schluessler** [comment]
The CalDAV server belongs to server/core. The Tasks app is not involved in the sync process, it is only a client itself. Hence moving to server.

Also, I cannot test or reproduce at the moment, since my iOS device still is on iOS 12.

**Comment by tcitworld** [comment]
That's an Apple issue. The new task app doesn't use CalDAV anymore and removes old tasks from sync.

> CalDAV is a globally accepted, open standard that iCloud has in fact been a big part of for decades. We don't see Apple removing support for this, however it is unfortunate that the new Reminders app will no longer sync over CalDAV as this would mean you have to choose between Reminders and anything else. If you wish that it still did, please leave feedback with Apple and let them know.


[All lists and tasks deleted in 2Do after upgrading to macOS 10.15 Reminders or iOS 13 Reminders](https://www.2doapp.com/kb/article/all-lists-and-tasks-deleted-in-2do-after-upgrading-to-macos-10-15-reminders-or-ios-13-reminders.html)

**Comment by tcitworld** [comment]
Let's add some kind of warning in https://docs.nextcloud.com/server/16/user_manual/pim/sync_ios.html

**Comment by georgehrke** [comment]
Also see https://support.busymac.com/help/112428-reminders-from-ios-13-macos-10-15-reminders-aren-t-syncing

I'm afraid if Apple decides to drop support for CalDAV in Reminders and replaces it with their own proprietary protocol, there is not much we can do about it.

If you want to keep using the old reminder app, do not upgrade to the new reminders when prompted, otherwise i can only recommend to look for a different tasks app or obviously just use the great online [tasks app](https://apps.nextcloud.com/apps/tasks) by @raimund-schluessler

**Comment by BernieO** [comment]
Hm. I updated my iPhone SE to iOS 13 and the caldav-sync of reminders is still working:

- adding a new reminder in my iOS 13 iPhone gets synced to Nextcloud and shows up on my iPad with iOS 12.
- adding a new reminder in my iOS 12 iPad gets synced to Nextcloud and also shows up on my iPhone with iOS 13.

I did not change anything after the upgrade, neither in iOS-settings nor in my Nextcloud configuration (nor webserver-config). I am still using Nextcloud 15(.0.11) though.

**Comment by raimund-schluessler** [comment]
> 
> 
> Hm. I updated my iPhone SE to iOS 13 and the caldav-sync of reminders is still working:
> 
>     * adding a new reminder in my iOS 13 iPhone gets synced to Nextcloud and shows up on my iPad with iOS 12.
> 
>     * adding a new reminder in my iOS 12 iPad gets synced to Nextcloud and also shows up on my iPhone with iOS 13.
> 
> 
> I did not change anything after the upgrade, neither in iOS-settings nor in my Nextcloud configuration (nor webserver-config). I am still using Nextcloud 15(.0.11) though.
> 
> EDIT: I am using the final release version of iOS 13

Same for me. I updated to iOS13 and everything (syncing back and forth) still works. I also was not confronted with a question whether or not to migrate the reminder database (as described in the 2Do blog above).

**Comment by georgehrke** [comment]
Maybe Apple changed their mind in the last minute, because too many people complained.  I will also upgrade to iOS 13 soon and unpin this ticket if i can't reproduce it anymore.

**Comment by tcitworld** [comment]
Yup, in the end, it still works for me too (iOS 13.1)

**Comment by raimund-schluessler** [comment]
I might start to understand why its for some not working anymore. I think this is only the case when you synced over iCloud (and from there by CalDAV probably). I switched on Reminders in iCloud setup on the iPhone (I had them disabled before, because I only use Nextcloud CalDAV) and the update button appeared for the iCloud reminders:

![19-09-20 15-59-30 3226](https://user-images.githubusercontent.com/2496460/65340732-27906b00-dbcf-11e9-855b-8f6c48803216.png)

After I touched it, I got an upate window where I confirmed the update and it looked like this afterwards:

![19-09-20 17-44-04 3227](https://user-images.githubusercontent.com/2496460/65340783-47c02a00-dbcf-11e9-8353-dc948436877a.png)

Reminders in the iCloud list now offer some more features than the ones in the Nextcloud CalDAV calendars (e.g. subtodos). CalDAV sync to the Nextcloud still works as before, though.

**Comment by BernieO** [comment]
> Deleting and reconfiguring the CalDAV account was no success, now even the different calendars don’t show up in the iOS tasks app again.

I‘ve been brave and deleted my Nextcloud-caldav account from my iPhone with iOS 13.
Re-adding the account (with service-discovery) worked as expected - all calendars including their tasks show up in the iOS 13 tasks-app as well as all calendars and events in the iOS 13 calendar-app.

**Comment by georgehrke** [comment]
It seems Apple changed the behaviour in the iOS 13 final. Removing as pinned issue.

**Comment by guidedways** [comment]
I've tested this just now, changes in Reminders do not sync with any other CalDAV client and vice versa. So the behavior hasn't changed, but Apple may have dropped the silly migration step where everything from their account is deleted (although I doubt it - I'll have to test to make sure).

**Comment by guidedways** [comment]
Mind you - there's two things at play here:

1) Reminders (essentially an app that used to display task-only calendars) does not sync back and forth with CalDAV

2) Upgrading Reminders would delete everything from every other CalDAV client (essentially it would delete all task-only calendars from their iCloud CalDAV account).

(1) is still true, I haven't yet tested (2) but I suspect this would still be the case, unless they've stopped doing that and left users even more confused as to why Reminders won't sync.

**Comment by HackintoshHD** [comment]
I'm using both Apple Reminders and BusyMac's BusyCal with Nextcloud CalDAV only, each of them on both iOS (iPhone SE, iPad Pro) and macOS. I can confirm @BernieO 's and @raimund-schluessler 's findings:

1. After upgrading my iPhone SE to iOS 13 and launching Apple's iOS13 Reminders app, I didn't notice any dialogue of a Reminders data migration, just an introduction to new features of the Reminders app in iOS 13 as far as I can remember.

2. Tasks are still successfully synced back and forth between the server and all apps involved, just as they were in iOS 12.

3. The iOS 13 Reminders app launch did not delete any task items or calendars on the server. It however seems to have **_added_ a new CalDAV calendar** on the server named **'Inbox'**.

**Comment by guidedways** [comment]
Thanks for the thorough response. 

I don't know, ¯\_(ツ)_/¯ we're still getting feedback from users reporting their Reminders app has stopped syncing with CalDAV, and are suffering from the exact same symptoms listed on our support page (i.e. everything replaced with a new calendar called "Reminders ⚠️").

Maybe there are certain regions they're doing this more aggressively with or certain 'kind' of users that experience this. I simply don't know as Apple won't say. People who aren't experiencing loss of sync between Reminders and other apps are lucky I guess, while the rest of us are suffering from this unwarranted change.

**Comment by swingpatrol** [comment]
Hi!

(sorry if this is not the right place to write, as I see the thread is closed; in case, please, tell me where to write)

My contribution on IOS 13 Reminders caldav problems and a question on nextcloud configuration.

I have performed some tests and, in my case, it seems that IOS 13 Reminders continues to support CalDAV while the sync problems could depend on the specific used server. 

At the moment I have configured 3 accounts for my iPhone Reminders:

- CalDAV with my Owncloud (it worked until IOS 12; no more working with IOS 13)

- CalDAV with an online free service (caldav-sync works perfectly!!)

- iCloud, not upgraded (it works)

![Screenshot 2019-10-01 at 15 42 08](https://user-images.githubusercontent.com/36482442/65970910-a905ba00-e467-11e9-901a-8e144a508a0d.png)

So, my guess is that my old caldav Owncloud server could be the cause of the caldav-sync problems with IOS 13.

Now I would like to configure a NextCloud as a caldav server.

Question:
people who have NextCloud caldav server working with IOS 13 Reminders (@BernieO, @raimund-schluessler, ...), could you, please, provide some tip/information about the version and configuration of your server?

Thanks!

**Comment by raimund-schluessler** [comment]
I run Nextcloud 16.0.5.

**Comment by j-ed** [comment]
@swingpatrol Please post this kind of questions in the [Nextcloud help forum](https://help.nextcloud.com/), because the purpose of this repository is to track bugs.

**Comment by BernieO** [comment]
This turns out to be a certificate issue. Apple increased the requirements for certificates in iOS13 and MacOS 10.15 (Catalina): https://support.apple.com/en-us/HT210176

With a proper certificate fullfilling the new requirements the reminder sync works without any problems. I am using a letsencrypt certificate which meets the requirements. That is why my reminders kept syncing.

On my private homeserver I‘ve been using a selfsigned certificate. I tried to setup caldav-sync there which worked for calendars, by reminders stayed empty. With a new selfsigned certificate fullfilling the requirements and imported to iOS the reminders now do also sync on my homeserver with a selfsigned certificate.

**Comment by BernieO** [comment]
Meanwhile Apple refreshed their page about the new reminders app. It clearly states now, that only the primary iCloud account is affected from the upgrade process and caldav-Accounts are not changed:

>The upgrade process affects existing reminders in your primary iCloud account only. Reminders in all other accounts, such as secondary iCloud accounts and CalDAV and Exchange accounts, aren't changed.
(https://support.apple.com/en-us/HT210220)

**Comment by Hakbarth** [comment]
If somebody wants to know why it does not work in 2026, https is mandatory to be used even in local set up (SSL-encryption) in the settings of the nextcloud account in ios / ipad os, otherwise Reminders will not sync properly. After using SSL, it works.
