### ISSUE TITLE
Incorrect display of enabled app

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#17193]
- Enabled app are displayed as disabled in "Disabled app".

Enabled app:
![obraz](https://user-images.githubusercontent.com/47037905/65141955-f3bc1680-da11-11e9-97a5-67af8ad455c6.png)

App as disabled in "Disabled app".
![obraz](https://user-images.githubusercontent.com/47037905/65141908-db4bfc00-da11-11e9-971a-53eec2d7de60.png)

- I also noticed that the displayed version of the GpxPod app is not compatible with the installed version.

Displayed in "Your apps":
![obraz](https://user-images.githubusercontent.com/47037905/65142141-53b2bd00-da12-11e9-929a-62b581defc8a.png)

Displayed in app:
![obraz](https://user-images.githubusercontent.com/47037905/65142124-4ac1eb80-da12-11e9-98f9-d09d7b0a16de.png)

**Nextcloud version:** (see Nextcloud admin page)
17.0.0 RC 1 and 16.0.4

**Comment by kesselb** [comment]
Hmm. I don't know how to reproduce :worried:

**Comment by Valdnet** [comment]
@kesselb The GpxPod v4.0.5 app is installed via the app store.

**Comment by Valdnet** [comment]
@kesselb I found the reason. On the server I kept old copies of the old versions of the app. After they were removed, everything returned to normal.
I only wonder why the app information referred to the old directories.
