### ISSUE TITLE
Installation error  An exception occurred while executing

### ISSUE THREAD

**Issue by x0penghui** [nextcloud/server#17205]
# Releases  v17.0.0rc1

An exception occurred while executing 'SELECT "uid", "displayname" FROM "oc_users" WHERE "uid_lower" = ?' with params ["admin"]: SQLSTATE[HY000]: General error: 1 no such table: oc_users

**Comment by x0penghui** [comment]
### Both MySQL and SQLLite have only `oc_migrations`, cannot find `oc_users` and other tables.

![image](https://user-images.githubusercontent.com/11740100/65250627-71724600-db28-11e9-8f8b-c1f7f59985f3.png)

**Comment by x0penghui** [comment]
surroundings
Windows10
Apache2.4
PHP7.1

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

Please note that windows is not supported as os for nextcloud/server.
