### ISSUE TITLE
CMYK Jpeg Images produce a wrong colored preview

### ISSUE THREAD

**Issue by waffshappen** [nextcloud/server#17209]
### Steps to reproduce
1. Upload a CYMK image
2. Look at the preview

Alternative: use convert from imagemagick directly, without arguments it will not convert to rgb by default but keep cmyk,

### Expected behaviour
The image preview should be in rgb, so it can be properly displayed by browsers

### Actual behaviour
The image is still kept cmyk, and looks horribly wrong-colored

### Server configuration

**Operating system**:
Fedora 30
**Web server:**
Httpd
**Database:**
Postgresql/Mysql (different servers)
**PHP version:**
7.3-fpm
**Nextcloud version:** (see Nextcloud admin page)
16.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0
**Where did you install Nextcloud from:**
Nextcloud website server.zip

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "http:\/\/cloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 1,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "enable_previews": true,
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "preview_max_scale_factor": 30,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "preview_max_filesize_image": 100,
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
Chromium-vaapi 76/Firefox 69
**Operating system:**
Fedora 30

Logs: irrelevant

**Comment by szaimen** [comment]
I cannot reproduce this on NC21.0.2
@waffshappen If this still happens to you on NC21.0.2, can you please share the testimage here so that I can reproduce this?
Thanks!
