### ISSUE TITLE
Download of files fails after a certain amount of time

### ISSUE THREAD

**Issue by tiotrom** [nextcloud/server#17214]
### Steps to reproduce
For example you can use any of our iso files from here https://www.cloud.tromsite.com/index.php/s/oseAb7yxwBNy9jL - download via the browser and after a few minutes you will see that the download fails. This can be a server issue since we tried to debug it for the past days, and the hosting company said we may reach some limits with FCGI. But we are not sure what kind of limits. We have a VPS. It is true that if we use CGI instead of FCGI the downloads work, but the .htaccess of nextcloud is not properly read and there are some other errors.

### Expected behaviour
The download should not time-out.

### Actual behaviour
The download fails. 

## Server configuration detail

**Operating system:** Linux 4.9.159-vs2.3.9.8-vs+ #4 SMP Wed Aug 28 15:05:40 PDT 2019 x86_64

**Webserver:** Apache (fcgi)

**Database:** mysql 5.7.25

**PHP version:** 

7.2.11
Modules loaded: Core, date, libxml, pcre, sqlite3, filter, hash, mbstring, SPL, PDO, Reflection, sodium, pdo_sqlite, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, exif, fileinfo, ftp, gd, gettext, iconv, imap, json, mysqlnd, openssl, pcntl, pdo_mysql, zlib, posix, pspell, mysqli, SimpleXML, soap, sockets, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, imagick, memcached, intl, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - apporder: 0.7.1
 - bruteforcesettings: 1.4.0
 - checksum: 0.4.3
 - cloud_federation_api: 0.2.0
 - dav: 1.9.2
 - deck: 0.6.6
 - drawio: 0.9.3
 - external: 3.3.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_external: 1.7.0
 - files_markdown: 2.1.0
 - files_mindmap: 0.0.15
 - files_pdfviewer: 1.5.0
 - files_retention: 1.5.1
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.3
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - richdocuments: 3.4.2
 - serverinfo: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - text: 1.0.2
 - theming: 1.7.0
 - theming_customcss: 1.3.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - audioplayer
 - comments
 - dropit
 - encryption
 - files_accesscontrol
 - files_antivirus
 - files_external_gdrive
 - gallery
 - keeporsweep
 - ojsxc
 - polls
 - sharebymail
 - survey_client
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "www.cloud.tromsite.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "overwrite.cli.url": "http:\/\/www.cloud.tromsite.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here

The log file is to big so it can be accessed from here https://www.cloud.tromsite.com/index.php/s/zyWxgJHA2DXLrdn
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by tiotrom** [comment]
A mention: it almost always fails after 9 minutes. Which is odd.

**Comment by tiotrom** [comment]
Update: It seems the issue is with FCGI timeout. We tested more and more. Our server's FCGI timeout limit is between 450 and 560 they said. As we know the recommended for nextcloud is around 300? If that's the case it should work. Why do we reach the FCGI limit after say 9 minutes? HPPT downloads work perfectly fine from the same server (so, direct downloads work). Downloads that last longer than 9 minutes via nextcloud work with CGI or FCGI on Nginx. Not with FCGI on Apache.

**Comment by szaimen** [comment]
Thank you for taking the time to report a problem 👍

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
