### ISSUE TITLE
Account created with Quota unlimited but only 1.7Gb is displayed as usable

### ISSUE THREAD

**Issue by zimzimax** [nextcloud/server#17229]
Hi All,
I have installed Nextcloud successfully , I have created a user to test it and I have set quota as unlimited but when I connect via the ios app I can see that I have only 1.7GB allowed and from the web as well.
Herre a screenshot attached.
Anyone have an idea or it's just a limitation to make us a buy a complete version?
![nextcloud1 7GBissue](https://user-images.githubusercontent.com/55637303/65378786-dc08ba80-dcbd-11e9-9dd8-7d2b0cb3cab4.png)

**Comment by kesselb** [comment]
> a limitation to make us a buy a complete version?

There is no such limitation.

> Anyone have an idea

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com
