### ISSUE TITLE
"Add new" + Icon overlays the directory tree on copy/move modal

### ISSUE THREAD

**Issue by LordSimal** [nextcloud/server#17225]
### Steps to reproduce
1. Click the 3 dots on a file or folder and select "move or copy"
2. On the upcomming overlay the "+" Icon overlay the direcotry tree so you can't go to the root directory

See here 
![image](https://user-images.githubusercontent.com/9105243/65373109-2e73b800-dc79-11e9-988e-1163bf5ffe77.png)

### Expected behaviour
The + Icon should not overlay the directory tree so I can access the root folder

### Actual behaviour
The + Icon does overlay the directory tree and therefore prevents me from going to the root folder

### Possible Solution
Increase the padding of the dirtree to 50px
```
#oc-dialog-filepicker-content .dirtree {
  padding-left: 50px;
}
```

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Version

**Where did you install Nextcloud from:**
Downloaded it from nextcloud.com/install/

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - onlyoffice: 3.0.0
  - password_policy: 1.6.0
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - updatenotification: 1.6.0
  - uploaddetails: 0.1.2
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.pfiff.me",
            "onlyoffice.pfiff.me"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.pfiff.me",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "loglevel": 1,
        "tempdirectory": "\/var\/www\/pfiff.me\/nextcloud\/cloud_tmp",
        "maintenance": false,
        "htaccess.RewriteBase": "\/",
        "theme": "",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_x": 1920,
        "preview_max_y": 1080,
        "preview_max_scale_factor": 1,
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar"
        ],
        "onlyoffice": {
            "verify_peer_off": true
        }
    }
}
</details>

**Are you using external storage, if yes which one:**
No

**Are you using encryption:**
No

**Are you using an external user-backend, if yes which one:** 
No

### Client configuration
**Browser:**
Google Chome 77.0.3865.90

**Operating system:**
Windows 10

#### Browser log
<details>
<summary>Browser log</summary>
JQMIGRATE: Migrate is installed, version 1.4.1
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/core/js/dist/main.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/core/js/dist/share_backend.js.map
2main.js?v=31193276-17:750 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=31193276-17:750
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
translate @ main.js?v=31193276-17:39
P @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
_infoTemplate @ merged-index.js?v=31193276-17:4080
render @ merged-index.js?v=31193276-17:4149
FileSummary @ merged-index.js?v=31193276-17:3926
_createSummary @ merged-index.js?v=31193276-17:7654
initialize @ merged-index.js?v=31193276-17:4926
FileList @ merged-index.js?v=31193276-17:4659
initialize @ merged-index.js?v=31193276-17:84
(anonymous) @ merged-index.js?v=31193276-17:344
(anonymous) @ main.js?v=31193276-17:39
setTimeout (async)
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
P @ main.js?v=31193276-17:39
i @ main.js?v=31193276-17:39
(anonymous) @ merged-index.js?v=31193276-17:343
u @ main.js?v=31193276-17:39
fireWith @ main.js?v=31193276-17:39
ready @ main.js?v=31193276-17:39
O @ main.js?v=31193276-17:39
main.js?v=31193276-17:750 The select2 library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=31193276-17:750
render @ systemtags.js?v=31193276-17:1
render @ systemtags.js?v=31193276-17:1
setFileInfo @ systemtags.js?v=31193276-17:1
(anonymous) @ merged-index.js?v=31193276-17:10333
_.each._.forEach @ main.js?v=31193276-17:39
setFileInfo @ merged-index.js?v=31193276-17:10332
_updateDetailsView @ merged-index.js?v=31193276-17:5220
reload @ merged-index.js?v=31193276-17:6610
changeDirectory @ merged-index.js?v=31193276-17:6458
_onUrlChanged @ merged-index.js?v=31193276-17:5332
P @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
dispatch @ main.js?v=31193276-17:39
_.handle @ main.js?v=31193276-17:39
trigger @ main.js?v=31193276-17:39
e.event.trigger @ main.js?v=31193276-17:278
(anonymous) @ main.js?v=31193276-17:39
each @ main.js?v=31193276-17:28
each @ main.js?v=31193276-17:28
trigger @ main.js?v=31193276-17:39
_onPopState @ merged-index.js?v=31193276-17:303
initialize @ merged-index.js?v=31193276-17:129
(anonymous) @ merged-index.js?v=31193276-17:344
(anonymous) @ main.js?v=31193276-17:39
setTimeout (async)
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
P @ main.js?v=31193276-17:39
i @ main.js?v=31193276-17:39
(anonymous) @ merged-index.js?v=31193276-17:343
u @ main.js?v=31193276-17:39
fireWith @ main.js?v=31193276-17:39
ready @ main.js?v=31193276-17:39
O @ main.js?v=31193276-17:39
main.js?v=31193276-17:750 The select2 library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=31193276-17:750
render @ systemtags.js?v=31193276-17:1
render @ systemtags.js?v=31193276-17:1
setFileInfo @ systemtags.js?v=31193276-17:1
(anonymous) @ merged-index.js?v=31193276-17:10333
_.each._.forEach @ main.js?v=31193276-17:39
setFileInfo @ merged-index.js?v=31193276-17:10332
_updateDetailsView @ merged-index.js?v=31193276-17:5220
reload @ merged-index.js?v=31193276-17:6610
changeDirectory @ merged-index.js?v=31193276-17:6458
_onUrlChanged @ merged-index.js?v=31193276-17:5332
P @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
dispatch @ main.js?v=31193276-17:39
_.handle @ main.js?v=31193276-17:39
trigger @ main.js?v=31193276-17:39
e.event.trigger @ main.js?v=31193276-17:278
(anonymous) @ main.js?v=31193276-17:39
each @ main.js?v=31193276-17:28
each @ main.js?v=31193276-17:28
trigger @ main.js?v=31193276-17:39
_onPopState @ merged-index.js?v=31193276-17:303
initialize @ merged-index.js?v=31193276-17:129
(anonymous) @ merged-index.js?v=31193276-17:344
(anonymous) @ main.js?v=31193276-17:39
setTimeout (async)
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
P @ main.js?v=31193276-17:39
i @ main.js?v=31193276-17:39
(anonymous) @ merged-index.js?v=31193276-17:343
u @ main.js?v=31193276-17:39
fireWith @ main.js?v=31193276-17:39
ready @ main.js?v=31193276-17:39
O @ main.js?v=31193276-17:39
main.js?v=31193276-17:750 The humanFileSize library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=31193276-17:750
_createRow @ merged-index.js?v=31193276-17:6186
fileList._createRow @ merged-index.js?v=31193276-17:8994
e._createRow @ comments.js?v=31193276-17:1
e._createRow @ additionalScripts.js?v=31193276-17:1
_renderRow @ merged-index.js?v=31193276-17:6370
_nextPage @ merged-index.js?v=31193276-17:5864
setFiles @ merged-index.js?v=31193276-17:5942
reloadCallback @ merged-index.js?v=31193276-17:6675
(anonymous) @ main.js?v=31193276-17:39
u @ main.js?v=31193276-17:39
fireWith @ main.js?v=31193276-17:39
r.<computed> @ main.js?v=31193276-17:39
(anonymous) @ client.js?v=31193276-17:495
Promise.then (async)
getFolderContents @ client.js?v=31193276-17:488
reload @ merged-index.js?v=31193276-17:6602
changeDirectory @ merged-index.js?v=31193276-17:6458
_onUrlChanged @ merged-index.js?v=31193276-17:5332
P @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
dispatch @ main.js?v=31193276-17:39
_.handle @ main.js?v=31193276-17:39
trigger @ main.js?v=31193276-17:39
e.event.trigger @ main.js?v=31193276-17:278
(anonymous) @ main.js?v=31193276-17:39
each @ main.js?v=31193276-17:28
each @ main.js?v=31193276-17:28
trigger @ main.js?v=31193276-17:39
_onPopState @ merged-index.js?v=31193276-17:303
initialize @ merged-index.js?v=31193276-17:129
(anonymous) @ merged-index.js?v=31193276-17:344
(anonymous) @ main.js?v=31193276-17:39
setTimeout (async)
(anonymous) @ main.js?v=31193276-17:39
(anonymous) @ main.js?v=31193276-17:39
P @ main.js?v=31193276-17:39
i @ main.js?v=31193276-17:39
(anonymous) @ merged-index.js?v=31193276-17:343
u @ main.js?v=31193276-17:39
fireWith @ main.js?v=31193276-17:39
ready @ main.js?v=31193276-17:39
O @ main.js?v=31193276-17:39
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_videoplayer/js/main.js.map
/apps/files/?dir=/tmp&fileid=337173:1 Failed to decode downloaded font: https://nextcloud.pfiff.me/core/fonts/Nunito-Regular.woff2
/apps/files/?dir=/tmp&fileid=337173:1 OTS parsing error: invalid version tag
/apps/files/?dir=/tmp&fileid=337173:1 Failed to decode downloaded font: https://nextcloud.pfiff.me/core/fonts/Nunito-Bold.woff2
/apps/files/?dir=/tmp&fileid=337173:1 OTS parsing error: invalid version tag
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/viewer/js/viewer.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_sharing/js/dist/collaboration.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_trashbin/js/files_trashbin.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_sharing/js/dist/files_sharing.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_versions/js/files_versions.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/comments/js/comments.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/notifications/js/notifications.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_sharing/js/dist/additionalScripts.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_texteditor/build/editor.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_markdown/build/editor.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/files_markdown/build/styles.css.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/recommendations/js/main.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/core/js/dist/systemtags.js.map
DevTools failed to parse SourceMap: https://nextcloud.pfiff.me/apps/systemtags/js/systemtags.js.map
</details>

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Check https://github.com/nextcloud/server/pull/17017

**Comment by LordSimal** [comment]
Uh sorry, tried to find a similar issue but didn't find that one^^
