### ISSUE TITLE
Video Bug

### ISSUE THREAD

**Issue by BugProg** [nextcloud/server#17224]
### Steps to reproduce
#1 Upload video on the server (video.mkv) The problem is only present if the video is in .mkv format
#2 Play the video on the server (no problem all work normaly) : https://193.248.252.103/s/GKBr9ixjbKm7CaN Screenshot
#3 I want to share my video with a link. But i can't play that : https://193.248.252.103/s/eXbLfFmWoiykHAY Screenshot of the problem.

For #1 #2 and #3 i use the same browser

### Expected behaviour
Play the video

### Actual behaviour
I cant' play the video

## Server configuration detail

**Operating system:** Linux 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l

**Webserver:** Apache/2.4.38 (Raspbian) (apache2handler)

**Database:** mysql 10.3.15

**PHP version:** 

7.3.4-2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - announcementcenter: 3.5.1
 - audioplayer: 2.8.4
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.3
 - cospend: 0.1.0
 - dav: 1.9.2
 - deck: 0.6.6
 - drawio: 0.9.3
 - drop_account: 0.1.0
 - extract: 1.2.0
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_automatedtagging: 1.6.0
 - files_ebookreader: 0.0.1
 - files_fulltextsearch: 1.3.6
 - files_mindmap: 0.0.15
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - fulltextsearch_elasticsearch: 1.3.6
 - gallery: 18.3.0
 - groupfolders: 4.1.0
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - metadata: 0.9.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - passwords: 2019.9.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - quota_warning: 1.5.0
 - recommendations: 0.4.0
 - registration: 0.4.7
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - spreed: 6.0.4
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_admin: 0.4.1
 - twofactor_backupcodes: 1.5.0
 - twofactor_totp: 3.0.1
 - unsplash: 1.1.3
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - files_texteditor
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.4.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "overwrite.cli.url": "https:\/\/192.168.1.36\/nextcloud\/",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Chrome/77.0.3865.75

**Operating system:** Fedora

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Adrien-ops** [comment]
main.js?v=5077270f-0:278 JQMIGRATE: Migrate is installed, version 1.4.1
2main.js?v=5077270f-0:750 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
i @ main.js?v=5077270f-0:750
vendors~videojs.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. an
(anonymous) @ vendors~videojs.js:1
DevTools failed to parse SourceMap: https://192.168.1.36/core/js/dist/share_backend.js.map
DevTools failed to parse SourceMap: https://192.168.1.36/apps/groupfolders/build/files.js.map
DevTools failed to parse SourceMap: https://192.168.1.36/core/js/dist/main.js.map
DevTools failed to parse SourceMap: https://192.168.1.36/apps/text/js/public.js.map
DevTools failed to parse SourceMap: https://192.168.1.36/apps/files_videoplayer/js/vendors~videojs.js.map
DevTools failed to parse SourceMap: https://192.168.1.36/apps/files_videoplayer/js/main.js.map
DevTools failed to parse SourceMap: https://192.168.1.36/apps/files_videoplayer/js/videojs.js.map

**Comment by Adrien-ops** [comment]
Hello,
This ?

**Comment by BugProg** [comment]
https://193.248.252.103/s/XAG6EyyFWERD5om
If you want this is the link for the video

**Comment by kesselb** [comment]
![Screenshot from 2019-09-21 15-20-38](https://user-images.githubusercontent.com/3902676/65373873-70a1f700-dc83-11e9-833a-fea744aa1c53.png)

cc @rullzer

**Comment by BugProg** [comment]
Thank you !
But how to make it work ?

**Comment by go2sh** [comment]
I see this:



![asd](https://user-images.githubusercontent.com/150886/65373945-65030000-dc84-11e9-9c54-d4a5299a6dfe.png)

**Comment by BugProg** [comment]
thank you
There is a solution ?

**Comment by kesselb** [comment]
@BugProg please note that github is not a chat platform. 

Did some more testing with test files from http://www.jell.yfish.us.

jellyfish-10-mbps-hd-h264.mkv :heavy_check_mark: 
jellyfish-10-mbps-hd-hevc.mkv  :x: 

Not sure why playing as user works but not as share. Could not reproduce with the videos above.

**Comment by skjnldsv** [comment]
Hey!
This depends on the browser support.
There is nothing we can do.

We improved with our new Viewer by doing some fancy tricks, but there are some limitations we can't override :shrug:
