### ISSUE TITLE
Deleting some files and folders on S3 doesn't work

### ISSUE THREAD

**Issue by Disco1** [nextcloud/server#17237]
### Steps to reproduce
1. Mount S3 using external file system plugin
2. Add a bunch of files and folders (I used drag and drop) to the S3 mount
3. Try to delete them

### Expected behaviour
Files should all delete

### Actual behaviour
Some files deleted, most did not, and many refused to be deleted at all. I had to go to S3 to delete the files myself.

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache 2.4, SELinux ENABLED

**Database:**
MySQL

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Nextcloud website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Accessibility	1.2.0	Official	
Activity	2.9.1	Official	
Brute-force settings	1.4.0	Official	
Calendar	1.7.1	Official	
Collaborative tags	1.6.0	Official	
Comments	1.6.0	Official	
Contacts	3.1.3	Official	
Deleted files	1.6.0	Official	
External storage support	1.7.0	Official	
Federation	1.6.0	Official	
File access control	1.6.0	Official	
File sharing	1.8.0	Official	
First run wizard	2.5.0	Official	
Gallery	18.3.0	Official	
Log Reader	2.1.0	Official	
Monitoring	1.6.0	Official	
Nextcloud announcements	1.5.0	Official	
Notifications	2.4.1	Official	
Password policy	1.6.0	Official	
PDF viewer	1.5.0	Official	
Plain text editor	2.8.0	Official	
Privacy	1.0.0	Official	
RainLoop	6.0.3		
Recommendations	0.4.0	Official	
Right click	0.15.1		
Share by mail	1.6.0	Official	
Support	1.0.0	Official	
Theming	1.7.0	Official	
Update notification	1.6.0	Official	
Usage survey	1.4.0	Official	
Versions	1.9.0	Official	
Video player	1.5.0	Official	
Viewer	1.1.0	Official	
Auditing / Logging	1.6.0	Official	
Default encryption module	2.4.0	Official	
LDAP user and group backend	1.6.0	Official
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.instanthousecall.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "http:\/\/nextcloud.instanthousecall.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, S3

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Brave

**Operating system:**
Windows

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Disco1** [comment]
Console Log attached.

[console.log.txt](https://github.com/nextcloud/server/files/3643583/console.log.txt)

**Comment by kesselb** [comment]
OK. Looks like https://github.com/nextcloud/server/issues/16491 then.
