### ISSUE TITLE
"Detected suspicious file operations"

### ISSUE THREAD

**Issue by truelai** [nextcloud/server#17247]
Nextcloud 16.0.1

I've received this notice but there is no link to any explanation. What should I be checking to see these operations?

![detected](https://user-images.githubusercontent.com/4158476/65519711-66b30a80-deb4-11e9-8ff4-74beae98f7a0.png)

**Comment by kesselb** [comment]
Thanks for reporting this issue :+1: 



This message is part of [ransomware_detection app](https://github.com/search?q=%22Detected+suspicious+file+operations%22&type=Code). Please report this enhancement to [their repository](https://github.com/undo-ransomware/ransomware_detection).
