### ISSUE TITLE
Shared links with password on Google Chrome

### ISSUE THREAD

**Issue by floviolleau** [nextcloud/server#17246]
Hi,

Thanks for this good product.

I'm facing to an anoying bug since the last upgrade from 16.0.3 to 16.0.4

### Steps to reproduce
1. Have a nextcloud installed under 16.0.3 and working fine
2. Migrate nextcloud from 16.0.3 to 16.0.4 with updater/updater.phar in cli
3. The migration is OK no errors
4. Login by using Chromium like browsers
5. Create a share of a folder or file with password protected.
6. Logout or be in private mode
7. Load the share link
8. See the page to put the password
9. Type the password and press enter or click on the arrow
10. Nothing happens and no errors in dev tools

![image](https://user-images.githubusercontent.com/5442973/65504433-3de84080-dec7-11e9-98f2-03fb09eac642.png)

### Expected behaviour
Be able to see documents of the share password protected with chromium like browsers

### Actual behaviour
Unable to see documents of the share password protected with chromium like browsers. Firefox / Safari are working well.

### Server configuration

**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie

**Web server:**
Apache 2

**Database:**
Mysql Ver 10.13 Distrib 5.5.62

**PHP version:**
PHP 7.3.2 (cli) (built: Mar  8 2019 14:43:12)

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.3

**Where did you install Nextcloud from:**
Used updater/updater.phar to upgrade

**Signing status:**
N/A

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - announcementcenter: 3.5.1
  - audioplayer: 2.8.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_downloadactivity: 1.5.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trackdownloads: 1.5.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - flowupload: 0.1.2
  - gallery: 18.3.0
  - groupfolders: 4.1.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.9.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - polls: 0.10.2
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - quicknotes: 0.1.9
  - quota_warning: 1.5.0
  - ransomware_protection: 1.4.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - sharerenamer: 2.7.1
  - socialsharing_email: 1.0.5
  - support: 1.0.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - encryption
  - files_external
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\ArrayCache",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpport": "465",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "admin_notifications"
        ],
        "simpleSignUpLink.shown": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome Version 76.0.3809.132 (Official Build) (64-bit) but other chromium like are failing. Only Firefox and Safari are ok.

**Operating system:**
Any

#### Web server error log
Nothing

#### Nextcloud log (data/nextcloud.log)
Nothing

#### Browser log
Nothing (see screenshot)

**Comment by kesselb** [comment]
Are you able to reproduce this with https://try.nextcloud.com?

**Comment by floviolleau** [comment]
Issue solved thanks to the comment here https://github.com/nextcloud/server/issues/14471#issuecomment-534737503
