### ISSUE TITLE
Login UI bug with button (alt-login)

### ISSUE THREAD

**Issue by evil7** [nextcloud/server#17243]
hello there. I found a login page UI bug about alt-login button:

my version is 16.0.4 stable

but I found it same in the new versions:

https://github.com/nextcloud/server/blob/61d22ff6cf54af0250a9917ab1b30a5dff1cb236/core/templates/login.php#L11-L13

that I thing we should changed to 

```
<input type="submit" class="login primary" formaction="<?php print_unescaped($login['href']); ?>" value="<?php p($login['name']); ?>" />
```

(I used `formaction` for can not to change the js file. but it maybe not work if not support to html5 tags status)

maybe we should put it all in `<input>` not a `<a>` link. what's U think?

befor:

![TIM截图20190924125841](https://user-images.githubusercontent.com/6292673/65482946-2f9d2300-decd-11e9-8109-f93c6c98a117.png)

fix:

![TIM截图20190924130033](https://user-images.githubusercontent.com/6292673/65482968-3c217b80-decd-11e9-82b7-bf0ff4246c9a.png)

**Comment by kesselb** [comment]
cc @skjnldsv @GretaD

**Comment by skjnldsv** [comment]
This has been changed in 18 already.
What is the exact issue, I don't get your explanation :)

**Comment by evil7** [comment]
Sry I means can't alignment. The button in login page are diff width. And it's only 16.0.4 now at (free) stable version not 18 (maybe it already fixed in Pro 18 version?) I just think we should fix it at 16 version unless all latest update is 18 now :P

**Comment by kesselb** [comment]
17 is the next major release.
18 means the current development branch.

There is no such thing like a pro version. Feel free to submit a patch with your changes. Should be a few lines of css. I don't think we need to replace the a with an button.

**Comment by evil7** [comment]
Yeah. Fix it whatever way I think is all OK. I just don't wanna send a PR just for this "1 line" UI problem. And if it's already being fixed at 18 then plz just close this issue. And thx for this awesome file-cloud project again. <3
