### ISSUE TITLE
Deleted Files - Check All Files  -  delete permanently not working

### ISSUE THREAD

**Issue by ghosttable** [nextcloud/server#17259]
Hi folks,

just noticed a strange behaviour.
1.) Delete some files so they get into Deleted Files 
2.) Mark all files checked
3.) Delete Permanently

Expected Behaviour:
Files get deleted

Behaviour:
nothing happens

If you mark every file or folder by itself and the click delet permanently, all works fine.

Nextcloud 16.0.4.1 
PHP 7.3.9
Mysql 10.4.6

**Comment by kesselb** [comment]
Please add the issue template https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md for easier triage.

**Comment by ghosttable** [comment]
16.0.5.1 still not working

Nextcloud.log dont show any logging for the timestamp.

So could anyone maybe look into it?
