### ISSUE TITLE
Require confirmation when trying to delete an account

### ISSUE THREAD

**Issue by TalviT** [nextcloud/server#17261]
**Is your feature request related to a problem? Please describe.**
As an administrator it is too easy to delete a user in the user selection by a wrong click, because no confirmation is asked for. The same applies to deactivating the user and wipe all of it's devices, while the impersonation option asks for confirmation.

**Describe the solution you'd like**
Require confirmation from the administrator when trying to delete or disable the user, or wipe the user's devices, as done with the impersonate option.

**Additional context**
![Menu](https://user-images.githubusercontent.com/18188251/65609711-862f5d80-dfb0-11e9-9e32-3bb926e455e8.png)
![Impersonation](https://user-images.githubusercontent.com/18188251/65609715-87f92100-dfb0-11e9-8e16-1fa7b08425b5.png)

**Comment by gary-kim** [comment]
While the general design of Nextcloud is make changes reverable rather than have confirmation boxes, user deletion may be one that warrents both.

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Yep, definitely!
@jancborchardt , what do you think we should go for? Popup? This is disruptive, but it is also the most destructive action we have on nextcloud :)

**Comment by enoch85** [comment]
I was seconds from wiping a legit device just moments ago. *peew*

**Comment by ma12-co** [comment]
+1 for the popup window, I think it's good to catch the user's complete attention here :)

**Comment by jkufner** [comment]
How Gitlab does this:

![Screenshot_20190930_145108](https://user-images.githubusercontent.com/16572/65880235-be101980-e391-11e9-8d44-d6be2f70f295.png)

For very destructive operations it asks for the name of the victim. Such a question ensures the user is destroying the intended target and also that a simple missclick does not do anything that bad.

**Comment by jancborchardt** [comment]
UX improvements for this confirmation dialog which is essentially the same for deletion, impersonation and for remote wipe:

- The labels need to be descriptive instead of "Yes / No".
- The actual username needs to be included on the button, e.g. "Impersonate Marco"
- The text "Are you sure blablabla" is just generic filler. We should write what this means. Like

> **Impersonation**
> See Marco’s account as they would see it, including all their personal data.
> [ Cancel ]     **[ Impersonate Marco ]**

> **Remote wipe of devices**
> In case of lost device or exiting the organization, this can remotely wipe the Nextcloud data from all devices associated with the account. Of course only works if they are connected to the internet.
> [ Cancel ]     **[ Wipe Marco’s devices ]**

> **Account deletion**
> Fully delete the user account including all their personal files, app data, etc.
> [ Cancel ]     **[ Delete Marco’s account ]**


Also, the sorting of the action menu is off / reverse. It should be sorted from least destructive to most:
- Impersonate
- Disable user
- Wipe all devices
- Delete user
