### ISSUE TITLE
How can I share a link of an already shared folder?

### ISSUE THREAD

**Issue by sebelk** [nextcloud/server#17265]
I'm using NC 16.01 and I haven't found a way to share a links of an already shared folder.

For example

1. Share Folder "Dir1" with user jdoe.
2. Upload a new file to Dir1.
3. You would like to share the link to "Dir", but in this case, the shared folder "Dir1" is accessible for everyone

I'd want to share the link to "Dir1" again and to be shared only for user jdoe

Is NC able to do that?

Thanks in advance!

**Comment by kesselb** [comment]
I don't think so. There is another issue about this: https://github.com/nextcloud/server/issues/12877
