### ISSUE TITLE
Multiple File Upload - Total Size and Progress Incorrect

### ISSUE THREAD

**Issue by 42CF11059F2F** [nextcloud/server#17279]
**Server:** Debian 10
**PHP:** 7.3
**Browser:** Chrome
**Nextcloud:** 16.0.5

**Issue**
Draggin a file / folder into Nextcloud results in it uploading, with the status showing in the progress bar. If you drag another file / folder to upload before the current one finishes, it uploads correctly, but the status information is incorrect. It shows the total size of the latest file / folder being uploaded instead of the overall total size of upload. This results in the current upload progress exceeding the total upload size, and the progress sticking at 100%:

![image](https://user-images.githubusercontent.com/665111/65694880-74ac8b00-e06e-11e9-9615-a7d3deaaa948.png)

![image](https://user-images.githubusercontent.com/665111/65695009-a9204700-e06e-11e9-8bc6-18f05999a3d8.png)

**Expected Behaviour**
Total file / folder size for all items combined is displayed and the progress doesn't exceed this number, and the progress doesn't hit 100% until complete.

**Comment by kesselb** [comment]
Please report this issue to https://github.com/burgha/nextcloud_uploaddetails

**Comment by a1pilot** [comment]
@kesselb @burgha

Reported to the dev as requested, but dev says bring it back here.

[App Report](https://github.com/burgha/nextcloud_uploaddetails/issues/5)

**Comment by szaimen** [comment]
I think this was fixed in the meantime -> closing.
