### ISSUE TITLE
Move / Copy - New Folder Created But Dialogue Stuck

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/server#17283]
**Server:** Debian 10
**PHP:** 7.3
**Browser:** Chrome
**Nextcloud:** 16.0.5

**Issue**
When moving / copying items, using the "new folder" option results in a soft freeze. After entering the new folder name and pressing the arrow to create it, the panel goes blank and just has the spinning icon. You have to navigate to a different folder within the move / copy dialogue and come back to where you just placed the new folder to see it, or you have to close the dialogue and re-try.

The folder is created correctly, it just doesn't refresh the view and show the updated folder tree or navigate into the new folder as expected.

Creating a folder:
![image](https://user-images.githubusercontent.com/665111/65695651-d5889300-e06f-11e9-8bb1-5ca6a4921d47.png)

Freezing:
![image](https://user-images.githubusercontent.com/665111/65695898-4334bf00-e070-11e9-83f1-8fb8a60d4b20.png)
![image](https://user-images.githubusercontent.com/665111/65695914-492aa000-e070-11e9-8165-793ee0f0f7f7.png)

This isn't a problem in the root folder, it works correctly there. It only gets stuck when in a sub-folder.

I assumed it was due to the "&", but it happened in another folder with a single word name too.

**Expected Behaviour**
New folder is created and either the view refreshes to show it in the list, or you enter the new folder for selection.

**Comment by kesselb** [comment]
> The issue templates can be found here but be aware of the different repositories! See list below. Please always use an issue template when reporting issues.

https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#submitting-issues

**Comment by a1pilot** [comment]
Is this closed purely due to the template or because it's already fixed?

I can reference countless other still opens in the list of issues that don't use the template - I trust this action isn't targeting me specifically.

**Comment by kesselb** [comment]
> Is this closed purely due to the template

Yes. It's lacking the important information.

**Comment by kesselb** [comment]
> Yes. It's lacking the important information.

But in this case, they're sufficient ;)
