### ISSUE TITLE
LDAP: overhaul Jobs/UpdateGroups.php and create occ command for it

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#1728]
aka https://github.com/owncloud/user_ldap/pull/14 done right

This gets into 11 only if everything else planned is done, otherwise → 12.

**Comment by MorrisJobke** [comment]
Also see https://github.com/owncloud/core/pull/26402 (it's an fix for this occ command)

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by joshtrichards** [comment]
This was covered via #39446 (and #33034) from the looks of it. Okay to close this, @come-nc or @blizzz?

**Comment by come-nc** [comment]
Yeah we should be good now.
