### ISSUE TITLE
Move / Copy Files - Missing Root Folder Navigation Link

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/server#17280]
**Server:** Debian 10
**PHP:** 7.3
**Browser:** Chrome
**Nextcloud:** 16.0.5

**Issue**
Move / copy file option doesn't have a way to get to the root folder. Carefully clicking on the left arrow next to the "new folder" icon does achieve this, but requires precision.

![image](https://user-images.githubusercontent.com/665111/65695290-29df4300-e06f-11e9-9626-dc46cdc3e8e2.png)

**Expected Behaviour**
There should be a home or other icon / button to allow navigation to the top level of the Nextcloud users files.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/17017
