### ISSUE TITLE
id3parser does not use 'tempdirectory', violating open_basedir

### ISSUE THREAD

**Issue by cgzones** [nextcloud/server#17291]
### Steps to reproduce
1. Have some music files in nextcloud
2. Visit the containing folder

### Expected behaviour
No error

### Actual behaviour
Nextcloud issues error messages

### Server configuration

**Operating system**: Debian unstable

**Web server:** apache 2.4.41-1

**Database:** mariadb 1:10.3.18-1

**PHP version:** 7.3.9-1

**Nextcloud version:** 16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.3
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "tempdirectory": "\/var\/www\/nextcloud\/tmp",
        "log_type": "syslog",
        "maintenance": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "mydomain"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Sep 26 22:58:12 server02 Nextcloud[9532]: {PHP} tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/var/www/) at /var/www/sites/nextcloud/3rdparty/lukasreschke/id3parser/src/getID3/getid3_lib.php#1001
</details>

**Comment by kesselb** [comment]
```
Index: christophwurst/id3parser/src/getID3/getid3_lib.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- christophwurst/id3parser/src/getID3/getid3_lib.php	(date 1568109763000)
+++ christophwurst/id3parser/src/getID3/getid3_lib.php	(date 1569536193917)
@@ -997,16 +997,7 @@
 
 
 	public static function GetDataImageSize($imgData, &$imageinfo=array()) {
-		$GetDataImageSize = false;
-		if ($tempfilename = tempnam(sys_get_temp_dir(), 'gI3')) {
-			if (is_writable($tempfilename) && is_file($tempfilename) && ($tmp = fopen($tempfilename, 'wb'))) {
-				fwrite($tmp, $imgData);
-				fclose($tmp);
-				$GetDataImageSize = @getimagesize($tempfilename, $imageinfo);
-			}
-			unlink($tempfilename);
-		}
-		return $GetDataImageSize;
+		return @getimagesizefromstring($imgData, $imageinfo);
 	}
 
 	public static function ImageExtFromMime($mime_type) {
```

Mind to try this patch? If it works for you we can send a patch upstream. I guess it's easier to read the information from the data string instead of writing it first to the disk and reading it again.

**Comment by cgzones** [comment]
thanks, the patch works for me

**Comment by StudioMaX** [comment]
> tempnam(): open_basedir restriction in effect. File(/tmp) is not within the allowed path(s): (/var/www/)

Probably some misconfiguration?
Try to add `open_basedir /tmp` in Apache's config or php.ini. Or maybe change `sys_temp_dir` to any allowed path.

**Comment by kesselb** [comment]
> Probably some misconfiguration?

No. `tempdirectory` is a config option for nextcloud. Probably we should ini_set(sys_temp_dir, $configValue) if `tempdirectory` is not empty. Not sure if changing the sys_temp_dir is possible with ini_set.
