### ISSUE TITLE
Unable to authenticate via desktop client login

### ISSUE THREAD

**Issue by MSG-maniac** [nextcloud/server#17303]
I installed it via docker and there is a nginx proxy on the front end. However, the default IP address assigned by docker is not accessible externally, causing the verification to fail.

The server could not complete your request.

If it happens again, please send the technical details to the server administrator below.

More details can be found in the server log.

technical details

Remote address: 10.30.11.1

Request ID: 85bCuBmp0HAB7ubQuvOV

**Comment by MSG-maniac** [comment]
{"reqId":"85bCuBmp0HAB7ubQuvOV","level":3,"time":"2019-09-28T09:08:58+00:00","remoteAddr":"10.30.11.1","user":"admin","app":"index","method":"GET","url":"\/login\/v2\/grant","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Core\\Controller\\ClientFlowLoginV2Controller::grantPage() must be of the type string, null given, called in \/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php on line 166","Code":0,"Trace":[{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":166,"function":"grantPage","class":"OC\\Core\\Controller\\ClientFlowLoginV2Controller","type":"->","args":[null]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"grantPage"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\ClientFlowLoginV2Controller"},"grantPage"]},{"file":"\/var\/www\/html\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\ClientFlowLoginV2Controller","grantPage",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.ClientFlowLoginV2.grantPage"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.ClientFlowLoginV2.grantPage"}]},{"file":"\/var\/www\/html\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.ClientFlowLoginV2.grantPage"}]},{"file":"\/var\/www\/html\/lib\/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/login\/v2\/grant"]},{"file":"\/var\/www\/html\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/var\/www\/html\/core\/Controller\/ClientFlowLoginV2Controller.php","Line":150,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/77.0.3865.90 Safari\/537.36","version":"16.0.4.1"}

**Comment by MSG-maniac** [comment]
Mixed Content: The page at 'https://xxxx.xxx/login/v2/grant?stateToken=Nayk1zTt67fJ5zzFLUC3YDRmffZYZRhEE8wiMq4utd5eHyUqj0v9zzfoA1c0loJ5' was loaded over a secure connection, but contains a form that targets an insecure endpoint 'http://xxxx.xxx/login/v2/grant'. This endpoint should be made available over a secure connection.
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
grant?stateToken=Nayk1zTt67fJ5zzFLUC3YDRmffZYZRhEE8wiMq4utd5eHyUqj0v9zzfoA1c0loJ5:1 Refused to send form data to 'http://xxxx.xxx/login/v2/grant' because it violates the following Content Security Policy directive: "form-action 'self'".

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Would you mind to edit your post and add the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? The information are required to reproduce your issue.

> I installed it via docker and there is a nginx proxy on the front end. 

By default the information from the reverse proxy (e.g. x-forwarded-host, x-forwarded-proto, x-forwarded-for) are ignored. [Please add the ip of your reverse proxy to `trusted_proxies`](https://docs.nextcloud.com/server/17/admin_manual/configuration_server/reverse_proxy_configuration.html). 

I suppose from `Remote address: 10.30.11.1` and that urls generated with http instead of https that this might be the root of your problem.

**Comment by MSG-maniac** [comment]
Nginx I configured according to the official documentation

There is also a frp intranet penetration in front of nginx

Frp will cause all remote access IPs to be 127.0.0.1

So here should be the callback address that returns the domain name format.

Instead of returning the docker container ip

**Comment by MSG-maniac** [comment]
Just tested, as long as there is an error involving the client login callback, here should be the callback domain name? Not a real IP address.

**Comment by kesselb** [comment]
As said. Your problem is quite hard to reproduce without the issue template. I still see a setup issue here. If you are running nextcloud via docker you need to add the internal ip of the reverse proxy (nginx in your case) to `trusted_proxies`. If you run a more complex setup (like reverse proxy > intranet reverse proxy > nextcloud docker) you might use `overwritehost` and `overwriteprotocol` to tell nextcloud the right values for url generation.

**Comment by MSG-maniac** [comment]
Already solved, thank you very much.

It is also recommended that you configure this project on the website configuration page.

**Comment by kesselb** [comment]
> It is also recommended that you configure this project on the website configuration page.

Can you elaborate?

**Comment by MSG-maniac** [comment]
For example, in the website settings page, you can set this option directly through the web page.

**Comment by MSG-maniac** [comment]
https://xxx.xxx.xxx/settings/admin

There are too few options that can be configured under this page. You should add some config.sample.php to configure the graphical configuration of the project.

**Comment by kesselb** [comment]
I agree with you. But this is a different story ;)

**Comment by MSG-maniac** [comment]
Thank you very much for your reply and help me solve the problem. Best blessing

**Comment by Temtaime** [comment]
Same issue, i cannot auth my desktop client in latest nextcloud.
Seems that this regression was introduced in latest versions and i didn't notice it.
I retried all the settings from docs and it doesn't work.
Don't know what to do else.

**Comment by Temtaime** [comment]
@kesselb any ideas? Cannot login on new devices and cannot figure out the cause

**Comment by kesselb** [comment]
> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

@Temtaime

**Comment by Temtaime** [comment]
This is an internal error which is not pointing one to the incorrect settings and used to work once.
I don't see a reason why this should go to the help with an installation.
If you need some additional data, you could just ask.
