### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by cristtiah** [nextcloud/server#17307]
Hi how do I release my NextCloud from maintenance mode from an update.

This Nextcloud instance is currently in maintenance mode, which may take a while. This page will refresh itself when the instance is available again.

**Comment by cristtiah** [comment]
this didnt work

docker exec -u www-data -it nextcloudpi /bin/bash
php /var/www/nextcloud/occ maintenance:mode --off

php not found

**Comment by kesselb** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

**Comment by cristtiah** [comment]
support there is really the worst. Do you have anything that can help me? Thanks I appreciate it.
