### ISSUE TITLE
DELETE FROM "oc_comments" WHERE "id" = $1 

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#17314]
```
2019-09-28 21:05:50.815 UTC [76] ERROR:  invalid input syntax for integer: "%"
2019-09-28 21:05:50.815 UTC [76] STATEMENT: DELETE FROM "oc_comments" WHERE "id" = $1 
```

![image](https://user-images.githubusercontent.com/3902676/65822646-14714100-e248-11e9-8311-f8cd25b19b41.png)

e.g. https://drone.nextcloud.com/nextcloud/server/21987/20/3

https://github.com/nextcloud/server/blob/e4b36f4f47e40529fd41a0b0c55a68a093f725f1/lib/private/Comments/Manager.php#L684-L687

Don't know how to fix it properly :see_no_evil: Code and this string <-> int conversions are confusing :man_shrugging: 

cc @rullzer @nickvergessen

**Comment by nickvergessen** [comment]
On the `eq()` call add a 3rd parameter `, IQueryBuilder::PARAM_INT` (blind guessing the constant name

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/f50abde7ac99fd6f7563fb60b662ca21ac320f34/tests/lib/Comments/ManagerTest.php#L448-L452

Ouch :see_no_evil: It's a test. Should be safe to ignore it.
