### ISSUE TITLE
limit device tokens/passwords to a specific app

### ISSUE THREAD

**Issue by pille** [nextcloud/server#17327]
**Is your feature request related to a problem? Please describe.**
i'm using device tokens/passwords instead of the real account credentials for android-apps on my devices. unfortunately each device has access to all my nextcloud-apps.  

**Describe the solution you'd like**
please implement an optional possibility to restrict device tokens to certain nextcloud-apps.

**Describe alternatives you've considered**
found none. using device tokens/passwords is already a step in the right direction.

**Additional context**
device tokens/passwords can already be restricted minimally (file system access). this should be elaborated.

**Comment by jospoortvliet** [comment]
Duplicate of https://github.com/nextcloud/server/issues/17327

**Comment by jospoortvliet** [comment]
Duplicate of https://github.com/nextcloud/server/issues/17327

**Comment by sunjam** [comment]
> Duplicate of #17327

Duplicate of itself?

**Comment by joshtrichards** [comment]
Duplicate of #2866
