### ISSUE TITLE
Removal of second german non formal language

### ISSUE THREAD

**Issue by Siggi0904** [nextcloud/server#17323]
Hello together,

I'd like to discuss the removal of the second, non formal german language, in all apps and in core.
Many apps, tools and gui's use only the formal language.

The non formal language is in transfix very often only a placeholder for not supported language.

In these case it would be better these second german non formal language in all apps and in Transifex. I think that the quality of one german language will raise with no copy/paste second language.

Great thanks.

**Comment by Siggi0904** [comment]
Hi, no comments to these remove of non formal language?

**Comment by daniu-de** [comment]
you want a comment: I totally agree. Non-formal language might be funny but is totally unnecessary ("Spielerei"). Someone who wants it shall do it himself.

**Comment by Siggi0904** [comment]
For shure, would be easier to handle only one language in transifex.

So please, remove all the option to switch formal/non-formal
and delete non-formal german language in Transifex.

**Comment by rakekniven** [comment]
Closing this here and follow at https://help.nextcloud.com/t/zwei-deutsche-ubersetzungen-ist-das-notwendig/96023

@Siggi0904 Invited you already at Transifex to join discussion.

Cheers
