### ISSUE TITLE
Login page does not follow the language setting in config.php

### ISSUE THREAD

**Issue by sorsbychen** [nextcloud/server#17329]
I have a fresh installation of Nextcloud 16.0.5. 
Two settings have been added to config.php
  'default_language' => 'zh-CN',
  'force_language' => 'zh-CN',
However, the login page is still in English.

**Comment by skjnldsv** [comment]
Hey, those languages are indeed for the user, so on the login page it's not used I guess?

**Comment by skjnldsv** [comment]
Maybe @danxuliu knows since he worked a lot on public pages?

**Comment by kesselb** [comment]
Login page uses the browsers `Accept-Language` header. 

![Peek 2020-01-10 23-20](https://user-images.githubusercontent.com/3902676/72190462-e4693a80-33ff-11ea-83f7-5d42ba52ec0a.gif)
