### ISSUE TITLE
Remote wipe is too easy

### ISSUE THREAD

**Issue by jkufner** [nextcloud/server#17337]
### Steps to reproduce
1. Try to remote wipe a device
2. A confirmation dialog shows, it asks a yes/no question.

![Screenshot_20190930_144658](https://user-images.githubusercontent.com/16572/65879910-27dbf380-e391-11e9-9f38-9ea273924c1f.png)

### Expected behaviour

The confirmation dialog should show whose account it is and whose device is being deleted. The operation is too dangerous for a single click.

The confirmation should not be a single button, it should ask for user name, like Gitlab does when removing a repository:

![Screenshot_20190930_145108](https://user-images.githubusercontent.com/16572/65880235-be101980-e391-11e9-8d44-d6be2f70f295.png)

### Actual behaviour

Click "Yes".

### Server configuration

N/A

See https://youtu.be/oyWXMjb-6ik

**Comment by gary-kim** [comment]
Similar to #17261 but for user's personal settings rather than for the admin. I think we may need to have a discussion about how much confirmation and "undoability" there should be for very destructive actions such as remote wipe and user deletion.

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Yeah, let's have both in #17261
