### ISSUE TITLE
Disable "Add to your nextcloud" option in public gallery links

### ISSUE THREAD

**Issue by grenzverkehr** [nextcloud/server#17343]
Although all Federated Cloud Sharing options have been deselected, it is still displayed in public gallery links.

In public links it works (https://github.com/nextcloud/server/issues/12395 and https://github.com/nextcloud/server/pull/13261).

**Comment by szaimen** [comment]
Now that the gallery isn't available anymore, the problem won't come up anymore. -> closing.
