### ISSUE TITLE
[NC17] Broken update notification

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#17346]
When nextcloud update is avail, folowing notification showed on every page

![изображение](https://user-images.githubusercontent.com/12619075/65931118-b6ad4680-e44b-11e9-9db2-362be90b586b.png)

**Comment by dohlin** [comment]
I too am getting this using the linuxserver docker container, caused by the update notifications app.  If I disable that app all prompts go away, but with it enabled I see if every time there is an update available.  Latest version of NC currently (18.0.1).

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by mrtnmtth** [comment]
Should be fixed via https://github.com/nextcloud/server/pull/23175
