### ISSUE TITLE
X-Frame-Options wrong Check

### ISSUE THREAD

**Issue by sapycola** [nextcloud/server#17341]
On security check:
L'intestazione HTTP "X-Frame-Options" non è configurata come "SAMEORIGIN". Questo è un potenziale rischio di sicurezza o di riservatezza, e noi consigliamo di modificare questa impostazione.
Not configurated "SAMEORIGIN" but in GET call i have this HEADER

Pragma: | no-cache
-- | --
X-Frame-Options: | SAMEORIGIN
X-Content-Type-Options: | nosniff
X-XSS-Protection: | 1; mode=block
X-Download-Options: | noopen
X-Permitted-Cross-Domain-Policies: | none
Referrer-Policy: | no-referrer
X-Robots-Tag: | none
Content-Length: | 0 byte
Keep-Alive: | timeout=5, max=100
Connection: | Keep-Alive
Content-Type: | text/html; charset=UTF-8

Nextcloud 16.0.5
How to send log?

curl -I https://colantonio.homelinux.net/nextcloud/index.php/

OS: CentOS8

**Comment by kesselb** [comment]
```
curl -I -s https://colantonio.homelinux.net/nextcloud/index.php|grep "X-"|sort
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Powered-By: PHP/7.2.11
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
```

X-Frame-Options is there two times. Please remove it from your webserver configuration.

**Comment by sapycola** [comment]
Ok, Thanks I have resolved it!

:)

Il lun 30 set 2019, 22:43 Daniel Kesselberg <notifications@github.com> ha
scritto:
