### ISSUE TITLE
user_ldap group/uid association fails with memberUid

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#1735]
With a fresh Nextcloud 10.0.1 installation, I'm having troubles with openldap groups.

Nextcloud access is allowed for members of a specific groupOfNames object via memberOf, that works fine.

Nextcloud groups should be taken from ldap posixGroups. These are imported correctly, but group membership via memberUid isn't resolved, although uid/group association is defined correctly.
Testing with groupOfNames, I could verify that still memberOf or member is used, not memberUid.

This might be a degradation (another site installed from NC9 imported uid/group assoc back then correctly; similar config but openldap has no memberOf capabilities), or caused by the memberOf enabled openldap server.

**Comment by andreas-p** [comment]
Just had to add a posixGroup to that other production server (NC10.0.0) without memberOf capabilities. No problem resolving uid/group association, so the problem mentioned above is either a 10.0.0->10.0.1 regression, or memberof related.

**Comment by MorrisJobke** [comment]
cc @GitHubUser4234 @blizzz

**Comment by blizzz** [comment]
@andreas-p isn't this fixed by https://github.com/nextcloud/server/pull/3329?

**Comment by andreas-p** [comment]
I think so.
