### ISSUE TITLE
Allow to setup number of visible application icons

### ISSUE THREAD

**Issue by ewidance** [nextcloud/server#17365]
Nextcloud show icon apps  in a directly available / more scheme. 
Number of directly visible icon is dependant of /core/js/js.js:
var usePercentualAppMenuLimit = 0.33;

It would be interresting to allow to parameter this settings for having a larger zone for icons allowing to directly pick more applications. 

For example, 0.50 allow to see 13 apps.

**Comment by kesselb** [comment]
I hope it's okay with you to close this issue as duplicate of https://github.com/nextcloud/server/issues/13079

**Comment by teotikalki** [comment]
How about 'it's ok if doing so acknowledges that this is a highly requested feature wanted by MANY' and not 'we hear this all the time and still don't care'?

**Comment by kesselb** [comment]
> doing so acknowledges that this is a highly requested feature wanted by MANY

Yes.

> we hear this all the time and still don't care

We are closing issues as duplicates to keep all information / discussion at one place.
