### ISSUE TITLE
Revoke an wipe device the same?

### ISSUE THREAD

**Issue by NorryNew** [nextcloud/server#17369]
### Steps to reproduce
click revoke or wipe has the same dialog an messagetext

### Expected behaviour
there should be difference

### Actual behaviour
the same for the user

## Server configuration detail

**Operating system:** Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.17

**PHP version:** 

7.3.9-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** webinstaller

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.4
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_external_onedrive: 1.0.6
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - maps: 0.1.2
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - ownbackup: 19.9.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.180.36"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "overwrite.cli.url": "http:\/\/192.168.180.36\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "beta",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "calendar",
        "files_external_onedrive",
        "issuetemplate"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by rullzer** [comment]
They are not the same.
Revoke just removes access.
Wipe will wipe the device if it supports our wipe API.

**Comment by NorryNew** [comment]
then it was a hickup in my installation, sorry

**Comment by dicenl** [comment]
NorryNew, did you do anything to get this fixed? I just tested the wipe device option, but all that happened is that the remote client gets logged out, but the files remain on the system. In the webinterface it does say that the device is marked for remote wipe. Do i need to install some extra modules for the nextcloud api?

**Comment by NorryNew** [comment]
dicenl, no nothing at the serverside, but you need a actual APP and maybe it is only for Android, but i am not sure.

**Comment by dicenl** [comment]
ok tnx for to reply! not sure what i'm missing here. will look in to it.

**Comment by Schedulaar** [comment]
I have a similar question due to the a bit spartan documentation under https://docs.nextcloud.com/server/latest/developer_manual/client_apis/RemoteWipe/index.html:

Does Wiping also remove the access of the device?

The attack vector is a stolen, unencrypted device. Once noticed, that the device was stolen, the user clicks on "Wipe Device".
Is it then possible for the attacker to read the token from the file system of the stolen device (possibly he doesn't boot the device nor start the nextcloud client) and retrieve user data? Or is the token already "invalid" and no more API requests are possible (except for the wiping endpoints) once the device has been marked for wiping?
At least, that's what I would expect. If that is the case, maybe someone can update the documentation and a sentence here?
