### ISSUE TITLE
Bring back the "Delete" option from fullscreen picture viewer

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#17361]
I recently upgraded to NC 16 (snap) and while filtering my photos, I noticed I can't quickly remove some of the pics like I used to in the version 15.

Picture: new top-bar is missing the "delete" function
![Screenshot_20191001_192813](https://user-images.githubusercontent.com/36133540/65985194-a0ba7880-e481-11e9-811d-247fb54893af.png)

I dont know what the motivation for removing it was, but it always served me great purpose so I would suggest putting it back.

**Comment by kesselb** [comment]
I think the gallery app has been replaced by the viewer app but is still available via the app store. Could that fix your issue (by switching back to the gallery app)? I don't think the viewer app ever had a delete button.

**Comment by pilsnerbeer** [comment]
you are correct - I didn't realize that the gallery app was replaced. Switching to it brings it back but I imagine it also brings back the problems and bugs that came with it (I remember having issues with video files that I am not noticing any more with Viewer- just tested a few files and everything seems OK.)

So I'll probably switch over to Viewer but my suggestion can stay, as the Viewer app is missing "Delete" function which was very useful for me back in NC15.

**Comment by pilsnerbeer** [comment]
Moving my request to nextcloud/viewer
