### ISSUE TITLE
All repair steps should be verbose when updating via "occ upgrade"

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#1737]
Currently we only show output for repair steps that report their progress. All others are executed quietly. This caused me a lot of confusion while working on a repair step for Mail.

As suggested by @rullzer we should enable output for all repair steps by default. Running "occ maintenance:repair" does it too.

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
I plan to make the verbose mode default and log also the output by default. Let me see if I can come up with a good solution.

**Comment by MorrisJobke** [comment]
#2314 simply logs everything to the log file even if not started in verbose mode. Does this solve the issue for you? I will close this one here then :)
