### ISSUE TITLE
Visual indication of Comments in Webui

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#17376]
Hi, I'd like to encourage adding a visual indication of comments to the webui of the Files app.  This could make it easier to browse and access comments.  Currently, comment status is only displayed in the Activity and Recommendations app.  In the Files app, it is buried under ... menu > Details > Comments

Suggestion:

![show-comments-webui](https://user-images.githubusercontent.com/1787238/66072073-30efd080-e509-11e9-8a9a-ee6044c3d1cf.png)

_This tells me there are comments about this folder._

![2-new-comments](https://user-images.githubusercontent.com/1787238/66072077-3220fd80-e509-11e9-8f49-216f3465208d.png)

_And, this tells me there are two new and unread comments!_

I like either of these examples because they are visually clear, can be used to access comments easily, and match up with the current functionality of viewing a Favorite Star or seeing what is actively shared at a glance.
![Screen Shot 2019-10-02 at 11 40 59 AM](https://user-images.githubusercontent.com/1787238/66072303-a6f43780-e509-11e9-9ee1-5c97b23e5a45.png)

Edit: [Discussion about comments started here](https://help.nextcloud.com/t/lets-talk-about-comments/61238).

**Comment by Spartachetto** [comment]
I signal two related issues.

One is #6424 (_Indicator for tagged files in list_) which starts with: "_It looks like there is no hint or any sign, when a file has tags or **comments**_". So maybe the two issues are similar...

The other one is nextcloud/android#2908, which is about displaying comments in the android client.

I seem to remember also a discussion with the participation of @jancborchardt in which different possible icons for the presence of comments were discussed, with the possibility to distinguish between the presence of a comment by the same user, an unread comment from another user and a read comment from another user. I am sorry but I do not recall which issue was.

I do think that knowing which file has comments without opening the details would be very useful

**Comment by jancborchardt** [comment]
We need to think about mobile first, and also about the grid view. An additional icon in the list is not going to work there.

So I’d say we could have an indicator which is combined with the 3-dot action icon, like either a comment-icon overlapped.

Then when you open the action menu, the "Details" entry could have a subline saying "3 new comments".

**Comment by Spartachetto** [comment]
I am fine with not having this kind of information on mobile and in grid view. 

Yet I'd really like to see all the files with comments (and tags) in a folder without the need to open **all the details entries**  when I am not in the grid view!

This same behaviour would be the same of most file managers of the different operating systems I know: 
- in grid view you see something of the content of the file (image preview, beginning of the text, ...)
- in detailed view you see more details of the data about the file. Here comments and tags status of the file would fit perfectly, in my humble opinion...

**Comment by thomasgg23** [comment]
Would love to see this enhancement with the icons for the comments.

For the mobile view, couldn't there be an icon including the comment symbol like the star symbol for the favorite files?

**Comment by marcelklehr** [comment]
This has landed some time ago, now.
