### ISSUE TITLE
Nextcloud with Minio

### ISSUE THREAD

**Issue by mruslan97** [nextcloud/server#17384]
Hi all! Is it possible to use nextcloud + collabora + minio as primary or external storage? 
When i change config.php and set minio as primary s3 storage all plugins stopped, and app store show message: your nextcloud version not compatible

**Comment by nagdevAmruthnath** [comment]
MinIO can be used as external storage. Enable external storage in Apps --> then in settings, select external storage --> Amazon S3 and fill out all the information. Click the box use path style and you should be able to connect individual buckets.
