### ISSUE TITLE
 The column 'uid_lower' on table 'oc_users' already exists.

### ISSUE THREAD

**Issue by kr15714n** [nextcloud/server#17381]
RESOLVED: allsync issue

Keep getting this error on upgrade then update Nextcloud. Cannot access newly created Pro account for Allsync

Update to 16.0.5

Doctrine\DBAL\Schema\SchemaException: The column 'uid_lower' on table 'oc_users' already exists.

**Comment by kesselb** [comment]
Hmm. Have you contacted Allsync? Allsync looks like a managed instance.

**Comment by kr15714n** [comment]
Yeah, my bad. Should have set this as resolved. It was allsync
