### ISSUE TITLE
Deprecate share type GUEST

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#17389]
So, there is a migration here, meaning we cannot really remove the guest type
https://github.com/nextcloud/server/blob/7800a9bc24d50d3eed40f8b1d40236a262b4f8ef/apps/files_sharing/lib/Migration/OwncloudGuestShareType.php#L69-L73

Question is, since we don't use it anywhere and that since the guests app is creating users share instead of guests shares, what do we do with those?
cc @rullzer @nickvergessen @blizzz

_Originally posted by @skjnldsv in https://github.com/nextcloud/server/pull/16673#issuecomment-537977048_

**Comment by blizzz** [comment]
cc @icewind1991

**Comment by skjnldsv** [comment]
Ping

**Comment by skjnldsv** [comment]
cc @MorrisJobke @rullzer

**Comment by MorrisJobke** [comment]
I guess this is there because back then we didn't had email shares, right? So we would need to migrate existing guest shares to email shares again and then we can drop this?

**Comment by skjnldsv** [comment]
The question is, is there any old guest shares around?

**Comment by MorrisJobke** [comment]
> The question is, is there any old guest shares around?

One can never know, because there are thousands of instances out there.

**Comment by skjnldsv** [comment]
If so, the guest app isn't handling it, so if there are any, I don't think they work tbh

**Comment by MorrisJobke** [comment]
> If so, the guest app isn't handling it, so if there are any, I don't think they work tbh

Then we can also remove it here. But what about the migration? Should we then not migrate at all and leave it with email? Does it work this way? Are those shares then correctly transferred to Nextcloud?
