### ISSUE TITLE
NC17 | Mixed authentication | Direct Login and SAML

### ISSUE THREAD

**Issue by tpimpao** [nextcloud/server#17391]
Fresh installation using Nextcloud FPM Docker images. After starting containers and installing/configure user_saml app "Direct Login" stop working. 

### Steps to reproduce
1. Docker compose UP
2. Download and copy user_saml to app folder
3. Enable user_saml app
4. Configure user_saml app (i'm using Keycloack)
5. Login with SAML with sucess
6. Login with Direct Login fails without error and redirect to (http://mynextcloud.app.com:8080/apps/user_saml/saml/selectUserBackEnd?redirectUrl=)

### Expected behaviour
Mixed login (Direct Login and SAML) with success. 

### Actual behaviour
SAML login with sucess, Direct login fails

### Server configuration

Default Docker images configurations (Storage/Network)

**Web server:**
Nginx
**Database:**
MariaDB
**PHP version:**
Version: 7.3.10

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Docker HUB
**Signing status:**
<details>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.14.2
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.3
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - piwik: 0.5.3
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - registration: 0.4.7
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - user_saml: 2.4.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "sbox.grupocgd.net:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "overwrite.cli.url": "http:\/\/sbox.grupocgd.net:8080",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome 76.0.3809.132 or IE11

**Operating system:**
Windows 8.1

#### Web server error log
<details>
<summary>Web server error log</summary>
0.50.13.65 - - [04/Oct/2019:08:16:21 +0000] "POST /login HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:21 +0000] "GET /apps/user_saml/saml/selectUserBackEnd?redirectUrl= HTTP/1.1" 200 3636 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:21 +0000] "GET /css/core/68b4-c652-css-variables.css?v=db81cddf52fdb3c8ca1e4c859e214124-2e5553d9-0 HTTP/1.1" 200 499 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:21 +0000] "GET /css/core/68b4-c652-results.css?v=db81cddf52fdb3c8ca1e4c859e214124-2e5553d9-0 HTTP/1.1" 200 506 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /css/icons/icons-vars.css?v=1570113475 HTTP/1.1" 200 29452 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /apps/theming/styles?v=0 HTTP/1.1" 200 377 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /js/core/merged-template-prepend.js?v=2e5553d9-0 HTTP/1.1" 200 2950 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /css/core/68b4-c652-server.css?v=db81cddf52fdb3c8ca1e4c859e214124-2e5553d9-0 HTTP/1.1" 200 19225 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /core/js/dist/main.js.map HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /apps/accessibility/js/accessibility?v=0 HTTP/1.1" 200 65 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:22 +0000] "GET /apps/theming/js/theming?v=0 HTTP/1.1" 200 232 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /apps/piwik/js/tracking HTTP/1.1" 200 2734 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /login HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /svg/core/logo/logo?color=fff&v=1 HTTP/1.1" 200 194 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /apps/user_saml/saml/selectUserBackEnd?redirectUrl= HTTP/1.1" 200 3634 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /cron.php HTTP/1.1" 200 51 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /core/js/dist/share_backend.js.map HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /apps/files_videoplayer/js/main.js.map HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /login HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:23 +0000] "GET /login HTTP/1.1" 302 5 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:24 +0000] "GET /apps/user_saml/saml/selectUserBackEnd?redirectUrl= HTTP/1.1" 200 3638 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"
10.50.13.65 - - [04/Oct/2019:08:16:24 +0000] "GET /apps/user_saml/saml/selectUserBackEnd?redirectUrl= HTTP/1.1" 200 3627 "-" "Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36" "-"

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"Rtu2zaiuPsKRBzzJ9eLC","level":0,"time":"2019-10-04T08:14:45+00:00","remoteAddr":"10.50.13.65","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 10","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36","version":"17.0.0.9"}
{"reqId":"Rtu2zaiuPsKRBzzJ9eLC","level":0,"time":"2019-10-04T08:14:45+00:00","remoteAddr":"10.50.13.65","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\Files\\BackgroundJob\\CleanupFileLocks job with ID 10 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36","version":"17.0.0.9"}
{"reqId":"tl9CNIbx6dJ4RDFjDwfm","level":0,"time":"2019-10-04T08:14:57+00:00","remoteAddr":"10.50.13.65","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Run OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 11","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36","version":"17.0.0.9"}
{"reqId":"tl9CNIbx6dJ4RDFjDwfm","level":0,"time":"2019-10-04T08:14:57+00:00","remoteAddr":"10.50.13.65","user":"--","app":"DeleteOrphanedSharesJob","method":"GET","url":"\/cron.php","message":"0 orphaned share(s) deleted","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36","version":"17.0.0.9"}
{"reqId":"tl9CNIbx6dJ4RDFjDwfm","level":0,"time":"2019-10-04T08:14:57+00:00","remoteAddr":"10.50.13.65","user":"--","app":"cron","method":"GET","url":"\/cron.php","message":"Finished OCA\\Files_Sharing\\DeleteOrphanedSharesJob job with ID 11 in 0 seconds","userAgent":"Mozilla\/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/76.0.3809.132 Safari\/537.36","version":"17.0.0.9"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Chrome/Console Output
JQMIGRATE: Migrate is installed, version 1.4.1
main.js?v=2e5553d9-0:763 Could not find initial state loginErrors of core
main.js?v=2e5553d9-0:763 Could not find initial state loginMessages of core
main.js?v=2e5553d9-0:763 Could not find initial state loginRedirectUrl of core
main.js?v=2e5553d9-0:763 Could not find initial state resetPasswordTarget of core
main.js?v=2e5553d9-0:763 Could not find initial state resetPasswordUser of core
</details>

**Comment by tpimpao** [comment]
Hi,
More info added.

Thanks,
TP

**Comment by jurgenhaas** [comment]
I'm having a similar error where the redirect after direct login form submission gores to the external SAML login service. The NC log also shows this:

```
{"reqId":"MiwEV5TKOY4Kyb9AOc47","level":3,"time":"2019-10-04T01:10:31+00:00","remoteAddr":"2a01:4f8:120:93d3::2","user":"--","app":"jsresourceloader","method":"GET","ur
l":"\/index.php\/login?direct=1","message":"Could not find resource js\/config.js to load","userAgent":"--","version":"17.0.0.9"}
```

Not sure which component is missing the config.js file, it is not shown in the log unfortunately.

**Comment by flighter18** [comment]
Hi @kesselb 

i have exactly the same problem. My browserlogs are:
```
Navigated to https://share.bl.ch/index.php/login?redirect_url=&direct=1
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
initialstate.js:31 Could not find initial state loginErrors of core
initialstate.js:31 Could not find initial state loginMessages of core
initialstate.js:31 Could not find initial state loginRedirectUrl of core
initialstate.js:31 Could not find initial state resetPasswordTarget of core
initialstate.js:31 Could not find initial state resetPasswordUser of core
```
I've tested it on a second nextcloud installation. Same problem on this installation. 
As soon you enable the SSO/SAML APP the direct login doesn't work anymore. 
But if you disable the app again the direct login works as expected., 
So I think it is a bug.

**Comment by kesselb** [comment]
Still an issue? https://github.com/nextcloud/server/issues/17487 seems to be closed.
