### ISSUE TITLE
MinIO S3 Patch Issue

### ISSUE THREAD

**Issue by nagdevAmruthnath** [nextcloud/server#17394]
## Background
There was MinIO directory sync issue and a patch was provided to solve it. 

## Problem
The following https://github.com/nextcloud/server/issues/9808#issuecomment-463721101 gives error. There seems to be an issue with the patch or consecutive commits.
`error: unrecognized input`

## Reproducable

```
>root@nextcloud:/var/www/html# curl -L  https://github.com/nextcloud/server/compare/bugfix/6954/scan-external-s3.patch -o /tmp/scan-external-s3.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  273k    0  273k    0     0   507k      0 --:--:-- --:--:-- --:--:--  507k

>root@nextcloud:/var/www/html# git apply /tmp/scan-external-s3.patch 
error: unrecognized input

```

## Environment
Running this as docker container pulled from image `nextcloud:17.0.0RC2`

**Comment by kesselb** [comment]
The branch does not exist anymore. You can grab the patch from: https://github.com/nextcloud/server/pull/14913

**Comment by nagdevAmruthnath** [comment]
> The branch does not exist anymore. You can grab the patch from: #14913

I used the patch from there and it did not work. 

```
root@test# curl -O https://github.com/nextcloud/server/compare/bugfix/14913/scan-external-s3.patch | git apply -
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  273k    0  273k    0     0   467k      0 --:--:-- --:--:-- --:--:--  466k
error: unrecognized input
root@test#
```

**Comment by kesselb** [comment]
https://patch-diff.githubusercontent.com/raw/nextcloud/server/pull/14913.patch
