### ISSUE TITLE
http error 503 share folder hd usb

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#17407]
I shared a folder on an external usb 3.0 hd and gave permission to download and change to 3 users, an admin and 2 user, yet only admin can download it, while to the 2 users while seeing folder and files when they tend to download via web receive error http 503. I wonder if I should also enter them as authorized in the main home or just have them declared among the users in the external archiving menu

**Comment by kesselb** [comment]
> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

**Comment by tigernero79** [comment]
Ok thanks
