### ISSUE TITLE
Installation w/ Postgresql 11 stuck w/ only table "oc_migrations" being created

### ISSUE THREAD

**Issue by haozhou** [nextcloud/server#17401]
### Steps to reproduce
1. Install nextcloud using docker 
docker run -d --name nextcloud -p 8080:80  -e "POSTGRES_DB=nextcloud" -e "POSTGRES_USER=nextcloud" -e "POSTGRES_PASSWORD=somepassword" -e "POSTGRES_HOST=192.168.1.2" -v /mnt/data:/var/www/html/data  nextcloud:latest

2. Open http://someip:8080
3. Enter admin username and password

### Expected behaviour
Installation complete

### Actual behaviour
Installation stucks. If I check Postgresql db, only one table "oc_migrations" is created and no data being inserted.

### Server configuration

**Operating system**:
Docker running on RancherOS 1.5.4
Postgresql running on FreeBSD 12.0-p10

**Comment by kesselb** [comment]
Something in the logs?

**Comment by haozhou** [comment]
I don't see any errors from the log while installation is going on.

After a while, it prints following errors on web page/

`Error while trying to create admin user: An exception occurred while executing 'SELECT a.attnum, quote_ident(a.attname) AS field, t.typname AS type, format_type(a.atttypid, a.atttypmod) AS complete_type, (SELECT tc.collcollate FROM pg_catalog.pg_collation tc WHERE tc.oid = a.attcollation) AS collation, (SELECT t1.typname FROM pg_catalog.pg_type t1 WHERE t1.oid = t.typbasetype) AS domain_type, (SELECT format_type(t2.typbasetype, t2.typtypmod) FROM pg_catalog.pg_type t2 WHERE t2.typtype = 'd' AND t2.oid = a.atttypid) AS domain_complete_type, a.attnotnull AS isnotnull, (SELECT 't' FROM pg_index WHERE c.oid = pg_index.indrelid AND pg_index.indkey[0] = a.attnum AND pg_index.indisprimary = 't' ) AS pri, (SELECT pg_get_expr(adbin, adrelid) FROM pg_attrdef WHERE c.oid = pg_attrdef.adrelid AND pg_attrdef.adnum=a.attnum ) AS default, (SELECT pg_description.description FROM pg_description WHERE pg_description.objoid = c.oid AND a.attnum = pg_description.objsubid ) AS comment FROM pg_attribute a, pg_class c, pg_type t, pg_namespace n WHERE n.nspname NOT IN ('pg_catalog', 'information_schema', 'pg_toast') AND c.relname = 'nc_migrations' AND n.nspname = ANY(string_to_array((select replace(replace(setting,'"$user"',user),' ','') from pg_catalog.pg_settings where name = 'search_path'),',')) AND a.attnum > 0 AND a.attrelid = c.oid AND a.atttypid = t.oid AND n.oid = c.relnamespace ORDER BY a.attnum': SQLSTATE[HY000]: General error: 7 could not receive data from server: Connection timed out `

**Comment by haozhou** [comment]
the connection between docker container and postgresql db has no problem since table `oc_migrations` was created successfully by the installator

**Comment by haozhou** [comment]
If I copy same query to pgAdmin4, it works fine.

**Comment by haozhou** [comment]
I experienced the same issue in 20.0.2.2.

**Comment by haozhou** [comment]
The same issue can be reproduced in 20.0.2.2
