### ISSUE TITLE
Update issue, now Stuck in Maintenece Mode.  InvalidArgumentException: RegexIterator::__construct(): JIT compilation failed: no more memory

### ISSUE THREAD

**Issue by PuraVlda** [nextcloud/server#17412]
I was updating my server to 16.0.5 and followed the instructions for manual upgrade below:

Manually upgrading is also an option for users on shared hosting; download and unpack the Nextcloud tarball to your PC. Delete your existing Nextcloud files, except data/ and config/ files, on your hosting account. Then transfer the new Nextcloud files to your hosting account, again preserving your existing data/ and config/ files.

I am on a Mac and went to my Server Folder where all of these files are located.  I moved all files from download except the two folders above mentioned.

Went to my server address and got this:

<img width="494" alt="Screen Shot 2019-10-04 at 2 52 00 PM" src="https://user-images.githubusercontent.com/51298667/66232295-89b09c00-e6b6-11e9-8893-9985a8b06a2c.png">

When I clicked to upgrade this is what I got:

<img width="458" alt="Screen Shot 2019-10-04 at 2 52 34 PM" src="https://user-images.githubusercontent.com/51298667/66232337-9d5c0280-e6b6-11e9-9d5a-27d193666037.png">

I am fairly new to all of this, not sure what I did wrong if anything.

Thanks.

**Comment by kesselb** [comment]
Try [https://github.com/composer/composer/issues/7836](https://bit.ly/2Oko2qn)?

**Comment by kesselb** [comment]
If you want to report a bug please use https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE/Bug_report.md the next time. It's not possible to triage issues without. 


> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

**Comment by PuraVlda** [comment]
Sorry @kesselb but thank you for the help.  Got it fixed using your recommendation:

https://github.com/composer/composer/issues/7836

Added pcre.jit= 0 to the php.ini file and all worked.
