### ISSUE TITLE
Can't login to my admin user since the latest update.

### ISSUE THREAD

**Issue by CryptoSiD** [nextcloud/server#17426]
Hi, Im having an issue with an account. When im doing a files:scan with occ this is what im getting: http://dpaste.com/13GZK8G

I also tried "maintenance:repair" but it's not resolving the issue unfortunately

This is what I'm getting whenr unning "occ user:info SiD" http://dpaste.com/3V0F1FZ

Any help appreciated. Thank you

**Comment by CryptoSiD** [comment]
The issue happens as soon as a user is in the group admin.

I also tried to add a user to the admin group using occ and I get an error.

root@CryptoSiD:/var/www/nextcloud# sudo -u www-data php occ group:adduser admin Backup

In AbstractMySQLDriver.php line 60:
                                                                                                                        
  An exception occurred while executing 'SELECT `displayname` FROM `oc_groups` WHERE `gid` = ?' with params ["admin"]:  
                                                                                                                        
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'displayname' in 'field list'                                  
                                                                                                                        

In PDOStatement.php line 119:
                                                                                        
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'displayname' in 'field list'  
                                                                                        

In PDOStatement.php line 117:
                                                                                        
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'displayname' in 'field list'  
                                                                                        

group:adduser <group> <user>

**Comment by kesselb** [comment]
[Issue Template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)?

Probably missing a migration: https://github.com/nextcloud/server/pull/17221

**Comment by CryptoSiD** [comment]
Steps to reproduce
Expected behaviour
Tell us what should happen

Actual behaviour
Tell us what happens instead

Server configuration
Operating system: Ubuntu 19.04

Web server: Nginx 1.16.1

Database:  MariaDB 10.4

PHP version: 7.3.8

Nextcloud version: 18.0.0 Alpha


If I try to login to NextCloud with an admin user I get an internal error. It won't work on the web nor with the Nextcloud client.


Could you please give me more detail about the "migration" @kesselb 

I updated my NextCloud installation daily with "git pull" so I don't understand why the fix hasn't been applied to my NextCloud?

**Comment by kesselb** [comment]
Migrations are executed on upgrade from 17 to 18.
