### ISSUE TITLE
Anonymous upload shows login window

### ISSUE THREAD

**Issue by ugokanain** [nextcloud/server#17436]
Been trying to set up a nextcloud instance, but can't get it to share a folder for anonymous uploads without requesting the login credentials. 

Running version 17. In the share link I have "file drop (upload only)" and "hide download". In the sharing settings I have "allow users to share via link:allow public uploads"

Tried several different settings but haven't been able to get away from the login window. Even removed the password requirements at the share link and the settings (sharing)

Suspicious login showed a login, but couldn't find much more from the log 

Running PHP Version: 7.1.32, mysql 5.7.27 and version 17.0.0.9 of nextcloud

**Comment by kesselb** [comment]
> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

Please ask such questions at https://help.nextcloud.com the next time. For reporting issues we need the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

Regarding you report: I tried it with the docker image and it worked so far. 

![image](https://user-images.githubusercontent.com/3902676/66311363-92031400-e90e-11e9-9775-87dd7e950aac.png)

![image](https://user-images.githubusercontent.com/3902676/66311452-ce367480-e90e-11e9-8c17-b8e4fb0e1080.png)

Are you able to reproduce it with https://try.nextcloud.com?

**Comment by ugokanain** [comment]
I gave the trial a go before posting, but it is finicky and clunky. However had gotten to the point of dropping a document, but got **"Book2.txt" is not an allowed filetype** So I wasn't sure if it had succeeded or not, since not sure if the filters happen before. 

Will post at the forum
