### ISSUE TITLE
Oc_credentials security?

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#17439]
Hi,
Can i get informations about the algorithm used to hash password inside oc_credentials.

I think this is synchronous hash because nextcloud need it with external storage but i’m not sure ?

Best regards

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/c54a59d51eb924e77df6f6d2bb79ea466d169221/lib/private/Security/CredentialsManager.php#L53-L69
https://github.com/nextcloud/server/blob/be5c050acc9f9dffa6a28f04822f5f1fd7e73127/lib/private/Security/Crypto.php#L84-L103

**Comment by Schmuuu** [comment]
Hi @kesselb 

Just to let you know, I told him to better ask the developers regarding these questions. We in the Forum don't have much of the insights. Especially when it comes to questions why certain hash functions have been chosen, the broader community is missing the information I think.

**Comment by kesselb** [comment]
> told him to better ask the developers regarding these questions

Seems valid. Do you think the answer is sufficient? We can still ping some of the paid engineers. But the question is not specific.

**Comment by Schmuuu** [comment]
Thanks :)

Well, I'm not sure; @tanguy-opendsi does this answer your question? 
The comment seems to be descriptive: "Encrypts a value and adds an HMAC (Encrypt-Then-MAC)"

And the DB table oc_credentials seems to save a value consisting of 
`ciphertext|iv|hmac`

where "iv" seems to be a random number based on the length of an string. I don't understand what iv could mean or what ivLength is about. But maybe you understand that.
Please let us know what your questions was aiming at and where further clarification is required.

**Comment by kesselb** [comment]
cc @nextcloud/security :ping_pong:

**Comment by LukasReschke** [comment]
IV = Initialization Vector, which is required as this is using AES in CBC mode.

https://en.wikipedia.org/wiki/Initialization_vector has some more details.

**Comment by tanguy-opendsi** [comment]
@LukasReschke  that mean HMAC use AES?

**Comment by LukasReschke** [comment]
The HMAC is there to provide integrity. AES CBC alone doesn’t provide that.

The answer at https://security.stackexchange.com/questions/63132/when-to-use-hmac-alongside-aes is describing this quite well.

**Comment by LukasReschke** [comment]
I guess it would be good if you could rephrase your original question so that we can give a better answer :-)

What are your concerns? What do you want to protect against?

**Comment by tanguy-opendsi** [comment]
@LukasReschke 
Ok :) 
My question is : 
How work the mechanism when you use external storage? 
Nextcloud have to store and decrypt the password to use external storage properly ? 
If yes, what is the strength of your code (Using salt, what algorithm ect..)
Can you describe the mechanism ?

**Comment by olivluca** [comment]
Isn't it futile to encrypt the password, considered that if an attacker compromises the system he can easily obtain the secret?
I'd much prefer for the password **not** to be stored if there is no need for them, yet they are even if I have no external storage configured with stored credentials.

**Comment by kesselb** [comment]
@olivluca https://github.com/nextcloud/server/pull/21037
