### ISSUE TITLE
Safari iOS - Add to home screen uses screenshot for app icon

### ISSUE THREAD

**Issue by jdmarshall90** [nextcloud/server#17435]
In Safari, when I go to `mynextcloudsubdomain.myhome.lan` and add the web app to my home screen, it uses the Nextcloud icon, as expected.

But when I go to `mynextcloudsubdomain.local`, the icon is a screenshot.

Client: iPhone X, Safari, iOS 13.1.2
Server: Raspberry Pi 4th gen, Raspbian OS, Nextcloud v17.0.0 Stable

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
