### ISSUE TITLE
This is a bug about the nextcloud date translation issue.

### ISSUE THREAD

**Issue by z536797212** [nextcloud/server#17430]
### Steps to reproduce
Modify the language of Nextcloud to any language other than English (eg Chinese).

### Expected behaviour
All dates in Nextcloud should be translated into the corresponding language. For example, if I change the language to Chinese, the modified date of the stored files in Nextcloud should be Chinese date.

### Actual behaviour
The date is not correctly translated into the corresponding language format and is still in English.

### Server configuration

**Operating system**:
Centos 7
**Web server:**
Nginx
**Database:**
Mysql
**PHP version:**
php7.2
**Nextcloud version:** (see Nextcloud admin page)
17.0.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
Nextcloud official website(www.nextcloud.com)
**Signing status:**
No signature
**List of activated apps:**
default
**Nextcloud configuration:**
default
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by z536797212** [comment]
I found that modifying the ‘p.a.locale(c.a.getLocale())’ in ‘core/js/dist/main.js’ to the 'p.a.locale(c.a.getLanguage())' field can debug this bug. However, in the Nextcloud page, this bug still exists in Settings->Personal->Security->Devices & sessions->Last activity.

**Comment by kesselb** [comment]
Ref https://github.com/nextcloud/server/pull/14784
