### ISSUE TITLE
Security & setup warnings nags about configured Apps directory

### ISSUE THREAD

**Issue by rblayzor** [nextcloud/server#17446]
### Steps to reproduce
1. NextCloud 17
2. Create a secondary Apps path
3. Add path to config.php

### Expected behaviour
Unknown, but "Security & setup warnings" should recognize configured Apps paths.

### Actual behaviour
Security & setup warnings nags about "Some files have not passed the integrity check...". Even though the Apps path is configured in config.php. NextCloud 16 did not exhibit this issue.

### Server configuration

**Operating system**:
FreeBSD 11.2

**Web server:**
NGINX

**Database:**
PostgresSQL 10.10

**PHP version:**
PHP 7.3.x

**Nextcloud version:** (see Nextcloud admin page)
17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from NextCloud 16.0.4

**Where did you install Nextcloud from:**
FreeBSD ports

**Signing status:**
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- apps-pkg/notifications/js/notifications.js
		- apps-pkg/notifications/js/notifications.js.map
		- apps-pkg/notifications/l10n/gl.json
		- apps-pkg/notifications/l10n/mn.json
		- apps-pkg/notifications/l10n/ca.js
		- apps-pkg/notifications/l10n/es_PY.json
		- apps-pkg/notifications/l10n/da.js
	

config.php (parts):

$CONFIG = array (
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/opt/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 =>
    array (
      'path' => '/opt/nextcloud/apps-pkg',
      'url' => '/apps-pkg',
      'writable' => false,
    ),
  ),

**Comment by kesselb** [comment]
Has that been fixed by an update?
