### ISSUE TITLE
Replacing the master key

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#1744]
Hi,

This is a feature request to add a way to replace the master key in Nextcloud. This would be useful for example in case the master key had been compromised and needs to be replaced asap. Or the key might be replaced on a regular basis as a security measure (scheduled downtime until all files are re-encrypted).

This had been originally requested in the ownCloud issue [#21434](https://github.com/owncloud/core/issues/21434), but as it is rotting in the backlog there and we switched to Nextcloud, it would be nice to actually see this feature here.

I copied an old comment from @schiessle which appears to be still valid:

> [..]the master key is encrypted with the secret stored in config.php. You can't change this secret easily because it is also used in other places. So if we want to be able to replace the master key with a new one and also want a new password we need to introduce a new config.php option to store the master key password. If it is set we use this password, if not we fall back to the "secret" for backward compatibility.
> 
> The hard part of replacing the master key is not to generate a new one and set a new password somehow but to re-encrypt all files with the new key! Therefore we would need a occ call similar to "encrypt-/decrypt-all" and some extended logic to place a "read-key" and a "write-key" in the session. By default this would be the same keys. But in case of a "change master key call" we could add the old key as "read-key" and the new key as "write-key" and then read all existing files and writing them to new ones. So this involved quite some work as you can see if you look at the encrypt-all and decrypt-all commands.

**Comment by hodyroff** [comment]
This was implemented by ownCloud with 10.0.4. It is NOT "rotting in the backlog".

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
