### ISSUE TITLE
Better version handling for apps

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#17465]
Apps have to specify what versions of Nextcloud they support. This makes for a very long wait when upgrading Nextcloud versions, until so authors have released a new version. 

```xml
<dependencies>
	<nextcloud min-version="12" max-version="16" />
</dependencies>
```

I think it would be better if apps could test for specific features supported be the running Nextcloud instance, so that they continue to work as long as those bits in the API are still there.

Of course maybe better would be that the API is more stable across versions. Perhaps NC10-19 are backwards compatible NC10 apps and NC 20-29 with all NC20 apps, etc. 

Not sure how to solve it. Just know that this is a continuing cat and dog race and it's pointless to keep up.

**Comment by szaimen** [comment]
Sry but there were already many discussions on this and it was decided that it is not feasible for the project to do this.
