### ISSUE TITLE
Updater does not preserve user-added certificates to ca-bundle.crt

### ISSUE THREAD

**Issue by flixman** [nextcloud/server#17468]
### Steps to reproduce
1. Add a custom certificate to resources/config/ca-bundle.crt
2. Update to a new nextcloud version

### Expected behaviour
Custom-added certificate should be added to the new ca-bundle.crt

### Actual behaviour
ca-bundle.crt is the one coming from the sources.

### Server configuration

**Operating system**: GNU/Linux Debian 10.1 (stable)

**Web server:** apache - 2.4.38

**Database:** MariaDB - 10.3

**PHP version:** 7.3.4-2

**Nextcloud version:** 16.0.5 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** older Nextcloud

**Where did you install Nextcloud from:** sources

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - accessibility: 1.2.0
  - bookmarks: 2.2.0
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - deck: 0.6.6
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_videoplayer: 1.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - news: 14.0.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - passman: 2.3.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - richdocuments: 3.4.2
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.3
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "asset-pipeline.enabled": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.kngnt.org"
        ],
        "apps_paths": [
            {
                "path": "\/srv\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_authfailip": true,
        "loglevel": 2,
        "logfile": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Berlin",
        "mail_smtpdebug": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "session_lifetime": 3600,
        "share_folder": "\/Shared",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "enable_previews": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox 70.0b

**Operating system:** GNU/Linux Arch

**Comment by kesselb** [comment]
`occ security:certificates:import` does not work for you?

**Comment by flixman** [comment]
Indeed, it does :o sorry, I did not know about this one. Where does this store the certificate? Will I have to run it after every update?

**Comment by kesselb** [comment]
> Will I have to run it after every update?

Don't think so

> Where does this store the certificate?

`appdata_$instanceId/files_external/rootcerts.crt`

>  I did not know about this one

Don't worry. There is no documentation about this feature :see_no_evil: (or I couldn't find it)
