### ISSUE TITLE
Client s/w installed, but attempts to connect to http://myserver:443 [FAIL]

### ISSUE THREAD

**Issue by JLE082** [nextcloud/server#17460]
Hello all,

I cannot figure out why, but both the Windows client and the Linux client (I cannot verify Mac) attempt to obtain a token from my own NextCloud server (docker instance behind an nginx/letsencrypt proxy) by generating a link like "http://my.nextcloud.server:443/login/etc/etc/etc.

Needs no further elaboration is needed to make clear that this fails.

When I manipulate the link (i.e. I stick 'https' at the front, OR I take out the :443 port so that nginx takes care of rewriting the URL to https) I can proceed to the next step. Sadly, the final page contains a button that shoots out a token - again via http://my.nextcloud.server:443 so I cannot authenticate my PC client.

Can anybody explain what to do about this? And why somebody thought it to be a good idea to put http traffic onto port 443? My webserver chokes on that!

Thanks, Jaap.

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/17/admin_manual/configuration_server/reverse_proxy_configuration.html#defining-trusted-proxies

Nginx forwards `X-Forwarded-Host` and `X-Forwarded-Proto` so nextcloud is able to generate the correct urls. But by default these headers are ignored if the ip of your reverse proxy is not specified in `trusted_proxies`. Solution: Add the ip of your reverse proxy to `trusted_proxies`.

**Comment by JLE082** [comment]
Dude, you put me on the right track. 😉 Thanks !!!


Even though this didn't exactly do the trick for me, I found the overwritehost and overwriteprotocol parameters that did.


Thanks again!

Jaap.
________________________________
Van: kesselb <notifications@github.com>
Verzonden: dinsdag 8 oktober 2019 12:15:33
Aan: nextcloud/server
CC: Lelie, Jaap (J.); Author
Onderwerp: Re: [nextcloud/server] Client s/w installed, but attempts to connect to http://myserver:443 [FAIL] (#17460)


https://docs.nextcloud.com/server/17/admin_manual/configuration_server/reverse_proxy_configuration.html#defining-trusted-proxies

Nginx forwards X-Forwarded-Host and X-Forwarded-Proto so nextcloud is able to generate the correct urls. But by default these headers are ignored if the ip of your reverse proxy is not specified in trusted_proxies. Solution: Add the ip of your reverse proxy to trusted_proxies.
