### ISSUE TITLE
Link to signup offered on shared link page

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#17478]
### Steps to reproduce
1. Create a shared link
2. Open that link in a non-logged-in browser

### Expected behaviour
Receipients should not see any links unrelated to the shared content.

### Actual behaviour
Shared pages read now "Get your own free account" ("Hole Dir Dein eigenes kostenloses Konto") at the bottom. That links to https://nextcloud.com/signup/ which is not about getting a free account anyway.

### Server configuration
**Nextcloud version:** 17.0.0.9
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install
**Where did you install Nextcloud from:** ZIP from Nextcloud website
**Signing status:** no errors
**List of activated apps:** many, but not relevant, as is the rest of the bug report template

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/12909
https://github.com/nextcloud/server/issues/11788
https://github.com/nextcloud/server/issues/11327
https://github.com/nextcloud/server/issues/11198

The config flag to turn it off does not work?

**Comment by nursoda** [comment]
Uh, I'm very sorry: I thought I had searched bugs properly. Obvioulsy I did not. You are right: Both [adding the config switch or issuing the OCC command](https://github.com/nextcloud/server/issues/11101#issuecomment-453740147) (leading to the same line in config.php) DO work fine. So I close the issue.

However, I would expect to find such command in the install guide or even disabled by default.
