### ISSUE TITLE
contact search: Avatar images doesn't show up

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#17483]
I don't see in the contact search the avatar photos. Only in the contact app

### Steps to reproduce
1. Search in the contact search (top bar) for a user which has assigned a photo
2. User showes up but without the image
3. Search for the same user in the contact app, the images shows. 

### Expected behaviour
The image should show up in the contact search (top bar), too

### Actual behaviour
In the contact search (top bar) is only a colored circle with the first letter of the name shown.

### Server configuration
Nextcloud 17

**Comment by viruslab1** [comment]
I have this trouble too

**Comment by skjnldsv** [comment]
I'd say fixed since we have it in the unified search now
![Uploading Capture d’écran_2020-11-07_23-55-52.png…]()
