### ISSUE TITLE
Nextcloud does not redirect to login page while open share link If user not logged in

### ISSUE THREAD

**Issue by rgalexey** [nextcloud/server#1748]
### Steps to reproduce
1. Enable notify by mail in case sharing folder.
2. Mail received by user with URL like that https://server/apps/files/?dir=Candidates
3. User click on URL to view files.

### Expected behaviour
Site opened in browser and redirects to login page and after success login to destination folder view.

### Actual behaviour
Getting error about :
>Forbidden
>You don't have permission to access /apps/files/ on this server.

### Server configuration
**Operating system**:
Centos 7
**Web server:**
Apache 2.4
**Database:**
Mysql
**PHP version:**
5.5
**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Comment by LukasReschke** [comment]
There seems to be some info missing in your report.

**Comment by rgalexey** [comment]
Yes. Just pushed post button by mistake before filled report.

**Comment by nickvergessen** [comment]
Works quite fine here for both emails:
* user specific emails use `index.php/f/23`
* public link emails use `index.php/s/7nvpPwDMb42ueOR`

**Comment by rgalexey** [comment]
You are referring to share URL.
My request is about URL mentioned in the mail when you have shared folder with user and checked "notify by email". As result Nextcloud generate mail to the user.

```
Hey there,

just letting you know that User shared Candidates with you.
View it!

Cheers! 
```
Where "View it!" is link https://server/apps/files/?dir=Candidates

**Comment by nickvergessen** [comment]
On Nextcloud 10 the link is `index.php/f/23` and that one works fine for me. Also it redirects correctly to the file after login.

**Comment by rgalexey** [comment]
Weird
Testing right now and not getting same thing.
How come I've got this kind of URl have no idea now. That was folder share with group.
Now getting URL like index.php/f/23

**Comment by rgalexey** [comment]
Sorry. 
It appears that bad URL was generated when there was Nextcloud 9.0.53.
But server has been upgraded since couple hours to 10.0.1

**Comment by y0va** [comment]
For me this still does not work in Nextcloud 13.0.1 with Onlyoffice.

While trying to access eg. https://mycloud.io/apps/onlyoffice/3097 when not logged in, I get `File not found`. Might also be OnlyOffice upstream.

**Comment by kiksmon21** [comment]
I'm having almost the same problem but instead of getting the mentioned error, mine was downloading instead of redirecting to login page.
Does anyone know the workaround for this?
BTW. Here's my build:

Operating system:
OpenSUSE Leap 15.0
Web server:
Apache 2.4
Database:
MariaDB
PHP version:
7
Nextcloud version: (see Nextcloud admin page)
13
