### ISSUE TITLE
Reminders (Tasks) are not shown in Mac OS 10.15 Catalina

### ISSUE THREAD

**Issue by pl4te** [nextcloud/server#17491]
As some might know, there was a big change of the reminders app with iOS 13 and Mac OS 10.15. I'm using nextcloud 17 and use contact, calendar and task app for many years to sync those with my iOS and Mac OS devices via CalDav and CardDav. This usually works well.
Also the upgrade to iOS 13 was no problem. The sync worked seamlessly on the iPhone after upgrading.

Now I upgraded to Mac OS 10.15 (or making a clean reinstall to be precise). I set-up my CalDav and CardDav accounts as usual (and as described here: https://docs.nextcloud.com/server/17/user_manual/pim/sync_osx.html) and everything works fine except there are no tasks shown in the reminder app.
Sync of calendar and contacts works fine as usual. Also the sync with all of them (including tasks) with the iOS device.
One strange thing: I nevertheless get a notification if a tasks is due. But the reminders app remains completely empty.

I think this has something to do with the changes Apple made on there reminders app. What I'm curious about, absolutely no problems with iOS 13 even they also brought the new reminders app to the phone.

Anyone else has the same problem?
Would be nice if somebody has an idea or the knowledge to do further research as I'm not an expert of the syncing in background.

Thanks in advance.

**Comment by kesselb** [comment]
As reference: https://github.com/nextcloud/server/issues/17190

**Comment by BernieO** [comment]
Looks like this is a certificate issue:
https://github.com/nextcloud/server/issues/17190#issuecomment-546915193

**Comment by pl4te** [comment]
Thanks for your comment. Is this also true for Mac OS Catalina? Does it work for you with Catalina?
Cause I'm also using a Let's Encrypt certificate. Still the issue that it works with iOS 13 and not with Mac OS Catalina. Even though it's the same Let's Encrypt certificate.

Greetings,

plate

**Comment by BernieO** [comment]
I don‘t use MacOS 10.15 Catalina myself, but a friend of mine does. And on his Computer Reminders do sync via caldav against Nextcloud.

**Comment by j-ed** [comment]
As already referenced, see https://github.com/nextcloud/server/issues/17190#issuecomment-546915193 for further details, especially:

https://support.busymac.com/help/112428-reminders-from-ios-13-macos-10-15-reminders-aren-t-syncing

**Comment by pl4te** [comment]
@BernieO 
Thanks for the information. That's interesting that it works in some cases.

@j-ed 
I don't really get the reference again. I read the link before. As I wrote I'm using a Let's Encrypt certificate which meets all the requirements stated at https://bob.gatsmas.de/articles/caldav-sync-erinnerungen-app-ios-13-und-macos-1015 .
Furthermore, for my understanding the certificate requirements are true for iOS 13 and Mac OS 10.15. But the sync on my iOS device works well. Nevertheless, I renewed my certificate few minutes ago. Nothing changed. Seems very strange.

Greetings,

pl4te

**Comment by pl4te** [comment]
Now I managed to get reminders on macOS Catalina as well. It turned out to be an issue with the domain-configuration. There was no well-known redirecting. 
See:
https://docs.nextcloud.com/server/17/admin_manual/issues/general_troubleshooting.html#service-discovery-label

So I can also confirm that CalDav works with the new generation of Reminders basically.
Another problem is that the sync does not work as expected. All changes made on iOS or in the Nextcloud-Interface are synced to the Mac. All changes made on the reminders app on macOS Catalina are not synced to the Nextcloud server.
But as this is another problem as stated in the initial post, I will close this one.

Thanks for your contribution.
