### ISSUE TITLE
amazon cloud hsm support 

### ISSUE THREAD

**Issue by cyber-goka** [nextcloud/server#17490]
Hello, 
In docs everywhere said it supports hsm, but I can't find any documentation about it, can you please tell me where to find it?

**Comment by kesselb** [comment]
>In docs everywhere said it supports hsm

Where do you have this information from?

**Comment by cyber-goka** [comment]
> > In docs everywhere said it supports hsm
> 
> Where do you have this information from?
https://nextcloud.com/endtoend/ 
https://github.com/nextcloud/end_to_end_encryption_rfc/blob/master/RFC.md#support-for-hsm

**Comment by cyber-goka** [comment]
Hey, anything?

**Comment by kesselb** [comment]
cc @nextcloud/security @jospoortvliet
