### ISSUE TITLE
Shortened URL

### ISSUE THREAD

**Issue by delete-exe** [nextcloud/server#17492]
**Is your feature request related to a problem? Please describe.**
When I send out public links of shared data these links are quite long due to my long domain name. At the end there's always _/index.php/abcdefghijklmnop_ attached, what makes the links even longer.
The link generated this way is giving away information, that are not necessary for the recipient to know.

**Describe the solution you'd like**
If NextCloud could generate a short version of that link,without any external service provider, this would be a great optinal feature.

**Describe alternatives you've considered**
The alternative is doing it just the way it goes today.

My best regards,
Delete.exe

**Comment by tflidd** [comment]
With pretty-URLs, you can at least get rid of the index.php:
https://docs.nextcloud.com/server/stable/admin_manual/installation/source_installation.html#pretty-urls

**Comment by wiswedel** [comment]
Does this help?
https://apps.nextcloud.com/apps/sharerenamer

**Comment by delete-exe** [comment]
Thanks for your suggestions. 
Both are working. Both are nice, but not exactly what I'm looking for, The URL itself should be shortened and disguised (on first view). 

_pretty-URL btw needs .htaccess content to be rewritable. That is - by security check within NextCloud - not correct and becomes a problem while updating. So it's funny that it is in the official docu._

**Comment by wiswedel** [comment]
> The URL itself should be shortened and disguised (on first view).

Sorry, that's not possible with Nextcloud at the moment. You'll have to pick a provider or another on-prem solution for that.

**Comment by punkyard** [comment]
Hi, is it possible to find a link editor that would offer a list of weblinks towards NC, and the edited/shorter version of it? Especially for links in Collectives (sharerenamer doesn't integrate Colelctives)
Thanks
