### ISSUE TITLE
User search in admin/groupadmin panel only on uid

### ISSUE THREAD

**Issue by hregnier** [nextcloud/server#1749]
My 30K users is imported from an old ldap, some of them have a random uid and I can search them only by their full name. But when an admin or a groupadmin search with the top bar searchbox, the search is only on uid. 

For a quick fix, i juste change in settings/Controller/UsersController.php
L:252 `$batch = $this->userManager->search($pattern, $limit, $offset);`
to
L:252 `$batch = $this->userManager->searchDisplayName($pattern, $limit, $offset);`

But im not pleased with it, because uid search can't be done. Is it possible to override all this process to make search on both criteria ?

**Comment by juliushaertl** [comment]
I like the idea, searching by users email would also be nice.

**Comment by blizzz** [comment]
@hregnier so you use the LDAP backend? https://docs.nextcloud.com/server/10/admin_manual/configuration_user/user_auth_ldap.html#directory-settings → "User Search Attributes"

**Comment by hregnier** [comment]
@blizzz no. I do not user LDAP Backend. By the way, if I understand the app, the user search attribute is useful for serching user in the LDAP, not in nextcloud. That's not what i want to do.

**Comment by MorrisJobke** [comment]
Fixed with #7169
