### ISSUE TITLE
oc_preferences: configvalue for configkey="lang" is set to "en" if the http-header "Accept-Language" is set to "de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3"

### ISSUE THREAD

**Issue by IeP4nieF** [nextcloud/server#17518]
### Steps to reproduce
1) create a new user
3) check value of configvalue where configkey='lang' in table oc_preferences
2) open the link in the mail to set a password
3) check value of configvalue where configkey='lang' in table oc_preferences

### Expected behaviour
After creating the new user configvalue is set correct to de_DE. firefox 60.9.0 sets the http-header "Accept-Language" to "de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3". So the expected behavior is, that the configvalue is set to "de_DE" or not set at all, after opening the link to set the first passwort in the email.

### Actual behaviour
After opening the link the configvalue='en' is set.

## Server configuration detail

**Operating system:** Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** pgsql PostgreSQL 11.5 (Debian 11.5-1+deb10u1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

**PHP version:** 

7.3.9-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** from https://nextcloud.com/install/

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.6
 - dav: 1.9.2
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.3
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - support: 1.0.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        0 => "localhost",
        1 => "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "16.0.5.1",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "log_rotate_size": 104857600,
    "updater.release.channel": "production",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "share_folder": "\/geteilt",
    "default_language": "de_DE",
    "default_locale": "de_DE"
}
```
</details>

**Are you using external storage, if yes which one:** no external storage

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** Debian 9

## Logs

<details><summary>Web server error log</summary>

```
no errors
```
</details>

<details><summary>Nextcloud log</summary>

```
nothing there
```
</details>

<details><summary>Browser log</summary>

don't have this
</details>

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/de6940352a2f708376219a89ec84a8e6d25ca59e/lib/private/L10N/Factory.php#L190-L195

The value is probably set at the above place. 

https://github.com/nextcloud/server/blob/de6940352a2f708376219a89ec84a8e6d25ca59e/tests/lib/L10N/FactoryTest.php#L389

Added the given http-header to the unit test and the result is de.

I'm not able to reproduce this issue. I tried different ways:

1) Changing Accept-Language with a browser addon
2) Set language via ui on user creation
3) Change the language of the admin user.

If the value "de_DE" is written to oc_preferences it stays like this after password reset. Probably already fixed with Nextcloud 17.
