### ISSUE TITLE
Mimetype detection for favorited files is not working

### ISSUE THREAD

**Issue by kugiigi** [nextcloud/server#17513]
### Steps to reproduce
1. Set a file as favorite. i.e. kdbx file
2. Run `files:scan <username>` as admin.
3. Go to the original file's location and click on the file.
4. Go to favorites and click on the file you add as favorite.

### Expected behaviour
The file should be detected or open appropriately depending on its file type.
i.e. kdbx files should open on keeweb.

### Actual behaviour
Clicking on the file in the original path opens the file correctly i.e. opens on keeweb
Clicking on the file in Favorites downloads the file.

### Server configuration

**Operating system**: Unknown

**Web server:** Unknown

**Database:** MySQL

**PHP version:** 7.2.23

**Nextcloud version:** 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Y

**Where did you install Nextcloud from:** Owncube hosting

**Comment by szaimen** [comment]
Hi, this needs to get implemented in the keeweb app. Thus please report it to the maintainer of that app in its repository: https://github.com/jhass/nextcloud-keeweb
