### ISSUE TITLE
External Nextcloud "Modified" date keeps updating randomly

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#17519]
I have linked another NC instance via the "External storages" function and keep noticing how the "Modified" date randomly updates to "Seconds ago" even though I haven't touched it in weeks. When I open the content of the external NC, the "Modified" data is correct. In fact, the "Modified" updates when you only open the folder of the external NC and don't write anything.

Reproduce:

1. link an external NC cloud using the "External storages"
2. Keep looking out for the "Modified date". If will randomly update. You can try opening the external NC folder which will also update the "Modified" date.

**Comment by kesselb** [comment]
Please use the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) to report a bug.
