### ISSUE TITLE
Colored folders

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#17520]
As my NC is getting bigger and populated with more semi-useful folders, it's important for me to distinguish / highlight folders that I tend to open more often (or that hold more importance) than others. One of the ways is being able to color folders.

Reference: G Drive

![Screenshot_2](https://user-images.githubusercontent.com/36133540/66702061-ea615980-ecf2-11e9-8d15-09a278e64d71.png)

In light of this, I suggest that folders do not share the main theme color. By default, I suggest that folders have neutral color to them, if not changed to any other color by the user.

Reference: G Drive

![defreulat](https://user-images.githubusercontent.com/36133540/66702152-0285a880-ecf4-11e9-8011-64aef93f0a78.png)

If this is not endorsed, another idea is to add color labels to individual folders (and files!).

![color](https://user-images.githubusercontent.com/36133540/66702174-4082cc80-ecf4-11e9-8d6e-da38dedd1574.png)
(reference to this idea is mega.nz)

**Comment by kesselb** [comment]
Ref: https://github.com/nextcloud/server/issues/6778

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
