### ISSUE TITLE
Upgrade to 17.0.0 failed

### ISSUE THREAD

**Issue by goergel** [nextcloud/server#17532]
### Steps to reproduce
1. sudo -u http ./occ upgrade

### Expected behaviour
A successful Update

### Actual behaviour
It failed
```
Set log level to debug
Updating database schema
Updated database
UnexpectedValueException: The files of the app "files_rightclick" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Reset log level
```

### Server configuration

**Operating system**:
arch linux (manjaro)

**Web server:**
Server version: Apache/2.4.41 (Unix)
Server built:   Aug 13 2019 22:44:41

**Database:**
psql (PostgreSQL) 11.5

**PHP version:**
PHP 7.3.10

**Nextcloud version:** (see Nextcloud admin page)
17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Where did you install Nextcloud from:**
arch linux package

** Solution **
I found the cause: The directory `apps/files_rightclick/` contained another directory named `files_rightclick` once again.
I was able to resolve the problem by hand in three steps. 

1. `cp -r apps/files_rightclick/files_rightclick/* apps/files_rightclick/`
2. `sudo -u http ./occ upgrade`
3. In `config/config.php` set `maintenance` to `false`

**Comment by BeiNacht** [comment]
had the same issue, soultion worked for me also

**Comment by grondinm** [comment]
Same issue with upgrade to 17.0.1. Same fix also worked. Thank you.

**Comment by nuf0xx** [comment]
same issue upon upgrade but the `cp -r` solution did not work for me. 

The following did work though:

1. `mv apps/files_rightclick/ /some/other/place/ `
2. `sudo -u http ./occ upgrade`
3. `sudo -u http ./occ maintenance:mode --off`

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
