### ISSUE TITLE
Unified direct editing API

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#17533]
The goal of this is to provide a editing api for mobile/desktop clients to be implemented by any app as a server API. This should work similar to the current richdocuments implementation but should be easy to integrate in other apps like OnlyOffice and Text and have the general handling done by the server.

How it works at the moment in richdocuments:
- Richdocuments exposes a list of mimetypes that can be opened
- The client does an authenticated OCS request to get an editing link for a given file id, with a one-time token so the url can be opened without providing user authentication
- The client opens the url in a webview
  - Collabora creates a separate WOPI token for future file handling so the collabora server has access to the file
  - The one-time token is revoked meaning that the editing session can only be instantiated once.

The idea is to unify the token generation and endpoints into a server API, so mobile apps and the desktop client can just query one endpoint instead of requiring individual implementation for every app.

The following is a rough writeup of the architecture i have in mind:

## Apps can register a direct editor implementation

```php
interface IEditor {

	/**
	 * Return a unique identifier for the editor
	 *
	 * e.g. richdocuments
	 *
	 * @return string
	 */
	public function getId(): string;

	/**
	 * Return a readable name for the editor
	 *
	 * e.g. Collabora Online
	 *
	 * @return string
	 */
	public function getName(): string;

	/**
	 * A list of mimetypes that should open the editor by default
	 *
	 * @return array
	 */
	public function mimetypes(): array;

	/**
	 * A list of mimetypes that can be opened in the editor optionally
	 *
	 * @return array
	 */
	public function mimetypesOptional(): array;

	/**
	 * Return a list of file creation options to be presented to the user
	 *
	 * @return array of ICreateFromTemplate|ICreateEmpty
	 */
	public function creators(): array;

	/**
	 * Return if the view is able to securely view a file without downloading it to the browser
	 *
	 * @return bool
	 */
	public function isSecure(): bool;

	/**
	 * Return a template response for displaying the editor
	 *
	 * open can only be called once when the client requests 
	 * the editor with a one-time-use token
	 * For handling editing and later requests, editors need 
	 * to implement their own token handling and take care of invalidation
	 *
	 * This behavior is similar to the current direct editing 
	 * implementation in collabora where we generate a one-time 
	 * token and switch over to the regular wopi token for the 
	 * actual editing/saving process
	 *
	 * @return TemplateResponse
	 */
	public function open(): TemplateResponse;
}

```

### GET /core/direct/capabilities

The server exposes available editors and file creation options

```json
{
    "editors": {
        "richdocuments": {
            "name": "Collabora Online",
            "mimeDefault": [
                "application/office"
            ],
            "mimeOptional": [],
            "secureView": true
        },
        "onlyoffice": {
            "name": "OnlyOffice",
            "mimeDefault": [
                "application/office"
            ],
            "mimeOptional": [],
            "secureView": true
        },
        "text": {
            "name": "Nextcloud Text",
            "mimeDefault": [
                "text/markdown"
            ],
            "secureView": false
        }
    },
    "creators": [
        {
            "editor": "richdocuments",
            "type": "document",
            "filename": "New Document",
            "extension": "odt",
            "templates": true
        },
        {
            "editor": "richdocuments",
            "type": "spreadsheet",
            "filename": "New Spreadsheet",
            "extension": "ods",
            "templates": true
        },
        {
            "editor": "text",
            "type": "rich",
            "filename": "New text document",
            "extension": "md",
            "templates": false
        }
    ]
}

```

### GET /core/direct/templates/{editorId}/{creatorType}

Return a list of available templates with a unique identifier, preview and name. Creating a new file from the template is handled by the apps implementation.

### POST /core/direct/edit

A post request with a given fileId that returns the one-time editing URL

### POST /core/direct/create

Create a file (empty or from a provided template id) and returns the one-time editing URL

### GET /core/direct/open/{token}

Render the editor by calling the IEditor::open method and revoking the token afterwards

## Secure view

Besides mobile editing this can also be used to provide a more secure "hide download" functionality. For Collabora for example the direct editing endpoint can be used to show a file on shares without sending the actual file to the client.

cc @rullzer @tobiasKaminsky

**Comment by tobiasKaminsky** [comment]
Nice :tada:

**Comment by tobiasKaminsky** [comment]
Ping me when there is something to test/implement please :+1:

**Comment by rullzer** [comment]
Cool stuf fin general.

Some things to consider to extend the spec. Editing or creating a new document should probably include the editor. Just in case there are two editors that can handle the same files.

**Comment by ChristophWurst** [comment]
#17625 implements this, right?

**Comment by rullzer** [comment]
Yes
