### ISSUE TITLE
Fresh install 17.0.0.9: Web view does not display files

### ISSUE THREAD

**Issue by daniel-callejas-sevilla** [nextcloud/server#17534]
### Steps to reproduce
1. Fresh install of Nextcloud 17.0.0.9 on LAMP server
2. Initial log in as Admin at the installed URL
3. The web view for 'Files' opens by default

### Expected behaviour
Files (eg. the ones from the skeleton, for a fresh install, or else the files of the logged in user in general) should show up.

### Actual behaviour
Only section "recently changed files" appear. Browser console warning logged: "OC.MimeType is undefined". 

If I go into the console and manually type `OC.MimeType = {} ; OC.MimeType.getIconUrl = function(a){return;},` then files show up correctly at the next interaction with the window (provided it does not trigger a page reload).

Problem appears for any user (e.g. I have moved 45 GB of files into this fresh install, cannot browse any of them on the web interface unless I create the OC.MimeType js object manually on every browser session).

### Server configuration

**Operating system**: Debian 10 (Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64)

**Web server:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** MariaDB 10.3.17

**PHP version:** 7.3.9-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** nextcloud.com/install (downloaded the .targ.bz2)

**Signing status:**
<details>
<summary>Signing status</summary>
Array ( )
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.14.2
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.xxx:xxxx",
        "example.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "overwrite.cli.url": "https:\/\/example.com\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwritehost": "example.com",
    "overwriteprotocol": "https",
    "overwritewebroot": "\/"
}</details>

**Are you using external storage, if yes which one:** No (files_external is disabled)

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No (OC\User\Database)

### Client configuration
**Browser:** Repeatable with up-to-date Firefox, Chrome (example: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 )

**Operating system:** Repeatable under both Windows and Ubuntu

#### Web server error log
<details>
<summary>Web server error log</summary>

Cannot access right now. There are no 404 replies from web server. Will attach later if needed.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Cannot access right now. Will attach later if needed.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
oc_config is deprecated: use OC.config instead globals.js:26:15
OCA.Viewer initialized viewer.js:394:269
New search handler registered search.js:67:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
The select2 library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
The select2 library is deprecated! It will be removed in nextcloud 19. globals.js:26:15
Source map error: AbortError: The operation was aborted. 
Resource URL: https://example.com/apps/viewer/js/viewer.js?v=28804ace-8
Source Map URL: viewer.js.map
Source map error: AbortError: The operation was aborted. 
Resource URL: https://example.com/core/js/dist/main.js?v=28804ace-8
Source Map URL: main.js.map 2
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: OC.MimeType is undefined merged-index.js:5991:5
could not load recommendation preview 
error { target: img, isTrusted: true, srcElement: img, currentTarget: img, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
RecommendedFile.vue:97
could not load recommendation preview 
error { target: img, isTrusted: true, srcElement: img, currentTarget: img, eventPhase: 2, bubbles: false, cancelable: false, returnValue: true, defaultPrevented: false, composed: false, … }
RecommendedFile.vue:97

</details>

**Comment by daniel-callejas-sevilla** [comment]
![image](https://user-images.githubusercontent.com/10685659/66750831-cab26880-ee8d-11e9-939d-1e8337defbf4.png)
Notice the empty area below the 'Recent files' section.

**Comment by daniel-callejas-sevilla** [comment]
![image](https://user-images.githubusercontent.com/10685659/66751512-7ad4a100-ee8f-11e9-920b-3eda45d9bcdb.png)
After manually patching the OC.MimeType js object and clicking on 'Recent' then back on 'All files'.

**Comment by daniel-callejas-sevilla** [comment]
Following patch is a poor man's workaround that fixes the issue for the time being:

```
--- /original/core/templates/layout.user.php      2019-09-26 10:23:22.000000000 +0200
+++ core/templates/layout.user.php      2019-10-14 22:19:57.962778379 +0200
@@ -24,6 +24,10 @@
                <link rel="manifest" href="<?php print_unescaped(image_path($_['appid'], 'manifest.json')); ?>">
                <?php emit_css_loading_tags($_); ?>
                <?php emit_script_loading_tags($_); ?>
+               <!-- Workaround for <https://github.com/nextcloud/server/issues/17534> { -->
+               <?php emit_script_tag("/core/js/mimetype.js"); ?>
+               <?php emit_script_tag("/core/js/mimetypelist.js"); ?>
+               <!-- } -->
                <?php print_unescaped($_['headers']); ?>
        </head>
        <body id="<?php p($_['bodyid']);?>">
```

**Comment by FrankMaute** [comment]
Same thing here. If you click the Tile view, all files are being displayed. This is a real nasty bug. Hope you solve soon.

**Comment by mpigou** [comment]
I too observe the same behaviour. Here are my instance details:

## Server configuration detail

**Operating system:** FreeBSD 11.2-STABLE FreeBSD 11.2-STABLE #0 r325575+95cc58ca2a0(HEAD): Fri May 10 15:57:35 EDT 2019     root@mp20.tn.ixsystems.com:/freenas-releng/freenas/_BE/objs/freenas-releng/freenas/_BE/os/sys/FreeNAS.amd64 amd64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 8.0.17

**PHP version:** 

7.2.23
Modules loaded: Core, date, libxml, pcre, Reflection, SPL, hash, session, cgi-fcgi, standard, apcu, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, gmp, mysqlnd, iconv, imagick, intl, json, exif, mysqli, openssl, pcntl, PDO, posix, SimpleXML, sqlite3, xml, xmlwriter, zip, zlib, pdo_mysql, pdo_sqlite, xmlreader, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older Nextcloud

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - apporder: 0.8.0
 - calendar: 1.7.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - deck: 0.7.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.17.0
 - nextcloud_announcements: 1.6.0
 - notes: 3.0.3
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - scanner: 0.1.5
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.1
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - twofactor_nextcloud_notification: 2.1.1
 - twofactor_totp: 4.0.0
 - twofactor_u2f: 4.0.0
 - updatenotification: 1.7.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logtimezone": "UTC",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mysql.utf8mb4": true,
    "loglevel": 0,
    "theme": "",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "updater.release.channel": "stable",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0

**Operating system:** Ubuntu 18.04.3 (same issue on Windows 10)

## Logs

<details><summary>Browser log</summary>

TypeError: OC.MimeType is undefined
merged-index.js:5991:5
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
    VueJS 24
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888


</details>

**Comment by mpigou** [comment]
For me, this issue does not occur anymore using the last release (17.0.1). Thanks!

**Comment by kesselb** [comment]
@daniel-callejas-sevilla @FrankMaute fixed for you too?

**Comment by FrankMaute** [comment]
The update of Talk did fix it.

**Comment by liamdennehy** [comment]
Upgrade from 16.0.8 -> 17.0.3, issue occurs. Talk (spreed) at latest version and also disabled, issue persists. Neither list nor grid views display any content. Clear browser of cache for entire site has no effect, so probably not stale js cache.

Error in the title is preceded by the following error from ``merged-template-prepend.js``:
```
TypeError: cannot declare global binding `initCore': property must be configurable or both writable and enumerable
```

**Comment by liamdennehy** [comment]
Created new issue for above comment in https://github.com/nextcloud/server/issues/19531 so as not to clutter this issue if they are unrelated.
