### ISSUE TITLE
incomplete NC 16 GUI translation

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#17544]
### Steps to reproduce
NC GUI user Personal info settings
1. select & ack. e.g. 'German (Förmlich/Sie)' as Language for the GUI and use this GUI somehow
2. afterwards select e.g. '**English (British-English)**' as Language for the GUI
3. ack. the change with your password if requested

The behaviour and presumably incomplete translation extends into the content of the b.m. marked sections 'Barrierefreiheit' i.e. 'Accessability' and 'Datenschutz' i.e. 'Privacy'.  This was oberved with Language 'English (British-English)' but not with Language 'English (US)' apparently.

The behaviour on Locale display of the day in week (e.g. 'Montag' instead of 'Monday') applies to both Languages 'English (British-English)' and  'English (US)'.

### Expected behaviour
The NC GUI should in completeness honor major the Language and minor the Locale as selected by user Personal info settings.

### Actual behaviour
**The NC GUI mixes some different Language content and/or shows incomplete translations.**

## Server configuration detail

**Operating system:** Linux 4.19.0-6-amd64 Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Webserver:** Apache (apache2handler) -- 2.4.38-3+deb10u1

**Database:** mysql 10.3.17

**PHP version:** 

7.3.9-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1, 16.0.4 - 16.0.4.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 15.0.11

**Where did you install Nextcloud from:** 
- 16.0.4 updated by GUI updater und `occ upgrade` on the commandline
- 16.0.5 updated manually acc. to https://docs.nextcloud.com/server/16/admin_manual/maintenance/manual_upgrade.html

<details><summary>Signing status</summary>

_n.a._

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - apporder: 0.8.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.6
 - dav: 1.9.2
 - external: 3.3.1
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.3
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.3
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - richdocuments: 3.4.2
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - spreed
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "debug": false,
    "trusted_domains": [
        "### manually REMOVED SENSITIVE VALUE###",
        "### manually REMOVED SENSITIVE VALUE###"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y-m-d H:i:s",
    "log_rotate_size": 52428800,
    "loglevel": 2,
    "activity_expire_days": 190,
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "### manually REMOVED SENSITIVE VALUE###",
    "theme": "",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "updater.release.channel": "production",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Macintosh; Intel Mac OS X 10.12; rv:60.0) Gecko/20100101 Firefox/60.0, Firefox on Linux

**Operating system:** 

- Mac OS X / macOS 10.12.6 Sierra & 10.14.6 Mojave
- Linux 4.19.0-6-amd64 Debian Buster (Netbook client with Xfce Desktop)

## Logs

<details><summary>Web server error log</summary>

```
n.a.
```
</details>

<details><summary>Nextcloud log</summary>

```
n.a.
```
</details>

<details><summary>Browser log</summary>

```
n.a.
```

</details>

## Screenshot

The GUI screenshot was viewed by a _Firefox 60.9.0esr (64-Bit) Mac OS X_ browser.

**Deviations** from the expected english text of the GUI are **marked with red colour** in the screenshot below

![screenshot_GUI_2019-10-11a](https://user-images.githubusercontent.com/31193257/66656086-98aac780-ec3d-11e9-8f86-6a59f712f423.png)

This report was produced by help of the [issuetemplate: 0.5.0 app](https://apps.nextcloud.com/apps/issuetemplate).

**Comment by kesselb** [comment]
> The behaviour on Locale display of the day in week (e.g. 'Montag' instead of 'Monday') applies to both Languages 'English (British-English)' and 'English (US)'.

Probably fixed by https://github.com/nextcloud/server/pull/17673

**Comment by skjnldsv** [comment]
yep
