### ISSUE TITLE
why 

### ISSUE THREAD

**Issue by ToughLama** [nextcloud/server#17546]
my NC17  The mobile phone cannot display properly

![image](https://user-images.githubusercontent.com/8759269/66831350-0599c680-ef8a-11e9-9586-a51ff9c2537b.png)

**Comment by juliushaertl** [comment]
Please fill out the issue template and provide a proper title for your issue.

**Comment by kesselb** [comment]
Looks similar to https://github.com/nextcloud/server/issues/17364

**Comment by ToughLama** [comment]
> Looks similar to #17364

this bug is not fix, always thank you

**Comment by juliushaertl** [comment]
Possible fix in https://github.com/nextcloud/server/issues/17364 

Let's close this in favor of #17364
