### ISSUE TITLE
NC17: root directory inaccessible due to unavailable federated share - "This directory is not available..."

### ISSUE THREAD

**Issue by Schmuuu** [nextcloud/server#17552]
### Steps to reproduce
1. Accept a federated share from another Nextcloud server
2. cut connection to the federated server (shutdown that server)
3. open files app on local server and notice the error message popping up

### Expected behaviour
The content of the users root folder should show up. 
If the federated shared folder is not available if could either be not listed or just show an error message when the user trys to access that folder. But most importantly, the user should be able to access his files.

### Actual behaviour
The page doesn't show any files and only an error message shows up: 
> This directory is not available. Please check the log files or contact the administrator.

Original in german:
![root-directory_inaccessible_on_NC](https://user-images.githubusercontent.com/26191454/66856771-3546cf80-ef86-11e9-9299-ca5d80815f8f.png)

In addition the sync client fails to access the server and sync files.
The favorites still work, so a user can access all files or folders which are put under the personal favorites. 

(The folder in question (see nextcloud log down below) is "budgt".)

## Server configuration detail

**Operating system:** Linux 4.19.77-1-lts SMP Sat Oct 5 18:49:03 CEST 2019 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.4.8

**PHP version:** 

7.3.10
Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, bz2, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, Phar, curl, exif, ftp, gd, gmp, intl, iconv, pdo_mysql, pdo_sqlite, sockets, sqlite3, zip, apcu, igbinary, imagick, smbclient, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** updated since NC13 release

**Where did you install Nextcloud from:** official archive download

<details><summary>Signing status</summary>

Array
(
    [text] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - announcementcenter: 3.6.1
 - apporder: 0.8.0
 - audioplayer: 2.8.4
 - bookmarks: 2.2.0
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - camerarawpreviews: 0.7.2
 - checksum: 0.4.3
 - circles: 0.17.8
 - cloud_federation_api: 1.0.0
 - cms_pico: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - cookbook: 0.5.2
 - cospend: 0.1.5
 - dav: 1.13.0
 - deck: 0.7.0
 - event_update_notification: 1.0.0
 - external: 3.4.1
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_accesscontrol: 1.7.0
 - files_automatedtagging: 1.7.0
 - files_downloadactivity: 1.6.0
 - files_external: 1.8.0
 - files_markdown: 2.1.0
 - files_mindmap: 0.0.15
 - files_pdfviewer: 1.6.0
 - files_readmemd: 1.1.1
 - files_retention: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_texteditor: 2.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - firstrunwizard: 2.6.0
 - flowupload: 0.1.3
 - gallery: 18.4.0
 - groupfolders: 5.0.3
 - guests: 1.3.1
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - maps: 0.1.2
 - metadata: 0.10.0
 - nextcloud_announcements: 1.6.0
 - notes: 3.0.3
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - polls: 0.10.2
 - previewgenerator: 2.1.0
 - provisioning_api: 1.7.0
 - qownnotesapi: 19.9.0
 - quota_warning: 1.6.0
 - ransomware_protection: 1.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - sharerenamer: 2.7.2
 - social: 0.2.101
 - socialsharing_email: 1.0.6
 - spreed: 7.0.0
 - support: 1.0.1
 - suspicious_login: 2.3.0
 - systemtags: 1.7.0
 - talk_simple_poll: 1.0.0
 - tasks: 0.11.3
 - telephoneprovider: 1.0.2
 - text: 1.0.2
 - theming: 1.8.0
 - twofactor_admin: 1.0.0
 - twofactor_backupcodes: 1.6.0
 - twofactor_totp: 4.0.0
 - updatenotification: 1.7.0
 - uploaddetails: 0.1.2
 - user_usage_report: 1.1.2
 - video_converter: 0.1.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - dashboard
 - dashboardcharts
 - dicomviewer
 - drawio
 - dropit
 - encryption
 - extract
 - files_reader
 - files_videoplayer
 - jsloader
 - onlyoffice
 - privacy
 - ransomware_detection
 - recommendations
 - sharelisting
 - survey_client
 - timetracker
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "my.domain.tld",
        "localhost"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "version": "17.0.0.9",
    "logtimezone": "Europe\/Berlin",
    "appstore.experimental.enabled": true,
    "appstoreenabled": true,
    "appstoreurl": "https:\/\/api.nextcloud.com\/v1",
    "appcodechecker": true,
    "apps_paths": [
        {
            "path": "\/var\/www\/nextcloud\/apps",
            "url": "\/apps",
            "writable": true
        }
    ],
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_smtpport": "587",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\TIFF",
        "OCA\\CameraRawPreviews\\RawPreview",
        "OCA\\CameraRawPreviews\\IndesignPreview",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop"
    ],
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "filelocking.enabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 0
    },
    "maintenance": false,
    "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
    "updater.release.channel": "stable",
    "loglevel": 2,
    "theme": "",
    "installed": true,
    "overwrite.cli.url": "https:\/\/my.domain.tld",
    "defaultapp": "apporder",
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "tasks",
        "files_readmemd",
        "polls",
        "apporder",
        "video_converter",
        "metadata",
        "telephoneprovider",
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** none

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:69.0) Gecko/20100101 Firefox/69.0

**Operating system:** independent from OS

## Logs

<details><summary>Nextcloud log</summary>

```
{"reqId":"aD9Pu5ly0eRU9ph4K2Yk","level":3,"time":"2019-10-15T19:01:21+02:00","remoteAddr":"2101:f51:aaa:2501:9e18:3c0d:92f5:11ab","user":"MY_USER","app":"no app in context","method":"GET","url":"\/ocs\/v1.php\/apps\/files_sharing\/api\/v1\/remote_shares?format=json&include_tags=true","message":{"Exception":"OCP\\Files\\StorageNotAvailableException","Message":"","Code":1,"Trace":[{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php","line":126,"function":"checkAvailability","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":112,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":112,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php","line":112,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/apps\/workflowengine\/lib\/Check\/FileMimeType.php","line":79,"function":"is_dir","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/apps\/workflowengine\/lib\/Check\/AbstractStringCheck.php","line":63,"function":"getActualValue","class":"OCA\\WorkflowEngine\\Check\\FileMimeType","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/apps\/workflowengine\/lib\/Manager.php","line":123,"function":"executeCheck","class":"OCA\\WorkflowEngine\\Check\\AbstractStringCheck","type":"->","args":["!is","image\/bmp"]},{"file":"\/var\/www\/nextcloud\/apps\/workflowengine\/lib\/Manager.php","line":94,"function":"check","class":"OCA\\WorkflowEngine\\Manager","type":"->","args":[{"id":"27","class":"OCA\\WorkflowEngine\\Check\\FileMimeType","operator":"!is","value":"image\/bmp","hash":"0893645dcc70a10aeac58865074a65a9"}]},{"file":"\/var\/www\/nextcloud\/apps\/files_accesscontrol\/lib\/Operation.php","line":67,"function":"getMatchingOperations","class":"OCA\\WorkflowEngine\\Manager","type":"->","args":["OCA\\FilesAccessControl\\Operation"]},{"file":"\/var\/www\/nextcloud\/apps\/files_accesscontrol\/lib\/CacheWrapper.php","line":63,"function":"checkFileAccess","class":"OCA\\FilesAccessControl\\Operation","type":"->","args":[{"mountPoint":"\/MY_USER\/files\/budgt\/","cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\RansomwareProtection\\StorageWrapper"},""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":71,"function":"formatCacheEntry","class":"OCA\\FilesAccessControl\\CacheWrapper","type":"->","args":[{"__class__":"OC\\Files\\Cache\\CacheEntry"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/Cache\/Wrapper\/CacheWrapper.php","line":69,"function":"get","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","line":1327,"function":"get","class":"OC\\Files\\Cache\\Wrapper\\CacheWrapper","type":"->","args":[""]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Files\/View.php","line":1382,"function":"getCacheEntry","class":"OC\\Files\\View","type":"->","args":[{"mountPoint":"\/MY_USER\/files\/budgt\/","cache":null,"scanner":null,"watcher":null,"propagator":null,"updater":null,"__class__":"OCA\\RansomwareProtection\\StorageWrapper"},"","\/budgt"]},{"file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Controller\/RemoteController.php","line":118,"function":"getFileInfo","class":"OC\\Files\\View","type":"->","args":["\/MY_USER\/files\/budgt"]},{"function":"extendShareInfo","class":"OCA\\Files_Sharing\\Controller\\RemoteController","type":"::","args":[{"id":"1","remote":"https:\/\/nextcloud.pahofmann.com\/","remote_id":"18","share_token":"kuZsIYq8BS1TY6S","name":"\/budgt","owner":"patrick","user":"MY_USER","mountpoint":"\/budgt","accepted":"1"}]},{"file":"\/var\/www\/nextcloud\/apps\/files_sharing\/lib\/Controller\/RemoteController.php","line":138,"function":"array_map","args":["self::extendShareInfo",[{"id":"1","remote":"https:\/\/nextcloud.pahofmann.com\/","remote_id":"18","share_token":"kuZsIYq8BS1TY6S","name":"\/budgt","owner":"patrick","user":"MY_USER","mountpoint":"\/budgt","accepted":"1"}]]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":170,"function":"getShares","class":"OCA\\Files_Sharing\\Controller\\RemoteController","type":"->","args":[]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\RemoteController"},"getShares"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\RemoteController"},"getShares"]},{"file":"\/var\/www\/nextcloud\/lib\/private\/AppFramework\/Routing\/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\RemoteController","getShares",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"ocs.files_sharing.Remote.getShares"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"ocs.files_sharing.Remote.getShares"}]},{"file":"\/var\/www\/nextcloud\/lib\/private\/Route\/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"ocs.files_sharing.Remote.getShares"}]},{"file":"\/var\/www\/nextcloud\/ocs\/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["\/ocsapp\/apps\/files_sharing\/api\/v1\/remote_shares"]}],"File":"\/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Availability.php","Line":90,"Hint":"Storage is temporarily not available","CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:69.0) Gecko\/20100101 Firefox\/69.0","version":"17.0.0.9"}
```
</details>

**Comment by kesselb** [comment]
```
Index: apps/files_sharing/lib/Controller/RemoteController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/files_sharing/lib/Controller/RemoteController.php	(revision 9d6a58e6aef035dc99fd5dedddc8353b5d888491)
+++ apps/files_sharing/lib/Controller/RemoteController.php	(date 1571235206617)
@@ -28,6 +28,7 @@
 use OCP\AppFramework\OCS\OCSForbiddenException;
 use OCP\AppFramework\OCS\OCSNotFoundException;
 use OCP\AppFramework\OCSController;
+use OCP\Files\StorageNotAvailableException;
 use OCP\ILogger;
 use OCP\IRequest;
 
@@ -115,7 +116,12 @@
 	 */
 	private static function extendShareInfo($share) {
 		$view = new \OC\Files\View('/' . \OC_User::getUser() . '/files/');
-		$info = $view->getFileInfo($share['mountpoint']);
+
+		try {
+			$info = $view->getFileInfo($share['mountpoint']);
+		} catch(StorageNotAvailableException $e) {
+			return false;
+		}
 
 		$share['mimetype'] = $info->getMimetype();
 		$share['mtime'] = $info->getMTime();
@@ -135,7 +141,7 @@
 	 */
 	public function getShares() {
 		$shares = $this->externalManager->getAcceptedShares();
-		$shares = array_map('self::extendShareInfo', $shares);
+		$shares = array_filter(array_map('self::extendShareInfo', $shares));
 
 		return new DataResponse($shares);
 	}
@@ -154,10 +160,14 @@
 
 		if ($shareInfo === false) {
 			throw new OCSNotFoundException('share does not exist');
-		} else {
-			$shareInfo = self::extendShareInfo($shareInfo);
-			return new DataResponse($shareInfo);
-		}
+		}
+
+		$shareInfo = self::extendShareInfo($shareInfo);
+		if ($shareInfo === false) {
+			throw new OCSNotFoundException('could not extend share info');
+		}
+
+		return new DataResponse($shareInfo);
 	}
 
 	/**
```

**Comment by Schmuuu** [comment]
Hi @kesselb 

Thanks for the suggestion. I made the changes to the file, restart nginx, restarted php-fpm and tried to load the root directory of the affected user, but still the same error message in the WebGUI.

The only thing that changed, I don't get an error message in the logs 🙈

**Comment by Schmuuu** [comment]
Hi, 

Is there any progress regarding this issues? I can't use Nextcloud right now. The clients crash on Windows and Linux due to this error, so I have no access to my files via the client. With the Browser the access to my files is very limited as well, as I can only navigate to the few folder I marked as favorites and navigate further from there or use the search function then to hopefully find a file in the specific folder I actually need to navigate to. 
The next release NC17.1 would profit as well (and a lot) from a fix. 

Thank you.

**Comment by Schmuuu** [comment]
Hello @MorrisJobke @juliushaertl @kesselb 

Please excuse me, that I pull you into this issue. I can't use my Nextcloud account for a while now, due to the federated share. While there is no official or supported way to remove the federated share apart from perform risky deletions directly in the DB, I'm a bit stranded here.
I don't know if somebody is already trying to fix this issue (at least no-one is assigned yet), so I only want to ask if somebody could take over this issue and try to resolve it soon?

Thank you so much in advance.

**Comment by kesselb** [comment]
cc @nextcloud/server-triage :sos:

**Comment by Schmuuu** [comment]
I really need to use my server in a normal way again soon. I was only holding back fixing this issue myself by wildly deleting entries from the database, so that I can help you fixing the problem by testing all attempts. Unfortunately this is taking really long now. And as said, I don't have any sync of my files right now, which I really need.

Please let me know, if I can provide anything to make fixing this issue easier.
If the whole handling of federated shares will change in the near feature and there is no reason to fix that issue in the current implementation, please let me know that as well. 

Thanks

**Comment by skjnldsv** [comment]
Hey @Schmuuu unfortunately we're all pretty busy lately :/
Does it works if you disable the workflow engine?

**Comment by Schmuuu** [comment]
Hi @skjnldsv 

Thanks a lot for the quick response today. Feels good to have some reaction at least :)
```
# sudo -u http php /var/www/nextcloud/occ app:disable workflowengine
workflowengine can't be disabled.
```
Because I could not disable the app via occ command, I disabled it directly via DB. It didn't have any effect on this issue though.

**Comment by Schmuuu** [comment]
I really had to "fix" that mid-November because I really needed to sync stuff again. The only way to solve that was by deleting entries from the DB tables. And that didn't feel good, as it is always advised by NC devs not to mess in the DB. But what could I do?!

The very sad thing: another friend shared a document via Federated Sharing with me now and his NC server stopped working (Raspi ran out of resources probably). So again I'm left with my server not being able to show my root directory or sync stuff.
The update to NC 17.0.2 didn't solve the problem.

With this issue, Federated Shares are not usable in private environments. Private servers go offline from time to time and that leaves all connected NC servers inaccessible for their connected sync clients. I'm just glad I prepared myself now and added all important folders to my "Favorites". That way I can at least access my files. But not being able to sync files is still very bad for me.

Getting this fixed in NC18 would be really great! Please, I beg you, could you please put some effort into this issue and somehow ignore (fail gracefully) when Federated Servers are not reachable?

I know nothing will happen here during the holidays but would be nice if this issue could be attacked hard the first days/ weeks in 2020.
For now: Merry Christmas and happy holidays!

**Comment by kesselb** [comment]
Could you share the workflow rule with `image/bmp`? Also do you have some access control rules for this folder? I just shared a folder from a test docker, accepted it and stopped the container. Still have access to my root folder.

**Comment by Schmuuu** [comment]
Hi @kesselb 

Thank you for the quick response! Unfortunately I couldn't answer earlier :(
Interesting, I checked the work flow rules before already and was thinking that they could not be the reason for this issue, because I didn't tag the Federated shares nor the root directory (and I don't know if tagging the root dir is possible at all).
However, with your quite specific question for one rule-set I deleted all rule-sets and voila, root dir is accessible again.
I could identify two rule-sets which cause this issue:
+ Only Pictures
+ admin only

If I have one of these two rule-sets configured (just defined in the admin section), the root dir gets inaccessible. The other rule-sets I have, don't interfere. Here are all of them:
![image](https://user-images.githubusercontent.com/26191454/71534490-7735af80-28ff-11ea-9eee-ac5d5158f8cb.png)

For now I have both problematic rule-sets removed to have a fully working NC server.

Thanks for the idea which helped me a lot already! It seems like a bug though, right?

**Comment by kesselb** [comment]
> It seems like a bug though, right?

I guess. Probably https://github.com/nextcloud/server/issues/14797#issuecomment-568492497 could work here.

**Comment by Schmuuu** [comment]
Hello @kesselb 

Thank you again very much for your efforts here!
I tried the code changes from your comment you linked, but that didn't help. There is still no access to the root folder with the same error message.
I removed the Access Rules for no, so that I can work with NC. If you need any information or debug data, please let me know and I will re-add the rules and test for you.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
