### ISSUE TITLE
Container on update screen is too wide

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#17556]
The update screen container is way too wide, which results in content like the app names being all over the place.

This also occurs on the version update page, where it actually changes width of the container depending on the current install step, which seems very unstable.

We should limit the width to the width of the log in boxes, as it was before. cc @nextcloud/designers?

![wide update screen](https://user-images.githubusercontent.com/925062/66871932-055af480-efa5-11e9-9dec-bee7f9dad2ca.png)

(Btw this repeats a vintage issue, same we had 2 years ago ;) https://github.com/nextcloud/server/issues/7161 )

**Comment by ma12-co** [comment]
I agree and I would also suggest aligning the text to the left to improve readability :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
