### ISSUE TITLE
Nextcloud 17 cannot see that php-opcache is used on CentOs 8

### ISSUE THREAD

**Issue by lopar** [nextcloud/server#17553]
### Steps to reproduce
1. Fresh install of Nextcloud 17.0.0 on LAMP server
2. Install php-opcache package
3. Configure `/etc/php.d/10-opcache.ini`
4. Restart httpd

### Expected behaviour
Everything works.

### Actual behaviour
I've got recomendations to enable and configure opcache, but I've already did it.

`php -v`
`PHP 7.2.11 (cli) (built: Oct  9 2018 15:09:36) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.11, Copyright (c) 1999-2018, by Zend Technologies`

### Server configuration detail

**Operating system:** Linux 4.18.0-80.el8.x86_64 #1 SMP Tue Jun 4 09:19:46 UTC 2019 x86_64

**Webserver:** Apache/2.4.37 (centos) OpenSSL/1.1.1 (fpm-fcgi)

**Database:** mysql 10.3.11

**PHP version:** 7.2.11

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, intl, json, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, zip, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.14.2
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - gallery: 18.4.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - firstrunwizard
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "styx.lopar.us",
        "192.168.20.101"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "overwrite.cli.url": "http:\/\/styx.lopar.us",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "updater.release.channel": "stable"
}
```
</details>

**External storages:** yes

<details><summary>External storage configuration</summary>

```
No mounts configured
```
</details>

**Encryption:** no

**User-backends:** 
 * OC\User\Database

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Comment by kesselb** [comment]
This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

**Comment by lopar** [comment]
But hey, doing all this steps, but using Nextcloud 16 do not reproduce the issue, 
So, I assume, if it appear in version 17 freshly installed only, when NC17's inner mechanism cannot see server options - it's NC problem, not server/installation/hardware one. 
No?

**Comment by kesselb** [comment]
I suspect a configuration problem because:

1) Code is the same (at least the backend one): [stable16](https://github.com/nextcloud/server/blob/0708ffcf77a718e7cddb63bc28b5a8dc7cf4bb6c/settings/Controller/CheckSetupController.php#L405-L429) vs [stable17](https://github.com/nextcloud/server/blob/8ebda6d60cc71cfdf43915a7eddfef6875c2b14c/settings/Controller/CheckSetupController.php#L405-L429)
2) 17 is out for a while. If the feature does not work in general there would be much more reports.

Mind to check the actual values for your opcache configuration with phpinfo?

**Comment by lopar** [comment]
Hmph, it looks like operating system issue. I wrote configs, I changed `php.ini` and `10-opcache.ini`, I restarted httpd service. `phpinfo()` and `php -v` both reported, that opcache is on and working.

So, minutes ago I desperately rebooted my server and all php-opcache alerts gone away.

**Comment by sparse91** [comment]
No need to reboot. You should restart php-fpm service.

**Comment by lopar** [comment]
> No need to reboot. You should restart php-fpm service.

Nope it didn't help. That's why I opened this issue. Only full server restart helped me.
