### ISSUE TITLE
S3 as primary storage encryption security

### ISSUE THREAD

**Issue by FlorentCoppint** [nextcloud/server#17561]
Hi,

When we set-up Nextcloud 17 with S3 as primary storage and we enable encryption, the encryption keys are stored on the S3 space.

What is the point of encrypting files on an unsecure place, and storing the encryption key at the same place ?

Will it be fixed ? Is there a workaround about this ?

Thank you.
Flo

**Comment by FlorentCoppint** [comment]
Nobody is concerned about this issue ? "S3 as primary storage" is supposed to be an "enterprise solution" ...

**Comment by Nils160988** [comment]
As pointed out in the documentation, serverside encryption does not prevent users' files from access by nextcloud administrators.
If you do not trust S3 (and its administrators/organisation), you should not place your primary storage there.

So: This is intentional behavior and no bug, I think.
At least, that has been my understanding. So better only use S3 as additional storage then.

**Comment by FlorentCoppint** [comment]
I agree it's not a bug, I didn't tag it.
Maybe we could imagine storing encryption keys on the Nextcloud server itself, and only encrypted data on S3. Or make it an option...

**Comment by Miaourt** [comment]
What the...
I must agree I would be worried if using S3 mean giving keys to my file to S3 suppliers, I trust myself and my server, but I don't trust Amazon or any S3 provider, encrypting the file is a way for me to have them securely stored and unreadable by thirds party, while still having their quite useful "unlimited capacity".

We should have a way to define where we want to store the keys imho, either on the database or on a federated configuration server if sharing the key is the point of this config

This make encryption a non feature in this case, what's the point of having a lock if the key is in the keyhole??

**Comment by tsalwierz** [comment]
Use rclone, mount s3 with rclone locally. Enable external storage as a local directory. Enable encryption on the external storage.

Problem solved. It's a workaround and fuse isn't exactly the best for hundreds of thousands of files, but I doubt this is going to be changed upstream anytime soon on nextclouds end.

**Comment by leo-lb** [comment]
Very poor security design here. I am shocked.

**Comment by jmthackett** [comment]
I'm looking at this too and pretty confused for the same reasons as others. I'd like to be able to store the key in either the database, or a specific filesystem location.

**Comment by samzehnder** [comment]
Have a look [here](https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html), I think/hope the keys are encrypted with the secret found in instance-config.

**Comment by szaimen** [comment]
cc @nextcloud/security any feedback on this? Sounds like a bad security design to me. If not, please close this issue.
The rest is tracked in #22077

**Comment by Miaourt** [comment]
bumb

**Comment by Miaourt** [comment]
Grrrr

**Comment by Miaourt** [comment]
botbump

**Comment by SimplyCorbett** [comment]
Why are legitimate issues being closed by your bots?

If you cant fix it you cant fix it but don't mark these issues as closed.

**Comment by sebastiansterk** [comment]
> cc @nextcloud/security any feedback on this? Sounds like a bad security design to me. If not, please close this issue. The rest is tracked in #22077

@nextcloud/security can you please have a look into this issue? Thanks!

**Comment by lkthomas** [comment]
> As pointed out in the documentation, serverside encryption does not prevent users' files from access by nextcloud administrators. If you do not trust S3 (and its administrators/organisation), you should not place your primary storage there.
> 
> So: This is intentional behavior and no bug, I think. At least, that has been my understanding. So better only use S3 as additional storage then.

I am totally disagreed on this, do you leave your key at the door lock and hope no one going to break in? What is the logic behind?

I want to confirm this after near 3 years of this ticket being opened: Does S3 encryption key still store in S3 space?

**Comment by sebastiansterk** [comment]
AFAIK yes the encryption keys are still stored in the S3 bucket.

**Comment by Hex4919** [comment]
> Another year and couple of months later encryption keys are still stored in the S3 bucket, despite a very clear warning in the official [documentation](https://docs.nextcloud.com/server/26/admin_manual/configuration_files/encryption_configuration.html).
> 
> I checked it on version 26.0.3
> 
> ![image](https://user-images.githubusercontent.com/46034975/252664824-79105ab5-5949-48f2-9db7-6d034df41a17.png)

tbh I currently don't really understand why there is no option to store the key on the Nextcloud host, so Files are not readable for the external storage provider...
This seems like the main use-case of this feature to me.

**Comment by joshtrichards** [comment]
> the encryption keys are stored on the S3 space.\n\nWhat is the point of encrypting files on an unsecure place, and storing the encryption key at the same place ?\n\nWill it be fixed ? Is there a workaround about this ?

This thread seems to be driven by a misunderstanding over terminology. Unless I'm missing something it's creating unnecessary panic. 

Please read the encryption document or at least ask questions to clarify understanding before jumping to conclusions.

Unfortunately some earlier more formal responses might have stopped the vacuum of misunderstanding from continuing - or at least turned this into a more productive conversation. Alas, people get busy and this *is* an open source project so you either have to be patient or look for yourself (or pay Nextcloud GmbH if you need a personalized and timely response).

I am in no way speaking for anyone or officially or for any organization, but I'll give this a shot...

So: There is a hierarchy of keys and key files. 
All of the intermediate key files are encrypted. They themselves can't be decrypted without knowledge of the private keys (think of the private keys as the top of the hierarchy). The private keys are the actual decryption "keys" and they're not stored in the remote object store. 

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#file-type-private-key-file

You can even see where what most people are thinking of as the actual keys are stored (or derived from) here:

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/encryption_details.html#derive-the-decryption-key
