### ISSUE TITLE
running an occ command when a user 1st logs into nextcloud

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/server#17563]
Hi,

Has anybody seen any topics about being able to run an occ command (ideally with variables e.g username) at 1st login

id like to map to a users home folder (using files_external as they are on centralised storage), but only at the point the user starts using nextcloud

Thanks

ZT

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
