### ISSUE TITLE
Too small mimetype icons in file picker in IE/Edge

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1757]
<img width="622" alt="bildschirmfoto 2016-10-14 um 18 27 01" src="https://cloud.githubusercontent.com/assets/245432/19395636/eba8661a-923e-11e6-97ca-a57ecdb31f7c.png">

To open the filepicker enter following in the JS console:

``` js
OCdialogs.filepicker('test');
```

**Comment by pv2k** [comment]
Can i take this????

**Comment by iamsk9** [comment]
can i contribute to this issue?

**Comment by MorrisJobke** [comment]
This is fixed in the meantime by #1756 ;)
