### ISSUE TITLE
possible LDAP timeout with a foreign uid and memberUid

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#17583]
When testing https://github.com/nextcloud/server/pull/17576 I have had users belonging to an disabled LDAP configuration, and a different one enbaled. When looking up groups, the LDAP server is queried to figure out the user's groups. It is expected to get an empty result set. It works properly with "uniqueMember" and "member" as associative attributes, but "memberUid" causes running into a time out.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by blizzz** [comment]
i think it was fixed on the way
