### ISSUE TITLE
oc_sessionPassphrase cookie

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/server#17582]
When testing a NC17  instance @ https://securityheaders.com/ it claims about the `oc_sessionPassphrase` cookie:

> There is no Cookie Prefix on this cookie. This is not a SameSite Cookie. 

Can or should this be fixed?

**Comment by kesselb** [comment]
Might be fixed by https://github.com/nextcloud/server/pull/17075

**Comment by acs-ferreira** [comment]
Let's consider this fixed then as the PR is on it's way 🚀
