### ISSUE TITLE
Scaling issue with burger menu in split screen

### ISSUE THREAD

**Issue by Lufthomas** [nextcloud/server#17592]
### Steps to reproduce
1. Open notes in a split window view (half the screen the browser window the other half another window)
2. Click on the "burger icon" to open menu

### Expected behaviour
The usual notes menu opens displaying other notes and new note. 

### Actual behaviour
Menu space opens but remains blank. Only becomes visible at 80% or 130% zoom in browser. 

## Server configuration detail

**Operating system:** Linux 3.10.0-957.5.1.el7.x86_64 nextcloud/notes#1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.41

**PHP version:** 

7.2.23
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bz2, calendar, ctype, hash, filter, ftp, gettext, gmp, SPL, iconv, Reflection, session, standard, SimpleXML, sockets, mbstring, tokenizer, xml, cgi-fcgi, mysqlnd, bcmath, curl, dba, dom, enchant, fileinfo, gd, imagick, imap, intl, json, ldap, exif, mysqli, odbc, PDO, pdo_mysql, PDO_ODBC, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, pspell, redis, soap, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, xmlreader, xmlrpc, xmlwriter, xsl, zip, ionCube Loader, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - apporder: 0.8.0
 - audioplayer: 2.8.4
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - cospend: 0.1.5
 - dav: 1.13.0
 - deck: 0.7.0
 - drawio: 0.9.4
 - event_update_notification: 1.0.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - mail: 0.17.0
 - maps: 0.1.2
 - nextcloud_announcements: 1.6.0
 - notes: 3.0.3
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - phonetrack: 0.5.4
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - rainloop: 6.0.4
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.1
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.1.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "thomasgevers.com",
        "cloud.thomasgevers.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "overwrite.cli.url": "https:\/\/thomasgevers.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; WOW64; rv:60.0) Gecko/20100101 Firefox/60.0

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by jancborchardt** [comment]
@ma12-co might this be fixed with your work on the navigation?

**Comment by ma12-co** [comment]
Should be, but I'm not entirely sure

**Comment by Lufthomas** [comment]
@jancborchardt and @ma12-co  I can confirm that i am not able to reproduce the original issue for Notes, Calendar, Contacts on Nextcloud 18.0.3 and Nextcloud 19.0.0 Beta 2. The menu is always visible regardless of zoom level or screen width. Thank you for your help!
