### ISSUE TITLE
Share Permissions - Different in File Browser versus "Shares" view

### ISSUE THREAD

**Issue by wdev86** [nextcloud/server#17611]
On Nextcloud 17 and have 3 external storages mounted (/media/mount1, /media/mount2 etc).

Admin account shares /media/mount1/test folder with users usr1, usr2.

The permissions available on the "file browser" (the main view) is "Can Edit", "Can Create", "Can Change". The permissions available on the "shares" view is "Can Edit", "Can Create", "Can Change", "Can Delete".

Why is "Can Delete" missing in the main file navigation view?

There is another problem actually. If I share the mount folder directly (share /media/mount1 with users usr1, usr2)......then only "Can Edit" and "Can Create" is available in the file navigation view. In the "shares" view, "Can Edit", "Can Create", "Can Change", "Can Delete" is available. Why is this?

**Comment by wdev86** [comment]
Also, this bug might be causing a serious bug in the iOS client where it goes into login loop when an invalid action occurs (trying to delete folder without delete permission, trying to upload a file without can create permission):
https://github.com/nextcloud/ios/issues/968

**Comment by szaimen** [comment]
Hi, please add your proposal to https://github.com/nextcloud/server/issues/26691 if it should still be important to you. Thanks!
