### ISSUE TITLE
(LDAP) Quotas are reset on login

### ISSUE THREAD

**Issue by Highview-Lucas** [nextcloud/server#17614]
User quotas are reset to "ldapQuotaDefault" when logging in to nextcloud each time. 

Steps to reproduce: 
Set a new quota for any user - either via 
`$ ./occ user:setting  TheUser files quota 1024Gb`
or via the Web UI.

Log user out. Log user in.
Quota is now set to the value set by
./occ  ldap:set-config s01 ldapQuotaDefault <size>

Setting <size> to be "Unlimited" does not give the user unlimited quota, but does break the updates enough that changing the quota actually persists through logout/login cycles.

**Comment by kesselb** [comment]
Similar to https://github.com/nextcloud/server/issues/17154?

**Comment by Highview-Lucas** [comment]
yes - that one was closed so i opened a new one.

The only difference is my default quota is not set in LDAP (there is none at all) and the default is set via the "files quota" occ setting.

**Comment by blizzz** [comment]
` ./occ ldap:set-config s01 ldapQuotaDefault` the value is missing as argument, use two single quotes for empty: `''`.

**Comment by PVince81** [comment]
please try the solution from blizzz

if this doesn't work in a recent version like Nextcloud 22.2.0, feel free to reopen
