### ISSUE TITLE
Cannot add a new user from the mobile web interface

### ISSUE THREAD

**Issue by nimarb** [nextcloud/server#17620]
### Steps to reproduce
1. Make sure your account has admin rights
2. Log into the web of NC from a mobile browser
3. Tap on the profile picture on the top right, then tap on "User"
4. Try to add a new user --> there is no `+` or `Add` button

### Expected behaviour
A `+` or `Add` button should be visible to create a new user account.
Similiar to the interface on the desktop site:

![image](https://user-images.githubusercontent.com/246059/67200821-16708f00-f405-11e9-9eba-d84a8e26c6d8.png)

### Actual behaviour
No button is visible. Also using "Request Desktop Site" does not show the desktop site, therefore it is impossible to add user accounts from a mobile browser.

### Server configuration

**Operating system**:
Linux

**Web server:**
nginx

**Database:**
mysql

**PHP version:**
7.x

**Nextcloud version:** (see Nextcloud admin page)
16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from 16.0.4

**Where did you install Nextcloud from:**
Arch linux package repo

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Safari

**Operating system:**
iOS 12.4 on an iPhone 7+

**Comment by wiswedel** [comment]
The missing Hamburger-menu has been fixed in 17.

<img width="84" alt="2019-10-22 06-19-20-1" src="https://user-images.githubusercontent.com/1804221/67259089-5fbbef80-f494-11e9-943a-f390addd9530.png">
