### ISSUE TITLE
[Feature] send a file to user (not sharing)

### ISSUE THREAD

**Issue by hoellen** [nextcloud/server#1762]
### Expected behaviour
Click on a file and choose "send file to...".
Then type in a federation share or another user on same nextcloud instance. 
Nextcloud sends a **copy** to the remote user.

### Actual behaviour
You can share a file, but not sending a copy. 

### Example szenario: 
Someone (Alice) request to scan a document and sending to her. At the moment you can scan the document, upload it to your cloud and share it with Alice. But you have to wait until Alice downloaded the file, because if I delete or unshare the file, Alice is not be able to download the document. 
Ok, I can send documents through email, but what if I want to share the installer of MS_Office_2010.exe, a large video or other big files?

**Comment by nickvergessen** [comment]
`MS_Office_2010.exe` is not a file you should share anyway.

Other then that you can just try to send it manually. Nothing we will implement....
