### ISSUE TITLE
Enhance installer

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#17634]
When installting Nextcloud we should offer to install recommended apps.
A simple (by default checked) checkbox should do the trick.

This has some advantages in my opinion

1. We can slim down the size of the release tarball so more apps can be released out of bounds (viewer, right click, pdf viewer etc etc)
2. We can promote more usefull apps that the 90% of admins install anyways (mail, calendar, contacts)
3. Admins that do not want any of this (or that do not have a proper internet connection) just uncheck and are left with a very clean tiny nextcloud.

This all should of course come with some explanatory text. But the basics are straight forward in my opinion.

**Comment by rullzer** [comment]
Probably after checking the box a dedicated page should show.

Here the downloads of the extra tarballs will be triggered.
And you fetch them all. Only when they are all complete (or failed?) you can continue to the next page that does the actual install.

**Comment by ChristophWurst** [comment]
As the installer isn't really ready for adding more front-end complexity in its current state, I would propose that we

* Add the checkbox on the existing installation page
* If checked, redirect to a new "Recommended apps" page on the existing app settings
* Do the rest of the described logic there

This also has the advantage that we can show that page to admins of existing installations. The automated download should of course only be triggered when coming from the installation page with the checkbox checked.
