### ISSUE TITLE
improve GUI administration for multi-language collaborative efforts

### ISSUE THREAD

**Issue by TP75** [nextcloud/server#17631]
### Steps to reproduce
Establish several items i.e. **a set of mixed website entries** to the ['External sites' app](https://github.com/nextcloud/external) sequentially and **with different locales selected** to the admin account in use. Arbitrarily re-order these items by help of the ['App order' app](https://github.com/juliushaertl/apporder/) with different locales selected. 

Arbitrarily select and deselect the administrative views of both apps several times each and make changes to the resp. app settings inside each of their views. This is understood as an usual administration task in a multi-language collaborative environment like a productive distributed Nextcloud in the EU.

### Expected behaviour

Presumably all NC administration and certainly the GUI administration tasks in a multi-language collaborative effort require:

1. Any combination of locales and languages with selectable setup items shall establish a stable and reasonable setup (i.e. list of apps in this use case) in the database. 
4. Any administrative entries to the NC database shall happen in a reasonable & transparent way and the integrity of the administrative setup shall be ensured at all times.
3. Use of locales and translations should be as flexible as possible and should be evenly distributed to the connected clients and the accessing web browsers.
2. The combination of both the 'External sites' app and the 'App order' app should always provide a stable set of data. 

Furthermore, the NC PHP and SQL code should provide some reasonable safety measures for the extended reliability and improved usability of all desktop clients connected.

### Actual behaviour

While establishing the a.m. mixed items by the 'External sites' app view several times some or even more **superfluous items** were observed. These entires appeared automatically and were redundantly listed in the view i.e. became added automatically to the bottom of the websites list. However, the viewed superfluous entries apparently vanished after closing the 'External sites' app view and could not be found in the GUI administration later.

No errors were found in the 'Logging' GUI. Only some days later the apparent b.m. issue of "the 'app list' of doom" was observed by coincidence and from several different NC desktop clients connected to this NC server. Presumably, the a.m. **superfluous entries** only vanished from the GUI admin view but as data entries **unfortunately remained in great numbers** in the database.

Intended website items and app order of the 'External sites' setup in this use case:

- Handbuch (DE) - top bar: 1st in apporder for DE locale 'Deutsch(Förmlich/Sie)', not for EN & NL locales
- Manual (EN) -  top bar: for EN & NL locales,  1st in apporder for DE locale 'Deutsch(Du)' and 2nd in apporder for DE locale 'Deutsch(Förmlich/Sie)' 
- Handbuch (DE) -  top bar: 2nd in apporder for DE locale 'Deutsch(Du)', not for EN & NL locales
- Geräte (DE) - bottom of NC home page
- Devices (EN) - bottom of NC home page

See the screenshot below.

## Server configuration detail

**Operating system:** Linux 4.19.0-6-amd64 - Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Webserver:** Apache (apache2handler)  -- 2.4.38-3+deb10u3

**Database:** mysql 10.3.17 -- mariadb-server 10.3.17-0+deb10u1

**PHP version:** 

7.3.9-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 16.0.5 - 16.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 16.0.4.1 via CLI

**Where did you install Nextcloud from:** 

- official NC repositiory
- 16.0.5 updated manually acc. to [NC 16 Admin Docs » Maintenance » Upgrade manually](https://docs.nextcloud.com/server/16/admin_manual/maintenance/manual_upgrade.html)

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.2.0
 - activity: 2.9.1
 - admin_audit: 1.6.0
 - announcementcenter: 3.5.1
 - **apporder: 0.8.0**
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 0.2.0
 - comments: 1.6.0
 - contacts: 3.1.6
 - dav: 1.9.2
 - **external: 3.3.1**
 - federatedfilesharing: 1.6.0
 - federation: 1.6.0
 - files: 1.11.0
 - files_accesscontrol: 1.6.0
 - files_pdfviewer: 1.5.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.8.0
 - files_texteditor: 2.8.0
 - files_trashbin: 1.6.0
 - files_versions: 1.9.0
 - files_videoplayer: 1.5.0
 - firstrunwizard: 2.5.0
 - gallery: 18.3.0
 - groupfolders: 4.1.4
 - issuetemplate: 0.5.0
 - logreader: 2.1.0
 - lookup_server_connector: 1.4.0
 - nextcloud_announcements: 1.5.0
 - notes: 3.0.3
 - notifications: 2.4.1
 - oauth2: 1.4.2
 - password_policy: 1.6.0
 - polls: 0.10.2
 - privacy: 1.0.0
 - provisioning_api: 1.6.0
 - recommendations: 0.4.0
 - richdocuments: 3.4.2
 - serverinfo: 1.6.0
 - sharebymail: 1.6.0
 - survey_client: 1.4.0
 - systemtags: 1.6.0
 - tasks: 0.11.3
 - text: 1.0.2
 - theming: 1.7.0
 - twofactor_backupcodes: 1.5.0
 - updatenotification: 1.6.0
 - viewer: 1.1.0
 - workflowengine: 1.6.0
Disabled:
 - encryption
 - files_external
 - spreed
 - support
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "debug": false,
    "trusted_domains": [
        "*redacted*",
        "*redacted*"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "16.0.5.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y-m-d H:i:s",
    "log_rotate_size": 52428800,
    "loglevel": 2,
    "activity_expire_days": 190,
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "filelocking.enabled": "true",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "timeout": 1.5
    },
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "*redacted*",
    "theme": "",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "updater.release.channel": "production",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla Firefox/60.0, Apple Safari 12.x / 13.x

**Operating system:** Mac OS X / macOS , Debian Linux, MS-Windows

For more details on the client config and some <del>funny</del> **relevant NC desktop screenshots** refer to the related issue i.e. the parallel bug report [nextcloud/desktop - avoid "the 'app list' of doom" # 1545](https://github.com/nextcloud/desktop/issues/1545)

## Logs

<details><summary>Web server error log</summary>

remains open until further clarification

```

```
</details>

<details><summary>Nextcloud log</summary>

* until now no errors were found in the 'logging' view of the NC GUI which would relate to this issue
* remains open until further clarification

```

```
</details>

<details><summary>Browser log</summary>

seems to be *not applicable* to this issue until further clarification
</details>

## Server Administration

View of the 'External sites' setup:

![screenshot_GUI_2019-10-22a01_external](https://user-images.githubusercontent.com/31193257/67250819-32a81680-f46d-11e9-9811-b1fcd5c28f5d.png)

View of the resp. 'App order' setup with the '**English(US)**' EN variant locale selected:

![screenshot_GUI_2019-10-22b01_apporder_en-US](https://user-images.githubusercontent.com/31193257/67250898-7c90fc80-f46d-11e9-840e-b48fbcd4291f.png)

View of the resp. 'App order' setup with the '**Deutsch(Förmlich/Sie)**' DE variant locale selected:

![screenshot_GUI_2019-10-22c01_apporder_de-DE_Sie](https://user-images.githubusercontent.com/31193257/67250968-c4178880-f46d-11e9-810e-c6e2d0a8cab8.png)

View of the resp. 'App order' setup with the '**Deutsch(Du)**' DE variant locale selected:

![screenshot_GUI_2019-10-22d01_apporder_de-DE_Du](https://user-images.githubusercontent.com/31193257/67251048-f4f7bd80-f46d-11e9-9cc2-667a95cb2141.png)

View of the resp. 'App order' setup with the '**Nederlands**' NL locale selected:

![screenshot_GUI_2019-10-22e01_apporder_NL](https://user-images.githubusercontent.com/31193257/67251168-6899ca80-f46e-11e9-8c57-b03d36e44373.png)

**Comment by juliushaertl** [comment]
Not as server issue but a limitation of the current apporder app. See https://github.com/nextcloud/external/issues/164#issuecomment-544890173 as well

**Comment by TP75** [comment]
@juliushaertl Thank you.

I fully agree after myself learning the same NC server account and the same 'External sites' setup on a _Linux_ machine with the _Version 2.5.1git desktop client_ **produces a stable view**.

Maybe not truly related to  'External sites' as presumed before?

Maybe an issue limited to an unstable Version 2.6.1RC1 desktop client?

**Comment by juliushaertl** [comment]
Lets continue over at  nextcloud/external#164 since you posted the same questions there :wink:
