### ISSUE TITLE
New Folder icon overlaps Home directory icon in move or copy dialog on Chrome

### ISSUE THREAD

**Issue by clcain** [nextcloud/server#17632]
### Steps to reproduce
1. Set up fresh installation of Nextcloud 17.0.0
2. Using Chrome, log in, go to Files, click the three dots next to a file, and select "Move or copy".

### Expected behaviour
The New Folder icon should appear after the path as it does when viewed with Firefox.

![move_copy_dialog_firefox](https://user-images.githubusercontent.com/13763029/67259460-f15f3900-f463-11e9-9bb5-7c33291884a0.png)

### Actual behaviour
The New Folder icon overlaps the Home icon, making the Home icon invisible.

![move_copy_dialog_chrome](https://user-images.githubusercontent.com/13763029/67259462-f58b5680-f463-11e9-8d12-e76294f7be3c.png)

### Server configuration
Fresh Nextcloud 17.0.0 from official Docker image

### Client configuration
Shows overlapping icon in Chrome 77.0.3865.120.
Works correctly on Firefox 69.0.3.

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Check https://github.com/nextcloud/server/pull/17017. Is coming to your instance with 16.0.6 or 17.0.1.

**Comment by clcain** [comment]
This appears to have been a Chrome issue and is fixed with Chrome 78.
