### ISSUE TITLE
uBlock Origin Firefox addon brakes/blocks "share link" function

### ISSUE THREAD

**Issue by tau-ri** [nextcloud/server#17630]
# A report of a painful research:

#### 4: DONE!

**That's it, you might now be able to see the "+" at "share link" again!**

# The Bugstory:

Dear nextclouders, this is not a bug but more than a report to help others facing that stupid situation. After upgrading nc from 15.x to finally 17.0, I missed the ability to "share files & folders via URL"!
WTX I thought and as a nc admin since oc6, I was looking at the APPS direction. Can be that at this upgrade process a APP might cause an issue.
After many trys of various app deactivation I finally deactivated any unofficial app and still some apps related with sharing, such as share by mail and social sharing. But all of this didn't bring me the solution. As I also have a NC16 running which has no problem at all I got more and more angry about wtx could be wrong anymore.
After a research via different search engines and no related problem like mine I thought that this must not be a server issue but a client problem. I tried a different browser and soon got it! This must be something at Firefox. But why is the NC16 working and nc17 not?
This brings me to the add-ons area of Firefox. I was checking all fo my scripts blocking and security stuff add one with no results. After inspecting the deep insights of uBlock Origin, I found a really old entry of my nc16 server (that one still working all the time...).
And that was just it! I Add a line for the URL of my nc17 Server and here wo go again.
I don’t know why uBlock Origin hides this function only since my upgrade, but I want to share this story to anybody for future timesaving’s!

**Comment by shadowlmd** [comment]
Just want to add that Share Link function is blocked by a filter from Fanboy's Annoyance List subscription.
