### ISSUE TITLE
Prevent upload certain file types (eg. mp3 files)

### ISSUE THREAD

**Issue by akurzawa** [nextcloud/server#17633]
Request for global option to prevent upload certain file types (eg. mp3, mp4 files) to the nextcloud server.

I wan't prevent the users to upload multimedia files to the nextcloud. Is this possible to create file type block list directly (and globally) on the server?

**Comment by kesselb** [comment]
https://docs.nextcloud.com/server/17/admin_manual/file_workflows/access_control.html#prevent-uploading-of-specific-files

> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
