### ISSUE TITLE
Pressing enter in "share link by email" reloads page instead of sending mail

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1764]
### Steps to reproduce
1. Share an item with link
2. Type in an address into "Email link to person"
3. Hit `Enter`
### Expected behaviour

Email should send
### Actual behaviour

Hard page refresh
### Server configuration

**Nextcloud version:** git stable10, master

PS: Note that sending the email currently fails as well, due to https://github.com/nextcloud/server/issues/1277

Something for you @ChristophWurst ?

**Comment by nickvergessen** [comment]
Functionality has been removed, closing

**Comment by nickvergessen** [comment]
Should still fix in 10

**Comment by MorrisJobke** [comment]
fixed with #2502
