### ISSUE TITLE
oc_filecache doubled in line count

### ISSUE THREAD

**Issue by dossantg** [nextcloud/server#17647]
We have a nextcloud instance for 100,000 users. This instance is in production since September 2018. This summer we made the update in 16.0.4 and we added the Collabora Online application which is under support.

On 10/10/2019 18PM we had 12 million lines in the oc_filecache table. I looked in a dump and we had 1 million line that correspond to the appdata file and about 11 million corresponding to the user files.

In 24H, the number of rows in the oc_filecache table has doubled. Today we have 23 million rows in this table.

I notice that the "storage" id of the oc_filecache table corresponding to the root of the Nextcloud data storage folder contains 12 million rows.

MariaDB [nextcloud]> select storage,count(storage) as nb from oc_filecache where storage=177 group by storage order by nb ASC;
+---------+----------+
| storage | nb       |
+---------+----------+
|     177 | 12112342 |
+---------+----------+
1 row in set (12.89 sec)

MariaDB [nextcloud]> select * from oc_storages where numeric_id=177;
+------------+------------------------+-----------+--------------+
| numeric_id | id                     | available | last_checked |
+------------+------------------------+-----------+--------------+
|        177 | local::/srv/nextcloud/ |         1 |         NULL |
+------------+------------------------+-----------+--------------+

Before the problem, I was at 1 million line on this id storage with only references to appdata.

All the lines that correspond to the user's storage (home::<user uid>) are now also in the storage local::/srv/nextcloud.

I have several questions:
  How can this happen? I must say that we have not carried out any type of rescan operation.
  Can cron cause this problem?
  Can something in Nexcloud do this?
  Can I delete all lines that match the id storage 177 without deleting those that refer to appdata?

Do not hesitate if you need more information

Best regards

### Steps to reproduce
I do not know how to reproduce this problem.

### Expected behaviour
The storage id local :: <data path> should only contain references to the data "appdata"

### Server configuration

**Operating system**:
Debian 9
**Web server:**
Apache 2.4.25
**Database:**
Mariadb 10.1.41
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from nextcloud 13.0.7

**Where did you install Nextcloud from:**
The sources come from the 16.0.4 branch of github.

**List of activated apps:**
<details>
<summary>Config report</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - files: 1.11.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - gallery: 18.3.0
  - lookup_server_connector: 1.4.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - provisioning_api: 1.6.0
  - richdocuments: 3.3.15
  - sharebymail: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - user_saml: 2.3.1
  - workflowengine: 1.6.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "dbindex": 1
        },
        "filesystem_check_changes": 0,
        "enable_avatars": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "cron_log": true,
        "loglevel": "2",
        "maintenance": false,
        "trashbin_retention_obligation": 30,
        "trashbin_auto_expire": true,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "knowledgebaseenabled": false,
        "sharing.maxAutocompleteResults": 20,
        "sharing.minSearchStringLength": 3,
        "activity_expire_days": "180"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 |                                                                                                                                  |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                                                                                |
| homeFolderNamingRule          |                                                                                                                                  |
| lastJpegPhotoLookup           | 0                                                                                                                                |
| ldapAgentName                 | **********************************************                                                                               |
| ldapAgentPassword             | ***                                                                                                                              |
| ldapAttributesForGroupSearch  |                                                                                                                                  |
| ldapAttributesForUserSearch   | cn;sn;mail;displayName                                                                                                           |
| ldapBackupHost                |                                                                                                                                  |
| ldapBackupPort                |                                                                                                                                  |
| ldapBase                      | ************************                                                                                                            |
| ldapBaseGroups                | ou=groups,****************                                                                                                 |
| ldapBaseUsers                 | ou=accounts,**************************                                                                                                  |
| ldapCacheTTL                  | 6000                                                                                                                             |
| ldapConfigurationActive       | 1                                                                                                                                |
| ldapDefaultPPolicyDN          |                                                                                                                                  |
| ldapDynamicGroupMemberURL     |                                                                                                                                  |
| ldapEmailAttribute            | mail                                                                                                                             |
| ldapExperiencedAdmin          | 1                                                                                                                                |
| ldapExpertUUIDGroupAttr       |                                                                                                                                  |
| ldapExpertUUIDUserAttr        | ********************                                                                                                                      |
| ldapExpertUsernameAttr        | ********************                                                                                                                   |
| ldapExtStorageHomeAttribute   |                                                                                                                                  |
| ldapGidNumber                 | gidNumber                                                                                                                        |
| ldapGroupDisplayName          | cn                                                                                                                               |
| ldapGroupFilter               |                                                                                                                                  |
| ldapGroupFilterGroups         |                                                                                                                                  |
| ldapGroupFilterMode           | 0                                                                                                                                |
| ldapGroupFilterObjectclass    |                                                                                                                                  |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                     |
| ldapHost                      | ***REMOVED SENSITIVE VALUE***                                                                                                               |
| ldapIgnoreNamingRules         |                                                                                                                                  |
| ldapLoginFilter               | (****************************************** |
| ldapLoginFilterAttributes     |                                                                                                                                  |
| ldapLoginFilterEmail          | 0                                                                                                                                |
| ldapLoginFilterMode           | 0                                                                                                                                |
| ldapLoginFilterUsername       | 1                                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                                |
| ldapOverrideMainServer        |                                                                                                                                  |
| ldapPagingSize                | 500                                                                                                                              |
| ldapPort                      | 389                                                                                                                              |
| ldapQuotaAttribute            |                                                                                                                                  |
| ldapQuotaDefault              |                                                                                                                                  |
| ldapTLS                       | 0                                                                                                                                |
| ldapUserAvatarRule            | default                                                                                                                          |
| ldapUserDisplayName           | displayName                                                                                                                      |
| ldapUserDisplayName2          | mail                                                                                                                             |
| ldapUserFilter                | *********************************                                                                         |
| ldapUserFilterGroups          |                                                                                                                                  |
| ldapUserFilterMode            | 0                                                                                                                                |
| ldapUserFilterObjectclass     |                                                                                                                                  |
| ldapUuidGroupAttribute        | auto                                                                                                                             |
| ldapUuidUserAttribute         | auto                                                                                                                             |
| turnOffCertCheck              | 0                                                                                                                                |
| turnOnPasswordChange          | 0                                                                                                                                |
| useMemberOfToDetectMembership | 1                                                                                                                                |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------+

</details>

**Comment by kesselb** [comment]
cc @nextcloud/server-triage

**Comment by rullzer** [comment]
@dossantg I assume you also have a Nextcloud subscription (since you mention under support and 100k users). Could you also shoot in a mail to the Nextcloud support system so we can track it there as well?

**Comment by dossantg** [comment]
Unfortunately we are under support only for the Collabora Online part.

**Comment by karlitschek** [comment]
@dossantg could you send us a message via the website https://nextcloud.com/contact/ and we can discuss subscription options. thanks a lot.

**Comment by dossantg** [comment]
@karlitschek Done !

**Comment by nickvergessen** [comment]
Closing as per above for now
