### ISSUE TITLE
File list empty

### ISSUE THREAD

**Issue by jameslao** [nextcloud/server#17649]
Nextcloud Snap Image 18.0.0 Alpha Build:2019-10-21T22:01:47+00:00 923735021b35d08aadf00cb30e3e9eda42f50a50

When opening the web page it won't show the file list.

In Chrome it shows 
```
main.js:39 Uncaught TypeError: e.registerHeader is not a function
    at Object.attach (main.js:39)
    at Object.attach (plugins.js:68)
    at FileList.initialize (merged-index.js?v=f872093e-0:5032)
    at new FileList (merged-index.js?v=f872093e-0:4654)
    at Object.initialize (merged-index.js?v=f872093e-0:80)
    at merged-index.js?v=f872093e-0:338
    at underscore.js:829
```

In Firefox it's said to be `webpack:///src/main.js `

```
OC.Plugins.register('OCA.Files.FileList', {

	el: null,

	attach: function(fileList) {
		if (fileList.id !== 'files') {
			return;
		}

		this.el = document.createElement('div')
		this.el.id = 'files-recommendation-wrapper';
-->		fileList.registerHeader({
			id: 'recommendations',
			el: this.el,
			render: this.render.bind(this),
			order: 90
		})
	},
```

**Comment by kesselb** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Seems https://github.com/nextcloud/recommendations/pull/136 was merged to early since https://github.com/nextcloud/server/pull/17482 is not yet merged it breaks.

**Comment by jameslao** [comment]
hi @juliushaertl I can see the merged code is in the latest snap (Build:2019-10-25T22:01:44+00:00 0971f27565d2237711ac1001df9d8a0e966cb7e5) but somehow the issue persists...?
