### ISSUE TITLE
Ability to update / overwrite email address when using LDAP authentication

### ISSUE THREAD

**Issue by thaispice** [nextcloud/server#17658]
_In an ideal world your LDAP directory would have up to date information but the reality is different. Particularly when using Active Directory the email field is often missing or wrong. Nextcloud is fast and easy to implement but getting someone to keep AD up to date can often be slow and complicated..._

**Solution:** Allow the email field to be changed even when using LDAP authentication.

This could be implemented in several ways e.g.

- Don't populate email address from LDAP but allow the user to edit it. _(Probably easiest to implement)_
- Populate the email address from LDAP once then allow the user to keep it updated from then on.
- Give each user the option to use either the LDAP value or allow them to override it with what they want it to be.

Thanks for all your work on this product -- really appreciated.

**Comment by blizzz** [comment]
I do not see this happening anytime soon, at least not by us. It would require overhead, like tracking when which email was set by whom, more settings options, the UI would need to touched without making it more complicated, etc. Thus, a lot of complexity.

Perhaps you want to look at https://apps.nextcloud.com/apps/ldap_write_support as an alternative.

As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
