### ISSUE TITLE
Unable to login for destination-user after occ transfer-ownership, Jail.php error logs on login

### ISSUE THREAD

**Issue by FlyinFistOfJuda** [nextcloud/server#1765]
### Steps to reproduce
1. sudo -u apache php occ files:transfer-ownership source-user destination-user
2. Files are transferred ok, client syncs ok.
3. Logins for destination user fails on WebGUI after successful transfer-ownership with
<code>"app":"PHP","message":"Call to a member function file_exists() on null at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Jail.php#214","level":3,"time":"2016-10-17T10:15:11+02:00","method":"POST","url":"\/login","user":"Administrator"}</code>

### Expected behaviour
Destination-User should be able to login

### Actual behaviour
Destination-User cant login, error log is produced, see reproduce step 3.

### Server configuration
**Operating system**:
CentOS 6.8

**Web server:**
Apache 2.2

**Database:**
MySQL 5.x

**PHP version:**
PHP 5.6.26 with acpu and redis

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Owncloud 8.0.2 -> Nextcloud 10.0.1

**Where did you install Nextcloud from:**
Nextcloud Site

**Signing status:**
<details>
<summary>No errors have been found.</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary><?php
$CONFIG = array (
  'instanceid' => 'code',
  'passwordsalt' => 'code',
  'secret' => 'code',
  'trusted_domains' =>
  array (
    0 => 'x.x.x.x',
    1 => 'hostname',
  ),
  'datadirectory' => '/data1/nextcloud_data',
  'filesystem_check_changes' => 1,
  'overwrite.cli.url' => 'https://x.x.x.x',
  'htaccess.RewriteBase' => '/',
  'proxy' => 'proxy:80',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'dbuser',
  'dbpassword' => 'xxx',
  'installed' => true,
  'logfile' => '/var/log/nextcloud.log',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Berlin',
  'mail_smtpmode' => 'smtp',
  'default_language' => 'de_DE',
  'skeletondirectory' => '',
  'maintenance' => false,
  'mail_from_address' => 'no-reply',
  'mail_domain' => 'xxx',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'asset-pipeline.enabled' => 'false',
  'forcessl' => 'true',
  'forceSSLforSubdomains' => false,
  'appstoreenabled' => false,
  'allow_user_to_change_username' => false,
  'knowledgebaseenabled' => false,
  'updatechecker' => false,
  'singleuser' => false,
  'theme' => '',
  'trashbin_retention_obligation' => 'auto',
  'auth.bruteforce.protection.enabled' => false,
  'has_internet_connection' => true,
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'debug' => false,
);
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>Irrelevant</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox, Chrome, Vivaldi, IExplore: Same error

**Operating system:**
Win7

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>,"app":"PHP","message":"Call to a member function file_exists() on null at \/var\/www\/nextcloud\/lib\/private\/Files\/Storage\/Wrapper\/Jail.php#214","level":3,"time":"2016-10-17T10:13:07+02:00","method":"POST","url":"\/login","user":"Administrator"}</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>None relevant</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by FlyinFistOfJuda** [comment]
Other accounts are still working, this is on a snapshotted test environment.

**Comment by nickvergessen** [comment]
@icewind1991 can you have a look?

**Comment by FlyinFistOfJuda** [comment]
Hm, short correction, here's the transfer log:
```
Analysing files of source-user ...
  124 [============================]
Collecting all share information for files and folder of source-user ...
    4 [============================]
Transferring files to administrator/files/transferred from source user on 2016-10-17T08:11:27+00:00 ...
Restoring shares ...
 4/4 [============================] 100%
```
.. but the directory "

transferred from source-user

 does not exist. Directory and files in data-folder are owned apache:apache 644.

**Comment by FlyinFistOfJuda** [comment]
o.O Ok guys, sorry for wasting your time, it's a false alert. Apparently we have an **A**dministrator and now the files are at **a**dministrator. I'll reset to the latest snapshot and do the transfer again. If it works ok, i'll close this bug report.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/1766 will help to prevent such misspelling of user names in the future. Sorry for your trouble.

**Comment by FlyinFistOfJuda** [comment]
No need to be sorry, I'm happy my coffein deficite lead to something good. :smile:
