### ISSUE TITLE
I can't see all groups in Limit Apps to Groups

### ISSUE THREAD

**Issue by michu-pl** [nextcloud/server#17655]
### Steps to reproduce
1. Open Apps menu
2. Select App e.g Password policy
3. Click the check box Limit to Groups

### Expected behaviour
All groups should be on the list.

### Actual behaviour
Only a few groups are on the list.

## Server configuration detail

**Operating system:** Linux 4.9.0-11-amd64 nextcloud/activity#1 SMP Debian 4.9.189-3 (2019-09-02) x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.1.41

**PHP version:** 

7.2.22-1+0~20190902.26+debian9~1.gbpd64eb7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, mailparse, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.0 - 17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-17.0.0.zip

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - bruteforcesettings: 1.4.0
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - data_request: 1.4.0
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - files: 1.12.0
 - files_accesscontrol: 1.7.0
 - files_automatedtagging: 1.7.0
 - files_external: 1.8.0
 - files_frommail: 0.3.0
 - files_pdfviewer: 1.6.0
 - files_retention: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - guests: 1.3.1
 - issuetemplate: 0.5.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - quota_warning: 1.6.0
 - ransomware_detection: 0.6.0
 - ransomware_protection: 1.5.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - systemtags: 1.7.0
 - terms_of_service: 1.3.0
 - text: 1.1.0
 - theming: 1.8.0
 - twofactor_admin: 1.0.0
 - twofactor_backupcodes: 1.6.0
 - twofactor_totp: 4.0.0
 - updatenotification: 1.7.0
 - uploaddetails: 0.1.2
 - user_ldap: 1.7.0
 - user_usage_report: 1.1.2
 - viewer: 1.1.0
 - workflow_pdf_converter: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - deck
 - encryption
 - federation
 - files_fulltextsearch
 - files_texteditor
 - firstrunwizard
 - fulltextsearch
 - gallery
 - spreed
 - support
 - survey_client

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.0.9",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": 1,
    "logtimezone": "Europe\/Warsaw",
    "trashbin_retention_obligation": "auto",
    "filelocking.enabled": "true",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "enable_previews": false,
    "htaccess.RewriteBase": "\/",
    "auth.bruteforce.protection.enabled": false,
    "default_language": "pl",
    "skeletondirectory": "",
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "simpleSignUpLink.shown": false,
    "twofactor_enforced": "true",
    "twofactor_enforced_groups": [
        "2FA"
    ],
    "twofactor_enforced_excluded_groups": [],
    "app_install_overwrite": [
        "workflow_pdf_converter",
        "data_request",
        "files_accesscontrol",
        "files_automatedtagging",
        "files_texteditor",
        "quota_warning",
        "ransomware_protection",
        "ransomware_detection",
        "files_retention",
        "terms_of_service",
        "issuetemplate"
    ],
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** LDAP

```

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>
