### ISSUE TITLE
Home Button not visible during move or copy files and folders

### ISSUE THREAD

**Issue by pthoelken** [nextcloud/server#17656]
### Steps to reproduce
1. Login into your nextcloud web application
2. Select a folder and choose "Copy or Move" in drop-down menu

![image](https://user-images.githubusercontent.com/12643853/67375475-f49d1680-f582-11e9-892b-253f69acf7a7.png)

### Expected behaviour
The home button is not visible. So i can't navigate to the root folder.

### Actual behaviour
The home button should be visible. 

### Server configuration

**Operating system:** CentOS 7

**Web server:** Apache/2.5.6

**Database:** MySQL Vers 15.1 Dirstrib 5.5.64-MariaDB

**PHP version:** 7.3.11

**Nextcloud version:** (see Nextcloud admin page) 17.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Manual Upgrade with replace files

**Where did you install Nextcloud from:** Your Web Page

**Comment by kesselb** [comment]
Thanks for your report :+1: 

Check https://github.com/nextcloud/server/pull/17017. Is coming to your instance with 16.0.6 or 17.0.1.

**Comment by pthoelken** [comment]
Thanks for your response. In this case I think we can close it here for now.
