### ISSUE TITLE
unlink(....): No such file or directory at ..../lib/private/Preview/Movie.php#98

### ISSUE THREAD

**Issue by Schneidoa** [nextcloud/server#17661]
Hello,
when creating preview files of movies, the following error occurs:
unlink(.....): No such file or directory at ..../lib/private/Preview/Movie.php#98

I think you can solve the problem like this:

File: /lib/private/Preview/Movie.php
```
		if ($returnCode === 0) {
			$image = new \OC_Image();
			$image->loadFromFile($tmpPath);
			unlink($tmpPath);
			if ($image->valid()) {
				$image->scaleDownToFit($maxX, $maxY);
				return $image;
			}
		}
               if(is_file($tmpPath)){ //-- check if the file exists before deleting
		     unlink($tmpPath);
                }
		return null;
```

regards
Schneidoa

**Comment by kesselb** [comment]
Thanks for reporting this issue :+1: 

I would pick a slightly different approach. If unlink in line 98 is executed but there is no `$tmpFile` than  `$returnCode` is 0 but the image is not valid. unlink in line 91 must be called before `return $image` inside the if clause.

Do you want to submit a pull request for this?
