### ISSUE TITLE
Sharing individual files from a directory by URL fragment (#foo part in an URI)

### ISSUE THREAD

**Issue by wilhelmy** [nextcloud/server#17668]
**Describe the solution you'd like**

Currently when I have URLs like this https://nextcloud.barfooze.de/s/EmLbDBcXqji2J8K#//IMG_2195.JPG which supposedly point to a single filename in the directory (judging by the URL), I would expect that file to be opened in preview mode.

Instead I'm redirected to the directory index.

I'm using Firefox 69.0.1 on Linux, in case that matters.

**Describe alternatives you've considered**

Creating a share-link to each individual file, which is obviously more cumbersome because you're dealing with more URLs.

**Comment by kesselb** [comment]
cc @skjnldsv @juliushaertl

**Comment by szaimen** [comment]
This should now work at least on NC21.0.2 and above by following:
1. share a link
2. open that shared link in an incognito tab
3. click on the file that you want to link to
4. copy the url that is now in the url-bar
5. share this link with your collegue -> will open the file directly.
