### ISSUE TITLE
[oauth2] Can not delete or change sessions created by incomplete oauth2

### ISSUE THREAD

**Issue by Rotzbua** [nextcloud/server#17675]
### Steps to reproduce

1. add external service to oauth2 
2. create an external oauth2 service
3. request `code` by external oauth2 service
4. do not create a `token`
5. try to rename or delete (revoke) session on `Devices & sessions` -> fails

### Expected behaviour

Session is renamed or deleted.

### Actual behaviour

Gives a error message that session not found if tried to rename or delete.
After relogin or browser refresh session still shown but not changeable.
Sessions with complete oauth2 process can be renamed or deleted.

### Server configuration

**Nextcloud version:** 16

### Client configuration

**Browser:** Firefox 70

#### network log

```
Adress: https://www.example.com/settings/personal/authtokens/16725
Requestmethod:DELETE
Status-Code: 404
Version:HTTP/2.0
```

**Comment by rullzer** [comment]
I think this got fixed in the mean time. At least I can't reproduce it.
Could you check?

**Comment by Rotzbua** [comment]
Seems ok. Thanks
