### ISSUE TITLE
Implementing SQRL authentication

### ISSUE THREAD

**Issue by sidbena** [nextcloud/server#17672]
**Is your feature request related to a problem? Please describe.**
I would like to skip using username and password based authentication altogether.

**Describe the solution you'd like**
Implement the usage of SQRL (https://en.m.wikipedia.org/wiki/SQRL or https://www.grc.com/sqrl/sqrl.htm) within Nextcloud.

**Describe alternatives you've considered**
While 2FA or token based authentication is still more secure than just a password based system, SQRL is even more secure and minimise the risks involved with losing or exposing a user database either by a malicious party or improperly secured server configurations.

**Comment by udoburghardt** [comment]
I would like to support this enhancement.

SQRL is a fascinating technology, I am using it with a wordpress site of mine and would be very happy to use it with my self-hosted NextCloud too. The crypto used is well documented and it has some real advantages compared to username/password schemes. It has been implemented by Steve Gibson (TWiT: "Security Now") during the last 5 years. 

Thanks to the NextCloud people for that great piece of software!

**Comment by forumgudo** [comment]
I would like to support this enhancement.

**Comment by nicox** [comment]
Maybe there is no need to implement everything new.
Drupal already has a module for sqrl, we might be able to copy their code?
https://www.drupal.org/project/sqrl/git-instructions

**Comment by aitorpazos** [comment]
And there is also a WordPress plugin which also has great ratings: https://wordpress.org/plugins/sqrl-login/

**Comment by Grizaster** [comment]
here another support for this enhancement!

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
