### ISSUE TITLE
Firefox blocks js srcipt without error in console

### ISSUE THREAD

**Issue by Milokita** [nextcloud/server#17677]
### Steps to reproduce
1. create an instance in try.nextcloud.com
2. open the page firefox 

### Expected behaviour
Tell us what should happen
All green in network monitor off Firefox
### Actual behaviour
Tell us what happens instead
some script such as "files.js?v=da7df667-0" got blocked by CSP & loaded twice

### Client configuration
**Browser:** Firefox 70.0

**Operating system:** Win 10

one of the response from try.nextcloud.com
`
HTTP/1.1 200 OK
Date: Fri, 25 Oct 2019 13:21:40 GMT
Server: Apache/2.4.38 (Debian)
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload
Last-Modified: Fri, 25 Oct 2019 13:12:03 GMT
ETag: "1c9ee-595bbe568d1f0-gzip"
Accept-Ranges: bytes
Vary: Accept-Encoding
Content-Encoding: gzip
Content-Length: 21906
Content-Type: application/javascript
Keep-Alive: timeout=5, max=97
Connection: Keep-Alive
`

**Comment by kesselb** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Yeah bug in firefox as far as I know.
