### ISSUE TITLE
Federated Backup

### ISSUE THREAD

**Issue by thibaultamartin** [nextcloud/server#17679]
Nextcloud pushes for self-hosting, which is a great thing but comes with some responsibilities some inexperienced users may not have in mind. Especially, losing data is easy if your server gets wiped for any reason.

A federated backup solution could be a user-friendly alternative for the less tech-savvy users. Two users could chose to backup each other's instance. This way if user A's instance got wiped, he could still pull the backup from user B's instance and restore it, from the administrator interface. This would at least require backups encryption, and probably a 24 word seed phrase for the key.

**Comment by sunjam** [comment]
Hi, see these related feature requests:

* Issue #8459 with [$5 bounty](https://www.bountysource.com/issues/55281346-request-allow-federated-storage-to-be-stored-locally)

> Federated data from remote host will still be accessible from the web client while the remote host is offline. Federated share owner can allow those with remote access to keep local copies of the shared data.

* Issue #11653 with [$70 bounty](https://www.bountysource.com/issues/64374997-feature-request-adopt-zot-protocol)

> Zot Protocol allows users to clone/merge/migrate user accounts across multiple physical servers. You can read about Zot/6 here in detail as it has been developed for Hubzilla and works beautifully. This would be an absolutely huge step forward for Nextcloud.

> 
>     Mirroring accounts across multiple servers for faster access times
>     Preventing single point of failure when a user's server goes down
>     Promoting free speech
>     Decentralization
>

**Comment by Gatak** [comment]
it's a good idea.NC should have some internal backup option that can export its database and data directories as well as any configuration files.

**Comment by sunjam** [comment]
I know [rclone is a solid tool](https://www.andyibanez.com/posts/rclone-basics-encryption/) for backing up Nextcloud instances + generic webdav.  [I see an rclone webui is being developed here in react](https://github.com/rclone/rclone-webui-react).  I noticed mention of people mounting their rclone backups via webdav (see various discussions on https://forum.rclone.org)

[Borg Backup](https://www.borgbackup.org/) is another tool that is available.

**Comment by Utopiah** [comment]
I'd also reference to https://github.com/nextcloud/server/issues/15883 in the sense that in my humble opinion this is not a feature, this is a requirement from a GDPR standpoint but, more importantly, a moral obligation when ones promotes itself against vendor lock-in.

**Comment by Gatak** [comment]
Indeed. A NC internal backup system could be GDPR compliant, whereas external backups usually are not. For example if a user do request data removal, it should also be removed from backups.

**Comment by sunjam** [comment]
Right now we have a pledge of moving towards compliance.  See the Data Request app on Github here [1]. You can submit ideas there.

[1] https://github.com/nextcloud/data_request/issues

**Comment by thibaultamartin** [comment]
> Indeed. A NC internal backup system could be GDPR compliant, whereas external backups usually are not. For example if a user do request data removal, it should also be removed from backups.

Some feedback from a digital rights lawyer, who had a quick look at the issue:

> As long as the backup is encrypted and it's an opt-in option for the end-user, I don't see it as an issue regarding GDPR. Quite on the opposite, the GDPR requires data safety

From a more technical standpoint, using a 24 word seed phrase for the encryption key would ensure that the encryption key is not stored on the remote server but can still be reconstructed if the master instance is lost.

I won't dig further into technical details as this is far from by domain of expertise :)

**Comment by Gatak** [comment]
Well even if the backups are encrypted (they should be protected). Users should also have the right to be removed. Data portability also still applies.

**Comment by cloo** [comment]
Falsely closed as recursive duplicates?
The issue was closed as a duplicate for #18589, while #18589 was closed as a duplicate for this one.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage does this make sense for the project in the long run?

**Comment by artonge** [comment]
I think the real need here is to propose a simple way to backup to a remote storage. This remote storage can be an S3 bucket, an FTP server, another Nextcloud instance, or whatever.

But, about making backups to another Nextcloud instance: I would say that it is a good idea in theory and it's fun, but in practice can come with some shortcomings. With this configuration, backups are limited by the available storage on the peer's server, its availability, and its capacity to keep the integrity of the data. So people need to be warned :).
