### ISSUE TITLE
Local storage issue: seeing only folders but : No files in here

### ISSUE THREAD

**Issue by dark-bg** [nextcloud/server#17682]
When i try to go in some folder says No files in here and in some others cant see all files. 

Sysinfo
Nextcloud 17
Ubuntu 18.04

**Comment by MartixNeo** [comment]
i'm having the same issue:
System information:
nc17
centos7
apache web server
mariadb
php7.2
I ran mkdir /media/Work_Orders attached to a cifs network share folder. I can see all files. I ran sudo -u apache:apache php occ files:scan --all. able to see files in gui, but when I open a file it not I get service unavailable.

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

Thanks :+1: Without the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) it's nearly impossible to triage your problem.
