### ISSUE TITLE
server/apps/files_external/  .nav-icon-external-storage\--icon-external-XXX

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#17690]
### Steps to reproduce
1. Installing Nextcloud 16.4
2. setting up a Themefolder in config.php (and setting up a own/new ..img/actions/external.svg and setting it up in the theme
```
.nav-icon-external-storage,
.icon-external {
 --icon-external-000: url("../img/filetypes/folder-external.svg");
 --icon-external-fff: url("../img/filetypes/folder-external.svg");
    background-image: var(--icon-external-000) !important;
	background-image: url('../img/filetypes/folder-external.svg'!important);
}
```
(should normally work ! )
3. creating a external folder in Nextcloud

### Expected behaviour
show the theme - Icon what's be setting up and it is in theme-folder as external.svg

### Actual behaviour
load at first the right Theme-Icon, then replaced it by loading with the Nextcloud-Core Icon.
This is not setted up in the app as Nextcloud-Icon conform with theme-compatibility

i guess, the couples entry's have a reload routine with a flashing and update the Icons again,
this is unnecessary, make the Nextcloud slow and should updated/removed to be conform to the other behaver, this flashing is unnecessary and make all slow ! 

the theme can you download here, should also work with NC 17.
http://www.blackysgate.de/files/folder-root/nextcloud/

### Server configuration

**Operating system**:
OpenMandriva 3.03 (latest)
**Web server:**
Apache
**Database:**
mariadb
**PHP version:**
dont need, it's a running NC instance
**Nextcloud version:
16.4
 (see Nextcloud admin page)

![picture](https://user-images.githubusercontent.com/7925717/66277617-436b6080-e8a1-11e9-884f-4614f578b808.jpg)

i reload the page and from 0:13 up to 0:14/0:15 let show the right icon,
but it is overwriting the right Icon with the wrong Standart-icon out from the app.. like i guess,
could you look for it ?

best regards
Blacky
<details>

**Comment by szaimen** [comment]
Sorry, this is more of a support question than a bug report. And that means you should either ask help from the volunteers on the forum at [help.nextcloud.com](help.nextcloud.com) (who can help you debug and turn it in a bug report if it is a bug) or, if this is important for your business, get a [Nextcloud subscription](https://nextcloud.com/pricing/) and we help you fix it in a few hours or days (according to the SLA).
