### ISSUE TITLE
Safari 6.1.6 doesn't render correctly pages

### ISSUE THREAD

**Issue by kde35** [nextcloud/server#17694]
### Steps to reproduce
1. connect to demo.nextcloud.com, create an account, using a browser that works fine, e.g., firefox and create an admin account.
2. log in to the same account using safari 6.1.6 MacOS X.7.5 
(3. Try to navigate) 

### Expected behaviour
Tell us what should happen
Pages should render correctly.

### Actual behaviour
Tell us what happens instead
Pages get messed up, c.f. attached images.

### Server configuration

Server configuration of the demo.nextcloud.com

(I could give my server configuration, but this happens
with the demo server as well, and I suppose you know
its configuration).
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list

Right click
0.14.2
Official
Accessibility
1.3.0
Official
Activity
2.10.1
Official
Brute-force settings
1.4.0
Official
Collaborative tags
1.7.0
Official
Comments
1.7.0
Official
Deleted files
1.7.0
Official
Federation
1.7.0
Official
File sharing
1.9.0
Official
First run wizard
2.6.0
Official
Gallery
18.4.0
Official
Log Reader
2.2.0
Official
Monitoring
1.7.0
Official
Nextcloud announcements
1.6.0
Official
Notifications
2.5.0
Official
Password policy
1.7.0
Official
PDF viewer
1.6.0
Official
Privacy
1.1.0
Official
Recommendations
0.5.0
Official
Share by mail
1.7.0
Official
Support
1.0.1
Official
Text
1.1.0
Official
Theming
1.8.0
Official
Update notification
1.7.0
Official
Usage survey
1.5.0
Official
Versions
1.10.0
Official
Video player
1.6.0
Official
Viewer 
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>

Again, this is the Nextcloud found on the demo server.

<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Safari 6.1.6

**Operating system:**
MacOS X 7.5
#### Web server error log
<details>
<summary>Web server error log</summary>

I don't have access to webserver error log of demo server.

As far as my own server is concerned, there is no error related access by Safari
(there are misconfigured clients trying to synchronize calendar/address cards every ten minutes or so, so the error log is quite big, but no line is related to current problem)
```
Insert your webserver log here

Again, I don't have the log for demo server.  From my own server, the lines I get when
I "access" the application decks,

192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/apps/decks HTTP/1.1" 302 -
192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/apps/apporder/ HTTP/1.1" 303 -
192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/apps/deck/ HTTP/1.1" 200 82375
192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/core/js/oc.js?v=61faf6e7 HTTP/1.1" 200
 6890
192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/css/icons/icons-vars.css?v=1572105844 
HTTP/1.1" 200 219190
192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/apps/piwik/js/tracking HTTP/1.1" 200 2
739
192.168.1.1 - - [26/Oct/2019:18:05:25 +0200] "GET /index.php/avatar/cn/32?v=3 HTTP/1.1" 304 -
192.168.1.1 - - [26/Oct/2019:18:05:26 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notificatio
ns HTTP/1.1" 200 18653
192.168.1.1 - - [26/Oct/2019:18:05:26 +0200] "GET /index.php/apps/apporder/getOrder HTTP/1.1" 200 6
44
192.168.1.1 - - [26/Oct/2019:18:05:26 +0200] "GET /ocs/v2.php/cloud/groups HTTP/1.1" 200 123
192.168.1.1 - - [26/Oct/2019:18:05:26 +0200] "GET /index.php/apps/deck/config HTTP/1.1" 200 17
192.168.1.1 - - [26/Oct/2019:18:05:26 +0200] "GET /index.php/apps/deck/boards HTTP/1.1" 200 2887
``` (lines containing login names removed)
192.168.1.1 - - [26/Oct/2019:18:05:36 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 17255
</details>

#### Nextcloud log (data/nextcloud.log)

In my server the file is empty
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

The following is "Developer console" output of Safari, when I created a new instance
of nextcloud on demo server.

nvalid CSS property declaration at: -
223icons-vars.css:2Invalid CSS property declaration at: -
jquery-migrate.min.js:2:556JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:26oc_config is deprecated: use OC.config instead
2globals.js:26oc_requesttoken is deprecated: use OC.requestToken instead
Viewer.js:37OCA.Viewer initialized
search.js:67New search handler registered
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
2globals.js:26The escapeHTML library is deprecated! It will be removed in nextcloud 19.
globals.js:26The select2 library is deprecated! It will be removed in nextcloud 19.
globals.js:26The select2 library is deprecated! It will be removed in nextcloud 19.
5globals.js:26The humanFileSize library is deprecated! It will be removed in nextcloud 19.
globals.js:26oc_defaults is deprecated: use OC.theme instead
whatsnew.js:86querying Whats New data was successful: nocontent
whatsnew.js:89undefined
https://try.nextcloud.com/phai9eib/apps/theming/img/core/filetypes/image.svg?v=0Failed to load resource: the server responded with a status of 500 (Internal Server Error)
![Capture d’écran 2019-10-26 à 16 55 27](https://user-images.githubusercontent.com/13499351/67622849-d8b5a100-f81e-11e9-94ff-ebd599c239e9.png)
![Capture d’écran 2019-10-26 à 17 01 04](https://user-images.githubusercontent.com/13499351/67622851-dc492800-f81e-11e9-80ef-4630feb25017.png)
![Capture d’écran 2019-10-26 à 17 12 25](https://user-images.githubusercontent.com/13499351/67622854-df441880-f81e-11e9-9bd8-22ca28ab8daa.png)

</details>

**Comment by kesselb** [comment]
Nextcloud don't support Safari 6.1.x.

[`last 2 versions, ie >= 11, firefox ESR, not dead`](https://browserl.ist/?q=last+2+versions%2C+ie+%3E%3D+11%2C+firefox+ESR%2C+not+dead) for a list of supported browsers.

**Comment by rullzer** [comment]
Yep that version is not supported. Please upgrade your system or switch to Firefox or Chrome.
