### ISSUE TITLE
Problem with uploading a lot of files.

### ISSUE THREAD

**Issue by dddmark** [nextcloud/server#17709]
Hello! Pls help! :)
When i try to Uploading of lot files (1500 (*.jpg) files and 71 folder) it uploads a small amount and then produces errors.

![image](https://user-images.githubusercontent.com/12506519/67635224-42fa3e80-f910-11e9-8689-3b55e98aa971.png)

![image](https://user-images.githubusercontent.com/12506519/67635232-5c9b8600-f910-11e9-8d9d-c21ba8345221.png)

But there is no problem if I upload 4.5 Gb file.
Ver. Nextcloud: 16.0.4

Video 1:
https://www.youtube.com/watch?v=oUN2s_zbPTI
Video 2:
https://www.youtube.com/watch?v=a3O8xCWodwI
I hope for your help! Thanks!

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

Thanks ;) I guess there are some issues with uploading many files via web but without the issue template and some logs it's quite hard to triage your problem.

**Comment by dddmark** [comment]
![image](https://user-images.githubusercontent.com/12506519/67635944-62489a00-f917-11e9-8945-72c1495715d8.png)
As I saw, there is nothing useful in the logs. Maybe I'm wrong! :)

**Comment by dddmark** [comment]
There is a suggestion that CSRF token is expired while uploading a lot of files (as errors on screen says)

**Comment by zorn-v** [comment]
I can confirm
![image](https://user-images.githubusercontent.com/12619075/68064066-a21de000-fd62-11e9-8fd1-d0c96450ea6f.png)

After pressing "Leave page" there is logout happened

Debug logs
![изображение](https://user-images.githubusercontent.com/12619075/68064126-6cc5c200-fd63-11e9-9fcb-a7c57e599722.png)

Nextcloud 16.0.4

**Comment by TessyPowder** [comment]
Just use [Flowupload](https://github.com/e-alfred/flowupload)
It works really well for thousands of files.

Usage of Flowupload:
![Usage](https://raw.githubusercontent.com/e-alfred/flowupload/master/appinfo/flowupload.gif)

**Comment by zorn-v** [comment]
Thanks for proposal, I will try

> but i dont think this a bug in nextcloud

If something works not as expected - it is a bug :wink:

**Comment by TessyPowder** [comment]
> If something works not as expected - it is a bug

Ok. Youre right.
I am not sure how nextclouds implements uploading (directly (web)dav or something different ?) but i had some bad experiences too. Especially with big or many files. My server is pretty slow (4 cores for 15 Dockers) and before i used flowupload wich uses many independent chunks (each 1.04 MB) i got many timeout errors (i am not saying its nextclouds fault- but being able to retry failed uploads seems like a basic and and needed feature to me)

_I think a lot more changes could be made to uploading. Especially a List of currently uploading files would be great (I made a [app ](https://github.com/TessyPowder/Nextcloud-Uploads-List)to implement that , but its pretty ugly/still a lot of work to do)_

**Comment by dgtlmoon** [comment]
You may run into issues where the server runs out of 'power' whilst trying to build the preview thumbnails for all of the existing images... https://github.com/nextcloud/server/issues/13709#issuecomment-554761933

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
