### ISSUE TITLE
Mobile view broken in NC17

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#17708]
It seems that the mobile view in NC17 is changed. The file name column is too narrow so you can't see any file names.

Also,the settings menu (with avatar) is too far too the right so there is side scrolling.

![Screenshot_20191027-140554_Opera](https://user-images.githubusercontent.com/1469150/67635075-f3415600-f8c2-11e9-8eb7-1a2761f53784.jpg)

![Screenshot_20191027-140746_Opera](https://user-images.githubusercontent.com/1469150/67635101-313e7a00-f8c3-11e9-9e5d-0718e953a349.jpg)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+mobile+view+nc17 ;)

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/17364 (just to set the reference)

**Comment by rollanders** [comment]
Another view with scaling issues. Chrome browser in Android. Scaling is OK with Firefox browser in Android
![Screenshot_20191031_164845_com android chrome](https://user-images.githubusercontent.com/36486009/67969596-e3e74300-fc09-11e9-83c4-de80eb288c3d.jpg)
