### ISSUE TITLE
Missing 3-point menu in the mobile view (After fixing #17469)

### ISSUE THREAD

**Issue by Octopus2** [nextcloud/server#17719]
I was able to find out in which situation in the mobile view the 3-point menu is not displayed (see screenshot here: https://github.com/nextcloud/server/pull/17469#issuecomment-541313138 )

Steps to reproduce:
1. Select german language in Nextcloud
2. Open fileexplorer with your smartphone (with Chrome)
3. You must have a hidden file or hidden folder in the main level
4. The "Show Hidden Files"-option is turned off

Screenshot 1:
![Screenshot_2019-10-27_23-07-28](https://user-images.githubusercontent.com/4060419/67689944-6074ea00-f99c-11e9-8237-e0af131ce6a1.png)
The footer with (....1 versteckte Datei) is too wide. If you go all the way down and wiping to the left in the footer (with optical errors) the 3-point menu becomes visible like in this Screenshot.

Screenshot 2:
![Screenshot_2019-10-27_23-07-52](https://user-images.githubusercontent.com/4060419/67689975-6bc81580-f99c-11e9-8712-977593af4625.png)
Changing the view option (Listview -> Thumbnailview -> Listview) seems to solve the problem superficially. But this is not true, the footer with the number of files and folders is simply no longer displayed.

**Comment by kesselb** [comment]
cc @skjnldsv @GretaD

**Comment by skjnldsv** [comment]
@kesselb please ping @nextcloud/designers, I'm already booked :)

**Comment by mhaelsig** [comment]
I found a similar issue: the 3-point menu (managing shares) is shown in Chromium 76.0.3809.100, but not in Firefox 70.0. I have attached two screenshots - the first one is Chromium, the second Firefox. 
![Kazam_screenshot_00000](https://user-images.githubusercontent.com/10079628/67752782-87c6c800-fa2b-11e9-8da6-43ecec1bb1e8.png)
![Kazam_screenshot_00001](https://user-images.githubusercontent.com/10079628/67752784-87c6c800-fa2b-11e9-9e8a-a865bd48f79c.png)

**Comment by Octopus2** [comment]
@mhaelsig I think that's a different context. With my mistake probably only a Linebreak is missing and with the view change the footer is not indicated any more.

But I also know the described problem with Firefox. For me it was the program "Adblock Plus". After deactivating it on the page, the menu reappeared.

**Comment by mhaelsig** [comment]
@Octopus2 Thank you for this hint. After deactivating the adblocker the menu reappeared.

**Comment by jancborchardt** [comment]
@GretaD do you want to look into this as you worked on this before? :)

**Comment by GretaD** [comment]
sure, i will try within this week
