### ISSUE TITLE
Configure custom share folder path from admin settings

### ISSUE THREAD

**Issue by linucksrox** [nextcloud/server#17713]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Currently the only way to set a custom share folder path is through config.php using the 'share_folder' directive. It would be nice to have a way to do this through the admin settings.

**Describe alternatives you've considered**
Just use config.php

**Additional context**
I have no thoughts on how to present this option, just somewhere in the admin settings.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
