### ISSUE TITLE
Old sessions

### ISSUE THREAD

**Issue by altaris** [nextcloud/server#17720]
**Is your feature request related to a problem? Please describe.**

I am not sure if it's a but or a feature. When a user goes to `Settings -> Security`, all the sessions ever opened to this account are listed. This is particularly annoying when software (such as Lightning in the image below) create those sessions.

![Settings - - Mozilla Firefox](https://user-images.githubusercontent.com/3671894/67691346-b6e32800-f99e-11e9-8333-ffd8b9885a7e.jpg)

This creates clutter that makes it harder for a user to review and manage manually created tokens. It could therefore be considered a security enhancement / issue. 

**Describe the solution you'd like**

I propose two solutions:
1. Display manually created tokens in a separate list, preferably above the current one.
2. An option to automatically terminate sessions older than a set period of time (e.g. 1 month)

**Describe alternatives you've considered**

A bulk-revoke functionality could also be considered. This would allow user to quickly revoke a lot of old or even unknown sessions.

**Additional context**

N/A

**Comment by kesselb** [comment]
Do you use a app password for Lightning?

cc @rullzer @ChristophWurst

**Comment by ChristophWurst** [comment]
Hm. This is tricky to triage, but I think if a client *does* support cookies, as in, send it with each request but still logs in anew every time, this can happen. If that's the case, it's indeed a problem of the client application. Not sure if this is fixable for us.

Stale session tokens are cleaned up in the background. Is your cron set up correctly?

**Comment by altaris** [comment]
Hi, and thank you for your quick response.
@kesselb I indeed use my usual user account password for lightning, thanks for pointing that out.
@ChristophWurst Yes my cron is set up properly as per `Administration -> General` not complaining

**Comment by ChristophWurst** [comment]
Okay. Then using an app password would most likely already solve the issue of newly created sessions.
