### ISSUE TITLE
External SMB storage slow, check SMB server's time zone always 

### ISSUE THREAD

**Issue by jdavidalarcon** [nextcloud/server#17738]
Hello,

All access to the cloud folders has slowed down by adding external SMB storage resources to the server. When the app 'External Storage' is disabled, the performance is recovered. Analyzing the problem it has been found that with each request to the web a process:
sh -c /usr/bin/net time zone -S 'xxxxxxxxxx.domain.local' was launched in the system and each execution of this command consumes almost 1s. 
Disabling the 'External Storage' app disappears these execs and the overall performance is recovered.

If I move the file '/usr/bin/net' to '/usr/bin/back.net' to test, it is also possible to improve the performance without error.

Tested in Nextcloud 15 and 16 now in 16.0.5 with 
Debian buster 10.1
php 7.3

Regards,

Aldasegu

**Comment by kesselb** [comment]
> For improved reliability and performance, we recommended installing libsmbclient-php, a native PHP module for connecting to SMB servers.

https://docs.nextcloud.com/server/17/admin_manual/configuration_files/external_storage/smb.html

> Analyzing the problem it has been found that with each request to the web a process:

We should probably cache the timezone for a while. cc @icewind1991

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
