### ISSUE TITLE
Previews list of sizes

### ISSUE THREAD

**Issue by PhieF** [nextcloud/server#17749]
**Is your feature request related to a problem? Please describe.**
When having a large amount of photos, generating previews uses a lot of storage. The only solution so far is to specify a max y and max x but it's not perfect

**Describe the solution you'd like**
The best for me would be to specify couple of preview sizes, for example

previews_max_sizes => [[x=>200, y=>200], [x=>1920, y=>1920], [x=> 2048, y=>2048]]

So as only three previews would be generated at max

Thanks for your work, if you think the idea is good but don't have time to implement it, we can discuss it here and I will see what I can do by myself

**Comment by tsalwierz** [comment]
I have previews set to 2048x2048, 2MB JPG's are reduced to 185KB on previews.

200,000 2MB JPG = 400GB
200,000 185KB previews = 37GB

That's not a lot of space in the grand scheme of things. If you want to reduce that further you can limit previews to 1024x1024 or less.

I'm assuming you haven't found the jpeg quality option yet.

**Comment by szaimen** [comment]
Hi, please see this article for recommended preview settings:
https://ownyourbits.com/2019/06/29/understanding-and-improving-nextcloud-previews/
Cheers!
