### ISSUE TITLE
CalDAV Cached Subscription: Ability to paste in shared calendar link to discover Webcal

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#17746]
Currently I can not just paste in for example https://cloud.nextcloud.com/apps/calendar/public/MIFAFLFJADIVX63I (Open Source Design calendar) to the subscription field. As it says »Please enter a valid Webcal address«. But we know Nextcloud and from that address should be able to deduct the Webcal address. :)

So, pasting every address like that link, or the WebDAV link should work. Is that possible @nextcloud/calendar?

**Comment by tcitworld** [comment]
I see a few ways we could do this: 

* Simply try the to fetch the hardcoded `?export` route if the provided one returns something else than ical data.
* Fetch with `Accept: text/calendar` and the calendar app could automatically redirect to the `?export` resource
* Or something more complex but also cleaner like adding something like this in our HTML and try looking for it? Could be useful for other apps.
```html
<link href='myshare?export' rel='alternate' type='text/calendar'>
```

**Comment by tcitworld** [comment]
Did 2. in https://github.com/nextcloud/calendar/pull/3250 (we we already fetching with the correct header).
