### ISSUE TITLE
InvalidArgumentException: The given object id is invalid

### ISSUE THREAD

**Issue by wiedi** [nextcloud/server#17758]
# InvalidArgumentException: The given object id is invalid

The cron job is failing with the following backtrace:

```
{
  "reqId": "4YA1EKEsRd9ZnuZgtTCu",
  "level": 3,
  "time": "2019-10-28T20:40:00+00:00",
  "remoteAddr": "",
  "user": "--",
  "app": "core",
  "method": "",
  "url": "--",
  "message": {
    "Exception": "InvalidArgumentException",
    "Message": "The given object id is invalid",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/html/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php",
        "line": 99,
        "function": "setObject",
        "class": "OC\\Notification\\Notification",
        "type": "->",
        "args": [
          "dav",
          "92921151181144849921009711810510092971149910410511810192117115101114924948484856484948929997108-21558"
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/CalDAV/Reminder/ReminderService.php",
        "line": 139,
        "function": "send",
        "class": "OCA\\DAV\\CalDAV\\Reminder\\NotificationProvider\\PushProvider",
        "type": "->",
        "args": [
          {
            "name": "VEVENT",
            "parent": {
              "name": "VCALENDAR",
              "parent": null,
              "__class__": "Sabre\\VObject\\Component\\VCalendar"
            },
            "__class__": "Sabre\\VObject\\Component\\VEvent"
          },
          "Personal",
          [
            {
              "__class__": "OC\\User\\User"
            }
          ]
        ]
      },
      {
        "file": "/var/www/html/apps/dav/lib/BackgroundJob/EventReminderJob.php",
        "line": 62,
        "function": "processReminders",
        "class": "OCA\\DAV\\CalDAV\\Reminder\\ReminderService",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/html/lib/private/BackgroundJob/Job.php",
        "line": 61,
        "function": "run",
        "class": "OCA\\DAV\\BackgroundJob\\EventReminderJob",
        "type": "->",
        "args": [
          null
        ]
      },
      {
        "file": "/var/www/html/lib/private/BackgroundJob/TimedJob.php",
        "line": 55,
        "function": "execute",
        "class": "OC\\BackgroundJob\\Job",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      },
      {
        "file": "/var/www/html/cron.php",
        "line": 124,
        "function": "execute",
        "class": "OC\\BackgroundJob\\TimedJob",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\BackgroundJob\\JobList"
          },
          {
            "__class__": "OC\\Log"
          }
        ]
      }
    ],
    "File": "/var/www/html/lib/private/Notification/Notification.php",
    "Line": 206,
    "CustomMessage": "Error while running background job (class: OCA\\DAV\\BackgroundJob\\EventReminderJob, arguments: )"
  },
  "userAgent": "--",
  "version": "17.0.0.9",
  "id": "5db7527c964f3"
}

```

The reason is that the UID is `92921151181144849921009711810510092971149910410511810192117115101114924948484856484948929997108-21558` which Nextcloud thinks is too long (more than 64 chars).

Looking in the `oc_calendar_reminders` table there are actually three rows with that very same too long uid. The corresponding rows in `oc_calendarobjects` also have that UID.
In `calendardata` they mention `PRODID:-//Nextcloud calendar v1.7.1`.

If my understanding of the code is correct the part that generates these UIDs is in `js/app/utility/stringUtility.js` / `StringUtility.uid`.
I don't see how that function could come up with that wrong UID but maybe there is some broken JS engine out there that has a strange `toString()` + some other bugs?

Nextcloud should probably do some stricter validation here to not allow the creation of Events with UIDs that will later be invalid.

The 64 byte limit also seems wrong as `rfc5545` states

> Implementations MUST be able to receive and persist values of at least 255 octets for this property [...]

A recommendation on how to fix these entries in the database would also be appreciated.
Thanks!

### Steps to reproduce

Not sure yet.
Maybe manually create Event with problematic UID.

### Expected behaviour

Cronjob not breaking.

### Actual behaviour

See stack trace above.

### Server configuration

**Operating system**:

Linux

**Web server:**

nginx/1.17.3

**Database:**

10.4.8-MariaDB-1

**PHP version:**

PHP/7.3.11

**Nextcloud version:** 

17.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated

**Where did you install Nextcloud from:**

Official docker image

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.8.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - cookbook: 0.5.4
  - dav: 1.13.0
  - deck: 0.7.0
  - drawio: 0.9.4
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_automatedtagging: 1.7.0
  - files_downloadactivity: 1.6.0
  - files_external: 1.8.0
  - files_markdown: 2.1.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_retention: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.17.0
  - maps: 0.1.2
  - metadata: 0.10.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - passwords: 2019.10.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_protection: 1.5.0
  - recommendations: 0.5.0
  - richdocuments: 3.4.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - smb_test: 0.2.3
  - social: 0.2.101
  - spreed: 7.0.1
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - talk_simple_poll: 1.0.0
  - tasks: 0.11.3
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - nextcloud_announcements
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/cloud.***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "default_language": "de",
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
</details>

**Are you using external storage, if yes which one:** 

SMB/CIFS

**Are you using encryption:** 

no

**Are you using an external user-backend, if yes which one:**

no

### Client configuration
**Browser:**

Unknown

**Operating system:**

Unknown

#### Web server error log
<details>
<summary>Web server error log</summary>
-
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

{"reqId":"lMt6H8nsJR6nciOwtuaa","level":3,"time":"2019-10-30T16:35:00+00:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"InvalidArgumentException","Message":"The given object id is invalid","Code":0,"Trace":[{"file":"\/var\/www\/html\/apps\/dav\/lib\/CalDAV\/Reminder\/NotificationProvider\/PushProvider.php","line":99,"function":"setObject","class":"OC\\Notification\\Notification","type":"->","args":["dav","92921151181144849921009711810510092971149910410511810192117115101114924948484856484948929997108-21558"]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/CalDAV\/Reminder\/ReminderService.php","line":139,"function":"send","class":"OCA\\DAV\\CalDAV\\Reminder\\NotificationProvider\\PushProvider","type":"->","args":[{"name":"VEVENT","parent":{"name":"VCALENDAR","parent":null,"__class__":"Sabre\\VObject\\Component\\VCalendar"},"__class__":"Sabre\\VObject\\Component\\VEvent"},"Personal",[{"__class__":"OC\\User\\User"}]]},{"file":"\/var\/www\/html\/apps\/dav\/lib\/BackgroundJob\/EventReminderJob.php","line":62,"function":"processReminders","class":"OCA\\DAV\\CalDAV\\Reminder\\ReminderService","type":"->","args":[]},{"file":"\/var\/www\/html\/lib\/private\/BackgroundJob\/Job.php","line":61,"function":"run","class":"OCA\\DAV\\BackgroundJob\\EventReminderJob","type":"->","args":[null]},{"file":"\/var\/www\/html\/lib\/private\/BackgroundJob\/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"\/var\/www\/html\/cron.php","line":124,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"\/var\/www\/html\/lib\/private\/Notification\/Notification.php","Line":206,"CustomMessage":"Error while running background job (class: OCA\\DAV\\BackgroundJob\\EventReminderJob, arguments: )"},"userAgent":"--","version":"17.0.0.9"}

</details>

**Comment by kesselb** [comment]
Should be fixed by #19252 in the meantime.
