### ISSUE TITLE
Admin password stored in plain text

### ISSUE THREAD

**Issue by tulamidan** [nextcloud/server#1775]
### Steps to reproduce
1. Install NC and configure a NC Admin user 
2. Check the content of ./config/config.php 
3.You will see that the Admin password is stored in plain text - > bad for security.

### Expected behavior
Tell us what should happen: The password should not be stored in plain text, rather hashed or encrypted

### Actual behavior
Tell us what happens instead -> Plain text, human readable

### Server configuration
**Operating system**:
linux
**Web server:**
nginx
**Database:**
mysql
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Download daily

**Comment by GoetheG** [comment]
Is this still an issue @tulamidan? Are all the passwords stored in the MySQL database?
