### ISSUE TITLE
Share sidebar: put »unshare« function in 3-dot menu as well

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1776]
The share sidebar is still messy with too many things:
![capture du 2016-10-18 11-16-28](https://cloud.githubusercontent.com/assets/925062/19471777/ea44e9ae-9524-11e6-92e7-c090733b7d98.png)

Putting the »Unshare« delete function in the dropdown as well will clean it up a lot. What do you think @nextcloud/javascript?

(Keeping the »can edit« visible is important since read-only or write is the main distinction.)

**Comment by skjnldsv** [comment]
Agreed. Will clear up the area.

**Comment by MorrisJobke** [comment]
Yes 👍 makes total sense

**Comment by rullzer** [comment]
I don't like it. If we are going to remove unsharing then we might as well remove the can edit as well. Especially since if you consider other languages translated `can edit` can take up even more space which make this saving a bit meh. Maybe an indicator to show if edit permissions are given is beter (same with share permissions?).

**Comment by rullzer** [comment]
Also. What resolution are you using? I have way more space available.

**Comment by jancborchardt** [comment]
> I don't like it. If we are going to remove unsharing then we might as well remove the can edit as well. 

Why? How do the two correlate? Read-only or write is an important indicator, much like the »Share« indicator in the file list. Unsharing is just an action.

> Also. What resolution are you using? I have way more space available.

This specific screenshot is from mobile. But it’s not an issue of space, but of too many elements. And if you look at the whole sidebar it’s even worse.

**Comment by rullzer** [comment]
Well it feels very arbitrary to hide everything but the can edit. I'd say can share is kind of essential in the share part.

**Comment by jancborchardt** [comment]
Because of information overload we should show only the most important one, so it’s a decision of what’s most important. If everything is essential, then nothing is.

**Comment by rullzer** [comment]
well we are already hiding a bunch of stuff. It is not like there are now a 100 items. but do as you want.

**Comment by jancborchardt** [comment]
> well we are already hiding a bunch of stuff

After we added about everything we could come up with ;D

**Comment by nickvergessen** [comment]
The problem I see with this is, that it will be even more pain, when you unshare a file from a couple of users (because we still have no expiration of user/group shares).
You just doubled the number of needed clicks.
Maybe similar to the file list a "check mark list" + "unshare selected" is needed?

**Comment by jancborchardt** [comment]
> The problem I see with this is, that it will be even more pain, when you unshare a file from a couple of users (because we still have no expiration of user/group shares).
> You just doubled the number of needed clicks.

Yes, but how often do you need it?

> Maybe similar to the file list a "check mark list" + "unshare selected" is needed?

Adding _even more_? Sorry but no.

Folks, we need to really carefully decide what to show. Only the most necessary stuff should always be in view. You use the software all day for developing so you might share and unshare all the time, but it’s different for the average person using Nextcloud.

**Comment by rullzer** [comment]
Yeah but most nessearry is the key here. I'd argue that setting edit permissions in a one time thing, which should happen when sharing not afterwards (But that is a different topic). The most commen action for a share is most likely removing it again.

Anyway I guess I just see it differently so I'll leave it up to the design team.

**Comment by MorrisJobke** [comment]
> Yeah but most nessearry is the key here. I'd argue that setting edit permissions in a one time thing, which should happen when sharing not afterwards (But that is a different topic). The most commen action for a share is most likely removing it again.

👍 

I think a little indicator for "read-write" is enough here instead of the text.

**Comment by jancborchardt** [comment]
So then we would have a separate indicator and setting for changing read-write. How would the indicator look – probably an icon? Then people are likely to not understand it, and we need explanatory text → boom we can just use the checkbox with text. ;)

**Comment by MariusBluem** [comment]
Solved in #1955 by @juliabode 💪 THX!
