### ISSUE TITLE
hasher.php fails with memory allocation error

### ISSUE THREAD

**Issue by jprush** [nextcloud/server#17761]
### Steps to reproduce
1. Use Webinstaller "setup-nextcloud.php" to start Setup Wizard for Nextcloud
2. click "Next" and chosse a directory to install in, I took the default "nextcloud"
3. After successful copy of all files click "Next" to go to step 3 of webinstaller
4. Give a username for admin, a password and select MySQL as database during install
5. supply details for database connection, click "finish install"
6. Installation fails with error

### Expected behaviour
Installation should finish successfully and go to Welcome-Screens of Web-Backend.

### Actual behaviour
Installation fails with message (in german)
"Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.

Weitere Details können im Server-Protokoll gefunden werden. "

### Server configuration

**Operating system**:  CentOS 7-1908

**Web server:** Apache 2.4

**Database:** MySQL 5.7

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** 
webinstaller from https://nextcloud.com/install/#instructions-server

**Signing status:** ?
JPRusch
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

cannot login due to password hasherror

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)

<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
{"reqId":"Xbm9lf63PHv7cOpZ4JY5zwAAAAA","level":3,"time":"2019-10-30T16:43:04+00:00","remoteAddr":"192.168.238.247","user":"--","app":"PHP","method":"POST","url":"\/nextcloud\/index.php","message":"password_hash(): Memory allocation error at \/home\/newvidbw\/nextcloud.newvision-demo.de\/nextcloud\/lib\/private\/Security\/Hasher.php#80","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.0.9"}
{"reqId":"Xbm9lf63PHv7cOpZ4JY5zwAAAAA","level":3,"time":"2019-10-30T16:43:15+00:00","remoteAddr":"192.168.238.247","user":"--","app":"index","method":"POST","url":"\/nextcloud\/index.php","message":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"\/home\/newvidbw\/nextcloud.newvision-demo.de\/nextcloud\/core\/Controller\/SetupController.php","line":72,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/newvidbw\/nextcloud.newvision-demo.de\/nextcloud\/lib\/base.php","line":938,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"\/home\/newvidbw\/nextcloud.newvision-demo.de\/nextcloud\/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"\/home\/newvidbw\/nextcloud.newvision-demo.de\/nextcloud\/lib\/private\/Setup.php","Line":415,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:70.0) Gecko\/20100101 Firefox\/70.0","version":"17.0.0.9"}
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>


Replacing code lines in /nextcloud/lib/private/Security/hasher.php
during step3 of webinstaller as a workaround leads to succesful installation:

**old:**
        public function hash(string $message): string {
		if (\defined('PASSWORD_ARGON2I')) {
			return 2 . '|' . password_hash($message, PASSWORD_ARGON2I, $this->options);
		} else {
			return 1 . '|' . password_hash($message, PASSWORD_BCRYPT, $this->options);
		}
	}

**new:**
        public function hash(string $message): string {
		if (\defined('PASSWORD_ARGON2I')) {
			return 2 . '|' . password_hash($message, PASSWORD_ARGON2I, ['memory_cost'=>8192]);
		} else {
			return 1 . '|' . password_hash($message, PASSWORD_BCRYPT, $this->options);
		}
	}

**Comment by jprush** [comment]
This seems related to https://bugs.php.net/bug.php?id=78516

**Comment by jprush** [comment]
I can confirm the same behaviour with PHP 7.3.10 and PHP 7.2.23

**Comment by blizzz** [comment]
related https://github.com/nextcloud/server/pull/19023 but it will still stick with the defaults.

**Comment by kesselb** [comment]
It's possible to pick lower values for the password hashing with Nextcloud 18.0.1 / 17.0.3 / 16.0.9 

https://github.com/nextcloud/server/blob/1e0e09e5cedf49a67143f4a94ef1c350cc41884f/config/config.sample.php#L1436-L1465

If you already know that your hardware is to slow create another configuration file with those options and use lower values: https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file
