### ISSUE TITLE
Nextcloud 17 - security - remotewipe - no username

### ISSUE THREAD

**Issue by akurzawa** [nextcloud/server#17764]
Nextcloud 17 - security - remotewipe

Great function, but how the whell would I know which entry is which user? There should be a username next to the list entry

![image](https://user-images.githubusercontent.com/20043789/67931383-fd649c80-fbc1-11e9-9ad0-fcf9d59454d9.png)

**Comment by j-ed** [comment]
> ow the whell would I know which entry is which user?

If I interpret your screenshot correctly, it shows the app specific password dialog. All listed passwords are usually owned by **one single user** who uses different app passwords for his apps. The user name for all these passwords is always the same as the login name of the user?!

**Comment by szaimen** [comment]
All of the listed devices are logins of your Nextcloud account. Hope that helps!
