### ISSUE TITLE
UI should reflect if you cannot create link shares

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#17774]
- [ ] Ui should not show "add new link share" (https://github.com/nextcloud/server/pull/18672)
- [ ] Sharing with email should not be suggested
- [ ] Improve the message in the settings stating that disabling link shares will also disable email sharing
- [ ] Merge the enforce settings together

ref https://github.com/nextcloud/server/pull/16629

**Comment by kshitizkashyap** [comment]
Hi @skjnldsv, I would like to work on this issue. I'm new to open source and this will be my first issue so it would be great if you could guide me through the process.
Thanks

**Comment by skjnldsv** [comment]
Hey @kshitizkashyap welcome! :)
Do you have specific knowledge on coding? On how to set up dev environments?
You can follow the [Join the team](https://github.com/nextcloud/server/#join-the-team-) section from our readme to have a working nextcloud setup on your local environment :rocket: 
Once done, I can guide you through the specific steps of this issue :tada: 
Ping me if you need anything :)

You can also join our public javascript channel here: https://cloud.nextcloud.com/call/k2svwwus

**Comment by kshitizkashyap** [comment]
Hey @skjnldsv 
Sorry for replying late. I have little knowledge in coding but no knowledge on how to set up dev environments. I have a design background. I was trying to setup the environment but couldn't do much progress.

**Comment by skjnldsv** [comment]
Hey :)
No worries!

What operating system do you use?
Here is our docs on how to set up the dev env https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html
You can ping me on irc if you want, We're on the channel #nextcloud-dev on freenode :)

**Comment by kshitizkashyap** [comment]
I'm currently using windows 10.
How do I login to the irc?

**Comment by skjnldsv** [comment]
You can probably setup the server on windows, but I have absolutely zero knowledge on this :/
You'll have to check for yourself :)
You can join irc via the webchat https://webchat.freenode.net/#nextcloud-dev
