### ISSUE TITLE
Error en unidad Nextcloud Desktop

### ISSUE THREAD

**Issue by Alexmanafan** [nextcloud/server#17779]
La aplicación Nextcloud Desktop muestra la unidad GB, en las carpetas cuando en realidad es en MB por ejemplo:

D:\Documents (146 GB)
cuando en realidad debería ser:
D:\Documents (146 MB)

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
