### ISSUE TITLE
Sidebar preview can't be clicked to open file if it is a pdf (but works for others)

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#17777]
In Nc 17.0.0 and before, you have nice previews of PDF's, even scroll-able, in the sidebar.

You can select text in them, but a click will not open them like with text files (preview even lets you scroll through them), images and Collabora/ONLYOFFICE documents.

Just updated a Nc 17 to daily (oct 31) on the updater to test, but there I can't get PDF previews to work, I'm afraid (probably local issue). I do notice that while with videos and images I can open the viewer by just clicking them, this doesn't work for text files.

**Comment by skjnldsv** [comment]
Fixed nc 20
