### ISSUE TITLE
Cancelling navigation to keep progress - visual bug

### ISSUE THREAD

**Issue by JonathanTreffler** [nextcloud/server#17786]
I want to contribute to [e-alfred/flowupload](https://github.com/e-alfred/flowupload/) and implement a "fix" for [Issue 66](https://github.com/e-alfred/flowupload/issues/66).

At first i thought this would be pretty easy. I just added following javascript code:
```javascript
window.addEventListener("beforeunload", function (e) {
    var confirmationMessage = 'If you proceed all pending uploads will get cancelled !';

    (e || window.event).returnValue = confirmationMessage;
    return confirmationMessage;
});
```

It kind of works:
The user gets asked properly and can select if he wants to stay or navigate away.
But if he clicks on an app icon in the navbar and then selects to stay the loading icon keeps spinning forever:
![image](https://user-images.githubusercontent.com/28999431/68084662-eb406380-fe38-11e9-9b10-f3219e2c198b.png)
The same applies to the dropdown menu under the account profile picture:
![image](https://user-images.githubusercontent.com/28999431/68084699-66097e80-fe39-11e9-98ba-9570402c27a1.png)

I have the following questions:

1.  Would a popup to stop a navigation violate any Nextcloud Design Guidelines ?
2. If it doesnt: Is this even a good idea ? It could annoy some users but others have said they want this feature ([in the issue at flowupload](https://github.com/e-alfred/flowupload/issues/66))
3. Is there any client side or server side API to implement this ?

**Comment by TessyPowder** [comment]
![image](https://user-images.githubusercontent.com/28999431/68705128-c90fb980-058d-11ea-8c8a-c252ea6fa228.png)

This issue also exists on the normal fileupload

**Comment by TessyPowder** [comment]
> This issue also exists on the normal file upload (tested on NC 16)

on Nextcloud 17 too

**Comment by TessyPowder** [comment]
@nextcloud/designers I don't think this is intended behavior.

**Comment by skjnldsv** [comment]
@TessyPowder you didn't use the appropriate issue templates, your issue is not having the appropriate visibility! :)

**Comment by TessyPowder** [comment]
> @TessyPowder you didn't use the appropriate issue templates, your issue is not having the appropriate visibility! :)

Ok. That's because It first was a question how to do navigation cancelling right , but now I think it's a big.

**Comment by TessyPowder** [comment]
> is not having the appropriate visibility!

How can i change that ?

**Comment by skjnldsv** [comment]
> How can i change that ?

I added the necessary labels

**Comment by TessyPowder** [comment]
Any Updates ?

**Comment by skjnldsv** [comment]
@TessyPowder this is a minor bug and unfortunately no one seems to have taken over it :)

**Comment by TessyPowder** [comment]
> @TessyPowder this is a minor bug and unfortunately no one seems to have taken over it :)

No problem :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by JonathanTreffler** [comment]
> Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

As far as I can tell there is no loading icon in the new Nextcloud 25 navbar, so the issue is indeed resolved :)

The code snippet in the initial bug report above works as expected with no visual bugs.
