### ISSUE TITLE
'occ app:enable appname' should make it clear that an app was already enabled

### ISSUE THREAD

**Issue by nodiscc** [nextcloud/server#17789]
### Steps to reproduce
1. Enable an already enabled app through `php ./occ app:enable appname`

### Expected behaviour
The command should succeed (return code 0) and return `appname already enabled` on the standard output.

### Actual behaviour
The command succeeds but returns `appname enabled`, exactly the same message as when the app was not previously enabled. This makes it difficult to determine if the command actually changed something and prevents using `occ` in an idempotent way in configuration management tools (ansible).

In this regard `app:disable appname` works as expected as it returns `No such app enabled: appname` when the app was already disabled. This makes it possible to detect that nothing was changed.

### Server configuration

**Operating system**: Debian GNU/Linux 10 Buster

**Web server:** Apache 2.4

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 17.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tarball at https://download.nextcloud.com/server/releases/nextcloud-17.0.0.zip

**Comment by kesselb** [comment]
```
Index: core/Command/App/Enable.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/Command/App/Enable.php	(revision 78d00ff0852a6199cc7ca33db6308f7bdd09b5a6)
+++ core/Command/App/Enable.php	(date 1572793732067)
@@ -98,6 +98,10 @@
 			return $group->getDisplayName();
 		}, $groupIds);
 
+		if ($this->appManager->isInstalled($appId)) {
+			$output->writeln($appId . ' already enabled');
+			return;
+		}
 
 		try {
 			/** @var Installer $installer */
```

Sounds good to me. Something like above should do the trick.

**Comment by sndrr** [comment]
I've added a PR. It also checks for group parameters, since that setting will impact the output.
