### ISSUE TITLE
Prioritize sync of a folder that is currently open in a client

### ISSUE THREAD

**Issue by manuel-tiedtke** [nextcloud/server#17791]
## Problem
In case a lot of files are still to be synchronized, it can take a really long time to get some specific files pushed to the server, that are needed asap on another device.

## Solution
Allow clients (iOS/Android app, etc.) to trigger immediate synchronization of directories that are currently open in them.

## Example Scenario
I add some files to a folder on my desktop, with the Nextcloud sync client installed. I want to have those files as fast as possible available on my iPad with the Nextcloud client installed. Thus if I move to the folder with the new files, on the iPad client, Nextcloud on the desktop should be notified to push the synchronization of that folder to the beginning of its sync queue.

**Comment by kesselb** [comment]
cc @nextcloud/desktop @nextcloud/android @nextcloud/ios

**Comment by jospoortvliet** [comment]
Ah, so say there's a gb of files being synced, you'd want those files to go first that are in the folder you open on another client?

While I understand the benefit, I do see a few problems, so just to ehrm temper expectations:
* the sync engine is super complicated. Changing something like this is a major undertaking, similar to adding E2E or a virtual drive. As you might know, neither is finished yet, and both are projects that started over a year ago
* this is a relatively rare scenario. The sync clients already push all new files immediately, and we are working on ways to speed up the response times of sync clients, so it really only helps when there is a BIG sync happening with lots and lots of files.

The combination of relatively small benefit and HUGE time investment on server AND clients all over means I don't think this will be done until we are the size of facebook and can put 5 people on this for 6 months even though it is a minor thing :1st_place_medal:

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
