### ISSUE TITLE
ShareLink shown in sidebar, despite public sharing being disabled

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#17799]
On current master. The sidebar show the "Share link" item, despite sharing publicly is disabled:

![Screenshot_20191104_151746](https://user-images.githubusercontent.com/2184312/68127503-5318ac00-ff16-11e9-8c5c-a21f9525600a.png)

And the error message is very generic and not helpful

![Screenshot_20191104_151831](https://user-images.githubusercontent.com/2184312/68127538-5f046e00-ff16-11e9-8034-7ff5584e9408.png)

Best to not show the option in this case.

**Comment by rullzer** [comment]
PR in #18672
