### ISSUE TITLE
Server stucks at manual login.

### ISSUE THREAD

**Issue by Quving** [nextcloud/server#17798]
### Steps to reproduce
1. Setup Nextcloud using the official docker image with 'latest' or '17' docker-image tag.
2. Logout and provide your login credentials and hit the login button.
3. 

### Expected behaviour
Usually you would proceed and get the view of your files.

### Actual behaviour
The user stucks at the login screen. I found that force reloading the website ensures the expected behaviour.

<img width="491" alt="Screenshot 2019-11-04 at 12 27 13" src="https://user-images.githubusercontent.com/15371515/68120956-7899bb80-fefe-11e9-9f31-276091b0d80e.png">

### Server configuration
Ubuntu 16 with docker-ce (latest) and the latest nextcloud official image.
**Operating system**: Linux

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Quving** [comment]
Ofcourse. The log can be retrieved from the following screenshot.


By the way, It does not work on Google-Chrome. But using Safari it works as expected.

![image](https://user-images.githubusercontent.com/15371515/68124513-7f78fc00-ff07-11e9-8edc-747d013fcdef.png)

**Comment by kesselb** [comment]
1) About nextcloud and reverse proxies in general: https://docs.nextcloud.com/server/17/admin_manual/configuration_server/reverse_proxy_configuration.html

2) Some pitfalls with the current docker image: https://github.com/nextcloud/docker/pull/819#issuecomment-541434657

The login form action points to `http://nextcloud.yourdomain.com` but should be `https://nextcloud.yourdomain.com`. Nextcloud fails to detect the right information (protocol and/or hostname) from the reverse proxy.
