### ISSUE TITLE
Empty response to get list of users by php curl

### ISSUE THREAD

**Issue by mehran7880** [nextcloud/server#17790]
If I have a bad English, sorry I'm trying to get a list of users from nextcloud using php curl. But i got empty response, even with curl_error I checked the error of curl but it didn't make any Error. I did a lot of searching and was even able to add user with add user api. But I couldn't get the list of users.
`
                         // Login Credentials as Admin
                         $ownAdminname = 'admin';
                         $ownAdminpassword = 'admin';

                        // Add data, to owncloud post array and then Send the http request for creating a new user
                        $url = 'http://' . $ownAdminname . ':' . $ownAdminpassword . '@cloud.local/ocs/v1.php/cloud/users';

                        $ownCloudPOSTArray = array();

                        $ch = curl_init($url);
                        curl_setopt($ch, CURLOPT_POST, 1);
                        curl_setopt($ch, CURLOPT_POSTFIELDS, $ownCloudPOSTArray);
                        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
                        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
                            'Content-Type: application/x-www-form-urlencoded',
                            'OCS-APIRequest: true'
                        ));
                        $response = curl_exec($ch);
                        echo "response: " . $response;
                        curl_close($ch);
                        die();
`
i ask this question in stackoverflow too:
https://stackoverflow.com/questions/58681773/empty-response-to-get-list-of-users-by-php-curl
please tell me where i was wrong. tanks

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
