### ISSUE TITLE
Implement JMAP proxy

### ISSUE THREAD

**Issue by mw80** [nextcloud/server#17802]
JMAP protocol might be the next step for mail server communication.
Nextcloud could act as JMAP proxy.
https://jmap.io/software.html

**Comment by jaudriga** [comment]
We are working on a JMAP app for nextcloud. @mw80 what would be your use case?

**Comment by mw80** [comment]
My use case would be to "hide" the mail server (e.g. dovecot, postfix, etc.) behind nextcloud. No requirement to open ports 143, 25, etc. Use the security features/authentication from nextcloud.

**Comment by tverbeke** [comment]
@jaudriga any repository we can follow to see progress and/or contribute?

**Comment by jaudriga** [comment]
@tverbeke I will post it here as soon as we have an initial version that we deem ready for the general public

**Comment by jaudriga** [comment]
We have published an initial version of our JMAP App for Nextcloud at https://github.com/audriga/nextcloud-jmap .

While we want to leave the door open for JMAP for Mail support in the future, our current focus is not on mail but on [JMAP for Contacts](https://jmap.io/spec-contacts.html) and [JMAP for Calendars](https://jmap.io/spec-calendars.html). These protocols are meant as an alternative to CardDAV/CalDAV. Feel free to leave some feedback or take a look around.

**Comment by szaimen** [comment]
Thanks for the request and thanks for developing the nextcloud-jmap app!
Please head over to its repository for further enhanvements regarding this request. 
Thank you!
