### ISSUE TITLE
Have the data folder out of the web root by default

### ISSUE THREAD

**Issue by forty** [nextcloud/server#17809]
According to https://docs.nextcloud.com/server/13/admin_manual/configuration_server/harden_server.html:
```
It is highly recommended to place your data directory outside of the Web root (i.e. outside of /var/www). It is easiest to do this on a new installation.
```
It seems an obvious thing to do, as it seems to me there is no real advantage do have the data folder in /var/www/ by default

**Comment by kesselb** [comment]
I'm not sure if we can change this upstream. For some configurations it's not possible to put files outside the document root / nextcloud folder. If another place is reasonable for the docker image do it ;)

**Comment by szaimen** [comment]
Based on kesselb's comment I am closing this since for some configurations it might not be possible to put files outside the document root / nextcloud folder.
