### ISSUE TITLE
NC17 Unable to generate a URL for the named route "ocs.provisioning_api.AppsController.disable"

### ISSUE THREAD

**Issue by anjoze** [nextcloud/server#17815]
### Steps to reproduce
1. Enable App Announcements

### Expected behaviour
Nothing on Logs

### Actual behaviour
It creates a new log entry every +- 30 seconds with this content:

[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "ocs.provisioning_api.AppsController.disable" as such route does not exist. at <<closure>>

 0. /var/www/html/cmacloud/lib/private/Route/Router.php line 337
    Symfony\Component\Routing\Generator\UrlGenerator->generate("ocs.provisionin ... e", {app: "nextcloud_announcements"}, 1)
 1. /var/www/html/cmacloud/lib/private/Route/CachingRouter.php line 60
    OC\Route\Router->generate("ocs.provisionin ... e", {app: "nextcloud_announcements"}, false)
 2. /var/www/html/cmacloud/lib/private/URLGenerator.php line 95
    OC\Route\CachingRouter->generate("ocs.provisionin ... e", {app: "nextcloud_announcements"}, false)
 3. /var/www/html/cmacloud/apps/nextcloud_announcements/lib/Notification/Notifier.php line 116
    OC\URLGenerator->linkToOCSRouteAbsolute("provisioning_api.AppsController.disable", {app: "nextcloud_announcements"})
 4. /var/www/html/cmacloud/lib/private/Notification/Manager.php line 253
    OCA\NextcloudAnnouncements\Notification\Notifier->prepare(OC\Notification\Notification {}, "pt_PT")
 5. /var/www/html/cmacloud/apps/notifications/lib/Controller/EndpointController.php line 102
    OC\Notification\Manager->prepare(OC\Notification\Notification {}, "pt_PT")
 6. /var/www/html/cmacloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Notifications\Controller\EndpointController->listNotifications("v2")
 7. /var/www/html/cmacloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Notification ... {}, "listNotifications")
 8. /var/www/html/cmacloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notification ... {}, "listNotifications")
 9. /var/www/html/cmacloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Notificati ... r", "listNotifications", OC\AppFramework\ ... {}, {apiVersion: "v2 ... "})
10. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({apiVersion: "v2 ... "})
11. /var/www/html/cmacloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {apiVersion: "v2 ... "})
12. /var/www/html/cmacloud/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/apps/no ... s")
13. /var/www/html/cmacloud/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/html/cmacloud/ocs/v1.php")

GET /ocs/v2.php/apps/notifications/api/v2/notifications
from 10.20.16.23 by 1F12E88D-60C7-4AEE-874C-2A180E24D844 at 2019-11-05T09:45:58+00:00

### Server configuration

**Operating system**:
Ubuntu 18.04 LTS
**Web server:**
Nginx
**Database:**
MariaDB Galera Cluster

**PHP version:**
7.3.10
**Nextcloud version:** (see Nextcloud admin page)
17
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 16

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - drawio: 0.9.4
  - external: 3.4.1
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - groupfolders: 5.0.4
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_detection: 0.6.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - socialsharing_email: 1.0.6
  - support: 1.0.1
  - systemtags: 1.7.0
  - terms_of_service: 1.3.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.1.0
  - w2g2: 3.0.0
  - workflowengine: 1.7.0
Disabled:
  - contacts
  - encryption
  - files_external
  - firstrunwizard
  - mail
  - spreed
  - survey_client
</details>

**Comment by j-ed** [comment]
The Nextcloud [help forum](https://help.nextcloud.com/search?q=Unable%20to%20generate%20a%20URL%20for%20the%20named%20route%20%22ocs.provisioning_api.AppsController.disable) is the right place to address this kind of problems first. As you can see that problem has already been addressed there which resulted in the following [issue ticket](https://github.com/nextcloud/nextcloud_announcements/issues/54).

**Comment by anjoze** [comment]
Yes, is the same problem.
Thank you
