### ISSUE TITLE
NextCloud Coockie Banner

### ISSUE THREAD

**Issue by JanDragon** [nextcloud/server#17812]
Hey,

I am requesting a NextCloud Coockie Banner. It’s important for Websites in Europe. So also NextCloud should have it. It’s ok if you can enable and disable it in the Config and set a link or text for the Coockie Banner. That’s would be awesome and for me and I think also for other people very important. 

JanDragon

**Comment by j-ed** [comment]
As already discussed here: https://help.nextcloud.com/t/nextcloud-cookie-banner/63180

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/16453
https://github.com/nextcloud/server/issues/15028

May the search be with you ;)
