### ISSUE TITLE
[admin_audit] log file IDs

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#17823]
**Is your feature request related to a problem? Please describe.**
admin_audit logs file names and paths. However, when a sharee opens or modifies a file that's shared with them, the sharee's own path gets logged.

**Describe the solution you'd like**
I'd like to have the file ID also logged on all audited file operations, so I can get a conststent audit trail for a specific file.

**Comment by jospoortvliet** [comment]
I recall @nickvergessen and @ChristophWurst recently made some changes in this area, perhaps after 19 is out this can be added relatively quickly - it can't be that complicated @rullzer

**Comment by nickvergessen** [comment]
The problem is that all of the hooks don't contain the file id

**Comment by szaimen** [comment]
Based on nickvergessen's comment it doesn't look like this idea is feasible.
Please reopen if you still want to implement this. Thanks!
