### ISSUE TITLE
Checkbox glitch in user management

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1782]
When the checkbox is checked, it moves to the left:
![capture du 2016-10-18 16-21-50](https://cloud.githubusercontent.com/assets/925062/19481691/1c14c16e-954f-11e6-9c55-9f65a9fe8322.png)

cc @Henni @juliushaertl @nextcloud/designers :)

**Comment by spot1000** [comment]
I'll take this one on if no one else has it.
