### ISSUE TITLE
files:scan does not update activity tab (inform users..)

### ISSUE THREAD

**Issue by ExaconAT** [nextcloud/server#17820]
We have a big NC Setup with about 500 Users, we use a 3rd party tool for digitaly stamping PDF's.

Those PDF's are shared from the admin account via "folder sharing" to all Users (different PDF's per User).

Now we ran into the problem that our local davfs2 connection to the nextcloud instance became very slow and now we have to work on file system level.

We are digitaly stamping the pdf's and copying the files via a Java application, now on file level (dir -> java app -> nc data dir - (admin user)). This runs very good now because it's a huge speed improvement (webdav using davfs2 with 800k+ files and 400+ folders is simply a bad joke).

We are syncing the files with files:scan admin, but now we run into the problem that the users (every user has a shared root folder) wont get an information if they receive a new PDF (activity app wont update).

Is there any solution that a file:scan triggers the activity app and shows "new file" @ date - time?

Thank you!

**Comment by szaimen** [comment]
Sorry, this is more of a support question than a bug report. And that means you should either ask help from the volunteers on the forum at [help.nextcloud.com](help.nextcloud.com) (who can help you debug and turn it in a bug report if it is a bug) or, if this is important for your business, get a [Nextcloud subscription](https://nextcloud.com/pricing/) and we help you fix it in a few hours or days (according to the SLA).
