### ISSUE TITLE
Previews of text files looks a bit weird

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#17828]
It might just be the demo text file but this looks weird to me in the preview pane of the sidebar.

![preview](https://user-images.githubusercontent.com/45821/68283758-6f365d80-007c-11ea-93f4-92b616744533.png)

@skjnldsv @jancborchardt @danxuliu

**Comment by jancborchardt** [comment]
Yup, the text is much too big and is cut off half. Also, can we make it wrap instead of overflow to the right?

**Comment by skjnldsv** [comment]
@jancborchardt it's a picture

**Comment by Gatak** [comment]
It's indeed a picture, but it could be generated better with different settings. I think it is Imagick that does it...

**Comment by jancborchardt** [comment]
@Gatak do you have more info on that, or do you want to look into the options? :)

**Comment by Gatak** [comment]
Not sure how it's done in NC, but I will assume Imagemagick.

You an choose two options; `-label` and `-caption`. Label renders according to `-pointsize` and `-size`, whereas Caption tries to fit all text into the target size image by automatically adjust font size.

I think label is most sensible. Just have to choose a good size, pointsize and font to use.

Here is one example. 
```
cat goria.htm |convert -size 500x500
 -fill black -font Helvetica  -pointsize 9 label:@- goria.png
```

![goria](https://user-images.githubusercontent.com/1469150/71592197-9c106980-2b2f-11ea-90b0-3144463cbb9c.png)


http://www.imagemagick.org/Usage/text/#label_lines

**Comment by juliushaertl** [comment]
The text preview is constructed here: https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/private/Preview/TXT.php#L55-L105 

The main issue is that we cannot generate different text sizes depending on the preview size since all preview images are generated from one image that is produced at the maximum preview size of 4096px width. We can adjust the font size to something smaller, but that will also have impact on the small thumbnails:

![image](https://user-images.githubusercontent.com/3404133/71598247-72167180-2b46-11ea-838f-e9656ea6ef05.png)

I also looked more into options for generating rendered markdown previews (for https://github.com/nextcloud/text/issues/23) but I' afraid I haven't found a way to get an image of the rendered text without non-php 3rdparty software.

In my opinion it would still be the best to allow apps like text to register their preview provider in the frontend, just as it was with the old sidebar. With this the text app could just render the markdown as HTML into the DOM and we would have the same display as in the text app itself.

cc @skjnldsv @rullzer

**Comment by Gatak** [comment]
Why do we want previews of text files anyway? Thinking a little about the purpose might perhaps help choose better defaults.

> In my opinion it would still be the best to allow apps like text to register their preview provider in the frontend

Probably a very good option.

**Comment by jancborchardt** [comment]
> Why do we want previews of text files anyway?

Previews are always to get a feel for what the file is, and globally to where you are in the list as it gives you a sense of space. Previews make sense for text files as much as they do for image files or e.g. in email or chat apps where you see the beginning of the message. You get a rough idea of what it is.

**Comment by skjnldsv** [comment]
> In my opinion it would still be the best to allow apps like text to register their preview provider in the frontend, just as it was with the old sidebar. With this the text app could just render the markdown as HTML into the DOM and we would have the same display as in the text app itself.

Pandora box :)
If we do that, we'll go back to the other issues where providers can register crazy things. What if your txt file is over 10MB ?
What about potential xss from files? Injecting user content is always a risk :/
I'd prefer having a proper preview generation service working in the background (like an a docker container) than a custom setup for each provider making the sidebar difficult to maintain :)

**Comment by juliushaertl** [comment]
> What about potential xss from files? Injecting user content is always a risk :/

I generally agree, but for the text example this would also mean that we should not open files for editing in general. 

> If we do that, we'll go back to the other issues where providers can register crazy things. What if your txt file is over 10MB ?

Same as with opening/editing. The app could make sure to not display the preview, load only a chunk of the file or or fallback to the image preview.

> I'd prefer having a proper preview generation service working in the background (like an a docker container) than a custom setup for each provider making the sidebar difficult to maintain :)

Yes, that would be great of course. We still should make sure that the out of the box experience is nice :wink: The current generated text file preview is neither nice nor really useful at all imo.

**Comment by skjnldsv** [comment]
> Same as with opening/editing. The app could make sure to not display the preview, load only a chunk of the file or or fallback to the image preview.

works for text files, but not pdf or others for example.
So it's either we go full in or none at all unfortunately :/

> Yes, that would be great of course. We still should make sure that the out of the box experience is nice  The current generated text file preview is neither nice nor really useful at all imo.

I'm sure adjusting the default generation can be already a great improvement
