### ISSUE TITLE
Notification icon is not inverted on first load when using a light theme color

### ISSUE THREAD

**Issue by small1** [nextcloud/server#17839]
### Steps to reproduce
1. Set the color to for example f2f2f2 
2. do a hard reload
3. icon will be white for a while until a background job is finished then it will be dark as all the others.

### Expected behaviour
Icon should be dark directly

### Actual behaviour
Icon is white for an small amount of time

![Screenshot from 2019-11-06 16-48-51](https://user-images.githubusercontent.com/317830/68314512-90b43b00-00b6-11ea-9676-8b6d62b2bfe5.png)

### Server configuration

**Operating system**: debian 9

**Web server:** nginx

**Database:** mariadb

**PHP version:** 7.2

**Nextcloud version:** 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 16.0.5 problems is probably on the old one as well

**Where did you install Nextcloud from:** github

**Signing status:**
<details>

### Client configuration
**Browser:** chrome   77.0.3865.90

**Operating system:** Ubuntu 18.04

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.2

cc @nextcloud/javascript does this need to be fixed in the server repository or in the notifications repostiory?

**Comment by juliushaertl** [comment]
I guess that should be solved by https://github.com/nextcloud/notifications/pull/946 with 22.
