### ISSUE TITLE
NextCloud website news RSS invalid XML

### ISSUE THREAD

**Issue by groentebroer** [nextcloud/server#1783]
Sorry if this is not the place to report this, but I could not find where to report it otherwise....

### Steps to reproduce
1. Validate the NextCloud news RSS in an RSS validator: [https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnextcloud.com%2Fblogfeed%2F](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fnextcloud.com%2Fblogfeed%2F)

### Expected behaviour
Should be valid

### Actual behaviour
XML is invalid.
(Causing not being able to use the feed in the NextCloud news plugin!)

### Server configuration
Not applicable

### Client configuration
Not applicable

### Logs
Not applicable
#### Web server error log
Not applicable

#### Nextcloud log (data/nextcloud.log)
Not applicable

#### Browser log
Not applicable

**Comment by nickvergessen** [comment]
Created an issue in our website repo: https://github.com/nextcloud/nextcloud.com/issues/204

**Comment by Artigan** [comment]
the pb is still here for https://nextcloud.com/blog/static-feed/
