### ISSUE TITLE
Quota 0B can be bypassed by copy from group folder or share

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#17836]
### Steps to reproduce
1. Login as admin
2. Create user _Alice_ with quota 0B, add to group _users_
3. Create folder X and share it with _Alice_
4. Create group folder Y and allow Alice's group _users_ to it
3. Login as _Alice_
4. see _You don’t have permission to upload or create files here_ on root folder
5. navigate into folder X
6. right-click on any file and copy it to the root directory

### Expected behaviour
An error prevents copying the file into the root folder, since the quota is expired.

### Actual behaviour
The file gets successfully copied.
Same goes for moving.
Same goes for copying/moving from shared folders into the root directory.

### Server configuration

**Nextcloud version:**

- 16.0.5
- 17.0.0

**Comment by wiswedel** [comment]
initially reported by @felixlutze

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
