### ISSUE TITLE
Webdav error from multifunction printer

### ISSUE THREAD

**Issue by gerla** [nextcloud/server#17842]
#Error LOG

Sabre\DAV\Exception\NotAuthenticated: No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Bearer' header found. Either the client didn't send one, or the server is mis-configured

    <<closure>>
    Sabre\DAV\Auth\Plugin->beforeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})
    /usr/share/nginx/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:
    call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])
    /usr/share/nginx/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 466:
    Sabre\Event\EventEmitter->emit("beforeMethod", [ Sabre\HTTP ... }])
    /usr/share/nginx/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})
    /usr/share/nginx/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:
    Sabre\DAV\Server->exec()
    /usr/share/nginx/nextcloud/remote.php - line 163:
    require_once("/usr/share/ ... p")

### Steps to reproduce
1. Clean install of nextcloud 17 on ubuntu 18.04 and LEMP stack
2. Configure webdav on multifunction device (in my case canon printer)

### Expected behaviour
Expected file transfer from multifunction to server

### Actual behaviour
I find a 0Kb pdf file
Trought web interface or external webdav clients (like cyberduck) the file transfer completes successfully
If i try the same configuration with a demo cloud istance of nextcloud from the same printer the transfer completes successfully

### Server configuration

Ubuntu 18.04

nginx

mariaDB

php 7.2

nextcloud 17

fresh install

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.



**List of activated apps:**
Enabled:
  - accessibility: 1.3.0
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - text: 1.1.0
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.1.0
  - workflowengine: 1.7.0
Disabled:
  - activity
  - comments
  - encryption
  - federation
  - files_external
  - files_trashbin
  - firstrunwizard
  - gallery
  - nextcloud_announcements
  - notifications
  - recommendations
  - sharebymail
  - systemtags
  - unsplash
  - user_ldap


**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.domain.com",      
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.0.9",
        "overwrite.cli.url": "https:\/\/nextcloud.domain.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "maintenance": false,
        "logfile": "\/var\/log\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": "0",
        "logdateformat": "F d, Y H:i:s"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

**Comment by gerla** [comment]
I also tried with a fresh install with snap package, exactly same behavior

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

Thanks ;) Please ensure that your are using the nginx configuration from the docs.
