### ISSUE TITLE
16.0.6 OC_VersionString in version.php reports wrong version

### ISSUE THREAD

**Issue by MAGICCC** [nextcloud/server#17849]
### Steps to reproduce
1. Download the 16.0.6 zip file ` wget https://download.nextcloud.com/server/releases/nextcloud-16.0.6.zip`

2. Unzip version.php and grep for VersionString 
`unzip -j nextcloud-16.0.6.zip nextcloud/version.php -d . && cat version.php | grep "VersionString"`

```bash
unzip -j nextcloud-16.0.6.zip nextcloud/version.php -d . && cat version.php | grep "VersionString"
Archive:  nextcloud-16.0.6.zip
  inflating: ./version.php
$OC_VersionString = '16.0.6 RC1';
```
 3. tar.bz2 affected too

### Expected behaviour
Shouldn't have RC1 in the string since it's a stable release and not a release candidate

### Actual behaviour
It has RC1 in the string

**Comment by pm-pm** [comment]
Thanks for that Information. I am only offered:

DropBox 16.0.5
Eine neue Version ist verfügbar: Nextcloud 16.0.6 RC1

**Comment by Thom1b** [comment]
Same issue here. The question is : is this release is really the stable 16.0.6 version with a bad string version, or is this the real 16.0.6rc1 version ?

**Comment by MAGICCC** [comment]
@Thom1b I hope it's only a bad string

**Comment by kesselb** [comment]
Archive ships the right `version.php` since 2019-11-07T22:22:16+00:00.
