### ISSUE TITLE
Calendar not loading correctly in 17.0.0 and 17.0.1

### ISSUE THREAD

**Issue by ChipwizBen** [nextcloud/server#17855]
### Steps to reproduce
1. Update to 17.0.x
2. Check then calendar view
3. Observe that none of the calendar entries load on the calendar to the right, and the list of calendars is replaced by a spinning loading circle

### Expected behaviour
Tell us what should happen

Calendar entries should load on the right, and available calendars should display in the left

### Actual behaviour
Tell us what happens instead

Calendar entries do not load on the right, and available calendars on the left are replaced with spinning loading signs

### Server configuration

**Operating system**: CentOS 7, up to date

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.2u

**Nextcloud version:** (see Nextcloud admin page)
17.0.0 / 17.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
16.0.1 / 16.0.5
**Where did you install Nextcloud from:**
Zip
**Signing status:**
<details>
<summary>Signing status</summary>

"No errors have been found."
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - oauth2: 1.5.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - notifications
  - password_policy
  - recommendations
  - sharebymail
  - support
  - survey_client
  - updatenotification
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "a",
            "b",
            "c"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "logtimezone": "NZST",
        "logfile": "\/tmp\/nextcloud_log",
        "log_authfailip": true,
        "log_rotate_size": "10 MB",
        "mail_smtpmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "30",
        "updatechecker": false,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "htaccess.RewriteBase": "\/",
        "overwrite.cli.url": "https:\/\/data.nwk1.com",
        "mail_sendmailmode": "smtp"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "15826"
        },
        "bruteforcesettings": {
            "enabled": "no",
            "installed_version": "1.4.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.7.1",
            "types": ""
        },
        "checksum": {
            "enabled": "no",
            "installed_version": "0.4.3",
            "types": "filesystem"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "compress": {
            "enabled": "no",
            "installed_version": "1.5",
            "types": ""
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.6",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "global_cache_gc_lastrun": "1436329144",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1393883818.2565",
            "lastcron": "1573188302",
            "lastupdateResult": "{\"version\":\"16.0.5.1\",\"versionstring\":\"Nextcloud 16.0.5\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/releases\\\/nextcloud-16.0.5.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/server\\\/16\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https:\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=16.0.5\",\"autoupdater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "0",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_mozilla_sync": "mozilla_sync\/appinfo\/remote.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "a7f88bd5973e21609e54f561c7c999c6",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "theming.variables": "a7f88bd5973e21609e54f561c7c999c6",
            "updater.secret.created": "1504661759",
            "vendor": "nextcloud"
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.9.0",
            "ocsid": "168711",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "900",
            "backgroundwatcher_previous_folder": "4302",
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_mv": {
            "enabled": "no",
            "installed_version": "0.8.2",
            "ocsid": "150271",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem,dav"
        },
        "files_tree": {
            "enabled": "no",
            "installed_version": "0.8.0",
            "types": ""
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "1.0",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.4.0",
            "types": ""
        },
        "gpxpod": {
            "enabled": "no",
            "installed_version": "2.2.2",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "metadata": {
            "enabled": "no",
            "installed_version": "0.10.0",
            "types": ""
        },
        "mozilla_sync": {
            "enabled": "no",
            "installed_version": "1.4",
            "ocsid": "161793",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "no",
            "installed_version": "1.5.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "no",
            "installed_version": "2.4.1",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": ""
        },
        "phonetrack": {
            "enabled": "no",
            "installed_version": "0.5.2",
            "types": ""
        },
        "piwik": {
            "enabled": "no",
            "installed_version": "0.2.0",
            "internal": "no",
            "piwik": "{\"siteId\":\"3\",\"url\":\"piwik\/\",\"validity\":86400}",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "readableLocation": "nz",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.4.0",
            "types": ""
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "spreed": {
            "enabled": "no",
            "installed_version": "6.0.4",
            "project_access_invalidated": "1",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "storage_charts": {
            "enabled": "no",
            "installed_version": "2.2",
            "types": ""
        },
        "support": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "survey_client": {
            "enabled": "no",
            "installed_version": "1.4.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.8",
            "ocsid": "164356",
            "types": ""
        },
        "tasks_enhanced": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "11",
            "color": "#2f2f2f",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "logoMime": "image\/png",
            "name": "data.nwk1.com",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "updatenotification": {
            "bruteforcesettings": "1.4.0",
            "calendar": "1.7.1",
            "checksum": "0.4.3",
            "contacts": "3.1.6",
            "core": "16.0.5.1",
            "enabled": "no",
            "files_pdfviewer": "1.2.1",
            "files_rightclick": "0.15.1",
            "installed_version": "1.6.0",
            "metadata": "0.10.0",
            "phonetrack": "0.5.2",
            "spreed": "3.2.6",
            "theming": "1.4.5",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.4",
            "ocsid": "166059",
            "types": ""
        },
        "user_external": {
            "installed_version": "0.7.0",
            "types": "prelogin,authentication"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** NFS

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox / CalDAV clients

**Operating system:** Fedora 30 / Android

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
[root@data ~]# tail -f /var/log/httpd/error_log
[Thu Nov 07 22:55:56.654895 2019] [mpm_prefork:notice] [pid 10308] AH00170: caught SIGWINCH, shutting down gracefully
[Thu Nov 07 22:56:12.173352 2019] [core:notice] [pid 1162] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Thu Nov 07 22:56:12.175397 2019] [suexec:notice] [pid 1162] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Thu Nov 07 22:56:12.178721 2019] [ssl:warn] [pid 1162] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Thu Nov 07 22:56:12.200720 2019] [lbmethod_heartbeat:notice] [pid 1162] AH02282: No slotmem from mod_heartmonitor
[Thu Nov 07 22:56:12.202644 2019] [ssl:warn] [pid 1162] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Thu Nov 07 22:56:12.282526 2019] [mpm_prefork:notice] [pid 1162] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/7.2.24 configured -- resuming normal operations
[Thu Nov 07 22:56:12.282556 2019] [core:notice] [pid 1162] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
libpng warning: Interlace handling should be turned on when using png_read_image
libpng warning: Interlace handling should be turned on when using png_read_image
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
[root@data ~]# cat /tmp/nextcloud_log
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":2,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"OC\\Log\\Rotate","method":"","url":"--","message":"Log file \"\/tmp\/nextcloud_log\" was over 10 MB bytes, moved to \"\/tmp\/nextcloud_log.1\"","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Log\\Rotate job with ID 20288 in 0 seconds","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\DAV\\BackgroundJob\\EventReminderJob job with ID 21090","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\DAV\\BackgroundJob\\EventReminderJob job with ID 21090 in 0 seconds","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OCA\\Text\\Cron\\Cleanup job with ID 21091","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"text","method":"","url":"--","message":"Run cleanup job for text sessions","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"text","method":"","url":"--","message":"Removed 0 inactive sessions","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OCA\\Text\\Cron\\Cleanup job with ID 21091 in 0 seconds","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Run OC\\Core\\BackgroundJobs\\CleanupLoginFlowV2 job with ID 20397","userAgent":"--","version":"17.0.1.1"}
{"reqId":"qCebCvjCyFGxMHzuCoZ9","level":0,"time":"2019-11-08T17:00:01+12:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"Finished OC\\Core\\BackgroundJobs\\CleanupLoginFlowV2 job with ID 20397 in 0 seconds","userAgent":"--","version":"17.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ChipwizBen** [comment]
Adding for clarity that CalDAV clients don't work either. The issue is not limited to the UI.

**Comment by BernieO** [comment]
I can't reproduce the issue on two instances I upgraded to 17.0.1 (haven't tried 17.0.0). The calendar-app just works fine: all calendars and events are displayed in the Nextcloud calendar app.
Also caldav clients work as expected (Mac OS X 10.15 calendar and iOS 13.2)

Have you tried to clear the browser cache (won't help for webdav-clients though)?

I think this issue should be moved to the calendar-repo @georgehrke

**Comment by ChipwizBen** [comment]
Yes, I've even tried a separate browser completely. I've seen a similar issue before where some database columns were missing and had to be manually added, but nothing is showing in the log for that. Nothing relevant seems to make it to the log at all.

**Comment by tanghus** [comment]
I can confirm this. I reported it at [help.nextcloud.com](https://help.nextcloud.com/t/calendar-exception-object-already-exists/67496), where the details are.

The js console gives: `Error: Same occurrence found twice, protecting you from death by recursion vendor.js:41295:14.`

I tried removing cache and cookies for my domain, but that didn’t help.

There is nothing related in the NC log.

I’m on NC 17.0.1 using PHP 7.3.11, MySQL 10.2.29 and Apache, dunno which version, as I’m on shared hosting.

I can download the calendar from the web UI, so all is not lost, but I can't sync, so this is a critical bug!

**Comment by tanghus** [comment]
@BernieO 

> I think this issue should be moved to the calendar-repo

I don't think there is a separate calendar repo anymore?

**Comment by tanghus** [comment]
I do get some errors under dev tools/network:

![image](https://user-images.githubusercontent.com/533222/72232039-ffce7400-35be-11ea-9a84-10ac3eaf9c1f.png)

**Comment by go2sh** [comment]
CSP error on all requests following the main page smells like a configuration issue somehow.

**Comment by tanghus** [comment]
Any idea where? Though I don't think it is the issue for the calendar error. I haven't changed the configuration for a long time.

**Comment by BernieO** [comment]
@tanghus 

> > I think this issue should be moved to the calendar-repo

>I don't think there is a separate calendar repo anymore?

I meant the [repository of Nextclouds calendar app](https://github.com/nextcloud/calendar), since I thought it is a problem with that app. But after seeing all those CSP errors I am not so sure anymore...

**Comment by tanghus** [comment]
I don't know why I thought that repo was closed..? @ChipwizBen do you have the same errors?

**Comment by go2sh** [comment]
Did you check, that it is the latest calendar app? There is an XML file inside the app folder and compare it with the store version. Maybe its not up to date.

**Comment by tanghus** [comment]
> Did you check, that it is the latest calendar app? There is an XML file inside the app folder and compare it with the store version. Maybe its not up to date.

Same version 1.7.2

> Also the Calendar App and the CalDAV backend are split. The calendar app has its own repository (nextcloud/calendar) and the CalDAV backend is in the server.

Ah, that's why I thought it was closed.

**Comment by georgehrke** [comment]
@tanghus Can you please check the Nextcloud.log? I suspect two different issues here:
- If sync clients stop working, it's most likely related to some server error (some error 500).
- That `Error: Same occurrence found twice, protecting you from death by recursion vendor.js:41295:14.` error is thrown by ical.js to protect from you infinite loops. It seems like some recurrence rule in an event is maybe not standard compliant.

**Comment by tanghus** [comment]
Hi @georgehrke :) Nada in the log concerning calendar. Some entries from OCA\Social and news, that's it. The log is set to report Warning|Error|Fatal.

**Comment by tanghus** [comment]
Now on NC 17.0.1 and Calendar 2.0.2 the calendars load fine except for an external holiday calendar I use, but that may very well just be a broken source.
So this can be closed I guess?

**Comment by the-moog** [comment]
I have this issue too.  Calendars just enabled (never enabled before) so no events in the calendars.
