### ISSUE TITLE
The update notification app freezes NC when the update server is heavily used   

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#17868]
The update for NC16 and NC 17 was just released. As a consequence the download server is heavily loaded. This can be shown by a very slow response when going to the download page at  https://nextcloud.com/install/#instructions-server

Now it takes a very long time for my own NC server to respond. After deactivating the Update_notification app, the server responds normally. 

We have seen this before. see https://github.com/nextcloud/server/issues/17128

It only happens for admins. 

NC16.0.5, Ubuntu 18.0.4

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure

**Comment by szaimen** [comment]
I think there were some caching improvements in this part of the code. -> closing.
Please reopen if you can still reproduce this! Thanks! :)
