### ISSUE TITLE
Changelog for 16.0.6 and 17.0.1 missing 

### ISSUE THREAD

**Issue by Bubu** [nextcloud/server#17869]
It's not here: https://nextcloud.com/changelog/
:-(

Oh and this time I did force-reload the page... (ref #14087)

**Comment by kesselb** [comment]
[15.0.13](https://github.com/nextcloud/server/pull/17723)
[16.0.6](https://github.com/nextcloud/server/pull/17722)
[17.0.1](https://github.com/nextcloud/server/pull/17721)

**Comment by stondino00** [comment]
Nothing has been officially released on the blog or GA change-log page so I don't believe these releases are going to be final due to current issues list.  I wish the developers would post some sort of notice or testing notes when these releases are not posted on their release date.

**Comment by Bubu** [comment]
Well, at least archlinux has already packaged it: https://www.archlinux.org/packages/community/any/nextcloud/

**Comment by kesselb** [comment]
> Nothing has been officially released on the blog or GA change-log page so I don't believe these releases are going to be final due to current issues list.

They are already announced via the updater. For some reason there is no changelog yet. Afaik the changelog update is a manual step. I guess it will be updated on monday. Feel free to wait with the update until the official changelog is available. 

[Updater 15.0.13](https://github.com/nextcloud/updater_server/pull/276)
[Updater 16.0.6](https://github.com/nextcloud/updater_server/pull/275)
[Updater 17.0.1](https://github.com/nextcloud/updater_server/pull/274)

**Comment by BernieO** [comment]
The changelog appeared: https://nextcloud.com/changelog/

IMHO this can be closed.
