### ISSUE TITLE
Invalid private key for encryption app.

### ISSUE THREAD

**Issue by SyncMaster740B** [nextcloud/server#17872]
I'm using Raspberry Pi with NextCloud, I have actived E2E encryption and now all users are getting "Invalid private key for encryption app. Please update your private key password in your personal settings to recover access to your encrypted files.", also news... I desactivated and deleted the application but the error messatge still here...

**Comment by kesselb** [comment]
Thanks for taking the time to create an issue :+1: 

Please use the search to look for similar issues: #8546 

For general questions / configuration / support please visit https://help.nextcloud.com (or https://portal.nextcloud.com for people with a support subscription).
