### ISSUE TITLE
Regression NC-17.0.0 -> NC17.0.1: Left sidebar too big

### ISSUE THREAD

**Issue by Gatak** [nextcloud/server#17890]
### Steps to reproduce
1. Upgrade to NC 17.0.1
2. Open apps view
3. Look at the left sidebar width

### Expected behaviour
The left sidebar should have been nice and narrow.

### Actual behaviour
There unnecessary white space to make the sidebar unnecessary large.
![image](https://user-images.githubusercontent.com/1469150/68550833-fb42df00-0406-11ea-81ee-a538ccbc89b8.png)
This happen on mobile view too.

I actually think the size should be user selectale, perhaps with the mouse. Also position should be rememberd.

### Server configuration

**Operating system**:
Linux e350 5.3.9-gentoo #3 SMP PREEMPT Fri Nov 8 15:17:22 CET 2019 x86_64 AMD E-350 Processor

**Web server:**
apache-2.4.41
**Database:**
mariadb-10.4.8
**PHP version:**
php-7.3.11
**Nextcloud version:** (see Nextcloud admin page)
17.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
update from prevous NC 17RC
**Where did you install Nextcloud from:**
updater.phar

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - audioplayer: 2.8.4
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.2
  - checksum: 0.4.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - cookbook: 0.5.4
  - cospend: 0.1.5
  - dav: 1.13.0
  - deck: 0.7.0
  - dropit: 0.3.0
  - event_update_notification: 1.0.0
  - extract: 1.2.2
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_automatedtagging: 1.7.0
  - files_downloadactivity: 1.6.0
  - files_external: 1.8.0
  - files_inotify: 0.1.6
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_snapshots: 0.3.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - flowupload: 0.1.5
  - gallery: 18.4.0
  - group_everyone: 0.1.3
  - groupfolders: 5.0.4
  - impersonate: 1.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.18.1
  - maps: 0.1.2
  - metadata: 0.10.0
  - music: 0.11.0
  - news: 14.0.1
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocdownloader: 1.7.4
  - ojsxc: 4.0.0-rc.1
  - password_policy: 1.7.0
  - previewgenerator: 2.1.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quickaccesssorting: 1.0.2
  - radio: 0.6.5
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.2
  - sharingpath: 0.0.2
  - socialsharing_email: 1.0.6
  - spreed: 7.0.1
  - support: 1.0.1
  - survey_client: 1.5.0
  - suspicious_login: 2.4.1
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - timetracker: 0.0.34
  - twofactor_backupcodes: 1.6.0
  - unsplash: 1.1.4
  - updatenotification: 1.7.0
  - uploaddetails: 0.1.2
  - viewer: 1.2.0
  - workflow_script: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_ebookreader
  - files_fulltextsearch
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - issuetemplate
  - recommendations
  - sharelisting
  - theming
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "filesystem_check_changes": true,
        "mysql.utf8mb4": true,
        "default_locale": "en_GB",
        "updater.release.channel": "beta",
        "enable_previews": true,
        "preview_max_x": "1920",
        "preview_max_y": "1200",
        "loglevel": 0,
        "maintenance": false,
        "auth.bruteforce.protection.enabled": false,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MP3",
            "OC\\Preview\\Font"
        ],
        "log_rotate_size": 52428800,
        "theme": "",
        "app_install_overwrite": [
            "spreed",
            "files_trackdownloads",
            "bookmarks_fulltextsearch",
            "tasks",
            "radio",
            "files_reader",
            "video_converter",
            "extract"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** 
local
**Are you using encryption:**
no
**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Opera and Chrome
**Operating system:**
Windows 10, Android 8.0.1

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by wiswedel** [comment]
I cannot reproduce this. On 16.0.5, 17.0.0 and 17.0.1 the sidebar has just the same size on my test instances.

**Comment by juliushaertl** [comment]
Same here. @Gatak You could try to disable third-party apps for testing to see if one is the faulty here? Otherwise maybe you can check the browser console and inspect the `#app-navigation` element to see where the width is coming from?

**Comment by Gatak** [comment]
The width: attribute is set to "auto" but I can't figure out how it comes up with the exact width of 178px. I'll try disabling some apps. to see if it helps. Any tips on where to start?

![image](https://user-images.githubusercontent.com/1469150/68567224-c790a500-0458-11ea-9f4b-5ea640cfcac6.png)

**Comment by Gatak** [comment]
I disabled many apps, including the XMPP chat. I do not use custom themes or CSS. Situation is the same. The left panel width is the same in Files, news, calendar, contacts, audio and music player etc. :(

**Comment by Gatak** [comment]
Here is a view from Firefox. Seems the `#app-navigation` is calculated correctly, but the drawing is still wrong? 

![image](https://user-images.githubusercontent.com/1469150/68567964-91ecbb80-045a-11ea-9230-9b2ffa445879.png)

**Comment by juliushaertl** [comment]
So when checking your screenshot again this is actually the correct size, however it has not changed since Nextcloud 16. The new width was introduced through our navigation standardization so that nested entries have enough space to show content text iirc. cc @skjnldsv

**Comment by jancborchardt** [comment]
Yup, just as Julius said, this is by design and has been like this for a few releases.

**Comment by Gatak** [comment]
Right ok. :)
