### ISSUE TITLE
port forwarding trips up nextcloud

### ISSUE THREAD

**Issue by mauricev** [nextcloud/server#17894]
I have two servers, server I, one in the cloud and one behind a router, server R. Server R hosts nextcloud. It has an ssh tunnel to port 8080 on server I. This enables me to access Server R via Server I. That is, I can reach nextcloud on Server R via Server I. However, this causes nextcloud to become confused and generate a "The server was unable to complete your request." error. 

Further details are described here [https://help.nextcloud.com/t/server-was-unable-to-complete-your-request/63567](url)

As I mention there, this looks similar to bug [https://github.com/nextcloud/server/issues/13943](url) and it might be the case this bug was never completely fixed.

**Comment by rullzer** [comment]
This is not a supported configuration. Setup a reverse proxy if you want such a setup
