### ISSUE TITLE
Nextcloud upgrade v16->v17 with PCNTL error

### ISSUE THREAD

**Issue by innovTech** [nextcloud/server#17897]
I use Nextcloud v16, and I want to upgrade to v17. But when I launch “php occ upgrade” I got an error:

> The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php. Nextcloud is not installed - only a limited number of commands are available Command “upgrade” is not defined.

On the same hosting I already upgrade v15 to v16 without error. No error in apache log are generated.
Hosting : OVH web pro 2014, Linux server with Apache. web [hosting details](http://fpm7.3-check.cluster003.hosting.ovh.net/phpinfo.php), PHP PCNTL is active. OVH support does not found problem.

No solution found by community. Any idea to resolve this issue?

**Comment by kesselb** [comment]
You found a way to fix it or still relevant?
