### ISSUE TITLE
AD attribute userWorkstations set cause SMB external share error

### ISSUE THREAD

**Issue by drlight17** [nextcloud/server#17902]
Hello.
Just figured out that after I set userWorkstations in Active Directory (through "Log on to" User menu) for samba user I get the red inaccessable share in this user's external storages. The following error is in the log.

```json
{
  "reqId": "EfDfCxPhqII1pJe8eAzI",
  "level": 3,
  "time": "2019-11-11T18:03:43+03:00",
  "remoteAddr": "192.168.4.42",
  "user": "test",
  "app": "no app in context",
  "method": "GET",
  "url": "/index.php/apps/files_external/userglobalstorages/34?testOnly=false",
  "message": {
    "Exception": "Icewind\\SMB\\Exception\\ConnectionException",
    "Message": "Connection not valid",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php",
        "line": 412,
        "function": "read",
        "class": "Icewind\\SMB\\Wrapped\\Connection",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php",
        "line": 146,
        "function": "execute",
        "class": "Icewind\\SMB\\Wrapped\\Share",
        "type": "->",
        "args": [
          "cd \"\""
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Share.php",
        "line": 165,
        "function": "dir",
        "class": "Icewind\\SMB\\Wrapped\\Share",
        "type": "->",
        "args": [
          "/"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php",
        "line": 170,
        "function": "stat",
        "class": "Icewind\\SMB\\Wrapped\\Share",
        "type": "->",
        "args": [
          "/files"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php",
        "line": 288,
        "function": "getFileInfo",
        "class": "OCA\\Files_External\\Lib\\Storage\\SMB",
        "type": "->",
        "args": [
          "/files"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Files/Storage/Common.php",
        "line": 452,
        "function": "stat",
        "class": "OCA\\Files_External\\Lib\\Storage\\SMB",
        "type": "->",
        "args": [
          ""
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php",
        "line": 602,
        "function": "test",
        "class": "OC\\Files\\Storage\\Common",
        "type": "->",
        "args": []
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/lib/config.php",
        "line": 274,
        "function": "test",
        "class": "OCA\\Files_External\\Lib\\Storage\\SMB",
        "type": "->",
        "args": [
          "*** sensitive parameter replaced ***",
          "*** sensitive parameter replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/lib/Controller/StoragesController.php",
        "line": 256,
        "function": "getBackendStatus",
        "class": "OC_Mount_Config",
        "type": "::",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/apps/files_external/lib/Controller/UserGlobalStoragesController.php",
        "line": 121,
        "function": "updateStorageStatus",
        "class": "OCA\\Files_External\\Controller\\StoragesController",
        "type": "->",
        "args": [
          "*** sensitive parameters replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 166,
        "function": "show",
        "class": "OCA\\Files_External\\Controller\\UserGlobalStoragesController",
        "type": "->",
        "args": [
          34,
          "*** sensitive parameter replaced ***"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
        "line": 99,
        "function": "executeController",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files_External\\Controller\\UserGlobalStoragesController"
          },
          "show"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 126,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OCA\\Files_External\\Controller\\UserGlobalStoragesController"
          },
          "show"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php",
        "line": 47,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OCA\\Files_External\\Controller\\UserGlobalStoragesController",
          "show",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "id": "34",
            "_route": "files_external.user_global_storages.show"
          }
        ]
      },
      {
        "function": "__invoke",
        "class": "OC\\AppFramework\\Routing\\RouteActionHandler",
        "type": "->",
        "args": [
          {
            "id": "34",
            "_route": "files_external.user_global_storages.show"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 297,
        "function": "call_user_func",
        "args": [
          {
            "__class__": "OC\\AppFramework\\Routing\\RouteActionHandler"
          },
          {
            "id": "34",
            "_route": "files_external.user_global_storages.show"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 975,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/apps/files_external/userglobalstorages/34"
        ]
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 42,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Wrapped/Connection.php",
    "Line": 63,
    "CustomMessage": "Error while getting file info"
  },
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
  "version": "16.0.5.1",
  "id": "5dc9785de5a10"
}
```

It is a bug or a feature?

**Comment by kesselb** [comment]
Good question. Somehow we call the smbclient in a wrong way or with wrong parameters. Have you tried to use the: [php extension for smb](https://github.com/eduardok/libsmbclient-php)?

**Comment by drlight17** [comment]
No. How can I force NC to use php-smbclient instead of smbclient? php-smbclient is already installed (the newest verion for Debian 9 Stretch):
# apt search php-smb
Sorting... Done
Full Text Search... Done
php-smbclient/oldstable,now 0.8.0-3 amd64 [installed]
  PHP wrapper for libsmbclient

**Comment by drlight17** [comment]
> Good question. Somehow we call the smbclient in a wrong way or with wrong parameters. Have you tried to use the: [php extension for smb](https://github.com/eduardok/libsmbclient-php)?
No. How can I force NC to use php-smbclient instead of smbclient? php-smbclient is already installed (the newest verion for Debian 9 Stretch):
apt search php-smb
Sorting... Done
Full Text Search... Done
php-smbclient/oldstable,now 0.8.0-3 amd64 [installed]
PHP wrapper for libsmbclient

**Comment by drlight17** [comment]
Just installed the newer version of php-smbclient:
apt search smbclient
Sorting... Done
Full Text Search... Done
php-smbclient/now 0.9.0-3+b1 amd64 [installed,local]
  PHP wrapper for libsmbclient
Now I've got the following error in log:
{"reqId":"rLxj8cfNAGZwQ52DJfCD","level":3,"time":"2019-11-12T09:01:58+03:00","remoteAddr":"192.168.4.42","user":"test","app":"no app in context","method":"GET","url":"/index.php/apps/files_external/userglobalstorages/34?testOnly=false","message":{"Exception":"Icewind\\SMB\\Exception\\ForbiddenException","Message":"Invalid request for /files (ForbiddenException)","Code":1,"Trace":[{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php","line":62,"function":"fromMap","class":"Icewind\\SMB\\Exception\\Exception","type":"::","args":[{"1":"Icewind\\SMB\\Exception\\ForbiddenException","2":"Icewind\\SMB\\Exception\\NotFoundException","13":"Icewind\\SMB\\Exception\\ForbiddenException","16":"Icewind\\SMB\\Exception\\FileInUseException","17":"Icewind\\SMB\\Exception\\AlreadyExistsException","20":"Icewind\\SMB\\Exception\\InvalidTypeException","21":"Icewind\\SMB\\Exception\\InvalidTypeException","22":"Icewind\\SMB\\Exception\\InvalidArgumentException","28":"Icewind\\SMB\\Exception\\OutOfSpaceException","39":"Icewind\\SMB\\Exception\\NotEmptyException","110":"Icewind\\SMB\\Exception\\TimedOutException","111":"Icewind\\SMB\\Exception\\ConnectionRefusedException","112":"Icewind\\SMB\\Exception\\HostDownException","113":"Icewind\\SMB\\Exception\\NoRouteToHostException"},1,"/files"]},{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php","line":74,"function":"handleError","class":"Icewind\\SMB\\Native\\NativeState","type":"->","args":["/files"]},{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php","line":184,"function":"testResult","class":"Icewind\\SMB\\Native\\NativeState","type":"->","args":["*** sensitive parameter replaced ***","smb://fs.ksc.loc/Homes/files"]},{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php","line":133,"function":"stat","class":"Icewind\\SMB\\Native\\NativeState","type":"->","args":["smb://fs.ksc.loc/Homes/files"]},{"file":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php","line":112,"function":"getStat","class":"Icewind\\SMB\\Native\\NativeShare","type":"->","args":["/files"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php","line":170,"function":"stat","class":"Icewind\\SMB\\Native\\NativeShare","type":"->","args":["/files"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php","line":288,"function":"getFileInfo","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->","args":["/files"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":452,"function":"stat","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->","args":[""]},{"file":"/var/www/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php","line":602,"function":"test","class":"OC\\Files\\Storage\\Common","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/files_external/lib/config.php","line":274,"function":"test","class":"OCA\\Files_External\\Lib\\Storage\\SMB","type":"->","args":["*** sensitive parameter replaced ***","*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Controller/StoragesController.php","line":256,"function":"getBackendStatus","class":"OC_Mount_Config","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/files_external/lib/Controller/UserGlobalStoragesController.php","line":121,"function":"updateStorageStatus","class":"OCA\\Files_External\\Controller\\StoragesController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":166,"function":"show","class":"OCA\\Files_External\\Controller\\UserGlobalStoragesController","type":"->","args":[34,"*** sensitive parameter replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_External\\Controller\\UserGlobalStoragesController"},"show"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_External\\Controller\\UserGlobalStoragesController"},"show"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_External\\Controller\\UserGlobalStoragesController","show",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"34","_route":"files_external.user_global_storages.show"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"34","_route":"files_external.user_global_storages.show"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"34","_route":"files_external.user_global_storages.show"}]},{"file":"/var/www/nextcloud/lib/base.php","line":975,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/files_external/userglobalstorages/34"]},{"file":"/var/www/nextcloud/index.php","line":42,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Exception/Exception.php","Line":30,"CustomMessage":"Error while getting file info"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","version":"16.0.5.1","id":"5dca4b0d4b1a5"}

With userWorkstations attribute not set mount works with no errors.

**Comment by skjnldsv** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

This is definitely not a bug but a misconfiguration. Sorry!
