### ISSUE TITLE
App Menu UI improvement

### ISSUE THREAD

**Issue by declan-marks** [nextcloud/server#17904]
One area of the UI that I think could do with improvement would be the App Menu

These improvements come from a previous post: https://github.com/nextcloud/server/issues/12778#issuecomment-454326150, I applied the fixes using the JSLoader and CustomCSS app. The visual improvement is much better than stock and I feel this should be integrated directly into the nextcloud.

Custom js:
```
(function(){
    var container = document.querySelector("#appmenu");
    var tooltipList = container.querySelectorAll('a[aria-label]');
    for(var i = 0; i < tooltipList.length; i++){
        var tooltipContainer = document.createElement('span');
        var att = document.createAttribute("class");       
        att.value = "triangle--span";       
        tooltipContainer.setAttributeNode(att); 
        tooltipList[i].parentNode.insertBefore(tooltipContainer, tooltipList[i].nextSibling);
    }   
})();
```

And the css:
```
/* Disable subtitles and jumping icons */

#appmenu li span {
  display: none;
}

#appmenu:hover li span,
#appmenu li:hover a + span,
#appmenu li a:focus + span, #appmenu li:hover span, #appmenu li:focus span,
#appmenu li a:focus span {
  display: none;
}

#appmenu:hover li svg,
#appmenu:hover li .icon-more,
#appmenu:hover li .icon-more-white,
#appmenu:hover li .icon-loading-small,
#appmenu:hover li .icon-loading-small-dark {
  transform: none;
}

#appmenu li a:focus svg,
#appmenu li a:focus .icon-more,
#appmenu li a:focus .icon-more-white,
#appmenu li a:focus .icon-loading-small,
#appmenu li a:focus .icon-loading-small-dark {
  transform: none;
}

/* Disable triangle below icons */
#appmenu li a.active::before, #appmenu li:hover a::before, #appmenu li:hover a.active::before, #appmenu li a:focus::before {
 display: none;
}

/* Enable tooltips */
#appmenu:hover li:hover span,
#appmenu:hover li:focus span {
    opacity: 1;
    z-index: 5;
    display: inline-block;
    margin-bottom: -25px;
    border-radius: 2px;
    background-color: black;
    color: #fff8eb;
    font-size: 1.3em;
    line-height: 1.6em;
}

#appmenu:hover li .active + span {
    opacity: 1;
    background-color: #bcbcbc1a;

}

#appmenu li a.active {
    opacity: 1;
    background-color: #bcbcbc1a;
    border-bottom: 2px black;
    border-radius: 50%;
}

#appmenu:hover li:hover span.triangle--span,
#appmenu:hover li:focus span.triangle--span {
    width: 0;
    height: 0;
    border-left: 15px solid transparent;
    border-right: 15px solid transparent;
    border-bottom: 15px solid black;
    z-index: 4;
    bottom: 0;
    margin-bottom: -3px;
    content: '';
    display: block;
    position: absolute;
    padding: 0;
    background: none;
}
```
This is the screenshot of what the results are:
![App Menu](https://camo.githubusercontent.com/dd06b85f9bd1df9a5f5f55b77017a3008dd322ba/68747470733a2f2f73322e67696679752e636f6d2f696d616765732f4e436170706d656e755f31352d30312d323031392e676966)

**Comment by kesselb** [comment]
This one is a follow up for https://github.com/nextcloud/server/issues/12778

cc @nextcloud/designers perhaps you changed your mind ;)

**Comment by jancborchardt** [comment]
The reason why the design is how it is:
- Showing all the app labels by default would be too much, and also overlap cause of label length.
- Not showing them at all makes it very difficult to identify the apps, especially if you do not use Nextcloud every day.
- Showing only the label of the current or hovered app still requires you to hover each individual item. This is called Mystery meat navigation: https://en.m.wikipedia.org/wiki/Mystery_meat_navigation

Any improvement which keeps these requirements in mind is very welcome. :) Simply removing the labels is not an option though.

**Comment by ma12-co** [comment]
Suggested Improvement: make the header 10px taller :)

**Comment by jancborchardt** [comment]
@ma12-co which issue will be solved by making the header taller? :) Seems unrelated to this issue at least?

**Comment by ma12-co** [comment]
It would improve the UI of the app menu :smile:?? 
Yeah kinda unrelated here, sorry.. Should I open a pr for this? I think we agreed on this at the conference @jancborchardt , isn't it?

**Comment by skjnldsv** [comment]
@jancborchardt closing?

**Comment by jancborchardt** [comment]
Yup, closing as we went with a design which shows app names (at least partly) at the same time – which works better for people who are bot used to the app icons.
