### ISSUE TITLE
Unable to unshare folder if "shared by" server is down

### ISSUE THREAD

**Issue by MrCapone** [nextcloud/server#17908]
### Steps to reproduce
1. accept share from another server
2. another server is turned off
3. on web interface choose unshare

### Expected behaviour
shared folder deleted from my server

### Actual behaviour
got `Error deleting file`

### Server configuration

**Operating system**: Debian 10 "buster"

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 17.0.0

### Client configuration
**Browser:** Mozilla Firefox 70.0.1 

**Operating system:** macOS 10.15.1 Catalina

**Comment by Thatoo** [comment]
Same for me.
What is the work around? out of web interface?

**Comment by MrCapone** [comment]
@Thatoo i was able to fix it only by manually editing database. First i removed folder from oc_share_external table. Then i removed folder lock from oc_file_locks.

**Comment by Thatoo** [comment]
for me, it's only a file. I can indeed find it in the table oc_share_external and could delete this line.
However, I don't find anything in the table oc_file_locks.
Is it ok to delete the line in oc_share_external if I don't have anything in oc_file_locks?

Thank you for your help,

**Comment by Thatoo** [comment]
It is also appearing in the oc_mounts table. Should I delete it from there too?

**Comment by MrCapone** [comment]
Try delete it from oc_share_external and then delete it by web interface.

**Comment by Thatoo** [comment]
I delete it from oc_share_external and it was gone. I didn't need to delete it by the web interface.

However, I have tried to share a file from an other nextcloud to the one where I've just done the work and it doesn't display neither. Did I loose the ability to receive any file shared?

**Comment by Thatoo** [comment]
Thank you!

**Comment by 466** [comment]
I got the very same issue here  :(

Is this being worked on?
Do not want to delete these entries manually .... .

**Comment by Thatoo** [comment]
I don't think so but it did work fro me to do as described

**Comment by kesselb** [comment]
```
Index: lib/private/Files/View.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Files/View.php	(revision 0ddb9c01362a74662a4f062683c82c1594c7da01)
+++ lib/private/Files/View.php	(date 1576960808363)
@@ -60,6 +60,7 @@
 use OCP\Files\NotFoundException;
 use OCP\Files\ReservedWordException;
 use OCP\Files\Storage\IStorage;
+use OCP\Files\StorageNotAvailableException;
 use OCP\ILogger;
 use OCP\IUser;
 use OCP\Lock\ILockingProvider;
@@ -1346,7 +1347,7 @@
 				$data = $cache->get($internalPath);
 				$this->unlockFile($relativePath, ILockingProvider::LOCK_SHARED);
 			}
-		} catch (LockedException $e) {
+		} catch (LockedException|StorageNotAvailableException $e) {
 			// if the file is locked we just use the old cache info
 		}
```

I'm able to delete a offline share again with the above change. But please be careful this code is used by any storage implementation (also the local one, smb, etc). Probably change it temporary, delete the broken share and revert it again. 

How does it work? If the remote is offline we cannot fetch the share information. Everything will break than. With the above patch we just ignore it and reuse the cached information. That seems to work for deleting afterwards.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

From a technical point it's the same as https://github.com/nextcloud/server/issues/14797 hence i'm closing this one.
