### ISSUE TITLE
Error Warning no app in context

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#17901]
`["2EY9XmeqrbEaLHN",{"type":"Person","name":"Tiger"},{"type":"Person","name":"Tiger@www.pensierando.it\/nx"},"Delete","2019-09-18T10:36:14+00:00",{"type":"Document","name":"\/IPTV Pro v5.1.4_arm64.apk"},[],[]]`

both with version 16.x and with the latest version nextcloud 17.0.1 I get this warning all the time and I don't know how to remove it.  does anyone have any ideas?

error refers to a file that is no longer available in a shared nextcloud folder

Apache2/php 7.3.11 

![Screenshot_20191111-142504](https://user-images.githubusercontent.com/35575744/68590546-16593180-048f-11ea-8a5f-01e4d0368eb5.png)

**Comment by kesselb** [comment]
Would you mind to use the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) to report a problem? It's usually much easier to triage any issue with it. Please also take note of [submitting issues](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md#submitting-issues).

To give you a concrete example: The above stack trace could be related to circles or social. I don't know which apps are present at your instance. How should I know which developer to mention? Anyway it's a warning so probably increasing the [loglevel](https://docs.nextcloud.com/server/17/admin_manual/configuration_server/config_sample_php_parameters.html#logging) will remove it.

cc @nextcloud/server-triage @nextcloud/social any idea where this comes from? ;)

**Comment by tigernero79** [comment]
I have the classic apps installed, plus qlc always official, maybe I have to increase the error in the logs, although it always shows the same file in error that actually doesn't even exist anymore.

**Comment by nickvergessen** [comment]
I guess it's an oversight from: https://github.com/nextcloud/activity/blob/master/lib/Controller/RemoteActivity.php#L92
Should be removed

**Comment by nickvergessen** [comment]
Fixed in https://github.com/nextcloud/activity/pull/411

**Comment by tigernero79** [comment]
will the commit be inserted in nextcloud 17.0.2?

Thanks for all

**Comment by nickvergessen** [comment]
Yes
