### ISSUE TITLE
Delete old calendar entries

### ISSUE THREAD

**Issue by mikch06** [nextcloud/server#17914]
The user should be able to delete old entries batch wise.
Most importan thing is having options like:

- delete entries older than a year
- delete all entries in the past
- ...

**Comment by georgehrke** [comment]
I feel like there already was an issue for this which we closed as won't fix, but i can't find it.

**Comment by mikch06** [comment]
Hopefully not. This is a main feature of a calendar app.

**Comment by georgehrke** [comment]
> This is a main feature of a calendar app.

macOS calendar doesn't offer it. Fantastical doesn't offer it. Google calendar doesn't offer it. Thunderbird Lightning doesn't offer it. ...

**Comment by mikch06** [comment]
:D nice to grow an cloud database... but do you like to host thousands of blob entries in an mariadb? i dont.

**Comment by georgehrke** [comment]
If someone wants to implement an occ command for this, I'm happy to guide them, but i don't want stuff like this to clutter our UI.

**Comment by mikch06** [comment]
Thx, i think this could be enough. I can manage it by sql for myself. But i often heard this from projects i am supporting.
