### ISSUE TITLE
Unknown error while uploading a file

### ISSUE THREAD

**Issue by bertalanimre** [nextcloud/server#17912]
https://cloud.bitandpixel.hu/s/98TD2eisSMA8gtM
Password: RxkuUU/T6PQXD97BWoEU

The issue for me is simple, no user is able to upload any file. They are able to create folders and files on the WebUI. But uploading is corrupted. In the NextCloud log, nothing shows up, like if nobody is using the server. Only in NginX log, I can see the following:
```
10.0.X.X - - [12/Nov/2019:14:54:18 +0100] "MKCOL /remote.php/dav/uploads/my.user/web-file-upload-6268cbd2da6fd48a61bce911089ef3d3-1573566857892 HTTP/1.0" 201 0 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.8 Safari/537.36" "10.0.X.X"
10.0.X.X - - [12/Nov/2019:14:54:18 +0100] "DELETE /remote.php/dav/uploads/my.user/web-file-upload-6268cbd2da6fd48a61bce911089ef3d3-1573566857892 HTTP/1.0" 204 0 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.8 Safari/537.36" "10.0.X.X"
10.0.X.X - - [12/Nov/2019:14:54:18 +0100] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=%2FTemplates%2FLimitless%20-%20Responsive%20Web%20Application%20Kit HTTP/1.0" 200 229 "-" "Mozilla/5.0 (X11; Fedora; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.8 Safari/537.36" "10.0.X.X"
```
I've just updated NextCloud in hope, this issue will go away, but no luck there. 
If you need any further info, let me know, but this annoys me a lot.

**Comment by kesselb** [comment]
> If you need any further info, let me know, but this annoys me a lot.

[Issue Template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)?

Please note this is the wrong place for configuration issues. https://help.nextcloud.com is the right place. For Nginx there is a special configuration required: https://docs.nextcloud.com/server/17/admin_manual/installation/nginx.html

**Comment by bertalanimre** [comment]
Are you sure it is a configuration issue? The system was working fine till a few days ago. I mean nobody reported any issue in the last 2 weeks, tho nobody was using it either. :/

**Comment by kesselb** [comment]
> Are you sure it is a configuration issue?

No. How should I? That's the reason we ask for the issue template. 

> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

(quoted from the issue template).

**Comment by bertalanimre** [comment]
Sorry. :(

**Comment by kesselb** [comment]
No need to worry ;) Just use the issue template if you want to report a bug so we can have a look. I guess if someone writes you a email (in your role as system administrator) "it does not work" you don't know what to do either without more information.

**Comment by bertalanimre** [comment]
Actually, just figured out. ZIP files are forbidden or something....
