### ISSUE TITLE
show shared files with full path - enhancement

### ISSUE THREAD

**Issue by zwotzie** [nextcloud/server#1791]
If you share a more than a few files or folders per hyperlink than it would be an necessary enhancement to show the full path not only in the tooltip but directly on the page.

**Comment by nickvergessen** [comment]
Can you make a screenshot of the page you are talking about?

**Comment by zwotzie** [comment]
here you are and thanks for the great sw:

<img width="275" alt="bildschirmfoto 2016-10-19 um 09 30 42" src="https://cloud.githubusercontent.com/assets/10273737/19509480/21947ba8-95df-11e6-937b-a0018253d7ca.png">

**Comment by nickvergessen** [comment]
Okay, I talked to a designer here in the office, the idea would be to only show the path (half-transparent) when the item name is **conflicting**.
E.g.
![shared_by_link_-_nextcloud_-_2016-10-19_10 45 18](https://cloud.githubusercontent.com/assets/213943/19511794/251c926a-95e9-11e6-8038-b7918fdab562.png)

**Comment by zwotzie** [comment]
I would say this solution is good, but not perfekt.

The preferred way would be to show the path always. I'll try to explain why:

* for me it looks inconsistent
* if you have many shared links in different folders, you always want to know where
* best would be to be able to customize the view in the settings, because everybody has his own opinion

All the best.

**Comment by roomanus** [comment]
Hey guys, 
sorry for warming this up!
On the "doing the share" side it is shown nicely, with the full path, additionally the full path is shown if you hoover over..
![1](https://cloud.githubusercontent.com/assets/20578820/24401709/be717c2e-13b5-11e7-848e-089b8b8e3fa9.JPG)

On the "getting the share" side though, there is only the shared folder shown, which can indeed be quite confusing depending on the folder structure laying under...no additional path shown when pointing with yout cursor as well...
![2](https://cloud.githubusercontent.com/assets/20578820/24401695/ae838faa-13b5-11e7-9b67-441b0c52e51e.JPG)

Is there any con or significant reason why on the share receiving side the path isn't shown?
The next thing to remark in my opinion is the representation in the activiy-stream, which is also confusing without any further path info...same here with cursor, on sender side additional info is shown, receiver side nothing is shown

Nevertheless thanks for your work and this great platform.
All the best...

**Comment by jancborchardt** [comment]
@roomanus please open a new issue for this. :)
