### ISSUE TITLE
Info on upgrade too wide

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#17921]
![image](https://user-images.githubusercontent.com/5836855/68741048-e0ca5a80-05ec-11ea-9275-c50b5233f26e.png)

Branch: master 

I think it was not that wide on previous updates.
Further screens are also auto resizing, but maybe it would be good to have a max-width? E.g. 60% of screen?

@nextcloud/designers

**Comment by ma12-co** [comment]
I would go with a fixed width as opposed to a % of the page width

**Comment by skjnldsv** [comment]
That what was originally, and we reverted it back by mistake. :/

**Comment by ChristophWurst** [comment]
This looks also ugly on the 2fa pages :cry:

**Comment by jancborchardt** [comment]
This is a duplicate of **Container on update screen is too wide #17556** ;)

And yes, totally agree. This should have the fixed width like before – as said in that issue.
