### ISSUE TITLE
Expire share link after minutes or hours

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#17934]
Currently, shared link expiration is set by calendar date only in Nextcloud 16 stable.  My request is:
- expiration of a share after so many _minutes_ from creation
- expiration of a share after so many _hours_ from creation

This is different from, but related to [this request for one time download links](https://github.com/nextcloud/server/issues/6841).

Example:
https://justbeamit.com creates a shared url that either automatically expires 10 minutes after or after the first time it is downloaded (I assume this means accessed twice in Nextcloud).
![Screen Shot 2019-11-13 at 2 56 29 PM](https://user-images.githubusercontent.com/1787238/68811673-117ab600-0626-11ea-8216-9dc348a44964.png)

This method works beautifully and automatically generates a one-time url for the sender , much like an otp 6 character code generation.

- Recipient enters the custom url and downloads the file.
- Sender sees "Completion" for the transfer.
![Screen Shot 2019-11-13 at 2 57 13 PM](https://user-images.githubusercontent.com/1787238/68811769-3ec76400-0626-11ea-9dd7-431e63d1705a.png)
- If sender attempts to generate a new share link, previous link will be automatically expired if it has not been accessed already.  If previous share is still active, sender is sent a warning they must accept to generate a new share link.
![Screen Shot 2019-11-13 at 3 02 05 PM](https://user-images.githubusercontent.com/1787238/68811967-bbf2d900-0626-11ea-910d-311dfcb4b13d.png)

**Comment by skjnldsv** [comment]
Hey!

> Currently, shared link expiration is set by calendar date only in Nextcloud 16 stable

What do you mean by that?

I don't understand your request :)
Do you have any more examples? Without using another service, create an example using nextcloud if possible ;)

**Comment by j-ed** [comment]
@skjnldsv I think he wants to be able to set an expiry period based on minutes or hours instead of days. Currently a share can only be set for a number of days.

**Comment by skjnldsv** [comment]
Ah okay, I did not understand what the whole point about the justbeamit service was about.

@jancborchardt I think we should not, already complicated enough, days is not an issue I think here.
If we want to implement #6841 with a xxx minutes delay before expiry in case the download failed, sure, let's do this.
But this one is really a too-many-options feature :)

**Comment by jancborchardt** [comment]
Yeah, considering we didn’t have this request so far (or am I missing something) it doesn’t seem to be something that’s really so necessary for the core product.

This might be perfect for an app developer?

**Comment by SunChero** [comment]
i have been tasked to do just that .. our company need to set expiry by hours instead of days ...
i understand nextcloud may not be willing to do this .. but if someone can point me to the right direction /files or cron .. i may code it myself  

i think a cron job running hourly or event a db trigger can be reasonable ...


thanks

**Comment by ralfhauser** [comment]
I would even go for seconds until expiration

**Comment by sunjam** [comment]
Perhaps this could be given the https://github.com/nextcloud/server/labels/Nice%20to%20have tag :)
