### ISSUE TITLE
NC 10.0.1 new install fails on Postgres 9.6 (fresh install)

### ISSUE THREAD

**Issue by namiba** [nextcloud/server#1793]
### Steps to reproduce
1.  create user in pg with SUPERUSER CREATEDB CREATEROLE;
2.  run web install 
3.  error
### Expected behaviour

Install should complete
### Actual behaviour

"message":"Error occurred while checking PostgreSQL version, assuming >= 9",
"Message":"Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:
### Server configuration

**Operating system**:  Gentoo 

**Web server:** apache

**Database:** Postgres 9.6

**PHP version:** 5.6.25

**Nextcloud version:** (see Nextcloud admin page) 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** No

**Where did you install Nextcloud from:**  NC 

**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
<?php
$CONFIG = array (
  'instanceid' => 'ocgudckwu6wm',
  'passwordsalt' => 'XXXXXXXXXXXXXXXXXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' =>
  array (
    0 => 'miniicloud.iserv.net',
  ),
  'datadirectory' => '/var/nextcloud/data',
  'overwrite.cli.url' => 'https://miniicloud.iserv.net',
  'dbtype' => 'pgsql',
  'version' => '9.1.1.5',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
);

```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...   No

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**

**Operating system:**
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>

```
{"reqId":"WAbqe8CoAfAAAAq0AA8AAAAB","remoteAddr":"192.168.1.20","app":"no`
 app in context","message":"Error occurred while checking PostgreSQL version, assuming >= 9","level":2,"time":"2016-10-19T03:37:31+00:00","method":"POST","url":"\/index.php","user":"--"}
{"reqId":"WAbqe8CoAfAAAAq0AA8AAAAB","remoteAddr":"192.168.1.20","app":"no app in context","message":"Exception: {\"Exception\":\"Doctrine\\\\DBAL\\\\DBALException\",\"Message\":\"Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] FATAL:  role \\\"apache\\\" does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(429): OC\\\\DB\\\\Connection->connect()\\n#1 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(389): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatformVersion()\\n#2 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(328): Doctrine\\\\DBAL\\\\Connection->detectDatabasePlatform()\\n#3 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(621): Doctrine\\\\DBAL\\\\Connection->getDatabasePlatform()\\n#4 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php(142): Doctrine\\\\DBAL\\\\Connection->setTransactionIsolation(2)\\n#5 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DriverManager.php(172): OC\\\\DB\\\\Connection->__construct(Array, Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOPgSql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#6 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/ConnectionFactory.php(123): Doctrine\\\\DBAL\\\\DriverManager::getConnection(Array, Object(Doctrine\\\\DBAL\\\\Configuration), Object(Doctrine\\\\Common\\\\EventManager))\\n#7 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Server.php(415): OC\\\\DB\\\\ConnectionFactory->getConnection('pgsql', Array)\\n#8 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/3rdparty\\\/pimple\\\/pimple\\\/src\\\/Pimple\\\/Container.php(113): OC\\\\Server->OC\\\\{closure}(Object(OC\\\\Server))\\n#9 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Utility\\\/SimpleContainer.php(103): Pimple\\\\Container->offsetGet('DatabaseConnect...')\\n#10 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/ServerContainer.php(89): OC\\\\AppFramework\\\\Utility\\\\SimpleContainer->query('DatabaseConnect...')\\n#11 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/Server.php(1029): OC\\\\ServerContainer->query('DatabaseConnect...')\\n#12 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/db.php(57): OC\\\\Server->getDatabaseConnection()\\n#13 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/db.php(134): OC_DB::prepare('SHOW SERVER_VER...', NULL, NULL)\\n#14 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(887): OC_DB::executeAudited('SHOW SERVER_VER...')\\n#15 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/util.php(867): OC_Util::checkDatabaseVersion()\\n#16 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/base.php(674): OC_Util::checkServer(Object(OC\\\\AllConfig))\\n#17 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/base.php(1059): OC::init()\\n#18 \\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/index.php(46): require_once('\\\/var\\\/www\\\/localh...')\\n#19 {main}\",\"File\":\"\\\/var\\\/www\\\/localhost\\\/htdocs\\\/nextcloud\\\/lib\\\/private\\\/DB\\\/Connection.php\",\"Line\":59}","level":3,"time":"2016-10-19T03:37:32+00:00","method":"POST","url":"\/index.php","user":"--"}
```

<summary>

Nextcloud log</summary>

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

**Comment by nickvergessen** [comment]
@icewind1991 you changed postgres stuff lately. Could you have a look?

**Comment by namiba** [comment]
This is for fresh installs ONLY:

Postgres 9.6 + NC 9.0.54 => OK
Postgres 9.5 + NC 9.0.54 => OK
Postgres 9.6 + NC 10.0.1 => Not OK (Same result as in bug report)
Postgres 9.5 + NC 10.0.1 => Not OK (Same result as in bug report)

It is not a Postgres problem but a NC issue.

**Comment by Lartza** [comment]
Also broken in 10.0.2RC2 and 11.0.0RC1, postgresql 9.6.1
This bugreport is missing the complete error which for me is `SQLSTATE[08006] [7] FATAL: role "oc_Lartza" does not exist`, this happens after pressing "Finish setup"

The problem I think is NC10 and NC11 create the role lowercase as oc_lartza but try to use it as oc_Lartza, NC9 creates the role as oc_Lartza without lowercasing it.

**Comment by LukasReschke** [comment]
@icewind1991 Please take a look. Thanks.

**Comment by Lartza** [comment]
I can confirm role case to be a change between the versions, and a possible reason why it breaks. Fresh install, same postgres server, all nextcloud versions were given the postgres user in setup to access the server, only 9.0.55 RC2 succeeds. Couldn't immediately pinpoint a commit that changed this but there must be one.

```
postgres=# \du
                                    List of roles
  Role name  |                         Attributes                         | Member of 
-------------+------------------------------------------------------------+-----------
 oc_Lartza9  | Create DB                                                  | {}
 oc_lartza10 | Create DB                                                  | {}
 oc_lartza11 | Create DB                                                  | {}
 postgres    | Superuser, Create role, Create DB, Replication, Bypass RLS | {}

postgres=# \l
                                      List of databases
    Name     |    Owner    | Encoding |   Collate   |    Ctype    |     Access privileges     
-------------+-------------+----------+-------------+-------------+---------------------------
 nextcloud10 | oc_lartza10 | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 | 
 nextcloud11 | oc_lartza11 | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 | 
 nextcloud9  | oc_Lartza9  | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 | oc_Lartza9=CTc/oc_Lartza9
 postgres    | postgres    | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 | 
 template0   | postgres    | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 | =c/postgres              +
             |             |          |             |             | postgres=CTc/postgres
 template1   | postgres    | UTF8     | fi_FI.UTF-8 | fi_FI.UTF-8 | =c/postgres              +
             |             |          |             |             | postgres=CTc/postgres
(6 rows)
```

Upgrading the successful 9.0.55 RC2 install to 10.0.2 RC2, web updater worked and Nextcloud seemed to continue to work.
Upgrading that upgraded 10.0.2 RC2 to 11.0 RC1, same result.

**Comment by Lartza** [comment]
Changing
https://github.com/nextcloud/server/blob/a89b033869db08f1ad3483a5ab3fe774e898fa0f/lib/private/Setup/PostgreSQL.php#L159 to
`$query = $connection->prepare("CREATE USER \"" . addslashes($this->dbUser) . "\" CREATEDB PASSWORD '" . addslashes($this->dbPassword) . "'");`
changes the error to `SQLSTATE[08006] [7] FATAL: database "nextcloud11" does not exist`

One step forward and one back since server now has a role "oc_Lartza11" but does not indeed have the database which it does without this change.

**Comment by nickvergessen** [comment]
I just installed 11 beta2 and 10 on postgres 9.5 yesterday, worked quit fine.

**Comment by Lartza** [comment]
I think I originally installed my production server as Nextcloud 10 (and not 9) on 9.5, but it could have been 9.4 too without issues too. In any case it is broken in the latest 10 and 11 RC's and the fix should be backwards compatible but I haven't tested this on other than 9.6.1

**Comment by andreas-p** [comment]
Positive confirmation for non-standard configurations:
Testing two scenarios against a PostgreSQL 9.6 server using git-master. The hostname is servername:port to specify the non-standard port

Using the user "ncTest" to access the database "ncGit" owned by himself succeeds. 
Using "ncTest" with CREATEDB privilege with no precreated database works as well.

**Comment by moodlebeuth** [comment]
I can confirm the error with port 6432 by using pgbuncer 1.7.2 or directly for nextcloud 11.0.3 and postgresql 9.6.2, php 5.6.30 & apache 2.4.10 on debian jessie:

> [Fri Apr 28 18:27:12.044594 2017] [:error] [pid 9258] [client q.x.y.z:41380] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in driver: SQLSTATE[08006] [7] could not connect to server: Connection refused\n\tIs the server running on host "q.x.y.z" and accepting\n\tTCP/IP connections on port 5432?' in /var/www/nextcloud/lib/private/DB/Connection.php:60\nStack trace:\n#0 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/nextcloud/lib/private/DB/Connection.php(147): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/nextcloud/3rdparty/doct in /var/www/nextcloud/lib/private/DB/Connection.php on line 60

I dentified the issue together with Andreas Kretschmer from 2ndquadrant.

Thanks & Greetings,
Michael

**Comment by Modi34** [comment]
have same error 
nc install script creates a user for some point instead of using the one I provided
https://i.imgur.com/PuDsjaq.png

with every new try it creates a new user 

if I add db name that does not exists in postgress it also fails with some new error
Ive lost a lot of time thinking something wrong with my vm  - please fix it or remove postgres support
