### ISSUE TITLE
sudden 100% CPU Usage with PHP-FPM 

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#17932]
### Steps to reproduce
Unknown

### Expected behaviour
Nothing out the ordinary

### Actual behaviour
a 95-100% CPU was observed today on the php-fpm process. Will run indefinitely until manually killed.

![Screenshot_4](https://user-images.githubusercontent.com/36133540/68802451-3e4abf80-065e-11ea-9907-d89e1217bfd0.png)

Nothing found in the logs at the time when the hogging process was started

```
Nov 13 17:39:01 localhost CRON[8002]: pam_unix(cron:session): session opened for user root by (uid=0)
Nov 13 17:39:01 localhost CRON[8003]: (root) CMD (  [ -x /usr/lib/php/sessionclean ] && if [ ! -d /run/systemd/system ]; then /usr/lib/php/sessionclean; fi)
Nov 13 17:39:01 localhost CRON[8002]: pam_unix(cron:session): session closed for user root
Nov 13 17:39:01 localhost systemd[1]: Starting Clean php session files...
Nov 13 17:39:01 localhost systemd[1]: phpsessionclean.service: Succeeded.
Nov 13 17:39:01 localhost systemd[1]: Started Clean php session files.
```

- NC Was not used by that time, no transfers.
- This happened two times in the past, each time the server ran another active service (currently docker container). This has never happened before when server ran only NC. 54% memory free currently.

### Server configuration

**Operating system**: Ubuntu 19.04

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.2.24

**Nextcloud version:** (see Nextcloud admin page) 16.05 snap

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.2.0
  - activity: 2.9.1
  - admin_audit: 1.6.0
  - apporder: 0.8.0
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0
  - checksum: 0.4.3
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - drawio: 0.9.4
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_ebookreader: 0.0.1
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - flowupload: 0.1.5
  - gpxpod: 4.1.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - metadata: 0.10.0
  - music: 0.11.0
  - nextcloud_announcements: 1.5.0
  - notes: 3.0.3
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - phonetrack: 0.5.2
  - previewgenerator: 2.1.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - spreed: 6.0.4
  - systemtags: 1.6.0
  - text: 1.0.2
  - theming: 1.7.0
  - theming_customcss: 1.4.0
  - twofactor_backupcodes: 1.5.0
  - twofactor_totp: 3.0.1
  - unsplash: 1.1.4
  - viewer: 1.1.0
  - workflowengine: 1.6.0r
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... local

**Are you using encryption:** yes/no no

**Comment by pilsnerbeer** [comment]
Picture: Sudden jump from idle to steady 95+% in a matter of minutes

![Screenshot_5](https://user-images.githubusercontent.com/36133540/68803727-94b8fd80-0660-11ea-8e6d-0c78ed25fa9c.png)

**Comment by kesselb** [comment]
Best guess: https://github.com/nextcloud/server/issues/17447

**Comment by pilsnerbeer** [comment]
Excellent! I think I found the cause. PHP-FPM goes to 100% instantly when visiting the "Shared" section in Android app. I remember accidentally tapping on it earlier today which I'm sure caused the 100% spike.


![Screenshot_6](https://user-images.githubusercontent.com/36133540/68804678-908ddf80-0662-11ea-8794-d1d1c36dfe92.png)
