### ISSUE TITLE
files deleted, created after closing and version does not work when edited using davfs

### ISSUE THREAD

**Issue by unnilennium** [nextcloud/server#17937]
### Steps to reproduce
1. follow the  how to there https://docs.nextcloud.com/server/15/user_manual/files/access_webdav.html
2. open a file using libreoffice and edit it from the webdav folder on your fedora 30
3. browse the nextcloud interface, the file has vanished.
4. close openoffice after saving modification, refresh browser, file reappeared as created seconds ago.

alternatively if libreoffice /gnomes crashes, your file is lost.ANy modification even saved while libreoffice was not completely close will be lost.

Note: I am not using the gnome client as it is not seen by many applications ( wine apps as examples, or never show as a direct and easy shortcut when trying to save from firefox, as it should). Using the gnome client allows to use the versioning

### Expected behaviour
being  able to see the file at the same time on both interfaces. versioning working with no loss of past editions.

### Actual behaviour
all versioning is lost, modifications done in libreoffice if it crashes are all lost.

### Server configuration

**Operating system**:
centos 6
**Web server:**
apache 2.2
**Database:**
mysql 5.5
**PHP version:**
php71

**Nextcloud version:** (see Nextcloud admin page) 16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 13

**Where did you install Nextcloud from:**
tar
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - dicomviewer: 1.2.0
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_inotify: 0.1.6
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - maps: 0.1.2
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - ocr: 4.4.16
  - password_policy: 1.6.0
  - provisioning_api: 1.6.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - user_ldap: 1.6.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_reader
  - privacy
  - recommendations
  - workflow_pdf_converter

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.12.1",
            "198.48.217.152"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "files_reader"
        ]
    }
}

</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox

**Operating system:** fedora 30

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by c0d3z3r0** [comment]
Interesting... I'm experiencing the same on a MS Sharepoint with LibreOffice and davfs2! Maybe this is a davfs2 or LibreOffice bug?!

**Comment by marekbedy** [comment]
I have the same problem with multiple applications like Okular, FoxitReader when annotating pdf files. 
When a file is changed and saved in the editor, it is deleted from nextcloud and a new version is not uploaded to nextcloud, file is lost. The mounted webdav filesystem freezes after, only a reboot helps.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by unnilennium** [comment]
confirmed still present using nextcloud 19.0.12
can not upgrade presently because of db that i need to update.
