### ISSUE TITLE
require minimum client version

### ISSUE THREAD

**Issue by r2evans** [nextcloud/server#17943]
**Is your feature request related to a problem? Please describe.**

Related to the security ramifications of the new **Remote Wipe** feature.

If there is no server-based constraint on the minimum client version, then an intentioned user can downgrade their client (or just never upgrade) below the clients that enable remote wipe. While this might disable any new features for them, it also minimizes *their* risk of losing the sync'd files.

**Describe the solution you'd like**

Server configuration that allows the admin to mandate a minimum client version before syncing.

**Describe alternatives you've considered**

I can think of nothing that would otherwise prevent a remote user from using an older client version to disable the risk (to them) of "remote wipe".

**Additional context**

This is all premised on the throughness of remote wipe itself. That is, the remote user can always manually (or programmatically) copy all sync'd files to another location outside of the NextCloud client context, thereby rendering the remote wipe at best a partial success, possibly effectively a "no-op" (other than a declarative legal step). While I don't know of any mechanism for preventing this, it also means the user must take extra deliberate steps to prevent remote wipe's effect.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/43bc31bacb9082c02bc4b63fb1695ddcb1d7af84/config/config.sample.php#L1461-L1473

I didn't test it ;) If someone builds his own version of the nextcloud client and removes / suppress / changes the user-agent it's still possible to workaround this configuration option.

**Comment by r2evans** [comment]
That's the capability that I was suggesting, I didn't think to check that (I assumed it would be in the UI, bad on me).

Thanks.

I will say I'm a little concerned about that second paragraph, though ...

```
 * When changing this, note that older unsupported versions of the Nextcloud desktop
 * client may not function as expected, and could lead to permanent data loss for
 * clients or other unexpected results.
```

That to me suggests that the clients have not-so-graceful fail conditions. But that's a different issue.

To you comment about recompiling ... yes, and I believe that goes along with my previous assertion that the remote wipe functionality is really just doing two things: (1) keep the honest honest; and (2) provide declarative legal intent. As soon as the user starts taking any of these steps (copying out of the way, recompiling the client, changing headers), it becomes knowledgeable and willful intent to retain the data despite directives from the server.

Thanks, @kesselb!

**Comment by kesselb** [comment]
Hmm. It seems that we have different expectations of the remote wipe functionality. You're probably looking for something like a virtual data room.

**Comment by r2evans** [comment]
I don't know that we are. My expectation of "remote wipe" is to remove data from the remote computer if/when a remote user (for whatever reason) no longer needs or has permission to keep the data. The company might choose to trust the remote user, but I think with human nature that is not a 100% solution. The alternative is to remotely trigger a wipe on all of the data that the remote user has sync'd from the server. In that case, "remote wipe" does what it should.

Another level above that paranoia is a virtual data room, in which the remote user can view and *with significant limitations* interact with the data, but not download them. This is the next level of security/paranoia, I believe.

What I think you're suggesting is that if one doesn't trust that the remote user will delete all sync'd files on termination, then you should use a VDR. I don't argue that point, but then ... why "remote wipe"? It does nothing except automate an honest remote user's clearing of files. It provides no security, just an outreach to politely ask the remote user to enforce a policy.

I'm not knocking it, just calling it what I believe it to be: a polite request. In that context, perhaps my previous suggestion to enforce a minimum client version was over-stating the remote-wipe's capabilities.

**Comment by kesselb** [comment]
I lost my device / I don't have access to it anymore and want to remove my data. That's my expectation of "remote wipe" as home user ;)

https://github.com/nextcloud/server/issues/3456 here is the initial issue for remote wipe. 
https://github.com/nextcloud/server/issues/17152 another feature request

> I'm not knocking it, just calling it what I believe it to be: a polite request. In that context, perhaps my previous suggestion to enforce a minimum client version was over-stating the remote-wipe's capabilities.

Feel free to open a new enhancement if you have some ideas how to improve this feature. I'm not sure if there is way how to control what a user does with data on his device. Perhaps something like all the data from the server is encrypted and on access the nextcloud client will decrypt it temporary. _(just thinking out loud)_

**Comment by r2evans** [comment]
I think that's a better way for me to envision remote wipe, thanks for reminding me of that (I had seen it at one point and forgot about it). I think I envisioned what it could be used for and did not research it further to determine a good fit.

Thanks, @kesselb! That context was just what I needed.
