### ISSUE TITLE
Display app icon instead of user avatars as favicons / tab icons

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/server#17946]
I think it would make more sense here to have your app icons both in your tabs and your favorites
instead of your favicon everywhere.

**How to reproduce:**
1) install the theming app
2) Upload a favicon

**Expected behavior**
Your tabs display the favicon only in the files app (like the nextcloud logo if you don't have theming enabled)

**Actual behavior:**
Your tabs display the favicon everywhere

![Screenshot_20191114_194256](https://user-images.githubusercontent.com/26852655/68886297-3dc22f80-0717-11ea-92d1-b0e0fdcf2682.png)

![Screenshot_20191114_194654](https://user-images.githubusercontent.com/26852655/68886469-91cd1400-0717-11ea-9043-68856aa6891d.

**Comment by szaimen** [comment]
This works if you just don't upload a favicon -> closing.
