### ISSUE TITLE
Files are not encrypting in 17.0.1

### ISSUE THREAD

**Issue by arpan45** [nextcloud/server#17957]
- I have installed nextcloud 17.0.1 to my shared hosting.
- Enabled Encryption Module
- Enabled Encryption in Settings.
- Logged out and Logged in.
All the uploaded files in data folder are still accessible and opening from my filebrowser of hosting

**Comment by kesselb** [comment]
> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

From our issue template. GitHub is not a support channel.

> Encrypt all data files for all users. For performance reasons, when you enable encryption on a Nextcloud server only new and changed files are encrypted. 

https://docs.nextcloud.com/server/17/admin_manual/configuration_files/encryption_configuration.html

**Comment by DBJRdev** [comment]
Allow me a comment to @arpan45 : As far as I am aware, Nextcloud only encrypts newly uploaded files. From your description it seems you expected that older files are also being encrypted afterwards. Probably just a misunderstanding?

**Comment by kesselb** [comment]
> Allow me a comment to

Fine by me. 

> Nextcloud only encrypts newly uploaded files.

I already quoted that? ;) The documentation also explains how to encrypt existing files.
