### ISSUE TITLE
In Nextcloud Maintenance Mode branding reappears after theming

### ISSUE THREAD

**Issue by arpan45** [nextcloud/server#17950]
I have themed my nextcloud with custom logo and colour and changed the texts. But when I was updating to 17.0.1 and logged in from my browser it shows maintenance
mode with nextcloud logo, colours, branding. Fix this issue

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/5789

Unfortunately the theming app is not loaded during upgrade. Check the linked issue for all the technical details. Thanks for reporting this issue :+1:
