### ISSUE TITLE
Resource booking managment

### ISSUE THREAD

**Issue by el3ctrician** [nextcloud/server#17961]
**Is your feature request related to a problem? Please describe.**
it's not clear how to insert shared resources and how to book them

**Describe the solution you'd like**
Better document the resource management in nextcloud docs

i see a lot of work on the resource managment like #https://github.com/nextcloud/server/issues/17349  and #https://github.com/nextcloud/server/pull/9773 but i was not able to find it in the admin panel as for the pic from #https://github.com/nextcloud/server/pull/9773 

Seems like no option is available in the Admin panel to add resource. Could this be documented better ?

Thanks for the great work

**Comment by kesselb** [comment]
cc @georgehrke is this something for nextcloud/calendar?

**Comment by georgehrke** [comment]
We are currently providing an API to allow users to hook their own resource / room backends into the system. I'm also working on a UI for a simple database backend, but i don't have any ETA for that.

**Comment by el3ctrician** [comment]
Thanks a lot for the answer, can i find any documentation about these APIs ?

**Comment by fwolfst** [comment]
> Thanks a lot for the answer, can i find any documentation about these APIs ?

Oh yeah, if somebody finds a link, please put it here (even if the issue is closed, for achive reasons :) ).

**Comment by andreas-becker** [comment]
I could provide Frontend/VueJS knowledge if needed.

**Comment by kesselb** [comment]
@andreas-becker 👍 You may have a look at https://github.com/nextcloud/nextcloud-vue/ or other issues tagged with good first issue.

**Comment by Seriousness** [comment]
@georgehrke is there some further information on this?

**Comment by dkoeh** [comment]
Probably there are no plans for a continuation?

**Comment by dkoeh** [comment]
@georgehrke Is there any news on this topic - it is quite in demand in the forum as well as here on GitHub?
