### ISSUE TITLE
Opening subfolder don´t scroll to top if you enter with FF70 or later

### ISSUE THREAD

**Issue by AndyFx12** [nextcloud/server#17967]
### Steps to reproduce
1. Enter a long (= necessary to scroll down) folder list
2. scroll to bottom and jump to a subfolder
3. scroll to bottom and jump to a subfolder again

### Expected behaviour
Everytime you enter a subfolder, scrolling position should be on top.

### Actual behaviour
Sometimes scrollposition from previous folder is used; subfolder starts scrolling e. g. on bottom.
It seems to be a Firefox-Browser related problem:
 MS-Edge: good
 Firefox 69 on LinuxMint: good
 Firefox 70.0.1 on LinuxMint: bad
 Firefox on Android: good
 Chrome on Android: good
 Chromium 78.0 on Linux: good
 Firefox 70.0.1 or later on Windows 10: bad

### Server configuration

**Operating system**: 
Ubuntu 18.04

**Web server:**
Apache

**Database:**
pgsql 10.10

**PHP version:**
7.2.24

**Nextcloud version:** 
17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC 16

**Where did you install Nextcloud from:**
via Nextcloud-VM

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>
```

**List of activated apps:**
<details>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - music: 0.11.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - previewgenerator: 2.1.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - encryption
  - files_external
  - nextcloud_announcements
  - recommendations
</details>
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "trusted_domains": [
            "localhost",
            "192.168.1.3",
            "cloud.s-t-franz.de",
            "nextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud\/",
        "overwritehost": "cloud.s-t-franz.de",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "17.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "log_rotate_size": "10485760",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/mnt\/ncdata\/nextcloud.log",
        "logtimezone": "Europe\/Berlin",
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "calendar"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.
**Are you using encryption:** yes/no
No.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.

### Client configuration
**Browser:**
Firefox 70.0.1 
**Operating system:**
Windows 10 (1909) 64bit

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Totally agree, the position should be retained.

That is, when you navigate back up, the position ideally should be the same, instead of being at the very top again. This helps you have a sense of space and know where you are.

**Comment by AndyFx12** [comment]
I recently updated to NC18.0.0beta1 - problem is gone in this version. But should be fixed in NC17, too.

**Comment by jancborchardt** [comment]
@AndyFx12 could you find out which of the pull requests or commits fixed this issue? Then we can look into if backporting is feasible. :)

Closing this issue as it’s fixed on master though. Thanks a lot for testing and reporting back!
