### ISSUE TITLE
Multiple Files Selection

### ISSUE THREAD

**Issue by xNuno** [nextcloud/server#17978]
### Steps to reproduce
1. Go to a folder with some files inside
2. Search for something that return more than 1 result
3. Check the multi selection box on the top

### Expected behaviour
Only visible items should be selected.

### Actual behaviour
All files of the folder get selected.

![2019-11-17 18_20_45-Window](https://user-images.githubusercontent.com/8095169/69012011-b79d2780-0968-11ea-89a3-1835d118c2ca.png)

### Server configuration

**Operating system**: Docker

**Web server:** Latest

**Database:** Latest

**PHP version:** Latest

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Sounds familiar https://github.com/nextcloud/server/issues/14016 ;) I'm not sure how to reproduce. Could you elaborate?

![Peek 2019-11-17 20-43](https://user-images.githubusercontent.com/3902676/69012915-0b187100-097b-11ea-9de0-a5c487db28ae.gif)

**Comment by xNuno** [comment]
Check this out... I'm using latest Chrome...

![Demo](https://user-images.githubusercontent.com/8095169/69013041-a7d71080-0973-11ea-8390-142a6bed45c8.gif)

**Comment by kesselb** [comment]
cc @nextcloud/designers ;)

**Comment by jancborchardt** [comment]
Seems a JS issue, not design. :) Using the "select all" box should of course only select all files which are in the current list. That is, in that search which only shows 3 files, select only those 3 files.

cc @skjnldsv who worked on the fix for #14016 which indeed seems related (but I can’t judge that in detail).

**Comment by skjnldsv** [comment]
Theoretical planned behavior:
- When you're searching, we select all the items in the list
- When you're not, we select all the files in the folder (even if they're not shown)

@xNuno if you click move, and move the 6 selected files, are there really 6 moved files? Or is there only the three (meaning it's just a design glitch) ?

**Comment by xNuno** [comment]
Hi @skjnldsv ,

I was trying to simulate and I figured out a behavior that seems normal...

![Demo](https://user-images.githubusercontent.com/8095169/69499684-a1edac00-0eec-11ea-901f-86a2bb1a93f5.gif)

**Comment by skjnldsv** [comment]
Yes, I do not see anything wrong with this :/

**Comment by neufeind** [comment]
Important issue imho, since it went unnoticed when deleting a number of files that even more was deleted by accident :-(
As seen in the comment from Nov 17th when you search and try to check files for deletion it seems to check also files hidden by the search. This even gives more strange results in large folders with "paging" where not all files in the list were loaded to the client immediately and thus after "selecting all files" (from the search-result) and deleting them there were still files remaining in that folder.

**Comment by kesselb** [comment]
I'm not able to reproduce with Nextcloud 18 :disappointed: 

![Peek 2020-01-10 12-49](https://user-images.githubusercontent.com/3902676/72151239-fdde9800-33a7-11ea-83a6-2102eb9590cd.gif)

For reporting a bug use the issue template: https://github.com/nextcloud/server/issues/new/choose and add the detailed steps how to reproduce.

If you comment on other issues please make sure to include at least some relevant information. For example which Nextcloud version (even if the same as the initial report), probably there is something suspicious in the browser or server logs or a new fact to the inital report. Also visuals are a big help. I always include GIFs or screenshots in my report to make it easier for anyone else to reproduce it.

**Comment by neufeind** [comment]
Happened with latest stable (installed in production) for me, 17.0.2 at the moment. Will retest once 18 is out. It happened for me as in the screen-recording that someone posted above (as I wrote), so I didn't create my own again.

**Comment by kesselb** [comment]
> It happened for me as in the screen-recording that someone posted above (as I wrote), so I didn't create my own again.

I just asked you to provide concrete steps how to reproduce a problem. And your answer is "someone posted a screen recording earlier that's my problem". Is this some kind of weird joke? ;)

![image](https://user-images.githubusercontent.com/3902676/72158748-3b98ec00-33bb-11ea-83e3-09786fa1d08f.png)

It's possible to copy the link to a specific post with "Copy link". I just checked every visual in this thread again. It's primary about select / deselect. I don't see anyone using the delete action. Probably https://github.com/nextcloud/server/issues/14016 is the issue you mean? 

I just setup a fresh 17.0.2 install (via docker) and did the same steps as in https://github.com/nextcloud/server/issues/17978#issuecomment-573009195. Upload some files, use the search to filter the list, press select all, click delete. Files matching the search term are deleted. 

This report is closed. Feel free to open a new one here: https://github.com/nextcloud/server/issues/new/choose. Don't forget the detailed steps how to reproduce it. Without we are not able to fix this (probably) critical bug.
