### ISSUE TITLE
Click on accepting share, but nothing happens

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#17981]
mentioned in https://github.com/nextcloud/server/pull/16828#issuecomment-553272279, but should be discussed separately:
- be in files root view
- receive a share
- click "accept" on notification
- nothing happens
--> where is my file? ;-) I guess this might be irritating users.
--> can we check if we are in the folder where the shared item should pop up and do a reload?

@nickvergessen @rullzer

**Comment by nickvergessen** [comment]
Yeah, the notification app emits an event on actions:
https://github.com/nextcloud/notifications/blob/master/src/Components/Action.vue#L51

So the files app should listen to the event and reload when necessary.

**Comment by rullzer** [comment]
> Yeah, the notification app emits an event on actions:
> https://github.com/nextcloud/notifications/blob/master/src/Components/Action.vue#L51
> 
> So the files app should listen to the event and reload when necessary.

@skjnldsv could you look into that?

**Comment by skjnldsv** [comment]
> So the files app should listen to the event and reload when necessary.

sure!

**Comment by skjnldsv** [comment]
fix in https://github.com/nextcloud/server/pull/18222
