### ISSUE TITLE
Cronjob error on my Nextcloud server

### ISSUE THREAD

**Issue by giftedsheep** [nextcloud/server#17990]
Hi guys, i have been advised to post this error in my server log that im getting here. Do you have an idea what is causing it? 

Thank you
![Screen Shot 2019-11-17 at 1 07 46 PM](https://user-images.githubusercontent.com/57340720/69082163-63d82000-09f4-11ea-92a6-339ee25732fe.png)

**Comment by kesselb** [comment]
Please have a look at https://github.com/nextcloud/server/issues/17951

**Comment by giftedsheep** [comment]
@kesselb  Thank you for the reference, i looked through it but im not really sure how to address the issue. Any help?

**Comment by acs-ferreira** [comment]
Fix is already on master branch, will be pushed in the next updates.
