### ISSUE TITLE
Unable to grant access to linux sync client

### ISSUE THREAD

**Issue by GideonWolfe** [nextcloud/server#18001]
### Steps to reproduce
1. Install and set up latest Nextcloud Docker image
2. Install sync client to linux PC
3. Attempt to connect to server
4. Log in
5. Click grant access

### Expected behaviour
The app should be authorized and file synchronization should begin

### Actual behaviour
There is no spinner on the button, the page just sits there unresponsive

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** SQLite

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Official Docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Firefox 70

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

**Comment by GideonWolfe** [comment]
I added the line 'overwriteprotocol' => 'https', and seemed to have fixed things!

**Comment by 0xswitch** [comment]
> I added the line `'overwriteprotocol' => 'https',` and seemed to have fixed things!

Thank, it worked for me too
