### ISSUE TITLE
Update to 17.01 Error in time - locale

### ISSUE THREAD

**Issue by Schneehexe** [nextcloud/server#18015]
After the update to 17.01 the locale "Deutsch (Deutschland)" is faulty, because it shows one hour too early.
All calendar entries are also displayed too early.

The update was performed with the Web-based Updater.

**Comment by j-ed** [comment]
I cannot confirm what you've written. All my calendar entries are displayed correctly. Due to the fact that the time settings are mainly influenced by your server settings. I would recommend to check these settings first.

This small php script, which you can create on your server and open it in a wen browser, might show you your current server settings:
```
<?php
error_reporting(E_ALL);
echo "PHP Version: " . phpversion() . "<br>\n";
echo "<br>\n";

$inipath = php_ini_loaded_file();
if ($inipath) {
    echo "Loaded php.ini: " . $inipath . "<br>\n";
} else {
    echo "A php.ini file is not loaded<br>\n";
}
echo "<br>\n";

if (date_default_timezone_get()) {
    echo "date_default_timezone_set: " . date_default_timezone_get() . "<br>\n";
}

if (ini_get('date.timezone')) {
    echo "date.timezone: " . ini_get('date.timezone') . "<br>\n";
}
echo "Current date/time: " . date('d.m.Y H:i:s', time()) . "<br>\n";
echo "<br>\n";
?>
```

**Comment by Schneehexe** [comment]
The script returns the following:
```

date_default_timezone_set: Europe/Berlin
date.timezone: Europe/Berlin
```
So there would be everything correct.

The time under "Personal settings, locale is exactly one hour too early.

The problem only exists since the update to 17.01.

**Comment by Schneehexe** [comment]
After a new login, the Problem not exist.

Best regards

Am 19. November 2019 18:20:38 MEZ schrieb j-ed <notifications@github.com>:
>I cannot confirm what you've written. All my calendar entries are
>displayed correctly. Due to the fact that the time settings are mainly
>influenced by your server settings. I would recommend to check these
>settings first.
>
>This small php script, which you can create on your server and open it
>in a wen browser, might show you your current server settings:
>```
><?php
>error_reporting(E_ALL);
>echo "PHP Version: " . phpversion() . "<br>\n";
>echo "<br>\n";
>
>$inipath = php_ini_loaded_file();
>if ($inipath) {
>    echo "Loaded php.ini: " . $inipath . "<br>\n";
>} else {
>    echo "A php.ini file is not loaded<br>\n";
>}
>echo "<br>\n";
>
>if (date_default_timezone_get()) {
>echo "date_default_timezone_set: " . date_default_timezone_get() .
>"<br>\n";
>}
>
>if (ini_get('date.timezone')) {
>    echo "date.timezone: " . ini_get('date.timezone') . "<br>\n";
>}
>echo "Current date/time: " . date('d.m.Y H:i:s', time()) . "<br>\n";
>echo "<br>\n";
>?>
>```
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/18015#issuecomment-555614096

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by kesselb** [comment]
Thanks :+1: If you found a way how to reproduce it we can reopen.
