### ISSUE TITLE
Sharing via Link stopped working after update to 17.0.1

### ISSUE THREAD

**Issue by shadowlmd** [nextcloud/server#18014]
### Steps to reproduce
1. Try to share a file or directory via link
2.
3.

### Expected behaviour
Click on "Share link" opens a dialog with generated link and options, i.e. setting password, expiry, etc.

### Actual behaviour
Nothing happens at all, "Share link" text is static.

### Server configuration

**Operating system**: Ubuntu 16.04

**Web server:** lighttpd/1.4.35

**Database:** MySQL 5.7.28

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 16.0.6

**Where did you install Nextcloud from:** Built-in updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - dav: 1.13.0
  - encryption: 2.5.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - music: 0.11.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - accessibility
  - admin_audit
  - comments
  - files_external
  - support
  - survey_client
  - systemtags
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "redacted.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "https:\/\/redacted.tld",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "end_to_end_encryption"
        ],
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome 78.0.3904.97

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(empty)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(too much sensitive information and nothing related to the problem, I will provide this log only if you insist)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
(nothing related to the problem in browser log as well)
```
</details>

**Comment by shadowlmd** [comment]
Sharing via link works in Android app by the way, so it's just something in web UI is broken.

**Comment by shadowlmd** [comment]
Issue reproduces in Firefox 70.0.1.

**Comment by jmcclelland** [comment]
Does this happen with all files, including files that the currently logged in user owns? I'm having this problem with Nextcloud 16.0.5.1 but only with files that are being shared to my user by a different user.

Also #17630 might help.

**Comment by shadowlmd** [comment]
Yep, that happened with all files and directories, and indeed it was caused by uBlock Origin. Thanks!
