### ISSUE TITLE
Maitenance mode does not wotk with opcache timestamps disabled

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/server#18021]
Well, same as https://github.com/nextcloud/nextcloud-snap/issues/486 so `occ maintenance:mode --on` has no effect if PHP `opcache.validate_timestamps = 0`

I don't know if this affects other things (like core/apps updates) but if yes, this should be fixed too and clean opcache (or invalidate files) when necessary.

**Comment by kesselb** [comment]
Don't disable it ;) We should probably add this to the setup check. Technically there is no way to invalidate it because php-fpm and cli do not share the opcache. Check the notes at: https://www.php.net/manual/en/function.opcache-reset.php
