### ISSUE TITLE
Sort favorite files first in the list

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1802]
Favoriting is not very integrated at the moment. Only an indicator, we can do better here.

Better integration without needing to switch to a separate view would be to always sort the favorited items of a the current folder up top.

Already done in Android, ref https://github.com/nextcloud/android/issues/107 @nextcloud/javascript

**Comment by nickvergessen** [comment]
Just noting: the web UI get files in batches, so when you scroll down it preloads more files. But this means that the initial list of files may not contain all your favorites. SO only "some" will appear at teh top, unless this is added fully to the api, in which case n/javascript is the wrong mention. 😦

**Comment by jancborchardt** [comment]
Ah ok – how do we get the favorites in the files filter then? We should do it like there. cc @icewind1991

**Comment by nickvergessen** [comment]
The filter uses a completly different endpoint

**Comment by ryanwr** [comment]
I think the sorting should be done server side, I think I've got an idea of how to do it, I'll have a go

**Comment by ryanwr** [comment]
@nickvergessen I'm not sure if I'm missing something but does the client receive batches of files from the webdav server? How does the webdav server paginate requests?

**Comment by ChristophWurst** [comment]
@ryanwr the pagination is done on the client, which means the folder content it fetched with a single webdav request AFAIK.

**Comment by ryanwr** [comment]
@ChristopherWurst Thanks! That's helpful

**Comment by ryanwr** [comment]
Opened a PR, I'd appreciate feedback on it!

**Comment by rullzer** [comment]
Merged in #1860 thanks @ryanwr
