### ISSUE TITLE
Group share accepting/rejecting keeps re-triggering notifications for others

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18020]
regarding https://github.com/nextcloud/server/pull/16828

## Steps to reproduce

- Alice and Bob are members of group _foo_
- Trudy shares a file with group _foo_
- Alice gets a notification about the incoming group share
- Bob gets a notification about the incoming group share
- Alice accepts the share
- Bob rejects the share

### Expected behaviour
- nothing more, everyone reacted

### Actual behaviour
- Alice gets the same notification again about the incoming group share she already accepted earlier

#### side note
This happens no matter if Bob rejects or accepts the share.

**Comment by skjnldsv** [comment]
Please use appropriate labels

**Comment by rullzer** [comment]
Fix in #18294
