### ISSUE TITLE
notification of new nextcloud version - should include "not all your apps are available for this version"

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#18022]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ferdiga** [comment]
the notification is a good thing, but it pops up and you can't update because one or more installed apps are not available for the new version.
Hence - include text as mentioned in the title
or - do not show notification unless all apps are available.

**Comment by szaimen** [comment]
Unfortunately the described feature is not really high on our priority list. But this doesn't mean that we don't like the idea or that we are against this feature per se. Quite the opposite! 🙂
There are many way to get new features in Nextcloud:
1. The easiest and most straight forward way (especially here at Github): pull request.
Nextcloud is completely Free Software, this means that everyone is welcome to join and to contribute. If you or anyone else want to work on this feature, this would be great! We appreciate every pull request, and we are definitely able to help in case of questions, reviews, etc.
2. We have a category for Freelancers in our form. Another option would be to post an offer there and try to find a freelancer who want to work on it.
3. The most direct way for a company or organization to get the issue addressed is to get a Enterprise Subscription. This includes everything to enable you to run Nextcloud in a productive environment with guaranteed SLA's and more. The Enterprise Subscription also includes optional professional services such as custom development. Feel free to reach out to us. We are happy to explore the possibilities how to make Nextcloud fit your needs.
