### ISSUE TITLE
Updater 404

### ISSUE THREAD

**Issue by hheinen** [nextcloud/server#18038]
### Steps to reproduce
1. Login as Administrator
2. Navigate to Settings->Verwaltung(Administration?)->Übersicht(Overview?)
3. Click "Updater öffnen" (open updater)

### Expected behaviour
Updater should open.

### Actual behaviour
Not Found
The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.

### Server configuration

**Operating system**:
Ubuntu 18.04.3 LTS

**Web server:**
Apache/2.4.29 (Ubuntu)

**Database:**
 10.1.43-MariaDB-0ubuntu0.18.04.1

**PHP version:**
PHP 7.2.24-0ubuntu0.18.04.1

**Nextcloud version:** (see Nextcloud admin page)
16.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh trying to update to the latest stable

**Where did you install Nextcloud from:**
GIT

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - contacts: 3.1.6
  - dav: 1.9.2
  - deck: 0.6.6
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - gallery: 18.3.0
  - lookup_server_connector: 1.4.0
  - mail: 0.17.0
  - oauth2: 1.4.2
  - provisioning_api: 1.6.0
  - richdocuments: 3.4.4
  - spreed: 6.0.4
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - polls
  - sharebymail
  - testing
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "app.mail.transport": "php-mail",
        "trusted_domains": [
            "intranet.example.de"
        ],
        "force_language": "de",
        "force_locale": "de_DE",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.4.1",
        "overwrite.cli.url": "http:\/\/666.stratoserver.net\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": "1",
        "logdateformat": "F d, Y H:i:s",
        "app_install_overwrite": [
            "files_pdfviewer"
        ],
        "updater.release.channel": "production",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false
    }
}

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:**

Chrome Version 78.0.3904.108 (Offizieller Build) (64-Bit)

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by gary-kim** [comment]
The updater is not in this git repo. The updater is at [nextcloud/updater](https://github.com/nextcloud/updater).
