### ISSUE TITLE
hidden files are not syncronized from the server to the client

### ISSUE THREAD

**Issue by his-his** [nextcloud/server#18034]
### Steps to reproduce
1. Create hidden file (for instants. .text.lock or .~hello.lock) on the server shared folder
2. Synchronize the Nexcloud Client with the server
3. The file does not appear on the client folder

### Expected behaviour
The hidden file is now also in the client folder

### Actual behaviour
The hidden file does never appear on the client side.
I have removed these pattern ".~lock.*   ]*.~*  " from sync-exclude.lst in the client side. Now when I create a hidden file on the server it appears on the server, but when it is created or exists on the server is not synchronized with the server. It seems it is working only one way from the client to the server but not from the server to the client

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
> on the server shared folder

Could you elaborate that? Is that a external storage or you're creating files directly in the data directory? For changes to external storages https://docs.nextcloud.com/server/17/admin_manual/configuration_files/external_storage_configuration_gui.html#adding-files-to-external-storages is probably required.

**Comment by his-his** [comment]
I am using only local files.
I have a Nextcloud server and I am using the Linux Nexcloud client on two computers. When I open an Excel file on one client a lock file is created, I can see this file is copied on the server, but when I check the files from the other Nexcloud client it is not there, so the second client think the file is not opened thy the other client
I have also reproduced this creating the files directly in the data directory and they are not transmitted the client

**Comment by k9t9** [comment]
@his-his I have also noticed that but only on win clients. 
And same with files/ folders that ENDS with a dot. (`.`) as in #18066. 
I thought it was only a windows problem / fault of how windows handles files with a `.` and `/` prefix or surfix but now it might be that these bugs are related ? Can you confirm this also on Linux ?
