### ISSUE TITLE
User Documentation does not get updated during upgrade from 9.0.53 to 10.0.1

### ISSUE THREAD

**Issue by TheCasualObserver** [nextcloud/server#1804]
### Steps to reproduce

I did a manual upgrade fom 9.0.53 to 10.0.1 according to the steps found on https://docs.nextcloud.com/server/10/admin_manual/maintenance/manual_upgrade.html

After the upgrade the user documentation found under "/nextcloud/index.php/settings/help" still shows the "Nextcloud 9 User Manual Introduction". I would have expected that the User documentation gets updated to version 10.
The Administrator documentation however was updated as expected and the server functions fine in all other ways.

### Server configuration
**Operating system**:
Debian Jessie
**Web server:** 
Apache 2.4 behind a nginx reverse proxy
**Database:**
postgresql 9.4
**PHP version:**
5.6.26
**Nextcloud version:** (see Nextcloud admin page)
10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
9.0.53
**Where did you install Nextcloud from:**
Manual Install with occ from command line after downloading nextcloud-10.0.1.tar.bz2 from nextcloud.com/install
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: true
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - password_policy: 1.0.0
  - serverinfo: 1.1.1
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - notifications
  - provisioning_api
  - richdocuments
  - survey_client
  - systemtags
  - templateeditor
  - user_external
  - user_ldap
- user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc42zythkrem",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "SENSITIVE-DOMAIN.COM"
        ],
        "datadirectory": "\/srv\/www\/data",
        "overwrite.cli.url": "https:\/\/SENSITIVE-DOMAIN.COM\/nextcloud",
        "dbtype": "pgsql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "192.168.1.20",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 8.1
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
{"reqId":"Dmvc3dOhkU5\/MxqB9Ao0","remoteAddr":"","app":"core","message":"starting upgrade from 9.0.53.0 to 9.1.1.5","level":0,"time":"2016-10-19T12:47:03+00:00","method":"--","url":"--","user":"--"}
{"reqId":"XPn4vgRpm46x4YaQvxVk","remoteAddr":"192.168.1.4","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-10-19T13:54:18+00:00","method":"PROPFIND","url":"\/nextcloud\/public.php\/webdav\/","user":"--"}
{"reqId":"hRH9njDOftFtO\/cGTAk\/","remoteAddr":"192.168.1.4","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-10-19T13:54:45+00:00","method":"PROPFIND","url":"\/nextcloud\/public.php\/webdav\/","user":"--"}
```
</details>

**Comment by rullzer** [comment]
A, probabaly an error in the tarball build script. Let me summon @LukasReschke

**Comment by nickvergessen** [comment]
Can you verify that your `lib/private/legacy/defaults.php` contains
```php
$this->defaultDocVersion = '10'; // used to generate doc links
```
rather than
```php
$this->defaultDocVersion = '9'; // used to generate doc links
```

**Comment by TheCasualObserver** [comment]
Thanks for the fast responses.
Extract from lib/private/legacy/defaults.php:

                $this->defaultDocBaseUrl = 'https://docs.nextcloud.org';
                $this->defaultDocVersion = '10'; // used to generate doc links
                $this->defaultSlogan = $this->l->t('a safe home for all your data');

Today I had to reboot the server for a kernel upgrade and now the help site looks as it should with version 10 user documentation.

**Comment by rullzer** [comment]
Mmmm maybe something was cached then.
