### ISSUE TITLE
NC17 - Summary not aligned anymore

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#18053]
# Steps to reproduce
1. Just use as usually

### Actual behaviour
The summary isn't aligned with the column

Nextcloud 17
![17](https://i.imgur.com/c1opeBk.png)

Nextcloud 15
![15](https://i.imgur.com/bkdEWMx.png)

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache/2.4.6

**Database:**
 5.5.64-MariaDB

**PHP version:**
PHP 7.3.11

**Nextcloud version:** (see Nextcloud admin page)
17.0.1.1

**Updated from an older Nextcloud or fresh install:**
Both

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Are you using encryption:** no

### Client configuration
Chrome 78.0.3904.97 (64 bits)
Firefox 70.0.1 (64 bits)
Edge

**Comment by jancborchardt** [comment]
@GretaD this is possibly related to what you were working on regarding making stuff work for mobile screens?

**Comment by GretaD** [comment]
> @GretaD this is possibly related to what you were working on regarding making stuff work for mobile screens?

not sure, I will check and let you know.

**Comment by GretaD** [comment]
I reverted the changes i did here [17756](https://github.com/nextcloud/server/pull/17756) locally and the problem still exist, so its not caused by that. I will check it next week to see whats the problem
