### ISSUE TITLE
Remove hidden files/folders from summary

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#18056]
**Is your feature request related to a problem? Please describe.**
I would like to remove the possibilty for Nextcloud to count the hidden files/folders in the summary.

![NC](https://i.imgur.com/y4Zx9rd.png)

Nextcloud is showing me 1 Folder in the picture; but in the summary I have :

 `3 folders and 1 file (including 3 hidden)`

How can I show only `1 folder` in the summary ?

Also when I make select all and delete, it will also delete my hidden files/folders.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
