### ISSUE TITLE
NC17 - Weird behaviour with search function

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#18069]
### Steps to reproduce
1. Search files/folders into folders
2. Wait for end of the search
3. Click "X" button to clean the content of the searchbox content
4. The block searchresults is appearing at the bottom of the page

![NC](https://i.imgur.com/Z7Ua6Wu.png)

### Expected behaviour
The block searchresults shouldn't appear when no research is made

### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache/2.4.6

**Database:**
 5.5.64-MariaDB

**PHP version:**
PHP 7.3.11

**Nextcloud version:** (see Nextcloud admin page)
17.0.1.1

**Updated from an older Nextcloud or fresh install:**
Both

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Are you using encryption:** no

### Client configuration
Chrome 78.0.3904.97 (64 bits)
Firefox 70.0.1 (64 bits)
Edge

**Comment by skjnldsv** [comment]
Fixed nc20
