### ISSUE TITLE
two factor login color issue with bright colors (theming)

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#18077]
### Steps to reproduce
1. set a bright color in the theming app (e.g. #ffac00)
2. enable two factor auth for a user
3. login as this user

### Expected behaviour
Login looks like this:
![nc-twofactor-light-background](https://user-images.githubusercontent.com/6691165/69438059-babb5d80-0d44-11ea-9c84-65739073ead0.PNG)

### Actual behaviour
Login should look like this:
![nc-twofactor-light-background-readable](https://user-images.githubusercontent.com/6691165/69438114-c9097980-0d44-11ea-8e89-37c6970565d8.PNG)

### Cause of the Problem:
https://github.com/nextcloud/server/blob/3860373fd42091790ac2b00039cccd22e59d0ea5/apps/theming/css/theming.scss#L181

I've deleted this line for my instance. I haven't found any problems yet.

cc @juliushaertl @MorrisJobke

**Comment by nursoda** [comment]
Not only when registering 2FA upon 1st logon if enforced but also during regular 2FA login:
![image](https://user-images.githubusercontent.com/8425483/69683660-e24c5600-10b5-11ea-99b9-306a6370815c.png)

**Comment by JanDragon** [comment]
Fix: #18128

**Comment by MorrisJobke** [comment]
cc @ChristophWurst @skjnldsv

**Comment by nursoda** [comment]
Still the same in NC19:
![grafik](https://user-images.githubusercontent.com/8425483/86604590-db6bb700-bfa5-11ea-9d14-abf4e221e4a1.png)

**Comment by ChristophWurst** [comment]
@nextcloud/designers if anyone would like to work on this or needs some help with the 2FA setup please ping me :)
