### ISSUE TITLE
WebUI Update of 17.0.0.1 instance Fails at "Cleanup cypress files from viewer app" 

### ISSUE THREAD

**Issue by sproggit** [nextcloud/server#18097]
### Steps to reproduce
1. Attempt to log in to ISP-hosted instance of NC 17.0.0.1
2. Automatic prompt observed, indicating update required
3. Update runs, but fails at a "Repair Step" for "Cleanup cypress files from viewer app" 

### Expected behaviour
Hoped to have the ability to simply authenticate and access NextCloud

### Actual behaviour
The above error page/process appears to be stuck in a loop. 
There is an option automatically provided on the last line to "Please reload the page." which makes no difference

### Server configuration

**Operating system**:
Generic Linux ISP Server Build

**Web server:**
Apache 2.4.41

**Database:**
MariaDB-10.2.27

**PHP version:**
7.2.22

**Nextcloud version:** (see Nextcloud admin page)
17.0.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Downloaded the Zip from nextcloud.com
Unpacked locally
Transferred to ISP host via FileZilla

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
I can't, because I can't get in to my NextCloud instance at all... 
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Files
Activity
Gallery
Contacts
Calendar
Deck
Tasks

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Sorry, I do not have Command Line Access
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Sorry, I do not have Command Line Access
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
Update to 17.0.0

An error occurred.
Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Purify and migrate collected mail addresses
[0 / 0]: Purify and migrate collected mail addresses
Updated "mail" to 0.18.1
Checking for update of app "accessibility" in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app "bruteforcesettings" in appstore
Checked for update of app "bruteforcesettings" in appstore
Checking for update of app "calendar" in appstore
Checked for update of app "calendar" in appstore
Checking for update of app "cloud_federation_api" in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app "comments" in appstore
Checked for update of app "comments" in appstore
Checking for update of app "contacts" in appstore
Checked for update of app "contacts" in appstore
Checking for update of app "dav" in appstore
Checked for update of app "dav" in appstore
Checking for update of app "deck" in appstore
Checked for update of app "deck" in appstore
Checking for update of app "federatedfilesharing" in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app "federation" in appstore
Checked for update of app "federation" in appstore
Checking for update of app "files" in appstore
Checked for update of app "files" in appstore
Checking for update of app "files_mindmap" in appstore
Checked for update of app "files_mindmap" in appstore
Checking for update of app "files_pdfviewer" in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app "files_rightclick" in appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app "files_sharing" in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app "files_trashbin" in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app "files_versions" in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app "firstrunwizard" in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app "gallery" in appstore
Checked for update of app "gallery" in appstore
Checking for update of app "logreader" in appstore
Checked for update of app "logreader" in appstore
Checking for update of app "lookup_server_connector" in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app "mail" in appstore
Checked for update of app "mail" in appstore
Checking for update of app "nextcloud_announcements" in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app "notifications" in appstore
Checked for update of app "notifications" in appstore
Checking for update of app "oauth2" in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app "password_policy" in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app "privacy" in appstore
Checked for update of app "privacy" in appstore
Checking for update of app "provisioning_api" in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app "recommendations" in appstore
Checked for update of app "recommendations" in appstore
Checking for update of app "serverinfo" in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app "sharebymail" in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app "spreed" in appstore
Checked for update of app "spreed" in appstore
Checking for update of app "support" in appstore
Checked for update of app "support" in appstore
Checking for update of app "systemtags" in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app "text" in appstore
Checked for update of app "text" in appstore
Checking for update of app "theming" in appstore
Checked for update of app "theming" in appstore
Checking for update of app "twofactor_backupcodes" in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app "updatenotification" in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app "viewer" in appstore
Checked for update of app "viewer" in appstore
Checking for update of app "workflowengine" in appstore
Checked for update of app "workflowengine" in appstore
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair mime types
Repair step: Clean tags and favorites
Repair info: 0 tags of deleted users have been removed.
Repair info: 0 tags for delete files have been removed.
Repair info: 0 tag entries for deleted tags have been removed.
Repair info: 0 tags with no entries have been removed.
Repair step: Repair invalid shares
Repair step: Move .step file of updater to backup location
Repair step: Fix potential broken mount points
Repair info: No mounts updated
Repair step: Add log rotate job
Repair step: Clear frontend caches
Repair info: Image cache cleared
Repair info: SCSS cache cleared
Repair info: JS cache cleared
Repair step: Clear every generated avatar on major updates
Repair step: Add preview background cleanup job
Repair step: Queue a one-time job to cleanup old backups of the updater
Repair step: Cleanup invalid photocache files for carddav
Repair step: Add background job to cleanup login flow v2 tokens
Repair step: Remove potentially over exposing share links
Repair info: No need to remove link shares.
Repair step: Clear access cache of projects
Repair step: Cleanup cypress files from viewer app
An error occurred.
Please reload the page.

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by sproggit** [comment]
Just to add, navigating to the URL of the impacted server this morning, I see an alert message which reads, "Maintenance mode" ... This Nextcloud instance is currently in maintenance mode, which may take a while. This page will refresh itself when the instance is available again.

Contact your system administrator if this message persists or appeared unexpectedly." 

Not currently able to access the site at all...

**Comment by sproggit** [comment]
This is the on-screen trace log from the event:-

Update to 17.0.0

An error occurred.
Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Purify and migrate collected mail addresses
[0 / 0]: Purify and migrate collected mail addresses
Updated "mail" to 0.18.1
Checking for update of app "accessibility" in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app "bruteforcesettings" in appstore
Checked for update of app "bruteforcesettings" in appstore
Checking for update of app "calendar" in appstore
Checked for update of app "calendar" in appstore
Checking for update of app "cloud_federation_api" in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app "comments" in appstore
Checked for update of app "comments" in appstore
Checking for update of app "contacts" in appstore
Checked for update of app "contacts" in appstore
Checking for update of app "dav" in appstore
Checked for update of app "dav" in appstore
Checking for update of app "deck" in appstore
Checked for update of app "deck" in appstore
Checking for update of app "federatedfilesharing" in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app "federation" in appstore
Checked for update of app "federation" in appstore
Checking for update of app "files" in appstore
Checked for update of app "files" in appstore
Checking for update of app "files_mindmap" in appstore
Checked for update of app "files_mindmap" in appstore
Checking for update of app "files_pdfviewer" in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app "files_rightclick" in appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app "files_sharing" in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app "files_trashbin" in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app "files_versions" in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app "firstrunwizard" in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app "gallery" in appstore
Checked for update of app "gallery" in appstore
Checking for update of app "logreader" in appstore
Checked for update of app "logreader" in appstore
Checking for update of app "lookup_server_connector" in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app "mail" in appstore
Checked for update of app "mail" in appstore
Checking for update of app "nextcloud_announcements" in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app "notifications" in appstore
Checked for update of app "notifications" in appstore
Checking for update of app "oauth2" in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app "password_policy" in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app "privacy" in appstore
Checked for update of app "privacy" in appstore
Checking for update of app "provisioning_api" in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app "recommendations" in appstore
Checked for update of app "recommendations" in appstore
Checking for update of app "serverinfo" in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app "sharebymail" in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app "spreed" in appstore
Checked for update of app "spreed" in appstore
Checking for update of app "support" in appstore
Checked for update of app "support" in appstore
Checking for update of app "systemtags" in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app "text" in appstore
Checked for update of app "text" in appstore
Checking for update of app "theming" in appstore
Checked for update of app "theming" in appstore
Checking for update of app "twofactor_backupcodes" in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app "updatenotification" in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app "viewer" in appstore
Checked for update of app "viewer" in appstore
Checking for update of app "workflowengine" in appstore
Checked for update of app "workflowengine" in appstore
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair mime types
Repair step: Clean tags and favorites
Repair info: 0 tags of deleted users have been removed.
Repair info: 0 tags for delete files have been removed.
Repair info: 0 tag entries for deleted tags have been removed.
Repair info: 0 tags with no entries have been removed.
Repair step: Repair invalid shares
Repair step: Move .step file of updater to backup location
Repair step: Fix potential broken mount points
Repair info: No mounts updated
Repair step: Add log rotate job
Repair step: Clear frontend caches
Repair info: Image cache cleared
Repair info: SCSS cache cleared
Repair info: JS cache cleared
Repair step: Clear every generated avatar on major updates
Repair step: Add preview background cleanup job
Repair step: Queue a one-time job to cleanup old backups of the updater
Repair step: Cleanup invalid photocache files for carddav
Repair step: Add background job to cleanup login flow v2 tokens
Repair step: Remove potentially over exposing share links
Repair info: No need to remove link shares.
Repair step: Clear access cache of projects
Repair step: Cleanup cypress files from viewer app
An error occurred.
Please reload the page.

**Comment by wdfee** [comment]
Do you have ssh access for using occ commands? You can try to perform the upgrade again via command line. In my case it worked.

**Comment by kesselb** [comment]
I guess that's similar to #18277. It was there a issue with a custom mimetypemapping. @sproggit you fixed the issue somehow?

**Comment by sproggit** [comment]
I am sorry - this matter remains unresolved for me at the moment. I've not had the time to explore the issue more fully. The instance where I have the problem is hosted by an ISP, so I have a few restrictions on my ability to interact with it...

**Comment by skjnldsv** [comment]
This is fixed since a while now.
Please upgrade to latests releases of your version
