### ISSUE TITLE
Inconsistent WebDAV endpoints

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#18096]
The [documented](https://docs.nextcloud.com/server/stable/user_manual/files/access_webdav.html) url is `/remote.php/dav/files/USERNAME/`, but `remote.php/webdav/` is still exposed to the user interface:

https://github.com/nextcloud/server/blob/1074e9838b508aacaac8e8d49f9506d68402dafa/apps/files/templates/appnavigation.php#L44-L45
https://github.com/nextcloud/server/blob/1074e9838b508aacaac8e8d49f9506d68402dafa/lib/private/OCS/CoreCapabilities.php#L55

And some hardcoded endpoints are here:
https://github.com/nextcloud/server/tree/1074e9838b508aacaac8e8d49f9506d68402dafa/build/integration/features/bootstrap

**Comment by gary-kim** [comment]
Also hardcoded into some of my scripts and configs. Gonna have to go through to change that...

**Comment by nursoda** [comment]
What's the rationale to deprecate a static endpoint that depends on login credentials only? In terms of user documentation, it's far easier to have a static string users can cut'n'paste than /USERNAME/ …

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by gary-kim** [comment]
It's been changed on the frontend for files at this point, so I'd say that places still using the old endpoint should be reported as a separate more specific bug.

Let's close.
