### ISSUE TITLE
Newline missing in downloaded vcf file

### ISSUE THREAD

**Issue by brjhaverkamp** [nextcloud/server#18092]
### Steps to reproduce
1. Download a vcf file from your contacts app (A group or the total list).
2. Run fgrep BEGIN Contacts.vcf (Or whatever the name of the downloaded file is)

### Expected behaviour
Tell us what should happen
Expected behavior is that for every contact in the list you would see  a BEGIN:VCARD line 
### Actual behaviour
Instead you will find a lot of lines with END:VCARDBEGIN:VCARD
Tell us what happens instead

### Server configuration

**Operating system**:
Ubuntu

**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
17.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from way way back
**Where did you install Nextcloud from:**
Your website

This bug was confirmed by J-ed on the forum.

https://help.nextcloud.com/t/various-vcf-file-encoding-problem/64623/7

Kind regards,

Bert

**Comment by BernieO** [comment]
I tried to reproduce the issue, but my exported vcf files do have a CRLF between `END:VCARD` and `BEGIN:VCARD`.

> Instead you will find a lot of lines with END:VCARDBEGIN:VCARD

Are within your output of the fgrep-command also (correct) lines with only `BEGIN:VCARD` or does the complete output only contain lines like `END:VCARDBEGIN:VCARD`?

**Comment by kesselb** [comment]
```
fgrep BEGIN contacts-2020-01-24.vcf 
BEGIN:VCARD
BEGIN:VCARD
```

Seems to work with Nextcloud 18 :thinking: At least for me ;)
