### ISSUE TITLE
Adjust message "This server has no working Internet connection"

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#181]
Setup:
 * Mac behind a NAT router/firewall
 * runs Arch Linux in VirtualBox, virtual network interface bridged (i.e. it got its own IP address 192.168.1.144 from the NAT router/firewall)
 * inside, running UBOS development version in a container started with `systemd-nspawn -n` (i.e. system sets up its own private network and NAT, container is at 10.0.0.2/28)
 * running NextCloud in that UBOS container.

Nextcloud reports: "This server has no working Internet connection". That appears to be incorrect:

    > traceroute github.com
    1  gateway (10.0.0.1)  0.071 ms  0.013 ms  0.010 ms
    2  xxx (192.168.1.1)  0.507 ms  0.454 ms  0.422 ms
    3  comcast outside host ... and so forth

DNS is also configured correctly:

    > host github.com
    github.com has address 192.30.252.128

It seems that detection code might be a bit too aggressive.

**Comment by MorrisJobke** [comment]
All what the internet check does is:

- connect to `https://owncloud.org/`
- connect to `http://owncloud.org/`

If there is no error happening, then the connection is working. I will prepare a log output to give you maybe a hint, what happened.

**Comment by MorrisJobke** [comment]
For more details add following code between those lines: https://github.com/nextcloud/server/blob/4b90429178f8a72e330356ffb743b02c1c1904a1/settings/controller/checksetupcontroller.php#L100-L101

```php
\OC::$server->getLogger()->logException($e, ['app' => 'internet_connection_check']);
```

**Comment by MorrisJobke** [comment]
Then open the admin page again and check the log. Beside that it could also be the case, that the config.php option `has_internet_connection` is set to false.

**Comment by jernst** [comment]
It works today. Given your explanation, perhaps owncloud.org was temporarily down yesterday. Can I suggest to modify the error message to: "This server has no working Internet connection: it cannot reach http://owncloud.org/", in which I would have known what it attempted to do and figured out myself without logging a bug :-)

**Comment by MorrisJobke** [comment]
> Can I suggest to modify the error message to: "This server has no working Internet connection: it cannot reach http://owncloud.org/", in which I would have known what it attempted to do and figured out myself without logging a bug :-)

Makes sense :)

**Comment by lpszBuffer** [comment]
Hey guys, let me know if #374 looks suitable.
