### ISSUE TITLE
Long filenames cant upload

### ISSUE THREAD

**Issue by sloslo4** [nextcloud/server#18102]
### Steps to reproduce
1. Install fesh nextcloud on ubuntu (any version docker\snap\etc work)
2. upload big file name (just create *.txt with max limit on Windows )

### Expected behaviour
success upload

### Actual behaviour
upload fail

### Server configuration

bbb@fuck:~$ uname -a
Linux fuck 4.15.0-70-generic #79-Ubuntu SMP Tue Nov 12 10:36:11 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
bbb@fuck:~$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"

**Web server:**
apache2 -v
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2019-09-16T12:58:48

**Database:**

База данных
Тип: pgsql

Версия: PostgreSQL 10.10 (Ubuntu 10.10-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

Размер: 12,1 MB
**PHP version:**
PHP
Версия: 7.2.24

Ограничение памяти: 512 MB

Максимальное время выполнения: 3600

Максимальный размер для загрузки: 1000 MB

**Nextcloud version:** Nextcloud 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
official fresh installation

------------
Recently some users join to my nextcloud instance and want to upload some files, w filenames like this one:

ййцшугенегпыыгвафщгятфугшптугвшгтупгупгфтщшфщфцт ц ефцщ фцт щец е ьцф ецф ьфц щьфцщ ецфьцей опылвтмдг ввущцш едуфуыптд фт ефт ешфуг тефудге тдфуге тдфуги ефугши фугдшеифушгеифуг еифуг иф гшиегшфи угефи шифуг шфуеи егшфуи .pdf

that is not real name just obfuscated example, but name length is saved, that max length what u can do with Win* systems = 226 chars

when this user upload file on my nextcloud (fresh install) i got this (original length saved):
```

[webdav] Fatal: OCA\DAV\Connector\Sabre\Exception\InvalidPath: Имя файла слишком длинное. at <<closure>>

0. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/LockPlugin.php line 59
   OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath("ййцшугенегпыыгв ... t")
1. <<closure>>
   OCA\DAV\Connector\Sabre\LockPlugin->getLock(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
2. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array([OCA\DAV\Connect ... "], [Sabre\HTTP\Requ ... }])
3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 466
   Sabre\Event\EventEmitter->emit("beforeMethod", [Sabre\HTTP\Requ ... }])
4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
5. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
   Sabre\DAV\Server->exec()
6. /var/www/nextcloud/remote.php line 163
   undefinedundefinedrequire_once("/var/www/nextcl ... p")

PUT /remote.php/webdav/%D0%B9%D0%B9%D1%86%D1%88%D1%83%D0%B3%D0%B5%D0%BD%D0%B5%D0%B3%D0%BF%D1%8B%D1%8B%D0%B3%D0%B2%D0%B0%D1%84%D1%89%D0%B3%D1%8F%D1%82%D1%84%D1%83%D0%B3%D1%88%D0%BF%D1%82%D1%83%D0%B3%D0%B2%D1%88%D0%B3%D1%82%D1%83%D0%BF%D0%B3%D1%83%D0%BF%D0%B3%D1%84%D1%82%D1%89%D1%88%D1%84%D1%89%D1%84%D1%86%D1%82%20%D1%86%20%D0%B5%D1%84%D1%86%D1%89%20%D1%84%D1%86%D1%82%20%D1%89%D0%B5%D1%86%20%D0%B5%20%D1%8C%D1%86%D1%84%20%D0%B5%D1%86%D1%84%20%D1%8C%D1%84%D1%86%20%D1%89%D1%8C%D1%84%D1%86%D1%89%20%D0%B5%D1%86%D1%84%D1%8C%D1%86%D0%B5%D0%B9%20%D0%BE%D0%BF%D1%8B%D0%BB%D0%B2%D1%82%D0%BC%D0%B4%D0%B3%20%D0%B2%D0%B2%D1%83%D1%89%D1%86%D1%88%20%D0%B5%D0%B4%D1%83%D1%84%D1%83%D1%8B%D0%BF%D1%82%D0%B4%20%D1%84%D1%82%20%D0%B5%D1%84%D1%82%20%D0%B5%D1%88%D1%84%D1%83%D0%B3%20%D1%82%D0%B5%D1%84%D1%83%D0%B4%D0%B3%D0%B5%20%D1%82%D0%B4%D1%84%D1%83%D0%B3%D0%B5%20%D1%82%D0%B4%D1%84%D1%83%D0%B3%D0%B8%20%D0%B5%D1%84%D1%83%D0%B3%D1%88%D0%B8%20%D1%84%D1%83%D0%B3%D0%B4%D1%88%D0%B5%D0%B8%D1%84%D1%83%D1%88%D0%B3%D0%B5%D0%B8%D1%84%D1%83%D0%B3%20%D0%B5%D0%B8%D1%84%D1%83%D0%B3%20%D0%B8%D1%84%20%D0%B3%D1%88%D0%B8%D0%B5%D0%B3%D1%88%D1%84%D0%B8%20%D1%83%D0%B3%D0%B5%D1%84%D0%B8%20%D1%88%D0%B8%D1%84%D1%83%D0%B3%20%D1%88%D1%84%D1%83%D0%B5%D0%B8%20%D0%B5%D0%B3%D1%88%D1%84%D1%83%D0%B8%20.txt
from 192.168.0.14 by admen at 2019-11-25T11:09:56+00:00
```

I have something around 2k files like this and Desktop Client stuck.

```
 sudo getconf NAME_MAX /mnt/ncdata/
255

```

Help!

**Comment by sloslo4** [comment]
I already try rebuilding\patching kernel with many filesystems (reiserfs \ btrfs), with NAME_MAX = 1023 and no success, seems that limit at nextcloud itself. 

This is a very overshadowing mistake. have to move to another product apparently, if there is no solution

**Comment by juliushaertl** [comment]
Nextcloud has knowledge of the underlying filesystem and we have a default limit of 250 characters in our filecache table to support all common filesystems (ext2/3/4, xfs come with a 255 byte limit).
