### ISSUE TITLE
Sharing features missing after upgrading to 17

### ISSUE THREAD

**Issue by phoenixsoap** [nextcloud/server#18110]
After upgrading to 17 all of the sharing features are missing, I can't create a share link or even view the sharing pane. Apache2/PHP7.3/MariaDB. Additionally "Activity" loads endlessly. Version 16 was working flawlessly

I have removed of the 'social sharing via email' apps, etc and it did not resolve the issue.

**Comment by cly0514** [comment]
found the same problem,  in macos chrome the icon to create the share link is missing, while in windows chrome ,the icon exist.

**Comment by jmcclelland** [comment]
Maybe #17630 can help?

**Comment by phoenixsoap** [comment]
Thanks for the input. Unfortunately for me it happens on all the browsers available to me. Thankfully clients are still able to follow links I’ve already sent!

James

**Comment by phoenixsoap** [comment]
I logged in as another user (without admin privileges) and the user can see the icons that the files/folders are shared but they still cannot share the files.

Additionally the "Activity" section just says "Today" and has an endless spinning icon.

I wish I had never upgraded, it was working so well! Now NextCloud is basically useless for me. I tried deleting the folder and replacing with a fresh copy. I also tried the daily copy -- same issue. I used all the repair occ tools I could find. Please any help to fix this would be much appreciated. I don't want to buy a dropbox account!

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

A screenshot would be nice to better understand what's not working.
Also have you tried to disable adblocker? They block html element sometimes.

**Comment by phoenixsoap** [comment]
Thanks for your offer of help but I accidentally over-wrote the install dir while troubleshooting (and learned to never put the install in a directory named “nextcloud” or it could be easily over-written by a tar extraction!) which completely broke things so I can’t recreate this error anymore

James

**Comment by kesselb** [comment]
OK. I'm closing this one then ;) Please create a new report if that happens again.
