### ISSUE TITLE
Calendar attendees/invitations

### ISSUE THREAD

**Issue by steckerhalter** [nextcloud/server#1811]
So currently when someone creates an event and adds attendees it sends an email to those people and one has to use a client applications to be able to accept said event.

Shouldn't it also be possible to accept events via the Nextcloud web interface as well? Otherwise the calendar system is not really usable without an external client.

Thinking a bit further, if it would be possible to accept events in the web interface, the next step would be some kind of free/busy implementation.

Is there already some plan regarding these things?

**Comment by nickvergessen** [comment]
I think this should be reported at the calendar app, since that one provides the UI:
https://github.com/nextcloud/calendar/issues
