### ISSUE TITLE
NextHub (NextCloud Code Share App)

### ISSUE THREAD

**Issue by JanDragon** [nextcloud/server#18122]
Hey,

I just went through my thoughts and the idea of a NextHub App came to me. This is like several apps in the main menu a small button where users can create repos and add users. Otherwise with New Code detection and divisible by link. How do you like this idea?

Look forward to your messages. 
JanDragon

**Comment by szaimen** [comment]
Hi, please add your idea to this category https://help.nextcloud.com/c/apps/app-ideas/21 where it can be discussed with the community. Thanks! :)
