### ISSUE TITLE
set report-uri in config

### ISSUE THREAD

**Issue by jfqd** [nextcloud/server#18125]
**Is your feature request related to a problem? Please describe.**

Without a report-uri in the csp-headers it is not possible to get any violation report.

**Describe the solution you'd like**

It would be helpful if we could set report-uri in the configuration and it will be added to the csp-headers.

**Comment by neic** [comment]
FYI if this in going to be implemented: The `report-uri` is deprecated in favour of `report-to`. See [CSP3](https://w3c.github.io/webappsec-csp/#directive-report-uri). `report-to` is for now only implemented in Chrome. See [caniuse](https://caniuse.com/#feat=mdn-http_headers_csp_content-security-policy_report-to). The standard recommends to use both.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
