### ISSUE TITLE
cron.php randomly returns "something went wrong..." in web UI

### ISSUE THREAD

**Issue by kiv57** [nextcloud/server#18136]
### Steps to reproduce
1. Setup cron job according to the doc
2. See this working perfectly for years
3. Update NC (to 17.0.1) and other server packages, install some apps, forget what you did precisely
4. Go to https://your-nc-instance.tld/index.php/settings/admin, see randomly that something went wrong during last cron job (I see the message in french)
5. Disable last installed apps
6. See the same message from time to time

### Expected behaviour

Cron job should run without error each 15min

### Actual behaviour

Cron job randomly returns success or error in the web UI

### Server configuration

**Operating system**: Debian 9.11

**Web server:** Nginx 1.10.3

**Database:** MariaDB 10.4.10

**PHP version:** 7.3.11

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Regularly updated since owncloud 8

**Where did you install Nextcloud from:** Web updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - maps: 0.1.2
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocsms: 2.1.6
  - password_policy: 1.7.0
  - passwords: 2019.11.1
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - qownnotesapi: 19.9.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - bookmarks
  - encryption
  - files_external
  - keeporsweep
  - mail
  - news
  - passman
  - phonetrack
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "url.tld",
            "container.IP"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/url.tld",
        "default_language": "fr",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "theme": "",
        "maintenance": false,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "session_keepalive": true,
        "updatechecker": false,
        "trashbin_retention_obligation": "auto",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": true,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "calendar"
        ],
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No entry in `var/log/nginx/error.log`
```
</details>

#### Nextcloud log (data/nextcloud.log)

Last error is 2 days old, I disabled mail app since then

<details>
<summary>Nextcloud log</summary>

```
[PHP] Error: The each() function is deprecated. This message will be suppressed on further calls at /path/to/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed/Horde/Text/Flowed.php#211

POST /index.php/apps/mail/api/accounts/1/draft
from container.IP by user at 2019-11-25T14:34:56+00:00
```
</details>

**Comment by kesselb** [comment]
> [PHP] Error: The each() function is deprecated. This message will be suppressed on further calls at /path/to/nextcloud/apps/mail/vendor/pear-pear.horde.org/Horde_Text_Flowed/Horde/Text/Flowed.php#211

cc @ChristophWurst

**Comment by BernieO** [comment]
> Cron job should run without error each 15min

In the [Nextcloud 17 documentation about cronjobs](https://docs.nextcloud.com/server/17/admin_manual/configuration_server/background_jobs_configuration.html#cron) `cron.php` gets executed every 5 minutes (not every 15 minutes like with Nextcloud <= 16)

You see the red message that something went wrong after 10 minutes because the cronjob should have been running twice in a 5 minute interval, but it did not (because your cron.php gets executed every 15 minutes).

**Comment by kiv57** [comment]
> In the [Nextcloud 17 documentation about cronjobs](https://docs.nextcloud.com/server/17/admin_manual/configuration_server/background_jobs_configuration.html#cron) `cron.php` gets executed every 5 minutes (not every 15 minutes like with Nextcloud <= 16)

Oops, I overlooked this!
I'm probably responsible for missing this info. But has it imply a manual change on the web user crontab, I suggest it could be pointed out somewhere in the NC admin pages ?

Anyway, I read just now in `index.php/settings/admin` close to Background jobs : "last task executed 9 minutes ago" (personal translation from FR). Does it negate your solution ?

**Comment by LiloBzH** [comment]
ouch. same thing for me. Same error. I change 15 mins to 5 mins !

thank you for information ^^
