### ISSUE TITLE
nextcloud started duplicating users 

### ISSUE THREAD

**Issue by akurzawa** [nextcloud/server#18137]
Why nextcloud started duplicating users on the users list?

server version:
php: 7.3.10
mysql
Running Nextcloud 17.0.0.9
Latest patch level
Major version still supported

Im runnin this nextcloud instance for about a month, created about 30 users no problem since, today I've noticed that any new user is duplicated

how to fix that?

![image](https://user-images.githubusercontent.com/20043789/69731805-cdf67080-112a-11ea-9d44-3683938e2483.png)

**Comment by codmdu** [comment]
We have the same issue, the users will be reloaded and reloaded.
That means if i scroll down the same user will be appended to the end again and again and again.

We have 700+ users, which means it will load 700 then 1400 then 2100 etc.
Each time the images of the users will be loaded, after some seconds our browser needs 4+GB RAM and the browser stop the nextcloud.

(Can be reproduced without any plugins)

**Comment by akurzawa** [comment]
That started to happend after last update (from about 14.11.2019 - as far I remember)

**Comment by kesselb** [comment]
Fix #18142
