### ISSUE TITLE
DEVONthink + WebDAV not working (400)

### ISSUE THREAD

**Issue by cawilliamson** [nextcloud/server#1814]
### Steps to reproduce
1. Go to http://www.devontechnologies.com/download/products.html
2. Download DEVONthink Pro office (or Pro) trial
3. Go to Preferences -> Sync -> + -> Add WebDAV account
4. Set the URL as your nextcloud URL, username and password.
5. Set the store name + encryption keys to anything you like
### Expected behaviour

I would expect DEVONthink to start syncing. It does work properly with a docker container I found at https://hub.docker.com/r/morrisjobke/webdav/ so it does work with the WebDAV protocol.
### Actual behaviour

DEVONthink reports a 400 bad request error and refuses to sync.

I am using the URL: https://HOSTNAME:8443/remote.php/webdav/dav/files/admin/

(hostname removed for security purposes.)

```
Error log from nginx
10.0.0.101 - - [20/Oct/2016:11:54:08 +0100] "PROPFIND /remote.php/webdav/dav/files/admin/DEVONthink.dtCloud HTTP/1.1" 400 7021 "-" "DEVONcloudy 1.2.0"
10.0.0.101 - - [20/Oct/2016:11:54:08 +0100] "MKCOL /remote.php/webdav/dav/files/admin/DEVONthink.dtCloud HTTP/1.1" 400 7021 "-" "DEVONcloudy 1.2.0"
10.0.0.101 - - [20/Oct/2016:11:54:09 +0100] "PROPFIND /remote.php/webdav/dav/files/admin/DEVONthink.dtCloud HTTP/1.1" 400 7021 "-" "DEVONcloudy 1.2.0"
```
### Server configuration

**Operating system**: Alpine Linux

**Web server:** Nginx

**Database:** sqlite3

**PHP version:** 5.6.26

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** https://hub.docker.com/r/lsiodev/nextcloud (docker)

**Signing status:**
No errors have been found.

**List of activated apps:**
Default - unchanged from deployment.

**The content of config/config.php:**

```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'datadirectory' => '/data',
  'instanceid' => 'ocrr07hqewva',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' =>
  array (
    0 => '10.0.0.100:8443',
  ),
  'overwrite.cli.url' => 'https://10.0.0.100:8443',
  'dbtype' => 'sqlite3',
  'version' => '9.1.1.5',
  'logtimezone' => 'UTC',
  'installed' => true,
  'updater.release.channel' => 'stable',
);
```

**Are you using external storage, if yes which one:**

No

**Are you using encryption:**

No

**Are you using an external user-backend, if yes which one:**
No
### Client configuration

**Browser:**
N/A

**Operating system:** macOS Sierra (10.12)
#### Web server error log

```
10.0.0.101 - - [20/Oct/2016:11:54:08 +0100] "PROPFIND /remote.php/webdav/dav/files/admin/DEVONthink.dtCloud HTTP/1.1" 400 7021 "-" "DEVONcloudy 1.2.0"
10.0.0.101 - - [20/Oct/2016:11:54:08 +0100] "MKCOL /remote.php/webdav/dav/files/admin/DEVONthink.dtCloud HTTP/1.1" 400 7021 "-" "DEVONcloudy 1.2.0"
10.0.0.101 - - [20/Oct/2016:11:54:09 +0100] "PROPFIND /remote.php/webdav/dav/files/admin/DEVONthink.dtCloud HTTP/1.1" 400 7021 "-" "DEVONcloudy 1.2.0"
```
#### Browser log

N/A

**Comment by cawilliamson** [comment]
Anyone?

**Comment by nickvergessen** [comment]
Nothing in your nextcloud.log file?

**Comment by MorrisJobke** [comment]
Closing due to no feedback
