### ISSUE TITLE
SECURITY ISSUES: trying to conenct to http while over https

### ISSUE THREAD

**Issue by rami-dabain** [nextcloud/server#18155]
---
name: Bug report
about: Using http when on https
labels: bug, security
---

### Steps to reproduce
1. Install nextcloud with docker compose on home server
2. VPN with public server
3. Nginx on public server with proxy via ssl to home server

### Expected behaviour
Everything working fine

### Actual behaviour
Upon logging in, multiple tries to fetch/post data via http (blocked by the browser)

### Server configuration

**Operating system**: ubuntu server 19

**Web server:** nginx proxy over ssl > nginx of official docker-compose nextcloud installation

**Database:** mysql

**PHP version:** as setup in latest nextcloud docker-compose

**Nextcloud version:** as setup in latest nextcloud docker-compose

**Updated from an older Nextcloud/ownCloud or fresh install:** no - fersh install

**Where did you install Nextcloud from:** docker-compose. official documentation

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>
  - activity: 2.10.1
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - drawio: 0.9.4
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - lookup_server_connector: 1.5.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - survey_client: 1.5.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.0.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0

</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "LAN IP:PORT",
            "MY_DOMAIN_NAME"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "https:\/\/MY_DOMAIN_NAME",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    },
    "apps": {
        "accessibility": {
            "enabled": "no",
            "installed_version": "1.3.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "10"
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "1.7.1",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.6",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installedat": "1574358670.4321",
            "lastcron": "1574964605",
            "lastupdateResult": "[]",
            "lastupdatedat": "1574964035",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_default_permission_candelete": "no",
            "shareapi_default_permission_canshare": "no",
            "shareapi_default_permission_canupdate": "no",
            "shareapi_default_permissions": "5",
            "theming.variables": "***REMOVED SENSITIVE VALUE***",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.13.0",
            "sendEventRemindersPush": "yes",
            "types": "filesystem"
        },
        "drawio": {
            "DrawioLang": "auto",
            "DrawioOffline": "yes",
            "DrawioTheme": "kennedy",
            "DrawioUrl": "https:\/\/www.draw.io",
            "DrawioXml": "yes",
            "enabled": "yes",
            "installed_version": "0.9.4",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "no",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.4.0",
            "types": ""
        },
        "logreader": {
            "enabled": "no",
            "installed_version": "2.2.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "3.0.3",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "installed_version": "1.7.0",
            "minLength": "12",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "prevent_group_restriction"
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.5.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        },
        "spreed": {
            "conversations_files": "0",
            "conversations_files_public_shares": "0",
            "enabled": "yes",
            "installed_version": "7.0.2",
            "project_access_invalidated": "1",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "no",
            "installed_version": "1.0.1",
            "types": "session"
        },
        "survey_client": {
            "apps": "no",
            "database": "no",
            "enabled": "yes",
            "encryption": "no",
            "files_sharing": "no",
            "installed_version": "1.5.0",
            "php": "no",
            "server": "no",
            "stats": "no",
            "types": ""
        },
        "systemtags": {
            "enabled": "no",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.11.3",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "8",
            "color": "#000000",
            "enabled": "yes",
            "faviconMime": "image\/png",
            "installed_version": "1.8.0",
            "logoMime": "image\/png",
            "name": "Okitoo",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_admin": {
            "enabled": "no",
            "installed_version": "1.0.0",
            "types": ""
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "4.0.0",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "files_rightclick": "0.15.1",
            "installed_version": "1.7.0",
            "types": "",
            "update_check_errors": "0"
        },
        "user_external": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "types": "prelogin,authentication"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        }
    }
}

</summary>

</details>

**Are you using external storage, if yes which one:** unrelated

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** chrome / firefox / android app

**Operating system:** Linux / Android

#### Web server error log
<details>
<summary>Web server error log</summary>

no errors

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

not related

</details>

#### Browser log
<details>
<summary>Browser log</summary>

login?clear=1:1 Refused to load manifest from 'http://MyDomain/login' because it violates the following Content Security Policy directive: "manifest-src 'self'".

</details>

- Theming app tries to load elements from HTTP
- Manifest file stores url in HTTP `start_url`
Talk app (icon in header) has http link even when over https:
`<a href="http://YOUR_DOMAIN/apps/spreed/"...`
  
- `<meta property="og:url" content="http://domain/"/>`

- on logging in. it tries to redirect the user to http: notice in browser console:
`Refused to send form data to 'http://.../' because it violates the following Content Security Policy directive: "form-action 'self'".`

**Comment by kesselb** [comment]
Please use https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md for reporting issues.

**Comment by rami-dabain** [comment]
Added

**Comment by j-ed** [comment]
Have you searched the Nextcloud help forum for a solution of your problem, because similar requests have been addressed and answered there in the past:

https://help.nextcloud.com/search?q=docker%20nginx%20proxy

**Comment by rami-dabain** [comment]
Didn't find anything related there. however i found the issue.
in https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/Http/Request.php
the function getServerProtocol will not be able to get the correct protocol (https) if you are using a proxy.
to solve this I added :
`'overwriteprotocol' => 'https',`
to the config.php and everything is working now.

As this is related to security, forcing protocol must be an easy to access option in the administration panel. this does not even have a default in the config file!

**Comment by rullzer** [comment]
It is even in the docs under reverse proxy: https://docs.nextcloud.com/server/17/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse#overwrite-parameters
