### ISSUE TITLE
Can't read long username / email addresses in user management

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#18158]
In the Nextcloud user management email addresses and display names are cut-off after a certain length:

![image](https://user-images.githubusercontent.com/1589737/69854934-a74f4b80-128a-11ea-8373-72fe26492694.png)

It would be good if you could see somehow the full display name and email address. A simple solution which would solve the issue would be a tooltip on hover.

**Comment by bpcurse** [comment]
see #12779

**Comment by Nienzu** [comment]
Should this issue be closed?
