### ISSUE TITLE
Unable to access external SMB-storage through smartphone app with save in sessions

### ISSUE THREAD

**Issue by jocke92** [nextcloud/server#18168]
I don't know if this is a bug or feature request. But I've noticed that you are unable to access external SMB-storage through smartphone app. I'm using the  "Login credentials, save in session" with ldap.

Right know the link to the external storage is shown in the app but it doesn't work. Either show it as unavailable or make it work

**Comment by szaimen** [comment]
Sorry, this is more of a support question than a bug report. And that means you should either ask help from the volunteers on the forum at [help.nextcloud.com](help.nextcloud.com) (who can help you debug and turn it in a bug report if it is a bug) or, if this is important for your business, get a [Nextcloud subscription](https://nextcloud.com/pricing/) and we help you fix it in a few hours or days (according to the SLA).
