### ISSUE TITLE
Path to icon in theme

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#18160]
### Steps to reproduce
1. Create a theme and add a custom file /themes/example/core/templates/layout.user.php
2. Add a custom logo in img/logo
3. Use img tag to import the logo using path /themes/example/core/img/logo.png
4. File not found

My nextcloud is installed as follow domain/nextcloud

### Expected behaviour
Should show the picture

### Actual behaviour
Having 404 not found
### Server configuration

**Operating system**:
CentOS 7

**Web server:**
Apache/2.4.6

**Database:**
 5.5.64-MariaDB

**PHP version:**
PHP 7.3.11

**Nextcloud version:** (see Nextcloud admin page)
17.0.1.1

**Updated from an older Nextcloud or fresh install:**
Both

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Are you using encryption:** no

### Client configuration
Chrome 78.0.3904.97 (64 bits)
Firefox 70.0.1 (64 bits)
Edge

**Comment by kesselb** [comment]
Do you use `image_path` to generate the src for the img tag?
