### ISSUE TITLE
Can't create and use external storage backend

### ISSUE THREAD

**Issue by PhrozenByte** [nextcloud/server#18165]
I'm trying to register a new `local_unencrypted` external storage backend with [`cms_pico`](https://github.com/nextcloud/cms_pico) (see https://github.com/nextcloud/cms_pico/issues/37 for a reasoning). Creating a external storage mount using said external storage backend works just fine:

![Screenshot_2019-11-30 Settings - Nextcloud](https://user-images.githubusercontent.com/920356/69899477-008cad00-1367-11ea-8219-8d5aefa4887e.png)

However, for some reason the storage backend isn't loaded when accessing a mount using this external storage backend. A `Sabre\DAV\Exception\ServiceUnavailable` is being thrown instead.

```
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Unknown storage backend "local_unencrypted" at <<closure>>

 0. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/dav/lib/DAV/Tree.php line 76
    OCA\DAV\Connector\Sabre\Directory->getChild("Local")
 1. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/dav/lib/DAV/Server.php line 967
    Sabre\DAV\Tree->getNodeForPath("files/nextcloud/Local")
 2. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/nextcloud/Local", ["{DAV:}getlastm ... "], 1)
 3. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 4. <<closure>>
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 5. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
 6. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
 7. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 8. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/apps/dav/lib/Server.php line 317
    Sabre\DAV\Server->exec()
 9. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
10. /home/daniel-public/Projekte/GitHub/Pico/Nextcloud-2/remote.php line 163
    undefinedundefinedrequire_once("/home/daniel-pu ... p")

PROPFIND /projects/private/pico/Nextcloud-2/remote.php/dav/files/nextcloud/Local
from 127.0.0.1 by nextcloud at 2019-11-30T10:42:42+00:00
```

Testing on a fresh NC 17.0.1.

If I "inject" the `local_unencrypted` external storage backend directly into the `files_external` app (i.e. if I create local files in `apps/files_external/lib` using the code below) it works just fine, i.e. the code itself seems to work. It rather looks like the app simply isn't loaded.

Here's the code: https://github.com/nextcloud/cms_pico/commit/ab1fc9b444973cbce32e54f445093e0910c64610

By the way: The `<types></types>` element of `appinfo/info.xml` is undocumented.

**Comment by kesselb** [comment]
Try to add `<dav/>` to types.

**Comment by PhrozenByte** [comment]
This unfortunately doesn't seem to help @kesselb

**Comment by kesselb** [comment]
Sorry! I forgot an important step. `types` is cached [somehow](https://github.com/nextcloud/server/blob/af6c788efc81d7bf4d3aec6c267e545dcf4afad6/lib/private/legacy/app.php#L306). Try to disable the app, delete the types row from app_config table for the app, enable again.

**Comment by PhrozenByte** [comment]
Yeah, I was aware of this and updated `oc_appconfig` accordingly already. Still no luck unfortunately

**Comment by PhrozenByte** [comment]
Got it working :+1:

The issue is that one can't register a external storage backend via `Application::__construct()`. A app's `Application` class is instanced at multiple points in Nextcloud's request lifecycle, however, not all points are reached under all circumstances. This was a total mess to debug, since `Application::registerStorageBackend()` was indeed called for the (presumably important) `index.php/apps/files/?dir=/Local` request. However, since Nextcloud doesn't send enough requests yet, it issues another request that won't call `Application::registerStorageBackend()` - and here we got our issue.

Moving the whole thing to `appinfo/app.php` solved the issue, because that one seems to be executed under all circumstances unless the app is enabled. Neither `<type>dav</type>` nor `<type>filesystem</type>` seem to have any effect, they only seem to change in which order apps are being loaded.

Thank you for your help @kesselb! :+1:

**Comment by kesselb** [comment]
> class is instanced at multiple points in Nextcloud's request lifecycle, however, not all points are reached under all circumstances. This was a total mess 

Yes. Situation will improve for Nextcloud 18 https://github.com/nextcloud/server/pull/17509. I would always recommend to do hook registration (etc.) in appinfo/app.php.
