### ISSUE TITLE
l10n: Bug or misunderstanding in files_sharing string

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#18166]
https://github.com/nextcloud/server/blob/62dc32019146bdc186e110bde23dd210633acbe7/apps/files_sharing/src/components/SharingEntry.vue#L179

Shouldnt it be {group} instead of {user}?

https://github.com/nextcloud/server/blob/62dc32019146bdc186e110bde23dd210633acbe7/apps/files_sharing/src/components/SharingEntry.vue#L181

Shouldnt it be "{conversation}" instead of "{user}"?

**Comment by kesselb** [comment]
Probably {displayName} instead of {user} would be better. From the block above I assume that {user} is the displayName of the share.

cc @skjnldsv :mag:

**Comment by rakekniven** [comment]
> From the block above I assume that {user} is the displayName of the share.

Are you sure?

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/62dc32019146bdc186e110bde23dd210633acbe7/apps/files_sharing/src/components/SharingEntry.vue#L171-L176

> Are you sure?

No. Just guessing from above block ;)

**Comment by skjnldsv** [comment]
Yep, all good here ;)
