### ISSUE TITLE
Deleting long name files is problematic using the drag&drop method

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#18175]
This issue describes the process of deleting files using the drag&drop method.
### Steps to reproduce
1. Have a file with long name
2. Drag and drop it on the "Deleted files" to quickly move it to trash

### Expected behaviour
file is deleted

### Actual behaviour
problems occur with files having long names, see below:

![NC](https://user-images.githubusercontent.com/36133540/69913648-dc9a9b80-143a-11ea-9382-5287373c29d2.gif)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page) 16

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.2 but it only appears with files that have more than 50 characters (I've tested that 60 doesn't work), so it is pretty unlikely that this happens often. Additionally, there is the standard way of deleting the file: just use right-click to delete it.
cc @nextcloud/javascript Maybe there is an easy way to fix this?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
