### ISSUE TITLE
Users settings interface not updating when new user is added.

### ISSUE THREAD

**Issue by Rillian-Grant** [nextcloud/server#18177]
### Steps to reproduce
1. Create a new user and add it to a group (in my case it was admin) in the /settings/users interface

### Expected behaviour
When you create a new user the numbers in the left-hand pane representing the number of users in the group should update to represent the new number of users in the group.

### Actual behaviour
It doesn't update until you reload the page.

### Server configuration

**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.x

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** zip downloaded from official website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:** Chromium

**Operating system:** Ubuntu MATE

#### Browser log
<details>
<summary>Browser log</summary>

```
JQMIGRATE: Migrate is installed, version 1.4.1
(10) globals.js:26 The escapeHTML library is deprecated! It will be removed in nextcloud 19.
```
</details>

**Comment by kesselb** [comment]
cc @GretaD probably something after your user management rework.

**Comment by PVince81** [comment]
still happening in Nextcloud 22.2.0

**Comment by Rillian-Grant** [comment]
and version 23.0.0

**Comment by GretaD** [comment]
The update is done correctly, the problem is that is added in the end of the list. Can you @Rillian-Grant confirm? Maybe you didnt notice(like me) that is added there first.
https://user-images.githubusercontent.com/12728974/152326682-5f44f1ec-a23f-4649-ba27-dbc810007092.mp4

**Comment by Rillian-Grant** [comment]
Your video appears to be corrupted.

![Screenshot_20220203-104238.png](https://user-images.githubusercontent.com/26653150/152327457-d09fb17b-b80f-43a6-972b-b1f2ebe8627c.png)

**Comment by GretaD** [comment]
ah sorry, hope it works now as a gif
![usersadding](https://user-images.githubusercontent.com/12728974/152332211-6fe2f30e-15e6-462b-a50b-b585792ce861.gif)

**Comment by Rillian-Grant** [comment]
Sorry, it's very low resolution. Should I rephrase the problem?

**Comment by GretaD** [comment]
> Sorry, it's very low resolution. Should I rephrase the problem?

No, i think its clear enough, i just cannot reproduce. When i try to add a user, its added on the list without me loading it, but its not on the top of the list, but in the end, even though the name starts with A.

**Comment by Rillian-Grant** [comment]
Until I reload the page the numbers do not change.

https://user-images.githubusercontent.com/26653150/153728865-65875c1a-4c21-44f8-bf8b-850fcef4c656.mp4

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
