### ISSUE TITLE
Use sync feature of webdav

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18185]
https://greenbytes.de/tech/webdav/draft-daboo-webdav-sync-05.html

As far as I understand this would give client possibility to ask for changes from one state to the other, so that clients only get back changes and thus sync should be way faster.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage what do you think? Is this feasible?

**Comment by tobiasKaminsky** [comment]
Server: @rullzer @icewind1991 
client: @marinofaggiana @camilasan @misch7

**Comment by rullzer** [comment]
Nope.

Or let me put it differently. Not any time soon. It will require a monumental amount of work to keep all this state in the database. Plus we'd ahve to solve how to deal with stuff that changes on shares, external storages etc.

**Comment by tobiasKaminsky** [comment]
I am fine with any answer that is not "no" ;-)
It is just meant as a feature wish, so we do not forget the idea :-)

**Comment by rullzer** [comment]
So another ticket that stays open here for the next 4 years?

**Comment by szaimen** [comment]
Based on rullzer's comment I am closing this. Feel free to reopen this if you still want to leave it open.
