### ISSUE TITLE
[files_external] Global credentials (user entered) not working

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18195]
### Steps to reproduce
1. Configure one or more external storages with auth method _Global credentials, user entered_ (no matter if on admin- or user-side external storage config page)
2. enter global credentials on user external storage config page and save
3. hit the checkmark behind the external storage

### Expected behaviour
green checkmark, storage connects

### Actual behaviour
red exclamation mark, storage doesn't connect

#### Log when trying to connect SMB/CIFS
```
{
"reqId": "i9aJHt3OkFpI1ILuyEU8",
"level": 3,
"time": "December 02, 2019 21:23:17",
"remoteAddr": "####################",
"user": "####################",
"app": "PHP",
"method": "PUT",
"url": "/apps/files_external/userglobalstorages/4",
"message": "Undefined index: user at /var/www/nextcloudLatest/apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php#55",
"userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0",
"version": "17.0.1.1"
}
{
"reqId": "i9aJHt3OkFpI1ILuyEU8",
"level": 3,
"time": "December 02, 2019 21:23:17",
"remoteAddr": "####################",
"user": "####################",
"app": "PHP",
"method": "PUT",
"url": "/apps/files_external/userglobalstorages/4",
"message": "Undefined index: password at /var/www/nextcloudLatest/apps/files_external/lib/Lib/Auth/Password/UserGlobalAuth.php#56",
"userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0",
"version": "17.0.1.1"
}
```

### Server configuration

Operating system: Linux 4.15.0-69-generic #78-Ubuntu SMP Wed Nov 6 11:30:24 UTC 2019 x86_64

Webserver: Apache/2.4.41 (Ubuntu) (apache2handler)

Database: mysql 10.4.10

PHP version: 7.3.12-1+ubuntu18.04.1+deb.sury.org+1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, inotify, libsmbclient, Zend OPcache

Nextcloud version: 17.0.1 - 17.0.1.1

files_external: 1.8.0

# Side notes
1. SMB/CIFS tested after applying https://github.com/nextcloud/server/pull/17873/files
2. happens also when connecting other types (e.g. Nextcloud) - but all throw different logs

**Comment by icewind1991** [comment]
can't reproduce with either nc17 or master

**Comment by wiswedel** [comment]
I still can - even with master. I also get prompted for credentials once I try entering the folder from the files list.
CC @nextcloud/server-triage can anyone else try to reproduce this please?

**Comment by rullzer** [comment]
Nope seems to work for me as well with a webdav mount...

**Comment by blizzz** [comment]
works for me too on master, with an Nextcloud storage configured.

**Comment by wiswedel** [comment]
Maybe I'm misunderstanding the concept or I'm too stupid.
Here's what still happens for me on master:

not working with user entered global credentials:
![Peek 2019-12-19 14-16](https://user-images.githubusercontent.com/1804221/71176590-77341080-226a-11ea-9892-53b4e1ac2f7c.gif)


however with _normal_ global credentials, it's working:
![Peek 2019-12-19 14-17](https://user-images.githubusercontent.com/1804221/71176598-7ac79780-226a-11ea-997b-be76b344a240.gif)

**Comment by icewind1991** [comment]
try setting your global credentials under personal settings, not admin settings.

**Comment by wiswedel** [comment]
> try setting your global credentials under personal settings, not admin settings.

see 1st video, I did that

**Comment by blizzz** [comment]
in the first vid, instead i went to files directly and clicked on that storage. entering them there i did work. i ignored the personal settings tbh. Does it work for you if you go via Files, @wiswedel ?

**Comment by wiswedel** [comment]
> Does it work for you if you go via Files, @wiswedel ?

That does work. But that's the "User entered, store in database" behavior (when it's admin-configured, but the user hasn't entered the credentials on their personal settings page), not Global Credentials, user entered.

**Comment by blizzz** [comment]
nope, i selected global credentials in the storage config, too. So, at least it should not be the case imho.

**Comment by wiswedel** [comment]
Wow, interesting new discovery. I'll open a follow-up issue because the whole case just got another source.
Short story: _Global Credentials, user entered_ does work.

**Comment by wiswedel** [comment]
Sorry, let's stay in this one after all.

So I just found out that the stored user entered global credentials get deleted when you hit the connection check button.
If you just enter and save your credentials and head straight to the files list, it works.

**Comment by wiswedel** [comment]
> So I just found out that the stored user entered global credentials get deleted when you hit the connection check button.

That's by the way not obvious right away, but when you navigate away from the settings page and come back, you see the blank credentials fields.

**Comment by wiswedel** [comment]
still happening on NC 18.0.0 with files_external 1.9.0

**Comment by blizzz** [comment]
@wiswedel patch candidate in #19312
