### ISSUE TITLE
Update to 17.0.1, TimeTracker: NotNullConstraintViolationException

### ISSUE THREAD

**Issue by lewie** [nextcloud/server#18192]
Hello,
I got this screen instead of the login form, while updating Nextcloud/TimeTracker:

> Aktualisierung auf 17.0.1
> 
> 
> Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while executing 'ALTER TABLE oc_timetracker_work_interval ADD "details" VARCHAR(1024) NOT NULL': SQLSTATE[23502]: Not null violation: 7 ERROR: column "details" contains null values
> Update vorbereiten
> 
> Log-Level auf "debug" gesetzt
> Wartungsmodus eingeschaltet
> Reparaturschritt: Repair MySQL collation
> Reparaturinformation: Not a mysql database -> nothing to do
> Reparaturschritt: Repair SQLite autoincrement
> Reparaturschritt: Copy data from accounts table when migrating from ownCloud
> Reparaturschritt: Drop account terms table when migrating from ownCloud
> Das Datenbankschema wird aktualisiert
> Datenbank aktualisiert
> Doctrine\DBAL\Exception\NotNullConstraintViolationException: An exception occurred while 
> executing 'ALTER TABLE oc_timetracker_work_interval ADD "details" VARCHAR(1024) NOT NULL': > SQLSTATE[23502]: Not null violation: 7 ERROR: column "details" contains null values
> 
> Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

![grafik](https://user-images.githubusercontent.com/5707426/69967795-6f116c80-1519-11ea-8764-b49fe59454d1.png)

Is there a way to disable TimeTracker? Can't login anymore now.

Thank You!

**Comment by lewie** [comment]
Workaround:
1. Delete /var/www/nextcloud/apps/timetracker
2. Login
3. disable timetracker over GUI
4. Enable (and download) Timetracker-app.

Did not lose any data.

**Comment by kesselb** [comment]
https://github.com/mtierltd/timetracker/issues/24
