### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by sanchobear** [nextcloud/server#18194]
The nextcloud webgui displays version 17.0.1  channel stable, which was upgraded vom 17.0.0 recently.
Using the external security check from https://scan.nextcloud.com/ with the server url the version is displayed as 15.0.7.0, which was initially installed. How can that be resolved?

**Comment by kesselb** [comment]
https://help.nextcloud.com/t/beware-to-fall-into-the-trap-of-outdated-docs-and-false-advice/63366/18
