### ISSUE TITLE
Inherited shares design review

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#18202]
Design review :)
- [ ] Main row text should be either only "Others with access", or "4 others with access" with the number prepended: __decision is to never show the number__
- [ ] Agree with @rullzer, let’s use "Added by" instead of "Invited by", better language
- [ ] "Open folder" is a bit confusing as it’s unclear what it does. It opens the parent folder which this person got shared. Can we just write the folder name here, as per the mockup? If that’s not possible, we should write "Via parent folder".

For another pr as we should change all the other sharing entries using this wording & icon
- [ ] ~~"Delete share" sounds like it deletes some content. Can it be "Unshare"~~
- [ ] ~~Also, can it have the icon-close as icon instead of the delete icon?~~

Answering your questions @skjnldsv 

>     Should the "open folder" action open in a newt tab?

Yes, probably.

>     Should we display inherited shares that are exactly the opened folder ? (e.g I can currently see shares of the folder 123 when opening the list of inherited shares on the folder 123)

No? Cause they are just shares, not inherited shares? Or do I misunderstand?

_Originally posted by @jancborchardt in https://github.com/nextcloud/server/pull/15952#issuecomment-559504090_

**Comment by wiswedel** [comment]
>  Main row text should be either only "Others with access", or "4 others with access" with the number prepended: **decision is to never show the number**

Please make sure to align this with https://github.com/rullzer/sharelisting/

![image](https://user-images.githubusercontent.com/1804221/70998887-9438da00-20d8-11ea-804b-49dd862ee15c.png)

**Comment by jancborchardt** [comment]
(Just btw and for future reference if we ever include the number again: There is _no_ space before a ":" colon. :)

**Comment by skjnldsv** [comment]
Sorry, [french habits](https://fr.wikipedia.org/wiki/Deux-points) :p

**Comment by skjnldsv** [comment]
Followup in https://github.com/nextcloud/server/issues/18477
