### ISSUE TITLE
Header gradient looks weird if the app uses the primary blue colour

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#18229]
![Capture d’écran_2019-12-04_14-49-26](https://user-images.githubusercontent.com/14975046/70147846-5f269380-16a5-11ea-94d4-50aaba9bb8e9.png)

I find it very nice, but it will definitely conflict with other areas :/

**Comment by jancborchardt** [comment]
Don't really think it's a problem to be honest. It was similarly 2-colored with a simple header color, and it's also there when themed. :)

(In this case also the app does not use the primary blue color, but a placeholder for avatars.)
