### ISSUE TITLE
Files should have their separate link &scrollto= more prominent for internal sharing

### ISSUE THREAD

**Issue by salam** [nextcloud/server#18237]
**Is your feature request related to a problem?**
When sharing a file internally with team or family members, there is no easy way to get a URL quickly. Instead, one needs to share the path and mention the file name in question.

**Describe the solution you'd like**

1. Firstly, it would be great that the list has a button to share the URL including the &scrollto= parameter to the clipboard
2. ~~Secondly, when opening the details panel, the &scrollto= parameter should be added to the URL in the browser, making it possible to share files by copying the URL~~ (available now in NC17)
3. Thirdly, it would be great that this shared link of a file will highlight the file more prominently than only with the details sidepanel. 
4. ~~Fourthly, the URLs with the &scrollto= URL parameter are redirected and then hidden, resulting in sharing like mentioned above not possible.~~ (seems solved in NC17)
5. Fifthly, the sharing of those files should be also possible in the desktop integration apps to enable quick sharing while working on the computer.

**Describe alternatives you've considered**
I think the above solution is consistent with the rest of the design of NC and with web standards.
Alternatively, the AJAX crawling hash #! is deprecated and therefore not ideal. The &scrollto= parameter already exists
Even thou the naming of &scrollto= is maybe to specific to the function and not the description of the data in the URL, it could be renamed to &file= or something similar. However, renaming would imply updating external referrers from the past and would only have cosmetic advantages.

**Additional context**
Sharing files, in the browser, on the computer and in the app is important and used several times a day. The URL should be the center piece of the sharing experience and easily accessible to increase the usage of Nextcloud. As an artefact of the current state, my team members and family members don't share the Nextcloud files, but rather copy or screenshot files and then reupload them to WhatsApp, Slack and other tools, making NC somehow unnecessary.

Looking forward to your feedback and hopefully a great upcoming feature ;)

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/12877

**Comment by szaimen** [comment]
I think all points were fixed in the meantime -> closing.
