### ISSUE TITLE
Exception while running cron job

### ISSUE THREAD

**Issue by frlan** [nextcloud/server#18239]
From Log:

`Dec  5 08:00:02 xxxx Nextcloud[16515]: {"reqId":"oTM2fL2F4TEmQi30e6fi","level":3,"time":"2019-12-05T07:00:02+00:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":"{\"Exception\":\"TypeError\",\"Message\":\"Argument 1 passed to OCA\\\\DAV\\\\CalDAV\\\\Reminder\\\\ReminderService::parseCalendarData() must be of the type string, resource given, called in \\\/srv\\\/nc\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Reminder\\\/ReminderService.php on line 110\",\"Code\":0,\"Trace\":[{\"file\":\"\\\/srv\\\/nc\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Reminder\\\/ReminderService.php\",\"line\":110,\"function\":\"parseCalendarData\",\"class\":\"OCA\\\\DAV\\\\CalDAV\\\\Reminder\\\\ReminderService\",\"type\":\"->\",\"args\":[null]},{\"file\":\"\\\/srv\\\/nc\\\/apps\\\/dav\\\/lib\\\/BackgroundJob\\\/EventReminderJob.php\",\"line\":62,\"function\":\"processReminders\",\"class\":\"OCA\\\\DAV\\\\CalDAV\\\\Reminder\\\\ReminderService\",\"type\":\"->\",\"args\":[]},{\"file\":\"\\\/srv\\\/nc\\\/lib\\\/private\\\/BackgroundJob\\\/Job.php\",\"line\":61,\"function\":\"run\",\"class\":\"OCA\\\\DAV\\\\BackgroundJob\\\\EventReminderJob\",\"type\":\"->\",\"args\":[null]},{\"file\":\"\\\/srv\\\/nc\\\/lib\\\/private\\\/BackgroundJob\\\/TimedJob.php\",\"line\":55,\"function\":\"execute\",\"class\":\"OC\\\\BackgroundJob\\\\Job\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\BackgroundJob\\\\JobList\"},{\"__class__\":\"OC\\\\Log\"}]},{\"file\":\"\\\/srv\\\/nc\\\/cron.php\",\"line\":124,\"function\":\"execute\",\"class\":\"OC\\\\BackgroundJob\\\\TimedJob\",\"type\":\"->\",\"args\":[{\"__class__\":\"OC\\\\BackgroundJob\\\\JobList\"},{\"__class__\":\"OC\\\\Log\"}]}],\"File\":\"\\\/srv\\\/nc\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/Reminder\\\/ReminderService.php\",\"Line\":664,\"CustomMessage\":\"--\"}","userAgent":"--","version":"17.0.1.1"}`

### Steps to reproduce
1. I have ```*/15 * * * * php -f /srv/nc/cron.php > /dev/null 2>&1```inside my crontab for www-data-User (debian)
2.
3.

### Expected behaviour
Better error logging

### Actual behaviour
Unproperly handled exception in log

### Server configuration

**Operating system:**
Debian GNU/Linux 10.2

**Web server:**
Nginx 

**Database:**
PostgreSQL 10

**PHP version:**

PHP 7.3.11-1~deb10u1

**Nextcloud version:** (see Nextcloud admin page)

17.0.1.1 

**Updated from an older Nextcloud/ownCloud or fresh install:**

Ja.

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - apporder: 0.8.0
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - camerarawpreviews: 0.7.2
  - checksum: 0.4.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - encryption: 2.5.0
  - event_update_notification: 1.0.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_accesscontrol: 1.7.0
  - files_automatedtagging: 1.7.0
  - files_external: 1.8.0
  - files_markdown: 2.1.0
  - files_pdfviewer: 1.6.0
  - files_readmemd: 1.1.3
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - gpxedit: 0.0.12
  - gpxmotion: 0.0.10
  - gpxpod: 4.1.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 0.19.1
  - maps: 0.1.2
  - music: 0.11.1
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - socialsharing_facebook: 1.0.5
  - socialsharing_twitter: 1.0.5
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_usage_report: 1.1.2
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - files_videoplayer
  - theming
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.chaotenchaos.de",
            "frlan.stratum0.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud2.chaotenchaos.de",
        "dbtype": "pgsql",
        "version": "17.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "log_type": "syslog",
        "logfile": "",
        "loglevel": "3",
        "updater.release.channel": "stable",
        "data-fingerprint": "eafa99f477d6c0f73d28314b18806445",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_filesize_image": 100,
        "app_install_overwrite": [
            "calendar"
        ],
        "mail_sendmailmode": "smtp",
        "mail_smtpsecure": "tls"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

local storage only

**Are you using encryption:** yes/no

yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thanks :+1: Check https://github.com/nextcloud/server/issues/17951.
