### ISSUE TITLE
renaming an existing app

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#18232]
Hello NC team,

The **Data Analytics** was published this week with its internal id `analytics`

Now there is a report, that the combination app-name + js folder is blocked by privacy filter lists
https://github.com/Rello/analytics/issues/8
`/analytics/js$script`

I need to evaluate the possibilities

- keep the app and expect issues
- rename the app

what is the impact of the later one? As far as I know I would need to redistribute the app under a new name
- can the existing app be revoked from the app-store?
- is there a way of notifying the existing users about the new one? I think about pushing a version update to the old app-name which includes a remark to the new one
- or is there a migration process for changing an app (I don´t expect one)

any other suggestion?
thank you
Rello

**Comment by szaimen** [comment]
Hi, The Talk app wants to do the same in the future. Maybe this can be of some help?
https://github.com/nextcloud/spreed/issues/1979
