### ISSUE TITLE
Grid view for shared image folder

### ISSUE THREAD

**Issue by hoellen** [nextcloud/server#18246]
**Is your feature request related to a problem? Please describe.**
If you want to share an image folder, it is prettier to see the folder in grid view. But users who don't use Nextcloud regularly, don't know that they can toggle the view. 
So it would be nice, if the shared link is automatically opened with the right view. 

**Describe the solution you'd like**
Add the possibility to set the default view for a share.

**Alternatives solutions**
Remember grid decision for the shared link (see #12161).

**Additional context**
Related:  #12161

**Comment by jospoortvliet** [comment]
When a folder is shared from the gallery, it uses the gallery view - that's ideal for pictures. Going forward, with the new Photos app, this'll be even nicer and work better. And that view will, likely, be (better) integrated in our normal file view as well. So I think that, for now, this is a bit of a UI complication that won't be needed in the near future anyway and I would reject doing this for that reason.

Does that make sense, @hoellen?

**Comment by hoellen** [comment]
Thanks for your reply. Yes, I'm aware of the gallery sharing possibility. But unfortunately it doesn't show other media types  (e.g. videos) then images. That was the reason for my feature request.

But shortly after I posted here, I saw yesterday the new photo app you mentioned and this fits perfectly my expectations. :tada: I'm really looking forward to it!
