### ISSUE TITLE
Add notification about recommended apps for upgraded installs

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#18243]
We should probably add a notification for existing installations that upgrade to install the recommended apps.

@ChristophWurst @juliushaertl @jancborchardt

**Comment by juliushaertl** [comment]
Maybe just add that to the firstrunwizard, the existing recommended apps notifications still need to be adjusted there. 

@jancborchardt Which apps should be shown in the notifications now? Tasks, deck, maps?

**Comment by juliushaertl** [comment]
Or should we just get rid of the extra app recommendation notifications and show one for existing installations that goes to the recommended app store page.

**Comment by rullzer** [comment]
Photos probably

**Comment by rullzer** [comment]
Done in the firstrun wizard

**Comment by jancborchardt** [comment]
Sorry, seem to have missed it! So for existing installations, we show the following recommendations, right?
- Talk
- Calendar
- Contacts
- Mail

Photos will be shipped, right?

**Comment by juliushaertl** [comment]
Existing installations already got the notification for those apps when upgrading to 17. Not sure if we should add them again on top of the other recommended ones?

**Comment by jancborchardt** [comment]
> Not sure if we should add them again on top of the other recommended ones?

I would say yes. If we don’t want to do so many notifications, then I’d rather say for people upgrading we should recommend Talk, Calendar, Contacts and Mail instead of the new ones.

What do you think @karlitschek?

**Comment by karlitschek** [comment]
agreed. But only if they are not yet installed.
