### ISSUE TITLE
Cannot contact update server.

### ISSUE THREAD

**Issue by Grimeton** [nextcloud/server#18245]
Hi,

not sure if this is really a bug. For a few days now, 4-5 days probably, I always get alerts on desktop and on mobile that Nextcloud couldn't contact the update server. Three seconds later it tells me that there's an update for a module.

I updated the TOTP module now but the messages still seem to be coming and going randomly. 

The server is fine, packet filter is fine, DNS is working.

Any ideas?

KR,

G.

**Comment by Grimeton** [comment]
Hi,

what do you need exactly?

I'd have used the Form for NC17, but there's none released yet.


### Steps to reproduce
1. Run Nextcloud, see the warning on iPhone and on Nextcloud desktop client
2.
3.

### Expected behaviour
No warning should appear

### Actual behaviour
Warning appears...

### Server configuration

**Operating system:**
Linux
**Web server:**
Nginx
**Database:**
Postgresql
**PHP version:**
7.2.24
**Nextcloud version:** (see Nextcloud admin page)
17.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from ownCloud over several Nextcloud versions to 17.0.1
**Where did you install Nextcloud from:**
nextcloud.com
**Signing status:**
fine.
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.3.0
  - admin_audit: 1.7.0
  - audioplayer: 2.8.4
  - bookmarks: 2.3.1
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - deck: 0.7.0
  - dropit: 0.3.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notes: 3.0.3
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - twofactor_backupcodes: 1.6.0
  - twofactor_totp: 4.1.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - activity
  - camerarawpreviews
  - checksum
  - encryption
  - files_external
  - files_rightclick
  - firstrunwizard
  - survey_client
  - theming
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "17.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "maxZipInputSize": 0,
        "allowZipDownload": true,
        "theme": "",
        "maintenance": false,
        "overwritewebroot": "\/oc",
        "overwrite.cli.url": "\/oc",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
</details>

### Client configuration
**Browser:**
Don't know if the client uses a web engine at all.
**Operating system:**
Windows 10 1909 
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing in the webserver log.
```
Insert your webserver log here
``` 
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

``` nothing in the Nextcloud log. Yes, I checked multiple times, nothing.

Insert your Nextcloud log here
``` Don't have a log. It's showing on Desktop and on Mobile
</details>

#### Browser log
<details>
<summary>Browser log</summary>
No Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

This is what I get on the phone:
![image](https://user-images.githubusercontent.com/2773919/70276921-a00bce80-17b1-11ea-9786-7cab73601f0e.png)

KR,

G.

**Comment by kesselb** [comment]
Thanks for reporting issues back to Nextcloud :+1: 

Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

> what do you need exactly?

Logs
