### ISSUE TITLE
No way to accept shares if notifications app is not enabled

### ISSUE THREAD

**Issue by icewind1991** [nextcloud/server#18255]
Since https://github.com/nextcloud/server/pull/16828, when a file is shared but the notifications app is not installed, there is no way to accept the share nor is any feedback given, everything looks fine for the person creating the share, but the recipient doesn't see anything.

Not having the notifications app is probably not common (outside git dev installs) but it's not a force enabled app

@nickvergessen @rullzer

**Comment by nickvergessen** [comment]
Right, does federation still have a workaround for this, or are they also broken?

**Comment by rullzer** [comment]
Probably still has a workaround I bet. I can check later.

**Comment by nickvergessen** [comment]
This topic came up in the office today and @karlitschek said we dont need to workaround if people disable a default enabled shipped app.

But we should add a config to automatically accept shares in some bigger enviroments.

**Comment by karlitschek** [comment]
@jospoortvliet

**Comment by jospoortvliet** [comment]
Imho the user sharing settings should have a "automatically accept incoming shares" checkbox, disabled by default. This makes this feature opt-in which is probably the right thing to do as it is quite a change of behavior if we make this default.

An OCC command or config.php option for this is probably also needed.

**Comment by wiswedel** [comment]
Let's follow up on Jos' suggestion (that I fully agree on) in a separate issue: https://github.com/nextcloud/server/issues/18373

**Comment by rullzer** [comment]
See #18384 for the config.php setting
And #18385 for the user setting

The user setting will only be available if the config.php override is not set.

**Comment by wiswedel** [comment]
> The user setting will only be available if the config.php override is not set.

nice approach
