### ISSUE TITLE
Adjust loading gif to be same thickness as CSS version

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1825]
The thickness of the loading.gif and loading-small.gif are still 1px as opposed to the better visible 2px we use for the CSS version.

CSS version (left) and current gif (disregard the size – but see that the thickness differs)
![capture du 2016-10-20 18-00-03](https://cloud.githubusercontent.com/assets/925062/19597880/a01eebf2-9797-11e6-97a1-02487d2bbe0e.png)![](https://raw.githubusercontent.com/nextcloud/server/master/core/img/loading.gif)

This goes for all core/img/loading-*.gif files

We should redo it so they match. @skjnldsv how did you create them? cc @nextcloud/designers

**Comment by skjnldsv** [comment]
As I recall I created it with gimp and animated it. Did not realise I did a mistake :p

**Comment by Espina2** [comment]
@jancborchardt Can I suggest to post print screen when are design related issues. I see you sometimes post it, but others you dont. Its harder to me sometimes to see what you guys are talking about.

**Comment by skjnldsv** [comment]
:)

**Comment by jancborchardt** [comment]
(@Espina2 sure, normally I try to do but I was on mobile. Edited the original post with the images.)

**Comment by Espina2** [comment]
Awesome, I think they should have at least two pixel. In non retina monitor one pixel have a very weird "smothing".

**Comment by jancborchardt** [comment]
Yeah – what I meant is that the gifs should ideally be generated from the look of the CSS spinners so they look exactly the same. Including the light-grey static circle.
