### ISSUE TITLE
Error when hashtag in group's name 

### ISSUE THREAD

**Issue by hunhejj** [nextcloud/server#18267]
### Steps to reproduce
1. Create a group that starts with a hashtag, e.g. `#testme`
2. Open the group
3. `An error occured during the request. Unable to proceed.` notification appears
4. console reveals that a `404` error was raised by the server

### Actual behaviour
No operations can be performed on the group (listing users, deleting group, etc.). Tested with both Firefox & Chrome

### Server configuration

**Operating system:**
Docker-based NextCloudPi `v1.15.2` from latest official docker image

**Nextcloud version:**
`16.0.3.0`

**Comment by hunhejj** [comment]
Update NextCloudPi to most recent v1.18.0. Problem still exists.

**Comment by nickvergessen** [comment]
Can you try with 16.0.5 or 17.0.1?

**Comment by kesselb** [comment]
Is this probably fixed by https://github.com/nextcloud/server/pull/18257?

**Comment by hunhejj** [comment]
Tried with 16.0.5.1. Problem still exists.

**Comment by gary-kim** [comment]
Should be fixed by #18462. I only checked that deleting worked when making #18257. My bad.
