### ISSUE TITLE
Download Icon Remains and Lock Isn't Cleared

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#18269]
### Steps to reproduce
1. Download any file or folder.
2. Check if the icon reverts after download complete.
3. Check if you can delete the file / folder following the download being complete.
4. If you cannot delete, refresh the page and try again. It should now have the correct icon and be deletable.

### Expected behaviour
On completion of a file / folder download, the icon should return to it's original (the spinning circle is cleared) and the lock to prevent deletion before the download is complete released.

### Actual behaviour
On completion of a file / folder download, the icon remains greyed out with the spinning circle and the lock to prevent deletion before the download is complete is maintained. You have to refresh the page to clear the issue.

![image](https://user-images.githubusercontent.com/665111/70325056-fc5e0500-1828-11ea-8afa-627083e8e397.png)

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache

**Database:** MariaDB 10.3.18

**PHP version:** PHP 7.3.11

**Nextcloud version:** (see Nextcloud admin page) 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 16.X

**Where did you install Nextcloud from:**Download from Nextcloud site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - apporder: 0.8.0
  - bruteforcesettings: 1.4.0
  - camerarawpreviews: 0.7.2
  - cloud_federation_api: 1.0.0
  - dav: 1.13.0
  - extract: 1.2.2
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - jsloader: 1.0.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.10.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocr: 4.4.23
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - provisioning_api: 1.7.0
  - richdocuments: 3.4.5
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - theming_customcss: 1.4.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - uploaddetails: 0.1.2
  - video_converter: 0.1.2
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - activity
  - admin_audit
  - comments
  - deck
  - encryption
  - federation
  - files_versions
  - gallery
  - privacy
  - recommendations
  - support
  - survey_client
  - systemtags
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "xxxxxxxxxxxx",
            "xxxxxxxxxxxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "overwrite.cli.url": "https:\/\/xxxxxxxxxxxx",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "jsloader"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** Local. Separate drive mounted as dedicated storage for Nextcloud.

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome Version 78.0.3904.108 (Official Build) (64-bit)

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No Nextcloud errors.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors related to downloads.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No errors related to downloads.
```
</details>

**Comment by a1pilot** [comment]
@skjnldsv Is this something someone can look at? It cripples functionality.

**Comment by skjnldsv** [comment]
@a1pilot no time for it unfortunately :(

**Comment by PVince81** [comment]
not reproducible on Nextcloud 22.2.0, the icon properly reverts
