### ISSUE TITLE
Feature Request: Send notifications via Gotify for admins

### ISSUE THREAD

**Issue by hypervtechnics** [nextcloud/server#18261]
**Is your feature request related to a problem?**
Not a problem. More a conveince thing. I am using Gotify to receive notifications from my applications and monitoring tools.

**Describe the solution you'd like**
It would be nice if Nextcloud could do the same (i.e. send notification text via gotify) for the admin notifications when there is e.g. a new update for apps or NC itself.

**Describe alternatives you've considered**
A script to fetch notifications using the API and then send them via the script to gotify. This would: Expose some kind of access token in the script which has to run somewhere.

**Additional context**
Gotify is an open source push notification server written in Go. If offers a CLI and/or an HTTP API to send notifications.

*I know this a very low priority one ;-)...*

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by szaimen** [comment]
Please see https://github.com/nextcloud/talk-android/issues/257 for some work that already started in bringing push notificatioons to ungoogled phones.
Also, we have notify_push now.

**Comment by hypervtechnics** [comment]
I understand that. Will look into alternatives or helper tools. Nevertheless thanks for your effort
