### ISSUE TITLE
beta 1: sidebar broken in text and photos

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#18275]
The sidebar buttons in full screen views of Text and Photos don't work for me on both a fresh and upgraded installs and on firefox and chromium. Guess file viewer issue? Maybe needs to be in https://github.com/nextcloud/viewer ??? @skjnldsv -> might be your area :smiling_imp:

**Comment by skjnldsv** [comment]
No labels? Wrong repo? ^^
Yes, this is known and will be fixed soon https://github.com/nextcloud/photos/issues/22
