### ISSUE TITLE
Deleting profile pictures is not possible, again

### ISSUE THREAD

**Issue by paulocoghi** [nextcloud/server#18276]
**Nextcloud version:** 17.0.1

The issue reported on #7500 is happening again, because we can't delete the current profile picture. The button for deletion isn't appearing.

![b2d6d8b8-0f9f-4306-9a96-700c7d545b08](https://user-images.githubusercontent.com/19711361/33964362-73245960-e058-11e7-8895-31f24248e7c0.jpeg)

**Comment by gary-kim** [comment]
cc @nextcloud/javascript

**Comment by kesselb** [comment]
Probably fixed by https://github.com/nextcloud/server/pull/18505

**Comment by skjnldsv** [comment]
@kesselb it's merged, is it fixed then? :p

**Comment by kesselb** [comment]
For Nextcloud 18 yes. Not sure if the repair job is backportable :thinking:

**Comment by MorrisJobke** [comment]
Fixed in 18.
