### ISSUE TITLE
[Transfer ownership] Receiver not informed about transfer taking some time

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18272]
While the ownership transfer initiator sees a hint, _It may take some time until the process is done_, the receiver doesn't know that the transfer actually happens with the next background job (which could take some time, depending on the server config). So the receiver has to assume something went wrong after accepting but not seeing anything coming in.

**Comment by jospoortvliet** [comment]
The receiver doesn't know when the initiator did it anyway, right? There is no notification that says "you received these and these files", certainly not before you actually did. So they have no expectation other than what the initiator might tell them, and the initiator knows that it takes some time (if he/she saw the hint), which seems sufficient to me.

**Comment by rullzer** [comment]
So we just update the initial acceptance notification that it can take some time?

**Comment by wiswedel** [comment]
> So we just update the initial acceptance notification that it can take some time?

Fine for me

**Comment by rullzer** [comment]
> > So we just update the initial acceptance notification that it can take some time?
> 
> Fine for me

Care to shoot in a PR yourself? SInce you already touched the code. And then you can word it how you think it should be worded ;)
