### ISSUE TITLE
trusted_proxies should be settable via the web-ui

### ISSUE THREAD

**Issue by teotikalki** [nextcloud/server#18286]
### Steps to reproduce
1. Install nextcloud behind nginx reverse proxy
2. Web-UI admin overview gives warning: "The reverse proxy header configuration is incorrect, or you are accessing Nextcloud from a trusted proxy. If not, this is a security issue and can allow an attacker to spoof their IP address as visible to the Nextcloud. Further information can be found in the documentation."
3. The only way to fix this is to manually edit the file /var/www/html/nextcloud/config/config.php (or whatever on your install) and add the block
  'trusted_proxies' => 
  array (
    0 => 'x.x.x.x',
  ),

### Expected behaviour
Since this file can be modified by Nextcloud, I expect to be able to add trusted proxies from the front end. The warning should link to the setting for this.

### Actual behaviour
See above Step 3

### Server configuration

OS: Debian Stretch (latest) in SmartOS lx zone
Web server: apache
Database: PostgresQL
PHP version: 7.3 (sury repository)
Nextcloud version: 16.0.6 (Channel: Production), fresh install

Where did you install Nextcloud from: wget https://download.nextcloud.com/server/releases/latest-16.zip

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
