### ISSUE TITLE
Requested uri () is out of base uri - BUG when cirillic symbols in path

### ISSUE THREAD

**Issue by Alexandr-X** [nextcloud/server#18298]
Eng paths work properly... but cirillyc not work... NC version: 17.0.1

![изображение](https://user-images.githubusercontent.com/58692653/70437238-f37d6580-1aac-11ea-90c6-2cfcbd99ef2c.png)

Error log:

Sabre\DAV\Exception\Forbidden: Requested uri () is out of base uri (/remote.php/dav/)

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 549:

Sabre\DAV\Server->calculateUri("")

/var/www/nextcloud/apps/dav/lib/Server.php - line 323:

Sabre\DAV\Server->getRequestUri()

/var/www/nextcloud/apps/dav/lib/Server.php - line 149:

OCA\DAV\Server->requestIsForSubtree([ "calendars ... "])

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 34:

OCA\DAV\Server->__construct(OC\AppFramework\Http\Request {}, "/remote.php/dav/")

/var/www/nextcloud/remote.php - line 163:

require_once("/var/www/ne ... p")

Ideas? )

Some error event some time to time raise:

LogicException:

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1296:

Sabre\HTTP\Request->getPath()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->checkPreconditions(Sabre\HTTP\R ... l}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... l}, Sabre\HTTP\Response {})

/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php - line 80:

Sabre\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 163:

require_once("/var/www/ne ... p")

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
