### ISSUE TITLE
18.0.0 Beta1 - Encryption error (fix included)

### ISSUE THREAD

**Issue by MartB** [nextcloud/server#18295]
Hey there, i get the following log on the latest beta

```
TypeError: Argument 3 passed to OCA\Encryption\Recovery::__construct() must be an instance of OCA\Encryption\KeyManager, instance of OC\Security\SecureRandom given, called in /usr/share/nginx/c/apps/encryption/lib/AppInfo/Application.php on line 173
```

Did i break something or what do i have to do to get rid of this?

Additionally i always get this:
`Encryption App is enabled, but your keys are not initialized. Please log-out and log-in again.`

**Comment by MartB** [comment]
This is caused by the wrong order of constructor arguments here:
https://github.com/nextcloud/server/blob/63a2725f3d38fe8e5e767cd62f65330776435811/apps/encryption/lib/AppInfo/Application.php#L167

**Comment by kesselb** [comment]
Regression from https://github.com/nextcloud/server/pull/15936
