### ISSUE TITLE
Recommendations for Configuring Memory Caching

### ISSUE THREAD

**Issue by b1ggjoe** [nextcloud/server#183]
Team,

I'm getting ready to setup my Nexcloud Server. I'm currently running PHP 5.5. I've already read through the information here: https://docs.nextcloud.org/server/9/admin_manual/configuration_server/caching_configuration.html 

Just need some clarification and guidance:

- First off, should I stay at 5.5 or do you recommend that I upgrade?

- What about using either XCache or eAccelerator ?

Thanks!

J.

**Comment by MorrisJobke** [comment]
> First off, should I stay at 5.5 or do you recommend that I upgrade?

What you feel comfortable with.



> What about using either XCache or eAccelerator ?

Feel free to activate XCache to speed up the loading time of the PHP.

:)

**Comment by MorrisJobke** [comment]
And this is also the bug tracker. Please open such requests in the forums next time ;) https://help.nextcloud.com/

**Comment by b1ggjoe** [comment]
Ok will do, but thank you very much!!

J.

**Comment by b1ggjoe** [comment]
@MorrisJobke,

I forgot to ask! In the Config.php...how do I configure/reference XCache?

Thanks!

J.

**Comment by MorrisJobke** [comment]
> I forgot to ask! In the Config.php...how do I configure/reference XCache?

Sorry to say that: This is not a support forum. Just google for it :( There is nothing in the config.php to configure. This is a PHP thing to setup.

**Comment by b1ggjoe** [comment]
No problem at all, thank you very much. I wasn't sure because the
documentation had shown examples for like APCu and etc. So just wanted to
make sure.

Thank you though.

;-)

J.

**Comment by MorrisJobke** [comment]
> for like APCu and etc.

Stuff like XCache (APC, eAccelerator, ...) caches preprocesses PHP code. APCu, Redis and Memcached cache data. So those are different kind of caches for different cases.
