### ISSUE TITLE
improve "Space used" Label / User Quota View

### ISSUE THREAD

**Issue by SB97** [nextcloud/server#18303]
**Is your feature request related to a problem? Please describe.**
I had the problem that my Server was full and after looking around i found out that nearly 50% of my Quota was bound in Deleted files and a few Megabits in File Versions (But in don´t know how much exactly from the Front End).

This is the only Data the Front End gave me:
![grafik](https://user-images.githubusercontent.com/20126520/70459697-9e415400-1aac-11ea-9d4f-fdbca8aa3b6b.png)

As an Admin i got this information as Admin User under Users:
![grafik](https://user-images.githubusercontent.com/20126520/70459770-c761e480-1aac-11ea-88ca-0bd0c3fdd8b9.png)

**Describe the solution you'd like**
For the Users Tab:
![grafik](https://user-images.githubusercontent.com/20126520/70460005-48b97700-1aad-11ea-8e71-3fe8a5305ac6.png)
a grafikal representaion of the storage usage. In my very good paint example i used orange for File Versions and Red for deleted Files.

On the main Screen a pie chart on click or hover like the Icon already suggests ;)

**Describe alternatives you've considered**
Maybe a Notification with Usage report for the user when the Quta gets near the max.

**Additional context**

**Comment by szaimen** [comment]
cc @nextcloud/designers Do you have some input on this?

**Comment by skjnldsv** [comment]
We had that, we removed it as a feature request and simplification :grin: 
Sorry, this will stay as is
