### ISSUE TITLE
unable to access folders via WebDav when U2f secondary authentication is active

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#18315]
I'm trying to map network drives under windows using url you reported at the bottom left of the web screen files section

`https://tigernero.duckdns.org/remote.php/webdav/`

oppure usando la path then user

`https://tigernero.duckdns.org/remote.php/dav/files/Tiger`

in both cases it asks me for the user credentials that I insert correctly but I get error credentials. I was wondering if the fact of having the second authentication factor u2f active would cancel the possibility of connecting via webdav

![Immagine](https://user-images.githubusercontent.com/35575744/70514377-d5a71380-1b33-11ea-8c67-f82c0cce0969.png)

**Comment by rullzer** [comment]
You have to go to your security settings and generate an app password.
