### ISSUE TITLE
Add ability to hide download button when sharing with email

### ISSUE THREAD

**Issue by jhesketh** [nextcloud/server#18318]
**Is your feature request related to a problem? Please describe.**
I can hide the download button for link shares, but not for shares made with email addresses.

**Describe the solution you'd like**
As a user, I would like to be able to hide the download button regardless of sharing method.

**Describe alternatives you've considered**
Only sharing by link. This would require me to send an email manually each time to the recipient. But it also makes cancelling links hard as I can't tell who I have shared what with.

**Comment by wiswedel** [comment]
@jhesketh Not sure if it was already possible in 17, but in 18 this is available.

**Comment by jhesketh** [comment]
So I just checked and there is now a box to disable downloads for email shares (this was not there before, so must be new in 18 I think).

However, ticking the box does not work. On refresh of the page the box is always unticked. This is true for new and existing email based shares.

**Comment by wiswedel** [comment]
> However, ticking the box does not work. On refresh of the page the box is always unticked. This is true for new and existing email based shares.

That's indeed a harsh bug. Let me file a bug issue and reference it here.

**Comment by wiswedel** [comment]
@jhesketh I found the bug already reported in https://github.com/nextcloud/server/issues/19484 (however described quite technical)

**Comment by jhesketh** [comment]
Great, thanks for the followup :-)
