### ISSUE TITLE
Files sidebar icon click UX inconsistency

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18317]
Click on the Projects icon (1) opens the projects selector.
All other functions (Share link, others with access, internal link) require clicking on the right-side-icons (2).

18.0.0 daily build 2019-12-09

![image](https://user-images.githubusercontent.com/1804221/70520025-2cfdb180-1b3d-11ea-8d75-0f093c6096c6.png)

**Comment by wiswedel** [comment]
CC @nextcloud/designers

**Comment by skjnldsv** [comment]
This is for https://github.com/juliushaertl/nextcloud-vue-collections

**Comment by skjnldsv** [comment]
@wiswedel mind to create it there? :)

**Comment by wiswedel** [comment]
> @wiswedel mind to create it there? :)

done https://github.com/juliushaertl/nextcloud-vue-collections/issues/300

**Comment by skjnldsv** [comment]
You're awesome :)

**Comment by juliushaertl** [comment]
Reopening as the projects entry has the correct behavior, quoting @jancborchardt from juliushaertl/nextcloud-vue-collections#300

> Just to be clear, for almost all of these actions, the full area should be click-sensitive.
> 
> - Others with access: for sure should be, there’s no reason only the icon is
> - Internal link: Also no reason to not copy the link when clicking anywhere on the entry
> - Share link: Same thing. It literally says "Share link", and that’s what the action should do

**Comment by skjnldsv** [comment]
Looks resolved
