### ISSUE TITLE
Apache "ProxyPass" and "overwritewebroot" doesn't work for "webroot"

### ISSUE THREAD

**Issue by z49x2vmq** [nextcloud/server#18329]
### Steps to reproduce
1. run docker instance
2. Apache proxy config
SSLProxyEngine on
<Location "/nc">
        ProxyPass http://127.0.0.1:8081
        ProxyPassReverse http://127.0.0.1:8081
        RequestHeader set X-Forwarded-Proto "https"
</Location>
3. set "overwritewebroot config"
'overwritewebroot' => '/nc',
4. connect to "https://localhost/nc"

### Expected behaviour
should redirect to "https://localhost/nc/login"

### Actual behaviour
redirected to "https://localhost/nc/nc/login"
("/nc" twice)

But when I manually enter "https://localhost/nc/login" it shows the login screen
but after login the page is redirected to "https://localhost/nc/nc/apps/files/"

Again, if I removed one of **"/nc"** it it works fine.

### Server configuration

**Nextcloud version:** 17.0.1(Docker Image)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Comment by z49x2vmq** [comment]
setting proper values for "trusted_proxies", "forwared_for_headers" solves the problem

**Comment by gt2416** [comment]
can you elaborate please ? Im getting a similar error

**Comment by viollinn** [comment]
up !!

I would be interested as well !
