### ISSUE TITLE
Connection to Server Lost

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/server#18339]
### Steps to reproduce

1. Logged in to Nextcloud
2. Hold a External Storage via samba share , having a at-least few subfolders whose url length might reach 255+ characters
Ex: http://example.org/ncloud/apps/files/?dir=/03_Archive_University_Question_Papers_Exam-Cell/03_Electronics_and_Communication_Engineering/01_BE_ECE/Regulation_2013/Semester_06/EC6001%20-%20Medical%20Electronics&fileid=2817860 

3. Now files are inside such folders are accessible from Local IP Address, but not accessible from public internet static IP address
4. From accessing via internet to such folder location, it shows that connection to server lost
5. But can access such folders, by renaming into short folder names

In Log: 
[PHP] Error: Module 'smbclient' already loaded at Unknown#0

### Expected behaviour
Either local IP address or Public IP it should display the files in folders with longer folder names

### Actual behaviour
Files are accessible only from local ip address but not from public ip & with longer folder hierarchy and name

### Server configuration

**Operating system:** : Ubuntu 18.04 LTS

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from Older Nextcloud

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"**No errors have been found.**"

Screenshot from accessing from Public IP:

![2019-12-10_22-41-04](https://user-images.githubusercontent.com/29704829/70553098-83500c00-1ba0-11ea-9187-89fe00e72920.jpg)

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Are you able to reproduce this with a demo instance: https://try.nextcloud.com/?

**Comment by pkmkrishnakumar** [comment]
Thanks for the reply.

I have this issue when using the External Storage from Samba Share from Ubuntu Server, not from folders stored in nextcloud itself. 
I am also configured for pretty url. 
Default apps are being used.

Are you using encryption:** no
Are you using an external user-backend, if yes which one:** NO

As of now i am renaming the folders to short and accessing the files.

**Comment by lamazze** [comment]
If anyone has a suggestion for a hotfix or even on which line of code the problem occurs, I'm interested.
Thank you.

**Comment by ralphkretzschmar** [comment]
i've got the same Problem with my truenas instance. :( Any news on this?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by lamazze** [comment]
I'm still on 20.10.0 but it looks like I cannot reproduce the problems anymore. Can anyone else confirm ?

**Comment by pkmkrishnakumar** [comment]
Earlier I  faced this issue with smb share, later i started using NAS instead of smb share and mounted the drive. Retained the smb share as well for novice windows users, when cron job runs, files updated via smb is also updated in Nextcloud. We are trying to educate our users (students to use web interface in future) This solved my issue. But not sure , whether the issue continues in smb share. I like to encourage to use NAS as alternate to sambe share in Nextcloud, which provides better performance as well compared to samba share
