### ISSUE TITLE
Tag visibility depending on group membership?

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/server#18340]
I have made some tags invisible. I would like to have them visible again to only a specific user group and not just the administrators.

**Comment by dbummy** [comment]
I do it through the database.  Couldn't find any other way.  Works good. Hope this helps!

![image](https://user-images.githubusercontent.com/24436109/100783152-0cc0a580-33d3-11eb-99f5-01566d48dd8c.png)

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/4699
