### ISSUE TITLE
OAuth2 login flow: Allow to enter "device" name

### ISSUE THREAD

**Issue by csware** [nextcloud/server#18362]
**Is your feature request related to a problem? Please describe.**

I've several computers. When I set up the desktop client on my any computer it will show up as "Sync-Client - Windows" on the security tab. This is not very helpful as now there are several devices with this name.

**Describe the solution you'd like**
When granting access, I'd like to have an edit box prefilled with the current suggested name whereas I'm able to adjust it to my needs (e.g., add "computer 1" or something).

**Comment by szaimen** [comment]
You are able to change the name afterwards in the security tab of your account. Please use that to rename the device.

Apart from that: 
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
