### ISSUE TITLE
Dedicated app install page polishing

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#18363]
From #18233 by @jancborchardt 

-----

I will only have time to look into this in the next days as I’ll be traveling. If someone else wants to have a quick look (a lot of these things look nice already on the 2FA choice page for example, maybe patterns to get from there):
- [ ] App title should be white (same as text color)
- [ ] App icon should be white (same as text color)
- [ ] App icon is a bit large in comparison to the text.
- [ ] App description text should be left-aligned
- [ ] Spacing between app title and app description is too much – could be halved
- [ ] Error should just be bold (in a `<strong>` element) instead of in a `class="error"` container
- [ ] The width of the dialog should be fixed to what we had before. See **Container on update screen is too wide #17556**
- [ ] The "Go back" link is a bit confusing? Should it be "Cancel"?

**Comment by jancborchardt** [comment]
All fixed in https://github.com/nextcloud/server/pull/18422
