### ISSUE TITLE
Make accepting incoming shares optional

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18373]
Imho the *user* sharing settings should have a 
* [ ] automatically accept incoming shares

This should be disabled by default. This makes this feature opt-in which is probably the right thing to do as it is quite a change of behavior if we make this default.

An OCC command or config.php option for this is probably also needed to change the default.

_Originally posted by @jospoortvliet in https://github.com/nextcloud/server/issues/18255#issuecomment-562646491_

**Comment by nickvergessen** [comment]
Closing this to avoid spreading the discussion over multiple places
