### ISSUE TITLE
Error messagetext for username character set: add " "(Space)

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#1837]
Apparently, a space is also part of the allowed characters for usernames, but the (error) message text (in case you enter an Umlaut or so) is not precise, as the error text does not list the space in the set of allowed characters.

**Comment by vgvenkat** [comment]
Can I take a look at this? I am just getting started on this project

**Comment by jancborchardt** [comment]
@vgvenkat sorry for the late reply but of course – just go ahead. :)

**Comment by MorrisJobke** [comment]
Fixed already: "Fehler beim Erstellen eines Benutzers: Benutzername enthält Leerzeichen am Anfang oder Ende" (german for "Username contains space at start or end"
