### ISSUE TITLE
favicon location or Url should become a new optional parameter in config.php

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#1838]
Currently, the favicon Url is hardcoded in the core, but it should become an optional parameter in config.php so that Nextcloud updates do not overwrite a favicon - when this was customized..

**Comment by juliushaertl** [comment]
@Wikinaut Thanks for your report. The favicon can be changed without replacing by creating a custom theme. See https://docs.nextcloud.com/server/10/developer_manual/core/theming.html#changing-favicon for details.

**Comment by Wikinaut** [comment]
@juliushaertl Thanks so far. Will try this.

Only as an explanation: I usually upgraded (until now) by _moving_ (renaming) the whole old subdirectory e.g. performing something like the following steps
```
mv nextcloud _nextcloud
tar -xjf nextcloud.bz2
cp _nextcloud/config/config.php nextcloud/config/config.php
```
which would "remove" a custom Theme subdirectory. In the future I will not perform these steps any more. Thanks for explanation and help.

**Comment by juliushaertl** [comment]
@Wikinaut Right, you should backup your custom theme just as the config.php, but there will be no file conflicts with new versions of Nextcloud.
