### ISSUE TITLE
Incoming share email broken

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18380]
Since https://github.com/nextcloud/server/pull/16828, when clicking on the file link in the email notification about an incoming share, the user ends up in his Nextcloud profile seeing only

![image](https://user-images.githubusercontent.com/1804221/70725378-89f39600-1cfc-11ea-9068-9d58ae4a9e5e.png)

**Comment by ChristophWurst** [comment]
Looks like this has been resolved in the meantime. I tried with current master and both link share for folder as well as for a single file send an email with a link that works.

**Comment by wiswedel** [comment]
Nope, not for me. And I think it cannot work after all, since the link under the button in the email points to a file ID (e.g. https://cloud.example.com/f/7), that's not yet existing for the sharee until they *accepted* the incoming share.

**Comment by ChristophWurst** [comment]
Okay, can't reproduce then.

**Comment by ChristophWurst** [comment]
Is this about guests? Because I just tried a simple share to an email address?

**Comment by wiswedel** [comment]
It's about normal users, getting an incoming share email notification.

**Comment by ChristophWurst** [comment]
Got it.

**Comment by rullzer** [comment]
Just noticed this as well in a mail I got. And I can now also see properly why and how.
Let me prepare a fix.
