### ISSUE TITLE
Installation broken and can't upgrade: The files of the app (viewer) were not replaced correctly. Make sure it is a version compatible with the server.

### ISSUE THREAD

**Issue by CryptoSiD** [nextcloud/server#18382]
I'm unable to upgrade my installation of Nextcloud.

root@CryptoSiD:/var/www/nextcloud# sudo -u www-data php occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
UnexpectedValueException: The files of the app "viewer" were not correctly replaced before running the update
Update failed
Maintenance mode is kept active
Reset log level

If I try to update the app with occ this is what I'm getting:

root@CryptoSiD:/var/www/nextcloud# sudo -u www-data php occ app:update viewer
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
viewer not installed

Any way to fix this?

**Comment by CryptoSiD** [comment]
Fixed by download https://download.nextcloud.com/server/prereleases/nextcloud-18.0.0beta2.zip and uploading the viewer app to the apps folder.

Thanks to Lartza on freenode!

**Comment by Lartza** [comment]
To clarify the install was a git install and thus missing the app. Official release archives are fine.

**Comment by ejb1987** [comment]
On freebsd: I went into /usr/local/www/nextcloud/apps and renamed the viewer folder to viewer.old. Then Manually upgraded the nextcloud install with `su -m www -c "php ./occ upgrade"`. It ran the upgrade, then I disabled maint mode: `su -m www -c 'php occ maintenance:mode --off'`. I could then log in. Under the apps tab, it told me that viewer is only supported in version 17 or lower.
