### ISSUE TITLE
[18.0.0 Beta2] Broken text app

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#18389]
### Steps to reproduce
1. Create or open any plain text document in the file roster
2. The opening user interface will not show any content and ability to add new
3. Only possible to exit

### Expected behaviour
The text of opened file and the cursor should be shown.

### Actual behaviour
The text of opened file is not shown. Any possibility to add one.

### Server configuration

**Operating system:** Centos 6.10 x64

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.2.24

**Nextcloud version:** (see Nextcloud admin page) 18.0.0.2 beta

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 17.0.2 RC

**Where did you install Nextcloud from:** updated

</details>

![image](https://user-images.githubusercontent.com/5199030/70755212-e3ca7f00-1d41-11ea-916a-c934938d558b.png)

**Comment by tsalwierz** [comment]
Confirming the bug.

**Comment by juliushaertl** [comment]
Fix in https://github.com/nextcloud/text/pull/473
