### ISSUE TITLE
Nextcloud startpage blank after upgrading from nextcloud 16.0.6.1 to 17.0.1

### ISSUE THREAD

**Issue by marrobHD** [nextcloud/server#18383]
### Steps to reproduce
1. Update from nextcloud 16.0.6.1 to 17.0.1 
2.
3.

### Expected behaviour
Nextcloud startpage should be shown

### Actual behaviour
![grafik](https://n8970q34vnvidunh897qfc5wenh87v.tk/s/oTtAg7DSSBAgAeK/preview)
Nextcloud startpage appeared but without any content and button functuality

### Server configuration

**Operating system:** Ubuntu 19.04 Server

**Web server:** nginx 1.14.0

**Database:**

**PHP version:** 7.3.12

**Nextcloud version:** should be 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Via Web Updater

Browser logs:
```
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_videoplayer/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/notifications/js/notifications.js
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/additionalScripts.js
Source-Map-Adresse: additionalScripts.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/files_sharing.js
Source-Map-Adresse: files_sharing.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/collaboration.js
Source-Map-Adresse: collaboration.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/text/js/files.js
Source-Map-Adresse: files.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/viewer/js/viewer.js
Source-Map-Adresse: viewer.js.map

Content Security Policy: "'unsafe-inline'" wird innerhalb von script-src oder style-src ignoriert: nonce-source oder hash-source angegeben
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). content_script.js:1516:34
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. main.js:160:6103
TypeError: "OC.imagePath is not a function"
    iconPath https://cloud.example.com/apps/notifications/js/notifications.js:14
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    evaluate https://cloud.example.com/apps/notifications/js/notifications.js:7
    xn https://cloud.example.com/apps/notifications/js/notifications.js:7
    a https://cloud.example.com/apps/notifications/js/notifications.js:14
    _render https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    init https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    Ji https://cloud.example.com/apps/notifications/js/notifications.js:7
    _update https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    _init https://cloud.example.com/apps/notifications/js/notifications.js:7
    On https://cloud.example.com/apps/notifications/js/notifications.js:7
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:33
    n https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
notifications.js:7:11676
    Kt https://cloud.example.com/apps/notifications/js/notifications.js:7
    Vt https://cloud.example.com/apps/notifications/js/notifications.js:7
    qt https://cloud.example.com/apps/notifications/js/notifications.js:7
    _render https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    init https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    Ji https://cloud.example.com/apps/notifications/js/notifications.js:7
    _update https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    _init https://cloud.example.com/apps/notifications/js/notifications.js:7
    On https://cloud.example.com/apps/notifications/js/notifications.js:7
    <anonym> https://cloud.example.com/apps/notifications/js/notifications.js:33
    n https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonym> https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonym> https://cloud.example.com/apps/notifications/js/notifications.js:1
TypeError: "OC.registerMenu is not a function"
    mounted https://cloud.example.com/apps/notifications/js/notifications.js:14
    Wt https://cloud.example.com/apps/notifications/js/notifications.js:7
    rn https://cloud.example.com/apps/notifications/js/notifications.js:7
    insert https://cloud.example.com/apps/notifications/js/notifications.js:7
    A https://cloud.example.com/apps/notifications/js/notifications.js:7
    Ji https://cloud.example.com/apps/notifications/js/notifications.js:7
    _update https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    _init https://cloud.example.com/apps/notifications/js/notifications.js:7
    On https://cloud.example.com/apps/notifications/js/notifications.js:7
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:33
    n https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
notifications.js:7:11676
TypeError: OC.filePath is not a function
main.js:22:35
TypeError: OC.linkTo is not a function
files_sharing.js:1:1003
TypeError: OC.linkTo is not a function
collaboration.js:1:940
TypeError: OC.linkTo is not a function
additionalScripts.js:1:2010
ReferenceError: oc_requesttoken is not defined
galleryutility.js:317:1
ReferenceError: oc_requesttoken is not defined
galleryfileaction.js:205:1
TypeError: OC.linkTo is not a function
files.js:73:256
TypeError: OC.filePath is not a function
viewer.js:7:66227
Content Security Policy: "'unsafe-inline'" wird innerhalb von script-src oder style-src ignoriert: nonce-source oder hash-source angegeben 2
TypeError: OC.imagePath is not a function
files-music-player.js:549:9
TypeError: OC.imagePath is not a function
viewer.js:75:31
TypeError: OC.filePath is not a function
main.js:223:145
TypeError: OC.imagePath is not a function
files-music-player.js:549:9
TypeError: OC.imagePath is not a function
viewer.js:75:31
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf ws://127.0.0.1:8974/ blockiert ("connect-src").
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/notifications/js/notifications.js
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/files_sharing.js
Source-Map-Adresse: files_sharing.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/collaboration.js
Source-Map-Adresse: collaboration.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/additionalScripts.js
Source-Map-Adresse: additionalScripts.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/viewer/js/viewer.js
Source-Map-Adresse: viewer.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/text/js/files.js
Source-Map-Adresse: files.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_videoplayer/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/systemtags.js
Source-Map-Adresse: systemtags.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_videoplayer/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/files_sharing.js
Source-Map-Adresse: files_sharing.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/comments/js/comments.js
Source-Map-Adresse: comments.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/collaboration.js
Source-Map-Adresse: collaboration.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/share_backend.js
Source-Map-Adresse: share_backend.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/systemtags/js/systemtags.js
Source-Map-Adresse: systemtags.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_versions/js/files_versions.js
Source-Map-Adresse: files_versions.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/viewer/js/viewer.js
Source-Map-Adresse: viewer.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/text/js/files.js
Source-Map-Adresse: files.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/notifications/js/notifications.js
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_trashbin/js/files_trashbin.js
Source-Map-Adresse: files_trashbin.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/recommendations/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/additionalScripts.js
Source-Map-Adresse: additionalScripts.js.map

​
```

**Comment by kesselb** [comment]
Logs ...

**Comment by marrobHD** [comment]
There are no logs in nextcloud.txt. I have already set debug to true

**Comment by kesselb** [comment]
Please have a look at the logs section here:https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md#logs

We usually ask for webserver logs, nextcloud log and your browsers log. A white page could also be a cache problem. Try to clear your browsers cache.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

Please take note.

**Comment by marrobHD** [comment]
Browser logs:
`
Browser logs:
`
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_videoplayer/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/notifications/js/notifications.js
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/additionalScripts.js
Source-Map-Adresse: additionalScripts.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/files_sharing.js
Source-Map-Adresse: files_sharing.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/collaboration.js
Source-Map-Adresse: collaboration.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/text/js/files.js
Source-Map-Adresse: files.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/viewer/js/viewer.js
Source-Map-Adresse: viewer.js.map

Content Security Policy: "'unsafe-inline'" wird innerhalb von script-src oder style-src ignoriert: nonce-source oder hash-source angegeben
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). content_script.js:1516:34
JQMIGRATE: Migrate is installed, version 1.4.1 main.js:278:531
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. main.js:160:6103
TypeError: "OC.imagePath is not a function"
    iconPath https://cloud.example.com/apps/notifications/js/notifications.js:14
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    evaluate https://cloud.example.com/apps/notifications/js/notifications.js:7
    xn https://cloud.example.com/apps/notifications/js/notifications.js:7
    a https://cloud.example.com/apps/notifications/js/notifications.js:14
    _render https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    init https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    Ji https://cloud.example.com/apps/notifications/js/notifications.js:7
    _update https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    _init https://cloud.example.com/apps/notifications/js/notifications.js:7
    On https://cloud.example.com/apps/notifications/js/notifications.js:7
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:33
    n https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
notifications.js:7:11676
    Kt https://cloud.example.com/apps/notifications/js/notifications.js:7
    Vt https://cloud.example.com/apps/notifications/js/notifications.js:7
    qt https://cloud.example.com/apps/notifications/js/notifications.js:7
    _render https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    init https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    l https://cloud.example.com/apps/notifications/js/notifications.js:7
    Ji https://cloud.example.com/apps/notifications/js/notifications.js:7
    _update https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    _init https://cloud.example.com/apps/notifications/js/notifications.js:7
    On https://cloud.example.com/apps/notifications/js/notifications.js:7
    <anonym> https://cloud.example.com/apps/notifications/js/notifications.js:33
    n https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonym> https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonym> https://cloud.example.com/apps/notifications/js/notifications.js:1
TypeError: "OC.registerMenu is not a function"
    mounted https://cloud.example.com/apps/notifications/js/notifications.js:14
    Wt https://cloud.example.com/apps/notifications/js/notifications.js:7
    rn https://cloud.example.com/apps/notifications/js/notifications.js:7
    insert https://cloud.example.com/apps/notifications/js/notifications.js:7
    A https://cloud.example.com/apps/notifications/js/notifications.js:7
    Ji https://cloud.example.com/apps/notifications/js/notifications.js:7
    _update https://cloud.example.com/apps/notifications/js/notifications.js:7
    r https://cloud.example.com/apps/notifications/js/notifications.js:7
    get https://cloud.example.com/apps/notifications/js/notifications.js:7
    mn https://cloud.example.com/apps/notifications/js/notifications.js:7
    mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    $mount https://cloud.example.com/apps/notifications/js/notifications.js:7
    _init https://cloud.example.com/apps/notifications/js/notifications.js:7
    On https://cloud.example.com/apps/notifications/js/notifications.js:7
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:33
    n https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
    <anonymous> https://cloud.example.com/apps/notifications/js/notifications.js:1
notifications.js:7:11676
TypeError: OC.filePath is not a function
main.js:22:35
TypeError: OC.linkTo is not a function
files_sharing.js:1:1003
TypeError: OC.linkTo is not a function
collaboration.js:1:940
TypeError: OC.linkTo is not a function
additionalScripts.js:1:2010
ReferenceError: oc_requesttoken is not defined
galleryutility.js:317:1
ReferenceError: oc_requesttoken is not defined
galleryfileaction.js:205:1
TypeError: OC.linkTo is not a function
files.js:73:256
TypeError: OC.filePath is not a function
viewer.js:7:66227
Content Security Policy: "'unsafe-inline'" wird innerhalb von script-src oder style-src ignoriert: nonce-source oder hash-source angegeben 2
TypeError: OC.imagePath is not a function
files-music-player.js:549:9
TypeError: OC.imagePath is not a function
viewer.js:75:31
TypeError: OC.filePath is not a function
main.js:223:145
TypeError: OC.imagePath is not a function
files-music-player.js:549:9
TypeError: OC.imagePath is not a function
viewer.js:75:31
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf ws://127.0.0.1:8974/ blockiert ("connect-src").
Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/notifications/js/notifications.js
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/files_sharing.js
Source-Map-Adresse: files_sharing.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/collaboration.js
Source-Map-Adresse: collaboration.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/additionalScripts.js
Source-Map-Adresse: additionalScripts.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/viewer/js/viewer.js
Source-Map-Adresse: viewer.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/text/js/files.js
Source-Map-Adresse: files.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_videoplayer/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/systemtags.js
Source-Map-Adresse: systemtags.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_videoplayer/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/files_sharing.js
Source-Map-Adresse: files_sharing.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/comments/js/comments.js
Source-Map-Adresse: comments.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/collaboration.js
Source-Map-Adresse: collaboration.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/core/js/dist/share_backend.js
Source-Map-Adresse: share_backend.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/systemtags/js/systemtags.js
Source-Map-Adresse: systemtags.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_versions/js/files_versions.js
Source-Map-Adresse: files_versions.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/viewer/js/viewer.js
Source-Map-Adresse: viewer.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/text/js/files.js
Source-Map-Adresse: files.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/notifications/js/notifications.js
Source-Map-Adresse: notifications.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_trashbin/js/files_trashbin.js
Source-Map-Adresse: files_trashbin.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/recommendations/js/main.js
Source-Map-Adresse: main.js.map

Source-Map-Fehler: Error: NetworkError when attempting to fetch resource.
Ressourcen-Adresse: https://cloud.example.com/apps/files_sharing/js/dist/additionalScripts.js
Source-Map-Adresse: additionalScripts.js.map

​
`
`

**Comment by kesselb** [comment]
Just to be sure: Your webserver uses the configuration from https://docs.nextcloud.com/server/17/admin_manual/installation/nginx.html? Either a caching issue (have you tried another browser / private window) or the webserver do not deliver the js files.

**Comment by marrobHD** [comment]
This issue only appeared after upgrading the config is ok. I also tried diffrent browsers

**Comment by kesselb** [comment]
Could you please update your first post and add the complete issue template with config export (remove the sensitive information), app list and all logs?

**Comment by marrobHD** [comment]
I have the backup from nextcloud-16.0.6.1 restored. The issue happened when I upgraded to 17.0.1 from nextcloud 16.0.6.1. It stuck in the web based upgrader. ![grafik](https://i.ibb.co/FXZkkPY/firefox-AY4kf3rpr0.png)
