### ISSUE TITLE
Add a name suggestion for shares

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/server#18397]
**Is your feature request related to a problem? Please describe.**
When sharing with other users, the name get set to the name of the folder at time of creation of the share.
Let's assume, Alice has some folders `Images/from Bob` and `Music/from Bob` where she wants to collect images and music from Bob. She shares them with him. Now Bob has in `$share_folder/from Bob` a empty folder where he should put his data. Due to the name conflict it is even unclear if the images or the music should go in this folder. The conflicting second share might get named with a `(1)` suffix but this is also not much worth. 
The problem I found while googling around as part a of [this post](https://help.nextcloud.com/t/major-usability-issue-with-sharing-folders-between-users-groups/23857).

**Describe the solution you'd like**
I would like Alice to have the option to give NC a hint how to name the shared folder on Bob's side. This way, she could call the share e.g. `Images for Alice`, etc. Bob can then move and rename the shares according to his own needs and put things in them.

**Describe alternatives you've considered**
Of course Alice could have temporarily renamed the corresponding folders to something Bob might use (`Images for Alice`), then create the share for Bob (which uses exactly this name), and then rename it again for herself to the original name. In my option this is cumbersome and error-prone.

**Additional context**
This is related to #18395 in the sense that in the workaround there the name of the user is used as the name of the share. So Bob would have multiples folders `Bob`, `Bob (1)`, etc in his `$share_folder`.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
