### ISSUE TITLE
Nextcloud 18b2: visual artifact after closing notification

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#18392]
After creating a new user and sharing something with them, log in as new user. A notification appears that something was shared with you. Accept, and be left with this:
![Screenshot_20191212_234847](https://user-images.githubusercontent.com/551757/70755658-bcbc7f00-1d3a-11ea-95f9-56a4d1da2caa.png)
 🤖🤖🤖

**Comment by wiswedel** [comment]
CC @nextcloud/designers

**Comment by skjnldsv** [comment]
Maybe coming from #16057 ?
cc @juliushaertl

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/notifications/pull/515
