### ISSUE TITLE
Widen permissions on shared subfolders

### ISSUE THREAD

**Issue by christianlupus** [nextcloud/server#18395]
**Is your feature request related to a problem? Please describe.**
I am collecting photos and other data from various sources. This includes to share it read-write with family members so that they can add their data as well.
My father tends to change images just because he does not see well anymore and clicks the wrong buttons. This way I have to keep a full copy somewhere to restore if any file got corrupted by accident. The NC internal trash recovery might overflow quickly, if larger amounts of data if to be changed repeatedly.

Thus, I want to avoid that person A can modify data from person B.

**Describe the solution you'd like**
I would like to share the files read-only to a group (call it "Family"). In the folder for my father I would give him additional read-write rights. The same for my brother etc. This way he can only mess with his own files but not with mine.
This way everyone can see the data/images from everyone else and this is automatically organized well in terms of folder structure.

**Describe alternatives you've considered**
I used to share twice but this results in two different folders on my father's view and different rights on them. Also it is clumsy as he needs to somehow keep track of the different shares he cannot "bring together".

**Additional context**
This is somehow related to #6050 but the other way around: I would like to widen the rights but #6050 wants to restrict them further. The [trick with the tags](https://help.nextcloud.com/t/subfolders-permissions/10081/7) and file access plugin seems not to work as well.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by szaimen** [comment]
You might have a look at the groupfolders app, though:
https://apps.nextcloud.com/apps/groupfolders
