### ISSUE TITLE
An exception occurred while executing 

### ISSUE THREAD

**Issue by jiaji123** [nextcloud/server#18405]
An exception occurred while executing 'SELECT `uid`, `displayname` FROM `oc_users` WHERE `uid_lower` = ?' with params ["123"]: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_users' doesn't exist

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
