### ISSUE TITLE
Restore to..

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#18413]
**Is your feature request related to a problem? Please describe.**
When Im restoring files from trash I never know where they were deleted from. So when I hit "restore" I then have to search for the file name to find it. This is problematic with older files that I want to work with but dont know where to find them.

**Describe the solution you'd like**
A "Restore to.." option is a good feature that I can use to restore all my restored files in a specific (e. g. "Restored") folder.

**Comment by szaimen** [comment]
cc @nextcloud/designers I'd like to get your input on this feature request.

**Comment by skjnldsv** [comment]
Hi,

While this looks like a simple feature, this is just two clicks away from restoring. 
With 30 we also added the original file location. This should mitigate  the search issue :)
