### ISSUE TITLE
First entry is overlapped by header (again)

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18414]
### Steps to reproduce
1. Checkout master
2. Have at least one favorite
3. Goto favorite section

### Expected behaviour
See the file

### Actual behaviour
![image](https://user-images.githubusercontent.com/3902676/70863035-2196f580-1f44-11ea-9c77-22ec064664a5.png)

This issue was already part of https://github.com/nextcloud/server/issues/16076 and was fixed by https://github.com/nextcloud/server/pull/16366. https://github.com/nextcloud/server/pull/17989 reverted #16366 then to fix https://github.com/nextcloud/server/issues/17891 and here we are.

cc @nextcloud/designers

**Comment by skjnldsv** [comment]
cc @GretaD

**Comment by jancborchardt** [comment]
This might also be related to this overlap issue happening on the share page, or at least needs to be cross-tested?
![share page overlap](https://user-images.githubusercontent.com/925062/70897609-8d04c400-2025-11ea-9bc5-79db1fa89510.png)

**Comment by GretaD** [comment]
> This might also be related to this overlap issue happening on the share page, or at least needs to be cross-tested?

The overlapping was in all categories of file list when we first fix it, now its only on favorite, recent and shares and not on Deleted files or the main file list page.  So maybe it is related to this. Will check it out this week.
