### ISSUE TITLE
Search Exif data to search for pictures taken in a certain location

### ISSUE THREAD

**Issue by eibex** [nextcloud/server#18415]
**Is your feature request related to a problem? Please describe.**
Searching for specific photos can be tedious when you have a large photo library. It is much easier to remember the location of a photo than the year and month it was taken in (since year/month folder structure is very common).

**Describe the solution you'd like**
Exif information could be used when searching for files. For example, searching "Australia" could return pictures that are tagged with Australia in their geolocation exif field.

**Describe alternatives you've considered**
I've considered using the [nextcloud/maps](https://github.com/nextcloud/maps) app, while certainly useful, it is not possible to use the feature while using an external app (e.g. [nextcloud/ios](https://github.com/nextcloud/ios)).

**Additional context**
I can imagine this being complex to implement, especially for existing installations with many files already uploaded. Furthermore, I guess it could make the search function slower and heavier.

I have searched for issue duplicates both in open and closed and couldn't find anything that matched this. Apologise if it is indeed a duplicate.

**Comment by Spartachetto** [comment]
Maybe this could be solved by https://github.com/nextcloud/gallery/issues/514

**Comment by eibex** [comment]
What they proposed there for geolocation (map with pins) is the same as what nextcloud/maps does though.

**Comment by eibex** [comment]
Maybe this issue should be moved to nextcloud/photos if it doesn't fit the scope of the server core?

**Comment by Spartachetto** [comment]
Are you aware of the maps app? Do you think that it misses something?  What else would you need?

**Comment by eibex** [comment]
Related: https://github.com/nextcloud/photos/issues/445

> Are you aware of the maps app?

I have been using it since before I first created the issue, the app is fine but does not provide a seamless experience (slow loading as it needs to fetch thousands of photos, going between photos in the same location is slow for some reason, unusable on mobile devices, etc.). What I was looking for is probably best described in the linked issue.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/photos/issues/445
