### ISSUE TITLE
Multiline User Settings Alignment

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/server#18420]
The changes made in #17239 are great but has made some strange alignment issues.

### Steps to reproduce
1. Go into user settings page as an admin
2. Click on new user

### Expected behaviour
The new fields should line up with the user table.

### Actual behaviour
The new fields are not lined up with the user table and is slightly confusing. For instance, the input for display name is right under the header for `password`.
![Screenshot from 2019-12-16 16-33-39](https://user-images.githubusercontent.com/47195730/70891382-174b2900-2022-11ea-8e98-fb2813ef0a8d.png)

Also, when editing a user, the alignment of quota is slighty strange as it is center aligned while everything else is left aligned.

![Screenshot from 2019-12-16 16-37-04](https://user-images.githubusercontent.com/47195730/70891512-56797a00-2022-11ea-8f3c-97f2b3e2da29.png)

**Comment by jospoortvliet** [comment]
@GretaD :rocket:

**Comment by GretaD** [comment]
Thank you @gary-kim. I will prepare a patch and push it this week.
