### ISSUE TITLE
Sort By - new filters and new columns

### ISSUE THREAD

**Issue by aronmgv** [nextcloud/server#18426]
Per this [reply](https://github.com/nextcloud/server/issues/10649#issuecomment-565791190) I would like to request a new feature to include sorting per file type - in other words file extension or suffix.

This is how they did it in Pydio:
![image](https://user-images.githubusercontent.com/6546231/70908388-5ae66880-200b-11ea-9f17-286973e98e4d.png)

Thanks

**Comment by jancborchardt** [comment]
cc @tobiasKaminsky @marinofaggiana @rullzer on if we do this. Cause we do have something similar on iOS but planned to remove it for now to keep parity and so we can start with only what is really needed.

**Comment by tobiasKaminsky** [comment]
So, basically sort by filetype?
And in that then by name?

**Comment by marinofaggiana** [comment]
@tobiasKaminsky it should be "group by" filetype

**Comment by skjnldsv** [comment]
It's kind of already implemented for 28.
All columns (or almost) are sortable now. What would be a following enhancements would be adding new columns :thinking:

**Comment by gdragon-git** [comment]
I think you lost a lot of history and support for having a way to sort by upload date. This ticket doesn't capture the demand specific to Upload Date/Time being a property for file browser to show and allow sorting. 

Can you please consider reopening #22278 ?

**Comment by ux01** [comment]
I often use the non-standard sorting setting of “by last save date”. It can be found by clicking “more details” in the sorting selection in the standard explorer. Is there no way to move the whole “more details” button to Files?

**Comment by susnux** [comment]
This is now possible with https://github.com/nextcloud/server/pull/45708

**Comment by BluePixel4k** [comment]
@susnux I don't think the PR solves the issue, because the PR includes filters and not the requested feature to sort the files with more options.
Or have I misunderstood the linked PR?

**Comment by jancborchardt** [comment]
@BluePixel4k the original issue and discussion it is based on specifically mentions "sorting by file extension". Our solution to that is the following design, which does cover the request.
If any further sorting options are wanted, it’s best to open a new issue with specifics. :)

![image](https://github.com/user-attachments/assets/e4a89281-8d7c-40ee-8976-4091cdf55002)

**Comment by BluePixel4k** [comment]
@jancborchardt yes, but the PR only integrate filtering, right?
For me, filtering and sorting are not the same thing :)

**Comment by KS-emp100Git** [comment]
@jancborchardt would you be so kind and review this: 

skjnldsv closed #22278 with note it would be duplicate of #18426.
But nobody see's any relation between a upload date and these filter request #18426.
With #22278 we request since a long time now to get an "upload time stamp" - no success until today.

Do you see a way to wake up again #22278?
