### ISSUE TITLE
Can't revoke oldest app password because revoke option is hidden

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#18421]
When I have a lot of app passwords, I cannot revoke the oldest one because the "revoke" option is beyond the lower edge of the window and is therefore hidden. Even zooming out doesn't unhide it. See attached screenshot to understand the issue

![Bildschirmfoto von 2019-12-16 10-01-43](https://user-images.githubusercontent.com/3313208/70893904-49da2f00-1fec-11ea-9e86-522082c74dda.png)

**Comment by jospoortvliet** [comment]
@vasyugan the moment the menu shows you can probably scroll if you have a scroll wheel... At least that works here in firefox and chromium. It isn't nice but I'd call it a papercut.

@nextcloud/designers

**Comment by skjnldsv** [comment]
Once opened you can indeed scroll

**Comment by vasyugan** [comment]
> @vasyugan the moment the menu shows you can probably scroll if you have a scroll wheel... At least that works here in firefox and chromium. It isn't nice but I'd call it a papercut.
> 
> @nextcloud/designers

Indeed, your suggestion works! Thanks.

**Comment by jancborchardt** [comment]
This is one of the reasons why we have some whitespace at the bottom of any filelist. :) It shows you that it’s really the end, but it also leaves space for possible action menus.

A proper solution here would be to add some additional bottom margin to the last `.section` element in the AppContentView in settings. :)

**Comment by skjnldsv** [comment]
> This is one of the reasons why we have some whitespace at the bottom of any filelist. :) It shows you that it’s really the end, but it also leaves space for possible action menus.

well, the menu is shown entirely. I don't see how additional space will change the need for scrolling to get to the end of the list :)

**Comment by ma12-co** [comment]
I think that this https://github.com/nextcloud/nextcloud-vue/issues/641
Would solve the problem

**Comment by jancborchardt** [comment]
> well, the menu is shown entirely. I don't see how additional space will change the need for scrolling to get to the end of the list(menu) :)

Because to see the menu entirely you have to  both open it _and_ scroll. There is no way to only open it and have it work. :) This is why there should be additional margin by default on the bottom.

**Comment by szaimen** [comment]
I think this was fixed in the meantime
