### ISSUE TITLE
error wirh wrong URL by using S3 in china,

### ISSUE THREAD

**Issue by SinsanL** [nextcloud/server#18437]
i installed nextcloud and I want to use S3 storage，so I installed External Storage APP，when I config S3，I get a error message ‘Failed connect to nextprocloud.s3.cn-northwest-1.amazonaws.com:443’，I found the reason is the URL of my S3 bucket in AWSchina is end of amazonaws.com.cn .So that I cant access to aws with amazonaws.com。how can I config it to amazonaws.com.cn

**Comment by j-ed** [comment]
This is only the bug tracker of Nextcloud. For support purposes the [Nextcloud help forum](https://help.nextcloud.com/) exists in which several question around the configuration and usage of S3 have already been answered in the past. You should gibe it a try 😉

**Comment by kesselb** [comment]
Use `yourbucket.amazonaws.com.cn` (it' probably a different url. use the complete bucket url) as hostname as shown at https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage/amazons3.html?

**Comment by kesselb** [comment]
Closing as configuration issue.
