### ISSUE TITLE
Option to not crop images on grid view

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#18439]
So, it would just be a matter of adding `&a=1` to the preview url.
https://github.com/nextcloud/server/blob/f3cdf7e4c1654bfa2807a284c5ccf14e161d3201/apps/files/js/filelist.js#L2150
![image1](https://user-images.githubusercontent.com/14975046/70982659-a48c8d00-20b7-11ea-85d9-c27760e48103.jpeg)

This is something we could add as a setting in the bottom left in Files (and Photos)?

_The setting should be "Crop image previews" and be checked by default._

Cause we had the same discussion around Photos, and there’s no clear right or wrong. We use cropping as default, but just like macOS has it as an different view to not have it cropped, we should probably have it as an option too. Something for 19 though.

cc @jancborchardt

**Comment by jancborchardt** [comment]
Just a detail: The setting should be "Crop image previews" and _be_ checked by default.
