### ISSUE TITLE
Allow custom options for app password generation.

### ISSUE THREAD

**Issue by RayfenWindspear** [nextcloud/server#18436]
**Is your feature request related to a problem? Please describe.**
Currently, app passwords give you no customization options for length, charsets, etc. In addition to this they are static in length (25, the dashes don't count) and alphanumeric only (62 char pool), resulting in a reasonable, but not necessarily future-proof 148.85 bits of entropy. I'd like to propose allowing more customization in their generation.

**Describe the solution you'd like**
At the very least, allowing a custom length, or selection of various lengths would be nice, and very easy to implement as a first step. Ideally adding an "Advanced" section of UI for app password customization would include variable length and additional charset options, while still allowing easy one-click generation. Either in the form of an input field to enter additional characters to add to the pool, and/or a finite set of "toggle charset _X_", or toggling of individual characters. Or perhaps toggleable charsets with an input for problem characters to omit.

Not for any expectations, but simply for a visual example, here are the generator options for KeePassXC. 
![Screenshot from 2019-12-20 11-39-34](https://user-images.githubusercontent.com/2687517/71283601-efa7d980-231d-11ea-9140-90c2797c8850.png)
![Screenshot from 2019-12-20 11-39-45](https://user-images.githubusercontent.com/2687517/71283607-f3d3f700-231d-11ea-9fa2-c831a02834cc.png)

**Describe alternatives you've considered**
There aren't any alternatives, the app passwords are generated in the web UI with no options.

**Additional context**
I fully understand the choice of going alphanumeric, as the string will be compatible most anywhere. I am also painfully aware of lack the of consistency in password policy in general, especially the lack of proper support for entry and transmission of certain characters on certain clients/platforms. Being an advocate of generating random passwords and using managers, it feels a little underwhelming to be given zero options for app password generation, even if the resulting string cannot properly be used by the intended client. Still, it's easy to regenerate until one works, and I feel the added entropy would allow app passwords to be more future proof.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
