### ISSUE TITLE
Custom app recommandition

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18445]
For theming we have two different options:

https://docs.nextcloud.com/server/17/admin_manual/configuration_server/theming.html#branded-clients

> occ config:app:set theming AndroidClientUrl --value "https://play.google.com/store/apps/details?id=com.nextcloud.client"
occ config:app:set theming iTunesAppId --value "1125420102"
occ config:app:set theming iOSClientUrl --value "https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8"

and

https://docs.nextcloud.com/server/17/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=customclient_desktop#alternate-code-locations

> 'customclient_desktop' =>        'https://nextcloud.com/install/#install-clients',
'customclient_android' =>        'https://play.google.com/store/apps/details?id=com.nextcloud.client',
'customclient_ios' =>        'https://itunes.apple.com/us/app/nextcloud/id1125420102?mt=8',
'customclient_ios_appid' =>                 '1125420102',

According to a customer those behave different and we need to set it two times?

Why do we have two mechanism for this?

@skjnldsv maybe?

**Comment by skjnldsv** [comment]
theming is @juliushaertl

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/70998761-5045d500-20d8-11ea-8f77-2d333fe9cbd7.png)

> According to a customer those behave different and we need to set it two times?

I guess so. firstrun is already using the values from theming if the keys in `config.php` are not set. Other places only read `config.php`. 

> Why do we have two mechanism for this?

Laziness probably ;) There should be a "service" that provides the right values.

**Comment by tobiasKaminsky** [comment]
There is also a check if you use a mobile browser, e.g. safari on iPhone so that it shows a link to the app.
Is this also handled by config?
If so, we should omit the other way, or?

**Comment by juliushaertl** [comment]
I cannot find the reference ticket anymore, but iirc the idea was to move this out of the system config into the theming app. The current implementation will check for the theming app values first and fallback to system config if the theming app is disabled or not value is set.

**Comment by tobiasKaminsky** [comment]
Hm. But customer said they had to set both, to get it working in all cases, which is wrong.
So I suggest, to check that everything is working with theming app and then mark config.php as deprecated?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
