### ISSUE TITLE
18b2: share note auto-save useless

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18452]
The share note auto-save is completely useless. Unless you're a super-fast 10-finger-typer, it's auto-saving super-quickly and sending an email right away.
Also deleting the hint text (see also https://github.com/nextcloud/server/issues/18451) with the backspace key auto-saves all the time.

Example: The following video generated eight emails:

![Peek 2019-12-17 18-35](https://user-images.githubusercontent.com/1804221/71020174-1ab2e300-20fc-11ea-80a7-fedd3db07946.gif)

**Comment by rullzer** [comment]
@skjnldsv

**Comment by skjnldsv** [comment]
Yes let's increase the debounce :grin:

**Comment by jancborchardt** [comment]
Hmm, there is a button already to send, and it is not expected to send after any timeout.

Auto-saving the note is one thing, but auto-sending the email we should not do. That should happen only on clicking the confirm/send button. :)

**Comment by wiswedel** [comment]
> Auto-saving the note is one thing, but auto-sending the email we should not do. That should happen only on clicking the confirm/send button. :)

When there's a difference between saving and sending, we have to make sure the user notices if the message has been sent yet or not.

**Comment by jancborchardt** [comment]
cc @tobiasKaminsky @karlitschek this is the issue we ran into before btw.

**Comment by skjnldsv** [comment]
Isn't this fixed by https://github.com/nextcloud/server/pull/18771

**Comment by skjnldsv** [comment]
Fix https://github.com/nextcloud/server/pull/18894
