### ISSUE TITLE
18: progress bar vanishes if you delete a file

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#18454]
When you're uploading files and simultaneously delete a file, the progress bar disappears. navigating away and back to the folder, just the cancel upload button (right side) appears, but the progress bar is still gone...

papercut?!?

**Comment by rullzer** [comment]
Can you do a small screencast? I have trouble following what you mean.

**Comment by ChristophWurst** [comment]
I remember something like that from a review session of like Nextcloud 16? @jancborchardt?

**Comment by jospoortvliet** [comment]
1. Start a upload of enough files that it takes, say, a minute or two.
2. delete a file in the folder you are in.
3. see progress bar disappear completely, so you don't know the state of the upload (it is still uploading).
4. Navigate to another folder.
5. a broken upload bar (just the cancel button) suddenly appears
???

Sorry, can't do a screencast right now...

**Comment by GretaD** [comment]
I can reproduce this following the steps that Jos described, the thing is that how should we fix this?
@jancborchardt @skjnldsv should we have both bars, for uploading and deleting? Or show the deleting bar and after its done, the uploading bar pops up again?

**Comment by jancborchardt** [comment]
Whichever progress bar started first should have precedence for now. If that one is over, we can show the next one which is still running.

**Comment by acs-ferreira** [comment]
Can reproduce this too:

### Steps to reproduce in WebUI
1. Upload a file in the root 
2. Create a folder, go into the folder and start uploading many files 
3. Click on the Home icon while uploading
4. Delete the file uploaded into the root

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
