### ISSUE TITLE
18b2: Share note hint text too hard to get rid of

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18451]
The share note hint text _Enter a note for the share recipient_ appears as actual text inside the textbox, making it necessary for the user to mark and delete that hint before even being able to start typing their own text.
Most likely they'll start typing and therefore sending the example text together with their message.

![Peek 2019-12-17 18-26](https://user-images.githubusercontent.com/1804221/71019645-028e9400-20fb-11ea-9910-0c11c71703b5.gif)

**Comment by rullzer** [comment]
@skjnldsv

**Comment by skjnldsv** [comment]
fixed by https://github.com/nextcloud/server/pull/18771
