### ISSUE TITLE
Auto-opening date picker too intrusive

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18450]
The auto opening date picker for the share expiry is standing intrusively in the mouse way towards the share note checkbox.

![Peek 2019-12-17 18-19](https://user-images.githubusercontent.com/1804221/71019191-361cee80-20fa-11ea-82ab-069de3859e8e.gif)

**Comment by rullzer** [comment]
What do you suggest then?

CC: @nextcloud/designers

**Comment by wiswedel** [comment]
> What do you suggest then?

open date picker on click

**Comment by jancborchardt** [comment]
Yep, totally agree. The time picker should not open on hover, but only on tap/click.

cc @skjnldsv @georgehrke on this. :)

**Comment by skjnldsv** [comment]
There is already an open ticket for the issue here: https://github.com/nextcloud/nextcloud-vue/issues/704

**Comment by wiswedel** [comment]
> Opened ticket for the issue here: [nextcloud/nextcloud-vue#704](https://github.com/nextcloud/nextcloud-vue/issues/704)

 😂 No human can understand that issue!
However, crypronite, thanks for taking care.

**Comment by rullzer** [comment]
Lets keep it open so we don't forget ;) I check this repo a lot more than the vue one ;)

**Comment by skjnldsv** [comment]
>  No human can understand that issue!

I wasn't blaming saying there is already another one :p
Just if people want to keep track of the more wide issue on the vue components! :)

Thanks for reporting Sascha!

**Comment by blizzz** [comment]
the picker was overhauled, closing.
