### ISSUE TITLE
[Question] Migrate users from old instance to new with a clean sync

### ISSUE THREAD

**Issue by ThaDaVos** [nextcloud/server#18453]
I would like to migrate users from an old instance to a new one, already up and running with new users, I would prefer to do it in a way that all the users from the old instance have to resync the files, because this old instance is one which got broken by the encryption module en missing documentation regarding it when enabling group folders... I got it stable again but I would prefer for the users to resync the files...

Also, it would be great if I would only have to update the DNS record to point to the new instance, instead of manually going by all clients and reconfiguring them...

Is this possible?

**Comment by gary-kim** [comment]
Unless you were using external authentication like LDAP before, I think you're stuck with moving the DB over (which would require you move the files as well) or just manually copying users.
By the way, this is the issue tracker for Nextcloud. You can ask questions regarding setup or processes here: <https://help.nextcloud.com/>.

**Comment by ThaDaVos** [comment]
I could also maybe only move the users over from the old to the new - thanks for the info, I'll look into the databases :D
