### ISSUE TITLE
Two nextcloud installations show different number of Apps/Experimental Apps in Apps > Productivity

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#1846]
I have two Nextcloud 10.0.1 installations on two different machines, both Debian 8, both were upgraded from ownCloud 9.0.x.

What puzzles me is that the two similar installations show a different set of Apps in section "Productivity", one shows 1 Apps, no Experimental Apps, the other installation shows 2 Apps and about 16 Experimental Apps. I am puzzled...

https://server/nextcloud/index.php/settings/apps?category=productivity#

**Comment by Wikinaut** [comment]
solved.

config.php needs

```
  'appstore.experimental.enabled' => true,
```

**Comment by jancborchardt** [comment]
@Wikinaut this setting is also available in the interface, bottom left Settings area. :)

**Comment by Wikinaut** [comment]
Uh, tatsächlich.... (danke)
