### ISSUE TITLE
Move signature.json signature to .sig file

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#18464]
Right now the signature of the signature.json file (that contains hashes of all the files) is in the json file itself.

I think it would be better to have a signature.json with all the hashes and a signature.json.sig with the actual signature.
That way we decouple the two. Which makes it a lot cleaner IMO.

**Comment by rullzer** [comment]
Thinking some more about this.
Being backwards compatible is going to be hard. But we can keep it in 1 file. We just have to encode the hashlist so it is a single string. That we can also do with other tools.

We can add a version field. So that we know if something is an old hash?
Or we just add a signatureV2.json that has precedence over v1?

**Comment by szaimen** [comment]
I suppose this is still valid?

**Comment by blizzz** [comment]
@ChristophWurst you liked this, so I assume you know context 8) ^
