### ISSUE TITLE
Stuck at logging in.. (chrome)

### ISSUE THREAD

**Issue by MacGyver27** [nextcloud/server#18466]
Nextcloud gets stuck at logging in for chrome (tried 75 and also current version). In case of FF it gets me in.. Same thing I noticed with the mobile app - wont log in.. then it offers me to use old interface and that gets me in as well. Any ideas what it might be? Nextcloud version 17.0.1.

![image](https://user-images.githubusercontent.com/6546231/71077399-a291ff00-2187-11ea-816a-2f1c5d1e442a.png)

Thanks, Michal

**Comment by ChristophWurst** [comment]
See https://help.nextcloud.com/ for community support. If you identified a bug, use the corresponding template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md

thanks

**Comment by MacGyver27** [comment]
Sorry but who should have time for that?? I stated Nextcloud version and browser that should be more than enough to try to replicate.. That bug report is for you not me.

**Comment by ChristophWurst** [comment]
Okay, let's see.

**Comment by ChristophWurst** [comment]
Logged into a 17.0.1 Nextcloud with Chrome successfully -> can't reproduce with the information given

**Comment by ChristophWurst** [comment]
Reading some of the other comments you left in our organization I want to remind of our https://nextcloud.com/contribute/code-of-conduct/.

**Comment by MacGyver27** [comment]
I have noticed this in console (chrome) after hitting log in:
```
Refused to send form data to because it violates the following Content Security Policy directive: "form-action 'self'".
```

Then I found it was related to the this one #17409 so adding `'overwriteprotocol' => 'https',` to the config.php helped.

**Comment by ChristophWurst** [comment]
Awesome!
