### ISSUE TITLE
[18beta2]Log gets flooded with debug messages "Manager::registerResourceProvider is deprecated"

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#18476]
Happens in debug level and live update activated.

{"reqId":"Xfqc51eMFRiZ7qwowUAUFAAAAA8","level":0,"time":"2019-12-18T21:40:55+00:00","remoteAddr":"xxx","user":"me","app":"no app in context","method":"GET","url":"/ocs/v2.php/apps/notifications/api/v2/notifications","message":"\\OC\\Collaboration\\Resources\\Manager::registerResourceProvider is deprecated","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.4"}

{"reqId":"Xfqc6FeMFRiZ7qwowUAUGQAAABE","level":0,"time":"2019-12-18T21:40:56+00:00","remoteAddr":"xxx","user":"me","app":"no app in context","method":"GET","url":"/index.php/apps/logreader/poll?lastReqId=Xfqcr1eMFRiZ7qwowUATXgAAALk","message":"\\OC\\Collaboration\\Resources\\Manager::registerResourceProvider is deprecated","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.4"}

**Comment by rullzer** [comment]
If you set your log level to debug. You will see debug info. :wink:

**Comment by dartcafe** [comment]
I am not talking about the fact, that debug messages occur, I talked about the frequncy (about 20-30 per second).

**Comment by dartcafe** [comment]
<img width="1598" alt="grafik" src="https://user-images.githubusercontent.com/26707476/71244006-dbf67600-2311-11ea-8c91-f9ca68c2df9e.png">

**Comment by kesselb** [comment]
Have you deck and/or talk installed? For deck there is already a pull request to use the not deprecated way.

**Comment by dartcafe** [comment]
It seems that the logreader itself produces this behavior. See second log entry in my starting post.

**Comment by kesselb** [comment]
No.

**Comment by dartcafe** [comment]
Hmmm. All I can say, that the entries contain different urls:
* "/ocs/v2.php/apps/notifications/api/v2/notifications","message":"\\OC\\Collaboration\\Resources\\Manager::registerResourceProvider is deprecated"
* "/index.php/apps/logreader/poll?lastReqId=Xf0DToD5JkAcwSUyE2BwVgAAACE","message":"\\OC\\Collaboration\\Resources\\Manager::registerResourceProvider is deprecated"
* "/index.php/apps/logreader/live","message":"\\OC\\Collaboration\\Resources\\Manager::registerResourceProvider is deprecated"

And flooding starts with activating the live update.

**Comment by dartcafe** [comment]
But you were right. I didn't realized I had the deck app activated on my dev site. Thanks for the hint!
