### ISSUE TITLE
Use "Unshare" instead of "Delete share" for the sharing sidebar

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#18477]
Follow up of https://github.com/nextcloud/server/issues/18202

- [ ] "Delete share" sounds like it deletes some content. Can it be "Unshare"
- [ ] Also, can it have the icon-close as icon instead of the delete icon?

**Comment by gary-kim** [comment]
Just need to change the options here.
https://github.com/nextcloud/server/blob/f87a71cf23d2b7f2d2dd6cdf5223f5e86a7e4fe8/apps/files_sharing/src/components/SharingEntryLink.vue#L259-L264
