### ISSUE TITLE
Avatar endpoint returns wrong response code

### ISSUE THREAD

**Issue by mario** [nextcloud/server#18481]
According to https://github.com/nextcloud/server/blame/12bdb95c1a40170652570decef7f466e4b97aa65/core/Controller/AvatarController.php#L145, the server should return 200 if a user has an uploaded avatar (rather than generated one). 

This doesn't seem to be the case as the server returns 201 regardless of the type of avatar user has.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/lib/private/Avatar/UserAvatar.php#L109-L115

This fails for me. Upload any avatar, at some early stage "generated" (the file not the config flag) is deleted and if we are saving the cropped avatar the above code will throw a not found exception and will not set "generated" (the config flag) to false. So many users have a custom avatar now but the config flag "generated => true".  

The response code depends on the config flag. The setUserValue call must be done after the try-catch and a repair job is probably required to fix the wrong state. 

cc @nextcloud/server-triage
