### ISSUE TITLE
Rich workspace: Trying to access array offset on value of type int at /lib/private/Files/Node/Node.php#327

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18497]
### Steps to reproduce
1. Use the rich workspace
2. See "Trying to access array offset on value of type int" in the logs sometimes.

Failing request: `https://nextcloud.test/apps/text/session/fetch?documentId=167&sessionId=23&sessionToken=ezat0XD8IerjXMNL2mzWijrZGJZJYLPFPVQv6uVPIzlgwBfwOmhlvAESNoOVmdlS`

```
Index: lib/private/Files/Node/Node.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- lib/private/Files/Node/Node.php	(revision ab8a8c085a1693923525c6cc91a72a2824ede543)
+++ lib/private/Files/Node/Node.php	(date 1576783528069)
@@ -324,6 +324,9 @@
 	 * @return bool
 	 */
 	public function isValidPath($path) {
+		if (is_int($path)) {
+			throw new \InvalidArgumentException('$path is an int urgh');
+		}
 		if (!$path || $path[0] !== '/') {
 			$path = '/' . $path;
 		}
```

![image](https://user-images.githubusercontent.com/3902676/71205316-6f905e00-22a2-11ea-96eb-ad62e681736f.png)

`{"reqId":"gtdxWisqQizHqOK6O4Hm","level":3,"time":"2019-12-19T19:28:12+00:00","remoteAddr":"192.168.10.1","user":"admin","app":"index","method":"GET","url":"/apps/text/session/fetch?documentId=167&sessionId=21&sessionToken=AAbjNr534px9JNXIWFquvx3anHD1EhcEEQvcVgmSKfxP2N0NmKu3JNFzADeMc7WC","message":{"Exception":"InvalidArgumentException","Message":"$path is an int urgh","Code":0,"Trace":[{"file":"/home/vagrant/code/nextcloud/lib/private/Files/Node/Folder.php","line":59,"function":"isValidPath","class":"OC\\Files\\Node\\Node","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/Files/Node/Folder.php","line":137,"function":"getFullPath","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php","line":74,"function":"get","class":"OC\\Files\\Node\\Folder","type":"->"},{"file":"/home/vagrant/code/nextcloud/apps/text/lib/Service/DocumentService.php","line":175,"function":"getFile","class":"OC\\Files\\SimpleFS\\SimpleFolder","type":"->"},{"file":"/home/vagrant/code/nextcloud/apps/text/lib/Service/ApiService.php","line":104,"function":"getBaseFile","class":"OCA\\Text\\Service\\DocumentService","type":"->"},{"file":"/home/vagrant/code/nextcloud/apps/text/lib/Controller/SessionController.php","line":57,"function":"fetch","class":"OCA\\Text\\Service\\ApiService","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"fetch","class":"OCA\\Text\\Controller\\SessionController","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->"},{"file":"/home/vagrant/code/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func"},{"file":"/home/vagrant/code/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/home/vagrant/code/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::"}],"File":"/home/vagrant/code/nextcloud/lib/private/Files/Node/Node.php","Line":328,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36","version":"18.0.0.4","id":"5dfbcf4f02f6d"}`

### Expected behaviour

No error :see_no_evil: 

### Actual behaviour

Error :rofl:

**Comment by kesselb** [comment]
(string) will do it ;) 

@juliushaertl is there a particular reason that the document service is not using type hints at all? And have I created all these rich workspace related issue within the wrong repository? :thinking:

**Comment by juliushaertl** [comment]
> is there a particular reason that the document service is not using type hints at all? And have I created all these rich workspace related issue within the wrong repository? 

No reason I must admit 🙈 Yes, rich workspace is mainly handled by the text app. 

Fix is in https://github.com/nextcloud/text/pull/485
