### ISSUE TITLE
Min height for rich workspace

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18494]
### Steps to reproduce
1. Don't have a Readme.md
2. Enable rich workspace
3. Start editing the content

### Expected behaviour

I can use the editors toolbar

### Actual behaviour

![Peek 2019-12-19 19-42](https://user-images.githubusercontent.com/3902676/71200148-d3f9f000-2297-11ea-9a5d-270cf0dcfb57.gif)

**Comment by jancborchardt** [comment]
Ideal case would be if we can keep the height the same (as we specifically reduced it before: https://github.com/nextcloud/text/pull/468 ) and that the popover simply shows properly also overflowing the editor.

Silly quick-fix could be that on low height of the container, we make the heading list not a vertical but a horizontal one with only icons, so:

> h1 | h2 | h3 | h4 | h5 | h6

**Comment by juliushaertl** [comment]
> Silly quick-fix could be that on low height of the container, we make the heading list not a vertical but a horizontal one with only icons, so:

Not a quick fix, since this is not supported by our vue components.

> Ideal case would be if we can keep the height the same (as we specifically reduced it before: nextcloud/text#468 ) and that the popover simply shows properly also overflowing the editor.

Yes, let's make sure the popover is properly shown even if the height is not fitting all of its content.
