### ISSUE TITLE
Confirmation to accept share to group not working

### ISSUE THREAD

**Issue by jonascant** [nextcloud/server#18498]
Nextcloud version (eg, 12.0.2): 18.0.0 Beta 3
Operating system and version (eg, Ubuntu 17.04): Debian Buster
Apache or nginx version (eg, Apache 2.4.25): Nginx
PHP version (eg, 7.1): 7.3 fpm

The issue you are facing:
Shares now have to be accepted by recipient. But acceptance is not working. Instead, the notification to accept pops up again after a short while.

Is this the first time you’ve seen this error? (Y/N):y

Steps to replicate it:

    update to nc 18
    share a file with a group
    try to accept the share from another account in that group

The output of your Nextcloud log in Admin > Logging:

`{"reqId":"cZSFjz2mdYSqQ4lAxQiJ","level":3,"time":"2019-12-17T16:15:15+01:00","remoteAddr":"","user":"--","app":"cron","method":"","url":"--","message":{"Exception":"TypeError","Message":"Argument 7 passed to OCA\\Files_Sharing\\Notification\\Notifier::__construct() must be of the type string, null given","Code":0,"Trace":[{"function":"__construct","class":"OCA\\Files_Sharing\\Notification\\Notifier","type":"->","args":[{"__class__":"OC\\L10N\\Factory"},{"__class__":"OC\\Share20\\Manager"},{"__class__":"OC\\Files\\Node\\LazyRoot"},{"__class__":"OC\\Group\\Manager"},{"__class__":"OC\\User\\Manager"},{"__class__":"OC\\URLGenerator"},null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":83,"function":"newInstanceArgs","class":"ReflectionClass","type":"->","args":[[{"__class__":"OC\\L10N\\Factory"},{"__class__":"OC\\Share20\\Manager"},{"__class__":"OC\\Files\\Node\\LazyRoot"},{"__class__":"OC\\Group\\Manager"},{"__class__":"OC\\User\\Manager"},{"__class__":"OC\\URLGenerator"},null]]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":100,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":[{"name":"OCA\\Files_Sharing\\Notification\\Notifier","__class__":"ReflectionClass"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":115,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Files_Sharing\\Notification\\Notifier"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":414,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["OCA\\Files_Sharing\\Notification\\Notifier"]},{"file":"/var/www/nextcloud/lib/private/ServerContainer.php","line":134,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->","args":["OCA\\Files_Sharing\\Notification\\Notifier"]},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":146,"function":"query","class":"OC\\ServerContainer","type":"->","args":["OCA\\Files_Sharing\\Notification\\Notifier"]},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":302,"function":"getNotifiers","class":"OC\\Notification\\Manager","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/notifications/lib/Handler.php","line":148,"function":"dismissNotification","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/apps/notifications/lib/Handler.php","line":111,"function":"deleteById","class":"OCA\\Notifications\\Handler","type":"->","args":[1012,"jimmi",{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/apps/notifications/lib/App.php","line":70,"function":"delete","class":"OCA\\Notifications\\Handler","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/lib/private/Notification/Manager.php","line":282,"function":"markProcessed","class":"OCA\\Notifications\\App","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/apps/updatenotification/lib/Notification/BackgroundJob.php","line":251,"function":"markProcessed","class":"OC\\Notification\\Manager","type":"->","args":[{"__class__":"OC\\Notification\\Notification"}]},{"file":"/var/www/nextcloud/apps/updatenotification/lib/Notification/BackgroundJob.php","line":187,"function":"deleteOutdatedNotifications","class":"OCA\\UpdateNotification\\Notification\\BackgroundJob","type":"->","args":["mail","0.20.1"]},{"file":"/var/www/nextcloud/apps/updatenotification/lib/Notification/BackgroundJob.php","line":166,"function":"createNotifications","class":"OCA\\UpdateNotification\\Notification\\BackgroundJob","type":"->","args":["mail","0.21.0"]},{"file":"/var/www/nextcloud/apps/updatenotification/lib/Notification/BackgroundJob.php","line":88,"function":"checkAppUpdates","class":"OCA\\UpdateNotification\\Notification\\BackgroundJob","type":"->","args":[]},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":61,"function":"run","class":"OCA\\UpdateNotification\\Notification\\BackgroundJob","type":"->","args":[null]},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":55,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]},{"file":"/var/www/nextcloud/cron.php","line":125,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->","args":[{"__class__":"OC\\BackgroundJob\\JobList"},{"__class__":"OC\\Log"}]}],"File":"/var/www/nextcloud/apps/files_sharing/lib/Notification/Notifier.php","Line":65,"CustomMessage":"--"},"userAgent":"--","version":"18.0.0.4","id":"5df9f7dbee960"}`

The output of your config.php file in /path/to/nextcloud (make sure you remove any identifiable information!):

```
<?php
$CONFIG = array (
  'instanceid' => '####',
  'passwordsalt' => '####',
  'secret' => '####',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '####',
  ),
  'datadirectory' => '/BTRFS/nc_data',
  'dbtype' => 'mysql',
  'version' => '18.0.0.4',
  'overwrite.cli.url' => '####',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => '####',
  'installed' => true,
  'activity_expire_days' => 14,
  'auth.bruteforce.protection.enabled' => true,
  'blacklisted_files' => 
  array (
    0 => '.htaccess',
    1 => 'Thumbs.db',
    2 => 'thumbs.db',
  ),
  'cron_log' => true,
  'enable_previews' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\BMP',
    4 => 'OC\\Preview\\XBitmap',
    5 => 'OC\\Preview\\Movie',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
  ),
  'filesystem_check_changes' => 0,
  'filelocking.enabled' => 'true',
  'htaccess.RewriteBase' => '/',
  'integrity.check.disabled' => false,
  'knowledgebaseenabled' => false,
  'logfile' => '/var/nc_data/nextcloud.log',
  'loglevel' => 2,
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 104857600,
  'maintenance' => false,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'overwriteprotocol' => 'https',
  'preview_max_x' => 1024,
  'preview_max_y' => 768,
  'preview_max_scale_factor' => 1,
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
  'quota_include_external_storage' => false,
  'share_folder' => '/Shares',
  'skeletondirectory' => '',
  'theme' => '',
  'trashbin_retention_obligation' => 'auto, 7',
  'updater.release.channel' => 'beta',
  'app_install_overwrite' => 
  array (
    0 => 'apporder',
    1 => 'occweb',
    2 => 'files_reader',
  ),
  'mail_from_address' => '####',
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '####,
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/nextcloud/extra-apps',
      'url' => '/extra-apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/var/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => false,
    ),
  ),
  'updater.secret' => ####,
);
```

**Comment by kesselb** [comment]
cc @rullzer

**Comment by gary-kim** [comment]
#18457 May have addressed this issue. Could you try it?

**Comment by jonascant** [comment]
Wasn't this merged into Beta 3? The issue persists in beta 3.

**Comment by jonascant** [comment]
Issue still persists in Beta 4... I am happy to provide more information, if necessary.

**Comment by jonascant** [comment]
Issue still persists in RC1

**Comment by jonascant** [comment]
In addidtion: the setting "accept shares by default" in the sharing section does not have any effect (notification still pops up). Also: the Issue also accurs when sharing from user to user (not to group).

**Comment by addy90** [comment]
I can confirm that the automatic accepting of shares to groups does also not work with LDAP groups.
In the "oc_share" Table, the "accepted" cell is set to zero (false) instead of 1 (true). This leads to "File not found" exception for other users when trying to access a folder via activity view and in the folder view, the folder is missing.
I tried every combination of 'sharing.enable_share_accept' and 'sharing.force_share_accept' but none worked for sharing folders to groups.
Current workaround is to manually set the cell to accepted for a folder within the database.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
