### ISSUE TITLE
Hide rich workspace on delete

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18493]
### Steps to reproduce
1. Enable rich workspace
2. Add some text
3. Delete the file

### Expected behaviour

Reset / Unload / Hide the rich workspace

### Actual behaviour

Rich workspace is confused

![Peek 2019-12-19 19-37](https://user-images.githubusercontent.com/3902676/71199860-2a1a6380-2297-11ea-9660-07d768d26ed0.gif)

**Comment by ChristophWurst** [comment]
Fix is at https://github.com/nextcloud/text/pull/508
