### ISSUE TITLE
occ db:convert-filecache-bigint nx 17.0.2 in share hosting

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#18491]
I have an instance nextcloud server updated to 17.0.2 and in the report it gives me an error

occ db:convert-filecache-bigint 

for values

mounts.storage_id
mounts.root_id
mounts.mount_id

having access to only the mysql database panel with phpmyadmin, what commands should I feed into the nextcloud database to solve this error?

having access to only the mysql database panel with phpmyadmin, what commands should I feed into the nextcloud database to solve this error?

```
ALTER TABLE `oc_share` ADD KEY `share_with_index` (`share_with`) USING BTREE;
ALTER TABLE `oc_share` ADD KEY `parent_index` (`parent`) USING BTREE;
ALTER TABLE `oc_filecache` ADD KEY `fs_mtime` (`mtime`) USING BTREE;
```

for this error BigInt (64bit) identifiers shell is used

`sudo -u www-data php occ db:convert-filecache-bigint`

but having a shared hosting how to do with phpmyadmin? what values ​​to feed into the database?

**Comment by kesselb** [comment]
Thank you for using the search!

**Comment by tigernero79** [comment]
@kesselb I did not understand why the post was closed, can you provide me with the github link where it is resolved?

**Comment by tigernero79** [comment]
this url could perhaps solve the problem? now I try

https://github.com/nextcloud/server/issues/13704

**Comment by kesselb** [comment]
1) For general support please use https://help.nextcloud.com (we are tracking bugs and feature requests here).
2) Please use the search function (e.g. search for `mounts.root_id` or `db:convert-filecache-bigint`)

Thanks :+1:

**Comment by tigernero79** [comment]
resolve then

```
ALTER TABLE oc_mounts MODIFY mount_id BIGINT NOT NULL
ALTER TABLE oc_mounts MODIFY root_id BIGINT NOT NULL
ALTER TABLE oc_mounts MODIFY storage_id BIGINT NOT NULL
```

thanks
