### ISSUE TITLE
Flow: Browse the app store is not possible for users

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18495]
### Steps to reproduce
1. Login as user (without admin permission)
2. Visit personal settings
3. Go to flow
4. See "More flows" button

### Expected behaviour

I can either add more flows or don't see this button. Probably something like "there are no flows yet. ask your admin to add more flows via the app store".

### Actual behaviour
![image](https://user-images.githubusercontent.com/3902676/71200948-533bf380-2299-11ea-9faa-1d58cb62fd07.png)

**Comment by rullzer** [comment]
Yeah we should not show them there indeed.
