### ISSUE TITLE
Nextcloud file permissions completely wrong after updating via web updater (Breaks website on every update)

### ISSUE THREAD

**Issue by rkkoszewski** [nextcloud/server#18501]
Anybody has an idea of why this is happening? Are Apache web server setups using different permissions than NGINX plus PHP-FPM setups?

### Steps to reproduce
1. Install VestaCP or HestiaCP with NGINX and PHP FPM to have the same environment
2. Install Nextcloud and update Nextcloud trough the web updater
3. See that the site just appears completely broken and completely vanishes with 404 errors

### Expected behaviour
Nextcloud should set the proper permissions and keep working

### Actual behaviour
Hi, I'm running Nextcloud on a Linux Server that is running NGINX with PHP-FPM. Nextcloud is generally running perfectly fine, but during the update (Via the web updater), the permissions get completely messed up and it breaks the website completely, showing all files as 404 not found.

The issue is that PHP-FPM needs the "others" permission set to "read". Creating a new file does set that permisison by default, and also installing apps from the Nextcloud app store installs new apps perfectly fine and with the correct permissions.

The issue is with the web updater, when it downloads and installs the updated Nextcloud files, it sets all "others" permissions for all the files to "0". Preventing the server to access the website, showing a 404 error.

I'm not quite sure why this happens, if the permissions are in the update file, are set by the updater script or it's some deeper system misconfiguration of some sort. 

### Server configuration

**Operating system:**
Debian Stretch

**Web server:**
NGINX 
PHP-FPM
(HestiaCP)

**Database:**
MySQL
**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
17.0.1 to 17.0.2
But was also happening in previous versions

**Updated from an older Nextcloud/ownCloud or fresh install:**
%

**Where did you install Nextcloud from:**
ZIP install from the Nextcloud Website

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
We don't change this on purpose (I'm not sure to be honest but there is no change permission after update code). 

The updater (cli and web) is downloading the release and extract it. I would expect that the extract routine respects the umask configuration. I would try to create a new file (e.g. with touch) and check the permissions. 

In a shared hosting environment (even if you are the only user) I would expect a own php-fpm pool per user or domain. Making files word readable because php-fpm is running as www-data but the files are owned by web1, web2, etc. seems strange.

**Comment by kesselb** [comment]
You speak about a exception at https://github.com/hestiacp/hestiacp/issues/635. Mind to share to relevant logs? Triaging is much harder with only half of the information.

**Comment by rkkoszewski** [comment]
Thanks @kesselb for looking into it. 

Yes, that issue is related. I was unaware that the PHP scripts required different permissions than static files (And is different from how my last web hosting was working, where explicit execute permissions were required to run the PHP files).

I'll try to provide all logs asap (slight hard due to Christmas).

In any case, I tested the "touch" command with the domain user, and it creates a file with 644 permissions. Why would the updated files have different permissions? How can I debug this behaviour?

I also noticed that the "PHP opcache" is also influencing the results. Right after the update, I get redirected to index.php where a login like view can be seen with a button to upgrade the database. But that page has lost all its styles and shows as a broken black and white bullet list and a button, but after refreshing the page for a while it turns into a "404" error page, which makes me think it must be serving the cached PHP files for a while, and may be conflicting with the upgrade process.

**Comment by kesselb** [comment]
Updater does not update files ;) Release is extracted to a temp folder and then moved to the original place. So basically all files are created first by extracting to a different place. 

> Apart from the standard bug report logs, is there some other kind of logs I could provide that could help with triaging the issue?

I don't know. Do you think this issue is related to nextcloud? According to the hestiacp people even 640 should be enough. Seems to be a configuration issue :thinking:

**Comment by rkkoszewski** [comment]
I'm not sure. I just tested creating a test.php file with 640 permissions, and the page is showing up properly in the browser.. (No 404 error). Seems like this results are inconsistent for me.

What made me suspect of something Nextcloud related is that after the update, the "other" permissions for all files from the nexctloud root folder were gone. 

Just out of curiosity, I do have the "storage" folder mounted on an external harddrive, where the umask may differ. Is the temporary update directory inside the "storage" folder or somewhere else?

**Comment by kesselb** [comment]
Yes. It's inside the datadirectory. There should be a folder "updater".

**Comment by rkkoszewski** [comment]
Ok, that's the one. I just tried running the "touch" command inside the update-* folder and I get a file with 660 permissions, same as the ones seen after the update.

Therefore this is not really a Nextcloud related issue but a misconfiguration on my side. 

Umask is per process and not per folder, and therefore it must be an ACL misconfiguration on my side, enforcing a different permission mask. 

Still with those permissions it should be able to run the scripts, but messes up all static files, which are then non accessible, breaking everything anyway.

Thank you @kesselb for all the help! And I wish you a Merry Christmas! 😃

**Comment by kesselb** [comment]
Thanks and Merry Christmas @rkkoszewski
