### ISSUE TITLE
When i change data directory,I Unable to enter settings app page,help me please!!!

### ISSUE THREAD

**Issue by JGcoding25** [nextcloud/server#18512]
Because my data directory is full,so i buy a new disk,then change the datadirectory to new disk and Move all files in data to new disk..and then use `systemctl restart php-fpm` to restart php

then i can use nextcloud ,and i can enter 
/settings/user
/settings/user/security
/settings/user/sync-clients
bug i canot enter
/settings/user/activity
/settings/user/accessibility
/settings/user/sharing
/settings/user/privacy

help me please!!!

error logs

[index] Error: OCP\Files\NotPermittedException:  at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php line 106
    OC\Files\Node\File->putContent(":root {\n--icon ... }")
 1. /var/www/nextcloud/lib/private/Template/IconsCacher.php line 140
    OC\Files\SimpleFS\SimpleFile->putContent(":root {\n--icon ... }")
 2. /var/www/nextcloud/lib/private/Template/SCSSCacher.php line 336
    OC\Template\IconsCacher->setIconsCss(".icon-control{- ... }")
 3. /var/www/nextcloud/lib/private/Template/SCSSCacher.php line 181
    OC\Template\SCSSCacher->cache("/var/www/nextcloud/apps/privacy/css", "7d23-9fa4-style.css", "style.scss", OC\Files\SimpleFS\SimpleFolder {}, "/apps/privacy/css")
 4. /var/www/nextcloud/lib/private/Template/CSSResourceLocator.php line 109
    OC\Template\SCSSCacher->process("/var/www/nextcloud/apps/privacy", "css/style.scss", "privacy")
 5. /var/www/nextcloud/lib/private/Template/CSSResourceLocator.php line 84
    OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist("/var/www/nextcloud/apps/privacy", "css/style.scss", "privacy")
 6. /var/www/nextcloud/lib/private/Template/ResourceLocator.php line 78
    OC\Template\CSSResourceLocator->doFind("css/style")
 7. /var/www/nextcloud/lib/private/TemplateLayout.php line 298
    OC\Template\ResourceLocator->find(["css/server","c ... "])
 8. /var/www/nextcloud/lib/private/TemplateLayout.php line 203
    OC\TemplateLayout::findStylesheetFiles(["css/server","c ... "])
 9. /var/www/nextcloud/lib/private/legacy/template.php line 183
    OC\TemplateLayout->__construct("user", "settings")
10. /var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php line 165
    OC_Template->fetchPage({forms: {persona ... "})
11. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 123
    OCP\AppFramework\Http\TemplateResponse->render()
12. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Settings\Cont ... {}, "index")
13. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OC\\Settings\\C ... r", "index", OC\AppFramework\ ... {}, {section: "priva ... "})
14. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({section: "priva ... "})
15. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {section: "priva ... "})
16. /var/www/nextcloud/lib/base.php line 1000
    OC\Route\Router->match("/settings/user/privacy")
17. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

GET /settings/user/privacy
from 125.120.29.99 by admin at 2019-12-21T11:30:12+00:00

**Comment by kesselb** [comment]
Thanks for reporting issues back to Nextcloud!

Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
