### ISSUE TITLE
NC18 b4; Flow: Admin & Personal Page empty

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#18514]
Flow Admin/Personal Settings is empty

- `Uncaught TypeError: Object(...)(...).map(...).flat is not a function`
```
 events: Object(c.loadState)("workflowengine", "entities").map((function(e) {
                return e.events.map((function(t) {
                    return A({
                        id: "".concat(e.id, "::").concat(t.eventName),
                        entity: e
                    }, t)
                }
                ))
            }
            )).flat(),
```
- CSS File not found
`Could not find resource file "/nextcloud/apps/workflowengine/css/admin.css"`
- NC Log `Deprecated event type for OCP\WorkflowEngine::registerChecks: Symfony\Component\EventDispatcher\GenericEvent`

not sure if it relates to https://github.com/nextcloud/server/pull/18509
@blizzz ?

**Comment by juliushaertl** [comment]
@Rello Yes, seems related to #18509 

Could you check if that fixes the issue for you?

**Comment by Rello** [comment]
did not work out of the box. seems to cause some other issues.
I will wait for beta4 as I recognised several Flow-topics there

**Comment by Rello** [comment]
Hello,
Beta 4 is still broken. Flow can not be used at all.

![Screenshot 2019-12-29 at 09 07 46](https://user-images.githubusercontent.com/13385119/71554073-b0af0d80-2a1a-11ea-865d-9f2b1a249517.png)

what is your roadmap to have Flow available in NC 18?

**Comment by Rello** [comment]
The registerOperator error is coming from **Talk**.
Talk is not compatible with NC18/Flow and needs to be deactivated

**Comment by Rello** [comment]
The style error is coming from this part - there is no admin.css in workflowengine
https://github.com/nextcloud/server/blob/master/apps/workflowengine/lib/AppInfo/Application.php#L65-L67

**Comment by blizzz** [comment]
@Rello where do you have Spreed from? The 8.0 beta 2 from the app store?

**Comment by Rello** [comment]
Hello @blizzz 
how can I get beta versions from the appstore? did I miss a parameter?
I am running the "normal" one

**Comment by blizzz** [comment]
Normal one? But from appstore?

The 8 beta is released normally on the app store (for 18 only), so you should have it. Which version is reported on the apps page?

**Comment by Rello** [comment]
I commented in the other Talk-Thread. 8.0.0-alpha.2 is installed (and not working)

**Comment by juliushaertl** [comment]
@Rello Let's continue over here. Is the `Uncaught TypeError: Object(...)(...).map(...).flat is not a function` fixed with beta4 or is it still occuring before the talk error occurs?

**Comment by Rello** [comment]
Solved by updating the obsolete Chrome 65 version. `flat()` was not supported before and I had an issue with the updater.
