### ISSUE TITLE
Referrer-Policy HTTP header is not detected by security scan

### ISSUE THREAD

**Issue by kbabioch** [nextcloud/server#18516]
I have a Nextcloud instance running [here](https://babioch.de/nextcloud). On the admin overview page (`settings/admin/overview`), I'm being shown this error / recommendation / warning:

    The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" or "same-origin". This can leak referer information. See the W3C Recommendation ↗.

Following the deployment guide, I'm definitely setting this header, and it is also delivered to any request:

```
curl -X HEAD -i https://babioch.de/nextcloud
[...]
referrer-policy: no-referrer
[...]
```

### Steps to reproduce
1. Install Nextcloud
2. Visit the admin overview page
3. Be surprised by the warning, which is a false positive

### Expected behaviour
No warning should be shown when the header is set (which is the case in my setup)

### Actual behaviour
Warning is being shown despite the header being returned by the webserver

### Server configuration

**Operating system:** Linux

**Web server:** Apache

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Tarball from nextcloud.com

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox
**Operating system:** Linux

**Comment by kesselb** [comment]
```
curl -s -X HEAD -i "https://babioch.de/nextcloud/" | grep "referrer-policy"
referrer-policy: no-referrer
referrer-policy: strict-origin
```

I agree the warning is a bit misleading. Header is there but two times. Right now there is no simple way to disable the headers by nextcloud. 

Some people prefer to keep the headers with their webserver configuration. If seems to be possible to discard (some of) the headers set by nextcloud: https://github.com/nextcloud/server/issues/8207

Okay with you to close this issue as duplicate?

**Comment by kbabioch** [comment]
@kesselb You're right, of course. I've somehow missed that the header is set twice - with inconsistent values. I've adjusted the webserver configuration accordingly, and the error message is gone now.

I don't see if and how this is related to #8207, but I'm fine with closing this issue, although I do agree that the error message is not super helpful in my case.

**Comment by kesselb** [comment]
> I don't see if and how this is related to #8207 

It's not a duplicate of #8207. I just referenced it because people discussed many ways over there how to unset the headers (set by nextcloud before) and keep anything in the webserver configuration.
