### ISSUE TITLE
Dark Theme: Modified Text Color is Black

### ISSUE THREAD

**Issue by MrArca9** [nextcloud/server#18528]
### Steps to reproduce
1. Install 
2. Enable Dark Theme
3. Profit?

### Expected behaviour
Should be similar font color to Size column

### Actual behaviour
Flat Black

### Server configuration

**Operating system:**
Latest Ubuntu LTS (18.04)

**Web server:**
Snap Install

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Snap

Tested on Firefox and Brave (Chromium) Browsers
![image](https://user-images.githubusercontent.com/21209461/71317669-d94f6a00-2452-11ea-9539-a292c82bc23a.png)
Top Brave, Bottom Firefox

**Comment by a1pilot** [comment]
Same issue. Also note the "Convert To" text in the right-click context menu for the video convertor is black when all the rest is the correct white / grey shade.

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by juliushaertl** [comment]
Old issue showing up again it seems https://github.com/nextcloud/server/issues/14003

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/server/pull/19109

**Comment by a1pilot** [comment]
Ironically, I'm now having the oppostie issue in NC 18. Light mode has icons far too light. Will open a new ticket.
