### ISSUE TITLE
User management view: E-Mail misaligned

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18539]
# Steps to reproduce
1. Change your resolution to 1440x748 (Laptop L with chromium developer tools)
2. Go to user management page

![Screenshot from 2019-12-22 19-56-22](https://user-images.githubusercontent.com/3902676/71326025-8f6b9000-24f5-11ea-8ec9-4784a60ccb7c.png)

### Expected behaviour

Email column is aligned

### Actual behaviour

Email column is not aligned

**Comment by GretaD** [comment]
this is fixed

![email_align](https://user-images.githubusercontent.com/12728974/72148664-a806f180-33a1-11ea-918b-9fd9ffff06a5.png)

**Comment by kesselb** [comment]
Thanks :+1:
