### ISSUE TITLE
Cannot upgrade when using object storage as primary storage

### ISSUE THREAD

**Issue by NoxInmortus** [nextcloud/server#18544]
### Steps to reproduce
Configure object storage.
Wait for an update to be available.
Open updater.

### Expected behaviour
Updater open

### Actual behaviour
Blank page display with one line saying : Could not read data directory from config.php.

## Server configuration detail

**Operating system:** Linux 4.9.93-mainline-rev1 #1 SMP Tue Apr 10 09:54:46 UTC 2018 aarch64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** mysql 10.4.11

**PHP version:** 

7.3.12
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 17.0.1 - 17.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from latest v16

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - bruteforcesettings: 1.4.0
 - calendar: 1.7.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - encryption: 2.5.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - impersonate: 1.4.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - nextbackup: 19.12.1
 - nextcloud_announcements: 1.6.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - polls: 0.10.4
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - support: 1.0.1
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - user_ldap: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - survey_client

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "dbtype": "mysql",
    "version": "17.0.1.1",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "app_install_overwrite": [
        "impersonate"
    ],
    "mysql.utf8mb4": true,
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "objectstore": {
        "class": "\\OC\\Files\\ObjectStore\\S3",
        "arguments": {
            "bucket": "***REMOVED SENSITIVE VALUE***",
            "autocreate": true,
            "key": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "hostname": "***REMOVED SENSITIVE VALUE***",
            "port": 443,
            "use_ssl": true,
            "region": "***REMOVED SENSITIVE VALUE***"
        }
    },
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** s3

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

```

```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0

**Operating system:** Windows 10

## Logs

No logs available.

**Comment by kesselb** [comment]
Have you ever used the updater to update? :thinking:  The warning is there for more than 3 years. If there's no data directory you cannot use the updater. You don't need a datadirectory for objectstore but for the updater. Unfortunately I don't know what will happen if you configure a datadirectory beside objectstore. I would expect that the datadirectory is just used by the updater and anything else goes to objectstore but have not tested it.

**Comment by NoxInmortus** [comment]
Ok, I needed to have data directory for the update indeed. But primary storage is still s3, so all is ok.

thanks
