### ISSUE TITLE
Provide "lastLogin" resource through user metadata OCS API

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#18543]
**Is your feature request related to a problem? Please describe.**
When trying to generate a user list through OCS API call it is not possible to get the lastLogin data to sort the list accordingly and use it for further (automated) actions.

**Describe the solution you'd like**
Add "lastLogin" to the supplied resources through user metadata OCS API.

**Additional context**
#14715

**Comment by kesselb** [comment]
```
curl 'https://admin:admin@nextcloud.test/ocs/v1.php/cloud/users/admin' -H 'OCS-APIRequest: true' 
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <enabled>1</enabled>
  <storageLocation>/home/vagrant/nextcloud-data/admin</storageLocation>
  <id>admin</id>
  <lastLogin>1577049552000</lastLogin>
  <backend>Database</backend>
  <subadmin/>
  <quota>
   <free>10665918464</free>
   <used>220</used>
   <total>10665918684</total>
   <relative>0</relative>
   <quota>-3</quota>
  </quota>
  <email>admin@nextcloud.test</email>
  <displayname>admin</displayname>
  <phone></phone>
  <address></address>
  <website></website>
  <twitter></twitter>
  <groups>
   <element>admin</element>
  </groups>
  <language>en</language>
  <locale>de</locale>
  <backendCapabilities>
   <setDisplayName>1</setDisplayName>
   <setPassword>1</setPassword>
  </backendCapabilities>
 </data>
</ocs>
```

I see lastLogin within the response? :thinking:

**Comment by bpcurse** [comment]
Ah, darn... I trusted the docs instead of testing it :wink:  Sorry again.
Docs should reflect the actual values:

https://docs.nextcloud.com/server/17/developer_manual/client_apis/OCS/ocs-api-overview.html#user-metadata

**Comment by bpcurse** [comment]
@kesselb Don't know if this is an issue, not avoidable due to technical reasons or intended, but the unix time is always returned with 3 trailing zeros?

`<lastLogin>1577047458000</lastLogin>`

This makes an extra step necessary to strip these zeros before converting it to "human readable" time formats.

**Comment by kesselb** [comment]
It's in milliseconds. Don't know why.
