### ISSUE TITLE
Flow: disable flow / show warning if precondition not met

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18557]
### Steps to reproduce
1. Don't have libreoffice installed
2. Login as admin
3. Enable pdf conversion flow
4. Create flow with pdf conversion

### Expected behaviour

Admin: Flow will tell me that a dependency is missing
User: Don't show pdf conversion flow

### Actual behaviour

I'm able to create flows with pdf conversion. For a user without admin permissions it's not possible to figure out whats wrong.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
