### ISSUE TITLE
After installing External storage support, the following prompt pops up, what should I do?

### ISSUE THREAD

**Issue by heiyedetanxuenzhe** [nextcloud/server#18550]
No external storage configured or you don't have the permission to configure them
Global credentials

Global credentials can be used to authenticate with multiple external storages that have the same credentials.

**Comment by kesselb** [comment]
Hey! Welcome to GitHub and thanks for reporting this issue :+1: 

It's actually more a question than a bug report. Please visit https://help.nextcloud.com for general help with nextcloud.
