### ISSUE TITLE
Box replaced server domain certificates not ugraded

### ISSUE THREAD

**Issue by leighss** [nextcloud/server#1856]
1st time doing this, so I hope I have been succinct enough yet included all info.

I recently bought a Box with the pre-installed SD and set it up successfully, following the instructions.

I connected successfully to the internet using [WIKI](https://github.com/nextcloud/nextcloud-snap/wiki/Connecting-the-Nextcloud-Box-to-the-Internet) with a ddns.net account

All was working fine.

Then I changed my trusted domain to a subdomain of my own domain (which is all set up correctly as as seen below it works):
`# sudo nextcloud.occ config:system:set trusted_domains 2 --value=new.domain`

Then installed the **_new_** a Let's Encrypt SSL certificate (i.e. for my subdomain)
`$ sudo nextcloud.enable-https -d` All OK
`$ sudo nextcloud.enable-https` All OK

Again, All working fine except the certificate is still in the name of the initial ddns.net domain and I have to ignore the warning in the browser that the name of the cert and the domain dont match

My config.php is correctly updated to the new domain.

**Comment by oparoz** [comment]
This is probably due to the fact that most Let's Encrypt scripts save a domain config locally and use it to renew the certificates. If that's correct, then maybe the bash script should wipe that when https is disabled.

**Comment by leighss** [comment]
```
sudo nextcloud.disable-https
sudo nextcloud.enable-https -d
sudo nextcloud.enable-https
```

But still old certificate

**Comment by nickvergessen** [comment]
Since this has nothing to do with the server, please report your issue in the snap repository
