### ISSUE TITLE
[files] Can not download many files with long file names

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#18562]
If you check to download many files (but not all in dir) for download, there is limit of url length reached and no download performed. I think parameters should pass via POST request

![изображение](https://user-images.githubusercontent.com/12619075/71427952-2eb4a100-2709-11ea-881e-1c814d99b5af.png)

**Comment by kesselb** [comment]
Thanks :+1:  

From a technical point it's a duplicate of https://github.com/nextcloud/server/issues/7935
