### ISSUE TITLE
User management view: Rethink table based layout for create / update

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18561]
**Is your feature request related to a problem? Please describe.**

![nextcloud test_settings_users (3)](https://user-images.githubusercontent.com/3902676/71379067-5b15d380-25ca-11ea-8954-ccce97ba844b.png)

The user management view is unclear and confusing.

**Describe the solution you'd like**

I think we should not use a table based layout for create and update user. I would expect that edit user will increase the "row heigh" and shows a form with the available options below the user and above the next one. Similar to Mailcow (see additional context) list but with inline edit.

**Additional context**

![demo pydio com_welcome_](https://user-images.githubusercontent.com/3902676/71379781-f4de8000-25cc-11ea-822b-09b50d96cb5e.png)

Pydio uses a list and a dialog for editing

![demo mailcow email_mailbox](https://user-images.githubusercontent.com/3902676/71379824-1dff1080-25cd-11ea-9cf0-33034db033d2.png)

Mailcow uses a list and plus button to show additional information. But a different page for edit.

**Comment by gary-kim** [comment]
There's some work going on in #18455

**Comment by skjnldsv** [comment]
for you @jancborchardt

**Comment by jancborchardt** [comment]
The reason both the view and edit layout is the same is so people don't need to do a mental switch. When you have symmetry there, you immediately know what to edit.

It would be great if you can clarify what you mean by "unclear and confusing".

As for the inspiration, could you check with more widely used systems than Pydio and Mailcow, e.g. Google Suite or Basecamp? :)

**Comment by kesselb** [comment]
> As for the inspiration, could you check with more widely used systems than Pydio and Mailcow, e.g. Google Suite or Basecamp? :)

I don't have a Google Suite or Basecamp but we can check their docs:

- [Basecamp](https://3.basecamp-help.com/article/72-inviting-people-to-a-project)
- [Google Suite](https://support.google.com/a/answer/33310?hl=en)

Unfortunately only a small part of the interface is visible. But Office 365 has a detailed online documentation with videos.

- [Create a user](https://docs.microsoft.com/en-us/office365/admin/add-users/add-users?view=o365-worldwide)
- [Change email address](https://docs.microsoft.com/en-us/office365/admin/add-users/change-a-user-name-and-email-address?view=o365-worldwide)

I have to say well done Microsoft. That's easy to use and understand hence not confusing. 

> It would be great if you can clarify what you mean by "unclear and confusing".

You looked at the screenshot? :rofl: 

1) There is a column password. It's only required for adding a user but takes space all the time. 
2) I'm used to fill forms from top to bottom. Every form works like that. Register for a service, Tax declaration, Report a issue on GitHub. Sometimes I have to use left to right. For example a attendee list: Id, Date and Signature. That works well for a few columns. Not if you have a lot of information. 
3) Ask yourself: Where is the save button for a new user? Ah you can use the arrow keys to navigate to the right to make it visible. Fair enough 1440 width is probably a bit small.
![image](https://user-images.githubusercontent.com/3902676/71559555-ceeb2c80-2a5f-11ea-98f1-4dba7a353411.png)
4) Additional columns can be shown. Isn't that already a warning sign the a interface is to complex? 
5) Create user button and exit edit mode button are using a different design language (excuse me if this is the wrong terminology) with the same list. The button to show the new user input list and create user button are the same. But that still looks weird.
![image](https://user-images.githubusercontent.com/3902676/71559676-5b4a1f00-2a61-11ea-88ae-f05212dbf768.png)
6) Nothing wrong with that. But I always have a facepalm moment when looking at it ;)
![Peek 2019-12-29 17-37](https://user-images.githubusercontent.com/3902676/71559717-f3480880-2a61-11ea-9cb3-c29b8920211e.gif)
7) Yes. We can fix 3+4 by adding more CSS but I think that's the wrong track. People will ask for more features. For example the "send email to new user" checkbox is already gone (it was within the settings menu but missing now). But that's a popular feature and makes sense. Such a option should be checkable when creating a user. Not within a menu. I have the feeling that features are killed for a nice user interface. 

> When you have symmetry there, you immediately know what to edit.

![image](https://user-images.githubusercontent.com/3902676/71559495-f7bef200-2a5e-11ea-804a-e200f83655c6.png)

It seems we don't have the same understanding of symmetry ;) The input for the display name is with the password column, password with the email column. 

![image](https://doc.owncloud.com/server/10.3/admin_manual/_images/configuration/user/users-page.png)

I think the owncloud view is less confusingly. User create form is not part of the user list. That's a clear separation.

**Comment by jancborchardt** [comment]
Soo, that’s a lot of separate things and I agree on a lot of them and have proposals to fix them, as you can see from my design review previously at https://github.com/nextcloud/server/pull/17239#issuecomment-564075366

As they are so separate, they should ideally be opened as separate issues. :) Could you open separate issues for those? Feel free to also quote my points from the issue above in the relevant ones.

------------------

Also a simpler way of doing the "New user" form I commented at 
https://github.com/nextcloud/server/pull/18455#issuecomment-568722666

> Also, if you notice, the new entry basically duplicates all of the header info. So instead of showing it below the heading, it could be shown instead of it. (Above via z-index.)

--------

So yes, let’s absolutely simplify this, but not get ahead of ourselves. :) Small steps and small iterations.

**Comment by kesselb** [comment]
> they should ideally be opened as separate issues.

If you think so ;) Feel free to open it in a way that makes sense.

**Comment by gary-kim** [comment]
![Screenshot_2020-02-17 User List - Admin Console](https://user-images.githubusercontent.com/47195730/74608418-bb814700-511b-11ea-8ab8-29ddcf51507e.png)
Came up earlier. This is what I see in Google Admin for GSuite.

**Comment by szaimen** [comment]
At least the creation dialog was put into a modal in NC22.
Though editing isn't changed, yet.
Do we want to leave this issue open or do we want to create a new one for the rest?
