### ISSUE TITLE
User management view: Stay usuable on smaller screen

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#18560]
### Steps to reproduce
1. Change resolution to 1440 (Laptop L chromium developer tools)
2. Enable at least one additional column (eg. user backend)
3. Try to edit a user

![nextcloud test_settings_users (1)](https://user-images.githubusercontent.com/3902676/71378894-b1364700-25c9-11ea-99cd-9d95b9a074b9.png)

![nextcloud test_settings_users (2)](https://user-images.githubusercontent.com/3902676/71378893-b1364700-25c9-11ea-8252-d238ad147cd6.png)

### Expected behaviour

I can click the edit button without using the arrow keys

### Actual behaviour

I need to use the arrow keys to make the edit button visible

**Comment by jancborchardt** [comment]
Yup, as also mentioned at https://github.com/nextcloud/server/pull/17239#issuecomment-564075366

> Stuff is a bit squished, especially the controls on the right? Having the controls sticky on the right would be much better to have them easily reachable without horizontal scrolling (which is a huge pain)

Simply making the controls sticky on the right will fix control discoverability and accessibility for both viewing and editing.

**Comment by jancborchardt** [comment]
cc @GretaD as there’s another person with the same feedback. :)

**Comment by GretaD** [comment]
thank you both for the suggestion, but this is not a bug but a feature :) will work on it.
