### ISSUE TITLE
Error installing 17.0.2 from occ maintenance:install

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#18569]
Simple commands:

### MariaDB 10.4

```
mysql -e "CREATE DATABASE IF NOT EXISTS nc_db CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; CREATE USER IF NOT EXISTS 'nc_db'@'%' IDENTIFIED BY 'pass'; GRANT ALL PRIVILEGES ON nc_db.* TO 'nc_db'@'%'; FLUSH PRIVILEGES; EXIT;"
```

### PHP 7.3
```
sudo -u www-data php occ maintenance:install \
     --database "mysql" \
     --database-host "10.0.0.3" \
     --database-name "nc_db" \
     --database-user "nc_db" \
     --database-pass "pass" \
     --admin-user "admin" \
     --admin-pass "pass"
```

### Output:

```
In SchemaException.php line 30:

There is no table with name 'nc_db.oc_twofactor_backupcodes' in the schema.

maintenance:install [--database DATABASE] [--database-name DATABASE-NAME] [--database-host DATABASE-HOST] [--database-port DATABASE-PORT] [--database-user DATABASE-USER] [--database-pass [DATABASE-PASS]] [--database-table-prefix [DATABASE-TABLE-PREFIX]] [--database-table-space [DATABASE-TABLE-SPACE]] [--admin-user ADMIN-USER] [--admin-pass ADMIN-PASS] [--admin-email [ADMIN-EMAIL]] [--data-dir DATA-DIR]
```
No problem using `17.0.1.tar.bz2` file instead of default `latest.tar.bz2`

**Comment by t-markmann** [comment]
Same issue here. 

PHP 7.3 
mysql  Ver 15.1 Distrib 10.3.20-MariaDB, for debian-linux-gnu (x86_64)

Command:
`sudo -u www-data php occ maintenance:install --database "mysql" --database-host "${dbhost}" --database-table-prefix "${instanceprefix}" --database-name "${dbname}"  --database-user "${dbsuperuser}" --database-pass "${dbsuperpass}" --admin-user "admin-ANON" --admin-pass "${adminpass}"`

Output:

> Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'oc_admin-1e2'@'nodeANON' (using password: YES)

Error occurs with Nextcloud **17.0.2 and 16.0.7**
Works fine with 17.0.1 and 16.0.6

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/server/issues/18513

**Comment by acs-ferreira** [comment]
@kesselb my error seems different perhaps. Others are about permissions, but feel free to close if you're sure they are linked.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
