### ISSUE TITLE
Login loop upon fresh install

### ISSUE THREAD

**Issue by CountOmega** [nextcloud/server#18564]
# Steps to reproduce
1. Fresh installation of NC 17.0.2 on Ubuntu 18.04
2. First run and login was successful
3. Afterwards not being able to login

### Expected behaviour
Login should work

### Actual behaviour
Loop

### Server configuration

**Operating system:**
Ubuntu 18.04.3 LTS
**Web server:**
Apache 2.4.29
**Database:**
mySQL Ver 15.1 Distrib 10.3.21-MariaDB
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
17.0.2.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
No
**Where did you install Nextcloud from:**
nextcloud.com

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.14.2
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.68:880"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "http:\/\/192.168.178.68:880\/nextcloud",
        "overwritehost": "192.168.178.68:880",
        "overwriteprotocol": "http",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
</details>

### Client configuration
**Browser:**
Firefox 71
**Operating system:**
Windows 10
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"WzCMrhgeWHAg3bb2qjeB","level":3,"time":"2019-12-24T23:23:15+00:00","remoteAddr":"192.168.178.204","user":"--","app":"PHP","method":"POST","url":"\/nextcloud\/index.php\/apps\/files\/index.php","message":"mkdir(): No such file or directory at \/var\/www\/nextcloud\/lib\/private\/Setup.php#302","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":""} 
{"reqId":"KZXiDCSEsyh4xMIXKnBA","level":3,"time":"2019-12-24T23:25:08+00:00","remoteAddr":"192.168.178.204","user":"--","app":"PHP","method":"POST","url":"\/nextcloud\/index.php\/apps\/files\/index.php","message":"mkdir(): Permission denied at \/var\/www\/nextcloud\/lib\/private\/Setup.php#302","userAgent":"Mozilla\/5.0 (Android 9; Mobile; rv:68.0) Gecko\/68.0 Firefox\/68.0","version":""}

```
</details>

**Comment by kesselb** [comment]
Have you checked similar issues? For example https://github.com/nextcloud/server/issues/13431. These login loop problems usually boils down to a not writable session path.

**Comment by CountOmega** [comment]
Thanks for the quick reply. I've already set the permissions for www-data at `/var/lib/php/session`. I even tried the fix mentioned in #13431 with the... /session.php, but to no end.

**Comment by ZehuanZhang** [comment]
i have this problem too, even in the fresh installation.
these folders have right permissions  for php-fpm and apache in cetnos7, so my nc still don't work.
:(

**Comment by CountOmega** [comment]
Do you have permissions set to root or www:data for the /php/sessions folder?

**Comment by ZehuanZhang** [comment]
> Do you have permissions set to root or www:data for the /php/sessions folder?

the sessions floder located in /var/lib/php/session is already have permission to edit and write. 
i notice that a session file is created after i click login button, but this problem is still exist.

**Comment by ZehuanZhang** [comment]
> Do you have permissions set to root or www:data for the /php/sessions folder?

i have found nother information, in my apache log files, i read a error like:

[Fri Dec 27 23:18:43.162983 2019] [core:crit] [pid 22272] (13)Permission denied: [client 192.168.1.1:57065] AH00529: /home/www-data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/www-data/' is executable, referer: http://****/

this error is so strange for me, any path in my nextcloud or apache configurations is format like /home/www-data/path/to/nextcloud. should the .htaccess in nextcloud/ instead of www-data/?

**Comment by ZehuanZhang** [comment]
> > Do you have permissions set to root or www:data for the /php/sessions folder?
> 
> i have found another information, in my apache log files, i read a error like:
> 
> [Fri Dec 27 23:18:43.162983 2019] [core:crit] [pid 22272] (13)Permission denied: [client 192.168.1.1:57065] AH00529: /home/www-data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/www-data/' is executable, referer: http://****/
> 
> this error is so strange for me, any path in my nextcloud or apache configurations is format like /home/www-data/path/to/nextcloud. should the .htaccess in nextcloud/ instead of www-data/?

I solved this problem through occ command:
php occ maintenance:update:htacess

may it help others

**Comment by CountOmega** [comment]
Unfortunately, this didn't work for me. The issue still persists.

**Comment by CountOmega** [comment]
Now I have set up a completely new installation an used the .htaccess fix in the very beginning of it. Haven't had any problems since.

**Comment by ismailyenigul** [comment]
Hello,
I had the same issue. After re-install nextcloud I could not login page from another site via iframe.  I was getting redirected you too many times on Chrome 
I added the following Header to .htaccess to fix the problem.
```
 Header edit Set-Cookie ^(.*)$ "$1; HttpOnly; Secure; SameSite=None" 
```
in <IfModule mod_env.c> block.

I am using traefik as a reverse proxy and added the following label

      - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' *.myexternaldomain.com

Also I had to add/change 
```
  'overwriteprotocol' => 'https',
  'overwrite.cli.url' => 'https://mynextcloud.domain.com',
```

**Comment by wedsonlopes** [comment]
> Hello, I had the same issue. After re-install nextcloud I could not login page from another site via iframe. I was getting redirected you too many times on Chrome I added the following Header to .htaccess to fix the problem.
> 
> ```
>  Header edit Set-Cookie ^(.*)$ "$1; HttpOnly; Secure; SameSite=None" 
> ```
> 
> in block.
> 
> I am using traefik as a reverse proxy and added the following label
> 
> ```
>   - traefik.http.middlewares.nextcloud.headers.contentSecurityPolicy=frame-ancestors 'self' *.myexternaldomain.com
> ```
> 
> Also I had to add/change
> 
> ```
>   'overwriteprotocol' => 'https',
>   'overwrite.cli.url' => 'https://mynextcloud.domain.com',
> ```

I just saved few hours of research bro, it worked on fresh install of Nextcloud Hub 9 (30.0.2)
