### ISSUE TITLE
17.0.1 to 17.0.2 group folders key length too long

### ISSUE THREAD

**Issue by glossner** [nextcloud/server#18571]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_group_folders_trash ADD file_id BIGINT DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Detailed logs 
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_group_folders_trash ADD file_id BIGINT DEFAULT NULL': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by glossner** [comment]
Following up... 

I'm using MariaDB under Centos 7. I checked and it is configured for utf8mb4 support. This only happened from 17.0.1 to 17.0.2 upgrade. The upgrade from NC16->NC17 didn't show this problem.

I deleted group_folders from the apps directory and masked the problem. 

Not a server issue. Just fyi. Thanks.

**Comment by glossner** [comment]
Adding the last two lines to /etc/my.cnf fixed this:

[mysqld]
transaction_isolation=READ-COMMITTED
binlog_format=ROW
innodb_file_per_table=1
innodb_large_prefix=1
innodb_file_format=barracuda
