### ISSUE TITLE
USER_AGENT_CHROME doesn't match Vivaldi

### ISSUE THREAD

**Issue by Cybso** [nextcloud/server#18579]
The regular expression used for detecting Chrome-based browsers doesn't match Vivaldi, and possibly other browsers as well. The current expression is:

`/^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[0-9.]+ \(KHTML, like Gecko\)( Ubuntu Chromium\/[0-9.]+|) Chrome\/[0-9.]+ (Mobile Safari|Safari)\/[0-9.]+$/`

Vivaldi identifies as:

`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.99 Safari/537.36 Vivaldi/2.9.1705.41`

So the problem is the "Vivaldi/2.9.1705.41" suffix. I think it would be safe to remove the EOL marker ("$") at the end of the expression to match other chrome based browsers as well. What do you think?

**Comment by kesselb** [comment]
`^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[0-9.]+ \(KHTML, like Gecko\)( Ubuntu Chromium\/[0-9.]+|) Chrome\/[0-9.]+ (Mobile Safari|Safari)\/[0-9.]+( (Vivaldi|Brave)\/[0-9.]+|)$`

I would go for.
