### ISSUE TITLE
Can't login with email

### ISSUE THREAD

**Issue by ChevalierDeBalibari** [nextcloud/server#18570]
Hello, from recently we are unable to login via email/password but only username and password. 

### Steps to reproduce
1. enter valid user email and password
2. try to login

### Expected behaviour
Successfull login

### Actual behaviour
Wrong username or password message

### Server configuration

**OS:** 
Centos7 19.10
**Web server:**
Apache/2.4.6 (CentOS)
**Database:**
mysql  Ver 15.1 Distrib 5.5.64-MariaDB, for Linux (x86_64) using readline 5.1
**PHP version:**
PHP 7.2.24 (cli) (built: Nov  4 2019 10:23:08) ( NTS )
**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Migration from our old server
**Where did you install Nextcloud from:**
Self hosted
**Signing status:**

<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_mindmap: 0.0.15
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "drive.office.ars",
            "cloud.office.ars",
            "nextcloud.office.ars"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "http:\/\/drive.office.ars",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpport": "465",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Comment by kesselb** [comment]
Log section from issue template is missing. Also check your browser console for possible errors.

**Comment by ChevalierDeBalibari** [comment]
Hi!

I actually found the "bug" this morning. Due to server migration passwords stopped working but everyone can simply reset them, so its not an issue. 

My issue was that i had same email for my personal and admin account. It would be handy to have some separate email to receive administrative notifications.

With matter resolved, this can be closed.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Do you changed the `passwordsalt` during the server migration? If not password should continue to work I guess.
