### ISSUE TITLE
Create a native function to data replication with an other Nextcloud instance

### ISSUE THREAD

**Issue by CLeBeRFR** [nextcloud/server#18589]
**Is your feature request related to a problem? Please describe.**
I am affraid to lose my data if my Raspberry crash, burn, is stolen or something else.
I would like to install an other instance of Nextcloud 17 on my friend’s home and mutualise the storage.

**Describe the solution you'd like**
I would like a simple solution to synchronize and double all my data on both Nextcloud instances. For example if my _raspberry1-in-my-house.com_ crash, I change the Nextcloud application to _raspberry2-in-my-friend-house.com_ and all files will be the same.
Of course, all files in both instances should be encrypted.

**Describe alternatives you've considered**
The only solution at this moment is to synchronize on my computer my Nextcloud data. Thus, if my raspberry crash or is stolen, I have the files on my computer hard drive.

**Comment by kesselb** [comment]
That sounds like https://github.com/nextcloud/server/issues/17679?

**Comment by cloo** [comment]
Falsely closed as recursive duplicates?
The issue was closed as a duplicate for #17679, while #17679 was closed as a duplicate for this one.
