### ISSUE TITLE
Nextcloud 18 Beta: Installation not possible

### ISSUE THREAD

**Issue by benhartwich** [nextcloud/server#18587]
Hi,

it is not possible to install the release Nextcloud 18 beta 3 and 4 manually because the 3party folder is completely empty: "Composer autoloader not found, unable to continue. Check the folder "3rdparty". Running "git submodule update --init" will initialize the git submodule that handles the subfolder "3rdparty"."

I´ve downloaded the release file from the github repository at releases.

**Comment by kesselb** [comment]
Thanks for checking the beta :+1: 

Steps to install Nextcloud from source (git) are here: https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html
