### ISSUE TITLE
Notification Spam

### ISSUE THREAD

**Issue by JakeAi** [nextcloud/server#18586]
How do you disable this? It happens on my Macbook and windows. I'll wake my computers and have 30 of these things blow up my desktops.

![kdJRSEU](https://user-images.githubusercontent.com/3902676/71544458-eeab2380-297f-11ea-80ab-7bd520109d3b.png)

**Comment by kesselb** [comment]
I usually disable them via web ui or android app. I don't know if that works with desktop clients. 

A general note: Here on GitHub we track bugs and feature requests. For support / configuration / questions please visit https://help.nextcloud.com (or https://portal.nextcloud.com for users with a support subscription). 

If you want to report a bug or a feature request please use the templates: https://github.com/nextcloud/server/tree/master/.github/ISSUE_TEMPLATE
