### ISSUE TITLE
Uploading multiple files at once not working on mobile Safari

### ISSUE THREAD

**Issue by xMartin** [nextcloud/server#1859]
### Steps to reproduce
1. Create folder and share link with edit permission and hide file list option set
2. Open share link in mobile Safari (iOS)
3. Click "choose files" button and select two images from your foto library
### Expected behaviour

All two images being uploaded and appearing in my files app.
### Actual behaviour

Only one of the two pictures appearing in my files app.
### Server configuration

**Operating system**:
Linux

**Web server:**
Apache

**Database:**
SQLite

**PHP version:**
5.6.21

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
from ownCloud 9

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>

Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>
<summary>

App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
#### LDAP configuration (delete this part if not used)

<details>
<summary>

LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

</details>
### Client configuration

**Browser:**
Safari

**Operating system:**
iOS 9.3.5 (iPhone 4S)
#### Web server error log

<details>
<summary>

Web server error log</summary>

```
Insert your webserver log here
```

</details>
#### Nextcloud log (data/nextcloud.log)

<details>
<summary>

Nextcloud log</summary>

```
Insert your Nextcloud log here
```

</details>
#### Browser log

<details>
<summary>

Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

</details>

This probably happens because iOS mobile Safari names all uploaded files "image.jpeg", no matter what...

**Comment by jancborchardt** [comment]
cc the folks who have mobile Safari to test and possibly fix this: @nextcloud/ios @nextcloud/mac :)

**Comment by generated** [comment]
We are having the same issue. It seems the mobile safari gives it some generated name like 'FB7334E8-09D2-48E3-8BE1-2A9ED7C321F6.jpeg'. If you only select images it manages to upload 2 or 3 files before aborting, if you throw in videos as well it fails after first file.

**Comment by gryban1** [comment]
Same problem with firefox on my mobile phone. it also renames the uploaded files. But it works with the buildin "lite mode" from firefox.

**Comment by mcnesium** [comment]
I found a "secret workaround" later then, that at least works for me:

on an **upload only**-share the iOS Safari is able to upload multiple files. They are still renamed to `image.jpeg` but in contrast to a regular share upload they do not overwrite each other but like this:

    mcn@tx ~/upload ls image*
    'image (10).jpeg'  'image (3).png'   'image (6).jpeg'
    'image (2).jpeg'   'image (4).jpeg'  'image (6).jpg' 
    'image (2).jpg'    'image (4).jpg'   'image (7).jpeg'
    'image (2).png'    'image (4).png'   'image (7).jpg' 
    'image (3).jpeg'   'image (5).jpeg'  'image (8).jpeg'
    'image (3).jpg'    'image (5).jpg'   'image (8).jpg'

**Comment by acsfer** [comment]
Can someone confis this still an issue with latest iOS/Safari and NC 21+ ?

**Comment by rakekniven** [comment]
NC v22.2.3, iOS 15.2

Just tried it with three files (two jpgs and one png) and it works.
All three files are uploaded at once.

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by xMartin** [comment]
Works with latest versions 👍
