### ISSUE TITLE
Privacy leaked? Comments visible to other users not in same group

### ISSUE THREAD

**Issue by Quix0r** [nextcloud/server#18590]
The following possible privacy leak happens on web interface, maybe android client, too:

### Steps to reproduce
1. Create 2 users, 2 groups.
2. Assign each into separate group
3. enable privacy option, that they cannot see each other
4. user1 comments on a path shared with both users by 3rd person
5. user2 can see comment of user1

### Expected behaviour
user1 should not see comments from user2 and vise versa

### Actual behaviour
The users can see comments from each other.

### Server configuration

**Operating system:**
Linux

**Web server:**
Apache

**Database:**
MariaDB 10

**PHP version:**
7.0 (I know, I know, I need a systemd-free system)

**Nextcloud version:** (see Nextcloud admin page)
15.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated as usual

**Where did you install Nextcloud from:**
Main website (TAR ball)

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Are you using external storage, if yes which one:**
local

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
internal

### Client configuration
**Browser:**
Firefox

**Operating system:**
Linux

**Comment by Quix0r** [comment]
If that is not generally wished, please add another option to have comments included in that said privacy setting (users from different groups cannot see each other, still in comments possible!).

**Comment by kesselb** [comment]
> user1 should not see comments from user2 and vise versa

If a file is shared to both of them I would expect that the comments are visible to both. But that's probably open for discussion. 

 > Nextcloud version: 13

Is this still valid for newer versions? 13 is EOL for a while. https://try.nextcloud.com if you need a test instance.

**Comment by Quix0r** [comment]
Yes, I have to update it to latest version. :-) Will go for it maybe before New Year.

**Comment by Quix0r** [comment]
And it would be very helpful, if users should really never see each other ("stealth mode") at all. :-)

**Comment by Quix0r** [comment]
Updated to 15.0.9 (found by trying semantic version pattern). I retry now.

**Comment by Quix0r** [comment]
I run the update by:
- remove all files and directories except `app`, `config`
- removed within `app` all directories that are in the update package, too
- move the unpacked update files
- run `chmod 0700 occ`
- run `./occ upgrade`
- manually update incompatible addons

**Comment by rullzer** [comment]
If users have access to the same file they will see each others comments.
Just as they will see each others activities and versions.

Else you get weird situations where the owner of the file (so that shared it with the users) can see both comments but the others can not.

**Comment by Quix0r** [comment]
Privacy has been leaked through commenting on a file both can see. E.g. if my girlfriend (group `crush`) comments on a file, my mother (group `family`) can download. She can see my girlfriend's name. But elsewhere she cannot.

What would be nice is an option to enable (default disabled), like "user cannot see comments from users belonging to other group" or so. Then we have more stricter privacy, otherwise my mother knows about my girlfriend's details as exposed other the small tooltip (email/XMPP address).

**Comment by Quix0r** [comment]
Activity, usually not visible (I don't know at current state with comments being visible? Another leak then), contacts search boxes, like in "Share with someone" boxes (Sharing a file), not leaked there.

That is why I was nervous about that my mother can have access on my girlfriend's contact data for private reasons.
