### ISSUE TITLE
no login boxes after fresh install

### ISSUE THREAD

**Issue by wingsoul** [nextcloud/server#18591]
### Steps to reproduce
1. install nextcloud in ubuntu 18.04
2.
3.

### Expected behaviour
Suppose I can type login information to login

### Actual behaviour
Not able to type login information because....there is no login boxes

### Server configuration

**Operating system:** 
Unbutu 18.04

**Web server:**
nginx 1.14.0

**Database:**
mariadb 10.1.43

**PHP version:**
php7.2 with following module
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
imagick
intl
json
libxml
mbstring
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

**Nextcloud version:** (see Nextcloud admin page)
nextcloud 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
follow this post and change version to 17.0.2
https://www.linuxbabe.com/ubuntu/install-nextcloud-ubuntu-18-04-nginx-lemp

and use CLI install
https://docs.nextcloud.com/server/17/admin_manual/installation/command_line_installation.html

Image of login:
![Screenshot_20191228_151511](https://user-images.githubusercontent.com/3104634/71550452-4b5d0d00-2985-11ea-8d8b-20dfe2a486c2.png)
</details>

**Comment by kesselb** [comment]
Thanks for taking the time to report a issue :+1: 

> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.


Unfortunately you have overlooked the first paragraph of the issue template :disappointed: Also the most important information (configuration export, nextcloud log, browser log) are missing :-1:
