### ISSUE TITLE
"occ files:scan" doesn't support UTF encoded filenames

### ISSUE THREAD

**Issue by StCyr** [nextcloud/server#18605]
### Steps to reproduce
1. create a local external share
2. add a folder having an UTF encoded name ("eg: '2018-07-01 Vacances Bollu-Mao \u00e0 la mer du nord') and place a bunch of files in there
3. run "occ files:scan --all"

### Expected behaviour
When browsing the external share, nextcloud should show the UTF encoded folder.

### Actual behaviour
The UTF-encoded folder is not shown.

### Additional info

root@raspberrypi:/var/www/nextcloud# sudo -u www-data php7.3 occ files:scan --all
Starting scan for user 1 out of 1 (admin)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 11      | 176   | 00:00:47     |
+---------+-------+--------------+
root@raspberrypi:/var/www/nextcloud# mv /mnt/external/www/2018-07-01\ Vacances\ Bollu-Mao\ à\ la\ mer\ du\ nord /mnt/external/www/2018-07-01\ Vacances\ Bollu-Mao\ a\ la\ mer\ du\ nord/
root@raspberrypi:/var/www/nextcloud# sudo -u www-data php7.3 occ files:scan --all
Starting scan for user 1 out of 1 (admin)
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 12      | 242   | 00:01:19     |
+---------+-------+--------------+
root@raspberrypi:/var/www/nextcloud# 

### Server configuration

**Operating system:**

Raspbian

**Web server:**

Apache

**Database:**

Mariadb

**PHP version:**

7.3

**Nextcloud version:** (see Nextcloud admin page)

17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...

local

**Are you using encryption:** yes/no

https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration
**Browser:**

Firefox

**Operating system:**

MacOS

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

When running the "occ files:scan" command with an UTF encoded folder name, the following message pops up in the log:

```
Dec 29 19:41:06 raspberrypi Nextcloud[3014]: {"reqId":"IoYxfNx1ZU6KQIJBGqBN","level":0,"time":"2019-12-29T18:41:06+00:00","remoteAddr":"","user":"--","app":"OC\\Files\\Cache\\Scanner","method":"","url":"--","message":"!!! Path '2018-07-01 Vacances Bollu-Mao \u00e0 la mer du nord' is not accessible or present !!!","userAgent":"--","version":"17.0.1.1"}
```
</details>

**Comment by kescherCode** [comment]
Must have been in Nextcloud at least since 15, since that's where I last encountered it. Never got around to report it though.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
