### ISSUE TITLE
User menu and contacts menu are missing triangle indicators

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#18606]
Before: Nice triangle indicator as we do elsewhere with all menus and especially with the header to have a sense of space:
![user menu old](https://user-images.githubusercontent.com/925062/71571282-19c27e00-2b0c-11ea-90c1-955dbce079cd.png)

In master: The triangle is missing? This is both for the user menu and contacts menu.
Also the animation seems to come in from the right which does not really make a lot of sense – it should come in from above only.
![avatar menu](https://user-images.githubusercontent.com/925062/71571283-1a5b1480-2b0c-11ea-8d01-1e36f3f24141.png)

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Same issue for the "More" apps menu and the notifications menu actually. What happened here? :D

**Comment by juliushaertl** [comment]
Seems to be a regression of https://github.com/nextcloud/server/pull/16057 I'll have a look
