### ISSUE TITLE
(Allow to) Keep copy of shared files

### ISSUE THREAD

**Issue by Bibo-Joshi** [nextcloud/server#18600]
**Is your feature request related to a problem? Please describe.**
When sharing files it may quickly become desirable to tidy up the list of shares by unsharing files that won't be updated anymore (my most common use case: directories of pictures. I share them so the recipients have them, but I usually won't add more pictures later). But **unsharing files deletes them at the recipient side.**
I tested this behaviour by deleting the share both from my side and the recipient side and also via remote share (i.e. share with User@https://theirnextcloud.com). I was surprised by the latter finding, since this [answer](https://help.nextcloud.com/t/keep-shared-folder-without-copying-it/26407/2?u=bibo-joshi) states otherwise.

**Describe the solution you'd like**
A propose adding a "(Allow to) Keep copy" option to the "Delete share" button. That way both sides of the share may decide for the recipient to keep the data, when removing the share.

**Describe alternatives you've considered**
Letting the recipient keep a copy by default would also be okay.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by Bibo-Joshi** [comment]
Hi. Thanks for the response @szaimen . I have very limited knowlegde of PHP, JS & databases and haven't contributed to NC before, but I'd be willing to try & PR. So I had a look at the source code to try & get a grasp of what would have to be done.

What I realized is that shared files are not actually copied to the recipients storage. Ofc this makes sense when thinking about it, but it probably makes this rather complicated: When a share is unshared & the recipient should keep the data, NC would have to copy the shared files over to the recipient. TBH I haven't gotten much further yet, but I'm wondering if that's feasible at all. I imagine that if the shared files are large (in size or numbers), copying will take a while and if the sharee changes any of the files in the meantime, one would have to make sure to copy the old state and similar issues …

IISC, copying the data can somehow be done with the following function:

https://github.com/nextcloud/server/blob/fdb2b07803b54dc65a7db693c3c04e6e6a02b36c/apps/files_sharing/lib/Controller/ShareController.php#L540-L552

Would this already take care of such fallpits?

Also, I wasn't quite able to grasp where the "unshare" action happens. I found 

https://github.com/nextcloud/server/blob/fdb2b07803b54dc65a7db693c3c04e6e6a02b36c/apps/files_sharing/lib/Controller/RemoteController.php#L167-L177

but that seems to be only used for federation shares?

Maybe you could give me a rough judgement on whether this looks like a more-or-less-simple task to you or whether this would be a larger project?
