### ISSUE TITLE
I get error when I try get basket.

### ISSUE THREAD

**Issue by Shucach** [nextcloud/server#18601]
**TypeError: Return value of OCA\Files_Trashbin\Sabre\AbstractTrash::getSize() must be of the type int, float returned**

raspberrypi pi 3b+
php 7.3
server Apache 2

**Comment by kesselb** [comment]
Thanks for taking the time to report a problem :+1: 

See https://github.com/nextcloud/server/issues/13160 for details and possible workaround.
