### ISSUE TITLE
Login failure on web interface, but reload main page successed

### ISSUE THREAD

**Issue by huangyingjie** [nextcloud/server#18602]
### Steps to reproduce
1. Build nextcloud server with docker image latest.
2. Login with admin user on web interface.
3. Path `/login`  http status is `canceled`; And System log show `Login failure`, `no app in context`; My domain is https, but `/login` is `http`.
4. But go to main page `/` in browser address, the page redirect to `/apps/files/`.
### Expected behaviour
1. login success, and redirect to `/apps/files/`, do not show error .
2. `/login`'s domain protocal should be 'https', not 'http'
### Server configuration

**Operating system:** debian 10

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 17.0.2

**Where did you install Nextcloud from:** offical Nextcloud docker image

**Comment by kesselb** [comment]
The reverse proxy is not listed as trusted_proxy or the headers are not forwarded. By default `nextcloud:apache` will replace the ip with the forwarded one in some scenarios.

Please check https://github.com/nextcloud/docker/pull/819#issuecomment-541434657 for all the details. tl;dr set `overwriteprotocol` and `overwritehost`.

**Comment by huangyingjie** [comment]
awesome,thx
