### ISSUE TITLE
Bugged pic download

### ISSUE THREAD

**Issue by julia-berlin** [nextcloud/server#18614]
### Steps to reproduce
1. Nextcloud android App 3.9.2
2. Several Android Version 
3. Trying to dowload Pictures

### Expected behaviour
Pics are dowloaded, reduced image shown in list 

### Actual behaviour
None of the above, instead this error message:
"kein verkleinertes Bild verfügbar. Vollbild herunterladen?"
English: No reduced image available. Download full screen?

### Server configuration

**Operating system:**
Several Android Versions

**Web server:**
Cloud.bitkomplex.de

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
3.9.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updatesd and fresh install, cause I tried to remove the bug by deinstallation and new install.

**Where did you install Nextcloud from:**
Playstore

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by j-ed** [comment]
I assume that you haven't created preview pictures on your server and therefore only the full-size image can be downloaded. Make sure that you generate the previews and everything should be ok.

BTW, this is the development bug tracker and not the Nextcloud help forum, which you find [here](https://help.nextcloud.com/). 😉

**Comment by julia-berlin** [comment]
Thanks a lot! This is it :-D
Couldn't find anything about it, so I thought that this is a good place. Sorry for the spam and happy new year ;-)
