### ISSUE TITLE
File integration in an outer web site

### ISSUE THREAD

**Issue by BugProg** [nextcloud/server#18617]
Hello !
We are Nextcloud users and for one of our projects, We have put ".cpp" files in our Nextcloud server and we would like to integrate it in our web site which provides these c++ code files but with a nice interface. Therefor we are looking for a way to integrate it as it's possible with [codepen](https://codepen.io/pen/), because our .cpp files in Nextcloud are automatically updated when we modify it on my computer and we would like the same system on my web site.

Thanking you for the attention you will please give to our request, best regards,
Adrien and Ethan

**Comment by kesselb** [comment]
Thanks for reporting issues back to Nextcloud!

Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
