### ISSUE TITLE
Updater.phar issue with php7.4 as default

### ISSUE THREAD

**Issue by furai** [nextcloud/server#18616]
### Steps to reproduce
1. Run `php7.3 updater.phar` from commandline on 17.0.1 version to upgrade to 17.0.2

### Expected behaviour
Updater should run without problems.

### Actual behaviour
Updater failed on `occ upgrade` step. Most likely because of hardcoded reference to `php` binary.

### Server configuration
**Operating system:** Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:**  17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older version.

**Where did you install Nextcloud from:** Official website package.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.furai.pl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nextcloud.furai.pl",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 1
        },
        "maintenance": false,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "spreed"
        ]
    }
}
```
</details>

I haven't included all the rest requested here as I think they're irrelevant to the issue.
I have multiple versions of PHP installed on my system. 7.4 being default one. I expect the updater to use the version of php which it was invoked with.

I've run after failed update `php7.3 occ upgrade` on my own and lifted the maintenance mode. I hope I'm not missing any steps in the update process.

Cheers,
Furai

**Comment by kesselb** [comment]
Thanks for taking the time to report a problem :+1: 

Check this other report: https://github.com/nextcloud/updater/issues/261
