### ISSUE TITLE
[Transfer ownership] Input field autocomplete unreliable

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18624]
Autocomplete for ownership transfer receiver is not working reliably. I usually have to try different pronounciations until a user is found.

In my test setup, I try transfering to user "Henri", but the list keeps saying it's empty until I try "henri" - afterwards it does find "Henri" as well (weird upper-/lowercase behavior)

![01_unreliable](https://user-images.githubusercontent.com/1804221/71653738-874df480-2d2e-11ea-923b-b0c00c356a18.gif)

**Comment by wiswedel** [comment]
sorry, wrong title. just changed.

**Comment by ChristophWurst** [comment]
Created user `Henri` as well.

I can find it looking for `Henr` or `henr`. As soon as I add the `i` I don't get any results. BUT adding `í` gives me `Henri`. Hence this is something about locales or encoding? @juliushaertl @skjnldsv any clue?

**Comment by ChristophWurst** [comment]
> As soon as I add the `i` I don't get any results. BUT adding `í` gives me `Henri`

Note the two different characters i and í.
