### ISSUE TITLE
[Transfer ownership] allow some more padding between labels and inputs

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18623]
Padding between labels and inputs is currently quite narrow.

![image](https://user-images.githubusercontent.com/1804221/71653492-00e4e300-2d2d-11ea-8fb8-6a3ee9bd4eac.png)

**Comment by wiswedel** [comment]
CC @nextcloud/designers

**Comment by jancborchardt** [comment]
Yup, setting to good first issue! :)

The changes have to be made in https://github.com/nextcloud/server/blob/master/apps/files/src/components/TransferOwnershipDialogue.vue, the CSS is at the bottom of the file.

**Comment by ChristophWurst** [comment]
Doesn't look like anyone picked up the *good first issue*. @jancborchardt mind fixing this for 18?
