### ISSUE TITLE
[Transfer ownership] Input field for new owner too narrow

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18625]
Autocomplete results from the transfer ownership input field are cut quite early because the field is so narrow

![size and confirmation](https://user-images.githubusercontent.com/1804221/71654072-f0823780-2d2f-11ea-90b3-328cb1a85787.gif)

**Comment by rullzer** [comment]
@skjnldsv @juliushaertl @ChristophWurst I guess this needs a fix in the vue multiselect component stuff right?

**Comment by skjnldsv** [comment]
@rullzer no, we need to increase the min-width/width on the ui in server :)

**Comment by ChristophWurst** [comment]
But what is a good value for "min width"? Isn't that problematic on mobile?

**Comment by skjnldsv** [comment]
@ChristophWurst you can also try using flex grow, should work as well
