### ISSUE TITLE
[Transfer ownership] bad click behavior on selecting from suggestions

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18626]
Clicking on one of the suggested transfer receivers seems to accept the entry, but there's no feedback on the input field about it:

![size and confirmation](https://user-images.githubusercontent.com/1804221/71654133-4820a300-2d30-11ea-9008-6bf216ba1ecb.gif)

## Steps to reproduce

1. select a file to transfer
2. type in the user to transfer to
3. see autocomplete showing some suggestions
4. click on a suggestion
5. **see no feedback from the input field**
6. see the final button accepting the target user
7. click somewhere into blank
8. see the input field accepting the target user

**Comment by ChristophWurst** [comment]
That is how the multiselect component looks. 

>     5\. see no feedback from the input field

What kind of feedback would you expect? cc @nextcloud/vuejs

**Comment by wiswedel** [comment]
> What kind of feedback would you expect?

If I click on an entry, the entry gets applied, the suggestions go away - like for sharing.

> That is how the multiselect component looks.

No need for multiselect here.

**Comment by ChristophWurst** [comment]
> No need for multiselect here.

It's the name of the component used for the user list. We use single select here.
