### ISSUE TITLE
18b4 sharing auto-accept setting label displaced

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18627]
The label for the share-auto-accept checkbox in the personal sharing settings page is displaced:

![image](https://user-images.githubusercontent.com/1804221/71654717-8370a100-2d33-11ea-87d0-0853184bdd19.png)

**Comment by wiswedel** [comment]
cc @nextcloud/designers

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/server/pull/18628
