### ISSUE TITLE
Wording for unsharing incoming share

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18622]
Calendar 2.0 (NC 18+) uses the wording "Unshare from me" for opting out of incoming shares.

![image](https://user-images.githubusercontent.com/1804221/71653222-9da68100-2d2b-11ea-82ad-8511d309d16f.png)

I like that clarification that points out the difference between being the share owner and being the sharee, so I suggest to have that wording in Files as well.

Should this request get rejected, the issue needs to addressed as a UX streamlining issue at https://github.com/nextcloud/calendar/.

**Comment by wiswedel** [comment]
CC @nextcloud/designers

**Comment by jancborchardt** [comment]
We never use "me" or "my" so the wording is definitely nonstandard. It could be "Unshare from self" but that’s a bit odd.

I think it’s enough to have the 2 distinct actions:
- If you are the owner: You manage shares via "Share", and the destructive action is "Delete" with an icon-delete trashbin.
- If you are recipient: The destructive action is "Unshare" with an icon-close X.

So I’d say Calendar should adjust to use Unshare with an icon-close X. cc @georgehrke

**Comment by wiswedel** [comment]
> We never use "me" or "my"

What about this then?
![image](https://user-images.githubusercontent.com/1804221/71654332-6f2ba480-2d31-11ea-8548-a7b5dd693290.png)

**Comment by jancborchardt** [comment]
@wiswedel that’s "you", which we do use as it’s conversational. :) But we never use "me", which is basically personifying the software.

So we could write "Unshare from you". We should adjust it in Calendar @georgehrke, and then also use that in Files.

**Comment by jancborchardt** [comment]
Pull request to fix this at https://github.com/nextcloud/server/pull/22376
