### ISSUE TITLE
bug on update 17.0.2

### ISSUE THREAD

**Issue by brunofilipesequeirapinto** [nextcloud/server#18629]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_calendar_resources_md (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, resource_id BIGINT UNSIGNED NOT NULL, `key` VARCHAR(255) NOT NULL, value VARCHAR(4000) DEFAULT NULL, INDEX calendar_resources_md_idk (resource_id, `key`), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by juliushaertl** [comment]
@georgehrke

**Comment by juliushaertl** [comment]
@brunofilipesequeirapinto Please fill out the issue template with more information about your setup, especially what database you are using. If it is mysql, please check if 4byte support is enabled: https://docs.nextcloud.com/server/17/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
