### ISSUE TITLE
[18beta4] empty action menu behind sharees' profile picture if no email address configured

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18633]
Click on a sharee's profile picture in the sharing sidebar only reveals a little triangle below it, but there's no action menu appearing.

Plus: The triangles don't disappear any more.

![sidebar](https://user-images.githubusercontent.com/1804221/71667693-791bca80-2d66-11ea-8f31-930bde04e88a.gif)

**Comment by wiswedel** [comment]
Update: this only happens when the sharee has no email address configured or Talk isn't installed.

**Comment by wiswedel** [comment]
update2: applies also to click on the share owner's profile pic

![sidebar2](https://user-images.githubusercontent.com/1804221/71667824-fba48a00-2d66-11ea-9746-eac22e9f9c42.gif)

**Comment by blizzz** [comment]
removing the milestone. Wonder, whether this is still valid anyways.
