### ISSUE TITLE
[18beta4] recommended apps unclear

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18631]
On a fresh installation of NC 18, there's a checkbox "Install recommended apps".
However, there is no explaination,

- which apps that would be
- how many 
- why they are recommended and for what purpose

Later in the app store, you see only the label "Featured", but there's no way to find out,

- which apps were the recommend ones on installation (if you had installed them on setup)
- which are the recommended ones if you skipped them on setup and might refer to the offer later

**Comment by wiswedel** [comment]
cc @oparoz

**Comment by rullzer** [comment]
@jancborchardt @karlitschek

**Comment by jancborchardt** [comment]
Totally agree. As mentioned in our Talk conversation early December:

> Also we should tell ppl what the recommended apps are before pressing the button ;)
> - MVP: show a tooltip with the app names as text
> - Best: Put an `icon-info` right next to the label, which expands a list of the apps below, left icon and right the name + description (basically just like it looks in the recommendation Notification)

**Thinking about it, we can also simply put a line below it slightly greyed out, saying: "Calendar, Contacts, Talk & Mail" – much simpler and directly visible.**

**Comment by wiswedel** [comment]
> Thinking about it, we can also simply put a line below the "Install recommended apps" checkbox label, slightly greyed out, saying: "Calendar, Contacts, Talk & Mail" – much simpler and directly visible.

+1
It'll be also the best option in terms of accessibility.

**Comment by karlitschek** [comment]
I agree with @jancborchardt

**Comment by ChristophWurst** [comment]
> Thinking about it, we can also simply put a line below the "Install recommended apps" checkbox label, slightly greyed out, saying: "Calendar, Contacts, Talk & Mail" – much simpler and directly visible.

@jancborchardt so a simple span after https://github.com/nextcloud/server/blob/c2266da9413501aa1b7efb9a712b3011a1ebe5ee/core/templates/installation.php#L166? Do we have any existing styles/classes for the *greyed out* part?

**Comment by rullzer** [comment]
> > Thinking about it, we can also simply put a line below the "Install recommended apps" checkbox label, slightly greyed out, saying: "Calendar, Contacts, Talk & Mail" – much simpler and directly visible.
> 
> @jancborchardt so a simple span after
> 
> https://github.com/nextcloud/server/blob/c2266da9413501aa1b7efb9a712b3011a1ebe5ee/core/templates/installation.php#L166
> ? Do we have any existing styles/classes for the _greyed out_ part?

Just go for that right now :wink:

**Comment by jancborchardt** [comment]
Pull request to fix this at https://github.com/nextcloud/server/pull/18873
