### ISSUE TITLE
Remote share results in a 405 Method Not Allowed response

### ISSUE THREAD

**Issue by mcnesium** [nextcloud/server#18637]
### Steps to reproduce
1. Receive a folder share from a remote Nextcloud instance.
2. Accept share from bell-menu.

### Expected behaviour
Shared folder should appear in home directory, opening it should reveal remote contents.

### Actual behaviour
Shared folder does not appear, instead the following message appears in the logs:

> [no app in context] Error: error while sending notification for federated share: Client error: `POST http://cloud.remoteinstance.de/index.php/ocm/notifications` resulted in a `405 Method Not Allowed` response
> 
> POST /ocs/v2.php/apps/files_sharing/api/v1/remote_shares/pending/49
> from 192.168.0.1 by mcnesium at 2020-01-02T17:51:57+00:00

Reloading the files view makes the shared folder appear. But when trying to open it, only the message "Storage is temporarily not available" appears in the top right and in the logs it says:

>    [webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable:  at <<closure>>
>
>    0. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 76
>        OCA\DAV\Connector\Sabre\Directory->getChild("Test Share")
>    1. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 967
>        Sabre\DAV\Tree->getNodeForPath("files/mcnesium/Test Share")
>    2. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 1666
>        Sabre\DAV\Server->getPropertiesIteratorForPath("files/mcnesium/Test Share", ["{DAV:}getlastm ... "], 1)
>    3. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 355
>        Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
>    4. <<closure>>
>        Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
>    5. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
>        undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPropFind"], [Sabre\HTTP\Requ ... }])
>    6. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
>        Sabre\Event\EventEmitter->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
>    7. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
>        Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
>    8. /var/www/html/apps/dav/lib/Server.php line 317
>        Sabre\DAV\Server->exec()
>    9. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
>        OCA\DAV\Server->exec()
>    10. /var/www/html/remote.php line 163
>        undefinedundefinedrequire_once("/var/www/html/a ... p")
>
>    PROPFIND /remote.php/dav/files/mcnesium/Example%20Share
>    from 192.168.0.1 by mcnesium at 2020-01-02T17:55:43+00:00

Because in the first error message it says "POST **http://** cloud.remoteinstance.de" I would like to emphasize that both involved instances are properly set to use HTTPS with a valid Letsencrypt certificate.

<details><summary>Server configuration detail</summary>

**Operating system:** Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u1 (2019-09-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.4.10

**PHP version:** 

7.3.11
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 17.0.1 - 17.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Docker nextcloud:latest

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - calendar: 1.7.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.6
 - dav: 1.13.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - gallery: 18.4.0
 - impersonate: 1.4.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - maps: 0.1.2
 - nextcloud_announcements: 1.6.0
 - notes: 3.1.0
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - polls: 0.10.4
 - previewgenerator: 2.2.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - sharerenamer: 2.7.3
 - spreed: 7.0.2
 - support: 1.0.1
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.1
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - cospend
 - encryption
 - files_external
 - firstrunwizard
 - metadata
 - news
 - social
 - survey_client
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.localinstance.de"
    ],
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "17.0.1.1",
    "overwrite.cli.url": "https:\/\/cloud.localinstance.de\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "filesystem_check_changes": 1,
    "theme": "localinstance",
    "loglevel": 2,
    "overwriteprotocol": "https",
    "app_install_overwrite": [
        "calendar",
        "polls",
        "spreed"
    ]
}
```
</details>

<details><summary>Client configuration</summary>

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0

**Operating system:** 

</details>

**Comment by supremesyntax** [comment]
same here
i have received a remote share and accepted it. 
now the folder is in the list but i can't open it - it says "Storage is temporarily not available"

log says:

`{"reqId":"oknZkX4OPRUiM2KScsEc","level":4,"time":"2020-04-09T12:58:43+02:00","remoteAddr":"10.0.0.1","user":"user","app":"webdav","method":"PROPFIND","url":"/remote.php/dav/files/user/folder","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["folder"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":967,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files/user/folder"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1666,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->","args":["files/user/folder",["{DAV:}getlastmodified","{DAV:}getetag","{DAV:}getcontenttype","{DAV:}resourcetype","{http://owncloud.org/ns}fileid","{http://owncloud.org/ns}permissions","{http://owncloud.org/ns}size","{DAV:}getcontentlength","{http://nextcloud.org/ns}has-preview","{http://nextcloud.org/ns}mount-type","{http://nextcloud.org/ns}is-encrypted","{http://open-collaboration-services.org/ns}share-permissions","{http://owncloud.org/ns}tags","{http://owncloud.org/ns}favorite","{http://owncloud.org/ns}comments-unread","{http://owncloud.org/ns}owner-id","{http://owncloud.org/ns}owner-display-name","{http://owncloud.org/ns}share-types"],1]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":355,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->","args":[{"__class__":"Generator"},false]},{"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPropFind"],[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PROPFIND",[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":225,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.3.0","id":"5e8f00065b9fb"}`

i even can't even get rid of it, if i want to Unshare i receive "Error deleting file 'xyz'"

log says: 

`{"reqId":"0G4b0ete4GSEPErHdUDe","level":4,"time":"2020-04-09T12:47:27+02:00","remoteAddr":"10.0.0.1","user":"username","app":"webdav","method":"DELETE","url":"/remote.php/dav/files/user/folder","message":{"Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Message":"","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":76,"function":"getChild","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["folder"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":178,"function":"getNodeForPath","class":"Sabre\\DAV\\Tree","type":"->","args":["files/user/folder"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":287,"function":"delete","class":"Sabre\\DAV\\Tree","type":"->","args":["files/user/folder"]},{"function":"httpDelete","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpDelete"],[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:DELETE",[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.example.com/remote.php/dav/files/user/folder","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/remote.php","line":165,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","Line":225,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"18.0.3.0","id":"5e8efd50b78dd"}`

**Comment by nook24** [comment]
Nextcloud 20.0.4, External Storage 1.11.1. I can connect and use my Seafile via WebDAV but my log is full of undefined index errors:
```
[PHP] Error: Error: Undefined index: {DAV:}getlastmodified at /usr/share/nextcloud/lib/private/Files/Storage/DAV.php#593 at <<closure>>

 0. /usr/share/nextcloud/lib/private/Files/Storage/DAV.php line 593
    OC\Log\ErrorHandler::onError(8, "Undefined index: {DAV:}getlastmodified", "/usr/share/next ... p", 593, {path: "",respon ... }})
 1. /usr/share/nextcloud/lib/private/Files/Storage/Common.php line 458
    OC\Files\Storage\DAV->stat("")
 2. /usr/share/nextcloud/apps/files_external/lib/MountConfig.php line 264
    OC\Files\Storage\Common->test("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 3. /usr/share/nextcloud/apps/files_external/lib/Controller/StoragesController.php line 258
    OCA\Files_External\MountConfig::getBackendStatus("*** sensitive parameters replaced ***")
 4. /usr/share/nextcloud/apps/files_external/lib/Controller/GlobalStoragesController.php line 180
    OCA\Files_External\Controller\StoragesController->updateStorageStatus("*** sensitive parameters replaced ***")
 5. /usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Files_External\Controller\GlobalStoragesController->update("*** sensitive parameters replaced ***")
 6. /usr/share/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Extern ... {}, "update")
 7. /usr/share/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Extern ... {}, "update")
 8. /usr/share/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Files_Exte ... r", "update", OC\AppFramework\ ... {}, {action: null,id ... "})
 9. /usr/share/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/files_external/globalstorages/3")
10. /usr/share/nextcloud/index.php line 37
    OC::handleRequest()

PUT /index.php/apps/files_external/globalstorages/3
from 178.203.48.42 by nook24 at 2020-12-28T12:10:45+00:00

```

**Comment by uma201** [comment]
Concerning the 405 Method Not Allowed error, I would check the firewall configuration of the systems (see also https://help.nextcloud.com/t/nextcloud-on-plesk-obsidian-error-put-405-method-not-allowed/91502)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by supremesyntax** [comment]
In my case there was some config setting missing on the other side. Something about docker containers so case solved for me.

**Comment by szaimen** [comment]
great! closing :)
