### ISSUE TITLE
files:scan "stuck" on external folders

### ISSUE THREAD

**Issue by jbiason** [nextcloud/server#18638]
### Steps to reproduce
1. Attach external resource -- specifically, an S3 compatible resource (Digital Ocean Spaces)
2. Run `occ files:scan <user> -vv`
3.

### Expected behaviour
It should scan the external filesystem and update the file list; because `-vv` is specified, found folders (and maybe files) should appear.

### Actual behaviour
My current scan is stuck showing `Folder /user/files/External/` (and only that) for about 2 hours.

### Server configuration

**Operating system:** Ubuntu 18.04 (LTS) x64 (oficial Digital Ocean droplet)

**Web server:** Apache 2.4, part of the NextCloud snap.

**Database:** MySQL 5.7, again packaged with snap.

**PHP version:** PHP 7.2

**Nextcloud version:** (see Nextcloud admin page) Nextcloud 16.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** Snap updated, previous version was still 16.0.x.

**Where did you install Nextcloud from:** snap files.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.2.0
  - activity: 2.9.1
  - calendar: 1.7.1
  - cloud_federation_api: 0.2.0
  - dav: 1.9.2
  - deck: 0.6.6
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_external: 1.7.0
  - files_pdfviewer: 1.5.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - tasks: 0.11.3
  - twofactor_backupcodes: 1.5.0
  - viewer: 1.1.0
  - workflowengine: 1.6.0
Disabled:
  - admin_audit
  - comments
  - cospend
  - encryption
  - files_rightclick
  - gallery
  - keeporsweep
  - social
  - theming
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "cloud.juliobiason.me"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.5.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2,
        "overwritehost": "cloud.juliobiason.me"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... In this case, S3 (problem doesn't appear to affect non-S3 scans)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

### Client configuration
**Browser:** Firefox 71.0

**Operating system:** Ubuntu

### Logs

Is there any specific to the command line operations?

**Comment by kesselb** [comment]
> Is there any specific to the command line operations?

`nextcloud.log`

https://github.com/nextcloud/nextcloud-snap#where-is-my-stuff

**Comment by jbiason** [comment]
Just to explain better the problem: After running `occ files:scan <user> -vv`, I get:

[...]
```
        File    /jbiason/files/Joplin/.resource/5880756371c74e018107ba133dde1d24
        File    /jbiason/files/Joplin/.resource/421260e4710846d19cf33c7e794c226d
        File    /jbiason/files/Joplin/.resource/a5fef2e6c60544349935b4aa4dbc480f
        File    /jbiason/files/Joplin/.resource/80584dbed0064366a15a682ad8aa2083
        Folder  /jbiason/cache
        Folder  /jbiason/files/External/
        Folder  /jbiason/files/External/
        Folder  /jbiason/files/External/
        Folder  /jbiason/files/External/
```
[...]

That last line keeps repeating over and over.

I removed the `nextcloud.log` before running the command line, and during the scan, the file still appears with 0 bytes.

**Comment by jbiason** [comment]
Also, I'm almost sure it's just a display problem, not a processing problem.

**Comment by jbiason** [comment]
After two hours, I got this in the log: https://gist.github.com/jbiason/1e0f5c23eb097706654e540706d63f91

**Comment by jbiason** [comment]
Ok, kinda found the problem:

There was a file named `/` on the S3 and that would throw NextCloud into an eternal loop.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
