### ISSUE TITLE
Copying share link not possible on iOS

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1863]
- marking and copying long text from inside the disabled input field is not really possible
- using the »copy to clipboard« function is not supported on iOS

Since iOS devices are pretty common, we need to fix this.
- An idea could be to use text instead of a disabled input field. We have to check if it reliably works on other platforms when ellipsized etc.
- Making the input not-disabled could also be an option, but the potential for accidentally modifying the link then is a bit too high.
- Other ideas?

cc @nextcloud/designers @nextcloud/mac

**Comment by Espina2** [comment]
> using the »copy to clipboard« function is not supported on iOS

Not only the copy to clipboard doesnt work. It have another bug when you try to select the content of the form to.

**Comment by iangrey** [comment]
> using the »copy to clipboard« function is not supported on iOS

I've seen several apps do this. Has Apple introduced new restrictions here?

**Comment by MorrisJobke** [comment]
> using the »copy to clipboard« function is not supported on iOS

Tested and works here fine with 12.

**Comment by MorrisJobke** [comment]
I copied the "Share by link" link.
