### ISSUE TITLE
A non-numeric value encountered at apps/files_versions/lib/Storage.php#533

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#18636]
During normal usage I got some errors in nextcloud.log, all stating `A non-numeric value encountered at apps/files_versions/lib/Storage.php#533`. The error log wasn't really helpful but I made further investigations and could reproduce it in a fresh install. The issue appears if there is a file and a directory with the same basename but the directory with any extension. 

### Steps to reproduce
1. Create a file `A` and a directory `A.ext`
2. Create another file `B` in the previously created directory `A.ext`
3. Modify file `B`. files_versions app should create a second version of this file.
4. Show versions of file `A`

### Expected behaviour
Nextcloud
- should not list a version of file `A` as it does with other files if there is only one version
- should not show 'invalid date'

### Actual behaviour
- The files_versions app lists a version of file `A` with invalid date
- Errors in the nextcloud.log

[files_versions/lib/Storage.php#464](https://github.com/nextcloud/server/blob/dbbe68745621cc193bf37d510b6ed3f5e11c4373/apps/files_versions/lib/Storage.php#L464)
The `getVersions($uid, $filename, $userFullPath = '')` function in `Storage.php`
- does not ignore directories
- does not check the first character of the extension
- does not check if `$timestamp` is a numeric value.

### System, Configuration and Client Details as of the Issue Template
<details>

### Server configuration
**Operating system:** Debian GNU/Linux 10 (buster) / Docker 19.03.5
**Web server:** nginx/1.17.4
**Database:** postgresql/12.1
**PHP version:** php/7.3.10
**Nextcloud version:** 17.0.2
**Updated from an older Nextcloud or fresh install:** fesh install
**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - checksum: 0.4.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - gallery: 18.4.0
  - impersonate: 1.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - metadata: 0.10.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - ransomware_protection: 1.5.1
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - nextcloud_announcements
  - recommendations
  - support
  - survey_client
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "1",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "updater.release.channel": "stable",
        "default_language": "de",
        "theme": "",
        "versions_retention_obligation": "auto"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Chrome Version 79.0.3945.88 (Official Build) (64-bit)
**Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"7lzbzwZIwJk9pXbtH0DZ","level":3,"time":"2020-01-02T13:36:33+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"holzkopf","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/versions\/holzkopf\/versions\/221385","message":"A non-numeric value encountered at \/var\/www\/nextcloud\/apps\/files_versions\/lib\/Storage.php#533","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.88 Safari\/537.36","version":"17.0.2.1"}

```
</details>
</details>

**Comment by apiraino** [comment]
Confirming this warning also in other two places of Storage.php (as of NC 17.0.2.1)
apps/files_versions/lib/Storage.php +652
apps/files_versions/lib/Storage.php +672

**Comment by kesselb** [comment]
Thanks 👍 Mind to send a pull request? :)

**Comment by GregorB54321** [comment]
Same as with Nextcloud 18.0.9:
Error	PHP	A non-numeric value encountered at /var/www/html/apps/files_versions/lib/Storage.php#679	
Error	PHP	A non-numeric value encountered at /var/www/html/apps/files_versions/lib/Storage.php#659	
Error	PHP	A non-numeric value encountered at /var/www/html/apps/files_versions/lib/Storage.php#535

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by apiraino** [comment]
for what's it's worth, I don't see this in the logs anymore

**Comment by szaimen** [comment]
Thanks for the feedback! Lets track this in https://github.com/nextcloud/server/issues/27133 either way!
