### ISSUE TITLE
[18beta4] [Others with access] bad UX on empty list

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18632]
When there are no _Others with access_, there's quite little feedback about that fact when you invoke the listing action.

![others](https://user-images.githubusercontent.com/1804221/71667465-78ceff80-2d65-11ea-871f-2effa81af54e.gif)

**Comment by rullzer** [comment]
So shall we just do a small note 'no other users with access found' ?

**Comment by wiswedel** [comment]
> So shall we just do a small note 'no other users with access found' ?

That'd be perfect
