### ISSUE TITLE
Server Open local file for edit

### ISSUE THREAD

**Issue by Andreas-Kainz** [nextcloud/server#18643]
The online interface is great with stared, favorites, labels, ... compare to the webdav or sync client where you see only the file structure, the web is way better. Sure you can bookmark the files at your is and add labels but this is twice the work.

So why not focus on the web UI. The only issue is, that if you open an file online and you download the file and can edit it in the download folder, but than there is no synchronization.

So my question is, when you click an file in the web UI, can it open the local webdav or sync client file, which you can edit and sync work.

This is how agorum dms solve the issue https://mein-dms.agorum.com/blog/agorum-core-im-alltag-dokumente-ohne-umwege-bearbeiten

I also open an issue at the client repository cause it's an issue between server and client, I think.
https://github.com/nextcloud/desktop/issues/1705#issue-543862443

**Comment by szaimen** [comment]
Unfortunately the described feature is not really high on our priority list. But this doesn't mean that we don't like the idea or that we are against this feature per se. Quite the opposite! 🙂
There are many way to get new features in Nextcloud:
1. The easiest and most straight forward way (especially here at Github): pull request.
Nextcloud is completely Free Software, this means that everyone is welcome to join and to contribute. If you or anyone else want to work on this feature, this would be great! We appreciate every pull request, and we are definitely able to help in case of questions, reviews, etc.
2. We have a category for Freelancers in our form. Another option would be to post an offer there and try to find a freelancer who want to work on it.
3. The most direct way for a company or organization to get the issue addressed is to get a Enterprise Subscription. This includes everything to enable you to run Nextcloud in a productive environment with guaranteed SLA's and more. The Enterprise Subscription also includes optional professional services such as custom development. Feel free to reach out to us. We are happy to explore the possibilities how to make Nextcloud fit your needs.
