### ISSUE TITLE
How to execute a RAND() / random() SELECT ? (mariadb vs postgres)

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#18640]
Hello NC Masters,

I need to select a random number of records from a table (random tracks in audioplayer)
`...ORDER BY RAND() Limit 50`

RAND() = mariadb
random() = postgres

Is there a way to do this backend-specific? I could not find any reference/example if Querybuilder is capable.

thank you

**Comment by kesselb** [comment]
https://stackoverflow.com/questions/10762538/how-to-select-randomly-with-doctrine :disappointed:

**Comment by kesselb** [comment]
cc @nextcloud/server-triage

**Comment by nickvergessen** [comment]
Querybuilder has a createFunction method. Use this to run RAND().
If you need different ones, get the plattform from the database connection and add a switch, which method to execute

**Comment by nickvergessen** [comment]
See the old way of doing things in
https://github.com/Rello/audioplayer/commit/11f0f05e8ad71fab08424aab34268798e920b9e8

New code would use
```php
            if ($this->db->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSqlPlatform) {
                $query->orderBy($query->createFunction('random()'));
            } else {
                $query->orderBy($query->createFunction('RAND()'));
            }
```

**Comment by Rello** [comment]
Thanks Joas!
...will migrate to „new code“ soon
