### ISSUE TITLE
File replacement modal too wide on mobile

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1864]
Uploading multiple images with iPhone in Files is not possible because the confirmation dialog for overwriting files cannot be used as expected. There's not enough room for seeing the full dialog box.

![b767b0c2-94de-11e4-897e-195eba833027](https://cloud.githubusercontent.com/assets/925062/19626627/3ff4cc74-9936-11e6-92ca-df494d22c1d6.PNG)

cc @nextcloud/designers @nextcloud/mac

**Comment by MorrisJobke** [comment]
Fix is in #2342

**Comment by MorrisJobke** [comment]
Fixed with #2342
