### ISSUE TITLE
Convert sample video to a format which plays in the top browsers

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#1865]
The top browser today with 50% market share is Chrome and the sample video doesn't play, so it should be converted to play.

@jospoortvliet @jancborchardt

**Comment by nickvergessen** [comment]
I think @karlitschek did all the sample files

**Comment by karlitschek** [comment]
yes. i did it. I thougt that everyone can play H264. Works fine on Chrome on MacOS. @oparoz Can you check what exactly the problem is?

**Comment by MariusBluem** [comment]
Do you use Flash with Chrome on macOS? @karlitschek 

Ref: http://www.zdnet.de/41544877/google-chrome-stellt-support-fuer-video-codec-h-264-ein/

**Comment by MariusBluem** [comment]
http://caniuse.com/#feat=mpeg4

**Comment by karlitschek** [comment]
It is not using flash. It's native here. mpeg4 is only the container. The codec is also critical. It would be good if someone on linux, or wherever the current video doesn't work, would recode it so that it works. I can't test it because it works fine on Safari, Firefox and Chrome here.

**Comment by oparoz** [comment]
OK, my bad, Chromium doesn't support h.264, but Chrome does.

**Comment by MariusBluem** [comment]
Always these chromium users 🙄😜 ... Question: Is missing h.264 support in chromium a reason for using another format, since chromium is also an browser sometimes used in linux distributions 😁
