### ISSUE TITLE
Cant upload files 

### ISSUE THREAD

**Issue by orlovnv** [nextcloud/server#18656]
### Steps to reproduce
1.upload file via web any size got error not enough free space
2.upload via mobile app less 1mb all is ok, more 2mb cant upload error not enough rights
3.

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Nginx
**Database:**
Mysql 
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
Nginx log:
access forbidden by rule, client: , server: , request: "MOVE /remote.php/dav/uploads/user/2a7c27a6a902caed253c4d8d3f9df87d/.file HTTP/1.1", host:

**Comment by kesselb** [comment]
Thanks for taking the time to report a issue :+1: 

Please check: https://github.com/nextcloud/documentation/pull/1748/files / https://github.com/nextcloud/server/issues/8802

**Comment by orlovnv** [comment]
> Thanks for taking the time to report a issue 
> 
> Please check: https://github.com/nextcloud/documentation/pull/1748/files / #8802

This doesn't work
