### ISSUE TITLE
Show a (bell?) icon in the calendar entry if it has reminder(s) set.

### ISSUE THREAD

**Issue by netphantm** [nextcloud/server#18652]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Show a (bell?) icon in the calendar entry if it has reminder(s) set.

**Describe alternatives you've considered**
maybe also differentiate entries if they are recurring from the ones that are not

**Comment by bpcurse** [comment]
Is this the feature you are requesting? Seems it will be implemented soon.

https://github.com/nextcloud/calendar/pull/1755

**Comment by netphantm** [comment]
Yep, looks cool ;)
Perhaps even an icon for recurring events (some kind of recycling arrows) or another way to differentiate from the non-recurring ones? But this one is more important I think, so you see immediately if you or the creator of the event did set a reminder.
