### ISSUE TITLE
Cannot direct to any page after admin login

### ISSUE THREAD

**Issue by shresthasuruchi** [nextcloud/server#18650]
Hello!
I recently installed nextcloud in one of my servers, and there was no error during the whole installation process.
I configured apache, database and php.
After the full configuration and installation, to test the working of ncloud, I was successfully loaded to a page that asks us to create an admin account, and connect to the database. After I fill in the details and click on Finish button, I am directed to an error page in all the browsers that I use, stating that the connection was reset (in firefox), server dropped the connection (safari) , domain did not send any data (chrome). 
I have almost installed and done everything I possibly could think of so many times, but I keep getting the same errors.
Can anyone suggest me what can be done? Please help me out!! 

### Steps to reproduce
1. Install LAMP Server
2. Install ncloud
(for reference I used: https://websiteforstudents.com/install-nextcloud-server-using-composer-on-ubuntu-16-04-18-04-with-apache2-mariadb-and-php-7-2-support/)

### Expected behaviour
After replicating this process, you should be able to see the first setup page, and after filling in the details you should be directed to the admin ncloud account.

### Actual behaviour
After replicating this process, I was able to see the first setup page, but after providing the details, and when I clicked on the finish option, I was not displayed with anything, all browsers seemed to show an error.

### Server configuration

**Operating system:** Ubuntu 16.04 LTS

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 13

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://github.com/nextcloud/server.git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by gary-kim** [comment]
Sorry, just to be clear, did you install Nextcloud 13? 13 was EOL almost a year ago.

Also, if you're trying to install a stable version, take a look at the downloads at <https://nextcloud.com/install/#instructions-server>. The git repo is for development and the release script is, unfortunately, not public so you cannot make the production use version yourself.
