### ISSUE TITLE
Custom color in theming hides login image in NC18

### ISSUE THREAD

**Issue by marius-wieschollek** [nextcloud/server#18661]
### Steps to reproduce
1. Install Nextcloud 18.0.0 RC1 (Fresh install or upgrade)
2. Open the admin settings and go to "Theming"
3. (optional) Upload a "Login image"
4. Change the "Color" in the Theming settings
5. Look at the theme preview or login page

### Expected behaviour
Color is changed and the background image is visible.

### Actual behaviour
Only a color gradient is shown in the preview and the login page.
In the header of the first run wizard, the login image is now shown. (It was not visible there before)

![ezgif-7-f4886efb6f99](https://user-images.githubusercontent.com/8255857/71772851-ee4bf300-2f52-11ea-806c-03dba0770fb1.gif)

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.3.13

**Nextcloud version:** 18.0.0 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** releases page on Github (also happens with official docker image nextcloud:18-beta-fpm)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - passwords: 2020.1.0-BUILD
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 1.2.3
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "1025",
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "passwords.local"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.8",
        "overwrite.cli.url": "https:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "defaultapp": "passwords",
        "theme": "",
        "maintenance": false,
        "updater.release.channel": "beta"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 71

**Operating system:** Ubuntu 18.04

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No errors
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
no errors
```
</details>

**Comment by jancborchardt** [comment]
Yes, this is known as per the comment at https://github.com/nextcloud/server/pull/18082#issuecomment-558193138 and the following ones.

What we would need is that the background SVG also gets generated based on the primary color. The current background SVG uses the primary color at a certain opacity, so that it "vanishes" in the bottom left where the primary color is used, but shows the icons in the center and especially top left, where it fades into the lighter color. :)

**Comment by marius-wieschollek** [comment]
With the `$has-custom-background` variable from #18660 it could be possible to remove the image only when the color is changed and not custom background is used.

**Comment by jancborchardt** [comment]
Ah right, I get it now! :) Yes, it should be like you describe – could you submit a pull request?

**Comment by marius-wieschollek** [comment]
There is now PR #18726 to solve this issue.
