### ISSUE TITLE
Files cant upload

### ISSUE THREAD

**Issue by orlovnv** [nextcloud/server#18671]
https://github.com/nextcloud/server/issues/18656#issue-545293724
Write one more time, please dont close until problem will be solved

**Comment by kesselb** [comment]
Please have a look at our [contribution guidelines](https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md). 

> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

That's the first sentence of the issue template. We are not able to sort out your configuration problems. If your webserver is blocking those requests there is nothing we can do.
