### ISSUE TITLE
file initegrity issue after upgrade 16.0.6 -> 16.0.7

### ISSUE THREAD

**Issue by dt64** [nextcloud/server#18676]
After upgrading Nextcloud from 16.0.6 to 16.0.7 the automatied inbiuld checks reported some file integrity issue:

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => 008148d723136644c2542312557ed5b9db1af5de6797a221d221012ae0ad367b2daca4774bcaba8936ec8394093b83c3e3f2d8e7c52e5f5882e28579dffe99e2
                        )

                )

        )

)

**Comment by kesselb** [comment]
Please use the issue template to report a bug. I checked the latest release for the `files_rightclick` app contains a signature for README.md. Probably updating the app will fix the warning.

**Comment by dt64** [comment]
updating rightclick app solved it.
thanks & closed.
