### ISSUE TITLE
wrong behavior on "exclude groups from sharing"

### ISSUE THREAD

**Issue by BergBenji** [nextcloud/server#1867]
Hello, i found a bug. (In my opinion it is)

Share within "Exclude groups from sharing" works if another group is defined.

### Steps to reproduce
1. Create 3 ore more Users.

1.1 User 1: Group EMAIL, CONTACTS

1.2 User 2: Group: MyCompany, CONTACTS

1.3 User 3: Group Test3, MyCompany

2. Set in Adminarea "Exclude groups from sharing" for Group EMAIL and CONTACTS

### Expected behaviour
In my opinion the user 2 should only be possible to share folders/files with the Group "MyCompany"

### Actual behaviour
User 2 can share folders/files with users in Group "CONTACTS and MyCompany"

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP 7.0.8

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** nextcloud.com

**Comment by nickvergessen** [comment]
Did you read the little description below the input box?
> These groups will still be able to receive shares, but not to initiate them.
