### ISSUE TITLE
external storage: long and bright animation when Nextcloud loads.

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#18685]
### Steps to reproduce
1. install external storage app and connect a smb share or local cifs-share
2. make a folder available for a nextcloud user
3. when accessing Nextlcoud, there is a really bright and slow animation. maybe this could get removed?

![20200106_004247](https://user-images.githubusercontent.com/42591237/71787948-ee64f500-301d-11ea-95a9-ffeef146e1e3.gif)

### Expected behaviour
Don't show this bright animation when accessing Nextcloud; just show the folders.

### Actual behaviour
a really bright and slow animation

I am running on 17.0.2 and this happens on all devices and all browsers.

maybe this could also be something for polishing 18 or 19?

**Comment by szaimen** [comment]
@jancborchardt any thoughts on this?

**Comment by szaimen** [comment]
Could anyone point me to the code that is responsible for this?

**Comment by jancborchardt** [comment]
cc @skjnldsv for grid view – does this maybe have anything to do with the dark theme as well?

@szaimen could you confirm that it works fine with the dark theme disabled?

**Comment by skjnldsv** [comment]
No clue to be honest. :(

**Comment by szaimen** [comment]
@jancborchardt I think this has nothing to do with the dark theme because I get this animation always on every browser on every OS and also if the dark theme is disabled. I think it has to do with the usage of the external storage app: each time when I access my Nextcloud via the web interface I get this animation (also if I reload the site but only in the files app's root directory). 
Maybe icewind1991 could help us here in finding out what is causing this animation?

**Comment by skjnldsv** [comment]
@szaimen it only happens when you have external storage enabled?

**Comment by szaimen** [comment]
@skjnldsv It happens actually only for external storage mounts. You can see the difference here in this video:
[Screen_Recording_20200401-125817_1.zip](https://github.com/nextcloud/server/files/4414639/Screen_Recording_20200401-125817_1.zip)

**Comment by jancborchardt** [comment]
cc @icewind1991 any idea?

**Comment by szaimen** [comment]
Ping

**Comment by PVince81** [comment]
there is a JS checker that will find whether those external storages are available or not and while it does so they get highlighted

this is for the cases where a user's password might be needed in case the storage is not accessible any more (for example if a password was invalidated/changed on the SMB/AD side)

the code in question seems to be here: https://github.com/nextcloud/server/blob/v22.2.0/apps/files_external/js/statusmanager.js#L240

I don't think it's very useful to have the folder row flash like this, at least not for the user.
However, from what I remember, while the check is happening the user is not supposed to be able to click on that element, so maybe making it look disabled it would be better.

Or even better: if the user does interact, we'd need to know that the entry is not ready yet and would need to wait on a Promise. But doing the latter is much more involved and complicated and might be obsolete when moving the file list to Vue.

So probably a more subtle styling approach would do.

@szaimen mystery solved ?

**Comment by szaimen** [comment]
@PVince81 Yes, sounds like this is happening here! Thanks for shedding some light on this!
So where can I adjust the styling? :)

**Comment by szaimen** [comment]
Looks like probably here? https://github.com/nextcloud/server/blob/9de329a4c2327767d86bd7f594b232eb56af0d01/apps/files_external/css/external.css#L2

**Comment by PVince81** [comment]
@szaimen yes. also IIRC if the storage is not available the row will be highlighted red, then if the user clicks it they get prompted for a password, if applicable

**Comment by szaimen** [comment]
I'd vote for using var(--color-main-background) which looks much better to me :)

**Comment by szaimen** [comment]
Fix is at #29679
