### ISSUE TITLE
[mobile layout] problem with "cannot upload a file here" and icon in the top right corner

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#18683]
I am currently on Nextcloud 17.0.2 this happens on all mobile phones with different browsers.
The text that I cannot upload files here doesn't fit to the button in the top right corner: So it doesn't seem to be right this way:
![photo5228725884192665138](https://user-images.githubusercontent.com/42591237/71787698-6c73cc80-301b-11ea-9f9c-217bc0b83ad4.jpg)
![photo5231126942709820817](https://user-images.githubusercontent.com/42591237/71787699-6ed62680-301b-11ea-9553-6a6e0fcbffba.jpg)
Could this be some polishing for 18 or 19?

**Comment by wiswedel** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Instead of showing the text directly, which is a bit in-your-face, we should:
- Show the upload icon, but greyed out
- On tap, show a popover with the text

cc @nextcloud/designers

**Comment by szaimen** [comment]
for the reference: you can the find the message line here:
https://github.com/nextcloud/server/blob/a688f47a2f31ce59c40118f93503d19d268c3802/apps/files/templates/list.php#L8

**Comment by szaimen** [comment]
And I suppose this is the part where it gets hidden or shown:
https://github.com/nextcloud/server/blob/a688f47a2f31ce59c40118f93503d19d268c3802/apps/files/js/filelist.js#L2268-L2289
