### ISSUE TITLE
Improve integrated video capabilities

### ISSUE THREAD

**Issue by guitargurus** [nextcloud/server#1868]
### Steps to reproduce
1.  Select an .avi video file stored on nextcloud
2.  Attempt to play selected .avi video file

### Expected behaviour

.avi, as well as other popular formats such as .mov and .mpeg, should open in a window and play in the same way .mp4 video files play in Nextcloud.

### Actual behaviour

.avi (and .mov) video files do not play.  A download will start when selected, instead of playing in a video window.

### Comments:

It looks like video-js is used.  Adding the readily available videojs-java would enable playback of .avi, .mov, .mpg, and many other useful and commonly used formats.  videojs-vlc would be another excellent option that could be optionally enabled on the admin page (I understand not everyone has the vlc browser plugin installed, but it plays literally everything).  This feature would complete the video playback functionality.  Many people use iPhones, which record in .mov, and many of my Android devices record in .avi format.  As of now, Nextcloud is unable to play either and the video playback feature is pretty much useless for myself and others I know using Nextcloud.  There are countless reasons and benefits to support more commonly used formats.

[link to videojs-java plugin on github](https://github.com/Afterster/videojs-java)

[link to videojs-vlc plugin on github](https://github.com/Afterster/videojs-vlc)

# **Thank you for your hard work!!!!!**

**Comment by nickvergessen** [comment]
Feel free to create a PR in https://github.com/nextcloud/files_videoplayer

If you don't want to, please reopen your issue in that repository
