### ISSUE TITLE
NC18rc1 - InvalidArgumentException: The given object id is invalid

### ISSUE THREAD

**Issue by jookk** [nextcloud/server#18688]
Nc18RC1
Debian 10
PHP7.4-FPM
nginx 1.17.7

/var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php - line 103: OC\Notification\Notification->setObject()
/var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php - line 148: OCA\DAV\CalDAV\Reminder\NotificationProvider\PushProvider->send()
/var/www/nextcloud/apps/dav/lib/BackgroundJob/EventReminderJob.php - line 68: OCA\DAV\CalDAV\Reminder\ReminderService->processReminders()
/var/www/nextcloud/lib/private/BackgroundJob/Job.php - line 61: OCA\DAV\BackgroundJob\EventReminderJob->run()
/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php - line 55: OC\BackgroundJob\Job->execute()
/var/www/nextcloud/cron.php - line 125: OC\BackgroundJob\TimedJob->execute()
-- | --

**Comment by kesselb** [comment]
Hello @georgehrke @tcitworld

**Comment by tcitworld** [comment]
It seems the vevent would have no UID but that should have been caught before.

**Comment by georgehrke** [comment]
@jookk Can you please check the database row `oc_calendarobjects` if there are any rows with an UID set to null?

**Comment by jookk** [comment]
Thanks, there isnt any uid with 0.
Im using calendar beta3 - btw.

Dňa 6. januára 2020 21:58:21 používateľ Georg Ehrke 
<notifications@github.com> napísal:

**Comment by tcitworld** [comment]
`0` is not the same as `null`.

`SELECT * from oc_calendarobjects WHERE uid IS NULL`

**Comment by kesselb** [comment]
Just found this other report https://github.com/nextcloud/server/issues/17758. Error seems to be the same but the object_id is a long string and not null. Also https://github.com/nextcloud/server/issues/18789 reports that. 

I'm sorry for not requesting the issue template in the first place. Having the complete exception is important.

**Comment by Happyfeet01** [comment]
I have also this issue..

`[core] Error: InvalidArgumentException: The given object id is invalid at <<closure>>

0. /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/NotificationProvider/PushProvider.php line 103
   OC\Notification\Notification->setObject("dav", "040000008200E00 ... 9")
1. /var/www/nextcloud/apps/dav/lib/CalDAV/Reminder/ReminderService.php line 148
   OCA\DAV\CalDAV\Reminder\NotificationProvider\PushProvider->send(Sabre\VObject\Co ... }}, "Müll", [OC\User\User {}])
2. /var/www/nextcloud/apps/dav/lib/BackgroundJob/EventReminderJob.php line 68
   OCA\DAV\CalDAV\Reminder\ReminderService->processReminders()
3. /var/www/nextcloud/lib/private/BackgroundJob/Job.php line 61
   OCA\DAV\BackgroundJob\EventReminderJob->run(null)
4. /var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php line 55
   OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
5. /var/www/nextcloud/cron.php line 125
   OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-01-27T20:15:05+00:00 `

**Comment by Happyfeet01** [comment]
The error still exist on Nextcloud 18.0.1.

Every Cron this error.

**Comment by tcitworld** [comment]
Fix will be in 18.0.2

**Comment by tcitworld** [comment]
Fixed by #19252
