### ISSUE TITLE
Psql installation always attempts to connect to database named 'template1'

### ISSUE THREAD

**Issue by lepinkainen** [nextcloud/server#1869]
### Steps to reproduce
1. psql database without admin access
2. Start installation, give database name
3. nextcloud attempts to install itself to database named "template1" instead of the one given in the wizard
### Expected behaviour

Install where I tell it to go
### Actual behaviour

Install attempts to connect to 'template1', which fails.

'template1' is hardcoded in `3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php`

In master this seems to have been changed to 'postgres', which is still not the one the user specifies: https://github.com/nextcloud/3rdparty/blob/master/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php#L95

Install worked fine when I manually changed template1 to my provided database name.

**Comment by nickvergessen** [comment]
Well but we shouldn't end up in that path, when a db name was given.
We only end up there, when the db name was not set:
https://github.com/nextcloud/3rdparty/blob/master/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOPgSql/Driver.php#L89-L90

So we should have a look, why it was not set in first place.

**Comment by jaapio** [comment]
What is the is the status of this issue?

**Comment by nickvergessen** [comment]
Should be fixed since https://github.com/nextcloud/server/pull/497
So in 11.

Can you test?

**Comment by benediktg** [comment]
I have now a new Nextcloud 11.0.1 instance running with nginx and postgresql and it works, but I did create the database by hand:
```sql
create user nextcloud with password '...';
create database nextcloud;
grant all privileges on database nextcloud to nextcloud;
```
It runs pretty fine now.
