### ISSUE TITLE
super-huge 2FA submit button

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18691]
The submit button on the 2FA login screen is unusual super huge in _Nextcloud 18.0.0 RC1 Build:2020-01-05T22:01:57+00:00

![image](https://user-images.githubusercontent.com/1804221/71820090-594e1480-308e-11ea-86e6-c63449bce0d7.png)

Is that intended?

cc @nextcloud/designers

**Comment by rullzer** [comment]
Seems somewhere somebody messes with some css ;)

On the plus side. Now it is easy to spot the button.

@juliushaertl @skjnldsv @ChristophWurst

**Comment by wiswedel** [comment]
> On the plus side. Now it is easy to spot the button.

So it's actually a pro-accessibility feature, huh? 😜

**Comment by jancborchardt** [comment]
This is fixed through https://github.com/nextcloud/server/pull/18898 :)
