### ISSUE TITLE
Help request with clean up after deadlock while moving files - duplicates

### ISSUE THREAD

**Issue by Rychu-Pawel** [nextcloud/server#18697]
I need help solving one case with my instance. I was moving few mistakenly placed folders from `Camera\2019` named `2013`, `2014`, `2015`, `2016`, `2017`, `2018`. During this operation something went wrong and folders `2013`, `2016` and `2018` are visible in both target and source directory. I found in the logs it was a deadlock but unfortunatly I can't get the exact error message as my log is flooded with exceptions from the newly installed maps app about some GPSLatitudeRef.

I thought I'll just synchronise whole `Camera` folder to my PC then ensure nothing is missing in the target dirs (nextcloud GUI shows the same sizes for the folders) and then just delete the source ones. Unfortunatly after synchronisation I see only the target ones. Source ones are visible only through the GUI. 
Now I'm scared to remove the source ones as I'm not sure if the destination ones will remain intact.

I checked my server's filesystem. The problematic folders sit only in `Camera` folder.

How can I safely remove the source ones from the GUI?

**Comment by kesselb** [comment]
Please use help.nextcloud.com for help requests in the first place. If it turns out to be a software issue we can continue here.

**Comment by Rychu-Pawel** [comment]
Sure, thanks, sorry. If it turns out to be a bug I'll reopen this one.

**Comment by kesselb** [comment]
Thanks :+1: Don't forget to use the search before. There are some deadlock related issues around.
