### ISSUE TITLE
Image preview sidebar does not follow images when you scroll through them

### ISSUE THREAD

**Issue by rlitman** [nextcloud/server#18698]
### Steps to reproduce
1. In Files, browse to a directory filled with images.
2. Click on any image file to pull up the image preview
3. Click on the "Open Sidebar" button in the top right
4. Click on the < or > symbol at either side of the image

### Expected behaviour

The sidebar details should reflect the actual image being previewed.

### Actual behaviour

The sidebar details remain static, and are stuck on the details of the image that was up when you opened the sidebar.

### Server configuration

**Operating system:**
Ubuntu 18.04.3 LTS

**Web server:**
apache2                               2.4.29-1ubuntu4.11

**Database:**
mysql-server-5.7                      5.7.28-0ubuntu0.18.04.4

**PHP version:**
php7.2                                7.2.24-0ubuntu0.18.04.1

**Nextcloud version:** (see Nextcloud admin page)
17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated regularly.

**Where did you install Nextcloud from:**
Been too long to remember.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.10.1
  - announcementcenter: 3.6.1
  - apporder: 0.9.0
  - audioplayer: 2.8.4
  - bruteforcesettings: 1.4.0
  - calendar: 1.7.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.6
  - dav: 1.13.0
  - external: 3.4.1
  - federatedfilesharing: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - richdocuments: 3.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - socialsharing_email: 1.0.6
  - socialsharing_facebook: 1.0.5
  - spreed: 7.0.2
  - suspicious_login: 3.0.1
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_nextcloud_notification: 2.2.0
  - twofactor_totp: 4.1.1
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - accessibility
  - admin_audit
  - encryption
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - impersonate
  - nextcloud_announcements
  - notes
  - support
  - survey_client
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REDACTED"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/REDACTED",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "sendmail",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "auth.bruteforce.protection.enabled": true,
        "maintenance": false,
        "loglevel": 2,
        "mysql.utf8mb4": true
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome 79

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>
This is not an error, just unexpected behavior

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by skjnldsv** [comment]
Fixed since a while, missed this issue
