### ISSUE TITLE
Unified approach to bundle/minify all Nextcloud CSS/JavaScript assets

### ISSUE THREAD

**Issue by brylie** [nextcloud/server#18705]
There has been a lot of ad-hoc effort since 2017 to optimize *specific* Nextcloud pages so that CSS and JavaScript assets are at least bundled together.

https://github.com/nextcloud/server/pull/3988

Ideally, there would be a unified approach the server could use to bundle and minify all necessary assets to serve one, or multiple, Nextcloud views. This way, the development team could be assured that all Nextcloud pages are rendering as efficiently as possible, without having to maintain a checklist of un-optimized pages for ad-hoc work.

## Related issues
- https://github.com/nextcloud/server/issues/3790
- https://github.com/nextcloud/server/issues/6214
- https://github.com/nextcloud/server/issues/13204
- https://github.com/nextcloud/server/issues/13205
- https://github.com/nextcloud/server/issues/15791
- https://github.com/nextcloud/files_pdfviewer/issues/161

**Comment by rullzer** [comment]
The recent approach is to just use webpack. Since bundling on the server is error prone, and leads to issues on large installations. jsut having static assets that are compiled at build and then just served is the way to go.

**Comment by szaimen** [comment]
Based on rullzer's comment, I am closing this issue. Thanks for the idea, though!

**Comment by kolaente** [comment]
@szaimen How would that work with a bunch of plugins which all bring their own js bundle? Even if all of these are minified, loading 10 bundles from 10 plugins is not great.

**Comment by szaimen** [comment]
It is currently the best way to solve this problem for Nextcloud's architecture.
