### ISSUE TITLE
tga file preview support

### ISSUE THREAD

**Issue by zaywalker** [nextcloud/server#18702]
**Is your feature request related to a problem? Please describe.**
not a problem. just i'd like to manage tons of tga files with preview.

**Describe the solution you'd like**
just like other image files? jpg, bmp, gif...

**Additional context**
Thanks!!!!

**Comment by kesselb** [comment]
Seems to be possible with gd and php7.4: https://github.com/php/php-src/commit/81fd113506e4c5833e64998651f232734ebb2cb7

What needs to be done:

1. Create a new preview provider extending https://github.com/nextcloud/server/blob/master/lib/private/Preview/Image.php
2. Make sure that `getMimeType` will return the right mime tpe for tga files.
3. Overwrite `isAvailable` and return true if `PHP_VERSION_ID >= 70400` and `method_exists('imagecreatefromtga')`.
4. Tell `OC_Image` how to read tga files: https://github.com/nextcloud/server/blob/master/lib/private/legacy/image.php#L346 Basically: Extending the switch with a case for tga. Also apply the checks from 3. Make sure that $res is null or false if php version to low or method not available. 
5. Run `./build/autoloaderchecker.sh` to update the autoloader (and include the new provider).
6. Open a pull request and see what the CI thinks ;)

cc @rullzer

**Comment by Pranav2612000** [comment]
I am a newcomer and would like to contribute. Has this issue been solved?

**Comment by rullzer** [comment]
> I am a newcomer and would like to contribute. Has this issue been solved?

nope feel free to tackle it.

@kesselb while you are right. I prefer to spend time to have this nicely done via apps.
As keeping this all in server doesn't scale ;)

**Comment by sndrr** [comment]
> @kesselb while you are right. I prefer to spend time to have this nicely done via apps.
> As keeping this all in server doesn't scale ;)

So, this issue should be closed, or reworded into an app-request? And how would one go about creating an app like this? I suppose this needs an mime type handler, since we are adding a new mime-type.

**Comment by Unpublished** [comment]
Looks like this was done in #25268

**Comment by kesselb** [comment]
@Unpublished thanks :+1:
