### ISSUE TITLE
Decrypt command didn't really decrypt.

### ISSUE THREAD

**Issue by lumy** [nextcloud/server#18709]
Hello,

Here's what happened:

my nextcloud installation was deleted, so i had to redownload the package.
I can't be sure i'm using the same version.
On the older installation file where encrypted, i'm pretty sure it was server-side.
I tried with the version i gave later on to decrypt all the files. so i can back them up and do a proper install. problem after the occ:decrypt it's seem my file are still encrypted.

### Steps to reproduce
1. install nextcloud and use server side encrypt.
2. remove nextcloud folder (data are not in nextcloud folder)
3. reinstall what you think is the right version of nextcloud (but may not be).
4. use the command occ encryption:decrypt-all

### Expected behaviour
Files should be decrypt

### Actual behaviour
The decrypt command did spend some time decrypting, it has not reported any error.
but when you look at the About.txt file it still encrypted.
```
HBEGIN:oc_encryption_module:OC_DEFAULT_MODULE:cipher:AES-256-CTR:signed:true:HEND-----------------------------------------------------------------------------------------------------
```

### Server configuration

**Operating system:**
Debian stretch 64b.

**Web server:**
Apache2

**Database:**
mariadb  Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.0.33-0+deb9u3 (cli) (built: Mar  8 2019 10:01:24) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-0+deb9u3, Copyright (c) 1999-2017, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
nextcloud-13.0.12

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install but using older data/db install.

**Where did you install Nextcloud from:**
release zip file from nextcloud website.

**Signing status:**
Can't signin because nextcloud want to do an app update and i don't whish to risk anything.

**List of activated apps:**

```
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - activity: 2.7.0
 - admin_audit: 1.4.0
  - bruteforcesettings: 1.3.0
  - comments: 1.4.0
  - dav: 1.6.0
  - encryption: 2.2.0
  - federatedfilesharing: 1.4.0
  - files: 1.9.0
  - files_external: 1.5.0
  - files_pdfviewer: 1.3.2
  - files_sharing: 1.6.2
  - files_texteditor: 2.6.0
  - files_trashbin: 1.4.1
  - files_versions: 1.7.1
  - files_videoplayer: 1.3.0
  - firstrunwizard: 2.3.0
  - gallery: 18.1.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.2.0
  - nextcloud_announcements: 1.3.0
  - notifications: 2.2.1
  - oauth2: 1.2.1
  - password_policy: 1.4.0
  - provisioning_api: 1.4.0
  - serverinfo: 1.4.0
  - sharebymail: 1.4.0
  - survey_client: 1.2.0
  - systemtags: 1.4.0
  - theming: 1.5.0
  - twofactor_backupcodes: 1.3.1
  - updatenotification: 1.4.1
  - workflowengine: 1.4.0
Disabled:
  - federation
  - user_external
  - user_ldap
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "file.pplc-avocats.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/file.pplc-avocats.fr",
        "dbtype": "mysql",
        "version": "13.0.12.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "theme": "",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:**
nop

**Are you using encryption:** 
yes

**Are you using an external user-backend, if yes which one:** 
Nop

**Comment by mundschenk-at** [comment]
I did not redownload the package, but I've also noticed that while `decrypt-all` does something, some files stay encrypted.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
