### ISSUE TITLE
PDF Viewer: sidebar overlaps / no way to re-open it

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18703]
![image](https://user-images.githubusercontent.com/5836855/71872118-c0fe7100-311b-11ea-84ac-f9a1f4f9593b.png)

- open sidebar of a pdf file
- click on pdf to show it
- see that sidebar overlaps pdf

I would have expected that the remaining area is used.

Another problem is that, once it is closed, I cannot re-open the sidebar.

@skjnldsv (maybe?)

**Comment by wiswedel** [comment]
maybe related: https://github.com/nextcloud/text/issues/522

**Comment by skjnldsv** [comment]
> maybe related: [nextcloud/text#522](https://github.com/nextcloud/text/issues/522)

no, the pdf viewer doesn't use the unified viewer

**Comment by tobiasKaminsky** [comment]
Why is this closed? I can reproduce it still on NC19?

**Comment by skjnldsv** [comment]
Fixed with nc20
