### ISSUE TITLE
[others with access] duplicate entries on level 0

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18712]
### Steps to reproduce
1. User A shares _Foo_ with User B
2. User A shares _Foo/Bar_ with User C
3. User A opens sidebar for _Foo/Bar_
4. User C appears in the list of sharees for _Foo/Bar_
5. User A clicks on _Others with Access_

### Expected behaviour
User B appears as _other with access_.

### Actual behaviour
User B and User C appear as _others_ with access, even though User C is already listed in this object's sharee list.

**Comment by ChristophWurst** [comment]
@daita?

**Comment by daita** [comment]
this fix only the fact that shares in current folder will not be displayed within the inherited shares. However, if _Foo/_ was shared to UserC, the share would be displayed in the inherited shares.
