### ISSUE TITLE
List entry is behind header

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18719]
![image](https://user-images.githubusercontent.com/5836855/71898033-8f57cb00-3158-11ea-82ac-da9cfdb4d6cf.png)

Behind "Name" is 123.txt, which is barely readable.

_Originally posted by @tobiasKaminsky in https://github.com/nextcloud/server/pull/18707#issuecomment-571581983_

**Comment by kesselb** [comment]
Seems similar to https://github.com/nextcloud/server/issues/18414. It's probably helpful to add in which view you see this.

**Comment by tobiasKaminsky** [comment]
It is in "pending share" view of https://github.com/nextcloud/server/pull/18707
Julius said in this PR that it is unrelated to this PR, so I opened up a new issue.

**Comment by juliushaertl** [comment]
Closing as I cannot reproduce it on latest master anymore.
