### ISSUE TITLE
Change avatar placeholder from single letter to 2 letters (Firstname Lastname)

### ISSUE THREAD

**Issue by matchish** [nextcloud/server#18717]
I want to change a text generated for an avatar image.

Now it only one symbol. For example, if my name `Serge Shliakhov` avatar will be white `S` letter with some background. I want to change this behavior to get `SS` text as a result.

I see two solutions

- Simple solution. Rename `getAvatarLetter` to `getAvatarText` and change implementation to get the first letters from two first words in a display name, or one letter if it's only one word.
- Let an app developer redefine the behavior. We can introduce `IUserAvatarFactory` interface for example and inject it to [AvatarManager](https://github.com/nextcloud/server/blob/12bdb95c1a40170652570decef7f466e4b97aa65/lib/private/Avatar/AvatarManager.php). Then instead hardcoded [UserAvatar](https://github.com/nextcloud/server/blob/12bdb95c1a40170652570decef7f466e4b97aa65/lib/private/Avatar/AvatarManager.php#L109) we can use the injected factory to create an avatar with a desired behavior. 

Now I can redefine the behavior only if I copy/paste code of `AvatarManager` to my own class. I even can't extend it.

I'm ready to implement any solution if you don't mind and create pull request.

**Comment by kesselb** [comment]
I don't have a strong opinion on that. 

cc @nextcloud/designers opinions? 

>  I even can't extend it.

Extending from AvatarManager, changing the implementation and register your [avatar manager with the container](https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/lib/private/Server.php#L656-L664) will not work?

**Comment by kesselb** [comment]
cc @rullzer @ChristophWurst

**Comment by matchish** [comment]
> I don't have a strong opinion on that.
> 
> cc @nextcloud/designers opinions?
> 
> > I even can't extend it.
> 
> Extending from AvatarManager, changing the implementation and register your [avatar manager with the container](https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/lib/private/Server.php#L656-L664) will not work?

I can't extend `userManager` is private
Even if it will be protected if I extend `AvatarManager` then I should copy/paste code from `getAvatar` method. And if the original method will be changed then my class will be broken.

**Comment by kesselb** [comment]
That's a drawback. Keep in mind there is also `GuestAvatar` extending `Avatar`. Probably instead of overwriting / injecting a custom UserAvatar / GuestAvatar a CustomAvatarTextStrategy is easier.

**Comment by jancborchardt** [comment]
Did some research on others which show avatar placeholders, and most show 2: iOS, Skype, Signal for example.

Since only showing one letter is not very informative, we should also switch to using 2 letters in general.

> I'm ready to implement any solution if you don't mind and create pull request.

@matchish that would be great! @nextcloud/vuejs would this be something for the Vue components as well?

**Comment by skjnldsv** [comment]
> @nextcloud/vuejs would this be something for the Vue components as well?

maybe, but we're using the avatar endpoint as default, so if we have this, it's acting as a fallback :)

**Comment by matchish** [comment]
It's even better.

**Comment by matchish** [comment]
> That's a drawback. Keep in mind there is also `GuestAvatar` extending `Avatar`. Probably instead of overwriting / injecting a custom UserAvatar / GuestAvatar a CustomAvatarTextStrategy is easier.

It's even better

**Comment by matchish** [comment]
> Did some research on others which show avatar placeholders, and most show 2: iOS, Skype, Signal for example.
> 
> Since only showing one letter is not very informative, we should also switch to using 2 letters in general:
> 
> * Firstname and Lastname if available
> * If only one name is set, use only one letter
> * Ignore titles, nicknames or such
> 
> > I'm ready to implement any solution if you don't mind and create pull request.
> 
> @matchish that would be great! @nextcloud/vuejs would this be something for the Vue components as well?

I'm going just to change implementation of `getAvatarLetter`. No introduction `CustomAvatarTextStrategy`. I understand you right?

**Comment by jancborchardt** [comment]
@matchish yes, no custom stuff or settings, we just change the default to show 2 (or 1 if only one name is set). :)

**Comment by feutl** [comment]
Can this be tested with 18.0.1 already ?

Thanks

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/server/pull/18745

Will be part of Nextcloud 19.

**Comment by alhague** [comment]
It looks like an innocent change until someone appears and asks you to prevent evil two letter combinations from forming because they are "verboten". Then you start to wish this had been configurable.

**Comment by raimund-schluessler** [comment]
> It looks like an innocent change until someone appears and asks you to prevent evil two letter combinations from forming because they are "verboten". Then you start to wish this had been configurable.

This correctness might go a bit to far, if you end up forbidding someones initials.

**Comment by alhague** [comment]
> > It looks like an innocent change until someone appears and asks you to prevent evil two letter combinations from forming because they are "verboten". Then you start to wish this had been configurable.
> 
> This correctness might go a bit to far, if you end up forbidding someones initials.

Personally I can agree, but professionally I have an undesired problem now :-(

**Comment by raimund-schluessler** [comment]
> 
> 
> > > It looks like an innocent change until someone appears and asks you to prevent evil two letter combinations from forming because they are "verboten". Then you start to wish this had been configurable.
> > 
> > 
> > This correctness might go a bit to far, if you end up forbidding someones initials.
> 
> Personally I can agree, but professionally I have an undesired problem now :-(

Maybe you could just upload an avatar for this user then?

**Comment by alhague** [comment]
> > > > It looks like an innocent change until someone appears and asks you to prevent evil two letter combinations from forming because they are "verboten". Then you start to wish this had been configurable.
> > > 
> > > 
> > > This correctness might go a bit to far, if you end up forbidding someones initials.
> > 
> > 
> > Personally I can agree, but professionally I have an undesired problem now :-(
> 
> Maybe you could just upload an avatar for this user then?

yes, I hope this solution approach will be accepted
