### ISSUE TITLE
Please update "Maintenance and Release Schedule" accordingly.

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/server#18725]
After the last release the new Release Dates are not annouced:

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Please update table to make the updates planable for the Admins. :-)
Thanks.

**Comment by rullzer** [comment]
Done. Yeah that slipped with the christmas stuff ;)

**Comment by pm-pm** [comment]
Hello again,

could you please update again. ;-) Last release is some days ago.

https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

Thanks
