### ISSUE TITLE
Question mark in folder breaks sidebar file info

### ISSUE THREAD

**Issue by Mikescops** [nextcloud/server#18721]
### Steps to reproduce
1. Name a folder with a question mark at the end like "Question ?"
2. Try to open details, sidebar fail loading file info

![image](https://user-images.githubusercontent.com/4266283/71907475-6a6d5300-316c-11ea-82f0-c5e6f8d40479.png)

### Expected behaviour
File info should open properly.

### Actual behaviour
File info is not loading. Console states: `Error while loading the file data Error: "Request failed with status code 404"`

### Server configuration

**Operating system:**
5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
PHP 7.2.24-0ubuntu0.18.04.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install 

**Nextcloud version:**
Nextcloud 18.0.0 Beta3

**Comment by kesselb** [comment]
cc @skjnldsv @gary-kim
