### ISSUE TITLE
Image of active users and shares in serverinfo too small

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#18731]
Maybe not a bug but almost. The figures are so small so not useful 
NC17.0.2

![image](https://user-images.githubusercontent.com/36486009/71962366-8e2aaa80-31f9-11ea-940d-8e7d61544a79.png)

**Comment by kesselb** [comment]
Serverinfo is here: https://github.com/nextcloud/serverinfo Probably a new issue is not required. I think that's been logged already. Thanks :+1:

**Comment by arnowelzel** [comment]
No this bug is still present in NC 18.0.2. I'll open a new issue for this.
