### ISSUE TITLE
files sidebar broken

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#18746]
seems like since https://github.com/nextcloud/server/pull/18724 the sidebar is broken

![sidebarError](https://user-images.githubusercontent.com/1804221/71978619-10c46180-321c-11ea-94df-b3a072c38ad4.gif)

**Comment by gary-kim** [comment]
That's really strange, I can't reproduce that. Let me take a closer look

**Comment by gary-kim** [comment]
It may have something to do with the webserver configuration being used. I can't reproduce with my Apache setup but maybe it becomes a problem with some configs. Let's just skip encoding the slashes then.
