### ISSUE TITLE
config/config.php stores 'mail_smtppassword' in plaintext

### ISSUE THREAD

**Issue by dncnmckn** [nextcloud/server#18743]
### Steps to reproduce
1. open config/config/php file via file manager in cpanel and look at password.

### Expected behaviour
Tell us what should happen: should this not be encrypted?

### Actual behaviour
Tell us what happens instead: it is not encrypted.

### Server configuration

**Operating system:**
Linux

**Web server:**
Apache
**Database:**
mySQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
17.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh.
**Where did you install Nextcloud from:**
cpanel/softalicious

**Comment by ChristophWurst** [comment]
> should this not be encrypted?

encryted with what?

**Comment by nickvergessen** [comment]
With the salt that is stored in the same file. There is also always code necessary to decrypt this, so while you can't read it in the file anymore, all information for decryption is going to be there, so you can decrypt it anyway.
