### ISSUE TITLE
Changing password doesn't work for non-admin users

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#1874]
It seems that there is an issue with the current master that has somehow been introduced recently: When a user that is **not** in the admin group tries to change his password on the personal page, a 403 response is returned on the ajax call and the password change is unsuccessful.

**Comment by nickvergessen** [comment]
I will have a look

**Comment by nickvergessen** [comment]
Fix is in https://github.com/nextcloud/server/pull/1925

**Comment by GitHubUser4234** [comment]
Thanks!
