### ISSUE TITLE
Already exists warning on rename very red

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/server#18751]
### Steps to reproduce
1. Attempt to rename a file to the same name as another file in the same directory.

### Expected behaviour
Tell us what should happen
The interface should warn the user that another file in the folder has the same name.

### Actual behaviour
Tell us what happens instead
The interface does warn the user very aggressively by making the entire text box red. Like, **really aggressively**! 

![output](https://user-images.githubusercontent.com/47195730/71985184-fcf11d80-3264-11ea-930e-5d7e95914147.gif)

**Browser Version:** `Mozilla Firefox 72.0b11 (64-bit)`

### Server configuration

**Nextcloud version:** (see Nextcloud admin page) v18.0.0RC1-70-g8899162463

cc @nextcloud/designers

**Comment by ma12-co** [comment]
Agree, that's one aggressive warning xD
