### ISSUE TITLE
Changing password hint stays on personal page until page refresh

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#1875]
When a user tries to change his password with a wrong old password, a hint is shown saying "Wrong password", which is fine. However when the user corrects the old password and the password change is then successful (as indicated by a check mark), the previous hint is not cleared. This can be quite confusing:

![image](https://cloud.githubusercontent.com/assets/16538178/19642160/a0e8293c-9a16-11e6-8039-3ca46250e802.png)

Observation is based on the current master.

**Comment by GitHubUser4234** [comment]
With the latest code I pulled today, the UI for changing password somehow got messed up suddenly, maybe it can be fixed in a row, here some screenshot:

Eye icon in the wrong field
![image](https://cloud.githubusercontent.com/assets/16538178/19757562/235f14fc-9c56-11e6-899e-74387d0a12a9.png)

Password strength indicator in the wrong field:
![image](https://cloud.githubusercontent.com/assets/16538178/19757595/58d76b0c-9c56-11e6-94b2-2a31cca82576.png)

**Comment by henrymohn** [comment]
Please review PR #2021.  This is my first official PR to any project, so please let me know if I need to correct anything.  I read over the Development Guidelines published on docs.nextcloud.com and tried to make sure I followed everything I could.

**Comment by MorrisJobke** [comment]
Fixed with #2021
