### ISSUE TITLE
Setting to enforce strict log-in for external apps

### ISSUE THREAD

**Issue by dacoex** [nextcloud/server#18763]
**Is your feature request related to a problem? Please describe.**
Currently, there seem to exist many ways to log-in:
* via webdav
* via the mobile apps.

Especially when using the mobiles apps around, this creates a trust issue:
I have to be sure that apps do not leak the credentials.

**Describe the solution you'd like**
Users or administrators should be able to enforce extra strict log-in settings where only the following methods would be allowed:
* using offical desktop app
* using the offical mobile app
* using any log-in based on user created app token

This means, that any app would either need to request authorization via the mobile app (like it is handled with DAVx) or use an app token.
No need to "trust" the app developers. 

**Describe alternatives you've considered**
n/a

**Additional context**
This is relevant because not all apps in the app stores are security reviewed or audited.

**Comment by szaimen** [comment]
Please see
![image](https://user-images.githubusercontent.com/42591237/119965190-4cdf9a00-bfaa-11eb-8e4f-d2b072d4ffac.png)
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=token
Thanks!
