### ISSUE TITLE
Flow: different Events between admin & user config

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#18762]
within event-config, I have different conditions between admin:

![Screenshot 2020-01-08 at 21 21 57](https://user-images.githubusercontent.com/13385119/72012829-f1015d80-325c-11ea-9cb3-df3500459134.png)

and user settings:
![Screenshot 2020-01-08 at 21 22 55](https://user-images.githubusercontent.com/13385119/72012887-0aa2a500-325d-11ea-9454-8f88d04eab39.png)

e.g. the mime-type is only available for admin.
Is there a reason behind this setting?

@blizzz

**Comment by blizzz** [comment]
I think it is an oversight, and in the implementation we just didn't whitelist it.
