### ISSUE TITLE
Show subfolders when clicking on arrow in breadcrumb

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#18776]
When navigating upwards a directory tree, it would help to show a folders subfolders when clicking on the arrow in the breadcrumb. E.g. the files explorer in windows does it like this:

<img width="251" alt="breadcrumb" src="https://user-images.githubusercontent.com/2496460/72067508-2d779c80-32e3-11ea-9264-ab377ceccb80.png">

Hovering over the breadcrumb bar with the opened dropdown would then show the subfolders for the currently hovered folder.

**Comment by gary-kim** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Hmmmm – this does look interesting but seems like stuff will get too crowded then, and I’m not sure of the specific problem it solves.

While it does possibly make navigation quicker, it lacks the other files as points of reference, and basically reimplements the list in the breadcrumb?

Do any other file managers do this? Can’t find it in macOS Finder or GNOME Files.

**Comment by raimund-schluessler** [comment]
Might be something Windows specific. TotalCommander (and Matlab) does it like this as well:

<img width="551" alt="breadcrumb" src="https://user-images.githubusercontent.com/2496460/72283003-297ab000-363e-11ea-9e4f-81d4a1b5646d.png">

It would help to navigate or move something to a folder up the tree. But I agree, the use case is a bit limited.

**Comment by skjnldsv** [comment]
I also think it's a bit too much
Let's close then :)
