### ISSUE TITLE
Make /data folder 0771 so .htaccess is readable

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/server#18781]
With default `0770` umask, /`data/.hatccess` is unreadable by the webserver, so Apache 2.4 produces:

`/home/nextcloud/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/nextcloud/data/' is executable`

Only solution is to make `/data` `0771`.

For review and discussion (maybe other folders need these too).

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/lib/private/Setup.php#L224-L226

Nextcloud will create the data directory during setup and also create the .htaccess. I'm not aware of any code changing the permissions. Files and Folder created with the default umask. So if apache2 needs in your setup 0771 to read .htaccess file your default umask is wrong. 

cc @MichaIng

**Comment by acs-ferreira** [comment]
umask here is `002` which translates to default directory permissions `775` and default file permissions are `664`, which is the case (tested). Nextcloud is setting `770` for `/data`.

https://github.com/nextcloud/server/blob/12bdb95c1a40170652570decef7f466e4b97aa65/lib/private/legacy/util.php#L1013-L1014

Without the executable bit, Apache is unable to read htaccess (at least for me [and others](https://www.tech-g.com/2016/03/06/server-unable-to-read-htaccess-file-denying-access-to-be-safe/).)

**Comment by kesselb** [comment]
Scary to have such logic with a `check` method :fearful: Let's see what others think about this proposal. I still think its some kind of setup issue. If apache2 is not able to read .htaccess something is wrong with the permissions. I'm always adding my users to www-data group. But my knowledge is probably outdated in terms of linux administration :see_no_evil:

**Comment by MichaIng** [comment]
The last change I was part of was about .htaccess content only, not about how it is created.

From what if 77[0-3] permissions break webserver from being able to read the file, then the PHP handler runs as a different user + without webserver user being member of the same group, which is a quite unusual setup?

Also AFAIK at least on default Debian apache2 package the main process runs as root while only the child processes for actual content serving are spawned as www-data. This allows the server to read configs, SSL certs and .htaccess files (?) with any permissions. But that must not be true on other OS or custom setup.

**Comment by acs-ferreira** [comment]
> If 77[0-3] permissions break webserver from being able to read the file, then the PHP handler runs as a different user + without webserver user being member of the same group, which is a quite unusual setup?

I think you're right about this, as i'm running php and webserver with separate users, and also different groups for different purposes, this is why common CMS or PHP Frameworks run fine with default permissions (so 755) but not 770.

Closing as it seem to be setup-specific.

**Comment by MichaIng** [comment]
Of course it could be discussed to:
- Use default UMask if this is changes by Nextcloud for the relatively sensitive .htaccess files
- Change UMask Nextcloud internally to 775/664 for all generated dirs/files to assure they are readable by whatever user runs Apache, if this is even possible PHP-script internally. A benefit would be especially there for shared hostings where the user has no control, although no hosting provider will run such setup which would break most PHP-based web applications.

One could argue that .htaccess shouldn't be world-readable, but this is going into security-through-obscurity then.

**Comment by acs-ferreira** [comment]
@MichaIng please note that here is the folder that has to be executable, not (only) the file readable.

If you search for `unable to check htaccess file, ensure it is readable` on a search engine, you'll see a lot of posts of people facing this using cPanel or other common shared hosting panels when rights are not those set by the server itself (same case as here).

I'll reopen to have a little more feedback an let "big people" take decisions 😋

**Comment by MichaIng** [comment]
The obvious solution for cPanel would be to add it's user to all groups of file owners you want to admin with it, hence www-data or whatever PHP runs as in this case.

**Comment by linuxmangr** [comment]
Hello, I set the /data to 771 but is not work, change it to 755 nit work, set like setup it with install to 750 and not work.

I get the message in logs of the domain :  
[core:crit] [pid 23936:tid 140606751893248] (13)Permission denied: [client 192.168.1.155:0]  AH00529: /home/webusr/domain.com/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/webusr/domain.com/public_html/data/' is executable only when I go  to settings/admin/overview 
My Version Nextcloud 24.0.5 
PHP 8.1.9
Memory Limit 6GB
DB mysql - v 10.3.34 
.htaccess is 644 
For now the data/ is chmod 750 
The .htaccess is 644 and is correct
My WebServer is :
Server version: Apache/2.4.38 (Debian) like application server 
Nginx 1.22.0 like the proxy
PHP 8.1.9 (fpm-fcgi) (built: Aug 15 2022 09:50:29)
Zend Engine v4.1.9, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.9, Copyright (c), by Zend Technologies

P.S. In all other settings or pages this message not show in logs. 
Can some one suggest me forget this message or I can resolve it?

**Comment by thefantas** [comment]
I have the same problem, if I set it to 755 another error appears. 
AH01797: client denied by server configuration: /home/xxx/public_html/data/.ocdata
but after running the cron "data" it returns to 770... /.htaccess pcfg_openfile: unable to check htaccess file
:/

**Comment by handkerchief333** [comment]
Same Problem:
`Permission denied: /web/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that 'web/data/' is executable`

Nextcloud Hub 3 (25.0.3)
/data = 770
/config = 755

**Comment by D3nnis3n** [comment]
Same here, data directory is 770 and .htaccess is 644, yet those errors appear.

**Comment by KmdKeen** [comment]
Same boat:

`
[Mon Jan 20 14:47:28.815376 2025] [core:crit] [pid 1517079:tid 1517099] (13)Permission denied: [client <IP>:0] AH00529: /var/www/vhosts/domain.tld/nextcloud.domain.tld/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/var/www/vhosts/domain.tld/nextcloud.domain.tld/data/' is executable
`
