### ISSUE TITLE
"busy" event is not translated in public access

### ISSUE THREAD

**Issue by cboonet** [nextcloud/server#18782]
### Steps to reproduce
1. Create an event with option "when shared show only busy"
2. Share the calendar (tick public access)
3. go to to the shared link of the public calendar with a no english web browser 

### Expected behaviour
If your web browser is for example in french (but in a language other than English, it's the same problem), the event should display "occupé" (busy in french)

### Actual behaviour
If your web browser is in french (but in a language other than english, it's the same problem), the event displays "busy" and not the translation of "Busy" (it's OK only in english)

The word "busy" seems to be translated in transifax but not used in code ?

### Calendar app
**Calendar app version:** 1.7.1

### Client configuration
**Browser:**  Firefox 72.0.1 64 bits

**Operating system:** Windows 10

### Server configuration

**Operating system**: CentOS 7.7.1908

**Web server:** Apache 2.4.6

**Database:** MariaDB 5.5.64

**PHP version:** 7.2.23

**Nextcloud Version:**17.0.2

**Updated from an older installed version or fresh install:** Updated from an older installed

![ncc_busy_no_translation](https://user-images.githubusercontent.com/58264175/72072119-919f5e00-32ed-11ea-878c-d597fbd20728.png)

**Comment by gary-kim** [comment]
Decided to have a go and I narrowed down to here but I'm not sure how to get an instance of `IL10N` in a scenario like this. Could I get some pointers?
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/apps/dav/lib/CalDAV/CalendarObject.php#L112

**Comment by kesselb** [comment]
Probably there is a better way. But from having a quick look at the code there are two options:

Hacky: `$l10n = \OC::$server->getL10NFactory()->get('dav');`

Right: Extend `CalendarObject` constructor to accept `L10N $l10N`. Change all initialization of `CalendarObject` and `PublicCalendarObject`.
