### ISSUE TITLE
	Exception: Call to undefined function OCA\Theming\mime_content_type() 

### ISSUE THREAD

**Issue by ChinaParrot** [nextcloud/server#18798]
Exception: Call to undefined function OCA\Theming\mime_content_type()/www/wwwroot/nextcloud/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Theming\ ... {}, "getFavicon")/www/wwwroot/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Themin ... r", "getFavicon", OC\AppFramew ... {}, { app: "sett ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ app: "sett ... "})/www/wwwroot/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { app: "sett ... "})/www/wwwroot/nextcloud/lib/base.php - line 997:OC\Route\Router->match("/apps/themi ... s")/www/wwwroot/nextcloud/index.php - line 42:OC::handleRequest()被围住Error: Call to undefined function OCA\Theming\mime_content_type()/www/wwwroot/nextcloud/apps/theming/lib/IconBuilder.php - line 69:OCA\Theming\IconBuilder->renderAppIcon("settings", 128)/www/wwwroot/nextcloud/apps/theming/lib/Controller/IconController.php - line 126:OCA\Theming\IconBuilder->getFavicon("settings")/www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:OCA\Theming\Controller\IconController->getFavicon("settings")/www/wwwroot/nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 99:OC\AppFramework\Http\Dispatcher->executeController(OCA\Theming\ ... {}, "getFavicon")/www/wwwroot/nextcloud/lib/private/AppFramework/App.php - line 126:OC\AppFramework\Http\Dispatcher->dispatch(OCA\Theming\ ... {}, "getFavicon")/www/wwwroot/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:OC\AppFramework\App::main("OCA\\Themin ... r", "getFavicon", OC\AppFramew ... {}, { app: "sett ... "})<<closure>>OC\AppFramework\Routing\RouteActionHandler->__invoke({ app: "sett ... "})/www/wwwroot/nextcloud/lib/private/Route/Router.php - line 297:call_user_func(OC\AppFramew ... {}, { app: "sett ... "})/www/wwwroot/nextcloud/lib/base.php - line 997:OC\Route\Router->match("/apps/themi ... s")/www/wwwroot/nextcloud/index.php - line 42:OC::handleRequest()
--

**Comment by jospoortvliet** [comment]
Sorry, this is not a bug report. Please use the template we provide.

**Comment by vuthea** [comment]
You can check if Php-fileinfo extension is installed.

**Comment by sanchosk** [comment]
I know this is not the place, but the comment from @vuthea fixed it for me.
All I did was `sudo apt install php-mime-type`
