### ISSUE TITLE
Connection actively refused (webdav)

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#18794]
### Steps to reproduce

Enable a windows webdav mount with rclone on 18RC2, click on file and watch file explorer freeze for ~1 minute.

Trying to play the file directly with VLC works, however it takes a very long time to start streaming (as in, download to start verified by network manager).

And when it does stream it stutters and freezes.

You can find the file online for free - it's the 4k starwars trailer @ 1.2GB in size.

I feel it's important to note here that I use Ceph S3 locally and as primary storage, which means nextcloud does not support seeking with it. However once the file is playing it shouldn't be stuttering.

This also means it takes a very long time to start playing in the first place.

PHP is using 15% of a core on a 8700k (performance mode) while trying to stream this. The only thing the nextcloud server is doing is playing this file. The only thing installed on the nextcloud server is this one file.

### Expected behaviour
File explorer and file should play correctly and not freeze.

### Possible reasons

Nextcloud was not designed to stream lossless 4k files over webdav. However, this still does not explain why file explorer freezes when clicking on the file (as in, not downloading at all).

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Nginx
**Database:**
Mariadb
**PHP version:**
fpm-7.3
**Nextcloud version:** (see Nextcloud admin page)
18RC2
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from RC1

**Nextcloud configuration:**
Using redis as cache/filelocking. Most of the rest is standard.
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes

### Logs

rclone log:

Full of this:

`2020/01/09 13:59:21 ERROR : IO error: Get https://drive.blah.me/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv: dial tcp 10.0.1.20:443: connectex: No connection could be made because the target machine actively refused it.
2020/01/09 13:59:21 ERROR : Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv: ReadFileHandle.Release error: file already closed
2020/01/09 13:59:21 ERROR : IO error: file already closed`

nextcloud log:

`$
{"reqId":"sAaq9iohFpmMlPqdUvLR","level":3,"time":"2020-01-09T22:32:28+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"EPMzS8JiVhRqQMTs1y5X","level":3,"time":"2020-01-09T22:32:28+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"9DlCWrgRfArzFYoA8qsj","level":3,"time":"2020-01-09T22:32:38+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"4q9XP9LI6pxP2qc0e0y2","level":3,"time":"2020-01-09T22:32:38+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"5cbY9MWaGgj3w7YNf8T2","level":3,"time":"2020-01-09T22:32:47+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"AcC0mETMftd5mSutQWBy","level":3,"time":"2020-01-09T22:32:47+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"f1z2paeEtIfi781wfdxj","level":3,"time":"2020-01-09T22:32:56+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not sup$
{"reqId":"Y7g15VBKHzuoOYnxqYDP","level":3,"time":"2020-01-09T22:32:56+00:00","remoteAddr":localiphere,"user":"blah","app":"PHP","method":"GET","url":"/remote.php/webdav/Library/Movies/SW9_4K_4096x1716_DTS-HD_MA_51_AC3_51-thedigitaltheater.mkv","message":"fseek(): stream does not su`

nginx log:

`ent: 10.0.1.50, server: me.me, request: "GET /remote.php/webdav/Library/Movies/test.mkv HTTP/2.0", upstream: "fastcgi://127.0.0.1:porthere", host: "me.me"
2020/01/09 14:48:53 [warn] 3644#3644: *9 an upstream response is buffered to a temporary file /var/cache/nginx/fastcgi_temp/7/01/0000000017 while reading upstream, client: localiphere, server: me.me, request: "GET /remote.php/webdav/Library/Movies/test.mkv HTTP/2.0", upstream: "fastcgi://127.0.0.1:porthere", host: "me.me"`

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
