### ISSUE TITLE
"Unable to load the share list"

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#18815]
I saw this in the Nc18 RC on our instance.

If I open the details view on a file shared with me through a Talk room and go to the "Sharing"-tab I see this:

![image](https://user-images.githubusercontent.com/1589737/72162159-b6fd9c00-33c1-11ea-86f8-b040391b58be.png)

I can neither see the list of people who have access to the file nor can I reshare it, copy an internal link, etc.

**Comment by ncodeyx** [comment]
I can confirm this happens after upgrade to Nextcloud 18.0.3.
Browser reports this:
![image](https://user-images.githubusercontent.com/35234835/77581542-2cb3d700-6ede-11ea-96b7-168f93ad40ae.png)

Nextcloud logs:
![image](https://user-images.githubusercontent.com/35234835/77581564-376e6c00-6ede-11ea-9884-f140e02fa5f4.png)

**Comment by bushrang3r** [comment]
Same problem, new install, Nextcloud 18.0.3 (Was able to add a bunch of shares before this happened)
I'm getting **no** errors on the logging screen as above (all levels of reporting switched on)

**Comment by ncodeyx** [comment]
> Same problem, new install, Nextcloud 18.0.3 (Was able to add a bunch of shares before this happened)
> I'm getting **no** errors on the logging screen as above (all levels of reporting switched on)
> 
> **EDIT:** I solved my issue. It was simply that in the admin account, in settings > sharing, I had unchecked the _Allow apps to use the share API_ check box.

This fixed it for me too, although I'm not sure why Nextcloud disabled it by default after update, thanks!

**Comment by GitHubUser4234** [comment]
> Same problem, new install, Nextcloud 18.0.3 (Was able to add a bunch of shares before this happened)
> I'm getting **no** errors on the logging screen as above (all levels of reporting switched on)
> 
> **EDIT:** I solved my issue. It was simply that in the admin account, in settings > sharing, I had unchecked the _Allow apps to use the share API_ check box.

But doesn't mean it would disabled sharing completely? From the Nextcloud doc:

![image](https://user-images.githubusercontent.com/16538178/102735625-e82a6e80-437d-11eb-98bd-d9526ffd346a.png)

**Comment by GitHubUser4234** [comment]
Update:  In addition to the above problem description, it has been found that when a shared folder is renamed by the folder's owner, he will see the "Unable to load the shared list" message. When he renames the folder again by using the original name, the shared list re-appears.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by 4nanook** [comment]
It's still a problem in 22.2.3

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
