### ISSUE TITLE
No custom theming for some SVG-icons

### ISSUE THREAD

**Issue by fuanegua** [nextcloud/server#18820]
As described in this thread [#3094](https://github.com/nextcloud/server/issues/3094#issue-201066602) some svg icons are not changed when putting custom icons into the theme folder.

In my case both `folder-external.svg` and `toggle.svg` are still the old icons. 
After running `sudo -u www-data php occ maintenance:mimetype:update-js` and refreshing the webpage all other icons seem to be linked correctly, but those two still linking to `/core/img/filetypes/folder-external.svg` and 
`/core/img/actions/toggle.svg` 

instead of
`/themes/mytheme/core/img/filetypes/folder-external.svg` and
`/themes/mytheme/core/img/actions/toggle.svg`

Can anyone confirm this as a bug? Thanks a lot!

**Comment by kesselb** [comment]
Closing in favor of #20631
