### ISSUE TITLE
Copy whole folder fails because of 'target exists'

### ISSUE THREAD

**Issue by zeigerpuppy** [nextcloud/server#18846]
related to #15785
when copying a whole folder, there is no way to paste that folder in the current parent.

### Steps to reproduce
1. create a folder `parent`
2. create a folder inside `parent` called `test`
3. select and make action `Move or copy`
4. click `copy` in the dialogue that appears

outcome is the error message: `could not copy "test", target exists`

### Expected behaviour
If there is an attempt to copy a folder into a target where the same name exists, an option should be provided to rename the copied folder.  Alternatively, a safe name could be suggested like `test_copy`.

### Actual behaviour
Copy of folder fails with no option to change the destination name.

### Server configuration

**Operating system:**
Debian 9

**Web server:**
Apache2.4

**Database:
MariaDB

**PHP version:**
7.2.26

**Nextcloud version:** 
17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

### Client configuration
**Browser:**
Firefox (latest)

**Operating system:**
OS X

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.2

**Comment by szaimen** [comment]
I'd say the way how to solve this is by just by creating a copy by appending to the folder name (2) or something like that.

**Comment by MrHappy** [comment]
This behavior also prevents merging 2 folders, which seems like default file-explorer functionality.

**Comment by mtklar** [comment]
This problem still exists in Nextcloud v24.0.0.

**Comment by mikevh1997** [comment]
Seems to work with files, but not folders. I personally think the perfect solution would be the option to just rename the new folder to something you'd like, or append '(2)' if thats too difficult to accomplish.
