### ISSUE TITLE
AmazonS3.php repeatedly logs fclose() error in logs.

### ISSUE THREAD

**Issue by isaacgerg** [nextcloud/server#18851]
Used a fresh install of nextcloud-snap on ubuntu with AWS. Hooked up to S3 bucket. Every file upload to the S3 bucket works but the following shows up repeatedly in the logs:

fclose(): supplied resource is not a valid stream resource at /snap/nextcloud/18019/htdocs/apps/files_external/lib/Lib/Storage/AmazonS3.php#641

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/15486
