### ISSUE TITLE
Feature request: share real directory path

### ISSUE THREAD

**Issue by florian-rabis** [nextcloud/server#18852]
Hey there,
in our daily workflow we have very often the need to share file paths to selected files. The sharing feature hides the real file structure on the server. For us in the board of our association it is very important to know where all the files are located on the server.
Especially the the client-app on mobile or desktop should have this feature.

Thanks for all your fantastic work. Nextcloud is an amazing tool and I am surprised day by day about all the features and possibilities you ensure! Keep up the good work!

Best regards
Florian

**Comment by szaimen** [comment]
isn't there an app for that in the appstore?

**Comment by szaimen** [comment]
https://apps.nextcloud.com/apps/sharingpath
