### ISSUE TITLE
Dropping a folder onto ifself should be impossible

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#18850]
### Steps to reproduce
1. Create two folders `a` and `b`
2. Select both folders
3. Start dragging the two folders by clicking on folder `a` or `b`.

### Expected behaviour
It should not be possible to drop the two folders onto themself.

### Actual behaviour
It is possible to drop the two folders onto the folder which was not clicked for starting the drag, see the image:

<img width="1045" alt="dragging" src="https://user-images.githubusercontent.com/2496460/72225486-4653ac80-3586-11ea-9d50-2bfb3d77e2fd.png">

Of course, moving folder `b` into itself fails and produces an error message:

<img width="1042" alt="dragging2" src="https://user-images.githubusercontent.com/2496460/72225518-7e5aef80-3586-11ea-80df-0c9561512b71.png">

But since I wanted to move both folders, moving folder `a` into folder `b` is not the intended result.

### Server configuration

**Nextcloud version:** stable18 as of 8b4b3e19bb93e334a7e5f97a5ca1c2b9b5c5cfe0

**Comment by raimund-schluessler** [comment]
If someone from @nextcloud/javascript could give me a hint were to start I would look into this.

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.1

cc @nextcloud/javascript any update here regarding raimund-schuessler's comment above?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by raimund-schluessler** [comment]
The issue persists with 25.0.4 and 26.0.0 dev.
