### ISSUE TITLE
Message when smtp server is not defined

### ISSUE THREAD

**Issue by GambaJo** [nextcloud/server#18857]
My Nextclod installation is new and I didn't know, I have to define a smtp server in the settings.
When I tried to share a download link via email I got a massage, that the server cannot be reached. First I thought the server of the receiver is broken.

Maybe the message can be more understandable. When the smtp server is not defined, then the message should tell me that.

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
