### ISSUE TITLE
User Settings option forwards to site default page only for one user on all browsers and computers

### ISSUE THREAD

**Issue by WNYmathGuy** [nextcloud/server#18865]
**System Information**:
[https://cloud.ruppssites.com/index.php/s/mw4nPrntn6ep3Sx](https://cloud.ruppssites.com/index.php/s/mw4nPrntn6ep3Sx)
Generated on 2020-01-11 
<details><summary>Key for System Information</summary>
vprY+KT1DlnG8u/3LV1q
</details>

Nextcloud version: **17.0.2** (_also see link above_)
Operating system and version: **Ubuntu 18.04 LTS** (_also see link above_)
Apache version: **2.4.41** (_also see link above_)
PHP version: **7.3.13 & 7.4.1** (_also see link above_)

#### Problem/Bug summary 
The user account that was given Admin type authority, but is not the initial full admin of the server cannot access their User Settings `/index.php/apps/settings`. I had a similar problem in the past where clearing browser cache was enough to fix things, but this seems different. The first admin account can see their own settings, but when impersonating the second admin account can't access settings. The attempts are merely forwarded to the `/index.php/apps/files` page which is the default page for the whole system. The second admin type user can't see settings in Chrome or Firefox on a Ubuntu 18.04 workstation or a Windows 10 PC. The first admin user can access settings of all other users while impersonating them and other users can access their settings on both computers.

This might be a _"red-herring"_, but when the second admin type user logs out, the page waits excessively long to land back on the login page. The user is logged out, but the normal logged-in page rendering just hangs for 3 minutes or until reloaded. 

### Steps to replicate it:

1. I don't know how this happened or if it started after upgrading to NC 17. I rarely access my settings. I do know it's consistent. Click Settings, or manually type in the URL for settings and get forwarded back to the default page (_Files browser_).

### The output of your Nextcloud log in **Admin > Logging**:
<code>
{"reqId":"XhqDIS89TLw5dUgyKPtfWAAAABA","level":0,"time":"2020-01-12T02:23:29+00:00","remoteAddr":"192.168.1.1","user":"2nd-admin","app":"ocr","method":"GET","url":"/index.php/apps/ocr/api/personal/languages","message":"Get favorite languages for user: 2nd-admin: ","userAgent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36","version":"17.0.2.1","id":"5e1a832238374"}
</code>

### The output of your config.php file in `/path/to/nextcloud/config`:
Included in the **System Information** link at top.

### The output of your Apache2 log in `/var/log/____`:
<code>
192.168.1.1 - - [11/Jan/2020:21:22:57 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:22:58 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:02 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:22:46 -0500] "GET /index.php/apps/logreader/poll?lastReqId=XhqC9Qagq3iJqPwKVP9OMAAAAAY HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:07 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:10 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:12 -0500] "GET /core/img/actions/checkbox-mark.svg HTTP/1.1" 200 1408 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:12 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:13 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:18 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:23 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:23 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:26 -0500] "GET /index.php/settings/user HTTP/1.1" 302 1592 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:26 -0500] "GET /index.php HTTP/1.1" 302 1028 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:06 -0500] "GET /index.php/apps/logreader/poll?lastReqId=XhqC9Qagq3iJqPwKVP9OMAAAAAY HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:26 -0500] "GET /index.php/apps/files/ HTTP/1.1" 200 14257 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:27 -0500] "GET /index.php/apps/terms_of_service/terms HTTP/1.1" 200 39587 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:28 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 932 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:28 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:28 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/apporder/getOrder HTTP/1.1" 200 1969 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/files_readmemd/config HTTP/1.1" 200 1564 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/gallery/config?extramediatypes=1 HTTP/1.1" 200 1601 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/drawio/ajax/settings HTTP/1.1" 200 988 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/ocr/api/personal/languages HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/richdocuments/ajax/settings.php HTTP/1.1" 200 1564 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/systemtags/lastused HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /ocs/v2.php/apps/spreed/api/v1/signaling/settings HTTP/1.1" 200 1106 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "PROPFIND /remote.php/dav/files/2nd-admin/ HTTP/1.1" 207 45892 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:27 -0500] "GET /index.php/apps/logreader/poll?lastReqId=XhqC9Qagq3iJqPwKVP9OMAAAAAY HTTP/1.1" 200 1281 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:29 -0500] "GET /index.php/apps/recommendations/api/recommendations HTTP/1.1" 200 2638 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:30 -0500] "GET /index.php/apps/files/ajax/getstoragestats.php?dir=/ HTTP/1.1" 200 1052 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:30 -0500] "GET /index.php/core/preview?fileId=608785&x=32&y=32 HTTP/1.1" 404 826 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:35 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:39 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:40 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:45 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:30 -0500] "GET /index.php/apps/logreader/poll?lastReqId=XhqDIS89TLw5dUgyKPtfWAAAABA HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:50 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:53 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:56 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:23:58 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:58 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:01 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:06 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:09 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:23:50 -0500] "GET /index.php/apps/logreader/poll?lastReqId=XhqDIS89TLw5dUgyKPtfWAAAABA HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:11 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:17 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:22 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:23 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:27 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:28 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/79.0.3945.79 Chrome/79.0.3945.79 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:24:28 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:10 -0500] "GET /index.php/apps/logreader/poll?lastReqId=XhqDIS89TLw5dUgyKPtfWAAAABA HTTP/1.1" 200 819 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:32 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:38 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
192.168.1.1 - - [11/Jan/2020:21:24:39 -0500] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 1508 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36"
192.168.1.1 - - [11/Jan/2020:21:24:43 -0500] "POST /index.php/apps/text/public/session/sync HTTP/1.1" 200 5407 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0"
</code>

**Comment by kesselb** [comment]
Sounds like: https://github.com/pierre-alain-b/rainloop-nextcloud/issues/121

**Comment by WNYmathGuy** [comment]
Damn, @kesselb got it in 1!

I disabled Rainloop and settings worked, re-enabled it and settings stopped working. I'll post over there now. I don't know if this one should be marked closed or what, so I'll leave that up to you. I'll just follow the other thread from now on.

**Comment by noci2012** [comment]
It might be something else as well.  Disabling rainloop didn't help on my system. 
So other apps might also trigger this issue as well. 

At least a Groupadmin access settings. I have a feeling (not accessing settings all the time), the update to 17.0.2 did start this.., at least update to 17.0.x

**Comment by noci2012** [comment]
Also ocDownloader: https://github.com/nextcloud/server/issues/17899

**Comment by noci2012** [comment]
These are the only redirects references directly to / i could find:
core/templates/404.php:if(!isset($)) {//standalone page is not supported anymore - redirect to /
core/templates/403.php:if(!isset($)) {//standalone page is not supported anymore - redirect to /

And this calls 403:
settings/Middleware/SubadminMiddleware.php:

        /**
         * Return 403 page in case of an exception
         * @param Controller $controller
         * @param string $methodName
         * @param \Exception $exception
         * @return TemplateResponse
         * @throws \Exception
         */
        public function afterException($controller, $methodName, \Exception $exception) {
                if($exception instanceof NotAdminException) {
                        $response = new TemplateResponse('core', '403', array(), 'guest');
                        $response->setStatus(Http::STATUS_FORBIDDEN);
                        return $response;
                }

                throw $exception;
        }
I lack sufficient details info on settings & authorisation inside this to investigate this further.

**Comment by kesselb** [comment]
> closed or what, so I'll leave that up to you. I'll just follow the other thread from now on.

I don't think we can fix anything here.

**Comment by noci2012** [comment]
At least some error message when group admin rights are invoked ? .... 
Biggest problem there is no trace of any fault, but for GroupAdmins some extensions don't work and the reason why is swept under the carpet.

**Comment by kesselb** [comment]
Fine by me ;) I haven't reproduced this yet. Not sure where to add such logging. It seems to me that the apps are using a deprecated / removed api to register a personal settings page? Probably easier to fix that ;)

**Comment by noci2012** [comment]
Possibly, IMHO the problem is just that there is a possibility of something in the code going wrong and the issue being hidden in stead of exposed in some logging. 
I have been looking around for a few hours a day in the past week or so before i had enough to search for on the web and ran into this. 

Reproducer: install Rainloop and/or ocdownloader (possibly others) as plugin, enable them and use an account that is  admin for a group. 
Try to select from the user menu the setttings item, a redirect to / is the only visible result.
Both these plugins have a different model for doing settings ocDownloader is probably the oldest, both have no section/php script in lib/Settings. (one doesn't even have a lib directory).

**Comment by kesselb** [comment]
I see your point. Nextcloud don't have a strong isolation like iOS or Android. I hope that will change in the future but is also a lot of work with many pitfalls.

> exposed in some logging.

Not possible for this case. The redirect is triggered here: https://github.com/pierre-alain-b/rainloop-nextcloud/blob/b93c22966e5ca4dbfc0e1caa6ddd67fe403ee888/rainloop/admin.php#L11

`checkAdminUser` will redirect to /files/ if the current user is not admin. That's true for sub admins. 

```
if (!OC_User::isAdminUser(OC_User::getUser())) {
	return;
}

OCP\Util::addScript('rainloop', 'admin');

$oTemplate = new OCP\Template('rainloop', 'admin-local');
$oTemplate->assign('rainloop-admin-panel-link', OC_RainLoop_Helper::getAppUrl().'?admin');
$oTemplate->assign('rainloop-autologin', \OC::$server->getConfig()->getAppValue('rainloop', 'rainloop-autologin', false));
return $oTemplate->fetchPage();
```

That works for me. Looks a bit weird because the section is empty then but you can use the personal settings again. 

This method to register a admin or personal page is deprecated since Nextcloud 14. It will be removed at some point in the future. If you like the rainloop app probably try to migrate some of the code? https://github.com/pierre-alain-b/rainloop-nextcloud/pull/76 looks like a start.
