### ISSUE TITLE
NC 15.0.14 occ files:scan crashes on StorageNotAvailableException

### ISSUE THREAD

**Issue by hagbartus** [nextcloud/server#18864]
### Steps to reproduce
1. Download and install NC 15.0.14
2. Run occ files:scan -all 
3. If a storage is not available it crashes

### Expected behaviour
Handle exception instead of crash

### Actual behaviour
Crashes because its calling a function that is only introduced in NC 16!

Error: Call to undefined method OC\AllConfig::getSystemValueInt() in/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php:454

```
	protected function setUnavailable(StorageNotAvailableException $e) {
		$delay = self::RECHECK_TTL_SEC;
		if($e instanceof StorageAuthException) {
			$delay = max(
				// 30min
	--->			$this->config->getSystemValueInt('external_storage.auth_availability_delay', 1800),
				self::RECHECK_TTL_SEC
			);
		}
		$this->getStorageCache()->setAvailability(false, $delay);
		throw $e;
	}
}

**Comment by kesselb** [comment]
Ouch :see_no_evil: Introduced by: https://github.com/nextcloud/server/pull/17071

`$this->config->getSystemValueInt('external_storage.auth_availability_delay', 1800),`

needs to be:

`(int)$this->config->getSystemValue('external_storage.auth_availability_delay', 1800),`

cc @blizzz @rullzer 15 is EOL. What now? :confused:

**Comment by blizzz** [comment]
@hagbartus doh, I am sorry :( Alas, 15 is EOL, I would suggest to upgrade to 16.

**Comment by szaimen** [comment]
Fixed in new NC versions IIRC -> closing.
