### ISSUE TITLE
it shouldn't be possible to create usersid's with spaces in it

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#18868]
### Steps to reproduce
create a userid with spaces in it like: "Max Mustermann"

### Expected behaviour
there should be an error message, that this didn't work.

### Actual behaviour
It just works

### Server configuration

**Operating system:**
Ubuntu 18.03 LTS
**Web server:**
Apache
**Database:**
Pgsql
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
Nextcloud VM

While investigating possible testscenarios and userid's for https://github.com/nextcloud/vm/pull/1030, we experienced, that this is possible, but it shouldn't, because e.g. Federation wouldn't work. Also when logging in with that user, this happens:
![image](https://user-images.githubusercontent.com/42591237/72279616-cc2f3080-3636-11ea-8e9d-00ab7c9d7a77.png)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/18855

**Comment by enoch85** [comment]
Closing as duplicate.
