### ISSUE TITLE
Clicking on audio files that are playing pauses and resumes playback instead of playing from the beginning of the file

### ISSUE THREAD

**Issue by synthead** [nextcloud/server#18872]
When music is playing, clicking the currently-playing song pauses playback.  This is confusing in a UX perspective as I'd expect the player to play the song from the beginning.

### Steps to reproduce
1. Click an audio file to begin playing it.
2. Click on the audio file again.
3. Observe that the audio is paused instead of playing from the beginning of the file.

### Expected behaviour
The audio should start from the beginning.

### Actual behaviour
The audio playback is paused.

### Server configuration

**Operating system:** Arch Linux

**Web server:** Nginx 1.17.4

**Database:** PostgreSQL 11.5

**PHP version:** 7.3.10

**Nextcloud version:** (see Nextcloud admin page) 17.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Older version (via `pacman -Syu`)

**Where did you install Nextcloud from:** Arch Linux community repo (via `pacman`)

**Comment by kesselb** [comment]
Thanks for reporting a issue :+1: 

Are you using the music or audioplayer app perhaps? 

https://apps.nextcloud.com/apps/music
https://apps.nextcloud.com/apps/audioplayer
