### ISSUE TITLE
 I entered the right DB infomation but got an Access Denied error, and there seams a bug on adepting to new version of mariaDB.

### ISSUE THREAD

**Issue by fineTu** [nextcloud/server#18876]
I'm new in NextCloud , I use a RaspBerry Pi to install NextCloud with docker image, it's all works well until I got the Install Wizard, I entered the right DB infomation but got an Access Denied error.

> SQLSTATE[HY000] [1045] Access denied for user 'oc_finetu'@'172.17.0.2' (using password: YES)
 
 then I found code at /server/lib/private/Setup/MySQL.php

```

	private function createDBUser($connection) {
		try{
			$name = $this->dbUser;
			$password = $this->dbPassword;
			// we need to create 2 accounts, one for global use and one for local user. if we don't specify the local one,
			// the anonymous user would take precedence when there is one.
			$query = "CREATE USER '$name'@'localhost' IDENTIFIED WITH mysql_native_password BY '$password'";
			$connection->executeUpdate($query);
			$query = "CREATE USER '$name'@'%' IDENTIFIED WITH mysql_native_password BY '$password'";
			$connection->executeUpdate($query);
		}
		catch (\Exception $ex){
			$this->logger->logException($ex, [
				'message' => 'Database user creation failed.',
				'level' => ILogger::ERROR,
				'app' => 'mysql.setup',
			]);
		}
	}
```
  
My MariaDB version is 10.3（use apt-get）, when I run the sql manually I got an :

> 1064 - You have an error in your SQL syntax; check the manual that corresponds to your MariaDB 
server version for the right syntax to use near 'by 'gklifg123'' at line 1
  
  Then I saw the docs of mariadb,on this page:
(https://mariadb.com/kb/en/create-user/#identified-viawith-authentication_plugin)
  
Accrodding to the docs, mariadb has no longger support "IDENTIFIED WITH ... BY ... ", and instead by "IDENTIFIED WITH|VIA ... USING|AS ..."
  So I think there could be a bug here, please check out it, thanks.

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/server/issues/18513

**Comment by fineTu** [comment]
yeah，thanks for reply.
