### ISSUE TITLE
ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/cloud.vee.net/html/apps/user_ldap/lib/LDAP.php#74

### ISSUE THREAD

**Issue by mjog** [nextcloud/server#18889]
I'm getting the following constantly spamming my logs after enabling LDAP support:

```
ldap_control_paged_result_response(): Result is: No such object (32) at /var/www/cloud.vee.net/html/apps/user_ldap/lib/LDAP.php#74
```

Everything seems to be mostly working fine however - users show up and can log in, however I can't delete LDAP users and I'm seeing this issue as well: https://help.nextcloud.com/t/get-internal-server-error-when-a-user-first-logs-in/67743/2 (although that may be unrelated).

Nextcloud v17.0.2
LDAP user and group backend v1.7.0
OpenLDAP v2.4.47

Happy to provide any other details you need.

**Comment by kesselb** [comment]
cc @blizzz

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
