### ISSUE TITLE
Use callForSeenUsers where possible

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1889]
- once #1888 is in we should re-evaluate following occurences:

<img width="793" alt="bildschirmfoto 2016-10-24 um 17 28 05" src="https://cloud.githubusercontent.com/assets/245432/19652051/a9697482-9a0f-11e6-934a-04d014e2cef1.png">

cc @nickvergessen @rullzer @icewind1991

**Comment by nickvergessen** [comment]
The method will be 11+ I assume?

**Comment by MorrisJobke** [comment]
> The method will be 11+ I assume?

yes

**Comment by rullzer** [comment]
I think this is done. The two remaining calls seems to really want to iterate over all users.
