### ISSUE TITLE
App token - LDAP - password change

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/server#18891]
### Steps to reproduce
1. Create app token for WebDAV connection or login to sync client 2.6.2
2. Change password in Active Directory

### Expected behaviour
App tokens still will works, even password has been changed

### Actual behaviour
App tokens stopped working

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:**  nginx-1.16.1

**Database:** MariaDB 10.4.11

**PHP version:** 7.3.13

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

Could you help me with this please?

**Comment by go2sh** [comment]
See https://docs.nextcloud.com/server/17/user_manual/session_management.html . The tokens should be update by a new login with password.

**Comment by PiotrIr** [comment]
Hi do2sh,
Thank you for your reply. 
I've just tested and it doesn't work unfortunately. I mean, once I've changed password in active directory, login to website using new password (and token - I have 2FA enabled), the old app token for webdav and sync client doesn't work. I have to create new one.

**Comment by violoncelloCH** [comment]
sounds related to #18923

**Comment by PiotrIr** [comment]
Hi violoncello.ch,
Yes, you are correct - this is about the same issue. Hover in this post I didn't know default behavior so I've logged second one just to make it more clear.

**Comment by kesselb** [comment]
Would you mind to close one of the issues and update the initial post? Two issues for the same problem / question is not helpful. Thanks 👍

**Comment by PiotrIr** [comment]
Hi kesselb - sure, no problem. I will close this one and leave the other open.
