### ISSUE TITLE
unload retriggers before unload

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#18890]
https://github.com/nextcloud/server/blame/27dc4ef268722f525b3ce1f1fe72f0b17531ad6a/apps/files/js/filelist.js#L3792-L3794

It is causing problems for talk, because the "You are in a call, do you really want to leave" warning is shown twice.

From the blame the line is added 7 years ago for opera.... So I guess we can delete it.

cc @juliushaertl @skjnldsv @georgehrke

**Comment by skjnldsv** [comment]
I guess?
