### ISSUE TITLE
Unexpected handling of share password

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#18893]
1. Create a public link for an item
2. Tick the "Password protect"
![Bildschirmfoto von 2020-01-14 14-48-26](https://user-images.githubusercontent.com/213943/72349676-4619f500-36dd-11ea-8462-52f3ba021551.png)
3. Tick expiration date or video verification
4. It looks like the password is set
![Bildschirmfoto von 2020-01-14 14-48-33](https://user-images.githubusercontent.com/213943/72349677-46b28b80-36dd-11ea-94ed-ed885817f4e7.png)
5. Close and reopen the drop down
6. It still looks the same
7. Access the link you are not asked for a password
8. Reload the share setting page
9. The link has no password set

cc @skjnldsv

**Comment by j-ed** [comment]
I can confirm that behavior with Nextcloud 18.0.1 and Talk 8.0.4 and Firefox 73.0. As soon as I check the "Video Verification" checkbox, a "**Error updating the share**" message is shown on the screen.

![20200214_nc_video_verification](https://user-images.githubusercontent.com/2572764/74541478-f465c400-4f41-11ea-942b-382b32a0f257.png)

An other user has also reported the described behavior:

https://help.nextcloud.com/t/switching-on-the-video-verification-fails-and-leads-to-the-failure-of-the-password-protection/71120/6

**Comment by Ethendrel** [comment]
I am also having issues with this on 2 seperate nextcloud instances runnung 18.0 and 18.0.1.
When trying to set a password for a shared link:
1. when using the default suggested password it looks like the password is set and when accessing i get asked for the passowrd, but when using this password i get the message that the password is wrong.
2. when trying to set a custom password i get the same result as j-ed, "Error updating the share"

**Comment by skjnldsv** [comment]
@Ethendrel could you give us the error from the console?
It would help us narrow it. It should display the password error message though, this was design to.

Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by kesselb** [comment]
Seems to be similar to: https://github.com/nextcloud/server/issues/19525, https://github.com/nextcloud/server/issues/19675

**Comment by linuxuser424** [comment]
I have this error on a Nextcloud 18.0.4. 
If I click on "allow edit" the same error "Error updating the share" is shown. "forced password" is on or off - no impact.

screenshot console:
![screen](https://user-images.githubusercontent.com/48769262/80364732-b01e6a80-8886-11ea-8aac-07a2e62a6e57.gif)

I don't see any corresponding log in error.log or access.log. There is no "error 400" in these files.
Any ideas?

**Comment by skjnldsv** [comment]
@linuxuser424 I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

**Comment by linuxuser424** [comment]
Thanks, here is the screenshot:

![screen2](https://user-images.githubusercontent.com/48769262/80366442-8f0b4900-8889-11ea-955c-7d5929d9d8bf.gif)

**Comment by skjnldsv** [comment]
Please click the 400 failing request (bottom), select the repsonse tab, and copy/paste the results here

**Comment by linuxuser424** [comment]
Thank you, there is this message:

`{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Public upload is not allowed"},"data":[]}}`

Yes, public upload is not allowed. I thought public means everyone can upload (even without password).
But if I enable password-protection this would not be public, so this config-option may be confusing.

The [documentation](https://docs.nextcloud.com/server/18/admin_manual/configuration_files/file_sharing_configuration.html) says "Check 'Allow public uploads' to allow anyone to upload files to public shares." 
Well, anyone should not be enabled to upload - only someone with the correct password or account ;-)

Maybe it is just me and my understanding:
If I look at the config options and documentation, it is not clear for me: are these options "and" (cumulative) or are they "or" (exclusive, first match is taken: then would the password be ignored).

Nevertheless: After activating "pulic upload" in options, I can save the files sharing option successfully. **Thank you very much.**

**Comment by skjnldsv** [comment]
I think this is not about the password.
Can you screenshot the sharing menu (where you enter the password) ?
So I can have a look at what you're selecting?

![Capture d’écran_2020-04-27_14-44-00](https://user-images.githubusercontent.com/14975046/80373568-8caeec00-8895-11ea-8972-cbb4ece18506.png)
Were you selecting one of the two last permissions? (upload+edit or uploadonly) ?

**Comment by linuxuser424** [comment]
Yes, you are right: is not about the password (as I said above). This config option (as administrator):

![screen4](https://user-images.githubusercontent.com/48769262/80374793-891c6480-8897-11ea-8dd0-4de6572c1f6e.gif)

If this option is activated, i can save with this sharing menu - with and without password.

![screen3](https://user-images.githubusercontent.com/48769262/80374944-be28b700-8897-11ea-886a-1850787e3528.gif)

**Comment by skjnldsv** [comment]
> Only if this option is activated, i can save with this sharing menu - with and without password (with deactivated forced password above).

You're not doing this on a folder, but on a single file?

**Comment by linuxuser424** [comment]
> You're not doing this on a folder, but on a single file?

My screenshots are from a single file. Just tested: it makes no difference file/directory. If the admin-option "allow public uploads" is **not** active, there comes the error "Error updating the share".

**Comment by skjnldsv** [comment]
Can you open a new issue with all those data please? :)

**Comment by linuxuser424** [comment]
> Can you open a new issue with all those data please? :)

I think the issue is solved - or is just a documentation issue.
Why not reopen this one? So it is clear, I was not the only one with this configuration.

**Comment by skjnldsv** [comment]
Because yours is different. You shouldn't have to enable the allow upload for it to work. We should allow link shares without upload allowed.
And let me add that upload permissions only make sense to folder, as you cannot upload into a file. Permissions are different :)
