### ISSUE TITLE
Hide hidden files from UI

### ISSUE THREAD

**Issue by tkuther** [nextcloud/server#189]
It would be nice to have a simple toggle in the Files app's settings panel that allows to show/hide hidden files. I know, they are greyed out, but it would be nice to have an option to not show them at all, like actually hiding the already hidden files.

Old ref https://github.com/owncloud/core/issues/2589 - sounds so simple.

**Comment by LukasReschke** [comment]
That is implemented in 10.0

**Comment by tkuther** [comment]
Perfect! Thanks!
