### ISSUE TITLE
Add "Folder on top" option to sort

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#18905]
- [x] iOS
- [x] desktop (cannot do it)
- [ ] Android @tobiasKaminsky 
- [ ] Server @nextcloud/server-triage 

- add option to sorting dialog to "Sort folders on top"
- global option
- check box to indicate that it is enabled
- default: disabled (like now) @marinofaggiana is this also the default on iOS?
- positioning: 
  - server: bottom left in option menu
  - Android: at bottom in sorting menu

![IMG_8892](https://user-images.githubusercontent.com/5836855/72423539-bd569400-3784-11ea-9701-ae7f0546b54a.PNG)

**Comment by jancborchardt** [comment]
Closing in favor of https://github.com/nextcloud/server/issues/24190 since we have more info there. :)
