### ISSUE TITLE
Breadcrumbs grouping does not work, causes horizontal scrollbar

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#18916]
Vintage issue https://github.com/nextcloud/server/issues/11520 happening again @skjnldsv @danxuliu @juliushaertl @GretaD 

![Breadcrumbs grouping broken](https://user-images.githubusercontent.com/925062/72479132-d4809a80-37f3-11ea-97c3-0317b9e3ba59.png)

**Comment by GretaD** [comment]
This only happens on Firefox :/

Looks like if we add 
app-files #app-content 
`overflow-x: hidden;` 
and we remove 
`top:50px;` from #controls 

fixes the problem. @skjnldsv @danxuliu is this a good idea to fix this issue?

**Comment by skjnldsv** [comment]
I have no idea.
To be honest we allowed us to touch the files app too much on the lasts releases.
I'm afraid to touch it again. :/

**Comment by blizzz** [comment]
Clearing the milestone. Still an issue?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
