### ISSUE TITLE
[Feature Request] php occ trashbin:restore

### ISSUE THREAD

**Issue by Sour4pple** [nextcloud/server#18921]
Hey there!

I am dealing with customers, who sometimes delete files on their Nextcloud in huge quantities by accident. Restoring thousands of files through the webgui is pretty tedious. I know, you can select all files, but still it doesn't work clean for so many files, since it brings the web interface to it's limit (in my experience).

Now my suggestions would be to add a command line option to solve this easier in the future. Personally I'd add the option restore to the existing php occ trashbin command. Some useful arguments to define would probably be usernames to locate the correct trashbin and a verbose option.

Thanks for your work.

Best regards,
Tim

**Comment by alejandroscf** [comment]
That would be a great option. I just had to restore a backup from the previous day because with the webui was impossible.

**Comment by bseclier** [comment]
It would be a great feature, indeed !

**Comment by matthias-mo** [comment]
Just ran into this exact problem: coleague deleted lots of files (right now unknown) and I need to restore them. I know the user, who deleted the files and I know the time when it happened.

Right now, having an occ command to restore them with 1 line would be a god sent

**Comment by benoitlavorata** [comment]
I have the same issue on a server for a customer. The webUI is just too slow to restore all these files.
As I did not find any commands to restore the whole trashbin for a given timeframe, I made a snippet in Chrome to automate the click on "restore" for all the files deleted for a given period.

Definitely not perfect, but hopefully it can help someone.
Just change the dates in the function call at the bottom of the snippet.
You must be on the trashbin page, logged in with the user you want to restore files for.
Use at your own risks - this is only meant to help other admins with the same issues.

```js
let restoreFiles = async function(startDate, endDate, index=0) {
    let sleep = async function(timer) {
        return new Promise(res=>{
            setTimeout(()=>{
                res(true)
            }
            , timer)
        }
        )
    }

    let restoreBtns = $('.action-restore')
    let start = moment(startDate)
    let end = moment(endDate)

    for (var i = 0; i < restoreBtns.length; i++) {

        let btn = $(restoreBtns[i])
        let section = btn.parent().parent().parent()
        let tr = section.parent()

        let path = tr.attr('data-path')
        let file = tr.attr('data-file')
        let mtime = tr.attr('data-mtime')

        if (!mtime)
            continue;

        let mMoment = moment(parseInt(mtime))
        if (!(mMoment.isBefore(end) && mMoment.isAfter(start)))
            continue;

        console.log(`Restore: ${path}`)
        await sleep(1000)
        btn.click();
    }

    $("html, body").animate({
        scrollTop: $(document).height()
    }, 1000);
    return restoreFiles(startDate, endDate, index + 1)
}

clear();
restoreFiles('2020-12-13', '2020-12-16').then().catch()
```

**Comment by jabdoa2** [comment]
As I have been hit by https://github.com/nextcloud/desktop/issues/260 as well this would be useful to me too.

**Comment by szaimen** [comment]
Currently no one is working on this one, so it would be great if someone of you could open a PR to implement this :)

**Comment by martijnvandijk** [comment]
You, @benoitlavorata just helped me out big time with your snippet! Thank you _so_ much for sharing.

**Comment by Tie-fighter** [comment]
I need this so badly after my desktop client decided to mark files as deleted instead of freeing up disk space 😅
