### ISSUE TITLE
Convert files with Pandoc

### ISSUE THREAD

**Issue by reavessm** [nextcloud/server#18938]
I think it would be nice to generate HTML/DOCX/PDFs from markdown files in Nextcloud.  If we can do video conversion, document conversion shouldn't be too hard.

Also, there appears to already be a [Pandoc PHP wrapper](https://github.com/ryakad/pandoc-php).

**Comment by kesselb** [comment]
Probably a app for flow? 

cc @blizzz @juliushaertl

**Comment by juliushaertl** [comment]
Yes, this is a nice use-case for an individual app that integrates with Flow. The right place to post this would be https://help.nextcloud.com/c/feature/app-ideas
