### ISSUE TITLE
[Docker - Synology]: Cannot write into "config" directory displayed even when "config_is_read_only" is set to true.

### ISSUE THREAD

**Issue by Warlord1390** [nextcloud/server#18943]
Having an issue where after the Docker deployment on my Synology updated the nextcloud instance it is complaining about not being able to write the config.php though I have the config_is_read_only set to true.

**Comment by doronbehar** [comment]
I'm having the same issue with version 18 and on Arch Linux. I tried setting it to read_only and then refresh but I got the error:

> Cannot write into "apps" directory
> This can usually be fixed by giving the webserver write access to the apps directory or disabling the appstore in the config file. See https://docs.nextcloud.com/server/18/go.php?to=admin-dir_permissions

My nginx error log and access.log don't point out anything suspicious.

I've checked a hundred times that the permissions are set right for `http:http`. My `php-fpm.d/www.conf` has:

```
listen.owner = http
listen.group = http
# ...
listen.acl_users = http
listen.acl_groups = http
```

No idea at all what's wrong with my setup which was completely fine up until version 18.0 :disappointed: .

**Comment by kesselb** [comment]
@doronbehar https://github.com/nextcloud/server/issues/18943 maybe?

**Comment by doronbehar** [comment]
@kesselb the current issue is https://github.com/nextcloud/server/issues/18943 .

**Comment by kesselb** [comment]
@doronbehar then maybe https://github.com/nextcloud/server/issues/18978 ;)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
