### ISSUE TITLE
Sharing backend for principals not found /ldap

### ISSUE THREAD

**Issue by k4tfish** [nextcloud/server#1895]
I cannot share calenders with AD users. While searching for a contact to share, the app doesn't show any users.

The following appears in the log: "Sharing backend for principals not found"

There was a similar issue in the oc calender app. https://github.com/owncloud/core/issues/23827

-- k4tfish - calendar 1.4.0 /NC 10.0.1 / Ubuntu 16.04 / Apache

**Comment by nickvergessen** [comment]
@blizzz any idea?

**Comment by blizzz** [comment]
Works for me, although the user ids are shown instead of the display names, when sharing. cc @georgehrke 

@k4tfish can you please give a complete bug report using the [template](https://github.com/nextcloud/server/blob/master/.github/issue_template.md)? thx 

Github returns a 404 on the linked issue.

**Comment by georgehrke** [comment]
> Works for me, although the user ids are shown instead of the display names, when sharing. cc @georgehrke

Yes, working on that

**Comment by k4tfish** [comment]
@blizzz, 
the correct link to the owncloud issue.
https://github.com/owncloud/core/issues/23827

### Steps to reproduce
Sharing of a cal or folder using the web ui. 

### Expected behaviour
Showing the users/groups to select them.

### Actual behaviour
It can't find any user usually but worked sometimes. Then the calapp shows the SAMaccount name, 
whereas the fileapp shows the display name. 

### Server configuration
Ubuntu 16.04. Apache/2.4.18, MariaDB 10.0.27. mod-php 7.0.8. Nextcloud 10.0.1
Fresh install from 10.0.1 tarball, no other issues so far. 

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - activity: 2.3.2
  - apporder: 0.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - logreader: 1.1.5
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - passwords: 19
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - mail
  - user_external
  - user_saml
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "instanceid": "ockdzcqsvo3v",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.dc.local",
            "nextcloud.x",
            "10.200.125.230"
        ],
        "datadirectory": "\/var\/ncdata",
        "overwrite.cli.url": "\/",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "appstore.experimental.enabled": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "loglevel": 3,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "localhost",
            "port": 6379
        },
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "xxx",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "PLAIN",
        "mail_smtphost": "xxxx",
        "mail_smtpport": "25",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP/ActiveDirector
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
| Configuration                 | s02                                                                                                                                     |
+-------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                       |
| hasPagedResultSupport         |                                                                                                                                         |
| homeFolderNamingRule          |                                                                                                                                         |
| lastJpegPhotoLookup           | 0                                                                                                                                       |
| ldapAgentName                 | CN=ncADuser,CN=Users,DC=xxx-xxx                                                                                            |
| ldapAgentPassword             | ***                                                                                                                                     |
| ldapAttributesForGroupSearch  |                                                                                                                                         |
| ldapAttributesForUserSearch   |                                                                                                                                         |
| ldapBackupHost                |                                                                                                                                         |
| ldapBackupPort                |                                                                                                                                         |
| ldapBase                      | DC=xxx-xxx                                                                                                                  |
| ldapBaseGroups                | DC=xxx-xxx                                                                                                                  |
| ldapBaseUsers                 | DC=xxx-xxx                                                                                                                  |
| ldapCacheTTL                  | 600                                                                                                                                     |
| ldapConfigurationActive       | 1                                                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                                                         |
| ldapEmailAttribute            |                                                                                                                                         |
| ldapExperiencedAdmin          | 0                                                                                                                                       |
| ldapExpertUUIDGroupAttr       |                                                                                                                                         |
| ldapExpertUUIDUserAttr        |                                                                                                                                         |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                          |
| ldapGroupDisplayName          | cn                                                                                                                                      |
| ldapGroupFilter               | (|(cn=Mitarbeiter))                                                                                                                     |
| ldapGroupFilterGroups         | Mitarbeiter                                                                                                                             |
| ldapGroupFilterMode           | 0                                                                                                                                       |
| ldapGroupFilterObjectclass    |                                                                                                                                         |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                            |
| ldapHost                      | ldap://xxxx                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                         |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=Mitarbeiter,DC=xxx-xxx (primaryGroupID=1125))))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                         |
| ldapLoginFilterEmail          | 0                                                                                                                                       |
| ldapLoginFilterMode           | 0                                                                                                                                       |
| ldapLoginFilterUsername       | 1                                                                                                                                       |
| ldapNestedGroups              | 0                                                                                                                                       |
| ldapOverrideMainServer        |                                                                                                                                         |
| ldapPagingSize                | 500                                                                                                                                     |
| ldapPort                      | 389                                                                                                                                     |
| ldapQuotaAttribute            |                                                                                                                                         |
| ldapQuotaDefault              |                                                                                                                                         |
| ldapTLS                       | 0                                                                                                                                       |
| ldapUserDisplayName           | displayName                                                                                                                             |
| ldapUserDisplayName2          |                                                                                                                                         |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=Mitarbeiter,CN=Users,DC=xxx-xxx )(primaryGroupID=1125))))                         |
| ldapUserFilterGroups          | Mitarbeiter                                                                                                                             |
| ldapUserFilterMode            | 0                                                                                                                                       |
| ldapUserFilterObjectclass     | person                                                                                                                                  |
| ldapUuidGroupAttribute        | auto                                                                                                                                    |
| ldapUuidUserAttribute         | auto                                                                                                                                    |
| turnOffCertCheck              | 0                                                                                                                                       |
| useMemberOfToDetectMembership | 1                                                                                                                                       |
</details>

### Client configuration
**Browser:**
FF49
**Operating system:**
W7x64
### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>
no errors
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Error	OCP\Share	Sharing backend for principals not found
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Pls let me know which log exactly do you want. 

</details>

**Comment by ggeorgg** [comment]
Same problem for me. Just tried it on a fresh installation but after creating a new calendar with user1 and sharing it with user2 I already get that Error OCP\Share Sharing backend for principals not found.

**Comment by blizzz** [comment]
Perhaps the issue lies somewhere within the dav app part in core, at least that would be a starting point to look at.

**Comment by georgehrke** [comment]
> While searching for a contact to share, the app doesn't show any users.

For querying users and groups we use the endpoint of the files_sharing app?
Is the Sharing API enabled in the admin settings?

**Comment by ggeorgg** [comment]
In my nextcloud admin setting the point "allow apps to use sharing API" (in german) is enabled. 
I have to add, that I am not using ldap and the user with whom I shared the calendar was properly displayed when I entered the first letter of the user.

**Comment by blizzz** [comment]
This exception is thrown in lib/Share/Share::getBackend() instead. If it succeeds sometimes and sometimes not, it sounds a bit of a race condition, but this does not seem likely. Perhaps some initialization mixup, but then it should be consistent for you, still.

 @schiessle do you have an idea?

**Comment by blizzz** [comment]
I'll close it, since there changed a lot inbetween and this issue did not see an updates for almost 2 years. If the issue is still in place, please reopen (or shout out).
