### ISSUE TITLE
Can't remove orphaned external storage mount points

### ISSUE THREAD

**Issue by fredleb** [nextcloud/server#18956]
I fought to get SMB client work and it won.

First it created several mount points even though I wanted only one, but that's not the problem.

The problem is that I removed smbclient from the system and now I can't remove the mount points anymore...

Does not look nice really...

![Screenshot from 2020-01-17 13-58-16](https://user-images.githubusercontent.com/12045231/72614203-f3854680-3931-11ea-99a3-55deb9033c6a.png)

I'm using 17.0.2.

I guess this is what is causing my "A HTTP transmission error happened. The server file discovery reply is missing data." in the client...

**Comment by szaimen** [comment]
Hi there, did you use the correct section in the admin settings?
![image](https://user-images.githubusercontent.com/42591237/123426026-2a4d9a80-d5c3-11eb-95cf-3a74b1bc6362.png)
