### ISSUE TITLE
New installation with SMBClient as data path and error chmod 0770 even with nextcloud version 18

### ISSUE THREAD

**Issue by GentleRV** [nextcloud/server#18951]
Goodday all !!

After a installation on a virtual Ubuntu 18.04 machine hosted on a windows 2012 server I received the this error:
    Your data directory is readable by other users
    Please change the permissions to 0770 so that the directory cannot be listed by other users.

What I did:
On the windows host server shared a folder with full rights for one user only
Installed Ubuntu 18.04
updated all files
installed smbclient with cifs-utils and made a line in fstab in where filemode=0777 and dirmode=0777 is used together with the right user and password (same as in the windows system.
Testing give me that I can read, write and delete on the ceated Ubuntu /media/share.
after installing mariadb (version 10.1) and the nextcloud (version 17.0.2) software I received the first log-in screen from nextcloud, after enter all information i received the above mentioned message.
After changing the dirmode to 0770 apache2 only displays text saying the server was not configured properly, changing back to dirmode=0777 I got the text back

How I can continue the installation and avoid getting this message?
PS  I thought this error was already solved as it is mentioned many times searching on internet

Greetings

**Comment by szaimen** [comment]
i think the options are `file_mode` and `dir_mode`
probably you have to configure addditinally the linux user.
in your case probably www-data. you can get the id by `id www-data`
then you have to add the uid and gid this as aditional option to the fstab entry

**Comment by GentleRV** [comment]
@ szaimen,
Thanks for your answer, although it did not help
You are right for the dir_mode and file_mode, both were typed well in the fstab file
After changing the dir_mode to 0770, I added the uid and gid for the user and restarted the mount procces, the presented web page from nextcloud contained only characters, after changing the dir_mode to 0777 I got the page back with the error to change to 0770.
Then I changed again to dir_mode 0770 and added the uid and gid from www-data wgich did give me the same results as the user uid and gid.

It seems that only dir_mode is the trigger for this error.

**Comment by GentleRV** [comment]
Just now I updated nextcloud to version 18 and PHP to version 7.4 and still get this:
    Your data directory is readable by other users

    Please change the permissions to 0770 so that the directory cannot be listed by other users.

Please Please Please remove this sentence and continue the installation

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
