### ISSUE TITLE
Retention and Files automated tagging are enabled but can't be configured in Settings

### ISSUE THREAD

**Issue by chrissi55** [nextcloud/server#18957]
### Steps to reproduce
1. Install Retention and Files automated tagging
2. try to find the settings page of both in admin -> settings page
3. no entry 

### Expected behaviour
Tell us what should happen
I enabled both apps and want to configure them but in whole settings area i can't find the settings pages for them

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:** ubuntu-server 18.04.3

**Web server:** nginx 1.17.4

**Database:** PostgreSQL 12.1

**PHP version:** 7.3.13

**Nextcloud version:** (see Nextcloud admin page) 17.0.2.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 11.x .... 16.x

**Where did you install Nextcloud from:** local installation on the server via ssh connection
loaded the updates via Updater in Nextcloud (by admin account)

**Signing status:**No errors have been found.
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
```

> Enabled:
>   - accessibility: 1.3.0
>   - activity: 2.10.1
>   - admin_audit: 1.7.0
>   - bruteforcesettings: 1.4.0
>   - calendar: 2.0.0
>   - cloud_federation_api: 1.0.0
>   - comments: 1.7.0
>   - contacts: 3.1.6
>   - dav: 1.13.0
>   - federatedfilesharing: 1.7.0
>   - federation: 1.7.0
>   - files: 1.12.0
>   - files_accesscontrol: 1.7.0
>   - files_automatedtagging: 1.7.0
>   - files_downloadactivity: 1.6.0
>   - files_external: 1.8.0
>   - files_pdfviewer: 1.6.0
>   - files_retention: 1.6.0
>   - files_rightclick: 0.15.1
>   - files_sharing: 1.9.0
>   - files_trashbin: 1.7.0
>   - files_versions: 1.10.0
>   - files_videoplayer: 1.6.0
>   - gallery: 18.4.0
>   - groupfolders: 5.0.5
>   - logreader: 2.2.0
>   - lookup_server_connector: 1.5.0
>   - nextcloud_announcements: 1.6.0
>   - notifications: 2.5.0
>   - oauth2: 1.5.0
>   - onlyoffice: 4.1.1
>   - password_policy: 1.7.0
>   - privacy: 1.1.0
>   - provisioning_api: 1.7.0
>   - rainloop: 6.0.4
>   - recommendations: 0.5.0
>   - serverinfo: 1.7.0
>   - sharebymail: 1.7.0
>   - spreed: 7.0.2
>   - support: 1.0.1
>   - systemtags: 1.7.0
>   - tasks: 0.11.3
>   - text: 1.1.1
>   - theming: 1.8.0
>   - twofactor_backupcodes: 1.6.0
>   - twofactor_totp: 4.1.2
>   - updatenotification: 1.7.0
>   - user_ldap: 1.7.0
>   - viewer: 1.2.0
>   - workflowengine: 1.7.0
> Disabled:
>   - encryption
>   - firstrunwizard
>   - survey_client

```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

```

> {
>     "system": {
>         "instanceid": "***REMOVED SENSITIVE VALUE***",
>         "passwordsalt": "***REMOVED SENSITIVE VALUE***",
>         "secret": "***REMOVED SENSITIVE VALUE***",
>         "trusted_domains": [
>             "my.domain.com",
>             "local-IP"
>         ],
>         "activity_expire_days": 14,
>         "auth.bruteforce.protection.enabled": "false",
>         "blacklisted_files": [
>             ".htaccess",
>             "Thumbs.db",
>             "thumbs.db"
>         ],
>         "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
>         "overwritehost": "my.domain.com",
>         "overwriteconaddr": "^IP1\\.IP2\\.IP3\\.IP4$",
>         "forward_for_headers": [
>             "X_FORWARDED_FOR",
>             "HTTP_X_FORWARDED_FOR"
>         ],
>         "datadirectory": "***REMOVED SENSITIVE VALUE***",
>         "overwriteprotocol": "https",
>         "overwrite.cli.url": "https:\/\/my.domain.com",
>         "dbtype": "pgsql",
>         "version": "17.0.2.1",
>         "dbname": "***REMOVED SENSITIVE VALUE***",
>         "dbhost": "***REMOVED SENSITIVE VALUE***",
>         "dbport": "",
>         "dbtableprefix": "oc_",
>         "dbuser": "***REMOVED SENSITIVE VALUE***",
>         "dbpassword": "***REMOVED SENSITIVE VALUE***",
>         "htaccess.RewriteBase": "\/",
>         "logtimezone": "Europe\/Berlin",
>         "logfile": "\/media\/cloud\/data\/nextcloud.log",
>         "log_rotate_size": 10485760,
>         "cron_log": true,
>         "installed": true,
>         "filesystem_check_changes": 0,
>         "quota_include_external_storage": false,
>         "skeletondirectory": "",
>         "share_folder": "\/Shares",
>         "knowledgebaseenabled": false,
>         "ldapIgnoreNamingRules": false,
>         "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
>         "ldapUserCleanupInterval": 20,
>         "memcache.local": "\\OC\\Memcache\\Redis",
>         "filelocking.enabled": "true",
>         "memcache.locking": "\\OC\\Memcache\\Redis",
>         "redis": {
>             "host": "***REMOVED SENSITIVE VALUE***",
>             "port": 0,
>             "timeout": 0,
>             "password": "***REMOVED SENSITIVE VALUE***"
>         },
>         "mail_smtpmode": "smtp",
>         "mail_smtpsecure": "ssl",
>         "mail_from_address": "***REMOVED SENSITIVE VALUE***",
>         "mail_domain": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
>         "mail_smtpport": "465",
>         "maintenance": false,
>         "integrity.check.disabled": false,
>         "updater.release.channel": "stable",
>         "enable_previews": true,
>         "enabledPreviewProviders": [
>             "OC\\Preview\\PNG",
>             "OC\\Preview\\JPEG",
>             "OC\\Preview\\GIF",
>             "OC\\Preview\\BMP",
>             "OC\\Preview\\XBitmap",
>             "OC\\Preview\\Movie",
>             "OC\\Preview\\PDF",
>             "OC\\Preview\\MP3",
>             "OC\\Preview\\TXT",
>             "OC\\Preview\\MarkDown"
>         ],
>         "preview_max_x": 1024,
>         "preview_max_y": 768,
>         "preview_max_scale_factor": 1,
>         "trashbin_retention_obligation": "auto, 2",
>         "loglevel": 2,
>         "mail_sendmailmode": "smtp"
>     }
> }

```

**Are you using external storage, if yes which one:** local/smb/sftp/... local 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Firefox ESR 68.4

**Operating system:** ZorinOS 15.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Retention app seems to use workflow section. That should be Tag Management then.

**Comment by chrissi55** [comment]
I updated from 17.0.3 to 18.0.1
I'm at the moment not able to add, edit nor delete tags.
Also it isn't possible to tag files / folders manually because the Button behind the three dots "tags" does nothing when clicking on it.

The section "Flow" is there in settings but also here no possibility to edit tags nor editing existing rules for automated tagging / retention!!

I already did the following after occ upgrade

sudo -u www-data php occ maintenance:mode --on
sudo -u www-data php occ upgrade
sudo -u www-data php occ db:add-missing-indices
sudo -u www-data php occ db:convert-filecache-bigint
sudo -u www-data php occ maintenance:mimetype:update-js
sudo -u www-data php occ maintenance:mimetype:update-db
sudo -u www-data php occ maintenance:theme:update
sudo -u www-data php occ maintenance:update:htaccess
sudo -u www-data php occ maintenance:repair
sudo -u www-data php occ maintenance:mode --off

(www-data is my ubuntu nextcloud system user)

**Comment by chrissi55** [comment]
Update 16.02.2020
I decided to go back to PHP 7.3.14 and did a fullscan (occ files:scan --all) after disabling and removing the files_automatedtagging app completely.

There were many errors during scan that broke the process and makes it impossible to properly scan all files.

with PHP 7.3 enabled, still using Nextcloud 18.0.1 and deleted autotagging app i still can't manually tag my files or folders because the "Tag - Button" in Details Page is functionless.
Thinking of PopUp Blockers e.g. i switched to a windows machine and did the same with M$ Edge Browser -> same here.

So there is definitely a problem with tagging files/folders in NC 18

In other posts a user reported that he is using PostgreSQL instead of MariaDB / MySQL - so as i use PGSQL
But definitely i used it under NC 17.0.3 as well and never had problems to manually tagging my files.
So must be DB independant problem i think.

**Comment by chrissi55** [comment]
source from nextcloud forums:

> When I removed the talk app (version 8.0.4) tags are working again.
> You have the talk app installed?

So i tested this and it is as the user said. The Talk App is responsible for the disfunction of tagging files manually!!!
