### ISSUE TITLE
developer manual page not found in readme.md

### ISSUE THREAD

**Issue by dumasss163** [nextcloud/server#18952]
### Steps to reproduce
1. click the link in readme https://docs.nextcloud.com/server/latest/developer_manual/general/devenv.html, got a page not found error

### Expected behaviour
should show the page

### Actual behaviour
not found

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure

**Comment by MaSven** [comment]
This is for every version of the documentation currently. 
https://docs.nextcloud.com is working as intended but every other link on this page is not working.

**Comment by tcitworld** [comment]
It's the whole dev docs for 18 that are missing.

**Comment by Scarfmonster** [comment]
User and Administration manuals are fine, but developer manuals for every single version listed on https://docs.nextcloud.com/ are missing.

**Comment by rullzer** [comment]
Yes. We noticed as well. It seems that a depencency upgrade failed here to generate the dev docs. We'll make sure they are back asap.

**Comment by J0WI** [comment]
Duplicate of https://github.com/nextcloud/documentation/issues/1782
