### ISSUE TITLE
Countdown on website not accounting for timezone?

### ISSUE THREAD

**Issue by dbolton** [nextcloud/server#18962]
The countdown at https://nextcloud.com/countdown/ shows almost 3 hours till the big reveal, yet the blog post seems to indicate that the keynote already happened: https://nextcloud.com/blog/the-new-standard-in-on-premises-team-collaboration-nextcloud-hub/

Am I correct in guessing that the website countdown didn't factor in time zones? Or is the big reveal still to happen?

**Comment by georgehrke** [comment]
> Am I correct in guessing that the website countdown didn't factor in time zones?

Yes 

And please only use this bug tracker only for bugs in the Nextcloud server software. Thx

**Comment by dbolton** [comment]
Where's the correct place for reporting website bugs?

**Comment by georgehrke** [comment]
In the website repository: https://github.com/nextcloud/nextcloud.com
