### ISSUE TITLE
Files drop: don’t show avatar placeholder if no avatar is present

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1896]
For the file upload without file listing, we show the avatar nice and big. And that is cool.

However – when the sharer has no avatar set, it will show the giant circled first letter. This is rather useless and just takes attention away from the upload button.

If no avatar is set, the element should simply not be shown.

cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
@stephanruttloff Maybe also something for you 😉

**Comment by MorrisJobke** [comment]
Fix is in #4609

**Comment by MorrisJobke** [comment]
There are many votes against it in #4609 - I will close this one here as well, because I also doesn't like it. 👎

**Comment by jancborchardt** [comment]
Yeah, seems to be better even if it’s only a placeholder. Good on testing it out so we know it’s better like it already is! :)
