### ISSUE TITLE
 Class 'OCA\Onlyoffice\AppConfig' not found

### ISSUE THREAD

**Issue by flozi00** [nextcloud/server#18975]
After installation of clean nextcloud server on Apache Webserver I got two errors in the logs while opening .doc file.
1. Class 'OCA\Onlyoffice\AppConfig' not found

Second is already known and can be fixed with giving permissions to execute.
I can't find any fix for the first error

**Comment by kesselb** [comment]
https://github.com/nextcloud/documentserver_community/issues/8
