### ISSUE TITLE
Update error: Update to version 18

### ISSUE THREAD

**Issue by rubensutter** [nextcloud/server#18972]
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `o`.`id` FROM `oc_flow_operations` `o` LEFT JOIN `oc_flow_operations_scope` `s` ON `o`.`id` = `s`.`operation_id` WHERE `s`.`operation_id` IS NULL': SQLSTATE[42S02]: Base table or view not found: 1146 Table '-xxx-_-xxx-.oc_flow_operations_scope' doesn't exist

An Error Message appears and the nextcloud installation suddenly stopped working with no sync/access to files via client and no access/login via browser:

Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Populating added database structures for workflows
...
Das Update ist fehlgeschlagen.

(updated from latest version Version 17.0.2 December 20 2019)

**Comment by kesselb** [comment]
Thanks for reporting a problem :+1: 

Please use the search before opening a new issue. There is always a chance that a issue has been reported earlier and probably a workaround / solution is available.

https://github.com/nextcloud/server/issues/18265 should help you.
