### ISSUE TITLE
Allow Subfolders for External Storage

### ISSUE THREAD

**Issue by JokerGermany** [nextcloud/server#18977]
I mounted several folders to nextcloud
pictures
movies
music

It is a mess, that the directorys appear in the main directory of the user.
It would be great if i could specify a pathname. for example 
NAS/pictures 
NAS/movies
NAS/music
In the Main Directory of the User (and the external files directory) now appears a folder called NAS in which are 3 subfolders.

**Comment by da3dsoul** [comment]
I don't have this issue. I add /media/da3dsoul/Golias where Golias is the external folder. It shows up as /Golias/...contents as you'd expect.

**Comment by JokerGermany** [comment]
> I don't have this issue. I add /media/da3dsoul/Golias where Golias is the external folder. It shows up as /Golias/...contents as you'd expect.

pictures has other permissions then movies and music.
I can not add NAS because i need different permissions.

**Comment by szaimen** [comment]
This feature is already implemented and works, afaik.

**Comment by szaimen** [comment]
> NAS/pictures
> NAS/movies
> NAS/music

Just name them
```
/NAS/pictures
/NAS/movies
/NAS/music
```
and it should work.
(You might need to add a folder that is called NAS to your root folder before you do that, though.)

**Comment by szaimen** [comment]
Closing as the solution was provided.

**Comment by ristein** [comment]
this does not work for me.
It would be great to be able to move the folder in files-app since different users might want to store it in different subfolders
