### ISSUE TITLE
Datadirectory gets overwritten which poses a problem with fpm's chroot option set

### ISSUE THREAD

**Issue by jeroenlaylo** [nextcloud/server#18971]
I run a Nextcloud instance with `chroot` enabled for PHP-FPM. This causes an issue; the interpreter for web-based usage is `fpm`, whereas the cronjobs are executed from the `cli` interpreter, which doesn't support the `chroot` option.

I have worked around this by editing the data directory, which is occasionally overwritten by Nextcloud, causing the cronjobs to fail.

### Steps to reproduce
1. Enable the `chroot` functionality of PHP-FPM.
2. Open config.php and edit the datadirectory variable like `'datadirectory' => ((php_sapi_name() == 'cli') ? '/var/www' : '') . '/nextcloud-data',`.
3. Set the cronjob as per the official documentation.

### Expected behaviour
I expect the datadirectory variable to remain untouched.

### Actual behaviour
Updates (both minor and major) change the datadirectory variable to exclude the custom sapi rewrite. This happens since at least v15.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/10904. Would that work for you?

**Comment by jeroenlaylo** [comment]
> Sounds like #10904. Would that work for you?

Yes, thank you! Fix implemented!
