### ISSUE TITLE
NC18 - can not change own passwd / group 

### ISSUE THREAD

**Issue by Uwe-MrT** [nextcloud/server#19004]
hi,
i have made fresh install of nextcloud 18 on my own debian 10 server.
i can not change my own groups / passwd etc. if i log in as user1 (admin)
so i create a new user (user2) with admin privilegs and log in as user2
now i can not change user2 own groups / passwd etc...
but from user1 i can change all now
so login as user1 again i can change groups + passwd only from user2
but not my own (user1)...
this must be a bug ?

nextcloud/index.php/settings/users

**Comment by acs-ferreira** [comment]
Can you change them in `/settings/user` and `/settings/user/security`?

**Comment by Uwe-MrT** [comment]
on /settings/user i can not change my own account (missing modify symbol)
on /settings/user/security i get an error (Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden.)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/18530

**Comment by TheManchineel** [comment]
This is a huge issue and fixing it should imo have maximum priority

**Comment by acs-ferreira** [comment]
@TheManchineel https://github.com/nextcloud/server/pull/18555

**Comment by AaronADev** [comment]
I am having the same exact issue! This is a critical issue, any updates on this?

Thanks for yalls help and work.

**Comment by TheManchineel** [comment]
Additonally, I originally admin1 which could not edit itself, so I created admin2 which could edit admin1 but not admin2. Logging back into admin1 for some reason I can't edit neither admin1 nor admin2, but admin2 can still edit admin1. To remove admin2 I had to use `occ user:delete admin2`

**Comment by Octopus2** [comment]
Can the fix get in 18.0.1?

**Comment by wiswedel** [comment]
> Can the fix get in 18.0.1?

it will

**Comment by Ruinenarr** [comment]
> > Can the fix get in 18.0.1?
> 
> it will

don't seams to work in 18.0.1 or am I doing something wrong?

**Comment by ZehuanZhang** [comment]
> > Can the fix get in 18.0.1?
> 
> it will

it seems like not work in 18.0.1 now, is it still a bug or this bug is not fixed in 18.0.1? I want to modify my quota recently but this bug makes me worried there is no space to upload files near future

**Comment by kesselb** [comment]
Bug is still open. Fix not merged yet hence not shipped with 18.0.1.

**Comment by FelixBuehler** [comment]
Not fixed in 18.0.1 for me.
You can add the user to the group via `occ group:adduser [gid] [uid]` though.

**Comment by Uwe-MrT** [comment]
OK, Update today to NC 18.0.2
Still can not edit own groups, password, etc on user settings page
Can i fix it by downloading and replacing some files ?

**Comment by wiswedel** [comment]
>  Can i fix it by downloading and replacing some files ?

Sorry, @Uwe-MrT. It's only gonna be in 18.0.3, unless you check out the source and compile the Vue stuff by yourself. Then you can have it today.

**Comment by Uwe-MrT** [comment]
Kein Problem, ich kann warten...
Ich hatte es wohl falsch verstanden, was ich hier gelesen habe.

**Comment by gabrielklein** [comment]
> > Can i fix it by downloading and replacing some files ?
> 
> Sorry, @Uwe-MrT. It's only gonna be in 18.0.3, unless you check out the source and compile the Vue stuff by yourself. Then you can have it today.

Thank you for the work. Don't work on  18.0.2. 

What I currently do
sudo -u www-data bash
cd {nextcloud}
php occ group:adduser MyGroup123 gabriel

**Comment by MatthlK** [comment]
Got Update 18.0.3 yesterday. Still can't edit my (adminsn group settings in user management. Is a fix planned?

**Comment by wiswedel** [comment]
The just released 18.0.3 was a short-notice security fix release, so the planned features for 18.0.3 now in fact apply to 18.0.4 - sorry for the confusion.

**Comment by dasBuero** [comment]
Still the same issue with 20.0.0. Anyone else?

**Comment by switalla** [comment]
yes we have the same issue @dasBuero any clue when this will be fixed?

**Comment by TheManchineel** [comment]
So it broke again?

**Comment by switalla** [comment]
yes seems so, we are able to assign a user to a group but not able to unassign

please help

thx!
Zitat von TheManchineel <notifications@github.com>:

**Comment by Verox001** [comment]
Ich lasse NeextCloud auf der Version 27.1.0 laufen und erhalte immer noch den Fehler. Weder kann ich Nutzer der admin Gruppe modifizieren, noch kann ich meine Benutzereinstellungen als admin öffnen (siehe Bild).
<img width="960" alt="image" src="https://github.com/nextcloud/server/assets/47862641/1162752b-3e15-496c-acc9-cb6ca1bbf55a">
