### ISSUE TITLE
Apache reverseproxy - logon issue related to CSP and configuration

### ISSUE THREAD

**Issue by bekon16** [nextcloud/server#19021]
I have issue related to logon problems: “Refused to send form data to ‘http://redacted/’ because it violates the following Content Security Policy directive: “form-action ‘self’”.”
I have read all topics related to this issue and i couldn’t find working solution.

### Steps to reproduce
In nextcloud config i have:

  'overwrite.cli.url' => 'https://some.domain.xx',
  'overwrite host' => 'some.domain.xx',
  'overwriteprotocol' => 'https',
  'overwritewebroot' => '/',
  'overwrite condaddr' => '^192\\.168\\.2\\.2$',

On backend in apache2.conf i have such configuration:

RemoteIPHeader X-Forwarded-For
RemoteIPInternalProxy 192.168.2.2

My setup looks like this:

VM Apache2 reverseproxy > VM backend virtual host with nextcloud (also apache2)

### Expected behaviour
This line (RemoteIPHeader X-Forwarded-For) allow me to see remote client ip, than logs are sended back via remote syslog to reverse proxy to parse it using fail2ban tool. On backend server i have also some other virtual hosts (not only nextcloud).

### Actual behaviour
When line “RemoteIPHeader X-Forwarded-For” is deleted everything works great, no loggon issue, but with it i have error mentioned above. I cant delete: “RemoteIPHeader X-Forwarded-For” cause instead of remote clients ip i have only reverseproxy ip so its useless for fail2ban.

### Server configuration

**Operating system:**
Debian buster

**Web server:**
Apache/2.4.38

**PHP version:**
7.3

**Nextcloud version:** 
17.0.4

**Nextcloud configuration:**

```

$CONFIG = array (
  'instanceid' => 'XXXX',
  'passwordsalt' => 'XXXXXXXXX',
  'secret' => 'XXXXXXXXXXXXXXXXXXXX',
  'trusted_domains' =>
  array (
    0 => '10.12.13.14',
    1 => 'some.domain.xx',
  ),
  'datadirectory' => '/var/www/nextcloud/data',
  'overwrite.cli.url' => 'https://some.domain.xx',
  'dbtype' => 'mysql',
  'version' => '17.0.2.1',
  'dbname' => 'xxxx',
  'dbhost' => 'redacted',
  'dbport' => '',
  'dbtableprefix' => 'redacted_',
  'dbuser' => 'redacted',
  'dbpassword' => 'redacted',
  'installed' => true,
  'theme' => '',
  'trusted_proxies' => array('192.168.2.2'),
  'overwrite host' => 'some.domain.xx',
  'overwrite protocol' => 'https',
  'overwrite webroot' => '/',
  'overwrite condaddr' => '^192\\.168\\.2\\.2$',
  'maintenance' => false,
  'loglevel' => 2,
  'updater.release.channel' => 'stable',
  'mysql.utf8mb4' => true,
  'logtimezone' => 'Europe/Warsaw',
  'updater.secret' => 'redacted',
);
```

Any idea how i can solve this?

I thought it might be some error in configuration but it looks like bug cause i tried few various configuration types. On previous versions of NC it worked great, problem is since 17.X

**Comment by acs-ferreira** [comment]
See https://github.com/nextcloud/server/issues/17432#issuecomment-538779444

**Comment by bekon16** [comment]
Hi, its not my case.
1 - i don't use nginx.
2 - i already have mentioned there config options: forwarded_for_headers, overwriteprotocol' => 'https', trusted_proxies etc and still nothing.
When option “RemoteIPHeader X-Forwarded-For” is set in apache, nextcloud ignore mentioned above options.
