### ISSUE TITLE
NC18: Misbehaving apps can easily affect others

### ISSUE THREAD

**Issue by janLo** [nextcloud/server#19020]
Afer an Upgrade to NC 18 I debugged some Issues in the UI. For example the FileActions from the richdocuments-app where gone. The Issue was completely unrelated in an incompatibility of the files_fulltextsearch-App: https://github.com/nextcloud/files_fulltextsearch/issues/83. Similar issues seemed to be caused by the groupfolder-app: https://github.com/nextcloud/groupfolders/issues/737 or https://github.com/nextcloud/richdocuments/issues/793.

I think a general solution to contain broken app-init-code should be considered. This can be as simple as wrapping it into try/catch.

**Comment by szaimen** [comment]
I think this is not easy to fix with the current architecture. 

cc @nextcloud/server-triage for more input on this

**Comment by Spartachetto** [comment]
I wonder if it is right to close this issue because it _needs info_ , as the missing info should be provided by  @nextcloud/server-triage ...

I'd get it to be closed because too difficult with the current apps architecture.
