### ISSUE TITLE
What to do when you broke your instance during an upgrade process?

### ISSUE THREAD

**Issue by vityafx** [nextcloud/server#19038]
I had a version of nextcloud of 16 and wanted to upgrade to 17 and I didn't know that a new one, the 18th version of nextcloud has been published and so I broke my cloud instance by upgrading from 16 to 18.

So what my options are now? I can't downgrade, I can't switch back to 16 and do upgrade to 17 and then 18 because there are some files or database (I don't know) already broken by an attempt to run 18th version.

P.S. I am using docker for nextcloud, but I don't know where to ask about the update problem. I believe, fixes should be the same though.

**Comment by kesselb** [comment]
You already run occ upgrade? If no the fastest way should be to do a manual update to 17. It's described in detail in the docs somewhere.

1. Download latest 17 release
2. Extract it into a new folder
4. Copy config and data folder into the 17 folder
5. Run occ upgrade

Please if you report such issues make sure to provide as much information as you can. I don't know what exactly is broken or at which step it stucks.

**Comment by vityafx** [comment]
Thanks, and yes, so that's what I did. At first, I tried to run the `occ upgrade`, but then I had the

> UnexpectedValueException: The files of the app "files" were not correctly replaced before running the update

Then:

1. Removed the whole directory, backing up the `config.php` file from my installation and leaving it there with the version number taken from the `stable16` tag of this repository, it was `16.0.7.1`.
2. Cloned this repository and copied all the files to my the html directory.
3. Correct the permissions.
4. Changed the version of docker image to be 16 again (as it was before the update to 18).
5. Did the `occ upgrade` and `occ maintenance:repair` just to be sure everything is okay with 16 version.
6. Changed the version of docker image to 17, `docker-compose pull; docker-compose down; docker-compose up -d`.
7. Checked in the logs that the update has started and performs successfully.
8. After the updated finished, I changed the version of the docker image to 18 and checked if the update ran again.
9. The update went fine as well.

It works.
