### ISSUE TITLE
NC18: Videos with names starting with "#" cannot be played due to loading error

### ISSUE THREAD

**Issue by SignalFlagZ** [nextcloud/server#19036]
### Steps to reproduce
1. Upload video anywhere.  
2. Click it and check it playable.
3. Rename to file name starting with "#" like "#1.mp4".  
4. Click it to play but gets error.
 
### Expected behaviour
Play the video file.

### Actual behaviour
Get a message "Error loading "#1.mp4"

### Server configuration

**Operating system:**
Linux 5.3.0-1015-raspi2 #17-Ubuntu SMP Thu Dec 5 04:58:47 UTC 2019 aarch64
**Web server:**
Apache/2.4.38 (Debian) (apache2handler)
**Database:**
mysql 10.4.11
**PHP version:**
7.3.13
**Nextcloud version:** (see Nextcloud admin page)
18.0.0 - 18.0.0.10
**Updated from an older Nextcloud/ownCloud or fresh install:**
17.0.2
**Where did you install Nextcloud from:**
Docker hub latest tag

* Server configuration detail
<details><summary>Signing status</summary>
No errors have been found.
</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_linkeditor: 1.0.11
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trackdownloads: 1.7.0
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - music: 0.12.1
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - registration: 0.4.7
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - contacts
 - encryption
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": true,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        "0": "192.168.11.12:8180",
        "10": "xxxx.homeserver.com"
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\/var\/www\/skeleton",
    "default_language": "ja",
    "default_locale": "ja_JP",
    "dbtype": "mysql",
    "version": "18.0.0.10",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "overwritehost": "xxxx.homeserver.com",
    "overwriteprotocol": "http",
    "overwritewebroot": "\/",
    "overwritecondaddr": "",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\Movie",
        "OC\\Preview\\TXT"
    ],
    "overwrite.cli.url": "http:\/\/xxxx.homeserver.com"
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

+----------+-------------+------------+-----------------------+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+------------------+-------------------+-------+
| Mount ID | Mount Point | Storage    | Authentication Type   | Configuration                                                                                                                  | Options                              | Applicable Users | Applicable Groups | Type  |
+----------+-------------+------------+-----------------------+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+------------------+-------------------+-------+
| 14       | /TV         | SMB / CIFS | Username and password | host: "fileserver", share: "Titles", root: "", domain: "fileserver", show_hidden: false, timeout: "", user: "someone", password: "***" | enable_sharing: true, readonly: true |                  | admin             | Admin |
+----------+-------------+------------+-----------------------+--------------------------------------------------------------------------------------------------------------------------------+--------------------------------------+------------------+-------------------+-------+

</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.117 Safari/537.36

**Comment by tgressly** [comment]
+1

**Comment by SignalFlagZ** [comment]
NC19 also leaves this problem.

**Comment by szaimen** [comment]
I think this was fixed with the latest releases.
