### ISSUE TITLE
Right sidebar broken for folders that contain a dot

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19037]
### Steps
1. Receive a remote share for a folder named `thanks but there is no need for that.I just wondered if someone would respond. here are some pictures of my cat for no reason.`
2. Try to open the sidebar for the item after accepting the share

> ![Bildschirmfoto von 2020-01-21 08-58-50](https://user-images.githubusercontent.com/213943/72785977-c33cf100-3c2c-11ea-8bea-37bf3ae7e305.png)

cc @skjnldsv

**Comment by nickvergessen** [comment]
Also a lot more things are broken. It doesn't list the full name. so I can't rename or delete the item because the path is not matching anymore...

**Comment by skjnldsv** [comment]
> It doesn't list the full name

You mean in the list? Did it ever worked? ^^

**Comment by skjnldsv** [comment]
Works for me now
