### ISSUE TITLE
New folder: icon-confirm button for mouse users

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1904]
Currently the new folder name has to be confirmed by using enter. This is a problem on mobile and for people who use the mouse a lot.

We should introduce an icon-confirm button positioned in the right of the field which acts as a confirm function too.

cc @nextcloud/designers @nextcloud/javascript

**Comment by MorrisJobke** [comment]
I guess we are out of time for this -> move to 13.

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/8575
