### ISSUE TITLE
Accessing folder via favorites quick links in navigation keeps wrong Workspace and Recommendations

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#19048]
1. You start in the root folder, with a Workspace file and Recommendations:
![Root folder](https://user-images.githubusercontent.com/925062/72806118-74747300-3c8f-11ea-8a73-22b6e0a93e7d.png)

2. When you click on a subfolder via the folder list, it looks like this: Correctly changed workspace (none in this case) and no Recommendations as they only show in the root folder:
![Subfolder via folder list](https://user-images.githubusercontent.com/925062/72806117-73dbdc80-3c8f-11ea-8b3e-345ade19e36e.png)

### Problem
When, from the root folder, you navigate to that same subfolder not via the file list but via the favorites quick access list in the app navigation, the Workspace _and_ Recommendations from the parent folder are kept:
![Subfolder navigated via favorites quick access](https://user-images.githubusercontent.com/925062/72806114-73dbdc80-3c8f-11ea-8d6c-f6a0cf096c81.png)

cc @newhinton for favorites quick access and cc @juliushaertl for Workspaces and @ChristophWurst for Recommendations. :)

**Comment by juliushaertl** [comment]
Most likely something in the file list event process that changeDirectory is not properly triggered, since that is what is used in workspace and recommendations:

https://github.com/nextcloud/text/blob/b21f51cfd53ef999dda967292e7f1c5a31edf033/src/helpers/files.js#L194

**Comment by blizzz** [comment]
clearing the milestone

**Comment by PVince81** [comment]
another issue related to "changeDirectory":

1. go to the root
2. create a folder "test"
3. enter the folder "test"
4. use the browser back button to go back

Expected: recommendations appear again
Actual: recommendations don't

I think the event "changeDirectory" was supposed to be internal and not used by apps.

I have a local fix that fixes both the original issue and the one I reported.

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/30593
