### ISSUE TITLE
Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x92 \x09...' for column `cloud`.`calendarobjects_props`.`value` at row 1

### ISSUE THREAD

**Issue by docmcfly** [nextcloud/server#19043]
Hi,

I use DAVx5 version 2.6.3.1, aCalendar+ and Nextcloud 17.0.2 (Calendar 2.0) (Debian Buster/Maria DB/Apache).

My problem is triggered when I try to synchronize a calendar day with the following text from my smartphone to the Nextcloud: 

"🚒 TEST Event"

Note the fire truck. 

DAVX5 gives the following cause as error message: 

```
HTTP REQUEST:
Request{method=PUT, url=https://cloud.mydomain.tld/remote.php/dav/calendars/docmcfly/fwa/8d7bc1eb-0cd4-45a1-b76c-0768cfd3fb3f.ics, tags={}}
BEGIN:VCALENDAR
VERSION:2.0
PRODID:+//IDN bitfire.at//DAVx5/2.6.3.1-gplay ical4j/2.2.6
BEGIN:VEVENT
DTSTAMP:20200119T152445Z
UID:8d7bc1eb-0cd4-45a1-b76c-0768cfd3fb3f
SUMMARY:🚒 	TEST Event
DTSTART;VALUE=DATE:20201219
DTEND;VALUE=DATE:20201220
STATUS:CONFIRMED
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR

HTTP RESPONSE:
Response{protocol=http/1.1, code=500, message=Internal Server Error, url=https://cloud.mydomain.tld/remote.php/dav/calendars/docmcfly/fwa/8d7bc1eb-0cd4-45a1-b76c-0768cfd3fb3f.ics}
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Doctrine\DBAL\Exception\DriverException</s:exception>
  <s:message>An exception occurred while executing 'INSERT INTO `calendarobjects_props` (`calendarid`, `calendartype`, `objectid`, `name`, `parameter`, `value`) VALUES(?, ?, ?, ?, ?, ?)' with params ["26", 0, 1402, "SUMMARY", null, "\ud83d\ude92 \tTEST Event"]:

SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x9A\x92 \x09...' for column `cloud_cylancer`.`calendarobjects_props`.`value` at row 1</s:message>
</d:error>
```

If the error message is correct, it tries to interpret the fire truck as dateTime. 

I have changed my database to unicode. Interestingly, the dateTime is imported and appears in the calendar (with fire engine). 

Is this a problem with Nextcloud's CalDav interface or is DavX5 using the interface incorrectly? Or is the DB configured incorrectly? 

I have already posted the bug to DavX5 as well: [bitfire.at...](https://forums.bitfire.at/topic/2219/in-the-calendar-entry-generates-incomprehensible-synchronization-errors)

There is also described how to reproduce the error. 

Thanks for helpful answers... 
Greetings 
Clemens

Translated with www.DeepL.com/Translator (free version)

**Comment by tcitworld** [comment]
Please fill the issue template.

Your issue is probably linked to your database not using UTF8-mb4. https://docs.nextcloud.com/server/18/admin_manual/configuration_database/mysql_4byte_support.html

**Comment by docmcfly** [comment]
Hello, and sorry I haven't gotten back to you sooner.

I've checked everything thoroughly. My tables are all UTF8-mb4. 

```
SELECT table_name, column_name, character_set_name, collation_name 
FROM information_schema.columns 
WHERE table_name LIKE '%props';

table_name column_name character_set_name collation_name
calendarobjects_props id NULL NULL
calendarobjects_props calendarid NULL NULL
calendarobjects_props objectid NULL NULL
calendarobjects_props name utf8mb4 utf8mb4_bin
calendarobjects_props parameter utf8mb4 utf8mb4_bin
calendarobjects_props value utf8mb4 utf8mb4_bin
calendarobjects_props calendartype NULL NULL
```

That's why I can use the emojis without any problems when I enter new appointments in Nextcloud. 

Here is a simple example: 

1. I create a new calendar in Nextcloud and create two appointments, which always start with a fire engine. 

2. I have exported this calendar. See attachment. 

4. then I create another empty calendar in Nextcloud. I want to import the previous calendar into this one.  

5. I use DavX5 to synchronize the calendar situation on my smartphone. So I see both calendars. 

6. copy the exported calendar to my smartphone and import it into the empty second calendar. 

When DavX5 tries to synchronize the imported calendar, it gets the error message mentioned in the first post. 

Maybe someone else can reproduce it and confirm my error report. 

Thanks and Greetings Clemens   


[test-2020-03-31.zip](https://github.com/nextcloud/server/files/4408294/test-2020-03-31.zip)

**Comment by docmcfly** [comment]
With a heavy heart I had to completely rebuild my database yesterday to increase the page_size. 

So
```
# createBackup.sh 
# apt purge mariadb-server*
# apt install mariadb-server
# mysql mysql < mysql_rights_and_user.sql
# mysql -u root -p < databases.sql
```
...and after that everything worked fine. Although I didn't change anything on the exported dump.  

My guess: My database still has its root in Debian Woody. It always grew with me, but apparently the migration was not complete. 

Thanks and greetings Clemens

**Comment by bd4** [comment]
I am seeing this error in Nextcloud 23.0.0 when trying to convert from sqlite3 to mariadb. Apparently there is unicode in datetimes and sqlite allowed it but the mysql schema does not?

**Comment by bd4** [comment]
I was able to workaround this by putting this in my mariadb config:
```
command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
```
AND also adding this to the nextcloud config: `'mysql.utf8mb4' => true`

**Comment by zyphlar** [comment]
@bd4 I don't manage my DB or Nextcloud config files very directly, though I have root access. Could you tell me the file paths of the mariadb and nextcloud config files you edited just so I don't make a mistake?

**Comment by 0ranki** [comment]
I am converting back to MariaDB from Postgres, and ran in to the error as well.

Solved it with the following steps:
```
# /etc/mysql/conf.d/utf-8.cnf:
[mysql]                                                                                                                                                                                                                                                                                   
default-character-set=utf8mb4                                                                                                                                                                                                                                                             
                                                                                                                                                                                                                                                                                          
[mysqld]                                                                                                                                                                                                                                                                                  
collation-server = utf8mb4_unicode_ci                                                                                                                                                                                                                                                     
init-connect='SET NAMES utf8mb4'  
character-set-server = utf8mb4

# append to Nextcloud config.php (remember the comma after the latest entry):
'mysql.utf8mb4' => true

**Comment by FayeDE** [comment]
As this is the first google result on this issue, I'm commenting for future users: 
php occ maintenance:mode --on
php occ config:system:set mysql.utf8mb4 --type boolean --value="true"
php occ maintenance:repair
php occ db:convert-type --all-apps --clear-schema mysql nextcloud_user mysql nextcloud
php occ maintenance:mode --off

**Comment by hannob** [comment]
Hi, why has this issue been closed without a fix?
I'm seeing this with a current version of nextcloud (34.0.3), and it prevents me from converting from sqlite to mysql.
(Also, the workaround from the last comment did not work for me...)
