### ISSUE TITLE
New folder creation flow: descend into newly created folder by clicking enter again

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#1905]
When finished with entering the new folder name, the most likely thing people can do with it is fill it up with files. That’s why we should automatically descend into it.

With #1618 (share current folder) it will also be possible to share it from inside so that’s taken care of too.

cc @nextcloud/javascript @nextcloud/designers

**Comment by te-online** [comment]
You have a point there. But I'm not sure about the flow you describe.  

I can only speak from my own experience: Probably the second most likely thing people will do is creating multiple folders at a time (like ”Images", ”Videos” and ”Sounds”) and then filling one at a time. Jumping into the new folder surely makes the first most likely case a piece of cake, but it really makes this second case a bumpy ride.

One example from operating systems: If you go to single level view in Finder, Windows Explorer or Nautilus, for example – and our interface is a single level view right now, you can't see multiple levels at the same time – and if in this view you'd create a new folder, you will never automatically jump into that folder.

We could do an enhancement with keyboard shortcuts, though. Similar to the OS's filemanagers, we would just set the focus to the newly created folder and with pressing return you would enter the folder right away.

**Comment by jancborchardt** [comment]
@te-online right, so having the focus on the folder and then pressing enter again for entering it sounds like a good keyboard shortcut! :) Changing the title accordingly.

**Comment by sagorika1996** [comment]
I'm working on this.
