### ISSUE TITLE
Wrong password

### ISSUE THREAD

**Issue by bobinson84** [nextcloud/server#19059]
### Steps to reproduce
1. Restore login 

### Expected behaviour
Login as usual with name and password

### Actual behaviour
Cannot login as admin to my Nextcloud dashboard it says "Wrong password". I didn’t update or made any changes.  The same issue for all 50+ users and 6 admins. This happened instantly and I cannot get access to the Nextcloud. I have uploaded the backed up data folded to the server. And all access was granted to all accounts immediately. In few minutes it kicks off the account and all attempts login ended up with “Wrong password” again. Doing the same backup copy provides access for short period of time and them blocks.

### Server configuration

**Operating system:**
located at 123-reg.co.uk shared hosting without ssh access
**Web server:**
no information
**Database:**
mysql 10.2.16-MariaDB
**PHP version:**
5.6
**Nextcloud version:** (see Nextcloud admin page)
15.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
free install in march 2019 and no updates since that time. all files in the folder dated that date accept "owncloud.db" and "nextcloud.log".
**Where did you install Nextcloud from:**
Downloaded from official website 
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Tried and get same "Wrong password" message
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Only Group Folder was added all the rest are standard that were with the version installation. 
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Unfortunately no access since it is on shared hosting
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)

Unfortunately no access since it is on shared hosting
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

not used

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Not clear how to do it. Can send you the db if that's possible

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>
not clear how to get it
#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XiG6n20jbWMsHoPIWd7EPwAAAA4","level":2,"time":"2020-01-17T13:46:07+00:00","remoteAddr":"1.1.1.1","user":"--","app":"core","method":"POST","url":"\/nextcloud\/index.php\/login?user=uu_admin","message":"Login failed: 'uu_admin' (Remote IP: '1.1.1.1')","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/79.0.3945.117 Safari\/537.36","version":"15.0.5.3"}

```
</details>

#### Browser log

<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
not clear how to get it
a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by bobinson84** [comment]
Hello,
Do I need to do something in relation to the adding of the issue to the 3 different labels? 
Thank you.

**Comment by kesselb** [comment]
It's probably more a question for https://help.nextcloud.com. A good start would be to figure out if you are really using mariadb. You mention a file owncloud.db that's usually the name of the sqlite database.

**Comment by bobinson84** [comment]
Probably you are right. Because I checked it on the hosting provided account and not sure that the database of nextcloud uses the same one. Might be not. Would you please advise how can I check that in formation and where to look for the database? Thank you.

**Comment by kesselb** [comment]
There is a row "dbtype" in `config/config.php`.

**Comment by bobinson84** [comment]
Ok now i see. It is 'dbtype' => 'sqlite3'.
That probably should be added where to get this info. Anything else I can do in order to help resolving the issue. Could it be due to some updates done by hosting provider e.g. Brute Force Attack protection?

**Comment by kesselb** [comment]
Actually it's part of the issue template. Either use the config export via occ or insert `config.php` (but remove the sensitive information first).

> Anything else I can do in order to help resolving the issue. Could it be due to some updates done by hosting provider e.g. Brute Force Attack protection?

I don't know. Maybe someone else has a clue what could be wrong.

**Comment by bobinson84** [comment]
Thank you so much for you attempt to help me!
I cannot use occ since it is on shared hosting and hence there is no ssh with the package. 
Here is config.php, hope I didn't remove any excessive information from it.
/*-------------------------------------*/
<?php
$CONFIG = array (
  'instanceid' => '**********',
  'passwordsalt' => '**********',
  'secret' => '**********',
  'trusted_domains' => 
  array (
    0 => 'hytunnel.net',
  ),
  'datadirectory' => '/home/cluster-sites/8/h/hytunnel.net/public_html/nextcloud/data',
  'dbtype' => 'sqlite3',
  'version' => '15.0.5.3',
  'overwrite.cli.url' => 'http://hytunnel.net/nextcloud',
  'installed' => true,
  'maintenance' => false,
  'filelocking.enabled' => false,
  'mail_from_address' => 'hytunnel',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpname' => '**********',
  'mail_smtppassword' => '**********',
  'mail_smtpsecure' => 'ssl',
);

**Comment by bobinson84** [comment]
Hello! Sorry for asking probably too much, but is there anything that I can do in order to bring it back to life? Thank you!

**Comment by skjnldsv** [comment]
Hey! Sorry this slip through :(
Were you able to get back to your instance?

**Comment by bobinson84** [comment]
Hello! Yes finally managed and all is working. I was with https://www.123-reg.co.uk/  (avoid this provider) and spent so much time trying to resolve the issue with them got pissed off and moved to another hosting, recovered from back up and all started to work.
With previous hosting even new installation resulted in this error straight after installation, they told me that this is not theirs problem but rather Nextcloud and sent me off. I came to conclusion that they have some sort of firewall which prevented the Nextcloud to work.

**Comment by skjnldsv** [comment]
Glad it worked out! Thanks for taking the time to report the issue here :)
Stay safe!
