### ISSUE TITLE
[UPGRADE 17.0.2 -> 18.0.0] WORKFLOWENGINE Column not found: 1054 Unknown column 'entity' in 'where clause'

### ISSUE THREAD

**Issue by Comendatore** [nextcloud/server#19058]
### Steps to reproduce

- `cd /nextcloud/install/path`
- `sudo -u www-data php occ upgrade`

**Operating system** : Debian stable
**Current version of Nextcloud** : 17.0.2 (working)
**Expected version of Nextcloud** : 18.0.0

**Full log :**
````
Updating <workflowengine> ...
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE ``oc_flow_operations`` SET ``entity`` = ? WHERE ``entity`` = ''' with params ["OCA\\WorkflowEngine\\Entity\\File"]:

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'where clause'                                                                                                                                                                  
Update failed
Maintenance mode is kept active
Reset log level
````

I tried these commands without success :

- `sudo -u www-data php occ db:add-missing-indices`
- `sudo -u www-data php occ maintenance:update:htaccess`
- `sudo -u www-data php occ maintenance:repair`

**Comment by Comendatore** [comment]
**SOLUTION FOUND**:
i used database structure informations found in the file apps/workflowengine/lib/Migration/Version2000Date20190808074233.php from lines 114 to 128 and manually created missing fields with SQL command:
``ALTER TABLE `oc_flow_operations` ADD `entity` VARCHAR(256) NOT NULL AFTER `operation`, ADD `events` TEXT NOT NULL AFTER `entity`;``

Then i launched again `sudo -u www-data php occ upgrade` and all gone fine.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Same as https://github.com/nextcloud/server/issues/19058. Please make sure to delete `apps/workflowengine/appinfo/databases.xml` (if present).
