### ISSUE TITLE
OnlyOffice / Collabora not visible if FulltextSearch or Groupfolder are activted

### ISSUE THREAD

**Issue by wagnbeu0** [nextcloud/server#19071]
After installing NC18.0.0 in the main menu the + Button to create new files does not show Office Documents anymore.
This is both for OnlyOffice as well as for Collabora.
After installing either "Files - Fulltext Search" or "GroupFolder" it works.

see also https://help.nextcloud.com/t/nextcloud-18-collabora-not-working-anymore/68655/11

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
