### ISSUE TITLE
Can not change admin settings

### ISSUE THREAD

**Issue by Gadgetroch** [nextcloud/server#19072]
Good morning, when i go to the settings users, i can modify all settings but not mine, the admin user.

So i can't join any group, change my quota etc.

Nextcloud : v18

### Steps to reproduce
1. Go to settings

### Expected behaviour
Change admin (my) settings

### Actual behaviour
Link for change settings is not showing

### Server configuration

**Operating system:**
Nextcloud docker V18

**Comment by kesselb** [comment]
Same as https://github.com/nextcloud/server/issues/19004

**Comment by wiswedel** [comment]
closing duplicate
