### ISSUE TITLE
Add an app presetting mode after installing

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#19085]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I install a new App for my users to help them working for the club better but have to  Impersonate every user after installing this app to config the tool. 

**Describe the solution you'd like**
After Installing an App into Nextcloud, it should be possible to have a kind of "presetting" mode. Where you are able to Work inside the app and set this changes as default for other Users.

**Describe alternatives you've considered**
https://github.com/nextcloud/impersonate Impersonate every and all new user to be able to presett the App. (not able to encrypt nextcloud)

**Comment by szaimen** [comment]
This needs to be solved in each app and not in the server code. Please open this for every app where you need this feature. Thanks!

**Comment by Mannshoch** [comment]
Is there a guide or best practice how to develop apps to handle such settings? 
I will add such a link to Issues related to this kind of problems.

**Comment by szaimen** [comment]
> Is there a guide or best practice how to develop apps to handle such settings?

I personally don't know of any. But you could ask this at https://help.nextcloud.com/c/dev/11 :)
