### ISSUE TITLE
limit avatar demensions

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#19083]
Currently we allow requesting virtually any size of avatars between 1x1 and 2048x2048.
I think it makes sense to just come up with a list here of sizes that make sense

Personally I would opt for

* 64x64
* 128x128
* 256x256
* 512x512
* 1024x1024
* 2048x2048

That should already be more than enough sizes to pick from.

What do you think @ChristophWurst @nickvergessen @juliushaertl @skjnldsv

**Comment by nickvergessen** [comment]
32,64,128,256
We dont really need bigger ones

**Comment by skjnldsv** [comment]
@nickvergessen call screen on mobile clients with high res screens :)

**Comment by nickvergessen** [comment]
Most people dont even upload in that size...

**Comment by nickvergessen** [comment]
And as for the call screen, it was long ago decided to have a streched blurred version in the background and a reasonable normal size on top

**Comment by skjnldsv** [comment]
> Most people dont even upload in that size...

disagree, I upload high res 2Megapixels images because that's what I have on hand.
Also, generated avatars

**Comment by rullzer** [comment]
I'm fine with the extra sizes for now. No need to hack a lot in there form my point of view.

So. What do we want.

If the size requested is 90 just return the 128 avatar. Or do we do a 301 redirect?

**Comment by joshtrichards** [comment]
Fixed in #31010
