### ISSUE TITLE
Nextcloud 18 notes, lists or links

### ISSUE THREAD

**Issue by janarzz** [nextcloud/server#19088]
Hey, i have problem with Nextcloud 18 notes, lists and links spacing. Its to big. Why ?
Pic link is here...
https://www.upload.ee/image/11018372/nextcloud.png

**Comment by Beeez** [comment]
I get this as well.

**Comment by simmstein** [comment]
Remove the file `Readme.md`.

**Comment by kesselb** [comment]
Sounds like a duplicate of https://github.com/nextcloud/text/issues/586
