### ISSUE TITLE
resgisterAction doesn't work

### ISSUE THREAD

**Issue by bbbastien** [nextcloud/server#19080]
### Steps to reproduce
1. Create an app
2. Develop an app to add new menu context in Files
3. Cannot add a new link action

### Expected behaviour
My customized application should add a new menu link action on Files.

### Actual behaviour
Nothing happens, no error message

### Server configuration

**Operating system:**
Windows 10
**Web server:**
Nginx
**Database:**
MySQL
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
18
**Updated from an older Nextcloud/ownCloud or fresh install:**

### Client configuration
**Browser:**
Brave Browser
**Operating system:**
Windows 10

This is my Code : 
```
(function (OCA) {
	"use strict";

	OCA.Files = OCA.Files || {};

	OCA.Files.QrCodePlugin = {
		name: 'qrCode',
		_extendFileActions: function (fileActions) {
			fileActions.registerAction({
				name: 'qrCode',
				displayName: t('mynote', 'qrCode'),
				mime: 'all',
				iconClass: 'icon-public',
				actionHandler: function () {}
			});
		},
		attach: function (fileList) {
			this._extendFileActions(fileList.fileActions);
		}
	}


}) (OCA);

OC.Plugins.register('OCA.Files.FileList', OCA.Files.QrCodePlugin);
```

Can you tell me where I can debug my registerAction or tell me what is missing ?

**Comment by kesselb** [comment]
I think you have to register the script (with the above code) to Nextcloud. Like the files_lock app. App subscribes to `OCA\Files::loadAdditionalScripts` and if this event is emitted include the file with the script. 

https://github.com/nextcloud/files_lock/blob/36e2d470cf7d98d41e63fdc83c8bc372f47aa16a/lib/AppInfo/Application.php#L97-L103

**Comment by bbbastien** [comment]
I did it. But that changes nothing ><

**Comment by kesselb** [comment]
Is your app code available somewhere? I would try to debug this step by step.

1) Is my listener to `OCA\Files::loadAdditionalScripts` working? Probably something like `\OC::$server->getLogger()->debug('Yey! Listener is working');` in your listener callback.

2) Is my script loaded by the browser? (your browser will tell you probably some alerts)

**Comment by bbbastien** [comment]
I already found the solution, I added : 

```
permissions: OC.PERMISSION_UPDATE,
type: OCA.Files.FileActions.TYPE_DROPDOWN,
```

**Comment by kesselb** [comment]
Okay with you to close this issue then?

**Comment by bbbastien** [comment]
Yes
