### ISSUE TITLE
Also show 'current' version in files sidebar

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#19090]
Right now the sidebar only shows older versions of the file.
I think it makes sense to also show the current version (so just the file itself) here. So you have it all in a simple overview.

@skjnldsv probably not that hard to add once we move over to the new sidebar stuff.

**Comment by skjnldsv** [comment]
I don't understand what you mean :thinking: 
On the files_versions app?

**Comment by rullzer** [comment]
If you go to a file now. With several versions. And see the versions in the sidebar tab. You see only old versions. The newest version (hence current file) is not in there.

**Comment by skjnldsv** [comment]
There would be no actions then, right?

**Comment by skjnldsv** [comment]
Done with 26
