### ISSUE TITLE
Updating from version 16.0.4.1 to 17.0.2    SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 INT NOT NULL, DROP 1, CHANGE 1 1 INT NOT NULL' at line 1

### ISSUE THREAD

**Issue by wsz9903011** [nextcloud/server#19098]
CentOS Linux release 7.7.1908 (Core)
3.10.0-1062.9.1.el7.x86_64

nginx/1.15.8
mysql  Ver 15.1 Distrib 10.4.11-MariaDB, for Linux (x86_64) using readline 5.1
php 7.2

For the sake of completeness, here's the settings I added to /etc/my.cnf:
[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=1
datadir=/var/lib/mysql

============================================
Enter the command ./occ upgrade

then:
Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing
 'ALTER TABLE oc_tablename ADD 1 INT NOT NULL, DROP 1, CHANGE 1 1 INT NOT NULL': 

SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '1 INT NOT NULL, DROP 1, CHANGE 1 1 INT NOT NULL' at line 1

**Comment by kesselb** [comment]
`oc_tablename` which table?

**Comment by wsz9903011** [comment]
> `oc_tablename` which table?

Thank you for your reply.
Delete oc_tablename is normal
