### ISSUE TITLE
File permissions not preserved during app tarball extraction

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#19093]
### Steps to reproduce
1. Install Mail
2. Check permissions of `vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor`

### Expected behaviour
File should be executable

### Actual behaviour
File is not executable.

### Server configuration

**Operating system:**

Arch

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:**

18

Discovered in https://github.com/nextcloud/mail/issues/2489#issuecomment-576279474.

I could not find a way to force the tar extractor to preserve permissions. There is only one to preserve ownership.

The same problem was found in the document server app. @icewind1991 "fixed" it with https://github.com/nextcloud/documentserver_community/commit/c1e6c63774107437b2aa2df87970a294d9e94f6b.

Does preserving the permissions bear any risk @rullzer? If the current tar lib doesn't support this option I could look for an alternative.

**Comment by rullzer** [comment]
Well by default less permissions are better of course.
I guess you need a work around indeed

**Comment by ChristophWurst** [comment]
Okidoke: https://github.com/nextcloud/mail/pull/2534

**Comment by ldesgrange** [comment]
Probably related side effect, I tried to upgrade nextcloud 17 to 18, the updater's backup task failed with:

> Could not copy "/var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor" to "/srv/nextcloud/updater-ocjsrtro0f9e/backups/nextcloud-17.0.2.1/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor".
> Source /var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor is not readable.
> Destination /srv/nextcloud/updater-ocjsrtro0f9e/backups/nextcloud-17.0.2.1/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor is not writable

**Comment by ChristophWurst** [comment]
What are your current permission on the source file?

**Comment by ldesgrange** [comment]
`/var/www/nextcloud/apps/mail/vendor/christophwurst/kitinerary-bin/bin/kitinerary-extractor` has permissions `--wxr-x--T` (no read for the owner user which is the one nextcloud is using to perform the backup)

**Comment by ChristophWurst** [comment]
I've seen this in another report. The sticky bit puzzles me. We set the permissions to 744 now. So the user *should* have read permissions. We actually never set it to anything else manually.

**Comment by Nils160988** [comment]
Using the real octal number in the new version of mail (https://github.com/nextcloud/mail/pull/2575) fixes the issue for me, thank you @ChristophWurst

**Comment by ChristophWurst** [comment]
That is good news! Thanks for sharing, @Nils160988!

**Comment by ldesgrange** [comment]
Same here, update to Mail 1.1.2 worked, upgrade do nextcloud 17.0.3 and 18.0.0 is not blocked anymore. Thanks.

**Comment by rullzer** [comment]
Thanks for verifying all.
Lets close this then.
