### ISSUE TITLE
show readme in public shares

### ISSUE THREAD

**Issue by mokkin** [nextcloud/server#19101]
Actually we are using https://gitlab.univ-nantes.fr/uncloud/files_readmemd/ to instruct external users on public shares on the header.
With the new readme.md to descripe the function since v18 this could be replaced, at least as an option.

**Comment by boecko** [comment]
Readme.md doesn't work in public folder due to a javascript error
`Uncaught (in promise) TypeError: Cannot read property 'fileList' of undefined
    at Module.29 (client.js:125)
    at o (bootstrap:63)`

The corresponding line in client.js is 
```javascript
var client = OCA.Files.App.fileList.filesClient;
client.addFileInfoParser(function(response) {
```

**Comment by szaimen** [comment]
It is possible to show readme files on public links by using the built-in rich workspaces since NC18.
