### ISSUE TITLE
user list broken if people are in two many groups.

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#19122]
That's how the user listing looks for example at c.nc.com for users which are in a lot of groups.

![image](https://user-images.githubusercontent.com/1589737/73076953-7b81c800-3ebf-11ea-94c3-8fb7d426a1c4.png)

As you can see the entry of my account breaks the layout both horizontally and vertically.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/18920

**Comment by schiessle** [comment]
then let's close this one and continue here #18920
