### ISSUE TITLE
Subscription not fetched by server on creation

### ISSUE THREAD

**Issue by Perflyst** [nextcloud/server#19126]
### Steps to reproduce
1. Add a new iCal calendar

### Expected behaviour
Events in calendar should be displayed

### Actual behaviour
Nothing is displayed

### Calendar app
**Calendar app version:** 2.0.0

**CalDAV-clients used:** nan

### Client configuration
**Browser:** Firefox 72.0.1

**Operating system:** Ubuntu 18.04

### Server configuration

Docker 18.0-apache

**Updated from an older installed version or fresh install:** no

**List of activated apps:**

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - calendar: 2.0.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.6
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - provisioning_api: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

**Nextcloud configuration:**

```
{
    "system": {
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 0,
        "theme": "",
        "loglevel": 2,
        "maintenance": false
    }
}
```

### Logs
Nothing logged in browser or webserver error log

**Comment by georgehrke** [comment]
Needs a backport to 17

**Comment by manfredu** [comment]
> @manfredu Can you please open a separate issue for that, using the entire issue template **including all requested log files**. Thx.

https://github.com/nextcloud/calendar/issues/1899

**Comment by palegrand** [comment]
I still have the issue in 17.0.3. New events are not displayed. 
Cron runs without problem. Adding a new calender subscription with the very same .ics-link give me (after the first cron-run) a complete calendar with _all_ events. 
But events added after this moment are not shown (neither the old nor the new subscription) 
I understand this might be fixed in 18. is there anything I can do in 17.0.3?

**Comment by georgehrke** [comment]
@palegrand See https://github.com/nextcloud/server/pull/19229
The patch will be included in 17.0.4

**Comment by palegrand** [comment]
@georgehrke Thank you  - I updated two hours ago to 18.0.1 and hope it's working there right away

**Comment by palegrand** [comment]
* create subscription: new calendar show with all entries after first cron run --> ok
* **entries never get updated**, cron does call \UpdateCalendarResourcesRoomsBackgroundJob --> problem
* Verify behaviour: delete subscription, recreate it: calendar shows with all recent entries after first cron run - but never updates after creation (as above
* other calendars work/update fine. It only affects subsriptions. subscritptions used to work properly in calendar >2.0.1
current: stable (nextcloud 18.0.2, calendar 2.0.2)

**Comment by Mirko607** [comment]
I am facing the same issue as @palegrand did. 

Has there been opened a seperate issue? 

Where and how could I provide more information if needed?
