### ISSUE TITLE
Can't use string inside t and as singular in n

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#19123]
Tested on Nextcloud 17, 18, master.

In the calendar we have the following to translations:
https://github.com/nextcloud/calendar/blob/7a1e962c51bf418b4b13a31c9b2aa7b5f56741ce/src/components/AppNavigation/Settings/SettingsImportSection.vue#L31

(used for the button in the settings area)

https://github.com/nextcloud/calendar/blob/7a1e962c51bf418b4b13a31c9b2aa7b5f56741ce/src/components/AppNavigation/Settings/ImportScreen.vue#L50

(Button in import dialog, depending on how many calendars the user is importing)

For some reason, only singular version never ends up on Transifex, but the plural one does twice:
![55A79BE4-CEF2-4F82-9AF4-DE7127C885B3](https://user-images.githubusercontent.com/1250540/73075838-1cbb4f00-3ebd-11ea-9a3f-e34d549d2d1f.png)

**Comment by georgehrke** [comment]
Related calendar issue: https://github.com/nextcloud/calendar/issues/1897

**Comment by georgehrke** [comment]
cc @rullzer

**Comment by georgehrke** [comment]
Not exactly sure whether this is an issue in `t` or the translation extraction script we use.

**Comment by georgehrke** [comment]
also cc @nickvergessen, according to whom `n` without `%n` is not allowed.

**Comment by nickvergessen** [comment]
Yeah, so the thing is plurals `n()` should only be used, when a number is inserted. In languages with more than 1 plural rule, it otherwise gets very confusing. But there is help. In case you just want to express "many items", just use `t('Select calendars')`. Don't make 1 an exception for it and be done.

**Comment by Valdnet** [comment]
@georgehrke This has not been fixed in Calendar 2.0.2. The sentence "Import calendar" still appears without translation   :grimacing:.

**Comment by szaimen** [comment]
I cannot reproduce the issue anymore:
![image](https://user-images.githubusercontent.com/42591237/120176250-587bcc80-c207-11eb-865a-fc5d9bc3e590.png)
![image](https://user-images.githubusercontent.com/42591237/120176257-5ade2680-c207-11eb-8157-e4e180c9a146.png)
Please close this issue if it shouldn't be valid anymore. Thanks!
