### ISSUE TITLE
Downloads with IClient significantly slower compared to local curl

### ISSUE THREAD

**Issue by janis91** [nextcloud/server#19131]
### Steps to reproduce
1. In my app the `IRepairStep` [FetchTessdata](https://github.com/janis91/ocr/blob/master/lib/Migration/FetchTessdata.php) downloads a tar.gz file after installation ("post-migration" and "install"), if tessdata is not already available.
2. When users install the app or upgrade it to the version with that new workflow, the app installation crashes because of a curl timeout.
3. Users claim that downloading a file ~176MB shouldn't take that long on their server with 1Gbit/s connection.
4. I changed the timeout value in the meantime, but still experiencing way longer download time with the `OC\Http\Client` than with a local curl command on the same server, for instance.

### Expected behaviour
The download with the `OC\Http\Client` and the local curl command should take quite similar time.

### Actual behaviour
Like issued from some users, too, in the ocr repo: https://github.com/janis91/ocr/issues/249
The client stops after 30 second timeout. (I added a higher timeout for now, but I'm still sure, that the Client is significantly slower compared to a local curl command on the same server for example (in my case: ~12-15 seconds vs. <30 seconds for 176MB tar file).

### Server configuration

**Operating system:**
Different ones (for me it's FreeNAS)

**Web server:**
Different ones (for me it's nginx)

**Database:**
Mysql

**PHP version:**
7.2

**Nextcloud version:** (see Nextcloud admin page)
17

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated since v15

**Are you using external storage, if yes which one:** 
no

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
