### ISSUE TITLE
Group Folders additional rights setting shows every now and then

### ISSUE THREAD

**Issue by axel-rank** [nextcloud/server#19132]
Create a group folder, setup group permissions and additional rights.
Go to your files - Open your group folder - click share button:

![Bildschirmfoto_2020-01-25_13-17-12](https://user-images.githubusercontent.com/12480617/73121315-23a79780-3f79-11ea-90f1-f25c0fadd40b.png)

So far so good...
Navigate to settings, apps, user etc.
Go back to your group folder - click share button:

![Bildschirmfoto_2020-01-25_13-52-00](https://user-images.githubusercontent.com/12480617/73121393-e263b780-3f79-11ea-885b-215253936799.png)

Setting is gone!
Reload your browser, setting reappears, but only every now and then, sometimes you have to reload 3-4 times...sometimes it doesn't work at all...setting is gone.

**Comment by kesselb** [comment]
Please use the issue template to report bugs. To triage this add Nextcloud and Group Folders version to your report.

cc @wiswedel server or group folders repository?

**Comment by axel-rank** [comment]
Nextcloud 18.0.0, Groupfolders 6.0.0

**Comment by axel-rank** [comment]
Seems to be related only to Firefox (72.0.2).
Other Browsers (Chromium, Falkon) working.

**Comment by fschrempf** [comment]
Closing this as duplicate of https://github.com/nextcloud/groupfolders/issues/894.
