### ISSUE TITLE
Database access denied!

### ISSUE THREAD

**Issue by Pixxelcrasher** [nextcloud/server#19136]
Hello,
after I have moved my nextcloud installation to docker . I cant start it.. I only got this error:

{"reqId":"z5KD1NydPToFhjcolEIy","level":3,"time":"2020-01-25T20:49:29+00:00","remoteAddr":"87.122.106.159","user":"--","app":"mysql.setup","method":"POST","url":"/index.php","message":{"Exception":"Doctrine\\DBAL\\Exception\\ConnectionException","Message":"An exception occurred while executing 'CREATE DATABASE IF NOT EXISTS `nextcloud` CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':\n\nSQLSTATE[42000]: Syntax error or access violation: 1044 Access denied for user 'nextcloud'@'%' to database 'nextcloud'","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php","line":169,"function":"convertException","class":"Doctrine\\DBAL\\Driver\\AbstractMySQLDriver","type":"->","args":["An exception occurred while executing 'CREATE DATABASE IF NOT EXISTS `nextcloud` CHARACTER$

Please help me...
I have used this tutorial:
https://blog.ssdnodes.com/blog/installing-nextcloud-docker/

**Comment by MeiRos** [comment]
I would check your docker-compose file and see if you have the same db username and password there which you used when trying to start your Nextcloud.

**Comment by Pixxelcrasher** [comment]
I have checked that already... but thanks

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
