### ISSUE TITLE
Slow File Checking/Comparison Over Slow/Bad Internet Connection

### ISSUE THREAD

**Issue by pureche** [nextcloud/server#19134]
I'm currently using NextCloud overseas from my server. One of the major problem I have right now is that since I have a high latency to my server, about 100-1000ms, the whole file checking process is really slow. When I modify a file, it takes forever to go through all the files I have in the server to upload the ones I just modified.  I have 13GB of mixed files of all types. 

My internet speed isn't slow, it's just the latency. Is it possible to formulate a checksum file that contains everything on the server and download it to local to check against the file? Basically trading server and client CPU power to compensate for high latency on the internet. 

I'd love that as an option since I'm currently traveling overseas. I'm sure there's gotta be somebody who is also in my situation experiencing the same issue. 

Much appreciated.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
