### ISSUE TITLE
Error occured while updating my Nextcloud from 17.0.0 to 18.0.0.

### ISSUE THREAD

**Issue by qqice233** [nextcloud/server#19147]
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_flow_operations` SET `entity` = ? WHERE `entity` = ''' with params ["OCA\\WorkflowEngine\\Entity\\File"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'where clause'

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/18265
