### ISSUE TITLE
External Storge (local) causes high CPU and I/O with large files

### ISSUE THREAD

**Issue by david-kalbermatten** [nextcloud/server#19161]
### Steps to reproduce
1. Install linuxserver.io Docker version of Nextcloud 17.0.2
2. Install said Docker on UnRaid 6.8.2
3. Passthrough local resource from host ([host]/mnt/user/Peter -> [docker]/external/Peter)
4. Setup external storage plugin with local resource (/external/Peter)
5. Setup reverse proxy (nextcloud.yourdomain.com)
6. Try to download large file (file > 20 Gb)
7. Causes 100% CPU load and & 100% I/O on Raid Array even though the Download is significantly slower than what is being read from the array via external storage plugin

### Expected behavior
The Download should only cause as much read speed as the Download speed. The CPU usage and Disk usage should stop as soon as the download is aborted. Downloading from Nextcloud Storage doesn't seem to cause this issue, only downloading from external storage does...

### Actual behavior
Even after the download has been aborted/crashed, Nextcloud continues to read from the array at full speed and causes 100% CPU usage on the host...
My guess is that the External Storage plugin caches/buffers no matter what kind of 'external storage' is used, which results in crazy high I/O. The reason I believe that this is the issue is the fact that I can only see such a high usage for an extended period of time when handling large files. Smaller files are cached/buffered much faster and don't cause problems. However, if I try to download big files > 30GB, the whole thing just stops after a while and becomes unresponsive...

I have a very similar setup with CrushFTP v8 where I also pass-through local Unraid resources to be used with CrushFTP-Docker. There, I'm only speed limited by the reverse proxy (40 MB/s instead of 100 MB/s) which is plenty fast for me. 

### Server configuration

**Operating system:**
Unraid 6.8.2
**Web server:**

**Database:**
MariaDB
**PHP version:**
7.3.13
**Nextcloud version:** (see Nextcloud admin page)
17.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
16.x
**Where did you install Nextcloud from:**
Docker installtion from linuxserver.io
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.5.0
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - deck: 0.8.0
  - drawio: 0.9.4
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.0.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - unsplash: 1.1.4
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - files_external_onedrive
  - sharepoint
  - sharingpath
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.10:1723",
            "www.invictech.ch:1723",
            "invictech.ch:1723",
            "tower.local:1723",
            "invictech.ddns.net:1723",
            "185.71.114.15:1723",
            "nextcloud.invictech.ch"
        ],
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "overwrite.cli.url": "https:\/\/192.168.178.10:1723",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10 Pro 1903
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Not getting any errors since I fixed the bigint issue with my MariaDB installation
```
</details>

**Comment by pupboss** [comment]
Not only external storage, same problem with local data repository. See https://github.com/nextcloud/server/issues/22334 and https://github.com/nextcloud/server/issues/22276

**Comment by apryaldy** [comment]
Still happening though until now
I am using NextCloud version 21 with PHP 7.4 & MariaDB 10.3
And using external storage
Please advise.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/viewer/issues/894
