### ISSUE TITLE
Can't access "users" page in NC 17.0.2 - this.settings.quotaPreset.reduce is not a function

### ISSUE THREAD

**Issue by sabl0r** [nextcloud/server#19162]
### Steps to reproduce
1. Login as admin
2. To to "Users" page

### Expected behaviour
List of current users should be visible.

### Actual behaviour
Empty page.
Javascript error:
![Screenshot from 2020-01-27 15-01-31](https://user-images.githubusercontent.com/1169879/73180630-fba16b00-4115-11ea-97b5-9789ccc6c9be.png)

TypeError: "this.settings.quotaPreset.reduce is not a function"

### Server configuration

**Operating system:** Linux

**Web server:** Apache 2.4.41

**Database:** MySQL 5.6.45

**PHP version:** 7.3.14

**Nextcloud version:** 17.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updates from 16.x.x

**Where did you install Nextcloud from:** tgz file

**Signing status:**
<details>
<summary>Signing status</summary>

```
Raw output
==========
Array
(
    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => 06b250c3a2c2ae01c8a2c4b963d6449c99645dca36ee197c3aa513fb7ac3e90e42dc1408ee6957408d85f9f9a973b8983719e9c15125d42211d43f0853c7bf75
                            [current] => e5da848ca44b3b60abb1c99a3d26455d78464f94ea1f5f522b07d642096a771dcde9a1a5289e271805292659edc42925a86b5d6ad22ffa98b79ecec5bfed69ff
                        )

                    [lib/smb.php] => Array
                        (
                            [expected] => 283a99667fd865e54423d575953423bc6e15862b7683885cb5675aafdb3b2cbc1400a1318ec81cdbd90ce827c3f839aa6daf6a0f6e3ac6bd2742947498dd14f9
                            [current] => 1c12005d92f88017564fb4135a532810aab33ffab22eac67c19501a59d213518e417cceb83f5e9ea4b448ea81fff3149da37eefb0100a61bce3140ce67f8decc
                        )

                )

        )

)
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - calendar: 2.0.1
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_external: 0.8.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.2.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "debug": true,
        "log_type": "owncloud",
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "loglevel": 0,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "forcessl": true,
        "theme": "",
        "default_language": "de",
        "appstoreenabled": true,
        "trusted_domains": [
            "cloud.xxx.de"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "share_folder": "\/Shared",
        "user_backends": [
            {
                "class": "OC_User_FTP",
                "arguments": [
                    "localhost"
                ]
            }
        ],
        "trashbin_retention_obligation": "auto",
        "appstore.experimental.enabled": true,
        "overwrite.cli.url": "https:\/\/cloud.xxx.de"
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** FTP

### Client configuration
**Browser:** Firefox 72.0.1

**Operating system:** Linux

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

No logs are written while accessing the users page.
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
![Screenshot from 2020-01-27 15-01-31](https://user-images.githubusercontent.com/1169879/73180630-fba16b00-4115-11ea-97b5-9789ccc6c9be.png)

TypeError: "this.settings.quotaPreset.reduce is not a function"
```
</details>

**Comment by sabl0r** [comment]
Same issue still exists in v18.0.1

**Comment by kesselb** [comment]
cc @violoncelloCH could that be related to user external? Does the ftp backend supports / reports quota?

**Comment by violoncelloCH** [comment]
@kesselb user_external doesn't do anything with the quota... this is handled by the server, isn't it?

**Comment by kesselb** [comment]
@sabl0r `php occ config:app:get files quota_preset` do you have a custom value for quota_preset?

**Comment by sabl0r** [comment]
$ php occ config:app:get files quota_preset
default, none, 1 GB, 5 GB, 10 GB, 25 GB

**Comment by kesselb** [comment]
Are you able to use the users page again if you delete quota_preset? `php occ config:app:delete files quota_preset`

**Comment by sabl0r** [comment]
Yes, sir!

**Comment by kesselb** [comment]
You set it to `default, none, 1 GB, 5 GB, 10 GB, 25 GB` on purpose? I understand `1 GB, 5 GB, 10 GB, 25 GB` but `default and none` are internals.

**Comment by sabl0r** [comment]
I don't think that this was set on purpose. Don't know where it's coming from.
