### ISSUE TITLE
Files moved to trash bin from external storage are missing in object store setup

### ISSUE THREAD

**Issue by vpecinka** [nextcloud/server#19171]
Hi, this is experienced with NC 16.0.7 but I think this is a hidden "bomb" in the mixed storages setup.

Steps:
1. Have object store (Swift) setup with your NC
2. Add external storage (Samba in my case) with some files and dirs
3. Remove a file from the external storage via NC
4. You can find the file in trash bin, however you cannot restore it

The reason, I guess, is that moving to trash bin means altering `oc_filecache` record only and not touching the file in the object store. That makes sense until we mix file storages.

**Comment by acs-ferreira** [comment]
Confirmed here:
- Primary: S3
- External: WebDAV

When restore was attempted (file deleted from the WebDAV):
```
[PHP] Error: fopen(http://10.1.0.2:8080/bucket/urn%3Aoid%3A1924): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 at /lib/private/Files/ObjectStore/S3ObjectTrait.php#70

MOVE /remote.php/dav/trashbin/user/trash/Installer-7.2.5.32097.exe.d1580216890
```
and
```
[PHP] Error: fclose() expects parameter 1 to be resource, bool given at /lib/private/Files/Storage/Common.php#627

MOVE /remote.php/dav/trashbin/user/trash/Installer-7.2.5.32097.exe.d1580216890
```

**Comment by kesselb** [comment]
cc @icewind1991 @rullzer

**Comment by kesselb** [comment]
Another report about this issue #18132

**Comment by acsfer** [comment]
Fixed by https://github.com/nextcloud/server/pull/21628
