### ISSUE TITLE
Problem Sharing: Automatic Reply Problem

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/server#1918]
Hi,

I am running nextcloud 10.0.1 in a smaller environment ( 25 ppl ) using apache2 using the latest php7.
Some of my users noticed something problematic, when sharing something via link there is the option to send the link to someone via email.
The problem is when there is something like holiday away email, wrong email address oa the return email gets to the server and not to the user itself. 

In my case someone send such a link to a buddy, who was on vacation at the time, the return email that he is away was send to me and not to the user.

Is it possible to get a feature to forward any email from this function to the email address of the user? If they have one in their profile.
### Steps to reproduce
1. upload stuff to your cloud
2. share it via link
3. use the "share link via Email" function
4. sending to a buddy who's email account automatically replies with something.
### Expected behavior

The reply email gets send to the user itself and not the default email from the cloud install. So the user gets the info.
### Actual behavior

The reply email gets to the default send email from the cloud install and not the email address of the user who actually shared the link.
### Server configuration

**Operating system**:
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server loaded:  APR 1.5.1, APR-UTIL 1.5.4
Compiled using: APR 1.5.1, APR-UTIL 1.5.4
Architecture:   64-bit
Server MPM:     prefork
  threaded:     no
    forked:     yes (variable process count)

**Database:**
mysql  Ver 14.14 Distrib 5.5.52, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 7.0.12-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
version: 9.1.1.5
versionstring: 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 9 to 10 to 10.0.1

**Where did you install Nextcloud from:**
nextcloud homepage

**List of activated apps:**
<details>
<summary>

App list</summary>

```
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.1
  - direct_menu: 0.9.2
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - news: true
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
```

</details>

**The content of config/config.php:**
<details>
<summary>

Config report</summary>

```
//Default Parameters
  'trusted_domains' =>
  array (
    0 => 'cloud.magicbroccoli.de',
  ),
  'version' => '9.1.1.5',
  'installed' => true,
  'cipher' => 'AES-256-CFB',

//Database
  'dbtype' => 'mysql',

//User Experience
  'defaultapp' => 'files',
  'enable_avatars' => true,
  'allow_user_to_change_display_name' => false,
  'remember_login_cookie_lifetime' => 1296000,
  'session_lifetime' => 86400,
  'auth.bruteforce.protection.enabled' => true,

//Mail Parameters
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'nextcloud',
  'mail_domain' => 'magicbroccoli.de',

//Nextcloud Verifications
  'appcodechecker' => true,
  'updatechecker' => true,
  'updater.server.url' => 'https://updates.nextcloud.com/updater_server/',
  'has_internet_connection' => true,
  'check_for_working_htaccess' => true,
  'check_for_working_webdav' => true,
  'check_for_working_wellknown_setup' => true,

//Logging
  'logdateformat' => 'd.m.Y - H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'log_rotate_size' => 52428800,
  'loglevel' => 2,
  'logfile' => '/var/log/nextcloud/nextcloud.log',

//Apps
  'appstoreenabled' => true,
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
  'appstore.experimental.enabled' => false,

//Memory caching
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'redis' =>
        array (
//              'host' => 'localhost',
//              'port' => 6370,
                'host' => '/var/run/redis/redis.sock',
                'port' => 0,
                'timeout' => 0,
                'dbindex' => 0,
        ),

//Previews
  'enable_previews' => true,
  'preview_max_x' => 1024,
  'preview_max_y' => 1024,

//Proxy
  'htaccess.RewriteBase' => '/',

//Deleted Items and Versions
  'trashbin_retention_obligation' => 'auto, 60',
  'versions_retention_obligation' => 'auto',
  'activity_expire_days' => 160,

//Other
  'filesystem_check_changes' => 0,
  'theme' => '',
  'maintenance' => false,
  'singleuser' => false,
);

```

</details>

**Comment by nickvergessen** [comment]
This is not possible, because not email addresses can be used as sender address by any mail server. Also we are currently discussing the removal of this feature:
https://github.com/nextcloud/server/issues/1916

**Comment by schiessle** [comment]
I agree with @nickvergessen so let's close it.
