### ISSUE TITLE
Date picker should comply with user locale

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#19198]
Currently the date picker date format does not comply with the user locale.

Let's try to add that to the vue datepicker and dispatch for 18 & 19

**Comment by skjnldsv** [comment]
Related https://github.com/nextcloud/server/pull/14784

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
