### ISSUE TITLE
Invitation or update emails are not send to meeting attendees when event is synced by external CalDAV client

### ISSUE THREAD

**Issue by strenker** [nextcloud/server#19197]
### Steps to reproduce
1. Create or update event in an external (e.g. Android Calendar Client (e.g. PersonalCalendar))
2. Synchronize new or updated event via external DAV client (e.g. DAVx^5)

### Expected behaviour
Event or event update should be synced and invitation or update emails should be sent to all attendees.

### Actual behaviour
No emails are sent.
Nb.: when the internal Nextcloud-Calendar Client is used to create or update en event, then Invitation emails are sent (event updates are not sent ... at least when the event-locaton is updated). 

### Server configuration

**Operating system:** Synology DSM 6.2.2-24922 Update 4 on DS718+ NAS

**Web server:** Apache 2.4

**Database:** MariaDB 10

**PHP version:** 7.2

**Nextcloud version:** 18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 17.0.x

**Where did you install Nextcloud from:** Official download zip

**Signing status:**

<details>
<summary> No errors have been found</summary>
</details>

**List of activated apps:**
<details>
<summary>Apps</summary>
Enabled:
  - accessibility: 1.4.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - activity
  - admin_audit
  - encryption
  - federation
  - recommendations
</details>

**Nextcloud configuration:**
<details>
<summary>NC config</summary>
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.trenker.xyz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/nextcloud.trenker.xyz",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": "2",
        "forcessl": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "log_rotate_size": 20971520,
        "logtimezone": "Europe\/Berlin",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "theme": "",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp"
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enable_email": "no",
            "enabled": "no",
            "installed_version": "2.7.0",
            "types": "filesystem"
        },
        "admin_dependencies_chk": {
            "enabled": "no",
            "installed_version": "0.02",
            "ocsid": "166041",
            "types": ""
        },
        "admin_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "backgroundjob": {
            "lastjob": "360673"
        },
        "bruteforcesettings": {
            "enabled": "no",
            "installed_version": "1.2.0",
            "types": ""
        },
        "calendar": {
            "enabled": "yes",
            "installed_version": "2.0.1",
            "signed": "true",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "configreport": {
            "enabled": "no",
            "installed_version": "0.1.1",
            "types": "filesystem"
        },
        "contacts": {
            "enabled": "yes",
            "installed_version": "3.1.8",
            "signed": "true",
            "types": ""
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "backgroundjobs_step": "queued_tasks",
            "backgroundjobs_task": "OC_Cache_FileGlobal-gc",
            "enterpriseLogoChecked": "yes",
            "global_cache_gc_lastrun": "1436597102",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1545044955.5172",
            "lastcron": "1580300706",
            "lastupdateResult": "[]",
            "lastupdatedat": "1580300242",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "outgoing_server2server_share_enabled": "no",
            "previewsCleanedUp": "1",
            "public_caldav": "calendar\/share.php",
            "public_calendar": "calendar\/share.php",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_gallery": "gallery\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_ampache": "media\/remote.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_contactthumbnail": "contacts\/thumbnail.php",
            "remote_core.css": "\/core\/minimizer.php",
            "remote_core.js": "\/core\/minimizer.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_filesync": "files\/appinfo\/filesync.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "db81cddf52fdb3c8ca1e4c859e214124",
            "shareapi_allow_public_upload": "no",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "updater.secret.created": "1566043910",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventRemindersPush": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "dav"
        },
        "direct_menu": {
            "enabled": "no",
            "installed_version": "0.9.2",
            "ocsid": "169148",
            "signed": "true",
            "types": ""
        },
        "documents": {
            "converter": "local",
            "enabled": "no",
            "installed_version": "0",
            "ocsid": "168711",
            "types": "",
            "unstable": "false"
        },
        "external": {
            "enabled": "no",
            "installed_version": "1.2",
            "ocsid": "166046",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "no",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "backgroundwatcher_previous_file": "895",
            "backgroundwatcher_previous_folder": "1384",
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem",
            "user_mounting_backends": "\\OC\\Files\\Storage\\AmazonS3,\\OC\\Files\\Storage\\Dropbox,\\OC\\Files\\Storage\\FTP,\\OC\\Files\\Storage\\Google,\\OC\\Files\\Storage\\Swift,\\OC\\Files\\Storage\\OwnCloud,\\OC\\Files\\Storage\\SFTP,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB,\\OC\\Files\\Storage\\SMB_OC,\\OC\\Files\\Storage\\DAV"
        },
        "files_imageviewer": {
            "enabled": "no",
            "installed_version": "1.0"
        },
        "files_locking": {
            "enabled": "no",
            "installed_version": "",
            "types": "filesystem"
        },
        "files_odfviewer": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "cronjob_user_offset": "1000",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_videoviewer": {
            "enabled": "no",
            "installed_version": "0.1.3",
            "ocsid": "166054",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "galleryplus": {
            "enabled": "no",
            "installed_version": "14.3.0",
            "ocsid": "169116",
            "types": ""
        },
        "gpxpod": {
            "enabled": "no",
            "installed_version": "2.3.2",
            "types": ""
        },
        "groupfolders": {
            "enabled": "yes",
            "installed_version": "6.0.0",
            "types": "filesystem,dav"
        },
        "internal_bookmarks": {
            "enabled": "no",
            "installed_version": "2.1.3",
            "types": ""
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "provisioning_settings": "{\"active\":false,\"version\":1,\"email\":\"%USERID%@trenker.xyz\",\"imapUser\":\"%USERID%@trenker.xyz\",\"imapHost\":\"mail.trenker.xyz\",\"imapPort\":993,\"imapSslMode\":\"ssl\",\"smtpUser\":\"%USERID%@trenker.xyz\",\"smtpHost\":\"mail.trenker.xyz\",\"smtpPort\":587,\"smtpSslMode\":\"tls\"}",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "notification_groups": "[\"admin\",\"updatenotify\"]",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "yes",
            "installed_version": "3.1.1",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "enforceNumericCharacters": "0",
            "enforceUpperLowerCase": "0",
            "installed_version": "1.8.0",
            "types": ""
        },
        "pcsg_rescan": {
            "enabled": "no",
            "installed_version": "0.1.1",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "qownnotesapi": {
            "enabled": "no",
            "installed_version": "18.11.0",
            "types": ""
        },
        "recommendations": {
            "enabled": "no",
            "installed_version": "0.6.0",
            "types": ""
        },
        "search_lucene": {
            "enabled": "no",
            "installed_version": "0.7.0",
            "ocsid": "168709",
            "types": "filesystem"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "storagecharts2": {
            "enabled": "no",
            "installed_version": "2.6.1",
            "ocsid": "165528",
            "types": ""
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "last_report": "{\"id\":\"ocojjo0u6exs\",\"items\":[[\"server\",\"version\",\"18.0.0.10\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"cron\"],[\"php\",\"version\",\"7.2.24\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",0],[\"php\",\"upload_max_filesize\",2147483648],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.3.21\"],[\"database\",\"size\",428048384],[\"apps\",\"accessibility\",\"1.4.0\"],[\"apps\",\"activity\",\"disabled\"],[\"apps\",\"admin_dependencies_chk\",\"disabled\"],[\"apps\",\"admin_migrate\",\"disabled\"],[\"apps\",\"bruteforcesettings\",\"disabled\"],[\"apps\",\"calendar\",\"2.0.1\"],[\"apps\",\"cloud_federation_api\",\"1.1.0\"],[\"apps\",\"comments\",\"1.8.0\"],[\"apps\",\"configreport\",\"disabled\"],[\"apps\",\"contacts\",\"3.1.6\"],[\"apps\",\"dav\",\"1.14.0\"],[\"apps\",\"deck\",\"0.8.0\"],[\"apps\",\"direct_menu\",\"disabled\"],[\"apps\",\"documents\",\"disabled\"],[\"apps\",\"external\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.8.0\"],[\"apps\",\"federation\",\"disabled\"],[\"apps\",\"files\",\"1.13.1\"],[\"apps\",\"files_external\",\"1.9.0\"],[\"apps\",\"files_imageviewer\",\"disabled\"],[\"apps\",\"files_locking\",\"disabled\"],[\"apps\",\"files_odfviewer\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.7.0\"],[\"apps\",\"files_rightclick\",\"0.15.2\"],[\"apps\",\"files_sharing\",\"1.10.1\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.8.0\"],[\"apps\",\"files_versions\",\"1.11.0\"],[\"apps\",\"files_videoplayer\",\"1.7.0\"],[\"apps\",\"files_videoviewer\",\"disabled\"],[\"apps\",\"firstrunwizard\",\"2.7.0\"],[\"apps\",\"gallery\",\"disabled\"],[\"apps\",\"galleryplus\",\"disabled\"],[\"apps\",\"gpxpod\",\"disabled\"],[\"apps\",\"groupfolders\",\"6.0.0\"],[\"apps\",\"internal_bookmarks\",\"disabled\"],[\"apps\",\"logreader\",\"2.3.0\"],[\"apps\",\"lookup_server_connector\",\"1.6.0\"],[\"apps\",\"mail\",\"1.0.0\"],[\"apps\",\"nextcloud_announcements\",\"1.7.0\"],[\"apps\",\"notes\",\"3.1.1\"],[\"apps\",\"notifications\",\"2.6.0\"],[\"apps\",\"oauth2\",\"1.6.0\"],[\"apps\",\"password_policy\",\"1.8.0\"],[\"apps\",\"pcsg_rescan\",\"disabled\"],[\"apps\",\"photos\",\"1.0.0\"],[\"apps\",\"privacy\",\"1.2.0\"],[\"apps\",\"provisioning_api\",\"1.8.0\"],[\"apps\",\"qownnotesapi\",\"disabled\"],[\"apps\",\"recommendations\",\"disabled\"],[\"apps\",\"search_lucene\",\"disabled\"],[\"apps\",\"serverinfo\",\"1.8.0\"],[\"apps\",\"settings\",\"1.0.0\"],[\"apps\",\"sharebymail\",\"1.8.0\"],[\"apps\",\"storagecharts2\",\"disabled\"],[\"apps\",\"support\",\"1.1.0\"],[\"apps\",\"survey_client\",\"1.6.0\"],[\"apps\",\"systemtags\",\"1.8.0\"],[\"apps\",\"tasks\",\"disabled\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"text\",\"2.0.0\"],[\"apps\",\"theming\",\"1.9.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.7.0\"],[\"apps\",\"twofactor_totp\",\"4.1.2\"],[\"apps\",\"updatenotification\",\"1.8.0\"],[\"apps\",\"updater\",\"disabled\"],[\"apps\",\"user_ldap\",\"1.8.0\"],[\"apps\",\"user_migrate\",\"disabled\"],[\"apps\",\"videos\",\"disabled\"],[\"apps\",\"viewer\",\"1.2.0\"],[\"apps\",\"workflowengine\",\"2.0.0\"],[\"stats\",\"num_files\",314853],[\"stats\",\"num_users\",5],[\"stats\",\"num_storages\",60],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",6],[\"stats\",\"num_storages_other\",52],[\"stats\",\"num_comments\",0],[\"stats\",\"num_comment_markers\",0],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",17],[\"files_sharing\",\"num_shares_user\",17],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",0],[\"files_sharing\",\"num_shares_link_no_password\",0],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"5\"],[\"files_sharing\",\"permissions_0_15\",\"3\"],[\"files_sharing\",\"permissions_0_17\",\"7\"],[\"files_sharing\",\"permissions_0_19\",\"1\"],[\"files_sharing\",\"permissions_0_31\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1580076915",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "4.1.2",
            "types": ""
        },
        "updatenotification": {
            "calendar": "2.0.1",
            "contacts": "3.1.8",
            "core": "16.0.7.1",
            "enabled": "[\"admin\",\"updatenotify\"]",
            "files_pdfviewer": "1.2.1",
            "files_rightclick": "0.15.1",
            "installed_version": "1.8.0",
            "mail": "1.1.1",
            "notes": "3.1.1",
            "notify_groups": "[\"admin\",\"updatenotify\"]",
            "theming": "1.4.5",
            "twofactor_totp": "3.0.1",
            "types": "",
            "update_check_errors": "0"
        },
        "updater": {
            "enabled": "no",
            "installed_version": "0.6",
            "types": ""
        },
        "user_ldap": {
            "background_sync_interval": "43200",
            "background_sync_offset": "0",
            "background_sync_prefix": "s01",
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "s01_lastChange": "1580299504",
            "s01has_memberof_filter_support": "1",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "ldaps:\/\/ldap2.trenker.xyz",
            "s01ldap_backup_port": "636",
            "s01ldap_base": "dc=trenker,dc=xyz",
            "s01ldap_base_groups": "dc=trenker,dc=xyz",
            "s01ldap_base_users": "dc=trenker,dc=xyz",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "gecos",
            "s01ldap_dn": "uid=root,cn=users,dc=trenker,dc=xyz",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "uid",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "uniqueMember",
            "s01ldap_groupfilter_groups": "",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "ldaps:\/\/ldap1.trenker.xyz",
            "s01ldap_login_filter": "(&(&(|(objectclass=posixAccount))(|(memberof=cn=nextclouduser,cn=groups,dc=trenker,dc=xyz)))(!(shadowExpire=1))(objectClass=shadowAccount)(uid=%uid))",
            "s01ldap_login_filter_mode": "1",
            "s01ldap_loginfilter_attributes": "",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "636",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "0",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_avatar_rule": "default",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "nextclouduser",
            "s01ldap_userfilter_objectclass": "posixAccount",
            "s01ldap_userlist_filter": "(&(|(objectclass=posixAccount))(|(memberof=cn=nextclouduser,cn=groups,dc=trenker,dc=xyz)))",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "user_migrate": {
            "enabled": "no",
            "installed_version": "0.1"
        },
        "videos": {
            "enabled": "no",
            "installed_version": "1.0",
            "ocsid": "161584",
            "types": ""
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration
<details>
<summary>LDAP config</summary>
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                   |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                     |
| homeFolderNamingRule          |                                                                                                                                                       |
| lastJpegPhotoLookup           | 0                                                                                                                                                     |
| ldapAgentName                 | uid=root,cn=users,dc=trenker,dc=xyz                                                                                                                   |
| ldapAgentPassword             | ***                                                                                                                                                   |
| ldapAttributesForGroupSearch  |                                                                                                                                                       |
| ldapAttributesForUserSearch   |                                                                                                                                                       |
| ldapBackupHost                | ldaps://ldap2.trenker.xyz                                                                                                                             |
| ldapBackupPort                | 636                                                                                                                                                   |
| ldapBase                      | dc=trenker,dc=xyz                                                                                                                                     |
| ldapBaseGroups                | dc=trenker,dc=xyz                                                                                                                                     |
| ldapBaseUsers                 | dc=trenker,dc=xyz                                                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                                                   |
| ldapConfigurationActive       | 1                                                                                                                                                     |
| ldapDefaultPPolicyDN          |                                                                                                                                                       |
| ldapDynamicGroupMemberURL     |                                                                                                                                                       |
| ldapEmailAttribute            | mail                                                                                                                                                  |
| ldapExperiencedAdmin          | 0                                                                                                                                                     |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                       |
| ldapExpertUUIDUserAttr        |                                                                                                                                                       |
| ldapExpertUsernameAttr        | uid                                                                                                                                                   |
| ldapExtStorageHomeAttribute   |                                                                                                                                                       |
| ldapGidNumber                 | gidNumber                                                                                                                                             |
| ldapGroupDisplayName          | cn                                                                                                                                                    |
| ldapGroupFilter               |                                                                                                                                                       |
| ldapGroupFilterGroups         |                                                                                                                                                       |
| ldapGroupFilterMode           | 0                                                                                                                                                     |
| ldapGroupFilterObjectclass    |                                                                                                                                                       |
| ldapGroupMemberAssocAttr      | uniqueMember                                                                                                                                          |
| ldapHost                      | ldaps://ldap1.trenker.xyz                                                                                                                             |
| ldapIgnoreNamingRules         |                                                                                                                                                       |
| ldapLoginFilter               | (&(&(|(objectclass=posixAccount))(|(memberof=cn=nextclouduser,cn=groups,dc=trenker,dc=xyz)))(!(shadowExpire=1))(objectClass=shadowAccount)(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                       |
| ldapLoginFilterEmail          | 0                                                                                                                                                     |
| ldapLoginFilterMode           | 1                                                                                                                                                     |
| ldapLoginFilterUsername       | 1                                                                                                                                                     |
| ldapNestedGroups              | 0                                                                                                                                                     |
| ldapOverrideMainServer        |                                                                                                                                                       |
| ldapPagingSize                | 500                                                                                                                                                   |
| ldapPort                      | 636                                                                                                                                                   |
| ldapQuotaAttribute            |                                                                                                                                                       |
| ldapQuotaDefault              |                                                                                                                                                       |
| ldapTLS                       | 0                                                                                                                                                     |
| ldapUserAvatarRule            | default                                                                                                                                               |
| ldapUserDisplayName           | gecos                                                                                                                                                 |
| ldapUserDisplayName2          |                                                                                                                                                       |
| ldapUserFilter                | (&(|(objectclass=posixAccount))(|(memberof=cn=nextclouduser,cn=groups,dc=trenker,dc=xyz)))                                                            |
| ldapUserFilterGroups          | nextclouduser                                                                                                                                         |
| ldapUserFilterMode            | 0                                                                                                                                                     |
| ldapUserFilterObjectclass     | posixAccount                                                                                                                                          |
| ldapUuidGroupAttribute        | auto                                                                                                                                                  |
| ldapUuidUserAttribute         | auto                                                                                                                                                  |
| turnOffCertCheck              | 0                                                                                                                                                     |
| turnOnPasswordChange          | 0                                                                                                                                                     |
| useMemberOfToDetectMembership | 1                                                                                                                                                     |
+-------------------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------+
</details>

### Client configuration
**Browser:** Calendar App: PersonalCalendar, Sync App: DAVx^5

**Operating system:** Android 9

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>See attachment</summary>
[nextcloud.log.1.gz](https://github.com/nextcloud/server/files/4127977/nextcloud.log.1.gz)
[nextcloud.log.gz](https://github.com/nextcloud/server/files/4127978/nextcloud.log.gz)
</details>

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Seems to be similar to https://github.com/nextcloud/server/issues/17810?

**Comment by strenker** [comment]
Yes, that's correct. Sorry for not finding it in my earlier search efforts.

This is a really annoying bug, since using the web-client on a mobile phone is quite impractical.
And just updates of start/end-time fields fire updates in the web-client. Changes of other event attributes like location or description fields do not fire update mails (which is a bug as well).

**Comment by alexandrebln** [comment]
I encoutered the same issue.
I gave some additional information on the help form, I hope it can helps : https://help.nextcloud.com/t/nextcloud-calendar-not-sending-invitation-when-creating-from-android-app/69363/3 .
