### ISSUE TITLE
Upgrade NC to 18 or modifying config.php and "occ maintenance:update:htaccess" breaks onlyoffice integration

### ISSUE THREAD

**Issue by trendchiller** [nextcloud/server#19205]
Hi !

After upgrading a few systems to NC18 the OnlyOffice Integration does not work:
There is no possibility to create OO files or opening them and the OO menu does not show any options.
_After the Upgrade we executed
php7.3-cli Sites/xxx.xxx.de/occ app:install documentserver_community
php7.3-cli Sites/xxx.xxx.de/occ app:install onlyoffice_

The same issue arises after a fresh install (where OO works) and adding
  _'overwrite.cli.url' => 'https://nc.xxx.xxx',
  'overwriteprotocol' => 'https',
  'htaccess.RewriteBase' => '/',
  'htaccess.IgnoreFrontController' => true,_
to config.php and then executing _occ maintenance:update:htaccess_

no more OO integration

after that we always get error:
> Fehler beim Anschließen (Client error: `POST https://nc.xxx.xxx/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `403 Forbidden` response: <!DOCTYPE html> <html> <head> <meta charset="utf-8"> <style type="text/css"> html, body, (truncated...) )

The Log shows:

> [onlyoffice] Error: CommandRequest on check error: Client error: `POST https://nc.xxx.xxx/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `403 Forbidden` response:
> <!DOCTYPE html>
> <html>
>     <head>
>         <meta charset="utf-8">
>         <style type="text/css">
>             html, body, (truncated...)
> 
> 
> PUT /apps/onlyoffice/ajax/settings/address

Reinstalling solves the issue and as soon as we change the values again in config.php the issue is back and not repairable (to us)

### Server configuration

**Operating system:**
Linux infong-uk4 4.4.0-ui19255.033-uiabi1-infong-amd64 #1 SMP Debian 4.4.192-1~ui80+1 (2019-09-12) x86_64 GNU/Linux

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
PHP 4.4.9 (cgi-fcgi) (built: Aug 29 2019 12:59:15)
Copyright (c) 1997-2008 The PHP Group
Zend Engine v1.3.0, Copyright (c) 1998-2004 Zend Technologies
(uiserver):u96648038:~/Sites/cl-st.fuchs-kiel.de$ php7.3-cli -v
PHP 7.3.14 (cli) (built: Jan 27 2020 10:18:20) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
both

**Where did you install Nextcloud from:**
ZIP-file

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - documentserver_community: 0.1.4
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.0
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - groupfolders: 6.0.0
  - hsts: 0.3.0
  - impersonate: 1.5.0
  - keeweb: 0.6.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 5.0.6
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - rainloop: 6.0.6
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - sharerenamer: 2.7.3
  - socialsharing_email: 1.0.6
  - spreed: 8.0.1
  - support: 1.1.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - circles
  - drawio
  - encryption
  - files_external
  - files_mindmap
  - firstrunwizard
  - survey_client
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.xxx.xxx"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/nc.xxx.xxx",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "htaccess.IgnoreFrontController": true,
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "loglevel": 2,
        "skeletondirectory": "",
        "share_folder": "\/Mit mir geteilt",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_sendmailmode": "pipe",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "socialsharing_email",
            "keeweb",
            "sharerenamer",
            "files_mindmap",
            "hsts",
            "drawio"
        ]
    }
}

</details>

**Comment by kesselb** [comment]
> 'htaccess.IgnoreFrontController' => true,

Have you tried without ignoreFrontController? mod_env seems to be available for Ionos: https://www.ionos.de/hilfe/hosting/htaccess/verfuegbare-apache-module/

**Comment by trendchiller** [comment]
I tried,but i am not able to get it running again after it broke one time.
So even with ahh settings reverted in config.php and regenerated htaccess OO is not working anymore...
Any hint where to look for this ?

**Comment by kesselb** [comment]
Ah. You probably have to change the document server url with the only_office app. It's setup by default if empty to document_server. A change to the url structure is probably not expected.

**Comment by kesselb** [comment]
`curl -X POST https://cloud.fuchs-kiel.de/apps/documentserver_community/coauthoring/CommandService.ashx`

`curl -X POST https://cloud.fuchs-kiel.de/index.php/apps/documentserver_community/coauthoring/CommandService.ashx`

Both requests return http status 500. What does the logs say?

**Comment by trendchiller** [comment]
I‘ll have to look at the logs. 
I’ll have to check with IONOS where to find then. 
But what irritates me is that another IONOS instance upgraded without issues. 
It is completely configured the same way. 
I will keep you informed.

**Comment by trendchiller** [comment]
IONOS does not provide httpd error logs, only access and php error logs.
Do you think PHP error logs will help ?

**Comment by kesselb** [comment]
I would start with nextcloud.log in the datadirectory.

**Comment by trendchiller** [comment]
I tried to interpret but i cannot understand :-(
the nextcloud.log shows:

{"reqId":"XjiYSFKlUxoAAOukxuEAAAAh","level":3,"time":"2020-02-03T22:01:45+00:00","remoteAddr":"87.122.79.0","user":"--","app":"index","method":"POST","url":"/apps/documentserver_community/coauthoring/CommandService.ashx","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\DocumentServer\\Controller\\CoAuthoringController::command() must be of the type string, null given, called in /homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\CoAuthoringController"},"command"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\CoAuthoringController","command",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/coauthoring/CommandService.ashx"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\DocumentServer\\Controller\\CoAuthoringController::command() must be of the type string, null given, called in /homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"command","class":"OCA\\DocumentServer\\Controller\\CoAuthoringController","type":"->","args":[null]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\CoAuthoringController"},"command"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\CoAuthoringController"},"command"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\CoAuthoringController","command",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/coauthoring/CommandService.ashx"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/apps/documentserver_community/lib/Controller/CoAuthoringController.php","Line":33},"CustomMessage":"--"},"userAgent":"curl/7.64.1","version":"18.0.0.10"}

{"reqId":"XjiYq1KlUxoAARd@acUAAAAB","level":3,"time":"2020-02-03T22:03:23+00:00","remoteAddr":"87.122.79.0","user":"--","app":"index","method":"POST","url":"/index.php/apps/documentserver_community/coauthoring/CommandService.ashx","message":{"Exception":"Exception","Message":"Argument 1 passed to OCA\\DocumentServer\\Controller\\CoAuthoringController::command() must be of the type string, null given, called in /homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\CoAuthoringController"},"command"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\CoAuthoringController","command",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/coauthoring/CommandService.ashx"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OCA\\DocumentServer\\Controller\\CoAuthoringController::command() must be of the type string, null given, called in /homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"command","class":"OCA\\DocumentServer\\Controller\\CoAuthoringController","type":"->","args":[null]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\CoAuthoringController"},"command"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\DocumentServer\\Controller\\CoAuthoringController"},"command"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\DocumentServer\\Controller\\CoAuthoringController","command",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"documentserver_community.CoAuthoring.command"}]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/documentserver_community/coauthoring/CommandService.ashx"]},{"file":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/homepages/45/.../htdocs/Sites/cloud.xxx.de/apps/documentserver_community/lib/Controller/CoAuthoringController.php","Line":33},"CustomMessage":"--"},"userAgent":"curl/7.64.1","version":"18.0.0.10"}

**Comment by trendchiller** [comment]
I just installed another instance and tried to force the error.
When I set another FQDN in the field _Serviceadresse der Dokumentbearbeitung_ and save if afterwards it's broken and cannot be fixed...
so even if I delete the FQDN and click save (when it fills itself with the correct name) it won't work again.
So my question: What happens in this moment ? Is this value written somewhere in the database or any config file so it could be "resettable" ?

**Comment by trendchiller** [comment]
I now "solved" the problem by resetting the config values of "onlyoffice" by executing: _occ config:app:delete onlyoffice <all values>_  and the removing and newly installing onlyoffice.
It might be a workaround first, but now it works... - until some admin hits the save button ;-))

**Comment by DasRentier** [comment]
> I now "solved" the problem by resetting the config values of "onlyoffice" by executing: _occ config:app:delete onlyoffice _ and the removing and newly installing onlyoffice.
> It might be a workaround first, but now it works...
> 
> ...until some admin hits the save button ;-)

Hey trendchiller,
could you please explain it for a dummy again? I use ionos unlimited with no direct admin console on the webspace, but can use occ as ftp user without sudo.
Right after occ login to the nextcloud main directory, do I type:
"config:app:delete onlyoffice" ?
then remove and reinstall OO?
I don't touch the document server ?
Then I only type into the first line: "https://xxx.de/apps/documentserver_community/" ?
It was working great before the updates from a new 02.2020 to 03.2020 system. Is there a way to just go back?

**Comment by trendchiller** [comment]
Hi !
you have to be able to execute the occ command (php-script).
if you do not have command-line access you can use occ web i suppose.
You can find it here:  _https://apps.nextcloud.com/apps/occweb_

1. execute the command `occ config:app:delete onlyoffice`
2. remove the onlyoffice package
3. install the onlyoffice package

That's it.
Do **NOT** configure anything - that will break it again.
