### ISSUE TITLE
Update from 17.0.2 to 17.0.3 breaks integrity

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/server#19211]
### Steps to reproduce
1. Update 17.0.2 to 17.0.3
No errors during update. (Maybe update finished faster than expected?!)
Everything looks fine.

**Where is (my) problem? ;-)**

### Actual behaviour
Error Message in settings

> Einige Dateien haben die Integritätsprüfung nicht bestanden. Weiterführende Informationen befinden sich in unserer 

### Server configuration
**Operating system: Debian 10
**Database: sqlite
**PHP version: 7.3

**Updated from an older Nextcloud/ownCloud or fresh install: Update 17.0.2 to 17.0.3

**Where did you install Nextcloud from: Webupdater, following default process.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- user_external
	- INVALID_HASH
		- appinfo/info.xml
		- lib/smb.php

Raw output
==========
Array
(
    [user_external] => Array
        (
            [INVALID_HASH] => Array
                (
                    [appinfo/info.xml] => Array
                        (
                            [expected] => 06b250c3a2c2ae01c8a2c4b963d6449c99645dca36ee197c3aa513fb7ac3e90e42dc1408ee6957408d85f9f9a973b8983719e9c15125d42211d43f0853c7bf75
                            [current] => e5da848ca44b3b60abb1c99a3d26455d78464f94ea1f5f522b07d642096a771dcde9a1a5289e271805292659edc42925a86b5d6ad22ffa98b79ecec5bfed69ff
                        )

                    [lib/smb.php] => Array
                        (
                            [expected] => 283a99667fd865e54423d575953423bc6e15862b7683885cb5675aafdb3b2cbc1400a1318ec81cdbd90ce827c3f839aa6daf6a0f6e3ac6bd2742947498dd14f9
                            [current] => 1c12005d92f88017564fb4135a532810aab33ffab22eac67c19501a59d213518e417cceb83f5e9ea4b448ea81fff3149da37eefb0100a61bce3140ce67f8decc
                        )

                )

        )

)

```

BTW: The two files "info.xml" and "smb.php" are the same in version 17.0.2 and 17.0.3 (compared via diff)

**Comment by kesselb** [comment]
https://github.com/nextcloud/user_external/issues/119

**Comment by pm-pm** [comment]
Sorry, i looked and added this issue at the wrong position.
