### ISSUE TITLE
Nextcloud 18 - &nbsp; in french language

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#19213]
### Steps to reproduce
1. Set language to french
2. Try to copy/move a file into another directory
3. Get `Copier vers&nbsp;Documents` or `Déplacer vers&nbsp;Documents`

### Expected behaviour
Should be `Copier vers Documents` or `Déplacer vers Documents`

**Comment by acs-ferreira** [comment]
This has been fixed at https://www.transifex.com/nextcloud/nextcloud/translate/ and will be pushed in the next updates (you can/**should** contribute too 😃 )
