### ISSUE TITLE
problems with webdav external storage folder

### ISSUE THREAD

**Issue by luciomor** [nextcloud/server#19225]
623/5000
nextcloud correctly sends any file to webdav and shows everything correct on the screen. More when trying to create a folder, a message is displayed saying that it is not possible to create a folder. More when accessing the webdav from anywhere else the folder is there, it was created but it is not shown in the nextcloud. Then it loses the connection to the external webdav storage for a few minutes. This appears to be a bug. I have already tested other software connected to webdav and create the folders correctly. Ok permissions, everything ok. Repeating: nextcloud creates the folders more maybe because you can't find them says that it was not possible to create the folder.

**Comment by kesselb** [comment]
Thanks for reporting back a problem :1:

Please use https://help.nextcloud.com/ for questions and the issue template https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md for reporting a bug.
