### ISSUE TITLE
Upgraded 17.0.3 three dots cant see

### ISSUE THREAD

**Issue by cheesewizz** [nextcloud/server#19227]
Hi

here is my first found after i upgraded 17.0.3, three dots cant see i know is there it looks the color is grey.

![nc1703bug3dotcantsee](https://user-images.githubusercontent.com/14123082/73518756-23584200-443a-11ea-9470-6fca5ef0e4c2.png)

**Comment by cheesewizz** [comment]
also this
![nx1703bug2](https://user-images.githubusercontent.com/14123082/73520023-8697a380-443d-11ea-80c6-137c5f00994e.png)

**Comment by kesselb** [comment]
Clear the cache?
