### ISSUE TITLE
"Unknown error" when open OnlyOffice document in Nextcloud 18

### ISSUE THREAD

**Issue by b3nis** [nextcloud/server#19221]
Hello,

I have installed Nextcloud 18 (with ngix, mariadb, letsencrypt) and everything works flawless with https/ssl and file management - but today I enabled OnlyOffice document server (the one built in) and when I open the OnlyOffice connector setting the address to my server was pre-filled, but only "http" and it did not connect. I changed to https and the rest of the settings popped up. I manage to create documents and when I click on them they open in OnlyOffice but then I get thrown this error "Unknown error" in OnlyOffice. See [this screen record](https://youtu.be/RL79ToCvff0) (sorry for the bad cropping).

I have no weird apps and this is a fresh install - so I would guess it's some kind of bug or bad setup (I follow [this guide](https://blog.ssdnodes.com/blog/installing-nextcloud-docker/) to set it up).

From the log:

> {"reqId":"5j1BJ53FJJkc3mXqxtdG","level":3,"time":"2020-01-24T00:14:24+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"svQLLlWzFh1av3Fxzn96","level":3,"time":"2020-01-24T00:14:25+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"sTld2GdbjSbhI7qGjdAU","level":3,"time":"2020-01-24T00:14:25+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"UdNmJeSVjc2R5mvzTr3B","level":3,"time":"2020-01-24T00:14:25+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"uwACv2js2Iw2cVS2dElS","level":3,"time":"2020-01-24T00:14:26+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"7UAu5XGyho8LuMuOIAjN","level":3,"time":"2020-01-24T00:14:30+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"0Qk23swFbZBLqhnAtbV7","level":3,"time":"2020-01-24T00:14:30+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}
{"reqId":"JXIxSC2nqlup5kHEWlKG","level":3,"time":"2020-01-24T00:14:30+00:00","remoteAddr":"172.19.0.4","user":"benjamin","app":"onlyoffice","method":"PUT","url":"/apps/onlyoffice/ajax/settings/address","message":"CommandRequest on check error: Client error: `POST http://my.server.com/apps/documentserver_community/coauthoring/CommandService.ashx` resulted in a `405 Method Not Allowed` response","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:71.0) Gecko/20100101 Firefox/71.0","version":"18.0.0.10"}

_(my.server.com is, of course, not the real domain)_

Big thanks in advance!

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
