### ISSUE TITLE
Extended version control feature request

### ISSUE THREAD

**Issue by iron-owl** [nextcloud/server#19237]
Hello!

Me and my collegues are planning to deploy self-hosted Nextcloud as our Department's storage for internal operational documentation, troubleshooting guides, configuration guides, etc.

It would be great if Nextcloud gets extended version control feafure. I mean when somebody edits file, he/she writes a comment (description of changes), and any of these actions happens:
A. Old file copies to backup folder, and renames to file+date (YYYYMMDD)+file version. For example: user changes file "file.docx", typed comment, and old file is saved as "file_20200131_1.docx".
B. When user writes comment, he/she sets version of file in "x.y" format, where "x" - is number of major change, and "y" - number of minor change. For example, 0.2, 1.10, etc. And backup file renames to "file_1.10".
C. In Versions menu date and time of changes is displayed, and user, who changes file (or it would be good if there could be a link to comment assosiated to change).

Best Regards,
Kirill

**Comment by szaimen** [comment]
There is already a versions app available that saves older file versions.
