### ISSUE TITLE
Disable Apps (all the time)

### ISSUE THREAD

**Issue by bbbastien** [nextcloud/server#19232]
### Steps to reproduce
1. Activate my apps
2. Wait a little
3. Found my custom apps on Disable Apps

### Expected behaviour
Should never be disabled by default.

### Actual behaviour
After activated my custom apps, it disabled by itself.

### Server configuration

**Operating system:**
Windows 10

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
18

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Docker nextcloud

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Comment by kesselb** [comment]
Logs? Usually apps are disabled if something went wrong or incompatible.

**Comment by bbbastien** [comment]
There is no log. On database the App is enabled but not in my panel. My apps is still working.
