### ISSUE TITLE
Correct size labeling in interface.

### ISSUE THREAD

**Issue by Weyla** [nextcloud/server#19231]
Hi!
The data size is displayed in a binary system, but its labeled as the decimal. I recommend changing it to MiB, GiB etc...  The best would be to be able to change between binary in decimal in the user settings. I had problems in a Linux machine checking the file sizes if everything is synced after an error and the commonly used incorrect labeling just makes it confusing for people who don't know the the difference.

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/13143

**Comment by kesselb** [comment]
https://github.com/owncloud/core/issues/13386 is back ;)

cc @nextcloud/server-triage @jancborchardt anything changed since 2016? If not I would close this one as won't fix.

**Comment by nickvergessen** [comment]
Where is this? In the file list? The sidebar? Or all over the place?

**Comment by Weyla** [comment]
![image](https://user-images.githubusercontent.com/17383858/73581318-0eef6600-4489-11ea-911a-f4e3a8d6312d.png)
I think its everywhere where the file sizes are displayed.  I wouldnt call it a huge problem, but it gave me some trouble when i had an error and checked the file sizes to make sure everything is synced.
I checked in a linux GUI and it displayed in metric with the correct GB label, but when i checked in the terminal it said the binary version with the wrong GB label. I understand people will be confused with GiB, but i think everybody was taught about this, but actually has no idea whats happening and would realise what GiB is.
At least an option on the server or the client size to change it would be nice, but i guess its not gonna happen since everybody else uses the wrong system.
