### ISSUE TITLE
Server info App dont work after upgraded to 10.0.1

### ISSUE THREAD

**Issue by JarbyDev** [nextcloud/server#1924]
Server info was working perfectly on 10.0.0, but after i upgraded to 10.0.1, doesnt work anymore see screenshoots

![serverinfo](https://cloud.githubusercontent.com/assets/11229573/19724946/e90aa8e4-9b50-11e6-98a0-7e1e1ce06c4e.PNG)

![serverinfo1](https://cloud.githubusercontent.com/assets/11229573/19724954/ee0f8e4a-9b50-11e6-8219-1a9709c6c4f0.PNG)

**Comment by nickvergessen** [comment]
Please provide the full information that is asked for in the issue template.
Especially with the network log of the browser

**Comment by nickvergessen** [comment]
Feel free to reopen, once you provided the required information
