### ISSUE TITLE
Bug: All existing shares removed after removing a remote user (federated) from sharing list

### ISSUE THREAD

**Issue by haghighi-ahmad** [nextcloud/server#19248]
### Steps to reproduce
1. Share a file with a remote user (e.g. `john@foo.bar`)   
2. Unshare file (remove `John@foo.bar` from sharing list)  
3. Refresh your NC ... all your existing shares is gone!(local/internal/remote shares on any file and directory)  

### Description
I have a local NextCloud instance and a public(remote) NextCloud instance (accessible from the internet), Federated share works fine between two public instance (e.g. my public instance and another public instance), I was eager to test Federation feature between my internal instance and my public one.   
I shared a file with my user on public instance, I get a notification on public instance (as expected) related to that share and after accepting the _file sharing request_ nothing happened (it is reasonable, because the internal server is not accessible from public one).
So I decided to remove the remote user (`john@foo.bar`) from sharing list on internal NextCloud, after clicking on "unshare" button, remote user successfully deleted from sharing list (without any error) but ALL MY SHARES ON INTERNAL INSTANCE IS GONE! Even local ones. After removing remote user form I don't have any share.   

This problem is reproducible.

### Server configuration

**Operating system:**
Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64
**Web server:**
Apache/2.4.38 (Debian) (apache2handler)
**Database:**
mysql 10.4.12
**PHP version:**
7.3.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache
**Nextcloud version:** (see Nextcloud admin page)
18.0.0 - 18.0.0.10
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
Using Docker, this is my docker-compose file: https://github.com/haghighi-ahmad/nextcloud-collabora-office    
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - analytics: 2.0.0
 - announcementcenter: 3.7.0
 - audioplayer: 2.9.0
 - audioplayer_editor: 0.2.0
 - bookmarks: 2.3.4
 - calendar: 2.0.1
 - circles: 0.18.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.1.8
 - dav: 1.14.0
 - deck: 0.8.0
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_accesscontrol: 1.8.1
 - files_automatedtagging: 1.8.0
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.0
 - groupfolders: 6.0.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.2
 - maps: 0.1.4
 - music: 0.12.1
 - nextcloud_announcements: 1.7.0
 - notes: 3.1.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - richdocuments: 3.5.1
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - sociallogin: 2.4.3
 - spreed: 8.0.1
 - systemtags: 1.8.0
 - tasks: 0.11.3
 - terms_of_service: 1.4.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflow_pdf_converter: 1.3.1
 - workflowengine: 2.0.0
Disabled:
 - audioplayer_sonos
 - breezedark
 - bruteforcesettings
 - checksum
 - encryption
 - files_retention
 - impersonate
 - support
 - survey_client

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.0.10",
    "overwrite.cli.url": "https:***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "versions_retention_obligation": "disabled",
    "loglevel": 2,
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "app_install_overwrite": [
        "contacts",
        "unsplash"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local/smb/sftp/...
**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Nope

### Client configuration
**Browser:**
Mozilla/5.0 (X11; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
**Operating system:**
Fedora 31

**Comment by kesselb** [comment]
cc @skjnldsv :fearful:

**Comment by rullzer** [comment]
@haghighi-ahmad thanks for reporting this.
We'll look into it.

**Comment by ChristophWurst** [comment]
Related: https://github.com/nextcloud/server/pull/19178

**Comment by rullzer** [comment]
Got it. PR incomming

**Comment by rullzer** [comment]
@haghighi-ahmad see #19276 

Thanks for your detailed report. This made it far easier to track down and to see what was going on.

**Comment by haghighi-ahmad** [comment]
^_^  
Thank you @rullzer  for your prompt action.

**Comment by rakekniven** [comment]
Hello,

is this fix part of NC v18.0.1?
Could not find it in changelog.

**Comment by ChristophWurst** [comment]
It was backported as https://github.com/nextcloud/server/pull/19278. The changelog might be out of sync. @rullzer?

**Comment by rakekniven** [comment]
No, this one is in.
