### ISSUE TITLE
Federation for groups share misbehavior

### ISSUE THREAD

**Issue by etibamecus** [nextcloud/server#19245]
### Steps to reproduce
1. Admin of instance-A enable federation for groups on instance-A
2. User1 of instance-A share a folder with group2 of instance-B
3. User2 of group2 of instance-B accept the share

4. Admin of instance-A disable federation for groups on instance-A
5. User2 of group2 of instance-B can still see the shared folder.
6. User1 of instance-A cannot unshare the folder.

### Expected behaviour

Shared folder on instance-B should be disabled OR User1 of instance-A should be able to unshare.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)

instance-A : nextcloud 17.0.2
instance-B : nextcloud 18.0.0

**Comment by kesselb** [comment]
Yes. That should be possible. Do you get any response if you try to unshare or is the option missing?

cc @nextcloud/server-triage @skjnldsv

**Comment by etibamecus** [comment]
when you open the share tab of the folder, the option is missing.

I tried with group federation but not with user federation, so i don't know if the problem is the same.

**Comment by skjnldsv** [comment]
Could you share some screenshots please?

What do you mean by "enable federation for groups" ?


> when you open the share tab of the folder, the option is missing.

You mean the share is not visible in the panel so you cannot unshare it, right?

**Comment by etibamecus** [comment]
yes i mean the share is not visible in the panel so i cannot unshare it

**Comment by skjnldsv** [comment]
If you disable federated sharing, they will indeed not be shown.
cc @rullzer && @nickvergessen && @daita for sharing and recent changes

**Comment by etibamecus** [comment]
yes i understand that, but then the share should disapear on instance-B

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
