### ISSUE TITLE
Duplicate Notifications

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#19244]
After installing Nextcloud version 18.0.0 I received duplicate notifications. Was it accidental?

![obraz](https://user-images.githubusercontent.com/47037905/73530486-e0d23d80-4418-11ea-862c-8925ec6dd865.png)

![obraz](https://user-images.githubusercontent.com/47037905/73530510-eb8cd280-4418-11ea-9211-679f141659ad.png)

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Comment by Lostonaboat** [comment]
I have same issue after the 16.08 auto snap update. And now with the new snap update 17... I still have this issue.. adding to this though when creating new contacts i will add "notes" it now bring up 2 note boxes.. or if i add an additional phone box it now adds 2 boxes so i end up deleting one.. i also have to constantly refresh the screen when creating new contacts other wise not all info gets saved

**Comment by manuelkamp** [comment]
what was the solution, i do have this wit v23 now

**Comment by Valdnet** [comment]
> what was the solution,

There was no solution. In the next version the error issue did not appear.
