### ISSUE TITLE
don't overwrite .htaccess

### ISSUE THREAD

**Issue by ulph0** [nextcloud/server#19254]
hi. .htaccess is overwritten with every upgrade. i will reopen that issue here as a feature request. there are serveral duplicates: #4769, #6184 ans maybe more ... i makes no sense at all that that issues were closed. this is really annoying and as it seems, not only for me! since the shared hosting some of us are using (i use one at host europe) has no apache config access we have to do everything with the .htaccess file. forcing https, enabling HTTP strict transport security, ... and with every upgrade i have to do a backup of the htacces file, change permissions, put my changes back in, load it up again .. everytime with the rsisk to break my config ... PLEASE change that! at least nothing below the line "#### DO NOT CHANGE ANYTHING ABOVE THIS LINE ####" should be changed - otherwise why exactly do you have that line in there?

**Comment by kesselb** [comment]
I'm sorry there are no plans to support ANY shared hosting out there. Making changes to `.htaccess` is not supported. A common way to workaround this limitation is to run Nextcloud in a sub directory as `.htaccess` files are inherited from the document root. 

Closing as per https://github.com/nextcloud/server/issues/4769#issuecomment-322219262
