### ISSUE TITLE
Getting error while trying to login to Web GUI

### ISSUE THREAD

**Issue by fidelito** [nextcloud/server#19262]
Hi,

nginx version: nginx/1.17.8
php version is php7.3

I had nextcloud version 17.0.3 and it was failing so I upgraded to nextcloud 18.0.0 and I still have the same issue. I cannot login with my current user or a newly user created. 
On the web gui I get this
"The server was unable to complete your request.
If this happens again, please send the technical details below to the server administrator.
More details can be found in the server log."

In the nextcloud.log file I get this 

{"reqId":"RWM4ScuUAzeuCpQy4TN2","level":3,"time":"2020-02-02T16:34:31+00:00","remoteAddr":"192.168.10.132","user":"--","app":"index","method":"POST","url":"/login","message":{"Exception":"Exception","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 170","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":125,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"_route":"core.login.tryLogin"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":299,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"_route":"core.login.tryLogin"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/var/www/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/core/Controller/LoginController.php","Line":280},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}
{"reqId":"RWM4ScuUAzeuCpQy4TN2","level":3,"time":"2020-02-02T16:34:31+00:00","remoteAddr":"192.168.10.132","user":"--","app":"PHP","method":"POST","url":"/login","message":"Unknown: POST Content-Length of 198 bytes exceeds the limit of 10 bytes at Unknown#0","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0","version":"18.0.0.10"}

Please let me know if you need any more information that I may have missed.

**Comment by kesselb** [comment]
> more information that I may have missed.

Actually the issue template. I see that more often the last days (that people do not use the template and create a issue without labels). How do you came here to GitHub (the create issue form)? I suspect there is a broken link somewhere around. 

> Unknown: POST Content-Length of 198 bytes exceeds the limit of 10 bytes at Unknown#0

You (or someone else) configured the post_max_size for PHP to 10 bytes. Pick a higher value. https://stackoverflow.com/questions/6279897/post-content-length-exceeds-the-limit

**Comment by fidelito** [comment]
Hi,

I created the issue and it didn't have a template for me to use. So I created it based on similar post that I done to research this issue.

I check /etc/php/7.3/cli/php.ini  and /etc/php/7.3/fpm/php.ini

both values for the post_max_size = 5GB

Looks like I needed to put the value to 5G and now I don't get the error but it won't log me in or it seems the redirect its not working properly. I have no logs on the nextcloud.log

Nginx logs look good too

[02/Feb/2020:20:43:28 -0500] "GET /login?redirect_url=/apps/files/ HTTP/1.1" 200 3587

I will spend more time tomorrow troubleshooting it more. Please let me know if you have any hint or guide on how I can find the answer quicker.

Thanks

**Comment by fidelito** [comment]
@kesselb any suggestions? I can't seem to figure out why the page redirects me /login?redirect_url=/apps/files/ in the browser url but the page goes back to login screen. I know I put the correct password. I also know that my phone nextcloud app is working as I can upload files to it. 

Its just the web console won't work. i tried it on firefox, chrome and IE.

**Comment by fidelito** [comment]
remove nextcloud directory, nginx, php, redis, mariadb and started from scratch. Now it works fine.
