### ISSUE TITLE
Can't login SAML

### ISSUE THREAD

**Issue by jsargent7089** [nextcloud/server#19264]
Account not provisioned.
Your account is not provisioned, access to this service is thus not possible.

Fatal | user_saml | IDP parameter for the UID (Dozedrive) not found. Possible parameters are: ["http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/nameidentifier","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/emailaddress","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/name","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/upn","http:\/\/schemas.auth0.com\/identities\/default\/connection","http:\/\/schemas.auth0.com\/identities\/default\/provider","http:\/\/schemas.auth0.com\/identities\/default\/isSocial","http:\/\/schemas.auth0.com\/picture","http:\/\/schemas.auth0.com\/nickname","http:\/\/schemas.auth0.com\/email_verified","http:\/\/schemas.auth0.com\/clientID","http:\/\/schemas.auth0.com\/updated_at","http:\/\/schemas.auth0.com\/created_at"]
-- | -- | --

Fatal | user_saml | IDP parameter for the UID (Email) not found. Possible parameters are: ["http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/nameidentifier","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/emailaddress","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/name","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/upn","http:\/\/schemas.auth0.com\/identities\/default\/connection","http:\/\/schemas.auth0.com\/identities\/default\/provider","http:\/\/schemas.auth0.com\/identities\/default\/isSocial","http:\/\/schemas.auth0.com\/picture","http:\/\/schemas.auth0.com\/nickname","http:\/\/schemas.auth0.com\/email_verified","http:\/\/schemas.auth0.com\/clientID","http:\/\/schemas.auth0.com\/updated_at","http:\/\/schemas.auth0.com\/created_at"] |   | 2020-02-02T21:39:18-0800
-- | -- | -- | -- | --
Fatal | user_saml | IDP parameter for the UID (Email) not found. Possible parameters are: ["http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/nameidentifier","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/emailaddress","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/name","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/upn","http:\/\/schemas.auth0.com\/identities\/default\/connection","http:\/\/schemas.auth0.com\/identities\/default\/provider","http:\/\/schemas.auth0.com\/identities\/default\/isSocial","http:\/\/schemas.auth0.com\/picture","http:\/\/schemas.auth0.com\/nickname","http:\/\/schemas.auth0.com\/email_verified","http:\/\/schemas.auth0.com\/clientID","http:\/\/schemas.auth0.com\/updated_at","http:\/\/schemas.auth0.com\/created_at"] |   | 2020-02-02T21:31:35-0800
Fatal | user_saml | IDP parameter for the UID (Auth0) not found. Possible parameters are: ["http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/nameidentifier","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/emailaddress","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/name","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/upn","http:\/\/schemas.auth0.com\/identities\/default\/connection","http:\/\/schemas.auth0.com\/identities\/default\/provider","http:\/\/schemas.auth0.com\/identities\/default\/isSocial","http:\/\/schemas.auth0.com\/picture","http:\/\/schemas.auth0.com\/nickname","http:\/\/schemas.auth0.com\/email_verified","http:\/\/schemas.auth0.com\/clientID","http:\/\/schemas.auth0.com\/updated_at","http:\/\/schemas.auth0.com\/created_at"] |   | 2020-02-02T21:31:06-0800
Fatal | user_saml | IDP parameter for the UID (Remote Accounts) not found. Possible parameters are: ["http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/nameidentifier","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/emailaddress","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/name","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/upn","http:\/\/schemas.auth0.com\/identities\/default\/connection","http:\/\/schemas.auth0.com\/identities\/default\/provider","http:\/\/schemas.auth0.com\/identities\/default\/isSocial","http:\/\/schemas.auth0.com\/picture","http:\/\/schemas.auth0.com\/nickname","http:\/\/schemas.auth0.com\/email_verified","http:\/\/schemas.auth0.com\/clientID","http:\/\/schemas.auth0.com\/updated_at","http:\/\/schemas.auth0.com\/created_at"] |   | 2020-02-02T21:22:34-0800
Fatal | user_saml | IDP parameter for the UID (Remote Accounts) not found. Possible parameters are: ["http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/nameidentifier","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/emailaddress","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/name","http:\/\/schemas.xmlsoap.org\/ws\/2005\/05\/identity\/claims\/upn","http:\/\/schemas.auth0.com\/identities\/default\/connection","http:\/\/schemas.auth0.com\/identities\/default\/provider","http:\/\/schemas.auth0.com\/identities\/default\/isSocial","http:\/\/schemas.auth0.com\/picture","http:\/\/schemas.auth0.com\/nickname","http:\/\/schemas.auth0.com\/email_verified","http:\/\/schemas.auth0.com\/clientID","http:\/\/schemas.auth0.com\/updated_at","http:\/\/schemas.auth0.com\/created_at"]

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
