### ISSUE TITLE
No translated word "Reshare"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#19261]
### Steps to reproduce

1. Go to Nextcloud settings.
2. Select "Sharing" for the administrator.

### Expected behaviour
The word "Reshare" translated.

### Actual behaviour
Untranslated word "Reshare".

![obraz](https://user-images.githubusercontent.com/47037905/73608315-cedfce80-45c1-11ea-8e55-544f05891f65.png)

The problem was similarly addressed in this issue #14793.

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/apps/settings/lib/Settings/Admin/Sharing.php#L118-L122

`Reshare` as string seems to be passed to translate function. 
Probably only the translation is missing because  `Share` was renamed  to `Reshare` recently?

**Comment by kesselb** [comment]
Translation for `Reshare` is fetched from `lib` and not `settings`. Does that help to find the string? :confused:

**Comment by Valdnet** [comment]
@kesselb Gets `lib` from the `server/lib/l10n/` root directory that does not have this translation. Why is this happening? :astonished:

**Comment by kesselb** [comment]
> Why is this happening?

I don't know. Are you able to find the strings in transifex?

**Comment by Valdnet** [comment]
@kesselb  In Transefix there are translations for:

- `settings-1` 

Create -> `/app/apps/settings/lib/Settings/Admin/Sharing.php:105`
Change -> `/app/apps/settings/lib/Settings/Admin/Sharing.php:110`
Delete -> `/app/apps/settings/lib/Settings/Admin/Sharing.php:115`
Reshare ->`/app/apps/settings/lib/Settings/Admin/Sharing.php:120` -> Does not appear in `.js` and `.json` files for `settings`.

- `lib`
Create -> `/app/lib/private/Settings/Admin/Sharing.php:98`
Change -> `/app/lib/private/Settings/Admin/Sharing.php:103`
Delete -> `/app/lib/private/Settings/Admin/Sharing.php:108`
Reshare -> not available for translation -> Does not appear in `.js` and `.json` files  -> Does not appear in `.js` and `.json` files for `lib`.

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/73612643-c30a0180-45ed-11ea-92ee-b7029717cd61.png)

I can confirm that. String seems to be missing. Probably not bad to move all those strings to settings anyway. 

cc @rullzer @juliushaertl

**Comment by Valdnet** [comment]
cc @rullzer @juliushaertl Is the translation source set correctly here:
https://github.com/nextcloud/server/blob/1b46621cd31dabb48084c8e23f741de77e7007b4/apps/settings/lib/Settings/Admin/Sharing.php#L57

**Comment by rullzer** [comment]
I'll take care
