### ISSUE TITLE
German translation of the months in the tab title partially does not exist

### ISSUE THREAD

**Issue by ddrchs** [nextcloud/server#19282]
The german translation of the months in the tab title partially does not exist after update to nextcloud 17.0.3

**Comment by j-ed** [comment]
Can you please use the issue template and provide the requested information about your installation, the used web browser, how the problem can be reproduced, a screenshot of the problem etc., etc.

**Comment by rakekniven** [comment]
@ddrchs Kannst Du noch Details liefern?
