### ISSUE TITLE
Avatar doesn't rotate JPEGs based on EXIF data

### ISSUE THREAD

**Issue by josh4trunks** [nextcloud/server#1928]
### Steps to reproduce
1. Settings > Personal > Profile Picture
2. Upload a JPEG which has EXIF rotation
3. Or.. Choose a JPEG which has EXIF rotation
    * Example JPEG available here. This image should show in portrait.
https://cloud.githubusercontent.com/assets/1018807/14191717/4a47f866-f74e-11e5-9030-e1add9fc4db1.jpg

### Expected behaviour
Image should be automatically rotated based on EXIF data

### Actual behaviour
JPEG's EXIF data is ignored. Images in crop area, and after cropping, are not rotated properly

### Notes
This issue also exists in ownCloud https://github.com/owncloud/core/issues/23697
I presented a working fix, but it is not ideal because it uses views and not the Node API https://github.com/owncloud/core/issues/23697#issuecomment-204000138

**Comment by josh4trunks** [comment]
@rullzer if we did get an agreeable solution to this maybe we can backport to ownCloud since it is relevant to both.

**Comment by LukasReschke** [comment]
> maybe we can backport to ownCloud

That's not possible since ownCloud uses an incompatible, not OSI approved, proprietary, license in addition to the AGPL.

But yes. We should look into that here :)

**Comment by josh4trunks** [comment]
Ahh OK, good to know. I just didn't know the extent the projects were sharing code and thought it would be good to minimize unnecessary differences.

**Comment by LukasReschke** [comment]
> Ahh OK, good to know. I just didn't know the extent the projects were sharing code and thought it would be good to minimize unnecessary differences.

Technically, we can take any code from the ownCloud project and do cherry-pick all noteworthy commits but this is only possible in one direction at the moment. :)
