### ISSUE TITLE
l10n: Add plural form to message with placeholder (counter for apps)

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#19304]
https://github.com/nextcloud/server/blob/f11e4c9ec44f4eeb25d921f7680e23024749358a/apps/settings/src/components/AppList.vue#L28

Counter can be 1 and so we need plural form.

Want to do it myself, but cannot find docs after a quick search.

Looked for an example:

https://github.com/nextcloud/polls/commit/8b91e6b9c6506d0df2dd00360b25f7417a1f2484

But here we have more arguments.

Please add or enlight me.

Thank you

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/f11e4c9ec44f4eeb25d921f7680e23024749358a/core/src/globals.js#L153-L162

https://github.com/nextcloud/server/blob/ec01e0a790448fff38364f629a4de4edb5d465bf/core/src/OC/l10n.js#L129-L140

`n` is probably what you are looking for.

**Comment by szaimen** [comment]
As this looks like it was fixed with #19313, I am going to close this issue.
