### ISSUE TITLE
nextcloud 16.0.3 change update channel issue

### ISSUE THREAD

**Issue by dipol0** [nextcloud/server#19301]
### Steps to reproduce
1. I have Nextcloud v 16.03 server. set in Produclion channel to update
2. Enter in Settings i change channel to Stable and after page update NC show me when new version availabe (upgrade to v 16.0.7) but a dont make update pcodedure and revert update channel back to Production channel and update page. Now NC show me when i have v 16.0.7 in web-interfce and in console with ./occ   Now i dont know then i version have ??? 16.0.3 or 16.0.7  ???Online scanner https://scan.nextcloud.com/ show me i have 16.0.3

### Expected behaviour
- Tell us what should happen

### Actual behaviour
- Tell us what happens

### Environment data
Android version:

Device model: 

Stock or customized system:

Nextcloud app version:

Nextcloud server version:

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```
Insert your Nextcloud log here
```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by kesselb** [comment]
The results of scan.nextcloud.com are cached. Press the rescan button :)
