### ISSUE TITLE
Remote shares use local avatar

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19319]
### Steps to reproduce
1. Create a local user "test1" and upload an avatar
2. As admin start a remote share with "test1@try.nextcloud.com"
3. Be confused because the avatar of "test1" from your dev instance is shown :confused: 

### Expected behaviour
Placeholder avatar is shown

### Actual behaviour
Local avatar is shown

I think this is a regression from the Vue sidebar? So cc @skjnldsv

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by skjnldsv** [comment]
Fixed by two PRs:
- https://github.com/nextcloud/server/pull/48887
- https://github.com/nextcloud/server/pull/47441
