### ISSUE TITLE
Select2 select box hard to discover

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#1932]
Since the redesign of the select2 inputs ( #1780 and #1789  ), the collaborative tags dropdown is really awkward to discover:
![select2-design-issue](https://cloud.githubusercontent.com/assets/213943/19760283/4bd11734-9c31-11e6-839c-76058d6a6e0a.png)

@jancborchardt @nextcloud/designers

**Comment by skjnldsv** [comment]
Result : 
![2016-11-08_10-34-54](https://cloud.githubusercontent.com/assets/14975046/20093919/3690b07e-a59f-11e6-93b2-26886810bb21.png)

**Comment by jancborchardt** [comment]
@skjnldsv only one detail: The »select tag« placeholder text should be correctly left-aligned. Currently it floats in the middle.

**Comment by skjnldsv** [comment]
It was like that, I figured it should stay this way. Will fix! :)

**Comment by jancborchardt** [comment]
@skjnldsv can you separate it from the SCSS pull request? Because we are one week from feature freeze, it is very unlikely we will merge SCSS for Nextcloud 11. But this one is a fix we need.

(That’s why it’s always important to separate ;)

**Comment by skjnldsv** [comment]
It is now. See the base scss transition #2050
