### ISSUE TITLE
Old jquery avatars are not using 2 chars on placeholder

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19335]
The changes from https://github.com/nextcloud/server/pull/18745 need to be ported to core/src/jquery/avatar.js as well.

@matchish  Do you want to take care of this?

**Comment by matchish** [comment]
@nickvergessen Sure, I'll do it

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by szaimen** [comment]
Seems like this was done in https://github.com/nextcloud/server/pull/20634
