### ISSUE TITLE
S3 caching options?

### ISSUE THREAD

**Issue by ylluminate** [nextcloud/server#19336]
Some S3 services are a little slower than others and I'd like to know if there is a caching option for S3 that would speed up access for certain files that fit within a threshold on the NextCloud Server.

Just as an example, let's say I have a 20 GB server to host NextCloud and a Wasabi S3 bucket we're using. Sometimes Wasabi seems to drag a bit. Can we set up NextCloud to use 10 GB or so for caching buckets within a certain time period and/or size threshold to speed up access for these frequently used or recent files that fit within the cache?

**Comment by acs-ferreira** [comment]
https://github.com/nextcloud/server/issues/16623#issuecomment-578435890

**Comment by acs-ferreira** [comment]
Don't hesitate to ask the community for optimization options at https://help.nextcloud.com
