### ISSUE TITLE
Encoding typo: "Devices and sessions"

### ISSUE THREAD

**Issue by Nils-Magnus** [nextcloud/server#19337]
In "Settings | Security" the section "Devices and session" reads "Devices & amp ; sessions".

### Steps to reproduce
1. Log into Nextcloud Hub 
2. Click Settings
3. Click Security
4. Look at section

### Expected behaviour
Display "Devices & sessions"

### Actual behaviour
Display "Devices & amp ; sessions" (without spaces around "amp" for GH's sake)

### Server configuration

**Operating system:**
Linux, Debian

**Web server:**
Apache 2
**Database:**
MariaDB

**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
18 / Hub
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install five minutes ago
**Where did you install Nextcloud from:**
website
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
none after default
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
N/A
```
</details>

**Comment by schiessle** [comment]
I can verify it... Just wanted to report the same:

![image](https://user-images.githubusercontent.com/1589737/74156636-092b1a80-4c17-11ea-8a60-eddc0758be7c.png)

**Comment by moviuro** [comment]
Same here, NC 18.0.0, FreeBSD 12.1, PHP 7.3.14

**Comment by sndrr** [comment]
Same on NC 19.0.0 alpha.

This is an issue with Vue. It will translate unsafe characters into html-entities. To override this behaviour, we have to use the [`v-html`-directive](https://vuejs.org/v2/api/#v-html).

A quick patch would be something along the lines of:
```
diff --git a/apps/settings/src/components/AuthTokenSection.vue b/apps/settings/src/components/AuthTokenSection.vue
index e6643903cd..e89a7988e2 100644
--- a/apps/settings/src/components/AuthTokenSection.vue
+++ b/apps/settings/src/components/AuthTokenSection.vue
@@ -21,7 +21,7 @@

 <template>
        <div id="security" class="section">
-               <h2>{{ t('settings', 'Devices & sessions') }}</h2>
+               <h2 v-html="$t('settings', 'Devices & sessions')"></h2>
                <p class="settings-hint hidden-when-empty">
                        {{ t('settings', 'Web, desktop and mobile clients currently logged in to your account.') }}
                </p>
```

Any thoughts?

**Comment by conrad784** [comment]
Same issue on freshly upgraded Nextcloud 17 to 18.0.1 behind Apache2.

**Comment by szaimen** [comment]
@sndrr could you provide a patch for this?

**Comment by strugee** [comment]
Duplicate of #18662, I believe?

**Comment by mrizvic** [comment]
I use Nextcloud 19.0.0 beta 1
and still see
Devices &amp; sessions
Web, desktop and mobile clients currently logged in to your account.

**Comment by strugee** [comment]
@mrizvic do you mean `Devices &amp; sessions`?

**Comment by mrizvic** [comment]
yes, sorry :)
