### ISSUE TITLE
Deprecation of php7.2

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#19341]
Similar to https://github.com/nextcloud/server/issues/15079, php7.2 will only receive security fixes now and that will also end by the end of this year. We should plan ahead to smoothen the deprecation path. 19 will definitely support 7.2, though.

Ref https://github.com/nextcloud/server/issues/15079

cc @blizzz @nickvergessen @rullzer

**Comment by nickvergessen** [comment]
for 19 yes, 20 I'd say we should check where we are when it happens

**Comment by ChristophWurst** [comment]
Guess we should re-evaluate for 21. 7.2 will reach its EOL before the release of 21, ref https://www.php.net/supported-versions.php and https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by rullzer** [comment]
Yes 7.2 should die for 21
And we should have a look at support for 8

**Comment by ChristophWurst** [comment]
Done with https://github.com/nextcloud/server/pull/22767
