### ISSUE TITLE
Phase out untyped service injection in DI container

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#19345]
For historical reasons we still have aliases for parameters without type hints, like `Logger` for the ``\OCP\ILogger``. As we now type hint everything anyway, I think these aliases can be phased out slowly.

https://github.com/nextcloud/server/blob/2be1a6a04e024c93cda059fafa2b1fa405c86f44/lib/private/Server.php#L680

@blizzz @icewind1991 @nickvergessen @rullzer does that make sense? What could be a possible deprecation path? Document deprecation and remove later?

**Comment by rullzer** [comment]
Let me see if we can add debug logic for this.
So that if we use such an alias we can log it

**Comment by ChristophWurst** [comment]
You can register it as service instead of alias. And use the callback. But that will only be invoked once, I think. Unless you set it to shared=false :thinking:

**Comment by rullzer** [comment]
Actually we already register it as a wrapper service.
We can just add another one for this. That wraps 2 times. And then on first invocation logs (with a stack trace).?

**Comment by ChristophWurst** [comment]
At https://github.com/nextcloud/server/blob/2be1a6a04e024c93cda059fafa2b1fa405c86f44/lib/private/Server.php#L680 it's just an alias.

I'd say we start with a debug log, or maybe warning. And then gradually increase the level with each release?

> And then on first invocation

If you make the service non-shared then you can have a log for every time the service was requested.

**Comment by nickvergessen** [comment]
> If you make the service non-shared then you can have a log for every time the service was requested.

And you might break services as they dont have the same shared state anymore. Please don't do that.

**Comment by ChristophWurst** [comment]
No we don't. You register a non-shared service for the deprecated alias. But it will always return the same instance of the actual service. Like querying `Logger` will always give you the same `ILogger` instance.

**Comment by rullzer** [comment]
> > If you make the service non-shared then you can have a log for every time the service was requested.
> 
> And you might break services as they dont have the same shared state anymore. Please don't do that.

Seems that all aliases are currently not shared already. But the original service is.
