### ISSUE TITLE
Allow to open files in trashbin in the same way as "normal" files

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#19353]
## Expected behavior
If you want to restore a file from the trashbin, it should be possible to click and open it as it is possible with "normal" files, to be able to better identify which file should be chosen.

## Current behavior
If you want to restore a file from the trashbin it isn't possible to open it as a "normal" file. The only way to identify a file is currently to rely on the displayed preview or to restore the files in question first to be able to identify the right one afterwards and to delete supernumerary ones again.

![grafik](https://user-images.githubusercontent.com/2572764/74036015-c02b5a00-49bb-11ea-85a0-3a1bdbf1cc7a.png)

## Steps to reproduce
1. Open the Files app.
2. Open Deleted files (trashbin).
3. Try to identify a specific file only based on the preview.

#### Server Configuration
OS: Linux 4.9.207
Web server: Apache2 2.4.41
Database: MariaDB 10.2.24
PHP version: 7.3.13
Nextcloud version: 18.0.0

#### Client Configuration
Browser: Mozilla Firefox 72.0.2
Operating system: Windows 10

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/1071
