### ISSUE TITLE
Cannot open app and users page

### ISSUE THREAD

**Issue by Maxence1502** [nextcloud/server#19350]
Hello ! 
I upgraded from lastest nextcloud 17 to lastest nextcloud 18 but I cannot open the apps page (/index.php/settings/apps) it is rewrited to /index.php, same for users page. But the user page work !

Do you have any idea ?

**Comment by bpcurse** [comment]
Try to disable as much apps as possible through occ and see if it is caused by some strange app interaction. Although I don't believe it will help in this case it is always worth a try.

**Comment by kesselb** [comment]
Rainloop and ocDownloader are know to cause this. Probably every app using the old way to register a settings section.
