### ISSUE TITLE
Cant update file in webinterface, when not allowed to create

### ISSUE THREAD

**Issue by KnudH** [nextcloud/server#19363]
### Steps to reproduce
1. Share a dir, allow writing only, not creating
2. Login as user who the dir is shared with
3. Download file, edit, try to upload (all with webinterface)
4. You get the error, that you are not allowed to create, instead of the question to overwrite the file 

### Expected behaviour
New file should overwrite the old one. If user selecting both (old and new) you should get an error, that you are not allowed to create.

### Actual behaviour
See steps to reproduce

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.1 but I am not sure if this is like this by design.
cc @nextcloud/designers for further input on this.

**Comment by KnudH** [comment]
Which essential information is missing? Nobody is caring about this bug - thats the problem I think.
