### ISSUE TITLE
Problem: setup failed to create NC database user on NC 18 and mariaDB 10.3

### ISSUE THREAD

**Issue by argltuc** [nextcloud/server#19390]
System configuration:
Debian 10.2 (fresh install)
MariaDB 10.3.22
PHP 7.3
latest Nextcloud setup file from 2020-02-09 (version 18.0.0.10 / OC_BUILD String: '2020-01-17T13:48:20+00:00 905d07a85061e00f9ce735467bc68a1c24f44a9b')

Problem description:
While start an initial setup of NC 18, following error occours:
`Error while trying to create admin user: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1698] Access denied for user 'oc_admin'@'localhost'`

message in nextcloud log-file (its a part of the whole log, skipping the trace):
`"Exception": "Doctrine\\DBAL\\Exception\\SyntaxErrorException",
"Message": "An exception occurred while executing 'CREATE USER 'oc_admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'u/38aC3gPLfeltptYGigFxQQCkPoW1'':\n\nSQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'u/38aC3gPLfeltptYGigFxQQCkPoW1'' at line 1",
"CustomMessage": "Database user creation failed."`

if you will execute the `CREATE USER`-command in mariaDB cli you will get the same error:
`MariaDB [(none)]> CREATE USER 'oc_admin'@'localhost' IDENTIFIED WITH mysql_native_password BY 'u/38aC3gPLfeltptYGigFxQQCkPoW1';
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'BY 'u/38aC3gPLfeltptYGigFxQQCkPoW1'' at line 1`

refering to mariaDB documentation for auth-plugins, `mysql_native_password` is not recommended: https://mariadb.com/kb/en/authentication-plugin-mysql_native_password/

removing `WITH mysql_native_password` from create user command in https://github.com/nextcloud/server/blob/v18.0.0/lib/private/Setup/MySQL.php#L105 and https://github.com/nextcloud/server/blob/v18.0.0/lib/private/Setup/MySQL.php#L107 will fix the problem for the moment for me.

For reference: https://github.com/nextcloud/server/issues/18513

**Comment by kesselb** [comment]
What's the rationale to create a new issue if you found the right one already?

**Comment by argltuc** [comment]
since i found the reference issue only by the "looking same"-feature of github and some further crosslinks while creating this issue and not by searching thru the issue list, i decided to create a new one, which hopefully helps others to solve this very confusing problem.

More helpful would be, that the error message would be more specific. `Access denied for user 'oc_admin'@'localhost'` is technical right, but something like `failed to create user 'oc_admin'` is more helpful to locate where the error occurs.

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/server/pull/19303. Fix will come to 18.0.1 and 17.0.4.
