### ISSUE TITLE
Email Server "From Address" option not working with Gmail SMTP

### ISSUE THREAD

**Issue by Sbellins** [nextcloud/server#19394]
Hi, after setting up nextcloud, when i try sending the test email from the admi page the email arrives without problem but the "from address" and 'from domain' option i configured are not working.

For now i'm using Gmail and it works but i prefer to not show my real email to the users when they receive the mails.

Before this version i was using Nextcloud 14 or 15, i do not remeber. Now with versione 18 donwloaded from the original website is not working.

My setup:
-Raspberry pi 4, 4GB ram
- Apche
- Nextcloud 18 installer from .zip package
-Data directory on a mounted cifs SMB share
- Data files on a server with Windows Server 2019 (all files are crypted) on a private SMB share

I post all the config and images below (some part are in italian becausue i am italian)

![Cattura 1](https://user-images.githubusercontent.com/17677584/74152897-95394400-4c0f-11ea-8f42-18668adf9162.PNG)
![Cattura 2](https://user-images.githubusercontent.com/17677584/74152900-97030780-4c0f-11ea-930c-f438effe7c48.PNG)
![Cattura 3](https://user-images.githubusercontent.com/17677584/74152903-98343480-4c0f-11ea-87ba-6f7c46fa71a6.PNG)

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
