### ISSUE TITLE
Lightbox at shared images

### ISSUE THREAD

**Issue by mggcodes** [nextcloud/server#19407]
### Steps to reproduce
1. share folder with not registered people
2. open shared link
3. click on an image

### Expected behaviour
lightbox opens up with the image

### Actual behaviour
after click download of the file starts

### Server configuration

**Operating system:** Debian9

**Web server:** apache2

**Database:**mysql

**PHP version:** 7

**Nextcloud version:**18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** update from Nextcloud 17

**Where did you install Nextcloud from:** installed with zipfile from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

if you need more information let me know

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Duplicate of https://github.com/nextcloud/viewer/issues/89

**Comment by Wikinaut** [comment]
Same problem detected.
