### ISSUE TITLE
Dockerimage: After Updating Nextcloud dbuser and dbpassword is always overwritten

### ISSUE THREAD

**Issue by Cyber1000** [nextcloud/server#19403]
**Is your feature request related to a problem? Please describe.**
I'm using the dockercontainer with nextcloud 16. I store configs, docker-compose, ... in a git-repo. I don't want to check things like dbuser or dbpassword of config.php in. Therefore my config.php looks like this:
```
  'dbuser' => $_ENV["MYSQL_USER"],
  'dbpassword' => $_ENV["MYSQL_PASSWORD"],
```
Everytime I'm updating nextcloud to a newer version dbuser and dbpassword is exchanged by plaintext password.

**Describe the solution you'd like**
Don't change things like that in config.php

**Describe alternatives you've considered**
Maybe I'm trying to create a template which can recreate config.php on startup of the container. Config.php will  not get committed in my setup. Downside: I won't get the information if something substantial changes within config.php.

**Comment by kesselb** [comment]
I see your point and it's indeed a bit confusing that the configuration is overwritten. I recall another issue about that but unable to find it yet.

> Describe alternatives you've considered

Use [Multiple config.php file](https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file) and put the environment calls there.

**Comment by Cyber1000** [comment]
ok just tested this with an update:
- removed dbuser and dbpassword from config.php and added them to hiddendata.config.php (with envvars)
- updated
- The additional hiddendata.config.php isn't touched -> ok
- the config.php is updated and gets back dbuser and dbpassword in cleartext -> not ok

So I still have to revert the config.php. On updating it doesn't check if dbuser and dbpassword (and others) exist in an additional config-file and recreates them.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by Cyber1000** [comment]
It was still valid with nextcloud 18. If I have some time in the next 2 weeks I'll try this out, if not, I would suggest closing this issue, since it seems that I'm the only one complaining. But I'll try to get some time.
