### ISSUE TITLE
File names disappearing on shared folders

### ISSUE THREAD

**Issue by pphotography** [nextcloud/server#19401]
On my Nextcloud server (17.0.3) I shared a folder (public available without user, only passwort needed) and tested access on various browsers including webbrowsers on smartphones (Firefox for Android and Safari on iPhone).
After removing download links from the share I noticed that the folder names were invisible and only the extensions from the file were visible.

On a desktop browser I reduced the window size and I had the same behavior when the window width got below 1024px.

Since I got my own themed CSS I tried to reproduce that on a nextcloud demo server https://demo2.nextcloud.com/ and had the same behavior there.

Screenshot from demo server with width > 1024px:
![nextcloud01](https://user-images.githubusercontent.com/49001045/74194004-b83c1600-4c58-11ea-814e-ec2f7bea0147.jpg)

Screenshot from demo serverwith width < 1024px:
![nextcloud02](https://user-images.githubusercontent.com/49001045/74194017-ba9e7000-4c58-11ea-91a7-6d933bf29e9b.jpg)

I analyzed the CSS with a inspector and found the following change when the window width gets below 1024px:

```
@media only screen and (max-width: 1024px)
table td.filename .nametext {
```
When I change the max-width to a lower value like 24px I can see the filename again. Therefore I guess it's a CSS issue.

### Steps to reproduce
1. Share a file folder (just protected with a password) with the option to remove download links
2. Open the shared link without being a logged in user of the nextcloud instance
3. Reduce window-width of your browser < 1024px

### Expected behaviour
File and folder names should stay visible

### Actual behaviour
File and folder names disappear

### Server configuration
Installed on a shared webhoster (Hosteurope)

**Nextcloud version:** (see Nextcloud admin page)
17.0.3
**Updated from an older Nextcloud install:**

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

```
No errors have been found.
```

**Comment by skjnldsv** [comment]
Fixed on 18.0.2
