### ISSUE TITLE
plural of german "Sekunde" wrong

### ISSUE THREAD

**Issue by nerdoc** [nextcloud/server#19413]
### Steps to reproduce
1. update Nextcloud via web interface
2. at the end, it coutns a few seconds before it redirects you to "your nextcloud instance"

### Expected behaviour
In German, it's 0 Sekunden, 1 Sekunde, 2 Sekunden (mind the tailing n) - 

### Actual behaviour
this is the other way round: it says 1 Sekunden, 2 Sekunde

### Server configuration

**Operating system:**
Linux/Debian
**Web server:**
apache 2
**Database:**
mysql
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
Update from 16.0.7 to 16.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
tar.gz

I suppose it's just a mix in the German translations:
https://github.com/nextcloud/server/blob/1afe8906bc10247fcabf1651da881e027b3d8279/core/l10n/de.json#L132

**Comment by kesselb** [comment]
Thank you for reporting this :+1:  Translations are synced daily from transifex. Please join https://www.transifex.com/nextcloud/nextcloud/ to help with translations.
