### ISSUE TITLE
Security warning does not handle fallback referrer policy

### ISSUE THREAD

**Issue by SuperSandro2000** [nextcloud/server#19416]
### Steps to reproduce
1. Set a header on the server with ``referrer-policy: no-referrer,strict-origin-when-cross-origin``
2. Open https://nextcloud.example.com/settings/admin/overview
3. Be greeted by a warning about the referrer policy

### Expected behaviour
Nextcloud should notice that both the normal and fallback header are secure according to the recommendation.

### Actual behaviour
Nextcloud warns me with
````
The "Referrer-Policy" HTTP header is not set to "no-referrer", "no-referrer-when-downgrade", "strict-origin", "strict-origin-when-cross-origin" or "same-origin". This can leak referer information. See the W3C Recommendation ↗.
````

### Server configuration

**Operating system:** Docker

**Web server:** Apache

**Database:** Postgres

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** upgrade from Nextcloud 16 (I think)

**Where did you install Nextcloud from:** Docker Hub

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.9.0
  - bookmarks: 2.3.4
  - breezedark: 18.0.5
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - carnet: 0.20.0
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - drawio: 0.9.4
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_linkeditor: 1.0.11
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.17
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.2
  - metadata: 0.11.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.4
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - ransomware_protection: 1.6.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - smb_test: 0.2.4
  - spreed: 8.0.4
  - talk_simple_poll: 1.1.0
  - tasks: 0.11.3
  - terms_of_service: 1.4.0
  - text: 2.0.0
  - theming: 1.9.0
  - timetracker: 0.0.41
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - uploaddetails: 0.1.2
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - sharebymail
  - support
  - survey_client
  - systemtags
  - twofactor_admin
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbtype": "pgsql",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "has_rebuilt_cache": true,
        "htaccess.RewriteBase": "\/",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "jpeg_quality": "60",
        "loglevel": 2,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpmode": "smtp",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpsecure": "ssl",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "token_auth_enforced": true,
        "trashbin_retention_obligation": "auto, 30",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "twofactor_enforced": "true",
        "twofactor_enforced_excluded_groups": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "twofactor_enforced_groups": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "version": "18.0.0.10",
        "versions_retention_obligation": "auto, 90",
        "data-fingerprint": "9db06f6b7f1dfa9706ec8a9e6d234c82",
        "app_install_overwrite": [
            "uploaddetails",
            "drawio"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by kesselb** [comment]
A common reason for that warning is that the header is set twice. You can check that with curl -I xxx.com

**Comment by SuperSandro2000** [comment]
Checked that. The header is only set once.

````shell
curl -sI https://nextcloud.example.de | grep -e [Rr]eferrer-[pP]olicy
referrer-policy: no-referrer,strict-origin-when-cross-origin
````

**Comment by kesselb** [comment]
Is no-referrer-when-downgrade not longer recommended?

**Comment by SuperSandro2000** [comment]
``no-referrer-when-downgrade`` is still in the warning and also ``no-referrer`` and ``strict-origin-when-cross-origin``. Because the two I am using are in the recommended list of the warning I believe this is a bug as it also started to show up as I switched to the fallback header.

PS: the link to the w3c at the end is missing an ``target="_blank"``.

**Comment by kesselb** [comment]
Ah. The check does not support a fallback policy: https://github.com/nextcloud/server/blob/443181f9502cf7b9e552b89003bc7940fd745a17/core/js/setupchecks.js#L575

**Comment by SuperSandro2000** [comment]
Should I open a new issue for the ``target="_blank"`` from https://github.com/nextcloud/server/blob/443181f9502cf7b9e552b89003bc7940fd745a17/core/js/setupchecks.js#L582 not showing up in the web?

The HTML looks like this:
````
<a href="https://www.w3.org/TR/referrer-policy/" rel="noreferrer noopener">W3C Recommendation ↗</a>
````
