### ISSUE TITLE
Not updated translation of "Support"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#19410]
Translations for "Suport" from Transifex have not been updated for over 8 months.

![obraz](https://user-images.githubusercontent.com/47037905/74254044-326ba980-4cf0-11ea-8a5c-fcfd504ca76d.png)

### Steps to reproduce

1. Enter the administrator settings.
2. Select "Support".

### Expected behaviour
New translations from Transifex.

### Actual behaviour
There are old translations from Transifex and no new ones.

**Nextcloud version:** (see Nextcloud admin page)
18.0.0 and 18.0.0 Beta3

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by Valdnet** [comment]
@szaimen The problem is still there. Also in version 22.0.0 beta 2.

**Comment by szaimen** [comment]
cc @nextcloud/javascript Please advice where this needs to be fixed in the code. Thanks!

**Comment by gary-kim** [comment]
The support app repository is still private so this is something only Nextcloud GmbH employees can fix, unfortunately.

**Comment by Valdnet** [comment]
@MorrisJobke You can check it :wink:?

**Comment by Valdnet** [comment]
@nickvergessen Maybe you can check where is the error :wink:?
Morris is currently on vacation.

**Comment by nickvergessen** [comment]
There is no automation of this app, so someone has to do it manually. But I don't have access to the machine. Either @blizzz has or we need to wait for Morris

**Comment by MorrisJobke** [comment]
> There is no automation of this app, so someone has to do it manually. But I don't have access to the machine. Either @blizzz has or we need to wait for Morris

I just do it on my local machine. Let me do it again

**Comment by MorrisJobke** [comment]
Done for 19, 20, 21 and master.
