### ISSUE TITLE
locked directory error on uploading folder with many small files

### ISSUE THREAD

**Issue by pasdVn** [nextcloud/server#19415]
### Steps to reproduce
1. Setup nextcloud with ngingx, php-fpm, mariadb and (optionally) redis by using this docker-compose example: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm 
2. Create a folder containing a lot of quite small files. For example I used: 
`for n in {1..5000}; do dd if=/dev/urandom of=file$( printf %03d "$n" ).bin bs=1 count=$(( RANDOM + 128 )); done`
3. Drag and drop the folder in the Nextcloud web interface (Files "app")

### Expected behaviour
All files should get copied correctly.

### Actual behaviour
During copying you will get some error message boxes in the upper right corner saying that _**"path/to/folder" is locked**_, where the path/to/folder always varies a bit (the path to the new copied folder path itself, or some upper folder - depending on weather you copied to the root directory or some deeper path).
The number of error pop ups you get is equal to number of missing files after the operation finishes.

### Server configuration

**Operating system:**
Host system is ubuntu 18.04

**Web server:**
nginx version: nginx/1.17.8

**Database:**
mysqld  Ver 10.4.12-MariaDB-1:10.4.12+maria~bionic for debian-linux-gnu on x86_64 (mariadb.org binary distribution)

**PHP version:**
PHP 7.3.14 (fpm-fcgi) (built: Jan 24 2020 08:45:10)

**Nextcloud version:** (see Nextcloud admin page)
18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install (docker-compose)

**Where did you install Nextcloud from:**
docker compose: https://github.com/nextcloud/docker/tree/master/.examples/docker-compose/insecure/mariadb-cron-redis/fpm

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:8080"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "http:\/\/localhost:8080",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
no

### Client configuration
**Browser:**
Firefox 72.0.2

**Operating system:**
ubuntu 18.04

#### Web server error log
I uploaded the full log of all docker containers here (`docker-compose up > log`, note that this is not the first startup, i.e. you will only see the copy operation): https://gist.github.com/pasdVn/260c4d8fb436f7b3c3f1d0f6d2810dac

#### Nextcloud log (data/nextcloud.log)
nothing during the copy operation

#### Browser log
did not capture

### Additional info
- Originally I am experiencing this issue on a "nativ" setup on a vanilla debian buster (nginx 1.14.2, php 7.3.11, mariadb 15.1, redis ) with nextcloud 17.0.3.
- This bug also occurs if you don't use redis for locking but the db. In this yust the pop-up-error-message in the web interface looks a bit different (e.g. `An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1581116428, "files\/2535199b935e72595f64b6b88e6ae476"]: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transactional`) and you also get an error log entry in the nextcloud log, like:
```
[webdav] Fatal: Doctrine\DBAL\Exception\DeadlockException: An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = `lock` + 1, `ttl` = ? WHERE `key` = ? AND `lock` >= 0' with params [1581116428, "files\/2535199b935e72595f64b6b88e6ae476"]:

SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... n", Doctrine\DBAL\Dr ... ]})
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... n")
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "UPDATE `oc_file ... 0", {1: 1581116428,2 ... "})
 3. /var/www/nextcloud/lib/private/DB/Connection.php line 216
    Doctrine\DBAL\Connection->executeUpdate("UPDATE `oc_file ... 0", [1581116428,"fil ... "], [])
 4. /var/www/nextcloud/lib/private/Lock/DBLockingProvider.php line 189
    OC\DB\Connection->executeUpdate("UPDATE `oc_file ... 0", [1581116428,"fil ... "])
 5. /var/www/nextcloud/lib/private/Files/Storage/Common.php line 743
    OC\Lock\DBLockingProvider->acquireLock("files/2535199b935e72595f64b6b88e6ae476", 1)
 6. /var/www/nextcloud/lib/private/Files/View.php line 1940
    OC\Files\Storage\Common->acquireLock("tobias", 1, OC\Lock\DBLockingProvider {})
 7. /var/www/nextcloud/lib/private/Files/View.php line 2054
    OC\Files\View->lockPath("/tobias", 1)
 8. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 154
    OC\Files\View->lockFile("/tobias/files/F ... t", 2)
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
    OCA\DAV\Connector\Sabre\Directory->createFile("file066 (Kopie).bin", null)
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
    Sabre\DAV\Server->createFile("Filetest-FLAT/file066 (Kopie).bin", null, null)
11. <<closure>>
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
12. /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
13. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
14. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
15. /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
    Sabre\DAV\Server->exec()
16. /var/www/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/nextcl ... p")
```
- additionally you then can't delete the uploaded directory afterwards anymore, due to some orphaned locks (you need to manually clean oc_file_locks)

**Comment by LightOfShadow** [comment]
Same problem here with Nextcloud Version 18.0.4 on Ubuntu 18.04.5. Are there any new informations regarding this topic?

**Comment by pasdVn** [comment]
With NC 19.0.3 I do not have this issue anymore...
@LightOfShadow Can you confirm this on your setup?

**Comment by szaimen** [comment]
Based on pasdVn's comment I am closing this.
If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
