### ISSUE TITLE
Files: Add a MD5-checking tool to verify the integrity of downloaded files

### ISSUE THREAD

**Issue by PatAuge** [nextcloud/server#1942]
To make sure that downloaded files are secure:
- Calculate and display MD5 checksum of multiple files at one time.
- Use MD5 checksum to fleetly verify whether files have been changed.
- Load, save, add, remove and update MD5 checksum conveniently.

**Comment by matunixe** [comment]
That would be a very usefull feature! 👍

**Comment by LukasReschke** [comment]
Seems like a duplicate of https://github.com/nextcloud/server/issues/1381
