### ISSUE TITLE
NC18 no login with old iOS anymore

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#19434]
Hello Masters,

after upgrading to NC18, I can not log in with an old iPad on iOS 9 anymore.
The login-page is half empty.

![IMG_0668](https://user-images.githubusercontent.com/13385119/74341949-f6e0e600-4da8-11ea-9583-ec9577c82d64.PNG)

console shows some vue issues:
![Screenshot 2020-02-12 at 15 05 20](https://user-images.githubusercontent.com/13385119/74342033-1a0b9580-4da9-11ea-95c9-be155cff3626.png)

is this break in compatibility on purpose os is there a chance to keep the tabled for some more time?

thank you!

**Comment by szaimen** [comment]
Hi, did you try with another browser, too or does it fail with others, too?
