### ISSUE TITLE
NotPermittedExceptions are missing key information

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#19444]
When a `OCP\Files\NotPermittedException` occurs, the log contains a `Message` such as "Could not create folder" but it does not specify which folder it could not create. As a result, the message is not useful because it is not actionable.

Instead, the exception should be thrown with the full path of the folder or file whose creation failed, and that parameter should be shown in the log.

This exception also is typically not reproduceable (due to caching?) so in practice installations cannot be fixed because by the time you add error messages to the PHP, they won't happen again.

This has been around for a while, most recently seen in 17.0.3.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
