### ISSUE TITLE
Sharing single file via link sometimes links to old version of file in trash

### ISSUE THREAD

**Issue by XANi** [nextcloud/server#1944]
Sharing file then editing it sometimes will link to old file version in trash.

I've seen that few times with desktop files (use case was one of our users sharing .pngs to customer).

I *think* what happens is app that saves file does 

* save in tmpfile
* remove/move original file,
* move new file to the correct name

and if sync runs in point 2 it looks like file was deleted and re-created from perspective of server

### Steps to reproduce
1. Create file
2. Remove file
3. Create file with same name

### Expected behaviour
Should not link to file in trash

### Actual behaviour
Should link to current file version under same path and name as shared

share: 

    mysql> select * from oc_share where id =  3993
        -> ;
    +------+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------+-------------+------------+----------+---------------------+-----------------+-----------+---------------+
    | id   | share_type | share_with | uid_owner | parent | item_type | item_source | item_target | file_source | file_target   | permissions | stime      | accepted | expiration          | token           | mail_send | uid_initiator |
    +------+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------+-------------+------------+----------+---------------------+-----------------+-----------+---------------+
    | 3993 |          3 | NULL       | dkacprzak |   NULL | file      | 1544282     | NULL        |     1544282 | /tekstowy.txt |           1 | 1477658134 |        0 | 2016-11-27 00:00:00 | xxxxxx13Bby6Pme |         0 | xxxxxxxxxx    |
    +------+------------+------------+-----------+--------+-----------+-------------+-------------+-------------+---------------+-------------+------------+----------+---------------------+-----------------+-----------+---------------+

before:

    mysql> select * from oc_filecache where fileid = 1544282 limit 10;
    +---------+---------+----------------------------+----------------------------------+---------+--------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
    | fileid  | storage | path                       | path_hash                        | parent  | name         | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions | checksum |
    +---------+---------+----------------------------+----------------------------------+---------+--------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
    | 1544282 |      11 | files/Testowy/tekstowy.txt | 470f302ad7aefe83f4b3346a52004ab1 | 1544278 | tekstowy.txt |       21 |       13 |   28 | 1477659491 |    1477659491 |         0 |                0 | 686d07eb43ceeb5174ec1df0957d85d0 |          27 |          |
    +---------+---------+----------------------------+----------------------------------+---------+--------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
    1 row in set (0.00 sec)

after: 

    mysql> select * from oc_filecache where fileid = 1544282 limit 10;
    +---------+---------+-----------------------------------------------+----------------------------------+---------+--------------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
    | fileid  | storage | path                                          | path_hash                        | parent  | name                     | mimetype | mimepart | size | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions | checksum |
    +---------+---------+-----------------------------------------------+----------------------------------+---------+--------------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
    | 1544282 |      11 | files_trashbin/files/tekstowy.txt.d1477659604 | a40c4805febf8bf0ba855d554f3d83fd | 1214075 | tekstowy.txt.d1477659604 |        9 |        3 |   28 | 1477659491 |    1477659491 |         0 |                0 | 686d07eb43ceeb5174ec1df0957d85d0 |          27 |          |
    +---------+---------+-----------------------------------------------+----------------------------------+---------+--------------------------+----------+----------+------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+

### Server configuration
**Operating system**: Server: CentOS6 , Desktop: all

**Web server:**Nginx

**Database:**MySQL

**PHP version:**5.6

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Comment by rullzer** [comment]
I don't see the bug.

If you share `foo.txt` by link. And remove that file it moves the file to the trash. At that point the link no longer works. the share still exists for when you restore from the trash.

The link is bound to a fileid not the path.

**Comment by XANi** [comment]
I might've debugged it wrong but  we hit into weird behaviour some of our users are complaining about and I try find out if it is something weird they are doing. 

We have users that basically share a file to client then (usually using desktop client) constantly replace it with new version and at some point it starts to point out to old version of that file

**Comment by rullzer** [comment]
When you say replace. How does the program they use replace? Does it do

1. Delete `foo.png`
2. Save `foo.png`

Because if that is the case then there is not much I can do I fear. If the client notices between step 1 and 2 that the file is gone it will send the corresponding delete to the server.

I just ask because I have been overwriting files in a look now for 30 min and the syncs still work normal here.

**Comment by XANi** [comment]
That is most likely the case. I guess I just push the info to share folder instead of file to the users as it seems that was caused by user or his app doing something weird. Thanks for help :)
