### ISSUE TITLE
Production channel has disappeared for no good reason

### ISSUE THREAD

**Issue by ShamimIslam** [nextcloud/server#19447]
### Steps to reproduce
1. Update production site from 16.0.7 to 16.0.8
2. Update completes. Updater reports production update to 17.0.3
3. Update completes - channel is now stable

### Expected behaviour
Update should stay on production channel or users should be alerted that their channel of choice is no longer supported.

### Actual behaviour
Update completes to 17.0.3 and we are now on channel stable

While I agree that it is to NextCloud's choice to deprecate or even remove the production channel, to do so without warning is very irresponsible. 

I am a small time nextcloud user that relies on production quality code. The stable channel is not production quality and always has SOME bugs in it. It was not necessary to force me to go into the stable channel. 

I should have the wherewithall to decide my own fate and to make the choices I want to do. 

I switched to NextCloud specifically because ownCloud was not doing this.

Now, Nextcloud is repeating the same behavior. I woud have rather had the updater tell me that no further production updates were available than to be forced into a channel I do not want.

Additionally, you only had to disable the automated updates via updater.phar.

It was not necessary to provide false advertisting in the updater that a new production build was available. 

And believe me. Stable is not production. Even in 16.0.6, the external storage code was not working correctly until certain changes in 17.0.1 were backported to 16.0.7.

Thank you.

**Comment by kesselb** [comment]
Please join the discussion at https://help.nextcloud.com/t/production-channel-removal/64223/44.
