### ISSUE TITLE
Wrong update notification

### ISSUE THREAD

**Issue by 2edff206** [nextcloud/server#1945]
### Steps to reproduce
1. Log in to a running instance of Nextcloud 10
2. You get a notification about "a newer version is available Owncloud 9.1.1" (it's not a typo)

### Expected behaviour
You should get notification only for newer versions, not older. And of course, this is NextCloud, not ownCloud, so there is a strange behaviour here.

### Actual behaviour
You get a notification about "a newer version is available Owncloud 9.1.1" (it's not a typo)

### Server configuration
**Operating system**: Ubuntu 16.04.1 LTS

**Web server:** Apache

**Database:** Mysql

**PHP version:** 7

**Nextcloud version:**  10

**Updated from an older Nextcloud/ownCloud or fresh install:** Don't remember

**Where did you install Nextcloud from:** Don't remember

**Signing status:** 
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
root@ns330357:/var/www/html/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.0
  - documents: 0.13.1
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - twofactor_totp: 0.4.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - ownbackup
  - ownnote
  - user_external
  - user_ldap
  - user_saml

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

{
    "system": {
        "instanceid": "ocscai48ez31",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "\/var\/www\/html\/nextcloud\/data",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "9.1.0.16",
        "dbname": "nextcloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "daily",
        "maintenance": false,
        "loglevel": 2,
        "appstore.experimental.enabled": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** dropbox

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Firefox

**Operating system:** Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
See https://help.nextcloud.com/t/notification-about-an-upgrade-to-owncloud-9-1-1-in-nextcloud-10-stable/4573/7

Please update manually to 10.0.1 then the message should be correctly in the future

**Comment by nickvergessen** [comment]
And just for the record, 9.1.1 is the internal version of 10.0.1, so it's basically advertising the "same" version
