### ISSUE TITLE
Errors when updating to 18.0.1

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#19457]
Updated to NC18.0.1. Got http 502. Tried occ maintenance:repair and found an error in association with spreed. Tried to deactivate spreed via terminal but did not help.

Restored my snapshot and found out that the nonactivated JavaScript XMPP Chat had a new version needing upgrade. Upgraded. Did the server upgrade to 18.0.1. Now I also got http 502. 
Did occ upgrade via terminal which went on well except for these errors

Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Checked for update of app "spreed" in appstore
Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown

Anyhow now I could access the site via the browser and so far I think everything works. I have these errors in the log 

Error | no app in context | Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "user_saml.SAML.assertionConsumerService" as such route does not exist. |   | 2020-02-13T13:08:39+0100
-- | -- | -- | -- | --
Error | no app in context | Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "user_saml.SAML.getMetadata" as such route does not exist. |   | 2020-02-13T13:08:39+0100
Error | no app in context | Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "user_saml.SAML.base" as such route does not exist. |   | 2020-02-13T13:08:39+0100
Error | PHP | "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /var/www/nextcloud/apps/workflowengine/lib/Helper/LogContext.php#55

+ a number of 
{"reqId":"1E3Olil3F7sn0Y6wNw31","level":0,"time":"2020-02-13T13:06:29+01:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Deprecated event type for \\OC\\Repair::step: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"--","version":"17.0.3.1","id":"5e4542ed4aa1a"}

**Comment by Dragon988** [comment]
Backup all files, database and config.php. Download 18.0.1 from the nextcloud website and not github.. that's important.

Extract, restore the config.php and browse the website to run the updater. Do not use occ.

Flawless upgrade from 18.0.1 RC2 at least.

**Comment by Luticus** [comment]
During my upgrade from 18.0.0 to 18.0.1 I also go these errors:  

  1 Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
  2 Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
  3 Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
  4 Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown 

Everything else seemed fine.  

To upgrade, I pulled update from nextcloud.com, extracted, copied the config file and did:  sudo -u www-data php occ upgrade

This method has always worked in the past.  

Interestingly so far everything *seems* to work.  I guess we will see when I test out the talk app.  I suspect if anything will be impacted it would be that.

**Comment by livier** [comment]
from 17.0.4 to 18.0.3

Ugrade via UI, finished with a white page at reload.

nextcloud$ php occ -V
Nextcloud 18.0.3

nextcloud$ php occ upgrade
long green lines, and at the end : 
```


Checking for update of app spreed in appstore
Update app spreed from appstore
Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Checked for update of app "spreed" in appstore 
Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
```
Seem to word even with theses errors, I'll come back if not.

**Comment by wajumaju** [comment]
In my case, I was missing php-cURL lib, so the UI installed failed with the same Repair Errors listed above and then went into maintenance mode.

Steps to fix:

`apt install php-curl`

then

`sudo -u www-data php occ upgrade`

and finally:

`sudo -u www-data php occ maintenance:mode --off`

**Comment by Luticus** [comment]
this is not the case for me.  I have php7.3-curl installed.

**Comment by danuker** [comment]
Under Debian 10 (buster), installing php-curl (latest version 2:7.3+69), this fixed my problem. Thanks @wajumaju .

**Comment by pcavalcanti** [comment]
Under FreeBSD 12.1 I have php74-curl installed and the same error appears. What can I do?
Upgraded from 18.0.6 to 18.0.7.

**Comment by szaimen** [comment]
I think this was fixed in the Talk app in the meantime. Please reopen if this shouldn't be the case.
