### ISSUE TITLE
usernames visible

### ISSUE THREAD

**Issue by droogi** [nextcloud/server#19467]
all usernames are visible via nextcloud talk,
usefull when own server, 
maybe not useful if on public server
-->

### Steps to reproduce
1. e.g. owndrive.com
2. create free account
3. goto talk, see all? alot of users

### Expected behaviour
I do not want to be on the public talk list

**Comment by kesselb** [comment]
cc @nextcloud/talk 🤷‍♂️

**Comment by nickvergessen** [comment]
Well, ask the admin of the instance to check the sharing settings. There are quite some that should help to make it a bit more private.
