### ISSUE TITLE
streamerInstance never set to TarStreamer

### ISSUE THREAD

**Issue by gbeekmans** [nextcloud/server#19468]
Nextcloud version: 17.0.3
OS: Ubuntu 18.04
Web server: Apache
PHP version: 7.2.24

I have a use case where I prefer to download a directory in tar format instead of the default zip. This is to be accomplished by sharing a directory and downloading it using wget or curl as https://nextcloud.domain.com/sharelink/download

There is code in lib/private/Streamer.php that is supposed to use TarStreamer if the user agent in the HTTP headers contains "macintosh" or "mac os x". The thought was to force a user-agent to match that so it's triggered.

It doesn't work due to the implementation of public function __construct(), specifically this part:

```php
if ($size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {`
  $this->streamerInstance = new ZipStreamer(['zip64' => false]);
} else if ($request->isUserAgent($this->preferTarFor)) {
  $this->streamerInstance = new TarStreamer();
} else {
  $this->streamerInstance = new ZipStreamer(['zip64' => PHP_INT_SIZE !== 4]);
}
```

The size and number of files check will always be true unless you're actually downloading something larger than 4 GB or more than 65,536 files. The "else if" is never evaluated as a result.

I am not 100% sure of the desired intention but maybe the code can be reworked to first check for the tar preference, then sort out if it should be zip32 or zip64.

Something like this might work:
```php
if ($request->isUserAgent($this->preferTarFor)) {
  $this->streamerInstance = new TarStreamer();
} else if ($size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
  $this->streamerInstance = new ZipStreamer(['zip64' => false]);
} else {
  $this->streamerInstance = new ZipStreamer(['zip64' => PHP_INT_SIZE !== 4]);
}
```
With this change made I receive a zip file when I run:

`wget --content-disposition sharelink/download`

And I receive a tar file when I run:

`wget --content-disposition --user-agent "macintosh" sharelink/download`

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
