### ISSUE TITLE
Scrollbar position/background colour

### ISSUE THREAD

**Issue by SR4ven** [nextcloud/server#19474]
### Steps to reproduce
1. Select dark theme
2. Open files/activity app with a folder that has enough elements to trigger the scrollbar

Can be reproduced on NC [demo](https://try.nextcloud.com/) instances

### Expected behaviour
Scrollbar should look like this (taken from settings/logging):
![grafik](https://user-images.githubusercontent.com/46794237/74519213-97ecaf80-4f15-11ea-812c-d07bc4bfe24b.png)

### Actual behaviour
Scrollbar is global and outside of the files app content window. 
The positioning of scrollbar "outside" of the page also results in it inheriting the wrong background colour when using the dark theme.
![grafik](https://user-images.githubusercontent.com/46794237/74519375-dbdfb480-4f15-11ea-8dad-dfe09bf0bd74.png)

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Firefox 73.0

**Operating system:**
Windows 10 1909

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by paulijar** [comment]
I don't think that the coloring of the scroll bar is related to its location. Instead, the scrollbar seems to have incorrect color on NC18 dark theme because of the style definition high-lighted in the following screenshot:
![image](https://user-images.githubusercontent.com/8565946/75092329-10d7b100-557f-11ea-958b-b3cdc9cf4b71.png)

This definition doesn't seem to make much sense, and it shadows the correct definition `background-color: var(--color-main-background);`. If you untick the culprit style definition in the browser development tools, then the scrollbar gets the correct dark color.

This same style definition was the root cause of the error https://github.com/owncloud/music/issues/739.

**Comment by SR4ven** [comment]
The background color of the scrollbar is set to transparent, so it does depend on where it's located.
https://github.com/nextcloud/server/blob/d3f2bda90cc68fcaf4e66465d1f684841ffad863/core/css/styles.scss#L27

Deactivating the style definition you mentioned does indeed solve the coloring issue. These changes were introduced in #18082 and it seems that the theming support was not taken too serious there.
In my css there are still many entries similar to the one mentioned before with rgba(28,175,255,1) (bluish) although I have set a custom color theme. The mentioned PR set that color statically, not very friendly for theming.
This is definitely something that should be taken care of.

I could open a PR removing https://github.com/nextcloud/server/blob/d3f2bda90cc68fcaf4e66465d1f684841ffad863/core/css/styles.scss#L90
but I think this should be properly cleaned up/fixed and I don't really feel qualified for this.

However I still think that the scrollbar is in the wrong place. Even with the fixed color it just doesn't look very nice with the header not filling the full page width.

![image](https://user-images.githubusercontent.com/46794237/75093012-27313d00-557e-11ea-9845-cb2348d74d07.png)

I find the appearance shown in the expected behaviour of my original post much more appealing.
If I knew how to move the sidebar around, I'd open a PR, but sadly this is far beyond my very limited webdev skills.

**Comment by SR4ven** [comment]
The color is fixed in NC19, but nothing has changes about the position.
Seems like this is intended.
