### ISSUE TITLE
Apps DB Migration issues can bring down upgrade

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#19473]
### Steps to reproduce

For instance

1. Use Postgres DB (9.6 at least)
2. have circles (0.17.x) enabled (and 0.18.1 offered)
3. upgrade to 18.0.1  

### Expected behaviour

With the DB migration issue the app will be disabled, but the upgrade continues successfully

### Actual behaviour

https://github.com/nextcloud/circles/issues/367

**Comment by blizzz** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
The stacktrace of the circles issue says AppSettingsController

So it is not while updating nextcloud itself, just the app.

**Comment by nickvergessen** [comment]
Also the exception from:
https://github.com/nextcloud/server/blob/d06ef07a97a9ca8826d9c47c925f633c145683a7/lib/private/Installer.php#L157

Should be catched in the controller which is were the log comes from:
https://github.com/nextcloud/server/blob/faf18b5f02b2f560566965030d6ca97407d3445e/apps/settings/lib/Controller/AppSettingsController.php#L457

and the error of the request i should be handled by:
https://github.com/nextcloud/server/blob/ec01e0a790448fff38364f629a4de4edb5d465bf/apps/settings/src/store/apps.js#L205-L213

so not sure. Seems like an error in the frontend trying to handle things?

**Comment by blizzz** [comment]
> The stacktrace of the circles issue says AppSettingsController
> 
> So it is not while updating nextcloud itself, just the app.

Alright, thanks for looking into it so far!

I hit this when upgrading, on CLI. I am afraid I don't have my stack trace anymore. However, this would suggest to deal with it before any Controller, or have the code secured in more places, also valid.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
