### ISSUE TITLE
How to set read and upload options without delete to anonymous logins

### ISSUE THREAD

**Issue by ukreddy-erwin** [nextcloud/server#19476]
For edit option:
not logged in, anonmous user able to delete
For readonly option:
can download can't upload
For filedrop:
cant see existing files but can upload

But any option to upload/download but can't delete?

Can you see this image once fir details.

[https://raw.githubusercontent.com/ukreddy-erwin/logs/master/nextcloud/gif.gif](url)

**Comment by bpcurse** [comment]
As far as I can tell this is a missing feature.

It can neither be achieved through WebUI nor through share API and file access control app would completely block access to a file/folder.

@ukreddy-erwin I think this should become a feature request.

**Comment by bpcurse** [comment]
(Ugly) workaround for Nextcloud 18.x:

Create two share links targeting the same folder
- create an upload only link for folder x
- create a read only link for folder x
- Put the upload link inside folder x (e.g. by using Link Editor app, so users can open it easily)
- Share the read only link

By experimenting with this I have found a bug in 16.0.7 and 17.0.3:
If you give the two links different permissions, the permissions of one of the links are reset.

But it's working fine on 18.0.1

**Comment by bpcurse** [comment]
This already has a solution (or at least a better workaround) and can probably be closed.
https://github.com/nextcloud/server/issues/6620#issuecomment-538298248

**Comment by szaimen** [comment]
Please add this feature to the discussion in https://github.com/nextcloud/server/issues/26691 if not already present.
Thanks!
