### ISSUE TITLE
Three dots menu not viewable on mobile browser in portrait view when longish file name used

### ISSUE THREAD

**Issue by jdaviescoates** [nextcloud/server#19479]
### Steps to reproduce
1. Visit share link of a document with a longish title in a mobile browser 
2. Don't see any option to download/ 3 dots menu button 
3. That's it

### Expected behaviour
I expect to always be able to see the 3 dots menu button. Even if the filename would normally take up the whole width of the screen, the 3 dots menu should always be viewable on top of it.

### Actual behaviour
Cannot see 3 dots menu when viewing files with long filenames in portrait view on mobile browsers (checked both Firefox and Chrome), see e.g. this file https://office.uniteddiversity.coop/s/S4cqnY3GRE6zsMx

### Server configuration

**Operating system:**

Ubuntu 18.04

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud 18.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated

**Where did you install Nextcloud from:**

Cloudron

**Signing status:**
<details>
<summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - calendar: 2.0.1
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.8
  - dav: 1.14.0
  - deck: 0.8.0
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.2
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - carnet
  - circles
  - drawio
  - encryption
  - files_external
  - files_mindmap
  - files_opds
  - gallery
  - groupfolders
  - notes
  - socialsharing_diaspora
  - socialsharing_email
  - socialsharing_facebook
  - socialsharing_twitter

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "office.uniteddiversity.coop"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/office.uniteddiversity.coop\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "5432",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forcessl": "1",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": "login",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "2525",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "office.uniteddiversity.coop",
        "overwriteprotocol": "https",
        "updatechecker": false,
        "updater.release.channel": "cloudron",
        "lost_password_link": "https:\/\/my.uniteddiversity.org\/api\/v1\/session\/password\/resetRequest.html",
        "logfile": "\/run\/nextcloud\/nextcloud.log",
        "loglevel": "3",
        "debug": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "integrity.check.disabled": true,
        "htaccess.RewriteBase": "\/",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "has_rebuilt_cache": true,
        "app_install_overwrite": [
            "files_opds"
        ]
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+----------------------------------------------------+
| Configuration                 |                                                    |
+-------------------------------+----------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                  |
| homeFolderNamingRule          |                                                    |
| lastJpegPhotoLookup           | 0                                                  |
| ldapAgentName                 |                                                    |
| ldapAgentPassword             | ***                                                |
| ldapAttributesForGroupSearch  |                                                    |
| ldapAttributesForUserSearch   | displayName;mail                                   |
| ldapBackupHost                |                                                    |
| ldapBackupPort                |                                                    |
| ldapBase                      | ou=users,dc=cloudron                               |
| ldapBaseGroups                | ou=groups,dc=cloudron                              |
| ldapBaseUsers                 | ou=users,dc=cloudron                               |
| ldapCacheTTL                  | 600                                                |
| ldapConfigurationActive       | 1                                                  |
| ldapDefaultPPolicyDN          |                                                    |
| ldapDynamicGroupMemberURL     |                                                    |
| ldapEmailAttribute            | mail                                               |
| ldapExperiencedAdmin          | 0                                                  |
| ldapExpertUUIDGroupAttr       |                                                    |
| ldapExpertUUIDUserAttr        | uid                                                |
| ldapExpertUsernameAttr        | username                                           |
| ldapExtStorageHomeAttribute   |                                                    |
| ldapGidNumber                 | gidNumber                                          |
| ldapGroupDisplayName          | cn                                                 |
| ldapGroupFilter               |                                                    |
| ldapGroupFilterGroups         |                                                    |
| ldapGroupFilterMode           | 0                                                  |
| ldapGroupFilterObjectclass    |                                                    |
| ldapGroupMemberAssocAttr      |                                                    |
| ldapHost                      | ldap://172.18.0.1                                  |
| ldapIgnoreNamingRules         |                                                    |
| ldapLoginFilter               | (&(objectclass=user)(|(username=%uid)(mail=%uid))) |
| ldapLoginFilterAttributes     |                                                    |
| ldapLoginFilterEmail          | 1                                                  |
| ldapLoginFilterMode           | 0                                                  |
| ldapLoginFilterUsername       | 1                                                  |
| ldapNestedGroups              | 0                                                  |
| ldapOverrideMainServer        |                                                    |
| ldapPagingSize                | 500                                                |
| ldapPort                      | 3002                                               |
| ldapQuotaAttribute            |                                                    |
| ldapQuotaDefault              |                                                    |
| ldapTLS                       | 0                                                  |
| ldapUserAvatarRule            | default                                            |
| ldapUserDisplayName           | displayname                                        |
| ldapUserDisplayName2          |                                                    |
| ldapUserFilter                | (|(objectclass=user))                              |
| ldapUserFilterGroups          |                                                    |
| ldapUserFilterMode            | 0                                                  |
| ldapUserFilterObjectclass     | user                                               |
| ldapUuidGroupAttribute        | auto                                               |
| ldapUuidUserAttribute         | auto                                               |
| turnOffCertCheck              | 0                                                  |
| turnOnPasswordChange          | 0                                                  |
| useMemberOfToDetectMembership | 1                                                  |
+-------------------------------+----------------------------------------------------+

</details>

### Client configuration
**Browser:**

Firefox
Chrome

**Operating system:**

Android 8.1.0

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Wrongly closed - reopen.
