### ISSUE TITLE
Enhance the share dialog

### ISSUE THREAD

**Issue by Dennis1993** [nextcloud/server#19489]
**Is your feature request related to a problem? Please describe.**
Some users don't unserstand how they can share files. The people don't check it, that the link to share is on the sidebar because the plus icon is to simple and not good visible.

**Describe the solution you'd like**
In some versions before the share functionality was a extra dialog. If the user would share some files a new dialog was appeared and all possibility was displayed. Every user understand what is to do. Maybe we can discus about that.
At the moment all variations are located on the sidebar and the users dont know what is to do know. 
![image](https://user-images.githubusercontent.com/1473674/74586570-33028980-4fe9-11ea-8487-2772a5c58335.png)

If a user check that and create a link they see a green tick and think all is perfect and send the link.
![image](https://user-images.githubusercontent.com/1473674/74586600-70671700-4fe9-11ea-85b9-a21ca34e34a5.png)

No users knows that he can grant permissions to the share. Every two days I receive a call about that, the shared file cant be changed. The default option is "read only". If I show how it works all users said, why is it so complicated and not a simple dialog with a little wizard. The options are not easy enough
![image](https://user-images.githubusercontent.com/1473674/74586642-c6d45580-4fe9-11ea-8400-c42fa7bbf13f.png)

**Describe alternatives you've considered**
The idea is to bring back the old extra dialog modal window with all options. I don't know in which version it was but the users know what is to do because it is very simple and self explanatory.

In ownCloud it is at the moment and users know what is to do here:
![image](https://user-images.githubusercontent.com/1473674/74586666-1e72c100-4fea-11ea-8a63-cc5b9fa8b475.png)

**Comment by Dennis1993** [comment]
A part of it: https://github.com/nextcloud/server/issues/1963

**Comment by szaimen** [comment]
Hi, please add your concerns to the discussion in https://github.com/nextcloud/server/issues/26691 if they aren't already addressed there. Thanks!

**Comment by jancborchardt** [comment]
@Dennis1993 this was fixed in the recent sharing redesign which moved this from a popup into a 2-step process: https://github.com/nextcloud/server/issues/26691
