### ISSUE TITLE
hideDownload ignored in createShare

### ISSUE THREAD

**Issue by sodiumchl** [nextcloud/server#19484]
Nextcloud version 18.0
in file lib/private/Share20/Manager.php
692:	public function createShare(\OCP\Share\IShare $share)
$share->hideDownload is ignored.

To reproduce:
                $share = $this->shareManager->newShare();
                $share->setSharedBy($userId);
                $share->setNode($node);
                $share->setShareType(Share::SHARE_TYPE_LINK);
                $share->setHideDownload(true); //or 1 
                $this->shareManager->createShare($share);
The created share has hideDownload uncheck as seen in the GUI

**Comment by kesselb** [comment]
cc @rullzer

**Comment by sodiumchl** [comment]
This does not set hideDownload to true either:
                $check = $this->shareManager->getShareByToken($token);
                if (is_null($check)) return 'Error';
                $check->setHideDownload(true);
                return $token;

**Comment by sodiumchl** [comment]
And this does not set hide_download to 1  either:
curl -u ...  -H ... -d 'hide_download=1' -X PUT 'https://my.doma.in/ocs/v2.php/apps/files_sharing/api/v1/shares/<sid>'

**Comment by wiswedel** [comment]
Even if you set [oc_share].[hide_download] manually to ```1``` in the database, the checkbox stays unchecked and the download button remains visible and functional on the share.

**Comment by wiswedel** [comment]
This only applies to email shares. Link shares are working fine.

Reproduced with 18.0.1

**Comment by wiswedel** [comment]
cc @nextcloud/server-triage (security)

**Comment by skjnldsv** [comment]
> This only applies to email shares. Link shares are working fine.
> 
> Reproduced with 18.0.1

Most likely due to the merge of mail link shares and link shares

**Comment by rullzer** [comment]
Got it. PR incomming
