### ISSUE TITLE
let users host update mirrors with their NC

### ISSUE THREAD

**Issue by ITwrx** [nextcloud/server#19505]
**Is your feature request related to a problem? Please describe.**
My nextcloud is not showing any available updates for NC 18 even though it's been a month since 18.0 was released, i'm guessing because of the way that updates are rolled out in waves to keep NC update servers from being overloaded or running up bandwidth bills. I'm having to hold my whole server's php version back b/c of NC not supporting the latest php version in my current NC version. At least i think NC 17.0.3 doesn't support php 7.4.

**Describe the solution you'd like**
Have the option in NC for users to enable their NC server to be used as a official NC mirror and designate storage space, bandwidth and any other relevant resource limits. Then the latest releases should be downloaded and made available for download to others. Once this was implemented and rolled out, the current NC server could just be used for seeding the decentralized mirrors instead of directly for end users. Also, end users could query the main NC update server for the checksums and signing keys for verifying that the mirrors are serving unaltered data. Any failing servers should be disabled, etc. 

**Describe alternatives you've considered**
Waiting and being patient. :)

Thanks for your consideration.

**Comment by kesselb** [comment]
Alternatives:

1. Switch the updater channel to beta, do the upgrade to 18.0.1, switch the channel back to stable.
2. https://docs.nextcloud.com/server/18/admin_manual/maintenance/manual_upgrade.html

According to the [update server](https://github.com/nextcloud/updater_server/blob/e9daa84b87ea05792d6d0157cdb83a80df56a10b/config/config.php) 18.0.1 is not announced as update for 17.0.x instances. Probably will with 18.0.3 or earlier if the release managers collected enough data. Sounds like a nice idea but it's not about bandwidth hence I don't see (not yet) the need to distributed the packages.

**Comment by ITwrx** [comment]
ok, thanks for the alts info and feedback. I knew about 1 , but i couldn't remember if there were any drawbacks. I thought this FR might be a "nice to have later" or possibly even "never" item, but i figured i would post it anyways. :)

**Comment by ITwrx** [comment]
also, it's not very intuitive that a user sets it to stable and they are not notified of stable releases. 18.0.1 is a stable release, not a beta, so most would expect to be notified immediately, not counting any short term delays for load management. This is another reason why i didn't remember that switching to the beta channel temporarily would make this release available. This should be changed, IMHO.
