### ISSUE TITLE
Disable personal Calendar - use only group-calendars

### ISSUE THREAD

**Issue by demlak** [nextcloud/server#19507]
Hey.. is there any solution to manage caldav in this way, that users are not able to have own calendars, but only the calendars that an admin gave them/their group?

Background:
we want to use the nextcloud instance ONLY for colaborative use. users shuould not use it for personal use (same with files and so on)

**Comment by kesselb** [comment]
Please use https://help.nextcloud.com for questions.

**Comment by demlak** [comment]
ok. thx
