### ISSUE TITLE
continue" targeting switch is equivalent to "break

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#19504]
I use nextcloud 18.0.1 with calendar synchronization but lately my server goes downtime.  registering error:

continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? at /var/www/Franco/nx/apps/workflowengine/lib/Helper/LogContext.php#55

I have disabled app file access control.  but how to solve?

I have php 7.3

**Comment by juliushaertl** [comment]
PR at https://github.com/nextcloud/server/pull/19510
