### ISSUE TITLE
Users Page - Dropdown menu issue

### ISSUE THREAD

**Issue by ankurghai** [nextcloud/server#19503]
### Steps to reproduce
1. Goto users page.
2. Click on any user's storage quota dropdown.
3. The list comes beneath the info of other users so you cannot select options from dropdown menu.

### Expected behavior
Normally the list should allow selecting options from it.

### Actual behaviour
As the list is placed beneath the text of other user's information, it is not possible to select an option.

### Server configuration

**Operating system:** Ubuntu Server 18

**Web server:** Amazon EC2

**Database:** MySQL 5.7

**PHP version:** PHP 7.3

**Nextcloud version:** 18.0.1 Build:2020-02-15T23:01:50+00:00 e092141b6e03d35ccdc4b523b2ca99a775b79f93

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from : ** SNAP Repository

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

  'secret' => ,
  'trusted_domains' =>
  array (
    0 => ,
  ),
  'datadirectory' => '/var/snap/nextcloud/common/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '18.0.1.3',
  'overwrite.cli.url' => ,
  'dbname' => ,
  'dbhost' => 'localhost:/tmp/sockets/mysql.sock',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => ,
  'dbpassword' => ,
  'installed' => true,
  'app_install_overwrite' =>
  array (
    0 => 'admin_notifications',
    1 => 'dashboard',
    2 => 'printer',
  ),
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
    0 => 'admin',
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...  NO

**Are you using encryption:** yes/no   NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...   NO

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10 Professional

![error](https://user-images.githubusercontent.com/58544238/74603556-c5e61580-5108-11ea-8143-0a0e767deba4.png)

**Comment by StCyr** [comment]
same here on NC 18.0.1 RC2

**Comment by FelixBuehler** [comment]
Can confirm on NC 18.0.1. You can add the user to the group via `occ group:adduser [gid] [uid]` though.

**Comment by ChristophWurst** [comment]
Yes. This was only fixed for 19. The backport is pending: https://github.com/nextcloud/server/pull/19533

**Comment by rollanders** [comment]
I think this is dependent on the browser. I have the problems in Chrome and Edge but not in Firefox.
