### ISSUE TITLE
counterintuitive error message when password to share does not conform to policy

### ISSUE THREAD

**Issue by Ethendrel** [nextcloud/server#19525]
![nc2](https://user-images.githubusercontent.com/18167348/74721307-76eace00-5237-11ea-87e6-ab706c9f9fde.jpeg)

The error message shown when a password does not conform to the password policy set in the security settings should give a better hint to the problem than "Error updating the share". As of now it gives the impression of a general problem.

**Comment by Beeez** [comment]
I was extremely confused as well by this. There needs to be some better reporting based off this. Took me awhile to figure out what the error was because nothing was logged in regards to the password length. 

I recommend that we give better insight as to why a share failed to share when it hits password policies.

**Comment by kesselb** [comment]
cc @skjnldsv

**Comment by adsworth** [comment]
I just stumbled across this when sharing a folder with a password. That is very confusing.

**Comment by skjnldsv** [comment]
Hum, there is a tooltip on the password input too as far as I remember? :thinking:

**Comment by adsworth** [comment]
@skjnldsv I don't see any tooltip. If I click outside the popup, it hides and then reappears with the error message. Hovering the mouse pointer over the edit control also doesn't display a tooltip.

**Comment by skjnldsv** [comment]
Yep, there is supposed to be a tooltip on the input
https://github.com/nextcloud/server/blob/699cbeb2fcc0f6bbaa12234e965900a5b27d52d2/apps/files_sharing/src/components/SharingEntryLink.vue#L180

**Comment by skjnldsv** [comment]
Found the error
This is how it should behave
![Capture d’écran_2020-04-14_10-12-06](https://user-images.githubusercontent.com/14975046/79201611-a3d2f000-7e38-11ea-87d8-b42f0d25d1d3.png)

**Comment by adsworth** [comment]
Ahh, that looks better. :)

**Comment by skjnldsv** [comment]
fix in https://github.com/nextcloud/server/pull/20469

**Comment by adsworth** [comment]
@skjnldsv Thanks!
