### ISSUE TITLE
<noscript> version of "share via link"

### ISSUE THREAD

**Issue by heeplr** [nextcloud/server#19521]
When sharing a file or directory via link, the person opening the link needs to have javascript enabled to access the shared file/directory. Would it be possible to provide a \<noscript> version of the page?

Even a minimal version with missing features would be better than just getting the "This app requires javascript ..." dialog, when opening shared links in high-security environments or realms of paranoid sysadmins.
E.g. Password protected links could still show the error message.

**Comment by Bun-Bun** [comment]
I also would like this to be implemented for the same reasons as heeplr mentioned plus opening broader browser support along with just general debloating. The share page feels very heavy when sharing a simple file.

**Comment by Lartza** [comment]
Someone else on IRC voiced concerns about flat out blocking users without Javascript with no good reason. And I certainly myself don't disagree on being as lean and supportive as possible of all browsers even if the "major" browsers today do support every single feature. Not every user does at the very least for the reasons voiced in the original comment.

To add to that, at least the common functionalities of the sharing page do work without Javascript if you just block/remove the warning frame, and the original commit that made the pages require Javascript does not mention what exactly is broken.

Attached is a patch I was wasked to contribute that flat out disables the JS warning, but it might need to be combined with something that selectively disables whatever does not work without JS if someone can determine what that is.
[ieRo.txt](https://github.com/nextcloud/server/files/4561434/ieRo.txt)(GitHub does not allow .patch attachments)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
