### ISSUE TITLE
18.0.1: user mention in comment field is not working

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#19523]
### Steps to reproduce
1. open details of any file
2. click the comments tab
3. write @username in the field

### Expected behaviour
popup should show all the corresponding @usernames 

### Actual behaviour
Nothing happend, no popup

**Comment by roadrunnerjb** [comment]
Same here,

yesterday I've updated 4 of our 17.0.3 Instances to 18.0.1 and
**user autocompletion in comments does not work any more**. In the other 17.0.3 instances it still works. Any ideas or new config switch ?

When user inputs a correct username all is working as expected, when user inputs a wrong name, the comment is accepted but is prefixed with **Unknown User**

**Comment by roadrunnerjb** [comment]
Still not working with 18.03. any progress on this issue ?

**Comment by maxio-co** [comment]
Hi Team

we are seeing this issue specifically for us the issue is seen when commenting on a file using hte "files" app.

when mentioning a user in "Deck" and "calendar" comment section its working as expected.

Hope the above helps.

Please let us know if we can assist with further troubleshooting?

""Cheers
G

**Comment by jospoortvliet** [comment]
Also/still broken in 19.0.0. Note that if you know the user name and type @(username) and send the comment it will work. It is 'just' the popup that doesn't work.

### Server configuration
cloud.nextcloud.com
private cloud, also with Nc 19

**PHP version:**
7.2.x and whatever is on cloud.nc.c

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

#### Browser log
No errors that I can see, just deprecation warnings.

```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

  | $ | @ | comments.js:50
-- | -- | -- | --
  | get | @ | comments.js:50
  | _onTextChange | @ | comments.js?v=24847595-66:1
  | dispatch | @ | jquery.js:564
  | v.handle | @ | jquery.js:564

@blizzz you might be able to have a look...

**Comment by blizzz** [comment]
> @blizzz you might be able to have a look...

I am afraid i can confirm. No request is triggered, but there is not JS error either. Perhaps this is due to sidebar rework? @skjnldsv

**Comment by roadrunnerjb** [comment]
still not working in 20.x !

**Comment by skjnldsv** [comment]
@roadrunnerjb please use the github reactions.

**Comment by lolozere** [comment]
I confirm for nextcloud 20 (docker image nextcloud:20-apache). No error or warning in the log file. In the browser console, when I open the details info, I have a list of errors like : `XHR GET 404 https://cloud.soletic.org/ocs/v2.php/apps/user_status/api/v1/statuses/steffi` and when I try to mention, no new errors

**Comment by jakobroehrl** [comment]
Is solved with NC21

**Comment by roadrunnerjb** [comment]
First I thougt its solved with NC21. Selction works but we have users with special chars as "@" in their usernames. When I select one of those users the "@" inside the username is removed and so the user mention does not work
