### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by datorexpert** [nextcloud/server#19534]
### Steps to reproduce
1. Started upgrading from v18.0 to 18.0.1. When upgrading the database the error came up.
2.
3.

### Expected behaviour
Upgrade successful to v18.0.1

### Actual behaviour
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### Server configuration

**Operating system:**
Customized Linux OS from QNAP

**Web server:**
Apache

**Database:**
mySQL

**PHP version:**
7.3.7

**Nextcloud version:** (see Nextcloud admin page)
18.0.0 -> 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrading

**Where did you install Nextcloud from:**
18.0.0

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
<
Nextcloud
Uppdatera till 18.0.1

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Detaljerade loggar

Förbereder uppdatering

Sätter loggningsnivå till "debug"

Aktiverade underhållsläge

Reparationssteg: Repair MySQL collation

Reparationsinfo: Change row format for oc_addressbooks ...

Reparationsinfo: Change collation for oc_addressbooks ...

Reparationsinfo: Change row format for oc_authtoken ...

Reparationsinfo: Change collation for oc_authtoken ...

Reparationsinfo: Change row format for oc_calendarobjects ...

Reparationsinfo: Change collation for oc_calendarobjects ...

Reparationsinfo: Change row format for oc_calendars ...

Reparationsinfo: Change collation for oc_calendars ...

Reparationsinfo: Change row format for oc_calendarsubscriptions ...

Reparationsinfo: Change collation for oc_calendarsubscriptions ...

Reparationsinfo: Change row format for oc_dav_shares ...

Reparationsinfo: Change collation for oc_dav_shares ...

Reparationsinfo: Change row format for oc_ldap_group_mapping ...

Reparationsinfo: Change collation for oc_ldap_group_mapping ...

Reparationsinfo: Change row format for oc_ldap_group_members ...

Reparationsinfo: Change collation for oc_ldap_group_members ...

Reparationsinfo: Change row format for oc_ldap_user_mapping ...

Reparationsinfo: Change collation for oc_ldap_user_mapping ...

Reparationsinfo: Change row format for oc_login_flow_v2 ...

Reparationsinfo: Change collation for oc_login_flow_v2 ...

Reparationsinfo: Change row format for oc_migrations ...

Reparationsinfo: Change collation for oc_migrations ...

Reparationsinfo: Change row format for oc_mimetypes ...

Reparationsinfo: Change collation for oc_mimetypes ...

Reparationsinfo: Change row format for oc_systemtag_group ...

Reparationsinfo: Change collation for oc_systemtag_group ...

Reparationsinfo: Change row format for oc_trusted_servers ...

Reparationsinfo: Change collation for oc_trusted_servers ...

Reparationssteg: Repair SQLite autoincrement

Reparationssteg: Copy data from accounts table when migrating from ownCloud

Reparationssteg: Drop account terms table when migrating from ownCloud

Uppdaterar databasschema

Uppdaterade databasen

Letar efter uppdatering av appen "accessibility" i appbutiken

Letade efter uppdatering av appen "accessibility" i appbutiken

Letar efter uppdatering av appen "activity" i appbutiken

Letade efter uppdatering av appen "activity" i appbutiken

Letar efter uppdatering av appen "bruteforcesettings" i appbutiken

Letade efter uppdatering av appen "bruteforcesettings" i appbutiken

Letar efter uppdatering av appen "cloud_federation_api" i appbutiken

Letade efter uppdatering av appen "cloud_federation_api" i appbutiken

Letar efter uppdatering av appen "comments" i appbutiken

Letade efter uppdatering av appen "comments" i appbutiken

Letar efter uppdatering av appen "dav" i appbutiken

Letade efter uppdatering av appen "dav" i appbutiken

Letar efter uppdatering av appen "federatedfilesharing" i appbutiken

Letade efter uppdatering av appen "federatedfilesharing" i appbutiken

Letar efter uppdatering av appen "federation" i appbutiken

Letade efter uppdatering av appen "federation" i appbutiken

Letar efter uppdatering av appen "files" i appbutiken

Letade efter uppdatering av appen "files" i appbutiken

Letar efter uppdatering av appen "files_pdfviewer" i appbutiken

Letade efter uppdatering av appen "files_pdfviewer" i appbutiken

Letar efter uppdatering av appen "files_rightclick" i appbutiken

Letade efter uppdatering av appen "files_rightclick" i appbutiken

Letar efter uppdatering av appen "files_sharing" i appbutiken

Letade efter uppdatering av appen "files_sharing" i appbutiken

Letar efter uppdatering av appen "files_trashbin" i appbutiken

Letade efter uppdatering av appen "files_trashbin" i appbutiken

Letar efter uppdatering av appen "files_versions" i appbutiken

Letade efter uppdatering av appen "files_versions" i appbutiken

Letar efter uppdatering av appen "files_videoplayer" i appbutiken

Letade efter uppdatering av appen "files_videoplayer" i appbutiken

Letar efter uppdatering av appen "firstrunwizard" i appbutiken

Letade efter uppdatering av appen "firstrunwizard" i appbutiken

Letar efter uppdatering av appen "logreader" i appbutiken

Letade efter uppdatering av appen "logreader" i appbutiken

Letar efter uppdatering av appen "lookup_server_connector" i appbutiken

Letade efter uppdatering av appen "lookup_server_connector" i appbutiken

Letar efter uppdatering av appen "nextcloud_announcements" i appbutiken

Letade efter uppdatering av appen "nextcloud_announcements" i appbutiken

Letar efter uppdatering av appen "notifications" i appbutiken

Letade efter uppdatering av appen "notifications" i appbutiken

Letar efter uppdatering av appen "oauth2" i appbutiken

Letade efter uppdatering av appen "oauth2" i appbutiken

Letar efter uppdatering av appen "password_policy" i appbutiken

Letade efter uppdatering av appen "password_policy" i appbutiken

Letar efter uppdatering av appen "photos" i appbutiken

Letade efter uppdatering av appen "photos" i appbutiken

Letar efter uppdatering av appen "privacy" i appbutiken

Letade efter uppdatering av appen "privacy" i appbutiken

Letar efter uppdatering av appen "provisioning_api" i appbutiken

Letade efter uppdatering av appen "provisioning_api" i appbutiken

Letar efter uppdatering av appen "ransomware_protection" i appbutiken

Letade efter uppdatering av appen "ransomware_protection" i appbutiken

Letar efter uppdatering av appen "recommendations" i appbutiken

Letade efter uppdatering av appen "recommendations" i appbutiken

Letar efter uppdatering av appen "serverinfo" i appbutiken

Letade efter uppdatering av appen "serverinfo" i appbutiken

Letar efter uppdatering av appen "settings" i appbutiken

Letade efter uppdatering av appen "settings" i appbutiken

Letar efter uppdatering av appen "sharebymail" i appbutiken

Letade efter uppdatering av appen "sharebymail" i appbutiken

Letar efter uppdatering av appen "support" i appbutiken

Letade efter uppdatering av appen "support" i appbutiken

Letar efter uppdatering av appen "survey_client" i appbutiken

Letade efter uppdatering av appen "survey_client" i appbutiken

Letar efter uppdatering av appen "systemtags" i appbutiken

Letade efter uppdatering av appen "systemtags" i appbutiken

Letar efter uppdatering av appen "text" i appbutiken

Letade efter uppdatering av appen "text" i appbutiken

Letar efter uppdatering av appen "theming" i appbutiken

Letade efter uppdatering av appen "theming" i appbutiken

Letar efter uppdatering av appen "twofactor_backupcodes" i appbutiken

Letade efter uppdatering av appen "twofactor_backupcodes" i appbutiken

Letar efter uppdatering av appen "twofactor_totp" i appbutiken

Letade efter uppdatering av appen "twofactor_totp" i appbutiken

Letar efter uppdatering av appen "updatenotification" i appbutiken

Letade efter uppdatering av appen "updatenotification" i appbutiken

Letar efter uppdatering av appen "viewer" i appbutiken

Letade efter uppdatering av appen "viewer" i appbutiken

Letar efter uppdatering av appen "workflowengine" i appbutiken

Letade efter uppdatering av appen "workflowengine" i appbutiken

Reparationssteg: Repair MySQL collation

Reparationsinfo: Change row format for oc_addressbooks ...

Reparationsinfo: Change collation for oc_addressbooks ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Uppdateringen misslyckades. Vänligen rapportera felet till Nextcloud-gemenskapen.
>

**List of activated apps:**
N/A

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
<The current PHP memory limit is below the recommended value of 512MB.
Nextcloud or one of the apps require upgrade - only a limited number of commands                                                                                                                                                              are available
You may use your browser or the occ upgrade command to do the upgrade
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
[/share/Web/nextcloud] #>

**Nextcloud configuration:**
<The current PHP memory limit is below the recommended value of 512MB.
Nextcloud or one of the apps require upgrade - only a limited number of commands                                                                                                                                                              are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.10.177:44370",
            "nc.myddns.me:44370"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.0.10",
        "overwrite.cli.url": "https:\/\/192.168.10.177:44370",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "11"
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "core": {
            "default_encryption_module": "OC_DEFAULT_MODULE",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1581460473.91",
            "lastcron": "1582058971",
            "lastupdateResult": "{\"version\":\"18.0.1.3\",\"versionstring\":\"N                                                                                                                                                             extcloud 18.0.1\",\"url\":\"https:\\\/\\\/download.nextcloud.com\\\/server\\\/re                                                                                                                                                             leases\\\/nextcloud-18.0.1.zip\",\"web\":\"https:\\\/\\\/docs.nextcloud.com\\\/s                                                                                                                                                             erver\\\/18\\\/admin_manual\\\/maintenance\\\/upgrade.html\",\"changes\":\"https                                                                                                                                                             :\\\/\\\/updates.nextcloud.com\\\/changelog_server\\\/?version=18.0.1\",\"autoup                                                                                                                                                             dater\":\"1\",\"eol\":\"0\"}",
            "lastupdatedat": "1582057411",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "theming.variables": "b92d206521717ac032f8aa58d3c7ff2f",
            "updater.secret.created": "1582059070",
            "vendor": "nextcloud"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.14.0",
            "types": "filesystem"
        },
        "encryption": {
            "masterKeyId": "master_f01d9f12",
            "publicShareKeyId": "pubShare_f01d9f12",
            "recoveryKeyId": "recoveryKey_f01d9f12"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.10.1",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.3.0",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "readableLocation": "se",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "logging"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "text": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "logging"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "yes",
            "installed_version": "4.1.2",
            "types": ""
        },
        "updatenotification": {
            "core": "18.0.1.3",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "",
            "update_check_errors": "0"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}
>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
<<?php
$CONFIG = array (
  'instanceid' => 'oclfaydix7ap',
  'passwordsalt' => 'n/a',
  'secret' => 'n/a',
  'trusted_domains' => 
  array (
    0 => 'n/a',
    1 => 'n/a',
  ),
  'datadirectory' => '/share/CACHEDEV1_DATA/Web/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '18.0.0.10',
  'overwrite.cli.url' => 'n/a',
  'dbname' => 'n/a',
  'dbhost' => 'n/a',
  'dbport' => '',
  'dbtableprefix' => 'n/a',
  'dbuser' => 'n/a',
  'dbpassword' => 'n/a',
  'installed' => true,
  'maintenance' => false,
  'mysql.utf8mb4' => true,
  'updater.secret' => 'n/a',
  'theme' => '',
  'loglevel' => 2,
);
>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

```
</details>

### Client configuration
**Browser:**
Firefox 73

**Operating system:**
Windows 10 Home

### Logs
#### Web server error log
N/A

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
