### ISSUE TITLE
Sharedialog sub permission add can

### ISSUE THREAD

**Issue by hechi** [nextcloud/server#1953]
@jancborchardt would like to have all subshare option "edit, change, delete" which can. Because the user can do stuff and we have it in "can reshare"

![screenshot_20161029_155646](https://cloud.githubusercontent.com/assets/3808354/19830088/f3492518-9df0-11e6-9bdd-145068852883.png)

**Comment by hechi** [comment]
pull request here https://github.com/nextcloud/server/pull/1954

**Comment by jancborchardt** [comment]
Thanks a lot @hechi! :)
