### ISSUE TITLE
Filews webview empty, JS Errors OC.MimeType Undefined

### ISSUE THREAD

**Issue by liamdennehy** [nextcloud/server#19531]
### Steps to reproduce
* Open Nextcloud Files web application, 

### Expected behaviour
* Files web application is populated with files

### Actual behaviour
* Recently active files view on top only displays filename and "recently edited"
* Files list and grid views both remain empty

## Server configuration detail

**Operating system:** Linux 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.1.44

**PHP version:** 

7.2.24-0ubuntu0.18.04.2
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 17.0.3 - 17.0.3.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 16.0.8

**Where did you install Nextcloud from:** Official ZIP

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - apporder: 0.9.0
 - bookmarks: 2.3.4
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.8
 - dav: 1.13.0
 - deck: 0.8.0
 - federatedfilesharing: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - issuetemplate: 0.6.0
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - music: 0.13.0
 - nextcloud_announcements: 1.6.0
 - notes: 3.1.5
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - phonetrack: 0.6.2
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - sharerenamer: 2.7.3
 - spreed: 7.0.2
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - twofactor_totp: 4.1.2
 - updatenotification: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - admin_audit
 - encryption
 - federation
 - news
 - ocsms
 - user_ldap
 - weather

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/servername.domain.tld\/nextcloud",
    "dbtype": "mysql",
    "version": "17.0.3.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "php",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "logfile": "\/var\/lib\/nextcloud\/log\/nextcloud.log",
    "apps_paths": [
        {
            "path": "\/opt\/nextcloud\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/lib\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "theme": "",
    "maintenance": false,
    "trashbin_retention_obligation": "auto",
    "updatechecker": false,
    "mysql.utf8mb4": true,
    "logtimezone": "Europe\/Amsterdam",
    "log_type": "file",
    "updater.release.channel": "stable"
}
```
</details>

**Are you using external storage, if yes which one:** local (in turn server-mounted via NFS)

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** none

## Client configuration

**Browser:** Firefox 68 on Linux, Firefox on Windows, Chrome on Windows

**Operating system:** Linux & Windows

## Logs

<details><summary>Web server error log</summary>

```
Unknown which logs to add, but all content is either 3xx or 2xx, so no indications of mis-served files.
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"DCYBmqYGzWrIboKXcIEd","level":3,"time":"2020-02-18T16:35:17+01:00","remoteAddr":"95.96.203.8","user":"liam","app":"lib","method":"GET","url":"\/index.php\/apps\/files\/","message":"ResourceLocator can not find a web root (root: \/var\/lib\/nextcloud\/extra-apps\/spreed, file: index.php\/css\/spreed\/28d1-2374-merged-files.css?v=294a003c80a5fba8a1fa83f465494450, webRoot: , throw: true)","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:68.0) Gecko\/20100101 Firefox\/68.0","version":"17.0.3.1"}

Note: Disabling spreed does not affect this issue
```
</details>

<details><summary>Browser log</summary>

Firefox 68 Console log:

JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
TypeError: cannot declare global binding `initCore': property must be configurable or both writable and enumerable merged-template-prepend.js:1:1
oc_config is deprecated: use OC.config instead globals.js:26:15
oc_requesttoken is deprecated: use OC.requestToken instead 2 globals.js:26:15
Proxying an event bus of version 0.2.1 with 0.2.0 ProxyBus.js:30:14
OCA.Viewer initialized Viewer.js:37:10
New search handler registered search.js:67:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
Source map error: request failed with status 404
Resource URL: https://nextcloud.domain.tld/index.php/js/spreed/merged-files.js?v=ab7a4e38-4
Source Map URL: backbone.marionette.min.js.map
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:26:15
Source map error: request failed with status 404
Resource URL: https://nextcloud.domain.tld/extra-apps/spreed/js/collections.js?v=ab7a4e38-4
Source Map URL: collections.js.map
Unhandled promise rejection TypeError: "OC.MimeType is undefined"
    _getIconUrl merged-index.js:5995
    _createRow merged-index.js:6008
    _createRow merged-index.js:9001
    _createRow filesplugin.js:72
    _createRow share.js:46
    _renderRow merged-index.js:6377
    _nextPage merged-index.js:5871
    setFiles merged-index.js:5949
    reloadCallback merged-index.js:6682
    jQuery 4
    getFolderContents client.js:495
    s es6.promise.js:75
    H es6.promise.js:92
    u _microtask.js:18
es6.promise.js:110:18
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
    VueJS 24
TypeError: "OC.MimeType is undefined"
    data RecommendedFile.vue:84
    VueJS 21
vue.runtime.esm.js:1888
</details>

**Comment by liamdennehy** [comment]
Upgraded to 18.0.1, so cannot provide any further troubleshooting with this issue. Issue is no longer occurring in v18.

**Comment by brakhane** [comment]
*Sorry for reviving this old report, but it's one of the top search results for this error, so I hope it might be useful for someone stumbling upon the same issue*

I've had the same issue occurring on NC 29, and according to forum posts it seems to happen now and then with other versions as well.

What I've found is that running `occ files:scan-app-data` seems to solve this problem.
