### ISSUE TITLE
No translation in "Security"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#19547]
No translation of the description in "Security":

- Two-factor authentication can be enforced for all users and specific groups. If they do not have a two-factor provider configured, they will be unable to log into the system. 

There is a translation in Transifex.

![obraz](https://user-images.githubusercontent.com/47037905/74841099-623a3300-5328-11ea-8d32-57e606b0bd28.png)

Steps:

1.  Enter the settings.
2. Select "Security" for the administrator.

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Comment by sndrr** [comment]
Translation can be found in the file `settings/l10n/<locale>.js`. Not reproducible in NC 17.0.3.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/commit/6a82bb1f00a5dbfb5be4eb8eaa921e806e384f6a#diff-64b4b6508dd2e45b5f587069910cf764

Translation for this string was added at 2020-02-08 so this should be shipped with 18.0.2.

**Comment by Valdnet** [comment]
@kesselb The translation appears in l10n files for version 18.0.1, but is still not displayed in "Security".

- The translation was downloaded from Transifex in 2020-02-07.
- Nextcloud 18.0.1 release was in 2020-02-12.

The problem with the lack of translations is probably somewhere else.

**Comment by kesselb** [comment]
Good catch :+1: 

cc @rullzer @juliushaertl

**Comment by kesselb** [comment]
Found it ;) There are some tab characters.

**Comment by kesselb** [comment]
Fix in #19586 (master) and #19612 (stable18).
