### ISSUE TITLE
"always ask for password" leads to set password, but not visible to user

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#19543]
- enable as admin "always ask for password"
- as user create a share link
- now link is protected with an unknown password, but even more worse it is not shown at all that the link is password protected
- the user has to click on "three dots" to open the popup and see that password is set with an unknown password
- now they have to toggle off/on to see the password

![image](https://user-images.githubusercontent.com/5836855/74838909-adeadd80-5324-11ea-8457-7e12af407777.png)

**Comment by GretaD** [comment]
isnt this fixed by this PR: https://github.com/nextcloud/server/pull/19542?

**Comment by tobiasKaminsky** [comment]
No, #19542 shows the password field, but with hidden chars as seen above.
As the user creates the link for first time, the password needs to be shown once.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
