### ISSUE TITLE
Activity notification 'downloaded via public link' should show the link

### ISSUE THREAD

**Issue by Solaner** [nextcloud/server#19559]
**Problem:**
The activity notification for downloaded files via public links does not say which link was used.
The activity notification only says “{file} downloaded via public link”.
It’s possible to add multiple links to a file or folder (Share link / Add another link).
For what purpose should I create multiple links, if the activity reports are the same for each link?
Perhaps there are other benefits of using multiple links that I don't see.

**The solution I'd like**
The activity notification should say something like “{file} downloaded via public link {share-link}”.

**My current workaround:**
To achieve something similar I wanted, I created a hundred mount points for the same share, which is on a NAS (accessible with something like _//192.168.1.20/FolderToShare_).

1. I created the folders for the mount points:
```
mkdir /mnt/SomeFolder/000001
mkdir /mnt/SomeFolder/000002
...
mkdir /mnt/SomeFolder/000100
```
2. I modified _/etc/fstab_ in order to mount the shares
```
//192.168.1.20/FolderToShare /mnt/SomeFolder/000001 cifs credentials=/home/pi/.smbcredentials 0 0
//192.168.1.20/FolderToShare /mnt/SomeFolder/000002 cifs credentials=/home/pi/.smbcredentials 0 0
…
//192.168.1.20/FolderToShare /mnt/SomeFolder/000100 cifs credentials=/home/pi/.smbcredentials 0 0
```
3. In nextcloud I added the external share _/mnt/SomeFolder_
-> In the Files View I see the folders _SomeFolder/000xyz/FolderToShare_

4. When I need to share my _FolderToShare_ I create a link to one of the hundred _SomeFolder/000xyz/FolderToShare_.
-> The user who gets the link does not see which mount point he is using. His top level folder is _FolderToShare_.

5. When the user has downloaded something, I get an email notification like:
_SomeFolder/000xyz/FolderToShare/SomeFileToShare.pdf_ downloaded via public link.

**My request:**
My workaround is the only way I found to implement something similar what I wanted.
The workaround is very ugly.
If there already exists a better solution which I have overseen please tell me.
Otherwise please implement the desired feature which in my opinion is necessary.

**Comment by szaimen** [comment]
cc @nextcloud/designers is this something we should do and implement as suggested?
