### ISSUE TITLE
Nextcloud Security Check API

### ISSUE THREAD

**Issue by maschhoff** [nextcloud/server#19552]
Hello nextcloud Team,

Is your security check API an open API?
I have setup a Python scheduled Client that will send me a notification If there are issues.
Before I Upload IT to github I would like to have your permission to access your API.
Its an open source GPL v3 Python Client.

Thanks

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure

**Comment by szaimen** [comment]
cc @nextcloud/infrastructure

**Comment by LukasReschke** [comment]
I don't think we can commit on our API being stable.
