### ISSUE TITLE
Transfers to external drive write to SD card first on RPi

### ISSUE THREAD

**Issue by thisaccountname** [nextcloud/server#19550]
### Steps to reproduce
1. Create an auto-sync folder on Windows, ensure destination folder on NC is inside external drive.
2. Place 1G file into folder, transfer to NC begins
3. Monitor storage devices. Notice SD card's used space increases until entirely downloaded, where the file is then moved to external drive. 

### Expected behavior
I am selecting my external drive when I create this sync folder, I would like to spare my SD card's life and skip this middle-man behavior. 

### Actual behavior
Uploads are saving to SD card and THEN transferring to external drive.

### Server configuration
RPi 4 (4g) running Raspbian Buster. 

**Operating system:**
I've witnessed this issue when using a Windows 10 client, but I can imagine it would behave the same way from my android sync-folders as well. 

**Web server:**
Apache2, it's a pretty vanilla installation. 

**Database:**
MariaDB/Mysql

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud v18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Pulled directly from nextcloud servers

**Are you using external storage, if yes which one:** local/smb/sftp/...
Local

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by juliushaertl** [comment]
This seems to be a setup issue as this depends on how you have integrated the external drive into your Nextcloud so I would like to ask you to raise your question in the forums: https://help.nextcloud.com

A quick hint would be to check the tempdirectory setting in your config.php. Maybe your operating system
