### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by thimberwolf** [nextcloud/server#19551]
I receive this: 
Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `o`.`id` FROM `oc_flow_operations` `o` LEFT JOIN `oc_flow_operations_scope` `s` ON `o`.`id` = `s`.`operation_id` WHERE `s`.`operation_id` IS NULL': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'd02e7e71.oc_flow_operations_scope' doesn't exist

Do you have an idea ?

**Comment by kesselb** [comment]
Please use the search. There are some reports with solution around.

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/18265
