### ISSUE TITLE
Dropdown in User-menu broken.

### ISSUE THREAD

**Issue by ConnerK96** [nextcloud/server#19560]
When you enter the User menu to add a User to a group the dropdown does not work. This refers to the fields under "Group" and "Group admin for" when you hit the edit button.
It seems to get lost behind the other content. Therefore you cannot pick a group. 

It was great if you could fix this issue. Should be an easy one if you know where to look for it. Thanks :)

**Comment by GretaD** [comment]
Hello @ConnerK96, thank you for your bug report, this issue is fixed here: https://github.com/nextcloud/server/pull/19533#event-3048940620
