### ISSUE TITLE
No visual feedback while backup codes are generated

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#19564]
### Steps to reproduce
1. Run Nextcloud on a slow / embedded device.
2. Generate backup codes for the two-factor authentication.

### Expected behaviour
A spinner / some visual feedback should be shown while the codes are generated on the server.

### Actual behaviour
No feedback is visible until some time later the codes are being shown. This might cause users to think the generation did not work so they click the button again (causing even more load on the device).

### Server configuration

This is an ODROID C1 running Nextcloud 18.0.0 on Ubuntu 18.04 with php-fpm 7.2.24 and MariaDB 10.1.44 from the official repository.

**Comment by kesselb** [comment]
At least the button should be disabled. But your device has definitely not enough power to run Nextcloud.

**Comment by fancycode** [comment]
> But your device has definitely not enough power to run Nextcloud.

No, Nextcloud itself is running perfectly fine.
