### ISSUE TITLE
Streaming large videos via Browser

### ISSUE THREAD

**Issue by DocKDE** [nextcloud/server#19563]
Hi,
I just noticed that the webinterface won't play videos with a file size larger than 2GB. Anything just below is no problem. This seems to be some sort of arbitrary limit I should be able to change somewhere in the config, does anyone, perchance know about it?

### Steps to reproduce
1. Log in to Nextcloud in Browser
2. Try to open a Video larger than 2 GB

### Expected behaviour
Start to play Video in Browser

### Actual behaviour
Loading Error 

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

If any logs are required I think I can dig them up.
Thanks!

**Comment by kesselb** [comment]
Would you mind to ask the question at https://help.nextcloud.com first? Also on GitHub are already some reports about playing videos. The issue template is there to make reproducing issues possible. If you left out some information (for example what response does your browser get when trying to play that video) it's quite hard to reproduce a problem.
