### ISSUE TITLE
Need a way to get icon in primary text color

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19565]
As an app we want to have icons on primary color buttons.
For this we use `$color-primary-text` because we want it to be independent from the text color, because the text color in the button can be different from normal text color. So the following sounds like the solution:
```scss
	.icon-incoming-call {
		@include icon-color('video', 'actions', $color-primary-text, 1, true);
	}
```

However, `$color-primary-text` is white or black, and therefor 
https://github.com/nextcloud/server/blob/521b2dd61572202519c2a2ee8b1bac71c42e0c2a/core/css/functions.scss#L70-L74

will use `--icon-video-fff`  in case of default nextcloud blue, that is still okay.
But if you now enable dark-mode `--icon-video-fff` requests the image `?color=000` because:
https://github.com/nextcloud/server/blob/30d985b639b2def47ace858e00c1bb6a44e9d682/apps/accessibility/lib/Controller/AccessibilityController.php#L281-L297
Doesn't know anymore that `fff` is because of `$color-primary-text` :crying_cat_face: 

Any clever idea around this? cc @skjnldsv @juliushaertl

**Comment by skjnldsv** [comment]
Use svg icons inline or icons as font? and use color: var(--color-primary-text)
This is where we want to go in the end, icons classes are too messy.

**Comment by nickvergessen** [comment]
> This is where we want to go in the end, icons classes are too messy.

Sorry I'm just a backend dev in need of a icon in the color I tell you. So for now we get a wrong icon color in Talk dark mode, fine by me.

**Comment by nickvergessen** [comment]
Onlyoffice has the same issue:
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/247

**Comment by mat-m** [comment]
Mail app also has Inbox icon in black, but others (Favorites, Drafts, Sente, Archive, Junk) in white in Dark mode.

**Comment by mat-m** [comment]
Mail has the same issue.
Inbox and Trash icons are black with Dark Theme from Accessibility.

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/spreed/pull/3398/commits/6ddb58f2da7c9f5730f8929c0010c357336f3e52 seems to work as an intermediate workaround.

**Comment by blizzz** [comment]
clearing the milestone

**Comment by juliushaertl** [comment]
Is that actually needed now that more apps are switching to use vue material icons that embed SVG which can dynamically be adjusted in color? I'd say we can close this.

**Comment by nickvergessen** [comment]
Still relevant for app icons with situations like the header bar or login page (e.g. registration app), but yeah less urgent

**Comment by skjnldsv** [comment]
Do I get this right? You want an icon to have a fitting colour over a primary colour?
Like if it's too bright -> dark and if it's too dark -> bright ?

if so #31751 tackles that in a way

**Comment by nickvergessen** [comment]
Yes exactly

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/issues/32060

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by nickvergessen** [comment]
Still an issue atm, but we are all migrating away to inline SVGs, so it's hopefully solved soon.
