### ISSUE TITLE
Autoscan/repair/check appdata folder / Make it robust

### ISSUE THREAD

**Issue by paskalito** [nextcloud/server#19579]
**Is your feature request related to a problem? Please describe.**
When the appdata folder is broken, the whole Webui of the installation breaks (internal server error) - without any reasonable message/hint/errormessage **anywhere**

**Describe the solution you'd like**
introduce some sanitycheck and or autorepair of that folder.
- on the updater!
- on occ repair command !
- even on cronjobs - or wherever it makes sense

**Describe alternatives you've considered**
- at least drop some error message into the errorfiles of the server. 
- or display one in the webui
- rearrange everything in a way that that **data** folder cannot completely break the webui.

**Additional context**
feel free to follow my story here:
https://help.nextcloud.com/t/very-presistent-internal-server-error/67725/3

**Comment by szaimen** [comment]
I don't think that we will be able to fix non existing appdata folders based on the current architecture but better hinting might be doable.
cc @nextcloud/server-triage for mor input on this.

**Comment by skjnldsv** [comment]
Yeah, the question would be why the folder has gone missing out of nowhere.
For me this is the real issue and should be addressed.
