### ISSUE TITLE
CSS not applying to third app button

### ISSUE THREAD

**Issue by Ecphrasis** [nextcloud/server#19571]
Hi all,
I have installed an app for CAS login : https://apps.nextcloud.com/apps/user_cas
But, since the version 18 (I am currently in 18.0.1, all apps updated), CSS doesn't apply to this button.
![Sans titre](https://user-images.githubusercontent.com/11899009/75022325-31780c00-5496-11ea-8ef0-06eb49dbce26.png)
Is there a way to fix this ?
Thanks !

**Comment by georgehrke** [comment]
Please report this to the developer of https://apps.nextcloud.com/apps/user_cas

It seems they are applying their own styles.

**Comment by georgehrke** [comment]
If you want to "fix" it yourself, you can use the [custom css app](https://apps.nextcloud.com/apps/theming_customcss) to add your own styles.
