### ISSUE TITLE
Remove federated link at folder share => Error msg

### ISSUE THREAD

**Issue by arbeitsgreiss** [nextcloud/server#19570]
### Steps to reproduce
1. Add federated link to another NC at a folder (e.g. user@url.de@cloud.adress.de)
2. Try to unshare the federated link again

### Expected behaviour
share should be removed

### Actual behaviour
share still exists and error message appears:
"Error removing share
Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services."

### Server configuration

**Operating system:**
**Web server:**
**Database:**
^^ NC hosted by provider - didn't find information

**PHP version:**
7.1.33

**Nextcloud version:** (see Nextcloud admin page)
17.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated a few times until current version

**Where did you install Nextcloud from:**
was installed by provider

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
"No errors have been found."

**List of activated apps:**
Accessibility
Activity
Collaborative tags
Comments
Deleted files
Federation
File sharing
First run wizard
Gallery
Log Reader
Monitoring
Nextcloud announcements
Notifications
Password policy
PDF viewer
Privacy
Recommendations
Right click
Share by mail
Support
Text
Theming
Update notification
Usage survey
Versions
Video player
Viewer

**Nextcloud configuration:**
 
<?php
$CONFIG = array (
  'instanceid' => '-- removed --',
  'passwordsalt' => '-- removed --/-- removed --',
  'secret' => '-- removed --//-- removed --',
  'trusted_domains' => 
  array (
    0 => '-- removed --.-- removed --.de',
  ),
  'datadirectory' => '/var/www/vhosts/-- removed --.-- removed --.de/httpdocs/data',
  'dbtype' => 'mysql',
  'version' => '17.0.3.1',
  'overwrite.cli.url' => 'https://-- removed --.-- removed --.de',
  'dbname' => '-- removed --',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '-- removed --_u',
  'dbpassword' => '-- removed --',
  'installed' => true,
  'mysql.utf8mb4' => true,
  'maintenance' => false,
  'memcache.distributed' => '\\OC\\Memcache\\APCu',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'theme' => '',
  'loglevel' => 2,
);

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Tested with FF / Chrome => Same result

**Operating system:**
Win 10

**Comment by juliushaertl** [comment]
Could you check your nextcloud log if there is an entry related to the unshare action?

**Comment by arbeitsgreiss** [comment]
Sorry, yesterday evening I was to blind to find the log ;-)

Independently from the error I see a lot of messages of this kind:
```
[PHP] Error: Zend OPcache can't be temporary enabled (it may be only disabled till the end of request) at Unknown#0

GET /index.php/js/core/merged-template-prepend.js?v=70a0afb8-6
```


At the time of the unshare action this message appears:

```
[no app in context] Error: OC\HintException: Invalid Federated Cloud ID at <<closure>>

 0. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/apps/federatedfilesharing/lib/FederatedShareProvider.php line 574
    OCA\FederatedFileSharing\AddressHandler->splitUserRemote("Andi")
 1. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/apps/federatedfilesharing/lib/FederatedShareProvider.php line 544
    OCA\FederatedFileSharing\FederatedShareProvider->revokeShare(OC\Share20\Share {}, true)
 2. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/lib/private/Share20/Manager.php line 1003
    OCA\FederatedFileSharing\FederatedShareProvider->delete(OC\Share20\Share {})
 3. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/apps/files_sharing/lib/Controller/ShareAPIController.php line 351
    OC\Share20\Manager->deleteShare(OC\Share20\Share {})
 4. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Files_Sharing\Controller\ShareAPIController->deleteShare("77")
 5. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sharin ... {}, "deleteShare")
 6. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sharin ... {}, "deleteShare")
 7. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Files_Shar ... r", "deleteShare", OC\AppFramework\ ... {}, {id: "77",_route ... "})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({id: "77",_route ... "})
 9. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {id: "77",_route ... "})
10. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/ocs/v1.php line 82
    OC\Route\Router->match("/ocsapp/apps/fi ... 7")
11. /var/www/vhosts/***subdomain***.***domain***.de/httpdocs/ocs/v2.php line 24
    undefinedundefinedrequire_once("/var/www/vhosts ... p")

DELETE /ocs/v2.php/apps/files_sharing/api/v1/shares/77?format=json
from *** IP *** by Andi at 2020-02-21T14:15:59+00:00
```

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
