### ISSUE TITLE
Nextcloud not compatible with PHP 7.1.

### ISSUE THREAD

**Issue by YorozuyaDev** [nextcloud/server#19583]
### Steps to reproduce
I have installed nextcloud on my raspberry pi server:
1. Install apache2
2. Install php7.3 php7.3-gd sqlite php7.3-sqlite3 php7.3-curl php7.3-zip php7.3-xml php7.3-mbstring
3. Restart apache2
4. cd /var/www/html
5. curl https://download.nextcloud.com/server/releases/nextcloud-16.0.3.tar.bz2 | sudo tar -jxv
6. sudo mkdir -p /var/www/html/nextcloud/data
7. sudo chown -R www-data:www-data /var/www/html/nextcloud/
8. sudo chmod 750 /var/www/html/nextcloud/data
### Expected behaviour
Nextcloud login screen should appears.
### Actual behaviour
Following message appear in the browser
```
This version of Nextcloud is not compatible with PHP 7.1.
You are currently running 7.3.14-1~deb10u1.
```
### Server configuration

**Operating system:** GNU/Linux Raspbian lite 4.19..97-v7
**PHP version:** PHP 7.3.14-1~deb10u1 
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Comment by Dennis1993** [comment]
Why you are downloading an old version? For NextCloud 16 PHP 7.2 is recommended. Install the latest release 18.0.1 please and you don‘t have any problems. NextCloud 18.0.1 is ready for PHP 7.4 ✌🏼

**Comment by j-ed** [comment]
> This version of Nextcloud is not compatible with PHP 7.1.
You are currently running 7.3.14-1~deb10u1.

I don't know from where you've download the archive file or from which version you've taken that message from, but I think you're referring to a file which isn't part of the official package. The only location where the PHP check is done and such kind of message is printed, can be found in the file `lib/versioncheck.php`. If you download the Nextcloud 16.0.3 archive file and check the mentioned file you will see that this message doesn't exists in it:
```
<?php

// Show warning if a PHP version below 7.1 is used,
if (version_compare(PHP_VERSION, '7.1') === -1) {
        http_response_code(500);
        echo 'This version of Nextcloud requires at least PHP 7.1<br/>';
        echo 'You are currently running ' . PHP_VERSION . '. Please update your PHP version.';
        exit(-1);
}

// Show warning if > PHP 7.3 is used as Nextcloud is not compatible with > PHP 7.3 for now
if (version_compare(PHP_VERSION, '7.4.0') !== -1) {
        http_response_code(500);
        echo 'This version of Nextcloud is not compatible with > PHP 7.3.<br/>';
        echo 'You are currently running ' . PHP_VERSION . '.';
        exit(-1);
}
```
As @Dennis1993 already recommended, you should use an up-to-date version, the mentioned one 16.0.3 is from 07/2019 and even for that branch a 16.0.8 already exists. Better would be to directly install the latest version **18.0.1**!

**Comment by YorozuyaDev** [comment]
I have installed nextcloud 18.0.1 curl https://download.nextcloud.com/server/releases/nextcloud-18.0.1.tar.bz2 | sudo tar -jxv with same behaviour

**Comment by j-ed** [comment]
As I already, wrote this is impossible because the included archive doesn't include a message referring to PHP 7.1. I assume that you're not extracting the package to a clean directory or and old version is cached somewhere. 

https://github.com/nextcloud/server/blob/d3f2bda90cc68fcaf4e66465d1f684841ffad863/lib/versioncheck.php#L36
