### ISSUE TITLE
Certificate problem with mail server

### ISSUE THREAD

**Issue by CyberMew** [nextcloud/server#19581]
I am using dreamhost email (I have my own domain and hosting with them). I am using letsencrypt and nextcloud docker as well, so nextcloud.mydomain.com works fine. There are no issues in admin overview.

I am getting this while trying to set the email admin setting on NextCloud 18.0.0:

A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host smtp.dreamhost.com :stream_socket_client(): SSL operation failed with code 1. OpenSSL Error messages: error:1408F10B:SSL routines:ssl3_get_record:wrong version number

Any idea why is that the case and how to solve it? The nearest I got was https://help.nextcloud.com/t/additional-settings-email-configuration-solved/22070/4 but mine is not a self-signed certificate.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

Nextcloud uses Swift Mailer (6.2.3 with Nextcloud 18) to send emails. The above message is the response from Swift Mailer and the underlying system. Nextcloud is not able to fix any of those errors. It seems related to (probably outdated) certificates.

**Comment by CyberMew** [comment]
Dreamhost and my website definitely don't have outdated certificates.

Turns out instead of SSL/TLS, I should select STARTTLS instead. Works fine now. Anyway the documentation for the email settings is a little outdated.

**Comment by kesselb** [comment]
Mind to use the "Edit on GitHub" on https://docs.nextcloud.com/server/18/admin_manual/configuration_server/email_configuration.html to suggest a fix for the outdated information?
