### ISSUE TITLE
Cannot use gmail smtp server "unable to connect to tcp://smtp.gmail.com:587 (Operation timed out) (code: 0)"

### ISSUE THREAD

**Issue by plozachm** [nextcloud/server#19582]
### Steps to reproduce
1. Configure gmail smtp server smtp.gmail.com with STARTTLS on port 587
2. Send test mail

![image](https://user-images.githubusercontent.com/16304323/75090839-538d8f00-5567-11ea-979d-446d5320a7d5.png)

### Expected behaviour
Test mail should be sent

### Actual behaviour
Error with message:
`A problem occurred while sending the email. Please revise your settings. (Error: Connection could not be established with host smtp.gmail.com :stream_socket_client(): unable to connect to tcp://smtp.gmail.com:587 (Operation timed out) Log data: ++ Starting Swift_SmtpTransport !! Connection could not be established with host smtp.gmail.com :stream_socket_client(): unable to connect to tcp://smtp.gmail.com:587 (Operation timed out) (code: 0))`

### Server configuration

**Operating system:**
Linuxserver version: Docker version 19.03.6 on Linux Ubuntu 19.10 (64 bits)

**Web server:**
Nginx 1.16.1

**Database:**
MySQL 8

**PHP version:**
PHP 7.3.14 (cli) (built: Jan 27 2020 21:40:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
18.0.1 stable

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Linuxserver

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - breezedark: 18.0.6
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.5
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_antivirus
  - files_external
  - ransomware_protection
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "****.duckdns.org:443"
        ],
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "https:\/\/****.duckdns.org:443",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "maintenance": false,
        "mail_smtpdebug": true,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** none

### Client configuration
**Browser:**
Latest chrome

**Operating system:**
MacOS

**Comment by j-ed** [comment]
Due to the fact that this is the development bug tracker and not the help forum, I would recommend to check the existing solutions for your problem first, which you might find here:

https://help.nextcloud.com/search?q=Cannot%20use%20gmail%20smtp%20server

**Comment by plozachm** [comment]
I already checked and could not fix the problem with any of the suggestion.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem +1

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

Nextcloud uses Swift Mailer (6.2.3 with Nextcloud 18) to send emails. The above message is the response from Swift Mailer and the underlying system. `Operation timed out` means Nextcloud (Swift Mailer to be precise) is not able to establish a connection to the smtp server. Please make sure your server is able to connect to the smtp server.
