### ISSUE TITLE
Call to undefined method OCA\\Maps\\Service\\PhotofilesService::safeDeleteByFolderIdUserId()

### ISSUE THREAD

**Issue by dgedgedge** [nextcloud/server#19608]
### Steps to reproduce
1. From a user X share a directory DD to a Y user.
2. In the directory DD there is music.
3. In the user X and Y do indexing of the music in DD with module Music.
4. Reset database of Y
5. Ask for unsharing the directory.

### Expected behaviour
The directory is not shared.

### Actual behaviour
Show error : Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. 

Error: 

### Server configuration

**Operating system:**
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster

Operating system: Linux 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1 (2020-01-26) x86_64

Webserver: Apache (apache2handler)

Database: mysql 10.3.22

PHP version: 7.3.14-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, intl, json, exif, msgpack, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, memcached, Zend OPcache

Nextcloud version: 17.0.3 - 17.0.3.1

Updated from an older Nextcloud install.

Where did you install Nextcloud from: Manual, nextcloud zip.

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.3.0
 - activity: 2.10.1
 - admin_audit: 1.7.0
 - analytics: 2.0.0
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.1
 - checksum: 0.4.4
 - cloud_federation_api: 1.0.0
 - comments: 1.7.0
 - contacts: 3.1.8
 - cookbook: 0.5.7
 - dav: 1.13.0
 - deck: 0.8.0
 - federatedfilesharing: 1.7.0
 - federation: 1.7.0
 - files: 1.12.0
 - files_external: 1.8.0
 - files_markdown: 2.2.0
 - files_mindmap: 0.0.17
 - files_pdfviewer: 1.6.0
 - files_rightclick: 0.15.1
 - files_sharing: 1.9.0
 - files_trashbin: 1.7.0
 - files_versions: 1.10.0
 - files_videoplayer: 1.6.0
 - firstrunwizard: 2.6.0
 - gallery: 18.4.0
 - geoblocker: 0.1.0
 - keeweb: 0.6.2
 - logreader: 2.2.0
 - lookup_server_connector: 1.5.0
 - maps: 0.1.5
 - music: 0.13.0
 - nextcloud_announcements: 1.6.0
 - notes: 3.1.5
 - notifications: 2.5.0
 - oauth2: 1.5.0
 - password_policy: 1.7.0
 - privacy: 1.1.0
 - provisioning_api: 1.7.0
 - recommendations: 0.5.0
 - serverinfo: 1.7.0
 - sharebymail: 1.7.0
 - spreed: 7.0.2
 - support: 1.0.1
 - survey_client: 1.5.0
 - systemtags: 1.7.0
 - tasks: 0.11.3
 - text: 1.1.1
 - theming: 1.8.0
 - twofactor_backupcodes: 1.6.0
 - updatenotification: 1.7.0
 - user_usage_report: 1.1.2
 - viewer: 1.2.0
 - workflowengine: 1.7.0
Disabled:
 - encryption
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "owncloud.fager.fr",
        "192.168.202.110",
        "89.156.195.207"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/owncloud.fager.fr",
    "dbtype": "mysql",
    "version": "17.0.3.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "logtimezone": "Europe\/Paris",
    "logfile": "\/var\/log\/nextcloud.log",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "updater.release.channel": "stable",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mysql.utf8mb4": true,
    "trashbin_retention_obligation": "auto, 100"
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured

</details>

Encryption: no

User-backends:

OC\User\Database

**Signing status:**

<details>
<summary>Signing status</summary>

</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

{"reqId":"507TeWfsKDixGFmO9p7g","level":3,"time":"2020-02-23T13:22:11+01:00","remoteAddr":"89.156.39.124","user":"musicfamger","app":"no app in context","method":"DELETE","url":"/ocs/v2.php/apps/files_sharing/api/v1/shares/257?format=json","message":{"Exception":"Exception","Message":"Call to undefined method OCA\\Maps\\Service\\PhotofilesService::safeDeleteByFolderIdUserId()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"deleteShare"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","deleteShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"257","_route":"ocs.files_sharing.ShareAPI.deleteShare"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"257","_route":"ocs.files_sharing.ShareAPI.deleteShare"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"257","_route":"ocs.files_sharing.ShareAPI.deleteShare"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/shares/257"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":109,"Previous":{"Exception":"Error","Message":"Call to undefined method OCA\\Maps\\Service\\PhotofilesService::safeDeleteByFolderIdUserId()","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/hook.php","line":106,"function":"preUnShare","class":"OCA\\Maps\\Hooks\\FileHooks","type":"->","args":[{"id":"257","itemType":"folder","itemSource":440063,"shareType":0,"shareWith":"denis","itemparent":null,"uidOwner":"musicfamger","fileSource":440063,"fileTarget":"/musicfamger"}]},{"file":"/var/www/nextcloud/lib/private/Share20/LegacyHooks.php","line":62,"function":"emit","class":"OC_Hook","type":"::","args":["OCP\\Share","pre_unshare",{"id":"257","itemType":"folder","itemSource":440063,"shareType":0,"shareWith":"denis","itemparent":null,"uidOwner":"musicfamger","fileSource":440063,"fileTarget":"/musicfamger"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":212,"function":"preUnshare","class":"OC\\Share20\\LegacyHooks","type":"->","args":[{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"},"OCP\\Share::preUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":44,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[["OCA\\Activity\\FilesHooksStatic","unShare"],[{"__class__":"OC\\Share20\\LegacyHooks"},"preUnshare"]],"OCP\\Share::preUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":59,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Share::preUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":996,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["OCP\\Share::preUnshare",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/var/www/nextcloud/apps/files_sharing/lib/Controller/ShareAPIController.php","line":351,"function":"deleteShare","class":"OC\\Share20\\Manager","type":"->","args":[{"__class__":"OC\\Share20\\Share"}]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"deleteShare","class":"OCA\\Files_Sharing\\Controller\\ShareAPIController","type":"->","args":["257"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":99,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"deleteShare"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":126,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Files_Sharing\\Controller\\ShareAPIController"},"deleteShare"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Files_Sharing\\Controller\\ShareAPIController","deleteShare",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"id":"257","_route":"ocs.files_sharing.ShareAPI.deleteShare"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"id":"257","_route":"ocs.files_sharing.ShareAPI.deleteShare"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"id":"257","_route":"ocs.files_sharing.ShareAPI.deleteShare"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":82,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/apps/files_sharing/api/v1/shares/257"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/apps/maps/lib/Hooks/FileHooks.php","Line":152},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:73.0) Gecko/20100101 Firefox/73.0","version":"17.0.3.1","id":"xxxxxx"}
</details>

**Comment by kesselb** [comment]
https://github.com/search?l=&q=safeDeleteByFolderIdUserId&type=Issues

**Comment by dgedgedge** [comment]
Note: I have just seel Issue #280 and please see that I have Map enabled.

**Comment by sutidor** [comment]
I have maps enabled.
Fix:
path: /var/www/vhosts/nextcloud/apps/maps/lib/Hooks/FileHooks.php
apply change [#302](https://github.com/nextcloud/maps/pull/302/commits/12440760c29927cb9cee87c91103fa63d5ffd5bb)
