### ISSUE TITLE
Flow: Lightweight RBAC - Automatic groups.

### ISSUE THREAD

**Issue by Kerasit** [nextcloud/server#19617]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Build rules for Automatic assignment of groups to users.
Example:
(runs with Cron): If member of group A
Then
Assign Group B.

If added to Group A
Then
Assign Group B.

If removed from Group A.
Then
Remove from Group B.

I would like to be able to base App access on group memberships. For example so each app will have a group. Can also be used for 2FA (group: 2FA. Then Force 2FA for this group).

Then I can create role groups like: Social, Collaboration, Security, Family etc. And then I can dynamically define who can use what apps based on the Flow workflow rules. This also enables you to be able to easily assign the use of specific apps to single users.

**Describe alternatives you've considered**
Base my solution on an LDAP Directory and then use Dynamic Groups.
This is argueable the easiest and most powerfull way to control this and makes it so much easier to be in constant control as reporting and certification of access is easy in an LDAP Directory.
However this requires me to also maintain an LDAP server which only few privat users would ever do hence maintainen and operating an LDAP directory service is not for everyone.

Second Alternative could be to maintain this in "Limit to groups" for each apps however this setting is not consistant. Some are actually through the settings menu and not through the App menu.
The nice layout of the Flow App also makes it so much easier and powerfull to stay in control with the access model.

**Comment by szaimen** [comment]
> I would like to be able to base App access on group memberships.

You are. See this option for each app in the appstore:
![image](https://user-images.githubusercontent.com/42591237/120172879-c7572680-c203-11eb-8174-72f6e546383a.png)
