### ISSUE TITLE
No sharing tab on desktop Firefox

### ISSUE THREAD

**Issue by Mohammed-Al-Haidary** [nextcloud/server#19614]
Note: I have tested for this issue on Android Firefox and it works. The issue arises in the Desktop Firefox.

### Steps to reproduce
1. Go to the Files app on a Desktop Firefox browser.
2. Click on the "Share" button.

### Expected behaviour
The sidebar that comes up should have a Sharing tab.

### Actual behaviour
The sidebar has does not have a Sharing tab at all.

### Server configuration

**Operating system:** NextcloudPi

**Database:** 	mysql  10.3.17

**PHP version:** 7.3.11

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from an older NC.

**Signing status:**
<details>
<summary>Signing status</summary>

"No errors have been found."

</details>

**Are you using external storage, if yes which one:** I'm using a Local External Storage.

**Are you using encryption:** No.

### Client configuration
**Browser:** Desktop Firefox

**Operating system:** Windows 10

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

The Web Console log when I click on the Share button:

"showDetailsView is deprecated! Use OCA.Files.Sidebar.activeTab. It will be removed in nextcloud 20. merged-index.js:4452:12
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
recommendations 
[]
​
__ob__: Object { value: [], dep: {…}, vmCount: 0 }
​
length: 0
​
<prototype>: {…}
​​
pop: function ()​​
push: function ()​​
reverse: function ()​​
shift: function ()​​
sort: function ()​​
splice: function ()​​
unshift: function ()​​
<prototype>: Array []"

</details>

**Comment by kesselb** [comment]
Try without adblock?

**Comment by Mohammed-Al-Haidary** [comment]
I tried it without uBlock Origin and it worked!
I whitelisted my domain so it works automatically.

Thank you!
Apologies for any inconvenience.
