### ISSUE TITLE
Change display name break group associations

### ISSUE THREAD

**Issue by hmielimo** [nextcloud/server#19627]
nextcloud version 18.0.1
php 7.3

change user displayname with UI it breaks the group-associations but doing so with api work fine.

**Comment by hmielimo** [comment]
# ------------------------------------------------------------------------------------------------------------
# --- history
# ------------------------------------------------------------------------------------------------------------
- initial step: https://help.nextcloud.com/t/change-display-name-break-group-associations/72050?u=kiz
- second step: https://github.com/nextcloud/server/issues/19627

# ------------------------------------------------------------------------------------------------------------
# --- set environement
# ------------------------------------------------------------------------------------------------------------
- fresh nextcloud 18.0.1 install on ubuntu 18.04.4 LTS using php 7.3
- login as ncadmin and check box "Restrict users to only share with users in their groups" in Settings - Administration - Sharing

# ------------------------------------------------------------------------------------------------------------
# --- set parameter
# ------------------------------------------------------------------------------------------------------------
PoNCoadmin=mydomain
PoNCoADMINoPASSWORD=myPassword
MYURL="https://${PoNCoadmin}:${PoNCoADMINoPASSWORD}@${PoDOMAIN}/nextcloud/ocs/v1.php/cloud"
MYGROUP1=MusterFirma
MYGROUP2=Musterfirma.Buchhaltung
MYGROUP3=Musterfirma.Marketing
MYGROUP4=Musterfirma.Logistik
MYGROUP5=Musterfirma.BuM
MYGROUP6=Musterfirma.MuL

# ------------------------------------------------------------------------------------------------------------
# --- drop and create needed groups
# ------------------------------------------------------------------------------------------------------------
MYGROUP=${MYGROUP1}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP2}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP3}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP4}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP5}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP6}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 

# ------------------------------------------------------------------------------------------------------------
# --- drop and create needed users
# ------------------------------------------------------------------------------------------------------------
MYUSER=Mitarbeiter1.Buchhaltung
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP2}" -d groups[]="${MYGROUP5}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Buchhaltung
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP2}"                           -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Buchhaltung
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"   -d groups[]="${MYGROUP2}"                          -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Marketing
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP3}" -d groups[]="${MYGROUP5}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Marketing
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP3}" -d groups[]="${MYGROUP6}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Marketing
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"   -d groups[]="${MYGROUP3}"                          -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Logistik
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP4}" -d groups[]="${MYGROUP6}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Logistik
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP4}"                           -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Logistik
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"   -d groups[]="${MYGROUP4}"                          -H "OCS-APIRequest:true" 

# ------------------------------------------------------------------------------------------------------------
# --- change to UI and validate
# ------------------------------------------------------------------------------------------------------------
=> log in as Mitarbeiter1.Buchhaltung
=> list contacts: you see: Mitarbeiter1.Marketing, Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung
=> log in as Mitarbeiter1.Marketing
=> list contacts: you see: Mitarbeiter1.Buchhaltung, Mitarbeiter2.Marketing and Mitarbeiter3.Marketing

# ------------------------------------------------------------------------------------------------------------
# --- set environement/parameter
# ------------------------------------------------------------------------------------------------------------

MYUSER=Mitarbeiter1.Buchhaltung
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}X" -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP2}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP5}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Buchhaltung
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP2}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Buchhaltung
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP2}"            -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Marketing
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}X" -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP3}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP5}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Marketing
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP3}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP6}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Marketing
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP3}"            -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Logistik
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}X" -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP4}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP6}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Logistik
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP4}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Logistik
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP4}"            -H "OCS-APIRequest:true" 


# ------------------------------------------------------------------------------------------------------------
# --- change to UI and validate
# ------------------------------------------------------------------------------------------------------------
=> log in as Mitarbeiter1.BuchhaltungX
=> list contacts: you see: Mitarbeiter1.MarketingX, Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung

=> log in as Mitarbeiter1.MarketingX
=> list contacts: you see: Mitarbeiter1.BuchhaltungX, Mitarbeiter2.Marketing and Mitarbeiter3.Marketing

=> log in as Mitarbeiter1.BuchhaltungX 
=> change full name (display name) to Mitarbeiter1.Buchhaltung
=> list contacts: you see: Mitarbeiter1.MarketingX, Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung

=> log in as Mitarbeiter1.MarketingX
=> list contacts: you see (PROBLEM now we miss Mitarbeiter1.Buchhaltung): Mitarbeiter2.Marketing and Mitarbeiter3.Marketing
=> change full name (display name) to Mitarbeiter1.Marketing

=> log in as Mitarbeiter1.Buchhaltung
=> list contacts: you see (PROBLEM now we miss Mitarbeiter1.Marketing): Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung

**Comment by kesselb** [comment]
Thanks for this detailed report :+1: 

1. Please use the issue template: https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md. It's acceptable to skip the logs section (if there are no lines regarding this problem).  

2. Please use https://guides.github.com/features/mastering-markdown/ to format your post. In the current version it's hard to read.

3. It's good to reference the topic with help.nextcloud.com but please make sure that all information required to reproduce the issue are also on GitHub.

To keep this report uncluttered please edit the existing posts.

**Comment by hmielimo** [comment]
---
name: 🐛 Bug report
about: Help us improving by reporting a bug
labels: bug, 0. Needs triage
---



### Steps to reproduce
1. fresh nextcloud 18.0.1 install
2. login as ncadmin and check box "Restrict users to only share with users in their groups" in Settings - Administration - Sharing
3. run script A (drop and create needed groups, drop and create needed users)
4. use UI and validate (I)
5. change displayname of users (api driven)
6. use UI and validate (II)

### Expected behaviour
use UI and validate (I) have to be equal to use UI and validate (II)

### Actual behaviour
use UI and validate (I) differ from to use UI and validate (II)

### Server configuration

**Operating system:** ubuntu 18.04.4 LTS

**Web server:**  Apache/2.4.29 

**Database:** PostgreSQL 10.12

**PHP version:** 7.3.15

**Nextcloud version:** Nextcloud 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-18.0.1.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

developer@localhost:~$ sudo -u www-data php "${PoNCoPATH}"/occ config:list system
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "development.kommunikation-im-zentrum.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.1.3",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "maintenance": false,
        "loglevel": 2,
        "data-fingerprint": "c37c6dbdcd41760eb5e9f91e23ad6e8a"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 73.0.1 32bit

**Operating system:** windows 10

### needed details
#### history
<details>
<summary>history</summary>
initial step: https://help.nextcloud.com/t/change-display-name-break-group-associations/72050?u=kiz
second step: https://github.com/nextcloud/server/issues/19627
</details>

#### SCRIPT A
<details>
<summary>SCRIPT A</summary>
set parameter
PoNCoadmin=mydomain
PoNCoADMINoPASSWORD=myPassword
MYURL="https://${PoNCoadmin}:${PoNCoADMINoPASSWORD}@${PoDOMAIN}/nextcloud/ocs/v1.php/cloud"
MYGROUP1=MusterFirma
MYGROUP2=Musterfirma.Buchhaltung
MYGROUP3=Musterfirma.Marketing
MYGROUP4=Musterfirma.Logistik
MYGROUP5=Musterfirma.BuM
MYGROUP6=Musterfirma.MuL

drop and create needed groups
MYGROUP=${MYGROUP1}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP2}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP3}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP4}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP5}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 
MYGROUP=${MYGROUP6}
curl -X DELETE ${MYURL}/groups/${MYGROUP}                  -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/groups -d groupid="${MYGROUP}"     -H "OCS-APIRequest:true" 

drop and create needed users
MYUSER=Mitarbeiter1.Buchhaltung
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP2}" -d groups[]="${MYGROUP5}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Buchhaltung
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP2}"                           -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Buchhaltung
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"   -d groups[]="${MYGROUP2}"                          -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Marketing
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP3}" -d groups[]="${MYGROUP5}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Marketing
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP3}" -d groups[]="${MYGROUP6}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Marketing
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"   -d groups[]="${MYGROUP3}"                          -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Logistik
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP4}" -d groups[]="${MYGROUP6}" -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Logistik
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"  -d groups[]="${MYGROUP4}"                           -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Logistik
curl -X DELETE ${MYURL}/users/${MYUSER}                                                                                                         -H "OCS-APIRequest:true" 
curl -X POST   ${MYURL}/users -d userid="${MYUSER}" -d password="kommunikation-im-zentrum"   -d groups[]="${MYGROUP4}"                          -H "OCS-APIRequest:true" 
</details>

#### use UI and validate (I)
<details>
<summary>use UI and validate (I)</summary>
* log in as Mitarbeiter1.Buchhaltung
* list contacts: you see: Mitarbeiter1.Marketing, Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung
* log in as Mitarbeiter1.Marketing
* list contacts: you see: Mitarbeiter1.Buchhaltung, Mitarbeiter2.Marketing and Mitarbeiter3.Marketing
</details>

#### change displayname of users (api driven)
<details>
<summary>change displayname of users (api driven)</summary>
MYUSER=Mitarbeiter1.Buchhaltung
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}X" -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP2}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP5}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Buchhaltung
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP2}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Buchhaltung
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP2}"            -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Marketing
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}X" -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP3}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP5}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Marketing
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP3}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP6}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Marketing
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP3}"            -H "OCS-APIRequest:true" 

MYUSER=Mitarbeiter1.Logistik
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}X" -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP4}"            -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP6}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter2.Logistik
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP4}"            -H "OCS-APIRequest:true" 
MYUSER=Mitarbeiter3.Logistik
curl -X PUT  ${MYURL}/users/${MYUSER} -d key="displayname" -d value="${MYUSER}"  -H "OCS-APIRequest:true" 
curl -X POST ${MYURL}/users/${MYUSER}/groups -d groupid="${MYGROUP4}"            -H "OCS-APIRequest:true" 
</details>

#### use UI and validate (II)
<details>
<summary>use UI and validate (II)</summary>
* log in as Mitarbeiter1.BuchhaltungX
* list contacts: you see: Mitarbeiter1.MarketingX, Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung

* log in as Mitarbeiter1.MarketingX
* list contacts: you see: Mitarbeiter1.BuchhaltungX, Mitarbeiter2.Marketing and Mitarbeiter3.Marketing

* log in as Mitarbeiter1.BuchhaltungX 
* change full name (display name) to Mitarbeiter1.Buchhaltung
* list contacts: you see: Mitarbeiter1.MarketingX, Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung

* log in as Mitarbeiter1.MarketingX
* list contacts: you see (PROBLEM now we miss Mitarbeiter1.Buchhaltung): Mitarbeiter2.Marketing and Mitarbeiter3.Marketing
* change full name (display name) to Mitarbeiter1.Marketing

* log in as Mitarbeiter1.Buchhaltung
* list contacts: you see (PROBLEM now we miss Mitarbeiter1.Marketing): Mitarbeiter2.Buchhaltung and Mitarbeiter3.Buchhaltung
</details>

**Comment by hmielimo** [comment]
this Issue still valid in NC21.0.2
