### ISSUE TITLE
update to 15.0.14 fail DriverException

### ISSUE THREAD

**Issue by raoulhatterer** [nextcloud/server#19620]
This is the problem

Étape de réparation : Repair MySQL collation

Informations de réparation : Change row format for oc_addressbooks ...

Informations de réparation : Change collation for oc_addressbooks ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

The installation process stopped there.

What should I do ?

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by raoulhatterer** [comment]
`hatterer@ProBook-4515s:/var/www/html/nextcloud$ sudo mysql -u root Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.37-MariaDB-0+deb9u1 Debian 9.6

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show variables like 'innodb_file_format';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| innodb_file_format | Antelope |
+--------------------+----------+
1 row in set (0.01 sec)

MariaDB [(none)]> SET GLOBAL innodb_file_format=Barracuda;Query OK, 0 rows affected (0.00 sec)

MariaDB [(none)]> show variables like 'innodb_file_format';
+--------------------+-----------+
| Variable_name      | Value     |
+--------------------+-----------+
| innodb_file_format | Barracuda |
+--------------------+-----------+
1 row in set (0.00 sec)

MariaDB [(none)]> quit
Bye
hatterer@ProBook-4515s:/var/www/html/nextcloud$ sudo systemctl restart mariadb
hatterer@ProBook-4515s:/var/www/html/nextcloud$ sudo mysql -u root Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 2
Server version: 10.1.37-MariaDB-0+deb9u1 Debian 9.6

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show variables like 'innodb_file_format';
+--------------------+----------+
| Variable_name      | Value    |
+--------------------+----------+
| innodb_file_format | Antelope |
+--------------------+----------+
1 row in set (0.00 sec)

MariaDB [(none)]> 
`
When I restart the server as mentioned on step 3 Barracuda format is lost.
