### ISSUE TITLE
Desktop version is not perfectly responsive.

### ISSUE THREAD

**Issue by Usamaahmad751** [nextcloud/server#19643]
Nextcloud is not fully responsive to Desktop devices. On larger screens, the scroll bars appear sometimes and disappear automatically that's not a good for better user experience.

**Comment by kesselb** [comment]
Thanks for taking the time to create a bug report :+1: 

I know the issue template is a bit inconvenient for visual issues but please make sure to include at least Nextcloud version, the browser you see that issue, and a screenshot. Otherwise it's hard to reproduce the problem.
