### ISSUE TITLE
Design Issue in Mobile Version.

### ISSUE THREAD

**Issue by Usamaahmad751** [nextcloud/server#19644]
The section's "Compliant By Design" Content is aligned to left without any space. It should be aligned in the center or with some space to the left to resemble other sections' content.

**Comment by kesselb** [comment]
Thanks for taking the time to create a bug report :+1: 

I know the issue template is a bit inconvenient for visual issues but please make sure to include at least Nextcloud version, the browser you see that issue, and a screenshot. Otherwise it's hard to reproduce the problem.
