### ISSUE TITLE
App store is blank after upgrade from 17 to 18. Error 404 https://apps.nextcloud.com/api/v0/apps.json not found

### ISSUE THREAD

**Issue by rkkoszewski** [nextcloud/server#19650]
Hi,
My appstore seems broken after the last Nextcloud upgrade from 17 to 18 trough the web installer. From the logs I can see that Nextcloud is trying to get the app list from the following URL "https://apps.nextcloud.com/api/v0/apps.json", but that path returns a 404 not found error. Manually going to that URL yields the same result. 

Is the App Store down or did the Nextcloud App Store URL change? How can I avoid this in future updates?

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/11cae98394884830e2d5e03fdec95f3c77aced92/lib/private/App/AppStore/Fetcher/Fetcher.php#L224

Remove appstoreurl from config.php and fetcher will use the default endpoint. v0 does not exist.

**Comment by kesselb** [comment]
And please use https://help.nextcloud.com for questions. That's the issue tracker not a support channel.

**Comment by georgehrke** [comment]
Closing, since this is a support request.

As already pointed out by @kesselb above:
Please raise your question in the forums: https://help.nextcloud.com
