### ISSUE TITLE
Fresh Nextcloud 18.0.1 installation reports missing indexes and that some columns are not set to big int

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#19658]
I just installed a fresh Nextcloud 18.0.1 (with the checkbox "install recommended apps" checked) with MariaDB as DB back-end.

After I finished the installation and went to the Admin settings -> Overview I saw this warnings:

![image](https://user-images.githubusercontent.com/1589737/75347157-7807a500-58a0-11ea-9e6f-13c0a873fe06.png)

cc @georgehrke because one of it seems to be calendar related.

**Comment by tcitworld** [comment]
I'd say that's expected behaviour since it's not regular repair steps but occ commands.

**Comment by georgehrke** [comment]
We should be able to fix it by modifying the original migration that is creating those tables.

cc @nickvergessen

**Comment by nickvergessen** [comment]
> We should be able to fix it by modifying the original migration that is creating those tables.

yes, same for the big ints

**Comment by nickvergessen** [comment]
> I'd say that's expected behaviour since it's not regular repair steps but occ commands.

The expected behaviour is to have an "okay" state after install. Warning about missing indexes are not giving a good feeling

**Comment by lnsergio** [comment]
`occ db:add-missing-indices`

If you use linux:

`sudo -u www-data php /path_to_nextcloud/occ db:add-missing-indices`

**Comment by leolivier** [comment]
Hi, on my side I got these messages after moving from NC 17 to 18.0.1.
The update went fine and NC18 seems to be working properly but I have this message and when I try to execute the occ command provided in the message, I get an error telling me 
```
An unhandled exception has been thrown:
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: could not find driver in /var/www/nextcloud/lib/private/DB/Connection.php:68
```

**Comment by tcitworld** [comment]
@leolivier As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com. The PHP module for your database might be disabled for CLI.

If you wish support with setup issues from Nextcloud GmbH they offer this as part of the Nextcloud subscription. Learn more about this at nextcloud.com/enterprise

**Comment by leolivier** [comment]
wise advice @tcitworld !
I found the right answer on https://help.nextcloud.com. (i.e. use php7.3 instead of php, cause due to an install problem, php is linked to php7.4 by mistake)
