### ISSUE TITLE
RSS feed for apps/activity often shows previous activity

### ISSUE THREAD

**Issue by c-prompt** [nextcloud/server#19663]
On the index.php/apps/activity/ page, when you click on Settings, you can check "Enable RSS feed" which will provide you a URL like myserver.com/index.php/apps/activity/rss.php?token=myTokenHere. The activity on the page itself looks fine and doesn't repeat.

However, within the actual RSS feed, I will often receive activity items "published" days ago and had already been received, even though they were not updated by anyone (e.g., "You created event EventName in calendar User2 and User1"). In other words, the pubDate is days ago and, although the RSS entry was already received when created, it is received again. Perhaps there's code incorrectly creating a new guid even though no change occurred? Or perhaps it's duplicating in the RSS feed because there are multiple activity_id (which appears to be the guid) for the same event (across different calendars)?

For example, here's what I see in the oc_activity table for an event that was just re-received:

```

activity_id | timestamp | priority | type | user | affecteduser | app | subject | subjectparams | message | messageparams | file | link | object_type | object_id
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
7496 | 1582311338 | 30 | calendar_event | User1 | User3 | dav | object_add_event | {"actor":"User1","calendar":{"id":13,"uri":"User2-and-User1","name":"User2   and   User1"},"object":{"id":"96b3da52-273b-4a05-ab7a-dd2c8cd48fa0","name":"EventName","classified":false}} | [] |   |   | calendar | 13
7495 | 1582311338 | 30 | calendar_event | User1 | User2 | dav | object_add_event | {"actor":"User1","calendar":{"id":13,"uri":"User2-and-User1","name":"User2   and   User1"},"object":{"id":"96b3da52-273b-4a05-ab7a-dd2c8cd48fa0","name":"EventName","classified":false}} | [] |   |   | calendar | 13
7494 | 1582311338 | 30 | calendar_event | User1 | User1 | dav | object_add_event_self | {"actor":"User1","calendar":{"id":13,"uri":"User2-and-User1","name":"User2   and   User1"},"object":{"id":"96b3da52-273b-4a05-ab7a-dd2c8cd48fa0","name":"EventName","classified":false}} | [] |   |   | calendar | 13
7493 | 1582311327 | 30 | calendar_event | User1 | User3 | dav | object_add_event | {"actor":"User1","calendar":{"id":13,"uri":"User2-and-User1","name":"User2   and   User1"},"object":{"id":"a24d6d3e-39f5-4aa4-b7b5-473794c3e44f","name":"EventName","classified":false}} | [] |   |   | calendar | 13
7492 | 1582311327 | 30 | calendar_event | User1 | User2 | dav | object_add_event | {"actor":"User1","calendar":{"id":13,"uri":"User2-and-User1","name":"User2   and   User1"},"object":{"id":"a24d6d3e-39f5-4aa4-b7b5-473794c3e44f","name":"EventName","classified":false}} | [] |   |   | calendar | 13
7491 | 1582311327 | 30 | calendar_event | User1 | User1 | dav | object_add_event_self | {"actor":"User1","calendar":{"id":13,"uri":"User2-and-User1","name":"User2   and   User1"},"object":{"id":"a24d6d3e-39f5-4aa4-b7b5-473794c3e44f","name":"EventName","classified":false}} | [] |   |   | calendar | 13
```

Once an activity is published to the RSS feed, it shouldn't be published again unless it's changed/deleted.

Nextcloud 18.0.1 (although it's been happening in earlier versions)
PHP 7.3.15
Debian 9
mysql 10.1.44

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
