### ISSUE TITLE
can't add user to group

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#19679]
I created a few users in the Nextcloud internal user management and later tried to assign them to the group "demo":

![image](https://user-images.githubusercontent.com/1589737/75457590-f3d71f80-597c-11ea-839a-4416ce4cf986.png)

The screenshot shows how I try to assign user "demo2" to the group "demo", as you can see the drop down to select the group doesn't cover the content of the row below and I'm also not able to select the group "demo" with the mouse. With the keyboard it works but therefore you really have to know what you are doing.

Tested with Nextcloud 18.0.1

**Comment by acs-ferreira** [comment]
Isn't this covered by https://github.com/nextcloud/server/pull/19533?
If yes, fixes will be pushed on the next minor update relase.

**Comment by schiessle** [comment]
yes, seems to be the same like https://github.com/nextcloud/server/issues/19503, just for groups instead of quota... Thanks for pointing me to it @acs-ferreira
