### ISSUE TITLE
Could not extract app documentserver_community

### ISSUE THREAD

**Issue by gen2** [nextcloud/server#19674]
### Steps to reproduce
1. install nextcloud 18.0.1
2. try to install "Community Document Server" from "App bundles"

### Expected behaviour
I expect a clean & smooth install of the requested component

### Actual behaviour
I get an error message popup inside the browser window:
"An error occured during the request. Unable to proceed.
Could not extract app documentserver_community"

### Server configuration

**Operating system:**
gentoo linux

**Web server:**
apache v2.4.41

**Database:**
SQLite

**PHP version:**
php7.3

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from older Nextcloud instance

**Where did you install Nextcloud from:**
official gentoo portage

**Signing status:**
<details>
<summary>Signing status</summary>

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- files_rightclick
	- EXTRA_FILE
		- README.md

Raw output
==========
Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => 008148d723136644c2542312557ed5b9db1af5de6797a221d221012ae0ad367b2daca4774bcaba8936ec8394093b83c3e3f2d8e7c52e5f5882e28579dffe99e2
                        )

                )

        )

).
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
 checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.1.9
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.17
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.5
  - nextcloud_announcements: 1.7.0
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.2
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.4
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - circles
  - encryption
  - files_external
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
   "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.gfz.qayx.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "sqlite3",
        "version": "18.0.1.3",
        "overwrite.cli.url": "http:\/\/localhost",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2,
        "maintenance": false,
        "app_install_overwrite": [
            "calendar",
            "circles"
        ]
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chromium, Version 80.0.3987.87 (Official Build)

**Operating system:**
Linux Mint 19.3 Tricia

#### Web server error log
<details>
<summary>Web server error log</summary>
will be attached (access.log)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
will be attached (nextcloud.log)
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Insert your browser log here, this could for example include:

a) The javascript console log
i don't know how to copy this from the webmaster tools :(

b) The network log
will be attached (network.log)

</details>

**Comment by gen2** [comment]
[access.log](https://github.com/nextcloud/server/files/4261608/access.log)
[nextcloud.log](https://github.com/nextcloud/server/files/4261609/nextcloud.log)
[network.log](https://github.com/nextcloud/server/files/4261610/network.log)

**Comment by manu-p** [comment]
Hi, I just can't find the way to install Community Document Server on NC 18.0.2 and make it run...
I've been:
1. downloading the master.zip from this [link](https://github.com/nextcloud/documentserver_community/archive/master.zip) ;
2. unzipping it in the NC apps subfolder and renamed it to `documentserver_community` ;
3. installing ONLYOFFICE via the normal way (i.e. appstore in NC) and activating it ;
4. deleting Document Editing Service address in the ONLYOFFICE settings leting all options empty and saving these setting ;
5. installing glibc* on the server ; 

Now, when I try to activate Community Document Server 0.1.5 in the NC appstore, I get this error message:
`sh: 1: ../../tools/allfontsgen: not found`

No allfontsgen file anywhere in the NC tree...

Also tried to add custom fonts to the document server using the following occ commands:
`sudo -u www-data ./occ documentserver:fonts --add /usr/share/fonts/myfont.ttf`

And I get this error message:
`There are no commands defined in the "documentserver" namespace.`

What did I miss?

**Comment by kesselb** [comment]
> What did I miss?

That GitHub is a issue tracker and not a support channel: https://help.nextcloud.com is the first place to ask questions. 

> downloading the master.zip from this https://github.com/nextcloud/documentserver_community/archive/master.zip ;

Don't know how told you to use that version but I would try to version from the releases page and not a dump of the git branch (until you want to build it yourself).

**Comment by manu-p** [comment]
OK thanks.

**Comment by gen2** [comment]
> > What did I miss?
> 
> That GitHub is a issue tracker and not a support channel: https://help.nextcloud.com is the first place to ask questions.

I know, and IMHO i reported an issue: the installation of an app from within the NextCloud installation by clicking "Enable" just failed. To do that, i completed a somewhat extended form for proper issue reporting...


> > downloading the master.zip from this https://github.com/nextcloud/documentserver_community/archive/master.zip ;
> 
> Don't know how told you to use that version but I would try to version from the releases page and not a dump of the git branch (until you want to build it yourself).

Thanks, i'll do that.

**Comment by gen2** [comment]
> Looks similar to #19061. Seems to be related to the archive. You may install the release from https://github.com/nextcloud/documentserver_community/releases manually.

Tnx, that helped! :)

**Comment by alex9434** [comment]
I don not think that this is a good long term solution, because it would require MANUALLY updating all apps individually. Because of this bug the automatic update is broken.

**Comment by spants** [comment]
related to #21328 ?
