### ISSUE TITLE
Add TODOs Badge to README

### ISSUE THREAD

**Issue by patrickdevivo** [nextcloud/server#19677]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/nextcloud/server)](https://www.tickgit.com/browse?repo=github.com/nextcloud/server)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.com/nextcloud/server)](https://www.tickgit.com/browse?repo=github.com/nextcloud/server)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

(full disclosure, I am the creator/maintainer of `tickgit`)

**Comment by georgehrke** [comment]
Hi @patrickdevivo,

Thx for the offer, but that does not really fit the way we handle open todos in this organization.

**Comment by patrickdevivo** [comment]
> Hi @patrickdevivo,
> 
> Thx for the offer, but that does not really fit the way we handle open todos in this organization.

Understood! Thanks for considering and please do reach out if there are any ways the project could be made more useful to you or other contributors!
