### ISSUE TITLE
 'tempdirectory' in config.php is ignored. 

### ISSUE THREAD

**Issue by thisaccountname** [nextcloud/server#19682]
### Steps to reproduce
1. Fresh installation of NC
2. Change data directory successfully, config.php looks like:
```
 'datadirectory' => '/mnt/my8TBeZ/nextcloud/data',
  'tempdirectory' => '/mnt/my8TBeZ/nextcloud/data/tmp',
```
3. Upload decently sized file, monitor disk usage during upload. 

### Expected behaviour
'tempdirectory' is used and _only_ my external drive's disk space decreases.

### Actual behaviour
Large (~150MB) chunks are continually written to SD card before being transferred to external.

### Server configuration

**Operating system:**
Raspbian
**Web server:**
Apache
**Database:**
MySQL/MariaDB
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
18.0.1.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
NC Github

### Things I've done
Added `upload_tmp_dir = /mnt/my8TBeZ/nextcloud/data/tmp` to my .user.ini file. 
Added `upload_tmp_dir = /mnt/my8TBeZ/nextcloud/data/tmp` to my php.ini file. 

Ensured proper ownership on mount location, running both
```
sudo chmod 0770 /mnt/my8TBeZ/nextcloud/
sudo chown -R www-data:www-data /mnt/my8TBeZ/nextcloud/
```

I can read and write files just fine. The process in which they get there is the part I can't change.

[Apparently I wasn't alone in this](https://github.com/nextcloud/server/issues/9631), I am hoping this thread won't be ignored as much as [@berho](https://github.com/berho)'s was

**Comment by kesselb** [comment]
Don't put the temp directory inside the data directory.

**Comment by thisaccountname** [comment]
> Don't put the temp directory inside the data directory.

Changes made, server restarted. 

Same behavior.

**Comment by kesselb** [comment]
Yes. Just a general note not to do that.

**Comment by thisaccountname** [comment]
@kesselb gotcha, thank you!

**Comment by kesselb** [comment]
I don't see any issue with Nextcloud. `tempdirectory` is not relevant for uploads. Chunks are always uploaded to the datadirectory. PHP also has a directive for temporary files. Change that directive to a location on your external disk.

**Comment by thisaccountname** [comment]
> Chunks are always uploaded to the datadirectory.
Then why, after setting my data directory to my external drive, does this behavior persist?

> PHP also has a directive for temporary files. Change that directive to a location on your external disk.

As mentioned in my post, I did.

**Comment by kesselb** [comment]
> As mentioned in my post, I did.

You don't. `upload_tmp_dir` is the wrong directive.

**Comment by thisaccountname** [comment]
> You don't. `upload_tmp_dir` is the wrong directive.

Why didn't you mention that 4 days ago?

Both `upload_tmp_dir` and `sys_temp_dir` are defined. Are either of these supposed to be fixing this issue?

**Comment by suslikas** [comment]
Same for version **18.0.4.2**. Php-fpm 7.3+nginx. From this case 

./lib/private/TempManager.php
```
    if ($temp = $this->config->getSystemValue('tempdirectory', null)) {
      $directories[] = $temp;
    }
    if ($temp = \OC::$server->getIniWrapper()->get('upload_tmp_dir')) {
      $directories[] = $temp;
    }
    if ($temp = getenv('TMP')) {
      $directories[] = $temp;
    }
    if ($temp = getenv('TEMP')) {
      $directories[] = $temp;
    }
    if ($temp = getenv('TMPDIR')) {
      $directories[] = $temp;
    }
    if ($temp = sys_get_temp_dir()) {
      $directories[] = $temp;
    }
```

Work only TMPDIR when configured in php-fpm pool as 

```
env[TMPDIR] = /path/tmp
```

**Comment by suslikas** [comment]
@kesselb can you reopen issue? Problem not related with tmp directory path.

**Comment by kesselb** [comment]
What problem are you talking about?

**Comment by suslikas** [comment]
*tempdirectory* parameter in config.php is ignored. During file upload via webdav all php temporary files stored in /tmp
 
```
'tempdirectory' => '/data/tmp',
```

**Comment by kesselb** [comment]
> I don't see any issue with Nextcloud. `tempdirectory` is not relevant for uploads. Chunks are always uploaded to the datadirectory. PHP also has a directive for temporary files. Change that directive to a location on your external disk.

Uploads are processed by PHP before handed to Nextcloud. We are unable to change the location PHP uses to store temporary files used for uploads.

![image](https://user-images.githubusercontent.com/3902676/86779297-af127200-c05b-11ea-80e7-7739cfbbdf17.png)


https://www.php.net/manual/en/ini.core.php#ini.upload-tmp-dir

![image](https://user-images.githubusercontent.com/3902676/86779343-b9cd0700-c05b-11ea-8de1-c20a9fb77fc2.png)

https://www.php.net/manual/en/configuration.changes.modes.php

**Comment by suslikas** [comment]
My questions not about how to change php upload directory. tempdirectory directive for other nextcloud temporary files, not php upload? Then make sense update documentation, because is not clear.

```
/**
 * Override where Nextcloud stores temporary files. Useful in situations where
 * the system temporary directory is on a limited space ramdisk or is otherwise
 * restricted, or if external storages which do not support streaming are in
 * use.
 *
 * The Web server user must have write access to this directory.
 */
'tempdirectory' => '/tmp/nextcloudtemp',
```

Thank you. Now it's clear.

**Comment by thisaccountname** [comment]
@suslikas this was a while ago but the only way I was able to get around this behavior was to put my RPi filesystem on an external USB drive. 

I followed this guide:

https://www.raspberrypi.org/forums/viewtopic.php?t=44177

I also ended up moving away from Nextcloud, but from the short amount of testing I did this solved my problem. Pain in the butt but overall better performance regardless.

Good luck!

**Comment by petrosy** [comment]
I have the same issue which I solved as follows. 
I created my new TMP folder and then setup a symbolic link to the original default

I first deleted the original /var/snap/nextcloud/common/nextcloud/tmp
then linked my new folder
ln -sf /media/usbc/nextcloud/tmp/ /var/snap/nextcloud/common/nextcloud/
folder is owned by ROOT

**Comment by sebastiansterk** [comment]
Issue still persists in Nextcloud 24. `tempdirectory` is still being ignored. :-/

**Comment by CaptainSifff** [comment]
As stated above setting the php environment variables does the trick. A clarification in the docs for this setting would still be nice....

**Comment by kesselb** [comment]
@CaptainSifff mind to send a pull request?

**Comment by CaptainSifff** [comment]
like so? https://github.com/nextcloud/server/pull/35974
