### ISSUE TITLE
"Admin" item not showing in top right menu

### ISSUE THREAD

**Issue by phiraspb4** [nextcloud/server#19686]
Hello,
I have a question from a newbie : on my freshly installed NextCloud17 , when I click on the top right menu, I don't have the "Admin" item available even though I appear to be a member of the ADMIN group. 
Am I missing something or is there a configuration somewhere to grant access to this feature ?
In fact I need it to add a storage device to my Rasp4 server and it needs this admin access to fulfill this task.
Thanks for your answer, if you can...

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
