### ISSUE TITLE
LDAP App Not reachable oustide domain 

### ISSUE THREAD

**Issue by NA3** [nextcloud/server#19687]
Hi, my nextcloud i online throuth opnsense firewall (ha proxy & let's encrypt)
but when i active the ldap app it is only reachable inside my domain lan
the ldap login is doing good with active directory but netcloud was offline on the internet only goo on the lan
if someone can help?
Regards.

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
