### ISSUE TITLE
10.0.1: Error during final Configuration with MySQL

### ISSUE THREAD

**Issue by linuxfreund** [nextcloud/server#1969]
### Steps to reproduce
1. Download release 10.0.1
2. Start Configuration with MySQL Backend

### Expected behaviour
Login screen should appear
With SQLite as Backend it works fine.

### Actual behaviour
An Error message appears:
Error while trying to create admin user:
Failed to connect to the database:
An exception occured in driver
SQLSTATE[HY000] [1045] Access denied
for user ‘db-user‘@‘localhost‘ (using password: YES)

### Server configuration
**Operating system:** Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-100-generic x86_64)

**Web server:** Apache 2

**Database:** MySQL 5.6.33

**PHP version:** PHP 5.6.25

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** nextcloud-10.0.1.tar.bz2

**Comment by nickvergessen** [comment]
Well did you specify the correct database credentials?

**Comment by linuxfreund** [comment]
Yes, I am sure, that I used correct database login data. In Fact, I tried the installation on two different LAMP-Servers at different ISPs. I got always the same error message.

**Comment by yendar28** [comment]
Hello, I do have the same error while finishing the setup. I am working on shared hosting. Does the setup perhaps try to use some operations that need root on the database? E.g. operations like creating new user or reading from "mysql.user" shall need root. But shared hosting, at least in my case, does not offer root on database. Owncloud did have that problem month ago as I read. But current OC 9 setup worked for me at shared hosting.

**Comment by linuxfreund** [comment]
The official software installer of my ISP announced, that PHP must me Version 7. With this parameter in the initial settings the installation worked very well.
