### ISSUE TITLE
Version 17.0.3 is allegedly latest version - why not 18.0.1

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#19692]
Hey guys,

I'm using NC version 17.0.3. Both the settings and occ:upgrade give me the information, my version is already latest. But on NC download page 18.0.1 is displayed as latest version:
![image](https://user-images.githubusercontent.com/11487054/75522042-452cf080-5a09-11ea-8954-16aed6278980.png)

When will 18.0.3 be available as stable upgrade from within an existing NC instance?

**Comment by kesselb** [comment]
Please use https://help.nextcloud.com for questions.
