### ISSUE TITLE
Mac Mojave Contacts won't synchronize properly

### ISSUE THREAD

**Issue by mo77en** [nextcloud/server#19708]
Steps to reproduce
1. Open Mac Contatcs 
2. Add NC CardDav Account, using the following steps
   2.1 Open Mac Calender.app
   2.2 Select Settings - > Accounts - > "+" - > extended 
3. I already tried the following settings for server path, username, password
   3.1. cloud.example.com, username, password
   3.2 cloud.example.com/remote.php/dav/,username,password
  3.3 cloud.example.com/remote.php/dav/principals/users/username,username,password

### Expected behaviour
Contacts will synch between Mac Contacts and NC Contacts synchronously 

### Actual behaviour
Mac Contacts is pulling complete Adressbook from NC Contacts once. After the initial synchronization finished it is synching only from Mac to NC. Changes made on the NC Contacts or other Devices connected to NC won't be synchronized to the Mac. 
Calender and NC Desktoplient work fine. 
On all other devices (another Mac, iPhone, iPad, ANDROID Phone, Windows PC) everything is working fine. 

### Server configuration
I am using NC 17.0.0 on an Ubuntuserver 18.0.4.
The Version of the Contacts app is 3.1.9.

Client configuration:
Mac OSX 10.14.6 (Mojave) 
Contacts.app 12.0(1894)

**Comment by BernieO** [comment]
> Add NC CardDav Account, using the following steps
2.1 Open Mac Calender.app
2.2 Select Settings - > Accounts - > "+" - > extended

CardDav/CalDav Accounts should be added in the system preference pane under "Internet Accounts"

Can you follow the documentation, when adding an account?
https://docs.nextcloud.com/server/17/user_manual/pim/sync_osx.html

**Comment by mo77en** [comment]
> CardDav/CalDav Accounts should be added in the system preference pane under "Internet Accounts"
> 
> Can you follow the documentation, when adding an account?
> https://docs.nextcloud.com/server/17/user_manual/pim/sync_osx.html

I tried it that way. But it is still the same behavior of the system.

**Comment by mo77en** [comment]
is there someone who is able to help me or has the same issue?

**Comment by kesselb** [comment]
https://help.nextcloud.com is the channel for support.

**Comment by skjnldsv** [comment]
Closing, there are lots of duplicates.
There is also opened discussions on the contacts repo and more importantly, the forum :)
