### ISSUE TITLE
"Move / Copy to ..." Button descriptions doesn't change after creating new folder

### ISSUE THREAD

**Issue by trisomeyr** [nextcloud/server#19718]
**Server:** Debian 9
**PHP:** 7.3
**Browser:** Firefox
**NC Version:** 18.0.1

**Actual behavior**
When creating a new folder lets say named "newexamplefolder" in an existing folder lets say "parentexamplefolder" within the move/copy Dialog, nc moves to the new folder after its creation. But the bottons descriptions do not change, they stay at "move to parentexamplefolder" and "copy to parentexamplefolder".

**Expected behavior**
When creating a new folder lets say named "newexamplefolder" in an existing folder lets say "parentexamplefolder" within the move/copy Dialog, nc moves to the new folder after its creation. The bottons descriptions change to "move to newexamplefolder" and "copy to newexamplefolder".

**Comment by trisomeyr** [comment]
thx for adding the labels, didn't know, how to do that :/

**Comment by lars-sh** [comment]
Same for me with both, Nextcloud versions 18.0.1 and 19.0.2.

Just for clarification: The buttons do not change, but clicking them works as expected.

**Comment by szaimen** [comment]
I can still reproduce this on NC21.0.2

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by lars-sh** [comment]
I just checked this with Nextcloud 25.0.2 and the problem still exists.

**Comment by siccovansas** [comment]
This is still an issue with Nextcloud 26.0.1.

To expand this issue. When you first select a file and click on 'Move or copy', the button's texts in the modal only show 'Copy' and 'Move'. To make the button text consistent it would make sense to also directly show the name of the current folder. To add to the argument: if you click on the current folder's name in the breadcrumb the 'Copy' and 'Move' buttons suddenly do show the current folder in their button text.

**Comment by skjnldsv** [comment]
cc @susnux

**Comment by susnux** [comment]
Fixed with 27.1 and later
