### ISSUE TITLE
Font size change when checkboxes are selected in NC18.0.*& NC17.0.3

### ISSUE THREAD

**Issue by GammaPi** [nextcloud/server#19725]
Just a small UI bug
### Steps to reproduce
1. Login
2. Check a folder
3. Font size change

![Peek 2020-03-01 15-47](https://user-images.githubusercontent.com/19838874/75621795-2cbd0180-5bd4-11ea-9c57-fad19f786d8f.gif)

### Server configuration

**Nextcloud version:** 18.0.3&18.0.2&18.0.1 & 17.0.3

**Where did you install Nextcloud from:**
Docker

**Comment by GretaD** [comment]
I cannot reproduce this on in none of the instances you have mentioned. I am using ubuntu 18.04 and firefox latest version. What browser are you using, and OS?

**Comment by GammaPi** [comment]
Firefox 74.0 (64-bit)
Problem persists on 18.0.3

**Comment by GammaPi** [comment]
Is it because of docker? If I use docker to upgrade from one version to another, some paths maybe overwritten by volume and cause this problem.
I'm currently mounting the following volume:
/var/www/html

**Comment by GammaPi** [comment]
Problem fixed after disabling OCR app. So it's probably not a nextcloud server problem.
