### ISSUE TITLE
LDAP -> LDAPS Version 17.0.3 error in log

### ISSUE THREAD

**Issue by hexxter** [nextcloud/server#19726]
### Expected behaviour
Tell us what should happen

After switch from ldap (PORT 389) to ldaps (PORT 636) (AD Server 2016) this entry is shown in the log:
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: OC\ServerNotAvailableException: Lost connection to LDAP server. at <<closure>>

0. <<closure>>
   undefinedundefined{closure}("*** sensitive parameters replaced ***")
1. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   undefinedundefinedcall_user_func_array(Closure {}, ["*** sensitive  ... "])
2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 466
   Sabre\Event\EventEmitter->emit("beforeMethod", ["*** sensitive  ... "])
3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
4. /var/www/html/nextcloud/remote.php line 72
   Sabre\DAV\Server->exec()
5. /var/www/html/nextcloud/remote.php line 166
   undefinedundefinedhandleException(OC\ServerNotAvailableException {})

PROPFIND /nextcloud/remote.php/dav/files/A9E44040-9967-4E8A-A5D5-xxxxxxx/
from 10.30.0.101 by A9E44040-9967-4E8A-A5D5-xxxxx at 2020-03-01T10:20:42+00:00

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**
Linux Debian 10.2
Linux cloudint 4.15.18-17-pve #1 SMP PVE 4.15.18-43 (Tue, 25 Jun 2019 17:59:49 +0200) x86_64 GNU/Linux

**Web server:**
apache2 Server version: Apache/2.4.38 (Debian)

**Database:**
Server version: 10.3.18-MariaDB-0+deb10u1 Debian 10

**PHP version:**
PHP 7.3.11-1~deb10u1 (cli) (built: Oct 26 2019 14:14:18) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.11, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.11-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
17.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Not a upgrade issue

**Where did you install Nextcloud from:**
nextcloud.com

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - checksum: 0.4.4
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - deck: 0.8.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - impersonate: 1.4.0
  - keeweb: 0.6.2
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.2
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - polls: 1.3.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - ransomware_protection: 1.5.1
  - recommendations: 0.5.0
  - richdocuments: 3.5.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharerenamer: 2.7.3
  - socialsharing_email: 1.0.6
  - spreed: 7.0.2
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - tasks: 0.11.3
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - calendar
  - encryption
  - external
  - files_trackdownloads
  - ransomware_detection
  - twofactor_totp
  - twofactor_yubikey

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.garching.semsotec.de",
            "cloudint.garching.semsotec.de",
            "10.30.0.106"
        ],
        "overwriteprotocol": "https",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.garching.semsotec.de",
        "overwritehost": "cloud.garching.semsotec.de",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app.mail.imap.timeout": 25,
        "app.mail.smtp.timeout": 10,
        "theme": "",
        "loglevel": 1,
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "keeweb"
        ]
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.10.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "4578"
        },
        "bookmarks": {
            "enabled": "yes",
            "installed_version": "2.3.4",
            "previews.screenly.token": " \tE5fmVNaV5kv3RqdHhveFi5uIRmPL2uC3YQGgrttJvz226YkIIn",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "2.0.1",
            "types": ""
        },
        "checksum": {
            "enabled": "yes",
            "installed_version": "0.4.4",
            "types": "filesystem"
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "enterpriseLogoChecked": "yes",
            "installedat": "1530030102.88",
            "lastcron": "1583060409",
            "lastupdateResult": "[]",
            "lastupdatedat": "1583059931",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "scss.variables": "ff67b979d883f0a59d3bca7980d43bb1",
            "shareapi_allow_resharing": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_default_permission_candelete": "yes",
            "shareapi_default_permission_canshare": "no",
            "shareapi_default_permissions": "15",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_expire_after_n_days": "30",
            "shareapi_only_share_with_group_members": "no",
            "theming.variables": "ff67b979d883f0a59d3bca7980d43bb1",
            "umgmt_show_backend": "true",
            "umgmt_show_email": "false",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "true",
            "updater.secret.created": "1580686229",
            "vendor": "nextcloud"
        },
        "dav": {
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.13.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "dav"
        },
        "external": {
            "enabled": "no",
            "installed_version": "3.4.1",
            "max_site": "3",
            "sites": "***REMOVED SENSITIVE VALUE***",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "federation": {
            "autoAddServers": "0",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "5 GB",
            "enabled": "yes",
            "installed_version": "1.12.0",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "yes",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem",
            "user_mounting_backends": "dav,owncloud,sftp,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "files_rightclick": {
            "enabled": "yes",
            "installed_version": "0.15.1",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.9.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trackdownloads": {
            "enabled": "no",
            "installed_version": "1.6.0",
            "types": "filesystem"
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.10.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "18.4.0",
            "types": ""
        },
        "impersonate": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "keeweb": {
            "enabled": "yes",
            "installed_version": "0.6.2",
            "types": "filesystem"
        },
        "logreader": {
            "enabled": "yes",
            "installed_version": "2.2.0",
            "levels": "00111",
            "relativedates": "",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": ""
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.5.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "types": "authentication"
        },
        "password_policy": {
            "enabled": "yes",
            "enforceHaveIBeenPwned": "1",
            "installed_version": "1.7.0",
            "types": ""
        },
        "polls": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "prevent_group_restriction"
        },
        "ransomware_detection": {
            "debug": "0",
            "enabled": "no",
            "installed_version": "0.6.0",
            "types": "logging"
        },
        "ransomware_protection": {
            "enabled": "yes",
            "extension_exclusions": "[\".cbf\",\".enc\",\".ttt\",\"^Lock\\\\.\",\".lock\"]",
            "installed_version": "1.5.1",
            "types": "logging"
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.5.0",
            "types": ""
        },
        "richdocuments": {
            "canonical_webroot": "",
            "enabled": "yes",
            "external_apps": "",
            "installed_version": "3.5.2",
            "public_wopi_url": "https:\/\/collabora.garching.semsotec.de",
            "types": "filesystem,dav,prevent_group_restriction",
            "wopi_url": "https:\/\/collabora.garching.semsotec.de:443"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "enforcePasswordProtection": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        },
        "sharerenamer": {
            "enabled": "yes",
            "installed_version": "2.7.3",
            "types": ""
        },
        "socialsharing_email": {
            "enabled": "yes",
            "installed_version": "1.0.6",
            "types": ""
        },
        "spreed": {
            "enabled": "yes",
            "hide_signaling_warning": "yes",
            "installed_version": "7.0.2",
            "project_access_invalidated": "1",
            "signaling_servers": "***REMOVED SENSITIVE VALUE***",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "turn_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.5.0",
            "last_report": "{\"id\":\"ocx1fdfvegv8\",\"items\":[[\"server\",\"version\",\"15.0.12.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"no\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.0.33\"],[\"php\",\"memory_limit\",536870912],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",535822336],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"10.1.26\"],[\"database\",\"size\",3459653632],[\"apps\",\"accessibility\",\"1.1.0\"],[\"apps\",\"activity\",\"2.8.2\"],[\"apps\",\"admin_audit\",\"1.5.0\"],[\"apps\",\"bookmarks\",\"2.1.1\"],[\"apps\",\"calendar\",\"1.6.6\"],[\"apps\",\"checksum\",\"0.4.3\"],[\"apps\",\"cloud_federation_api\",\"0.1.0\"],[\"apps\",\"comments\",\"1.5.0\"],[\"apps\",\"dav\",\"1.8.2\"],[\"apps\",\"deck\",\"disabled\"],[\"apps\",\"external\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.5.0\"],[\"apps\",\"federation\",\"1.5.0\"],[\"apps\",\"files\",\"1.10.0\"],[\"apps\",\"files_external\",\"1.6.0\"],[\"apps\",\"files_pdfviewer\",\"1.4.0\"],[\"apps\",\"files_sharing\",\"1.7.0\"],[\"apps\",\"files_texteditor\",\"2.7.0\"],[\"apps\",\"files_trackdownloads\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.5.0\"],[\"apps\",\"files_versions\",\"1.8.0\"],[\"apps\",\"files_videoplayer\",\"1.4.0\"],[\"apps\",\"firstrunwizard\",\"2.4.0\"],[\"apps\",\"gallery\",\"18.2.0\"],[\"apps\",\"keeweb\",\"0.5.1\"],[\"apps\",\"logreader\",\"2.0.0\"],[\"apps\",\"lookup_server_connector\",\"1.3.0\"],[\"apps\",\"mail\",\"0.11.1\"],[\"apps\",\"nextcloud_announcements\",\"1.4.0\"],[\"apps\",\"notifications\",\"2.3.0\"],[\"apps\",\"oauth2\",\"1.3.0\"],[\"apps\",\"password_policy\",\"1.5.0\"],[\"apps\",\"provisioning_api\",\"1.5.0\"],[\"apps\",\"ransomware_detection\",\"disabled\"],[\"apps\",\"richdocuments\",\"3.4.2\"],[\"apps\",\"serverinfo\",\"1.5.0\"],[\"apps\",\"sharebymail\",\"1.5.0\"],[\"apps\",\"socialsharing_email\",\"1.0.5\"],[\"apps\",\"spreed\",\"5.0.4\"],[\"apps\",\"support\",\"1.0.0\"],[\"apps\",\"survey_client\",\"1.3.0\"],[\"apps\",\"systemtags\",\"1.5.0\"],[\"apps\",\"tasks\",\"0.11.3\"],[\"apps\",\"theming\",\"1.6.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.4.1\"],[\"apps\",\"twofactor_totp\",\"disabled\"],[\"apps\",\"twofactor_yubikey\",\"disabled\"],[\"apps\",\"updatenotification\",\"1.5.0\"],[\"apps\",\"user_ldap\",\"1.5.0\"],[\"apps\",\"workflowengine\",\"1.5.0\"],[\"stats\",\"num_files\",512537],[\"stats\",\"num_users\",52],[\"stats\",\"num_storages\",130],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",92],[\"stats\",\"num_storages_other\",36],[\"stats\",\"num_comments\",608],[\"stats\",\"num_comment_markers\",27],[\"stats\",\"num_systemtags\",15],[\"stats\",\"num_systemtags_mappings\",13],[\"files_sharing\",\"num_shares\",1518],[\"files_sharing\",\"num_shares_user\",851],[\"files_sharing\",\"num_shares_groups\",149],[\"files_sharing\",\"num_shares_link\",58],[\"files_sharing\",\"num_shares_link_no_password\",58],[\"files_sharing\",\"num_fed_shares_sent\",1],[\"files_sharing\",\"num_fed_shares_received\",1],[\"files_sharing\",\"permissions_2_0\",\"2\"],[\"files_sharing\",\"permissions_11_0\",\"2\"],[\"files_sharing\",\"permissions_0_1\",\"12\"],[\"files_sharing\",\"permissions_1_1\",\"2\"],[\"files_sharing\",\"permissions_3_1\",\"39\"],[\"files_sharing\",\"permissions_4_1\",\"3\"],[\"files_sharing\",\"permissions_0_3\",\"11\"],[\"files_sharing\",\"permissions_3_3\",\"1\"],[\"files_sharing\",\"permissions_4_3\",\"2\"],[\"files_sharing\",\"permissions_3_4\",\"2\"],[\"files_sharing\",\"permissions_0_7\",\"39\"],[\"files_sharing\",\"permissions_4_14\",\"1\"],[\"files_sharing\",\"permissions_0_15\",\"39\"],[\"files_sharing\",\"permissions_1_15\",\"4\"],[\"files_sharing\",\"permissions_2_15\",\"9\"],[\"files_sharing\",\"permissions_3_15\",\"16\"],[\"files_sharing\",\"permissions_4_15\",\"2\"],[\"files_sharing\",\"permissions_0_17\",\"26\"],[\"files_sharing\",\"permissions_1_17\",\"2\"],[\"files_sharing\",\"permissions_2_17\",\"5\"],[\"files_sharing\",\"permissions_0_19\",\"94\"],[\"files_sharing\",\"permissions_10_19\",\"4\"],[\"files_sharing\",\"permissions_11_19\",\"1\"],[\"files_sharing\",\"permissions_0_21\",\"2\"],[\"files_sharing\",\"permissions_0_23\",\"44\"],[\"files_sharing\",\"permissions_1_23\",\"6\"],[\"files_sharing\",\"permissions_2_23\",\"5\"],[\"files_sharing\",\"permissions_0_31\",\"584\"],[\"files_sharing\",\"permissions_1_31\",\"135\"],[\"files_sharing\",\"permissions_2_31\",\"406\"],[\"files_sharing\",\"permissions_4_31\",\"17\"],[\"files_sharing\",\"permissions_6_31\",\"1\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1570469527",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.11.3",
            "types": ""
        },
        "text": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "8",
            "enabled": "yes",
            "installed_version": "1.8.0",
            "logoMime": "image\/png",
            "name": "Nextcloud Semsotec",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "no",
            "installed_version": "4.1.2",
            "types": ""
        },
        "twofactor_yubikey": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "types": ""
        },
        "updatenotification": {
            "bookmarks": "2.3.4",
            "bruteforcesettings": "1.5.0",
            "calendar": "1.6.5",
            "checksum": "0.4.4",
            "core": "17.0.3.1",
            "deck": "0.8.0",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "keeweb": "0.6.2",
            "mail": "1.1.1",
            "notify_groups": "[\"admin\"]",
            "polls": "1.3.0",
            "richdocuments": "3.5.2",
            "sharerenamer": "2.7.3",
            "socialsharing_email": "1.0.5",
            "spreed": "4.0.2",
            "tasks": "0.10.1",
            "types": "",
            "update_check_errors": "0"
        },
        "user_ldap": {
            "background_sync_interval": "43200",
            "background_sync_offset": "0",
            "background_sync_prefix": "s01",
            "cleanUpJobOffset": "0",
            "enabled": "yes",
            "installed_version": "1.7.0",
            "s01_lastChange": "1583060401",
            "s01has_memberof_filter_support": "1",
            "s01home_folder_naming_rule": "",
            "s01last_jpegPhoto_lookup": "0",
            "s01ldap_agent_password": "***REMOVED SENSITIVE VALUE***",
            "s01ldap_attributes_for_group_search": "",
            "s01ldap_attributes_for_user_search": "",
            "s01ldap_backup_host": "",
            "s01ldap_backup_port": "",
            "s01ldap_base": "DC=SAGE-SEMSOTEC,DC=local",
            "s01ldap_base_groups": "DC=SAGE-SEMSOTEC,DC=local",
            "s01ldap_base_users": "DC=SAGE-SEMSOTEC,DC=local",
            "s01ldap_cache_ttl": "600",
            "s01ldap_configuration_active": "1",
            "s01ldap_default_ppolicy_dn": "",
            "s01ldap_display_name": "displayname",
            "s01ldap_dn": "CN=admin,CN=Users,DC=SAGE-SEMSOTEC,DC=local",
            "s01ldap_dynamic_group_member_url": "",
            "s01ldap_email_attr": "mail",
            "s01ldap_experienced_admin": "0",
            "s01ldap_expert_username_attr": "",
            "s01ldap_expert_uuid_group_attr": "",
            "s01ldap_expert_uuid_user_attr": "",
            "s01ldap_gid_number": "gidNumber",
            "s01ldap_group_display_name": "cn",
            "s01ldap_group_filter": "(|(cn=cloud)(cn=H2F_cloud)(cn=admin_c)(cn=entw_elektronik_c)(cn=entw_mechanik_c)(cn=entw_software_c)(cn=prod_bonding_c)(cn=prod_mechanik_c)(cn=qualit\u00e4t_c)(cn=verwaltung_c))",
            "s01ldap_group_filter_mode": "0",
            "s01ldap_group_member_assoc_attribute": "member",
            "s01ldap_groupfilter_groups": "cloud\nH2F_cloud\nadmin_c\nentw_elektronik_c\nentw_mechanik_c\nentw_software_c\nprod_bonding_c\nprod_mechanik_c\nqualit\u00e4t_c\nverwaltung_c",
            "s01ldap_groupfilter_objectclass": "",
            "s01ldap_host": "ldap:\/\/10.10.100.114",
            "s01ldap_login_filter": "(&(&(|(objectclass=person))(|(|(memberof=CN=cloud,CN=Users,DC=SAGE-SEMSOTEC,DC=local)(primaryGroupID=2158))))(|(samaccountname=%uid)(|(sAMAccountName=%uid))))",
            "s01ldap_login_filter_mode": "0",
            "s01ldap_loginfilter_attributes": "sAMAccountName",
            "s01ldap_loginfilter_email": "0",
            "s01ldap_loginfilter_username": "1",
            "s01ldap_nested_groups": "0",
            "s01ldap_override_main_server": "",
            "s01ldap_paging_size": "500",
            "s01ldap_port": "389",
            "s01ldap_quota_attr": "",
            "s01ldap_quota_def": "",
            "s01ldap_tls": "0",
            "s01ldap_turn_off_cert_check": "1",
            "s01ldap_turn_on_pwd_change": "0",
            "s01ldap_user_display_name_2": "",
            "s01ldap_user_filter_mode": "0",
            "s01ldap_userfilter_groups": "cloud",
            "s01ldap_userfilter_objectclass": "person",
            "s01ldap_userlist_filter": "(&(|(objectclass=person))(|(|(memberof=CN=cloud,CN=Users,DC=SAGE-SEMSOTEC,DC=local)(primaryGroupID=2158))))",
            "s01use_memberof_to_detect_membership": "1",
            "types": "authentication"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": "filesystem"
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NA
**Are you using encryption:** yes/no
Fileencryption No, Transport https (TLS), LDAP No (this ist the problem)
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP / ActiveDirectory 
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                          |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                            |
| homeFolderNamingRule          |                                                                                                                                                                              |
| lastJpegPhotoLookup           | 0                                                                                                                                                                            |
| ldapAgentName                 | CN=admin,CN=Users,DC=SAGE-SEMSOTEC,DC=local                                                                                                                                  |
| ldapAgentPassword             | ***                                                                                                                                                                          |
| ldapAttributesForGroupSearch  |                                                                                                                                                                              |
| ldapAttributesForUserSearch   |                                                                                                                                                                              |
| ldapBackupHost                |                                                                                                                                                                              |
| ldapBackupPort                |                                                                                                                                                                              |
| ldapBase                      | DC=SAGE-SEMSOTEC,DC=local                                                                                                                                                    |
| ldapBaseGroups                | DC=SAGE-SEMSOTEC,DC=local                                                                                                                                                    |
| ldapBaseUsers                 | DC=SAGE-SEMSOTEC,DC=local                                                                                                                                                    |
| ldapCacheTTL                  | 600                                                                                                                                                                          |
| ldapConfigurationActive       | 1                                                                                                                                                                            |
| ldapDefaultPPolicyDN          |                                                                                                                                                                              |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                              |
| ldapEmailAttribute            | mail                                                                                                                                                                         |
| ldapExperiencedAdmin          | 0                                                                                                                                                                            |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                              |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                              |
| ldapExpertUsernameAttr        |                                                                                                                                                                              |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                              |
| ldapGidNumber                 | gidNumber                                                                                                                                                                    |
| ldapGroupDisplayName          | cn                                                                                                                                                                           |
| ldapGroupFilter               | (|(cn=cloud)(cn=H2F_cloud)(cn=admin_c)(cn=entw_elektronik_c)(cn=entw_mechanik_c)(cn=entw_software_c)(cn=prod_bonding_c)(cn=prod_mechanik_c)(cn=qualität_c)(cn=verwaltung_c)) |
| ldapGroupFilterGroups         | cloud;H2F_cloud;admin_c;entw_elektronik_c;entw_mechanik_c;entw_software_c;prod_bonding_c;prod_mechanik_c;qualität_c;verwaltung_c                                             |
| ldapGroupFilterMode           | 0                                                                                                                                                                            |
| ldapGroupFilterObjectclass    |                                                                                                                                                                              |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                       |
| ldapHost                      | ldap://10.10.100.114                                                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                                                              |
| ldapLoginFilter               | (&(&(|(objectclass=person))(|(|(memberof=CN=cloud,CN=Users,DC=SAGE-SEMSOTEC,DC=local)(primaryGroupID=2158))))(|(samaccountname=%uid)(|(sAMAccountName=%uid))))               |
| ldapLoginFilterAttributes     | sAMAccountName                                                                                                                                                               |
| ldapLoginFilterEmail          | 0                                                                                                                                                                            |
| ldapLoginFilterMode           | 0                                                                                                                                                                            |
| ldapLoginFilterUsername       | 1                                                                                                                                                                            |
| ldapNestedGroups              | 0                                                                                                                                                                            |
| ldapOverrideMainServer        |                                                                                                                                                                              |
| ldapPagingSize                | 500                                                                                                                                                                          |
| ldapPort                      | 389                                                                                                                                                                          |
| ldapQuotaAttribute            |                                                                                                                                                                              |
| ldapQuotaDefault              |                                                                                                                                                                              |
| ldapTLS                       | 0                                                                                                                                                                            |
| ldapUserAvatarRule            | default                                                                                                                                                                      |
| ldapUserDisplayName           | displayname                                                                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                                                                              |
| ldapUserFilter                | (&(|(objectclass=person))(|(|(memberof=CN=cloud,CN=Users,DC=SAGE-SEMSOTEC,DC=local)(primaryGroupID=2158))))                                                                  |
| ldapUserFilterGroups          | cloud                                                                                                                                                                        |
| ldapUserFilterMode            | 0                                                                                                                                                                            |
| ldapUserFilterObjectclass     | person                                                                                                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                         |
| ldapUuidUserAttribute         | auto                                                                                                                                                                         |
| turnOffCertCheck              | 1                                                                                                                                                                            |
| turnOnPasswordChange          | 0                                                                                                                                                                            |
| useMemberOfToDetectMembership | 1                                                                                                                                                                            |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

**Comment by blizzz** [comment]
Probably a CA of your own? You have to make it known https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html#ssl-certificate-verification-ldaps-tls

**Comment by szaimen** [comment]
Seems to be answered already by blizzz.
