### ISSUE TITLE
Upload via Drag&Drop into Browser Window works improperly

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/server#19728]
Upload via Drag&Drop into a Browser Window does not work if one doesn’t hit the upper area of the window. In that case the file is ignored (not uploaded).

The issue happens when using a shared link, it does NOT happen if one do the same as a regularly logged-on NC user. I tried Firefox and Chrome both under Windows 10

See below example images. Drop location in first image works. The drop location used in 2nd image does not.

### Steps to reproduce
1. Create a Folder and Share it via Link
2. Navigate to the Link  
3. Maximize the Browser Window (certain screen resolution is needed to reproduce)
4. Try to Drag&Drop a file in lower area of the window (see 2nd example image)

![works](https://user-images.githubusercontent.com/17343515/75628637-4b72c680-5bdb-11ea-9f40-719e27e9bbbd.jpg)

![worksnot](https://user-images.githubusercontent.com/17343515/75628639-5168a780-5bdb-11ea-9af2-c4563be7620f.jpg)

**Comment by acs-ferreira** [comment]
This is because the container div only fits the top of the screen.

![image](https://user-images.githubusercontent.com/12234510/75759530-06af7280-5d36-11ea-9017-1f36facac6cc.png)

**Comment by steve-s-71** [comment]
any hope to get this fixed?

**Comment by steve-s-71** [comment]
No reaction for more than 3 months. I assume I have entered this feedback into the wrong category and hereby close this issue. I have submitted it again in a more appropriate category here: https://github.com/nextcloud/server/issues/21912
