### ISSUE TITLE
Getting 404 on re share with delete disabled on initial share

### ISSUE THREAD

**Issue by joeltheukranian** [nextcloud/server#19727]
V18 on Ubuntu

Getting 404 on re share with delete disabled on initial share

Admin Shares fileA with delete off to user X
User X reshares same fileA to user Y
404

Request URL: http://localhost:2280/ocs/v2.php/apps/files_sharing/api/v1/shares
Request Method: POST
Status Code: 404 Not Found
Remote Address: 127.0.0.1:2280
Referrer Policy: no-referrer

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
