### ISSUE TITLE
Update oc_addressbooks

### ISSUE THREAD

**Issue by roosbug** [nextcloud/server#19735]
### Steps to reproduce
1. run the php updater
2. 
3.

### Expected behaviour
error : 

Étape de réparation : Repair MySQL collation

Informations de réparation : Change row format for oc_addressbooks ...

Informations de réparation : Change collation for oc_addressbooks ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

On ssh console : 

Checking for update of app spreed in appstore
Update app spreed from appstore
Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Checked for update of app "spreed" in appstore
Repair error: Repair step 'OCA\Talk\Migration\FixNamespaceInDatabaseTables' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Repair error: Repair step 'OCA\Talk\Migration\ClearResourceAccessCache' is unknown
Repair error: Repair step 'OCA\Talk\Migration\CreateHelpCommand' is unknown
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;':

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Update failed

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:** Debian 9

**Web server:**

**Database:**

**PHP version:** PHP version: 7.3.15

**Nextcloud version:** (see Nextcloud admin page) 17 > 18

**Updated from an older Nextcloud/ownCloud or fresh install:** update

**Where did you install Nextcloud from:** my own server

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Please use the search 🔎
