### ISSUE TITLE
Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#1974]
I just tried a federated share between two users on the same servers (master). If the recipient  accepts the share I see this in my nextcloud.log:

````
{"reqId":"od6W9gJLNy+Fc9FLFv1+","remoteAddr":"::1","app":"filesystem","message":"Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","level":2,"time":"2016-11-02T09:25:01+00:00","method":"PROPFIND","url":"\/master\/public.php\/webdav\/","user":"--","version":"9.2.0.4"}
````

Everything seems to work. But it still looks suspicious. Any idea @rullzer @icewind1991 ?

Edit: Seems to happen for any action on the federated share, if I navigate into the folder, open a file, edit it,... All operation work but they always trigger this error message

**Comment by nickvergessen** [comment]
Duplicate https://github.com/nextcloud/server/issues/1652

**Comment by elhananjair** [comment]
I found that an app called "Share Permissions" is giving the same warning after I installed it on my nextcloud 21
