### ISSUE TITLE
cURL error 28: Operation timed out after XXXXXX milliseconds

### ISSUE THREAD

**Issue by nooblag** [nextcloud/server#19753]
This issue has been reported before at help.nextcloud.com, but I'm not sure if it has been reviewed or actioned as a bug, let alone fixed in latest release, so I'm filing this here.

**Recap/issue:**
We have fresh Nextcloud 18.0.0 server that is based in Australia and connections to *.nextcloud.com are always very slow, even on our fast connection, I assume just because of geography. When trying to access and install apps from Appstore, we often run into `cURL error 28: Operation timed out after XXXXXX milliseconds` errors.

This occurs both in web and when using `occ app:install`.

It's been mentioned there is a hardcoded timeout in:
`/var/www/nextcloud/lib/private/App/AppStore/Fetcher/Fetcher.php`
`/var/www/nextcloud/lib/private/Http/Client/Client.php`

If the timeout in these files is increased, the cURL problem is fixed and apps install fine.

I consider this a bug, because it is undesirable to modify core files, and also triggers security warnings about core files being modified (checksum failures).

Could the hardcoded timeout for the above two files be increased to a much larger value?

**References:**
https://help.nextcloud.com/t/curl-error-28-operation-timed-out-after-xxxxxx-milliseconds-with-xxxxxx-out-of-xxxxxx-bytes-received-see-http-curl-haxx-se-libcurl-c-libcurl-errors-html/67621

https://help.nextcloud.com/t/downloading-certain-apps-not-working/62603

**Comment by kesselb** [comment]
Thanks 👍 Please use the search. There are already some reports.

**Comment by nooblag** [comment]
Thank you. Ah yes, now I can see quite a lot actually on this issue.

Any consensus on moving forward? I'd upvote [Making 'timeout for HTTP requests' a configurable item](https://github.com/nextcloud/server/issues/18103) since as I say, hacking core files to increase a hardcoded timeout is unwanted and the software is essentially broken without this change?

**Comment by nooblag** [comment]
Okay thanks. ;)
