### ISSUE TITLE
NC is not storing users sessions

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#19759]
### Steps to reproduce
1. Launch one instance of nc (in docker or k8s), use docker image 16.0.8-fpm
2. Setup and config Social Login (custom openid connect -> ldap backend (I use keycloak))
3. Scale number of instances, use one common config (nfs-volume), db, redis

### Expected behaviour
open login page, choose social login, enter ldap name and pass, login inside

### Actual behaviour
after entering login and pass, getting error 
```
The authorization state [state=HA-DHBSWTVN2UYK70XLO6MJ4IPQ9AR8F1E5G3ZC] of this page is either invalid or has already been consumed.
```

### Server configuration

**Operating system:**
Debian Buster
**Web server:**
Nginx 1.17.8
**Database:**
Percona XtraDB Cluster, mysql  Ver 14.14 Distrib 5.7.18-15
**PHP version:**
7.3.15
**Nextcloud version:** (see Nextcloud admin page)
16.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
`docker pull nextcloud:16.0.8-fpm`
**Signing status:**
Impossible, cannot login
Using one instance - no errors.

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.2.0
  - activity: 2.9.1
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 0.2.0
  - comments: 1.6.0
  - dav: 1.9.2
  - federatedfilesharing: 1.6.0
  - federation: 1.6.0
  - files: 1.11.0
  - files_pdfviewer: 1.5.0
  - files_rightclick: 0.13.0
  - files_sharing: 1.8.0
  - files_texteditor: 2.8.0
  - files_trashbin: 1.6.0
  - files_versions: 1.9.0
  - files_videoplayer: 1.5.0
  - firstrunwizard: 2.5.0
  - gallery: 18.3.0
  - logreader: 2.1.0
  - lookup_server_connector: 1.4.0
  - nextcloud_announcements: 1.5.0
  - notifications: 2.4.1
  - oauth2: 1.4.2
  - password_policy: 1.6.0
  - privacy: 1.0.0
  - provisioning_api: 1.6.0
  - recommendations: 0.4.0
  - serverinfo: 1.6.0
  - sharebymail: 1.6.0
  - support: 1.0.0
  - survey_client: 1.4.0
  - systemtags: 1.6.0
  - theming: 1.7.0
  - twofactor_backupcodes: 1.5.0
  - updatenotification: 1.6.0
  - viewer: 1.2.0
  - workflowengine: 1.6.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "logtimezone": "Europe\/Prague",
        "social_login_auto_redirect": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "enable_previews": false,
        "objectstore_multibucket": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "num_buckets": 15000,
                "bucket": "nextcloud-",
                "autocreate": true,
                "key": "superkey",
                "secret": "hackme",
                "use_ssl": false,
                "hostname": "minio.svc.cluster.local",
                "port": 9000,
                "use_path_style": true
            }
        },
        "onlyoffice": {
            "jwt_header": "Authorization",
            "verify_peer_off": true
        },
        "loglevel": 3,
        "trusted_domains": [
            "nc.domain.org",
            "localhost",
            "10.*.*.*",
            "onlyoffice.domain.org"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379"
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "16.0.8.1",
        "overwrite.cli.url": "https:\/\/nc.domain.org",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "production",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
S3 as default storage
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
oAuth -> Keycloak (as gateway for authentication ) -> FreeIPA

### Client configuration
**Browser:**
Firefox 69.0.2 
**Operating system:**
Arch Linux
#### Web server error log
nothing related to this problem

#### Nextcloud log (data/nextcloud.log)
nothing related to this problem

#### Browser log
nothing related to this problem

Probably, the reason is than NC doesn't save users sessions in redis, that's why the sessions cannot be common for all instances.

**Comment by kesselb** [comment]
https://github.com/nextcloud/docker/blob/ac8c9984319e45fd34fa3863f82fd9063d628aa4/docker-entrypoint.sh#L25-L41

Nextcloud uses the session handling provided by PHP. You can configure PHP to use Redis as session handler. That's already happening for the docker image. 

https://github.com/zorn-v/nextcloud-social-login/blob/5b0f0951eb1cb44029c22c77953b8d5c039dd418/3rdparty/hybridauth/hybridauth/src/Adapter/OAuth2.php#L385-L388

Seems to be the origin of the error message. The app seems to use the session to store such data. Probably not bad to triage this issue first with https://github.com/zorn-v/nextcloud-social-login to have some more insights what is going wrong.

**Comment by krakazyabra** [comment]
Hi, @kesselb 

I added environments to my deployment
```yaml
        env:
          - name: REDIS_HOST
            value: "redis-nextcloud-master"
          - name: REDIS_HOST_PASSWORD
            value: ""
```
And everything works perfect. thank you for your attention.
