### ISSUE TITLE
contact button in top bar: clicking on email does not open mailto: link

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#19750]
### Steps to reproduce
1. in the top right, click on the contacts symbol
2. click on the mail symbol of a contact or nextcloud user
3. the popup with the email address stays floating, no matter where you click on the page. Only reloading or changing to a different app makes it go away

### Expected behaviour
Treat it as a mailto: link (I have set my browser to open mailto: links with my mailprovider. It works with mailto: links on other websites but not here)

### Server configuration

<details>
Operating system: Linux 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64

Webserver: nginx/1.14.0 (fpm-fcgi)

Database: mysql 5.7.27

PHP version: 7.2.24-0ubuntu0.18.04.1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 18.0.1 - 18.0.1.3

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - calendar: 2.0.1
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - data_request: 1.5.0
 - dav: 1.14.0
 - deck: 0.8.0
 - encryption: 2.6.0
 - external: 3.5.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_linkeditor: 1.0.11
 - files_pdfviewer: 1.7.0
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - forms: 1.1.0
 - impersonate: 1.5.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.1.3
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - polls: 1.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - ransomware_protection: 1.6.0
 - recommendations: 0.6.0
 - richdocuments: 3.5.2
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.5
 - support: 1.1.0
 - survey_client: 1.6.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - files_external
 - files_frommail
 - systemtags
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.demokratische-schule-x.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.demokratische-schule-x.de",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "theme": "",
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "loglevel": 2,
    "skeletondirectory": "",
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}

</details>

External storages: files_external is disabled

Encryption: yes

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:73.0) Gecko/20100101 Firefox/73.0
</details>

**Comment by kesselb** [comment]
![Peek 2020-03-03 09-47](https://user-images.githubusercontent.com/3902676/75758245-12019e80-5d34-11ea-99e3-9e938e441eff.gif)

I'm not able to reproduce with https://try.nextcloud.com.

**Comment by acs-ferreira** [comment]
@kesselb did you click on the icon ?

Also test with the address 'very.long.mail.address.to.reproduce@gmail.com'

**Able to reproduce it here, NC 18.0.1**

**Comment by kesselb** [comment]
I did. It opens a dialog to pick a registered mailto: protocol handler.

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by tcitworld** [comment]
Looks like an issue with the tooltip position when it's too big.

**Comment by alexanderdd** [comment]
Yep, works as expected in NC  24.0.10
