### ISSUE TITLE
Calender app surprisingly cancels meeting and sends cancellation messages to meeting participants

### ISSUE THREAD

**Issue by herrep** [nextcloud/server#19757]
When creating calendar entries with participants, I encounter a weird reaction of the calender app that automatically sends cancellation messages to the participants although the organizer of the meeting does not even touch the calender entry after creation.

### Steps to reproduce
1. Create a calender entry
2. Add at least one email address of a meeting participant
3. Participant receives invitation
4. Later onwards, about one day later, the system automatically sends a meeting cancellation message ("Cancelled") to all participants except for the organizer of the meeting. The cancellation message states that the meeting has been cancelled by the meeting organizer.

### Expected behaviour
I expect that a cancellation message is only sent if the meeting organizer proactively cancels the meeting without any automatic behaviour of the calender app.

### Actual behaviour
For an unknown reason, the calendar app sends a cancellation message in case of meetings with at least one participant besides the meeting organizer.

### Calendar app
**Calendar app version:** 2.0.1

### Server configuration

**Operating system**: Ubuntu 18.04.4 LTS

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.14 (7.3.14-6+ubuntu18.04.1+deb.sury.org+1)

**Nextcloud Version:** 17.0.3

**Updated from an older installed version or fresh install:** older version

**List of activated apps:**

```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - audioplayer: 2.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.1
  - camerarawpreviews: 0.7.3
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.1.8
  - dav: 1.13.0
  - dicomviewer: 1.2.1
  - dropit: 0.3.0
  - emlviewer: 0.0.5
  - event_update_notification: 1.0.1
  - extract: 1.2.3
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_antivirus: 2.2.1
  - files_downloadactivity: 1.6.0
  - files_external: 1.8.0
  - files_fulltextsearch: 1.3.6
  - files_fulltextsearch_tesseract: 1.3.2
  - files_mindmap: 0.0.17
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - fulltextsearch: 1.3.8
  - fulltextsearch_elasticsearch: 1.4.1
  - gallery: 18.4.0
  - geoblocker: 0.0.2
  - groupfolders: 5.0.5
  - guests: 1.3.1
  - impersonate: 1.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.1.2
  - maps: 0.1.4
  - metadata: 0.11.1
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - passwords: 2020.2.1
  - phonetrack: 0.6.2
  - provisioning_api: 1.7.0
  - ransomware_protection: 1.5.1
  - recommendations: 0.5.0
  - richdocuments: 3.5.2
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - spreed: 7.0.2
  - support: 1.0.1
  - suspicious_login: 3.1.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_gateway: 0.15.1
  - updatenotification: 1.7.0
  - uploaddetails: 0.1.2
  - user_ldap: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - bookmarks_fulltextsearch
  - encryption
  - firstrunwizard
  - ldap_write_support
  - privacy
  - sharingpath
  - survey_client
```

**Nextcloud configuration:**

```
I{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.3.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": ***REMOVED SENSITIVE VALUE***,
            "timeout": 0
        },
        "memcache.distributed": "\\OC\\Memcache\\Memcached",
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "maintenance": false,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "loglevel": 2,
        "mysql.utf8mb4": true,
        "data-fingerprint": "***REMOVED SENSITIVE VALUE***",
        "app_install_overwrite": [
            "calendar",
            "mail",
            "spreed",
            "bookmarks_fulltextsearch"
        ],
        "mail_sendmailmode": "pipe",
        "blacklisted_files": [],
        "updater.release.channel": "stable",
        "default_language": "de",
        "default_locale": "de_DE"
    }
}
```
#### Log file (data/nextcloud.log)
The Nextcloud log file is silent about issuing a cancellation message.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by herrep** [comment]
Tested again with Nextcloud 20.0.9. Issue not longer reproducable.

**Comment by ImAGitHubUser** [comment]
This exact scenario is happening to me in NC 25.0.6 with Calendar 4.3.3.

The scenario the OP describes occurs:

1) invite sent with multiple invitees.
2) calendar item remains intact
3) If one invitee accepts the invite using the traditional* calendar "accept meeting", the meeting will be cancelled for all invitees, except the organizer.

* what I mean here is that if the user accepts the invite via Outlook or another mail client (away from nextcloud) that can interpret ics files and respond accordingly, it appears to cancel the invite.

**Comment by miaulalala** [comment]
> This exact scenario is happening to me in NC 25.0.6 with Calendar 4.3.3.
> 
> The scenario the OP describes occurs:
> 
> 1. invite sent with multiple invitees.
> 2. calendar item remains intact
> 3. If one invitee accepts the invite using the traditional* calendar "accept meeting", the meeting will be cancelled for all invitees, except the organizer.
> 
> * what I mean here is that if the user accepts the invite via Outlook or another mail client (away from nextcloud) that can interpret ics files and respond accordingly, it appears to cancel the invite.

Are you able to observe anything in the logs? Or possibly the PUT request that happens?

**Comment by tom-ch1** [comment]
I am also hit by this bug, which renders event-scheduling

- Nextcloud Hub 6 (27.1.10)
- Calendar App (4.7.4)
- On my mobile, I use
  - [Business Calendar App](https://play.google.com/store/apps/details?id=com.appgenix.bizcal&hl=en) 
  - [Davx5](https://www.davx5.com/)
- The recipients don't have a nextcloud account and probably use Outlook to accept the invitation

Note:
- Accepting or rejecting the event is sent to my email address, nextcloud does not get any information about that
- Accepting using the web link only worked after I made sure all users had unique e-mail addresses (https://github.com/nextcloud/calendar/issues/6071)

**Comment by tom-ch1** [comment]
I think I have a lead: I use the CalDavSynchronizer plugin for outlook on my business-computer. This user is also one of the invitees. I saw the following log entry in nextcloud log just before receiving the event cancellation:

`
{"reqId":"ImXQQi7jdGrC5ITpV8hV","level":1,"time":"2024-06-16T15:29:14+00:00","remoteAddr":"77.57.35.108","user":"tom","app":"contactsinteraction","method":"PUT","url":"/remo
te.php/dav/calendars/tom/tom_edu/38c10736-0c48-462b-9b47-2db46debf94f.ics","message":"Ignoring contact interaction with self","userAgent":"CalDavSynchronizer/4.4","version":
"27.1.10.2","data":{"app":"contactsinteraction"}}
`
So it might be that my caldav synchronizer somehow triggers the cancellation (which might still a bug, because the synchronizer does synchronize the event to my outlook calendar)

**Comment by ImAGitHubUser** [comment]
Interesting observation.

I use the CalDavSync for outlook too.

This occurs very infrequently for me. But next time it occurs, I will check the logs.
