### ISSUE TITLE
Spinner in wrong position when deleting multiple users

### ISSUE THREAD

**Issue by rubo77** [nextcloud/server#19765]
### Steps to reproduce
1. go to user administration
2. delete a user
3. delete a second user before the first is completely processed

### Expected behaviour
There should be spinner in the row, which user is going to be deleted. Once a user in the rows above is removed from the list, the spinner should move up with the row it is currently in.

### Actual behaviour
the spinner stays in the row it was first occurring, even after the update of the page, where the first user was successfully removed. It continues to spin in the original row.

### Server configuration
docker ccontainer on debian
NC 18.0.1 and older

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by rubo77** [comment]
it is hard to test, if I delete one it is immediately deleted now, and I cannot see the spinner at all

**Comment by szaimen** [comment]
That sounds like we made some improvements in this regard. :)
Are you okay if I close this issue then?

**Comment by rubo77** [comment]
I tested it in chrome, there you can set a custom throttle of 1kbit and 1000ms delay.

it worked fine now
