### ISSUE TITLE
Unable to edit admin's quota and groups

### ISSUE THREAD

**Issue by dirdi** [nextcloud/server#19760]
### Steps to reproduce
1. Login using an admin account
2. Go to Settings -> Users
3. Try to add / remove Admin account to / from group or change its quota

### Expected behaviour
Admin accounts should be able to change their quota and add / remove themselves to/from groups, but not be able to remove themselves from admin group.

### Actual behaviour
Edit option is missing for admin accounts:

![Screenshot](https://help.nextcloud.com/uploads/default/original/3X/7/5/75ec046bec36f6cde238099691a0dcbbc168017c.png)

Screenshot taken from HanZ92's [forums post](https://help.nextcloud.com/t/cant-edit-own-account-under-users-including-admin/71915/7).

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2.4.38

**Database:** MariaDB 10.3.22

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** ZIP archive

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 73.0.1 (64-bit)

**Operating system:** Debian 11

**Comment by kesselb** [comment]
Thanks for taking the time to report a issue :+1: Please use the search to look for similar issues :mag:

**Comment by tflidd** [comment]
It seems to be this issue: https://github.com/nextcloud/server/issues/19004
However; from the title it's not clear, rather further down in the comments:
https://github.com/nextcloud/server/issues/19004#issuecomment-578522441

@dirdi Sorry that I said to open an issue. I didn't find anything on the first run because it wasn't directly linked to quotas.

**Comment by JimmyKater** [comment]
@tflidd @dirdi 
that seems to go back to #18555 even.

@kesselb 
so great that you're on it and trying to resolve it. but as it wasn't easy to find it would have been nice if you would have mentioned the original issue within your comment. 
thank you though

**Comment by dirdi** [comment]
@tflidd: Don't worry! Since you urged us to open a bug report, I was just astounded that it was closed immediately - but it's okay ;D

However, I was able to remove the quota for my admin account by manipulating the `oc_preferences table` using phpMyAdmin:
![2020-03-03-220250_774x228_scrot](https://user-images.githubusercontent.com/7914030/75819343-d0580e80-5d9a-11ea-8540-d4b577bcfaca.png)

Maybe this workaround is helpful to others, too.

**Comment by MatthlK** [comment]
Updated to 18.0.3 yesterday. Still can't edit my (admins) group membership in user management. Is a fix planned? Sorry i post in multiple threads. Don't know which one active and confused everywhere it reads "closed" but it isn't?!

**Comment by dirdi** [comment]
This bug report was closed because it was a duplicate of #19004. Please continue over there.
