### ISSUE TITLE
[feature-request] Public Upload - create folder per upload

### ISSUE THREAD

**Issue by Uwe-MrT** [nextcloud/server#19776]
is it possible to integrate a function "ask uploaders for a name of the upload and create an folder in public uploads with Date + foldername" ?
as example "Insert Name for your Uploaded files"
the uploader insert "Photos"
The Public Upload App creates an Folder "public-upload/2020-03-03_12:30 Photos" and put the uploaded Files in this Folder. 

The Date/Time is because if some other insert the same name for a folder...

**Comment by szaimen** [comment]
cc @nextcloud/designers for some ideas/mockups how this could work
