### ISSUE TITLE
Anbox no linux 

### ISSUE THREAD

**Issue by FighttoSurvivor** [nextcloud/server#19775]
Estou tendo muita dificuldade para executar aplicativos no linux é um sistema muito novo para mim que uso windows 20 anos e preciso para utilizar aplicativos basicos, sou tao leigo que nao sei executar um arquivo conpactado tudo que faço é somente pelo terminal seguindo tutoriais simples

**Comment by kesselb** [comment]
Please ask your question at https://help.nextcloud.com. GitHub is for bugs and feature request. Thanks.
