### ISSUE TITLE
Problem with Nextcloud 18 upgrade

### ISSUE THREAD

**Issue by carminerodio86** [nextcloud/server#19771]
Preparazione dell'aggiornamento

Imposta il livello del log per il debug

Modalità di manutenzione attivata

Fase di riparazione: Repair MySQL collation

Informazioni di riparazione: All tables already have the correct collation -> nothing to do

Fase di riparazione: Repair SQLite autoincrement

Fase di riparazione: Copy data from accounts table when migrating from ownCloud

Fase di riparazione: Drop account terms table when migrating from ownCloud

Aggiornamento schema database

Database aggiornato

Fase di riparazione: Populating added database structures for workflows

Doctrine\DBAL\Exception\TableNotFoundException: An exception occurred while executing 'SELECT `o`.`id` FROM `oc_flow_operations` `o` LEFT JOIN `oc_flow_operations_scope` `s` ON `o`.`id` = `s`.`operation_id` WHERE `s`.`operation_id` IS NULL': SQLSTATE[42S02]: Base table or view not found: 1146 Table 'nextcloud.oc_flow_operations_scope' doesn't exist

L'aggiornamento non è riuscito. Segna

**Comment by kesselb** [comment]
Thanks for reporting a problem :+1: 

Check this https://github.com/nextcloud/server/issues/18265 issue for more details.
