### ISSUE TITLE
Changing the display name does not update the placeholder avatar letters

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19788]
### Steps to reproduce
1. Login and check your placeholder avatar
2. Go to personal settings and change your name to start with different characters

### Expected behaviour
The avatar should reflect the name change

### Actual behaviour
The avatar is untouched

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by nickvergessen** [comment]
Working in the meantime
