### ISSUE TITLE
Initial share expiration date not written to DB

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#19786]
### Steps to reproduce
1. make sure _Settings > Sharing > Set default expiration date for shares_ is **not** activated
2. browse to a file or folder
3. create a share (this report applies for email shares, public shares, user shares and group shares)
4. open the share's ... menu
5. click _Set expiration date_

### Expected behaviour
- The first possible expiration date is auto-entered into the date field below
- That date is written into the database

### Actual behaviour
- Today's date (which is besides an invalid value) is auto-entered into the date field
- Nothing is written into oc_share.expiration

tested with NC 18.0.1, 18.0.0 and 16.0.5

**Comment by wiswedel** [comment]
Issue still exists with Nextcloud 19 and 20.

Thinking of it, this is even a security risk: The sharing user is in good faith that their share will auto-expire. However the share remains exposed until the end of all time.

**Comment by PVince81** [comment]
still happening on master.
indeed, even closing the dropdown doesn't save anything and reopening shows today's date

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!
