### ISSUE TITLE
Favorite handling fails for folders not in the filelist

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#19789]
### Steps to reproduce
1. Create a folder
2. Navigate into the folder
3. Open the sidebar via the share icon in the breadcrumb
4. Click on the favorite icon

### Expected behaviour
Works :star: 

### Actual behaviour
Works in the background, but the UI shows an error: `Unable to change the favourite state of the file`

The problem is `OCA.Files.App.fileList.getModelForFile` can not find the file and therefor continues with null, causing the following error in the console:
>  Unable to change favourite state TypeError: "fileInfoModel is null"

cc @skjnldsv

**Comment by skjnldsv** [comment]
Stupid legacy code :p

**Comment by nickvergessen** [comment]
It could also be fixed by reducing the scope of the catch to the actual axios execution

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by nickvergessen** [comment]
Also on master
