### ISSUE TITLE
Nextcloud installation proxysql/galera as root

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#19792]
Hi when we want install nextcloud on galera/proxysql achitecture as root.
Nextcloud is creating other user to protect root credential.
But when you install nextcloud with proxysql.
Nextcloud is creating user on galera cluster but not on proxysql. 
That mean the installation did not work. 

Best regards

**Comment by kesselb** [comment]
And what is the reason for you to report that as bug to Nextcloud?

If your setup requires a special configuration create the user (for galera and proxysql) as part of your deployment and make sure that the user has no rights to create another user / database. In that case Nextcloud will use the provided credentials.

Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers. You can find help debugging your system on our home user forums: https://help.nextcloud.com.

**Comment by oparoz** [comment]
> And what is the reason for you to report that as bug to Nextcloud?

I've asked him to do so to see if there was something we could improve here, probably in our documentation.

I'll get back to you as soon as I have more information.

**Comment by kesselb** [comment]
All right. ProxySQL is transparent for the application. As per https://github.com/sysown/proxysql/wiki/Users-configuration ProxySQL uses a different syntax to create users. Also creating a user seems to be done via a admin interface. I would suggest to create a user with limited permissions as part of the deployment. Don't forget to ping `@nextcloud/server-triage` if you have more information ;)

**Comment by tanguy-opendsi** [comment]
@kesselb it's just a little bug but it's a bug and in your configuration i did't see any notes talking about "nextcloud is creating user when using root privilèges" 
I know this is security feature .
But if someone want use root (i'm totaly agree with your security code ) he will get a bug.

**Comment by szaimen** [comment]
I am closing this as there seems to be few interest to implement this.
Please reopen if you still want to implement it.
