### ISSUE TITLE
Need a nice app icon for share by mail

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#1979]
The "share by mail" is a new share provider which allows you to directly send a personalized link to a give email address. This all will be shipped with Nextcloud 11 and needs a nice app icon.

app: https://github.com/nextcloud/server/tree/master/apps/sharebymail

cc @nextcloud/designers

**Comment by Espina2** [comment]
@shiessle can you add a screenshot for we could see where it will be placed the icon?

**Comment by jancborchardt** [comment]
@schiessle should be the same icon as for Sharing, to keep it under the same umbrella.

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/2000
