### ISSUE TITLE
Updater broken(?)

### ISSUE THREAD

**Issue by tchncs** [nextcloud/server#198]
Hi there, the Nextcloud `9.0.50 (stable)` updater is pretty sure that i am on the latest release.
I am sure its wrong.

I tested on an Arch server with PHP7 and Debian 8.5 with PHP5.6.
I didn't saw any issues in the log.

(both clouds are upgraded clouds from owncloud)

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by LukasReschke** [comment]
Updates are not enabled because the updater is broken. There is ongoing work to rewrite a new one.

**Comment by tchncs** [comment]
oh i thought it was just on oc 9.0.1 broken :/ good to know
