### ISSUE TITLE
Share by Link not working at all for one of my NC 18.0.1 instances

### ISSUE THREAD

**Issue by dj3mu** [nextcloud/server#19806]
### Steps to reproduce
1. Log into NC as any user (no matter whether Admin privs or not)
2. Choose any folder. Existing or new, filled or empty one, inside other share or outside. All doesn't matter.
3. Click "Share" symbol
4. Click "+" symbol for "Share link" (Link teilen)
5. Copy the URL (e.g. click "Copy to clipboard")
6. Open a different browser or a new private tab and paste the link of point 5
7. Try to modify any settings of the link. UI behaves just like normal.

The issue is reproducible on one of the three NC instances that I maintain. All on same SW configuration (one even on the same server). But slightly different NC configuration.

Main difference (but not sure if related): The **non**-working instance is **not** using LDAP auth. The other two instance are using LDAP.

On request I can provide App list and other details of the working instances. But I don't want to "mess up" this initial report with it.

### Expected behaviour
At step 6: The link should be created and hence accesible via the provided "random" URL. The Link should be modifiable w/o error message. Folder should show up as "Shared".
At step 7: The link's setting should be modified.

### Actual behaviour
At step 6: NC just tells the link doesn't exist. Modifying the link brings up an error. After reload, the folder is not even marked as "Shared".
At step 7: An error popup appears in the right upper corner saying "Error updating the share".

### Server configuration

**Operating system:**
Ubuntu 18.04.4 LTS

**Web server:**
Self-built from sources including Modsecurity support.  
But also tested with Modsec completely disabled. Same behaviour. Also there's same Modsecurity config on the two working instance. And there's no error in the Modsecurity log file. So I'd say we can exclude Modsec for the being the root-cause.
```
nginx version: nginx/1.17.9
built by gcc 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
built with OpenSSL 1.1.1d  10 Sep 2019
TLS SNI support enabled
configure arguments: --user=www-data --group=www-data --with-threads --with-file-aio --with-http_ssl_module --with-http_v2_module --with-http_realip_module --with-http_addition_module --with-http_sub_module --with-http_dav_module --with-http_gunzip_module --with-http_gzip_static_module --with-http_auth_request_module --with-http_random_index_module --with-http_stub_status_module --with-compat --with-openssl=/usr/local/src/openssl --add-dynamic-module=../ModSecurity-nginx
```

**Database:**
Distro version installed with APT.
`mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**PHP version:**
Distro version installed with APT.  
Using php7.2-fpm.
```
PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.3, Copyright (c) 1999-2018, by Zend Technologies
```

**Nextcloud version:** (see Nextcloud admin page)
18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from previous versions.

**Where did you install Nextcloud from:**
Tarball. Years ago (cannot tell since which NC version).  
Since then only updates via Updater App. Database index updates performed at command line when requested by "Admin->Overview" page.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - gpxpod: 4.1.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.3
  - notes: 3.1.5
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.5
  - support: 1.1.0
  - systemtags: 1.8.0
  - tasks: 0.11.3
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_admin: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.2
  - twofactor_u2f: 5.0.2
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - end_to_end_encryption
  - federation
  - files_external
  - files_videoplayer
  - firstrunwizard
  - nextcloud_announcements
  - ransomware_protection
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "localhost",
            "***REMOVED MORE SENSITIVE VALUES: All IPs (incl. IPv6) and the hostname of the instance***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE: FULL HTTPS URL OF THE INSTANCE***",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "18.0.1.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "forcessl": true,
        "overwritewebroot": "\/",
        "filelocking.enabled": "true",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 1
        },
        "forceSSLforSubdomains": true,
        "session_lifetime": 691200,
        "session_keepalive": true,
        "log_rotate_size": 10485760,
        "trashbin_retention_obligation": "auto, 60",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "auth.bruteforce.protection.enabled": true,
        "appstore.experimental.enabled": true,
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "tls",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mysql.utf8mb4": true,
        "tempdirectory": "\/var\/tmp"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No. On none of the instances.

**Are you using encryption:** yes/no
No. On none of the instance.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No. Not on the failing instance.

### Client configuration
**Browser:**
Rerpducible with
* FF 73.0.1 (Win10, 64bit)
* Chrome 80.0.3987.132 (Win10, 64bit)
* Nextcloud Windows Client App v. 2.6.2stable-Win64 (build 20191224) when using the "Share with Nextcloud" Explorer context menu

**Operating system:**
Win10-64

#### Web server error log
<details>
<summary>Web server error log</summary>

Nothing written to the web server error log.

```
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

Nothing written to the NC log. Surely the log contains data but last entry was 3 days ago. An no new entry gets written reproducing the steps above.
```
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
09:16:17.122 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
09:16:18.909 showDetailsView is deprecated! Use OCA.Files.Sidebar.activeTab. It will be removed in nextcloud 20. merged-index.js:4452:12
09:16:19.096 The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
09:16:19.131 The escapeHTML library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
09:16:19.143 The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
09:16:19.184 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
09:16:19.256 The select2 library is deprecated! It will be removed in nextcloud 19. 2 main.js:1082:57
09:16:19.656 recommendations 
Array(5) [ {…}, {…}, {…}, {…}, {…} ]
files_sharing_tab.js:1382:7192
09:16:21.166 Link share created 
Object { … }
files_sharing_tab.js:1403:13924
09:16:21.171 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
09:16:21.189
Object { action: "copy", text: "https://***REMOVED SENSITIVE VALUE***/s/af6Rb6QYqzQc8Xp", trigger: button, clearSelection: value() }
files_sharing_tab.js:1403:15879
09:16:21.198 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
09:16:21.182 document.execCommand('cut'/'copy') wurde abgelehnt, weil es nicht von innerhalb einer kurz dauernden benutzergenerierten Ereignisbehandlung aufgerufen wurde. sidebar.js:257:6008
09:16:23.198 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 main.js:1082:57
09:16:23.869 Error while updating share Error: "Request failed with status code 404"
    exports https://***REMOVED SENSITIVE VALUE***/apps/files_sharing/js/dist/files_sharing_tab.js?v=411097bd-13:379
    exports https://***REMOVED SENSITIVE VALUE***/apps/files_sharing/js/dist/files_sharing_tab.js?v=411097bd-13:699
    onreadystatechange https://***REMOVED SENSITIVE VALUE***/apps/files_sharing/js/dist/files_sharing_tab.js?v=411097bd-13:379
files_sharing_tab.js:1382:1991
09:16:25.200 moment is deprecated: please ship your own, this will be removed in Nextcloud 20 3 main.js:1082:57
```
</details>

**Comment by dj3mu** [comment]
### I finally figured out which configuration is causing this:

![grafik](https://user-images.githubusercontent.com/41773089/77685458-c2fa0280-6f9b-11ea-9917-02fd8be5b90f.png)

In the sharing dialog I had enabled "Set default expiration date". In the corresponding input field for the "Expire after" I was fine with the 7 days shown there.

**So I didn't change it. And that was my mistake !!**

The "7" in the field is slightly greyed out and effectively NOT set.

So, when creating a new share it effectively enables the "Expiration Date" but cannot calculate the date.

Simply typing the number of "7" into the field solves the problem:

![grafik](https://user-images.githubusercontent.com/41773089/77686537-65ff4c00-6f9d-11ea-9a9e-2bbbe7d17acc.png)

Yes, in this second screenshot, the value has been entered. In the first one not!  
As you can see, it's almost invisible whether the number has been entered or not.  
#### The field should definitely be highlighted with something better visible as long as the value is missing.

**Comment by kesselb** [comment]
cc @jancborchardt is removing the placeholder a valid solution?

**Comment by dj3mu** [comment]
> is removing the placeholder a valid solution?

Maybe for this field yes.
But from my side I'd say NC is currently a bit lazy about invalid form content. I tried, for example, the E-Mail-Server configuration dialog and just removed the server name at all:
![grafik](https://user-images.githubusercontent.com/41773089/77730437-12bee500-7001-11ea-938c-283a9c9aedeb.png)
While for this field it's pretty clear that it's empty and not set, I'm really surprised that NC actually saves the invalid data (see green "Saved" banner).  
This will later on surely result in possibly hard to find (at least for "normal users") runtime errors, won't it?

**Comment by jancborchardt** [comment]
> The "7" in the field is slightly greyed out and effectively NOT set.

This is the issue. The "7" being set as placeholder should of course mean that it is taken as the default value. :)

**Comment by dj3mu** [comment]
> Should this issue still be open?

Not sure who is intended to be adressed by this question.

I've verified in NC 19.0.2 and the place-holder "7" is still present. Didn't verify if the behaviour is still the same. 
But maybe a merge to stable is still open for this.

**Comment by skjnldsv** [comment]
Yes, this is the default if left empty
https://github.com/nextcloud/server/blob/28c57004dda25f9d78a9679237d1ec747c1d60b0/lib/private/Share20/Manager.php#L1756
https://github.com/nextcloud/server/blob/28c57004dda25f9d78a9679237d1ec747c1d60b0/lib/private/Share20/Manager.php#L1784
