### ISSUE TITLE
Wrong Max Execution Time in Serverinfo Page

### ISSUE THREAD

**Issue by thrdroom** [nextcloud/server#1980]
### Steps to reproduce
1. Manual Update from 10.0.0 to 10.0.1
2. Check Max Execution Time in Serverinfo Page at http://CLOUD/index.php/settings/admin/serverinfo > Max Execution Time is: 3600
3. $ nano /etc/php/7.0/apache2/php.ini
4. change the value of max_execution_time to 1888
5. $ service apache2 restart
6. Check Max Execution Time in Serverinfo Page at http://CLOUD/index.php/settings/admin/serverinfo > Max Execution Time is: 3600
7. phpinfo(); shows correct Max Execution Time 1888

### Expected behaviour
Serverinfo Page should list the correct Max Execution Time as set in php.ini

### Actual behaviour
Serverinfo Page shows 3600 as Max Execution Time

### Server configuration
**Operating system**: Debian 8.6
**Web server:** Apache 2
**Database:** Mysql 5.7.16
**PHP version:** PHP 7.0.12
**Nextcloud version:** (see Nextcloud admin page) 10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 10.0.0
**Where did you install Nextcloud from:** nextcloud-10.0.1.tar.bz2

**Comment by nickvergessen** [comment]
Can you report that in the repo of the app?
https://github.com/nextcloud/serverinfo/issues
