### ISSUE TITLE
Allow to disable user flows

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#19804]
As an administrator it should be possible to disable user flows since they can have quite some impact on the performance of a system and you might not want to give users the ability to define their own flows while still making use of the administrator level ones like file_accesscontrol/automated tagging.

cc @blizzz

**Comment by juliushaertl** [comment]
I guess just having an app config value that can be set would be fine, no need for a UI to configure this from my point of view.

**Comment by szaimen** [comment]
Isn't this already fixed with #19930 ? 
So why is this still open?

**Comment by juliushaertl** [comment]
Yes, apparently "implements" didn't trigger the auto close :)
