### ISSUE TITLE
Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#19814]
- NC 17.0.3

```
[index] Error: Exception: Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given,
called in /lib/private/AppFramework/Http/Dispatcher.php on line 170 at <<closure>>

0. /lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controller\LoginController {}, "tryLogin")
1. /lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OC\\Core\\Controller\\LoginController", "tryLogin", OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "core.login.tryLogin"})
3. /lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "core.login.tryLogin"})
4. /lib/base.php line 997
   OC\Route\Router->match("/login")
5. /index.php line 42
   OC::handleRequest()

by TypeError: Argument 1 passed to OC\Core\Controller\LoginController::tryLogin() must be of the type string, null given,
called in /lib/private/AppFramework/Http/Dispatcher.php on line 170
    
0.  /lib/private/AppFramework/Http/Dispatcher.php - line 170:
    OC\Core\Controller\LoginController->tryLogin("*** sensiti ... *")
1.  /lib/private/AppFramework/Http/Dispatcher.php - line 99:
    OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Cont ... {}, "tryLogin")
2.  /lib/private/AppFramework/App.php - line 126:
    OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Cont ... {}, "tryLogin")
3.  /lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:
    OC\AppFramework\App::main("OC\\Core\\C ... r", "tryLogin", OC\AppFramew ... {}, { _route: "c ... "})
    <<closure>>
4.  OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "c ... "})
    /lib/private/Route/Router.php - line 297:
    call_user_func(OC\AppFramew ... {}, { _route: "c ... "})
5.  /lib/base.php - line 997:
    OC\Route\Router->match("/login")
6.  /index.php - line 42:
    OC::handleRequest()
```

**Comment by kesselb** [comment]
You know that triaging issues without the [issue template ](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md) is much harder ;)

I recall some other reports with that error. Still think that's some kind of configuration problem. The first argument for `tryLogin` is the username. Not sure how to end up with a login request without a username. 

Probably a good place to start is to check the post request on login with the network inspector and see if user, password, redirect_url, timezone and timezone_offset are present as form data.

**Comment by acs-ferreira** [comment]
I know it but i can't reproduce it, even inspecting the POST.
Closing for now.

**Comment by CleanAir777** [comment]
I have the same issue, using NC22.0.0. The SAML trace shows that the fields you mention are present in te POST. Strange thing is: This problem shows up in Edge (91.0.864.70) and Firefox (89.0.2), but not in Vivaldi browser (4.0.2312.41).

**Comment by diafoirus** [comment]
Hello, I have the same issue (NC 21.0.3). This problem shows up with Chrome (91.0.4472.164) , Firefox (90.0.1), but not in Vivaldi browser (4.0.2312.41)

**Comment by idmacdonald** [comment]
I have this problem with a NextCloud 21.0.3 installation running on php 7.3.29. The problem seems to only affect certain users. After seeing this, I'll have to check and see if there is a correlation with the browser being used.

**Comment by mig5** [comment]
I am also seeing this issue with just one user since the upgrade to NextCloud 21.0.3

The user has tried Chrome, Edge, Firefox 90, but gets this same error message.

What is weird is that if I reset their password, I can login as that user on Firefox 90 on macOS, and on Firefox 78 on Linux, without any problem at all.

```
{"reqId":"bSRE2Dv7zFUrLZGg92H1","level":3,"time":"2021-07-22T12:19:31+00:00","remoteAddr":"XX.XX.XX.XX","user":"--","app":"index","method":"POST","url":"/login","message":{"Exception":"Exception","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 218","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Core\\Controller\\LoginController::tryLogin() must be of the type string, null given, called in /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 218","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"tryLogin","class":"OC\\Core\\Controller\\LoginController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/var/www/html/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OC\\Core\\Controller\\LoginController"},"tryLogin"]},{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OC\\Core\\Controller\\LoginController","tryLogin",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"_route":"core.login.tryLogin"}]},{"file":"/var/www/html/nextcloud/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/login"]},{"file":"/var/www/html/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/core/Controller/LoginController.php","Line":290},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36","version":"21.0.3.1"}
```

**Comment by mig5** [comment]
I can reproduce the issue if I edit my browser's request to send either no payload data at all, or, say, no `&password=xxxxxxxxxxx` or no `user=xxxx` (e.g in Developer tools in Firefox), and then resend the request. If either the username or password is missing in the POST payload (or both), the 500 error with the tryLogin() exception occurs.

So it is as if, for some browsers/operating systems, the submission of the Login form, is somehow not sending the username/password in the payload.

The fact that at least 3 or more people here have suddenly reported this in 21.0.3 or 22, and given the wide variety of browsers that do or don't work, suggests it's a recent regression..

**Comment by idmacdonald** [comment]
Hi,

I can confirm that this error occurs in Edge 91.0.864.71 and in Firefox 89.0 on Windows 10.

For the same user, though, there is no problem when using Chrome 91.0.4472.164 on Andriod 10.

This particular NextCloud install has many login usernames that include spaces. That makes me wonder whether those spaces in the usernames are being mangled somehow, or are somehow leading to a blank username being passed to NextCloud.

**Comment by CleanAir777** [comment]
Strange, but true. WHen I just uninstalled BitDefender, I could login to NextCloud again, both with Edge and Firefox.

**Comment by Kugelkoordinator** [comment]
I had the same issue with Bitdefender. I could resolve it by adding my Nextcloud URL to the whitelist.

**Comment by kesselb** [comment]
> Hi, 
> 
> we (the community developing Nextcloud) having some reports on GitHub (https://github.com/nextcloud/server/issues/19814) that login to Nextcloud with Firefox, Chrome or Edge does not work when Bitdefender is installed. 
> 
> It seems that some Bitdefender products install a plugin for a browser and "protect" the user from malicious requests. For some reason username and password are removed from the login request done by Nextcloud. 
> 
> Could you share with us how to improve our login request - so that Bitdenfer does not classify it as mailcious anymore?
> 
> Please let me know if you have further questions. The easiest way to get in touch with the affected Bitdefender users is directly on GitHub (https://github.com/nextcloud/server/issues/19814). I don't use your product and cannot give you more information about the issue.
> 
> There is also a similar questions for other websites in your community: https://community.bitdefender.com/en/discussion/88583/bitdefender-is-blocking-access-to-websites-that-we-use-all-the-time
> 
> Regards

Opened a support ticket with Bitdefender. Ticket number is: 1006648408.

I suppose that Bitdefender installs a browser plugin and check the network requests for username and passwords. For some reason the plugin classifies the login request as evil and prevent "leaking" username and password. 

If anyone of you has some ideas please let us know ;)
