### ISSUE TITLE
Flow check for containing directory

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#19810]
For user flows it would be very useful to add a check that can verify if a file event was performed on a file inside of a given directory.

Basically what we have shown in the [mockups of the preannouncement](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/):

![image](https://user-images.githubusercontent.com/3404133/76070688-3c9e6200-5f95-11ea-860a-26343a66082b.png)

@blizzz I guess this only makes sense for user scope? I don't remember exactly how those were implemented, if we assume a flow operation is triggered on file change, will the flow be executed only for file changes by the user who has configured or also if someone else changes a shared file that is owned by the user?

**Comment by wiswedel** [comment]
> Basically what we have shown in the [mockups of the preannouncement](https://nextcloud.com/blog/nextcloud-flow-makes-it-easy-to-automate-actions-and-workflows/):

same for "Send an email" and "Notify me" - would be a huge benefit
cc @jancborchardt

**Comment by nickvergessen** [comment]
> I guess this only makes sense for user scope?

The thing is we tried to prevent this all the time, because if you have a share received and have that moved into the folder you want the rule to apply, it will not trigger. The rules are only executed on the storage of the actual owner. So this will lead to confusion on all ends all the time.

See https://docs.nextcloud.com/server/17/admin_manual/file_workflows/access_control.html#denying-access-to-folders

**Comment by martin-rueegg** [comment]
As per https://github.com/nextcloud/server/pull/23452#issuecomment-720610996 you can use a tag (aka File System Tag) on the containing folder.

**Comment by PVince81** [comment]
While using system tags would work for blocking just the folder, it doesn't look like it would allow to say something like "for every file uploaded into folders tagged as X run a script S" (using workflow_script for example).

Not sure if the script would run at all, maybe just at the time where the folder is created.
Would need another rule that says "if the contents of the folder tagged as X has changed, run the script S on the folder"

My use case is for processing pictures from instant upload for import like auto-rotate, see https://github.com/nextcloud/photos/issues/622

**Comment by wiswedel** [comment]
workflow_script doesn't work on folders: https://github.com/nextcloud/workflow_script/issues/26

**Comment by PVince81** [comment]
Even if it did, the bit that's missing is "trigger the action whenever something is happening **inside** the folder, not on the folder itself". Maybe it could be called "Parent is tagged with tag T" (or even "Any parent is tagged with tag T)

**Comment by nickvergessen** [comment]
So at least with autotagging the thing is triggered on updates as well. Not sure if it's also for the workflow_script, but if there is an update it also works because at least the mtime of the folder changes.

**Comment by wiswedel** [comment]
> Parent is tagged with tag T

Interestingly that does work with automated tagging: When file is changed and file system tag is tagged with <folderTag> then assign tag <fileTag>.
Then you can run the script on the <fileTag> tagged files.

**Comment by nickvergessen** [comment]
> Maybe it could be called "Parent is tagged with tag T" (or even "Any parent is tagged with tag T)

I'll leave this here:
https://docs.nextcloud.com/server/17/admin_manual/file_workflows/access_control.html#available-rules

> File collaborative tag: Either the **file itself, or any of the file owner’s parent folders** needs to be tagged with the tag.

**Comment by PVince81** [comment]
I guess we could change the text to make it more obvious within the UI that it is recursive.
I've also noted that it still says "system tag" there, which is the very old technical name, so we should also rename it to "collaborative tag".

**Comment by wiswedel** [comment]
> we should also rename it to "collaborative tag"

Why not only "Tag" after all? What's collaborative about them in the first place?

**Comment by PVince81** [comment]
"Collaborative tag" is the name that was given in the web UI a long time ago.
But it seems in some places it also says "Tags" so I guess that wording would work as well.

**Comment by szaimen** [comment]
So is this option feasible?

**Comment by RTechSn** [comment]
This shouldn't be closed.

**Comment by blizzz** [comment]
https://github.com/nextcloud/server/issues/19810#issuecomment-595692235 ff

**Comment by Denyerec** [comment]
Found this trying to make the Flow feature work for me - I need notifications if files are created in a specific folder, and found so far now way to accomplish this :(
