### ISSUE TITLE
Timestamp of config/config.php changed - updater.secret 

### ISSUE THREAD

**Issue by szepeviktor** [nextcloud/server#19828]
I've got [an alert](https://github.com/szepeviktor/debian-server-tools/blob/master/monitoring/siteprotection.sh) that the timestamp of `config/config.php` has just changed.

```diff
--- config.php  2020-01-22 12:57:58.835307349 +0000
+++ /home/nextcloud/website/code/config/config.php       2020-03-05 17:40:36.164510806 +0000
@@ -25,7 +25,6 @@
   'mail_smtphost' => 'localhost',
   'mail_smtpport' => '25',
   'maintenance' => false,
-  'updater.secret' => '$2y$10$*****',
   'theme' => '',
   'loglevel' => 2,
 );
```

Then I've done a diff with the backup and `updater.secret` was deleted from the config file.

It was during a `GET /cron.php` request.

- no upgrade was done
- no administration was done

Is it the result of normal operation of Nextcloud or a compromise?
Thank you!

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/apps/updatenotification/lib/ResetTokenBackgroundJob.php

There is a background job removing the `updater.secret` after 2 days. So that looks like a normal operation.

**Comment by szepeviktor** [comment]
Oh!!!
Thank you. :)
