### ISSUE TITLE
Select calendar on which "Accept" e-mail button creates the event

### ISSUE THREAD

**Issue by blacoste** [nextcloud/server#19826]
Let's consider two users are on the same Nextcloud instance. When one accepts from the other a Calendar meeting via "Accept" HTML e-mail button, it always creates the event on my "Personal" calendar and it cannot be changed. 

Maybe the solution would be:
1/ to let the user the ability to select a default calendar for meeting acceptance
2/ to allow the user to select the related calendar on the web page once he clicks on the "Accept" or "more button.

Today, if I accept via HTML I have then to move the event to the right Calendar.

Nextcloud version : 18.0.1

This is harcoded here: https://github.com/nextcloud/server/blob/master/apps/dav/lib/CalDAV/Schedule/Plugin.php#L275

**Comment by tcitworld** [comment]
Related to https://github.com/nextcloud/server/issues/3014, https://github.com/nextcloud/server/issues/10781 and could help https://github.com/nextcloud/calendar/issues/9

**Comment by tcitworld** [comment]
@georgehrke This would be a setting saved in `dav` that would populate `schedule-default-calendar-URL`, but would the UI be in Calendar or shall we finally introduce a groupware section in the NC personal settings ?

**Comment by georgehrke** [comment]
Kind of duplicate / heavily related to https://github.com/nextcloud/calendar/issues/1835#issuecomment-589257421

**Comment by georgehrke** [comment]
> shall we finally introduce a groupware section in the NC personal settings ?

I think we should put it into the calendar, and move settings to a popover like recently discussed.
Would you prefer a groupware section? I'm open for that as well

**Comment by tcitworld** [comment]
> I think we should put it into the calendar, and move settings to a popover like recently discussed.

For this specific issue and from a technical PoV I feel we shouldn't need the calendar app to pick a `dav` setting (even if nearly everyone has the Calendar app installed). At the same time it would feel odd to have *only* this setting in the groupware section, as I can't think of anything else right now.

(I also like the iOS way of putting every setting into a dedicated section and not in the app itself, but maybe people that are not used to it wouldn't find it easily. Also groupware isn't really an user-friendly term.)

**Comment by georgehrke** [comment]
> For this specific issue and from a technical PoV I feel we shouldn't need the calendar app to pick a dav setting (even if nearly everyone has the Calendar app installed). At the same time it would feel odd to have only this setting in the groupware section, as I can't think of anything else right now.

We already had a similar-ish problem with the "Enable birthday calendar" feature.
Theoretically it's possible that a user has deleted their birthday calendar via dav, but to restore it you have to use the calendar app, not the settings section.

While not strictly necessary, it's probably save to assume that 99% of users, who use CalDAV, also have the calendar app installed.

**Comment by tcitworld** [comment]
Okay, so let's have this in the calendar settings popup like discussed.

Back to the default calendar topic, should users be able to pick calendars shared with them as default calendars (probably not a good idea)?

**Comment by georgehrke** [comment]
No, they shouldn’t, since you also can’t send out invitations in shared calendars. :)

**Comment by blacoste** [comment]
I'm a bit confused about the current behavior. I may be missing something but here are my questions.

What if the invitation is sent by another Nextcloud instance (or not even Nextcloud) and I click on accept? So I guess that the event would not be created on none of my calendar and that I should have then used the ICS.

I think that depending on the origin of the sender (same instance or not) would result in different consequence (auto creation or not of the event) and it is a bad experience for the user... that will for sure make things difficult for him to understand when it is created or not.

Maybe on the HTML page it should be reminded to open the ICS or not depending on this situation.

**Comment by tcitworld** [comment]
@blacoste Providing the updated ics to the external user that confirmed their attendance is another issue.

@raimund-schluessler Just noticed the Tasks app already has a "default task list" option, are you interested in this ?

**Comment by raimund-schluessler** [comment]
Interesting to know, but I think you need to pick the default calendars individually for both apps, since one could select a calendar which does not allow to store VTODO or VEVENT, respectively.

**Comment by tcitworld** [comment]
@georgehrke Should we close here in favor of https://github.com/nextcloud/calendar/issues/1835 since the server part is done?
