### ISSUE TITLE
Issue with Installation

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#1983]
I have HostGator shared hosting, I have used both installation methods, uploading all the files manually and using the Shared Host Installer. In both circumstances I get the following error message:

`Warning: require_once(lib/base.php): failed to open stream: No such file or directory in /cloud/index.php on line 46

Fatal error: require_once(): Failed opening required 'lib/base.php' (include_path='.:/opt/php54/lib/php') in /cloud/index.php on line 46
`

The installation files have not been changed in anyway, they were uploaded just the way they were downloaded.

**Comment by LukasReschke** [comment]
Please open an issue at help.nextcloud.com. That seems more setup related.
