### ISSUE TITLE
Upgrade from 16.0.3 to 16.0.8 problem

### ISSUE THREAD

**Issue by radyphan** [nextcloud/server#19855]
Hi All,

I have some issue regarding uprade from version 16.0.3 to 16.0.8 on my nextcloud here is the issue bellow:
1. Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)

After check i got the message bellow:
Results
=======
- core
	- FILE_MISSING
		- core/skeleton/Documents/About.odt
		- core/skeleton/Documents/About.txt
		- core/skeleton/Documents/Nextcloud Flyer.pdf
		- core/skeleton/Photos/Coast.jpg
		- core/skeleton/Photos/Hummingbird.jpg
		- core/skeleton/Photos/Nextcloud Community.jpg
		- core/skeleton/Photos/Nut.jpg
	- EXTRA_FILE
		- ocs/.rnd
		- .rnd
		- index.html.1

2. The "Strict-Transport-Security" HTTP header is not set to at least "15552000" seconds. For enhanced security, it is recommended to enable HSTS as described in the security tips ↗.

Can anyone help me to fix this issue ? Really appreciated.

Thank you,
Rady

**Comment by acs-ferreira** [comment]
Hi there,

please refer to https://help.nextcloud.com/ for configuration issues and **use Git for code bugs only**.

In your case, these are warnings and not errors, so you Nextcloud should run smoothly, but you should take a look at https://docs.nextcloud.com/server/16/admin_manual/ as it contains all the informations needed (Upgrade & Troubleshoot sections).

Thanks 👍
