### ISSUE TITLE
Move to button label not updated after creating new folder

### ISSUE THREAD

**Issue by PriceChild** [nextcloud/server#19854]
### Steps to reproduce
1. In the files app, click the dots on an item
2. select "move or copy"
3. navigate to a second folder (important - this updates the blue button to "Move to `secondfolder`")
4. Create a third folder using the + button next to location breadcrumbs

### Expected behaviour
The blue button "Move to `secondfolder`" should be updated to use the name of the third folder.

### Actual behaviour
The blue button remains as "Move to `secondfolder`", referring to the folder you just created a new, third folder in. The third (empty) folder's items are shown.

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Nginx

**Database:** Mysql

**PHP version:** 7.2.24-0ubuntu0.18.04.3

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 15ish

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
NA
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
NA
```
</details>

**Are you using external storage, if yes which one:** NA

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** Noe

### Client configuration
**Browser:** Firefox 73.0.1

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
NA
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
NA
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
NA
```
</details>

**Comment by kesselb** [comment]
That sounds like https://github.com/nextcloud/server/issues/19718

**Comment by PriceChild** [comment]
Agreed, sorry I didn't find it.
