### ISSUE TITLE
strange behavior on filename "wp-config.php" 

### ISSUE THREAD

**Issue by zwotzie** [nextcloud/server#1985]
### Steps to reproduce
1. fresh installation of 10.0.1 on linux shared hoster with mysql 5.5 backend
2. create (+) new Text file named "wp-config.php"
3. you can do nothing with it, can't edit, delete, rename, sync it, sync breaks also

### Expected behaviour
just like every other Textfile

**Comment by zwotzie** [comment]
other combinations like wp-xyz.php or wp-config-xyz.php work without problems

**Comment by LukasReschke** [comment]
Please open an issue at help.nextcloud.com. That seems more setup related.
