### ISSUE TITLE
Developer tool / APP Checker...

### ISSUE THREAD

**Issue by noci2012** [nextcloud/server#19868]
**Disclaimer: I am NOT an experienced PHP programmer, I am trying to "repair" some old module that broke due to they maintainer giving up on fast API changes between 10-15 **

**Is your feature request related to a problem? Please describe.**
During development i had the problem of loading a Settings pagelet for an application.
The Personal Settings section did load and show and for some mysterious reason the Admin Settings did NOT show up. 
No errors visible, No logging visible, No HTTP / PHP-FPM visible problems.
After enabling debug in the config, ALL modules produce errors along explicitly loading OCA\AppInfo\Application... (also this module).  So at least it is recognized, still no error messages and no ADMIN pagelet.
After comparing a lot of other apps (and observing they are almost all written differently... in this aspect).  I just added a bunch of use OCP\.... (from another modules header) statements. 
From that moment on the Admin pagelet did show up.
So apparantly i was missing use statements. In this case after minimizing the needed changes was 
**use OCP\IL10N;**  due to the use of the argument IL10N.
The code checker has this rather unuseful remark:
Invalid appinfo.xml file found: Element 'admin': This element is not expected. Expected is one of ( admin-section, personal, personal-section ).
App is not compliant

(This message is always show irrespective if the modules Admin page is correct or not).

**Describe the solution you'd like**
A scanner tool that can verify an App on  consistency. If some types are used, warn for the uses that are missing. (no need to fix things in the source) warning should be sufficient.
The scanner can also be used to verify if API's and other constructs are used that are deprecated or are gone... 

**Describe alternatives you've considered**
I see no reasonable alternative.  Documentation that is more accessible on problems and issues etc. 

**Additional context**
A command line tool should be sufficient.

With debug enabled weir messages appear:
RuntimeException: App class OCA\LogReader\AppInfo\Application is not setup via query() but directly
(for EACH module that is active, so LogReader varies).

Another message on a standard module: (whole bunch of them).
Invalid characters passed for attempted conversion, these have been ignored at /home/xxx/nextcloud/nc18/3rdparty/nikic/php-parser/lib/PhpParser/Node/Scalar/String_.php#103

The app:check-code complains loudly about the vendor modules inside the default App.

**Comment by exussum12** [comment]
This has been fixed in PHP parser. Just needs an update

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by noci2012** [comment]
I' will close this as a gave up on nextcloud plugin development.
