### ISSUE TITLE
Theming app permission error, creating directory manually solved issue

### ISSUE THREAD

**Issue by benks-io** [nextcloud/server#19876]
### Steps to reproduce
1. install Version 17.0.3 with an installed theme in ~/themes/ and a separate data directory
2. install Theming App
3. open Theming App in configuration menu

With another instance with the very similar setup the problem did not occur.

### Expected behaviour
The directory should be created automatically. 

### Actual behaviour
Opening the Theming App shows an "Internal Server Error". The Logs showed:

[index] Error: OCP\Files\NotPermittedException: Could not create path at <<closure>>
[...] see below

Checking the owner and permissions for the Directory (Data/NC root) didn't show anything wrong.

/var/nextcloud/data/appdata_$MYINSTANCEID# ls -lisa
drwxr-xr-x 15 www-data www-data 4096 Feb  3 17:05 css

After creating the missing directory
  /var/nextcloud/data/appdata_$MYINSTANCEID/css/theming
the theming app could be opened without errors.

### Server configuration

**Operating system:** Debian Buster

**Web server:**  Apache

**PHP version:** PHP Apache Modul

**Nextcloud version:** 17.0.3.1
**Theming App:** 1.8.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - cloud_federation_api: 1.0.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - support: 1.0.1
  - text: 1.1.1
  - theming: 1.8.0
  - theming_customcss: 1.5.0
  - twofactor_backupcodes: 1.6.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - comments
  - encryption
  - files_external
  - files_pdfviewer
  - firstrunwizard
  - gallery
  - nextcloud_announcements
  - sharebymail
  - survey_client
  - systemtags
  - updatenotification
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

[index] Error: OCP\Files\NotPermittedException: Could not create path at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/SimpleFS/SimpleFolder.php line 83
    OC\Files\Node\Folder->newFile("4fda-e3a3-theming.css")
 1. /var/www/nextcloud/lib/private/Template/SCSSCacher.php line 311
    OC\Files\SimpleFS\SimpleFolder->newFile("4fda-e3a3-theming.css")
 2. /var/www/nextcloud/lib/private/Template/SCSSCacher.php line 181
    OC\Template\SCSSCacher->cache("/var/www/nextcloud/apps/theming/css", "4fda-e3a3-theming.css", "theming.scss", OC\Files\SimpleFS\SimpleFolder {}, "/apps/theming/css")
 3. /var/www/nextcloud/apps/theming/lib/Controller/ThemingController.php line 410
    OC\Template\SCSSCacher->process("/var/www/nextcloud/apps/theming", "css/theming.scss", "theming")
 4. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Theming\Controller\ThemingController->getStylesheet()
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Theming\Cont ... {}, "getStylesheet")
 6. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Theming\Cont ... {}, "getStylesheet")
 7. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Theming\\C ... r", "getStylesheet", OC\AppFramework\ ... {}, {_route: "theming.Theming.getStylesheet"})
 8. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "theming.Theming.getStylesheet"})
 9. /var/www/nextcloud/lib/private/Route/Router.php line 297
    undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "theming.Theming.getStylesheet"})
10. /var/www/nextcloud/lib/base.php line 997
    OC\Route\Router->match("/apps/theming/styles")
11. /var/www/nextcloud/index.php line 42
    OC::handleRequest()

</details>

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
