### ISSUE TITLE
18.0.1 Shared link - Video files in folder are download only

### ISSUE THREAD

**Issue by JoeatMJ** [nextcloud/server#19878]
### Steps to reproduce
1. Upload video files into a folder.
2. Share the folder via a link.
3. Click the links in the folder.

### Expected behaviour
Supported files play in the NC video player in the browser window.

### Actual behaviour
The files download to the local machine when they should play.

Sharing video files directly, behavior is as expected. The files play within the browser window . This bug happening when sharing a folder with video files inside. OnlyOffice files and other file types behave as they should within that shared file. Testing the sharing in multiple different ways on multiple client platforms shows that this is just with video files.

### Server configuration

**Operating system:**
Ubuntu 18.04.3
**Web server:**
Apache
**Database:**
MySQL 5.7.29
**PHP version:**
7.2.24
**Nextcloud version:** (see Nextcloud admin page)
18.0.1 - 18.0.1.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
17.0.3
**Where did you install Nextcloud from:**
Nextcloud site using command line updater
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
- accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - announcementcenter: 3.7.0
 - audioplayer: 2.9.0
 - bruteforcesettings: 1.5.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_retention: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - groupfolders: 6.0.1
 - impersonate: 1.5.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.1.3",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "loglevel": 2,
    "log_rotate_size": 52428800,
    "onlyoffice": {
        "jwt_secret": "***REMOVED SENSITIVE VALUE***",
        "jwt_header": "***REMOVED SENSITIVE VALUE***"
    },
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true,
    "simpleSignUpLink.shown": false


Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Multiple from Edge, Firefox, Chrome, Opera, and others.

**Operating system:**
Win 10, MacOS 10.14
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Dragon988** [comment]
Either this is fixed in 18.0.2 RC2 or you're trying to have users play a format their browser doesn't natively support.

No such issue on my end.

**Comment by JoeatMJ** [comment]
We ended up having multiple issues surrounding sharing. I have multple VM's that I use for testing and all the 18.0.1's were having the same issue. I tested out 18.0.2 on a test VM and and it took care of the issues. Updated live instances and they are working well. Thank you all for all your work on this project!

**Comment by rgr101** [comment]
Just having set up am 18.0.2 instance for a friend to enable him to giving "Corona-caused" online lessons... ...and ran into exactly this issue!

I'm observing the following behavior: 

After having uploaded the video file into a shared folder, 

a) as long as the "Hide download" checkbox is NOT checked it will play as desired
b) but as soon as "Hide download" is checked, the video won't be loaded; the Browser's console shows "Failed to load resource: the server responded with a status of 404 ()"

=> It seems that the object will be shown in the folder but as soon as it is going to be loaded it fails (the playing function might have been killed with kindness to really prevent users to download... Honestly - I have no clue how to achieve the one by preventing from the other at the same time... - kind of a paradox?)

Mind you - this behavior is observed with files within a shared folder. 
When sharing the file itself the video will play, even if shared with "Hide download" checked.

BTW: In my personal 17.0.2 instance everything works as expected; however, the browser's right-mouse-click standard feature _always_ allows to download... - anyway; it seems to better than the 18's behavior **=> backport?**

**Comment by kesselb** [comment]
cc @nickvergessen @rullzer
