### ISSUE TITLE
Feature request: Server-side encryption - allow per volume setting for external storage volumes

### ISSUE THREAD

**Issue by sgofferj** [nextcloud/server#19883]
**Is your feature request related to a problem? Please describe.**
I use various external storage volumes, including local filesystem, SMB, S3 and Google Drive. For obvious reasons, I would like the files on S3 and Google Drive to be encrypted, however, there is no need for the overhead on the "external" local storage or the SMB volumes. The "external" local storage also contains my photo archive which needs to be accessible in the LAN directly through SMB and NFS.

**Describe the solution you'd like**
I would like to be able to choose that only external storage is encrypted (which already is the case) and I would like to then be able to choose in the external storage tab which of the external storage volumes should be encrypted and which not.

**Describe alternatives you've considered**
I don't see alternatives short of not using public cloud storage - which unfortunately is the only convenient off-site backup/storage choice for private/SMB users. Using the access control functions of the cloud storage provider does not protect from access through the provider.

**Comment by szaimen** [comment]
Hi, please see the following:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html#mount-options
![image](https://user-images.githubusercontent.com/42591237/120178374-be695380-c209-11eb-9702-580d88bb2251.png)
Thanks!

**Comment by szaimen** [comment]
Of course you need to enable it after you enable the app before you can use it. you need to activate it here: https://yourdomain.com/index.php/settings/admin/security
Afterwards, the checkboxes for external storage become visible.

**Comment by sgofferj** [comment]
Ah, thanks! A bit unintuitive but got it to work - after a heart attack... The system was throwing 500s after enabling encryption but I could fix it.
