### ISSUE TITLE
Upgrade to 18.0.1: Check for expected files The following extra files have been found: nextcloud_new.log

### ISSUE THREAD

**Issue by virse** [nextcloud/server#19898]
Hey there,

I try to upgrade my runing NC 17.0.3 to 18.0.1. 

Via Webupdater and also console I receive this error message:

```
Check for expected files
The following extra files have been found:
nextcloud_new.log
```

But the nextcloud_new.log is created by the updater itself. Even if I delete the file before I hit the "y"-button to accept the further upgrade, the updater stops.

Any hints on that?

Thx, Mike

The system is an Ubuntu 18 LTS with Apache2, PHP 7.3 and PHP-FPM.

**Comment by kesselb** [comment]
> But the nextcloud_new.log is created by the updater itself.

I doubt that. 

> Any hints on that?

https://help.nextcloud.com is the place to ask questions. GitHub is used to track bugs. I don't see any bug here. Also you decided to not use the issue template so triaging your report is not possible anyway.
