### ISSUE TITLE
Extraneous vertical space in 'files' app.

### ISSUE THREAD

**Issue by sciurius** [nextcloud/server#19893]
NC 18.0.2 RC2. Firefox 73 on Fedora 31.

The 'files' app shows a big empty area at the top of the page.

![scrot20200311163434](https://user-images.githubusercontent.com/1118804/76434789-71a41d80-63b6-11ea-871c-8870a2ec59e2.png)

**Comment by szaimen** [comment]
Hi, this is by design because of the workspaces introduced with NC18. You can disable it by deselecting workspaces in the settings of the files app:
![image](https://user-images.githubusercontent.com/42591237/120179246-9a5a4200-c20a-11eb-9168-38e9e304287f.png)
