### ISSUE TITLE
Different usernames in iOS-Profile file and app-passwort if 2-factor auth is active

### ISSUE THREAD

**Issue by manolo4711** [nextcloud/server#19896]
**Steps to reproduce**
2-factor auth is active
Example username: famMaier
When I create a new App-Passwort for this account famMaier (in the 2 factor settings) the username will be: fammaier

**Expected behaviour**
I recommend my user to use the iOS config file. That's a great simplification. If 2 factor auth is active I thought the iOS Profile functionality was supposed to take care of this. 

Actual behaviour
The result is that the user will getting errors during import the profile in ios (username/or Passwort is incorrect) The reason: In the xml profile file the username is fam**M**aier and not fammaier for 2 factor auth.

**Nextcloud version:** 
18.0.1

**Comment by kesselb** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
we might use the `uid`, so the internal user identifier. but we also have something that is called *login name*, it's what you enter on the login page.

Check you database for `select * from oc_accounts where lower(uid) = 'fammaier';`, then we'll know your UID.

**Comment by Wdavery** [comment]
Having this exact issue myself. One account, "user" works as expected, but another, "User" does not work.

**Comment by ChristophWurst** [comment]
@Wdavery mind checking https://github.com/nextcloud/server/issues/19896#issuecomment-601241744 with your UID?

**Comment by Wdavery** [comment]
I’m not sure how to go about doing that, but I can definitely give it a go. Just a bit outside my scope 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Wdavery** [comment]
I will check to see if this issue persists, get my UID from the dB and report back. This got back burner'd for me, sorry!

**Comment by Wdavery** [comment]
Happy to report that the issue seems to be resolved!
