### ISSUE TITLE
Cannot add new user using API

### ISSUE THREAD

**Issue by zmaren** [nextcloud/server#19891]
Hello,

I have tried like it's described in the documentation to add a new user:

![image](https://user-images.githubusercontent.com/36674206/76415313-42cb7e80-6399-11ea-974a-780eb89126fc.png)

I provided correct credentials and login works from the web. Did I make some mistakes here?

Thanks.

**Comment by kesselb** [comment]
Two issues to be precise.

1) Ingoring the issue template and posting that as issue here 

2) `OCS-APIRequest: true` as header for api request is required. That's of course a bit confusing but has historical reasons and is also documented.
