### ISSUE TITLE
Show system cron user in web interface for easier setup

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#1989]
This was requested by @ronnyhartenstein while talking with him about the setup process.

It would be really nice to see the user under which the cron job should be executed in the web UI. (admin settings -> cron).

@nextcloud/designers What do you think? Does that make sense?

**Comment by enoch85** [comment]
Isn't it *always* www-data?

**Comment by LukasReschke** [comment]
No. The PHP process can easily run under another user. Mine runs as "nextcloud-com" for example ;)

**Comment by enoch85** [comment]
@LukasReschke Super-high-tech-security-Lukas ;)

**Comment by MorrisJobke** [comment]
Fix is in #1994

**Comment by ronnyhartenstein** [comment]
Well, I cronned as www-data and got errors about permission problems. So I must start it with `sudo` to get the glue. So I appreciate a hint :)
