### ISSUE TITLE
OCS API user metadata: inconsistent response on unlimited quota

### ISSUE THREAD

**Issue by bpcurse** [nextcloud/server#19909]
### Steps to reproduce
1. Create user `testuser` and set quota to `unlimited`
2. Do **not** log in with `testuser`
3. Query the API
`curl -u  adminuser:adminpassword 'https://cloud.example.com/ocs/v1.php/cloud/users/testuser' -H "OCS-APIRequest: true"`
4. Log in with 'testuser'
5. Repeat step 3

### Expected behaviour
- Both API calls should return `-3` on `quota`.
- Both API calls should return either a value or `null` on `free`, not different responses

It is not necessary to distinguish users that have logged in to users that have never logged in through the `quota` response. This can be easily achieved using `lastLogin`.

### Actual behaviour
- The first call returns `none`, the second returns `-3` on `quota`
- The first call returns `null`, the second returns a value on `free`

```
  <lastLogin>0</lastLogin>
  <backend>Database</backend>
  <subadmin/>
  <quota>
   <quota>none</quota>
   <used>0</used>
  </quota>
```
```
  <lastLogin>1583616955000</lastLogin>
  <backend>Database</backend>
  <subadmin/>
  <quota>
   <free>6350103810048</free>
   <used>16913912</used>
   <total>6350120723960</total>
   <relative>0</relative>
   <quota>-3</quota>
  </quota>
```

### Server configuration
18.0.2 (same behaviour on 17.0.3)

**Comment by kesselb** [comment]
> Both API calls should return -3 on quota.

:+1: 

> Both API calls should return either a value or null on free, not different responses

Not possible. The file system is not setup for such users hence we are not able to tell. We only know for sure that 0 bytes are used.

**Comment by kesselb** [comment]
```
Index: apps/provisioning_api/lib/Controller/AUserData.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/provisioning_api/lib/Controller/AUserData.php	(revision a5b0f41a9ffc570319abbae24b1e82128f3171a6)
+++ apps/provisioning_api/lib/Controller/AUserData.php	(date 1584032074304)
@@ -37,6 +37,7 @@
 use OCP\AppFramework\OCS\OCSException;
 use OCP\AppFramework\OCS\OCSNotFoundException;
 use OCP\AppFramework\OCSController;
+use OCP\Files\FileInfo;
 use OCP\Files\NotFoundException;
 use OCP\IConfig;
 use OCP\IGroupManager;
@@ -205,11 +206,13 @@
 				throw new OCSException('User does not exist', 101);
 			}
 			$quota = $user->getQuota();
-			if ($quota !== 'none') {
+			if ($quota === 'none') {
+				$quota = FileInfo::SPACE_UNLIMITED;
+			} else {
 				$quota = OC_Helper::computerFileSize($quota);
 			}
 			$data = [
-				'quota' => $quota !== false ? $quota : 'none',
+				'quota' => $quota === false ? FileInfo::SPACE_UNKNOWN : $quota,
 				'used' => 0
 			];
 		}
```

**Comment by bpcurse** [comment]
> > Both API calls should return either a value or null on free, not different responses
> 
> Not possible. The file system is not setup for such users hence we are not able to tell. We only know for sure that 0 bytes are used.

In this special case (unlimited quota) the system simply reports the total free space as `free` to the user.
So shouldn't it be also possible to return it for users that have never logged in, or am I missing something?

![nextcloud_18_report_free_space](https://user-images.githubusercontent.com/29312856/76547359-5526e480-648d-11ea-83d5-1cc8709f07e3.png)

```
 <free>6350103810048</free>
```

They are the same, the system overview just incorrectly reports TB instead of TiB.

**Comment by kesselb** [comment]
> So shouldn't it be also possible to return it for users that have never logged in

I think so. But you have even more permutations then. Quota for users logged in once, Quota for users not logged in before and quota unlimited, Quota for users not logged in before and another quota configuration. How is that better?

**Comment by bpcurse** [comment]
> How is that better?

From a server developer's view: probably worse :wink: 
From an API user's view: You have less `null` data to deal with.

But I agree that it's not that important and if it complicates things on the server side probably not worth it. Although, if it's easy to achieve, why not?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
