### ISSUE TITLE
device-specific password doesn't work after user's password change in Active Directory

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/server#19905]
**Steps to reproduce**
1.	Create device token for WebDav
2.	Change password in Active Directory

**Expected behaviour**
“For password changes in external user backends the device-specific passwords are marked as invalid and once a login of the user account with the main password happens all device-specific passwords are updated and work again.”

**Actual behaviour**
Login to Nextcloud using web browser or client doesn’t update WebDav device password in 90% of attempts. Sometime it does if I will do it straight away, but if I wait around hour, the device password doesn’t work and I have to create it from begin. I’ve tested the behaviour on different serves with versions 18.0.1, 17.0.2 and 15.0.5. On all servers the behaviour is exactly the same.

**Server configuration**
Operating system: Ubuntu 18.04
Web server: nginx-1.16.1
Database: MariaDB 10.4.11
PHP version: 7.3.13
Nextcloud version: 18.0.1

Updated from an older Nextcloud/ownCloud or fresh install: Fresh install
Could you help me with this please?

**Comment by kesselb** [comment]
To reference: https://help.nextcloud.com/t/device-specific-password-doesnt-work-after-users-active-directory-password-is-changed/73640

**Comment by PiotrIr** [comment]
I'm still waiting for somebody to help me with this issue. It is no resolved yet unfortunately :-(

**Comment by PiotrIr** [comment]
I'm also not sure what other information are required - please tell me so I will provide them.
