### ISSUE TITLE
[Web] Upper-right icons too small (specially notifications icon)

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#19906]
After the global `font-size` raising in NC18, it should be considered to raise (or redesign) the upper-right icons on the web GUI. Notifications are small and not **eye-catching** as notifications should be.

See these screenshots taken from other systems that implement notifications.

**NC 18**
![image](https://user-images.githubusercontent.com/12234510/76519270-f5b2df80-6460-11ea-9323-ff0b0a99401c.png)
**System A**
![image](https://user-images.githubusercontent.com/12234510/76519331-0f542700-6461-11ea-948a-e94a20a81126.png)
**System B**
![image](https://user-images.githubusercontent.com/12234510/76519356-1d09ac80-6461-11ea-8916-c93c358c194b.png)

@nextcloud/designers

**Comment by juliushaertl** [comment]
Good point, also they are slightly smaller (16px) than the app icons (20px) so I'd say we can align them all to 20px.

**Comment by deepank120896** [comment]
@juliushaertl 
Is anyone working on this one?

**Comment by juliushaertl** [comment]
Not yet, feel free to pick it up, this is definitely a good issue to start contributing. ;)

**Comment by deepank120896** [comment]
> Not yet, feel free to pick it up, this is definitely a good issue to start contributing. ;)

Can you help in setting up development environment or steps/guide?

**Comment by ma12-co** [comment]
@deepank120896 do you have WSL set up?

**Comment by saloni-singh14** [comment]
Hey, can I work on this issue?

**Comment by Aryan-Abhishek** [comment]
Hi, So I think this serves the best for my domain, shall I do this.

**Comment by skjnldsv** [comment]
> Hi, So I think this serves the best for my domain, shall I do this.

Sure, feel free!

**Comment by Aryan-Abhishek** [comment]
> > Hi, So I think this serves the best for my domain, shall I do this.
> 
> Sure, feel free!

sir, how do i get this file are you going to assign/send this.

**Comment by Aryan-Abhishek** [comment]
> > > Hi, So I think this serves the best for my domain, shall I do this.
> > 
> > 
> > Sure, feel free!
> 
> sir, how do i get this file are you going to assign/send this.

I am new to open source community, and wants to contribute.

**Comment by ma12-co** [comment]
@Aryan-Abhishek, join our community channel, you will find help there! https://cloud.nextcloud.com/call/xs25tz5y

**Comment by yash-rana23** [comment]
is it assigned to someone?  if not, then may i do this one?

**Comment by szaimen** [comment]
> is it assigned to someone? if not, then may i do this one?

It is currently not assigned. Feel free to proceed! :)

**Comment by szaimen** [comment]
Since there doesn't seem to be any progress, I am taking this. Hope that is okay.
