### ISSUE TITLE
NC 18.0.1: Modifying cURL timeout in Client.php has no effect

### ISSUE THREAD

**Issue by Mohammed-Al-Haidary** [nextcloud/server#19900]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Modify the "RequestOptions::TIMEOUT" variable in server/lib/private/Http/Client/Client.php to 600.
2. Attempt to update the Mail app or download Community Document Server from the web UI.

### Expected behaviour
The app should either update successfully or give a timout error after 600 seconds.

### Actual behaviour
It gives a timout error after 120 seconds.

### Server configuration

**Operating system:** NextcloudPi

**Database:** mysql 10.3.17

**PHP version:** 7.3.11

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18.0.0

**Signing status:**
<details>
<summary>Signing status</summary>

"No errors have been found."

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

"Could not open input file: occ"

</details>

**Are you using external storage, if yes which one:** Yes, local.

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Desktop Firefox

**Operating system:** Windows 10

### Logs

"[core] Error: GuzzleHttp\Exception\ConnectException: cURL error 28: Operation timed out after 120000 milliseconds with 1638657 out of 12158468 bytes received (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at <<closure>>

 0. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 149
    GuzzleHttp\Handler\CurlFactory::createRejection(GuzzleHttp\Handl ... l}, {errno: 28,error ... 6})
 1. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlFactory.php line 102
    GuzzleHttp\Handler\CurlFactory::finishError(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 2. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/CurlHandler.php line 43
    GuzzleHttp\Handler\CurlFactory::finish(GuzzleHttp\Handler\CurlHandler {}, GuzzleHttp\Handl ... l}, GuzzleHttp\Handler\CurlFactory {})
 3. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 28
    GuzzleHttp\Handler\CurlHandler->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 4. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Handler/Proxy.php line 51
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 5. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php line 37
    GuzzleHttp\Handler\Proxy::GuzzleHttp\Handler\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Middleware.php line 30
    GuzzleHttp\PrepareBodyMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 7. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 70
    GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
 8. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 107
    GuzzleHttp\RedirectMiddleware->__invoke("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
 9. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/RedirectMiddleware.php line 72
    GuzzleHttp\RedirectMiddleware->checkRedirect(GuzzleHttp\Psr7\Request {}, "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
10. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/FulfilledPromise.php line 39
    GuzzleHttp\RedirectMiddleware->GuzzleHttp\{closure}("*** sensitive parameters replaced ***")
11. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/TaskQueue.php line 47
    GuzzleHttp\Promise\FulfilledPromise::GuzzleHttp\Promise\{closure}("*** sensitive parameters replaced ***")
12. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 246
    GuzzleHttp\Promise\TaskQueue->run(true)
13. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 223
    GuzzleHttp\Promise\Promise->invokeWaitFn()
14. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 267
    GuzzleHttp\Promise\Promise->waitIfPending()
15. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 225
    GuzzleHttp\Promise\Promise->invokeWaitList()
16. /var/www/nextcloud/3rdparty/guzzlehttp/promises/src/Promise.php line 62
    GuzzleHttp\Promise\Promise->waitIfPending()
17. /var/www/nextcloud/3rdparty/guzzlehttp/guzzle/src/Client.php line 131
    GuzzleHttp\Promise\Promise->wait()
18. /var/www/nextcloud/lib/private/Http/Client/Client.php line 149
    GuzzleHttp\Client->request("get", "https://github. ... z", {proxy: null,ver ... e})
19. /var/www/nextcloud/lib/private/Installer.php line 274
    OC\Http\Client\Client->get("https://github. ... z", {save_to: "/var/ ... 0})
20. /var/www/nextcloud/lib/private/Installer.php line 191
    OC\Installer->downloadApp("*** sensitive parameter replaced ***")
21. /var/www/nextcloud/apps/settings/lib/Controller/AppSettingsController.php line 528
    OC\Installer->updateAppstoreApp("*** sensitive parameters replaced ***")
22. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 170
    OCA\Settings\Controller\AppSettingsController->updateApp("*** sensitive parameters replaced ***")
23. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 99
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings\Con ... {}, "updateApp")
24. /var/www/nextcloud/lib/private/AppFramework/App.php line 125
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings\Con ... {}, "updateApp")
25. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
    OC\AppFramework\App::main("OCA\\Settings\\ ... r", "updateApp", OC\AppFramework\ ... {}, {appId: "*** sen ... "})
26. <<closure>>
    OC\AppFramework\Routing\RouteActionHandler->__invoke({appId: "*** sen ... "})
27. /var/www/nextcloud/lib/private/Route/Router.php line 299
    call_user_func(OC\AppFramework\ ... {}, {appId: "*** sen ... "})
28. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/settings/apps/update/mail")
29. /var/www/nextcloud/index.php line 38
    OC::handleRequest()"

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/b54fdae062412c358debc563367525fdbc0a5b24/lib/private/Installer.php#L279

GitHub is not a support channel. Use https://help.nextcloud.com the next time.
