### ISSUE TITLE
CardDAV image export broken for Mail

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#1992]
The image export plugin we use in Mail to show contact images is broken since https://github.com/nextcloud/server/pull/1339.

Apparently, removing the ``Content-Disposition`` header fixes the problem. ref https://github.com/nextcloud/server/pull/1339#discussion_r82282689

cc @LukasReschke

ref nextcloud/mail#131

**Comment by ChristophWurst** [comment]
@LukasReschke how could this be fixed?

**Comment by LukasReschke** [comment]
Patch is at https://github.com/nextcloud/server/pull/2677
