### ISSUE TITLE
Update to 18.0.2 from 18.0.1 fails when updating apps

### ISSUE THREAD

**Issue by krheinwald** [nextcloud/server#19927]
When finishing the upgrade, the last step fails with a nondescriptive error message.

On first glance, I could not find any helpful information in the logs.

Any suggestions are highly appreciated.

![Anmerkung 2020-03-13 123929](https://user-images.githubusercontent.com/452679/76617946-a84d7580-6527-11ea-8a91-1a67fc3f8094.png)

**Comment by szaimen** [comment]
I suppose this happened because of the appstore being overwhelmed by requests. Please try again and report back if it still happens. Thanks!
