### ISSUE TITLE
User icon (avatar) is not shown for "file-drop" if user is not logged in

### ISSUE THREAD

**Issue by nooblag** [nextcloud/server#19920]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Set up a file-drop share for a folder within a folder. For example, /apps/files/?dir=/Uploads/Public Uploads
2. Visit file-drop link

### Expected behaviour
User icon should appear as in root file-drop shares

### Actual behaviour
User icon is a gray ? question mark icon

### Server configuration

**Operating system:** Ubuntu 18.04.4 LTS

**Web server:** nginx 1.16.1

**Database:** psql (PostgreSQL) 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1)

**PHP version:** PHP 7.2.24-0ubuntu0.18.04.3 (cli) (built: Feb 11 2020 15:55:52) ( NTS )

**Nextcloud version:** 18.0.2

**Where did you install Nextcloud from:**
nextcloud.com

**Comment by nooblag** [comment]
![Capture](https://user-images.githubusercontent.com/1122344/76598583-44db3c00-6557-11ea-8995-054951293698.PNG)

**Comment by nooblag** [comment]
Just expanding this issue to root folders as well after more testing. I can't seem to get any public shares to display their icons.

I've narrowed the issue to: if users are already logged in to Nextcloud, sometimes icons are shown, but if a fresh "anonymous" user visits the page, icons are never shown and ? appears.

**Comment by rullzer** [comment]
That is because your avatar is not set to public. Set it to public and it will work.

**Comment by nooblag** [comment]
Thanks for the reply.

Where is the setting to set avatar to public? I couldn't find one. And this is what my "Settings" screen looks like:

![Capture](https://user-images.githubusercontent.com/1122344/80794818-30720200-8bde-11ea-9c3e-be87353f75a0.PNG)

Thanks.

**Comment by rullzer** [comment]
Ah I guess those are not there when you don't have the lookup server stuff enabled etc.

Yeah something to look into.
@MorrisJobke

**Comment by nooblag** [comment]
I assume lookup server is referring to federation? Yes, the server is not federated, it's stand-alone.
Thanks.

**Comment by MorrisJobke** [comment]
> I assume lookup server is referring to federation? Yes, the server is not federated, it's stand-alone.
> Thanks.

It's the "Allow users to publish their data to a global and public address book" option in admin > sharing > federated cloud sharing

![Bildschirmfoto 2020-05-04 um 14 21 39](https://user-images.githubusercontent.com/245432/80965344-a8287280-8e12-11ea-8920-f67f2fccfd7c.png)

Then there are no options for the avatar - indeed.

On 19.0.0 the avatar is replaced by a folder for me. @skjnldsv did anything change there lately?

**Comment by skjnldsv** [comment]
> On 19.0.0 the avatar is replaced by a folder for me. @skjnldsv did anything change there lately?

Yes, it was moved to subfolder? I don't recall exactly.
Or was it the previews. I any case, 

> It wasn't me
— shaggy

**Comment by nooblag** [comment]
Thanks for the note.

In 18.0.6, enabling "Allow users to publish their data to a global and public address book" option in Admin > Sharing > Federated Cloud Sharing did not seem to fix this issue. Question mark in place of icon still remained.

I ended up upgrading to 19.0.0 so doesn't matter to us now anymore, but just FYI.

Thanks.
