### ISSUE TITLE
Wrong useragent regex for safari in browserSupportsCspV3

### ISSUE THREAD

**Issue by xklonx** [nextcloud/server#19941]
Example useragent from safari 13.0.5
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15`
current regex
`^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[0-9.]+ \(KHTML, like Gecko\) Version\/(1[2-9]|[2-9][0-9])\.[0-9]+ Safari\/[0-9.A-Z]+$`
correct example 
`^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[0-9.]+ \(KHTML, like Gecko\) Version\/(1[2-9]|[2-9][0-9])\.[0-9]+\.?[0-9]+ Safari\/[0-9.A-Z]+$`

i can make pullrequest if you want

**Comment by xklonx** [comment]
One more problem is that CSPMiddleware uses getDefaultPolicy
`public function afterController($controller, $methodName, Response $response): Response {
		$policy = !is_null($response->getContentSecurityPolicy()) ? $response->getContentSecurityPolicy() : new ContentSecurityPolicy();

		if (get_class($policy) === EmptyContentSecurityPolicy::class) {
			return $response;
		}

		$defaultPolicy = $this->contentSecurityPolicyManager->getDefaultPolicy();
		$defaultPolicy = $this->contentSecurityPolicyManager->mergePolicies($defaultPolicy, $policy);

		if($this->cspNonceManager->browserSupportsCspV3()) {
			$defaultPolicy->useJsNonce($this->csrfTokenManager->getToken()->getEncryptedValue());
		}

		$response->setContentSecurityPolicy($defaultPolicy);

		return $response;
	}`
 which creates new ContentSecurityPolicy and then uses mergePolicies to merge all values in that
`public function getDefaultPolicy(): ContentSecurityPolicy {
		$event = new AddContentSecurityPolicyEvent($this);
		$this->dispatcher->dispatch(AddContentSecurityPolicyEvent::class, $event);

		$defaultPolicy = new \OC\Security\CSP\ContentSecurityPolicy();
		foreach($this->policies as $policy) {
			$defaultPolicy = $this->mergePolicies($defaultPolicy, $policy);
		}
		return $defaultPolicy;
	}` 
but mergePolicies skips string value of $useJsNonce 
`public function mergePolicies(ContentSecurityPolicy $defaultPolicy,
								  EmptyContentSecurityPolicy $originalPolicy): ContentSecurityPolicy {
		foreach((object)(array)$originalPolicy as $name => $value) {
			$setter = 'set'.ucfirst($name);
			if(\is_array($value)) {
				$getter = 'get'.ucfirst($name);
				$currentValues = \is_array($defaultPolicy->$getter()) ? $defaultPolicy->$getter() : [];
				$defaultPolicy->$setter(array_values(array_unique(array_merge($currentValues, $value))));
			} elseif (\is_bool($value)) {
				$defaultPolicy->$setter($value);
			}
		}

		return $defaultPolicy;
	}` 
and there is no way for app to create custom code to bypass this issue.

**Comment by xklonx** [comment]
Also i think that if nonce is set we need to add unsafe-inline even if is not set so modern browsers ignore unsafe and older ones use unsafe instead of nonce.
```
if(!empty($this->allowedScriptDomains) || $this->inlineScriptAllowed || $this->evalScriptAllowed) {
			$policy .= 'script-src ';
			if(is_string($this->useJsNonce)) {
				$policy .= '\'nonce-'.base64_encode($this->useJsNonce).'\'';
				$allowedScriptDomains = array_flip($this->allowedScriptDomains);
				unset($allowedScriptDomains['\'self\'']);
				$this->allowedScriptDomains = array_flip($allowedScriptDomains);
				if(count($allowedScriptDomains) !== 0) {
					$policy .= ' ';
				}
			}
			if(is_array($this->allowedScriptDomains)) {
				$policy .= implode(' ', $this->allowedScriptDomains);
			}
			if($this->inlineScriptAllowed) {
				$policy .= ' \'unsafe-inline\'';
			}
			if($this->evalScriptAllowed) {
				$policy .= ' \'unsafe-eval\'';
			}
			$policy .= ';';
		}
```
change if to `if(is_string($this->useJsNonce) || $this->inlineScriptAllowed)`

**Comment by kesselb** [comment]
> i can make pullrequest if you want

Please ;) But make sure that the new regex works with:

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0 Safari/605.1.15`

`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.5 Safari/605.1.15`

As per https://developers.whatismybrowser.com/useragents/explore/software_name/safari/ both are valid.

**Comment by kesselb** [comment]
cc @rullzer for the getDefaultPolicy stuff ;)

**Comment by xklonx** [comment]
https://www.phpliveregex.com/p/vgu
`^Mozilla\/5\.0 \([^)]+\) AppleWebKit\/[0-9.]+ \(KHTML, like Gecko\) Version\/(?:1[2-9]|[2-9][0-9])\.[0-9]+(?:\.[0-9]+)? Safari\/[0-9.A-Z]+$`

**Comment by xklonx** [comment]
https://github.com/nextcloud/server/pull/19954

**Comment by xklonx** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

> Specifying nonce makes a modern browser ignore 'unsafe-inline' which could still be set for older browsers without nonce support.

**Comment by kesselb** [comment]
Mind to create another issue for the script-src thing? Thanks :+1:

**Comment by xklonx** [comment]
#19956
