### ISSUE TITLE
Ability to make a single file show up in different folders

### ISSUE THREAD

**Issue by amo13** [nextcloud/server#19948]
**Is your feature request related to a problem? Please describe.**
I would like to have some files (or folders) show up in different places of my Nextcloud Files. What I am thinking of is something like a symlink on the file system preventing from having multiple copies of one and the same file at multiple places. 

**Describe the solution you'd like**
A simple GUI element to create such a (sym)link to another file or folder inside the same users files.

**Describe alternatives you've considered**
The only way to accomplish this (that I can think of) for now is to create a user2, share the file/folder with this user2 and have user2 share it back to the original user to make the that file/folder show up at a different place without creating a duplicate copy.

**Comment by bpcurse** [comment]
Maybe a feature resembling a hardlink would be more appropriate. But it depends on the use case.
- If you want a "master" file, where all "copies" are deleted or remain as faulty links, if the file itself is deleted, your proposal is the right way to go.
- If you want "copies" that also do not consume additional storage space and are independent from others being deleted (as long as they are not altered), the behaviour of hardlinks should be desirable.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
