### ISSUE TITLE
Cannot upload/sync Android Studio files.

### ISSUE THREAD

**Issue by Beowulf2** [nextcloud/server#19944]
My server version is Nextcloud 18.0.2.

My problem is that I would like sync my Android Studio Project files between devices, but I cannot upload the Project folder to Android Studio.
I get a lot of this MKCOL-Errors. I exported one Error:
[log.txt](https://github.com/nextcloud/server/files/4331493/log.txt)

I hope anyone can help me.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
