### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by smart2128** [nextcloud/server#19952]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Expected behaviour
Strings should be translated

### Actual behaviour
Some strings are not translated in Accessibility and Security settings
![Screenshot_20200314_113547](https://user-images.githubusercontent.com/16859/76681206-c0d59280-65f0-11ea-8d8f-af8896bb1b99.png)

![Screenshot_20200314_114646](https://user-images.githubusercontent.com/16859/76681207-c4691980-65f0-11ea-97c2-80b8e688ffbe.png)

**Operating system:**
Centos 7

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.1

**Nextcloud version:**
17.0.4

**Comment by acs-ferreira** [comment]
You can (and should 👍 ) contribute to it at https://www.transifex.com/nextcloud/nextcloud/

**Comment by smart2128** [comment]
Hi,
I'm sorry if I didn't specifiy that those strings are already translated on Transifex.
I'm the Italian translation team coordinator.
Please, could you re-open the issue?

Thank you in advance,
Vincenzo
