### ISSUE TITLE
Add unsafe-inline for older browsers when nonce is set 

### ISSUE THREAD

**Issue by xklonx** [nextcloud/server#19956]
I think that if nonce is set we need to add unsafe-inline even if is not set,
then modern browsers will ignore unsafe and older ones would use unsafe instead of nonce.
```
if(!empty($this->allowedScriptDomains) || $this->inlineScriptAllowed || $this->evalScriptAllowed) {
			$policy .= 'script-src ';
			if(is_string($this->useJsNonce)) {
				$policy .= '\'nonce-'.base64_encode($this->useJsNonce).'\'';
				$allowedScriptDomains = array_flip($this->allowedScriptDomains);
				unset($allowedScriptDomains['\'self\'']);
				$this->allowedScriptDomains = array_flip($allowedScriptDomains);
				if(count($allowedScriptDomains) !== 0) {
					$policy .= ' ';
				}
			}
			if(is_array($this->allowedScriptDomains)) {
				$policy .= implode(' ', $this->allowedScriptDomains);
			}
			if($this->inlineScriptAllowed) {
				$policy .= ' \'unsafe-inline\'';
			}
			if($this->evalScriptAllowed) {
				$policy .= ' \'unsafe-eval\'';
			}
			$policy .= ';';
		}
```
change if to 
```
if(is_string($this->useJsNonce) || $this->inlineScriptAllowed) {
				$policy .= ' \'unsafe-inline\'';
			}
```

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src

> Specifying nonce makes a modern browser ignore 'unsafe-inline' which could still be set for older browsers without nonce support.

**Comment by kesselb** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Well sure.
But we only set the nonce for browsers that support it.

We can't always set the nonce (believe me I tried). Since for example edge and older safaris choked on it then.
