### ISSUE TITLE
Share by link permission

### ISSUE THREAD

**Issue by Tim2468** [nextcloud/server#19953]
**Is your feature request related to a problem? Please describe.**
I want to restrict sharing via link to groups and/or users. For example, I as admin would like to have the possibility to share content via link, but all others should not be able to do so.

**Describe the solution you'd like**
It should be possible to restrict sharing by link to individual groups. For example, I don't want to allow sharing by link, but as an admin I still want to have the possibility.

**Comment by wiswedel** [comment]
This should equivalently apply to email shares

**Comment by szaimen** [comment]
You will be able to do this in NC22 https://github.com/nextcloud/server/pull/26727
