### ISSUE TITLE
Add low timeout values to "Security & setup warnings"

### ISSUE THREAD

**Issue by Tie-fighter** [nextcloud/server#19951]
**Is your feature request related to a problem? Please describe.**
My Sync client often receives "504 Gateway timed out" errors messages when moving large files. I have tried tuning multiple timeout values without success.

**Describe the solution you'd like**
It could be cool if Nextcloud reported on low timeout values, just like with low PHP memory limit, making it easier to find and fix the right timeout value.

**Describe alternatives you've considered**
I have tried increasing all kinds of timeouts in php.ini, nginx and php-fpm.

**Additional context**
I am using a Freenas Jail with nginx and php-fpm.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this something we should/can do?

**Comment by artonge** [comment]
It would be hard I think as the proxy can be on another server.

**Comment by skjnldsv** [comment]
Also can be tons of reasons for a timeout

**Comment by Tie-fighter** [comment]
I am sorry, I was very vague in my initial posting.

What I was trying to suggest was adding some checks to the "Security & setup warnings" functionality.
I know this won't fix all possible problems, but it might be a good start to help with obvious/common problems.
