### ISSUE TITLE
18.0.2: setting space quota of user cannot be changed

### ISSUE THREAD

**Issue by joo4mart** [nextcloud/server#19969]
# Steps to reproduce
1. login as adminstrator
2. create a new user or config an existing user
3. set the quota fo this user, e.g. to 1GB

### Expected behaviour
It should be shown "1GB" in this field

### Actual behaviour
It seems nothing is selected

### Server configuration

**Operating system:**
Linux Debian with kernel 4.9.0-12 (hosting company)

**Web server:**
Apache2

**Database:**
PostgreSQL 9.6.16

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
NC 18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
from NC 18.0.1

**Where did you install Nextcloud from:**
with webinstaller "setup-nextcloud.php"

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
"No errors have been found."

### Client configuration
**Browser:**
Firefox 74

**Operating system:**
Linux Debian 10

**Comment by kesselb** [comment]
Might be fixed by https://github.com/nextcloud/server/pull/18818 but not sure yet. Actually settings the quota works just the visual feedback is missing. Reload the page and you see the correct value.

**Comment by bd8392** [comment]
Same issue here...I also can't set the quota of my admin account when Im logged in with it...

**Comment by kesselb** [comment]
Fixed by #18818 (19) / #20144 (18.0.4)
