### ISSUE TITLE
nextcloud 16.0.10 release missing

### ISSUE THREAD

**Issue by flokli** [nextcloud/server#19976]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Read [nC-SA-2020-015](https://nextcloud.com/security/advisory/?id=nC-SA-2020-015)
2. Try to find Nextcloud Server 16.0.10, which should fix above issue
3. See it's missing from https://download.nextcloud.com/server/releases/

### Expected behaviour
It should be hosted there.

### Actual behaviour
It's currently not available.

### Server configuration
This is for packaging Nextcloud for the current (phasing out) stable distro release, so we'd like to keep the 16.x track

**Comment by kesselb** [comment]
I guess that is already fixed by https://github.com/nextcloud/server/pull/19362 for 16.0.9 and a typo with the advisory.

cc @nickvergessen

**Comment by nickvergessen** [comment]
Oh,m yeah sorry it's supposed to be 16.0.9
Typo in https://github.com/nextcloud/security-advisories/blob/master/server/nc-sa-2020-015.json#L26

**Comment by flokli** [comment]
Fixed in https://github.com/nextcloud/security-advisories/pull/21, PTAL.
