### ISSUE TITLE
Image optimisation

### ISSUE THREAD

**Issue by Brennii96** [nextcloud/server#19977]
**Is your feature request related to a problem? Please describe.**
Taking photos from my phone leaves images at 5 - 6MB and on a day out it could end up with a few hundred or thousand photos. And over the course of a month it could end up being several GB in the Photo Gallery. 

**Describe the solution you'd like**
It would be great if there was an image optimiser as external api like  that could be configured in the settings. I only really care about JPEG's as that's what most phones saves as. 

**Describe alternatives you've considered**
At the moment I'm using jpegoptim as a cron job, `strip-none` because I want to keep data for the locations tags feature. I got a 2GB folder down to 1.2GB by doing this without noticeable loss of quality. 
`find . -iname "*.jpg" -exec jpegoptim -m80 --strip-none -p {} \; `

But it would be great if it done this automatically on upload rather than as a cron job as the previews then need to be regenerated for images which have already been done.

**Comment by kesselb** [comment]
https://apps.nextcloud.com/apps/workflow_script

**Comment by Dragon988** [comment]
> 
> 
> https://apps.nextcloud.com/apps/workflow_script

Will this work if your primary storage is S3?

**Comment by kesselb** [comment]
I would think so. It seems that a local copy of the file is available as %f as per https://github.com/nextcloud/workflow_script.

**Comment by Dragon988** [comment]
Hmm doesn't seem to work with S3 storage unless I'm doing something wrong.

The www-data group has access to jpegoptim and works correctly from commandline.

**Comment by CrazyLionHeart** [comment]
I'm not sure if you backup you photos to hdd/tape/usb want some unwanted/unexpected optimization. With Nexcloud - same case.

**Comment by SimplyCorbett** [comment]
> I'm not sure if you backup you photos to hdd/tape/usb want some unwanted/unexpected optimization. With Nexcloud - same case.

But I do actually want that optimization. Especially lossless optimization. It can easily be a user-enabled setting within nextcloud.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
