### ISSUE TITLE
Some users cannot login

### ISSUE THREAD

**Issue by sciurius** [nextcloud/server#19973]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. A running NC server on system A, using MariaDB on system A and cloud storage on system A.
2. Configure a new NC server on system B, using the database and cloud storage on system A.
The config.php of the new server is identical to the config.php of server A. Both servers run exact the same version of NC (currently 18.0.2).

Both servers run as virtual hosts. Connection to the server is using HTTPS, the server name is 
resolved via DNS. The intention is to have a load balancer dispatching queries to the servers.

### Expected behaviour
Users should be able to login to either server.

### Actual behaviour
Some users can login to either server. Some users can only login to server B. When loggin in to server A they get a "wrong username/password" error. Nevertheless they can login to server B with the same username/password.

#### Server A (the original server).

**Operating system:** DSM 6.2 (Synology NAS)

**Web server:** Apache 2

**Database:** MariaDB 5

**PHP version:** 7.3

**Nextcloud version:** 18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated.

**Where did you install Nextcloud from:** update/updater.phar

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

I have not the faintest idea what is meant by this...
```
</details>

#### Server B (the new server).

**Operating system:** Debian 10 (Raspbian, RPi4)

**Web server:** Nginx 1.14.2

**Database:** MariaDB 5 on Server A

**PHP version:** 7.3

**Nextcloud version:** 18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install + cloned config.php.

**Where did you install Nextcloud from:** NC site.

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

I have not the faintest idea what is meant by this...
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - drawio: 0.9.5
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - photos: 1.0.0
  - provisioning_api: 1.8.0
  - settings: 1.0.0
  - tasks: 0.12.1
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - joplin
  - password_policy
  - privacy
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - survey_client
  - systemtags
  - theming
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.squirrel.nl"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.2.2",
        "overwrite.cli.url": "https:\/\/cloud.squirrel.nl",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "beta",
        "maintenance": false,
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "joplin"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** No. Cloud storage native on server A and SMB mounted on server B,

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Firefox

**Operating system:** Fedora 31

#### Web server error log
<details>
<summary>Web server error log</summary>

No relevant entries
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"BiImgTjWmMMiwRkRbVhQ","level":2,"time":"2020-03-15T19:42:57+00:00","remoteAddr":"192.168.1.251","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php/login","message":"Login failed: jv (Remote IP: 192.168.1.251)","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.2.2"}
{"reqId":"NXU74azWR2tA75hrDatb","level":2,"time":"2020-03-15T19:43:25+00:00","remoteAddr":"192.168.1.251","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php/login","message":"Login failed: admin (Remote IP: 192.168.1.251)","userAgent":"Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"18.0.2.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

No relevant entries.
</details>

**Comment by kesselb** [comment]
Sounds like a configuration issue to me. Please ask such questions at https://help.nextcloud.com.

**Comment by sciurius** [comment]
That was the first thing I did, but no helpful replies.
https://help.nextcloud.com/t/help-needed-to-setup-a-nc14-cluster/39707/20?u=sciurius

**Comment by kesselb** [comment]
I bet your issue is: https://help.nextcloud.com/t/help-needed-to-setup-a-nc14-cluster/39707/6?u=kesselb

**Comment by sciurius** [comment]
I added a link to my comment so that is, indeed, a safe bet :smile: .

**Comment by kesselb** [comment]
help.nextcloud.com/t/help-needed-to-setup-a-nc14-cluster/39707/**20**
help.nextcloud.com/t/help-needed-to-setup-a-nc14-cluster/39707/**6**
