### ISSUE TITLE
user management: cannot change language

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#19975]
**To reproduce**
1. in user management view, in bottom left settings activate "show language"
1. click the pen to edit a user
1. click in language field

**actual behavior**
you cannot choose or enter languages.

**expected behavior**
a dropdown is shown with language options and type-ahead search, as in the groups field.

**details**
NC 18.0.2

**comments**
oh gosh, this is already 18.0.2 and user management is still broken (two months after release 18.0). I thought https://github.com/nextcloud/server/pull/19767 would have finally fixed everything but nope. I am super frustrated. Should have sticked with 17. If you/we wanna beat GoogleMicrosoft then the product needs to work reliably.

**Comment by kesselb** [comment]
Duplicate of #19912

**Comment by alexanderdd** [comment]
Right, sorry. I did a search but maybe didnt try hard enough.
