### ISSUE TITLE
Error 18.0.1 -> 18.0.2 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by bodryj** [nextcloud/server#19972]
```
Проверено наличие обновления приложения «workflowengine»

Шаг восстановления: Repair MySQL collation

Информация восстановления: Change row format for oc_authtoken ...

Информация восстановления: Change collation for oc_authtoken ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_authtoken` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```
Error 18.0.1 -> 18.0.2

**Comment by kesselb** [comment]
Have you tried to search for "Specified key was too long; max key length is 767 bytes" at https://github.com/nextcloud/server/issues? We especially explain how to use search on GitHub in our issue template. I'm closing this one as duplicate. I guess you will find the solution in one of the 68 other issues. Please note (as also explained in the issue template) that https://help.nextcloud.com is the channel for support.
