### ISSUE TITLE
Reshare a calendar

### ISSUE THREAD

**Issue by fischerscode** [nextcloud/server#19994]
### Steps to reproduce
1. create a calendar
2. share the calendar to user2 and give him write permissions
3. try to share the calendar as user2 to an other user

### Expected behaviour
As user2 is allowed to create a shared link (works like a charm) and user2 is able to enter an username, user2 should be able to share this calendar to an other user.

### Actual behaviour
After entering the username/clicking on the preview, no user gets added.
(It's not a visual thing, as the "other user" can't access the calendar.)

### Calendar app
**Calendar app version:**  2.0.2

**CalDAV-clients used:** Used the included webapp.

### Client configuration
**Browser:** Firefox 74.0

**Operating system:** MacOS Mojave

### Server configuration

**Operating system**: Ubuntu 18.04

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.2

**Nextcloud Version:** 18.0.2

**Updated from an older installed version or fresh install:** fresh

**List of activated apps:**

```
  - accessibility: 1.4.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - documentserver_community: 0.1.5
  - external: 3.5.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_frommail: 0.4.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - forms: 1.1.1
  - groupfolders: 6.0.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.3
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - rainloop: 6.1.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.5
  - support: 1.1.0
  - systemtags: 1.8.0
  - talk_simple_poll: 1.1.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - video_converter: 0.1.3
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**Nextcloud configuration:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "_____________________________________",
            "_____________________________________"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.2.2",
        "overwrite.cli.url": "_____________________________________",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_locale": "de",
        "maintenance": false,
        "mysql.utf8mb4": true,
        "memcache.local": "\\OC\\Memcache\\APCu"
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```
nothing calendar related
```

#### Log file (data/nextcloud.log)
```
empty
```

#### Browser log
**Console:**
```
Error:                                       (calendar.js:2:1377388)
```
**Network:**
_Request:_
_______________
**URL:** ```https://**DOMAIN**/remote.php/dav/calendars/**user2**/**calendarName**_shared_by_**username**/```
**params:** ```<x4:share xmlns:x4="http://owncloud.org/ns"><x4:set><x0:href xmlns:x0="DAV:">principal:principals/users/OTHERUSER</x0:href></x4:set></x4:share>```
________________
_Response:_
________________
**403**
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\Forbidden</s:exception>
  <s:message/>
</d:error>
```
________________

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by fischerscode** [comment]
@szaimen
I've just tested it with the [nextcloud demo server](https://try.nextcloud.com/) and sharing a shared calendar did not work.
It seems like the share request returns 403.
![grafik](https://user-images.githubusercontent.com/45403027/121780725-e9f12400-cba1-11eb-99ea-f00adac5dfe1.png)

**Comment by szaimen** [comment]
cc @nextcloud/calendar

**Comment by tcitworld** [comment]
This used to work. Need to evaluate if hiding the possibility in the calendar app is easier than fixing it for now.

Also part of https://github.com/nextcloud/server/issues/20096

**Comment by raimund-schluessler** [comment]
See also https://github.com/nextcloud/tasks/issues/993

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Input-BDF** [comment]
Running into this issue still on 25.0.4 and 26.0.0. So why is this closed?

Browser console gives an POST 403 (Forbidden) response and

```
Uncaught (in promise) Error
    at n.value.regeneratorRuntime.mark.regeneratorRuntime.wrap.e.abrupt.s.onreadystatechange (dist.js:1:121978)
```
    
after selecting a group or user.

Same behaviour like @fischerscode describes. Creating a public share by user 2 is allowed. Sharing with a group or other user is not possible via user2.

**Comment by ZID-TU-Graz** [comment]
we are also affected by this issue (NC 25.0.5)

**Comment by ZID-TU-Graz** [comment]
this issue also occurs on NC 26.0.4.

**Comment by ZID-TU-Graz** [comment]
this issue also occurs on NC 27.0.2.

**Comment by Input-BDF** [comment]
this issue also occurs on NC 28.0.1
meanwhile on Calendar 4.6.3

**Comment by gnrfzui** [comment]
using NC 27.1.5, the re-sharing option disappeared completely when updating Calendar 4.6.0 -> Calendar 4.6.6

**Comment by Input-BDF** [comment]
Can confirm this on NC 28.0.3 with Calendar 4.6.6
Having the internal links available is also essential in our use-cases.

**Comment by SebastianKrupinski** [comment]
Hi Everyone, After reviewing this request, the team has decided that calendar re-sharing will not be possible at this time, due to the overwhelming complexity this would create. Sorry.
