### ISSUE TITLE
Error: Call to a member function getUID() on null, when uploading folder on external local share

### ISSUE THREAD

**Issue by simm4ik** [nextcloud/server#19996]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1) Create local folder on server ("/test" for example) owned by www-data user with write permissions. 
2) Add created folder as external storage. Create file share link with upload permission on external storage.
3) Try to upload a folder using shared link.

### Expected behaviour
Folder should be uploaded

### Actual behaviour
Browser shows folder creation error and upload error while folder is been created.
In logs appears Error: Call to a member function getUID() on null

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** pgsql PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, json, igbinary, apcu, PDO, xml, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, redis, ldap, exif, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, smbclient, soap, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.2 - 18.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** vm script installation

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [core] => Array
        (
            [FILE_MISSING] => Array
                (
                    [3rdparty/php-opencloud/openstack/env_test.sh.dist] => Array
                        (
                            [expected] => cdb0441b351375dbea118034c7a651fc5588a72d3a03a7ce206aa1ba0f00b40d1f7437006aa706f042728bb29d76875a4de2f16ff1011a66386e0d366b2deaf7
                            [current] => 
                        )

                )

            [INVALID_HASH] => Array
                (
                    [core/css/header.scss] => Array
                        (
                            [expected] => 346bd0ae854523c9f6429127c5764e85a7623ee11eafa426e0e408760f25585fc30f934d0bec274af4725c96964f78412feb9a1b85101f1a38b1f6f66317cd5f
                            [current] => a9129801afb1f1c9d75d51785c122331c8637562e8c81555b27b9d7fdb637002d9d1788f2238d7b26e609bef80054b3fcb9f008e75e6f9bc2cc44f83659fabee
                        )

                )

        )

    [activity] => Array
        (
            [FILE_MISSING] => Array
                (
                    [check-handlebars-templates.sh] => Array
                        (
                            [expected] => fd8e1cd2a4696213ce9b1b607e637aa2d65ff7425cb25f586b87a6052f774f785542310a12b0db8ab0f502dd45f1c2da6a3efecab30bd91dcfd47331efe29a14
                            [current] => 
                        )

                    [compile-handlebars-templates.sh] => Array
                        (
                            [expected] => 448294a19fe80a398f6a3bb795a1551e3ba4ac0b781d72e646ba0dc71cc9bbab4dc9de5f46d4ccc2b88a2716b9ff2e5dc2b324159a4ca1ae8719ea1bd9166fcc
                            [current] => 
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - cloud_federation_api: 1.1.0
 - dav: 1.14.0
 - extract: 1.2.3
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - text: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_ldap: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - comments
 - encryption
 - federation
 - files_trashbin
 - files_versions
 - groupfolders
 - guests
 - ldap_write_support
 - mail
 - photos
 - sharebymail
 - systemtags
 - theming

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "cloud.dtgroup.ru"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "18.0.2.2",
    "overwrite.cli.url": "https:\/\/cloud.dtgroup.ru\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "upgrade.disable-web": "true",
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
    "loglevel": "2",
    "skeletondirectory": "",
    "theme": "dtgroup",
    "default_language": "ru",
    "force_language": "ru",
    "default_locale": "ru",
    "force_locale": "ru",
    "lost_password_link": "https:\/\/cloud.dtgroup.ru\/",
    "mail_smtpmode": "smtp",
    "remember_login_cookie_lifetime": "1382400",
    "log_rotate_size": "10485760",
    "trashbin_retention_obligation": "auto, 180",
    "versions_retention_obligation": "auto, 365",
    "simpleSignUpLink.shown": "false",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "filelocking.enabled": true,
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0.5,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "logtimezone": "Europe\/Moscow",
    "htaccess.RewriteBase": "\/",
    "ldapIgnoreNamingRules": false,
    "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
    "maintenance": false,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** Yes /local

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

<details><summary>LDAP configuration (delete this par if not used)</summary>

```
background_sync_interval: 43200background_sync_offset: 0background_sync_prefix: s01cleanUpJobOffset: 0enabled: yesinstalled_version: 1.8.0s01_lastChange: 1584442727s01has_memberof_filter_support: 1s01home_folder_naming_rule: s01last_jpegPhoto_lookup: 0s01ldap_agent_password: SW5NZW1vcmlhbTE5NDU=s01ldap_attributes_for_group_search: s01ldap_attributes_for_user_search: s01ldap_backup_host: s01ldap_backup_port: s01ldap_base: dc=corp,dc=dtgroup,dc=rus01ldap_base_groups: s01ldap_base_users: s01ldap_cache_ttl: 600s01ldap_configuration_active: 1s01ldap_default_ppolicy_dn: s01ldap_display_name: displaynames01ldap_dn: CN=Administrator,CN=Users,dc=corp,dc=dtgroup,dc=rus01ldap_dynamic_group_member_url: s01ldap_email_attr: mails01ldap_experienced_admin: 0s01ldap_expert_username_attr: samaccountnames01ldap_expert_uuid_group_attr: s01ldap_expert_uuid_user_attr: samaccountnames01ldap_ext_storage_home_attribute: s01ldap_gid_number: gidNumbers01ldap_group_display_name: cns01ldap_group_filter: s01ldap_group_filter_mode: 0s01ldap_group_member_assoc_attribute: s01ldap_groupfilter_groups: s01ldap_groupfilter_objectclass: s01ldap_host: corp.dtgroup.rus01ldap_login_filter: (&(&(|(objectclass=person))(userAccountControl=512)(|(|(memberof=CN=Cloud access,OU=storage groups,OU=groups,OU=dtgroup,DC=corp,DC=dtgroup,DC=ru)(primaryGroupID=1255))))(|(samaccountname=%uid)(|(mailPrimaryAddress=%uid)(mail=%uid)(entryUUID=%uid))))s01ldap_login_filter_mode: 1s01ldap_loginfilter_attributes: s01ldap_loginfilter_email: 0s01ldap_loginfilter_username: 1s01ldap_nested_groups: 0s01ldap_override_main_server: s01ldap_paging_size: 500s01ldap_port: 389s01ldap_quota_attr: s01ldap_quota_def: s01ldap_tls: 0s01ldap_turn_off_cert_check: 0s01ldap_turn_on_pwd_change: 0s01ldap_user_avatar_rule: defaults01ldap_user_display_name_2: s01ldap_user_filter_mode: 1s01ldap_userfilter_groups: s01ldap_userfilter_objectclass: persons01ldap_userlist_filter: (&(|(objectclass=person))(userAccountControl=512)(|(|(memberof=CN=Cloud access,OU=storage groups,OU=groups,OU=dtgroup,DC=corp,DC=dtgroup,DC=ru)(primaryGroupID=1255))))s01use_memberof_to_detect_membership: 1types: authentication
```
</details>

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Nextcloud log</summary>

```
{"reqId":"UJG4TLJWYMgFyP2sU8oG","level":3,"time":"2020-03-17T15:07:08+03:00","remoteAddr":"192.168.1.225","user":"--","app":"public","method":"MKCOL","url":"/public.php/webdav/1/gopro","message":{"Exception":"Error","Message":"Call to a member function getUID() on null","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooks.php","line":638,"function":"getOwner","class":"OC\\Files\\View","type":"->","args":["/source EXCHANGE/MERZ 12.03/1/gopro"]},{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooks.php","line":190,"function":"getSourcePathAndOwner","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/source EXCHANGE/MERZ 12.03/1/gopro"]},{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooks.php","line":148,"function":"addNotificationsForFileAction","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/source EXCHANGE/MERZ 12.03/1/gopro","file_created","","created_public"]},{"file":"/var/www/nextcloud/apps/activity/lib/FilesHooksStatic.php","line":47,"function":"fileCreate","class":"OCA\\Activity\\FilesHooks","type":"->","args":["/source EXCHANGE/MERZ 12.03/1/gopro"]},{"file":"/var/www/nextcloud/lib/private/legacy/hook.php","line":111,"function":"fileCreate","class":"OCA\\Activity\\FilesHooksStatic","type":"::","args":[{"run":true,"path":"/source EXCHANGE/MERZ 12.03/1/gopro"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1275,"function":"emit","class":"OC_Hook","type":"::","args":["OC_Filesystem","post_create",{"run":true,"path":"/source EXCHANGE/MERZ 12.03/1/gopro"}]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1203,"function":"runHooks","class":"OC\\Files\\View","type":"->","args":[["create","write"],"/source EXCHANGE/MERZ 12.03/1/gopro",true]},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":269,"function":"basicOperation","class":"OC\\Files\\View","type":"->","args":["mkdir","/1/gopro",["create","write"]]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":189,"function":"mkdir","class":"OC\\Files\\View","type":"->","args":["/1/gopro"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1210,"function":"createDirectory","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->","args":["gopro"]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":590,"function":"createCollection","class":"Sabre\\DAV\\Server","type":"->","args":["1/gopro",{"__class__":"Sabre\\DAV\\MkCol"}]},{"function":"httpMkcol","class":"Sabre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.dtgroup.ru/public.php/webdav/1/gopro","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpMkcol"],[{"absoluteUrl":"https://cloud.dtgroup.ru/public.php/webdav/1/gopro","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:MKCOL",[{"absoluteUrl":"https://cloud.dtgroup.ru/public.php/webdav/1/gopro","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.dtgroup.ru/public.php/webdav/1/gopro","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php","line":109,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/nextcloud/public.php","line":81,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/publicwebdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/View.php","Line":1690,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363","version":"18.0.2.2"}
```
</details>

**Comment by simm4ik** [comment]
I found that the activity app was the reason of such behavior. I'll open issue on app's page.

**Comment by Uwe-MrT** [comment]
please tell me the link to your  issue on app's page
i have same problems

**Comment by simm4ik** [comment]
https://github.com/nextcloud/activity/issues/439

You can deactivate activity app until this issue is resolved.

Regards, Artem


ср, 18 мар. 2020 г. в 19:36, Uwe-MrT <notifications@github.com>:

**Comment by massa007** [comment]
That solved the issue while creating files/folders but I´m still not able to delete/modify anything! 
Is this only me?

**Comment by jessrbird** [comment]
I've noticed the same thing as massa007. Deactivate activity app helps, but still unable to delete/modify. If I try to upload a file with the same name, I get the "1 file conflict" message, I choose to "have a number added" to the new file and click continue. It goes through the upload process, then fails with unknown error and  "Error: Call to a member function getUID() on null" in the logs.

**Comment by gabrielklein** [comment]
Similar issue...  Disabling "activity" doesn't work.

`array (
  'reqId' => 'xxx',
  'level' => 3,
  'time' => '2020-03-31T22:27:38+00:00',
  'remoteAddr' => 'xxx',
  'user' => '--',
  'app' => 'public',
  'method' => 'PUT',
  'url' => '/public.php/webdav/testfile3.txt',
  'message' => 
  array (
    'Exception' => 'Error',
    'Message' => 'Call to a member function getUID() on null',
    'Code' => 0,
    'Trace' => 
    array (
      0 => 
      array (
        'file' => '/home/data/c.mysite.com/lib/private/Files/Filesystem.php',
        'line' => 907,
        'function' => 'getOwner',
        'class' => 'OC\\Files\\View',
        'type' => '->',
        'args' => 
        array (
          0 => '/BT01/testfile3.txt',
        ),
      ),
      1 => 
      array (
        'file' => '/home/data/c.mysite.com/apps/files_versions/lib/Storage.php',
        'line' => 101,
        'function' => 'getOwner',
        'class' => 'OC\\Files\\Filesystem',
        'type' => '::',
        'args' => 
        array (
          0 => '/BT01/testfile3.txt',
        ),
      ),
      2 => 
      array (
        'file' => '/home/data/c.mysite.com/apps/files_versions/lib/Storage.php',
        'line' => 182,
        'function' => 'getUidAndFilename',
        'class' => 'OCA\\Files_Versions\\Storage',
        'type' => '::',
        'args' => 
        array (
          0 => '/BT01/testfile3.txt',
        ),
      ),
      3 => 
      array (
        'file' => '/home/data/c.mysite.com/apps/files_versions/lib/Hooks.php',
        'line' => 62,
        'function' => 'store',
        'class' => 'OCA\\Files_Versions\\Storage',
        'type' => '::',
        'args' => 
        array (
          0 => '/BT01/testfile3.txt',
        ),
      ),
      4 => 
      array (
        'file' => '/home/data/c.mysite.com/lib/private/legacy/hook.php',
        'line' => 111,
        'function' => 'write_hook',
        'class' => 'OCA\\Files_Versions\\Hooks',
        'type' => '::',
        'args' => 
        array (
          0 => 
          array (
            'path' => '/BT01/testfile3.txt',
            'run' => true,
          ),
        ),
      ),
      5 => 
      array (
        'file' => '/home/data/c.mysite.com/apps/dav/lib/Connector/Sabre/File.php',
        'line' => 374,
        'function' => 'emit',
        'class' => 'OC_Hook',
        'type' => '::',
        'args' => 
        array (
          0 => 'OC_Filesystem',
          1 => 'write',
          2 => 
          array (
            'path' => '/BT01/testfile3.txt',
            'run' => true,
          ),
        ),
      ),
      6 => 
      array (
        'file' => '/home/data/c.mysite.com/apps/dav/lib/Connector/Sabre/File.php',
        'line' => 249,
        'function' => 'emitPreHooks',
        'class' => 'OCA\\DAV\\Connector\\Sabre\\File',
        'type' => '->',
        'args' => 
        array (
          0 => true,
        ),
      ),
      7 => 
      array (
        'file' => '/home/data/c.mysite.com/3rdparty/sabre/dav/lib/DAV/Server.php',
        'line' => 1130,
        'function' => 'put',
        'class' => 'OCA\\DAV\\Connector\\Sabre\\File',
        'type' => '->',
        'args' => 
        array (
          0 => '*** sensitive parameter replaced ***',
        ),
      ),
      8 => 
      array (
        'file' => '/home/data/c.mysite.com/3rdparty/sabre/dav/lib/DAV/CorePlugin.php',
        'line' => 513,
        'function' => 'updateFile',
        'class' => 'Sabre\\DAV\\Server',
        'type' => '->',
        'args' => 
        array (
          0 => '*** sensitive parameters replaced ***',
        ),
      ),
      9 => 
      array (
        'function' => 'httpPut',
        'class' => 'Sabre\\DAV\\CorePlugin',
        'type' => '->',
        'args' => 
        array (
          0 => 
          array (
            'absoluteUrl' => 'https://c.mysite.com/public.php/webdav/testfile3.txt',
            '__class__' => 'Sabre\\HTTP\\Request',
          ),
          1 => 
          array (
            '__class__' => 'Sabre\\HTTP\\Response',
          ),
        ),
      ),
      10 => 
      array (
        'file' => '/home/data/c.mysite.com/3rdparty/sabre/event/lib/EventEmitterTrait.php',
        'line' => 105,
        'function' => 'call_user_func_array',
        'args' => 
        array (
          0 => 
          array (
            0 => 
            array (
              '__class__' => 'Sabre\\DAV\\CorePlugin',
            ),
            1 => 'httpPut',
          ),
          1 => 
          array (
            0 => 
            array (
              'absoluteUrl' => 'https://c.mysite.com/public.php/webdav/testfile3.txt',
              '__class__' => 'Sabre\\HTTP\\Request',
            ),
            1 => 
            array (
              '__class__' => 'Sabre\\HTTP\\Response',
            ),
          ),
        ),
      ),
      11 => 
      array (
        'file' => '/home/data/c.mysite.com/3rdparty/sabre/dav/lib/DAV/Server.php',
        'line' => 479,
        'function' => 'emit',
        'class' => 'Sabre\\Event\\EventEmitter',
        'type' => '->',
        'args' => 
        array (
          0 => 'method:PUT',
          1 => 
          array (
            0 => 
            array (
              'absoluteUrl' => 'https://c.mysite.com/public.php/webdav/testfile3.txt',
              '__class__' => 'Sabre\\HTTP\\Request',
            ),
            1 => 
            array (
              '__class__' => 'Sabre\\HTTP\\Response',
            ),
          ),
        ),
      ),
      12 => 
      array (
        'file' => '/home/data/c.mysite.com/3rdparty/sabre/dav/lib/DAV/Server.php',
        'line' => 254,
        'function' => 'invokeMethod',
        'class' => 'Sabre\\DAV\\Server',
        'type' => '->',
        'args' => 
        array (
          0 => 
          array (
            'absoluteUrl' => 'https://c.mysite.com/public.php/webdav/testfile3.txt',
            '__class__' => 'Sabre\\HTTP\\Request',
          ),
          1 => 
          array (
            '__class__' => 'Sabre\\HTTP\\Response',
          ),
        ),
      ),
      13 => 
      array (
        'file' => '/home/data/c.mysite.com/apps/dav/appinfo/v1/publicwebdav.php',
        'line' => 109,
        'function' => 'exec',
        'class' => 'Sabre\\DAV\\Server',
        'type' => '->',
        'args' => 
        array (
        ),
      ),
      14 => 
      array (
        'file' => '/home/data/c.mysite.com/public.php',
        'line' => 81,
        'args' => 
        array (
          0 => '/home/data/c.mysite.com/apps/dav/appinfo/v1/publicwebdav.php',
        ),
        'function' => 'require_once',
      ),
    ),
    'File' => '/home/data/c.mysite.com/lib/private/Files/View.php',
    'Line' => 1690,
    'CustomMessage' => '--',
  ),
  'userAgent' => 'curl/7.65.3',
  'version' => '18.0.3.0',
)`

**Comment by muxflash** [comment]
idem. please help

**Comment by simm4ik** [comment]
I think you need to open another issue with reproducing steps as in my case
there was no such problems.

С уважением,

Александров Артем


ср, 1 апр. 2020 г. в 13:05, muxflash <notifications@github.com>:

**Comment by Swingslain** [comment]
same problem! any fix yet?

**Comment by asoral** [comment]
I am also facing the same issue. Any fix? Why is this closed?

**Comment by metalcated** [comment]
If anyone is using php fpm, restart the service and see if that helps.
