### ISSUE TITLE
Can not open App Store at multiple NC Versions

### ISSUE THREAD

**Issue by weiger96** [nextcloud/server#19991]
### Actual behaviour
If I wants to open the App Store at the web page I got the below error message. I tried it with a backup Nextcloud but it did not work. Unfortunately I did not test it for a long time. Is it an configuration failure?

### Server configuration

**Operating system:**
Raspbian
**Web server:**
Apache2
**Database:**
MariaDB
**PHP version:**
PHP7.3
**Nextcloud version:** (see Nextcloud admin page)
18.02
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
web updater

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption

```
</details

$CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => '',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '192.168.178.10',
  ),
  'datadirectory' => '/mnt/nextcloud-data/',
  'overwrite.cli.url' => 'https://192.168.178.10',
  'dbtype' => 'mysql',
  'version' => '18.0.2.2',
  'dbname' => 'nextclouddb2',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mysql.utf8mb4' => true,
  'app_install_overwrite' => true,
  0 => 
  array (
    0 => 'calendar',
    1 => 'spreed',
    2 => 'files_texteditor',
  ),
  'updater.secret' => '',
  'data-fingerprint' => '',
  'updater.release.channel' => 'stable',
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
);

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no.


### Logs
[PHP] Error: in_array() expects parameter 2 to be array, bool given at /var/www/html/nextcloud/apps/settings/lib/Controller/AppSettingsController.php#274

GET /index.php/settings/apps/list
from 192.168.178.22 by jweigand at 2020-03-16T20:29:56+00:00

**Comment by kesselb** [comment]
Have you asked the friendly people at https://help.nextcloud.com for advice?

**Comment by weiger96** [comment]
yes, but for a week no comment.

**Comment by weiger96** [comment]
I tested your pull request and it works now. Thanks.
Can you tell me, why app-install_overwrite is not an array? Any misconfiguration or something else in the past?
