### ISSUE TITLE
config datadirectory not persistent

### ISSUE THREAD

**Issue by mokkin** [nextcloud/server#19997]
After updating some apps my modified `datadirectory` setting in the config.php gets set back.

I modified it to:
`  'datadirectory' => ((php_sapi_name() != 'cli') ? '/var/www/vhosts/hosting123456.subdomain.example.net' : '').'/httpdocs/nextcloud/data',
`
After updating it was reset to the correct location, but without php cli function:
`  'datadirectory' => '/var/www/vhosts/hosting123456.subdomain.example.net/httpdocs/nextcloud/data',
`

### Steps to reproduce
1. update apps

### Expected behaviour
datadirectory setting should be persistent

### Actual behaviour
datadirectory reset

### Server configuration

**Operating system:**
Debian 9 shared webhosting

**Web server:**
Apache with Nginx Proxy

**Database:**
mysql

**PHP version:**
7.3.15

**Nextcloud version:** (see Nextcloud admin page)
18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
since OwnCloud 4

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.3.1
  - photos: 1.0.0
  - previewgenerator: 2.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - files_readmemd
  - mail
  - maps
  - phonetrack
  - user_ldap


or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Adding code to `config.php` is not supported. What you see is that the expression is executed and the result is written. That's not a bug just not supported. 

https://github.com/nextcloud/server/issues/19181 will probably help.

**Comment by drewjosh** [comment]
@kesselb dang it ☹️ I thought I found the solution..

**Comment by drewjosh** [comment]
#19181 -> did indeed help! 😎👏🏻
