### ISSUE TITLE
Using user_saml app breaks occ command

### ISSUE THREAD

**Issue by herrfeuer** [nextcloud/server#1999]
### Steps to reproduce
1. Install & Configure Nextcloud
2. Login as admin and enable Saml Authentication app (user_saml)
3. Configure SAML App
4. Isuse any occ command (sudo -u nginx php70 /var/www/nextcloud/occ config:list)

### Expected behaviour
occ shoud execute the given command

### Actual behaviour
 sudo -u nginx php70 /var/www/nextcloud/occ config:list
An unhandled exception has been thrown:
Exception: The requested uri() cannot be processed by the script '/var/www/nextcloud/occ') in /var/www/nextcloud/lib/private/AppFramework/Http/Request.php:695
Stack trace:
#0 /var/www/nextcloud/lib/private/AppFramework/Http/Request.php(717): OC\AppFramework\Http\Request->getRawPathInfo()
#1 /var/www/nextcloud/apps/user_saml/appinfo/app.php(54): OC\AppFramework\Http\Request->getPathInfo()
#2 /var/www/nextcloud/lib/private/legacy/app.php(195): require_once('/var/www/nextcl...')
#3 /var/www/nextcloud/lib/private/legacy/app.php(153): OC_App::requireAppFile('user_saml')
#4 /var/www/nextcloud/lib/private/legacy/app.php(123): OC_App::loadApp('user_saml')
#5 /var/www/nextcloud/lib/private/Console/Application.php(96): OC_App::loadApps()
#6 /var/www/nextcloud/console.php(89): OC\Console\Application->loadCommands(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#8 {main}

### Server configuration
**Operating system:** Centos 7

**Web server:** nginx/1.10.1

**Database:** sqlite 3.7.17, but same with pgsql

**PHP version:** PHP 7.0.12

**Nextcloud version:** 10.0.1 but confusing output from occ status:
  - version: 9.1.1.5
  - versionstring: 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-10.0.1.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_saml: 1.2.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocs2zuz59gtn",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "realhostname.domain.tld"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbtype": "sqlite3",
        "version": "9.1.1.5",
        "logtimezone": "UTC",
        "installed": true
    }
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** SAML

### Client configuration
**Browser:** Any

**Operating system:** Any

### Logs

No logs generated by occ command

**Comment by LukasReschke** [comment]
Please reopen at https://github.com/nextcloud/user_saml

**Comment by herrfeuer** [comment]
https://github.com/nextcloud/user_saml #46
