### ISSUE TITLE
Enable SameSite for session cookies

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#19992]
### Steps to reproduce
1. Use https://webbkoll.dataskydd.net/en to analyze any NC instance (I used 18.0.2.2)
2. View results. Nearly perfect, except for
- 'missing' "style-src 'unsafe-inline';" (fine using https://csp-evaluator.withgoogle.com/), and 
- the session cookies not being "SameSite"

### Expected behaviour
All cookies should state their permissiveness as explained on https://web.dev/samesite-cookies-explained/ . Session cookies only need to be read for the same domain, the Passphrase probably initially (when linking from elsewhere or opening an new tab) so they should be marked 'Lax' (or 'Strict' if possible). If there is a technical reason for being permissive, they should be marked 'none'.

### Actual behaviour
The session cookies (e.g. oc_sessionPassphrase) are either marked 'None' or not marked at all (not sure how to properly find that out, I presume FX dev console tries to be smart, it displays 'None').

### Server configuration
OS: Arch Linux, Nginx 1.16.1, MariaDB 10.4.12, PHP 7.4, NC 18.0.2.2, updated from 17, installed from nextcloud.com, singing status: "No errors have been found."
Activated apps: all avalable twofactor_-apps

all the rest probably irrelevant for this bug

**Comment by kesselb** [comment]
Thanks :+1: Please use the search :mag_right:

**Comment by nursoda** [comment]
Huh? I _did_ search before opening this issue, only found [this](https://github.com/nextcloud/server/issues/15028), which is different. I'm a bit irritated what I did miss or do wrong. A hint would have been nice.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/17075

Issues with reference to this pull request are findable if you search for samesite. Add the cookie name for less results. 

Thanks for the report 👍 Reports like yours (with clear steps to reproduce) are always welcome.

**Comment by nursoda** [comment]
Thanks a lot, sorry I did not find it.
