### ISSUE TITLE
Groupfolder and Database export app to enable relocation of NC if hosted NC is used

### ISSUE THREAD

**Issue by mmetzmac** [nextcloud/server#20014]
It would be nice, having a database backup with download functionallity and a similiar import functionality.

Reason: if Nextcloud is used as hosted service (i. e. Hetzner StorageCloud) it sometimes happens, that one would like to change the provider or to switch to another NC package (more space, etc.). If so, all users must register in the new instance as it is not possible, moving users simply to a new location/Nextcloud installation. The same applies to Groupfolders, which only can be created after the Users and user permission is setup in the system. Having a kind of "automation" for this, would ease up the change of NC packages/providers.

An App would help, moving at least the community and the Groupfolders to a new installation. Having the Groupfolders included would be brilliant. I think, I can tell a user, uploading his/her personal contant later on again, works - but Groupfolders, its content and permissions might be another story?!

Dont know, whether this is possible but think it's not worth to ask.

**Comment by szaimen** [comment]
Please request a database export and file export from your hoster for that. This is not really feasible for Nextcloud itself, imho.
But cc @nextcloud/server-triage for further input on this.
