### ISSUE TITLE
External storage issues

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#20012]
Nextcloud 15.0.9
Php 7.3

Hi when i want use CIFS/SMB external storage i got issues : 

Downloading files < 35K works 
Downloading files > 35K not work

I already put Nextcloud on debug... but nothing appear, same in apache2 errors logs. 
When i click on dowload 
![Error](https://user-images.githubusercontent.com/38983960/76945461-cee22680-6902-11ea-8747-205f2e21e871.png)

This issue is not happening when i'm not inside external storage share

Best regards

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
