### ISSUE TITLE
Only show app ratings in the apps mgmt after a certain amount of votes

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2001]
Currently a lot of apps by default have 2.5 stars as rating showed, which makes them look very bad. These apps actually received no ratings yet, and showing that is simply wrong.

The rating should not be shown at all until there are a certain amount of votes on the app, for example 10.

cc @nextcloud/appstore

**Comment by BernhardPosselt** [comment]
Solution here is probably to also expose the amount of ratings in the API and filter out ratings below a threshold.  Can you create a new ticket in the app store @jancborchardt ?

**Comment by jancborchardt** [comment]
@BernhardPosselt not sure what I should exactly open there. Can you do it?

**Comment by MorrisJobke** [comment]
> @BernhardPosselt not sure what I should exactly open there. Can you do it?

It's already done ;)

**Comment by MorrisJobke** [comment]
Fix is in #2425
