### ISSUE TITLE
LDAP user cannot login and be delete

### ISSUE THREAD

**Issue by wingsoul** [nextcloud/server#20010]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. configure LDAP/AD intergration
2. login with LDAP user

### Expected behaviour
it should able to log in and delete

### Actual behaviour
User A and user B are in the same OU
User A can login but user B cannot

even if delete by CLI, There also has error
`root@ip-172-31-0-218:/var/www/html/nextcloud# sudo -u www-data php occ user:delete BF49A323-3C43-4135-8500-C444A42498C7
The specified user could not be deleted. Please check the logs.`

### Server configuration

**Operating system:**
ubuntu 18.0.4
**Web server:**
nginx 17.9
**Database:**
10.1.44-MariaDB
**PHP version:**
7.2.28
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 15.0.1 RC 1
**Updated from an older Nextcloud/ownCloud or fresh install:**
install directly without upgrading and used around 1 year
**Where did you install Nextcloud from:**
git clone --branch stable15 https://github.com/nextcloud/server.git nextcloud
composer install

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - cloud_federation_api: 0.1.0
  - dav: 1.8.0
  - encryption: 2.3.0
  - federatedfilesharing: 1.5.0
  - files: 1.10.0
  - files_external: 1.6.0
  - files_pdfviewer: 1.2.1
  - files_sharing: 1.7.0
  - files_versions: 1.8.0
  - lookup_server_connector: 1.3.0
  - oauth2: 1.3.0
  - provisioning_api: 1.5.0
  - systemtags: 1.5.0
  - theming: 1.6.0
  - twofactor_backupcodes: 1.4.1
  - user_ldap: 1.5.0
  - workflowengine: 1.5.0
Disabled:
  - accessibility
  - admin_audit
  - comments
  - federation
  - files_trashbin
  - sharebymail
  - testing
  - updatenotification
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocnosbmitala',
  'passwordsalt' => 'cKCcEqmj3uCYNPHbK1QZdVvza2aByT',
  'secret' => 'L0+2rUkcx4htv7VNNuw0x1hTNc5uNmNnPe3da8U4fuM5AisC',
  'log_type' => 'file',
  'logfile' => '/var/www/html/nextcloud/nextcloud.log',
  'logfilemode' => 416,
  'loglevel' => '0',
  'logdateformat' => 'F d, Y H:i:s',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'force_language' => 'en',
  'trusted_domains' => 
  array (
    0 => 'a.b.com',
  ),
  'datadirectory' => '/var/www/html/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '15.0.1.0',
  'overwrite.cli.url' => 'https://a.b.com',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'password',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'updater.release.channel' => 'stable',
  'updater.secret' => '$2y$10$QbJlXbxvKHpX/.IAlKZdpei1MRfKNlyjH5A6NOsEOh.kkDKbTCT/K',
);


```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration
```
Please let me know if any information has to be provided
I have tried "sudo -u www-data php occ ldap:show-config" but too many company's sensitive data.
But I believe the LDAP setting is fine since most of our users can log in.
```

### Client configuration
**Browser and Operating system:**
Gentoo Linux with Brave, Chrome, firefox
WIndows 10 with Chrome

### Logs
``

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"QTYfdwFnjEYc3vPawsGs","level":0,"time":"March 18, 2020 01:01:57","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"No cache entry found for \/appdata_ocnosbmitala\/dav-photocache\/cffd9f3e50c4d6e79f095fd7e0d01c8b (storage: local::\/var\/www\/html\/nextcloud\/data\/, internalPath: appdata_ocnosbmitala\/dav-photocache\/cffd9f3e50c4d6e79f095fd7e0d01c8b)","userAgent":"--","version":"15.0.1.0"}
{"reqId":"QTYfdwFnjEYc3vPawsGs","level":1,"time":"March 18, 2020 01:01:57","remoteAddr":"","user":"--","app":"user_ldap","method":"","url":"--","message":"User BF49A323-3C43-4135-8500-C444A42498C7 is not marked as deleted, not cleaning up.","userAgent":"--","version":"15.0.1.0"}
{"reqId":"QTYfdwFnjEYc3vPawsGs","level":1,"time":"March 18, 2020 01:01:57","remoteAddr":"","user":"--","app":"user_ldap","method":"","url":"--","message":"User BF49A323-3C43-4135-8500-C444A42498C7 is not marked as deleted, not cleaning up.","userAgent":"--","version":"15.0.1.0"}
```
</details>

**Comment by skjnldsv** [comment]
cc @blizzz

**Comment by blizzz** [comment]
>  Nextcloud 15.0.1 RC 1 

:eyes: 

> User A and user B are in the same OU
User A can login but user B cannot

As this seems to be a config issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

> root@ip-172-31-0-218:/var/www/html/nextcloud# sudo -u www-data php occ user:delete BF49A323-3C43-4135-8500-C444A42498C7 The specified user could not be deleted. Please check the logs.

We don't write for LDAP (but there is an app for this). Otherwise, https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap_cleanup.html
