### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by PluginYML** [nextcloud/server#20015]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

How can I fix that?

**Comment by kesselb** [comment]
By using the search :)
