### ISSUE TITLE
post /login just fail........

### ISSUE THREAD

**Issue by chan17** [nextcloud/server#20024]
![image](https://user-images.githubusercontent.com/3273748/76988807-4b671a80-6980-11ea-95cb-62bba7635926.png)

when i am post /login,  just fail……

use Raspberry Pi(debian) / php7.3-fpm/  nextcloud-18.0.2

**this is my log:** 
`
{"reqId":"1nKmdiwZALiD2RScBHy7","level":3,"time":"2020-03-18T17:20:11+00:00","remoteAddr":"192.168.1.113","user":"--","app":"password_policy","method":"POST","url":"/login","message":{"Exception":"RuntimeException","Message":"App class OCA\\Password_Policy\\AppInfo\\Application is not setup via query() but directly","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/apps/password_policy/lib/AppInfo/Application.php","line":40,"function":"__construct","class":"OCP\\AppFramework\\App","type":"->","args":["password_policy"]},{"file":"/var/www/html/nextcloud/apps/password_policy/appinfo/app.php","line":23,"function":"__construct","class":"OCA\\Password_Policy\\AppInfo\\Application","type":"->","args":[]},{"file":"/var/www/html/nextcloud/lib/private/legacy/app.php","line":266,"args":["/var/www/html/nextcloud/apps/password_policy/appinfo/app.php"],"function":"require_once"},{"file":"/var/www/html/nextcloud/lib/private/legacy/app.php","line":155,"function":"requireAppFile","class":"OC_App","type":"::","args":["password_policy"]},{"file":"/var/www/html/nextcloud/lib/private/legacy/app.php","line":128,"function":"loadApp","class":"OC_App","type":"::","args":["password_policy"]},{"file":"/var/www/html/nextcloud/lib/base.php","line":1005,"function":"loadApps","class":"OC_App","type":"::","args":[]},{"file":"/var/www/html/nextcloud/index.php","line":38,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/nextcloud/lib/public/AppFramework/App.php","Line":80,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36","version":"18.0.2.2"}
`

**Comment by kesselb** [comment]
Please ask the community at https://help.nextcloud.com for configuration issues. If you found a bug and want to report it cool but the issue template is required. All the information.
