### ISSUE TITLE
Migrate tabs to vue

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#20020]
Now that we got a proper standalone sidebar, we need to make the last tabs standalone too:
- [x] Comments https://github.com/nextcloud/server/pull/23173
- [x] Activity https://github.com/nextcloud/activity/pull/581
- [x] Versions #26675  https://github.com/nextcloud/server/pull/34769
- [ ] Tags

Refs: #17737 #15719, might conflict with https://github.com/nextcloud/server/issues/658
cc @nextcloud/javascript

**Comment by matiasdelellis** [comment]
Hello everyone,
I am trying to migrate my application to the new api.  https://github.com/matiasdelellis/facerecognition/pull/268

Add the correct listender, the app adds the scripts when open the sidebar, and now get to the same point as the apps you comment in this issue.

> TypeError: OCA.Files.DetailTabView is undefined

Can you at least guide me on what should I do? The documentation of the original issues is using vue.js. I honestly have no ability to migrate to vue. Is it mandatory?

Thanks,
Matias

**Comment by skjnldsv** [comment]
Hey! Unfortunately, the main sidebar requires a vue component yes.
We plan to improve this so anything can be registered in the future.

**Comment by matiasdelellis** [comment]
> Hey! Unfortunately, the main sidebar requires a vue component yes.

Ohh. I did not want to learn vue .. I guess I will have to try. :sweat: 

Thanks for clarifying..

**Comment by skjnldsv** [comment]
> Ohh. I did not want to learn vue .. I guess I will have to try.

Yeah, sorry :)
You can still use the old legacy way though.
See how we do for the old tabs like comments

**Comment by skjnldsv** [comment]
Wait, you actually already had a tab. So it should still works.
You shouldn't have to change anything for it to work with the new sidebar.

**Comment by matiasdelellis** [comment]
Hi @skjnldsv 

I didn't want to deviate this report too much. Sorry for that. 

> You can still use the old legacy way though.

Yes, but it was not shown in photos because before dont manage the `LoadSidebar` event. Now fix this, but it doesn't work.

About `TypeError: OCA.Files.DetailTabView is undefined` adding the script with `Util::addScript('files', 'detailtabview');` fixes it, but still doesn't show and now there is any log. I don't think it's an good solution either. Note that most third-party app sidebars extend from DetailTabView just like the comments app.

> See how we do for the old tabs like comments

Also remember that my original report was this https://github.com/nextcloud/photos/issues/243, and the comment sidebar also is not showed in photos.

**Comment by skjnldsv** [comment]
> Yes, but it was not shown in photos because before dont manage the `LoadSidebar` event. Now fix this, but it doesn't work.

Ah, it will no work in photos.
You need to make sure it's compatible with the new standard then. We ketp compatibiliy for files for legacy tabs. But you still need to have a proper implementation to support the global sidebar. Sorry for the misanderstanding :confused:

**Comment by e-alfred** [comment]
This should be part of https://github.com/nextcloud/server/issues/20953 it seems.

**Comment by enochterrymize** [comment]
[files_versions.zip](https://github.com/nextcloud/server/files/6348381/files_versions.zip)

**Comment by PVince81** [comment]
versions was done in https://github.com/nextcloud/server/pull/34769

**Comment by artonge** [comment]
Just discovered this tracking ticket: activity was done last year https://github.com/nextcloud/activity/pull/581

**Comment by szaimen** [comment]
So everything done then? :)

**Comment by artonge** [comment]
Tags are not done yet

**Comment by szaimen** [comment]
> Tags are not done yet

I thought they dont have a separate tab and are already inregrated into the sidebar?

**Comment by artonge** [comment]
Not sure if @skjnldsv still wants to track them. Let's wait for his input tomorrow :)

**Comment by skjnldsv** [comment]
> I thought they dont have a separate tab and are already inregrated into the sidebar?

But they're still not vue :)
There is a ticket about this laying somewhere i think
