### ISSUE TITLE
Cannot determine UUID for AD Groups

### ISSUE THREAD

**Issue by zippytiff** [nextcloud/server#20029]
Hi

Since upgrading to Nextcloud 18, when i add a new group from AD into the nextcloud LDAP scope, its now saying....

note all sensitive info removed

> in logging

Info | user_ldap | Cannot determine UUID for cn=_test group,ou=--removed--users,dc=--removed--,dc=--removed--. Skipping. |  
-- | -- | -- | --

> nextcloud.log

{"reqId":"EHwIaADHcdySgo6ZlscJ","level":1,"time":"2020-03-19T11:44:03+00:00","remoteAddr":"--removed--","user":"--removed--","app":"user_ldap","method":"GET","url":"/index.php/settings/users","message":"Cannot determine UUID for cn=_test group,ou=--removed--users,dc=--removed--,dc=--removed--. Skipping.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36","version":"18.0.2.2"}
{"reqId":"6f2HiVJYVOYvyFBKobVy","level":1,"time":"2020-03-19T11:44:04+00:00","remoteAddr":"--removed--","user":"--removed--","app":"user_ldap","method":"GET","url":"/ocs/v2.php/cloud/users/details?offset=0&limit=25&search=","message":"Cannot determine UUID for cn=_test group,ou=--removed--users,dc=--removed--,dc=--removed--. Skipping.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36","version":"18.0.2.2"}

so i cannot use new group as yet, new users unaffected

any additional debug ? logs i can pull ? commands i can run

**Comment by EBS-DarkD** [comment]
I'm facing the same issue too.
Nextcloud: 18.02
Operating System: Debian 9
Apache: 2.4.25
PHP: 7.3

Have 46 groups which are working fine and were added when we were still running v17.
Just gone to add two groups since upgrading to v18.
Groups appear in the LDAP groups but not in the groups on the user page and I'm seeing the same "Cannot determine UUID" message for both groups repeating constantly

**Comment by Lenezir** [comment]
Same issue here too.
Nextcloud: 18.02
OS : Ubuntu Server 20.04
Apache: 2.4.41
PHP: 7.4.3

It worked perfectly with my old version of NC 15.0.14 on my Ubuntu 16.04.
On my fresh install, with the exact same LDAP request, the test button display the exact number of groups, the LDAP users are shown, but like above on my logs I've the message: 


Info | user_ldap | Cannot determine UUID for cn=mygroup,ou=groupes,dc=myndd,dc=fr. Skipping.
-- | -- | --

I've one line per group.

**Comment by Lenezir** [comment]
Bug still present in the latest 18.0.3.

**Comment by ArtemyBo** [comment]
Hi!
Same issue too.
Nextcloud: 18.0.3
OS: CentOS Linux release 7.6.1810 
Apache: 2.4.6
MariaDB: 10.2.19
PHP: 7.3.15

**Comment by kesselb** [comment]
This sounds similar to https://github.com/nextcloud/server/issues/19970 and might be fixed by https://github.com/nextcloud/server/pull/20039.

**Comment by zippytiff** [comment]
Thank you

**Comment by Lenezir** [comment]
While waiting for the update, this trick works : https://github.com/nextcloud/server/issues/19970#issuecomment-601049756

**Comment by ArtemyBo** [comment]
Confirm!
Reverting back to https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/apps/user_ldap/lib/Access.php fixes the issue.

**Comment by 11harveyj** [comment]
Same issue here, although I found going into the expert tab of the LDAP configuration and manually setting the setting "UUID Attribute for groups" to "objectGUID" (This is from Active Directory, YMMV) seems to solve the issue.
