### ISSUE TITLE
File Restore: When files are deleted from S3 folder, user cannot see file to restore

### ISSUE THREAD

**Issue by joeltheukranian** [nextcloud/server#20023]
V18.0.0 on Ubuntu (Amazon)

1. Admin -> Share folder1 to User1 (non-admin). Folder1 configured for S3 storage.
2. User1 Upload file f1.txt to folder1
3. Login as User1
4. User1 delete f1.txt
5. User1 try to recover f1.txt
6. User1 cannot see f1.txt

My admin looked into this. When files are deleted from S3, the files are moved from S3 to a local file system. Is this affecting the restore?

Admin can see and restore. User cannot see file in order to restore

-Joel

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
