### ISSUE TITLE
IAppManager->getAppWebPath() is wrong when using custom app directories

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/server#20041]
The [IAppManager->getAppWebPath(string $appId)](https://github.com/nextcloud/server/blob/d3401efa2d368e420c8d805a03c6779a2b9f5234/lib/public/App/IAppManager.php#L142) reports wrong URL when  using custom app directories as per https://docs.nextcloud.com/server/latest/admin_manual/apps_management.html#using-custom-app-directories
Shouldn't the **web** path always be reported as _/**apps**/app_name_ and NOT as _/**apps2**/app_name_

**Comment by kesselb** [comment]
apps2 seems to be correct for example from the docs.

**Comment by SergeyMosin** [comment]
but I will not be able to reach my app at https://www.domain.com/index.php/**apps2**/my_app/... because it is served at https://www.domain.com/index.php/**apps**/my_app/...

**Comment by kesselb** [comment]
I don't think that custom app directories work that way. If you configure other_apps as second apps directory it also needs to be reachable from the web by using other_apps/some_app.

**Comment by SergeyMosin** [comment]
> it also needs to be reachable from the web by using other_apps/some_app

Are there page controller settings for that or would I do it in ``routes.php`` somehow ?

**Comment by kesselb** [comment]
I don't know. What are you trying to do? If some_app is installed to apps2 it's reachable via nextcloud/apps2/some_app. Installed to apps it's reachable via nextcloud/apps/some_app. The custom app directories are not merged.

**Comment by SergeyMosin** [comment]
I have an app installed in nextcloud/apps2/some_app and on the **web**  it is only reachable at https://.../index.php/**apps**/some_app and NOT at https://.../index.php/**apps2**/some_app . 
However, the IAppManager->getApp**Web**Path() says that I can find it at .../**apps2**/some_app

**Comment by kesselb** [comment]
Ah. I think you are using getAppWebPath for the wrong thing. To generate urls to your app please use the url generator. The path returned by getAppWebPath can be used to generate paths to static assets for example.

**Comment by SergeyMosin** [comment]
That makes sense.

Thanks
