### ISSUE TITLE
l10n: Need context for string "({scope})"

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#20059]
https://github.com/nextcloud/server/blob/a0058fe60177c92c6257804d7115ebd1766e64a8/core/js/systemtags/systemtags.js#L48

Reported at Transifex. See https://www.transifex.com/nextcloud/nextcloud/translate/#de_DE/$/90994219?q=issue%3Aopen

**Comment by kesselb** [comment]
Guessing from the code it's either restricted or invisible. That's related to tags and is about a tag that can be used by end users or administrators.

**Comment by rakekniven** [comment]
So, what what does this mean for translators? Does we need to translate it?

**Comment by gary-kim** [comment]
I don't think that translation is necessary at all. The scope that is being added there is a string that has already been translated. I'll make a PR.
