### ISSUE TITLE
App menu icons dissapear when using the file app on firefox

### ISSUE THREAD

**Issue by Luticus** [nextcloud/server#2005]
### Steps to reproduce
1.launch nextcloud in firefox
2.make sure you're using the files app
3.click the apps menu and observe the app icons disappear

### Expected behaviour
Tell us what should happen
Icons should stay visible

### Actual behaviour
Tell us what happens instead
Icons disappear

### Server configuration
**Operating system**:
Debian Jessie
**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update

**Where did you install Nextcloud from:**
downloaded from nextcloud site

**Signing status:**
<details>
<summary>Signing status</summary>
Disabled this functionality due to the external app storing custom icon files in it's directory.  Got tired of that triggering the alert.
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes, google, local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
firefox/chrome

**Operating system:**
Debian Jessie and Debian Stretch
Mac OS

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

I know there's a few missing details above, like the applist.  I can comment on those when I get home.  Thanks.

**Comment by Luticus** [comment]
Above I stated that the browser am using is both firefox and chrome.  That's true but as far as I've seen the behavior is only noticed in Firefox.  Chrome seems to work.

**Comment by nickvergessen** [comment]
Yeah only happens in Firefox.
I tracked this down to the following line:
https://github.com/nextcloud/server/blob/890f752a6b57598ee6b2088a615c41f60d697847/core/js/js.js#L1843-L1843

When this line is commented out, the icons remain visible. Not sure how that is related thou.
I guess something is killing the SVG invert-filter...

@juliushaertl @nextcloud/javascript anyone with an idea?

**Comment by nickvergessen** [comment]
Happens on 10 and 11 (master)

**Comment by juliushaertl** [comment]
@nickvergessen I've just found this one:

**Comment by juliushaertl** [comment]
So it will be fixed in Firefox 51, but i guess we sould have a look for a workaround.

**Comment by nickvergessen** [comment]
Awesome,.... https://github.com/rexxars/react-hexagon/issues/4#issuecomment-254174681 was linked as a workaround, maybe you can extract something for us?

**Comment by juliushaertl** [comment]
I'll try this later today.

**Comment by MorrisJobke** [comment]
Fixed via #2018

**Comment by Luticus** [comment]
I implemented the work around in core/js/js.js and it seems to work so far.  Thank you very much for the fix!

**Comment by Luticus** [comment]
Fix breaks folders in the nextcloud interface.  Had to remove it, unfortunately.

**Comment by nickvergessen** [comment]
@Luticus try adding this on top:
https://github.com/nextcloud/server/pull/2036/files

**Comment by juliushaertl** [comment]
I'm sorry that i missed the javascript error in Firefox in my first PR. After a review of the Firefox issue, i made a new PR #2040 that applies the firefox hotfix to the svg filters as well.

**Comment by Luticus** [comment]
nickvergessen, the new line allows me to browse sub directories correctly but sadly doesn't fix the icon issue.
