### ISSUE TITLE
impossible to create user without setting a password

### ISSUE THREAD

**Issue by phonon112358** [nextcloud/server#20073]
### Steps to reproduce
1. Go to the user page
2. Try to create a new user with email address but without password

### Expected behaviour
A welcome email should be sent to the user's email address (see https://help.nextcloud.com/t/is-there-a-way-to-send-a-welcome-email-with-create-password-link-when-account-is-created/31505/2). 
Sometimes this works, but sometimes not!

### Actual behaviour
Sometimes (!), I get an error message that the password must contain at least one number (I have the password policy app enabled). 

This issue seems to be very similar to https://github.com/nextcloud/server/issues/6089.

### Server configuration

**Operating system:** Debian 10

**Web server:** nginx 

**PHP version:** php 7.3 

**Nextcloud version:** (see Nextcloud admin page) 18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**updated from NC 17 -> 18.0.1 -> 18.0.2

**Comment by BennyE** [comment]
I noticed the same and assume it has to do with the fact that 0-9 is missing.

**Comment by phonon112358** [comment]
I leave the password field empty because I want the new user to get force to set her/his own password ...

**Comment by orandev** [comment]
I also have the issue (sometimes), after an update from 18.0.1 to 18.0.3.

**Comment by szaimen** [comment]
Related: https://github.com/nextcloud/server/issues/16465

**Comment by szaimen** [comment]
cc @nextcloud/security do we want to allow empty passwords? If not, please close this issue. Thanks! :)

**Comment by LukasReschke** [comment]
I think we can close this.
