### ISSUE TITLE
New web ui does not allow make new shares to users/groups. 

### ISSUE THREAD

**Issue by burner-** [nextcloud/server#20080]
### Expected behaviour
When user open file share menu at web ui there sould be way to add new share

### Actual behaviour
Currently user can see shares but cannot share file to anyone. There is no link/button to add new share for another user. 

**Nextcloud version:** 18.0.2

**Comment by simonsan** [comment]
I don't even see the sharing tab, in the HTML it's everything greyed out, am I doing something wrong? 🤔 Sharing with a user from the Nextcloud client (on Windows) is working and afterwards the file also shows a "shared" symbol in the overview. Clicking on it then doesn't show the "Share" tab either.

**Comment by burner-** [comment]
with that sharing icon (points with links) but after that there is only "Share link" as active and another options are grey.

**Comment by simonsan** [comment]
I don't see it, it should be in the middle.

![2020-03-21 18_23_37-Window-Screenshot](https://user-images.githubusercontent.com/14062932/77232432-27ceea80-6ba1-11ea-93f2-fc726ba21a3f.png)

**Comment by burner-** [comment]
At least I have it :) 
But anyway that whole sharing system feels to be quite broken at many levels. It just feels that they did not do any tests to it before release. 
![image](https://user-images.githubusercontent.com/3836115/77235287-2ad7d400-6bbd-11ea-89ca-ff54b974bb26.png)

**Comment by simonsan** [comment]
Ref.: #17737

**Comment by Nils160988** [comment]
Did you try disabling addblocker for your domain?
#16337

**Comment by burner-** [comment]
Yes I did. And I also test with computer where is no addblock at all.

**Comment by burner-** [comment]
But hey. I just notice that search works now. So my problem went away.

**Comment by simonsan** [comment]
> Did you try disabling addblocker for your domain?
> #16337

That it was for me. Unfortunately `###sharing` is on these Filter lists:

``` 
Fanboy’s Social 
Fanboy’s Annoyance
```

**Comment by Nils160988** [comment]
> But hey. I just notice that search works now. So my problem went away.

So, can this issue be closed?

**Comment by burner-** [comment]
Yes. I am not totally sure why it started work but it works now and I cannot reprocude it any more so I will close this.
