### ISSUE TITLE
Possibility to sort the folders in the folder view

### ISSUE THREAD

**Issue by Boki4d** [nextcloud/server#20081]
**Is your feature request related to a problem? Please describe.**
It's not really a problem, but if you have several group folders from different groups and many folders in general, an option to sort the folders would by beneficial.

**Describe the solution you'd like**
I imagine something like the Windows 10 start menu, where you can create "Groups" for application-icons. 

**Describe alternatives you've considered**
Another possibility would be to sort the folders automatically by group. Maybe this would be easier to implement.

**Additional context**
![groupsorting](https://user-images.githubusercontent.com/62222212/77229302-6a86c780-6b8d-11ea-88dc-9964f7198010.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers is this feasible?
