### ISSUE TITLE
Better versioning control

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#2009]
As admin I want to be able to see this in the Activities menu to the right:

- [ ] When a user do an external upload to a public shared folder (and what file that was uploaded)

Emails:
- [ ] If a user has edited a file, I want to be able to get an email when that's happened and what changed.

Today I can only see when a foler is created or shared (please correct me if I'm wrong) and I don't get an email when a new file is uploaded or edited to/in a shared folder.

Makes sense?

**Comment by nickvergessen** [comment]
You can enable emails for that in the personal settings?

**Comment by enoch85** [comment]
@nickvergessen Sorry, what I mean to be precise is that it should be shown in the "Activites" for the specific folder in the right bar section as well as in the regular "Activites" (the app) , you know what I mean? Right now you can only see if the folder is shared.

Aslo regarding emails, would it be possible to get the diff of what's changed, I mean for example if you are working with a text document..?

**Comment by nickvergessen** [comment]
There is an issue about showing activities of sub folders/files. But currently this is technically not possible...

No, the activity app will certainly not get a diff engine...

**Comment by enoch85** [comment]
Ok, ok, letäs close this then. :)
