### ISSUE TITLE
Duplicate HTML encoding

### ISSUE THREAD

**Issue by smurfix** [nextcloud/server#20098]
### Steps to reproduce
1. set language to German
2. go to /settings/user/security
3. observe "\&amp;" in heading (top of last section)

### Expected behaviour
That should be a single ampersand obviously

### Actual behaviour
Something is doing HTML escaping on already-escaped text

### Server configuration

**Operating system:** Debian Buster

**Web server:** nginx

**Database:** mysql

**PHP version:** 7.3

**Nextcloud version:** v18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** git

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - lookup_server_connector: 1.6.0
  - oauth2: 1.6.0
  - provisioning_api: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - systemtags: 1.8.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - testing
  - user_ldap
```
</details>

**Comment by georgehrke** [comment]
Duplicate of https://github.com/nextcloud/server/issues/18662

**Comment by georgehrke** [comment]
Please search for existing issues before creating new ones. Thx
