### ISSUE TITLE
File / Folder Creation / Upload / Deletion not working - Error: Call to undefined method OCP\Files\Cache\CacheUpdateEvent::setPath()

### ISSUE THREAD

**Issue by idominiki** [nextcloud/server#20107]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Create / delete or upload any file or folder 
2. Error is shown
3.

### Expected behaviour
File should be created or so

### Actual behaviour
Error is shown and nothing happend

### Server configuration

**Operating system:**
UCS 4.4-3 errata499
**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
18.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 17 on UCS
**Where did you install Nextcloud from:**
UCS AppCenter
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
[remote] Error: Error: Call to undefined method OCP\Files\Cache\CacheUpdateEvent::setPath() at <<closure>>

 0. /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 247
    OCA\GroupFolders\CacheListener->onCacheEvent(OCP\Files\Cache\CacheUpdateEvent {}, "OCP\\Files\\Cache\\CacheUpdateEvent", Symfony\Componen ... {})
 1. /var/www/html/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners([Closure {}], "OCP\\Files\\Cache\\CacheUpdateEvent", OCP\Files\Cache\CacheUpdateEvent {})
 2. /var/www/html/lib/private/EventDispatcher/EventDispatcher.php line 80
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch(OCP\Files\Cache\CacheUpdateEvent {}, "OCP\\Files\\Cache\\CacheUpdateEvent")
 3. /var/www/html/lib/private/EventDispatcher/SymfonyAdapter.php line 63
    OC\EventDispatcher\EventDispatcher->dispatch("OCP\\Files\\Cache\\CacheUpdateEvent", OCP\Files\Cache\CacheUpdateEvent {})
 4. /var/www/html/lib/private/Files/Cache/Cache.php line 393
    OC\EventDispatcher\SymfonyAdapter->dispatch("OCP\\Files\\Cache\\CacheUpdateEvent", OCP\Files\Cache\CacheUpdateEvent {})
 5. /var/www/html/lib/private/Files/Cache/Wrapper/CacheJail.php line 133
    OC\Files\Cache\Cache->update("*** sensitive parameters replaced ***")
 6. /var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php line 140
    OC\Files\Cache\Wrapper\CacheJail->update("*** sensitive parameters replaced ***")
 7. /var/www/html/apps/groupfolders/lib/Mount/RootEntryCache.php line 52
    OC\Files\Cache\Wrapper\CacheWrapper->update("*** sensitive parameters replaced ***")
 8. /var/www/html/lib/private/Files/Cache/Wrapper/CacheWrapper.php line 140
    OCA\GroupFolders\Mount\RootEntryCache->update("*** sensitive parameters replaced ***")
 9. /var/www/html/lib/private/Files/Cache/Updater.php line 247
    OC\Files\Cache\Wrapper\CacheWrapper->update("*** sensitive parameters replaced ***")
10. /var/www/html/lib/private/Files/Cache/Updater.php line 160
    OC\Files\Cache\Updater->correctParentStorageMtime("9998_Apple/Scho ... s")
11. /var/www/html/lib/private/Files/View.php line 327
    OC\Files\Cache\Updater->remove("9998_Apple/Scho ... s")
12. /var/www/html/lib/private/Files/View.php line 1174
    OC\Files\View->removeUpdate(OCA\Files_Trashb ... }}, "9998_Apple/Scho ... s")
13. /var/www/html/lib/private/Files/View.php line 348
    OC\Files\View->basicOperation("rmdir", "/Schul-Netzwerk ... s", ["delete"])
14. /var/www/html/apps/dav/lib/Connector/Sabre/Directory.php line 312
    OC\Files\View->rmdir("/Schul-Netzwerk ... s")
15. /var/www/html/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\Directory->delete()
16. /var/www/html/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
    Sabre\DAV\Tree->delete("files/dfahrin/S ... s")
17. <<closure>>
    Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
18. /var/www/html/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
19. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
20. /var/www/html/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
21. /var/www/html/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
22. /var/www/html/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
23. /var/www/html/remote.php line 165
    require_once("/var/www/html/a ... p")

DELETE /nextcloud/remote.php/dav/files/dfahrin/Schul-Netzwerke/9998_Apple/School%20Manager/ASM_CSV_Templates
from 10.0.0.1 by dfahrin at 2020-03-23T12:45:51+00:00
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes UCS LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Safari 13
**Operating system:**
macOS 10.15
### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by svenbatistasteinbach** [comment]
I have the same problem..

**Comment by svenbatistasteinbach** [comment]
Same problem on dockerized Nextcloud:

```
[index] Error: Exception: Call to undefined method OCP\Files\Cache\CacheUpdateEvent::setPath() at <<closure>>

0. /var/www/html/lib/private/AppFramework/App.php line 125
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Text\Controller\SessionController {}, "sync")
1. /var/www/html/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Text\\Cont ... r", "sync", OC\AppFramework\ ... {}, {_route: "text.Session.sync"})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "text.Session.sync"})
3. /var/www/html/lib/private/Route/Router.php line 299
   call_user_func(OC\AppFramework\ ... {}, {_route: "text.Session.sync"})
4. /var/www/html/lib/base.php line 1008
   OC\Route\Router->match("/apps/text/session/sync")
5. /var/www/html/index.php line 38
   OC::handleRequest()

POST /index.php/apps/text/session/sync
```

**Comment by bellwood** [comment]
I will add we are seeing this when using remote clients. 

In-browser usage doesn't seem to exhibit the same issues.

**Comment by idominiki** [comment]
First I seen this bug when using macOS Nextcloud Client. Now I got the same error over the browser guy

**Comment by svenbatistasteinbach** [comment]
We first had this problem in the browser when we wrote in the app "text". Now it is no longer possible to create a new folder/file or change .md files with text within a group folder. The problem does not occur in own folders at least we could not observe it there yet. The problems occured after updating several apps under other group folders

**Comment by pmalsenz** [comment]
We're having issues with the groupfolders app in our cloud too, but it looks like only groupfolders created before upgrading from Nextcloud 17 (latest release) to 18.0.0.

If I run `occ groupfolders:scan` with a folder_id from Nextcloud 17, we get `Error: Call to undefined method OCP\Files\Cache\CacheUpdateEvent::setPath() in /var/www/nextcloud/apps/groupfolders/lib/CacheListener.php:49`

Running `occ groupfolders:expire`, we get this message `In File.php line 137:                                     
  [OCP\Files\NotPermittedException]`

To me it looks like a problem with file versioning.

**Comment by kesselb** [comment]
Oh. For `setPath` you need at least 18.0.2.

**Comment by kesselb** [comment]
cc @nextcloud/server-triage @juliushaertl @icewind1991

**Comment by idominiki** [comment]
18.0.2 isn‘t available in UCS AppCenter right?

**Comment by kesselb** [comment]
Don't know much about UCS AppCenter but for the time beeing I would replace the groupfolders app 6.0.2 / 6.0.3 with 6.0.1: https://github.com/nextcloud/groupfolders/releases/tag/v6.0.1.

**Comment by idominiki** [comment]
Can you help? How can I do that 😬

**Comment by pmalsenz** [comment]
Thanks, will try ASAP :-)

**Comment by bellwood** [comment]
> Oh. For `setPath` you need at least 18.0.2.

Shouldn't there a blocker for this such that those not on 18.0.2 can't install SharedFolders > 6.0.1?

**Comment by pmalsenz** [comment]
So, all Updates went well and NC is running in version 18.0.3 with Groupfolders app version 6.0.3.

But the `groupfolders:expire` command still throws errors as written before (`In File.php line 137: [OCP\Files\NotPermittedException]`)

I need to clean up the files versioning as it actually has 21 GB (!) for one group folder and we're running low on disk space.

**Comment by nickvergessen** [comment]
Please open a new issue in the groupfolders app for that

**Comment by nickvergessen** [comment]
(the expire i mean)

**Comment by nickvergessen** [comment]
We don't have an option to require minor patch versions i think, or can someone test that it works. In case it does work it should be fixed in the groupfolders app
