### ISSUE TITLE
Files sidebar: Activity tab not updating on file switch

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#20106]
![Peek 2020-03-23 13-33](https://user-images.githubusercontent.com/1804221/77317147-f2461080-6d0a-11ea-9024-eb976fea11b4.gif)

### Steps to reproduce
1. Click on ... > Details at File A => sidebar opens, focusing activity tab in sidebar
2. See activities for File A
3. Click on ... > Details at File B

### Expected behaviour
Activities for File B are shown

### Actual behaviour
Activities for File A are shown

### Server configuration

NC 18.0.2 + 18.0.3

**Comment by q-wertz** [comment]
Same here. 
The activities are refreshed when clicking on on of the other tabs (e.g. Comments or Sharing) and then back to the Activities tab.
