### ISSUE TITLE
Can't edit Users: Cannot read property 'beforeRouteEnter' of undefined

### ISSUE THREAD

**Issue by mariusbolik** [nextcloud/server#20103]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.

### Steps to reproduce
1. Install NC 18.0.2
2. Press on your Profile Avatar
3. Click on "Users"

### Expected behaviour
List of existing Users should show up.

### Actual behaviour
A blank Page appears:

<img src="https://i.imgur.com/7Zfwsux.png">

### Server configuration

**Operating system:** Debian

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 18.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 18.0.1

**Where did you install Nextcloud from:** Downloaded it from official Nextcloud website

**Comment by mariusbolik** [comment]
Deleted Browser Cache. Now it's working. Nevertheless it's a strange behavior 🤔

**Comment by szaimen** [comment]
Closing as it was resolved.
