### ISSUE TITLE
Add options to define path to workflow log and to disable logging (flow.log)

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#20100]
### Expected behavior
I would expect that an app doesn't create a separate log file without being told to do so. It should be possible to 
a) define a custom path where the workflow log should be stored.
b) disable the creation of the workflow log file at all. Here is a short excerpt of the log file:
```
...
... ,"time":"2020-02-13 11:59:13+01:00","remoteAddr":"<ip-addr>","user":"<user>","app":"workflowengine","method":"PROPFIND","url":"/remote.php/webdav/<directory-path>/","message":"Flow activation: rules were requested","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.10.1","version":"18.0.1.3","data":{"scopes":[{"scope":"admin"},{"scope":"user","uid":"<user>"}],"operation":{"class":"OCA\\FilesAutomatedTagging\\Operation","name":"Tags automatisch zuweisen"},"message":"Flow activation: rules were requested"}}
... ,"time":"2020-02-13 11:59:13+01:00","remoteAddr":"<ip-addr>","user":"<user>","app":"workflowengine","method":"PROPFIND","url":"/remote.php/webdav/<directory-path>/","message":"No flow configurations is going to run","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.10.1","version":"18.0.1.3","data":{"operation":{"class":"OCA\\FilesAutomatedTagging\\Operation","name":"Tags automatisch zuweisen"},"message":"No flow configurations is going to run"}}
...
```
### Actual behavior
The app automatically creates a flow.log file in the data directory. I was really surprised to find a **15 GB log file** in that directory, covering a period of 8 days, although I haven't really used that function. 

#### Server Configuration
OS: Linux 4.9.210
Web server: Apache2 2.4.41
Database: MariaDB 10.2.24
PHP version: 7.3.13
Nextcloud version: 18.0.2
**Workflow engine: 2.0.0**

#### Client Configuration
Browser: Mozilla Firefox 74.0
Operating system: Windows 10

**Comment by kesselb** [comment]
cc @blizzz @juliushaertl

**Comment by kesselb** [comment]
> a) define a custom path where the workflow log should be stored.

`php occ config:app:set workflowengine logfile --value=/path/to/your/flow.log`

**Comment by blizzz** [comment]
> > a) define a custom path where the workflow log should be stored.
> 
> `occ config:app:set workflowengine logfile --value=/path/to/your/flow.log`

Aye. Use /dev/null and you're good.
