### ISSUE TITLE
Possible bug in sharing (file/folder) to an LDAP group

### ISSUE THREAD

**Issue by dea-75** [nextcloud/server#20110]
Hi all !

This is my structure:
N.2 servers Nextcloud, Debian 10 based, PHP 7.3 (Debian 10), Apache 2.4 (Debian 10) and PostgreSQL as db.
The servers was installed (nativaly) on 17.0.0 and successfuly upgraded to 18.0.2 (17.0.3->18.0.2).

I use *only* LDAP users and groups.

All app are upgraded to the last version.

I think there is a problem, not only in Nextcloud 18.0.2, but I think it present in 17.0.2 then updated, initially I had not given weight to the problem.

The problem:

-) When I share a folder to any single users, all ok
-) When I share a folder from LDAP users on group A to all group A, all ok
-) When I share a folder from LDAP users in group A to group B, the directory is marked as shared, BUT, the users on group B doesn't see the shared folder.

The behavior is identical on two servers

Note: I don't use "Group folders" app

**A practical example:**
I am "admin", create a new folder, share it with LDAP group "A", any users on the group "A" does'nt see the folder.
If I share it directly to single user (or more single users) on group "A", Thom, Robert, etc. works correctly.

Very thanks for support !!!

Luca

**Comment by remogatto** [comment]
It seems I ran into the same issue. I'm using the 18.0.2 version. I'm available to give any information about my installation. Thank you.

**Comment by dea-75** [comment]
I've upgraded on 18.0.3.. seems persist...

**Comment by addy90** [comment]
Can confirm this: #19988

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
