### ISSUE TITLE
Nextcloud notification count in browser title bar / tab title

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#20111]
I just want to drop an interesting feedback/idea I got from a Nextcloud users.

It could be nice to have a "new notification"-counter in the Browser title bar and the Browser's tab title. Many other sites (twitter, etc) do it, this way you can easily spot that a new notification is available.

**Comment by georgehrke** [comment]
It would be nice if there was one standard API for modifying the title.
The calendar app is also changing the title to reflect the current view (like June 2019) and this would conflict.

**Comment by schiessle** [comment]
Good point, we would probably need a API which allows you to append stuff to the title so that one app can't overwrite the title of the other one.

Or, even that technically notifications are also just a app, we could treat this as a core functionality. Apps could add stuff to the left side, e.g. "Files - Nextcloud", "March 2020 - Calendar - Nextcloud" and the notification would be always added to the right side like "March 2020 - Calendar - Nextcloud (🔔2)"

**Comment by nickvergessen** [comment]
Implemented with `*` now similar to talk: https://github.com/nextcloud/notifications/pull/908
