### ISSUE TITLE
No entry in changelog for 18.03 (17.05 etc.)

### ISSUE THREAD

**Issue by putt1ck** [nextcloud/server#20119]
Issue: servers show update available to 18.03, but link to changelog for the update shows no such update. Looks like a similar issue exists for 17.05. This makes nervous sys admins even more nervous.

Expected outcome: changelog lists changes in new release before update is released as upgrade to channel.

**Comment by kesselb** [comment]
Please use the search the next time: https://github.com/nextcloud/server/issues/20113. Also GitHub is not a support channel: https://help.nextcloud.com/t/is-update-to-18-03-real/74909.

**Comment by kesselb** [comment]
cc @rullzer please consider another process for such security releases. I know you updated the wiki accordingly and also pushed the release to the updater_server but a release without a announcement at nextcloud.com leads always to new issues on GitHub.

**Comment by putt1ck** [comment]
The link to the change log is a secondary security layer from my perspective, so yes a bug not a support issue. Bugs are not always in code.

**Comment by kesselb** [comment]
Anyway use the search next time.

**Comment by putt1ck** [comment]
I did. Neither a search for "18.03" nor "changelog" returned any results, searching in all issues.

**Comment by kesselb** [comment]
I would try 18.0.3 the next time.

**Comment by jorsn** [comment]
> Anyway use the search next time.

@kesselb Please don't blame admins who do not blindly trust an update server pushing an update with dubious validity.

When I searched, there was no official documentation about the release apart from the release schedule. Still, you can't see from the usual channels what is contained in the release: No git tag, no Github release, an empty milestone and no official change log despite all these things existing normally, this seems super fishy. As if someone accidentally or intentionally pushed the update before it was ready.

This *is* is an important issue, which needed to be created and shall be open until fixed. To me, a release without a change log is no complete release.

So, please limit yourself to the constructive comments like your [above post](https://github.com/nextcloud/server/issues/20119#issuecomment-602717758).

**Comment by kesselb** [comment]
Please make sure to update your instance soon :rocket:  It's better to have that fix :lock:

**Comment by gary-kim** [comment]
Also, just to ask, how much time until the fix gets applied in the repo? It's an interesting bug.

**Comment by SimJoSt** [comment]
I was also confused by the missing references to that version. No Docker tag, no Github tag/release, no changelog and no blog post. The download link on the official website also points to 18.0.2  
Because of the first, I am not able to update my instance.

**Comment by Kieltux** [comment]
Ok, I hope I used the right support channel :-)
https://nextcloud.com/changelog/#latest18
Really? 18.0.03 is from 13.03.2020? I am confused.

Version 18.0.3 March 13 2020

Download: nextcloud-18.0.3.tar.bz2 or nextcloud-18.0.3.zip
Check the file integrity with:
MD5: nextcloud-18.0.3.tar.bz2.md5 or nextcloud-18.0.3.zip.md5
SHA256: nextcloud-18.0.3.tar.bz2.sha256 or nextcloud-18.0.3.zip.sha256
SHA512: nextcloud-18.0.3.tar.bz2.sha512 or nextcloud-18.0.3.zip.sha512
PGP (Key): nextcloud-18.0.3.tar.bz2.asc or nextcloud-18.0.3.zip.asc
Changes

Security update

Keep safe & healthy.

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/nextcloud.com/commit/2a214fb136e4394918c9da0259626ec9bad13d74

**Comment by stweil** [comment]
The tag is still missing. This is confusing.
