### ISSUE TITLE
[18.0.3] Can't delete files/folders

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#20115]
I did a quick search and can't find this bug.

This has existed since at least 18.0.2.

I cannot delete files or folders because it cuts off the menu before the delete option appears. I am using firefox and 18.0.3

Here is a GIF of the issue (scroll down)

![1umPh7iWos](https://user-images.githubusercontent.com/3902676/77338848-377a3a80-6d2b-11ea-8cc8-9afc1766282f.gif)

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
We need to add more padding on the bottom :)

**Comment by rmanibus** [comment]
Also when moving a file and the target folder has only five element, something goes wrong:

![nextcloud](https://user-images.githubusercontent.com/10419172/77404011-5de2b900-6db1-11ea-9914-370ace6ed8bf.PNG)

![nextcloud2](https://user-images.githubusercontent.com/10419172/77404047-676c2100-6db1-11ea-9d80-6c0f61735741.PNG)

**Comment by sarkisben** [comment]
Can I take this issue?

**Comment by juliushaertl** [comment]
Yes, of course, contributions are very welcome. Let us know if you have any questions. Otherwise feel free to just open a pull request where we can discuss the changes then.

**Comment by Zen-glen** [comment]
Was this issue resolved @sarkisben , otherwise I can try for my first issue.

**Comment by Zen-glen** [comment]
Hello,

I will have a go at trying to resolve this. I am new so let me say my understanding of the issue:

The popup menu on the files app does not take into account the bottom of the view port, such as in this image:

![image](https://user-images.githubusercontent.com/34506780/90488683-2bf13b00-e134-11ea-88f0-e30ead1aa5b1.png)

To fix this would be along the lines of pushing the popup higher or adding a scroll etc.

**Comment by Zen-glen** [comment]
I had a look at this issue. When in apps/files, the screen should contain enough height to always show the pop up - although the user may need to scroll down.

![image](https://user-images.githubusercontent.com/34506780/90489227-e84b0100-e134-11ea-9fdd-1345cb7c7d5e.png)

As you can see in the above image, the pop up is cut off, however, the user can simply scroll further down.  

I therefore believe this issue my have been user error. 

Unless, you would rather have the popup factor in the bottom of the view port and never go below that?

**Comment by jancborchardt** [comment]
@Zen-glen thanks for the update – it seems it was fixed meanwhile and we can close the issue.
Please feel free to look at other design issues, looking forward to any contributions :)

**Comment by szaimen** [comment]
Actually this isn't fixed at least on Nextcloud 19.0.1
Or is it fixed on Master?
![20200818_105602](https://user-images.githubusercontent.com/42591237/90492509-8e046d00-e141-11ea-8777-5fa11298617d.png)

**Comment by jancborchardt** [comment]
Can’t reproduce it on master, neither on desktop nor mobile. That is, you _do_ need to scroll after opening the menu, but that’s ok as we don’t want to forcefully scroll the view. You can reach the "Delete" action just fine:
![image](https://user-images.githubusercontent.com/925062/90493654-e9832a80-e142-11ea-8703-6ca34943c60e.png)
![image](https://user-images.githubusercontent.com/925062/90493770-0ddf0700-e143-11ea-851e-1cb4bbd3a38e.png)

**Comment by szaimen** [comment]
You cannot scroll further down also after opening the context menu on NC 19.0.1. But great if it is fixed on master 👍 
Closing!

**Comment by Dragon988** [comment]
This issue is fixed on 19.0.1 with the latest firefox.
