### ISSUE TITLE
Video Thumbnails in web interface and in android client 

### ISSUE THREAD

**Issue by orsotron** [nextcloud/server#2011]
### Actually
this is a nice to have feature request
It would be very useful to have a thumbnail for videos in web  UI  and in android client. Since in some browser video preview is not supported for a consistent number of video formats, it woul be great to have something that  at least lets user identify which video file is about to download. I'm not sure if this is a common need, but I believe it could be very useful, to me for sure, and actually it's something provided by google drive web UI and android client. I know an open source project as Nextcloud could not  ever be compared to the product of a trilion dollar firm like Google, but, considering I'm a basic user for both, I have to tell I was surprised by the high quality and richness of features offered by Nextcloud and the comparison is head to head. Apart of course this single missing feature. Anyway the whole application is wonderful, thanks for making it!
### Actual behaviour
A "play" Icon is shown

### Server configuration
**OS Version:** Raspbian wheezy on Raspberry Pi

**Web Server:** Apache2

**DB Server:** mysql, converted from sqlLite

**php Version:** php5

**NextCloud Version:** 10.01, Fresh Install

**Comment by nickvergessen** [comment]
See https://docs.nextcloud.com/server/9/admin_manual/configuration_server/config_sample_php_parameters.html#previews

**Comment by orsotron** [comment]
Sorry but actually I don't see any reference to video preview providers.

**Comment by orsotron** [comment]
Even enabling the OC\Preview\Movie parameter there is no thumbnail. Neither for mp4, MTS or mov files.

**Comment by nickvergessen** [comment]
Two possible reasons:
1. #1475 
2. You didn't install ffmpeg/avconf

I just saw that the docs don't mention this, so I open an issue in the docs repo

**Comment by orsotron** [comment]
do I have to rescan files also?

**Comment by nickvergessen** [comment]
I don't think so, but local caching could be a thing, but that should expire within 24 hours latest
