### ISSUE TITLE
What is Nextcloud 18.0.3 ?? Why is it offered?

### ISSUE THREAD

**Issue by pm-pm** [nextcloud/server#20113]
My Server offers me Nextcloud 18.0.**3** (stable) for update. - WHY?

No Code on Github. (No beta, no release)
No Download on nextcloud.com

What is 18.0.**3**? - Why is it offered to me??

Fake? Bug? Hack? Feature?

Thanks

pm-pm

**Comment by kesselb** [comment]
GitHub is not a support channel: https://help.nextcloud.com/t/is-update-to-18-03-real/74909

**Comment by kesselb** [comment]
The last time [you asked](https://github.com/nextcloud/server/issues/18725) to update https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule accordingly. This has been done.

**Comment by kesselb** [comment]
Please make sure to update your instance soon :rocket:  It's better to have that fix :lock:

**Comment by pc-robelbois** [comment]
The OP question is legit. I saw the upgrade option to .3 -> went to github to check what's inside -> the release is not listed in the release page -> this does not seems normal -> panic mode enabled.
