### ISSUE TITLE
Corrupt vcf file by export

### ISSUE THREAD

**Issue by MiMoHo** [nextcloud/server#20112]
Exporting contacts on my Nextcloud server produces a corrupt vcf file for some of my contacts. When I export the entire address book, it is affected as well. I attached a vcf file that was exported with Nextcloud and cannot be reimported. Nextcloud version says "latest".
[F31BFC51-7C45-4281-8E45-28CACDF3E1A1.zip](https://github.com/nextcloud/server/files/4370229/F31BFC51-7C45-4281-8E45-28CACDF3E1A1.zip)

**Comment by kesselb** [comment]
I had no issues importing your vcf file locally. Also works with a demo account at https://try.nextcloud.com/.
