### ISSUE TITLE
[solution found] Missing AppStore update 16.0.9 to 17.05

### ISSUE THREAD

**Issue by dirigit** [nextcloud/server#20126]
Updated 16.0.9 to 17.0.5 while using a new directory for 17.0.5 with config.php from 16.0.9.

No AppStore visible, no chance to install missing apps.

Found something related in forums but, solutions mentioned there (eg. related to 17.0.3, 18.0.x) didn't work.

**Comment by kesselb** [comment]
This one perhaps? https://github.com/nextcloud/server/issues/19783

**Comment by kesselb** [comment]
I added the "needs info" label because the issue template is missing.

**Comment by dirigit** [comment]
hm.
`{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"accessibility\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"appstoreFetcher","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":{"Exception":"GuzzleHttp\\Exception\\ClientException","Message":"Client error: `GET https:\/\/apps.nextcloud.com\/api\/v0\/apps.json` resulted in a `404 Not Found` response:\n\n\n<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n    <meta charset=\"utf-8\">\n    <meta name=\"viewport\" content=\"width=device-wid (truncated...)\n","Code":404,"Trace":[{"file":"\/htdocs\/cl\/3rdparty\/guzzlehttp\/guzzle\/src\/Middleware.php","line":66,"function":"create","class":"GuzzleHttp\\Exception\\RequestException","type":"::","args":[{"__class__":"GuzzleHttp\\Psr7\\Request"},"*** sensitive parameter replaced ***"]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":203,"function":"GuzzleHttp\\{closure}","class":"GuzzleHttp\\Middleware","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":156,"function":"callHandler","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":[1,"*** sensitive parameter replaced ***",[{"__class__":"GuzzleHttp\\Promise\\Promise"},{"__class__":"Closure"},null]]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/TaskQueue.php","line":47,"function":"GuzzleHttp\\Promise\\{closure}","class":"GuzzleHttp\\Promise\\Promise","type":"::","args":["*** sensitive parameters replaced ***"]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":246,"function":"run","class":"GuzzleHttp\\Promise\\TaskQueue","type":"->","args":[true]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":223,"function":"invokeWaitFn","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":267,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":225,"function":"invokeWaitList","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/promises\/src\/Promise.php","line":62,"function":"waitIfPending","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/guzzle\/src\/Client.php","line":131,"function":"wait","class":"GuzzleHttp\\Promise\\Promise","type":"->","args":[]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/Http\/Client\/Client.php","line":144,"function":"request","class":"GuzzleHttp\\Client","type":"->","args":["get","https:\/\/apps.nextcloud.com\/api\/v0\/apps.json",{"proxy":null,"verify":"\/homepages\/22\/d30829954\/htdocs\/data\/files_external\/rootcerts.crt","timeout":10,"headers":{"User-Agent":"Nextcloud Server Crawler"},"synchronous":true}]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/App\/AppStore\/Fetcher\/Fetcher.php","line":108,"function":"get","class":"OC\\Http\\Client\\Client","type":"->","args":["https:\/\/apps.nextcloud.com\/api\/v0\/apps.json",{"timeout":10}]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/App\/AppStore\/Fetcher\/AppFetcher.php","line":84,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->","args":["",""]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/App\/AppStore\/Fetcher\/Fetcher.php","line":172,"function":"fetch","class":"OC\\App\\AppStore\\Fetcher\\AppFetcher","type":"->","args":["",""]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/Installer.php","line":396,"function":"get","class":"OC\\App\\AppStore\\Fetcher\\Fetcher","type":"->","args":[]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/Updater.php","line":448,"function":"isUpdateAvailable","class":"OC\\Installer","type":"->","args":["accessibility"]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/Updater.php","line":258,"function":"upgradeAppStoreApps","class":"OC\\Updater","type":"->","args":[["accessibility","activity","admin_audit","cloud_federation_api","comments","dav","federatedfilesharing","federation","files","files_pdfviewer","files_rightclick","files_sharing","files_trashbin","files_versions","files_videoplayer","firstrunwizard","gallery","logreader","lookup_server_connector","nextcloud_announcements","notifications","oauth2","password_policy","privacy","provisioning_api","recommendations","serverinfo","sharebymail","support","systemtags","theming","twofactor_backupcodes","updatenotification","viewer","workflowengine"]]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/lib\/private\/Updater.php","line":128,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["17.0.5.0","16.0.9.2"]},{"file":"\/homepages\/22\/d30829954\/htdocs\/cl\/core\/ajax\/update.php","line":212,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]}],"File":"\/homepages\/22\/d30829954\/htdocs\/cl\/3rdparty\/guzzlehttp\/guzzle\/src\/Exception\/RequestException.php","Line":113,"CustomMessage":"--"},"userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"accessibility\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"activity\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"activity\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"admin_audit\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"admin_audit\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreAppBefore: Checking for update of app \"cloud_federation_api\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}
{"reqId":"XnmwzFKlVlIAARuO59MAAAAW","level":1,"time":"2020-03-24T08:04:15+01:00","remoteAddr":"a.b.c.d","user":"--","app":"updater","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=o32yBDzM%2ByX4Q9NyZprDRCYSqMgMtOXPJc5aTYuwgb4%3D%3AxA%2FqNgi8yXLXCJ0nTcLxEWN%2F3bF%2B%2F4%2BaXKIiPL7j284%3D","message":"\\OC\\Updater::checkAppStoreApp: Checked for update of app \"cloud_federation_api\" in appstore","userAgent":"Mozilla\/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko\/20100101 Firefox\/74.0","version":"16.0.9.2"}`

**Comment by dirigit** [comment]
Found reason:
If you have
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',
in config.php you'll see no apps to install. Removing this option solves problem.

**Comment by Nils160988** [comment]
If you found the solution, can you also close the issue?
