### ISSUE TITLE
OC\Preview\Movie does not create any thumbnail for video files

### ISSUE THREAD

**Issue by orsotron** [nextcloud/server#2013]
### Steps to reproduce
1. Enabled OC\Preview\Movie in [nextcloud]/config/config.php
2. restarted apache2
3. even restarted the whole server (sudo reboot)

### Expected behaviour
I should see preview icons in WebUI or android client for .mp4, .mts or .mov video files
### Actual behaviour
 but nothing changes, still the same "play" Icon.

### Server configuration
**Operating system**: Raspbian wheezy

**Web server:** apache 2

**Database:** mysql, converted from sqllite

**PHP version:** php5

**Nextcloud version:** 10.01

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh Install

**Comment by nickvergessen** [comment]
Let's continue this in your other issue: #2011
