### ISSUE TITLE
Cannot move or copy file when the target path take more than one line

### ISSUE THREAD

**Issue by rmanibus** [nextcloud/server#20130]
### Steps to reproduce

When moving a file and the target folder has only five element and the path take more than one line, the buttons move along with the scrollbar and the fifth item does not appears:

![nextcloud](https://user-images.githubusercontent.com/10419172/77405326-4c021580-6db3-11ea-9d51-702c90a9e399.PNG)

![nextcloud2](https://user-images.githubusercontent.com/10419172/77405330-4e646f80-6db3-11ea-88d6-a54a64e39227.PNG)

**Comment by rmanibus** [comment]
I think we need
```
.oc-dialog { overflow-x: hidden}
```
to prevent the dialog to be scrollable 
and add some padding-bottom to 
```
picker-filestable
```

**Comment by kesselb** [comment]
cc @skjnldsv @GretaD

**Comment by GretaD** [comment]
Hey @rmanibus what version of NC are you using?

**Comment by rmanibus** [comment]
hi, 18.02

**Comment by GretaD** [comment]
> I think we need
> 
> ```
> .oc-dialog { overflow-x: hidden}
> ```
> 
> to prevent the dialog to be scrollable
> and add some padding-bottom to
> 
> ```
> picker-filestable
> ```

Hello again, 
you're right, I can also reproduce it in different versions. Do you want to work on it? Since you already have a solution on mind :)

**Comment by rmanibus** [comment]
Of course,

How do you rebuild the scss content ?

**Comment by skjnldsv** [comment]
> How do you rebuild the scss content ?

scss is automatically recompiled :)
You can force a clear by doing an occ maintenance:repair

**Comment by rmanibus** [comment]
thanks, I think this does the trick !
