### ISSUE TITLE
"Download picture" downloaded file has a wrong .vcf extension (Firefox only)

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#20143]
**To Reproduce**
1. Go to any contact
2. Click on the avatar
3. Open the 3-dot menu in the top right and click "Download picture"
4. Open the downloaded file

**Expected behavior**
The picture is opened.

**Actual behavior**
Because the file is called `Some ID.vcf`, it is opened with the text editor and just shows jumbled characters.
Changing the extension to `.jpg` fixes the issue.

Happens with latest master and happened some weeks before too.

**Comment by jancborchardt** [comment]
@skjnldsv how should we move forward then – transfer the issue to server, loop someone else it, or anything else?

**Comment by skjnldsv** [comment]
I guess adding the filename in the `Content-Disposition` header should work

**Comment by deepank120896** [comment]
@skjnldsv Hi , anyone working on this?

**Comment by skjnldsv** [comment]
Nope, go for it @deepank120896  :)
Welcome!

**Comment by sarkisben** [comment]
Is this resolved?

**Comment by j-ed** [comment]
> Is this resolved?

If it would have been solved the issue ticket status would be "**closed**" 😉

**Comment by sarkisben** [comment]
Alrighty, I would like to take a stab at it then.

**Comment by skjnldsv** [comment]
@sarkisben sure! :)
Feel free to dive into it!
We're available in the contacts public channel if you have questions https://cloud.nextcloud.com/call/wx2oqhpy

**Comment by jneplokh** [comment]
Is it preferred we save the photo as `Some ID.png` or can it just be `ContactPhoto.png`?

**Comment by skjnldsv** [comment]
> Is it preferred we save the photo as `Some ID.png` or can it just be `ContactPhoto.png`?

I would use the contact filename and use the correct extension (can be png, svg, jpeg... etc)
