### ISSUE TITLE
Height of user rows in user management

### ISSUE THREAD

**Issue by acs-ferreira** [nextcloud/server#20174]
@juliushaertl after installing 18.0.3 i can confirm this still happens with a few users.
(about my comments at https://github.com/nextcloud/server/pull/19882)

See the difference here on ALL USERS screen and a GROUP screen with a few users:

### ALL USERS, row heights is good.
![image](https://user-images.githubusercontent.com/12234510/77636048-cb2e4f80-6f53-11ea-919d-69a937e1c40d.png)

### 2 USERS, row heights is big.
![image](https://user-images.githubusercontent.com/12234510/77636077-d71a1180-6f53-11ea-8ce1-c1d63d24d528.png)

**Comment by donvipre** [comment]
I can confirm that on Nextcloud 18.0.3 from the release page that this also happens on all my nextcloud instances.

**Comment by acs-ferreira** [comment]
Fixed on 18.0.4 https://github.com/nextcloud/server/milestone/115?closed=1
