### ISSUE TITLE
Update error

### ISSUE THREAD

**Issue by r100gs** [nextcloud/server#20187]
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'ALTER TABLE oc_gpxpod_pictures RENAME COLUMN datetaken TO date_taken': SQLSTATE[42703]: Undefined column: 7 FEHLER: Spalte »datetaken« existiert nicht

Detaillierte Protokollmeldungen 
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: Not a mysql database -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'ALTER TABLE oc_gpxpod_pictures RENAME COLUMN datetaken TO date_taken': SQLSTATE[42703]: Undefined column: 7 FEHLER: Spalte »datetaken« existiert nicht
<

**Comment by kesselb** [comment]
https://gitlab.com/eneiluj/gpxpod-oc/-/issues/186
