### ISSUE TITLE
[Transfer ownership] username instead of displayname shown

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#20182]
While for incoming shares, the share owner's displayname is showed to the sharee, for ownership transfers the internal username is shown in the notification as well as in the folder name "Transferred from...".

Since especially in SAML and LDAP back ends the usernames are usually some unfriendly UUIDs, the recipient has no idea who's transferring something with them.

**Comment by nickvergessen** [comment]
But the Display name could contain characters which are not allowed on the filesystem: `/\\:?"'` and more

**Comment by wiswedel** [comment]
> But the Display name could contain characters which are not allowed on the filesystem: `/\\:?"'` and more

Can't that be sanitized by PHP before creating the folder?

**Comment by nickvergessen** [comment]
Sure, just wanted to mention it, especially with long display names and empty ones after removing all invalid characters its dangerous.
