### ISSUE TITLE
OC dialog confirm improvements

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#20192]
The current "Leaving call" modal could be better:
![Leave call modal needs better title and buttons](https://user-images.githubusercontent.com/925062/77435007-fe50d180-6de1-11ea-8b03-8bcf00e0b32f.png)

Ref https://github.com/nextcloud/spreed/issues/3144 by @jancborchardt 

- [ ] The icon is not needed, it just makes the text strangely aligned.
- [ ] Allow custom Yes/No button texts and "alert" instead of primary color, e.g. in Talk:
  -  "No" button should be "Stay in call".
  -  "Yes" button should be "Leave call" and not primary colored but red, as it is destructive.

**Comment by gary-kim** [comment]
I added `OC.dialogs.confirmDestructive` in #17785 and it sounds like that's pretty much what you're looking for.

It looks like this:
![Screenshot from 2019-11-05 14-48-41](https://user-images.githubusercontent.com/47195730/68184976-6772ac80-ffdb-11e9-8770-c4bcf6042f69.png)
![Screenshot from 2019-11-05 14-48-30](https://user-images.githubusercontent.com/47195730/68184974-6772ac80-ffdb-11e9-8174-4b3b3ff738f5.png)
You can also configure what the cancel button says.

**Comment by Dennis1993** [comment]
We should switch position of the buttons. Cancel to the right and the leave button to the left. That’s the default position and here is it wrong 🙂

**Comment by jancborchardt** [comment]
@gary-kim aaaawesome, as usual! :) 

------------

> We should switch position of the buttons. Cancel to the right and the leave button to the left. That’s the default position and here is it wrong slightly_smiling_face

@Dennis1993 the primary action is always on the right, as in the majority of systems. (Given it’s a Left-to-Right language.)

**Comment by gary-kim** [comment]
Closing as the requested enhancements were already implemented.

**Comment by nickvergessen** [comment]
Yeah, thanks a lot fo rthe pointer @gary-kim
