### ISSUE TITLE
imagick not recognized

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/server#20211]
### Steps to reproduce
1. Install the latest Raspbian light on a Raspi B+
2. Download the nextcloud files and install nextcloud manually
3. Install imagick together with php

### Expected behaviour
Nextcloud should recognize the enabled and installed module imagick

### Actual behaviour
Nextcloud says imagick is missing

### Server configuration

**Operating system:**
Raspian

**Web server:**
Apache

**Database:**
Maria db

**PHP version:**
7.*

**Nextcloud version:** (see Nextcloud admin page)
18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 
fresh

**Where did you install Nextcloud from:**
nextcloud.com

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>All the default apps plus contacts, calendar and tasks</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** Win10

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
