### ISSUE TITLE
Implement occ system:cron like in owncloud

### ISSUE THREAD

**Issue by ggeorgg** [nextcloud/server#20213]
I was just making some tests with the previewgenerator app and I wanted to understand better how the whole system works. I was stumbling over the table oc_jobs and I wanted to start/debug the cron job that will (as far as I know) execute exactly these jobs in this table. 
In the end I found an occ command to execute the cron jobs with an option "-p" to get a progress information. But this command is not implemented in nextcloud so I had a look into the code of owncloud et voila: 
[https://github.com/owncloud/core/blob/master/core/Command/System/Cron.php](https://github.com/owncloud/core/blob/master/core/Command/System/Cron.php)

Does it make sense to also implement this in nextcloud? I have seen, that this file is quite new in owncloud as well (implemented on Jul 4, 2019).

Best regards
Georg

**Comment by szaimen** [comment]
I think this will be implemented with https://github.com/nextcloud/server/pull/27217
