### ISSUE TITLE
Notification of adding event more complete

### ISSUE THREAD

**Issue by FredMa01** [nextcloud/server#20229]
Would it be possible for the activity notification to be more complete when adding events to the calendar?
Example:
There has been activity on Nextcloud
Today 18:59
Jules created the Guitar exam event in the Jules calendar

I am missing the date, time and description of the event

All thanks

**Comment by kesselb** [comment]
cc @nextcloud/calendar I think there is already another enhancement ticket for this but could not find it anymore.

**Comment by FredMa01** [comment]
I find this one : https://github.com/nextcloud/server/issues/18508

**Comment by tcitworld** [comment]
Indeed, thanks for finding it. Closing as duplicate. Feel free to subscribe to the other one.
