### ISSUE TITLE
Extend always enabled apps list

### ISSUE THREAD

**Issue by matchish** [nextcloud/server#20226]
I have a container with some preinstalled apps. One of them must be always enabled. If the application will be disabled I can lose important events. So I prefer down a server than the disabled app.

As a solution, I see a property in `appinfo.xml`.  So we can read it from appinfo and extend `$alwaysEnabled` list https://github.com/nextcloud/server/blob/0c3e2fac54602926cfa1a0965650481dcaf86743/lib/private/App/AppManager.php#L95

I tried to implement `uninstall` repair step and throw exception there. But an app already disabled when `unistall` repair step is run.  So this approach is not reliable for my opinion

**Comment by gary-kim** [comment]
The list of always enabled apps are here: https://github.com/nextcloud/server/blob/master/core/shipped.json
You could make a patch to add your app here.
