### ISSUE TITLE
Cannot save change of background jobs from Cron to Ajax

### ISSUE THREAD

**Issue by wiegell** [nextcloud/server#20225]
### Steps to reproduce
1. Change background-jobs to Ajax in webinterface or with OCC-command
2. Wait for Cron-job to run
3. The setting has now reverted to Cron again in the web interface

<img width="829" alt="Skærmbillede 2020-03-29 kl  20 50 30" src="https://user-images.githubusercontent.com/29224981/77861572-02cc1e80-7216-11ea-8bfe-f24a45aa37c2.png">

### Expected behaviour
- That Nextcloud alter the Cronjob
- That cron.php should _ignore_ calls from crond, if the setting is Ajax in the database.
- That Nextcloud should not automatically revert the database-setting from Ajax to Cron, if cron.php is called by crond.

### Actual behaviour
- Opposite of above. The problem is almost impossible to solve if you're using a docker-file with the cron-job imbedded. Even if the cronjob is deleted in the container it will reappear when the docker container is restarted. It's a mayor problem when trying to keep low power consumption on a singleboard computer paired with regular HDD since the cron will cause spinups every 5 minutes (or whatever schedule is used by the docker-file). 

### Server configuration

**Operating system:**
Linux odroidxu4 4.14.150-odroidxu4 #2 SMP PREEMPT Mon Oct 28 08:07:45 CET 2019 armv7l GNU/Linux

**Web server:**
Nginx

**Database:**
MySQL

**PHP version:**
PHP 7.3.11 (cli) (built: Oct 26 2019 06:24:00) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 17.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Docker from https://github.com/linuxserver/docker-nextcloud.
I think i found the files creating the cron-job:
[https://github.com/linuxserver/docker-nextcloud/blob/master/root/etc/cont-init.d/50-install](https://github.com/linuxserver/docker-nextcloud/blob/master/root/etc/cont-init.d/50-install)
[https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/root](https://github.com/linuxserver/docker-nextcloud/blob/master/root/defaults/root)

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - bruteforcesettings: 1.4.0
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - dav: 1.13.0
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_external: 1.8.0
  - files_pdfviewer: 1.6.0
  - files_rightclick: 0.14.2
  - files_sharing: 1.9.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - nextcloud_announcements: 1.6.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - password_policy: 1.7.0
  - previewgenerator: 2.2.0
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - recommendations: 0.5.0
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - support: 1.0.1
  - survey_client: 1.5.0
  - systemtags: 1.7.0
  - text: 1.1.1
  - theming: 1.8.0
  - twofactor_backupcodes: 1.6.0
  - updatenotification: 1.7.0
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - admin_audit
  - encryption
  - user_ldap
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwritewebroot": "\/nextcloud",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.1.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": "0",
        "logdateformat": "F d, Y H:i:s"
</details>

**Are you using external storage, if yes which one:** Local "external storage" mounted to the docker container.

**Are you using encryption:** No

#### MySQL log (log/mysql/mysql.log) :
<details>
<summary>When setting Cron -> Ajax either through webUI or OCC:</summary>

```
9 Query	UPDATE `oc_appconfig` SET `configvalue` = 'ajax' WHERE (`appid` = 'core') AND (`configkey` = 'backgroundjobs_mode') AND (`configvalue` <> 'ajax’)
```
</details>

#### MySQL log (log/mysql/mysql.log):
<details>
<summary>When the cron-job is running (notice the timestamp)</summary>

```
200329 21:15:01	   16 Query	UPDATE `oc_appconfig` SET `configvalue` = 'cron' WHERE (`appid` = 'core') AND (`configkey` = 'backgroundjobs_mode') AND (`configvalue` <> 'cron’)”
```
</details>

**Comment by hvedemelsbof** [comment]
It's been suggested to remove/rename the cron.php as a temporary solution:

**Comment by Nils160988** [comment]
I think, it is quite convenient that a cronjob automatically changes the setting from ajax to cron and I am sure it is intended behavior.
The default is ajax, if you want to change to cron, you can configure a cronjob. If you don't, it stays with ajax, so I see no problem here.

**Comment by hvedemelsbof** [comment]
I've seen several dockerfiles for different architectures that implements a cronjob in the docker-image automatically that means that all the non-technical users following tutorials setting up Nextcloud in a docker-container won't have the opportunity to select Ajax and the default will de facto be Cron. That is a problem IMO.

**Comment by Nils160988** [comment]
Hmm, I understand your problem. Maybe it would be better to discuss this topic at the place, where the docker-container are build because I still think this is no server issue.

**Comment by hvedemelsbof** [comment]
Well it could be solved across all the docker builds if the cron.php just checks with the database and is not "convinced" by the cron-job. And what really is the downside? If you're smart enough to create a cronjob surely you're able to just switch to the setting to cron in the webUI as well.

**Comment by Nils160988** [comment]
A possible downside might be install scripts for some people relying on this behavior (or just people not aware of the change). If this was a new piece of software, probably both choices are sensible and have their downsides.
Nextcloud maintainers should decide if they want to change the behavior or not. @nextcloud/server-triage

**Comment by hvedemelsbof** [comment]
Yea ok, i see.
In that light, keeping the current option would favor sysadmins rather than the regular user. Doesn't really sound like the spirit of Nextcloud to me.
The installscripts you mention should simply add the already documented command:
`sudo -u www-data php occ background:ajax`

**Comment by wiegell** [comment]
I have patched cron.php to behave as i expect it to.
It's my first contribution to a project of this size, and i'm not very skilled in PHP.
Maybe someone could help me with unit testing, of which i know basically nothing?

[cron.php.zip](https://github.com/nextcloud/server/files/4519088/cron.php.zip)

**Comment by blizzz** [comment]
What's the motivation to retreat from cron and favor ajax?

**Comment by nickvergessen** [comment]
Yeah sorry to say, but we should not actively support reducing cron. More and more features depend on it. Actually we did the opposite and warn people now when cron is not executed often enough.

**Comment by wiegell** [comment]
> What's the motivation to retreat from cron and favor ajax?

I feel like i've already pretty thoroughly explained the situation above. In summery: I disagree that this patch is **favoring** ajax. It just ensures, that newcomers actually _have_ the option of selecting ajax, which i couldn't do before this edit because of the default cronjob in my docker image. Cron.php will still respond to calls from cronjob (or CLI as the if-statement is using in the code), but only if the setting is cron in the database.

> Yeah sorry to say, but we should not actively support reducing cron. More and more features depend on it. Actually we did the opposite and warn people now when cron is not executed often enough.

Am i not correct, when i say that exactly the same background jobs will be executed when cron.php is called via Ajax? Could you elaborate on the problems that comes with cron not being executed?

**Comment by nickvergessen** [comment]
So the problem with ajax cron is it runs 1 job every time you load a page. So when e.g. you only use your sync client, you never load a UI page and therefore never run any background job. This means the instance will never notify you about outstanding updates, can not clean up versions or the thrashbin, no writing back of files from the document server when connection was lost, etc.

To achieve what you want (**and I still recommend to not do it**) just first remove the system cron entry (maybe even from your docker file), then make sure there is currently no cron running and then change the selection to ajax.

**Comment by nickvergessen** [comment]
And it's totally fine to run a modified version (at own risk) and share a patch here with everyone, but we are not going to merge that code into our codebase.

**Comment by wiegell** [comment]
> So the problem with ajax cron is it runs 1 job every time you load a page. So when e.g. you only use your sync client, you never load a UI page and therefore never run any background job. This means the instance will never notify you about outstanding updates, can not clean up versions or the thrashbin, no writing back of files from the document server when connection was lost, etc.
> 
> To achieve what you want (**and I still recommend to not do it**) just first remove the system cron entry (maybe even from your docker file), then make sure there is currently no cron running and then change the selection to ajax.

Thank you for explaining, i didn’t consider these factors.
Do you have any suggestions as to how distributors of docker files can help giving both options to their audience?
Maybe a solution could be to advice for making the docker cron folder a mount, and therefore editable.

**Comment by kesselb** [comment]
I like the suggestion. If ajax or webcron is configured `php cron.php` should exit with error code 1 and print a message and probably the occ command to change that value. 

>  quite convenient that a cronjob automatically changes 

Yes it's convenient. I have a problem with such convenients in general. Right now the mode is changed without any notice. I would expect a warning if the mode is not configured.

**Comment by MorrisJobke** [comment]
> Yes it's convenient. I have a problem with such convenients in general. Right now the mode is changed without any notice. I would expect a warning if the mode is not configured.

I also thought about this already in the past. The change is done here: https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/cron.php#L109

Any preference if we should drop it? Also running the AJAX version together with the CLI version does not interfere anymore as we have locking on a per job base. On the other side: it doesn't make sense to let cron run through the Webserver if it is already periodically run on the CLI. The CLI is always more robust due to not being vulnerable to webserver timeouts.

**Comment by wiegell** [comment]
> > Yes it's convenient. I have a problem with such convenients in general. Right now the mode is changed without any notice. I would expect a warning if the mode is not configured.
> 
> I also thought about this already in the past. The change is done here:
> 
> https://github.com/nextcloud/server/blob/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/cron.php#L109
> 
> Any preference if we should drop it? Also running the AJAX version together with the CLI version does not interfere anymore as we have locking on a per job base. On the other side: it doesn't make sense to let cron run through the Webserver if it is already periodically run on the CLI. The CLI is always more robust due to not being vulnerable to webserver timeouts.

Only editing this line would not solve my problem though, since the jobs would be run by cron anyway, even if the setting stayed as ajax. I think your suggestion could serve a purpose, if one actually wants to trigger from both a cronjob and ajax at the same time. But is that even a thing? :) If so the radio-switcher in the UI maybe would have to become checkboxes for each of the three options? From what i’ve sensed from the other commenters, i don’t think that’s going to be popular :)

**Comment by kesselb** [comment]
Your problem is caused by your setup. The nextcloud/docker image does not run the cron by default.

**Comment by MorrisJobke** [comment]
I still don't get why one would only allow cron jobs from AJAX. What is the problem from having the cron jobs run also from CLI?

**Comment by kesselb** [comment]
> It's a mayor problem when trying to keep low power consumption on a singleboard computer paired with regular HDD since the cron will cause spinups every 5 minutes (or whatever schedule is used by the docker-file).

@MorrisJobke but that's a very special case. `nextcloud/docker` does not run cron by default. I would open a feature request at https://github.com/linuxserver/docker-nextcloud and ask for a environment variable to turn cron off. 

> Also running the AJAX version together with the CLI version does not interfere anymore as we have locking on a per job base. 

Hmm. I'm not a fan ;) A hybrid mode sounds good at first but try to reproduce a issue with such a configuration :see_no_evil:

> What is the problem from having the cron jobs run also from CLI?

That's not my point ;) I think cron.php should respect the `backgroundjobs_mode` configuration. If one configured ajax and runs cron.php from cli we should exit with error code 1.

**Comment by MorrisJobke** [comment]
> I think cron.php should respect the `backgroundjobs_mode` configuration. If one configured ajax and runs cron.php from cli we should exit with error code 1.

I guess there is nothing wrong with this change in NC 20 cycle. 👍

**Comment by ozboss** [comment]
Well I actually would like the run both AJAX and cron, here is my reason:
When I run cron every so often my drives will never sleep and this is a (noise) problem for me.
So the idea would be to run cron.php together with my backup job once a day when the drives are active anyway.
Then run AJAX always when the server is accessed anyway.

As far as I understood this would be better then never running cron.php.
Unfortunately this is not possible with the configuration automatically switching to cron once cron.php is run.

**Comment by nickvergessen** [comment]
> Anyway is this recommended or is it pointless to run cron.php only once a day?

It's recommended to run cron.php every 5 minutes
