### ISSUE TITLE
Problems with OAuth2 system

### ISSUE THREAD

**Issue by gael-grzelak** [nextcloud/server#20228]
The authorization entry point always asks to connect and authorize the client, even if the client has already been accepted and he is already connected.
(With other providers, after accepting the client at the very first time, I am redirected transparently.)

And there is also a problem with the redirection. In the standard login process, you have to redirect the client with the parameter given in the request. The parameter saved on Nextcloud must be used for security (trusted domain). That's why I can't redirect on sub.domain.com, or domain.com/variable_path. Even worse, I loose other parameters currently used on my page. domain.com?paramaters (parameters must be add with the returned code, statement, token...)

Request parameters :
```
"response_type" => "code",
"client_id" => CLIENT_ID,
"redirect_uri" => "http://sub.domain.com/varible_path?parameters"
// No scope
```

![image](https://user-images.githubusercontent.com/48556902/77898810-07c3b900-727c-11ea-847c-08728967f719.png)
![image](https://user-images.githubusercontent.com/48556902/77898847-190cc580-727c-11ea-8e44-f2a065db91ac.png)
![image](https://user-images.githubusercontent.com/48556902/77899155-989a9480-727c-11ea-8f81-fc28e298ca11.png)

Can you also clarify the [documentation](https://docs.nextcloud.com/server/18/admin_manual/configuration_server/oauth2.html) by giving each possible value of the query parameters ?

I use a fresh installation of Nextcloud 18.0.3 on Ubuntu Server 18.04. No error, no warning in Nextcloud Administration panel.

Thank you ! :-)

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by gael-grzelak** [comment]
Still valid, but maybe this bug is not the most important.
