### ISSUE TITLE
Admin page translation issue

### ISSUE THREAD

**Issue by Loki3000** [nextcloud/server#2022]
### Steps to reproduce
1. open /index.php/settings/admin url
2. look at left menu

### Expected behaviour
Expected that left menu is localized

### Actual behaviour
Localized only one item of left menu

### Server configuration
**Operating system**:
ubuntu 16.4
**Web server:**
Apache2
**Database:**
mysql 5.7.16
**PHP version:**
PHP 7.0.12
**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (stable)
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated form ownCloud

I've a little dig in this problem and get follow:
in ```lib/private/Settings/Manager.php:332```

```0 => [new Section('server',        $this->l->t('Server settings'), 0)],```

```$this->l``` contains strings from ```core/l10n/*.json``` file
but required string ```'Server settings'``` (and followed strings) contains in file ```lib/l10n/*.json```

**Comment by MariusBluem** [comment]
Could you have a look into that 😁 @MorrisJobke ... On Transifex it seems to be translated 🤔

**Comment by Loki3000** [comment]
Yes strings translated, but placed in other dir:
file loaded into ```$this->l``` object
**core**/l10n/*.json

file contains required strings
**lib**/l10n/*.json

**Comment by MariusBluem** [comment]
@Loki3000 you may want to fix this directly over an PR? 😁

**Comment by Loki3000** [comment]
I don't know right solution. Maybe translate strings placed in wrong place, and also maybe that to Manager.php was sent wrong object as a parameter.
Someone who knows the code should confirm that it is not the second case.
