### ISSUE TITLE
Admin Quota

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/server#20222]
I think it was possible before to set the Quota for the first user as well. At least that should be possible. It can be useful to restrict the storage one uses and to get warnings when approaching that limit. The default setting could be unlimited but i dont see any good reason why it shouldnt be possible to set a maximum Quota for the first/admin user. To achieve what id like id have to create a second account and switch or use groups or something else which isnt intuitively.

**Comment by kesselb** [comment]
Please use the search next time or ask at help.nextcloud.com first.

https://github.com/nextcloud/server/pull/19882

**Comment by acs-ferreira** [comment]
Shouldn't this be fixed on `18.0.3`?
(https://github.com/nextcloud/server/pull/19882 has been committed to `stable18` before the release).

https://github.com/nextcloud/server/issues/20174 too.

cc @juliushaertl

**Comment by juliushaertl** [comment]
18.0.3 was an intermediate release and just contained security related fixes and https://github.com/nextcloud/server/pull/19882 shows that it is part of 18.0.4 :wink:

**Comment by acs-ferreira** [comment]
My bad, sorry & thanks!
