### ISSUE TITLE
Unable to Log out, redirects back to home page

### ISSUE THREAD

**Issue by tbennett6421** [nextcloud/server#2023]
### Steps to reproduce
1. Login to next cloud as any user.
2. Click username > log out

### Expected behaviour
User should logout and page should redirect to login page

### Actual behaviour
Tell us what happens instead
redirects instead to apps/files as the logged in user.

### Server configuration
**Operating system**:
Ubuntu 16.04.1 LTS

**Web server:**
Apache/2.4.18 (Ubuntu)

**Database:**
mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

**Nextcloud version:**
Nextcloud 9.0.51 (production)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
nextcloud.com zip file

**Signing status:**
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - comments: 0.2
  - dav: 0.1.6
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_external
  - user_external
  - user_ldap

**The content of config/config.php:**
{
    "system": {
        "instanceid": "octr0n1m8725",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.nsecure.me"
        ],
        "datadirectory": "\/mnt\/cloud\/",
        "overwrite.cli.url": "http:\/\/cloud.nsecure.me",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "9.0.51.0",
        "dbname": "cloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "America\/Chicago",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "check_for_working_htaccess": true,
        "cron_log": true,
        "log_rotate_size": 104857600,
        "appstoreenabled": true
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.2.1",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "backgroundjob": {
            "lastjob": "9"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "core": {
            "OC_Channel": "production",
            "backgroundjobs_mode": "cron",
            "installedat": "1467650369.5398",
            "lastcron": "1478349003",
            "lastupdateResult": "[]",
            "lastupdatedat": "1478349427",
            "oc.integritycheck.checker": "[]",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "0.0.4",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "enabled": "yes",
            "installed_version": "1.4.4",
            "types": "filesystem"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "0.9.1",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "0.8.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "yes",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "yes",
            "installed_version": "14.5.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.2.3",
            "types": "logging"
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "0.4.1",
            "types": "prevent_group_restriction"
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "0.2",
            "types": "logging"
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "0.1.0",
            "types": ""
        }
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
nfs

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google Chrome
Safari

**Operating system:**
Mac OS X 10.12
Windows 7 Ultimate x64

Feels like it may be related to mod_rewrite
[Sat Nov 05 08:27:02.213720 2016] [rewrite:trace2] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] init rewrite engine with requested uri /ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.213774 2016] [rewrite:trace1] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] pass through /ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214204 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] add path info postfix: /var/www/cloud/ocs/v2.php -> /var/www/cloud/ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214244 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] strip per-dir prefix: /var/www/cloud/ocs/v2.php/apps/notifications/api/v1/notifications -> ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214255 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] applying pattern '^core/js/oc.js$' to uri 'ocs/v2.php/apps/notifications/api/v1/notifications'
[Sat Nov 05 08:27:02.214266 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] add path info postfix: /var/www/cloud/ocs/v2.php -> /var/www/cloud/ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214298 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] strip per-dir prefix: /var/www/cloud/ocs/v2.php/apps/notifications/api/v1/notifications -> ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214309 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] applying pattern '^core/preview.png$' to uri 'ocs/v2.php/apps/notifications/api/v1/notifications'
[Sat Nov 05 08:27:02.214319 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] add path info postfix: /var/www/cloud/ocs/v2.php -> /var/www/cloud/ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214328 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] strip per-dir prefix: /var/www/cloud/ocs/v2.php/apps/notifications/api/v1/notifications -> ocs/v2.php/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214337 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] applying pattern '.' to uri 'ocs/v2.php/apps/notifications/api/v1/notifications'
[Sat Nov 05 08:27:02.214361 2016] [rewrite:trace1] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396850a0/initial] [perdir /var/www/cloud/] pass through /var/www/cloud/ocs/v2.php
[Sat Nov 05 08:27:02.214623 2016] [rewrite:trace2] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] init rewrite engine with requested uri /apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214656 2016] [rewrite:trace1] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] pass through /apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214726 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] add path info postfix: /var/www/cloud/apps/notifications/api -> /var/www/cloud/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214758 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] strip per-dir prefix: /var/www/cloud/apps/notifications/api/v1/notifications -> apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214769 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] applying pattern '^core/js/oc.js$' to uri 'apps/notifications/api/v1/notifications'
[Sat Nov 05 08:27:02.214779 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] add path info postfix: /var/www/cloud/apps/notifications/api -> /var/www/cloud/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214788 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] strip per-dir prefix: /var/www/cloud/apps/notifications/api/v1/notifications -> apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214795 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] applying pattern '^core/preview.png$' to uri 'apps/notifications/api/v1/notifications'
[Sat Nov 05 08:27:02.214804 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] add path info postfix: /var/www/cloud/apps/notifications/api -> /var/www/cloud/apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214813 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] strip per-dir prefix: /var/www/cloud/apps/notifications/api/v1/notifications -> apps/notifications/api/v1/notifications
[Sat Nov 05 08:27:02.214821 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] applying pattern '.' to uri 'apps/notifications/api/v1/notifications'
[Sat Nov 05 08:27:02.214886 2016] [rewrite:trace2] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] rewrite 'apps/notifications/api/v1/notifications' -> 'index.php'
[Sat Nov 05 08:27:02.214933 2016] [rewrite:trace3] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] add per-dir prefix: index.php -> /var/www/cloud/index.php
[Sat Nov 05 08:27:02.214947 2016] [rewrite:trace2] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] forcing '/var/www/cloud/index.php' to get passed through to next API URI-to-filename handler
[Sat Nov 05 08:27:02.214957 2016] [rewrite:trace2] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] trying to replace prefix /var/www/cloud/ with /
[Sat Nov 05 08:27:02.214966 2016] [rewrite:trace1] [pid 1958] mod_rewrite.c(476): [client 10.0.0.51:52863] 10.0.0.51 - - [cloud.nsecure.me/sid#7f6641fc3140][rid#7f66396870a0/subreq] [perdir /var/www/cloud/] internal redirect with /index.php [INTERNAL REDIRECT]

**Comment by nickvergessen** [comment]
Please update to 9.0.53 or 10.0.1, there have been some fixes to redirects.
Please report back if updating solved the issue for you.

**Comment by tbennett6421** [comment]
Upgraded to 10.0.1 and this issue has been resolved.

Thank you
