### ISSUE TITLE
Firefox - Unable to share files.

### ISSUE THREAD

**Issue by R3tr0R4z0r** [nextcloud/server#20230]
### Share option not showing on Firefox

When the client is using Firefox the share option in the right hand menu does not show thus not allowing any files or folders to be hared in any form.
When tested in Chrome everything works normally.
Screen grabs attached to show the issue on Firefox compared to Chrome.

### Steps to reproduce
1. Login to Nextcloud server with Firefox 74.0 (64bit), Windows 10.
2. Select any file and click the share button.
3. No Share option is shown, works in Chrome, Version 80.0.3987.149 (Official Build) (64-bit)

### Expected behaviour
Share option shown in right hand menu.

### Actual behaviour
No Share option is shown

### Server configuration

**Operating system:**
Ubuntu 18.04 LTS

**Web server:**
Apache2.1.4

**Database:**
MySQL

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.2
10.0.2 updated from 18.0.1

**Where did you install Nextcloud from:**
Update from browser updated
Originally installed from Nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
Firefox

**Operating system:**
Win 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

![Capture Chrome](https://user-images.githubusercontent.com/11089936/77903439-c8489d00-727a-11ea-95a6-c4a19af90df0.JPG)
![Capture Firefox](https://user-images.githubusercontent.com/11089936/77903443-c8e13380-727a-11ea-9a6f-4903dca1e0e0.png)

</details>

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/19908?

**Comment by R3tr0R4z0r** [comment]
very true, didn't see that one, thank you kesselb, 
closing as duplicate
