### ISSUE TITLE
Can't upload file > 1M - Webdav - External Storage

### ISSUE THREAD

**Issue by Bushrider** [nextcloud/server#20248]
[reaction]https://github.com/nextcloud/server/issues/12728#issuecomment-606591305

### Steps to reproduce
1.Connect external storage with webdav
2.Upload File > 1M to external storage

### Expected behaviour
Should upload to external storage

### Actual behaviour
Client error: `PUT http://xxx.xxx.fr/webdav/Nuage/Emilie/logofacture.png.ocTransferId37033970.part` resulted in a `417 Expectation Failed` response: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "htt (truncated...)

### Server configuration

**Operating system:**
Debian 8 jessie
**Web server:**
nginx 1.15.12-1
**Database:**
mysql 5.5.62
**PHP version:**
php7.4-fpm
**Nextcloud version:** (see Nextcloud admin page)
18.0.3.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
Web Installer
**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.4
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - spreed
  - user_ldap

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nuage.informatdom.fr"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "https:\/\/nuage.informatdom.fr",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "logfilemode": 416,
        "loglevel": "2",
        "logdateformat": "F d, Y H:i:s"
    }
}

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Webdav
**Are you using encryption:** yes/no
no

**Browser:**

74.0
Firefox Release
March 10, 2020

<summary>Web server error log</summary>

[error.log](https://github.com/nextcloud/server/files/4409320/error.log)

<summary>Nextcloud log</summary>

[nextcloud.log](https://github.com/nextcloud/server/files/4409316/nextcloud.log)

<details>
<summary>Browser log</summary>

```
a) PUT 500
b) The humanFileSize library is deprecated! It will be removed in nextcloud 19.
```
</details>

**Comment by kesselb** [comment]
```
Client error: `PUT http://orange.soubeyran.fr/webdav/Nuage/Anthony/logo%20d%C3%A9grad%C3%A9.png.ocTransferId645717793.part` resulted in a `417 Expectation Failed` response:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "htt (truncated...)
```

That's the response form your NAS. As start I would try to list and upload files with another webdav client. 

```
Index: apps/dav/lib/Connector/Sabre/File.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/dav/lib/Connector/Sabre/File.php	(revision f5e81749901ae7a5c6db91bfd61c886b2c644592)
+++ apps/dav/lib/Connector/Sabre/File.php	(date 1585663702290)
@@ -415,6 +415,9 @@
 			try {
 				$res = $this->fileView->fopen(ltrim($this->path, '/'), 'rb');
 			} catch (\Exception $e) {
+				if ($e instanceof \GuzzleHttp\Exception\ClientException && $e->getResponse() !== null) {
+					\OC::$server->getLogger()->debug('Response from dav endpoint: ' . $e->getResponse()->getBody()->getContents());
+				}
 				$this->convertToSabreException($e);
 			}
 			if ($res === false) {
```

As second step to log the complete response from the NAS.

**Comment by Bushrider** [comment]
> ```
> Client error: `PUT http://orange.soubeyran.fr/webdav/Nuage/Anthony/logo%20d%C3%A9grad%C3%A9.png.ocTransferId645717793.part` resulted in a `417 Expectation Failed` response:
> <?xml version="1.0" encoding="iso-8859-1"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
>          "htt (truncated...)
> ```
> 
> That's the response form your NAS. As start I would try to list and upload files with another webdav client.

As described here : [relation]https://github.com/nextcloud/server/issues/12728#issuecomment-606591305
I can upload the same file to the Nas using File explorer's webdav connection without any problem.

<details>
> Index: apps/dav/lib/Connector/Sabre/File.php
> IDEA additional info:
> Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
> <+>UTF-8
> ===================================================================
> --- apps/dav/lib/Connector/Sabre/File.php	(revision f5e81749901ae7a5c6db91bfd61c886b2c644592)
> +++ apps/dav/lib/Connector/Sabre/File.php	(date 1585663702290)
> @@ -415,6 +415,9 @@
>  			try {
>  				$res = $this->fileView->fopen(ltrim($this->path, '/'), 'rb');
>  			} catch (\Exception $e) {
> +				if ($e instanceof \GuzzleHttp\Exception\ClientException && $e->getResponse() !== null) {
> +					\OC::$server->getLogger()->debug('Response from dav endpoint: ' . $e->getResponse()->getBody()->getContents());
> +				}
>  				$this->convertToSabreException($e);
>  			}
>  			if ($res === false) {
> ```
> 
</details>
> As second step to log the complete response from the NAS.


<details>
<summary>Log WebUI</summary>


Fatal | webdav | Sabre\DAV\Exception: Client  error: `PUT  http://orange.soubeyran.fr/webdav/Nuage/Emilie/logofacture.png.ocTransferId1267903985.part`  resulted in a `417 Expectation Failed` response: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"          "htt (truncated...) /var/www/nuage/apps/dav/lib/Connector/Sabre/File.php - line 244: OCA\DAV\Connector\Sabre\File->convertToSabreException()/var/www/nuage/apps/dav/lib/Connector/Sabre/Directory.php - line 156: OCA\DAV\Connector\Sabre\File->put()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile()<<closure>>Sabre\DAV\CorePlugin->httpPut()/var/www/nuage/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod()/var/www/nuage/apps/dav/appinfo/v1/webdav.php - line 82: Sabre\DAV\Server->exec()/var/www/nuage/remote.php - line 165: require_once("/var/www/nu ... p")Causé parGuzzleHttp\Exception\ClientException: Client  error: `PUT  http://orange.soubeyran.fr/webdav/Nuage/Emilie/logofacture.png.ocTransferId1267903985.part`  resulted in a `417 Expectation Failed` response: <?xml version="1.0" encoding="iso-8859-1"?> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"          "htt (truncated...) /var/www/nuage/3rdparty/guzzlehttp/guzzle/src/Middleware.php - line 66: GuzzleHttp\Exception\RequestException::create()/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 203: GuzzleHttp\Middleware::GuzzleHttp\{closure}("*** sensiti ... *")/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 156: GuzzleHttp\Promise\Promise::callHandler()/var/www/nuage/3rdparty/guzzlehttp/promises/src/TaskQueue.php - line 47: GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}("*** sensiti ... *")/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 246: GuzzleHttp\Promise\TaskQueue->run()/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 223: GuzzleHttp\Promise\Promise->invokeWaitFn()/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 267: GuzzleHttp\Promise\Promise->waitIfPending()/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 225: GuzzleHttp\Promise\Promise->invokeWaitList()/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php - line 62: GuzzleHttp\Promise\Promise->waitIfPending()/var/www/nuage/3rdparty/guzzlehttp/guzzle/src/Client.php - line 131: GuzzleHttp\Promise\Promise->wait()/var/www/nuage/lib/private/Http/Client/Client.php - line 251: GuzzleHttp\Client->request()/var/www/nuage/lib/private/Files/Storage/DAV.php - line 513: OC\Http\Client\Client->put()/var/www/nuage/lib/private/Files/Storage/DAV.php - line 420: OC\Files\Storage\DAV->uploadFile()/var/www/nuage/lib/private/Files/Storage/DAV.php - line 411: OC\Files\Storage\DAV->writeBack()<<closure>>OC\Files\Storage\DAV->OC\Files\Storage\{closure}("*** sensiti ... *")/var/www/nuage/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php - line 121: call_user_func()<<closure>>Icewind\Streams\CallbackWrapper->stream_close()/var/www/nuage/lib/private/Files/Storage/Common.php - line 862: fclose()/var/www/nuage/lib/private/Files/Storage/Wrapper/Wrapper.php - line 630: OC\Files\Storage\Common->writeStream()/var/www/nuage/lib/private/Files/Storage/Wrapper/Wrapper.php - line 630: OC\Files\Storage\Wrapper\Wrapper->writeStream()/var/www/nuage/apps/dav/lib/Connector/Sabre/File.php - line 192: OC\Files\Storage\Wrapper\Wrapper->writeStream()/var/www/nuage/apps/dav/lib/Connector/Sabre/Directory.php - line 156: OCA\DAV\Connector\Sabre\File->put()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096: OCA\DAV\Connector\Sabre\Directory->createFile()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525: Sabre\DAV\Server->createFile()<<closure>>Sabre\DAV\CorePlugin->httpPut()/var/www/nuage/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit()/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod()/var/www/nuage/apps/dav/appinfo/v1/webdav.php - line 82: Sabre\DAV\Server->exec()/var/www/nuage/remote.php - line 165: require_once("/var/www/nu ... p")
-- | -- | --



</details>

<details>
<summary>Nextcloud Log</summary>
<pre>&quot;reqId&quot;:&quot;h6FsWPiHuamkZpR5CI2f&quot;,&quot;level&quot;:4,&quot;time&quot;:&quot;March 31, 2020 15:41:14&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;webdav&quot;,&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;/remote.php/webdav/Nuage/Emilie/logofacture.png&quot;,&quot;message&quot;:{&quot;Exception&quot;:&quot;Sabre\\DAV\\Exception&quot;,&quot;Message&quot;:&quot;Client error: `PUT http://orange.soubeyran.fr/webdav/Nuage/Emilie/logofacture.png.ocTransferId1912597708.part` resulted in a `417 Expectation Failed` response:\n&lt;?xml version=\&quot;1.0\&quot; encoding=\&quot;iso-8859-1\&quot;?&gt;\n&lt;!DOCTYPE html PUBLIC \&quot;-//W3C//DTD XHTML 1.0 Transitional//EN\&quot;\n         \&quot;htt (truncated...)\n&quot;,&quot;Code&quot;:0,&quot;Trace&quot;:[{&quot;file&quot;:&quot;/var/www/nuage/apps/dav/lib/Connector/Sabre/File.php&quot;,&quot;line&quot;:244,&quot;function&quot;:&quot;convertToSabreException&quot;,&quot;class&quot;:&quot;OCA\\DAV\\Connector\\Sabre\\File&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/apps/dav/lib/Connector/Sabre/Directory.php&quot;,&quot;line&quot;:156,&quot;function&quot;:&quot;put&quot;,&quot;class&quot;:&quot;OCA\\DAV\\Connector\\Sabre\\File&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/3rdparty/sabr$
{&quot;reqId&quot;:&quot;2Z9Lyw05XjvaaRtoDdnW&quot;,&quot;level&quot;:3,&quot;time&quot;:&quot;March 31, 2020 15:43:28&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;remote&quot;,&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;/remote.php/webdav/Nuage/Emilie/logofacture.png&quot;,&quot;message&quot;:{&quot;Exception&quot;:&quot;ParseError&quot;,&quot;Message&quot;:&quot;syntax error, unexpected &apos;if&apos; (T_IF)&quot;,&quot;Code&quot;:0,&quot;Trace&quot;:[{&quot;file&quot;:&quot;/var/www/nuage/lib/composer/composer/ClassLoader.php&quot;,&quot;line&quot;:322,&quot;function&quot;:&quot;Composer\\Autoload\\includeFile&quot;},{&quot;function&quot;:&quot;loadClass&quot;,&quot;class&quot;:&quot;Composer\\Autoload\\ClassLoader&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/apps/dav/lib/Connector/Sabre/Directory.php&quot;,&quot;line&quot;:150,&quot;function&quot;:&quot;spl_autoload_call&quot;},{&quot;file&quot;:&quot;/var/www/nuage/3rdparty/sabre/dav/lib/DAV/Server.php&quot;,&quot;line&quot;:1096,&quot;function&quot;:&quot;createFile&quot;,&quot;class&quot;:&quot;OCA\\DAV\\Connector\\Sabre\\Directory&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/3rdparty/sabre/dav/lib/DAV/CorePlugin.php&quot;,&quot;line&quot;:525,&quot;function&quot;:&quot;createFile&quot;,&quot;class&quot;:&quot;Sabre\\DAV\\Server&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;function&quot;:&quot;httpPut&quot;,&quot;c$
{&quot;reqId&quot;:&quot;2Z9Lyw05XjvaaRtoDdnW&quot;,&quot;level&quot;:3,&quot;time&quot;:&quot;March 31, 2020 15:43:28&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;no app in context&quot;,&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;/remote.php/webdav/Nuage/Emilie/logofacture.png&quot;,&quot;message&quot;:{&quot;Exception&quot;:&quot;Symfony\\Component\\Routing\\Exception\\RouteNotFoundException&quot;,&quot;Message&quot;:&quot;Unable to generate a URL for the named route \&quot;calendar.view.index\&quot; as such route does not exist.&quot;,&quot;Code&quot;:0,&quot;Trace&quot;:[{&quot;file&quot;:&quot;/var/www/nuage/lib/private/Route/Router.php&quot;,&quot;line&quot;:339,&quot;function&quot;:&quot;generate&quot;,&quot;class&quot;:&quot;Symfony\\Component\\Routing\\Generator\\UrlGenerator&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/lib/private/URLGenerator.php&quot;,&quot;line&quot;:82,&quot;function&quot;:&quot;generate&quot;,&quot;class&quot;:&quot;OC\\Route\\Router&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/lib/private/NavigationManager.php&quot;,&quot;line&quot;:293,&quot;function&quot;:&quot;linkToRoute&quot;,&quot;class&quot;:&quot;OC\\URLGenerator&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/lib/private/NavigationManager.php&quot;,&quot;line&quot;:114,&quot;function&quot;:&quot;init&quot;,$
{&quot;reqId&quot;:&quot;2Z9Lyw05XjvaaRtoDdnW&quot;,&quot;level&quot;:3,&quot;time&quot;:&quot;March 31, 2020 15:43:28&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;no app in context&quot;,&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;/remote.php/webdav/Nuage/Emilie/logofacture.png&quot;,&quot;message&quot;:{&quot;Exception&quot;:&quot;Symfony\\Component\\Routing\\Exception\\RouteNotFoundException&quot;,&quot;Message&quot;:&quot;Unable to generate a URL for the named route \&quot;photos.page.index\&quot; as such route does not exist.&quot;,&quot;Code&quot;:0,&quot;Trace&quot;:[{&quot;file&quot;:&quot;/var/www/nuage/lib/private/Route/Router.php&quot;,&quot;line&quot;:339,&quot;function&quot;:&quot;generate&quot;,&quot;class&quot;:&quot;Symfony\\Component\\Routing\\Generator\\UrlGenerator&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/lib/private/URLGenerator.php&quot;,&quot;line&quot;:82,&quot;function&quot;:&quot;generate&quot;,&quot;class&quot;:&quot;OC\\Route\\Router&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/lib/private/NavigationManager.php&quot;,&quot;line&quot;:293,&quot;function&quot;:&quot;linkToRoute&quot;,&quot;class&quot;:&quot;OC\\URLGenerator&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/lib/private/NavigationManager.php&quot;,&quot;line&quot;:114,&quot;function&quot;:&quot;init&quot;,&quot;c$
{&quot;reqId&quot;:&quot;FAAEXbSnjipS6Ak8JYC0&quot;,&quot;level&quot;:3,&quot;time&quot;:&quot;March 31, 2020 15:44:15&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;no app in context&quot;,&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;/remote.php/webdav/Nuage/Emilie/logofacture.png&quot;,&quot;message&quot;:{&quot;Exception&quot;:&quot;GuzzleHttp\\Exception\\ClientException&quot;,&quot;Message&quot;:&quot;Client error: `PUT http://orange.soubeyran.fr/webdav/Nuage/Emilie/logofacture.png.ocTransferId1267903985.part` resulted in a `417 Expectation Failed` response:\n&lt;?xml version=\&quot;1.0\&quot; encoding=\&quot;iso-8859-1\&quot;?&gt;\n&lt;!DOCTYPE html PUBLIC \&quot;-//W3C//DTD XHTML 1.0 Transitional//EN\&quot;\n         \&quot;htt (truncated...)\n&quot;,&quot;Code&quot;:417,&quot;Trace&quot;:[{&quot;file&quot;:&quot;/var/www/nuage/3rdparty/guzzlehttp/guzzle/src/Middleware.php&quot;,&quot;line&quot;:66,&quot;function&quot;:&quot;create&quot;,&quot;class&quot;:&quot;GuzzleHttp\\Exception\\RequestException&quot;,&quot;type&quot;:&quot;::&quot;},{&quot;file&quot;:&quot;/var/www/nuage/3rdparty/guzzlehttp/promises/src/Promise.php&quot;,&quot;line&quot;:203,&quot;function&quot;:&quot;GuzzleHttp\\{closure}&quot;,&quot;class&quot;:&quot;GuzzleHttp\\Middleware&quot;,&quot;type&quot;:&quot;::&quot;,&quot;$
{&quot;reqId&quot;:&quot;FAAEXbSnjipS6Ak8JYC0&quot;,&quot;level&quot;:4,&quot;time&quot;:&quot;March 31, 2020 15:44:15&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;webdav&quot;,&quot;method&quot;:&quot;PUT&quot;,&quot;url&quot;:&quot;/remote.php/webdav/Nuage/Emilie/logofacture.png&quot;,&quot;message&quot;:{&quot;Exception&quot;:&quot;Sabre\\DAV\\Exception&quot;,&quot;Message&quot;:&quot;Client error: `PUT http://orange.soubeyran.fr/webdav/Nuage/Emilie/logofacture.png.ocTransferId1267903985.part` resulted in a `417 Expectation Failed` response:\n&lt;?xml version=\&quot;1.0\&quot; encoding=\&quot;iso-8859-1\&quot;?&gt;\n&lt;!DOCTYPE html PUBLIC \&quot;-//W3C//DTD XHTML 1.0 Transitional//EN\&quot;\n         \&quot;htt (truncated...)\n&quot;,&quot;Code&quot;:0,&quot;Trace&quot;:[{&quot;file&quot;:&quot;/var/www/nuage/apps/dav/lib/Connector/Sabre/File.php&quot;,&quot;line&quot;:244,&quot;function&quot;:&quot;convertToSabreException&quot;,&quot;class&quot;:&quot;OCA\\DAV\\Connector\\Sabre\\File&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/apps/dav/lib/Connector/Sabre/Directory.php&quot;,&quot;line&quot;:156,&quot;function&quot;:&quot;put&quot;,&quot;class&quot;:&quot;OCA\\DAV\\Connector\\Sabre\\File&quot;,&quot;type&quot;:&quot;-&gt;&quot;},{&quot;file&quot;:&quot;/var/www/nuage/3rdparty/sabr$
{&quot;reqId&quot;:&quot;qjbgJZe1PQPOZVXRLrX5&quot;,&quot;level&quot;:3,&quot;time&quot;:&quot;March 31, 2020 15:44:48&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;PHP&quot;,&quot;method&quot;:&quot;GET&quot;,&quot;url&quot;:&quot;/apps/logreader/get?offset=0&amp;count=50&amp;levels=11111&quot;,&quot;message&quot;:&quot;Trying to access array offset on value of type null at /var/www/nuage/apps/logreader/lib/Log/LogIterator.php#78&quot;,&quot;userAgent&quot;:&quot;Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0&quot;,&quot;version&quot;:&quot;18.0.3.0&quot;}
{&quot;reqId&quot;:&quot;qjbgJZe1PQPOZVXRLrX5&quot;,&quot;level&quot;:3,&quot;time&quot;:&quot;March 31, 2020 15:44:48&quot;,&quot;remoteAddr&quot;:&quot;86.207.213.220&quot;,&quot;user&quot;:&quot;Bushrider&quot;,&quot;app&quot;:&quot;PHP&quot;,&quot;method&quot;:&quot;GET&quot;,&quot;url&quot;:&quot;/apps/logreader/get?offset=0&amp;count=50&amp;levels=11111&quot;,&quot;message&quot;:&quot;Trying to access array offset on value of type null at /var/www/nuage/apps/logreader/lib/Log/LogIterator.php#78&quot;,&quot;userAgent&quot;:&quot;Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0&quot;,&quot;version&quot;:&quot;18.0.3.0&quot;}

</pre>
</details>

**Comment by kesselb** [comment]
You may change the loglevel to 0 in config.php to log the message.

**Comment by Bushrider** [comment]
Ok thx !
Here it is ...
[nextcloud.log](https://github.com/nextcloud/server/files/4410447/nextcloud.log)
