### ISSUE TITLE
enable application for group or user 

### ISSUE THREAD

**Issue by Sicoval31** [nextcloud/server#20247]
Hi, 
as many applications appear in nextcloud, and more since V18, my director decide to cut acces to certain application (onlyoffice, deck, etc ...).
But some useers need this appli !
Is it possible to add option to manage access to application by users and users groups ?

So i can give access to onlyoffice for a crew and disable it to the rest of users :)
thanks

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by Sicoval31** [comment]
It's not a bug... this feature doesn't exist !
Where can you manage that this user can access this application or not ???? nowhere

I not open an issue but a feature request !
