### ISSUE TITLE
http2 support in NextCloud

### ISSUE THREAD

**Issue by serenity-networks** [nextcloud/server#2024]
I'm having a hard time finding out if http2 is supported by Nextcloud.  Obviously, Apache supports it and it can easily be enabled, but I don't know if the underlying nextcloud architecture will play well.  I've been unable to so much as find a mention of http2 in the nextcloud github, or on the nextcloud website.  Can anyone shed light on this?

If http2 is not supported, it should definately be a priority.  There are many performance benefits it brings to the table and I can think of many that could potentially have a major impact on nextcloud performance.  Especially WRT syncing a significant number of small files.  Another major factor is security.

Thanks,
Mike

**Comment by MariusBluem** [comment]
Hi Mike,

Lets continue this discussion over here: https://help.nextcloud.com/t/http-2-yes-or-no/4026/21
You may want to report about your experiences using HTTP/2 with Nextcloud there ... THX!

Greetings

**Marius**
