### ISSUE TITLE
Reporting wrong version in Security Check

### ISSUE THREAD

**Issue by b3nis** [nextcloud/server#20255]
![Screenshot from 2020-04-01 09-41-46](https://user-images.githubusercontent.com/54119148/78113543-2eaaf800-7400-11ea-81e9-0bb29b430926.png)
![Screenshot from 2020-04-01 09-41-18](https://user-images.githubusercontent.com/54119148/78113547-2f438e80-7400-11ea-8f7f-4a95415a4def.png)

### Steps to reproduce
1. Go to settings -> overview
2. Note the NC version number (18.0.3)
3. Click on "Security Check" 
4. Security Check says I am running 18.0.0.10

### Expected behaviour
Security check should show the correct version number (at least that would make more sense)

### Actual behaviour
Security check shows a different version number

### Server configuration

**Operating system:**
Ubuntu Server 19.10 running NC, MariaDB, Letsencrypt and nginx via Docker

**Web server:**
Official NC docker

**Database:**
MariaDB docker

**PHP version:**
Whatever is included in latest NC docker

**Nextcloud version:** (see Nextcloud admin page)
18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
18 fresh install, updated 2 times so far

**Where did you install Nextcloud from:**
NC official docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```No errors have been found.
</details>

****
**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
![Screenshot from 2020-04-01 09-41-46](https://user-images.githubusercontent.com/54119148/78113462-133fed00-7400-11ea-8f32-97d2195747dc.png)
![Screenshot from 2020-04-01 09-41-18](https://user-images.githubusercontent.com/54119148/78113466-13d88380-7400-11ea-9463-3cc702a8ab39.png)



</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

### Logs

<!--- Reports without logs might be closed as unqualified reports! -->

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by tigernero79** [comment]
you need to clear your browser cache to get correct information

**Comment by kesselb** [comment]
1. Screenshot. Press re-trigger scan.

**Comment by b3nis** [comment]
@tigernero79 
Same behaviour (wrong version) even if I try in "private mode" (tried both Firefox and Chromium) :-(

**Comment by kesselb** [comment]
Please use https://help.nextcloud.com for such questions. GitHub is not a support channel.

**Comment by b3nis** [comment]
@tigernero79, thanks it works now.

@kesselb, sorry about that - I thought something was wrong. But my bad. Noted.
