### ISSUE TITLE
Statistics in OCC command

### ISSUE THREAD

**Issue by EpeR1** [nextcloud/server#20254]
It would be a great  option if I can get  statistics with occ command, like in the serverinfo module, plus two option: 
How many users are logged in by web page.
How many users are connected with desktop or mobile app.
(In last 5min, 1hour, 24hour.)

It can be more useful for generating nice Munin graph rather than serverinfo's web request.

**Comment by j-ed** [comment]
I think this is not the right repository for this enhancement request. The serverinfo app already exists to gather and visualize server specific figures. It also contains an api interface to access this data from other programs.
You should first check if you're satisfied with the available information and if not, open a new feature request [there](https://github.com/nextcloud/serverinfo/).

**Comment by EpeR1** [comment]
OK, thank you!
I moved my question to:  https://github.com/nextcloud/serverinfo/issues/190
