### ISSUE TITLE
URL shortener for v18

### ISSUE THREAD

**Issue by ifuchs** [nextcloud/server#20252]
A URL Shortener would be a very useful addition to NC v 18. Share renamer does not run on v18. Alternatively, and probably even better would be an integration of NC with either polr or yourls.

**Comment by kesselb** [comment]
This should be implemented as a Nextcloud app and not in the server itself. I'm closing this ticket in favor of https://help.nextcloud.com/t/nextcloud-url-shortener/10855.

**Comment by TobjasR** [comment]
> This should be implemented as a Nextcloud app and not in the server itself. I'm closing this ticket in favor of https://help.nextcloud.com/t/nextcloud-url-shortener/10855.

@kesselb , the former Dev of the ShareRenamer app says it's not feasible for NC 18+ any longer, and *needs* to be implemented in core .. https://github.com/DecaTec/sharerenamer could you please help make ShareRenamer or an integration of polr or yourls feasible by app?
