### ISSUE TITLE
Links at bottom of public share page on private instance goes to nextcloud.com

### ISSUE THREAD

**Issue by estan** [nextcloud/server#20253]
### Steps to reproduce
1. Set up a private Nextcloud instance
2. Create a shared file or folder link
3. Visit the shared link

### Expected behaviour

Either there should be no links at the bottom when the instance is private, or they should point to the private instance URL.

### Actual behaviour

There are two links at the bottom of the page

- "Nextcloud – a safe home for all your data" - points to https://nextcloud.com
- "Get your own free account" - points to https://nextcloud.com/signup

These two links are confusing for people with whom you've shared your link, because they may click them, ending up on the public Nextcloud.

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache 2.4.29

**Database:** PostgreSQL 10.10

**PHP version:** 7.2.24

**Nextcloud version:** 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Source

**Comment by gary-kim** [comment]
You can add the following to your `config.php` to remove that. 
```php
'simpleSignUpLink.shown' => false,
```
BTW, these kinds of questions are probably more suitable for the [forum](https://help.nextcloud.com) rather than the issue tracker.

**Comment by estan** [comment]
@gary-kim Thanks for the quick response. I must have missed that config option. Closing issue.

**Comment by estan** [comment]
Sorry, that option only removes the "Get your own free account" link, not the "Nextcloud – a safe home for all your data" link. Re-opening.

**Comment by gary-kim** [comment]
That part is from theming. You're welcome to to change that around in theming. This is my instance, for example: 
![image](https://user-images.githubusercontent.com/47195730/78109448-ca059280-742b-11ea-8523-881fb87fd35c.png)

Also, again, more suitable for the forum rather than the issue tracker.

**Comment by estan** [comment]
Okay, sorry. Even if it is part of theming, I thought it an issue that the default theme is showing a link to nextcloud.com even on a private instance. But if it's not considered an issue by Nextcloud team I'll close this issue.

**Comment by gary-kim** [comment]
All instances are private so...

Anyways, personally, I would not consider this a bug

**Comment by estan** [comment]
Alright, after thinking a bit about it, I think I agree. Linking to nextcloud.com is a good default. So closing issue. Someone can reopen if they disagree.

Potentially the code could be restructured so the link and tagline are part of the server core, and the theme just formats it, and the default could thdn be taken from the domain the instance is running under. But better not complicate things, the current situation is fine.

**Comment by punkyard** [comment]
hi, yes, i don't fully agree, as the frame saying "Nextcloud – a safe home for all your data" covers part of the text at the bottom at the page. Could it be move to a small frame on the left? or in the top barre? or just removed?

contacts who receive a public file from us, have absolutely no need of the link to our login page. It's been many times confusing, especially with students.

So, i'd be happy to ask again for the deletion of this announcement at the bottom of the page. ✌️

thanks for your concern and all the good work done for your users
