### ISSUE TITLE
Documents not being saved when editing with OnlyOffice. Nextcloud 18

### ISSUE THREAD

**Issue by Michael2222** [nextcloud/server#20264]
### Steps to reproduce
1. Open a document with OnlyOffice
2. Save this document
3. OPen this document via WebDAV
4. No changes are stored

See also https://help.nextcloud.com/t/documents-not-being-saved-when-editing-nextcloud-18-local-community-document-server-plugin/71382

### Expected behaviour
Changes stored in the document in nextcloud

### Actual behaviour
No changes

### Server configuration

**Operating system:**
Ubuntu 18.04 LTS

**Web server:**
Apache 2

**Database:**
MySQL

**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
18.03

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 17

**Where did you install Nextcloud from:**
Via ftp. No docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.4.0
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - circles: 0.18.4
  - cloud_federation_api: 1.1.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - deck: 0.8.0
  - documentserver_community: 0.1.5
  - drawio: 0.9.5
  - emlviewer: 0.0.5
  - external: 3.5.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_mindmap: 0.0.20
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 0.1.8
  - forms: 1.1.1
  - gpxpod: 4.2.1
  - groupfolders: 6.0.3
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.4
  - maps: 0.1.6
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - piwik: 0.5.4
  - polls: 1.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.1
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - socialsharing_email: 2.0.0
  - spreed: 8.0.6
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - unsplash: 1.1.5
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - files_versions
  - keeweb
  - nextcloud_announcements
  - printer
  - qownnotesapi
  - recommendations
  - scanner
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "0",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.194",
            "subdomain.dyndns.org",
            "192.168.178.183"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "http:\/\/192.168.178.194\/cloud",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "onlyoffice": {
            "DocumentServerInternalUrl --value=\"http:\/\/192.168.178.183\/\"": "",
            "verify_peer_off": true
        },
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
The documents are stored in a Synology DiscStation. I have connected with "sudo mount 192.168.178.188:/volume3/FC_Daten/daten /media/fc_daten"

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
WebDAV
### Client configuration
**Browser:**
Firefox 74.0

**Operating system:**
Windows 10

**Comment by kesselb** [comment]
https://help.nextcloud.com/t/documents-not-being-saved-when-editing-nextcloud-18-local-community-document-server-plugin/71382/15?u=kesselb

**Comment by agentlibre** [comment]
Why is this closed?

**Comment by kesselb** [comment]
Click on the link and figure it out?

**Comment by fthommen** [comment]
Your answer is not very helpful @kesselb. Forcing users to read through lengthy posts to find out why an issue has been closed is not very friendly. At least you could have posted the link to the related github issue (https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/21) or a direct link to your post with the explanation why you have closed the issue (https://help.nextcloud.com/t/documents-not-being-saved-when-editing-nextcloud-18-local-community-document-server-plugin/71382/29)

**Comment by fthommen** [comment]
@kesselb  The closing comment of the Github issue that you are referring to (https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/21#issuecomment-607822941) explicitely refers to the NextCloud team to solve the issue. Now both sides have closed their issues by pointing to the other party :-(.  Please reopen this issue. Thanks

**Comment by kesselb** [comment]
> At least you could ...

A friendly advice: Try to rephrase such sentences as questions. That sounds much nicer.

> `https://help.nextcloud.com/t/documents-not-being-saved-when-editing-nextcloud-18-local-community-document-server-plugin/71382/15?u=kesselb`

`/71382/15` is a reference to a specific comment. 

![image](https://user-images.githubusercontent.com/3902676/81333492-fd7bb280-90a4-11ea-9117-25a88a55913c.png)

That comment to be precise. A link to the right issue on GitHub is included there. Actually you need two clicks to find the right issue. I don't see a problem here. Also the post at help.nextcloud.com includes more helpful information. 

> Please reopen this issue. 

The right repository is https://github.com/nextcloud/documentserver_community and a issue is already filed over there. It's not necessary to open multiple issues for the same problem and it does not speed up things.

**Comment by fthommen** [comment]
For those interested, the mentioned issue is https://github.com/nextcloud/documentserver_community/issues/100
