### ISSUE TITLE
Not displaying user quota in the user administration menu

### ISSUE THREAD

**Issue by cardosocristian** [nextcloud/server#20266]
Issue 1:
When I create a new user and try to set the quota field, I select the desired option, but nothing is displayed in the field.

Issue 2:
After the user is created, the user's total quota is not displayed in the quota field to the right of the user administration menu.
![image](https://user-images.githubusercontent.com/32941615/78195689-b4599280-7456-11ea-806f-239e182fc90e.png)

SO: FreeBSD 12.1
Stable version 18.0.3
PHP 7.3

**Comment by derfladi** [comment]
Same here:
OS: Ubuntu 18.04 (as LXC-Container under Proxmox 6.1.5)
NC 18.0.3
PHP 7.2.24
MariaDB

**Comment by the-n3i** [comment]
I have the same problem, both in NC 18.0.3 and the release candidate of NC 18.0.4.
It appears to be fixed in the NB 19 beta though.

**Comment by szaimen** [comment]
based on the-n3i's comment I am closing this.
