### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by Trakt0r22** [nextcloud/server#20260]
Tried to update my NC 18.0.0 to 18.0.3 and this is what happened. Please help.

> Preparing update
> 
> Set log level to debug
> 
> Turned on maintenance mode
> 
> Repair step: Repair MySQL collation
> 
> Repair info: Change row format for oc_addressbooks ...
> 
> Repair info: Change collation for oc_addressbooks ...
> 
> Repair info: Change row format for oc_authtoken ...
> 
> Repair info: Change collation for oc_authtoken ...
> 
> Repair info: Change row format for oc_calendarobjects ...
> 
> Repair info: Change collation for oc_calendarobjects ...
> 
> Repair info: Change row format for oc_calendars ...
> 
> Repair info: Change collation for oc_calendars ...
> 
> Repair info: Change row format for oc_calendarsubscriptions ...
> 
> Repair info: Change collation for oc_calendarsubscriptions ...
> 
> Repair info: Change row format for oc_dav_shares ...
> 
> Repair info: Change collation for oc_dav_shares ...
> 
> Repair info: Change row format for oc_login_flow_v2 ...
> 
> Repair info: Change collation for oc_login_flow_v2 ...
> 
> Repair info: Change row format for oc_mail_mailboxes ...
> 
> Repair info: Change collation for oc_mail_mailboxes ...
> 
> Repair info: Change row format for oc_migrations ...
> 
> Repair info: Change collation for oc_migrations ...
> 
> Repair info: Change row format for oc_mimetypes ...
> 
> Repair info: Change collation for oc_mimetypes ...
> 
> Repair info: Change row format for oc_systemtag_group ...
> 
> Repair info: Change collation for oc_systemtag_group ...
> 
> Repair info: Change row format for oc_trusted_servers ...
> 
> Repair info: Change collation for oc_trusted_servers ...
> 
> Repair step: Repair SQLite autoincrement
> 
> Repair step: Copy data from accounts table when migrating from ownCloud
> 
> Repair step: Drop account terms table when migrating from ownCloud
> 
> Updating database schema
> 
> Updated database
> 
> Repair step: Fix the namespace in database tables
> 
> Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by Tanfav** [comment]
I have exactly the same issue, but already on 18.0.3, just trying to update TALK.
It brings me back to this "namespace in database tables" issue…
so, it really seems related to TALK (i didn't had any issue updating my 18.0.1 to 18.0.2 then 18.0.3 several weeks ago

**Comment by Trakt0r22** [comment]
> I have exactly the same issue, but already on 18.0.3, just trying to update TALK.
> It brings me back to this "namespace in database tables" issue…
> so, it really seems related to TALK (i didn't had any issue updating my 18.0.1 to 18.0.2 then 18.0.3 several weeks ago

That's so annoying considering I don't even use talk yet xD

**Comment by Trakt0r22** [comment]
Going to try [https://help.nextcloud.com/t/solved-syntax-error-or-access-violation-1071-specified-key-was-too-long-max-key-length-is-767-bytes/34740](this). Seems to be the same issue.
