### ISSUE TITLE
Task app update failure

### ISSUE THREAD

**Issue by Tanfav** [nextcloud/server#20261]
### Steps to reproduce
1. Nextcloud 18.0.3 on Debian
2.Application update "TALK"
3.Launch the update of Talk…

### Expected behaviour
Application update

### Actual behaviour
it brings me back to the server login page with message: application update needed TALK (spreed)
Start the update, then this error message:
Mise à jour vers 18.0.3

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### Server configuration

Debian
Ngnix
mariaSQL
php 7.4
18.0.3
updated since 18.0.1 release

"complete" log:
Préparation de la mise à jour
Réglage du niveau de journalisation à "déboguage"
Mode de maintenance activé
Étape de réparation : Repair MySQL collation
Informations de réparation : All tables already have the correct collation -> nothing to do
Étape de réparation : Repair SQLite autoincrement
Étape de réparation : Copy data from accounts table when migrating from ownCloud
Étape de réparation : Drop account terms table when migrating from ownCloud
Mise à jour du schéma de la base de données
Base de données mise à jour
Étape de réparation : Fix the namespace in database tables
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/16/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by Tanfav** [comment]
Hello, and thanks for your feedback.
In fact, that's weird as utf8mb4 was set months ago… and i dind't had any warning;.. before this app update"broke" the instance.
Anyway, i'll fix it… but that's also unpleasant to see that updating an simple app can put my server unavailable... i'll have to break confiment to go fix it… if i get corona, i'll officially blame Nextcloud ;)
