### ISSUE TITLE
FTP folder reading instead of per file reading in occ file:scan --all

### ISSUE THREAD

**Issue by viisauksena** [nextcloud/server#20277]
hey,

we made many tests lately with ftp remote folders (we have some big ones)
we found out that the update is laggy - which results in seemingly emtpy folders in web frontend.
we found out that file:scan against a very reliable and fast proftpd connection is ultraslow - somehow one file or folder a second. It seems nextcloud is opening a ftp connection for every file it has to check availability and permissions. 

We suggest to do this on a directory listing base - since all the needed / wanted data is given by a directory listing. This should improve ftp scan dramaticly in most cases 
(except you have some thousand folders with 1 file each) - 
we have some 200k files - in 2.5k folders. Theoretically we would only need 1.x percent of the time/resources to scan these.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
