### ISSUE TITLE
Missing 18.0.3 release tag?

### ISSUE THREAD

**Issue by snakyjake1** [nextcloud/server#20280]
On April 2, 2020 I upgraded the server to 18.0.3 stable.  But on GitHub I don't see see a 18.0.3 server release.  For example, there's no https://github.com/nextcloud/server/releases/tag/v18.0.3.

I'm also hoping to find the change log so I can see what has changed or what's new.

![image](https://user-images.githubusercontent.com/8312560/78305226-3d270b80-74f5-11ea-86a2-1319cfb68bcd.png)

Thanks

**Comment by Nils160988** [comment]
18.0.3 is a security update, please use the search function.
Duplicate of https://github.com/nextcloud/server/issues/20119

**Comment by georgehrke** [comment]
As pointed out by @Nils160988, this is a duplicate, so let's close the issue.
