### ISSUE TITLE
Login with a device: device name is default after login

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#20289]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Login to Nextcloud as user
2. Go to Settings -> Personal -> Security
3. Add a Webauthn device and call it Yubi

![Screenshot from 2020-04-03 16-24-17](https://user-images.githubusercontent.com/3902676/78371530-62d11500-75c8-11ea-9a34-724c4b4a0154.png)

4. Logout
5. Login to Nextcloud as user with Yubi
6. Go to Settings -> Personal -> Security

![Screenshot from 2020-04-03 16-25-49](https://user-images.githubusercontent.com/3902676/78371537-65cc0580-75c8-11ea-8ec9-7e9e17b1f70d.png)
### Expected behaviour

I see a Webauthn device called Yubi

### Actual behaviour

I see a Webauthn device called default

### Server configuration

**PHP version:** 7.4
**Nextcloud version:** https://github.com/nextcloud/server/commit/4e8bbc4e341861ad1ddcf872c8e248fadb711861

**Comment by ChristophWurst** [comment]
huh, I think I had this as well but I didn't realize the device was renamed after login

**Comment by jospoortvliet** [comment]
Love the 'how to use github' thing, we should have this in all our templates :dagger:

**Comment by g6094199** [comment]
+1
