### ISSUE TITLE
Calendar notification sent again and again

### ISSUE THREAD

**Issue by madmas** [nextcloud/server#20286]
Hi, sine I've upgraded to NC 18.0.3, notifications from updates to a shared calendar are send again and again every 30 minutes (which aligns withmy cron job setup).

### Steps to reproduce
1. Nextcloud 18.0.3
2. Shared Calandar, somebody the calendar is shared with does a change (add event)
3. EMail notification are sent every time cron.php is run

### Expected behaviour
Notification is sent once.

### Actual behaviour
Notification is sent again and again

### Server configuration

**Operating system:** Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64

**Webserver:** Apache (apache2handler)

**Database:** pgsql PostgreSQL 9.3.16 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4, 64-bit

**PHP version:** 7.2.24-0ubuntu0.18.04.3

**Modules loaded:** Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, imap, intl, json, exif, mysqli, pdo_mysql, pdo_pgsql, pgsql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:**  Upgraded 

**Where did you install Nextcloud from:** 

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - bruteforcesettings: 1.5.0
 - calendar: 2.0.2
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_external: 0.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
</summary>

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "18.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "forcessl": true,
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "127.0.0.1",
                143,
                null,
                null,
                false,
                true
            ]
        }
    ],
    "lost_password_link": "disabled",
    "theme": "",
    "maintenance": false,
    "trusted_domains": [
...
    ],
    "secret": "***REMOVED SENSITIVE VALUE***",
    "share_folder": "\/Shared",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "loglevel": 1,
    "trashbin_retention_obligation": "auto",
    "updater.release.channel": "stable",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** IMAP

### Client configuration
**Browser:** not applicable

**Operating system:** not applicable

**Comment by warnerbryce** [comment]
I confirm that
I had to manually close all calendar alerts i had in the past in the notification Bubble. 
2 years back. 

I can’t update my others instances because of that bug

**Comment by madmas** [comment]
After looking into the code, it look to me like somthing in the [activity app](https://github.com/nextcloud/activity/) goes wrong and sent items are not deleted from the events list.
Will continue to debug this.

**Comment by georgehrke** [comment]
Closing in favour of https://github.com/nextcloud/activity/issues/459

**Comment by erdoukki** [comment]
+1
