### ISSUE TITLE
Share button available via RightClick

### ISSUE THREAD

**Issue by jonmert** [nextcloud/server#20290]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Disable Sharing App
2. Open Context Menu for File
3. Right Click File

### Expected behaviour
There should be no Share button in Context Menu or Right Click Menu.

### Actual behaviour
Right Click Menu has Share Button
Context Menu has no Share button

### Server configuration

**Operating system:**
Centos 8
**Web server:**
Apache
**Database:**
Mariadb
**PHP version:**
7.2 
**Nextcloud version:** (see Nextcloud admin page)
18.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.0
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-18.0.0.zip
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
ERR_CONNECTION_TIMED_OUT

</details>

**List of activated apps:**

<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder


Enabled:
  - accessibility: 1.4.0
  - bruteforcesettings: 1.5.0
  - cloud_federation_api: 1.1.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_rightclick: 0.15.2
  - groupfolders: 6.0.3
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - support: 1.1.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_sql: 4.4.1
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - activity
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - password_policy
  - photos
  - privacy
  - recommendations
  - sharebymail
  - survey_client
  - systemtags
  - text
  - user_ldap
```

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
           "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": ""***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "session_lifetime": 3600,
        "session_keepalive": false,
        "remember_login_cookie_lifetime": 3600,
        "lost_password_link": "disabled",
        "knowledgebaseenabled": false,
        "maintenance": false,
        "theme": "invent",
        "loglevel": 2,
        "default_language": "de_DE",
        "default_locale": "de_DE",
        "skeletondirectory": "",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp"
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** 
YES. SQL via  - user_sql: 4.4.1

### Client configuration
**Browser:** Google Chrome

**Operating system:** Windows 10

**Comment by kesselb** [comment]
This way: https://github.com/nextcloud/files_rightclick/issues/88
