### ISSUE TITLE
Listener in OC\Encryption\Util for excluding additional directories from encryption

### ISSUE THREAD

**Issue by mutec** [nextcloud/server#20297]
It's well known that group folders are not working with encryption and that combination is causing unexcepted situations and broken functionality.
This problem could be "solved" by excluding group folders from the directory which could be encrypted.
In my own installation I used a dirty workaround like this; I added `__groupfolders` to `Util::$excludedPaths` over here:
https://github.com/nextcloud/server/blob/master/lib/private/Encryption/Util.php#L102-L104
for me it's now:
```PHP
$this->excludedPaths[] = 'files_encryption';
$this->excludedPaths[] = '__groupfolders';
$this->excludedPaths[] = 'appdata_' . $config->getSystemValue('instanceid', null);
$this->excludedPaths[] = 'files_external';
```

Since the group folders feature is located in another repository ( https://github.com/nextcloud/groupfolders ) I'd request a possiblity - an listener or something else - for adding additional directories to that property instead of the need to patch that file within the core package if something changed in the other package.

Maybe that's still worth a look for version 19, since it's status is still beta.
Due to the current situation I need that feature for communication with other users but can't disable encryption for the user directories because they contain customer-related data.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
