### ISSUE TITLE
Upgrade from 18.01 to 18.03

### ISSUE THREAD

**Issue by gucu** [nextcloud/server#20295]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. I was running 18.01 and noticed that there was no invite to upgrade in the settings. The server said Version and under that Nextcloud 18.01. I reported this to my server support and they upgraded me to 18.03 to see if this fixed the issue.

### Expected behaviour
A notice saying you are up to date

### Actual behaviour
It says Version 18.03

### Server configuration

I can't find this information. I think it would normally have a link below the Version 18.03

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- EXTRA_FILE
		- nextcloud-18.0.3.zip

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [nextcloud-18.0.3.zip] => Array
                        (
                            [expected] => 
                            [current] => f7ae10f89ca4d1c0da240eefecadcddf15172177c411181a5dd7977b33ac2237805211156dbe229dfc9e71f8da3d1062677b8463f19b4103a757f1fd20af0b73
                        )

                )

        )

)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
No access to command line
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
Yes but I don't know which one
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Webdav
```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Vivaldi
**Operating system:**
Ubuntu 20.04
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>
I am unsure how I find much of this information.

Thanks

Rich

**Comment by dirigit** [comment]
Looks like your technical support downloaded the zip into subdirectory core and there it stays for no reason (=== additional file).

Maybe it's zip with server only. Most probably support should have downloaded packaged 18.0.3 and extract it to root of NC.

Overwriting existing files to perform an update might be error prune because there is chance of old files staying in file system. They have to be deleted by hand than.

Better would be to extract new release to a separate directory beside existing installation first, copy working config.php and .htaccess from root to correct places in this new directory, rename old directory and new directory to name of previous root directory and run update afterwards.

**Comment by gucu** [comment]
Hi
Thanks for the reply. To better explain this I have taken a screenshot of the issue. 
![version nextcloud](https://user-images.githubusercontent.com/8758633/79839523-85c33d80-83ac-11ea-98ea-f4ecffd0c644.png)
This was what it looked like with 18.01 and the reason why it was upgraded by the server managers and not by the web console that I would normally use.
Thanks

**Comment by Nils160988** [comment]
Sorry, I don't really understand how your screenshot now is related to your original issue.
You need to remove the extra file nextcloud-18.0.3.zip to make the file integrity check happy.

**Comment by gucu** [comment]
The original issue had nothing to do with the extra file. The original issue was that at 18.01 I could not see any of the usual comments under the version in settings. In my previous Nextcloud installs it said:
Version:
xxxxxxx
Your version is up to date 
Or
Your version needs updating
When I went from 17.xx to 18.01 I lost those comments. When my server guys put out a call that 18.03 was fine to upgrade I went to this area and found no way of upgrading. I put out a ticket and the server guys updated my nextcloud instance for me but the problem is still there. I understand that you are saying the zip file shouldn't be there but the issue I am experiencing was there in 18.01 and had no relevance for that file because it only arrived in the upgrade to 18.03. I will ask them to remove it though.
Hopefully that explains my issue better. Thanks

**Comment by Nils160988** [comment]
I have no idea who your "server guys" are but it is probably a good idea to reach out to them with your issue if they administrate your instance.
The version check works fine for me.

**Comment by gucu** [comment]
Server guys = Managed server and these folks do the maintenance on it.
I reached out and they have deleted the file but I am still showing no indication of up to date or needs updating.
They have said they believe it to be a NextCloud issue because they don't have the problem elsewhere.
Thanks
