### ISSUE TITLE
File sharing between users not available in 18.0.3

### ISSUE THREAD

**Issue by lje** [nextcloud/server#20302]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. click folder in web UI and press share button
2. Sharing should be available but is not

### Expected behaviour
Sharing link available

### Actual behaviour
Sharing link not visible
Trying to share folder in windows desktop client crashes the client

Sharing is enabled
![Sharing-enabled](https://user-images.githubusercontent.com/357743/78422310-ab3b1200-765e-11ea-8a33-b2d8b31ba4b0.png)

But the icon is missing
![Browser](https://user-images.githubusercontent.com/357743/78422313-afffc600-765e-11ea-88e0-1ecdc12645f0.png)

### Server configuration

**Operating system:**
Linux CentOS 7, kernel 3.10.0

**Web server:**
Apache 2.4.39

**Database:**
MariaDB 10.3.19

**PHP version:**
7.4 or 7.3 (tried both)

**Nextcloud version:** (see Nextcloud admin page)
18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-18.0.3.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.1.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

Disabled:
  - admin_audit
  - comments
  - encryption
  - files_external
  - files_videoplayer
  - firstrunwizard
  - survey_client
  - systemtags
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/19908

**Comment by lje** [comment]
You're riht, it works in Chrone with uBo, but doesn't in FF with uBo (same filter lists).
The Windows client still crashed when trying to share, but I guess I should create a client issue for that.

**Comment by skjnldsv** [comment]
> The Windows client still crashes when trying to share, but I guess I should create a client issue for that.

yes



> You're right, it works in Chrone with uBo, but doesn't in FF with uBo (same filter lists).

Check another extension, it might be adblockplus, or other custom filters.
All works fine here without custom rules and default uBo install
