### ISSUE TITLE
External user can reset password

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#2030]
Hey guys,

I just noticed external users (authenticating against IMAP in my case) are not able to reset their invalid / lost password. They just get 

> Wrong password.

 without 

> Reset it?

I think it was great to be able to just set up an URL that performs the external password reset instead of nextCloud. So the user gets its email with the reset-link, enters its password and uuid, password and the existing reset token are sent to the specified external server. This server checks if the token is valid and resets the pasword.

So the only cost for you was to allow the user to reset its password to be able to enter a new one like a normal internal user.

If this wasn't interesting, please tell me where I can set "canResetPassword" to true for external users as well, because I didn't find the right place in the code.

Thank you!

**Comment by MariusBluem** [comment]
`/**
 * If your user backend does not allow to reset the password (e.g. when it's a
 * read-only user backend like LDAP), you can specify a custom link, where the
 * user is redirected to, when clicking the "reset password" link after a failed
 * login-attempt.
 */
'lost_password_link' => 'https://example.org/link/to/password/reset',`

You can set it in your `config.php`: https://github.com/nextcloud/server/blob/master/config/config.sample.php#L237

**Comment by alve89** [comment]
Yes, great, didn't know that!  :smile:  :smile: Thank you!

**Comment by alve89** [comment]
BUT: Where can I set that called URL should contain some parameters (username, may be a token like it's set when resetting via email)?

**Comment by MariusBluem** [comment]
I think this is not possible 😁

**Comment by nickvergessen** [comment]
Yeah, as @MariusBluem already said, that is not possible.
Basically your user management system should provide the full set of things to reset a users password and then you can use the linked feature.

Other then that, nothing more we can do.

**Comment by alve89** [comment]
I think an enhancement was to use this link only for external users because Nextcloud already has a method to reset passwords of users directly within Nextcloud via email.
What do you think?

**Comment by nickvergessen** [comment]
Well in general production instances should have users only in 1 user backend (apart from the first admin account). Otherwise you can run into a series of problems.

**Comment by TommiHil** [comment]
I had the same error on my site [https://tawjihi-jo.com/](https://tawjihi-jo.com/)

but it was solved as you described above: we specified the URL of our manager and now our users can reset their accesses - thank you!
