### ISSUE TITLE
Login flow v2 not working with app password

### ISSUE THREAD

**Issue by ruedigerkupper** [nextcloud/server#20301]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. obtain an app-password on your Nextcloud's settings/security page
2. log out from Nextcloud in your browser
3. use the Linux desktop client to connect to your Nextcloud
4. observe it opens the login page in you browser (login flow v2)
5. type your username and the app-password you just created
6. observe that it is not accepted
7. observe, though, that you can log in with your standard password

### Expected behaviour
Login flow v2 should accept the app password.

### Actual behaviour
It doesn't. It only accepts your standard password.

Note that according to 
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html
the whole point of the login flow is that clients should _not_ use the users's standard credentials, but app passwords!
 
### Server configuration

**Operating system:** Linux / Ubuntu 19.10

**Web server:** Apache (from Nextcloud snap)

**Database:** mysql (from Nextcloud snap)

**PHP version:** 7.3.16 (from Nextcloud snap)

**Nextcloud version:** 17.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:** updated (snap)

**Where did you install Nextcloud from:** snap

### Client configuration
**Browser:** Chromium (snap)

**Operating system:** Linux / Ubuntu 19.10

**Comment by kesselb** [comment]
Using a app password to create a new app password does not work. Client will create a app password for you hence login with username and password is required.

**Comment by ruedigerkupper** [comment]
Oh, really? Sorry, that wasn't transparent to me. Could the login page mention that a new app password will be created and used?
I generally want as few apps as possible using my standard password and was concerned.
