### ISSUE TITLE
Update SQL Failure Talk 8.0.6 to 8.0.7 - NC 18.03

### ISSUE THREAD

**Issue by bristolca** [nextcloud/server#20304]
Updating App Talk 8.0.6 to 8.0.7 on NC 18.03 Instance generated the following Error:

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-CA-0' for key 'oc_talk_participants.tp_ident'

Detailed Log:
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Fix the namespace in database tables
Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3-CA-0' for key 'oc_talk_participants.tp_ident'

Can anybody please give me a hint to solve this Error? 
Thanks in advance
bristol

**Comment by alfelge** [comment]
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Reparaturschritt: Fix the namespace in database tables

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE INDEX tp_uid ON oc_talk_participants (user_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

i get this error, any idea?

**Comment by ericschdt** [comment]
I had the same error. I removed spreed via occ and could successfully update Nextcloud.

Then I tried to install spreed again via occ but the error 
```
PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version8000Date20200331144101, because the name is already in use in /var/www/(...)/nextcloud/apps/spreed/lib/Migration/Version8000Date20200331144101.php on line 54
```
occured.
Renaming this file and trying to install it again via occ finally worked.

**Comment by nickvergessen** [comment]
The actual fix to the problem is removing duplicated entries manually prior to the update. This should not have happened at all and if you experienced it, it means you couldn't enter the room anyway

https://github.com/nextcloud/spreed/issues/3232#issuecomment-607696462

**Comment by praptoumache** [comment]
worked for me!
but i had to change the table names
`CREATE TABLE `talk_participants_temp` LIKE `talk_participants`;
CREATE UNIQUE INDEX `tp_ident` ON `talk_participants_temp` (`room_id`, `user_id`, `session_id`);
INSERT IGNORE INTO `talk_participants_temp` SELECT * FROM `talk_participants`;
DROP TABLE `talk_participants`;
ALTER TABLE `talk_participants_temp` RENAME TO `talk_participants`;`
