### ISSUE TITLE
Main login form has "autocomplete" set to "on" by default - this is insecure

### ISSUE THREAD

**Issue by sotel** [nextcloud/server#20307]
![Bildschirmfoto_2020-04-04_21-51-49](https://user-images.githubusercontent.com/107782/78460867-dce6c400-76c4-11ea-90d8-9711ff19aa98.png)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install or update a Nextcloud web installation
2. Log off
3. Try to log in again with your username and your password

### Actual behaviour
Giving the field for the "username" will active a dropdown with your username

### Expected behaviour
There should not be any information about the last user(s)!

### Server configuration

**Operating system:**
Linux 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

**Web server:**
Apache

**Database:**
Mariadb

**PHP version:**
v7.3

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
Nexcloud updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
Example Domain
This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.

More information...
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.5.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_fulltextsearch_tesseract: 1.4.1
  - files_linkeditor: 1.0.13
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - fulltextsearch: 1.4.1
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - metadata: 0.11.1
  - nextbackup: 19.12.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 6.0.25
  - ocsms: 2.1.7
  - password_policy: 1.8.0
  - passwords: 2020.3.1
  - photos: 1.0.0
  - polls: 1.3.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.5
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - dropit
  - encryption
  - federation
  - files_external
  - firstrunwizard
  - printer
  - privacy
  - user_ldap
  - workflow_script
</details>

**Comment by Dragon988** [comment]
While this should be fixed out of principle it's only insecure if you are running in a browser without privacy mode on. And if you're vulnerable and at a public computer you should be using privacy mode.

Even if you forget it still doesn't provide your password or two factor authentication that's needed to login.

**Comment by skjnldsv** [comment]
Yeah, also,  browsers enforce autocompletion even if not set nowadays. 
https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion#The_autocomplete_attribute_and_login_fields


> Modern browsers implement integrated password management: when the user enters a username and password for a site, the browser offers to remember it for the user. When the user visits the site again, the browser autofills the login fields with the stored values.
> 
> Additionally, the browser enables the user to choose a master password that the browser will use to encrypt stored login details.
> 
> Even without a master password, in-browser password management is generally seen as a net gain for security. Since users do not have to remember passwords that the browser stores for them, they are able to choose stronger passwords than they would otherwise.
> 
> For this reason, many modern browsers do not support autocomplete="off" for login fields:
> 
> If a site sets autocomplete="off" for a <form>, and the form includes username and password input fields, then the browser still offers to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.
> If a site sets autocomplete="off" for username and password <input> fields, then the browser still offers to remember this login, and if the user agrees, the browser will autofill those fields the next time the user visits the page.
> This is the behavior in Firefox (since version 38), Google Chrome (since 34), and Internet Explorer (since version 11).

**Comment by devi69** [comment]
It seems that the autocomplete feature of the main login form can be disabled by setting `'login_form_autocomplete' => false,` in config.php. I'll mention this so that others who see this ticket don't get the wrong idea that can't turn off autocomplete.
https://github.com/nextcloud/server/blob/stable18/config/config.sample.php#L1776
