### ISSUE TITLE
http proxy support should allow no_proxy settings

### ISSUE THREAD

**Issue by luizluca** [nextcloud/server#20300]
**Is your feature request related to a problem? Please describe.**
Currently, nextcloud will use proxy for every request it does, even for local domain

**Describe the solution you'd like**
It should allow to set no_proxy

**Describe alternatives you've considered**
Editing code

**Additional context**

**Comment by kesselb** [comment]
Closing as duplicate of https://github.com/nextcloud/server/issues/12402.

https://github.com/nextcloud/server/pull/17684 for more details.
