### ISSUE TITLE
Can't open search in mobile safari

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#20305]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open Nextcloud with Mobile Safari on iOS 13.4
2. Try to open the search input field by clicking / tapping on it

### Expected behaviour
The search input should appear.

### Actual behaviour
The search input is visible as long as you hold the search icon, but it immediately closes again after you stop tapping. If you tap twice fast enough (double click) the input stays visible since it is focused.

### Server configuration

**Nextcloud version:** Happens on both 18.0.3 and latest master

### Client configuration
**Browser:** Mobile safari

**Operating system:** iOS 13.4 on iPhone 8

**Comment by skjnldsv** [comment]
Fixed nc20
