### ISSUE TITLE
DNSSEC partially broken for nextcloud.com

### ISSUE THREAD

**Issue by DaleBCooper** [nextcloud/server#20306]
Don't know where else to report this.

Two of the five name severs of nextcloud.com suffer from expired rrsigs, namely:
ns.inwx.de
ns2.inwx.de
The signatures expired on last Thursday at 12am utc:
[...]
nextcloud.com.          3600    IN      RRSIG   A 8 2 3600 20200402000000 20200312000000 8703 ...
[...]

See:  https://dnsviz.net/d/nextcloud.com/XohrIQ/dnssec/

You should report this to your infrastructure team asap.

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure

**Comment by rullzer** [comment]
Seems to be at the DNS provider somewhere. We reached out
