### ISSUE TITLE
www.nextcloud.com

### ISSUE THREAD

**Issue by I-am-stefan** [nextcloud/server#20318]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. make a ping at nextcloud.com works
2. make a ping at www.nextcloud.com does not work
3. The system told me that the actualization service cannot be reached.

### Expected behaviour
www.nextcloud.com should be reachable or the service will move to another URL

### Actual behaviour
make a ping at www.nextcloud.com does not work

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
18.03

### Logs

GuzzleHttp\Exception\ConnectException: cURL error 6: Could not resolve host: www.nextcloud.com (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

**Comment by DaleBCooper** [comment]
This is related to  #20306

**Comment by kesselb** [comment]
cc @nextcloud/infrastructure
