### ISSUE TITLE
Add checksum in oc_filecache table for sync comparision 

### ISSUE THREAD

**Issue by dassio** [nextcloud/server#20324]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
when detach and attach again an external storage, all the files's etag  will change.
if you are using the desktop client, it will download all the files again.
usually  the egress bandwidth is really expensive, it will cause  a lot of cost for user with the same file both on server and local.

**Describe the solution you'd like**
add checksum to the `oc_filecache`  if we can get them :
- for local file, this can be calculated on the server,
- for external file like S3 , we can get from metdata (https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/) 

so the desktop client can rely on checksum instead of etag(which is generated randomly).

**Additional context**
>S3 Storage price : $0.023 per GB
> Egress traffic price:  $0.09 per GB

traffic is more valuable than storage 

desktop client sync comparison method: https://docs.nextcloud.com/desktop/2.6/architecture.html#synchronization-by-time-versus-etag

**Comment by kesselb** [comment]
You heard about the search?

**Comment by dassio** [comment]
i searched `checksum` on the issue list, do you know  how many result comes out ? i have to click page by page and reach page 4  to find the relevant issue. 

for other benefits, here is the relevant  issue :  #11138

**Comment by kesselb** [comment]
It's also possible to combine multiple terms. For example `checksum sync` to reduce the number of results.
