### ISSUE TITLE
link-Shared folder with images shows only file list

### ISSUE THREAD

**Issue by MparkG** [nextcloud/server#20325]
link-shared folder with images shows only the file list

... is this behaviour normal?
I would have expected a preview or built in image viewer as the bare minimum instead of a file list.

When I click on the file it just downloads.

It appears i cant share any photos without forcing people to download the images one by one or the whole folder at once?

When I set the "hide download" button in the control panel of the share, then the file can not even be accessed in any way through the share, it wont start downloading then, neither be viewed.
!!?!?!?!?!?!?!?!

Thanks

**Comment by kesselb** [comment]
For questions: https://help.nextcloud.com

**Comment by MparkG** [comment]
i take it this is done on purpose?
rubbish.

**Comment by kesselb** [comment]
Please use https://help.nextcloud.com to ask questions. If you want to report a bug use the template. The problem might be fixed by 18.0.4 by some updates to the viewer.

**Comment by MparkG** [comment]
Thanks a lot thats all i wanted to hear.
I get it you know that its a "problem" and are fixing it,
yet i imagine many people asking for it.
I'm sorry to be one of them.

I dont have an account nor am i familliar with the nextcloud forum, so that is a lot of effort i.e. time for me to get into for this.

Sorry to disturb, kind regards,
Park

Am 5. April 2020 23:47:28 MESZ schrieb kesselb <notifications@github.com>:
>Please use https://help.nextcloud.com to ask questions. If you want to
>report a bug use the template. The problem might be fixed by 18.0.4 by
>some updates to the viewer. 
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/20325#issuecomment-609489827

-- 
Max vom Telefon
