### ISSUE TITLE
Use a different entries for user id and username

### ISSUE THREAD

**Issue by Deuteu** [nextcloud/server#20323]
**Is your feature request related to a problem? Please describe.**
At the moment given that the username is the unique user id. The username can't be changed without breaking other references in other tables (oc_preferences, oc_group_user, oc_credentials, oc_twofactor_totp_secrets, ...).

**Describe the solution you'd like**
It could be useful to have a internal user id (which could be automatically generated) and a username used for authentication or other user interaction.
For a step by step process ans a retro compatible solution, a new column could be introduced as username and by default it could be filled with the user id and/or just fallback to user_id when username is blank.

**Describe alternatives you've considered**
An alternative would be to have kind a script to be able to edit the users table and all other tables using this information but every app should also have some similar behavior that the core package could call and I don't know if this is possible.

**Additional context**
https://github.com/nextcloud/guests/issues/333

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by blizzz** [comment]
the "username" is the userid and remains immutable. Login names can differ and the abstraction is flexible (e.g. with LDAP users defaulting to their entries UUID). Also the local database allows login with email address (but yes, it's loginame is just case insensitive userid). The userid is considered internal.

**Comment by szaimen** [comment]
Thanks for the answer, @blizz! So do I understand correctly that the internal userID for the local user backend isn't going to be changed to an abstract one?

**Comment by Deuteu** [comment]
> the "username" is the userid and remains immutable
I get that the internal user ID must be immutable.

@blizzz  I don't see why this is preventing from having a user facing "username" (or call it whatever you want "loginname", "pseudo", ... ) which you could use as login and could be mutable.

**Comment by Deuteu** [comment]
@blizzz @szaimen Friendly ping on this.
Why couldn't there be two user identifier, one immutable used for technical reference and the other one used as human-friendly identifier which potentially could be editable ?
