### ISSUE TITLE
[18.0.3 & 19 Beta 2] - new errors - Move/copy window does not appear

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#20322]
Edit: New errors from firefox on 19.0.0 beta2.

` is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 6 globals.js:61:15
TypeError: "t is undefined"
    jQuery 3
        _build
        init
        octemplate
    filepicker dialogs.js:268
    jQuery 4
    _getFilePickerTemplate dialogs.js:1036
    jQuery 4
 data: undefined octemplate.js:90:11
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. globals.js:61:15
TypeError: u.$filePicker.data(...) is undefined
dialogs.js:527:24
    filepicker dialogs.js:527
    jQuery 4
    _getFilePickerTemplate dialogs.js:1036
    jQuery 4
TypeError: e.$showGridView.get(...) is undefined
dialogs.js:1009:22
    _getGridSettings dialogs.js:1009
    jQuery 4
TypeError: d is undefined3 dialogs.js:1205:10
    onload dialogs.js:1205`

It turns out this error also happens on 18.0.3 so new bug report!

I have tested bypassing HAProxy and disabling all cache. I have tested by using LAN only instead of WAN. I have tested by fully reinstalling 18.0.3 to rule out any issues on my end.

I have tried all major browsers including chrome, firefox and edge.

Speaking of edge it can't login at all to my nextcloud installation which is a different bug report.

Edit: Not that I'm saying it can't be my setup but I've gone through the effort of ruling most stuff out and the rest of nextcloud functions with no issue on 18.0.3.

**19 Beta 1 errors:**
```
{"reqId":"ZbAS3UIuQ2XVLenVRa3K","level":0,"time":"2020-04-05T01:41:36+00:00","remoteAddr":"51241","user":"paradox","app":"serverDI","method":"PROPFIND","url":"/remote.php/dav/files/paradox/","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"zgG6aBfwgJORBCQhw7Z7","level":0,"time":"2020-04-05T01:41:36+00:00","remoteAddr":"512412","user":"paradox","app":"serverDI","method":"GET","url":"/core/preview.png?file=%2F%2Feducation+key.docx&x=100&y=100","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"zgG6aBfwgJORBCQhw7Z7","level":1,"time":"2020-04-05T01:41:36+00:00","remoteAddr":"5124","user":"paradox","app":"no app in context","method":"GET","url":"/core/preview.png?file=%2F%2Feducation+key.docx&x=100&y=100","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"aWCVC70aYDznCY1qRJ6G","level":0,"time":"2020-04-05T01:41:36+00:00","remoteAddr":"5124","user":"paradox","app":"serverDI","method":"GET","url":"/core/preview.png?file=%2F%2FReadme.md&x=100&y=100","message":"The requested alias \"PreviewManager\" is depreacted. Please request \"OCP\\IPreview\" directly. This alias will be removed in a future Nextcloud version.","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
{"reqId":"aWCVC70aYDznCY1qRJ6G","level":1,"time":"2020-04-05T01:41:36+00:00","remoteAddr":"51249","user":"paradox","app":"no app in context","method":"GET","url":"/core/preview.png?file=%2F%2FReadme.md&x=100&y=100","message":"Deprecated event type for OCP\\IPreview:PreviewRequested: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:74.0) Gecko/20100101 Firefox/74.0","version":"19.0.0.2"}
```

**18.0.3 errors:**

```
{"reqId":"dq4hXcYgkVlxoUClVjp7","level":3,"time":"2020-04-05T12:43:18+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"PHP","method":"GET","url":"/apps/files/","message":"Trying to access array offset on value of type null at /var/www/html/3rdparty/aws/aws-sdk-php/src/RetryMiddleware.php#144","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
{"reqId":"OV3IkCB7crUx4ilAo7An","level":0,"time":"2020-04-05T12:43:24+00:00","remoteAddr":"10.0.1.163","user":"paradox","app":"no app in context","method":"GET","url":"/apps/files/","message":"Deprecated event type for OCA\\Files::loadAdditionalScripts: Symfony\\Component\\EventDispatcher\\GenericEvent","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36","version":"18.0.3.0"}
```

**Configuration:**
NC 19 Beta1 & 18.0.3
Primary S3 storage | path style false
Debian 10
PHP 7.4-FPM
HAProxy + Nginx
Postgresql
Upgraded from 18.0.3 (obviously testing environment)
No encryption
External SFTP storage enabled & assigned to user account

**Steps to reproduce**
Try moving any file or folder. Window does not show up.

**Expected behavior**
Window shows up.

**Nextcloud config**

```
<?php
$CONFIG = array (
  'objectstore_multibucket' =>
stuff here
    ),
  ),
  'trusted_domains' =>
  array (
    0 => 'asfsagse',
  ),
  'trusted_proxies' =>
  array (
    0 => '192.122228.4415.1',
  ),
  'filelocking.enabled' => false,
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 0,
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'jpeg_quality' => '75',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'asgasge',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.sendgrid.net',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'apikey',
  'mail_smtppassword' => 'SsagasgasgavRC-oasgasgsaF_5asgagsg',
  'mail_smtpauthtype' => 'LOGIN',
  'quota_include_external_storage' => true,
  'trashbin_retention_obligation' => '7, 14',
  'enabledPreviewProviders' =>
    2 => 'OC\\Preview\\JPEG',
    3 => 'OC\\Preview\\GIF',
    4 => 'OC\\Preview\\HEIC',
    5 => 'OC\\Preview\\BMP',
    6 => 'OC\\Preview\\XBitmap',
    7 => 'OC\\Preview\\MP3',
    8 => 'OC\\Preview\\TXT',
    9 => 'OC\\Preview\\MarkDown',
    10 => 'OC\\Preview\\Movie',
    11 => 'OC\\Preview\\TIFF',
    12 => 'OC\\Preview\\Photoshop',
  ),
  'twofactor_enforced' => 'true',
  'twofactor_enforced_groups' =>
  array (
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
  ),
  'has_rebuilt_cache' => true,
  'app_install_overwrite' =>
  array (
    0 => 'passman',
    1 => 'files_photospheres',
    2 => 'keeweb',
    3 => 'checksum',
    4 => 'camerarawpreviews',
    5 => 'onlyoffice',
    6 => 'documentserver_community',
  ),
  'instanceid' => 'asg',
  'passwordsalt' => 'asgsagsag',
  'secret' => 'gagasgsagas',
  'datadirectory' => '/var/www/242424241e/data',
  'dbtype' => 'pgsql',
  'version' => '18.0.3.0',
  'overwrite.cli.url' => 'https://dsagfsagme',
  'dbname' => 'drive',
  'dbhost' => '10.0.22221.33333',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '12141241241e',
  'dbpassword' => 'GEsagsagsagas',
  'installed' => true,
);
```
**Nginx config:**

More or less identical to the one in the nextcloud guide.

**Comment by Dragon988** [comment]
You can still move files by dragging them into other folders so this is specific to the popup window.

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by Dragon988** [comment]
> 
> 
> Thank you for reporting this issue 👍
> 
> I will need your browser console log to investigate this issue. Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.
> How to access your browser console (Click to expand)
> # Chrome
> 
>     * Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
> 
>     * Alternative method:
>       
>       1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
>       2. Click the “console” tab.
> 
> 
> # Safari
> 
>     * Press CMD + ALT + I to open the Web Inspector.
> 
>     * See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)
> 
> 
> # IE9
> 
>     1. Press F12 to open the developer tools.
> 
>     2. Click the “console” tab.
> 
> 
> # Firefox
> 
>     * Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
> 
>     * or, if Firebug is installed (recommended):
>       
>       1. Press F12 to open Firebug.
>       2. Click on the “console” tab.
> 
> 
> # Opera
> 
>     1. Press CTRL + SHIFT + I to open Dragonfly.
> 
>     2. Click on the “console” tab.

![chrome_fw24rYlg59](https://user-images.githubusercontent.com/7935624/78503056-25c86800-7719-11ea-8361-7065c162b7de.png)

Let me know if you need something more.

**Comment by Dragon988** [comment]
Just to be clear, I have reinstalled this twice and also upgraded to 19 beta1 so that makes three different installations with this issue.

Best guess is the file doesn't get uploaded to S3 as primary.

Alternatively, the slow 100KB/s speeds to nextclouds server are causing timeouts during installation and preventing the install from fully finishing. I have to manually add in apps such as the document server because of the slow speeds causing timeouts while installing over the nextcloud app page.

Not that my server is slow, just that nextcloud has poor peering or something.

Just theories!

**Comment by Dragon988** [comment]
Have reinstalled the entire OS and started from scratch, same issue. This may be a S3 specific bug.

**Comment by Dragon988** [comment]
Updated OP with new errors on 19 beta2 with firefox debug console.

**Comment by Dragon988** [comment]
This ended up being some weird configuration issue on nginx, so my apologies.
