### ISSUE TITLE
Browsing folders doesn't work in Firefox

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#2033]
After merging #2018 you can't browse folders anymore in Firefox - in Chrome everything works.

@juliushaertl Could you have a look?

Thanks @Mannshoch for noticing this.

**Comment by MorrisJobke** [comment]
cc @nickvergessen @rullzer To let you know about this issue.

**Comment by MorrisJobke** [comment]
@ChristophWurst Mind taking a look at this?

**Comment by rullzer** [comment]
Mmmm very strange this happens to me in private mode but not in my default session (hard refresh and firefox restart and all).

**Comment by rullzer** [comment]
Seems to be https://github.com/nextcloud/server/blob/master/core/js/js.js#L1844

selector is not defined.

**Comment by juliushaertl** [comment]
:see_no_evil: I will not have time to have a look today, so if anyone else wants, feel free to do so. Otherwise I'll check this out tomorrow.

**Comment by ChristophWurst** [comment]
> Seems to be https://github.com/nextcloud/server/blob/master/core/js/js.js#L1844
> 
> selector is not defined.

Removing that parameter fixes the bug for me. I'm not sure what consequences that has though. @juliushaertl do you know why that variable was added?

On a site note: https://github.com/nextcloud/server/blob/master/core/js/js.js#L1847 looks weird. My IDE even called it a "Weird assignment" 🙈
