### ISSUE TITLE
theming apps issue: thumbnail icon not shown : /apps/theming/icon?v=200 return 0B

### ISSUE THREAD

**Issue by Zarawee** [nextcloud/server#20348]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.enable theming apps 
2. change a color and upload new log
3. share a public link in whatsapp or any social media
### Expected behaviour
Tell us what should happen
the thumbnail icon should be appeared when share a link  on whatsapp

### Actual behaviour
Tell us what happens instead
when sharing a link, there is no preview of thumbnail icon
### Server configuration

**Operating system:**
FreeBSD (FreeNAS)
**Web server:**
nginx version: nginx/1.16.1
**Database:**
mysql  Ver 14.14 Distrib 5.7.29
**PHP version:**
PHP 7.3.15
**Nextcloud version:** (see Nextcloud admin page)
nextcloud 18.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
from FreeBSD ports
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/usr/local/www/nextcloud/apps',
      'url' => '/apps',
      'writable' => true,
    ),
    1 => 
    array (
      'path' => '/usr/local/www/nextcloud/apps-pkg',
      'url' => '/apps-pkg',
      'writable' => true,
    ),
  ),
  'logfile' => '/var/log/nextcloud/nextcloud.log',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'passwordsalt' => 'nCTc3QZoWctdd6KVlxYGuetOEylEZ4',
  'secret' => 'h9dllRrZfPXA4W54M52JE/XjFKsKAIVsHIyqAOR6X0dH99Dz',
  'trusted_domains' => 
  array (
    0 => 'localhost',
    1 => '192.168.178.54',
    2 => 'nc.****.duckdns.org',
    3 => 'nc.****.duckdns.org',
  ),
  'mysql.utf8mb4' => true,
  'overwriteprotocol' => 'https',
  'datadirectory' => '/usr/local/www/nextcloud/data',
  'dbtype' => 'mysql',
  'version' => '18.0.3.0',
  'overwrite.cli.url' => 'http://192.168.178.54',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_ncadmin',
  'dbpassword' => '******',
  'installed' => true,
  'instanceid' => 'oclkvnzajoqc',
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'simpleSignUpLink.shown' => false,
  'updater.release.channel' => 'stable',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_sendmailmode' => 'smtp',
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
no

### Client configuration
**Browser:**
firefox, chrome, IE, Edge
**Operating system:**
windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```

Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log

domain,      cause , type,   transferred,   size
https://nc.****.duckdns.org/apps/theming/icon?v=356,    img, png,   883B,    0B

response header
{"Response Headers (883 B)":{"headers":[{"name":"Cache-Control","value":"max-age=86400, must-revalidate"},{"name":"Connection","value":"keep-alive"},{"name":"Content-Disposition","value":"inline; filename=\"touchIcon-core\""},{"name":"Content-Length","value":"0"},{"name":"Content-Security-Policy","value":"default-src 'none';base-uri 'none';manifest-src 'self'"},{"name":"Content-Type","value":"image/png"},{"name":"Date","value":"Tue, 07 Apr 2020 12:59:52 GMT"},{"name":"ETag","value":"\"d13a2ca0a25afb2627c6dbe43b66c01c\""},{"name":"Expires","value":"Wed, 08 Apr 2020 12:59:52 +0000"},{"name":"Feature-Policy","value":"autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'"},{"name":"Last-Modified","value":"Tue, 07 Apr 2020 09:11:57 +0000"},{"name":"Pragma","value":"public"},{"name":"Referrer-Policy","value":"no-referrer"},{"name":"Server","value":"nginx/1.16.1"},{"name":"Strict-Transport-Security","value":"max-age=15768000; includeSubDomains; preload;"},{"name":"X-Content-Type-Options","value":"nosniff"},{"name":"X-Download-Options","value":"noopen"},{"name":"X-Frame-Options","value":"SAMEORIGIN"},{"name":"X-Permitted-Cross-Domain-Policies","value":"none"},{"name":"X-Robots-Tag","value":"none"},{"name":"X-XSS-Protection","value":"1; mode=block"}]}}
c) ...
```
</details>

**Comment by szaimen** [comment]
I suppose this has to do with thumbnail caching of whatsapp. Since I also cannot reproduce any issue with theming thumbnails, I am closing this issue. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
