### ISSUE TITLE
Update of spreed app failed, leaving broken install - NC 18

### ISSUE THREAD

**Issue by IIerpos** [nextcloud/server#20340]
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Repair step: Fix the namespace in database tables

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by vandam2k7** [comment]
Solution
`$ sudo mysql -u root -p
MariaDB [(none)]> use nextcloud;
MariaDB [nextcloud]> set global innodb_large_prefix=on;
MariaDB [nextcloud]> set global innodb_file_format=Barracuda;
$ sudo -u www-data php occ maintenance:repair`

**Comment by kesselb** [comment]
Please use the search for: `Specified key was too long; max key length is 767 bytes`

**Comment by IIerpos** [comment]
Thanks, vandam2k7! That solved it.
