### ISSUE TITLE
Folder in talk room missing the next day

### ISSUE THREAD

**Issue by mokkin** [nextcloud/server#20345]
## Steps to reproduce
1. create a talk room
2. add a folder on the right projects sidebar
3. check if it is missing the next day
![image](https://user-images.githubusercontent.com/2938748/78663888-38869c80-78d3-11ea-82ff-4b13ca4452b9.png)

### Expected behaviour
The attached folder should be there until the folder or the room gets removed.

### Actual behaviour
The folder disappears the next day (or maybe after a couple of hours)

## Browser
latest Firefox
Ubuntu 18.04

## Talk app

**Talk app version:** 
8.0.7
**Custom TURN server configured:** 
yes

**Custom STUN server configured:** 
no

## Server configuration

**Operating system**: 
shared host on Debian 9

**Web server:** Apache/Nginx
both via shared host
**Database:**
mysql  Ver 15.1 Distrib 10.0.38-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
**PHP version:**
7.3.15
**Nextcloud Version:** (see admin page)
18.0.3
**List of activated apps:**

<details>
```
Enabled:  - accessibility: 1.4.0  - activity: 2.11.0  - admin_audit: 1.8.0  - bruteforcesettings: 1.6.0  - calendar: 2.0.2  - cloud_federation_api: 1.1.0  - comments: 1.8.0  - contacts: 3.2.0  - dav: 1.14.0  - documentserver_community: 0.1.5  - federatedfilesharing: 1.8.0  - federation: 1.8.0  - files: 1.13.1  - files_external: 1.9.0  - files_markdown: 2.2.0  - files_pdfviewer: 1.7.0  - files_rightclick: 0.15.2  - files_sharing: 1.10.1  - files_trashbin: 1.8.0  - files_versions: 1.11.0  - files_videoplayer: 1.7.0  - firstrunwizard: 2.7.0  - groupfolders: 6.0.4  - logreader: 2.3.0  - lookup_server_connector: 1.6.0  - nextcloud_announcements: 1.7.0  - notes: 3.2.0  - notifications: 2.6.0  - oauth2: 1.6.0  - occweb: 0.0.7  - onlyoffice: 4.1.4  - password_policy: 1.8.0  - passwords: 2020.4.0  - photos: 1.0.0  - previewgenerator: 2.3.0  - privacy: 1.2.0  - provisioning_api: 1.8.0  - qownnotesapi: 20.1.0  - recommendations: 0.6.0  - serverinfo: 1.8.0  - settings: 1.0.0  - sharebymail: 1.8.0  - spreed: 8.0.7  - support: 1.1.0  - survey_client: 1.6.0  - systemtags: 1.8.0  - tasks: 0.12.1  - text: 2.0.0  - theming: 1.9.0  - twofactor_backupcodes: 1.7.0  - updatenotification: 1.8.0  - viewer: 1.2.0  - workflowengine: 2.0.0Disabled:  - deck  - encryption  - files_readmemd  - mail  - maps  - phonetrack  - user_ldap
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
