### ISSUE TITLE
Updating to NextCloud 18.0.3

### ISSUE THREAD

**Issue by nobiryu** [nextcloud/server#20356]
Every time I have ran the web based updater for NextCloud to 18.0.3 from 18.0.1 I the update keeps failing with the information below.  I have checked my mysql data base with the command:

sudo mysqlcheck -u root -p --databases nextcloud

they came back with no errors.  I am new with sql data bases, but with a google search I have not been able to find a solution for the error comment of:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Anymore information needed please let me know.

NextCloud updater output:

Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: Change row format for oc_addressbooks ...
Repair info: Change collation for oc_addressbooks ...
Repair info: Change row format for oc_authtoken ...
Repair info: Change collation for oc_authtoken ...
Repair info: Change row format for oc_calendarobjects ...
Repair info: Change collation for oc_calendarobjects ...
Repair info: Change row format for oc_calendars ...
Repair info: Change collation for oc_calendars ...
Repair info: Change row format for oc_calendarsubscriptions ...
Repair info: Change collation for oc_calendarsubscriptions ...
Repair info: Change row format for oc_dav_shares ...
Repair info: Change collation for oc_dav_shares ...
Repair info: Change row format for oc_login_flow_v2 ...
Repair info: Change collation for oc_login_flow_v2 ...
Repair info: Change row format for oc_mail_mailboxes ...
Repair info: Change collation for oc_mail_mailboxes ...
Repair info: Change row format for oc_migrations ...
Repair info: Change collation for oc_migrations ...
Repair info: Change row format for oc_mimetypes ...
Repair info: Change collation for oc_mimetypes ...
Repair info: Change row format for oc_systemtag_group ...
Repair info: Change collation for oc_systemtag_group ...
Repair info: Change row format for oc_trusted_servers ...
Repair info: Change collation for oc_trusted_servers ...
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Checking for update of app "accessibility" in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app "activity" in appstore
Checked for update of app "activity" in appstore
Checking for update of app "bruteforcesettings" in appstore
Update app "bruteforcesettings" from appstore
Checked for update of app "bruteforcesettings" in appstore
Checking for update of app "calendar" in appstore
Checked for update of app "calendar" in appstore
Checking for update of app "cloud_federation_api" in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app "comments" in appstore
Checked for update of app "comments" in appstore
Checking for update of app "contacts" in appstore
Checked for update of app "contacts" in appstore
Checking for update of app "dav" in appstore
Checked for update of app "dav" in appstore
Checking for update of app "federatedfilesharing" in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app "federation" in appstore
Checked for update of app "federation" in appstore
Checking for update of app "files" in appstore
Checked for update of app "files" in appstore
Checking for update of app "files_pdfviewer" in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app "files_rightclick" in appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app "files_sharing" in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app "files_trashbin" in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app "files_versions" in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app "files_videoplayer" in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app "firstrunwizard" in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app "logreader" in appstore
Checked for update of app "logreader" in appstore
Checking for update of app "lookup_server_connector" in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app "mail" in appstore
Checked for update of app "mail" in appstore
Checking for update of app "nextcloud_announcements" in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app "notifications" in appstore
Checked for update of app "notifications" in appstore
Checking for update of app "oauth2" in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app "onlyoffice" in appstore
Checked for update of app "onlyoffice" in appstore
Checking for update of app "password_policy" in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app "photos" in appstore
Checked for update of app "photos" in appstore
Checking for update of app "privacy" in appstore
Checked for update of app "privacy" in appstore
Checking for update of app "provisioning_api" in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app "quota_warning" in appstore
Checked for update of app "quota_warning" in appstore
Checking for update of app "recommendations" in appstore
Checked for update of app "recommendations" in appstore
Checking for update of app "serverinfo" in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app "settings" in appstore
Checked for update of app "settings" in appstore
Checking for update of app "sharebymail" in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app "spreed" in appstore
Update app "spreed" from appstore
Repair step: Fix the namespace in database tables
Checking for update of app "support" in appstore
Checked for update of app "support" in appstore
Checking for update of app "survey_client" in appstore
Checked for update of app "survey_client" in appstore
Checking for update of app "systemtags" in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app "terms_of_service" in appstore
Checked for update of app "terms_of_service" in appstore
Checking for update of app "text" in appstore
Checked for update of app "text" in appstore
Checking for update of app "theming" in appstore
Checked for update of app "theming" in appstore
Checking for update of app "twofactor_backupcodes" in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app "updatenotification" in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app "viewer" in appstore
Checked for update of app "viewer" in appstore
Checking for update of app "workflow_pdf_converter" in appstore
Checked for update of app "workflow_pdf_converter" in appstore
Checking for update of app "workflowengine" in appstore
Checked for update of app "workflowengine" in appstore
Repair step: Repair MySQL collation
Repair info: Change row format for oc_addressbooks ...
Repair info: Change collation for oc_addressbooks ...
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_addressbooks` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment]
Use the search and look for Specified key was too long; max key length is 767 bytes
