### ISSUE TITLE
Issues on NextCloud 18.0.3

### ISSUE THREAD

**Issue by vELiNiO** [nextcloud/server#20358]
Hello,

I have two issues running NextCloud 18.0.3 (the latest stable version). First of all I would like to say that I'm running it on a virtual machine with Ubuntu 18.04, php 7.2, apache2. Secondly, I have the issue that when I play a video logged in the cloud, everything runs alright, but when I share a .mov file, it doesn't play in Chrome, Edge or Internet Explorer (only on Firefox and Safari). Can this be fixed somehow from the server? Then, I have the issue with the file thumbnails - I downloaded an app called Preview Generator, generated all the previews with the known command /occ preview:generate all (or something like that), the previews are being generated, but then I see no thumbnails on files except the photos (I mostly need them for my video files). Is there a way to achieve this?

Thanks!

**Comment by j-ed** [comment]
Due to the fact that this is the bug tracker for the development and not the [Nextcloud help forum](https://help.nextcloud.com/). I would recommend to use the search function off the help forum first, before you post a new request, to reduce the number of similar requests 😉

**Comment by vELiNiO** [comment]
I searched about it, but didn't find a clear solution, that's why I'm posting that question..

**Comment by Nils160988** [comment]
Even if you did, you are kindly asked to fill out the issue template and to create separate issues. Otherwise, it is hard or even impossible to reproduce your issue.
