### ISSUE TITLE
Deleted files aka trashbin do not work

### ISSUE THREAD

**Issue by hmielimo** [nextcloud/server#20357]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. setup server (error free)
2. install nextcloud 18.0.3 (error free and Deleted files aka trashbin works)
3. upgrade nextcloud from version 17.0.2.1 to 18.0.3 (one error and Deleted files aka trashbin works)
Version 1
4. install Default encryption module app (error free and Deleted files aka trashbin works)
5. install End-to-End Encryption app     (error free and Deleted files aka trashbin works)
6. occ encryption:encrypt-all            (error free and Deleted files aka trashbin do not work)
Version 2
4. install End-to-End Encryption app     (error free and Deleted files aka trashbin works)
5. install Default encryption module app (error free and Deleted files aka trashbin works)
6. occ encryption:encrypt-all            (error free and Deleted files aka trashbin do not work and no log entries)

### Expected behaviour
Deleted files aka Deleted files show up in the trashbin and are restoreable works

### Actual behaviour
Deleted files aka Deleted files show up in the trashbin and are restoreable do not work

### Server configuration
**Operating system:** Ubuntu 18.04 LTS
**Web server:**  Apache/2.4.29 
**Database:** PostgreSQL 11.7
**PHP version:** 7.3.16
**Nextcloud version:** Nextcloud 18.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install
**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-18.0.3.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>
Login as admin user into your Nextcloud and access 
https://development.kommunikation-im-zentrum.de/nextcloud/index.php/settings/integrity/failed 
No errors have been found.
</details>

**List of activated apps:**

<details>
<summary>first App list</summary>

sudo -u www-data php "${PoNCoPATH}"/occ app:list

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - encryption: 2.6.0
  - end_to_end_encryption: 1.4.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - files_external
  - user_ldap

</details>

**Nextcloud configuration:**

<details>
<summary>Config report</summary>

sudo -u www-data php "${PoNCoPATH}"/occ config:list system

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "development.kommunikation-im-zentrum.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "https:\/\/development.kommunikation-im-zentrum.de\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0
        },
        "default_language": "de",
        "default_locale": "de_DE",
        "trashbin_retention_obligation": "30, 31",
        "loglevel": 3,
        "logfile": "\/nextcloud-data\/nextcloud.log",
        "log_rotate_size": 104857600,
        "logtimezone": "Europe\/Berlin",
        "maintenance": false,
        "data-fingerprint": "7be78cde7f454593d085dc8078daf6fe"
    }
}

</details>

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** firefox 75.0 32bit

**Operating system:** windows 10

#### history
<details>
<summary>history</summary>
no history
</details>

#### post upgrade details
<details>
<summary>post upgrade details</summary>
(1) (Wed Apr  8 08:08:43 UTC 2020) ===> /nextcloud-data/nextcloud.log
=================================================================================================================
List nextcloud log_:  -rw-r----- 1 www-data www-data 89K Apr  8 08:08 /nextcloud-data/nextcloud.log
Number of lines____:  314
Debug___:  95
Info____:  218
Warning_:  0
Error___:  1
Fatal___:  0
=================================================================================================================
List all Errors
240:{"reqId":"1TAsNV6fBBtThxrbw8mb","level":3,"time":"2020-04-08T10:08:23+02:00","remoteAddr":"","user":"--","app":"core","method":"","url":"--","message":{"Exception":"Exception","Message":"Could not download app gallery","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/legacy/app.php","line":399,"function":"downloadApp","class":"OC\\Installer","type":"->","args":["gallery"]},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":459,"function":"enable","class":"OC_App","type":"->","args":["gallery"]},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":263,"function":"upgradeAppStoreApps","class":"OC\\Updater","type":"->","args":[["gallery"],true]},{"file":"/var/www/nextcloud/lib/private/Updater.php","line":131,"function":"doUpgrade","class":"OC\\Updater","type":"->","args":["18.0.3.0","17.0.2.1"]},{"file":"/var/www/nextcloud/core/Command/Upgrade.php","line":257,"function":"upgrade","class":"OC\\Updater","type":"->","args":[]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Command/Command.php","line":255,"function":"execute","class":"OC\\Core\\Command\\Upgrade","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":915,"function":"run","class":"Symfony\\Component\\Console\\Command\\Command","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":272,"function":"doRunCommand","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"installer":{"__class__":"OC\\Installer"},"__class__":"OC\\Core\\Command\\Upgrade"},{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/console/Application.php","line":148,"function":"doRun","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/lib/private/Console/Application.php","line":214,"function":"run","class":"Symfony\\Component\\Console\\Application","type":"->","args":[{"__class__":"Symfony\\Component\\Console\\Input\\ArgvInput"},{"__class__":"Symfony\\Component\\Console\\Output\\ConsoleOutput"}]},{"file":"/var/www/nextcloud/console.php","line":99,"function":"run","class":"OC\\Console\\Application","type":"->","args":[]},{"file":"/var/www/nextcloud/occ","line":11,"args":["/var/www/nextcloud/console.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Installer.php","Line":375,"CustomMessage":"--"},"userAgent":"--","version":"17.0.2.1"}
=================================================================================================================

</details>

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
