### ISSUE TITLE
No sharee matching by email when sharebymail not installed autocompletion is disabled

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#20359]
### Steps to reproduce
1. Disable Settings > Admin > Sharing > _Allow username autocompletion in share dialog_
2. Disable app _Share by mail_
3. Create a user _Bobby_ with email address _bob@hopp.com_
4. Go to a file's sharing dialog
5. Enter _bob@hopp.com_ in the sharee input field

### Expected behaviour
_Bobby_ gets suggested as sharee

### Actual behaviour
_No elements found_

### Additional info
- Entering _Bobby_ does correctly suggest _Bobby_ as sharee.
- This only happens when _Share by mail_ is disabled.

### Server configuration

tested with NC 18.0.3

**Comment by skjnldsv** [comment]
Potentially related https://github.com/nextcloud/server/pull/16035

**Comment by skjnldsv** [comment]
Fixed now
