### ISSUE TITLE
User administration page doesn't save changes when clicking on checkmark

### ISSUE THREAD

**Issue by revendoc** [nextcloud/server#20352]
### Steps to reproduce
1. Login to NextCloud
2. Click on Users from the top right admin menu
3. Click on the edit pencil on the right side of any user listed
4. Edit the user's display name
5. Click on the done checkmark to save the entry

### Expected behaviour
The users display name should be updated to the value you entered in step 4 above

### Actual behaviour
The users display name reverts back to it's original value

### Server configuration

**Operating system:**
Debian Buster 10.2

**Web server:**
Apache 2.4.38

**Database:**
MariaDB 10.3.22

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from Nextcloud 17

**Where did you install Nextcloud from:**
Installed from Nextcloud.com downloads

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 

No errors have been found.
```

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.2
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.4
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.4
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.7
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_versions
  - recommendations
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "0": "nextcloudservername",
            "1": "localhost",
            "3": "mydomain.com"
        },
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwritehost": "mydomain.com",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "https:\/\/mydomain.com\/",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "maintenance": false,
        "mysql.utf8mb4": true,
        "theme": "",
        "loglevel": 2,
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
storage encryption is not being used

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

### Client configuration
**Browser:**
Mozilla Firefox 68.6.1esr (on Raspbian)
Chromium Version 78.0.3904.108 (on Raspbian)
Mozilla Firefox version 24.1 (iOS)
Safari (iOS)

**Operating system:**
Raspbian Buster 
iOS 13.4

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No entries written to apache error.log since daily rollover
[Tue Apr 07 00:00:01.583603 2020] [mpm_prefork:notice] [pid 684] AH00163: Apache/2.4.38 (Debian) configured -- resuming normal operations
[Tue Apr 07 00:00:01.583630 2020] [core:notice] [pid 684] AH00094: Command line: '/usr/sbin/apache2'

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No entries found in data/nextcloud.log during this time
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
The javascript console log:
[Violation] Forced reflow while executing JavaScript took 31ms
```
</details>

**Comment by acs-ferreira** [comment]
At your step 5, hit ENTER.

**Comment by revendoc** [comment]
> At your step 5, hit ENTER just after name change and before click on the check-mark.

Yes thank you. This is a valid workaround but I still believe this issue as documented above is a bug.

**Comment by szaimen** [comment]
You either need to press [ENTER] after changing the display name or click on the arrow button:
![image](https://user-images.githubusercontent.com/42591237/120189222-5a4d8c00-c217-11eb-920b-005358ac9d5e.png)
But cc @nextcloud/designers if we need to do something about this.
