### ISSUE TITLE
Some useful features requested

### ISSUE THREAD

**Issue by potato1992** [nextcloud/server#20353]
Hello,
I just migrate from KodExplorer [https://github.com/kalcaddle/KodExplorer](url) to Nextcloud, I have been using KodExplorer for more than one year, but their newest version will encrypt data folder, which is not I can accept (I use syncthing and samba at the same time). After a few days with Nextcloud, I think there are many things that Nextcloud could do better.

1. Build in flow upload support, it is implemented by the plugin [https://github.com/e-alfred/flowupload](url), but in KodExplorer, it's a built in function, just drag a bunch of folders into the web page, a queue of uploads will show up clearly indicating every process. (I can retry some failed individual file)

2. Multi-media player support, which has already been discussed [https://github.com/nextcloud/files_videoplayer/issues/51](url) . However, I do not think it is not possible to enable MKV RMVB AVI files to play, as KodExplorer already supports them all without any issue.

3. I think one great feature of KodExplorer is the windows explorer like web page, i.e., I can drag folders and files inside the web page, or even use some keyboard shortcuts, like ctrl+c(copy), ctrl+x(cut), ctrl+v(paste), ctrl+shift+n(new folder). And I can do a box selection inside the web page to select all target files/folders  I want, instead of click the check box one by one.

4. KodExplorer does really great in built in text editor, it support so many language(C,C++,Java, php, XML and so on), and I think the Markdown editor is even better in KodExplorer. The spilt view for the Markdown plugin looks not as good as that in KodExplorer, at least, the font size in the left is much smaller than in the right, and it's not adjustable. 

5. The grid view of folders and files, I think the icons are too big. I know it's just a matter of taste, but I think it's better to have some options. The CSS method refered in [https://github.com/nextcloud/server/issues/11902](url) does not solve it, as when icons becomes smaller, more icons should show up, instead of just being more sparse.

Overall I am happy to use Nextcloud and I really appreciate your great jobs. Those are all I feel that could make Nextcloud better.

**Comment by Spartachetto** [comment]
You'd better open an issue for every feature request. Even better if each one is in the appropriate repository

**Comment by szaimen** [comment]
@potato1992 please do as Spartachetto suggested. This way we can reliably track each request. Thanks!
