### ISSUE TITLE
Integrate tags with Tagspaces

### ISSUE THREAD

**Issue by xordspar0** [nextcloud/server#20350]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I use Tagspaces to tag and organize my files. Nextcloud also has a tag system. It would be nice if I could search for tags in Nextcloud and it was aware of the tags applied by Tagspaces.

**Describe alternatives you've considered**
I'm not sure if this is better implemented directly in the Files app or in a 3rd party app.

**Additional context**
Tagspaces tags are simple to parse. They're part of the filename, like this:

```
note[20200407 list ideas].md
```

The docs are here: https://docs.tagspaces.org/tagging.html#file-tagging-based-on-filenames

Tagspaces can also write tags to a sidecar json file. This could be added later or as a stretch goal.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
