### ISSUE TITLE
Selecting of items has a different look depending on the kind of item

### ISSUE THREAD

**Issue by Clementine46** [nextcloud/server#20369]
When adding a file to a project and linking it to an item (board, file or conversation) the selection indicators are different for each type of items.

File > share > Add to a project > Link to a board : light blue frame
<img width="1440" alt="Capture d’écran 2020-04-08 à 20 35 27" src="https://user-images.githubusercontent.com/50834537/78827075-d87f1b80-79e2-11ea-9bcf-e1d8fe625239.png">

Link to a file : grey background
<img width="1440" alt="Capture d’écran 2020-04-08 à 20 36 06" src="https://user-images.githubusercontent.com/50834537/78827274-1da34d80-79e3-11ea-83ce-50bc43d11b19.png">

Link to a conversation : light blue line on the left side
<img width="1440" alt="Capture d’écran 2020-04-08 à 20 36 17" src="https://user-images.githubusercontent.com/50834537/78827291-272cb580-79e3-11ea-9a3d-1f246a5e57bb.png">

The last one is not necessarily linked to the Projects feature but the selection indicator when choosing participants to create a conversation is also different : check marks
<img width="1440" alt="Capture d’écran 2020-04-08 à 20 36 40" src="https://user-images.githubusercontent.com/50834537/78827782-f7ca7880-79e3-11ea-85b2-49879b7bf182.png">

The selection indicators are very different from each other and I believe the design would be better if those indicators were cohesive. I also think the indicator for a conversation is not really visible, the most effective indicator seems to be the one for the files.

**Comment by jancborchardt** [comment]
Really great analysis @Clementine46!

> I also think the indicator for a conversation is not really visible, the most effective indicator seems to be the one for the files.

The indicator in conversations depends on the theming color, which seems to be quite light on your instance. However, there we normally automatically fall back to a grey with enough contrast, which should happen in this case too – cc @ma12-co 

-----------------

@Clementine46 we also have the 2 feedback states for hover/focus (light grey) and active/selected (light primary/theming color), as you can also see in the Talk navigation.

We could use either the light grey or the light primary color for this selection design as well – which do you think would be better? (Also e.g. when you select items in the file list with multiselect.)
![hover feedback](https://user-images.githubusercontent.com/925062/78830567-77f2dd00-79e8-11ea-9e43-d4846e8a3604.png)

**Comment by ma12-co** [comment]
Cool that you brought this up @Clementine46 :)

Yep, we should add a fallback there @jancborchardt, but as a general pattern for multi-selections I would mimic what we do for the navigation:

- var(--color-hover) when hovering elements;
- var(--color-primary-light) for selected elements;

**Comment by Clementine46** [comment]
I agree with @ma12-co, the theming color should be used for the selection design. Since this color is already used for selected elements, it will be more consistent that way :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
