### ISSUE TITLE
Lang=ru some word overlap others

### ISSUE THREAD

**Issue by DevDorrejo** [nextcloud/server#20371]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open NextCloud
2. Change to Russian Language
3. Hover the mouse over the Icon of the top menu

### Expected behaviour
When mouse hover a menu this one have to push the others to the label not hover those and be a little more easy to read.

### Actual behaviour
Tell us what happens instead
Hover mouse on a menu overlap the label of the other.

### Server configuration

**Operating system:** openSUSe Leap 15.1

**Web server:** Apache Server

**Database:** mariaDB

**PHP version:** 7.2.5

**Nextcloud version:**18.0.3 (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**Yes

**Where did you install Nextcloud from:**source

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - audioplayer: 2.9.0
  - audioplayer_editor: 0.2.0
  - audioplayer_sonos: 1.1.0
  - calendar: 2.0.2
  - circles: 0.18.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - data_request: 1.5.0
  - dav: 1.14.0
  - deck: 0.8.2
  - encryption: 2.6.0
  - end_to_end_encryption: 1.4.0
  - event_update_notification: 1.0.1
  - external: 3.5.0
  - extract: 1.2.3
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_downloadactivity: 1.7.0
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_retention: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trackdownloads: 1.7.0
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.5
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.4
  - music: 0.13.2
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - passwords: 2020.4.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - registration: 0.4.7
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - social: 0.2.101
  - socialsharing_email: 2.0.0
  - spreed: 8.0.7
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_usage_report: 1.2.0
  - viewer: 1.2.0
  - workflow_pdf_converter: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - drop_account
  - files_mindmap
  - nextcloud_announcements
  - terms_of_service
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "cloud.astian.org",
            "office.astian.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "https:\/\/cloud.astian.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "end_to_end_encryption",
            "admin_notifications",
            "drop_account",
            "uploaddetails",
            "social"
        ],
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "log_type": "file",
        "loglevel": "3",
        "logdateformat": "F d, Y H:i:s",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "theme": "",
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** FireFox

**Operating system:**ArchLinux

### Logs

1- ![image](https://user-images.githubusercontent.com/7697566/78837466-25062f00-79c2-11ea-9f7d-393fe8caddd6.png)

2- ![Screenshot (23)](https://user-images.githubusercontent.com/7697566/78837590-65fe4380-79c2-11ea-9641-3fbbd7a47480.png)

</details>

**Comment by skjnldsv** [comment]
Hi,

Yes, it is like that for all languages.
@jancborchardt there was a background on the text before, was that removed when you added the gradient?

**Comment by jancborchardt** [comment]
> Hi,
> 
> Yes, it is like that for all languages.
> @jancborchardt there was a background on the text before, was that removed when you added the gradient?

Yes, unfortunately it didnt work with the gradient because then the box was visible. :/

Is it possible to instead do it by reducing the width of the app labels next to it?

**Comment by skjnldsv** [comment]
No idea, technically it's possible, but I think the animation is done via css, and not sure you can via css

**Comment by DevDorrejo** [comment]
but is possible to do a simple hover?, when the mouse is over the menu increase the padding?

**Comment by skjnldsv** [comment]
> but is possible to do a simple hover?, when the mouse is over the menu increase the padding?

No because the text background have been removed, so extending the padding won't change, it's still transparent

**Comment by DevDorrejo** [comment]
ok

**Comment by PVince81** [comment]
still happening in Nextcloud 22.2.0

<img width="117" alt="image" src="https://user-images.githubusercontent.com/277525/141337795-d4ea9f95-787b-4df0-83e7-0509145529be.png">

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
