### ISSUE TITLE
Cannot login onto nextcloud: update failed

### ISSUE THREAD

**Issue by tjakober** [nextcloud/server#20389]
I am required to install an update for the talk plugin. After trying this it failed. Since then I cannot login to nextcloud. I am always required to update but it fails.

Here the detailed description:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Detaillierte Protokollmeldungen 
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

Reparaturschritt: Fix the namespace in database tables

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE UNIQUE INDEX tp_ident ON oc_talk_participants (room_id, user_id, session_id)': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment]
Have you heard about the search function?

**Comment by tjakober** [comment]
About what I should search about? In the error message it says: "Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community." I did this. 
If you know the solution it would be helpful if you give me a hint. Thanks in advance.

**Comment by kesselb** [comment]
`Specified key was too long; max key length is 767 bytes`

**Comment by tjakober** [comment]
Many thanks, this helped a lot.

Best regards

Thomas Jakober


Am Do., 9. Apr. 2020 um 17:48 Uhr schrieb kesselb <notifications@github.com
