### ISSUE TITLE
References to owncloud in file set

### ISSUE THREAD

**Issue by PeterEdens** [nextcloud/server#2039]
Hi,
I found some owncloud files still in the nextcloud file set:

/usr/lib/nextcloud/www/resources/codesigning/owncloud.crt
/usr/lib/nextcloud/www/apps/gallery/js/vendor/owncloud

### Steps to reproduce
1. install nextcloud
2. go to /usr/lib/nextcloud/www/resources/codesigning
3. owncloud.crt is listed

### Expected behaviour
owncloud should not be listed in the file set

### Actual behaviour
owncloud files are found at /usr/lib/nextcloud/www/apps/gallery/js/vendor/owncloud and /usr/lib/nextcloud/www/resources/codesigning/owncloud.crt

### Server configuration
Ubuntu

**Web server:**
nginx

**Database:**
mysql

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
10

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Comment by LukasReschke** [comment]
This is expected behaviour and can be ignored for now. It's just internal naming.
