### ISSUE TITLE
Display file from other directory when it has been moved

### ISSUE THREAD

**Issue by azul** [nextcloud/server#20394]
With #20185 one can now link directly to a file in a directory and the default action for that file will be triggered. This was mostly introduced to make ctrl-click and middle mouse button clicks do the right thing.

However these links can also be used in other places.
Right now if the file that the link points to has been moved from the folder it will trigger a download of the zipped folder content - probably not what we want.

@jancborchardt what would the desired behavior be when:
* I create `MyFile.md`.
* I copy the link to `MyFile.md` in the folder (that is used to open it in another tab)
* I move `MyFile.md` to another place
* I click on the link.

I see a number of options:
1. open the same file in the new folder (we can tell where it is by the file id)
2. display a message that the file has been moved (maybe including the new place)
3. only display the folder

I guess 2. would be the right thing to do. But maybe i am missing something.

_Originally posted by @azul in https://github.com/nextcloud/server/pull/20185#issuecomment-611429523_

**Comment by jancborchardt** [comment]
I would say best and most streamlined is option 1:

> open the same file in the new folder (we can tell where it is by the file id)

We could still show a notification "File moved, showing in new location" if we feel that is necessary at all. But for now I don't think it is.

**Comment by azul** [comment]
Ok... updated the issue description accordingly.

**Comment by azul** [comment]
This becomes even more relevant with easier link creation to files coming in nextcloud/text#879.

Not sure when i will have time to look into it... but it's on my list.

**Comment by szaimen** [comment]
I suppose this is still valid?
