### ISSUE TITLE
please delete

### ISSUE THREAD

**Issue by argv1** [nextcloud/server#20397]
redundant

**Comment by kesselb** [comment]
That looks like a question obfuscated as feature request. For question please visit https://help.nextcloud.com. 

1. Updater downloads a new nextcloud version, backups the old one, extract the new one, move some files around and cleanups the process. 
2. After the new version is in place the upgrade routine changes the database and regenerates some files.

That all takes a while. If you have low limits (memory or script running times) that might timeout. Increase the limits or use the cli updater. Sure there are ways to workaround such limitations but why? Hosting packages with enough resources are affordable. 

Nextcloud is open source and is accepting contributions. Feel free to submit a patch to improve the update routine.
