### ISSUE TITLE
[19.0.0] Beta2 - Cronjob failure text warning

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#20392]

**Comment by kesselb** [comment]
Mind to add some more information?

**Comment by Dragon988** [comment]
> 
> 
> Mind to add some more information?

I thought it was something else but it didn't create the .ocdata file in my custom data directory. It had the proper permissions and creating a blank file fixed it. Can't exactly delete a bug report once its been created.

**Comment by kesselb** [comment]
> Can't exactly delete a bug report once its been created.

Yes but you can close it.
