### ISSUE TITLE
The size of icons and fonts didn't change after update to v.18

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#20398]
After update of the instance from 17.0.3 to 18.0 and later the size of icons and fonts didn't change, though it was expected that they have to be larger.

![image](https://user-images.githubusercontent.com/5199030/78933711-683fcb00-7ab2-11ea-8072-1aedb658a51b.png)

Compare with 18.0.3

![image](https://user-images.githubusercontent.com/5199030/78933806-8c031100-7ab2-11ea-9aac-b94fc8ee3ce9.png)

**Comment by kesselb** [comment]
Why do you expect the icons to be larger? If your instance looks like https://try.nextcloud.com everything is all right.

**Comment by ostasevych** [comment]
> Why do you expect the icons to be larger? If your instance looks like https://try.nextcloud.com everything is all right.

It doesn't, my icons and font size are less than in demo and of the same size as in nc17 and earlier. As I remember, starting from nc18 the UI elements should be bigger upon the request of users.

**Comment by kesselb** [comment]
Without the issue template there is not much we can do. You probably need to update your custom theme if you have one.

**Comment by ostasevych** [comment]
> Without the issue template there is not much we can do. You probably need to update your custom theme if you have one.

Thanks for hint, however the only what I have is own logo which I uploaded 5 versions ago and that's all. So, what to update and how?

**Comment by kesselb** [comment]
cc @skjnldsv 🤔

**Comment by skjnldsv** [comment]
Can you share a link share with us maybe?
So we can have a look at your nextcloud?

Also, the icons did not change with 18, only the font size

**Comment by ostasevych** [comment]
> Can you share a link share with us maybe?
> So we can have a look at your nextcloud?
> 
> Also, the icons did not change with 18, only the font size

I will try to do that in a temporal basis. Whom to send the link for testing?

**Comment by skjnldsv** [comment]
skjnldsv@protonmail.com

**Comment by ostasevych** [comment]
> [skjnldsv@protonmail.com](mailto:skjnldsv@protonmail.com)

Thank you! I will not bother you: after last update everything seems to be fine....
