### ISSUE TITLE
Error: Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by mokkin** [nextcloud/server#20400]
### Steps to reproduce
1. fresh install on shared host
2. open logs (see below)
3. a lot of warnings (see title) are appearing

### Expected behaviour
no errors

### Actual behaviour
a lot of warnings (see title) are appearing

### Server configuration

**Operating system:**
Shared Host with Debian9
**Web server:**
Apache/Nginx
**Database:**
MariaDB
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
19 beta2
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases/nextcloud-19.0.0beta2.zip

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - issuetemplate: 0.6.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - occweb: 0.0.7
  - password_policy: 1.9.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.0
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.3",
        "overwrite.cli.url": "https:\/\/cloud.example.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "htaccess.RewriteBase": "\/",
        "app_install_overwrite": [
            "occweb",
            "issuetemplate"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
 no

**Are you using an external user-backend, if yes which one:**
no

### Client configuration
**Browser:**
Firefox
**Operating system:**
shared hosting on Debian 9

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```[PHP] Error: Trying to access array offset on value of type null at /var/www/vhosts/hosting123456.abcde.netcup.net/httpdocs/cloud.example.de/3rdparty/scssphp/scssphp/src/Compiler.php#6189

GET /settings/user
from 79.232.xxx.yyy by demo at 2020-04-09T22:13:31+00:00
```
</details>

**Comment by kesselb** [comment]
Thanks :+1: 

The exact error message is missing. Also there are already two other reports: https://github.com/nextcloud/server/issues/18996 and https://github.com/nextcloud/server/issues/18996. If you have the error at a different location please open a new issue.
