### ISSUE TITLE
Some files have not passed the integrity check.

### ISSUE THREAD

**Issue by cieska** [nextcloud/server#20409]
### Steps to reproduce
I have no idea how to reproduce.  But I have such error for a long time since maybe version 15xx.  Some versions didn't have this. I think 17.0.3? 

### Expected behaviour
No error messages. 

### Actual behaviour

```
Technical information

The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
- spreed
	- FILE_MISSING
		- js/vendor/backbone.marionette/ISSUE_TEMPLATE.md
		- js/vendor/backbone.marionette/PULL_REQUEST_TEMPLATE.md
		- l10n/.gitkeep

Raw output
Array
(
    [spreed] => Array
        (
            [FILE_MISSING] => Array
                (
                    [js/vendor/backbone.marionette/ISSUE_TEMPLATE.md] => Array
                        (
                            [expected] => d911ec09106892007cef8f86e6c0013ab872c1e371f4c379dadea0b3a7dffb5ff38cafd0e7223a753e43f64f0b5ff46a6459ffa27aaaaa13f09998c2fb12634f
                            [current] => 
                        )

                    [js/vendor/backbone.marionette/PULL_REQUEST_TEMPLATE.md] => Array
                        (
                            [expected] => 64bdb44d529f2476089a9fb0441ba0e8dfdb6cf1f8055ac70d654f46e2b435dc7f2d8f1a7dbb3b679c1f994d66c3b455235693bcbe6181593cb40043b9ad1eff
                            [current] => 
                        )

                    [l10n/.gitkeep] => Array
                        (
                            [expected] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                            [current] => 
                        )

                )

        )

)

```

## Server configuration detail

**Operating system:** Linux 4.15.0-91-generic #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.29

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** I think I have this instalation since version 11 or 12

**Where did you install Nextcloud from:** from scratch. 

<details><summary>Signing status</summary>

Array
(
    [spreed] => Array
        (
            [FILE_MISSING] => Array
                (
                    [js/vendor/backbone.marionette/ISSUE_TEMPLATE.md] => Array
                        (
                            [expected] => d911ec09106892007cef8f86e6c0013ab872c1e371f4c379dadea0b3a7dffb5ff38cafd0e7223a753e43f64f0b5ff46a6459ffa27aaaaa13f09998c2fb12634f
                            [current] => 
                        )

                    [js/vendor/backbone.marionette/PULL_REQUEST_TEMPLATE.md] => Array
                        (
                            [expected] => 64bdb44d529f2476089a9fb0441ba0e8dfdb6cf1f8055ac70d654f46e2b435dc7f2d8f1a7dbb3b679c1f994d66c3b455235693bcbe6181593cb40043b9ad1eff
                            [current] => 
                        )

                    [l10n/.gitkeep] => Array
                        (
                            [expected] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                            [current] => 
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.2.0
 - cookbook: 0.6.3
 - dav: 1.14.0
 - deck: 0.8.2
 - event_update_notification: 1.0.1
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_fulltextsearch: 1.4.2
 - files_mindmap: 0.0.20
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - fulltextsearch: 1.4.1
 - groupfolders: 6.0.5
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - news: 14.1.3
 - nextcloud_announcements: 1.7.0
 - notes: 3.2.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocr: 6.0.29
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.12.1
 - telephoneprovider: 1.0.3
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - bookmarks
 - encryption
 - federation
 - files_external
 - fulltextsearch_elasticsearch
 - spreed
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.xxxxx.com",
        "nx.are.lab"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/nextcloud.xxxxx.com",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "18.0.3.0",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "updater.release.channel": "stable",
    "theme": "",
    "loglevel": 2,
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "app_install_overwrite": [
        "calendar"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0

**Operating system:** Kubuntu 18.0.4

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
I would try to reinstall the talk / spread app.

cc @nextcloud/talk

**Comment by nickvergessen** [comment]
When you are on Nextcloud 18 with Talk 8.0.5 this error should be gone.
