### ISSUE TITLE
Update from v17.0.5 to 18.0.3 failed

### ISSUE THREAD

**Issue by chobbess** [nextcloud/server#20424]
Using WebUpdater which failed with message:

Check for write permissions
The following places can not be written to:

    /var/www/nextcloud/updater/../cron.php
    /var/www/nextcloud/updater/../version.php
    /var/www/nextcloud/updater/../console.php
    /var/www/nextcloud/updater/../public.php
    /var/www/nextcloud/updater/../robots.txt
    /var/www/nextcloud/updater/../status.php
    /var/www/nextcloud/updater/../.htaccess
    /var/www/nextcloud/updater/../COPYING
    /var/www/nextcloud/updater/../occ
    /var/www/nextcloud/updater/../remote.php
    /var/www/nextcloud/updater/../index.php
    /var/www/nextcloud/updater/../index.html
    /var/www/nextcloud/updater/../AUTHORS
    /var/www/nextcloud/updater/../.user.ini

**Comment by Nils160988** [comment]
Did you check for write permissions? How are the permissions on your Nextcloud directory? Have you changed them manually somewhen?

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
