### ISSUE TITLE
Creating shares for files/folders not possible from one domain when in trusted_domain config

### ISSUE THREAD

**Issue by michaelof** [nextcloud/server#20423]
(asked about this bug already here: https://help.nextcloud.com/t/creating-shares-for-files-folders-not-possible-from-one-domain-when-in-trusted-domain-config/74572, no answer)

### Steps to reproduce
1. use nextcloud with at least two trusted_domains
e.g.
$CONFIG = array (
  ...
  'trusted_domains' =>
  array (
    0 => 'example.com',
    1 => 'beispiel.de',
  ),
...

2. try to share files/folders with domain 0: WORKS
3. try to share files/folders with domain 1: DOES NOT WORK

("sorting" of trusted domains has no effect. Tried, but the "newer" trusted_domain e.g. "beispiel.de" always has the issue, independent of sort order)

### Expected behaviour
Sharing should be possible in context of all trusted_domains. Esp. because nextcloud sends invitation emails with context of domain. 

### Actual behaviour
Sharing Tab is not shown for "buggy" domain, please see screenshots (appended) "Sharing_Tab_MISSING_for_DomainB.png" and "Sharing_Tab_WORKING_for_DomainA.png"

### Server configuration

**Operating system:**
OpenSuse Leap 15.1, own VPS
**Web server:**
Apache 2.4.33
**Database:**
MariaDB 10.2.31
**PHP version:**
7.2.5

**Nextcloud version:** (see Nextcloud admin page)
18.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
years ago migarted from owncloud. seqential nextcloud upgrades since then.

**Where did you install Nextcloud from:**
OpenSuse Leap distro rpms

**List of activated apps:**
<details>
<summary>App list</summary>
sudo -u wwwrun php occ app:list
The current PHP memory limit is below the recommended value of 512MB.
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - audioplayer: 2.9.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.1.4
  - music: 0.13.2
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.7
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "updatechecker": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost:10080",
            "WORKING.example.org",
            "NOT_WORKING.beispiel.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost:10080\/nextcloud",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "sendmail",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "appstore.experimental.enabled": true,
        "theme": "",
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "log_rotate_size": 10485760,
        "app_install_overwrite": [
            "tasks",
            "contacts",
            "unsplash",
            "bruteforcesettings"
        ],
        "mysql.utf8mb4": true
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO

**Are you using encryption:** yes/no
YES

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
Firefox 75.0, but issue is IMHO Browser independent
**Operating system:**
OpenSuse Leap 15.1
![Sharing_Tab_MISSING_for_DomainB](https://user-images.githubusercontent.com/15951622/78994129-a6370080-7b3f-11ea-936f-80f4da043ae2.png)
![Sharing_Tab_WORKING_for_DomainA](https://user-images.githubusercontent.com/15951622/78994131-a6cf9700-7b3f-11ea-8f11-1b6a860a6ea4.png)

**Comment by landryb** [comment]
i've seen a similar bug with the sharing tab being hidden, but that was regardless of the order of trusted_domain values (only a real domain and localhost here) - though using a webkit-based browser like midori showed me the sharing tab, ... so maybe something js/browser-related ?

**Comment by michaelof** [comment]
Indeed, browser specific!
Tried for testing with chromium on OpenSuse, works!

**Comment by Nils160988** [comment]
The missing sharing tab is also known to be related to certain addblockers. That would fit your observation of it beeing browser specific.
Do you use an addblocker with your browser? Maybe the addblock-configuration is different for domain 0 and 1.

**Comment by michaelof** [comment]
un-be-iiev-able! Thank you so much!

In fact I've activated Adblock Plus (ABP), as an (must-have nowadays :-)) addon for firefox. 
--> Deactivating for my "buggy domain B" SOLVES this issue. Can create and manage shares also for domain B now

BUT weird as it is: ABP prevents Nexcloud from working correctly for domain B, but does NOT TELL about it!! ABP firefox stop sign in tool bar does NOT show the # of blocked items as usual, and opening the ABP details page for a nextcloud domain B page says "0 elements blocked"

That's why I've NEVER expected this to be an ABP issue, although  I'm usually (of course) look at ABP status for webpage related issue at first. 

So I've LEARNED SOMETHING VERY IMPORTANT, and again: Thank both of you very, very much, @landryb and @Nils160988 


Last question: As this is nevertheless an end user confusing issue, what are your thoughts: 
1. possible for nextcloud to change anything and handle this issue? guess not.
2. Firefox issue?
3. ABP issue?
If you think 2 and/or 3, I'll open issue in mozilla's or ABP's issue tracking systems

**Comment by Nils160988** [comment]
https://github.com/nextcloud/server/issues/16337 and https://github.com/nextcloud/server/issues/20080 for reference ;)
You can probably close this one, I think

**Comment by szaimen** [comment]
Closing as this seems to be resolved.
