### ISSUE TITLE
Phantom Shares on NC 18.0.3 

### ISSUE THREAD

**Issue by resoli** [nextcloud/server#20436]
Hello, 

I recently upgraded to 18.0.3, and noticed that some shares (by me as admin to a user group) are still proposed to freshly created users even if I deleted all my shares towards others.

These "phantom shares" are related to federated shares offered by another NC instance to the admin user, re-shared by admin to the local user group.

Moreover, if the freshly created user tries to use an old desktop sync client (till 2.6.2, included), the phantom shares prevent him even to start the first syncronization (HTTP Transmission error): 
![nc-desktop-2 5 1git_firstsync_error](https://user-images.githubusercontent.com/9579173/79045289-a18b4e80-7c0a-11ea-9ed1-04d9a512cd0f.png)

### Steps to reproduce
1. Delete all shares offered to group "MyGroup" by admin account
2. Create new user (s7 in the present example) as member of "MyGroup".
3. Login as s7, see old shares from admin to "MyGroup" account still proposed to s7 in a notification. Proposed shares are invisible on s7's web user interface.
4. Try to configure desktop sync client (v2.5.1 in the example, same behaviour till 2.6.2, 2.6.4 succeddes), observe Error "HTTP Trensmission error" ar first sync.
5. If s7 "Unshares" all, previously invisible old shares by admin, suddenly appears. Unsharing them makes desktop sync client work.
6. Share coming from other users, not reshared from an upstream federated share are working as usual.

### Expected behaviour
No deleted share should be proposed to users.

### Server configuration

**Operating system:**
Debian buster, on server, and on s7 client.

**Web server:**
Apache 2.4 from stock debian buster package.

**Database:**
Mysql (mariadb) from stock debian package

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from previous versions, shares created on previous versions.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by resoli** [comment]
No more relevant
