### ISSUE TITLE
Theming NC18 - iOS - It's not possible to add user or group on iPad (iPadOS 13/ iOS13) in landscape view

### ISSUE THREAD

**Issue by inet-cologne** [nextcloud/server#20434]
If in **landscape** view mode on **iPad** (safari or chrome browser) it is **not possible to add a group or user** any more as the left menu column does not show anything. It's the same with german and english locale settings.

You need to turn your iPad to portrait mode. Then everythings fine.

Screenshot is showing the landscape view. 
![6887128C-ABC9-44D6-8D96-A1DA4D61FD56](https://user-images.githubusercontent.com/42293052/79041742-5e24e600-7bf2-11ea-9f98-6b62d5867fad.jpeg)

A bug in the theming I think.

**Comment by inet-cologne** [comment]
Sorry. Saw that there's a special iOS area for bug reports.
I try to add a link there pointing to this topic.

**Comment by szaimen** [comment]
I think this should be resolved with the new user creation Modal in NC22.
