### ISSUE TITLE
setIconsCss issue in IconsCacher.php

### ISSUE THREAD

**Issue by MrApplejuice** [nextcloud/server#20430]
Today, I updated my nextcloud server from version 17.0.2.1 to 18.0.3.0. This was a bit of a rocky update. After the update nextcloud would not come back up again because of the following error:

~~~~~~.json
        "app": "index",
        "level": 3,
        "message": {
            "Code": 0,
            "CustomMessage": "--",
            "Exception": "OCP\\Files\\NotPermittedException",
            "File": "/var/www/html/nextcloud/lib/private/Files/Node/File.php",
            "Line": 77,
            "Message": "",
            "Trace": [
               "NOTE: full trace in attached log file"
            ]
        },
        "method": "GET",
        "remoteAddr": "192.168.0.10",
        "reqId": "NmJRwOAHwt8sa0M4f6Vd",
        "time": "2020-04-10T19:48:29+00:00",
        "url": "/nextcloud/index.php/apps/files/",
        "user": "paul",
        "userAgent": "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0",
        "version": "18.0.3.0"

~~~~~~

Note: **I edited the traceback because it contained multiple strings that were larger than 150 kB in size and to remove names**. The long strings seemed to be mainly long inline-css css strings.

I traced back the error to these lines, though I am not sure if these are the cause of the issue:

https://github.com/nextcloud/server/blob/1762a409f954fd9a66e7572704ea9ba7813601b4/lib/private/Template/IconsCacher.php#L143-L150

In order to experiment with the issue I changed the line `if (\strlen($data) > 0 && \strlen($list) > 0) {` to `if (\strlen($data) > 0 && \strlen($list) > 0 && 0) { ` to jump over the branch and see if any follow up errors would occur. However, the page loaded fine.

I reverted back to the old line to inspect the error more closely but it was gone! So I have no clue what was going on, my site seems to be online. Maybe some cache was not updated but I could not tell which. Maybe someone else who knows the codebase better can have a second look. Otherwise, my experience might help someone else to "fix" this issue for him/her.

[log_shortened.txt](https://github.com/nextcloud/server/files/4463302/log_shortened.txt)

**Comment by MrApplejuice** [comment]
I just discovered that the issue is _not_ actually solved for me. If I try to go to the settings menu, it happens again. My hack (disabling the caching functions) seems to work to mitigate the issue. Not sure if there are any undesired sideffects.

**Comment by MrApplejuice** [comment]
Okay. I did another series of updates, and the same error popped up again. I discovered some anomalies during the update. It ended with the warning:

~~~~~~
Repair warning: Unable to clear the frontend cache
~~~~~~

The full upgrade chain was 18.0.3 -> 18.0.14 -> 19.0.10 (got stuck after this part because on 20.0.9 I got an integrity check issue)

Here the full update log for the update 18.0.3 -> 18.0.14:
[update-log.txt](https://github.com/nextcloud/server/files/6511633/update-log.txt)

I also was able to extract the internal path to the file that generates the `NotPermittedException` , which is 
`/appdata_oc7s147zwynr/css/icons/icons-vars.css`. Turns out that this file _is_ in my datafolder, but, of course, my system root-folder is not my data folder. That would instead be `/srv/stripestore/store/nextcloud`. It seems to me that something does not correctly assemble the path in the pipeline.

I also generated a stacktrace for someone to look into:

~~~~~~
Technical details

    Remote Address: 192.168.0.10
    Request ID: GMQyOG3KA2o96lNzskbl
    Type: OCP\Files\NotPermittedException
    Code: 0
    Message: /appdata_oc7s147zwynr/css/icons/icons-vars.css
    File: /var/www/html/nextcloud/lib/private/Files/Node/File.php
    Line: 77


Trace

#0 /var/www/html/nextcloud/lib/private/Files/SimpleFS/SimpleFile.php(108): OC\Files\Node\File->putContent(':root {\n--icon-...')
#1 /var/www/html/nextcloud/lib/private/Template/IconsCacher.php(146): OC\Files\SimpleFS\SimpleFile->putContent(':root {\n--icon-...')
#2 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(353): OC\Template\IconsCacher->setIconsCss('/**\n * @copyrig...')
#3 /var/www/html/nextcloud/lib/private/Template/SCSSCacher.php(190): OC\Template\SCSSCacher->cache('/var/www/html/n...', '47cd-6c00-setti...', 'settings.scss', Object(OC\Files\SimpleFS\SimpleFolder), '/nextcloud/apps...')
#4 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(110): OC\Template\SCSSCacher->process('/var/www/html/n...', 'css/settings.sc...', 'settings')
#5 /var/www/html/nextcloud/lib/private/Template/CSSResourceLocator.php(85): OC\Template\CSSResourceLocator->cacheAndAppendScssIfExist('/var/www/html/n...', 'css/settings.sc...', 'settings')
#6 /var/www/html/nextcloud/lib/private/Template/ResourceLocator.php(78): OC\Template\CSSResourceLocator->doFind('css/settings')
#7 /var/www/html/nextcloud/lib/private/TemplateLayout.php(310): OC\Template\ResourceLocator->find(Array)
#8 /var/www/html/nextcloud/lib/private/TemplateLayout.php(215): OC\TemplateLayout::findStylesheetFiles(Array)
#9 /var/www/html/nextcloud/lib/private/legacy/template.php(184): OC\TemplateLayout->__construct('user', 'settings')
#10 /var/www/html/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php(167): OC_Template->fetchPage(Array)
#11 /var/www/html/nextcloud/lib/private/AppFramework/Http/Dispatcher.php(123): OCP\AppFramework\Http\TemplateResponse->render()
#12 /var/www/html/nextcloud/lib/private/AppFramework/App.php(125): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\Settings\Controller\PersonalSettingsController), 'index')
#13 /var/www/html/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php(47): OC\AppFramework\App::main('OCA\\Settings\\Co...', 'index', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#14 [internal function]: OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
#15 /var/www/html/nextcloud/lib/private/Route/Router.php(299): call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
#16 /var/www/html/nextcloud/lib/base.php(1011): OC\Route\Router->match('/settings/user')
#17 /var/www/html/nextcloud/index.php(38): OC::handleRequest()
#18 {main}
~~~~~~

Please note that I got this error for all versions I updated to, so this is not an isolated incidence anymore right now. Unfortunately.

I will reapply my workaround from last year for now. If someone has an idea, please tell me :)

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
