### ISSUE TITLE
User counts not updated on add/delete (w/o page refresh)   

### ISSUE THREAD

**Issue by joshmorel** [nextcloud/server#20438]
I generated this from Issue Template app but I'm quite certain this relates solely to Vue (i.e. server stuff isn't relevant). First noticed this on 18.0.3 when troubleshooting another issue and confirmed with recent pull from GitHub. This should likely be considered low priority item. I wouldn't mind taking it on as a first contribution.

### Steps to reproduce
1. As Admin go to Users. Add new user and at same time add to group. 
2. Refresh page
3. Delete user. 

### Expected behaviour
1. User count increases in Everyone + group
2. User count same as step 1
3. User count decreases in Everyone + group

### Actual behaviour
1. User count doesn't increase for Everyone + group
2. User count is now as expected
3. User count doesn't decrease in Everyone + group

Updating existing user's groups and enabling/disabling a user does change counts as expected.

![nextcloud-settings-users-counts-update](https://user-images.githubusercontent.com/10546720/79051611-0f317d80-7bff-11ea-86c6-30acc1521d32.gif)

## Server configuration detail

**Operating system:** Linux 4.15.0-96-generic #97-Ubuntu SMP Wed Apr 1 03:25:46 UTC 2020 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.1.44

**PHP version:** 

7.2.24-0ubuntu0.18.04.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 19.0.0 beta 2 - 19.0.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** git

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - issuetemplate: 0.6.0
 - lookup_server_connector: 1.7.0
 - oauth2: 1.7.0
 - provisioning_api: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - systemtags: 1.9.0
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - testing
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "ncdev.local",
        "192.168.33.19"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.0.3",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "issuetemplate"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0 (NOTE: same on Chrome)

**Operating system:** Kubuntu 1804

## Logs

<details><summary>Web server error log</summary>

```
Not applicable
```
</details>

<details><summary>Nextcloud log</summary>

```
Not applicable
```
</details>

<details><summary>Browser log</summary>

None related to this issue
</details>

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.2

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
