### ISSUE TITLE
trusted proxies broken in 17.0.5

### ISSUE THREAD

**Issue by crackers8199** [nextcloud/server#20441]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. install 17.0.5
2. set up trusted proxy
3.

### Expected behaviour
trusted proxies should work

### Actual behaviour
they do not

### Server configuration

**Operating system:**
docker container

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
17.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
docker hub

17.0.5 does not seem to work with trusted proxies, and as such the warning on the settings overview page never goes away. i reverted to the 17.0.4 image and it works as expected.

```
root@4e4cdcb389c0:/var/www/html# sudo -u www-data php occ config:system:set trusted_proxies 0 --value=192.168.64.3
System config value trusted_proxies => 0 set to string 192.168.64.3
root@4e4cdcb389c0:/var/www/html# sudo -u www-data php occ config:system:get trusted_proxies

root@4e4cdcb389c0:/var/www/html# 
```

if you start with the 17.0.4 image and then upgrade to 17.0.5 after you have a working 17.0.4 install, then it works...but it does not work if you start with a clean install of 17.0.5.

we have a thread on the community open on this...

https://help.nextcloud.com/t/cannot-get-rid-of-the-reverse-proxy-warning/77376/14

**Comment by crackers8199** [comment]
we have a thread on the community open on this, someone else is seeing the same behavior i am

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/20167 is the only change from 17.0.4 to 17.0.5.

**Comment by kesselb** [comment]
I guess that is related to https://github.com/nextcloud/docker/pull/1010. If you don't set it via environment variable it's null by default.

**Comment by kesselb** [comment]
Should be fixed by https://github.com/nextcloud/docker/pull/1048
