### ISSUE TITLE
Previews for Bitmaps too large

### ISSUE THREAD

**Issue by exussum12** [nextcloud/server#20452]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload a PDF
2. Generate previews
2. Convert to jpg `convert 1024-1024-crop.png test.jpg` for example

### Expected behaviour
Previews smaller than actual PDF

### Actual behaviour
Previews Larger than PDF

### Server configuration
N/A

The Bitmap generator used by 
Font
Photoshop
PDF
TIFF
Illustrator
Postscript

uses PNG for its output format an example PDF on my server, the 1024*1024 is 1.3MB, optipng reduces to 1.2MB (8% saving, but much more processing power required) Converting to jpg reduces to 373kb (~72% saving). For context the PDF is about 1MB.

Its a very simple change, is there any reasons not to do this ?

Ones I can think are below
Basic images - Like nextcloud manual, this is larger with jpeg, Its smaller with gif. The image above is also smaller with gif, but larger than jpeg

Transparency support. Not sure how useful that is.

So a quick recap

Filesize Larger > Smaller

Complex Image
PNG > GIF > JPG

Basic Image
JPG > PNG > GIF

Would a change to jpg / gif be accepted ?

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by exussum12** [comment]
It is, I can make the PR but not sure why its like this to start with.

**Comment by szaimen** [comment]
> but not sure why its like this to start with.

I don't know, either.

**Comment by szaimen** [comment]
cc @nextcloud/server-triage for some input on this

**Comment by exussum12** [comment]
Happy to make this change if someone has some input on this.
