### ISSUE TITLE
Slogan text not properly encoded

### ISSUE THREAD

**Issue by schopenhauer** [nextcloud/server#20459]
### Steps to reproduce

1. Change the slogan in the "Theming" config page to include a ' (i.e. single quote or apostrophe)
2. Leave the configuration page
3. Return to the "Theming" config page and find the incorrectly encoded ' as &#039; in the Slogan text field

### Screenshot

![Screenshot_2020-04-13_14-23-30](https://user-images.githubusercontent.com/2085103/79120512-5a7c9500-7d93-11ea-9d52-070ce4e21225.png)

### Server configuration

**Operating system: Ubuntu 18.04**
**Web server: Apache 2.4**
**Database: MySQL**
**PHP version: 7.4.4**
**Nextcloud version: 18.0.3**

**Comment by kesselb** [comment]
Seems like a duplicate of https://github.com/nextcloud/server/issues/7460

**Comment by schopenhauer** [comment]
@kesselb - yes, this issue is a duplicate of [#7460](https://github.com/nextcloud/server/issues/7460) and can be closed.
