### ISSUE TITLE
Cronjob separate schedules

### ISSUE THREAD

**Issue by LeonardoGentile** [nextcloud/server#2045]
Hello,
apologies if I did not use the template but I think it wouldn't apply here.

My first point is a suggestion to update the doc to clearly state **what** cron is going to run. To find out I had to dig in the `jobs` db table, analyze the strings in there and look for the relevant piece of code that would be run by cron. Either I did not find the list of these tasks in the docs or they are not mentioned at all.

My second point is more a feature request. In my setup I put the hard disk to sleep if nothing happens for x time (let's say 20 min). If I run cron every 15 min it will have to access my disk for the tasks related to file cleaup and management in fact waking up the disk too often.  
So my suggestion would be to make this system more flexible, giving the possibly to run **some** task (as db or email management) often and other (file access) less often. In general to let the user decide **what** to run and **when**.

Would this be possible?

**Comment by nickvergessen** [comment]
Well as far as I know almost all jobs need access to the file system, so it would defeat the purpose?

**Comment by LeonardoGentile** [comment]
@nickvergessen even the ones only cleaning up the database?

Btw in the docs and example the crontab is set to run every 15 minutes. Where this value is coming from? Do we **really** need to run these jobs every 15 minutes? Or is it something related to the number of users/usage/workload for hour? What could be the trouble if I run this jobs avery 12/24 hours? 

I'm asking because these jobs seems not to be documented so I'm not really sure what's going on all the time. Having a list of the default jobs in the docs would help and make things clear.

**Comment by rullzer** [comment]
The filesystem is initialized but this by itself doesn't access the disk. It is a lot of reading from the DB etc. Only if we do actual file operations (emptying the trash for example). Then of course we also have to delete files.

But PHP is doing a lot of reading of mtimes on disk etc to see if its opcache is still up to date.

The way I solved this is by having an SSD in my server. This holds (among other things) the Nextcloud code and the DB. I have the data location on a big HDD. This way the drive only spins up on actual data access.

**Comment by nickvergessen** [comment]
Closing as per above and due to the limitations

**Comment by LeonardoGentile** [comment]
Thanks @rullzer I will perform some test and check if spindown is not interrrupted too ofted by the cron jobs.

As for the other points:
 - update the doc, explaining briefly what those jobs do
 - is it really necessary to run those jobs every 15 minutes? Could you give us some hint on how to fine tune this value depending on different requirements? Let's say I have an instance where I am the only user, uploading max 1 times per day, should I keep 15 minutes or in this case I can just change this value to much longer time slot?

**Comment by nickvergessen** [comment]
On one user instances you can make this slower, if you don't care about activities and other things running regularly. However that is nothing we will promote in our docs.
