### ISSUE TITLE
Plural translations don't seem to work

### ISSUE THREAD

**Issue by matiasdelellis** [nextcloud/server#20453]
### Steps to reproduce
1. Inside the server, set the language to a translation, for example, Spanish Argentina
2. Find some plural translations. For example the summary of the current folder.
3. Just check if the plural works.

### Expected behaviour
In summary expect:
> 6 carpetas y 5 archivos 	8,5 GB

### Actual behaviour
In summary i see:

> 6 carpeta y 5 archivo 	8,5 GB

![imagen](https://user-images.githubusercontent.com/733715/79083796-b77e3980-7d06-11ea-8426-1bcf01ffb4fe.png)
:disappointed: 

Note that the translation is programmed correctly:

https://github.com/nextcloud/server/blob/2b913de41706aae531d476d80f64c4fd2fd91b92/apps/files/js/filesummary.js#L223-L226

..and also is translated.

https://github.com/nextcloud/server/blob/df463f90be01be2d38f6cdd5b2b1a20900696b54/apps/files/l10n/es_AR.js#L61-L62

But use the singular, with the number greater than 1. 

## Server configuration detail

**Operating system:** Linux 5.5.10-200.fc31.x86_64 #1 SMP Wed Mar 18 14:21:38 UTC 2020 x86_64

**Webserver:** Apache/2.4.43 (Fedora) OpenSSL/1.1.1d (fpm-fcgi)

**Database:** mysql 10.3.22

**PHP version:** 

7.3.16
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, iconv, imap, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, igbinary, imagick, msgpack, pcov, pdlib, smbclient, zip, redis, libsmbclient, Zend OPcache

**Nextcloud version:** 18.0.2 - 18.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```

```
</details>

**Are you using external storage, if yes which one:** 

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
Good finding :+1: 

![image](https://user-images.githubusercontent.com/3902676/79138995-ca037c00-7db5-11ea-9ddd-a3cf9e2ee735.png)

It seems to work with es. 

![image](https://user-images.githubusercontent.com/3902676/79139470-a987f180-7db6-11ea-8e4b-9d0603e826e4.png)

That seems to be the issue. The function assumes that the language is `es_AR` but `es-AR` is passed. I'm not sure why the language is `es-AR` or where this value is coming from ;)

cc @gary-kim @nextcloud/javascript

**Comment by skjnldsv** [comment]
We updatet the lang list recently iirc?
Maybe before they made sure to convert everything to _ and not - ?
Or the other way around :p
Anyway, simple fix I guess?

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/79140531-6dee2700-7db8-11ea-9171-8f6e3da0f198.png)

It's correct over there :man_shrugging:

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/commit/e5be2991019f1a6716d253596562f8ab0f4df008 That's the commit /code changing `es_AR` to `es-AR`. It's like that since Nextcloud 14 so changing the `_getPlural` function should do it.

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/server/pull/17222

**Comment by matiasdelellis** [comment]
Well, I guess is difficult to discuss about translations to Transifex, but seem that they use underscores to separate counties from translations, which seems wrong. I don't know what would be the right thing ..

**Comment by MorrisJobke** [comment]
@skjnldsv There was a reason why it is - instead of _ but I can't find it right now. For the transformation it might also help to just specify it here: https://github.com/nextcloud/server/blob/master/.tx/config#L3 ?

**Comment by MorrisJobke** [comment]
> @skjnldsv There was a reason why it is - instead of _ but I can't find it right now. For the transformation it might also help to just specify it here: https://github.com/nextcloud/server/blob/master/.tx/config#L3 ?

Keep in mind that this then needs to be updated in every single app out there. So fixing the JS part to look for the transifex version of the string might be the easier solution.

**Comment by matiasdelellis** [comment]
And do the fix within the tool [translationtool.phar](https://github.com/nextcloud/docker-ci/raw/master/translations/translationtool/translationtool.phar)? I think we all use this to apply translations.

**Comment by kesselb** [comment]
I'm confused now. Are we still talking about the same thing?

https://github.com/nextcloud/server/pull/8217 changed `es_AR` to `es-AR`. The reason is that https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang expects the language tag as defined at https://www.ietf.org/rfc/bcp/bcp47.txt. 

What needs to done is to check the usages of OC.getLanguage() and other places using the lang attribute and make sure the code expects `-` instead of `_`. Fixing `_getPlural` might be a start.

**Comment by welaq** [comment]
In Lithuanian plurals also do not work even though strings in Transifex are translated...

**Comment by matiasdelellis** [comment]
Thank you very much @kesselb
