### ISSUE TITLE
Better file access check before upgrade with SELinux systems

### ISSUE THREAD

**Issue by omerule** [nextcloud/server#20455]
Good afternoon,
When upgrading with the webinterface there are some checks access checks done before doing the upgrade (NC 17 to 18).
But in my case during the upgrade process there was still a access problem.
I think i fixed the access problem Denial SELinux php-fm var/www/html/nextcloud/themes/.
But the upgrade process had already changed many files, emptied de apps dir etc.
This way you get stuck halfway, in a upgrade process which could not completed but already altered the system.

Is it possible for the upgrade process, to check file access - before doing anything -   of the intended file mutation during the upgrade process?

Yours kindly Omer

**Comment by kesselb** [comment]
The right repository for such a report is https://github.com/nextcloud/updater. Please include a minimal working example (especially the selinux rules) how to reproduce such a situation.
