### ISSUE TITLE
Dark theme applies when printing

### ISSUE THREAD

**Issue by mcorteel** [nextcloud/server#20468]
For now, when printing a page with dark theme enabled, the page has whitish text against black background, which prints as white text against white background. This is an issue with the cookbook app (mrzapp/nextcloud-cookbook#192).

Dark mode should be behind a `@media screen` media query. See `/apps/accessibility/css/dark.scss`.

Tested with NC 18 and 19-beta2.

I'm willing to create the pull request if you confirm that it's an issue with nextcloud/server.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
