### ISSUE TITLE
S3 primary storage : always recalculating file size

### ISSUE THREAD

**Issue by FlorentCoppint** [nextcloud/server#20477]
### Steps to reproduce
1. Install Nextcloud with S3 primary storage
2. Upload files
3. List directories

### Expected behaviour
All metadata (file names, file size, etc...) to be retrieved from database.

### Actual behaviour
Recalculation of "unencrypted size" occurs every time.

### Server configuration

**Operating system:** Debian 10

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.org

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.2.0
  - dav: 1.14.0
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_automatedtagging: 1.8.2
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflow_script: 1.3.1
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.perso.io"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "overwrite.cli.url": "https:\/\/cloud.perso.io",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "3306",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "filelocking.enabled": false,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "cloud-perso",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "s3.fr-par.scw.cloud",
                "port": 443,
                "use_ssl": true,
                "region": "fr-par",
                "use_path_style": true
            }
        },
        "maintenance": false,
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "simpleSignUpLink.shown": false,
        "trashbin_retention_obligation": "180, 365",
        "versions_retention_obligation": "180, 365",
        "theme": "",
        "loglevel": 3,
        "dbdriveroptions": {
            "1007": "\/etc\/ssl\/mysql\/client-key.pem",
            "1008": "\/etc\/ssl\/mysql\/client-cert.pem",
            "1009": "\/etc\/ssl\/mysql\/ca-cert.pem",
            "1014": true
        },
        "updater.release.channel": "stable"
    }
}
```
</details>

**Are you using external storage, if yes which one:** S3

**Are you using encryption:** yes

I found a bug when using S3 as primary storage.

The default encryption module is always trying to recalculate each file size, querying S3 provider each time (waste of resources).

The problem occurs for example when listing a directory. Each file size is stored in database, but Nextcloud is ALWAYS querying S3 provider to get file size.

The culprit is in /lib/private/Files/Storage/Wrapper/Encryption.php

In the function filesize() :

```
		if (isset($info['fileid']) && $info['encrypted']) {
			return $this->verifyUnencryptedSize($path, $info['size']);
		}
```

This condition is always true when S3 as primary storage, then in verifyUnencryptedSize(), "$unencryptedSize === $size" is ALWAYS true when S3 used as primary storage. Of course it should not.
When S3 primary storage is used, the "size" saved in database is the unencrypted size !
So the condition is true, so a new recalculation of unencrypted file size is done EVERY TIME a filesize is needed !

I think we should use correctly "size" and "unencrypted_size" fields in database with S3 primary storage and the problem should be gone.

Can someone give feedback about this issue ?

**Comment by Dragon988** [comment]
This actually gets worse. Check out #20478 

Apparently it has to list the entire bucket to get user quota. If you run an indexless bucket (meaning nextcloud is in charge of everything) users with quota enabled can't even login.

Linking because the issue is relevant to this bug as well.

**Comment by kesselb** [comment]
Issue Template?

**Comment by FlorentCoppint** [comment]
> Issue Template?

It has limited interest here. There's no step to reproduce, not related to web server...

I debugged and directly give technical data...

**Comment by cuppett** [comment]
Similar to #17591 (wrong size used for a display)

**Comment by kesselb** [comment]
cc @rullzer @icewind1991

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by SimplyCorbett** [comment]
Is this issue still valid in NC22??

**Comment by cuppett** [comment]
FWIW, in NC 22.1.0 with S3 primary storage and default encryption, I'm seeing the same size reported in the UI as what S3 is listing for it (I'd expect the actual size to vary somewhat).

Potentially unrelated (still digging a little bit):

In addition, I can preview them in the web UI just fine, but when I try to "Download" images or MP4 files I see this in the log (and get an error):

[22-Aug-2021 10:56:43] WARNING: [pool www] child 60 said into stderr: "NOTICE: PHP message: [owncloud][no app in context][3] Couldn't re-calculate unencrypted size for files/InstantUpload/Camera/20210508_194333.jpg"
[22-Aug-2021 10:56:43] WARNING: [pool www] child 60 said into stderr: "NOTICE: PHP message: [owncloud][no app in context][3] {"Exception":"OCP\\Encryption\\Exceptions\\GenericEncryptionException","Message":"Bad Signature","Code":0,"Trace":[{"file":"/var/www/html/apps/encryption/lib/Crypto/Crypt.php","line":470,"function":"checkSignature","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/apps/encryption/lib/Crypto/Encryption.php","line":377,"function":"symmetricDecryptFileContent","class":"OCA\\Encryption\\Crypto\\Crypt","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php","line":583,"function":"decrypt","class":"OCA\\Encryption\\Crypto\\Encryption","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/private/Files/Storage/Wrapper/Encryption.php","line":503,"function":"fixUnencryptedSize","class":"OC\\Files\\Storage\...
