### ISSUE TITLE
Special characters in folder name break Nextcloud Sync

### ISSUE THREAD

**Issue by SamirSaidani** [nextcloud/server#20482]
### Steps to reproduce
1. Prerequisite : a tested and functional Nextcloud Sync
2. Create a folder named  <verbatim>test "sync"</verbatim> with the quotes in the webapp 
2. Create a folder named  <verbatim>test sync</verbatim> without the quotes in the webapp  
3. Check your synced directory : folder <verbatim>test sync</verbatim> appears, <verbatim>test "sync"</verbatim> does not

### Expected behaviour
When entering folder name with special characters, the webapp must prevent us to use any special characters not allowed in the folder name of all major OS - linux/mac/windows/android

### Actual behaviour
No sync

### Server configuration

Windows 10/NC 17.0.2/NC Sync Version 2.6.4stable-Win64 (build 20200303). 

### Note
I've tested all windows special characters : /\:?*><|.
Special characters breaking nextcloud sync are ":?<>|. The not allowed ones, working as expected, are : \ /

**Comment by colorchestra** [comment]
I just ran into the same thing. A fix would be greatly appreciated! I've tried explaining to all our users that they can't use double quotes in file names, but that's not very user friendly and just not sustainable, and it keeps happening from time to time.

**Comment by wiswedel** [comment]
related: https://github.com/nextcloud/server/issues/7762

**Comment by Mululu** [comment]
I ask you to solve this problem with the next update.

No matter how often you tell users not to use these symbols, it still happens again and again.

Thank you so much!

**Comment by szaimen** [comment]
> When entering folder name with special characters, the webapp must prevent us to use any special characters not allowed in the folder name of all major OS - linux/mac/windows/android

cc @nextcloud/server-triage is this feasible?

**Comment by thsnielsen** [comment]
Nextcloud 24.0.6 having the same issue but not with folder names, but file name - i cannot sync my files down to a new linux client (nextcloud-desktop-3.6.0-1.2.x86_64), and then discovered, that i cannot also visualize the files using the gui.
I am not even sure if it is nextcloud initially when receiving these files that has removed the "ê" and made it a "?" - because the %3F% should have been a "ê" and not "?"

**Comment by aurisnoctis** [comment]
A user in our Nextcloud created a file with `?` as part of the filename. Now it cannot be renamed or moved or deleted. I copied the contents into another file with a normal name, but how can we get rid of the file with `?`?

Version: `Nextcloud Hub 8 29.0.4`

**Comment by egabosh** [comment]
Why is this closed? Problem is still there.
