### ISSUE TITLE
Opening file for editing in a new tab

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#20489]
Please, add the option of opening a file for editing (Collabora/Onlyoffice/markdown editor) in a new tab. This will help to keep viewing the tree of files in the original tab what is essential when working with several documents.

**Comment by vohzd** [comment]
I also second this! It's a small thing that makes it super super user friendly!

**Comment by szaimen** [comment]
I think for collabora and onlyoffice was the option already implemented. If you want this for the default text editor, please open a new issue there https://github.com/nextcloud/text. Thanks!
