### ISSUE TITLE
Can't swap contacts between address books

### ISSUE THREAD

**Issue by phiL0co** [nextcloud/server#20492]
### Steps to reproduce
1. Create a second adress book
2. Open a contact and switch the contact to the new address book (choose new address book from list)
3. Close the contact and reopen it -> contact's address book is the old one again.

### Expected behaviour
The address book should remain the previously selected

On the phone (after a sync) a "switched" contact should only be in one address book, the address book that is selected in Nextcloud's contact app.

### Actual behaviour
The address book always switches back to the first one.

BUT: When I sync the new address book on my phone, suddenly the contact seems to be in both address books, according to the phone. In the browser view, the contact remains in the old address book. So it seems somethings is happening in the background.

After syncing with the phone at some point the contact appears twice in Nextcloud contacts app, one contact in the old address book, the other one in the new address book.

### Server configuration

**Operating system**:
Ubuntu 18.04

**Web server:**
Apache

**Database:**
MySQL 5.7.28

**PHP version:**
7.2.24

**Nextcloud version:** (see Nextcloud admin page)
17.0.2

**Contacts version:** (see Nextcloud apps page)
3.1.6

**Updated from an older Nextcloud or fresh install:**
Updated

**Signing status:**
What does this mean?

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
```

**List of activated apps:**
Accessibility 1.3.0
Activity 2.10.1
Auditing / Logging 1.7.0
Bookmarks 2.3.4
Calendar 2.0.0
Checksum 0.4.3
Collaborative tags 1.7.0
Comments 1.7.0
Contacts 3.1.6
Default encryption module 2.5.0
Deleted files 1.7.0
Draw.io 0.9.4
Federation 1.7.0
File sharing 1.9.0
First run wizard 2.6.0
Gallery 18.4.0
Log Reader 2.2.0
Markdown Editor 2.2.0
Metadata 0.10.0
Monitoring 1.7.0
Nextcloud announcements 1.6.0
Notifications 2.5.0
ocDownloader 1.7.5
Password policy 1.7.0
PDF viewer 1.6.0
Privacy 1.1.0
RainLoop 6.0.4
Recommendations 0.5.0
Right click 0.15.1
Share by mail 1.7.0
Support 1.0.1
Suspicious Login 3.0.1
Tasks 0.11.3
Text 1.1.1
Theming 1.8.0
Two-Factor TOTP Provider 4.1.2
Update notification 1.7.0
Usage survey 1.5.0
Versions 1.10.0
Video player 1.6.0
Viewer 1.2.0
```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**Nextcloud configuration:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Only CalDav and CardDav if thats a user-backend

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**
Firefox 68.4.1 esr /  Firefox 72

**Operating system:**
Windows 10 / Manjaro Linux

**CardDAV-clients:**
DAVx5

**Comment by phiL0co** [comment]
> Okay, you see the url you currently have, it should be something like yourdomain.com/apps/contacts/group/addressbookid~contactsuid
> 
> Change the addressbookid from default (it seems to be that) to the other one. Does it display a contact?
> (you can screenshot the very bottom of the `headers` tab for me as well as the `params` tab too please?)

I can click on the duplicate that's not in the default address book, then the URL switches to what you described. But it's the other way around, first the contact ID (cryptic) and then the name of the address book. (.../index.php/apps/contacts/Alle Kontakte/d88aebce-592d-46f0-a1ff-e11db67f28d0~default)

I noted, that the contact ID is the same in each address book:
.../index.php/apps/contacts/Alle Kontakte/d88aebce-592d-46f0-a1ff-e11db67f28d0~default

.../index.php/apps/contacts/Alle Kontakte/d88aebce-592d-46f0-a1ff-e11db67f28d0~jeph_gemeinsam


That's what the 200-entry says in headers:
![2020-04-15_10-44](https://user-images.githubusercontent.com/9380245/79317617-2fff1900-7f06-11ea-876a-d41a659035f6.png)

Nothing in the params box!

(I didn't switch a contact this time because to do what you asked I had to use the duplicate (to make the URL switch). And as long as that exists, I can't copy the contact again. I then get an error message like "contact already exists...". )

**Comment by phiL0co** [comment]
Another thing I should add that I didn't know in my initial opening post:

When I switch a contact from one address book to another, at first it seems the switch was successful. The contact is only shown once in the new address book. 
But when I reload the page the contact then appears twice in the list, once in every address book.

**Comment by cweiske** [comment]
On Nextcloud 19.0.1 the error message is different:
```
MOVE /remote.php/dav/addressbooks/users/admin/contacts/12DE8587-2859-4349-A5D5-7EEB89051A71.vcf

400 Bad Request

<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Calendar object with uid already exists in this calendar collection.</s:message>
</d:error>
```

**Comment by cweiske** [comment]
The problem is as follows:

1. When a vcard changes, "onCardChanged" is called on the BirthdayService, so that the birthdate can be stored in the calendar.
2. `BirthdayService::updateCalendar` checks if the calendar entry already exists with `CalDavBackEnd::getCalendarObject($calendarId, $objectUri)`. That one says "no, does not exist", because the `$objectUri` is at the new calendar.
3. `BirthdayService::updateCalendar` tries to create a new calendar entry with `CalDavBackEnd::createCalendarObject($calendarId, $objectUri, $calendarData->serialize())`. That fails, because `createCalendarObject` first checks if an calendar entry with that UID (not uri!) already exists, and throws an exception here.

**Comment by cweiske** [comment]
The problem is not that the card is changed; moving a card to another address book means that 1. a new card is created and 2. the old card is deleted.
This explains the duplicate address book entries after the crash.

This also means that we cannot see that a card is being moved; we must handle the duplicate calendar entry problem before the old one gets deleted.
