### ISSUE TITLE
Error in nextcloud.log after logout

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#20490]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade to 19 Beta 2
2. Login with a user
3. Logout with this user

### Expected behaviour
No error messages in log

### Actual behaviour
The nextcloud log shows an error each time a user logs out. So far, I can see no further effects, but it might be interesting for you to find the cause for this error.

### Server configuration

**Operating system:** Ubuntu 18.04.3

**Web server:** apache 2.4.29

**Database:** mariadb 10.1.44

**PHP version:** 7.2.24

**Nextcloud version:** 19.0.0.3 (Beta 2)

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - announcementcenter: 3.8.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.2.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 0.8.2
  - drawio: 0.9.5
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 6.0.5
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - systemtags: 1.9.0
  - tasks: 0.12.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - apporder
  - circles
  - documentserver_community
  - encryption
  - event_update_notification
  - external
  - files_automatedtagging
  - files_external
  - group_everyone
  - impersonate
  - onlyoffice
  - polls
  - ransomware_protection
  - spreed
  - support
  - survey_client
  - user_ldap
  - user_usage_report
  - workflow_pdf_converter
  - workflow_script
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.xyz.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/test.xyz.de\/nextcloud",
        "htaccess.RewriteBase": "\/",
        "dbtype": "mysql",
        "version": "19.0.0.3",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_locale": "de_DE",
        "logtimezone": "Europe\/Berlin",
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "beta",
        "skeletondirectory": "\/var\/www\/default-files",
        "maintenance": false,
        "mysql.utf8mb4": true,
        "data-fingerprint": "01ab1f439dc59f5b900a4be407aad640",
        "activity_use_cached_mountpoints": "true"
    }
}

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 75.0

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:20 +0200] "GET /logout?requesttoken=vEJgmQniP3UEkDYUF9HDKAocjDxE1t9YtyRByfPKudQ%3D%3AhTYW4XGpBydB4n1feKiGf019znYr%2BYki%2BEEZkJ%2F7gbg%3D HTTP/1.1" 303 1959 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:20 +0200] "GET /login?clear=1 HTTP/1.1" 303 879 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:20 +0200] "GET /login?clear=1 HTTP/1.1" 200 4921 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/deck/css/activity.css?v=2ebc9247-8 HTTP/1.1" 200 928 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/files_pdfviewer/css/style.css?v=4fda350b-8 HTTP/1.1" 200 910 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/css/guest.css?v=4f951eb8-8 HTTP/1.1" 200 6243 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/files_sharing/l10n/de.js?v=4f951eb8-8 HTTP/1.1" 200 5993 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/search/js/search.js?v=4f951eb8-8 HTTP/1.1" 200 2700 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/l10n/de.js?v=4f951eb8-8 HTTP/1.1" 200 19128 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/files_sharing/js/dist/main.js?v=4f951eb8-8 HTTP/1.1" 200 1719 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/files_pdfviewer/js/previewplugin.js?v=4f951eb8-8 HTTP/1.1" 200 2931 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/theming/styles?v=8 HTTP/1.1" 200 1840 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/files_videoplayer/js/main.js?v=4f951eb8-8 HTTP/1.1" 200 3392 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/js/files/fileinfo.js?v=4f951eb8-8 HTTP/1.1" 200 1565 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/search/js/searchprovider.js?v=4f951eb8-8 HTTP/1.1" 200 4431 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/js/files/client.js?v=4f951eb8-8 HTTP/1.1" 200 6408 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /js/core/merged-template-prepend.js?v=4f951eb8-8 HTTP/1.1" 200 4297 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/accessibility/js/accessibility?v=0 HTTP/1.1" 200 951 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/js/dist/login.js?v=4f951eb8-8 HTTP/1.1" 200 229195 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /apps/theming/js/theming?v=8 HTTP/1.1" 200 1130 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /core/js/dist/main.js?v=4f951eb8-8 HTTP/1.1" 200 423540 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:21 +0200] "GET /svg/core/logo/logo?color=fff&v=1 HTTP/1.1" 200 1169 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:22 +0200] "GET /core/img/favicon.ico HTTP/1.1" 200 3884 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
xxx.xxx.xxx.xxx - - [15/Apr/2020:00:18:22 +0200] "GET /core/img/favicon-touch.png HTTP/1.1" 200 3525 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"lKYXO4j9SrEvPvDGVDpJ","level":3,"time":"2020-04-15T00:18:20+02:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"--","app":"PHP","method":"GET","url":"/logout?requesttoken=vEJgmQniP3UEkDYUF9HDKAocjDxE1t9YtyRByfPKudQ%3D%3AhTYW4XGpBydB4n1feKiGf019znYr%2BYki%2BEEZkJ%2F7gbg%3D","message":"session_start(): A session had already been started - ignoring at /var/www/test-nextcloud/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"19.0.0.3"}
```
</details>

**Comment by cgzones** [comment]
OS: Debian Sid
Apache: 2.4.43-1
PHP: 7.4.5-1

```
{"reqId":"XqHXTWUb@-TAzm7MZj0EaQAAAAg","level":3,"time":"2020-04-23T17:58:37+00:00","remoteAddr":"replaced_ip","user":"--","app":"PHP","method":"GET","url":"/index.php/logout?requesttoken=replaced_token","message":"session_start(): A session had already been started - ignoring at /var/www/sites/nextcloud/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0","version":"19.0.0.6"}
```

**Comment by MeiRos** [comment]
I have this issue too. I opened a thread about it few days ago. There are more information about my setup etc.
https://help.nextcloud.com/t/a-session-had-already-been-started/81037

**Comment by axheli** [comment]
Im also getting the following on NC 19 RC2 PHP 7.4.6, MYSQL, APACHE2

session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

**Comment by LHollyfeld** [comment]
And again the error in the new 19.0.0   without RCxxxx

{"reqId":"4fyReJxUH3PJwpvKtZDr","level":3,"time":"2020-05-27T10:32:22+02:00","remoteAddr":"192.168.10.180","user":"--","app":"PHP","method":"GET","url":"/nextcloud/index.php/logout?requesttoken=TnYhjbweqYplNl6PSmVlAZSFf0UwA9%2B7WVHSBimyobQ%3D%3AFwVZxc176LoWdxa8MFILZN%2FoJhRpUo3qAB2FMUjiw%2Bc%3D","message":"session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0","version":"19.0.0.12"}

Ubuntu Server 20.04 and PHP 7.4. Update from Nextcloud 18.04.

**Comment by Ruinenarr** [comment]
Same here

**Comment by tacruc** [comment]
Probably related to: https://github.com/nextcloud/maps/issues/397

**Comment by Rob3487** [comment]
Same issue , fresh instalation , 19.0.0
Ubuntu 20.04
Apache 2.4.41
PHP 7.3.18

**Comment by ml94** [comment]
Same issue with fresh instalation too.

Operating system: Ubuntu 20.04
Web server: Nginx
Database: MariaDB
PHP version: 7.4.3
Nextcloud Version: 19.0.0

**Comment by returntrip** [comment]
This issue happens for me systematically when refreshing/fetching articles from the Nextcloud News for Android:

[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/html/lib/private/Session/Internal.php#209

PUT /index.php/apps/news/api/v1-2/items/read/multiple?
from 10.0.1.1 at 2020-06-08T11:31:16+00:00

**Comment by returntrip** [comment]
This issue happens for me systematically when refreshing/fetching articles from the Nextcloud News for Android:

```
[PHP] Error: session_start(): A session had already been started - ignoring at /var/www/html/lib/private/Session/Internal.php#209

PUT /index.php/apps/news/api/v1-2/items/read/multiple?
from 10.0.1.1 at 2020-06-08T11:31:16+00:00
```

## System Information
* News app version: 14.1.11
* Nextcloud version: 19 (Docker)

**Comment by Rob3487** [comment]
> Same issue , fresh instalation , 19.0.0
> Ubuntu 20.04
> Apache 2.4.41
> PHP 7.3.18

In my case the behavior turned out to be a database connection issue. 
I no longer experience the error.

**Comment by Ruinenarr** [comment]
> > Same issue , fresh instalation , 19.0.0
> > Ubuntu 20.04
> > Apache 2.4.41
> > PHP 7.3.18
> 
> In my case the behavior turned out to be a database connection issue.
> I no longer experience the error.

How did you find the issue? Maybe it could solve it at other installation aswell.

**Comment by d0m1n1q0** [comment]
@Rob3487
No offense. Despite my language command, I can't figure out what you are talking about.
Let alone providing a solution.
Cheers

**Comment by LgWagon** [comment]
Same error here, Nextcloud 19.0.0, ubuntu 16.04.
Lg

**Comment by barzog** [comment]
Is there any news on that?

**Comment by steadybright** [comment]
Many occurrences of this error in my Nextcloud logfile:
session_start(): A session had already been started - ignoring at /usr/share/webapps/nextcloud/lib/private/Session/Internal.php#209

Here's my server configuration detail:
Server configuration detail

Operating system: Linux 5.7.2-arch1-1 #1 SMP PREEMPT Wed, 10 Jun 2020 20:36:24 +0000 x86_64

Webserver: nginx/1.19.0 (fpm-fcgi)

Database: mysql 10.4.13

PHP version: 7.4.7

Modules loaded: Core, date, libxml, openssl, pcre, zlib, ctype, dom, fileinfo, filter, hash, json, mbstring, pcntl, SPL, PDO, apcu, posix, readline, Reflection, session, SimpleXML, standard, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, bcmath, bz2, curl, exif, ftp, gd, gettext, gmp, iconv, imap, intl, mysqli, pdo_mysql, pdo_sqlite, pspell, snmp, sockets, sqlite3, tidy, xmlrpc, xsl, zip, apc, Phar, geoip, igbinary, imagick, pam, redis, smbclient, libsmbclient, Zend OPcache

Nextcloud version: 19.0.0 - 19.0.0.12

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - apporder: 0.10.0
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.2
 - extract: 1.2.4
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_external: 1.10.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - nextcloud_announcements: 1.8.0
 - notes: 3.5.1
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - richdocuments: 3.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - support: 1.2.1
 - survey_client: 1.7.0
 - suspicious_login: 3.1.0
 - systemtags: 1.9.0
 - tasks: 0.13.1
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_totp: 4.1.3
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - encryption
 - files_markdown
 - user_ldap



</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nc.icfll.com"
    ],
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "dbindex": 0,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "19.0.0.12",
    "overwrite.cli.url": "https:\/\/nc.icfll.com",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "3306",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "log_type": "file",
    "logfile": "\/var\/log\/nextcloud-error.log",
    "loglevel": 3,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "theme": "",
    "app_install_overwrite": [
        "files_rightclick",
        "files_reader"
    ]
}


</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured


</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.97 Safari/537.36 Edg/83.0.478.45

**Comment by HolgerHees** [comment]
for me the same happens.

maybe it is an API related problem. It happens for me for the news and the notes native app.

means the web version works fine, but if I start the android apps I get this error.

btw. the native nextcloud app works without any error.

**Comment by d0m1n1q0** [comment]
> btw. the native nextcloud app works without any error.

**Comment by d0m1n1q0** [comment]
That’s because the app does not log-out

**Comment by HolgerHees** [comment]
what you mean with logout.

normally you call session_start to create a new session or to resume a session based on submitted session id and you do this on every request.

Why should a app log-out for every new request?

**Comment by d0m1n1q0** [comment]
Try the following.

Do not logout.
Kill your browser whilst logged-in.
Log-in again
There is no error recorded.

Which is similar to closing the mobile app.

**Comment by HolgerHees** [comment]
I debugged it a little bit more.

**Comment by acsfer** [comment]
@HolgerHees thanks, can you make a PR about this for reviewing?

**Comment by Dellyjoe** [comment]
Hello Everyone, 

Why is this still open if a fix has been made. I ended up using @HolgerHees Fix when looking at Internal.php and it seems to be working"?

Is this a temp fix? and the community as a whole are looking  into a more permit fix?

Thank you for reading,
Joe

**Comment by acsfer** [comment]
@Dellyjoe https://github.com/nextcloud/server/pull/22243 is the right fix.

**Comment by yan12125** [comment]
The fix  #22243 seems not working on PHP 8. See #25807

**Comment by debaba** [comment]
Stiil having the same.
Running Nextcloud 21.0.1.1
Latest patch level
Major version still supported
Scanned at 2021-04-15 13:53:18

**Comment by osm-frasch** [comment]
I probably have the same problem. However, only in Firefox (currently 121)
After I log out of the Password app, I can no longer access the administration settings, the dashboard and the user account administration. (Internal server error, the server could not complete the request).

I have opened Chrome in parallel and am also logged into Nextcloud there. There I can access all apps and the settings without a server error

(Nextcloud: 27.1.5, PhP: 8.1)

**Comment by joshtrichards** [comment]
@osm-frasch Can you open a dedicated issue with your full details? This issue has been closed for several years so it's likely that - even if related - it's an independent issue. That said, if you're getting a internal server error, your `nextcloud.log` will have further details. You may also wish to post at the Nextcloud Help Forum - https://help.nextcloud.com
