### ISSUE TITLE
Unable to edit users existing since several years

### ISSUE THREAD

**Issue by pauleve** [nextcloud/server#20498]
### Steps to reproduce
Edit avatar, name, or email of an user created several years ago

### Expected behaviour
Edit gets applied

### Actual behaviour
For users created years ago, nothing change.
The log output several errors related to undefined indexes and missing properties

## Server configuration detail

**Operating system:** Linux 5.5.11-linux-hardened-a #1 SMP Sat Mar 21 16:41:05 CET 2020 x86_64

**Webserver:** nginx/1.16.1 (fpm-fcgi)

**Database:** pgsql PostgreSQL 12.2 on x86_64-pc-linux-gnu, compiled by x86_64-pc-linux-gnu-gcc (Gentoo Hardened 9.2.0-r2 p3) 9.2.0, 64-bit

**PHP version:** 

7.4.4
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bz2, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, mysqli, PDO, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, Reflection, imap, SimpleXML, soap, sockets, exif, tokenizer, xml, xmlreader, xmlrpc, xmlwriter, zip, cgi-fcgi, Zend OPcache

**Nextcloud version:** 18.0.3 - 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** gentoo packages

<details><summary>Signing status</summary>

Array
(
    [files_rightclick] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [README.md] => Array
                        (
                            [expected] => 
                            [current] => 008148d723136644c2542312557ed5b9db1af5de6797a221d221012ae0ad367b2daca4774bcaba8936ec8394093b83c3e3f2d8e7c52e5f5882e28579dffe99e2
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - calendar: 2.0.3
 - cloud_federation_api: 1.1.0
 - cookbook: 0.6.3
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_videoplayer: 1.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - oauth2: 1.6.0
 - passwords: 2020.4.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - settings: 1.0.0
 - support: 1.1.0
 - text: 2.0.0
 - twofactor_backupcodes: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - activity
 - admin_audit
 - comments
 - deck
 - encryption
 - federation
 - files_versions
 - firstrunwizard
 - nextcloud_announcements
 - notifications
 - password_policy
 - serverinfo
 - sharebymail
 - spreed
 - survey_client
 - systemtags
 - theming
 - updatenotification
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "pgsql",
    "version": "18.0.3.0",
    "installedat": "1334771854.9147",
    "lastupdatedat": "1335649658.425",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "loglevel": 0,
    "forcessl": true,
    "theme": "",
    "trusted_domains": [
        "inzenet.org",
        "loicpauleve.name"
    ],
    "mail_smtpmode": "smtp",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/cloud",
    "overwrite.cli.url": "https:\/\/inzenet.org\/cloud",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** no

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
Error	index	OCP\Accounts\PropertyDoesNotExistException: Property avatar does not exist.	
2020-04-15T12:22:34+0200
Error	PHP	Trying to access array offset on value of type null at /var/www/localhost/htdocs/nextcloud/apps/settings/lib/Settings/Personal/PersonalInfo.php#142	
2020-04-15T12:22:33+0200
Error	PHP	Undefined index: twitter at /var/www/localhost/htdocs/nextcloud/apps/settings/lib/Settings/Personal/PersonalInfo.php#120	
2020-04-15T12:22:33+0200
Error	PHP	Trying to access array offset on value of type null at /var/www/localhost/htdocs/nextcloud/apps/settings/lib/Settings/Personal/PersonalInfo.php#141
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by kesselb** [comment]
Make sense :+1: 

A workaround could be to remove all rows from the accounts table for the given uid. I don't know if some of those information important. Have a backup as always.

Advanced solution is to check what fields are missing for the account and add them with some default values. A typed UserDataObject might be cleaner than the array currently used.

**Comment by pauleve** [comment]
The data column of these old users is '{}'. Doing
```
delete from accounts where data = '{}';
```
fixed the issue, thank you very much!
