### ISSUE TITLE
File Scan not possible if nextcloud is in maintenance mode

### ISSUE THREAD

**Issue by soccermax215** [nextcloud/server#20515]
### Steps to reproduce
1. Put nextcloud in maintenance mode
2. try to start files scan `sudo -u www-data php occ files:scan`

### Expected behaviour
- files scan should be possible if nextcloud is in maintenance mode
- as it's currently not possible to do so, an appropriate error message should be displayed
- there should be a piece of information about this behavior in the documentation of occ

### Actual behaviour
- error message if you start a files scan in maintenance mode: ` There are no commands defined in the "files" namespace.`

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:**: Apache/2.4.29 (Ubuntu)

**PHP version:** PHP 7.3.16-

**Nextcloud version:** latest - 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from owncloud, OC 10->NC 12->13->14->15->16->17->18

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/latest-18.tar.bz2

**Comment by Fluxenator** [comment]
Same issue here.

Operating System: Ubuntu 20.04

NC version: 18.0.8

**Comment by drewjosh** [comment]
Same problem but with Nextcloud 20.0.6 without being in the maintenance mode.

**Comment by pelMEN** [comment]
same problem 20.8
start scan then send serv to maintenance mode.
