### ISSUE TITLE
Cannot upload/move/copy to Minio b2 gateway (The specified bucket does not exist)

### ISSUE THREAD

**Issue by much-doge** [nextcloud/server#20521]
Hey, I have been having problem integrating b2 into my Nextcloud, I finally figured out how to access my b2 files from Nextcloud by using Minio as the gateway to translate b2 into s3, however I could not upload/move/copy file(s) to Minio b2 gateway. **File deletion works tho**, new document and folder creation also work, but I cannot open or edit the document.

### Steps to reproduce
1. Configure Minio as a b2 gateway to access backblaze b2
2. Connect Minio b2 gateway as external s3 storage in Nextcloud
3. Try to upload file

### Expected behaviour
The file should be uploaded succesfully

### Actual behaviour
It didn't. This error showed up:

> [webdav] Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://my.nextcloud.site/nextcloud-at-backblaze/til.jpg?uploadId=4_zc86e0f856a5bf40d6afc011d_f2062c4b0259be743_d20200416_m135517_c000_v0001028_t0041"; AWS HTTP error: Client error: POST https://minio.gateway.site/nextcloud-at-backblaze/til.jpg?uploadId=4_zc86e0f856a5bf40d6afc011d_f2062c4b0259be743_d20200416_m135517_c000_v0001028_t0041 resulted in a 404 Not Found response:
> 
> NoSuchBucketThe specified bucket does not exist</Mes (truncated...)
> NoSuchBucket (client): The specified bucket does not exist -
> NoSuchBucketThe specified bucket does not existtil.jpgnextcloud-at-backblaze/nextcloud-at-backblaze/til.jpg1606514F429DBAFB25827a70-3301-418d-87dc-de883bc3278e at <>
> 
>     /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 243
>     OCA\DAV\Connector\Sabre\File->convertToSabreException(Aws\S3\Exception ... {})
>     /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
>     OCA\DAV\Connector\Sabre\File->put(null)
>     /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
>     OCA\DAV\Connector\Sabre\Directory->createFile("til.jpg", null)
>     /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
>     Sabre\DAV\Server->createFile("minio/til.jpg", null, null)
>     <>
>     Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
>     /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
>     undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
>     /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
>     Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
>     /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
>     Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
>     /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
>     Sabre\DAV\Server->exec()
>     /var/www/nextcloud/remote.php line 163
>     undefinedundefinedrequire_once("/var/www/nextcl ... p")
> 
> PUT /remote.php/webdav/minio/til.jpg
> from MY IP by MY NEXTCLOUD ACCOUNT at 2020-04-16T13:55:20+00:00
> 

### Server configuration

**Operating system:**
Debian Buster
**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
PHP 7.3
**Nextcloud version:** (see Nextcloud admin page)
17.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 17.0.3, the fresh install was 17.0.2
**Where did you install Nextcloud from:**
The official download link
**Signing status:**
<details>
<summary>Signing status</summary>
```
```No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.3.0
  - activity: 2.10.1
  - admin_audit: 1.7.0
  - analytics: 2.2.1
  - announcementcenter: 3.6.1
  - apporder: 0.9.0
  - audioplayer: 2.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.3
  - checksum: 0.4.4
  - cloud_federation_api: 1.0.0
  - comments: 1.7.0
  - contacts: 3.2.0
  - dashboardcharts: 0.1.3
  - dav: 1.13.0
  - deck: 0.8.2
  - drawio: 0.9.5
  - dropit: 0.4.0
  - encryption: 2.5.0
  - external: 3.4.1
  - extract: 1.2.3
  - federatedfilesharing: 1.7.0
  - federation: 1.7.0
  - files: 1.12.0
  - files_accesscontrol: 1.7.0
  - files_antivirus: 2.3.0
  - files_automatedtagging: 1.7.0
  - files_downloadactivity: 1.6.0
  - files_external: 1.8.0
  - files_frommail: 0.3.1
  - files_fulltextsearch: 1.3.7
  - files_markdown: 2.2.0
  - files_mindmap: 0.0.21
  - files_readmemd: 1.1.4
  - files_rightclick: 0.15.1
  - files_sharing: 1.9.0
  - files_trackdownloads: 1.6.0
  - files_trashbin: 1.7.0
  - files_versions: 1.10.0
  - files_videoplayer: 1.6.0
  - firstrunwizard: 2.6.0
  - gallery: 18.4.0
  - gpxmotion: 0.0.11
  - gpxpod: 4.2.1
  - groupquota: 0.1.2
  - guests: 1.3.1
  - logreader: 2.2.0
  - lookup_server_connector: 1.5.0
  - mail: 1.3.0
  - maps: 0.1.6
  - metadata: 0.11.1
  - music: 0.13.2
  - news: 14.1.3
  - nextcloud_announcements: 1.6.0
  - notes: 3.2.0
  - notifications: 2.5.0
  - oauth2: 1.5.0
  - ocdownloader: 1.7.5
  - ocr: 6.0.30
  - onlyoffice: 4.1.4
  - passman: 2.3.5
  - password_policy: 1.7.0
  - phonetrack: 0.6.2
  - piwik: 0.5.4
  - privacy: 1.1.0
  - provisioning_api: 1.7.0
  - quota_warning: 1.6.0
  - ransomware_detection: 0.6.0
  - ransomware_protection: 1.5.2
  - recommendations: 0.5.0
  - registration: 0.4.7
  - serverinfo: 1.7.0
  - sharebymail: 1.7.0
  - sharepoint: 1.5.0
  - sociallogin: 2.4.5
  - socialsharing_email: 1.0.6
  - socialsharing_twitter: 1.0.5
  - support: 1.0.1
  - survey_client: 1.5.0
  - suspicious_login: 3.1.0
  - systemtags: 1.7.0
  - tasks: 0.12.1
  - terms_of_service: 1.3.1
  - text: 1.1.1
  - theming: 1.8.0
  - theming_customcss: 1.5.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.6.0
  - twofactor_gateway: 0.15.1
  - twofactor_totp: 4.1.3
  - unsplash: 1.1.5
  - updatenotification: 1.7.0
  - user_usage_report: 1.1.2
  - video_converter: 0.1.3
  - viewer: 1.2.0
  - workflowengine: 1.7.0
Disabled:
  - files_pdfviewer
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***MY SITE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "17.0.5.0",
        "overwrite.cli.url": "https:\/\/my.nextcloud.site",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "filelocking.enabled": true,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "maintenance": false,
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "theme": "",
        "loglevel": 2,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, s3 and my other nextcloud instance
**Are you using encryption:** yes/no
Yes. it is disabled tho.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Logs
#### Web server error log
<details>
<summary>Web server error log</summary>

```

[webdav] Fatal: Sabre\DAV\Exception: An exception occurred while completing a multipart upload: Error executing "CompleteMultipartUpload" on "https://my.nextcloud.site/nextcloud-at-backblaze/til.jpg?uploadId=4_zc86e0f856a5bf40d6afc011d_f2062c4b0259be743_d20200416_m135517_c000_v0001028_t0041"; AWS HTTP error: Client error: POST https://minio.gateway.site/nextcloud-at-backblaze/til.jpg?uploadId=4_zc86e0f856a5bf40d6afc011d_f2062c4b0259be743_d20200416_m135517_c000_v0001028_t0041 resulted in a 404 Not Found response:

NoSuchBucketThe specified bucket does not exist</Mes (truncated...)
NoSuchBucket (client): The specified bucket does not exist -
NoSuchBucketThe specified bucket does not existtil.jpgnextcloud-at-backblaze/nextcloud-at-backblaze/til.jpg1606514F429DBAFB25827a70-3301-418d-87dc-de883bc3278e at <>

    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 243
    OCA\DAV\Connector\Sabre\File->convertToSabreException(Aws\S3\Exception ... {})
    /var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php line 156
    OCA\DAV\Connector\Sabre\File->put(null)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1096
    OCA\DAV\Connector\Sabre\Directory->createFile("til.jpg", null)
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 525
    Sabre\DAV\Server->createFile("minio/til.jpg", null, null)
    <>
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
    /var/www/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    undefinedundefinedcall_user_func_array([Sabre\DAV\CorePlugin {},"httpPut"], [Sabre\HTTP\Requ ... }])
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:PUT", [Sabre\HTTP\Requ ... }])
    /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
    /var/www/nextcloud/apps/dav/appinfo/v1/webdav.php line 80
    Sabre\DAV\Server->exec()
    /var/www/nextcloud/remote.php line 163
    undefinedundefinedrequire_once("/var/www/nextcl ... p")

PUT /remote.php/webdav/minio/til.jpg
from MY IP by MY NEXTCLOUD ACCOUNT at 2020-04-16T13:55:20+00:00
```
</details>

Related issues: 
https://github.com/nextcloud/server/issues/13808#issue-402973021
https://github.com/nextcloud/server/issues/13808#issue-402973021

**Comment by much-doge** [comment]
One thing I notice is that in my Minio gateway site the url looks like this: https://minio.gateway.site/**minio**/the-bucket/

Whereas in Nextcloud multipart upload it tries to do the operation at https://minio.gateway.site/the-bucket

and thus results in 404.

**Comment by asoltesz** [comment]
I have the same issue. 

Listing files, downloading and deleting works through my Minio server (working as a gateway to B2).

However, I cannot upload files via Nextcloud 17 or create a text file in the folder/bucket.

I can upload files on the Minio web interface and those are stored properly in B2 so I thought maybe there is an issue in how Nextcloud handles the S3 protocol.

**Comment by much-doge** [comment]
Backblaze added S3 compatible API just yesterday, I will try this out. This can't be used on the old bucket made before 4th May 2020 though, so it might not be a final solution to the people who got terabytes of data in their old bucket. 

https://www.backblaze.com/blog/backblaze-b2-s3-compatible-api/
