### ISSUE TITLE
File Not Found on Shared Limk when shared by non-owning user

### ISSUE THREAD

**Issue by Megatherium** [nextcloud/server#20522]
Steps to reproduce:

1. Let user A share a file with group X
2. Create shared link with user b (from group x)
3. Download file via link

Results:
Nextcloud 17: File can be downloaded
Nextcloud 18: File not found

If the link is created by the owning user you get a 'user blocked' message (which is sensible I guess to prevent post-termination data exfiltration)

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
