### ISSUE TITLE
Add postLoginFailed UserHooks orEvent

### ISSUE THREAD

**Issue by citronbleuv** [nextcloud/server#20526]
Is it possible to have an supplementary hook on UserHooks => postLoginFailed(string $user, string $password) ? (or an event)
I need to send a mail after x attempts.

At the moment I use a method no beautifful with BackgroundJob or preLogin to check that.

**Comment by kesselb** [comment]
For Nextcloud 19: https://github.com/nextcloud/server/pull/19845
