### ISSUE TITLE
Share expiration date not shown

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#20520]
### Steps to reproduce
1. Share a file (doesn't matter if link, internal, group or email)
2. set an expiration date by date picker

### Expected behaviour
- Expiration date is shown in date field
- Expiration date has been written to the database (oc_share.expiration)

### Actual behaviour
Date has been written to the DB, but doesn't appear on the UI

### Server configuration

NC 19.0.0 Beta4

**Comment by gary-kim** [comment]
Seems to be an upstream issue in `nextcloud-vue`. Making a fix
