### ISSUE TITLE
Sharing menu does not find group if name is the same as current user

### ISSUE THREAD

**Issue by michaelschefczyk** [nextcloud/server#20525]
### Steps to reproduce
1. Create user of any name, e.g., "DMS"
2. Create group of the same name as user, e.g., "DMS"
3. Login as user "DMS" and try to share with group "DMS"

### Expected behaviour
A group is likely to contain multiple users. There should be no restriction against assigning one name to a group and one of its users simultaneously - symbols do distinguish this from the viewpoint of the human user of the system. Then, it should still be possible for the user to share folders and files with the group bearing the same name as the very user.

### Actual behaviour
We have a generic central user named DMS. This user created most folders then shared with others. In addition, we used to have a group called DMS as well. This group used to share folders created by DMS with a few other admin users.

From some point in time - maybe since upgrading to mextcloud 18 - this was no longer possible. The search available in the sharing menu does not find the user name of the active user - which might be OK. However, this leads to the search menu also not finding a group of an identical name – probably without intention. Our workaround was to delete the group DMS and replace it by a group bearing another name (DokMS in our case). This was inconvenient. This setting used to work for years. It is then difficult to determine why it might have suddenly stopped.

Just to check, I did create a group DMS again later. This led to the same problem. Before removing the historical group DMS and its share associations, they would still exist, but not visible as "Others with access". I gather that these are all reflections of the same issue.

### Server configuration

Operating system: Debian 10.3

Web server: Apache/2.4.38 (Debian)

Database: mysql  Ver 8.0.19-10 for debian-linux-gnu on x86_64 (Percona Server (GPL), Release '10', Revision 'f446c04')

PHP version: PHP 7.3.14-1~deb10u1

Nextcloud version: 18.0.3

**Comment by skjnldsv** [comment]
Hi!
I will need a screenshot of your network requests.
Before you do anything, still on the development tools, there is a tab called `network`. Click on it and then the xhr filter. Do your action and screenshot the network log like this:
![capture d ecran_2018-09-27_21-49-46](https://user-images.githubusercontent.com/14975046/46170857-43548000-c29f-11e8-9403-db72713dd9c1.png)

You will see a request named `sharees?format...`, click on it, select the response tab, and copy/paste the content here please.

**Comment by michaelschefczyk** [comment]
Dear skjnldsv,

Thank you very much!

The response does look like:

{"ocs":{"meta":{"status":"ok","statuscode":100,"message":"OK","totalitems":"","itemsperpage":""},"data":{"exact":{"users":[{"count":2,"label":"......","value":{"shareType":0,"shareWith":"......"}},{"count":2,"label":"......","value":{"shareType":0,"shareWith":"......"}}],"groups":[{"count":50,"label":"DokMS","value":{"shareType":1,"shareWith":"DokMS"}},{"count":2,"label":"......","value":{"shareType":1,"shareWith":"......"}},{"count":2,"label":"......","value":{"shareType":1,"shareWith":"......"}}],"remotes":[],"remote_groups":[],"emails":[]},"users":[],"groups":[],"remotes":[],"remote_groups":[],"emails":[]}}}

Six dots are real users from the list of recent sharing activity. I could only share a version without shortening for privacy if I knew how to hide the recent activity. Alternatively, I would probably need to create a test user. The DokMS is an example of a real group. If my user DMS would search for group DMS, this would not be in the list. Please find the screenshot below.

Regards,

Michael

![Bild](https://user-images.githubusercontent.com/5464672/79849603-f83f1800-83c2-11ea-9cdf-948a13425bf7.jpg)
