### ISSUE TITLE
File details (e.g. GPX distance) in file overview

### ISSUE THREAD

**Issue by smaugilein** [nextcloud/server#20534]
I would like to get more details about the files in the file overview. For example, I would be interested in the recorded track of a GPX file, maybe the image dimensions of a JPG, etc.

GIMP example ;-)
![gpx_example](https://user-images.githubusercontent.com/63549111/79567448-8c07a000-80b4-11ea-8acb-925cc52f6775.png)

**Comment by szaimen** [comment]
Please have a look at the metadata app: https://apps.nextcloud.com/apps/metadata
