### ISSUE TITLE
getInstanceId returns empty string

### ISSUE THREAD

**Issue by KatjaD-CH** [nextcloud/server#20543]
Affected file: `../nextcloud/lib/private/legacy/util.php`

On my fresh, yet not working, Nextcloud installation `\OC::$server->getSystemConfig()->getValue('instanceid', null)` returns an empty string. That empty string doesn't trigger the test with `is_null`.
```
public static function getInstanceId() {
		$id = \OC::$server->getSystemConfig()->getValue('instanceid', null);
		if (is_null($id)) {
			// We need to guarantee at least one letter in instanceid so it can be used as the session_name
			$id = 'oc' . \OC::$server->getSecureRandom()->generate(10, \OCP\Security\ISecureRandom::CHAR_LOWER.\OCP\Security\ISecureRandom::CHAR_DIGITS);
			\OC::$server->getSystemConfig()->setValue('instanceid', $id);
		}
		return $id;
	}
```
At the moment I've change the code to: `if (is_null($id) or empty($id)) {`

System: Ubuntu Bionic Beaver 18.04 LTS i386
Server: nginx
PHP: 7.2
DB: mysql
Version: nextcloud-18.0.3.tar.bz2
Location: /var/www/html/nextcloud

**Comment by kesselb** [comment]
If `instanceid` is a empty string something in your setup is broken. You probably copied the config.sample.php to config.php which you are not supposed to do.

**Comment by KatjaD-CH** [comment]
Indeed I did copy the sample config, now I'm a step further. Thank you for the hint.

However, I think that my report is still valid. Even though the error normally does not occur, the code does not serve its purpose for all possible return values of `\OC::$server->getSystemConfig()->getValue('instanceid', null)`.

I personally would change the code anyway.

**Comment by kesselb** [comment]
The code does exactly what it is supposed to do. If `instanceid` is null generate one.

**Comment by kesselb** [comment]
cc @nextcloud/server-triage

**Comment by blizzz** [comment]
> The code does exactly what it is supposed to do. If `instanceid` is null generate one.

I agree here. Having an empty instanceid is not what should normally occur, I don't think blindly creating a new `instanceid` is a good idea.
