### ISSUE TITLE
feature request: get notification when shared link is opened

### ISSUE THREAD

**Issue by IVI-I** [nextcloud/server#20542]
I think the monitor/tracking features of Nextcloud really miss an important one, which is the **notification of accessed shared files / links**.

Whenever a file is downloaded I can get notified but most of the time the recipient only views the document and therefore I have no idea of when the document is seen or if it is seen at all. 

I really would look forward to a function that gives me insights on when the link was accessed and optionally also by what IP and for how long the page was open. 

There seems to be no addon available for that. Would that be something of interest for you guys?

**Comment by IVI-I** [comment]
![2020-04-17_183320](https://user-images.githubusercontent.com/40261714/79592251-05fe5000-80da-11ea-8987-82c6579f1655.png)

it could look something like the above in the activity section and be included in the notification bar like this

![2020-04-17_183634](https://user-images.githubusercontent.com/40261714/79592582-760cd600-80da-11ea-8db4-6ea20f003fc4.png)

**Comment by szaimen** [comment]
Currently, activities for opening files that are shared via link/mail are the same like downloading. So this is already covered when you activate:
![image](https://user-images.githubusercontent.com/42591237/120196565-478b8500-c220-11eb-9c58-0eb80f594fdf.png)
