### ISSUE TITLE
Notifications on uploads or modifications to shared folders

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/server#20565]
I just had a thought: I shared a link on my Nextcloud instance and I would like to be notified, when someone finally decides to upload something there. Is there any way of doing it and if not, can someone think of implementing this. Cheers.

**Comment by kbacia7** [comment]
Hello, I start work on this issue, if it isn't problem but I don't push any local changes to origin yet

**Comment by Nils160988** [comment]
Just retried and works as expected: Set your activity notifications accordingly and notifications are sent if someone uploads a file in a shared folder.
Does it work for you?

**Comment by alexbijma** [comment]
@Nils160988 what notification is being triggered by this action?
i think may'be it could work with Flow but therefor a new trigger like "new file" or "file has changed" needs to be developed i guess

**Comment by szaimen** [comment]
> Hello, I start work on this issue, if it isn't problem but I don't push any local changes to origin yet

Hi @kbacia7 do you still have your work somewhere and could create a PR? Thank you! :)

**Comment by kbacia7** [comment]
> > Hello, I start work on this issue, if it isn't problem but I don't push any local changes to origin yet
> 
> Hi @kbacia7 do you still have your work somewhere and could create a PR? Thank you! :)

No, I completely forgot about it and I did something else. I'm not working on it, I'm sorry that I forgot update comment here.

**Comment by brendan-pike** [comment]
Seems the logical place would be in personal Settings / Notifications with a new row called "A file or folder has been created"
However I think many people are interested in this because they want to be alerted to anonymous uploads in particular.
There is an app which may of some reusable parts https://github.com/RCOSDP/nextcloud-file_upload_notification

**Comment by pierreozoux** [comment]
Actually, I just tried, and it worked:

Configure the activity as follow:

![Screenshot from 2022-05-11 13-31-55](https://user-images.githubusercontent.com/1863453/167840048-e25a1ed6-5555-482d-8053-2e42e28ef154.png)

Upload a file to your folder that is a file drop, wait some minutes, and you'll receive an email \o/

I'll close this issue then!

**Comment by brendan-pike** [comment]
This is a very broad brush however, picture a system with dozens of users and you want to allow clients to upload files, and you need to know when it occurs.  You'll spend your day constantly sifting through irrelevant alerts in case there is an important one there.

**Comment by pierreozoux** [comment]
@brendan-pike then follow this issue 
https://github.com/nextcloud/activity/issues/271

:upside_down_face: 

Cheers!
