### ISSUE TITLE
Unknown error when uploading into a shared folder on external storage

### ISSUE THREAD

**Issue by meddie77** [nextcloud/server#20566]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. set up en external storage using a windows share via smb/vifs
2. create a folder via nextcloud on the external storage
3. share this folder with a link. set this link as upload folder
4. Open the share with this link and upload a file (dont matter filetype or size)

### Expected behaviour
the user should be able to upload a file or folder without getting an error. After uploading the file, it should be shown in the browser

### Actual behaviour
After uploading the file in the right upper corner the guest see an error ballon "unknown error" after that the file is not appearing. Only when the guest refresh the GUI the file will be shown.
Same behavier when the geust try to rename the file. 
Deleting the file is not possible,  

### Server configuration

**Operating system:** Ubuntu 16.0.4.6 LTS

**Web server:** apache

**Database:** postgresql 10.12

**PHP version:** 7.3.16

**Nextcloud version:** (see Nextcloud admin page) 18.0.3.0

**Updated from an older Nextcloud/ownCloud or fresh install:** i have more installations, one of them is new installed, but all the installations has exactly the same behavior. 

**Where did you install Nextcloud from:** HansonIT

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... yes

**Are you using encryption:** yes/no no

**Are you using an external user-backend, if yes which one:** LDAP.

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
Error: Call to a member function getUID() on null
/usr/lib/nextcloud/apps/activity/lib/FilesHooks.php - line 638:
OC\Files\View->getOwner("/Eigene Dat ... f")
/usr/lib/nextcloud/apps/activity/lib/FilesHooks.php - line 190:
OCA\Activity\FilesHooks->getSourcePathAndOwner("/Eigene Dat ... f")
/usr/lib/nextcloud/apps/activity/lib/FilesHooks.php - line 148:
OCA\Activity\FilesHooks->addNotificationsForFileAction("/Eigene Dat ... f", "file_created", "", "created_public")
/usr/lib/nextcloud/apps/activity/lib/FilesHooksStatic.php - line 47:
OCA\Activity\FilesHooks->fileCreate("/Eigene Dat ... f")
/usr/lib/nextcloud/lib/private/legacy/hook.php - line 111:
OCA\Activity\FilesHooksStatic::fileCreate({ path: "/Ei ... "})
/usr/lib/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 389:
OC_Hook::emit("OC_Filesystem", "post_create", { path: "/Ei ... "})
/usr/lib/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 321:
OCA\DAV\Connector\Sabre\File->emitPostHooks(false)
/usr/lib/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php - line 156:
OCA\DAV\Connector\Sabre\File->put(null)
/usr/lib/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1096:
OCA\DAV\Connector\Sabre\Directory->createFile("Übung Prepositions.pdf", null)
/usr/lib/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 525:
Sabre\DAV\Server->createFile("Woche vom 2 ... f", null, null)
<<closure>>
Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})
/usr/lib/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105:
call_user_func_array([ Sabre\DAV\ ... "], [ Sabre\HTTP ... }])
/usr/lib/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479:
Sabre\Event\EventEmitter->emit("method:PUT", [ Sabre\HTTP ... }])
/usr/lib/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254:
Sabre\DAV\Server->invokeMethod(Sabre\HTTP\R ... "}, Sabre\HTTP\Response {})
/usr/lib/nextcloud/apps/dav/appinfo/v1/publicwebdav.php - line 109:
Sabre\DAV\Server->exec()
/usr/lib/nextcloud/public.php - line 81:
require_once("/usr/lib/ne ... p")
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Looks like a duplicate of https://github.com/nextcloud/activity/issues/439

**Comment by meddie77** [comment]
yes sorry, i found an issue but this was already closed but not solved, so i decided to open a new one. I close this issue and hope that the other one will be solved.
