### ISSUE TITLE
Font size for generated avatars is too big

### ISSUE THREAD

**Issue by mario** [nextcloud/server#20585]
Since we now have two letters in generated avatars the size of the font is simply too big, at least for mobile devices. Please considering lowering the size of the font.

**Comment by szaimen** [comment]
Actually, I think the font size looks quite okay or was this already changed?
![image](https://user-images.githubusercontent.com/42591237/120198236-2d52a680-c222-11eb-9f34-790eed0fe7a6.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers
