### ISSUE TITLE
Calendar invites: The invitation mail should not contain the nextcloud instance name in the "From"-field

### ISSUE THREAD

**Issue by steppy** [nextcloud/server#20601]
**Is your feature request related to a problem? Please describe.**

When a new appointment is set up via the calendar app or through an external calendar, nextcloud sends an invitation to all attendees. The sender of the mail is shown like this:
"Max Muster via Nextcloud"

"Max Muster" is the name of the nextcloud user that sent the invitation.
"Nextcloud" is the name of the nextcloud instance.

I had cases where people where irritated or considered this mail as spam because they never heard of nextcloud. The fact that there is a nextcloud server in the background is not important to the attendees. Renaming the nextcloud instance does not improve the situation.

**Describe the solution you'd like**

The sender of the invitation should just be the name the user.

**Describe alternatives you've considered**
It would be even more flexible if this could be configurable.

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/server/issues/12391
