### ISSUE TITLE
Transfer-ownership - missing \OCP\Share::SHARE_TYPE_EMAIL in collectUsersShares in apps/files/lib/Service/OwnershipTransferService.php

### ISSUE THREAD

**Issue by ruppo68** [nextcloud/server#20609]
Nextcloud Version 18.0.3.

The OCC command transfer-ownership failes in restoring shares if the Share Type Email was used.

In apps/files/lib/Service/OwnershipTransferService.php please add the missing Share_Type

        private function collectUsersShares(string $sourceUid,
                                                                                OutputInterface $output): array {
                $output->writeln("Collecting all share information for files and folders of $sourceUid ...");

                $shares = [];
                $progress = new ProgressBar($output);
                foreach ([\OCP\Share::SHARE_TYPE_GROUP, \OCP\Share::SHARE_TYPE_USER, \OCP\Share::SHARE_TYPE_LINK, \OCP\Share::SHARE_TYPE_REMOTE, \OCP\Share::SHARE_TYPE_ROOM,  \OCP\Share::SHARE_TYPE_EMAIL] as $shareType) {

Thanks
Peter Rupp

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by ruppo68** [comment]
Issue is resolved.
