### ISSUE TITLE
Error opening DICOM file shared by link with 'Hide Download' enabled

### ISSUE THREAD

**Issue by raddrz** [nextcloud/server#20606]
Same issue as #19572 but for DICOM (.dcm) files viewed in DICOM viewer app.

### Steps to reproduce
1. 'Share link' folder containing DICOM (.dcm) files. Sample files attached for you to test:
[DICOM sample.zip](https://github.com/nextcloud/server/files/4519367/DICOM.sample.zip)

2. Select 'Hide Download' option
3. Share link

### Expected behaviour
DICOM viewer app opens DICOM file in browser

### Actual behaviour
"There is no available DICOM image to display". Error presumably due to DICOM viewer app not being able to download files in the background (note app works fine when 'Hide Download' is disabled).

### Server configuration

**Operating system:**  Linux 4.19.107-Unraid x86_64

**Web server:** nginx

**Database:** MariaDb 10.4.12 

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:**

**Comment by kesselb** [comment]
That should be fixed by #20032.

**Comment by raddrz** [comment]
Updated to 18.0.4 and indeed it has been fixed. Thank you.
