### ISSUE TITLE
New php dependencies?

### ISSUE THREAD

**Issue by Nils160988** [nextcloud/server#20600]
After upgrade from 19 beta 2 to 19 beta 4, admin warnings complain about missing php dependencies (bcmath and gmp). For beta 2, no warnings appeared.
bcmath is not mentioned in the documentation at all and gmp is only recommended in combination with sftp.
If this (new?) requirement is intended, it should be mentioned in the documentation or release notes. Maybe I just missed it, then it would be nice if someone can show me.

**Comment by kesselb** [comment]
cc @MorrisJobke @rullzer

**Comment by rullzer** [comment]
It is needed for the passwordless auth.
Adding it to the 19 docs is still on my todo

**Comment by Lars1963** [comment]
closing possible through https://github.com/nextcloud/documentation/pull/2040
