### ISSUE TITLE
Log Settings in Nextcloud 18 Invalid

### ISSUE THREAD

**Issue by pthoelken** [nextcloud/server#20610]
Hello Community, 

after I've setup the log-settings in config.php 

![image](https://user-images.githubusercontent.com/12643853/80068499-fb134780-853f-11ea-8515-5565c74d2f40.png)

I've got the following error: 

![image](https://user-images.githubusercontent.com/12643853/80068510-01a1bf00-8540-11ea-9f6a-9024c0e51fd5.png)
(which means Server setup check failed) and the /settings/admin/logging will not loading. 

I've got the information from your documentation site: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/logging_configuration.html?highlight=logging

**Comment by pthoelken** [comment]
Any response here?!

**Comment by j-ed** [comment]
This is the Nextcloud bug tracker only and NOT the Nextcloud help forum. You've already asked [this question](https://help.nextcloud.com/t/log-problematiken-in-config-php-file/80902) in the help forum and the problem hasn't finally been evaluated there. Why do you open an issue ticket in parallel here?

**Comment by pthoelken** [comment]
As you can see; I've reported this kind of problem some weeks ago.
