### ISSUE TITLE
Flat File view

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/server#20616]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
The NextCloud Android app's Instant Upload feature uploads images I'm different folders based on date; often when I'm using the NC Web UI, I want to deal with, multiple files/photos at a time, i.e. select a bunch and then delete them.

This becomes a headache when having to drill down through folders all the time to do so.

**Describe the solution you'd like**
There's already a button to toggle views between List view and Thumbnail (a.k.a. "Grid view"; it would be great to include a Flat File view to that as well, doing the normal Flat File view thing (list all files and folders at once, in the same view). Then we can just select whichever files we want to manage, in one view.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by tilllt** [comment]
I would LOVE to see this feature as well. It is very cumbersome to find a specific image in the cloud without it, especially givebn the EXTREMELEY rudimentary feature set of the "Photos" functionality in Nextcloud. In a "normal" Photo organisation tool, we could make collections / virtual folders and group pictures using those mechanisms, all that does not exist in NC (yet?)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
