### ISSUE TITLE
Group list is overlapping if you are part of too many groups

### ISSUE THREAD

**Issue by pavo976** [nextcloud/server#20623]
Hello.
<https://github.com/nextcloud/server/issues/18920> -> <https://github.com/nextcloud/server/pull/19533>

![nextcloud-groups](https://user-images.githubusercontent.com/2650700/80154788-fba3f080-85c8-11ea-86eb-f840a3927106.png)

**Nextcloud version:** 18.0.3 - 18.0.3.0
Install from [docker-compose](https://github.com/nextcloud/docker)

I need advice on how to fix this.

**Comment by kesselb** [comment]
cc @nextcloud/designers isn't that fixed already 🤔

**Comment by skjnldsv** [comment]
I think so.
@pavo976 can you try and clear your browser cache please?

**Comment by pavo976** [comment]
@skjnldsv - you are right

thanks!!
