### ISSUE TITLE
Nextcloud Federation shares cant cant be modified by external nextcloud server while haveing full acess.

### ISSUE THREAD

**Issue by wwwwiii** [nextcloud/server#20628]
Goodmorning,

Am faceing the following isseu.

I have 2 nextcloud servers that are connected with federated sharing. On the main server i deploy de shares to other nextcloud servers.

All the servers and user recieving the share have full access delete, modify execpt resharing.
The users on de nextcloud server that recieve the share are Azure users users connected with saml 2.0.

Even though those users have full acces they can delete files on the federated share. It counts for webgui and desktop client do difference.

Errors am recieving on desktop client;
Server replied ""500 internal server error to delete "https cloud..."

On de federated user that recieves the share from the main server i see the following errors coming by:

Error | files | Backends provided no user object for use@domainname.com/ |  

Fatal | webdav | OC\User\NoUserException: Backends provided no user object |   | 2020-04-24T09:41:47+0200
-- | -- | -- | -- | --

When doing an occ files:scan --all on de same server i see those things popping by:
Protocol negotiation failed: NT_status_Connection_reset

ON the main server where federated shares are located i can delete de folders without any problem.
Both server are freshly installed running ubuntu server 18 lts and running nginx newest nextcloud version

**Comment by wwwwiii** [comment]
Seems to be an nextcloud federation isseu and not sso related

**Comment by arjan-s** [comment]
I'm having the same issue on my federated share. Files can be uploaded, downloaded and modified, just not deleted.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by wwwwiii** [comment]
Not sure if it still is an issue. I made a manuel solution fo this. Ticket can be closed

**Comment by k00ni** [comment]
> I made a manuel solution fo this.

How did you solve it?

**Comment by wwwwiii** [comment]
@k00ni I ditched the whole federation stuff. And synced nextcloud to a smb folder with the client. After that i created a manuel service.
The second server was is the same netwerk as the smb share. on that server am using the external file share plugin.

**Comment by wwwwiii** [comment]
stable for for over a year bassicly

**Comment by wwwwiii** [comment]
is not meant the be used that way but if nextcloud doesnt come with a better solution. This wil be my way.

I have one main server like this and 2 member servers
