### ISSUE TITLE
Changelog on Nextcloud website is out of date

### ISSUE THREAD

**Issue by christefano** [nextcloud/server#20638]
Changelog on the Nextcloud website needs to be updated. It doesn’t yet list changes in the new 18.0.4 release: https://nextcloud.com/changelog/

**Comment by kesselb** [comment]
https://github.com/nextcloud/nextcloud.com would be the right repository

Changelog seems to be merged and should be available soon.

**Comment by christefano** [comment]
I just saw the changelog appear today. Thanks for pointing to the changelog in the repo! That was quite helpful. 

Is there a reason the website changelog isn’t updated more quickly prior to it immediately following a release? It seems odd to me that new versions are released without the corresponding web page being updated at the same time.

**Comment by kesselb** [comment]
> Is there a reason the website changelog isn’t updated more quickly prior to it immediately following a release?

I don't know. It seems to be technical issues with GitHub this time.
