### ISSUE TITLE
Custom folder-icons: still not possible for "folder-external.svg"

### ISSUE THREAD

**Issue by fuanegua** [nextcloud/server#20631]
In NC 18 custom external folder icons are still not working.
So custom icons in the theming directory are all displayed correctly except the external folder.
It is still used from the root directory and keeps the origin blue NC color:

<img width="300" alt="folder-external-black" src="https://user-images.githubusercontent.com/843542/80205945-cc729b00-862b-11ea-987e-66447ce7bbef.png">

<img width="300" alt="folder-external-lightblue" src="https://user-images.githubusercontent.com/843542/80206344-6e928300-862c-11ea-9687-79b826c57e88.png">

I think it must be a bug or am I wrong?

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by fuanegua** [comment]
Yes, it still exists.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by fuanegua** [comment]
With 25.0.2 was changed quite more. 
Now folder color and adress bar color is the theme color from the NC settings. Theme options and CSS are ignored.
Is there new code for it? I couldn’t find anything.

**Comment by szaimen** [comment]
Yes, you should be able to disable user theming in the admin theming settings

**Comment by fuanegua** [comment]
Yes, got it. Thanks. 
Unfortunately, it does not affect the colorized browser address bar. There, the color is still taken from the admin settings.
