### ISSUE TITLE
Multiple scripts not loaded in Firefox due to CSP header

### ISSUE THREAD

**Issue by Whissi** [nextcloud/server#20643]
### Steps to reproduce
1. Open https://demo1.nextcloud.com/ in Firefox (I tried v75.0 which is current at the moment)
2. Press F12 and go to Network tab
3. Reload ...

### Expected behaviour
All referenced resources should get loaded.

### Actual behaviour
Various scripts are getting blocked due to CSP:

![image](https://user-images.githubusercontent.com/729436/80258506-ad9ff300-8683-11ea-96f8-deea1944abb7.png)

I experienced the issue with my own Nextcloud instance (v18.0.4) but server details shouldn't matter like you can reproduce the problem in the official demo.

**Comment by kesselb** [comment]
https://bugzilla.mozilla.org/show_bug.cgi?id=1591807

I think that's still a bug in Firefox. Do you see the same with another browser?

**Comment by Whissi** [comment]
No, only in Firefox.

**Comment by kesselb** [comment]
Closing as Firefox issue. Afaik that is only happening with dev tools open. Find all the details in the mozilla bug report.

**Comment by Whissi** [comment]
Yes, this seems to be a Firefox issue. However, it always happens. It's **not** just failing when dev tools are opened. In other words: Nextcloud is currently broken for **all** Firefox users.

I solved this problem for my own instance by dropping entire CSP header from response which is of course not the best solution.

I recommend that you drop the rule causing the problem for Firefox for now until a fix has reached all Firefox users, including ESR.

**Comment by kesselb** [comment]
> Nextcloud is currently broken for all Firefox users.

Mind to elaborate?
