### ISSUE TITLE
Using calendar with SAML authentication does not work as expected

### ISSUE THREAD

**Issue by alx2317** [nextcloud/server#20646]
### Steps to reproduce
1. Enable SAML in the Nextcloud settings. Configure with desired IDP service. Verify SAML authentication works for normal user logins.
2. Setup calendar for user and obtain private CALDAV link
3. Attempt to add CALDAV link to calendar client - Thunderbird or Mobile CALDAV app.

### Expected behaviour
User should authenticate with the calendar app using their SAML/IDP credentials.  Calendar app should pass these into the Nextcloud core for authentication which "should" go to the IDP for verification and allow the user to access their calendar.

### Actual behaviour
Authentication fails - the calendar app collects the credentials but the SAML settings don't seem to take effect. Only 'local' Nextcloud user authentication works. 
As a work-around, users can add a new 'Calendar App' to their security configuration and use the specific key to authenticate.  This is a bit cumbersome as each device would need to be setup with a password as opposed to using the normal authentication mechanism for the user.

### Calendar app
**Calendar app version:** 2.0.3

**CalDAV-clients used:** Thunderbird Lightning

### Client configuration
**Browser:** Chrome 81

**Operating system:** Ubuntu 19.10, Windows 10

### Server configuration

**Operating system**: Debian 9

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3.11

**Nextcloud Version:** 18.03

**Updated from an older installed version or fresh install:**  Updated

**List of activated apps:**  
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 0.8.2
  - documentserver_community: 0.1.5
  - end_to_end_encryption: 1.4.0
  - event_update_notification: 1.0.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_accesscontrol: 1.8.1
  - files_antivirus: 2.3.0
  - files_fulltextsearch: 1.4.2
  - files_lock: 0.8.1
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - forms: 1.1.1
  - fulltextsearch: 1.4.1
  - groupfolders: 6.0.6
  - lookup_server_connector: 1.6.0
  - nextbackup: 20.4.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocr: 6.0.33
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - rainloop: 6.1.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - twofactor_admin: 2.1.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_email: 1.0.1
  - twofactor_gateway: 0.16.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - user_saml: 3.0.1
  - user_sql: 4.5.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED DOMAIN***",
            "***REMOVED IP***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/***REMOVED DOMAIN ***",
        "dbtype": "mysql",
        "version": "18.0.3.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "mytheme",
        "loglevel": 2,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.utf8mb4": true,
        "mail_sendmailmode": "smtp",
        "debug": false
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your instance's installation folder

or

Insert your config.php content here
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

#### Web server error log (e.g. /var/log/apache)
```
Insert your webserver log here
```

#### Log file (data/nextcloud.log)
```
Insert your nextcloud.log file here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

**Comment by kmille** [comment]
Can we reopen this? The problem still exists. We are using Keycloak as authentication backend. Authentication works in the browser if people are using /login. Android/Thunderbird get's a 401. If we reset the "local nextcloud" password with `occ user:resetpassword`, the Cal/CardDav login works. Username can be found with `occ user:list | grep`.
Why does Card/CaldDav authentication not work with third party authentication?

**Comment by szaimen** [comment]
Hi, please open a new issue about this with up-to-date information. Thanks!
