### ISSUE TITLE
Changelog in releases

### ISSUE THREAD

**Issue by NoxInmortus** [nextcloud/server#20645]
Hello,

I would like to ask for the changelogs to be displayed in the releases. This way, you can then have an auto-generated rss flux to auto receive the changes : https://github.com/nextcloud/server/releases.atom

It would be great.

**Comment by szaimen** [comment]
cc @nextcloud/infrastructure

**Comment by MorrisJobke** [comment]
We plan to do this sooner or later in that repository: https://github.com/nextcloud-releases/server

We can't do it in here as all of our maintainers would have access to it. Therefore we planned to do it in the separate org and fully automated. Still some steps to go, but we are heading there. I will nevertheless close it here.
