### ISSUE TITLE
Custom email templates no longer work

### ISSUE THREAD

**Issue by yrammos** [nextcloud/server#20648]
### Steps to reproduce
1. Create an app extending `OC/Mail/EMailTemplate` for customized welcome emails. 
2. In the NC `config.php`, associate the `mail_template_class` key with this new class name.
3. Select a user in your NC installation and attempt to send them a welcome email.
4. ⚠️ Error (see log below).

### Expected behaviour
The custom email should be sent, as it would be prior to the recent refactoring of `lib/private/Mail/Mailer.php`.

### Actual behaviour
Email is not sent, PHP error is logged instead.

### Server configuration

**Nextcloud version:**

18.0.4

### Logs

`Exception: Argument 3 passed to OC\Mail\EMailTemplate::__construct() must implement interface OCP\L10N\IFactory, instance of OC\L10N\LazyL10N given` 

### Proposed solution

See PR below.

**Comment by MorrisJobke** [comment]
Fixed by #20650
