### ISSUE TITLE
Calendar app: iOS address

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#2065]
Not shure if this is relevant or interesting for you guys, but there's a little bug (?) with the iOS CalDAV address provided by the calendar app.

It's quite important to say that I do NOT add the CalDAV account manually but automatically with a configuration profile (.mobileconfig, see this: [https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html](https://developer.apple.com/library/content/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html)).

If I use the provided iOS address, calendar accounts aren't added at all. But they are added when only using 'myhost.tld' or 'cloud.myhost.tld' without any further information. I configured using SSL and port 443 and it is added instantly.

I don't knwo whose fault this is, this issue is just for your information. :smile: 

# Configuration

Nextcloud: 10.0.1
iOS: 10.1.1, iPhone 6
macOS: Sierra (can't test the different host addresses right now, but it works with the "raw address" from above)

**Comment by georgehrke** [comment]
@alve89 Do you mind telling us the property value combination you used in the plist file? :)

**Comment by georgehrke** [comment]
Also we are planning to provide built in config profiles ;)
https://github.com/nextcloud/server/issues/1434

**Comment by alve89** [comment]
Please look into #1434 or here: https://github.com/alve89/PHPMobileConfig

**Comment by MorrisJobke** [comment]
I will close this one here in favour of #1434. We should fix this via a more user friendly way.
