### ISSUE TITLE
Update Nextcloud from 17.0.3 to 18.0.1 is failing

### ISSUE THREAD

**Issue by aaron-git** [nextcloud/server#20665]
**Steps to reproduce**
- try to update nextcloud to 18.0.1
- I'm using git as update channel.
- Just setting HEAD to the 18.0.1 commit

**Expected behaviour:**
- Nextcloud is at Version 18.0.1 and is working fine

**Actual Behavior:**
- Browser load's an empty page
- see Apache errorlog at the end of the post

**Server configuration:**

Operating system: Ubuntu 18.04

PHP version: 7.2.24

Nextcloud version: 18.0.1

Apache-version: 2.4.29

PSQL version: 12.2

**Where did you install Nextcloud from:** 

just clone the source repo

**Error Message from the /var/log/apache/error.log**

 PHP Fatal error:  
Uncaught Error: Class 'Doctrine\\DBAL\\TransactionIsolationLevel' not found in /var/www/html/nextcloud/lib/private/DB/Connection.php:155\nStack trace:\n#0 /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Array, Object(Doctrine\\DBAL\\Driver\\PDOPgSql\\Driver), Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#1 /var/www/html/nextcloud/lib/private/DB/ConnectionFactory.php(159): Doctrine\\DBAL\\DriverManager::getConnection(Array, Object(Doctrine\\DBAL\\Configuration), Object(Doctrine\\Common\\EventManager))\n#2 /var/www/html/nextcloud/lib/private/Server.php(748): OC\\DB\\ConnectionFactory->getConnection('pgsql', Array)\n#3 /var/www/html/nextcloud/3rdparty/pimple/pimple/src/Pimple/Container.php(118): OC\\Server->OC\\{closure}(Object(OC\\Server))\n#4 /var/www/html/nextcloud/lib/private/ServerContainer.php(125): Pimple\\Container->offsetGet('OCP\\\\IDBConnecti...')\n#5 /var/www/html/nextcloud/lib/private/AppFramework/Utility/SimpleContainer.php( in /var/www/html/nextcloud/lib/private/DB/Connection.php on line 155

**Comment by kesselb** [comment]
> Third-party components are handled as git submodules which have to be initialized first. So aside from the regular git checkout invoking git submodule update --init or a similar command is needed, for details see Git documentation.


https://github.com/nextcloud/server/blob/master/README.md#development-setup-

Please keep in mind that running Nextcloud from git is for development.
