### ISSUE TITLE
May be or may be not a sanitizing issue: "Geräte &amp; Sitzungen" on /settings/user/security

### ISSUE THREAD

**Issue by Wikinaut** [nextcloud/server#20666]
* Nextcloud version 18.0.4
index.php/settings/user/security 

![20200426-111729 Auswahl](https://user-images.githubusercontent.com/1151915/80303317-c7d6ef80-87af-11ea-9854-03ede0d5f752.png)

**Comment by kesselb** [comment]
As always. Please use the search before creating a new issue.

**Comment by Wikinaut** [comment]
Search for "&amp" did not reveal any issue.
