### ISSUE TITLE
Upgrade from ownCloud 10.0.9.5 to latest Nextcloud doesn't work

### ISSUE THREAD

**Issue by Nowaker** [nextcloud/server#20664]
### Steps to reproduce
1. Have `owncloud 10.0.9.5` and `nextcloud 18.0.4`
2. `php occ upgrade`
3. See: `Updates between multiple major versions and downgrades are unsupported.`

### Expected behaviour

As per https://docs.nextcloud.com/server/stable/admin_manual/maintenance/migrating_owncloud.html it should work because I have Owncloud `10.0.1 or later` and I migrate to Nextcloud `12.0.1 or later`.

If this is not supported, the documentation needs to be clearer about it.

### Actual behaviour

It doesn't work.

### Server configuration

**Operating system:** Arch Linux

**PHP version:** 7.4.5

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** 10.0.9.5

**Where did you install Nextcloud from:** pacman -S nextcloud

**all other questions**: not applicable / doesn't work / doesn't matter

**Comment by kesselb** [comment]
@nickvergessen @MorrisJobke mind to update the documentation? :)

**Comment by MorrisJobke** [comment]
> https://docs.nextcloud.com/server/stable/admin_manual/maintenance/migrating_owncloud.html it should work because I have Owncloud `10.0.1 or later` and I migrate to Nextcloud `12.0.1 or later`.

Ah ... yes - it is only supported to 12.0.1 or later on the 12 major version. So 12.0.x where x is not 0.

**Comment by MorrisJobke** [comment]
See https://github.com/nextcloud/documentation/pull/2028
