### ISSUE TITLE
The problem with moving the file.

### ISSUE THREAD

**Issue by Glossow** [nextcloud/server#20672]
Hello. Nextcloud deleted a file when moving to a shared folder.
All information on the video: https://yadi.sk/i/GAl47OGx9362Ug
Nextcloud 
Server configuration
Operating system: Debian GNU/Linux 10
Web server: nginx/1.14.2
Database: mariadb-server-10.3/stable,now 1:10.3.22-0+deb10u1
PHP version: 7.3.14-1~deb10u1
Nextcloud version: 18.0.4
Updated from an older Nextcloud/ownCloud or fresh install: New installation.
Where did you install Nextcloud from: DigitalOcean. Installed from source.

The problem is resolved.
'filelocking.enabled' => false, (need true)

**Comment by kesselb** [comment]
Thanks for taking the time to record a video :+1: 

Please edit your post and add the issue template: https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md

It's quite hard to reproduce a problem without those information.
