### ISSUE TITLE
wrong app certificate revoked

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#20674]
when installing the Data Analytics app in 18.0.4 the message is

**Certificate "4353" has been revoked**

certificates did not change
https://github.com/nextcloud/app-certificate-requests/tree/master/analytics

I think it might be related to this commit?
https://github.com/nextcloud/server/commit/d702c3d7880b6239350d0617d532b03e06e9fce0#diff-130227cf4fad75939e37b7b224923e71
@MorrisJobke is it possible that you killed the analytics-app certificate with this commit?!

**Comment by Rello** [comment]
https://github.com/Rello/analytics/issues/38

**Comment by MorrisJobke** [comment]
This came in via https://github.com/nextcloud/server/pull/20474 and there I only revoked that specific certificate:

```
openssl ca -config openssl.cnf -revoke certs/spgverein.crt
```

Let me check the revocation list.

**Comment by MorrisJobke** [comment]
Found the issue:

```
$ openssl x509 -in spgverein/spgverein.old.crt -noout -text | head -n 4
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 4353 (0x1101)
$ openssl x509 -in analytics/analytics.crt -noout -text | head -n 4
Certificate:
    Data:
        Version: 1 (0x0)
        Serial Number: 4353 (0x1101)
```

They both have the same serial number. Let me check how this could have happened.

**Comment by Rello** [comment]
thank you @MorrisJobke 
it sounds like any fix would require a new root file to be pushed via an NC update.

should I request a new certificate/signature for the app? would this be quicker?

**Comment by j-ed** [comment]
> They both have the same serial number. Let me check how this could have happened.
OpenSSL usually reads the serial number to be used for a new certificate from the serial-file. The number should always be +1 of the last certificated listed in the index.txt file. It might be sufficient to correct the number in the serial-file if only one certificate with a double serial number has been generated.

**Comment by MorrisJobke** [comment]
> should I request a new certificate/signature for the app? would this be quicker?

Let me sign your existing csr again and then you have a new certificate.



> OpenSSL usually reads the serial number to be used for a new certificate from the serial-file. The number should always be +1 of the last certificate listed in the index.txt file. It might be sufficient to correct the number in the serial-file, if only one certificate with a double serial number has been generated.

We found the issue, which originates in a migration of our signing machine, which caused some certs being issued in one place and some in another. We are on it.

**Comment by MorrisJobke** [comment]
As it is already revoked you can find the new cert at https://github.com/nextcloud/app-certificate-requests/commit/c27d7eecf957a5ef81798925e5f4a58c95146bfc

Sorry for the trouble. :/

**Comment by Rello** [comment]
Just to verify: I just have to release the app with a new subversion x.x.1 into the appstore and sign it with the new cert, correct?

**Comment by MorrisJobke** [comment]
Fixed by issuing a new certificate. Sorry for the trouble.

**Comment by MorrisJobke** [comment]
> Just to verify: I just have to release the app with a new subversion x.x.1 into the appstore and sign it with the new cert, correct?

Correct. Just use the new certificate and then there should be no warning during the installation.

**Comment by Rello** [comment]
one addition to this: I registered the app as "new" to the appstore due to the changed signature. then I pushed a new release.
it worked at the end. thanks for the quick fix

**Comment by MorrisJobke** [comment]
> one addition to this: I registered the app as "new" to the appstore due to the changed signature. then I pushed a new release.
> it worked at the end. thanks for the quick fix

But you kept the appid, right? Because the problem here was only due to the signature and not due to the appid. But good that it worked in the end :)

**Comment by Rello** [comment]
@MorrisJobke yes. app-id is the same. but a new signature requires a "new" app

`This form can also be used to update existing certificates, however only the app owner is allowed to do so. Updating an app certificate will delete all of its already uploaded releases!`

**Comment by MorrisJobke** [comment]
> This form can also be used to update existing certificates, however only the app owner is allowed to do so. Updating an app certificate will delete all of its already uploaded releases!

Oh ... didn't knew that, but makes sense when thinking about it 👍

**Comment by fedwiiix** [comment]
Hello, how to change revoked status or create a new valid certificat for my application : mindmap_app ?

**Comment by MorrisJobke** [comment]
> Hello, how to change revoked status or create a new valid certificat for my application : mindmap_app ?

We updated the certificate: https://github.com/nextcloud/app-certificate-requests/pull/267#issuecomment-619952309

You just need to re-register the app: see https://github.com/nextcloud/app-certificate-requests/pull/287#issuecomment-644279715
