### ISSUE TITLE
Setup error: Failed to start nextcloud-setup.service

### ISSUE THREAD

**Issue by razvan-flavius-panda** [nextcloud/server#20675]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Use operating system NixOS Linux
2. Install Nix packages: nextcloud18, nextcloud-client, postgresql
3. Add following to `configuration.nix`: https://nixos.org/nixos/manual/index.html#module-services-nextcloud-basic-usage
4. Create a file named `nextcloudAdminPass.txt` in same folder as `configuration.nix` and save into it the admin password you want nextcloud to use and then update `adminpassFile = "/path/to/admin-pass-file";` to `adminpassFile = "nextcloudAdminPass.txt";`
5. Update `hostName` to use your local address, eg. `hostName = "192.168.0.17";` in my case
6. Run `sudo nixos-rebuild switch`

### Expected behavior

I would expect nextcloud to install successfully.

### Actual behavior

Running `sudo nixos-rebuild switch` outputs the following error:

```shell
neo@nixos ~> sudo nixos-rebuild switch
building Nix...
building the system configuration...
trace: warning: A legacy Nextcloud install (from before NixOS 20.03) may be installed.

You're currently deploying an older version of Nextcloud. This may be needed
since Nextcloud doesn't allow major version upgrades that skip multiple
versions (i.e. an upgrade from 16 is possible to 17, but not 16 to 18).

It is assumed that Nextcloud will be upgraded from version 16 to 17.

 * If this is a fresh install, there will be no upgrade to do now.

 * If this server already had Nextcloud installed, first deploy this to your
   server, and wait until the upgrade to 17 is finished.

Then, set `services.nextcloud.package` to `pkgs.nextcloud18` to upgrade to
Nextcloud version 18.

activating the configuration...
setting up /etc...
reloading user units for sddm...
reloading user units for neo...
setting up tmpfiles
warning: the following units failed: nextcloud-setup.service

● nextcloud-setup.service
   Loaded: loaded (/nix/store/pfi3xbkgll0xiwbp6gly0h5j6n7hq7ix-unit-nextcloud-setup.service/nextcloud-setup.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-04-26 11:55:10 IST; 22ms ago
  Process: 31002 ExecStart=/nix/store/svvwjdigb5xrqd7y4p91jv0l8qfmz3vr-unit-script-nextcloud-setup-start (code=exited, status=1/FAILURE)
 Main PID: 31002 (code=exited, status=1/FAILURE)
       IP: 0B in, 0B out
      CPU: 149ms

Apr 26 11:55:10 nixos sudo[31008]:     root : TTY=unknown ; PWD=/nix/store/c3ljn5plyrw4jmd7r2qh76qsnyib30z7-nextcloud-17.0.4 ; USER=nextcloud ; ENV=NEXTCLOUD_CONFIG_DIR=/var/lib/nextcloud/config ; COMMAND=/nix/store/8xg66anvp8rr7pjs893l1dnrqsvqrv8g-php-7.3.16/bin/php -c /nix/store/i279myr15286cy0givvk53hr7xy4c6xn-php.ini occ upgrade...
Apr 26 11:55:10 nixos sudo[31008]: pam_unix(sudo:session): session opened for user nextcloud by (uid=0)
Apr 26 11:55:10 nixos svvwjdigb5xrqd7y4p91jv0l8qfmz3vr-unit-script-nextcloud-setup-start[31002]: Nextcloud is not installed - only a limited number of commands are available
Apr 26 11:55:10 nixos svvwjdigb5xrqd7y4p91jv0l8qfmz3vr-unit-script-nextcloud-setup-start[31002]:                                      
Apr 26 11:55:10 nixos svvwjdigb5xrqd7y4p91jv0l8qfmz3vr-unit-script-nextcloud-setup-start[31002]:   Command "upgrade" is not defined.
Apr 26 11:55:10 nixos svvwjdigb5xrqd7y4p91jv0l8qfmz3vr-unit-script-nextcloud-setup-start[31002]:                                      
Apr 26 11:55:10 nixos sudo[31008]: pam_unix(sudo:session): session closed for user nextcloud
Apr 26 11:55:10 nixos systemd[1]: nextcloud-setup.service: Main process exited, code=exited, status=1/FAILURE
Apr 26 11:55:10 nixos systemd[1]: nextcloud-setup.service: Failed with result 'exit-code'.
Apr 26 11:55:10 nixos systemd[1]: Failed to start nextcloud-setup.service.
Hint: Some lines were ellipsized, use -l to show in full.
warning: error(s) occurred while switching to the new configuration
```

### Server configuration

**Operating system:** NixOS 20.03 Beta

**Web server:** How can I tell this?

**Database:** PotgreSQL

**PHP version:** How can I tell this?

**Nextcloud version:** Version 18

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Nix packages

**Are you using external storage, if yes which one:** I am not using external storage.

**Are you using encryption:** No.

**Are you using an external user-backend, if yes which one:** No.

### Client configuration
**Browser:** Chrome

**Operating system:** NixOS

### Logs

How do I obtain logs?

**Comment by razvan-flavius-panda** [comment]
Using the package `nextcloud17` gives the same error.

**Comment by kesselb** [comment]
Thanks for reporting 👍 

Mind to use https://help.nextcloud.com for your question? That looks more like a configuration issue to me. 

I don't know if anyone over there is familiar with the NixOS package. If there is a help community for NixOS may ask their.

**Comment by razvan-flavius-panda** [comment]
@kesselb I linked to this question there:

https://help.nextcloud.com/t/setup-error-failed-to-start-nextcloud-setup-service/79389

I also asked on IRC in #nixos but not answer yet.

**Comment by razvan-flavius-panda** [comment]
How can I tell the Web server and PHP version?

How do I obtain the logs?
