### ISSUE TITLE
swift external storage fails on ssl openstack endpoint

### ISSUE THREAD

**Issue by stefanost67** [nextcloud/server#2069]
The bug I am reporting dates back to owncloud 9.0 (if not before). It does not show up when the Swift object storage is accessed through plain http (no SSL). Tested it on multiple Swift platforms know to be working at production level with correctly configured commercial SSL certificates .

### Steps to reproduce
1. Configure Swift external storage over an SSL endpoint
2. upload files
3. download files

### Expected behaviour
Files should be downloaded correctly

### Actual behaviour
Files are uploaded correctly
File downloaded from swift client are uncorrupted
File downloaded from nextcloud web ui or sync client is a html page. The body content is

"Can't read file"

### Server configuration
**Operating system**:
ubuntu 16.04
**Web server:**
apache2
**Database:**
mysql
**PHP version:**
PHP 7.0.8-0ubuntu0.16.04.3
**Nextcloud version:** (see Nextcloud admin page)
10.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
nextcloud vm script at https://github.com/nextcloud/vm

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - spreedme: 0.3.3
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "172.16.2.149",
            "nextcloud",
            "nextcloud.lngs.infn.it"
        ],
        "datadirectory": "\/var\/ncdata",
        "overwrite.cli.url": "https:\/\/172.16.2.149\/",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud_db",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "proxy": "http:\/\/wwwcache.lngs.infn.it:80",
        "instanceid": "occ57mjiu4rd",
        "appstore.experimental.enabled": "true",
        "mail_smtpmode": "smtp",
        "mail_smtpauth": "1",
        "mail_smtpport": "465",
        "mail_smtphost": "smtp.gmail.com",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "www.techandme.se",
        "mail_domain": "gmail.com",
        "mail_smtpsecure": "ssl",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0,
            "dbindex": 0
        },
        "htaccess.RewriteBase": "\/",
        "maintenance": false
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
swift
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Up-to-date Chrome (irrelevant)
**Operating system:**
ubuntu 16.04 (irrelevant)
#### Web server error log
<details>
<summary>Web server error log</summary>
none (irrelevant)

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"CfvVfTR2BZWVlZfbiRcA","remoteAddr":"172.17.22.70","app":"PHP","message":"Invalid argument supplied for foreach() at \/var\/www\/nextcloud\/3rdparty\/guzzle\/stream\/Guzzle\/Stream\/PhpStreamRequestFactory.php#268","level":3,"time":"2016-11-10T07:21:02+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Fswift&files=Angelo%20Ferracuti.zip&downloadStartSecret=llpcdjoayy8t9cgfyi2ysc3di","user":"ncadmin"}
{"reqId":"CfvVfTR2BZWVlZfbiRcA","remoteAddr":"172.17.22.70","app":"no app in context","message":"Exception: {\"Exception\":\"Guzzle\\\\Common\\\\Exception\\\\RuntimeException\",\"Message\":\"Error creating resource.\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php(218): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->createResource(Object(Closure))\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php(62): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->createStream(Array)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files_external\\\/lib\\\/Lib\\\/Storage\\\/Swift.php(382): Guzzle\\\\Stream\\\\PhpStreamRequestFactory->fromRequest(Object(Guzzle\\\\Http\\\\Message\\\\Request))\\n#3 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OCA\\\\Files_External\\\\Lib\\\\Storage\\\\Swift->fopen('Angelo Ferracut...', 'r')\\n#4 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Availability.php(318): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('Angelo Ferracut...', 'r')\\n#5 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(849): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Availability->fopen('Angelo Ferracut...', 'r')\\n#6 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(917): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->readFirstBlock('Angelo Ferracut...')\\n#7 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Encryption.php(379): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->getHeader('Angelo Ferracut...')\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/Storage\\\/Wrapper\\\/Wrapper.php(294): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Encryption->fopen('Angelo Ferracut...', 'rb')\\n#9 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(1118): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->fopen('Angelo Ferracut...', 'rb')\\n#10 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(963): OC\\\\Files\\\\View->basicOperation('fopen', '\\\/swift\\\/Angelo F...', Array, 'rb')\\n#11 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Files\\\/View.php(426): OC\\\\Files\\\\View->fopen('\\\/swift\\\/Angelo F...', 'rb')\\n#12 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(304): OC\\\\Files\\\\View->readfile('\\\/swift\\\/Angelo F...')\\n#13 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/legacy\\\/files.php(120): OC_Files::getSingleFile(Object(OC\\\\Files\\\\View), '\\\/swift', 'Angelo Ferracut...', Array)\\n#14 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/files\\\/ajax\\\/download.php(63): OC_Files::get('\\\/swift', 'Angelo Ferracut...', Array)\\n#15 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Route.php(155) : runtime-created function(1): require_once('\\\/var\\\/www\\\/nextcl...')\\n#16 [internal function]: __lambda_func()\\n#17 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(293): call_user_func('\\\\x00lambda_3896', Array)\\n#18 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/base.php(983): OC\\\\Route\\\\Router->match('\\\/apps\\\/files\\\/aja...')\\n#19 \\\/var\\\/www\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#20 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/guzzle\\\/stream\\\/Guzzle\\\/Stream\\\/PhpStreamRequestFactory.php\",\"Line\":271}","level":3,"time":"2016-11-10T07:21:02+00:00","method":"GET","url":"\/nextcloud\/index.php\/apps\/files\/ajax\/download.php?dir=%2Fswift&files=Angelo%20Ferracuti.zip&downloadStartSecret=llpcdjoayy8t9cgfyi2ysc3di","user":"ncadmin"}

</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by MorrisJobke** [comment]
Could you retest with the current daily master we have updated the swift library and I tested a swift setup with SSL successfully. So this should be fixed now :)
