### ISSUE TITLE
"Error updating the share" when "allow editing" at sharing

### ISSUE THREAD

**Issue by linuxuser424** [nextcloud/server#20692]
Hi,

I have this issue on Nextcloud 18.0.4 and tested it also on Nextcloud 19.0.0 Beta 5.
In thread #18893  @skjnldsv advised me to open a new issue. 

### Steps to reproduce
1. I want to share a file or a directory (makes no difference) - with or without password (also no difference).
2. Additionally I want to allow editing of this shared file

![screen3](https://user-images.githubusercontent.com/48769262/80393182-6d718800-88b0-11ea-9330-acad507ba0f2.gif)

3. This admin option (red arrow in screenshot) is **not** active:
![screen4](https://user-images.githubusercontent.com/48769262/80394190-d0175380-88b1-11ea-8e9c-726e1d875811.gif)

### Expected behaviour
After clicking on "Allow editing" Nextcloud saves this option for this file and user with correct password can edit the file.

### Actual behaviour
After clicking on "Allow editing" this error appears: "Error updating the share". It seems to be activated, but it is not. A fresh page visit later: the option was not saved.

Only if I activate the admin config option "Allow public uploads" (see image number 2 above) the expected behaviour arise.

### Server configuration

**Operating system:** Debian 9 

**Web server:** Apache

**Database:** MariaDB 10.3

**PHP version:** 7.3

**Nextcloud version:** 18.0.4 and 19.0.0 Beta 5

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** manual install from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - audioplayer: 2.10.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 0.8.2
  - encryption: 2.7.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.2.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.0
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - systemtags: 1.9.0
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - data_request
  - documentserver_community
  - files_external
  - files_lock
  - files_rightclick
  - firstrunwizard
  - onlyoffice
  - ransomware_protection
  - recommendations
  - richdocuments
  - spreed
  - support
  - survey_client
  - text
  - user_ldap
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Ubuntu 18.04 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>

nothing during reproduction of the error

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
nothing during reproduction of the error
</details>
Audit log is also empty.

#### Browser log
<details>
<summary>Browser log</summary>

browser console:
![screen](https://user-images.githubusercontent.com/48769262/80394586-559b0380-88b2-11ea-8fb7-9b8c5f4bffa7.gif)

network requests:
![screen2](https://user-images.githubusercontent.com/48769262/80394588-56cc3080-88b2-11ea-8407-9c2cf6487e2f.gif)

After that i clicked the 400 failing request (bottom), select the repsonse tab and got this error:

`{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Public upload is not allowed"},"data":[]}}`
</details>

**Comment by deepthought-64** [comment]
I came across this very same behavior in my Nextcloud 21 installation. 
So am I right in assuming that this is **not** fixed by #20726?

```
ShareRequests.js:109 Error while updating share Error: Request failed with status code 400
    at t.exports (createError.js:16)
    at t.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:62)
```

If I enable public uploads, it works... just like @linuxuser424 observed too.
