### ISSUE TITLE
Moving and playing movie files

### ISSUE THREAD

**Issue by gucu** [nextcloud/server#20694]
Hi

I am trying to move movie files and finding that I can't, not sure if this is related to size but it says it cannot do it and then when I try to play the movie files it won't play them in a browser. Plays them fine if they are downloaded.

Thanks.

**Comment by gucu** [comment]
Just discovered I can't download either. If I try the share link method it says it has downloaded but it only downloads 0 bytes, not the file.

**Comment by kesselb** [comment]
I'm not able to reproduce with a demo account at https://try.nextcloud.com.

**Comment by gucu** [comment]
How do I proceed from here please? The logs are saying:
[PHP] Error: fopen(/home/gqatawtz/nextclouddata/rich/files/Movies/A/Alien/Alien.m4v): failed to open stream: No such file or directory at /home/gqatawtz/public_html/lib/private/Files/Storage/Local.php#302

GET /index.php/s/jnZYBQbn23pZQDL/download
from 92.13.174.149 at 2020-04-27T18:47:43+00:00

The files are there and when I check the info the file size is shown as 1.2gb. Does that help? Do you need anymore information.

**Comment by gucu** [comment]
I think I have tracked down the problem. I created a new directory and uploaded a movie file to that directory. I have just played the movie with no problems, in a browser and as a download.

Is there anyway of seeing whether a directory is corrupted in some way please?

Thanks
