### ISSUE TITLE
Device-specific passwords get invalidated for no obvious reason

### ISSUE THREAD

**Issue by jurgenhaas** [nextcloud/server#20702]
### Steps to reproduce

I have no idea how to reproduce this. What I have installed is the twofactor_totp app and I created a user with 2FA enabled. I then created a device specific password for that user which is used by a monitoring system to curl into https://cloud.example.com/ocs/v2.php/apps/serverinfo/api/v1/info?format=json and providing the `Authorization: Basic [base64 encoded username:app-token]` as a header value for authentication.

This is working for a period of time and then suddenly not any longer. Reviewing the scenario highlighted that for that device specific password the field `password_invalid` in the table `authtoken` is set to 1 but we have no idea why.

The installation is in place for many years, gets updated only automatically (no manual fiddling with files or config) and the described behaviour started a couple of weeks ago. See also nextcloud/twofactor_totp#878

### Expected behaviour

The authtoken should be valid all the time and not being invalidated - unless we know for a valid reason while this is currently not the case. We've analysed the situation and have no explanation for this what so ever.

### Actual behaviour

Randomly, the authtoken get invalidated, sometimes just for the monitoring app, but sometimes also for the desktop client from NextCloud or der DAVx5 client on Android.

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** MySQL 5.7.29-0ubuntu0.18.04.1

**PHP version:** 7.2.24-0ubuntu0.18.04.4

**Version:** 18.0.4

**Updated from an older version or fresh install:** Fresh install of code, but database moves forward since version 8 or 9

**List of activated apps:**

```
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - audioplayer: 2.10.0
  - bookmarks: 2.3.4
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - circles: 0.18.5
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - cookbook: 0.6.3
  - dav: 1.14.0
  - deck: 1.0.0-beta2
  - drawio: 0.9.5
  - external: 3.5.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_automatedtagging: 1.8.2
  - files_downloadactivity: 1.7.0
  - files_fulltextsearch: 1.4.2
  - files_fulltextsearch_tesseract: 1.4.1
  - files_pdfviewer: 1.7.0
  - files_readmemd: 1.1.4
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 0.1.8
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - gpxedit: 0.0.13
  - gpxmotion: 0.0.11
  - gpxpod: 4.2.1
  - group_everyone: 0.1.5
  - groupfolders: 6.0.6
  - guests: 1.4.3
  - impersonate: 1.5.0
  - keeweb: 0.6.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - metadata: 0.11.1
  - news: 14.1.4
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - phonetrack: 0.6.2
  - photos: 1.0.0
  - polls: 1.3.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_detection: 0.7.1
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - registration: 0.4.7
  - richdocuments: 3.5.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - user_saml: 3.0.1
  - viewer: 1.2.0
  - workflowengine: 2.0.0
```

**The content of config/config.php:**

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.example.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": "true",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "logfile": "\/var\/log\/nextcloud\/example.log",
        "theme": "",
        "maintenance": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "timeout": 0,
            "dbindex": 2
        },
        "appstore.experimental.enabled": true,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/cloud.example.com",
        "overwriteprotocol": "https",
        "logtimezone": "UTC",
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.utf8mb4": true
    }
}
```

#### Client configuration

**Browser:** Firefox, Brave, Chrome

**Operating system:** Ubuntu 18.04 LTS

##### Web server error log

```
this is empty
```

##### Server log (data/nextcloud.log)

```
there hasn't been any log entry at the time, this happened last time, will post something later when it happens next time and if anything were in the log then
```

##### Browser log

```
this happens without a browser being involved
```

**Comment by jurgenhaas** [comment]
It just happened again. There is nothing in the apache error log. Here is the sequence in the apache access log:

```
192.168.3.58 - - [28/Apr/2020:16:25:46 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:25:46 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1323 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:25:49 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:25:49 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1308 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:25:52 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:25:52 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1308 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:25:55 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:25:55 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1323 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:25:58 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:25:58 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1323 "-" "-"
192.168.3.44 - jurgenhaas [28/Apr/2020:16:26:00 +0000] "PROPFIND /remote.php/dav/files/jurgenhaas/ HTTP/1.1" 207 390 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
192.168.3.58 - - [28/Apr/2020:16:26:01 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:01 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1323 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:04 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:04 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1323 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:07 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:07 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 200 1323 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:10 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:10 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 401 106 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:13 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:13 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 401 106 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:16 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:16 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 401 106 "-" "-"
192.168.3.44 - jurgenhaas [28/Apr/2020:16:26:17 +0000] "PROPFIND /remote.php/dav/files/jurgenhaas/ HTTP/1.1" 207 391 "-" "Mozilla/5.0 (Linux) mirall/2.6.4git (Nextcloud)"
192.168.3.58 - - [28/Apr/2020:16:26:19 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:19 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 401 106 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:22 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:22 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 401 106 "-" "-"
192.168.3.58 - - [28/Apr/2020:16:26:25 +0000] "GET /index.php/login HTTP/1.1" 200 6639 "-" "-"
192.168.3.58 - jurgenhaas [28/Apr/2020:16:26:25 +0000] "GET /ocs/v2.php/apps/serverinfo/api/v1/info?format=json HTTP/1.1" 401 106 "-" "-"
```

This shows that all requests to `/ocs/v2.php/apps/serverinfo/api/v1/info?format=json` respond with 200 and suddenly change to 401.

There is nothing in the nextcloud log either at that time.

**Comment by jurgenhaas** [comment]
And a second instance just showed the same effect. Nothing in apache's error log, nothing in nextcloud's log and similar entries in apache's access log.

The monitoring site (NetData) shows the following graph around the time when this happens:

![Screenshot from 2020-04-28 19-07-30](https://user-images.githubusercontent.com/1475675/80516464-cb22d480-8983-11ea-8291-cd9590c11377.png)

What it shows:

- Response time is below 300ms and response length more than 1200 bytes
- Suddenly, response time peeks to 900ms and response length drops to around 100 bytes
- At the same time, status turns bad (note, the time scale on the third is shifted to the right, all 3 events happen at the same time)

So, although nothing is in the logs, it looks like there is a request which takes significantly longer and from than on, this fails.

**Comment by kesselb** [comment]
> there hasn't been any log entry at the time,

Set the `loglevel` to a lower value. If validating the passwords fails a message is logged with loglevel 2. Not sure if that leads to more insights but it's start ;)

**Comment by jurgenhaas** [comment]
OK, that helps, thanks. However, the only additional information in the log is this:

```
{"reqId":"ihg2D1Y8MJ1pEhI69NLB","level":2,"time":"2020-04-29T09:49:26+00:00","remoteAddr":"192.168.3.58","user":"--","app":"core","method":"GET","url":"/ocs/v2.php/apps/serverinfo/api/v1/info?format=json","message":"Login failed: 'jurgenhaas' (Remote IP: '192.168.3.58')","userAgent":"--","version":"18.0.4.2"}
{"reqId":"ihg2D1Y8MJ1pEhI69NLB","level":2,"time":"2020-04-29T09:49:26+00:00","remoteAddr":"192.168.3.58","user":"--","app":"core","method":"GET","url":"/ocs/v2.php/apps/serverinfo/api/v1/info?format=json","message":"Login failed: 'jurgenhaas' (Remote IP: '192.168.3.58')","userAgent":"--","version":"18.0.4.2"}
```

No idea, why it's logged twice. Does that tell anything?

The performance graph at that time looks similar again:

![Screenshot from 2020-04-29 12-11-21](https://user-images.githubusercontent.com/1475675/80585774-30260b00-8a14-11ea-81e0-d3bfe0f2abcb.png)

What I just realized is that the monitoring sends a request every 3 seconds, which is over the top I think. I've reduced that to every 60 seconds now and will have a look if that makes any difference.

**Comment by jurgenhaas** [comment]
Unfortunately, this doesn't fix the problem. I'm running out of ideas now.

**Comment by jurgenhaas** [comment]
What I've been doing the last few days is tuning MySQL with some success. It looks like the issue is almost gone - at least it now only happens very rarely compared to the issue rate we saw before.

There is only one area of attention with regard to MySQL which needs some improvements in NC: missing indices, especially when it comes to joins.

On one of my servers there is an up-to-date analysis excerpt:

```
[OK] Maximum reached memory usage: 2.8G (8.91% of installed RAM)
[OK] Maximum possible memory usage: 26.0G (83.57% of installed RAM)
[OK] Overall possible memory usage with other process is compatible with memory available
[!!] Slow queries: 13% (467K/3M)
[OK] Highest usage of available connections: 7% (15/200)
[OK] Aborted connections: 0.00%  (0/102884)
[OK] Query cache is disabled by default due to mutex contention on multiprocessor machines.
[OK] Sorts requiring temporary tables: 0% (0 temp sorts / 110K sorts)
[!!] Joins performed without indexes: 21337
[!!] Temporary tables created on disk: 64% (163K on disk / 250K total)
[OK] Thread cache hit rate: 99% (140 created / 102K connections)
[!!] Table cache hit rate: 0% (4K open / 3M opened)
[OK] Open file limit used: 0% (1/1M)
[OK] Table locks acquired immediately: 100% (102 immediate / 102 locks)
```

13% slow queries in fact is all joins without indexes. I've analysed the slow.log and not a single query took longer than the threshold of 0.5s. So there are 21.337 different queries with joins but without indexes, and those got executed 467K times.

Not sure about the "cost" of adding more indexes. But I'd be glad to identify them from the logs in order to get them added into NC. Please let me know if that's anything that would be helpful.

**Comment by jurgenhaas** [comment]
This problem is still present and I really hope, somebody can have a look. I'm happy the debug and provide more info or make tests. But I'm running out of ideas what could be wrong and really need help. We have a lot of services connected to NC instances (Thunderbird, Android devices, NC client on Linux and Windows, Home Automation, etc.) and all of them have authentication issues every now and then which is always the password_invalid column in authtoken table being set to 1 - always.

With dozens of services connected like this, having to deal with a user complaint more than once a day is a real issue, so we need to fix this something. Please help.

**Comment by pbek** [comment]
This issue sounds similar to https://gitlab.tugraz.at/dbp/nextcloud/webapppassword/-/issues/11.

**Comment by skjnldsv** [comment]
cc @rullzer @ChristophWurst

**Comment by pbek** [comment]
Yes, for us the empty passwords from OIDC we got back from `OCP\Authentication\LoginCredentials\IStore` were the problem. We now started to use `OCP\IUserSession` instead to get a proper `PasswordlessTokenException` so we can set the password to `null` instead when creating the temporary token (see [Using OCP\IUserSession to fix expiring app password with OIDC](https://gitlab.tugraz.at/dbp/nextcloud/webapppassword/-/commit/c5f2c44cf6f707e17b96ad59196f388e8f60cdc9)).

**Comment by pbek** [comment]
@jurgenhaas, are you sure you are not also getting an empty password (empty, as in "empty string") from your auth provider? Tokens with empty password will be invalidated after 5min by `\OC\User\Session::checkTokenCredentials`.

**Comment by pbek** [comment]
@kesselb, I was never able to actually see the `['some' => 'data']` anywhere with `\OC::$server->getLogger()->warning()` 😟

**Comment by jurgenhaas** [comment]
> @jurgenhaas, are you sure you are not also getting an empty password (empty, as in "empty string") from your auth provider? Tokens with empty password will be invalidated after 5min by `\OC\User\Session::checkTokenCredentials`.

@pbek TBH I don't know. How could I find out?

With regard to the debugging code from @kesselb above, I do see `Run checkPassword query` in the logs every few seconds but not a single case of `storedHash is not a valid hash of password` yet. But also, I haven't seen any invalid password instances since I've started debugging. So maybe the problem has disappeared. I'll keep watching out.

**Comment by pbek** [comment]
> @pbek TBH I don't know. How could I find out?

I sent-me/logged the password in `\OC\User\Session::checkTokenCredentials` on  a dev server.

**Comment by jurgenhaas** [comment]
Thanks @pbek I've added something to the logging there.

Last night, I saw 2 cases of "storedHash is not a valid hash of password". What's interesting: each of those recorded twice with exactly the same request ID and timestamp. May that be a reason for the problem?

**Comment by pbek** [comment]
> "storedHash is not a valid hash of password"

Interesting. I don't know, we didn't have that. We had no warnings/errors that meant anything at all. What request did you make to trigger this message?

**Comment by jurgenhaas** [comment]
In both cases, the URL `/ocs/v2.php/apps/serverinfo/api/v1/info?format=json` was requested.

**Comment by pbek** [comment]
With a manually generated app password and basic auth?

**Comment by jurgenhaas** [comment]
Yes, manually generated app password using basic auth with header value.

**Comment by pbek** [comment]
Where you able to log/mail the fetched password?

**Comment by jurgenhaas** [comment]
Not yet, I've added that extra logging only this morning, but the issues happened last night. I'll report back when I get another case.

**Comment by kesselb** [comment]
> OC::$server->getLogger()->warning()

Is written to nextcloud.log. Make sure the loglevel in `config.php` is low enough. 

https://github.com/nextcloud/server/blob/cb2695df8d47f9d5b08a7d6f1a9dbc55f63b6e59/lib/public/ILogger.php#L45-L69

Anything <= 2 would work.

**Comment by jurgenhaas** [comment]
So, here is the first incident:

```
{"reqId":"mfnL013YEFiPK9cTjinl","level":3,"time":"2020-08-26T12:46:11+00:00","remoteAddr":"192.168.3.58","user":"--","app":"no app in context","method":"REPORT","url":"/remote.php/dav/calendars/jurgenhaas/default/","message":"Run checkPassword query","userAgent":"Mozilla/5.0","version":"19.0.1.1"}
{"reqId":"mfnL013YEFiPK9cTjinl","level":3,"time":"2020-08-26T12:46:12+00:00","remoteAddr":"192.168.3.58","user":"--","app":"no app in context","method":"REPORT","url":"/remote.php/dav/calendars/jurgenhaas/default/","message":"storedHash is not a valid hash of password","userAgent":"Mozilla/5.0","version":"19.0.1.1"}
{"reqId":"mfnL013YEFiPK9cTjinl","level":3,"time":"2020-08-26T12:46:12+00:00","remoteAddr":"192.168.3.58","user":"--","app":"no app in context","method":"REPORT","url":"/remote.php/dav/calendars/jurgenhaas/default/","message":"invalid 4","userAgent":"Mozilla/5.0","version":"19.0.1.1"}
{"reqId":"mfnL013YEFiPK9cTjinl","level":3,"time":"2020-08-26T12:46:12+00:00","remoteAddr":"192.168.3.58","user":"--","app":"no app in context","method":"REPORT","url":"/remote.php/dav/calendars/jurgenhaas/default/","message":"Run checkPassword query","userAgent":"Mozilla/5.0","version":"19.0.1.1"}
{"reqId":"mfnL013YEFiPK9cTjinl","level":3,"time":"2020-08-26T12:46:12+00:00","remoteAddr":"192.168.3.58","user":"--","app":"no app in context","method":"REPORT","url":"/remote.php/dav/calendars/jurgenhaas/default/","message":"storedHash is not a valid hash of password","userAgent":"Mozilla/5.0","version":"19.0.1.1"}
```

This is one request causing 5 log entries. The `invalid 4` comes from `if ($this->manager->checkPassword($dbToken->getLoginName(), $pwd) === false) {`, so the last of the checks in `\OC\User\Session::checkTokenCredentials`

The request comes from HomeAssistant which is trying to read from the calendar. In its log I can find this:

```
2020-08-26 14:46:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for calendar.default fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 263, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 456, in async_device_update
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 146, in update
    self.data.update()
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 239, in wrapper
    result = method(*args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/components/caldav/calendar.py", line 203, in update
    results = self.calendar.date_search(start_of_today, start_of_tomorrow)
  File "/usr/local/lib/python3.8/site-packages/caldav/objects.py", line 594, in date_search
    response = self._query(root, 1, 'report')
  File "/usr/local/lib/python3.8/site-packages/caldav/objects.py", line 160, in _query
    ret = getattr(self.client, query_method)(
  File "/usr/local/lib/python3.8/site-packages/caldav/davclient.py", line 161, in report
    return self.request(url, "REPORT", query,
  File "/usr/local/lib/python3.8/site-packages/caldav/davclient.py", line 254, in request
    raise ex
caldav.lib.error.AuthorizationError: AuthorizationError at 'https://cloud.example.com/remote.php/dav/calendars/jurgenhaas/default/', reason 'Unauthorized'
```

Fun fact: this instance is running for weeks and suddenly this is happening. So, those requests are always sending the same authentication.

**Comment by jurgenhaas** [comment]
It's hard to tell. I've implemented a workaround which sets the password_invalid field to zero every 5 minutes directly in the database for those relevant records. I can turn that workaround off for now to see if it now works ok without it. I'll let you know in a couple of days.

**Comment by jurgenhaas** [comment]
It's been working for 6 days now without any issue, I guess we can call this resolved without knowing why ;-)
