### ISSUE TITLE
 Allow to edit groupadmin/own user in the user management 

### ISSUE THREAD

**Issue by JB1985** [nextcloud/server#20706]
Related to #19882 

Allow to edit admin the own user in the user management is fixed in 18.0.4, but not for a Groupadmin. 

The User test000 is a Group Admin and cant change the own settings.

![](https://user-images.githubusercontent.com/9932751/80080162-821ceb80-8551-11ea-8bd9-7b032a1090ab.png)

**Comment by JB1985** [comment]
@skjnldsv @rullzer 

Is there hope that the bug will be fixed for the next release?

**Comment by farvardin** [comment]
I can confirm we can't edit ourself as admin. It's a problem if we want for example to add ourself to another group. As a workaround, I've created a fake admin account, logged out, logged in the new account, changed my group settings, logged out, logged in my real admin account, deleted the fake admin account.

**Comment by skjnldsv** [comment]
@gary-kim or @juliushaertl  maybe? :)
