### ISSUE TITLE
Latest tarball has config.php and data directory owned by root.

### ISSUE THREAD

**Issue by RNCTX** [nextcloud/server#20700]
### Steps to reproduce
1. Download nextcloud latest tarball, unzip it, install via command line
2. "Cannot write to config" will be the error
3. Because, the latest tarball's config file was owned by root when it was zipped up ;).  Same goes for the default 'data' directory.

### Expected behaviour
It should install

### Actual behaviour
Fails due to permissions error

### Server configuration

**Operating system:**
Ubuntu 18.04
**Web server:**
Nginx
**Database:**
Postgres
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
latest
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh
**Where did you install Nextcloud from:**
tarball

**Comment by kesselb** [comment]
```
$ tar tvf latest.tar.bz2 | grep nextcloud/config
drwxr-xr-x nobody/nogroup       0 2020-04-22 21:23 nextcloud/config/
-rw-r--r-- nobody/nogroup   54813 2020-04-22 21:23 nextcloud/config/config.sample.php
-rw-r--r-- nobody/nogroup     495 2020-04-22 21:23 nextcloud/config/.htaccess
-rw-r--r-- nobody/nogroup       0 2020-04-22 21:23 nextcloud/config/CAN_INSTALL
```

`config.php` and `data/` are created by the installer. 
If those owned by root you run the installer as root.

**Comment by RNCTX** [comment]
Hmmm, this must be my ansible problem then.  I was working on a playbook to install via the command line and figured they came from the tarball that way.  I may have had stray copies of those folders laying around from a failed playbook test with wrong `become` set on a command.

Nevermind!
