### ISSUE TITLE
Better designed emails when sharing links and calendar etc

### ISSUE THREAD

**Issue by enoch85** [nextcloud/server#2071]
Today we use standard templates that contains mostly text. It works, but isn't that pretty. What I suggest is to improve the design so that it looks more professinal. I've seen some great work by @Espina2 the past weeks, and I'd really like to see some suggestions regarding an improvment of the mails that are sent to users.

As an external user of Nextcloud (someone that uses Nextcloud sends a link to someone that doesn't) the first impression is the mail they get with either a calendar invitavion or a shared link. To attract more users to use Nextcloud and make a switch from Google or some other provider I belive it's crucial that our soulution looks better.

Google Calendar invitation:
![markering_002](https://cloud.githubusercontent.com/assets/4511254/20173548/09531524-a73a-11e6-8afc-f92ded462dc4.png)

Google Drive shared link:
![markering_003](https://cloud.githubusercontent.com/assets/4511254/20173606/42c8b26e-a73a-11e6-9b65-5dd2da638245.png)

Please fill this issue with more examples.

@jancborchardt What do you think?
@georgehrke Is this something that you control in the calendar app?

**Comment by Espina2** [comment]
Can you post the actual email?

**Comment by enoch85** [comment]
@Espina2 The sharing email looks like this:

![markering_004](https://cloud.githubusercontent.com/assets/4511254/20174676/607b48da-a73f-11e6-8e4d-cc8739184058.png)

My header is black in the Theme settings.

```
Hello there,

just wanted to inform you that Daniel Hansson shared links TURN.txt with you.
Show it!

The share will expire November 17, 2016.

Have a great day!
``` 

I'm having issues generating the Calendar share email.

**Comment by enoch85** [comment]
Ok, just found out that when sharing an event in the Calendar to a Gmail address, the email looks as it came from Google - same as in the picture. 

Haven't tried with other mail suppliers or Mirosoft Exchange.

**Comment by Espina2** [comment]
I will take a look and see what I can make as soon as I can. :)

**Comment by georgehrke** [comment]
The invitation mails are handled in the day app, the email that includes the sharing link for public calendars is generated in the calendar app.

**Comment by MorrisJobke** [comment]
Related to https://github.com/nextcloud/server/issues/1326

https://mjml.io/

**Comment by eppfel** [comment]
I created some simple Drafts to start a discussion. I did not consider calendar invites, yet, but first things, first.
I opted for the colorful header, instead of just the logo (proposed by @jancborchardt in #1446 ) as a stronger brand indicator, because we use it in the web application, on nextcloud.com, on Android...
We definitely should use call-to-action buttons in every Mail.
And of course thumbnails would be nice. How realistic is this? At least filetype icons should be possible, right?

@MorrisJobke mjml looks really nice. But how would you integrate it in the development process? Or should we use it only to create responsible templates?

![sharebymail](https://cloud.githubusercontent.com/assets/1899308/20674047/abe0d0e6-b587-11e6-91ee-32fb0890020d.png)
![sharebymailrounded](https://cloud.githubusercontent.com/assets/1899308/20674046/abdeccf6-b587-11e6-92bf-44163599319d.png)
![sharebymailwhitebg](https://cloud.githubusercontent.com/assets/1899308/20674044/abde4ace-b587-11e6-977c-ea2554c425e9.png)

New User Template:
![newuser](https://cloud.githubusercontent.com/assets/1899308/20674045/abde9100-b587-11e6-9df8-edccc3586ff5.png)
Theming:
![businessbox](https://cloud.githubusercontent.com/assets/1899308/20674043/abdc0be2-b587-11e6-9fb3-637eec6bc395.png)

**Comment by enoch85** [comment]
@eppfel Very nice! I like number 2 and 3 best. What do you think @jancborchardt?

**Comment by Espina2** [comment]
I prefer with round buttons, you should increase the margins on open on Nextcloud, and maybe switch to open in the browser, since nextcloud is a brand and if configure but another brand it doesnt make to much sense.

**Comment by eppfel** [comment]
Thx, for the feedback. The rounded buttons are definitively more distinctive. I'll incorporate your feedback and create drafts for different devices/screes-sizes based on 2 and 3. When we decided on the look, we can create designs for the various other templates, to see, if it works well, in all cases.

Just, realized: We didn't ping @nextcloud/designers, yet.

**Comment by enoch85** [comment]
This would be great to have in 11, if not too late?

**Comment by georgehrke** [comment]
The first beta is already out, so we are way beyond feature freeze.

**Comment by enoch85** [comment]
Well then, lett's try to make it into 11.0.1 :)

**Comment by eppfel** [comment]
@enoch85 http://semver.org/ 😉 That's not how it works and we are already at 11.0.5.
A complete redesign takes time, but as it's mostly decoupled of other functionality, so maybe a 11.5.0 😁 But that's not for me to decide.

**Comment by phsc** [comment]
How can we be at 11.0.5 if 11.0.0 is not even released?
But I agree, according to semver.org, this would make it into 11.1.0 at the earliest.

**Comment by LukasReschke** [comment]
For the record: We don't use semver on the server. Since this is a new feature this will have to be in 12 => Early next year.

**Comment by enoch85** [comment]
Aaanyway, better late then never.

**Comment by MorrisJobke** [comment]
> @MorrisJobke mjml looks really nice. But how would you integrate it in the development process? Or should we use it only to create responsible templates?

Only use it as inspiration or try to integrate it (see bower.json ;))

**Comment by enoch85** [comment]
Any news here? :)

**Comment by MorrisJobke** [comment]
Yes:

<img width="787" alt="bildschirmfoto 2016-12-16 um 10 12 00" src="https://cloud.githubusercontent.com/assets/245432/21269376/1eb353c0-c378-11e6-9d9e-4395acedbb08.png">

😉

**Comment by eppfel** [comment]
Sry, assigned it to me now, but no promises... 😁

**Comment by enoch85** [comment]
Ping

**Comment by MorrisJobke** [comment]
> Ping

<img width="784" alt="bildschirmfoto 2017-02-15 um 18 15 41" src="https://cloud.githubusercontent.com/assets/245432/23001423/c8a7d146-f3aa-11e6-9cf4-d702fbfc9131.png">

**Comment by enoch85** [comment]
Always good with a reminder sometimes. :)

And you're too funny @MorrisJobke :D

**Comment by enoch85** [comment]
> For the record: We don't use semver on the server. Since this is a new feature this will have to be in 12 => Early next year.

12 is around the corner. How is this issue in the priority list? I have customers that asks for it all the time. 

If this is not going into 12 I would like to know how I can:
1. Change the logo so that the logo is the same as the Theming app logo.
2. Change the FROM name to the name of the Theming app to something else than Nextcloud.

Would [Email Templates](https://docs.nextcloud.com/server/9/admin_manual/configuration_server/email_configuration.html#using-email-templates) be the place to start?

**Comment by eppfel** [comment]
I'm sorry, but I had no time left for Nextcloud these days and it will be sparse in the next month, too. I feel this needs to be done shortly, but I have no influence on priorities...

**Comment by enoch85** [comment]
@eppfel I understand. 

@Espina2 Do you have time? :)

**Comment by Espina2** [comment]
@enoch85 

I have a bit of free time. But even if I come with something and do the HTML stuff, I don't know wich files I have to change. :/

**Comment by enoch85** [comment]
@Espina2 Great! 

@eppfel Could you point him in the right direction please? Or anyone else? Would be super!

**Comment by Espina2** [comment]
@MorrisJobke can I use foundation for emails and anyone of us integrate into the actual Nextcloud core?

**Comment by LukasReschke** [comment]
> @MorrisJobke can I use foundation for emails and anyone of us integrate into the actual Nextcloud core?

Sure :) Doing the HTML and CSS is fine and we can then integrate it into the mailing code :)

**Comment by Espina2** [comment]
I will work on that this weekend. :)

**Comment by enoch85** [comment]
Thank you @Espina2!

**Comment by Espina2** [comment]
So this is I came for. I don't make illustrations or any other decorative stuff because they will depend on the brand that sends the email. So is very basic and straight forward.

After the feedback, I can code this. 
![new account](https://cloud.githubusercontent.com/assets/11150206/24311700/33cfddda-10cd-11e7-9721-04264b5fbe40.png)

@enoch85

**Comment by enoch85** [comment]
@Espina2 Very cool! And when the user changes the header color and logo with the Theme app it will change as well?

**Comment by Espina2** [comment]
Is the idea, but is not me who are going to make that. That kind of thing is do in the template engine. :)

**Comment by enoch85** [comment]
Aah ok. Well then, good to go from me. Thank you @Espina2 for taking care of this before 12 is released.

**Comment by MorrisJobke** [comment]
@nextcloud/designers Please feedback :)

**Comment by eppfel** [comment]
Like it a lot. Primary better on the right? 

And @espina2 maybe try another use case like sharing to see how your design works. 
Sadly the templates are scattered and not in a central place. I touched most templates in the following PR, which gives a good list:

**Comment by enoch85** [comment]
> Primary button better on the right?

I vote no on this one. We read from left to right, not right to left.

**Comment by Espina2** [comment]
@enoch85 

Source code here (made with foundation emails) : https://cloud.paulomoura.com.pt/nextcloud-emails/

Live compiled version here: https://cloud.paulomoura.com.pt/nextcloud-emails/dist/new-member.html

I will make the other versions after @eppfel. But like how it's made it is very versatile, what is going to change is only the white part.  

@eppfel I don't see any particular reason for be on the right. If is another type of button like for example "next" it should be on the right in any other case I don't see any problem in the principal button stay on the left, like enoch said we read from left to right. :)

Hope this helps and anyone can integrate this.

**Comment by enoch85** [comment]
@Espina2 Very nice Paulo!

**Comment by jancborchardt** [comment]
Good stuff Paulo! :) What do you think about making the background white too, so it’s just all white? The grey background with white box makes it feel like it’s a bit much content on the page while it’s just a simple 1-info mail.

**Comment by enoch85** [comment]
@Espina2 Could you make this a PR so we can get it into Nextcloud 12 before release?

**Comment by Espina2** [comment]
@enoch85 
Like I said any of the other people here have to do that. I don't know the changes need in the core.

It must be another person.

**Comment by jancborchardt** [comment]
@LukasReschke and me can check it out :)

**Comment by enoch85** [comment]
@jancborchardt @LukasReschke Thank you!!

**Comment by Espina2** [comment]
@jancborchardt I prefer to have the grey and the white. It doesn't change anything if you remove the grey, but I think is more boring... 

When you check it out, you can do whatever you want. :)

**Comment by enoch85** [comment]
> I prefer to have the grey and the white. 

Me too, it makes the box stand out.

**Comment by enoch85** [comment]
I heard Hackweek is going on. Would be great if this made it into 12 before release! *please* :)

**Comment by enoch85** [comment]
> @LukasReschke and me can check it out :) 

@jancborchardt Will this make it into 12?

**Comment by MorrisJobke** [comment]
PR for the welcome email: #4244

**Comment by enoch85** [comment]
Great work @MorrisJobke @Espina2! :1st_place_medal: What about the calendar invitation and sharing emails? :)

**Comment by Espina2** [comment]
The template should be the same, just some tweaks are needed it. (design)

**Comment by MorrisJobke** [comment]
> Great work @MorrisJobke @Espina2! 🥇 What about the calendar invitation and sharing emails? :)

Keep calm. We all have limited time.

**Comment by enoch85** [comment]
@MorrisJobke Sorry, was just hoping to see this in 12.

**Comment by MorrisJobke** [comment]
Sharing emails: #4307

**Comment by enoch85** [comment]
First of all, I just tested master on localhost and I'm very happy with the result. Thank you @MorrisJobke @Espina2 and others!

On thing is still missing though, calendar invites. It currently looks like this:
![calendar](https://cloud.githubusercontent.com/assets/4511254/25436996/41a285f2-2a95-11e7-90a0-4ceaf31abb75.png)

It would be great it that also was merged before 12 is release so that we can close this issue.

Thank you! :)

**Comment by MorrisJobke** [comment]
> One thing is still missing though, calendar invites. It currently looks like this in Thunderbird:

Yep - they need to be updated. Could you open an issue in the calendar repo? Because all emails of the server are updated. Activity is also updated. Only the calendar is missing.
