### ISSUE TITLE
Show avatar image in bigger size

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#20712]
Sometimes I want to see the new avatar image from my colleague a litte bit bigger then 32x32.

![image](https://user-images.githubusercontent.com/24530680/121187001-e4c16b80-c867-11eb-9231-d0421a63945e.png)
![image](https://user-images.githubusercontent.com/24530680/121187215-1f2b0880-c868-11eb-8a55-cb9e07d6d77e.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers for more input on this.

**Comment by jakobroehrl** [comment]
> I'm confused about what this is about 🤔
> @jakobroehrl , could you elaborate and/or add screenshots?

Sure, updated the description, HTH
