### ISSUE TITLE
Frequency of notifications about available updates

### ISSUE THREAD

**Issue by bes1002t** [nextcloud/server#20727]
I got notifications that there are updates available separately for each app and nextcloud itself. I think this is a very useful feature, but why are these notifications fired each hour? In web UI I could ignore the notification but on my Linux client 4 notifications per hour are popping up. I have to clear the notification list each time to avoid missing important notifications.

At the moment I have no chance to backup my server and I don't wanna update until my backup issue is solved. I know the importance of updates and I will update as soon as my backup mechanism is working again.

Could we provide a way to change the frequency to once a day? Or probably let the administrator configure the frequency?

**Comment by kesselb** [comment]
Quite hard to triage without the issue template. 
I've seen some reports about notification spam the last days: 

https://help.nextcloud.com/t/how-to-stop-desktop-notifications-for-recommended-apps/79325
https://github.com/nextcloud/server/issues/20524

Probably something broken with the clients. Do you just swipe the notification away? It might help open the client, go to activity and dismiss the notifications there.

**Comment by bes1002t** [comment]
@kesselb as far as I know the client only shows what the server is sending, but yah maybe a client bug.

The question is, if I remove the notification from webgui, will I get a reminder e.g. tomorrow? Because I want to avoid forgetting to update, so an reminder per day would be still good. 

For debug purpose I will dismiss the notifications in webgui. Lets see when the next reminder pops up.

**Comment by bes1002t** [comment]
I've dismissed the notifications and since then they never appeared again. :(
That's not what should happen.

**Comment by kesselb** [comment]
> I've dismissed the notifications and since then they never appeared again. :(

I would expect that.

**Comment by bes1002t** [comment]
The target we all have is to make Nextcloud installations more secure. By sending hourly notifications to the client if the information is not dismissed on server may annoy admins. So what they will do is dismiss the notification on the server. But if they dismiss this notification they will be not remembered anymore and might forget about the update.

Possible solutions:
- provide configurable notification frequencies
- create new notification on server after specific time, so even after dismissing the notification they won't forget to update

**Comment by bes1002t** [comment]
once a week I have time to work on some server configs etc. That's the time when I will update my nextcloud or nextcloud addons. Until Sunday I get a notification for every single app (if update exists) each hour. This is really annoying and will lead to less updates since admins will simply dismiss the notification on server and they won't get a notification anymore.

If this is not a server related issue please let me know and I will create a new one in client repositories.

**Comment by szaimen** [comment]
I know, it is only applicable to a very specific setup but there is a workaround in the Nextcloud VM
(it only works, if you webuser is www-data and nextcloud is installed to /var/www/nextcloud)

https://github.com/nextcloud/vm/blob/master/static/updatenotification.sh

you have to execute the following to make it work:
```
SCRIPTS="/var/scripts"
mkdir "$SCRIPTS"
cd "$SCRIPTS"
curl -sLO https://raw.githubusercontent.com/nextcloud/vm/master/static/updatenotification.sh
chmod +x "$SCRIPTS"/updatenotification.sh
crontab -u root -l | { cat; echo "59 18 * * * $SCRIPTS/updatenotification.sh > /dev/null 2>&1"; } | crontab -u root -
```

**Comment by kesselb** [comment]
> Until Sunday I get a notification for every single app (if update exists) each hour. This is really annoying and will lead to less updates since admins will simply dismiss the notification on server and they won't get a notification anymore.

I don't see that behaviour on my setup.

**Comment by szaimen** [comment]
> > Until Sunday I get a notification for every single app (if update exists) each hour. This is really annoying and will lead to less updates since admins will simply dismiss the notification on server and they won't get a notification anymore.
> 
> I don't see that behaviour on my setup. Perhaps my setup is broken ;) I'm not sure what the default / expected behaviour is.

Do you get notifications for server updates?
Then you should theoratically also get notifications for available app updates...

**Comment by kesselb** [comment]
I see the notification in Nextcloud. But the notification is not pushed to desktop (on linux) or android. I will debug this sometime ;) The clients are requesting the notification endpoints regularly.

cc @nextcloud/server-triage what is the expected behaviour? :thinking:

**Comment by MorrisJobke** [comment]
That the notifications pop up on desktop again and again was (or is?) a bug in the desktop client. I'm not sure if it was fixed already. But maybe @camilasan or @misch7 knows more.

**Comment by bes1002t** [comment]
@MorrisJobke in other tickets I saw the arguments that clients only redirect the server push notifications and that clients does not ja logic to schedule these notifications. That's why I opened this issue in server project.

Since you mentioned this is a client bug, I will add some more information, maybe this could help to debug:
- OS: Linux Fedora 31
- Client: Nextcloud official Linux Desktop Client from Fedora repository
- Client-Version: 2.6.4-4.fc31
