### ISSUE TITLE
Settings section shows a scrollbar 

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2072]
### Firefox
![bildschirmfoto vom 2016-11-10 12-33-50](https://cloud.githubusercontent.com/assets/213943/20175243/17d941c4-a742-11e6-9329-2876945a26e5.png)

### Chrome
![bildschirmfoto vom 2016-11-10 12-33-59](https://cloud.githubusercontent.com/assets/213943/20175244/19001528-a742-11e6-81cf-571f15661238.png)

The ugly borders are actually scrollbars. Doesn't happen on 10 for both browsers
@nextcloud/designers

**Comment by MorrisJobke** [comment]
Fixed with #2107
