### ISSUE TITLE
MIssing Icons in file and gallery app

### ISSUE THREAD

**Issue by hj-beckers** [nextcloud/server#20721]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
new installation of 18.04 or update 18.02 -> 18.03/04 makes no difference.
The "new" button in the file app is only a grey circle. the plus sign is not shown.
In the gallery app all icons are not shown/show a combination of 4 letters (EA0x, where x varies ). If you hold the mouse over them, their description (close, left, right, start slideshow) is shown. All buttons work as intended. When dark mode is enabled, the plus sign in the new file button is shown; the gallery buttons don't change.

Tried various solutions suggested (change colour in theming, run maintenance:repair, (de-)activating theming, accessibility); makes no difference.

**Comment by vnourdin** [comment]
Icons are back in my instance since 2 or 3 days, no idea how :thinking:.

**Comment by cornim** [comment]
Deactivating the Theming app solved the issue for me.

**Comment by skjnldsv** [comment]
clear caches and do occ maintenance repair when it happens
