### ISSUE TITLE
Strange behavior of calendar/caldav on macOS Catalina (10.15.4)

### ISSUE THREAD

**Issue by tomdrops** [nextcloud/server#20730]
I’m facing a real strange behavior of the calendar and acldav respectively when accessing the calendar via CalDAV from MacOS 10.15.4. If a user creates a new event and invites participants everything works smoothly as long as the user (the one who organizes the event) is not in the address book of the invited party. it does not matter which address book on the Mac the organizer of the meeting is in. As soon as there is a local or any carddav address book entry a server error pops up. Checking the nextcloud logs I found out that sabre complains with following error message:

“message”:{“Exception”:“Sabre\DAV\Exception\BadRequest”,“Message”:“Calendar object with uid already exists in this calendar collection.”,“Code”:0,“Trace”:[{“file”:"/var/www/vhosts/nottoknow.orgt/cloud.nottoknow.org/3rdparty/sabre/dav/lib/CalDAV/

this is the log file entry:

```
{“reqId”:“XqhwFSoZR9ow2dCKj@rrmAAAAAA”,“level”:4,“time”:“2020-04-28T18:04:05+00:00”,“remoteAddr”:“81.10.202.127”,“user”:“tg”,“app”:“webdav”,“method”:“PUT”,“url”:"/remote.php/dav/calendars/tg/personal/d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics",“message”:{“Exception”:“Sabre\DAV\Exception\BadRequest”,“Message”:“Calendar object with uid already exists in this calendar collection.”,“Code”:0,“Trace”:[{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/3rdparty/sabre/dav/lib/CalDAV/Calendar.php",“line”:201,“function”:“createCalendarObject”,“class”:“OCA\DAV\CalDAV\CalDavBackend”,“type”:"->",“args”:[“8”,“d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics”,“BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Vienna\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T020000\r\nTZNAME:MESZ\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T030000\r\nTZNAME:MEZ\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nTRANSP:TRANSPARENT\r\nDTEND;TZID=Europe/Vienna:20200428T210000\r\nDTSTART;TZID=Europe/Vienna:20200428T203000\r\nORGANIZER;CN=“Tom Cannibal”;SCHEDULE-AGENT=CLIENT:mailto:tom@cannibal.on\r\n e\r\nUID:d8408200-a2c6-4a04-944f-aa78ef5a2bed\r\nDTSTAMP:20200428T175859Z\r\nSEQUENCE:2\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:Cannibals\r\nLAST-MODIFIED:20200428T180401Z\r\nCREATED:20200428T175828Z\r\nATTENDEE;CN=“Thomas Gumpinger";CUTYPE=INDIVIDUAL;EMAIL="tg@nottoknow.org”\r\n ;PARTSTAT=DECLINED;ROLE=REQ-PARTICIPANT:mailto:tg@nottoknow.org\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n”]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/3rdparty/sabre/dav/lib/DAV/Server.php",“line”:1096,“function”:“createFile”,“class”:“Sabre\CalDAV\Calendar”,“type”:"->",“args”:[“d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics”,“BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Vienna\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T020000\r\nTZNAME:MESZ\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T030000\r\nTZNAME:MEZ\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nTRANSP:TRANSPARENT\r\nDTEND;TZID=Europe/Vienna:20200428T210000\r\nDTSTART;TZID=Europe/Vienna:20200428T203000\r\nORGANIZER;CN=“Tom Cannibal”;SCHEDULE-AGENT=CLIENT:mailto:tom@cannibal.on\r\n e\r\nUID:d8408200-a2c6-4a04-944f-aa78ef5a2bed\r\nDTSTAMP:20200428T175859Z\r\nSEQUENCE:2\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:Cannibals\r\nLAST-MODIFIED:20200428T180401Z\r\nCREATED:20200428T175828Z\r\nATTENDEE;CN=“Thomas Gumpinger";CUTYPE=INDIVIDUAL;EMAIL="tg@nottoknow.org”\r\n ;PARTSTAT=DECLINED;ROLE=REQ-PARTICIPANT:mailto:tg@nottoknow.org\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n”]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/3rdparty/sabre/dav/lib/DAV/CorePlugin.php",“line”:525,“function”:“createFile”,“class”:“Sabre\DAV\Server”,“type”:"->",“args”:[“calendars/tg/personal/d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics”,“BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Vienna\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T020000\r\nTZNAME:MESZ\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T030000\r\nTZNAME:MEZ\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nTRANSP:TRANSPARENT\r\nDTEND;TZID=Europe/Vienna:20200428T210000\r\nDTSTART;TZID=Europe/Vienna:20200428T203000\r\nORGANIZER;CN=“Tom Cannibal”;SCHEDULE-AGENT=CLIENT:mailto:tom@cannibal.on\r\n e\r\nUID:d8408200-a2c6-4a04-944f-aa78ef5a2bed\r\nDTSTAMP:20200428T175859Z\r\nSEQUENCE:2\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:Cannibals\r\nLAST-MODIFIED:20200428T180401Z\r\nCREATED:20200428T175828Z\r\nATTENDEE;CN=“Thomas Gumpinger";CUTYPE=INDIVIDUAL;EMAIL="tg@nottoknow.org”\r\n ;PARTSTAT=DECLINED;ROLE=REQ-PARTICIPANT:mailto:tg@nottoknow.org\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n”,null]},{“function”:“httpPut”,“class”:“Sabre\DAV\CorePlugin”,“type”:"->",“args”:[{“absoluteUrl”:"https://cloud.nottoknow.org/remote.php/dav/calendars/tg/personal/d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics",“class”:“Sabre\HTTP\Request”},{“class”:“Sabre\HTTP\Response”}]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/3rdparty/sabre/event/lib/EventEmitterTrait.php",“line”:105,“function”:“call_user_func_array”,“args”:[[{“class”:“Sabre\DAV\CorePlugin”},“httpPut”],[{“absoluteUrl”:“https://cloud.nottoknow.org/remote.php/dav/calendars/tg/personal/d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics","class”:“Sabre\HTTP\Request”},{“class”:“Sabre\HTTP\Response”}]]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/3rdparty/sabre/dav/lib/DAV/Server.php",“line”:479,“function”:“emit”,“class”:“Sabre\Event\EventEmitter”,“type”:"->",“args”:[“method:PUT”,[{“absoluteUrl”:“https://cloud.nottoknow.org/remote.php/dav/calendars/tg/personal/d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics","class”:“Sabre\HTTP\Request”},{“class”:“Sabre\HTTP\Response”}]]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/3rdparty/sabre/dav/lib/DAV/Server.php",“line”:254,“function”:“invokeMethod”,“class”:“Sabre\DAV\Server”,“type”:"->",“args”:[{“absoluteUrl”:“https://cloud.nottoknow.org/remote.php/dav/calendars/tg/personal/d8408200-a2c6-4a04-944f-aa78ef5a2bed.ics","class”:“Sabre\HTTP\Request”},{“class”:“Sabre\HTTP\Response”}]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/apps/dav/lib/Server.php",“line”:319,“function”:“exec”,“class”:“Sabre\DAV\Server”,“type”:"->",“args”:[]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/apps/dav/appinfo/v2/remote.php",“line”:35,“function”:“exec”,“class”:“OCA\DAV\Server”,“type”:"->",“args”:[]},{“file”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/remote.php",“line”:165,“args”:["/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/apps/dav/appinfo/v2/remote.php"],“function”:“require_once”}],“File”:"/var/www/vhosts/nottoknow.org/cloud.nottoknow.org/apps/dav/lib/CalDAV/CalDavBackend.php",“Line”:1069,“CustomMessage”:"–"},“userAgent”:“Mac+OS+X/10.15.4 (19E287) CalendarAgent/930.4.1”,“version”:“18.0.4.2”}
```

**Comment by kesselb** [comment]
Looks similar to #17915?

**Comment by tomdrops** [comment]
Could be, but not likely. I’ve tried the same thing with Thunderird7Lightning, on Linux and macOS, as well as EM-Client on Windows and there is no error. I’ve investigated MAC forums and user groups and did not find any issue. I connected my Mac to a baikal day server and there were no issues. Just this constellation produces an error and it is reproducable on other nextcloud sites… all tested and verified. lightning however needs server managed scheduling mode enabled but then runs perfectly.

**Comment by kesselb** [comment]
If you see that behaviour after upgrading to 18.0.4 it's probably https://github.com/nextcloud/server/issues/20732.

**Comment by tomdrops** [comment]
nope, the server is running centos 7, php 7.3.17. however, the 2nd server I tested was running ubuntu 18.04 lts....

**Comment by kesselb** [comment]
Nextcloud 18.0.4 ;)

**Comment by tomdrops** [comment]
I have one server still running 18.0.3.... I'll verify this... ;)

**Comment by tomdrops** [comment]
unfortunately the same error occurs in nextcloud 18.0.3...

{"reqId":"QpWMSg5QdrV4hq8ddMI1","level":4,"time":"2020-04-30T09:10:24+00:00","remoteAddr":"81.10.202.127","user":"thomas.g","app":"webdav","method":"PUT","url":"/remote.php/dav/calendars/thomas.g/personal/706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","message":{"Exception":"Sabre\\DAV\\Exception\\BadRequest","Message":"Calendar object with uid already exists in this calendar collection.","Code":0,"Trace":[{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/3rdparty/sabre/dav/lib/CalDAV/Calendar.php","line":201,"function":"createCalendarObject","class":"OCA\\DAV\\CalDAV\\CalDavBackend","type":"->","args":["4","706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Vienna\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T020000\r\nTZNAME:MESZ\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T030000\r\nTZNAME:MEZ\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nTRANSP:OPAQUE\r\nDTEND;TZID=Europe/Vienna:20200430T130000\r\nDTSTART;TZID=Europe/Vienna:20200430T123000\r\nORGANIZER;CN=\"Tom Cannibal\";SCHEDULE-AGENT=CLIENT:mailto:tom@cannibal.on\r\n e\r\nUID:706b30ef-e5fe-40b5-a65f-f3fda7538ad3\r\nDTSTAMP:20200430T090929Z\r\nSEQUENCE:2\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:v2.3\r\nLAST-MODIFIED:20200430T091013Z\r\nCREATED:20200430T090906Z\r\nATTENDEE;CN=\"Thomas Gumpinger\";CUTYPE=INDIVIDUAL;EMAIL=\"thomas.g@conscio\r\n us-consulting.group\";PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:thoma\r\n s.g@conscious-consulting.group\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n"]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/3rdparty/sabre/dav/lib/DAV/Server.php","line":1096,"function":"createFile","class":"Sabre\\CalDAV\\Calendar","type":"->","args":["706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Vienna\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T020000\r\nTZNAME:MESZ\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T030000\r\nTZNAME:MEZ\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nTRANSP:OPAQUE\r\nDTEND;TZID=Europe/Vienna:20200430T130000\r\nDTSTART;TZID=Europe/Vienna:20200430T123000\r\nORGANIZER;CN=\"Tom Cannibal\";SCHEDULE-AGENT=CLIENT:mailto:tom@cannibal.on\r\n e\r\nUID:706b30ef-e5fe-40b5-a65f-f3fda7538ad3\r\nDTSTAMP:20200430T090929Z\r\nSEQUENCE:2\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:v2.3\r\nLAST-MODIFIED:20200430T091013Z\r\nCREATED:20200430T090906Z\r\nATTENDEE;CN=\"Thomas Gumpinger\";CUTYPE=INDIVIDUAL;EMAIL=\"thomas.g@conscio\r\n us-consulting.group\";PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:thoma\r\n s.g@conscious-consulting.group\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n"]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":525,"function":"createFile","class":"Sabre\\DAV\\Server","type":"->","args":["calendars/thomas.g/personal/706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","BEGIN:VCALENDAR\r\nVERSION:2.0\r\nPRODID:-//Apple Inc.//Mac OS X 10.15.4//EN\r\nCALSCALE:GREGORIAN\r\nBEGIN:VTIMEZONE\r\nTZID:Europe/Vienna\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nDTSTART:19810329T020000\r\nTZNAME:MESZ\r\nTZOFFSETTO:+0200\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nDTSTART:19961027T030000\r\nTZNAME:MEZ\r\nTZOFFSETTO:+0100\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nBEGIN:VEVENT\r\nTRANSP:OPAQUE\r\nDTEND;TZID=Europe/Vienna:20200430T130000\r\nDTSTART;TZID=Europe/Vienna:20200430T123000\r\nORGANIZER;CN=\"Tom Cannibal\";SCHEDULE-AGENT=CLIENT:mailto:tom@cannibal.on\r\n e\r\nUID:706b30ef-e5fe-40b5-a65f-f3fda7538ad3\r\nDTSTAMP:20200430T090929Z\r\nSEQUENCE:2\r\nX-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC\r\nSUMMARY:v2.3\r\nLAST-MODIFIED:20200430T091013Z\r\nCREATED:20200430T090906Z\r\nATTENDEE;CN=\"Thomas Gumpinger\";CUTYPE=INDIVIDUAL;EMAIL=\"thomas.g@conscio\r\n us-consulting.group\";PARTSTAT=ACCEPTED;ROLE=REQ-PARTICIPANT:mailto:thoma\r\n s.g@conscious-consulting.g
roup\r\nEND:VEVENT\r\nEND:VCALENDAR\r\n",null]},{"function":"httpPut","class":"S
abre\\DAV\\CorePlugin","type":"->","args":[{"absoluteUrl":"https://cloud.conscious-consulting.group/remote.php/dav/calendars/thomas.g/personal/706b30ef-e5fe-40b
5-a65f-f3fda7538ad3.ics","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre
\\HTTP\\Response"}]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.c
onscious-consulting.group/3rdparty/sabre/event/lib/EventEmitterTrait.php","line":105,"function":"call_user_func_array","args":[[{"__class__":"Sabre\\DAV\\CorePlugin"},"httpPut"],[{"absoluteUrl":"https://cloud.conscious-consulting.group/remote.php/dav/calendars/thomas.g/personal/706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/3rdparty/sabre/dav/lib/DAV/Server.php","line":479,"function":"emit","class":"Sabre\\Event\\EventEmitter","type":"->","args":["method:PUT",[{"absoluteUrl":"https://cloud.conscious-consulting.group/remote.php/dav/calendars/thomas.g/personal/706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.conscious-consulting.group/remote.php/dav/calendars/thomas.g/personal/706b30ef-e5fe-40b5-a65f-f3fda7538ad3.ics","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/remote.php","line":165,"args":["/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/vhosts/conscious-consulting.group/cloud.conscious-consulting.group/apps/dav/lib/CalDAV/CalDavBackend.php","Line":1068,"CustomMessage":"--"},"userAgent":"Mac+OS+X/10.15.4 (19E287) CalendarAgent/930.4.1","version":"18.0.3.0"}

**Comment by j-ed** [comment]
@tomdrops It would be nice if you could insert a line containing three back ticks (**```**) before and after the log lines to improve the readability 😉

**Comment by q-wertz** [comment]
Have the same issue. MacOS Thunderbird/Lightning filling server logs. The client is also sending Email invitations every half hour to the invitees. (In Thunderbird the Calender was NOT set to "Prefer client side email scheduling")
NC Server is 18.0.6
I "managed" to get the same error once on my Ubuntu Client. I think there it occurred when I tested the setup with disabled "Prefer client side email scheduling" and used the server side scheduling...

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
