### ISSUE TITLE
Update failled (17 to 18)

### ISSUE THREAD

**Issue by MrSanjb** [nextcloud/server#20739]
Hello
I wanted to update my nextcloud 17 to the lastes (18.0.4) via the webupdater (I don't have a consol access).
It started weel untill I got this error : 
Doctrine\DBAL\Schema\SchemaException: The table with name '4v1v8_cloud.oc_direct_edit' already exists.
With the error message that the update failled and I have to report the issue to the community.
Any idea how to fix the issue?

Thanks

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by MrSanjb** [comment]
Hello
Ok, thanks for the answer.
