### ISSUE TITLE
Trouble setting up SAML using WSO2

### ISSUE THREAD

**Issue by turbomettwurst** [nextcloud/server#2074]
I am currently evaluating nextcloud for proper purchase. Unfortunately i ran into issues authorizing my users against a SAML IDP. Maybe someone could give a pointer?

### Steps to reproduce
1. Activate SAML authentication as seen here:
![2016-11-10_12 35 09](https://cloud.githubusercontent.com/assets/6160921/20175316/6b81b3f6-a742-11e6-83c7-46298d457423.png)
The SSL Cert used here is WSO2s Certificate, exported from Firefox

2. Register a new Service Provider in WSO2
![2016-11-10_12 34 50](https://cloud.githubusercontent.com/assets/6160921/20175354/9efec368-a742-11e6-96e2-84b99dbb7a3f.png)

3. Log in using a second Browser with an activated SAML Tracer and try to understand the output (i kinda failed there...)
SAML XML:
`<?xml version="1.0" encoding="UTF-8"?>
<saml2p:Response Destination="https://thedomain.weus.ed/index.php/apps/user_saml/saml/acs"
    ID="fjhljkfoeihnofcjapmagocnmofpibcmoflhnlek"
    InResponseTo="ONELOGIN_9a5d7f4b21e7f1ca80597943709ed74974fc6b4d"
    IssueInstant="2016-11-10T11:19:25.353Z" Version="2.0"
    xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol">
    <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
        xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://identity.workspace.domain.tld</saml2:Issuer>
    <saml2p:Status><saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success"/> </saml2p:Status>
    <saml2:Assertion ID="negnpbibngacadflomalckilakinngoclomfiagd"
        IssueInstant="2016-11-10T11:19:25.353Z" Version="2.0"
       xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema">
        <saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">https://identity.workspace.domain.tld</saml2:Issuer>
        <ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
           <ds:SignedInfo><ds:CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"/><ds:SignatureMethod Algorithm="http://www.w3.org/2000/09/xmldsig#rsa-sha1"/>
                <ds:Reference URI="#negnpbibngacadflomalckilakinngoclomfiagd">
                    <ds:Transforms><ds:Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature"/>
                        <ds:Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#"><ec:InclusiveNamespaces PrefixList="xs" xmlns:ec="http://www.w3.org/2001/10/xml-exc-c14n#"/></ds:Transform>
                    </ds:Transforms><ds:DigestMethod Algorithm="http://www.w3.org/2000/09/xmldsig#sha1"/>
                    <ds:DigestValue>T+WKnNevosKXkwCnWRqpnbb8QuM=</ds:DigestValue>
                </ds:Reference>
            </ds:SignedInfo>
            <ds:SignatureValue>Z8otA6HDTxrtdoiI8C7k+vwr7JKdzak9RHb8KV66KfOsQ/ipLi9R/WGiJ0q2NRsMIP2VJtPRyI2+fuY/nmaPs+7KiIdMlMdI11jOR4YLGtFg6BQbcQbFjheACJ8Z4z+augJ5MpVFWPKmnSNsj8QYYvnjVObfIeQ8ZOJhwc/28b8Ce8x4WXvT3Nn2T+4ntDuC7zTJdlYtyfvX5kuDyJZ+2rgOatzgXkyXGeqq1GWHBh9wjdZSzzwcJ835DmTUDeLyjhtRzGnu1xOx8sqGZCKjIQq5tjn4IlyjzWgJ8a/lCSjUAWJqCRsCok7dFQS6JX9qzPd2KPUJZDlUdVaT9g0W4A==</ds:SignatureValue>
            <ds:KeyInfo>
                <ds:X509Data>
                    <ds:X509Certificate>MIIGTzCCBTegAwIBAgIKEKRuBwAAAAAA7zANBgkqhkiG9w0BAQUFADBDMRMwEQYKCZImiZPyLGQBGRYDbmV0MRYwFAYKCZImiZPyLGQBGRYGd2l0Y29tMRQwEgYDVQQDEwtXSVQtREMwMS1DQTAeFw0xNTAxMzAwOTEzMjdaFw0xOTA4MjYwODMzMjFaMHgxCzAJBgNVBAYTAkRFMQswCQYDVQQIEwJIRTESMBAGA1UEBxMJV2llc2JhZGVuMRQwEgYDVQQKEwtXaVRDT00gR21iSDELMAkGA1UECxMCSVQxJTAjBgNVBAMTHGlkZW50aXR5LndvcmtzcGFjZS53aXRjb20uZGUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCUNach+Aqz5DqW6FBwbr/a2gudQThMzavP4cTWRPUzzJW3CPqCF36V10rS20fWjhRDzBVw1vtpcz+o7WGWHYuffMFojcUoY73tzKSEB0zbZSFFNqCvsuWj0ASq1CwQmUsdWeMQ2DwSuTSYp3qPyDbkyNf9wI6AVEoBYJwaVRbtkgHCKAviMCX0aYbXS7LfydmKLOMRjJIm1wp52rLz4ilbtEV7O6CWVLaP6IkJ6XGdv+g9/brV+we3OpSLso4g+8DK0iax0LFSYhKKHk8+r8nO7kkzxICj+D83xR6TwIA5CyNbBurqExCm7u0uJXe71OLcsJOC7WRcSPUefWccM59vAgMBAAGjggMOMIIDCjAdBgNVHQ4EFgQUq1k3t1IrzAQXjKT9Jcndhx7e4fgwHwYDVR0jBBgwFoAUfpk12M7O95ljO2ZWpY39hNGbe00wge8GA1UdHwSB5zCB5DCB4aCB3qCB24YkaHR0cDovL2NybC53aXRjb20uZGUvV0lULURDMDEtQ0EuY3JshoGybGRhcDovLy9DTj1XSVQtREMwMS1DQSxDTj1XSVQtQ0EwMSxDTj1DRFAsQ049UHVibGljJTIwS2V5JTIwU2VydmljZXMsQ049U2VydmljZXMsQ049Q29uZmlndXJhdGlvbixEQz13aXRjb20sREM9bmV0P2NlcnRpZmljYXRlUmV2b2NhdGlvbkxpc3Q/YmFzZT9vYmplY3RDbGFzcz1jUkxEaXN0cmlidXRpb25Qb2ludDCCAQIGCCsGAQUFBwEBBIH1MIHyMIGpBggrBgEFBQcwAoaBnGxkYXA6Ly8vQ049V0lULURDMDEtQ0EsQ049QUlBLENOPVB1YmxpYyUyMEtleSUyMFNlcnZpY2VzLENOPVNlcnZpY2VzLENOPUNvbmZpZ3VyYXRpb24sREM9d2l0Y29tLERDPW5ldD9jQUNlcnRpZmljYXRlP2Jhc2U/b2JqZWN0Q2xhc3M9Y2VydGlmaWNhdGlvbkF1dGhvcml0eTBEBggrBgEFBQcwAoY4aHR0cDovL2NybC53aXRjb20uZGUvV0lULURDMDEud2l0Y29tLm5ldF9XSVQtREMwMS1DQS5jcnQwDgYDVR0PAQH/BAQDAgWgMDwGCSsGAQQBgjcVBwQvMC0GJSsGAQQBgjcVCIaS2GmM+B+B+Y0zhvz5CoH4+yyBUIT48kSZsSECAWQCAQIwEwYDVR0lBAwwCgYIKwYBBQUHAwEwGwYJKwYBBAGCNxUKBA4wDDAKBggrBgEFBQcDATBQBgNVHREESTBHghxpZGVudGl0eS53b3Jrc3BhY2Uud2l0Y29tLmRlghhpZGVudGl0eS1tZ210LndpdGNvbS5uZXSCDWlkZW50aXR5LW1nbXQwDQYJKoZIhvcNAQEFBQADggEBAHqIZfscKRdgi8dbKotq5OCEUg3RJj3nKdm8BfYFnADJCp1blGPk55g+btnFExxq9oZr2NUOxn/K5NV82Zt9L8qa3r4C/m5tvR01HFksS/8aSFspHsb3EJB5LTCJX8AAOZ6DEFx3Fwoz1uXEMazdYW9Mr+B1tonWGHJwu44IjpH9D4sOqaWpbpywxWcgLIKb1pNZ6aKjTVKBZkjasbC4FeuZhIyFEdT1um4O8gYFtPhmA/h6U2kPkQvYWP50D41VTj8flpjn1wpOr2FdWAZ9nKIc1FavixKekLQMRbi1yIV0tQCLYYEVJrSqVAnPDsDPQWAr1095qjpmW4kHFcTvfpU=</ds:X509Certificate>
                </ds:X509Data>
            </ds:KeyInfo>
        </ds:Signature>
        <saml2:Subject>
            <saml2:NameID Format="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress">4730</saml2:NameID>
            <saml2:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer"><saml2:SubjectConfirmationData InResponseTo="ONELOGIN_9a5d7f4b21e7f1ca80597943709ed74974fc6b4d"
                NotOnOrAfter="2016-11-10T11:24:25.353Z"
                Recipient="https://thedomain.weus.ed/index.php/apps/user_saml/saml/acs"/></saml2:SubjectConfirmation>
        </saml2:Subject>
        <saml2:Conditions NotBefore="2016-11-10T11:19:25.353Z" NotOnOrAfter="2016-11-10T11:24:25.353Z">
            <saml2:AudienceRestriction>
                <saml2:Audience>https://thedomain.weus.ed/index.php/apps/user_saml/saml/metadata</saml2:Audience>
            </saml2:AudienceRestriction>
        </saml2:Conditions>
        <saml2:AuthnStatement AuthnInstant="2016-11-10T11:19:25.354Z">
            <saml2:AuthnContext>
                <saml2:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:Password</saml2:AuthnContextClassRef>
            </saml2:AuthnContext>
        </saml2:AuthnStatement>
        <saml2:AttributeStatement>
            <saml2:Attribute Name="http://wso2.org/claims/preferred_username"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">4730</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="http://wso2.org/claims/emailaddress"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">A.LastName@domain.tld</saml2:AttributeValue>
            </saml2:Attribute>
            <saml2:Attribute Name="http://wso2.org/claims/fullname"
                NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
                <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">LastName, Andreas</saml2:AttributeValue>
            </saml2:Attribute>
        </saml2:AttributeStatement>
    </saml2:Assertion>
</saml2p:Response>`

the request
![request](https://cloud.githubusercontent.com/assets/6160921/20175797/dc479180-a744-11e6-9705-642f3bdab517.png)

and finally the response:
![response](https://cloud.githubusercontent.com/assets/6160921/20175799/dfe80ef0-a744-11e6-9fcd-74f864e57375.png)

### Expected behaviour
I would very much like to log in into my nextcloud instance  :)

### Actual behaviour
After entering my credentials on the wso2 page i am being redirected to a blank page without any errors

### Server configuration
**Operating system**:
CentOS 7
**Web server:**
Apache 2.4 (from SCL)
**Database:**
MariaDB 10.1 (from SCL)
**PHP version:**
PHP 5.6 (from SCL)

**Nextcloud version:** 
10.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
manually from zip file
**Signing status:**
<details>
<summary>No errors have been found.</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

</details>

**List of activated apps:**
<details>

<summary>Contacts, SAML Auth</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

</details>

**The content of config/config.php:**
<details>
<summary><?php
$CONFIG = array (
  'trusted_domains' => 
  array (
    0 => 'obfucated.as.usual',
  ),
  'datadirectory' => '/var/local/nextcloud/name/config',
  'overwrite.cli.url' => 'https://obfuscated.as.usual,
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'db',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'user',
  'dbpassword' => 'YoMomma',
  'logtimezone' => 'UTC',
  'installed' => true,
);</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no, just saml

### Client configuration
**Browser:**
Firefox, Chromium, Opera (most recent versions as of today)
**Operating system:**
Arch Linux
#### Web server error log
<details>
<summary>
```
123.123.123.123- - [10/Nov/2016:13:03:15 +0100] "GET / HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"
123.123.123.123- - [10/Nov/2016:13:03:15 +0100] "GET /index.php/login HTTP/1.1" 302 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"
123.123.123.123- - [10/Nov/2016:13:03:15 +0100] "GET /index.php/apps/user_saml/saml/login?requesttoken=TDosBF0jBigsFzopCnsrIjV%2BZSkqKw1wNhAbcQYhMVk%3D%3A8PNMetMFySlyR5jkZLRZXblFYXC2jCSmso99AAz7qP8%3D HTTP/1.1" 303 - "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"
123.123.123.123- - [10/Nov/2016:13:03:17 +0100] "POST /index.php/apps/user_saml/saml/acs HTTP/1.1" 303 - "https://identity.workspace.domain.tld/samlsso?SAMLRequest=pVNNj9owEL3zK1DuJJimLGtBJAr9QKKAINtDLyvjTIrVxHY9k8L%2B%2B3USELTqcmkuUcbz3rz3PBmjKAvLpxUd9BZ%2BVYDU6frnVBYaeXM4CSqnuRGokGtRAnKSfDf9uuSDsM%2BtM2SkKYK%2FYPdRAhEcKaNb2GI%2BCdarj8v158XqecCYjAXIuD%2BSWSzj%2FWAUs4d8NNzHEMfDR8gfHsVQZC30Gzj0PJPA0wadlg2xgoVGEpp8vc%2BGPcZ6rJ%2ByAe%2B%2F4%2Bz99xY692aVFtTAD0QWeRSpDDQpegmPxv1EKySER0XSlGEGUW0M0bTwzdn5B6UzpX%2FcN7xvm5B%2FSdNNb7PepS3J9BLEzGisSnA7cL%2BVhKft8qopVwXgQThPcBEjC1NlkSeFU2gPNhLWYlR5rudaYyM0EhKDpJkyrr95k4tL%2FpO1BBKZIDGObkmvYyxfefeL%2BcYUSr409fr5ZFwp6O2QWMiaisp6edPKK40WpMoVnK%2B6yasozHHmQBBMAnIVBN3oj%2BHnJYasWWmfKsGJujNTWu8U65uGk5B0DuYazm37rPD7uYU8ubvCksu6z5c3%2FuXXJas3AqSfnTrhxRtH55D%2BSd6qju7ITjqX49v%2FM3kF&RelayState=https%3A%2F%2Ffilesharing.domain.tld%2Findex.php%2Fapps%2Fuser_saml%2Fsaml%2Flogin" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"
123.123.123.123- - [10/Nov/2016:13:03:17 +0100] "GET / HTTP/1.1" 302 - "https://identity.workspace.domain.tld/samlsso?SAMLRequest=pVNNj9owEL3zK1DuJJimLGtBJAr9QKKAINtDLyvjTIrVxHY9k8L%2B%2B3USELTqcmkuUcbz3rz3PBmjKAvLpxUd9BZ%2BVYDU6frnVBYaeXM4CSqnuRGokGtRAnKSfDf9uuSDsM%2BtM2SkKYK%2FYPdRAhEcKaNb2GI%2BCdarj8v158XqecCYjAXIuD%2BSWSzj%2FWAUs4d8NNzHEMfDR8gfHsVQZC30Gzj0PJPA0wadlg2xgoVGEpp8vc%2BGPcZ6rJ%2ByAe%2B%2F4%2Bz99xY692aVFtTAD0QWeRSpDDQpegmPxv1EKySER0XSlGEGUW0M0bTwzdn5B6UzpX%2FcN7xvm5B%2FSdNNb7PepS3J9BLEzGisSnA7cL%2BVhKft8qopVwXgQThPcBEjC1NlkSeFU2gPNhLWYlR5rudaYyM0EhKDpJkyrr95k4tL%2FpO1BBKZIDGObkmvYyxfefeL%2BcYUSr409fr5ZFwp6O2QWMiaisp6edPKK40WpMoVnK%2B6yasozHHmQBBMAnIVBN3oj%2BHnJYasWWmfKsGJujNTWu8U65uGk5B0DuYazm37rPD7uYU8ubvCksu6z5c3%2FuXXJas3AqSfnTrhxRtH55D%2BSd6qju7ITjqX49v%2FM3kF&RelayState=https%3A%2F%2Ffilesharing.domain.tld%2Findex.php%2Fapps%2Fuser_saml%2Fsaml%2Flogin" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"
123.123.123.123- - [10/Nov/2016:13:03:17 +0100] "GET /index.php/login HTTP/1.1" 302 - "https://identity.workspace.domain.tld/samlsso?SAMLRequest=pVNNj9owEL3zK1DuJJimLGtBJAr9QKKAINtDLyvjTIrVxHY9k8L%2B%2B3USELTqcmkuUcbz3rz3PBmjKAvLpxUd9BZ%2BVYDU6frnVBYaeXM4CSqnuRGokGtRAnKSfDf9uuSDsM%2BtM2SkKYK%2FYPdRAhEcKaNb2GI%2BCdarj8v158XqecCYjAXIuD%2BSWSzj%2FWAUs4d8NNzHEMfDR8gfHsVQZC30Gzj0PJPA0wadlg2xgoVGEpp8vc%2BGPcZ6rJ%2ByAe%2B%2F4%2Bz99xY692aVFtTAD0QWeRSpDDQpegmPxv1EKySER0XSlGEGUW0M0bTwzdn5B6UzpX%2FcN7xvm5B%2FSdNNb7PepS3J9BLEzGisSnA7cL%2BVhKft8qopVwXgQThPcBEjC1NlkSeFU2gPNhLWYlR5rudaYyM0EhKDpJkyrr95k4tL%2FpO1BBKZIDGObkmvYyxfefeL%2BcYUSr409fr5ZFwp6O2QWMiaisp6edPKK40WpMoVnK%2B6yasozHHmQBBMAnIVBN3oj%2BHnJYasWWmfKsGJujNTWu8U65uGk5B0DuYazm37rPD7uYU8ubvCksu6z5c3%2FuXXJas3AqSfnTrhxRtH55D%2BSd6qju7ITjqX49v%2FM3kF&RelayState=https%3A%2F%2Ffilesharing.domain.tld%2Findex.php%2Fapps%2Fuser_saml%2Fsaml%2Flogin" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"
123.123.123.123- - [10/Nov/2016:13:03:17 +0100] "GET /index.php/apps/user_saml/saml/login?requesttoken=Ig0oAV18Lh0sdx0BFw0CAxZHDgAhcCkEASYqDEM4M1g%3D%3AVgJHe%2Besy3KQOCCJyu9sS9H2nnrO%2FZQlnPBmzQOE%2BC4%3D HTTP/1.1" 303 - "https://identity.workspace.domain.tld/samlsso?SAMLRequest=pVNNj9owEL3zK1DuJJimLGtBJAr9QKKAINtDLyvjTIrVxHY9k8L%2B%2B3USELTqcmkuUcbz3rz3PBmjKAvLpxUd9BZ%2BVYDU6frnVBYaeXM4CSqnuRGokGtRAnKSfDf9uuSDsM%2BtM2SkKYK%2FYPdRAhEcKaNb2GI%2BCdarj8v158XqecCYjAXIuD%2BSWSzj%2FWAUs4d8NNzHEMfDR8gfHsVQZC30Gzj0PJPA0wadlg2xgoVGEpp8vc%2BGPcZ6rJ%2ByAe%2B%2F4%2Bz99xY692aVFtTAD0QWeRSpDDQpegmPxv1EKySER0XSlGEGUW0M0bTwzdn5B6UzpX%2FcN7xvm5B%2FSdNNb7PepS3J9BLEzGisSnA7cL%2BVhKft8qopVwXgQThPcBEjC1NlkSeFU2gPNhLWYlR5rudaYyM0EhKDpJkyrr95k4tL%2FpO1BBKZIDGObkmvYyxfefeL%2BcYUSr409fr5ZFwp6O2QWMiaisp6edPKK40WpMoVnK%2B6yasozHHmQBBMAnIVBN3oj%2BHnJYasWWmfKsGJujNTWu8U65uGk5B0DuYazm37rPD7uYU8ubvCksu6z5c3%2FuXXJas3AqSfnTrhxRtH55D%2BSd6qju7ITjqX49v%2FM3kF&RelayState=https%3A%2F%2Ffilesharing.domain.tld%2Findex.php%2Fapps%2Fuser_saml%2Fsaml%2Flogin" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/54.0.2840.59 Safari/537.36 OPR/41.0.2353.46"

error log is empty
</summary>
```</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>
empty, even after setting the loglevel to 0
</summary>
```

```

</details>

#### Browser log
<details>
<summary>See the SAML Logs above :)</summary>
```

```

</details>

**Comment by LukasReschke** [comment]
> I am currently evaluating nextcloud for proper purchase. Unfortunately i ran into issues authorizing my users against a SAML IDP. Maybe someone could give a pointer?

Please reach out to sales@nextcloud.com if you're interested in deploying this in an enterprise deployment and require help setting up your environment. Otherwise https://help.nextcloud.com is the place to ask. This here is the issue tracker for bugs only.

With regard to your issue: https://github.com/nextcloud/user_saml/blob/5855e6e2ccb352ea8aa8637e17c885e21be76e81/lib/controller/samlcontroller.php#L107 may be a place where you could do a `var_dump($auth-> getAttributes())` to check which attributes are sent. I suppose the `preferred_username` field is empty.

**Comment by turbomettwurst** [comment]
sorry about posting in the wrong corner, will try to contact pre sales support

**Comment by LukasReschke** [comment]
No worries. Please make sure to mention that I referred you to them :-)

**Comment by kundansingh27feb** [comment]
Hi All,

I am getting the below error while enabling the SSO & SAML authentication. I am using nextcloud 12.0.4. Kindly let me know the issue.
**ERROR:**
    Account not provisioned.
    Your account is not provisioned, access to this service is thus not possible.
And the SSO & SAML authentication page showing me only 3 filed no certificate or IDP filed are shown by this.

**Comment by inem88** [comment]
Do you resolve this problem? Anybody??

**Comment by turbomettwurst** [comment]
no this issue was never resolved

**Comment by inem88** [comment]
After many tries - I done it. For example in your settings you need at least to set "http://wso2.org/claims/preferred_username" instead "preferred_username" in first field in Nextcloud
