### ISSUE TITLE
Repeated user results on search page (LDAP, PHP 7.2)

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#20745]
(This is mostly a reminder for me)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have LDAP configured and PHP up to 7.2 (old API)
2. Go to users page
3. Do a search

### Expected behaviour

* Looked for user is being shown once

### Actual behaviour

* Looked for user is being shown infinitely

**Comment by blizzz** [comment]
Reproducible also on CLI (and only with search term):

```
╚> php occ ldap:search 'j' --limit=2 --offset=2
Joyce, George (person_133173) (person_133173)

╚> php occ ldap:search 'j' --limit=2 --offset=12
Joyce, George (person_133173) (person_133173)

╚> php occ ldap:search '' --limit=2 --offset=0
Krista, Love (person_13317) (person_13317)
Victoria, Kennedy (person_133170) (person_133170)

╚> php occ ldap:search '' --limit=2 --offset=20
Ida, Mason (person_133172) (person_133172)
Joyce, George (person_133173) (person_133173)
```

**Comment by henry-rd** [comment]
Same problem on latest Nextcloud 19 (clean v.18 install + upgrade to 19) on PHP 7.4.
User directory from Windows Server 2019 AD

![image](https://user-images.githubusercontent.com/66421448/83756050-150e7280-a634-11ea-9773-deb671291736.png)

**Comment by nigle-dev** [comment]
Same here, 19.0.0 clean install with php 7.4 and FreeIPA as backend.
Also navigating to users -> everybody gives an infinite loop of the same users.

**Comment by CHBMB** [comment]
Just hit this issue on a fresh install of 19.0.0 and can confirm https://github.com/nextcloud/server/pull/21108 fixes the issue for me.

Thanks @blizzz
