### ISSUE TITLE
Indeterminate checkbox style in files app inconsistently applied

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#20777]
### Steps to reproduce
1. Go to the files app and navigate to a folder with some files.
2. Select a file (but not all files).

### Expected behaviour
The checkbox to select all files should have an indeterminate state in case one file, but not all files are selected.

### Actual behaviour
The checkbox to select all files does not show an indeterminate state.
However, if you search for a file so that other files are filtered and then select all files, the checkbox shows the indeterminate state. This is already inconsistent, especially since the state stays when you clear the search. And even if you unselect the files, the indeterminate state stays. See the GIF below for clarification:

![checkbox](https://user-images.githubusercontent.com/2496460/80831443-230f4480-8beb-11ea-91ce-9a41ad66005d.gif)

@jancborchardt Could you please confirm that it is the expected behaviour to show the indeterminate state whenever files, but not all files are selected?

@nextcloud/javascript Are there any plans to migrate the files app to vue, or does it still make sense to fix the problem in the current javascript code?

### Server configuration

**Nextcloud version:** latest master 24bb4a05c46069d459086a36cfc896d1f5b6915e

**Comment by jancborchardt** [comment]
> @jancborchardt Could you please confirm that it is the expected behaviour to show the indeterminate state whenever files, but not all files are selected?

Yup, confirmed! :)

**Comment by ChristophWurst** [comment]
> @nextcloud/javascript Are there any plans to migrate the files app to vue, or does it still make sense to fix the problem in the current javascript code?

There are some plans but nothing specific has been started I think. So yeah, fixing this in the old code makes sense if it's not too much effort.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by raimund-schluessler** [comment]
The issue persists with 25.0.4 and 26.0.0 dev.

**Comment by skjnldsv** [comment]
Closed with upcoming files to vue. Will be slowly mitigated view per view
