### ISSUE TITLE
No invite reply sent when accepting calendar event to NC calendar in Thunderbird

### ISSUE THREAD

**Issue by pi-xel** [nextcloud/server#20773]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Add a NC calendar in Thunderbird via CalDav. Make sure that client-side scheduling in TB is disabled.
2. Send an event invitation from another calendar to the email linked to the calendar.
3. After receiving the invite in TB, click on the arrow next to the "Accept" button in the TB dialog popping up over the email. Click "Send a response now" from the dropdown and then select the NC calendar to store the event.

### Expected behaviour
The event is added to the calendar and NC sends a response to the inviter.

### Actual behaviour
The event is added to the calendar, but no response is sent.

If I now open the event in TB and select a different status (like tentative) and then "Send a response now", NC correctly sends the updated status to the inviter.

I guess this could be related to https://github.com/nextcloud/calendar/issues/2144 as it could be that the same mechanism preventing to send invites on a new event when the organizer is not the calendar owner in a shared calendar also prevents to send the reply to the organizer here (to stress this, the bug only occurs if the reply is to be sent on a new event added to NC via TB of which the organizer is someone else, not when the event is updated from TB after adding it).

Not sure if it's also related to https://github.com/nextcloud/server/issues/17915.

### Server configuration

**Operating system: Ubuntu 16.04**

**Web server: Apache**

**Database: MySQL**

**PHP version: 7.3**

**Nextcloud version: 18.03**

**Updated from an older Nextcloud/ownCloud or fresh install: Updated**

**Where did you install Nextcloud from: nextcloud.com**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by q-wertz** [comment]
As I am also having some troubles with the calendars and played around a little bit:
I think when I tried this scenario the attendee status changed with the next sync of Thunderbird. 
I understand it in that way: 
server side the attendee is confirmed (maybe check online in the calendar application) and Thunderbird gets this status with the next synchronization.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by section1** [comment]
This issue still exist. I'm using NC version 25.0.5 and Calendar version 4.3.4 when i accept a invite from say gmail or hotmail account NC never sends an Accepted reply.
