### ISSUE TITLE
Enforcing two-factor authentication should check admin for enabled two-factor

### ISSUE THREAD

**Issue by ngaggi** [nextcloud/server#20783]
Hello...

When "enforcing two-factor authentication" option is enabled, a check should be done proving (all or at least one) admin account for enabled two-factor.

Today, no check takes place and there is the chance to lock out yourself.

Doc: https://docs.nextcloud.com/server/18/admin_manual/configuration_user/two_factor-auth.html

**Comment by jospoortvliet** [comment]
@ngaggi users who do not yet have 2FA enabled will be prompted to set it up the first time. Does that not work for your use case? If not, please re-open.

**Comment by ngaggi** [comment]
Pls reopen.

I just set up a fresh Nextcloud instance to play with only one admin account. After enabling enforcing two-factor authentication, I locked my self out without any check or notice.

I thought erroneously, the setting is for all the accounts created AFTER this setting.
