### ISSUE TITLE
Safari v11.1.2 / v13.1 Shared Link Expiry Date not visible

### ISSUE THREAD

**Issue by p-sims** [nextcloud/server#20780]
### Steps to reproduce
1. Login to a nextcloud server using Safari v11.1.2 or v13.1 (presuming Issue is the same in intermediate version but not tested). [ensure default shared link expiry dates are enabled]
2. Click on sharing for a file, then click the '+' next to share link
3. Once the link has been created click on the '...' to customise. 
### Expected behaviour
As per this screen shot take using firefox expiry date should be visible:
![Screenshot 2020-05-02 at 09 01 27](https://user-images.githubusercontent.com/64636731/80858790-92b91a00-8c53-11ea-902e-53dcf58e4891.png)

### Actual behaviour
As per these screenshots expire data isn't visible in safari.
![Screenshot 2020-05-01 at 17 09 41](https://user-images.githubusercontent.com/64636731/80858725-10c8f100-8c53-11ea-81e2-c57fd8f541c9.png)
![Screenshot 2020-05-01 at 17 09 50](https://user-images.githubusercontent.com/64636731/80858726-11fa1e00-8c53-11ea-958e-7e2ed43385a9.png)

### Server configuration

**Operating system:** 
Debian Buster 

**Web server:**
Apache/2.4.38

**Database:**
MariaDB Version: 10.3.22

**PHP version:**
Version: 7.4.4

**Nextcloud version:** (see Nextcloud admin page)
<version>18.0.3.0</version>
**List of activated apps:**
<apps>
<num_installed>48</num_installed>
<num_updates_available>2</num_updates_available>
<app_updates>
<groupfolders>6.0.6</groupfolders>
<spreed>8.0.8</spreed>
</app_updates>
<app_updates>...</app_updates>
</apps>
<apps>...</apps>

### Client configuration
**Browser: / Operating system:**
Safari 11.1.2 (MacOS 10.11)
Safari 13.1 (MacOS 10.14)

#### Nextcloud log (data/nextcloud.log)
Attached redacted for relevant time frame
[nextcloud.log](https://github.com/nextcloud/server/files/4567325/nextcloud.log)

#### Browser log
[Console Log (Safari 13.1).txt](https://github.com/nextcloud/server/files/4567312/Console.Log.Safari.13.1.txt)

**Comment by kesselb** [comment]
cc @nextcloud/mac

**Comment by MorrisJobke** [comment]
Can confirm. On 19.0.0 beta 5 it's also like that - I clicked on expiry date, selected one and then the input is empty:

![Bildschirmfoto 2020-05-04 um 14 18 49](https://user-images.githubusercontent.com/245432/80965044-30f2de80-8e12-11ea-9b5b-056ad112eb45.png)

**Comment by alexbijma** [comment]
i have the same issue, is there any work around or news on this?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by MorrisJobke** [comment]
Works find in 21.0.2 RC1
