### ISSUE TITLE
Change "Open in ONLYOFFICE" to "View..." or "Edit in ONLYOFFICE" according to the share permissions

### ISSUE THREAD

**Issue by loelkes** [nextcloud/server#20785]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
After sharing a document via a public link it is not clearly visible for the receiving user that this document is shared as read-only. Even after opening ONLYOFFICE there's no message that the document is read-only. Users who are not familiar with the different UIs of ONLYOFFICE (almost no buttons in read-only mode) might think that something is malfunctioning. 

**Describe the solution you'd like**
Instead of "Open in ONLYOFFICE" change the buttons according to the share state to "View in ONLYOFFICE (read-only)" and "Edit in ONLYOFFICE".

**Describe alternatives you've considered**
Feature request to ONLYOFFICE so that the editor shows a warning.

**Additional context**
A user shared a document and forgot or mistakenly did not enable editing [for](url) that share. Users clicking on the link thought nextcloud/ONLYOFFICE was broken oder malfunctioning since the sharing user said the document can be edited.

This is related to #19489.

**Comment by kesselb** [comment]
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/ should be the right repository for such a request because the button is added by their app to the public sharing page: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/blob/f9e427ea53866568271a950c27343ca0ebee8aae/js/main.js#L365-L368
