### ISSUE TITLE
User Avatar crossed by dotted line

### ISSUE THREAD

**Issue by wagnerfl85** [nextcloud/server#20796]
### Steps to reproduce
1. Log in to Nextcloud (Browser)
2. Go to Settings
3. Click on privacy

or

1. Log in to Nextcloud (Browser)
2. Go to Talk
3. Look at you contacts

### Expected behaviour
You should see normal user avatar icons

### Actual behaviour
All of the user avatars are crossed by dotted lines
![grafik](https://user-images.githubusercontent.com/42145591/80920615-3a783a00-8d71-11ea-9934-02ae88cfc071.png)

### Server configuration

**Operating system:** Ubuntu 16.04

**Web server:** Apache 2.4.18

**Database:** MySQL 5.7.29

**PHP version:** 7.3

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from older Version

**Where did you install Nextcloud from:** official Nextcloud Server ZIP 

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - audioplayer: 2.10.0
  - bookmarks: 2.3.4
  - breezedark: 18.0.13
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 0.8.2
  - documentserver_community: 0.1.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - nextcloud_announcements: 1.7.0
  - notes: 3.2.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - rainloop: 6.1.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - side_menu: 1.3.4
  - spreed: 8.0.8
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.12.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_gateway: 0.16.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "debug": false,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.spit-munich.de",
            "spit-munich.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.spit-munich.de\/",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "maintenance": false,
        "theme": "",
        "filelocking.enabled": "false",
        "data-fingerprint": "a4ef744b67b31984f4e49189b6cbbd40",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "app_install_overwrite": [
            "audioplayer"
        ],
        "mail_sendmailmode": "smtp",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "trashbin_retention_obligation": "auto",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpdebug": true,
        "mail_smtpstreamoptions": {
            "ssl": {
                "allow_self_signed": true,
                "verify_peer": false,
                "verify_peer_name": false
            }
        }
    },
    "apps": {
        "accessibility": {
            "enabled": "yes",
            "installed_version": "1.4.0",
            "types": ""
        },
        "activity": {
            "enabled": "yes",
            "installed_version": "2.11.0",
            "types": "filesystem"
        },
        "admin_audit": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "audioplayer": {
            "enabled": "yes",
            "installed_version": "2.10.0",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "9899"
        },
        "bookmarks": {
            "enabled": "[\"admin\",\"freunde\",\"wagner\",\"Spider IT Munich\",\"Customer\"]",
            "installed_version": "2.3.4",
            "types": ""
        },
        "breezedark": {
            "enabled": "yes",
            "installed_version": "18.0.13",
            "types": ""
        },
        "bruteforcesettings": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": ""
        },
        "calendar": {
            "enabled": "[\"Customer\",\"Meierhold\",\"Spider IT Munich\",\"freunde\",\"wagner\",\"TheJapaneseUnicorns\"]",
            "installed_version": "2.0.3",
            "types": ""
        },
        "cloud_federation_api": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "filesystem"
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "contacts": {
            "enabled": "[\"Customer\",\"Meierhold\",\"Spider IT Munich\",\"wagner\",\"TheJapaneseUnicorns\"]",
            "installed_version": "3.3.0",
            "types": ""
        },
        "core": {
            "OC_Channel": "stable",
            "enterpriseLogoChecked": "yes",
            "installed.bundles": "[\"CoreBundle\"]",
            "installedat": "1469014772.9547",
            "lastcron": "1588525984",
            "lastupdateResult": "[]",
            "lastupdatedat": "1588525983",
            "moveavatarsdone": "yes",
            "oc.integritycheck.checker": "[]",
            "previewsCleanedUp": "1",
            "public_files": "files_sharing\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "remote_caldav": "dav\/appinfo\/v1\/caldav.php",
            "remote_calendar": "dav\/appinfo\/v1\/caldav.php",
            "remote_carddav": "dav\/appinfo\/v1\/carddav.php",
            "remote_contacts": "dav\/appinfo\/v1\/carddav.php",
            "remote_dav": "dav\/appinfo\/v2\/remote.php",
            "remote_files": "dav\/appinfo\/v1\/webdav.php",
            "remote_webdav": "dav\/appinfo\/v1\/webdav.php",
            "repairlegacystoragesdone": "yes",
            "scss.variables": "10e97b1a2648e4f835be75f0e772da8e",
            "shareapi_allow_group_sharing": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_enforce_expire_date": "no",
            "shareapi_enforce_links_password": "yes",
            "shareapi_expire_after_n_days": "7",
            "shareapi_only_share_with_group_members": "yes",
            "theming.variables": "939a90ad95e7ae4bd7630d60974bbee5",
            "updater.secret.created": "1587994497",
            "vendor": "nextcloud"
        },
        "dashboard": {
            "installed_version": "6.0.0",
            "types": ""
        },
        "dav": {
            "OCA\\DAV\\Migration\\ValueFixInsert_ran": "true",
            "buildCalendarReminderIndex": "yes",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "enabled": "yes",
            "installed_version": "1.14.0",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "sendEventRemindersPush": "yes",
            "types": "filesystem"
        },
        "deck": {
            "enabled": "yes",
            "installed_version": "0.8.2",
            "types": "dav"
        },
        "direct_menu": {
            "enabled": "no",
            "installed_version": "0.10.2",
            "ocsid": "169148",
            "types": ""
        },
        "documentserver_community": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "types": "filesystem"
        },
        "drawio": {
            "enabled": "no",
            "installed_version": "0.8.8",
            "types": "filesystem"
        },
        "external": {
            "enabled": "no",
            "installed_version": "",
            "ocsid": "166046",
            "sites": "***REMOVED SENSITIVE VALUE***",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "2 GB",
            "enabled": "yes",
            "installed_version": "1.13.1",
            "types": "filesystem"
        },
        "files_antivirus": {
            "av_chunk_size": "1024",
            "av_cmd_options": "",
            "av_host": "",
            "av_infected_action": "only_log",
            "av_mode": "socket",
            "av_path": "\/usr\/bin\/clamscan",
            "av_port": "0",
            "av_socket": "\/var\/run\/clamav\/clamd.ctl",
            "enabled": "no",
            "installed_version": "0.8.0.1",
            "ocsid": "157439",
            "signed": "true",
            "types": "filesystem"
        },
        "files_mindmap": {
            "enabled": "yes",
            "installed_version": "0.0.21",
            "types": ""
        },
        "files_pdfviewer": {
            "enabled": "[\"freunde\",\"wagner\",\"Spider IT Munich\",\"Customer\",\"HL\"]",
            "installed_version": "1.7.0",
            "types": ""
        },
        "files_retention": {
            "enabled": "no",
            "installed_version": "1.4.0",
            "types": "filesystem"
        },
        "files_rightclick": {
            "enabled": "[\"admin\"]",
            "installed_version": "0.15.2",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "incoming_server2server_share_enabled": "no",
            "installed_version": "1.10.1",
            "lookupServerUploadEnabled": "no",
            "outgoing_server2server_share_enabled": "no",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "no",
            "installed_version": "2.8.0",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem,dav"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.11.0",
            "types": "filesystem,dav"
        },
        "files_videoplayer": {
            "enabled": "[\"admin\",\"freunde\",\"Customer\",\"Spider IT Munich\",\"wagner\",\"TheJapaneseUnicorns\"]",
            "installed_version": "1.7.0",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "2.7.0",
            "types": "logging"
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "18.4.0",
            "types": ""
        },
        "logreader": {
            "enabled": "[\"admin\"]",
            "installed_version": "2.3.0",
            "levels": "00011",
            "relativedates": "1",
            "types": ""
        },
        "lookup_server_connector": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "mail": {
            "enabled": "[\"admin\",\"Spider IT Munich\"]",
            "installed_version": "1.3.4",
            "signed": "true",
            "types": ""
        },
        "maps": {
            "enabled": "yes",
            "installed_version": "0.1.6",
            "types": "filesystem"
        },
        "nextcloud_announcements": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
            "types": "logging"
        },
        "notes": {
            "enabled": "[\"admin\",\"freunde\",\"wagner\",\"Spider IT Munich\",\"Customer\"]",
            "installed_version": "3.2.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "2.6.0",
            "types": "logging"
        },
        "oauth2": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "types": "authentication"
        },
        "onlyoffice": {
            "DocumentServerUrl": "https:\/\/cloud.spit-munich.de\/index.php\/apps\/documentserver_community\/",
            "defFormats": "{\"docx\":true,\"pptx\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"doc\":true,\"ppt\":true,\"xls\":true}",
            "editFormats": "{\"csv\":true,\"docx\":true,\"pptx\":true,\"txt\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"rtf\":true}",
            "enabled": "yes",
            "installed_version": "4.1.4",
            "sameTab": "true",
            "types": "filesystem"
        },
        "openhab": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "types": ""
        },
        "ownnote": {
            "enabled": "no",
            "installed_version": "1.08",
            "ocsid": "168512",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceSpecialCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.8.0",
            "types": ""
        },
        "photos": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "privacy": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "readableLocation": "de",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "prevent_group_restriction"
        },
        "qownnotesapi": {
            "enabled": "yes",
            "installed_version": "20.1.0",
            "types": ""
        },
        "rainloop": {
            "enabled": "yes",
            "installed_version": "6.1.0",
            "types": ""
        },
        "recommendations": {
            "enabled": "yes",
            "installed_version": "0.6.0",
            "types": ""
        },
        "serverinfo": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.8.0",
            "types": ""
        },
        "settings": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": ""
        },
        "sharebymail": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "filesystem"
        },
        "side_menu": {
            "enabled": "[\"admin\"]",
            "installed_version": "1.3.4",
            "types": ""
        },
        "spreed": {
            "default_group_notification": "1",
            "enabled": "yes",
            "installed_version": "8.0.8",
            "project_access_invalidated": "1",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "start_calls": "0",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "turn_servers": "***REMOVED SENSITIVE VALUE***",
            "types": "prevent_group_restriction"
        },
        "support": {
            "enabled": "yes",
            "installed_version": "1.1.0",
            "types": "session"
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "1.6.0",
            "last_report": "{\"id\":\"ocuahfgg0a9x\",\"items\":[[\"server\",\"version\",\"16.0.5.1\"],[\"server\",\"code\",\"other\"],[\"server\",\"enable_avatars\",\"yes\"],[\"server\",\"enable_previews\",\"yes\"],[\"server\",\"memcache.local\",\"\\\\OC\\\\Memcache\\\\APCu\"],[\"server\",\"memcache.distributed\",\"none\"],[\"server\",\"asset-pipeline.enabled\",\"no\"],[\"server\",\"filelocking.enabled\",\"yes\"],[\"server\",\"memcache.locking\",\"none\"],[\"server\",\"debug\",\"yes\"],[\"server\",\"cron\",\"ajax\"],[\"php\",\"version\",\"7.1.30\"],[\"php\",\"memory_limit\",1073741824],[\"php\",\"max_execution_time\",3600],[\"php\",\"upload_max_filesize\",2097152],[\"database\",\"type\",\"mysql\"],[\"database\",\"version\",\"5.7.26\"],[\"database\",\"size\",251314176],[\"apps\",\"accessibility\",\"1.2.0\"],[\"apps\",\"activity\",\"2.9.1\"],[\"apps\",\"admin_audit\",\"1.6.0\"],[\"apps\",\"audioplayer\",\"2.8.4\"],[\"apps\",\"bookmarks\",\"2.3.1\"],[\"apps\",\"bruteforcesettings\",\"1.4.0\"],[\"apps\",\"calendar\",\"1.7.1\"],[\"apps\",\"cloud_federation_api\",\"0.2.0\"],[\"apps\",\"comments\",\"1.6.0\"],[\"apps\",\"contacts\",\"3.1.6\"],[\"apps\",\"dashboard\",\"6.0.0\"],[\"apps\",\"dav\",\"1.9.2\"],[\"apps\",\"deck\",\"disabled\"],[\"apps\",\"direct_menu\",\"disabled\"],[\"apps\",\"drawio\",\"disabled\"],[\"apps\",\"external\",\"disabled\"],[\"apps\",\"federatedfilesharing\",\"1.6.0\"],[\"apps\",\"federation\",\"1.6.0\"],[\"apps\",\"files\",\"1.11.0\"],[\"apps\",\"files_antivirus\",\"disabled\"],[\"apps\",\"files_pdfviewer\",\"1.5.0\"],[\"apps\",\"files_retention\",\"disabled\"],[\"apps\",\"files_rightclick\",\"0.15.1\"],[\"apps\",\"files_sharing\",\"1.8.0\"],[\"apps\",\"files_texteditor\",\"disabled\"],[\"apps\",\"files_trashbin\",\"1.6.0\"],[\"apps\",\"files_versions\",\"1.9.0\"],[\"apps\",\"files_videoplayer\",\"1.5.0\"],[\"apps\",\"firstrunwizard\",\"2.5.0\"],[\"apps\",\"gallery\",\"18.3.0\"],[\"apps\",\"logreader\",\"2.1.0\"],[\"apps\",\"lookup_server_connector\",\"1.4.0\"],[\"apps\",\"mail\",\"disabled\"],[\"apps\",\"maps\",\"0.1.2\"],[\"apps\",\"nextcloud_announcements\",\"1.5.0\"],[\"apps\",\"notes\",\"3.0.3\"],[\"apps\",\"notifications\",\"2.4.1\"],[\"apps\",\"oauth2\",\"1.4.2\"],[\"apps\",\"ownnote\",\"disabled\"],[\"apps\",\"password_policy\",\"1.6.0\"],[\"apps\",\"privacy\",\"1.0.0\"],[\"apps\",\"provisioning_api\",\"1.6.0\"],[\"apps\",\"rainloop\",\"disabled\"],[\"apps\",\"recommendations\",\"0.4.0\"],[\"apps\",\"serverinfo\",\"1.6.0\"],[\"apps\",\"sharebymail\",\"1.6.0\"],[\"apps\",\"spreed\",\"6.0.4\"],[\"apps\",\"support\",\"1.0.0\"],[\"apps\",\"survey_client\",\"1.4.0\"],[\"apps\",\"systemtags\",\"1.6.0\"],[\"apps\",\"tasks\",\"0.11.3\"],[\"apps\",\"templateeditor\",\"disabled\"],[\"apps\",\"text\",\"1.0.2\"],[\"apps\",\"theming\",\"1.7.0\"],[\"apps\",\"twofactor_backupcodes\",\"1.5.0\"],[\"apps\",\"twofactor_gateway\",\"0.14.1\"],[\"apps\",\"twofactor_totp\",\"disabled\"],[\"apps\",\"updatenotification\",\"1.6.0\"],[\"apps\",\"viewer\",\"1.1.0\"],[\"apps\",\"workflowengine\",\"1.6.0\"],[\"stats\",\"num_files\",150675],[\"stats\",\"num_users\",38],[\"stats\",\"num_storages\",60],[\"stats\",\"num_storages_local\",2],[\"stats\",\"num_storages_home\",42],[\"stats\",\"num_storages_other\",16],[\"stats\",\"num_comments\",29],[\"stats\",\"num_comment_markers\",5],[\"stats\",\"num_systemtags\",0],[\"stats\",\"num_systemtags_mappings\",0],[\"files_sharing\",\"num_shares\",75],[\"files_sharing\",\"num_shares_user\",11],[\"files_sharing\",\"num_shares_groups\",0],[\"files_sharing\",\"num_shares_link\",40],[\"files_sharing\",\"num_shares_link_no_password\",40],[\"files_sharing\",\"num_fed_shares_sent\",0],[\"files_sharing\",\"num_fed_shares_received\",0],[\"files_sharing\",\"permissions_0_1\",\"3\"],[\"files_sharing\",\"permissions_3_1\",\"13\"],[\"files_sharing\",\"permissions_4_1\",\"12\"],[\"files_sharing\",\"permissions_3_3\",\"4\"],[\"files_sharing\",\"permissions_4_3\",\"1\"],[\"files_sharing\",\"permissions_3_4\",\"1\"],[\"files_sharing\",\"permissions_0_7\",\"1\"],[\"files_sharing\",\"permissions_4_14\",\"3\"],[\"files_sharing\",\"permissions_0_15\",\"1\"],[\"files_sharing\",\"permissions_3_15\",\"22\"],[\"files_sharing\",\"permissions_4_15\",\"8\"],[\"files_sharing\",\"permissions_0_31\",\"6\"],[\"encryption\",\"enabled\",\"no\"],[\"encryption\",\"default_module\",\"no\"]]}",
            "last_sent": "1572246038",
            "server": "yes",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.8.0",
            "types": "logging"
        },
        "tasks": {
            "enabled": "yes",
            "installed_version": "0.12.1",
            "types": ""
        },
        "templateeditor": {
            "enabled": "no",
            "installed_version": "0.2",
            "types": ""
        },
        "text": {
            "enabled": "[\"admin\",\"wagner\",\"freunde\",\"Customer\",\"Meierhold\"]",
            "installed_version": "2.0.0",
            "types": "dav"
        },
        "theming": {
            "backgroundMime": "image\/png",
            "cachebuster": "13",
            "color": "#4DC977",
            "enabled": "yes",
            "installed_version": "1.9.0",
            "logoMime": "image\/svg+xml",
            "name": "Spider IT Munich",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "types": "logging",
            "url": "***REMOVED SENSITIVE VALUE***"
        },
        "twofactor_backupcodes": {
            "enabled": "yes",
            "installed_version": "1.7.0",
            "types": ""
        },
        "twofactor_gateway": {
            "enabled": "[\"admin\"]",
            "installed_version": "0.16.0",
            "types": ""
        },
        "twofactor_totp": {
            "enabled": "no",
            "installed_version": "0.4.1",
            "ocsid": "174726",
            "types": ""
        },
        "updatenotification": {
            "audioplayer": "2.6.0",
            "bookmarks": "2.3.1",
            "bruteforcesettings": "1.1.0",
            "calendar": "1.6.1",
            "contacts": "3.0.3",
            "core": "15.0.4.0",
            "deck": "0.2.1",
            "direct_menu": "0.10.2",
            "enabled": "[\"admin\"]",
            "files_pdfviewer": "1.2.1",
            "installed_version": "1.8.0",
            "mail": "0.7.9",
            "notes": "2.4.2",
            "rainloop": "5.0.2",
            "richdocuments": "1.12.36",
            "spreed": "3.2.2",
            "tasks": "0.9.8",
            "theming": "1.4.5",
            "twofactor_gateway": "0.12.0",
            "types": "",
            "update_check_errors": "1"
        },
        "viewer": {
            "enabled": "yes",
            "installed_version": "1.2.0",
            "types": ""
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "2.0.0",
            "types": "filesystem"
        }
    }
}

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 75.0

**Operating system:** Ubuntu 20.04 LTS

**Comment by kesselb** [comment]
Do you see the issue as well with `breezedark` disabled.

**Comment by wagnerfl85** [comment]
You are absolutely right, the problem is related to the breezedark theme/app. If  i disable breezedark then the problem is gone.

**Comment by kesselb** [comment]
https://github.com/mwalbeck/nextcloud-breeze-dark is the right place for this report then.
