### ISSUE TITLE
Open_basedir restriction in effect. File(/) is not within the allowed path(s)

### ISSUE THREAD

**Issue by havn** [nextcloud/server#20792]
**Open_basedir restriction in effect. File(/) is not within the allowed path(s)**

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud via the Softaculous auto-installer, use the default datadir: "nextclouddata".
2. after installation, try to log in at admin login page  index.php
3. get error message "Open_basedir restriction in effect. File(/) is not within the allowed path(s)" 
4. Note: it installed without errors yet the nextcloud datadir is placed by default at an illegal location:
".../home/_useraccountname_/nextclouddata/"

### Expected behaviour
The Softaculous installer should create the nextcloud datadirectory at a different location, namedly:
".../home/_useraccountname_/domains/include/nextclouddata/"

### Actual behaviour
I think that. because the directory "include" did not exist yet, the installer couldn't or wouldn't use that, and reverted to the actual root as a location. Which is illegal.

### Server configuration

**Operating system:**
I dont know, it's not my server, I just rent some space there. It looks like Linux but i'm not sure.

**Web server:**
Apache

**Database:**
Type:	mysql
Versie:	10.3.11

**PHP version:**
Versie:	7.3.5

**Nextcloud version:**
Nextcloud 18.0.4
--

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install via Softaculous Auto Installer

**Where did you install Nextcloud from:**
"From"?   ->  See previous answer, I guess.

**Signing status:**
<details>
<summary>Signing status</summary>

```
There is nothing there, just:
_"Example Domain
This domain is for use in illustrative examples in documents. You may use this domain in literature without prior coordination or asking for permission.
More information..."_
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
no apps installed yet
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => 'ocu6opvyzpdo',
  'passwordsalt' => '_sensitive_data_removed_',
  'secret' => '_sensitive_data_removed_',
  'trusted_domains' => 
  array (
    0 => 'cloud.braintrainen.nl',
  ),
  'datadirectory' => '/home/_useraccountname_/domains/include/nextclouddata',
  'dbtype' => 'mysql',
  'version' => '18.0.4.2',
  'overwrite.cli.url' => 'http://cloud.braintrainen.nl/nc',
  'dbname' => _sensitive_data_removed_',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '_sensitive_data_removed_',
  'dbpassword' => '_sensitive_data_removed_',
  'installed' => true,
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Chrome 

**Operating system:**
Windows 10 
Version 1803
Build 17134.285

#### Web server error log
<details>
<summary>Web server error log</summary>
```
it is not my webserver and I dont know how to get the logs. 
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>The Log in the nextcloud data folder was basically started when I logged in first, there are no records or entries from install time (the log was empty then)</summary>

```
{"reqId":"Xq5PJPQkPP-7CfAhH0@rXgAAAVo","level":3,"time":"2020-05-03T04:57:09+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/index.php/settings/admin/serverinfo","message":"Undefined variable: result at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5PJPQkPP-7CfAhH0@rXgAAAVo","level":3,"time":"2020-05-03T04:57:09+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/index.php/settings/admin/serverinfo","message":"Invalid argument supplied for foreach() at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/templates/settings-admin.php#101","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5PJ-QkPP-7CfAhH0@rZQAAAU0","level":3,"time":"2020-05-03T04:57:12+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/ocs/v2.php/apps/serverinfo/api/v1//diskdata?format=json","message":"Undefined variable: result at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5PJ-QkPP-7CfAhH0@rZQAAAU0","level":3,"time":"2020-05-03T04:57:12+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/ocs/v2.php/apps/serverinfo/api/v1//diskdata?format=json","message":"Invalid argument supplied for foreach() at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/lib/Os.php#155","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5QcH-rKKI4vyl01AELqgAAAJc","level":3,"time":"2020-05-03T05:02:40+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/index.php/settings/admin/serverinfo","message":"Undefined variable: result at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5QcH-rKKI4vyl01AELqgAAAJc","level":3,"time":"2020-05-03T05:02:41+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/index.php/settings/admin/serverinfo","message":"Invalid argument supplied for foreach() at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/templates/settings-admin.php#101","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5QcvQkPP-7CfAhH0@tIwAAAWU","level":3,"time":"2020-05-03T05:02:42+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/ocs/v2.php/apps/serverinfo/api/v1//diskdata?format=json","message":"Undefined variable: result at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#173","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5QcvQkPP-7CfAhH0@tIwAAAWU","level":3,"time":"2020-05-03T05:02:42+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"PHP","method":"GET","url":"/nc/ocs/v2.php/apps/serverinfo/api/v1//diskdata?format=json","message":"Invalid argument supplied for foreach() at /home/anjabfh330/domains/braintrainen.nl/public_html/cloud/nc/apps/serverinfo/lib/Os.php#155","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}
{"reqId":"Xq5Rj-QkPP-7CfAhH0@uIAAAAUc","level":2,"time":"2020-05-03T05:07:28+00:00","remoteAddr":"212.178.112.106","user":"admin","app":"core","method":"POST","url":"/nc/index.php/login/confirm","message":"Login failed: 'admin' (Remote IP: '212.178.112.106')","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36","version":"18.0.4.2"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
I have no idea what to put here,  Like Chrome logs?
Please tell me what to put here and where I can find it.
```
</details>
![Much install config errors to be solved](https://user-images.githubusercontent.com/7382455/80899430-47b10c80-8d10-11ea-9c64-cae4e9a09518.JPG)

**Comment by kesselb** [comment]
> Install Nextcloud via the Softaculous auto-installer,

> The Softaculous installer should create the nextcloud datadirectory at a different location

Mind to report your issue to softaculous? We don't maintain that installer.

**Comment by havn** [comment]
Good point, will do, cheers.

Have a nice day!


Hans van Noord

___________________
hansvannoord@hotmail.com<mailto:hansvannoord@hotmail.com>
Emmastraat 15-K111
9722 EW - Groningen
Tel: 06–53172852
______________________________


________________________________
Van: kesselb <notifications@github.com>
Verzonden: Sunday, May 3, 2020 10:16:08 AM
Aan: nextcloud/server <server@noreply.github.com>
CC: havn <hansvannoord@hotmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [nextcloud/server] Open_basedir restriction in effect. File(/) is not within the allowed path(s) (#20792)


Install Nextcloud via the Softaculous auto-installer,

The Softaculous installer should create the nextcloud datadirectory at a different location

Mind to report your issue to softaculous? We don't maintain that installer.
