### ISSUE TITLE
Breadcrumbs padding error on home folder

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#2079]
After 742ece8b7a054ce16152d721f91936d04b5d22c2
@MorrisJobke 

![capture d ecran_2016-11-10_16-51-46](https://cloud.githubusercontent.com/assets/14975046/20184172/0d55a15e-a768-11e6-9a33-eef6e7490111.png)
![capture d ecran_2016-11-10_17-05-44](https://cloud.githubusercontent.com/assets/14975046/20184178/118f4978-a768-11e6-89e6-2d2ea3ad22cf.png)

**Comment by MorrisJobke** [comment]
Fix is in #2088
