### ISSUE TITLE
Public upload with "Hide file listing" not possible if 'enable_avatars' =>false 

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#2080]
### Steps to reproduce
1. set enable_avatars to false in config.php
2. create a share with "Hide file listing" enabled
3. Try to upload a file by select or drag and drop

### Expected behaviour
Upload dialog is not opened

JS error on page load:
TypeError: $(...).avatar is not a function 
Error points to this line:
https://github.com/nextcloud/server/blob/v10.0.1/apps/files_sharing/js/files_drop.js#L101

### Actual behaviour
upload dialog should be opened

### Server configuration
**Nextcloud version:** 10.0.1

If i set 'enable_avatars' =>true everything works fine.
I think something like that should help:
https://github.com/owncloud/core/pull/11428/files

**Comment by MorrisJobke** [comment]
@rullzer Didn't we removed the avatar flag in master?

**Comment by rullzer** [comment]
Ha nope. But I can take care of this
