### ISSUE TITLE
Webcal cache: fails with bad DTEND date

### ISSUE THREAD

**Issue by arminus** [nextcloud/server#20804]
### Steps to reproduce
1. My google .ics feed has some birthday reminders with illegal end dates (no idea how that happened in the first place, probably a google bug or caused by whatever software originally produced those entries)
2. that value looks like `DTEND;VALUE=DATE:18991230`
3. CalDAV import will partially fail with `SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'lastoccurence' at row 1 at <<closure>>`

### Expected behaviour
- handle bogus dates in a controlled way
- proposed change in CalDavBackend:getDenormalizedData (end of `if ($componentType === 'VEVENT' && $component->DTSTART) {` block):
```
if ($lastOccurrence < 0) {
    $maxDate = new DateTime(self::MAX_DATE);
    $lastOccurrence = $maxDate->getTimestamp();
}
```

### Actual behaviour
- the import failure might get unnoticed if the log is not checked since the import errors message in the main UI hides itself after some seconds and the other entries appear to be inserted correctly
- as a consequence, subsequent auto refreshes of that calendar appear to be not working at all, i.e. not even the partially imported events get synch-ed or new events from the .ics feed get pulled in

**Comment by kesselb** [comment]
cc @nextcloud/calendar

**Comment by georgehrke** [comment]
@arminus How did you import that calendar? 

The CalDAV server should reject anything that's not within 1970-01-01 and 2038-01-19.

**Comment by arminus** [comment]
[![New-Subscription.png](https://i.postimg.cc/rFmRtqqQ/New-Subscription.png)](https://postimg.cc/dDbVbPky)

the full log is [here](https://pastebin.com/eUduc4j8)

**Comment by dirigit** [comment]
@georgehrke When first date being allowed is in 1970 ... How to you enter a birthday in year 1926?

IMHO this limit makes no sense,

cu, diri

**Comment by georgehrke** [comment]
> IMHO this limit makes no sense,

We didn’t just set this limit for fun ;) 
Many clients (including some Android phones) don't support dates before the start of unixtime.

Furthermore, we also use unixtime internally (e.g. in the database for faster querying.

Our internal birthday calendar mitigates that problem, so use that one instead, if you want a birthday calendar.

**Comment by arminus** [comment]
I don't really care about a birthday calendar. Fact is, my google ics feed has those dates for some reason and it won't import due to that issue - which is really blocking in my case.

What's the risk of applying the patch/workaround I suggested? This doesn't set the date to something illegal which would cause issues downstream after all I would think?

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by arminus** [comment]
Unless someone has fixed this, the issue is still valid - I need to merge my change in for every update I do, otherwise my google ics feed doesn't load.

**Comment by szaimen** [comment]
cc @nextcloud/calendar is this something we should/can fix?

**Comment by flesser** [comment]
Similar error when trying to create events with dates after 2038 (in my case: via DAVx⁵ from Android Smartphone):
```xml
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OC\DB\Exceptions\DbalException</s:exception>
  <s:message>An exception occurred while executing a query: SQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'lastoccurence' at row 1</s:message>
</d:error>
```

Looks like a typical https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by Goldmaster** [comment]
I have encounted this and may be related to my issue. I guess wait till it get fixed at some point.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by tcitworld** [comment]
> I'm happy to submit a PR.

PR has been here for a while, I just never took the time to test if there's no side-effects introduced by this. I guess we can now merge it.
https://github.com/nextcloud/server/pull/31790
