### ISSUE TITLE
"Job title" / "Department" profile field which is visible to colleagues via avatar menu

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#20806]
**Is your feature request related to a problem? Please describe.**
In larger organizations, you often don’t know everyone or maybe forget which department someone is in. Our already existing profile info fields have some basic info, but not for example department / job title.

On our own instance we also have a lot of guest users, and there it would be nice which company they are from.

**Describe the solution you'd like**
We can add some profile fields for people to add more details. These could be shown in the avatar menu, as well as in the subline of the Contacts menu in the header.
Relevant additions:
- Job title: To know what this colleague’s expertise is.
- Department: Especially for bigger companies where a job title might not be informative enough, or be too freeform, this could even just be a dropdown. Or possibly this is not needed as this is supplied by the "Groups" feature anyway?
- Company: Could be especially useful for guest users, to know which company they are from.

"Title" and "Company" are also the job-relevant ones which are used in Contacts, so we have consistency there.

**Describe alternatives you've considered**
This is very related to the **Name and status in top right dropdown menu #6069**, but more permanent and in a specific format.

**Additional context**

The current profile fields:
- Full name
- Email
- Phone number
- Address
- Website
- Twitter
![Profile fields](https://user-images.githubusercontent.com/925062/80953589-1f9ed780-8dfc-11ea-907c-6890052d6098.png)

What do you think @karlitschek @jospoortvliet @rullzer?

**Comment by karlitschek** [comment]
I totally agree. If we brainstorm a bit more then we can probably come up with more useful fields. @oparoz @jospoortvliet @wiswedel for more ideas. @blizzz We have to check to not duplicate information that might come from a directory.

**Comment by blizzz** [comment]
> I totally agree. If we brainstorm a bit more then we can probably come up with more useful fields. @oparoz @jospoortvliet @wiswedel for more ideas. @blizzz We have to check to not duplicate information that might come from a directory.

All those mentioned details are common to be in LDAP. We already had a request to sync the information on the personal page from LDAP. Of those it is just avatar, email and name that are being taken, as it is what is handled by user management. If we want to expand it, there might be more interest to have these data be synced down, too.

The common, extended user info in LDAP (inetOrgPerson class) contains:

> audio $ businessCategory $ carLicense $ departmentNumber $
        displayName $ employeeNumber $ employeeType $ givenName $
        homePhone $ homePostalAddress $ initials $ jpegPhoto $
        labeledURI $ mail $ manager $ mobile $ o $ pager $
        photo $ roomNumber $ secretary $ uid $ userCertificate $
        x500uniqueIdentifier $ preferredLanguage $
        userSMIMECertificate $ userPKCS12

(https://tools.ietf.org/html/rfc2798)




What is missing there is and could also be useful is a nickname.

**Comment by jancborchardt** [comment]
Let’s first go with the things we actually deem useful though, not try to come up with stuff to flood the page with. ;) Step by step

**Comment by wiswedel** [comment]
Why don't we let people pick their own details just like we do in Contacts?

![image](https://user-images.githubusercontent.com/1804221/81270239-b82a9700-904a-11ea-98e9-6bfbb6ef6a61.png)

If we decide now which properties _we_ find useful (and which not), we can already start taking bets how many seconds after the merge there will be the first enhancement requests are coming in.

**Comment by go2sh** [comment]
Microsoft within ActiveDirectory uses `organizationalperson`, which has a `department` attribute used for full-text department description and a `title` attribute, which is the same as in `inteOrgPerson`.

**Comment by jancborchardt** [comment]
> If we decide now which properties we find useful (and which not), we can already start taking bets how many seconds after the merge there will be the first enhancement requests are coming in.

We already did decide that, and those are the fields now showing in the profile settings. This is how any popular platform with a profile functionality works, and it helps focus on the important stuff.

**Comment by blizzz** [comment]
I didn't suggest  to include everything, only gave a picture which details MIGHT  be already present in a directory. It CAN be more, depending on the customization of it. This was on the question of how much might be duplicated from there.

What we should decide on is whether to read also additional attributes from LDAP and set the profile values. In this case, we would also needs checks on whether a user can actually modify these fields, because it would not write to LDAP (unless you have the write support app enabled). So it has a rat tail, but for a start we can leave this out from first phase. Eventually, not having an import would look half-baken for organizational users.

**Comment by wiswedel** [comment]
> and it helps focus on the important stuff
Exactly that's what we gain if we don't decide anything top down. Let users pick their own details, have admins define a mapping for LDAP attributes on detail class if necessary and we're free from decisions and discussions forever.

In the end, expose all filled details in the user's profile.

**Comment by Dubidubiduu** [comment]
For my perspective, background: german activist group on animal things, when hovering over one anothers profile I want to know:
Name
Town
State
Function (Job title), should (also?) be entered by admin.
Some NC-Groups - so others know about their interests/access rights

No Email by default #14959!!

**Comment by Spartachetto** [comment]
As I work in a big organization which has contacts with other big organizations, my experience is that I need two or three levels of information for the information about the workplace of my contacts.

This means that 

- for internal contacts I have Department + Office
- for external contacts I have either Company + Department + Office or Company + Division + Department + Office 

Hope that helps.

**Comment by jancborchardt** [comment]
This was done already in the form of "Title" and "Company" with the new Profile thanks to @Pytal :)

**Comment by Spartachetto** [comment]
As I wrote time ago, I usually need **at least**  one more field: Title + office + company or Title + office + department + company.
