### ISSUE TITLE
"internal server error" for only 1 user - nextcloud 18.0.4 else working fine - error.log is empty

### ISSUE THREAD

**Issue by idana1976** [nextcloud/server#20816]
Hi, we have a Nextcloud server which runs only Nextcloud with 22 user and 6 groups
exactly 1 user out of the 22 has the "Internal Server Error" issue no matter which PC or which browser he is using. Also he can't log out anymore to check if he can use another account no matter what you do with the browser.

### Steps to reproduce - nothing special
1. open our nextcloud url in any browser (most of us use chrome) and any device (i checked it on my PC as well)
2. log in 1 specific user "a***s"
3. type password (which worked perfectly fine up till now and still works fine on the nextcloud desktop app)
--- 4. follow up: once that is done no matter which browser settings when opening our nextcloud url again it only shows the error message

### Expected behaviour
it should just log him in and show the file list like it does with all the 20 other users (1 is not tested) 

### Actual behaviour
no matter which browser or device is used the Server displays the error message (sorry for german, most of the users are german)
Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen.
Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator.
Weitere Details können im Server-Protokoll gefunden werden.
Technische Details
Entfernte Adresse: <my IP>
Anfragekennung: PfVfUJZStGjENudnFepn

### Server configuration
**Operating system: Ubuntu 18.04 on a new server (installed February 2020)
**Web server: Apache 2.4
**Database: MariaDB 10.1.44
**PHP version: 7.2.24
**Nextcloud version: 18.0.4 (updated today in an attempt to fix the issue)
**Updated from an older Nextcloud/ownCloud or fresh install: 18.0.2 i think up till today
**Where did you install Nextcloud from: was preinstalled by the server provider

**Signing status: of https://cloud.***.de/index.php/settings/integrity/failed 
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>
Every other error or logfile is empty as well.

i will provide more infos if you need but what really strikes me is that only 1 user has that issue, so i think some of his settings glitched?

**Comment by acsfer** [comment]
You should try https://help.nextcloud.com for this kind of questions.

**Comment by idana1976** [comment]
Hi thank you, i did, i went through all the troubleshoot threats, most of them from before 2018. problem is, technically there is no error anywhere in the logs except that only 1 user defenetly cant log on his account anymore. also i found at least 3 answers: mysql trouble (but there is nothing in the error.log) or damaged css (but then why does only 1 person have the problem) i found alot of answers, but non of them really fixed the problem.

**Comment by idana1976** [comment]
seems like the error is such a generic/unspecific error message. the user changed their language from english to german and then from german back to english and for some reason that glitched him out. we managed to correct that in the database 
still, i would consider that a bug... jsut some that will be really hard to point out... i think

**Comment by idana1976** [comment]
Hi, so this is defenetly a bug, altho it might be a small one.
1. Nextcloud is freshly installed
2. account worked fine
3. installation is complete
4. no errors in any log

when i made accounts, i changed all to language and local de_DE 

one of my collegues prefers language in english tho but he accidently changed language and locale to to en_US_POSIX 

for some reason nextcloud declared that the local en_US_POSIX is not installed while it was installed!

our other serveradmin changed language and local back to de_DE and it works now 

sorry but that sounds to me like a bug specially when it is fresh installed, nothing changed and everything is kept with standard settings

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
