### ISSUE TITLE
Share by Email Wrong Password

### ISSUE THREAD

**Issue by graybuck** [nextcloud/server#20819]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Enable Share by Email
2. Enable Send password by mail in setting
3. Enable Enforce password protection in setting

### Expected behaviour
Receive emails with link and password. Select link to access file/folder and use password to gain access.

### Actual behaviour
Able to get to the site using link. However, the password is always wrong. When I use Share link option and use the link created, then it works, even with auto generated password.

### Server configuration

**Operating system:**
Ubuntu 18.04 with Docker
**Web server:**
Docker nginx-alpine
**Database:**
Docker Mariadb 10.4
**PHP version:**
7.3.17
**Nextcloud version:** (see Nextcloud admin page)
18.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install
**Where did you install Nextcloud from:**
Docker Hub
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - federation
  - files_external

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' =>
  array (
    0 =>
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 =>
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'instanceid' => 'ppk2kd8urmgf',
  'passwordsalt' => 'mxxBH9EfjVlnmQA09TcJPKu9Ul//jq',
  'secret' => '2HVaJZuImcU1B1HjJMxNm88DHs1oYIhTRKcbPTHggP6YtYao',
  'trusted_domains' =>
  array (
    0 => 'mynextcloud.mydomain.com',
    1 => 'dockernginxhost',
  ),
  'trusted_proxies' =>
  array (
    0 => '10.10.10.0/24',
    1 => '10.10.20.0/24',
  ),
  'datadirectory' => '/var/www/html/data',
  'dbtype' => 'mysql',
  'version' => '18.0.4.2',
  'overwrite.cli.url' => 'http://mynextcloud.mydomain.com',
  'overwriteprotocol' => "https",
  'skeletondirectory' => '/var/www/html/data/empty_skeleton',
  'dbname' => 'mydb',
  'dbhost' => 'mydbhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'mydbuser',
  'dbpassword' => 'mypassword',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'lost_password_link' => 'https://password.mydomain.com',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'admin',
  'mail_domain' => 'mydomain.com',
  'mail_smtphost' => 'smtpserver',
  'mail_smtpport' => 'myport',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'admin@mydomain.com',
  'mail_smtppassword' => 'mypassword',
  'mail_smtpauthtype' => 'LOGIN',
  'maintenance' => false,
  'loglevel' => 2,
);

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder
+-------------------------------+----------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                      |
+-------------------------------+----------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                        |
| homeFolderNamingRule          |                                                                                                          |
| lastJpegPhotoLookup           | 0                                                                                                        |
| ldapAgentName                 | cn=admin,dc=mydomain,dc=com                                                                                |
| ldapAgentPassword             | ***                                                                                                      |
| ldapAttributesForGroupSearch  |                                                                                                  |
| ldapAttributesForUserSearch   |                                                                                                   |
| ldapBackupHost                |                                                                                                          |
| ldapBackupPort                |                                                                                                          |
| ldapBase                      | o=section,dc=mydomain,dc=com                                                        |
| ldapBaseGroups                | o=section,dc=mydomain,dc=com                                                  |
| ldapBaseUsers                 | o=section,dc=mydomain,dc=com                                                |
| ldapCacheTTL                  | 600                                                                                                      |
| ldapConfigurationActive       | 1                                                                                                        |
| ldapDefaultPPolicyDN          |                                                                                                          |
| ldapDynamicGroupMemberURL     |                                                                                                          |
| ldapEmailAttribute            | mail                                                                                                     |
| ldapExperiencedAdmin          | 0                                                                                                        |
| ldapExpertUUIDGroupAttr       |                                                                                                          |
| ldapExpertUUIDUserAttr        | uid                                                                                                      |
| ldapExpertUsernameAttr        | uid                                                                                                      |
| ldapExtStorageHomeAttribute   |                                                                                                          |
| ldapGidNumber                 | gidNumber                                                                                                |
| ldapGroupDisplayName          | cn                                                                                                       |
| ldapGroupFilter               | (|(cn=alluser))                                                                                         |
| ldapGroupFilterGroups         | alluser                                                                                                 |
| ldapGroupFilterMode           | 0                                                                                                        |
| ldapGroupFilterObjectclass    |                                                                                                          |
| ldapGroupMemberAssocAttr      | member                                                                                                   |
| ldapHost                      | 10.10.10.180                                                                                             |
| ldapIgnoreNamingRules         |                                                                                                          |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=alluser,ou=groups,o=section,dc=mydomain,dc=com)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                          |
| ldapLoginFilterEmail          | 0                                                                                                        |
| ldapLoginFilterMode           | 0                                                                                                        |
| ldapLoginFilterUsername       | 1                                                                                                        |
| ldapNestedGroups              | 0                                                                                                        |
| ldapOverrideMainServer        |                                                                                                          |
| ldapPagingSize                | 500                                                                                                      |
| ldapPort                      | 389                                                                                                      |
| ldapQuotaAttribute            |                                                                                                          |
| ldapQuotaDefault              |                                                                                                          |
| ldapTLS                       | 0                                                                                                        |
| ldapUserAvatarRule            | default                                                                                                  |
| ldapUserDisplayName           | displayname                                                                                              |
| ldapUserDisplayName2          |                                                                                                          |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson))(|(memberof=cn=alluser,ou=groups,o=section,dc=mydomain,dc=com)))              |
| ldapUserFilterGroups          | alluser                                                                                         |
| ldapUserFilterMode            | 0                                                                                                        |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                            |
| ldapUuidGroupAttribute        | auto                                                                                                     |
| ldapUuidUserAttribute         | auto                                                                                                     |
| turnOffCertCheck              | 0                                                                                                        |
| turnOnPasswordChange          | 0                                                                                                        |
| useMemberOfToDetectMembership | 1                                                                                                        |
+-------------------------------+----------------------------------------------------------------------------------------------------------+

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
**172.20.0.2 - - [04/May/2020:09:40:06 -0700] "GET /index.php/s/T78Ejwgek3oFJw3 HTTP/1.1" 303 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "10.10.10.100"
172.20.0.2 - - [04/May/2020:09:40:06 -0700] "GET /index.php/s/T78Ejwgek3oFJw3/authenticate/showShare HTTP/1.1" 200 12464 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "10.10.10.100"
172.20.0.2 - - [04/May/2020:09:40:32 -0700] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.132 Safari/537.36" "10.10.10.100"
172.20.0.2 - - [04/May/2020:09:40:34 -0700] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 OPR/68.0.3618.63" "10.10.10.100"
172.20.0.2 - - [04/May/2020:09:40:56 -0700] "POST /index.php/s/T78Ejwgek3oFJw3/authenticate/showShare HTTP/1.1" 200 12460 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "10.10.10.100"
172.20.0.2 - - [04/May/2020:09:40:56 -0700] "GET /index.php/apps/accessibility/js/accessibility?v=0 HTTP/1.1" 200 85 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "10.10.10.100"
172.20.0.2 - - [04/May/2020:09:40:56 -0700] "GET /index.php/apps/theming/image/logo?useSvg=1&v=7 HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "10.10.10.100"

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No log registered
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No log registered related to this issue
```
</details>

**Comment by kurn77** [comment]
Using Nextcloud for a small size community, my users are fan of "**share by mail**" functionnality with auto-generated password which avoid them to think and apply different password on each share.

However, a lot of them were doing me feedback that the **password is not working** : first I though the end user is not confortable with computers, but they sent me 1 exemple of "share link email" / "share password email" and I must confess they were right. Removing share and creating a new one often solve issue and this issue happen sometimes, but I cannot understand why sometimes it is working and sometimes not ? 

Personnally, trying to reproduce alone, I was not able to do it. But considering a large amount of share made by my users, I must accept this situation really occurs.

This situation happened with the simple (auto-generated) password : **#wwE#wj]**

Sharing admin configuration is : 

![image1](https://user-images.githubusercontent.com/74493472/100799473-6356cf80-3425-11eb-87a3-9ac489d880d9.png)

### Server configuration

**Operating system:** Debian 10.12-2
**Web server:** Apache 2.4
**Database:** PostgreSQL 10.12
**PHP version:** PHP 7.3.19
**Nextcloud version:** NextCloud v 17.0.10
**Updated from an older Nextcloud/ownCloud or fresh install:** No

No errors have been found when login as admin user into your Nextcloud and access to http://example.com/index.php/settings/integrity/failed

List of activated apps:
Accessibility 1.6.0 / Activity 2.13.2 / Calendar 2.1.2 / Comments 1.10.0 / Contacts 3.4.1 / Contacts Interaction 1.1.0 / Custom CSS 1.7.0 / Data Request 1.7.0 / Deleted files 1.10.1 / DICOM Viewer 1.2.2 / External sites 3.7.1 / File sharing 1.12.0 / Group folders 8.1.0 / Log Reader 2.5.0 / Notifications 2.8.0 / Password policy 1.10.1 / PDF viewer 2.0.1 / Photos 1.2.0 / Recommendations 0.8.0 / Right click 0.17.0 / Share by mail 1.10.0 / Support 1.3.0 / Text 3.1.0 / Theming 1.11.0 / Update notification 1.10.0 / Usage survey 1.8.0 / User status 1.0.0 / Versions 1.13.0 / Video player 1.9.0

**Are you using external storage, if yes which one: no
**Are you using encryption: no
**Are you using an external user-backend, if yes which one: no

### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

**Operating system:**
Windows 10 Version 10.0.19041 Numéro 19041

Somebody else experienced that situation ?

**Comment by kurn77** [comment]
Add-on : removing all constraints on password format, I manually setted the same password on a share by email and it worked. 

Thus, it seems the password caracters are not responsible of the issue > maybe hashing process before to be stored in database ?

**Comment by kurn77** [comment]
Add-on : I wondered in previous test why I had to remove the password policy... looking a bit more I realised that
- My password policy is at least 12 caracters, 1 upper caracter, 1 lower caracter, 1 numeric character and 1 special caracter
- I freshly generated 2 successful share by mail password (auto-generated password) : **2Dru[tw+,CK/** and **9/>*|xX?mogk**
- Both are perfectly consistent with password policy
- On the other hand, the previously not working auto-generated password was not compliant with that password policy :  **#wwE#wj]** which has only 8 caracters and no numeric caracters

![image2](https://user-images.githubusercontent.com/74493472/100807876-5e008180-3433-11eb-964c-ff0070ea2358.png)
Thus, I think issue is either when generating a password not compliant with password policy, or when embedding it the password in the password mail it is truncated and then not correct when copy/pasted by end user.

Somebody with more experience may have a look on that point ?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by kurn77** [comment]
Hello @szaimen : I didn't test NC21 but I will soon. I keep you informed about the result. However I feel that problem doesn't occur anymore with NC20.0.9 already, it should not be the case also with NC21.
