### ISSUE TITLE
Remember the last choosen login method welcome screeen

### ISSUE THREAD

**Issue by g6094199** [nextcloud/server#20817]
He Guys,

today i managed to change from pw to webauthn login but one thing could be more comfortable to use.

When you setup webauthn an logout. Then the welcome screen asks for the pw auth. Ok. So clicking to use the "mit Geraet anmelden" button brings you to the webauthn dialog. Aufter you have been logged in with webauthn and re-logged out the welcome screen promts again for the "old" pw auth!
tested on FF 75 and Chromium 81 on Ubuntu 20.04

It would be very nice to have the browser remember the last known auth method and welcomes you with the screen you used the last time.

regards
Sash

**Comment by tigernero79** [comment]
I installed webauthn myself too, but from what I understand, you always need a password to log in and then stick.  it is a webauthn u2f.  I do not trust without a password.  I don't understand which button you have to avoid putting a password and inserting the key.  i don't understand if webauthn nextcloud only supports fido u2f or also fido2 passwordless

**Comment by g6094199** [comment]
No, FIDO2 supports passwordless auth, which is implemented in NC when you have a closer look at the security page.

**Comment by tigernero79** [comment]
> No, FIDO2 supporta l'autent senza password, che viene implementata in NC quando si osserva più da vicino la pagina di sicurezza.

what do you mean that app already allows fido2 authentication without password? I did not understand what you mean up close, sorry for the delay but I'm Italian. if it supports passwordless how to do it because I only get webauthn u2f

**Comment by tigernero79** [comment]
I am writing to you because nextcloud always asks me first username and password and I don't see any wording to access with passwordless

**Comment by g6094199** [comment]
1st you have to install NC19! but this is no support forum. plz [use](https://help.nextcloud.com/c/international/18) for usage/install problems.

**Comment by tigernero79** [comment]
ok thanks

**Comment by kowalski7cc** [comment]
This could be solvable with a Username first flow. (i.e. login flows where a user has to type username first on one page and then password on another page), so the "second part" would have WebAuthn if configured else ask for a password.

**Comment by szaimen** [comment]
> This could be solvable with a Username first flow. (i.e. login flows where a user has to type username first on one page and then password on another page), so the "second part" would have WebAuthn if configured else ask for a password.

This is already possible. Just use this app https://apps.nextcloud.com/apps/twofactor_webauthn instead of the built-in webauthn.

**Comment by kowalski7cc** [comment]
> This is already possible. Just use this app https://apps.nextcloud.com/apps/twofactor_webauthn instead of the built-in webauthn.

@szaimen This would be more a UI/UX improvement than a technical one.
