### ISSUE TITLE
Custom session variable disappear after several days but user still logged in

### ISSUE THREAD

**Issue by Mariick** [nextcloud/server#2081]
### Steps to reproduce
1. Set some session data like this :
`$this->session->set('tokendata',$token);`

### Expected behaviour
The session variable can always be accessible while the session is alive while the user logged out.

### Actual behaviour
The session variable can be accessible everytime, but after let open the session several days or/and when the host computer hibernate and resume the variable is deleted, but the user is still logged in in nextcloud (the session is alive but the variable is out...)

### Server configuration
**Operating system**:
Debian 8.6

**Web server:**
Apache 2.4

**Database:**
Mysql 5.5.52

**PHP version:**
PHP 5.6.24

**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (fresh install)

**Where did you install Nextcloud from:**
from official website

**Comment by nickvergessen** [comment]
@LukasReschke

**Comment by MorrisJobke** [comment]
I guess we renew the session by the cookie and therefore delete the existing session and create a new one (to avoid that the same session could still be hijacked).

If you want to store some info in your app: put it in the memcache or the database instead. We do not support to transfer data that is stored in the session.
