### ISSUE TITLE
Possibility to change username/uid

### ISSUE THREAD

**Issue by phonon112358** [nextcloud/server#20829]
Hi,

I use NC 18 for a small company.
I just have realised that I have spaces in the user/login names and would like to replace them by underscores...
I have read https://github.com/nextcloud/server/issues/5488. 
Why is that not possible?? Where does NC save the usernames beside in the `oc_users` table in the database?

**Comment by kesselb** [comment]
Closing as duplicate of #5488. I hope you don't mind. The username is still used as internal identifier (I agree a questionable decision) everywhere as reference to a user.
