### ISSUE TITLE
Picture query doesn't provide an answer within an acceptable time

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#20839]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

## Expected behavior
If the “Photos” menu entry is chosen in the Nextcloud Android app, it initiates a server query which should show the first 60 photos within an acceptable time and load another 60 photos if requested, etc.

## Current behavior
If the “Photos” menu entry is chosen in the Nextcloud Android app, the initiated server query doesn't return any photos within an acceptable time. Instead "No Photos" is displayed. One user reported that he'd waited up-to 30min within a result being returned.

@tobiasKaminsky assumes that a server problem might cause this behavior. 
The problem has previously been discussed in the [Nextcloud help forum](https://help.nextcloud.com/t/no-pictures-are-shown-under-photos-menu-entry/80375)

During my tests I've seen that the following message being logged on the server:
```
...","app":"PHP","method":"SEARCH","url":"/remote.php/dav","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) at .../nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#158","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.12.0 RC1","version":"18.0.4.2"}
```
Although the server is working like a charm and the mentioned message hasn’t been displayed in the past, I increased the available PHP memory limit from 512MB to 1GB. Surprisingly a similar message is still being logged:
```
...,"app":"PHP","method":"SEARCH","url":"/remote.php/dav","message":"Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) at .../nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php#158","userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.12.0 RC1","version":"18.0.4.2"}
```

Now I wonder why only the Nextcloud app requests such a huge amount of memory, only to search photos and why no result is being returned. Non of the other server related functions are running into that problem, nor the Nextcloud web gui does?!

## Steps to reproduce
1. Open the Nextcloud Android app
2. Select the Photos menu entry
3. Wait for photos being displayed.
   -> No photos are shown at all.

#### Server Configuration
OS: Linux 4.9.218
Web server: Apache2 2.4.41
Database: MariaDB 10.2.24
PHP version: 7.3.13
Nextcloud version: 18.0.4

#### Client Configuration
Nextcloud Android app version: **3.12.0 RC1**
Phone: Samsung Galaxy S7

**Comment by kesselb** [comment]
@tobiasKaminsky mind to share the dav request the app sends?

**Comment by tobiasKaminsky** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns">
    <d:basicsearch>
        <d:select>
            <d:prop>
                <d:displayname />
                <d:getcontenttype />
                <d:resourcetype />
                <d:getcontentlength />
                <d:getlastmodified />
                <d:creationdate />
                <d:getetag />
                <d:quota-used-bytes />
                <d:quota-available-bytes />
                <oc:permissions xmlns:oc="http://owncloud.org/ns" />
                <oc:id xmlns:oc="http://owncloud.org/ns" />
                <oc:size xmlns:oc="http://owncloud.org/ns" />
                <oc:favorite xmlns:oc="http://owncloud.org/ns" />
            </d:prop>
        </d:select>
        <d:from>
            <d:scope>
                <d:href>/files/test</d:href>
                <d:depth>infinity</d:depth>
            </d:scope>
        </d:from>
        <d:where>
            <d:like>
                <d:prop>
                    <d:getcontenttype />
                </d:prop>
                <d:literal>image/%</d:literal>
            </d:like>
        </d:where>
        <d:orderby>
            <d:order>
                <d:prop>
                    <d:getlastmodified />
                </d:prop>
                <d:descending />
            </d:order>
        </d:orderby>
    </d:basicsearch>
</d:searchrequest>
```

With limit:
```
<?xml version="1.0" encoding="UTF-8"?>
<d:searchrequest xmlns:d="DAV:" xmlns:oc="http://nextcloud.com/ns">
    <d:basicsearch>
        <d:select>
            <d:prop>
                <d:displayname />
                <d:getcontenttype />
                <d:resourcetype />
                <d:getcontentlength />
                <d:getlastmodified />
                <d:creationdate />
                <d:getetag />
                <d:quota-used-bytes />
                <d:quota-available-bytes />
                <oc:permissions xmlns:oc="http://owncloud.org/ns" />
                <oc:id xmlns:oc="http://owncloud.org/ns" />
                <oc:size xmlns:oc="http://owncloud.org/ns" />
                <oc:favorite xmlns:oc="http://owncloud.org/ns" />
            </d:prop>
        </d:select>
        <d:from>
            <d:scope>
                <d:href>/files/test</d:href>
                <d:depth>infinity</d:depth>
            </d:scope>
        </d:from>
        <d:where>
            <d:like>
                <d:prop>
                    <d:getcontenttype />
                </d:prop>
                <d:literal>image/%</d:literal>
            </d:like>
        </d:where>
        <d:orderby>
            <d:order>
                <d:prop>
                    <d:getlastmodified />
                </d:prop>
                <d:descending />
            </d:order>
        </d:orderby>
    </d:basicsearch>
</d:searchrequest>
```

Both are for user "test", therefore scope is files/test

My finding is that this is some related to amount of total files and about numbers of found files.
so if you have 100 files and it finds 10 or you have 10k files and it finds 10 files makes a huge difference.

**Comment by kesselb** [comment]
Hmm. I can reproduce it somehow on my production instance. 

I'm watching the access.log and ...

1. Open Nextcloud app and switch to photos and see 34 photos
2. Scroll down and see 51 photos
3. Scroll down again, see the loading animation 

```
[07/May/2020:21:35:47 +0200] "SEARCH /remote.php/dav HTTP/1.1" 207 26396 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
[07/May/2020:21:35:53 +0200] "SEARCH /remote.php/dav HTTP/1.1" 207 13651 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
[07/May/2020:21:35:55 +0200] "SEARCH /remote.php/dav HTTP/1.1" 207 787 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.11.1"
```

It seems the server sent a response already but the app still shows the loading animation. But the third response is also much smaller then the first two.

**Comment by svenb1234** [comment]
Any news on this?

What is a sensible expectation on reaction time, i.e. display of the first pictures?

On a Qnap or Synology with their respective app the previews show up instantly. The time for loading the pictures does also not depend on the collection size.

For 60.000 pictures Qnap takes less than a second to start displaying pictures. Nextcloud takes 45 seconds for the first 45, then again a very long time for the next 45 etc. Sometimes it even displays no pictures found, if it takes too long.

**Comment by julientard** [comment]
Same issue here (Android 3.12.1, Server last official docker image, behind Traefik).
I have also this issue (infinite loading) on Activity tab. I don't know if it's related.

**Comment by tacruc** [comment]
Hi Together,
I'm experiencing the same Issue. I Just wanted to give the request send by the photos app, as this request is running without problems. 
```
<?xml version="1.0" encoding="UTF-8"?>
	<d:searchrequest xmlns:d="DAV:"
				xmlns:oc="http://owncloud.org/ns"
				xmlns:nc="http://nextcloud.org/ns"
				xmlns:ns="https://github.com/icewind1991/SearchDAV/ns"
				xmlns:ocs="http://open-collaboration-services.org/ns">
		<d:basicsearch>
			<d:select>
				<d:prop>					
					<oc:fileid />
					<d:getlastmodified />
					<d:getetag />
					<d:getcontenttype />
					<d:getcontentlength />
					<nc:has-preview />
					<oc:favorite />
					<d:resourcetype />
				</d:prop>
			</d:select>
			<d:from>
				<d:scope>
					<d:href>/files/user</d:href>
					<d:depth>infinity</d:depth>
				</d:scope>
			</d:from>
			<d:where>
				<d:and>
					<d:or>
						<d:eq>
							<d:prop>
								<d:getcontenttype/>
							</d:prop>
							<d:literal>image/jpeg</d:literal>
						</d:eq>
						<d:eq>
							<d:prop>
								<d:getcontenttype/>
							</d:prop>
							<d:literal>image/heic</d:literal>
						</d:eq>
						<d:eq>
							<d:prop>
								<d:getcontenttype/>
							</d:prop>
							<d:literal>video/mp4</d:literal>
						</d:eq>
						<d:eq>
							<d:prop>
								<d:getcontenttype/>
							</d:prop>
							<d:literal>video/quicktime</d:literal>
						</d:eq>
					</d:or>
							
					<d:eq>
						<d:prop>
							<oc:owner-id/>
						</d:prop>
						<d:literal>user</d:literal>
					</d:eq>
				</d:and>
			</d:where>
			<d:orderby>
				<d:order>
					<d:prop><d:getlastmodified/></d:prop>
					<d:descending/>
				</d:order>
			</d:orderby>
			<d:limit>
				<d:nresults>35</d:nresults>
				<ns:firstresult>0</ns:firstresult>
			</d:limit>
		</d:basicsearch>
	</d:searchrequest>
```

**Comment by tacruc** [comment]
@tobiasKaminsky I don't see the difference between the limited and unlimted request you posted.

**Comment by tacruc** [comment]
Ok I played arround with the queries a little:
54s:
```
<d:displayname />
                <d:getcontenttype />
                <d:resourcetype />
                <d:getcontentlength />
                <d:getlastmodified />
                <d:creationdate />
                <d:getetag />
                <d:quota-used-bytes />
                <d:quota-available-bytes />
                <oc:permissions xmlns:oc="http://owncloud.org/ns" />
                <oc:id xmlns:oc="http://owncloud.org/ns" />
                <oc:size xmlns:oc="http://owncloud.org/ns" />
                <oc:favorite xmlns:oc="http://owncloud.org/ns" />
						</d:prop>
					</d:select>
					<d:from>
						<d:scope>
							<d:href>/files/test</d:href>
							<d:depth>infinity</d:depth>
						</d:scope>
					</d:from>
					<d:where>
						<d:like>
                <d:prop>
                    <d:getcontenttype />
                </d:prop>
                <d:literal>image/%</d:literal>
            </d:like>
					</d:where>
					<d:orderby>
						<d:order>
							<d:prop><d:getlastmodified/></d:prop>
							<d:descending/>
						</d:order>
					</d:orderby>
					<d:limit>
						<d:nresults>35</d:nresults>
						<ns:firstresult>0</ns:firstresult>
					</d:limit>
				</d:basicsearch>
			</d:searchrequest>
```
457ms:
```
<?xml version="1.0" encoding="UTF-8"?>
			<d:searchrequest xmlns:d="DAV:"
				xmlns:oc="http://owncloud.org/ns"
				xmlns:nc="http://nextcloud.org/ns"
				xmlns:ns="https://github.com/icewind1991/SearchDAV/ns"
				xmlns:ocs="http://open-collaboration-services.org/ns">
				<d:basicsearch>
					<d:select>
						<d:prop>
							
	<d:displayname />
                <d:getcontenttype />
                <d:resourcetype />
                <d:getcontentlength />
                <d:getlastmodified />
                <d:creationdate />
                <d:getetag />
                <d:quota-used-bytes />
                <d:quota-available-bytes />
                <oc:permissions xmlns:oc="http://owncloud.org/ns" />
                <oc:id xmlns:oc="http://owncloud.org/ns" />
                <oc:size xmlns:oc="http://owncloud.org/ns" />
                <oc:favorite xmlns:oc="http://owncloud.org/ns" />
						</d:prop>
					</d:select>
					<d:from>
						<d:scope>
							<d:href>/files/test</d:href>
							<d:depth>infinity</d:depth>
						</d:scope>
					</d:from>
					<d:where>
						<d:and>
							<d:or>
								
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>image/jpeg</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>image/heic</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>video/mp4</d:literal>
		</d:eq>
	
		<d:eq>
			<d:prop>
				<d:getcontenttype/>
			</d:prop>
			<d:literal>video/quicktime</d:literal>
		</d:eq>
	
							</d:or>
							
							<d:eq>
								<d:prop>
									<oc:owner-id/>
								</d:prop>
								<d:literal>arne</d:literal>
							</d:eq>
						</d:and>
					</d:where>
					<d:orderby>
						<d:order>
							<d:prop><d:getlastmodified/></d:prop>
							<d:descending/>
						</d:order>
					</d:orderby>
					<d:limit>
						<d:nresults>35</d:nresults>
						<ns:firstresult>0</ns:firstresult>
					</d:limit>
				</d:basicsearch>
			</d:searchrequest>
```

**Comment by svenb1234** [comment]
If I understand correctly the difference is that defining which mime type is requested reduces the response time. If so I would suggest to set the query to the default formats of camera apps, i.e. JPEG and MP4 for Android and whatever for iOS.

However, users with raw formats etc. should not be excluded, i.e. one should be able to enable more formats/mime types in the settings of the app.

**Comment by tobiasKaminsky** [comment]
@nextcloud/server-triage any idea how/if we can enhance this without explicitly specifying mimetimes?
Or to phrase it the other way around: why is <d:literal>image/%</d:literal> so damn slow?

**Comment by rullzer** [comment]
Searching in all storages you have access to is just damn slow. 
Basically it explodes because of the nr of shares you have.

**Comment by tobiasKaminsky** [comment]
True, but I guess in this case it is a different problem.
(wrote it also in engineering chat).
One query against our server with "image/%" does not succeed and ends with 500.
Same query but with "image/jpeg" returns in ~10s with correct images.

**Comment by tobiasKaminsky** [comment]
So it seems that if we have another endpoint or enhance the mimetype search, that it helps a lot.
See also above test by @tacruc: on his server it is around 100x faster.

**Comment by skjnldsv** [comment]
> So it seems that if we have another endpoint or enhance the mimetype search

this doesn't seems to be a different endpoint, just different syntax on the mimetype search. I'm not surprised, searching with LIKE% and searching for exact string match doesn't really compare in termes of performances.

In photos we do the same https://github.com/nextcloud/photos/blob/master/src/services/PhotoSearch.js#L94

**Comment by tobiasKaminsky** [comment]
So another test against our server:
search for image/jpeg -> 12s
search for image/jpeg or image/png -> >35s and thus 500 error code
search for image/jpeg AND limit to own user -> 1-3s
search for image/jpeg or image/png AND limit to own user -> 1-3s
searching for any image (image/%) -> 1-3s 

So it basically boils down to reducing scope to own user and then in it amazingly fast.

**Comment by skjnldsv** [comment]
> So it basically boils down to reducing scope to own user and then in it amazingly fast.

Yes, that is why we don't show shares in Photos

**Comment by tacruc** [comment]
So could it be a fix to limit the scope to the own user for now, and fix the shares with the metadata topic later?

**Comment by svenb1234** [comment]
While I understand that it's the easiest "fix", I hope that it is obvious that ignoring shares on a system whose main purpose is sharing without copying, is failure by design.

Just imagine how useful the Photos app in the web client and the photos section in the Android app are to a family that wants to share family photos. Should they only use the file view?

I understand that it might be useful to limit the photos view to certain shares, but the user should be able to select those.

Another aspect as to why ignoring shares in general and without the possibility to select folders does not make sense: why would the same amount of pictures be significantly slower just because they are in a shared folder - on the same host? If I have 2.000 pictures with user A and 2.000 with user B (shared) it should be as fast as having 4.000 pictures just for user A.

Of what use is ignoring shares if one does not know their size and impact? On the same host, if I have 50.000 pictures and the share only 200, I would still not be able to view them in the app although the only represent a fraction of the total number of pictures to display.

It seems there is a general performance problem with folders with many items. Actually, to be more precise,  there seems to be a performance issue with displaying the first items within a folder with many items instantly. Even in file view and not a shared folder. Opening a folder with 5000 photos or videos takes a very long time >20 seconds and the app stalls afterwards for even longer. Opening the same folder with the web client takes still very long but less than half the time and the UI is responding.

So even if Nextcloud seems to be slow, why would the app be any slower than the web client?

**Comment by skjnldsv** [comment]
> So even if Nextcloud seems to be slow, why would the app be any slower than the web client?

When you say web client, you mean the files app?
Because files is not searching through all your files for photos, only listing per directory.
Regarding the photos app, we all agree that this isn't really working the best we would like. But ya know, time... we can't fix everything in one day!

**Comment by tobiasKaminsky** [comment]
I change it now on Android, so it is in sync with photo app.
Once there is progress in tuning the search, please do not forget to mention me/ the clients 💙

**Comment by svenb1234** [comment]
> When you say web client, you mean the files app?
> Because files is not searching through all your files for photos, only listing per directory.
> Regarding the photos app, we all agree that this isn't really working the best we would like. But ya know, time... we can't fix everything in one day!

There are two scenarios I compare the performance.
1. Files web client Vs. files Android app view.
2. Files web client app Vs. Photos web client app.

In both scenarios the compared apps do exactly the same, I.e. displaying items from just one folder.

Yes I mean the files app in the web client and the file view in the Android app. Opening the same folder is a lot slower and stalls when using the android app. Folder with 5000 pictures in it.

But there is also a performance issue with the photos web client app compared to the files web client app. If I use the "your albums" or whatever the "walk the folders" view on the photos app is called and navigate to a folder with 5000 photos it shows "no files" for a long time and then starts to display the items. It does not have to search through all photos but just the items in that folder. Using the file app on the web client is a lot faster in opening that folder and displaying the first few items. Same action, different performance.

Furthermore. Querying a database for the first 40 or so images from its index should be done in less than a second. From then on, only loading the previews takes some time.

**Comment by skjnldsv** [comment]
> In both scenarios the compared apps do exactly the same, I.e. displaying items from just one folder.

Depending on what part of the Photos app you're refering to, this sentence is not true :)
The Folder/Album section have the same performances as the web Files app, as they're using the same methods (only files have pagination).
Here we're talking about the TImeline/Your photos view only, that search through your entire root filesystem for images. The performances is nothing to be compared of :)

**Comment by tobiasKaminsky** [comment]
@skjnldsv https://github.com/nextcloud/android/issues/7245#issuecomment-734139263
There is a query that seems to work quite fast.
What do you think?

**Comment by svenb1234** [comment]
How does that compare to other gallery apps?

**Comment by ggogel** [comment]
I'm facing a similar issue. The main view of the photos app "your photos" works perfectly fine, but the folder view, simply doesn't show pictures on folders with large amounts of images. In folders where I have only a few dozen or hundred pictures it works but I in my main folder, which I use for auto-upload, the app shows just "No photos here". It contains 4800 images. The mobile app is just completely locking up when opening that folder. When I use the normal file view the folder is showing up fine.
I run a pretty beefed out setup with two instances, mariadb and redis on docker swarm.
Would be nice to know if there is any hard-coded limit in the app or something...

**Comment by svenb1234** [comment]
So at least I am not the only one who experiences that this statement

> The Folder/Album section have the same performances as the web Files app

does not match reality. And given that this happens on a "beefed set-up" it is also not a server issue.

This matches my experience on Nextcloud:

> in my main folder, which I use for auto-upload, the app shows just "No photos here". It contains 4800 images. The mobile app is just completely locking up when opening that folder. When I use the normal file view the folder is showing up fine.

Tried the web clients and Android apps of other private clouds such as qnap and Synology, and there I have no issue with the same and even more pictures in the collection! not a single folder. The first picture is shown instantly when opening the gallery, even though the pictures are spread across many folders and more than 50k in total.

This performance issue and the fact that neither the web client nor the Android app are able to sort by "taken date" but only "file modified" leave a pretty big gap to the requirements of a very simple gallery app, leaving aside a stand of the art gallery app.

I know that is is annoying to read but I really do not understand why the product owner(s) of the web client photos app and the Android app did not yet focus on these two basic issues for the gallery functionality in Nextcloud. IMHO being able to show previews, sorting by "taken date" and performance are the three starting requirements for a new photos gallery app. Maybe I take the time to actually search on the play store for a gallery app which cannot sort by date taken to make sure I am not completely off track with my expectations.

**Comment by ggogel** [comment]
Last night I was moving pictures of said large folders into several other folders, separated by year. So in my InstantUpload folder only the few pictures from 2021 were left the photos app was still not able to show them. Then I just deleted this folder and moves my instant upload to /Photos/InstantUpload. This made the photos app work but for some reason made the android app lock up and crash on startup, see https://github.com/nextcloud/android/issues/5926.

So I recreated the instant upload in the root /InstantUpload, and the app worked again. I was able to make the app crash several times only by deleting this folder. The app either doesn't clear data completely on de-installation or has something hard-coded that looks for the instant upload folder in the root.

In any way, all of this is completely unacceptable. I basically have two use cases for nextcloud: sync folders and view files, including photos, on the go from my smartphone or other devices. I don't use anything else. If it isn't able to simply deliver those two simple functionalities, I'm really loosing trust into nextcloud, although I was using it for years now, starting with owncloud back in 2013. I'm actually considering to switch to another solution, also because a few days ago I also had another issue where the client simply hard-deleted a whole folder, which broke the second functionality I'm using, namely syncing.

**Comment by ggogel** [comment]
Oh and I just recognized that I can still reproduce this with one of the newly created folders. It is the largest with 1655 images and again the photo app shows no images. In the normal file view the previews load up super faster, so this really can't be a performance limitation. The previews of the other folders in the photos app also load up very fast. This one folder is just too large again and hits some kind of limitation... 👎

**Comment by tobiasKaminsky** [comment]
> @skjnldsv [nextcloud/android#7245 (comment)](https://github.com/nextcloud/android/issues/7245#issuecomment-734139263)
> There is a query that seems to work quite fast.
> What do you think?

@rullzer @icewind1991 @skjnldsv 
This query works for me locally, on my own instance, and even on our own (remember we have many shares due to Talk).

Do you see any risk in trying this? Is there something better?
my server: ~14s (but I have endless photos)
our server: 3s

**Comment by skjnldsv** [comment]
I replied already, https://github.com/nextcloud/android/issues/7245#issuecomment-737277937

**Comment by tobiasKaminsky** [comment]
Ah, right, this was too long ago for me to remember it.

Then let us wait for feedback of Roeland and Robin.

**Comment by saywebsolutions** [comment]
Is there any recommendation for how to get Media tab (formerly Photos) in the android app working again? We tried the new Version 3.15.1 release but Media tab is still broken. Should we have users downgrade to Version 3.14.1 until this is fixed? Thank you

**Comment by svenb1234** [comment]
What do you mean by broken? It works as in it does display pictures. It does not sort the most recent pictures first and there is no way to navigate to a date or change the sorting. I would have to scroll thousands of pictures before seeing the most recent.

So rather than being broken it got useless.

**Comment by saywebsolutions** [comment]
Fair, the exact error does seem to vary; for some people it's not completely broken as you mention but basically unusable. For others it is actually broken too, for instance on one of my accounts it loads oldest to newest, but will only load a max of 119 media files (the total number is in the thousands but it stops letting me scroll down to seek more entires after 119).

So you're right to be more specific; it's more accurate to describe the issue as broken and/or unusable

**Comment by svenb1234** [comment]
https://github.com/nextcloud/android/issues/7245#issuecomment-733807876 seems to hint towards this not being a server issue. Having the same user experience on both mobile platforms would be great.

**Comment by saywebsolutions** [comment]
Ahh, maybe the android maintainers can talk to the ios app maintainers to figure out what went wrong in the android app?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
