### ISSUE TITLE
[19.0] Broken dbpassword-toggle button

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#20833]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

The dbpassword-toggle button is broken in current 19.0-beta. It works fine in 18.0.

### Steps to reproduce
1. fetch the sources for Nextcloud 19 on a webserver an access from a browser (Mozilla Firefox)
2. toggle the Database to something else than SQLite
3. provide any database password and toggle the eye symbol (dbpassword-toggle)

### Expected behaviour
password should be shown in clear text

### Actual behaviour
nothing happens

no logs or error are shown for this action.

**Comment by MarcinWieczorek** [comment]
Confirmed.
I think commit bba26cb2ebf48413ed938af572ee46b7cb9f0ba2 introduced the bug when installations.js and other files were merged into `core/src/install.js` but the code regarding the password (`$('#dbpass').showPassword().keyup();`) is missing. Could someone confirm this?

**Comment by J0WI** [comment]
:ping_pong: @nextcloud/javascript

**Comment by MarcinWieczorek** [comment]
@J0WI I'm not sure what it's supposed to point at, the url is invalid.
