### ISSUE TITLE
Quotas Accessibly Issue

### ISSUE THREAD

**Issue by FriendlyGamer** [nextcloud/server#20847]
As mentioned on the forums... 
https://help.nextcloud.com/t/accessibly-concern-cannot-set-quota-due-to-zoomed-in-browser-vivaldi/80036

Attached is what I am having troubles with in regards to accessing certain components ( cutting off in the GROUP area and not being able to access others at all like QUOTAS). 
![Screenshot from 2020-05-05 11-05-30](https://user-images.githubusercontent.com/38051855/81227283-2b37fd00-8fba-11ea-9773-fa5a8f6a593f.png) 

Environments as stated in the forum... 
I was using the official snap at the time https://github.com/nextcloud/nextcloud-snap and the following environment was involved as posted there…
Nextcloud server packaged as a snap. It consists of:

Nextcloud 18.0.4
Apache 2.4
PHP 7.3
MySQL 5.7
Redis 5.0
mDNS for network discovery
On Ubuntu Server 18.04 LTS on a 1GB 1vCore VPS. 
Browser Information 
![2020-05-05 10 36 02 version 669aac55a015](https://user-images.githubusercontent.com/38051855/81227506-8b2ea380-8fba-11ea-810a-1d12d0dd5231.png)

**Comment by FriendlyGamer** [comment]
Hi there, might there be further things I may be able to be of help here? Since it have been several months and I am _really confused_ on what's going on or the status of this as a result. 

Thanks very much in advance.

**Comment by szaimen** [comment]
cc @nextcloud/accessibility
