### ISSUE TITLE
[External Storages] Feature request: Ability to add a CDN domain for S3 storage

### ISSUE THREAD

**Issue by mashirozx** [nextcloud/server#20848]
**Is your feature request related to a problem? Please describe.**
The S3 external storage plugin only need me to fill in the S3 hostname, eg. `s3-us-1.aws.com`, and it will test the storage accessibility with and download files from `https://bucket_name.s3-us-1.aws.com` by default. 

However, the download speed from the `https://bucket_name.s3-us-1.aws.com` is poor on my Nextcloud server side. So in my condition, I hope to use a custom CDN domain to download files from S3 Storage instead of the default `http://bucket.hostname`. 

**Describe the solution you'd like**
The easiest solution is to add a field to fill in my CDN domain.

**Comment by Dragon988** [comment]
So create a CDN. This has nothing to do with nextcloud.

**Comment by mashirozx** [comment]
> So create a CDN. This has nothing to do with nextcloud.

Please read carefully 😒

**Comment by Dragon988** [comment]
> 
> 
> > So create a CDN. This has nothing to do with nextcloud.
> 
> Please read carefully 😒

I'm a simpleton.

What stops you from using a custom domain with your own CDN? You can use a reverse proxy for s3-us-1.aws.com along with bucket_name.s3-us-1.aws.com.

AWS -> CDN -> Nextcloud

**Comment by mashirozx** [comment]
I's not easy to reverse proxy AWS S3 upload API, and what I need is using original AWS URL to do thing with API, and using CDN URL to download files only.

**Comment by Dragon988** [comment]
> 
> 
> I's not easy to reverse proxy AWS S3 upload API, and what I need is using original AWS URL to do thing with API, and using CDN URL to download files only.

So how have you setup your CDN url?

Keep in mind nextcloud is a php script. It could be configured in such a way to use a different outbound domain if you want to edit the script... but you will still need a CDN setup to do so.

**Comment by mashirozx** [comment]
So that's the problem, I don't want to modify php files every time when there is a updating of next cloud.

**Comment by Dragon988** [comment]
> 
>
> So that's the problem, I don't want to modify php files every time when there is a updating of next cloud.

I'll let someone else take over from here but:

A) You will need a reverse proxy/cache/CDN setup to do this. There isn't a magical workaround with php code.

B) You can create a pull request and if accepted it will be integrated into nextcloud.

C) You can already use a different inbound/outbound destination if you know what you're doing with Linux. Nextcloud does not have to be edited to achieve this.

Good luck!

**Comment by smorimoto** [comment]
Similar issue: #30917

**Comment by smorimoto** [comment]
In fact, you can solve this issue aggressively by doing something complex, but I don't think that's a good answer on the issue tracker.
