### ISSUE TITLE
Provisioning API returns broken XML 

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#20840]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Send requests to provisioning API, see cURL requests below

### Expected behaviour
Valid XML

### Actual behaviour
Broken XML

The API is using the userId as name of the XML-element. This is breaking for obvious reasons.

### Suggested fix
- Do not use userId as element name. use `<user>` instead. The element already contains an `<id>` element.

Downside: Breaking change plus it's no longer possible to access users directly in JSON (via `data.users.admin`)

### Server configuration
**Nextcloud version:** reproducible on any supported version
**Where did you install Nextcloud from:** git

### API Response:
`curl  -H "OCS-APIRequest: true" http://admin:admin@nextcloud.local/ocs/v1.php/cloud/users/details`
```xml
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <users>
   <admin>
    <enabled>1</enabled>
    <storageLocation>/usr/local/apache2/htdocs/public/nextcloud/data/admin</storageLocation>
    <id>admin</id>
    <lastLogin>1588766990000</lastLogin>
    <backend>Database</backend>
    <subadmin/>
    <quota>
     <free>51709734912</free>
     <used>164</used>
     <total>51709735076</total>
     <relative>0</relative>
     <quota>-3</quota>
    </quota>
    <email/>
    <displayname>admin</displayname>
    <phone></phone>
    <address></address>
    <website></website>
    <twitter></twitter>
    <groups>
     <element>admin</element>
    </groups>
    <language>en_GB</language>
    <locale></locale>
    <backendCapabilities>
     <setDisplayName>1</setDisplayName>
     <setPassword>1</setPassword>
    </backendCapabilities>
   </admin>
   <enabled>1</enabled>
   <storageLocation>/usr/local/apache2/htdocs/public/nextcloud/data/user@example.com</storageLocation>
   <id>user@example.com</id>
   <lastLogin>0</lastLogin>
   <backend>Database</backend>
   <subadmin/>
   <quota>
    <quota>none</quota>
    <used>0</used>
   </quota>
   <email/>
   <displayname>User with at sign</displayname>
   <phone></phone>
   <address></address>
   <website></website>
   <twitter></twitter>
   <groups/>
   <language>en</language>
   <locale></locale>
   <backendCapabilities>
    <setDisplayName>1</setDisplayName>
    <setPassword>1</setPassword>
   </backendCapabilities>
  </users>
 </data>
</ocs>
```

**Comment by rullzer** [comment]
Whe is the xml actally broken?

**Comment by go2sh** [comment]
@rullzer 
> XML elements must follow these naming rules:
>    Element names are case-sensitive
>    Element names must start with a letter or underscore
>    Element names cannot start with the letters xml (or XML, or Xml, etc)
>    Element names can contain letters, digits, hyphens, underscores, and periods
>    Element names cannot contain spaces
Within nextcloud at least the `@` is allowed.

**Comment by georgehrke** [comment]
We also allow `'` (for some reason), which is also no valid xml.
Furthermore, usernames can start with numbers, which is forbidden in XML as well.

**Comment by rullzer** [comment]
O joy...

**Comment by a-schild** [comment]
Potential work arround for consumers of the API:
A possible work arround is to:

    Send a request to get a list of the users (without details)
    /ocs/v1.php/cloud/users

    For each user send a separate request to retrieve the details
    /ocs/v1.php/cloud/users/myuser@mydomain.com

This will work, since the "single" response for the user details has a different xml structure, but the drawback is that we need n+1 requests to get all users

**Comment by a-schild** [comment]
Should this issue not be flagged as "wont be fixed" or similar?

https://github.com/nextcloud/server/pull/20854

**Comment by a-schild** [comment]
Other work arround is to switch to json data format, then it works as expected

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
