### ISSUE TITLE
I hope Nextcloud can be installed and run on Windows without virtual machine or docker.

### ISSUE THREAD

**Issue by jackjenson** [nextcloud/server#20843]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by MorrisJobke** [comment]
There was windows support a few years back. The main problem was that filesystems work a lot different on windows vs linux. This compared with the very small user base was not worth the really big investment that need to be made to have it run on windows. Thus I need to sadly say, that we do not aim to provide Windows support for the server in the close future.

**Comment by jackjenson** [comment]
Thank you 😊!发自我的华为手机-------- 原始邮件 --------发件人： Morris Jobke <notifications@github.com>日期： 2020年5月7日周四 半夜12:45收件人： nextcloud/server <server@noreply.github.com>抄送： Qianhe <593637418@qq.com>, Author <author@noreply.github.com>主    题： Re: [nextcloud/server] I hope Nextcloud can be installed and run on Windows without virtual machine or docker. (#20843)
There was windows support a few years back. The main problem was that filesystems work a lot different on windows vs linux. This compared with the very small user base was not worth the really big investment that need to be made to have it run on windows. Thus I need to sadly say, that we do not aim to provide Windows support for the server in the close future.
