### ISSUE TITLE
When Reverse Proxy leads to Sabre\DAV\Exception\Forbidden

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/server#20845]
### Steps to reproduce
1. Install a fresh installation of nextcloud
2. complete the setup
3. configure a reverse proxy

Nextcloud installed in Server with IP : 10.10.1.154

Accessible from Host Server with out proxy settings in config: http://10.10.1.154/

After setting Proxy settings in config.php (Last 5 lines)

Proxy Server : 10.10.1.150/cloud

Settings in Proxy server:

sudo nano /etc/apache2/sites-available/000-default.conf

        ProxyPreserveHost On
        ProxyVia On
        ProxyPass /cloud http://10.10.1.154/
        ProxyPassReverse /cloud http://10.10.1.154/
        ProxyPassReverseCookiePath /cloud /

### Expected behaviour
Login and Display the files

### Actual behaviour
Logs in with Error "This directory is unavailable, please check the logs or contact the administrator"

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache2

**Database:** Maria DB

**PHP version:** PHP 7.4

**Nextcloud version:** 18.0.4 and also in 18.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Nextcloud

**Nextcloud configuration:**

<?php
$CONFIG = array (
  'instanceid' => '----------------------------------',
  'passwordsalt' => '-------------------------------',
  'secret' => '---------------------------------------',
  'trusted_domains' => 
  array (
    0 => '10.10.1.154',
	1 => '10.10.1.150',
    2 => '10.10.1.151',
  ),
  'datadirectory' => '/cloud_storage',
  'dbtype' => 'mysql',
  'version' => '18.0.4.0',
  'overwrite.cli.url' => 'http://10.10.1.154',
  'dbname' => 'cloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'cloud',
  'dbpassword' => 'cloud',
  'installed' => true,
  'overwritehost' => '10.10.1.150',
  'overwriteprotocol' => 'http',
  'overwritewebroot' => '/cloud',
  'overwritecondaddr' => '10.10.1.154',
  'overwrite.cli.url' => 'http://10.10.1.150/cloud',
);

### Client configuration
**Browser:** : Firefox

**Operating system:**
Windows 10

### Logs

Error | remote | Sabre\DAV\Exception\Forbidden: Requested uri (/cloud/remote.phpp/dav/files/admin/) is out of base uri (/cloud/remote.php/dav/)/var/www/cloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 549: Sabre\DAV\Server->calculateUri()/var/www/cloud/apps/dav/lib/Server.php - line 325: Sabre\DAV\Server->getRequestUri()/var/www/cloud/apps/dav/lib/Server.php - line 151: OCA\DAV\Server->requestIsForSubtree()/var/www/cloud/apps/dav/appinfo/v2/remote.php - line 34: OCA\DAV\Server->__construct()/var/www/cloud/remote.php - line 165: require_once("/var/www/cl ... p")
-- | -- | --

#### Nextcloud log (data/nextcloud.log)

[nextcloud.log](https://github.com/nextcloud/server/files/4588440/nextcloud.log)

**Comment by pkmkrishnakumar** [comment]
Please provide a sample config  in Documentation for various use cases.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by pkmkrishnakumar** [comment]
Thanks Kesselb

I sorted it out , it's true it was a setup problem.

I reinstalled Apache2, Everything works as expected.

It was a problem with many unwanted proxy headers are enabled.

My same old setup works !!! & I will close this issue

Thanks

Krishnakumar Masimalai
