### ISSUE TITLE
Addressbook discovery broken in Nextcloud 19?

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#20856]
I just noticed that my company address books are gone on my Desktop.

I configured them with GNOME Online Accounts where I only enter the main address of the Nextcloud and all address books are discovered.

A quick test showed that I can sync the address book again if I enter the exact Carddav URL for the address book I want to sync. But it seems like the general discovery is broken.

**Comment by georgehrke** [comment]
@schiessle Can you send me a Network capture of the requests please?

**Comment by georgehrke** [comment]
Closing for lack of feedback.
I wasn't able to reproduce it.
