### ISSUE TITLE
Feature Request: Option to hide download link of shared media

### ISSUE THREAD

**Issue by oeves** [nextcloud/server#2085]
We are sharing a lot of small videos (h264 mp4) and the player works very well.

It would be nice to have the option of hiding the download link for selected files to offer only the media player.

**Comment by nickvergessen** [comment]
Hiding the button is easy. However the link itself will still work, because the player uses the exact same endpoint. So we could only pseudo fix this.

**Comment by oeves** [comment]
The pseudo fix sounds perfect. That the file is still downloadable "if you know how" is not a problem i think, because it is also possible to download files from YouTube/Vimeo/etc with the right knowledge for example.

**Comment by MorrisJobke** [comment]
I would vote against this. Adding more and more special options for shares doesn't make it easier. What do you think, @jancborchardt and @karlitschek?

**Comment by karlitschek** [comment]
I agree. Let's not make another option for something that is mainly cosmetic.

**Comment by jancborchardt** [comment]
Yep. What we could do is improve the design of the share view to make the viewer more the focal point, and the download / link area less prominent.
