### ISSUE TITLE
Show progress/spinner when create/delete user in web UI

### ISSUE THREAD

**Issue by koreywithak** [nextcloud/server#2086]
### Steps to reproduce
1. Add or remove a user via Web interface admin page

### Expected behaviour
1. Action should happen without freezing or long delay. It should at least have a progress bar.

### Actual behaviour
1. It can take over 30 seconds for the action to finish, with the page frozen in the meantime.

### Server configuration
**Operating system**:
Linux Jessie lite

**Web server:**
Nginx 1.10.1

**Database:**
MariaDB 10.0

**PHP version:**
7.0. 1

**Nextcloud version:** (see Nextcloud admin page)
10.0. 1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Apt-get

**Signing status:**
"No errors have been found."

**List of activated apps:**
Enabled:
  - activity: 2.3.2
  - bookmarks: 0.9.0
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - tasks: 0.9.3
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocw2lrcmig6j",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "example.com"
        ],
        "datadirectory": "\/media\/cloud_main\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/example.com\/nextcloud",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 2
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, an external HDD at /media/cloud_main

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
N/A

### Client configuration
**Browser:**
Crome: 53.0.2785.116

**Operating system:**
Windows 10

#### Web server error log
{"reqId":"x9pHBU+5\/quvmxKYo3P6","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:36:34+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"AFohX7QJwclkuGlv1luu","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:40:33+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"vild+4yd69zhehEjDbRH","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:42:32+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"Tt\/NAJyfeDC87TQqtSHU","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:43:50+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"7JjWKRD09lt2xfnCtAir","remoteAddr":"masked.ip.address","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 982089 got 81920\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #82)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20161104_21...', Resource id #82)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('Photos\\\/Phone\\\/20...', Resource id #82, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(60): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/nextcloud\\\/remote.php(165): require_once('\\\/var\\\/www\\\/nextcl...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":150,\"User\":\"main.user\"}","level":4,"time":"2016-11-05T03:20:31+00:00","method":"PUT","url":"\/nextcloud\/remote.php\/webdav\/Photos\/Phone\/2016\/11\/IMG_20161104_213614.jpg","user":"main.user"}
{"reqId":"41douJ05mx89j3P36VLn","remoteAddr":"107.12.51.220","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-05T12:41:52+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Phone\/Manual\/","user":"main.user"}
{"reqId":"1OWuAjAiCJTOVblmCXxz","remoteAddr":"107.12.51.220","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-06T14:45:44+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Photos\/Camera","user":"main.user"}
{"reqId":"rCrBzDZm8kaaG1Jt9oPh","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T14:38:42+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/UHC%20health%20statements","user":"main.user"}
{"reqId":"TqhuTtVDj\/Z8R\/CYVJNR","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T14:39:29+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/UHC%20claim","user":"main.user"}
{"reqId":"suQydzaPgMlE\/qn2m9\/E","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T14:45:09+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/Paychecks","user":"main.user"}
{"reqId":"OsPtab3AV0F\/h4dzOhFP","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T15:48:39+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/HSA%20Statements","user":"main.user"}
{"reqId":"gmvtoLgtZtfZiJAFmUcq","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T19:41:22+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/Dental%20Statements\/Claims","user":"main.user"}
{"reqId":"HulSKkpdeAKctEDWcebk","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T21:22:46+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Test%20folder","user":"sync"}
{"reqId":"WgpGqkpWPRFfkN79iHDC","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-11T02:25:54+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Desktop","user":"main.user"}
{"reqId":"gFx8LEIzq5XCzgME9hjU","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-11T02:26:00+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Laptop","user":"main.user"}

#### Nextcloud log (data/nextcloud.log)
{"reqId":"AFohX7QJwclkuGlv1luu","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:40:33+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"vild+4yd69zhehEjDbRH","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:42:32+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"Tt\/NAJyfeDC87TQqtSHU","remoteAddr":"masked.ip.address","app":"files","message":"Upload error: 3 - The uploaded file was only partially uploaded","level":3,"time":"2016-11-01T00:43:50+00:00","method":"POST","url":"\/nextcloud\/apps\/files\/ajax\/upload.php","user":"main.user"}
{"reqId":"7JjWKRD09lt2xfnCtAir","remoteAddr":"masked.ip.address","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 982089 got 81920\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/Directory.php(137): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #82)\\n#1 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('IMG_20161104_21...', Resource id #82)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('Photos\\\/Phone\\\/20...', Resource id #82, NULL)\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT${"reqId":"41douJ05mx89j3P36VLn","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-05T12:41:52+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Phone\/Manual\/","user":"main.user"}
{"reqId":"1OWuAjAiCJTOVblmCXxz","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-06T14:45:44+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Photos\/Camera","user":"main.user"}
{"reqId":"rCrBzDZm8kaaG1Jt9oPh","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T14:38:42+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/UHC%20health%20statements","user":"main.user"}
{"reqId":"TqhuTtVDj\/Z8R\/CYVJNR","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T14:39:29+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/UHC%20claim","user":"main.user"}
{"reqId":"suQydzaPgMlE\/qn2m9\/E","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T14:45:09+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/Paychecks","user":"main.user"}
{"reqId":"OsPtab3AV0F\/h4dzOhFP","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T15:48:39+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/HSA%20Statements","user":"main.user"}
{"reqId":"gmvtoLgtZtfZiJAFmUcq","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T19:41:22+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Documents\/Dental%20Statements\/Claims","user":"main.user"}
{"reqId":"HulSKkpdeAKctEDWcebk","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-10T21:22:46+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Test%20folder","user":"sync"}
{"reqId":"WgpGqkpWPRFfkN79iHDC","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-11T02:25:54+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Desktop","user":"main.user"}
{"reqId":"gFx8LEIzq5XCzgME9hjU","remoteAddr":"masked.ip.address","app":"PHP","message":"stream_get_contents() expects parameter 2 to be integer, string given at \/var\/www\/nextcloud\/3rdparty\/sabre\/http\/lib\/Message.php#81","level":3,"time":"2016-11-11T02:26:00+00:00","method":"MKCOL","url":"\/nextcloud\/remote.php\/webdav\/Sync\/Laptop","user":"main.user"}

#### Browser log
(I'm unsure about this, but hopefully it's not necessary)

**Comment by nickvergessen** [comment]
Please fill out the issue template completly. Otherwise important information is missing.

**Comment by koreywithak** [comment]
The information is now updated.

**Comment by koreywithak** [comment]
I believe this was because I was running on a Raspberry Pi, which was slow. It's better when running on a faster computer. A progress bar is recommended though.

Also, I notice that if you try to use a password that doesn't meet the constraints, no error is given, nothing happens when you click "create." Some error box should show if you try to create a user and it can't; otherwise, it just sits there and the admin is unsure if it's working on it or not.

**Comment by MorrisJobke** [comment]
@skjnldsv This is now done in the new UI, right? - ref #8824

**Comment by skjnldsv** [comment]
@MorrisJobke Yes, I missed this somehow :)
