### ISSUE TITLE
ONLYOFFICE cannot be reached. Please contact admin

### ISSUE THREAD

**Issue by romankh3** [nextcloud/server#20879]
`ONLYOFFICE cannot be reached. Please contact admin` 
I have this error when I try to open a doc or spreadsheet.
I have reinstalled Onlyoffice bit the error is still there.

Also, I have checked, that the Community Document Server is installed and enabled.

Versions:
*  `Nextcloud Server` is `18.0.4`
*  `Community Document Server` is `0.1.5`
*  `ONLYOFFICE` is `4.14`

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

If you found a bug please use the issue template to provide all necessary information to reproduce it.

**Comment by romankh3** [comment]
@kesselb thank you for your fast answer. I've created a new topic in `help.nextcloud.com`.

**Comment by romankh3** [comment]
I found the problem!
there was a wrong settings for ONLYOFFICE. `Document Editing Service address` was wrong. it refers to `http` host without domain name.

When I changed it to my https URL with domain name it was fixed it.

**Comment by blissarts** [comment]
Hello,
can you please share how exactly you changed the "Document Editing Service address".
I have the same issue.

Thanks, BR

**Comment by romankh3** [comment]
@blissarts, here it is
<img width="1666" alt="Screen Shot 2020-07-09 at 9 46 35 PM" src="https://user-images.githubusercontent.com/16310793/87078858-e89ad700-c22d-11ea-800d-58b51dc8b896.png">

**Comment by rubo77** [comment]
can you please give the complete path, you added in your **Document Editing Service address**?
