### ISSUE TITLE
WhatsNew für Apps?

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#20888]
Hello Team,

NC has the WhatsNew backend to provide updates for the NC release.
I think this feature might be interesting for Apps also - in my case I want to inform Analytics user about new features.

Current flow to my understanding:
OCP.WhatsNew.query()
=> WhatsNewController.php
===> check `preferences` table for `whatsNewLastRead` per `userid`
===> Updater/ChangeCheck.php
=====> Updater/ChangesMapper.php
=======> check `whats_new`table

I see 2 ways to go:
- an app owner "forks" these files and implements them on an own "app_whats_new" table
- the process is enhanced with an app-id to be able for apps to use the existing framework including UI
this would be a nice one with the app just calling OCP.WhatsNew.query() with a parameter. everything else is NC out of the box

@blizzz, @ChristophWurst 
what do you think?

![Screenshot 2020-05-09 at 11 02 56](https://user-images.githubusercontent.com/13385119/81469326-ac72d800-91e4-11ea-82e2-b4797d5cc885.png)

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/server/issues/9165

**Comment by Rello** [comment]
nice "historic" find :-)
my idea would not to that far with the integration in the app store. 
but the concept based on the xml is a good one

**Comment by blizzz** [comment]
Let's continue with #9165 (closing as dup)

Right now it does not have a priority, but yeah, it would make it complete.
