### ISSUE TITLE
Remove abandoned properties from oc_properties table

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#20887]
## Expected behavior
Invalid/unrequired properties should be removed from the **oc_properties** table.

## Current behavior
After checking the list of configured and/or shared ressources, I found several entries, which seem to be outdated, because they definitely doesn't exist anymore. Therefore these abandoned entries should automatically be removed.
```
MariaDB [nextcloud]> select * from nc_properties;
+---------+------------------------------------------------------------+-------------------------------------------+---------------+----+
| userid  | propertypath                                               | propertyname                              | propertyvalue | id |
+---------+------------------------------------------------------------+-------------------------------------------+---------------+----+
...
| lucy    | calendars/lucy/feiertage2016_shared_by_charlie             | {http://owncloud.org/ns}calendar-enabled  | 0             | 14 |
| lucy    | calendars/lucy/feiertage2010-2015_shared_by_charlie        | {http://owncloud.org/ns}calendar-enabled  | 0             | 15 |
| lucy    | calendars/lucy/schulferiennrw2015-2016_shared_by_charlie   | {http://owncloud.org/ns}calendar-enabled  | 0             | 16 |
...
| lucy    | calendars/lucy/feiertage-2017_shared_by_charlie            | {http://apple.com/ns/ical/}calendar-color | #748be7       | 37 |
| lucy    | calendars/lucy/schulferien-nrw-2017_shared_by_charlie      | {http://apple.com/ns/ical/}calendar-color | #748be7       | 38 |
...
+---------+------------------------------------------------------------+-------------------------------------------+---------------+----+

```
## Steps to reproduce
1. Check the oc_properties table in the database.
2. Identify shared resources which doesn't exist anymore and remove it.

#### Server Configuration
OS: Linux 4.9.218
Web server: Apache2 2.4.41
Database: MariaDB 10.2.24
PHP version: 7.3.13
Nextcloud version: 18.0.4

#### Client Configuration
Browser: Mozilla Firefox 76.0.1
Operating system: Windows 10

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by j-ed** [comment]
@szaimen I've just checked the content of the mentioned table in my database. It still contains more than 20 records from legacy shared calendars which have already been deleted in the meantime. So yes, there is still a requirement to add a kind of house-keeping process to get these abandoned records removed automatically.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!
