### ISSUE TITLE
Problem during occ db:convert-type from postgres to mysql: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x9F |...' for column `nextcloud_main`.`oc_mail_messages`.`subject`

### ISSUE THREAD

**Issue by ksieluzycki** [nextcloud/server#20883]
For me it is a minor issue, but it may be important for others.

### Steps to reproduce
1. Use mail app
2. Have some e-mail with strange subject (probably emoji; I do not have this mail in my inbox as it was deleted months ago. I also purged mail table as a workaround for this problem)
3. Convert db from postgres to mysql using occ db:convert-type --all-apps mysql

### Actual behaviour
Conversion stopped with following error:
SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x9F |...' for column `nextcloud_main`.`oc_mail_messages`.`subject` at row 1

detailed message in log section.

**Operating system:**
Debian 10 Buster 4.19.0-8-amd64
**Web server:**
Apache 2.4.38-3
**Database:**
Postgresql 11.7 and Mariadb 10.3
**PHP version:**
7.3
**Nextcloud version:**
18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated
**Where did you install Nextcloud from:**
From official webpage

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
$CONFIG = array (
  'instanceid' => '##EDITED##,
  'passwordsalt' => '##EDITED##',
  'secret' => '##EDITED##',
  'trusted_domains' =>
  array (
    0 => '##EDITED##',
    1 => '##EDITED##',
    2 => '##EDITED##',
    3 => '##EDITED##',
  ),
  'datadirectory' => '/home/nextcloud',
  'dbtype' => 'pgsql',
  'version' => '18.0.4.2',
  'overwrite.cli.url' => 'https://##EDITED##:64567',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'nextcloud',
  'dbpassword' => '##EDITED##',
  'installed' => true,
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => '##EDITED##',
  'mail_domain' => '##EDITED##',
  'maintenance' => true,
  'theme' => '',
  'loglevel' => 2,
  'updater.release.channel' => 'stable',

</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Logs

In AbstractMySQLDriver.php line 106:
 
  An exception occurred while executing 'INSERT INTO `oc_mail_messages` (`id`, `uid`, `message_id`, `mailbox_id`, `subject`, `sent_at`, `flag_answered`, `flag_deleted`, `flag_draft`, `flag_flagged`, `flag_seen`, `flag_forwarded`, `flag_jun
  k`, `flag_notjunk`, `updated_at`, `structure_analyzed`, `flag_attachments`, `preview_text`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [1512, 353, "<1d0ada203e6047e3df11c874e.5d3104f501.20200102213807.fac06
  111a8.f8e49bbe@mail8.sea61.rsgsv.net>", "28", "Happy New Year\u00a0\ud83c\udf1f | 50% off Drops Premium", 1578001139, false, false, false, false, false, false, false, false, null, false, null, null]:
 
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x9F |...' for column `nextcloud_main`.`oc_mail_messages`.`subject` at row 1
 

In PDOStatement.php line 119:
 
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x9F |...' for column `nextcloud_main`.`oc_mail_messages`.`subject` at row 1
 

In PDOStatement.php line 117:
 
  SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x8C\x9F |...' for column `nextcloud_main`.`oc_mail_messages`.`subject` at row 1### Server configuration

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
no related info in nextcloud.log (nextcloud in maintenance mode during conversion)
</details>

**Comment by ksieluzycki** [comment]
Sorry, I forgot to add - the mysql base is freshly created with character set utf8, using command from nextcloud manual:
CREATE DATABASE IF NOT EXISTS nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

**Comment by ksieluzycki** [comment]
I had same error with oc_ocsms_smsdatas, but I think I found the source of the problem. Solution is simple - just add 'mysql.utf8mb4' => true in config before running migration.

Just to be clear, I have in mariadb config:  
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci

However, lib/private/DB/ConnectionFactory.php on line 222 checks for this variable in config, and if it is not here, sets collation for newly created tables to utf8_bin. And that causes problems with emojis...

**Comment by a4bits** [comment]
Found possible solution

set your mariadb mysql.cnf
from 
` init-connect='SET NAMES utf8'`
to
` init-connect='SET NAMES utf8mb4'`

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/mail/issues/4299
