### ISSUE TITLE
Copying several (big) files from external SFTP storage causes DoS

### ISSUE THREAD

**Issue by llucax** [nextcloud/server#20884]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Configure an external SFTP storage (if it is slowish, better)
2. Select several (at least the amount of `pm.max_children` configured in PHP FPM) big files (al least hundreds of megabytes) from the external storage
3. Copy them to a local folder

### Expected behaviour
Copying happens in the background and the nextcloud server keeps working as usual.

### Actual behaviour
The copy starts in the background for `pm.max_children` files and all further requests to the nextcloud server get a timeout until one of the files being copied finishes.

Also after it finishes, there is a message in the UI: `Could not copy "<FILE COPIED>" ✖` for each file. But if I go to the destination folder after a while, the failed files are there.

#### Analysis

The main issue here seems to be the UI is doing one request for each file, triggering a lot of php workers on the server. Then, those workers are long lasting, because the download of the files take quite a while. Then I guess there is some browser timeout happening, which triggers the "Could not copy" error, while the workers keep downloading the file in the server. Then if the amount of files copied are equal or bigger than the maximum configured workers in the server, you end up in a DoS, which is bad.

I think it would make more sense, first of all, to do only one request for all the files that need to be copied and parallelize all the downloads with asynchronous I/O (but I'm not sure if this is possible in PHP, but I want to believe it is). That would get rid of many of the problems listed above. There is still the problem of: eventually hitting a maximum time a PHP process can live, which is usually limited. A proper solution would probably be to have a separate download server that doesn't have the time limits the general PHP process have and that can manage the downloads in a more reasonable way, with a queue and paralellizing only a handful of downloads at the time. Then some async mechanism to report progress or status to the UI.

### Server configuration

**Operating system:** Raspbian GNU/Linux 10

**Web server:** 2.4.38-3+deb10u3

**Database:** 10.3.22

**PHP version:** 7.3.14-1~deb10u1

**Nextcloud version:** 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh from version 18, but applied some path-level update

**Where did you install Nextcloud from:** nextcloudpi

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:                 
  - accessibility: 1.4.0
  - activity: 2.11.0     
  - apporder: 0.9.0
  - audioplayer: 2.10.0
  - audioplayer_editor: 0.2.2     
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.3
  - checksum: 0.4.4 
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0               
  - contacts: 3.3.0   
  - dav: 1.14.0 
  - dicomviewer: 1.2.2  
  - event_update_notification: 1.0.1
  - extract: 1.2.4
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0     
  - files: 1.13.1    
  - files_downloadactivity: 1.7.0                                                   [27/317]
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_pdfviewer: 1.7.0
  - files_photospheres: 1.0.8
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - flowupload: 0.1.8
  - fulltextsearch: 1.4.1
  - keeweb: 0.6.2
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.4
  - maps: 0.1.6
  - metadata: 0.11.1
  - news: 14.1.6
  - nextcloud_announcements: 1.7.0
  - nextcloudpi: 0.0.1
  - notes: 3.2.0 
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - occweb: 0.0.7
  - ocr: 6.0.35
  - password_policy: 1.8.0
  - phonetrack: 0.6.2
  - photos: 1.0.0
  - previewgenerator: 102.2.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.0
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - tasks: 0.12.2
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - unsplash: 1.1.5
  - updatenotification: 1.8.0
  - video_converter: 0.1.4
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - groupfolders
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{                                                                                           
    "system": {                                                                             
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",                                    
        "secret": "***REMOVED SENSITIVE VALUE***",                                          
        "trusted_domains": {                                                                
            "0": "localhost",                                                               
            "1": "nextcloudpi.local",                                                       
        },                                                                                  
        "datadirectory": "***REMOVED SENSITIVE VALUE***",                                   
        "dbtype": "mysql",                                                                  
        "version": "18.0.4.2",                                                              
        "overwrite.cli.url": "https:\/\/192.168.2.9\/",                                    
        "dbname": "***REMOVED SENSITIVE VALUE***",                                         
        "dbhost": "***REMOVED SENSITIVE VALUE***",                                         
        "dbport": "",   
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",                                         
        "dbpassword": "***REMOVED SENSITIVE VALUE***",                                     
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",                                     
        "instanceid": "***REMOVED SENSITIVE VALUE***",                              [19/396]
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },  
        "tempdirectory": "\/srv\/nextcloud\/data\/tmp",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": 2048,
        "preview_max_y": 2048,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\SVG",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MKV",
            "OC\\Preview\\MP4",
            "OC\\Preview\\AVI"
        ],  
        "jpeg_quality": "60",
        "overwriteprotocol": "https",
        "maintenance": false,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": "2",
        "log_type": "file",
        "htaccess.RewriteBase": "\/",
        "mail_sendmailmode": "smtp",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls"
    }
}
```
</details>

**Are you using external storage, if yes which one:** sftp (as described in the "how to reproduce")

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 72.0.2

**Operating system:** Debian

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Fri May 08 20:04:11.373124 2020] [proxy_fcgi:error] [pid 5565:tid 2619282464] (70007)The timeout specified has expired: [client 192.168.2.146:45367] AH01075: Error dispatching request
 to : (polling)                                                                             [Fri May 08 20:04:12.946395 2020] [proxy_fcgi:error] [pid 5566:tid 2610889760] (70007)The ti
meout specified has expired: [client 192.168.2.106:37918] AH01075: Error dispatching request
 to : (polling)                                                                             [Fri May 08 20:04:55.823282 2020] [proxy_fcgi:error] [pid 5566:tid 2872796192] (70007)The ti
meout specified has expired: [client 192.168.2.194:53978] AH01075: Error dispatching request
 to : (polling)                                                                             
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"FBqU1HEBeb4Dm7DnUW3U","level":2,"time":"2020-05-03T17:30:03+00:00","remoteAddr":"","user":"--","app":"fulltextsearch","method":"","url":"--","message":"Exception while cronIndex: OCA\\FullTextSearch\\Exceptions\\PlatformNotSelectedException - Admin have not selected any IFullTextSearchPlatform","userAgent":"--","version":"18.0.4.2"}                        
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

Browser console:
```
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Refreshing device list failed. 
Object { error: Exception, errorString: "[Exception... \"NS_ERROR_UNKNOWN_HOST\"  nsresult: \"0x804b001e (NS_ERROR_UNKNOWN_HOST)\"  location: \"JS frame :: resource://services-common/rest.js :: onStopRequest :: line 488\"  data: no]", message: null, code: null, errno: null, toString: toString() }
browser-sync.js:249:15
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. 2
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. 2
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
1588966209513	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 151"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:151
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:167
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:352
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:293
1588966209553	addons.update-checker	WARN	onUpdateCheckComplete failed to parse update manifest: [Exception... "Update manifest is missing a required addons property."  nsresult: "0x80004005 (NS_ERROR_FAILURE)"  location: "JS frame :: resource://gre/modules/addons/AddonUpdateChecker.jsm :: getRequiredProperty :: line 151"  data: no] Stack trace: getRequiredProperty()@resource://gre/modules/addons/AddonUpdateChecker.jsm:151
parseJSONManifest()@resource://gre/modules/addons/AddonUpdateChecker.jsm:167
onLoad()@resource://gre/modules/addons/AddonUpdateChecker.jsm:352
UpdateParser/<()@resource://gre/modules/addons/AddonUpdateChecker.jsm:293
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively. 3
Content Security Policy: Directive ‘child-src’ has been deprecated. Please use directive ‘worker-src’ to control workers, or directive ‘frame-src’ to control frames respectively.
Content Security Policy: The page’s settings blocked the loading of a resource at inline (“default-src”). 2 panel.js:62:24
```
</details>

**Comment by llucax** [comment]
I realized this was actually a DoS when I was in the middle of the report, and now that I submitted it I guess if I should have reported it as a security issue.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/security/policy if you still want to submit it as security Issue.

**Comment by llucax** [comment]
I'm not chasing a bounty (and even if i would it says there that DoS are not bounty-worthy), so I'm not sure if it makes sense to submit again. Can you just change the issue label or the issue reporting template is also very different? Also there is responsible disclosure, I'm sorry if I shouldn't have made this public but it seems like a very minor-ish issue, as I said I just realized this is actually a DoS after I submitted it. Just to clarify, I'm not a security specialist.

On 9 May 2020 01:39:32 GMT+02:00, kesselb <notifications@github.com> wrote:
>https://github.com/nextcloud/server/security/policy if you still want
>to submit it as security Issue.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/20884#issuecomment-626064582

-- 
Leandro Lucarella (luca)
Sent from my phone. Please excuse my brevity and any typos.

**Comment by rullzer** [comment]
Mmm it should indeed queue them up and do max X (where X is some sane number) of copies.

@danxuliu @skjnldsv any idea here

**Comment by skjnldsv** [comment]
Could use https://github.com/sindresorhus/p-queue
But I no touching the upload legacy script, super risky

**Comment by harrison-tc** [comment]
Given how Nextcloud works... the premise is that "Any long-running php script that is executed on demand can trigger a denial of service". The scope is limited to users with sufficient credentials to run the offending code, so someone with a login, third-party storage, or a public link that happens to use one of these methods.

A queuing system for the downloads would create a different DoS condition, where a large number of requests in the download queue would deny access to external storage. The architecture of Nextcloud is such that a particular worker that receives a request needs to be able to fulfil it itself... if that means downloading it over SFTP, or just reading it from the local filesystem.

The mitigation for day to day use would be to improve the connection to the SFTP service, or increase the number of php-fpm workers to handle the expected load.

**Comment by llucax** [comment]
I'm sorry, I can understand if you consider that the amount of work to improve this is not worth it, but having a DoS on a particular external storage is clearly an improvement over having a DoS over the WHOLE SERVER. Specially when it can be a completely unintended DoS, as it happened to me personally.

I'm my particular case the sftp server is on a local network over a GB Ethernet connection, so there isn't much to improve really. It just happened that I wanted to copy like 10 big files that took more than a minute each, and the server just stopped responding so I couldn't even see the log without logging into the server via SSH. Just having my external sftp take a long time to process more files seems totally reasonable, specially if the user is well informed that there are X files already queued.

Finally, what I did was just to increase the number of workers to reduce the likelihood of having this again at the risk of having a big amount of cpu intensive requests instead of a big amount of I/O bound requests and have my server's CPU chocking (and unintentionally DoS-ing me again).

On 9 May 2020 19:59:51 GMT+02:00, harrison-tc <notifications@github.com> wrote:
>Given how Nextcloud works... the premise is that "Any long-running php
>script that is executed on demand can trigger a denial of service". The
>scope is limited to users with sufficient credentials to run the
>offending code, so someone with a login, third-party storage, or a
>public link that happens to use one of these methods.
>
>A queuing system for the downloads would create a different DoS
>condition, where a large number of requests in the download queue would
>deny access to external storage. The architecture of Nextcloud is such
>that a particular worker that receives a request needs to be able to
>fulfil it itself... if that means downloading it over SFTP, or just
>reading it from the local filesystem.
>
>The mitigation for day to day use would be to improve the connection to
>the SFTP service, or increase the number of php-fpm workers to handle
>the expected load.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/20884#issuecomment-626213561

-- 
Leandro Lucarella (luca)
Sent from my phone. Please excuse my brevity and any typos.

**Comment by harrison-tc** [comment]
Sorry, I wrote that poorly, I don't think I was clear on what the implications were. With a queue, you have no way to know if the user is still there when you do end up servicing the request and all file operations must be kept in order to avoid deadlocking on the external storage. The issue you're describing can occur with any long running script, not just external downloads, so another mitigation might be more appropriate. 

Ideally, Nextcloud would be able to designate some workers as "can go to external storage/run long-running scripts and some workers as "UI and management things", so that this kind of thing doesn't block the entire instance, but I don't know if that's possible architecturally.

**Comment by skjnldsv** [comment]
> I'm sorry, I can understand if you consider that the amount of work to improve this is not worth it

No, it's not about not being worth it, it's about it being risky
Touching those files always result in lots of issues afterwards.
So until we properly migrate the files app and have a whole new clean code everyone understand, this is just a risk I'm not willing to take

**Comment by llucax** [comment]
That I can perfectly understand too. I was referring to the other reply (saying having a queue will add another DoS).

On 11 May 2020 11:18:46 GMT+02:00, "John Molakvoæ" <notifications@github.com> wrote:
>> I'm sorry, I can understand if you consider that the amount of work
>to improve this is not worth it
>
>No, it's not about not being worth it, it's about it being risky
>Touching those files always result in lots of issues afterwards.
>So until we properly migrate the files app and have a whole new clean
>code everyone understand, this is just a risk I'm not willing to take
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/20884#issuecomment-626580755

-- 
Leandro Lucarella (luca)
Sent from my phone. Please excuse my brevity and any typos.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by llucax** [comment]
Hi @szaimen , thanks for the heads up. I'm running 25.0.5 now but I'm not using external storage anymore, so it's not easy to test. I will reopen if I come across this issue again. Thanks!
