### ISSUE TITLE
File options list is blurred

### ISSUE THREAD

**Issue by jooola** [nextcloud/server#20889]
### File options list is blurred

When using the CSS property `translationX(50%)`, the file options is blurred.

Duplicate already closed: #13996

![image](https://user-images.githubusercontent.com/19195485/81470284-5c970f80-91ea-11ea-80dc-c26a0bef1c13.png)

This could be fixed by not using translationX (which IMO should actually always be avoided). I used `margin-right: -8rem;` but that's not responsive in any way and the popover isn't properly placed.

![image](https://user-images.githubusercontent.com/19195485/81470368-bac3f280-91ea-11ea-93db-a77b2d889f29.png)

### Steps to reproduce
1. Select file
2. Open options list

### Expected behaviour

Not to be blurred.

### Actual behaviour

List is blurred

### Client configuration
**Browser:** Firefox 75

**Operating system:** Debian Buster

**Comment by jooola** [comment]
https://github.com/nextcloud/server/search?q=translateX%28&unscoped_q=translateX%28

**Comment by kesselb** [comment]
cc @skjnldsv

**Comment by skjnldsv** [comment]
I've been noticing that quite often yep

**Comment by PVince81** [comment]
I'm not seeing this with Nextcloud 22.2.0 neither with Firefox 93 nor Chromium 95 on openSUSE Tumbleweed 20211107
<img width="133" alt="image" src="https://user-images.githubusercontent.com/277525/141341913-bf7ed7f6-b054-4434-808d-d09323283667.png">

I do remember seeing effects like this when using CSS3 effects (GPU based) in older versions of Chromium, so it could be a glitch of the operating system or browser.

Please reopen and state your OS + browser if it still happens for you in Nextcloud 22.2.0+
