### ISSUE TITLE
Special characters Parsed incorrectly

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/server#20899]
I just installed the latest Version with the Webinstaller on my Webspace. I use a database server and changed the language Settings to German (Sie, förmlich) within the nextcloud settings. On the Security Page one Heading shows the Text: "Geräte (&)amp; Sitzungen". While the ä ist displayed correctly the & is not

I had to add the brackets to display it here without turning into an &

**Comment by kesselb** [comment]
Thank you for reporting 👍

Closing as duplicate of https://github.com/nextcloud/server/issues/18662.
