### ISSUE TITLE
Checkbox alignment is broken

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2089]
Just looks not okay anymore

## Sharing
![files_-_nextcloud_-_2016-11-11_09 21 55](https://cloud.githubusercontent.com/assets/213943/20208717/56b6108a-a7f0-11e6-9a85-8193a0a26b52.png)

## Activity settings
![bildschirmfoto vom 2016-11-11 09-19-42](https://cloud.githubusercontent.com/assets/213943/20208724/5e845948-a7f0-11e6-9ff1-adb02eeb704d.png)

When all are checked or unchecked, they are all aligned @nextcloud/designers

**Comment by jancborchardt** [comment]
This is most likely related to »Fix checkbox left margin glitch« #1971 – @skjnldsv you wanna look into this too? ;)

**Comment by MorrisJobke** [comment]
I can't reproduce this - neither on Firefox nor on Chrome

**Comment by nickvergessen** [comment]
Caused by theming, only when colors are used this is an issue.

So mentioning @juliushaertl

**Comment by juliushaertl** [comment]
@nickvergessen I'll have a look.

**Comment by juliushaertl** [comment]
Fix is at #2157
