### ISSUE TITLE
Multiple Errors

### ISSUE THREAD

**Issue by ThorgerJ** [nextcloud/server#20900]
### Steps to reproduce
1. rent Webspace at Netcup.de
2. Install Nextcloud with Webinstaller
3. Get Errors spammed

### Expected behaviour
No Errors in Log

### Actual behaviour

- Invalid argument supplied for foreach() at /var/www/vhosts/x/x/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#120
- Trying to access array offset on value of type null at /var/www/vhosts/x/x/3rdparty/leafo/scssphp/src/Compiler.php#5230

Also i experienced Other Problems with Nextcloud over all kind of Servers and Platforms in the last Versions:

- Often no Memory Cache is detected even though one is installed
- imagick is often not detected even though it is installed
-  Most annoying: There are multiple Database Informations/Errors after a FRESH installtion. This shouldnt be at all. A fresh installation should always install in a way that no errors/infos schould appear. Regarding big int and missing indexes.
- Cron rarely Working even thought it should be available. God knows why but its hella annoying

**Comment by Dragon988** [comment]
Have you contacted your web host for assistance?

This does not sound like a nextcloud issue.

**Comment by ThorgerJ** [comment]
Not yet but it seems like nextcloud tries to use functions that are not available in this environment. In no case the log should be spammed with error messages and in best case nextcloud caches it to show a message once somewhere. Its just a normal webspace in the plesk environment which is rather usual.

Regarding the oter listest issues its definately a nextcloud problem. There are multiple issues for it already.

**Comment by kesselb** [comment]
Please use the search before creating a bug report.

`Trying to access array offset on value of type null at /var/www/vhosts/x/x/3rdparty/leafo/scssphp/src/Compiler.php#5230`

https://github.com/nextcloud/server/search?q=org%3Anextcloud+is%3Aissue+Trying+to+access+array+offset+on+value+of+type+null&type=Issues

    Invalid argument supplied for foreach() at /var/www/vhosts/x/x/apps/serverinfo/lib/OperatingSystems/DefaultOs.php#120

https://github.com/nextcloud/server/search?q=org%3Anextcloud+OperatingSystems%2FDefaultOs.php%23120&type=Issues

`A fresh installation should always install in a way that no errors/infos schould appear. Regarding big int and missing indexes.`

https://github.com/nextcloud/server/issues?q=is%3Aissue+big+int+and+missing+indexes

`Often no Memory Cache is detected even though one is installed` 

Yep. It's a false positive and fixed. A function is used to check if opcache is enabled or not. Those function is disabled by Plesk by default hence the warning. 

`Cron rarely Working even thought it should be available. God knows why but its hella annoying`

That happens sometime if multiple php versions are available and the cron is setup in a wrong way and a topic for https://help.nextcloud.com/.

>  There are multiple issues for it already.

Yep. No need to have another "multiple errors" issue open. A bug tracker is usually one issue per bug (or feature request) and no duplicates.

**Comment by ThorgerJ** [comment]
Thank you for the information you fond many of the issues that i wasnt able to find. I appreciate your in depth answer.

**Comment by kesselb** [comment]
> `A fresh installation should always install in a way that no errors/infos schould appear. Regarding big int and missing indexes.`
> 
> https://github.com/nextcloud/server/issues?q=is%3Aissue+big+int+and+missing+indexes

https://github.com/nextcloud/server/issues/20212 you already reported that a while ago. 

Please don't abuse our issue tracker as support channel. Ask the friendly community for advice: https://help.nextcloud.com/.
