### ISSUE TITLE
l10n: Changed information in Nextcloud update details

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#20921]
During Nextcloud updates, I noticed in the "Detailed logs" that two information should be changed:
Detailed logs

- Set log level to debug
- Reset log level

They should be changed to:

- Setting the log level for debugging
- Resetting the log level

This is information for the user as to what was done. Example other information for an update that is in the appropriate form:

- Starting code integrity check
- Finished code integrity check

![obraz](https://user-images.githubusercontent.com/47037905/81553115-e8dd3a00-9384-11ea-90e8-7a2acf3286a6.png)
![obraz](https://user-images.githubusercontent.com/47037905/81553250-16c27e80-9385-11ea-992f-ececd6cda057.png)

**Comment by skjnldsv** [comment]
Hi,

Are you referring to the translation that is wrong or the initial worfing?
Translations are managed on http://transifex.com/nextcloud/

**Comment by Valdnet** [comment]
> Are you referring to the translation that is wrong or the initial worfing?

@skjnldsv I am referring to the source of the text string.

> Translations are managed on http://transifex.com/nextcloud/

Yes I know about it. I'm a reviewer on Transifex 😉.

**Comment by skjnldsv** [comment]
Okay, easy change to make then :)

**Comment by Nils160988** [comment]
I tried to open a pull request for that, please check if that worked as intended as I haven't done this before like this.

Also I thought the wording "Setting log level to debug" and "Resetting log level" takes your suggestions into account and also sticks more to the way the other messages are phrased.

**Comment by Valdnet** [comment]
> Also I thought the wording "Setting log level to debug" and "Resetting log level" takes your suggestions into account and also sticks more to the way the other messages are phrased.

That was exactly what it was about.

In PR, I asked @skjnldsv to be reviewed.
