### ISSUE TITLE
l10n: Addition of text strings to be translated

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#20920]
When installing the sample application for Nextcloud, untranslated information appeared. Understanding why this happens, I noticed a lot of text strings in, for example, https://github.com/nextcloud/server/blob/1762a409f954fd9a66e7572704ea9ba7813601b4/lib/private/Installer.php#L297 that cannot be translated. **Is this the intended purpose?**

I will say that it is uncomfortable for a user in a language other than English.
It may give you the opportunity to translate them in Transifex.

![obraz](https://user-images.githubusercontent.com/47037905/81550452-8a15c180-9380-11ea-96aa-456f902b009b.png)

**Comment by skjnldsv** [comment]
Wait actually this is on purpose, this is the appID, not eh appname.
This is admin debug output, so on purpose
