### ISSUE TITLE
Activity/Notifications improvements

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#20929]
# Summary

Right now the activity and notifications are unrelated but they feel related. The plan is to make this 1 integrated experience. So activities are generated and you get some as mail or push as well.

# Details

An activity is just an event that happened that you can later see in your activity stream. Right now activities and notifications are separated. But what we'd want is that certain activities could automatically trigger a notifications. And this is configurable in the settings.

## Automatic notification generation

We want to provide a way for certain activities to be registered as 'notifiable'. For activities that are generic we just generate the mail/push notification ourselves. If an app wants to provided a detailed/special notification this should still be possible.

## API

We will provide a set of interfaces and classes. These can be used to control the which events send notification mails or push events. They will also control how the notifications are send.

# Acceptance criteria

* [x] I do not want to be able to filter anymore what goes into the activity stream everything should go and the setting should be gone.
* [x] I want to be able to configure for some settings if I get a mail or a notifications for those activities
* [x] For generic activities a default notification (push and mail) template should be used
* [x] An activity should be able to provide its own notification if desired

**Comment by tobiasKaminsky** [comment]
Needs to be clarified how we do this on clients.

**Comment by jancborchardt** [comment]
Since we do not have any settings for this on mobile or desktop atm, that is out of scope for the initial implementation anyway. In the future we can think about exposing the exact same settings we have on the server also via the clients.

**Comment by tobiasKaminsky** [comment]
Ah, I assumed that this combination is also reflected on web UI and thus mobile should be consistent too…

**Comment by MorrisJobke** [comment]
https://github.com/nextcloud/activity/pull/471
https://github.com/nextcloud/server/pull/21542

**Comment by MorrisJobke** [comment]
> * [ ]  An activity should be able to provide its own notification if desired

@icewind1991 I guess this is still pending, right?

**Comment by icewind1991** [comment]
An app can do that by calling `IEvent::setGenerateNotification` to disable the automated notification

**Comment by MorrisJobke** [comment]
Seems that this is done now 👍
