### ISSUE TITLE
Sharing a PDF with password protection + hide download results in cURL error 3

### ISSUE THREAD

**Issue by sray** [nextcloud/server#20927]
**Describe the bug**
If you share a pdf using a share link with password protection and you tick "hide download" you get the following error message: "cURL error 3: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)"

**To Reproduce**
1. Upload a PDF
2. Click on 'the share icon'
3. Click on '+' behind the 'Share link' label
3. Enter Password (if password protection is mandatory, or activate password protection manually)
4. Click on '...' behind the 'Share link' label
5. Click on the check box 'Hide download' to activate the feature to hide the download button
6. Copy share link url
7. open then share link in separate browser window (make sure to log out first)
8. See error

**Expected behavior**
See the PDF without the inline PDF menu open (just presentation mode like you can activate with pressing F5 in most PDF reader clients) and now download button

**Screenshots**
![Screenshot from 2020-01-31 20-22-59](https://user-images.githubusercontent.com/1809538/73568458-b8722f80-4468-11ea-87f7-2471248f5d8d.png)
![Screenshot from 2020-01-31 20-24-57](https://user-images.githubusercontent.com/1809538/73568457-b8722f80-4468-11ea-8282-c0e1b7e20a05.png)

**Host Info:**
 - OS: Debian 10
- setup: apache running nextcloud behind nginx proxy

If you need more host infos, to reproduce the problem, let me know which ones.

**Comment by kesselb** [comment]
Same error message but different file type: https://github.com/nextcloud/server/issues/20927

https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md is the template to report issues. Add the missing information to your post.

**Comment by sray** [comment]
**Client configuration**
Browser: Chrome, Firefox

**Comment by sray** [comment]
@kesselb I am not comfortable publish **all setup details** of my nextcloud setup here as this may increase the attack vector for someone interested in the production systems I support and maintain. So, it would be good to know, which ones are most likely relevant to the shared file password protection. A pointer to the code section dealing with shared file password protection would probably be enough. If I can figure out the parts there by skimming it, I will provide the probably relevant setup details then.

**Other potentially relevant, related use cases**
The password protection on it's own works, if one DOES NOT hide the download.
The hide download on it's own works, if one DOES NOT protect it with a password also.
_hope, that helps to narrow down on the code section that causes this bug._

**Comment by kesselb** [comment]
Are you able to reproduce the problem with https://try.nextcloud.com? It seems to work there.

**Comment by sray** [comment]
@kesselb yes, it works there. which version is deployed there? which libcurl version is used there? I can't see that as the demo user. I would like to compare them with my production system.

**Comment by kesselb** [comment]
19.0.1 as per https://demo1.nextcloud.com/status.php. I don't know which curl version.

**Comment by sray** [comment]
I will try in the coming weeks then to see if an upgrade fixes the issue.
