### ISSUE TITLE
Status overview

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#20931]
# Summary

It would be nice if in your Nextcloud you could relay your own status to other users. So they know what you are doing.

# Details

A lot of modern communication platforms have statuses. Something like that would be useful for Nextcloud as well. That way you can signal that you are busy, on holiday, on site somewhere etc.

**To be extended**

## API

<details>

### DB:
1. New table: `user_status`
  - `id` (unsigned int, not null, autoincrement)
  - `user_id` (string, not null)
  - `status_type` (string, not null) => available, busy, unavailable
  - `status_icon` (string) => 1 unicode character
  - `message` (string) => custom message
  - `created_at` (unsigned int, not null) => unixtime 
  - `clear_at` (unsigned int) => unixtime

### API spec (OCS):
1. Expose user_status capability
Req: `GET /ocs/v1.php/cloud/capabilities`
Res: 
```
{
  "ocs": {
    ...
    "data": {
      ...
      "capabilities": {
        ...
        "user_status": {
          "enabled": true
        }
      }
    }
  }
}
```

2. Read all user-statuses
Req: `GET /ocs/v1.php/apps/user_status/api/v1/statuses`
Res: 
```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": null
    },
    "data": [
      {
        "userId": "admin",
        "statusType": "busy",
        "createdAt": 1589795903
      },
      {
        "userId": "user",
        "statusType": "holiday",
        "statusIcon": "🏝",
        "message": "On Vacation",
        "createdAt": 1589795903,
        "clearAt": 1589795904,
      }
    ]
  }
}
```

Allowed parameters:
- `limit`
- `offset`

3. Read status of specific user:
Req: `GET /ocs/v1.php/apps/user_status/api/v1/statuses/admin`
Res: 
```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": null
    },
    "data": {
      "userId": "admin",
      "statusType": "busy",
      "createdAt": 1589795903
    }
  }
}
```

3. Read status of authenticated user:
Req: `GET /ocs/v1.php/apps/user_status/api/v1/status`
Res: 
```
{
  "ocs": {
    "meta": {
      "status": "ok",
      "statuscode": 200,
      "message": null
    },
    "data": {
      "userId": "admin",
      "statusType": "busy",
      "createdAt": 1589795903
    }
  }
}
```

4. Set a new status:
Req: `PUT /ocs/v1.php/apps/user_status/api/v1/status`

5. Clear status:
Req: `DELETE /ocs/v1.php/apps/user_status/api/v1/status`

### Notes on privacy:
The APIs should respect the sharing privacy settings. (e.g. only allow to fetch status within own groups, etc.)
</details>

# Acceptance criteria

**To be extended.**

* [x] I want to be able to see my own status overlayed on my avatar in the top right
* [x] I want to be able to set my status
* [x] I want to have at least the available statuses
  - [x] Available
  - [x] Busy
  - [x] Holiday
* [ ] In places where appropiat (specify @georgehrke @jancborchardt) I want to see the status of other users on the system
* [x] I want to have an API that can be used by our mobile apps as well

**Comment by go2sh** [comment]
It would be nice to set a certain time span or end date for a status, e.g. "Holiday until 17.05.2020".

**Comment by georgehrke** [comment]
@go2s Yes, the plan is to have a "Clear status in 1 hour / 1 day / 1 week" feature.

**Comment by ChristophWurst** [comment]
> Holiday

Nitpick: this is a bit specific. How about *unavailable*, which covers vacation, out of office and being sick

**Comment by go2sh** [comment]
I think the reason, why someone is unavailable, provides a good value for communication, because you can express a grading. If someone is sick or on vaction, you might get no answere, but if someone is out of office, or doing homeoffice, you might get answer.

**Comment by ChristophWurst** [comment]
Fair enough, *out of office* does not mean *unavailable*. But *being sick*, *public holiday* and *vacation* can be seen as *unavailable* IMO :)

**Comment by georgehrke** [comment]
@go2sh You will have the ability to set a custom icon and custom message like `🌴 On Vacation` or `🤒 On sick leave`.

The status should really be on a lower level:
- 🟢 Available
- 🟠 Busy (e.g. in a meeting right now, but i will be available after)
- 🔴 Unavailable.

**Comment by go2sh** [comment]
Ah nice, that wasn't clear to me. :-)

**Comment by tobiasKaminsky** [comment]
So for mobile it would be great to have it in:
- propfind "nc:sharees" of files/folders, so that we can directly show it in file list
- search for users when sharing (should be "ocs/v2.php/apps/files_sharing/api/v1/sharees")

**Comment by georgehrke** [comment]
@rullzer @jancborchardt Should the user-status be visible on public pages as  well or should it only be visible to other users?

**Comment by rullzer** [comment]
> @rullzer @jancborchardt Should the user-status be visible on public pages as well or should it only be visible to other users?

O that is a good question.
For now I guess not. we already have privacy controls for the avatar. So we don't always (or by default not even) show it. So I guess for now status should not be shown on public pages. Since it can leak even more sensitive info.

**Comment by georgehrke** [comment]
Let's keep this open to track further improvements and client parity.

**Comment by georgehrke** [comment]
ToDo for a follow-up PR:
- [ ] inject user-status into prop-find for shares
- [ ] inject user-status into share search endpoint
- [ ] Changes to nextcloud/vue to reflect status in Multiselect (user-search) and Avatar
- [ ] Changes to sharing list in files
- [ ] The invisible icon is black on dark background when dark theme is used.

**Comment by georgehrke** [comment]
PHP API: https://github.com/nextcloud/server/pull/22106

**Comment by georgehrke** [comment]
Followup PR: #22109

**Comment by georgehrke** [comment]
Pull-Request in Nc/Vue:https://github.com/nextcloud/nextcloud-vue/pull/1259

**Comment by azul** [comment]
@georgehrke I'm [starting to use vuex in our app](https://gitlab.com/collectivecloud/wiki/-/merge_requests/67). At times i only see the user status data in the stores state:

![Bildschirmfoto von 2020-08-15 06-06-03](https://user-images.githubusercontent.com/102902/90304962-8339a600-debd-11ea-984f-edca2b22ae08.png)

(note the url of the wiki app and the mixed mutations: `wikis` from our app and then `loadStatusFromServer`)

How can we isolate the two stores from each other?

**Comment by georgehrke** [comment]
@azul That is an issue in the devtools, see https://github.com/vuejs/vue-devtools/issues/430.

Vuex itself will work correctly though

**Comment by azul** [comment]
@georgehrke You're right - it's just in the dev tools. The issue in my code was a different one. Thanks for the hints. :smile:

**Comment by georgehrke** [comment]
Follow-up Issues:
Indicator on Top Right Avatar: https://github.com/nextcloud/server/issues/22451
Client Implementation Tracking: https://github.com/nextcloud/server/issues/22452
