### ISSUE TITLE
Other information when updating the app

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#20959]
When updating the app for Nextcloud, the information window should read "Update for app_name". Currently, the Nextcloud instance update is not distinguished from the Nextcloud app update. For users, this is confusing because the description suggests that Nextcloud should be updated.

Update for the Nextcloud instance:
![obraz](https://user-images.githubusercontent.com/47037905/81857015-e257e980-9561-11ea-9296-d755e9027394.png)

App update for Nextcloud:
![obraz](https://user-images.githubusercontent.com/47037905/81857798-0f58cc00-9563-11ea-9172-28ae99fcc638.png)

**Comment by szaimen** [comment]
@Valdnet I don't understand this request. Please add a new one with better explanation or edit your first post. Afterwards feel free to reopen. Thanks! :)
