### ISSUE TITLE
Force use of app passwords to access API

### ISSUE THREAD

**Issue by mcassaniti** [nextcloud/server#20962]
**Is your feature request related to a problem? Please describe.**
If I use the remote API (such as accessing calendars or contacts) I can by default use my login password. This is allowed even if 2FA is enforced for a user.

**Describe the solution you'd like**
Have an administrative checkbox that forces the use of app passwords. This will at least need a basic explanation underneath, and probably a link to documentation to explain what the implications are.

This option should not have to depend on 2FA at all, so you could still force the use of app passwords even though the user has a single password they log in with and no 2FA.

**Describe alternatives you've considered**
Some applications do support OAuth2.0 and I've looked into them, but several unfortunately do not. This would certainly be better, but can't be universally used.

**Additional context**
Before Google started going OAuth2.0 everywhere I could use an app password for my IMAP client even though I had 2FA enabled. I did not have the option of using my normal password anymore as soon as 2FA was enabled.

**Comment by ColdSphinX** [comment]
There was an "app password" function, but since it's removal it broke thinks like syncing calendar using OpenSync on Android and such.

**Comment by mcassaniti** [comment]
I'm on Nextcloud 17 and I can see the app password details there. The [Nextcloud 18 documentation](https://docs.nextcloud.com/server/18/user_manual/session_management.html) calls these device specific passwords. I'm trying to make sure that all my devices use a device specific password if 2FA is configured and cannot use the normal password anymore.

The [documentation](https://docs.nextcloud.com/server/18/user_manual/user_2fa.html#using-client-applications-with-two-factor-authentication) also says "_Once you have enabled 2FA, your clients will no longer be able to connect with just your password unless they also have support for two-factor authentication. To solve this, you should generate device specific passwords for them_".

Does the behaviour actually match the documentation? If it does then this can be closed, but I'm not so convinced after I performed my initial setup, at least with Nextcloud 17.

**Comment by mcassaniti** [comment]
One thing I forgot to mention was that I only noticed these details in the documentation **after** raising this feature request.

**Comment by mcassaniti** [comment]
I have found that this does work as expected, it just seems to take some time to fully apply. My devices accessing the remote.php endpoint eventually stopped working without an app specific password which is what I was expecting.

**Comment by chris246** [comment]
This is also a feature I'm looking for to force users to login using the OIDC flow (with 2FA there).

Allowing access directly authenticating only via username+password undermines the security goals.
