### ISSUE TITLE
Readability / Distinction of currently selected element on right sidebar

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#2096]
Follow up of https://github.com/nextcloud/news/issues/56 😜 

Some people are experiencing problems with reading and distinct the elements on the right sidebar. They cannot distinct the currently selected and the other items because of the missing emphasis in form of a grey field under the selected item, which was removed with (...8.2 😅) 

Nextcloud News has reintroduced the grey on the sidebar already (see screenshot below) - but I am not happy to see this difference between server and news. I see @BernhardPosselt's point - so I think we should consider about solutions for this ;)
![](https://raw.githubusercontent.com/nextcloud/news/master/screenshots/1.png)

@BernhardPosselt @jancborchardt @nextcloud/designers @nextcloud/accessibility

**Comment by BernhardPosselt** [comment]
Linking issue https://github.com/owncloud/core/issues/20208

**Comment by jancborchardt** [comment]
Finally found a good solution: https://github.com/nextcloud/server/pull/3150 :)
