### ISSUE TITLE
Cannot disable dyslexia font

### ISSUE THREAD

**Issue by BenBo17** [nextcloud/server#20967]
Hello,
i enabled the dyslexia font because i wanted to try it.
Now the font is active but the checkbutton isn't checked.
When I check it, the font ist still enabled, when I uncheck it then it is disabled. But when I reload the page or klick on another menu (so the page is redirecting) the font is enabled again.
I don't know what to do. I cannot find the config location..

Nextcloud Version: 18.0.4
Server OS: Ubuntu 18.04.4 LTS

Thank you!
Ben

**Comment by jaythie** [comment]
Hello Ben,

I think this might be a browser related problem.

If you are using Chrome or Edge I would recommend reloading the page with CTRL + F5. Or Google how to do a "Hard Refresh" for your browser.

jaythie

**Comment by BenBo17** [comment]
Hi jaythie,
Thanks for your answer.
Unfortunately it isn’t. I did that before and it had no affect. I also restarted Apache and the Server, but it’s still there.. :(

**Comment by jaythie** [comment]
You're welcome. 

The only other thing i can think of would be disabling and reenabling the app "Accessibility". I think that could fix your problem. If it doesnt, maybe just leave it disabled unless you need it?

**Comment by BenBo17** [comment]
Yes that’s a good idea, I will try this. At the moment, my provider is doing some maintenance. But I will notify you, if that was working or not. :)

**Comment by BenBo17** [comment]
Hey, it worked! Thank you :)
