### ISSUE TITLE
Theming app (uloading wrong sized logo) breaks sending emails

### ISSUE THREAD

**Issue by Omaha2002** [nextcloud/server#20972]
### Steps to reproduce
1. theming app enabled
2. click send test email in basic testing
3. Send email says sending.... 

### Expected behaviour
Send email in basic settings should send email

![Aantekening 2020-05-14 120356](https://user-images.githubusercontent.com/3179748/81921544-14596200-95db-11ea-98b4-c24b98ee774c.jpg)

### Actual behaviour
Send email results in a red Sending... and some errors:

![Aantekening 2020-05-14 120314](https://user-images.githubusercontent.com/3179748/81921572-1d4a3380-95db-11ea-8b42-36c0a833330b.jpg)

error in php7.3-fpm.log:
[14-May-2020 08:13:21] WARNING: [pool www] child 21442 exited on signal 6 (SIGABRT - core dumped) after 13.959858 seconds from start

error in nextcloud.error.log (nginx):

2020/05/14 08:46:50 [error] 27064#27064: *1025 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 94.212.75.122, server: ********, request: "POST /settings/admin/mailtest HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.3-fpm.sock:", host: "******"

### Server configuration

**Operating system:**
Ubuntu 18.04.4
**Web server:**
nginx/1.17.10
**Database:**
Ver 15.1 Distrib 10.4.13-MariaDB
**PHP version:**
PHP 7.3.17
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 18.0.3
**Where did you install Nextcloud from:**
installation manual
`
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

- accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - announcementcenter: 3.7.0
  - apporder: 0.9.0
  - bookmarks: 3.0.13
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - dav: 1.14.0
  - deck: 1.0.0
  - drawio: 0.9.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_antivirus: 2.3.0
  - files_external: 1.9.0
  - files_fulltextsearch: 1.4.2
  - files_mindmap: 0.0.21
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - fulltextsearch: 1.4.1
  - fulltextsearch_elasticsearch: 1.5.1
  - groupfolders: 6.0.6
  - guests: 1.4.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.3.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - quota_warning: 1.7.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - side_menu: 1.6.1
  - sociallogin: 2.4.6
  - socialsharing_email: 2.0.0
  - spreed: 8.0.9
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - tasks: 0.13.0
  - text: 2.0.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - w2g2: 3.0.1
  - workflowengine: 2.0.0
</details>

**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "groningen.network"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "overwrite.cli.url": "https:\/\/groningen.network",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": "false",
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/var\/nc_data\/nextcloud.log",
        "loglevel": 0,
        "logtimezone": "Europe\/Amsterdam",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "\/var\/www\/nextcloud\/core\/skeleton",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "fulltextsearch",
            "files_readmemd",
            "drawio"
        ],
        "has_rebuilt_cache": true,
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***"
    }
}

### Client configuration

Any browser

**Operating system:**

Any OS

#### Nextcloud log (data/nextcloud.log)

Nextcloud doesn't throw any error in the log file

#### Browser log

throws a 502 bad gateway

**Comment by Omaha2002** [comment]
Update: Did some more research and found out it is caused by uploading a logo for the login page, apparently something is wrong with the dimensions:

![Uploading InkedAantekening 2020-05-15 092828_LI.jpg…]()

The specific logo that makes things crash:

![G logo](https://user-images.githubusercontent.com/3179748/82023516-af5f4400-968e-11ea-8898-d3cde3684b1b.png)

**Comment by Omaha2002** [comment]
Apparently it's a nasty logo, problem still persistent in 19.0.0 RC2.

original logo is 2.6MB in size, resizes to 300x300 makes it 8K, still I can imagine someone uploads a big size logo accidentely, there should be a warning of some sort "logo too big"..

**Comment by szaimen** [comment]
I'd say this is a problem of the image that you've tried to use. Even Github has problems showing that and just stops for a second when loading/showing the image. Also since not many users seem to have this problem, I am closing this issue for now.
