### ISSUE TITLE
Adding OneDrive external storage support

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/server#2097]
Could it be possible to implement the ability to connect a users OneDrive with thier cloud?
Some of my users have a real big storage availability and would like to use them with thier nextcloud client.
Would that be possible?

**Comment by MariusBluem** [comment]
APIs are there - If somebody wants to step in 🙈 https://dev.onedrive.com

**Comment by mightyBroccoli** [comment]
Are there any news on this? I would love this feature I hope somebody is able to implement that.

**Comment by psychowood** [comment]
Fyi, WebDAV integration is not working, even if theoretically supported by OneDrive (probably something related to a non-complete WebDAV support from OD, nextCloud throws a "Method not supported" error).

**Comment by MorrisJobke** [comment]
cc @icewind1991 @rullzer I guess this should be done as app, right?

**Comment by rullzer** [comment]
Yes app!

**Comment by xXSTrikeXx** [comment]
why its closed? :0

**Comment by craige1** [comment]
Please dont close

**Comment by MariusBluem** [comment]
We closed this issue since this is something somebody can implement as an app :) This is nothing we want and will have in the server core...

**Comment by craige1** [comment]
Oh. 
How much work do you think this would actually be?
Could an amateur coder give it a shot, or should it be left to the skilled?

**Comment by e-alfred** [comment]
@craige1 You could use this app as a starting point to implement support for different external storage services:

https://github.com/icewind1991/files_external_dropbox

**Comment by Upperholme** [comment]
> This is nothing we want and will have in the server core...

Whilst I can understand the rationale for not having OneDrive support in the server core, and the argument for it to be an app, I am surprised that support for OneDrive is not seen as being a strategic priority for NextCloud in terms of enabling widespread adoption.

**Comment by hifihedgehog** [comment]
This is absurd. They could easily add OneDrive support via, minimally, WebDAV. I know of several programs and web apps off the top of my head that do this. Just use https://d.docs.live.net/https://d.docs.live.net/1234567890ABCDEF and then your Microsoft account username and an app password. This isn't rocket science and this is highly requested.

**Comment by hevelius** [comment]
Hi everyone,

if you are interested I am working on an app to integrate onedrive in nextcloud.
Now beta-unstable with some performance issues.

https://github.com/hevelius/files_external_onedrive
