### ISSUE TITLE
File sharing with link: password policy creates unfriendly error message for share passwords

### ISSUE THREAD

**Issue by lightonflux** [nextcloud/server#20973]
### Steps to reproduce
1. Set password policy
2. Create share link
3. Set custom password that does not meet policy 
4. Watch for unfriendly error message "Error updating share"

### Expected behaviour
Give user feedback that a password policy is in place and why the password is not accepted

### Actual behaviour
An error message is displayed: "error updating share".
This message does not help users at all. And it is also not translated. Also the auto generated password might not meet the policy neither. (See #8834) There is also an issue about uncoupling share link passwords from the policy: #18180 

![nextcloud-password-policy-bug](https://user-images.githubusercontent.com/1377943/81925676-1de5c880-95e1-11ea-8e01-d1e3fe68cec4.gif)

### Server configuration

**Nextcloud version:** Nextcloud 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from several other 18 minor version.

**Where did you install Nextcloud from:** Manual from the archive provided on the nextcloud website.

**Web browser:** Firefox 76.0.1

**Comment by kesselb** [comment]
Looks similar to https://github.com/nextcloud/server/issues/19525
