### ISSUE TITLE
Files Comments "New comments available - Icon on Files and Folders" and a counter of new unread Comments

### ISSUE THREAD

**Issue by apg1980** [nextcloud/server#20971]
Hello,

this is not an Issue but an improvement.
Is it possible to add a Icon if comments are added to a file or folder (it would be great to see a count for unread new comments as well).
Right now there is no hint for that a file or folder has comments from other users.
I hope i have explained it right.

Thank you and best regards.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by szaimen** [comment]
I think this works in the meantime
![image](https://user-images.githubusercontent.com/42591237/120470029-5ea6b000-c3a3-11eb-84c4-91ee71565b77.png)
