### ISSUE TITLE
Backup And Restore Feature While First Setup

### ISSUE THREAD

**Issue by IzumiSena** [nextcloud/server#20982]
Hello i use nextcloud in my home server and i wanted to change my server os so i try to test with my backup data config and database in a new server os inside virtual box and what results i got is (no matter what i do or which os i choose i cant restore nextcloud in new server all nextcloud docs guide i followed) but if i try to fresh start it work in all different os,,,,

so i think you guys at least consider to add a backup and restore feature that can help admin and can backup all extra apps, data, config, database from inside nextcloud admin panel and when it comes to restore add a restore page in first time setup page so admin can just select old backup files and restore it in nextcloud server (NOT NEXTCLOUD SNAP)
thanks

**Comment by Nils160988** [comment]
Related to https://github.com/nextcloud/server/issues/17328

**Comment by kesselb** [comment]
Currently there are no plans to implement such a feature. Thus I will close this ticket for now.
