### ISSUE TITLE
Help me, MariaDB Crashes and I dont know why.

### ISSUE THREAD

**Issue by Emporea** [nextcloud/server#20984]
I use Nextcloud(18 currently). Everything was working fine until this day when i got this message when accessing my cloud via the webbrowser.

`Internal Server Error 
The server encountered an internal error and was unable to complete your request.
Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
More details can be found in the server log.`

I am using docker, or more specific docker compose for almost 2 years now. fpm alpine, splitted into 5 parts: mariadb, redis, app, web, and cron.

The mariadb one has an error currently.

![image](https://user-images.githubusercontent.com/21969523/81988474-d3de0080-963b-11ea-8671-877e78da4fe0.png)

this is in the docker logs. this sounds way too complicated for me and i have no clue.

![image](https://user-images.githubusercontent.com/21969523/81988755-47800d80-963c-11ea-970c-ee93b01a6692.png)

 I have not made any changes to my system. I need my system working. It is in productive use.

let me know if you know anything related to this problem or what i should look for to get this fixed. Thank you.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by Emporea** [comment]
I have not changed anything to the setup. As I said i am using docker for almost 2 years, with some changes made to the docker-compose.yml file over the time. But this issue just appeared and i havent changed anything for about 3 or 4 months.



version: '3'

services:
  nextcloud_db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=
    env_file:
      - db.env

  nextcloud_redis:
    image: redis:alpine
    restart: always

  nextcloud_app:
    build: ./app
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db
      - REDIS_HOST=nextcloud_redis
    env_file:
      - db.env
    depends_on:
      - nextcloud_db
      - nextcloud_redis

  nextcloud_web:
    build: ./web
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=
      - LETSENCRYPT_HOST=
    depends_on:
      - nextcloud_app

  nextcloud_cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - nextcloud_db
      - nextcloud_redis

volumes:
  nextcloud_db:
  nextcloud:




Is it possible, that it has something to do with a big database? I am using Nextcloud News and do not purge any items because i use them for machine learning data processing. So the database might be a little big.

**Comment by kesselb** [comment]
As explained in the issue template. GitHub is not a support channel. I have no idea what is wrong with your setup. Your screenshot show some warnings from MariaDB. That's probably something to look into. Feel free to come back if it turns out as bug in Nextcloud.

**Comment by acsfer** [comment]
See also
![image](https://user-images.githubusercontent.com/12234510/82123098-c178d980-9797-11ea-98ce-0387c192568c.png)
