### ISSUE TITLE
Ability to scan portions of the filesystem from the GUI (occ files:scan)

### ISSUE THREAD

**Issue by NoMoreNicksLeft** [nextcloud/server#20997]
It would be convenient and simple to be able to click on the options icon for a folder and select "OCC scan". This is difficult considering that many of us now run NC directly from a docker container, or might need to do so remotely without shell access.

It should definitely be a per-folder option, so that a full scan isn't necessary. A progress indicator might be nice, but since any new content it finds would be hidden (you've not drilled down into that directory yet, or you'd not be able to click scan), a refresh probably isn't necessary.

Is this possible? Are there security implications (would be an admin-only thing, obviously)? Should it be an app?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
