### ISSUE TITLE
Cannot modify header information Since NC19 RC2

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#21000]
Error | PHP | Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php#680
-- | -- | --

**Comment by Nils160988** [comment]
Can you use the issue template to make it easier to debug your issue?

**Comment by axheli** [comment]
I'm sorry about that.

Running Ubuntu 18.04 Server
PHP 7.3
apache2

**Comment by axheli** [comment]
What is needed

**Comment by Derkades** [comment]
I got a very similar error today:
```
Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#683
```

Nextcloud 19.0.3, PHP 7.4 (fpm with nginx)

**Comment by Quiver92** [comment]
Hi! The same error:
Error: Cannot modify header information - headers already sent by (output started at /var/www/html/3rdparty/sabre/http/lib/Sapi.php:132) at /var/www/html/apps/dav/lib/Connector/Sabre/File.php#691

PHP: 7.4.11
DB: mysql 10.5.6
Nextcloud 20.0.2

**Comment by cbartondock** [comment]
I have exactly the same error - this should not be closed.

**Comment by hex-m** [comment]
possible duplicate: https://github.com/nextcloud/server/issues/22509
