### ISSUE TITLE
IE 11 is detected as IE 7 in session settings

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2101]

**Comment by nickvergessen** [comment]
Can you post the entry from the database, so people without IE can fake this?

**Comment by MorrisJobke** [comment]
> Can you post the entry from the database, so people without IE can fake this?

https://modern.ie 🙈  I will provide you with the user agent.

**Comment by MorrisJobke** [comment]
`Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko`

**Comment by MorrisJobke** [comment]
Fix is in #2108
