### ISSUE TITLE
Exception: The bucket will not be created because the name is not dns compatible.

### ISSUE THREAD

**Issue by alicehsiao** [nextcloud/server#21022]
While trying to create an Amazon S3 external storage, this is the error that I get upon trying multiple bucket names (which ARE dns compatible according to Amazon - no periods).

**Comment by IIPoliII** [comment]
Hey, how were you able to correct this?

**Comment by StefanArts** [comment]
+1

**Comment by aherbjornsen** [comment]
This problem still exist. The GUI needs a period in the bucket name, which is not an allowed character in Backblaze B2.
Created the bucket with occ instead, and it worked fine.
