### ISSUE TITLE
Missing space by "add to project" button

### ISSUE THREAD

**Issue by erth5** [nextcloud/server#21027]
### Steps to reproduce
— I use German language
— I use Breeze Theme

select item -> share
see at "add to project"

### Expected behaviour
With theme:
button in dark color, like blue, text in white

without theme:
more space below button, like
margin-bottom: +1em;

### Actual behaviour
With theme:
button text not visible. grey text and white background

without theme:
button overlap description text which stand below

## Server configuration detail

**Operating system:** Linux 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64

**Webserver:** Apache (apache2handler)

**Database:** mysql 5.7.30

**PHP version:** 

7.2.24-0ubuntu0.18.04.4
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, apcu, mysqlnd, PDO, xml, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, geoip, gettext, gmp, gnupg, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** saled instance from companie "ocloud.de"

<details><summary>Signing status</summary>

Integrity checker has been disabled. Integrity cannot be verified.
</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - apporder: 0.9.0
 - audioplayer: 2.10.0
 - audioplayer_editor: 0.2.2
 - bruteforcesettings: 1.6.0
 - calendar: 2.0.3
 - checksum: 0.4.4
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - contacts: 3.3.0
 - dav: 1.14.0
 - deck: 1.0.1
 - drawio: 0.9.5
 - encryption: 2.6.0
 - end_to_end_encryption: 1.4.0
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - gpxedit: 0.0.13
 - gpxmotion: 0.0.11
 - gpxpod: 4.2.1
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.3.4
 - maps: 0.1.6
 - metadata: 0.11.1
 - music: 0.14.1
 - news: 14.1.7
 - nextcloud_announcements: 1.7.0
 - notes: 3.3.1
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - ocloudadmin: 12.0.0
 - ocr: 6.0.41
 - onlyoffice: 4.1.4
 - password_policy: 1.8.0
 - photos: 1.0.0
 - previewgenerator: 2.3.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - radio: 0.6.6
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - systemtags: 1.8.0
 - talk_simple_poll: 1.1.1
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - video_converter: 0.1.4
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - breezedark
 - files_external
 - privacy
 - support
 - survey_client
 - updatenotification
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "matthe.ocloud.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "https:\/\/matthe.ocloud.de",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "integrity.check.disabled": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "enable_previews": true,
    "loglevel": "4",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtptimeout": "30",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "simpleSignUpLink.shown": false,
    "versions_retention_obligation": "10,30",
    "trashbin_retention_obligation": "10,30",
    "activity_expire_days": "30",
    "upgrade.disable-web": true,
    "forcessl": true,
    "onlyoffice": {
        "verify_peer_off": true
    },
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

**********************************************************************Loading stuff:

Insert your browser log here, this could for example include:

Navigating away, leaving conversation FilesSidebarTabApp.vue:149
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). blocker.js:232:46
Die Ressource von "https://matthe.ocloud.de/apps/maps/js/filetypes.js?v=c5ed5039-18" wurde wegen eines MIME-Typ-Konfliktes ("text/html") blockiert (X-Content-Type-Options: nosniff).
files
Laden fehlgeschlagen für das <script> mit der Quelle "https://matthe.ocloud.de/apps/maps/js/filetypes.js?v=c5ed5039-18". files:95:1
JQMIGRATE: Migrate is installed, version 1.4.1 jquery-migrate.min.js:2:551
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Notifications permissions denied App.vue:248
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 4 globals.js:66:15
OCA.Files.Sidebar initialized Sidebar.js:37:10
Handlebars is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
Proxying an event bus of version 1.1.2 with 0.2.1 ProxyBus.js:65:14
OCA.Sharing.ShareSearch initialized ShareSearch.js:33:10
OCA.Sharing.ExternalLinkActions initialized ExternalLinkActions.js:33:10
OCA.Viewer initialized Viewer.js:41:10
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. addStylesClient.js:220:17
New search handler registered search.js:67:12
Clipboard is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
registerTabView is deprecated! It will be removed in nextcloud 20. merged-index.js:7511:12
Legacy tabs are deprecated! They will be removed in nextcloud 20. Tab.js:49:11
registerTabView is deprecated! It will be removed in nextcloud 20. merged-index.js:7511:12
Legacy tabs are deprecated! They will be removed in nextcloud 20. Tab.js:49:11
registerDetailView is deprecated! It will be removed in nextcloud 20. merged-index.js:7522:12
registerTabView is deprecated! It will be removed in nextcloud 20. merged-index.js:7511:12
Legacy tabs are deprecated! They will be removed in nextcloud 20. Tab.js:49:11
registerTabView is deprecated! It will be removed in nextcloud 20. merged-index.js:7511:12
Legacy tabs are deprecated! They will be removed in nextcloud 20. Tab.js:49:11
registerTabView is deprecated! It will be removed in nextcloud 20. merged-index.js:7511:12
Legacy tabs are deprecated! They will be removed in nextcloud 20. Tab.js:49:11

**********************************************************************open share menue:
OCA.Ocr initialized App.ts:22:12
The humanFileSize library is deprecated! It will be removed in nextcloud 19. 21 globals.js:66:15
showDetailsView is deprecated! Use OCA.Files.Sidebar.activeTab. It will be removed in nextcloud 20. merged-index.js:4464:12
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
The escapeHTML library is deprecated! It will be removed in nextcloud 19. 4 globals.js:66:15
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
The select2 library is deprecated! It will be removed in nextcloud 19. 2 globals.js:66:15
recommendations 
Array [ {…}, {…} ]
</details>

![overlap](https://user-images.githubusercontent.com/9325448/82189251-5d692900-98ef-11ea-9622-fae28e7623bd.png)
![text not visible in breeze Theme](https://user-images.githubusercontent.com/9325448/82189255-5e01bf80-98ef-11ea-8482-767d2496f97d.png)
![overlap](https://user-images.githubusercontent.com/9325448/82189371-90132180-98ef-11ea-9ffe-0b6f541343fc.png)
![text not visible in breeze Theme](https://user-images.githubusercontent.com/9325448/82189372-90abb800-98ef-11ea-9e39-3825b21ee2cc.png)

**Comment by kesselb** [comment]
Is the repository for breeze theme: https://github.com/mwalbeck/nextcloud-breeze-dark

![image](https://user-images.githubusercontent.com/3902676/82211460-273ca100-9911-11ea-94ee-64782f826957.png)

Looks good to me with Nextcloud 19.
