### ISSUE TITLE
Collabora Issue ** Files cannot be saved 

### ISSUE THREAD

**Issue by telien** [nextcloud/server#21038]
Dear all,

I experienced an issue with collabora. Files cannot be saved due to some issue. 

I am currently running the following setup:
Nextcloud: 18.0.4
Collabora App: 3.6.0
PHP: 7.3.18

Please find the logfiles from docker below:
 `wsd-00008-00116 2020-05-18 17:40:03.719050 [ docbroker_00a ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://cloud.myhomepage.com/index.php/apps/richdocuments/wopi/files/493499_ocbdyjm76any/contents?access_token=gaEND3DSTTgtSh2NXHFlfplFNkYFC2l6&access_token_ttl=0]. Error: | wsd/Storage.cpp:1145
wsd-00008-00116 2020-05-18 17:40:03.720776 [ docbroker_00a ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/493499_ocbdyjm76any] to URI [https://cloud. myhomepage.com/index.php/apps/richdocuments/wopi/files/493499_ocbdyjm76any?access_token=gaEND3DSTTgtSh2NXHFlfplFNkYFC2l6&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1106
wsd-00008-00116 2020-05-18 17:40:04.404433 [ docbroker_00a ] ERR  Unexpected response to WOPI::PutFile : 500Cannot save file to WOPI storage uri [https://cloud. myhomepage.com/index.php/apps/richdocuments/wopi/files/493499_ocbdyjm76any/contents?access_token=gaEND3DSTTgtSh2NXHFlfplFNkYFC2l6&access_token_ttl=0]. Error: | wsd/Storage.cpp:1145
wsd-00008-00116 2020-05-18 17:40:04.406049 [ docbroker_00a ] ERR  Failed to save docKey [/index.php/apps/richdocuments/wopi/files/493499_ocbdyjm76any] to URI [https://cloud. myhomepage.com/index.php/apps/richdocuments/wopi/files/493499_ocbdyjm76any?access_token=gaEND3DSTTgtSh2NXHFlfplFNkYFC2l6&access_token_ttl=0]. Notifying client.| wsd/DocumentBroker.cpp:1106
`

Can anyone help?

**Comment by kesselb** [comment]
Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com

https://github.com/nextcloud/richdocuments is the repository for the richdocuments app. If you found a bug feel free to report it there.
