### ISSUE TITLE
More contextually relevant button labels

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2104]
For example in the case of this modal:
![administration_-_nextcloud_-_2016-10-31_12 15 50](https://cloud.githubusercontent.com/assets/213943/19852646/ca6474fc-9f64-11e6-95ff-63d24ac14b41.png)

The button labels »Yes« and »No« are pretty stupid. Instead the »Yes« button should say »Yes, add trusted domain«.

@nickvergessen since you said the JS only has these options, we should make it possible to pass custom labels which make more sense than a stupid »Yes«, »No« and »OK«.

cc @nextcloud/designers @nextcloud/javascript

**Comment by skjnldsv** [comment]
Also fix the translation? "Are you really sure that you want to add..."?

**Comment by comradekingu** [comment]
To me it seems odd to repeat the notion of adding.

**Comment by jancborchardt** [comment]
Well, still the button should not say only "Yes" and the content could be a tad more verbose:

> Add https://… as trusted domain?

> Yes, trust this domain

**Comment by nickvergessen** [comment]
The button description is hackable atm:
https://github.com/nextcloud/server/blob/086ce709f7368af41543178a3de5d3c561b5ddb7/core/js/js.js#L1706-L1713

But yeah maybe some JS expert rewrites our Dialogs into something that also allows to provide the button labels directly.

**Comment by szaimen** [comment]
I think this is already implemented at many places -> closing.
