### ISSUE TITLE
serverBackground should only be set if it is a custom background or default hub

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#21046]
serverBackground is exposed via Capability: background

Cases:
- default blue
- no background
--> serverBackground should return NC Hub icons

- color manually set to orange
- no background
--> serverBackground should nothing

- color manually set to green
- background set
--> serverBackground should return manually set background (no hub icons)

@jancborchardt @juliushaertl maybe? 💙

**Comment by juliushaertl** [comment]
Makes sense. https://github.com/juliushaertl/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/apps/theming/lib/Capabilities.php#L82-L85 is the relevant code part.
