### ISSUE TITLE
Shared link for onlyoffice files does not work properly 

### ISSUE THREAD

**Issue by ratzdi** [nextcloud/server#21043]
### Steps to reproduce
1. create an only office document
2. create a shared link
3. open shared link without credentials

### Expected behaviour
Download page of nextcloud with the link to shared document should open.

### Actual behaviour
Nextcloud shows a page with error text:

Error
cURL error 3: (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

### Server configuration

**Operating system:**
nextcloudpi
Linux 7d73842c82db 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 GNU/Linux

**Web server:**
apache
**Database:**
mariadb  Ver 15.1 Distrib 10.3.22-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:**
PHP 7.3.14-1~deb10u1 (cli) (built: Feb 16 2020 15:07:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.14, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.14-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 17

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - bookmarks: 3.0.13
  - breezedark: 18.0.16
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - cms_pico: 1.0.6
  - comments: 1.8.0
  - contacts: 3.3.0
  - cookbook: 0.6.5
  - dav: 1.14.0
  - deck: 1.0.1
  - documentserver_community: 0.1.5
  - drawio: 0.9.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_markdown: 2.2.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - hsts: 0.4.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.6
  - music: 0.14.1
  - news: 14.1.7
  - nextcloud_announcements: 1.7.0
  - nextcloudpi: 0.0.1
  - notes: 3.3.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.1.4
  - password_policy: 1.8.0
  - passwords: 2020.5.0
  - photos: 1.0.0
  - polls: 1.4.3
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - richdocuments: 3.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.0
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - twofactor_u2f: 5.1.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - weather: 1.7.2
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - previewgenerator.orig
  - user_ldap

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder


Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": {
            "1": "172.17.0.2",
            "20": "***REMOVED SENSITIVE VALUE***",
            "6": "***REMOVED SENSITIVE VALUE***"
        },
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "tempdirectory": "\/var\/www\/nextcloud\/data\/tmp",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "loglevel": "2",
        "log_type": "file",
        "maintenance": true,
        "mail_sendmailmode": "pipe",
        "jpeg_quality": "60",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "htaccess.RewriteBase": "\/",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "business"
        ],
        "twofactor_enforced_excluded_groups": [],
        "data-fingerprint": "58593289704d82d59cea0e07b87cf2df",
        "updater.release.channel": "stable",
        "theme": "",
        "app_install_overwrite": [
            "radio"
        ]
    }
}

</details>

**Comment by kesselb** [comment]
Logs?

**Comment by applesoff** [comment]
I have the same issue as this person before. i see this in my logs when trying to share an external link. Any idea how to fix it?

2024/06/17 00:57:22 [error] 7870#7870: *108 open() "/var/www/onlyoffice/documentserver/web-apps/apps/documenteditor/main/[object HTMLCollection]" failed (2: No such file or directory), client: 172.16.144.6, server: , request: "GET /8.0.1-31/web-apps/apps/documenteditor/main/[object%20HTMLCollection] HTTP/1.1", host: "office.pendra.dev", referrer: "https://office.pendra.dev/ds-vpath/8.0.1-31/web-apps/apps/documenteditor/main/index.html?_dc=8.0.1-31&lang=en-US&frameEditorId=iframeEditor&isForm=false&parentOrigin=https://office.pendra.dev&uitheme=default-dark&fileType=docx"
