### ISSUE TITLE
nvalidArgumentException: Migration step 'OCA\Files\Migration\Version11301Date20191205150729' is unknown

### ISSUE THREAD

**Issue by JanaFischinger** [nextcloud/server#21040]
Got:

nvalidArgumentException: Migration step 'OCA\Files\Migration\Version11301Date20191205150729' is unknown

Try to upgrade from 16.0.10 to 17.0.0

`php ./occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <files> ...
InvalidArgumentException: Migration step 'OCA\Files\Migration\Version11301Date20191205150729' is unknown
Update failed
Maintenance mode is kept active
Reset log level
`

**Comment by zoernert** [comment]
Problem occures if you have multiple versions in the same folder. 

Solution: Remove (after Backup) you 'apps/' folder then unzip installation package again.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
