### ISSUE TITLE
preconfigured quota presets for group admins

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#21045]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
#### Situation
- Group admins are able able to set quotas for the users they administrate.
- They can either type in a custom value or select from a drop down menu.
![image](https://user-images.githubusercontent.com/1804221/82305331-c919c780-99bd-11ea-8526-4ec537c98f72.png)
- There is no limitation to the settable quota values

#### Problem
- Often there are corporate quota guidelines to be followed.
- Unlimited quota may not be allowed after all
- The built-in suggestions may not reflect the corporate presets

**Describe the solution you'd like**
- The choosable presets should be configurable.
- Entering of free custom values should be allowable or deniable.
- When entering of free custom values is allowed, a maximum settable quota needs to be configured.
- Configuration should be either available on the admin UI or at least in the config.php

**Comment by bpcurse** [comment]
see also #18326

**Comment by diemelone** [comment]
Are there any updates since last year?

**Comment by wiswedel** [comment]
> Are there any updates since last year?

stay tuned for a life sign on this topic within the next 4 weeks please

**Comment by szaimen** [comment]
@wiswedel some update here?

**Comment by Pytal** [comment]
@eneiluj does https://github.com/nextcloud/server/pull/28009 close this?

**Comment by szaimen** [comment]
Implemented with #28009

**Comment by Shar1988** [comment]
👍
