### ISSUE TITLE
[Feature] Add an "All users" core group

### ISSUE THREAD

**Issue by loxK** [nextcloud/server#21051]
There is an admin core group. I am in the need of an "All Users" group containing all users.

The use case is some Group Folders shared to all users in read access but to another group in write access.

**Comment by Nils160988** [comment]
You might have a look at this (https://apps.nextcloud.com/apps/group_everyone) app. Does it do what you want?
But be aware: This app kind of breaks feature like "limit sharing to their own group" because all users automatically share a group then, so I had to disable it.

**Comment by bpcurse** [comment]
@loxK We use the everyone group app for this: https://apps.nextcloud.com/apps/group_everyone

But I agree, it would be better to have it implemented in core.

**Comment by rullzer** [comment]
As said use the app. It does what you want (create a group with everyone). Implementing everything in core is not something we should aim for.
