### ISSUE TITLE
Clear the cache if switching between light and dark mode

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#21069]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
While switching between light and dark mode, I noticed on NC18.0.4 that on chromium based browsers some files and pictures get so havily cached, that I have to manually clear the cache so that the dark mode/light mode works as expected after switching

**Describe the solution you'd like**
Would be really nice if Nextcloud could clear the cache after switching between light and dark mode

**Comment by paulijar** [comment]
At least the variable `OCA.Accessibility.theme` is not updated after changing between light/dark modes, until the user makes a manual refresh.

On Firefox, it is enough to hit the 'Refresh' button to fix the situation, but on Chrome/Chromium, the default behavior of the 'Refresh' button is to make a "milder refresh". There, the situation can be fixed be making the "forced refresh" by holding shift while pressing the 'Refresh' button. On the mobile Chrome, on the other hand, I haven't figured out any other way to do this except manually clearing the cached data via the History view.

**Comment by szaimen** [comment]
I just tested again and couldn't reproduce the issue on NC21.0.1 anymore. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
