### ISSUE TITLE
rich-workspace icon-loading appears after upgrade 17.0.2 to 18.0.4

### ISSUE THREAD

**Issue by nazrimazlan** [nextcloud/server#21064]
Hi team,
The rich-workspace icon-loading appears in the workspace.
So now how to remove it, did I need to edit the php files?
![image](https://user-images.githubusercontent.com/13063492/82532578-438c4800-9b74-11ea-9b6b-4d3c83787c7f.png)

![image](https://user-images.githubusercontent.com/13063492/82538646-a387ec00-9b7e-11ea-8af7-bfed845c9f40.png)

![image](https://user-images.githubusercontent.com/13063492/82538699-b69abc00-9b7e-11ea-8de4-65f01b3f83eb.png)

BR,
Nazri

**Comment by kesselb** [comment]
https://github.com/nextcloud/text/issues/820

GitHub is not a support channel. The Issue Template is mandatory to report a bug. Please use it the next time.

**Comment by nazrimazlan** [comment]
Noted with thanks.
