### ISSUE TITLE
Upgrade experience: confusing message about disabled incompatible apps

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#21066]
### Summary

The upgrade process shows confusing messages about disablig apps while not disablig anything after all.

### Detailed description

During the upgrade process, there's a screen saying "These incompatible apps will be disabled".

Example (no idea why it's suddenly German, sorry):
![willbeDeactivated](https://user-images.githubusercontent.com/1804221/82642611-7d119180-9c0e-11ea-8cdf-300d09cb4bb1.png)

Those listed apps are in fact enabled and don't have a compatible version for the server upgrade target version.

After running the server upgrade, there is another confirmation screen that there were (in this case three) apps that have been disabled:

![after](https://user-images.githubusercontent.com/1804221/82642756-b3e7a780-9c0e-11ea-8df2-9b8464892eac.png)

However, in fact after the upgrade, when checking back in the app store, the apps haven't been disabled after all:

![stillEnabled](https://user-images.githubusercontent.com/1804221/82642814-cb269500-9c0e-11ea-9262-61e7e93495b3.png)

#### Side note

This dialog has been confusing me for ages, so it also applies for a bunch of versions <19

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.2? Does this needs to be fixed in the server or the updater?

**Comment by tuxick** [comment]
This is still relevant, upgrading to 24 gave me:

These incompatible apps will be disabled:

    Group folders (groupfolders)
    Impersonate (impersonate)

**Comment by kb173** [comment]
Can confirm, had the same issue with apps like "Calendar" when upgrading to Nextcloud 24 via NextcloudPi. Thankfully the message was indeed wrong and the apps stayed enabled.

**Comment by SjoerdV** [comment]
same issue going from 27 to 28.
Only the metadata app was actually disabled, rest were fine. Had me scared there....

The following apps have been disabled: 
deck (incompatible), 
drawio (incompatible), 
external (incompatible), 
files_accesscontrol (incompatible), 
files_automatedtagging (incompatible), 
files_retention (incompatible), 
files_rightclick (incompatible), 
flow_notifications (incompatible), 
forms (incompatible), 
groupfolders (incompatible), 
guests (incompatible), 
metadata (incompatible), 
spreed (incompatible), 
workflow_pdf_converter (incompatible), 
workflow_script (incompatible)
