### ISSUE TITLE
Use GitHub Discussions when available

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#21072]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I'm always frustrated when the issue tracker is used for meta discussions and questions. Also keeping track of enhancement requests is a bit inconvenient because there is no way to sort issues by :+1: 

**Describe the solution you'd like**

https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

I would suggest to make issues with "enhancement" and  "0. need triage" a discussion. It seems that a transition issue to discussion is possible but not the other way around (because discussion to issue would loose information). 

We should consider to disable "help" as category and send people to https://help.nextcloud.com for questions / help.

**Describe alternatives you've considered**

Move enhancement requests to https://help.nextcloud.com similar to https://community.bitwarden.com/c/feature-requests/5. Could work but some migration script would be required to copy the issues and update the references. Sounds like a nightmare to me.

**Additional context**

See it in action: https://github.com/zeit/next.js/discussions

**Comment by szaimen** [comment]
This is now available in beta, afaik.

**Comment by szaimen** [comment]
So do we wana do this then? I am under the impression that we've dediced not to do this.
cc @nextcloud/server

**Comment by skjnldsv** [comment]
We could open discussions for meta and tech questions only sure :)
I would be up for that. Thoughts @juliushaertl @blizzz

Also cc @tobiasKaminsky & @jancborchardt since you use meta issues quite often

**Comment by kesselb** [comment]
I think @nickvergessen had some points why help.nc.com is better.

**Comment by tobiasKaminsky** [comment]
> Also cc @tobiasKaminsky & @jancborchardt since you use meta issues quite often

I am not for opening up another area where we have issues/enhancements stored in.
Current approach with meta-issues is fine, I think:
In meta issue we discuss it in general
in each repo there is a corresponding issue where the technical discussion per platform can be done

I do not see in which parts the GH discussion system might benefit.
Only in one step before, to discuss if an enhancement/idea is something we want to do, but again this is something we already do in our regular issues …
