### ISSUE TITLE
OnlyOffice doesn't update the file

### ISSUE THREAD

**Issue by olli0815** [nextcloud/server#21087]
### Steps to reproduce
1. create an spreadsheed
2. put in some data
3. leave the sheet
3.1 the original file will not be upadted / changed after closing
3.2 even changing mode "collaboration mode to formal" & save doesn't effect
4. data in sheet may have changed correctly when reopeneing
5. but file attributes doesn't notice any changes
6. sync of the unchanged file will not take place

### Expected behaviour
when changing the file (here an spreadsheet) file attributes should reflect changes at least after closing / leaving the file (via OO in place or OO-Desktopeditor)

### Actual behaviour
see above

### Server configuration

**Operating system:**
NC Docker (apache)

**Web server:**
apache
**Database:**
mysql
**PHP version:**
7.something
**Nextcloud version:** (see Nextcloud admin page)
NC 18.4
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**
git
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
https://github.com/nextcloud/documentserver_community is the repository to report such a problem. Probably there is already a issue.
