### ISSUE TITLE
Bad endpoint URL with S3

### ISSUE THREAD

**Issue by babeuloula** [nextcloud/server#21081]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create an account to [scaleway](scaleway.com/)
2. Follow this [guide](https://www.scaleway.com/en/docs/install-and-configure-nextcloud-object-storage/)
3. You will have an error

### Expected behaviour

Use https://s3.fr-par.scw.cloud/my-nextcloud-storage-bucket

### Actual behaviour

Use https://my-nextcloud-storage-bucket.s3.fr-par.scw.cloud/

### Server configuration

**Operating system:**

Alpine

**Web server:**

Docker image

**Database:**

SQLite

**PHP version:**

From nextcloud 18 docker fpm-alpine

**Nextcloud version:** (see Nextcloud admin page)

18

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh install

**Where did you install Nextcloud from:**

Local before production

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"EdxYu1s9FP4b5ps7v9tO","level":3,"time":"May 24, 2020 12:36:23","remoteAddr":"172.31.0.1","user":"test","app":"objectstore","method":"GET","url":"/apps/files/","message":{"Exception":"Exception","Message":"Creation of bucket \"my-nextcloud-storage-bucket\" failed. Error executing \"CreateBucket\" on \"https://my-nextcloud-storage-bucket.s3.fr-par.scw.cloud:433/\"; AWS HTTP error: cURL error 7: Failed to connect to my-nextcloud-storage-bucket.s3.fr-par.scw.cloud port 433: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

I think it could be nice to update flysystem to the latest version.

**Comment by babeuloula** [comment]
If you want, you can check my repo with your installation : https://github.com/babeuloula/docker-nextcloud/tree/init-repo

**Comment by kesselb** [comment]
Looks like a configuration issue to me.

https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/primary_storage.html#simple-storage-service-s3

**Comment by babeuloula** [comment]
My bad, it's a typo, but now I've this : 

```
{"reqId":"OgIgshAIDpIUbIyhTa1J","level":3,"time":"May 24, 2020 15:43:12","remoteAddr":"172.25.0.1","user":"test","app":"objectstore","method":"GET","url":"/apps/files/","message":{"Exception":"Aws\\S3\\Exception\\S3MultipartUploadException","Message":"An exception occurred while initiating a multipart upload: Error executing \"CreateMultipartUpload\" on \"https://s3.fr-par.scw.cloud:433/MY_BUCKET/urn%3Aoid%3A19?uploads\"; AWS HTTP error: cURL error 7: Failed to connect to s3.fr-par.scw.cloud port 433: Connection refused (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)","Code":0,"Trace":[{"file":"/var/www/html/3rdparty/aws/aws-sdk-php/src/Multipart/AbstractUploadManager.php","line":156,"function":"transformException","class":"Aws\\Multipart\\AbstractUploadManager","type":"->","args":["*** sensitive parameter replaced ***"]}
```

**Comment by kesselb** [comment]
https://help.nextcloud.com for questions. I don't know (and it's not related to nextcloud) why the connection to your s3 provider fails.

**Comment by kesselb** [comment]
I would double check port 433. The guide at scaleway says 443. 

I'm closing the report in the meantime. Please don't use GitHub as support channel. Use https://help.nextcloud.com for setup questions.
