### ISSUE TITLE
Add flow trigger (event) on user profile updates

### ISSUE THREAD

**Issue by yrammos** [nextcloud/server#21086]
### How to use GitHub

I can think of many reasons to trigger a webhook every time users decide to change their  profile info (avatar, display name, etc.). For example, this would allow OpenID identity providers to stay up-to-date without the need for LDAP.

**Solution description**
Make a "user data updated" event available alongside existing events ("File created," "File updated," etc.).

**Alternatives considered**
Adding an LDAP backend somewhere between OpenID and NextCloud — terribly complicated and old-fashioned.

**Comment by pReya** [comment]
I am too interested in the possibility to have Flow triggers for User events (not only profile update but also user creation, deletion, etc.). Is the Flow feature supposed to have triggers aside from Files? Or is it conceptually only there to work with File triggers?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
