### ISSUE TITLE
Show app version in sidebar

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/server#21093]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using a small screen (e.g. on a smartphone) and visit the Apps page (https://<your_nextcloud_domain>/settings/apps), I can't see the version of the apps. On a large screen you see two extra columns per app: the 'featured' column and the 'app version' column. They are both removed on smaller screens. I understand this is necessary because of the little space on smaller screens. However when I click on an app, the sidebar does show if the app is featured or not, but it doesn't show the app version.

**Describe the solution you'd like**
Show the app version in the sidebar.

**Additional context**
Knowing the app version is useful, e.g., when you can upgrade to a new version of the app it is nice to see which version you are currently using so you can read up on the changes since your current version.

**Comment by Aman-Mandal** [comment]
Is this issue still there?

**Comment by szaimen** [comment]
I fear so, yes

**Comment by Aman-Mandal** [comment]
> I fear so, yes

Can you guide me in this..I wanna take this but this is my first ever contribution ..so i dont know much

**Comment by szaimen** [comment]
I fear I don't know sherr to start either. Maybe @PVince81 does?

**Comment by Brennii96** [comment]
@siccovansas Is this what you're looking for? 
Mobile view: 
![image](https://user-images.githubusercontent.com/16559757/151701237-eaf0d1ee-a832-4389-8434-81add99ef136.png)
Desktop view: 
![image](https://user-images.githubusercontent.com/16559757/151701264-3a943f50-8971-469b-8527-c889a23551df.png)

**Comment by siccovansas** [comment]
@Brennii96 yes, that looks perfect!
