### ISSUE TITLE
timestamp of account creation in database

### ISSUE THREAD

**Issue by stekaa** [nextcloud/server#21125]
It would be nice to have timestamp of account creation stored in database. Primarily it is interesting for finding unused accounts. 

I know about occ user:info lat_seen and database value for lastLogin. And if it is NULL/empty/zero the account was never used. But it could be a just created account or an old account.

With timestamp of account creation it would be possible to disable/delete an account automatically after a period of time.

So far I didn't found an app that makes it possible. Hints on this are welcome.

Thanks in advance.

**Comment by szaimen** [comment]
I think what you are looking for is this https://github.com/nextcloud/user_retention
