### ISSUE TITLE
Medias preview overlay (pictures/vidéos) not working with anonymous folder shares [18.0.4 server]

### ISSUE THREAD

**Issue by PhMetzger** [nextcloud/server#21137]
### Steps to reproduce
1.Create an anonymous share url for a folder containing some pictures and vidéos files
2.Access the link

### Expected behaviour
The preview overlay should open and display a preview of the media file

### Actual behaviour
The overlay open with an endless spinner
(propfind request initiated by viewer.js on the media file end with a 401 error for a picture file)

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2.4.38

**Database:** MariaDB 10.4.13

**PHP version:** 7.3.14

**Nextcloud version:** 18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** yes

**Where did you install Nextcloud from:** Download from nextcloud.com

**Comment by szaimen** [comment]
https://github.com/nextcloud/viewer/issues/500#issuecomment-632888881

**Comment by PhMetzger** [comment]
That solve the problem, event if not obvious :)
Thanks a lot
