### ISSUE TITLE
user list shows user entries twice

### ISSUE THREAD

**Issue by c-0815** [nextcloud/server#21134]
### Steps to reproduce
1. open user list as admin user
2. users are listed
3. when I scroll down the site is loading
4. in the table users entries were added, which already in the upper part of the list

### Expected behaviour
I should see every user only one time

### Actual behaviour

I see every user twice

occ user:list lists the users correctly, only one entry per user. Seems to be a gui problem.

### Server configuration

**Operating system:**
CentOS 7.8
**Web server:**
httpd 2.4
**Database:**
MySQL 5.5.65
**PHP version:**
7.2.31
**Nextcloud version:** (see Nextcloud admin page)
17.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:**
regular Updates since 14.0.6 without issues
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

best regards

Ralph

**Comment by c-0815** [comment]
Behavior is still present in 18.0.6

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by c-0815** [comment]
Actually in version 20.0.10 it is fixed.
