### ISSUE TITLE
Add setting "Ignore executable bit in WEBDAV" in nextcloud config.php for turn off oc_properties table query

### ISSUE THREAD

**Issue by Baltix** [nextcloud/server#21136]
**Is your feature request related to a problem? Please describe.**
ls, cp or rm one or several files from folder with several thousands files takes 10-40 seconds if lots of files have executable bit set, see issue #8962 

**Describe the solution you'd like**
It would be wise to create the setting "Ignore executable bit in WEBDAV" in nextcloud's config.php and don't query oc_properties table at all when this setting is set to true.

**Additional context**

Steps to reproduce
 1. Create a folder and upload 6000-15000 files with one user through webdav
 2. mount that folder with davfs
 3. Set executable bit for all or (at least of 3000) files
 4. try ls, cp or rm one or several files from mounted folder (or with file manager, which supports webdav)

Expected behaviour
ls, cp or rm one or several files from folder should take 1 or 2 seconds

Actual behaviour
ls, cp or rm one or several files from folder takes 10-40 seconds

See issue #8962 , especially https://github.com/nextcloud/server/issues/8962#issuecomment-475057159 and https://github.com/nextcloud/server/issues/8962#issuecomment-548255153 also newer comments with proposed code modification for more info.

### How to use GitHub
* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by acsfer** [comment]
Let me put this here too to feed this thread: https://help.nextcloud.com/t/huge-really-sql-activity-on-oc-properties-table/90598

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by haarp** [comment]
terrible bot.
