### ISSUE TITLE
LDAP quota units

### ISSUE THREAD

**Issue by krejcar25** [nextcloud/server#21149]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I use NextCloud in an Active Directory environment with a Zentyal server installed. Zentyal provides a nice field to specify user quota and stores it in LDAP, thus making it available to NextCloud. The problem is Zentyal just always uses megabytes and does not specify the unit in the value, just the number of MBs. NextCloud then interprets that as bytes.

**Describe the solution you'd like**
My suggestion is have a Units dropdown in the advanced section of the LDAP config next to the attribute field for quota and default quota. One value could be "Auto", that would interpret the LDAP value as it is now, other options would be B, KB, MB, GB...

This way it would be compatible with all possible scenarios.

**Describe alternatives you've considered**
Dynamically generated LDAP values, if that is even possible.

**Comment by kesselb** [comment]
Is that documented somewhere at Zentyal? Is there a reason to use mb always. I guess no one uses a 500kb quota anyway nowdays :)

**Comment by krejcar25** [comment]
The Zentyal UI does not allow unit selection, Mb is just written next to the input field. The choice of MB on Zentyal's side is not wrong in my opinion. The way NextCloud handles it could be configurable.

I suppose one other option would be to just set the default unit in NextCloud's config.php for the cases when there is just a number in LDAP.

**Comment by kesselb** [comment]
> The choice of MB on Zentyal's side is not wrong in my opinion. 

You reported this problem to Zentyal?

**Comment by krejcar25** [comment]
No. Again, I don't feel like their approach is necessarily wrong. And to be honest, I feel like I have a much higher chance to succeed here, NextCloud is more community-ish

**Comment by ChristophWurst** [comment]
>  The choice of MB on Zentyal's side is not wrong in my opinion

That is your personal opinion, yet most other solutions use bytes as a universal unit.

**Comment by blizzz** [comment]
> > The choice of MB on Zentyal's side is not wrong in my opinion
> 
> That is your personal opinion, yet most other solutions use bytes as a universal unit.

Seconded. If you don't provide a unit, what else can you expect than the base one? How is it possible to interact with different solutions, when you have to guess the units? This is unnecessary work for both admins and software developers.

**Comment by blizzz** [comment]
btw, if it is an option you can probably extend Zentyal with your own LDAP attribute. We have a schema for OpenLDAP at https://github.com/nextcloud/univention-app/blob/master/nextcloud.schema, it might help you.
