### ISSUE TITLE
Cannot create user when data files already exist for it

### ISSUE THREAD

**Issue by gabriel-v** [nextcloud/server#21144]
We're using Nextcloud as a file upload/download front-end for a single-user application. This means we are running a Docker image with two volumes attached:
- `./nextcloud:/var/www/html`
- `./userdata:/var/www/html/data/the_user/files`

The `userdata` volume is attached to another service that creates and removes files from it. Our setup periodically runs `files:scan --all` to keep Nextcloud up to date.

In prior versions the above setup worked fine. In nextcloud 18, one gets the error `Username is invalid because files already exist for this user` when creating a user with a data directory that already exists, but creating such a user is exactly my intention.

### Steps to reproduce

1. `mkdir -p userdata/stuff && touch userdata/stuff/a_file`
2. `docker run --rm --name nextcloud -e POSTGRES_... -v $PWD/nextcloud:/var/www/html -v $PWD/userdata:/var/www/html/data/the_user/files nextcloud:18`
3. `docker exec nextcloud php occ maintenance:install`
3. `docker exec nextcloud php occ user:add the_user` 

### Expected behaviour
The user is created. The pre-populated user data is found when running `php occ files:scan -all`.

### Actual behaviour
The message `Username is invalid because files already exist for this user` is printed to `stdout`.

### Server configuration

**Operating system:** Ubuntu 18
**Web server:** Apache/2.4.38 (Debian)
**Database:** postgres 12
**PHP version:**  PHP/7.3.17
**Nextcloud version:**  18.0.4.2

# Questions

- Is there some flag to `user:add` that supresses this check and I missed it?
  - If not, would such a flag be a welcome addition to nextcloud?
- I can't seem to locate the `if` that generates this error in this repository. I wish to remove this check in a fork; can someone point me to the right direction?
- Is there a reason for this changed behaviour?

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/18130

**Comment by NorseGaud** [comment]
This is a big problem for those of us that use ECS/Fargate and an EFS mount.

**Comment by kesselb** [comment]
Closing as per https://github.com/nextcloud/server/pull/18130#issuecomment-604697773
