### ISSUE TITLE
Request to develop dynamic forms and lists functionality similar to SharePoint

### ISSUE THREAD

**Issue by nigel-dewar** [nextcloud/server#21147]
**Is your feature request related to a problem? Please describe.**
No - this is a next feature idea

**Describe the solution you'd like**
I am a professional developer with alot of experience in SharePoint as well. I would like to develop dynamics forms and lists functionality like what SharePoint has. I have a pretty fair idea about how to do it and would like to propose the concept for discussion

**Additional context**
NextCloud pretty much has EVERYTHING a business could ever need, except the functionality I mention above.

The functionality I propose of course is not trivial, in fact its quite complicated to get right, however I believe it would provide massive benefit to NextCloud users.

I have quite a bit of experience building dynamic forms systems, with substantial code and experience to boot. Dynamic drag and drop builders written in Angular and Vue is something I have along with the backend code which supports the storage of these forms in database. I believe the way forwards is to have a base forms framework which is platform agnostic ( I have thought alot about this ), and then have implementations of this forms framework in React, Vue or Angular. This would allow the developer to extend the front end functionality as they please.

The backend ( lists ), essentially needs to be some sort of dynamic API. I have used OData and this is something SharePoint uses, however there are plenty of other options like GraphQL etc. Ive also experiemented with using backend storage like Marten (uses PostGres) for a really nice NoSQL storage.

I realize nextcloud is written in Java, so of course what I propose on the backend would all be native Java written in line with the nextcloud guidance and specifications. Essentially at a high level what I am saying is for 'Lists' functionality, the data must be exposable in a dynamic fashion so the end users can create lists with multiple fields 'columns' and even lookup fields (connect to data in other lists) as they please. This provides Psudo database like functionality. SharePoint does a semi good job of it, but has serious limits and can be a right pain to work with. SharePoint is also based off an older OData spec 'v3' which of course has its limits.

As said, this is not a trivial project, its definitely complicated, but one I believe would absolutely complete the NextCloud offering. NextCloud is absolutely a mind blowingly amazing system, and in my mind is the SharePoint killer, and a logical framework in which to build the Office 365 killer for those looking to escape it.

I am floating this idea to see if anyone is interested in working with me on it. 

I will begin a fork in a public repo and post back here in the following weeks. I will commit my code for how I think a framework would work based on my current expertise for others to view and critique. 

NextCloud admins, please move this thread or direct me to the correct place to post these things to the community.

Kind Regards

**Comment by Spartachetto** [comment]
I am sorry, I do not know SharePoint so take this just as a suggestion.

You could provide more information to understand how these features would be different from the functionality provided by Nextcloud Forms.
You could also explain why this should be part of the server and not provided as a separate app.

In my opinion these two pieces of information could help to have more people interested in your proposal.

**Comment by Terrox** [comment]
> I realize nextcloud is written in Java, so of course what I propose on the backend would all be native Java written in line with the nextcloud guidance and specifications.

I think Nextcloud is written in PHP and Javascript. Java is different.

**Comment by nigel-dewar** [comment]
@Terrox , you are right! My apologies, it is written in php and not java.

@Spartachetto , you are right this should really be a separate app. 

I will close this Issue. I will setup an App and demo for the community what I mean properly. 

thanks guys

**Comment by newice** [comment]
@nigel-dewar Hi do you already have started Bildung this App? I am also looking for a Sharepoint list like functionality.
