### ISSUE TITLE
Trashbin not cleaned for users without storage quota

### ISSUE THREAD

**Issue by judos** [nextcloud/server#21157]
### Steps to reproduce
Create user without space quota.
Delete files for this user
Configure rention in config.php e.g. 'trashbin_retention_obligation' => '180, 180',
Use GUI to show deleted files after the configured period

### Expected behaviour
No files appear which are deleted longer ago than the trashbin_retention_obligation specifies.

### Actual behaviour
I see files that are 10 month old and take up around 100GB space. I would expect they are deleted after 180 days as specified by the config.

## Server configuration detail

**Operating system:** Linux 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 5.7.26

**PHP version:** 

7.3.18
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 18.0.4 - 18.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** Via docker-compose. Originally nextcloud 16, today migrated to 17 and 18. (Nextcloud 16 did also not clean up these files earlier)

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - bruteforcesettings: 1.6.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_texteditor: 2.11.0
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - admin_audit
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "overwriteprotocol": "https",
    "htaccess.RewriteBase": "\/",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.1.5:8600",
        "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "http:\/\/192.168.1.5:8600",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "trashbin_retention_obligation": "180, 180",
    "theme": "",
    "loglevel": 2,
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** No (Everything is locally stored on a Raid5 HDD array)

**Are you using encryption:** false

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:76.0) Gecko/20100101 Firefox/76.0

**Operating system:** Win10 / Android 8 (works perfectly as expected)

## Logs

No related entries to the cleanup that should happen but doesn't.

**Comment by judos** [comment]
Additional notes:
I saw there is a command to do cleanup on server side:
```
php occ trashbin:cleanup --help
```
<details>
<summary>Command description</summary>

```
Description:
  Remove deleted files

Usage:
  trashbin:cleanup [options] [--] [<user_id>...]

Arguments:
  user_id               remove deleted files of the given user(s)

Options:
      --all-users       run action on all users
  -h, --help            Display this help message
  -q, --quiet           Do not output any message
  -V, --version         Display this application version
      --ansi            Force ANSI output
      --no-ansi         Disable ANSI output
  -n, --no-interaction  Do not ask any interactive question
      --no-warnings     Skip global warnings, show command output only
  -v|vv|vvv, --verbose  Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug
```
</details>

However so far it's unclear whether this will remove only the old trashed files (older than 180days) or all files. The description is not so clear in this way.

**Comment by acsfer** [comment]
Just to be sure, your `cronjob` is correctly running?

**Comment by judos** [comment]
I think yes:

![grafik](https://user-images.githubusercontent.com/5525810/83297579-1d5d4c80-a1f3-11ea-8bf8-2bdd4de67046.png)

It's executed and configured to use ajax. Low amount of users so should work fine. It shows actually that it has just been updated when I opened the admin panel.

**Comment by szaimen** [comment]
Hi, please configure system Cron. Ajax and Webcron have proven to be unreliable. If you still can reproduce after configuring system cron and updating to the lateset NC release, feel free to reopen. Thanks!

**Comment by judos** [comment]
Thanks that worked. With nextcloud 20.0.8 I started to see that the Ajax didn't keep up and/or was not working anymore. So I switched to System cron and the trash is cleaned now 👍
