### ISSUE TITLE
Error deleting file.  OCA\DAV\Connector\Sabre\Exception\FileLocked:

### ISSUE THREAD

**Issue by beatrfrm** [nextcloud/server#21170]
### Actual behaviour
I uploaded a 260 MB .mp4 video. I can delete it.
If I open this video and then want to delete it, I get the Error deleting File message.
If I restart Apache then I can delete the video again.
I uploaded a 200MB file without extension, wich I can't open therefore I can delete it.

### Expected behaviour
If I delete a file should be deleted. 
I searched the whole forum for an answer, but everywhere just solved with 'filelocking.enabled' => 'false', wich doesn't work in my case. Actually is a new installation, with some apps. But if I disabled all (the basic apps to) apps the problem is still here. APCu, Redis makes the same result. 
I want to use my server for our family with max 20 users.

Thank you for your help!

### Server configuration

Server configuration detail

Operating system: Linux 3.16.72-46 #1 SMP PREEMPT Tue Aug 13 18:09:58 -03 2019 aarch64

Webserver: Apache/2.4.29 (Ubuntu) (apache2handler)

Database: mysql 10.1.44

PHP version: 7.2.24-0ubuntu0.18.04.4

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, imap, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlrpc, xmlwriter, xsl, zip, Zend OPcache

Nextcloud version: 18.0.4 - 18.0.4.2

Updated from an older Nextcloud/ownCloud or fresh install:

Where did you install Nextcloud from: unknown
https://www.tecmint.com/install-nextcloud-in-ubuntu/

<details><summary>Signing status</summary>

Array ( )

</details>

<details><summary>List of activated apps</summary>

Enabled:
 - activity: 2.11.0
 - calendar: 2.0.3
 - camerarawpreviews: 0.7.3
 - carnet: 0.22.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - cookbook: 0.6.5
 - dav: 1.14.0
 - event_update_notification: 1.0.1
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - maps: 0.1.6
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - polls: 1.4.3
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.0
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - tasks: 0.13.1
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - accessibility
 - admin_audit
 - bruteforcesettings
 - encryption
 - external
 - federation
 - files_versions
 - nextcloud_announcements
 - updatenotification
 - user_external
 - user_ldap

</details>

<details><summary>Configuration (config/config.php)</summary>

{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "192.168.0.181"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.4.2",
    "overwrite.cli.url": "http:\/\/192.168.0.181\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "log_type": "file",
    "logfile": "\/var\/www\/htmml\/nextcloud\/data\/nextcloud.log",
    "loglevel": 0,
    "logdateformat": "F d, Y H:i:s",
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.distributed": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "filelocking.enabled": "false"
}

</details>

External storages: yes

<details><summary>External storage configuration</summary>

No mounts configured

</details>

Encryption: no

User-backends:

OC\User\Database

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.138 Safari/537.36 OPR/68.0.3618.125

```

### Logs
[webdav] Debug: OCA\DAV\Connector\Sabre\Exception\FileLocked: "Teszt/PUBG MOBILE_2020-05-23-14-10-53.mp4" is locked at <<closure>>

0. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
   OCA\DAV\Connector\Sabre\File->delete()
1. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
   Sabre\DAV\Tree->delete("files/Beatr/Tes ... 4")
2. <<closure>>
   Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
3. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
4. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
   Sabre\Event\EventEmitter->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
6. /var/www/html/nextcloud/apps/dav/lib/Server.php line 319
   Sabre\DAV\Server->exec()
7. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
8. /var/www/html/nextcloud/remote.php line 165
   require_once("/var/www/html/n ... p")

DELETE /remote.php/dav/files/Beatr/Teszt/PUBG%20MOBILE_2020-05-23-14-10-53.mp4
from 192.168.0.133 by Beatr at 2020-05-31T13:17:19+00:00

[no app in context] Info: OCP\Lock\LockedException: "files/fc8748cd16c9afac2f9d18c084c007e0" is locked, existing lock on file: 2 shared locks at <<closure>>

 0. /var/www/html/nextcloud/lib/private/Files/Storage/Common.php line 811
    OC\Lock\MemcacheLockingProvider->changeLock("files/fc8748cd16c9afac2f9d18c084c007e0", 2)
 1. /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 615
    OC\Files\Storage\Common->changeLock("files/Teszt/PUB ... 4", 2, OC\Lock\MemcacheLockingProvider {})
 2. /var/www/html/nextcloud/lib/private/Files/View.php line 1988
    OC\Files\Storage\Wrapper\Wrapper->changeLock("files/Teszt/PUB ... 4", 2, OC\Lock\MemcacheLockingProvider {})
 3. /var/www/html/nextcloud/lib/private/Files/View.php line 1151
    OC\Files\View->changeLock("/Teszt/PUBG MOB ... 4", 2)
 4. /var/www/html/nextcloud/lib/private/Files/View.php line 716
    OC\Files\View->basicOperation("unlink", "/Teszt/PUBG MOB ... 4", ["delete"])
 5. /var/www/html/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 448
    OC\Files\View->unlink("/Teszt/PUBG MOB ... 4")
 6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 179
    OCA\DAV\Connector\Sabre\File->delete()
 7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 287
    Sabre\DAV\Tree->delete("files/Beatr/Tes ... 4")
 8. <<closure>>
    Sabre\DAV\CorePlugin->httpDelete(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
 9. /var/www/html/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
    call_user_func_array([Sabre\DAV\CorePlugin {},"httpDelete"], [Sabre\HTTP\Requ ... }])
10. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 479
    Sabre\Event\EventEmitter->emit("method:DELETE", [Sabre\HTTP\Requ ... }])
11. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 254
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Reque ... "}, Sabre\HTTP\Response {})
12. /var/www/html/nextcloud/apps/dav/lib/Server.php line 319
    Sabre\DAV\Server->exec()
13. /var/www/html/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
14. /var/www/html/nextcloud/remote.php line 165
    require_once("/var/www/html/n ... p")

DELETE /remote.php/dav/files/Beatr/Teszt/PUBG%20MOBILE_2020-05-23-14-10-53.mp4
from 192.168.0.133 by Beatr at 2020-05-31T13:17:19+00:00

**Comment by szaimen** [comment]
This happens due to https://github.com/nextcloud/viewer/issues/894
