### ISSUE TITLE
API Endpoit to set application specific password

### ISSUE THREAD

**Issue by Kkeller83** [nextcloud/server#21178]
When creating users automatically via API I also want to be able to set and retrieve generated application specific password via REST api. 

The idea is that not each and every user has to go into Nextcloud and set their application specifc password manually in order to configure the Thunderbird lightning calendar when two factor authentication is enabled.

**Comment by kesselb** [comment]
It seems there is an api endpoint for creating app passwords. I'm not sure if there is any documentation but at https://github.com/nextcloud/server/issues/21285 one mentioned it. 

https://github.com/nextcloud/server/blob/3f8168b6e5c0fc14709b713d9ca4943f9df70273/core/routes.php#L103-L105

Are the routes.

https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/core/Controller/AppPasswordController.php#L83-L121

Is the related code.
