### ISSUE TITLE
 Cannot view the password of a shared link

### ISSUE THREAD

**Issue by AEGEGE** [nextcloud/server#21196]
Hello，
     I created a public link with mandatory encryption, but I can't view his password, and the link is copied without a password. Is there a good solution? I use nextcloud 18.0.4

**Comment by FDVCZ** [comment]
I have to confirm issue described above.
Currently there is no way (in NextCloud 18.0.4) how to find out what is the password (which already has been set), which is quite unpractical.

**Comment by szaimen** [comment]
You could just generate a new one and send that one!

Afaik, nextcloud isn't able to show you the password after saving it since it gets hashed for security reasons.

**Comment by FDVCZ** [comment]
OK, this is a satisfactory solution for some situations (I didn't notice before there is an option to create more than one password-protected link).

**Comment by szaimen** [comment]
What I meant was that you could just open the settings of the first link and disable password protection and directly enable it again to get a new password which you can copy to clipboard and save to change it to the new one

**Comment by FDVCZ** [comment]
Yes, I am aware this is possible, but not applicable to our usual use case (usually we send a link to Person A and after few days it may arise a need to send this link also to Person B, but the password is in that moment already unkown and we can not change it, because in that case Person A would lose access).

**Comment by szaimen** [comment]
Then just send the new password to person A and B again? Or just ask person A to get the old password?

**Comment by FDVCZ** [comment]
Yeah, both ways are possible, but none of them suitable for business use.

(Consider that both persons A and B are customers and you as a supplier and also owner of the link are asking them what is the password for your own link? That would be indeed lame.)

**Comment by AEGEGE** [comment]
> 是的，这两种方式都是可行的，但都不适合商业用途。
> 
> （考虑到A和B都是客户，您作为供应商以及链接的所有者都在问他们您自己的链接的密码是什么？这确实很la脚。）

感谢回复！
但是我觉得，密码不该对链接所有者保密，因为这本身就是所有者分享个其他人的。
另外我觉得如果在复制链接的时候可以将密码自动加载后面，例如：
http://nextcloud.com/xxxxx,passwd is xxxxx
这样将会非常方便使用。

**Comment by AEGEGE** [comment]
> Yeah, both ways are possible, but none of them suitable for business use.
> 
> (Consider that both persons A and B are customers and you as a supplier and also owner of the link are asking them what is the password for your own link? That would be indeed lame.)

Thanks Reply!
But I think that the password should not be kept secret from the link owner, because it is the owner who shares the others.
In addition, I think if you can automatically load the password when copying the link, for example:
http://nextcloud.com/xxxxx,passwd is xxxxx
This will be very convenient to use！

**Comment by szaimen** [comment]
> Yeah, both ways are possible, but none of them suitable for business use.
> 
> (Consider that both persons A and B are customers and you as a supplier and also owner of the link are asking them what is the password for your own link? That would be indeed lame.)

So then is probably the best option creating an additional link, as you said before.

**Comment by AEGEGE** [comment]
> > Yeah, both ways are possible, but none of them suitable for business use.
> > (Consider that both persons A and B are customers and you as a supplier and also owner of the link are asking them what is the password for your own link? That would be indeed lame.)
> 
> So then is probably the best option creating an additional link, as you said before.

Thanks, nextcloud is a great web drive.
We hope that it will be more user-friendly. I don't think it is necessary to keep the password of the link owner secret.

**Comment by szaimen** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
Yeah, that is exactly why multiple links are allowed.
Even better use "Share by mail" then the shares are labeled with the email addresses and you can revoke access individually.

Making Nextcloud less secure by adding something that allows unhashing the password is not an option.
