### ISSUE TITLE
Web: No notification for users uploading to shared folders in accounts with exceeded / high quota

### ISSUE THREAD

**Issue by opus-nbo** [nextcloud/server#21192]
If a user (or a group folder) has a quota and there is not sufficient space available in the account / group folder, upload to shared folders with write access fails with a 'insufficient space' message after completely sending the file to the server.

This is not very intuitive
1) the user thinks everything is ok
2) there is no clear indication of whats going on
3) the text is not translated (english instead of german in my case)

This should be handled before uploading the file. The server should check whether the space for the file(s) to be uploaded is sufficient and if not, the upload should not start and a translated user-friendly message should be displayed.

Nextcloud 17.0.6 on Ubuntu 18.04.4 LTS

![Bildschirmfoto 2020-06-02 um 14 35 27](https://user-images.githubusercontent.com/44579933/83521396-77a22a00-a4df-11ea-85b5-5ea5fe4d80f6.png)
![image](https://user-images.githubusercontent.com/44579933/83521439-87217300-a4df-11ea-80af-f20c452c468c.png)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
