### ISSUE TITLE
Remotely revoke authtokens

### ISSUE THREAD

**Issue by williamrech** [nextcloud/server#21194]
Is there a way to remotely revoke the user tokens as it is done through the security tab? The method described on the documentation about login flow app password doesn't quite do that.

**Comment by Terrox** [comment]
and in a related note, why don't the Security->Devices & Sessions show the IP addresses of the logged in sessions? There is no real way to tell if a logged in session is through one of your own trusted IPs or some hacker IP or you left a login active from an untrusted IP.

**Comment by Ornias1993** [comment]
@williamrech I was also breaking my head on this, because I was expecting a IDP initiated logout to also do this.
Seems userSession->logout also doesn't actually revoke the users session tokens.

https://github.com/nextcloud/user_saml/issues/455

**Comment by szaimen** [comment]
IIRC you are looking for either of thos options:
![image](https://user-images.githubusercontent.com/42591237/121669773-f5aeee80-caac-11eb-85f8-b1a8010461ef.png)

**Comment by Ornias1993** [comment]
> IIRC you are looking for either of thos options:
> ![image](https://user-images.githubusercontent.com/42591237/121669773-f5aeee80-caac-11eb-85f8-b1a8010461ef.png)

No, that was not what he was asking.
This is the second issue you are closing without carefully reading it.

He was asking if there where other ways of doing this LIKE in the security tab you just quoted.

**Comment by szaimen** [comment]
No, there is no other way, afaik.
