### ISSUE TITLE
Create themes vor nextcloud

### ISSUE THREAD

**Issue by thorian93** [nextcloud/server#212]
### Feature request
Hey guys!
I didn't find a template for feature request, so I will just go ahead and share my idea:
There should be on or more themes to personalize nextcloud. That could be instance-wide or per user, depending on the effort to implement this or on the developers decision.

Hopefully this is possible somehow, as I love dark themes and well... you know... nextcloud is bright as f***. I love the software but the bright design makes my eyes hurt. :wink: 

Thats my personal opinion but I hope I could at least start a discussion about this.
Thanks for your attention. :+1:

**Comment by mar1u5** [comment]
#59 will introduce a theming app :wink: Introducing a dark theme would make sense anyway - especially for people which are disabled (problems with eyes, photosensitve epilepsy, ...)

@nextcloud/accessibility

**Comment by thorian93** [comment]
My apologies, I oversaw that issue :disappointed: 
I searched for `theme`, which made me miss it I assume.
Thanks for the heads-up!
