### ISSUE TITLE
Chrome: Download not working - Sandboxed IFrame

### ISSUE THREAD

**Issue by toughIQ** [nextcloud/server#21205]
I could not find any info regarding this problem.
Using Chrome and viewing an inline PDF, like the Nextcloud Manual, the DOWNLOAD feature does not work, since it seems to be an IFrame which gets sandboxed in Chrome and Downloads are prohibited.

### Steps to reproduce
1. Open "Nextcloud Manual.pdf" using Chrome Browser
2. Try to Download given file using Download Button featured in Inline-viewer
![ScreenShot Chrome Download](https://filebox.apa-it.at/s/x5dbjEZDBAPMxTn/preview)
3. Check Chrome Inspector Error messages:
`Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.`

### Expected behaviour
Download dialog should appear

### Actual behaviour
Nothing happens

### Server configuration

**Operating system:**
Linux ServerName 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
Debian: 9.12
**Web server:**
Apache2 2.4.25-3+deb9u9

**Database:**
Server version: 10.1.44-MariaDB-0+deb9u1 Debian 9.11

**PHP version:**
PHP 7.2.30-1+0~20200419.40+debian9~1.gbpb1b799 (cli) (built: Apr 19 2020 08:41:18) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
18.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Raised from 14.x

**Where did you install Nextcloud from:**
Nextcloud build in updater
### Client configuration
**Browser:**
Chrome Version 83.0.4103.61 (Offizieller Build) (64-Bit)
**Operating system:**
Win10

### Logs
Chrome console:
`Download is disallowed. The frame initiating or instantiating the download is sandboxed, but the flag ‘allow-downloads’ is not set. See https://www.chromestatus.com/feature/5706745674465280 for more details.`

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/files_pdfviewer/pull/186

**Comment by toughIQ** [comment]
Thanks @kesselb 
How do I get this fix?
The version of files_pdfviewer here says 18.0.5
But with my Nextcloud 18.0.5 I get PDF Viewer 1.7.0
![PDF Viewer Version](https://filebox.apa-it.at/s/bzDGP5QNkKN2mcM/preview)
Thanks

**Comment by kesselb** [comment]
Either wait for a new release or apply the patch yourself.

**Comment by toughIQ** [comment]
> Either wait for a new release or apply the patch yourself.

Thanks @kesselb 
Is there a manual on how to apply such a change? I substituted the original apps folder with the 18.0.5 code, but could not see the change be applied.
Any hint for me?
Thx

**Comment by kesselb** [comment]
cc @juliushaertl Is pdfviewer shipped with server?
