### ISSUE TITLE
Option to limit how often a shared linked could be opened or downloaded

### ISSUE THREAD

**Issue by MarcelMpunkt** [nextcloud/server#21204]
**What is the problem?**
If you share something via link, you can protect the link by password or expiration date. But often you only want to share something so that somebody else can view or download it one or several times. You don´t know exactly when somebody is using the link. But that it has to be opened at least once to fullfil its purpose.

**What could be the solution?**
In the sharing-context-menu there should be an option like:

- "Set Limit"
  - "Download Limit"
  - "View Limit"

**Are there alternative solutions?**

none

**Additional context**
You could set a limit how often something could be viewed, before it is unavailable. It could also be useful if you want to give away something like an ebook. If you set a download limit of 500 copies, it could only be downloaded 500 times before it is unavailabe.

![sharing-context-menu](https://user-images.githubusercontent.com/18383682/83630883-d8dc0300-a59c-11ea-85ab-f5067540f2e9.JPG)

**Comment by kesselb** [comment]
It's hard to detect if a request is done by a real user or the url is fetched in a automated way. For example Skype does this to preview a page sometime.

**Comment by MarcelMpunkt** [comment]
I think there are several possibilities with JavaScript. 


Am 3. Juni 2020 19:02:57 MESZ schrieb kesselb <notifications@github.com>:
>It's hard to detect if a request is done by a real user or the url is
>fetched in a automated way. For example Skype does this to preview a
>page sometime.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/nextcloud/server/issues/21204#issuecomment-638328143

Beste Grüße
der Marcel

**von meinem Mobiltelefon gesendet**

**Comment by sndrr** [comment]
Even though it is possible with Javascript, it does not make it easy. And how do you handle browser reopenings on mobile?

**Comment by szaimen** [comment]
I guess before [this](https://github.com/nextcloud/activity/issues/519) isn't fixed, it doesn't really make sense to implement this because we won't be able to track this reliably.
