### ISSUE TITLE
Nextcloud 18.0.4, directory date in the future

### ISSUE THREAD

**Issue by dea-75** [nextcloud/server#21219]
Hi all,
We use a Debian 10 64 bit full update, Nextcloud 18.0.4 on PHP-FPM (Debian 10 version), Apache2 (Debian 10 version), PostgreSQL (Debian 10 version).
We don't use "external storage", datastore is on NFS local mounted.

Yesterday I see this:
A directory "_CLIENTI": (stat...)
![immagine](https://user-images.githubusercontent.com/62520276/83724916-58bba900-a641-11ea-9a48-923d3d679c51.png)
Perfectly correct !

On Nextcloud I see this:

![immagine](https://user-images.githubusercontent.com/62520276/83725003-7f79df80-a641-11ea-8110-3195f3d057b0.png)

Totally senseless

Time server is perfect (NTP works fine)

Any idea to fix ?

Thanks

**Comment by ChristophWurst** [comment]
Please ask your support question at https://help.nextcloud.com/
