### ISSUE TITLE
PHP fatal error when S3 legacy_auth is enabled

### ISSUE THREAD

**Issue by sq5gvm** [nextcloud/server#21214]
**NextCloud version 19.0.0**

When trying to enable S3 storage with legacy_auth enabled Nextcloud "crashes" with following message in PHP logs:

`Declaration of OC\Files\ObjectStore\S3Signature::presign(Psr\Http\Message\RequestInterface $request, Aws\Credentials\CredentialsInterface $credentials, $expires) must be compatible with Aws\Signature\SignatureInterface::presign(Psr\Http\Message\RequestInterface $request, Aws\Credentials\CredentialsInterface $credentials, $expires, array $options = Array)`

Current presign function is missing last parameter - array of options, required by v3 of aws-sdk-php:
https://github.com/nextcloud/server/blob/1762a409f954fd9a66e7572704ea9ba7813601b4/lib/private/Files/ObjectStore/S3Signature.php#L73-L77

Adding missing parameter fixes this error.

AWS docs: https://docs.aws.amazon.com/aws-sdk-php/v3/api/class-Aws.Signature.SignatureInterface.html#_presign

**Comment by kesselb** [comment]
Looks good to me. Mind to send a pull request?

**Comment by BorisdeFloris** [comment]
Having this problem in my 19.0.0 also which updated today and since today is my S3 storage broken, my main use.
I can´t edit this S3Signature.php
