### ISSUE TITLE
cron.php fails while scanning external smb storage

### ISSUE THREAD

**Issue by schinni15** [nextcloud/server#21213]
cron.php fails with error when SMB1 is deactivated.
Error in syslog 
 smbXcli_negprot_smb1_done: No compatible protocol selected by server.
Jun  2 00:01:30 linus php[80415]: Protocol negotiation failed: NT_STATUS_INVALID_NETWORK_RESPONSE

Entries in smb.conf are present
   client min protocol = SMB2
   client max protocol = SMB3

System Ubuntu 20.04
NextCloud 19 RC3

**Comment by kesselb** [comment]
Looks similar to https://github.com/nextcloud/server/issues/19429
