### ISSUE TITLE
After NC 19 Upgrade Tons of session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209

### ISSUE THREAD

**Issue by apg1980** [nextcloud/server#21237]
After Upgrade to NC 19 i got a mass of entrys like this in the nextcloud.log
`session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209`
### Steps to reproduce
1. goto setting
2. open logging
3. see

### Expected behaviour
not seeing the entrys

### Actual behaviour
`session_start(): A session had already been started - ignoring at /var/www/nextcloud/lib/private/Session/Internal.php#209`

### Server configuration

**Operating system:**ubuntu 18.04 lts

**Web server:**apache2

**Database:**postgresql

**PHP version:**7.3-fpm

**Nextcloud version:** 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**fro 18.04

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Please search the existing issues first, it's likely that your issue was already reported or even fixed.

-  Go to https://github.com/nextcloud and type any word in the top search/command bar. You probably see something like "We couldn’t find any repositories matching ..." then click "Issues" in the left navigation.
- You can also filter by appending e. g. "state:open" to the search string.
- More info on search syntax within github: https://help.github.com/articles/searching-issues
