### ISSUE TITLE
Emit cancellable Pre-Event before setting the E-Mail (Possible other attributes)

### ISSUE THREAD

**Issue by VincentWo** [nextcloud/server#21233]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
We use Nextcloud with an LDAP-User Backend. We enforce unique E-Mails through the use of a LDAP-Overlay, so sometimes writing an E-Mail can fail. (We use the LDAP write support plugin). I already filled out a Bug Report at the Write Support, but I've got told, that they only receive an event after the Mail has already been changed.

**Describe the solution you'd like**
Make the E-Mail Setting somehow cancelable, by either emitting an pre-event or by reverting changes when the after-event is cancelled.

**Describe alternatives you've considered**
Adding an option to enforce unique E-Mails would also solve this specific issue, but making the event cancelable would probably scale better.

**Additional context**
LDAP Write Support Issue I filed: https://github.com/nextcloud/ldap_write_support/issues/164

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
