### ISSUE TITLE
[Updater] Could not find resource js/config.js to load

### ISSUE THREAD

**Issue by MichaIng** [nextcloud/server#21235]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Related Nextcloud forum thread:
https://help.nextcloud.com/t/jsresourceloader-error-could-not-find-resource-js-config-js-to-load/66979?u=michaing

### Steps to reproduce
1. Use the web based updater to update from any version between NC17 and NC19 to any newer version.
2. Check nextcloud.log

### Expected behaviour
No error log entries.

### Actual behaviour
```
{"reqId":"XXXX","level":3,"time":"2020-06-04T13:11:40+02:00","remoteAddr":"XXXX","user":"--","app":"jsresourceloader","method":"GET","url":"/nextcloud/","message":"Could not find resource js/config.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4115.5 Safari/537.36 OPR/70.0.3707.0 (Edition developer)","version":"19.0.0.9","id":"XXXX"}
```
But this only shows up a **single time** as very first log entry when using the web-based updater and I noticed **no actual issues**. Hence I mark this as **low priority**.

### Server configuration

**Operating system:** Debian Buster and Bullseye

**Web server:** Apache 2.4

**Database:** MariaDB 10.3

**PHP version:** PHP7.3 and PHP7.4

**Nextcloud version:** 17/18/19

**Updated from an older Nextcloud/ownCloud or fresh install:** Issue appears during update

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.12.0
  - apporder: 0.10.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_rightclick: 0.16.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - impersonate: 1.6.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.4.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - provisioning_api: 1.9.0
  - ransomware_protection: 1.7.0
  - settings: 1.1.0
  - spreed: 9.0.0
  - survey_client: 1.7.0
  - tasks: 0.13.1
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - accessibility
  - admin_audit
  - comments
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_sharing
  - files_videoplayer
  - firstrunwizard
  - password_policy
  - privacy
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - systemtags
  - text
  - theming
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "my.domain.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "logtimezone": "Europe\/Berlin",
        "trashbin_retention_obligation": "disabled",
        "versions_retention_obligation": "disabled",
        "skeletondirectory": "",
        "defaultapp": "apporder",
        "maintenance": false,
        "overwrite.cli.url": "https:\/\/micha.gnoedi.org\/nextcloud",
        "htaccess.RewriteBase": "\/nextcloud",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "mysql.utf8mb4": true,
        "updater.release.channel": "beta",
        "tempdirectory": "\/mnt\/sda\/ncdata\/tmp",
        "preview_max_x": "2048",
        "preview_max_y": "2048",
        "jpeg_quality": "60",
        "app_install_overwrite": [
            "apporder",
            "calendar",
            "impersonate",
            "ransomware_protection",
            "contacts",
            "spreed"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Opera

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
nothing
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"XXXX","level":3,"time":"2020-06-04T13:11:40+02:00","remoteAddr":"XXXX","user":"--","app":"jsresourceloader","method":"GET","url":"/nextcloud/","message":"Could not find resource js/config.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4115.5 Safari/537.36 OPR/70.0.3707.0 (Edition developer)","version":"19.0.0.9","id":"XXXX"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
nothing
```
</details>

**Comment by MichaIng** [comment]
Still face this on update 19.0.0 => 19.0.1

**Comment by MichaIng** [comment]
Some research:
- The calendar app contains several references to a `config.js` file in `./apps/calendar/js/calendar.js.map`, but there is no such file. However I don't believe that this is called/invoked during the update.
- `./apps/files/list.php` contains this part:
    > $config = \OC::$server->getConfig();
$userSession = \OC::$server->getUserSession();
// TODO: move this to the generated config.js
$publicUploadEnabled = $config->getAppValue('core', 'shareapi_allow_public_upload', 'yes');

    I have the share API disabled currently, not sure if related and where/how this config.js is "generated".
- And the following `*.js.map` files as well contain references to a `config.js` file, which are likely the issue:
  - `./core/js/dist/maintenance.js.map`
  - `./core/js/dist/login.js.map`
  - `./core/js/dist/main.js.map`

Not sure if `config.js` is something that is created temporarily or not even as real file?

Based on timestamps it is either when loading the the web updater page (2. stage, so after files have been installed, so for migration/repair steps) or when hitting the start button:
```
{"reqId":"Lp3SNmMkHPxMxgREeJSo","level":3,"time":"2020-07-17T14:34:24+02:00","remoteAddr":"192.168.1.10","user":"--","app":"jsresourceloader","method":"GET","url":"/nextcloud/","message":"Could not find resource js/config.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4181.8 Safari/537.36 OPR/71.0.3749.0 (Edition developer)","version":"19.0.0.12","id":"5f12e1a7d957c"}
{"reqId":"H7jxnzh1oy0oYKL8J0ki","level":1,"time":"2020-07-17T14:34:30+02:00","remoteAddr":"192.168.1.10","user":"--","app":"updater","method":"GET","url":"/nextcloud/core/ajax/update.php?requesttoken=9zljKFKIhYKhY7dy7EYMXQ%2BHSNVOnXKUmNrxcb7LpvE%3D%3AhFFMbzCx0vOKJvxCoiM8Em71cbZ70RT%2F6qOoBIuZ0os%3D","message":"\\OC\\Updater::maintenanceEnabled: Turned on maintenance mode","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4181.8 Safari/537.36 OPR/71.0.3749.0 (Edition developer)","version":"19.0.0.12","id":"5f12e1a7d94bd"}
{"reqId":"H7jxnzh1oy0oYKL8J0ki","level":1,"time":"2020-07-17T14:34:30+02:00","remoteAddr":"192.168.1.10","user":"--","app":"updater","method":"GET","url":"/nextcloud/core/ajax/update.php?requesttoken=9zljKFKIhYKhY7dy7EYMXQ%2BHSNVOnXKUmNrxcb7LpvE%3D%3AhFFMbzCx0vOKJvxCoiM8Em71cbZ70RT%2F6qOoBIuZ0os%3D","message":"\\OC\\Repair::step: Repair step: Repair MySQL collation","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4181.8 Safari/537.36 OPR/71.0.3749.0 (Edition developer)","version":"19.0.0.12","id":"5f12e1a7d924d"}
```
Actually I remember that in most cases I need to hit the button two times before it starts. Prooobably, as I see the GET request token, the root of this issue is the same as in #17065 due to a wrongly decoded access token? Although since to page reload is done before is succeeds, and my webserver does not suffer the pre-decoding issue of Lighttpd with its new defaults, I don't think that it has something to do with it.

Probably someone with some more insights can have a look, especially into `./core/js/dist/login.js.map` since it is about the login/front page, just with fresh code installed ready for upgrade/migration.

**Comment by axheli** [comment]
Same issue on Nextcloud 20
PHP 7.4.3
MYSQL 8
APACHE2

<details>
<summary>Web server error logs</summary>

```
{"reqId":"z3i3LkufcjZjKnkokHBJ","level":3,"time":"2020-10-12T13:49:28+00:00","remoteAddr":","user":"","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/files/client.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"20.0.0.9","id":"5f84946e98d2a"}

{"reqId":"z3i3LkufcjZjKnkokHBJ","level":3,"time":"2020-10-12T13:49:28+00:00","remoteAddr":"","user":"","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/files/fileinfo.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36","version":"20.0.0.9","id":"5f84946e98d47"}

```

**Comment by weak-head** [comment]
After the recent update I'm having the same issue. In my case I run nextcloud as FreeNAS plugin installed/updated via the marketplace.

```json
{
  "reqId": "YUDOT3Wi5h1dfciivmTh",
  "level": 3,
  "time": "2020-10-30T02:24:04+00:00",
  "remoteAddr": "10.10.1.10",
  "user": "--",
  "app": "jsresourceloader",
  "method": "GET",
  "url": "/",
  "message": "Could not find resource js/config.js to load",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0",
  "version": "19.0.1.1"
}
```

**Comment by skjnldsv** [comment]
cc @MorrisJobke @rullzer @ChristophWurst

**Comment by pszypowicz** [comment]
Also for me. Happens i.e. when I try to share Task deck with other user. 

Ubuntu 20.04
PHP 7.4.3
Postrgresql 12.4
Nginx: 1.18

```
{"reqId":"VteHg2dxktlfK4hVFIcj","level":3,"time":"2020-11-09T09:47:48+00:00","remoteAddr":"xxx","user":"xxx","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/files/client.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1","id":"5fa9115657e4a"}
```

**Comment by skjnldsv** [comment]
Coming from https://github.com/nextcloud/server/blob/48d843858de095e83105f55d6b994ad41939f5d4/lib/base.php#L374

**Comment by skjnldsv** [comment]
Lol, 9 years ago https://github.com/nextcloud/server/commit/2e05bd69f5b39f449f7e7475d81c27ee2b1f946a

**Comment by Vivida1** [comment]
Still getting this error in 20.0.2 (using container nextcloud:20.0.2). I also applied commit https://github.com/nextcloud/server/commit/8e9d259074619de0f137d749fc94dd4e580d2ec9 to 20.0.1 manually a few days ago with the same result.

```
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.1.20. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.1.20. Set the 'ServerName' directive globally to suppress this message
[Thu Nov 19 21:02:24.095218 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.12 configured -- resuming normal operations
[Thu Nov 19 21:02:24.095427 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
[Thu Nov 19 21:05:14.008288 2020] [php7:notice] [pid 36] [client ::1:41990] {"reqId":"OSsdiI2FLTqbkpeqzDii","level":3,"time":"2020-11-19T21:05:14+00:00","remoteAddr":"::1","user":"--","app":"jsresourceloader","method":"GET","url":"/","message":"Could not find resource js/setup.js to load","userAgent":"curl/7.64.0","version":""}
::1 - - [19/Nov/2020:21:05:13 +0000] "GET / HTTP/1.1" 200 8313 "-" "curl/7.64.0"
```

**Comment by Jollerprutt** [comment]
Same issue on Nextcloud 20.0.2
PHP 7.4.13
MYSQL 15.1
Nginx 1.14
<details>
<summary>log message</summary>
<pre>$ {"reqId":"N1JhziQyT2TQnriMd11o","level":3,"time":"2020-12-08T02:09:18+00:00","remoteAddr":"XX.XX.XX.XX","user":"carl","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/files/client.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0","version":"20.0.2.2","id":"xxxx"}</pre>
</details>

**Comment by MichaIng** [comment]
@Jollerprutt 
Can you please open a new issue with this? It is not the same issue, a different file in a different circumstance is involved. It is when accessing the workflow settings in admin panel and I even triggered another missing script there:
```
{"reqId":"mwoYe5Icksh9ArfSlCGe","level":3,"time":"2020-12-08T13:18:31+01:00","remoteAddr":"192.168.1.1","user":"Micha","app":"jsresourceloader","method":"GET","url":"/nextcloud/settings/admin/workflow","message":"Could not find resource core/js/files/fileinfo.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4315.5 Safari/537.36 OPR/74.0.3890.0 (Edition developer)","version":"20.0.2.2","id":"5fcf6f2f5bf85"}
```

**Comment by Jollerprutt** [comment]
@MichaIng Yes sorry, it's not the same as your original post but it is the same as what @axheli posted earlier in this issue. https://github.com/nextcloud/server/issues/21235#issuecomment-707259275

**Comment by MichaIng** [comment]
However, this issue is closed with a fix for the originally reported bug. For the sake of attention and transparent bug fix tracking, it makes sense to report even such similar bug as a separate issue. It appeared with a different Nextcloud version and in a very different part of Nextcloud is affected here, even that the error message looks so similar 😉.
