### ISSUE TITLE
(Optional) Cleanup plugin database tables while deinstalling

### ISSUE THREAD

**Issue by frlan** [nextcloud/server#21245]
**Is your feature request related to a problem? Please describe.**

When installing and deinstalling plugins, old tables (and data) keeps on the database. This might leads to a huge amount of actually unused data inside the database.

**Describe the solution you'd like**
Add a way to remove old tables.  As a first idea plugins could somehow register tables and once the registration is gone (due to the plugin is gone), a maintenance-subcommand could offer to delete these orphaned tables.

**Comment by kesselb** [comment]
Closing as duplicate of https://github.com/nextcloud/server/issues/5539
