### ISSUE TITLE
Expiration Date not set is Paeronal info/Locale = Marathi

### ISSUE THREAD

**Issue by shakapare** [nextcloud/server#21258]
### Steps to reproduce
Set Locale in Personal info = Marathi or Marathi (India)
Try setting expiration date for any file or folder to be shared

### Expected behaviour
Expiration Date will be set

### Actual behaviour
Error shown at two places:
1. Top Side : "Error Updating Share"
2. On Expiry date Setting : " expireDate, Invalid date. Format must be YYYY-MM-DD"

If the Locale is set to India this error gets resolved.

## Server configuration detail

**Operating system:** Linux 2.6.32-042stab116.2 #1 SMP Fri Jun 24 15:33:57 MSK 2016 x86_64

**Webserver:** Apache/2.4.41 (Unix) OpenSSL/1.0.2k-fips (cgi-fcgi)

**Database:** mysql 10.1.45

**PHP version:** 

7.3.16
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gettext, gmp, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, mysqli, PDO, pdo_mysql, pdo_sqlite, Phar, posix, pspell, Reflection, imap, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, imagick, ssh2, mcrypt, ionCube Loader

**Nextcloud version:** 18.0.5 - 18.0.5.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 18

**Where did you install Nextcloud from:** Auto Update

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - bruteforcesettings: 1.6.0
 - cloud_federation_api: 1.1.0
 - dav: 1.14.0
 - encryption: 2.6.0
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_ebookreader: 0.0.1
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - mail: 1.3.5
 - notes: 3.4.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.9
 - text: 2.0.0
 - theming: 1.9.0
 - theming_customcss: 1.6.0
 - twofactor_backupcodes: 1.7.0
 - unsplash: 1.1.5
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - activity
 - admin_audit
 - comments
 - federation
 - files_external
 - firstrunwizard
 - nextcloud_announcements
 - password_policy
 - recommendations
 - support
 - survey_client
 - systemtags
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.ske.ind.in"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.5.1",
    "overwrite.cli.url": "https:\/\/cloud.ske.ind.in",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "simpleSignUpLink.shown": false,
    "maintenance": false,
    "mysql.utf8mb4": true,
    "theme": "",
    "loglevel": 2,
    "app_install_overwrite": [
        "files_reader",
        "files_ebookreader"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.163 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Not Necessarry
```
</details>

<details><summary>Nextcloud log</summary>

```
Not Necessarry
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

![Annotation 2020-06-05 180141](https://user-images.githubusercontent.com/66482177/83891977-a83fc900-a756-11ea-87a0-0804d72ed893.png)

**Comment by zahradehghanpur** [comment]
Same problem here.

**Comment by dev-am1** [comment]
same with persian locale .

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2
