### ISSUE TITLE
Inline script blocked

### ISSUE THREAD

**Issue by Dreamsorcerer** [nextcloud/server#21269]
I'm getting: `Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”).  utils.js:35`.

The code appears to be trying to inject a script directly into the DOM. This occurs on the Decks app.

**Comment by kesselb** [comment]
Added the needs info label due the missing issue template. Repository for deck app is: https://github.com/nextcloud/deck

**Comment by Dreamsorcerer** [comment]
Think I may have been looking at the wrong thing. Sorry.
