### ISSUE TITLE
Calendars not loading 500 in Browser Console 

### ISSUE THREAD

**Issue by brucewillis88** [nextcloud/server#2126]
### Steps to reproduce
1. Open Nextcloud
2. Log in
3. Go to Calendar App

### Expected behaviour
Calendars should each load and display their events

### Actual behaviour
One or more of my 6 calendars fails to load with an HTTP 500 in the browser console

### Server configuration
**Operating system**:
Linux

**Web server:**
Apache Version	2.4.23
cPanel Version	60.0 (build 19)

**Database:**
MySQL Version	5.5.52-cll

**PHP version:**
PHP Version	5.6.27

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
downloads.nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
- core
	- INVALID_HASH
		- core/doc/admin/_sources/configuration_files/collaborative_documents_configuration.txt
		- core/doc/admin/_static/style.css
		- core/fonts/LICENSE.txt
		- core/vendor/jsTimezoneDetect/jstz.js
	- EXTRA_FILE
		- error_log
- files_external
	- INVALID_HASH
		- 3rdparty/Dropbox/API.php
- files_texteditor
	- INVALID_HASH
		- js/vendor/ace/src-noconflict/mode-diff.js
```
</details>

**List of activated apps:**
<details>
<summary>Activity, Auditing/Logging, Deleted files, external sites, federation, file sharing, gallery, mail template editor, notifications, password policy, pdf viewer, provisioning api, server info, text editor, theming, update notifications, usage report, versions, video player, calendar </summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

<?php
$CONFIG = array (
  'instanceid' => 'oc2wnc6m0o3f',
  'passwordsalt' => 'x',
  'secret' => 'x',
  'trusted_domains' => 
  array (
    0 => 'cloud.midstatelitho.net',
  ),
  'datadirectory' => '/home/cloud/public_html/data',
  'overwrite.cli.url' => 'http://cloud.midstatelitho.net',
  'defaultapp' => 'calendar',
  'dbtype' => 'mysql',
  'version' => '9.1.1.5',
  'dbname' => 'x',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'x',
  'dbpassword' => 'x',
  'logtimezone' => 'UTC',
  'theme' => 'msl',
  'installed' => true,
  'loglevel' => 0,
  'maintenance' => false,
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no, just https

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
google chrome

**Operating system:**
windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```

Debug	webdav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/cloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/cloud\/public_html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/home\/cloud\/public_html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/home\/cloud\/public_html\/remote.php(165): require_once('\/home\/cloud\/pub...')\n#7 {main}","File":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":"ellen"}	2016-11-14T18:24:05+00:00	ellen
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2016-11-14T18:23:59+00:00	steven
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	2016-11-14T18:23:52+00:00	--
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2016-11-14T18:23:49+00:00	steven
Info	no app in context	Invalidating tokens older than 2016-11-13T18:23:39+00:00	2016-11-14T18:23:39+00:00	--
Debug	DeleteOrphanedSharesJob	0 orphaned share(s) deleted	2016-11-14T18:23:52+00:00	--
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2016-11-14T18:23:49+00:00	steven
Info	no app in context	Invalidating tokens older than 2016-11-13T18:23:39+00:00	2016-11-14T18:23:39+00:00	--
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2016-11-14T18:19:50+00:00	--
Debug	webdav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/cloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/cloud\/public_html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/home\/cloud\/public_html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/home\/cloud\/public_html\/remote.php(165): require_once('\/home\/cloud\/pub...')\n#7 {main}","File":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":"shawn"}	2016-11-14T18:09:47+00:00	shawn
Error	PHP	Automatically populating $HTTP_RAW_POST_DATA is deprecated and will be removed in a future version. To avoid this warning set 'always_populate_raw_post_data' to '-1' in php.ini and use the php://input stream instead. at Unknown#0	2016-11-14T18:07:50+00:00	--
Debug	webdav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/cloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/cloud\/public_html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/home\/cloud\/public_html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/home\/cloud\/public_html\/remote.php(165): require_once('\/home\/cloud\/pub...')\n#7 {main}","File":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":"ellen"}	2016-11-14T18:05:40+00:00	ellen
Debug	webdav	Exception: {"Message":"HTTP\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/home\/cloud\/public_html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/cloud\/public_html\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/home\/cloud\/public_html\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/home\/cloud\/public_html\/remote.php(165): require_once('\/home\/cloud\/pub...')\n#7 {main}","File":"\/home\/cloud\/public_html\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":"ellen"}	2016-11-14T18:05:39+00:00	ellen
Info	admin_audit	Login successful: "ellen"	2016-11-14T18:05:37+00:00	ellen
Info	admin_audit	Login attempt: "ellen"	2016-11-14T18:05:37+00:00	--

```
</details>

#### Browser log
<details>
<s
[nextcloud (2).Txt](https://github.com/nextcloud/server/files/590161/nextcloud.2.Txt)

ummary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
jquery-migrate.min.js?v=a00127d…:2 JQMIGRATE: Migrate is installed, version 1.4.0
https://cloud.midstatelitho.net/remote.php/dav/calendars/steven/reminders/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://cloud.midstatelitho.net/remote.php/dav/calendars/steven/sales/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
https://cloud.midstatelitho.net/remote.php/dav/calendars/steven/technicians/ Failed to load resource: the server responded with a status of 500 (Internal Server Error)
b) The network log
c) ...
```
</details>

Recommended to post this here by georgehrke

**Comment by georgehrke** [comment]
@LukasReschke Could this be related to an error 500?
```
Info	no app in context	Invalidating tokens older than 2016-11-13T18:23:39+00:00	2016-11-14T18:23:39+00:00	--
```

**Comment by brucewillis88** [comment]
Here is the correct error log

> [Mon Nov 14 14:01:36.726006 2016] [:error] [pid 124802] (12)Cannot allocate memory: [client 50.245.98.65:8471] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:23:06.916458 2016] [core:crit] [pid 87532] (13)Permission denied: [client 50.245.98.65:19832] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 13:23:06.834211 2016] [:error] [pid 77671] (12)Cannot allocate memory: [client 50.245.98.65:28157] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
> [Mon Nov 14 13:22:47.592741 2016] [:error] [pid 84045] (12)Cannot allocate memory: [client 50.245.98.65:8205] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:22:47.575953 2016] [:error] [pid 88849] (12)Cannot allocate memory: [client 50.245.98.65:1892] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:22:12.960860 2016] [core:crit] [pid 88852] (13)Permission denied: [client 50.245.98.65:3553] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 13:22:12.958198 2016] [:error] [pid 88849] (12)Cannot allocate memory: [client 50.245.98.65:11522] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:22:00.479484 2016] [core:crit] [pid 86909] (13)Permission denied: [client 50.245.98.65:1793] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 13:11:09.738811 2016] [:error] [pid 77019] (12)Cannot allocate memory: [client 50.245.98.65:30613] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:11:09.738811 2016] [:error] [pid 78998] (12)Cannot allocate memory: [client 50.245.98.65:20433] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:10:59.159829 2016] [:error] [pid 77002] (12)Cannot allocate memory: [client 50.245.98.65:4207] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 13:10:59.128541 2016] [:error] [pid 76885] (12)Cannot allocate memory: [client 50.245.98.65:15792] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:52:44.361539 2016] [:error] [pid 61881] (12)Cannot allocate memory: [client 50.245.98.65:8118] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:52:42.415296 2016] [:error] [pid 60859] (12)Cannot allocate memory: [client 50.245.98.65:18239] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:52:42.415296 2016] [:error] [pid 61863] (12)Cannot allocate memory: [client 50.245.98.65:9981] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:52:42.404446 2016] [:error] [pid 57222] (12)Cannot allocate memory: [client 50.245.98.65:23116] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:52:42.396891 2016] [:error] [pid 61862] (12)Cannot allocate memory: [client 50.245.98.65:17752] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:45:47.225223 2016] [:error] [pid 56002] (12)Cannot allocate memory: [client 50.245.98.65:23777] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:45:47.176226 2016] [:error] [pid 56001] (12)Cannot allocate memory: [client 50.245.98.65:21838] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:45:47.139503 2016] [:error] [pid 44627] (12)Cannot allocate memory: [client 50.245.98.65:24735] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:24:06.755551 2016] [:error] [pid 32011] (12)Cannot allocate memory: [client 50.245.98.65:62098] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
> [Mon Nov 14 12:24:06.705584 2016] [core:crit] [pid 35005] (13)Permission denied: [client 50.245.98.65:65376] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 12:24:00.609586 2016] [:error] [pid 33623] (12)Cannot allocate memory: [client 50.245.98.65:63269] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:24:00.575002 2016] [:error] [pid 32824] (12)Cannot allocate memory: [client 50.245.98.65:49967] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:24:00.552880 2016] [:error] [pid 31053] (12)Cannot allocate memory: [client 50.245.98.65:56305] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:23:51.939162 2016] [core:crit] [pid 32824] (13)Permission denied: [client 50.245.98.65:49967] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 12:23:51.936331 2016] [:error] [pid 25353] (12)Cannot allocate memory: [client 50.245.98.65:60339] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
> [Mon Nov 14 12:23:51.932587 2016] [:error] [pid 33703] (12)Cannot allocate memory: [client 50.245.98.65:60540] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
> [Mon Nov 14 12:23:39.427567 2016] [core:crit] [pid 33592] (13)Permission denied: [client 50.245.98.65:44183] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 12:23:29.678879 2016] [:error] [pid 23628] (12)Cannot allocate memory: [client 50.245.98.65:40665] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:23:29.673659 2016] [:error] [pid 32916] (12)Cannot allocate memory: [client 50.245.98.65:44362] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
> [Mon Nov 14 12:23:29.673659 2016] [:error] [pid 33592] (12)Cannot allocate memory: [client 50.245.98.65:47947] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
> [Mon Nov 14 12:23:29.650693 2016] [core:crit] [pid 31348] (13)Permission denied: [client 50.245.98.65:22709] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 12:03:11.073868 2016] [:error] [pid 13104] (12)Cannot allocate memory: [client 50.245.98.65:11527] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:03:11.062471 2016] [:error] [pid 13252] (12)Cannot allocate memory: [client 50.245.98.65:10088] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:02:58.479716 2016] [:error] [pid 12967] (12)Cannot allocate memory: [client 50.245.98.65:64087] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:02:48.300512 2016] [:error] [pid 12816] (12)Cannot allocate memory: [client 50.245.98.65:64678] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:02:48.276726 2016] [:error] [pid 11644] (12)Cannot allocate memory: [client 50.245.98.65:38742] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:02:27.682829 2016] [:error] [pid 2769] (12)Cannot allocate memory: [client 50.245.98.65:48004] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:02:14.035889 2016] [:error] [pid 8821] (12)Cannot allocate memory: [client 50.245.98.65:20332] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:02:14.004386 2016] [:error] [pid 8786] (12)Cannot allocate memory: [client 50.245.98.65:46956] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 12:00:54.479168 2016] [core:crit] [pid 4513] (13)Permission denied: [client 50.245.98.65:52504] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable
> [Mon Nov 14 11:59:55.564526 2016] [:error] [pid 4901] (12)Cannot allocate memory: [client 50.245.98.65:8803] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
> [Mon Nov 14 11:59:55.559957 2016] [core:crit] [pid 7101] (13)Permission denied: [client 50.245.98.65:37327] AH00529: /home/cloud/public_html/data/.htaccess pcfg_openfile: unable to check htaccess file, ensure it is readable and that '/home/cloud/public_html/data/' is executable

**Comment by georgehrke** [comment]
I removed your IP address from your logs.

Cannot allocate memory: [client xxx.xxx.xxx.xxx:8471] couldn't create child process: opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php`

This is pretty clear. The php script runs out of memory.
Can you check the memory limit of your instance?

<img width="959" src="https://cloud.githubusercontent.com/assets/1250540/20282454/0027589c-aab5-11e6-9164-511f50130655.png">

**Comment by brucewillis88** [comment]
PHP

Version: 5.6.27
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513.0 MB

**Comment by nickvergessen** [comment]
That should still be enough in theory.

**Comment by brucewillis88** [comment]
- I had my host up the memory limit to 512 MB.
- I wiped and did a clean install. Moved my calendars by downloading the .ics and then importing it.
- If I load the calendar page with all the calendars OFF, then turn them on _one at a time_ they all load OK.
- If I load the page with all 6 calendars ON, one or more of them will exhibit the 500 error
- Below is an updated error log after this fresh install.

```
[Tue Nov 15 07:05:46.064015 2016] [:error] [pid 59223] (12)Cannot allocate memory: [client xx.xx.xx.xx:64150] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/index.php
[Tue Nov 15 07:05:46.060802 2016] [:error] [pid 57495] (12)Cannot allocate memory: [client xx.xx.xx.xx:12275] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/ocs/v2.php
[Tue Nov 15 07:05:31.154289 2016] [:error] [pid 67543] (12)Cannot allocate memory: [client xx.xx.xx.xx:13617] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:05:31.136681 2016] [:error] [pid 65550] (12)Cannot allocate memory: [client xx.xx.xx.xx:55429] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:05:31.080332 2016] [:error] [pid 68097] (12)Cannot allocate memory: [client xx.xx.xx.xx:4974] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:05:24.933725 2016] [:error] [pid 61155] (12)Cannot allocate memory: [client xx.xx.xx.xx:11709] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/ocs/v2.php
[Tue Nov 15 07:05:22.495928 2016] [:error] [pid 68081] (12)Cannot allocate memory: [client xx.xx.xx.xx:46922] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:04:25.800706 2016] [:error] [pid 66671] (12)Cannot allocate memory: [client xx.xx.xx.xx:10938] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:04:25.799724 2016] [:error] [pid 67105] (12)Cannot allocate memory: [client xx.xx.xx.xx:13738] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:39.121978 2016] [:error] [pid 66575] (12)Cannot allocate memory: [client xx.xx.xx.xx:2064] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:39.101904 2016] [:error] [pid 65565] (12)Cannot allocate memory: [client xx.xx.xx.xx:39935] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:39.046632 2016] [:error] [pid 63429] (12)Cannot allocate memory: [client xx.xx.xx.xx:64745] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:26.862330 2016] [:error] [pid 65515] (12)Cannot allocate memory: [client xx.xx.xx.xx:15552] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:26.780880 2016] [:error] [pid 65551] (12)Cannot allocate memory: [client xx.xx.xx.xx:56817] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:21.426347 2016] [:error] [pid 62097] (12)Cannot allocate memory: [client xx.xx.xx.xx:47362] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
[Tue Nov 15 07:03:21.355034 2016] [:error] [pid 58833] (12)Cannot allocate memory: [client xx.xx.xx.xx:58757] couldn't create child process: /opt/suphp/sbin/suphp for /home/cloud/public_html/remote.php
```

**Comment by georgehrke** [comment]
@brucewillis88 Can you estimate how many events/todos are in these calendars?
Are there a lot of repeating events?

**Comment by brucewillis88** [comment]
Tough to estimate, we use it for our company's scheduling. Average of 5 events a day I would guess. We've been using the calendar for about 18 months this way. There are no repeating events. Since this started I've eliminated 2 calendars by merging them. This has helped make the bug more manageable.

![example](https://cloud.githubusercontent.com/assets/19995724/20317801/987d07c4-ab35-11e6-8de5-852a00579105.JPG)

**Comment by LollenJumplan** [comment]
Can you still reproduce this in a recent nextcloud version? Nextcloud 10 has been EOL for a while now.

**Comment by georgehrke** [comment]
Never got feedback from the original reporter, closing.
