### ISSUE TITLE
Personal Share Notes

### ISSUE THREAD

**Issue by gary-kim** [nextcloud/server#21265]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I often make several links for files that are shared for different people or groups so I can more easily keep track of who should have access to them and if I end up needing to remove certain links. I am currently doing this with comments but that makes it very difficult to know which link each comment refers to. Public share notes are another option but often, this is a message I'd like to keep private to only people with edit access to the file.

**Describe the solution you'd like**

In addition to the `Note to recipient`, an extra `Note to self` option that allows you to write a note to your future self about the share link.

**Describe alternatives you've considered**

Currently using the comments system but that gets out of hand very quick if there is more than one share link for the file.

I looked for if there was an already existing feature request and didn't find one but if I missed it, sorry about that.

**Comment by wiswedel** [comment]
duplicate of https://github.com/nextcloud/server/issues/15500
