### ISSUE TITLE
Cannot add WebAuthn-device in NC 19

### ISSUE THREAD

**Issue by OliverPifferi** [nextcloud/server#21268]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

Hello everyone,

after successfully upgrading to NC19, I am facing the problem that I cannot add a WebAuthn-device (Nitrokey FIDO2) to use the integrated passwordless login. Once I click on the button, nothing happens - this depends on my user though as the Nextcloud-Administrator doesn’t have this problem.
![baa426d57cea0209b7a904187b8688f5010c288d](https://user-images.githubusercontent.com/42076599/83946477-763f6d00-a811-11ea-845c-610d1210ce2d.png)
I used WebAuth via the separate app “Two-Factor WebAuthn” (https://apps.nextcloud.com/apps/twofactor_webauthn 6) before with NC 18 and hadn’t any problems. The app wasn’t compatible but could be activated nevertheless so I removed my Nitrokey, removed the app and am still stuck as I cannot add the key with the new, integrated feature in NC 19.

I also took a test system, complete new installation with NC 19 in the meantime. I cannot add WebAuthn as a standard user, being the Nextcloud-Administrator it works as it should.

Is this issue possibly already known? Affected systems are Debian 10 and Ubuntu 20 Server, Nextcloud is running with latest Apache and PHP 7.4 and MariaDB.

**Comment by kesselb** [comment]
cc @rullzer @ChristophWurst

**Comment by Borega** [comment]
I have the same issue. Nextcloud 19 on Ubuntu 20 server with ngnix. and php7.4 and MariaDB

**Comment by thgoebel** [comment]
With my Docker installation, the dev console shows a 403 on the `/settings/api/personal/webauthn/registration` endpoint if I try to set up WebAuthn as a normal user, if that's any help.

**Comment by derHSE** [comment]
Same for Yubikey 5 NFC (...ok, it is FIDO2 :-) )

**Comment by kesselb** [comment]
```
Index: apps/settings/lib/Controller/WebAuthnController.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/settings/lib/Controller/WebAuthnController.php	(revision dba76c04bba910c3c6f1dec4f3eba6416ec3378d)
+++ apps/settings/lib/Controller/WebAuthnController.php	(date 1591471721105)
@@ -65,6 +65,7 @@
 
 	/**
 	 * @NoAdminRequired
+	 * @NoSubadminRequired
 	 * @PasswordConfirmationRequired
 	 * @UseSession
 	 * @NoCSRFRequired
@@ -82,6 +83,7 @@
 
 	/**
 	 * @NoAdminRequired
+	 * @NoSubadminRequired
 	 * @PasswordConfirmationRequired
 	 * @UseSession
 	 */
```

Should do the trick ;)
