### ISSUE TITLE
Video CPU use bug and a question.

### ISSUE THREAD

**Issue by JanisPlayer** [nextcloud/server#21272]
### Steps to reproduce
1. Upload a mp4 file.
2. Watch and fast forward the video with the browser.
3. And look the CPU use.
https://help.nextcloud.com/t/i-have-a-high-cpu-usage-when-watching-a-video-via-the-browser/83029
There are others who have the same problem.

I wanted to ask whether the encryption can also be managed by another user?
So that an extra service takes over the encryption and not the www-data user.
I ask because I'm trying to write a plugin that encrypts the files via Javascript and optionally via an extra server before they are uploaded / added.

### Expected behaviour
Tell us what should happen
The CPU usage increases and many threads are opened.

### Actual behaviour
Tell us what happens instead
The CPU usage increases and many threads are opened.

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
mariadb
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
18.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
No
**Where did you install Nextcloud from:**
Nextcloud :D
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - encryption: 2.6.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - mail: 1.3.5
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.2.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)


{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "download.heldendesbildschirms.dynv6.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.5.1",
        "overwrite.cli.url": "http:\/\/download.heldendesbildschirms.dynv6.net",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 2,
        "theme": "",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
yes
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome HTML5
**Operating system:**
Windows 10, Android, Ubuntu
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
> So that an extra service takes over the encryption and not the www-data user.
I ask because I'm trying to write a plugin that encrypts the files via Javascript and optionally via an extra server before they are uploaded / added.

=> https://help.nextcloud.com/c/dev/11

**Comment by JanisPlayer** [comment]
Is there a solution to the workload problem now? I can't use Nextcloud like this if I get a small video from the server DoS. :( Apache works much better for the same video. I can't even see the load in htop, unlike Nextcloud, because my server is only fighting. It is really strange that it is displayed several times under the details downloads. Although the video was only tackled once. So something is wrong. And I asked around, I'm not the only one.

**Comment by JanisPlayer** [comment]
Disable encryption:
sudo -u www-data php7.3 occ encryption:enable
cd /var/www/html/nextcloud/
sudo -u www-data php7.3 occ encryption:decrypt-all
sudo -u www-data php7.3 occ maintenance:mode --on
sudo -u www-data php7.3 occ encryption:disable
sudo -u www-data php7.3 occ maintenance:mode --off
You only need the encryption, if you have store files on the order unsecury Server.
On your nextcloud server, you can every time decrype 
the data, with masterkey or sharekey or user password.
Warning, please make a backup for you decrypt, my first try to decrypt have not work it perfectly and 2-4 data is lost.
