### ISSUE TITLE
Upgrading to 19.0.0 failst with table exists

### ISSUE THREAD

**Issue by madpipeline** [nextcloud/server#21293]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Deploy latest nextcloud 18 with Docker
2. Pull and start on the same deploy the Nextcloud 19 docker image, replacing the 18 image.

### Expected behaviour
The upgrade to be able to run completely after triggered from the CLI or WEB UI.

### Actual behaviour
Both CLI and WEB UI fail the upgrade with this error:

`The table with name 'nextcloud.oc_recent_contact' already exists.`

### Server configuration

**Operating system:**
Linux Docker
**Web server:**
Nginx
**Database:**
MariaDb
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
Upgrade from latest 18 to latest 19
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated since OwnCloud.
**Where did you install Nextcloud from:**
Official FPM Docker image.

**Comment by madpipeline** [comment]
Renaming that table to something else in the DB solves the issue.

I could rename it since I don't use the contacts app, even though it's installed.

**Comment by kesselb** [comment]
`oc_recent_contact` is a new table for `contactsinteraction` app and only available for Nextcloud 19 and above. Strange the table already exist on your instance.

**Comment by fragadass** [comment]
Same issue on my Nextcloud 19.0.0, while upgrading to 19.0.1 (stable canal).
The table already exists, it seems normal according to @kesselb 
My table was empty, so I deleted it to finish the upgrade.
Maybe a little 'IF NOT EXISTS' is missing in the sql ?

**Comment by zsbolyoczki** [comment]
I was just updating from 19.0.1.1 to 19.0.3.1 and I have also bumped into this.

Fortunately the table was empty so I renamed it and the ``occ upgrade`` finished successfully.

**Comment by tjaehnel** [comment]
I had the same error during `occ upgrade` from Nextcloud 18 to 19 (19.0.3 in particular). Since it was empty I removed that table believing it will be recreated anyway.
Unfortunately `occ upgrade` did not create that table and as a result I wasn't able to access my contacts from neither the web interface nor any CardDav Client. The log showed: _"Base table or view not found: 1146 Table 'nextcloud.oc_recent_contact' doesn't exist"_.

Thank you @kesselb for mentioning that this table belongs to the contacts interaction app.
Disabling that app solved the problem and access to contacts is now restored.

**Comment by DrAxelbauer** [comment]
Hi there!
I am facing a similar issue trying to upgrade from 18.0.6 to 19.0.6. The Updater fails with the following issue:
Doctrine\DBAL\Schema\SchemaException: The table with name 'oci-pbijidod81.shw18_recent_contact' already exists.
(oci-pbijidod81 is the name of my database) 
Unfortunately I couldn't find the table to rename or delete and I don't want to run the risk of deleting the contacts...Any hints how to solve this issue? Thx

**Comment by deisi** [comment]
Hey guys I also have this wile upgrading from 21.0.0 to 21.0.1 for me the updater showed:

```
Doctrine\DBAL\Schema\SchemaException: The table with name 'nextcloud.oc_recent_contact' already exists.
Update failed
```

after dropping the table the upgrade just went fine.

**Comment by kesselb** [comment]
I'm unable to reproduce this issue. Feel free to reopen if one has new information how to trigger this error.
