### ISSUE TITLE
Duplicated users after reinstalling Talk

### ISSUE THREAD

**Issue by ostasevych** [nextcloud/server#21291]
### Steps to reproduce
1. Uninstall Talk
2. Drop tables oc_talks*
3. Install Talk
4. Observe the duplication of users when trying to share some file

### Expected behaviour
The users are not duplicated

### Actual behaviour
When I try to share some file I see two users: ordinary one and the one with the same username but in brackets (conversation).
![image](https://user-images.githubusercontent.com/5199030/83974939-83378b80-a8f9-11ea-97a0-769a8b8c5df5.png)

![image](https://user-images.githubusercontent.com/5199030/83974970-a95d2b80-a8f9-11ea-9652-513e3e233cb6.png)

### Server configuration

**Operating system:** Centos 6.10

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.3

**Nextcloud version:** 19.0.0.12

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** official repositort

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/24407
