### ISSUE TITLE
Installation screen: On button click, collapse details and show spinner correctly

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2129]
When clicking the install button while the Storage & database settings are open, the view looks really strange and the spinner is somewhere inbetween the text.

Instead, the advanced settings should collapse and then the spinner will be shown correctly on top of the user/password input fields.

cc @nextcloud/javascript especially because this is the first experience, we should fix it.

**Comment by jancborchardt** [comment]
(As per https://github.com/nextcloud/server/issues/2134)

**Comment by skjnldsv** [comment]
Screenshot? :D

**Comment by MorrisJobke** [comment]
![broken installer](https://cloud.githubusercontent.com/assets/245432/20395356/e6128398-ace2-11e6-8745-1ed2280b7c7b.png)

**Comment by jancborchardt** [comment]
Probably simply collapsing the details via JS will take care of the issue. Will investigate.

**Comment by skjnldsv** [comment]
Are you working on it @jancborchardt ? I can take a look on this tomorrow morning otherwise :)

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/2242 :)
