### ISSUE TITLE
Allow admin to define a password rules

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#213]
I will start working on a app which let the admin define some rules for passwords.

## Scope

- [x] public link passwords
- [x] login passwords (for local user back-end)

## Rules

- [x] define a minimum length of the password
- [x] enforce upper/lower case 
- [x] at least one numeric character
- [x] at least one special character

Did I miss something?

Development started here https://github.com/nextcloud/password_policy/pull/1
Added events to core: https://github.com/nextcloud/server/pull/221

cc @karlitschek @LukasReschke @MorrisJobke @blizzz

**Comment by karlitschek** [comment]
sweeet. i think this should be all

**Comment by LukasReschke** [comment]
> login passwords (for local user back-end)

I doubt that ownCloud has this. Furthermore, this is usually considered snake-oil and it has been proven that this actually decreases security. 

Something more reliable in this case usually is what for example Discourse does:

- Define minimum password length (e.g. 8 characters)
- Ship a JSON file of the 1 million or 100'000 most used passwords (you can get them in the internet) and  forbid to use it if it is on it.

I'd *HIGHLY* advocate to go this approach for the login passwords as well as the share passwords instead. We won't add a highly complicated GUI plus it is technically more secure. Plus easier to implement ;-)

You can get a list from https://github.com/danielmiessler/SecLists/tree/master/Passwords and an example implementation https://github.com/discourse/discourse/blob/master/lib/common_passwords/common_passwords.rb

**Comment by LukasReschke** [comment]
>  define a minimum length of the password

👍 

> enforce upper/lower case
> at least one numeric character
> at least one special character

👎  and go instead with an proposal as suggested at https://github.com/nextcloud/server/issues/213#issuecomment-228285060

**Comment by karlitschek** [comment]
let's go with the same feature set for now.

**Comment by LukasReschke** [comment]
> let's go with the same feature set for now.

Share link only passwords then, that should be easy as there are already hooks for that: `\OC\Share::verifyPassword` and `\OC\Share::verifyExpirationDate`. Both pass `$accepted` as reference.

**Comment by schiessle** [comment]
> Share link only passwords then, that should be easy as there are already hooks for that: \OC\Share::verifyPassword and \OC\Share::verifyExpirationDate. Both pass $accepted as reference.

I would just solidarity the hooks while working on it and also add it to the normal password change. Shouldn't be a lot of work and with a dedicated hook other apps can also connect to it and verify their passwords if they wish.

**Comment by LukasReschke** [comment]
> I would just solidarize the hooks while working on it and also add it to the normal password change. Shouldn't be a lot of work and with a dedicated hook other apps can also connect to it and verify their passwords if they wish.

Ok. Good point. 👍

**Comment by schiessle** [comment]
Merged and ready for Nextcloud 9.0.52
