### ISSUE TITLE
Invitation email subjects are not localized

### ISSUE THREAD

**Issue by maluhub** [nextcloud/server#21305]
### Steps to reproduce
1. Change your language to anything but english (e.g. Polish)
2. Invite somebody to your event

### Expected behaviour
Both - mail subject and body should be localized to Polish.

### Actual behaviour
Mail body is localized, but mail subject is still in English ("Invitation: ", "Cancelled: ").

### Nextcloud version
18.0.4

**Comment by maluhub** [comment]
I wanted to contributed this fix, but can't find a way to create a branch without forking.
Could anyone apply fix from attachment?
[21305-patch.zip](https://github.com/nextcloud/server/files/4745431/21305-patch.zip)

**Comment by maluhub** [comment]
Let me call you @kesselb , since this issue could be easily solved by simply applying a patch (see above comment).

**Comment by kesselb** [comment]
Does that make sense @nextcloud/calendar?

**Comment by georgehrke** [comment]
That patch makes sense. I'm not sure we should translate 'Re: ' though.

@maluhub Can you please send a pull-request?

**Comment by maluhub** [comment]
@georgehrke I'm senior gitlab user, but I'm new to github, and I don't know how. I would normally create a branch, commit changes and create a pull request, however I have no idea how to create a remote branch to which I could push my changes.

**Comment by Mer0me** [comment]
Some news about this issue ?

**Comment by szaimen** [comment]
Hi maluhub do you mind creating a PR with your patch?
Thank you!
