### ISSUE TITLE
Files uploaded by WEBDAV are 0 sized in DB (also web interface), but on storage are OK.

### ISSUE THREAD

**Issue by biware-repo** [nextcloud/server#21315]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Run WebDAV client and create connection to NC instance
2. Copy some files to NC
3. Files have zero size, the 0 is in also in oc_filecache
4. The physical storage show the proper size of files and content is OK

### Expected behaviour
The files should have proper size in web interface, also webdav client should show the proper size of file after upload.

### Actual behaviour
There 0 in size of uploaded files in web interface and also webdav client show 0

### Server configuration
Intel(R) Xeon(R) CPU E5620 @ 2.40GHz (4 cores) - Virtual machine
16 GB RAM
4 TB SSD Intel (RAID 5)

**Operating system:**
UBUNTU 18.04.4 LTS (Bionic Beaver)
Linux 4.15.0-99-generic x86_64

**Web server:**
Apache 2.4.29

**Database:**
MariaDB 10.1.44

**PHP version:**
PHP 7.2.24

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18.0.5

**Where did you install Nextcloud from:**
Updated with updater from admin interface.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
``` 
  - accessibility: 1.5.0
  - activity: 2.12.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_automatedtagging: 1.9.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - flowupload: 1.0.0
  - groupfolders: 6.0.6
  - impersonate: 1.6.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 4.2.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - side_menu: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.0
  - viewer: 1.3.0
  - workflow_script: 1.4.0
  - workflowengine: 2.1.0
``` 
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
``` 
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           "***REMOVED SENSITIVE VALUE***",
           "***REMOVED SENSITIVE VALUE***",
           "***REMOVED SENSITIVE VALUE***",
           "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",,
        "dbtableprefix": "oc_",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "simpleSignUpLink.shown": "false",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "trashbin_retention_obligation": "14,31",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "maintenance": false,
        "skeletondirectory": "core\/skeleton",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "beta",
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "onlyoffice",
            "ldapcontacts",
            "files_reader"
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "version": "19.0.0.12",
        "has_rebuilt_cache": true,
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}
``` 
</details>

**Are you using external storage, if yes which one:** 
local

**Are you using encryption:** 
no

**Are you using an external user-backend, if yes which one:** 
no

### Client configuration
**Browser:**
Chrome 83.0.4103.61

**Operating system:**
Windows 10 1903

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Mon Jun 08 06:25:10.071564 2020] [mpm_event:notice] [pid 36008:tid 140286657182656] AH00489: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Mon Jun 08 06:25:10.071602 2020] [core:notice] [pid 36008:tid 140286657182656] AH00094: Command line: '/usr/sbin/apache2'
[Mon Jun 08 07:27:01.674808 2020] [access_compat:error] [pid 7408:tid 140285686302464] [client 213.81.157.70:49978] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Mon Jun 08 09:03:29.013712 2020] [access_compat:error] [pid 7408:tid 140285703087872] [client 95.105.172.148:53674] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Mon Jun 08 09:40:42.730314 2020] [access_compat:error] [pid 7409:tid 140286222051072] [client 194.154.241.247:53276] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Mon Jun 08 10:01:14.452407 2020] [access_compat:error] [pid 7408:tid 140285174609664] [client 194.154.248.129:58895] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Mon Jun 08 12:59:44.608673 2020] [access_compat:error] [pid 7408:tid 140286213650176] [client 213.81.157.70:52910] AH01797: client denied by server configuration: /var/www/nextcloud/config
[Mon Jun 08 15:04:05.816081 2020] [access_compat:error] [pid 7408:tid 140285686302464] [client 46.34.234.215:15017] AH01797: client denied by server configuration: /var/www/nextcloud/config
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Log is empty after base cleaning, although the bug exists.
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Browser log is not related, because bug exists only with webdav client. 3 clients have been tested. Before update was everything fine.
```
</details>

In the screenshot is Z: connected as WebDAV. File is copied, but show 0 size. In the oc_filecache there is also 0 in size field. Physically on the storage the file has proper size and content, but still show 0 in all clients. (webdav, mobile app, web interface) The same problem is with bigger files newly uploaded.

![screenshot](https://user-images.githubusercontent.com/22624070/84037990-9ef56d00-a99f-11ea-8e95-339f9f418e7a.png)

**Comment by biware-repo** [comment]
No solution for relative primitive bug? Before was all ok. Now if file is copied via Webdav there 0 size, although on the physical storage on nextcloud is ok.

**Comment by hwangjunjie** [comment]
I have the same problem   -_-

**Comment by hwangjunjie** [comment]
I want to know from which version the problem started

**Comment by biware-repo** [comment]
For me after update to 19.0.0

**Comment by hwangjunjie** [comment]
I have downgraded to 18.0.6，it is fine

**Comment by biware-repo** [comment]
How did you do it. Generally it is not supported. Probably i need to do the same. But I do not know how.

**Comment by SilentMiner2** [comment]
> I have downgraded to 18.0.6，it is fine

how did you downgrade? or did you restore a backup?

**Comment by TorinKR** [comment]
At the moment I found two solutions. The first is to use Air Live Drive as a mapping tool https://www.airlivedrive.com/en/ looks like it is working properly. Tests since last night and probably (?) No problems.
The second solution that I started to research on the second test server yesterday is Nextcloud's night build. It also looks like it solves a problem!

**Comment by hwangjunjie** [comment]
> > I have downgraded to 18.0.6，it is fine
> 
> how did you downgrade? or did you restore a backup?

I reinstalled and copied th data directory, then create the top-level directory on site, and the data will be restored

**Comment by hwangjunjie** [comment]
> > > I have downgraded to 18.0.6，it is fine
> > 
> > 
> > how did you downgrade? or did you restore a backup?
> 
> I reinstalled and copied th data directory, then create the top-level directory on site, and the data will be restored

@biware-repo you can try it

**Comment by bbolokofsky** [comment]
Same issue.  
I noticed also that collabora office development Edition is sometimes zeroing out the file as well when opening an existing normal file and saving it.  Even after the file is zeroed out CODE will still open the file and if I change it again sometimes it saves normally and sometimes it's still zero.

**Comment by wbonis** [comment]
Yes we see the same problem here!

Webdav (and Collabora) creates 0 byte files in the view. The content is still there.

Serious Bug, Because it can lead to data corruption, if a client saves back the 0 byte file, the data is lost.

Any ETA on a bugfix?

**Comment by bbolokofsky** [comment]
I was really hoping to see some kind of update on this.   This seems to be a critical issue and has caused data loss for some of my clients.  Data loss does not look good for us or Nextcloud.  Unfortunately these were new installs and not upgrades so we can’t even restore from backup. We would just like to know if a fix is coming soon so we can decide weather we need to build new server installs and migrate the data (hundreds of thousands of files) for each of these customers or wait.

**Comment by julieni** [comment]
Hi,

I have some similar issue, mostly repeatable when working on a folder that is shared by an other user.

* create an XLSX file locally
* upload to Nextcloud shared folder with webdav client (tried Nautilus on linux and Cyberduck on Windows)
* try to open file from Nautilus: works
* edit file remotly in libre office OR change file locally with Excel in windows then reupload with cyberduck
* try to open file from Nautilus again: file is corrupted most of the time

NB: I'm not doing concurrent updates/uploads, but tested on 2 platforms

NB: It seems far less repeatable if my nextcloud user owns the folder the files are in (not a folder shared by another user)

Also tried with TXT files, with text editors or simply echoing some content to file from shell, also managed to have partial content over time, and even I/O errors in shell.

**Comment by stephenitpro** [comment]
Same problem using a webdav client (RaiDrive) for NC19.  Uploads the files fine but reports back on the Webdav mount and web ui as 0KB.  Kinda dangerous.

**Comment by wbonis** [comment]
Yes, i also dont understand! 

The Slogan is "A safe home for all your data" 
But this Bug in a released version of the Software is now more than 20days open! Exposing dataloss!

Everyone could loose data!

Why did now one of the core team even comment here?

Why is there no fix?

**Comment by stephenitpro** [comment]
This is true, NC19 is destroying people's data and wasn't ready for release. 👎

**Comment by bbolokofsky** [comment]
I’m curious is this only happening on Docker installs?

**Comment by stephenitpro** [comment]
My install is on bare metal and does odd things with webdav and webui uploads

**Comment by kesselb** [comment]
Please avoid "I have the same problem" and other unrelated comments. Such comments makes it harder to find the important information how to reproduce a problem. Use [reactions](https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to agree or disagree. 

I tried to reproduce the upload a file via webdav problem with https://try.nextcloud.com but that seems to work with Nautilus: 
1. Create a demo user A
2. Connect the user webdav with Nautilus 3.34.1
3. Copy a file to mounted folder - validate file size via terminal / remounted folder and web ui - seems correct (at least it's not 0kb)
4. Create another demo user B
5. **B:** Create a new folder and share it with user A
6. **A:** Copy files to the folder shared from user B - validate size again - seems correct
7. **B:** Also check the size of the files uploaded by user A

For your information: The desktop and mobile clients provided by Nextcloud are also using the webdav interface to access the files.

To develop a fix we need a reliable way to reproduce this problem. It would help if some of you could try to reproduce it with https://try.nextcloud.com and provide the steps. 

Thanks in advance :+1:

**Comment by wbonis** [comment]
What i have done:

create a Account on try.nextcloud.com

Setup a webdav mount from Finder on Mac: ( to https://demo1.nextcloud.com/remote.php/dav/files/XLRgxCMFjjf7paj7/ )

Drop a File in the Documents Folder

Result: The File size is 0 ( in Finder and in the Webinterface)

**Comment by wbonis** [comment]
I did another Test on this Webdav mount ( See Screenshoots  )

<img width="846" alt="screenshot_556" src="https://user-images.githubusercontent.com/7256778/87226379-aa1f2c80-c393-11ea-9bbe-92803c47e548.png">
![screenshot_557](https://user-images.githubusercontent.com/7256778/87226391-c28f4700-c393-11ea-87c9-9b28bbb1515b.png)

**Comment by bbolokofsky** [comment]
The same results are produced when using mountain duck or the native windows WebDAV client.  Air live drive and an rclone mapped drive in windows for some reason do not cause the 0 byte problem.

**Comment by jospoortvliet** [comment]
In the dolphin and Konqueror file managers on Linux I get an error that there is no free space when I try to copy in files. What does work is creating a new text file (2 bytes...) and editing it. Creating a new presentation (ods) also gives the error and I can't copy in a 2 byte (new) flat text file either.

This was using cloud.nextcloud.com, running Nextcloud 19.0.1RC1.

A bit of testing showed however the same issue with Nextcloud 18.0.6, so this isn't new. I guess the WebDAV implementation is sensitive and doesn't work well with some/many clients.

**Comment by Bables55** [comment]
Will a fix for this issue be available in time for the 16.0.1 stable release scheduled for this week?

**Comment by bjoernv** [comment]
I tested uploading a LibreOffice Impress file directly via LibreOffice and via Dophin/KDE.

Saving a LibreOffice Impress via LibreOffice works.

Copying an existing LibreOffice Impress file via Dolphin results in the following error:
`There is not enough space on the disk to write file:///tmp/xyz.odp.`
/tmp/xyz.odp is the source file, so free disk space (> 10 Gbyte) should not be a problem.

The server is Nextcloud 18.0.6.

**Comment by biware-repo** [comment]
So again.
1. Mount nextcloud via webdav (eg. Windows WebClient)
2. Copy some file to nextcloud. This results to 0 file size. BUT FILESIZE IS OK ON PHYSICAL NEXTCLOUD STORAGE. In DB is 0. Creating files is not OK. There is no info about files size before inserting to DB.
3. Copy the same file again and rewrite the existing file. This results to proper file size in DB. File already exists size is properly updated in DB.

It is connected to process of creating new file and handling the filesize during creation.

**Comment by julieni** [comment]
Hi @kesselb,

I managed to reproduce on try.nextcloud.com.

Both users are on demo1

1st user : cBjg4s4NK8DnRL3T
2nd user : EzGSma6tkWZ5PwJa

2nd user shares a folder named "shared", then creates some subfolders

![Capture d’écran de 2020-07-13 10-52-40](https://user-images.githubusercontent.com/995738/87287142-0a2fe300-c4fa-11ea-9700-6ac2540b07d4.png)

1st user uses Nautilus 3.36.3 (latest archlinux) and uploads an .xlsx file created with Libreoffice.

![Capture d’écran de 2020-07-13 10-54-55](https://user-images.githubusercontent.com/995738/87287145-0ac87980-c4fa-11ea-8c6f-5386fc825950.png)

The file opens fine locally (of course), and remotely (fine too).
Local and remote files show same size:

> $ ls -al nc-test*
> -rw-r--r-- 1 julien users 4873 13 juil. 10:34 nc-test.xlsx

> $ ls -al shared/a\ subfolder/another\ one/
> total 5
> drwx------ 1 julien users    0 13 juil. 10:54 .
> drwx------ 1 julien users    0 13 juil. 10:54 ..
> -rwx------ 1 julien users 4873 13 juil. 10:54 nc-test.xlsx

Then user1 updates file locally, and uploads it remotely with Nautilus, replacing the original one.

Local file still opens fine with libreoffice, but remote file is corrupt (error message in french, telling the file is corrupted and asking for repair)
![Capture d’écran de 2020-07-13 10-58-35](https://user-images.githubusercontent.com/995738/87287149-0ac87980-c4fa-11ea-9715-d3e8d74d4699.png)

Before updating the file, i made a copy to keep the original one locally, so we can see the size is different :

> $ ls -al nc-test*
> -rw-r--r-- 1 julien users 4873 13 juil. 10:34 nc-test-orig.xlsx
> -rw-r--r-- 1 julien users 5248 13 juil. 10:57 nc-test.xlsx

and on remote side, the old size is returned (same for the modification time), even after a long time wait :

> $ date
> lun. 13 juil. 2020 11:12:26 CEST
> $ ls -al shared/a\ subfolder/another\ one/
> total 5
> drwx------ 1 julien users    0 13 juil. 10:58 .
> drwx------ 1 julien users    0 13 juil. 10:58 ..
> -rwx------ 1 julien users 4873 13 juil. 10:54 nc-test.xlsx

Then a connected as user2 with webdav, replaced the file once again, then file and modification date are OK

> $ ls -al
> total 6
> drwx------ 1 julien users    0 13 juil. 11:22 .
> drwx------ 1 julien users    0 13 juil. 11:22 ..
> -rwx------ 1 julien users 5248 13 juil. 11:22 nc-test.xlsx

then updated local file, uploaded again as user2, and size and time update accordingly.

> $ ls -al
> total 6
> drwx------ 1 julien users    0 13 juil. 11:24 .
> drwx------ 1 julien users    0 13 juil. 11:24 ..
> -rwx------ 1 julien users 5265 13 juil. 11:24 nc-test.xlsx

So my best guess is that it happens (wrong sizes) when working on a shared folder if you're not the owner of that folder. Because both size nor time update, I bet it's db-cached infos related, I mean updating as not the owner does not trigger info updates.

Julien

**Comment by julieni** [comment]
Hi @kesselb,

just tried again on try.nextcloud.com, 100% reproductible.

2 accounts on demo2 server
user 2 shares a folder "shared" with user 1

Everything is fine with user 2 :

> $ echo "123456789" > test.txt
> $ ls -al test.txt
> -rwx------ 1 julien users 10 16 juil. 15:29 test.txt

reduce file :

> $ echo "1234" > test.txt
> $ ls -al test.txt
> -rwx------ 1 julien users 5 16 juil. 15:30 test.txt

increase file :

> $ echo "1234567" > test.txt
> $ ls -al test.txt
> -rwx------ 1 julien users 8 16 juil. 15:31 test.txt

NB: I have the same `ls -al test.txt` results from user 1 shell (user 1 just does listing at this step)



Now I switch to user 1 shell:

> $ ls -al test.txt 
> -rwx------ 1 julien users 8 16 juil. 15:31 test.txt
> $ cat test.txt
> 1234567
> $ echo "12" > test.txt 
> $ ls -al test.txt 
> -rwx------ 1 julien users 8 16 juil. 15:31 test.txt

size and time are not updated (neither from user 1 nor user 2 shells), even after minutes waiting

writing the file a second time triggers size and time updates:

> $ echo "12" > test.txt 
> $ ls -al test.txt 
> -rwx------ 1 julien users 3 16 juil. 15:35 test.txt

increasing content leads to corrupted file:

> $ echo "123456789" > test.txt 
> $ ls -al test.txt 
> -rwx------ 1 julien users 3 16 juil. 15:38 test.txt
> $ cat test.txt
> 123

The file is corrupted because only 3 bytes (wrong cached size) are retrieved.
At this point, the file is still OK on server side storage
In fact, it will be corrupt if I save/sync that truncated file back to the server.

**Comment by stephenitpro** [comment]
Does anyone know whether this problem persists with the new NC19.0.1 update?

**Comment by Bables55** [comment]
> Does anyone know whether this problem persists with the new NC19.0.1 update?
Maybe that's different from this issue. In my case, it was worse than NC 19.0.0. The probability of office files being corrupted and unable to be opened has been greatly increased. WebDAV in NC19 is very dangerous.

**Comment by stephenitpro** [comment]
> Maybe that's different from this issue. In my case, it was worse than NC 19.0.0. The probability of office files being corrupted and unable to be opened has been greatly increased. WebDAV in NC19 is very dangerous.

You upgraded to 19.0.1?

**Comment by bbolokofsky** [comment]
After upgrading one of our installs from 19.0 to 19.01. It seems to have solved the problem for at least mountain duck, windows WebDAV and Collabora.  We will be doing more extensive testing over the next few days.

**Comment by stephenitpro** [comment]
> After upgrading one of our installs from 19.0 to 19.01. It seems to have solved the problem for at least mountain duck, windows WebDAV and Collabora. We will be doing more extensive testing over the next few days.

Are you running it as a Docker container or on a bare host? I am watching the issues closely before I upgrade our NC19 instance which requires a lot of fine tuning for Nginx, Mariadb, and php-fpm.  We are using Raidrrive as our freeware webdav Win 7/10 client but I too need to test Mountain Duck for MacOS clients.

**Comment by theoneandonly-vector** [comment]
is this the same issue?:
https://github.com/nextcloud/server/issues/3056

**Comment by stephenitpro** [comment]
> is this the same issue?:
> #3056

Seems like it but really hard to know 100% due to the varying types of installations available.

**Comment by biware-repo** [comment]
> is this the same issue?:
> #3056

It is not the same. At the beginning of this, is written, files on physical storage have proper size. The problem is in updating of database where oc_filecache has 0 in field named size.

**Comment by julieni** [comment]
Will 19.0.1 be used on try.nextcloud.com ? If yes, when is it excepted. I'll try the same tests to see if files are still getting corrupted due to wrong size being cached

**Comment by stephenitpro** [comment]
So far I'm seeing better webdav results from my clients Mountain Duck (MacOS) and Raidrive (Windows)

**Comment by julieni** [comment]
Hi,

is try.nextcloud.com updated to 19.0.1 ? it seems file's size / time reported via webdav are Ok now.

> $ echo "123" > test.txt
> $ ls -al test.txt 
> -rwx------ 1 julien users 4 22 juil. 17:41 test.txt

> $ echo "123456" > test.txt
> $ ls -al test.txt 
> -rwx------ 1 julien users 7 22 juil. 17:43 test.txt

> $ echo "1234" > test.txt
> $ ls -al test.txt 
> -rwx------ 1 julien users 5 22 juil. 17:46 test.txt

Will try to update my own instances to check.

Julien

**Comment by theoneandonly-vector** [comment]
I installed the update on 2 Instances and it fixed the issue on both.

**Comment by theoneandonly-vector** [comment]
I got another problem after the update, which might be related to the fix.
(This happens only for .mkv files as of now) also not for all of them but for many.
they will report a negative amount of storage used and can't be played anymore. the size on disk is correct, but not so on web or webdav-client.

**Comment by acsfer** [comment]
Everyone: can you confirm the **19.0.1** release fix this?
From my side, i can't reproduce it, either using Cyberduck or Raidrive.

React with 👍 for WORKS
React with 👎 for DOESN'T WORK

**Comment by deajan** [comment]
Doesn't work for me with 19.0.2, see https://github.com/photoprism/photoprism/issues/443

**Comment by mahibi** [comment]
Doesn't work for me with 19.0.2 either. See https://github.com/laurent22/joplin/issues/3350#issuecomment-691494783 for details.

**Comment by JBM888** [comment]
I also have problems with WebDAV as well as the Windows 2.6.5 and 3.0.1 client. Files are either 0 bytes, very small (8 bytes) and a lot of file sync conflicts . Everything was fine until I let the system do an upgrade to NC19.... 
This needs to be addressed  NOW!!! It's more or less a scandal that a version with these flaws was released.  Claiming that one should sign up for support is *NOT* the way to handel such an issue that affect so many not to mention Nextclouds reputation. No one will consider a system so poorly maintained that clearly lack the stability for any serious business use.  Development IS tricky business but serious bug(s) for this long? With "standard" installations like mine?  That's not anything for  any business use....

**Comment by PVince81** [comment]
as far as I can see, the Sabre DAV library (which Nextcloud uses) was supposed to block such uploads with an error instead of letting it go through with 0 bytes: https://github.com/sabre-io/dav/blob/master/lib/DAV/CorePlugin.php#L471

from reading this it seems there is no solution to make it work apart from switching clients or web server, but not sure what web server (or web server settings) would make it work

I've found this article from one of the Sabre DAV authors: https://evertpot.com/260/
So there might be server setups in which it can work.

**Comment by osscombat** [comment]
In my case the same problem using Mountain Duck was caused by the following nginx reverse proxy (NC 19.0.5 was behind it) settings

```
proxy_buffering off;
proxy_request_buffering off;
```
just removed them, and the problem gone.

**Comment by deajan** [comment]
The solution @osscombat provides works for nginx. For Apache, there's so such option and I had to switch back from php-fpm to mod_php in order to get this resolved ;(

**Comment by Kixunil** [comment]
FYI the option was called `fastcgi_request_buffering off;` in my config and removing it helped. Thanks!

For context, I was trying to upload files simply using `curl --netrc -S -T - "$nc_server/remote.php/dav/files/$file_name"`

**Comment by szaimen** [comment]
I suppose this is still happening on NC21.0.3?

**Comment by rfc2822** [comment]
> FYI the option was called `fastcgi_request_buffering off;` in my config and removing it helped. Thanks!

I had the same problem with Nextcloud 22.2.0 and this helped, too. For Apache, it seems to be related to https://www.jeffgeerling.com/blog/2017/apache-fastcgi-proxyfcgi-and-empty-post-bodies-chunked-transfer.

Because `fastcgi_request_buffering off;` is in the Nextcloud manual: https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx, I suggest to

* re-open this issue,
* change it to a documentation issue,
* adapt the nginx setup documentation in Nextcloud manual (https://docs.nextcloud.com/server/19/admin_manual/installation/nginx.html#nextcloud-in-the-webroot-of-nginx), specifically to remove the `fastcgi_request_buffering off;` line.

**Comment by schiessle** [comment]
Seems like a real issue, so I re-open the ticket. Is the update of the documentation enough? Any drawbacks / side effects  if we remove the `fastcgi_request_buffering off;` ? And what would be the solution for Apache?

**Comment by grote** [comment]
> What would be the solution for Apache?

I am also curious about this.

https://www.jeffgeerling.com/blog/2017/apache-fastcgi-proxyfcgi-and-empty-post-bodies-chunked-transfer says:

>  If you need to handle chunked content transfer, don't rely on Apache with mod_proxy_fcgi or mod_fastcgi

So I need to go back to plain `mod_php`?

I tried this and it does indeed fix the issue.

**Comment by deajan** [comment]
Can confirm that using `mod_php` fixed the issue, and indeed we needed to use `mpm_prefork`.
No other solution worked for me. If anybody has a good solution that works with `php-fpm` and `apache`, I'd love to hear about it ;)

**Comment by rfc2822** [comment]
I think this is still a problem.

**Comment by AykutCevik** [comment]
It is still a problem, I get this with NC 28.0.3 and am uploading files via Mountain Duck (Version 4.10.3 (19145)) on MacOS.

**Comment by Migsi** [comment]
Just encountered this on Andorid, using DAVx5 to upload a SeedVault backup. All files are created as 0 Byte, in the end the backup fails with the file structure being there, but no data in those files. The files are 0 Bytes on storage as well. I'm using external storage on SMB. Works fine with all other connections (Gnome goa, Nextcloud Sync Client, Windows WebDAV client).

**Comment by Kixunil** [comment]
> My Nginx server has `fastcgi_request_buffering off;` set, so that shouldn't cause the issue here.

That is actually what *causes* the issue.

**Comment by AykutCevik** [comment]
I still have the issue with the following docker-compose setup as you have here: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/with-nginx-proxy/mariadb/fpm/docker-compose.yml

As well as after adding
```
proxy_buffering off;
proxy_request_buffering off;
fastcgi_request_buffering off;
```
to both, `web` and `proxy` image. 
I mounted my Nextcloud instance via MountainDuck on MacOS. My Nextcloud version is `29.0.4`.

**Comment by Kixunil** [comment]
@AykutCevik you need to **remove** those lines, not add them.

**Comment by AykutCevik** [comment]
Oh sorry, was reading it totally wrong🙈
At least can confirm that it works now, thank you very much!
