### ISSUE TITLE
Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328 (Nextcloud 19.0.0)

### ISSUE THREAD

**Issue by sebalis** [nextcloud/server#21325]
### Steps to reproduce
1. Install NC 19 (using official Docker images) and use it
2. Messages appear in log at regular intervals

### Expected behaviour
No errors

### Actual behaviour
I can observe a cluster of log messages (some 20 at times divisible by 5 minutes) each saying “Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328”

This looks very simitar to issue #21236 but I didn’t find one that is related to NC 19, or indeed one that is still open. Note that the line number is offset by one compared to that previous issue.

### Server configuration

**Operating system:**
Server: Ubuntu 18, Docker image: Alpine 3.11

**Web server:**
nginx from official Docker image nextcloud:fpm-alpine

**Database:**
mariadb (official Docker image)

**PHP version:**
7.4.6

**Nextcloud version:** (see Nextcloud admin page)
19.0.0.12

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 18 through docker-compose pull and docker-compose up -d

**Where did you install Nextcloud from:**
official Docker images

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
- accessibility: 1.5.0
- activity: 2.12.0
- bookmarks: 3.1.1
- bruteforcesettings: 1.6.0
- calendar: 2.0.3
- cloud_federation_api: 1.2.0
- comments: 1.9.0
- contacts: 3.3.0
- contactsinteraction: 1.0.0
- dav: 1.15.0
- deck: 1.0.2
- federatedfilesharing: 1.9.0
- federation: 1.9.0
- files: 1.14.0
- files_pdfviewer: 1.8.0
- files_rightclick: 0.16.0
- files_sharing: 1.11.0
- files_trashbin: 1.9.0
- files_versions: 1.12.0
- files_videoplayer: 1.8.0
- firstrunwizard: 2.8.0
- groupfolders: 6.0.6
- logreader: 2.4.0
- lookup_server_connector: 1.7.0
- nextcloud_announcements: 1.8.0
- notifications: 2.7.0
- oauth2: 1.7.0
- password_policy: 1.9.1
- photos: 1.1.0
- privacy: 1.3.0
- provisioning_api: 1.9.0
- recommendations: 0.7.0
- richdocuments: 3.7.0
- serverinfo: 1.9.0
- settings: 1.1.0
- sharebymail: 1.9.0
- support: 1.2.1
- survey_client: 1.7.0
- systemtags: 1.9.0
- text: 3.0.1
- theming: 1.10.0
- twofactor_backupcodes: 1.8.0
- updatenotification: 1.9.0
- viewer: 1.3.0
- workflowengine: 2.1.0
Disabled:
- admin_audit
- encryption
- files_external
- user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud-intern.digitalcourage.de"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED",
            "HTTP_FORWARDED_FOR"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/cloud-intern.digitalcourage.de",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_smtpport": "25",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:**
local only

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
none

### Client configuration
**Browser:**
Firefox

**Operating system:**
Linux

#### Web server error log
The nginx logs in the web server Docker container are empty.

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
{"reqId":"jyRsnATrX7PZWCM4soYv","level":3,"time":"2020-06-08T19:35:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","ur
l":"--","message":"Trying to access array offset on value of type int at /var/www/html/lib/private/Files/Node/Node.php#328","userAge
nt":"--","version":"19.0.0.12"}
</details>

#### Browser log
omtted as this seems to be a server-side issue

**Comment by kesselb** [comment]
Mind to apply https://github.com/nextcloud/server/issues/19010#issuecomment-576683752 and share the stack trace?

**Comment by sebalis** [comment]
I applied the patch, will report tomorrow.

**Comment by sebalis** [comment]
Here is one such stack trace:

```
[no app in context] Error: LogicException: $path is an integer: 10 at <<closure>>

 0. /var/www/html/lib/private/Files/Node/Folder.php line 60
    OC\Files\Node\Node->isValidPath(10)
 1. /var/www/html/lib/private/Files/Node/Folder.php line 138
    OC\Files\Node\Folder->getFullPath(10)
 2. <<closure>>
    OC\Files\Node\Folder->get(10)
 3. /var/www/html/custom_apps/groupfolders/lib/Helper/LazyFolder.php line 72
    call_user_func_array([OC\Files\Node\Folder {},"get"], [10])
 4. /var/www/html/custom_apps/groupfolders/lib/Helper/LazyFolder.php line 144
    OCA\GroupFolders\Helper\LazyFolder->__call("get", [10])
 5. /var/www/html/custom_apps/groupfolders/lib/Mount/MountProvider.php line 184
    OCA\GroupFolders\Helper\LazyFolder->get(10)
 6. /var/www/html/custom_apps/groupfolders/lib/Mount/MountProvider.php line 124
    OCA\GroupFolders\Mount\MountProvider->getFolder(10)
 7. /var/www/html/custom_apps/groupfolders/lib/Versions/VersionsBackend.php line 160
    OCA\GroupFolders\Mount\MountProvider->getMount(10, "/dummyuser/files/IT-Administration", {IT-Administration: 31}, "-3")
 8. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 62
    OCA\GroupFolders\Versions\VersionsBackend->getAllVersionedFiles({id: 10,mount_po ... e})
 9. /var/www/html/custom_apps/groupfolders/lib/Versions/GroupVersionsExpireManager.php line 57
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireFolder({id: 10,mount_po ... e})
10. /var/www/html/custom_apps/groupfolders/lib/BackgroundJob/ExpireGroupVersions.php line 40
    OCA\GroupFolders\Versions\GroupVersionsExpireManager->expireAll()
11. /var/www/html/lib/private/BackgroundJob/Job.php line 62
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
12. /var/www/html/lib/private/BackgroundJob/TimedJob.php line 57
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
13. /var/www/html/cron.php line 126
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-06-09T08:35:01+00:00
```

I think I can guess what’s happening here. The string “IT-Administration”, I am happy to disclose, is the name of one of our group folders. It’s folder_id in the database is 10 and that is of course also the name of its root directory in the file system. I am getting one such error for every group folder (just one, whether they have content or not). That ID or path name probably started out as a string and then got converted to an integer automagically.

Strangely these groups of errors seem to appear every 65 minutes. The Nextcloud cron job is set to run every 5 minutes.

**Comment by kesselb** [comment]
> 11. /var/www/html/lib/private/BackgroundJob/Job.php line 62
    OCA\GroupFolders\BackgroundJob\ExpireGroupVersions->run(null)
> 12. /var/www/html/lib/private/BackgroundJob/TimedJob.php line 57
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})

https://github.com/nextcloud/groupfolders/issues/907 a patch is already merged. I hope to see a release soon but I'm not familiar with release process of group folder app.

> Strangely these groups of errors seem to appear every 65 minutes. The Nextcloud cron job is set to run every 5 minutes.

The job to expire group folder versions is scheduled to run every ~60 minutes.

**Comment by sebalis** [comment]
Glad to be of service …

**Comment by kesselb** [comment]
@sebalis Thanks for your help :+1:
