### ISSUE TITLE
Disable video player  is ineffective

### ISSUE THREAD

**Issue by fredbcode** [nextcloud/server#21323]
Hello,

With Nextcloud 19 (and maybe before) disable the video plug-in is ineffective
There is no way to directly download the video with a player like vlc

The html5 player is very limited and useless in many cases (large video, mkv, etc) , I think that an "open with" choice could be great, with nextcloud android client there is a choice, unfortunately you must select your player each time but something similar could be a first step  

At least remove the video plugin choice enable/disable because It's not understandable that there is no effect at all

How to reproduce: In netxcloud add-on interface disable "Video Player", after that click to video and the player still present (with his limitations for me) 

Expected behaviour: The video file should be downloaded and opened by a local player linked to browser (vlc for example) or, if this a technical limitation, the choice to disable the add-on removed

**Comment by kesselb** [comment]
Added "needs info" label due the missing issue template. I understand there are probably no logs to share and other setup related information not relevant but **ADD** (by editing your issue) at least some information how to reproduce the issue, the expected behaviour and the actual behaviour.

**Comment by fredbcode** [comment]
How to reproduce added and yes there is no log , thanks

**Comment by kesselb** [comment]
Mind to add a screenshot? I suspect your browser is opening the video. We could probably send a download header if no viewer for file is enabled. For most people the browser's default behaviour should be fine.

**Comment by fredbcode** [comment]
Plug-in disable (sorry French language)

![image](https://user-images.githubusercontent.com/5287473/84072691-df6cdf00-a9cf-11ea-8f1b-9aeda8b4afbb.png)

But js video player still working
And more annoying for me, many videos are unusable, for example all mkv files, but also large files (4k), etc
![image](https://user-images.githubusercontent.com/5287473/84073446-1a234700-a9d1-11ea-9c2e-486e428fbf00.png)

![image](https://user-images.githubusercontent.com/5287473/84073083-73d74180-a9d0-11ea-82c5-d65bf954318c.png)
![image](https://user-images.githubusercontent.com/5287473/84073249-b9940a00-a9d0-11ea-835a-4adfd4c341b9.png)

It's better with the android application I can use "cast" (diffuser in French) and chose vlc,  with this player all my videos works !
Still, I need to chose cast each time because by default the player is from nextcloud

FI: If I enable "video player" add-on there is no difference at all

**Comment by kesselb** [comment]
cc @nextcloud/viewer

**Comment by kesselb** [comment]
cc @skjnldsv @juliushaertl

**Comment by Walterfilms** [comment]
There are 2 different players :

"video player app" for public share of single video
"viewer" for playing videos inside your instance (logged in) and also when using a public share of a folder containing videos.

**Comment by fredbcode** [comment]
I have no "viewer" except "pdf viewer"

But there is "photos" I will try to disable this plugin and post the result

**Comment by fredbcode** [comment]
I confirm no viewer I could disable, and photo seems also unrelated

**Comment by Walterfilms** [comment]
hmm.. i don't know why but viewer app is not visible into the web UI but you can see it in your nextcloud/apps folder.

**Comment by fredbcode** [comment]
Great, video opened with vlc now, works like a charm !

So there is two"bugs" here

1 - we can't disable viewer with ui 
2 - Disable viewer is also related with pictures, an only video option is needed 

Thanks

**Comment by skjnldsv** [comment]
> hmm.. i don't know why but viewer app is not visible into the web UI but you can see it in your nextcloud/apps folder.

because it's a built-in app that cannot be disabled :)

**Comment by skjnldsv** [comment]
> It's better with the android application I can use "cast" (diffuser in French) and chose vlc, like this all my videos works !
> Still, I need to chose cast each time because by default the player is from nextcloud

You should be able to right click the video and cast, no?

**Comment by fredbcode** [comment]
Only with Android app and at each time, no choice save

**Comment by fredbcode** [comment]
Arg, only "cast" in andoid works well

Now without "viewer" the video is well downloaded, but entirely before starting ...

**Comment by juliushaertl** [comment]
> Expected behaviour: The video file should be downloaded and opened by a local player linked to browser (vlc for example) or, if this a technical limitation, the choice to disable the add-on removed

I don't think that this is something we should do or offer to disable as showing the video is what most users would expect to happen. You can always download the file instead of viewing it from the file context menu.

![image](https://user-images.githubusercontent.com/3404133/84644292-44a85f00-aeff-11ea-9859-4393ca5e14b7.png)

**Comment by fredbcode** [comment]
Ok, maybe the "cast' option on Android could be added to the browser version ? And better with an option to use this by default

It works very very well, this option is the best choice in my opinion

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by fredbcode** [comment]
![Screenshot_2020-06-15-13-11-35-35_06ea656a9ba653ff96746f477f32d0f9](https://user-images.githubusercontent.com/5287473/84651243-e0d76380-af09-11ea-89ec-d47075ec231b.png)


I mean this option "Diffuser avec" in French

**Comment by fouram** [comment]
> I don't think that this is something we should do or offer to disable as showing the video is what most users would expect to happen. You can always download the file instead of viewing it from the file context menu.

This is a problem when I have a directory of VODs from a Twitch stream, and each of them is 10GB and when the Viewer opens, it takes an extremely long time preloading all these videos just to support the forward and back arrows, and all the user wanted was to preview the one file.

Once the player is open, we can move next and previous almost instantly, which is pretty cool, but ultimately useless to us, since it took so long to open the player in the first place. I would much rather be able to double click from the list and get the Viewer to open in <5 seconds.

If we can't disable it, it would be nice if we could at least configure it. For my use case, I have no need for allowing my users (in those specific directories) to use the forward or back chevrons and therefore I have no need for the Viewer to force them to wait for 600 video files to partially preload. Simply having a way to disable the preloading (could even allow us to set exceptions per-directory, or provide a threshold like only-preload-X-items) would be enough to make Viewer useful to me. As it is, it makes NextCloud for hosting a VOD archive a terrible experience, and quite unnecessarily at that.

**Comment by normen** [comment]
+1 for an option to disable the player. Especially with large video files it places an unnecessary strain on the server on my instance.

**Comment by Mrkev22** [comment]
Such a basic function and they missed it. Nextcloud is bugy as shit and you can even turn off these function.

**Comment by 911realdeb** [comment]
try this : 

1.Copy alias :  
 
`sudo cp /usr/share/nginx/nextcloud/resources/config/mimetypealiases.dist.json /usr/share/nginx/nextcloud/config/mimetypealiases.json`

2.Copy mapping : 

`sudo cp /usr/share/nginx/nextcloud/resources/config/mimetypemapping.dist.json /usr/share/nginx/nextcloud/config/mimetypemapping.json`

3. Update mimestype:  

`sudo -u www-data php /usr/share/nginx/nextcloud/occ maintenance:mimetype:update-js`

after restart web server : 

`sudo service nginx restart`

4. Edit and change mapping : 

`sudo nano /usr/share/nginx/nextcloud/config/mimetypemapping.json`

you want directly download ex :   

`"mkv": ["video/x-matroska"],`

for

`"mkv": ["application/octet-stream"],`
 
avi mp4 etc ...

5. Update existing files mapping :

`sudo -u www-data php /usr/share/nginx/nextcloud/occ files:scan --all`

6. refresh user browser 

et voila ....

**Comment by tomasz-lasko** [comment]
> I don't think that this is something we should do or offer to disable as showing the video is what most users would expect to happen. You can always download the file instead of viewing it from the file context menu.

@juliushaertl 

I don't agree, there is also a need to disable player in cases of specific resource limits or constraints, and having a lot of huge video files, then even allowing people to play these huuuge files in browser (either when logged in or from a shared public link) causes overloading of server. But apart from this huge-video-playback, all other functions are working OK on the server, meaning the server behaves well. 

Even generation of thumbnail previews don't overload our server (and we have a lot of images and videos), but already **there even exists an option to disable thumbnail preview generation** for the very same performance reasons: https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/previews_configuration.html#disabling-previews

Can it be that I am the only one, some crazy lunatic, that experiences a big hit from huge video playback (much much much bigger hit than from generating thumbnail previews)? If I'm not crazy, then kindly please at least talk about this within nextcloud team, thank you.

**Comment by normen** [comment]
> Can it be that I am the only one, some crazy lunatic, that experiences a big hit from huge video playback (much much much bigger hit than from generating thumbnail previews)? If I'm not crazy, then kindly please at least talk about this within nextcloud team, thank you.

Nah, I see the same, especially with large videos (>1GB)
