### ISSUE TITLE
version/update inconsistency

### ISSUE THREAD

**Issue by BangL** [nextcloud/server#21331]
![nextcloud_updates](https://user-images.githubusercontent.com/551400/84113230-81b9b080-aa2a-11ea-9040-794e2fdee799.png)

**Comment by kesselb** [comment]
Rollout of 18.0.5 has been stopped due a regression. You got the notification but the update is not longer available. 

Please use https://help.nextcloud.com for questions the next time.

cc @nextcloud/server-triage does it make sense to clear the notification for such a case? Seems rather edgy to me.

**Comment by BangL** [comment]
ok, thanks for clarification

**Comment by rullzer** [comment]
> cc @nextcloud/server-triage does it make sense to clear the notification for such a case? Seems rather edgy to me.

yeah... I mean in theory sure. In practice this is indeed an edge case.
