### ISSUE TITLE
upload.part" is locked

### ISSUE THREAD

**Issue by 745719408** [nextcloud/server#21330]
For help: When I upload a large file that exceeds 3G to 4G, I report: upload.part" is locked Report that exceeds 10G: 502, what should I do?

**Comment by Nils160988** [comment]
You should use the forum for questions? ;)

**Comment by 745719408** [comment]
> 你应该使用论坛提问吗？;)

I couldn't log in to the forum, and I didn't find a solution. Does anyone know how to solve it?

**Comment by Nils160988** [comment]
Please use the issue template if you want to report an issue and use the search function to check for similar issues in advance.
