### ISSUE TITLE
Update failed: Rebuild font library 

### ISSUE THREAD

**Issue by RayFielding** [nextcloud/server#21348]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

I was prompted to do the above update. It downloaded ok and I get to the "Start Update" screen but when I try to run the update it fails. I have tried to attatch the screen shots although I;m not sure they have come through properly.

The log is as follows:

Exception: sh: ../../tools/allfontsgen: not found

Detailed logs 
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
Repair step: Rebuild font library
Exception: sh: ../../tools/allfontsgen: not found

Please help. I am stuck looping to these two screens and cannot seem to get and further.

<img width="571" alt="1" src="https://user-images.githubusercontent.com/66694271/84189947-fc67e780-aa8d-11ea-9bbf-5246f137049a.png">
<img width="575" alt="2" src="https://user-images.githubusercontent.com/66694271/84189950-fd007e00-aa8d-11ea-9c0d-95b76f973657.png">

**Comment by DCPDad** [comment]
Confirmed: I just got the exact same error as above.

**Comment by mattes0303** [comment]
Same problem.
Never "migrating from ownCloud" 
<img width="809" alt="Screenshot at Jun 09 23-03-05" src="https://user-images.githubusercontent.com/18162746/84199463-81123000-aaa5-11ea-9bc3-7f24cbb3882d.png">

**Comment by thatsnasty** [comment]
Yep, exact same for me.

**Comment by kesselb** [comment]
Is the issue report at the right repository: https://github.com/nextcloud/documentserver_community/issues/145

https://github.com/nextcloud/documentserver_community/blob/6d011650e6718d7232c155df95e9202ef35c8c69/lib/Migration/RebuildFonts.php#L46

Is the code in question. It seems some dependencies are missing for a repair step. I would comment the line and run the upgrade again.

**Comment by fNCZsp5AV5n8d5** [comment]
i had this issue yesterday. (it was on 18.0.05) https://github.com/nextcloud/server/issues/21329

**Comment by gerath1045** [comment]
> 
> 
> Same problem.
> Never "migrating from ownCloud"
> <img alt="Screenshot at Jun 09 23-03-05" width="809" src="https://user-images.githubusercontent.com/18162746/84199463-81123000-aaa5-11ea-9bc3-7f24cbb3882d.png">

i have the same issue no fix.. has anyone found a fix for this issue

**Comment by kesselb** [comment]
Just upgraded from 18.0.5 to 18.0.6 and had no issues with the `documentserver_community` app. I would like to ask everyone to add (edit your existing comment - don't add a new one) the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md).

And in addition:
1. Does `apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/tools/allfontsgen` exists (replace apps with your app directory)
2. `ldd apps/documentserver_community/3rdparty/onlyoffice/documentserver/server/tools/allfontsgen`

**Comment by Timeforsmilin** [comment]
I have the same issue with nextCloud 18.03 on a Thecus N5550 running OS7.

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Repair step: Rebuild font library

Exception: ../../tools/allfontsgen: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libgraphics.so) ../../tools/allfontsgen: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libkernel.so) ../../tools/allfontsgen: /lib64/libc.so.6: version `GLIBC_2.17' not found (required by ./libkernel.so) ../../tools/allfontsgen: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libUnicodeConverter.so) ../../tools/allfontsgen: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./libicuuc.so.58)

The update was unsuccessful. Please report this issue to the Nextcloud community.
👍

**Comment by gacpac** [comment]
Yep I'm having the same problem. 

But how to I cancel now to upgrade my nextcloud instance?

**Comment by kesselb** [comment]
@gacpac https://github.com/nextcloud/server/issues/21348#issuecomment-641615174

**Comment by kesselb** [comment]
I'm closing this report in favour of https://github.com/nextcloud/documentserver_community/issues/145.
