### ISSUE TITLE
Extend API meta for sharing to show expected password length

### ISSUE THREAD

**Issue by ochorocho** [nextcloud/server#21353]
I wrote a little plugin for [Kap Screenrecorder](https://getkap.co/). It uploads the created file to Nextcloud and creates a share link (with and without password) using the API.

Currently i get "Password needs to be at least 32 characters long" response when a share link was not created. It could work to regex the number from the string and trigger it again. But this does not seem like a good solution.

https://github.com/ochorocho/kap-nextcloud/issues/5#issuecomment-641306516

By default i'm setting a 8 char long passwrd. But this can be configured within nextcloud.

Woudln't it make sense to expose this setting somehow in the API so external software can act according to these settings?

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by ochorocho** [comment]
I'm just setting long passwords by default.
