### ISSUE TITLE
Document changes made to the Test class for NC11

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#2135]
There have been breaking changes made to the Test class and devs need:
1. To be made aware of it
1. Ideally to be told how to adapt their code

-----
cc @rullzer @nickvergessen @LukasReschke , but feel free to share with others ;)

**Comment by oparoz** [comment]
Sample of the breakage which happens after the changes:

```
[PHPUnit_Framework_Exception]                                                                                                                  
  Declaration of Test\TestCase::onNotSuccessfulTest($e) should be compatible with PHPUnit_Framework_TestCase::onNotSuccessfulTest(Exception $e)  
```

**Comment by nickvergessen** [comment]
The actual change is that since we now require php 5.6+ we also require phpunit 5+
Seems like travis doesn't have this: `Powered by PHPUnit 4.8.26`

**Comment by oparoz** [comment]
Actually, that's the exact version being used:

```
3.48s$ php vendor/bin/codecept run acceptance --env firefox
Codeception PHP Testing Framework v2.2.1
Powered by PHPUnit 4.8.26 by Sebastian Bergmann and contributors.
                                                                                                                                                 
  [PHPUnit_Framework_Exception]                                                                                                                  
  Declaration of Test\TestCase::onNotSuccessfulTest($e) should be compatible with PHPUnit_Framework_TestCase::onNotSuccessfulTest(Exception $e)
```

**Comment by oparoz** [comment]
OK, after re-reading this, I guess it's a problem with PHPUnit which will never be fixed. 

>sebastianbergmann commented on 12 Feb
I do not support PHPUnit 4.8 on PHP 7, as is clearly stated on the website.

Since PHPUnit 5 still support 5.6. There should be a not somewhere about that change so that all app devs can update their Travis.

**Comment by nickvergessen** [comment]
I added 100 lines of magic to fix it: https://github.com/nextcloud/server/pull/2137

**Comment by oparoz** [comment]
Great, thanks!. Let's close this then if that was the only problem linked to PHP 5.6 and testing.
