### ISSUE TITLE
Enhancement of Projects

### ISSUE THREAD

**Issue by Clementine46** [nextcloud/server#21359]
### The existing

The current flow to add an item to a project seems quite confusing to me.
When sharing an item, in the side menu you can:

- Add your item to an existing project (by typing its name)
- Link your item to another item, which automatically creates a new project with the name of your first item. This action is unexpected and not the most practical

### My suggestions

I tried to make a simpler flow while still keeping the existing possible actions. There are two different user flows with slight differences so that everyone can choose which one is best in their opinion.

I made paper mockups and used the Marvel app to make them interactive.
If you do not know where to click, just click anywhere and a blue frame will appear around the clickable zone.

**First user flow**

1. Share the fourth file
2. Add to a project
3. Create a new project (a new name will appear)
4. Confirm your project's name (your new project appears at the end)
5. Click on the meatball menu (horizontal three dots)
6. Link to a file
7. Choose the second file
8. Confirm (the file is now linked to your new project)

Here is the link to try it out: https://marvelapp.com/237i8946/screen/70095966

**Second user flow** (essentially the same except for the meatball menu)

1. Share the fourth file
2. Add to a project
3. Create a new project (a new name will appear)
4. Confirm your project's name (your new project appears at the end)
5.  **Click on the meatball menu** (horizontal three dots)
6. **Add an item**
7. **Link to a file**
8. Choose the second file
9. Confirm (the file is now linked to your new project)

Here is the link: https://marvelapp.com/237i8946/screen/70096063

The reason why I made two versions is because the projects are meant to include more things in the future, like calendars. So the first option means the menu will eventually get longer. The second option allows to keep a short menu but adds one click to the process.

### What I changed

- The first thing I did was to remove the possibility to link an item to another item right after clicking "add to a project". In my opinion, it's unclear and confusing. Instead, I decided to present existing projects (the three most recent ones are shown) and the option to create a new project with your selected file in it.

![exemple 1](https://user-images.githubusercontent.com/50834537/84194441-52905700-aa9d-11ea-85ee-b27d62f7b80a.jpg)

- In the meatball menu of the project, I added the "add an item" option. Essentially I moved the possibility to link an item directly into the project's options.

![exemple 2](https://user-images.githubusercontent.com/50834537/84194258-0ba26180-aa9d-11ea-8200-16152cf30322.jpg)

Feedbacks are welcome :)

**Comment by Spartachetto** [comment]
I recently created a project in Nextcloud 18 and IMHO both of Clementine46 user flows are more intuitive than the existing one.

In spite of knowing well the logic behind projects, it was true for me what stated: __The first thing I did was to remove the possibility to link an item to another item right after clicking "add to a project". In my opinion, it's unclear and confusing.__

**Comment by skjnldsv** [comment]
Thanks for diving into this @Clementine46 !
It would be a very nice enhancement yes!

I'm still concerned about the length of the sharing tab though.
On some files on our cloud, it's already super long, and I am afraid to see those get pushed down the list and ending being not discoverable :/

**Comment by Clementine46** [comment]
@skjnldsv That is true. I believe projects should have a separate tab but there are already a lot. Maybe some tabs could be united to make some room for a new one ?

**Comment by ostasevych** [comment]
I also see that there are a lot of clicking activities, plus, sometimes these smaller screens are overlapped with other apps or even goes beyond the screen. Due to some bugs with the code translated strings may look even more ugly.

What do you mind if to rethink the whole concept of projects, which may be not so clear for usual customers, but very productive for some organisations, which are specifically project oriented (in particular NGOs, ITs, developers etc)?

In this case we may just add the Projects as an additional app, like Talk, which extends the functionality? 

With this approach, all workflow starts from the creation of the project entity with further linking folders and files, decks, boards and cards, calendar events and tasks, contacts, conversations, mail messages, photos, map markers, polls, forms etc.  

Optionally, it may be a part of the Deck functionality, however Kanban is not the only style of project management, there are other views, eg Gantt, which are really missing. So, I am in favour of creation of the specific application or transforming the Deck app by extending it with other features.

**Comment by jancborchardt** [comment]
> > I'm still concerned about the length of the sharing tab though.
> > On some files on our cloud, it's already super long, and I am afraid to see those get pushed down the list and ending being not discoverable :/
>
> That is true. I believe projects should have a separate tab but there are already a lot. Maybe some tabs could be united to make some room for a new one ?

Yes. As per the sidebar spec, we should have 3 tabs:
- **Activity:** For any chronological info like activity, comments, versions etc.
- **Sharing:** Sharing with users, email and via link
- **Details:** Things neither chronological nor related to sharing. Projects would belong here.

**Comment by ostasevych** [comment]
> > > I'm still concerned about the length of the sharing tab though.
> > > On some files on our cloud, it's already super long, and I am afraid to see those get pushed down the list and ending being not discoverable :/
> > 
> > 
> > That is true. I believe projects should have a separate tab but there are already a lot. Maybe some tabs could be united to make some room for a new one ?
> 
> Yes. As per the sidebar spec, we should have 3 tabs:
> 
> * **Activity:** For any chronological info like activity, comments, versions etc.
> * **Sharing:** Sharing with users, email and via link
> * **Details:** Things neither chronological nor related to sharing. Projects would belong here.

There should be a special view for Projects, where you may see all the links in the form of the tree. 
Another moment, if I am linking folder, does that mean that all subfolders are also included?..
A lot of questions.

**Comment by Spartachetto** [comment]
If I get well the suggestions, several times the proposal is to have 
1. A part of the sidebar about projects
2. A specific view about projects (maybe in the new dashboard...!)

@jancborchardt , @skjnldsv , @juliushaertl do you think that the point 2 is interesting?

**Comment by jancborchardt** [comment]
Regarding the part of the sidebar about projects – as said above there should be a specific tab:

> 3. Details: Things neither chronological nor related to sharing. Projects would belong here.

And the specific view for projects is related to the Dashboard spec: https://github.com/nextcloud/server/issues/20930

**Comment by ma12-co** [comment]
Very nice work, I have only one remark about the plus icon on the "Add to a project" element:

>![additional suggestions 3](https://user-images.githubusercontent.com/50834537/84288325-51b10100-ab41-11ea-8210-2d6d8c532fae.jpg)

Since the whole element is clickable this is a bit confusing, as it would be a button on top of button, both triggering the same action. I would put the plus instead of the projects icon or omit it.

**Comment by ostasevych** [comment]
My another suggestion is to add additional UI Projects on the level of Activity, Comments, Sharing, Chat to avoid confusing. Plus, to put away this functionality in a separate app, and add the dashboard, as it was mentioned above.

**Comment by Clementine46** [comment]
@ma12-co The reason I made this change is because the whole element shouldn't be clickable in my opinion. You might be used to it, but it's confusing for new users since it's not consistent with the rest. All the others options have a clickable icon on the right, the rest isn't clickable. So having the entire project option as clickable, without an icon, seems illogical and confusing to me.

**Comment by jancborchardt** [comment]
> it's confusing for new users since it's not consistent with the rest. All the others options have a clickable icon on the right, the rest isn't clickable.

Actually, for the other entries it should be the same: At least the ones which only have one action, there’s no reason to not have the entire row clickable instead of only the icon.

**Comment by Andreas-Kainz** [comment]
As the chat sidebar Tab Link to share where is also projects, what if the chat sidebar Tab was replaced by project tab where you can  you files not only to chat, also to deck, dash, file AND chat.

So project sidebar Tab will be way more flexible than chat only.

**Comment by jancborchardt** [comment]
After some further analysis and discussion, we will probably go with a very much simplified approach of automatically showing "related resources" as specified in https://github.com/nextcloud/server/issues/28320
