### ISSUE TITLE
Robots Noindex Config

### ISSUE THREAD

**Issue by tkirl** [nextcloud/server#21363]
Hi,  as I did not find a related feature request, I am opening this one. Sorry if I missed it. 

### Issue
As you may have noticed Google-Search-Engine dropped support of robots.txt ([https://webmasters.googleblog.com/2019/07/a-note-on-unsupported-rules-in-robotstxt.html?m=1](https://webmasters.googleblog.com/2019/07/a-note-on-unsupported-rules-in-robotstxt.html?m=1)), recommending noindex in meta-tag or X-Robots-tag ([https://developers.google.com/search/reference/robots_meta_tag](https://developers.google.com/search/reference/robots_meta_tag)) to hide pages [https://support.google.com/webmasters/answer/6062608?hl=en](https://support.google.com/webmasters/answer/6062608?hl=en)). I also experienced similar behavior of other search engines, too.

### Relevance
This is relevant for many Nextcloud-installations, that do not want do be indexed at all. And especially those instances dealing with many users, that are **publicly** sharing files, polls, calendars etc., but do not know, their content will be indexed by search engines.

### Solution
Certainly this is fixable by simply adding the tag-code to the header. But this would have to be redone with future updates and reimplementation will most likely be forgotten. So I would love to see the functionality to edit noindex via meta or X-Robots-tag in a configuration-file.

Please take this feature into consideration. What do you think about this idea?

**Comment by blizzz** [comment]
@tkirl perhaps you can have a look at the layout.* files in core/templates, add the noindex meta tag and create a pull request here?

**Comment by kesselb** [comment]
@nickvergessen suggested yesterday (in the community call) to write an app for. If we add that flag by default we need a way to disable it so a app might be easier.

**Comment by nickvergessen** [comment]
Yeah, a simple app that:

1. Writes the `robots.txt`
2. Sets the meta tag `robots` to `noindex`
3. Sets the header `X-Robots-Tag` to `NoIndex`

**Comment by blizzz** [comment]
> Writes the robots.txt

Then we need to remove the default one. And have to have this app shipped to continue using the default config (which is to block anything from being indexed).

**Comment by kesselb** [comment]
Good point. I missed that there is already a robots.txt 🙈 If that is already the default we can just set it as header or meta tag.

**Comment by nickvergessen** [comment]
Same here, I was not aware of the shipped file. So yea then let's "fix" it by adding the meta tag and header.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
