### ISSUE TITLE
Share a single file as guest from a shared folder

### ISSUE THREAD

**Issue by arteteco** [nextcloud/server#21361]
Hello everyone,
If I share a folder with someone, with editing and downloading permission, this someone may want to share a single file with someone else without giving the link to the folder.
This can be done for most files by opening them in another window with the central mouse click and sharing that URL. I haven't found an easy way to do it without a central mouse click.
Clicking on the "share file" that open with the right clic should give that link, while atm it does nothing

**Example:** 
* I share [this folder](https://cloud.qoto.org/s/BD4reAfweBn2A7i)
* The guest only wants to share the pdf link in there
* If I open it with the central mouse wheel I have a [specific link](https://cloud.qoto.org/s/BD4reAfweBn2A7i?path=%2F&openfile=63506)
* This is what I would expect from the "Share File" option with the right click, which doesn't do anything

Am I missing something?

Thanks!

**Comment by mayank1470** [comment]
Is this happening with PDF only?

**Comment by arteteco** [comment]
Hi @mayank1470 , no, it happens with every file, permissions are of upload and edit.
I've set up a small folder just to test this, you can see it [here](https://cloud.qoto.org/s/BD4reAfweBn2A7i)

Another way to share a single file is to right click + ctrl and copy link address, but again, I feel like that is what the "Share" option with the simple right click should give.

Hope I'm being clear, thanks!

**Comment by szaimen** [comment]
Sorry but I don't get what the problem here is. 
Please paraphrase your issue or better share a screencast video or screenshots of your problem. 
After that feel free to reopen. Thanks!
