### ISSUE TITLE
Nextcloud oc_accounts table should use json or jsonb data types in postgres

### ISSUE THREAD

**Issue by jmthackett** [nextcloud/server#21365]
Nextcloud currently stores data about users in the `oc_accounts` table, made up of a varchar uid and a text field containing json data of this format:

```
{"displayname":{"value":"name","scope":"contacts","verified":"0"},"address":{"value":"","scope":"private","verified":"0"},"website":{"value":"","scope":"private","verified":"0"},"email":{"value":null,"scope":"contacts","verified":"0"},"avatar":{"scope":"contacts"},"phone":{"value":"","scope":"private","verified":"0"},"twitter":{"value":"","scope":"private","verified":"0"}}
```

Since the field is a text field, it isn't queryable through postgres's json query tools. Please consider making this column a jsonb column, as that will make it very easy to work with.

**Comment by rullzer** [comment]
Yeah since it needs to work everywhere I'd rather not mess with it. Nextcloud will just select on another column and thenparse the json.
