### ISSUE TITLE
webauthn : import / migrate existing devices?

### ISSUE THREAD

**Issue by shinenelson** [nextcloud/server#21378]
would it make sense to import already registered token signatures for wenbAuthn from the `twofactor_u2f` app if it is installed?

I also understand the security aspect of it where we should not make security decisions for the user. the alternative option would be a UI option to opt-in to import existing tokens.

this would ease the migration path for users; by not having to go through the whole registration process all over again when they already did it once for 2FA. we're only converting the 2FA to 1FA right?

**Comment by kesselb** [comment]
cc @rullzer @ChristophWurst

**Comment by rullzer** [comment]
Nope.
First of all we'd need to somehow expose an API those apps can use. But more importantly the tokens could be registered differently. Hence not suitable.

Also I hardly doubt there is a big user base out there that was using that before.
And I rather have people manually making that choice. Also it is not as if registering a new token is that much work.
