### ISSUE TITLE
exception in webauthn failure scenario

### ISSUE THREAD

**Issue by shinenelson** [nextcloud/server#21377]
I deliberately simulated an authentication failure scenario with the webAuthn login. I got thrown a `HTTP 500`. The success scenario works fine.

system info : 
* server OS : debian 10 ( buster )
* dockerized : no
* upgrade status : yes, from v18.0.6

though it's a good thing that an unauthorized hardware device doesn't log you in, it should do so gracefully, not with `HTTP 500`.

~I'm sorry I don't know how to pretty print this log line as a good stacktrace.~ [**EDIT** : I was using `jq` incorrectly the last time.]
<details>
<summary>Stacktrace</summary>

```json
{
  "reqId": "PNijSCYDjoW4Lh7aJM1J",
  "level": 3,
  "time": "2021-06-08T18:24:10+00:00",
  "remoteAddr": "[REDACTED]",
  "user": "--",
  "app": "index",
  "method": "POST",
  "url": "/login/webauthn/finish",
  "message": {
    "Exception": "Exception",
    "Message": "Argument 1 passed to OC\\Core\\Controller\\WebAuthnController::finishAuthentication() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 218",
    "Code": 0,
    "Trace": [
      {
        "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
        "line": 157,
        "function": "dispatch",
        "class": "OC\\AppFramework\\Http\\Dispatcher",
        "type": "->",
        "args": [
          {
            "__class__": "OC\\Core\\Controller\\WebAuthnController"
          },
          "finishAuthentication"
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/private/Route/Router.php",
        "line": 302,
        "function": "main",
        "class": "OC\\AppFramework\\App",
        "type": "::",
        "args": [
          "OC\\Core\\Controller\\WebAuthnController",
          "finishAuthentication",
          {
            "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
          },
          {
            "_route": "core.WebAuthn.finishAuthentication"
          }
        ]
      },
      {
        "file": "/var/www/nextcloud/lib/base.php",
        "line": 993,
        "function": "match",
        "class": "OC\\Route\\Router",
        "type": "->",
        "args": [
          "/login/webauthn/finish"
        ]
      },
      {
        "file": "/var/www/nextcloud/index.php",
        "line": 37,
        "function": "handleRequest",
        "class": "OC",
        "type": "::",
        "args": []
      }
    ],
    "File": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
    "Line": 159,
    "Previous": {
      "Exception": "TypeError",
      "Message": "Argument 1 passed to OC\\Core\\Controller\\WebAuthnController::finishAuthentication() must be of the type string, null given, called in /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php on line 218",
      "Code": 0,
      "Trace": [
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 218,
          "function": "finishAuthentication",
          "class": "OC\\Core\\Controller\\WebAuthnController",
          "type": "->",
          "args": [
            null
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php",
          "line": 127,
          "function": "executeController",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OC\\Core\\Controller\\WebAuthnController"
            },
            "finishAuthentication"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/AppFramework/App.php",
          "line": 157,
          "function": "dispatch",
          "class": "OC\\AppFramework\\Http\\Dispatcher",
          "type": "->",
          "args": [
            {
              "__class__": "OC\\Core\\Controller\\WebAuthnController"
            },
            "finishAuthentication"
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/private/Route/Router.php",
          "line": 302,
          "function": "main",
          "class": "OC\\AppFramework\\App",
          "type": "::",
          "args": [
            "OC\\Core\\Controller\\WebAuthnController",
            "finishAuthentication",
            {
              "__class__": "OC\\AppFramework\\DependencyInjection\\DIContainer"
            },
            {
              "_route": "core.WebAuthn.finishAuthentication"
            }
          ]
        },
        {
          "file": "/var/www/nextcloud/lib/base.php",
          "line": 993,
          "function": "match",
          "class": "OC\\Route\\Router",
          "type": "->",
          "args": [
            "/login/webauthn/finish"
          ]
        },
        {
          "file": "/var/www/nextcloud/index.php",
          "line": 37,
          "function": "handleRequest",
          "class": "OC",
          "type": "::",
          "args": []
        }
      ],
      "File": "/var/www/nextcloud/core/Controller/WebAuthnController.php",
      "Line": 96
    },
    "CustomMessage": "--"
  },
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:90.0) Gecko/20100101 Firefox/90.0",
  "version": "21.0.1.1"
}
```
</details>

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

cc @rullzer @ChristophWurst

**Comment by shinenelson** [comment]
I think I know what might have happened. Google Chrome / Chromium gives a very nice visual error message when authentication failed and it probably gobbles up the actual request to the server.

![Screenshot from 2020-06-12 00-42-02](https://user-images.githubusercontent.com/4771718/84430057-c02bb700-ac46-11ea-9dc5-48a7730d015a.png)

I observed that the request to the server doesn't happen until the notification is dismissed. This doesn't happen on Firefox, it just sends the request.

what I think should be approach here is : 
1. implement an error fallback flow - throw an error pop-up ( at least on Firefox; it just stays there doing nothing which might lead to a lot of unnecessary spam auth requests to the server )
2. don't make a request to the server if the authentication on the client-side has already failed.

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by shinenelson** [comment]
Yes, this is still an issue. I am still able to reproduce the issue with Firefox on server v21.0.1. And with #27079, the feature is completely useless.

**Comment by white-miku** [comment]
Not sure that my problem belongs to the issue, but I'm getting too 500 error on finishing Webauthn authentication.
Chrome Dev 93.0.4535.2, Ubuntu Server 20.10, Nginx and PHP 8.0.7 (yes, I know that such configuration isn't officially supported).
Log info:
```{"reqId":"1X9YtiOjF9i1y01gbpJN","level":3,"time":"2021-06-13T15:00:34+00:00","remoteAddr":"****","user":"--","app":"index","method":"POST","url":"/login/webauthn/finish","message":{"Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Message":"An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY'","Code":1062,"Trace":[{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Connection.php","line":1728,"function":"convert","class":"Doctrine\\DBAL\\Driver\\API\\MySQL\\ExceptionConverter","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Connection.php","line":1667,"function":"handleDriverException","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Connection.php","line":1146,"function":"convertExceptionDuringQuery","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/mnt/storage/sites/next/lib/public/AppFramework/Db/QBMapper.php","line":135,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/mnt/storage/sites/next/lib/public/AppFramework/Db/QBMapper.php","line":159,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/CredentialRepository.php","line":89,"function":"insertOrUpdate","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/CredentialRepository.php","line":93,"function":"saveAndReturnCredentialSource","class":"OC\\Authentication\\WebAuthn\\CredentialRepository","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php","line":206,"function":"saveCredentialSource","class":"OC\\Authentication\\WebAuthn\\CredentialRepository","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/Manager.php","line":235,"function":"check","class":"Webauthn\\AuthenticatorAssertionResponseValidator","type":"->"},{"file":"/mnt/storage/sites/next/core/Controller/WebAuthnController.php","line":107,"function":"finishAuthentication","class":"OC\\Authentication\\WebAuthn\\Manager","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"finishAuthentication","class":"OC\\Core\\Controller\\WebAuthnController","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/mnt/storage/sites/next/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/mnt/storage/sites/next/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Driver/API/MySQL/ExceptionConverter.php","Line":60,"Previous":{"Exception":"Doctrine\\DBAL\\Driver\\PDO\\Exception","Message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY'","Code":1062,"Trace":[{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Driver\\PDO\\Exception","type":"::"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/mnt/storage/sites/next/lib/public/AppFramework/Db/QBMapper.php","line":135,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/mnt/storage/sites/next/lib/public/AppFramework/Db/QBMapper.php","line":159,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/CredentialRepository.php","line":89,"function":"insertOrUpdate","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/CredentialRepository.php","line":93,"function":"saveAndReturnCredentialSource","class":"OC\\Authentication\\WebAuthn\\CredentialRepository","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php","line":206,"function":"saveCredentialSource","class":"OC\\Authentication\\WebAuthn\\CredentialRepository","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/Manager.php","line":235,"function":"check","class":"Webauthn\\AuthenticatorAssertionResponseValidator","type":"->"},{"file":"/mnt/storage/sites/next/core/Controller/WebAuthnController.php","line":107,"function":"finishAuthentication","class":"OC\\Authentication\\WebAuthn\\Manager","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"finishAuthentication","class":"OC\\Core\\Controller\\WebAuthnController","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/mnt/storage/sites/next/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/mnt/storage/sites/next/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Driver/PDO/Exception.php","Line":26,"Previous":{"Exception":"PDOException","Message":"SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY'","Code":"23000","Trace":[{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","line":82,"function":"execute","class":"PDOStatement","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Connection.php","line":1136,"function":"execute","class":"Doctrine\\DBAL\\Driver\\PDO\\Statement","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/DB/Connection.php","line":257,"function":"executeStatement","class":"Doctrine\\DBAL\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Query/QueryBuilder.php","line":213,"function":"executeStatement","class":"OC\\DB\\Connection","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/DB/QueryBuilder/QueryBuilder.php","line":287,"function":"execute","class":"Doctrine\\DBAL\\Query\\QueryBuilder","type":"->"},{"file":"/mnt/storage/sites/next/lib/public/AppFramework/Db/QBMapper.php","line":135,"function":"execute","class":"OC\\DB\\QueryBuilder\\QueryBuilder","type":"->"},{"file":"/mnt/storage/sites/next/lib/public/AppFramework/Db/QBMapper.php","line":159,"function":"insert","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/CredentialRepository.php","line":89,"function":"insertOrUpdate","class":"OCP\\AppFramework\\Db\\QBMapper","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/CredentialRepository.php","line":93,"function":"saveAndReturnCredentialSource","class":"OC\\Authentication\\WebAuthn\\CredentialRepository","type":"->"},{"file":"/mnt/storage/sites/next/3rdparty/web-auth/webauthn-lib/src/AuthenticatorAssertionResponseValidator.php","line":206,"function":"saveCredentialSource","class":"OC\\Authentication\\WebAuthn\\CredentialRepository","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Authentication/WebAuthn/Manager.php","line":235,"function":"check","class":"Webauthn\\AuthenticatorAssertionResponseValidator","type":"->"},{"file":"/mnt/storage/sites/next/core/Controller/WebAuthnController.php","line":107,"function":"finishAuthentication","class":"OC\\Authentication\\WebAuthn\\Manager","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"finishAuthentication","class":"OC\\Core\\Controller\\WebAuthnController","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/mnt/storage/sites/next/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/mnt/storage/sites/next/lib/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/mnt/storage/sites/next/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/mnt/storage/sites/next/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php","Line":82}},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4535.2 Safari/537.36","version":"21.0.2.1","id":"60c61e2626e3b"}```

**Comment by shinenelson** [comment]
@white-miku looking at the stacktrace that you posted, the error message `"An exception occurred while executing a query: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '3' for key 'PRIMARY'"` indicates that it is #27079.

Please go there and :
- Please use the +1 reaction to show that you are affected by the same issue.
- Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
- Subscribe to receive notifications on status change and new comments.

Optionally, you could unsubscribe from this issue as it is not directly related to your issue ( even though it affects the same feature ).

**Comment by ChristophWurst** [comment]
https://github.com/nextcloud/server/pull/27886#issuecomment-894799772 backports have failed. This might need some manual porting.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by shinenelson** [comment]
I am sorry for the delayed response. Unfortunately, I do not have an installation of NextCloud anymore that I can use to test / experiment. I hope some of the people who have voted on this issue ( @omicron-b, @marekful ) might be able to test the validity of this issue 🤔
