### ISSUE TITLE
Allow linking URLs to projects

### ISSUE THREAD

**Issue by founderio** [nextcloud/server#21390]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When using different tools for collaboration, keeping track of related content across these tools is a challenge.
Nextcloud allows linking related resources into projects, but all these resources are internal to Nextcloud. Resources in other tools are not considered.

**Describe the solution you'd like**
A possibility to link URLs to projects to show them on the same level as the related folders, files, boards, etc.  
This would be helpful to e.g. link GitLab projects, public product websites, or content in CRM applications to a project.

**Describe alternatives you've considered**
An alternative would be to integrate with an app like the [Link Editor](https://apps.nextcloud.com/apps/files_linkeditor). In the current state, you can create a link file and add it to the project, but clicking it navigates to the file's containing folder instead of opening the link.  
If a linked .url or .webloc would instead trigger the app to open the link, it would be a working alternative.

**Additional context**
N/A

**Comment by szaimen** [comment]
cc @nextcloud/server-triage  do we want this?

**Comment by founderio** [comment]
How is this stale? It's a feature request, with an internal question of "Do we want this" => Does not need info, it needs a decision ;)

**Comment by skjnldsv** [comment]
@juliushaertl does it make sense?
Is it doable?

**Comment by juliushaertl** [comment]
Yes, though I'd say it is something for a separate app to add support for that as projects would need a resource type for links, probably bookmarks is a good place for that (https://github.com/nextcloud/bookmarks/issues/1492) but it could also be a separate app that just tracks linked urls.

**Comment by szaimen** [comment]
The bookmarks app sounds actually like the perfect candidate for this after thinking about this. So I'd say lets track this in https://github.com/nextcloud/bookmarks/issues/1492

**Comment by marcelklehr** [comment]
Done.
