### ISSUE TITLE
iOS browser app list view doesn't load images

### ISSUE THREAD

**Issue by Tomtom068** [nextcloud/server#21399]
Dear all, 
Server: Nextcloud 18.0.6, php 7.4
Displaying shared link on iOS > 12.0 (safari or chrome), to a folder containing any kind of file.

- Non-image type file download when clicked, which is the expected behavior.
- Image-type file loads preview, which is the expected behavior as well, but preview never displays.
![image](https://user-images.githubusercontent.com/18502843/84592086-3268eb00-ae43-11ea-8f55-64cb8ccbcd78.png)
Preview never loads...
![image](https://user-images.githubusercontent.com/18502843/84592088-35fc7200-ae43-11ea-9d07-04a81740e938.png)

The same preview works perfectly fine on desktop.

Don't hesitate to ask for details !

BR, 
Thomas

**Comment by kesselb** [comment]
cc @nextcloud/ios @skjnldsv

**Comment by szaimen** [comment]
Sounds like https://github.com/nextcloud/viewer/issues/500

**Comment by skjnldsv** [comment]
@Tomtom068 please enable federate sharing on your admin sharing settings :)

**Comment by Tomtom068** [comment]
> Sounds like [nextcloud/viewer#500](https://github.com/nextcloud/viewer/issues/500)

> @Tomtom068 please enable federate sharing on your admin sharing settings :)
It was actually this. I don't understand how this affects the display of an image in the iOS browser, while in desktop browser it doesn't need the checked box. 
Probably not the optimal solution, but it actually solved the issue.
