### ISSUE TITLE
Add support json field type to qbmapper

### ISSUE THREAD

**Issue by matchish** [nextcloud/server#21398]
I want to store some data as json in db but QBMapper doesn't support it

Can we add `json` field type here?https://github.com/nextcloud/server/blob/f04d526681322282dc79ba76c41a8e9b945e9d75/lib/public/AppFramework/Db/QBMapper.php#L217

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)

**Comment by szaimen** [comment]
Hi @matchish do you mind creating a PR with a patch for discussion?
Thank you!
