### ISSUE TITLE
Issues with .ocdata

### ISSUE THREAD

**Issue by thepra** [nextcloud/server#21403]
I have this message in the Security & setup warnings:
> It was not possible to execute the cron job via CLI. The following technical errors have appeared:
>The data folder is not valid. Make sure that there's a file ".ocdata" in the root of the data folder.
> Impossible to create the "data" folder....

My data folder is on a mounted and encrypted SSD and the data folder is looking fine for me:
![filess](https://user-images.githubusercontent.com/7032509/84605799-7f2edf00-aea0-11ea-9355-c6bd73e2f865.png)
And I did use ACL to have multiple owners of that folder.

Given this what could be cause of this issue?

**Comment by gary-kim** [comment]
Hi!

We deal with setup issues at <https://help.nextcloud.com>. Could you post your issue over there?

Thanks
