### ISSUE TITLE
Personal page layout issues with the password field

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2140]
On large screens the "show password" button at the New Password field is on the wrong position. See following screenshot:

correct (small screen):

![screenshot1](https://cloud.githubusercontent.com/assets/1589737/20314572/eec6b15a-ab5a-11e6-8272-099e18d13a5d.png)

wrong (large screen):

![screenshot2](https://cloud.githubusercontent.com/assets/1589737/20314578/f3bc3b58-ab5a-11e6-8c87-c2055287eb24.png)

cc @nextcloud/designers

**Comment by jancborchardt** [comment]
@schiessle you said that with #1946 (add more personal info) the fields are fixed to two columns. Then the password field can never flow this way. :)

**Comment by schiessle** [comment]
yes, was fixed as part of #1946
