### ISSUE TITLE
Name when creating a new folder and a new text document

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#21415]
### Steps to reproduce
1. Click the menu to send the file.
![obraz](https://user-images.githubusercontent.com/47037905/84662608-551b0280-af1c-11ea-85e7-5485814fd2ed.png)
2. Select "New folder".
![obraz](https://user-images.githubusercontent.com/47037905/84662680-6fed7700-af1c-11ea-9dea-7c29281d307b.png)
3. Click on the folder name to change its name.
![obraz](https://user-images.githubusercontent.com/47037905/84662825-9ca18e80-af1c-11ea-8704-bd1c132adb69.png)

### Expected behaviour
Editing the folder name by clicking the mouse on the folder name.

### Actual behaviour
Unable to edit the folder name by clicking on the name with the mouse. Can **only** be edited using the keyboard and navigation between letters of the name.

* The same error occurs when creating a new text document.
![obraz](https://user-images.githubusercontent.com/47037905/84663943-1be39200-af1e-11ea-9889-6568be720d0f.png)

### Server configuration

**Database:**
mysql 5.6.44 
**PHP version:**
7.2.29
**Nextcloud version:** (see Nextcloud admin page)
19.0.0

### Client configuration
**Browser:**
Firefox 77.0.1
**Operating system:**
Win10

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

cc @nextcloud/javascript for pointers where this needs to be fixed in the code

**Comment by Valdnet** [comment]
cc @nextcloud/javascript The problem persists in NC 22.0.0.

**Comment by Valdnet** [comment]
Issue has been around for over a year and is still available in version 22.1.1. This is very inconsistent with the overall NC. It requires special attention. You can get neurosis when you create many catalogs 😬.

@PVince81 @georgehrke @juliushaertl I know for sure that you will deal with it and correct it in no time. For developers, some things are easy to fix 😉.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

**Comment by Valdnet** [comment]
@szaimen In the latest versions of NC 24 and 25, the described problem still occurs.

**Comment by skjnldsv** [comment]
Fixed for 28
