### ISSUE TITLE
End-to-End encryption for sending user authentication

### ISSUE THREAD

**Issue by yku12cn** [nextcloud/server#21411]
Current user authentication mechanism sends user's password in plain text through the internet. It may not be a big problem if the server is https only. However, it will poses a security risk to anyone using the service in a bad setup(Such as Local network without https support/ Https with weak ciphers/through lousy CDN).

**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
The solution is basically a "Diffie Hellman" approach. Say, we use Diffie Hellman to generate a symmetrical key on the server and client respectively and use that key to encrypt the password on the client side before sending it to the server.

**Describe alternatives you've considered**
An easier way of doing this is to let the server generate a RSA key pair for the client to encrypt their password. However, this method can't protect against the Man-In-The-Middle attack.

**Additional context**
I'm not a professional web developer. I'm not sure if it is possible to perform a strong symmetrical  encryption on client side with some javascript. However, since we are only sending a rater short text, any symmetrical encryption method would be secure enough.

I have already checked a lot main stream websites. They all did something similar for user authentication. I guess there should be some pretty mature solution.

**Comment by kesselb** [comment]
Sounds like something for @rullzer ;)

> I have already checked a lot main stream websites. They all did something similar for user authentication. 

Mind to share them?

**Comment by yku12cn** [comment]
> Sounds like something for @rullzer ;)
> 
> > I have already checked a lot main stream websites. They all did something similar for user authentication.
> 
> Mind to share them?

Well.. I have to admit, I have been exaggerated when I say "mainstream". Sites like Google, twitter... they all rely purely on HTTPS and solid CDN. Sites with the encryption I mentioned mostly are rather small or even not English based.
"https://www.aliexpress.com/" is one of such site.

For our case, since most users setup their own server. We'd better use some more fool-proof mechanism.

**Comment by rullzer** [comment]
So what is the issue that this should solve?
I'm not per se against alternative login methods. But lets take a step back before we dive into it.

if a server is setup insecure this would (if we'd do some DH type things) prevent the password from leaking. However your password is by far the 'most' important thing.

If they can perform man-in-the-middle attacks you are basically doomed anyway.

1. They can steal your cookies. Hence they will be automatically logged in into your account
2. They can sniff (and save) everything you do, uploaded files, downloaded files. Etc etc.

So this would only protect you from having your password leaked. Which is still a noble quest of course.

**Comment by yku12cn** [comment]
> So what is the issue that this should solve?
> I'm not per se against alternative login methods. But lets take a step back before we dive into it.
> 
> if a server is setup insecure this would (if we'd do some DH type things) prevent the password from leaking. However your password is by far the 'most' important thing.
> 
> If they can perform man-in-the-middle attacks you are basically doomed anyway.
> 
> 1. They can steal your cookies. Hence they will be automatically logged in into your account
> 2. They can sniff (and save) everything you do, uploaded files, downloaded files. Etc etc.
> 
> So this would only protect you from having your password leaked. Which is still a noble quest of course.

In my opinion, password leak is much worse than data leak from a single server.
Lot people reuse their passwords.
For example, my office has nextcloud server for internal file sharing without https. Since this is an internal server, nobody really care about leaking files. But since we are all connected in a single sub net, anyone can sniff the traffic and find out other's password.

In a lot scenarios, people use nextcloud for non sensitive data and pay very little attention to security. In those scenarios, passwords may be the most important data. Since nextcloud already stores password in a very secure way, let't try not to compromise it by passing plain text around.

**Comment by rullzer** [comment]
Well if the idea is to prevent against snooping then sure there is no real difference.
However if the idea is to protect against MITM attack so the users password is never leaker then you'd need something DH.

**Comment by yku12cn** [comment]
> Well if the idea is to prevent against snooping then sure there is no real difference.
> However if the idea is to protect against MITM attack so the users password is never leaker then you'd need something DH.

@rullzer , so what would you say to this proposal in practice? I think besides choosing RSA or DH, the real challenge is how to add this to the various ways of user authentication that nextcloud now has. I could imagine this to affect a lot other functions such as WebDAV and some API. I do see some other services pop up a web browser every time when user need to authenticate.

**Comment by szaimen** [comment]
Seems like we won't implement this. Feel free to reopen if I misunderstood this.
