### ISSUE TITLE
When PHP 7.3.x or 7.4.x compiled with Argon2 .. wizard killed with white page

### ISSUE THREAD

**Issue by nephaste** [nextcloud/server#21426]
Steps to reproduce
after setup any DB in Wizard
blank page
Expected behaviour
go to auth page

Actual behaviour
blank page

Server configuration
Linux x86_64

Web server:

Apache 2.4.43

Database: Any

PHP version: 7.3.19 and 7.4.07

Nextcloud version: latest 18 & 19

Updated from an older Nextcloud/ownCloud or fresh install:

fresh install

Where did you install Nextcloud from:

Website tar.gz

discover an issue when php is compiled with Argon2.. after complete Wizard the page become blank and Nextcloud doesnt start

**found Workaround :**

1 ) force in config file to add the following line

`'hashing_default_password' => true,`

just like this

`<?php
$CONFIG = array (
  'instanceid' => 'ocg61wiq87m3',
  'passwordsalt' => 'ydniAQlWFcDG9MMAWzMlK8XkvgLZro',
  'secret' => 'O2DHiLvehj3VCsRPCak+sHUzSUXcJOPnJ9+knoHrN8qYJ5O5',
  'trusted_domains' => 
  array (
    0 => '192.168.0.59:35180',
  ),
  'datadirectory' => '/share/CACHEDEV1_DATA/.qpkg/NextCloud74/nextcloud/data',
  'dbtype' => 'sqlite3',
  'version' => '18.0.4.2',
  'overwrite.cli.url' => 'http://192.168.0.59:35180',
  'hashing_default_password' => true,
);
`

2 ) second workaround

comment lines 208, 209, 210 in nextcloud/lib/private/Security/Hasher.php such that they look like:

//if (\defined('PASSWORD_ARGON2I')) {
// $default = PASSWORD_ARGON2I;
//}
This will fallback to old hash algorithm.

**Comment by kesselb** [comment]
cc @rullzer @blizzz 

I'm don't know how to reproduce. Wizard works fine for me with php7.4 from sury (with argon2).

Nothing in the web server or nextcloud log?

**Comment by nephaste** [comment]
nothing in webserver logs and nextcloud log as well...

all is compiled from source , with argon2 from github as dependency

https://github.com/P-H-C/phc-winner-argon2/archive/20190702.tar.gz

**Comment by kesselb** [comment]
Have you tested the packages from your os vendor? I don't see a general issue with the hashing yet. There are some issues with fedora because they compiled it without a library and now a core extension is not available without installing an additional package.

**Comment by nephaste** [comment]
no OS Vendor, i am on Qnap NAS
i am QPKG creator for those devices for QnapClub... (all are cross-compiled from source)

Apache + PHP works as expected with all others PHP based applications,

**Comment by nephaste** [comment]
after setting wizard and getting white page without my workaround

NC logs : [](https://pastebin.com/VbyeLPSw)

Apache 2.4.43 with php 7.3.18

[](https://pastebin.com/abwcxgdG)

**Comment by rullzer** [comment]
Then setting hashing default password to true seems th be the easy solution.

It looks like your php is lying. The constant is defined but it seems to then die when it is used. Which is really weird. But then just use your first workaround.

**Comment by nephaste** [comment]
thanks rullzer

that what i think but not sure  how implement it, for an unattended installation with Wizard ... the config file is generated by wizard on what i saw

should i create an empty config file with this line ... (what should be the text format inside)
and not sure the wizard behavior  will not overwrite it.. or consider config file existing and refuse to start....

if have any clue ...

**Comment by nephaste** [comment]
seems working with an empty config.php file with

```
<?php
$CONFIG = array (
  'hashing_default_password' => true,
);
```

**Comment by kesselb** [comment]
Try to create a file `config/default_password_hash.config.php`:

```
<?php

$CONFIG = [
    'hashing_default_password' => true,
];
```

But the right fix would be to fix the broken php.

Here is for example how the debian packages are built https://salsa.debian.org/php-team/php/-/blob/debian/main/7.4/travis/compile.sh. Maybe it's enough to build php with libsodium instead of aragon2.

**Comment by nephaste** [comment]
libsodium (with extension) and argon2 are both include ..; in the php 7.x release in my package

i will try your solution as well but creating a custom config.php is actually working for me
