### ISSUE TITLE
Failed to view upload files via FTP on external storage. Wrong size

### ISSUE THREAD

**Issue by Pablossi** [nextcloud/server#21422]
I want to connect an external storage unit to be able to access some files that I upload via FTP. The problem is that NextCloud is not able to correctly show its size and sometimes it is shown as pending.

The file I want to upload is 10Gb and it is shown as 1.8GB but if I connect via FTP the size is correct.

I run the command "/ occ files: scan --all" and "/ occ files: scan --unscanned --all" and nothing.

Imagine it could be related to the limits in php.ini and Apache.conf but not either.

Any idea what is happening?

### Steps to reproduce
1.Upload a 10GB file to the server via FTP
2.Connect the extaerna drive pointing to the FTP folder
3.Synchronize it manually with "/ occ files: scan --all"

### Expected behaviour
The expected behavior is to match the size

### Actual behaviour
There is a difference in size that is reported

### Server configuration

**Operating system:Ubuntu 18.04.3 LTS

**Web server:Apache2

**Database:MySQL

**PHP version:7.4

**Nextcloud version:19

**Updated from an older Nextcloud/ownCloud or fresh install:fresh install

**Where did you install Nextcloud from:https://download.nextcloud.com/server/releases/latest-19.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.
</details>

**List of activated apps:**
<details>
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_antivirus: 2.4.1
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - lookup_server_connector: 1.7.0
  - mail: 1.3.5
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - ransomware_protection: 1.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.1
  - support: 1.2.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - federation
  - firstrunwizard
  - logreader
  - nextcloud_announcements
  - ojsxc
  - photos
  - recommendations
  - richdocuments
  - riotchat
  - survey_client
  - systemtags
  - user_ldap
  - user_oidc

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "www.???.org"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/www.???.org",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one: YES local/home/$USER/ftp/...

**Are you using encryption:no

</details>

### Client configuration
**Browser:Chrome 83.0.4103.97**

**Operating system:Windows 10 64

**Comment by szaimen** [comment]
Is this Issue still valid? If not, please close this issue. Thanks! :)
