### ISSUE TITLE
High server load, during file upload on 19.0.0

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#21428]
### Steps to reproduce
Upload a large file using e.g. curl

### Expected behaviour
Load during upload not higher than stable branch, here >=18.0.4

### Actual behaviour
Load roughly doubles (here Haswell CPU), upload rate drops by 40% on a gigabit connection

## Server configuration detail

**Operating system:** Linux 5.7.0-050700-generic #202005312130 SMP Mon Jun 1 01:33:12 UTC 2020 x86_64

**Webserver:** Apache/2.4.41 (Ubuntu) (apache2handler)

**Database:** sqlite3 3.31.1

**PHP version:** 

7.4.3
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, imagick, intl, json, exif, mysqli, pdo_mysql, pdo_sqlite, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - cloud_federation_api: 1.1.0
 - dav: 1.14.0
 - federatedfilesharing: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_sharing: 1.10.1
 - files_videoplayer: 1.7.0
 - issuetemplate: 0.6.0
 - lookup_server_connector: 1.6.0
 - oauth2: 1.6.0
 - previewgenerator: 2.3.0
 - provisioning_api: 1.8.0
 - settings: 1.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - accessibility
 - activity
 - admin_audit
 - comments
 - encryption
 - federation
 - files_pdfviewer
 - files_rightclick
 - files_trashbin
 - files_versions
 - firstrunwizard
 - logreader
 - nextcloud_announcements
 - notifications
 - password_policy
 - photos
 - privacy
 - recommendations
 - serverinfo
 - sharebymail
 - support
 - survey_client
 - systemtags
 - text
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "overwriteprotocol": "https",
    "trusted_domains": [
        "192.168.0.170:444",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "sqlite3",
    "overwrite.cli.url": "http:\/\/192.168.0.170:444",
    "installed": true,
    "updater.release.channel": "stable",
    "mail_smtpmode": "smtp",
    "mail_smtpauth": 1,
    "mail_sendmailmode": "smtp",
    "mail_smtpsecure": "ssl",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "jpeg_quality": "60",
    "enable_previews": true,
    "enabledPreviewProviders": {
        "0": "OC\\Preview\\PNG",
        "1": "OC\\Preview\\JPEG",
        "2": "OC\\Preview\\GIF",
        "10": "OC\\Preview\\TIFF"
    },
    "preview_max_x": "1600",
    "preview_max_y": "1600",
    "maintenance": false,
    "theme": "",
    "loglevel": 2
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:**

**Are you using an external user-backend, if yes which one:** 

## Client configuration

**Browser:** Curl Latest

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```

```
</details>

<details><summary>Nextcloud log</summary>

```
no errors logged
```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by f-s** [comment]
Has this issue been addressed the past month? How can I tell?

**Comment by f-s** [comment]
Hello, its almost 2 months. Has this issue been addressed? If the answer is yes, how can I tell if it can be fixed and what cause was?

**Comment by f-s** [comment]
19.0.1 is in the stable channel. Thanks, now this is everywhere.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
