### ISSUE TITLE
"&amp;" instead & in localized title (NC19.0.0)

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#21420]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install out-of-the-box NC 19.0.0
2. Set language to German
3. Go To Settings -> Personal -> Security (or the equivalent in German)

### Expected behaviour
Title should be "Geräte & Sitzungen"

### Actual behaviour
See this:
![grafik](https://user-images.githubusercontent.com/42836313/84695170-b5289d80-af4a-11ea-9a91-3e1c6ff1a235.png)

### Server configuration

**Nextcloud version:** 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** nextcloud.com

### Client configuration
**Browser:** Firefox 77.0.1

**Operating system:** Win 10 x64

**Comment by kesselb** [comment]
Search :)
