### ISSUE TITLE
UX: Vertical scroll bar too narrow

### ISSUE THREAD

**Issue by habernal** [nextcloud/server#21424]
### Steps to reproduce
1. Nextcloud 18.0.6
2. Firefox 77.0.1 on Xubuntu 20.04

### Expected behaviour
The vertical scroll bar used to be bigger (AFAIK), now it's half the size. This impacts usability of scrolling with mouse click.

See the attached screenshot for comparison: Nextcloud at the top, a regular website at the bottom.

![screenshot_2020-06-16_08-06-00](https://user-images.githubusercontent.com/11850778/84738230-d2408900-afa9-11ea-8152-fdaf6a9845cd.png)

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
@jancborchardt

**Comment by szaimen** [comment]
I think this was implemented in the meantime
