### ISSUE TITLE
Login flow creating duplicate tokens

### ISSUE THREAD

**Issue by williamrech** [nextcloud/server#21438]
I'm building an app to manage my clients Nextcloud server using the APIs available in the documentation. Everything is working fine, except that the login flow creates two separate tokens for the same session:

<img width="614" alt="Captura de Tela 2020-06-16 às 15 51 47" src="https://user-images.githubusercontent.com/66319068/84815399-5b2ae500-afe9-11ea-8409-0b97368cf28d.png">

I'm using dart and a web view to display the page provided for the users to type their info, enter and allow access. I also noticed that the 'Chrome' token is generated as the user clicks 'enter' and the 'dart' token after the access is granted on the same page.
Because of this, the remote wipe doesn't allow the user to enter a different account if so desired, instead, the webpage jumps to the 'grant access' part.
The result I expect can be achieved by manually revoking the extra token, or deleting the app data on the device. 

Is there a way to revoke these two, or all tokens? Or maybe prevent them from duplicating the first place?

**Comment by kesselb** [comment]
https://github.com/nextcloud/documentation/issues/1688
