### ISSUE TITLE
Allow to provide password as a parameter in the URL for a shared link

### ISSUE THREAD

**Issue by eharris** [nextcloud/server#21437]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to allow easy one-click access to password protected shared files (or dirs), which is a barrier to ease of use by less technical users that do not have accounts.  It also prevents being able to use those files/links as inline image/documents in other documents or email.

**Describe the solution you'd like**
I would like for there to be a way to supply the share password as part of the url, so that an intermediate password prompt page and POST is bypassed.

**Describe alternatives you've considered**
The only alternative that allows one-click access for non-account holders seems to be to just not password protect the share, which is less secure.

**Additional context**
Either a clear-text password or an obfuscated one would work for me, since it should be invisible to sniffing as long as the connection is SSL.  But perhaps an obfuscated one is preferable, as long as it is just as easy to see/manage when you need to.

**Comment by rullzer** [comment]
Then don't use a password.

There are around 54 septillion possible tokens. So guessing a token is not really feasible. This doesn't really add much in my opinion.
