### ISSUE TITLE
No known password when Share link with "always ask for a password"

### ISSUE THREAD

**Issue by JensKuehnel** [nextcloud/server#21436]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install nextcloud
2. enable in settings/admin/share, check"always ask for a password"
3. create a new share 

![output](https://user-images.githubusercontent.com/173758/84811186-c76b1000-b00c-11ea-99ad-c91d0de02f12.gif)

### Expected behaviour
It should show the password.

### Known workaround
unset checkbox and set checkbox again shows the new password.

### Actual behaviour
You don't know the password.

### Server configuration

**Operating system:** Centos 7
**Web server:** apache 2.4.6-93 (from Centos)
**Database:** MariaDB 5.5.65 (from Centos)
**PHP version:** 7.3.19 (from remi)
**Nextcloud version:** 18.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** 
updated from nextcloud 17 in January. Installed as owncloud and updated to NC 10-16.
Reproduced on a fresh 18 install.

**Where did you install Nextcloud from:** tar.gz 

**Signing status:**
No errors have been found.

**List of activated apps:**
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - apporder: 0.10.0
  - bookmarks: 3.1.1
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - data_request: 1.5.0
  - dav: 1.14.0
  - deck: 1.0.2
  - documentserver_community: 0.1.5
  - end_to_end_encryption: 1.4.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - guests: 1.4.6
  - hsts: 0.4.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - music: 0.14.1
  - nextcloud_announcements: 1.7.0
  - notes: 3.5.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - ocsms: 2.1.7
  - onlyoffice: 4.2.0
  - password_policy: 1.8.0
  - phonetrack: 0.6.3
  - photos: 1.0.0
  - polls: 1.4.3
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - qownnotesapi: 20.1.0
  - quota_warning: 1.7.0
  - rainloop: 6.1.4
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - suspicious_login: 3.1.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_nextcloud_notification: 2.3.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'instanceid' => '"***REMOVED SENSITIVE VALUE***"',
  'passwordsalt' => '"***REMOVED SENSITIVE VALUE***"',
  'datadirectory' => '"***REMOVED SENSITIVE VALUE***"',
  'dbtype' => 'mysql',
  'version' => '18.0.6.0',
  'installed' => true,
  'forcessl' => true,
  'theme' => '',
  'trusted_domains' => 
  array (
    0 => '"***REMOVED SENSITIVE VALUE***"',
    1 => '"***REMOVED SENSITIVE VALUE***"',
  ),
  'share_folder' => '/Shared',
  'secret' => '"***REMOVED SENSITIVE VALUE***"',
  'logtimezone' => 'Europe/Berlin',
  'asset-pipeline.enabled' => false,
  'assetdirectory' => '"***REMOVED SENSITIVE VALUE***"',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbuser' => 'nextcloud',
  'dbpassword' => '"***REMOVED SENSITIVE VALUE***"',
  'loglevel' => 0,
  'trashbin_retention_obligation' => 'auto',
  'maintenance' => false,
  'overwrite.cli.url' => 'https://"***REMOVED SENSITIVE VALUE***"/',
  'mysql.utf8mb4' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updater.release.channel' => 'stable',
  'upgrade.disable-web' => false,
  'mail_from_address' => 'nextcloud',
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_domain' => '"***REMOVED SENSITIVE VALUE***"',
  'enable_previews' => false,
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'simpleSignUpLink.shown' => false,
  'app_install_overwrite' => 
  array (
    0 => 'ocsms',
    1 => 'end_to_end_encryption',
    2 => 'hsts',
  ),
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no server-side, some users use client-side

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium&Firefox

**Operating system:** Linux and Windows

### Logs
no logs are created.

**Comment by kesselb** [comment]
cc @skjnldsv @jancborchardt

**Comment by JensKuehnel** [comment]
reproduced on a fresh installed NC 19.0.0 with sqlite.

**Comment by skjnldsv** [comment]
Fixed already, don't recall the version. (at least 20)

![Peek 22-03-2021 09-47](https://user-images.githubusercontent.com/14975046/111963339-aed7db00-8af3-11eb-8034-e177fc8cd409.gif)
