### ISSUE TITLE
High energy impact reported by Firefox - Continously calling setInterval

### ISSUE THREAD

**Issue by BraindeadBZH** [nextcloud/server#21459]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open NextCloud in Firefox in a window on one screen, on any app
2. Open about:performance in another window on another screen, so both page are visible at the same time
3. Firefox shows a medium to high energy impact for the NC page, even above a playing Youtube video
4. Open Firefox developer tools and go to the performance tab while on the NC page
5. Record a short session (10-15s is enough)
6. The record is full of call to setInterval, the stack show "easeTo/n.animatingInterval< main.js:791

### Expected behaviour
Energy impact should be low when doing nothing on the page.

### Actual behaviour
Energy impact is medium to high while doing nothing.

### Server configuration
Official Docker image: fpm-alpine (NC 19.0.0)

### Client configuration
**Browser:**
Firefox 77.0.1

**Operating system:**
Windows 10 x64

**Comment by kesselb** [comment]
Nextcloud is a open application. You can modify the behaviour by installing apps. To reproduce issues we ask for the list of apps and your configuration. Please edit your comment and add the missing information from the issue template. 

`about:performance` looks fine over here. Energy impact is usually low to medium. I also see a lot of setTimeout calls.

**Comment by PVince81** [comment]
I'm on NC 21.0 (master) locally with almost no apps.

You need two separate Firefox windows to see it, one with NC files app loaded and another one with the performance monitor.
I noticed that if I switch the NC tab to another tab on that window, the energy impact drops significantly, close to zero.

I tried to disable all elements with display: none but the high impact continues. It's very strange.

**Comment by PVince81** [comment]
In the files app:

1. Resize the window so that the left sidebar is not visible.
2. Observe performance: low impact
3. Maximize the window: medium impact
4. Unmaximize again: low impact again

At some point I even managed to make it go high by resizing several steps.

I wonder if there's a resize handler or something that gets multiplied, or a timer that gets multiplied with each resize or so.

**Comment by PVince81** [comment]
got the easeTo

<img width="927" alt="image" src="https://user-images.githubusercontent.com/277525/97637215-84995a00-1a3a-11eb-89ea-f849cce7a3eb.png">

now to find out where it comes from...

**Comment by PVince81** [comment]
Disabling this block makes the problem go away: https://github.com/nextcloud/server/blob/v20.0.0/core/src/init.js#L207
I just added a `if (false &&` and recompiled the JS.

So it's definitely related to Snap.js, the lib used to swiping the left sidebar.

**Comment by PVince81** [comment]
and here it explains what I observed: when the sidebar is visible, snapper gets disabled here https://github.com/nextcloud/server/blob/v20.0.0/core/src/init.js#L287

seems this was reported upstream already: https://github.com/jakiestfu/Snap.js/issues/216

**Comment by PVince81** [comment]
as far as I can see, we are sometimes calling `snapper.close()` when it's already closed or `snapper.open()` when already open.
apparently the library is not able to deal with multiple calls

a possible solution is to try and always check the state before doing a call (I have a local WIP)

**Comment by PVince81** [comment]
seems checking for the state is not enough, one can still make it go mad by hitting the enter key multiple times while focussing on the button... so already need to detect the "animating" state and not trigger anything during that time :'(

**Comment by PVince81** [comment]
I have a draft PR here that fixes most of the cases https://github.com/nextcloud/server/pull/23785
