### ISSUE TITLE
Can not autocomplete users by displayname

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#21451]
# Steps to reproduce
1. Run integration test: `sharees_features/sharees.feature:57` "Search only with group members - allowed"

Or

1. Set `shareapi_only_share_with_group_members` to `yes`
2. Add two users with user id `DEF1` and `DEF2` and displaynames `ABC1` and `ABC2` to a common group
3. As one of the user try to share an item with the other one.

Problem comes from: 
https://github.com/nextcloud/server/blame/caff1023ea72bb2ea94130e18a2a6e2ccf819e5f/lib/private/Group/Group.php#L308

which calls but that checks only the uid and not a related display name: 
https://github.com/nextcloud/server/blame/a636aef585a6e3e6cc628be6952cbec526148d70/lib/private/Group/Database.php#L350

So I guess it's broken since:
https://github.com/nextcloud/server/blame/294e40db5f01133d0b4227f3db85335924fe128f/lib/private/Collaboration/Collaborators/UserPlugin.php#L79

which was merged only recently:
https://github.com/nextcloud/server/pull/16035

**Comment by danxuliu** [comment]
See also [comment in #16035](https://github.com/nextcloud/server/pull/16035#issuecomment-612958873)

**Comment by nickvergessen** [comment]
Yeah, PR is at https://github.com/nextcloud/server/pull/21452 to fix it
