### ISSUE TITLE
No connection to local synapse/matrix server .

### ISSUE THREAD

**Issue by remi75** [nextcloud/server#21466]
### Steps to reproduce
1. Install / activate Riot Chat module
2. Configure the server's url 
3. Try to use / connect Riot Chat module

### Expected behaviour
A connection .

### Actual behaviour
Doesn't connect . msg: connection impossible to localhost:8008

### Server configuration

**Operating system:** debian 10

**Web server:** apache 2.4

**Database:** mariaDB 10

**PHP version:** php7.3

**Nextcloud version:** 19

Fresh installation

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-19.0.0.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>

 No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

ik02 nextcloud # sudo -u www-data php ./occ app:list  
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - appointments: 1.5.2
  - breezedark: 19.0.1
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - carnet: 0.22.0
  - cloud_federation_api: 1.2.0
  - cms_pico: 1.0.7
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - customproperties: 1.0.1
  - dav: 1.15.0
  - emlviewer: 0.0.12
  - encryption: 2.7.0
  - end_to_end_encryption: 1.5.1
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_texteditor: 2.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - flowupload: 1.0.0
  - gpgmailer: 0.0.1
  - guests: 1.4.6
  - login_notes: 0.2.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.0
  - maps: 0.1.6
  - metadata: 0.11.1
  - nextcloud_announcements: 1.8.0
  - notes: 3.5.1
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - ocdownloader: 1.7.8
  - onlyoffice: 4.2.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - qownnotesapi: 20.1.0
  - quicknotes: 0.6.0
  - rainloop: 7.0.1
  - recommendations: 0.7.0
  - riotchat: 0.4.3
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - unsplash: 1.1.6
  - updatenotification: 1.9.0
  - user_external: 0.10.0
  - viewer: 1.3.0
  - weather: 1.7.3
  - workflow_script: 1.4.0
  - workflowengine: 2.1.0
Disabled:
  - richdocuments
  - richdocumentscode
  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

sudo -u www-data php ./occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "ik02.remi.lu"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "https:\/\/ik02.remi.lu\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "has_rebuilt_cache": true,
        "maintenance": false
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... : No

**Are you using encryption:** Yes

**Are you using an external user-backend, No

</details>

### Client configuration
**Browser:**   Firefox 76.0.1

**Operating system:** Linux 

#### Web server error log

[nextcloud.zip](https://github.com/nextcloud/server/files/4798028/nextcloud.zip)
[nextclouderrorweb.log](https://github.com/nextcloud/server/files/4798061/nextclouderrorweb.log)
[nextcloudaccessweb.log](https://github.com/nextcloud/server/files/4798062/nextcloudaccessweb.log)

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

[nextcloud.zip](https://github.com/nextcloud/server/files/4798028/nextcloud.zip)

</details>

#### Browser log
<details>
<summary>Browser log</summary>
</details>

On the server, launching : lynx http://localhost:8008 or lynx localhost:8008
gives a positive greeting message from the im server .

Also, I have sniffed the network layer with tcpdump, I saw zero trafic on port 8008 , while trying to connect thru nextcloud .

**Comment by kesselb** [comment]
Wrong repository as riotchat is an app for Nextcloud. Look for the right repository and create a issue there. I cannot move your issue to the right repository because the app is not part of the Nextcloud organization here on GitHub.
