### ISSUE TITLE
Remove untested app override from config.php after a supported version of the app is installed or app is uninstalled

### ISSUE THREAD

**Issue by e-alfred** [nextcloud/server#21465]
### Steps to reproduce
1. Enable untested app that has no release for new Nextcloud version.
2. Install an updated version of a previously untested app that is compatible with the new Nextcloud version or uninstall the app completely.

### Expected behaviour
App should be removed from overrides in config.php.

### Actual behaviour
App is still listed in config.php app overrides.

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache 2.4

**Database:** Mariadb 10

**PHP version:** 7.2

**Nextcloud version:** (see Nextcloud admin page) 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** 18.0.4

**Where did you install Nextcloud from:** Official update

**Comment by DrCarsonBeckett** [comment]
#19044 explains this issue before this topic was opened.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/19044
