### ISSUE TITLE
.well-known check issues

### ISSUE THREAD

**Issue by idl0r** [nextcloud/server#21473]
Hi,

I'm on 18.0.6 right now but it appears as a warning for quite some time now.
The first thing that happens on my webserver is a https redirect when it's a http request. Internal connections are http only and that seems to cause the warnings on the overview page:

```
There are some warnings regarding your setup.

    Your web server is not properly set up to resolve "/.well-known/caldav". Further information can be found in the documentation.
    Your web server is not properly set up to resolve "/.well-known/carddav". Further information can be found in the documentation.

```

When I change the .htaccess to use an absolute link to https://example.com... it seems to work just fine. 
It doesn't seem to follow redirects and that is probably the problem? Because since the internal connection is http, apache/.htaccess rewrites to http, which is actually no problem.
It will be redirected to https first anyway. Is it possible to add an optional header, like it's done for the X-Forwarded-For header, to define a header that shows whether it's a https connection or something like that? Or to make the check follow redirects perhaps?

So just doing a 
curl -Lvs http://example.com/.well-known/caldav
works just fine. Same for carddav.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by kesselb** [comment]
I probably closed this report to quick. As per https://stackoverflow.com/a/10013873 ajax follows redirects by default so something else must be broken. The request should happen in your browser hence you can inspect it with the network tools.

**Comment by idl0r** [comment]
Hey, thanks!

So according to Firefox's F12 it's somewhat different than expected. It does a PROPFIND against https://example.com/.well-known/caldav and gets a 301 to http://example.com/remote.php/dav/ (note: http, because nextcloud .htaccess doesn't know that it's actually https) which it doesn't follow any further because then it would be redirected to https (https://example.com/remote.php/dav/) and get the actual result/page.

So the problem still looks to me like it a) doesn't follow the redirect and b) a http scheme has been used for a redirect because it doesn't know about the upper laying https connection

**Comment by kesselb** [comment]
You tried overwriteprotocol?

**Comment by idl0r** [comment]
Yes, it's set to "https" but it doesn't affect the .htaccess redirect.

**Comment by kesselb** [comment]
Closing as configuration issue. Please check the docs: https://docs.nextcloud.com/server/19/admin_manual/configuration_server/reverse_proxy_configuration.html#service-discovery. Your reverse proxy has to do the direct for such a setup.
