### ISSUE TITLE
Error opening shared file with collabora while loged in nextcloud

### ISSUE THREAD

**Issue by SiJux** [nextcloud/server#21488]
When you share odt-files per share link in the same nextcloud with other Users and they are opening the link while their are logged in the following error-message occurs when collabora try to open the file:
"Failed to read document from storage. Please contact your storage server (<server-url>) administrator."
The workaround for this problem is now to log out from the nextcloud and then open the shared file per share link again.

Steps to reproduce:
1. You need nextcloud with collabora
2. Generate odt-File in collabora and save it in nextcloud
3. Generate share link for this document
4. Log in with another User and open the shared link
5. now collabora is opening in the browser and you can see the error-message.

We are using nextcloud 18.0.3 with collabora online 3.5.2 and on the collabora server we are using loolwsd  4.0.11 (git hash: ff7fc02) and Collabora Office 6.0-29 (git hash: 5c5e764). We can also reproduce the problem while using nextcloud 18.0.4 with  Collabora Online 3.5.2 and on the collabora server loolwsd 4.2.3 (git hash: 6144a6c) and Collabora Office 6.2-12 (git hash: 8dce0b1).

**Comment by kesselb** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Please open an issue at https://github.com/nextcloud/richdocuments/issues and also check the Nextcloud/Collabora logs for errors
