### ISSUE TITLE
Elevated rights when resharing is enabled

### ISSUE THREAD

**Issue by Glowazowski** [nextcloud/server#21480]
Hi there,

I got the following issue: When I share a file to user A as read only and allow resharing, user A is allowed to share the file to user B (correct) and even allow user B to edit that file - so user C has higher rights to that file than the orignial author has granted to user A.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share file to other user and only allow that user to reshare that file
2. Second user shares the file to a third user with permission to edit that file
3. Third user may now edit that file

### Expected behaviour
Third user is not allowed to edit that file as the first user (owner) did not allow editing to any other user

### Actual behaviour
Third user is allowed to edit file

### Server configuration

**Operating system:**
Debian 10.4

**Web server:**
nginx 1.19

**Database:**
MariaDB 10.4

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
offical repository

**Comment by kesselb** [comment]
cc @nextcloud/sharing @nextcloud/security

**Comment by rullzer** [comment]
Please always submit security issues to https://hackerone.com/nextcloud

**Comment by rullzer** [comment]
Lets tackle this on h1
