### ISSUE TITLE
Problem with space and special characters in file & folder names

### ISSUE THREAD

**Issue by Kontonavn** [nextcloud/server#21501]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Try to create folder/file with a space or special character in it - in the browser, Windows-client and Android app.

2. Open existing file/folder with space and/or special characters 

Similar reports can be found [at the forum](https://help.nextcloud.com/t/synchronization-failed-space-or-letter-scolnzz-in-folder-filename/84617/9).
### Expected behaviour
1. File and/or folder is successfully created

2. File/folder opens
### Actual behaviour
1. No files/folders are actually created

2. Browser keeps loading

### Server configuration

Item|Version
-- | --
OS|CloudLinux OS+
Apache Version | 2.4.43
PHP Version | 7.3.17
MySQL Version | 5.7.29-cll-lve
Nextcloud | 18.0.6/19.0.0
LiteSpeed | 5.4.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
Tried both

**Where did you install Nextcloud from:**
Nextcloud.com and Softaculous

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:  - activity: 2.11.0  - admin_audit: 1.8.0  - bruteforcesettings: 1.6.0  - cloud_federation_api: 1.1.0  - dav: 1.14.0  - federatedfilesharing: 1.8.0  - files: 1.13.1  - files_accesscontrol: 1.8.1  - files_pdfviewer: 1.7.0  - files_rightclick: 0.15.2  - files_sharing: 1.10.1  - files_trackdownloads: 1.7.0  - files_trashbin: 1.8.0  - files_versions: 1.11.0  - files_videoplayer: 1.7.0  - firstrunwizard: 2.7.0  - impersonate: 1.5.2  - logreader: 2.3.0  - lookup_server_connector: 1.6.0  - nextcloud_announcements: 1.7.0  - notifications: 2.6.0  - oauth2: 1.6.0  - occweb: 0.0.7  - password_policy: 1.8.0  - privacy: 1.2.0  - provisioning_api: 1.8.0  - recommendations: 0.6.0  - serverinfo: 1.8.0  - settings: 1.0.0  - sharebymail: 1.8.0  - survey_client: 1.6.0  - systemtags: 1.8.0  - text: 2.0.0  - theming: 1.9.0  - twofactor_backupcodes: 1.7.0  - updatenotification: 1.8.0  - viewer: 1.2.0  - workflowengine: 2.0.0Disabled:  - accessibility  - comments  - encryption  - federation  - files_external  - maps  - photos  - support  - user_ldap

**Nextcloud configuration:**
...
{    
	"system": {        
	"instanceid": "***REMOVED SENSITIVE VALUE***",        
	"passwordsalt": "***REMOVED SENSITIVE VALUE***",        
	"secret": "***REMOVED SENSITIVE VALUE***",        
	"trusted_domains": [            "website.com"        ],        
	"datadirectory": "***REMOVED SENSITIVE VALUE***",        
	"dbtype": "mysql",        "version": "18.0.6.0",        
	"overwrite.cli.url": "https:\/\/website.com",        
	"dbname": "***REMOVED SENSITIVE VALUE***",        
	"dbhost": "***REMOVED SENSITIVE VALUE***",        
	"dbport": "",        "dbtableprefix": "oc_",        
	"mysql.utf8mb4": true,        
	"dbuser": "***REMOVED SENSITIVE VALUE***",        
	"dbpassword": "***REMOVED SENSITIVE VALUE***",        
	"installed": true,        
	"maintenance": false,        
	"theme": "",        
	"loglevel": 2,        
	"mail_smtpmode": "smtp",        
	"mail_smtpauth": 1,        
	"mail_sendmailmode": "smtp",        
	"mail_smtpauthtype": "LOGIN",        
	"mail_smtpsecure": "ssl",        
	"mail_smtphost": "***REMOVED SENSITIVE VALUE***",        
	"mail_smtpport": "465",        
	"mail_domain": "***REMOVED SENSITIVE VALUE***",        
	"mail_from_address": "***REMOVED SENSITIVE VALUE***",        
	"mail_smtpname": "***REMOVED SENSITIVE VALUE***",        
	"mail_smtppassword": "***REMOVED SENSITIVE VALUE***"    
	}
}
...
**Are you using external storage, if yes which one:** local/smb/sftp/...
No
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
### Client configuration
**Browser:**
Google Chrome 83.0.4103.106

**Operating system:**
Windows 10 and Nextcloud-android/3.10.1
#### Web server error log
<details>
<summary>Web server error log</summary>

```
"HEAD /remote.php/webdav/Newname%20(bilder)/Someroad%201C%2C%20Stj%C3%B8rdal%2C%20Erik%20Johnson%20-bygging%20av%20trapp/image0000011.jpg HTTP/1.1" 500 0 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
"PUT /remote.php/webdav/Newname%20(bilder)/Someroad%201C%2C%20Stj%C3%B8rdal%2C%20Erik%20Johnson%20-bygging%20av%20trapp/image0000011.jpg HTTP/1.1" 500 3233 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
"PUT /remote.php/dav/files/User1/Newname%20(beta%20og%20stable)/Some%20Customers/Someroad%201C,%20Stj%C3%B8rdal,%20Erik%20Johnson%20-maling%20av%20grunnmur%20og%20vinduskarm/Obs%20Bygg%20kr%20298,00.pdf HTTP/1.1" 500 1211 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"
"MOVE /remote.php/dav/files/User1/Newname%20(beta%20og%20stable)/Some%20Customers/Peter%20Street%2019%20A,%20%20Bj%C3%B8rn%20Ole%20Reid-%20vaskemaskin,%20skap HTTP/1.1" 500 1211 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"
"MKCOL /remote.php/dav/files/User1/Newname%20(beta%20og%20stable)/Some%20Customers/Skj%C3%A6ringen%206%20-%20Customer%202 HTTP/1.1" 500 1210 "-" "Mozilla/5.0 (Windows) mirall/2.6.4stable-Win64 (build 20200303) (Nextcloud)"
"PROPFIND /remote.php/webdav/Newname%20(beta%20og%20stable)/Some%20Customers/Nameandpath-%20Customer%202/ HTTP/1.1" 503 579 "-" "Mozilla/5.0 (Android) Nextcloud-android/3.10.1"
```
</details>

Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud error log</summary>
```
[remote] Error: Exception: The requested uri(/remote.php/webdav/Folder path with spaces/) cannot be processed by the script '/remote.php/webdav/Folder path with spaces/') at <<closure>>

0. /path/lib/private/AppFramework/Http/Request.php line 808
   OC\AppFramework\Http\Request->getRawPathInfo()
1. /path/remote.php line 127
   OC\AppFramework\Http\Request->getPathInfo()

HEAD /remote.php/webdav/Folder path with spaces//
from XXXXXX by YYYY at 2020-06-20T17:33:10+00:00

[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Exception: The requested uri(/remote.php/webdav/Path/to/file/with spaces.pdf) cannot be processed by the script '/remote.php/webdav/Path/to/file/with spaces.pdf') at <<closure>>

0. <<closure>>
   {closure}("*** sensitive parameters replaced ***")
1. /XYZ/3rdparty/sabre/event/lib/EventEmitterTrait.php line 105
   call_user_func_array(Closure {}, ["*** sensitive  ... "])
2. /XYZ/3rdparty/sabre/dav/lib/DAV/Server.php line 466
   Sabre\Event\EventEmitter->emit("beforeMethod", ["*** sensitive  ... "])
3. /XYZ/3rdparty/sabre/dav/lib/DAV/Server.php line 254
   Sabre\DAV\Server->invokeMethod("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
4. /XYZ/remote.php line 74
   Sabre\DAV\Server->exec()
5. /XYZ/remote.php line 168
   handleException(Exception {xdebu ... "})

PROPFIND /remote.php/webdav/Path/to/file/with spaces.pdf
from ABC by XYZ at 2020-06-20T11:03:46+00:00
```
</details>
Chrome Browser log
<details>
```
client.js?v=a93a9949-11:284 Uncaught (in promise) TypeError: Cannot read property 'length' of undefined
    at Client._parseFileInfo (client.js?v=a93a9949-11:284)
    at client.js?v=a93a9949-11:413
    at Function.v.map.v.collect (underscore.js:205)
    at Client._parseResult (client.js?v=a93a9949-11:412)
    at client.js?v=a93a9949-11:497

Request URL: https://website.com/ocs/v2.php/apps/text/workspace?path=%2FFolder_with_space
Request Method: GET
Status Code: 404 
```
</details>

**Comment by Dragon988** [comment]
This is confusing. The issue you linked to is specifically related to the android client. However, you stated here that you can't create the folder in the web browser either. Is it both or one or the other?

**Comment by Dragon988** [comment]
I'm not able to replicate this on NC19 with postgresql/nginx.

![iLVRHEERxW](https://user-images.githubusercontent.com/7935624/85211741-fc26e200-b300-11ea-9081-8be64ccf2f04.gif)

Is this a possible mysql/mariadb bug?

**Comment by Kontonavn** [comment]
Thanks for trying to replicate the issue!
According to the linked forum thread this started after a LiteSpeed Web Server update. This might also be the case here:

![Bug](https://user-images.githubusercontent.com/67204260/85212088-96ae1200-b34f-11ea-8053-bac98dfb1b25.gif)

**Comment by Dragon988** [comment]
Well if you use nginx or apache does the problem go away? Easiest way to determine if it's a litespeed issue.

**Comment by jjbubka** [comment]
Hello, I have the exact same issue, and my server is litespeed. But as it is a shared host service, I think i can't change it. In my case NC 18.0.4 was working well till I updated to 18.0.6. Next I updated to NC19, but the issue still persists. I don't know if it was a change in my hosting service between 18.0.4 and 18.0.6, or the issue really appeared at 18.0.6.
If I can make a test in my circumstances let me know.
Thank you

**Comment by Kontonavn** [comment]
I just did a fresh install with NC 18.0.4 and LiteSpeed, and the problem persists. Changing the web server isn't possible in my case as this is a shared plan.

The Photos and OCC Web app throws the following, which is related to the rest:

```
[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "photos.page.index" as such route does not exist. at <<closure>>

 0. /home/web/website.info/public_html/lib/private/Route/Router.php line 339
    Symfony\Component\Routing\Generator\UrlGenerator->generate("photos.page.index", [], 1)
 1. /home/web/website.info/public_html/lib/private/URLGenerator.php line 82
    OC\Route\Router->generate("photos.page.index", [])
 2. /home/web/website.info/public_html/lib/private/NavigationManager.php line 293
    OC\URLGenerator->linkToRoute("photos.page.index")
 3. /home/web/website.info/public_html/lib/private/NavigationManager.php line 114
    OC\NavigationManager->init()
 4. /home/web/website.info/public_html/apps/theming/lib/ThemingDefaults.php line 182
    OC\NavigationManager->getAll("guest")
 5. /home/web/website.info/public_html/lib/private/legacy/defaults.php line 263
    OCA\Theming\ThemingDefaults->getShortFooter()
 6. /home/web/website.info/public_html/lib/public/Defaults.php line 169
    OC_Defaults->getLongFooter()
 7. /home/web/website.info/public_html/core/templates/layout.guest.php line 55
    OCP\Defaults->getLongFooter()
 8. /home/web/website.info/public_html/lib/private/Template/Base.php line 179
    include("home/web/website ... p")
 9. /home/web/website.info/public_html/lib/private/Template/Base.php line 151
    OC\Template\Base->load("home/web/website ... p", null)
10. /home/web/website.info/public_html/lib/private/legacy/template.php line 181
    OC\Template\Base->fetchPage(null)
11. /home/web/website.info/public_html/lib/private/legacy/template.php line 212
    OC_Template->fetchPage(null)
12. /home/web/website.info/public_html/lib/private/Template/Base.php line 132
    OC_Template->fetchPage()
13. /home/web/website.info/public_html/lib/private/legacy/template.php line 300
    OC\Template\Base->printPage()
14. /home/web/website.info/public_html/remote.php line 82
    OC_Template::printErrorPage("App not installed: ", "", 0)
15. /home/web/website.info/public_html/remote.php line 168
    handleException(RemoteException  ... "})

PROPFIND /remote.php/dav/files/User1/Photos/Nextcloud%20community.jpg
```
And
```
[no app in context] Error: Symfony\Component\Routing\Exception\RouteNotFoundException: Unable to generate a URL for the named route "occweb.occ.index" as such route does not exist. at <<closure>>

 0. /home/web/website.info/public_html/lib/private/Route/Router.php line 339
    Symfony\Component\Routing\Generator\UrlGenerator->generate("occweb.occ.index", [], 1)
 1. /home/web/website.info/public_html/lib/private/URLGenerator.php line 82
    OC\Route\Router->generate("occweb.occ.index", [])
 2. /home/web/website.info/public_html/lib/private/NavigationManager.php line 293
    OC\URLGenerator->linkToRoute("occweb.occ.index")
 3. /home/web/website.info/public_html/lib/private/NavigationManager.php line 114
    OC\NavigationManager->init()
 4. /home/web/website.info/public_html/apps/theming/lib/ThemingDefaults.php line 182
    OC\NavigationManager->getAll("guest")
 5. /home/web/website.info/public_html/lib/private/legacy/defaults.php line 263
    OCA\Theming\ThemingDefaults->getShortFooter()
 6. /home/web/website.info/public_html/lib/public/Defaults.php line 169
    OC_Defaults->getLongFooter()
 7. /home/web/website.info/public_html/core/templates/layout.guest.php line 55
    OCP\Defaults->getLongFooter()
 8. /home/web/website.info/public_html/lib/private/Template/Base.php line 179
    include("home/web/website ... p")
 9. /home/web/website.info/public_html/lib/private/Template/Base.php line 151
    OC\Template\Base->load("home/web/website ... p", null)
10. /home/web/website.info/public_html/lib/private/legacy/template.php line 181
    OC\Template\Base->fetchPage(null)
11. /home/web/website.info/public_html/lib/private/legacy/template.php line 212
    OC_Template->fetchPage(null)
12. /home/web/website.info/public_html/lib/private/Template/Base.php line 132
    OC_Template->fetchPage()
13. /home/web/website.info/public_html/lib/private/legacy/template.php line 300
    OC\Template\Base->printPage()
14. /home/web/website.info/public_html/remote.php line 82
    OC_Template::printErrorPage("App not installed: ", "", 0)
15. /home/web/website.info/public_html/remote.php line 168
    handleException(RemoteException  ... "})

PROPFIND /remote.php/dav/files/User1/Photos/Nextcloud%20community.jpg
```

**Comment by kesselb** [comment]
Mind to report this to litespeed and ask what they changed? It does work for apache2 and nginx. At least for me that's good enough. Any other webserver is not supported anyway.

**Comment by Kontonavn** [comment]
This is a confirmed LiteSpeed issue which is fixed in their latest build:

> Please try the latest debug build, should be addressed.
> /usr/local/lsws/admin/misc/lsup.sh -d -f -v 5.4.7

My host has updated to this build, and everything is running as it should.

**Comment by jjbubka** [comment]
Oh well, thank you for the solution. My host is using litespeed 5.4.7 but they don't want to upgrade, so I suppose I must wait until a v5.4.8 is released, or change my provider.

**Comment by kesselb** [comment]
> This is a confirmed LiteSpeed issue which is fixed in their latest build:

Thanks for reporting back. I'm closing the report then.
