### ISSUE TITLE
occ upgrade: UnexpectedValueException: The files of the app "viewer" were not correctly replaced before running the update

### ISSUE THREAD

**Issue by zem** [nextcloud/server#21500]
### Steps to reproduce
1. Run Nextcloud 18.0.4 installed from stable18 branch
2. Upgrade to latest 18.0.6 using ./occ upgrade
3. receive the error: UnexpectedValueException: The files of the app "viewer" were not correctly replaced before running the update
4. Read knowledge base: https://help.nextcloud.com/t/error-the-files-of-the-app-viewer-were-not-replaced-correctly-after-upgrading/75521 
5. be confused how this relates. **Why is the app "viewer" only located the archive files https://download.nextcloud.com/server/releases/ and not with in this git repository?**

### Expected behaviour
Upgrade should pass with no issues. 

### Actual behaviour
occ upgrade is missing the "viewer" application. which seems not to be within this repository. That should not be. either viewer is not needed or it should be in this repository, or be listed as external dependency.

**Comment by kesselb** [comment]
Thanks for reporting a problem :+1: 

> Otherwise, git checkouts can be handled the same as release archives, by using the stable* branches. **Note they should never be used on production systems.**

https://github.com/nextcloud/server#development-setup-

Here is the list of apps usually shipped with a Nextcloud release: https://github.com/nextcloud/server/blob/master/core/shipped.json. Apps are listed in `alwaysEnabled` are expected to be there.
