### ISSUE TITLE
File Link with openfile param in NC19 breaks video/audio in iOS app and Safari

### ISSUE THREAD

**Issue by Scherar** [nextcloud/server#21509]
The new Link Structure in NC19 breaks loading videofiles in iOS and Safari
NC18 https://www.mydomain.tld/cloud/remote.php/webdav/Nextcloud.mp4 (works)
NC19 https://www.mydomain.tld/cloud/index.php/apps/files?dir=/&openfile=123456 (fails)

### Steps to reproduce
1. Click on a media file in Safari or iOS client
2. "Error loading xyz.mp4"
### Expected behaviour
the media should play in browser or iOS client

### Actual behaviour
get a message in Safari "error loading xyz.mp4", in iOS dark screen and infinate loading

### Server configuration

**Operating system:**
CentOS Linux 8

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 18

**Where did you install Nextcloud from:**
Updater

</details>

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:  - accessibility: 1.5.0  - activity: 2.12.0  - admin_audit: 1.9.0  - audioplayer: 2.10.1  - bruteforcesettings: 1.6.0  - calendar: 2.0.3  - cloud_federation_api: 1.2.0  - comments: 1.9.0  - contacts: 3.3.0  - contactsinteraction: 1.0.0  - dav: 1.15.0  - documentserver_community: 0.1.7  - federatedfilesharing: 1.9.0  - federation: 1.9.0  - files: 1.14.0  - files_pdfviewer: 1.8.0  - files_sharing: 1.11.0  - files_trashbin: 1.9.0  - files_versions: 1.12.0  - files_videoplayer: 1.9.0  - impersonate: 1.6.1  - logreader: 2.4.0  - lookup_server_connector: 1.7.0  - mail: 1.4.0  - nextcloud_announcements: 1.8.0  - notifications: 2.7.0  - oauth2: 1.7.0  - occweb: 0.0.7  - onlyoffice: 4.2.0  - password_policy: 1.9.1  - photos: 1.1.0  - privacy: 1.3.0  - provisioning_api: 1.9.0  - serverinfo: 1.9.0  - settings: 1.1.0  - sharebymail: 1.9.0  - systemtags: 1.9.0  - text: 3.0.1  - theming: 1.10.0  - theming_customcss: 1.6.0  - twofactor_backupcodes: 1.8.0  - updatenotification: 1.9.0  - viewer: 1.3.0  - workflowengine: 2.1.0 Disabled:  - encryption  - files_external  - files_rightclick  - firstrunwizard  - recommendations  - support  - survey_client  - user_ldap

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{    "system": {        "instanceid": "***REMOVED SENSITIVE VALUE***",        "passwordsalt": "***REMOVED SENSITIVE VALUE***",        "secret": "***REMOVED SENSITIVE VALUE***",        "trusted_domains": [
"cloud.gerhardhufnagl.de",
"cloud.museum-und-klick.com"        ],        "datadirectory": "***REMOVED SENSITIVE VALUE***",        "dbtype": "mysql",        "version": "19.0.0.12",        "overwrite.cli.url": "https:\/\/cloud.gerhardhufnagl.de",        "overwritehost": "cloud.gerhardhufnagl.de",        "dbname": "***REMOVED SENSITIVE VALUE***",        "dbhost": "***REMOVED SENSITIVE VALUE***",        "dbport": "",        "dbtableprefix": "oc_",        "mysql.utf8mb4": true,        "dbuser": "***REMOVED SENSITIVE VALUE***",        "dbpassword": "***REMOVED SENSITIVE VALUE***",        "installed": true,        "maintenance": false,        "trashbin_retention_obligation": "7,14",        "versions_retention_obligation": "7,auto",        "mail_smtpmode": "smtp",        "mail_smtpsecure": "ssl",        "mail_sendmailmode": "smtp",        "mail_from_address": "***REMOVED SENSITIVE VALUE***",        "mail_domain": "***REMOVED SENSITIVE VALUE***",        "mail_smtpauthtype": "LOGIN",        "mail_smtpauth": 1,        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",        "mail_smtpport": "465",        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",        "theme": "",        "loglevel": 2,        "htaccess.RewriteBase": "\/",        "memcache.local": "\\OC\\Memcache\\APCu",        "app_install_overwrite": [
"impersonate",
"occweb",
"hsts"        ],        "updater.release.channel": "beta"    },    "apps": {        "accessibility": {
"enabled": "yes",
"installed_version": "1.5.0",
"types": ""        },        "activity": {
"enable_email": "no",
"enabled": "yes",
"installed_version": "2.12.0",
"types": "filesystem"        },        "admin_audit": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "logging"        },        "audioplayer": {
"enabled": "yes",
"installed_version": "2.10.1",
"types": "filesystem"        },        "backgroundjob": {
"lastjob": "7"        },        "bruteforcesettings": {
"enabled": "yes",
"installed_version": "1.6.0",
"types": ""        },        "calendar": {
"enabled": "yes",
"installed_version": "2.0.3",
"types": ""        },        "cloud_federation_api": {
"enabled": "yes",
"installed_version": "1.2.0",
"types": "filesystem"        },        "comments": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "logging"        },        "contacts": {
"enabled": "yes",
"installed_version": "3.3.0",
"types": ""        },        "contactsinteraction": {
"enabled": "yes",
"installed_version": "1.0.0",
"types": "dav"        },        "core": {
"backgroundjobs_mode": "ajax",
"enterpriseLogoChecked": "yes",
"installed.bundles": "[\"CoreBundle\"]",
"installedat": "1575823872.4708",
"lastcron": "1592723702",
"lastupdateResult": "[]",
"lastupdatedat": "1592722928",
"oc.integritycheck.checker": "[]",
"public_files": "files_sharing\/public.php",
"public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
"shareapi_default_permission_candelete": "no",
"shareapi_default_permission_canshare": "no",
"shareapi_default_permissions": "7",
"theming.variables": "88d2c80cc60a2b9d471213d2a9a4341c",
"updater.secret.created": "1591887056",
"vendor": "nextcloud"        },        "dav": {
"buildCalendarReminderIndex": "yes",
"buildCalendarSearchIndex": "yes",
"chunks_migrated": "1",
"enabled": "yes",
"installed_version": "1.15.0",
"regeneratedBirthdayCalendarsForYearFix": "yes",
"types": "filesystem"        },        "documentserver_community": {
"enabled": "yes",
"installed_version": "0.1.7",
"types": "filesystem"        },        "federatedfilesharing": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": ""        },        "federation": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "authentication"        },        "files": {
"cronjob_scan_files": "500",
"enabled": "yes",
"installed_version": "1.14.0",
"types": "filesystem"        },        "files_pdfviewer": {
"enabled": "yes",
"installed_version": "1.8.0",
"types": ""        },        "files_rightclick": {
"enabled": "no",
"installed_version": "0.16.0",
"types": ""        },        "files_sharing": {
"enabled": "yes",
"incoming_server2server_share_enabled": "no",
"installed_version": "1.11.0",
"lookupServerUploadEnabled": "no",
"outgoing_server2server_share_enabled": "no",
"types": "filesystem"        },        "files_trashbin": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "filesystem,dav"        },        "files_versions": {
"enabled": "yes",
"installed_version": "1.12.0",
"types": "filesystem,dav"        },        "files_videoplayer": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": ""        },        "firstrunwizard": {
"enabled": "no",
"installed_version": "2.6.0",
"types": "logging"        },        "gallery": {
"enabled": "no",
"installed_version": "18.4.0",
"types": ""        },        "hsts": {
"enabled": "no",
"installed_version": "0.4.0",
"types": "prelogin"        },        "impersonate": {
"enabled": "yes",
"installed_version": "1.6.1",
"types": ""        },        "logreader": {
"enabled": "yes",
"installed_version": "2.4.0",
"types": ""        },        "lookup_server_connector": {
"enabled": "yes",
"installed_version": "1.7.0",
"types": "authentication"        },        "mail": {
"enabled": "yes",
"installed_version": "1.4.0",
"types": ""        },        "nextcloud_announcements": {
"enabled": "yes",
"installed_version": "1.8.0",
"pub_date": "Thu, 24 Oct 2019 00:00:00 +0200",
"types": "logging"        },        "notifications": {
"enabled": "yes",
"installed_version": "2.7.0",
"types": "logging"        },        "oauth2": {
"enabled": "yes",
"installed_version": "1.7.0",
"types": "authentication"        },        "occweb": {
"enabled": "[\"admin\"]",
"installed_version": "0.0.7",
"types": ""        },        "onlyoffice": {
"DocumentServerUrl": "https:\/\/cloud.gerhardhufnagl.de\/index.php\/apps\/documentserver_community\/",
"defFormats": "{\"docx\":true,\"pptx\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"doc\":true,\"ppt\":true,\"xls\":true}",
"editFormats": "{\"csv\":true,\"docx\":true,\"pptx\":true,\"txt\":true,\"xlsx\":true,\"odp\":true,\"ods\":true,\"odt\":true,\"rtf\":true}",
"enabled": "yes",
"installed_version": "4.2.0",
"sameTab": "true",
"types": "filesystem"        },        "password_policy": {
"enabled": "yes",
"installed_version": "1.9.1",
"minLength": "5",
"types": "authentication"        },        "passwords": {
"enabled": "no",
"installed_version": "2019.12.1",
"types": ""        },        "photos": {
"enabled": "yes",
"installed_version": "1.1.0",
"types": ""        },        "polls": {
"enabled": "no",
"installed_version": "1.1.6",
"types": ""        },        "privacy": {
"enabled": "yes",
"installed_version": "1.3.0",
"readableLocation": "de",
"types": ""        },        "provisioning_api": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "prevent_group_restriction"        },        "recommendations": {
"enabled": "no",
"installed_version": "0.5.0",
"types": ""        },        "serverinfo": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": ""        },        "settings": {
"enabled": "yes",
"installed_version": "1.1.0",
"types": ""        },        "sharebymail": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "filesystem"        },        "spreed": {
"enabled": "no",
"installed_version": "8.0.9",
"project_access_invalidated": "1",
"signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
"stun_servers": "***REMOVED SENSITIVE VALUE***",
"types": "prevent_group_restriction"        },        "support": {
"enabled": "no",
"installed_version": "1.1.0",
"types": "session"        },        "survey_client": {
"enabled": "no",
"installed_version": "1.6.0",
"types": ""        },        "systemtags": {
"enabled": "yes",
"installed_version": "1.9.0",
"types": "logging"        },        "tasks": {
"enabled": "no",
"installed_version": "0.13.1",
"types": ""        },        "text": {
"enabled": "yes",
"installed_version": "3.0.1",
"types": "dav"        },        "theming": {
"backgroundMime": "image\/jpeg",
"cachebuster": "53",
"color": "#2F6773",
"enabled": "yes",
"faviconMime": "image\/png",
"iOSClientUrl": "https:\/\/gerhardhufnagl.de\/bilder\/logo.png",
"imprintUrl": "***REMOVED SENSITIVE VALUE***",
"installed_version": "1.10.0",
"logoMime": "image\/png",
"logoheaderMime": "image\/png",
"name": "Gerhard Hufnagl Cloud",
"privacyUrl": "***REMOVED SENSITIVE VALUE***",
"slogan": "***REMOVED SENSITIVE VALUE***",
"types": "logging",
"url": "***REMOVED SENSITIVE VALUE***"        },        "theming_customcss": {
"cachebuster": "1587555804890",
"customcss": "footer { display:none !important; }",
"enabled": "yes",
"installed_version": "1.6.0",
"types": ""        },        "twofactor_backupcodes": {
"enabled": "yes",
"installed_version": "1.8.0",
"types": ""        },        "updatenotification": {
"audioplayer": "2.10.1",
"core": "18.0.6.0",
"documentserver_community": "0.1.7",
"enabled": "yes",
"files_rightclick": "0.15.1",
"impersonate": "1.6.1",
"installed_version": "1.9.0",
"mail": "1.3.5",
"theming_customcss": "1.6.0",
"types": "",
"update_check_errors": "0"        },        "viewer": {
"enabled": "yes",
"installed_version": "1.3.0",
"types": ""        },        "workflowengine": {
"enabled": "yes",
"installed_version": "2.1.0",
"types": "filesystem"        }    }}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

### Client configuration
**Browser:**
Safari 13.1.1
**Operating system:**
MacOS 10.15.5

### Logs

JS Console: 
Error loading – "/Nextcloud.mp4" – CustomEvent
Unhandled Promise Rejection: NotSupportedError: The operation is not supported.
</details>

**Comment by kesselb** [comment]
cc @nextcloud/ios

**Comment by Scherar** [comment]
The issue was related to a missing HTTP Header (Content-Range)... Sorry, issue fixed by Hoster...
