### ISSUE TITLE
Grid view in a shared photo folder consumes a lot of CPU and memory

### ISSUE THREAD

**Issue by derhagen** [nextcloud/server#21512]
### Steps to reproduce
I uploaded a folder of 150 photos, each 3-6MB. I shared the folder with a public link. Opening the link and viewing single photos works fine, but switching to grid view consumes a lot of CPU and memory. In this case, it uses all of my 2GB of memory.

#### OS/snapd/snap version
```
$ snap list nextcloud
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  18.0.6snap1  21521  latest/stable  nextcloud✓  -
```
```
$ snap version
snap    2.45
snapd   2.45
series  16
ubuntu  18.04
kernel  4.15.0-106-generic
```

**Comment by derhagen** [comment]
Moved here from https://github.com/nextcloud/nextcloud-snap/issues/1383

**Comment by kesselb** [comment]
Closing in favor of: https://github.com/nextcloud/server/issues/13709.
