### ISSUE TITLE
Error after last update (18.06): notes folder is not accessible 

### ISSUE THREAD

**Issue by Japhys** [nextcloud/server#21515]
I posted this issue in the Notes repository but they suggested I post it here since it seems to be an encryption problem -> https://github.com/nextcloud/notes/issues/546

Describe the bug
Notes will not show when clicking Notes from the admin bar. When I browse my folder, the folder Notes is accessible. It all happened after updating to 18.06 and subsequently the apps. Absolutely nothing else changed on the server / machine.

To Reproduce

    Go to menu Notes
    Error appears

Expected behavior
I expect to see my notes

Screenshots
See screenshots

Server (please complete the following information):

    Notes app version: 1.5.1
    Nextcloud version: 18.06
    OS: Linux 18.04 LTS
    Web server: Apache 2.4
    PHP version: 7.2.24
    Database: mysql 10.1.44

Client (please complete the following information):

    Browser (incl. version): Firefox 77.01
    OS: Windows

Log files

![85038204-9c0c3080-b186-11ea-8df4-a97801fb812d](https://user-images.githubusercontent.com/24695937/85228856-5fd70b00-b3e6-11ea-86e8-decc72cacc76.jpg)
![84876292-59affa00-b087-11ea-849f-82c3d14e0188](https://user-images.githubusercontent.com/24695937/85228857-61083800-b3e6-11ea-8980-f90828f32b85.png)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Japhys** [comment]
Nope seems to be fine now
