### ISSUE TITLE
Typo in App List (German language)

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#21516]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Use a NC 19.0.0
2. Wait for 2 or more apps to be updated

### Expected behaviour
Should say "Für 2 Apps ist eine Aktualisierung verfügbar" (Apps, not App)

### Actual behaviour
See:
![grafik](https://user-images.githubusercontent.com/42836313/85231615-12b06480-b3f9-11ea-8fb9-e6d927d5931a.png)

### Server configuration
NC 19.0.0

**Comment by kesselb** [comment]
It's not possible to fix it in transifex?

**Comment by johkoenig** [comment]
Could be. I did report it here because I didn't know a better place to do so.

**Comment by kesselb** [comment]
cc @rakekniven

**Comment by rakekniven** [comment]
Just took a closer look and changed it to Transifex. Should be fixed in v19.0.1 then. Thanks for reporting.
