### ISSUE TITLE
Collabora integrated CODE not using OVERWRITEPROTOCOL=https

### ISSUE THREAD

**Issue by s3ppo** [nextcloud/server#21513]
when trying to open a Office document with Collabora, i get an error in console:
```
Mixed Content: The page at 'https://mydomain' was loaded over HTTPS, but requested an insecure form action 'http://mydomain'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by kesselb** [comment]
Thanks for letting us know 👍

As explained in the issue template this repository is for nextcloud/server. Find the code for richdocumentscode at: https://github.com/CollaboraOnline/richdocumentscode/

**Comment by s3ppo** [comment]
where is the difference, i installed nextcloud and not richdocumentscode? :D

**Comment by kesselb** [comment]
richdocumentscode is an app for Nextcloud. The app does not respect overwriteprotocol hence you have to report it there.

**Comment by 0987363** [comment]
I had the same issue.

Nextcloud is run in docker with http.
Collabora is run in docker with tls disable.

Caddy reverse proxy nextcloud and collabora with https.
https://nextcloud.xxx.com:8008
https://collabora.xxx.com:8008

Nextcloud collabora app's remote address set to https://collabora.xxx.com:8008.
When open a doc, the error in console:
```
Mixed Content: The page at 'https://nextcloud.xxx.com:8008/apps/files/?dir=/doc&fileid=146' was loaded over HTTPS, but requested an insecure form action 'http://collabora.xxx.com:8008/loleaflet/6ad9d47/loleaflet.html?WOPISrc=https%3A%2F%2Fnextcloud.xxx.com%3A8008%2Findex.php%2Fapps%2Frichdocuments%2Fwopi%2Ffiles%2F79649_oc53itwzerti&title=%E8%BD%AF%E4%BB%B6%E9%9C%80%E6%B1%82%E8%A7%84%E6%A0%BC%E8%AF%B4%E6%98%8E%E4%B9%A6%E6%A8%A1%E6%9D%BF.doc&lang=zh-CN&closebutton=1&revisionhistory=1'. This request has been blocked; the content must be served over HTTPS.
```
