### ISSUE TITLE
Local App Store Repository

### ISSUE THREAD

**Issue by summersab** [nextcloud/server#21519]
Quite simply, it would be nice to be able to host a local clone of https://apps.nextcloud.com and then set `appstoreurl` to point to the local system. This would provide a number of benefits:

- Reduce traffic to Nextcloud's servers
- Speed up app installations for users
- Avoid issues some organizations may have with restricted access to the internet
- Allow administrators to restrict which apps are available (rsync provides mechanisms for excluding files)

Most Linux repos can be cloned by using rsync, and they are updated four times a day. Some repos allow for push-triggered syncing so that updates only occur when updates are available. Here's an overview from Debian:
https://www.debian.org/mirror/ftpmirror

Having a similar feature in NC would be quite useful.

**Comment by kesselb** [comment]
> Having a similar feature in NC would be quite useful.

Useful for? I don't see any benefit. Only additional work for a very limited use case. If you need that for your enterprise scenario probably talk with Nextcloud GmbH about it. 

The appstore requests:

- https://apps.nextcloud.com/api/v1/apps.json
- https://apps.nextcloud.com/api/v1/categories.json

Mirror those files and point appstoreurl to it (that's explained in the docs somewhere). Apps are downloaded from GitHub. Write a script to download the releases, store it locally and rewrite `apps.json`.

cc @nextcloud/server-triage keep it open?

**Comment by summersab** [comment]
I guess I didn't realize that the apps were being fetched straight from GitHub. I can script up a little service to routinely check for updates and pull from the repositories. It might be nice to allow `appstoreurl` to be set in `config.php` for advanced users/enterprise customization, though.

**Comment by nickvergessen** [comment]
A config already exists, it's just missing from the sample config:

https://github.com/nextcloud/server/blob/master/lib/private/App/AppStore/Fetcher/Fetcher.php#L225

**Comment by kesselb** [comment]
> A config already exists, it's just missing from the sample config:

Yep. How it works is already documented here: https://docs.nextcloud.com/server/19/admin_manual/apps_management.html#using-your-own-appstore

**Comment by summersab** [comment]
Whoops. Sorry about that, team. :-\
