### ISSUE TITLE
not 443 or 80 port

### ISSUE THREAD

**Issue by yyjazsf** [nextcloud/server#21520]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. install nextcloud
2. use nginx proxy, use port 8443
3. login, nextcloud redirect, but not  add port 8443, so website not show

### Expected behaviour
login in https://example.com:8443
jump to  https://example.com:8443/index.php.....

and some assets file link use https://example.com:8443/....

### Actual behaviour
login in https://example.com:8443
jump to  https://example.com/index.php.....

some img link is https://example.com/xxx so it will 404
### Server configuration

**Operating system:**
docker version : https://hub.docker.com/_/nextcloud/
latest

**Web server:**
ubuntu nginx
**Database:**
pg 12
**PHP version:**
docker version
**Nextcloud version:** (see Nextcloud admin page)
19.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
 fresh install:
**Where did you install Nextcloud from:**
 https://hub.docker.com/_/nextcloud/
**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
none one
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
chrome
**Operating system:**
macos 10.15
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for reporting a problem :+1: 

Please use https://help.nextcloud.com for questions or configuration issues and don't use our issue tracker as support channel. I'm closing your report as configuration issue. Check the documentation how to setup Nextcloud behind a reverse proxy: https://docs.nextcloud.com/server/19/admin_manual/configuration_server/reverse_proxy_configuration.html.

Help us to keep our issue tracker clean by using the search next time. There are plenty of reports for this kind of problem already.
