### ISSUE TITLE
Inconsistent NoSubAdminRequired NoSubadminRequired annotations

### ISSUE THREAD

**Issue by summersab** [nextcloud/server#21534]
Pretty simple bug. Throughout the controllers, security middleware, and subadmin middleware, there is inconsistent use of `NoSubAdminRequired` and `NoSubadminRequired` annotations (note the capitalization difference). It appears that the second form (`NoSubadminRequired`) is the more common annotation used in the code.

I did not see any issues with `SubAdminRequired` vs `SubadminRequired`.

```
$OC_VersionString = '19.0.0';
$OC_Build = '2020-05-26T08:11:09+00:00 9c63433cde916cd35b0708b398910cbc1cb52315';
```

**Comment by nickvergessen** [comment]
Yeah it's actually not a bug, as both annotations were correctly used within the scope of their app.
But we fixed it now to the same casing and (to avoid problems) to be case insensitive
