### ISSUE TITLE
Weblogin flow: re-auth and prefill username

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#21531]
On Android we use weblogin flow for authentication.
An user can the apptoken via web UI.

If the Android app then tries to access NC server again, it fails and thus opens up login flow, but without prefilled username.
As we have this on Android side, it would be great, if I can send this alongside with the login flow.

Bonus points for
- slightly better texts, e.g. re-authorize your client
- non-editable username

**Comment by joshtrichards** [comment]
I think this has since been covered by #29468 + #29530.
