### ISSUE TITLE
Please add X-OC-MTime and X-OC-CTime to file moving

### ISSUE THREAD

**Issue by mgutt** [nextcloud/server#21536]
As I was not able to update the file modification time [through many cURL commands](https://help.nextcloud.com/t/not-possible-to-update-file-modification-time-through-curl-or-other-methods/85441) I did a little bit research and found out that the X-OC-MTime header is only parsed in [Connector/Sabre/File.php -> put()](https://github.com/nextcloud/server/blob/d63abebc937583f2f97e58dc2887d88b6c6d13ee/apps/dav/lib/Connector/Sabre/File.php#L307).

By that its not possible to update the file modification time. Instead all files need to be re-uploaded if the times are wrong. The WebDAV spec contains two methods to solve this.

The first would be `PROPPATCH` as stated in my first link. But [the spec recommends to protect the property getlastmodified](https://tools.ietf.org/html/rfc4918#section-15.7) and it seems [Sabre DAV is doing this](https://github.com/owncloud/core/issues/33502). As its only a recommendation I opened an [issue for sabre/dav unprotecting getlastmodified](https://github.com/sabre-io/dav/issues/1277) to give the clients/users more freedom.

So I think the only possible way to realize that, would be to extend the `MOVE` method as it was done with `PUT`and my suggestion is to add the following code from the `put()` function to [this location](https://github.com/nextcloud/server/blob/b8b53a2d9a1cd12d112116151d32ff400f518524/apps/dav/lib/Connector/Sabre/Directory.php#L436) in Connector/Sabre/Directory.php -> moveInto().
```
			// allow sync clients to send the mtime along in a header
			if (isset($this->request->server['HTTP_X_OC_MTIME'])) {
				$mtime = $this->sanitizeMtime($this->request->server['HTTP_X_OC_MTIME']);
				if ($this->fileView->touch($this->path, $mtime)) {
					$this->header('X-OC-MTime: accepted');
				}
			}
			// allow sync clients to send the creation time along in a header
			if (isset($this->request->server['HTTP_X_OC_CTIME'])) {
				$ctime = $this->sanitizeMtime($this->request->server['HTTP_X_OC_CTIME']);
				$fileInfoUpdate['creation_time'] = $ctime;
				$this->header('X-OC-CTime: accepted');
			}
```

So moving a file twice would make it possible to update the file modification time.

It would be even better if `MOVE` would allow an [Overwrite: T header](https://doc.owncloud.com/server/developer_manual/webdav_api/trashbin.html#request-headers-2), but as [sabre dav does not allow source and target being the same](https://github.com/sabre-io/dav/blob/30e42f408516512ea44e0ca63b2843c924ad2946/lib/DAV/Server.php#L766), it's not realizable.

Of course X-OC-MTime / X-OC-CTime should be part of `COPY` as well, allowing the user to preserve the file modification time of a file copy or changing the creation time. If I found the correct position the above code [should be place here](https://github.com/nextcloud/server/blob/1762a409f954fd9a66e7572704ea9ba7813601b4/apps/dav/lib/Connector/Sabre/ObjectTree.php#L239), too.

**Comment by joho1968** [comment]
Does this mean that the instructions for finalizing a chunked upload does not properly set the time? That [example](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html) uses the **X-OC-Mtime** header with the MOVE command. Or is that a special situation only valid for chunked uploads?

**Comment by mgutt** [comment]
>Or is that a special situation only valid for chunked uploads?

Seems so as it is only part of the chunkperf.php:
https://github.com/nextcloud/server/blob/b219eadb8f3f459f2c71e937dfd3542f0792da8e/apps/dav/bin/chunkperf.php#L76

and of the createFileChunked function:
https://github.com/nextcloud/server/blob/0aa442220b0ddffe8cd7e9bfb0603c65b61ab3d9/apps/dav/lib/Connector/Sabre/File.php#L591

**Comment by szaimen** [comment]
Hi there, would you mind creating a PR with your patch?
Thank you! :)
