### ISSUE TITLE
File Browser - Retain Position When Navigating

### ISSUE THREAD

**Issue by valdearg** [nextcloud/server#21540]
Hi All,

I use Nextcloud for storing backups of various files, a lot of the time the folder listings are pretty long.

In these cases you have to scroll, wait for more to load, scroll again and so forth. If you then open one of the folders and then go back, it will return to the top of the page and then you have to go scrolling again.

Could the position in the folder be saved somehow?

**Comment by szaimen** [comment]
> Could the position in the folder be saved somehow?

Unfortunatley not, since that would require to load all of until to this point loaded files in one go.

cc @nextcloud/server-triage could scrollTo solve this?
