### ISSUE TITLE
Disable Shared Sub-Folders in Dashboard & Error during remove of share in Sub-Folder

### ISSUE THREAD

**Issue by pthoelken** [nextcloud/server#21553]
Nextcloud version: 18.0.6 
Operating system and version: CentOS 8
Apache or nginx version: nginx/1.14.1
PHP version: PHP 7.4.5

The issue you are facing: We're facing an error while removing the share from a subfolder. 

Final situation: 
1. Error is gone
2. Disable / Hide the shared Sub-Folders in the Dashboard from the user 

Is this the first time you've seen this error?: Y

Steps to replicate it:

1. Create a Folder and share it with a person in your nexcloud
2. Create a sub folder (which is automatically shared by default)
3. Try to remove the share-option at the subfolder (check the picture below)
4. You've got the error which you can see below

![image](https://user-images.githubusercontent.com/12643853/85501527-d7bf5400-b5e5-11ea-91b7-99c2a3882a91.png)
 
The output of your config.php file in `/path/to/nextcloud` (make sure you remove any identifiable information!):
```
<?php
$CONFIG = array (
  'instanceid' => 'ochqemu9ucx8',
  'passwordsalt' => 'YXXX',
  'secret' => 'XXX',
  'trusted_domains' => 
  array (
    0 => 'cloud.ev.de',
  ),
  'datadirectory' => '/media/evcldata',
  'dbtype' => 'mysql',
  'version' => '18.0.6.0',
  'overwrite.cli.url' => 'https://cloud.ev.de',
  'dbname' => 'dbevcl',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'uscl',
  'dbpassword' => 'XXXD',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'lost_password_link' => 'disabled',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'defaultapp' => 'files',
  'default_language' => 'de_DE',
  'force_language' => 'de_DE',
  'default_locale' => 'de_DE',
  'force_locale' => 'de_DE',
  'auth.bruteforce.protection.enabled' => true,
  'enabledPreviewProviders' => 
  array (
    0 => 'OC\\Preview\\PNG',
    1 => 'OC\\Preview\\JPEG',
    2 => 'OC\\Preview\\GIF',
    3 => 'OC\\Preview\\HEIC',
    4 => 'OC\\Preview\\BMP',
    5 => 'OC\\Preview\\XBitmap',
    6 => 'OC\\Preview\\MP3',
    7 => 'OC\\Preview\\TXT',
    8 => 'OC\\Preview\\MarkDown',
  ),
  'memcached_servers' => 
  array (
    0 => 
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'mail_from_address' => 'cloud',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'ev.de',
  'mail_smtphost' => '0.0.0.0',
  'mail_smtpport' => '25',
  'updater.release.channel' => 'stable',
  'maintenance' => false,
  'loglevel' => 2,
  'trashbin_retention_obligation' => 'auto',
  'updater.secret' => 'XY',
);

```

The output of your Apache/nginx/system log in `/var/log/____`:
```
nothing in this time span
```

**Comment by szaimen** [comment]
I could reproduce this on NC21.0.2

cc @nextcloud/javascript I suppose the option to delete the share should be hidden in this case?
![image](https://user-images.githubusercontent.com/42591237/120488334-fb267d80-c3b6-11eb-9f84-a6d28b1513b5.png)
