### ISSUE TITLE
Provide "Allow caldav access" option for app passwords

### ISSUE THREAD

**Issue by theCalcaholic** [nextcloud/server#21555]
The context menu of app passwords (in Settings/Security) provides an option to disable file access for an app password (see screenshot below). It would be a nice security feature to have that kind of option for more APIs, e.g. CalDav, NC API, Apps...

At least another option for CalDav would be very useful. :)

![image](https://user-images.githubusercontent.com/6317548/85526103-ffc0ae80-b609-11ea-868d-3bce078564bf.png)

**Comment by kesselb** [comment]
Related to #17327

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/17327
