### ISSUE TITLE
App can not access mp3 assets

### ISSUE THREAD

**Issue by sualko** [nextcloud/server#21561]
My XMPP chat is playing different sounds on different events, but it's not working in NC, because the url gets redirected. For example if you try to access `/apps/ojsxc/js/jsxc/assets/sound/Ping1-46f0422a.mp3` you get a 302. Can we add mp3, wav and ogg to the list of valid asset extensions?

https://github.com/nextcloud/server/blob/4bada5c7324d4ebf58a8ab2c8954b8e35cc883b2/lib/private/Setup.php#L531

ref https://github.com/jsxc/jsxc/issues/909

**Comment by szaimen** [comment]
I think this was fixed with https://github.com/nextcloud/server/pull/21580
