### ISSUE TITLE
[NC19] Email address is not saved when adding new user

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#21577]
1. Disable/uncheck the option "Send email to new user"
2. Add a new user with an email address

![image](https://user-images.githubusercontent.com/12234510/85638147-6f27b400-b685-11ea-957e-5cce697bac63.png)

3. Save

User is saved, but email address is not saved.

![image](https://user-images.githubusercontent.com/12234510/85638172-7bac0c80-b685-11ea-9f79-3fd00a916666.png)

Can reproduce it in any NC instance (upgraded from NC18 or fresh install).

**Comment by Ruinenarr** [comment]
Hi

got the same, but only if the "send email to new user"-option is unchecked.
if this option is activated, the email address is saved on creating a new user.

Rgds

**Comment by acsfer** [comment]
Exactly, forgot to mention. Thanks.

**Comment by acsfer** [comment]
With 19.0.3, email is not saved (well, is seem it is, but not visible on the UI) even if the option is checked.
Perhaps, the welcome email is sent...

Cc @nextcloud/server-triage

**Comment by skjnldsv** [comment]
cc @GretaD
