### ISSUE TITLE
Translation DE recemtly contacted

### ISSUE THREAD

**Issue by Matthias84** [nextcloud/server#21608]
### Describe the bug
While everything is translated properly to german, there is still the label "recently contacted".
Unfortunately I didn't found it at transifex to translate it myself

**To Reproduce**
1. Open settings / Einstellungen

**Expected behavior**
Full translation as 'Kürzlich kontaktiert'

**Screenshots**
![Screenshot_2020-06-27 Kontakte - Nextcloud](https://user-images.githubusercontent.com/217511/85920143-8cb97100-b871-11ea-93a9-f9fae0ac36ba.png)

### Server configuration

**Operating system**: Linux

**Web server:** Apache

**Database:** MariaDB,

**PHP version:** 7.4

**Nextcloud version:** 19.0

**Contacts version:** (see Nextcloud apps page)

**Updated from an older Nextcloud or fresh install:**
fresh

### Client configuration
**Browser:**

FF 77.0.1

**Comment by szaimen** [comment]
I cannot reproduce this on NC21.0.2
![image](https://user-images.githubusercontent.com/42591237/120490834-05e21200-c3b9-11eb-9ff1-1fc919b29f66.png)
