### ISSUE TITLE
Cannot Upload Files With Special Characters Or Spaces

### ISSUE THREAD

**Issue by chettyfj** [nextcloud/server#21611]
I have changed the database 4 byte recommendation and it still doesn't work. Any suggestions. 

Next Cloud 19.0.0
Interserver Hosting

Some Issues Shown:
![Screenshot (173)](https://user-images.githubusercontent.com/57745075/85934462-cdc78900-b936-11ea-8def-32c04a1c3021.png)

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
