### ISSUE TITLE
Incorrect start of the week for en_IE locale (should be Monday not Sunday)

### ISSUE THREAD

**Issue by RafalLukawiecki** [nextcloud/server#21614]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set user account locale to English (Ireland), or set `default_locale` to `en_IE` in `config.php`
### Expected behaviour
The "Locale" section of user settings should say "Week starts on Monday". This would be in line with the [moment/en-ie.js](https://github.com/moment/moment/blob/b8a7fc310eb3625e83fc0c8f1ea2840fa83c7378/locale/en-ie.js#L60) `week.dow` setting of "Monday is the first day of the week" and in accordance with the Irish custom, similar to the rest of Europe, and the way it works in other systems, for example macOS or iOS, when set to the Irish local

### Actual behaviour
The "Locale" section of the user settings says "Week starts on Sunday" which is not the expected value for Ireland. This affects Calendar view making it look strange and making multi-day event planning awkward.

As a workaround, changing locale to `en_GB` solves the issue of the starting day of the week, but that is not the correct locale for the Republic of Ireland.

### Server configuration

**Operating system:**
FreeBSD 11.3-RELEASE-p9

**Web server:**
caddy

**Database:**
mysql

**PHP version:**
7.3.19

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
18.0.6

**Where did you install Nextcloud from:**
https://github.com/danb35/freenas-iocage-nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 6.0.6
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - files_external
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Dublin",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "2",
        "logrotate_size": "104847600",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/mnt\/files\/skeleton",
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "default_language": "en_GB",
        "default_locale": "en_GB"
    }
}

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
</details>

### Client configuration
**Browser:**
Safari

**Operating system:**
macOS

#### Web server error log
<details>
<summary>Web server error log</summary>

```
***REMOVED SENSITIVE VALUE***
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
***REMOVED SENSITIVE VALUE***
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
***REMOVED SENSITIVE VALUE***
```
</details>

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2. 
As a workaround: please use the Irish (United Kingdom) locale.

**Comment by lindhe** [comment]
Same for Swedish locale.

**Comment by politas** [comment]
> As a workaround: please use the Irish (United Kingdom) locale.

Doesn't work for me. Like every single English locale, Irish (United Kingdom) is starting on Sunday.

**Comment by politas** [comment]
How is it that this is still a problem after two and a half years? People keep mentioning workarounds that never seem to work, and are not great anyway. The ISO standard is weeks starting on Monday, which is the default for almost every English locale, but Nextcloud is setting it to Sunday. Could we at the very least get a manual setting for Week Starts On?

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by politas** [comment]
I have recently upgraded to 25.0.2 
       
![image](https://user-images.githubusercontent.com/2109967/214025911-e982cc87-6713-4ae2-83df-acb8752611fa.png)

**Comment by politas** [comment]
Oh, just noticed, as you can see above, that English (World) is using the absurd US date representation that no other country uses.

**Comment by politas** [comment]
In general a workaround involving using an also-incorrect locale is not a useful workaround.

**Comment by politas** [comment]
I'm now on Nextcloud 27.0.0, and English (Australia) locale is still incorrectly setting Week Starts On to Sunday.

**Comment by politas** [comment]
Now upgraded to Nextcloud 27.1.1, and the same issues persist:

- English(Australia) incorrectly sets week starts on to Sunday
- English(World) incorrectly sets date formatting to mm/dd/yyyy
- There is no Great Britain or United Kingdom locale for English (the bare "English" setting has week starts on Sunday, so I don't think that's correct for the UK)

Isn't this a simple locale definitions file somewhere that needs to be fixed? It does seem to take a _long_ time to actually apply a changed locale setting.

**Comment by susnux** [comment]
> Incorrect start of the week for en_IE locale

This is resolved

![Screenshot 2024-08-07 at 18-38-31 Personal info - Personal settings - Nextcloud](https://github.com/user-attachments/assets/7383db19-bba5-4c33-b6af-b11d1dcc6808)
![Screenshot 2024-08-07 at 18-38-12 Personal info - Personal settings - Nextcloud](https://github.com/user-attachments/assets/bb2d3b62-298d-4c3c-a8b7-e06cdfd73f7b)
