### ISSUE TITLE
Buttons have not the same height as text-fields

### ISSUE THREAD

**Issue by MariusBluem** [nextcloud/server#2161]
<img width="109" alt="height" src="https://cloud.githubusercontent.com/assets/19711361/20350867/cd2d10f0-ac10-11e6-9746-8b8e55ecb268.png">

Buttons have not the same height as text-fields ... everywhere 😁 Tested with Chrome and Safari.

cc @jancborchardt @nextcloud/designers

**Comment by MorrisJobke** [comment]
They now have - thanks to @skjnldsv
