### ISSUE TITLE
Integrating New File Compression

### ISSUE THREAD

**Issue by Ttimmahlax** [nextcloud/server#21617]
Hello,

I was informed that this is the best channel for discussing custom code integration for NextCloud.

What kind of tooling would be necessary to implement a file compression into your platform?

I'm imagining a scenario where a file is uploaded from a desktop, it is transcoded into our file format for storage, and transcoded back when downloaded.

I look forward to the conversation, thank you!

**Comment by kesselb** [comment]
> I was informed that this is the best channel for discussing custom code integration for NextCloud.

How told you that?

> What kind of tooling would be necessary to implement a file compression into your platform?

That's a super general question. I would say you need at least PHPStorm if you want the server to do it.

**Comment by Ttimmahlax** [comment]
I'm not going to lie I was a little confused myself when I read through the threads, Frank sent me in this direction - most likely because it was a dev question.

Thought this might be the best place to see if anyone else had questions about implementing their own compression

**Comment by kesselb** [comment]
I doubt it's possible to give you any advice without details. Like you are going to a supermarket and asking a clerk _I want to buy groceries_.

**Comment by ChristophWurst** [comment]
> I'm not going to lie I was a little confused myself when I read through the threads, Frank sent me in this direction - most likely because it was a dev question.

Let's discuss at https://help.nextcloud.com/c/dev/app-dev/ instead :)
