### ISSUE TITLE
Cannot upgrade plugins anymore

### ISSUE THREAD

**Issue by mfechner** [nextcloud/server#21620]
### Steps to reproduce
1. Have a nextcloud 19.0.0 installed with php 7.4.7
2. Make sure you have the plugins Bookmarks (version 3.2.1) and/or Notes (version 3.5.1) installed
3. Make sure nextcloud reports that an update is available for these plugins
4. Click on Update all:

### Expected behaviour
Nextcloud should update the plugins correctly.

### Actual behaviour
Nothing happens and if you check the javascript console you see the error message:
TypeError: Cannot read property 'replace' of undefined

Which points to this code:

### Server configuration

**Operating system:**
FreeBSD 12.1

**Web server:**
NGINX 1.18.0

**Database:**
MariaDB 10.4.13

**PHP version:**
7.4.7

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
Using FreeBSD pkg (package management)

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - bookmarks: 3.2.1
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.5.1
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.1
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.1
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_external: 0.10.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - external
  - files_markdown
  - mozilla_sync

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.0.12",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "owncloud.fechner.net",
            "owncloud.idefix.lan",
            "owncloud.freebus.org",
            "nextcloud.fechner.net",
            "cloud.fechner.net"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "debug": false,
        "trashbin_retention_obligation": "auto",
        "preview_libreoffice_path": "\/usr\/local\/bin\/soffice",
        "overwrite.cli.url": "https:\/\/cloud.fechner.net",
        "overwriteprotocol": "https",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            },
            {
                "path": "\/usr\/local\/www\/nextcloud\/apps-pkg",
                "url": "\/apps-pkg",
                "writable": false
            }
        ],
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "PLAIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

</details>

### Client configuration
**Browser:**
Chrome Version 83.0.4103.116 (Offizieller Build) (64-Bit)

**Operating system:**
Win10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No logs created as this error is triggered in javascript on the browser
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No logs created as this error is triggered in javascript on the browser
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
octemplate.js:90 TypeError: Cannot read property 'replace' of undefined
    at Object._build (octemplate.js:83)
    at Object.init (octemplate.js:76)
    at e.fn.init.o.a.fn.octemplate (octemplate.js:102)
    at Object.<anonymous> (dialogs.js:146)
    at Object.<anonymous> (jquery.js:3256)
    at l (jquery.js:3099)
    at Object.fireWith [as resolveWith] (jquery.js:3211)
    at Object.Deferred.m.each.r.<computed> [as resolve] (jquery.js:3301)
    at Object.success (dialogs.js:1052)
    at l (jquery.js:3099) "data:" undefined



```
</details>

**Comment by kesselb** [comment]
cc @skjnldsv @GretaD looks related to the confirmation dialog for the password input.

**Comment by szaimen** [comment]
I think this was a bug in NC19 and was fixed in the meantime.
Please reopen if you can reproduce this with NC21.0.2!

**Comment by MartB** [comment]
@szaimen 
![image](https://user-images.githubusercontent.com/4820905/147886375-51a22eee-1b55-4bf0-8e44-8fd5e6ecf744.png)
on 23.0.0.

Authentication dialog is broken again.
```
octemplate.js:114 
TypeError: Cannot read properties of undefined (reading 'replace')
    at Object._build (octemplate.js:107)
    at Object.init (octemplate.js:100)
    at e.fn.init.o.a.fn.octemplate (octemplate.js:126)
    at dialogs.js:168
    at u (jquery.js:3534)
    at c (jquery.js:3602) 'data:' undefined
```

**Comment by MartB** [comment]
@szaimen Seeing that you handled this the last time, please kindly try and get this triaged.
Im not familiar enough with the nextcloud codebase but i think this affects everything on 23. that requires the admin password again. (Talk settings too.)

**Comment by MartB** [comment]
My case of this was solved by adjusting my nginx like outlined in https://help.nextcloud.com/t/cant-add-or-delete-groups-or-delete-users/91866/12 what an odd error...
