### ISSUE TITLE
Can not listen to "X" close button on `OC.dialogs.confirmDestructive`

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#21627]
From https://github.com/nextcloud/spreed/pull/3591#pullrequestreview-439053284

> When the dialog to leave or join is shown clicking on the close button in the top right closes the dialog without selecting any option, which leaves the UI in a weird state. Unfortunately [the close button is shown by default](https://github.com/nextcloud/server/blob/b1f74b0056b76402fbd618faff817432dec77ee3/core/src/jquery/ocdialog.js#L28) in the dialogs and [there is no parameter to disable it in `OC.dialogs`](https://github.com/nextcloud/server/blob/be0ecbc8c7f855cb0c9822233e38a9b459b80b58/core/src/OC/dialogs.js#L626-L630), so this needs to be fixed in the server.

The `OC.dialogs.confirmDestructive` dialog has a non-removable close button which can not be listened to.
In Talk we a workaround we added:
```js
	const interval = setInterval(function() {
		// eslint-disable-next-line no-undef
		if ($('.oc-dialog-dim').length === 0) {
			clearInterval(interval)
			EventBus.$emit('duplicateSessionDetected')
			window.location = generateUrl('/apps/spreed')
		}
	}, 3000)
```

This is as bad as it can get. Please help us to get rid of it and somehow trigger an event/callback or something so we can listen to the `X` properly (or even remove the `X`).

cc @nextcloud/javascript

**Comment by ChristophWurst** [comment]
This won't help here for a short term solution but I think this should be moved into a proper lazy (Vue) component and an API that gives you a promise. When the user clicks X then the promise shall be rejected. And all that should be added to https://github.com/nextcloud/nextcloud-dialogs/

**Comment by gary-kim** [comment]
Okay, would it make sense to call the already given callback with false if the x is pressed?

**Comment by nickvergessen** [comment]
For mecalling with the cancel option would be expected and is exactly what i do now.
I just didn't fine the right place in this legacy code to do that

**Comment by gary-kim** [comment]
Okay, gimme 10 minutes
