### ISSUE TITLE
Navigation Bar early Dropdown on medium sized screens

### ISSUE THREAD

**Issue by DragonDev1906** [nextcloud/server#21635]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open Nextcloud on any page (e.g. Files)
2. Resize the Browser window to 1811 pixel width or smaller
3. Look at the Navigation bar

### Expected behaviour
The Navigation bar should still show all icons next to each other because there is enough space for them (the screenshot is taken with 1812 pixel width). This should only change when the icons don't fit on the screen anymore.
![grafik](https://user-images.githubusercontent.com/8270201/86118028-5cbbd900-bad0-11ea-90ef-7713bd9412dc.png)

### Actual behaviour
At 1811 pixel or smaller some icons are moved to the dropdown. On a 1366x768 screen this is unfortunately always the case
![grafik](https://user-images.githubusercontent.com/8270201/86117995-50378080-bad0-11ea-9f47-c184190c73f2.png)

### Server configuration

**Operating system:**
Raspberry PI

**Database:**
mysql 10.3.17

**PHP version:**
7.3.11

**Nextcloud version:** (see Nextcloud admin page)
NextCloudPi 18.0.5

**List of activated apps:**
<details>
<summary>App list</summary>

- Accessibility
- Activity
- Calendar
- Collaborative tags
- Comments
- Contacts
- Deck
- Deleted Files
- Federation
- File sharing
- First run wizzard
- Log Reader
- Monitoring
- News
- Nextcloud announcements
- NextCloudPi
- Notes
- Notifications
- Password policy
- PDF viewer
- Photos
- Privacy
- Recommendations
- Right click
- Share by mail
- Support
- Tasks
- Text
- Theming
- Update notification
- Usage survey
- Versions
- Video Player
</details>

### Client configuration
**Browser:**
Firefox

**Operating system:**
- Windows 10
- Arch Linux

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
So … @karlitschek @juliushaertl what do you think?

To be honest we have more and more apps, especially with Nextcloud Hub, and limiting this to 8 seems really unnecessary. Yes we should also not let the apps take the whole header but leave some space between the icons on the right.

I would increase the limit to not use 33% of the width on large screens, but possibly 67%. This will make it look just fine on initial install, but also make it easy to access your other apps if you use Nextcloud a lot.

**Comment by karlitschek** [comment]
Agreed. Good compromise

**Comment by ma12-co** [comment]
> I would increase the limit to not use 33% of the width on large screens, but possibly 67%. 

Why not just fill all the available space with a fixed margin on the right between apps and the buttons on the right?

**Comment by jancborchardt** [comment]
> Why not just fill all the available space with a fixed margin on the right between apps and the buttons on the right?

I’m just working with the available parameters in core:
https://github.com/nextcloud/server/blob/master/core/src/init.js#L42-L43

Could be done otherwise of course as well.
