### ISSUE TITLE
php-fpm processes executing too slow

### ISSUE THREAD

**Issue by krentiken** [nextcloud/server#21631]
Hi!

OS - CentOS 7.8.2003
NC - 18.0.5
php-fpm-7.4.6
nginx-1.18.0-1
MariaDB-server-10.4.13-1
Browser - Chrome

My NextCloud works very slowly when navigating the menu. In the php-fpm logs, I see the following errors and warnings

<details>
<summary>Web server error log</summary>
[29-Jun-2020 22:25:36] WARNING: [pool www] child 20865, script '/var/www/html/nextcloud/ocs/v2.php' (request: "GET /ocs/v2.php") executing too slow (100.380196 sec), logging
[29-Jun-2020 22:25:36] NOTICE: child 20865 stopped for tracing
[29-Jun-2020 22:25:36] NOTICE: about to trace 20865
[29-Jun-2020 22:25:36] NOTICE: finished trace of 20865

[29-Jun-2020 22:30:13] WARNING: [pool www] child 11301, script '/var/www/html/nextcloud/remote.php' (request: "PROPFIND /remote.php") executing too slow (83.936190 sec), logging
[29-Jun-2020 22:30:13] NOTICE: child 11301 stopped for tracing
[29-Jun-2020 22:30:13] NOTICE: about to trace 11301
[29-Jun-2020 22:30:13] NOTICE: finished trace of 11301

[29-Jun-2020 22:00:14]  [pool www] pid 20865
script_filename = /var/www/html/nextcloud/ocs/v2.php
[0x00007ff752c14490] ldap_bind() /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php:335
[0x00007ff752c14420] call_user_func_array() /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php:335
[0x00007ff752c14340] invokeLDAPMethod() /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php:47
[0x00007ff752c142b0] bind() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:662
[0x00007ff752c141f0] bind() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:576
[0x00007ff752c14120] establishConnection() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:195
[0x00007ff752c140c0] init() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:203
[0x00007ff752c14050] getConnectionResource() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:1169
[0x00007ff752c13f40] executeSearch() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:1338
[0x00007ff752c13d70] search() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:1023
[0x00007ff752c13c30] searchUsers() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:916
[0x00007ff752c13b40] fetchListOfUsers() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:890
[0x00007ff752c13aa0] fetchUsersByLoginName() /var/www/html/nextcloud/apps/user_ldap/lib/User_LDAP.php:157
[0x00007ff752c139e0] getLDAPUserByLoginName() /var/www/html/nextcloud/apps/user_ldap/lib/User_LDAP.php:174
[0x00007ff752c13910] checkPassword() /var/www/html/nextcloud/apps/user_ldap/lib/User_Proxy.php:114
[0x00007ff752c138a0] call_user_func_array() /var/www/html/nextcloud/apps/user_ldap/lib/User_Proxy.php:114
[0x00007ff752c137a0] callOnLastSeenOn() /var/www/html/nextcloud/apps/user_ldap/lib/Proxy.php:150
[0x00007ff752c136f0] handleRequest() /var/www/html/nextcloud/apps/user_ldap/lib/User_Proxy.php:217
[0x00007ff752c13670] checkPassword() /var/www/html/nextcloud/lib/private/User/Manager.php:225
[0x00007ff752c135c0] checkPasswordNoLogging() /var/www/html/nextcloud/lib/private/User/Manager.php:202

[29-Jun-2020 22:10:23]  [pool www] pid 11301
script_filename = /var/www/html/nextcloud/ocs/v2.php
[0x00007ff752c165d0] session_start() /var/www/html/nextcloud/lib/private/Session/Internal.php:211
[0x00007ff752c16560] call_user_func_array() /var/www/html/nextcloud/lib/private/Session/Internal.php:211
[0x00007ff752c164b0] invoke() /var/www/html/nextcloud/lib/private/Session/Internal.php:59
[0x00007ff752c16420] __construct() /var/www/html/nextcloud/lib/base.php:429
[0x00007ff752c16330] initSession() /var/www/html/nextcloud/lib/base.php:647
[0x00007ff752c16180] init() /var/www/html/nextcloud/lib/base.php:1089
[0x00007ff752c16130] [INCLUDE_OR_EVAL]() /var/www/html/nextcloud/ocs/v1.php:33
[0x00007ff752c16070] [INCLUDE_OR_EVAL]() /var/www/html/nextcloud/ocs/v2.php:24

</details>

<details>
<summary>Signing status</summary>
No errors have been found.
</details>

<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - auto_groups: 1.2.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - deck: 1.0.4
  - documentserver_community: 0.1.7
  - drawio: 0.9.5
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_linkeditor: 1.1.1
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - groupfolders: 6.0.6
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - news: 14.1.11
  - nextcloud_announcements: 1.7.0
  - notes: 3.5.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - richdocuments: 3.7.3
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - tasks: 0.13.1
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - user_ldap: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - admin_audit
  - encryption
  - files_external
</details>

<details>
<summary>Config report</summary>
{
    "system": {
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.5.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "instanceid": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

<details>
<summary>LDAP config</summary>
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                        |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                          |
| homeFolderNamingRule          |                                                                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                                                                          |
| ldapAgentName                 | nclouduser                                                                                                                                                                 |
| ldapAgentPassword             | ***                                                                                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                                                                                            |
| ldapAttributesForUserSearch   |                                                                                                                                                                            |
| ldapBackupHost                |                                                                                                                                                                            |
| ldapBackupPort                |                                                                                                                                                                            |
| ldapBase                      | dc=XXX,dc=loc                                                                                                                                                   |
| ldapBaseGroups                | dc=XXX,dc=loc                                                                                                                                                   |
| ldapBaseUsers                 | dc=XXX,dc=loc                                                                                                                                                   |
| ldapCacheTTL                  | 600                                                                                                                                                                        |
| ldapConfigurationActive       | 1                                                                                                                                                                          |
| ldapDefaultPPolicyDN          |                                                                                                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                            |
| ldapEmailAttribute            | mail                                                                                                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                            |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                                             |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                            |
| ldapGidNumber                 | gidNumber                                                                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                                                                         |
| ldapGroupFilter               | (&(memberOf=CN=NCLOUDPortal_Write,OU=IT-Infrastructure,OU=ResourseGroups,OU=Groups,OU=XXX,DC=XXX,DC=loc)(objectClass=group))                         |
| ldapGroupFilterGroups         |                                                                                                                                                                            |
| ldapGroupFilterMode           | 1                                                                                                                                                                          |
| ldapGroupFilterObjectclass    |                                                                                                                                                                            |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                     |
| ldapHost                      | XXX.loc                                                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                                                            |
| ldapLoginFilter               | (&(objectclass=user)(|(sAMAccountName=%uid)(mail=%uid)))                                                                                                                   |
| ldapLoginFilterAttributes     |                                                                                                                                                                            |
| ldapLoginFilterEmail          | 0                                                                                                                                                                          |
| ldapLoginFilterMode           | 1                                                                                                                                                                          |
| ldapLoginFilterUsername       | 1                                                                                                                                                                          |
| ldapNestedGroups              | 0                                                                                                                                                                          |
| ldapOverrideMainServer        |                                                                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                                                                        |
| ldapPort                      | 389                                                                                                                                                                        |
| ldapQuotaAttribute            |                                                                                                                                                                            |
| ldapQuotaDefault              |                                                                                                                                                                            |
| ldapTLS                       | 0                                                                                                                                                                          |
| ldapUserAvatarRule            | default                                                                                                                                                                    |
| ldapUserDisplayName           | displayname                                                                                                                                                                |
| ldapUserDisplayName2          |                                                                                                                                                                            |
| ldapUserFilter                | (&(memberOf:1.2.840.113556.1.4.1941:=CN=NCLOUDPortal_Write,OU=IT-Infrastructure,OU=ResourseGroups,OU=Groups,OU=XXX,DC=XXX,DC=loc)(objectClass=user)) |
| ldapUserFilterGroups          |                                                                                                                                                                            |
| ldapUserFilterMode            | 1                                                                                                                                                                          |
| ldapUserFilterObjectclass     | person                                                                                                                                                                     |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                                                                                       |
| turnOffCertCheck              | 0                                                                                                                                                                          |
| turnOnPasswordChange          | 0                                                                                                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                                                                                                          |
+-------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
</details>

**Comment by timm2k** [comment]
Is this also the case when you disable `users_ldap` temporarly? May be your LDAP isn't working properly due to missing indexes or huge nesting level of groups. If disabling `users_ldap` brings a performance boost please provide some information about your LDAP server.

**Comment by krent84** [comment]
Hello, timm2k!

I disabled ldap configuration:

ldapConfigurationActive       | 0

and started working under the "admin" account. after a while I get the same errors:

<details>
<summary>php-fpm errors</summary>

[06-Jul-2020 20:28:31]  [pool www] pid 18499
script_filename = /var/www/html/nextcloud/index.php
[0x00007ff752c13cb0] ldap_bind() /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php:335
[0x00007ff752c13c40] call_user_func_array() /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php:335
[0x00007ff752c13b60] invokeLDAPMethod() /var/www/html/nextcloud/apps/user_ldap/lib/LDAP.php:47
[0x00007ff752c13ad0] bind() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:662
[0x00007ff752c13a10] bind() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:576
[0x00007ff752c13940] establishConnection() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:195
[0x00007ff752c138e0] init() /var/www/html/nextcloud/apps/user_ldap/lib/Connection.php:203
[0x00007ff752c13870] getConnectionResource() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:1267
[0x00007ff752c13720] count() /var/www/html/nextcloud/apps/user_ldap/lib/Access.php:1095
[0x00007ff752c13650] countObjects() /var/www/html/nextcloud/apps/user_ldap/lib/Wizard.php:112
[0x00007ff752c13590] countEntries() /var/www/html/nextcloud/apps/user_ldap/lib/Wizard.php:188
[0x00007ff752c13520] countInBaseDN() /var/www/html/nextcloud/apps/user_ldap/ajax/wizard.php:96
[0x00007ff752c13390] [INCLUDE_OR_EVAL]() /var/www/html/nextcloud/lib/private/Route/Route.php:155
[0x00007ff752c13300] OC\Route\{closure}() /var/www/html/nextcloud/lib/private/Route/Router.php:299
[0x00007ff752c13290] call_user_func() /var/www/html/nextcloud/lib/private/Route/Router.php:299
[0x00007ff752c131b0] match() /var/www/html/nextcloud/lib/base.php:1008
[0x00007ff752c130b0] handleRequest() /var/www/html/nextcloud/index.php:38

[06-Jul-2020 20:28:31]  [pool www] pid 18500
script_filename = /var/www/html/nextcloud/index.php
[0x00007ff752c13550] session_start() /var/www/html/nextcloud/lib/private/Session/Internal.php:211
[0x00007ff752c134e0] call_user_func_array() /var/www/html/nextcloud/lib/private/Session/Internal.php:211
[0x00007ff752c13430] invoke() /var/www/html/nextcloud/lib/private/Session/Internal.php:59
[0x00007ff752c133a0] __construct() /var/www/html/nextcloud/lib/base.php:429
[0x00007ff752c132b0] initSession() /var/www/html/nextcloud/lib/base.php:647
[0x00007ff752c13100] init() /var/www/html/nextcloud/lib/base.php:1089
[0x00007ff752c130b0] [INCLUDE_OR_EVAL]() /var/www/html/nextcloud/index.php:36

</details>

<details>
<summary>ldap config</summary>

| Configuration                 | s01                                                                                                                                                                        |

| hasMemberOfFilterSupport      | 1                                                                                                                                                                          |
| homeFolderNamingRule          |                                                                                                                                                                            |
| lastJpegPhotoLookup           | 0                                                                                                                                                                          |
| ldapAgentName                 | nclouduser                                                                                                                                                                 |
| ldapAgentPassword             | ***                                                                                                                                                                        |
| ldapAttributesForGroupSearch  |                                                                                                                                                                            |
| ldapAttributesForUserSearch   |                                                                                                                                                                            |
| ldapBackupHost                |                                                                                                                                                                            |
| ldapBackupPort                |                                                                                                                                                                            |
| ldapBase                      | dc=pc,dc=loc                                                                                                                                                   |
| ldapBaseGroups                | dc=pc,dc=loc                                                                                                                                                   |
| ldapBaseUsers                 | dc=pc,dc=loc                                                                                                                                                   |
| ldapCacheTTL                  | 600                                                                                                                                                                        |
| ldapConfigurationActive       | 0                                                                                                                                                                          |
| ldapDefaultPPolicyDN          |                                                                                                                                                                            |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                            |
| ldapEmailAttribute            | mail                                                                                                                                                                       |
| ldapExperiencedAdmin          | 0                                                                                                                                                                          |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                            |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                            |
| ldapExpertUsernameAttr        | sAMAccountName                                                                                                                                                             |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                            |
| ldapGidNumber                 | gidNumber                                                                                                                                                                  |
| ldapGroupDisplayName          | cn                                                                                                                                                                         |
| ldapGroupFilter               | (&(memberOf=CN=NCLOUDPortal_Write,OU=IT-Infrastructure,OU=ResourseGroups,OU=Groups,OU=Pc,DC=pc,DC=loc)(objectClass=group))                         |
| ldapGroupFilterGroups         |                                                                                                                                                                            |
| ldapGroupFilterMode           | 1                                                                                                                                                                          |
| ldapGroupFilterObjectclass    |                                                                                                                                                                            |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                     |
| ldapHost                      | pc.loc                                                                                                                                                         |
| ldapIgnoreNamingRules         |                                                                                                                                                                            |
| ldapLoginFilter               | (&(objectclass=user)(|(sAMAccountName=%uid)(mail=%uid)))                                                                                                                   |
| ldapLoginFilterAttributes     |                                                                                                                                                                            |
| ldapLoginFilterEmail          | 0                                                                                                                                                                          |
| ldapLoginFilterMode           | 1                                                                                                                                                                          |
| ldapLoginFilterUsername       | 1                                                                                                                                                                          |
| ldapNestedGroups              | 0                                                                                                                                                                          |
| ldapOverrideMainServer        |                                                                                                                                                                            |
| ldapPagingSize                | 500                                                                                                                                                                        |
| ldapPort                      | 389                                                                                                                                                                        |
| ldapQuotaAttribute            |                                                                                                                                                                            |
| ldapQuotaDefault              |                                                                                                                                                                            |
| ldapTLS                       | 0                                                                                                                                                                          |
| ldapUserAvatarRule            | default                                                                                                                                                                    |
| ldapUserDisplayName           | displayname                                                                                                                                                                |
| ldapUserDisplayName2          |                                                                                                                                                                            |
| ldapUserFilter                | (&(memberOf:1.2.840.113556.1.4.1941:=CN=NCLOUDPortal_Write,OU=IT-Infrastructure,OU=ResourseGroups,OU=Groups,OU=PcDC=pc,DC=loc)(objectClass=user)) |
| ldapUserFilterGroups          |                                                                                                                                                                            |
| ldapUserFilterMode            | 1                                                                                                                                                                          |
| ldapUserFilterObjectclass     | person                                                                                                                                                                     |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                       |
| ldapUuidUserAttribute         | auto                                                                                                                                                                       |
| turnOffCertCheck              | 0                                                                                                                                                                          |
| turnOnPasswordChange          | 0                                                                                                                                                                          |
| useMemberOfToDetectMembership | 1                                                                                                                                                                          |

</details>


"NCLOUDPortal_Write" contains 1 group - "NCLOUDPortal_Users", which contains about 1000 users in Active Directory LDAP catalog

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
