### ISSUE TITLE
Video streaming is sometimes slow: store transcoded videos and stream them?

### ISSUE THREAD

**Issue by jakobroehrl** [nextcloud/server#21633]
Video streaming is sometimes slow or doesn't work, especially on mobile. 
If I compress it, it works a lot better: https://help.nextcloud.com/t/help-with-the-external-scripts-app/52540/10
So, my idea is, to store the transcoded videos (360p, 480p, 720p, 1080p, ...) in the background and stream them. 
What are your thoughts about this?

**Comment by jakobroehrl** [comment]
Idea from @rullzer 
"And a small app kind of like the preview provider, combined with a dav collection (like the direct download) endpoint could work."

**Comment by tcitworld** [comment]
It will need a warning like "This will ~double the storage needed for each video".

**Comment by toast1234** [comment]
Optional background cleaning based on access time and/or size can maybe be a way of mitigate a growing preview folder. Not sure if that would be the task for an app or the core.

**Comment by PVince81** [comment]
and also not all video codecs are supported by the browser.

could also transcode GIFs to a smaller video for loading in the browser (like reddit does)

**Comment by PVince81** [comment]
here's also a more extensive discussion about transcoding: https://github.com/nextcloud/server/issues/604

**Comment by szaimen** [comment]
I don't think that we should implement a way to store transcoded videos and stream them because of storage concerns. 
We should more likely improve the video streaming itself and find out why it is somethings slow.

cc @nextcloud/server-triage for more input on this

**Comment by szaimen** [comment]
I'd recommend to use this flow app for the transcoding: https://github.com/cwilby/nextcloud-workflow-media-converter
So in my opinion this issue can be closed.
