### ISSUE TITLE
I just installed 19.0.0 on CENTOS8, LDAP-Groups are not visible.

### ISSUE THREAD

**Issue by sgiunchi** [nextcloud/server#21649]
I just installed 19.0.0 on CENTOS8, and I see this problem, LDAP-Groups are not visible.

_Originally posted by @sgiunchi in https://github.com/nextcloud/server/issues/19970#issuecomment-651903558_

As the ISSUE #19970  is closed and refers to NC 18.02, I opened this new issue.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by sgiunchi** [comment]
I'll double check, but the issue seems related to the referenced issue #19970 
I can see users and groups in AD setup, but I can't see groups afterwards.

**Comment by kesselb** [comment]
If you want to report a bug use the issue template. How do you think one could reproduce a problem if you provide zero information? 

https://help.nextcloud.com is the first place for questions and help to debug a problem.

**Comment by sgiunchi** [comment]
> If you want to report a bug use the issue template. How do you think one could reproduce a problem if you provide zero information?
> 
> https://help.nextcloud.com is the first place for questions and help to debug a problem.

I'm really sorry, as for me it's a regression, I thought that referencing to #19770 was enough. I'll do my homework, recheck the installation and post the issue template.
