### ISSUE TITLE
Downloads on mac OS clients (over 4GB) broken due to missing class TarHeader

### ISSUE THREAD

**Issue by lopezio** [nextcloud/server#21647]
### Steps to reproduce
1. Create a folder with content greater than 4 GB
2. Create a link (public) share (with or without password)
3. Share the link with a mac user
4. On the mac, open the share and click the overall Download button
5. A tar file is downloaded which has almost no content

### Expected behaviour
A Tar file with the archived content of the folder should be offered and downloaded by the browser

### Actual behaviour
A tar file is offered, which is only a few KB in size, actually containing html that hints to a server error with a request id. The request can be found in the logs (see below) and contains the rrror

### Server configuration
Nextcloud 19.0.0
PHP 7.4 
PHP-FPM
Apache 2.4 + PHP-FPM

**Operating system:**
FreeBSD 12.1

**Web server:**
Apache 2.4

**Database:**
MariaDB 10.2.x

**PHP version:**
7.4.x

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 14 via 15, 16, 17, 18

**Where did you install Nextcloud from:**
Downloaded releases from release page, upgraded without skipping major releases via php occ upgrade

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Yes LDAP

### Client configuration
**Browser:**
Firefox 

**Operating system:**
mac OS 10.12 High Sierra + Safari / Firefox / Chrome
mac OS 10.13 Mojave + Safari / Firefox / Chrome

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"dFxKggV649buD7zfqcjZ","level":3,"time":"2020-07-01T09:17:56+00:00","remoteAddr":"x.x.x.x","user":"--","app":"index","method":"GET","url":"/s/xxxxxxxxxxxxx/download","message":{"Exception":"Exception","Message":"Class 'ownCloud\\TarStreamer\\TarHeader' not found",
```
</details>

#### Workaround 

What worked (for now):

Adding the content (the class) of https://raw.githubusercontent.com/owncloud/TarStreamer/master/src/TarHeader.php
to ./3rdparty/deepdiver1975/tarstreamer/src/TarStreamer.php

the TarHeader class should be kept in the tarstreamer package.

**Comment by kesselb** [comment]
:see_no_evil:
