### ISSUE TITLE
Icon is missing in settings menu if text-overflow is reached

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#21659]
### Steps to reproduce
1. Select russian language for interface
2. Check "groupware" icon in admin settings page

![изображение](https://user-images.githubusercontent.com/12619075/86390428-61a0a880-bcdb-11ea-94b3-d2438c5a61fa.png)

If you cut text in browser html editor or remove "text-overflow" css property, icon appears

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

---

cc @nextcloud/javascript maybe there is a simple fix to this?

**Comment by szaimen** [comment]
I think this is solved in the meantime
