### ISSUE TITLE
autocomplete in comments seems broken in 19

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#21651]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a file
2. Share the file with another user
3. Go to the comments and try @mentioning them

### Expected behaviour
After typing @(name) you expect a auto-complete to show up

### Actual behaviour
There is no auto-complete.
If you know the user name and type @(username) and send the comment it will work

### Server configuration
cloud.nextcloud.com
private cloud, also with Nc 19

**PHP version:**
7.2.x and whatever is on cloud.nc.c

**Nextcloud version:** (see Nextcloud admin page)
19.0.0

#### Browser log
No errors that I can see, just deprecation warnings.

```
$ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

  | $ | @ | comments.js:50
-- | -- | -- | --
  | get | @ | comments.js:50
  | _onTextChange | @ | comments.js?v=24847595-66:1
  | dispatch | @ | jquery.js:564
  | v.handle | @ | jquery.js:564

@blizzz you might be able to have a look...

**Comment by jakobroehrl** [comment]
Duplicate of https://github.com/nextcloud/server/issues/19523 ?

**Comment by jospoortvliet** [comment]
> Duplicate of #19523 ?

You are very likely right. Will add my comment there and close this, thanks!
