### ISSUE TITLE
LDAP users empty email on nextcloud

### ISSUE THREAD

**Issue by jsalatiel** [nextcloud/server#21672]
### Steps to reproduce
1. Configure LDAP ( Around 1000 users  in this case)
2. List users

### Expected behaviour
Users should have the email imported from LDAP ( AD in this case )

### Actual behaviour
Most users do not have email set on nextcloud, although all of them have email set on active directory and correctly returned by an ldap_search. Without email set they do not receive notifications from nextcloud activities.

### Server configuration
**Docker container** 18.06

**Database:** postgresql 10

**Nextcloud version:** (see Nextcloud admin page) 18.06

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Docker Official Image

</details>

**Are you using encryption:**  No

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
+-------------------------------+----------------------
| Configuration                 | s01                 |
+-------------------------------+----------------------
| hasMemberOfFilterSupport      | 1                   |
| homeFolderNamingRule          |                     |
| lastJpegPhotoLookup           | 0                   |
| ldapAgentName                 | sensitive           |
| ldapAgentPassword             | sensitive           |
| ldapAttributesForGroupSearch  |                     |
| ldapAttributesForUserSearch   | displayName;mail    |
| ldapBackupHost                |                     |
| ldapBackupPort                |                     |
| ldapBase                      | sensitive           |  
| ldapBaseGroups                | sensitive           |  
| ldapBaseUsers                 | sensitive           |
| ldapCacheTTL                  | 120                 |
| ldapConfigurationActive       | 1                   |
| ldapDefaultPPolicyDN          |                     |
| ldapDynamicGroupMemberURL     |                     |
| ldapEmailAttribute            | mail                |
| ldapExperiencedAdmin          | 0                   |
| ldapExpertUUIDGroupAttr       |                     |
| ldapExpertUUIDUserAttr        |                     |
| ldapExpertUsernameAttr        | samAccountName      |
| ldapExtStorageHomeAttribute   |                     |
| ldapGidNumber                 | gidNumber           |
| ldapGroupDisplayName          | cn                  |
| ldapGroupFilter               | sensitive           |
| ldapGroupFilterGroups         |                     |
| ldapGroupFilterMode           | 0                   |
| ldapGroupFilterObjectclass    |                     |
| ldapGroupMemberAssocAttr      | member              |
| ldapHost                      | sensitive           |
| ldapIgnoreNamingRules         |                     |
| ldapLoginFilter               | sensitive           |
| ldapLoginFilterAttributes     |                     |
| ldapLoginFilterEmail          | 1                   |
| ldapLoginFilterMode           | 1                   |
| ldapLoginFilterUsername       | 1                   |
| ldapNestedGroups              | 1                   |
| ldapOverrideMainServer        |                     |
| ldapPagingSize                | 500                 |
| ldapPort                      | 389                 |
| ldapQuotaAttribute            |                     |
| ldapQuotaDefault              |                     |
| ldapTLS                       | 0                   |
| ldapUserAvatarRule            | default             |
| ldapUserDisplayName           | displayname         |
| ldapUserDisplayName2          |                     |
| ldapUserFilter                | sensitive           |
| ldapUserFilterGroups          |                     |
| ldapUserFilterMode            | 0                   |
| ldapUserFilterObjectclass     | person              |
| ldapUuidGroupAttribute        | auto                |
| ldapUuidUserAttribute         | auto                |
| turnOffCertCheck              | 1                   |
| turnOnPasswordChange          | 0                   |
| useMemberOfToDetectMembership | 1                   |




```
</details>

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Nothing related there
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```

Lots of: Info | user_ldap | No or empty name for cn= _sensitive_ with filter _sensitive_ 

Although login works just fine even for the user it complains about the empy name.



```
</details>

**Comment by johkoenig** [comment]
Please check that the LDAP attribute "mail" returns the e-mail addresses of the users. Depending on the system configuration, it may be a different attribute (e.g. mailPrimaryAddress on UCS).

cc @nextcloud/ldap

**Comment by jsalatiel** [comment]
Hi @johkoenig , Yes, I have checked that. If i run the command ldap_search with the samefilter I have on nextcloud I can see the attribute mail returns the email just fine. And as I have mentioned on this issue, the issue does not affect all ldap users. I'd say it affects around 80%.

**Comment by MorrisJobke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by jsalatiel** [comment]
Hi @MorrisJobke , tks! I will raise the question on the forums, although I do not think it is an setup issue because about 20% of the users retrieve the email just fine and I see the logs flooded with
 'Info | user_ldap | No or empty name for cn= _sensitive_ with filter _sensitive_ '

. Besides that, I use the same ldap filter I use in several other apps and all of them display the email correctly.
Concerning the subscription, I am quoting that already. Tks.

**Comment by MorrisJobke** [comment]
> Hi @MorrisJobke , tks! I will raise the question on the forums, although I do not think it is an setup issue because about 20% of the users retrieve the email just fine and I see the logs flooded with
> 'Info | user_ldap | No or empty name for cn= _sensitive_ with filter _sensitive_ '

At least it looks suspicious. On the other side. There are thousand of instances out there that have a working LDAP setup with emails properly being propagated.

**Comment by ruhrmann** [comment]
Hi @jsalatiel ,
I have the same behaviour. For me it looks like the mail-field is populated not before the user logs in for the first time. 

Peter

**Comment by stanelie** [comment]
I have the same issue.
Nextcloud 19.0.2
