### ISSUE TITLE
Trigger app updates periodically when using via cron.php

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#21694]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
People who do not have access to crontab cannot trigger app updates automatically

**Describe the solution you'd like**
Somewhere in the system there should be a setting where the administrator can define a daily/weekly maintenance time frame (e.g. 2am to 4am). Somewhen during that maintenance time frame, app updates should also be executed when cron.php is called.

**Describe alternatives you've considered**
Another entry to crontab:  sudo -u www-data php occ app:list

**Additional context**
A status e-mail to all administrators about failed/successful app updates would be also nice.

**Comment by gary-kim** [comment]
Christoph actually has a app he's working on that does what you want: https://github.com/ChristophWurst/unattended_upgrades

**Comment by kesselb** [comment]
> https://github.com/ChristophWurst/unattended_upgrades
