### ISSUE TITLE
Return value of OCA\\ContactsInteraction\\Db\\CardSearchDao::findExisting() must be of the type string or null, resource returned

### ISSUE THREAD

**Issue by apg1980** [nextcloud/server#21696]
### Expected behavior
Address more then 1 recipients into the TO: field and send mail to them.
Mails shoult sent without error and should moved after into "Sent Objects".

### Actual behavior
If more then 1 recipient is added, mail is throw error 500 and safed to "Entwürfe"

### Mail app

**Mail app version:1.4.0

**Mailserver or service:Exchange 2016

### Server configuration

**Operating system**: Ubuntu 18.04 LTS

**Web server:** Apache

**Database:** Postgresql

**PHP version:** 7.3 FPM

**Nextcloud Version:** NC 19

#### Client configuration
**Browser:** Latest Firefox

Nextcloud Log after the Issue:
`{"reqId":"ekArlJ0hf7ZnM4oOTgO3","level":3,"time":"2020-07-05T07:30:57+02:00","remoteAddr":"93.235.176.146","user":"08598A5C-6FB6-450C-A152-628B33F56156","app":"mail","method":"POST","url":"/apps/mail/api/accounts/10/send","message":{"Exception":"Exception","Message":"Return value of OCA\\ContactsInteraction\\Db\\CardSearchDao::findExisting() must be of the type string or null, resource returned","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"10","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"10","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"10","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/10/send"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Return value of OCA\\ContactsInteraction\\Db\\CardSearchDao::findExisting() must be of the type string or null, resource returned","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/contactsinteraction/lib/Listeners/ContactInteractionListener.php","line":120,"function":"findExisting","class":"OCA\\ContactsInteraction\\Db\\CardSearchDao","type":"->","args":[{"__class__":"OC\\User\\User"},null,"<email removed>",null]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\ContactsInteraction\\Listeners\\ContactInteractionListener","type":"->","args":[{"__class__":"OCP\\Contacts\\Events\\ContactInteractedWithEvent"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCP\\Contacts\\Events\\ContactInteractedWithEvent"},"OCP\\Contacts\\Events\\ContactInteractedWithEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"}],"OCP\\Contacts\\Events\\ContactInteractedWithEvent",{"__class__":"OCP\\Contacts\\Events\\ContactInteractedWithEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCP\\Contacts\\Events\\ContactInteractedWithEvent"},"OCP\\Contacts\\Events\\ContactInteractedWithEvent"]},{"file":"/var/www/nextcloud/apps/mail/lib/Listener/InteractionListener.php","line":84,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCP\\Contacts\\Events\\ContactInteractedWithEvent",{"__class__":"OCP\\Contacts\\Events\\ContactInteractedWithEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","line":76,"function":"handle","class":"OCA\\Mail\\Listener\\InteractionListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":251,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"},"OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"},{"__class__":"Closure"}],"OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/EventDispatcher.php","line":86,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"},"OCA\\Mail\\Events\\MessageSentEvent"]},{"file":"/var/www/nextcloud/apps/mail/lib/Service/MailTransmission.php","line":180,"function":"dispatch","class":"OC\\EventDispatcher\\EventDispatcher","type":"->","args":["OCA\\Mail\\Events\\MessageSentEvent",{"__class__":"OCA\\Mail\\Events\\MessageSentEvent"}]},{"file":"/var/www/nextcloud/apps/mail/lib/Controller/AccountsController.php","line":345,"function":"sendMessage","class":"OCA\\Mail\\Service\\MailTransmission","type":"->","args":[{"__class__":"OCA\\Mail\\Model\\NewMessageData"},null,null,73]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":170,"function":"send","class":"OCA\\Mail\\Controller\\AccountsController","type":"->","args":[10,"Test mit direkt Link zu einem Inhalt","<data removed>\n\n\ndas zum Beispiel ist ein direkter Link zum LuD Plan Juli.","<email removed>, \"<Name Removed> (<email removed>)\" <<email removed>>","","",false,73,null,null,[],null]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":137,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Mail\\Controller\\AccountsController"},"send"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php","line":47,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Mail\\Controller\\AccountsController","send",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"accountId":"10","_route":"mail.accounts.send"}]},{"function":"__invoke","class":"OC\\AppFramework\\Routing\\RouteActionHandler","type":"->","args":[{"accountId":"10","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":297,"function":"call_user_func","args":[{"__class__":"OC\\AppFramework\\Routing\\RouteActionHandler"},{"accountId":"10","_route":"mail.accounts.send"}]},{"file":"/var/www/nextcloud/lib/base.php","line":1007,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/apps/mail/api/accounts/10/send"]},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/nextcloud/apps/contactsinteraction/lib/Db/CardSearchDao.php","Line":89},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.0.12","id":"5f016b1e847d9"}`

**Comment by dehnhardt** [comment]
For some time now I do have the same Problem:

[mail] Error: Exception: Return value of OCA\ContactsInteraction\Db\CardSearchDao::findExisting() must be of the type string or null, resource returned at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/App.php line 137
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Mail\Controller\AccountsController {}, "send")
1. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Mail\\Cont ... r", "send", OC\AppFramework\ ... {}, {accountId: "1", ... "})
2. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({accountId: "1", ... "})
3. /var/www/nextcloud/lib/private/Route/Router.php line 297
   call_user_func(OC\AppFramework\ ... {}, {accountId: "1", ... "})
4. /var/www/nextcloud/lib/base.php line 1012
   OC\Route\Router->match("/apps/mail/api/accounts/1/send")
5. /var/www/nextcloud/index.php line 37
   OC::handleRequest()

POST /apps/mail/api/accounts/1/send
from 92.195.116.210 by holger at 2020-09-12T07:10:19+00:00


Operating system: Linux 5.4.6-xen #546 SMP Wed Dec 25 17:46:43 CET 2019 x86_64

MailApp: 1.4.1

Webserver: Apache (fpm-fcgi)

Database: pgsql PostgreSQL 12.4 (Debian 12.4-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit

PHP version: 7.3.19-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, PDO, xml, apcu, bcmath, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, intl, json, ldap, exif, pdo_pgsql, pgsql, apc, posix, readline, redis, shmop, SimpleXML, sockets, ssh2, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

Nextcloud version: 19.0.3 - 19.0.3.1

Browser: Chrome latest

**Comment by kruthoff** [comment]
Me too, _exactly_ the same error in nextcloud.log (above). Mail is received, on the other hand, but nextcloud mail app displays an error, and email is not stored into the sent mail folder.

Is more information required to solve this issue?

nginx:
`
192.168.1.70 - - [15/Oct/2020:21:50:54 +0200] "POST /apps/mail/api/accounts/3/send HTTP/2.0" 500 62 "-" "Mozilla/5.0 (X11; Linux armv7l) AppleWebKit/537.36 (KHTML, like Gecko) Raspbian Chromium/78.0.3904.108 Chrome/78.0.3904.108 Safari/537.36" "-" - -, -
`

**Comment by dehnhardt** [comment]
@kruthoff Is your database server PostgreSQL as well?

**Comment by kruthoff** [comment]
Yes. Postgres 11. Nextcloud 19.

**Comment by dehnhardt** [comment]
This seems to affect only Postgres users...

**Comment by hicwic** [comment]
same for me, but with the "share by email fonction". Email is sent, but an error popup, and the page is not refreshed.

Nextcloud 20

**Comment by poltrian** [comment]
same here on 20.0.0.1 but Email was not send
Error: Request failed with status code 500 
Answer and forward does not work, only sending

**Comment by ChristophWurst** [comment]
Fixed via https://github.com/nextcloud/server/pull/24096
