### ISSUE TITLE
Security Measures for "Login flow v2" ?

### ISSUE THREAD

**Issue by githubkoma** [nextcloud/server#21698]
Dear Team,

i discovered [Login flow v2](https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2.)

My **Question** is at the bottom :-)

Lets say, a phisher tries to use that API to initiate the Retrieval of an AppToken for UserXYZ, that is not himself.
`curl -X POST https://demo2.nextcloud.com/index.php/login/v2`
_(-> Using demo2.nextcloud.com in this example, but it could be nextcloud.ImportantCompany.com as well)_

The phisher gets back the following:
`{"poll":{"token":"3cx8pDOb3QJfQJDZDo4WemN4cjQDIhV4YZZELxeL7Wm5qWiIyZkYnLbZnbyS4IdEEakvVYMqxY1PM6tFr3Paam2dOstOjarCX4NfxGGFUFOxzjDjziJFdgX2A8NKoRH","endpoint":"https:\/\/demo2.nextcloud.com\/index.php\/login\/v2\/poll"},"login":"https:\/\/demo2.nextcloud.com\/index.php\/login\/v2\/flow\/ve5rsdvyLkgPjMU8ozIDf2Q0YVpz3aEj98oKQ59N3SiAzrwP9Zi0Rm1kdjgcQgRoE0OL9s52im0cGAlAZ18QG0MX63k4pemHVlCShGZbFYI4AvRJ985bBavDsz0Lqc21s"}`

The phisher then sends an EMail to UserXYZ at ImportantCompany Ltd. to open up the link and follow the instructions at:
https://demo2.nextcloud.com/index.php/login/v2/flow/ve5rsdvyLkgPjMU8ozIDf2Q0YVpz3aEj98oKQ59N3SiAzrwP9Zi0Rm1kdjgcQgRoE0OL9s52im0cGAlAZ18QG0MX63k4pemHVlCShGZbFYI4AvRJ985bBavDsz0Lqc21s

The phisher waits for the user to grant access and afterwards the phisher polls:
`curl -X POST https://demo2.nextcloud.com/login/v2/poll -d "token=3cx8pDOb3QJfQJDZDo4WemN4cjQDIhV4YZZELxeL7Wm5qWiIyZkYnLbZnbyS4IdEEakvVYMqxY1PM6tFr3Paam2dOstOjarCX4NfxGGFUFOxzjDjziJFdgX2A8NKoRH"`

So the phisher retrieves an AppToken für UserXYZ like:
```
{
    "server":"https:\/\/demo2.com.com",
    "loginName":"UserXYZ",
    "appPassword":"yKTVA4zgxjfivy52WqD8kW3M2pKGQr6srmUXMipRdunxjPFripJn0GMfmtNOqOolYSuJ6sCN"
}
```

I assume the phisher then can use all API Calls whatsoever of that Nextcloud's User named UserXYZ.

**Question** is: Are there any measures that prevent a phisher to use this method? 
Perhaps not only targeted for a specific user, but using this for a mass mailing phishing attack.
_(The phisher then of course has to build an infrastructure to mass-poll the API, which should be no problem)_

Am i missing something here?

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/5bf3d1bb384da56adbf205752be8f840aac3b0c5/core/Db/LoginFlowV2Mapper.php#L35 it It seems the token is valid for 30 minutes.

**Comment by nickvergessen** [comment]
Well if a user does this:

> # Connect to your account
> Please log in before granting xxx access to your Nextcloud account.

You lost already anyway. Sure we can improve the message, but on a technical level this is not an issue.
It's like preparing a page and asking the user to login with their nextcloud account on your page.

**Comment by githubkoma** [comment]
@nickvergessen 
as a phisher you dont even have to forge a page or spoof a domain

nextcloud presents the perfect login page under the correct domain

**Comment by nickvergessen** [comment]
Yeah, which is why we should extend the description a bit: https://github.com/nextcloud/server/pull/21706
But the technical thing is still valid. If someone logs in on any link you gave them `¯\_(ツ)_/¯`

**Comment by rullzer** [comment]
I mean in theory we could show 5 digit code. or something. But I doubt people will check.
It is in my opinion similar to granting others access via google or facebook. If you click yes at the moment that it shows you are about to give 'X' access to 'Y' then that is what you do.

also please always report security sensitive issues via hackerone

**Comment by githubkoma** [comment]
@nickvergessen 
thanks!

i am a bit irritated about the "disconnect" between the Client (who is intended to use an e.g. Native App originally)
and the one who polls the AppPassword. Of course, usually this is One Person. But it could also be 2 different Machines.

i myself perhaps would feel better, if the second /POST/ to actually retrieve the Token would be forced to originate from the same source-ip adress

that would deny a third party to poll the AppPassword

**Comment by githubkoma** [comment]
> also please always report security sensitive issues via hackerone

I'll keep that in mind with "hackerone"

The difference between Oauth2 is, that the IdP sends the user back to a trusted site, via redirect_uri.
So a phisher wouldnt be able to intercept the auth_code that the IdP 

Here with login flow v2 you just push out an Auth-Page to UserX and 
then, phase 2, to get the actual Token, a potential Phisher could sit anywhere in the world and pull that Token.
There is no redirect_uri mechanism

**Comment by kesselb** [comment]
Storing the ip address and show a warning on mismatch sounds good to me.

**Comment by kesselb** [comment]
Save the ip address and show a warning on mismatch sounds good to me.
