### ISSUE TITLE
armhf: MySQL username and/or password not valid You need to enter details of an existing account.

### ISSUE THREAD

**Issue by shuhaowu** [nextcloud/server#21690]
# Steps to reproduce
1. Setup a new installation of nextcloud on an armhf system (Raspberry PI OS, Armbian, take your pick) with docker.
2. Either try to create an admin user in the web installer or use the command 

```
sudo -u www-data php occ  \
maintenance:install --database "mysql" --database-name "nextcloud" \
--database-user "user" --database-pass "password" --database-host "mysql" \
--admin-user "admin" --admin-pass "pass"
```

See: https://help.nextcloud.com/t/trouble-installing-you-need-to-enter-details-of-an-existing-account/84657

### Expected behaviour
The admin user should be created.

### Actual behaviour
An error message shows up:

```
MySQL username and/or password not valid You need to enter details of an existing account.
```

If you examine the database at this point, you'll see that the `nextcloud` database has been created according to the `--database-name` option.

Looking at data/nextcloud.log shows:

```
An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'oc_admin'@'%' to database 'nextcloud'"
```

Looking at the actual MySQL server:

```
mysql> show grants for oc_admin@'%';
+--------------------------------------+
| Grants for oc_admin@%                |
+--------------------------------------+
| GRANT USAGE ON *.* TO `oc_admin`@`%` |
+--------------------------------------+
1 row in set (0.01 sec)

```

It looks like oc_admin is somehow incorrectly created?

### Server configuration

**Operating system:** Armbian Buster (armhf) + Docker

**Web server:** Apache (Docker image `19-apache`).

**Database:** MySQL

**PHP version:** 7? Whatever the `19-apache` docker image comes with

**Nextcloud version:** 19

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Official docker image

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Initializing nextcloud 19.0.0.11 ...
Initializing finished
New nextcloud instance
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.26.0.3. Set the 'ServerName' directive globally to suppress this message
[Sun Jul 05 00:34:29.305590 2020] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.38 (Debian) PHP/7.4.6 configured -- resuming normal operations
[Sun Jul 05 00:34:29.305821 2020] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.26.0.1 - - [05/Jul/2020:00:35:41 +0000] "GET / HTTP/1.1" 200 2779 "-" "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"
172.26.0.1 - - [05/Jul/2020:00:35:50 +0000] "POST /index.php HTTP/1.1" 200 3566 "-" "Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)

```
{"reqId":"ybOctU252NILqArHuHlg","level":3,"time":"2020-07-05T00:41:15+00:00","remoteAddr":"172.26.0.1","user":"--","app":"no app in context","method":"POST","url":"/index.php","message":{"Exception":"Doctrine\\DBAL\\DBALException","Message":"Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [1044] Access denied for user 'oc_admin'@'%' to database 'nextcloud'","Code":0,"Trace":[{"file":"/var/www/html/lib/private/Setup/MySQL.php","line":66,"function":"connect","class":"OC\\DB\\Connection","type":"->","args":[]},{"file":"/var/www/html/lib/private/Setup.php","line":358,"function":"setupDatabase","class":"OC\\Setup\\MySQL","type":"->","args":["admin"]},{"file":"/var/www/html/core/Controller/SetupController.php","line":75,"function":"install","class":"OC\\Setup","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/lib/base.php","line":945,"function":"run","class":"OC\\Core\\Controller\\SetupController","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/html/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/var/www/html/lib/private/DB/Connection.php","Line":67,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:78.0) Gecko/20100101 Firefox/78.0","version":"19.0.0.11"}

```

**Comment by shuhaowu** [comment]
Possibly related: https://github.com/nextcloud/server/issues/18513

**Comment by shuhaowu** [comment]
Looks like the problem is actually because the user I'm using to initialize the database doesn't have GRANT OPTIONS.

It may be a good idea to emit the message to the user. I spent half a day chasing my tails...

**Comment by holoword** [comment]
`grant all privileges on *.* to 'user'@'localhost' with grant option;`  can solve this problem

**Comment by stdcerr** [comment]
This helped me, Thank you!

**Comment by BenCloud75** [comment]
I faced this issue as well and struggle to solve it despite the `grant all privileges` action detailed above... 
I finally managed to solve it and succeeded in creating my NextCloud admin account. For that, I simply dropped my MariaDB data base and MariaDB user and recreated it through the Terminal : 

```
CREATE DATABASE your_NextCloud_Data_Base_Name;

CREATE USER 'your_Next_Cloud_User'@'localhost' IDENTIFIED BY 'your_Password';

GRANT ALL ON your_NextCloud_Data_Base_Name .* TO 'your_NextCloud_User'@'localhost';

FLUSH PRIVILEGES;
EXIT;
```

**Note** I hosted NextCloud on my Synology NAS

**Comment by GitHubxtsnl** [comment]
>
> ```
> CREATE DATABASE your_NextCloud_Data_Base_Name;
> 
> CREATE USER 'your_Next_Cloud_User'@'localhost' IDENTIFIED BY 'your_Password';
> 
> GRANT ALL ON your_NextCloud_Data_Base_Name .* TO 'your_NextCloud_User'@'localhost';
> 
> FLUSH PRIVILEGES;
> EXIT;
> ```
> 
> **Note** I hosted NextCloud on my Synology NAS

I'm using the Nextcloud package from http://digital.box.free.fr/dsm7/ on my Synology NAS with MariaDB (DS1520+ & DSM7.0.1).
I had the same issue when configuring the nextcloud instance, got the same error 

>
> ```
> MySQL username and/or password not valid You need to enter details of an existing account.
> ```
After using the method above everything is working like a charm.

**Comment by IngwiePhoenix** [comment]
> `grant all privileges on *.* to 'user'@'localhost' with grant option;` can solve this problem

Ran into this today too on a completely fresh setup.

This cost me three hours at least (plus another five that was about setting the right MySQL socket because PDO refused to tell me anything...).

Hoping to see this be addressed because several log outputs and error messages are quasi garbage as they have no helpful indicator that the grant never worked in the first place.

**Comment by numboDumbo** [comment]
> `grant all privileges on *.* to 'user'@'localhost' with grant option;` can solve this problem

Hey, how to run this?
I am using ansible with docker module to deploy, if that helps.

**Comment by EXCIDIVM** [comment]
> > `grant all privileges on *.* to 'user'@'localhost' with grant option;` can solve this problem
> 
> Hey, how to run this? I am using ansible with docker module to deploy, if that helps.

Terminal into your docker container. Then type:
`mysql -u root -p`

I can confirm that it works for me. Just had the same problem on a fresh install (on a Synology NAS). I am not sure what exactly fixed it, but I did both steps exactly as described by [BenCloud75](https://github.com/BenCloud75) and [IngwiePhoenix](https://github.com/IngwiePhoenix).

**Comment by Michael1337** [comment]
Ran into this, too. If you use docker, you can access your MySQL container using:
`docker exec -it mysql_container_name bash`
Then, to enter the MySQL service in the container as root:
`mysql -u root -p`
You need to be root because you most likely didn't give any other user the privilege to create new users.

Also: You may want to specify the "from host" part of the new user to be `@'%'` instead of `@'localhost'` depending on your overall setup. If your Nextcloud setup throws another error including an IP address, that might be the problem.

**Comment by Shadow8472** [comment]
I'm encountering this same error message. I'm reading the above comments, but I have absolutely no idea what's going on aside from MariaDB maybe having a now-patched bug and @'%' is another way of saying "localhost," but not really.

I have Nextcloud and MariaDB in their own containers within a Podman pod.
The pod and its contents are wiped between attempts.
Error showing up in logs as:
> [Warning] Access denied for user 'nextcloudDbUser'@'%' to database 'NextcloudDB'

It's good to know a solution is _probably_ here, even though I don't understand it yet.

**Comment by laidaJ** [comment]
> `grant all privileges on *.* to 'user'@'localhost' with grant option;` can solve this problem

many thanks,this works!
