### ISSUE TITLE
https://download.nextcloud.com/ certificate expired

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#21695]
The SSL certificate of download.nextcloud.com expired!

@nextcloud/infrastructure 

https://help.nextcloud.com/t/security-cert-expired-nc-website-unable-to-download/86587

**Comment by tribor1990** [comment]
can confirm, no download available.... anyone can hit me up with a zip to 19.0.0? really need to get it done soon :(

**Comment by rullzer** [comment]
Seems dehydrated didn't reload the webserver. all good again.
