### ISSUE TITLE
Theming app: preview for log in background image

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#217]
For the background image it would be good to have a small preview because unlike the logo it’s not visible in that view.

Simply have a small thumbnail below the upload button, about 400*300px or so should suffice.

**Comment by juliushaertl** [comment]
fixed with #1049

**Comment by jancborchardt** [comment]
@juliushaertl simply awesome! :)

By the way, you should give a quick lightning talk at the conf about the awesome new theming capabilities! (Don’t worry, the talks are only 5 minutes :) https://conf.nextcloud.com/conference/NextcloudConference2016/program/proposal/new

**Comment by juliushaertl** [comment]
@jancborchardt I've finally booked my hotel and submitted a proposal for a lightning talk. ;)

**Comment by jancborchardt** [comment]
Weeehu! :) Awesome to have you!
