### ISSUE TITLE
Token invalid

### ISSUE THREAD

**Issue by roberttilewick** [nextcloud/server#21707]
Why do I get this error on more than one server when I try to sign on?

**Comment by gary-kim** [comment]
Could you fill out the issue template? I'm not entirely sure what the issue you are experiencing is. Thank you.

https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by nickvergessen** [comment]
As per Gary, please fill out the complete issue template.

**Comment by roberttilewick** [comment]
I'll have to check; I'll go back

**Comment by roberttilewick** [comment]
I apologize for the missing info. As well, the error isn't repeating, so I'll make sure that if it does, I will provide all the needed info.
