### ISSUE TITLE
Move of read-only folder fails

### ISSUE THREAD

**Issue by joeltheukranian** [nextcloud/server#21719]
OS: Ubuntu 18.0.4
Version: NC 18.0.2
Server Config: Happens locally with a basic setup in ubuntu, and with External folders pointing to S3.

### Steps to reproduce
1. Create Folder F1 at root
2. Share F1 to Group1 with Editing/Creating/Deleting/Resharing off. (Read-only)
3. Login as Group1 (any user)
4. Move F1 to any other folder you have write access to

### Expected behaviour
I would expect the move to fail because we don't have write access to F1

### Actual behaviour
Dialog on top right "Could not move F1"

Move works fine if admin user does the move.

Was trying to track down an error in the logs, but I couldn't find anything that appeared related.

Attached logs in case they might help.

[nextcloud.zip](https://github.com/nextcloud/server/files/4879731/nextcloud.zip)
[nextcloud.Excel_filtered.zip](https://github.com/nextcloud/server/files/4879736/nextcloud.Excel_filtered.zip)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
