### ISSUE TITLE
Problem with birthday on Dec 31st

### ISSUE THREAD

**Issue by drupalwonder** [nextcloud/server#2171]
Hi there,

First of all: Thanx a lot for doing such a great work :)

My problem: One of my colleagues is born on December 31st (lets say Dolly is born on 1984-12-31), but the entry in the contacts birthday calendar is "Dolly (*1985)", so Dolly was made a year younger. Well that's charming for Dolly ... but it's a bug I suppose (and not a feature).

Nexcloud is running in version 10.

Has anybody an idea?

Greetz (especially to georgehrke)
Jürgen

**Comment by MariusBluem** [comment]
@georgehrke

**Comment by georgehrke** [comment]
🙈

**Comment by georgehrke** [comment]
fix is in https://github.com/nextcloud/server/pull/2173
