### ISSUE TITLE
Projects tab on the side bar doesn't update correctly

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#21727]
I noticed this already a few times on our instance. We have a Talk room where to request long term demos. With the project features we added  a spreadsheet to the room which keeps track in the running LTD's.

When I go to the room for the first time after some time (~24 hours), open the right sidebar and go to "Projects" the list of projects is empty. Only after a hard refresh the spreadsheet shows up. Then I can close the sidebar, leave the room, come back, open the sidebar again and the spreadsheet is still shown. So it seems some caching issue because when I stay away from the room long enough it lose the project list again.

One way I can trigger this behavior:

1. The file is shown correctly in the Projects sidebar.
2. I go to another room with no Projects.
3. Go to the empty projects tab of the room
4. Do a hard refresh (Ctrl+R)
5. Go back to the room with the project
6. The project is empty again.
7. Do a hard refresh (Ctrl+R)
8. The project shows up
9. Now I can switch room and every time I come back the spreadsheet on the Projects tab shows up until I do again a hard refresh on another room.

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
