### ISSUE TITLE
Custom favicon on NC19

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#21731]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install the latest version of Nextcloud 19
2. Create a new custom theme and activate it in configuration file
3. Add a custom favicon in nextcloud/themes/mytemplate/core/img/favicon.ico

### Expected behaviour
The favicon should be the new .ico from the themes

### Actual behaviour
Getting the default favicon nextcloud/core/img/favicon.ico

### Server configuration

**Operating system:**
Centos 7

**Web server:**
Apache

**Database:**
MariaDB

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
19

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases

**Comment by Silv4n** [comment]
Did you clear the browser cache or tried it on a different browser?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
