### ISSUE TITLE
Upgrade to 19.0.0 from 18.0.4. via Softaculous stops with an error

### ISSUE THREAD

**Issue by brdobrdo** [nextcloud/server#21737]
### Steps to reproduce
1. Go to CPanel --> Softaculous --> Script instalations and click blue arrows for upgrade of Nextcloud
2. Wait for Softaculous to finish and give you a link to your nextcloud instance for you to click so upgrade can finish
3. Click on the link, nextcloud opens in the browser and starts to upgrade... 

### Expected behaviour
It should update from version 18.0.4 to 19.0.0

### Actual behaviour
After step 3 it starts to update, there is log on the screen and then it stops with an error, goes to maintenance mode and you cannot use your nextcloud any more. I restored 18.0.4. from backup.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

For your next report here: Please always use the issue template and provide the exact error message. An error is nothing one can work with.
