### ISSUE TITLE
Recommended URL for CalDAV is not useful for Thunderbird

### ISSUE THREAD

**Issue by Gittum** [nextcloud/server#21744]
In NC I have a shared calendar. Under 'Settings & Import' in the left lower edge I found some hints to synchronize this calendar to my Thunderbird. 

But there are the Strings:
primary CalDAv Address: https://<my host>/remote.php/dav 
IOS/macOS: https://<my host>/remote.php/dav/principals/users/<myuser>

Both of them are not successful. I have to use:
https://<my host>/remote.php/dav/calendars/<user>/<calendarname>

To get the CalDAV synced w/o a hints is not easy at the first time. But get it synced with a misleading hind ...

### Steps to reproduce
1. Go to a calendar
2. Look to the hint in the edge left below
3.

### Expected behaviour
There should be a correct URL

### Actual behaviour
There is a URL copied that is not functionating

**Nextcloud version:** (see Nextcloud admin page)
18.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Comment by kesselb** [comment]
cc @nextcloud/calendar

**Comment by georgehrke** [comment]
https://docs.nextcloud.com/server/19/user_manual/pim/sync_thunderbird.html#the-old-method-manually-subscribing-to-calendars

**Comment by Gittum** [comment]
From my POV it is not helpful to set a link to documentation and close this thread.

When a new user try to configure he get the wrong string from NC and can not success! This will end in question to the admin or an unlucky user who tells NC is crap. 

At least dev should remove this wrong hint! No hint seems better then a wrong hint.

**Comment by georgehrke** [comment]
> At least dev should remove this wrong hint! No hint seems better then a wrong hint.

The "Primary CalDAV address" is working in pretty much all clients (DavDroid, Evolution, KOrganizer, ...), with the exception of Thunderbird.

Thunderbird Lightning cannot automatically find all calendars itself, but you have to subscribe to each calendar individually.

**Comment by tcitworld** [comment]
Also the the documentation states the recommended way is to use the TBSync addon that works with the Primary CalDAV URL.

Feel free to subscribe to this Lightning bug (which seems to be in progress): https://bugzilla.mozilla.org/show_bug.cgi?id=306495
