### ISSUE TITLE
Login form loads after alternative logins

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#21756]
I guest this is because login form is vue component now and loaded lately.
Maybe set height of vue app container of login form in guest page styles ?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by zorn-v** [comment]
Yep. There is a gif about what I mean (I press F5 five times there)
![Peek 2021-06-08 01-57](https://user-images.githubusercontent.com/12619075/121051899-34b71880-c7fd-11eb-875f-866cc2fb8071.gif)

take into account that it on LOCALHOST, and imagine how it seems on real hosting.

**Comment by szaimen** [comment]
Thanks for the GIF!

**Comment by zorn-v** [comment]
Check in action BTW )
https://admin.inter-cat.net

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by szaimen** [comment]
thanks for verifying!
