### ISSUE TITLE
LDAP: Add attribute mapping for first and last name

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#21762]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Currently, Nextcloud is only pulling the displayName from LDAP. For people with more complex names than just "Firstname Lastname" this often leads to wrong interpretation what the first name and the last name are. For example, many people have two first names (John Jacob Astor), however, I know a person who is named similar to "Simon Schuster Müller". In this case, "Schuster Müller" (with space in between!)  is his last name. Currently, there is no way to distinguish between the names and so, taking initials for the contact list bubble (if no photo is given) will not work correctly in at least one case.

Another situation, which I am facing right now on my NC, is that somebody has a university title. Here, you can see that the talk app is unable to pull the first name correctly:
![bug](https://user-images.githubusercontent.com/42836313/86967728-50d4b480-c16b-11ea-8c1b-1cf9ade5537c.png)

Also, the bubble with the initials (before the photo was added) was "DS" instead of "SK". 

**Describe the solution you'd like**
Add options the LDAP interface to define the attributes for first name and last name.

**Describe alternatives you've considered**
Updating the automatic detection algoritm. But that will never cover all cases from around the world.

**Additional context**
Here some examples of tricky situations:
- Three names, as stated above (2 first names or 2 last names)
- prefixes and suffixes (Dr. John Doe Jr.)
- asian vs. western order: Liu Chang ("Lui" is last name) vs. John Doe

**Comment by kesselb** [comment]
As reference: https://github.com/nextcloud/server/pull/21369#issuecomment-643813728

**Comment by johkoenig** [comment]
cc @nextcloud/ldap

**Comment by mdoggydog** [comment]
When/if this is implemented, please consider labeling these two names as "given name" and "surname" (or "family name"), e.g., similar to the attributes in LDAP, which are trying to be order-independent (not "first" versus "last").

And/or, consider instead defining an identifier with more functional semantics to it, i.e., a "nickname" which is intended to be used where a shortened identifier is appropriate.  It would be great to be able to specify "Use LDAP `uid` attribute as the short-name", especially when the internal Nextcloud userid is really an LDAP UUID ("1ae3fa62-54ec-109a-9879-bf1a7c84922f"), which is something that nobody ever (ever) wants to see anywhere.

I'm not sure there are many cases where NC would need to display someone's "family name" independent of their full name, but I can see cases where a canonical "short name" would be handy.

**Comment by johkoenig** [comment]
Example use cases are:
* Correctly sorting by last name indipendent of displayName
* Correctly adressing people informally (Hello John)

In the end, it breaks down to "first name and last name do not need to pulled from displayName"

**Comment by blizzz** [comment]
In Nextcloud, for users we have only a user id (not end user facing) and the display name. It is free form, which allows to place any structure therein.

The LDAP backend reads a display name from LDAP. We expect it to be exactly what it is: the full name of the user displayed in the desired form.

For searching the LDAP backend utilizes the LDAP server's functionality. The attributes that should be taken into account can be specified in the user search attributes (https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_auth_ldap.html#directory-settings). If nothing is entered (default), it falls back to the display name. Most often it makes sense to specificy there "sn" and "givenName" to be able to search in given and sur name separately. 

What is not solved by this approach?

**Comment by johkoenig** [comment]
@blizz,
I see your point that currently, there is no specific situation where seperate first names and last names are needed. The problem in the talk app has been solved by disabling the guessing of the first name, see nextcloud/spreed#3888 and nextcloud/spreed#3901.

If the talk-developers want to bring back the adressing with first name only to their app, this would be use-case where a seperate frist name is needed. Maybe @nickvergessen can say something about this.
Apart from that, I don't see a use-case right now, especially since manually created users also only have a display name and no seperate fields for first and last name.

Feel free to close this if you think it is not needed.

**Comment by nickvergessen** [comment]
Yeah fixed by using the full name again in talk. We don't know if first name is appriciated anyway (it's not in most enterprises)
