### ISSUE TITLE
preview generator not work

### ISSUE THREAD

**Issue by beniyas** [nextcloud/server#21763]
error came to leave in preview generator when update did mariadb for 10.5 series.

run php ./occ preview:pre-generate
----
In Folder.php line 164:
Could not create folder
---

after mariadb 10.4 -> 10.5 updated

### Server configuration

linux-5.4.39

**Web server:**
apache-2.4.43

**Database:**
mariadb-10.5.4

**PHP version:**
php-7.4.7 fpm-cgi

**Nextcloud version:** (see Nextcloud admin page)
18.06

**Nextcloud configuration:**
<?php
$CONFIG = array (
  'instanceid' => 'oc1uvhywx96n',
  'passwordsalt' => 'beGJTGCcQnDeV9k7z1hdt+jZeOsLvV',
  'secret' => 'xg+yJjKxzGFnGxqc9Mx2gYq+PHKSsnF3yEOyh5c5JZ53bhBc',
  'trusted_domains' =>
  array (
    0 => 'cloud.sinfonia.or.jp',
  ),
  'preview_max_x' => '1800',
  'preview_max_y' => '1000',
  'preview_max_scale_factor' => '1',
  array (
    1 => '',
  ),
  'datadirectory' => '/next/data',
  'dbtype' => 'mysql',
  'version' => '18.0.6.0',
  'overwrite.cli.url' => 'https://cloud.sinfonia.or.jp/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'Okafuji4612',
  'enable_previews' => 'true',
  'installed' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'theme' => '',
  'mail_from_address' => 'Admin',
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => 'cloud.sinfonia.or.jp',
  'mail_smtphost' => 'cloud.sinfonia.or.jp',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauthtype' => 'LOGIN',
  'maintenance' => false,
  'loglevel' => 2,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'app_install_overwrite' =>
  array (
    0 => 'preview_webp',
  ),
);

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by cweiske** [comment]
I also have this problem, about once per week with Nextcloud Hub 6 (27.1.9).

I get notified about it via e-mail from cron:
> Subject: Cron <www-system@ahso4> php8.2 -f /var/www/system/wolke.cweiske.de/occ preview:pre-generate > /dev/null
> 2024-07-09T08:15:13+00:00 
> 2024-07-09T08:15:13+00:00 In Folder.php line 162:
> 2024-07-09T08:15:13+00:00                                                                                
> 2024-07-09T08:15:13+00:00   Could not create folder "/appdata_528f7ea160b90/preview/7/1/e/2/9/2/b/18059  
> 2024-07-09T08:15:13+00:00   98"                                                                          
> 2024-07-09T08:15:13+00:00                                                                                
> 2024-07-09T08:15:13+00:00 
> 2024-07-09T08:15:13+00:00 preview:pre-generate
> 2024-07-09T08:15:13+00:00 

When checking the file system, the folder exists, and it contains files.

My guess is that some parallel jobs try to create the same folder, and because of this race condition it exists in one of the code paths.

----

Related:
- [nextcloudpi: nc_previews : Could not create folder #1260](https://github.com/nextcloud/nextcloudpi/issues/1260)
- [nextcloud forum: Error: NotPermittedException Could not create folder “/appdata_ocXXXXX/preview/8/b/d/e/8/a/c/554139”](https://help.nextcloud.com/t/error-notpermittedexception-could-not-create-folder-appdata-ocxxxxx-preview-8-b-d-e-8-a-c-554139/179321)
