### ISSUE TITLE
Theming app: also change other icons to selected logo

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#218]
The other icons like favicon are not changed yet. We should have some code to automatically convert the logo in to all the different things like favicon and mail header icon.

cc @schiessle @LukasReschke

**Comment by mar1u5** [comment]
It is also possible to change the login-logo independent from the logo on the top by creating an theme. Shouldn't this also be possible with theming?

**Comment by jancborchardt** [comment]
@mar1u5 no, we intentionally phased out that difference, and we'll keep it that way to make theming as simple as possible first. We still need to fix some stuff there, so this is not the time to complicate it yet. :)

**Comment by juliushaertl** [comment]
I've played a bit with generating dynamic icons, it is still quite a mess, but I'm working on this. SVG support in Imagemagick is really crappy. :disappointed:

**Comment by blizzz** [comment]
Looks like bigger changes, due to the RC knocking at the door, let's also move this milestone to 11.

**Comment by juliushaertl** [comment]
Fixed with #840

**Comment by jancborchardt** [comment]
Wohooo @juliushaertl :)
