### ISSUE TITLE
iOs does not upload file and delete it from transfer queue

### ISSUE THREAD

**Issue by 4d1830** [nextcloud/server#21808]
### Steps to reproduce
1. take a screenshoot or make a photo
2. phone is "off-line mode"
3. enter inside nexcloud app (off-line mode)
4. check if new file is added to upload queue
5. Quit from app
6. Put online mode
7. Go back in the app
8. check "transfers" area

### Expected behaviour
New file should be uploaded

### Actual behaviour
Photo (or new file) is not uploaded but deleted from transfer queue

### Server configuration

**Operating system:** iOs 13.5.1

**Web server:** N/A

**Database:** mysql 10.3.23

**PHP version:** 7.3.19

**Nextcloud version:** (see Nextcloud admin page) 18.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Hetzner Cloud Service

**Where did you install Nextcloud from:** Hetzner Cloud Service

Please check attached screencast: [Link](https://www.dropbox.com/s/kga8rbvyivpomaz/Nextcloud%20Bug%3F.mov?dl=0)

**Comment by eibex** [comment]
You should have raised the issue here: https://github.com/nextcloud/ios

In any case, I cannot reproduce.

**Comment by 4d1830** [comment]
> You should have raised the issue here: https://github.com/nextcloud/ios
> 
> In any case, I cannot reproduce.

Thank's a lot, sorry it was my first post here on github, I opened here: https://github.com/nextcloud/ios/issues/1346 .

How I can close/delete this issue?
