### ISSUE TITLE
treat audio like video - audio and video player default in nextcloud

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#21805]
In Nextcloud is a video player and it works fine.
But in Nextcloud is not a music player.

If i want to see a video i click on the video.
If i share the video another people can click on the video and see it.

If i want to hear a music file (e.g. mp3) i must install an audio app for usage in nextcloud gui.
If i share the mp3 directly i do not need a audio player.  Why?
That makes all no sense.

I think there is no difference between audio and video.
Please insert default audio playing or remove video playing from nextcloud

Read and see/hear (hear not) examples:
https://help.nextcloud.com/t/how-to-play-a-movie-in-nextcloud/87119/2

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/viewer/issues/126

**Comment by devnull4242** [comment]
Ok. There is NO default audio app because AUDIO has more features than VIDEO. On a preinstalled Nextcloud like https://nc.nl.tab.digial i can now watch videos but not hear music because of SONOS ... What a pity.

https://github.com/nextcloud/viewer/issues/126#issuecomment-499624880: 
naja,
I think Music and Audio Player are different by design - which is also backed by their user numbers.
They differ in UI, formats or backends.

As mentioned e.g. Music has a cleaner UI, where as AP has more flexibility.

but what might actually be interesting would be a more modular setup for the add-ons.
Music has e.g. Ampache backend within the app itself. This is the second most request for AP at the moment. I implemented a Sonos-Backend in AP. This would also make more sense as an add-on.

**Comment by kesselb** [comment]
> Ok. There is NO default audio app because AUDIO has more features than VIDEO. On a preinstalled Nextcloud like https://nc.nl.tab.digial i can now watch videos but not hear music because of SONOS ... What a pity.

Your conclusion is wrong. Viewer does not play audio files because nobody added support for it (yet).
