### ISSUE TITLE
App Login credentials not working

### ISSUE THREAD

**Issue by ka223** [nextcloud/server#21845]
I am using nextcloud 18.0.6 and recently upgraded from 18.0.3.

The additional app passwords from security -> devices & sessions are not working. Passwords are generated over the "Create new app password" button.

I created a new app password, the android nextcloud app responds with incorrect credentials, same by using a browser and the app login.

The log says:
```
Info core Bruteforce attempt from “****” detected for action “login”.
Warning no app in context Login failed: **** (Remote IP: ****)
```

I cleared the database bruteforce attempt entry with my IP address, but at the first login attempt with the correct (generated) _app login_ credentials, a new bruteforce attempt entry is created in the database and the login is rejected with "Wrong username or password. "

Update:
**_Just tested on a nextcloud hoster with 18.0.6 (updated from 18.0.3), with the same problem!_**

### Steps to reproduce
1. maybe upgrade from18.0.3. to 18.0.6 
2.  "Create new app password"
3. Login with the generated password inside browser or android nextcloud app

### Expected behaviour
Login successful.

### Actual behaviour
Error Message "Wrong username or password. "

### Server configuration

Debian buster

**Web server:**
Apache 2.4.38-3+deb10u3

**Database:**
MariaDB

**PHP version:**
php 7.3

**Nextcloud version: 18.0.6 

**Updated from an older Nextcloud/ownCloud or fresh install:** 
18.0.3.

**Where did you install Nextcloud from:**
https://nextcloud.com/install/
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notes: 3.6.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - encryption
  - federation
  - files_external
  - files_sharing
  - user_ldap
```

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.***.**",
            "*****.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/192.168.***.**\/nextcloud",
        "dbtype": "mysql",
        "version": "18.0.6.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": true,
        "loglevel": 0,
        "theme": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "updatechecker": false,
        "appstoreenabled": true,
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/nextcloud",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```

**Comment by MaxXor** [comment]
Same problem on 19.0.1, newly generated app passwords are no longer working.

**Comment by Palulukas** [comment]
Same problem on 18.0.7, debian buster with Apache 2.4 and PHP 7.3

**Comment by nielsenb-jf** [comment]
I see the same thing here, errors in the log that I think are related look like this:

```
[no app in context] Warning: Login failed: nielsenb (Remote IP: 172.19.0.2)

POST /login
from 172.19.0.2 at 2020-08-18T21:23:35+00:00
```

I am running Nextcloud behind a reverse proxy with nginx to handle SSL. I managed to get things working by setting `'overwriteprotocol' => 'https'` in `config.php`.

**Comment by Palulukas** [comment]
> 
> 
> I see the same thing here, errors in the log that I think are related look like this:
> 
> ```
> [no app in context] Warning: Login failed: nielsenb (Remote IP: 172.19.0.2)
> 
> POST /login
> from 172.19.0.2 at 2020-08-18T21:23:35+00:00
> ```
> 
> I am running Nextcloud behind a reverse proxy with nginx to handle SSL. I managed to get things working by setting `'overwriteprotocol' => 'https'` in `config.php`.

Thannks for your effort, I'll try your fix very soon!

**Comment by ka223** [comment]
> I see the same thing here, errors in the log that I think are related look like this:
> 
> ```
> [no app in context] Warning: Login failed: nielsenb (Remote IP: 172.19.0.2)
> 
> POST /login
> from 172.19.0.2 at 2020-08-18T21:23:35+00:00
> ```
> 
> I am running Nextcloud behind a reverse proxy with nginx to handle SSL. I managed to get things working by setting `'overwriteprotocol' => 'https'` in `config.php`.

Still login failed "Wrong username or password. " with app login. :/

**Comment by MaxXor** [comment]
@nielsenb-jf Sadly the workaround is not working here.

This should be higher priority as it's currently no longer possible to add new apps to the nextcloud account without revealing the main password.

**Comment by Palulukas** [comment]
> 
> 
> > I see the same thing here, errors in the log that I think are related look like this:
> > ```
> > [no app in context] Warning: Login failed: nielsenb (Remote IP: 172.19.0.2)
> > 
> > POST /login
> > from 172.19.0.2 at 2020-08-18T21:23:35+00:00
> > ```
> > 
> > 
> > I am running Nextcloud behind a reverse proxy with nginx to handle SSL. I managed to get things working by setting `'overwriteprotocol' => 'https'` in `config.php`.
> 
> Still login failed "Wrong username or password. " with app login. :/

Same here. :/

**Comment by PhilLab** [comment]
Also fails for me, Nextcloud 19.0.2

**Comment by MaxXor** [comment]
Issue persists on Nextcloud 19.0.5.

**Comment by ka223** [comment]
... issue persists on Nextcloud 20.0.7.1

How is this possible?

**Comment by Prometheus9001** [comment]
`'overwriteprotocol' => 'https'` doesn't work for me either, since it was already configured like that.
Tested with our own server as well as public hoster; generating a new app-password never works and using it afterwards newer works. This is now actually a problem for our intended backup strategy, since all accounts require 2FA and this is hardly possible with nextcloud in a headless linux. It's concerning at least, to see that this kind of issue hasn't even been adressed yet.

**Comment by cdeletre** [comment]
I've had the same kind of issue after moving my native Nexcloud instance into Docker with the apache image. Using nginx in front to enable HTTPS was working fine for accessing though a browser but all my desktop and mobile clients were failing with the authentication, which of course triggered the bruteforce protection and makes me crazy before I ended here. The addind of 'overwriteprotocol' => 'https' in the config.php solved the issue for me, also I have aligned the 'overwrite.cli.url' parameter with the vhost name of my https proxy (not sure it was needed).

**Comment by Anisotropic** [comment]
I have the same issue. Adding 'overwriteprotocol' => 'https' does nothing.
I have nextcloud snap installation in VM under proxy. System couldn't recognize generated app passwords. Creating new users are going well.

**Comment by archont00** [comment]
The same issue: NC 20.0.9.

Authenticating an android NC client via QR of app password works. Granting access from android NC client to DAVx works.
However, manually copy & paste app password to DAVx or KeePass2Android fails.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by PhilLab** [comment]
@szaimen I fear this is not a setup issue. The app credentials do not work and above comments are just talking about work around which do not work, as I understood it

**Comment by szaimen** [comment]
Maybe yes but in contrary app credentials work on my instance and other instances so there is probably something wrong with their setup...

**Comment by ka223** [comment]
@szaimen 

This issue has already been discussed in the forum: https://help.nextcloud.com/t/app-password-not-working/87228

Only manual created app passwords are affected and I can not see a possible config issue.
On my own instance and on my _hosters instance (not administered by me)_ is this issue.

If you think some configuration can cause this issue, please give me an example here or in the nextcloud forum. I would like to test this.

**Comment by FaySmash** [comment]
Same Issue on NC21.0.3 on Ubuntu 18LTS behind a nginx reverse Proxy. My old tokens still work, only newley created fail. Definitely an issue with nextcloud code.

**Comment by flammekueche** [comment]
On 22.1 getting worse.
No logging ar all on Android App for all account, old or new created account.
Login perfect on firefox browser.

**Comment by moboter** [comment]
OK same problem with NC 21.0.4
on Ubuntu 20.04.1
PHP 7.4.22
MySql 10.3.31

Client Win 10 PRO 21H1 64 Bit
SyncClient 3.3.3
Browser Firefox 91.1.0 ESR 64 Bit
I created a new User in NC
Went to Settings selected security Typed in a APP-NAME Create New APP password copied the password
Opened up the Sync client typed in the adress https://subdomain.domain.tld
Browser windows opened Prompting for do you want to grant access to Input the newly created credentials and the Browser failed to Login with the neww APP Password Logged in fine with the Credentials I typed in when I created the user.
Sync Client stored the Manual input and I dont know if the password is going to expire now

**Comment by LeffBA** [comment]
Same issue...
**System**:
- NC 21.0.4/22.1.1
- Ubuntu 20.04.3 LTS
- nginx/1.18.0
- PHP 7.4.3
- MySql 10.3.31

**Client**:
- Win 10 1803 64 Bit
- Browser Google Chrome 94.0.4606.61 64 Bit

All newly generated App-Passwords rejected by the system. The solution option with setting `'overwriteprotocol' => 'https'` doesn't helped.

**Comment by enoch85** [comment]
I also noticed this today.

Any progress here?

**Comment by andyxheli** [comment]
Same just noticed this today on NC 23.0.0

**Comment by to-str** [comment]
Same problem with my pretty vanilla installation. V22.2.3 behind nginx proxy. This does not seem to be a configuration issue, since the problem only happens after I change a user password after the user already exists. This is the log entry:

```
[no app in context] Warning: Login failed: <user> (Remote IP: 123.123.123.123)

POST /login
from 123.123.123.123 at 2022-01-03T14:25:36+00:00
```

**Comment by to-str** [comment]
I was trying some more and I think I found an issue. First, I tried a password with 12 chars, alphanumeric. It said password not complex enough, at least 15 chars. 

So I created a password with 15 chars, but still no special chars in there. This it seems to accept (i.e. no error displayed) but actually does not save it to database. Using a much more complex password like `hB*MvZyxKvSie?Nv23` works, and user can login again.

I advise you who have this problem to give this a try, maybe there is a mismatch between frontend password verification and backend password verification.

**Comment by andyxheli** [comment]
Hopefully there's a fix soon

**Comment by enoch85** [comment]
I don't think this is related to LDAP since I don't have LDAP enabled on my server.

**Comment by ehrlichja** [comment]
I'm hitting this too. Is the only workaround to disable 2fa globally on the nextcloud instance, and use the main password?

**Comment by leybodv** [comment]
Same issue on nextcloud 23.0.1
Is there any workaround?

**Comment by andyxheli** [comment]
I have not found a workaround i hope they fix this soon

**Comment by andyxheli** [comment]
Hi Nextcloud support, any updates on this?

**Comment by andyxheli** [comment]
Still an issue on NC 23.0.3. How is this not a priority  security is very critical

**Comment by andyxheli** [comment]
@PVince81 is #31519 suppose to fix this ? as the apps passwords do not work ?

**Comment by PVince81** [comment]
I'm not sure about the background of this, it is possible that app passwords are not accepted any more through the login flows.
I do know that app passwords cannot be used in the web UI login, so perhaps this is related.

What I know is that the desktop client app and also mobile apps are recently going through "login flow v1" or "login flow v2" for which they require the original password. Then, through the login flow they will automatically receive a generated password (like the app password) and save it locally. See https://docs.nextcloud.com/server/latest/developer_manual/client_apis/LoginFlow/index.html

This means that you don't need to manually generate an app password any more for the official apps.

However, for apps like Caldav Sync, Carddav sync or others that use the Webdav API, you should use app password (when I did it worked for me).

**Comment by PVince81** [comment]
in conclusion, the current behavior change might be by design and not a bug

**Comment by andyxheli** [comment]
Thank you for your clarification! Yes, you're correct. I just created a new app password and tested it via Webdav connection and it works. I was testing via Nextcloud portal login and that wasn't working. Again. I'm sorry to bother you.

**Comment by oe1rfc** [comment]
This seems to breaks app passwords for apps that use `webview` or `Login flow v2` login (eg. AntennaPod to use the GPodder Sync Plugin) which open the login page in a web browser.
If this is by design there is at least a documentation issue that app passwords will not work with apps that open the login portal.

**Comment by szaimen** [comment]
Hi, please update to 24.0.8 or better 25.0.2 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by oe1rfc** [comment]
@szaimen I'm already at `25.0.3.2`, but I can verify that logging in AntennaPod to Nextcloud with the Gpoddersync plugin using an app password and the `Alternative log in using app token` login option works again. Thank you very much!

**Comment by szaimen** [comment]
Great! Thanks for verifying!

**Comment by Rudd-O** [comment]
Bad news.  Nextcloud 27, app passwords don't work again.  I generate an app password, then I open the Web site and attempt to use the app password to log in, wrong username or password.

Am I doing something wrong?

Also, I thought the idea was to limit the specific password to specific apps.  Can't find any setting to do this.  Is there anything like that?

**Comment by collier-watkins** [comment]
Can confirm, same issue on Nextcloud 27. Running via docker behind nginx

**Comment by imerualfonzo** [comment]
Confirm, same issue on Nextcloud. Running via docker behind OMV7

**Comment by joshtrichards** [comment]
@Rudd-O @collier-watkins @imerualfonzo https://github.com/nextcloud/server/issues/21845#issuecomment-1099483351

AFAIK this is expected behavior: app/device passwords are intended for WebDAV device/app connections. They don't work with the Web UI itself.

You're also commenting on a three year old closed issue. If there's truly been a regression please create a new issue for it, since it likely would have a different root cause. Though from the sounds of it, there's no bug.

**Comment by Rudd-O** [comment]
Huge bummer.  I'd expect the app password to work properly and let me select which apps can be accessed when using it.

**Comment by joshtrichards** [comment]
> Also, I thought the idea was to limit the specific password to specific apps. Can't find any setting to do this. Is there anything like that?

> Huge bummer. I'd expect the app password to work properly and let me select which apps can be accessed when using it.

They do work as designed. The term "app password" refers to the connecting app, not the server-side app/permissions. They're for situations like where *apps* don't support things like 2FA (mostly). It's an industry term (maybe not an ideal one). Search your favorite search engine and you'll see our implementation/use of the term is a similar use case as most other platforms.

They're also less necessary with the newer login flow(s) these days in many cases. For example, they're meaningless (at least creating them manually) for all the official clients, since the one-time login flow essentially creates one internally for you.

That said, if you have a use case for controlling access within the same account in a special way I suggest you create an enhancement issue. Not sure your use case, but separate accounts, the `guests` app, etc. may also be options.

Either way, let's take any follow-up elsewhere since this is a long closed issue that was specifically referring to official client logins.
