### ISSUE TITLE
Upgrading CMS Pico Module Fails

### ISSUE THREAD

**Issue by TerryHewitt** [nextcloud/server#21852]
Nextcloud server version: 19.0.0 on ubtunu 20.04
cms pico version 1.0.6

Trying to upgarde to the latest version of CMS PICO I get this:

hewitt@zfsserver01:/var/www/nextcloud$ sudo -u www-data php /var/www/nextcloud/occ upgrade

Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Updating <cms_pico> ...
OCP\Files\ForbiddenException: Following symlinks is not allowed
Update failed
Maintenance mode is kept active
Reset log level

The home page of my server wants to run the update again I can get at the files.
I disabled cms pico with app:disable cmd_pico so I can get back to files disaply.

Could someone advise a fix please.

Best wishes
Terry

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1: 

Would you mind to **edit** your post and **add** the [issue template](https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md)? The information are required to reproduce your issue.
