### ISSUE TITLE
Transfer "incoming shares" in occ files:transfer-ownership command 

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#21856]
### Extend command files:transfer-ownership

* Some times user namespaces have to be rearranged. Even names might change when people get married, so their usernames should be changed
* This can be done right now by creating a new user and using occ files:transfer-ownership to transfer the files from $OLDUSER to $NEWUSER
* Shares that were issued by $OLDUSER are transferred to $NEWUSER but incoming shares from other users are lost  

It would be great if incoming shares, eg files and folders shared with the $OLDUSER, would be transferred to $NEWUSER in case no specific path was given and $OLDUSERS's whole cloud content will be transferred. 
Possibly with an additional option like "--include-shares"

**Comment by Volker-K** [comment]
No reaction right now?

**Comment by wiswedel** [comment]
inconsistency remark: The Guests app's user migration (https://github.com/nextcloud/guests#auto-convert-guest-users-into-full-users) process does migrate incoming shares for transfered objects:

https://github.com/nextcloud/guests/blob/e8a95fcdff73dde692c26f8afaab45cb91618fc3/lib/Hooks.php#L256-261

**Comment by Volker-K** [comment]
> inconsistency remark: The Guests app's user migration (https://github.com/nextcloud/guests#auto-convert-guest-users-into-full-users) process does migrate incoming shares for transfered objects:
> 
> https://github.com/nextcloud/guests/blob/e8a95fcdff73dde692c26f8afaab45cb91618fc3/lib/Hooks.php#L256-261

Indeed, but in this case it's no guest user but a user with a valid ID that has been changed. 

transfer-ownership right now only transfers files and folders and all shares that refer to them, e.g. when I transfer a folger containing project data to a new project manager, the folder with all contents is moved and the nwe owner becomes the sharer.

A full transfer of all files from one account to another is possible, too, but I understand that it should not include all incoming shares of the source account.  

transfer-ownership is no full conversion of an account like this migration from a guest account into a valid one. So I suggest to add an option to this command to transfer incoming shares, too.

**Comment by szaimen** [comment]
cc @nextcloud/sharing does this make sense?
