### ISSUE TITLE
Nextcloud 19 breaks Joplin Notes/ Joplin Sync

### ISSUE THREAD

**Issue by mahibi** [nextcloud/server#21851]
Some users that use Nextcloud to sync their Notes with [Joplin](https://joplinapp.org/)  complain that since Nextcloud19 notes are incomplete/corrupt after syncing.

Please have a look at [#3350](https://github.com/laurent22/joplin/issues/3350)

**Comment by julieni** [comment]
Seems related to webdav problem corrupting files due to wrong size / mtime reporting, see https://github.com/nextcloud/server/issues/21315#issuecomment-657440946
So yes, NC19 is causing data loss :(

**Comment by kesselb** [comment]
I'm closing this report in favour of https://github.com/nextcloud/server/issues/21315. We can reopen if it turns out to be a different problem.
