### ISSUE TITLE
Braces mistype causes revoke federated share failure

### ISSUE THREAD

**Issue by p5n** [nextcloud/server#21854]
https://github.com/nextcloud/server/blob/8368d56f8efd28098f2e0e7e3046c8c6a904449d/apps/federatedfilesharing/lib/FederatedShareProvider.php#L564

Bad current line:
```
if ($this->userManager->userExists($share->getShareOwner() && $this->userManager->userExists($share->getSharedBy()))) {
```
Good:
```
if ($this->userManager->userExists($share->getShareOwner()) && $this->userManager->userExists($share->getSharedBy())) {
```

**Comment by kesselb** [comment]
Thanks 👍 Mind to send a pull request?

**Comment by p5n** [comment]
https://github.com/nextcloud/server/pull/21855
