### ISSUE TITLE
Users UI overflows badly when user is a member of many groups

### ISSUE THREAD

**Issue by kawaii** [nextcloud/server#21871]
See the screenshot below - the UI for the `/settings/users` page will become quite messy when users are in many groups with longer names. Perhaps they should be formatted as a list instead?

![image](https://user-images.githubusercontent.com/12242877/87689121-be8e6b00-c77f-11ea-85fe-f00ec591ee22.png)

Note: I am using NextCloud 18.0.6 with groups from the LDAP/AD module.

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Isn't this fixed already?
@GretaD I think you worked on this?

**Comment by kawaii** [comment]
@skjnldsv you're right! After I upgraded the NextCloud container I still had cached CSS in my browser from the 18.0.1 version, sorry. :(
