### ISSUE TITLE
External WebDAV Storage cannot read big directories

### ISSUE THREAD

**Issue by smartbyte** [nextcloud/server#21884]
Module: External Storage + WebDAV + scan:files --all

1. Have a WebDAV Storage with big directories (Fails on my system with 7404 files)
2. Try to access it with the WebFrontend -> Fails (loads indefinitely)
3. Do a scan:files --all on your home (loads indefinitely on the big folder, all berfore are O.K.)

### Expected behaviour
The system should show / find all files and put into DB

### Actual behaviour
The system (Nextcloud on the WebFrontend and scan:files --all) stops at the big directory and "hangs"

### Server configuration
Nextcloud 19.0.1 (Beta newest Version)
Ubuntu 20.04

**Web server:**
Apache 2.4 (newest in Ubuntu)

**Database:**
SQLite

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install (with existing WebDAV Server)

**Where did you install Nextcloud from:**
from bz archive

**Comment by kesselb** [comment]
You see the same issue with MariaDB or Postgres? Sqlite is not recommend for production setups.

**Comment by smartbyte** [comment]
Yes, I can now finally confirm that the same error occurs with MaraDB. 
I am pretty sure problem is located in the WebDAV Interface and not somewhere else.

**Comment by smartbyte** [comment]
> You see the same issue with MariaDB or Postgres? Sqlite is not recommend for production setups.

**Comment by smartbyte** [comment]
The issue seems to be MEGA.nz webdav-service related and not primarily a nextcloud issue, as I have the same issue with davfs2... Although when I try to access the directory with a web-browser it shows the files, although it looks like it is loading the directory in chunks (because of around 7000 files in there)
