### ISSUE TITLE
New Start-screen/Dashboard to be call Nextcloud Hub https://github.com/nextcloud/server/issues/20930

### ISSUE THREAD

**Issue by MarkPartlett** [nextcloud/server#21883]
https://github.com/nextcloud/server/issues/20930 is recommending a new Start-screen , The name 'Dashboard' has been referenced within feature request and the recommendation is to call it 'Hub' . Fitting with the current Nextcloud branding of 'Nextcloud Hub'

**Comment by kesselb** [comment]
Closing in favor of #20930.
