### ISSUE TITLE
App-navigation without settings should not have padding-bottom

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2189]
Since #app-settings is inside #app-navigation, we can not do this via CSS. We probably need to add a class ».without-app-settings« to the #app-navigation via JS when there’s no settings, and then via CSS:
```
#app-navigation.without-app-settings {
   padding-bottom: 0;
}
```
![capture du 2016-11-17 18-40-15](https://cloud.githubusercontent.com/assets/925062/20400541/7119c98a-acf5-11e6-9459-17bc904bc4dd.png)

cc @BernhardPosselt @nextcloud/designers @nextcloud/javascript

**Comment by MorrisJobke** [comment]
Fix is in #2283
