### ISSUE TITLE
Documents sharing error

### ISSUE THREAD

**Issue by ShinyShrimp** [nextcloud/server#219]
### Steps to reproduce
1. Open Documents
2. New Document
3. Click Share
4. Click share link

### Expected behaviour
I should see the shared link

### Actual behaviour
Popup: Error while sharing

![25-06-_2016_01-44-10](https://cloud.githubusercontent.com/assets/11614619/16339594/a11f116c-3a77-11e6-8932-1971e53d7ec8.png)

**Comment by mar1u5** [comment]
Uhmm ... This is not about the `server`, its about the `documents` app 😉 
Problem is, that we at Nextcloud are currently not providing an repository for this app, where you can report bugs 😁 

...should this be reported to ownCloud or should I import this repository 😁 @MorrisJobke

**Comment by LukasReschke** [comment]
Please report this at https://github.com/owncloud/documents

**Comment by eudoxos** [comment]
Has this been reported against https://github.com/owncloud/documents yet? Could not find it. If so, there should be a link here so that nextcloud users facing that error can find it and follow.

**Comment by FreeMinded** [comment]
There is an issue at https://github.com/owncloud/documents/issues/622

@PVince81 wrote there:
> Note that the documents app has no maintainer currently so if someone is up to taking care of it and publishing to the app store (and future market), please let us know.
