### ISSUE TITLE
share autocomplete not display correct group-name

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/server#21906]
### Steps to reproduce
1. share a file/directory with a group of the name "LV BBV"
2. if you type in the autocomplete "lv" you will see in the list "lv BBV" which is wrong as the name ist "LV BBV"

### Expected behaviour
you should see the correct group-name with the right lower/uppercase.

### Actual behaviour
shows wrong group name

### Server configuration

**Nextcloud version:** 19.*, 19.01

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by kinimodmeyer** [comment]
@szaimen thanks for reminding on this issue here!

not valid in current versions anymore, closed
