### ISSUE TITLE
Proxyexclude not working

### ISSUE THREAD

**Issue by devz3r0** [nextcloud/server#21915]
### Steps to reproduce
https://help.nextcloud.com/t/proxyexclude-not-working/87321
1. Add a Proxy to be able to get/update apps
2. Add Proxy excludes to be able to use Onlyoffice
‘proxy’ => ‘http://PROXY:3128’,
‘proxyexclude’ => [‘share.domain.com’, ‘share.dom-main.com’, ‘1.2.3.4’],
OR
‘proxyexclude’ => [‘domain.com’, ‘.dom-main.com’, ‘1.2.3.4’],

3. see in the tcpdump that the connection to the proxy is still crated

### Expected behaviour
https://github.com/nextcloud/server/pull/17684
working onlyoffice and to be able to get new apps 

### Actual behaviour
Proxyconnection still created

### Server configuration

Nextcloud version (eg, 18.0.2): 18.0.6
Operating system and version (eg, Ubuntu 20.04): Centos 8
Apache or nginx version (eg, Apache 2.4.25): Apache/2.4.37
PHP version (eg, 7.1): 7.3.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh

**Comment by astrakid** [comment]
Issue also existent in 18.0.7.

**Comment by szaimen** [comment]
Based on astrakid's comment I am closing this since it seems to work.
