### ISSUE TITLE
Update to OwnCloud

### ISSUE THREAD

**Issue by jonisc** [nextcloud/server#2191]
### Steps to reproduce
1.Update from OwnCloud came
2.Nextcloud wanted me to upgrade to Owncloud
3.

### Expected behaviour
Tell us what should happen
Nextcloud shouldn't show owncloud updates
### Actual behaviour
Tell us what happens instead
Nextcloud wants to upgrade to OwnCloud: Nextcloud 10.0 RC1 wants to update to ownCloud 9.1.1
https://i.redd.it/4zltnov4g7ux.png
### Server configuration
**Operating system**: Debian Linux (Bananian)

**Web server:**apache2

**Database:**
Mariadb
**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud: fresh

**Comment by jonisc** [comment]
See this too: https://m.reddit.com/r/NextCloud/comments/59u08e/nextcloud_100_rc1_wants_to_update_to_owncloud_911/

**Comment by jonisc** [comment]
See the source: https://m.reddit.com/r/NextCloud/comments/59u08e/nextcloud_100_rc1_wants_to_update_to_owncloud_911/

**Comment by grouchysysadmin** [comment]
Known issue. See https://help.nextcloud.com/t/notification-about-an-upgrade-to-owncloud-9-1-1-in-nextcloud-10-stable/4573/3
