### ISSUE TITLE
Upload via Drag&Drop into a Browser Window  works improperly

### ISSUE THREAD

**Issue by steve-s-71** [nextcloud/server#21912]
Upload via Drag&Drop into a Browser Window does not work if one doesn’t hit the upper area of the window. In that case the file is ignored (not uploaded).

The issue **happens when using a shared link**, it does **NOT** happen if one do the same as a regularly logged-on NC user. I tried Firefox and Chrome both under Windows 10

See below example images. Drop location in first image works. The drop location used in 2nd image does not.

It is super confusing. I got many complains from less tech affine users who did not manage to upload a file due to this issue. 

### Steps to reproduce
- Create a Folder and share it via a Link
- Navigate to the Link Maximize the Browser Window (certain screen resolution is needed to reproduce)
- Try to Drag&Drop a file in lower area of the window (see 2nd example image) 

###  NC Version
16, 17,18,19 all have this issue

### Expected behaviour
Upload should work no within the entire window (see screen shoots below)

### Actual behaviour
Upload work only on top of the screen (see screen shoots below)
 
![1](https://user-images.githubusercontent.com/17343515/87882368-db38d600-c9ff-11ea-97ff-0f50573be86b.jpg)

![2](https://user-images.githubusercontent.com/17343515/87882373-df64f380-c9ff-11ea-9432-5ac0f54e7b48.jpg)

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by steve-s-71** [comment]
This bug still presists in NC 20   👎

**Comment by steve-s-71** [comment]
Just tried with NC21. This bug still presists. Very disapponting!

**Comment by jospoortvliet** [comment]
Can partially confirm, same bug here on linux/Firefox but it works properly on linux/Chrome, the whole area you can drop files in.

**Comment by steve-s-71** [comment]
Different picture on Windows: the bug exists with windows/Chrome as well. An also with windows/Firefox, windows/InternetExplorer and windows/Edge   

Please can you give it a push towards a resultion @jospoortvliet
