### ISSUE TITLE
Versions not showing Onlyoffice changes

### ISSUE THREAD

**Issue by kowjens** [nextcloud/server#21927]
Hi all,

I run NC with integrated Onlyoffice (documentserver_community: 0.1.7 + onlyoffice: 4.3.0 apps). Following gives a short overview from `“settings->support->system report”`:

**Server Config:**
Operating system: Linux 4.15.0-109-generic # 110-Ubuntu SMP Tue Jun 23 02:39:32 UTC 2020 x86_64
Webserver: nginx/1.19.0 (fpm-fcgi)
Database: mysql 10.2.14
PHP version: 7.4.8
Nextcloud version: 19.0.0 - 19.0.0.12
(didn’t want to blow up the topic with loaded modules/apps, but if needed I’ll add all)

**Steps to reproduce**
1) First if I open an office document inside the browser, change it and close it, the details button of no file in this directory is working anymore. This only happends if the file is changed. Reloading the page or folder changes back and fore make it work again. This is only a small but reproducible bug.
2) More important, how I find, is that edited files are not considered in Versions at all! Under activity, it shows that the file has been changed by “remote user” after the cronjob was executed. I wonder if both, activity and versions interaction with OO could be optimized by adding an occ command after closing/ saving the file like “`occ files:scan –path=…`” or similar? However, the username should be passed to the office and back as well.

**Expected behaviour**
- in Office edited files should be updated in Versions

**Actual behaviour**
- changes in documents are not considered in Versions or only from "remote user" in Activities
- changes in Activities only visible after cronjob

Maybe one of you faced this issue already or knows how it can be solved? Thanks in advance everybody!
Especially not showing changes in Versions makes the office integration unusable for cooperative work.

Kind regards
Jens

**Comment by kesselb** [comment]
Sounds like https://github.com/nextcloud/documentserver_community/issues/12?

**Comment by kowjens** [comment]
Yes you are right that's exactly the problem, tnx I didn't found something before. Some more related/same topics, which I found due to your help, are:

[#53](https://github.com/nextcloud/documentserver_community/issues/53)
[#59](https://github.com/nextcloud/documentserver_community/issues/59)
[#78](https://github.com/nextcloud/documentserver_community/issues/78)
[#100](https://github.com/nextcloud/documentserver_community/issues/100)

However, here is a part of the log, which seems to be related to the issue:
```
[documentserver_community] Error: OCA\DocumentServer\Document\DocumentConversionException: namespace error : Namespace prefix wp14 on sizeRelH is not defined
/drawingml/2006/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctWidth is not defined
/main"/></wp:cNvGraphicFramePr><wp14:sizeRelH relativeFrom="page"><wp14:pctWidth
                                                                               ^
namespace error : Namespace prefix wp14 on sizeRelV is not defined
p14:pctWidth>0</wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"
                                                                               ^
namespace error : Namespace prefix wp14 on pctHeight is not defined
wp14:pctWidth></wp14:sizeRelH><wp14:sizeRelV relativeFrom="page"><wp14:pctHeight
                                                                               ^
 at <<closure>>
0. /var/www/html/custom_apps/documentserver_community/lib/DocumentConverter.php line 123
   OCA\DocumentServer\Document\ConverterBinary->run("/tmp/oc_tmp_AGkhfM-.xml", null)
1. /var/www/html/custom_apps/documentserver_community/lib/DocumentConverter.php line 78
   OCA\DocumentServer\DocumentConverter->runCommand(OCA\DocumentServ ... {})
2. /var/www/html/custom_apps/documentserver_community/lib/Document/DocumentStore.php line 151
   OCA\DocumentServer\DocumentConverter->saveChanges("*** sensitive parameter replaced ***", ["78;AgAAADEA//8 ... "], "/var/www/html/d ... x", "docx")
3. /var/www/html/custom_apps/documentserver_community/lib/LocalAppData.php line 100
   OCA\DocumentServer\Document\DocumentStore->OCA\DocumentServer\Document\{closure}("*** sensitive parameters replaced ***")
4. /var/www/html/custom_apps/documentserver_community/lib/Document/DocumentStore.php line 164
   OCA\DocumentServer\LocalAppData->getReadWriteLocalPath(OC\Files\SimpleFS\SimpleFolder {}, Closure {})
5. /var/www/html/custom_apps/documentserver_community/lib/Document/SaveHandler.php line 56
   OCA\DocumentServer\Document\DocumentStore->saveChanges(77729904, [OCA\DocumentSer ... }])
6. /var/www/html/custom_apps/documentserver_community/lib/BackgroundJob/Cleanup.php line 69
   OCA\DocumentServer\Document\SaveHandler->flushChanges(77729904)
7. /var/www/html/lib/public/BackgroundJob/Job.php line 80
   OCA\DocumentServer\BackgroundJob\Cleanup->run(null)
8. /var/www/html/cron.php line 126
   OCP\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
at 2020-07-21T17:40:02+00:00
```

Sorry for opening another issue on an already existing topic. I guess this can be closed than and discussion should be continued in one of the other topics.
