### ISSUE TITLE
Files: show favorites column in Shared views as well

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2193]
Currently the Favorites stars are only shown in the Files and Favorites view. They should be shown in the other views as well.

cc @nextcloud/javascript

**Comment by MorrisJobke** [comment]
Duplicate of #2347 (there is more activity

**Comment by jancborchardt** [comment]
@MorrisJobke this has a clear plan though. ;) Reopening hence

**Comment by MorrisJobke** [comment]
Only the "Recent" view is missing - out of scope for 12. Moved to 13: #4697
