### ISSUE TITLE
File Sharing broken // no POST/DELETE requests send to apache

### ISSUE THREAD

**Issue by internethering** [nextcloud/server#21932]
### Steps to reproduce
I try to share a Folder with another user. After clicking on the share symbol, I enter the name and press enter, when the right username is shown to me. The spinning symbol doesn't stop and the name doesn't get displayed in the list. At reloading page I get a „Error creating the share” error. After reloading I see the name in the list, but the other user doesn't see the share.

### Expected behaviour
Sharing should work.

### Actual behaviour
I doesn't see in the apache logs the POST/DELETE requests like (from working nextcloud copied) „[21/Jul/2020:12:08:10 +0200] "POST /ocs/v2.php/apps/files_sharing/api/v1/shares HTTP/1.1" 200 776 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0"“

## Server configuration detail

**Operating system:** Linux 5.7.0-gentoo #1 SMP PREEMPT Tue Jun 2 17:29:19 CEST 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 8.0.20

**PHP version:** 

7.3.19
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, bcmath, bz2, calendar, ctype, curl, dba, dom, hash, fileinfo, filter, ftp, gd, gettext, SPL, iconv, session, intl, json, mbstring, standard, mysqlnd, pcntl, mysqli, PDO, pdo_mysql, pdo_sqlite, apcu, posix, readline, Reflection, imap, SimpleXML, soap, sockets, exif, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, wddx, xml, xmlreader, xmlrpc, xmlwriter, xsl, zip, cgi-fcgi, apc, Phar, geoip, imagick, mailparse, mcrypt, memcached, Zend OPcache

**Nextcloud version:** 18.0.7 - 18.0.7.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** 

<details><summary>Signing status</summary>

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - bruteforcesettings: 1.6.0
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - encryption: 2.6.0
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_external: 1.9.0
 - files_frommail: 0.4.0
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - issuetemplate: 0.6.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - user_external: 0.10.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "18.0.7.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "UTC",
    "installed": true,
    "trashbin_retention_obligation": "auto, 7",
    "filelocking.enabled": "true",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/cloud\/htdocs\/apps",
            "url": "\/apps",
            "writable": true
        },
        {
            "path": "\/var\/www\/cloud\/htdocs\/cke_apps",
            "url": "\/cke_apps",
            "writable": false
        }
    ],
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "imap.ck-energy.de",
                993,
                "ssl"
            ]
        }
    ],
    "loglevel": 2,
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "enable_avatars": true,
    "singleuser": false,
    "updater.release.channel": "stable",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "smtp",
    "mail_smtpport": "25",
    "mysql.utf8mb4": true
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** 1

**Are you using an external user-backend, if yes which one:** Imap

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:79.0) Gecko/20100101 Firefox/79.0

**Operating system:** Gentoo Linux

## Logs

<details><summary>Web server error log</summary>

```
no entrys about this beheavor
```
</details>

<details><summary>Nextcloud log</summary>

```
no entrys about this beheavor
```
</details>

<details><summary>Browser log</summary>

moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
suggestions 
Array(11) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
SharingInput.vue:252
suggestions 
Array [ {…}, {…} ]
SharingInput.vue:252
XHRPOSThttps://***REMOVED SENSITIVE VALUE***/ocs/v2.php/apps/files_sharing/api/v1/shares
moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
XHRPOSThttps://***REMOVED SENSITIVE VALUE***/index.php/apps/text/session/sync
[HTTP/1.1 200 OK 383ms]

moment is deprecated: please ship your own, this will be removed in Nextcloud 20 globals.js:66:15
XHRGEThttps://***REMOVED SENSITIVE VALUE***/ocs/v2.php/apps/notifications/api/v2/notifications
[HTTP/1.1 200 OK 105ms]

</details>

**Comment by kesselb** [comment]
Adblock or something like this? I would check the network log for failing requests (not only the post/get/delete but also loading of additional scripts). As this works on try.nextcloud.com and my private instance I don't see an actual issue here. Please visit https://help.nextcloud.com/ for general help and configuration issues.

**Comment by internethering** [comment]
> Adblock or something like this? I would check the network log for failing requests (not only the post/get/delete but also loading of additional scripts). As this works on try.nextcloud.com and my private instance I don't see an actual issue here. Please visit https://help.nextcloud.com/ for general help and configuration issues.

adblocker ist not installed. any another requests doesn't fail, all have status code 200/303/304. the only one is the posted POST request

**Comment by kesselb** [comment]
> I doesn't see in the apache logs the POST/DELETE requests

> the only one failing is the posted POST request

You see the request in network inspector but not in access log? 

What does the failing post request looks like? Is there a response?

**Comment by internethering** [comment]
> You see the request in network inspector but not in access log?
yes

> What does the failing post request looks like? Is there a response?
there is no response. 

 
![Screenshot_20200804_132831](https://user-images.githubusercontent.com/6939869/89288742-6ea41500-d656-11ea-84f6-7990e341586d.png)
