### ISSUE TITLE
Consider making the occweb app official?

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#21933]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It seems like the occweb app was deprecated by the developer: https://git.adphi.net/adphi/occweb

**Describe the solution you'd like**
Would be great if you could make the app an official one, so that it can be upgraded by the core team since it is one of the best Nextcloud apps and it would be a shame if it would just vanish, imho.

**Describe alternatives you've considered**
Maybe convince the developer to reconsider his decision?

**Additional context**
-

**Comment by szaimen** [comment]
@kesselb why are you against this idea?

**Comment by kesselb** [comment]
> Consider making the occweb app official

Unlikely 

> It seems like the occweb app was deprecated by the developer

You read the deprecation note? A common use case for occweb is to run those migration scripts. If those migrations scripts are interrupted they might leave you instance in a broken state. I guess it will work for most instances out there but if we make this way official and/or supported people expect it to work. But long running / expensive operations and web servers with timeouts involved will never work. I have stopped counting the issues at nextcloud/updater about broken / interrupted updates. 

The last one I remember was a report that the backup of current Nextcloud takes more than 1 hour and that interrupts the web based updater at some point. The backup step is actually copy Nextcloud (without data) to a different folder. We are talking about ~1 GB of data. 

As workaround he used the CLI based updater instead. And that's my main concern. If such a way is available people will use for whatever reason. Does it make sense to run a upgrade routine with your web server if the CLI is available? Nope. I usually run php updater.phar and service php7.4-fpm restart and that's it. No timeouts, No interrupts. 

> the lack of true asynchronous occ operations can lead to serious alterations of voluminous instances. 

There is no way to fix this problem with the typical web server <-> php setup. It might be fixed if one would implement Nextcloud in Rust, Go or Assembler but then you are not able to run it on your 1,99€ web hosting too. Actually you can run Nextcloud today on your 1,99€ web hosting with limitations. If we rewrite in Rust, Go or Assembler you cannot. 

> one of the best Nextcloud apps 

I fail to see why. occweb is a way to run ./occ as Nextcloud app? What is it good for (beside running occ commands on web hosting without shell access)?

> Maybe convince the developer to reconsider his decision?

> And over all of this , I want to say I really dislike, even dispise the overall Nextloud teams communication, the "we are the best", and other "look, we make so many commits", witout fixing good old issues, moving fast forward, "we make more commits than pydio"! what a good point ! your more than 10x their developpers ! What a 'prouesse' !!!

_(quoted from https://git.adphi.net/adphi/occweb/src/master/README.md#-deprecated-)._ 

That sounds final :disappointed:

**Comment by szaimen** [comment]
Thank you for your very detailed explanation!

In the following, I will try to address your concerns:

> > one of the best Nextcloud apps
> 
> I fail to see why. occweb is a way to run ./occ as Nextcloud app? What is it good for (beside running occ commands on web hosting without shell access)?

I think this is one underrated feature which also makes sense on a normal instance, e.g. if you don't want to use ssh each time you want to change one small thing or run a short command, because you are logged in and can run this command easily on the fly. (If it makes sense to be always logged in as an admin is questionable, but another topic)
Additionally, options like e.g. disabling the readme feature of the text app are still not available via GUI and therefore is running the command via occ the only choice, which makes the occweb app a must have on shared hosters.

> Actually you can run Nextcloud today on your 1,99€ web hosting with limitations. If we rewrite in Rust, Go or Assembler you cannot.

Please note: this request isn't a hidden attempt to try to trigger a rewrite.
My point is that I think, that this app is badly needed, especially on shared hosters.

> But long running / expensive operations and web servers with timeouts involved will never work.

Actually, there was an attempt to block certain commands to make it more robust and prevent the user from executing the wrong commands, which is the way to go, imho: https://git.adphi.net/adphi/occweb/pulls/14

If those blacklist-commands where implemented, including e.g. executing updates via occweb, I think it could become quite stable and therefore maybe stable enough to actually get considered to become official, don't you think?

**Comment by kesselb** [comment]
>  e.g. disabling the readme feature of the text app are still not available via GUI and therefore is running the command via occ the only choice

`config:app:set` changes the `oc_appconfig` table. You don't need occweb to change a configuration value there. Just login to your database.

> I think this is one underrated feature which also makes sense on a normal instance, e.g. if you don't want to use ssh each time you want to change one small thing or run a short command, because you are logged in and can run this command easily on the fly.

Fine by me. 

> https://git.adphi.net/adphi/occweb

It's not possible to move the repository to the Nextcloud organization as the repository is not hosted on GitHub. Feel free to clone the repository and keep maintaining it.

**Comment by rullzer** [comment]
Nope we will not maintain this app. Sorry but we have to make choices in what we support and what not. There are to many risks involved if we suppor this and everybody starts using it.

Of course you could reach out to the maintainer to help out.

**Comment by funky123** [comment]
i need to fix the stuff at a shared hosting, so i have no chance to fix these issues:

Fehlender Index "calendarobject_calid_index" in der Tabelle "oc_calendarobjects_props".
Fehlender Index "schedulobj_principuri_index" in der Tabelle "oc_schedulingobjects".
Fehlender Index "properties_path_index" in der Tabelle "oc_properties".

**Comment by kesselb** [comment]
> i need to fix the stuff at a shared hosting, so i have no chance to fix these issues:
> 
> Fehlender Index "calendarobject_calid_index" in der Tabelle "oc_calendarobjects_props".
> Fehlender Index "schedulobj_principuri_index" in der Tabelle "oc_schedulingobjects".
> Fehlender Index "properties_path_index" in der Tabelle "oc_properties".

Of course you have. Just head over to https://help.nextcloud.com and use the search.
