### ISSUE TITLE
Nextcloud occ:files scan did not remove share when file is delete

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#21947]
Hi, 

1 : Create DIR or file (with nextcloud) 
2 : Create a public link or share on it 
3 : Delete the file on the Nextcloud User datas storage directly 
4 : Don't forget the link 
5 : Scan files with occ:files scan --path DIRORFILEPATH
6 : Go inside your db in share table 

You will se your public link with entry eaven if your DIR/file is deleted. 

Why i'm doing that ? 

I want delete all files/DIR inside DIR based on mtime(DIR) in files_cache table 

Ofc i try file_retention but there is no way do that . 

Best regards

**Comment by sharidas** [comment]
May be a repair step should help here? That way orphan entry can be cleaned up.

**Comment by szaimen** [comment]
I think as long as the file is in the trashbin the link doesn't get deleted but only disabled. Only after removing the file from the trashbin, it should remove the link too. Did you check if that works?

**Comment by tanguy-opendsi** [comment]
@sharidas sorry i did not saw your answer ^^
@szaimen  good idea !!! i'll try it
