### ISSUE TITLE
macOS CardDAV sync creates duplicate contacts

### ISSUE THREAD

**Issue by jprenken** [nextcloud/server#21944]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a CardDAV account in macOS' Contacts app (server path: /principals/user/).
2. Set the Nextcloud CardDAV account to be the Default Account in the General pane of Contacts' Preferences.
3. Create a new contact.

This configuration was previously working; this behavior started to occur after a macOS and/or Nextcloud upgrade. Unfortunately, I don't know exactly when or which upgrade this was.

### Expected behaviour
The contact should be created (once) on the Nextcloud server.

### Actual behaviour
Every time Contacts (i.e. the AddressBookCore service) syncs with the Nextcloud server, a duplicate copy of the contact is created on the Nextcloud server.

### Server configuration

**Operating system:**
Debian 10.4 (Buster)

**Web server:**
nginx 1.14.2-2+deb10u1

I am using the snippet from https://docs.nextcloud.com/server/18/admin_manual/installation/nginx.html so that gzip does not remove ETag headers.

**Database:**
MariaDB 1:10.3.22-0+deb10u1

**PHP version:**
PHP 7.3.19-1~deb10u1

**Nextcloud version:** (see Nextcloud admin page)
18.0.7.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from a (much) older version.

**Where did you install Nextcloud from:**
nextcloud.com tarball.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - admin_audit: 1.8.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_external: 1.9.0
  - files_pdfviewer: 1.7.0
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - nextcloud_announcements: 1.7.0
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.9
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0
Disabled:
  - documentserver_community
  - encryption
  - files_rightclick
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.renken-sebastian.us"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/cloud.renken-sebastian.us\/",
        "dbtype": "mysql",
        "version": "18.0.7.1",
        "appstoreenabled": true,
        "apps_paths": [
            {
                "path": "\/home\/www\/nextcloud\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "theme": "",
        "loglevel": 0,
        "maintenance": false,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "updater.release.channel": "stable",
        "activity_expire_days": 365,
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "app_install_overwrite": [
            "calendar"
        ]
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no (not within Nextcloud)

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mac OS X/10.15.6 (19G73) AddressBookCore/1

**Operating system:** Mac OS X/10.15.6 (19G73)

#### Web server error log
<details>
<summary>Web server error log</summary>
No relevant entries.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
An enormous number of lines like these:

```
{"reqId":"***REMOVED SENSITIVE VALUE***","level":0,"time":"2020-07-21T17:15:20+00:00","remoteAddr":"***REMOVED SENSITIVE VALUE***","user":"jrenken","app":"webdav","method":"PUT","url":"/remote.php/dav/addressbooks/users/jrenken/contacts/***REMOVED SENSITIVE VALUE***.vcf","message":{"Exception":"Sabre\\DAV\
\Exception\\PreconditionFailed","Message":"An If-Match header was specified, but none of the specified the ETags matched.","Code":0,"Trace":[{"file":"/home/www/nextcloud/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"checkPreconditions","class":"Sabre\\DAV\\Server
","type":"->","args":[{"absoluteUrl":"https://cloud.renken-sebastian.us/remote.php/dav/addressbooks/users/jrenken/contacts/***REMOVED SENSITIVE VALUE***.vcf","__class__":"Sabre\\HTTP\\Request"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/home/www/nextcloud/nextcloud/3rdparty/
sabre/dav/lib/DAV/Server.php","line":254,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->","args":[{"absoluteUrl":"https://cloud.renken-sebastian.us/remote.php/dav/addressbooks/users/jrenken/contacts/***REMOVED SENSITIVE VALUE***.vcf","__class__":"Sabre\\HTTP\\Requ
est"},{"__class__":"Sabre\\HTTP\\Response"}]},{"file":"/home/www/nextcloud/nextcloud/apps/dav/lib/Server.php","line":319,"function":"exec","class":"Sabre\\DAV\\Server","type":"->","args":[]},{"file":"/home/www/nextcloud/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec"
,"class":"OCA\\DAV\\Server","type":"->","args":[]},{"file":"/home/www/nextcloud/nextcloud/remote.php","line":165,"args":["/home/www/nextcloud/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/home/www/nextcloud/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php"
,"Line":1338,"CustomMessage":"--"},"userAgent":"Mac OS X/10.15.6 (19G73) AddressBookCore/1","version":"18.0.7.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
I ran:

```
defaults write com.apple.iCal LogHTTPActivity yes
defaults write com.apple.AddressBook.CardDAVPlugin EnableDebug -bool YES
defaults write com.apple.AddressBook.CardDAVPlugin LogConnectionDetails -bool YES
```

`Library/Logs/Contacts/CardDAV/*/traffic.log` files were created with a great deal of output (~ 30 MB / minute) with hard-to-redact sensitive information. The `An If-Match header was specified, but none of the specified the ETags matched.` message is present throughout.
</details>

**Comment by binarykitchen** [comment]
Ugh, I have this too now and it's painful

**Comment by ukd1** [comment]
Also have this.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by jprenken** [comment]
I can no longer reproduce this with Nextcloud 21.0.3 and macOS 11.4. @binarykitchen & @ukd1, how about you?

**Comment by ukd1** [comment]
@jprenken I've since moved on and didn't end up using this project due to this error. Glad it's fixed for y'all though :)
