### ISSUE TITLE
Overwriting file with webdav/rclone fails with postgresql error

### ISSUE THREAD

**Issue by joequant** [nextcloud/server#21943]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. mount filesystem with webdav/rclone
2. copy new file onto existing filename
3. nextcloud creates zero length file with error

AH00558: httpd: Could not reliably determine the server's fully qualified domain name, using fe80::a48b:e3ff:fe29:e641%tap0. Set the 'ServerName' directive globally to suppress this message
2020-07-21 11:40:10.331 UTC [235] ERROR:  duplicate key value violates unique constraint "fce_fileid_idx"
2020-07-21 11:40:10.331 UTC [235] DETAIL:  Key (fileid)=(477) already exists.
2020-07-21 11:40:10.331 UTC [235] STATEMENT:  INSERT INTO "oc_filecache_extended" ("fileid", "upload_time") VALUES($1, $2)

### Expected behaviour
Tell us what should happen

The file should copy over using webdav.  Alternatively if there is an exception the copy should fail.

### Actual behaviour
Tell us what happens instead

File copy aborts but file is overwritten with a zero-length file

### Server configuration

**Operating system:**

Linux

**Web server:**

apache

**Database:**

postgresql

**PHP version:**
7.4.8

**Nextcloud version:** (see Nextcloud admin page)

19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

updated

**Where did you install Nextcloud from:**

Generated own rpm packages from source

**Signing status:**
<details>
<summary>Signing status</summary>

```

Results
=======
- core
	- INVALID_HASH
		- .htaccess
		- lib/private/Installer.php
	- FILE_MISSING
		- .user.ini
		- AUTHORS
		- COPYING
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Nothing in `nextcloud.log`?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
