### ISSUE TITLE
CountWrapper stream_seek(0) should reset $readCount

### ISSUE THREAD

**Issue by kesselb** [nextcloud/server#21958]
**Motivation**

https://github.com/nextcloud/server/blob/94c74fb97bc2f46878a396c21621c694391032f5/lib/private/Files/ObjectStore/S3ObjectTrait.php#L89-L93

Replace the MultipartUploader with ObjectUploader. The ObjectUploader uses a PutObject operation for files < 16 MB (default, can be changed) and MultipartUpload otherwise. Amazon S3 charges you for storage and requests hence less requests are better.

| Example: New text document    | MultipartUpload                                            | PutObject |
|-------------------------------|------------------------------------------------------------|-----------|
| 1. Create the object          | CreateMultipartUpload, UploadPart, CompleteMultipartUpload | PutObject |
| 2. Generate max preview using | CreateMultipartUpload, UploadPart, CompleteMultipartUpload | PutObject |
| 3. Generate another preview   | CreateMultipartUpload, UploadPart, CompleteMultipartUpload | PutObject |

**Blocker**

It's not possible to upload files with https://github.com/nextcloud/server/pull/21952 anymore (actually uploading works but the process is aborted). 

https://github.com/nextcloud/server/blob/57403c7020b4ac5e47df21c43882fde4be24456b/apps/dav/lib/Connector/Sabre/File.php#L237-L239

Is thrown because the number of bytes read is not correct. If $stream->getSize() is not available (at least on my dev setup it's never available), ObjectUploader reads the first 5 MB of a stream and sets the pointer back to 0.

https://github.com/nextcloud/server/blob/734c62bee0f46652285f782761317889d1ef5c7d/lib/private/Files/ObjectStore/ObjectStoreStorage.php#L454-L460

Does not care about seek(0). The count for files uploaded via ObjectUploader is always 5 MB to high. 

```
	public function stream_seek($offset, $whence = SEEK_SET) {
		$this->readCount = 0;
		return parent::stream_seek($offset, $whence); // TODO: Change the autogenerated stub
	}
```

Uploading files via ObjectUploader works if I patch the CountWrapper like above. 

**Question**

Is this something for https://github.com/icewind1991/streams? It depends on the use case if all bytes ever read or the bytes after the last seek(0) are wanted. It might be easier to overwrite the CountWrapper here because reset the read count on offset = 0 is a breaking change.

Also most of the storage code relies on the assumption that bytes read = bytes written to external storage. Looks like a risky change :eyes:

**Comment by szaimen** [comment]
I suppose this is still valid?

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/27877
