### ISSUE TITLE
When install failed installer doesn’t keep status of "install recommended apps" checkbox

### ISSUE THREAD

**Issue by dboehmer** [nextcloud/server#21959]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. download tarball, extract and configure webserver
2. go to Nextcloud base URL showing installer page
3. enter invalid database credentials, uncheck *install recommended apps*
4. submit

### Expected behaviour
The checkbox *install recommended apps* stays unchecked.

### Actual behaviour
The checkbox is checked again.

### Server configuration

**Operating system:** Debian Buster

**Web server:** Nginx

**Database:** none yet

**PHP version:** 7.3

**Nextcloud version:** 19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tarball

**Nextcloud configuration:** none yet

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by dboehmer** [comment]
I've just verified this: This is still valid in Nextcloud 22.0.0

**Comment by carlcsaposs** [comment]
Appears to no longer be an issue, as tested with Nextcloud 22.2.7 and eb720b9 (Nextcloud 25).

Invalid database credentials show an error
![error](https://user-images.githubusercontent.com/97926121/169364235-de747bea-0377-435d-99ad-167c4f79e772.png)

and the checkbox appears to have been replaced with a button, which is shown after the database credentials are verified.
![no-checkbox](https://user-images.githubusercontent.com/97926121/169364356-454d431b-20c1-42ec-b97e-e5f06aaca899.png)

**Comment by szaimen** [comment]
Thanks for verifying! :)
