### ISSUE TITLE
[NC19.0.1]-Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by Spilarix** [nextcloud/server#21965]
While browsing the web interface, the error log is generating issues like :
`Trying to access array offset on value of type bool at /var/www/html/console.php#69`
In log file : `"level":3,"time":"2020-07-23T07:13:24+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type bool at /var/www/html/console.php#69","userAgent":"--","version":"19.0.1.1"`

Sometimes I can see some other files referenced for the same bug like cron.php#99. I can say it's the same bug because the line of code seems identical :
	`if ($user['name'] !== $configUser['name']) {`

**Steps to reproduce**

Browse the web interface or check logs.
This problem doesn't occured with NC 18.0.7 !

**Server configuration**

Web server : nginx

Database: PostgreSQL

Nextcloud version : [Docker image fpm-alpine 19.0.1](https://github.com/nextcloud/docker/blob/45f3995ab7c46fff7d7e779a00b69443f9a90fa6/19.0/fpm-alpine/Dockerfile)

Updated from an older Nextcloud/ownCloud or fresh install: Fresh install

Are you using encryption : no

**Comment by stueja** [comment]
I can second this with a slightly different message producing a log file of 338 GIGAbyte.
`{"reqId":"8EXXgsUZhoDrRD2Af2qj","level":3,"time":"2020-07-26T08:11:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array
 offset on value of type null at /usr/share/webapps/nextcloud/lib/private/Files/Cache/Scanner.php#418","userAgent":"--","version":"19.0.1.1"}`

**Comment by Spilarix** [comment]
> 
> 
> I can second this on a non-dockerized installation with a slightly different message producing a log file of 338 GIGAbyte.
> `{"reqId":"8EXXgsUZhoDrRD2Af2qj","level":3,"time":"2020-07-26T08:11:00+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":"Trying to access array offset on value of type null at /usr/share/webapps/nextcloud/lib/private/Files/Cache/Scanner.php#418","userAgent":"--","version":"19.0.1.1"}`
I think it's a different issue because the failing test is different and its return type too.

**Comment by Spilarix** [comment]
It seems to be linked to a docker installation with a specific user. I will open an issue on nextcloud-docker.
