### ISSUE TITLE
Dashboard icon too similar to talk icon

### ISSUE THREAD

**Issue by ma12-co** [nextcloud/server#21969]
![Screenshot from 2020-07-23 13-32-25](https://user-images.githubusercontent.com/26852655/88282000-f9951f00-cce8-11ea-87c5-3c1af40b1754.png)

**Comment by juliushaertl** [comment]
I'm open for suggestions here, but this is what we came up with when discussing with @jancborchardt since it nicely fits to the concept of making it the Nextcloud home screen as it mainly reuses the circle element from our logo.

**Comment by ma12-co** [comment]
I still prefer the "3 columns" icon that was used before. I think it has so much more to do with the actual app and doesn't create confusion with talk.

**Comment by skjnldsv** [comment]
You're missing photos and activity @ma12-co. Your example is not a default install.
I think it's fine as it is

**Comment by ma12-co** [comment]
To me they should be more different, regardless of the default app order, but whatever, not a biggie :)

**Comment by kowalski7cc** [comment]
Maybe just decreasing the inner circle radius so there would be more white can make a small difference

**Comment by skjnldsv** [comment]
closing, if Jan wants to open it again, please do with a replacement suggestion and set `1. to develop` :)
