### ISSUE TITLE
[UX] First account creation is a bit long, and there is no indication that something is happening.

### ISSUE THREAD

**Issue by pierreozoux** [nextcloud/server#21964]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to an SSO backend (SAML, ldap..) or self registration
2. Connect for the first time
3. The user account is created
4. It takes more than 20s
5. the page is blank during this time

### Expected behaviour

It would be nicer to show a message telling the user that the account is being created, to helm them wait this time.

### Actual behaviour

The page is blank.

**Comment by rullzer** [comment]
@pierreozoux could you profile your request with xdebug?
I just tried it here with SSO and the account was created in a second or so. So something must be taking up the time on your system.

**Comment by pierreozoux** [comment]
hum, did some more tests, it is not that bad.

Between 8 and 15s.

With or without sso actually it is the same.

And when using SSO the blank page is on the sso side, so nothing about you.

Sorry to bother 😞
