### ISSUE TITLE
Undefined index: redirect_url at core/templates/twofactorsetupselection.php

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#21968]
Hi,

When accessing _/server/index.php/login/setupchallenge_ , the following error is triggered:

`Undefined index: redirect_url at /xxx/core/templates/twofactorsetupselection.php#36`

Setup:
- NC 18.0.6 
- Only 1 authenticator app is installed (twofactor_totp v4.1.3)
- 2FA globally enforced
- Apache 2.4
- PHP 7.4

Not sure whether it is something similar like #2854? 

How could I quickly patch this manually? Thanks!

**Comment by kesselb** [comment]
```
Index: core/templates/twofactorsetupselection.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- core/templates/twofactorsetupselection.php	(revision 1edd191af77e9a0ac4f4665041f862e021137f08)
+++ core/templates/twofactorsetupselection.php	(date 1595530177267)
@@ -33,7 +33,6 @@
 			   href="<?php p(\OC::$server->getURLGenerator()->linkToRoute('core.TwoFactorChallenge.setupProvider',
 								[
 									'providerId' => $provider->getId(),
-									'redirect_url' => $_['redirect_url'],
 								]
 							)) ?>">
 				<?php
```

A redirect url is not required for setup provider. It's also not available at this stage. I guess the above patch should fix it but never used this feature before ;)

cc @rullzer

**Comment by GitHubUser4234** [comment]
Thanks @kesselb, removed the suggested line and no more errors show up.

**Comment by rullzer** [comment]
@ChristophWurst do you remember why this is there?
Maybe we can remove it? Or else have some logic to only add it if it is set?

**Comment by sam9032** [comment]
Thanks @kesselb. The same error occurred in my Nextcloud instance and that fixed it. Would be great to have this patch in the repo.

**Comment by acsfer** [comment]
Problem remains at 21.0.1.

**Comment by andyxheli** [comment]
Also still on 20.0.8

**Comment by andyxheli** [comment]
I remove the line 'redirect_url' => $_['redirect_url'], in /var/www/nextcloud/core/templates/twofactorsetupselection.php#36 setup a new user account and configure 2FA on first logon and error is no longer there. Im sorry about the pull request i changed the wrong file.

**Comment by andyxheli** [comment]
any update on this ?

**Comment by sveeke** [comment]
Also an issue on 23.0.0.

**Comment by andyxheli** [comment]
Still an issue NC 23.0.3

{"reqId":"haaLKh61xoXXv4t7erSJ","level":3,"time":"2022-04-12T14:05:11+00:00","remoteAddr":"10.0.0.1","user":"Steve","app":"PHP","method":"GET","url":"/login/setupchallenge","message":"Undefined array key \"redirect_url\" at /var/www/nextcloud/core/templates/twofactorsetupselection.php#36","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36","version":"23.0.3.2","exception":{"Exception":"Error","Message":"Undefined array key \"redirect_url\" at /var/www/nextcloud/core/templates/twofactorsetupselection.php#36","Code":0,"Trace":[{"file":"/var/www/nextcloud/core/templates/twofactorsetupselection.php","line":36,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":180,"args":["/var/www/nextcloud/core/templates/twofactorsetupselection.php"],"function":"include"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":179,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":204,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":171,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1006,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":36,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"id":"6255979664931"}
