### ISSUE TITLE
Feature Request: Prevent duplicate uploads server-side

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#220]
### Wanted behaviour
When I attempt to upload a duplicate file, I'd like it to prompt me before it uploads. Maybe a message that states "_x_ with that name and datestamp already exists. Upload another copy?" 

In an ideal world it would be able to do this with several files in one go, rather than 1 by 1 so as to agree or disagree with duplicate uploads all at once, but anything would be acceptable at the moment.

### Actual behaviour
Currently uploading duplicates just appends a number in brackets, meaning I then later have to manually remove duplicates.

Context: 
https://help.nextcloud.com/t/is-there-anything-to-stop-duplicates-being-uploaded/1146

**Comment by tobiasKaminsky** [comment]
In the linked entry I thought you were talking about the android app?

**Comment by jasonbayton** [comment]
Well I figured this functionality should be server side to work with all clients?

**Comment by tobiasKaminsky** [comment]
Yes, but then this must be opened in every client as the server (web ui) already supports this afair?

**Comment by jasonbayton** [comment]
OK, should this be closed or moved?

**Comment by MorrisJobke** [comment]
This is solved on the server component. Please open this for the clients that behave wrongly (in the web UI the conflict dialog is in a current version show before the first upload happen).

Thanks :)

**Comment by mar1u5** [comment]
...can users still use `owncloud/__` repositories for such issues if they are not forked already 😁 @MorrisJobke

**Comment by MorrisJobke** [comment]
Sure :)
