### ISSUE TITLE
When adding users, the user count on the left column only updates after refresh

### ISSUE THREAD

**Issue by jameslao** [nextcloud/server#22009]
### Steps to reproduce
1. Add a user
2. The user shows up on the right column 

### Expected behaviour
The user count should automatically update

### Actual behaviour
On the left column, the user count in each group only updates after a page refresh

### Server configuration

Nextcloud 19.0.1 built 22400

**Comment by kesselb** [comment]
Sounds like #20438

**Comment by jameslao** [comment]
> Sounds like #20438

Yes. Let's work on that one.
