### ISSUE TITLE
Can't view PDF in files app anymore

### ISSUE THREAD

**Issue by heptathlon** [nextcloud/server#2200]
Using latest master (6c11c54434b29bb9f7f07ba9a8070ed8308bc5a4), when selecting a PDF file from the Nextcloud file list I'd expect to see the PDF in my browser. However I only see a white screen. The developer console logs:

`test.pdf:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-2kQS8h/rR9ylH+S6eZbKdsD/cB6Ljcz2Rg607Jnk/eY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

**Comment by LukasReschke** [comment]
Make sure to use master of the files_pdfviewer app as well.

**Comment by heptathlon** [comment]
How?

**Comment by LukasReschke** [comment]
`git checkout master && git pull` in the apps folders that you use. That said, using git in production is not recommended and not officially supported.

**Comment by heptathlon** [comment]
I do know how to pull, yeah, thanks. I don't use the the files_pdfviewer app at all.

**Comment by LukasReschke** [comment]
Then you need to properly fill out the issue template as otherwise we have no idea what you are doing, what browser you are using etc. – It's there for a reason 😉
