### ISSUE TITLE
Can't view/download PDF in files app anymore

### ISSUE THREAD

**Issue by heptathlon** [nextcloud/server#2201]
Continuation from #2200

### Steps to reproduce
1. Upload a PDF file to the root directory with name "test.pdf"
2. Open web interface
3. Click on the PDF name (test.pdf)
4. Get redirected to /remote.php/webdav/test.pdf

### Expected behaviour
Download should start

### Actual behaviour
I get a white screen with error
`test.pdf:1 Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'none'". Either the 'unsafe-inline' keyword, a hash ('sha256-2kQS8h/rR9ylH+S6eZbKdsD/cB6Ljcz2Rg607Jnk/eY='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.`

### Server configuration
New Nextcloud installation from master (6c11c54), without any additional apps.

Browser: Chrome 54

ok @LukasReschke ?

**Comment by heptathlon** [comment]
Any news on this?

**Comment by MorrisJobke** [comment]
> New Nextcloud installation from master (6c11c54), without any additional apps.

You need the files_pdfviewer app: https://github.com/nextcloud/files_pdfviewer. ;)

Works with 10.0.2 and 11.0.0 tar balls just fine.
