### ISSUE TITLE
warn in admin overview when client protocol and server side detected protocol don't match

### ISSUE THREAD

**Issue by lub** [nextcloud/server#22010]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When you configure Nextcloud with a reverse proxy and don't correctly configure the used protocol (e.g. with overwriteprotocol) you can have issues like broken CSP.

**Describe the solution you'd like**
I'd like a warning in the admin settings when the protocol of the browser (typically https) and the one that is detected server side (with reverse proxy often http) mismatch and link to the docs (e.g. https://docs.nextcloud.com/server/19/admin_manual/configuration_server/reverse_proxy_configuration.html#overwrite-parameters)
The cause for these symptoms (CSP error) is otherwise probably not really obvious for many users.

**Describe alternatives you've considered**
RTFM, but that'd probably also be the case for many other warnings in the settings.

**Additional context**
Seems I was not the only one having trouble with this:
https://help.nextcloud.com/t/csp-error-during-login-from-nextcloud-windows/81356/6

**Comment by kesselb** [comment]
> I'd like a warning in the admin settings when the protocol of the browser (typically https) and the one that is detected server side (with reverse proxy often http) mismatch and link to the docs

There is a warning https://github.com/nextcloud/server/pull/17692 for Nextcloud 19.
