### ISSUE TITLE
File metadata is updated incorrectly after editing

### ISSUE THREAD

**Issue by bence-ulx** [nextcloud/server#22023]
### Steps to reproduce
1. Check timestamp/filesize of a file (e.g. a text file).
2. Edit file and close editor.
3. Check timestamp/filesize again.

### Expected behaviour
Live timestamps should show the correct time after editing. File size should also be updated.

### Actual behaviour
File metadata isn't updated after editing.

### Server configuration

**Operating system:** Red Hat Enterprise Linux Server release 7.8 (Maipo)

**Web server:** Apache/2.4.34

**Database:** mysql  Ver 15.1 Distrib 5.5.65-MariaDB

**PHP version:** PHP 7.3.11

**Nextcloud version:** Nextcloud 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** Github

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.6.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - lookup_server_connector: 1.8.0
  - oauth2: 1.8.0
  - provisioning_api: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
