### ISSUE TITLE
Bad migration from NC 9.x to NC 10.x - All LDAP users unable to login

### ISSUE THREAD

**Issue by bcooksley** [nextcloud/server#2202]
### Steps to reproduce
1. Setup LDAP with NC 9.x, specifying your LDAP queries manually, with the login query to contain (uid=%uid) or equivalent
2. Upgrade to NC 10.x
3. Find your LDAP users can't login

### Expected behaviour
NextCloud upgrade process should not tamper with user listing LDAP query, or if this is a new filter it should ensure the user login query doesn't contain any conditional filters such as %uid when it does so.

The admin should be informed where automated munging of the query is done, or be prompted to input a corrected query.

### Actual behaviour
Upgrade process happened "smoothly" but was left unable to login at all.

No error message was issued by the frontend indicating why one is unable to login - it just redirects you back to the login page.

Log files, due to the flood of spurious / debug level messages from user_ldap are unhelpful in investigating the actual cause of the issue.

### Server configuration
**Operating system**: Ubuntu 14.04, unmodified.

**Web server:** Apache 2.4, using php5-fpm

**Database:** MySQL 5.5.53

**PHP version:** 5.5.9-1ubuntu4.20

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NextCloud 9.0.54

Was previously updated shortly before from Owncloud 8.2.9 to NextCloud 9.0.54 - Login worked fine after this upgrade however.

**Where did you install Nextcloud from:** Nextcloud.com

**Signing status:**
No errors have been found.

**List of activated apps:**

Enabled:
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_ldap: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - activity
  - documents
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_pdfviewer
  - files_retention
  - firstrunwizard
  - user_external
  - user_saml

**The content of config/config.php:**
<Withheld>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No external storage

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

#### LDAP configuration (delete this part if not used)
<WIthheld, Please Contact Privately to Discuss>

### Client configuration
Not relevant

### Log
Too big to provide, filled with confidential / sensitive information, withheld.

**Comment by MorrisJobke** [comment]
We haven't seen this issue on other instances again. Does this still happen? I will close this for now, but if this is still the case with a recent (11.0.4 or 12.0.2) Nextcloud version I will reopen the ticket. Thanks
