### ISSUE TITLE
Migration from OC 9.1.2 to NC 10.0.1 not possible

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#2203]
If you try to migrate from OC 9.1.2 to 10.0.1 you get the message that downgrading is not possible. The internal version strings are probably 9.1.2.5 and 9.1.1.5 (NC 10.0.1).

Question: What are users supposed to do?

Background: They start to change the version string manually to bypass the downgrade check.
ref:
https://help.nextcloud.com/t/migrating-from-oc-9-1-2-latest-to-nc-10-01-fails-common-problem/5240
https://help.nextcloud.com/t/cannot-downgrade-nextcloud-9-1-2-5-to-9-1-1-5-solution/5265

**Comment by tflidd** [comment]
even more people are asking:
https://help.nextcloud.com/t/error-during-upgrade-owncloud-9-1-2-to-nextcloud-10-0-1/5642
https://help.nextcloud.com/t/change-from-owncloud-to-nextcloud/5563

@LukasReschke @MorrisJobke

**Comment by MorrisJobke** [comment]
Mmmmh ... maybe we also should run also integration tests to upgrades from ownCloud to Nextcloud. Because we only test this from time to time (not how nextcloud migrations).

cc @karlitschek

**Comment by karlitschek** [comment]
hmm. true. maybe we should check this automatically. yes. A lot of people are migrating

**Comment by iteco** [comment]
original question is still open .. is the version string manipulation the solution (referred above) or should I wait that NC 11 is out ? (as you have solved it there.. ??)  

and once you answer to that, you could also update migration page accordingly
https://nextcloud.com/migration/

cheers,

**Comment by MorrisJobke** [comment]
> original question is still open .. is the version string manipulation the solution (referred above) or should I wait that NC 11 is out ? (as you have solved it there.. ??)

For now there is no way around the manual change of the version. The only way I see is to bring this somehow into the updater logic (in /updater) where we can detect before replacing the current code if it is an ownCloud or an Nextcloud instance and then tweak the version number in there. On the other hand: we should somehow verify that the migration between ownCloud and Nextcloud still works. I guess there will be some point in time where this is simply not possible anymore because of changed DB layout.

**Comment by falolaf** [comment]
Today I tried to migrate from OC91.2 to NC 10.0.2 and get this:
Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.2.5 to 9.1.2.2)

Any advice? Should I just wait for next release?

**Comment by mbewley** [comment]
I get the error with NC 10.0.0.2 as well (it seems people anticipated it would support upgrade from 9.1.2.5, not just 9.1.2.2). I also can't get the manual upgrade to work (by forcing version number changes in a file). I've tried with changing the OC version listed in version.php from 9.1.2.2 to 9.1.2.5, but that just caused an internal server error. Any ideas?

**Comment by j-ed** [comment]
I did similar tests last week and found out that it is possible to change the version number in the `config.php` file from `'version' => '9.1.2.5',`to `'version' => '9.1.2.2',` to get system access back. I've not yet realized any problems with the system although **downgrading** is officially not supported.

**Comment by falolaf** [comment]
Now, is this change of version string in config.php the official way to do the migration? As it is not mentioned on the migration page it feels more like a hack for now.

**Comment by ngleb** [comment]
No, this is an unofficial method for solving the issue.

**Comment by falolaf** [comment]
Now that NC11 is out in the wild and I have seen some reports that going to NC11 directly from OC9.1.2 works. Is this a valid path to take even if the migration/upgrade manuals tells not to skip major relases?

**Comment by MorrisJobke** [comment]
> Now that NC11 is out in the wild and I have seen some reports that going to NC11 directly from OC9.1.2 works. Is this a valid path to take even if the migration/upgrade manuals tells not to skip major relases?

Yes. Nextcloud 10.0 is internally named 9.1 so it doesn't skip a major version.

**Comment by tflidd** [comment]
There is still a lot of confusion (https://help.nextcloud.com/t/migrating-from-owncloud-to-nextcloud/551/93). Would be great to have some clarification

- if we can migrate from OC 9.1.x -> NC 10.0.x by just taking any version number that is smaller than the current in Nextcloud.
- if OC 9.1.x can directly be upgraded to NC 11

**Comment by falolaf** [comment]
I did the migration from OC 9.1.2.5 to NC 11 yesterday and everything seems
to work.

2016-12-17 10:13 GMT+01:00 tflidd <notifications@github.com>:

**Comment by nickvergessen** [comment]
The odd thing here is, that we have code in place to allow this:
https://github.com/nextcloud/server/blob/776f5bcd345b77b05cbb9cd3fd234f3ba40eac25/lib/private/Updater.php#L196-L202

When the first and second digit of the version are the same, the update is still performed, when the vendor of the update and of the old database are not the same. So the only way I can reproduce this is by trying the update a second time.

**Comment by tribut** [comment]
If I read the git log correctly, this code (vendor switch detection) is only available in NC 11. However the docs say to upgrade from OC 9, one must first install NC 10.

**Comment by cweiske** [comment]
I had the same problem today, with message:

    OC\HintException: [0]: Downgrading is not supported and is likely to cause unpredictable issues (from 9.1.4.2 to 9.1.3.2) ()

That was the latest ownCloud from the official debian packages.

I modified my `config/config.php` file to have version `9.1.1.2`, and then the upgrade worked.

**Comment by MorrisJobke** [comment]
> I modified my config/config.php file to have version 9.1.1.2, and then the upgrade worked.

This is also the only workaround I have in mind. @nickvergessen The vendor was only set on upgrade. So an upgrade needs to happen before you can upgrade to Nextcloud with this version number.

**Comment by nickvergessen** [comment]
Yeah I'm sorry, I think OC never patched the "set vendor on install".

**Comment by MorrisJobke** [comment]
In those cases we recommend to upgrade from ownCloud 9.1.x to Nextcloud 11, because this is an allowed upgrade path. And also Nextcloud 11 is now out long enough. See https://github.com/nextcloud/server/blob/stable11/version.php#L39-L41
