### ISSUE TITLE
Error when updating NC 18.0.6 to 18.0.7

### ISSUE THREAD

**Issue by oneilonline** [nextcloud/server#22049]
Error when updating NC 18.0.6 to 18.0.7 via the web admin portal:
Curl error: SSL: no alternative certificate subject name matches target host name 'download.nextcloud.com'

Dig results on server:
download.nextcloud.com.	60	IN	A	0.0.0.0

DNS Nameservers: 1.0.0.3,1.1.1.3

Is download.nextcloud.com having issues?

Thank you

**Comment by blizzz** [comment]
Nope, did not have. Obviously the answer from the DNS servers was wrong,  for  whatever reason. if i run dig now, they report the correct address for me now.
