### ISSUE TITLE
Error when upgrading nc 18

### ISSUE THREAD

**Issue by omgslinux** [nextcloud/server#22047]
Hi. Some time ago, I did a fresh install of nc 16, and provided support for utf8mb4 according to the docs. I set the config accordingly. I had several problems and had to do lots of manual changes in previous upgrades, all related to the key size.

Now, I'm upgrading from nc 18.0.1 to latest 18.0.7 from inside nc administration options. After initial checks, when upgrading from the web browser, I get this known error (I'm aware of it, yes).

    Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

In this case, the table doesn't exist, so I can't modify it. Anyway, I see this happens too often to many people when trying to use utf8mb4, and there seems not to be a clean solution yet. So, with the intention of trying to help, I wonder what I can do in order to help to solve this problem when upgrading forever, without lots of manual operations. It looks like the upgrade configuration files ignore or can't handle properly the mb4 support, but I'm not sure where to find them all and do the proper changes without spending too much time. So, if anybody can provide a solution this way, I think it could be the best solution.

Thanks in advance.

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
