### ISSUE TITLE
Slow upload speed (max 1MB/s  - 18.0.6 & 19.0.1 )

### ISSUE THREAD

**Issue by NiTRoeSE** [nextcloud/server#22045]
Hi with older versions of NC i never had issues with upload speed, unfortunately i cant say when this happens first time ( i think all was ok till NC 18 ) but now every upload to the cloud reaches a max speed of 1MB/s most of upload time its between 100KB/s - 500KB/s. 
Previously upload speed was over 10MB/s. It doesnt matter if its many small or a single large file, the speed is always slow like described. (Webinterface, Downloading Files, Deleting Files etc. runs fast , only upload is affected)

I tried a lot of things to find the bottleneck or a reason for this.

- checked I/O of HDD —> OK (1-5%)

- checked CPU Load —> OK (0.15-0.20)

- checked network interfaces

- checked network speed of server: OK —> (Down: ~350Mbit , Up: ~350 Mbit)

- Checked log files: no errors in nextcloud.log & php.log & apache.err log

- Disabled: httpd2 —> no change

- Disabled: mod_requesttimout —> no change

- Disabled all nextcloud apps —> no change

- Run occ repair command —> no change

- Upgraded to NC version 19.01 —> no change

- Upload a lot of big image files on same server to a wordpress runs fast.

—-

## Server configuration detail
*Operating system:* Linux 3.10.0-1127.13.1.el7.x86_64 #1 SMP Tue Jun 23 15:46:38 UTC 2020 x86_64

*Webserver:* Apache/2.4.43 (codeit) OpenSSL/1.1.1g (fpm-fcgi)

*Database:* mysql 10.3.23

*PHP version:* 7.3.20

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, intl, json, ldap, exif, mysqlnd, PDO, Phar, posix, pspell, shmop, SimpleXML, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mcrypt, mysqli, pdo_mysql, pdo_sqlite, wddx, xmlreader, apcu, geoip, igbinary, imagick, zip, redis, Zend OPcache

*Nextcloud version:* 19.0.1 - 19.0.1.1

*Updated from an older Nextcloud/ownCloud or fresh install:*
```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.0
 - admin_audit: 1.9.0
 - announcementcenter: 3.8.1
 - audioplayer: 2.11.0
 - calendar: 2.0.3
 - circles: 0.19.3
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contacts: 3.3.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - deck: 1.0.5
 - documentserver_community: 0.1.7
 - event_update_notification: 1.0.2
 - external: 3.6.0
 - extract: 1.2.4
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_downloadactivity: 1.8.0
 - files_markdown: 2.3.0
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - onlyoffice: 4.3.0
 - password_policy: 1.9.1
 - photos: 1.1.0
 - polls: 1.4.3
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - quota_warning: 1.8.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - spreed: 9.0.2
 - support: 1.2.1
 - survey_client: 1.7.0
 - text: 3.0.1
 - theming: 1.10.0
 - theming_customcss: 1.6.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - encryption
 - files_external
 - groupfolders
 - radio
 - recommendations
 - systemtags
 - user_ldap

```

```
{
    "updatechecker": false,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.domain.de",
        "www.cloud.domain.de"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.domain.de",
    "dbtype": "mysql",
    "version": "19.0.1.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "logtimezone": "Europe\/Berlin",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "loglevel": 2,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "theme": "",
    "maintenance": false,
    "filelocking.enabled": true,
    "appstore.experimental.enabled": false,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enable_previews": true,
    "log_type": "owncloud",
    "logfile": "\/clouddata\/owncloud.log",
    "log_authfailip": true,
    "log_query": false,
    "log_rotate_size": 52428800,
    "htaccess.RewriteBase": "\/",
    "updater.release.channel": "stable",
    "mysql.utf8mb4": true,
    "integrity.check.disabled": false,
    "app_install_overwrite": [
        "radio",
        "contacts",
        "polls",
        "circles"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```

*External storages:* files_external is disabled

*Encryption:* no

*User-backends:*
* OC\User\Database

—-

I dont know if its a nextcloud problem, but for me it seems so because other services on same server runs fast as usual. I hope someone could help. 

Thanks in advanced 🙂

**Comment by f-s** [comment]
I have a similar bug here https://github.com/nextcloud/server/issues/21428

**Comment by mageunic** [comment]
Hi @NiTRoeSE, I have tried something and I discovered something strange on my nextcloud server. 
When I set a value other 0 in this command:
`sudo -u www-data php occ config:app:set files max_chunk_size --value 0`
I have 300 bytes/seconde of uploads but when 0 is used i have 11 MB/s of uploads ( max upload that I can have because i used a 100 mb/s switch)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
