### ISSUE TITLE
Symlinks in external storages (local) do not work 

### ISSUE THREAD

**Issue by allcoolusernamesaregone** [nextcloud/server#22040]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a directory e.g. /mnt/external/ (ext4)
2. Have a directory e.g. /mnt/anotherdir/ (ext4)
3. Create a symlink /mnt/external/theotherdir to /mnt/anotherdir 
4. Create an external storage "test" of type local with target path /mnt/external/

### Expected behaviour
one should see the content in the storage "test" and should also see and able to access the directory "theotherdir" 

### Actual behaviour
- various error messages in webclient or android client when trying to access "test" - not even the content of "test" itself is visible
- error messages
  * Error | no app in context | OCP\Files\ForbiddenException: Following symlinks is not allowed
  * Error | core | Following symlinks is not allowed ('/mnt//anotherdir' -> '/mnt/anotherdir/' not inside '/mnt/external/')

As written in Issue #11879: changing  $allowSymlinks to true in lib/private/Files/Storage/Local.php fixes the behavior and the "base" or "root" of the external storage can be seen/accessed and the symlink directory can be seen and accessed also.

I understand the cause or issue to do not support symlinks in the own data directory, but in an external storage it must not be a problem. at least it should be able to see the base/root directory content of the external storage, even if there just is a symlink, even if this symlink could not be accessed. But the parent must work.

### Server configuration

**Operating system:**  Debian GNU/Linux 9 (stretch)

**Web server:** Nginx

**Database:**  MariaDB

**PHP version:** 7.3

**Nextcloud version:** 19.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** not recently

**Where did you install Nextcloud from:** officieal dowload package

**Are you using external storage, if yes which one:** see above

**Comment by jkufner** [comment]
Moreover, the failure due to an existing symlink is a wrong behavior regardless the Nextcloud's approach to the symlinks. They should be either ignored or followed, but it should not crash with an exception just because a symlink is found.

**Comment by jkufner** [comment]
A quick workaround (with possible security consequences):

````.patch
--- a/lib/private/Files/Storage/Local.php       2020-12-16 12:41:55.090057472 +0100
+++ b/lib/private/Files/Storage/Local.php       2020-12-16 12:41:37.622057490 +0100
@@ -57,7 +57,7 @@

        protected $dataDirLength;

-       protected $allowSymlinks = false;
+       protected $allowSymlinks = true;

        protected $realDataDir;
`````

**Comment by szaimen** [comment]
I suppose this issue is still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by hashworks** [comment]
Since it is now possible to configure this with `'localstorage.allowsymlinks' => true` I think we can close this.

**Comment by szaimen** [comment]
Thanks for the feedback! Doing as suggested.

**Comment by haarp** [comment]
`localstorage.allowsymlinks` is a solution when you actually want to follow symlinks. It doesn't cover the use case of them simply existing without Nextcloud throwing exceptions. That's what #27448 was about.

**Comment by allcoolusernamesaregone** [comment]
> `localstorage.allowsymlinks` is a solution when you actually want to follow symlinks. It doesn't cover the use case of them simply existing without Nextcloud throwing exceptions. That's what #27448 was about.

I second this. Setting allowymlinks to true was my workaround and is working, with no negative other effects for me. But it is not the proper solution.
