### ISSUE TITLE
Feature request: Make auto-login to external sites possible

### ISSUE THREAD

**Issue by scroom** [nextcloud/server#2205]
### Steps to reproduce
1. Activate the external sites app
2. Choose an external site to be integrated in your NC (for example a wiki connected to the same LDAP as NC)
3. The user will have to enter his/her login data always.

### Expected behaviour
Would be cool if the admin could choose "take the NC login data to login to site".

### Actual behaviour
As described above.

### Server configuration
**Operating system**: Ubuntu 16.04 (shouldn't be relevant)

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP 5.5.9-1ubuntu4.20 (cli)

**Nextcloud version:** 10.0.1 (stable)

**Comment by MorrisJobke** [comment]
@scroom sorry for the late reply. The external sites app is in the apps repo. Could I ask you to reopen this feature request there? https://github.com/nextcloud/apps/issues

Thanks :)
