### ISSUE TITLE
XSS judged due to a Content-Type mismatch in the request header

### ISSUE THREAD

**Issue by k-ooshiro** [nextcloud/server#22066]
Due to a mismatch between the Content-Type in the request header and the Content-Type in the body (payload) section, the WAF application determines an XSS attack and blocks the requests.

In Nextcloud 16, the Content-Type of the request header is "text/xml", but in Nextcloud 18, it is "text/plain;charset=UTF-8".
I believe that the Content-Type of the request header must match the Content-Type of the body (Payload) section.

I've attached a screenshot for your reference in the browser log section.

### Steps to reproduce
1.Open the files app and click Nextcloud.png
2.Check the Request Header Content-Type when displaying file details or previewing a file.

### Expected behaviour
The Content-Type in the request header and the Content-Type in the body (Payload) part are the same.

### Actual behaviour
 Content-Type does not match.

### Server configuration

**Operating system:** CentOS7

**Web server:** Nginx

**Database:** MariaDB 10.3

**PHP version:** php-7.3.6 with php-fpm

**Nextcloud version:** 18.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** tar archive from nextcloud.com

#### Browser log
Request header for Nextcloud 16.0.10
![RequestHeaders_16_0_10](https://user-images.githubusercontent.com/13651800/89000920-908a5880-d333-11ea-8a42-81e7d1a1757d.png)

Request header for Nextcloud 18.0.6
![RequestHeaders_18_0_6](https://user-images.githubusercontent.com/13651800/89000930-98e29380-d333-11ea-9ebc-f83d98d9c674.png)

</details>

**Comment by robertofabrizi** [comment]
@k-ooshiro  I have the exact same issue, the Sucuri WAF thinks they are XSS, did you manage to find a solution to this?

**Comment by k-ooshiro** [comment]
@robertofabrizi We have not found an effective solution either. Therefore, we have registered an exclusion URL so that the WAF side will not block it. 
It would be nice if we could match the content types, I think it will no longer be blocked.

**Comment by robertofabrizi** [comment]
@k-ooshiro I thought about that too but the only "generic" part to whitelist that I could think of is ^remote.php/dav/files which seems a bit "extreme" to me, did you make a better filter? Thank you

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by robertofabrizi** [comment]
@szaimen they still don't match

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
