### ISSUE TITLE
Make the file drop feature more obvious

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2207]
I wasn't aware initially when I installed NC the public filedrop option had been included until I read this article:

https://nextcloud.com/why-open-source-rocks/29

Then it took me a little while longer to actually be able to enable it as Google searches and document hunting on docs.nc led me nowhere.

It was only upon clicking "Allow editing" and "Hide file listing" out of sheer luck that I realised that's what it is..

Can this be made more obvious in a future update? Perhaps promote it as a public filedrop rather than wording it as hiding directory contents?

It'd be a little clearer.

Context:
https://help.nextcloud.com/t/filedrop-can-it-be-a-little-more-obvious/659

**Comment by tflidd** [comment]
If you only want to change the wording, the string can be found here:
https://github.com/nextcloud/server/blob/7100a1b3472f35ba8edb6e427fa6657dc53ef63b/core/js/sharedialoglinkshareview.js#L340
(you can clone the nextcloud-server-repo, create a new branch, make and submit the changes and then create a pull request).

**Comment by jasonbayton** [comment]
I think a discussion needs to be had first as the wording was seemingly chosen for a reason, but I'd hope for a little more logic than just a wording change as outlined in the context thread on help.nc:

https://help.nextcloud.com/t/filedrop-can-it-be-a-little-more-obvious/659/5?u=jasonbayton

**Comment by MorrisJobke** [comment]
@jancborchardt We talked exactly about this during the hackweek ;)

It's mentioned in the review of 11 as "Think about 'hide file listing'" - see #2134

@nextcloud/designers Any ideas how to make this more discoverable? Maybe also show this by default (when "Allow edit" is not ticked but then show it disabled?)

**Comment by jasonbayton** [comment]
@MorrisJobke might've been from my original post, as that was June 😄 

I made this suggestion: 
![](https://help.nextcloud.com/uploads/default/original/1X/8aac8f9a86209451337f4fec02a9458960f265da.png)

and.. err.. this one too, but I make a lot of drop folders for media uploads after gigs, so I'm not sure how often the "normal" userbase would use this:

![](https://help.nextcloud.com/uploads/default/original/1X/2e2e654cbab96f95b9138338eba3372dea50868b.png)

**Comment by jancborchardt** [comment]
@jasonbayton that seems good! I’d go first with the rewording in the share menu. Adding it to the »New« menu is a bit too much since the Collabora stuff is also in there.

@nextcloud/javascript what do you think?

**Comment by jancborchardt** [comment]
There’s a pull request for the wording at #2243 

In addition, and what I also mentioned there, instead of the greying out which would be a bit confusing I propose:
- showing both options
- making them radio buttons
- with »Allow upload and editing« being the default

This is probably something for Nextcloud 12 though because of the feature freeze.

**Comment by jasonbayton** [comment]
I'm game for radio buttons. Not sure why I didn't think of that :)

**Comment by jancborchardt** [comment]
Right, also as you mentioned in the pull request. We need to go for a 3-option radio button. :)

**Comment by jasonbayton** [comment]
I'm not a big GH user, I may have accidentally commented on the PR and then realised it should be here!

**Comment by Espina2** [comment]
So what I suggest here, is to create page of upload instead of open the OS file manager. 

If we have another page its better to upload files from different folders and organize them better. For example you have created a new empty folder and you want to upload files from multiple folders. Right now you have to one by one. 

In that new screen you can pretty easily show that you can drag and drop files. With that in mind people will get use to it and its normally to just drag and drop to window without going to the new page. 

Something like this (image from the internet I can make a mockup if you guys agree with me)
![image](https://cloud.githubusercontent.com/assets/11150206/20635215/21532b86-b352-11e6-9466-991faea9350a.png)

What you think @jancborchardt @nextcloud/designers

**Comment by jasonbayton** [comment]
@jancborchardt I feel like I've helped make a positive minute change to NC11 ;)

![image](https://cloud.githubusercontent.com/assets/3178412/21182232/e8b21d1c-c1f9-11e6-8876-551bfe431bf8.png)

I'm looking forward to 12 though. I get the "allow upload and edit" then "upload only" appearing after, but I still think the radio buttons will make it truly intuitive.

**Comment by jancborchardt** [comment]
@Espina2 this issue is more about making the feature more obvious for people _sending out_ the link, not receiving it. :)

@jasonbayton you sure did! Thanks a lot for the feedback and keep it coming :smiley:

**Comment by MorrisJobke** [comment]
@jancborchardt We awaited some help here from you but the PR was closed in the meantime, because of inactivity: #3784

**Comment by jasonbayton** [comment]
Don't leave us hanging @jancborchardt!

**Comment by Espina2** [comment]
I think @eppfel open a pull request with the same improvoment but based on this, https://github.com/nextcloud/server/issues/4273

**Comment by jasonbayton** [comment]
So I don't see the changes in 12 beta for a radio button arrangement. Is it going to make the final?

**Comment by MorrisJobke** [comment]
> So I don't see the changes in 12 beta for a radio button arrangement. Is it going to make the final?

It wasn't finished in time.

**Comment by jasonbayton** [comment]
Bummer. Bring on 12.1! 🤣

**Comment by MorrisJobke** [comment]
> Bummer. Bring on 12.1! 🤣

I guess we will have no 12.1 ... the next one will be 13. 🤔

**Comment by MorrisJobke** [comment]
Fix for this is in #4681

**Comment by MorrisJobke** [comment]
Merged
