### ISSUE TITLE
Missing Avatars in shared links

### ISSUE THREAD

**Issue by meisterleise** [nextcloud/server#22072]
### Steps to reproduce
1. sharing a folder for upload only
2. open the link as an unknown user

### Expected behaviour
Avatar of the sender should be shown. Should look like this: [Screenshot](https://nimb.ws/DHc53E)
(works fine in nc17.x

### Actual behaviour
the avatar of the sender is not shown: [screenshot](https://nimb.ws/dH2tG8)
(if the recipient is logged in, the avatar is shown)

### Server configuration

**Operating system:**
Linux

**Web server:**
Apache

**Database:**
5.7.25

**PHP version:**
7.3.13

**Nextcloud version:** (see Nextcloud admin page)
18.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
from 17.x

**Where did you install Nextcloud from:**
nc

**Comment by meisterleise** [comment]
Hmm – I've noticed that this feature works totally different in nc19. There you don't see the sender's name anymore. Just the shared folder. [Screenshot](https://nimb.ws/zJURoh)

**Comment by szaimen** [comment]
cc @nextcloud/designers I can reproduce this on NC21.0.2 but I don't recall if this was maybe a privacy decision...

**Comment by skjnldsv** [comment]
I guess this is because we stopped displaying user informations on public pages, for privacy reasons.

@nickvergessen I think you did the pr, no? Any idea what we should take here? Stop displaying the avatar entirely?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/215aef3cbdc1963be1bb6bca5218ee0a4b7f1665/apps/files_sharing/lib/Controller/ShareController.php#L345

From description point of view this uses the wrong constant. The avatar should be controlled by `!== IAccountManager::SCOPE_PRIVATE` and the name always be displayed?

**Comment by nickvergessen** [comment]
Ref of original implementation was https://hackerone.com/reports/752353
But the description of the scopes now explicitly mentions "and guests" on "Local", so yeah private avatar should not be shown, but the name could be always shown.

**Comment by szaimen** [comment]
There is a discussion about this here, too:
https://github.com/nextcloud/server/issues/26541

**Comment by szaimen** [comment]
In my opinion it is okay to show neither the name nor the avatar on shared links sites. But since this issue is about the avatar, we should maybe close this and open a new one for the name if it is important?

**Comment by nickvergessen** [comment]
I would vote to just remove the avatar/name thing from there. The name is/can be shown in the top left with an adjusted/removed scope check, but the avatar does not need showing.

**Comment by meisterleise** [comment]
I found it best as it was originally (nc17) and my logo (avatar) was displayed large.
The avatar provides trust because it lets poeple who know me and my logo know that the link is coming from a trustworthy person.

**Comment by szaimen** [comment]
> I would vote to just remove the avatar/name thing from there. The name is/can be shown in the top left with an adjusted/removed scope check, but the avatar does not need showing.

He? I was actually not able to make the avatar nor the username visible on shared pages on NC21.0.2. What did I do wrong?
