### ISSUE TITLE
Provide link when moving folder/file to immediately jump to location

### ISSUE THREAD

**Issue by monsieurhannes** [nextcloud/server#22079]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Hi,
I think NC improved immensly over the months I'm using it now and it also feels faster! Thanks for everyones work!

**Is your feature request related to a problem? Please describe.**
No, it's not a real problem, just a nice feature that might not be hard to implement - but I'm don't even know where to begin with such things.
When you move a folder in Nextcloud you go through your sometimes quite deep folder structure and select the final location. Often you want to edit or share the folder after moving it, the process of going through the same structure once again is quite tedious.

**Describe the solution you'd like**
It would be great if NC would provide a short info banner e.g. on the bottom that confirms that the folder is moved and asks if you want to jump to it. Similar to the "undo" banner on Gmail, but with a link to the folder:
![grafik](https://user-images.githubusercontent.com/20651440/89098053-7b213700-d3e4-11ea-9a22-5e687dc7dc7c.png)

**Describe alternatives you've considered**
There are two options, one is to jump into the folder, but I think it's more useful to jump to the parent folder, that way it would even work for files.

**Comment by monsieurhannes** [comment]
Just me thinking of this or did it come with a wave of other issues? ;-)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
