### ISSUE TITLE
Preview folder full with long ago deleted files on productive server without bash

### ISSUE THREAD

**Issue by snoopy72** [nextcloud/server#22082]
I read all the threads regarding those "magically" full preview folders - because i have the same problem here:

15 GB of previews from photos, deleted several weeks ago.

i am not able to run bash command son that server AND it is a custom cloud, so my absolut (and non discussable) highest priority is the safety of the existing customer (users) data. so i am not willing to run some of those commands and "solutions" from others threads like "delete the folder" and hopefully it will be restored with massive cpu load over days ?!

i decreased the preview sizes now, but the folder keeps the size.

is there no official working solution ?!

how can i be, that an app fills the folder with tons of data and then "misses" the management of those folder (the privacy rules and laws completly ignoring) ?

**Comment by snoopy72** [comment]
no support here ?

so i will change to seafile - its also open source, has waorking community support and is for free.

**Comment by kesselb** [comment]
Closing this report because the user migrated to Seafile. If one has the same problem feel free to report a new issue. Using the issue template gives you a better chance that one responds to your issue ;)
