### ISSUE TITLE
Notifications icon 

### ISSUE THREAD

**Issue by CountOmega** [nextcloud/server#22086]
### Expected behaviour
The notifications icon should only be highlighted orange if there is a new notification (e.g. updates)
### Actual behaviour
The notifications icon is highlighted orange even if there is no new notification

### Server configuration

**Operating system:** Ubuntu 18.04

**Web server:** Apache 2.25

**Database:** MariaDB 10.3

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 18.0.7

`{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.178.68:880",
            "192.168.178.68:8443"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "18.0.7.1",
        "overwrite.cli.url": "http:\/\/192.168.178.68:880",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "app_install_overwrite": [
            "printer"
        ],
        "has_rebuilt_cache": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}`
I don´t know if this has been already made an issue.

**Comment by kesselb** [comment]
Mind to add a screenshot?

**Comment by CountOmega** [comment]
Here you go:
![c](https://user-images.githubusercontent.com/23419969/89176127-45698300-d589-11ea-8fc2-98d188acef95.PNG)

**Comment by kesselb** [comment]
Mind to click the notification icon and share another screenshot. Just to make sure there is no unread notification and as help to replicate that state.

**Comment by CountOmega** [comment]
![bn](https://user-images.githubusercontent.com/23419969/89205508-22a29300-d5b8-11ea-8416-04979ba894dc.PNG)

**Comment by CountOmega** [comment]
As you can see, the notification box is empty.

**Comment by szaimen** [comment]
I suppose this has to do with asking for notification permissions when logging in -> not a bug but a feature.
