### ISSUE TITLE
Shared File/Directory not visible for original user after occ files:transfer-ownership

### ISSUE THREAD

**Issue by rponline** [nextcloud/server#22114]
situation:

* A User ("Alice") ist Part of a group ("Orga")
* Alice created a directory and shared it with Orga.
* The cloud admin decides to transfer the ownership to a new user "Bob":
  `occ files:transfer-ownership --path="directory" alice bob`

Now comes the bug:
* Alice can't see the directory anymore! Even if she is part of the "Orga" group.
* All other users in the group can see the dirctory.
* Only after Bob removes the share, and recreates it, Alice can see the directory again.

As an admin I tried stuff like ...
`occ maintenance:repair`  
`occ files:scan --all`  
`occ files:cleanup`  
... but this didn't change anything.

Tested with:
nextcloud 18.0.7

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by rponline** [comment]
I tested it right now on a fresh NC21.0.2 and it seems to work!

Closing :)
