### ISSUE TITLE
Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#22119]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Reboot Server
2.
3.

### Expected behaviour
Not get this error

### Actual behaviour
Everytime i reboot the server i get this error then never comes back again until i reboot it again but nextcloud is working

### Server configuration

**Operating system:**
Ubuntu Server 20.04.1 LTS
**Web server:**
Server version: Apache/2.4.43
**Database:**
mysql  Ver 8.0.21 for Linux on x86_64 (MySQL Community Server - GPL)
**PHP version:**
PHP 7.4.8 (cli) (built: Jul 13 2020 16:46:22) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
19.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Yes
**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

*CONFIG = array (
  'instanceid' => '',
  'passwordsalt' => ',
  'secret' => '',
  'trusted_domains' => 
  array (
    0 => '',
    1 => '',
  ),
  'datadirectory' => '/var/data',
  'dbtype' => 'mysql',
  'version' => '19.0.1.1',
  'overwrite.cli.url' => '',
  'dbname' => '',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '',
  'dbpassword' => '',
  'installed' => true,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'maintenance' => false,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'ldapUserCleanupInterval' => 21,
  'updater.release.channel' => 'stable',
  'theme' => '',
  'loglevel' => 2,
  'app_install_overwrite' => 
  array (
    0 => 'twofactor_yubikey',
    1 => 'external',
    2 => 'breezedark',
  ),
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' => 
  array (
  ),
  'twofactor_enforced_excluded_groups' => 
  array (
  ),
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_smtphost' => '',
  'mail_smtpport' => '25',
  'mail_from_address' => '',
  'mail_domain' => '',
  'skeletondirectory' => '',
  'trashbin_retention_obligation' => 'auto, 30',
);

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>

rror | core | Doctrine\DBAL\DBALException: Failed to connect to the database: An exception occurred in driver: SQLSTATE[HY000] [2002] No such file or directory |  
-- | -- | -- | --

<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by acsfer** [comment]
At the same time you get the error, can you connect to the database with `mysql -u USERNAME -p`?
This is most likely a server/DB configuration problem, not a bug. https://help.nextcloud.com

**Comment by axheli** [comment]
@acsfer  Yes i can connect to the database with no issues

**Comment by axheli** [comment]
Found out the issue apache2 was starting before mysql and thats what i got that error 

After=mysql.service network.target remote-fs.target nss-lookup.target

added above comment to "/lib/systemd/system/apache2@.service" & "/lib/systemd/system/apache2.service" 

rebooted the server now mysql start before apache2

**Comment by p6002** [comment]
> Found out the issue apache2 was starting before mysql and thats what i got that error
> 
> After=mysql.service network.target remote-fs.target nss-lookup.target
> 
> added above comment to "/lib/systemd/system/apache2@.service" & "/lib/systemd/system/apache2.service"
> 
> rebooted the server now mysql start before apache2

how to do this?

**Comment by axheli** [comment]
sudo nano /lib/systemd/system/apache2@.service
sudo nano /lib/systemd/system/apache2.service

Then find the line After=mysql.service network.target remote-fs.target nss-lookup.targe it's not going to have the mysql.server in the line so id recommend copying this line save it on both files and reboot the server and see if you get the error in the logs.

**Comment by wookie73** [comment]
@axheli 
Thanks that seemed to work for me
