### ISSUE TITLE
External SMB not working v19.0.1

### ISSUE THREAD

**Issue by Sx3** [nextcloud/server#22113]
We are using Nextcloud version 19.0.1 on Ubuntu 20.04
We have mapped an external share inside the Ubuntu VM successfully But the External Mapping on the app is not working
it shows the following error.  

**Icewind\SMB\Exception\ConnectionException: Connection not valid**

also tried the solution https://help.nextcloud.com/t/cifs-smb-external-storage-stopped-working-version-17-0-1/64635
but no luck. any help would be appreciated

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
