### ISSUE TITLE
Integrated mail viewer for system mails

### ISSUE THREAD

**Issue by mammutserver** [nextcloud/server#22123]
I'd like to have an integrated mail viewer to view all mails for my account sent by the server. This also should include mails from shared folders or file which I shared by mail.

**Comment by j-ed** [comment]
Such function already exists as a separate app. Install the [mail app](https://apps.nextcloud.com/apps/mail) and you will be able to access your mailbox. BTW, a dedicated [Nextcloud help forum](https://help.nextcloud.com/latest) exists, to address general questions  😉

**Comment by szaimen** [comment]
Please use the mail app for this. Thanks!
