### ISSUE TITLE
admin_audit: Random loss in filesystem signals, read, preview, create

### ISSUE THREAD

**Issue by UralZima** [nextcloud/server#22126]
Hi. I am writing a module for nextcloud for files access statistics report. 
I am registering signals with:
Util::connectHook(Filesystem::CLASSNAME, Filesystem::signal_read, $this, 'repread');
and for preview eventdispatcher for IPreview::EVENT
The code I copied from admin_audit module. This bug affects admin_audit module also.
Sometimes we lose 'create' signals. 
For accessing text files, sometimes both preview and read events triggered, sometimes none of them.
Please help fix this issue

### Steps to reproduce
1. Access some text files, photos, upload
2. Look into admin_audit log
3. Find lost entries

### Expected behaviour
All access and create signals must be triggered

### Actual behaviour
random loss in signal triggering, log entries

### Server configuration
**Operating system: Ubuntu 20.04
**Web server: apache2
**Database: mysql
**PHP version:7.4
**Nextcloud version: 19.0.1
**Where did you install Nextcloud from: T&M Hansson's Virtual Machine

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
