### ISSUE TITLE
horizontal multiple tabs function

### ISSUE THREAD

**Issue by karthikindia** [nextcloud/server#22125]
I am thinking of multiple tabs inside the application instead to opening multiple browser tabs
any one can help me on this.
https://pix.cobrasoftwares.org/image/vXzU
https://pix.cobrasoftwares.org/image/vKJn
https://pix.cobrasoftwares.org/image/vW4f

**Comment by kesselb** [comment]
cc @nextcloud/designers I think that has been discussed before. Any one of you remember the issue?

**Comment by skjnldsv** [comment]
I think it was discussed verbally, but not written.
This is something that is super complicated to do

**Comment by raimund-schluessler** [comment]
I think I don't get it. What is the benefit of this compared to just having multiple browser tabs?

**Comment by jancborchardt** [comment]
What you show in the first picture:
![image](https://user-images.githubusercontent.com/925062/89527104-15201f80-d7e9-11ea-823c-a7a6836f02f2.png)

Is literally the default Nextcloud experience with the app icons directly shown:
![image](https://user-images.githubusercontent.com/925062/89527154-2c5f0d00-d7e9-11ea-9c4b-ca54cad83e90.png)

You simply need to disable the custom [side menu](https://apps.nextcloud.com/apps/side_menu) app to get back to the default design.

**Comment by karthikindia** [comment]
the current menu system still can serve only one page at a time. can open more than one tabs to serve more pages at a time. e.g(livechat portal(external), email, files page
