### ISSUE TITLE
Provide option for 'direct download' when sharing public link

### ISSUE THREAD

**Issue by bbceg** [nextcloud/server#22132]
**Is your feature request related to a problem? Please describe.**
In order to have a direct download link I have to first get a public link and then manually append '/download'. This is fine as a one-off but not ideal if used regularly.

**Describe the solution you'd like**
It would be great to have the option to copy a link with the '/download' already appended.

Taking this one step further it could optionally be set as the default when sharing public links.

Originally this issue was raised specifically against the desktop client under nextcloud/desktop#2230 where I provided a suggestion as to how it could be included. However it was suggested I raise it here because it should first be implemented in the server to ensure all clients followed a similar UX design.

**Comment by bbceg** [comment]
Based on the response to the other issue (nextcloud/desktop#2230) it seems additional menu options are not desirable due to the number already present. Preempting the same response here, I thought I'd offer a couple of alternatives:

1. It doesn't have to be an additional option in the menu, it could be a different "copy download link" button
2. You could allow the user to configure the menu options available at the server (or user profile) level. This would allow users to unclutter the menu when they didn't need all of the options (I appreciate this raises the complexity somewhat)
3. A more basic alternative suggested above as an extension of the original request (but that could be implemented instead without the need for a menu item) would be to provide a setting that allowed the user to make _all_ public links 'download' links

Just to describe the use case in a bit more detail in case it helps...

I wish to send a link (via email) to external users (usually clients) to allow them to review a PDF file in whatever PDF viewer they are accustomed to using and then reply to my original email with feedback. I don't want to have to explain to click the download button or have them click more buttons than necessary. I appreciate this misses the point of the collaboration tools but I have yet to be convinced that these are a better alternative to our current way of working.

**Comment by szaimen** [comment]
Hello, please add your requirement to the discussion in #26691 if not already present. Thanks!
