### ISSUE TITLE
NC could not automatically change data directory after modified the config.php

### ISSUE THREAD

**Issue by ZehuanZhang** [nextcloud/server#22141]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. An installed nextcloud (not pure installation, it already has many users, data and applications).
2. Moving the data directory by following commands:
```
systemctl stop httpd
cd path/to/nextcloud
php occ maintenance:mode --on
cd path/to/old/data/directory
mv * .* path/to/new/data/directory
cd path/to/nextcloud
php occ maintenance:mode --off
systemctl start httpd
```

### Expected behaviour
The expected behavior is NC working as normal and would not throw any exceptions.

### Actual behaviour
The actual behavior is NC throws an Internal Error in the web interface.

### Server configuration

**Operating system:** CentOS 7.8.2003

**Web server:** Apahce 2.4

**Database:** mysql 5.7.31

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 19.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** from older NC

**Where did you install Nextcloud from:** personal data storage (also for family members)

**Signing status:**
<details>
<summary>Signing status</summary>

** I have changed the datadirectory to the old path so there are no error **

No errors have been found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - apporder: 0.10.0
  - audioplayer: 2.11.2
  - bookmarks: 3.2.4
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - camerarawpreviews: 0.7.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - drawio: 0.9.7
  - event_update_notification: 1.0.2
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_markdown: 2.3.0
  - files_mindmap: 0.0.22
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - ocdownloader: 1.7.8
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - qownnotesapi: 20.1.0
  - quota_warning: 1.8.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sharingpath: 0.2.5
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - video_converter: 0.1.4
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - checksum
  - data_request
  - dicomviewer
  - encryption
  - files_readmemd
  - metadata
  - ransomware_detection
  - support
  - unsplash
  - user_ldap
  - w2g2
  - workflow_pdf_converter
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

{
    "system": {
        "default_language": "zh_CN",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
           ********** REMOVED ***********
        ],
        "skeletondirectory": "\/home\/www-data\/ServerData\/nextcloud_skeleton",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "***REMOVED***",
        "htaccess.RewriteBase": "\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "data-fingerprint": "63de176b8a61716b79f61569d1556a90",
        "app_install_overwrite": [
            "bookmarks_fulltextsearch",
            "drawio"
        ]
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>
** sorry, I'm confused that what different between server log and data/log, and where can i find the server log? Is it the apache log ?**
```
Apache error log is empty (i am sure the access log and error log has been configured in apache)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"Xy1T8bCt2SKzfvexjT8QAgAAAAU","level":3,"time":"2020-08-07T13:15:29+00:00","remoteAddr":"192.168.100.94","user":"admin","app":"core","method":"GET","url":"/csrftoken","message":{"Exception":"RuntimeException","Message":"Could not get appdata folder for js","Code":0,"Trace":[{"file":"/home/www-data/ServerData/nextcloud/lib/private/Files/AppData/AppData.php","line":157,"function":"getAppDataFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":[]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Template/JSCombiner.php","line":100,"function":"newFolder","class":"OC\\Files\\AppData\\AppData","type":"->","args":["core"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Template/JSResourceLocator.php","line":116,"function":"process","class":"OC\\Template\\JSCombiner","type":"->","args":["/home/www-data/ServerData/nextcloud","core/js/merged-template-prepend.json","core"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Template/JSResourceLocator.php","line":72,"function":"cacheAndAppendCombineJsonIfExist","class":"OC\\Template\\JSResourceLocator","type":"->","args":["/home/www-data/ServerData/nextcloud","core/js/merged-template-prepend.json"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Template/ResourceLocator.php","line":79,"function":"doFind","class":"OC\\Template\\JSResourceLocator","type":"->","args":["js/merged-template-prepend"]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/TemplateLayout.php","line":344,"function":"find","class":"OC\\Template\\ResourceLocator","type":"->","args":[["core/js/dist/main","js/merged-template-prepend","search/js/search","core/l10n/en","search/l10n/en","search/js/searchprovider","js/files/fileinfo","js/files/client","js/dist/maintenance"]]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/TemplateLayout.php","line":173,"function":"findJavascriptFiles","class":"OC\\TemplateLayout","type":"::","args":[["core/js/dist/main","js/merged-template-prepend","search/js/search","core/l10n/en","search/l10n/en","search/js/searchprovider","js/files/fileinfo","js/files/client","js/dist/maintenance"]]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/legacy/OC_Template.php","line":185,"function":"__construct","class":"OC\\TemplateLayout","type":"->","args":["error",""]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/Template/Base.php","line":132,"function":"fetchPage","class":"OC_Template","type":"->","args":[]},{"file":"/home/www-data/ServerData/nextcloud/lib/private/legacy/OC_Template.php","line":334,"function":"printPage","class":"OC\\Template\\Base","type":"->","args":[]},{"file":"/home/www-data/ServerData/nextcloud/index.php","line":63,"function":"printExceptionErrorPage","class":"OC_Template","type":"::","args":[{"__class__":"RuntimeException"},500]}],"File":"/home/www-data/ServerData/nextcloud/lib/private/Files/AppData/AppData.php","Line":118,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36","version":"19.0.1.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Here you go: https://help.nextcloud.com/t/howto-change-move-data-directory-after-installation/17170

**Comment by ZehuanZhang** [comment]
Thanks for your reply, this problem is solved.
