### ISSUE TITLE
Colorpicker manual color specification (#RRGGBB [hex] or RR,GG,BB [decimal])

### ISSUE THREAD

**Issue by Schebang** [nextcloud/server#22158]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'd like to specify colors more precisely, based on color codes and that's not possible with the current colorpicker.

**Describe the solution you'd like**
I'd like to have an option to specify the color as an RGB value (hexadecimal or decimal, like #FFFFFF or 255,255,255). A simple textbox or three separate ones would suffice.

**Describe alternatives you've considered**
Using sliders for the individual colors.

**Comment by skjnldsv** [comment]
Hi,
What use do you have for this?
Are you maintaining/creating an app and using our vue components?

**Comment by Schebang** [comment]
Hi,
I would like to use it when adding events to the calendar or adding a card to deck.
I'm just a normal user who would like to choose the colors for my events/cards more precisely :)

**Comment by skjnldsv** [comment]
So I'm not sure I follow correctly, you are requesting a feature as a developer or as a user?

**Comment by Schebang** [comment]
I'm requesting this feature as a user

**Comment by skjnldsv** [comment]
@jancborchardt 
Probably for the vue components, but still :)
