### ISSUE TITLE
Webauthn nx 19 it logs in but then asks me for the second factor between totp and u2f or recovery code

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#22154]
@rullzer 

I have correctly configured my yubico 5 Nfc in nextcloud 19 but I noticed that at login it turns on asking me for one of the 2 authentication factors between totp / u2f or recovery code.  I ask myself: should I not enter directly with fido2 without being asked for totp or other factors?  it would make more sense.  otherwise what is fido2?  or is there something I have to do?

in practice I log in with fido2 like this:

![Screenshot_20200808-180206](https://user-images.githubusercontent.com/35575744/89714770-77bc1b80-d9a1-11ea-958f-2cee199c6e7f.png)

and so:

![Screenshot_20200808-180213](https://user-images.githubusercontent.com/35575744/89714786-8c98af00-d9a1-11ea-886e-e64b215123d2.png)

now instead of logging in it asks me totp or u2f why?

![Screenshot_20200808-180225](https://user-images.githubusercontent.com/35575744/89714796-a33f0600-d9a1-11ea-81d8-e273c24f2843.png)

**Comment by rullzer** [comment]
Yes this is expected. Right now in Nextcloud webauthn replaces your password. Not your second factor. This is still something we'd like to do. But not something that is there right now.

**Comment by tigernero79** [comment]
@rullzer 
But in this way I don't have dark according to factor and I do more steps. 
1) Click on Sign with Device 
2) Enter User 
3) Click on Log in 
4) Use according to authentication factor (a senseless thing for me if I use Fido2) while if I don't use Fido2 I do 3 steps. 

It is assumed as in Outlook that trusts 2 can give you access without using other authentication. Also if I remove U2F and TOTP there is always backup code as a request. 
How do I deactivate the recovery codes so Fido2 should not ask for anything else 9 am I wrong?

**Comment by tigernero79** [comment]
maybe as Outlook webauthn / fido2 you can use fido2 PIN and touch Key to verify 2 factors or for NFC the Key is approached to the mobile and stop as I already do for Outlook mail both on desktop and mobile.

**Comment by tigernero79** [comment]
https://github.com/nextcloud/server/issues/21215

**Comment by tigernero79** [comment]
I have a very good understanding of using fido2 for SSH access, as well as using yubico 5 Nfc fido 2 token in using openpgp.  for web credit 2 access the yubico has 25 slots available to store login credentials, which can currently be Outlook accounts, or ssh fido2 credentials, other uses of fido2 do not store anything in one of the 25 slots, when configured as nextcloud access fido2  and this is not clear to me.  why trust2 like Outlook does it and others don't?  I would like to clarify that from version 5.2.3 of yubico 5 series upwards it is possible to individually delete one of the 25 stored keys, with versions prior to 5.2.3 ai could only reset fido2 by deleting all the keys simultaneously and not individually.

**Comment by tigernero79** [comment]
https://developers.yubico.com/WebAuthn/

**Comment by szaimen** [comment]
Let's track this in https://github.com/nextcloud/server/issues/21215
