### ISSUE TITLE
Save space by storing encrypted files in raw binary, not in base64

### ISSUE THREAD

**Issue by jivanpal** [nextcloud/server#22156]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Enabling server-side encryption (encryption at rest) results in a 35% increase in disk usage

**Describe the solution you'd like**
This is a documented consequence of encrypted data being base64-encoded. Is it feasible to not do so, storing encrypted files on disk in raw binary format? Are there any noteworthy design choices or implementation details that make it troublesome to do this?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Pingger** [comment]
The Main-Issue I can see is, that many nextcloud instances are using the base64 encoded format. If this was to change, either (the endpoints would need to distinguish between base64 and binary) or (the server would have convert all stored files from base64 to binary). A third option would be using a config setting, that can only be applied upon enabling of Encryption, that forces to choose between base64 or binary and that would be default to base64 for "old" instances of nextcloud.

**Comment by jivanpal** [comment]
@Pingger, IMO, transitioning existing setups is another issue, but solved easily enough. I envision an option (potentially hidden from frontend) to use binary rather than base64, making it the default on new installations. A flag in file metadata (database or secondary object storage) could be used to signify whether a given encrypted file is stored raw or in base64, and if that flag isn't present (such as in existing installations), then assume base64. When the setting is toggled (such as when an existing installation is upgraded and/or an admin opts in), then the encoding of all files can be transitioned in a rolling fashion so that uptime is not affected.

**Comment by kesselb** [comment]
Some additional reading:
https://github.com/owncloud/core/issues/10831
https://security.stackexchange.com/questions/117068/why-would-an-encrypted-file-be-35-larger-than-an-unencrypted-one

**Comment by szaimen** [comment]
cc @nextcloud/security is this feasible?

**Comment by LukasReschke** [comment]
Yes. Feasible. But a matter of someone doing this. ownCloud added this for example in https://github.com/owncloud/encryption/pull/224, the code should be similarish enough to take inspiration from there.

**Comment by jivanpal** [comment]
@LukasReschke , thanks for your feedback. Are you a member of the security/encryption team (if one exists)? Is there a roadmap of what security-related features are currently being attended to?
