### ISSUE TITLE
Gridview - Album titles to small 

### ISSUE THREAD

**Issue by Gomez** [nextcloud/server#22165]
We have the case that the titles in the album/grid view are a way to small.  Any plan to give them more space? What would be a good way?

@jancborchardt 

![2020-08-10_08-34](https://user-images.githubusercontent.com/48724/89757405-6e3bcc00-dae5-11ea-8f57-85d1a05874c6.png)

**Comment by zsbolyoczki** [comment]
It would be nice to have long filenames shown in multiple lines in grid view.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
