### ISSUE TITLE
AVIF Support

### ISSUE THREAD

**Issue by 1div0** [nextcloud/server#22166]
New AV1 based image format is already gaining support in recent browser, such as Firefox 78+ (with image.avif.enabled = true in about:config) and upcoming Google Chrome 85 (as indicated by image/avif in the following string from the request header).

Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9

It would be really nice to proactively add support for AVIF in the Nextcloud as well. It is fast, efficient and nice. Pick any three.

Please check:
https://photo.reflexion.tv/AVIF/

**Comment by 1div0** [comment]
So, Cr 85 is already available.

**Comment by 1div0** [comment]
Also, Vivaldi is already partially supporting the AVIF.

**Comment by 1div0** [comment]
Brave as well.

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/13552
