### ISSUE TITLE
Update 17->18 Fail!  How to get back?

### ISSUE THREAD

**Issue by WernerBleisteiner** [nextcloud/server#22160]
Tried now to update my server from 17 to 18 with the web updater. This all worked fine, but then....

See  below
Aaargh!
How can I revert now?
I feel really pissed!
w
----
Nextcloud
Aktualisierung auf 18.0.7

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_flow_operations` SET `entity` = ? WHERE `entity` = ''' with params ["OCA\\WorkflowEngine\\Entity\\File"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'where clause'
Detaillierte Protokollmeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Migrate old user config
[1 / 0]: Migrate old user config
[2 / 0]: Migrate old user config
[3 / 0]: Migrate old user config
[4 / 0]: Migrate old user config
[5 / 0]: Migrate old user config
[6 / 0]: Migrate old user config
[7 / 0]: Migrate old user config
[8 / 0]: Migrate old user config
[8 / 8]: Migrate old user config
"accessibility" aktualisiert auf 1.4.0
"federatedfilesharing" aktualisiert auf 1.8.0
"files_pdfviewer" aktualisiert auf 1.7.0
"files_rightclick" aktualisiert auf 0.15.2
"files_videoplayer" aktualisiert auf 1.7.0
"logreader" aktualisiert auf 2.3.0
"password_policy" aktualisiert auf 1.8.0
"privacy" aktualisiert auf 1.2.0
"provisioning_api" aktualisiert auf 1.8.0
"recommendations" aktualisiert auf 0.6.0
"serverinfo" aktualisiert auf 1.8.0
Reparaturschritt: Switches from default updater server to the customer one if a valid subscription is available
Reparaturinformation: Repair step already executed
"support" aktualisiert auf 1.1.1
"survey_client" aktualisiert auf 1.6.0
"text" aktualisiert auf 2.0.0
Reparaturschritt: Add background job to check for backup codes
"twofactor_backupcodes" aktualisiert auf 1.7.0
"updatenotification" aktualisiert auf 1.8.0
"federation" aktualisiert auf 1.8.0
"lookup_server_connector" aktualisiert auf 1.6.0
Reparaturschritt: Update OAuth token expiration times
"oauth2" aktualisiert auf 1.6.0
"files" aktualisiert auf 1.13.1
"activity" aktualisiert auf 2.11.0
"cloud_federation_api" aktualisiert auf 1.1.0
Reparaturschritt: Fix component of birthday calendars
Reparaturinformation: 1 birthday calendars updated.
Reparaturschritt: Regenerating birthday calendars to use new icons and fix old birthday events without year
Reparaturinformation: Repair step already executed
Reparaturschritt: Fix broken values of calendar objects
[0 / 0]: Fix broken values of calendar objects
Reparaturschritt: Registering building of calendar search index as background job
Reparaturinformation: Repair step already executed
Reparaturschritt: Registering background jobs to update cache for webcal calendars
Reparaturinformation: Added 0 background jobs to update webcal calendars
Reparaturschritt: Registering building of calendar reminder index as background job
Reparaturinformation: Repair step already executed
Reparaturschritt: Clean up orphan event and contact data
Reparaturinformation: 0 events without a calendar have been cleaned up
Reparaturinformation: 0 properties without an events have been cleaned up
Reparaturinformation: 0 changes without a calendar have been cleaned up
Reparaturinformation: 0 cached events without a calendar subscription have been cleaned up
Reparaturinformation: 0 changes without a calendar subscription have been cleaned up
Reparaturinformation: 0 contacts without an addressbook have been cleaned up
Reparaturinformation: 0 properties without a contact have been cleaned up
Reparaturinformation: 0 changes without an addressbook have been cleaned up
Reparaturschritt: Remove activity entries of private events
Reparaturinformation: Removed 0 activity entries
"dav" aktualisiert auf 1.14.0
Reparaturschritt: Fix the share type of guest shares when migrating from ownCloud
Reparaturschritt: Copy the share password into the dedicated column
Reparaturschritt: Set existing shares as accepted
"files_sharing" aktualisiert auf 1.10.1
"files_trashbin" aktualisiert auf 1.8.0
"files_versions" aktualisiert auf 1.11.0
"sharebymail" aktualisiert auf 1.8.0
Reparaturschritt: Populating added database structures for workflows
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_flow_operations` SET `entity` = ? WHERE `entity` = ''' with params ["OCA\\WorkflowEngine\\Entity\\File"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'where clause'
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

Aktualisierung auf 18.0.7

Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_flow_operations` SET `entity` = ? WHERE `entity` = ''' with params ["OCA\\WorkflowEngine\\Entity\\File"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'where clause'
Detaillierte Protokollmeldungen
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
Reparaturschritt: Populating added database structures for workflows
Doctrine\DBAL\Exception\InvalidFieldNameException: An exception occurred while executing 'UPDATE `oc_flow_operations` SET `entity` = ? WHERE `entity` = ''' with params ["OCA\\WorkflowEngine\\Entity\\File"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'entity' in 'where clause'
Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

**Comment by Dragon988** [comment]
Restore from the backup you took prior to the upgrade or the last working backup you have.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

> How to get back

Please visit https://help.nextcloud.com for such questions. It depends on your setup.

> Column not found: 1054 Unknown column 'entity' in 'where clause'

https://github.com/nextcloud/server/issues/18265
https://help.nextcloud.com/t/read-this-before-you-update-to-nextcloud-18/68389

**Comment by WernerBleisteiner** [comment]
Thanks. 
Was able to revert to the hosted backup.

However, concerning he quoted
[https://help.nextcloud.com/t/read-this-before-you-update-to-nextcloud-18/68389](https://help.nextcloud.com/t/read-this-before-you-update-to-nextcloud-18/68389)

I attempted to execute the proposed web-based update from 17.0.8 to 18.0.7 on a 'stable' channel.
Therefore I wouldn't expect such serious issues or even having to work manually.

Using NC now for quite a while, this is the first time these kind of inconveniences arise. 

Is this to be fixed later?
Or will I have really to upgrade to NC 18 manually?
