### ISSUE TITLE
[19.0.1] Preview images are generated sideways

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#22163]
More then 50% of my pictures taken on my phone appear sideways in the android nextcloud app and on the web GUI of nextcloud 19.0.1.

Direct downloading the file and opening in an external application has the file in the correct orientation.

This issue occurs on both the thumbnail and the main preview image.

### Steps to reproduce

Upload photos with an android 10 phone.

### Expected behaviour

Image in the correct orientation.

### Actual behaviour

Image rotated sideways.

### Server configuration

**Operating system:**
Arch

**Web server:**
Nginx

**Database:**
Postgresql

**PHP version:**
7.4.9

**Nextcloud version:** (see Nextcloud admin page)
19.0.1

**Are you using external storage, if yes which one:** local/smb/sftp/...

No

**Are you using encryption:** yes/no

No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No

**Comment by kesselb** [comment]
Looks like a duplicate of https://github.com/nextcloud/server/issues/21418? :thinking:

**Comment by Dragon988** [comment]
Huh, thought I closed that one. My bad. :/
