### ISSUE TITLE
Internal share with different name

### ISSUE THREAD

**Issue by adi-dev** [nextcloud/server#22194]
I have instance with few users. I noticed that we have similar folder structure. In my opinion, it would be a good idea, if the share I want to create with others on server could have given name at the start. I know, it can be changed later but not everyone here is technical and my users ending up with two folders with the same name - one of their own and second one as incoming share.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
