### ISSUE TITLE
SCHEDULE-AGENT:X-name/NONE - RFC6638 Section-7.1 support

### ISSUE THREAD

**Issue by SergeyMosin** [nextcloud/server#22197]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Event with a ``SCHEDULE-AGENT`` parameter on an ORGANIZER/ATTENDEE is needed. Ex:
```
ORGANIZER;SCHEDULE-AGENT=X-MYAPP:mailto:bernard@example.com
```
2. Move the event in the calendar app.

### Expected behaviour
The "Invitation: ..." email **should not be sent** as per [RFC6638 Section-7.1](https://tools.ietf.org/html/rfc6638#section-7.1) :
```
...
When "NONE" is specified, no scheduling messages are being sent to
the calendar user.
...
Servers and clients MUST treat x-name and iana-token values they
do not recognize the same way as they would the "NONE" value.
```

### Actual behaviour
The "Invitation: ..." **email is sent** regardless of the ``SCHEDULE-AGENT`` parameter value

### Server configuration

All version on all systems are affected.

-------------------
#### Proposed solution
Patch ``apps/dav/lib/CalDAV/Schedule/IMipPlugin.php`` - this only fixes ``SCHEDULE-AGENT:X-name`` but can be extended for ``SCHEDULE-AGENT:NONE``
```
Index: apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- apps/dav/lib/CalDAV/Schedule/IMipPlugin.php	(date 1597160242625)
+++ apps/dav/lib/CalDAV/Schedule/IMipPlugin.php	(date 1597160242625)
@@ -154,6 +154,12 @@
 			return;
 		}
 
+		// @see https://tools.ietf.org/html/rfc6638#section-7.1
+        $organizer=$iTipMessage->message->VEVENT->ORGANIZER;
+		if(isset($organizer->parameters['SCHEDULE-AGENT']) && strpos($organizer->parameters['SCHEDULE-AGENT'],"X-")===0){
+		    return;
+        }
+
 		$summary = $iTipMessage->message->VEVENT->SUMMARY;
 
 		if (parse_url($iTipMessage->sender, PHP_URL_SCHEME) !== 'mailto') {

```

**Comment by kesselb** [comment]
cc @nextcloud/calendar

**Comment by georgehrke** [comment]
@SergeyMosin This seems to be an upstream issue in http://github.com/sabre-io/dav, no?

**Comment by SergeyMosin** [comment]
@georgehrke I'll open an issue there as well, thanks.

**Comment by SergeyMosin** [comment]
Is there any other way to stop the scheduling/IMipPluging from sending emails on certain events ?

**Comment by georgehrke** [comment]
Not that i'm aware of.

**Comment by SergeyMosin** [comment]
Upstream issue is open at: https://github.com/sabre-io/dav/issues/1293
