### ISSUE TITLE
CSS - Themeing / Skinning

### ISSUE THREAD

**Issue by blackcrack** [nextcloud/server#222]
Have today playing around an bit with theming
for my next theme neXtrealTime

### Steps to reproduce
1. Create a new theme and change colors
part for part ..(and you see, there be many where have to clean up..)
2. add other webfonts ttf/woff/etc.
3. the apps have no standard like font-size and colloring so on,

### Expected behaviour
Tell us what should happen
it should give a standard, what be explicit theme/s in the 
styles.css , font-family:arial; (or an OFT and this as woff,woff2,eot,svg and ttf) 
to be able for setting clean up which font for which element used.
and not easy 100% or something, no, should be set up in pixel (px)
to be in able for setting up an hard font-size:; like 12,17 or something in pixels

### Actual behaviour
Tell us what happens instead:
wrong size's of fonts on different Apps like Mail, calendar and so on
it only strikes, if change the colors and size of the Font, 
so if create an other theme with own colors and font-size .

this must be fixed and at all, size and colouring do with css and not 
with java or directly in the code. Because change to be right, 
if you be a javaprogrammer it's easy, there you can iron out the 
mistakes loose, but it strikes, if you try to create different themes 
as non java programmer .

### Server configuration
**Operating system**:
Openmandriva 2014 
W7

**Web server:**
blackysgate.net/phpinfo.php

**Database:**
Mariadb

**PHP version:**
blackysgate.net/phpinfo.php

**Nextcloud version:** (see Nextcloud admin page)
9.0.51

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Where did you install Nextcloud from:**
https://nextcloud.com/install/#instructions-server
tar.bz2

**Signing status (Nextcloud 9.0 and above):**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**
Enabled:
  - activity: 2.2.1
  - admin_audit: 1.0.0
  - bookmarks: 0.7
  - calendar: 1.2.2
  - comments: 0.2
  - contacts: 1.3.1.0
  - dav: 0.1.6
  - direct_menu: 0.8.0
  - documents: 0.12.0
  - federatedfilesharing: 0.1.0
  - federation: 0.0.4
  - files: 1.4.4
  - files_external: 0.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 0.9.1
  - files_texteditor: 2.1
  - files_trashbin: 0.8.0
  - files_versions: 1.2.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 14.5.0
  - mail: 0.5.2
  - music: 0.3.11
  - notifications: 0.2.3
  - provisioning_api: 0.4.1
  - systemtags: 0.2
  - templateeditor: 0.1
  - updatenotification: 0.1.0
Disabled:
  - encryption
  - external
  - files_mv
  - user_external
  - user_ldap

**The content of config/config.php:**
not need

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
hehehe


### Client configuration
**Browser:**
Linux actual Firefox
Windows actual Firefox

**Operating system:**

Win7
OpenMandriva

**Comment by jospoortvliet** [comment]
I guess we'll have to hunt down each inconsistency separately. Many are/will be in apps. If you want to help with that, it'd be great... File a bug for each of the separate problems you found in the right app repository!

**Comment by jancborchardt** [comment]
Not entirely sure what you mean. Because we do have standards. There are buidling blocks for apps as described in the documentation: https://docs.nextcloud.com/server/9/developer_manual/app/css.html?highlight=css#standard-layout

And these are used by the main apps already. The font is always Open Sans Light, which is also used consistently. Same for the colors, which are all defined either by the theme, or the apps.css.
