### ISSUE TITLE
App navigation design issues

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22219]
Apps might have a name that is too long to fit the 50px space that is available in the app menu (this is usually an issue with translations):

![image](https://user-images.githubusercontent.com/3404133/90012730-3f1f8900-dca4-11ea-9d4b-4b4b8955208a.png)

Just adjusting the width to fit doesn't work properly since this would mean that the app icons change position on hover:

![Peek 2020-08-12 14-02](https://user-images.githubusercontent.com/3404133/90012877-80b03400-dca4-11ea-8275-a860ab0ebcf0.gif)

I discussed this with @jancborchardt already where he proposed a flex layout where the app names would be a separate row of flex items, however this will also not work properly since then we can not detect the hover on the combined icon+text dom elements anymore.

Maybe someone of @nextcloud/designers has an idea how we could solve this in a sane and elegant way.

**Comment by juliushaertl** [comment]
As a sidenote, the background color we had for the label was removed due to the gradient in the header, so we could add this back for plain colors (which is the case with theming) however this will not work with the new dashboard UI (#22143) nor the default Nextcloud blue gradient.

**Comment by YouveGotMeowxy** [comment]
How about just not showing the labels as text under the icons, and just show the icons; then hovering the cursor over the icon will display the standard tooltip with the app's name?

**Comment by jancborchardt** [comment]
> How about just not showing the labels as text under the icons, and just show the icons; then hovering the cursor over the icon will display the standard tooltip with the app's name?

We did this previously, however the issue is that we can only show 1 label at a time that way. The point of showing them all was that people who don’t use Nextcloud _all the time_ know what is what quickly.

**Comment by jancborchardt** [comment]
A solution which would not look _so_ good but be reasonable and fix the issue at hand is to add a background to the app title – as before already and as discussed – and just accept that it will look different on the various backgrounds. We could use the primary color for it to look the least out-of-place, and use `var(--border-radius-pill)` for it to blend nicely?

**Comment by jancborchardt** [comment]
Hm … doesn’t look so good:
![Peek 2020-08-13 14-58](https://user-images.githubusercontent.com/925062/90137145-7f9b0780-dd75-11ea-803b-e023d43e69b0.gif)

> I discussed this with @jancborchardt already where he proposed a flex layout where the app names would be a separate row of flex items, however this will also not work properly since then we can not detect the hover on the combined icon+text dom elements anymore.

Could we not expand the name of the hovered app, and cut the ones left and right accordingly?

**Comment by juliushaertl** [comment]
> Could we not expand the name of the hovered app, and cut the ones left and right accordingly?

At least I didn't find any sane way to do that.

**Comment by STaRDoGG** [comment]
I didn't look at what framework(s) they're using, but what about something like [Hotjar ](https://www.hotjar.com)does?

![capture](https://user-images.githubusercontent.com/1524526/90207584-4336ce00-ddac-11ea-8c6d-cc6978ffe286.gif)

**Comment by juliushaertl** [comment]
@STaRDoGG Let me quote @jancborchardt from earlier here:

> We did this previously, however the issue is that we can only show 1 label at a time that way. The point of showing them all was that people who don’t use Nextcloud all the time know what is what quickly.
