### ISSUE TITLE
UI shows a folder exists, but cline does not?

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/server#22224]
I'm not very familiar with using Linux and have been having a problem with the NC Android app saying that I don't have permission to upload when I have InstantUpload turned on...

After looking at the log for the app, it seemed that one folder in particular was causing the error: "07". (for the month of July).

So I went to look at the folder in the UI and is seemed line there's no problem; it shows the folder and some files in it, however when I look for that folder from the cline (I'm using the NC docker container) it seems to not even _have_ the 07 folder?

Not being a Linux girl I don't really know _why_ this would happen, and more importantly, _how_ to fix it?

![image](https://user-images.githubusercontent.com/39491297/90068714-be1dbd00-dcb6-11ea-8504-c9d624efb4be.png)

Any help greatly appreciated! :)

**Comment by YouveGotMeowxy** [comment]
Well, just to keep this highly active thread updated ... ;)

I tried to move the files in that folder shown in the UI to another folder and got this:

![image](https://user-images.githubusercontent.com/39491297/90109536-9576e100-dd11-11ea-9539-38548c96e636.png)

Then I just deleted them (I don't know if the files actually got deleted, of maybe there were just "pointers" to the files in the db that were deleted) but got no errors there.

Then, I tried to delete the "07" folder itself, and got:

![image](https://user-images.githubusercontent.com/39491297/90109680-c6571600-dd11-11ea-88d8-e7d027308406.png)

I navigated up a folder and refreshed and the 07 folder no longer showed. Went to the Android app and tried to re-send those files that were getting the permissions error, thinking it would just auto-create the 07 folder on the server like the app normally does when it uploads stuff, but the new error was simply "conflict"...

Then I manually created the 07 folder on the server (no problems) and again re-tried in the app, and this time they uploaded.

I have no idea what happened to cause all the strife, but it seems like a regular, probably unsavvy (like myself) user of NC shouldn't have to ever deal with this; like some error checking and resolving should automatically be happening in the background. It's hard to imagine something like this being ok with something like DropBox or Google Drive.

**Comment by szaimen** [comment]
Hi, most likely the internal database and the actual files on your drive got out of sync. In this case you need to rescan the files with `occ files:scan --all` or comparable.

As this seems to be a setup issue I would like to ask you to raise further questions in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
