### ISSUE TITLE
Duplicate email field in personal settings

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2222]
![capture du 2016-11-21 21-37-45](https://cloud.githubusercontent.com/assets/925062/20499675/cc5b5710-b032-11e6-839d-bcf60a0231e3.png)

@schiessle any idea?

Also if I change the email, the checkmark shows in the Name field, not in the email field. cc @nextcloud/javascript @nextcloud/designers

**Comment by LukasReschke** [comment]
@schiessle …

**Comment by LukasReschke** [comment]
PR at https://github.com/nextcloud/server/pull/2251
