### ISSUE TITLE
Visibility switcher of profile picture doesn’t work

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2223]
All the other switchers in the personal settings work, but that one doesn’t. Console error:

```
federationscopemenu.js? line 114 Uncaught TypeError: Cannot read property 'value' of undefined
```

@schiessle @LukasReschke @nextcloud/javascript

**Comment by LukasReschke** [comment]
Please test https://github.com/nextcloud/server/pull/2224
