### ISSUE TITLE
Allow to pause some accounts

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#22238]
We are far beyond the point where uninstalling the app/client is an option, especially in multi profile setups. It should possible to mute notifications from certains profiles easily and revertible. Unluckily on all OS you can only block the apps completely, so we need to implement this, so you can pause your work accounts and still be notified from your private/volunteer/other profiles, without having to delete the accounts/clients all the time and reinstall/setup/sync from scratch again.

One option would be to hook in the user status and allow it to "opt out users of push/popup notifications"

**Comment by nickvergessen** [comment]
Or should this be an option of the user status? Cc @jancborchardt @georgehrke

**Comment by er-vin** [comment]
> Or should this be an option of the user status? Cc @jancborchardt @georgehrke

Yes, was about to point this out. I think it could tie in to the status in some way.

**Comment by nickvergessen** [comment]
Done via nextcloud/server#22424 and https://github.com/nextcloud/notifications/pull/724
