### ISSUE TITLE
Unable to delete or edit file in NTFS external storage if the file has the extended attribute "compress contents to save disk space"

### ISSUE THREAD

**Issue by scanom** [nextcloud/server#22248]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Add a NTFS external storage with some files.
2. Add the extended attribute "compress contents to save disk space" to a file.
3. Refresh the page and open context menu of that file.

### Expected behaviour
The option to delete the file should show up.

### Actual behaviour
There is no option to delete the file, like the file is in _read-only_ mode.

### Server configuration

**Operating system:** Centos 7

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.3 

**Nextcloud version:** Same behavior using nextcloud 18.0.7 and 19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated since 15.0

**Where did you install Nextcloud from:** Official package

**Signing status:**
<details>
<summary>Signing status</summary>

```
Not relevant
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Not relevant
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Not relevant
```
</details>

**Are you using external storage, if yes which one:** NTFS

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
Not relevant
```
</details>

### Client configuration
**Browser:** Tested with Firefox and Chrome and native mobile apps

**Operating system:** Windows, Linux, iOS... same behaviour

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Nothing relevant
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Nothing relevant
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
