### ISSUE TITLE
Polishing - "Adjust the dashboard to your needs" overlays the firstrunwizard

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#22246]
I just noticed that the popup overlaps the firstrunwizard and looks a bit weird.

@juliushaertl Mind to fix this for 20? :)

cc @jancborchardt

**Comment by MorrisJobke** [comment]
![Bildschirmfoto 2020-08-14 um 09 13 34](https://user-images.githubusercontent.com/245432/90223639-b96c1c80-de0e-11ea-832b-b469296dce07.png)

**Comment by jancborchardt** [comment]
Good question on that one – do we have any tooltips in the firstrunwizard @juliushaertl? If not then we should probably just set that z-index to higher (tooltips have a value of 100000)?

**Comment by jancborchardt** [comment]
If we possibly remove this special "first run" handling for the Customize button – which also looks weird on certain screen sizes with the button overlapping, and also introducing quite some noise – this would be fixed as well.

What do you think about just removing that special first run case @MorrisJobke @juliushaertl?

**Comment by juliushaertl** [comment]
Should also be fine. I think with just the default 4 widgets the customize button is also quite well visible so it should be clear that there is something there.
