### ISSUE TITLE
Links with "scrollto" in large folders are very slow

### ISSUE THREAD

**Issue by papst01** [nextcloud/server#22251]
### Steps to reproduce
1. Fill a folder with several 100 or 1000 pictures
2. Use the search function to search for one picture (idealy one which is alphabetically listed pretty much at the end of the folder)
3. The search result will be a link in a form like: https://[Domain]/index.php/apps/files/?dir=/Directory/ToYourPic&scrollto=PictureName.jpg
4. Click on the link and wait a loooong time to get the picture shown

If you open the browser console you see all the pictures scrolling by till the final wanted picture is found

### Expected behaviour
Open the picture within 5 seconds

### Actual behaviour
It lasted 2minutes to load (folder with 2600 pictures (ca. 30GB)) and loaded almost 50MB to the browser, several apache instances were active and allmost used the complete cpu resources.

### Server configuration
J4105 Celeron
12GB RAM
SoftRaid 5 (3 Samsungs SSDs)

**Operating system:**
Ubuntu 18.04.5 LTS 

**Web server:**
Apache 2.4.29

**Database:**
mysql 10.1.44 (DB size 428MB(

**PHP version:**
7.2.24

**Nextcloud version:** 
18.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated (used since version 11 or twelve, originally upgraded from Owncloud)

**Where did you install Nextcloud from:** no memory about it

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.4.0
  - activity: 2.11.0
  - bruteforcesettings: 1.6.0
  - calendar: 2.0.3
  - cloud_federation_api: 1.1.0
  - comments: 1.8.0
  - contacts: 3.3.0
  - dav: 1.14.0
  - documentserver_community: 0.1.7
  - facerecognition: 0.6.1
  - federatedfilesharing: 1.8.0
  - federation: 1.8.0
  - files: 1.13.1
  - files_pdfviewer: 1.7.0
  - files_rightclick: 0.15.2
  - files_sharing: 1.10.1
  - files_trashbin: 1.8.0
  - files_versions: 1.11.0
  - files_videoplayer: 1.7.0
  - firstrunwizard: 2.7.0
  - logreader: 2.3.0
  - lookup_server_connector: 1.6.0
  - maps: 0.1.6
  - notes: 3.6.1
  - notifications: 2.6.0
  - oauth2: 1.6.0
  - onlyoffice: 4.3.0
  - password_policy: 1.8.0
  - photos: 1.0.0
  - previewgenerator: 2.3.0
  - privacy: 1.2.0
  - provisioning_api: 1.8.0
  - ransomware_protection: 1.6.1
  - recommendations: 0.6.0
  - serverinfo: 1.8.0
  - settings: 1.0.0
  - sharebymail: 1.8.0
  - spreed: 8.0.10
  - support: 1.1.1
  - survey_client: 1.6.0
  - systemtags: 1.8.0
  - text: 2.0.0
  - theming: 1.9.0
  - twofactor_backupcodes: 1.7.0
  - twofactor_totp: 4.1.3
  - updatenotification: 1.8.0
  - viewer: 1.2.0
  - workflowengine: 2.0.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "mydomain.tld"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/x.x.x.x",
        "dbtype": "mysql",
        "version": "18.0.7.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "integrity.check.disabled": false,
        "maintenance": false,
        "theme": "",
        "log_type": "owncloud",
        "logfile": "\/var\/log\/nextcloud.log",
        "loglevel": "3",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": "true",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

</details>

### Client configuration
**Browser:**
under Win10: Firefox, Chrome
under Android: Yandex, Chrome

**Operating system:**
Win 10 / Android 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Seems for every file it scrolles by a line get is done (only a small cutout):
My.IP.x.x - - [14/Aug/2020:13:27:53 +0200] "GET /index.php/core/preview?fileId=1528768&c=c14060fc1f89e7abce1a3cb715ffc3c5&x=250&y=250&forceIcon=0 HTTP/1.1" 200 32031 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528773&c=f192cfe00adf3745c2f3266850465c71&x=250&y=250&forceIcon=0 HTTP/1.1" 200 24247 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528771&c=51c40cd52499322f8235b0f09004e749&x=250&y=250&forceIcon=0 HTTP/1.1" 200 32772 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:53 +0200] "GET /index.php/core/preview?fileId=1528769&c=b3505eb698899b81f6859cd21d8fa83c&x=250&y=250&forceIcon=0 HTTP/1.1" 200 34105 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528772&c=448af6e4f7196eead915e54923fceab3&x=250&y=250&forceIcon=0 HTTP/1.1" 200 24774 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528774&c=4bbb8f92e290309938760251a70a4d09&x=250&y=250&forceIcon=0 HTTP/1.1" 200 25428 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528778&c=d428b9d6d279f4d6d7ae6caa98273a66&x=250&y=250&forceIcon=0 HTTP/1.1" 200 31030 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528776&c=5ef2911c96cf423ac9ef38c4725752ab&x=250&y=250&forceIcon=0 HTTP/1.1" 200 27283 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528775&c=22406dbb3d96607b9165645f381514dc&x=250&y=250&forceIcon=0 HTTP/1.1" 200 24148 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
My.IP.x.x - - [14/Aug/2020:13:27:54 +0200] "GET /index.php/core/preview?fileId=1528777&c=6dd84783df33448b429adc176635f477&x=250&y=250&forceIcon=0 HTTP/1.1" 200 24686 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log (no more lines were written while loading the picture/page) </summary>

```
{"reqId":"2ddlSCQeu5KP0bjUg4AI","level":3,"time":"2020-08-14T11:31:32+00:00","remoteAddr":"192.168.178.20","user":"[USER]","app":"PHP","method":"GET","url":"/index.php/core/preview?fileId=1528786&c=62c31afc0dde96f3655706819bc42173&x=250&y=250&forceIcon=0","message":"imagecreatefromstring(): one parameter to a memory allocation multiplication is negative or zero, failing operation gracefully\n at /var/www/html/lib/private/legacy/image.php#621","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"18.0.7.1"}
{"reqId":"2ddlSCQeu5KP0bjUg4AI","level":3,"time":"2020-08-14T11:31:32+00:00","remoteAddr":"192.168.178.20","user":"[USER]","app":"PHP","method":"GET","url":"/index.php/core/preview?fileId=1528786&c=62c31afc0dde96f3655706819bc42173&x=250&y=250&forceIcon=0","message":"imagecreatefromstring(): Passed data is not in 'WBMP' format at /var/www/html/lib/private/legacy/image.php#621","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"18.0.7.1"}
{"reqId":"2ddlSCQeu5KP0bjUg4AI","level":3,"time":"2020-08-14T11:31:32+00:00","remoteAddr":"192.168.178.20","user":"[USER]","app":"PHP","method":"GET","url":"/index.php/core/preview?fileId=1528786&c=62c31afc0dde96f3655706819bc42173&x=250&y=250&forceIcon=0","message":"imagecreatefromstring(): Couldn't create GD Image Stream out of Data at /var/www/html/lib/private/legacy/image.php#621","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:79.0) Gecko/20100101 Firefox/79.0","version":"18.0.7.1"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
![browser_log](https://user-images.githubusercontent.com/6513409/90246005-fe567a00-de33-11ea-96c7-e6d899315221.png)

</details>

**Comment by da-anda** [comment]
I can confirm this running NC20

**Comment by szaimen** [comment]
Hi, do you use the previewgenerator to generate previews beforehand? This should speed up the loading of folders with a large amount of picture by a lot. https://apps.nextcloud.com/apps/previewgenerator

**Comment by jonjomckay** [comment]
This is also happening to me, with a folder containing ~5000 items. The page loads all the layout (but no files listed yet), then hangs for about 100 seconds, pegging a CPU core at 100%.

Looking in the developer tools, the hang happens when making a request to the same WebDAV XML endpoint mentioned above. Making the same call using cURL takes less than a second, so it's definitely something in the Nextcloud frontend being slow, and not to do with the server or preview generation (which I do have enabled regardless). 

I'm also using Firefox 90 on Linux. Happy to help diagnose more if needed - this is a pretty annoying bug!

**Comment by szaimen** [comment]
> preview generation (which I do have enabled regardless)

So previews are already generated beforehand?

**Comment by jonjomckay** [comment]
Yep they are already generated, but the freeze happens before the previews are requested anyway - it freezes when it tries to download/parse the WebDAV response.

**Comment by szaimen** [comment]
okay, thanks for the clarification!

**Comment by jonjomckay** [comment]
Here's a screen recording of the issue, with a test folder I just created with 2000 empty text files in. It's not exactly enthralling viewing, but it should show that nothing really happens until 1:20 in!

https://user-images.githubusercontent.com/456645/122403070-f694c400-cf75-11eb-822b-89e2ae5abf82.mp4

**Comment by FernandoMarques-Santos** [comment]
Nextcloud Hub II (23.0.5)
Ubuntu Focal Fossa
PHP8.0

The issue still persists and it's a problem when accessing pictures through the face-recognition app. Did anyone solve this?

**Comment by germainm** [comment]
It would be cool to get option to disable the scrollto

normal search open automatically the file (pdf for me) BUT a background scrollto is used (can see in the URL) and sometimes I can't scroll the document (pdf in my case) until it ends. Need to wait the background scrollto to end. Another symptom is that I can't close the document if the scrollto is not done processing

elastic search still doesn't automatically open the file. it opens the directory and use scrollto to show the file.

so, a feacture to disable scrollto would be greatly appreciated ( or optimization is really needed 5-10x speed would be probably OK for 5000 files directory )

It's really annoying and hang browser and there's nothing about unoptimized server (my vm has 32 gb, I setup redis, increased elastic memory, given more memory to php process)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by germainm** [comment]
yep, still on issue on nextcloud 25.0.2.

**Comment by skjnldsv** [comment]
fixed on 28+
