### ISSUE TITLE
file_put_contents() uses "false" to indicate failure

### ISSUE THREAD

**Issue by guettli** [nextcloud/server#22258]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I get a `GenericFileException('file_put_contents failed')` and now I try to find the root cause.

I am looking at this code:

```
if ($this->view->file_put_contents($this->path, $data) === false) {
    throw new GenericFileException('file_put_contents failed');
}
```
Source: https://github.com/nextcloud/server/blob/master/lib/private/Files/Node/File.php#L72

**Describe the solution you'd like**

I guess the current API of `file_puts_contents()` is that it does not throw an exception
and returns `false` on error.

This pattern in is common in the language C, but since PHP supports exceptions,
it might make more sense to throw the exception where it occurs.

In above code snippet the root cause gets lost and a meaningless error message gets 
created.

**Describe alternatives you've considered**

`file_puts_contents()` should raise an exception with a meaningful message.

Related: [my personal guidelines](https://github.com/guettli/programming-guidelines/blob/master/README.md#false-means-failure-the-root-cause-is-gone)

**Comment by szaimen** [comment]
Hello, would you be able to create a PR with your findings? Thank you!
