### ISSUE TITLE
Create IObjectStore for SMB

### ISSUE THREAD

**Issue by kallibr44** [nextcloud/server#22267]
As i can understand, now impossible to set Samba as primary external storage instead of internal. I'm tried to make myself IObjectStore class for SMB, but it was unsuccessful :( So please, can you create this class for Samba?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
