### ISSUE TITLE
Update fail from Nextcloud 18.X to 19.X Mail app

### ISSUE THREAD

**Issue by ThomasH13090** [nextcloud/server#22269]
Hello, I got this error after trying to update my nextcloud server. Anyone having the same issue? 

Thanks ahead

_Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_mail_mailboxes DROP sync_token': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes_

**Comment by PatrickCronin** [comment]
I got this same issue when updating Nextcloud from the browser from 16.X to 17.0.10:

```
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Updated "accessibility" to 1.3.0

Updated "federatedfilesharing" to 1.7.0

Updated "files_pdfviewer" to 1.6.0

Updated "files_rightclick" to 0.14.2

Updated "files_videoplayer" to 1.6.0

Updated "gallery" to 18.4.0

Updated "logreader" to 2.2.0

Updated "password_policy" to 1.7.0

Updated "privacy" to 1.1.0

Updated "provisioning_api" to 1.7.0

Updated "recommendations" to 0.5.0

Updated "serverinfo" to 1.7.0

Repair step: Switches from default updater server to the customer one if a valid subscription is available

Updated "support" to 1.0.2

Updated "survey_client" to 1.5.0

Repair step: Add background job to check for backup codes

Updated "twofactor_backupcodes" to 1.6.0

Updated "updatenotification" to 1.7.0

Updated "federation" to 1.7.0

Updated "lookup_server_connector" to 1.5.0

Repair step: Update OAuth token expiration times

Updated "oauth2" to 1.5.0

Updated "files" to 1.12.0

Updated "activity" to 2.10.1

Updated "cloud_federation_api" to 1.0.0

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_calendar_resources_md (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, resource_id BIGINT UNSIGNED NOT NULL, `key` VARCHAR(255) NOT NULL, value VARCHAR(4000) DEFAULT NULL, INDEX calendar_resources_md_idk (resource_id, `key`), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

**Comment by PatrickCronin** [comment]
Apologies, my issue was caused by an outdated version of MySQL. My issue is resolved.

**Comment by j-ed** [comment]
> Specified key was too long; max key length is 767 bytes_

Please use the Nextcloud [help forum](https://help.nextcloud.com/) to get your question answered, because this is the bug and feature tracker of the developers only. Using the given search criteria you will find [tons of matches](https://help.nextcloud.com/search?q=Specified%20key%20was%20too%20long%3B%20max%20key%20length%20is%20767%20bytes) which should allow you to fix your problem.
