### ISSUE TITLE
User provisioning API creates a user and returns failure on invalid properties

### ISSUE THREAD

**Issue by go2sh** [nextcloud/server#22266]
I just saw that while creating a user with an invalid attribute (e.g. language) the user still gets created but a failure is send as response.
This is happens because the attributes are changed through the `editUser` function after the user has been created. There is no cleanup if any of the `editUser` calls fail. Additionally an undocumented status code is returned since it comes from a different api call.
See https://github.com/nextcloud/server/blob/master/apps/provisioning_api/lib/Controller/UsersController.php#L314
I just want to know if this might be a wont fix and if not create a pull request.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
