### ISSUE TITLE
nested groups not evaluated completely, TOTP not enforced

### ISSUE THREAD

**Issue by mamama1** [nextcloud/server#22263]
### Steps to reproduce
1. fresh nextcloud 19.0.1 installation on the officail hanssonit nextcloud vm
2. configure ldap server (active directory, server 2019)
3. configure totp (optional) using the TOTP app, enforce 2FA for specific LDAP groups

### Expected behaviour
nested groups should be evaluated correctly, TOTP should be enforced

### Actual behaviour
only the first group within the configured group is being evaluated, so only the two members which are in the first group are being found by nextcloud.
also, TOTP is not being enforced based on non-nested group memberships, users can logon while 2FA is not configured.

### Server configuration

fresh official nextcloud vm

#### LDAP configuration (delete this part if not used)
ldaps on port 636
bind user is being used
base dn is DC=mydomain,DC=local

users filter:
(&(objectClass=person)(memberof:1.2.840.113556.1.4.1941:=cn=nextcloudusers,ou=groups,dc=example,dc=com)(samaccountname=%uid)

rest of the filters is left default
turn off ssl validation
nested groups enabled in advanced config
paging chunksize 0 (didn't work with default either)

users do not have more than like 15 groups, no ultra long group names.

it appears that ldap nesting is continuously making trouble and that it is getting fixed over and over again.

the same ldap filters entered on the Active Directory Domain controller returned all desired users, not just two of them, so the filters are ok.

I have now changed the config to use the extensionAttribute2 like this:
users filter: (&(objectclass=person)(extensionAttribute2=nextcloud))
login attribute: (&(objectclass=person)(extensionAttribute2=nextcloud)(samaccountname=%uid))
group filter: (&(objectClass=group)(extensionAttribute2=nextcloud))

and nextcloud keeps telling me "Configuration incorrect", but everything is working fine (except 2FA enforcement still isn't working, as that is still based on group memberships. it does not work despite the fact that the groups used for 2FA enforcment have the users as direct members, so no nesting here.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
