### ISSUE TITLE
Select2: Another broken dialogue in our current daily

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2226]
<img width="982" alt="screen shot 2016-11-21 at 23 43 44" src="https://cloud.githubusercontent.com/assets/878997/20503759/693263b0-b044-11e6-9b0b-26365dbf04a9.png">

cc @jancborchardt

**Comment by MorrisJobke** [comment]
@skjnldsv As I told you: https://github.com/nextcloud/server/pull/2133#issuecomment-261261847

Maybe this is something related to OS X? @oparoz Could I ask you to look at this on Chrome on Windows?

**Comment by MorrisJobke** [comment]
Fix is in #2229

**Comment by skjnldsv** [comment]
Well, we can exclude the cache issue now! Sorry about that Morris!

**Comment by MorrisJobke** [comment]
> Well, we can exclude the cache issue now! Sorry about that Morris!

;) There is this magic setting in Chrome:

<img width="298" alt="bildschirmfoto 2016-11-22 um 10 44 19" src="https://cloud.githubusercontent.com/assets/245432/20518778/a4236f76-b0a0-11e6-8fcc-49943199dab9.png">

So I knew that it wasn't a caching issue ;)

**Comment by skjnldsv** [comment]
I also have it enabled, but i had so many cache issues on the past I don't trust it anymore 😆
