### ISSUE TITLE
Groupadmins can not add existing users to their assigned group

### ISSUE THREAD

**Issue by KoljaL** [nextcloud/server#22264]
The admin creates groups and appoints group admins, who should then be able to manage their groups independently.
Like written in the dokumentation:

> Group administrators have the rights to create, edit and delete users in their assigned groups.

### Steps to reproduce
1. As a groupadmin, try to add an existing user to your group

### Expected behaviour
As a group admin, i should be able to see all users and add individuals to my group.

### Actual behaviour
As a group administrator, I can create new users who are then in my group, but do not add any existing users.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
18.0.7
**Updated from an older Nextcloud/ownCloud or fresh install:**
tried both
**Where did you install Nextcloud from:**
nextcloud.com

**Comment by dirigit** [comment]
Looks correct for me in relation to data protection. A mechanism like invitation or something similar could be usefull.
cu, diri

**Comment by y0va** [comment]
Missing that feature too.

https://help.nextcloud.com/t/how-to-add-existing-users-as-group-admin/44766/6

**Comment by Daksol** [comment]
If you add Group "everyone" to the list of groups for all of the Group Admins then it works fine. GAs can browse through users to find the user of interest, and add that user to Groups they are GA for.

There are some downsides of doing this, as GAs have capability to do actions like deleting accounts, resetting user passwords. See link above to item 22371

Our organisation would prefer that:-

* GAs cannot make any changes wrt user accounts - cannot create, modify or delete users, cannot reset passwords
* GAs can view all users - and add them or remove them for the Groups they are GA for.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by tvogel** [comment]
Honestly, this is not a nice to have but instead makes instead the lack of it makes it impractical to delegate group administration. I whole-heartedly agree with https://github.com/nextcloud/server/issues/22264#issuecomment-832809700 .
