### ISSUE TITLE
Can't post comments on current daily

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2227]
I get a 400:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>Invalid input values</s:message>
</d:error>
```

@rullzer THX

**Comment by LukasReschke** [comment]
Also instead of fixing just this bug I'd love to have this scenario covered by integration tests. ;-)

**Comment by LukasReschke** [comment]
Funnily the comments do appear after I have reloaded though?!?

**Comment by rullzer** [comment]
crazy stuff. 
We do have intergration tests (https://github.com/nextcloud/server/blob/master/build/integration/features/comments.feature)
I can't reproduce on master and/or daily.

Tested in firefox and chrome...

**Comment by LukasReschke** [comment]
Works on newest daily now.
