### ISSUE TITLE
ftp -> ls -> ftp server show "." in file list. Nextcloud doesn't like this

### ISSUE THREAD

**Issue by smartbyte** [nextcloud/server#22282]
Nextcloud Beta (19.0.1)
DB -> SQLite3
On Ubuntu 20.04 LTS
On Apache 2.4 php-f... module

Following Problem:
I have a buggy FTP Server which sends the file list as follows (ls):
drwxrwxrwx     1 1000 1000        4 Jan 23 15:56 .
drwxrwxrwx     1 1000 1000        4 Jun 23 08:20 backup
drwxrwxrwx     1 1000 1000        4 Jun 28 21:08 media
drwxrwxrwx     1 1000 1000        4 Jun 24 09:50 nextcloud

As you can see in the first line there is a directory called "." (Netxcloud does recognize this "." correctly and uses the upper folder name, so if I am in folder backup, Nextcloud shows me a backup folder inside the backup folder, which is wrong) My question is: As this is a general bug (of the ftp server but might happen on others too), is there a way to filter out this "." when sending the file list inside a directory to NextCloud?

Thanks.

**Comment by szaimen** [comment]
Looks like you should fix your ftp server.
