### ISSUE TITLE
Calendar : Status update fail with link in invitation's email

### ISSUE THREAD

**Issue by tgift1530** [nextcloud/server#22286]
Hello, 

### Steps to reproduce
1. User A and User B have NC accounts on the same server.
2. User A create an event and add User B as an attendee.
    In DB, there are 2 lines in oc_calendarobject (1 per user) with the same UID.
3. UserB receive an invitation email, with link for accept or decline, like:
    (https://......./index.php/apps/dav/invitation/accept/s6NuBkjtDzdJk8tcizBFYWxKXgHaX8Y6U5u4lJM9yr8eh99fdt0TLtqFsgc7)

### Expected behaviour
both calendardar in oc_calendarobject should have PARTSTAT=ACCEPTED

### Actual behaviour
When User B Click Accept with email's link, the response is updated only on UserA oc_calendarobject.
The line of UserB is still in NEEDS-ACTION status.
If the acceptation is done in a iPhone calendar, both lines are updated (with PARTSTAT=ACCEPTED)

### Server configuration

**Operating system:**
CentOS 8
**Web server:**
httpd 
**Database:**
mysql
**PHP version:**
7.4.1
**Nextcloud version:** (see Nextcloud admin page)
17.0.1 & 19.0.0

Regards, 
Franck.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
