### ISSUE TITLE
Remove "index.php" - folder from nextcloud url (default setting in future releases?)

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#22296]
In the default settings in the nextcloud path you see "index.php" like:

 https://demo2.nextcloud.com/index.php/login (index.php in path)
vs.
 https://nc.nl.tab.digital/ogin (no index.php in path)

I think there is no reason for it. You can change it this way:

config/config.php:
'htaccess.RewriteBase' => '/',
sudo -u www-data php /var/www/nextcloud/occ maintenance:update:htaccess

I think in 2020 nobody needs this folder. It is only ugly, useless and because of rewrite no real folder ;-)
Perhaps you can change the default settings in new nextcloud releases.
Thanks.

**Comment by szaimen** [comment]
As I understand it, this is not doable based on the current architecture since we would then would drop the feature to install nextcloud in a subdirectory.

**Comment by devnull4242** [comment]
No. I think it is further possible to install nextcloud in a subdir. You can change in every nextcloud installation the obove configuration in config.php to change from path with "index.php" to path without "index.php". I think default without "index.php" would be fine.

**Comment by kdambekalns** [comment]
Except when not using Apache, e.g. nginx – for me `maintenance:update:htaccess` sound like an Apache-only solution.
