### ISSUE TITLE
Calendar : VAlarm are saved in all attendees calendarobject

### ISSUE THREAD

**Issue by tgift1530** [nextcloud/server#22290]
Hello,
### Steps to reproduce
1. 2 users are on same event.
2. User 1 record an alarm
3. this alarm is duplicated on event of User 2

### Expected behaviour
Alarms should not be shared (ie, not copied)

### Actual behaviour
Last saved alarm will override previous alarms (for all attendees)

### Server configuration

**Operating system:**
CentOS
**Web server:**
httpd
**Database:**
mariaDB
**PHP version:**
7.4.1
**Nextcloud version:** (see Nextcloud admin page)
17.0.1 -> 19.0.0

Regards,
Franck.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
