### ISSUE TITLE
New server should copy all events from clients

### ISSUE THREAD

**Issue by achimwagenknecht** [nextcloud/server#22318]
I replaced a broken Nextcloud server with new hardware. I connected an existing calendar client.

What I expected to happen:
Server copies all events from the client. (Seemed normal for me.)

What really happened:
All events on the client were deleted. (Seems ridiculous and dangerous for me.)

I've been told, this was the usual behaviour. 

So I suggest to implement a "first run"-condition in the server.

When a client initialises the first sync with a new server, the dialog should work as follows:
Client asks for event.
Event is not stored on the server.
Instead of telling the client: "Event has been deleted" (which is not true!) "please delete it, too", the server says: "Event missing on my side, please send data."

I'm not sure if this should be implemented on server side or on client side or both. If it should be implemented in the client, please move this issue accordingly. I don't know how this is reflected in the protocol. I only tested this with calendars, but maybe other modules are affected, too.

**Comment by Spartachetto** [comment]
This would be a really interesting functionality. If the different clients could copy at least part of their information on the new server that would be terrific.
Maybe it could be a step towards #11653 ...

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
