### ISSUE TITLE
People menu improvements

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#22329]
## Feature request

Overall we always wanted to do more with that "Contacts" menu than what it is right now.

![image](https://user-images.githubusercontent.com/925062/90762147-cee8b700-e2e4-11ea-8bc9-44292e89888b.png)

Showing Contacts alone is just not very useful – especially sorted alphabetically, where you see the same people starting with "A" all the time.
It should not be limited to "Contacts", but also include Talk conversations as well and also users on the instance.

## Solution

Basically it should be a "People" menu. And it could be sorted by most recent interaction, e.g. who you last communicated with via Talk / who last sent you a message, or who you last shared with / last shared with you. It would basically be like:

> **Name of person**
> Subline with last interaction, like Talk message, or file share

(And of course their avatar on the left as now :)

For example for Talk messages:

> **Alex Lastname**
> 💬 Yeah that would be cool!

For Files sharing:

> **Sam Lastname**
> 📁 shared document.pdf

For Mail:

> **Blake Lastname**
> 💌 Re: Party planning

And so on. :) What do you think @dk1a @skjnldsv?

## Work packages

- [x] https://github.com/nextcloud/server/issues/40559
- [ ] https://github.com/nextcloud/server/issues/40561

**Comment by dk1a** [comment]
Seems interesting to me, I assume I should finish the baseline #22274 first

**Comment by skjnldsv** [comment]
Yes, it's for a future enhancement. Let's move to vue first @dk1a :)

**Comment by jancborchardt** [comment]
Closing as this was done for 28 via https://github.com/nextcloud/server/issues/40559
