### ISSUE TITLE
Display Upload Date for Files in App (and make it sortable)

### ISSUE THREAD

**Issue by florom** [nextcloud/server#22324]
Hi Devs,

The Use Case is:

1, Anyone adds new Pictures to a Folder with (Picture) Creation Date 15.05.2020.
2, It is sorted for Creation Date so I find easily the new pictures
3, Anyone adds new Pictures to a Folder with (Picture) Creation Date 30.05.2020.
4, It is sorted for Creation Date so I find easily the new pictures.
5, Anyone adds new Pictures to a Folder with (Picture) Creation Date 22.05.2020.
6, It is sorted for Creation Date so I do not find new pictures nor at the beginning and not at the end too. ---> That is quite frustrating

Is there a possibility to personally adapt something like that. It is really annoying missing new pics.

Thanks for considering,
Florom

**Comment by florom** [comment]
Hi @tobiasKaminsky ,

Thanks for the reply and therefore consideration.
 I have made a request in nextcloud / server which is similar:

https://github.com/nextcloud/server/issues/22278

Probably there are now duplicates.

Thank you,
Florom

**Comment by tobiasKaminsky** [comment]
Yes, they are. 
So closing this one :-)
