### ISSUE TITLE
Removal of the last (and only) tag renders filesync, occ files:scan unusable (webdav seems affected also)

### ISSUE THREAD

**Issue by Bubbelb** [nextcloud/server#22323]
### Steps to reproduce
1. Tag a file in NC (If not yet tagged)
2. Remove tag
3. Wait for a few days (Background process running?) and sync an occ files:scan fails.

Errors are described here: https://help.nextcloud.com/t/tag-id-s-not-found-fixed/90050

### Expected behaviour
Sync and scan should run as normal.

### Actual behaviour
See forum post

### Server configuration

**Operating system:**
Arch Linux x86_64
**Web server:**
Apache

**Database:**
MariaDB
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
19.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
yes
**Where did you install Nextcloud from:**
Archlinux package
**Signing status:**
```
No errors have been found.
```
</details>

Rest of the bug report seems quite unneeded for this issue.

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Bubbelb** [comment]
I'll check.
Will report in a week, or so.

**Comment by Bubbelb** [comment]
Quite sooner than a week and it seems to be resolved.
occ files:scan --all runs without any hickups. and there are no other strange things going on.

I'll keep an eye on it the coming week, but as it seems for now all is well.
I'll close the issue and reopen, if the issue reappears.
