### ISSUE TITLE
Reshare Permission Problem with Groups and Users

### ISSUE THREAD

**Issue by orb1tzero** [nextcloud/server#22328]
### Steps to reproduce
1. Create a group
2. Give that group to an user
3. Share a folder to that group with readonly permissions
4. Share a subfolder of that folder to the same user with all permissions

Example:
1. Create group _mygroup_
2. Give _mygroup_ to user _myuser_
3. Share the folder _myfolder_ to _mygroup_ with readonly permissions
4. Share a subfolder _mysubfolder_ to _myuser_ with full permissions

### Expected behaviour
The user should have full access to _mysubfolder_ in the main directory.

### Actual behaviour
The user can't share a link of _mysubfolder_ even if he has the permissions to reshare, because the permissions from the parentfolder seem to block that permission. 
(Still worked correctly in 18.0.7 but in 19.0.1 not anymore)

### Server configuration
OS: Ubuntu 18.04 64Bit   Linux 4.15.0-106-generic x86_64
Official Docker Image: nextcloud:latest sha256:f4f468c318f55d05e6b2022e8510371d7454b29718f93e44381a66c6f4fad4a3
Nextcloud-Version: 19.0.1
Updated from Version: 18.0.7

**Comment by skjnldsv** [comment]
cc @nickvergessen @rullzer permissions issues?

**Comment by orb1tzero** [comment]
This also affects the permissions to create textfiles and preventing you from saving documents with collabora.

**Comment by alexbijma** [comment]
this is still an issue in version 21. Is there any expectation when this will be fixed? Please let me know if more information to reproduce or other details are needed.

**Comment by Pytal** [comment]
@orb1tzero is this still applicable on the latest 23, 22, 21, or 20 releases?

**Comment by alexbijma** [comment]
I tested it on Nextcloud Hub II 23.0.0 and it still occurs in there.
