### ISSUE TITLE
Dashboard empty state improvements and unification

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#22339]
There are some outstanding improvements for the empty states:
- [ ] For every widget: Since we have a bold heading for each widget already, it’s a bit much to set the emptycontent text as h2 as well. I’d say we should instead set it as a simple `<p>`.
- [x] Recommended files: Doesn’t show anything, should show the files icon and "No recommendations yet". cc @juliushaertl 
- [x] Mail: The image is a bit out of place, should use an icon instead. cc @ChristophWurst @GretaD 
    - [ ] When no accounts are set up: `icon-archive` from Mail, and text "No accounts configured".
    - [ ] When accounts are set up but there’s no important mails: `icon-checkmark`, "No important mails". If there are any other mails, we could also have that message be only 2 entries high and show other mails below like we do in Talk.
- [x] Calendar: Is great regarding text and position, but the "Create a new event" button does nothing. Also the text should be set as `<p>` as said above, and icon-checkmark would be better as icon (also to not duplicate the calendar icon). cc @georgehrke 
- [x] Talk: Is great on icon and text (when it’s shortened), but if there are no conversations yet it’s strange to have it stick to the top. It would be better to have it vertically centered, and also to have a button "Start a conversation". cc @nickvergessen => https://github.com/nextcloud/spreed/pull/4033

. | .
-|-
![image](https://user-images.githubusercontent.com/925062/90791117-1f720b80-e309-11ea-9bb5-125ec0dd6772.png)|![image](https://user-images.githubusercontent.com/925062/90791543-9c04ea00-e309-11ea-95c1-bb4f88dfc513.png)

**Comment by georgehrke** [comment]
>  Calendar: Is great regarding text and position, but the "Create a new event" button does nothing. 

I simply didn't implement it yet. That PR is still a draft after all :)

**Comment by nickvergessen** [comment]
> Talk: Is great on icon and text (when it’s shortened), but if there are no conversations yet it’s strange to have it stick to the top. It would be better to have it vertically centered, and also to have a button "Start a conversation". 

Talk is not empty on first visit, as you have the changelog conversation and in the future the notes conversation, you just removed everything but that is not the default. :wink: I think the logic in the vue component is currently quite bound to load the conversation afterwards and being on the talk UI, so not sure it makes too much sense to invest a lot of time into this when it only shows when you intentionally clear all conversations.

For the positioning, the current positioning is chosen, as we will show conversations without calls/mentions if you have no calls/mentions at all. So again, this only looks like this when you intentionally go to talk and make it look like this. Can we spent time better or is this a must have for people wanting to break things?

**Comment by jancborchardt** [comment]
@nickvergessen ok, sure – probably a bit convoluted. Still for Talk: Could you shorten the message to just "No unread mentions" as well as setting it as a `<p>` instead of a `<h2>`?

**Comment by nickvergessen** [comment]
I thought I had done that already, let me check

**Comment by juliushaertl** [comment]
Closing as the core apps have been fixed and other issues should be tracked in the individual app repos.
