### ISSUE TITLE
IUser::getEMailAddress() returns null

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#2235]
### Steps to reproduce
1. use IUser in an app
2. call `getEMailAddress()` to get user's email address

### Expected behaviour
`getEMailAddress()` returns e-mail entered in personal settings

### Actual behaviour
`getEMailAddress()` returns null

Reproducible on master
Regression
Most certainly introduced with AccountsManager

@schiessle

**Comment by schiessle** [comment]
I will have a look at it

**Comment by schiessle** [comment]
fix is here: https://github.com/nextcloud/server/pull/2276

Problem was not the getEMailAddress(), but that we didn't updated the users setting correctly after the user changed his email address... Please review.
