### ISSUE TITLE
.htaccess does not handle HTTPS .well_known redirects properly, when running behind a reverse proxy

### ISSUE THREAD

**Issue by gjoliver** [nextcloud/server#22375]
### Steps to reproduce
1. Configure a reverse proxy in front of your Nextcloud installation for terminating HTTPS requests.
2. Use Chrome browser and go to Settings -> Overview page.
3. See the warnings about .well_known redirects not properly set up.

### Expected behaviour

.htaccess should redirect to HTTPS URLs when x-forwarded-proto header is https.

### Actual behaviour

Instead, .htaccess always redirect to HTTP urls today, since it doesn't respect the x-forwarded-proto header.

### Server configuration

RancherOS
Custom Reverse Proxy
MariaDB, Redis
nextcloud:18.0.3-apache docker image, freshly install.
Chrome Browser

A working fix was proposed and shot down here: https://github.com/nextcloud/server/pull/22084
The PR thread contains tons of good context and discussion about the problem, and why I think it was the right fix.
Hopefully useful if anyone wants to pick this issue up.

**Comment by szaimen** [comment]
Hi, please make sure that your reverse proxy configuration is correct.
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse%20proxy
