### ISSUE TITLE
GroupAdmin implementation considered harmful (delete users:allowed, add/remove members:not allowed)

### ISSUE THREAD

**Issue by dereks** [nextcloud/server#22371]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Add a GroupAdmin for a group
2. Add a normal user who is member of that group
3. Have the GroupAdmin delete that user, and their files, forever.

### Expected behaviour

Deleting users should not be an option for GroupAdmins. It is a blatant security violation. This is not how groups work under POSIX systems. It is not normal. **Only a SuperAdmin should be able to create or delete users.**

For example: say Alice from Accounting wants to join the company Soccer team. So the SuperAdmin adds her to group **soccer**, so she can upload and share pictures of the soccer games.

Because of that, Bob the GroupAdmin of **soccer** can DELETE ALICE'S ACCOUNT AND FILES ENTIRELY FOREVER.

**Being a member of any one group should not subject you to total annihilation by that group's admin.** If I'm a member of ten different groups, that's ten different GroupAdmins who could make a mistake, like click the wrong button, leave their computer unattended in public, or get mad because I'm so awesome at soccer, and thus destroy my account and all of my files.

Even if Alice is herself a GroupAdmin it won't save her. **So with Nextcloud the GroupAdmin of the company soccer team can delete the GroupAdmin of the accounting department.** That is crazy.

As far as affecting other users, a GroupAdmin should only be able to add people to a group or remove them from a group. 

### Actual behaviour

GroupAdmins can delete users entirely.

Related Bugs:

GroupAdmin can't add a user to their group. See: #22264
GroupAdmin can't remove a user from their group. Results in error message _Not viable to remove user from the last group you are SubAdmin of_ .

### Server configuration

**Operating system:** Ubuntu Linux 20.04

**Nextcloud version:** (see Nextcloud admin page) 19.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Fresh install from the provided script:  **nextcloud_install_production.sh**.

</details>

**Comment by skjnldsv** [comment]
See https://github.com/nextcloud/server/issues/3630

**Comment by dereks** [comment]
@skjnldsv Agree, #3630 is a duplicate.

But #3630 is a 3 year old bug with no updates in 1.5 years. And the discussion was locked because it got heated.

The user comments are almost unanimous that this is an anti-feature, i.e., an actual bug that should be fixed. To quote one of the many "me toos" from that thread:

> it IS dangerous. We are an educational institution with 500 employees and over 4000 students, and you can imagine my surprise when students were deleted not only from groups by our tutors but from the complete system. Took quite some time to find out what happened there and almost gave our SharePoint-Advocates a good edge...

**Comment by skjnldsv** [comment]
Yes, we won't start a new discussion here. Sorry. :)

**Comment by dereks** [comment]
@skjnldsv Thanks for your reply. I understand. Unfortunately, this bug is the reason I decided not to use Nextcloud in our organization.

"Nextcloud - a safe home for all your data" is simply not true so long as this user interface issue exists. The best crypto in the world can't save you from a dangerous user interface.

There is no use case where this makes sense. It seems beyond obvious from a data security and system administration point of view. I cannot trust file server software written by a team who thinks this is a good idea.

I hope you will take this feedback constructively and decide to address this issue in the near future. The look'n'feel of Nextcloud is terrific, and the collaborative document editing is the killer feature that brought me here. But none of that matters if a careless or disgruntled employee deletes all your data.
