### ISSUE TITLE
Adjusting visual cues & hints for End-to-end encrypted folders

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#22370]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I dont like how E2EE-enabled folders are constantly visually differentiated / highlighted on web:

![Screenshot_1](https://user-images.githubusercontent.com/36133540/90962161-3c940f00-e4ae-11ea-8011-cdae065b3bc5.png)

I also dont feel the phrase "you dont have permission to upload or create files" is appropriate for a server admin/owner to display. Moreoever, Im not able to delete the E2EE folder as a whole but I can remove files individually.

![Screenshot_2](https://user-images.githubusercontent.com/36133540/90962165-461d7700-e4ae-11ea-9747-fd6b9273a032.png)

**Describe the solution you'd like**
- Remove constant higlight for E2EE folders
- Explain that plain non-encrypted files cannot be uploaded through web but not in a way that would question one's permissions as an admin
- Be able to delete whole E2EE folder from web ?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
