### ISSUE TITLE
Dashboard not automatically enabled if the old app has been disabled before

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22380]
- Having the old dashboard app installed before at some point
- oc_appconfig has enabled=no for the dashboard app
- Update to 20 beta1
- See that the dashboard has not been auto enabled

I'm not sure how to solve that yet without hardcoding a special case for dashboard. cc @nextcloud/server-triage Any ideas?

**Comment by skjnldsv** [comment]
Migration to remove the appConfig?

**Comment by juliushaertl** [comment]
:see_no_evil: Of course :grin:
