### ISSUE TITLE
Text files - visualisation

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/server#22399]
Might by a feature, might be a bug, or else !!!

nextcloud 18.0.7
opening a txt files: ables to read only 74 colum ( or character ) per line. 
Yes, txt is a flatfile, usualy unformated, and with no specific EOF.
But, usually, the commun ground is 80 columns in most txt editor ...

Is there a way to adapt nextcloud to shwo 80 columns ??

If not, i will simply retype my txt files using 74 columns :)

**Comment by jospoortvliet** [comment]
Hi,

please read the bug report template - this isn't a support forum. Use help.nextcloud.com for this kind of questions.

Thanks!
