### ISSUE TITLE
Nextcloud sharing the file that associate with the apps inside

### ISSUE THREAD

**Issue by SomboChea** [nextcloud/server#22406]
Hi, there!

I wonder about the file sharing that need the apps inside Nextcloud account to open the file that shared out/inside account to use the associate the file open-with. Liked Google Drive, they have open-with option that we can choose the app to open with the file that we shared to.

Because I have installed Nextcloud in my own server, then I created the document from drawio with .xml extension. After that, I shared to my team and they cannot open with drawio to collaborate the file together.

What should I do, if I want to open the file shared that want to associate with apps inside the Nextcloud?

Thank you!

**Comment by kesselb** [comment]
https://github.com/pawelrojek/nextcloud-drawio#mimetype-detection
