### ISSUE TITLE
Getting 404 when fetching notes (Readme.md)

### ISSUE THREAD

**Issue by kfirfer** [nextcloud/server#22438]
Server setup:
19.0.1.1

Using docker image

Cluster setup:
Redis for apache php session storage + file locks
+
MySQL Percona Cluster 8.0.19
+
Minio S3 for data

Having 2 Nextcloud instances

Reproduce:

Open 2 browsers , different sessions, login to the same account and you could see in the picture attached

![Screenshot from 2020-08-26 20-03-45](https://user-images.githubusercontent.com/7741545/91335560-3f0da600-e7d9-11ea-9a68-997366065594.png)

**Comment by kesselb** [comment]
Thanks :+1: 

Closing your report in favor of https://github.com/nextcloud/text/issues/820. If you are using the docker image from linuxserver.io this comment might be helpful: https://github.com/nextcloud/text/issues/820#issuecomment-632850792
