### ISSUE TITLE
NC20 app icon of "User Status"

### ISSUE THREAD

**Issue by Rello** [nextcloud/server#22433]
The app icon of the "User status" app in the appstore is using the inverted color (white icon).
the black needs to be shown

![Bildschirmfoto 2020-08-26 um 09 09 05](https://user-images.githubusercontent.com/13385119/91272276-cc221200-e77b-11ea-98e1-1883284e17ec.png)

**Comment by juliushaertl** [comment]
@georgehrke

**Comment by georgehrke** [comment]
PR: #22450
