### ISSUE TITLE
Coordinate displaying avatars

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#22434]
- [x] Android @tobiasKaminsky 
- [x] Desktop @nextcloud/desktop 
- [ ] iOS @marinofaggiana 
- [x] Server

Test Admin -> TA
Tobias Kaminsky -> TK
Admin -> A
Test Server Admin -> TS
email@server.com -> E

Use first char of first two words:

```
$firstTwoLetters = array_map(function ($namePart) {
			return mb_strtoupper(mb_substr($namePart, 0, 1), 'UTF-8');
		}, explode(' ', $displayName, 2));
```

**Comment by tobiasKaminsky** [comment]
Android done, check PR for further test cases: https://github.com/nextcloud/android/pull/6819

**Comment by rullzer** [comment]
So I'm just wondering. Where is this still used on the clients? As the endpoint will not always return you an avatar right?

**Comment by tobiasKaminsky** [comment]
This is used 
- for room and group shares
- as a first shown placeholder until avatar is fetched
- as contact if there is no photo set
- as a fallback if avatar retrieving is not working (e.g. no internet connection)

**Comment by juliushaertl** [comment]
Iirc @jancborchardt mentioned recently that we should actually not use letter placeholders (like avatars) for anything else than users.

**Comment by tobiasKaminsky** [comment]
Currently it looks like this on Android:
This is default file listing with dummy values.

![image](https://user-images.githubusercontent.com/5836855/91833832-810a7200-ec47-11ea-939b-a8a659851683.png)

If I understand this correctly, then I need to change
- email -> email symbol with primary color as background
- group -> group icon? with primary color as background (?)
- room -> talk icon (?)

**Comment by tobiasKaminsky** [comment]
> If I understand this correctly, then I need to change
> 
>     * email -> email symbol with primary color as background
> 
>     * group -> group icon? with primary color as background (?)
> 
>     * room -> talk icon (?)

@jancborchardt please :-)

**Comment by juliushaertl** [comment]
He'll be back next week :wink:

**Comment by tobiasKaminsky** [comment]
![image](https://user-images.githubusercontent.com/5836855/92224852-b232ae80-eea2-11ea-9448-5f18374ebb37.png)

I just saw this on our server, latest master.
- no 2 chars
- char also for conversation, groups

**Comment by tobiasKaminsky** [comment]
iOS tracked in: https://github.com/nextcloud/ios/issues/1703
