### ISSUE TITLE
Too much spacing on select2 options

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2244]
Using Firefox and Chromium

@jancborchardt @nextcloud/designers 

### System tags sidebar
> ![bildschirmfoto vom 2016-11-22 16-25-03](https://cloud.githubusercontent.com/assets/213943/20529552/d3861806-b0d0-11e6-81c9-23d7d66b26af.png)

### Spreed select callee
> ![bildschirmfoto vom 2016-11-22 16-26-27](https://cloud.githubusercontent.com/assets/213943/20529553/d3a40604-b0d0-11e6-9b35-22065e761337.png)

It's a nested 12px padding, so 24 and this looks very odd

**Comment by skjnldsv** [comment]
Refs: #2229 & #2133#issuecomment-262059604

**Comment by nickvergessen** [comment]
Right, that fixed it. Thanks
