### ISSUE TITLE
Cluster of nextcloud 19 sessions with redis + Proxy load balancer round robin

### ISSUE THREAD

**Issue by kfirfer** [nextcloud/server#22445]
Cluster:
* 19.0.1-apache
* Redis 5.0.6 for file locking and **session storage**
* PHP 7
* Apache 2
* Minio S3 for storage
* Percona xtradb cluster 8.0.19

The whole cluster sits on top of kubernetes cluster.
Each component has 3 instances, e.g. 3 redis(s) , 3 Nextcloud instances and so forth...

The traffic is behind a load balancer proxy (NginX)

when I enable load balancer round robin on the proxy level (NginX), 
the server throws to the user 401, and tells that the user is not logged in

Kind of the cluster architecture setup
![ffff](https://user-images.githubusercontent.com/7741545/91364279-0e446580-e807-11ea-819b-6ab1df9fd357.jpg)

### Server configuration

**Where did you install Nextcloud from:**
Docker image:
<details>
<summary>Docker file </summary>

```
FROM nextcloud:19.0.1-apache

RUN set -ex; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        libmagickcore-6.q16-6-extra \
        procps \
        smbclient \
        supervisor \
#       libreoffice \
    ; \
    rm -rf /var/lib/apt/lists/*

RUN set -ex; \
    \
    savedAptMark="$(apt-mark showmanual)"; \
    \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        libbz2-dev \
        libc-client-dev \
        libkrb5-dev \
        libsmbclient-dev \
    ; \
    \
    docker-php-ext-configure imap --with-kerberos --with-imap-ssl; \
    docker-php-ext-install \
        bz2 \
        imap \
    ; \
    pecl install smbclient; \
    docker-php-ext-enable smbclient; \
    \
# reset apt-mark's "manual" list so that "purge --auto-remove" will remove all build dependencies
    apt-mark auto '.*' > /dev/null; \
    apt-mark manual $savedAptMark; \
    ldd "$(php -r 'echo ini_get("extension_dir");')"/*.so \
        | awk '/=>/ { print $3 }' \
        | sort -u \
        | xargs -r dpkg-query -S \
        | cut -d: -f1 \
        | sort -u \
        | xargs -rt apt-mark manual; \
    \
    apt-get purge -y --auto-remove -o APT::AutoRemove::RecommendsImportant=false; \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p \
    /var/log/supervisord \
    /var/run/supervisord \
;

RUN chmod -R 777 /usr/local/etc/php/conf.d

COPY supervisord.conf /

ENV NEXTCLOUD_UPDATE=1

RUN useradd -ms /bin/bash next
USER next

CMD ["/entrypoint.sh", "apache2-foreground"]

```

</details>

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'htaccess.RewriteBase' => '/',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
  'overwriteprotocol' => 'https',
  'overwritehost' => '*******',
  'logfile' => '/dev/stdout',
  'trusted_proxies' => 
  array (
    0 => '*******',
  ),
  'skeletondirectory' => '',
  'activity_expire_days' => 14,
  'auth.bruteforce.protection.enabled' => false,
  'knowledgebaseenabled' => false,
  'trashbin_retention_obligation' => 'auto, 30',
  'secret' => '*******',
  'passwordsalt' => '*******',
  'updater.release.channel' => 'stable',
  'integrity.check.disabled' => false,
  'mysql.utf8mb4' => true,
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.enabled' => 'true',
  'redis' => 
  array (
    'host' => 'redis-redis-ha-haproxy',
    'port' => '6379',
  ),
  'objectstore' => 
  array (
    'class' => '\\OC\\Files\\ObjectStore\\S3',
    'arguments' => 
    array (
      'bucket' => 'nextcloud',
      'hostname' => 'minio',
      'port' => 9000,
      'autocreate' => true,
      'key' => '*******',
      'secret' => ''*******',',
      'region' => 'optional',
      'use_ssl' => false,
      'use_path_style' => true,
    ),
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'smtp.sendgrid.net',
  'mail_smtpport' => '465',
  'mail_smtpsecure' => 'ssl',
  'mail_smtpauth' => true,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpname' => 'apikey',
  'mail_smtppassword' => '*******',',
  'mail_from_address' => 'admin',
  'mail_domain' => '*******',',
  'instanceid' => '*******',
  'trusted_domains' => 
  array (
    0 => 'files.pica.co.il',
  ),
  'datadirectory' => '/usr/local/data',
  'dbtype' => 'mysql',
  'version' => '19.0.1.1',
  'overwrite.cli.url' => '*******',
  'dbname' => 'nextcloud',
  'dbhost' => 'haproxy',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'oc_kfirfer',
  'dbpassword' => '''*******'',',
);

```
</details>

**Comment by georgehrke** [comment]
As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com

If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by kfirfer** [comment]
I dont think this is a setup issue
I checked redis to see if there is a php sessions written there, and it is

**Comment by kesselb** [comment]
@kfirfer mind to share your solution? I remember some reports at https://help.nextcloud.com and here on GitHub about expired / missing sessions on clustered environments. Would be nice to have some pointers how to fix such issues.

**Comment by kfirfer** [comment]
I successed by sync the config.php across the instances
Seems the installation on each instance change the passwordsalt and secret (hash them any time there's a installation)
So when they are different, the sessions are different as-well

btw, the instances filesystems are separate, I trying to avoid using NFS server or any kind of centerlized file system

how is sounds saving the passwordsalt + secret on S3 and when theres a new installation he will grab it from s3 if its already exists ?  or mabye the whole config.php file ?

**Comment by kesselb** [comment]
Thanks :+1: 

`passwordsalt` and `secret` must be the same.

> how is sounds saving the passwordsalt + secret on S3 and when theres a new installation he will grab it from s3 if its already exists ? or mabye the whole config.php file ?

My approach would be to create a `secrets.config.php` next to `config.php` and use `getenv` to read the values for passwordsalt and secret from environment variables.

**Comment by kfirfer** [comment]
When I dont make reinstall process on the addional instances, I had to sync also the `/var/www/html/.htaccess` file to void 403

**Comment by SegaTurbo** [comment]
@kfirfer Hi! 
I have a task to build a cluster, but I haven’t dealt with it before, can you suggest a guide on unfolding a similar structure? S3 connection is planned in a similar way. Nextcloud x2 . Thank you very much!
