### ISSUE TITLE
Overlay Status Indicator on your own avatar in the top right

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#22451]
| Avatar in the top right | Expected status indicator |
|:---------:|:------:|
|![42D25B34-DFC0-4D35-BB93-E9186097D9F3](https://user-images.githubusercontent.com/1250540/91415206-fc39e580-e84d-11ea-82a9-92f1a8c5c661.png)|![21C47F91-5E55-4403-ACCC-B431FBCFABAF](https://user-images.githubusercontent.com/1250540/91415800-d8c36a80-e84e-11ea-8ce9-0a74bc9cd67e.png)|

**Comment by jancborchardt** [comment]
This needs that part to be moved to Vue – cc @rullzer @nickvergessen @juliushaertl for reference. Set it to 21 tentatively, feel free to move to 22.

**Comment by blizzz** [comment]
this is completed for 23
