### ISSUE TITLE
File specific versioning settings

### ISSUE THREAD

**Issue by FlyingKawasaki74** [nextcloud/server#22456]
As of now file versioning settings are controlled globally in the config.php according to the following documentation: https://docs.nextcloud.com/server/14/admin_manual/configuration_files/file_versioning.html

I would like to request a feature to override this global config on a per-file-case. For example I might set the global setting to 'auto, D', while setting it to 'auto' for a small file (e.g. a KeePass DB file). 

Right now I don't see how to add tags to this, so I recommend: "enhancement" and "feature: files"

**Comment by jospoortvliet** [comment]
Interesting idea, indeed. I wouldn't hold my breath, but perhaps somebody wants to pick this up some day ;-)

**Comment by joshtrichards** [comment]
Duplicate of #17566
