### ISSUE TITLE
Feature Parity: User Status

### ISSUE THREAD

**Issue by georgehrke** [nextcloud/server#22452]
This is an issue to track the feature parity of user-status:

### Status
- [x] Android @tobiasKaminsky 
- [x] Desktop https://github.com/nextcloud/desktop/pull/3639
- [x] iOS @marinofaggiana 
- [x] Server

### Docs
https://gist.github.com/georgehrke/55a0412007f13be1551d1f9436a39675

**Comment by tobiasKaminsky** [comment]
Android: https://github.com/nextcloud/android/pull/7149

**Comment by camilasan** [comment]
Desktop: https://github.com/nextcloud/desktop/issues/2318
1st PR: https://github.com/nextcloud/desktop/pull/2505
