### ISSUE TITLE
Scan is not correctly handling the size of terabytes-long files

### ISSUE THREAD

**Issue by dimm0** [nextcloud/server#22465]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Put several 250GB files in user's folder
2. See the storage used for the user

### Expected behaviour
Long files are correctly handled

### Actual behaviour
Showing less than `du -h`. No errors from `occ scan`

### Server configuration

**Operating system:**
Docker container

**Nextcloud version:** (see Nextcloud admin page)
19.0.1

**Comment by dimm0** [comment]
The files are ocTransferId files from ocDownloader. Is it possible that the files are sparse, and nextcloud is looking at the real use, not the filesize?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by dimm0** [comment]
I don't have those large files anymore, can't check...
Closing.
