### ISSUE TITLE
Remote instance in update pending mode breaks federated shares when folders are accessed in between

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22461]
1. Have a federated shared folder from instance NC2 to NC1
2. Increase version of NC2 but don't run occ upgrade
3. try to access the folder on NC1, but fail
4. Upgrade NC2
5. Try to access again, but it still fails

It actually seems that the storage availability is not updated ever again:

```
MariaDB [nextcloud]> select * from oc_storages where id like 'shared::%';
+------------+------------------------------------------+-----------+--------------+
| numeric_id | id                                       | available | last_checked |
+------------+------------------------------------------+-----------+--------------+
|       1013 | shared::47004d5108ca3a32a7feab300abbc744 |         0 |   1598544715 |
|       2723 | shared::deb9a9d7bbad83bcd5cebbe2efca6053 |         0 |   1598545310 |
+------------+------------------------------------------+-----------+--------------+
2 rows in set (0.001 sec)
```

Updating it manually resolves it.

```
MariaDB [nextcloud]> update oc_storages set available = 1 where id like 'shared::%';
Query OK, 2 rows affected (0.019 sec)
Rows matched: 2  Changed: 2  Warnings: 0

MariaDB [nextcloud]> update oc_storages set available = 1 where id like 'shared::%';
```

To be further investigated...

**Comment by juliushaertl** [comment]
Could be related to https://github.com/nextcloud/server/issues/14797 as i could also not remove the share manually

**Comment by mhellmeier** [comment]
Same problem here on Nextcloud 19 / 20. The `available` was also set to `0` in my database. The manual change you suggested doesn't work for me.
Also tried to remove the shared folder and add it again but the problem still exists: The folder size from the federation shows _pending_ and I can't view the files in it (error in the web client: "Storage is temporarily not available").

Maybe related to #9125 .

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by juliushaertl** [comment]
Fixed by https://github.com/nextcloud/server/pull/25332
