### ISSUE TITLE
Dashboard app: Disabling the weather and status widgets is not consistent

### ISSUE THREAD

**Issue by szaimen** [nextcloud/server#22468]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update to NC 20 beta 2
2. see the new dashboard app
3. disable the weather and status widgets
4. the weather and status widgets are now invisible
4. force a reload of the side
5. the weather and status widgets are now visible again

### Expected behaviour
They should still be unvisible

### Actual behaviour
they are visible

### Server configuration
**Nextcloud version:** (see Nextcloud admin page)
NC 20 beta 2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from NC 19.0.1
**Where did you install Nextcloud from:**
NcVM

**Comment by szaimen** [comment]
@nextcloud/designers I wonder if it is
meant to be this way?

**Comment by skjnldsv** [comment]
cc @juliushaertl @eneiluj

**Comment by eneiluj** [comment]
@szaimen It is not meant to be this way :grin:. I can't reproduce this problem. Could you run this SQL query ?

``` sql
select configvalue from oc_preferences where appid="dashboard" and configkey="statuses"
```

After having disabled the statuses, you are supposed to get `{"weather":false,"status":false}`.

Also, is there any error in the browser error log or the server logs when you toggle a status?

**Comment by szaimen** [comment]
This is the output when running the command:
![image](https://user-images.githubusercontent.com/42591237/91702311-d6c41900-eb78-11ea-863c-4628bfe55d90.png)

This is what the following command returns:
![image](https://user-images.githubusercontent.com/42591237/91701936-500f3c00-eb78-11ea-8e43-8c42a757588b.png)

Those are the console logs:
![image](https://user-images.githubusercontent.com/42591237/91701096-1984f180-eb77-11ea-957c-d1482129a2b2.png)

In the nextcloud logs, I get nothing related.

@eneiluj Could it be a problem, that I am running a Postgresql database?

**Comment by eneiluj** [comment]
> Could it be a problem, that I am running a Postgresql database?

@szaimen I don't think so as other values are successfully written to your oc_preferences table.

1. Could you check if the request to "/apps/dashboard/statuses" is failing or not in the network tab of developer tools? The request JSON parameters is supposed to be
```
statuses: "{\"weather\":true,\"status\":false}"
```
2. Is the widget layout saved correctly? If not, then the problem is larger...

@juliushaertl Any clue about what could be happening there?

**Comment by szaimen** [comment]
Thanks for your respond!

for 1.: This is what I get in the network tab when modifying the weather and status widgets:
![image](https://user-images.githubusercontent.com/42591237/91733827-6930e080-ebaa-11ea-9543-d98044ecf403.png)

for 2.: The layout is saved correctly until I reload the site. Then it just shows those widgets again, also if I had disabled them before. (probably because the statuses value(s) isn't saved correctly into the database)

**Comment by eneiluj** [comment]
@szaimen Which browser are you using? Could you try with another one?

Widget activation, widget layout and statuses activation are all supposed to be saved and restored on page load. For the moment I have no idea what happens to you but it seems nothing is saved.

**Comment by szaimen** [comment]
I've tested this on Brave, which is based on Chromium 85.
But the same happens on Firefox 80, too.
![image](https://user-images.githubusercontent.com/42591237/91735868-34725880-ebad-11ea-9667-c817a5a42946.png)

> but it seems nothing is saved.

This is not true. The layout of the app-widgets like recent files and recent statuses is saved and restored correctly. (But this is most likely stored in a layout respond? and not in the status respond?)
Only the weather and status widgets have this problem.

**Comment by eneiluj** [comment]
I thought you said the widgets layout was not saved.

Anyway I found the problem. I'll fix that soon. Thanks for your perseverance :+1:

**Comment by eneiluj** [comment]
@szaimen Ok fixed. Could you try `fix/save-statuses` branch and confirm it now works fine?

**Comment by szaimen** [comment]
> I thought you said the widgets layout was not saved.

Sry, maybe I wasn't clear enough.

> Anyway I found the problem. I'll fix that soon. Thanks for your perseverance 👍

Great!

> @szaimen Ok fixed. Could you try `fix/save-statuses` branch and confirm it now works fine?

@eneiluj Yes, I've tried the fix by simply copying the content to the correct file and it fixes the issue. Thank you very much!

**Comment by szaimen** [comment]
I guess this can be closed since the fix was merged
