### ISSUE TITLE
Help for Update 19.0.1 => 19.0.2

### ISSUE THREAD

**Issue by mercurio31** [nextcloud/server#22464]
Good evening everyone,
sorry but i'm not very experienced and i need help please. I have an update problem. I tried to update my server with Ubuntu 18.04 server, Apache, mariadb, PHP 7.4, but it gives me this error message:
Doctrine \ DBAL \ Exception \ DriverException: An exception occurred while executing "ALTER TABLE oc_addressbooks CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_bin;": SQLSTATE [42000]: Syntax error or access violation: 1071 The specified key it was too long; the maximum key length is 767 bytes

What can I do?
Thank you all!

**Comment by j-ed** [comment]
Please check-out the [**Nextcloud help forum**](https://help.nextcloud.com/) which has been set-up to address such support requests.  [Search](https://help.nextcloud.com/search?q=maximum%20key%20length%20is%20767%20bytes) for "`the maximum key length is 767 bytes`" to find information about how to fix the 4-byte support.
