### ISSUE TITLE
Optimise translation resources at transifix with respect to language codes

### ISSUE THREAD

**Issue by arjanvs** [nextcloud/server#22477]
Dear all

Perhaps, this is wrong place to address this. If so, please move the issue to the right place.

Today I had some time and wanted to translate some blocks at transifix. There I discovered something, what I was viewing as a waste of resources.

For both the website and server, there exists the situations that language codes are mixed together with country codes. This results for example in:
- Translations for German (de) and Germany (de_DE); or
- Spanisch (es), but also Hundurian (es_HN), Argetinian (es_AR) and Mexican Spaninsch (es_MX)
Of course, there are more examples.

So, I have the following suggestion:
-Just use [language codes](https://www.w3schools.com/tags/ref_language_codes.asp) without [country codes](https://www.w3schools.com/tags/ref_country_codes.asp)
-Merge the effort into one set of pure language codes and add all users to their language

This assures, that the website and nextcloud itself is quicker available in more languages.

What do you think?

KR Arjan

**Comment by kesselb** [comment]
cc @rakekniven where do you discuss such things?

**Comment by rakekniven** [comment]
Hello @arjanvs ,

the world is big and we have many languages.
The languages codes you mention are not sufficient e.g. portugal and brasil. No way for them to use the same translation file (language).

See https://en.wikipedia.org/wiki/Language_localisation

What problems do you see with having this many languages?

Cheers

**Comment by rakekniven** [comment]
@kesselb At conferences maybe, mailinglist or IRC? Do not know. 
There has been no discussion about that topic since 2012 AFAIK.

**Comment by kesselb** [comment]
@rakekniven okay.

I updated a wrong german translation today. Had to do it twice because of de and de_DE.

Asked the transifex support if relations of language's are possible. For example de_De is a child of de and only overwrites some strings. That is unfortunately not possible but would reduce the work for Nextcloud.

**Comment by rakekniven** [comment]
Hello Bernhard,

hope for I am right :-)

The german translation community supports two translations: formal and informal. 
For my understanding a parent-child relation will not work.
You are totally right about the work load about it.

Do you know https://help.nextcloud.com/t/die-deutsche-ubersetzung-von-nextcloud-hier-diskutieren-und-fehler-melden-was-sollte-ich-wissen-wenn-ich-bei-der-ubersetzung-helfen-mochte-oder-eine-anmerkung-habe/32139/323?u=rakekniven

Cheers,
Mark

**Comment by arjanvs** [comment]
Dear all

 
> the world is big and we have many languages.
> The languages codes you mention are not sufficient e.g. portugal and brasil. No way for them to use the same translation file (language).
> 
> See https://en.wikipedia.org/wiki/Language_localisation
> 
> What problems do you see with having such many languages?

Nothing is wrong, I think it great.

> I updated a wrong german translation today. Had to do it twice because of de and de_DE.
> 
> Asked the transifex support if relations of language's are possible. For example de_De is a child of de and only overwrites some strings. That is unfortunately not possible but would reduce the work for Nextcloud.

I was talking about the work load. To be honest, differences are most of the time marginal. So, better to have the basic right and start from there to update and keep it alligned.

Now, still some major languages are missing, i.e. website (Spaninsch, Portugese, French, Chinese). Even the server is not 100% up to date.

KR Arjan

**Comment by rakekniven** [comment]
Hello Arjan,

can you see the completness at Transifex? Not sure about the visibilty about completness and roles at Transifex.

Regarding southern america there has been a bigger contract related to education/universities and therefor there are many spanish dialects.

![grafik](https://user-images.githubusercontent.com/2069590/91600057-9772ae00-e967-11ea-85be-c9b7ff0a7c1e.png)

Most common languages are most complete. Do I miss something?

Please let me know.
Mark

**Comment by rakekniven** [comment]
Sorry for closing it. Ctrl*Enter*Double

**Comment by arjanvs** [comment]
Dear Mark

I am aware of the dialects. Perhaps, to make things clearer, I was thinking allong the following lines:
- I assumed that a server will first provide the website on the language code, before it will check details concerning dialects (language and country code pair)
- If that is the case, it would strengthen nextcloud to focus on language codes instead of "wasting" resources on all dialects. I know open source is about freedom etc.
- My whish is to unlock Nextcloud to a big as possible audiance. For this more benificial to bundle resources. Currently, the webpage is only available in 3 languages.
- If people are not translating nextcloud core, they could use their spare time to translate the webpages and documentation. Doing that in all dialects, will costs alot of effort.

![grafik](https://user-images.githubusercontent.com/16195666/91721283-cde33f80-eb98-11ea-9560-941294660efb.png)

![grafik](https://user-images.githubusercontent.com/16195666/91721401-fbc88400-eb98-11ea-90e8-4a1963e2e814.png)

KR Arjan

PS. I didn't noticed the closing.

**Comment by rakekniven** [comment]
Hello Arjan, 



> * I assumed that a server will first provide the website on the language code, before it will check details concerning dialects (language and country code pair)

AFAIK it does this. Mobile Apps have no language switcher at all.

> * If that is the case, it would strengthen nextcloud to focus on language codes instead of "wasting" resources on all dialects. I know open source is about freedom etc.

But why not supporting any language people using and translating as volunteers?
The most used languages have the biggest translation teams and highest completeness.
 
> * My whish is to unlock Nextcloud to a big as possible audiance. For this more benificial to bundle resources. Currently, the webpage is only available in 3 languages.
That is as different one. The Nextcloud company is responsible for the website. And they have to make sure that translations are correct. They only allowed these three languages. That has nothing to do with transifex.
See https://www.transifex.com/nextcloud/nextcloud-website/announcements/7354/
 
> * If people are not translating nextcloud core, they could use their spare time to translate the webpages and documentation. Doing that in all dialects, will costs alot of effort.

People have different interests. Some like to work on documentation other like some specific apps.
Do you know https://help.nextcloud.com/t/list-of-resources-and-their-priority-for-translation/78312 ?

Best regards

**Comment by skjnldsv** [comment]
We're pulling our locale list from transifex directly.
https://github.com/nextcloud/server/pull/17222/files
