### ISSUE TITLE
Nextcloud 20 The old server-side-encryption format is enabled

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#22478]
Hello getting this warring in NC20. 

Is server side encryption no longer supported ? 

![image](https://user-images.githubusercontent.com/59488153/91604942-37631400-e935-11ea-9b1d-a3f334f3f699.png)

![image](https://user-images.githubusercontent.com/59488153/91604965-43e76c80-e935-11ea-89e1-c6cb22d17930.png)

**Comment by axheli** [comment]
https://docs.nextcloud.com/server/20/admin_manual/configuration_files/encryption_migration.html

![image](https://user-images.githubusercontent.com/59488153/92150901-c82e6980-ede5-11ea-9578-776ad0a356ae.png)

**Comment by dhrunia** [comment]
The documentation says running `occ encryption:scan:legacy-format`  will tell you if you can remove the legacy encryption mode. I have ran the command but the output just says scanning/recreate keys for users and all users where done. Does this mean I can disable legacy encryption?

**Comment by axheli** [comment]
Yup you should be good!

**Comment by Adambean** [comment]
Also running NextCloud 20 here and getting this warning, though I've never used it. Running `occ encryption:scan:legacy-format` returns error:

> There are no commands defined in the "encryption:scan" namespace.

**Comment by MacGulliver** [comment]
> 
> 
> Also running NextCloud 20 here and getting this warning, though I've never used server-side encryption. (Alternative cryptography in place at a lower level.) Running `occ encryption:scan:legacy-format` returns error:
> 
> > There are no commands defined in the "encryption:scan" namespace.
> 
> I trust it's OK to just disable legacy encryption in "config.php" then?

same here

**Comment by error420** [comment]
> Also running NextCloud 20 here and getting this warning, though I've never used server-side encryption. (Alternative cryptography in place at a lower level.) Running `occ encryption:scan:legacy-format` returns error:
> 
> > There are no commands defined in the "encryption:scan" namespace.
> 
> I trust it's OK to just disable legacy encryption in "config.php" then?

Same issue

**Comment by Adambean** [comment]
Just an update for you all on this:

> I trust it's OK to just disable legacy encryption in "config.php" then?

I had done that a month ago, and so far, literally zero problems. If your NC had encryption turned (in its settings) as we did then you're also probably going to be safe to turn off legacy encryption in the configuration file.

**Comment by BastianBalthasarBux** [comment]
> https://docs.nextcloud.com/server/20/admin_manual/configuration_files/encryption_migration.html
> 
> ![image](https://user-images.githubusercontent.com/59488153/92150901-c82e6980-ede5-11ea-9578-776ad0a356ae.png)

To be honest, the command tells nothing but a progress on scanning all files for all users.
After completed, it just ends. There is no output of what the result is, and in the documentation is ZERO explanation, what's going on, what should be the output, what should be done, if this or that output is displayed etc ...
So linking to a nonsense documenation about command which hardly explains it's pure existence is NOT what I expect a good base for closing an issue.
Just my 2 cents.

**Comment by Micromegass** [comment]
Also it would be very interesting to know:

- What effect will this have on my files?
- Hence, when disabling legacy encryption, Is there no encryption at all anymore? Do they just deprecate it without any alternative? What will be the status after disabling it?
- I agree with @BastianBalthasarBux the documentation is not helpful a bit since it tells us nothing about the root and resolution of the problem

**Comment by sergey-dryabzhinsky** [comment]
Same here. Notification popups constantly, but here is no encryption enabled.
NextCloud 20.0.10.

**Comment by sergey-dryabzhinsky** [comment]
```
$ php occ encryption:status
  - enabled: false
  - defaultModule: OC_DEFAULT_MODULE
$ php occ encryption:decrypt-all
Server side encryption not enabled. Nothing to do.
```

**Comment by sergey-dryabzhinsky** [comment]
Done. Everyone, just run from console:
```
php occ encryption:migrate-key-storage-format
```
And remove from config.php line with:
```
'encryption.legacy_format_support' => true,
```
Maybe you need run `occ encryption:decrypt-all` before.

**Comment by andyxheli** [comment]
@sergey-dryabzhinsky do you have in your config.php

'encryption.legacy_format_support' => false,
'encryption.key_storage_migrated' => false,

**Comment by sergey-dryabzhinsky** [comment]
@andyxheli I was have in my config.php:
```
'encryption.legacy_format_support' => true,
'encryption.key_storage_migrated' => false,
```

After `occ encryption:migrate-key-storage-format` second line gone.
And after that - I removed first.

**Comment by andyxheli** [comment]
@sergey-dryabzhinsky please make sure it's set to false

**Comment by sergey-dryabzhinsky** [comment]
@andyxheli Put it into config. All looks good. Notification not appears.

**Comment by andyxheli** [comment]
@sergey-dryabzhinsky Perfect!

**Comment by sergey-dryabzhinsky** [comment]
Maybe documentation need to be updated to clarify these moments. Some FAQ at encryption section.
Or notification text should be expanded a little.

**Comment by andyxheli** [comment]
If you go to the following link is dose state changing the entry to false but it also says to remove it so it's confusing 

https://docs.nextcloud.com/server/20/admin_manual/configuration_files/encryption_migration.html

**Comment by sergey-dryabzhinsky** [comment]
But command `occ encryption:scan:legacy-format` don't exists in NC-20.
So yes, it's confusing.
These section need to be updated with step-by-step check-list and FAQ if something gone wrong.
