### ISSUE TITLE
regression Nc 20 Beta2 - universal search means no search in app store

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#22479]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

# No search in app store
The search icon in the top bar used to search apps so you can quickly install or enable the one you are looking for. As we have over 250 apps, this is pretty much a must-have... But it no longer works that way and there is no replacement yet.

A search on top of the left bar would do the trick, of course, but it has to be implemented :hammer: 

![Screenshot_20200828_222208](https://user-images.githubusercontent.com/551757/91612083-eecf4900-e97c-11ea-9ad9-126f34f8cf6c.png)

**Comment by raimund-schluessler** [comment]
It seems that there will be a global event when you type in the unified search box, see https://github.com/nextcloud/server/issues/22092#issuecomment-673369766. So the appstore could hook to this event and still use the unified search input to filter the apps.

**Comment by MorrisJobke** [comment]
Fixed in #22800 already
