### ISSUE TITLE
Share events: Allow users to share events to other calendars

### ISSUE THREAD

**Issue by k00ni** [nextcloud/server#22471]
I searched the issue tracker for this feature (and tried to find it in NC 18.x), but had no luck.

**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Users having personal calendars should be able to share certain events with other (owned or subscribed) calendars. Foreign events could be read-only to anyone but the sharer.

**Use Case**: An organization wants to maintain a personnel calendar where everyone posts vacation times, for instance. Instead of having to maintain multiple calendars (where they might change other events), they prefer personnel working in a personal calendar and share events.

**Additional context**
A client of mine needs this feature within 3 months. I don't know how such requests are handled here, I hope its the right place to ask. There is some budget available for anyone who is willing to implement that. I saw issues using bountysource.com to provide a bounty for developers, but I am not familiar with it.

**Comment by kesselb** [comment]
> I don't know how such requests are handled here

1. @nextcloud/calendar decides if this feature is acceptable
2. One has to build it ;)

We are not using bountysource.com anymore due: https://help.nextcloud.com/t/dont-use-bountysource-anymore/84943. 
For some people at tool like https://www.absence.io might work. I think they have a option to export vacations as calendar.

**Comment by georgehrke** [comment]
> 1. @nextcloud/calendar decides if this feature is acceptable

If you want to share individual events, invite people as attendees and they will receive any update to it.

In the very early days, we had this, but it caused many issues:
- Every user would get two additional calendars:
  - Individually shared events that are writable
  - Individually shared events that are read-only
  (Which in itself is very weird and unexpected)
- What does deleting an event mean?
  - Actually deleting or do i just want to unshare it from myself
- ...

**Comment by kesselb** [comment]
> An organization wants to maintain a personnel calendar where everyone posts vacation times, for instance. Instead of having to maintain multiple calendars (where they might change other events), they prefer personnel working in a personal calendar and share events.

It seems this feature is not on the roadmap. An alternative approach could be to implement this feature (vacation booking) as app and expose the calendar to the manager. 

A similar feature for deck is already in development (https://github.com/nextcloud/deck/pull/1545) so some of the required apis are already there. If you are looking for a freelancer: https://help.nextcloud.com/c/nextcloud-freelancing/48.

**Comment by k00ni** [comment]
Thank you for the feedback.
