### ISSUE TITLE
Data too long for column 'subjectparams'

### ISSUE THREAD

**Issue by kehrlein** [nextcloud/server#22487]
### Steps to reproduce
Create a new calendar event
(since upgraded vom NC 18.x to 19.0.2)

### Expected behaviour
Event should be created and synced / shown in all other calendar clients using this WebDAV calendar

### Actual behaviour
Event is beeing created and shown in the client who created the event. But the new event is not showing up in any other clients, using this WebDAV calendar.
Behaviour can be reproduced while creating it in the nextcloud web frontend, iOS calendar app and macOS calendar app.

**Log shows database error**
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'subjectparams' at row 1 
See full error message below.

**My debugging results**
Column 'subjectparams' in table 'oc_activity' is type varchar(255) and too small for the new record.

**Fix**
ALTER TABLE oc_activity CHANGE 'subjectparams' 'subjectparams' varchar(500) COLLATE utf8mb4_bin NOT NULL;
-> errors disapper and all new events are beeing synced.

### Server configuration

**Operating system:**
Debian 10

**Web server:**
apache 2.4.38

**Database:**
mariadb 10.3.23

**PHP version:**
7.3.19

**Nextcloud version:** 
19.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded vom NC 18.x to 19.0.2

#### Nextcloud log
<details>
<summary>Nextcloud log</summary>

[webdav] Fatal: Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_activity` (`app`, `subject`, `subjectparams`, `message`, `messageparams`, `file`, `link`, `user`, `affecteduser`, `timestamp`, `priority`, `type`, `object_type`, `object_id`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["dav", "object_add_event", "{\"actor\":\"martin.mustermann\",\"calendar\":{\"id\":10,\"uri\":\"private\",\"name\":\"Private\"},\"object\":{\"id\":\"40074b2e-936d-449c-88bf-2fc3a8735f7c\",\"name\":\"Test Event\",\"classified\":false,\"link\":{\"object_uri\":\"5BDC2BA3-AEC5-42FE-9BCC-50660DAEACDD.ics\",\"calendar_uri\":\"private\",\"owner\":\"martin.mustermann\"}}}", "", "[]", "", "", "martin.mustermann", "other.username", 1598698202, 30, "calendar_event", "calendar", 10]:

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'subjectparams' at row 1 at <<closure>>

 0. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 169
    Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException("An exception oc ... 1", Doctrine\DBAL\Dr ... ]})
 1. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php line 145
    Doctrine\DBAL\DBALException::wrapException(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "An exception oc ... 1")
 2. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php line 1063
    Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Doctrine\DBAL\Driver\PDOMySql\Driver {}, Doctrine\DBAL\Dr ... ]}, "INSERT INTO `oc ... )", {1: "dav",2: "ob ... 0})
 3. /var/www/nextcloud/lib/private/DB/Connection.php line 214
    Doctrine\DBAL\Connection->executeUpdate("INSERT INTO `oc ... )", ["dav","object_a ... 0], [2,2,2,2,2,2,2,2,2,2,2,2,2,2])
 4. /var/www/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php line 203
    OC\DB\Connection->executeUpdate("INSERT INTO `oc ... )", {app: "dav",type ... "}, [])
 5. /var/www/nextcloud/lib/private/DB/QueryBuilder/QueryBuilder.php line 216
    Doctrine\DBAL\Query\QueryBuilder->execute()
 6. /var/www/nextcloud/apps/activity/lib/Data.php line 101
    OC\DB\QueryBuilder\QueryBuilder->execute()
 7. /var/www/nextcloud/apps/activity/lib/Consumer.php line 76
    OCA\Activity\Data->send(OC\Activity\Event {})
 8. /var/www/nextcloud/lib/private/Activity/Manager.php line 149
    OCA\Activity\Consumer->receive(OC\Activity\Event {})
 9. /var/www/nextcloud/apps/dav/lib/CalDAV/Activity/Backend.php line 473
    OC\Activity\Manager->publish(OC\Activity\Event {})
10. /var/www/nextcloud/apps/dav/lib/AppInfo/Application.php line 235
    OCA\DAV\CalDAV\Activity\Backend->onTouchCalendarObject("object_add_event", {id: "10",uri: " ... "}, [{href: "princip ... }], {id: "4205",uri: ... 0})
11. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 264
    OCA\DAV\AppInfo\Application->OCA\DAV\AppInfo\{closure}("*** sensitive parameters replaced ***")
12. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 239
    Symfony\Component\EventDispatcher\EventDispatcher->doDispatch([Closure {}], "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
13. /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php line 73
    Symfony\Component\EventDispatcher\EventDispatcher->callListeners([Closure {}], "*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
14. /var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php line 70
    Symfony\Component\EventDispatcher\EventDispatcher->dispatch("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
15. /var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php line 1096
    OC\EventDispatcher\SymfonyAdapter->dispatch("*** sensitive parameter replaced ***", "*** sensitive parameter replaced ***")
16. /var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/Calendar.php line 202
    OCA\DAV\CalDAV\CalDavBackend->createCalendarObject("10", "5BDC2BA3-AEC5-4 ... s", "BEGIN:VCALENDAR ... R")
17. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1104
    Sabre\CalDAV\Calendar->createFile("5BDC2BA3-AEC5-4 ... s", "BEGIN:VCALENDAR ... R")
18. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 527
    Sabre\DAV\Server->createFile("calendars/sandr ... s", "BEGIN:VCALENDAR ... R", null)
19. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
20. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:PUT", [Sabre\HTTP\Requ ... }])
21. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
22. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
23. /var/www/nextcloud/apps/dav/lib/Server.php line 320
    Sabre\DAV\Server->exec()
24. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
25. /var/www/nextcloud/remote.php line 167
    require_once("/var/www/ownclo ... p")

PUT /nextcloud/remote.php/dav/calendars/martin.mustermann/private/5BDC2BA3-AEC5-42FE-9BCC-50660DAEACDD.ics
from 185.16.17.18 by martin.mustermann at 2020-08-29T10:50:02+00:00

</details>

**Comment by kesselb** [comment]
cc @nickvergessen @georgehrke

**Comment by nickvergessen** [comment]
Actually the field should be of type text and be able to store up to 64k chars.
https://github.com/nextcloud/activity/blob/master/lib/Migration/Version2006Date20170808154933.php#L81-L83

It used to be 4k chars before that until 4 years ago with Nextcloud 11.

Did you move your instance from an server to another, or update from sqlite? But anyway this is somethign for the forums

**Comment by kehrlein** [comment]
> Did you move your instance from an server to another, or update from sqlite?

No & no.
But: Migrated from OwnCloud several years ago and did multiple major updates of NC since.

**Comment by fnordsh** [comment]
> > Did you move your instance from an server to another, or update from sqlite?
> 
> No & no.
> But: Migrated from OwnCloud several years ago and did multiple major updates of NC since.

Same here, and I get the same error.
