### ISSUE TITLE
Logging in and Nextcloud 19, page doesn't redirect at chrome browser.

### ISSUE THREAD

**Issue by thetthet7** [nextcloud/server#22484]
Logging in and Nextcloud 19, page doesn't redirect at chrome browser.

![image](https://user-images.githubusercontent.com/3530387/91632340-99705780-e9cf-11ea-9b5a-ef5d6f178d30.png)

**Comment by kesselb** [comment]
Are you able to reproduce the problem with https://try.nextcloud.com?

**Comment by KhinNoe** [comment]
![image](https://user-images.githubusercontent.com/3530387/91634263-0b1ec480-ea15-11ea-8716-09fcac5fe488.png)
I can login with chrome for demo.

**Comment by moroq** [comment]
Also have this issue.
Error page 500 appears not only on login, but exactly on index page. Seems like NC is not redirecting correctly to /app/files. But if I go to https://myserver/app/files - everything is ok, server works as expected.
There is error in logs
`Error: Call to undefined method OCP\App::checkAppEnabled()
/var/www/nextcloud/lib/private/Route/Route.php - line 156:

require_once()

<<closure>>

OC\Route\Route->OC\Route\{closure}("*** sensiti ... *")

/var/www/nextcloud/lib/private/Route/Router.php - line 297:

call_user_func()

/var/www/nextcloud/lib/base.php - line 1012:

OC\Route\Router->match()

/var/www/nextcloud/index.php - line 37:

OC::handleRequest()`

**Comment by moroq** [comment]
SOLVED

This outdated method can be used in third party apps. In my case it was Twain scanner. As it wasn't useful anyway - disabling app solved redirection problem.
Check your apps and plugins.
