### ISSUE TITLE
[NC20 beta2] logreader broken

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#22489]
### Steps to reproduce
1. open index.php/settings/admin/logging

### Expected behaviour
Log entries should be displayed

### Actual behaviour
Since beta1 the logreader under index.php/settings/admin/logging is broken.

console error: 
```
Uncaught TypeError: can't access property "logreader", OCA.Search is undefined
    <anonymous> index.js:21
    <anonymous> main.js:19
    Webpack 5
        r
        <anonymous>
        r
        <anonymous>
        <anonymous>
index.js:21:23

```

### Server configuration

**Operating system:** Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 20.0.0 beta2

**Updated from an older Nextcloud 19 -> 20.0.0 beta1 -> beta2**

**Comment by kesselb** [comment]
cc @icewind1991 🙋‍♂️

**Comment by dartcafe** [comment]
Back in beta3 🙏
