### ISSUE TITLE
[20 beta 2] Toggle status CSS problem

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#22506]
On firefox 80 with Linux toggle status goes outside of the window.

My monitors default resolution is 4k, but it happens when in window mode as well.

![statuses](https://user-images.githubusercontent.com/7935624/91671168-028fc200-ead9-11ea-8566-a7ec224a3488.jpg)

**Comment by raimund-schluessler** [comment]
I also saw that on my testing instance. The status select popover is contained within the parent popover. Might be fixed with updating nextcloud-vue library.

**Comment by raimund-schluessler** [comment]
Seems like this is fixed in latest master:

<img width="195" alt="status" src="https://user-images.githubusercontent.com/2496460/92156969-09e10380-ee2a-11ea-95e6-e66fd41b5bf5.png">

Please report if it is still an issue for you.
