### ISSUE TITLE
 "enforcing two-factor authentication"  Admin account locked out

### ISSUE THREAD

**Issue by jpalcantara** [nextcloud/server#22501]
Hello,

  I made an error enabling  "enforcing two-factor authentication" and as a result I am locked out of the account.
I tried to restore the DB KO and now all my account are locked
I have version 18.of NC installed on a synology DSM and worked very well until this morning
I found some instruction by running this line to get the 2nd authentication to be disabled.  No luck 
sudo -u http php72 occ app:disable twofactor_totp
it asked for a password then I get this:

HP Warning:  PHP Startup: Unable to load dynamic library 'mcrypt.so' (tried: /usr/local/lib/php72/modules/mcrypt.so (/usr/local/lib/php72/modules/mcrypt.so: cannot open shared object file: No such file or directory), /usr/local/lib/php72/modules/mcrypt.so.so (/usr/local/lib/php72/modules/mcrypt.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library 'mysql.so' (tried: /usr/local/lib/php72/modules/mysql.so (/usr/local/lib/php72/modules/mysql.so: cannot open shared object file: No such file or directory), /usr/local/lib/php72/modules/mysql.so.so (/usr/local/lib/php72/modules/mysql.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
Could not open input file: occ

I would like to get this resolved and understand the issue.  Otherwise, I need to get everything off it and restart over. 
Thanks

**Comment by Dragon988** [comment]
Contact your system administrator or IT support tech for your PHP issue.

Regarding your two factor issue you can use occ to sort this out. I'd probably just generate a one time code for the admin user using occ.

**Comment by jpalcantara** [comment]
Or may you can just edit the config.ini file and set this   'twofactor_enforced' => 'false',    Instead of just reading the actually dialog of NC.
