### ISSUE TITLE
[20 Beta 2] Comments go outside of textbox.

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#22505]
Using firefox 80 on Linux. When leaving a comment on a file if the text is longer then the new comment box it goes outside of the box indefinitely.

I'm not sure if this has been addressed but don't see anything on the latest commits.

**Comment by jospoortvliet** [comment]
Try clicking the comment? here on Chrome that makes the size of the box fit the length of the text.

**Comment by szaimen** [comment]
As I cannot reproduce the original issue anymore, I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen. The latest version can be seen by checking [https://nextcloud.com/install/#install-clients](https://nextcloud.com/install/#install-clients) and [https://nextcloud.com/install/#instructions-server](https://nextcloud.com/install/#instructions-server) respectively.
