### ISSUE TITLE
Dark theme not working correctly on some drop down/ pop-up boxes

### ISSUE THREAD

**Issue by jayjay991** [nextcloud/server#22525]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Apply Dark Theme on Nextcloud (Settings > Accessibility > Enable Dark Theme)
2. Open Maps App
3. Click the directions search icon and see the mismatched colouring

or

1. Apply Dark Theme on Nextcloud (Settings > Accessibility > Enable Dark Theme)
2. Open Settings > Logging
3. Click the "Level" sort icon

### Expected behaviour
Tell us what should happen

White areas should be dark - should be able to read the text and drop down suggestions

### Actual behaviour
Tell us what happens instead:

Large white space makes reading text difficult

### Server configuration

**Operating system:**

Linux 5.4.0-40-generic x86_64
(Ubuntu 20.04)

**Web server:**

Nginx 1.19.0 (Alpine - Docker)

**Database:**

MariaDB 10 (Docker)

**PHP version:**

7.4

**Nextcloud version:** (see Nextcloud admin page)

19.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated from 19.0.0

**Where did you install Nextcloud from:**

DockerHub

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

[Run: docker exec --user www-data nextcloud php occ app:list]

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - audioplayer: 2.11.2
  - bruteforcesettings: 2.0.0
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.3.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.0.5
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.0.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - maps: 0.1.6
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - phonetrack: 0.6.4
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - ransomware_protection: 1.7.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.3
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "<NC server ip address>"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "http:\/\/<NC server ip address>\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "loglevel": 0,
        "maintenance": false,
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

There are no commands defined in the "ldap" namespace.

### Client configuration
**Browser:**
Firefox 79

**Operating system:**
Windows 10

**Maps**
![Screenshot (17)](https://user-images.githubusercontent.com/34886607/91756819-47912280-ebc5-11ea-9c0f-e61902d27ae1.png)

**Settings > Logging > Levels Sort**
![Screenshot (18)](https://user-images.githubusercontent.com/34886607/91756912-714a4980-ebc5-11ea-9dd8-8e279def9068.png)

**Comment by skjnldsv** [comment]
Hi,
Please search and open issues to the relevant repositories directly :)
https://github.com/nextcloud/maps
https://github.com/nextcloud/logreader

Cheers!
