### ISSUE TITLE
Nextcloud 19.2 Cannot modify header information - headers already sent by (output started at /var/www/nextcloud/3rdparty/sabre/http/lib/Sapi.php:112

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#22529]
![image](https://user-images.githubusercontent.com/59488153/91781494-16622380-ebc0-11ea-820d-690105471383.png)
![image](https://user-images.githubusercontent.com/59488153/91781526-2843c680-ebc0-11ea-9a74-53c156061be5.png)

**Comment by kesselb** [comment]
Duplicate of #22509
