### ISSUE TITLE
Can you add an option to disable nextcloud doing CSP

### ISSUE THREAD

**Issue by mdosch** [nextcloud/server#22536]
I realized that the CSP for my nexctloud is [broken](https://csp-evaluator.withgoogle.com/?csp=https://oc.mdosch.de) even when I removed all of my settings. AFter some research I found that nextcloud is setting some CSP itself.

I removed all my CSP headers and it is still broken so I assume it's the included one being broken.

I'd prefer to control my CSP myself via nginx like I do for all other websites and webapps so I kindly ask you to add an option to disable the CSP by nextcloud.

**Comment by kesselb** [comment]
Looks related to https://github.com/nextcloud/server/issues/14980

cc @rullzer

**Comment by szaimen** [comment]
cc @nextcloud/security is this feasible?

**Comment by LukasReschke** [comment]
I don't think that's something that we will officially support.
