### ISSUE TITLE
Split caching

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#22542]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Hi! Is there a way, how caching can be splitted? When you're using CDN it's better to give browser content (css, js, static common images) from the closest server. But in case, if there only one global storage and a lot of CDN servers, better will be to split caching: CDN Redis will provide interface files, and global Redis (near storage) will handle user's files and locks.

**Comment by Dragon988** [comment]
Try help.nextcloud.com for server configuration questions.

**Comment by krakazyabra** [comment]
@Dragon988, please read carefully. The question is not about configuration. Currently in NC there is only one method to put objects in redis. And everything will be put there. And I'm talking about splitting of flows: web-interface files in one flow, user's files/locks - in another.

**Comment by Dragon988** [comment]
You're going to need to provide some details on your nextcloud configuration.

CDN is typically a reverse proxy configuration with one or two origin servers. http cache mirrors work great for that setup. What are you trying to do here?

**Comment by krakazyabra** [comment]
Nextcloud with S3 primary handles interface files in zero-bucket. So, files are cached by cache-server. Web-server receives files from nextcloud. Nextcloud receives them from cache server. Web-server caches them in his own cache-server. This is how now working NC. 
I suggest to make separate method, where interface files will be in another location (not in zero-bucket on default storage). This idea came to me after this issue https://github.com/nextcloud/server/issues/22250. Seems, that NC with S3 default cannot work well with interface files, which are in default redis.

**Comment by Dragon988** [comment]
Transactional file locking should be disabled with S3 as primary.

**Comment by krakazyabra** [comment]
@Dragon988 This doesn't work. There are still problems with loading the page: 
```
NOTICE: PHP message: {"reqId":"8HWNSvI6yXUo3rjmUXCR","level":3,"time":"2020-09-03T17:08:34+02:00","remoteAddr":"10.36.129.181","user":"domain-auth-dd64c489-a84c-4648-a4d4-c22a46d261bc","app":"cssresourceloader","method":"GET","url":"/apps/files/","message":"Could not find resource css/server.css to load","userAgent":"Mozilla/5.0 (Windows) mirall/2.6.5stable-Win64 (build 20200710) (Nextcloud)","version":"19.0.1.1"}
```

**Comment by Dragon988** [comment]
> @Dragon988 This doesn't work. There are still problems with loading the page:

Then you need to file a separate bug report about that issue. Let's not derail this ticket.

> better will be to split caching: CDN Redis will provide interface files, and global Redis (near storage) will handle user's files and locks.

With transitional file locking disabled that should eliminate the need of the latter part of this ticket. That leaves your desire to have a CDN redis, which is a server configuration issue and not a nextcloud issue.

Keep in mind there are many many ways to cache content and redis is just one way to do so.

**Comment by jospoortvliet** [comment]
In general, if you set up the type of server where you have the need to split up the cache - get a subscription so our engineers can help you in their work time, don't rely on volunteers.

We have Global Scale, but it doesn't do this exactly - and currently I don't think Nextcloud supports anything like this. If you need it - get in contact with sales. I'll leave the issue open to track this as a feature, but I doubt this will be developed unless somebody volunteers for it or a customer asks us for it.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
