### ISSUE TITLE
[19.0.2] Previews sent over SMS on android corrupt

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#22544]
## Issue

Some of the previews viewed in mobile browser appear corrupted.

This does not happen on the desktop and is not visible on the desktop even with the same sharing link that is corrupted on mobile.

## Steps to reproduce

1. Generate image share link
2. Send image share link over android messaging system via SMS to your contact. Do not view image prior to this.
3. Your phone automatically shows the "preview" sent over SMS. The corrupt image is generated now.
4. Corrupt preview is visible on the SMS preview image.
5. View image on mobile browser to confirm corrupted preview.

## Expected behaviour
Preview is generated correctly

## Actual behaviour
Preview is corrupted on mobile browser.

## Browsers
Both on android firefox 80 and chrome.

**Server configuration**

Operating system:
Arch

Web server:
Nginx Mainline

Database:
Postgresql 12

PHP version:
PHP-FPM 7.4

Nextcloud version: (see Nextcloud admin page)
19.0.2

Updated from an older Nextcloud/ownCloud or fresh install:
Fresh

Where did you install Nextcloud from:
Nextcloud website

Are you using external storage, if yes which one: local/smb/sftp/...
No

Are you using encryption: yes/no
No

**Shared desktop browser:**

![Screenshot_20200901_183925](https://user-images.githubusercontent.com/7935624/91922308-846f1f00-ec82-11ea-980c-23acea396b2a.jpg)

**Shared mobile browser:**

![Screenshot_20200901_183142](https://user-images.githubusercontent.com/7935624/91922322-8cc75a00-ec82-11ea-8984-33ebfdd5cb23.jpg)

**Comment by Dragon988** [comment]
Mobile (prior to pressing to enlarge):

![see1](https://user-images.githubusercontent.com/7935624/91923847-30663980-ec86-11ea-815e-642027c1d6e4.jpg)


Mobile (after enlarging):

![see2](https://user-images.githubusercontent.com/7935624/91923851-33f9c080-ec86-11ea-944e-ad6a95a26f16.jpg)


Desktop (enlarged):

![see3](https://user-images.githubusercontent.com/7935624/91923902-4ecc3500-ec86-11ea-836d-3f0126e9e29b.jpg)

**Comment by Dragon988** [comment]
cc @nextcloud/viewer

**Comment by Dragon988** [comment]
cc @skjnldsv

**Comment by Dragon988** [comment]
Experimented some more. Found out exactly how to replicate this issue:

Generate image share link

Send image over android messaging system via SMS to your contact. Do not view image prior to this.

Your phone automatically shows the "preview" sent over SMS. The corrupt image is generated now.

Corrupt preview is visible on the SMS preview image.

View image on mobile browser to confirm corrupted preview.

**Comment by skjnldsv** [comment]
cc @rullzer

**Comment by rullzer** [comment]
Could you get me the example image.
And the access logs of the previews that are requested?

Since my phone does not do previews for sms.

**Comment by Dragon988** [comment]
I'll attach an example an image but after figuring out how to replicate this it happens to every image sent. I'll update the title to reflect this.

nextcloud.log, no errors.

Access.log:

```
duper-ip - - [02/Sep/2020:08:04:04 -0700] "POST /apps/text/session/sync HTTP/1.1" 200 248 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"
super-duper-ip - - [02/Sep/2020:08:04:10 -0700] "GET /s/dBTgWpnwX8K4QqE HTTP/1.1" 200 2899 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)"
super-duper-ip - - [02/Sep/2020:08:04:10 -0700] "GET /apps/files_sharing/publicpreview/dBTgWpnwX8K4QqE?x=200&y=200&file=/IMG_20180218_171323.jpg HTTP/1.1" 200 23927 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)"
super-duper-ip - - [02/Sep/2020:08:04:10 -0700] "GET /s/dBTgWpnwX8K4QqE/preview HTTP/1.1" 200 545694 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)"
duper-ip - - [02/Sep/2020:08:04:10 -0700] "POST /apps/text/session/sync HTTP/1.1" 200 249 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"
super-duper-2-ip - - [02/Sep/2020:08:04:11 -0700] "GET /s/dBTgWpnwX8K4QqE HTTP/1.1" 200 2904 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)"
super-duper-2-ip - - [02/Sep/2020:08:04:11 -0700] "GET /apps/files_sharing/publicpreview/dBTgWpnwX8K4QqE?x=200&y=200&file=/IMG_20180218_171323.jpg HTTP/1.1" 200 23927 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36 Google (+https://developers.google.com/+/web/snippet/)"
duper-ip - - [02/Sep/2020:08:04:17 -0700] "POST /apps/text/session/sync HTTP/1.1" 200 249 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0"
```
![IMG_20181013_130653](https://user-images.githubusercontent.com/7935624/92001613-bf5d6b00-ecf3-11ea-93ec-ea2f322a8807.jpg)

![Screenshot_20200902-080814(1)](https://user-images.githubusercontent.com/7935624/92001788-fb90cb80-ecf3-11ea-8eb1-10e51c1894ec.png)

**Comment by Dragon988** [comment]
![Screenshot_20200902-081445](https://user-images.githubusercontent.com/7935624/92002269-8671c600-ecf4-11ea-8514-820ad3cff73d.png)

**Comment by acsfer** [comment]
@rullzer you can install https://play.google.com/store/apps/details?id=com.google.android.apps.messaging it will do previews.

**Comment by skjnldsv** [comment]
PLease also share the generated previews of this file (in the data/appdata_xxx/, search recursively for the file id, this is how the folder is named)

**Comment by Dragon988** [comment]
@skjnldsv The previews are generated correctly on the backend. In this case, this corrupted image above shows as 2048-1536-max.jpg on the mobile browser.

![stuff5](https://user-images.githubusercontent.com/7935624/92037493-b33ed100-ed26-11ea-8f13-f51b07979087.jpg)

**Comment by skjnldsv** [comment]
@Dragon988 this seems like a weird bug to me!
@rullzer maybe we should load the screen size preview like we do in viewer?

**Comment by skjnldsv** [comment]
@Dragon988 what about saving the broken image by long pressign and `save as` ?
Can you compare the hashes of the server one and the downloaded one?

**Comment by Dragon988** [comment]
@skjnldsv They have different checksums.

And unless I'm doing this wrong the one on the phone doesn't exist on the server at all.

```
primary /mnt/primary/drive/appdata_ocrjpfqyar4p # find . -type f -exec sha1sum {} \; | grep '19cb75c03fed1d5734560c358006ffb2aa492e2d'
primary /mnt/primary/drive/appdata_ocrjpfqyar4p # 
```

**Comment by Dragon988** [comment]
@skjnldsv Nope, that command works. The preview doesn't exist.

**Comment by Dragon988** [comment]
@skjnldsv Also doesn't exist on my cache mirror which rules that out.

**Comment by Dragon988** [comment]
Have verified with another phone, same problem. It's not a cached image on the phone.

**Comment by Dragon988** [comment]
@skjnldsv @rullzer This does not happen on apple phones.

**Comment by Dragon988** [comment]
I'm going to go sulk for wasting everyones time. It actually is a cache issue, typical.

Apologies..

**Comment by skjnldsv** [comment]
No worries! I like those bug reports ;)
