### ISSUE TITLE
Nextcloud security problem

### ISSUE THREAD

**Issue by PiotrIr** [nextcloud/server#22559]
I would like to allow company internal users to have full access to Nextcloud using sync client and WebDAV but external users should be able to use only website. I know, I can’t achieve this using Nextcloud interface but if I will set reverse proxy between Nextcloud server and internet and block some URLs (responsible for sync client and web daw) for external users – is it possible? If so, could you tell me what should be blocked please?

**Comment by kesselb** [comment]
> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

The above note is from the issue template. I find your "bug report" super cheeky because:

- It's a question not a bug report
- You are using click-baiting to get attention (https://help.nextcloud.com/t/block-urls-on-reverse-proxy/91340)
