### ISSUE TITLE
Trash icons with deleted files for different states

### ISSUE THREAD

**Issue by gorsing** [nextcloud/server#22576]
There is a request that the displayed information is full or not the basket with deleted files. Quotas are set for each user. In addition to the fact that files are counted, the quota also includes files in the recycle bin. This functionality is very important.

3 states would be optimal.
icon when filling
1)> 20%
2)> 60%
3)> 80%

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
