### ISSUE TITLE
No writing permissions when there are several groups with different permissions at shared calenders

### ISSUE THREAD

**Issue by nova-os** [nextcloud/server#2260]
### Steps to reproduce

1.  Add two groups. One has write and read, the other has readonly
2.  Add one user to both groups

### Expected behaviour

User should be able to edit the calender.

### Actual behaviour

User can only view calender and has no permission to write.

### Server configuration

**Operating system**:  
linux  
**Web server:**  
apache  
**Database:**  
mysql  
**PHP version:**  
5.6  
**Server version:** (see your admin page)  
10.0.1  
**Calendar version:** (see the apps page)  
1.4.0  
**Updated from an older installed version or fresh install:**  
fresh installed  
**Signing status (ownCloud/Nextcloud 9.0 and above):**

    Login as admin user into your cloud and access 
    http://example.com/index.php/settings/integrity/failed 
    paste the results here.

No errors have been found.  
**List of activated apps:**

    If you have access to your command line run e.g.:
    sudo -u www-data php occ app:list
    from within your instance's installation folder

Enabled:

*   activity: 2.3.2
*   calendar: 1.4.0
*   comments: 1.0.0
*   contacts: 1.4.0.0
*   dav: 1.0.1
*   federatedfilesharing: 1.0.1
*   federation: 1.0.1
*   files: 1.5.2
*   files_pdfviewer: 0.8.1
*   files_sharing: 1.0.0
*   files_texteditor: 2.1
*   files_trashbin: 1.0.0
*   files_versions: 1.3.0
*   files_videoplayer: 0.9.8
*   firstrunwizard: 1.1
*   gallery: 15.0.0
*   notifications: 0.3.0
*   password_policy: 1.0.0
*   provisioning_api: 1.0.0
*   serverinfo: 1.1.1
*   survey_client: 0.1.5
*   systemtags: 1.0.2
*   theming: 1.0.1
*   updatenotification: 1.0.1
*   workflowengine: 1.0.1  
    Disabled:
*   admin_audit
*   encryption
*   external
*   files_accesscontrol
*   files_automatedtagging
*   files_external
*   files_retention
*   templateeditor
*   user_external
*   user_ldap
*   user_saml  
    **The content of config/config.php:**

    {
        "system": {
            "instanceid": "ocimemixhyjj",
            "passwordsalt": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "trusted_domains": [
                "xxx.de"
            ],
            "datadirectory": "\/usr\/www\/users\/wolkek\/data",
            "overwrite.cli.url": "http:\/\/xxx.de",
            "dbtype": "mysql",
            "version": "9.1.1.5",
            "dbname": "wolkek_db3",
            "dbhost": "localhost",
            "dbport": "",
            "dbtableprefix": "oc_",
            "dbuser": "***REMOVED SENSITIVE VALUE***",
            "dbpassword": "***REMOVED SENSITIVE VALUE***",
            "logtimezone": "UTC",
            "installed": true
        }
    }

**Are you using external storage, if yes which one:** local/smb/sftp/...  
no  
**Are you using encryption:** yes/no  
no  
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...  
no

#### LDAP configuration (delete this part if not used)

    With access to your command line run e.g.:
    sudo -u www-data php occ ldap:show-config
    from within your instance's installation folder

    Without access to your command line download the data/owncloud.db to your local
    computer or access your SQL server remotely and run the select query:
    SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';

    Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.

### Client configuration

**Browser:**  
chrome  
**Operating system:**  
macOS  
**CalDAV-clients:**  
Nextcloud

#### Web server error log

    Insert your webserver log here

#### Log file (data/owncloud.log)

    Insert your ownCloud.log file here

#### Browser log

    Insert your browser log here, this could for example include:

    a) The javascript console log
    b) The network log 
    c) ...

notify @nova-tb

**Comment by MorrisJobke** [comment]
cc @georgehrke @rullzer @schiessle

**Comment by georgehrke** [comment]
Duplicate,

@nickvergessen fixed this already.

**Comment by georgehrke** [comment]
original bug: https://github.com/nextcloud/server/issues/3677

fix: https://github.com/nextcloud/server/pull/3678

was also backported to Nextcloud 11
