### ISSUE TITLE
Unable to open status selection when scrolled down

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#22606]
Also, the status select popover moves out of the viewport when scrolling and flutters while scrolling. See here:

![status](https://user-images.githubusercontent.com/2496460/92301581-3baab500-ef65-11ea-9a26-d9822ed4f9c5.gif)

This is due to the `boundaries-element` being `body` which moves out of the viewport. The flutter is due to the container being `body` as well, which moves. See https://github.com/nextcloud/nextcloud-vue/issues/1384 for details.

Server version: latest master.

**Comment by raimund-schluessler** [comment]
I reopen this since we will likely revert #22614 in https://github.com/nextcloud/server/pull/22773.

**Comment by raimund-schluessler** [comment]
See my comment in https://github.com/nextcloud/nextcloud-vue/issues/1384#issuecomment-690569801. From my side there will be no solution to fix this other than setting `min-height: 100%`, sorry.

**Comment by raimund-schluessler** [comment]
So, how do we proceed here? Globally changing the CSS in server obviously is no solution as it breaks some apps at the moment. However, I think we still need to fix this issue, also for Nextcloud 20.

As only apps which use the default layout are affected by this, it might be a solution to fix this on a per app basis for now. I know this is more work, and not the ideal solution for something that should just work, but the advantage is we could check per app if something breaks.

Apps currently affected by this problem are (list is not exhaustive):
- Dashboard
- Files
- Activity
- Photos
- Contacts
- Settings

For all these apps adding
```css
body {
	min-height: 100%;
	height: auto;
}
```
like I did for Tasks in https://github.com/nextcloud/tasks/pull/1224 fixes the issue and I couldn't see any problems (but this sure needs more testing). Later on we could adjust apps which currently break with this style (e.g. Talk) to anyway work properly and move this CSS rule to server.

@nextcloud/vuejs What do you think?

**Comment by juliushaertl** [comment]
I agree that for 20 it makes most sense to fix this in the individual apps and then we can make the full height body a default on server master as a next step so it is in as a change early for 21. From a standardization perspective apps like talk and deck which have different scroll area can then apply a workaround for their custom implementation.

**Comment by jancborchardt** [comment]
For reference, after discussion meetings, we decided to move the statuses Online/Away/Dnd/Invisible into the modal and have a click on "Set status" open the modal directly. (The biggest reason being so that the "Status message" part is more obvious and not buried so deeply.)

So no dropdown anymore, and the problem will be gone. Ref @rullzer @nickvergessen @juliushaertl

**Comment by jancborchardt** [comment]
Will be fixed through pull request https://github.com/nextcloud/server/pull/23130
