### ISSUE TITLE
Make dashboard useable - predefined information

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/server#22609]
**Is your feature request related to a problem? Please describe.**
I have defined a few onboarding notes in a .md and it is shown in the main-tree of files. You see this after login. Works fine.

First thing someone sees after login should be her dashboard. But also the onboarding notes are critical.

**Describe the solution you'd like**
1. Give me as an admin the power to set some default widgets (for me it would be calendar, deck, announcements)
2. I then could set up a my announcements. This would be perfect.

**Describe alternatives you've considered**
Using first-run wizard, but it's not that practical for these notes.

**Comment by sunjam** [comment]
Do you mean sharing your Dashboard with other users?  Cause I'm wondering about that myself while testing 20.0.0beta3

**Comment by Dubidubiduu** [comment]
> 
> 
> Do you mean sharing your Dashboard with other users? Cause I'm wondering about that myself while testing 20.0.0beta3

Would also be fine, when it's the default board and I can share by groups (e.x. to my all-group).

In general, I do think about something like sharepoint, it's defined by special users for everyone.

**Comment by Dubidubiduu** [comment]
Making announcement center a default widget would be enough for the beginning.

**Comment by wiswedel** [comment]
> Give me as an admin the power to set some default widgets (for me it would be calendar, deck, announcements)

resolved by https://github.com/nextcloud/server/pull/25309

> I then could set up a my announcements.

You might wanna have a look at https://github.com/eneiluj/welcome (Readme wip [here](https://github.com/eneiluj/welcome/blob/e2fbbc60c0431fe1e19a950bb65416a0a1b0d114/README.md))

**Comment by Dubidubiduu** [comment]
Actually I don't understand #25309 yet, how do I config this?

**Comment by wiswedel** [comment]
> how do I config this?

yeah, sorry, documentation is still missing.
You configure it by occ command:

`occ config:app:set dashboard layout --value='recommendations,mail,calendar,spreed,welcome'` (example)

**Comment by Dubidubiduu** [comment]
> 
> 
> > how do I config this?
> 
> yeah, sorry, documentation is still missing.
> You configure it by occ command:
> 
> `occ config:app:set dashboard layout --value='recommendations,mail,calendar,spreed,welcome'` (example)

Once again, thank you!

So, bunch of users have logged in since dashboard came out. How do I set their dashboards, i.e. set default dashboard for all users, cuz this occ command haven't changed anything for my current user so I guess it's not changing anything for them either.

**Comment by wiswedel** [comment]
> How do I set their dashboards, i.e. set default dashboard for all users

`occ user:setting myUser dashboard layout --delete` (to reset a user's setting to system default)

`occ user:setting myUser dashboard layout 'welcome,spreed'` (to set an explicit user setting)

If you have direct DB access to issue an SQL query: `DELETE FROM oc_preferences WHERE appid='dashboard' AND configkey='layout'` (to reset all users' custom configs)

**Comment by Dubidubiduu** [comment]
Mhm, I do:
`./occ config:app:set dashboard layout --value='welcome,calendar,deck,spreed'`

which results in this oc_appconfig entry
`
  | dashboard | layout | welcome,calendar,deck,spreed
-- | -- | -- | --
`

Refreshing dashboard resets it, as expected, BUT in fact I get recommendations, spreed, mail and calendar widget.

How so?

NC 20.0.8
Dashboard 7.0.0

If dashboard gets documentated please also think of background settings.

**Comment by wiswedel** [comment]
> Refreshing dashboard resets it, as expected, BUT in fact I get recommendations, spreed, mail and calendar widget.

That's the hard-coded default if nothing is set in the database.

> NC 20.0.8
> Dashboard 7.0.0

The config key requires Nextcloud 21. Sorry I didn't mention that before.

**Comment by szaimen** [comment]
This is done on NC21 and above
