### ISSUE TITLE
Mail notification works only for new shares

### ISSUE THREAD

**Issue by sirio81** [nextcloud/server#2261]
### Steps to reproduce
1. Configure smtp to send e-mail notification
2. Create two users and add their e-mail address
3. In their profile check the 'Mail' option for all kinds of notifications
    (Check also 'Notify about your own actions via email'),
4. Share a folder form the first user to the second user
5. Do activities in such directory from both user (create, change, delete files)
    Do also activities in the users' own directories.
6. Check thei mail box after an hour

### Expected behaviour
I expect to find e-mail notification about users' activities.

### Actual behaviour
I only receive e-mail for the new shared folder.
No other action is notified.

### Server configuration
**Operating system**: debian 8

**Web server:** apache 2.4

**Database:** mariadb 10.0.28

**PHP version:** 5.6

**Nextcloud version:** 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** .zip

Note: before opening the bug I asked the [forum](https://help.nextcloud.com/t/mail-notification-works-only-for-new-shares/5269)

**Comment by nickvergessen** [comment]
Please make sure that cron jobs are executed correctly.

**Comment by sirio81** [comment]
I did and I also run it manually to be even more sure.

**Comment by nickvergessen** [comment]
There were two fixes with regards to the notification mails in 11.0 and 10.0.3. When the problem still exists for you, please open a new issue in the activity repository: https://github.com/nextcloud/activity/issues/new
