### ISSUE TITLE
20.0.0beta3 - sometimes Untested apps must be enabled twice

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22613]
Installed 20.0.0beta3 and notice that sometimes apps listed as Untested in the appstore must be enabled twice now.  Seems to be a small bug.

1.  `Enable Untested app`
2.  `Enable`

**Comment by Nils160988** [comment]
I think this is intentional. 
In the first step, you override the warning of the app being untested (this creates an entry in your config.php) and in the second step, you regularly enable the app.

**Comment by sunjam** [comment]
Well, for some apps it did Enable them immediately.  So, hasn't been consistent.  In the past, this has been a one-click operation.

**Comment by Nils160988** [comment]
Okay, haven't tried it for the last weeks. At least, it should be consistent (one or two clicks).

**Comment by kesselb** [comment]
> In the first step, you override the warning of the app being untested (this creates an entry in your config.php) and in the second step, you regularly enable the app.

Is the intended behavior: https://github.com/nextcloud/server/blob/27fbab131c153759c478d5ce28a7f62906ec4d62/apps/settings/lib/Controller/AppSettingsController.php#L554
