### ISSUE TITLE
Feature Request: Option to disable Backup prior to upgrade via web updater

### ISSUE THREAD

**Issue by sourcenux** [nextcloud/server#22645]
**Is your feature request related to a problem? Please describe.**
When doing an upgrade of nextcloud instances, that contain some gigabytes of data always take pretty long, because the web-updater seems to create a backup of all files contained in that instance. 

**Describe the solution you'd like**
I would like to see an option to disable creating backups prior to the upgrade, to use the web-updater in conjunction with larger instances. 

**Describe alternatives you've considered**
Obviously the recommended way to upgrade larger instances is to use the cli-based updater. But this is less convenient than using the web updater and it is also not a suitable way to upgrade, if you do not have shell access.

**Comment by kesselb** [comment]
Thanks for reaching out 👍

Closing your report in favor of 
https://github.com/nextcloud/updater/issues/285

**Comment by kesselb** [comment]
For the cli updater it's also possible to skip the backup (--no-backup) because most people have a backup anyway.

**Comment by LicoMonch** [comment]
> For the cli updater it's also possible to skip the backup (--no-backup) because most people have a backup anyway.

@kesselb 
```
$ sudo -u www-data php updater.phar --no-backup


  [Symfony\Component\Console\Exception\RuntimeException]
  The "--no-backup" option does not exist.


update
```

🤔🤔🤔

**Comment by kesselb** [comment]
https://github.com/nextcloud/updater/pull/292

It's new. Maybe not available for older releases yet.

**Comment by LicoMonch** [comment]
ah ok, I see, that was merged into 19 after the last release
thanks for the info
