### ISSUE TITLE
Fix invalid VCALENDAR data in DB!

### ISSUE THREAD

**Issue by rullzer** [nextcloud/server#2264]
As described in https://github.com/nextcloud/server/issues/2249

If we have invalid data in the DB this might fail at some point. We should fix the invalid VCALENDAR data properly!

**Comment by avanc** [comment]
I also got invalid calendar data in my DB. I read through the different pull request (for NC12, backport to NC11, etc). However, I have no idea how I have to do to repair the DB. @LukasReschke ,  can you give me some hint?
