### ISSUE TITLE
Add support for user notes

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#22655]
Can we get admin-only user notes added to individual users/profiles?

The user wouldn't be able to see them but the admin can. This might be useful for large organizations managing dozens of users.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
