### ISSUE TITLE
Nextcloud mistakenly gives an "internet not connected" warning even though it is

### ISSUE THREAD

**Issue by mobamoba** [nextcloud/server#2265]
I receive the following error on my Admin page: This server has no working Internet connection. This means that some of the features like mounting external storage, notifications about updates or installation of third-party apps will not work. Accessing files remotely and sending of notification emails might not work, either. We suggest to enable Internet connection for this server if you want to have all features.

Given that I'm actually accessing Nexcloud from the internet, this is clearly wrong, i.e. somehow the server is issuing a warning that it has no internet connection when it actually does and it's actually working.

This is obviously a very minor issue since nothing is really impacted. Still, a bug is a bug so I figured I'd report it.

### Server configuration
**Operating system**:
Ubuntu Xenial

**Web server:**
Apache
**Database:**
Mysql
**PHP version:**
7
**Nextcloud version:** (see Nextcloud admin page)
10.01
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
Tarball
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>
No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Well if you get this message, it means that none of the following sites could be reached:
* `www.nextcloud.com`
* `www.google.com`
* `www.github.com`

Your nextcloud.log file should held some information why so.

**Comment by mobamoba** [comment]
Maybe it was a transient DNS thing - ping was working fine but nslookup wasn't; a reboot solved it. Thanks.

**Comment by HLFH** [comment]
A `systemctl reboot` fixed it also for me.
