### ISSUE TITLE
Search can't be accessed from Safari on iOS and iPadOS

### ISSUE THREAD

**Issue by Volker-K** [nextcloud/server#22658]
### Steps to reproduce
1. Open Nextcloud with Safari on a mobile device
2. Log in
3. Tap on the search field

### Expected behaviour
Serach field opens and accepts input

### Actual behaviour
Opens while you touch it, closes when you release your finger.
Works fine on Android devices with Chrome and Firefox

### Server configuration
**Nextcloud version:** 
Occurs with both 18.0.3.0 and 19.0.0.12

### Client configuration
**Browser:**
Safari

**Operating system:**
iOS 13.6.1 and iPadOS 13.6.1
~~Verification with 13.7 will follow.~~
Update: With 13.7 a very, very, very short tap sometimes opens the search field. 

### Logs
Happens just inside the browser, no log entries found

**Comment by skjnldsv** [comment]
Fixed with new nextcloud 20 search
