### ISSUE TITLE
Users can delete shared folders without permissions

### ISSUE THREAD

**Issue by abolinhas** [nextcloud/server#2268]
### Steps to reproduce
1. Create a new folder and share with a group
2. Remove the all edit permissions
3. Login with the user of the group and delete the shared folder without permissions

### Expected behaviour
Without permissions the user of the group should not have the possibility to remove the shared folder

### Actual behaviour 
The users can delete shared folder without permissions
Check the video
https://florasul.pt/fileplace/wl/?id=h3P943oRsJJxPATWB0cdHaQwNeMM8im3

### Server configuration
**Operating system**:
CentOS release 6.8 (Final)

**Web server:**
Apache 2.2

**Database:**
MYSQL 5.5.52-cll

**PHP version:**
PHP 5.4

**Nextcloud version:** (see Nextcloud admin page)
10.0.1 (daily) Build:2016-11-23T00:01:11+00:00 fee91b10732cc93dea24bb9f9114457bc7968c5e

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by rullzer** [comment]
The delete permission isn't about receiving the share it is about the data in the share.

If userA shares a folder with userB. Then userA can't force userB to have that share. userB is free to delete the mountpoint of the share (and thus deleting the share). However what userB can't do is delete data in the folder.

**Comment by abolinhas** [comment]
In owncloud this behavior doesn't happens, the user b can't delete the mount point. In enterprise environment such feature its important. If I share a lot of folders with my employees I don't want that they have the option to delete the mount point in their areas. Any way to add such feature?

**Comment by abolinhas** [comment]
@rullzer In owncloud this behavior doesn't happens, the user b can't delete the mount point. In enterprise environment such feature its important. If I share a lot of folders with my employees I don't want that they have the option to delete the mount point in their areas. Any way to add such feature?

**Comment by mvisser00** [comment]
@rullzer, For me this was also unexpected behavior. We share a folder with our customers and I don't want them to have the option to delete the share. Is there any way to disable this or add this as a feature?  So in fact as user A you force userB to have and keep the share.

**Comment by detm54** [comment]
My company also needs such feature to prevent customers from deleting shared folders.
So I started some testing today (not a professional PHP coder at all) and discovered the **public function deleteFromSelf** in **$nextcloudroot/lib/private/Share20/Manager.php**.

At the moment it looks like I can achieve my goals with a simple line:

`if ($share->getShareOwner() !== 'admin-user') { do what you are supposed to do }`

Customers can still click on Unshare and the share will disappear but in case the file or folder has been shared by our cloud-admin nothing will happen (yeah, the share will still disappear but then you just need to refresh the website to get the share back).

What do you think?

**Comment by abolinhas** [comment]
@detm54 I achive my goal by creating a trigger on mysql

`CREATE TRIGGER `_UndoUserShareDeleteRename` BEFORE INSERT ON `oc_share`
 FOR EACH ROW BEGIN
		IF (NEW.permissions=0 and NEW.share_type=2) 
THEN 
        SIGNAL SQLSTATE '45000'
 SET MESSAGE_TEXT = 'Cannot unshare folder if not owner';
    END IF;	
IF (NEW.permissions=1 and NEW.share_type=2) 
THEN 
        SIGNAL SQLSTATE '45000'
 SET MESSAGE_TEXT = 'Cannot rename folder if not owner';
    END IF;	
END`

**Comment by dopenpc** [comment]
@abolinhas I've tested your solutions with Trigger but not work for me.
User can always unshare folders or files.
You have idea?
Thanks
