### ISSUE TITLE
Allow multiple SMTP servers 

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#2271]
Maybe I'm all wrong, but it seems like multiple SMTP servers aren't supported even though the documentation [says so](https://github.com/nextcloud/documentation/blob/master/admin_manual/configuration_server/email_configuration.rst)? 

- Have tried with the current master to set multiple hosts separated by semicolon for the 'mail_smtphost' parameter, but sending a test mail fails as the whole hosts string is treated as one host which obviously can't be connected to

- In the source code it doesn't look like Swiftmailer's multiple hosts features are used, e.g. Swift_FailoverTransport or Swift_LoadBalancedTransport...

Hope I'm wrong though as I would like to use the feature. Maybe someone can shed some light on this? Thanks :)

**Comment by nickvergessen** [comment]
Yeah, I didn't know this was ever supported. But shouldn't be too hard to bring it back in general I guess.
The only problem I see is, that all servers have to work with the same credentials etc.

If that is expected and enough, it can be easily added to https://github.com/nextcloud/server/blob/ba87db3fccb40aa58d84d12932424c83a4db411f/lib/private/Mail/Mailer.php#L180

**Comment by GitHubUser4234** [comment]
Hm, so was it actually there before and somehow got scrapped? :D

Yeah, for a start just covering what is written in the documentation sounds sufficient. And individual credentials, protocols etc. for each server could then for example be added as a further enhancement.

**Comment by nickvergessen** [comment]
> Hm, so was it actually there before and somehow got scrapped? :D

I'm not sure, if so it got killed with the introduction of swiftmailer in 8.0

**Comment by MorrisJobke** [comment]
@nickvergessen I would say we don't support it. Because it doesn't seem to work for a longer time, which means it isn't used at all :( Instead of adding more complexity here I would vote for adjusting the documentation.

**Comment by GitHubUser4234** [comment]
> I would say we don't support it. Because it doesn't seem to work for a longer time, which means it isn't used at all :( Instead of adding more complexity here I would vote for adjusting the documentation.

Well thing is, it at least works with only one SMTP server. But that doesn't mean backup servers wouldn't be needed.  When emails can't be sent out due to SMTP server failure, it indeed can have a critical impact especially on large scale projects. Having the option to employ backup servers isn't really that special, last but not least that's also why email providers offer more than one SMTP server for backup.

And as discussed above, it is not all that much effort to re-implement this feature. We would really need this on the long run, and I'm sure there are other Nextcloud users who would welcome the feature.

**Comment by MorrisJobke** [comment]
> And as discussed above, it is not all that much effort to re-implement this feature. We would really need this on the long run, and I'm sure there are other Nextcloud users who would welcome the feature.

We are happy about pull requests. But many people here are already doing other stuff that is also needed. As this doesn't work right now I would not rate this a bug but a wrong documentation. I will make this a enhancement ticket then :)

**Comment by GitHubUser4234** [comment]
> We are happy about pull requests. But many people here are already doing other stuff that is also needed. As this doesn't work right now I would not rate this a bug but a wrong documentation. I will make this a enhancement ticket then :)

Perfect, thanks :D

**Comment by szaimen** [comment]
I am going to close this since there doesn't seem to be a lot of interest (no upvotes) and no respond since around 2 years. Please reopen if you still want to implement this.
