### ISSUE TITLE
smb/cifs external storage bad performance when using hostname instead of IP

### ISSUE THREAD

**Issue by muzzol** [nextcloud/server#22728]
### Steps to reproduce
1. Create an external storage with type smb/cifs with a hostname: samba1.example.com
2. Acces files and see how long it takes to load every directory
3. Reconfigure and put IP instead of hostname: 192.168.1.100
4. Acces files again and see how long it takes now

### Expected behaviour
it should take the same time to access

### Actual behaviour
takes longer with hostname

### Server configuration

**Operating system:**
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic

**Web server:**
apache2                               2.4.29-1ubuntu4.13

**Database:**
postgresql-10                         10.12-0ubuntu0.18.04.1

**PHP version:**
php7.2-fpm                            7.2.24-0ubuntu0.18.04.3

**Nextcloud version:** (see Nextcloud admin page)
18.0.2

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
