### ISSUE TITLE
Webcron executes one background job at a time

### ISSUE THREAD

**Issue by soisik** [nextcloud/server#22730]
# Steps to reproduce
1. Set "Webcron" as background jobs in setting and set a service that call cron.php every 5 minutes over HTTP
2. Install an app that creates lot of jobs in oc_jobs (such as workflow_script in our case) 
3. Trigger new jobs to queue up in oc_jobs table

### Expected behaviour
All jobs should be executed every 5 minutes. 

One could expect webcron to reproduce a CLI execution of cron.php because :
- [Background jobs Documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html) and UI do not mention that jobs are executed one at a time in Webcron (while it does state so for AJAX mode) 
- [AJAX Documentation](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/background_jobs_configuration.html) recommands to use webcron or cron with some apps that seems to rely on jobs being executed promptly :
"Especially when using the Activity App or external storages, where new files are added, updated or deleted one of the two methods below should be preferred." which lead to believe that they can both efficiently handle the job queue fast.

### Actual behaviour
Jobs are executed one at a time, resulting in jobs that stays in the oc_jobs table for hours before getting executed.

Cron.php, when called using ajax or webcron, executes only one job, but if it is called using the CLI mode, it loops through and executes all awaiting job:

```php
if (OC::$CLI) {
       // Loop through jobList and executes all jobs 
        while ($job = $jobList->getNext()) {
			...
        }
} else {
       // Execute one job at a time:
	$jobList = \OC::$server->getJobList();
	$job = $jobList->getNext();
	if ($job != null) {
		$job->execute($jobList, $logger);
		$jobList->setLastJob($job);
	}
	OC_JSON::success();
}
```
### Server configuration
**Nextcloud version:** 18.0.8

**Comment by kesselb** [comment]
> All jobs should be executed every 5 minutes.
> Cron.php, when called using ajax or webcron, executes only one job, but if it is called using the CLI mode

Yes. Unfortunately we don't know how long the web server / php runtime keeps the process running. At worst they kill the request during a long running task. I think we could read the max_execution_time and run more jobs if the limit is high. Most jobs are pretty fast. But it's a optimization for a configuration we do not recommend anyway. The most reliable way is to use cron. No web server's involved and no execution time limits. Pull requests are always welcome. Feel free to hack around :sunglasses:

**Comment by MorrisJobke** [comment]
> Yes. Unfortunately we don't know how long the web server / php runtime keeps the process running. At worst they kill the request during a long running task. I think we could read the max_execution_time and run more jobs if the limit is high. Most jobs are pretty fast. But it's a optimization for a configuration we do not recommend anyway. The most reliable way is to use cron. No web server's involved and no execution time limits. Pull requests are always welcome. Feel free to hack around 😎

That sums it up.

The webcron is a default work around for setups where the cron.php can't be called from CLI. If you require the cron to be executed more often there are services in the internet that call a URL regularly which then would allow to execute the cron.php more often.

Or just configure the system cron job.

So I will close this as a won't fix.
