### ISSUE TITLE
New way to migrate a Nextcloud to a new server destination.

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#22732]
**Problem:**
I have an old Nextcloud with some hacky settings and missing database indices and wish anyway to migrate the Nextcloud server destination to a new one.

**As a solution I would propose this idea:**

- Install a new, fresh and clean Nextcloud. Setup all important Parameters.
- Set up the take-over procedure <-- To develop
- All connected User get Informed about the Change.
  - Web: Big Prompt 
  - Nextcloud App: Notification 
  - If encryption get deactivated:
   A content of this Message: `This Server change to a non per user encrypted Nextcloud, Please enter Password if you approve that`
- All Nextcloud connected Apps and Federation receive a change of Server Message and automatic move account server to the new location

**Take-over procedure**
(Only an Idea)
1. Migrate User database including encryption Keys
1. Ask Admin if missing Apps should get installed
1. If Encryption is not active on the new Nextcould -> "User Data only get transferred after the User approve this. - Are you sure you wish to deactivate Encryption here?"
1. Notification for changing deactivating encryption to Nextcloud Client and Website 
1. The Nextcloud server change immediately. Until the moment all data is transferred directories and Files are external storage link to the old Nextcloud. The moment the data transfer process receive a user account this account get temporary blocked. 
1. After all data is transferred this external storage link get replaced by the transferred, now local data.
1. User get again access to his account.

**Comment by Dragon988** [comment]
Baremetal install, full copy:

https://help.ubuntu.com/community/BackupYourSystem/TAR

Read backing up and restoring.

While migrating create a temporary website on another server that tells everyone maintenance is enabled.

Don't delete your old data until you confirm the transfer went smoothly.

You'll need to regenerate grub/grub-efi/fstab and initramfs and run grub-mkconfig on the new server.

That's all there is to it!

For further assistance try help.nextcloud.com.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/

**Comment by Mannshoch** [comment]
May could be based on https://github.com/nextcloud/user_migration
