### ISSUE TITLE
ocDownloader - Dark Mode

### ISSUE THREAD

**Issue by tobi614** [nextcloud/server#22735]
### Steps to reproduce
Enable Dark Mode under settings -> accessibility. Go to Main App "ocDownloader".

### Expected behaviour
Background is black. Font is white. 

### Actual behaviour
Faulty coloring. See picture.
![Error2](https://user-images.githubusercontent.com/64694684/92498720-441c1d80-f1fb-11ea-94f0-9f4ca84c1a17.JPG)

### Versions
Nextcloud: 19.0.1
ocDownloader: 1.7.8

**Comment by splitt3r** [comment]
I think https://github.com/e-alfred/ocdownloader/issues would be the best place for this issue.

**Comment by tobi614** [comment]
Thanks. I have opened there a new issue.
