### ISSUE TITLE
Calendar - Default Reminder for Birthsday Calendar

### ISSUE THREAD

**Issue by tobi614** [nextcloud/server#22738]
Since the "Contact Birthdays" calendar is read-only it is also not possible to set reminders for the birthdays which makes it easy to still miss these birthdays.

Could there be added a default reminder like one day in advance or something? I mean it's good to have the calendar but it's main purpose for me should be to help me not to forget birthdays which it now more or less only does by accident.

**Comment by tcitworld** [comment]
Duplicate from https://github.com/nextcloud/server/issues/1505
