### ISSUE TITLE
[Question - NC20] Reacting to OS dark mode?

### ISSUE THREAD

**Issue by dartcafe** [nextcloud/server#22740]
I am confused. While testing the polls app in public polls, the layout reacts to the OS settings regarding the dark or bright theme. If I activate dark mode in Windows, the whole site turns to a black background. This does not happen, if I am logged in. Is this a new function?

BTW: The text in the text box does not have enough contrast and is not readable.

OS: Windows 10
Browser: Firefox 80, Chrome, Edge (Chromium)
With dark mode on
![grafik](https://user-images.githubusercontent.com/26707476/92570272-f8f91d80-f281-11ea-891b-3839accc837a.png)
With dark mode off
![grafik](https://user-images.githubusercontent.com/26707476/92570362-1cbc6380-f282-11ea-93a0-65b86f7285e9.png)

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/pull/21366

**Comment by dartcafe** [comment]
Thanks. Didn't find that. So I think, I have to get a good idea to calculate the correct font color.
