### ISSUE TITLE
NC 18.0.6: Share folder without delete still allows delete on actions menu

### ISSUE THREAD

**Issue by joeltheukranian** [nextcloud/server#22756]
Ubuntu 18.0.4
NC 18.0.6

1. Create Group 1. Add user1
2. Create Group 2. Add user2
3. Login as user1. Go to Home folder. Share Folder folder1 to Group2. Uncheck delete
4. Login as user2. Go to folder1. Check box to left.
5. Click Actions. Why is Delete there? Note it's not there under "..."

Note if you click delete, user1 can still see folder1. What is delete doing?

**Comment by dkennerknecht** [comment]
"Delete" removes the Share created by user1

This allows users to delete unneeded shares from other users

**Comment by joeltheukranian** [comment]
Well that's confusing. "Delete share" might be more appropriate.

So only the owner can truly delete a folder they share to others?

**Comment by szaimen** [comment]
I think this is pretty clear:
![image](https://user-images.githubusercontent.com/42591237/121671347-baadba80-caae-11eb-846c-b29aa19b7515.png)
