### ISSUE TITLE
External Storage : all shares (public or not) are deleted if storage is temporarily unavailable

### ISSUE THREAD

**Issue by Ravinou** [nextcloud/server#22751]
# Steps to reproduce

1. create a public share on a file or on a folder in your external storage.
2. Open the link in a tab.
3. Make your external storage inaccessible (without deleting it in the nextcloud's external storage options, just make sure your nextcloud can't access it anymore by umount the point on your server for example).
4. Refresh your tab open on step 2. Normally there will be an error, and it's normal.
5. Make your external storage accessible again.
6. Now, public link open on step 2 is delete for me and all shares created in this external storage are deleted.

# Expected behaviour

Delete public link only if the external storage is delete. It can be check in the database. 

# Actual behaviour

Actually, Nextcloud check if the instance is up, if it's up Nextcloud delete all share create in the external storage :( 
Code is here : https://github.com/nextcloud/server/blob/0934aee46bee13d5ac4d62eae6fe5250c25192fb/apps/files_sharing/lib/External/Storage.php#L217
```
// valid Nextcloud instance means that the public share no longer exists
// since this is permanent (re-sharing the file will create a new token)
// we remove the invalid storage
```

# Server configuration

Operating system:
Debian GNU/Linux 10 (buster)

Web server:
2.4.38-3+deb10u4

Database:
MariaDB 10.3.23-0+deb10u1

PHP version:
PHP 7.3.19-1~deb10u1

Nextcloud version: (see Nextcloud admin page)
19.0.2

**Comment by szaimen** [comment]
Let us track this in https://github.com/nextcloud/server/issues/20995
