### ISSUE TITLE
Error when trying to create new User: Bad request

### ISSUE THREAD

**Issue by DerInternets** [nextcloud/server#22759]
New installation of nextcloud in docker. When trying to create a new user, i get an error message: 
"Es ist ein Fehler bei der Anfrage aufgetreten. Es kann nicht fortgefahren werden. Bad request"

Nextcloud Version 19.0.2
PHP Version: 7.3.22
DB: MariaDB (Version: 10.4.14)

**Comment by MorrisJobke** [comment]
Please check your logs for more details. This should contain the reason of the failure.

**Comment by DerInternets** [comment]
Nothing in the logs that I could find, reinstalled 3 more times. No Idea why, but the issue seems to be gone.
