### ISSUE TITLE
Sharing icon seems missing

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2277]
Is it intended that no sharing icon is shown anymore in the three dot menu or elsewhere? The DOM has it but I don't happen to see it on master.

cc @jancborchardt 

<img width="1294" alt="screen shot 2016-11-23 at 14 21 20" src="https://cloud.githubusercontent.com/assets/878997/20563382/a15c35fa-b188-11e6-9932-327d05a47f8c.png">
<img width="1127" alt="screen shot 2016-11-23 at 14 22 50" src="https://cloud.githubusercontent.com/assets/878997/20563384/a29c9fb8-b188-11e6-93a6-d1c76478788c.png">

**Comment by MorrisJobke** [comment]
Fix is in #2278
