### ISSUE TITLE
In the latest version of nextcloud, what is the reason for the slow reading and writing of webdav?

### ISSUE THREAD

**Issue by fan4905** [nextcloud/server#22772]
Excuse me, I use nextcloud19.0.2, I use webdav on windows10 to map to the z drive on the hard disk, when I copy files larger than 4G to the z drive, the speed is very slow, and the upload is halfway or when it is almost finished. , What is the reason?

**Comment by jospoortvliet** [comment]
This is a support question, not a bug report. Please read the template: this is NOT a support forum. Use help.nextcloud.com please! I hope somebody there can help you.
