### ISSUE TITLE
Locale setting has wrong date format for many locales

### ISSUE THREAD

**Issue by digital-carver** [nextcloud/server#22785]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to Settings -> Personal Info
2. Change Locale to English (Austria), or English (Barbados), or English (India), or one of many other similar ones

### Expected behaviour
The date format should be D/M/Y i.e. date/month/year as is used in these regions ( [Wikipedia](https://en.wikipedia.org/wiki/Date_format_by_country), [data from Oracle Java](https://gist.github.com/mlconnor/1887156) )

(There are nuances about the separator used and zero-padding, but the order of the elements is IMHO the most important and potentially confusing part that needs to be fixed.)

### Actual behaviour
The date format shown is M/D/Y 

### Client configuration
**Browser:** Firefox 

**Operating system:** Windows 7

</details>

Arguably, this also applies to more generic ones like English (Europe), as D/M/Y is the most common format in Europe as per the same sources. And English (World) should either be Y/M/D as usual current compromise between the various formats, or D/M/Y as the most common format used around the world. 

As of now, a few major locales like English (United Kingdom) and English (Australia) have the correct format set in them, but most of the rest of the countries are left with the rarely used US date format that only applies to a few other countries in the world.

**Comment by kesselb** [comment]
For anyone who want to work on this:

The list of locales in the personal info section are the locales available to PHP minus locales not available for your user. https://github.com/nextcloud/server/blob/7e281a07bb66a082a35cbdd52f7d1e418beb4f53/apps/settings/lib/Settings/Personal/PersonalInfo.php#L116

For most php components the locale / language should be correct. But some js components don't know the correct format yet. moment.js (that's a library used by Nextcloud) only supports a subset of the locales: https://github.com/moment/moment/tree/develop/locale. 

A locale like `en_DE` falls back to `en` (try `moment.locale('en_DE')` in your console). What needs to be done (at least what I think that needs to be done): A custom per user locale as described here: https://momentjs.com/docs/#/i18n/ and https://momentjs.com/docs/#/customization/.

Please get in touch to discuss a possible solution first before you work at this issue. Happy hacking :sunglasses:

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by digital-carver** [comment]
Hi, 

The (external) Nextcloud provider I use seems to be only on version  23.0.4.1, so I unfortunately can't report on the status of the latest versions w.r.t. this issue. 

In version  23.0.4.1, all the `en-` locales  that have files in the [moment.js folder linked above](https://github.com/moment/moment/tree/2.29.4/locale) by @kesselb work correctly. These are:  Australia, Canada, United Kingdom, Ireland, Israel, India, New Zealand, and Singapore. 

But many of the others (eg. _English (Pakistan)_ ) still wrongly use the M/D/Y date format.

**Comment by mikoladz** [comment]
I can confirm that the problem still occurs in NC 30.0.11. Language and region are set to Polish, yet the date is still displayed as mm/dd/yyyy, same with calendar.

![Image](https://github.com/user-attachments/assets/12fda9cf-700b-43c2-9379-361564a2ae1b)

**Comment by cdauth** [comment]
Could this be reopened?

English (World) should use YYYY-MM-DD (which is the standard used internationally). English (Germany) should also use that, since that is what is used in Germany in an international context. I don’t see much point in the English (Europe) locale, but I feel like it would also make the most sense to use the international standard.

**Comment by JosephChataignon** [comment]
> I can confirm that the problem still occurs in NC 30.0.11. Language and region are set to Polish, yet the date is still displayed as mm/dd/yyyy, same with calendar.

Same issue with French. Long-form date is displayed correctly ("8 septembre 2025"), short-form is correct in Files ("08/09/2025") but in Calendar and in the date-selection forms of the settings page itself, the format is wrong ("09/08/2025").
