### ISSUE TITLE
Admins can not change emails anymore

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2279]
The call receives a 302 because route not found....
@schiessle I guess your rework has to do with this.

**Comment by LukasReschke** [comment]
Apparently also passwords? => https://github.com/nextcloud/server/issues/2284

**Comment by blizzz** [comment]
Passwords are unrelated to this issue.

**Comment by schiessle** [comment]
always this hidden features... will have a look

**Comment by schiessle** [comment]
will be fixed as part of https://github.com/nextcloud/server/pull/2276
