### ISSUE TITLE
Transfer not possible if a reshare to a group/room exists where the user is no member

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#22803]
From https://github.com/nextcloud/server/pull/22761

> While doing that I have noticed that currently it is only possible to transfer ownership of a reshare if it is a reshare with a group (or room) and the reshare is transferred to a user in the group (or [room](https://github.com/nextcloud/spreed/blob/6089fa5ec7577685214e91e4d61626173bfe74a0/tests/integration/features/sharing/transfer-ownership.feature#L51)).
> 
> When transferring ownership of a reshare with another user or with a group to a user not in the group restoring the share fails (but the command succeeds, it only fails for the specific files that are reshares).
>     
> When transferring ownership of a path that is a reshare the command fails (as when a specific path is provided [the path tries to move the file](https://github.com/nextcloud/server/blob/f0b46ea605548d9feb4af115a3d05cf2cff24bda/apps/files/lib/Service/OwnershipTransferService.php#L306), it does not take into account reshares).
> 
> Note that the above is not related to https://github.com/nextcloud/server/pull/22648 (that pull request fixed the _transferring ownership of folder reshared with group to a user in the group_ scenario). The failure when restoring a reshare is caused by [`getMountPoint()` being called on a null object](https://github.com/nextcloud/server/blob/2a054e6c04e0a40421510eb889cbf59f153c5177/lib/private/Share20/Manager.php#L304). However, even before https://github.com/nextcloud/server/pull/21489 it was failing too (in that case it complained that it could not increase permissions).
> 
> @rullzer @juliushaertl Feel free to either work on the issues or change the pull request state to _To review_ if not being able to transfer reshares is not an issue (or if you prefer to merge this now and work on them later ;-) ).

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
