### ISSUE TITLE
Collapse or Hide Dashboard Widget if "No Unread"

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22807]
Testing Nextcloud `20.0.0beta3` and Dashboard #20930.  Inspired by #22339 on empty state improvements and unification.

When an active, configured widget has nothing to display, it would be useful for it to collapse or auto-hide.  This could prove more useful as more and more widgets become available on the Dashboard.

Here is a rough example of collapsing a couple items, when _no unread_.  Forever Alone.
![Screenshot_20200911_065411](https://user-images.githubusercontent.com/1787238/92933918-b6f3e700-f3fb-11ea-9d4d-e87e4eecc32e.png)
![Screenshot_20200911_065343](https://user-images.githubusercontent.com/1787238/92933928-b8bdaa80-f3fb-11ea-92ac-48be258d65ca.png)

Or perhaps this is a "You are Caught Up / Forever Alone Widget" with the check mark icon.

![Screenshot_20200911_070005](https://user-images.githubusercontent.com/1787238/92934519-6f218f80-f3fc-11ea-827b-7c8cc6dd8054.png) **Up to Date**
![Screenshot_20200911_065411](https://user-images.githubusercontent.com/1787238/92933918-b6f3e700-f3fb-11ea-9d4d-e87e4eecc32e.png)
![Screenshot_20200911_065343](https://user-images.githubusercontent.com/1787238/92933928-b8bdaa80-f3fb-11ea-92ac-48be258d65ca.png)

**Comment by jancborchardt** [comment]
Much like home screens with app icons and widgets on iOS and Android, things should stay in the same place.

What we do for example when there are no unread talk messages is show a notice about that, but then below still show recent conversations to be useful. Same we can do with Mail for example.
