### ISSUE TITLE
Optimize online status update 

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#22805]
The new online status feature is really great!

From a UX/design perspective I think it take quite a lot of space and the drop-down menu becomes already quite large:

![image](https://user-images.githubusercontent.com/1589737/92910393-4dd69880-f428-11ea-94da-7bb76b29d0c6.png)

Also the name is completely useless because there is no action at all. How about combining them into one line:

![image](https://user-images.githubusercontent.com/1589737/92910744-a3ab4080-f428-11ea-9051-9a0972fe05af.png)

I think together with a tooltip (which we already have in the current version) when you hover over the name/status indicator this is obvious enough for most users.

What do you think @nextcloud/designers ?

**Comment by stefan-niedermann** [comment]
Is a pure color accessible though? color blind people might also relate on form. (I haven't tested the feature yet and don't know the other states, if there is another form on other status, just mark my comment as "resolved", no need to answer 😉)

**Comment by skjnldsv** [comment]
> Is a pure color accessible though? color blind people might also relate on form.

We though about this, all status have different shapes :)

**Comment by raimund-schluessler** [comment]
It would also be good if the whole width of the status selection would be clickable:

![status](https://user-images.githubusercontent.com/2496460/93028712-e1b98780-f615-11ea-8e65-a59bb3ef2788.gif)

**Comment by jancborchardt** [comment]
The problem of getting rid of "Set status" is that this also leaves no space for the status message, so we can’t do that.

> I think together with a tooltip (which we already have in the current version) when you hover over the name/status indicator this is obvious enough for most users.

A tooltip is not obvious at all, so we shouldn’t do that. Especially not for the core of the feature, which is the status message, as well as the prompt to set a status. :)

**Comment by skjnldsv** [comment]
CLosing then
