### ISSUE TITLE
Projects Widget for Dashboard

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22810]
Humble request for considering the addition of a `Projects` Widget.

Inspired by `Favorites` or `File Recommendations` widget, but specifically relating to **Projects** notification / activity.  Projects can contain [Deck](https://github.com/nextcloud/deck/issues/2221), [Talk](https://github.com/nextcloud/spreed/pull/4136) and other app widgets.

#15841 inspired on developing a project manager
#21359 is a related issue on enhancing Files app's handling of projects.
#20930 Dashboard overview discussion

Curious on how this could be applied.  Either for all projects or per-project.  If no unread on a specific project + per-project widgets available, could pair nicely with #22807. Mock up example follows of per-project widget:

![Screenshot_20200911_072633](https://user-images.githubusercontent.com/1787238/92937391-2370e500-f400-11ea-98ed-33d27720d293.png) **Project: Contract Agreement**
- Invited `@Trish` to `Meeting Notes`
- Example.jpg _shared_ 10:53 am
- Example.jpg _edited_ 10:45 am
- Joined Conversation 10:11am

**Comment by jancborchardt** [comment]
The idea is actually that Projects are not a widget in Dashboard, but a _navigation_ for the Dashboard. :)

See the specification and second mockup in the overview issue:
https://github.com/nextcloud/server/issues/20930

**Comment by sunjam** [comment]
> See the specification and second mockup in the overview issue:

Ah, so Security would be the project.
![](https://user-images.githubusercontent.com/3404133/82212494-ed6c9a00-9912-11ea-8d9d-132dd87f3dff.png)

**Comment by jancborchardt** [comment]
See **⭕📑👥 Integration of Projects and Teams into Dashboard #22897** for the plan on how we could proceed here. :)
