### ISSUE TITLE
feature request: configure the TMP directory at initial setup

### ISSUE THREAD

**Issue by supervisitor** [nextcloud/server#22811]
... I do a new install twice, first I use the Web Installer "setup-nextcloud.php", than I use the archive file "nextcloud-19.0.1.zip". After both installation I run into this tmp-dir-error... and I don't configure anything more than I was ask for at the installation process, but I got one more error message at the logging file: `opendir(/tmp): failed to open dir: Permission denied at /...path/to/server/dir.../lib/private/TempManager.php#191`
so, it looks like this is a setup/default config problem.

for me, this is not a problem, I know how to work with, but other could be confused by this... this why I report this issue, this why I'm a little confused that the ticket is closed as fast?! 😇

_Originally posted by @supervisitor in https://github.com/nextcloud/server/issues/22177#issuecomment-671976045_

**Comment by kesselb** [comment]
> configure the temp directory at initial setup

https://docs.nextcloud.com/server/19/admin_manual/configuration_server/config_sample_php_parameters.html#multiple-config-php-file

**Comment by supervisitor** [comment]
... the documentation is great but: why is there no option to setup the TMP dir at the initial setup wizard? most user do not know any about the error, if they do not have a look to the logs.
this is the reason why i think you could change it, you could add it to the setup wizard.

**Comment by kesselb** [comment]
> The issue with your setup is that your hosting provider forgot to set sys_temp_dir and the default is /tmp/ which is not writable on your shared hosting account.

As explained at https://github.com/nextcloud/server/issues/22177#issuecomment-671987313. For most setups it's not necessary to change the tempdirectory thus there is not option with the installer.
