### ISSUE TITLE
Allow installing/removing/enabling/disabling multiple apps with occ app:install / etc. command

### ISSUE THREAD

**Issue by Zocker1999NET** [nextcloud/server#22823]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It is related to the problem of setting up a new instance using Ansible. I decided to also deploy certain apps while disabling other preinstalled apps while Ansible configures my Nextcloud instances. It is possible with Ansible to loop over the list of apps I want to enable / install, however it is very slow because of Ansible not being the fastest deployment solution, but also occ has a slight overhead.

**Describe the solution you'd like**
Allow the following occ commands to manage multiple apps at once:

- `app:install`
- `app:enable`
- `app:disable`
- `app:remove`
- `app:update`

An example usage would be `php occ app:install twofactor_admin twofactor_backupcodes twofactor_gateway twofactor_u2f`.

**Describe alternatives you've considered**
If there is another way to command Nextcloud to install a given list of apps, it may be an good alternative. But also supporting multiple app ids on certain occ commands should not be too complicated to implement and maintain, and also should not break anything.

**Additional context**
Other "package managers" allow this behavior too, like `apt` / `dpkg` / `pacman` / …

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
