### ISSUE TITLE
 Weather status widget returning incorrect time

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22834]
NextcloudPi 20.0.0beta3 and beta4.

[Here is forum post](https://help.nextcloud.com/t/20-0-0beta4-feedback/92138).

Time of day is completely wrong by 6 hours.
Detect Location returns incorrect time of day for my city.
Manually adding my address equally incorrect.

Thanks for your good work!

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing this report in favour of https://github.com/nextcloud/server/issues/23399. A tip for reporting issues: It's often helpful to include a image to show a problem. Also the usage of the issue template is highly recommended.
