### ISSUE TITLE
Nextcloud 20.0.0beta 3 and beta4 do not actually disable incompatible apps

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22832]
When updating from `stable 19.0.2` to `20.0.0beta3` and from `beta3` to `beta4` incompatible apps are never actually disabled by the system as part of the Admin / Overview update to latest Beta release.  Based on the notifications during during these system updates I'd assume they would be disabled, but perhaps I've misunderstood.  

**What actually happens**
All apps continue running as previously enabled.  System logs dm'ed to @jospoortvliet

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
