### ISSUE TITLE
Fail gracefully if unified search request fails

### ISSUE THREAD

**Issue by raimund-schluessler** [nextcloud/server#22837]
Currently, if a request to a unified search provider fails (for whatever reason, e.g. due to https://github.com/nextcloud/server/issues/22755) and no other provider delivers a search result, the placeholder is never replaced with an empty result. Also, the failed result gives an ugly message in the javascript console.

It would be great if a failed search request is handled more gracefully. I.e. print a meaningful debug message and anyhow show an empty search result instead of the placeholder.

This is how it currently looks like (with a failed request due to https://github.com/nextcloud/server/issues/22755)
<img width="1280" alt="failed" src="https://user-images.githubusercontent.com/2496460/93026548-035f4280-f607-11ea-9056-50f49e304a3a.png">

@skjnldsv As I have the impression you take care of most of the unified search stuff 😉

**Comment by skjnldsv** [comment]
fixed
