### ISSUE TITLE
libravatar federation

### ISSUE THREAD

**Issue by tclavier** [nextcloud/server#22831]
**Description**  
As a user of nextcloud, i want to define my avatar in my account in order to share it on other sites. To do that, other sites can follow the libravatar api (https://wiki.libravatar.org/api/) to get my avatar 

**Example**  
As user `thomas` on `https://nextcloud.domain.com` with email `thomas@domain.com` i put an avatar on my account.

Others sites can request DNS for : `SRV _avatars-sec._tcp._tcp.domain.com`. DNS respond `nextcloud.domain.com` and finaly they can download my avatar at url : `https://nextcloud.domain.com/avatar/4fbeb1bd99d764f65642babb1308c9c9`

All details of API to implement is describe at https://wiki.libravatar.org/api/

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by tclavier** [comment]
What is missing to leave this request open?
