### ISSUE TITLE
Cannot locate Dashboard Weather Widget github repo in the app store

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#22833]
All other integrations appear to have app store listing and github repos, but cannot find Weather widget.
![image](https://user-images.githubusercontent.com/1787238/93006341-d9772480-f50f-11ea-9f47-96d62266d21b.png)

**Comment by sunjam** [comment]
Located through the app store under "Weather Status".  [See this forum post](https://help.nextcloud.com/t/20-0-0beta4-feedback/92138).  Still feels awkward to locate, so leaving this issue open for the moment.  Thanks.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/tree/master/apps/weather_status
