### ISSUE TITLE
Admins cannot change passwords anymore on Users page

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#2284]
Either success or failure, the response is not dealt with. The text input stays as is and there is no confirmation.

**Comment by MorrisJobke** [comment]
You shall search the bug tracker first 🔮  #2279

**Comment by MorrisJobke** [comment]
Even nearly the same wording ;)

**Comment by MorrisJobke** [comment]
And the same labels ;)

**Comment by LukasReschke** [comment]
Well. Password != email but fair enough 😉

**Comment by blizzz** [comment]
@MorrisJobke the issue is caused by the blurFunction from https://github.com/nextcloud/server/commit/3ffd9a755f60761d6a1f5fa3d02d07b4c2e68972

**Comment by schiessle** [comment]
> @MorrisJobke the issue is caused by the blurFunction from 3ffd9a7

yes, I just tested it. Password change work, this is just a UI issue that the user get no success message. If it fails, e.g. because of the password policy app the error message also is no longer displayed correctly.

**Comment by MorrisJobke** [comment]
Ah - okay - then I missed this one. I will have a look tomorrow

**Comment by MorrisJobke** [comment]
`OC.PasswordConfirmation.requiresPasswordConfirmation()` evaluates to false even if it is needed 🤔

**Comment by MorrisJobke** [comment]
Introduced with https://github.com/nextcloud/server/pull/2216

**Comment by MorrisJobke** [comment]
@nickvergessen Could you have a look - this does not seem to be because of the callbacks, but because the require check is wrong.

**Comment by blizzz** [comment]
@MorrisJobke no, one problem is already  the use of ```this```  in the callback..

**Comment by MorrisJobke** [comment]
Fix is in #2417
