### ISSUE TITLE
objectId to unified search results for files/comments

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#22855]
- search for a file/comment via new unified search as a client
- need objectId to know which file/folder to display

Currently only resourceUrl is available:
"resourceUrl": "http:\/\/localhost\/nc\/index.php\/apps\/files\/?dir=\/&scrollto=ManyManyImages",

@nickvergessen

**Comment by nickvergessen** [comment]
Yeah we should add `object id` and `object type` as already known from activities, notifications, conversations on "objects", etc.

**Comment by nickvergessen** [comment]
cc @ChristophWurst

**Comment by ChristophWurst** [comment]
Fine by me, but that requires an API change as the current search providers do not give you this info.

**Comment by tobiasKaminsky** [comment]
Adding info to API is no breaking change…

**Comment by ChristophWurst** [comment]
I'm not talking about the REST/OCS API. But there is an API that apps implement in order to participate in the unified search. And that API has to be changed. We can't magically extract an object ID and type from the current data if apps don't specify that.

**Comment by tobiasKaminsky** [comment]
True, I was also a bit short :S 
What I meant was to have this as an additional parameter, and if others app do not implement it, it is null/"" by default, so there is direct backward compatibility.
Would have the benefit that, e.g. deck could update during NC20 cycle and it works directly, without new server release.

So then it will be in 20.1?

**Comment by ChristophWurst** [comment]
> So then it will be in 20.1?

@rullzer's call

**Comment by skjnldsv** [comment]
Ping?

**Comment by tobiasKaminsky** [comment]
This is needed for all clients to handle unified search at all. 
Whoever implements this, I am happy to co-work so we can test it at least on files, talk, deck, etc.

**Comment by rullzer** [comment]
I guess we should do this for 21. Breaking the API would result in broken Nextclouds if we do it 20.0.1 or 20.0.2 if an app did not get updated. Since php will just start throwing errors since the interface doesn't match.

**Comment by tobiasKaminsky** [comment]
I guess it would be enough to extend API to give more info, but I am fine with 21.
Can you please schedule it with a bit of buffer, so that it will be done in 21 and not in very last week, as clients can only work on their implementation once server is done.

**Comment by rullzer** [comment]
> I guess it would be enough to extend API to give more info, but I am fine with 21.

Yeah but we need to make sure this gets relayed from the providers. The search endpoint can't magically find the object id etc from a deck board. it is a stupid component that just relays info.

> Can you please schedule it with a bit of buffer, so that it will be done in 21 and not in very last week, as clients can only work on their implementation once server is done.

@ChristophWurst I agree. Could you maybe look into this soonish so we can merge it early after the branch off?

**Comment by rullzer** [comment]
Sorry it is early.
@ChristophWurst would you have time to extend the API and the interfaces this week? Then the clients can check as well

**Comment by ChristophWurst** [comment]
done via https://github.com/nextcloud/server/pull/24474
