### ISSUE TITLE
UI - Misaligned position of size

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#22863]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Small thing, it looks like the displayed size of selected folders/files is not aligned with the "SIZE" column of individual files (screenshot).

### Steps to reproduce
1. in files, select a random file/folder

### Expected behaviour
Total selected size is aligned with sizes of other files

### Actual behaviour
is not aligned

![Screenshot from 2020-09-15 14-23-50](https://user-images.githubusercontent.com/36133540/93210268-9612f500-f75f-11ea-993a-7665b2e8ae2f.png)

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2
![image](https://user-images.githubusercontent.com/42591237/121668909-0e6ad480-caac-11eb-8891-98a9a696586e.png)

**Comment by szaimen** [comment]
Fixed in https://github.com/nextcloud/server/pull/27995
