### ISSUE TITLE
Cannot administrate users in small windows

### ISSUE THREAD

**Issue by rollanders** [nextcloud/server#22862]
Since some versions back the outlay for the users administration was changed. Previously I could change users permissions and accept new users from the browser in the phone. Now the window is too small and I cannot do this administration. It used to be handy to do this kind of thing in front of the new user. Now I can only do it in the computer browser.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
