### ISSUE TITLE
Periodic high CPU load since 19.0.2 update

### ISSUE THREAD

**Issue by kitzler-walli** [nextcloud/server#22878]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
The average load of my system was 40% before the update to 19.02

### Actual behaviour
Since the update my server has periodic loads of 80%
![image](https://user-images.githubusercontent.com/1926992/93323282-b2bd3480-f814-11ea-844b-556b99d116ee.png)

These loads seem to be caused by postgres, at least my first inspections showed high loads causes by background workers oder ncadmin statements.

### Server configuration

**Operating system:** Linux 5.4.0-45-generic x86_64 (Ubuntu 20.04)

**Web server:** Apache/2.4.41 (Ubuntu)

**Database:** PostgreSQL 10.12 (Ubuntu 10.12-0ubuntu0.18.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0, 64-bit

**PHP version:** 7.4.3

**Nextcloud version:** 19.0.3

The historic data shows this is a new issue:
![image](https://user-images.githubusercontent.com/1926992/93323734-47c02d80-f815-11ea-8020-fbb19bfd84a3.png)

**Comment by Dragon988** [comment]
When the CPU spikes what queries are being run on the postgresql backend?

**Comment by kitzler-walli** [comment]
What's the best way to get a dump of the current queries with high loads or long wait times?

**Comment by acsfer** [comment]
How are your Cronjobs configured? At which times are they triggered?

**Comment by kitzler-walli** [comment]
*/5  *  *  *  * php -f /var/www/nextcloud/cron.php > /dev/null 2>&1
0 4 * * * php -f /var/www/nextcloud/occ preview:pre-generate >> /var/log/nextcloud/previewgenerator.log

**Comment by Dragon988** [comment]
When you do find out which queries are being run let us know.

**Comment by kitzler-walli** [comment]
OK it seems like that was some sort of temporary problem:
![image](https://user-images.githubusercontent.com/1926992/93728090-b0652c80-fbbe-11ea-9843-d3beadbc6c22.png)
