### ISSUE TITLE
Add preview mimetype support capabilities 

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#22873]
ref https://github.com/nextcloud/viewer/pull/577

On viewer, we have no way to know if the preview endpoint supports the file or not.
E.G for heic, they cannot be displayed directly in a browser, thus we need the preview endpoint. If imagick isn't installed, there is no support for heic, but we still register it as 'supported' in viewer

cc @MorrisJobke

**Comment by MorrisJobke** [comment]
I just noticed that previews are registered via a regex. So the regex and a callback are passed to the preview manager. Then if a preview is requested it checks the mime type of that file against all regexes and calls the matching callback. So there is no easy way to just get back a list. Maybe we should pass down the regex?

Does that make sense to give the list of regex and then the client can reimplement this logic?

cc @rullzer

**Comment by rullzer** [comment]
Just use the has preview property from webdav

**Comment by MorrisJobke** [comment]
> Just use the has preview property from webdav

@skjnldsv Might this be an option for the viewer?

**Comment by skjnldsv** [comment]
No, because the file actions needs to be registered before. Otherwise we'd still open the viewer without a view to display it.

I need the list of mimes that can have a preview generated.
But if the fileActions API allows regex too, then it's fine for me. Otherwise, can we get it from gd or imagick?

**Comment by MorrisJobke** [comment]
> I need the list of mimes that can have a preview generated.

Then we don't have this, because we have a list of regexes that match a mime type.



> Otherwise, can we get it from gd or imagick?

What do you mean? It also needs to have a preview provider on our side and not only in gd or imagick.

**Comment by skjnldsv** [comment]
> What do you mean? It also needs to have a preview provider on our side and not only in gd or imagick.

Ah right!
Then just getting the regex should be good I think? Does the fileActions support regex? I'm not in front of the workstation right now. If so, let's just output the capabilities as regex and string?

**Comment by skjnldsv** [comment]
Done in https://github.com/nextcloud/viewer/pull/1177
