### ISSUE TITLE
More SEO friendly 

### ISSUE THREAD

**Issue by mxkeke** [nextcloud/server#22879]
I'd like to see Nextcloud more SEO friendly in the future versions:
<img width="982" alt="d6c847386d4244a4ef1503b047ae4dbb9c29d52c" src="https://user-images.githubusercontent.com/8062159/93324891-c7023100-f816-11ea-97d7-d4c8aa09a5af.png">

Now all the pdf public shared are blocked (or with limited indexing for search engines) from robot.txt.

**Comment by Dubidubiduu** [comment]
1. Typically you don't want your cloud exposed to google by default.
2. It's just about your public files shares?
3. To get a good SEO-Result you should at least be able to set the title, better also set up a meta-description, have more than 600 words on that page. Also having a readable url is a plus. I don't see that for public shares..

Anyway, maybe https://apps.nextcloud.com/apps/cms_pico is what you search for?

**Comment by mxkeke** [comment]
Yes, it's only for public pdf files shared.
I've a case where the user would like to use Nextcloud to save brochures, technical sheets, etc and then use the public url to sharing in the pages of his website (with the Nextcloud pdf viewer) or to create a folder public shared (e.g. creating a "docs" link on the website that open the Nextcloud folder shared). Now Nextcloud block them from indexing, instead to leave the search engines scan the pdf (Google can indexing perfectly the pdfs from their meta tags, title and contents).

I don't know Pico, later I'll take a look.
Thanks

**Comment by mxkeke** [comment]
I've tried with Pico but the result is the same... robot.txt block the indexing from the search engines

**Comment by mxkeke** [comment]
Is there a way to disable robot.txt?
I've tried to remove the "Disallow: /" on the file txt but not works.

**Comment by acsfer** [comment]
@mxkeke please use the forum for these questions. Use Git only for bugs or enhancements, not configuration issues.
Thanks for understanding.

That being said, Nextcloud is mostly a private system, so 99,9% users don't want any data exposed on the search engines.

Perhaps, you can change this behavior by changing either your `.htaccess` and/or your server configuration to allow all/some public content to be indexed. Open a topic at https://help.nextcloud.com/ and i'm sure someone will help you.

Thanks 👍
