### ISSUE TITLE
Admin can send App QR-Code via Mail to user

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/server#22889]
**Is your feature request related to a problem? Please describe.**
Some of my users don't know how to use the internet, putting in server, mail and password is too much to ask for setting up an App.

**Describe the solution you'd like**
In backend, the admin can send QR-Code via email to the user. User can then scan QR-Code and use the app. Also command line command is appreciated.

**Describe alternatives you've considered**
I have to impersonate the user, create a qr code, make a screenshot, send this screenshot to my user? Don't know.

**Additional context**
For me, it's mostly about talk-app.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
