### ISSUE TITLE
Change themed CSS generation to SCSS templates

### ISSUE THREAD

**Issue by eppfel** [nextcloud/server#2288]
Thanks to the introduction of Sass in nextcloud (#2050), we could really improve how the css styles are generated in the Theming Controller, because now the controller is bloated with concatenated CSS strings: [server/apps/theming/lib/Controller/ThemingController.php](https://github.com/nextcloud/server/blob/master/apps/theming/lib/Controller/ThemingController.php)

We could use the [scssphp](http://leafo.net/scssphp/) compiler to compile SASS templates with variables:
```php
echo $scss->compile('
  $color: #abc;
  div { color: lighten($color, 20%); }
');
```
This would also make theming more accessible.
What do you think @juliushaertl, @LukasReschke, @schiessle @nickvergessen ?

**Comment by juliushaertl** [comment]
@eppfel Having a simpler CSS generation really makes sense.

We should have the CSS rules in an external file and generate the CSS by just adding the theming variables.

**Comment by eppfel** [comment]
jep, there is a lot of functionality: http://www.sass-lang.com/documentation/file.SASS_REFERENCE.html#control_directives__expressions

And yes external file template was, what i was thinking of.
I'd gladly try to build something on top of #2050, but not before the weekend.

**Comment by juliushaertl** [comment]
@eppfel Sure, that would be awesome. If you need any help, just ping me. :wink:

**Comment by eppfel** [comment]
I was thinking...
When we move to SASS we actually could give up on the practice, of overwriting styles with an additional theming stylesheet and move the variables (which are mainly just colors) to the original SASS files.
Less files to load, less CSS rules to apply, much happy 👏 
Of course this implies more theming code in the core. I don't know if this is desired 🤔 
Starting development does not make sense, yet, as #2050 is still being developed.
