### ISSUE TITLE
Unified search: Currency conversion

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#22909]
Some search mechanisms have this as a quick way for currency conversion (much like the maths operations, see https://github.com/nextcloud/server/issues/22908), like macOS, iOS and Google.

The difference here is that we need some sort of reasonably up-to-date currency metrics so we don’t show outdated data. Not sure if this would be easily doable hence.

Some possible resources:
- https://exchangeratesapi.io/
- https://openrates.io/
- https://fixer.io/

Here’s a screenshot of how iOS does it:
<img width="414" alt="iOS search currency converter" src="https://user-images.githubusercontent.com/925062/93460906-3d209980-f8e4-11ea-856b-f4d172892140.png">

cc @nextcloud/search

**Comment by skjnldsv** [comment]
I highly doubt this is the place for this.
Please add this to the app ideas forum section https://help.nextcloud.com/c/feature/app-ideas/21
this is just polluting server with issues that are not related to server :cry:
