### ISSUE TITLE
Unified search: Ability to do basic maths operations

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#22908]
A lot of search mechanisms offer this as a nice quick way to calculate without having a full-blown calculator. E.g. macOS, GNOME, iOS, Google etc.

Here’s a screenshot of how iOS does it:
![iOS search calculator](https://user-images.githubusercontent.com/925062/93460743-00ed3900-f8e4-11ea-83b9-293e1f28220a.jpeg)

cc @nextcloud/search

**Comment by ChristophWurst** [comment]
Same as https://github.com/nextcloud/server/issues/22909#issuecomment-694202592. This should be a separate app. I'm happy to help whoever wants to play with this, but it's not a feature request of server.
