### ISSUE TITLE
email is not set when creating a user via API

### ISSUE THREAD

**Issue by FSD-Christian-ADM** [nextcloud/server#22914]
When using the API to create a user, like it is described in the documentation https://docs.nextcloud.com/server/15/admin_manual/configuration_user/instruction_set_for_users.html all values are excepted except for the email.

`curl -s https:/localnextcloudinstallation/ocs/v1.php/cloud/users -H "OCS-APIRequest: true" -u "admin_user":"admin_pass" -X POST -d userid="testuser_01" -d password="Secure_Password" -d email="email@domain.com"`

email is left blank and no welcome mail is sent. workaround is to reset the email, after creating a user and then resending the welcome mail

using Nextcloud 19.0.2

**Comment by TrebSasch** [comment]
We have the same issue. 

We are on 19.0.3. Had the same issue in 18, too.

**Comment by acsfer** [comment]
Not a duplicate but this is similar.
https://github.com/nextcloud/server/issues/21577

**Comment by FSD-Christian-ADM** [comment]
> 
> 
> Not a duplicate but this is similar.
> #21577

I tried to set the option "send email to new user". unfort7unately it doesn't change the bahavior

**Comment by manuelrhdotcl** [comment]
I was try with 19.0.1 and works fine. So, then I was update to 19.0.3 and works fine too.

`curl -u xxxx -X POST https://domain.tld/ocs/v1.php/cloud/users -H "OCS-APIRequest: true"  -d userid="testuser_01" -d password="Secure_Password" -d email="email@domain.com"

![imagen](https://user-images.githubusercontent.com/215673/94227023-89b13980-fecf-11ea-9f93-70d91510bda8.png)


`OS: Centos 7 Linux 3.10.0-862.2.3.el7.x86_64 x86_64
PHP: 7.3.19
MySQL: 5.5.65
`

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
