### ISSUE TITLE
Update Release Schedule

### ISSUE THREAD

**Issue by tflidd** [nextcloud/server#2292]
The update and release schedule hasn't been updated for a while.

There are already a number of nice fixes for NC 10, so it would be great to get out the 10.0.2-release soon.

For NC 11 it would be great to get some more details about the planned dates, especially feature freeze is interesting, when all features are in the code and can be tested (and it shouldn't be that long judging from this list: https://github.com/nextcloud/server/issues/745).

**Comment by MorrisJobke** [comment]
cc @karlitschek @LukasReschke 

We plan to release something soon. And yes - we need to improve on this specific topic.

**Comment by tflidd** [comment]
Great. All the release handling is still a bit unclear. I also started a thread on the forum some time ago:
https://help.nextcloud.com/t/support-cycle-number-of-maintained-versions/2508

**Comment by MorrisJobke** [comment]
I updated https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule#nextcloud-11

The plan is to do a beta2 today, that is also pushed out via the updater (to instances on the beta channel).

Then we plan an RC in one week and the final release in 2 weeks.

Cheers 🚀
