### ISSUE TITLE
Drop PHP 7.2 support

### ISSUE THREAD

**Issue by mwkward** [nextcloud/server#22929]
[PHP 7.2 will end security support at November 30, 2020](https://www.php.net/supported-versions),  So I think nextcloud have to end php 7.2 support and focus on version 7.3, 7.4, and php 8 for security

**Comment by Nils160988** [comment]
Dropping php 7.2 support is already scheduled for NC21, see https://github.com/nextcloud/server/pull/22767

**Comment by mwkward** [comment]
Sorry, I close this issue.
