### ISSUE TITLE
2 link shares created with specific sharing configuration

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#22939]
### Steps to reproduce
1. Have the following configuration:
![Bildschirmfoto von 2020-09-18 13-49-26](https://user-images.githubusercontent.com/213943/93594525-4b3eea80-f9b6-11ea-981b-17e8deb6294e.png)

2. Create a folder
3. Select a different expiration day
4. Click into the password field to copy it
5. Click onto the :arrow_right: in the password fields because you think that is needed or does something
6. Reload the page

### Expected behaviour
There is 1 public link share with the expiration date you set

### Actual behaviour
There are 2 public link shares with the expiration date you set :confused: 

Does not happen on stable19

**Comment by nickvergessen** [comment]
cc @skjnldsv you seem to have reworked that thing a bit in may?

**Comment by skjnldsv** [comment]
Did I? :thinking:

**Comment by nickvergessen** [comment]
Aparently https://github.com/nextcloud/server/commits/master/apps/files_sharing/src/components/SharingEntryLink.vue

**Comment by skjnldsv** [comment]
I guess this is a just firing the form?

**Comment by kurn77** [comment]
Hello, I reproduce simply with creating the share link, click on right arrow (next to psw) and reload page > no need to change expiration day and/or copy password. / Not reproduced on share by email.

Operating system: Debian 10.12-2
Web server: Apache 2.4
Database: PostgreSQL 10.12
PHP version: PHP 7.3.19
Nextcloud version: NextCloud v 20.0.1
Client configuration: Version 86.0.4240.111 (Build officiel) (64 bits)
Operating system: Windows 10 Version 10.0.19041 Numéro 19041

**Comment by szaimen** [comment]
Hi, please update to at least 23.0.12 and report back if it fixes the issue. Thank you!

**Comment by nickvergessen** [comment]
Seems to be solved.
