### ISSUE TITLE
Add new file menu in shared link not fully visible

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/server#22959]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share link with permission to add files.
2. Press the plus button.
3. Menu is partially off screen. 

### Expected behaviour
Menu should be fully visible.

### Actual behaviour
Menu is partially off screen:
![obraz](https://user-images.githubusercontent.com/19647553/93668875-ece63a80-fa8f-11ea-8a24-04f9d05db337.png)

### Server configuration

**Operating system:** Ubuntu 18.04 LTS

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 19.0.3

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

**Comment by szaimen** [comment]
I think this is solved in the meantime
