### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Marios1231** [nextcloud/server#22968]
when ever NC sends an email the logo looks stupid in the email like this 
since i dont know how to put pictures here ill just share a link of the photo https://maryus.site/index.php/s/FsnZ9P4Bq9GTdcg
btw this is NC beta4

**Comment by kurn77** [comment]
Hello, I cannot open the photo > but is it same issue than this one #23977 ?

**Comment by Marios1231** [comment]
> Hello, I cannot open the photo > but is it same issue than this one #23977 ? 

Yeah it is thank you now I know how to fix it

**Comment by kurn77** [comment]
So it is also linked to #23357 and I have seen there a pull request on going at #24135 
Don't hesitate to close this issue as the solution is on going on another on.
