### ISSUE TITLE
Disable / Enable users with LDAP

### ISSUE THREAD

**Issue by autoantwort** [nextcloud/server#22963]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
We want to disable users with ldap. 

**Describe the solution you'd like**
Add an attribute to the ldap person/entry to disable the person, like the `ownCloudQuota` attribute for quota.

**Additional context**
We want to disable users when they don't pay the networking fee at out dorm.

**Comment by johkoenig** [comment]
Currently, there are several ways to do this:
* You can deactivate the user by hand using the user settings in Nextcloud
* You can disable the whole LDAP account. He will not be able to use Nextcloud (or any other LDAP-connected service) anymore.
* You can limit the access to your Nextcloud to a group and remove that user from this group

maybe @nextcloud/ldap sees this differently, however I think your case is covered.

**Comment by szaimen** [comment]
Based on johkoenig's comment I am closing this.
