### ISSUE TITLE
[user_status] Change the font size and bold

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#22978]
I propose to change the font size and bold in "Recent statuses" for the text string:

- No recent status changes

![obraz](https://user-images.githubusercontent.com/47037905/93715210-50439b80-fb68-11ea-837a-b348e112dfe8.png)

Proposal for a change:

![obraz](https://user-images.githubusercontent.com/47037905/93715221-63566b80-fb68-11ea-82c1-32b7127dec04.png)

https://github.com/nextcloud/server/blob/1a312c4d2a38296fe208c4399ba97a76c88aea11/apps/user_status/src/views/Dashboard.vue#L22-L35

App:
Nextcloud 20.0.0 beta4
User status 1.0.0

**Comment by jneplokh** [comment]
Hey, I'd be happy to take this on. What would the recommended font size be?

**Comment by Valdnet** [comment]
> What would the recommended font size be?

Recommended size: `font-size: 14px;`.

**Comment by jneplokh** [comment]
Got it, about to open a PR!
