### ISSUE TITLE
l10n: There is no button translation in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#22977]
There is no string text for the button in Transifex:

- Reasons to use Nextcloud in your organization

![obraz](https://user-images.githubusercontent.com/47037905/93714927-2f7a4680-fb66-11ea-8b3f-f35e43fe45c9.png)

https://github.com/nextcloud/server/blob/16e1d1cb12229270d61d89dfda93399d056d456c/apps/settings/templates/settings/personal/development.notice.php#L3

App:
Nextcloud 20.0.0 beta4

**Comment by kesselb** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
Fix at https://github.com/nextcloud/server/pull/23014, please review
