### ISSUE TITLE
Failed Federation Share to an LDAP Group

### ISSUE THREAD

**Issue by JonnyTischbein** [nextcloud/server#22971]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud, Create a folder
2. Have a remote Instance (with ldap groups) you don’t control and you want to share with.
3. Enable group federative share on both sides (or just the retrieving side ?)
4. Share your folder with ldap-group@cloud.remote-instance.org or ldap-group@https://cloud.remote-instance.org and retrieve the error
5. (Optional) Share your folder with (nextcloud group) admin@cloud.remote-instance.org or admin@https://cloud.remote-instance.org and retrieve a success

### Expected behaviour
Sharing files to a federated ldap group should work without an error.

### Actual behaviour
When sharing a folder to an federated group which is provided by the remote ldap, I retrieve the error: InvalidArgumentException: Invalid Federated Cloud ID.
Sharing the same folder to the same instance but to an remote “internal” nextcloud group works fine.

### Server configuration

**Operating system:** 
Debian 10 Kernel 4.19.118-2+deb10u1 (2020-06-07) x86_64

**Web server:** 
apache2/buster-backports,now 2.4.46-1~bpo10+1

**Database:** 
mariadb-server/stable,now 1:10.3.23-0+deb10u1

**PHP version:**
php7.3/unbekannt,now 7.3.22-1+0~20200909.67+debian10~1.gbpdd7b72

**Nextcloud version:** (see Nextcloud admin page)
19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

**Where did you install Nextcloud from:**
https://nextcloud.com/install/#instructions-server

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - metadata: 0.12.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - ownpad: 0.6.15
  - password_policy: 1.9.1
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - richdocuments: 3.5.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_pwauth: 2.6.4
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - bookmarks
  - contacts
  - files_external
  - files_pdfviewer
  - nextcloud_announcements
  - photos
  - support
  - survey_client
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "trusted_domains": [
            "cloud.***.***",
            "***.****.***",
            "*****.****.***"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "overwrite.cli.url": "https:\/\/cloud.***.***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "app_install_overwrite": [
            "calendar",
            "ownpad",
            "user_pwauth",
            "documents",
            "richdocuments"
        ],
        "mysql.utf8mb4": true,
        "simpleSignUpLink.shown": false,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
Yes (user password)

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
user_pwauth

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
None
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
cloud.***.**:443 87.123.193.184 - - [20/Sep/2020:10:35:44 +0200] "POST /ocs/v2.php/apps/files_sharing/api/v1/shares HTTP/1.1" 403 1621 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"
cloud.***.***:443 87.123.193.184 - - [20/Sep/2020:10:35:51 +0200] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 304 799 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0"

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
InvalidArgumentException: Invalid Federated Cloud ID

    /var/www/owncloud/lib/private/Collaboration/Collaborators/RemoteGroupPlugin.php - line 60:

    OC\Collaboration\Collaborators\RemoteGroupPlugin->splitGroupRemote("reffis@")

    /var/www/owncloud/lib/private/Collaboration/Collaborators/Search.php - line 70:

    OC\Collaboration\Collaborators\RemoteGroupPlugin->search("reffis@", 200, 0, OC\Collabora ... {})

    /var/www/owncloud/apps/files_sharing/lib/Controller/ShareesAPIController.php - line 213:

    OC\Collaboration\Collaborators\Search->search("reffis@", [ 0,1,4,6,9,10], false, 200, 0)

    /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Files_Sharing\Controller\ShareesAPIController->search("reffis@", "folder", 1, 200, [ "0","1","6 ... "], false)

    /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sh ... {}, "search")

    /var/www/owncloud/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sh ... {}, "search")

    /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Files_ ... r", "search", OC\AppFramew ... {}, { _route: "o ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "o ... "})

    /var/www/owncloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "o ... "})

    /var/www/owncloud/ocs/v1.php - line 88:

    OC\Route\Router->match("/ocsapp/app ... s")

Verursacht durchInvalidArgumentException: Invalid cloud id

    /var/www/owncloud/lib/private/Collaboration/Collaborators/RemoteGroupPlugin.php - line 87:

    OC\Federation\CloudIdManager->resolveCloudId("reffis@")

    /var/www/owncloud/lib/private/Collaboration/Collaborators/RemoteGroupPlugin.php - line 60:

    OC\Collaboration\Collaborators\RemoteGroupPlugin->splitGroupRemote("reffis@")

    /var/www/owncloud/lib/private/Collaboration/Collaborators/Search.php - line 70:

    OC\Collaboration\Collaborators\RemoteGroupPlugin->search("reffis@", 200, 0, OC\Collabora ... {})

    /var/www/owncloud/apps/files_sharing/lib/Controller/ShareesAPIController.php - line 213:

    OC\Collaboration\Collaborators\Search->search("reffis@", [ 0,1,4,6,9,10], false, 200, 0)

    /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 170:

    OCA\Files_Sharing\Controller\ShareesAPIController->search("reffis@", "folder", 1, 200, [ "0","1","6 ... "], false)

    /var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Files_Sh ... {}, "search")

    /var/www/owncloud/lib/private/AppFramework/App.php - line 137:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Files_Sh ... {}, "search")

    /var/www/owncloud/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47:

    OC\AppFramework\App::main("OCA\\Files_ ... r", "search", OC\AppFramew ... {}, { _route: "o ... "})

    <<closure>>

    OC\AppFramework\Routing\RouteActionHandler->__invoke({ _route: "o ... "})

    /var/www/owncloud/lib/private/Route/Router.php - line 297:

    call_user_func(OC\AppFramew ... {}, { _route: "o ... "})

    /var/www/owncloud/ocs/v1.php - line 88:

    OC\Route\Router->match("/ocsapp/app ... s")
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
ShareRequests.js:61:12
Error while creating share Error: Request failed with status code 403
    exports createError.js:16
    exports settle.js:17
    onreadystatechange xhr.js:61
```
</details>

**Comment by LedzZm** [comment]
Hey there,

Are you still having this issue?

I stumbled upon it as well. Could it be that you are using a self-signed ssl certificate?
I am (for now), and I am lead to believe that it has something to do with the present issue. If you are using a non self-signed certificate, then it might be a false negative on my end. I could be seeing just a layer on top of the main issue which could very well be the ldap integrated users, which I also have in my case.

I will come back to this, if I discover anything else.

**Comment by JonnyTischbein** [comment]
Hi,

no I'm using a Let's encrypt certificate and for test reasons no TLS for the ldap connection

**Comment by LedzZm** [comment]
This operation performs an ajax request to actually do the federated share. In my case, in the error message it was hinted that the issue lies with the certificate. Have you checked the response in your network tab to see if you get something else, more informative?

**Comment by JonnyTischbein** [comment]
For me it works now.

Tested from NC 19.0.3 to 20.0.4.

Should I close ?

**Comment by LedzZm** [comment]
> 
> 
> ~For me it works now.~
> 
> ~Tested from NC 19.0.3 to 20.0.4.~
> 
> ~Should I close ?~
> 

> ```

For me the Issue appears in 20.0.5

I will be upgrading to 21 soon probably, so I could check if it works in the newest version and reply here. 
But I can't tell when this will happen exactly.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by JonnyTischbein** [comment]
I will test it soon, after upgrading my instances.

**Comment by JonnyTischbein** [comment]
Thanks a lot!
It is working now. I tested both direction:
- from `21.0.2` to ldap-group on `20.0.10`
- from `21.0.10` to ldap-group on `20.0.2`
