### ISSUE TITLE
.LRDATA file shown as folders on nextcloud server side

### ISSUE THREAD

**Issue by poudenes** [nextcloud/server#22970]
Hi ALl,

I use Lightroom on my OSX. Lightroom have some files ending with **.LRDATA** when I sync those to my nextcloud server nextcloud change them to folders. This creates LOT of conflict problems... 

Here structure in finder OSX
![finder_osx](https://user-images.githubusercontent.com/4399532/93707035-d42b6280-fb2b-11ea-8dea-4447fc3b5207.png)

**Here how they show in the Nextcloud OSX App**
![nextcloud_app](https://user-images.githubusercontent.com/4399532/93707037-d55c8f80-fb2b-11ea-838e-6aec82be6dd3.png)

**Here how they show on server command line**
![nextcloud_commandline](https://user-images.githubusercontent.com/4399532/93707038-d5f52600-fb2b-11ea-93bd-542669a8c2c4.png)

**Here how they show in Nextcloud web portal**
![nextcloud_webserver](https://user-images.githubusercontent.com/4399532/93707039-d68dbc80-fb2b-11ea-95b8-b318afb2e5bb.png)

Question:

1) Can I change something so nextcloud see them as files and not as folders?
2) what can I do to perform system to avoid all the conflicts? Its to many folders to check all the conflict on server side

**Comment by szaimen** [comment]
> * Can I change something so nextcloud see them as files and not as folders?

No since they are folders

> * what can I do to perform system to avoid all the conflicts? Its to many folders to check all the conflict on server side

See e.g. https://github.com/nextcloud/desktop/issues/1288 https://github.com/nextcloud/desktop/issues/3429
