### ISSUE TITLE
l10n: Translation of the text string "Linked accounts"

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#22986]
After installing eg: "Discourse Integration" there is no translated text string "Linked accounts" for the user and administrator in "Settings".
The text string also does not appear in Transifex to translate native language.

![obraz](https://user-images.githubusercontent.com/47037905/93747500-18376980-fbf7-11ea-8275-dcc9e81738f9.png) ![obraz](https://user-images.githubusercontent.com/47037905/93747721-62b8e600-fbf7-11ea-9b35-28e48aa056fa.png)

**Comment by kesselb** [comment]
cc @eneiluj

**Comment by eneiluj** [comment]
You should post issues related with Discourse integration in this app's repo : https://github.com/nextcloud/integration_discourse

What you are facing is expected. This string was changed to "Connected accounts" and will be included in next app's release.
