### ISSUE TITLE
Reduce font size and remove bold of search empty content notice

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#22987]
I propose to change the font size and bold in "Start typing to search" for the text string:

![obraz](https://user-images.githubusercontent.com/47037905/93748770-1373b500-fbf9-11ea-9048-852f7a1076a0.png)

Proposal for a change:

![obraz](https://user-images.githubusercontent.com/47037905/93748906-47e77100-fbf9-11ea-8b43-163093b43518.png)

App:
Nextcloud 20.0.0 beta4

**Comment by kesselb** [comment]
cc @jancborchardt @skjnldsv

**Comment by jancborchardt** [comment]
Yep, it indeed looks a bit off since it’s different from the emptycontent of Notifications, as well as the loading feedback of the Contacts menu.

Would look better with the same font size (standard text size) and non-bold as you say.

**Comment by Valdnet** [comment]
@jancborchardt Responsible for this:
https://github.com/nextcloud/server/blob/d77d52d2575043d9f50d32a45875f2299b2d2b61/core/css/apps.scss#L21-L27

This also affects the user's status in the Dashboard.
Issue: #22978

**Comment by vivienhennig** [comment]
Hey, can I work on this?

**Comment by Valdnet** [comment]
@vivienhennig It would be very good to correct it :wink:.

> Hey, can I work on this?

Create a PR and wait for developer approval.

**Comment by skjnldsv** [comment]
> @skjnldsv if you point out where this would have to be changed, this would make for a nice "good first issue". :)

This is using the EmptyContent component
