### ISSUE TITLE
Subdirectories within and encrypted directory are not encrypted or accessable

### ISSUE THREAD

**Issue by seanthegeek** [nextcloud/server#22997]
### Steps to reproduce
1. Create end-to-end-encrypted folder on a server running the Owncloud Snap
2. Add contents, including subdirectories using 2.x client
3. Attempt to modify contents using a 3.0.1 client

### Expected behaviour
Files and directories within end-to-end encrypted directories must be encrypted, and must be editable when using a Nextcloud client

### Actual behaviour

The files and subdriectories within an encrypted directory are not encrypted, and contents can be viewed via a web browser

![image](https://user-images.githubusercontent.com/44679/93841216-d7743a80-fc60-11ea-84cb-e51e9bf3add1.png)

Attempting to add/remove/modify contents results in an error:

```text
OCA\DAV\Connector\Sabre\Exception\Forbidden: Write access to end-to-end encrypted folder requires token - no token sent

    /var/snap/nextcloud/23171/nextcloud/extra-apps/end_to_end_encryption/lib/Connector/Sabre/LockPlugin.php - line 153:

    OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->verifyTokenOnWriteAccess(OCA\DAV\Conn ... {}, null)

    /snap/nextcloud/23171/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

    OCA\EndToEndEncryption\Connector\Sabre\LockPlugin->checkLock(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

    /snap/nextcloud/23171/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 458:

    Sabre\DAV\Server->emit("beforeMethod:PUT", [ Sabre\HTTP ... }])

    /snap/nextcloud/23171/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

    /snap/nextcloud/23171/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

    Sabre\DAV\Server->start()

    /snap/nextcloud/23171/htdocs/apps/dav/lib/Server.php - line 320:

    Sabre\DAV\Server->exec()

    /snap/nextcloud/23171/htdocs/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /snap/nextcloud/23171/htdocs/remote.php - line 167:

    require_once("/snap/nextc ... p")
```

### Server configuration
**Operating system**:
Ubuntu

**Web server:**
From Snap

**Database:**
From snap

**PHP version:**
From snap

**Nextcloud version:** (see Nextcloud admin page)

19.0.3snap1

**Updated from an older Nextcloud/ownCloud or fresh install:**

The snap auto-updates

**Where did you install Nextcloud from:**
 Snap

**Are you using encryption:** yes

**Comment by WhiteBahamut** [comment]
can this be related to https://github.com/nextcloud/desktop/issues/2314? At least the same exception on the server happens

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2 and desktop v3.2.2? If not, please close this issue. Thanks! :)
