### ISSUE TITLE
Viewer does not play audio files because nobody added support for it (yet).

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#22991]
Hallo,
i want to play audio files (e.g. .mp3) in a default nextcloud installation without audio-plugin e.g. in Nextcloud from https://nc.nl.tab.digital.

Can someone insert audio support in the multimedia viewer?

@kesselb wrote:
Your conclusion is wrong. Viewer does not play audio files because nobody added support for it (yet).

**Comment by kesselb** [comment]
Are you kidding 🤔

**Comment by devnull4242** [comment]
No. But i think a modern sharing and collaboration platform should support by default video and audio. Maybe I am wrong.
