### ISSUE TITLE
Req: "smarter" handling of context menu

### ISSUE THREAD

**Issue by YouveGotMeowxy** [nextcloud/server#22996]
I'm currently using the latest version of NC (docker image) but have noticed this issue in previous versions as well.

When looking at a list of thumbnails (I think this also happens in all other areas as well, other than just images) and then clicking the ellipse to bring up the context menu, the very bottom row will clip the menu so that you can't see all menu items.

I'm assuming this is related to the number of addons/apps you've added that will expand the number of menu items. Perhaps some sort of "smarter" handling where the amount of space required for the menu is calc'd before it's shown so that the entire menu's items show no matter where it originates?

Screenshot shows the menu item on the left from a row of images NOT on the bottom row; the right is from the bottom row if images:

![image](https://user-images.githubusercontent.com/39491297/93797621-16bf6e80-fc02-11ea-9e06-d234c94c3de5.png)

This is a usability issue because for 1, many people, like myself, click that menu to use the Delete menu item, and if on the bottom row, the Delete item doesn't show, so you have to then click the checkbox, click the "Actions" menu at the top, and then click it's Delete item. Side Note: it would also be very handy to allow using the Delete key on the keyboard to delete items (with a confirmation option).

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by nimisha-vijay** [comment]
Have you tried scrolling once the menu is opened?
You can also try right clicking anywhere on the file you want, that will open the menu at your cursor.
