### ISSUE TITLE
Delete old oc_bruteforce_attempts entries automatically

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/server#22993]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.  use nextcloud (with bruteforce protection enabled) for a while

### Expected behaviour
Entries in oc_bruteforce_attempts should be cleaned up automatically. Maybe it's to discuss if keep them for a week or a month. But these entries should be removed to be GDPR compliant.

### Actual behaviour
The table oc_bruteforce_attempts fills up with old entries. I got about 200k entries from 4 years.

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Apache
**Database:**
MariaDB
**PHP version:**
7.3 (fpm)
**Nextcloud version:** (see Nextcloud admin page)
19.0.3
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated

### Logs

No errors or warnings.

### Workaround
Running 
```sql
delete from oc_bruteforce_attempts where occurred<unix_timestamp(DATE_SUB(NOW(), INTERVAL 7 DAY));
```
via mysql client / cronjob.

**Comment by J0WI** [comment]
Fixed in #23287
