### ISSUE TITLE
Feature request: Use user email in reply-to header for all notification emails

### ISSUE THREAD

**Issue by xylo** [nextcloud/server#22990]
### Current state

When a user shares a file his/her email address appears in the reply-to header of the notification emails:

https://github.com/nextcloud/server/blob/339e32006479daf9e11152c386c34e6b2d757cf2/lib/private/Share20/Manager.php#L757-L761

### Problem

Unfortunately this feature does not apply to the following actions:

- when a new user is created
- when a user is assigned/removed to/from a group

So whenever someone reply to those notification emails the reply goes to the system admin instead of the user who did the action.  (And I have to manually forward those replies to the user in charge)

### Solution

Please use the same feature as mentioned above (user email address in reply-to header) for all notification emails.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
