### ISSUE TITLE
Error deleting zombie file

### ISSUE THREAD

**Issue by pilsnerbeer** [nextcloud/server#23006]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

There exist a bug in Nextcloud that will turn a normal file into a zombie one that is stuck in the directory and can not be removed. ( it is visible on other apps, too). I am using NC with a provider and dont have full server access, which makes it that worse as I can not delete the file myself. I had precisely this issue when I hosted NC myself over a year ago. Even though I am not able to provide much of info now, I think it is necessary to raise awareness of this issue. 

As for the cause/exact steps, they are unknown.

### Steps to reproduce
1. file is uploaded to the server
2. something happens
3. file becomes zombie & cant be interacted with. 

### Expected behaviour
user can delete files
### Actual behaviour
user can't delete/rename/move zombie file

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**Are you using external storage, if yes which one:**  no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Could you contact the provider and ask for the log files?

**Comment by pilsnerbeer** [comment]
I was trying to delete the file yesterday and it suddenly deleted. It wasn't being used/downloaded or anything during that time, it just started working and I could get rid of it. So unfortunately I cant provide any further info. I asked the provider but they don't keep the logs. Pity, but I'm sure sooner or later the issue will arise once again.

**Comment by pilsnerbeer** [comment]
I now suspect there may be a bug regarding file "lock" - that is, you can't do anything with a file (move/delete) while its being downloaded using desktop client. (That is easily reproducible). I know that I wrote that the file wasnt being downloaded while I tried deleting it but it could've been that it was still somehow locked (which would explain me finally being able to delete it after some time later).

**Comment by szaimen** [comment]
So this honestly looks like expected: if the desktop client downloads the file it should be locked.
Please open a new issue with logs attached if you should experience this issue again. Thanks!
