### ISSUE TITLE
App/device password missing, probably after some upgrade

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#2300]
I used to have a device password for my mobile. After going to todays daily it is missing on the list on the personal page and my phone asks me to update the account, i.e. the device password is apparently lost. On the internal instance. Name for the device password probably contained "jolla c", or at least "jolla", unknown case.

@LukasReschke

**Comment by MorrisJobke** [comment]
For me it's there on master. Could you checkout if this is also missing on master?

**Comment by blizzz** [comment]
@MorrisJobke can't, @LukasReschke will check whether the password is indeed gone from the DB later.

**Comment by MorrisJobke** [comment]
And on current daily I also see the entry :(

**Comment by blizzz** [comment]
It seems it is a bit more stange. I combed through the logs.

Upgrade from 9.1.1.5 to 11.0.0.2 was done this morning at 9.21.36 am, but at this point of time the issue was already present.

The first failed login was recoded at 21:17:03 yesterday.

What happened previously? A couple of updates

```
{"reqId":"yAO4fDJIrmKne6smAHds","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.5 to 9.1.1.5","level":0,"time":"2016-11-23T21:16:51+00:00","method"
:"--","url":"--","user":"--"}
…
{"reqId":"Q4WQMRjN+aqrQJqRwX5v","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.5 to 9.1.1.5","level":0,"time":"2016-11-23T21:17:41+00:00","method"
:"--","url":"--","user":"--"}
…
{"reqId":"eKPuCxIg+RRQqE++Cg\/V","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.5 to 9.1.1.5","level":0,"time":"2016-11-23T21:18:22+00:00","method
":"--","url":"--","user":"--"}
…
{"reqId":"cWkuNi+MGMw5z6Gfroxl","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.5 to 9.1.1.5","level":0,"time":"2016-11-23T21:19:30+00:00","method":"--","url":"--","user":"--"}
```

However none of the recorded UPDATE database statements were related. No DELETE statement was recorded.

**Comment by LukasReschke** [comment]
> What happened previously? A couple of updates, but one that was before this occurence.

Yesterday I updated the spreed app quite some time so that triggered some update routines to run. No server update was involved yesterday.

**Comment by blizzz** [comment]
I went down the log until <6pm yesterday, but could not spot anything suspicious.

**Comment by MorrisJobke** [comment]
> Yesterday I updated the spreed app quite some time so that triggered some update routines to run. No server update was involved yesterday.

Maybe there is a malicious repair step? Is the entry dropped from the database for your app password?

**Comment by MorrisJobke** [comment]
This is then maybe related to https://github.com/nextcloud/server/pull/2299#issuecomment-262784461

**Comment by blizzz** [comment]
> Maybe there is a malicious repair step? Is the entry dropped from the database for your app password?

I assume so, but have no access to the DB.

**Comment by rullzer** [comment]
Maybe it is just related to https://github.com/nextcloud/server/issues/2431

**Comment by blizzz** [comment]
@rullzer yes, that might be it

**Comment by ChristophWurst** [comment]
@blizzz which user back end was used? Was it an external one like in https://github.com/nextcloud/server/issues/2431#issuecomment-264141308?

**Comment by blizzz** [comment]
@ChristophWurst yes, LDAP

**Comment by nickvergessen** [comment]
Closing in favor of #2431 then
