### ISSUE TITLE
Set language at user creation on WebUI

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#23039]
The ability to set the language on the user creation form could be something useful on a multi user environment.

**Comment by gratuxri** [comment]
Hello, I'm not sure, if this is a good idea, because of browser language setting, also if someone choose in browser preffered language, this language shoud use nextcloud. What do you think about that?

**Comment by acsfer** [comment]
My main problem is the welcome email language at user creation.

**Comment by skjnldsv** [comment]
Might be easier to add with https://github.com/nextcloud/server/pull/23529

**Comment by joshtrichards** [comment]
I can't find the associated PR, but this is done in NC28:

![image](https://github.com/nextcloud/server/assets/1731941/13fd391d-c45c-4132-8f12-4937afe2b43e)
