### ISSUE TITLE
Weakness in function getAppTemplateDirs

### ISSUE THREAD

**Issue by quenenni** [nextcloud/server#23037]
Hello,

The line "if (file_exists($app_dir.'/templates/')) {" in the file function getAppTemplateDirs from the file lib/private/Template/Base.php can lead to template problems (internal server problem).

I explained the problem and gave a solution here https://help.nextcloud.com/t/suddenly-internal-server-error/91029

I'm using Nc 19.0.1.1

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing as duplicate of https://github.com/nextcloud/server/issues/14115.
