### ISSUE TITLE
Custom css for theme

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#23045]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. copy core/css/header.scss into you custom theme themes/mytheme/core/css/header.scss
2. add some more css rules, or override current
3. run `sudo -u www-data php occ  maintenance:theme:update`

### Expected behaviour
I see changes on the page

### Actual behaviour
I don't see any changes

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
19.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

[Docs](url) says: 
```
The folder structure of a theme is exactly the same as the main Nextcloud structure. You can override js files, images, translations and templates with own versions. CSS files are loaded additionally to the default files so you can override CSS properties.
```
I've copied core/css/header.scss to my theme folder themes/mytheme/core/css/header.scss, made some changes (or added few more). Nothing changed after `sudo -u www-data php occ  maintenance:theme:update`. 
In the same time, when I'm adding such changes into core css files, I see all changes.

**Comment by szaimen** [comment]
Hi, please use this app https://apps.nextcloud.com/apps/theming_customcss
Thanks!
