### ISSUE TITLE
Nextcloud Desktop Client: Virtual Folder

### ISSUE THREAD

**Issue by officialjuhoo** [nextcloud/server#23053]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Just like the ownCloud desktop client, it would be very advantageous if you don't have to synchronize all your files so that you can also view them as virtual files. Like the OneDrive Client

**Describe alternatives you've considered**
To be able to use this feature, I am currently using the Owncloud desktop client for my Nextcloud

**Additional context**
.

**Comment by kesselb** [comment]
Closing your report in favour of https://github.com/nextcloud/desktop/issues/1951.
