### ISSUE TITLE
Customized themes partially broken

### ISSUE THREAD

**Issue by ManfredSteiner** [nextcloud/server#23059]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Change color in function `getScssVariables()` and `getColorPrimary()`  in theme example (*themes/example/default.php*)
2. add `  'theme' => 'example',` to file *configs/config.php*
3. reload webpage ... -> no change of color

Change of variable `$color-primary: #0082c9 !default;` in file *core/css/variables.scss* works fine. Same bug on logo, ...

### Expected behaviour
Customized themes should work as expected (primary color, logo, favicon, ...)

### Actual behaviour
Some theme-features like favicon.ico in themes/example/core/img are working as expected.
Other theme-features in example primary color or themes/example/core/img/logo/logo.svg are not working. In this case you have to overwrite or modify files in normal file locations.

### Server configuration

**Operating system:** Ubuntu 18.04.5 LTS

**Web server:** apache2 (2.4.29-1ubuntu4.14)

**Database:** mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**PHP version:** PHP 7.2.24-0ubuntu0.18.04.6

**Nextcloud version:** 19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** download nextcloud-19.0.3.zip

**Comment by szaimen** [comment]
Sorry but IIRC will this not be fixed because we think about removing legacy themes:
https://github.com/nextcloud/server/issues/27433
