### ISSUE TITLE
Update to 20.0.0RC2 fails from beta4.  Could not copy "/data/nextcloud/apps/dashboard/js/dashboard.js.map"

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#23068]
[Updater.log](https://ybin.me/p/88ada772bdcc0c70#S7Sovi0dco1/1oBPGyarJ1ujQ43PSxLjCleVHceTP8k=)

`Could not copy "/data/nextcloud/apps/dashboard/js/dashboard.js.map" to "/data/nextcloud/data/updater-ochxgtum9iy3/backups/nextcloud-20.0.0.6/apps/dashboard/js/dashboard.js.map"`

Now the webui displays: `It looks like you are trying to reinstall your Nextcloud. However the file CAN_INSTALL is missing from your config directory. Please create the file CAN_INSTALL in your config folder to continue.`

Server configuration detail
Operating system: Linux 5.8.5-meson64 #20.08.1 SMP PREEMPT Tue Sep 1 18:47:20 CEST 2020 aarch64
Webserver: Apache (fpm-fcgi)
Database: mysql 10.3.23
PHP version: 7.3.19-1~deb10u1

Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

Nextcloud version: 20.0.0 Beta 4 - 20.0.0.6

Updated from an older Nextcloud

Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.1
 - admin_audit: 1.10.0
 - apporder: 0.11.0
 - bookmarks: 3.3.4
 - breezedark: 19.0.4
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - cms_pico: 1.0.10
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - cpanelmailsync: 0.0.7
 - customproperties: 1.0.1
 - dashboard: 7.0.0
 - dav: 1.16.0
 - deck: 1.1.0-beta2
 - end_to_end_encryption: 1.6.2
 - external: 3.7.0
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - flow_notifications: 1.0.1
 - globalsiteselector: 1.3.0
 - integration_mastodon: 0.0.3
 - integration_reddit: 0.0.2
 - login_notes: 0.3.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.4.1
 - news: 14.2.2
 - nextcloud_announcements: 1.9.0
 - nextcloudpi: 0.0.1
 - notes: 3.6.4
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - polls: 1.5.1
 - previewgenerator: 102.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - qownnotesapi: 20.9.0
 - recommendations: 0.8.0
 - riotchat: 0.6.10
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - sharingpath: 0.2.5
 - side_menu: 1.16.0
 - spreed: 10.0.0-rc.2
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - talk_matterbridge: 1.18.3
 - tasks: 0.13.3
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflow_script: 1.5.0
 - workflowengine: 2.2.0

**Comment by kesselb** [comment]
Still relevant?

**Comment by sunjam** [comment]
No longer seeing this as of 20.0.1

Thanks
