### ISSUE TITLE
Shared files that get deleted are not cleaned up in the database

### ISSUE THREAD

**Issue by MrShoenel** [nextcloud/server#23064]
Hey,
it appears that shares to files that get deleted are never cleaned up in table `oc_share`. Running the cleanup commands `occ sharing:cleanup-remote-storage` and `occ dav:remove-invalid-share` does not resolve the issue, and neither does the Cronjob.

### Steps to reproduce
1. Share a file with another user on the same server
2. Delete the file, also delete from trash (purge)
3. Entry in the said table does not disappear

### Expected behaviour
* The entry in the table should disappear.

### Actual behaviour
* The entry remains.

### Server configuration

**Operating system:**
CentOS 7.6

**Web server:**
nginx/1.19.2

**Database:**
MySQL/5.7.30

**PHP version:**
PHP/7.4.10

**Nextcloud version:** (see Nextcloud admin page)
19.0.2 (latest)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Not a fresh install

**Where did you install Nextcloud from:**
Using the built-in updater

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
