### ISSUE TITLE
Search window for Apps

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#23062]
### Steps to reproduce

1. Select Apps from the menu.
2. Click in the search window.
3. Enter the name of the app to search for.

### Expected behaviour
Disabling the search results window for an app.

### Actual behaviour
Visible search results window for the application.

![obraz](https://user-images.githubusercontent.com/47037905/94339970-72249e80-fffe-11ea-8070-36751ef89da4.png)

The visible search results window is in my opinion unnecessary and also misleading. The message: "No results for xxx" confuses the search result. The search window also obscures the current searched applications.

![obraz](https://user-images.githubusercontent.com/47037905/94340164-dc8a0e80-ffff-11ea-8a52-907d7828ae59.png)

**Nextcloud version:** (see Nextcloud admin page)
20.0.0 RC2

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by szaimen** [comment]
lets track this in https://github.com/nextcloud/server/issues/23127
