### ISSUE TITLE
NC 20 hash_equals(): Expected user_string to be a string, bool given at /var/www/nextcloud/lib/private/Security/Crypto.php#138

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#23078]
I keep getting this error on all my NC 20 instances. 

![image](https://user-images.githubusercontent.com/59488153/94452503-395b0580-0175-11eb-8419-722c091ef3b3.png)
![image](https://user-images.githubusercontent.com/59488153/94452588-5394e380-0175-11eb-9eec-c09c16544cce.png)
'![image](https://user-images.githubusercontent.com/59488153/94452373-0d3f8480-0175-11eb-8a21-951904777ee0.png)

**Comment by fabianbusch** [comment]
I have the same error since upgrade from 19.0.4 to 20.0.0 

Error: hash_equals(): Expected user_string to be a string, bool given at

**Comment by thomsen-rockt** [comment]
I have the same issue after upgrade from 19.0.4 to 20.0.

**Comment by hg1978** [comment]
Same for me here.. With 19.0.4 all fine since 20.0 and now 20.0.1 same error. It happens also while using Nextcloud iOS app (newest version).

**Comment by Obi-Wahn** [comment]
I have the same issue after upgrade from 19.0.4 to 20.0.1

**Comment by axheli** [comment]
hopefully they have a fix soon.

**Comment by mpranj** [comment]
+1

**Comment by axheli** [comment]
dup #23197
