### ISSUE TITLE
Search Limit, Pagification, Show more

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#23082]
The Search in nextCloud is impressively fast, and repeatedly helps me lots. However, there are times it fails.

Namely, with the number of results and how that gets handled.

Can we please get:
1. The ability to set the # of results per search/page of search
2. The ability to pagify search results (OR)
3. The ability to "show more results"

Also, if we could get searches filtered by Tags, that would be really awesome too! Please? :D

**Comment by Spartachetto** [comment]
I think that the "searches filtered by tags" would need another issue. Or maybe try to suggest it here: #22092

**Comment by jancborchardt** [comment]
The search will be completely renewed for Nextcloud 20 which will be released soon, did you already see that?

**Comment by BloodyIron** [comment]
> The search will be completely renewed for Nextcloud 20 which will be released soon, did you already see that?

I haven't looked into NC20 yet, have the feature notes been announced?

**Comment by jancborchardt** [comment]
No, the announcement and release will be this weekend for our Nextcloud Conference :) https://nextcloud.com/conf-2020/

**Comment by BloodyIron** [comment]
Well then how could I have seen it? heheh. Well hopefully this is addressed with NC20 then! :D

**Comment by jancborchardt** [comment]
If you try out the master branch. ;)

In any case, I’ll close this since it’s likely addressed with the new search. Feel free to open new, separate issues for any problems you encounter with search in Nextcloud 20.
