### ISSUE TITLE
Missing delete option for email shares in the sidebar

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2308]
I guess this is because the trash icon was moved to the "..." menu?

@schiessle @jancborchardt 

> ![files_-_nextcloud_-_2016-11-24_15 32 04](https://cloud.githubusercontent.com/assets/213943/20601904/35a016d2-b25b-11e6-9896-69d8b453a65a.png)

**Comment by schiessle** [comment]
> I guess this is because the trash icon was moved to the "..." menu?

Probably, the unshare button was there when the feature was merged... I will have a look.

**Comment by jancborchardt** [comment]
@schiessle shouldn’t the share by mail feature also have the »can edit« checkbox? Cause it sends out a shared link for that person, and depending on the permission it’s like »Allow upload and editing« for public link shares.

**Comment by schiessle** [comment]
@jancborchardt it has, but only for folders, similar to the public link. If you open a link you get the same view as for a public link. This means that for a single file you only have a preview and a option to download it but no possibility to upload a modified version, so it doesn't make sense to have a "can edit" permission for single files shared by mail.
