### ISSUE TITLE
Advanced File Tagging

### ISSUE THREAD

**Issue by mar1u5** [nextcloud/server#231]
I like the idea of tags, but I think that there is still place for improvement. Currently, there are some tag-features implanted in the ownCloud 9.0 Enterprise Edition, which should be rewritten for Nextcloud:

## [Tag Manager](https://github.com/nextcloud/server/pull/494)
The Tag Manager is for creating new tags, editing existing tags, and deleting tags. Tags may be made Visible and assignable by all users, Not-assignable by normal users, or Invisible to normal users.

## [Automatic Tagging](https://github.com/nextcloud/files_automatedtagging)
The Automatic Tagging module operates on newly-uploaded files. Create a set of conditions, and then when a file or folder matches those conditions it is automatically tagged. The tag must already have been created with the Tag Manager. For example, you can assign the invisible tag iOS Uploads to all files uploaded from iOS devices. This tag is visible only to admins.

## Retention
The Retention module is your housecleaning power tool, because it automatically deletes files after a time period that you specify. Select which tag to set a time limit on, and then set your time limit. File age is calculated from the file mtime (modification time).

(https://doc.owncloud.org/server/9.0/admin_manual/enterprise_file_management/files_tagging.html)

_I'd also like the option to make tags private (only for own user or inside of groups) ... especially for shared environments_ 😉 

cc @karlitschek @MorrisJobke @LukasReschke

**Comment by karlitschek** [comment]
Agreed. We should have an open source implementation for Nextcloud

**Comment by mar1u5** [comment]
cc'ing @nickvergessen because he has written the EE-app "workflow" :wink:

**Comment by nickvergessen** [comment]
Group based tags have been added in oc9.1 iirc, maybe you can abuse that. But other then that, remember that we are talking about global/system-wide tags here for a reason. User based tags exist since a long time, they only don't have an UI

**Comment by nickvergessen** [comment]
Added "Tag management" for normal and admin tags:
https://github.com/nextcloud/server/issues/494

**Comment by nickvergessen** [comment]
Automated tagging: https://github.com/nextcloud/files_automatedtagging

**Comment by nickvergessen** [comment]
Retention app is done:
https://github.com/nextcloud/files_retention

**Comment by Henry-White** [comment]
Tags are not shown/sharing when using external storage [https://github.com/nextcloud/server/issues/13113](url)
