### ISSUE TITLE
Do not show apps results if you're on `/apps/settings/apps`

### ISSUE THREAD

**Issue by skjnldsv** [nextcloud/server#23103]
Unified search followup :)

When searching on the apps management page, we should not return any results from the app navigation entries. This is conflicting and confusing.

**Comment by divyavit** [comment]
Can you please tell in more detail what exactly has to be done in this issue

**Comment by skjnldsv** [comment]
> Can you please tell in more detail what exactly has to be done in this issue

I updated the main post

**Comment by weeman1337** [comment]
@skjnldsv for me the search box does not show app results if being in the apps management.  
And that annoys me ;) See #23127

**Comment by skjnldsv** [comment]
@weeman1337 this is different, try searching for an installed app: like calendar.
This will be confusing as people will think the entry on the unified search is the one on the apps management

**Comment by blizzz** [comment]
cannot reproduce
