### ISSUE TITLE
Upload Folder

### ISSUE THREAD

**Issue by mikrofyr** [nextcloud/server#23106]
There is not "Upload Folder" function in the "+" menu.
![menu](https://user-images.githubusercontent.com/24606037/94671139-c3d96b80-0313-11eb-93f0-c2af17b95eb9.PNG)

Drag and drop is not always nice, should be in menu.

**Comment by acsfer** [comment]
AFAIK, you can't select a folder. If you select a folder and click Open, it will open the folder to show it's contents, and not select it.
So Drag'n'Drop is the only option i know, with Nextcloud or other systems.

**Comment by mikrofyr** [comment]
Droppy has support for uploading folder via menu: https://github.com/silverwind/droppy
It also has ability to rename files, but lack several things that Nexcloud has. 

docker run --name droppy -p 8989:8989 silverwind/droppy to give it a spin. 
Would something like that be possible?

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
