### ISSUE TITLE
Add global variable to change icons colors

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#23111]
**Is your feature request related to a problem? Please describe.**
For now there is only one way to change color of icons in topmenu and files icons color - via Theming app. For those, who use their custom theme there is no simple way to change that colors. 

**Describe the solution you'd like**
Add variables for changing color of icons to variables.css files 

**Describe alternatives you've considered**
No alternatives

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
