### ISSUE TITLE
Error uploading file: Not enough free space... when using Webinterface

### ISSUE THREAD

**Issue by motatuc** [nextcloud/server#2311]
Hello.

Just installed Nextcloud on my server with the setup-nextcloud.php-script.
Finished without any problems. Login working fine. But I cannot upload any files (doesn't matter what size) via the Webinterface. 

Strange thing is I can delete any file via Webinterface. Something is really wrong here.
Space is 170G left, no quotas, no wrong permissions of folders (otherwise I would not be able to delete)

### Steps to reproduce
1. Login Nextcloud
2. Open the file chooser
3. Press upload

### Expected behaviour
The file gets uploaded.

### Actual behaviour
Error uploading file "TranscriberAG-2.0.0-b1.tar.gz": Not enough free space, you are uploading 8.5 MB but only 0 B is left

Nothing in nextcloud.log

**List of activated apps:**

Standard activated apps. Firstrunwizard disabled.

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no
```
PHP

Version: 5.5.38
Memory Limit: 512.0 MB
Max Execution Time: 3600
Upload max size: 513.0 MB
```

```
Database

Type: mysql
Version: 5.6.33
Size: 3.9 MB
```

**Comment by motatuc** [comment]
Even more strange: Using the nextcloud app for android, I can upload files just fine. It must have be something that is related to the webinterface. What could that problem be?

**Comment by MorrisJobke** [comment]
cc @icewind1991

**Comment by motatuc** [comment]
Hello.

Any idea about that problem? I already checked these similar owncloud issues but the solutions posted there did not help.

https://github.com/owncloud/core/issues/15030
https://github.com/owncloud/core/issues/18886
https://github.com/owncloud/core/pull/19533


I tried to change file-upload.js
```
freeSpace = $('#free_space').val();
to
freeSpace = 1000000000;
```
Now I am able to upload files BUT I get this message right after uploading:
```
Error uploading file "TranscriberAG-2.0.0-b1.tar.gz": Not Found
```

Any idea how to proceed now and how to solve this problem (whatever it actually is)?

@icewind1991: I see you were set as cc. Do you got an idea?

**Comment by nickvergessen** [comment]
@motatuc did you solve this issue already?

**Comment by motatuc** [comment]
No, unfortunately I did not. I gave up because nobody seems to know a solution to my problem.

**Comment by mnewmedia** [comment]
I also have this, dev tools shows:
```
 GET https://sub.domain.com:7070/nextcloud/index.php/apps/files/ajax/getstoragestats.php?dir=%2F 
404 ()
```
Has maybe todo with using it with a proxy and docker.

**Comment by motatuc** [comment]
@mnewmedia Did you find a solution for this problem?

**Comment by mnewmedia** [comment]
not yet, but I highly assume it has to do with using it behind a proxy, since it's working on localhost.
And I have currently no time to look further into this problem :(

**Comment by motatuc** [comment]
I see. @mnewmedia If you find a solution, it would be nice if you share it here. Thanks.

**Comment by motatuc** [comment]
Question to the developers here: Is there still no idea/solution to that problem? I would now have to use commercial nextcloud solutions but I'd rather like to run it on my own....

**Comment by thalex80** [comment]
I have the same issue. In addition I cannot set quotas for my users. I followed **[Aptalca's Nginx-Letsencrypt to Reverse Proxy LSIO's Nextcloud](https://forums.lime-technology.com/topic/49743-how-to-use-aptalcas-nginx-letsencrypt-to-reverse-proxy-lsios-nextcloud/)** - guide for my setup. Upload via WEBDAV is working fine.

I can upload files again locally if I 

- disable Letsencrypt

- set **root /config/www/;** back to **root /config/www/nextcloud/**; in nextcloud/config/nginx/site-confs/defaults

- outcomment the **overwritexxx parameter** in the config.php

So I also assume an issue with the proxy

**Comment by jbyvosges** [comment]
Same for me : Cannot upload any files.

**Comment by tavinus** [comment]
Hi,  
Had the same problem.  
In my case, I had a special php config with file size limit as 0 (write to disk). Weird that some folders would work and others not (shared ones failed). I had that to upload files bigger than 2GB in a 32-bit system, used to work. After I changed the limit to 2GB in the admin settings and saved, upload works again for shared folders.  

So, I would suggest checking your file size limit and also checking your PHP configuration relating to uploads.  

Related info:
 - https://docs.nextcloud.com/server/9/admin_manual/configuration_files/big_file_upload_configuration.html
 - https://help.nextcloud.com/t/maximum-upload-size/665
 - https://help.nextcloud.com/t/max-upload-size-and-file-permissions/6034  
  
Cheers!  
Gus

**Comment by jbyvosges** [comment]
The problem is solved for me : I cannot upload any file only when the quota is "illimited"

**Comment by reckas** [comment]
Had the same problem. In my case it was the upgrade to php7-fpm and the integration via  
<Proxy fcgi://127.0.0.1:9002>

I've switched to the unix socket variant of php7.0-fpm  
                AddHandler php7-fcgi .php
                Action php7-fcgi /php7-fcgi virtual
                Alias /php7-fcgi /usr/lib/cgi-bin/php7-fcgi-cloud
                FastCgiExternalServer /usr/lib/cgi-bin/php7-fcgi-cloud -idle-timeout 250 -socket /var/run/php/php7.0-fpm-cloud.sock -pass-header Authorization

and now everything works like a charm

**Comment by noryck** [comment]
Had the same problem. In my case it was the nginx conf for nextcloud.

**Comment by jbyvosges** [comment]
Hi,
Have you left the quotas "unlimited" ? You have to put a quota.

**Comment by dncnmckn** [comment]
Yeah, I have this too. Using apache.
