### ISSUE TITLE
Make Push-Notifications more useful

### ISSUE THREAD

**Issue by ragnarookie** [nextcloud/server#23118]
I need Push-Notifications in Nextcloud. Otherwise the whole thing is pretty useless for me.

But: Push-Notifications last only for about 1 or 2 seconds; no matter if on Chrome (85.0) or Firefox(81.0). Using Firefox's option to use Window's notification-center yields the same results. 

That is barely enough to notice them, certainly not enough to read them. I'm prettty positive that this is not the usual behavior as examples like https://www.bennish.net/web-notifications.html last way longer.

Can you give an option to change this behaviour?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
