### ISSUE TITLE
Apps: Side menu burger menu icon above content

### ISSUE THREAD

**Issue by weeman1337** [nextcloud/server#23126]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup a NC 20 RC2 environment
2. Go to the apps management

### Expected behaviour
Burger menu icon looks "correct" (see below).

### Actual behaviour
Burger menu icon overflows the list.  
It looks odd somehow:

![image](https://user-images.githubusercontent.com/6216686/94846637-c32efb00-0421-11eb-8076-268aa4154528.png)

There are other places where the side bar burger menu icon is above the list as well (e.g. calendar).  
The question is: How should it look like?

### Server configuration

**Nextcloud version:** 20 RC2

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh

**Where did you install Nextcloud from:** Git

### Client configuration
**Browser:** Firefox 81.0

**Operating system:** Ubuntu 20.04

**Comment by kurn77** [comment]
Same issue reproduced also with : 

**Operating system:** Debian 10.12-2
**Web server:** Apache 2.4
**Database:** PostgreSQL 10.12
**PHP version:** PHP 7.3.19
**Nextcloud version:** NextCloud v 20.0.1
**Client configuration:** Version 86.0.4240.111 (Build officiel) (64 bits)
**Operating system:** Windows 10 Version 10.0.19041 Numéro 19041

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/16934
