### ISSUE TITLE
Create previews of document for thumbnails

### ISSUE THREAD

**Issue by Niclas-sol** [nextcloud/server#23123]
It would be great to have a preview of a pdf and other files without opening it. Like the generated previews on Mac.
I don't know if it is right repo, maybe it can be integrated to the preview generator?

**Comment by acsfer** [comment]
This is already possible, it is a configuration issue
See https://www.allerstorfer.at/nextcloud-install-preview-generator/

If further help is needed, check https://help.nextcloud.com
Thanks 👍
