### ISSUE TITLE
https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/357#issuecomment-702632678

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#23133]
There is a OnlyOffice Issue -->

https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/357#issuecomment-702632678

LinneyS from OnlyOffice says -->

Please note that Community Document Server was developed by Nextcloud Team, if you have any issues with it, please contact them in the appropriate GitHub repository.

If you are using our official method of integration (Nextcloud + dedicated Document Server instance as per our installation guide), we will be glad to answer your questions. Please see more info on our forum.

Question is 👍 

which is the appropriate GitHub repository to report OnlyOffice Issues ? 
(when "https://github.com/ONLYOFFICE/onlyoffice-nextcloud" is not, according to the message of LenneyS ?)

**Comment by kesselb** [comment]
> which is the appropriate GitHub repository to report OnlyOffice Issues ?

Look at https://github.com/ONLYOFFICE/onlyoffice-nextcloud as the user interface. 
The user interface connects to a backend server for the document processing. 

Available backend servers:
- https://github.com/ONLYOFFICE/DocumentServer (official server from onlyoffice)
- https://github.com/nextcloud/documentserver_community (server developed by nextcloud)
