### ISSUE TITLE
Debugging App Framework

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#23131]
For "File sharing" and "Maps" the following message appears in the event log:

![obraz](https://user-images.githubusercontent.com/47037905/94902442-74707800-0498-11eb-8a90-0c5da68b8b4b.png)

### Server configuration

**Operating system:**
Linux 4.4.235-1.el7.elrepo.x86_64 x86_64

**PHP version:**
7.3.16

**Nextcloud version:** (see Nextcloud admin page)
20.0.0 RC2

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing your report in favour of https://github.com/nextcloud/server/issues/23046. The repository for maps is https://github.com/nextcloud/maps. 

Increase the log level to 1 or higher to hide debug messages. It's expected for level debug to log deprecated calls.
