### ISSUE TITLE
l10n: No text string in Transifex

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#23140]
The following text strings to be translated are missing from Transifex:

- geocoding with Nominatim
- elevation data from OpenTopoData

![obraz](https://user-images.githubusercontent.com/47037905/93711914-47e06600-fb52-11ea-8c71-2ffc97b7f321.png)

https://github.com/nextcloud/server/blob/2b7c2a04103d749fe5fcd10628cdd61b4fd1240e/apps/dashboard/src/App.vue#L78

App:
Nextcloud 20.0.0 RC2
Dashboard 7.0.0

**Comment by kesselb** [comment]
cc @juliushaertl @eneiluj

**Comment by eneiluj** [comment]
@juliushaertl @ChristophWurst Could it be because multiple `t()` calls are on the same line?

**Comment by juliushaertl** [comment]
Yeah the regex does greedy matching by default so it will match until the last `'` of a line:

https://github.com/nextcloud/docker-ci/blob/master/translations/translationtool/src/translationtool.php#L330-L341

**Comment by eneiluj** [comment]
@ChristophWurst @juliushaertl Thanks, then I'll split this into multiple lines :grin:.

**Comment by rakekniven** [comment]
That has been fixed IIRC, or?

**Comment by Valdnet** [comment]
String text has appeared in Transefix.
