### ISSUE TITLE
Upgrade internal S3 library

### ISSUE THREAD

**Issue by flypenguin** [nextcloud/server#2315]
#60 is closed now, *but* the internal S3 lib is too old to support all AWS regions because of v2 vs. v4 authentication mechanisms.

So please upgrade the internal S3 connection lib to enable all regions (e.g. Frankfurt).

(ref: https://github.com/nextcloud/server/pull/768#issuecomment-261536804)

**Comment by MariusBluem** [comment]
Is this something still possible with Nextcloud 11? @rullzer @icewind1991

**Comment by LukasReschke** [comment]
Doubt it. 12 at earliest. (aka early next year)

**Comment by rullzer** [comment]
I wouldn't risk doing that for 11. But makes sense to do it early in the 12 cycle.

**Comment by MariusBluem** [comment]
Because this is blockig S3 for AWS in Frankfurt I think this is important 😁😅

**Comment by MariusBluem** [comment]
Is v2 (the current implemenetation) still supported and "secure" if we are talking about authentification ;)

**Comment by 8BitAce** [comment]
Has the AWS PHP SDK changed that significantly over this time period? Or is this something that someone with only basic understanding of nexcloud app structuring can pick up?

**Comment by icewind1991** [comment]
Updated the sdk in https://github.com/nextcloud/server/pull/4410

Please spend some time testing the various s3 integrations (not with production data ofc)

**Comment by MorrisJobke** [comment]
Out of scope for 12 -> move to 13

**Comment by flypenguin** [comment]
MEH. Was hoping I could move my files into S3 now.
Any timeline for 13?

**Comment by MorrisJobke** [comment]
> Any timeline for 13?

~5-6 months after 12 I would say roughly.

**Comment by icewind1991** [comment]
https://github.com/nextcloud/server/pull/4410 should be ready for review.

Any help testing the changes would be greatly appreciated (and helps make sure they actually get merged 😄 )

**Comment by flypenguin** [comment]
one remark, even if maybe this is already present: it would be nice, at least in some future, that you could use AWS server side encryption for S3 objects as well. is that being done / considered or should I create another ticket?

ref: http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

**Comment by MorrisJobke** [comment]
Fixed with #4410
