### ISSUE TITLE
Undefined index: permissions for scan FTP external storage, Nextcloud 19

### ISSUE THREAD

**Issue by douggutaby** [nextcloud/server#23153]
Hi,

I use FTP as external storage maybe since Nextcloud 15. Few days ago I updated to Nextcloud 19 from 18 and since then I cannot scan ftp files. Permission seems good, I can ftp with apache user and no SELinux errors in logs. If I try to scan a subdirectory (e.g.: /User/files/Name/SubDir) not the root directory (e.g.: /User/files/Name) it works.
Strange is the parameter in method call is empty: handleChildren('', true, 3, 122343, true, 0)
If I try the same on an other directory (not ftp but local dir) I got this: handleChildren('.Trash-1000', true, 3, 97282, true, 0)
Which is ok, only root can read this directory.

As a WA I tried to remove the FTP external storage and reattach it. It seems good, like it scaned all of the files, but if I run sudo -u apache php /var/www/html/nextcloud/occ files:scan --path=/User/files/Name
I got the same error.

Can you help me what happened with my FTP?

### Steps to reproduce
1. Set FTP external storage on Nextcloud 18
2. Update to Nextcloud 19
3. Scan files

### Expected behaviour
Nextcloud should scan all of the files on FTP.

### Actual behaviour
sudo -u apache php /var/www/html/nextcloud/occ files:scan --path=/User/files/Name
Starting scan for user 1 out of 1 (User)
Exception during scan: Undefined index: permissions
#0 /var/www/html/nextcloud/lib/private/Files/Storage/Wrapper/PermissionsMask.php(160): OCA\Files\Command\Scan->exceptionErrorHandler(8, 'Undefined index...', '/var/www/html/n...', 160, Array)
#1 [internal function]: OC\Files\Storage\Wrapper\PermissionsMask->getDirectoryContent('')
#2 /var/www/html/nextcloud/lib/private/Files/Cache/Scanner.php(408): iterator_to_array(Object(Generator))
#3 /var/www/html/nextcloud/lib/private/Files/Cache/Scanner.php(388): OC\Files\Cache\Scanner->handleChildren('', true, 3, 122343, true, 0)
#4 /var/www/html/nextcloud/lib/private/Files/Cache/Scanner.php(340): OC\Files\Cache\Scanner->scanChildren('', true, 3, 122343, true)
#5 /var/www/html/nextcloud/lib/private/Files/Utils/Scanner.php(260): OC\Files\Cache\Scanner->scan('', true, 3)

### Server configuration

**Operating system:**
CentOS 7.8.2003

**Web server:**
Apache 2.4.6

**Database:**
MariaDB 5.5.65

**PHP version:**
7.3.23

**Nextcloud version:** (see Nextcloud admin page)
19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**
From 18, maybe 18.0.4

**Where did you install Nextcloud from:**
Web updater

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - audioplayer: 2.11.2
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_markdown: 2.3.1
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - encryption
  - user_ldap

**Nextcloud configuration:**
{
    "system": {
        "debug": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.4.100",
            "htpc.dyndns.hu",
            "htpc"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "http:\/\/htpc\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Movie",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\SVG",
            "OC\\Preview\\OpenDocument"
        ],
        "maintenance": false,
        "updater.release.channel": "stable",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "loglevel": 2,
        "theme": "",
        "mysql.utf8mb4": true,
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes, ftp

**Are you using encryption:** yes/no
No for ftp

**Comment by etalks** [comment]
Bump, Same error after upgrading to 19. I lost some of the folders from the cloud too. No data is not lost physical folders are there but Cloud does list them or sync then anymore.

**Comment by etalks** [comment]
ok found the solution.
I ran the following
sudo -u www-data php /var/www/nextcloud/occ files:scan -vvv <my user>

this will show you what the command is doing step by step.
in my case there was a corrupt  user file that got somehow got stored in the cloud half cooked
can I took out the file is showed just before the error.
ran again and all is good now.

**Comment by douggutaby** [comment]
I only got one new line with -vvv:
	Folder	/User/files/Name/
I still don't understand what is the problem. My WA is to scan subdirectories:
for subdir in /home/user/dir
do
  scan subdir
done

**Comment by etalks** [comment]
I found that in the directory where its breaking, there are special characters in the file names.

I am not sure why but there are 2 ways to fix it..
1 is to rename the troubling file.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
