### ISSUE TITLE
PDF Viewer not working

### ISSUE THREAD

**Issue by edouda** [nextcloud/server#23157]
After updating from Nextcloud 19 to Nextcloud 20, the PDF Viewer App doesn't work properly : 
it opens a window with the alert : CURLE_URL_MALFORMAT (3) The URL was not properly formatted. pdf viewer nextcloud
url)

**Comment by edouda** [comment]
I fixed it in my case by enabling pdf reading for Onlyoffice and disabling it again, but for people who don't manage to find the solution for it, their should be a patch.

**Comment by skjnldsv** [comment]
cc @juliushaertl might be related.
there seems to be a conflict between cool/oo and our viewer

**Comment by juliushaertl** [comment]
Hard to tell without a full issue template. I would guess the curl url malformed error comes from onlyoffice there. 

> I fixed it in my case by enabling pdf reading for Onlyoffice and disabling it again, but for people who don't manage to find the solution for it, their should be a patch.

Seems like a but for the ONLYOFFICE integration to me then https://github.com/ONLYOFFICE/onlyoffice-nextcloud/
