### ISSUE TITLE
Hash ip and metadata of bruteforce attempts

### ISSUE THREAD

**Issue by J0WI** [nextcloud/server#23162]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

**Is your feature request related to a problem? Please describe.**
`oc_bruteforce_attempts` table leaks a lot of personal data like IP addresses combined with usernames and timestamps.

**Describe the solution you'd like**
Hash the IP and username with a oneway function before inserting it. This still allows Nextcloud to detect and block bruteforce attempts, while not storing any additional information.

**Describe alternatives you've considered**

- #22993
- https://github.com/nextcloud/suspicious_login/issues/72

**Comment by rullzer** [comment]
Nope. The plan is still to use subnets as fallback at some point. Which we can't do if they are hashed.
Also it is only hiding the symptones. MD5-ing the ipv4 for example. You can still reverse it because your initial space is so small.

**Comment by rullzer** [comment]
But we should indeed cleanup old entries and only keep for how long we need them. Let me have a look at that

**Comment by rullzer** [comment]
See https://github.com/nextcloud/server/pull/23287

**Comment by J0WI** [comment]
> The plan is still to use subnets as fallback at some point.

We can also compare hashes of subnets.

> You can still reverse it because your initial space is so small.
Sure, but it raises the costs to do so. At least if not just plain MD5 is used.
It's easy to exclude IP addresses from logs but here the smallest possible needs to be stored to provide the functionality. The full address gives you more information than required.

**Comment by J0WI** [comment]
Closing due #23287
