### ISSUE TITLE
Documentation - Manual upgrade

### ISSUE THREAD

**Issue by BloodyIron** [nextcloud/server#23165]
Hey Folks, I'm manually upgrading from NC19 to NC20, and I noticed a discrepancy in the documentation: https://docs.nextcloud.com/server/20/admin_manual/maintenance/manual_upgrade.html

If you notice at step 13 you are told to execute occ commands. However, up until this point the occ file has not been given the execution flag, so you cannot do that. Really should add this part to the documentation. ;)

**Comment by kesselb** [comment]
https://github.com/nextcloud/documentation/ is the repository for the documentation.


You tested `php occ upgrade` without the executable flag? Afaik only the php binary needs +x for the above command.
