### ISSUE TITLE
Enhance Redis cache funcionality to allow us to specify multiple redis servers

### ISSUE THREAD

**Issue by DRN88** [nextcloud/server#2317]
### Feature request, enhancement 
Please enhance Redis cache feature in config.php so Nextcloud could talk to a new elected Redis Master by Redis Sentinel upon failover.

### Expected behaviour
* Automatically connect to new Redis master.  
* List multiple Redis servers and Nextcloud should select the new master.

### Actual behaviour
Currently we can only specify one IP or Hostname in config.php.
After a failover event a new redis master will be elected, which has a different IP/Domain name, so Nextcloud will be unavailable until we point config.php to the new master.  
A similar feature exists for Memcached, where we can list an array of arrays with multiple memcached servers.

### Server configuration
**Operating system**: CentOS 7 x86_64

**Web server:** Nginx 1.10.2 LibresSSL static linked

**Database:** PerconaDB 5.7 Cluster 3 nodes

**PHP version:** php70u from IUS repo

**Nextcloud version:** Latest 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** packaged tar.bz2 installer from main website

**Comment by MorrisJobke** [comment]
cc @LukasReschke @rullzer 

https://github.com/phpredis/phpredis

https://github.com/phpredis/phpredis/blob/feature/redis_cluster/cluster.markdown#readme

**Comment by rullzer** [comment]
Request makes sense. Especially for larger instances.

Do we have any speed numbers for phpredis?

**Comment by DRN88** [comment]
Thanks for picking this up.

If somebody found this ticket and trying to figure out a workaround here is one which I use currently:
Loadbalancing with HAProxy: http://blog.haproxy.com/2014/01/02/haproxy-advanced-redis-health-check/

Since I have a load balancer in front of my database I added a redis frontend and backend.

Config with AUTH:
```
frontend f_redis
    bind *:6379
    mode tcp
    option tcplog
    timeout client 1h
    default_backend b_redis_master

backend b_redis_master
    option tcp-check
    tcp-check connect
    tcp-check send AUTH\ mysuperstrongpassword\r\n
    tcp-check expect string +OK
    tcp-check send PING\r\n
    tcp-check expect string +PONG
    tcp-check send info\ replication\r\n
    tcp-check expect string role:master
    tcp-check send QUIT\r\n
    tcp-check expect string +OK
    server lxncredislon01 192.168.101.214:6379 check inter 1s
    server lxncredislon02 192.168.101.215:6379 check inter 1s
    server lxncredislon03 192.168.101.216:6379 check inter 1s
```

**Comment by MorrisJobke** [comment]
PR is in #4061
