### ISSUE TITLE
Strange folder icon on share web view

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#23176]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share a folder
2. Open that shared folder in your web browser

### Expected behaviour
Same folder icons as in the nextcloud

### Actual behaviour
Strange grey folder icons
See:
![grafik](https://user-images.githubusercontent.com/42836313/95028440-8fadd400-06a0-11eb-95e5-5690f77dedfd.png) vs. ![grafik](https://user-images.githubusercontent.com/42836313/95028457-a522fe00-06a0-11eb-9969-ae4b00eda1a3.png)
(left is nextcloud, right is share)
Can be reproduced for Firefox and Chrome

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache 2

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 19.0.0

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:** No errors

**Are you using external storage, if yes which one:** none, but data folder is on a nfs share (system level)

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP (UCS)

### Client configuration
**Browser:** Firefox 81.0.1 and current Chrome

**Operating system:** Win 10 x64 de

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2
cc @nextcloud/sharing does this need to be fixed in the server repository or in the groupfolders app?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
