### ISSUE TITLE
Instance Profile is not being used for S3 with External Storage Plugin

### ISSUE THREAD

**Issue by bkk87** [nextcloud/server#23178]
I want to connect my S3 Bucket using the External Storage Plugin.

There was a recent PR in NC 20 that it should no longer be necessary to have to provide the Access Key and the Secret.
Instead, the Instance Profile should be used which is more secure: <https://github.com/nextcloud/server/issues/19790>

However, using the GUI, I still have to fill out the Access Key and Secret. 
![Bildschirmfoto 2020-10-05 um 08 02 06](https://user-images.githubusercontent.com/70271327/95048731-a5df8280-06e8-11eb-81c7-bfa8b1a79a68.png)

### Steps to reproduce
1. Go to the settings of the External Storage Plugin and try to configure a S3 Bucket.
2. You will see that you have to fill out the Access Key and Secret.

### Expected behaviour
Configuring Access Key and Secret should be optional.
Setting up the Bucket should succeed without providing Access Key and Secret. Internally, NC should instead try to use the Instead Profile if no Access Key and Secret is provided.

### Actual behaviour
Bucket configuration does not succeed without providing Access Key and Secret.

### Server configuration

Using Nextcloud Snap (development branch for NC 20)
**Operating system:** Ubuntu LTS 20.04

**Comment by Amexy** [comment]
Any update on this? I'm also using the latest Docker image and I can't find a way to bypass entering the keys.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by bkk87** [comment]
I no longer run NC on AWS. 

Do you, @Amexy?

**Comment by santosh-goundar** [comment]
am having same requirement, tried creating instance profile, still accessing for access keys while adding S3 bucket, how to avoid mentioning access key, running 20.0.8 on prod, also tried by updating NC to  22.2.3 on stage, still same issue, please suggest
