### ISSUE TITLE
[LDAP] Support for `sidhistory` for automagic migration

### ISSUE THREAD

**Issue by Commifreak** [nextcloud/server#23180]
**Is your feature request related to a problem? Please describe.**
Currently, migrating from one LDAP to another, Nextcloud treat the "same" users as new accounts - the sid is different. But the sidhistory is avilable.

**Describe the solution you'd like**
It would be great if NC would check the sidhistory field to detect a user with a known UID in its sidhistory entry - if this is possible.
If detected, correct the mapping so the user wont loose any files/shares

**Additional context**
https://ldapwiki.com/wiki/SIDHistory
https://docs.microsoft.com/en-us/windows/win32/adschema/a-sidhistory

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
