### ISSUE TITLE
autoconfig.php fails if database already exists

### ISSUE THREAD

**Issue by mgerhardy** [nextcloud/server#23181]
I'm using nextcloud in a kubernetes environment with an init container to set everything up. The first setup works perfectly. But removing the config volume and only trying to keep data and database intact leads to problems during autoconfig. The error reported is "database already exists". This is intended in my situation. The kubernetes pod is automatically recreated with the same settings as before. I just don't wanna lose the database state and the data directory. Everything else should just be auto-provisioned.

It would be nice if we could get an autoconfig.php option that allows us to re-use the already existing database. And just continue to setup the config.php.

**Comment by ealvarez968** [comment]
Hi @mgerhardy,

That happened to me a couple of times when I was migrating nextclound to another server, I think that the pod with the nextcloud install it's doing a reinstallation process, that's why it says "Database already exists". 

Try saving the config.php nextcloud file   under the config before removing the volume, then you can replace it back.

Please tell me if this works, if not I would like to help you solve it. 👍

**Comment by mgerhardy** [comment]
The point is that I'm trying to build a kubernetes installation that works in situations where no database exists - so the initial installation of a new nextcloud instance. But also the redeployment of nextcloud in environments where on the user data directories and the database survived.

For me this currently means, that I can't use the autoconfig feature (as it is mounted as a volume that is more or less hardcoded independently of the nextcloud state in the k8s-deployment yamls) but have to mount the config.php as volume (but then the initial setup with an empty database wouldn't work, too). This means that whenever I lose the state of the cluster and have to restore the database from backups, I basically can't just reinstall nextcloud - due to this error check. That's why I would like to have that option.

**Comment by kesselb** [comment]
> database already exists

Are you sure this error is from Nextcloud? I don't see why your scenario should not work. 

For example MySQL: 

1. Create a user for Nextcloud: This step should be skipped for your scenario as a database user is already configured in `autoconfig.php`.

2. Create a database for Nextcloud: `CREATE DATABASE IF NOT EXISTS `$name` CHARACTER SET $characterSet COLLATE ${characterSet}_bin;` is the query used. If the database already exists the query does nothing. If this step fails the error should be: Database creation failed

3. Grant permissions to database: If this step fails the error should be: Could not automatically grant privileges, this can be ignored if database user already had privileges.

**Comment by mgerhardy** [comment]
And what if the database tables already exist? Maybe it's just the error message that is misleading. But the error comes from nextcloud as far as I can tell.
