### ISSUE TITLE
Be able to sync your google/microsoft calendar with your nextcloud calendar 

### ISSUE THREAD

**Issue by nsturtz** [nextcloud/server#23200]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Not related to a problem

**Describe the solution you'd like**
It would be nice if you could sync your google or Microsoft calendar with your nextcloud calendar without having to download and reupload it every time

**Additional context**
You could also add Gmail notifications to the dashboard app via a plugin

**Comment by strugee** [comment]
Can't you already do this with the "Add new calendar from link" functionality in the calendar app?

**Comment by nsturtz** [comment]
@strugee I was unaware of that, I am testing it.

**Comment by nsturtz** [comment]
It works, sorry for wasting you time
