### ISSUE TITLE
No Release Notes or Changelog für v20.0.0

### ISSUE THREAD

**Issue by Delphinator** [nextcloud/server#23219]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to the [server download page](https://nextcloud.com/install/#instructions-server). "Latest stable version" is 20.0.0.
2. Follow the link to the [changelog](https://nextcloud.com/changelog/). Latest version with a changelog entry is 19.0.3.
3. [Latest release](https://github.com/nextcloud/server/releases/latest) here on GitHub is 20.0.0 (with no description).

### Expected behaviour
There should be a changelog published somewhere including the current stable version. Especially as a new major version could include breaking changes admins might want to know about before upgrading.

### Actual behaviour
I was unable to find a changelog for 19.0.3 to 20.0.0

**Comment by jospoortvliet** [comment]
not true, I usually do it together with the release itself. But not always - and in this case, I totally forgot ;-)

Will do it tomorrow.

**Comment by acsfer** [comment]
Fixed by https://nextcloud.com/changelog/#latest20

**Comment by pm-pm** [comment]
I don´t want to open a new issue, but the same with 19.0.4. No Changelog anywhere. :-(

Here is the "official" information from inside the official download archive. (senseless)


> Changelog
> =========
> The change log is at [https://nextcloud.com/changelog/](https://nextcloud.com/changelog/).

**Comment by jospoortvliet** [comment]
> I don´t want to open a new issue, but the same with 19.0.4. No Changelog anywhere. :-(
> 
> Here is the "official" information from inside the official download archive. (senseless)
> 
> > # Changelog
> > The change log is at https://nextcloud.com/changelog/.

for 19.0.4 we're basically delaying announcing it because our download server is still overloaded :cry:
I'll put the changelog there, but the rest comes Monday or later (as I'm now on holiday for a week)
