### ISSUE TITLE
Feature-Policy has been renamed to Permissions Policy

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/server#23228]
NC sets
`Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'`

Because `Feature-Policy` has been renamed to `Permissions-Policy` I suggest to use that also in NC

`Permissions-Policy: autoplay=(self); camera=(none); fullscreen=(self); geolocation=(none); microphone=(none); payment=(none)`

If someone points out where to change that in the code, I can bring in a PR.

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/22792
