### ISSUE TITLE
Broken symlinks cause "nextcloud.occ files:scan" to malfunction, and oc_filecache corruption

### ISSUE THREAD

**Issue by Pajkastare** [nextcloud/server#23238]
### Substitute "nextcloud.occ" with "occ": Originally a Snap-NC bug report, redirected here instead

I use the Snap version of Nextcloud, and originally filed it under https://github.com/nextcloud/nextcloud-snap/issues/. However, it was closed with the reason it is an upstream bug. So I created this issue here instead, but note that the paths I state below are valid for the Snap version, and may need to be adjusted for a non-snap setup.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Before reproducing:
1. "cd /var/snap/nextcloud/current/mysql"
2. "ls -al nextcloud/oc_filecache*"
3. Note the filesizes

1. Go to the directory that is the root of the Nextcloud files area, the one defined by "datadirectory" in /var/snap/nextcloud/current/nextcloud/config/config.php
2. "cd username/files"
3. "ln -s /invalid/directory/that/does/not/exist"   # I.e., create a broken symlink, which causes the problems
4. "nextcloud.occ files:scan username -v"
5. Watch the invalid paths scroll by (or omit the "-v" to speed this process up a bit)
6. "cd /var/snap/nextcloud/current/mysql"
7. "ls -al nextcloud/oc_filecache*"
8. Observe the larger filesizes compared to before before

### Expected behaviour
The "nextcloud.occ files:scan [username | --all] -v" should ignore broken/invalid symlinks, and not create invalid paths in the database.
Also, an automatic and periodic database optimization step to reduce filesizes would be nice, but not really relevant for this bug report.

### Actual behaviour
If a broken symlink (a symlink that leads to an invalid/nonexistent location) is placed in the files directory under a user, and "nextcloud.occ files:scan [username | --all] -v" is executed, invalid entries such as "/username/files////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////Readme.md" are listed. And added to the oc_filecache table, as the "path". There seems to be one additional entry one "/" longer until the [currently] 4000 bytes limit to the "path" field in the database is reached, after which error messages will be displayed stating that the path is too long.

This will cause the oc_filecache files to get very large. I observed oc_filecache file sizes of > 900 MB, for about 5000 files, which is not reasonable in any way.

### Server configuration

**Operating system:** Ubuntu 20.04 64-bit (on a Raspberry Pi 4, 4 GB RAM)

**Web server:** Snap: Apache

**Database:** Snap: MySQL

**PHP version:** Not really sure, whatever was current in the snap at that time.

**Nextcloud version:** From snap: 
Name       Version      Rev    Tracking       Publisher   Notes
nextcloud  19.0.1snap2  22408  latest/stable  nextcloud✓  -

**Updated from an older Nextcloud/ownCloud or fresh install:** Original snap install, auto-updated regularly

**Where did you install Nextcloud from:** Snap

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Probably not relevant, I think...
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
Snap defaults, except I use /mnt/ for the "datadirectory"
```
</details>

**Are you using external storage, if yes which one:** Changed storage path "datadirectory" to /mnt/, and made the Snap-connection to "Removable Media", otherwise no change

**Are you using encryption:** Not for Nextcloud, except HTTPS access only

**Are you using an external user-backend, if yes which one:** No

### Client configuration
Irrelevant, problem caused by command line at server

### Logs
The above description should be enough, I fixed the problem and moved on...

#### Web server error log
The above description should be enough, I fixed the problem and moved on...

#### Nextcloud log (data/nextcloud.log)
The above description should be enough, I fixed the problem and moved on...

#### Browser log
The above description should be enough, I fixed the problem and moved on...

### EXTRA: A workaround for other persons who might get this problem:
0. Backup everything
1. Remove all invalid symlinks under the Nextcloud data directory
2. snap start nextcloud
3. cd /var/snap/nextcloud/current/mysql
4. nextcloud.mysql-client nextcloud
5. show table status like "oc_filecache";
6. SELECT * FROM oc_filecache WHERE path LIKE '%//%'; # Sanity-check that this catches invalid entries
6. DELETE FROM oc_filecache WHERE path LIKE '%//%';
7. OPTIMIZE TABLE oc_filecache;
8. Ctrl-D (to exit mysql-client)
9. snap stop nextcloud; snap start nextcloud; sleep 5; nextcloud.mysql-client nextcloud # This might be unnecessary
10. SELECT * FROM oc_filecache WHERE path LIKE '%//%'; # Should be an empty set
11. show table status like "oc_filecache"; # Should only contain valid stuff
12. Ctrl-D (to exit mysql-client)
13. nextcloud.occ files:scan --all -v
14. Done.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
