### ISSUE TITLE
Can't choose groups in settings

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/server#23232]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to settings - basic settings (or some other settings pages)
2. See that you can't choose groups for the announcements

### Expected behaviour
Field for choosing apps should be visible

### Actual behaviour
No field displayed, error in JS console (see below)

### Server configuration

**Database:** Postgres 12

**Nextcloud version:** 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from 19.0.3

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 78.2.0 / Chromium 85.0.4183.121

**Operating system:** Windows 10 / openSUSE Tumbleweed

#### Browser log
<details>
<summary>Browser log</summary>

```
Chromium/Chrome:
admin.js?v=effac2b9-22:26 Uncaught TypeError: Cannot read property 'setupGroupsSelect' of undefined
    at HTMLDocument.<anonymous> (admin.js?v=effac2b9-22:26)
    at l (jquery.js:3187)
    at Object.add [as done] (jquery.js:3246)
    at e.fn.init.m.fn.ready (jquery.js:3496)
    at admin.js?v=effac2b9-22:23

Firefox:
Uncaught TypeError: OC.Settings is undefined
    <anonymous> admin.js:26
    jQuery 3
        l
        add
        ready
    <anonymous> admin.js:23
```
</details>

**Comment by xNako** [comment]
Same for users & groups in the label "Available For" when setting up external storage.
![c3758e7369cd2ea037cad12a9be28930369a569a](https://user-images.githubusercontent.com/23058703/95232031-42e30e00-0804-11eb-92ef-ca224b3d872a.png)

**Comment by nsturtz** [comment]
I can 
![image](https://user-images.githubusercontent.com/67589701/95247813-f7b50500-07db-11eb-8fdb-016e75fbe68f.png)

**Comment by Chartman123** [comment]
@nsturtz even with the browser cache disabled?

**Comment by nsturtz** [comment]
Yes, I just clear the cache on my browser

**Comment by Chartman123** [comment]
Might this be the result of some race condition? I just tried reloading the settings page a few times and the groups were editable around 50% of the times...

**Comment by nsturtz** [comment]
@Chartman123 They are editable for me 100% of the time

**Comment by qtw1998** [comment]
I met the same issues when I tried to add groups admin for external storage!!  Does anybody solve this problem?
![image](https://user-images.githubusercontent.com/34357479/95611802-eb0f0600-0a94-11eb-9b5b-b0bd17f7b937.png)

**Comment by muchahagrande** [comment]
I have the same problem. And I can't share anything anymore.
The previous shares still exists, but I can't create new ones.

Log is full of repeated messages like these:
{"reqId":"X4DvNKofQQMv4KcFVEfdbQAAADU","level":3,"time":"2020-10-09T20:16:04-03:00","remoteAddr":"192.168.2.10","user":"fjm","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/fjm/","message":{"Exception":"Error","Message":"array_diff(): Expected parameter 2 to be an array, object given at /var/www/nextcloud/lib/private/Share20/Manager.php#1850","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1850,"function":"array_diff"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"sharingDisabledForUser","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":125,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":106,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":254,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":156,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":192,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":144,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.2stable-Win64 (build 20200924) (Nextcloud)","version":"20.0.0.9"}
{"reqId":"X4DvOrCHzCVwgjUtBm-QUwAAAEc","level":3,"time":"2020-10-09T20:16:10-03:00","remoteAddr":"192.168.2.10","user":"fjm","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/fjm/","message":{"Exception":"Error","Message":"array_diff(): Expected parameter 2 to be an array, object given at /var/www/nextcloud/lib/private/Share20/Manager.php#1850","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1850,"function":"array_diff"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"sharingDisabledForUser","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":125,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":106,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":254,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":156,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":192,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":144,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.2stable-Win64 (build 20200924) (Nextcloud)","version":"20.0.0.9"}
{"reqId":"X4DvOs5nNWWkEWoJMvwZrQAAABg","level":3,"time":"2020-10-09T20:16:11-03:00","remoteAddr":"192.168.2.10","user":"fjm","app":"PHP","method":"GET","url":"/ocs/v2.php/core/navigation/apps?absolute=true&format=json","message":{"Exception":"Error","Message":"array_diff(): Expected parameter 2 to be an array, object given at /var/www/nextcloud/lib/private/Share20/Manager.php#1850","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1850,"function":"array_diff"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"sharingDisabledForUser","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/Mount/Manager.php","line":92,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1375,"function":"find","class":"OC\\Files\\Mount\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/Root.php","line":201,"function":"getFileInfo","class":"OC\\Files\\View","type":"->"},{"function":"get","class":"OC\\Files\\Node\\Root","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":66,"function":"call_user_func_array"},{"file":"/var/www/nextcloud/lib/private/Files/Node/LazyFolder.php","line":143,"function":"__call","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/AppData/AppData.php","line":142,"function":"get","class":"OC\\Files\\Node\\LazyFolder","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ImageManager.php","line":106,"function":"getFolder","class":"OC\\Files\\AppData\\AppData","type":"->"},{"file":"/var/www/nextcloud/apps/theming/lib/ThemingDefaults.php","line":337,"function":"getImage","class":"OCA\\Theming\\ImageManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/URLGenerator.php","line":193,"function":"replaceImagePath","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/var/www/nextcloud/lib/private/NavigationManager.php","line":286,"function":"imagePath","class":"OC\\URLGenerator","type":"->"},{"file":"/var/www/nextcloud/lib/private/NavigationManager.php","line":108,"function":"init","class":"OC\\NavigationManager","type":"->"},{"file":"/var/www/nextcloud/core/Controller/NavigationController.php","line":56,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"getAppsNavigation","class":"OC\\Core\\Controller\\NavigationController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.2stable-Win64 (build 20200924) (Nextcloud)","version":"20.0.0.9"}
{"reqId":"X4DvRTcmwu3OZIWo6koiwAAAACM","level":3,"time":"2020-10-09T20:16:21-03:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"PUT","url":"/apps/user_status/heartbeat","message":{"Exception":"Error","Message":"array_diff(): Expected parameter 2 to be an array, object given at /var/www/nextcloud/lib/private/Share20/Manager.php#1850","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1850,"function":"array_diff"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"sharingDisabledForUser","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9"}
{"reqId":"X4DvUrUaKspyEEu0xUroYAAAAA4","level":3,"time":"2020-10-09T20:16:34-03:00","remoteAddr":"192.168.2.10","user":"fjm","app":"PHP","method":"PROPFIND","url":"/remote.php/dav/files/fjm/","message":{"Exception":"Error","Message":"array_diff(): Expected parameter 2 to be an array, object given at /var/www/nextcloud/lib/private/Share20/Manager.php#1850","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1850,"function":"array_diff"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"sharingDisabledForUser","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":125,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Backend/AbstractBasic.php","line":106,"function":"validateUserPass","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":254,"function":"check","class":"Sabre\\DAV\\Auth\\Backend\\AbstractBasic","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Auth.php","line":156,"function":"auth","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":192,"function":"check","class":"OCA\\DAV\\Connector\\Sabre\\Auth","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Auth/Plugin.php","line":144,"function":"check","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"beforeMethod","class":"Sabre\\DAV\\Auth\\Plugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":458,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":325,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.2stable-Win64 (build 20200924) (Nextcloud)","version":"20.0.0.9"}
{"reqId":"X4DvUkIZ@Y7Xsl@Xyq5SLAAAAEo","level":3,"time":"2020-10-09T20:16:35-03:00","remoteAddr":"192.168.2.10","user":"admin","app":"PHP","method":"GET","url":"/apps/files_external/applicable?pattern=&limit=30&offset=0&_=1602285034855","message":{"Exception":"Error","Message":"array_diff(): Expected parameter 2 to be an array, object given at /var/www/nextcloud/lib/private/Share20/Manager.php#1850","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1850,"function":"array_diff"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/MountProvider.php","line":92,"function":"sharingDisabledForUser","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Config/MountProviderCollection.php","line":119,"function":"getMountsForUser","class":"OCA\\Files_Sharing\\MountProvider","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":452,"function":"addMountForUser","class":"OC\\Files\\Config\\MountProviderCollection","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Filesystem.php","line":377,"function":"initMountPoints","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":322,"function":"init","class":"OC\\Files\\Filesystem","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1008,"function":"setupFS","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0","version":"20.0.0.9"}

**Comment by ondrejmo** [comment]
> I met the same issues when I tried to add groups admin for external storage!! Does anybody solve this problem?
> ![image](https://user-images.githubusercontent.com/34357479/95611802-eb0f0600-0a94-11eb-9b5b-b0bd17f7b937.png)

I've the same problem, although changing to groups with `occ` command works as expected. (running `20.0.0-apache` docker image)

**Comment by muchahagrande** [comment]
> 
> 
> I have the same problem. And I can't share anything anymore.
> The previous shares still exists, but I can't create new ones.
> 

Sharing problem was solved. I've restricted sharing to "Amigos" group. So, I've turned off the restriction and sharing was enabled for everyone. Then I turned the restriction on again and changed the groups in the list. After that I set the config back to the original and now sharing is back to the allowed groups and restricted to "Amigos".

The groups selection problem at the external storage menu still exists.

**Comment by nsturtz** [comment]
@ondrejmo I have that issue to, I did not understand what you ment!

**Comment by mplawner** [comment]
@nsturtz I'm not too familiar with this, but I had the same issue. Here's what I did (be careful):
This listed my shares:
`docker exec -u www-data -it nextcloud-app /var/www/html/occ files_external:list`

This have me the command line parameters to make changes to a share:
`docker exec -u www-data -it nextcloud-app /var/www/html/occ files_external:applicable`

This allowed me to remove the default "All" users and add only "myusername" user to share ID 2 (got from list above):
`docker exec -u www-data -it nextcloud-app /var/www/html/occ files_external:applicable --remove-user All --add-user myusername 2`

Hope that gets you started!

**Comment by nsturtz** [comment]
I don't use docker for nextcloud

**Comment by mplawner** [comment]
Well, the `occ` command works similarly. I think you replace `docker exec -u www-data -it nextcloud-app` with `sudo -u www-data` 
Sorry, not completely sure, but that should be pretty easy to find.

**Comment by nsturtz** [comment]
ok I think so also

**Comment by nsturtz** [comment]
It worked, thank you!

**Comment by Chartman123** [comment]
At least in Nextcloud 21 I don't see this problem anymore. So I'd propose to close this issue...
