### ISSUE TITLE
Nextcloud add file from url with api for clients/android

### ISSUE THREAD

**Issue by markushub** [nextcloud/server#23247]
**Is your feature request related to a problem? Please describe.**
My aim is to directly transfer a single file from a third-party server to a (my) nextcloud server.

In my other issue from nextcloud/android they told me open the issue here.
See the corresponding issue for the background of the android problem with multiple data traffic volume
https://github.com/nextcloud/android/issues/6834#issuecomment-700624341

**Describe the solution you'd like**
Nextcloud server can download files (e.g. a new nextcloud releases or app updates)
Nextcloud apps like nextcloud cookbook can download/parse a recipe with download corresponding images. So I think there exist a good infrastructure for downloading inside nextcloud server.

Nextcloud server should provide an api for download new files from urls to the clients.
So the user can add a new file. Enter the url on android client to trigger the download on nextcloud server and store the file into nextcloud filesystem.

Desired solution
On nextcloud Android 
"add to nextcloud" -> from url

After copy the url into the nextcloud android app "add to nextcloud from url" it starts an asynchronous download from the third-party server and save this in the selected nextcloud server folder.
After download is finished the file can shared to other user with nextcloud ways.

**Describe alternatives you've considered**
Currently surfing with an android device and find a link (url) e.g. with a new version of an manual (pdf) or iso, zip file on a third-party server and i need a copy of this file on my server.
1. I have do download it with my browser to my smartphone
2. waiting till download is finished
3. share the download with nextcloud
4. waiting till upload is finished
 
It costs mobile data traffic volume twice (once for download and once for upload)
It's not often important to have a local copy on the android device. It's more important to have a copy on the own server and to share it.

**Additional context**
I host and use nextcloud over several years. I really like it.

Please provide a solution where the word "collaborate" is a solution and not only a slogan.

The desired api is an addition to this issue
https://help.nextcloud.com/t/upload-to-nextcloud-from-url/1237/26

Stay connected and bring your data home to nextcloud as simple as possible.
I hope you can help me here.

**Comment by rullzer** [comment]
This is more something suitabe for an app.
Nextcloud itself won't just go around downloading random stuff from the web.

See https://apps.nextcloud.com/apps/ocdownloader for example
