### ISSUE TITLE
Sharing autocomplete overflows for long names

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#2324]
* create a contact with long name and an email address
* try to autocomplete
* the autocomplete box overflows

<img width="434" alt="bildschirmfoto 2016-11-25 um 10 40 54" src="https://cloud.githubusercontent.com/assets/245432/20620821/f3a8d696-b2fb-11e6-826b-deca4bed8f29.png">

The whole box has a flexible with. If the names are short the width is perfect, but once the names are longer the box extends (`<ul>` element with these classes `ui-autocomplete ui-menu ui-widget ui-widget-content ui-corner-all`). Once I set this ul elements width to the correct value all the overflow handling works correctly.

@skjnldsv @jancborchardt  @nextcloud/designers  Any idea how/where to fix this?

**Comment by skjnldsv** [comment]
Since the autocomplete function is calculating the full width and therefore applying a width to the container, there's nothing we can do css-side :/

**Comment by skjnldsv** [comment]
Edit: see http://stackoverflow.com/a/11845718
