### ISSUE TITLE
Error when assembling chunks, status code 403 (webgui) + server replied 403 forbidden MOVE to https

### ISSUE THREAD

**Issue by ledufakademy** [nextcloud/server#23258]
But here is the problem that I’m facing right now, I can’t upload the file with size more than 10MB.
I have followed almost every articles (max upload size, max execution time, etc).
But I still don’t get the right answer yet to solve my problem.

The error message that I get:
On desktop client (Windows)

    ***/remote.php/dav/uploads/NAME/3764481260/.file

On web browser

    Error when assembling chunks, status code 403

**Comment by ledufakademy** [comment]
clearly issue here for Assembling chunk ...
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html

**Comment by ledufakademy** [comment]
Because i can watch file arriving on webserer :+1: 
`root@web2:/var/www/clients/client6/web53/web#  ls -alh  data/givenname.surname/uploads/web-file-upload-35c1aa13e7ba1826d43bac3a2ea7482e-1602075210235/
total 62M
drwxr-xr-x 2 web53 client6 4.0K Oct  7 14:53 .
drwxr-x--- 3 web53 client6 4.0K Oct  7 14:53 ..
-rw-r--r-- 1 web53 client6  10M Oct  7 14:53 0
-rw-r--r-- 1 web53 client6  10M Oct  7 14:53 10485760
-rw-r--r-- 1 web53 client6  10M Oct  7 14:53 20971520
-rw-r--r-- 1 web53 client6  10M Oct  7 14:53 31457280
-rw-r--r-- 1 web53 client6  10M Oct  7 14:53 41943040
-rw-r--r-- 1 web53 client6  10M Oct  7 14:53 52428800
-rw-r--r-- 1 web53 client6 1.7M Oct  7 14:53 62914560
`

**Comment by kesselb** [comment]
You tried https://help.nextcloud.com?

I remember some discussions about this problem especially if ispconfig is used as web hosting control panel.

**Comment by kesselb** [comment]
I found the related issues on GitHub: https://github.com/nextcloud/documentation/pull/1748/files / #8802

**Comment by ledufakademy** [comment]
in my nginx conf, i can't see what you're showing me ;-) 

> # Add headers to serve security related headers
# Before enabling Strict-Transport-Security headers please read into this
# topic first

add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;

#
# WARNING: Only add the preload option once you read about
# the consequences in https://hstspreload.org/. This option
# will add the domain to a hardcoded list that is shipped
# in all major browsers and getting removed from this list
# could take several months.
add_header Referrer-Policy "no-referrer" always;
add_header X-Content-Type-Options "nosniff" always;
add_header X-Download-Options "noopen" always;
add_header X-Frame-Options "SAMEORIGIN" always;
add_header X-Permitted-Cross-Domain-Policies "none" always;
add_header X-Robots-Tag "none" always;
add_header X-XSS-Protection "1; mode=block" always;

# Remove X-Powered-By, which is an information leak
fastcgi_hide_header X-Powered-By;

location = /robots.txt {
    allow all;
    log_not_found off;
    access_log off;
}

# The following 2 rules are only needed for the user_webfinger app.
# Uncomment it if you're planning to use this app.
rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json last;

# The following rule is only needed for the Social app.
# Uncomment it if you're planning to use this app.
rewrite ^/.well-known/webfinger /public.php?service=webfinger last;

location = /.well-known/carddav {
    return 301 $scheme://$host:$server_port/remote.php/dav;
}
location = /.well-known/caldav {
    return 301 $scheme://$host:$server_port/remote.php/dav;
}
location ~ /.well-known/acme-challenge {
    allow all;
}

# set max upload size
client_max_body_size 512M;
fastcgi_buffers 64 4K;

# Enable gzip but do not remove ETag headers
gzip on;
gzip_vary on;
gzip_comp_level 4;
gzip_min_length 256;
gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;

# Uncomment if your server is build with the ngx_pagespeed module
# This module is currently not supported.
#pagespeed off;

location / {
    rewrite ^ /index.php;
}

location ~ ^\/(?:build|tests|config|lib|3rdparty|templates|data)\/ {
    deny all;
}
location ~ ^\/(?:\.|autotest|occ|issue|indie|db_|console) {
    deny all;
}

location ~ ^\/(?:index|remote|public|cron|core\/ajax\/update|status|ocs\/v[12]|updater\/.+|oc[ms]-provider\/.+)\.php(?:$|\/) {
    fastcgi_split_path_info ^(.+?\.php)(\/.*|)$;
    set $path_info $fastcgi_path_info;
    try_files $fastcgi_script_name =404;
    include fastcgi_params;
    fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    fastcgi_param PATH_INFO $path_info;
    fastcgi_param HTTPS on;
    # Avoid sending the security headers twice
    fastcgi_param modHeadersAvailable true;
    # Enable pretty urls
    fastcgi_param front_controller_active true;
{FASTCGIPASS} 
    fastcgi_intercept_errors on;
    fastcgi_request_buffering off;
}

location ~ ^\/(?:updater|oc[ms]-provider)(?:$|\/) {
    try_files $uri/ =404;
    index index.php;
}

# Adding the cache control header for js, css and map files
# Make sure it is BELOW the PHP block
location ~ \.(?:css|js|woff2?|svg|gif|map)$ {
    try_files $uri /index.php$request_uri;
    add_header Cache-Control "public, max-age=15778463";
    # Add headers to serve security related headers (It is intended to
    # have those duplicated to the ones above)
    # Before enabling Strict-Transport-Security headers please read into
    # this topic first.
    #add_header Strict-Transport-Security "max-age=15768000; includeSubDomains; preload;" always;
    #
    # WARNING: Only add the preload option once you read about
    # the consequences in https://hstspreload.org/. This option
    # will add the domain to a hardcoded list that is shipped
    # in all major browsers and getting removed from this list
    # could take several months.
    add_header Referrer-Policy "no-referrer" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Download-Options "noopen" always;
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-Permitted-Cross-Domain-Policies "none" always;
    add_header X-Robots-Tag "none" always;
    add_header X-XSS-Protection "1; mode=block" always;

    # Optional: Don't log access to assets
    access_log off;
}

location ~ \.(?:png|html|ttf|ico|jpg|jpeg|bcmap)$ {
    try_files $uri /index.php$request_uri;
    # Optional: Don't log access to other assets
    access_log off;
}

        location ~ \.php$ {##delete##
            try_files /a1fc5821d2b5d92d0d04aa0046688818.htm @php;
        }

**Comment by ledufakademy** [comment]
> I found the related issues on GitHub: https://github.com/nextcloud/documentation/pull/1748/files / #8802

Yes you can !
this is an ISPconfig default nginx site conf.
with to much security (or normrl i don't know)

**Comment by alkino** [comment]
Duplicate of #8802
