### ISSUE TITLE
Exported groups are badly formatted - import not possible in thunderbird

### ISSUE THREAD

**Issue by olivy70** [nextcloud/server#23250]
Hey !

The problem is when I export a Group to import it in thunderbird.
The import generates an error "Error importing addresses from Vcard file".

I have noticed that sometimes there is a problem with the BEGIN / END of some Vcards.
The BEGIN and the END are on the same line, and it generates the import error.

ex:
BEGIN:VCARD
FN:Les affiches de la Haute-Saone
UID:0b5ca12e-96dd-4d3c-8aa8-f059048a5a9b
TEL;TYPE=VOICE:0633513887
EMAIL;TYPE=WORK:email@orange.fr
CATEGORIES:diffusion-presse
VERSION:3.0
N: ;;;;
END:VCARDBEGIN:VCARD --------------------------------------------------->problem
FN:Vosges FM
UID:bba054a4-eee0-48e2-a7eb-56bb3066ab72
EMAIL;TYPE=WORK:email@gmail.com
CATEGORIES:diffusion-presse
VERSION:3.0
N: ;;;;
END:VCARD

### Expected behaviour
BEGIN:VCARD
...
END:VCARD
BEGIN:VCARD
...
END:VCARD

### Actual behaviour
BEGIN:VCARD
...
END:VCARDBEGIN:VCARD
...
END:VCARD

## Server configuration detail

**Operating system:** Ubuntu

**Webserver:** nginx

**Nextcloud version:** 19.0.2

**Comment by j-ed** [comment]
@skjnldsv Interesting, this problem should already have been fixed with NC 18, based on [**this**](https://github.com/nextcloud/server/issues/18092) issue ticket.

**Comment by skjnldsv** [comment]
Let's add two more lines? xD

**Comment by olivy70** [comment]
I add that there is no problem with the export of an address book.
Only with groups.
