### ISSUE TITLE
Issue syncing __init__.py (for django projects at least)

### ISSUE THREAD

**Issue by josh-dix** [nextcloud/server#23268]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
I expect the projects to sync fully and without error.

### Actual behaviour
Syncing is paused at specific files that it has an error on. I've noticed the files mentioned in the subject cause this error repeatedly. This has also led to my nextcloud instance filling up with 25GB of error logs, but that is out of scope of the nextcloud project I am sure.

![Screenshot from 2020-10-07 11-15-33](https://user-images.githubusercontent.com/50813399/95353953-db739f80-0891-11eb-85d7-11cb64262c41.png)

### Steps to reproduce
1. create a django project in the nextcloud folders (with default hidden filters)
1a. install python
1b. python -m pip install django
1c. navigate to a directory inside nextcloud dir
1d. django-admin startproject mysite
2. allow the project to sync up to the nextcloud server (completes successfully)
3. try to sync on a different client device (fails with pictured error)
4. in order to delete the offending file, it must deleted from server ui, original client deletion doesn't seem to sync

### Client configuration
Client version:
Exists in all 3.0.x so far. I think I recall testing in a windows 2.6.x as well with same error.

Operating system:
Ubuntu

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Nextcloud version 3.0.2-20200924.150911.068ad89d8-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.1 LTS, x86_64

Client package (From Nextcloud or distro) (Linux only):
This seemed to start after a server upgrade to 18+ and seems to effect client versions in the 2.x and 3.x cross platform.
ppa:nextcloud-devs/client // nextcloud-client

Installation path of client:
ubuntu: /usr/bin/nextcloud

### Server configuration
Nextcloud version:
19.0.3

Storage backend (external storage):
s3 bucket

### Logs

1. Client logfile: 
Output of `nextcloud --logdebug --logwindow` or `nextcloud --logdebug --logfile log.txt`
https://www.cfs1.usdo2.uptimepros.com/nextcloud/index.php/s/i9zRqJxw4fNJ78F

2. Web server error log:
I think my permissions were blocking log generation for apache httpd so I'll need to create some.

3. Server logfile: nextcloud log (data/nextcloud.log):
https://www.cfs1.usdo2.uptimepros.com/nextcloud/index.php/s/x7KFAaPGRDw6ygK

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/server/pull/22651 and https://github.com/nextcloud/server/issues/22482.

**Comment by josh-dix** [comment]
#22651 was indeed the culprit and upgrading to 19.0.4 did the trick :).
