### ISSUE TITLE
Internal Server Error on new user login assigned to a group

### ISSUE THREAD

**Issue by divvet** [nextcloud/server#2328]
An odd problem has recently started with my Nextcloud install. When a new user is created and assigned to 2 particular groups, when they login they get the following error:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> 
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> 
> More details can be found in the server log.

**User groups:**
8 in total.

**Groups:** ad, aa, ac, ap, as, au, spm, sps

When user is assigned to a single group - no error.
When a user is assigned to 2 or more of a particular group, the error occurs. I drew a table showing which groups cause a conflict when assigned to a user.

![image](https://cloud.githubusercontent.com/assets/1207050/20626454/c77dc908-b311-11e6-8b4f-b4ce43fd7740.png)

 
### Steps to reproduce
1. Create 2 groups
2. create new user and assign to both groups
3. Error occurs on user 1 login

### Expected behaviour
User should log in without an error

### Actual behaviour
Following error occurs:

> Internal Server Error
> 
> The server encountered an internal error and was unable to complete your request.
> 
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> 
> More details can be found in the server log.

### Server configuration
**Operating system**: Ubuntu Server 16.04

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.0.11

**Nextcloud version:** (see Nextcloud admin page) 10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from Owncloud 8

**Where did you install Nextcloud from:** Zip File from website

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

> Integrity checker has been disabled. Integrity cannot be verified.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

```
> Enabled:
>   - activity: 2.3.2
>   - admin_audit: 1.0.0
>   - comments: 1.0.0
>   - dav: 1.0.1
>   - federatedfilesharing: 1.0.1
>   - files: 1.5.2
>   - files_pdfviewer: 0.8.1
>   - files_sharing: 1.0.0
>   - files_texteditor: 2.1
>   - files_trashbin: 1.0.0
>   - files_versions: 1.3.0
>   - files_videoplayer: 0.9.8
>   - firstrunwizard: 1.1
>   - gallery: 15.0.0
>   - notifications: 0.3.0
>   - password_policy: 1.0.0
>   - provisioning_api: 1.0.0
>   - serverinfo: 1.1.1
>   - survey_client: 0.1.5
>   - systemtags: 1.0.2
>   - templateeditor: 0.1
>   - theming: 1.0.1
>   - updatenotification: 1.0.1
>   - workflowengine: 1.0.1
> Disabled:
>   - encryption
>   - external
>   - federation
>   - files_accesscontrol
>   - files_automatedtagging
>   - files_external
>   - files_retention
>   - user_external
>   - user_ldap
>   - user_saml
> 

```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

> <?php
> $CONFIG = array (
> 'instanceid' => 'BLANKED',
> 'passwordsalt' => 'BLANKED',
> 'secret' => 'BLANKED',
> 'trusted_domains' =>
> array (
> 0 => 'BLANKED',
> 1 => 'BLANKED',
> 2 => 'BLANKED',
> ),
> 'datadirectory' => '/data/data',
> 'overwrite.cli.url' => 'http://BLANKED/owncloud',
> 'dbtype' => 'mysql',
> 'dbname' => 'owncloud',
> 'dbuser' => 'oc_mysql_user',
> 'dbpassword' => 'BLANKED',
> 'dbhost' => 'localhost',
> 'dbtableprefix' => 'oc_',
> 'version' => '9.1.1.5',
> 'installed' => true,
> 'mail_smtpmode' => 'smtp',
> 'forcessl' => false,
> 'forceSSLforSubdomains' => false,
> 'mail_smtphost' => 'mhs.swansea.ac.uk',
> 'mail_domain' => 'BLANKED',
> 'mail_from_address' => 'BLANKED',
> 'mail_smtpport' => '25',
> 'loglevel' => 0,
> 'maintenance' => false,
> 'theme' => '',
> 'trashbin_retention_obligation' => 'auto',
> 'memcache.local' => '\OC\Memcache\APCu',
> 'memcache.locking' => '\OC\Memcache\Redis',
> 'redis' =>
> array (
> 'host' => 'localhost',
> 'port' => 0,
> ),
> );

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

### Client configuration
**Browser:** Google Chrome/Firefox/Internet Explorer

**Operating system:** Windows 7/10

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
$

> 1. > {"reqId":"f4Mxp3mgC3QrjRQsZPMB","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:07:04+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 2. > {"reqId":"vF\/v3VJQKOmp0evdpXWv","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:07:34+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 3. > {"reqId":"BA\/YeHAvk9lAT63oZp2S","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:08:04+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 4. > {"reqId":"6CYAGkp0dFcukdWY3YIi","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:08:34+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 5. > {"reqId":"q+rXZTHe\/ZhxlaPRH6e8","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:09:04+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 6. > {"reqId":"CrC8C8EflUGc\/elfr9Sb","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:09:34+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 7. > {"reqId":"htrljwvCEGuiS1STnpQE","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:10:04+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 8. > {"reqId":"UvqB96r5Q5IJ8Ri5MsfB","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:10:34+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}
> 9. > {"reqId":"dhDAC\/tIpL9LRKyTJiCa","remoteAddr":"BLANKED","app":"PHP","message":"OCP\Files\NotFoundException: at \/var\/www\/owncloud\/lib\/private\/Share20\/Share.php#163","level":3,"time":"2016-11-16T10:11:04+00:00","method":"GET","url":"\/ocs\/v2.php\/apps\/notifications\/api\/v1\/notifications?format=json","user":"n.watkins"}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
ReferenceError: oc_appconfig is not defined
<anonymous>
shareconfigmodel.js:24
<anonymous>
shareconfigmodel.js:13
[Learn More]shareconfigmodel.js:24:4
TypeError: link is undefined
OC.filePath()
js.js:203
<anonymous>
viewer.js:4
[Learn More]js.js:203:1
TypeError: data.ocs is undefined
OCA.Notifications.fetch/<()
app.js:340
n.Callbacks/j()
jquery.min.js:2
n.Callbacks/k.fireWith()
jquery.min.js:2
x()
jquery.min.js:4
.send/b/<()
jquery.min.js:4
[Learn More]app.js:340:1
TypeError: data.ocs is undefined
OCA.Notifications.fetch/<()
app.js:340
n.Callbacks/j()
jquery.min.js:2
n.Callbacks/k.fireWith()
jquery.min.js:2
x()
jquery.min.js:4
.send/b/<()
jquery.min.js:4
[Learn More]
b) The network log
c) ...
```
</details>

**Comment by nickvergessen** [comment]
Seems like these groups have an invalid share. @rullzer to the rescue?

**Comment by rullzer** [comment]
I have a feeling this is https://github.com/nextcloud/server/issues/1862 so *should (tm)* be fixed in the next release.

**Comment by divvet** [comment]
Is there any fix in the short term? Causing kinda big problems in my organisation. I saw the #2091 fix, if I manually apply this fix should it resolve the issue?

**Comment by nickvergessen** [comment]
Should solve it, yes.

**Comment by divvet** [comment]
I can confirm #2091 fixed my issue. Thank you very much for the help!
