### ISSUE TITLE
Upload progress bar "invisible" when setting the theme colour to #FFFFFF

### ISSUE THREAD

**Issue by tgurr** [nextcloud/server#23283]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. set theming colour to #FFFFFF

![Screenshot_20201008_135135](https://user-images.githubusercontent.com/414984/95455289-ebf94800-096d-11eb-905a-13f42b2a97f9.png)

2. observe the upload progress bar being "invisible"

![Screenshot_20201008_134715](https://user-images.githubusercontent.com/414984/95455295-eef43880-096d-11eb-8020-96dba9212217.png)

### Expected behaviour
Still being able to properly read the file upload progress / have the progress bar displayed

### Actual behaviour
White progress bar on white background = invisible

### Server configuration

**Operating system:** Linux

**Web server:** Apache

**Database:** MariaDB

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Release Tarball

**Signing status:** ?

### Client configuration
**Browser:** Chromium

**Operating system:** Linux

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by tgurr** [comment]
> Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

Right now this appears to not longer be a valid issue on 25.0.x (can't test 24.0.x anymore) as the behaviour changed completely in recent versions and setting the color to #FFFFFF in the designs setting isn't applied to "everything" anymore, nextcloud is still mostly bluish including the progress bars where the setting previously affected more elements including the progress bar. So on one hand this issue is no longer valid on the other it's a step back in being able to customize colors/designs at all.

**Comment by szaimen** [comment]
> So on one hand this issue is no longer valid 

Lets close this issue then.

> on the other it's a step back in being able to customize colors/designs at all.

Please create a feature request for this. Thanks!
