### ISSUE TITLE
Enable to pull list of all enabled apps over API

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#23297]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
This is related to nextcloud/ios#1435. Currently, there is no way to pull a list of all enabled apps. However, this is needed in order to check whether the comments app is enabled. If this is not the case, the comment section shall be hidden in the ios app. 

**Describe the solution you'd like**
Something similar to https://cloud.example.com/ocs/v2.php/core/navigation/apps but for all apps (not only navigation).

**Describe alternatives you've considered**
Trying to send a comment will trigger a 404. This could be catched and handled accordingly, but thats a huge technical debt.

**Additional context**
nextcloud/ios#1435
Access to the list of all enabled apps should be limited to logged in users for security reasons.

**Comment by szaimen** [comment]
Based on this comment it is already possible to do so via the capabilites endpoint:
https://github.com/nextcloud/ios/issues/1435#issuecomment-706885532
