### ISSUE TITLE
drop down overlap in share dialog

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2329]
Share a folder with two users, user1 and user2

Now try to change the permission for user1 (the user at the top of the list):
* click on the three dot menu
* click on "can create"

Now the change permission for user1 is triggered but at the same time the underlaying "three dot menu" for user2 gets clicked. This is the result:

![bug2](https://cloud.githubusercontent.com/assets/1589737/20627549/13f3429a-b321-11e6-9863-c0acd91d68b5.png)

**Comment by schiessle** [comment]
Maybe @rullzer or @blizzz can have a look?

**Comment by blizzz** [comment]
Confirmed, bisecting

**Comment by blizzz** [comment]
Fix in https://github.com/nextcloud/server/pull/2363

**Comment by MorrisJobke** [comment]
Fixed with #2363
