### ISSUE TITLE
[18.0.10] Wrong check for update, infrastructure?

### ISSUE THREAD

**Issue by dirigit** [nextcloud/server#23301]
After updating NC to 18.0.10 I expect systemcheck to show correct information.

Currently it shows wrong info:

Testsite 18.0.10

Eine neue Version ist verfügbar: Nextcloud 18.0.10

**Comment by mlsxlist** [comment]
Same here:

![image](https://user-images.githubusercontent.com/6071818/95585994-4d89e700-0a40-11eb-8312-cc117a25ff5b.png)

root@box:/var/www# sudo -u www-data php /var/www/nextcloud/occ status
  - installed: true
  - version: 18.0.10.2
  - versionstring: 18.0.10
  - edition:

**Comment by J0WI** [comment]
:ping_pong: @nextcloud/infrastructure

**Comment by MorrisJobke** [comment]
On 18.0.x (that is not 18.0.10) it should show 18.0.10:

https://github.com/nextcloud/updater_server/blob/master/config/config.php#L143-L158

And on 18.0.10 it should show 19.0.4:

https://github.com/nextcloud/updater_server/blob/master/config/config.php#L127-L142

Don't fully know why it shows you the old one. 


18.0.9 gets a 18.0.10:

<img width="1082" alt="Bildschirmfoto 2020-10-12 um 14 45 54" src="https://user-images.githubusercontent.com/245432/95747997-a43e2d80-0c99-11eb-8b64-ba692304ce54.png">

18.0.10 gets 19.0.4:

<img width="1081" alt="Bildschirmfoto 2020-10-12 um 14 46 28" src="https://user-images.githubusercontent.com/245432/95748048-b750fd80-0c99-11eb-8668-927ba3015285.png">

So the updater server itself works correct. 

Could you show the content of your version.php?

**Comment by kesselb** [comment]
As additional information: https://help.nextcloud.com/t/updatechecker-permanently-breaks-the-overview-panel-after-upgrade/63683

The result (`lastupdateResult`) from the updater server is cached for 30 minutes. On successful upgrade the value for `lastupdatedat` is set to 0 (that invalidates the cache).

Sometimes the value is not set to 0 which uses the cached response with the previous update announcement. Usually that's fixed 30 minutes later ;)

I'm not sure how to reproduce this issue in the wild. Maybe a broken / interrupted update somehow.
