### ISSUE TITLE
LDAP user refresh with caching enabled

### ISSUE THREAD

**Issue by andreas-p** [nextcloud/server#2330]
I'm auth'ing using user_ldap, and have APCU caching enabled.

When users/groups are changed in ldap, this isn't reflected immediately in NC because caching will prevent re-reading the ldap server, which is fine for most requests. But when accessing /settings/users, I'd expect the cache to be bypassed/partially cleared to update NC data from LDAP. Currently, I have to purge the cache by restarting apache.

**Comment by blizzz** [comment]
The scenario "add user in LDAP + go to Nc users page" sounds to me not to be a case that happens very often. I expect  that  going to the users page without having an LDAP change before is the use case that happens more often, and there performance  benefits.

**Comment by andreas-p** [comment]
The scenario "add user in LDAP + go to Nc users page" happens whenever I change users... And I'd certainly expect my ldap users here.

**Comment by blizzz** [comment]
I don't have any intention  to work on this. If it is such a troubling issue, I expect a PR (that won't impact the usual case). In that case please re-open.
