### ISSUE TITLE
InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.

### ISSUE THREAD

**Issue by Abenstex** [nextcloud/server#23309]
I'm using PostgreSQL and during upgrade to version 18.10 I got the following error:

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: Not a mysql database -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert -> database updated

InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.

**Comment by Abenstex** [comment]
I found the answer in an older issue via google

**Comment by acsfer** [comment]
Duplicate of https://github.com/nextcloud/server/issues/23174
