### ISSUE TITLE
404 for user home folder after upgrade from 19.0.3 to >=19.0.4, 20, 21, 22 & 23

### ISSUE THREAD

**Issue by csware** [nextcloud/server#23315]
### Steps to reproduce
1. Upgrade from 19.03 to 19.04 using web updater
2. Log in to nextcloud or use the nextcloud desktop app

### Expected behaviour
After logging in I expect to see all my files respective the Nextcloud Desktop app to synchronize all files.

### Actual behaviour
 After logging in I see an empty file list and Nextcloud Desktop says "404 folder does not exist"

Maybe this is related to my username which is for historic reasons "name+extension@domain".

### Server configuration

**Operating system:** Debian Buster

**Web server:** Apache 2.4

**Database:** 10.3.23-MariaDB-0+deb10u1-log

**PHP version:** PHP 7.3.22-1+0~20200909.67+debian10~1.gbpdd7b72

**Nextcloud version:** (see Nextcloud admin page) 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19.0.3

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.1.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_external: 1.10.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - gpxpod: 4.2.2
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - photos: 1.1.0
  - polls: 1.5.4
  - provisioning_api: 1.9.0
  - richdocuments: 3.7.4
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - systemtags: 1.9.0
  - tasks: 0.13.3
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - password_policy
  - privacy
  - recommendations
  - support
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "loglevel": 2,
        "integrity.check.disabled": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/XXX\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "maintenance": false,
        "theme": "",
        "overwrite.cli.url": "https:\/\/XXX",
        "overwriteprotocol": "https",
        "activity_expire_days": 31,
        "trusted_domains": [
            "XXX"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trashbin_retention_obligation": "auto",
        "htaccess.RewriteBase": "\/",
        "mail_smtpmode": "sendmail",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "appstore.experimental.enabled": false,
        "singleuser": false,
        "log_rotate_size": 104857600,
        "logtimezone": "Europe\/Berlin",
        "mail_sendmailmode": "pipe",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "filelocking.enabled": true,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "mysql.utf8mb4": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 81.0.1

**Operating system:** Win10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
XXX - - [09/Oct/2020:15:50:26 +0200] "PROPFIND /remote.php/dav/files/name+extension@domain/ HTTP/1.1" 404 1075 "-" "Mozilla/5.0 (Windows) mirall/2.6.5stable-Win64 (build 20200710) (Nextcloud)"
XXX - - [09/Oct/2020:15:50:43 +0200] "PROPFIND /remote.php/dav/files/name+extension@domain/ HTTP/2.0" 404 585 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:81.0) Gecko/20100101 Firefox/81.0"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No related log entries.
```
</details>

**Comment by csware** [comment]
Downgrading to 19.0.3 solved the issue.

**Comment by kesselb** [comment]
> Maybe this is related to my username which is for historic reasons "name+extension@domain".

Sounds like https://github.com/nextcloud/server/pull/22770.

**Comment by kesselb** [comment]
cc @nextcloud/server-triage :wave:

**Comment by csware** [comment]
Maybe related: In 19.0.3 the trash is display as empty for that user, however, the `name+extension@domain/files_trashbin/files/` folder contains several files (also a `./occ files:scan -- name+extension@domain` did not help).

**Comment by skjnldsv** [comment]
@MorrisJobke @nickvergessen @blizzz

**Comment by csware** [comment]
> Maybe related: In 19.0.3 the trash is display as empty for that user, however, the `name+extension@domain/files_trashbin/files/` folder contains several files (also a `./occ files:scan -- name+extension@domain` did not help).

After further debugging: This is indeed unrelated. Firefox shows me a XML processing error (caused by a filename which is not proper UTF-8). Should in this case an error shown to the user instead of "there are not deleted files"?

**Comment by nickvergessen** [comment]
For now affected instances can revert https://github.com/nextcloud/server/pull/22770/files locally.

Since `+` can not be used it should be the exception here. So maybe we can add it as a fall back when we didn't find the user with `urldecode()` we try without?

**Comment by csware** [comment]
This issue is still in 19.0.5, requiring affected people to update and then patch their installation manually.

I don't think that such unsystematic/random encodings/decodings should be done at all.

**Comment by csware** [comment]
Still an issue in 20.0.0.7 and also seems to be stinn an issue for 21.

**Comment by csware** [comment]
Still an issue in 22.2.3

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by csware** [comment]
THis issue is still there, however, I created a new account.

**Comment by szaimen** [comment]
in which nc version did you test?

**Comment by csware** [comment]
The issue is still in the code: https://github.com/nextcloud/server/blob/9ecec2fd753bb98446333ff95833abb198a1cdc5/apps/dav/lib/Connector/Sabre/Principal.php#L166 Unsystematic/random encodings/decodings should not be done at all.

However, in the meantime other tools have ended to support `+` in the username. Not a good process at all.

**Comment by szaimen** [comment]
As workaround for now, you could create a new user with a better userid and transfer your files to that.

**Comment by csware** [comment]
@szaimen See my comment above. I created a new account and moved everything. Moving the files worked okay, but oll other stuff such Calendars etc. was a PITA.

**Comment by szaimen** [comment]
Ah yes, true.

**Comment by csware** [comment]
Except for https://github.com/nextcloud/server/issues/23315#issuecomment-706985640 this is a non issue any more for me - I only question that there are random/unsystematic encodings/decodings.

**Comment by skjnldsv** [comment]
Hey, so, I'm tempted to close as we fixed this by forbidding such characters now.
It's been done for a while, and while it is not ideal for old users, this is kind of a legacy issue that should fade off over time.

It now throws the following

> Only the following characters are allowed in a username: "a-z", "A-Z", "0-9", spaces and "_.@-'"
