### ISSUE TITLE
file upload conflict dialog broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2331]
Try to upload twice the same file so that the upload conflict dialog is shown. As you can see the dialog is broken on master (previews and checkboxes are not shown at the right place):

Firefox only, Chrome/Chromium is fine.

![bug1](https://cloud.githubusercontent.com/assets/1589737/20627596/6067f486-b321-11e6-9b9b-203c511e45a0.png)

**Comment by MorrisJobke** [comment]
Works here. (Maybe also give #2342 a try)

**Comment by nickvergessen** [comment]
Broken here as well with Firefox, also #2342 doesn't help.

However works fine in Chromium with and without the patch.

**Comment by nickvergessen** [comment]
@nextcloud/designers should be fixed before the 11 release

**Comment by MorrisJobke** [comment]
> After the recent fixes in #2342 I can't reproduce this anymore (only on small screens where those two elements doesn't fit beside each other).

Tested in Firefox.

**Comment by nickvergessen** [comment]
I just pulled master and the issue still exists for me.

The conflict div is 457px wide, both entries 230px. So they can not be displayed next to each other.

@MorrisJobke maybe it's because Firefox on iOS has a scrollbar which is much smaller?

**Comment by MorrisJobke** [comment]
> @MorrisJobke maybe it's because Firefox on iOS has a scrollbar which is much smaller

Ah - possible.
