### ISSUE TITLE
User syncing for trusted servers does not work anymore after update to Nextcloud 20

### ISSUE THREAD

**Issue by lars-a** [nextcloud/server#23316]
After updating to Nextcloud 20 the users are not seen anymore on other federated Nextcloud instances setup as trusted servers of each other.

Steps to reproduce:
- Install 2 Nextcloud 19 instances and setup each as trusted server for the other. Each instance shows the users of the other instance in the autocompletion for the sharing input field. Also in the settings of each instance the other server is shown with a green symbol. So at this point everything is working as expected.
- Update instance 1 to Nextcloud 20 and after that instance 2 can no longer see the users of instance 1. It is also shown with an orange symbol in the settings of instance 2. And "occ federation:sync-addressbooks" returns "Error while syncing https://servername/nextcloud : Unauthorized". 

As long as instance 2 is kept on Nextcloud 19 the sync in the other direction still works and the users of instance 2 are shown on instance 1. After updating instance 2 the Nextcloud 20 this also stops working.

OS: openSUSE Leap15.2
PHP 7.4.11
DB: mariadb 10.4.14

**Comment by Mystikal57** [comment]
Same problem for me

**Comment by michaelkuhn** [comment]
I have the same problem with two servers, one running NC 19 and one running NC 20. The logs of the NC 20 server contain lines like this:
```
Login failed: 'system' (Remote IP: 'x.x.x.x')
```

**Comment by michaelkuhn** [comment]
I just checked today after updating to Nextcloud 20.0.3 and the problem seems to be fixed for me.

**Comment by faust64** [comment]
Have you tried updating to a recent 20.0.x, @lars-a ? Still having that issue?

**Comment by lars-a** [comment]
> 
> 
> Have you tried updating to a recent 20.0.x, @lars-a ? Still having that issue?

I have updated my nextcloud instances to 20.0.7 and this issue is fixed.

**Comment by szaimen** [comment]
based on lars-a's comment I am closing this. Feel free to open a new issue if you should still experience this on NC21.0.2

**Comment by benks-io** [comment]
for me it helped to:

- add the servers it self as a trusted server
- trigger the cron job on booth ends two times,
- and trigger `occ dav:sync-system-addressbook` and `occ federation:sync-addressbooks`
