### ISSUE TITLE
Ability to disable or restrict unified search

### ISSUE THREAD

**Issue by nursoda** [nextcloud/server#23311]
While I see the benefit of unified search, it sometimes leads to weird results. I tried to search a user in settings/users (to "impersonate" her). I could use my browser's in-page search (Ctrl-F) for that…but NC "hijacks" that hotkey (which is fine, too). Until NC19, I got results quickly. In NC 20, unified search is enabled and that takes way longer – too long I think, at least in an instance with many users and with many apps installed (as in my case). Therefore, I'd love to have a possibility to either unset Ctrl-F in NC or to restrict certain dialogs, like "Don't use unified search in [ ] settings [ ] apps [ ] users dialogs."

**Comment by dassio** [comment]
hijacking Ctrl-F is really not good, it breaks the overall experience, you open 10 tabs and looking for stuff, all of sudden , Ctrl-F is not working , really anoying .

**Comment by nursoda** [comment]
@dassio I partly disagree. I think that using the search shortcut for the "hijacked" full-system search is what most people expect. I'd even expect it in settings/users – but we have TWO reactions here: one on the main page (less users displayed in the list) and one in the search box (which I did not intend to use IN THIS CASE).

A possible solution would be to reduce the number of entries in the list (as prior to 20) and display a SMALL clickable notification-like dialog next to the search button. That way, the admin can either modify the user OR check what unified search yielded.

**Comment by skjnldsv** [comment]
> Therefore, I'd love to have a possibility to either unset Ctrl-F in NC

Press it twice. :)
Lots of websites are doing this, this is the expected behaviour

**Comment by nursoda** [comment]
Didn't know that, thanks!
