### ISSUE TITLE
Can't Edit Personal Info's After Updating Nextcloud 19 to 20

### ISSUE THREAD

**Issue by IzumiSena** [nextcloud/server#23312]
Nextcloud Personal Info,s 
Phone number, Address, Website, Twitter i can't edit this, look at this photo,,, 
after updating nextcloud 19 to 20 i am facing this problem

![Screenshot from 2020-10-09 18-59-28](https://user-images.githubusercontent.com/61591769/95586139-c5034a80-0a2f-11eb-8cf9-92e1e77377f6.png)
 
Please Help me if there is already a way to fix this, Thanks

OS Debian 10

DB MariaDB 10.3.23

PHP 7.3.19

**Comment by kesselb** [comment]
Looks like https://github.com/nextcloud/server/issues/21212. Please use https://help.nextcloud.com/ for questions the next time. Thanks ;)
