### ISSUE TITLE
clicking the current folder should refresh file listing

### ISSUE THREAD

**Issue by doomi** [nextcloud/server#2332]
### Steps to reproduce
1. go to Files
2. go to a subfolder, i.e. "photos"
3. upload a file from the mobile app
4. click the foldername above the file listing

### Expected behaviour
the folder should refresh and show the newly uploaded file.

### Actual behaviour
the folder does not refresh.
as a workaround, you have to leave the current folder and coming back to refresh the file listing.

### Server configuration
**Nextcloud version:** 10.0.1
no additional information, because it's a hosted environment (portknox.net)

**Comment by ChristophWurst** [comment]
cc @jancborchardt

**Comment by jancborchardt** [comment]
Yep, that's a good call. We could also habe a pull to refresh like in the Mail app cc @nextcloud/javascript

**Comment by abhanshgiri21** [comment]
hey,
i am new to open source projects i want to start working on open source projects. can i get help on how to start working on open source and as a beginner, which issues can i fix.?

**Comment by Henni** [comment]
@abhanshgiri21 best point to get started is our IRC channel: #nextcloud-dev
Also take a look at the developer documentation: https://docs.nextcloud.com/server/11/developer_manual/

If you want to have a go at this issue, I believe the right place would be the [files app's javascript code](https://github.com/nextcloud/server/tree/master/apps/files/js).
Take a look around and feel free to ask anytime you need help.

**Comment by abhanshgiri21** [comment]
there are so many files, what am i supposed to do, which file has tha code that i have to edit.!? @Henni

**Comment by Henni** [comment]
@abhanshgiri21 I haven't worked on the files app. I believe the right people to help you out, probably are @rullzer and @MorrisJobke, as they contributed to the initial webdav implementation of the files app.
