### ISSUE TITLE
Weather widget shows the wrong time. i.e., it show the UTC time instead of local time

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/server#23330]
### Steps to reproduce
Weather widget shows the wrong time 

### Expected behavior
Weather widget should show the time of local time of either server or current local time of the location

### Actual behaviour
Weather widget shows the wrong time , i.e., it show the UTC time instead of local time

### Server configuration

**Operating system:** Ubuntu 18.04 LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** PHP 7.4

**Nextcloud version:** (see Nextcloud admin page) 20

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgraded from 19.x

**Where did you install Nextcloud from:** Official Web page

**Comment by DrCarsonBeckett** [comment]
I can confirm that on my system as well:

Server configuration
Operating system: Debian Buster 10
Web server: Apache/2
Database: MySQL (MariaDB)
PHP version: PHP 7.4
Nextcloud version: 20.0.0.9
Updated from an older Nextcloud/ownCloud or fresh install: Upgraded 19.0.3.1 to 19.0.4.x and then to 20.
Where did you install Nextcloud from: Downloaded the files from the official website and uploaded them manually.

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/23399
