### ISSUE TITLE
Translation issues

### ISSUE THREAD

**Issue by DrCarsonBeckett** [nextcloud/server#23337]
There seems to be an issue (at least after upgrading from 19 to 20) with the dashboard. For me, it gets shown partially in english.
I get greethed in english, the customize button is in english, the weather too. The status system seems to be completely in english as well. When I press customize, its mostly english too.

Server configuration
Operating system: Debian Buster 10
Web server: Apache/2
Database: MySQL (MariaDB)
PHP version: PHP 7.4
Nextcloud version: 20.0.0.9
Updated from an older Nextcloud/ownCloud or fresh install: Upgraded 19.0.3.1 to 19.0.4.x and then to 20.
Where did you install Nextcloud from: Downloaded the files from the official website and uploaded them manually.

**Comment by NorryNew** [comment]
your preferred language will be? Than the translation team can have a look.

**Comment by DrCarsonBeckett** [comment]
Oh, yea ... sorry. Its german.

**Comment by NorryNew** [comment]
We work hard to translate and review all strings @rakekniven  would be happy for any help.
https://help.nextcloud.com/t/die-deutsche-ubersetzung-von-nextcloud-hier-diskutieren-und-fehler-melden-was-sollte-ich-wissen-wenn-ich-bei-der-ubersetzung-helfen-mochte-oder-eine-anmerkung-habe/32139/328

**Comment by kesselb** [comment]
Thank for you reporting @DrCarsonBeckett :+1: 

I'm closing this report in favour of https://github.com/nextcloud/server/issues/23337. It seems that the translations for user_status and weather app the translations not bundled with the latest release.

**Comment by rakekniven** [comment]
> I'm closing this report in favour of #23337

That is the same issue no. as of that thread
