### ISSUE TITLE
Serverinfo & Apps-Overview not load when https://apps.nextcloud.com is down

### ISSUE THREAD

**Issue by VimS** [nextcloud/server#23338]
Since https://apps.nextcloud.com is down my nextcloud was not able to show Serverinfo or Apps-Overview-Page:

I worked around this by chaning the Timeout for Guzzle form 60 seconds to 10, but I suggest you build in some kind of mechanism to stop this behaviour. For example Catch the Guzzle-Eception which should be thrown when a Server is not reachable.

https://github.com/nextcloud/server/blob/081c974971e5ff7c8f4b8c39a4ad91742d8058a7/lib/private/App/AppStore/Fetcher/Fetcher.php#L110

**Comment by paulcalabro** [comment]
I'm also seeing this error.

**Comment by kesselb** [comment]
Closing this report in favour of https://github.com/nextcloud/server/issues/23334. Please check the pinned issues or use the search  the next time. Thanks ;)

If you prefer to not mess around with code it's also possible to turn the apps store off:

https://github.com/nextcloud/server/blob/081c974971e5ff7c8f4b8c39a4ad91742d8058a7/config/config.sample.php#L921-L926

(for the time the server is not available)
