### ISSUE TITLE
Could not connect to appstore: cURL error 28: Connection timed out after 60000 milliseconds

### ISSUE THREAD

**Issue by parasudilip** [nextcloud/server#23342]
Its a fresh default install of nextcloud.
Nothing else is done on the config side, its default.

The appstore dosent show apps from nextcloud store

curl https://apps.nextcloud.com/api/v1/categories.json    and
curl https://apps.nextcloud.com    
Shows returns nothing

**Comment by BORIKKEN21** [comment]
the server has been down for 10h and with problems since the last 3 days

**Comment by parasudilip** [comment]
Ohh, didn't know about that.
Reinstalled nextcloud 2 times because of this.
