### ISSUE TITLE
Error 404 when you want to open contact using loupe

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/server#23341]
Steps to reproduce
1. Try to find any contact using loupe
2. Try to open selected contact -> error 404

Server configuration

Operating system:
Ubuntu 20.04

Web server:
Apache

Database:
SQLite

PHP version:
7.4.3
Nextcloud version: (see Nextcloud admin page)
20.0

Updated from an older Nextcloud/ownCloud or fresh install:
upgrade from 19.03
Client configuration

Browser:
Firefox
Operating system:
Ubuntu 20.04

**Comment by skjnldsv** [comment]
https://github.com/nextcloud/contacts/issues/1852
