### ISSUE TITLE
Move files expose complete folder structure on public links

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2334]
* Share a folder with some files as public link with edit permissions
* open the public link
* the "three dot menu" of the files will show the "move" operation
* click on it

![move2](https://cloud.githubusercontent.com/assets/1589737/20628149/ac230c5a-b324-11e6-8695-a3290e910a2d.png)

Result:

You see the root of the users files folder. You can move the files to any location and look at the complete folder structure of the user

Expected:

Only show folders within the shared folder

cc @icewind1991

**Comment by LukasReschke** [comment]
I think that is because the WebDAV call is performed with the wrong credentials. Can you try in a private tab?

So there is no actual real loss of information but simply the credentials of the logged-in users used. At least from how I understand the code.

**Comment by LukasReschke** [comment]
Yep. Move seems to connect against `/remote.php/webdav` instead `/public.php/webdav`

cc @icewind1991 Can you take a look? THX :)

**Comment by schiessle** [comment]
yes, in a private tab we don't expose the whole directory structure but the dialog is still broken. It shows a spinner and "Problem loading page, reloading in 5 seconds"
