### ISSUE TITLE
Can't access Apps when apps.nextcloud.com is not responding. 

### ISSUE THREAD

**Issue by szakes1** [nextcloud/server#23349]
### Steps to reproduce
1. Install Nextcloud
2. Go to Apps section on menu
3. Apps try to load but with no effect

### Expected behaviour
Apps should load and I would be able to edit my apps: disable them, enable and remove them. It'd be better if I would be able to edit my Apps first instead going straight into App Store. If apps.nextcloud.com is inaccessible, this prevents me to edit my Apps, because it loads the App Store first. 

### Actual behaviour
Instead Apps are loading and I can't access Apps. In the log file, it shows that Nextcloud can't access apps.nextcloud.com. 

### Server configuration

**Operating system: Ubuntu 20.04 LTS**

**Web server: Nginx (docker)**

**Database: MariaDB/PostGreSQL**

**PHP version: the newest (doesn't matter anyway)**

**Nextcloud version: 20.0.0** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install: Fresh install**

**Where did you install Nextcloud from: linuxserver/nextcloud docker image**

**Comment by szakes1** [comment]
This should actually be a feature not a bug request, but it's a bug in the same time.

**Comment by philipreimer** [comment]
https://apps.nextcloud.com/ seems to be down.

Can't access it, neither in browser nor in nextcloud Apps section.

Is this a planned maintenance?

@szakes1 I can manage my apps in nextcloud Apps section, but it takes a very long time to load.

**Comment by szakes1** [comment]
> https://apps.nextcloud.com/ seems to be down.
> 
> 
> 
> Can't access it, neither in browser nor in nextcloud Apps section.
> 
> 
> 
> Is this a planned maintenance?
> 
> 
> 
> @szakes1 I can manage my apps in nextcloud Apps section, but it takes a very long time to load.

Yes, It's probably down. I can't access it either.

**Comment by kesselb** [comment]
Closing this report in favour of #23334. Please check the pinned issues or use the search the next time. Thanks ;)

**Comment by funky123** [comment]
It seems as long as the apps.nextcloud.com is down, your cannt acces new apps via your own nextcloud instance. :( but i need the occ app for fixing my update issues :( :( 

does anyone know why its down?

**Comment by szakes1** [comment]
> It seems as long as the apps.nextcloud.com is down, your cannt acces new apps via your own nextcloud instance. :( but i need the occ app for fixing my update issues :( :( 
> 
> 
> 
> does anyone know why its down?

No one knows, we have to wait for their message.

**Comment by funky123** [comment]
zzz Jesus help us to get this fixed

**Comment by Schmidtjanroman** [comment]
Same problem seems to be active at the moment, can't access the website nor the store on my NC installtion.
