### ISSUE TITLE
InvalidArgumentException: Column name "SrjM9_flow_operations"."entity" is NotNull, but has empty string or null as default.

### ISSUE THREAD

**Issue by nextcloud1** [nextcloud/server#23358]
Hi there!

Tried to web-update from V17->V18.

Stuck in the second step, it says:

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

InvalidArgumentException: Column name "SrjM9_flow_operations"."entity" is NotNull, but has empty string or null as default.

Can anyone help, please?

Thank You so much!

**Comment by kubjo** [comment]
Same here:
Tried to web-update from V17.0.10->V18.0.10

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
**InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.**

Any suggestions what to do?

**Comment by acsfer** [comment]
Duplicate of https://github.com/nextcloud/server/issues/23174
