### ISSUE TITLE
nextcloud logo in email notifications is misaligned in version 20.0.0

### ISSUE THREAD

**Issue by govindsmenokee** [nextcloud/server#23357]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Mind to add a screenshot? Also for email issues it's helpful to include which email client you are using. The clients render html different.

**Comment by axheli** [comment]
![image](https://user-images.githubusercontent.com/59488153/95698545-d1da9680-0c07-11eb-8ddf-95b18e844a4d.jpeg)

**Comment by govindsmenokee** [comment]
Tested with multiple clients(Gmail, Outlook, Thunderbird) it is misaligned in every single one of them.

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by skjnldsv** [comment]
Cannot reproduce, centered for me :thinking:

**Comment by medcloud** [comment]
I also reproduce issue with current configuration

## Server configuration
#### Operating system:
Debian 10

#### Web server:
Apache 2.4

#### Database:
PG10

#### PHP version:
PHP 7.3

#### Nextcloud version: (see Nextcloud admin page)
NextCloud v 20.0.1

#### Updated from an older Nextcloud/ownCloud or fresh install:
NextCloud v 17.0.9

#### List of activated apps:
Accessibility 1.6.0 / Activity 2.13.2 / Calendar 2.1.2 / Comments 1.10.0 / Contacts 3.4.1 / Contacts Interaction 1.1.0 / Custom CSS 1.7.0 / Dashboard 7.0.0 / Data Request 1.7.0 / Deleted files 1.10.1 / DICOM Viewer 1.2.2 / External sites 3.7.1 / File sharing 1.12.0 / Group folders 8.1.0 / Log Reader 2.5.0 / Notifications 2.8.0 / Password policy 1.10.1 / PDF viewer 2.0.1 / Photos 1.2.0 / Recommendations 0.8.0 / Right click 0.17.0 / Share by mail 1.10.0 / Support 1.3.0 / Text 3.1.0 / Theming 1.11.0 / Update notification 1.10.0 / Usage survey 1.8.0 / User status 1.0.0 / Versions 1.13.0 / Video player 1.9.0 / Weather status 1.0.0

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

#### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

#### Operating system:
Windows 10 Version 10.0.19041 Numéro 19041

**Comment by medcloud** [comment]
OK, I think I have found a solution changing in EMailTemplate.php 2 lines. The problem was visible in Gmail, Hotmail, Outlook, etc...

I think change in EMailTemplate.php may have solved issue :

Original code (line 123 to 125) :

````
<center data-parsed="" style="background-color:%s;width:150px;height:150px;padding:0px;position:relative;border-radius:200px">
	<img class="logo float-center" src="%s" alt="%s" align="center" style="-ms-interpolation-mode:bicubic;clear:both;display:block;float:none;outline:0;text-align:center;text-decoration:none;position:absolute;max-height:100px;max-width:100px;width:auto;height:auto;position:absolute;top:0;bottom:0;left:0;right:0;margin:auto;">
</center>
````

Changed by the code (line 123 to 125) :

````
<center data-parsed="" style="background-color:%s;min-width:150px;padding:50px 0;border-radius:200px">
       <img class="logo float-center" src="%s" alt="%s" align="center" style="-ms-interpolation-mode:bicubic;Margin:0 auto;clear:both;display:block;float:none;margin:0 auto;outline:0;text-align:center;text-decoration:none" height="50">
</center>
````

### Before

![Before - Gmail iOS2](https://user-images.githubusercontent.com/42641918/99016072-9872af00-2556-11eb-9d86-8c91558e9da4.png)

### After

![After - Gmail iOS2](https://user-images.githubusercontent.com/42641918/99016141-b93b0480-2556-11eb-92ba-f742d2452265.png)

**Comment by medcloud** [comment]
Same modifications made for #23977

**Comment by skjnldsv** [comment]
Can you open a pr @medcloud ? :)

**Comment by medcloud** [comment]
Yes : I will just test a last thing, and if it works well I will open en pull request by end of week-end !

**Comment by medcloud** [comment]
OK, so before pulling a request, I just wanted to check again the rendering with original Nextcloud logo. So, the code modification I propose is mainly focused on a square logo which would be correctly centered. However, for a logo like Nextcloud one (252x120px) the display is a bit different but acceptable from my point of view. Anyway, I think it will always depend on theme logo which can be different from one to another.

Final proposal in EMailTemplate.php file is (line 123 to 125) :
```
<center data-parsed="" style="background-color:%s;min-width:175px;max-height:175px; padding:35px 0px;border-radius:200px">
     <img class="logo float-center" src="%s" alt="%s" align="center" style="-ms-interpolation-mode:bicubic;clear:both;display:block;float:none;margin:0 auto;outline:0;text-align:center;text-decoration:none max-height:105px;max-width:105px;width:auto;height:auto" width="105px" />
</center>
```
 Display in Gmail (Chrome and Gmail iOS app) are for both versions (Nextcloud logo, and a fictive square logo) 

![Last - Apres correction Gmail Chrome NC](https://user-images.githubusercontent.com/42641918/99129159-1ee9c800-260d-11eb-965d-42973861047f.png)

![Last - Apres correction Gmail Chrome Exemple](https://user-images.githubusercontent.com/42641918/99129178-28733000-260d-11eb-9fe8-5359900bb02d.png)

![Last - Apres correction Gmail iOS Exemple](https://user-images.githubusercontent.com/42641918/99129197-31640180-260d-11eb-8678-17db8ead67e9.png)

![Last - Apres correction Gmail iOS NC](https://user-images.githubusercontent.com/42641918/99129205-3759e280-260d-11eb-94a8-1de5ec65bd00.png)

Now, I will try to open a pull request ;-) (Never done)

**Comment by skjnldsv** [comment]
> Now, I will try to open a pull request ;-) (Never done)

You can check our readme if you want, it have some useful informations on how to proceed :)
https://github.com/nextcloud/server/#development-setup-

Welcome!!

**Comment by medcloud** [comment]
Thanks : I tried my forst pull request.

I red on your development setup page : Create a pull request and @mention the people from the issue to review

I hope, I did well > PR is at #24135

**Comment by cphan97** [comment]
Hello Everyone,

I have a issue, my problem is when i send a email or the notification, i don't have a logo....
![Capture](https://user-images.githubusercontent.com/77049257/103752166-a5b59280-5009-11eb-8086-5c9fb5b30773.PNG)

I installed Nextcloud version : 2.0.4.0 with apache.

Please can you help me,

Thanks a lot !
