### ISSUE TITLE
Why is the performance of nextcloud v19.0.0.1 so poor, it took 5s to call the add user interface?

### ISSUE THREAD

**Issue by fan4905** [nextcloud/server#23365]
I used the nextcloud v19.0.0.1 version and used postman to call the /ocs/v1.php/cloud/users interface to add users. The result took 5 seconds to return. I checked the cause and found lib/private/User/Manager. PHP’s createUserFromBackend method executes to $this->emit('\OC\User','postCreateUser', [$user, $password]); this line took 2 seconds, why is this line of code so time-consuming ?

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
