### ISSUE TITLE
Nextcloud index page bugged (/#app-content)

### ISSUE THREAD

**Issue by Rhobil** [nextcloud/server#23366]
#23145 # Steps to reproduce

3 Ways:

1a. Login into nextcloud -> done

1b. Already logged in
2b. Click on Nextcloud Icon in left corner -> done

1c. enter website url (only domain) into browser after logged in -> done

### Expected behaviour

Correct nextcloud with default app active should be displayed (in this case: activity)

### Actual behaviour

Strange, ugly page applies (see screenshot)
Could be a mobile page with errors in css (?)

### Screenshot
![nextcloud19_bug](https://user-images.githubusercontent.com/44193271/95719245-d5096d00-0c6f-11eb-9dc0-3159877ba9c3.jpg)

### Server configuration

**Operating system:**

Linux Debian-102-buster-64-minimal 4.19.0-9-amd64

**Web server:**
 Apache/2.4.38 (Debian)

**Database:**
mysql 19.0.4.2

**PHP version:**
PHP 7.3.19-1~deb10u1

**Nextcloud version:** (see Nextcloud admin page)
19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
18.x

**Where did you install Nextcloud from:**
nextcloud updater

**Login as admin user into your Nextcloud and access 
**http://example.com/index.php/settings/integrity/failed 
**paste the results here.

Result:
No errors have been found.

**List of activated apps:**

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - apporder: 0.11.0
  - bookmarks: 3.4.3
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - encryption: 2.7.0
  - external: 3.6.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_antivirus: 3.0.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trackdownloads: 1.8.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - impersonate: 1.6.1
  - keeweb: 0.6.3
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - music: 0.16.0
  - news: 14.2.2
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - onlyoffice: 6.0.2
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - radio: 0.6.6
  - rainloop: 7.0.3
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - theming_customcss: 1.6.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - user_saml: 3.2.1
  - viewer: 1.3.0
  - workflowengine: 2.1.0

**Nextcloud configuration:**

 "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "default_locale": "de_DE",
        "defaultapp": "activity, files",
        "allow_user_to_change_display_name": true,
        "skeletondirectory": "",
        "overwriteprotocol": "https",
        "htaccess.RewriteBase": "\/",
        "appcodechecker": true,
        "updater.release.channel": "stable",
        "activity_expire_days": 14,
        "maintenance": false,
        "filesystem_check_changes": 1,
        "theme": "",
        "loglevel": 2,
        "app_install_overwrite": [
            "keeweb",
            "radio"
        ],
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

Google Chrome Version 85.0.4183.121 (Offizieller Build) (64-Bit)

or

Mozilla Firefox 81.0 (64-bit)

#### Web server error log

no errors logged in testing time (empty)

#### Nextcloud log (data/nextcloud.log)

nothing logged in testing time (empty)

#### Browser log

javascript:

globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.

**Comment by nirvana88** [comment]
Had the same. App 'Radio 0.6.6' caused it. Disabled it, works fine again.

**Comment by Rhobil** [comment]
Yes thanks, I disabled it, now everything is fine again :) 👍
