### ISSUE TITLE
[NC20] Image and PDF viewer broken if Theming app is disabled

### ISSUE THREAD

**Issue by N4IR0** [nextcloud/server#23368]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Disable Theming app
2. Reload page
3. Try to open image or PDF

### Expected behaviour
A viewer with the content of the PDF or the image should be shown.

### Actual behaviour
Endless loading animation.

### Server configuration detail

**Operating system:** Linux 5.4.0-45-generic #49-Ubuntu SMP Wed Aug 26 13:38:52 UTC 2020 x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.3.25

**PHP version:** 7.4.11

Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, readline, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, cgi-fcgi, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.0 - 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**  Fresh install

**Where did you install Nextcloud from:** Docker image

<details><summary>Signing status</summary>

```
No errors have been found.
```

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.1
 - analytics: 3.0.0
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.0
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - admin_audit
 - encryption
 - theming
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "skeletondirectory": "\/var\/www\/html\/themes\/custom_theme\/skeleton",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "<full fqdn>"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.0.9",
    "overwrite.cli.url": "https:\/\/<full fqdn>",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": "6379",
        "timeout": "1.5",
        "dbindex": "0"
    },
    "filelocking.enabled": true,
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "log_type": "syslog",
    "syslog_tag": "nextcloud",
    "simpleSignUpLink.shown": false,
    "upgrade.disable-web": true,
    "updatechecker": false,
    "theme": "custom_theme"
}
```
</details>

**External storages:** files_external is disabled

**Encryption:** no

**User-backends:** 
 * OC\User\Database

### Client configuration
**Browser:** Tested with Firefox 81.0.1 and Vivaldi 3.3.2022.47

**Operating system:** Fedora 32

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No request is triggered when opening a file
```

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Since no request is triggered, no logging has been done here
```

</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Uncaught (in promise) TypeError: OCA.Theming is undefined
    updateTitle Viewer.vue:458
    n Viewer.vue:336
    l runtime.js:63
    _invoke runtime.js:293
    b runtime.js:118
    ae viewer-main.js:403
    a viewer-main.js:403
    se viewer-main.js:403
    se viewer-main.js:403
    openFile Viewer.vue:309
    file Viewer.vue:228
    VueJS 4
        run
        cr
        tt
        Xe
Viewer.vue:458
    ae viewer-main.js:403
    a viewer-main.js:403
    se viewer-main.js:403
    se viewer-main.js:403
    openFile Viewer.vue:309
    openFile self-hosted:1167
    file Viewer.vue:228
    VueJS 4
        run
        cr
        tt
        Xe
```

</details>

**Comment by kesselb** [comment]
Thanks for reporting +1

Closing in favour of nextcloud/viewer#632. Scheduled for Nextcloud 20.0.1.
