### ISSUE TITLE
Disable showing 'Login with Device' if Passwordless Authentication is not used

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#23360]
Please add the option under Admin Settings to disable "Login with Device" from the webui login page if Passwordless Authentication is not being used.  It is visually confusing for users who have no interest in webauthn.  Thanks for considering, and great work.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/b76698c547bcaf22857f8ec67a8567399520f73a/config/config.sample.php#L293-L296
