### ISSUE TITLE
Add admin UI for "trusted_domains" setting

### ISSUE THREAD

**Issue by fancycode** [nextcloud/server#2337]
### Steps to reproduce
1. Access Nextcloud using an untrusted domain.
2. The page about untrusted domain is shown, containing a button to add the domain.
3. Click the button.

### Expected behaviour
The domain should be added to the list of trusted domains.

### Actual behaviour
The IP address of the link can not be reached. From that it looks like, the first entry from the already configured trusted domains is used for that link.

Here is how that happened for me:
- During setup, the `trusted_domains` entry in `config.php` was populated from the (DHCP) IP address and hostname. The IP address was the first entry.
- I can access and use Nextcloud using my hostname just fine. The IP address has changed since the initial setup.
- When I use a different hostname to access Nextcloud, it's using the initial, no longer working IP address in the link to add the domain.

For cases like this, and if you don't have filesystem access to `config.php`, it would be nice to be able to manage the `trusted_domains` through the admin ui.

**Comment by MorrisJobke** [comment]
cc @LukasReschke

**Comment by jancborchardt** [comment]
Sounds like rather than havimg it manageable from the Admin settings UI, that button should simply work. :)

**Comment by fancycode** [comment]
Sure, that would also work - however I'm not sure how you can detect (on the server when rendering that template) which of the previously configured trusted domains can actually be reached by the client that is trying to use a non-trusted domain.

**Comment by jancborchardt** [comment]
@LukasReschke can you comment on this? :)

**Comment by MorrisJobke** [comment]
We dropped that button, because it caused just more problems than it solved and now properly link to the documentation.

#9217
