### ISSUE TITLE
ldap not responding nextcloud 20

### ISSUE THREAD

**Issue by zainadan** [nextcloud/server#23387]
hi, i just did clean installation for nexcloud 20 using nginx on ubuntu 20.04.

am trying to setup ldap but is not responding.  checking logs shows below error.

{"reqId":"OWAaRplxqWdUqyuaCD46","level":3,"time":"2020-10-12T18:06:17+02:00","remoteAddr":"172.16.0.40","user":"admin","app":"PHP","method":"GET","url":"/settings/admin/ldap","message":{"Exception":"Error","Message":"Undefined index: s02 at /var/www/nextcloud/apps/user_ldap/templates/part.wizard-server.php#10","Code":0,"Trace":[{"file":"/var/www/nextcloud/apps/user_ldap/templates/part.wizard-server.php","line":10,"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/apps/user_ldap/templates/settings.php","line":74,"args":["/var/www/nextcloud/apps/user_ldap/templates/part.wizard-server.php"],"function":"require_once"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":178,"args":["/var/www/nextcloud/apps/user_ldap/templates/settings.php"],"function":"include"},{"file":"/var/www/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Template.php","line":180,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/nextcloud/lib/public/AppFramework/Http/TemplateResponse.php","line":210,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":142,"function":"render","class":"OCP\\AppFramework\\Http\\TemplateResponse","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":83,"function":"formatSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php","line":152,"function":"getSettings","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/apps/settings/lib/Controller/AdminSettingsController.php","line":68,"function":"getIndexResponse","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"index","class":"OCA\\Settings\\Controller\\AdminSettingsController","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1009,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/nextcloud/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36","version":"20.0.0.9","id":"5f847f06c2905"}

**Comment by wavehawkca** [comment]
I have the same problem.
Cannot continue with LDAP.
The App is un-responsive.

Debian 10
Nextcloud 20
nginx
php7.4


Thanks

**Comment by gllmhyt** [comment]
Same problem on my server since the upgrade from 19.0.4 to 20.
Debian stable
PHP 7.3
Nginx 1.14.2
MariaDB 10.3.5
slapd 2.4.47

**Comment by gllmhyt** [comment]
Update: it seems like the latest Nginx configuration for Nextcloud might be the culprit of this error, as it's working with the one recommended for NC19.

**Comment by Tundra-bit** [comment]
> Update: it seems like the latest Nginx configuration for Nextcloud might be the culprit of this error, as it's working with the one recommended for NC19.

I changed my nginx config to the recommended for NC19 - LDAP now works - Thanks @gllmhyt

**Comment by ikaruswill** [comment]
+1 This issue is rather frustrating as it's difficult to pin down, however I do not have the nginx expertise nor the context to pinpoint and fix the exact configuration issue. 

Thanks for finding the issue, though it's a pity that it's garnering less attention than it should.

**Comment by szaimen** [comment]
Please make sure that you adjust your configuration correctly. https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html
Thanks!

**Comment by gllmhyt** [comment]
NC 22 and latest Nextcloud configuration does not solve the issue, this issue shouldn't be closed!
