### ISSUE TITLE
Repeated folders when shared with a group and a user belonging to such a group

### ISSUE THREAD

**Issue by floatingpurr** [nextcloud/server#23380]
### Steps to reproduce
1. Create the following directories
```
foo
|__bar
|__ other_stuff
```

2. Create `groupA`. Create `userA`. Add `userA` to `groupA`.
3. Share `foo` with `groupA` (read only)
4. Share `bar` with `groupA` (read and write)

### Expected behaviour
`userA` can see in the Web UI these dirs: 

```
foo
|__bar
|__ other_stuff
```

and she can access to all the files under `foo` and she can edit files under `bar`.

### Actual behaviour
`userA` sees in the WEB UI both `foo` and `bar` **separately**, like those were different entities.

### Server configuration

**Operating system:** ubuntu 18.04

**Web server:** the one bundled w/ the Docker image (Apache, I guess)

**Database:** Postgres

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page) 19.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by acsfer** [comment]
Use groupfolders for that. https://apps.nextcloud.com/apps/groupfolders

**Comment by floatingpurr** [comment]
This is a good idea however:

> Advanced Permissions allows entitled users to configure permissions inside groupfolders on a per file and folder basis.
> 
> Permissions are configured by setting one or more of "Read", "Write", "Create", "Delete" or "Share" permissions to "allow" or "deny". Any permission not explicitly set will inherit the permissions from the parent folder. If multiple configured advanced permissions for a single file or folder apply for a single user (such as when a user belongs to multiple groups), the "allow" permission will overwrite any "deny" permission. **Denied permissions configured for the group folder itself cannot be overwritten to "allow" permissions by the advanced permission rules.**

So if i deny write permission for `groupA` on `foo` I cannot allow it on `bar` for a `userA`.
