### ISSUE TITLE
Add new user content boxes not aligned

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#23397]
Nextcloud 20 

![image](https://user-images.githubusercontent.com/59488153/95806742-03b63080-0cce-11eb-8e13-d5427b2a4cfb.png)

**Comment by acsfer** [comment]
This is not specific to 20. Here in v19.

![image](https://user-images.githubusercontent.com/12234510/95846695-06576b00-0d4c-11eb-9739-b83a427a5c73.png)

**Comment by Dennis1993** [comment]
we should create a modal window and make the input fields one below the other. Then we have enough space and a better UI. The current style is not very user friendly.

Whats your opinion?

**Comment by axheli** [comment]
> we should create a modal window and make the input fields one below the other. Then we have enough space and a better UI. The current style is not very user friendly.
> 
> 
> 
> Whats your opinion?

Yes, the modal windows sounds like an amazing idea. Love it

**Comment by Simounet** [comment]
Hi there,
Just a quick message to let you know that I'm working on a solution with the `<Modal>` component. I'll try to upload some screenshots here to get feedback even if it will be quite simple.

**Comment by axheli** [comment]
> Hi there,
> 
> Just a quick message to let you know that I'm working on a solution with the `<Modal>` component. I'll try to upload some screenshots here to get feedback even if it will be quite simple.

Sick!!!

**Comment by Simounet** [comment]
I made a PR #23529 but there is some details to fix anyway. At least, you can see the screenshot with the simple result.

**Comment by Dennis1993** [comment]
that looks very good! I would make it a bit wider, but otherwise it's great! Good work!
Thanks!

**Comment by axheli** [comment]
@Simounet nice job looks really good I love it. 

If I may add, I think the display name should be first then username password etc.

**Comment by Simounet** [comment]
Why not. I'll check where the order come from.

**Comment by axheli** [comment]
@Simounet you're the best thank you! :)
