### ISSUE TITLE
translation problem

### ISSUE THREAD

**Issue by arily** [nextcloud/server#2339]
### Steps to reproduce
1.there has a typo in Chinese translation
2.means "You don't have permission to upload or crate files" at the right of the path
3.

### Expected behaviour
it should be 您没有权限来上传或者创建文件

### Actual behaviour
湖州哦 is a typo

**Comment by arily** [comment]
![d91f7d8c-286b-4c18-9a45-74f4f1ef5b8e](https://cloud.githubusercontent.com/assets/10007589/20629747/751530e8-b370-11e6-99c2-074bcee4253d.png)

**Comment by MariusBluem** [comment]
Thank you for your report ✊ ...Translation problems should be reported and fixed over Transifex: 
https://www.transifex.com/nextcloud/

**Comment by chiyi4488** [comment]
湖州是啥!!:D哈哈
我是完全沒法顯示中文(兩三詞):D
