### ISSUE TITLE
Translation for "All checks passed." wrong in de_DE

### ISSUE THREAD

**Issue by ekric** [nextcloud/server#234]
### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status (Nextcloud 9.0 and above):**

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### Nextcloud log (data/owncloud.log)
```
Insert your Nextcloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by ekric** [comment]
./settings/l10n/de_DE.json:129:    "All checks passed." : "Alle checks erfolgreich gepfüft.",
./settings/l10n/de_DE.js:131:    "All checks passed." : "Alle checks erfolgreich gepfüft.",

Should be:
./settings/l10n/de_DE.json:129:    "All checks passed." : "Alle checks erfolgreich geprüft.",
./settings/l10n/de_DE.js:131:    "All checks passed." : "Alle checks erfolgreich geprüft.",

**Comment by ungesundes-halbwissen** [comment]
While at it: "alle checks ...geprüft" does not sound too nice. How about one of the latter:

- Alle Bedingungen erfolgreich geprüft
- Alle Voraussetzungen erfolgreich geprüft
- Alle Prüfungen (waren) erfolgreich
- Alle Tests (waren) erfolgreich

**Comment by ekric** [comment]
I like: "Alle Tests waren erfolgreich" the best

**Comment by ekric** [comment]
Of course with "." in the end.

**Comment by rullzer** [comment]
Please join the translation team on https://www.transifex.com/nextcloud

**Comment by ungesundes-halbwissen** [comment]
Translations are done. Thanks for your patience!
