### ISSUE TITLE
Buttons and inputs font sizes

### ISSUE THREAD

**Issue by marcoambrosini** [nextcloud/server#23407]
@ma12-co buttons and inputs still seem to be force set to font-size: 13px per core css. Can you look into that?

_Originally posted by @jancborchardt in https://github.com/nextcloud/server/pull/23226#issuecomment-706223689_

**Comment by Zhoha28** [comment]
Has this issue been solved yet, if not can you please assign it to me, I would like to work on this issue?

**Comment by ma12-co** [comment]
Hi @Zhoha28, sure! And thanks :)

**Comment by blizzz** [comment]
seems to be resolved meanhwile i hear
