### ISSUE TITLE
Double scroll bar with long activity list

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#23406]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have a file
2. Change it regularly and often
3. Scroll the list

### Expected behaviour
There is 1 scroll bar

### Actual behaviour
There is a double scroll bar

![Bildschirmfoto von 2020-10-13 09-29-12](https://user-images.githubusercontent.com/213943/95829682-d8b3f700-0d36-11eb-9153-502bc2e11f2e.png)

### Server configuration

**Nextcloud version:** 20.0.0

Currently the talk app is already hacking the sidebar to circumvent this and I think it's time to fix this in the files app instead. all sidebar tabs should be height limited and then scroll only there and the file list should have its scroll bar next to it and not disconnected after a sidebar.

cc @danxuliu @skjnldsv @juliushaertl

**Comment by skjnldsv** [comment]
> ### Expected behaviour
> There is 1 scroll bar
> 
> ### Actual behaviour
> There is a double scroll bar

Well, there are two elements that can scroll, there will always be two scrollbars.
How else do you want it to be? Not scollable in the AppSidebar? How do we display more items?

**Comment by skjnldsv** [comment]
> and the file list should have its scroll bar next to it and not disconnected after a sidebar.

This will not happen.
The whole nextcloud is scrolling, not just the inner files. This created tons of issues before.
That is how all websites are doing it, let's stop hacking and use standard html/css implementations.

**Comment by skjnldsv** [comment]
![Capture d’écran_2020-10-17_16-58-15](https://user-images.githubusercontent.com/14975046/96347167-2c5c7280-10a0-11eb-9397-a0a2b41c36ac.png)
Google example.
