### ISSUE TITLE
Translations missing from daily packages and final releases?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#23408]
the daily master tar ball is missing translation files/folders in:
admin_audit, cloud_federation_api, contactsinteraction, dashboard, user_status, weather_status

Also I have empty `l10n` folders for those apps in my instance after installing 20.0.0 from github.

**Comment by MorrisJobke** [comment]
> Also I have empty `l10n` folders for those apps in my instance after installing 20.0.0 from github.

That is because 20.0.0 didn't had any translations: https://github.com/nextcloud/server/tree/v20.0.0/apps/admin_audit/l10n

**Comment by MorrisJobke** [comment]
Somehow the latest container image didn't made it to the transifex sync machine. I will check that again. Then stable20 should also have all the translations.

**Comment by MorrisJobke** [comment]
Ah ... it ran into the PHP 7.3 requirement we have on master 🚀

**Comment by MorrisJobke** [comment]
And there they are: https://github.com/nextcloud/server/tree/stable20/apps/admin_audit/l10n
