### ISSUE TITLE
La actualización ha fallado

### ISSUE THREAD

**Issue by ngarcesv** [nextcloud/server#23414]
He actualizado la verión del Nextcloud 19.0.3 a la 20.0.0.

Al momento de actualizar me salta el siguiente error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_user_status (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, status_timestamp INT UNSIGNED NOT NULL, is_user_defined TINYINT(1) NOT NULL, message_id VARCHAR(255) DEFAULT NULL, custom_icon VARCHAR(255) DEFAULT NULL, custom_message LONGTEXT DEFAULT NULL, clear_at INT UNSIGNED DEFAULT NULL, UNIQUE INDEX user_status_uid_ix (user_id), INDEX user_status_clr_ix (clear_at), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
