### ISSUE TITLE
[Theming] Add more fields for Titles/names

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#23418]
**Is your feature request related to a problem? Please describe.**
In theming app there is only one field for typing server name. This name will be used everywhere (server name, sender name for emails, in title etc). In the same time in themes/<your_theme>/default.php administrator can manage, which name where will be used. 
Using theming app you cannot set 2+ words `name` field, because this value will be used as name of email sender. 

**Describe the solution you'd like**
Add more fields like Title, HTMLName

**Comment by krakazyabra** [comment]
One of alternatives - use `'mail_from_address' => '<name>',` in config.php

**Comment by szaimen** [comment]
krakazyabra mentioned a solution to this.
