### ISSUE TITLE
Notification Sync server <-> Client

### ISSUE THREAD

**Issue by vacy** [nextcloud/server#23447]
**Is your feature request related to a problem? Please describe.**
I am somehow reluctant to swiping away all the calender notifications you get on each device.
Its like having a bad monitoring system with too many meaningless alerts, you get kinda blind for the important.

**Describe the solution you'd like**
I don't think WebDAV offers  solution to this, i am quite sure it does not offer.
Ideal would be if each device could sync the response to the notification to the server so other devices copy the action on their Interface. Like you swipe a notification to disappear, the other systems shall be informed to make it happen as well.

**Describe alternatives you've considered**
I think not even Microsoft AD can do it. But it would be a killer feature.

**Additional context**
Just thoughts... what do you guys think?

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Subscribe to receive notifications on status change and new comments.

**Comment by szaimen** [comment]
I think nextclouds notifications are synced between different devices in the meantime.
