### ISSUE TITLE
Link to 'Developer documentation' doesn't work on Apps page

### ISSUE THREAD

**Issue by siccovansas** [nextcloud/server#23441]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade to Nextcloud 20
2. Go to Apps page
3. Click on 'Developer documentation' link at the bottom  of the navigation pane on the left

### Expected behaviour
You should go the developer documentation website (I think https://docs.nextcloud.com/server/20/developer_manual/)

### Actual behaviour
Nothing happens as the `href` for the link is `#`

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Nginx 1.19.3

**Database:** Postgresql 12.4

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19

**Where did you install Nextcloud from:** -

### Client configuration
**Browser:** Firefox 81.0 and Chromium 85.0.4183.121

**Operating system:** Ubuntu 18.04

**Comment by mrtnmtth** [comment]
Also affects Nextcloud version 19.0.4

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

**Comment by siccovansas** [comment]
I just checked and this is still an issue on Nextcloud 23.0.2.

It is quite an ugly bug as the dead link is on a prominent location and I guess many people will click on it only to see nothing happen.

I guess this is a really easy fix for someone who knows the Nextcloud codebase (I tried, but couldn't figure it out as I'm not familiar with the codebase). Something for you @szaimen or would you recommend another dev?

![Nextcloud developer documentation bug](https://user-images.githubusercontent.com/696839/155724857-27e34f4b-bdb1-4f22-b418-1fd838b22d0d.png)
