### ISSUE TITLE
JS FileInfo regressions, breaks file list sidebar tabs

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#23445]
### Steps to reproduce

1. Setup NC from master (2b36842e137e66655f78e99a1e2635c5c9651e37)
1. Enable spreed app from master
1. Create a file
1. Share it with other people
1. Open the sidebar for that file
1. Click on "Versions"
1. Click on "Talk"

### Expected result
Versions tab loads correctly.
Talk tab exists.

### Actual result
JS issues:
```
Tab.js:52 Uncaught Error: The id argument is not a valid string
    at new e (Tab.js:52)
    at mainFilesSidebarLoader.js:49
```
Versions tab spinner stays, JS error:
```
versioncollection.js:61 Uncaught (in promise) TypeError: this._fileInfo.getFullPath is not a function
    at i.parse (versioncollection.js:61)
    at i.set (backbone.js:839)
    at Object.e.success (backbone.js:1059)
    at backbone-webdav.js:174
```

Talk tab does not appear at all!

### Versions
NC 21.0.0 alpha git master 2b36842e137e66655f78e99a1e2635c5c9651e37
Talk app git master acaf9aac3fec3b9e99c2a1e685127470501ee74d

### Analysis

It seems that the `FileInfo` object passed in for the versions is of the wrong class OC.Files.FileInfo as it doesn't have `getFullPath()`. The correct object should be of type OCA.Files.FileInfoModel

@skjnldsv I heard you might have an idea or have touched this bit recently ?
(happy to help with the analysis if needed)

**Comment by skjnldsv** [comment]
> Talk tab does not appear at all!

https://github.com/nextcloud/spreed/pull/4291

**Comment by skjnldsv** [comment]
Versions needs a fix, Roeland was working on migrating it to vue :)

**Comment by skjnldsv** [comment]
Fixed on https://github.com/nextcloud/server/commit/9172b9ad206efa766cefec4e5c1db63fc9190432
I stupidly thought I was on another branch and pushed master...

Should not have worked today ^^'
