### ISSUE TITLE
Link to GitHub issue tracker is broken on Nextcloud support page

### ISSUE THREAD

**Issue by stefan-it** [nextcloud/server#2344]
Link to the GitHub issue tracker is broken on the NextCloud support page:

### Steps to reproduce
1. Go to `https://nextcloud.com/support/`
2. Click on the *bug trackers* link

### Expected behaviour
Redirect should point to [GitHub issue page](https://github.com/nextcloud/server/issues)

### Actual behaviour
Link is broken - it will point to `https://github.com/nextcloud/server/blob/master/.github/CONTRIBUTING.md` and this leads to an 404 error.

**Comment by MariusBluem** [comment]
Thank you for your report 😁 But this is the repo for the server, and not the website (nextcloud.com). You will find it's issue tracker over here: https://github.com/nextcloud/nextcloud.com

I'll take care of fixing it ✊
