### ISSUE TITLE
No longer able to sync files on mobile app after update up 20.0.0

### ISSUE THREAD

**Issue by mbh-dev** [nextcloud/server#23449]
Hi,

Following the update from 19 to 20, we can no longer access our files via the Nextcloud mobile app on Android.

The latest versions are installed on both server and mobile. We can login fine on the mobile app, just no files are shown.

Files sync and are accessible via browser and Windows application, just seen issue with mobile.

Could anyone shed any light on the situation?

Many thanks

**Comment by kesselb** [comment]
Hey,

please ask such questions at https://help.nextcloud.com and try to figure out what's wrong. If they tell you to report a bug on GitHub come back and use the issue template: https://github.com/nextcloud/server/issues/new?labels=bug%2C+0.+Needs+triage&template=Bug_report.md

Thanks :+1:

**Comment by mbh-dev** [comment]
Unfortunately I'm not getting a response from anyone in the discord, I consider this a major bug that needs addressing. Thank you
