### ISSUE TITLE
Calendar invites: Sender is server instance, not user email address

### ISSUE THREAD

**Issue by gqgunhed** [nextcloud/server#2345]
### Steps to reproduce
1. Create calendar entry and add attendees with email addresses
2. Submit/Save entry to calendar, invites are being sent to attendees (as expected BUT ...) 
3. Emails are always sent with "from: nextcloud@internal.domain", not from "user@internal.domain"

### Expected behaviour
Invites should be sent using the email address of the user (provided by user profile) creating the calendar entry. Using a central email makes responding, filtering, etc. impossible.
(internal domain is being converted when transmitted to the outside world, so no worries about that)

### Actual behaviour
All invites are being sent with "from: nextcloud@internal.domain" which is the central notification email set via Administration -> Additional Settings -> Email -> Using SMTP

### Server configuration
**Operating system**: FreeBSD 10.3

**Web server:** nginx-1.10.1_1,2

**Database:** mysql 5.6.33

**PHP version:** PHP5.6.27

**Server version:** (see your admin page) 10.0.1

**Calendar version:** (see the apps page) 1.4.1

**Updated from an older installed version or fresh install:** Update

**Signing status (ownCloud/Nextcloud 9.0 and above):** ?

```
Login as admin user into your cloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
No errors have been found.

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your instance's installation folder
```
root@nextcloud:/usr/local/www/nextcloud # su -m www -c "php occ app:list"
The process control (PCNTL) extensions are required in case you want to interrupt long running commands - see http://php.net/manual/en/book.pcntl.php
Enabled:                                                                                                               
  - activity: 2.3.2                                                                                                    
  - admin_audit: 1.0.0                                                                                                 
  - audioplayer: 1.3.1                                                                                                 
  - bookmarks: 0.9.0                                                                                                   
  - calendar: true                                                                                                     
  - comments: 1.0.0                                                                                                    
  - contacts: 1.5.2                                                                                                    
  - dav: 1.0.1                                                                                                         
  - direct_menu: 0.9.3                                                                                                 
  - documents: 0.13.1                                                                                                  
  - federatedfilesharing: 1.0.1                                                                                        
  - federation: 1.0.1                                                                                                  
  - files: 1.5.2                                                                                                       
  - files_external: 1.0.2                                                                                              
  - files_pdfviewer: 0.8.1                                                                                             
  - files_sharing: 1.0.0                                                                                               
  - files_texteditor: 2.1                                                                                              
  - files_trashbin: 1.0.0                                                                                              
  - files_versions: 1.3.0                                                                                              
  - files_videoplayer: 0.9.8                                                                                           
  - firstrunwizard: 1.1                                                                                                
  - gallery: 15.0.0                                                                                                    
  - mail: 0.6.0                                                                                                        
  - news: 9.0.4                                                                                                        
  - notifications: 0.3.0                                                                                               
  - password_policy: 1.0.0                                                                                             
  - provisioning_api: 1.0.0                                                                                            
  - serverinfo: 1.1.1                                                                                                  
  - survey_client: 0.1.5                                                                                               
  - systemtags: 1.0.2                                                                                                  
  - templateeditor: 0.1                                                                                                
  - theming: 1.0.1                                                                                                     
  - updatenotification: 1.0.1                                                                                          
  - workflowengine: 1.0.1                                                                                              
Disabled:                                                                                                              
  - encryption                                                                                                         
  - external                                                                                                           
  - files_accesscontrol                                                                                                
  - files_automatedtagging                                                                                             
  - files_retention                                                                                                    
  - ojsxc                                                                                                              
  - roundcube                                                                                                          
  - user_external                                                                                                      
  - user_ldap                                                                                                          
  - user_saml                                                                                                          

**The content of config/config.php:**

root@nextcloud:/usr/local/www/nextcloud # cat config/config.php  
```
<?php                                                            
$CONFIG = array (                                                
  'instanceid' => 'instanceid_here',                                
  'passwordsalt' => 'passwordsalt_here',            
  'secret' => 'secret_here',
  'trusted_domains' =>                                           
  array (                                                        
    0 => 'nextcloud.internal.domain,                             
  ),                                                             
  'datadirectory' => '/usr/local/www/nextcloud/data',                                
  'overwriteprotocol' => 'https',                                                    
  'overwrite.cli.url' => 'https://nextcloud..internal.domain',                         
  'dbtype' => 'mysql',                                                               
  'version' => '9.1.1.5',                                                            
  'dbname' => 'nextcloud',                                                           
  'dbhost' => 'db.internal.domain',                                                   
  'dbtableprefix' => 'oc_',                                                          
  'dbuser' => 'db_user_here',                                                           
  'dbpassword' => 'dbpassword_here',                                                    
  'logtimezone' => 'UTC',                                                            
  'installed' => true,                                                               
  'mail_smtpmode' => 'smtp',                                                         
  'mail_from_address' => 'nextcloud',                                                
  'mail_domain' => 'internal.domain',                                                 
  'mail_smtphost' => 'mail.internal.domain',                                          
  'mail_smtpport' => '25',                                                           
  'trashbin_retention_obligation' => 'auto, 30',                                     
  'versions_retention_obligation' => 'auto, 90',                                     
  'loglevel' => 2,                                                                   
  'maintenance' => false,                                                            
  'theme' => '',                                                                     
  'updater.secret' => 'updater_secret_hash',
  'appstoreenabled' => true,                                                         
  'appstoreurl' => 'https://apps.nextcloud.com/api/v0',                              
  'appstore.experimental.enabled' => false,                                          
  'apps_paths' =>                                                                    
  array (                                                                            
    0 =>                                                                             
    array (                                                                          
      'path' => '/usr/local/www/nextcloud/apps',                                     
      'url' => '/apps',                                                              
      'writable' => true,                                                            
    ),                                                                               
  ),                                                                                 
  'enabledPreviewProviders' =>                                                       
  array (                                                                            
    0 => 'OC\\Preview\\PNG',                                                         
    1 => 'OC\\Preview\\JPEG',                                                        
    2 => 'OC\\Preview\\GIF',                                                         
    3 => 'OC\\Preview\\BMP',                                                         
    4 => 'OC\\Preview\\XBitmap',                                                     
    5 => 'OC\\Preview\\MarkDown',                                                    
    6 => 'OC\\Preview\\MP3',                                                         
    7 => 'OC\\Preview\\TXT',                                                         
    8 => 'OC\\Preview\\Movie',                                                       
  ),                                                                                 
  'filelocking.enabled' => 'true',                                                   
  'memcache.locking' => '\\OC\\Memcache\\Redis',                                     
  'memcache.local' => '\\OC\\Memcache\\APCu',                                        
  'redis' =>                                                                         
  array (                                                                            
    'host' => '/var/run/redis/redis.sock',                                           
    'port' => 0,                                                                     
  ),                                                                                 
);  
```                                                                                 

**Are you using external storage, if yes which one:** local/smb/sftp/...
smb

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:** Firefox/Chrome both current

**Operating system:** Linux/Windows/FreeBSD

**CalDAV-clients:** web-interface of nextcloud

**Comment by nickvergessen** [comment]
> All invites are being sent with "from: nextcloud@internal.domain" which is the central notification email set via Administration -> Additional Settings -> Email -> Using SMTP

This is actually the expected thing, because not all SMTP connections are allowed to use a different sender address than their own.

However we set the "Reply-To" header, so you should be able to organize based on that.
Also replying/responding is not a problem at all. Works just fine.

**Comment by gqgunhed** [comment]
Ok, I see. Have not looked at the Reply-To Field. Thanks for pointing that out.
/var/log/maillog just shows the From: field.

**Comment by tuergeist** [comment]
Re-Opening the issue. It would be great if you leave it to the admin to decide how it shall work. I actually use NextClound+Calendar for different domains; in that case it's somehow annoying to have to chose one special email address for everybody (also for users with different domain names).

**Comment by georgehrke** [comment]
https://github.com/nextcloud/server/pull/5304 will make it possible to opt-out of server-side scheduling.

**Comment by zyro23** [comment]
@georgehrke does it? #5304 looks like it fixes handling past events but not like it introduces a way to disable server-side invitation mail sending completely?

**Comment by georgehrke** [comment]
No, it's not included. I removed it upon request from Morris and Lukas. Will open a dedicated PR for it
