### ISSUE TITLE
Update from 17.0.10 to 18.0.10 failed

### ISSUE THREAD

**Issue by LeGeek01** [nextcloud/server#23457]
Hello, I am coming to you because the update from NextCloud 17.0.10 to 18.0.10 failed with the error: InvalidArgumentException: Column name "oc_flow_operations". "Entity" is NotNull, but has empty string or null as default.
It is marked that you must report this bug, that's what I'm doing now.
How to solve this?
Thanks in advance.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favour of https://github.com/nextcloud/server/issues/23174.
