### ISSUE TITLE
"Step 4 is currently in process. Please reload this page later." --> since a week

### ISSUE THREAD

**Issue by Mannshoch** [nextcloud/server#23454]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Start Updater
2. after a while "Step 4 is currently in process. Please reload this page later." appear

### Expected behaviour
I don see that this update need a whole week. 
- please advice me what I have to do
- I miss information in documentation what I have to do.
- If I reoad the page or open the update again the Information have to change

### Actual behaviour
only "Step 4 is currently in process. Please reload this page later." appear if I open the updater.
The cloud works without problem

### Server configuration

**Operating system:** Linux 3.10.0-1127.18.2.el7.x86_64 #1 SMP Sun Jul 26 15:27:06 UTC 2020 x86_64

**Webserver:** Apache (cgi-fcgi)

**Database:** mysql 10.2.33

**PHP version:** 7.2.34

**Modules loaded:** Core, date, libxml, openssl, pcre, zlib, filter, hash, pcntl, readline, Reflection, SPL, session, standard, cgi-fcgi, bcmath, bz2, calendar, ctype, curl, dba, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imap, intl, json, ldap, exif, mysqlnd, odbc, PDO, Phar, posix, pspell, shmop, SimpleXML, soap, sockets, sodium, sqlite3, sysvmsg, sysvsem, sysvshm, tidy, tokenizer, xml, xmlwriter, xsl, mysqli, pdo_mysql, PDO_ODBC, pdo_sqlite, wddx, xmlreader, xmlrpc, igbinary, imagick, msgpack, zip, redis, ionCube Loader, Zend OPcache

**Nextcloud version:** 18.0.7 - 18.0.7.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** ZIP file

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "trusted_domains": [
        "***REMOVED SENSITIVE VALUE***",
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "18.0.7.1",
    "logtimezone": "Europe\/Berlin",
    "logdateformat": "Y.m.d, H:i:s",
    "log_query": false,
    "logfile": "***REMOVED SENSITIVE VALUE***\/nextcloud.log",
    "loglevel": 0,
    "syslog_tag": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "default_language": "de",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtpauthtype": "LOGIN",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "skeletondirectory": "\***REMOVED SENSITIVE VALUE***\/skeleton",
    "user_backends": [
        {
            "class": "OC_User_IMAP",
            "arguments": [
                "***REMOVED SENSITIVE VALUE***",
                993,
                "ssl",
                "***REMOVED SENSITIVE VALUE***",
                false,
                false
            ]
        }
    ],
    "debug": false,
    "theme": "",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "updater.release.channel": "stable",
    "0": [
        "occweb"
    ],
    "mysql.utf8mb4": true,
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}

```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** mail

### Client configuration
**Browser:** Firefox

**Operating system:** Ubuntu

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by Mannshoch** [comment]
Hi @kesselb 
I don't see a Setup issue for help.nextcloud.com . In my opinian there seems a lack of comunicating and Error handling if something went wrong in the setup proccess. The solution here, was simply to remove the step file in the /data/updater-xxxxxx/ directory. 
The update did after that run again from start without any problems.

**Comment by Mannshoch** [comment]
Hi @kesselb 
Please tell me, did I miss something? Why do you think that his is not a Problem? I do no't understand in any kind why you closed this issue.

**Comment by Mannshoch** [comment]
@kesselb  Hello please clarify your position!

**Comment by Mannshoch** [comment]
Hi @kesselb I wish an Explanation!

**Comment by Mannshoch** [comment]
Ping

**Comment by kesselb** [comment]
Hey @Mannshoch,

> In my opinian there seems a lack of comunicating and Error handling if something went wrong in the setup proccess. The solution here, was simply to remove the step file in the /data/updater-xxxxxx/ directory.

Sounds good to me. https://github.com/nextcloud/updater is the repository for the updater component. Please create a enhancement issue over there. 

> The update did after that run again from start without any problems.

It depends at which stage the updater crashed. At least we should give the user more insights what's going on.

**Comment by Mannshoch** [comment]
Thank you very much @kesselb for your answer. I will create a new issue at the correct repository.
