### ISSUE TITLE
Guzzle Error!

### ISSUE THREAD

**Issue by yezz123** [nextcloud/server#23455]
I am try to share existing file on `NextCloud` server. This is not my server, i have only access to account and API. `NextCloud `server version 19.0.2.
I am using new API without examples:
https://docs.nextcloud.com/server/stable/developer_manual/client_apis/OCS/ocs-share-api.html#create-a-new-share 
And old API with examples:
https://doc.owncloud.com/server/developer_manual/core/apis/ocs-share-api.html#create-a-new-share.
After this request i recived statusCode 200 (it must be 100, 400, 403 or 404 on API documentation ) and file is not shared.

**Comment by kesselb** [comment]
https://help.nextcloud.com/c/dev/11 for such questions.
