### ISSUE TITLE
Give names to versions

### ISSUE THREAD

**Issue by strassan** [nextcloud/server#23460]
I would like to request a feature to be able to give names to older versions of your files.

# Current behaviour
Versions of a file are named by the number of days they were created ago ("X days ago"). Especially when there is more than one version a day, this is not really helpful.

# Requested behaviour
I would like to be able to have the option to give a verbose name to the file (e.g. "v1.2")

## What I will use it for
The band I play in uses Nextcloud to organize guitar tabs of our songs (and a lot of other stuff). When someone uploads a new guitar riff idea, the riff is usually altered by other members a few times, before it reaches its final form in a song. Instead of having 5 different files of almost the same riff, I would like to use the versioning feature for this and give the versions a verbose name, like e.g. the person who did the last changes to the riff.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
