### ISSUE TITLE
Write access to external SMB folders with flag "Read-Only" not possible

### ISSUE THREAD

**Issue by samanyu7** [nextcloud/server#23462]
After an upgrade from nextcloud18 to version 19.0.3 it is no longer possible to save files in SMB directories (external storage) flagged with the "Read-Only" DOS attribute.

Even though this sounds like expected behaviour, it actually is a bug and should be changed.

 
> Unlike the Read-only attribute for a file, the Read-only attribute for a folder is typically ignored by Windows, Windows components and accessories, and other programs. For example, you can delete, rename, and change a folder with the Read-only attribute by using Windows Explorer.

Reference: http://support.microsoft.com/kb/326549

 
**Affected Nextcloud version:** 19.0.3, 19.0.4, 20.0.0

**Comment by CinMike** [comment]
If anyone is awaiting a fix, I did a dirty fix by altering the following as I was desperate in SMB.php (No guarantees it doesnt destroy your Nextcloud etc etc):

```
private function getMetaDataFromFileInfo(IFileInfo $fileInfo) {
		$permissions = Constants::PERMISSION_READ + Constants::PERMISSION_SHARE;

		if (!$fileInfo->isReadOnly()) {
			$permissions += Constants::PERMISSION_DELETE;
			$permissions += Constants::PERMISSION_UPDATE;
			if ($fileInfo->isDirectory()) {
				$permissions += Constants::PERMISSION_CREATE;
			}
		}
```

to

`private function getMetaDataFromFileInfo(IFileInfo $fileInfo) {
		$permissions = Constants::PERMISSION_READ + Constants::PERMISSION_SHARE;

		if (!$fileInfo->isReadOnly()) {
			$permissions += Constants::PERMISSION_DELETE;
			$permissions += Constants::PERMISSION_UPDATE;
		}
                if ($fileInfo->isDirectory()) {
                        $permissions += Constants::PERMISSION_DELETE;
			$permissions += Constants::PERMISSION_UPDATE;
			$permissions += Constants::PERMISSION_CREATE;
		}`

**Comment by samanyu7** [comment]
@CinMike  Thanks for your code snippet to provide a possible fix. It actually works in terms of restoring the ability to save files in directories with a ReadOnly attribute.

However there are some negative impacts with this solution. In directories that are _really_ write-protected to the user, Nextcloud won't show it in a message althoug the actual write operation fails. A better fix would be to make changes to the fileInfo->isReadOnly() method and treat the ReadOnly attribute differently there.


Please accept this post as a valid bug report and take care of an improvement. We have many customers affected by this problem.

**Comment by CinMike** [comment]
Update to my previous post:

Change /apps/files_external/3rdparty/icewind/smb/src/Native/NativeFileInfo.php

`public function isReadOnly() {
                $mode = $this->getMode();
                if ($mode > 0x1000) {
                        return !(bool)($mode & 0x80); // 0x80: owner write permissions
                } else {
                        return (bool)($mode & IFileInfo::MODE_READONLY);
                }
        }`

to

`public function isReadOnly() {
                $mode = $this->getMode();
                if ($this->isDirectory()) {
                        return false;
                } elseif ($mode > 0x1000) {
                        return !(bool)($mode & 0x80); // 0x80: owner write permissions
                } else {
                        return (bool)($mode & IFileInfo::MODE_READONLY);
                }
        }`

**Comment by blizzz** [comment]
You (those affcted) might want to test https://github.com/nextcloud/server/pull/26292
