### ISSUE TITLE
Sharing tab is missing after update to nextcloud 20

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#23461]
### Steps to reproduce
1. Update to nextcloud 20 (or fresh install)
2. Click "share" icon (before 3 dots for file context menu)

### Expected behaviour
Share tab should be show in sidebar

### Actual behaviour
No tab and errors in console like 
`TypeError: e.$refs.sidebar.updateTabs is not a function`  
`Ignoring invalid tab Object { tag: "vue-component-5-SharingTab", data: {…`  
`TypeError: n.$refs.sidebar.updateTabs is not a function`

### Server configuration

**Nextcloud version:** 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Checked in updated and fresh too (with default config)

**Where did you install Nextcloud from:** docker image

**Comment by kesselb** [comment]
cc @nextcloud/javascript

**Comment by ChristophWurst** [comment]
Dup of https://github.com/nextcloud/server/issues/23356

**Comment by mikpotik** [comment]
I have the same problem with Nextcloud 20.0.0. But if you select English in the settings of your profile, everything works.
