### ISSUE TITLE
Nothing appears in Available To field of SMB share in Settings

### ISSUE THREAD

**Issue by HammyHavoc** [nextcloud/server#23465]
### Steps to reproduce
Click the Available To field on an SMB share, or try typing in the name of a group.

### Expected behaviour
To suggest names of Groups and actually function when you type one in manually.

### Actual behaviour
Blank, nothing saved, despite multiple groups. External Storage ends up showing up for all users as Available To functionality won't work.

![image](https://user-images.githubusercontent.com/503951/96104755-1cdaff00-0ed1-11eb-9f63-ce41afc51ea1.png)

![image](https://user-images.githubusercontent.com/503951/96104655-03d24e00-0ed1-11eb-8763-f3ce86841d9e.png)

## Server configuration detail

**Operating system:** Linux 4.19.107-Unraid #1 SMP Thu Mar 5 13:55:57 PST 2020 x86_64

**Webserver:** nginx/1.18.0 (fpm-fcgi)

**Database:** mysql 10.4.15

**PHP version:** 

7.3.23
Modules loaded: Core, date, libxml, pcre, zlib, filter, hash, readline, Reflection, SPL, session, cgi-fcgi, bcmath, bz2, ctype, curl, dom, fileinfo, ftp, gd, gmp, iconv, intl, json, ldap, mbstring, openssl, pcntl, PDO, pgsql, posix, standard, SimpleXML, smbclient, sodium, sqlite3, xml, xmlwriter, zip, exif, imap, mysqlnd, pdo_pgsql, pdo_sqlite, Phar, xmlreader, pdo_mysql, apcu, igbinary, redis, memcached, imagick, mcrypt, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.0 - 20.0.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:** 

No. Fresh.

**Where did you install Nextcloud from:** Official Docker

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.1
 - admin_audit: 1.10.0
 - analytics: 3.0.0
 - announcementcenter: 4.0.0
 - apporder: 0.11.0
 - audioplayer: 2.12.0
 - audioplayer_editor: 0.3.0
 - audioplayer_sonos: 1.2.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - circles: 0.20.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - data_request: 1.7.0
 - dav: 1.16.0
 - deck: 1.1.2
 - duplicatefinder: 0.0.2
 - event_update_notification: 1.1.0
 - external: 3.7.1
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_accesscontrol: 1.10.0
 - files_automatedtagging: 1.10.0
 - files_downloadactivity: 1.9.0
 - files_external: 1.11.1
 - files_linkeditor: 1.1.2
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - flow_notifications: 1.0.1
 - groupfolders: 8.1.0
 - groupquota: 0.1.4
 - imageconverter: 1.2.1
 - impersonate: 1.7.0
 - integration_github: 0.0.6
 - integration_gitlab: 0.0.5
 - integration_mastodon: 0.0.5
 - integration_reddit: 0.0.4
 - integration_twitter: 0.0.4
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.5.0
 - metadata: 0.12.0
 - news: 15.0.4
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - occweb: 0.0.7
 - password_policy: 1.10.1
 - photos: 1.2.0
 - previewgenerator: 3.0.1
 - printer: 0.0.3
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - recommendations: 0.8.0
 - richdocuments: 3.7.5
 - richdocumentscode: 4.2.800
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - social: 0.4.0
 - socialsharing_diaspora: 2.1.0
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - socialsharing_twitter: 2.1.0
 - spreed: 10.0.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - talk_matterbridge: 1.18.3
 - talk_simple_poll: 1.2.0
 - tasks: 0.13.4
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_nextcloud_notification: 3.0.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.0
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflow_ocr: 1.20.0
 - workflow_pdf_converter: 1.5.0
 - workflow_script: 1.5.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.splitanatom.com"
    ],
    "dbtype": "mysql",
    "version": "20.0.0.9",
    "overwrite.cli.url": "https:\/\/cloud.splitanatom.com",
    "overwritehost": "cloud.splitanatom.com",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "mail_smtpmode": "smtp",
    "mail_smtpsecure": "tls",
    "mail_sendmailmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "app_install_overwrite": [
        "occweb",
        "printer",
        "social",
        "camerarawpreviews"
    ],
    "maintenance": false
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB
**Are you using encryption:** 
No, still figuring out if Nextcloud is suitable/reliable.
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No
## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36 Edg/86.0.622.38

**Operating system:** Windows 10 Pro for Workstations

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by kesselb** [comment]
- Go to https://github.com/nextcloud/server/issues
- Click FAQ issue
- Check list of known issues
