### ISSUE TITLE
Create API for dashboard-backgroundimage

### ISSUE THREAD

**Issue by newhinton** [nextcloud/server#23476]
The new Dashboard could expose an simple api to allow thirdparty apps to provide background images for it.

@juliushaertl

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by newhinton** [comment]
@szaimen Has this been implemented? Since Hub 3 will make even more use of the background, we should probably have an api for that.

I would preferrably have a "use unsplash" button that then allows me to add custom css everywhere, basically a way to tell unsplash it is now allowed to set the background. I am currently abusing `$this->config->getUserValue($this->userId, "theming", 'background', 'default');` to find out if i should add the image.
