### ISSUE TITLE
Error creating user: Bad request

### ISSUE THREAD

**Issue by LeGeek01** [nextcloud/server#23485]
Hello everyone again,
This time I come to you because the user creation fails, with the error: Bad Request.
I recently updated NextCloud from 15.0.10 to 19.0.4, through 17.0.10 and 18.0.10.

This problem happened 1 month after installing 15.0.10, so I tried to do the updates to see if that fixed the problem.

How to fix this?
Thank you in advance.

**Comment by LeGeek01** [comment]
Hello @acsfer,
what information are you missing?
Cordially.

**Comment by acsfer** [comment]
Well, the whole template when you open the issue...
Nobody in this world will help you with a message like "Bad request". :)

**Comment by LeGeek01** [comment]
Oh, ok, but I'm not sure how to complete this template, I'll try again.
