### ISSUE TITLE
[DB] NC_SHARE uid_owner will not update while using Transfer Ownership function 

### ISSUE THREAD

**Issue by freumichCH** [nextcloud/server#23483]
Hello NC-Team 

Today we discovered following bug while using the transfer ownership function in the WebGUI: 
User1 has shared  a Folder with user2 and want to transfer the ownership to user3. The following Notification process works fine. After transfering the data to User3, the system does not update the uid_owner in nc_share for this folder. It presist to the original user1 

Thias results in a faulty share who is not editable anymore over the WebGUI. The option menu for the shared folder is no longer available. But the record presists (see attached screenshot) 

<img width="484" alt="Bildschirmfoto 2020-10-15 um 17 10 36" src="https://user-images.githubusercontent.com/22443781/96149310-74955c80-0f09-11eb-9de9-628fa19882fb.png">

**How to solve this**
To solve this issue, we had to fill the uid_owner field in nc_share with the correct username (new owner: user3). This reactivates the share to user2 and the menu for shared folder apears.

**How to reproduce:** 

> **Setup Users:** 
> - user1 
> - user2
> - user3
> 
> **User1:**
> - Create a folder an drop some data in it. 
> - Share folder with user2
> - Transfer ownership of shared folder with user initiated ownership transfer to user3 
> 
> **User3:**
> - Login to account an accept ownership transfer from user1
> - Waite for cronjob to transfer ownership 
> - Check shares on transfered folder
> - Sharing menu ist not available and folder dissapears in user account of user2
> 

**FYI:** 
The same process with the OCC command, does work seamless. I'm not realy familiar with the sharing System. But i could imaging that the problem sits someware in this file: `apps/files/lib/Service/OwnershipTransferService.php `

Reproducible in NC18.0.7 and NC18.0.9 

It works correct with NC18.0.10 

Does it make sense to backport the Version of responsible file of NC18.0.10 to NC18.0.9 and NC18.0.7?

Thanks in advance 😊

**Comment by vvvllll** [comment]
We had this issue with NC21.0.4 ; some shares remained with the old owner in oc_share and it made some folders unbrowsable with error 500 on propfind of the parent folder of the broken shares.
