### ISSUE TITLE
Permission errors and occ not even working.

### ISSUE THREAD

**Issue by snaildos** [nextcloud/server#23493]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. https://docs.nextcloud.com/server/9/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions follow this guide
2. Now your permissions are stuffed.
3. And nothing works.

### Expected behaviour
I was expecting it to fix OCC since that was showing some permission errors and everything should work.

### Actual behaviour
Well now nothing works at all.
ne 83PHP message: {"reqId":"8lPC0aVJ2EjNh5ltnLzI","level":3,"time":"2020-09-28T07:06:51+00:00","remoteAddr":"162.158.2.211","user":"--","app":"PHP","method":"GET","url":"/","message":"touch(): Unable to create file /usr/share/nginx/nex>
2020/09/28 07:06:51 [error] 6842#6842: *83 FastCGI sent in stderr: "ko) Chrome/85.0.4183.121 Safari/537.36","version":""}PHP message: {"reqId":"8lPC0aVJ2EjNh5ltnLzI","level":3,"time":"2020-09-28T07:06:51+00:00","remoteAddr":"162.158.2.2>
2020/09/28 07:06:51 [error] 6842#6842: *83 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /usr/share/nginx/nextcloud/data/nextcloud.log in /usr/share/nginx/nextcloud/lib/private/Log/File.php on line 83P>
2020/09/28 07:13:33 [error] 6842#6842: *96 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /usr/share/nginx/nextcloud/data/nextcloud.log in /usr/share/nginx/nextcloud/lib/private/Log/File.php on line 83P>
2020/09/28 07:13:33 [error] 6842#6842: *96 FastCGI sent in stderr: "ko) Chrome/85.0.4183.121 Safari/537.36","version":""}PHP message: {"reqId":"R8A752XPWIcTmnDqIuHk","level":3,"time":"2020-09-28T07:13:33+00:00","remoteAddr":"162.158.2.2>
2020/09/28 07:13:33 [error] 6842#6842: *96 FastCGI sent in stderr: "PHP message: PHP Warning:  fileperms(): stat failed for /usr/share/nginx/nextcloud/data/nextcloud.log in /usr/share/nginx/nextcloud/lib/private/Log/File.php on line 83P>
2020/09/28 07:23:17 [error] 6842#6842: *159 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 162.158.2.219, server: cloud.snaildos.tk, request: "POST /settings/apps/enable HTTP/1.1", up>
2020/09/28 07:24:35 [error] 6842#6842: *167 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 162.158.2.193, server: cloud.snaildos.tk, request: "POST /settings/apps/enable HTTP/1.1", up>
2020/09/28 07:25:38 [error] 6842#6842: *177 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Cannot declare class OCA\Talk\Migration\Version2000Date20170707093535, because the name is already in use in /usr/share/nginx/nextcloud/>
2020/09/28 07:33:53 [error] 6842#6842: *409 access forbidden by rule, client: 162.158.2.193, server: cloud.snaildos.tk, request: "GET /data/.ocdata?t=1601278433859 HTTP/1.1", host: "cloud.snaildos.tk"
2020/09/28 07:34:01 [error] 6842#6842: *438 access forbidden by rule, client: 162.158.2.219, server: cloud.snaildos.tk, request: "GET /data/.ocdata?t=1601278441849 HTTP/1.1", host: "cloud.snaildos.tk"
2020/09/28 07:34:13 [error] 6842#6842: *460 access forbidden by rule, client: 162.158.2.219, server: cloud.snaildos.tk, request: "GET /data/.ocdata?t=1601278454169 HTTP/1.1", host: "cloud.snaildos.tk"

### Server configuration

**Operating system: Ubuntu 20**

**Web server: Nginx**

**Database: Maria**

**PHP version: God knows.**

**Nextcloud version: I cant even view the admin page.** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install: I did update once**

**Where did you install Nextcloud from: That stupid one script setup**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Uhm, I sent one at the top.
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
I can't access the server.
```
</details>

**Comment by snaildos** [comment]
I know I was told not the reply, But if you where wondering what I actually want; I just want a permission script to set all my permissions right, this is a mess.

**Comment by kesselb** [comment]
Thanks for reporting 👍

The permission script was developed for Nextcloud 9. The correct permissions for your files depends on your setup. Feel free to ask such questions at https://help.nextcloud.com. That's nothing for the bug tracker.
