### ISSUE TITLE
Make it possible to disable sticky favourites at the top of the list

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#2350]
### Steps to reproduce

1. Sort the file list by date
2. Mark some files and folder as favourites

### Expected behaviour

Favourites should stay where they are. If I need access to them, I have the favourite filter at my disposal

### Actual behaviour

Favourites are migrated to the top of the list, disrupting the order I picked.

If I order files by date, it's because I deem it important to always know which folders have been recently updated. I don't want to have to mentally re-arrange the order.

Since not everybody may agree with me, I would be fine with a Files setting which allows people like me to disable that "feature" :) 

--------
@jancborchardt

**Comment by nickvergessen** [comment]
Maybe we should only sort them to the top, when sorting by name and otherwise just retain them in the normal order?

@ChristophWurst because you implemented this IIRC

**Comment by ChristophWurst** [comment]
> @ChristophWurst because you implemented this IIRC

Nope https://github.com/nextcloud/server/pull/1860 🙊

**Comment by jancborchardt** [comment]
See discussion in #2379. Disabling this based on view is confusing. And why have a switch? If the files are favorites then it's good they are up top. Simply because it's a change from the old? It's also just another code path to maintain.

**Comment by oparoz** [comment]
> If the files are favorites then it's good they are up top.

No. From my OP:
"If I order files by date, it's because I deem it important to always know which folders have been recently updated. I don't want to have to mentally re-arrange the order."

It's not another code path, it's a feature for efficient people. Simplicity first, yes, but only offering one option will never work for everybody. We have a settings panel in the Files app. It's designed for that. This request is similar to the "show hidden files" feature. It's important for some people.

**Comment by jancborchardt** [comment]
This is now 2.5 years old – I’ll close it? Adding a configuration option for something basic as this will increase our testing matrix, and it’s pretty useful by now as we do it everywhere.
