### ISSUE TITLE
Error: Undefined offset: 0 at /apps/serverinfo/lib/OperatingSystems/FreeBSD.php#155

### ISSUE THREAD

**Issue by gegeweb** [nextcloud/server#23501]
### Steps to reproduce
1. Go to Administration > System

### Actual behaviour
Got an error page.

### Server configuration

**Operating system:** FreeBSD 12.1 (Nextcloud running inside a jail)

**Web server:** Nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated (initialy updated from a owncloud server with Nextcoud 13 and last updade from 19.4)

**Log :**
<details>
<summary>Error Log</summary>

Error: Undefined offset: 0 at /usr/local/www/owncloud/apps/serverinfo/lib/OperatingSystems/FreeBSD.php#188

    /usr/local/www/owncloud/apps/serverinfo/lib/OperatingSystems/FreeBSD.php - line 188:

    OC\Log\ErrorHandler::onError(8, "Undefined offset: 0", "/usr/local/ ... p", 188, { result: [ ... ]})

    /usr/local/www/owncloud/apps/serverinfo/lib/Os.php - line 132:

    OCA\ServerInfo\OperatingSystems\FreeBSD->getNetworkInterfaces()

    /usr/local/www/owncloud/apps/serverinfo/lib/Settings/AdminSettings.php - line 111:

    OCA\ServerInfo\Os->getNetworkInterfaces()

    /usr/local/www/owncloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 141:

    OCA\ServerInfo\Settings\AdminSettings->getForm()

    /usr/local/www/owncloud/apps/settings/lib/Controller/AdminSettingsController.php - line 83:

    OCA\Settings\Controller\AdminSettingsController->formatSettings([ [ OCA\Serv ... ]])

    /usr/local/www/owncloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 152:

    OCA\Settings\Controller\AdminSettingsController->getSettings("serverinfo")

    /usr/local/www/owncloud/apps/settings/lib/Controller/AdminSettingsController.php - line 68:

    OCA\Settings\Controller\AdminSettingsController->getIndexResponse("admin", "serverinfo")

    /usr/local/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:

    OCA\Settings\Controller\AdminSettingsController->index("serverinfo")

    /usr/local/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:

    OC\AppFramework\Http\Dispatcher->executeController(OCA\Settings ... {}, "index")

    /usr/local/www/owncloud/lib/private/AppFramework/App.php - line 152:

    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Settings ... {}, "index")

    /usr/local/www/owncloud/lib/private/Route/Router.php - line 308:

    OC\AppFramework\App::main("OCA\\Settin ... r", "index", OC\AppFramew ... {}, { section: " ... "})

    /usr/local/www/owncloud/lib/base.php - line 1009:

    OC\Route\Router->match("/settings/admin/serverinfo")

    /usr/local/www/owncloud/index.php - line 37:

    OC::handleRequest()

</details>

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing this report in favour of https://github.com/nextcloud/serverinfo/issues/250.

Also checkout our new FAQ issue:

- Go to https://github.com/nextcloud/server/issues
- Click FAQ issue
- Check list of known issues
