### ISSUE TITLE
PUT request with missing parent must return status code 409

### ISSUE THREAD

**Issue by SailReal** [nextcloud/server#23519]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Make sure that `/Foo/` doesn't exists
2. Create `/Foo/Bar.txt` using a `PUT` request, e.g. 
   `curl -X PUT "https://.../cloud/remote.php/webdav/Foo/Bar.txt" --upload-file Bar.txt -u xxx`

### Expected behaviour
According to https://tools.ietf.org/html/rfc4918#section-9.7.1 the response code must be `409`:
>    A PUT that would result in the creation of a resource without an
>   appropriately scoped parent collection MUST fail with a 409
>   (Conflict).

### Actual behaviour
The server responds with a status code `404`

### Server configuration

**Operating system:** Linux

**Web server:** Apache

**Database:** mysql 5.7.31

**PHP version:** 7.3.23

**Nextcloud version:** 19.0.4

**Are you using encryption:** no

### Client configuration

**Operating system:** Ubuntu 20.04.1

### Logs

```
curl -X PUT "https://.../remote.php/webdav/Foo/Bar.txt" --upload-file Bar.txt -u xxx -v
Enter host password for user 'xxx':
* Server auth using Basic with user 'xxx'
> PUT /remote.php/webdav/Foo/Bar.txt HTTP/1.1
> User-Agent: curl/7.68.0
> Accept: */*
> Content-Length: 5
< HTTP/1.1 404 Not Found
< Date: Fri, 16 Oct 2020 14:11:33 GMT
< Content-Type: application/xml; charset=utf-8
< Content-Length: 231
< Connection: keep-alive
< Server: Apache
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name Foo could not be located</s:message>
</d:error>
```

**Comment by skjnldsv** [comment]
I think this should go into the sabre/dav repository :)
https://github.com/sabre-io/dav/

**Comment by SailReal** [comment]
@skjnldsv thanks for the hint :+1:, just created this issue https://github.com/sabre-io/dav/issues/1304

**Comment by skjnldsv** [comment]
Thank you! :)
