### ISSUE TITLE
Allow admin to enable multiple (or all) untested apps

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#23526]
Please add ability for admins to enable **all** untested apps, or at least select multiple at once.
![disabled-apps](https://user-images.githubusercontent.com/1787238/96293558-d0aac000-0f9f-11eb-90fe-03c34da6042b.PNG)
![enable-untested](https://user-images.githubusercontent.com/1787238/96293563-d2748380-0f9f-11eb-8dc9-d2203e3e14ee.PNG)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
