### ISSUE TITLE
Please add "Breeze Dark" theme to Accessibility app

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#23527]
[Please fork the Breeze Dark theme into Accessibility app permanently](https://github.com/mwalbeck/nextcloud-breeze-dark/issues/171).  It works just as well as the default Dark theme and the only issue I've noted is it having to update for each new release.  Thank you for considering.

**Comment by Derkades** [comment]
I don't think it is reasonable to expect Nextcloud to become maintainer of all kinds of obscure themes. While the Breeze Dark theme indeed looks good and works well, I think it belongs in the app center rather than in the core installation.

**Comment by sunjam** [comment]
I do not expect anything. Feel free to close this request. Thanks.

**Comment by skjnldsv** [comment]
Yeah, sorry, that is out of scope :/
One day maybe we'll have some themes available (who knows :shrug:), but that is definitely not planned
