### ISSUE TITLE
Retry upload when fail

### ISSUE THREAD

**Issue by christophe195** [nextcloud/server#23547]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I have a low hardware (dual core) setup, when i try to upload files it fails when the server is bussy, if a upload fails it wil stop and i need to serch for missing files in the directory.

**Describe the solution you'd like**
It woud be nice if nextcloud try's to reupload the files when there is something wrong

**Describe alternatives you've considered**
I upload multiple times the same directory if i see that the file count's doesn't match and keep existing on nextcloud

**Additional context**
Sorry, no screenshot of the problem

**Comment by bes1002t** [comment]
Mh as a workaround you could simply keep the old upload, upload it again and skip the already uploaded files. Nextcloud should ask whether files which are already uploaded should be replaced or not. 

But I'm totally with you, there should be a retry upload at the end of the upload procedure, for all files which could be not uploaded in the first attempt.

I recognized this issue as well, but was not sure whether it is caused of bad server configuration. I get the following error messages for two images which could be not uploaded (but also had cases with much more image upload failures):
2020/10/19 23:46:05 [error] 2359#2359: *37000 FastCGI sent in stderr: "PHP message: {"reqId":"Wc3raId0Wt87GipvPUvL","level":1,"time":"2020-10-19T23:46:05+02:00","remoteAddr":"87.175.103.182","user":"<username>","app":"text","method":"POST","url":"/<cloud_root>/apps/text/session/sync","message":{"Exception":"OCP\\Files\\Not$
2020/10/19 23:46:05 [error] 2359#2359: *37000 FastCGI sent in stderr: "PHP message: {"reqId":"eWDMYwcXMCv7QU713Gvg","level":1,"time":"2020-10-19T23:46:05+02:00","remoteAddr":"87.175.103.182","user":"<username>","app":"text","method":"POST","url":"/<cloud_root>/apps/text/session/sync","message":{"Exception":"OCP\\Files\\Not$

**Comment by christophe195** [comment]
the uploader get's a time out from the server, it is low power and likly processing files the files (and thumbnails).

I do not want to increase the timeout on the server.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
