### ISSUE TITLE
Theming app: allow domain, group or user based custom theming

### ISSUE THREAD

**Issue by eldelacajita** [nextcloud/server#23545]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
We are setting up a Nextcloud instance that is to be used and accessed by different groups or organizations, each through a different domain. We want them to have their own branding without creating separate NC instances, but Branding app doesn't let us choose a branding based on organizations/groups, but just for the whole instance. This is a great limitation in terms of branding and ease of use. 

**Describe the solution you'd like**
We would love to have a way to set up different themes for different domains (so that when a user accesses through X.com domain, sees X branding, and when using Y.com domain, sees Y branding). The Theming app would allow creating several themes and choosing to which domains they would be assigned. 

**Describe alternatives you've considered**
The solution could also be user- or group-based. In this alternative, the Theming app would allow to have several themes and choose which users or groups would see which themes. I'm not suggesting a user-side theme chooser, but something that the admin of the instance can control and set up for everyone. 

**Additional context**
Just adding a quick mockup here. Each column could be a different theme, and include a field for selecting to which domain/group/users the theme should be applied. 

![Group-based-theming-obfuscated](https://user-images.githubusercontent.com/2880679/96354095-dce36a00-10d2-11eb-986c-115fcb926401.png)

Don't take this too seriously, this is really just a quick test. If you need help with further design, I'd be glad to give this some more thought. For example, theme assignation should be mutually exclusive, and there should be a button for adding or creating a new theme.

**Comment by kesselb** [comment]
https://help.nextcloud.com/t/support-for-multi-tenancy/76788

**Comment by eldelacajita** [comment]
We are sharing the instance with small groups or organizations. Being on one instance makes collaboration easier (without relying on federation) and minimizes maintenance costs, but having different branding for different domains would be really helpful, especially for less tech-savy people. 

But... I see your point. Thanks for the reply.

**Comment by kesselb** [comment]
> different domains would be really helpful

https://help.nextcloud.com/t/howto-individual-themes-per-domain/27585 that's possible just not out of the box.

**Comment by eldelacajita** [comment]
Thanks a lot for the link!

**Comment by tomlp** [comment]
Dear all,
i like to jump into this issue - i (mostly) installed the individual "theme per domain". At the Time a User logged in, he has the look regarding the settings.
I stuck now in the "automated send notification" emails from nextcloud himself. They are all send with the first domain....

How can i bring nextcloud to look into the share where it is created from (the domain where the user logged in as he created the share/directory) and send with this settings. The share should have a different mail domain too - it works with the user interaction, but not on system level where the notifications are created and send ?
a glue will be fantastic - as nextcloud is in general :)
kr Tom

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by punkyard** [comment]
Then I'd like to add my request to put some weight on that request

 💪🤓👍

which is quite surprising besides the great utility this option shows.

And, in the end, not much is required: just a bit more power in the required css files ;)
like the background setting at login page ;)

**Comment by ripper17** [comment]
This would be a great addition, indeed. Usecase: I'm basically the entire IT department for a couple of hobyyist projects and it would be (hopefully) easier to maintain only one instance of nextcloud.
