### ISSUE TITLE
Add an "email me" notification for logins

### ISSUE THREAD

**Issue by criwe** [nextcloud/server#2354]
Hi all!

It would be nice to have an "email me, when someone logs in with my accout"-option.

Thx!
Best
Chris

**Comment by MorrisJobke** [comment]
cc @LukasReschke @ChristophWurst

**Comment by ChristophWurst** [comment]
Hi,
what's the use case for this?

**Comment by criwe** [comment]
@ChristophWurst you know when someone logs in with your account. So when someone gets your logindata, you get information about it when that person logs in.

**Comment by MorrisJobke** [comment]
> what's the use case for this?

I only see a use case here for the "there was a new not known device that authed" or "there was a device from an uncommon location that authed"

**Comment by nickvergessen** [comment]
That usecase isenough I think?

@criwe did you already post it in our app ideas section? https://help.nextcloud.com/c/feature/app-ideas
Because that is where I think it should be.

**Comment by criwe** [comment]
@nickvergessen not yet, but I will do it, thx for the hint

**Comment by joshtrichards** [comment]
The `suspicious_login` app that exists today fulfills this role to a large extent and also minimizes unnecessary notifications:

https://github.com/nextcloud/suspicious_login
