### ISSUE TITLE
Could not find resource core/js/files/... when clicking on "workflow" in settings.

### ISSUE THREAD

**Issue by DJ-3ncoder** [nextcloud/server#23542]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. click on "workflow" in settings: domain.com/settings/admin/workflow
2. check the logs and see the error: "Could not find resource core/js/files/client.js to load"

### Expected behaviour
no error

### Actual behaviour
error: "Could not find resource core/js/files/client.js to load"

### Server configuration

**Operating system:** Ubuntu Focal Fossa 20.04.1 LTS GNU/Linux 5.4.0-51-generic x86_64

**Web server:** nginx 1.19.3-1~focal

**Database:** MariaDB, mysql

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh installation on fresh Focal Fossa

**Where did you install Nextcloud from:**
official Nexctloud website

**Signing status:**
Don't know what this is

Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

"No errors have been found."

```
</details>

**List of activated apps:**


```
If you have access to your command line run e.g.:
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - firstrunwizard
  - survey_client
  - user_ldap

**Nextcloud configuration:**

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system

{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.3ncoder.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "https:\/\/cloud.3ncoder.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "activity_expire_days": 14,
        "auth.bruteforce.protection.enabled": true,
        "blacklisted_files": [
            ".htaccess",
            "Thumbs.db",
            "thumbs.db"
        ],
        "cron_log": true,
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\Movie",
            "OC\\Preview\\PDF",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown"
        ],
        "filesystem_check_changes": 0,
        "filelocking.enabled": "true",
        "htaccess.RewriteBase": "\/",
        "integrity.check.disabled": false,
        "knowledgebaseenabled": false,
        "logfile": "\/wd-red-1TB\/nc-data\/nextcloud.log",
        "loglevel": 2,
        "logtimezone": "Europe\/Vienna",
        "log_rotate_size": 104857600,
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "overwriteprotocol": "https",
        "preview_max_x": 1024,
        "preview_max_y": 768,
        "preview_max_scale_factor": 1,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0
        },
        "quota_include_external_storage": false,
        "share_folder": "\/Shares",
        "skeletondirectory": "",
        "theme": "",
        "trashbin_retention_obligation": "auto, 7",
        "updater.release.channel": "stable",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpsecure": "tls",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** no but it is not the main-partition

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

no ldap

### Client configuration
**Browser:** Firefox 81.0.2

**Operating system:** Windows 10 Pro

#### Web server error log
no error in this time

#### Nextcloud log (data/nextcloud.log)

"user":"niklas-nc","app":"jsresourceloader","method>{"reqId":"e7fSiUloNkwomF8pGaEq","level":3,"time":"2020-10-17T17:32:49+02:00"
Could not find resource core/js/files/clients.js to load

"user":"niklas-nc","app":"jsresourceloader","method>{"reqId":"e7fSiUloNkwomF8pGaEq","level":3,"time":"2020-10-17T17:32:49+02:00"
Could not find resource core/js/files/fileinfo.js to load

"user":"niklas-nc","app":"jsresourceloader","method>{"reqId":"hxMM4RFEL15S6Bf74lOT","level":3,"time":"2020-10-17T17:38:55+02:00"
Could not find resource core/js/files/clients.js to load

"user":"niklas-nc","app":"jsresourceloader","method>{"reqId":"hxMM4RFEL15S6Bf74lOT","level":3,"time":"2020-10-17T17:38:55+02:00"
Could not find resource core/js/files/fileinfo.js to load

**Comment by pszypowicz** [comment]
Same error. 

I'm using php-fpm. Error happen for example when I try to share Task deck with other user. 

Ubuntu 20.04
PHP: 7.4.3
Postgresql: 12.4
Nginx: 1.18

Error:
```
{"reqId":"VteHg2dxktlfK4hVFIcj","level":3,"time":"2020-11-09T09:47:48+00:00","remoteAddr":"192.168.xxx","user":"xxx","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/files/client.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1","id":"5fa915b484de6"}
{"reqId":"VteHg2dxktlfK4hVFIcj","level":3,"time":"2020-11-09T09:47:48+00:00","remoteAddr":"192.168.xxx","user":"xxx","app":"jsresourceloader","method":"GET","url":"/settings/admin/workflow","message":"Could not find resource core/js/files/fileinfo.js to load","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0","version":"20.0.1.1","id":"5fa915b484df9"}
```

**Comment by ChillmasterG** [comment]
I have nearly the same error.

Im using debian 10.6
php 7.3.24
mysql 10.3.25
apache 2.4.38-3
nginx 1.18.0.1 as proxy

nextcloud 20.0.2

Error:
`[jsresourceloader] Error: Could not find resource core/js/files/fileinfo.js to load

GET /index.php/settings/admin/workflow
from 77.20.10.222 by admin at 2020-11-19T16:11:43+00:00`

**Comment by fireeater112** [comment]
Same behavior
FreeBSD 12.2-RC3 amd64
php 7.4.12
mysql 10.4.15
nc 20.0.2

**Comment by FALErwi** [comment]
![16058282625496106898713969098876](https://user-images.githubusercontent.com/74250574/99736510-8dc89480-2ad7-11eb-8098-755d6d5408e3.jpg)

Fresh installation NC 20.0.2
Apache 2.4
PHP 7.4
Database Mysql latest version
OS Ubuntu 20.04

**Comment by anto** [comment]
I saw a lot of messages with "Could not find resource core/js/files/client.js to load" on nextcloud.log after I upgraded to version 20.0.1. But maybe that was because I manually upgraded from version 19.0.3. The update notification stopped functioning, so I didn't realise that there were versions 19.04 and 19.0.5 before version 20.0.0

I followed manual upgrade guide on https://docs.nextcloud.com/server/20/admin_manual/maintenance/manual_upgrade.html, so of course core/js/files directory (actually core/js/systemtags as well) is not carried over from version 19.0.3 to 20.0.1.

What I did to get rid of the error message was to copy core/js/files directory and its content from version 19.0.3 into version 20.0.1. I am not sure if that would be a good solution.

As side notes, there are actually files and directories which exist in version 19.0.3 but they don't exist in version 20.0.1. So I am wondering if I should actually just copy the whole files version 20.0.1 into the old version 19.0.3, so that the old directories and files in 19.0.3 which do not exist in 20.0.1 will be kept. I am now in version 20.0.2 (the update notification works again), so I am not sure if I could safely do re-upgrade (is that even the right word?)

**Comment by FALErwi** [comment]
Any help in this issue as I need to use the workflow.

**Comment by anto** [comment]
> Any help in this issue as I need to use the workflow.

Did you try copying core/js/files directory and its content from version 19.0.5 into your current version?

I am not sure which workflow apps that you want to use. But I did that and I can use "Automated PDF conversion" apps. It did not even show up on the "Available Flows" before I copied that core/js/files directory.

**Comment by pszypowicz** [comment]
I had a first installation of 20.0.0 (now upgraded to 20.0.2). There are no files for me to "move" from previous installation. I'm curious if package maintainer forgot to include them?

**Comment by anto** [comment]
> I had a first installation of 20.0.0 (now upgraded to 20.0.2). There are no files for me to "move" from previous installation. I'm curious if package maintainer forgot to include them?

Well... You can just download https://github.com/nextcloud/server/archive/v19.0.5.zip, extract it and copy the core/js/files directory and its content into you running installation, can't you?

**Comment by anto** [comment]
From what I observed, I think the component relevant to the workflow is not yet being updated. The core/js/files has been moved to webpack by commit https://github.com/nextcloud/server/commit/44d05bf356824329d7691e00e91aa7de891221b9 in May.

**Comment by skjnldsv** [comment]
cc @juliushaertl

**Comment by juliushaertl** [comment]
Fix is in https://github.com/nextcloud/server/pull/24374

**Comment by phu9Suop** [comment]
I have the same problem on a fresh install in November 20, no nx update ever since
L
Linux 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
"Devuan GNU/Linux 3 (beowulf)"
10.0
CHASSIS=server
A
Server version: Apache/2.4.38 (Debian)
Server built:   2020-08-25T20:08:29
Package: apache2
Version: 2.4.38-3+deb10u4
State: installed
Automatically installed: no
M
Package: mariadb-server
Version: 1:10.3.27-0+deb10u1
State: installed
Automatically installed: no
Package: mariadb-client-core-10.3
Version: 1:10.3.27-0+deb10u1
State: installed
Automatically installed: no
E: Unable to locate package mysql
Nextcloud
  'version' => '20.0.2.2',
P
PHP 7.3.27-1~deb10u1 (cli) (built: Feb 13 2021 16:31:40) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.27-1~deb10u1, Copyright (c) 1999-2018, by Zend Technologies
