### ISSUE TITLE
Option to set default dashboard background in theming app

### ISSUE THREAD

**Issue by michag86** [nextcloud/server#23558]
Make the default dashboard background configurable. This is important for enterprise users to customize it to their corporate design.

I think the best place for this settings is in settings - design (theming app).

**Comment by skjnldsv** [comment]
cc @jancborchardt @rullzer @MorrisJobke

**Comment by MorrisJobke** [comment]
Up to @jancborchardt and @juliushaertl I would say. :)

**Comment by juliushaertl** [comment]
Implemented by https://github.com/nextcloud/server/pull/23588
