### ISSUE TITLE
Migrate everything from app.php to the Application class.

### ISSUE THREAD

**Issue by letopisec3** [nextcloud/server#23560]
Server configuration
Ubuntu 20.04.1 LTS
Apache Apache/2.4.41
PHP 7.4.9
10.3.22-MariaDB-1ubuntu1
Nextcloud 20.0.0
Updated from 19
![Снимок экрана_2020-10-19_13-07-52](https://user-images.githubusercontent.com/36674563/96431758-a6aa0580-120c-11eb-9d43-b7c1c0c148bb.png)

**Comment by acsfer** [comment]
Check https://github.com/nextcloud/server/issues/23442
