### ISSUE TITLE
After the update >>> InvalidArgumentException

### ISSUE THREAD

**Issue by ichdu007** [nextcloud/server#23573]
After the update nextcloud is no longer available and I don't know what to do. :(
Can anyone help me?
Nextcloud is on a subdomain at the hoster all-inkl.

#####
Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

**InvalidArgumentException: Column name "gVA4A_flow_operations"."entity" is NotNull, but has empty string or null as default.**

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favour of https://github.com/nextcloud/server/issues/23174.
