### ISSUE TITLE
Cannot create new users after upgrade

### ISSUE THREAD

**Issue by asterismo** [nextcloud/server#2358]
Hi, i updated next cloud a couple of times and now i cannot create new users using the admin webpage

I get this error in nginx log:

2016/11/27 20:24:45 [error] 1544#0: *4937 FastCGI sent in stderr: "PHP message: {"reqId":"g2Ph8j0eXyEt3XhF5+2A","remoteAddr":"127.0.0.1","app":"core","message":"Login failed: 'admin' (Remote IP: '127.0.0.1')","level":2,"time":"2016-11-27T20:24:45+00:00","method":"POST","url":"\/index.php\/login","user":"--"}" while reading response header from upstream, client: 127.0.0.1, server: nextcloud.mydomain.com, request: "POST /index.php/login HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "nextcloud.mydomain.com"

I hit the create button and nothing happens. Nothing is logged in nextcloud.log

any ideas? it seems a misconfiuguration of php?

**Comment by MorrisJobke** [comment]
@asterismo Could you check the web developer tools in your webbrowser when you click the create user button. (Open them and then click the button)

There the console and the network tab are of interest. Best would be to send over a screenshot of those two tabs.

**Comment by schiessle** [comment]
Additionally it would be good to know the Nextcloud version you are using. Thanks!

**Comment by asterismo** [comment]
its 10.0.1 stable

**Comment by asterismo** [comment]
No clue... still cannot.

**Comment by asterismo** [comment]
What else can i provide to try to fix this?

**Comment by asterismo** [comment]
TypeError: result.responseJSON is undefined
<anonymous>
 users.js:874
n.Callbacks/j()
 jquery.min.js:2
n.Callbacks/k.fireWith()
 jquery.min.js:2
x()
 jquery.min.js:4
.send/b/<()
 jquery.min.js:4

**Comment by asterismo** [comment]
That happened when clicking the button on developer console

**Comment by asterismo** [comment]
any other info that i can provide to help solve this problem?

**Comment by MorrisJobke** [comment]
@asterismo Could I ask you for opening the developer console and click the button. Then check the network tab. There must happen a request when clicking the button. The content of that request would be really nice to have. Maybe took some screenshots of the content of the response and the headers that are send.

**Comment by asterismo** [comment]
This is from the Net tab in developer console, 

TypeError: result.responseJSON is undefined
<anonymous>
 users.js:874
n.Callbacks/j()
 jquery.min.js:2
n.Callbacks/k.fireWith()
 jquery.min.js:2
x()
 jquery.min.js:4
.send/b/<()

This is from the Security tab in developer console, 

TypeError: result.responseJSON is undefined
<anonymous>
 users.js:874
n.Callbacks/j()
 jquery.min.js:2
n.Callbacks/k.fireWith()
 jquery.min.js:2
x()
 jquery.min.js:4
.send/b/<()

I'm running Debian 8 Jessie, nginx/1.6.2 and PHP 5.6.28-0+deb8u1 (cli)

**Comment by MorrisJobke** [comment]
Sorry I meant the details about what request is sent to the server and what the response is (especially HTTP  response code and actual response) 

The errors you wrote are the symptoms of this wrong response

**Comment by asterismo** [comment]
This is the log i get from access.log in nginx, error.log shows nothing.
https://pastebin.oalm.gub.uy/view/6b3f15e8

**Comment by asterismo** [comment]
Inoticed a POST XHR line in the browser console with this error

POST 
XHR 
https://cloud.undernet.uy/index.php/settings/users/users [HTTP/1.1 403 Forbidden 194ms]

**Comment by MorrisJobke** [comment]
> https://cloud.undernet.uy/index.php/settings/users/users [HTTP/1.1 403 Forbidden 194ms]
> That happens when i click on the "create" button. Is some permission issue maybe...

This is indeed interesting. You are using an admin user? Or is this only a group admin?

**Comment by asterismo** [comment]
I'm the admin user, and on this account i have created the other 2 accounts... its wierd

**Comment by MorrisJobke** [comment]
@asterismo What apps are enabled?

**Comment by asterismo** [comment]
![cloud_apps](https://cloud.githubusercontent.com/assets/5679035/21322061/3ac33b4a-c5f6-11e6-8f64-287590aed60c.png)

**Comment by asterismo** [comment]
Should i try disabling all and then create new user?

**Comment by MorrisJobke** [comment]
> Should i try disabling all and then create new user?

Yes - maybe disable one app after another to see which one is the app that maybe causes this.

**Comment by asterismo** [comment]
Well, it was the "Password Policy" module causing the problem. I disabled it and i could create accounts. Its wierd because it shows no error, it should prompt some message as a feedback. The module was activated but i had not defined any password policy whatsoever. I'm closing this issue. Thanks @MorrisJobke

**Comment by MorrisJobke** [comment]
For me the error is shown (on 10.0.1):

![bildschirmfoto 2016-12-21 um 06 36 57](https://cloud.githubusercontent.com/assets/245432/21378622/e8f2f2b2-c747-11e6-82ee-4a62ce96eb19.png)


By default this app only checks for the most common 1 million passwords (which is a sane default from our point of view)

**Comment by asterismo** [comment]
Yeah, i have no feedback whatsoever... so thst is why i had no clue about the error...

**Comment by wudimenghuan** [comment]
I have this problem, too.
It's default install in 11 stable
