### ISSUE TITLE
Log entries due to no user logging on to the external storage

### ISSUE THREAD

**Issue by weinic** [nextcloud/server#23587]
Hello, 
I have the following problem.

[files] Error: Icewind\SMB\Exception\ForbiddenException: Invalid request for /petra (ForbiddenException) at <<closure>>

 0. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 66
    Icewind\SMB\Exception\Exception::fromMap({1: "Icewind\\SM ... "}, 13, "/petra")
 1. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 78
    Icewind\SMB\Native\NativeState->handleError("/petra")
 2. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeState.php line 109
    Icewind\SMB\Native\NativeState->testResult(false, "smb://127.0.0.1/intern/petra")
 3. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Native/NativeShare.php line 92
    Icewind\SMB\Native\NativeState->opendir("smb://127.0.0.1/intern/petra")
 4. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 236
    Icewind\SMB\Native\NativeShare->dir("petra")
 5. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files_external/lib/Lib/Storage/SMB.php line 604
    OCA\Files_External\Lib\Storage\SMB->getFolderContents("petra")
 6. <<closure>>
    OCA\Files_External\Lib\Storage\SMB->getDirectoryContent("petra")
 7. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 408
    iterator_to_array(Generator {})
 8. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 388
    OC\Files\Cache\Scanner->handleChildren("petra", 2, 3, 15257869, true, 0)
 9. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 340
    OC\Files\Cache\Scanner->scanChildren("petra", 2, 3, 15257869, true)
10. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 506
    OC\Files\Cache\Scanner->scan("petra", 2, 3)
11. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 517
    OC\Files\Cache\Scanner->OC\Files\Cache\{closure}("*** sensitive parameters replaced ***")
12. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Cache/Scanner.php line 505
    OC\Files\Cache\Scanner->runBackgroundScanJob(Closure {}, "petra")
13. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Files/Utils/Scanner.php line 186
    OC\Files\Cache\Scanner->backgroundScan()
14. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 83
    OC\Files\Utils\Scanner->backgroundScan("")
15. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/files/lib/BackgroundJob/ScanFiles.php line 111
    OCA\Files\BackgroundJob\ScanFiles->runScanner(OC\User\User {})
16. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/BackgroundJob/Job.php line 62
    OCA\Files\BackgroundJob\ScanFiles->run(null)
17. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/BackgroundJob/TimedJob.php line 57
    OC\BackgroundJob\Job->execute(OC\BackgroundJob\JobList {}, OC\Log {})
18. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/cron.php line 126
    OC\BackgroundJob\TimedJob->execute(OC\BackgroundJob\JobList {}, OC\Log {})

at 2020-10-20T12:00:03+02:00

**Comment by weinic** [comment]
This message comes every few minutes

I also know where this message comes from and I have made the following settings in the admin area for the external storage so that users only have to log in with their username and password.

![Screenshot_20201020-122316](https://user-images.githubusercontent.com/57099502/96575189-bc80fe80-12d0-11eb-8264-2fa35b64fb2d.jpg)


However, I get this above error for all users who have not logged in.  Here it would be good if you don't get any log entries because of this.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
