### ISSUE TITLE
Odd German translation for "file drop"

### ISSUE THREAD

**Issue by julieannenoying** [nextcloud/server#2359]
"File drop" in the file sharing sidebar was translated to "Datei fallen lassen".. Maybe it's better to name it "Dateiablage" or something similar?
![issue](https://cloud.githubusercontent.com/assets/24209909/20652743/67489e88-b4ff-11e6-8557-cab8d3fdaf79.jpg)

**Comment by go2sh** [comment]
The translations are managed with [transifex](https://www.transifex.com/nextcloud/nextcloud/). I changed the translation to: "Dateien ablegen (nur Hochladen)"

**Comment by MorrisJobke** [comment]
Oh dear -.- German translations for stuff like this are always funny 😕 

@julieannenoying Thanks for spotting :)

@go2sh Thanks for fixing.

 I just reran the transifex job. Should be fixed now :)
