### ISSUE TITLE
Avatar: choosing a .gif results in "unknown file type"

### ISSUE THREAD

**Issue by julieannenoying** [nextcloud/server#2360]
When trying to set a user profile picture, uploading a gif file is not supported. It says "png or jpg", but people tend to not read it. I was wondering if there is a reason for not supporting gifs? (it was not an animated gif).
cc @rullzer @icewind1991 
![issue2](https://cloud.githubusercontent.com/assets/24209909/20652766/3eb33b08-b500-11e6-8816-b655ae66f46e.jpg)

**Comment by MorrisJobke** [comment]
cc @juliushaertl @rullzer

**Comment by nickvergessen** [comment]
Seems like only jpg and png are allowed:
https://github.com/nextcloud/server/blob/b05fe45d520a8df309897626ad109a4daf64ed83/core/Controller/AvatarController.php#L245-L250

I guess the problem is that transparency and animation might break horrible with the cropping/resizing and therefor we just don't allow them at all, instead of having to deal with all the corner cases gifs have.

**Comment by LukasReschke** [comment]
👍 for just keeping GIF disallowed.

**Comment by jancborchardt** [comment]
Why don’t we just suppress the animation then? And png has transparency as well, so it’s not only gif. Gif is a normal image type. Other platforms like Twitter, Google etc allow it as well.

@rullzer please comment on the feasibility

**Comment by rullzer** [comment]
We never supported gif there. I can't tell you anything about the orginal reasons. I think GIF is just a pain to work with.

However we have currently no way to suppress the animation in our current image classes. So unless somebody is masocistic enough to dive into our OC_Image class and make it a proper class and then add nice awesome gif stuff to it. It won't happen.

Also note that the users that don't read 'Only jpeg or png supported' probabaly will also wonder why their awesome animated gif is now no longer animated.

**Comment by jancborchardt** [comment]
Good points @rullzer, thanks for the clarification.
