### ISSUE TITLE
Slow upload file

### ISSUE THREAD

**Issue by icecko** [nextcloud/server#23600]
Write files to nextcloud server through Webdav or web is too slow.
Transfer to server is fast but wait to write and close dialog window is too slow.

size of file(s)---time/speed-----time to end
300M---------150MB/s-------40s
1400M--------150MB/s-------203s
1000M--------150MB/s------165s
700M---------150MB/s-------117s
400 x 1.1M-----80MB/s-------780s

After thist test I try do delete created files. This proces was too slow. Deleted 3 files/s and proces  take cca 30s

I did this test on more configuration of virtual server. I used SSD disk. And Php7.2 and 7.3.

### Server configuration

**Operating system:CentOS Linux 3.10.0-1127.19.1.el7.x86_64 x86_64 (Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (1 core))

**Web server:Apache/2.4.6

**Database: mysql 5.5.56

**PHP version:	7.2.34

**Nextcloud version:19.0.2.2

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favour of https://github.com/nextcloud/server/issues/22045. There is a overhead by using Nextcloud. If you look for the maximum performance you might use a different tool.
