### ISSUE TITLE
FTP dont work properly with Win1251

### ISSUE THREAD

**Issue by vgdh** [nextcloud/server#23605]
an be reproduce at NC18

If FTP uses an encoding WIN_1251, then only files named in english will be visible.

I use docker version of Nextcloud

Server configuration detail
Operating system: Linux 4.15.0-117-generic #118-Ubuntu SMP Fri Sep 4 20:02:41 UTC 2020 x86_64
Webserver: Apache/2.4.38 (Debian) (apache2handler)
Database: mysql 10.5.5
PHP version: 7.3.21
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache
Nextcloud version: 18.0.8 - 18.0.8.2
Updated from an older Nextcloud/ownCloud or fresh install:
Where did you install Nextcloud from: unknown
<details><summary>Signing status</summary>
Array ( )
</details>
<details><summary>List of activated apps</summary>

Enabled:
 - accessibility: 1.4.0
 - activity: 2.11.0
 - admin_audit: 1.8.0
 - checksum: 0.4.5
 - cloud_federation_api: 1.1.0
 - comments: 1.8.0
 - dav: 1.14.0
 - drawio: 0.9.7
 - extract: 1.2.4
 - federatedfilesharing: 1.8.0
 - federation: 1.8.0
 - files: 1.13.1
 - files_downloadactivity: 1.7.0
 - files_external: 1.9.0
 - files_linkeditor: 1.1.2
 - files_mindmap: 0.0.23
 - files_pdfviewer: 1.7.0
 - files_rightclick: 0.15.2
 - files_sharing: 1.10.1
 - files_trackdownloads: 1.7.0
 - files_trashbin: 1.8.0
 - files_versions: 1.11.0
 - files_videoplayer: 1.7.0
 - firstrunwizard: 2.7.0
 - logreader: 2.3.0
 - lookup_server_connector: 1.6.0
 - nextcloud_announcements: 1.7.0
 - notifications: 2.6.0
 - oauth2: 1.6.0
 - onlyoffice: 6.0.2
 - password_policy: 1.8.0
 - photos: 1.0.0
 - privacy: 1.2.0
 - provisioning_api: 1.8.0
 - quota_warning: 1.7.0
 - recommendations: 0.6.0
 - serverinfo: 1.8.0
 - settings: 1.0.0
 - sharebymail: 1.8.0
 - spreed: 8.0.11
 - support: 1.1.1
 - survey_client: 1.6.0
 - systemtags: 1.8.0
 - text: 2.0.0
 - theming: 1.9.0
 - twofactor_backupcodes: 1.7.0
 - updatenotification: 1.8.0
 - viewer: 1.2.0
 - workflowengine: 2.0.0
Disabled:
 - encryption
 - files_readmemd
 - sharingpath
 - user_ldap

Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36
Where did you install Nextcloud from: Docker HUB

**Comment by kesselb** [comment]
As reference: https://github.com/nextcloud/server/issues/18604

Would you mind to explain how to reproduce this situation? It's also not cool to ignore the issue template (the second time actually). That makes reproducing such issues much harder and lowers your chance than one will fix it or is at least able to reproduce. 

For such a problem the information what kind of ftp server you are connection too could be relevant.

**Comment by vgdh** [comment]
Its very easy to reproduce.
Of FTP server add folder with cyrillic name "НазваниеПапки". 
Then on any version of Nextcloud add  this FTP to  "FTP External Storage"
You are will not able to see this folder "НазваниеПапки" in your nextcloud External Storage.
But english name works well.

**Comment by j-ed** [comment]
@vgdh Please also tell us which ftp server you are using in detail. I made the experience that not all of them are working in the same way and that the behavior might differ based on the used server package.

**Comment by vgdh** [comment]
I experience this issue on all ftp that a try to use. Unfortunately i can't give credentials for private FTPs our company uses.
Its been FTP 4 different FTP from 4 different company, i guess server side soft is also pretty mach different .

**Comment by kesselb** [comment]
I'm not able to reproduce. 

- Have a local development setup for Nextcloud 20
- https://github.com/stilliard/docker-pure-ftpd/wiki/Basic-example-walk-through
- Connect with FileZilla
- Create a folder "НазваниеПапки"
- Create a file "test.md"
- Configure the above ftp as external storage in Nextcloud

![image](https://user-images.githubusercontent.com/3902676/96748713-3648e300-13ca-11eb-9b64-37870c047586.png)

![image](https://user-images.githubusercontent.com/3902676/96748776-48c31c80-13ca-11eb-8c70-a2ff09e249d0.png)

**Comment by j-ed** [comment]
I just tested it on my own server with a ftp share, mounted as "FTP", with the following results:
1. ❎ - I've created a ftp folder "**AAA-НазваниеПапки**" on the file system, accessed the ftp share, but the folder **wasn't displayed**.
2. ✅ - I've created a ftp folder "**BBB-НазваниеПапки**" using the Nextcloud files app, accessed the ftp share and the newly created folder **was instantly displayed**.   
3. ❎ - I've executed the following command on the server but the first created folder **wasn't displayed**:
    `./occ files:scan "/testuser/FTP"`  
4. ✅ - I've executed the following command on the server and the first created folder **was displayed**:
   `./occ files:scan testuser

➡️ So my conclusion is, that a character set problem most likely doesn't exist but the file system need to be scaned to update the  folder and file list information of the external share in the database.
