### ISSUE TITLE
Stucked in grid view - setting ui disappears

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/server#23607]
### Steps to reproduce
1. Guess it happens after NC 20 upgrade.
2. When I use files app, the setting (top right corner) where I could change the view (grid or list) just stays for a blink while loading the page.

### Expected behaviour
That setting should stay at that corner.

### Actual behaviour
It flashes for a short moment, unable to change that view.

`
Diese Seite verwendet die nicht standardisierte Eigenschaft "zoom". Stattdessen sollte calc() in den entsprechenden Eigenschaftswerten oder "transform" zusammen mit "transform-origin: 0 0" verwendet werden. files
Uncaught (in promise) TypeError: window.OCA.Files.App.fileList is null
    29 client.js:130
    29 client.js:28
    o Webpack
client.js:130:1
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 10 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 22 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 22 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 22 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 23 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 23 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 22 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 22 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 24 main.js:1:1407020
OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206697
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 26 main.js:1:1407020
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 9 main.js:1:1407020
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 216 main.js:1:1407020
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 12 main.js:1:1407020
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 29 main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 7 main.js:1:1407020
jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 196 main.js:1:1407020
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 29 main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 7 main.js:1:1407020
OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment 261 main.js:1:206868
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own. 14 main.js:1:1407020
1

​

`

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**List of activated apps:**
<details>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - analytics: 3.0.0
  - announcementcenter: 4.0.0
  - appointments: 1.7.11
  - apporder: 0.11.0
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - deck: 1.1.2
  - documentserver_community: 0.1.7
  - event_update_notification: 1.1.0
  - external: 3.7.1
  - extract: 1.2.4
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.0
  - files_automatedtagging: 1.10.0
  - files_linkeditor: 1.1.2
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_readmemd: 1.2.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - flow_notifications: 1.0.2
  - forms: 2.0.4
  - groupfolders: 8.1.0
  - impersonate: 1.7.0
  - login_notes: 0.3.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.5.0
  - metadata: 0.12.0
  - news: 15.0.4
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.1.0
  - password_policy: 1.10.1
  - polls: 1.5.4
  - previewgenerator: 3.0.1
  - printer: 0.0.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quickaccesssorting: 1.1.1
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - side_menu: 1.19.0
  - socialsharing_email: 2.1.0
  - spreed: 10.0.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - talk_simple_poll: 1.2.0
  - tasks: 0.13.5
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_sql: 4.5.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_script: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - bruteforcesettings
  - encryption
  - files_external
  - firstrunwizard
  - issuetemplate
  - ocr
  - photos
  - ransomware_protection
  - sharerenamer
  - telephoneprovider
  - user_ldap

</details>

**Comment by kesselb** [comment]
You are using some apps which are not compatible to Nextcloud 20. I would try to turn them off one by one and figure out which on breaks. Maybe start with files_readmemd.

**Comment by Dubidubiduu** [comment]
It has been Custom Menu. I'm writing to the app author.

**Comment by kesselb** [comment]
> It has been Custom Menu. I'm writing to the app author.

Thanks :+1:
