### ISSUE TITLE
Suggestion: Change how the storage backend works

### ISSUE THREAD

**Issue by Dragon988** [nextcloud/server#23610]
Current behavior:

Uploading: Files are uploaded into the user uploads folder. Upload completes -> Waits for all uploads to finish -> Uploads all contents to storage backend and/or copied.

Trash: Files are physically copied to the trash folder.

Suggested behavior:

Uploading: Files are uploaded to the uploads folder and when an individual file completes should be uploaded/copied to the storage backend immediately instead of waiting for the entire contents to finish.

Trash: There either needs to be a "delete now" option or this system needs to be reworked so the files aren't transferred to the root filesystem.

Reasons for suggestion:

I have an installation with a very limited / root file system.

Trash: I am not able to delete any folders above 30GB in length because it copies them to the root file system which becomes full.

This means nextcloud can't delete any files and it becomes useless as a file manager.

Uploading: If I have a 10TB drive mounted/binded to my users files directory and I'm uploading 400GB of files... I should not have to have 400GB on the root filesystem, nor should 400GB be stuck in the uploads folder until everything finishes uploading.

Question: If the root file system has 200GB space on a normal installation and 190GB is uploaded, does the system freeze because it runs out of space when making copies from the uploads folder? This is specifically regarding a normal installation with no binds/mounts.

SSD/NVME limitations: All of these devices have limited reads/writes before the drive dies. It would make sense for uploads to not touch the root filesystem at all.

While I haven't used any external storage backends I'm going to make the assumption all of these issues also apply to them. External storage backends should have direct uploads - the files should not in my opinion be touching the root file system if uploading to an external mount.

**Comment by AndyScherzinger** [comment]
Even though closed right away transfered it to server since it is not based on the Android files app.

**Comment by Dragon988** [comment]
Haha yeah, didn't really think before posting it.

I mean the point still stands but brute forcing this stuff with a 10TB drive works fine.
