### ISSUE TITLE
Federation failed but never ends trying

### ISSUE THREAD

**Issue by pixel8383** [nextcloud/server#23619]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. I tried to send a federation request from an intranet nextcloud instance (not visible on the web) to another visible on the web
2. On the latter instance the federation request is received but fails for obviously reasons ("`[no app in context] Warning: Host nextcloud.home.local was not connected to because it violates local access rules`"
3. Nextcloud seems to be trying continuously to contact that remote instance fullfilling the logs with the error.

### Expected behaviour
One or more retry, then fails and stop trying.

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** nginx

**Database:** mysql 10.3.22

**PHP version:** 7.4.3

**Nextcloud version:** 19.04

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** latest.zip from nextcloud website

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by pixel8383** [comment]
Hello @szaimen yes, I do confirm the issue is still there with the latest release.

I have removed the federation app from my installation but Nextcloud is still trying to connect to the remote server.

`{"reqId":"xODCXDfg7179xwmIFjQc","level":2,"time":"2021-06-17T18:48:05+00:00","remoteAddr":"<my-ip>","user":"Emanuele","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/Emanuele/","message":"External storage not available: Sabre\\HTTP\\ClientException: Could not resolve host: nextcloud.home.local","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.2.1","id":"60cb99446fe0f"}`


`{"reqId":"xODCXDfg7179xwmIFjQc","level":2,"time":"2021-06-17T18:48:05+00:00","remoteAddr":"<my-ip>","user":"Emanuele","app":"no app in context","method":"PROPFIND","url":"/remote.php/dav/files/Emanuele/","message":{"Exception":"OCP\\Files\\StorageNotAvailableException","Message":"Sabre\\HTTP\\ClientException: Could not resolve host: nextcloud.home.local","Code":1,"Trace":[{"file":"/var/www/nextcloud/lib/private/Files/Storage/DAV.php","line":290,"function":"convertException","class":"OC\\Files\\Storage\\DAV","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/DAV.php","line":586,"function":"propfind","class":"OC\\Files\\Storage\\DAV","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Common.php","line":458,"function":"stat","class":"OC\\Files\\Storage\\DAV","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/External/Storage.php","line":191,"function":"test","class":"OC\\Files\\Storage\\Common","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":475,"function":"test","class":"OCA\\Files_Sharing\\External\\Storage","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php","line":70,"function":"test","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php","line":84,"function":"updateAvailability","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php","line":93,"function":"isAvailable","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Availability.php","line":442,"function":"checkAvailability","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php","line":581,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\Availability","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":115,"function":"getMetaData","class":"OC\\Files\\Storage\\Wrapper\\Wrapper","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/Cache/Scanner.php","line":153,"function":"getData","class":"OC\\Files\\Cache\\Scanner","type":"->"},{"file":"/var/www/nextcloud/apps/files_sharing/lib/External/Scanner.php","line":63,"function":"scanFile","class":"OC\\Files\\Cache\\Scanner","type":"->"},{"file":"/var/www/nextcloud/lib/private/Files/View.php","line":1490,"function":"scanFile","class":"OCA\\Files_Sharing\\External\\Scanner","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Directory.php","line":265,"function":"getDirectoryContent","class":"OC\\Files\\View","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/TagsPlugin.php","line":226,"function":"getChildren","class":"OCA\\DAV\\Connector\\Sabre\\Directory","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\TagsPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1052,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":984,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1646,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":346,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":472,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":253,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":321,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":332,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Files/Storage/DAV.php","Line":865,"Hint":"Storage is temporarily not available","CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:89.0) Gecko/20100101 Firefox/89.0","version":"21.0.2.1","id":"60cb99446fdff"}`

**Comment by szaimen** [comment]
Looks more like you have still an invalid external storage mount in your configuration. Could you try to disable the external storage app to see if that fixes the issue? Or is the app not enabled?

**Comment by pixel8383** [comment]
The federation app is disabled from months now.

**Comment by szaimen** [comment]
I am talking about the external storage app also called files_external app.

**Comment by szaimen** [comment]
Is this maybe the same issue?
https://github.com/nextcloud/server/issues/14797

**Comment by pixel8383** [comment]
This is the app list enabled right now on that installation:

Enabled:
  - accessibility: 1.7.0
  - activity: 2.14.3
  - bruteforcesettings: 2.1.0
  - cloud_federation_api: 1.4.0
  - contactsinteraction: 1.2.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - files_fulltextsearch: 21.0.2
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - fulltextsearch: 21.0.1
  - fulltextsearch_elasticsearch: 21.0.1
  - geoblocker: 0.5.0
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - news: 15.4.5
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - photos: 1.3.0
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - suspicious_login: 4.0.0
  - systemtags: 1.11.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0

**Comment by pixel8383** [comment]
> Is this maybe the same issue?
> #14797

Could be related, except I could not ever instaurate a federation with the remote server since the hostname is unresolved.

**Comment by szaimen** [comment]
After reading the other issue a bit more, I think the mentioned issue really quite similar so I'd recommend to close this one. There was also a workaround mentioned: https://github.com/nextcloud/server/issues/14797#issuecomment-576047668
