### ISSUE TITLE
Share multiselect overlapped on small screens

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#23617]
### Steps

1. Upload a picture
1. Open the details panel
1. Open the sharing tab
1. Reduce the window size so that the sharing tab has a scrollbar and uses less than 30% of the screen
1. Type some text in the field
1. Try to select something in the multiselect dropdown

### Expected result
Can select something.
And if not, at least a way to expand that panel or reduce the preview size to be able to see the panel better.

### Actual result
Multiselect dropdown is appearing behind the tabs so cannot see anything
<img width="379" alt="image" src="https://user-images.githubusercontent.com/277525/96840048-3ee0fe00-144a-11eb-84d1-32cd33564778.png">

I tried to quickly set z-index on the ".multiselect" element but that didn't help. Might need more advanced CSS engineering or even shifting DOM nodes.

### Versions
Observed on git master 872f03209cccd376c0be908581164f245e558070

In Nextcloud Talk 20 the dropdown appears correctly above, so this is a regression!

**Comment by PVince81** [comment]
- [ ] bisect regression
- [ ] check stable20

**Comment by PVince81** [comment]
I've bisected it but the result doesn't make sense. It points at a commit that doesn't contain any code related to the frontend: 6c1b542def8ba59306c4c539c0e56c0794389873

And yet, when I jump back on the previous commit, the autocomplete appears correctly.
And when I jump to that commit, the bug occurs.

Really weird...

**Comment by PVince81** [comment]
What?!

If I check out https://github.com/nextcloud/server/commit/6c1b542def8ba59306c4c539c0e56c0794389873 and revert the version.php from 21.0.0.1 to 21.0.0.0, the dropdown works again ?!

**Comment by PVince81** [comment]
Trying again without extra apps, just in case, and with production build

**Comment by PVince81** [comment]
Aha, after resetting the apps folder to what git provides, the error is gone.

So it means I had an app in there which CSS caused side effects. Hmmm... And maybe it got auto-enabled on 21.0.0.1 but not 21.0.0.0... Investigating...

**Comment by PVince81** [comment]
I had the photos app version 1.3.0 (git 63897ad6eb25cce805fe419eac161b97f9db21e9) in my apps folder.

For both version.php 21.0.0.0 or 21.0.0.1 the app gets auto-enabled, so it's not an auto-enable bug.

Now to find out why a CSS from an app would be different based on version.php...

**Comment by PVince81** [comment]
I updated the git code from the photos app, now sitting on e4b9123c7488fb2d1d17889f5e0f93d120038fa3
Now: if I only build from the server repo with `make dev-setup && make build-js`, I heard that it would also compile the scss from apps. => here the problem occurs.
However if I run `make dev-setup && make build-js` in the app's folder, then the problem disappears.

As an app dev I'd expect doing both of these operations to have the same effect ?
In general as an app dev I wouldn't expect the server repo to compile my app's assets.

@rullzer @skjnldsv

**Comment by PVince81** [comment]
closing as the css problem is gone, but might want a new issue to discuss the compiling bits

**Comment by skjnldsv** [comment]
> I heard that it would also compile the scss from apps. => here the problem occurs.

The only scss we have is https://github.com/nextcloud/photos/blob/master/css/icons.scss
Another thing is managed by webpack directly on photos. No interferences with the webpack build on server

**Comment by PVince81** [comment]
it's back:
<img width="265" alt="image" src="https://user-images.githubusercontent.com/277525/99533325-fa437680-29a5-11eb-8689-e731a46cf4d0.png">

and this time I have no photos app.

and I have the original code from master, no files compiled nor changed.

reopening to investigate further

**Comment by skjnldsv** [comment]
Shoudld be fixed with the `open-direction="below"` prop https://vue-multiselect.js.org/#sub-props

**Comment by PVince81** [comment]
I can try. However when a preview image is present, there might not be enough room to display it downwards.

In general I guess we should perhaps reduce the preview size on smaller screens (small dpi-wise, I have 1080p but with higher dpi so everything looks bigger)

**Comment by PVince81** [comment]
If I remove the overflow of the tab the dropdown appears again, but it messes up the scrollbars:
<img width="475" alt="image" src="https://user-images.githubusercontent.com/277525/99545741-ff102680-29b5-11eb-86be-2f7cfbaaf350.png">

**Comment by skjnldsv** [comment]
Of course :p
I mean, we don't do any height-responsiveness on Nextcloud at the moment, only width is being handled for mobile view.

I guess it's fine if we just set it to bottom for now

**Comment by PVince81** [comment]
okay, I had your branch checked out: https://github.com/nextcloud/nextcloud-vue/pull/1579

and locally added open direction and it looks better, but there's another unrelated issue which I guess you are working on already:
<img width="678" alt="image" src="https://user-images.githubusercontent.com/277525/99557393-eeb27880-29c2-11eb-87f4-cf22ac284c93.png">

I like that the multiselect adjusts to the remaining height.

Next steps:

- [ ] PR to nextcloud-vue to expose "open-direction"
- [ ] set open-direction in server

**Comment by PVince81** [comment]
The error disappeared when I switched to nextcloud-vue master.

- PR to forward the property: https://github.com/nextcloud/nextcloud-vue/pull/1581

**Comment by blizzz** [comment]
yesterday i've had it with a full screen window with master.

**Comment by PVince81** [comment]
still visible on stable21 5ec0132c17609231fb8ecf6c0bcb2b1c713e1ad5 (with no extra files)

![Uploading image.png…]()

**Comment by PVince81** [comment]
also happening with the 21.0.0RC1 release tarball

**Comment by PVince81** [comment]
I've tried https://github.com/nextcloud/server/pull/24694 (rebased onto master + recompiled), but it doesn't fix this issue.
So maybe it's not a boundary thing.

**Comment by PVince81** [comment]
a short in the dark: I tried updating nextcloud-vue to 3.5.4 but it also doesn't fix the issue either.

**Comment by PVince81** [comment]
I had a look deeper into vue-multiselect and it appears that the dropdown is always appended within the same container, not in the body. There is no option to make it use a different containment.

**Comment by PVince81** [comment]
Seems this is still on a TODO list for the next major vue-multiselect version: https://github.com/shentao/vue-multiselect/issues/618

I see some possible workarounds in that ticket

**Comment by PVince81** [comment]
okay, back to the old solution: setting the direction to "below".

I'll push a PR

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/25503
