### ISSUE TITLE
Dropdown on mobile missing text next to icons

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2362]
### Steps to reproduce
1. Create a public shared folder
2. Open link on mobile
3. Open the "..." menu

### Expected behaviour
`⬇️ Download`

### Actual behaviour
`⬇️ `

![bildschirmfoto vom 2016-11-28 09-56-09](https://cloud.githubusercontent.com/assets/213943/20661874/3979949c-b551-11e6-828d-2517065fb0f7.png)

Happens on both, 10 and 11 beta/master.

@jancborchardt @nextcloud/designers

**Comment by Espina2** [comment]
If you only have this option why don't only display them instead of having that two steps solution?

**Comment by eppfel** [comment]
Is there any other option than download? Otherwise I would really support @Espina2 proposal. The public pages need a redesign anyway 😅 For people, that never saw nextcloud, it is suboptimal.

The fix to show the wording again is in `mobile.css`:
Replace
```CSS
@media only screen and (max-width: 768px)
#fileList a.action span
```
with 
```css
@media only screen and (max-width: 768px)
#fileList a.action:not(.menuitem) span
```

**Comment by MorrisJobke** [comment]
Fix is in #2410

**Comment by MorrisJobke** [comment]
> If you only have this option why don't only display them instead of having that two steps solution?

see #1450

**Comment by jancborchardt** [comment]
@Espina2 the existing issue for that is https://github.com/nextcloud/server/issues/1450 :)
