### ISSUE TITLE
Add an option to set the default Dashboard image

### ISSUE THREAD

**Issue by lazerl0rd** [nextcloud/server#23631]
I think it would be great to be able adjust the default background of Dashboard for new users. In my case, I think it looks great just set to the default colour, but of course different administrators would vary on that.

![image](https://user-images.githubusercontent.com/24303423/96877246-52538f80-1471-11eb-83a2-7e64089c277b.png)

I believe an option would be quite useful especially for companies, schools, and other uses where Nextcloud is to be branded. This could help them buy allowing the Dashboard to have a branded background image (as they're likely not going to see the login page much).

A possible extension is to also deny the changing of Dashboard's background in the case where branding is necessary (is it ever, though).

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I take it that we love the `config.php` file here and well, since Dashbaord merged into server recently it seems fair enough to place the option there.

**Describe alternatives you've considered**
I don't think adjusting it for every user is a fair alternative.

**Additional context**
Maybe defaulting to the background colour would also be preferred over the "clouds" image that is currently the default.

**Comment by kesselb** [comment]
Search ;)

**Comment by lazerl0rd** [comment]
My apologies, I completeley missed #23558.
