### ISSUE TITLE
Image viewer not working when Theming app is disabled

### ISSUE THREAD

**Issue by adaigre** [nextcloud/server#23644]
Hi there !

Since I updated to NC 20, I can't open images anymore. When I click on a image (from Files or Gallery app), the loading animation never ends.

In the browser DevTools, I've got this in the console :
```
Viewer.vue:458 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at a.updateTitle (Viewer.vue:458)
    at Viewer.vue:336
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at ae (viewer-main.js?v=fc2531de:403)
    at a (viewer-main.js?v=fc2531de:403)
    at viewer-main.js?v=fc2531de:403
    at new Promise (<anonymous>)
    at viewer-main.js?v=fc2531de:403
```
```
updateTitle(fileName) {
	document.title = `${fileName} - ${OCA.Theming.name}`
},
```

Because it seems to be related to the theming app, I re-enabled her and the image viewer is now working.

### Steps to reproduce
1. Open an image from the file or gallery app

### Expected behaviour
The image viewer should show the image

### Actual behaviour
The loading animation never ends

### Server configuration

**Operating system:** Official Docker image

**Database:** PostgreSQL

**Nextcloud version:** 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19.x

**Where did you install Nextcloud from:** Docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - admin_audit: 1.10.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - photos: 1.2.0
  - previewgenerator: 3.0.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - text: 3.1.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.0.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - dashboard
  - encryption
  - firstrunwizard
  - password_policy
  - recommendations
  - support
  - survey_client
  - systemtags
  - theming
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium 86.0.4240.111

**Operating system:** ArchLinux

#### Browser log
<details>
<summary>Browser log</summary>

```
Viewer.vue:458 Uncaught (in promise) TypeError: Cannot read property 'name' of undefined
    at a.updateTitle (Viewer.vue:458)
    at Viewer.vue:336
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at ae (viewer-main.js?v=fc2531de:403)
    at a (viewer-main.js?v=fc2531de:403)
    at viewer-main.js?v=fc2531de:403
    at new Promise (<anonymous>)
    at viewer-main.js?v=fc2531de:403

```
</details>

**Comment by kesselb** [comment]
![Peek 2020-10-23 14-10](https://user-images.githubusercontent.com/3902676/97001922-7bd7ee00-1539-11eb-8170-eba254e3f40b.gif)
