### ISSUE TITLE
Readme.md is created when create file is aborted

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#23668]
### Steps to reproduce
1. open files app and select a folder without Readme.md file
2. top of page, select the plus-button and "create new textfile"
3. instead of editing the filename, click outside the popup

### Expected behaviour
create file operation is aborted

### Actual behaviour
an empty Readme.md is created

### Server configuration
**  Operating system: 
Linux
** Web server:
Apache2
** PHP version:
7.3
** Nextcloud version: (see Nextcloud admin page)
20.0.1
** Updated from an older Nextcloud/ownCloud or fresh install:
upgrade from 19.0.4
** Where did you install Nextcloud from:
tar.bz2

**Comment by kesselb** [comment]
That's the expected behaviour. You probably clicked inside the rich workspace area.

**Comment by schaarsc** [comment]
@kesselb thank you for your comment. I was not aware of this behavior.
