### ISSUE TITLE
weather widget ignores has_internet_connection

### ISSUE THREAD

**Issue by schaarsc** [nextcloud/server#23667]
### Steps to reproduce
1. enable and configure weather widget in dashboard
2. set has_internet_connection => false
3. open dashboard

### Expected behaviour
weather should report "administrator has disabled internet access"

### Actual behaviour
weather server is contacted

### Server configuration

**Operating system:**
Linux
**Web server:**
Apache2
**PHP version:**
7.3
**Nextcloud version:** (see Nextcloud admin page)
20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:**
upgrade from 19.0.4
**Where did you install Nextcloud from:**
tar.bz2

**Comment by kesselb** [comment]
cc @MorrisJobke @eneiluj what do you think about this one? 

https://github.com/nextcloud/server/search?q=has_internet_connection we have a lot of code already to check if a connection is allowed. The quick solution for this issue is to add a similar check to the weather service but still a lot of apps do not respect this configuration flag.

**Comment by MorrisJobke** [comment]
> Is that a check the HttpClient should do and could we integrate such a check in a non breaking way?

This makes most sense IMO ... initially the setting was there to indicate the missing connection to the required requests (appstore, update, etc), but it makes sense to respect them also in apps and try to enforce it as often as possible.

**Comment by MorrisJobke** [comment]
cc @rullzer @ChristophWurst

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
