### ISSUE TITLE
Internal folder and file share with better workflow

### ISSUE THREAD

**Issue by hoergen** [nextcloud/server#23672]
When you share a file or folder to another user I would love to see the following features (I'm working with 19.0.4)

1. You can submit with a share a note e.g. an explanation why you share this file/folder
2. The recipient can reject the shared file/folder e.g. he is the wrong recipient, because of the same name or the sender just clicked the wrong name. Or the wrong file/folder was shared. So you avoid an avoidable communication. 
3. When you reject a file, you have to enter a reason (note) why you reject (for documentation reasons) 
4. As a system administrator it would be nice, if you could configure default folder name (like "Shared with me") in the root directory of a user, where such folders are arriving. Instead in the root directory currently.
5. Additionally could it be very helpful, if files are not only stored in the configured default folder, it would be very helpfull if they are appearing in a subfolder with the name of the "sender" or the "project" it comes from. Consider someone gets from 10 People the same hour several files and folders shared. This could save a lot time and keep this process transparent
6. Maybe an option where the administrator could allow the normal user, to change the folder name (like "Shared with me") to something a user is more comfortable with.
7. I could imagine that in huge environments or projects there could even be a need to establish a workflow according to subprojects or time ranges or some other work conditions.

**Comment by szaimen** [comment]
Hi, thanks for your ideas!

> * You can submit with a share a note e.g. an explanation why you share this file/folder

This is possible:
![image](https://user-images.githubusercontent.com/42591237/122439542-058e6d00-cf9c-11eb-948b-05930556082a.png)

> * The recipient can reject the shared file/folder e.g. he is the wrong recipient, because of the same name or the sender just clicked the wrong name. Or the wrong file/folder was shared. So you avoid an avoidable communication.

This is also possible:
![image](https://user-images.githubusercontent.com/42591237/122439680-26ef5900-cf9c-11eb-81b0-d1286a41c018.png)

> * When you reject a file, you have to enter a reason (note) why you reject (for documentation reasons)

This is not on the roadmap.

> * As a system administrator it would be nice, if you could configure default folder name (like "Shared with me") in the root directory of a user, where such folders are arriving. Instead in the root directory currently.

This is possible:
![image](https://user-images.githubusercontent.com/42591237/122439850-4be3cc00-cf9c-11eb-8ab0-aabe7a673965.png)

> * Additionally could it be very helpful, if files are not only stored in the configured default folder, it would be very helpfull if they are appearing in a subfolder with the name of the "sender" or the "project" it comes from. Consider someone gets from 10 People the same hour several files and folders shared. This could save a lot time and keep this process transparent

Please use the groupfolders app for this: 
https://apps.nextcloud.com/apps/groupfolders

> * Maybe an option where the administrator could allow the normal user, to change the folder name (like "Shared with me") to something a user is more comfortable with.

This is not on the roadmap

> * I could imagine that in huge environments or projects there could even be a need to establish a workflow according to subprojects or time ranges or some other work conditions.

Maybe something like workflows?
https://nextcloud.com/workflow/
