### ISSUE TITLE
Sharing link generates Error "Fehler beim Erstellen der Freigabe" (sorry for not using the english translation)

### ISSUE THREAD

**Issue by jgrete** [nextcloud/server#23674]
**Steps to reproduce:**
Try to share directory or file via Share Link
Be sure to check "Always ask for password" in section Administration/sharing. The error disappears if this option is unchecked!

**Expected behaviour:**
when sharing directories or files the user always is asked to enter a password

**Actual behaviour**
a very unspecific error message says "Fehler beim Erstellen der Freigabe", no sharing occurs
uncheck "Always ask for password" in section Administration/sharing and sharing is working again

**Server configuration detail**
Operating system: Linux 5.3.18-lp152.44-default #1 SMP Wed Sep 30 18:51:43 UTC 2020 (914f31e) x86_64
Webserver: Apache (apache2handler)
Database: mysql 10.4.14
PHP version: 7.4.6
Modules loaded: Core, date, libxml, pcre, filter, hash, Reflection, SPL, session, SimpleXML, standard, xml, mysqlnd, apache2handler, bcmath, ctype, curl, dom, fileinfo, gd, gmp, iconv, imagick, intl, json, mbstring, mysqli, openssl, pcntl, PDO, pdo_mysql, pdo_sqlite, posix, redis, sqlite3, tokenizer, xmlreader, xmlwriter, zip, zlib, Zend OPcache

Nextcloud version: 19.0.4 - 19.0.4.2
Updated from an older Nextcloud/ownCloud or fresh install: updated form 19.0.2
Where did you install Nextcloud from: update
Signing status: Array
(
)

List of activated apps:  - spreed: 9.0.4
 - support: 1.2.1
 - survey_client: 1.7.0
 - systemtags: 1.9.0
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - twofactor_webauthn: 0.2.5
 - updatenotification: 1.9.0
 - user_usage_report: 1.3.3
 - viewer: 1.3.0
 - w2g2: 3.0.3
 - workflowengine: 2.1.0
Disabled:
 - dropit
 - encryption
 - files_accesscontrol
 - files_fulltextsearch_tesseract
 - files_readmemd
 - maps
 - sharepoint
 - sharerenamer
 - user_ldap
 - workflow_pdf_converter
 - workflow_script

Configuration (config/config.php): {
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "cloud.xxxx.yy",
        "194.aa.bb.cc",
        "localhost",
        "127.0.0.1",
        "192.xx.yy.zz"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/cloud.xxxxxxxxxxx",
    "dbtype": "mysql",
    "version": "19.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "dbdriveroptions": {
        "1002": "SET wait_timeout = 28800"
    },
    "log_type": "owncloud",
    "logfile": "\/srv\/oc_data\/owncloud.log",
    "loglevel": "2",
    "syslog_tag": "Owncloud",
    "logtimezone": "Europe\/Berlin",
    "cron_log": false,
    "log_rotate_size": 10485760,
    "installed": true,
    "maintenance": false,
    "theme": "",
    "skeletondirectory": "",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_sendmailmode": "pipe",
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "default_language": "de_DE",
    "trashbin_retention_obligation": "auto, 30",
    "trashbin_auto_expire": true,
    "updatechecker": false,
    "enable_certificate_management": true,
    "htaccess.RewriteBase": "\/owncloud",
    "filelocking.enabled": true,
    "updater.release.channel": "stable",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\Epub",
        "OC\\Preview\\FB2",
        "OC\\Preview\\PDF",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007"
    ],
    "filesystem_check_changes": 1,
    "app_install_overwrite": [
        "apporder",
        "spreed",
        "occweb"
    ],
    "mysql.utf8mb4": true,
    "config_is_read_only": true
}
Are you using external storage, if yes which one: no
Are you using encryption: no
Are you using an external user-backend, if yes which one : no

**Client configuration**
Browser: many different
Operating system: Linux, Windows 10, MacOs

**Logs**
Web server error log:
No error entries related to this event.

Only a couple of lines in access_log:
a.b.c.d - - [25/Oct/2020:04:40:36 +0100] "GET /owncloud/ocs/v2.phpud/ocsapp/apps/password_policy/api/v1/generate HTTP/1.1" 302 -
a.b.c.d - - [25/Oct/2020:04:40:37 +0100] "GET /owncloud/apps/files/ HTTP/1.1" 200 77388
a.b.c.d - - [25/Oct/2020:04:40:37 +0100] "POST /owncloud/ocs/v2.php/apps/files_sharing/api/v1/shares HTTP/1.1" 403 128
a.b.c.d - - [25/Oct/2020:04:40:38 +0100] "POST /owncloud/apps/text/session/sync HTTP/1.1" 200 351
a.b.c.d - - [25/Oct/2020:04:40:43 +0100] "POST /owncloud/apps/text/session/sync HTTP/1.1" 200 351

Nextcloud log 
no entries except that the admin impersonates a user to produce this error case.
The error w as reproduced by other users also

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
