### ISSUE TITLE
Files External is unable to show the user's list and restrict shares

### ISSUE THREAD

**Issue by gigidsss** [nextcloud/server#23673]
### Server configuration

**Operating system:** Raspabian 10

**Web server:** Apache 2

**Database:** MariaDB

**PHP version:** 7.3

**Nextcloud version:** 20.00

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

Hi,

When I created a new mount, I had the possibility to select how many users was able to access to the new mount, but now, when I write my username, the entry still blank (for any users in my groups and others).

Here are the screenshots:
[https://cloud.doussis.be/s/FbRyPYPf9q2d9g9](https://cloud.doussis.be/s/FbRyPYPf9q2d9g9)

Sincerly Yours,

**Comment by argonimos** [comment]
I have got the same error under the following config:
Operating system: FreeBSD

Web server: NGINX

Database: MariaDB

PHP version: 7.3

Nextcloud version: 20.00

Updated from an older Nextcloud/ownCloud or fresh install: fresh install

Whenever I try to change the users or groups a mount is visible to, the entry turns blank whenever I enter a valid username but displays "No matches found" when I type something that does not relate to any username or group.   

Screenshots:
![Screenshot 2](https://user-images.githubusercontent.com/68082834/97103022-6b935080-16aa-11eb-93c5-9c03fe0773bf.PNG)
![Screenshot 1](https://user-images.githubusercontent.com/68082834/97103025-6cc47d80-16aa-11eb-8c95-6e6ffbb158a2.PNG)

With best regards

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/97105015-7f45b380-16b8-11eb-997b-321179e13396.png)
