### ISSUE TITLE
Error when deleting a user from a group via the web interface

### ISSUE THREAD

**Issue by pkmkrishnakumar** [nextcloud/server#23682]
### Steps to reproduce
1. Fresh Nextcloud Install
2. Created a user1 and created two groups namely group1 and group2
3. Added the user1 to group1 and group2
4. Saved
5. Now edit user and trying to remove user from group1 or group2
6. Both doesn't work 

### Expected behaviour
remove user from the group which is been selected

### Actual behaviour
Performing the Task with Browser:
Error: An error occured during the request. Unable to proceed.

Works with performing task with occ:
sudo -u www-data php occ group:removeuser group1 user1

Error in Log: 

Exception: Argument 2 passed to OCA\Provisioning_API\Controller\UsersController::removeFromGroup() must be of the type string, null given, called in /var/www/html/lib/private/AppFramework/Http/Dispatcher.php on line 169

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache2

**Database:** Mysql 

**PHP version:** php7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** FRESH INSTALL

**Where did you install Nextcloud from:** nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```

**List of activated apps:**
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.1
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.5
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap


**Nextcloud configuration:**
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.159.138"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.0.9",
        "overwrite.cli.url": "http:\/\/192.168.159.138",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true
    }
}

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:**  NO

**Comment by kesselb** [comment]
![image](https://user-images.githubusercontent.com/3902676/97117234-9ad5ac00-1702-11eb-927c-3d6b0ebc3d58.png)

**Comment by kesselb** [comment]
Duplicate of #23237
