### ISSUE TITLE
Oracle DB query error when upgrading from NC 18 to 19

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/server#23698]
When upgrading from Nextcloud 18 to 19 via `occ upgrade`, a `Doctrine\DBAL\Exception\DriverException` is raised when renaming an index. Main message is:
```
An exception occurred while executing 'ALTER INDEX bin$shtdhcx0rjhguwbjte1tpw==$0 RENAME TO share_id_index':\n\nORA-02243: Ung\u00fcltige ALTER INDEX- oder ALTER MATERIALIZED VIEW-Option
```

Here is the full log line: 
[oracle-upgrade.log](https://github.com/nextcloud/server/files/5440254/oracle-upgrade.log)

@nickvergessen Could it be caused by an encoding problem? Any clue about this?

**Comment by nickvergessen** [comment]
Well we don't have anything encoding worthy in the db structure.
Also the main issue seems to be the temporary name `bin$shtdhcx0rjhguwbjte1tpw==$0` and I'm not even sure where this is coming from.

**Comment by ChristophWurst** [comment]
> Ung\u00fcltige

It's the localized Oracle error. It's not about encoding.

**Comment by ChristophWurst** [comment]
I'm pretty sure this is caused by https://github.com/nextcloud/server/blob/7e6f04490e286450d009c156f08de6a22f0f653d/apps/federatedfilesharing/lib/Migration/Version1010Date20200630191755.php#L55

**Comment by eneiluj** [comment]
So would you suggest to try upgrading with this commented? Or will it cause further problems if the index is not there?

**Comment by ChristophWurst** [comment]
It will most likely. Either with an error (we can't ensure that column is unique) or with a performance penalty (lookups might be slower).

**Comment by ChristophWurst** [comment]
Wait a min. The migration is brand new. The code with the problems is https://github.com/nextcloud/server/blob/238435f9b56803b226704e3ea9e37cf5931c61bb/apps/federatedfilesharing/appinfo/database.xml#L31-L38. So that uses the old migration system.

**Comment by nickvergessen** [comment]
But it also has a name there, and it's the same on 18 and 19:
https://github.com/nextcloud/server/blob/stable18/apps/federatedfilesharing/appinfo/database.xml
https://github.com/nextcloud/server/blob/stable19/apps/federatedfilesharing/appinfo/database.xml

**Comment by nickvergessen** [comment]
I guess someone should add a debug step here https://github.com/nextcloud/3rdparty/blob/186e68124ad258b3612408e63b42b2045264b2f2/doctrine/dbal/lib/Doctrine/DBAL/Platforms/OraclePlatform.php#L932-L940
And then reverse up the tree to see if the table is created with a wrong name in the beginning.

**Comment by eneiluj** [comment]
Here is some feedback from someone comfortable with Oracle databases:

> ALTER INDEX bin$shtdhcx0rjhguwbjte1tpw= - the table with this index has been removed and is in the trash. Maybe the trash must be deleted before applying the new version. The objects with "bin" at the beginning are in the trash/bin elements and can not be used in a select, alter, insert etc.

Sounds helpful?

**Comment by szaimen** [comment]
I suppose this is still valid?
