### ISSUE TITLE
Update is failing in web-updater: InvalidArgumentException while Update

### ISSUE THREAD

**Issue by kathoefer** [nextcloud/server#23707]
Hello community,

The web-updater fails, gives me an error message and sends me to the community:
"InvalidArgumentException: Column name "nc_9349_flow_operations"."entity" is NotNull, but has empty string or null as default."

I don´t know how to enter my nextcloud again. Another nextcloud (same webhosting) went through almost at the same time.

Thank you for your help and great afford! 
Patrick

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/23174
