### ISSUE TITLE
Use ICrypto within class

### ISSUE THREAD

**Issue by alve89** [nextcloud/server#2370]
I try to use the method encrypt() of ICrypto to store a password after logging users in. 
My problem is not really a nextcloud but a PHP thing but this problem belongs to nextcloud.

How can I use the method?!

My class uses this:

```
use \OC_DB;
use OCP\Security\ICrypto;
abstract class Base extends \OC_User_Backend {
	protected $backend = '';
	public function __construct($backend) {
		$this->backend = $backend;
	}
}
```
I searched within this repo and within apps but the only thing I found was 
```
	public function __construct($backend, ICrypto $crypto) {
		$this->backend = $backend;
                $this->crypto = $crypto;
	}
```

I'm really consfused and appreciate any hints - many thanks in advance!

**Comment by nickvergessen** [comment]
For writing apps please search and ask for help in the forums or on IRC: https://nextcloud.com/support/
