### ISSUE TITLE
[NC20] The old server-side-encryption format is enabled

### ISSUE THREAD

**Issue by MeCias** [nextcloud/server#23704]
Hi,

I get following since NC 20 (20.0.1) under Setup and setup warnings

> The old server-side-encryption format is enabled. We recommend disabling this. For more details see the [documentation](https://docs.nextcloud.com/server/12/go.php?to=admin-sse-legacy-format).

The link to the documentation does not help neither the search within the documentation.

What do I have to disable and where can I find it? In Nextcloud or on my provider side?

Not sure what to provide from the log files, there is a lot but nothing that seems to be relevant.

**Comment by kesselb** [comment]
Link to documentation is correct on my setup: https://docs.nextcloud.com/server/20/admin_manual/configuration_files/encryption_migration.html?highlight=format%20old

**Comment by MeCias** [comment]
Thx

That was the clue I am looking for.

Not sure why mine is pointing to 

https://docs.nextcloud.com/server/12/go.php?to=admin-sse-legacy-format

I have to check where that is coming from

**Comment by kesselb** [comment]
> have to check where that is coming from

A custom theme may overwrite the documentation url.

**Comment by Pushergene** [comment]
Would it safer to decrypt:all and reinstall encryption module to prevent data loss ?

**Comment by CodeAlDente** [comment]
Why even disabling it? Doesn't really sound like a good idea to weaken security and privacy matters.

**Comment by mirko** [comment]
For me the link to the docs (from the warning) also directed me to the wrong docs while no custom theme is instaled.

What also doesn't help here is that
https://docs.nextcloud.com/server/20/admin_manual/configuration_files/encryption_migration.html
as well as
https://docs.nextcloud.com/server/21/admin_manual/configuration_files/encryption_migration.html
state the solution would be the command
`occ encryption:scan:legacy-format`
while for v20.x as well as v21.x I get:

> $ sudo -u nc php /data/nextcloud/occ encryption:scan:legacy-format
> Nextcloud is in maintenance mode - no apps have been loaded
>   There are no commands defined in the "encryption:scan" namespace.  
>                                                                      
>   Did you mean this?                                                 
>       encryption

**Comment by mirko** [comment]
I'm on version v21.0.4 now, still have the warning, still get above "command not defined" error and when calling `encryption:status` I get:

> $ sudo -u nc php /data/nextcloud/occ encryption:status
>   - enabled: false
>   - defaultModule: OC_DEFAULT_MODULE
which seems mutually exclusive to the warning in the webinterface (that (old-style) sse is enabled)
