### ISSUE TITLE
Not able to use the request token for the WebDAV operations on Nextcloud

### ISSUE THREAD

**Issue by rohnitVizexperts** [nextcloud/server#23717]
My current setup-
Nextcloud Version: 18.0.4.1
Database: mySQL
Php: 7.2.31
System: Ubuntu Subsystem 18.04.1 in windows

I am currently using Node.js to perform WebDAV related operations on nextcloud. All of the operations are working absolutely fine. But, the problem is that I am using username and password to perform these operations and for the users to use this would not be secure at all. I want it to be done through tokens(preferably JWT) to make it safe for the other users, who will be using it.

I tried it using the OC.requestToken, but no success in it. 

Is there a way to implement this thing, keeping in mind the security of the users?

Thanks in advance!

**Comment by kesselb** [comment]
It's good to see that people add support for Nextcloud to their applications - Thanks for that :+1: 

![image](https://user-images.githubusercontent.com/3902676/97314053-97a80080-1867-11eb-9a41-deee1f0446c5.png)

But the issue tracker is not a support channel :exclamation: Your comment is not a bug report, not a feature request and not a security vulnerability. It's a question for https://help.nextcloud.com/c/dev/11. Please ask your next question there.

I guess you are looking for app passwords:

- https://docs.nextcloud.com/server/20/developer_manual/client_apis/LoginFlow/index.html#login-flow-v2 how to obtain a app password.
https://docs.nextcloud.com/server/20/user_manual/en/session_management.html#managing-devices app passwords from a user perspective.

**Comment by kesselb** [comment]
As reference: https://help.nextcloud.com/t/not-able-to-use-the-request-token-for-the-webdav-operations-on-nextcloud/96337

It seems the poster already asked the question there and decided to post it here a second time (or the other way around). 

For anyone else: If you are a developer and looking for help to integrate your application with Nextcloud please use https://help.nextcloud.com/c/dev/11.

**Comment by rohnitVizexperts** [comment]
@kesselb Sorry for posting this question here. I did so because earlier I asked two questions on that platform and didn't get any response on those. So, this time I thought that I could ask it here as well. But, I was happy to see someone reply on the post: https://help.nextcloud.com/t/not-able-to-use-the-request-token-for-the-webdav-operations-on-nextcloud/96337 .

Now, that you made me aware of it and getting a reply on help.nextcloud.com, I may continue using help.nextcloud.com

By the way, thanks for your help mate.
