### ISSUE TITLE
No files shown when connected to NC 20.0.0.9 with LDAP user

### ISSUE THREAD

**Issue by patit72** [nextcloud/server#23716]
### Steps to reproduce
connect account to NC 20.0 installation user with LDAP backend --> No file here shows in app
Normal user (internal db) works fine.
iOS app works fine
Same app connected on NC 19 shows files correctly.

### Environment data
Android version: 10

Device model: Xiaomi Mi8

Stock or customized system: customized

Nextcloud app version: 3.13.1

Nextcloud server version: 20.0.0.9

Reverse proxy:

#### Web server error log

Insert your webserver log here
```

#### Nextcloud log (data/nextcloud.log)
```

{"reqId":"BEsK2MjzljIZ1TyEiFFu","level":4,"time":"2020-10-21T11:18:08+02:00","remoteAddr":"192.168.96.254","user":"3D58B46B-4511-4A10-85D7-7646419FE73B","app":"webdav","method":"PROPFIND","url":"/remote.php/webdav/","message":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\Group\\Manager::getUserGroupIds() must implement interface OCP\\IUser, null given, called in /var/www/nextcloud/lib/private/Share20/DefaultShareProvider.php on line 884","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Share20/DefaultShareProvider.php","line":884,"function":"getUserGroupIds","class":"OC\\Group\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Share20/Manager.php","line":1333,"function":"getSharedWith","class":"OC\\Share20\\DefaultShareProvider","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/Node.php","line":323,"function":"getSharedWith","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php","line":372,"function":"getNoteFromShare","class":"OCA\\DAV\\Connector\\Sabre\\Node","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/PropFind.php","line":96,"function":"OCA\\DAV\\Connector\\Sabre\\{closure}","class":"OCA\\DAV\\Connector\\Sabre\\FilesPlugin","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/apps/dav/lib/Connector/Sabre/FilesPlugin.php","line":374,"function":"handle","class":"Sabre\\DAV\\PropFind","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"handleGetProperties","class":"OCA\\DAV\\Connector\\Sabre\\FilesPlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1063,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":989,"function":"getPropertiesByNode","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1678,"function":"getPropertiesIteratorForPath","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":1661,"function":"writeMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":363,"function":"generateMultiStatus","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpPropFind","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php","line":84,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Group/Manager.php","Line":325,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Android) Nextcloud-android/3.13.1","version":"20.0.0.9"}

```
**NOTE:** Be super sure to remove sensitive data like passwords, note that everybody can look here! You can use the Issue Template application to prefill some of the required information: https://apps.nextcloud.com/apps/issuetemplate

**Comment by kesselb** [comment]
Closing in favour of #23355
