### ISSUE TITLE
Sharing by Link with "Force password protection" enabled / selecting "allow Editing" not possible

### ISSUE THREAD

**Issue by devdracon** [nextcloud/server#23748]
Hey, i have the following behavior with my installation:

Nextcloud version (eg, 18.0.2): 19.04
PHP version (eg, 7.1): 7.3

The issue you are facing:

when i share a document by link and want to allow editing, this function cannot be activated
prerequisite: the Option “Force password protection” is selected

Is this the first time you’ve seen this error? (Y/N): Y

Steps to replicate it:

    create a document
    share by link
    check “allow editing”
    close detail box
    revisit sharing details
    “allow editing” is unchecked

i have analyzed the problem further and it appears under the following constellation:

    at “Settings” -> “Share” -> “Force password protection” is selected
    if you want to share the document by link, the editing mode cannot be activated

Workaround:

Remove setting to 1) and set password protection when creating a share

Then it is also possible to edit the document

I tested this bevavior on 2 different instances and i could reproduce this even on a new, clean installation with Version 19.0.4

**Comment by ochealaaf** [comment]
Same behaviour on NC version 20.0.1, editing documents of linked shares  - for instance markdown files or libreoffice files in collabora - is not possible.

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

**Comment by szaimen** [comment]
cc @nextcloud/sharing

**Comment by yoyoyonas** [comment]
I have this bug without having "Enforce password protection" enabled on NC 21.0.4.

**Comment by yoyoyonas** [comment]
Just tested on NC 22.1.1; same Problem: The `PUT` request from checking "allow editing" returns a 400 bad request. 

Nextcloud log:

> {"reqId":"$reqId","level":0,"time":"2021-09-20T19:30:22+00:00","remoteAddr":"$remoteAddr","user":"$user","app":"files_sharing","method":"PUT","url":"/nc/ocs/v2.php/apps/files_sharing/api/v1/shares/135","message":"/appinfo/app.php is deprecated, use \\OCP\\AppFramework\\Bootstrap\\IBootstrap on the application class instead.","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:92.0) Gecko/20100101 Firefox/92.0","version":"22.1.1.2"}

I'm using Nginx.

**Comment by meonkeys** [comment]
I'm seeing something that seems related in nextcloud v22.2.3. I share a file then later try to click "Allow editing", then I get an error notifiction: "Error updating the share: Cannot increase permissions of " (that's verbatim... the message ends mid-sentence) and I see a 404 error in the Javascript console like this: https://github.com/nextcloud/server/issues/27962#issuecomment-894824159

**Comment by yoyoyonas** [comment]
For me, this issue was resolved with NC 24 (or some dot release of 24).

**Comment by devdracon** [comment]
Hi, I can confirm that with the current version (25.0.3) the error is fixed.

**Comment by szaimen** [comment]
Thanks for verifying!
