### ISSUE TITLE
Unable to upload new profile picture

### ISSUE THREAD

**Issue by hardwareadictos** [nextcloud/server#23754]
Hey, good morning.

I get a "invalid image" message when uploading a new profile picture into my nextcloud user accounts. I get this on nextcloud.log:

{"reqId":"RudqdNED5RSWAixwyawF","level":3,"time":"2020-10-28T13:40:54+00:00","remoteAddr":"192.168.192.15","user":"Daniel","app":"PHP","method":"POST","url":"/avatar/","message":{"Exception":"Error","Message":"file_put_contents(/data/Daniel/cache/avatar_upload.mPOQpGyZHpulrgqN.part): failed to open stream: Permission denied at /config/www/nextcloud/lib/private/Files/Storage/Local.php#277"

Thanks in advance for the help :)

**Comment by skjnldsv** [comment]
Hey, please follow the issue template.
