### ISSUE TITLE
Cannot accept or decline federated share after dismissing notification

### ISSUE THREAD

**Issue by michaelkuhn** [nextcloud/server#23769]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Share a file with a remote user
2. Dismiss notification in the remote Nextcloud instance without clicking "accept" or "decline"
3. Cannot accept or dismiss external share anymore

### Expected behaviour

The pending external share should be shown somewhere, for instance, in "Pending shares".

### Actual behaviour

The pending external share is nowhere to be found. The entry in the `oc_share_external` table still exists, though.

### Server configuration

**Operating system:** Fedora 32

**Web server:** Apache 2.4.46

**Database:** PostgreSQL 12.4

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from Nextcloud 19.x

**Where did you install Nextcloud from:** Installed manually using tarballs.

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration

**Browser:** Chrome 86

**Operating system:** Fedora 32

#### Web server error log

<details>
<summary>Web server error log</summary>
Nothing relevant in the logs.
</details>

#### Nextcloud log (data/nextcloud.log)

<details>
<summary>Nextcloud log</summary>
Nothing relevant in the logs.
</details>

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by PVince81** [comment]
still happening in NC 21.0.3

I have the feeling that this hasn't been implemented yet

**Comment by PVince81** [comment]
it seems there's already a backend endpoint for it: https://github.com/nextcloud/server/blob/master/apps/files_sharing/appinfo/routes.php#L171

a quick grep didn't show any results in frontend code, so probably the frontend bits are missing

**Comment by PVince81** [comment]
PR here to add the missing frontend bits: https://github.com/nextcloud/server/pull/27751

**Comment by PVince81** [comment]
what I thought would be a straightforward quick addition turns out to be a can of worms: remote group share handling had many bugs
