### ISSUE TITLE
innodb_large_prefix is deprecated since MySQL 5.7.7

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2377]
This setting is required for the 4-byte support: https://docs.nextcloud.com/server/11/admin_manual/maintenance/mysql_4byte_support.html

The setting was changed to be default enabled in 5.7.7 and at the same time it was deprecated: http://dev.mysql.com/doc/refman/5.7/en/innodb-parameters.html#sysvar_innodb_large_prefix

> innodb_large_prefix is deprecated in MySQL 5.7.7 and will be removed in a future release. innodb_large_prefix was introduced in MySQL 5.5 to disable large index key prefixes for compatibility with earlier versions of InnoDB that do not support large index key prefixes. 

I'm not sure what that means. I hope it means you simply can't control it anymore, but it remains enabled? From my understanding yes. Otherwise the experimental MySQL 4byte support is already at an end, before it started working.

Want to be sure on this, before we ship this nice stuff and then it breaks with the next MySQL major release.

cc @blizzz @LukasReschke  @MorrisJobke

**Comment by blizzz** [comment]
I got confirmation on IRC (#msql on freenode) from Naktibalda that this will be basically force-enabled. Behaviour stays, switch goes.
