### ISSUE TITLE
UserCreatedEvent emitted twice when creating user via user management webui

### ISSUE THREAD

**Issue by ecsecta** [nextcloud/server#23797]
When creating a user account via the user management web ui, the '\OCP\User\Events\UserCreatedEvent' is emitted twice.

### Steps to reproduce
1. Create a listener for the '\OCP\User\Events\UserCreatedEvent' event and let it log or do something
2. Create a user via the user management webui
3. See the handle function of the listener is called twice

### Expected behaviour
'\OCP\User\Events\UserCreatedEvent' should be emitted once only.

### Actual behaviour
'\OCP\User\Events\UserCreatedEvent' is emitted twice.

### Server configuration
Tested in official docker based Nextcloud 19.0.4 and 20.0.1 

I think this causes the behaviour:
* Emit Hook and Event in UserManager:
https://github.com/nextcloud/server/blob/f94af85749f1c98564c7b4f503a13309a24595fb/lib/private/User/Manager.php#L375-L378
* React on Hook and emit Event a second time:
https://github.com/nextcloud/server/blob/f94af85749f1c98564c7b4f503a13309a24595fb/lib/private/Server.php#L539-L546

If commenting L544-L545of Server.php the listener is only triggerd once.

**Comment by kesselb** [comment]
cc @ChristophWurst @MorrisJobke

**Comment by ChristophWurst** [comment]
> If commenting L544-L545of Server.php the listener is only triggerd once.

Yep, I guess the latter translation of the hook to the event is the reason for the duplication. If the user manager already emits, there really is no reason to do this translation. Mind sending a PR that removes those lines?

**Comment by ecsecta** [comment]
Done
