### ISSUE TITLE
Mail notification - limit number of duplicated items

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/server#23802]
I enabled mail notifications and when I modify note, I see a lot of the same items
For example:

Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt
Yesterday at 7:16 PM
You changed Notes/New note.txt

Please add one item (per minute) with number of items
For example

Yesterday at 7:16 PM
You changed Notes/New note.txt (20x)
Yesterday at 7:17 PM
You changed Notes/New note.txt (5x)

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?

**Comment by pawlosck** [comment]
Any progress?
