### ISSUE TITLE
Sensitive Data Exposure – Sensitive Data in URL

### ISSUE THREAD

**Issue by ViNNu9** [nextcloud/server#23818]
**please suggest me how to fix it! on nextcloud** 

Sensitive Data Exposure – Sensitive Data in URL
Explain:

Information exposure through query strings in URL is when sensitive data is passed to parameters in the
URL. This allows attackers to obtain sensitive data such as usernames, passwords, tokens (authX),
database details, and any other potentially sensitive data. The entire URL is cached within the local user's
browser history. This may expose sensitive data to any other user of the workstation.
The entire URL is exposed if the user clicks on a link to another HTTPS site. This may expose sensitive
data within the referral field to the third party site. This exposure occurs in most browsers and will only
occur on transitions between two TLS sites.

**Comment by acsfer** [comment]
Hi, please use https://help.nextcloud.com to get help for these questions and Git only for bug requests in the code please. Thanks for understanding 👍
