### ISSUE TITLE
Include host names for sessions in settings/user/security 

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#23816]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

I have a large number of sessions listed with identical names such as "Firefox Linux" or "Sync client Linux" and I don't know which is which and it is therefore hard to identify which sessions I should keep and which I should remove.

**Describe the solution you'd like**
For desktop sync clients and browser sessions, include at least the host names in the names of the sessions.

**Describe alternatives you've considered**

Set an expiration date for inactive  sessions.

**Comment by szaimen** [comment]
> for browser sessions include at least the host names in the names of the sessions.

This is not possible for most browsers, afaik because it would make tracking pretty simple.
For desktop sync clients this might be possible but please open a new issue in the correct repo for this if not already present.
Thank you!

> Set an expiration date for inactive sessions.

This should already work if you've configured your Nextcloud correctly.

---

I am closing this now since everything seems to be answered/solved.

**Comment by vasyugan** [comment]
> This should already work if you've configured your Nextcloud correctly.

... only for web browser session. It doesn't seem to work for other kinds of sessions. As I have read, the default expiration time is 15 days, and I see active sessions for sync clients, caldav clients etc that are months old.

**Comment by szaimen** [comment]
> As I have read, the default expiration time is 15 days, and I see active sessions for sync clients, caldav clients etc that are months old.

I think that not removing other kinds of sessions is working as designed. So I don't think that this request is on our roadmap. 
cc @nextcloud/server-triage for feedback on this
