### ISSUE TITLE
Uploading Files in an Anonymous Upload which is an shared folder

### ISSUE THREAD

**Issue by Putzlappeneimer** [nextcloud/server#2381]
### Steps to reproduce
1. Create a folder for a group on the external storage (SMB) and share this folder with the user.
2. The user goes to his shared folder and creates a public share
3. Upload files over 5 MB into the share

### Expected behaviour
There should be no error-message after the successfull Upload.

### Actual behaviour
Tell us what happens instead
If the file is over 5 MB following message is shown: _"Fehler beim Hochladen der Datei "LinuxUSBCreator.exe":Invalid request for /Test/LinuxUSBCreator.exe (NotFoundException_). First sentence is german and just says that there was an error while uploading. Even with showing that error, the file is uploaded.

If the public share is not allowed to see the data inside the folder and just can upload following error is shown: _could not upload "{filename}"_ The circle that it is uploading continues to spin, but nothing will happen afterwards. If i login and check the folder, the file was uploaded.

If i create a public share on the folder without using the shared folder, but instead of that going the whole path to that folder over the external storage menu, these errors dont happen. The problem for me is, that the users are not allowed to have access to the whole external storage folders, so they cant create that public link that way. I guess the only problem here, is that the uploader tries to use the wrong path here. For example:

Whole Path: /nextcloud-share/departmentA/user1
Shared Path: /user1

So if the link is created on the shared folder, he tries to write or move it in a directory which doesnt even exist. But the weird thing is that even with showing that error message, the file is moved to the right directory AND this message is not shown for files under 5 MB. I hope I explained it understandable. 

I didnt tested, if that happens on folders which arent on an External Storage. 

### Server configuration
**Operating system**:
Ubuntu 16.04 

**Web server:**
Apache2

**Database:**
MariaDB

**PHP version:**
php7.0
**Nextcloud version:** (see Nextcloud admin page)
10.1

**Are you using external storage, YES, SMB

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** EDGE, Mozilla and Opera were tested

**Operating system:** Windows 10

This is in the logs from the Web-GUI:

Uncaught Error: Access to undeclared static property: OC\Files\Filesystem::$normalizedPathCache in /var/www/nextcloud/lib/private/Files/Filesystem.php:773 Stack trace: #0 /var/www/nextcloud/lib/private/Files/View.php(2034): OC\Files\Filesystem::normalizePath('/"Username of the Admin-Account who shared the folder with me"/files...') #1 /var/www/nextcloud/lib/private/Files/View.php(1152): OC\Files\View->unlockFile('/nextcloud/pds/...', 1) #2 [internal function]: OC\Files\View->OC\Files\{closure}() #3 /var/www/nextcloud/apps/files_external/3rdparty/icewind/streams/src/CallbackWrapper.php(109): call_user_func(Object(Closure)) #4 [internal function]: Icewind\Streams\CallbackWrapper->stream_close() #5 {main} thrown at /var/www/nextcloud/lib/private/Files/Filesystem.php#773	2016-11-28T16:14:17+01:00	"myusername"
Warning	filesystem	Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.	2016-11-28T16:04:55+01:00	--
Warning	filesystem	Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.	2016-11-28T16:02:30+01:00	--
Warning	filesystem	Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.	2016-11-28T16:04:55+01:00	--
Warning	filesystem	Storage wrapper 'sharePermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.	2016-11-28T16:02:30+01:00	--
Error	PHP	Icewind\SMB\Exception\NotFoundException: Invalid request for /Test (NotFoundException) at /var/www/nextcloud/apps/files_external/3rdparty/icewind/smb/src/Parser.php#57	2016-11-28T16:02:23+01:00	"myusername"
Error	PHP	Invalid argument supplied for foreach() at /var/www/nextcloud/apps/dav/lib/Connector/Sabre/ShareTypeList.php#69	2016-11-28T16:01:27+01:00	"myusername"

**Comment by Putzlappeneimer** [comment]
A way to prevent this error message, is instead of sharing the subfolders just mount each subfolder specially for that group and share it in the external storage menu. I tried that and the message isnt thrown.

**Comment by skjnldsv** [comment]
As there is no feedback since a while I will close this ticket. If this is still happening please make sure to upgrade to the latest version. After that, feel free to reopen.
