### ISSUE TITLE
SMB Shares not working on 19.0.4

### ISSUE THREAD

**Issue by wookie73** [nextcloud/server#23826]
This problem started for me on Nextcloud 18, unfortunately I can remember which version exactly.
I have 8 Windows SMB shares, all apart from two stopped working.
I since upgraded a few times and am now on NC 19.0.4 and this problem still persists.

I am getting errors in the log file:
[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Storage is temporarily not available at <<closure>>

0. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 976
   OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath(" Photos")
1. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1678
   Sabre\DAV\Server->getPropertiesIteratorForPath(" Photos", ["{DAV:}creation ... "], 0)
2. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1661
   Sabre\DAV\Server->writeMultiStatus(Sabre\Xml\Writer ... ]}, Generator {}, false)
3. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 363
   Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
4. /var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
5. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
6. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
7. /var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
8. /var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php line 82
   Sabre\DAV\Server->exec()
9. /var/www/html/nextcloud/remote.php line 167
   require_once("/var/www/html/n ... p")

PROPFIND /remote.php/webdav/%20Photos/
from 192.168.1.153 by Wookie_73 at 2020-10-30T20:56:58+00:00

I have tried removing the shares and recreating them. This has not worked.
Have had a good look around and have found similar issues:
https://github.com/nextcloud/server/issues/20622
https://github.com/nextcloud/server/pull/21342/files
https://discourse.joplinapp.org/t/nextcloud-sync-broken-here/9916

But most of these are not quite the same and for older versions.

I have also noticed that on the NC android app when i try to go to the SMB shared folders that don't work the NC app says "server in maintenance mode". It is defiantly not in maintenance mode

**Operating system:**
Ubuntu 20.04.1 LTS, Running as a virtual machine in Hyper-V
**Web server:**
Apache 2.4.41
**Database:**
mariadb 10.3
**PHP version:**
7.4.3
**Nextcloud version:** (see Nextcloud admin page)
19.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated via web updater

Any help or pointers much appreciated.

**Comment by gregecslo** [comment]
Hi.
We have NC 18.0.10, PHP 7.2.34
Updated from 17 where it all worked.

I have 2 SMB shares, one is working and other not.
When I click on not not working one:
"There was an error with message: Empty response from the server. Do you want to review mount point config in admin settings page?"

Funny thing is, if I configure share to use subfolder of non working share then it works. There was no permission change or anything on fileserver or nextcloud.

In log I only see this: External storage not available: stat() failed

**Comment by expressrussian** [comment]
I confirm.
Ubuntu Server 20.04 LTS. Standalone nextcloud installation on LAMP. PHP 7.4.3.
When in Nextcloud web interface i go to Settings / External Storages, it gives me blue screen of error:
"Internal Server Error
The server was unable to complete your request. If this happens again, please send the technical details below to the server administrator. More details can be found in the server log."
But the log file /var/www/nextcloud/data/nextcloud.log does not contain the lines for the timeframe...

**Comment by wookie73** [comment]
> Funny thing is, if I configure share to use subfolder of non working share then it works. There was no permission change or anything on fileserver or nextcloud.
> 

Just tried adding a sub folder to the share and hey presto it works.
Not much help but maybe it will give someone an idea of what is wrong?

**Comment by gregecslo** [comment]
Yeah, it would be awesome if someone would figure it out.
I really need this feature :)

**Comment by gregecslo** [comment]
I also upgraded to 19.0.4 and same thing...

**Comment by brainstuetze** [comment]
We are on 19.05 and have SMB Shares to Roaming Windows Home Folders, which are hosted on a Debian 9 using Samba 4.5.16 
The folder was suddenly read-only after coming from NC Version 16.
After applying the following patches, creating and editing files in those shares is possible again:
https://github.com/nextcloud/server/issues/23462#issuecomment-723676958
https://github.com/nextcloud/server/issues/20622#issuecomment-633800927

Not exactly sure if this is related to your problem though...

**Comment by wookie73** [comment]
@brainstuetze thanks for the input. Had a look through and nothing in the posts that I think will help though.

Just upgraded to Nextcloud 20.0.4 was really hoping this would sort out the issue but sadly not.

Been playing around with my Windows permissions a bit to try and fix this error, but haven't had any luck yet. I am reluctant to go too crazy though as it all used to work fine many releases ago.
Very odd that if you point to a sub folder everything works ok.

**Comment by wookie73** [comment]
Well after having some time over Christmas I seem to have fixed the issue.

I was missing the PHP smbclient module

Turns out that in Ubuntu 20.04LTS php-smbclient has been removed from the Ubuntu repositories. 
As I upgraded from 18.04LTS to 20.04LTS along with a raft of other stuff at the same time including upgrading from PHP 7.2 to 7.4 and Nextcloud updates. 
When the issue occurred I had no idea where it arose from, hence me thinking it was a NC update issue.

For me to fix the issue I added Ondřej Surý PHP repository.
details can be found on this page:
[https://launchpad.net/~ondrej/+archive/ubuntu/php/+index?batch=75&memo=150&start=150](url)

to add repository and smbclient i did:
sudo add-apt-repository ppa:ondrej/php
sudo apt update
sudo apt install php7.4-smbclient

A reboot and everything worked as it should again.

Hope this helps those out with the same issue.

**Comment by GeneralVictm** [comment]
Still had this issue with a fresh installation of Nextcloud v22.0.0.11 on Ubuntu 20.04 LTS.

The Nextcloud documentation states that using either smbclient or the PHP package will work, which was not the case for me. Using smbclient did allow me to add SMD Shares to my cloud, but the connection didn't work.

Only after following the instructions for getting the PHP package and restarting Apache did the Shares finally connect.

Getting the package via PECL didn't work for me, it showed some errors I couldn't make any sense of.
