### ISSUE TITLE
Can't remove Group from User

### ISSUE THREAD

**Issue by benjelloun69** [nextcloud/server#23830]
Hi everybody,

I have Nextcloud Server 20.0.1, and I can't remove a group from a user.

Error : 
Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services.

I know why it's invalid, data is missing -> { "groupId" : "myGroup"} in the DELETE request.

When I use curl whith "-d { "groupId" : "myGroup"} " it works.
I know that the problem is in the file "vue-settings-apps-users-management.js" which is minified.. I can' read or understand it.
I have found on the net a solution : 

change "axios.delete(sanitize(url), { data}" to "axios.delete(sanitize(url), { params: data}" in src/js/api.js.
but in my installation I have no "src" folder...

I found "axios.delete(sanitize(url), { data}" in "vue-settings-apps-users-management.js.map" which is a "map" file not "js".. don't even know what is "map" file.

I really don't know what to do.

Thank you in advance for your help.

**Comment by benjelloun69** [comment]
![image](https://user-images.githubusercontent.com/16430387/97842602-272a3500-1ce8-11eb-88ca-51913e4b99cb.png)

Here I can't remove group Test from user..

Please help.

Thank you again =)

**Comment by kinimodmeyer** [comment]
sounds like: https://github.com/nextcloud/server/issues/23237 / https://github.com/nextcloud/server/pull/23269
but they say it is is fixed in 20.0.1

**Comment by benjelloun69** [comment]
@kinimodmeyer thank you for your answer.
In the fix I have to make changes to "apps/settings/src/store/api.js". But this file doesn't exist in my installation..
Also in the fix, the diff for "apps/settings/js/vue-settings-apps-users-management.js.map" can't be shown, with this error : "1 addition, 1 deletion not shown because the diff is too large. Please use a local Git client to view these changes." 

I would appreciate if you continue helping me =)

Too many thanks!

**Comment by axheli** [comment]
hmm trying running occ repair ? or manual copying the files over ?

**Comment by skjnldsv** [comment]
Yep, fixed !

@benjelloun69 those are compiled files you cannot patch them, please upgrade to latest nextcloud releases
