### ISSUE TITLE
The system is updated too frequently, so how dare I use so many bugs?

### ISSUE THREAD

**Issue by fan4905** [nextcloud/server#23831]
Can you come up with a stable version instead of frequent updates?

**Comment by pawlosck** [comment]
For me, nextcloud is generally stable app (there are some a little bugs, but no big bugs), but version 20 is too buggy.

**Comment by fan4905** [comment]
I mean stable version, you should make sure that there are no small bugs, or you will lose user confidence

**Comment by pawlosck** [comment]
There are limited number of users which uses this nextcloud (me and other three users). Currently I am using mainly contacts, calendar and notes and these apps are very stable.

**Comment by szaimen** [comment]
There are a few tips how to run your Nextcloud yourself as stable as possible. If done right, Nextcloud (or at least the core functionality of Nextcloud) is pretty stable. Please refer to the forum for details.
