### ISSUE TITLE
.nomedia / .noimage is not working in 20.0.0

### ISSUE THREAD

**Issue by tolotos-rgu** [nextcloud/server#23837]
The webpage gallery of NC 20.0.0 ignore the .noimage / .nomedia files completely.

**Comment by tolotos-rgu** [comment]
IOS app shows the same issue and devs said it was no app function. 
As it works in NC <= 19.x it must be NC 20 server related.

**Comment by skjnldsv** [comment]
Please check for existing issues on the dedicated app: https://github.com/nextcloud/photos
