### ISSUE TITLE
Firefox - User Settings - Some svg icons not visible

### ISSUE THREAD

**Issue by Eninspace** [nextcloud/server#23849]
It is a visual bug appears on the settings page when there are many characters in the string. I think this is due to css
```
#app-navigation:not(.vue)>ul>li>ul>li>a
overflow: hidden;
```
which hides the icon along with the overflow text. If you comment out overflow: hidden; icons appear

### Steps to reproduce
1. Set Russian languages
1. Open User Setting Page

### Expected behaviour
All Icons in the left side bar are displayed correctly

### Actual behaviour
Some icons don't displayed

![изображение](https://user-images.githubusercontent.com/38405119/97905972-ee27aa00-1d53-11eb-9561-3957b1ab9f57.png) ![изображение](https://user-images.githubusercontent.com/38405119/97906111-2c24ce00-1d54-11eb-9dbb-7d2df7b5d686.png)

### Server configuration

**Operating system:*Ubuntu*

**Web server:*Apache*

**Database:*PostgreSQL 12.4*

**PHP version:*7.4.3*

**Nextcloud version:*19.0.4*

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:*Nextcloud official website*

### Client configuration
**Browser:*Firefox 82.0.2*
**Operating system:*Windows 10*

**Comment by TimonPllkrn** [comment]
Hey, I'd like to pick up this Issue.

**Comment by szaimen** [comment]
Can you please try to reproduce this on NC22.0.0? I wasn't able to reproduce it...
