### ISSUE TITLE
After installation no default channel is used

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2385]
@MorrisJobke I suppose we should default to `stable` then? 

<img width="975" alt="screen shot 2016-11-28 at 18 20 38" src="https://cloud.githubusercontent.com/assets/878997/20678540/6289d2d4-b597-11e6-83b8-e85511163f02.png">

**Comment by rullzer** [comment]
Why not daily 😛

**Comment by MorrisJobke** [comment]
I'm on it.

**Comment by MorrisJobke** [comment]
Fix is in #2396
