### ISSUE TITLE
SSL certificate for download.nextcloud.com is expired

### ISSUE THREAD

**Issue by tonystafford** [nextcloud/server#23853]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Attempt to update your Nextcloud instance through the built-in updater in the administrator panel.

### Expected behaviour
The software is able to download the update and continue the update process. 

### Actual behaviour
The update fails with the following error: "Curl error: SSL certificate problem: certificate has expired"

**Operating system:**
Ubuntu 18.04.05 LTS

**Nextcloud version:**
19.0.2

**Comment by meonkeys** [comment]
Can verify with https://observatory.mozilla.org/analyze/download.nextcloud.com . Rating is obviously an F because of the invalid cert, although it does mention a CSP issue as well: `Content Security Policy (CSP) header not implemented`. Might be the same root cause.
