### ISSUE TITLE
oc_file_locks table is used despite redis is set

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#23855]
As discussed on chat, I use redis for file locking:
```
'memcache.local' => '\\OC\\Memcache\\APCu',
  'filelocking.enabled' => 'true',
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
  ),
```
still I see currently ~25k entries in oc_file_locks table.
```
{"id":"18924560","lock":"0","key":"files\/85113f96431ea41c9bd38637d184e5ff","ttl":"1604385358"},
{"id":"18924561","lock":"0","key":"files\/5f2f4f0477982c5cfb9ec6bf68f482df","ttl":"1604385358"},
{"id":"18924562","lock":"0","key":"files\/ed36b2634d5f4da318ab55d5cb99d88c","ttl":"1604385358"},
{"id":"18924563","lock":"0","key":"files\/4a7deb0bdf5d97e7f4d82382e6aa7921","ttl":"1604385358"},
{"id":"21867817","lock":"1","key":"files\/66cb46dffa290009b841d570c9305926","ttl":"1604385901"},
{"id":"21893422","lock":"0","key":"files\/69d4dae129cb033b0fd18e968d4d46a5","ttl":"1604385901"},
{"id":"21893423","lock":"0","key":"files\/76101f503b3a497c8b447afdc6763269","ttl":"1604385901"},
{"id":"21893425","lock":"0","key":"files\/731503f3a82a3baed002ed70115f8101","ttl":"1604385901"},
{"id":"21893427","lock":"0","key":"files\/7e4045d103368ad47f40a7507b06647e","ttl":"1604385901"},
{"id":"21893428","lock":"0","key":"files\/b34d17e44cd7201912a6bd0a3fd850de","ttl":"1604385901"}
````

@rullzer @icewind1991

**Comment by tobiasKaminsky** [comment]
This is crazy.
I rescanned one user, and now I have 430k entries…

**Comment by tobiasKaminsky** [comment]
Shame on me. 
Redis was not properly configured :S

**Comment by tobiasKaminsky** [comment]
Hm. I still have 250k entries in oc_file_locks, while I now see in "redis-cli monitor" that redis works.

**Comment by tobiasKaminsky** [comment]
Now after some times I even have 500k in oc_file_locks

**Comment by axheli** [comment]
@tobiasKaminsky whats the issue? how are you getting the locks?

**Comment by tobiasKaminsky** [comment]
I guess this is the big question…
Now it is >900k.

**Comment by PVince81** [comment]
In my dev env (git master 32ded877dc30b18f6eba7f3854988ce2992feb00) I always setup redis for all memcaches upon setup. I've checked oc_file_locks and it's empty.

also ran a file scan and it did not populate oc_file_locks.

strange...

what version was this happening on?

**Comment by tobiasKaminsky** [comment]
Sorry, I forget to update.
After restarting everything and delete all content in file_locks it remains now empty.

so it was a pebkac…🙈
