### ISSUE TITLE
Fetching notes for dashboard has failed. HTTP 500 (undefined)

### ISSUE THREAD

**Issue by pawlosck** [nextcloud/server#23871]
### Steps to reproduce
1. After login into Nextcloud, I see this message.
Morning it worked correctly and and later stopped working. I didn't install anything on the server.

### Expected behaviour
Notes in widget should be visible and no errors should be displayed

### Actual behaviour
Notes in widgets are not visible. Notes in Note app are visible correctly

### Server configuration

**Operating system:**
Ubuntu 20.04.1 LTS

**Web server:**
Apache

**Database:**
SQLite

**PHP version:**
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )

**Nextcloud version:** (see Nextcloud admin page)
20.0.1 (in 20.0 the same bug)

**Updated from an older Nextcloud/ownCloud or fresh install:**
from Nextcloud 20.0

**Where did you install Nextcloud from:**
zip file from website

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Firefox

**Operating system:**
Ubuntu 20.04.1 LTS

#### Web server error log
<details>
<summary>Web server error log</summary>
No errors
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
**Latest log**

Error: Undefined offset: 3 at /nextcloud/lib/private/legacy/OC_Helper.php#548
    /nextcloud/lib/private/legacy/OC_Helper.php - line 548:
    OC\Log\ErrorHandler::onError()
    /nextcloud/apps/settings/lib/Settings/Personal/PersonalInfo.php - line 108:
    OC_Helper::getStorageInfo()
    /nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 141:
    OCA\Settings\Settings\Personal\PersonalInfo->getForm()
    /nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php - line 77:
    OCA\Settings\Controller\PersonalSettingsController->formatSettings()
    /nextcloud/apps/settings/lib/Controller/CommonSettingsTrait.php - line 152:
    OCA\Settings\Controller\PersonalSettingsController->getSettings()
    /nextcloud/apps/settings/lib/Controller/PersonalSettingsController.php - line 68:
    OCA\Settings\Controller\PersonalSettingsController->getIndexResponse()
    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 169:
    OCA\Settings\Controller\PersonalSettingsController->index()
    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 100:
    OC\AppFramework\Http\Dispatcher->executeController()
    /nextcloud/lib/private/AppFramework/App.php - line 152:
    OC\AppFramework\Http\Dispatcher->dispatch()
    /nextcloud/lib/private/Route/Router.php - line 308:
    OC\AppFramework\App::main()
    /nextcloud/lib/base.php - line 1009:
    OC\Route\Router->match()
    /nextcloud/index.php - line 37:
    OC::handleRequest()

====================================
**Second log**

Exception: 
    /nextcloud/lib/private/AppFramework/Http/Dispatcher.php - line 123:
    OCP\AppFramework\Http\JSONResponse->render()
    /nextcloud/lib/private/AppFramework/App.php - line 152:
    OC\AppFramework\Http\Dispatcher->dispatch()
    /nextcloud/lib/private/Route/Router.php - line 308:
    OC\AppFramework\App::main()
    /nextcloud/lib/base.php - line 1009:
    OC\Route\Router->match()
    /nextcloud/index.php - line 37:
    OC::handleRequest()

</details>

**Comment by pawlosck** [comment]
![obraz](https://user-images.githubusercontent.com/3769853/98023477-4b306800-1e07-11eb-871b-a3b2b2173ade.png)

**Comment by sirdrakeistda** [comment]
This could be related to this issue:
https://github.com/nextcloud/notes/issues/620
or this one:
https://github.com/nextcloud/server/issues/23241
Some strings in the notes cause this error, so try to remove all non ASCII characters.

**Comment by pawlosck** [comment]
After update Notes app, bug fixed, so issue can be closed
