### ISSUE TITLE
Comments are not marked as read

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/server#23877]
* having a file shared from user1 to user2
* as user1 comment on that file
* as user2 I see an unread comment icon in the file list
* clicking on the icon should open the comments in the sidebar
* actual: unread comment icon is still there (also after page reload)
* expected: unread comment icon should not be there and the comments should be marked as read

cc @skjnldsv

**Comment by MorrisJobke** [comment]
Most likely related to #23173

**Comment by skjnldsv** [comment]
Oh interesting, I thought that would be linked to the api requests or something.
How is it done?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/pull/23173/files#diff-c56f3a86ecfd5f48a31776dd8c9c77c82303d7dacc02ffc6e5526c1b166ed9bfL157-L163
and
https://github.com/nextcloud/server/pull/23173/files#diff-3651575eb69fe523c921c50fe52e197f517aa4538db6a5278e49ba3b4c6605b1L14

**Comment by ImaCrea** [comment]
Hello there,
I see this bug seem to be postponed from one version to another. I was wondering if we could reasonably hope it will be fixed for the next release please?

Thanks :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
