### ISSUE TITLE
LDAP Groups Users error

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#23883]
On nextcloud 18.10
Here our config :+1: `-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                    |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                      |
| homeFolderNamingRule          | attr:employeeNumber                                                                                                                                                    |
| lastJpegPhotoLookup           | 0                                                                                                                                                                      |
| ldapAgentName                 | CNSECURES                                                                                                                       |
| ldapAgentPassword             | ***                                                                                                                                                                    |
| ldapAttributesForGroupSearch  |                                                                                                                                                                        |
| ldapAttributesForUserSearch   |                                                                                                                                                                        |
| ldapBackupHost                |                                                                                                                                                                        |
| ldapBackupPort                |                                                                                                                                                                        |
| ldapBase                      | dc=CLIENT,dc=org                                                                                                                                                     |
| ldapBaseGroups                | ou=groups,dc=CLIENT,dc=org                                                                                                                                           |
| ldapBaseUsers                 | dc=CLIENT,dc=org                                                                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                                                                    |
| ldapConfigurationActive       | 1                                                                                                                                                                      |
| ldapDefaultPPolicyDN          |                                                                                                                                                                        |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                        |
| ldapEmailAttribute            | mail                                                                                                                                                                   |
| ldapExperiencedAdmin          | 0                                                                                                                                                                      |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                        |
| ldapExpertUUIDUserAttr        | employeeNumber                                                                                                                                                         |
| ldapExpertUsernameAttr        | employeeNumber                                                                                                                                                         |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                        |
| ldapGidNumber                 | gidNumber                                                                                                                                                              |
| ldapGroupDisplayName          | cn                                                                                                                                                                     |
| ldapGroupFilter               | (&(objectClass=groupOfEntries)(|(businessCategory=Organigramme)(&(businessCategory=Application)(!(cn=*-Gestionnaire)))))                                               |
| ldapGroupFilterGroups         |                                                                                                                                                                        |
| ldapGroupFilterMode           | 1                                                                                                                                                                      |
| ldapGroupFilterObjectclass    |                                                                                                                                                                        |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                                 |
| ldapHost                      | ldaps://ldapnextcloud.CLIENT.org                                                                                                                                     |
| ldapIgnoreNamingRules         |                                                                                                                                                                        |
| ldapLoginFilter               | (&(&(objectclass=inetOrgPerson)(memberOf=cn=Apps-NEXTCLOUD,ou=applications,ou=permissions,ou=groups,dc=CLIENT,dc=org))(|(employeeNumber=%uid)(mail=%uid)(uid=%uid))) |
| ldapLoginFilterAttributes     |                                                                                                                                                                        |
| ldapLoginFilterEmail          | 0                                                                                                                                                                      |
| ldapLoginFilterMode           | 1                                                                                                                                                                      |
| ldapLoginFilterUsername       | 1                                                                                                                                                                      |
| ldapMatchingRuleInChainState  | unknown                                                                                                                                                                |
| ldapNestedGroups              | 0                                                                                                                                                                      |
| ldapOverrideMainServer        |                                                                                                                                                                        |
| ldapPagingSize                | 500                                                                                                                                                                    |
| ldapPort                      | 636                                                                                                                                                                    |
| ldapQuotaAttribute            |                                                                                                                                                                        |
| ldapQuotaDefault              |                                                                                                                                                                        |
| ldapTLS                       | 0                                                                                                                                                                      |
| ldapUserAvatarRule            | default                                                                                                                                                                |
| ldapUserDisplayName           | cn                                                                                                                                                                     |
| ldapUserDisplayName2          |                                                                                                                                                                        |
| ldapUserFilter                | (&(objectclass=inetOrgPerson)(memberOf=cn=Apps-NEXTCLOUD,ou=applications,ou=permissions,ou=groups,dc=CLIENT,dc=org))                                                 |
| ldapUserFilterGroups          |                                                                                                                                                                        |
| ldapUserFilterMode            | 1                                                                                                                                                                      |
| ldapUserFilterObjectclass     | person                                                                                                                                                                 |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                   |
| ldapUuidUserAttribute         | auto                                                                                                                                                                   |
| turnOffCertCheck              | 0                                                                                                                                                                      |
| turnOnPasswordChange          | 0                                                                                                                                                                      |
| useMemberOfToDetectMembership | 1                                                                                                                                                                      |
+-------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

`

Inside user pannel : 
![image](https://user-images.githubusercontent.com/38983960/98081169-e876b500-1e76-11eb-8f07-f0f16fdaeac8.png)

On the user inside the group filter 
![image](https://user-images.githubusercontent.com/38983960/98081235-07754700-1e77-11eb-8b45-bcf628cfb82e.png)

As you can see the user is in the group but, when we list the user's group the group is not here, and if we share something to this group the user's did not receice the share

EDIT : 
We found something : 
All groups inside ou=organigramme,ou=groups,dc=CLIENT,dc=org  did not works properly 
But 
All groups ou=applications,ou=permissions,ou=groups,dc=CLIENT,dc=org works

**Comment by tanguy-opendsi** [comment]
Can someone give me some help ? :)

**Comment by faust64** [comment]
Can you show us some sample of the groups in both ou=applications and ou=organigramme?

**Comment by tanguy-opendsi** [comment]
what do you mean about sample

**Comment by faust64** [comment]
Some ldif that shows what a group in ou=applications looks like. comparing it to another group in ou=organigrame.
A sample of what a group is, in your directory.
Does your group filter actually apply to both branches of your directory?
Can your nextcloud LDAP user search both branches of your directory for such attributes?
