### ISSUE TITLE
Pop up for moving files empty

### ISSUE THREAD

**Issue by MelBourbon** [nextcloud/server#23893]
I searched for it but not found the issue. If I did it wrong and this is a duplicate please terminate again.

With Nextcloud 20.0.1 I can not move and copy files anymore with function "move" as no other folders are shown in the pop up (see attached screenshot)

![image](https://user-images.githubusercontent.com/30600002/98100066-a5294000-1e90-11eb-99a3-f974d70a14a3.png)

### Steps to reproduce
1. Mark a file and click on actions
2. Select "Move or Copy"

### Expected behaviour
Folders in the same folder should be shown to select new folder

### Actual behaviour
Pop up is empty

### Server configuration

**Operating system:** Ubuntu 18.0.4
**Web server:** Nginx
**Database:** MariaDB mysql
**PHP version:** 7
**Nextcloud version:** 20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 19

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by nsrafk** [comment]
I’ve had this issue. I solved it by disabling external app ‘fvorites quick sorting’ or similar name.

**Comment by MelBourbon** [comment]
Tried to reproduce. Was reproducable when opening a folder and file the first time (see server-1604492081045.log attached). After reloading page with F5 the pop up is now filled correctly (see server-1604492101050.log). So current workaround is to click F5.

[server-1604492081045.log](https://github.com/nextcloud/server/files/5487691/server-1604492081045.log)
[server-1604492101050.log](https://github.com/nextcloud/server/files/5487692/server-1604492101050.log)

**Comment by kesselb** [comment]
Thanks @nsrafk :+1: 

Please report the issue to https://github.com/newhinton/quickaccesssorting them. If it turns out to be an issue with nextcloud/server we can reopen.

**Comment by nsrafk** [comment]
> Thanks @nsrafk 👍
> 
> Please report the issue to https://github.com/newhinton/quickaccesssorting them. If it turns out to be an issue with nextcloud/server we can reopen.

Copy that. Just did. You can see here https://github.com/newhinton/quickaccesssorting/issues/4

**Comment by digitalrevisor** [comment]
This issue seems to exist even without quickaccessorting installed. We got this issue on version 20.02 on Ubuntu 18.04 with PHP 7.4 & apache2.4.29. No error in console, nextcloud error log, or apache error log as far as I can see. We have another server with similar versions to what I just mentioned where it works, so I'm trying to see if there is any differences between them that might cause the issue. quickaccessorting is not installed on either server, and as far as I know has never been. No folder leftover from it, and app menu shows "Download & Activate".
![Fildeling-Digital-Revisor](https://user-images.githubusercontent.com/59980626/102788148-79134100-43a2-11eb-86fe-fae512d08ee4.png)
