### ISSUE TITLE
"Supported Apps" all come from ownCloud

### ISSUE THREAD

**Issue by cyphar** [nextcloud/server#2390]
### Steps to reproduce
1. Install NextCloud 10.0.1
2. Install the Contacts and Calendar apps using the "+ Apps" interface.
3. Note that all of the Apps come from ownCloud's repos and App Store.

### Expected behaviour
I'd expect the code to come from the nextcloud/calendar, nextcloud/contacts and so on repos.

### Actual behaviour
The code comes from owncloud/{contacts,calendar}.

I get that this is a transition period, but I'm concerned that I will have to manually migrate to the NextCloud versions of these apps in a few months. Will NextCloud make sure that when the time comes all of the migrations will be done "automatically" (through the interface) and I won't have to do any of it manually? If not, I'd prefer to know now before I start dumping all of my information into it.

**Comment by LukasReschke** [comment]
11 will use the Nextcloud appstore and have automatic migration.
