### ISSUE TITLE
Continuous Integration for Postgres 12 and 13

### ISSUE THREAD

**Issue by Chartman123** [nextcloud/server#23913]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
docs.nextcloud.com currently doesn't state that PostgreSQL 12/13 are supported. However, they both seem to work fine with at least NC 19 and 20. https://help.nextcloud.com/t/postgres-13-support/93184

There is already an issue for docs: https://github.com/nextcloud/documentation/issues/5321#issuecomment-722199392 

**Describe the solution you'd like**
In order to be able to add it to the docs, it should first be validated. So, adding Postgres 12 and 13 to CI should be the first step.

**Comment by faust64** [comment]
This has been done, in https://github.com/nextcloud/server/commit/734b29b2775e2caf15ccce0a48252c8065d8407f

**Comment by Chartman123** [comment]
@rullzer @MorrisJobke Should we then close this issue here?
