### ISSUE TITLE
Feature request: file activity export on demand

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2392]
Context: https://help.nextcloud.com/t/is-it-possible-to-export-activity-on-demand/5598

It'd be very useful for reporting/audit purposes to be able to export the activity of a file. Currently it's possible to _see_ what has happened (uploaded, downloaded, shared) when clicking on the file within the web interface: 

![](https://help.nextcloud.com/uploads/default/original/2X/0/044ec3b08854a131028541575a2c1288d07acb3f.png)

But aside from occasional activity emails which don't provide the full activity every email, copying and pasting from that area in the UI is the only option.

**Comment by nickvergessen** [comment]
Activity app => https://github.com/nextcloud/activity/issues
