### ISSUE TITLE
Security & setup warnings，From Synology NAS, for help

### ISSUE THREAD

**Issue by pianshanchou** [nextcloud/server#23945]
Today, I installed nextcloud with Synology NAS and completed the installation in web. This prompt appears in “security & setup warnings”. I am very confused, tried many methods, still can’t solve. Hope to get help here, thank you. :smile:
![b47dc0fabbe3c5b349d01e4009bd25f050496f19](https://user-images.githubusercontent.com/1827701/98398326-c01bd000-209b-11eb-959a-cf40df8e21d6.png)

**Comment by Apieceofbluesky** [comment]
You can ssh into your Synology (if you have activated ssh in control panel), and chown -R the apps directory to the appropriate www-data user. 

Besides that, if your Synology supports Docker, i'd recommend to install Nextcloud via that method

**Comment by Dennis1993** [comment]
Please use our community for that, because its not a bug or improvement for our software and developer under https://help.nextcloud.com/

Apeaceofbluesky wrote a solution to fix your information on the admin panel.

Thank you!

**Comment by pianshanchou** [comment]
> 您可以SSH进入Synology（如果已在控制面板中激活ssh），然后将apps目录-R锁定到适当的www-data用户。
> 
> 除此之外，如果您的Synology支持Docker，我建议通过该方法安装Nextcloud

Thank you. It's a good idea. My problem has been solved.
