### ISSUE TITLE
413 Request Entity Too large error

### ISSUE THREAD

**Issue by mikeaxle** [nextcloud/server#23949]
### Steps to reproduce
1. Set up server using MySQL as database
2. Configure server to use default storage for uploads
3. Upload file larger than 2MB

### Expected behaviour
The file supposed to upload successfully.

### Actual behaviour
Files larger than 2MB fail to upload. I get a 413 Request Entity Too large error. I asked my host to change the upload size on their end and they gave me this response: 

"the limit being hit - SecRequestBodyNoFilesLimit - is not because of the actual size of the content that you're busy uploading but rather the fact that the request header is not separated from the request body which then it makes the request appear to be an empty request with only a header, or the size of the request body itself.

As this is type of requests are similar to those received when the server is under a DDoS attack, our ModSecurity firewall limits the allowed size of these requests.

Increasing the request higher than what it has temporarily been increased puts the server at risk. I confirm having reverted the change made.  

We would suggest reviewing the website code instead to either separate the body and header of the request or to significantly reduce the size of the request. " 

They are reluctant to increase the SecRequestBodyNoFilesLimit because of the DDOS risks and suggest I change the code instead. Can someone help me with this? I am not too sure where in the code I must do that. 

### Server configuration

**Operating system:**
Linux 4.9.0-11-amd64 x86_64

**Web server:**
Apache

**Database:**
mysql 10.4.15

**PHP version:**
 7.4.11

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh Install

**Where did you install Nextcloud from:**
Server Install Script

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'ocdbqax6fh9l',
  'passwordsalt' => '7ZzyKQ2RByJwEeY4Eic2wmHG/S/9ls',
  'secret' => 'NOjSFh7ob7x3cbGpc021C1gsN6fWqez/JZUNAADmm1VxZrhK',
  'trusted_domains' => 
  array (
    0 => 'edsecloud.waynes.org.za',
  ),
  'datadirectory' => '/usr/www/users/edsecmgktv/data',
  'dbtype' => 'mysql',
  'version' => '20.0.1.1',
  'overwrite.cli.url' => 'http://edsecloud.waynes.org.za',
  'dbname' => 'edsecmgktv_db1',
  'dbhost' => 'dedi60.jnb3.host-h.net',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'edsecmgktv_1',
  'dbpassword' => '',
  'installed' => true,
  'mail_domain' => 'waynes.co',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'support',
  'mail_smtpauthtype' => 'PLAIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => 'smtp.waynes.co',
  'mail_smtpport' => '587',
  'mail_smtpname' => 'support@waynes.co',
  'mail_smtppassword' => '',
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
**Browser:**
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.183 Safari/537.36

**Operating system:**
Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
[client 197.185.113.6] ModSecurity: Request body no files data length is larger than the configured limit (1048576).. Deny with code (413) [hostname "edsecloud.waynes.org.za"] [uri "/remote.php/dav/uploads/admin/web-file-upload-e89c941d1c96ae911f8dd82044bd7218-1604694069308/0"] [unique_id "X6WwN7WXxuTP1Rc034uJjAAAAAM"]
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"file":"/usr/www/users/edsecmgktv/index.php","line":37,"function":"handleRequest","class":"OC","type":"::","args":[]}],"File":"/usr/www/users/edsecmgktv/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36","version":"20.0.1.1"}
{"reqId":"X6VAIy3VwVA0uet7KMtqwwAAADM","level":3,"time":"2020-11-06T12:22:59+00:00","remoteAddr":"197.185.111.242","user":"admin","app":"PHP","method":"GET","url":"/ocs/v2.php/cloud/users/details?
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
a) /remote.php/dav/uploads/admin/web-file-upload-e89c941d1c96ae911f8dd82044bd7218-1604696324152/0:1 Failed to load resource: the server responded with a status of 413 ()
b) Request URL: https://edsecloud.waynes.org.za/remote.php/dav/uploads/admin/web-file-upload-e89c941d1c96ae911f8dd82044bd7218-1604696533818
Request Method: MKCOL
Status Code: 201 
Remote Address: 196.22.132.233:443
Referrer Policy: no-referrer

Request URL: https://edsecloud.waynes.org.za/remote.php/dav/uploads/admin/web-file-upload-e89c941d1c96ae911f8dd82044bd7218-1604696533818/0
Request Method: PUT
Status Code: 413 
Remote Address: 196.22.132.233:443
Referrer Policy: no-referrer
```
</details>

**Comment by kesselb** [comment]
>  Can someone help me with this? I am not too sure where in the code I must do that.

Nextcloud (web, mobile and desktop) upload files in chunks. A file > 10mb is sliced into chunks and each request is uploaded in a own request. I guess apache/mod_security are unable to detect the chunks as file uploads. 

To change this behaviour you need to update all clients as well. I don't think such a change is planned. Your best option is to pick a different hosting company. 

cc @nextcloud/server-triage because my knowledge about mod_security is limited.

**Comment by mikeaxle** [comment]
@kesselb Thanks for responding so quickly! I will close this issue as this seems to be more of a problem with my hosting company. I managed to convince them increase the limit and put in place another DDOS control to manage the risk.
