### ISSUE TITLE
Fix blank page on browsers without support for ResizeObserver (SOLUTION)

### ISSUE THREAD

**Issue by Captain-FLAM** [nextcloud/server#23972]
As a Waterfox Classic user, I debug this and posted the solution...

That's not a correct way to do... because **ResizeObserver** is used in many places (check by yourself)

I just post the good way there :
https://help.nextcloud.com/t/fix-blank-page-on-browsers-without-support-for-resizeobserver/97412

Enjoy !

_Originally posted by @Captain-FLAM in https://github.com/nextcloud/calendar/pull/2620#issuecomment-723436196_

**Comment by kesselb** [comment]
Thanks for debugging :+1: 

> because ResizeObserver is used in many places (check by yourself)

ResizeObserver is not used in nextcloud/server. Fix for calendar looks reasonable to me. If apps (like calendar) use ResizeObserver they should include the polyfill with their javascript bundle.
