### ISSUE TITLE
Share by mail template design issue (logo not centered on the circle)

### ISSUE THREAD

**Issue by medcloud** [nextcloud/server#23977]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to NextCloud server with following actived plugins : "Share by mail" & "File sharing"
2. Select a folder or file, and share by mail
3. Connect to your mail box and look for the mail received

### Expected behaviour
Looking to the email, the logo should be centered in the circle in the header of the email

### Actual behaviour
Currently, the logo is aligned on the top of the circle in the header of the email

![Github - Bug 01](https://user-images.githubusercontent.com/42641918/98446639-2b5ab600-211f-11eb-8957-27f9033a0027.png)

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache 2.4

**Database:**
PG10

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
NextCloud v 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
NextCloud v 17.0.9

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed, paste the results here.
No errors have been found.

List of activated apps:
Accessibility 1.6.0
Activity 2.13.2
Calendar 2.1.2
Comments 1.10.0
Contacts 3.4.1
Contacts Interaction 1.1.0
Custom CSS 1.7.0
Dashboard 7.0.0
Data Request 1.7.0
Deleted files 1.10.1
DICOM Viewer 1.2.2
External sites 3.7.1
File sharing 1.12.0
Group folders 8.1.0
Log Reader 2.5.0
Notifications 2.8.0
Password policy 1.10.1
PDF viewer 2.0.1
Photos 1.2.0
Recommendations 0.8.0
Right click 0.17.0
Share by mail 1.10.0
Support 1.3.0
Text 3.1.0
Theming 1.11.0
Update notification 1.10.0
Usage survey 1.8.0
User status 1.0.0
Versions 1.13.0
Video player 1.9.0
Weather status 1.0.0

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

**Operating system:**
Windows 10 Version 10.0.19041 Numéro 19041

**Comment by TheRealEscimo** [comment]
Yes, I am also experiencing this on the latest Snap.

**Comment by medcloud** [comment]
OK, I think I have found a solution changing in EMailTemplate.php 2 lines. The problem was visible in Gmail, Hotmail, Outlook, etc...

Original code (line 123 to 125) :
```
<center data-parsed="" style="background-color:%s;width:150px;height:150px;padding:0px;position:relative;border-radius:200px">
	<img class="logo float-center" src="%s" alt="%s" align="center" style="-ms-interpolation-mode:bicubic;clear:both;display:block;float:none;outline:0;text-align:center;text-decoration:none;position:absolute;max-height:100px;max-width:100px;width:auto;height:auto;position:absolute;top:0;bottom:0;left:0;right:0;margin:auto;">
</center>
```

Changed by the code (line 123 to 125) :

```
<center data-parsed="" style="background-color:%s;min-width:150px;padding:50px 0;border-radius:200px">
       <img class="logo float-center" src="%s" alt="%s" align="center" style="-ms-interpolation-mode:bicubic;Margin:0 auto;clear:both;display:block;float:none;margin:0 auto;outline:0;text-align:center;text-decoration:none" height="50">
</center>
```

### Before

![Before - Gmail Chrome](https://user-images.githubusercontent.com/42641918/99014766-aa068780-2553-11eb-96ac-562817430765.png)

### After

![After - Gmail Chrome](https://user-images.githubusercontent.com/42641918/99014794-bab6fd80-2553-11eb-8a20-2b8a0be33ca9.png)
