### ISSUE TITLE
activity page contains links to images with absolute http path - mixed content policy rejects them

### ISSUE THREAD

**Issue by NESC1US** [nextcloud/server#23985]
### Steps to reproduce
1. have ssl encryption handled by reverse proxy and switched off in nextcloud
2. open activity page (https://example.com/index.php/apps/activity/) - all but one image are not loaded as unencrypted content on encrypted site is not allowed by firefox and other browsers.
3. ![image](https://user-images.githubusercontent.com/15976294/98465695-f4da7500-21ca-11eb-9b3b-90dc188a5bf9.png)

### Expected behaviour
see all icons and thumbnails on activity page

### Actual behaviour
all but one icon are set as absolute url using http as encryption is switched off:

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** Nextcloud 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.13.2
  - apporder: 0.11.0
  - bookmarks: 4.0.5
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.1
  - contactsinteraction: 1.1.0
  - dav: 1.16.0
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.23
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - gpxpod: 4.2.3
  - groupfolders: 8.1.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.6.0
  - maps: 0.1.8
  - news: 15.0.6
  - notes: 4.0.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - ojsxc: 4.1.1
  - password_policy: 1.10.1
  - photos: 1.2.0
  - polls: 1.5.7
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - social: 0.4.1
  - tasks: 0.13.5
  - theming: 1.11.0
  - theming_customcss: 1.7.0
  - twofactor_backupcodes: 1.9.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - accessibility
  - admin_audit
  - audioplayer
  - audioplayer_editor
  - auto_mail_accounts
  - calendar
  - camerarawpreviews
  - cospend
  - dashboard
  - encryption
  - firstrunwizard
  - flowupload
  - gpxedit
  - gpxmotion
  - nextcloud_announcements
  - ocr
  - recommendations
  - scanner
  - side_menu
  - spreed
  - support
  - survey_client
  - systemtags
  - text
  - user_ldap
  - user_status
  - weather_status
  - workflow_pdf_converter
```
</details>

**Nextcloud configuration:**
{
    "system": {
        "apps_paths": [
            {
                "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
                "url": "\/extra-apps",
                "writable": true
            }
        ],
        "supportedDatabases": [
            "mysql"
        ],
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nimbus.perfugium.net"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.1.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "has_rebuilt_cache": true,
        "loglevel": 0,
        "theme": "",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "app_install_overwrite": [
            "ojsxc",
            "ocr"
        ],
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "overwritehost": "***REMOVED SENSITIVE VALUE***"
    }
}
</details>

**Are you using encryption:** no (it is encrypted by nginx reverse proxy)

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by NESC1US** [comment]
thank you for closing this issue and referencing links which are relevant but unrelated, i will surely report more bugs!

**Comment by NESC1US** [comment]
![image](https://user-images.githubusercontent.com/15976294/98549375-fc694f00-229a-11eb-9d14-ba6ee2f32584.png)
rewriting rule is in place - if i open the svg image shown in above screenshot in a new window, i get it via https, this however does not seem working in freshly opened private window or a different browser (- i dont think it is cache related)
the one displaying icon is linked by relative path, so no rewritting rule applies.
I only found this actual issue happening on activities page and nowhere else.

**Comment by kesselb** [comment]
You set `overwriteprotocol` to `https` and it does not work?
