### ISSUE TITLE
Avatar picture gone after Nc 10 to 11 beta 2 upgrade

### ISSUE THREAD

**Issue by karlitschek** [nextcloud/server#2399]
I upgraded Nextcloud 10.0.1 to 11.0 beta 2 with the web updater.
Everything seems to work. But my avatar picture is gone. I had my photo in the header and after the upgrade I only see the display name. 
On the personal page I also see an empty profile picture.

### Steps to reproduce
1. upgrade from 10.0.1 to 11.0 beta 2
2. I tested this only once so not sure this is easy to reproduce.

### Expected behaviour
I expected that my profile picture stays unmodified.

### Actual behaviour
The picture is gone.

### Server configuration
**Operating system**:
Ubuntu 16.10

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
now 11.0 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 10.0.1

**Where did you install Nextcloud from:**
tar file and then the web updater.

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Integrity checker has been disabled. Integrity cannot be verified.
Not sure why it is disabled.
</details>

**List of activated apps:**
Enabled:
  - activity: 2.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 1.3.1
  - lookup_server_connector: 1.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.0
  - survey_client: 0.1.5
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
  'instanceid' => 'foobar',
  'passwordsalt' => 'foobar',
  'secret' => 'foobar',
  'trusted_domains' =>
  array (
    0 => 'foobar:88',
    1 => 'foobar2:88',
  ),
  'datadirectory' => '/data/nc-data',
  'overwrite.cli.url' => 'https://foobar:88/nc',
  'dbtype' => 'mysql',
  'version' => '11.0.0.5',
  'dbname' => 'nc',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'nc_',
  'dbuser' => 'nc_frank1',
  'dbpassword' => 'foobar',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => '',
  'loglevel' => 2,
  'maintenance' => false,
  'trashbin_retention_obligation' => 'auto',
  'updater.release.channel' => 'beta',
  'updater.secret' => 'foobar,

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Google, Safari, Firefox

**Operating system:**
macOS

#### Web server error log
Nothing relevant

#### Nextcloud log (data/nextcloud.log)
Interesting entries might be:
\OC\Repair::step: Repair step: Add mover avatar background job
\OC\Repair::step: Repair step: Fix permissions so avatars can be stored again
\OC\Repair::startProgress: Starting ... Fix permissions so avatars can be stored again (2)

I did a 'chown -R www-data nc' before the upgrade so that the upgrade can write files. This shouldn't affect the updater.

#### Browser log
nothing relevant

**Comment by LukasReschke** [comment]
cc @rullzer

**Comment by nickvergessen** [comment]
> Add mover avatar background job

I guess the cron job didnt run yet. Let's see

**Comment by LukasReschke** [comment]
Time to add an on-demand migration when an avatar is requested?

@rullzer Feasible?

**Comment by rullzer** [comment]
mmm ondemand is hard. Because either we need to store that it is succesfully migrated or we always look in 2 places when requesting the avatar when it doesn't exist.

**Comment by nickvergessen** [comment]
oc_preferences holds a value?
```
 	admin 	avatar 	version 	1
```
Can't we check this?

**Comment by rullzer** [comment]
I'll look into that

**Comment by rullzer** [comment]
Ok, so... if we would want live migration this would basically require more filesystem setup for each avatar. Probabaly adding it to the release notes or something makes more sense as for 99% of the people they will appear back within 15 minutes.

**Comment by MorrisJobke** [comment]
> Ok, so... if we would want live migration this would basically require more filesystem setup for each avatar. Probabaly adding it to the release notes or something makes more sense as for 99% of the people they will appear back within 15 minutes.

Yes - put it in there. We talked about this and the migration should be fast and not blocked by the avatar migration.

I also think that not available avatars until the cron job has run is acceptable here.

**Comment by MorrisJobke** [comment]
@karlitschek Opinion on this?

**Comment by karlitschek** [comment]
I agree. This is acceptable. The strategy to do long running migration steps in a background job is good. Exactly how it should be. But should mention this in the release notes.

**Comment by rullzer** [comment]
Added to changelog.
CC @jospoortvliet to make sure we communicate it
