### ISSUE TITLE
Allow non-rounded storage quotas

### ISSUE THREAD

**Issue by christianvw** [nextcloud/server#24002]
**Is your feature request related to a problem? Please describe.**
In our specific Nextcloud instance we need unrounded quotas, for example 1.8 TB. But Nextcloud does not allow to set those values, Nextcloud currently only accept values like `2 TB` or `10 GB`.

<details>
<summary>Background, why such values could be useful</summary>

We have 2TB storage for our nextcloud instance (2TB disks in RAID1 each). 

Our offsite backup also has a 2TB size. However, offsite backup also creates snapshots to allow versioning of the backups. These snapshots of course also need storage, since files that have been deleted will remain there for weeks.

We would like to deduct this storage space that these snapshots use from the quota in Nextcloud.

The problem should not only affect us, since most hard drives and rented storages have sizes of full TB.
</details>

**Describe the solution you'd like**
Please allow setting non-rounded quptas at `https://cloud.example.com/settings/users`

**Describe alternatives you've considered**
None.

**Additional context**

- Relevant database table: `oc_preferences` (`appid`: `files`, `configkey`: `quota`)
- The database structure allows values like `1.8 TB` (tested already), however the frontend does not allow entering non-rounded quotas. Tested with Nextcloud 20.0.1

**Comment by kesselb** [comment]
1800 GB would be to hard for your administrators?

**Comment by christianvw** [comment]
Does not work either - I tried that already :D

**Comment by rubo77** [comment]
closing in favor to #18468
