### ISSUE TITLE
User already exists API social_login

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#24003]
### Steps to reproduce
1. Create user in keycloak (or another same provider)
2. Assign him role, which allows to use Nextcloud
3. Using API, create user in Nextcloud
```
POST /ocs/v1.php/cloud/users HTTP/1.1
Authorization: Basic ***HIDDEN***
User-Agent: MSIE
Host: ***NEXTCLOUD HOST***
Accept: */*
OCS-APIRequest: true
Content-Length: 82
Content-Type: application/x-www-form-urlencoded

Array
(
    [password] => ***PASSWORD***
    [userid] => ***USER ID***
)
```

### Expected behaviour
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

### Actual behaviour
```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>failure</status>
  <statuscode>102</statuscode>
  <message>User already exists</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data/>
</ocs>
```

### Server configuration

**Operating system:**
Debian 10 Buster

**Web server:**
nginx/1.19.1

**Database:**
Percona xtradb-cluster 5.7.19

**PHP version:**
PHP 7.3.20

**Nextcloud version:** (see Nextcloud admin page)
19.0.1-fpm

**Updated from an older Nextcloud/ownCloud or fresh install:**
Rolling updates from 16 

**Where did you install Nextcloud from:**
 Docker image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No messages
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - admin_audit: 1.9.0
  - analytics: 2.5.0
  - apporder: 0.11.0
  - bookmarks: 3.4.3
  - calendar: 2.0.4
  - camerarawpreviews: 0.7.8
  - checksum: 0.4.5
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.0
  - contactsinteraction: 1.0.0
  - cookbook: 0.7.6
  - dashboardcharts: 0.1.3
  - dav: 1.15.0
  - deck: 1.1.2
  - dicomviewer: 1.2.2
  - encryption: 2.7.0
  - external: 3.6.0
  - extract: 1.2.4
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_automatedtagging: 1.9.0
  - files_downloadactivity: 1.8.0
  - files_external: 1.10.0
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.23
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_texteditor: 2.14.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - forms: 2.0.4
  - gpxedit: 0.0.13
  - gpxmotion: 0.0.11
  - gpxpod: 4.2.2
  - groupfolders: 7.1.0
  - groupquota: 0.1.4
  - keeweb: 0.6.3
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - mail: 1.4.1
  - maps: 0.1.6
  - music: 0.16.0
  - news: 14.2.2
  - notes: 3.6.4
  - oauth2: 1.7.0
  - ocr: 6.0.56
  - onlyoffice: 6.0.2
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quicknotes: 0.6.1
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - sociallogin: 3.4.1
  - socialsharing_email: 2.1.0
  - spreed: 9.0.4
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - tasks: 0.13.4
  - text: 3.0.1
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - appointments
  - nextcloud_announcements
  - notifications
  - phonetrack
  - theming
  - theming_customcss
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "theme": "mytheme",
        "blacklisted_files": [],
        "mail_smtpmode": "sendmail",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": 25,
        "mail_smtptimeout": 10,
        "mail_smtpsecure": "",
        "mail_smtpauth": false,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "logfile": "\/dev\/stdout",
        "enable_previews": true,
        "preview_max_filesize_image": 4096,
        "preview_max_y": 4096,
        "preview_max_x": 4096,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Photoshop"
        ],
        "logtimezone": "Europe\/Prague",
        "social_login_auto_redirect": true,
        "updatechecker": false,
        "has_internet_connection": true,
        "objectstore_multibucket": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "num_buckets": 15000,
                "bucket": "nextcloud-",
                "autocreate": true,
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "use_ssl": true,
                "hostname": "***REMOVED SENSITIVE VALUE***",
                "port": 443,
                "use_path_style": true
            }
        },
        "onlyoffice": {
            "jwt_header": "Authorization",
            "verify_peer_off": true
        },
        "loglevel": 3,
        "trusted_domains": [
            "nc.domain.org",
            "localhost",
            "10.*.*.*",
            "onlyoffice.domain.org",
            "nc-api.domain.org",
            "*cluster.local"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": false,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": "6379",
            "timeout": 0
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.1.1",
        "overwrite.cli.url": "https:\/\/nc.domain.com",
        "overwriteprotocol": "https",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "updater.release.channel": "stable",
        "maintenance": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
Minio S3 as default backend

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
Keyclak and Social login app in NC

#### Nextcloud log (data/nextcloud.log)
Nothing criminal for this operation

For me it is similar to https://github.com/nextcloud/server/issues/14796 but I'm using SSO instead of LDAP
For automated user creation I'm using such command: 
```
curl -X POST https://admin:<VERYSTRONGPASSWORD>@nc-api.domain.org/ocs/v1.php/cloud/users -H "OCS-APIRequest: true" -d userid="USER ID" -d password="USER PASSWORD"
```

**Comment by kesselb** [comment]
Why do you think that's an issue for nextcloud/server? I guess if social_login (the user_backend) says the user exist there is not much we can do.

**Comment by krakazyabra** [comment]
hi @kesselb 
It is nextcloud, who is reporting that, because I'm calling to `/ocs/v1.php/cloud/users`. And this endpoint reports, that user exists. Social login doesn't create users (it can, but this function is disabled). Because this is disabled by me, I have to create a user mannualy, for that I'm using Nextcloud API and executing `curl -X POST https://admin:<VERYSTRONGPASSWORD>@nc-api.domain.org/ocs/v1.php/cloud/users -H "OCS-APIRequest: true" -d userid="USER ID" -d password="USER PASSWORD"` 

@zorn-v am I right, that in this process social login does not take part?

**Comment by zorn-v** [comment]
> am I right, that in this process social login does not take part?

Yes, it use default "user backend" (NC database)

**Comment by kesselb** [comment]
cc @rullzer @ChristophWurst

**Comment by krakazyabra** [comment]
@kesselb @rullzer @ChristophWurst Is there any progress with it?

**Comment by ChristophWurst** [comment]
nope

**Comment by zorn-v** [comment]
More context - AFAIR this problem is "floating", may occur and may not. 
I think problem maybe in some "cloud config" (like k8s) and several distributed servers/containers.

**Comment by krakazyabra** [comment]
Yesterday I got idea: 
we're running nextcloud in 3 replicas with shared config and common DB, there is service in front of them, which is pointing to random replica of nextcloud. Can it be the cause of such message?

**Comment by zorn-v** [comment]
Em, with that message user actually created ? If yes - of course can. Some two requests on different servers, return first recieved and gotcha.

**Comment by ChristophWurst** [comment]
> we're running nextcloud in 3 replicas with shared config and common DB, there is service in front of them, which is pointing to random replica of nextcloud. Can it be the cause of such message?

do you also share the session data?

**Comment by krakazyabra** [comment]
>do you also share the session data?

Should I do it manually? I thought such kind of data should be in redis.

**Comment by ChristophWurst** [comment]
nah redis is perfectly fine. you just shouldn't use local files on each of the nodes :)

**Comment by krakazyabra** [comment]
>local files on each of the nodes 

No, there is NFS filesystem (read-write-many) with nextcloud, which mounts in /var/www/nextcloud of each replica :)

**Comment by krakazyabra** [comment]
Today I created dedicated replica of the same nextcloud (same nfs, db, redis, config), use separate url to access exactly this replica. Will try to point api requests to this single-replica. If error will go away - then the deal is in multi-replicas.

**Comment by krakazyabra** [comment]
After 5 months started to get this error again.  
Month ago upgraded Nextcloud to 19.0.10. 
Have no idea, why it appeared again. And have no idea, how to debug.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by krakazyabra** [comment]
I don't know about 21st version, I'm using 19th. And will use it until the end-of-life. So, please, try to find the solution for 19th version.

**Comment by ChristophWurst** [comment]
Well https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule

**Comment by krakazyabra** [comment]
that was unexpected xD
I'll upgrade to 20th and update current issue, or will close it.
