### ISSUE TITLE
Sharing calendar: First day of the week doesn't fit to locale

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#24014]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Limit a share by using the date picker

Note: Client OS, browser and NC are all set to German.

### Expected behaviour
Shown monthly calendar should fit to locale settings (in my case, German)

### Actual behaviour
Monthly calendar starts with Sunday, which is not fitting for German language
![calendar](https://user-images.githubusercontent.com/42836313/98583187-3f8be800-22c4-11eb-86da-ca2ca2a68395.png)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page) 19.0.4

### Client configuration
**Browser:** Firefox 82.0.2 (de_DE)

**Operating system:** Windows 10 x64 (de_DE)

**Comment by ikke-t** [comment]
also applies to Finland. Week does not start on Sunday here, but Monday.

![Screenshot from 2021-03-10 08-44-19](https://user-images.githubusercontent.com/1146409/110588168-557bbd80-817d-11eb-951b-570c4cc626e6.png)

**Comment by ikke-t** [comment]
oops, going back there, it shows it correctly the next time for finnish. So it only happens at the time one changes the locale setting. I just changed it to Finnish, and at the time time and date format got correct, but week start day was wrong. The next time loading the page also week start day was right, Monday.

**Comment by johkoenig** [comment]
Problem is still present on German NC 20.0.8
![grafik](https://user-images.githubusercontent.com/42836313/110597195-84476300-8180-11eb-9292-f179642b98c7.png)

**Comment by szaimen** [comment]
I can reproduce this on NC22 beta 5

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
