### ISSUE TITLE
Error when Upgrading to 20.0.1

### ISSUE THREAD

**Issue by AnemoiThuellai** [nextcloud/server#24015]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Attempted to upgrade several times
2. Attempted from Desktop 
3. Attempted from server-side using C-panel

### Expected behaviour
Software should upgrade to next version

### Actual behaviour
Received error log

### Server configuration

**Operating system:**
linux

**Web server:**
ecbiz261

**Database:**
bearand9_next892

**PHP version:**
7.2.33

**Nextcloud version:** (see Nextcloud admin page)
16.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from an older Nextcloud version. Original version: 16.0.1

**Where did you install Nextcloud from:**
Originally from c-panel

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
n/a
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
n/a
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Win 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_appconfig` (`appid`,`configkey`,`configvalue`) SELECT ?,?,? FROM `oc_appconfig` WHERE `appid` = ? AND `configkey` = ? HAVING COUNT(*) = 0' with params ["core", "oc.integritycheck.checker", "{\"core\":{\"EXTRA_FILE\":{\"core\\\/img\\\/filetypes\\\/mindmap.svg\":{\"expected\":\"\",\"current\":\"b0484953431f937d2f10f8a8e526498763275691bda9252179c5b386ed94fbff95cc635022940b32f10c52afc15112774c158464b4853b4224ff9a7b8f650d0c\"}}}}", "core", "oc.integritycheck.checker"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away
</details>

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
