### ISSUE TITLE
Add "cancel sharing" button in sharing overview

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#24010]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Cancelling shared files/folders requires too many steps.

**Describe the solution you'd like**
When looking at the Share Overview within Files & Folders, it shows me all shared ressources. Thats fine so far. However, one of the most used tasks here is to cancel the sharing once the user has received confirmation that the other party successfully downloaded the shared content. So, I propose to add a "quick cancel" button next to the sharing icon. This button should show up not only in the share overview, but also on the normal file list. 
See screenshot below.

**Describe alternatives you've considered**
The current way. Too many steps.

**Additional context**
![Cancel-Sharing](https://user-images.githubusercontent.com/42836313/98580624-91327380-22c0-11eb-98a2-a37c9868aa1b.png)

**Comment by kesselb** [comment]
cc @jancborchardt

**Comment by skjnldsv** [comment]
Would be nice!

**Comment by skjnldsv** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there a no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.
