### ISSUE TITLE
UI bug in sharing overview

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#24011]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open sharing overview
2.
3.

### Expected behaviour
No UI bug

### Actual behaviour
see:
![Ui error](https://user-images.githubusercontent.com/42836313/98581851-60533e00-22c2-11eb-84e9-601f7323a555.png)

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache 2.4

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Where did you install Nextcloud from:** nextcloud.com

### Client configuration
**Browser:** Firefox 82.0.2 with uBlock Origin

**Operating system:** Windows 10 x64

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2

**Comment by szaimen** [comment]
Fixed in https://github.com/nextcloud/server/pull/28015
