### ISSUE TITLE
Slow WebDAV performance

### ISSUE THREAD

**Issue by strongboy54** [nextcloud/server#24032]
Comparing speeds to uploading on WebDAV vs just direct drag and drop on the website, I get 10x higher speeds.
This has been tested with 100s of smaller files and larger 10GB+ files. Same issue is present. 
Using WebDAV is incredibly slow compared to other methods. 
Server has encryption with default module. 

**Server configuration**

Operating System: | Linux 5.4.0-52-generic x86_64
CPU: | Intel(R) Xeon(R) CPU E5-2620 v2 @ 2.10GHz (6 cores)
Memory: | 19.55 GB
Free Space: 1.3 TB

### Server configuration (Check attachment: 2020-11-10.txt)

**Operating system:**
Ubuntu 20.04

**Database:**
MariaDB

**PHP version:**
Version: 7.4.3
Memory Limit: 16 GB
Max Execution Time: 3600
Upload max size: 16 GB

**Nextcloud version:** (see Nextcloud admin page)
20.0.1 - 20.0.1.1

```
No errors have been found.
```

[Annotation 2020-11-10 155359](https://user-images.githubusercontent.com/31914358/98682780-f774d000-236c-11eb-94c5-610dbc7f0585.png)

[2020-11-10.txt](https://github.com/nextcloud/server/files/5517801/2020-11-10.txt)

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favour of https://github.com/nextcloud/server/issues/22045. Feel free to add your findings over there. There is a overhead by using Nextcloud. If you look for the maximum performance you might use a different tool. 

>  just direct drag and drop on the website

If you drag a file on the website it also uses webdav to upload the file.

**Comment by madscientist42** [comment]
This issue is...ahem...separate...from the linked...FWIW.

WebDAV IS involved with the other- but it's **_WebDAV_**, not upload.  Seriously?
