### ISSUE TITLE
Arabic language disappeared from NC 20

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/server#24031]
HI Everyone 

It seems that Arabic language is disappeared from nextcloud 20
I have another NC ver 19 and it's still there in the language menu. 

Thank you. 

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** Apache2.4

**Database:** Maria db

**PHP version:** 7.4

**Nextcloud version:** 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install: Frash installation

**Comment by j-ed** [comment]
I assume that only a minority of users in this forum can read an arabic language, therefore it would be helpful if you could post a screenshot of the language settings to get an idea how the writing should look like.

In v20.0.1 I found the following languages listed at the bottom of the dialog. Is the desired language listed?

![grafik](https://user-images.githubusercontent.com/2572764/98723230-61ec3700-2392-11eb-840c-b10d105b674b.png)

**Comment by FALErwi** [comment]
Hi

Thank you for your advice. 

![IMG_20201111_030557](https://user-images.githubusercontent.com/74250574/98748488-d642cc80-23ca-11eb-9c82-2a4ae5f772ad.jpg)

**Comment by FALErwi** [comment]
It's OK now.
