### ISSUE TITLE
Trashbin: no "restore" action and missing previews

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2407]
The trash bin no longer shows a undelete operation.

![trash](https://cloud.githubusercontent.com/assets/1589737/20715760/7def43c4-b650-11e6-925b-5932eb91285c.png)

Also there is no preview if encryption is enabled. Both works on stable10:

![trash - stable10](https://cloud.githubusercontent.com/assets/1589737/20716071/7d0fdc06-b651-11e6-8926-1ecb8e9d8c44.png)

cc @rullzer for the previews

Regarding the "restore" action, the code is still in the template, don't know why it is no longer visible https://github.com/nextcloud/server/blob/master/apps/files_trashbin/templates/index.php#L34

**Comment by rullzer** [comment]
Fix for the preview in #2415 

Here it does show the restore option btw...

**Comment by rullzer** [comment]
@schiessle #2415 is in. I can't reproduce the restore that is missing. So can't help there.

**Comment by schiessle** [comment]
@rullzer thanks, previews work fine again. Do you see the restore button next to the file, like in the second screenshot? I just tried again on master with Firefox and Chromium, no restore button for me.

**Comment by rullzer** [comment]
yes I do...

**Comment by schiessle** [comment]
Strange, I tried everything, delete browser cache, etc.... The restore button is not there. Can someone else verify if this is rally just me... cc @nickvergessen @MorrisJobke

**Comment by nickvergessen** [comment]
Previews work here, but the "Restore" action is missing. But it works with the "Restore selected" option.

**Comment by schiessle** [comment]
> But it works with the "Restore selected" option.

Yes, this also works for me. But it should work without selecting the file first. If you inspect the HTML code you will see that the code for the restore button is there but for some reasons it is not shown. Couldn't figured out why.

**Comment by rullzer** [comment]
Mmmm clean setup and now it is missing indeed
seems some weird CSS magic I might have a fix
