### ISSUE TITLE
Improve error message for missing .ocdata

### ISSUE THREAD

**Issue by Micha-Btz** [nextcloud/server#24074]
Hi there,

I have to move my nextcloud to a different webspace and of course there are all paths different from the old one.

> cloud$ /opt/plesk/php/7.3/bin/php occ db:add-missing-indices
> Your data directory is invalid
> Ensure there is a file called “.ocdata” in the root of the data directory.
> 
> Cannot create “data” directory
> This can usually be fixed by giving the webserver write access to the root directory. See https://docs.nextcloud.com/server/19/go.php?to=admin-dir_permissions

better would be to tell the user where nextcloud is looking for, for example 

> /opt/plesk/php/7.3/bin/php occ db:add-missing-indices
> Your data directory is invalid: /var/www/vhosts/******/owncloud/data
> Ensure there is a file called “.ocdata” in the root of the data directory.

Also would be great if this can check for the right permissions and can suggest changes, like data folder should have chmod xxx rights.

Thanks

Micha

https://help.nextcloud.com/t/problems-after-migrateing-nextcloud-to-a-new-webspace/97807

**Comment by Micha-Btz** [comment]
Aslo it would be great to set a new path per occ config:newpath ..... to avoid editing the database itself.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
