### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by hitam4450** [nextcloud/server#24073]
![update_20 01](https://user-images.githubusercontent.com/9738727/98956961-f2e12080-2500-11eb-8a51-1dacb936e25b.png)

Hi, the update process failed continuously and repeatedly  at step 5 of the process ( see screenshot!)

Issuing 

sudo -u www-data php occ maintenance:repair

clears the error message, but does not resolve the issue !

What is to do to upgrade successfully ?

regards, hitam4450

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
Thank you!
