### ISSUE TITLE
Content Security Policy violation: Error in webconsole

### ISSUE THREAD

**Issue by cloud2018** [nextcloud/server#24089]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Describe the bug:
Nextcloud setting/apps causes Content Security Policy violations when loading images (in AppItem.vue, 152, image.src = this.app.screenshot)

### Steps to reproduce
1. open ..../settings/apps/enabled
2. open webconsole of browser
3. see errors:
```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://raw.githubusercontent.com/nextcloud/logreader/master/screenshots/reader.png blockiert ("img-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://raw.githubusercontent.com/nextcloud/text/master/img/screenshots/screenshot1.png,https://raw.githubusercontent.com/nextcloud/text/master/img/screenshots/screenshot2.png,https://raw.githubusercontent.com/nextcloud/text/master/img/screenshots/screenshot3.gif blockiert ("img-src").
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf https://user-images.githubusercontent.com/245432/43194622-1a40ce90-9003-11e8-8101-15d08cce7264.png blockiert ("img-src").

```

### Expected behaviour
No errors in webconsole and don't try to download ressources from other webservers

### Actual behaviour
3 time nextcloud try to download png-files from foreign hosts

### Server configuration
**Nextcloud version:**
Nextcloud 20.0.1
**App versions**
Log Reader 2.5.0
Text 3.1.0

**Comment by kesselb** [comment]
cc @rullzer @juliushaertl @icewind1991

**Comment by juliushaertl** [comment]
Seems to be an issue with apps that are not in the app store, so the appstore image proxy isn't available but have a screenshot in the appinfo.xml

**Comment by juliushaertl** [comment]
If the app is not on the app store the image proxy cannot return the image so we should not try to show it.

**Comment by eliasp** [comment]
Doesn't seem to be a problem of external apps, as I'm seeing those messages also for [nextcloud/logreader](https://github.com/nextcloud/logreader) or [nextcloud/text](https://github.com/nextcloud/text) on Nextcloud 22.1.1 and Firefox 91.0

```
Content Security Policy: The page’s settings blocked the loading of a resource at https://raw.githubusercontent.com/nextcloud/logreader/master/screenshots/reader.png (“img-src”). AppItem.vue:152
Content Security Policy: The page’s settings blocked the loading of a resource at https://user-images.githubusercontent.com/245432/43194622-1a40ce90-9003-11e8-8101-15d08cce7264.png (“img-src”). AppItem.vue:152
Content Security Policy: The page’s settings blocked the loading of a resource at https://raw.githubusercontent.com/nextcloud/text/master/img/screenshots/screenshot1.png,https://raw.githubusercontent.com/nextcloud/text/master/img/screenshots/screenshot2.png,https://raw.githubusercontent.com/nextcloud/text/master/img/screenshots/screenshot3.gif (“img-src”). AppItem.vue:152
```
