### ISSUE TITLE
Improve error message for not existing column

### ISSUE THREAD

**Issue by ocram1095** [nextcloud/server#24083]
Hello guys,
while upgrading from 17.0.1.10.1 to 18.0.10.2 the following error message occured. 

For context:
`Occured error: "InvalidArgumentException: Column name \"iqmUw_flow_operations\".\"entity\" is NotNull, but has empty string or null as default."`

It happens here:
https://github.com/nextcloud/server/blob/35be4fdb019da658a824f41dc4bf0f415c032cb8/lib/private/DB/MigrationService.php#L519

After a look in the source code i found that the real reason for this error is a missing column not else.
I think it would be a good improvement to change this message to:

`Column <column> with <type> in <table> not found`

I was able to solve my mistake on my own, but it would certainly be helpful for the future if the message were more meaningful.

Thanks.

Marco

**Comment by kesselb** [comment]
Sounds good to me. Mind to send a pull reqeust?

cc @nickvergessen @MorrisJobke

**Comment by nickvergessen** [comment]
already part of #24055

**Comment by nickvergessen** [comment]
Or well my PR adjusts the error message a bit. The error happens before the column is created and in this case can't be created.
