### ISSUE TITLE
Cannot select last item in file picker

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#2408]
The last item in the file picker file list is overlapped by a white gradient and therefore not selectable.

You can see the gradient on the folder icon here:
![bildschirmfoto von 2016-11-29 16-58-56](https://cloud.githubusercontent.com/assets/1374172/20717248/393df766-b655-11e6-8726-95a41682ca5d.png)
(resized the window to have a shorter list)

cc @icewind1991 @skjnldsv

**Comment by skjnldsv** [comment]
Will someone ever get such a small window height? :p

**Comment by ChristophWurst** [comment]
> Will someone ever get such a small window height? :p

That's unrelated. I just resized to a smaller window because I was too lazy to create some folders :-) This is an issue with standard windows sizes too.

**Comment by skjnldsv** [comment]
Well, there is a white space at the end of the list to prevent that.

**Comment by ChristophWurst** [comment]
Current master:
![bildschirmfoto von 2016-11-29 17-25-30](https://cloud.githubusercontent.com/assets/1374172/20718393/ddb4b160-b658-11e6-9264-65f6ab864c7a.png)
Ignore the missing folder icons, something's screwed up on my dev env.

There are 1 or two pixel of the very last image that are clickable on the top. The rest isn't.

**Comment by ChristophWurst** [comment]
As always, it works on Chrome:
![bildschirmfoto von 2016-11-29 17-27-46](https://cloud.githubusercontent.com/assets/1374172/20718485/31dbd7b4-b659-11e6-8e7c-7a1a9c721f0e.png)

**Comment by skjnldsv** [comment]
AHahaha, sorry! I should have checked!

**Comment by ChristophWurst** [comment]
Well, I should have mentioned that I'm using FF 😉
