### ISSUE TITLE
Share icon is not updated just after share by mail or link

### ISSUE THREAD

**Issue by medcloud** [nextcloud/server#24086]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to NextCloud server with following actived plugins : "Share by mail" & "File sharing"
2. Select a folder or file, and share by mail or by link

### Expected behaviour
Just after clicking on the email, the share would be added and shared icon on the ritght side of folder icon changed

### Actual behaviour
Just after clicking on the email, the share is added, but no shared icon change > you must refresh webpage to see icon updated

This is a regression because it was working well on NC17.

#### Just after adding the share, without F5 refresh

![Bug Share by mail icon 1](https://user-images.githubusercontent.com/42641918/99018775-2f416a80-255b-11eb-9f99-10fbc90d7ac9.png)

#### Just after F5 webpage refresh
![Bug Share by mail icon 2](https://user-images.githubusercontent.com/42641918/99018587-bd692100-255a-11eb-8d41-182dcd2cb4b2.png)

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache 2.4

**Database:**
PG10

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
NextCloud v 20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
NextCloud v 17.0.9

Login as admin user into your Nextcloud and access
http://example.com/index.php/settings/integrity/failed, paste the results here.
No errors have been found.

List of activated apps:
Accessibility 1.6.0
Activity 2.13.2
Calendar 2.1.2
Comments 1.10.0
Contacts 3.4.1
Contacts Interaction 1.1.0
Custom CSS 1.7.0
Dashboard 7.0.0
Data Request 1.7.0
Deleted files 1.10.1
DICOM Viewer 1.2.2
External sites 3.7.1
File sharing 1.12.0
Group folders 8.1.0
Log Reader 2.5.0
Notifications 2.8.0
Password policy 1.10.1
PDF viewer 2.0.1
Photos 1.2.0
Recommendations 0.8.0
Right click 0.17.0
Share by mail 1.10.0
Support 1.3.0
Text 3.1.0
Theming 1.11.0
Update notification 1.10.0
Usage survey 1.8.0
User status 1.0.0
Versions 1.13.0
Video player 1.9.0
Weather status 1.0.0

**Are you using external storage, if yes which one: no

**Are you using encryption: no

**Are you using an external user-backend, if yes which one: no

### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

**Operating system:**
Windows 10 Version 10.0.19041 Numéro 19041

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
