### ISSUE TITLE
No Nextcloud app template at Openshift

### ISSUE THREAD

**Issue by tarsisnet** [nextcloud/server#241]
Hello there,

I was told at the Freenode Nextcloud-dev channel to file an issue here.

The thing is we would like to try Nextcloud at Openshift. We found there is an OC app template, but no NC. We rather prefer to test on NC so, do you have a schedule to create such an app template?

Thank you for your help and keep up the good work!

**Comment by MorrisJobke** [comment]
> do you have a schedule to create such an app template?

We don't have a plan to add this template. If this is done by somebody we would really love this, but it is not on our schedule. Anybody who want to help out here is very welcome.
