### ISSUE TITLE
Upload 2G or more large file prompt 504 error:'Error when assembling chunks,status code 504'

### ISSUE THREAD

**Issue by pianshanchou** [nextcloud/server#24109]
![99085070-b85fac80-2602-11eb-8e89-0e13f9c28902](https://user-images.githubusercontent.com/1827701/99090424-99b0e400-2609-11eb-9d52-46fe78ee021c.png)

I made some attempts, and when I was uploading a 1.5G file, it was normal. But when I upload files above 2G, it will prompt 504 error.

Refresh the page, the file exists. It took me about three minutes to upload the file.

![99085151-d1685d80-2602-11eb-8ead-30aeb1726e08](https://user-images.githubusercontent.com/1827701/99090472-a8979680-2609-11eb-94b3-da66c536b34e.png)
![99085531-43d93d80-2603-11eb-9143-06494d9bed98](https://user-images.githubusercontent.com/1827701/99090479-aa615a00-2609-11eb-8407-3490283a97b4.png)

I tried to find a solution on the Internet, which didn’t help me. This problem has been bothering me for several days.

**Comment by JonathanTreffler** [comment]
Are you using a reverse proxy ?

**Comment by pianshanchou** [comment]
> 您是否在使用反向代理？

![058c6e33645c9d986d2052947f8797c8578eef18](https://user-images.githubusercontent.com/1827701/99102563-35961c00-2619-11eb-8765-ed8095c3cf89.png)
I didn't use the reverse proxy. I used web to install nextcloud instead of docker. Just now, I adjusted an official method, but the problem still remains unsolved.

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing this report in favour of https://help.nextcloud.com/t/upload-2g-or-more-large-file-prompt-504-error/98039. Please avoid cross posts.

**Comment by kesselb** [comment]
Also have a look at:

- https://github.com/nextcloud/server/issues/22936
- https://github.com/nextcloud/server/issues/17992
