### ISSUE TITLE
Share sidebar actions not working after renaming file

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24101]
### Steps

1. Upload a file "test.txt"
1. Open the share tab in the sidebar for that file
1. Rename "test.txt" to "test2.txt"
1. In the still open sidebar, click any share action, like "Share link" or pick a recipient.

### Expected result
Sharing works

### Actual result
404 error in network console. The path used there is still "test.txt".

### Version
NC server git master 25f8d76f266d53fa4b6f0f3c4fa65febc7b31253

This works correctly in NC 20 so this is a regression, likely introduced by recent refactorings in the sidebar code.

**Comment by blizzz** [comment]
is this still valid?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
