### ISSUE TITLE
When i click download a folder, it shows en error

### ISSUE THREAD

**Issue by GretaD** [nextcloud/server#24105]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open files and find a folder
2. Click Action-Menu for that Folder
3. Download

### Expected behaviour
The folder is downloaded.

### Actual behaviour
Tell us what happens instead
![file-error](https://user-images.githubusercontent.com/12728974/99078744-2da98e00-25bf-11eb-946f-60de3d5ba75d.png)

### Server configuration

**Operating system:** Ubuntu

**Nextcloud version:** 21 alfa

**Comment by PVince81** [comment]
happening for all folders ? if yes then it could be a regression.

works for me locally on master (32ded877dc30b18f6eba7f3854988ce2992feb00)

**Comment by GretaD** [comment]
It used to happen with all the folders i had, but now all looks good. Thank you
