### ISSUE TITLE
Allow associating file types with editors ("Open With") for users

### ISSUE THREAD

**Issue by asoltesz** [nextcloud/server#24110]
**Is your feature request related to a problem? Please describe.**

Nextcloud applications often do not associate with all of the file types they are capable of editing. In this case the user can only download the file even though one of the Nextcloud apps could edit it perfectly well.

Sometimes an application associates with types for which it is not the optimal editor (e.g.: the new "Text" application now badly mishandles Markdown files) and that makes it impossible to use an other, more suitable application for editing that file (e.g. the "Markdown Editor" application).  

**Describe the solution you'd like**

Simply allow the user to override default file type associations with an "Open with" context menu item.

That should present all of the available editor applications in a list. The user selects an application and the document opens in that application's editor.

Also allow the user to make Nextcloud remember the association so that next time, it automatically opens all of the files with the same extension with the selected editor application. This should be specific for that user, not for all users (altough it would be nice if an admin user could set a global / system level default assotiation like this)

NOTE: This is the standard solution for this problem in all major desktop environments and should work in Nextcloud too.

**Describe alternatives you've considered**
-

**Additional context**

Editing files in Nextcloud can be very frustrating and provide a worse experience than it could with intelligent editor selection.

**Comment by szaimen** [comment]
cc @nextcloud/designers does this make sense and is it feasible?

**Comment by juliushaertl** [comment]
Related discussion for collabora https://github.com/nextcloud/richdocuments/issues/1400#issuecomment-811794266
