### ISSUE TITLE
Previews for empty files broken

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2413]
Steps to reproduce:

1. Create a empty text file in the web ui
2. edit the file and add some content
3. go to versions drop down

Result:

broken preview for the empty version of the file (should fall back to the mime icon)

![versions](https://cloud.githubusercontent.com/assets/1589737/20719799/50174f16-b65d-11e6-8288-4d0f6e9b1cbe.png)

cc @rullzer

**Comment by rullzer** [comment]
I'll have a look

**Comment by rullzer** [comment]
Fix in #2414
