### ISSUE TITLE
After closing a PDF, go back to the exact position the file list was before

### ISSUE THREAD

**Issue by Jennes** [nextcloud/server#24132]
# Current behaviour

When you open a PDF document from the end of a longer list in the *files* app, and then close it again, the view jumps back to the beginning of the list.

# Desired behaviour

After closing the document, the file list browser jumps to the beginning of the file list, no matter what. This is quite uncomfortable because I often look for a particular pdf generated by my scanner, which are always named like "scan-2020111-001.pdf" and so on.

Alternatively, a display filter could be used, where the amount of files displayed is limited to matching entries only, like for example "\*202011\*pdf", so that only scans from November 2020 would be shown.

Edit: I just saw, that such a filter already exists. Anyways, it would be a lot more convenient, if closing a PDF would jump back to the list where it was before

**Comment by szaimen** [comment]
I think this was fixed with NC20.
