### ISSUE TITLE
Showing issue as file is locked

### ISSUE THREAD

**Issue by varunprakashnkl** [nextcloud/server#24131]
It keep on showing as file is locked what's the solution to upload a file in our drive.

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
