### ISSUE TITLE
Add-Missing-Primary-Keys

### ISSUE THREAD

**Issue by cliffmcl** [nextcloud/server#24142]
Hi Folks

I have just upgraded to NC 20 on my Ububtu Server and fallen foul of the Add-Missing-Primary -Keys not defines message. I found this article - https://github.com/nextcloud/server/pull/24097/commits/7e042af66a63db20c543418239aa401fc22bb042 - which suggests I edit the register_command.php file. Could one of you kind folk please give me an indication where this file is located?

Thanks

**Comment by AlexG-78** [comment]
check https://github.com/nextcloud/server/issues/24084

**Comment by cliffmcl** [comment]
> check #24084

Thanks. I'd already read that but I'm more proficient with Windows and a relative Newbie to Linux and complete Newbie at GitHub. 

Could you possibly give me a step by step to making the changes? I searched but can't locate theregister_command.php file on my system. 

Thanks

**Comment by AlexG-78** [comment]
Go to you install folder, for example /var/www/html/nextcloud/core/
Open the file register_command.php
Add the following at line 104:
`$application->add(new OC\Core\Command\Db\AddMissingPrimaryKeys(\OC::$server->getDatabaseConnection(), \OC::$server->getEventDispatcher()));
`
Then run the occ command to update the primary keys.
php occ db:update_primary_keys

Hope this helps

**Comment by cliffmcl** [comment]
Thanks for coming back so quickly. Yeah it really helps when you know where to look!

Found and edited and it worked a treat.

Thanks for your patience and help
