### ISSUE TITLE
function findMatchingRoute doesn't support nextcloud hosted in subdirectory

### ISSUE THREAD

**Issue by StCyr** [nextcloud/server#24144]
https://github.com/nextcloud/server/blob/769f59ec657a4dcb993550ef33341015d5ea7942/lib/private/Route/Router.php#L245

function assumes nextcloud is always at the webroot. Could we change that?

for example by changing `substr` tests by `strpos`?

or by adding `strpos` tests after the `substr` tests, and before the final `else` clause?

That shouldn't be an issue if you have good unit tests :-)

**Comment by StCyr** [comment]
Current behaviour causes issues like these: https://github.com/nextcloud/mail/pull/4044

**Comment by szaimen** [comment]
cc @nextcloud/server-triage

**Comment by StCyr** [comment]
If I can help....

**Comment by mejo-** [comment]
I stumbled across this issue while debugging [issue "Search does not include Page contents"](https://gitlab.com/collectivecloud/collectives/-/issues/184) in the Colectives app.

I opened a PR to fix this issue: #27971

**Comment by mejo-** [comment]
So I went ahead and opened a new PR in order to fix this issue: #28303 

Reviews welcome :blush:
