### ISSUE TITLE
The language of the region

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#24143]
Steps:

1. Select "Settings" from the menu.
2. Select "Personal Info".

The selection of the region is not in the native language despite the set language, e.g. Polish.

![obraz](https://user-images.githubusercontent.com/47037905/99185261-e949f980-2748-11eb-9294-8ea363133f2a.png)

App:
Nextcloud 20.0.1

**Comment by nickvergessen** [comment]
Moving to server as that is not from the tos app

**Comment by Valdnet** [comment]
Does it have to do with showing months in the gallery?
Issue: https://github.com/nextcloud/photos/issues/708.

**Comment by szaimen** [comment]
I think it is a duplicate of https://github.com/nextcloud/server/issues/14822

**Comment by Valdnet** [comment]
@szaimen This is not a duplicate as this issue is related to not displaying translated text strings in NC that already exist. It should be open.
A similar problem was with the lack of text strings in Transifex which should be closed 😉.
