### ISSUE TITLE
Version history needs to show modification time.

### ISSUE THREAD

**Issue by vasyugan** [nextcloud/server#24157]
The versions history should show the modification time, not just the number of days that the last modification is in the past, else I get this:
![grafik](https://user-images.githubusercontent.com/3313208/99246139-1360f180-2805-11eb-8239-19779bb2f4a7.png)

It doesn not indicate which version is the earlier one and at which time of the day the modifications were done, which I really need to know to decide which version is the one I am looking for.

**Comment by kurn77** [comment]
Hello, modification date is visible if you keep the mouse on the information "2 days ago". However, I confess that a precise date / hour is probably a more relevant information for such a functionality.

**Comment by szaimen** [comment]
cc @nextcloud/designers does this make sense?

**Comment by bes1002t** [comment]
@szaimen yes. Sometimes you want to know the exact time.

My proposal would be one of these two solutions (1 is my favorite)
![1](https://user-images.githubusercontent.com/3890580/125493896-606c2d5c-5ea4-4434-90a9-947edb42b866.png)
![2](https://user-images.githubusercontent.com/3890580/125493898-9467a3f5-4e1d-44eb-a9a5-f73fdd7b9ea0.png)
:

**Comment by skjnldsv** [comment]
Done since Nc 26
