### ISSUE TITLE
[Feature Request] Add to a Project as Flow

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#24167]
My request is for adding to a [Project](https://github.com/nextcloud/server/issues/22897) via Flow app.

Ideally I could use it to add all supported project functionality (Talk, Deck, Files) to a project as a flow.  Might make it easier in helping other apps to add Project support if they already support Flow app.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
