### ISSUE TITLE
Calendar room and resource booking UI

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#24175]
The calendar has a lose end regarding rooms and resources.

The event creation window offers to add rooms and resources to an event:

![image](https://user-images.githubusercontent.com/1804221/99369917-4e266080-28bd-11eb-9bd8-7b32d58b1868.png)

However, those rooms and resources cannot be managed either on the GUI or on the command line.

The back-end part seems to be done: https://github.com/nextcloud/server/pull/9773.
According to https://github.com/nextcloud/server/pull/10027#issue-197799693, a GUI component was planned but has never happened yet.

**Comment by Spartachetto** [comment]
There are multiple requests on how the resource management works also in the forum. 
In addition this resources management functionality was listed also in one of the release notes.
I am writing this hoping it is useful information....

**Comment by cybertschunk** [comment]
hey, i found this issue while searching for this exact problem. I would really like to book ressources like rooms for an calendar entry. Is there any progress expectable in this issue?

**Comment by j-ed** [comment]
Based on information from the following issue ticket, an api endpoint exists to handle resources:

https://github.com/nextcloud/server/issues/17961#issuecomment-554401645

One of the developers has already worked on a resource booking gui in the past, but the project seems not to be worked on anymore because it has been "archive" in the meantime:

https://github.com/georgehrke/admin_resource_booking_database

**Comment by cybertschunk** [comment]
hey @j-ed thanks for your answer. Unfortunately I couldn't find any documentation for the api in the [docs ](https://docs.nextcloud.com/server/latest/developer_manual/). Do you know where documentation for the backend in question might be located?

**Comment by ThinkOli** [comment]
Well, I'm desperately looking for an alternative to Outlook (MS365) or Google calendar resource booking.  But unfortunately, there doesn't seem to exist a user friendly solution.
Having tried to get https://github.com/georgehrke/admin_resource_booking_database to work, but unfortunately, upon the local install of the app onto NC 20, settings are not available - which is very reasonable given it was built for NC 14 3 years back.
I then got me the latest version of the calendar app and tried to leverage the 'location' field - but that's nothing more than a comment field: not at all related to any bookable resource.
Resource booking really would be a killer app with NC and a great addition to the overall toolsuite. Any chance the great preparation work of @georgehrke will make it into a release? What would be required? May I contribute to get the work funded? I don't see an open bounty herefore.
I'll highly appreciate an update hereon!

**Comment by go2sh** [comment]
Read the announcement for the NC22 beta. I guess it will be part of it and you can already try it via the beta. ;-)

**Comment by ChristophWurst** [comment]
The new back-end app is https://github.com/nextcloud/calendar_resource_management. There are still some things to do, but you can define your resources with a few straight forward occ commands. Calendar and other compatible applications will show them.
