### ISSUE TITLE
Can't start Nextcloud because the version of the data (20.0.2.0) is higher than the docker image version (20.0.1.1) and downgrading is not supported.

### ISSUE THREAD

**Issue by Turab** [nextcloud/server#24174]
As seen in the title, I am running Nextcloud in a docker container from official release in Docker Hub. I had upgraded from 20.0.1.1  to 20.0.2.0 via Nextcloud admin panel. For a reason I needed to restart the container. Now it wouldn't start because image is 20.0.1.1. I checked the old threads and issues about this and saw that it is quite common but I couldn't find a solution. I would have tried to upgrade the docker image too; but I can't since there is no image released for 20.0.2.0 yet.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
