### ISSUE TITLE
Dashboard: allow andmins to define the default themes and widgets of the users dashbaord

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#24187]
I think it would be really useful for large setups if the admin could define the default background color/image of the dashboard for a unified corporate identity and maybe even the widgets everybody sees by default.

cc @nextcloud/designers

**Comment by juliushaertl** [comment]
With https://github.com/nextcloud/server/pull/23588 we use the login image background if the admin has configured one as a default. I guess that should cover most of the requirements, or?

**Comment by szaimen** [comment]
the picture option and default widget option are implemented in the meantime.
