### ISSUE TITLE
Broken link to issue template in CONTRIBUTING.md

### ISSUE THREAD

**Issue by milkomeda** [nextcloud/server#2418]
see link
`[template]: https://raw.githubusercontent.com/nextcloud/server/master/.github/issue_template.md`
in
`https://github.com/nextcloud/server/blob/master/CONTRIBUTING.md`

The link results in an `404: Not Found`.

The directory `.github`  directory does not exists in `nextcloud/server/master/`.

**Comment by icewind1991** [comment]
Thanks for spotting the error, fix is here: https://github.com/nextcloud/server/pull/2419
