### ISSUE TITLE
Error requesting the password

### ISSUE THREAD

**Issue by mvvvmd** [nextcloud/server#24199]
# Steps to reproduce
1. Create a share link for a file with password protection
2. Open the link in a different browser or private window
3. Click on the Request Password button
![Screenshot from 2020-11-18 09-29-10](https://user-images.githubusercontent.com/15438922/99509610-42eb3780-2986-11eb-81da-b6dbc1942f8c.png)

### Expected behaviour

Either the button should not be there or clicking should provide a useful action for the user.

### Actual behaviour

The error "Error requesting the password" is produced

### Server configuration

**Operating system:**

Ubuntu 18.04

**Web server:**

Apache 2.4

**Database:**

Mariadb 10.1

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)

20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

Both

**Where did you install Nextcloud from:**

nextcloud.com

**Comment by viper4gh** [comment]
Same Problem with:
Nextcloud: 20.0.2
OS: Ubuntu 20.04
Web Server: Apache 2.4.41
DB: mysql 8.0.22
PHP: 7.4.13
Updated from an older Nextcloud/ownCloud or fresh install: both
Where did you install Nextcloud from: nextcloud.com

**Comment by dominikjannis** [comment]
Same Problem with:
Nextcloud 20.0.3 on

**OS:**
Ubuntu 18.04

**Web Server:**
Apache 2.4

**Database**:
Mariadb 10.1

**PHP version:**
7.4

**updated:**
19.06 -> 20.03

**installed from:**
via Plesk extension

**Comment by mvvvmd** [comment]
Duplicate issue [4523](https://github.com/nextcloud/spreed/issues/4523)

**Comment by mvvvmd** [comment]
I'm closing this one as the issue at the nextcloud/spreed repo is in the milestone for the next version to be fixed.
