### ISSUE TITLE
Nextcloud v18 - Not compatible with composer v2

### ISSUE THREAD

**Issue by anthosz** [nextcloud/server#24202]
### Steps to reproduce
1. Install php 7.4 + composer v2
2. composer install --no-dev -o

### Expected behaviour
Generating optimized autoload files OK

### Actual behaviour
`Class OC_API located in ./lib/private/legacy/api.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_App located in ./lib/private/legacy/app.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_DB located in ./lib/private/legacy/db.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_DB_StatementWrapper located in ./lib/private/legacy/db/statementwrapper.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Defaults located in ./lib/private/legacy/defaults.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_EventSource located in ./lib/private/legacy/eventsource.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_FileChunking located in ./lib/private/legacy/filechunking.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Files located in ./lib/private/legacy/files.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Helper located in ./lib/private/legacy/helper.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Hook located in ./lib/private/legacy/hook.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Image located in ./lib/private/legacy/image.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_JSON located in ./lib/private/legacy/json.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Response located in ./lib/private/legacy/response.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Template located in ./lib/private/legacy/template.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_User located in ./lib/private/legacy/user.php does not comply with psr-0 autoloading standard. Skipping.
Class OC_Util located in ./lib/private/legacy/util.php does not comply with psr-0 autoloading standard. Skipping.`

### Server configuration
**Operating system:** RHEL 7
**Web server:** Apache 2.4
**Database:** NC
**PHP version:** 7.4
**Nextcloud version:** 18.0.10
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Comment by ChristophWurst** [comment]
>  composer install --no-dev -o

Why would you need that? Our releases don't require you to do this

**Comment by anthosz** [comment]
To ignore 👍 

Indeed, not needed
