### ISSUE TITLE
LDAP login external storage with Log-in credentials, save in database, not works

### ISSUE THREAD

**Issue by gerardjm** [nextcloud/server#24201]
#22413 # Steps to reproduce
1. Create a SMB external storage
2 .Use Log-in credentials, save in database
3.

### Expected behaviour
WEB UI open the folder

### Actual behaviour
Folder not open, give mount error, If use used entered, save in session, it works

### Server configuration

**Operating system:**
Ubuntu 20

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgrade from 18 to 19 to 20

**Where did you install Nextcloud from:**
Hannson IT VM compilation

**Comment by sparunakian** [comment]
Hi,

I just encountered the same problem with Nextcloud 20.0.1. In the Samba logs, they were multiple lines indicating that Nextcloud tried to log in with the Nextcloud administrator credentials, even when using a normal user on Nextcloud. Downgrading to Nextcloud 19.0.4 solved the issue.

Regards

**Comment by gerardjm** [comment]
Hi,

Thanks, then the problem is with version 20.0.1? it will be fix in next version?

I cannot do a downgrade all is updated.

**Comment by jaygearhead** [comment]
also happening on 20.0.4 with new users, existing users still seem to work

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by ynott** [comment]
> Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

It's not happening on NC21.0.2.
Thank you very much.

I think that we can close this issue.
