### ISSUE TITLE
Improve messages for uploading users

### ISSUE THREAD

**Issue by Pierre-de-la-Verre** [nextcloud/server#24205]
Based on the discussion here
https://help.nextcloud.com/t/meldungen-fur-fehlerhafte-uploads/98418/8
I want to write this FR.

A user, uploading data to a link that he received, gets this information:
https://help.nextcloud.com/uploads/default/original/3X/b/f/bf1ac67d552a79f7b04d0c18fd19aa0b891bd0ae.png

First step - important:
- increase the space for the displayed filenames. Long names now are truncated
- give information what the icons (e.g. the exclamation mark; maybe more) want to say - e.g. add tooltips or text information
- give information why the upload failed

Second step - more comfortable:
- improve the display of maaaaany uploaded files. Now it is only one column - maybe it can be switched to 2 or three columns, to be displayed sorted and so.
- for biig files, check the free space in the cloud and warn the user that his biiig file is to big for current free space

Thanks to all!

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
