### ISSUE TITLE
Client on MacOS 10.15.7 keeps asking for verification.

### ISSUE THREAD

**Issue by tzunder** [nextcloud/server#24204]
### Expected behaviour
Once email verified on platform (**good cloud** and **tab digital** for me) then the client should not ask for email verification.

### Actual behaviour
client continues to nag for email verification

### Server configuration

**Operating system:**
Client on MacOS 10.15.7

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud Desktop Client
Version 3.0.3 (macOS). 

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
https://nextcloud.com/install/#install-clients

<img width="526" alt="Screenshot 2020-11-18 at 14 56 11" src="https://user-images.githubusercontent.com/43070521/99548018-1b10c980-29b0-11eb-917f-b86d06bd615e.png">

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by tzunder** [comment]
I don't know I gave up using Nextcloud because of the problem


Ni dieu ni maître !

**Comment by szaimen** [comment]
Since this looks more like a configuration problem of the provider that you've chosen I am closing this. Thanks for the report nonetheless!
