### ISSUE TITLE
Share by mail, strange text input leading to incorrect recipient mail display

### ISSUE THREAD

**Issue by kurn77** [nextcloud/server#24209]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Connect to NextCloud server
2. Create a folder and share it by mail to somebody
3. Click on detailed view of the share and type into upper text input visible on the popup
4. Click on right arrow to validate the text

### Expected behaviour
I don't know, as I don't understand what is the purpose of the upper input text in the popup.
At least, I don't expect any error on display

### Actual behaviour
Currently, nothing happen on click, but the recipient email is change to something like "Share the link ({tag})" info
If you refresh webpage again, the recipient email is displayed correctly again, and if you click again on detailed view of the share, nothing is visible in the upper text input in the popup.

![Picture01](https://user-images.githubusercontent.com/74493472/99589896-ebcc7d80-29ec-11eb-8129-624794696ac2.png)

![Picture02](https://user-images.githubusercontent.com/74493472/99589907-f0913180-29ec-11eb-891b-e04f1d3ecd94.png)

![Picture03](https://user-images.githubusercontent.com/74493472/99589917-f424b880-29ec-11eb-9c93-889d817e3c14.png)

### Server configuration

**Operating system:** Debian 10.12-2
**Web server:** Apache 2.4
**Database:** PostgreSQL 10.12
**PHP version:** PHP 7.3.19
**Nextcloud version:** NextCloud v 20.0.1
**Updated from an older Nextcloud/ownCloud or fresh install:** NextCloud v 17.0.9

No errors have been found when login as admin user into your Nextcloud and access to http://example.com/index.php/settings/integrity/failed

List of activated apps:
Accessibility 1.6.0 / Activity 2.13.2 / Calendar 2.1.2 / Comments 1.10.0 / Contacts 3.4.1 / Contacts Interaction 1.1.0 / Custom CSS 1.7.0 / Data Request 1.7.0 / Deleted files 1.10.1 / DICOM Viewer 1.2.2 / External sites 3.7.1 / File sharing 1.12.0 / Group folders 8.1.0 / Log Reader 2.5.0 / Notifications 2.8.0 / Password policy 1.10.1 / PDF viewer 2.0.1 / Photos 1.2.0 / Recommendations 0.8.0 / Right click 0.17.0 / Share by mail 1.10.0 / Support 1.3.0 / Text 3.1.0 / Theming 1.11.0 / Update notification 1.10.0 / Usage survey 1.8.0 / User status 1.0.0 / Versions 1.13.0 / Video player 1.9.0

**Are you using external storage, if yes which one: no
**Are you using encryption: no
**Are you using an external user-backend, if yes which one: no

### Client configuration
Version 86.0.4240.111 (Build officiel) (64 bits)

**Operating system:**
Windows 10 Version 10.0.19041 Numéro 19041

**Comment by skjnldsv** [comment]
The email should be set as a second line then! :+1:
