### ISSUE TITLE
Group restrictions for apps are not displayed correctly

### ISSUE THREAD

**Issue by milkomeda** [nextcloud/server#2421]
### Steps to reproduce
1. Set group restrictions for a specific app (tried calendar, contacts, tasks)
2. Log out
3. Log in again
4. Check group restricitions for specific app

### Expected behaviour
I expected to see the specific apps group restrictions in apps list.

### Actual behaviour
Although the group restricitions for a specific app are set and working. The user interface shows no group restricitions in apps list.

### Server configuration
**Operating system:** Ubuntu 16.04.1 LTS

**Web server:** nginx/1.11.6

**Database:** MySQL Ver 5.7.16-0ubuntu0.16.04.1 for Linux on x86_64 ((Ubuntu))

**PHP version:** PHP 7.0.8-0ubuntu0.16.04.3

**Nextcloud version:** 10.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** 
Updated from [...] ownCloud 8.2.7 -> ownCloud 8.2.9 -> Nextcloud 9.0.54 -> Nextcloud 10.0.1
Was working on ownCloud 8.2.7 didn't test it on versions in between.

**Where did you install Nextcloud from:**
Manual Installation (https://download.nextcloud.com/server/releases/nextcloud-10.0.1.tar.bz2).

**Signing status:**
No errors have been found.

**List of activated apps:**
Enabled:
- activity: 2.3.2
- admin_audit: 1.0.0
- calendar: true
- comments: 1.0.0
- contacts: true
- dav: 1.0.1
- federatedfilesharing: 1.0.1
- federation: 1.0.1
- files: 1.5.2
- files_pdfviewer: 0.8.1
- files_sharing: 1.0.0
- files_texteditor: 2.1
- files_trashbin: 1.0.0
- files_versions: 1.3.0
- files_videoplayer: 0.9.8
- firstrunwizard: 1.1
- notifications: 0.3.0
- password_policy: 1.0.0
- provisioning_api: 1.0.0
- serverinfo: 1.1.1
- survey_client: 0.1.5
- systemtags: 1.0.2
- tasks: 0.9.3
- templateeditor: 0.1
- theming: 1.0.1
- updatenotification: 1.0.1
- workflowengine: 1.0.1

Disabled:
- encryption
- external
- files_accesscontrol
- files_automatedtagging
- files_external
- files_retention
- gallery
- user_external
- user_ldap
- user_saml

**The content of config/config.php:**
```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***/data",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": true,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "loglevel": 3,
        "trashbin_retention_obligation": "auto",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis.sock",
            "port": 0
        }
    }
}
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Google Chrome Version 54.0.2840.99 m

**Operating system:** Windows 10 Pro 1607

### Logs
no log entry

#### Nextcloud log (data/nextcloud.log)
no log entry

#### Browser log
no console log entry
no conspicuousness in network log

**Comment by nickvergessen** [comment]
Works quite fine here. Which groups do you select, maybe it depends on the groups name.

**Comment by milkomeda** [comment]
Group "admin" for instance. Did you log out and immediately log in again to check app group restrictions?

**Comment by nickvergessen** [comment]
Yes, works quite fine here:
> ![apps_-_nextcloud_-_2016-12-02_09 47 55](https://cloud.githubusercontent.com/assets/213943/20827791/6c4f63f8-b874-11e6-9091-8d21a7dcd52b.png)

**Comment by MorrisJobke** [comment]
Works here fine (stable10, stable11 and master):

<img width="306" alt="bildschirmfoto 2017-01-24 um 15 23 00" src="https://cloud.githubusercontent.com/assets/245432/22267435/623508ec-e249-11e6-8534-a66d773bd120.png">
<img width="462" alt="bildschirmfoto 2017-01-24 um 15 25 28" src="https://cloud.githubusercontent.com/assets/245432/22267436/623525d4-e249-11e6-8394-07762e04ba1d.png">
