### ISSUE TITLE
Deleting a shared file on encrypted nextcloud and restoring the file displays an error

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/server#24216]
### Steps to reproduce
1. Use encrypted nextcloud (with separate encryption for each user; user keys + master key + recovery key)
2. User A shares a folder whit user B. Any of those users creates a file in this folder.
3. User B deletes the file.
4. User B opens the trashbin and clicks on "restore".
5. An error prompt says: "Error when restoring from trashbin" (original: "Fehler beim Wiederherstellen aus Papierkorb")
6. The file is restored, but a copy remains in the trashbin of user A. There remains no copy in the trashbin of user B. (If the owner  A restores the file, there is no error prompt, the file is also restored, but a copy remains in the trashbin of user B)

7. minor bug: If the folder is also shared with a user C at step 2, user C will not see the deleted file in the trashbin after step 3. Only user A and B can see or restore it.

### Expected behaviour
a) There should be no error prompt, because the file is successfully restored.
b) Any user should be able to see the file in the trashbin, if he has access to the shared folder.

### Actual behaviour
Error prompt.

### Server configuration

**Operating system:** Ubuntu server 20.04

**Web server:** Apache2

**Database:** mySQL / mariaDB

**PHP version:** 7.4.3

**Nextcloud version:** (see Nextcloud admin page) 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** from 18

**Where did you install Nextcloud from:** used linuxbabe tutorial for nc18 on ubuntu server 18.04

Error Log:
`{"reqId":"xxxxxxxxxxxxxxxxxxxxxxx","level":4,"time":"2020-11-19T13:35:14+00:00","remoteAddr":"123.345.678.123","user":"userB","app":"webdav","method":"MOVE","url":"/remote.php/dav/trashbin/userB/trash/Taupunkttabelle%20(Kopie).pdf.d1605792897","message":{"Exception":"Error","Message":"Call to a member function getOwner() on null","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/Encryption/File.php","line":106,"function":"getAccessList","class":"OC\\Share20\\Manager","type":"->"},{"file":"/var/www/nextcloud/lib/private/Encryption/Update.php","line":189,"function":"getAccessList","class":"OC\\Encryption\\File","type":"->"},{"file":"/var/www/nextcloud/lib/private/Encryption/Update.php","line":122,"function":"update","class":"OC\\Encryption\\Update","type":"->","args":["*** sensitive parameters replaced ***"]},{"file":"/var/www/nextcloud/lib/private/Encryption/HookManager.php","line":47,"function":"postRestore","class":"OC\\Encryption\\Update","type":"->"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Hook.php","line":110,"function":"postRestore","class":"OC\\Encryption\\HookManager","type":"::"},{"file":"/var/www/nextcloud/lib/public/Util.php","line":354,"function":"emit","class":"OC_Hook","type":"::"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trashbin.php","line":475,"function":"emitHook","class":"OCP\\Util","type":"::"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trash/LegacyTrashBackend.php","line":85,"function":"restore","class":"OCA\\Files_Trashbin\\Trashbin","type":"::"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Trash/TrashManager.php","line":65,"function":"restoreItem","class":"OCA\\Files_Trashbin\\Trash\\LegacyTrashBackend","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Sabre/AbstractTrash.php","line":94,"function":"restoreItem","class":"OCA\\Files_Trashbin\\Trash\\TrashManager","type":"->"},{"file":"/var/www/nextcloud/apps/files_trashbin/lib/Sabre/RestoreFolder.php","line":76,"function":"restore","class":"OCA\\Files_Trashbin\\Sabre\\AbstractTrash","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Tree.php","line":164,"function":"moveInto","class":"OCA\\Files_Trashbin\\Sabre\\RestoreFolder","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php","line":641,"function":"move","class":"Sabre\\DAV\\Tree","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"httpMove","class":"Sabre\\DAV\\CorePlugin","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":474,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":251,"function":"invokeMethod","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/lib/Server.php","line":320,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/apps/dav/appinfo/v2/remote.php","line":35,"function":"exec","class":"OCA\\DAV\\Server","type":"->"},{"file":"/var/www/nextcloud/remote.php","line":167,"args":["/var/www/nextcloud/apps/dav/appinfo/v2/remote.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Share20/Manager.php","Line":1621,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36","version":"19.0.4.2","id":"xxxxxxxxxxxxxx"}`

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
