### ISSUE TITLE
[20.0.2] Unified contact search link mismatch if address book contains a whitespace

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#24218]
## Expected behavior
If you use the unified search function to lookup a contact and click on the provided result link, the contacts app should instantly open and display the related contact record.

## Current behavior
If you use the unified search function to lookup a contact and click on the provided result link, the contacts app is opened but a "**Contact not found**" error message is displayed if the address book contains a whitespace.

I compared the generated search link and the link which is shown when I manually select a contact record and found out that both differ which is most likely the reason why the generated error is being created. The main/important difference between both links is, that the generated search link contains a single whitespace (`%20`) in the address book name, whereas the address book name of the direct link contains an invalid additional ampersand character in front of the whitespace (**`%25`**`%20`)?!

Generated search link:
```
https://<fqdn-of-server>/apps/contacts/direct/6280cacf-04a5-4485-8ab8-3b43fd281f44~Gemeinsame%20Kontakte
```

Direct link to contact:
```
https://<fqdn-of-server>/apps/contacts/Alle Kontakte/6280cacf-04a5-4485-8ab8-3b43fd281f44~Gemeinsame%2520Kontakte
                                                                                                    ^^^
```

## Steps to reproduce
1. Create an address book named e.g. "`Gemeinsame Kontakte`" and create a contact record in it.
2. Enter the contact name in the search field and select the displayed result.
**RESULT:** The contacts app is opened and a "Contact not found" message is shown.

#### Server Configuration
OS: Linux 4.9.218
Web server: Apache2 2.4.46
Database: MariaDB 10.2.24
PHP version: 7.4.11
Nextcloud version: 20.0.2

#### Client Configuration
Browser: Mozilla Firefox 83.0
Operating system: Windows 10

**Comment by Lokirator** [comment]
I have the same problem.

**Server Configuration**
OS: Ubuntu 18.04.5 LTS
Web Server: Apache/2.4.29 (Ubuntu)
Database: MySQL 5.7.32
PHP: 7.4.12
Nextcloud: 20.0.2

**Client Configuration**
OS: Windows 10 20H2 (Build 19042.630)
Broswer: Mozilla Firefox 83.0 (64 Bit)

**Comment by j-ed** [comment]
@skjnldsv Might it be possible that this is more a Contacts app problem than a server one, because it seems that the mentioned links ar both build in the routes.php file of the Contacts app. If your answer is yes, this issue report should be moved to the contacts repository.

**Comment by skjnldsv** [comment]
> the direct link contains an invalid additional ampersand character in front of the whitespace (**`%25`**`%20`)?!

This is not an ampersand but a `%`. I guess something is wrong indeed.
Sorry, I haven't seen this issue sooner :)
I can reproduce the issue indeed. Nowadays new addressbooks doesn't have spaces on them, I guess this is coming from old ones.

This is coming from dav returning url encoded values directly.
I'm not sure this is the correct approach.
![Capture d’écran_2020-11-30_11-20-11](https://user-images.githubusercontent.com/14975046/100597683-08768880-32fe-11eb-9847-3bf4b4403626.png)

**Comment by ChristophWurst** [comment]
> @ChristophWurst @tcitworld @juliushaertl do you think the properties should be urlencoded from the dav xml response?
> IMO they should stay unaltered and the front should manage the url encoding or not, right?

I don't know DAV really, but I guess you are right. Doesn't seem logical to have *url encoding* in anything that isn't a URL …

**Comment by skjnldsv** [comment]
I tried digging where this could come from, but it's super hard narrowing down where dav propfind request go through ^^'

**Comment by tcitworld** [comment]
Isn't this https://github.com/nextcloud/server/issues/17610#issuecomment-586745316 ?

**Comment by skjnldsv** [comment]
Oh totally!
