### ISSUE TITLE
When recovering a users encrypted data with recovery key, it does not ask twice for the new password

### ISSUE THREAD

**Issue by Kuphi** [nextcloud/server#24213]
Steps to reproduce
1. sudo -u www-data php /var/www/nextcloud/occ encryption:recover-user username
Please enter the recovery key password: xxxxxxxxx
Please enter the new login password for the user:
Start to recover users files... This can take some time...Done.

### Expected behaviour
Please enter the new login password for the user **again**:

### Actual behaviour
It does not ask twice. One typo and one would have to do the procedure again.

### Server configuration

**Operating system:** Ubuntu server 18.04

**Web server:** Apache2

**Database:** MySQL / MariaDB

**PHP version:** 7.4.3

**Nextcloud version:** 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** from 18

**Comment by Kuphi** [comment]
Could this get a simple fix?

**Comment by szaimen** [comment]
cc @nextcloud/encryption is this feasible?

**Comment by Kuphi** [comment]
This issue is still not solved. Maybe can get a fix? Thanks!
