### ISSUE TITLE
NC 20.0.2 forcefully enables legacy encryption

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#24223]
I have a fresh installation of NC 20.0.1, which was upgraded to 20.0.2 today. Right after upgrading, a notification about legacy encryption was displayed in admin page (I have encryption enabled). Sure enough, all files are encrypted using new format (because it's a new installation of v20.x, and I even manually ran OCC command to ensure no legacy format is used).

What is the reason that NC 20.0.2 **forcefully** enabled legacy encryption support? To be specific, it added a new line to config file, and this line forcefully enables support for legacy encryption.

**Comment by rullzer** [comment]
Should be fixed with https://github.com/nextcloud/server/pull/24241
