### ISSUE TITLE
owner cannot edit permissions for reshared file

### ISSUE THREAD

**Issue by alx-tuilmenau** [nextcloud/server#24221]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Case 1)
1. User A creates a Folder (in his home, he is the owner) and shares it to User B with resharing enabled, but read-only
2. User B shares this folder read-only to User C

Case 2)
1. User A creates a Folder  (in his home, he is the owner) and shares it to User B with resharing and write/create/update enabled
2. User B shares this folder read-only to User C
3. User B unshares the folder (removes it for himself)

### Expected behaviour
User A should be able to add write permissions to User C

### Actual behaviour
Error Message, 404 on the put request to /ocs/v2.php/apps/files_sharing/api/v1/shares/*id*

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache / php-fpm

**Database:** mysql

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbdriveroptions": {
            "1002": "SET wait_timeout = 28800"
        },
        "installed": true,
        "default_language": "de",
        "updatechecker": true,
        "has_internet_connection": true,
        "memcached_servers": [
            [
                "localhost",
                11211
            ]
        ],
        "appstoreenabled": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "loglevel": 0,
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "sendmail",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "skeletondirectory": "\/data\/nextcloud_skel",
        "activity_expire_days": 14,
        "integrity.check.disabled": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "knowledgebaseenabled": false,
        "defaultapp": "apporder",
        "sharing.minSearchStringLength": 4,
        "sharing.maxAutocompleteResults": 5,
        "maintenance": false,
        "overwritehost": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "proxy": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "theme": "tuitest",
        "lookup_server": "",
        "app_install_overwrite": [
            "files_upload_mtime",
            "quotaadmin",
            "drop_account",
            "mindmap_app"
        ],
        "auth.webauthn.enabled": false
    }
}

```
</details>

**Are you using external storage, if yes which one:** none

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox 83

**Operating system:** Windows 10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No Messages
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No Messages
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No Messages in Konsole (except deprecations).
```
</details>

**Comment by szaimen** [comment]
I am not sure if it was designed to work this way or if this is a bug.

cc @nextcloud/sharing for more input on this.

**Comment by alx-tuilmenau** [comment]
still reproduceable in 21.0.3

I don't know how it is designed, but there should be a consistent way without error messages. In my opinion, the owner of a file / folder should always have the permission to change the sharing permissions of any user the file / folder is shared to.

But the behavior for case 2 looks like an additional bug, on removal of user B the uid_initiator should be set to uid_owner for all users of this share, if it is user B. Otherwise noone can edit permissions for all users user B shared the file to.
