### ISSUE TITLE
file_put_contents - failed to open stream: File name too long at /snap/nextcloud/24051/htdocs/lib/private/Files/Storage/Local.php#560

### ISSUE THREAD

**Issue by huzibizi** [nextcloud/server#24227]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create file with name that is close to filesystem limit of 255 bytes
2. Sync using latest windows desktop app

### Expected behaviour
File is uploaded with no errors

### Actual behaviour
File is not uploaded with a logged error.  Nextcloud adds .ocTransferId**********.part suffix to the end of the file name and thus exceeds filesystem limit for the file name length.

### Details
My local filesystem is NTFS, filesystem for nextcloud data directory is XFS, both limited by 255 bytes for the filename.

Nextcloud should really automatically reduce filename size for any files that end up being too long to upload, and then append something on the end maybe too. 

### Server configuration

**Operating system:**  Ubuntu Server 20 LTS (running on a win10 hyperV virtual machine)

**Web server:** Apache (can't find the version - it was included with the latest nextcloud snap)

**Database:** MySQL 6.7.32

**PHP version:** 7.4.11

**Nextcloud version:** 20.0.1snap1 (latest version of the snap as of posting, 20.0.2 snap not released yet)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** Ubuntu Server, Nextcloud Official Snap

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

</details>

### Client configuration
**Browser: N/A**

**Operating system: Windows 10 Pro x64**

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud Log</summary>

```
Error: file_put_contents(/var/snap/nextcloud/common/nextcloud/data/********/files/***********************/Misc KEEP/health/مردانہ کمزوری کا علاج - مردانہ کمزوری کا آسان نسخہ - मर्दाना कमजोरी - मर्दाना कमजोरी का आसान नुस्खा - YouTube.url.ocTransferId948594041.part): failed to open stream: File name too long at /snap/nextcloud/24051/htdocs/lib/private/Files/Storage/Local.php#560

    <<closure>>

    OC\Log\ErrorHandler::onError(2, "file_put_co ... g", "/snap/nextc ... p", 560, { path: "fil ... l})

    /snap/nextcloud/24051/htdocs/lib/private/Files/Storage/Local.php - line 560:

    file_put_contents("/var/snap/n ... t", null)

    /snap/nextcloud/24051/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 631:

    OC\Files\Storage\Local->writeStream("files/160GB ... t", null, null)

    /snap/nextcloud/24051/htdocs/lib/private/Files/Storage/Wrapper/Wrapper.php - line 631:

    OC\Files\Storage\Wrapper\Wrapper->writeStream("files/160GB ... t", null, null)

    /snap/nextcloud/24051/htdocs/apps/dav/lib/Connector/Sabre/File.php - line 207:

    OC\Files\Storage\Wrapper\Wrapper->writeStream("files/160GB ... t", null)

    /snap/nextcloud/24051/htdocs/apps/dav/lib/Connector/Sabre/Directory.php - line 155:

    OCA\DAV\Connector\Sabre\File->put(null)

    /snap/nextcloud/24051/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 1104:

    OCA\DAV\Connector\Sabre\Directory->createFile("مردانہ کمزو ... l", null)

    /snap/nextcloud/24051/htdocs/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 527:

    Sabre\DAV\Server->createFile("files/drbis ... l", null, null)

    /snap/nextcloud/24051/htdocs/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

    Sabre\DAV\CorePlugin->httpPut(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

    /snap/nextcloud/24051/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

    Sabre\DAV\Server->emit("method:PUT", [ Sabre\HTTP ... }])

    /snap/nextcloud/24051/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

    /snap/nextcloud/24051/htdocs/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

    Sabre\DAV\Server->start()

    /snap/nextcloud/24051/htdocs/apps/dav/lib/Server.php - line 325:

    Sabre\DAV\Server->exec()

    /snap/nextcloud/24051/htdocs/apps/dav/appinfo/v2/remote.php - line 35:

    OCA\DAV\Server->exec()

    /snap/nextcloud/24051/htdocs/remote.php - line 167:

    require_once("/snap/nextc ... p")
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
N/A
```
</details>

**Comment by szaimen** [comment]
Sry but we cannot fix filesystem limitations. It is up to you to choose a filesystem that fits your needs.
