### ISSUE TITLE
Upgrade fails with code integrity chck

### ISSUE THREAD

**Issue by john-2000** [nextcloud/server#24229]
### Steps to reproduce
1. run upgrade from 20.0.1 to 20.0.2 via web updater or terminal
2. update fails

### Expected behaviour
upgrade should complete

### Actual behaviour
Upgrade fails with:

Starting code integrity check...
An unhandled exception has been thrown:
TypeError: Return value of OC\Files\Type\Detection::loadCustomDefinitions() must be of the type array, null returned in /var/www/nextcloud/lib/private/Files/Type/Detection.php:145
Stack trace:
#0 /var/www/nextcloud/lib/private/Files/Type/Detection.php(157): OC\Files\Type\Detection->loadCustomDefinitions()
#1 /var/www/nextcloud/lib/private/Files/Type/Detection.php(164): OC\Files\Type\Detection->loadAliases()
#2 /var/www/nextcloud/lib/private/IntegrityCheck/Checker.php(210): OC\Files\Type\Detection->getAllAliases()
#3 /var/www/nextcloud/lib/private/IntegrityCheck/Checker.php(378): OC\IntegrityCheck\Checker->generateHashes()
#4 /var/www/nextcloud/lib/private/IntegrityCheck/Checker.php(558): OC\IntegrityCheck\Checker->verify()
#5 /var/www/nextcloud/lib/private/IntegrityCheck/Checker.php(579): OC\IntegrityCheck\Checker->verifyCoreSignature()
#6 /var/www/nextcloud/lib/private/Updater.php(283): OC\IntegrityCheck\Checker->runInstanceVerification()
#7 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#8 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#9 /var/www/nextcloud/apps/mail/vendor/symfony/console/Command/Command.php(258): OC\Core\Command\Upgrade->execute()
#10 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(920): Symfony\Component\Console\Command\Command->run()
#11 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#12 /var/www/nextcloud/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#13 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#14 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#15 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')

### Server configuration

Ubuntu 20.04

Apache2

MariaDB

PHP 7.4.3

NC 20.0.2

Update from NC 20.0.1

Web updated

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
