### ISSUE TITLE
Update from 20.0.1 to 20.0.2 fails at Deleting old files

### ISSUE THREAD

**Issue by facorazza** [nextcloud/server#24244]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Web browser update

### Expected behaviour
Complete as usual

### Actual behaviour
Stuck at Delete old files

### Server configuration

**Operating system:** Ubuntu 20.04.1 LTS

**Web server:** 

**Database:** mysql  Ver 15.1 Distrib 10.3.25-MariaDB

**PHP version:** PHP 7.3.19-1

**Nextcloud version:** (see Nextcloud admin page) 20.0.1.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 20.0.1.1

**Where did you install Nextcloud from:** Docker Hub

**Signing status:**
<details>
<summary>Signing status</summary>

```
Update in process.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
PHP Warning:  require_once(/data/nextcloud/console.php): failed to open stream: No such file or directory in /data/nextcloud/occ on line 11
PHP Fatal error:  require_once(): Failed opening required '/data/nextcloud/console.php' (include_path='.:/usr/share/php') in /data/nextcloud/occ on line 11
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    ***
    ***
  ),
  'trusted_proxies' => 
  array (
    0 => 'traefik',
  ),
  'datadirectory' => '/ncdata',
  'dbtype' => 'mysql',
  'version' => '20.0.1.1',
  'overwrite.cli.url' => '***',
  'dbname' => '***',
  'dbhost' => '***',
  'dbport' => '***',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => '***',
  'dbpassword' => '***',
  'installed' => true,
  'instanceid' => '***',
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => '/var/run/redis/redis.sock',
    'port' => 0,
    'timeout' => 0.0,
    'password' => '***',
  ),
  'tempdirectory' => '/var/www/nextcloud/data/tmp',
  'mail_smtpmode' => 'sendmail',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_from_address' => '***',
  'mail_domain' => '***',
  'preview_max_x' => '2048',
  'preview_max_y' => '2048',
  'jpeg_quality' => '60',
  'overwriteprotocol' => 'https',
  'maintenance' => true,
  'loglevel' => 2,
  'theme' => '',
  'htaccess.RewriteBase' => '/',
  'data-fingerprint' => '***',
  'trashbin_retention_obligation' => 'auto, 30',
  'mail_sendmailmode' => 'smtp',
  'twofactor_enforced' => 'true',
  'twofactor_enforced_groups' => 
  array (
  ),
  'twofactor_enforced_excluded_groups' => 
  array (
  ),
  'updater.release.channel' => 'stable',
  'allow_local_remote_servers' => 'true',
  'app_install_overwrite' => 
  array (
    0 => 'files_external_dropbox',
    1 => 'telephoneprovider',
  ),
  'updater.secret' => '***',
);
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox

**Operating system:** MacOS Big Sur

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
empty
```
</details>

**Comment by facorazza** [comment]
This also doesn't work:

<img width="660" alt="Screenshot 2020-11-20 at 11 25 48" src="https://user-images.githubusercontent.com/20555025/99789615-259fa000-2b23-11eb-857d-f1c06f66b6da.png">

I'm able to get the plain text secret but it seems invalid. The secret changes every time I run that command for some reason.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
