### ISSUE TITLE
Option to switch between default and "real" storage quota calculation

### ISSUE THREAD

**Issue by kevATin** [nextcloud/server#24250]
**Is your feature request related to a problem? Please describe.**
I understand why the default storage calculation works like it does and why some people want it that way, however i fundamentally disagree with it and would greatly appreciate having the option to switch to a more brutalistic approach. 
Basically I want anything that relates to a user to actually count against their quota.

**Describe the solution you'd like**
Nextcloud server admins should have the ability to switch between the current, default way of calculating storage quotas, and this new way.
Things that are taken into account in this new approach:
* Metadata (thumbnails, temporary files, cache, and encryption keys)
* App data
* Use encrypted file size instead of unencrypted one if the file is encrypted
* Count the trash bin against your quota (and while we are at it, maybe the individual users could be given the ability to set trash deletion times, each user should be responsible for their own trash)
* Each version of a file when version control is enabled

**Additional context**
https://docs.nextcloud.com/server/stable/user_manual/en/files/quota.html 
> Metadata (thumbnails, temporary files, cache, and encryption keys) takes up about 10% of disk space, but is not counted against user quotas. Some apps store information in the database, such as the Calendar and Contacts apps. This data is excluded from your quota.

> Encrypted files are a little larger than unencrypted files; the unencrypted size is calculated against your quota.

> Deleted files that are still in the trash bin do not count against quotas. The trash bin is set at 50% of quota. Deleted file aging is set at 30 days. When deleted files exceed 50% of quota then the oldest files are removed until the total is below 50%.

> When version control is enabled, the older file versions are not counted against quotas.

**Comment by EngelPika32** [comment]
Question: How can you calculate the disc space some entries in the database require? 
(And, it would probably slow down the server a lot.)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
