### ISSUE TITLE
Add optional description for folders

### ISSUE THREAD

**Issue by philip-n** [nextcloud/server#2426]
Sometimes it would be nice to be able to add a description/annotation to folders, which would then be displayed in the nextcloud clients. Basic use cases that I encountered are folders which are shared between multiple persons (description of content or usage rules) and special folders (use description as a reminder e.g. not to rename folders that are used by apps).

### Frontend realization
In the different nextcloud views (e.g. browser-based, mobile clients, ...) the description is shown as smaller text below the folder name. Editing is performed in the same way as tags are added in the browser-based view (and maybe in mobile clients in future releases?).

### Backend realization
Technically, the description might be stored as a yaml-file "folder.cnf" in the according folder, similar to the way descriptions are handled in the gallery app [1]. This would allow to introduce additional features later that need a per-folder way of storing information (e.g. selectable folder icons, marking folder as "always on top of folder list", ...).

[1] https://docs.nextcloud.com/server/10/user_manual/files/gallery_app.html

**Comment by manicmarvin** [comment]
I would suggest that this featur enot be restricted to folders, but to all file-types. Enhancing the amount of metadata we can attach to each file/folder would vastly improve collaborative and archival use-cases. 

There was an owncloud plugin that was never maintained that attempted to do this. It's [here](https://apps.owncloud.com/content/show.php?content=151520).

**Comment by MorrisJobke** [comment]
cc @karlitschek @oparoz @rullzer @icewind1991 @schiessle @nextcloud/sharing Opinions on this?

I would say, that this is a bit too much for all folders in the beginning, but maybe we start with shared links and then enhance.

**Comment by karlitschek** [comment]
not a bad idea. But might be trick to show on some platform. (Desktop/WebDAV/...)

**Comment by schiessle** [comment]
Just  random idea. Maybe we could use the comments feature for it and always show the last comment on the file listing? This would also make comments more visible and easier to discover... To always show a specific comment we could add the possibility to pin a comment. If there is a pinned comment we will show this, if not we show the latest comment.

**Comment by MorrisJobke** [comment]
cc @nextcloud/designers

**Comment by jancborchardt** [comment]
Regardless of how we implement it, we need to make sure it works cross-platform. Proper integration into the desktop will already be difficult. On mobile, the comments should be easy to access anyway, but are still todo also. So we’re getting a bit ahead of ourselves by introducing another thing.

But in general yes, using comments for any further explanation seems to make the most sense.

**Comment by MorrisJobke** [comment]
ref #2019

**Comment by jancborchardt** [comment]
@jonathanpantall this is a different issue though as it relates to sharing. Please open a separate issue. :)

**Comment by mmuman** [comment]
Ideally this (and many other things) should be properly exposed on client side using xattrs when supported. For example, on Linux, FreeDesktop has a [proposed spec](https://www.freedesktop.org/wiki/CommonExtendedAttributes/) for those, including `user.dublincore.description`. Just sayin…

**Comment by olantrust** [comment]
See #4216 #4217
It's still quite disappointing that Nextcloud lose/destroy xattr data (extended attribute data, such as tags and descriptions) when syncing files from, for example, Linux distributions where Users carefully tag files (such as under KDE).

**Comment by wiswedel** [comment]
You might want to take a look at https://apps.nextcloud.com/apps/files_readmemd

**Comment by skjnldsv** [comment]
Implemented
