### ISSUE TITLE
Dashboard: add an .md file that is shown for all users (Landing Page)

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#24278]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
New users on our instance would like some guidance: "how do I use this?" and company-specific information about what is where. The dashboard cannot provide this at the moment.

**Describe the solution you'd like**
Create dashboard widget "Text" where the admin can edit an .md file that is shown to every user. 
Links and images should be possible to include. Not sure where in the folder tree the file should be saved, as Nextcloud use cases vary greatly. Maybe in admins individual files?

**Describe alternatives you've considered**
- Use announcement app and show after login via "app order" app -- but no links/images can be shown in announcement app, and it is only for announcements, and other dashboard functionality is lost
- use rich workspaces ("Readme.md") -- but this only works inside of a folder, not at the top level of the folder structure, and other dashboard functionality is lost
- use an external site as landing page and show after login via "app order" app -- other dashboard functionality is lost
- the old dashboard app had a text field that could be added for all users iirc?

**Comment by ilippert** [comment]
I would suggest, this issue is related to https://github.com/nextcloud/server/issues/22609

**Comment by wiswedel** [comment]
You might wanna have a look at https://github.com/eneiluj/welcome (Readme wip [here](https://github.com/eneiluj/welcome/blob/e2fbbc60c0431fe1e19a950bb65416a0a1b0d114/README.md))

**Comment by szaimen** [comment]
Yes, please use this app for this https://github.com/eneiluj/welcome
Thanks!
