### ISSUE TITLE
Preview image for videos

### ISSUE THREAD

**Issue by lackyluuk** [nextcloud/server#24282]
Hi there
I am using Nextcloud privately and it's really awesome. Great project 👍 👍 
I noticed that for uploaded videos, there is no preview image (like it is for Google Photos (Which I don't want to use anymore ;)))
Are there plans to have this implemented one day? Sometimes it's hard to find the correct video if you need it :)

Thanks and keep up the good work.
lackyluuk

**Comment by j-ed** [comment]
Please use the Nextcloud help forum to ask your question or better use the available search function to find an answer on your question. The purpose of this repository is primary to address issues or feature requests.

https://help.nextcloud.com/search?q=video%20preview

**Comment by lackyluuk** [comment]
alright, sorry for the trouble
thanks for the hint
