### ISSUE TITLE
Error: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found when upgrade from Nextcloud 19.0.4 to Nextcloud 19.0.5

### ISSUE THREAD

**Issue by Floppik** [nextcloud/server#24286]
### Steps to reproduce
Try update from Nextcloud 19.0.4 to Nextcloud 19.0.5 from web or via cli

### Expected behaviour
Update without errors

### Actual behaviour
Get error (see Nextcloud log)

## Server configuration detail

**Operating system:** Linux 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64

**Webserver:** nginx/1.19.4 (fpm-fcgi)

**Database:** mysql 10.3.25

**PHP version:** 

7.4.12
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, cgi-fcgi, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, apc, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, Phar, libsmbclient, Zend OPcache

**Nextcloud version:** 19.0.4 - 19.0.4.2

**Updated from an older Nextcloud/ownCloud or fresh install:** update from 19.0.4

**Where did you install Nextcloud from:** web

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.5.0
 - activity: 2.12.1
 - cloud_federation_api: 1.2.0
 - comments: 1.9.0
 - contactsinteraction: 1.0.0
 - dav: 1.15.0
 - drawio: 0.9.7
 - duplicatefinder: 0.0.4
 - extract: 1.2.5
 - federatedfilesharing: 1.9.0
 - federation: 1.9.0
 - files: 1.14.0
 - files_accesscontrol: 1.9.2
 - files_downloadactivity: 1.8.0
 - files_external: 1.10.0
 - files_fulltextsearch: 1.4.3
 - files_fulltextsearch_tesseract: 1.4.2
 - files_pdfviewer: 1.8.0
 - files_rightclick: 0.16.0
 - files_sharing: 1.11.0
 - files_trashbin: 1.9.0
 - files_versions: 1.12.0
 - files_videoplayer: 1.8.0
 - firstrunwizard: 2.8.0
 - fulltextsearch: 1.4.2
 - fulltextsearch_elasticsearch: 1.5.2
 - groupfolders: 7.1.1
 - issuetemplate: 0.7.0
 - logreader: 2.4.0
 - lookup_server_connector: 1.7.0
 - metadata: 0.12.0
 - nextcloud_announcements: 1.8.0
 - notifications: 2.7.0
 - oauth2: 1.7.0
 - ocdownloader: 1.7.8
 - onlyoffice: 6.1.0
 - password_policy: 1.9.1
 - passwords: 2020.11.1
 - photos: 1.1.0
 - previewgenerator: 2.3.0
 - privacy: 1.3.0
 - provisioning_api: 1.9.0
 - recommendations: 0.7.0
 - serverinfo: 1.9.0
 - settings: 1.1.0
 - sharebymail: 1.9.0
 - sharerenamer: 2.7.3
 - sharingpath: 0.2.5
 - systemtags: 1.9.0
 - text: 3.0.1
 - theming: 1.10.0
 - twofactor_backupcodes: 1.8.0
 - updatenotification: 1.9.0
 - viewer: 1.3.0
 - workflowengine: 2.1.0
Disabled:
 - admin_audit
 - admin_notifications
 - audioplayer
 - bruteforcesettings
 - calendar
 - contacts
 - dashboard
 - encryption
 - files_automatedtagging
 - files_frommail
 - files_retention
 - flowupload
 - ocr
 - registration
 - richdocuments
 - spreed
 - support
 - survey_client
 - twofactor_gateway
 - user_ldap
 - user_status
 - weather_status

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "rock64.net",
        "floppik.no-ip.biz:8081",
        "floppik.no-ip.biz",
        "nya.ddns.net",
        "i5.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "REMOVED SENSITIVE VALUE*",
    "dbtype": "mysql",
    "version": "19.0.4.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "activity_expire_days": 180,
    "auth.bruteforce.protection.enabled": true,
    "blacklisted_files": [
        ".htaccess",
        "Thumbs.db",
        "thumbs.db"
    ],
    "cron_log": true,
    "enable_previews": true,
    "enabledPreviewProviders": [
        "OC\\Preview\\PNG",
        "OC\\Preview\\JPEG",
        "OC\\Preview\\GIF",
        "OC\\Preview\\BMP",
        "OC\\Preview\\XBitmap",
        "OC\\Preview\\Movie",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown"
    ],
    "filesystem_check_changes": 0,
    "filelocking.enabled": "true",
    "htaccess.RewriteBase": "\/",
    "integrity.check.disabled": false,
    "knowledgebaseenabled": false,
    "logfile": "\/mnt\/Toshiba\/nc_data\/nextcloud.log",
    "loglevel": 0,
    "logtimezone": "Europe\/Volgograd",
    "log_rotate_size": 104857600,
    "mail_smtpmode": "sendmail",
    "mail_smtpauthtype": "LOGIN",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "465",
    "mail_smtpsecure": "ssl",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "preview_max_x": 1920,
    "preview_max_y": 1080,
    "preview_max_scale_factor": 1,
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0
    },
    "theme": "",
    "quota_include_external_storage": false,
    "share_folder": "\/Shares",
    "skeletondirectory": "",
    "trashbin_retention_obligation": "180, auto",
    "versions_retention_obligation": "45, auto",
    "updater.release.channel": "stable",
    "allowNightlyUpdates": [],
    "mail_sendmailmode": "smtp",
    "app_install_overwrite": [
        "sharerenamer"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Disabled incompatible app: sharerenamer
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore 
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore 
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore 
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore 
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore 
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore 
Checking for update of app drawio in appstore
Checked for update of app "drawio" in appstore 
Checking for update of app duplicatefinder in appstore
Checked for update of app "duplicatefinder" in appstore 
Checking for update of app extract in appstore
Checked for update of app "extract" in appstore 
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore 
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore 
Checking for update of app files in appstore
Checked for update of app "files" in appstore 
Checking for update of app files_accesscontrol in appstore
Checked for update of app "files_accesscontrol" in appstore 
Checking for update of app files_downloadactivity in appstore
Checked for update of app "files_downloadactivity" in appstore 
Checking for update of app files_external in appstore
Checked for update of app "files_external" in appstore 
Checking for update of app files_fulltextsearch in appstore
Checked for update of app "files_fulltextsearch" in appstore 
Checking for update of app files_fulltextsearch_tesseract in appstore
Checked for update of app "files_fulltextsearch_tesseract" in appstore 
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore 
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore 
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore 
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore 
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore 
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore 
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore 
Checking for update of app fulltextsearch in appstore
Checked for update of app "fulltextsearch" in appstore 
Checking for update of app fulltextsearch_elasticsearch in appstore
Checked for update of app "fulltextsearch_elasticsearch" in appstore 
Checking for update of app groupfolders in appstore
Checked for update of app "groupfolders" in appstore 
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore 
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore 
Checking for update of app metadata in appstore
Checked for update of app "metadata" in appstore 
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore 
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore 
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore 
Checking for update of app ocdownloader in appstore
Checked for update of app "ocdownloader" in appstore 
Checking for update of app onlyoffice in appstore
Checked for update of app "onlyoffice" in appstore 
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore 
Checking for update of app passwords in appstore
Checked for update of app "passwords" in appstore 
Checking for update of app photos in appstore
Checked for update of app "photos" in appstore 
Checking for update of app previewgenerator in appstore
Checked for update of app "previewgenerator" in appstore 
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore 
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore 
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in appstore 
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore 
Checking for update of app settings in appstore
Checked for update of app "settings" in appstore 
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore 
Checking for update of app sharingpath in appstore
Checked for update of app "sharingpath" in appstore 
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore 
Checking for update of app text in appstore
Checked for update of app "text" in appstore 
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore 
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore 
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore 
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore 
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore 
Checking for update of app sharerenamer in appstore
Checked for update of app "sharerenamer" in appstore 
An unhandled exception has been thrown:
Error: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found in /var/www/nextcloud/apps/user_status/lib/AppInfo/Application.php:48
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(444): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/nextcloud/lib/private/ServerContainer.php(105): class_exists()
#5 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\ServerContainer->getAppContainer()
#6 /var/www/nextcloud/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query()
#7 /var/www/nextcloud/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance()
#8 /var/www/nextcloud/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep()
#9 /var/www/nextcloud/lib/private/Installer.php(587): OC\DB\MigrationService->migrate()
#10 /var/www/nextcloud/lib/private/Installer.php(541): OC\Installer::installShippedApp()
#11 /var/www/nextcloud/lib/private/Updater.php(266): OC\Installer::installShippedApps()
#12 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#13 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#18 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#19 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#21 {main}?
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by faulix** [comment]
I had  the same issue updating from 18.0.9 to 18.0.11. Somehow the Bootstrap files were missing in the folder (lib/private and lib/public) as well as the oc_user_status table in the database. After copying all that files manuelly it worked.

**Comment by Floppik** [comment]
> I had the same issue updating from 18.0.9 to 18.0.11. Somehow the Bootstrap files were missing in the folder (lib/private and lib/public) as well as the oc_user_status table in the database. After copying all that files manuelly it worked.
Can you provide more details, which files and from where i should copy?

**Comment by faulix** [comment]
Sure. Please copy the following folders:

- https://github.com/nextcloud/server/tree/master/lib/private/AppFramework/Bootstrap meaning lib/private/AppFramework/Bootstrap
- https://github.com/nextcloud/server/tree/master/lib/public/AppFramework/Bootstrap meaning lib/public/AppFramework/Bootstrap/

You can either create the folders manually and download the files seperately with the raw function of Github or you copy the files from the current release.

Additionally I had the issue of a missing oc_user_status table in the database. For fixing this, please create the table manually in the database:
```
CREATE TABLE oc_user_status (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id VARCHAR(255) NOT
NULL, status VARCHAR(255) NOT NULL, status_timestamp INT UNSIGNED NOT NULL, is_user_defined TINYINT(1) NOT NULL, message_id VARCHAR(255) DEFAULT NULL, custom_icon VARCHAR(255) 
DEFAULT NULL, custom_message LONGTEXT DEFAULT NULL, clear_at INT UNSIGNED DEFAULT NULL, UNIQUE INDEX user_status_uid_ix (user_id), INDEX user_status_clr_ix (clear_at), 
PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB ROW_FORMAT = compressed
```
Later my integretiy check showed that the file `lib/Migration/Version0001Date20200602134824.php` is missing, which is I think the root course for this issue.

**Comment by Floppik** [comment]
> Sure. Please copy the following folders:
> 
> * https://github.com/nextcloud/server/tree/master/lib/private/AppFramework/Bootstrap meaning lib/private/AppFramework/Bootstrap
> * https://github.com/nextcloud/server/tree/master/lib/public/AppFramework/Bootstrap meaning lib/public/AppFramework/Bootstrap/
> 
> You can either create the folders manually and download the files seperately with the raw function of Github or you copy the files from the current release.
> 
> Additionally I had the issue of a missing oc_user_status table in the database. For fixing this, please create the table manually in the database:
> 
> ```
> CREATE TABLE oc_user_status (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, user_id VARCHAR(255) NOT
> NULL, status VARCHAR(255) NOT NULL, status_timestamp INT UNSIGNED NOT NULL, is_user_defined TINYINT(1) NOT NULL, message_id VARCHAR(255) DEFAULT NULL, custom_icon VARCHAR(255) 
> DEFAULT NULL, custom_message LONGTEXT DEFAULT NULL, clear_at INT UNSIGNED DEFAULT NULL, UNIQUE INDEX user_status_uid_ix (user_id), INDEX user_status_clr_ix (clear_at), 
> PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_bin` ENGINE = InnoDB ROW_FORMAT = compressed
> ```
> 
> Later my integretiy check showed that the file `lib/Migration/Version0001Date20200602134824.php` is missing, which is I think the root course for this issue.

I copy that folder from github to lib/public/AppFramework/Bootstrap/ and now get other error:
`
An unhandled exception has been thrown:
Error: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found in /var/www/nextcloud/apps/user_status/lib/AppInfo/Application.php:48
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(444): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/nextcloud/lib/private/ServerContainer.php(105): class_exists()
#5 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\ServerContainer->getAppContainer()
#6 /var/www/nextcloud/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query()
#7 /var/www/nextcloud/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance()
#8 /var/www/nextcloud/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep()
#9 /var/www/nextcloud/lib/private/Installer.php(587): OC\DB\MigrationService->migrate()
#10 /var/www/nextcloud/lib/private/Installer.php(541): OC\Installer::installShippedApp()
#11 /var/www/nextcloud/lib/private/Updater.php(266): OC\Installer::installShippedApps()
#12 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#13 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#18 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#19 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#21 {main}⏎`

**Comment by faulix** [comment]
You copied both folders? Because there are 2 folders you need to copy:
- lib/**private**/AppFramework/Bootstrap/
- lib/**public**/AppFramework/Bootstrap/

**Comment by Floppik** [comment]
> You copied both folders? Because there are 2 folders you need to copy:
> 
> * lib/**private**/AppFramework/Bootstrap/
> * lib/**public**/AppFramework/Bootstrap/

Yes:

` root@i5 /v/www# ls /var/www/nextcloud/lib/public/AppFramework/Bootstrap
IBootContext.php  IBootstrap.php  IRegistrationContext.php
root@i5 /v/www# ls /var/www/nextcloud/lib/private/AppFramework/Bootstrap
BootContext.php  Coordinator.php  FunctionInjector.php  RegistrationContext.php
root@i5 /v/www# sudo -u www-data php /var/www/nextcloud/occ upgrade
Nextcloud or one of the apps require upgrade - only a limited number of commands are available
You may use your browser or the occ upgrade command to do the upgrade
Set log level to debug
Updating database schema
Updated database
Disabled incompatible app: sharerenamer
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app cloud_federation_api in appstore
Checked for update of app "cloud_federation_api" in appstore
Checking for update of app comments in appstore
Checked for update of app "comments" in appstore
Checking for update of app contactsinteraction in appstore
Checked for update of app "contactsinteraction" in appstore
Checking for update of app dav in appstore
Checked for update of app "dav" in appstore
Checking for update of app drawio in appstore
Checked for update of app "drawio" in appstore
Checking for update of app duplicatefinder in appstore
Checked for update of app "duplicatefinder" in appstore
Checking for update of app extract in appstore
Checked for update of app "extract" in appstore
Checking for update of app federatedfilesharing in appstore
Checked for update of app "federatedfilesharing" in appstore
Checking for update of app federation in appstore
Checked for update of app "federation" in appstore
Checking for update of app files in appstore
Checked for update of app "files" in appstore
Checking for update of app files_accesscontrol in appstore
Checked for update of app "files_accesscontrol" in appstore
Checking for update of app files_downloadactivity in appstore
Checked for update of app "files_downloadactivity" in appstore
Checking for update of app files_fulltextsearch in appstore
Checked for update of app "files_fulltextsearch" in appstore
Checking for update of app files_fulltextsearch_tesseract in appstore
Checked for update of app "files_fulltextsearch_tesseract" in appstore
Checking for update of app files_pdfviewer in appstore
Checked for update of app "files_pdfviewer" in appstore
Checking for update of app files_rightclick in appstore
Checked for update of app "files_rightclick" in appstore
Checking for update of app files_sharing in appstore
Checked for update of app "files_sharing" in appstore
Checking for update of app files_trashbin in appstore
Checked for update of app "files_trashbin" in appstore
Checking for update of app files_versions in appstore
Checked for update of app "files_versions" in appstore
Checking for update of app files_videoplayer in appstore
Checked for update of app "files_videoplayer" in appstore
Checking for update of app firstrunwizard in appstore
Checked for update of app "firstrunwizard" in appstore
Checking for update of app fulltextsearch in appstore
Checked for update of app "fulltextsearch" in appstore
Checking for update of app fulltextsearch_elasticsearch in appstore
Checked for update of app "fulltextsearch_elasticsearch" in appstore
Checking for update of app groupfolders in appstore
Checked for update of app "groupfolders" in appstore
Checking for update of app issuetemplate in appstore
Checked for update of app "issuetemplate" in appstore
Checking for update of app logreader in appstore
Checked for update of app "logreader" in appstore
Checking for update of app lookup_server_connector in appstore
Checked for update of app "lookup_server_connector" in appstore
Checking for update of app metadata in appstore
Checked for update of app "metadata" in appstore
Checking for update of app nextcloud_announcements in appstore
Checked for update of app "nextcloud_announcements" in appstore
Checking for update of app notifications in appstore
Checked for update of app "notifications" in appstore
Checking for update of app oauth2 in appstore
Checked for update of app "oauth2" in appstore
Checking for update of app ocdownloader in appstore
Checked for update of app "ocdownloader" in appstore
Checking for update of app onlyoffice in appstore
Checked for update of app "onlyoffice" in appstore
Checking for update of app password_policy in appstore
Checked for update of app "password_policy" in appstore
Checking for update of app passwords in appstore
Checked for update of app "passwords" in appstore
Checking for update of app photos in appstore
Checked for update of app "photos" in appstore
Checking for update of app previewgenerator in appstore
Checked for update of app "previewgenerator" in appstore
Checking for update of app privacy in appstore
Checked for update of app "privacy" in appstore
Checking for update of app provisioning_api in appstore
Checked for update of app "provisioning_api" in appstore
Checking for update of app recommendations in appstore
Checked for update of app "recommendations" in appstore
Checking for update of app serverinfo in appstore
Checked for update of app "serverinfo" in appstore
Checking for update of app settings in appstore
Checked for update of app "settings" in appstore
Checking for update of app sharebymail in appstore
Checked for update of app "sharebymail" in appstore
Checking for update of app sharingpath in appstore
Checked for update of app "sharingpath" in appstore
Checking for update of app systemtags in appstore
Checked for update of app "systemtags" in appstore
Checking for update of app text in appstore
Checked for update of app "text" in appstore
Checking for update of app theming in appstore
Checked for update of app "theming" in appstore
Checking for update of app twofactor_backupcodes in appstore
Checked for update of app "twofactor_backupcodes" in appstore
Checking for update of app updatenotification in appstore
Checked for update of app "updatenotification" in appstore
Checking for update of app viewer in appstore
Checked for update of app "viewer" in appstore
Checking for update of app workflowengine in appstore
Checked for update of app "workflowengine" in appstore
Checking for update of app sharerenamer in appstore
Checked for update of app "sharerenamer" in appstore
An unhandled exception has been thrown:
Error: Interface 'OCP\AppFramework\Bootstrap\IBootstrap' not found in /var/www/nextcloud/apps/user_status/lib/AppInfo/Application.php:48
Stack trace:
#0 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(444): include()
#1 /var/www/nextcloud/lib/composer/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#3 [internal function]: spl_autoload_call()
#4 /var/www/nextcloud/lib/private/ServerContainer.php(105): class_exists()
#5 /var/www/nextcloud/lib/private/ServerContainer.php(132): OC\ServerContainer->getAppContainer()
#6 /var/www/nextcloud/lib/private/DB/MigrationService.php(444): OC\ServerContainer->query()
#7 /var/www/nextcloud/lib/private/DB/MigrationService.php(468): OC\DB\MigrationService->createInstance()
#8 /var/www/nextcloud/lib/private/DB/MigrationService.php(414): OC\DB\MigrationService->executeStep()
#9 /var/www/nextcloud/lib/private/Installer.php(587): OC\DB\MigrationService->migrate()
#10 /var/www/nextcloud/lib/private/Installer.php(541): OC\Installer::installShippedApp()
#11 /var/www/nextcloud/lib/private/Updater.php(266): OC\Installer::installShippedApps()
#12 /var/www/nextcloud/lib/private/Updater.php(130): OC\Updater->doUpgrade()
#13 /var/www/nextcloud/core/Command/Upgrade.php(255): OC\Updater->upgrade()
#14 /var/www/nextcloud/3rdparty/symfony/console/Command/Command.php(255): OC\Core\Command\Upgrade->execute()
#15 /var/www/nextcloud/3rdparty/symfony/console/Application.php(1012): Symfony\Component\Console\Command\Command->run()
#16 /var/www/nextcloud/3rdparty/symfony/console/Application.php(272): Symfony\Component\Console\Application->doRunCommand()
#17 /var/www/nextcloud/3rdparty/symfony/console/Application.php(148): Symfony\Component\Console\Application->doRun()
#18 /var/www/nextcloud/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#19 /var/www/nextcloud/console.php(100): OC\Console\Application->run()
#20 /var/www/nextcloud/occ(11): require_once('/var/www/nextcl...')
#21 {main}⏎  `

**Comment by faulix** [comment]
In this case I don't know, for me it worked. Sorry.

**Comment by Floppik** [comment]
Try upgrade to version 19.0.6. Get same error. After create folders manually and copy files rom github give other error:

An unhandled exception has been thrown:

Error: Class 'Doctrine\DBAL\Types\Types' not found in /config/www/nextcloud/apps/user_status/lib/Migration/Version0001Date20200602134824.php:52

**Comment by kesselb** [comment]
Are you sure that you are updating to 19.0.6? `OCP\AppFramework\Bootstrap\IBootstrap` and user_status app are new in Nextcloud 20. If you see such a warning on Nextcloud 19 something very weird is going on. Are you using our updater to update?

**Comment by ChristophWurst** [comment]
Yes, this was only added in Nextcloud 20. Don't manually copy random files from the master branch to an old release. This will only move the problem but never fix it.

**Comment by Floppik** [comment]
> * Have you probably upgraded to Nextcloud 20 and downgraded to 19 again due some problems? If so you may delete the user_status app.
 Hmm, maybe a upgrade to 20 version when move Nextcloud to new server and downgrade. Ok, wait stable 20 version, then try update.

**Comment by tigerfoot** [comment]
Hit by the same kind of error I was able to determine that app printer was the root cause of this. Removing printer resolve all issue, look like printer is only compatible with nc 20+

**Comment by ytc-1** [comment]
I'm having the same issue. When I upggraded to 19.06 I followed the procedure to copy the Bootstrap files. Now wanting to go to 20, but if I understand correctly I need to upgrade to 19.08 1st.

Hit the same problem, but coppying the dirs has not helped. Now just get a blank screen when I come out of maint.
Apache Error log shows.

[Thu Feb 04 10:52:49.581463 2021] [php7:error] [pid 349] [client 82.47.37.5:58214] PHP Fatal error:  Interface 'OCP\\AppFramework\\Bootstrap\\IBootstrap' not found in /var/www/nextcloud/apps/printer/lib/AppInfo/Application.php on line 33

Now trying to roll back to 19.06 .....

**Comment by ChristophWurst** [comment]
> I followed the procedure to copy the Bootstrap files

Where did you find those instructions?

**Comment by ytc-1** [comment]
At the top of this thread.

I've upgraded to 20.07 manually now, a bit bit messy ended up with a lot "EXTRA" files in the security/integrity scan (had to manully delete), also some mysql DB errors that needed fixing and had to set "MySQL is used as database but does not support 4-byte characters". Will sort that another time.

Seemed a lot of niggly work as 19.06 was all fine before I started :-)
