### ISSUE TITLE
Update to 20.0.2 fails with no table with name 'mydatabse.oc_direct_edit'

### ISSUE THREAD

**Issue by choybe** [nextcloud/server#24285]
Update to 20.0.2

Doctrine\DBAL\Schema\SchemaException: There is no table with name 'mydatabse.oc_direct_edit' in the schema.
Detailed logs

Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Doctrine\DBAL\Schema\SchemaException: There is no table with name 'mydatabase.oc_direct_edit' in the schema.

**Comment by hemelingertrinker** [comment]
Same here. Tried to upgrade from 19.0.4 to 20.0.2 using the web updater.

First, I got an error similar to https://github.com/nextcloud/server/issues/13732; I was able to solve it by applying the solutions suggested by @Altau3 and @bodograumann.

Now, after re-trying to upgrade, I get the same error message like the OP.

**Comment by hemelingertrinker** [comment]
Creating the missing table `oc_direct_edit` table solved it for me:

`CREATE TABLE oc_direct_edit (id BIGINT AUTO_INCREMENT NOT NULL PRIMARY KEY, editor_id VARCHAR(64) NOT NULL, token VARCHAR(64) NOT NULL, file_id BIGINT NOT NULL, user_id VARCHAR(64) DEFAULT NULL, share_id BIGINT DEFAULT NULL, timestamp BIGINT UNSIGNED NOT NULL, accessed TINYINT(1) DEFAULT '0', file_path VARCHAR(4000) DEFAULT NULL);`

and

`ALTER TABLE oc_direct_edit ADD INDEX(token);`

Make sure the table looks like this:
```
MariaDB [nextcloud]> describe oc_direct_edit;
+-----------+---------------------+------+-----+---------+----------------+
| Field     | Type                | Null | Key | Default | Extra          |
+-----------+---------------------+------+-----+---------+----------------+
| id        | bigint(20)          | NO   | PRI | NULL    | auto_increment |
| editor_id | varchar(64)         | NO   |     | NULL    |                |
| token     | varchar(64)         | NO   | MUL | NULL    |                |
| file_id   | bigint(20)          | NO   |     | NULL    |                |
| user_id   | varchar(64)         | YES  |     | NULL    |                |
| share_id  | bigint(20)          | YES  |     | NULL    |                |
| timestamp | bigint(20) unsigned | NO   |     | NULL    |                |
| accessed  | tinyint(1)          | YES  |     | 0       |                |
| file_path | varchar(4000)       | YES  |     | NULL    |                |
+-----------+---------------------+------+-----+---------+----------------+
9 rows in set (0.00 sec)

```

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
