### ISSUE TITLE
About Auth-download

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#24294]
### Steps to reproduce
1.create a folder
2.update a .pdf file
3.share that folder by link and  hide download 
4.open the pdf in the folder  with link 
### Expected behaviour
it can be download 
![image](https://user-images.githubusercontent.com/43975826/99933040-d1035b80-2d94-11eb-8610-d9db78bf0487.png)

I think that shoudnt be download and printing.

**Comment by AldousS22** [comment]
I updated v19.0.4 to v20.0.1
On version 19.0.04 it works currently
