### ISSUE TITLE
occ files_external:create allows duplicate entries

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24298]
### Steps

1. Run "occ files_external:create" with a specific configuration
1. Run the exact same command again

### Expected result
Error message about duplicate storage.

### Actual result
A second configuration with the exact same mount point, etc gets created.

Please note that if you use `occ files_external:import` multiple times with a JSON file it will correctly complain about duplicate mounts. So this report is mostly about aligning behaviors.

### Version
Nextcloud 20.0.1

**Comment by PVince81** [comment]
Context: I tried to setup external storages with Ansible and Ansible usually requires you to be able to repeat the same command but got a "not changed" result. Returning a text "Duplicate mount" would help achieve that result.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
