### ISSUE TITLE
Nextcloud Music App: the music file path, CSS padding not set

### ISSUE THREAD

**Issue by huzibizi** [nextcloud/server#24291]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Click the 'i' button next to a music file in the nextcloud music app.

### Expected behaviour
padding should be something like 5-20px

### Actual behaviour
no padding at all

can be fixed with 

a #path {padding: 5px;}

**Comment by kesselb** [comment]
https://github.com/owncloud/music is the repositoy for music app.
