### ISSUE TITLE
Add SFTP cipher to external storage app

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#24309]
When using aes128-gcm@openssh.com as a SSH cipher external storages does not connect to the SFTP server.

Is it possible to add support for this cipher and also the aes256-gcm@openssh.com variant?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
