### ISSUE TITLE
Should CAN_INSTALL be deleted on install ?

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24301]
### Steps

1. Extract NC 20.0.2 tarball
1. Run "occ maintenance:install" with relevant arguments
1. Check config/CAN_INSTALL file

### Expected result
The file is gone.

### Actual result
CAN_INSTALL is still there

### Version
Nextcloud 20.0.2

### Context
When using tools like Ansible one might want to check whether the "occ maintenance:install" was run already and the simplest way would be to check if CAN_INSTALL is there to find out whether installation still needs to be run.
But due to this issue this is not possible.

**Comment by PVince81** [comment]
As a workaround I tried to rely on the existence of config.php but due to https://github.com/nextcloud/server/issues/24302 it is also not reliable, as config.php will be created even in case on setup error.

**Comment by cyclops8456** [comment]
@PVince81 I hit the same issue as you yesterday while setting up a Kubernetes deployment.  Worked around it in my deployment by deleting the file in the batch job when the install completes, as other init containers check for the presence of this file before allowing their respective containers to start.  PR up to resolve this, as the web installer and CLI should maintain consistency.

**Comment by PVince81** [comment]
I've asked around and it seems it's expected that the file gets deleted and I should recheck write permissions there, that the "config" folder itself is writable, not only "config/config.php"

**Comment by cyclops8456** [comment]
@PVince81 It might have been expected that the CAN_INSTALL would be deleted when the install finishes, but it never was for the intial CLI install.  The web installer removed the file as expected, but this was missing from the CLI install.  This is resolved by #27492

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by PVince81** [comment]
solved by https://github.com/nextcloud/server/pull/27492
