### ISSUE TITLE
apps/user_ldap/lib/User/User.php:681 $this->access->search returns empty array resulting in Undefined offset: 0 

### ISSUE THREAD

**Issue by T35R6braPwgDJKq** [nextcloud/server#24305]
apps/user_ldap/lib/User/User.php
```php
  5                         $result = $this->connection->getFromCache($cacheKey);
  4                         if (is_null($result)) {
  3                                 $result = $this->access->search('objectclass=*', $ppolicyDN, ['pwdgraceauthnlimit', 'pwdmaxage', 'pwdexpirewarning']);
  2                                 $this->connection->writeToCache($cacheKey, $result);
  1                         }
681 
  1                         $pwdGraceAuthNLimit = array_key_exists('pwdgraceauthnlimit', $result[0]) ? $result[0]['pwdgraceauthnlimit'] : [];
```

In line 681 $result contains an empty array resulting in an Exception (Undefined offset: 0 ) logged due to $result[0] is not existing.

Is that expected behaviour and a configuration problem, i.e. is "$this->access->search" expected to return an empty array?

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
Thank you!
