### ISSUE TITLE
 Opening Document from a share with Notes causes broken Layout

### ISSUE THREAD

**Issue by akoyaxd** [nextcloud/server#24307]
### Steps to reproduce

Install Nextcloud 19 or 20 with Onlyoffice (dedicated Document Server)
Create a Folder
Add a note to the Folder
Share this Folder via Link and allow editing
Follow the share link and edit an Documen

### Expected behaviour

Onlyoffice is loading without the Notes overlapping it

### Actual behaviour

Onlyoffice loads with the notes overlaping Onlyoffice
![screenshot](https://user-images.githubusercontent.com/22196236/99956425-4a478200-2d86-11eb-8869-36b375fd4656.png)

### Server configuration

**Operating system:**
Nextcloud fpm Docker Image
Onlyoffice Docker Image
Host OS is Debian 10

**Web server:**
Nginx

**Database:**
mariadb

**PHP version:**
the one shipping with Nextcloud 20 fpm Image

**Nextcloud version: (see Nextcloud admin page)**
20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Since NC 14 upgraded

**Where did you install Nextcloud from:**
Docker

**Are you using external storage, if yes which one:**
no

**Are you using encryption:**
no

**Are you using an external user-backend, if yes which one:**
LDAP

**Browser:**
Firefox and MS Edge (Chromium based)

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/26828
