### ISSUE TITLE
occ maintenance:install leaving incomplete config.php on error

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24302]
### Steps

1. Run `occ maintenance:install` with the wrong db password or with an inaccessible data directory

### Expected result
Installation aborts, config.php is deleted.

### Actual result
Installation aborts, config.php is created but is incomplete.

### Version
Nextcloud 20.0.2

### Context
I was trying to rely on the existence of config.php to detect whether Nextcloud was already setup or not, but the existence of an invalid one combined with the "[existence of CAN_INSTALL](https://github.com/nextcloud/server/issues/24301)" bug makes it more tricky to detect. Would need to grep config.php contents for "installed" which feels more dirty and less convenient.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
