### ISSUE TITLE
Updating from 19.0.4 to 19.0.5 installs 20.0.2 instead

### ISSUE THREAD

**Issue by pludi** [nextcloud/server#24349]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install 19.0.4
2. Open the updater from the admin settings overview, stating that 19.0.5 is available

### Expected behaviour
Updater opens, pulling Nextcloud Server 19.0.5

### Actual behaviour
Updater opens, pulling Nextcloud Server 20.0.2

### Server configuration

**Operating system:** FreeBSD 12.2-RELEASE

**Web server:** nginx/1.18.0

**Database:** PostgreSQL 12.4

**PHP version:** 7.4.11

**Nextcloud version:** 19.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated all the way since 16

**Where did you install Nextcloud from:** Releases page

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - bookmarks: 3.4.9
  - bruteforcesettings: 2.0.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.2
  - contactsinteraction: 1.0.0
  - cookbook: 0.7.6
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - forms: 2.0.4
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - news: 14.2.2
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - previewgenerator: 2.3.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.0.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - files_videoplayer
  - firstrunwizard
  - survey_client
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.ludikovsky.name",
            "darp7imrofm2pwl66fifvftthfkok375efxj3wefkuzpwc7unqanoxyd.onion"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "https:\/\/nc.ludikovsky.name",
        "dbtype": "pgsql",
        "version": "19.0.4.2",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "loglevel": 0,
        "trashbin_retention_obligation": "auto",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "theme": "",
        "updater.release.channel": "stable",
        "app_install_overwrite": [
            "calendar",
            "twofactor_yubikey"
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 0
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 83.0

**Operating system:** Linux

**Comment by volo-thomas** [comment]
This just happened to me. It's just a home install so it's not a big deal but this could be a huge problem in a production environment.

**Comment by PifPof73** [comment]
Happend yesterday on our production environment.
We went through the update, but now we do have problems with the base encryption module.

**Comment by toxpal** [comment]
Just came here to report this issue, and noticed it's already reported. I have the same problem.

**Comment by pludi** [comment]
@volo-thomas @toxpal
### How to use GitHub

* Please use the +1 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

**Comment by InfamousUser** [comment]
Seems fixed now.

**Comment by pludi** [comment]
Can confirm. Closing the issue.

**Comment by vanMacG** [comment]
I have the same issue again with NC 20 and 21.
I'm on 20.0.8, admin overview offers 20.0.9, updater pulls 21.0.1.

(also see attached images)
![1](https://user-images.githubusercontent.com/8269814/114700521-e1a37680-9d21-11eb-87d9-d3d5656b9cc0.PNG)
![2](https://user-images.githubusercontent.com/8269814/114700526-e405d080-9d21-11eb-92c9-34b007488805.PNG)
