### ISSUE TITLE
iOS profile not allowing to set default account for contacts

### ISSUE THREAD

**Issue by CapSel** [nextcloud/server#24352]
## steps to reproduce
1. Install iOS profile from Nextcloud
2. Configure password for all accounts in profile
3. add google account
4. not able to set Nextcloud account as default one. Not on the list.

Probably bad path to CardDAV... again

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.

**Comment by szaimen** [comment]
Hi please open a new issue for this with up-to-date information. Thanks!

**Comment by szaimen** [comment]
Please open a new issue and fill out the issue template. Thanks!
