### ISSUE TITLE
Hide Dashboard app icon (when it is default?)

### ISSUE THREAD

**Issue by TurkeyMan** [nextcloud/server#24362]
The dashboard appears when you login, it's like a landing page, but it has an unnecessary tab at the top with a circle icon.
The 'home' icon with the nextcloud logo at the top-left goes to the dashboard... it doesn't need 2 icons to navigate there right next to eachother.

Nextcloud has a problem with app/tab overload in general; it feels very noisy and unprofessional. This is a tiny but meaningful little fix to improve in that area, and I imagine it's a trivial fix.

**Comment by kesselb** [comment]
cc @nextcloud/designers 

> The 'home' icon with the nextcloud logo at the top-left goes to the dashboard

The home button goes to the defaultapp. That's the dashboard app for most people yes. So your suggestion is actually to hide the app icon if the app is the default app?

**Comment by wiswedel** [comment]
Hi @TurkeyMan. You might wanna take a look at https://apps.nextcloud.com/apps/apporder.
It allows you to order apps manually as well as hiding selected icons from the navigation bar without having to disable the app.
How does that resonate with your personal requirement for a more neat experience?

**Comment by TurkeyMan** [comment]
Oh cool, just tried that; fixed a bunch of my initial complaints. Thanks for that!

That said, I'd probably still consider this a small but meaningful issue all the same. The way @kesselb described it sounds correct.
NextCloud feels quite full-featured, and seems to work very well generally, but my initial sense is that little things that will elevate the sense of polish towards the mega-corp's platforms would have a high ROI.

**Comment by wiswedel** [comment]
> The way @kesselb described it sounds correct.

Hmmm, implicit logic is always tricky in terms of UX and accessibility.

> NextCloud feels quite full-featured, and seems to work very well generally, but my initial sense is that little things that will elevate the sense of polish towards the mega-corp's platforms would have a high ROI.

Nextcloud is a highly modular ecosystem which on one hand allows for very flexible contributions but makes it on the other hand hard to streamline. Any top-down decisions are in the end even contrary to the project's values.

You are more than welcome to contribute ideas and also code.

**Comment by ma12-co** [comment]
I agree that having 2 links in the header, one beside the other, that do exactly the same thing is not desirable. Redundancy is not bad in and of itself but here I don't see any benefits in it. I'd  also agree with removing the dashboard link. 
@jancborchardt what were the reasons behind introducing it? am I missing something? 

> That's the dashboard app for most people yes.
What do you mean with "most" @kesselb? can it be something else?

**Comment by stefan-niedermann** [comment]
> What do you mean with "most" @kesselb? can it be something else?

Yes, the default app is configurable for each instance. An administrator can also set the Mail app as default app for example. In this case a click on the Nextcloud logo in the top left will redirect you to the Mail app and the dashboard app is not reachable anymore.

**Comment by ma12-co** [comment]
We could maybe hide it only if both of the links route to the dashboard, and show the dashboard icon otherwise?

**Comment by wiswedel** [comment]
@jancborchardt Could you please share your opinion about this?

I advise against implementing that kind of implicit navigation logic.

**Comment by wiswedel** [comment]
@TurkeyMan I hope you don't mind me changing the issue title according to the more general fashion your request has turned into.

**Comment by TurkeyMan** [comment]
> I advise against implementing that kind of implicit navigation logic.

My feeling is it's exactly that kind of fiddly attention to detail that presents as polish from a mature product.

**Comment by TurkeyMan** [comment]
Changed the title again; I'm not sure that logic should apply to any other app. If the default app was the mail app, it's unlikely you'd want the mail app icon to disappear.
The reason the Dashboard icon feels special, it because from a practical point of view dashboard shouldn't be thought of as "an app" to users; it's just a landing/home page, and not an activity you carry out when using nextcloud.

**Comment by wiswedel** [comment]
> If the default app was the mail app, it's unlikely you'd want the mail app icon to disappear.

Agreed.

> dashboard shouldn't be thought of as "an app" to users; it's just a landing/home page

Isn't that what culture has learned to be the 🏠 button?

**Comment by TurkeyMan** [comment]
Right, and I would have said the home button in this case is the nextcloud icon at the top-right... this is why it shouldn't have an additional app icon.

**Comment by juliushaertl** [comment]
We talked about that when working on dashboard but decided to always show the icon as otherwise it would not be really discoverable iirc (cc @jancborchardt)

**Comment by juliushaertl** [comment]
That is even more true if you have a different mail app. Most people would probably expect a mail icon to click to go to the mail app, not the nextcloud or company logo.

**Comment by szaimen** [comment]
> We talked about that when working on dashboard but decided to always show the icon as otherwise it would not be really discoverable iirc (cc @jancborchardt)

Based on this comment I am closing this issue.
