### ISSUE TITLE
LDAP_AUTH External storage user password changes and BAN

### ISSUE THREAD

**Issue by tanguy-opendsi** [nextcloud/server#24389]
### Steps to reproduce
1.  Use External storage with user and password stored in database
2. Log with your user
3. Change the user password in your LDAP
4. Wait a moment 

### Expected behaviour
When Nextcloud scan file and when he got bad credential from external SMB, Nextcloud never has to scan the external storage until the user enters the correct password

### Actual behaviour
Nextcloud scan all time and the user is banned from ldap because to much Auth fail

### Server configuration

**Operating system:* Debian 9 

**Web server:* Apache2

**Database:* Mariadb

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

Nextcloud 21 versions

**Comment by szaimen** [comment]
Hi, please fill out the complete issue template. Thanks! :)

**Comment by tanguy-opendsi** [comment]
> Hi, please fill out the complete issue template. Thanks! :)

hi give you more information about smb, ldap ect.

**Comment by szaimen** [comment]
https://raw.githubusercontent.com/nextcloud/server/master/.github/ISSUE_TEMPLATE/Bug_report.md

**Comment by tanguy-opendsi** [comment]
nevermind --'
