### ISSUE TITLE
Workflow engine returns incorrect results in some circumstances

### ISSUE THREAD

**Issue by jguzej** [nextcloud/server#24397]
### Steps to reproduce
1. Configure flow _File MIME Type "is not" Folder_ to assign tag
2. Create new folder 
3. Check tags assigned.

**Using operator "is not" is important.**

### Expected behaviour
Created folder was not tagged.

### Actual behaviour
Created folder has been tagged.

### Server configuration

**Operating system:**
CentOS Linux release 7.9.2009

**Web server:**
Installed Packages
Name        : httpd
Arch        : x86_64
Version     : 2.4.6
Release     : 95.el7.centos
Size        : 9.4 M
Repo        : installed
From repo   : base
Summary     : Apache HTTP Server
URL         : http://httpd.apache.org/
License     : ASL 2.0

**Database:**
Name        : MariaDB-server
Arch        : x86_64
Version     : 10.4.17
Release     : 1.el7.centos
Size        : 127 M
Repo        : installed
From repo   : MariaDB
Summary     : MariaDB: a very fast and robust SQL database server
URL         : http://mariadb.org
License     : GPLv2

**PHP version:**
Name        : php
Arch        : x86_64
Version     : 7.3.24
Release     : 1.el7.remi
Size        : 10 M
Repo        : installed
From repo   : remi-php73
Summary     : PHP scripting language for creating dynamic web sites
URL         : http://www.php.net/
License     : PHP and Zend and BSD and MIT and ASL 1.0 and NCSA

**Nextcloud version:** (see Nextcloud admin page)
19.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - announcementcenter: 3.8.1
  - calendar: 2.0.4
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contacts: 3.4.2
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - deck: 1.2.2
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.2
  - files_antivirus: 3.0.0
  - files_automatedtagging: 1.9.0
  - files_mindmap: 0.0.23
  - files_pdfviewer: 1.8.0
  - files_retention: 1.8.2
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - groupfolders: 7.1.1
  - guests: 1.6.1
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - metadata: 0.12.0
  - nextcloud_announcements: 1.8.0
  - notes: 3.6.4
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - quota_warning: 1.8.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - spreed: 9.0.6
  - systemtags: 1.9.0
  - tasks: 0.13.6
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.9.0
  - user_ldap: 1.9.1
  - user_saml: 3.2.1
  - viewer: 1.3.0
  - workflow_pdf_converter: 1.4.0
  - workflowengine: 2.1.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.5.2",
        "overwrite.cli.url": "https:\/\/"***REMOVED SENSITIVE VALUE***"",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "proxy": "***REMOVED SENSITIVE VALUE***",
        "proxyuserpwd": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "skeletondirectory": "",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 0,
        "app_install_overwrite": [
            "spreedme"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [
            "admin"
        ],
        "twofactor_enforced_excluded_groups": []
    }
}

```
</details>

The problem was probably caused by the commit https://github.com/nextcloud/server/pull/23212/files  
if ` $this->getActualValue()` and `$this->executeStringCheck($operator, $value, $this->mimeTypeDetector->detectPath($this->path))` does not return the same value and used operator is 'is not', result is allways true. 
Function `detectPath` does not detect directory correctly.
At first glance, code ` || $this->executeStringCheck($operator, $value, $this->mimeTypeDetector->detectPath($this->path))` seems to be redundant, but I probably do not see all relations.

Detection by function `getActualValue()` use `detectPath()` as last resort match.

Sorry for my english.

**Comment by kesselb** [comment]
cc @blizzz @juliushaertl

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by jguzej** [comment]
Issue solved.
