### ISSUE TITLE
S3 default upload part_size set to 500MB

### ISSUE THREAD

**Issue by solracsf** [nextcloud/server#24390]
https://github.com/nextcloud/server/blob/bb7e1bdfb791a08132fadbebe07d65f47ef209eb/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L73

Is there any reason to use 500 MB here instead of the default 5 MB?
cc @rullzer @icewind1991

**Comment by tlinna** [comment]
[There seems to be two relevant limits](https://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html): 

- maximum object size: 5 TB
- maximum number of parts per upload: 10000

5 TB / 10000 = 500 MB. I suspect this is the rationale? Proper solution would probably be to choose appropriate part size **per file** to keep the number of parts in an acceptable range and part size low enough not to cause trouble.

If this is not possible, I'd suggest reducing the part size to ~100 MB range for the time being to mitigate problems (e.g. #24330) . I guess most people can live with 1 TB max file size.

Five 500MB parts is a lot of data to handle at the same time (which can cause timeout issues mentioned - reducing the part size fixed them for me), but concurrency in general has its advantages.

**Comment by acsfer** [comment]
Well, i believe most people use Nextcloud to manage files <1Gb. Bigger files are an exception, not a rule.
So, IMHO, we should keep the default as 5MB and let the admin raise the `uploadPartSize` if needed as this is already possible (although not documented I believe).

**Comment by tlinna** [comment]
If it's easily configurable (in config.php?) then documenting it and reducing the default size to a low value seems perfectly fine to me.

Default of 5MB seems a bit too low to me though, as that would imply a practical 50GB file size limit - ordinary master video files can be larger than that, and I suspect we (a small nonprofit) are not the only one to use S3 external storage for longer term file archival purposes. Maybe something like 20MB would be better?

**Comment by acsfer** [comment]
Yes, in config.php, just like the line specifies:

https://github.com/nextcloud/server/blob/bb7e1bdfb791a08132fadbebe07d65f47ef209eb/lib/private/Files/ObjectStore/S3ConnectionTrait.php#L73

**Comment by szaimen** [comment]
cc @icewind1991

**Comment by tflidd** [comment]
Unfortunately, this issue is not stale, there are still reports by users on the forum with current versions:

https://help.nextcloud.com/t/s3-random-storage-problem-on-large-files/72897/4

**Comment by SignFinder** [comment]
Hi team,
I have found the same problem with upload of files to nextcloud with S3 bucket on-board, and it was related to chunks.
Fixed by file chunks disabling  when they are uploading by the command:
sudo -u www-data php occ config:app:set files max_chunk_size --value 0
More info is there 
https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/big_file_upload_configuration.html#adjust-chunk-size-on-nextcloud-side
