### ISSUE TITLE
Nextcloud does not properly logging rename file events

### ISSUE THREAD

**Issue by Aleksandra-maker** [nextcloud/server#24408]
Hello! 
I was tasked to parse Nextcloud logs to create and store table of when and by what user certain file was added to each folder. I tried to parse nextcloud.log file for that purpose but very soon found out that rename file generates MOVE event that specifies name of the file moved but not the destination or the new name of said file. Is there a way to get this information?

Also is there a way to set up logging of specific methods (I want to avoid debug logging on production if it is possible, but keep events related to create/move/detele files etc)?

Thank you in advance!

**Comment by kesselb** [comment]
Please ask your question at https://help.nextcloud.com/c/dev/11

The admin_audit log is probably what you are looking for: https://portal.nextcloud.com/article/using-the-audit-log-44.html
