### ISSUE TITLE
Option to Open File Location in File Manager

### ISSUE THREAD

**Issue by hahagu** [nextcloud/server#24400]
**Is your feature request related to a problem? Please describe.**
When opening a file through the `Recent Files` menu, there is no way to tell where the file is located. Therefore, finding the location of that specific file is impossible without searching again for the file name. Considering this feature exists in many major file managers, I believe that this feature would benefit the user considerably.

**Describe the solution you'd like**
A button, or a link in the sidebar to open the folder and `scrollto` the file that is currently open.

**Describe alternatives you've considered**
The current best alternative is to search for the file name or contents directly.

**Comment by fqdb** [comment]
Something like this would be perfect, a clickable link in the sidebar that takes you to [/index.php/apps/files/?dir=/Screenshots](/index.php/apps/files/?dir=/Screenshots)
![image](https://user-images.githubusercontent.com/2826336/106791656-7ec49d80-6655-11eb-9843-7593b269ea1a.png)

**Comment by szaimen** [comment]
The option is actually in the right-click or hamburger menu:
![image](https://user-images.githubusercontent.com/42591237/123098482-7a94f300-d431-11eb-9a37-03f5808be833.png)
Isn't this what you are looking for?

**Comment by fqdb** [comment]
@hahagu when right clicking any of the recent items, this right click menu is not available
![image](https://user-images.githubusercontent.com/2826336/123136834-a923c580-d453-11eb-866a-96082bbee480.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers
