### ISSUE TITLE
S3 Objectstore as Primary Storage, Files API malfunction.

### ISSUE THREAD

**Issue by hahagu** [nextcloud/server#24417]
When using S3 objectstore as primary storage, apps such as the `Photos` app and the `Recommendations` app fail to show new files that have been added to the server.
Considering that this happens in not only a single app but multiple apps, which are all using the `Files API`, the problem is suspected to be a bug with the API itself, and not the apps. 

https://github.com/nextcloud/photos/issues/522
https://github.com/nextcloud/recommendations/issues/337

There is no errors within the browser, or logged error messages on the server side.
It can only be concluded, that the API itself is to fault.
Thanks!

**Comment by hahagu** [comment]
Researching the code of photos and recommendations app,
the malfunction is possibly narrowed down to two functions responsible:

`OCP\Files\Folder -> getDirectoryListing();`
`OCP\Files\File ->getMimeType();`

These two functions seem mainly responsible for the errors.

**Comment by szaimen** [comment]
This might get fixed with https://github.com/nextcloud/server/pull/27561, too
