### ISSUE TITLE
Open_basedir and cron jobs!

### ISSUE THREAD

**Issue by SiaNariman** [nextcloud/server#24428]
Hi,
I've tried all 3 wayes to run the background job, but nothing working! open_basedir disabled or enabled to /dev/urandom is the same. The rest working well.
```
$ php cron.php 
PHP Warning:  require_once(): open_basedir restriction in effect. File(/var/www/mydomain.com/public_html/nextcloud/lib/versioncheck.php) is not within the allowed path(s): (/dev/urandom) in /var/www/mydomain.com/public_html/nextcloud/cron.php on line 39
PHP Warning:  require_once(/var/www/mydomain.com/public_html/nextcloud/lib/versioncheck.php): failed to open stream: Operation not permitted in /var/www/mydomain.com/public_html/nextcloud/cron.php on line 39
PHP Fatal error:  require_once(): Failed opening required '/var/www/mydomain.com/public_html/nextcloud/lib/versioncheck.php' (include_path='.:/usr/share/php') in /var/www/mydomain.com/public_html/nextcloud/cron.php on line 39
mydomain.com
```
**System is:**
Debian 10
Apache2
php 7.3
nextcloud 20.0.2

Thanks in advance

**Comment by j-ed** [comment]
This is the official issue and feature tracker of the development and not the official Nextcloud [help forum](https://help.nextcloud.com/), which has been created to address configuration problems as you already know. So please continue with your [related thread](https://help.nextcloud.com/t/cron-php7-3-with-errors/99571/2) in the forum to find a solution of your problem.
