### ISSUE TITLE
NC 20.0.2, opening standard NC png, mp4, pdf fails (Fatal webdav, Error PHP)

### ISSUE THREAD

**Issue by hemertje** [nextcloud/server#24431]
### Steps to reproduce
1. Open standard Nextcloud.png
2. Open standard Nextcloud intro.mp4
3. Open standard Nextcloud Manual.pdf
4. Open standard Reasons to use Nextcloud.pdf

### Expected behaviour
PNG, MP4 and PDF files should be displayed correctly

### Actual behaviour
1+2 opening PNG, MP4 shows 'Error loading...' 
3+4 opening PDF files gives an error:
PDF.js v2.4.456 (build: 228a591c)
Message: Unexpected server response (503) while retrieving PDF "https://nextcloud.*.com/remote.php/dav/files/*/Documents/nextcloud/Nextcloud%20Manual.pdf".

### Server configuration
**Operating system:**
Openmediavault 5.1.15-1

**Web server:**
NGINX/1.14.2

**Database:**
10.3.25-MariaDB-0+deb10u1 Debian 10

**PHP version:**
PHP 7.3

**Nextcloud version:** (see Nextcloud admin page)
NC 20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from NC 20

**Where did you install Nextcloud from:**
Online update

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>
Accessibility
1.6.0
Featured
Activity
2.13.3
Featured
Brute-force settings
2.0.1
Featured
Collaborative tags
1.10.0
Featured
Comments
1.10.0
Featured
Contacts Interaction
1.1.0
Featured
Dashboard
7.0.0
Featured
Deleted files
1.10.1
Featured
Federation
1.10.1
Featured
File sharing
1.12.0
Featured
First run wizard
2.9.0
Featured
Log Reader
2.5.0
Featured
Monitoring
1.10.0
Featured
Nextcloud announcements
1.9.0
Featured
Notifications
2.8.0
Featured
Password policy
1.10.1
Featured
PDF viewer
2.0.1
Featured
Photos
1.2.0
Featured
Privacy
1.4.0
Featured
Recommendations
0.8.0
Featured
Right click
0.17.0
Featured
Share by mail
1.10.0
Featured
Support
1.3.0
Featured
Text
3.1.0
Featured
Theming
1.11.0
Featured
Two-Factor TOTP Provider
5.0.0
Featured
Update notification
1.10.0
Featured
Usage survey
1.8.0
Featured
User status
1.0.1
Featured
Versions
1.13.0
Featured
Video player
1.9.0
Featured
Weather status
1.0.0
Featured
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.3
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.*.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "https:\/\/nextcloud.*.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "Everyone",
            "admin"
        ],
        "twofactor_enforced_excluded_groups": [],
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "maintenance": false,
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

 There are no commands defined in the "ldap" namespace.

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome
**Operating system:**
Openmediavault 

#### Opening standard Nextcloud.png
<details>
Error	PHP
Error: fopen(/srv/dev-disk-by-label-data/cloud/*/files/Documents/nextcloud/Nextcloud intro.mp4): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#356
<<closure>>

OC\Log\ErrorHandler::onError(2, "fopen(/srv/ ... y", "/var/www/ne ... p", 356, { path: "fil ... "})

/var/www/nextcloud/lib/private/Files/Storage/Local.php - line 356:

fopen("/srv/dev-di ... 4", "r")

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 300:

OC\Files\Storage\Local->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1165:

OC\Files\Storage\Wrapper\Wrapper->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1001:

OC\Files\View->basicOperation("fopen", "/Documents/ ... 4", [ "read"], "r")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 434:

OC\Files\View->fopen("Documents/n ... 4", "r")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

<details>

Fatal	webdav
Sabre\DAV\Exception\ServiceUnavailable: Could not open file
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")
</details>

<details>
Error	PHP
Error: fopen(/srv/dev-disk-by-label-data/cloud/*/files/Documents/nextcloud/Nextcloud intro.mp4): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#356
<<closure>>

OC\Log\ErrorHandler::onError(2, "fopen(/srv/ ... y", "/var/www/ne ... p", 356, { path: "fil ... "})

/var/www/nextcloud/lib/private/Files/Storage/Local.php - line 356:

fopen("/srv/dev-di ... 4", "r")

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 300:

OC\Files\Storage\Local->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1165:

OC\Files\Storage\Wrapper\Wrapper->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1001:

OC\Files\View->basicOperation("fopen", "/Documents/ ... 4", [ "read"], "r")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 434:

OC\Files\View->fopen("Documents/n ... 4", "r")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

<details>
Fatal	webdav

Sabre\DAV\Exception\ServiceUnavailable: Could not open file
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

 
#### Opening standard Nextcloud intro.mp4

<details>
Error	PHP

Error: fopen(/srv/dev-disk-by-label-data/cloud//files/Documents/nextcloud/Nextcloud intro.mp4): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#356
<<closure>>

OC\Log\ErrorHandler::onError(2, "fopen(/srv/ ... y", "/var/www/ne ... p", 356, { path: "fil ... "})

/var/www/nextcloud/lib/private/Files/Storage/Local.php - line 356:

fopen("/srv/dev-di ... 4", "r")

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 300:

OC\Files\Storage\Local->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1165:

OC\Files\Storage\Wrapper\Wrapper->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1001:

OC\Files\View->basicOperation("fopen", "/Documents/ ... 4", [ "read"], "r")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 434:

OC\Files\View->fopen("Documents/n ... 4", "r")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

<details>
Fatal	webdav
Sabre\DAV\Exception\ServiceUnavailable: Could not open file
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")
</details>

<details>
Error	PHP
Error: fopen(/srv/dev-disk-by-label-data/cloud/*/files/Documents/nextcloud/Nextcloud intro.mp4): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#356
<<closure>>

OC\Log\ErrorHandler::onError(2, "fopen(/srv/ ... y", "/var/www/ne ... p", 356, { path: "fil ... "})

/var/www/nextcloud/lib/private/Files/Storage/Local.php - line 356:

fopen("/srv/dev-di ... 4", "r")

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 300:

OC\Files\Storage\Local->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1165:

OC\Files\Storage\Wrapper\Wrapper->fopen("files/Docum ... 4", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1001:

OC\Files\View->basicOperation("fopen", "/Documents/ ... 4", [ "read"], "r")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 434:

OC\Files\View->fopen("Documents/n ... 4", "r")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

<details>
Fatal	webdav

Sabre\DAV\Exception\ServiceUnavailable: Could not open file
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

#### Opening standard Nextcloud Manual.pdf

<details>
Error	PHP
Error: fopen(/srv/dev-disk-by-label-data/cloud/*/files/Documents/nextcloud/Nextcloud Manual.pdf): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#356
<<closure>>

OC\Log\ErrorHandler::onError(2, "fopen(/srv/ ... y", "/var/www/ne ... p", 356, { path: "fil ... "})

/var/www/nextcloud/lib/private/Files/Storage/Local.php - line 356:

fopen("/srv/dev-di ... f", "r")

/var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php - line 300:

OC\Files\Storage\Local->fopen("files/Docum ... f", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1165:

OC\Files\Storage\Wrapper\Wrapper->fopen("files/Docum ... f", "r")

/var/www/nextcloud/lib/private/Files/View.php - line 1001:

OC\Files\View->basicOperation("fopen", "/Documents/ ... f", [ "read"], "r")

/var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php - line 434:

OC\Files\View->fopen("Documents/n ... f", "r")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

<details>
Fatal	webdav

Sabre\DAV\Exception\ServiceUnavailable: Could not open file
/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 90:

OCA\DAV\Connector\Sabre\File->get()

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit("method:GET", [ Sabre\HTTP ... }])

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

</details>

**Comment by adnion** [comment]
I get these errors on every file type, even text files! What about you? 
This bug could be a possible candidate for https://github.com/nextcloud/server/issues/23369

These `Could not open file` errors are quite popular among nextcloud users
https://help.nextcloud.com/t/what-on-earth-is-going-on/24098

For non bug-related information here is my discussion thread in the community forum
https://help.nextcloud.com/t/files-app-not-working-in-nc-20-0-2-2/99778

**Comment by hemertje** [comment]
yes saw the errors...
but still no reaction from the developers?

haven't tried txt filed, my standard photo's have no problems

**Comment by j-ed** [comment]
[**Here**]((https://help.nextcloud.com/) ) you will find the [Nextcloud help forum](https://help.nextcloud.com/) where you can asked all kind of questions concerning configuration problems etc. In your case I would vote for a configuration problem, because I've never seen such an url and paths before:
```
... while retrieving PDF "https://nextcloud.*.com/remote.php/dav/files/*/Documents/nextcloud/Nextcloud%20Manual.pdf".
                                           ^^^                        ^^^
```
Same here:
```
Error PHP Error: fopen(/srv/dev-disk-by-label-data/cloud/*/files/Documents/nextcloud/Nextcloud intro.mp4): failed to open stream: 
                                                        ^^^
```
And here:
```
Error PHP Error: fopen(/srv/dev-disk-by-label-data/cloud/*/files/Documents/nextcloud/Nextcloud Manual.pdf): failed to open stream: 
                                                        ^^^
```

**Comment by hemertje** [comment]
Hi,

What do you mean with “such” ?

With * I anonymize the full path

**Comment by adnion** [comment]
My NC instance isn't working for almost 2 days now. The server logs in `/var/log` are not helpful at all.
Are there some advanced debugging techniques users should know about?
I'll probably never update NC again.

**Comment by hemertje** [comment]
Which version where you running without any problems?

**Comment by adnion** [comment]
@hemertje NC19.0.4

**Comment by blackerking** [comment]
Same Error on our System. Simple Solution deactivate the PDF Reader

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
