### ISSUE TITLE
Plain Text emails for shared files and folders

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#24435]
This request is for adding `Plain Text Emails` as an alternative to html-only.  [See this related discussion on the forum](https://help.nextcloud.com/t/shared-shared-with-you-emails-how-do-i-improve-them/99644).
- html formatting of emails confuses recipients because they view them as spam.
- `>>File<<` in email subject and body looks like spam.  Could it either be `File` with no marks or `"File"` which recipients are used to seeing in email.
  - or, format the name in the subject as Google Drive does.  `Example Folder - Invitation to Edit`
- html clients, including Gmail, do not display pictures by default.

In Place Of
![](https://help.nextcloud.com/uploads/default/optimized/3X/e/5/e5507201e4839a50e037674397a2b0071bb9b88b_2_264x250.png)

It would be much cleaner to simply send plain text.  Google Drive Email Example:

```
John@cloud.example.com has invited you to edit the following folder: "Shared"

John: Hey, here is the template.  When you fill it out, make a copy.

Open in
https://cloud.example.com/s/did
```

These sorts of Google Drive emails specify if you were given _view_ or _edit_ access in the body.  They also skip any sorts of `<<marks>>` that are unnecessary.  And, include user comments within the body of the email.  #18319

**Comment by szaimen** [comment]
I think this should already be possible. See https://github.com/nextcloud/server/issues/17187#issuecomment-724675343
Please reopen if this shouldn be the case. Thanks!
