### ISSUE TITLE
Remove >>formatting<< from subject line and body of all Nextcloud server emails

### ISSUE THREAD

**Issue by sunjam** [nextcloud/server#24436]
Hi, thanks for reading this and developing this great tool!  This request is simply to remove `>>this<<` from the subject and body of all Nextcloud server related emails.  It is interpreted by the email recipient as spam and I'd truly appreciate if this was removed entirely to not confuse people.

Current Subject Line:
```
Shared >>Example Folder<< with you
```

Proposed subject line:
```
Example Folder -- Invitation to edit
```
Related #24435 

![](https://camo.githubusercontent.com/8309560b4e2da552d3f48eca8373b32daf6c8c43e65c067e659b5809e22b2698/68747470733a2f2f68656c702e6e657874636c6f75642e636f6d2f75706c6f6164732f64656661756c742f6f7074696d697a65642f33582f652f352f653535303732303165343833396135306530333736373433393761326230303731626239623838625f325f323634783235302e706e67)

**Comment by kesselb** [comment]
That sounds like an issue with the recipients spam filter. >> and << are valid characters to use.

**Comment by sunjam** [comment]
I've seen this in Yahoo and Gmail accounts. The emails are not going to the
spam filter, but just appear very sketchy looking.  Afaik it is the
standard. Interesting to hear that could be incorrect.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
