### ISSUE TITLE
tiny style issue: icon in personal settings in blue button on the bottom is grey, not white

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#24450]
It's a papercut, but it just looks off:
![Screenshot_20201130_132052](https://user-images.githubusercontent.com/551757/100610212-93ac4a00-330f-11eb-85a5-ea89784f76d3.png)

**Comment by 96RadhikaJadhav** [comment]
Could you please assign this issue to me and direct me to the file where it can be changed?

**Comment by Zhoha28** [comment]
Hi, I would like to work on this, if anyone has not been assigned to this yet

**Comment by BrookeDot** [comment]
Hi @96RadhikaJadhav or @Zhoha28 are either of you actively working on this? If not, I may give it a go. While I'm not intimately familiar with the code I did some searching on GitHub and think I found the right files:

HTML: https://github.com/nextcloud/server/blob/905e1918d2796b9a79025283cd6edf2c40f49d77/apps/settings/templates/settings/personal/development.notice.php#L3

SASS: https://github.com/nextcloud/server/blob/8f14403a9cc3fe1758bb29be2e38240bcc4ad9e4/apps/settings/css/settings.scss#L169-L191

**Comment by RafaOP** [comment]
While the icon does look off in gray, the button fades to white on mouseover. Changing the icon to white would make it white on a white background.

**Comment by RafaOP** [comment]
Hey @MorrisJobke, can you take a look at my request when you're available?

**Comment by MorrisJobke** [comment]
> Hey @MorrisJobke, can you take a look at my request when you're available?

Sure :) I mentioned some people :)

**Comment by RafaOP** [comment]
Thanks!

**Comment by J0WI** [comment]
Closed accidentally in #25119, but #25023 is still open

**Comment by Ayushbajpai19** [comment]
I would like to take this issue for hacktoberfest

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
