### ISSUE TITLE
Parameter 'enabledPreviewProviders' on config.php is being ignored

### ISSUE THREAD

**Issue by muchahagrande** [nextcloud/server#24464]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Edit config.php and add the parameter array enabledPreviewProviders
2. Add some providers to the array list

### Expected behaviour
Tell us what should happen
Using the file app you navigate through directories and when you encounter files of the types listed on enabledPreviewProviders array you shoud see that a thumbnail is generated for that file.
Thumbnails of file types NOT listed on enabledPreviewProviders list should not be generated.

### Actual behaviour
Tell us what happens instead
Thumbnails are generated even of file types not listed on enabledPreviewProviders array.
My particular problem is that I don't need thumbnails from office nor pdf documents and thay actually gets created despite my explicit list of wanted formats making my installation to hang for a while accessing a folder with a number of those files.
I had to turn off the whole preview generation because of this issue.

### Server configuration

**Operating system:**
Ubuntu 18.04

**Web server:**
Apache 2

**Database:**
PostgreSQL

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.1

**Where did you install Nextcloud from:**
HanssonIT VMWare Appliance

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list
  - accessibility: 1.6.0
  - activity: 2.13.3
  - admin_audit: 1.10.0
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - keeweb: 0.6.3
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - phonetrack: 0.6.5
  - photos: 1.2.0
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - qownnotesapi: 20.9.0
  - richdocuments: 3.7.10
  - richdocumentscode: 6.4.14
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.3
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "localhost",
            "192.168.2.4",
            "***REMOVED SENSITIVE VALUE***",
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***\/",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "remember_login_cookie_lifetime": "1800",
        "log_rotate_size": "10485760",
        "memcache.local": "\\OC\\Memcache\\Redis",
        "filelocking.enabled": true,
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0.5,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "htaccess.RewriteBase": "\/",
        "loglevel": "2",
        "log_type": "file",
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "logtimezone": "America\/Argentina\/Buenos_Aires",
        "default_language": "es_AR",
        "force_language": "es_AR",
        "default_locale": "es_AR",
        "force_locale": "es_AR",
        "log.condition": {
            "apps": [
                "admin_audit"
            ]
        },
        "maintenance": false,
        "mail_smtpsecure": "ssl",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "knowledgebaseenabled": false,
        "app_install_overwrite": [
            "keeweb"
        ],
        "lost_password_link": "disabled",
        "enable_previews": false,
        "preview_max_x": 512,
        "preview_max_y": 512,
        "preview_max_filesize_image": -1,
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\HEIC",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Krita"
        ],
        "twofactor_enforced": "false",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [],
        "skeletondirectory": "",
        "theme": ""
    },
    "apps": {
        "accessibility": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "1.6.0"
        },
        "activity": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.13.3"
        },
        "admin_audit": {
            "installed_version": "1.10.0",
            "types": "logging",
            "enabled": "yes"
        },
        "appointments": {
            "hk": "7ad30d20184003996cc6979fcb74fc36878995ebd53ff1f8fa0d8162dcf1f868",
            "enabled": "no",
            "tiv": "0e81d4c1866a64df92e12b96c16208c4",
            "installed_version": "1.0.9",
            "types": ""
        },
        "backgroundjob": {
            "lastjob": "1120"
        },
        "calendar": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "2.1.2"
        },
        "cloud_federation_api": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.3.0"
        },
        "comments": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.10.0"
        },
        "contacts": {
            "types": "dav",
            "installed_version": "3.4.2",
            "enabled": "yes"
        },
        "contactsinteraction": {
            "installed_version": "1.1.0",
            "types": "dav",
            "enabled": "[\"admin\",\"users\"]"
        },
        "core": {
            "installedat": "1556145584.2366",
            "vendor": "nextcloud",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "public_files": "files_sharing\/public.php",
            "backgroundjobs_mode": "cron",
            "shareapi_default_expire_date": "yes",
            "oc.integritycheck.checker": "[]",
            "shareapi_expire_after_n_days": "1",
            "shareapi_allow_public_upload": "yes",
            "scss.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "shareapi_allow_share_dialog_user_enumeration": "no",
            "enterpriseLogoChecked": "yes",
            "shareapi_allow_group_sharing": "yes",
            "shareapi_default_permission_candelete": "no",
            "newUser.sendEmail": "no",
            "lastupdatedat": "1606774801",
            "lastupdateResult": "[]",
            "shareapi_enable_link_password_by_default": "no",
            "shareapi_only_share_with_group_members": "no",
            "shareapi_default_permission_canupdate": "no",
            "shareapi_default_permission_cancreate": "no",
            "shareapi_exclude_groups": "yes",
            "shareapi_exclude_groups_list": "[\"Amigos\"]",
            "shareapi_default_permissions": "1",
            "shareapi_enabled": "yes",
            "theming.variables": "d41d8cd98f00b204e9800998ecf8427e",
            "lastcron": "1606823701",
            "shareapi_default_permission_canshare": "no"
        },
        "dashboard": {
            "installed_version": "7.0.0",
            "types": "",
            "enabled": "[\"admin\",\"users\"]"
        },
        "dav": {
            "types": "filesystem",
            "enabled": "yes",
            "regeneratedBirthdayCalendarsForYearFix": "yes",
            "installed_version": "1.16.1",
            "buildCalendarSearchIndex": "yes",
            "chunks_migrated": "1",
            "buildCalendarReminderIndex": "yes",
            "sendEventRemindersPush": "yes"
        },
        "deck": {
            "installed_version": "1.0.2",
            "types": "dav",
            "enabled": "no"
        },
        "extract": {
            "types": "",
            "enabled": "no",
            "installed_version": "1.2.4"
        },
        "federatedfilesharing": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.10.1"
        },
        "federation": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.10.1"
        },
        "files": {
            "default_quota": "0 B",
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.15.0",
            "cronjob_scan_files": "500",
            "watermark_shareAll": "no",
            "watermark_shareRead": "no",
            "watermark_linkSecure": "no",
            "watermark_linkRead": "no",
            "watermark_linkAll": "no",
            "watermark_linkTags": "no",
            "watermark_linkTagsList": "",
            "watermark_allGroups": "no",
            "watermark_allGroupsList": "",
            "watermark_allTags": "no",
            "watermark_allTagsList": "",
            "watermark_text": "",
            "watermark_enabled": "no"
        },
        "files_external": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.11.1",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,swift,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC",
            "allow_user_mounting": "no"
        },
        "files_pdfviewer": {
            "types": "",
            "installed_version": "2.0.1",
            "enabled": "[\"admin\",\"users\",\"Amigos\"]"
        },
        "files_rightclick": {
            "types": "",
            "installed_version": "0.17.0",
            "enabled": "[\"admin\",\"users\",\"rastreo\",\"Amigos\"]"
        },
        "files_sharing": {
            "types": "filesystem",
            "installed_version": "1.12.0",
            "enabled": "yes",
            "lookupServerUploadEnabled": "no"
        },
        "files_texteditor": {
            "installed_version": "2.8.0",
            "types": "",
            "enabled": "no"
        },
        "files_trashbin": {
            "types": "filesystem,dav",
            "enabled": "yes",
            "installed_version": "1.10.1"
        },
        "files_versions": {
            "types": "filesystem,dav",
            "enabled": "yes",
            "installed_version": "1.13.0"
        },
        "files_videoplayer": {
            "types": "",
            "installed_version": "1.9.0",
            "enabled": "[\"admin\",\"users\",\"Amigos\"]"
        },
        "firstrunwizard": {
            "installed_version": "2.5.0",
            "types": "logging",
            "enabled": "no"
        },
        "gallery": {
            "types": "",
            "installed_version": "18.4.0",
            "enabled": "no"
        },
        "issuetemplate": {
            "installed_version": "0.5.0",
            "types": "",
            "enabled": "no"
        },
        "keeweb": {
            "installed_version": "0.6.3",
            "enabled": "[\"admin\",\"users\"]",
            "types": ""
        },
        "logreader": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "2.5.0",
            "live": "1",
            "relativedates": "",
            "levels": "11111"
        },
        "lookup_server_connector": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "maps": {
            "osrmBikeURL": "",
            "lastAddressLookup": "1604202004",
            "osrmCarURL": "",
            "osrmDEMO": "on",
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "0.1.8"
        },
        "nextcloud_announcements": {
            "types": "logging",
            "installed_version": "1.9.0",
            "enabled": "yes",
            "pub_date": "Thu, 24 Oct 2019 00:00:00 +0200"
        },
        "notes": {
            "types": "",
            "installed_version": "4.0.1",
            "enabled": "[\"admin\",\"users\"]"
        },
        "notifications": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "2.8.0"
        },
        "oauth2": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.8.0"
        },
        "password_policy": {
            "types": "authentication",
            "enabled": "yes",
            "installed_version": "1.10.1"
        },
        "phonetrack": {
            "types": "",
            "installed_version": "0.6.5",
            "enabled": "[\"admin\",\"rastreo\",\"users\"]"
        },
        "photos": {
            "enabled": "[\"admin\",\"users\"]",
            "types": "",
            "installed_version": "1.2.0"
        },
        "previewgenerator": {
            "heighSizes": "512",
            "squareSizes": "512",
            "heightSizes": "256",
            "types": "filesystem",
            "installed_version": "3.0.1",
            "widthSizes": "512",
            "enabled": "no"
        },
        "privacy": {
            "types": "",
            "installed_version": "1.4.0",
            "enabled": "[\"admin\",\"users\"]",
            "readableLocation": "ar"
        },
        "provisioning_api": {
            "types": "prevent_group_restriction",
            "enabled": "yes",
            "installed_version": "1.10.0"
        },
        "qownnotesapi": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "20.9.0"
        },
        "recommendations": {
            "types": "",
            "installed_version": "0.5.0",
            "enabled": "no"
        },
        "richdocuments": {
            "doc_format": "",
            "canonical_webroot": "",
            "use_groups": "admin|users",
            "types": "filesystem,dav,prevent_group_restriction",
            "public_wopi_url": "https:\/\/***REMOVED SENSITIVE VALUE***\/apps\/richdocumentscode\/proxy.php?req=",
            "enabled": "yes",
            "installed_version": "3.7.10",
            "edit_groups": "",
            "wopi_url": "https:\/\/***REMOVED SENSITIVE VALUE***\/apps\/richdocumentscode\/proxy.php?req=",
            "disable_certificate_verification": "yes",
            "external_apps": ""
        },
        "richdocumentscode": {
            "installed_version": "6.4.14",
            "types": "",
            "enabled": "yes"
        },
        "serverinfo": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "1.10.0"
        },
        "settings": {
            "installed_version": "1.2.0",
            "enabled": "yes",
            "types": ""
        },
        "sharebymail": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "1.10.0"
        },
        "spreed": {
            "has_reference_id": "yes",
            "start_conversations": "[\"admin\",\"users\"]",
            "types": "prevent_group_restriction",
            "hide_signaling_warning": "yes",
            "signaling_ticket_secret": "***REMOVED SENSITIVE VALUE***",
            "project_access_invalidated": "1",
            "stun_servers": "***REMOVED SENSITIVE VALUE***",
            "enabled": "yes",
            "installed_version": "10.0.3",
            "signaling_servers": "***REMOVED SENSITIVE VALUE***",
            "allowed_groups": "[\"users\",\"Amigos\",\"admin\"]",
            "turn_servers": "***REMOVED SENSITIVE VALUE***"
        },
        "support": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "no"
        },
        "survey_client": {
            "installed_version": "1.4.0",
            "types": "",
            "enabled": "no"
        },
        "systemtags": {
            "types": "logging",
            "enabled": "yes",
            "installed_version": "1.10.0"
        },
        "tasks": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "0.13.6"
        },
        "text": {
            "types": "dav",
            "installed_version": "3.1.0",
            "enabled": "[\"admin\",\"users\"]"
        },
        "theming": {
            "types": "logging",
            "enabled": "yes",
            "logoMime": "image\/png",
            "installed_version": "1.11.0",
            "name": "***REMOVED SENSITIVE VALUE***",
            "url": "***REMOVED SENSITIVE VALUE***",
            "slogan": "***REMOVED SENSITIVE VALUE***",
            "color": "#DADADA",
            "backgroundMime": "backgroundColor",
            "cachebuster": "8"
        },
        "twofactor_backupcodes": {
            "types": "",
            "enabled": "yes",
            "installed_version": "1.9.0"
        },
        "twofactor_nextcloud_notification": {
            "ijm_enabled": "1",
            "types": "",
            "installed_version": "3.0.0",
            "fjm_enabled": "1",
            "enabled": "[\"admin\",\"users\"]"
        },
        "updatenotification": {
            "extract": "1.2.4",
            "enabled": "[\"admin\"]",
            "keeweb": "0.6.3",
            "types": "",
            "installed_version": "1.10.0",
            "calendar": "2.0.3",
            "phonetrack": "0.6.4",
            "qownnotesapi": "20.9.0",
            "twofactor_nextcloud_notification": "2.3.0",
            "notes": "4.0.1",
            "user_external": "0.8.0",
            "update_check_errors": "0",
            "files_rightclick": "0.15.0",
            "tasks": "0.13.6",
            "spreed": "10.0.3",
            "appointments": "1.1.5",
            "contacts": "3.4.2",
            "maps": "0.1.6",
            "core": "19.0.3.1"
        },
        "user_external": {
            "types": "prelogin,authentication",
            "enabled": "no",
            "installed_version": "0.8.0"
        },
        "user_status": {
            "installed_version": "1.0.1",
            "enabled": "[\"admin\",\"Amigos\",\"users\"]",
            "types": ""
        },
        "viewer": {
            "types": "",
            "enabled": "[\"admin\",\"users\"]",
            "installed_version": "1.4.0"
        },
        "weather_status": {
            "installed_version": "1.0.0",
            "types": "",
            "enabled": "[\"admin\",\"users\"]"
        },
        "workflowengine": {
            "types": "filesystem",
            "enabled": "yes",
            "installed_version": "2.2.0"
        }
    }
}
</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes SMB

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
```
'enabledPreviewProviders' => [
	'OC\Preview\PNG',
	'OC\Preview\JPEG',
	'OC\Preview\GIF',
	'OC\Preview\HEIC',
	'OC\Preview\BMP',
	'OC\Preview\XBitmap',
	'OC\Preview\MP3',
	'OC\Preview\TXT',
	'OC\Preview\MarkDown',
	'OC\Preview\OpenDocument',
	'OC\Preview\Krita',
],
```

Those are enabled by default. PDF and Office are disabled by default. 

```
'enabledPreviewProviders' => [
],
```

Will disabled the preview generation for new files. Previews already generated are still used. If you need to clean the previews https://github.com/nextcloud/server/issues/5717 might help you.

**Comment by muchahagrande** [comment]
Well, it's me that is doing something wrong or something is not working as expected.
I've tried 'enabledPreviewProviders' => [] as you mentioned and it worked as expected with JPG files, but it keeps generating PDF and Office documents thumbnails when entering a folder with that content.
