### ISSUE TITLE
Tag text field not showing consistently

### ISSUE THREAD

**Issue by fourstepper** [nextcloud/server#24473]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

We are experiencing a similar issue to https://github.com/nextcloud/server/issues/10774/ right now on version 20.0.2 - unfortunately, it's pretty hard to reproduce, as it doesn't happen all the time and on the same folders for the same people.

The common denominator is that this is primarily apparent when using Group Folders. We also use the LDAP backend for our users, but I suspect that's not related.

Basically:

### Steps to reproduce
1. Traverse the directory structure and open the details for a file or a folder
2. Click on the three dot (burger menu) in the detail, then on Tags

### Expected behaviour
Open the text field for adding or editing tags every time

### Actual behaviour
Sometimes, the text field for adding or editing tags doesn't open

### Server configuration

**Operating system:**
CentOS 8

**Web server:**
HTTPD

**Database:**
MySQL

**PHP version:**
PHP 7.4.13

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Upgraded from 20.0.0

**Where did you install Nextcloud from:**
The zip package

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "force_locale": "cs",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.idc.cz"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.2.2",
        "overwrite.cli.url": "https:\/\/nc.idc.cz",
        "overwriteprotocol": "https",
        "defaultapp": "apporder",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0
        },
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "app_install_overwrite": [
            "drawio",
            "sharelisting"
        ],
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [],
        "twofactor_enforced_excluded_groups": [
            "admin"
        ],
        "maintenance": false,
        "loglevel": 2,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

</details>

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

### Client configuration
Reproductible on Firefox, Chrome and Edge (Chromium-based), Safari, Windows, Linux, MacOSX

### Logs
I will make sure to add logs as soon as I come across this again

**Comment by kesselb** [comment]
Thank you for reporting this issue  :+1: 

I will need your browser console log to investigate this issue.  Open your console, reload your page and/or do the action leading to this issue and copy/paste the log in this thread.

<details>
<summary>How to access your browser console (Click to expand)</summary>

# Chrome
- Press either CTRL + SHIFT + J to open the “console” tab of the Developer Tools.
- Alternative method:
    1. Press either CTRL + SHIFT + I or F12 to open the Developer Tools.
    2. Click the “console” tab.

# Safari
- Press CMD + ALT + I to open the Web Inspector.
- See Chrome’s step 2. (Chrome and Safari have pretty much identical dev tools.)

# IE9
1. Press F12 to open the developer tools.
2. Click the “console” tab.

# Firefox
- Press CTRL + SHIFT + K to open the Web console (COMMAND + SHIFT + K on Macs).
- or, if Firebug is installed (recommended):
    1. Press F12 to open Firebug.
    2. Click on the “console” tab.

# Opera
1. Press CTRL + SHIFT + I to open Dragonfly.
2. Click on the “console” tab.
</details>

**Comment by fourstepper** [comment]
As soon as I manage to reproduce this again, I will add this information right away

**Comment by paulcalabro** [comment]
I'm experiencing the same issue on v20.0.4. It's a little difficult to reproduce, however. It didn't appear at first, however, I think I clicked on a photo that had an existing tag and then it worked. Or perhaps it was triggered by some other condition. Either way, I've observed this behavior for quite some time so I figured I'd mention it as well.

**Comment by fourstepper** [comment]
Thanks for bumping this @paulcalabro - I just wanted to mention that this is not dead but just a really hard to reproduce issue (that somehow only happens on computers out of my reach due to COVID). I will update this as much as possible with up2date information

**Comment by geep33** [comment]
Wtff idk Wtff I m doing fr

**Comment by fourstepper** [comment]
@paulcalabro btw, in what browser did you see this happen?

**Comment by paulcalabro** [comment]
@fourstepper I'm using FF v84.0.1 to test.

**Comment by fourstepper** [comment]
We have been able to reproduce it only on a single machine consistently in the end, which was a Windows 10 machine running Edgium - clearing the data of the browser (cookies etc.) fixed the issue there.

As far as this goes for me, this can be closed, not sure about @paulcalabro

**Comment by PVince81** [comment]
I found a way to reproduce the issue, it involves going into the other file sections in the left sidebar then coming back.

1. Create a folder "testtag"
2. Go to the "favorites" section on the left sidebar
3. Go back to "all files" (no page reload!)
4. Open the details panel
5. Click "tags" menu entry => it doesn't open

I also noticed that for files listed in the "favorites" section or "shared with link" the "tags" menu also doesn't work.

It is possible that something is getting initialized when loading one of these other sections that messes up with the logic for that field.

**Comment by fourstepper** [comment]
Yep, I can reproduce this as well @PVince81

**Comment by PVince81** [comment]
Not sure how many instances of "Sidebar" exist. In the past there used to be one instance per FileList.
But here it seems there's likely only a single one, because I see this error when switching to Favorites:
<img width="540" alt="image" src="https://user-images.githubusercontent.com/277525/106619676-1ef4c680-6571-11eb-90fd-051198a621b0.png">

Maybe the Vueification of the UI is expecting the sidebar component registration to work differently ?

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/25441
