### ISSUE TITLE
display label for public shares

### ISSUE THREAD

**Issue by brainchild0** [nextcloud/server#24476]
When creating a link for a public share, a short label may be given. However, this label is not shown to visitors using the public link. The name of the file is displayed across the top bar of the web interface to such visitors. Replacing the file name with the   label, if available, would improve the user experience, because the label would be displayed, and users sharing files would be able to mask a file name with a more friendly label, if preferred.

**Comment by szaimen** [comment]
Hi there, thank you for your enhancement idea!
I am not sure if I understood your idea correctly, could you maybe share some screenshots what you are talking about excactly?
Thank you :)

**Comment by brainchild0** [comment]
I think no screenshots are necessary. 

The idea is to show the value of the "share label" rather than the file name for the title when a user previews a file shared through a public link. The file owner may not necessarily wish to expose the file name, whereas, the  "share label" is not currently actually shared through the public link.

**Comment by szaimen** [comment]
cc @nextcloud/designers does this proposal make sense?

**Comment by nimisha-vijay** [comment]
As far as I understand, the share label currently exists to keep track of share links. The name of a file wouldn't particularly be confidential if the contents of the file are shared, don't you think? If you wish to include more information about the file you are sharing, you can include a note to the recipient. 
What do you think?

**Comment by juliushaertl** [comment]
Yes, the note would be the one facing towards the recipient, the label is for internal recognition.

**Comment by brainchild0** [comment]
I accept the distinction, but do feel too that it would be nice to have the ability to replace the file name showing on the title bar with some customized content.

On the subject of the file name, at times I do wish to share the contents of some particular file without sharing the file name I have used in my own directory tree. It would be advantageous to have control over which name is exposed to those accessing the public share.

**Comment by brainchild0** [comment]
If this *bot* is trying to make friends with me, then it should try a different approach.

**Comment by brainchild0** [comment]
Please keep open, _bot_ or no _bot_.
