### ISSUE TITLE
occ group:adduser guid --all would be a great feature for big installations

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/server#24493]
Hello!
When working with big installations it would be very helpful to have some "stack" worflow (batch processing) for occ commands. A concrete case would be to add all or a subset of users (in whichever way these would be chosen; like: everybody but the admin users) to a group via occ comand:

example 1: occ group:adduser guid --all
example 2: occ group:adduser guid1 guid2 guid3 --all --no-admin --no-group2 --no-group3

Am i missing something? Is something like this already implemented. Would be great for other user/group related comands, too.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
