### ISSUE TITLE
Remove the "no-cache, no-store, must-revalidate" for login.html

### ISSUE THREAD

**Issue by Milokita** [nextcloud/server#24490]
While using nextcloud with CDN, the no cache header will prevent the login.html page from being cached. Extending the time for the page to show up 

https://github.com/nextcloud/server/blob/7e6f04490e286450d009c156f08de6a22f0f653d/lib/public/AppFramework/Http/Response.php#L55

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
