### ISSUE TITLE
GroupAdmins should be able to create new (sub-)Groups

### ISSUE THREAD

**Issue by jasond2020** [nextcloud/server#24494]
At the moment the (super)Admin has to create groups and make some accounts GroupAdmin for some groups - so far so good.

But - there are scenarios where user-management is a bit more complex than just using existing groups - and the (super)Admin has some other things to do...

Therefore (and surely one can think of many more reasons) it would be fantastic, if this 'organisational'/administrative right could be forwarded in a more granular way, e.g. as follows:

Give some account (which is already a GroupAdmin) the right to create new groups.
These groups, which where created by this GroupAdmin, have to be assigned to this GroupAdmin account (as if the (super)Admin would have done it).

I would think this is not much of a big issue - and it would differentiate much better 'technical' workflows (for which the (super)Admin is responsible) from 'organisational' workflows (for which the team leaders (in NC the GroupAdmins) are responsible).

**Comment by kinimodmeyer** [comment]
while this is open you can use this app as a workaround: https://apps.nextcloud.com/apps/circles

**Comment by szaimen** [comment]
cc @nextcloud/server-triage are nested groups supported (which would be a requirement for this)?

**Comment by blizzz** [comment]
We do not have nested groups and no plans for it (the LDAP backend also just flattens them). I think circles is the better approach.

**Comment by szaimen** [comment]
Thanks for the feedback. Based on this I am closing this.
