### ISSUE TITLE
OCC->SQL Commands in Shared Hosting to Solve Issues

### ISSUE THREAD

**Issue by Trike27** [nextcloud/server#24507]
Hi,
Nextcloud 19.x shows the attached issues. I should run OCC-commands, but need to do it in a shared-hosting. Can you please translate this for me in SQL-commands which I can run in mySQL? Thank you! 👍 

Best regards
Martin

> In der Datenbank fehlen einige Indizes. Auf Grund der Tatsache, dass das Hinzufügen von Indizes in großen Tabellen einige Zeit in Anspruch nehmen kann, wurden diese nicht automatisch erzeugt. Durch das Ausführen von "occ db:add-missing-indices" können die fehlenden Indizes manuell hinzugefügt werden, während die Instanz weiter läuft. Nachdem die Indizes hinzugefügt wurden, sind Anfragen auf die Tabellen normalerweise schneller.
> 
>     Fehlender Index "initiator_index" in der Tabelle "oc_share".
>     Fehlender Index "twofactor_providers_uid" in der Tabelle "oc_twofactor_providers".
>     Fehlender Index "version" in der Tabelle "oc_whats_new".
>     Fehlender Index "cards_abid" in der Tabelle "oc_cards".
>     Fehlender Index "cards_prop_abid" in der Tabelle "oc_cards_properties".
>     Fehlender Index "calendarobject_calid_index" in der Tabelle "oc_calendarobjects_props".
>     Fehlender Index "schedulobj_principuri_index" in der Tabelle "oc_schedulingobjects".
>     Fehlender Index "properties_path_index" in der Tabelle "oc_properties".
> 
> In der Datenbank fehlen einige optionale Spalten. Da das Hinzufügen von Spalten bei großen Tabellen einige Zeit dauern kann, wurden sie nicht automatisch hinzugefügt, wenn sie optional sein können. Durch Ausführen von "occ db:add-missing-columns" können diese fehlenden Spalten manuell hinzugefügt werden, während die Instanz weiter läuft. Sobald die Spalten hinzugefügt sind, könnten einige Funktionen die Reaktionsfähigkeit oder die Benutzerfreundlichkeit verbessern.
> 
>     Fehlende optionale Spalte "reference_id" in der Tabelle "oc_comments".
> 
> Einige Spalten in der Datenbank können zu big int konvertiert werden. Das Ändern von Spaltentypen kann bei großen Tabellen einige Zeit dauern. Deshalb muss die Konvertierung manuell durch den Befehl "occ db:convert-filecache-bigint" gestartet werden. Zur Konvertierung muss die Instanz offline sein. Einzelheiten dazu auf der zugehörigen Dokumentationsseite.
> 
>     filecache.mtime
>     filecache.storage_mtime
>     filecache_extended.fileid
>     mounts.storage_id
>     mounts.root_id
>     mounts.mount_id

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

https://github.com/nextcloud/server/issues/13704
https://github.com/nextcloud/server/issues/18491
