### ISSUE TITLE
Sharing KO when user belongs to a groups with the same name

### ISSUE THREAD

**Issue by DylannCordel** [nextcloud/server#24510]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Hi folks,

I found a bug when trying to share a file with a group which has the same name than the current user. 

### Steps to reproduce

1. create a **group** « dolly »
2. create a **user** « dolly » as member of **group** « dolly »
3. connect with user « dolly »
4. (not required) share file `Readme.md` with **an other** user or group : it's ok
5. share something with the **group** « dolly » : app is happy, seems ok
6. refresh, and open sharing view : share with the **group** « dolly » is not here
7. disconnect 
8. connect with another user
9. create a file `another-test.md` and share it with **group** « dolly » : it's ok (even after refresh, it's always displayed)
10. create a file `shared-with-user.md` and share it with **user** « dolly » : it's ok (even after refresh, it's always displayed)
11. disconnect
12. connect with user « dolly »
13. in file list, dolly only see `Readme.md` and **not** `another-test.md` neither `shared-with-user.md`

### Expected behaviour

* Step 6: in shares view, we should see the share with the group « dolly »
* Step 13: dolly should see the file shared with the group she belongs too AND the file shared with her

### Actual behaviour

* Step 6: In shares view, dolly does not see the share with the group « dolly » (but we see it in the activity view). In the database, it's ok.
* Step 13: dolly see only it's own file, and not files shared with her group or with her and [she is really sad](https://facimalente.nl/wp-content/uploads/2019/06/2018-01-Als-je-het-allemaal-niet-meer-ziet-zitten-300x300.jpg)

#### Dolly can see the share in the activity tab

![activity](https://user-images.githubusercontent.com/4538884/100895463-df9cf180-34bd-11eb-94e3-12ba938e74f9.png)

#### Dolly can not see the share in the Sharing tab

(and trying to reshare will result in an error because share already exists)

![sharing](https://user-images.githubusercontent.com/4538884/100895480-e4fa3c00-34bd-11eb-8f3c-b5384b7712a5.png)

#### other user see the shares to dolly (user) and dolly (group)

![share-with-group](https://user-images.githubusercontent.com/4538884/100899701-6784fa80-34c2-11eb-8a3e-f0b60b75054b.png) 
![share-with-user](https://user-images.githubusercontent.com/4538884/100899798-7d92bb00-34c2-11eb-8a15-7646660951e5.png)

#### Dolly does not see the 2 expected shared files

![dolly-only-see-her-file](https://user-images.githubusercontent.com/4538884/100899886-969b6c00-34c2-11eb-99f4-04f88b4e2cb2.png)

#### Shares are ok in the DB

(good share_type, users etc.)
```
MariaDB [fosmclouddevelop]> SELECT * FROM oc_share WHERE file_target IN ('/Readme.md', '/another-test.md', '/shared-with-user.md');
+------+------------+---------------+----------+------------+---------------+--------+-----------+-------------+-------------+-------------+----------------------+-------------+------------+----------+------------+-------+-----------+------------+------------------+------+---------------+-------+
| id   | share_type | share_with    | password | uid_owner  | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target          | permissions | stime      | accepted | expiration | token | mail_send | share_name | password_by_talk | note | hide_download | label |
+------+------------+---------------+----------+------------+---------------+--------+-----------+-------------+-------------+-------------+----------------------+-------------+------------+----------+------------+-------+-----------+------------+------------------+------+---------------+-------+
| 9215 |          0 | w-utilisateur | NULL     | dolly      | dolly         |   NULL | file      | 44336       | NULL        |       44336 | /Readme.md           |          19 | 1606923564 |        1 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9216 |          1 | dolly         | NULL     | dolly      | dolly         |   NULL | file      | 44336       | NULL        |       44336 | /Readme.md           |          19 | 1606923572 |        0 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9217 |          2 | dolly         | NULL     | dolly      | dolly         |   9216 | file      | 44336       | NULL        |       44336 | /Readme.md           |          19 | 1606923572 |        1 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9218 |          0 | w-utilisateur | NULL     | django-api | django-api    |   NULL | file      | 44339       | NULL        |       44339 | /another-test.md     |          19 | 1606924215 |        1 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9219 |          1 | dolly         | NULL     | django-api | django-api    |   NULL | file      | 44339       | NULL        |       44339 | /another-test.md     |          19 | 1606924220 |        0 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9220 |          2 | dolly         | NULL     | django-api | django-api    |   9219 | file      | 44339       | NULL        |       44339 | /another-test.md     |          19 | 1606924220 |        1 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9221 |          0 | w-utilisateur | NULL     | django-api | django-api    |   NULL | file      | 44342       | NULL        |       44342 | /shared-with-user.md |          19 | 1606924447 |        1 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
| 9222 |          0 | dolly         | NULL     | django-api | django-api    |   NULL | file      | 44342       | NULL        |       44342 | /shared-with-user.md |          19 | 1606924452 |        1 | NULL       | NULL  |         0 | NULL       |                0 | NULL |             0 | NULL  |
+------+------------+---------------+----------+------------+---------------+--------+-----------+-------------+-------------+-------------+----------------------+-------------+------------+----------+------------+-------+-----------+------------+------------------+------+---------------+-------+
```

### Server configuration

**Nextcloud version:** 18.0.11

**Comment by DylannCordel** [comment]
Seems to be caused by those lines:

https://github.com/nextcloud/server/blob/dc3e05b69a31ef0187dba140520ec053a96ce554/apps/files_sharing/lib/MountProvider.php#L82

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
