### ISSUE TITLE
Error upgrade Nextcloud 20.0.2

### ISSUE THREAD

**Issue by ngarcesv** [nextcloud/server#24526]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Registros detallados 
Preparando la actualización

Establecer el nivel de registro a depuración

Modo mantenimiento activado

Paso de reparación: Repair MySQL collation

Información de reparación: All tables already have the correct collation -> nothing to do

Paso de reparación: Repair SQLite autoincrement

Paso de reparación: Copy data from accounts table when migrating from ownCloud

Paso de reparación: Drop account terms table when migrating from ownCloud

Actualizando el esquema del base de datos

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by roswitina** [comment]
I have the same error message.

**Comment by roswitina** [comment]
that helped me

sudo mysql -u root -p 
MariaDB [(none)]> use nextcloud; 
MariaDB [nextcloud]> set global innodb_large_prefix=on; 
MariaDB [nextcloud]> set global innodb_file_format=Barracuda; 
sudo -u www-data php occ maintenance:repair

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by kesselb** [comment]
```
MariaDB [(none)]> use nextcloud;
MariaDB [nextcloud]> set global innodb_large_prefix=on;
MariaDB [nextcloud]> set global innodb_file_format=Barracuda;
```

Please note that above configuration is not persistent. After the next restart the configuration is gone and the update will fail again.

**Comment by ngarcesv** [comment]
Thank you very much for answering.

How can I make the configuration persistent?

**Comment by steadfasterX** [comment]
> ```
> MariaDB [(none)]> use nextcloud;
> MariaDB [nextcloud]> set global innodb_large_prefix=on;
> MariaDB [nextcloud]> set global innodb_file_format=Barracuda;
> ```
> 
> Please note that above configuration is not persistent. After the next restart the configuration is gone and the update will fail again.

whats needed to make that change persistent?
