### ISSUE TITLE
Untranslated word "Shared" 

### ISSUE THREAD

**Issue by mirktmirkt** [nextcloud/server#24537]
Hello,

I have noticed that word "Shared" is not translated in files view:
https://help.nextcloud.com/uploads/default/original/3X/2/c/2c026cdc84087324151034e72840fb5558a57754.png
https://help.nextcloud.com/uploads/default/original/3X/2/b/2b7102657756d76c1061c580d93f47f276309fcf.png

if I add translation of "Shared" to core/l10n/… locally, it’s translated… But I can not find where to translate it on Transifex?

Regards

**Comment by kesselb** [comment]
cc @MorrisJobke

**Comment by mirktmirkt** [comment]
I have noticed the same situation with “User disabled" on login screen:
https://help.nextcloud.com/uploads/default/original/3X/b/f/bfb9a0fba9526170af1074ad5743cbf6698b280c.png
https://help.nextcloud.com/uploads/default/original/3X/2/0/20a7e4bab37f5ee9df6772c92dbce71e6230f7c4.png

this words are translated on Transifex:
https://help.nextcloud.com/uploads/default/original/3X/c/d/cdd7a732005aeb1a058b35aa229d0b8a8f756ca5.png

**Comment by MorrisJobke** [comment]
Fixed with https://github.com/nextcloud/server/pull/24460

It's in the maintenance RC from yesterday and will be released as 18.0.12, 19.0.6 and 20.0.3 next Thursday.

**Comment by rakekniven** [comment]
JFTR: https://help.nextcloud.com/t/missing-translations/99986
