### ISSUE TITLE
Untranslated "User disabled" on login screen

### ISSUE THREAD

**Issue by mirktmirkt** [nextcloud/server#24549]
Hello,

I have noticed that “User disabled" is not translated on login screen:

Lithuanian login screen:
https://help.nextcloud.com/uploads/default/original/3X/b/f/bfb9a0fba9526170af1074ad5743cbf6698b280c.png

German login screen:
https://help.nextcloud.com/uploads/default/original/3X/2/0/20a7e4bab37f5ee9df6772c92dbce71e6230f7c4.png

These words are translated on Transifex, e.g. Lithuanian:
https://help.nextcloud.com/uploads/default/original/3X/c/d/cdd7a732005aeb1a058b35aa229d0b8a8f756ca5.png

Regards

**Comment by rakekniven** [comment]
Is this located in the following vue file?

https://github.com/nextcloud/server/blob/b327b4fbe6d732cca06bb200921439ac1eba3f15/core/src/components/login/LoginForm.vue#L97

**Comment by rakekniven** [comment]
@MorrisJobke Using 'core' instead of 'lib' ?
