### ISSUE TITLE
Signed iOS provisioning profiles

### ISSUE THREAD

**Issue by johkoenig** [nextcloud/server#24570]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I add the provisioning profile for CalDAV/CardDAV to my iOS device and I receive a ton of warning because the profile is not signed.

**Describe the solution you'd like**
Profiles should be signed (e.g. with the server certificate, if this is technically possible).

**Describe alternatives you've considered**
1. Manual setup. Not good.

**Additional context**
I don't know the technical details of the signing process for iOS provisioning profiles. However, I remember that some years ago I've read a tutorial about creating (signed) iOS provisioning profiles from a php web interface. Maybe somebody with more knowledge about the technical background can give some information.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
