### ISSUE TITLE
URL shortener / ShareRenamer not feasible with NC 18+ core

### ISSUE THREAD

**Issue by TobjasR** [nextcloud/server#24572]
@kesselb , the former Dev of the ShareRenamer app @DecaTec says it's not feasible for NC 18+ any longer, and needs to be implemented in core .. https://github.com/DecaTec/sharerenamer could you please help make ShareRenamer or an integration of polr or yourls feasible by app? =)
––
"This should be implemented as a Nextcloud app and not in the server itself. I'm closing this ticket in favor of https://help.nextcloud.com/t/nextcloud-url-shortener/10855."
_Originally posted by @kesselb in https://github.com/nextcloud/server/issues/20252#issuecomment-607282474_

**Comment by kesselb** [comment]
This should be implemented as a Nextcloud app and not in the server itself. I'm closing this ticket in favor of https://help.nextcloud.com/t/nextcloud-url-shortener/10855.

**Comment by kesselb** [comment]
As reference: https://github.com/DecaTec/sharerenamer/issues/21

Please refrain from creating more issues about this topic. It has nothing do to with nextcloud/server.

**Comment by TobjasR** [comment]
> As reference: [DecaTec/sharerenamer#21](https://github.com/DecaTec/sharerenamer/issues/21)
> 
> Please refrain from creating more issues about this topic. It has nothing do to with nextcloud/server.

thanks for the reference. I've already read it before. However, this:
https://github.com/DecaTec/sharerenamer/issues/21#issuecomment-595049316
and this: https://github.com/DecaTec/sharerenamer/issues/21#issuecomment-657437170 and this: https://github.com/DecaTec/sharerenamer/issues/21#issuecomment-669730083
is what I was referring to. Currently, what you are suggesting just **isn't feasible.**
So, how to fix it?

**Comment by kesselb** [comment]
> So, how to fix it?

https://github.com/DecaTec/sharerenamer/issues/21#issuecomment-625094146

The app author only referenced a issue about the sidebar migration to Vue. Unless the app author creates a enhancement request over here and describe the api changes he needs there is not much we can do.
