### ISSUE TITLE
Error updating to 18.0.11: InvalidArgumentException: Column name "nc_0533_flow_operations"."entity" is NotNull, but has empty string or null as default.

### ISSUE THREAD

**Issue by volkisegler** [nextcloud/server#24573]
Hello,

I am a bit behind with my version and updated from 17.0.3 to 17.0.10 without any problems. Afterwards, the update to version 18.0.11 failed with the following error message:

InvalidArgumentException: Column name "nc_0533_flow_operations"."entity" is NotNull, but has empty string or null as default.

Detailed logs:
Preparing update
Set log level to debug
Turned on maintenance mode
Repair step: Repair MySQL collation
Repair info: All tables already have the correct collation -> nothing to do
Repair step: Repair SQLite autoincrement
Repair step: Copy data from accounts table when migrating from ownCloud
Repair step: Drop account terms table when migrating from ownCloud
Updating database schema
Updated database
InvalidArgumentException: Column name "nc_0533_flow_operations"."entity" is NotNull, but has empty string or null as default.

Could you please tell me how to get past this error?

Thank you,
Volker

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by volkisegler** [comment]
I am hosting on manitu.de and updated from within the web browser logged in as admin.

**Comment by acsfer** [comment]
Please check the pinned issue FAQ. Thanks 😊

**Comment by volkisegler** [comment]
Dear Carlos,

thanks for dealing with my problem. Unfortunately, I can't find the "pinned issue FAQ". Where is it pinned to and where can I find the link? Sorry for asking, but I am relatively new to Github I asking Google didn't help me.

Kind regards,

Volker

**Comment by acsfer** [comment]
![image](https://user-images.githubusercontent.com/12234510/101289115-c1572e80-37fa-11eb-8e8a-96b952a481c3.png)

**Comment by volkisegler** [comment]
Ok, thank you. I guess I have found it: #23174 

Thanks a million!

Volker
