### ISSUE TITLE
update error

### ISSUE THREAD

**Issue by Gaertjen** [nextcloud/server#24576]
Hi, I try to update. but there is a error. I don't know, what to do?

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
InvalidArgumentException: Column name "nc_5047_flow_operations"."entity" is NotNull, but has empty string or null as default.

**Comment by j-ed** [comment]
> InvalidArgumentException: Column name "nc_5047_flow_operations"."entity" is NotNull, but has empty string or null as default

Please check the known issues FAQ for this issue (#23174).

BTW, before you open an issue ticket you should search the Nextcloud help forum, where such a problem should be reported first, and the Nextcloud issue tracker to prevent any duplicate reporting.
