### ISSUE TITLE
Opening certain apps has sometimes a delay.

### ISSUE THREAD

**Issue by piiskop** [nextcloud/server#24577]
### Steps to reproduce
Just click around in the calendar and files! Sometimes you can't reproduce, sometimes you can.

### Expected behaviour
The targets will be loaded immediately.

### Actual behaviour
The targets will sometimes be loaded with a delay of ten seconds or so. 

## Server configuration detail

**Operating system:** Linux 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64

**Webserver:** Apache/2.4.29 (Ubuntu) (apache2handler)

**Database:** mysql 10.1.47

**PHP version:** 

7.2.24-0ubuntu0.18.04.7
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, apache2handler, mysqlnd, PDO, xml, apcu, apc, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, imap, intl, json, exif, mysqli, pdo_mysql, Phar, posix, readline, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
    [maps] => Array
        (
            [INVALID_HASH] => Array
                (
                    [lib/Controller/RoutingController.php] => Array
                        (
                            [expected] => a76dc79838a1e32aceb8d4ec917062bbe8dfad71191e02f6b52520d222f15469d7475967645e1062b7e645cfa11adbb8c14b9b1e32fc6799217d28aa9e89a8f2
                            [current] => 5cbb4f7111ae93b0e9bdb9daf880acada819956940030a1b7eb3fa5d4125352e2f8e09f6c79b43c7683e8a4ba4db677bdf81194a4048609a68b1967d6db94e20
                        )

                )

        )

)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.3
 - admin_audit: 1.10.0
 - audioplayer: 3.0.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.1
 - deck: 1.2.2
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.0.4
 - gpxmotion: 0.1.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.7.1
 - maps: 0.1.8
 - metadata: 0.12.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 2.1.2
 - password_policy: 1.10.1
 - photos: 1.2.0
 - polls: 1.6.2
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - registration: 0.5.2
 - richdocuments: 3.7.11
 - scanner: 0.2.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather: 1.7.4
 - weather_status: 1.0.0
 - wopi: 3.5.6
 - workflowengine: 2.2.0
Disabled:
 - dicomviewer
 - drawio
 - drop_account
 - emlviewer
 - encryption
 - external
 - files_automatedtagging
 - files_external_gdrive
 - ojsxc
 - spreed
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "nextcloud.tennis24.ee"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.2.2",
    "overwrite.cli.url": "https:\/\/test.tennis24.ee\/nextcloud",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "maintenance": false,
    "theme": "",
    "loglevel": 0,
    "app_install_overwrite": [
        "onlyoffice",
        "dashboard",
        "files_external_gdrive",
        "dicomviewer",
        "calendar"
    ],
    "tempdirectory": "\/projektid\/nextcloud\/data",
    "overwriteprotocol": "https",
    "mysql.utf8mb4": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "has_rebuilt_cache": true,
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpmode": "smtp",
    "mail_sendmailmode": "smtp",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpsecure": "tls"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by acsfer** [comment]
I'm sorry to say but this seems a server/configuration issue, not a Nextcloud bug.
I would try https://help.nextcloud.com to help you debug your setup.

**Comment by kesselb** [comment]
It might be a configuration issue or a bug somewhere. There are many factors that influence the response times. I'm closing the report for now as the provided information are not enough to narrow down the problem. Feel free to report back if you are able to tackle it down to a certain app or action.

**Comment by piiskop** [comment]
How can I figure out what exactly causes the slow loading sometimes? For instance, now, I opened _Files_ and loading was slow. Navigating in _Files_ was immediate. Uploading a file also. Then, I opened _Calendar_ and loading was slow again.

**Comment by gu1ll0me** [comment]
@piiskop Same problem on my side. Disabling Collabora Online 3.7.11 solves the loading delay.
