### ISSUE TITLE
Packaging issues with "files_external" app

### ISSUE THREAD

**Issue by rnalrd** [nextcloud/server#246]
Hello,
I'm the package maintainer of Nextcloud for Alpine Linux.
One of the objectives of the distro is to keep the footprint small, so Nextcloud tarball has been splitted into several packages.
Some apps like "files_external" have their own package.

I've found out that "files_external/lib/config.php" is actually called by the "Personal" user page. The class called is "OC_Mount_Config"

`2016/06/29 08:23:09 [error] 244#0: *109119 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Class 'OC_Mount_Config' not found in /usr/share/webapps/nextcloud/settings/personal.php on line 135" while reading response header from upstream, client: ***REDACTED***, server: ***REDACTED***, request: "GET /index.php/settings/personal HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "***REDACTED***"`

Is this correct? If this class is really needed shouldn't be moved into the "core" server?

Looking forward to your comments.

Thanks!

**Comment by LukasReschke** [comment]
Please don't split the apps shipped in https://github.com/nextcloud/server into it's own packages. Everything in this repository can depend on each other. So for the core server I'd just ship this whole Git repository.

With apps in other repositories this should be fine .
