### ISSUE TITLE
Icons for font files are incorrect in Files app

### ISSUE THREAD

**Issue by Mikescops** [nextcloud/server#24603]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload a file that is .ttf or .woff
2. See the the icon displayed in files app (same as pictures)

### Expected behaviour
Have an icon that represent font formats

### Actual behaviour
Icon displayed is a "picture" icon

### Server configuration

**Nextcloud version:** 20.0.2

### Screenshot

![image](https://user-images.githubusercontent.com/4266283/101461871-c53e9a00-393b-11eb-8304-dfe1ae9acb21.png)

**Comment by kesselb** [comment]
**What needs to be done:**

Icons are stored here: `core/img/filetypes`

A mapping for mimetypes: https://github.com/nextcloud/server/blob/master/resources/config/mimetypealiases.dist.json

You either change the existing mapping (e.g. `"application/font-woff": "image"` to `"application/font-woff": "font"`) or remove the aliases (to fallback to the default resolving). 

https://github.com/nextcloud/server/blob/fda6ffc866cf8c5d3579fe95d1731ab747894002/lib/private/Files/Type/Detection.php#L348

Code to resolve a mime type to an icon. It first checks if there is an alias for the mimetype and looks for a file with the mime type name then.

**Comment by Mikescops** [comment]
thanks @kesselb i'll do it then

@jancborchardt do you mind creating an icon for font types?

**Comment by ananyak19** [comment]
Hey I am a first time contributor.. can I work on this?

**Comment by kesselb** [comment]
Install nextcloud to use the command `maintenance:mimetype:update-js`.
