### ISSUE TITLE
Unable to move shared files to shared folders

### ISSUE THREAD

**Issue by fcmildef** [nextcloud/server#24608]
If a user tries to move a file that has been shared with them, into folder that also has been shared with them, the users get the message that the file can not be moved and the file remains in the same place.

### Steps to reproduce
1. User A shares file "file1" with user B
2. User C shares a folder with user B "folder1"
3. User B tries to move "file1" to "folder1" 
4. User B gets error message "Unable to Move file1"

### Expected behavior
User B should be able to move the file to wherever it has write permissions.

### Actual behavior
User B can only move "file1" to its own folders, not to folders that are shared with them. 

### Server configuration

**Operating system:**
Ubuntu 18.04.5 LTS

**Web server:**
Apache2 2.4.29-1ubuntu4.14

**Database:**
mariadb 1:10.1.47-0ubuntu0.18.04.1

**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
20.0.2
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**
website

We are using LDAP as authentication backend.

**Comment by szaimen** [comment]
I think this is as expected since otherwise sharing loops could be created which could crash the server.

**Comment by fcmildef** [comment]
Shouldn't the error message at least be a bit more clear? from a user perspective it is not clear why its not possible to move the file.
