### ISSUE TITLE
Allow to disable zipping/download of specified folders

### ISSUE THREAD

**Issue by ArKay74** [nextcloud/server#24601]
**SItuation**

I have a few download folders that contain very big files. Some users click on the download button and then the whole folder gets zipped which takes forever and hogs the server. Also, zipping those files makes no sense since they are already compressed.

**Request**

It would be nice to have a flag which disables the download/zip on folder level so that it can be disabled on some folders.

**Comment by PVince81** [comment]
or a "max size" option to disable the zip button when a folder is too big ?

**Comment by ArKay74** [comment]
Yeah, that could also be an option in fact, but there might be folders for which you really don't want it to be activated at all (one containing archives or multimedia files).

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
