### ISSUE TITLE
cron功能无效，无论是ajax、cron.php、system cron

### ISSUE THREAD

**Issue by jxjxjhjh** [nextcloud/server#24615]
![2020-12-09 16.15.43 cloud.191954.xyz 8220e39c05e7.png](https://i.loli.net/2020/12/09/f72YgKLF9rMvbT4.png)
![2020-12-09 16.16.30 cloud.191954.xyz e269b3573606.png](https://i.loli.net/2020/12/09/HV2ETsCdIZF9tXD.png)

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
