### ISSUE TITLE
InvalidArgumentException: Column name "oc_flow_operations"

### ISSUE THREAD

**Issue by boust3r** [nextcloud/server#24617]
Got:

InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default

Updated from 17.0.1 to 18.0.11

Log:

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Datenbank aktualisiert
InvalidArgumentException: Column name "oc_flow_operations"."entity" is NotNull, but has empty string or null as default.

**Comment by j-ed** [comment]
Please keep in mind, that this is the bug tracker of the developers and not the [Nextcloud help forum](https://help.nextcloud.com/), which is the right place to report these kind of problems first. Especially the mentioned issue has been reported multiple times and discussed in detail in the forum and a workaround has also been provided. Additionally you will find the issue listed in the ["FAQ + KNOWN ISSUES"](https://github.com/nextcloud/server/issues/23369).

Please keep in mind that it is always worth to **search first**, before posting an issue multiple times 😉
