### ISSUE TITLE
Search for files with "Tag + Keyword" in the search bar

### ISSUE THREAD

**Issue by devi69** [nextcloud/server#24626]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

It would be nice to be able to search for a combination of keywords, such as "Tag + folder name" or "Tag + file name".  

If there is a large number of items to hit in a search, it can strain memory and take a long response time to load all the results once they are displayed.  

It would be great to be able to narrow file search by multiple criteria, like "tag + keyword."   

At #326, it looks like it will be searchable by tag and I'm very much looking forward to it.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/326
