### ISSUE TITLE
Add OCC command to execute all 'recommended' actions

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#24632]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### description

In the admin settings under system checks, Nextcloud often recommends running certain commands on the command line. That is because they can be quite time consuming and break during upgrade, and aren't super crucial.

It would be great if it were possible to execute these with OCC in an easier way, by having a command that runs all of them.

Would also be nice to offer to run them after the upgrade is finished when doing an upgrade from the command line!

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
