### ISSUE TITLE
Support PHP 8 

### ISSUE THREAD

**Issue by freebrowser1** [nextcloud/server#24637]
Nextcloud 20 does not support PHP 8.

When does it support PHP 8 ?

**Comment by kesselb** [comment]
There are no plans to add support for PHP 8 to Nextcloud 20. 

Nextcloud 21 will support PHP 8. However if you don't have to upgrade PHP I would suggest to use PHP 7.4 for a while. It's likely that there are bugs.

As reference: https://help.nextcloud.com/t/nextcloud-and-php-8-x/99658
