### ISSUE TITLE
Add file dialog on public share partially hidden

### ISSUE THREAD

**Issue by drikqlis** [nextcloud/server#24638]
When trying to add file on public share the dialog is partially hidden because there is no left side navigation and CSS is not taking that into cosideration.

Normal logged-in user:
![obraz](https://user-images.githubusercontent.com/19647553/101779834-0aa6c700-3af6-11eb-81fc-820f89bb50ee.png)

Public share with permission to add files:
![obraz](https://user-images.githubusercontent.com/19647553/101779885-1abea680-3af6-11eb-9367-49694c108421.png)

It might be a problem only in different languages, not in English because of length of translation for example: New text file -> Nowy dokument tekstowy.

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/22959
