### ISSUE TITLE
PDF previews do not work in folders that have `#` in their name

### ISSUE THREAD

**Issue by felixfischer** [nextcloud/server#24634]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a folder that has a `#` in its name (e.g., `Project #2342`)
2. Put a PDF file there
3. Try to preview the PDF file

### Expected behaviour
The PDF preview should be shown

### Actual behaviour
PDF.js throws a "Missing PDF" error. The path that is displayed in the error message includes the `#` unescaped. When I copy that path and replace `#` with `%23` I can access the PDF.

### Server configuration

**Operating system:**
Ubuntu 18.04.3 LTS

**Web server:**
Apache (from Nextcloud Docker image)

**Database:**
MySQL

**PHP version:**
7.4.13

**Nextcloud version:** (see Nextcloud admin page)
20.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
16

**Where did you install Nextcloud from:**
Docker hub

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

### Client configuration
**Browser:**
Chrome

**Operating system:**
MacOS

**Comment by AntiSC2** [comment]
Seems to also happen if you have a `&` in the path name

**Comment by axheli** [comment]
Yes I agree

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Closing in favour of https://github.com/nextcloud/viewer/issues/415
