### ISSUE TITLE
TImes should be displayed using timezone derived by user location, or user configuration

### ISSUE THREAD

**Issue by weierophinney** [nextcloud/server#24647]
### Steps to reproduce
As an example, my server is set to UTC.

As a user, I've set my location, which is in North America.

When I go to my dashboard, as a result, the time displayed with the weather widget is in UTC, and not local time.

### Expected behaviour
I would expect one or both of the following:

- Timezone is derived from the user's location.
- User can specify their timezone.
- Anywhere time is specified in the UI, the timezone would be used.

### Actual behaviour
Times are always presented based on the server timezone.

## Server configuration detail

**Operating system:** Linux 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 5.7.32

**PHP version:** 

7.4.13
Modules loaded: Core, date, libxml, openssl, pcre, zlib, bcmath, bz2, ctype, curl, dom, hash, fileinfo, filter, ftp, gd, gmp, SPL, iconv, intl, json, ldap, mbstring, pcntl, PDO, session, posix, Reflection, standard, SimpleXML, mysqlnd, exif, tokenizer, xml, xmlreader, xmlwriter, zip, pdo_mysql, cgi-fcgi, redis, Zend OPcache

**Nextcloud version:** 20.0.2 - 20.0.2.2

**Updated from an older Nextcloud/ownCloud or fresh install:** updated via snap

**Where did you install Nextcloud from:** snap

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.3
 - admin_audit: 1.10.0
 - apporder: 0.11.0
 - calendar: 2.1.2
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.1
 - deck: 1.2.2
 - federatedfilesharing: 1.10.1
 - federation: 1.10.1
 - files: 1.15.0
 - files_external: 1.11.1
 - files_markdown: 2.3.1
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - metadata: 0.12.0
 - music: 0.17.3
 - news: 15.1.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.1
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - suspicious_login: 3.2.1
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_totp: 5.0.0
 - twofactor_u2f: 6.0.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - cookbook
 - encryption
 - files_downloadactivity
 - files_readmemd
 - passman
 - qownnotesapi
 - quicknotes
 - ransomware_protection
 - registration
 - twofactor_email
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "apps_paths": [
        {
            "path": "\/snap\/nextcloud\/current\/htdocs\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/snap\/nextcloud\/current\/nextcloud\/extra-apps",
            "url": "\/extra-apps",
            "writable": true
        }
    ],
    "supportedDatabases": [
        "mysql"
    ],
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0
    },
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "localhost",
        "cloud.mwop.net"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.2.2",
    "overwrite.cli.url": "http:\/\/localhost",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "objectstore": {
        "class": "\\OC\\Files\\ObjectStore\\S3",
        "arguments": {
            "bucket": "cloud-mwop-net",
            "key": "***REMOVED SENSITIVE VALUE***",
            "secret": "***REMOVED SENSITIVE VALUE***",
            "hostname": "cloud-mwop-net.nyc3.digitaloceanspaces.com",
            "region": "nyc3",
            "port": 443,
            "use_ssl": true,
            "use_path_style": true
        }
    },
    "maintenance": false,
    "theme": "",
    "loglevel": 0
}
```
</details>

**Are you using external storage, if yes which one:** Digital Ocean Spaces

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** none

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Operating system:** Ubuntu 20.04

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by pongraczi** [comment]
On the dashboard (v20.0.3) I can see the following weather status:  
![Kijelölés_563](https://user-images.githubusercontent.com/5891983/102210650-bc693d80-3ed2-11eb-9852-412f36eb8ab5.png)
* The location is (Hungary / Vác   GMT+1 at this moment).  
* The server timezone set to Europe/Budapest.
* In fact, the local time is 12:41, the temperature more or less accurate.  

So, I have no idea, how is 17:00 visible on the dashboard.

Meanwhile the windy.com shows the following when I click on the dashboard widget:  
![Kijelölés_564](https://user-images.githubusercontent.com/5891983/102211274-af008300-3ed3-11eb-8da9-e467b87b6e54.png)

**Comment by kesselb** [comment]
@pongraczi https://github.com/nextcloud/server/issues/23399

**Comment by kesselb** [comment]
Thanks for your bug report @weierophinney :+1: 

> Times are always presented based on the server timezone.

We send a request to a weather forecast service based on your location. We don't take the server time in account. The widget shows the upcoming weather. I guess it looks like UTC because the forecast is usually in 4 to 6 hours. 

Closing this report in favour of #23399.
