### ISSUE TITLE
Be notified when one specific file is updated

### ISSUE THREAD

**Issue by Mer0me** [nextcloud/server#24640]
Activity App should propose a way to subscribe to specific files updates rather than all files or all favorite files.

When you have thousands of shared files and you want to follow updates on some specific files, there is no option in the activity app to select those files.

Mark files as favorite and check updates on them is a workaround but I think followed files are not necessarily "favorites".
"Favorites files" are files that I often open and/or update myself.
"Followed files" are files that other users update and I want to be notified when they do.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
