### ISSUE TITLE
Allow unified search to be disabled

### ISSUE THREAD

**Issue by ongun-kanat** [nextcloud/server#24644]
I don't want to use unified search while I am in a specific app like contacts or calendar. It both takes longer to search and display many other results which are irrelevant to the active running app. It would be awesome if there would be an option to disable unified search and keep search per-app basis.

**Comment by mapson01** [comment]
At least for me is not only problematic function it is almost useless, if you are in the mail app and do a search function, it brings me back anything except something related to the email I am looking for. In the same way if you are in notes app, search function brings back a list of hundreds of files names except what I am looking for. So in my opinion the older search does better work. If you are in task app search only try to find in the task app. Probably I don’t know how to use this new feature but for me old way it is better and an option to disable it is a must. Some times you need a full-text search but sometimes only a quick search on the topic you are working is more than enough.

**Comment by kinimodmeyer** [comment]
before deactivating every new feature maybe we should think of improving it.

for me it seems that when you are in a specific app the result of this app sorted on top which is great.
but it seems that depeneding on the app you are it is not always working
(on demo being in deck app founded files come before deck cards)

**Comment by dirigit** [comment]
IMHO there are many more thoughts needed. Related to interface it should not happen that some pull down hides save button (f,e,). Some real usage is needed by developers to see how it works.

What makes a search usable and usefull?
Overhelming number of found results like G* offers due to it's enormous amount of data being available?

No. Never. Manual filtering in such a way is not what anybody wants to have when running a system like NC.

Take tasks as an example.

What might be related to a task?
Date, time, duration, end date and time, contacts (people), notes, documents, ...

To be usefull search should show some kind of minimal information first which can be extended to what you need (more details of contact, notes, etc).

Just some thougt...

cu, diri

**Comment by ongun-kanat** [comment]
@kinimodmeyer I agree on compromises. However, what is the compromise of not doing any search at all apps vs doing it?

Think like this: When we use desktop computers different apps do different jobs. So when I launch my file manager I don't want it to search my calendar at all. Basically it is a modality of mind.

However, a separate unified search application makes sense if I don't know what I am searching for. Maybe a separate app for it in Nextcloud makes sense. It would be nice if unified search is integrated in dashboard or has a special shortcut just like Spotlight search in Macs and Krunner of KDE.

So I propose 3 different "modes" of search:
- A simple filtering whatever that is on the screen
- An app specific search
- A global unified search as a separate app or integrated in the dashboard.

**Comment by skjnldsv** [comment]
Hi, sorry, you can find other issues about dedicated optimisations/improvements.
but the unified search is here to stay.

We are improving a lot in performances, and disabling it would not change anything. All the searches are simultaneous, meaning it doesn't matter if it's enabled or not, the search for your current opened app would still take the same time to show.

The only difference is that it's all in the same place, and it's also being discussed on how to filter the current app more reactively.

Best regards
Cheers

**Comment by MrLoverLoverMMMM** [comment]
Additionally would be nice:

**Comment by MrLoverLoverMMMM** [comment]
Possibility to search with filters with the default search (for example only in the current folder and better ui if there is alot of results as the dropdown is not the best way for more then 100 results^^)

**Comment by tinolin** [comment]
please consider the idea of being able to disable unified search, it wrecks database and performance in large organizations

I had to hide it in the frontend and I don't like having to do that!

please!
