### ISSUE TITLE
[NC 20] Navigation uses bad Font weights for Hover and overflows

### ISSUE THREAD

**Issue by tilllt** [nextcloud/server#24657]
Regarding NC 20.0.3
This is not a technical bug, more a design comment / consideration. The way that the navigation bar is rendered on different browser is not only inconsistent, its imo bad design and doesnt live up to the rest of the Nextcloud GUI. The "bold" Font style that is used when Hovering doesnt look like the proper bold cut of the font but a technically made "bold" weight. Which is typographically a very different thing. Futhermore the positioning of the enlarged element (when hovered) clashes with the typo in the back, which is not sufficiently subdued but too visible to look as if "in the background".

A comparison of some modern and an ancient (windows 10) browser

Chrome Version 87.0.4280.88 (Official Build) (64-bit)
![Chrome](https://user-images.githubusercontent.com/1854364/101893397-fcfc4a80-3ba4-11eb-9a9e-6615a05862ac.jpg)

Firefox v83.0 (64-Bit)
![Screenshot_34](https://user-images.githubusercontent.com/1854364/101893461-11d8de00-3ba5-11eb-94b5-ba815b048542.jpg)

MS Edge Version 87.0.664.57 (Official build) (64-bit)
![Screenshot_35](https://user-images.githubusercontent.com/1854364/101893560-32089d00-3ba5-11eb-96a4-259006e8722a.jpg)

MS Internet Explorer 11.630
![Screenshot_36](https://user-images.githubusercontent.com/1854364/101893651-52385c00-3ba5-11eb-99c3-143933045442.jpg)

I am truly sorry that i cannot be of more help to actually solve this problem, its just that the navigation bar, especially the way the hover is handles, (for me) is absolutely sticking out as ugly, bad UX and not up to par with the rest of the design of NC.

**Comment by acsfer** [comment]
I'm not against the "bold effect", but IMO the link should auto-expand to display the whole content, specially in non-english languages.

Here in French:
![image](https://user-images.githubusercontent.com/12234510/101900978-a432af00-3bb0-11eb-8c46-9ba13c237004.png)
would expect something more like:
![image](https://user-images.githubusercontent.com/12234510/101901131-e0fea600-3bb0-11eb-8b3c-9f5758d17a31.png)

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by tilllt** [comment]
> 
> 
> I'm not against the "bold effect", but IMO the link should auto-expand to display the whole content, specially in non-english languages.
> 
> Here in French:
> ![image](https://user-images.githubusercontent.com/12234510/101900978-a432af00-3bb0-11eb-8c46-9ba13c237004.png)
> would expect something more like:
> ![image](https://user-images.githubusercontent.com/12234510/101901131-e0fea600-3bb0-11eb-8b3c-9f5758d17a31.png)

Yes, if the surrounding Elements would move away from the hovered element, i could live with the typographically wrong bold weight as well. Both problems in combination look really crappy.

**Comment by skjnldsv** [comment]
The font is the same I'd say, but we change the font size and weight.
cc @jancborchardt you changed it recently

**Comment by kesselb** [comment]
cc @jancborchardt :wave:
