### ISSUE TITLE
Problem syncing Card/CalDAV with MacOSX CalendarAgent

### ISSUE THREAD

**Issue by acsfer** [nextcloud/server#24662]
I have a problem with a single user, using MacOS to sync its CalDAV/CarDAV. As only one user, with a configuration different from all others, is causing this issue, i don't believe it's a server configuration, otherwise other users would be affected.

I've looked at https://github.com/nextcloud/server/issues/20624 https://github.com/nextcloud/server/issues/20730 https://github.com/nextcloud/server/issues/20732 

User-agent of this specific user is `Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1`.

nginx `error` log outputs:

> readv() failed (104: Connection reset by peer) while reading upstream, client: 1.2.3.4, server: my.example.com, request: "PROPFIND /remote.php/dav/calendars/peter.l.1%40mail.dot/ HTTP/1.1"

and `access` log, `401` status (user is correctly logged in and identified):

> "PROPFIND /remote.php/dav/calendars/calendars/peter.l.1%40mail.dot/ HTTP/1.1" 401 "Mac+OS+X/10.14.6 (18G103) CalendarAgent/416.5.1"

Nothing at Nextcloud log...

As we have hundreds of users, and only this one has this specific user agent, maybe there is something wrong with him?

This problems stands since Nextcloud 18, all 19 versions and now on 20.0.2/3 too.

- Nextcloud 20.0.3
- nginx/1.19.5
- PHP 7.4.13
- MariaDB 10.4.17
- Memcached 1.6.9

**Comment by szaimen** [comment]
Hm... hard to debug without further logs.
