### ISSUE TITLE
Integrity failed after update, EXTRA_FILE

### ISSUE THREAD

**Issue by teemue** [nextcloud/server#24660]
After updating from NC 20.0.2 to 20.0.3, core integrity check fails for this log file:

`  - EXTRA_FILE:
    - ocm-provider/nextcloud.log:
      - expected:
      - current: cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e`

Removing the file does not solve the issue.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
