### ISSUE TITLE
Sorting by modification date gives wrong order

### ISSUE THREAD

**Issue by farindk** [nextcloud/server#24678]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open directory with many images
2. Click on "Modified" header

### Expected behaviour
Files should be ordered by date

### Actual behaviour
Files are not sorted correctly.

Two example screenshots attached.

![Screenshot from 2020-12-12 17-43-48](https://user-images.githubusercontent.com/968944/101989679-729a1080-3ca2-11eb-9ded-9787739579e5.png)
![Screenshot from 2020-12-12 17-33-40](https://user-images.githubusercontent.com/968944/101989681-7332a700-3ca2-11eb-9530-ce0809708e9b.png)

### Server configuration

**Nextcloud version:** 19.03

**Where did you install Nextcloud from:** Hetzner Storage-Share

**List of activated apps:**
none. Plain Nextcloud.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by farindk** [comment]
I don't know about 21.0.2, but in 20.0.9, there is still the same bug.

![Screenshot from 2021-07-18 15-58-44](https://user-images.githubusercontent.com/968944/126070112-1615704b-dc93-4cdf-974e-3b82fb6495fe.png)

**Comment by farindk** [comment]
I don't see why this should be closed. It's just that nobody seems to have a look for the last 8 months.

**Comment by medarion** [comment]
This happened to me, too, but only for a short period of time. I upgraded from 20.0.11 to 20.0.12 in hopes it would fix the problem after I never experienced this problem, but that didn't help. A few minutes later everything worked again as usual. Cron jobs are correctly set up to execute every 5 minutes, in case it's related and I can't really think of a reason why the should have stopped working for a limited amount of time. On the other hand during the appearance of the problem I didn't check when they had their last execution, so I can't rule this out as a cause.
