### ISSUE TITLE
ldap groups filter and some other things

### ISSUE THREAD

**Issue by ChrisChoke** [nextcloud/server#24696]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. go through ldap wizard without "advanced" config
2. check if user and groups will be found
3. setup advanced config with base search tree for user and groups
4. add the nextcloud group to "only from these group"
5. look at the ldap query filter below the dropdown

hint: my bind-user for nextcloud-ldap binding and the group for nextcloud users have the same name. but the dn is differently.
My Ldap is an Openldap 2.4.47 with the rfc2307bis schema instead of standard nis-schema.

Nextcloud does not support `groupOfMembers` for `the "only from these group" section. Can you implement it?! it is the same as groupOfNames withe the requirement to have members in it.

The User which found from first search after setup up the connection cant be delete with occ commands. 
i have ldap:check-user, the user marked as deleted and was shown on ldap:show-remnants. but with user:delete <uid> an exception throws on conmmand line.
```
In User_LDAP.php line 425:
                                         
  nextcloud is not a valid user anymore  
                                         

user:delete <uid>

```
so no chance to investigate. and the database will have remnants of these user. 

with this setup the `ldapGroupMemberAssocAttr` wasnt setup automaticly. so i have set to `member (AD)` because i think these means the `member` attribute in ldap.

### Expected behaviour
the "only from these groups" section should only show groups from the "base search tree" of advanced config.

### Actual behaviour
the groups dropdown show me my groups, but if i select the nextcloud group, the ldap filter below show the dn of my bind-user from a completly other search base.
```
(memberof=cn=familyshare,ou=groups,dc=local,dc=loc)
(memberof=uid=nextcloud,o=serviceBind,ou=users,dc=local,dc=loc)))
```

### Server configuration

**Operating system:**

Debian 10.7 Buster

**Web server:**

Nginx 1.14.2

**Database:**

Postgresql 12.5

**PHP version:**

7.3.19

**Nextcloud version:** (see Nextcloud admin page)

20.0.3

**Updated from an older Nextcloud/ownCloud or fresh install:**

rolling updates from NC 16 i think

**Where did you install Nextcloud from:**

from tar.gz from your website

**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.1
  - federatedfilesharing: 1.10.1
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.1
  - files_automatedtagging: 1.10.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.2
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "10.1.10.247"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.3.2",
        "overwrite.cli.url": "https:\/\/10.1.10.247",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "skeletondirectory": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "session_lifetime": 600,
        "session_keepalive": false,
        "trashbin_retention_obligation": "auto, 30",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis ": {
            " host ": "\/var\/run\/redis\/redis-server.sock",
            " port ": 6379
        },
        "theme": "",
        "loglevel": 0,
        "updater.release.channel": "beta",
        "app_install_overwrite": [
            "contacts"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "ldapUserCleanupInterval": 30
    }
}

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Configuration                 | s01                                                                                                                                                                 |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 1                                                                                                                                                                   |
| homeFolderNamingRule          |                                                                                                                                                                     |
| lastJpegPhotoLookup           | 0                                                                                                                                                                   |
| ldapAgentName                 | uid=nextcloud,o=serviceBind,ou=users,dc=local,dc=loc                                                                                                                |
| ldapAgentPassword             | ***                                                                                                                                                                 |
| ldapAttributesForGroupSearch  |                                                                                                                                                                     |
| ldapAttributesForUserSearch   |                                                                                                                                                                     |
| ldapBackupHost                |                                                                                                                                                                     |
| ldapBackupPort                |                                                                                                                                                                     |
| ldapBase                      | dc=local,dc=loc                                                                                                                                                     |
| ldapBaseGroups                | ou=groups,dc=local,dc=loc                                                                                                                                           |
| ldapBaseUsers                 | o=user,ou=users,dc=local,dc=loc                                                                                                                                     |
| ldapCacheTTL                  | 600                                                                                                                                                                 |
| ldapConfigurationActive       | 1                                                                                                                                                                   |
| ldapDefaultPPolicyDN          |                                                                                                                                                                     |
| ldapDynamicGroupMemberURL     |                                                                                                                                                                     |
| ldapEmailAttribute            |                                                                                                                                                                     |
| ldapExperiencedAdmin          | 0                                                                                                                                                                   |
| ldapExpertUUIDGroupAttr       |                                                                                                                                                                     |
| ldapExpertUUIDUserAttr        |                                                                                                                                                                     |
| ldapExpertUsernameAttr        | uid                                                                                                                                                                 |
| ldapExtStorageHomeAttribute   |                                                                                                                                                                     |
| ldapGidNumber                 | gidNumber                                                                                                                                                           |
| ldapGroupDisplayName          | cn                                                                                                                                                                  |
| ldapGroupFilter               |                                                                                                                                                                     |
| ldapGroupFilterGroups         |                                                                                                                                                                     |
| ldapGroupFilterMode           | 0                                                                                                                                                                   |
| ldapGroupFilterObjectclass    |                                                                                                                                                                     |
| ldapGroupMemberAssocAttr      | member                                                                                                                                                              |
| ldapHost                      | ldaps://IP-ADRESSE                                                                                                                                                 |
| ldapIgnoreNamingRules         |                                                                                                                                                                     |
| ldapLoginFilter               | (&(&(|(objectclass=inetOrgPerson))(|(memberof=cn=familyshare,ou=groups,dc=local,dc=loc)(memberof=uid=nextcloud,o=serviceBind,ou=users,dc=local,dc=loc)))(uid=%uid)) |
| ldapLoginFilterAttributes     |                                                                                                                                                                     |
| ldapLoginFilterEmail          | 0                                                                                                                                                                   |
| ldapLoginFilterMode           | 0                                                                                                                                                                   |
| ldapLoginFilterUsername       | 1                                                                                                                                                                   |
| ldapMatchingRuleInChainState  | unknown                                                                                                                                                             |
| ldapNestedGroups              | 0                                                                                                                                                                   |
| ldapOverrideMainServer        |                                                                                                                                                                     |
| ldapPagingSize                | 500                                                                                                                                                                 |
| ldapPort                      | 636                                                                                                                                                                 |
| ldapQuotaAttribute            |                                                                                                                                                                     |
| ldapQuotaDefault              |                                                                                                                                                                     |
| ldapTLS                       | 0                                                                                                                                                                   |
| ldapUserAvatarRule            | default                                                                                                                                                             |
| ldapUserDisplayName           | cn                                                                                                                                                                  |
| ldapUserDisplayName2          |                                                                                                                                                                     |
| ldapUserFilter                | (&(|(objectclass=inetOrgPerson))(|(memberof=cn=familyshare,ou=groups,dc=local,dc=loc)(memberof=uid=nextcloud,o=serviceBind,ou=users,dc=local,dc=loc)))              |
| ldapUserFilterGroups          | familyshare;nextcloud                                                                                                                                               |
| ldapUserFilterMode            | 0                                                                                                                                                                   |
| ldapUserFilterObjectclass     | inetOrgPerson                                                                                                                                                       |
| ldapUuidGroupAttribute        | auto                                                                                                                                                                |
| ldapUuidUserAttribute         | auto                                                                                                                                                                |
| turnOffCertCheck              | 0                                                                                                                                                                   |
| turnOnPasswordChange          | 0                                                                                                                                                                   |
| useMemberOfToDetectMembership | 1                                                                                                                                                                   |
+-------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

Chrome 87

**Operating system:**

Ubuntu 20.04.1

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
cc @nextcloud/ldap
