### ISSUE TITLE
Broken external Storage cannot be removed

### ISSUE THREAD

**Issue by OleAlbers** [nextcloud/server#24705]
### Steps to reproduce
1. Create an external storage using an AddOn
2. Remove that App
3. Display the external storage overview

### Expected behaviour
An option to remove the external storage should be available

### Actual behaviour
No removal option is present

### Version
19.0.6

### Detailed description
The following describes what happened and what addon was involved as an example. But this is not about that AddOn or how to fix ist. It is just an example how to achieve the state:

I used the Pico CMS - Addon to add an external storage (which is actually local) to my NextCloud. After a while I uninstalled Pico CMS because it was broken (and I did not need it anymore)

Now the external Storage that uses that AddOn isn't working anymore. The "External mount error" is displayed when trying to access the storage content. This is the expected behaviour.

In the "External Storages" overview that storage is listed with an error icon and an error in the "External Storage" - Column. Which also is the expected behaviour. 

What is missing is the "..." - option to allow the administrator to remove a broken external storage from the configuriation. (which is available on working external storages)

![grafik](https://user-images.githubusercontent.com/4692497/102188150-3db1d780-3eb5-11eb-990f-d1837dd7f397.png)

IMHO this should be considered a bug and not a feature request

**Comment by szaimen** [comment]
Hi there, did you use the correct settings section under admin?
![image](https://user-images.githubusercontent.com/42591237/122569620-38436e80-d04b-11eb-8309-08578c66efbe.png)
