### ISSUE TITLE
Error during update

### ISSUE THREAD

**Issue by shameerariff** [nextcloud/server#24719]
When try updating the next cloud to 20.0.03 the following error occurs.
`Doctrine\DBAL\Schema\SchemaException: The column 'private_key' on table 'oc_authtoken' already exists.
Update failed`

The log from the browser is

```
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Doctrine\DBAL\Schema\SchemaException: The column 'private_key' on table 'oc_authtoken' already exists.


```
The log activity during the process as shown below

```
sudo -u www-data php occ upgrade

Nextcloud or one of the apps require upgrade - only a limited number of commands are available

You may use your browser or the occ upgrade command to do the upgrade

Setting log level to debug

Updating database schema

Doctrine\DBAL\Schema\SchemaException: The column 'private_key' on table 'oc_authtoken' already exists.

Update failed

Maintenance mode is kept active

Resetting log level
```

Is this a bug or a fault in my server?

**Comment by kesselb** [comment]
I assume that's an issue with your setup. For some reason https://github.com/nextcloud/server/blob/905e1918d2796b9a79025283cd6edf2c40f49d77/core/Migrations/Version14000Date20180518120534.php is executed again. This migration was already released with Nextcloud 14. I doubt one is able to reproduce this problem without more information.

**Comment by shameerariff** [comment]
Hi @kesselb, You are almost correct because the setup no the server was interrupted and restarted. It was due to MYSQL(Maria DB) 4byte size issue. I am stuck in the middle of the process. Most possibly you may require DB schema. Let me know your exact requirement to share with you.

**Comment by kesselb** [comment]
> Let me know your exact requirement to share with you.

1. Issue Template: https://github.com/nextcloud/server/blob/master/.github/ISSUE_TEMPLATE/Bug_report.md 
2. A description how to move a Nextcloud setup into this state to reproduce it locally
