### ISSUE TITLE
Nextcloud 21 Module php-imagick in this instance has no SVG support

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#24710]
Module php-imagick in this instance has no SVG support. For better compatibility it is recommended to install it.

the php-imaqick is already install on my server. 

Ubuntu 20.0.4 LTS
Apache 2
php-imagick is already the newest version (3.4.4-4).

**Comment by axheli** [comment]
sudo apt install  libmagickcore-6.q16-3-extra fixed the issue.

**Comment by dR3b** [comment]
Please add `libmagickcore-6.q16-6-extra` to the Docker image!

**Comment by andyxheli** [comment]
I'm not using docker

**Comment by dR3b** [comment]
But I use Docker and have this error! 😃

**Comment by meonkeys** [comment]
> But I use Docker and have this error! smiley

Same here. I think https://github.com/nextcloud/docker/issues/1414 is the one to track for Docker users.
