### ISSUE TITLE
implement on-the-fly transcoding to stream more types of videos

### ISSUE THREAD

**Issue by meonkeys** [nextcloud/server#24712]
It would be awesome if Nextcloud could stream more types of video files. I have many videos that stream just fine from my Nextcloud server to desktop or mobile clients, and many videos that will play locally with VLC but will not stream.

The ideal solution would be transparent, automatic, and storage/memory/compute efficient transcoding with ffmpeg or something already present. I suppose it would be nice to have options to tweak it to use more or less storage, memory or compute.

I didn't see any existing issues about this.

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature. (or thumbs down if you are against it)
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

Workarounds/alternatives:

* Use another server to stream the videos Nextcloud can't stream, such as Jellyfin
* Transcode videos outside of Nextcloud to some format known to be able to stream easily to desktop & mobile clients
* Transcode using the "Video Converter" Nextcloud app

Related: https://github.com/nextcloud/server/issues/5218#issuecomment-745163715

Here's a screenshot trying to stream a video that plays fine locally with VLC. It's a "MPEG-1/2 Video (mpgv)" with audio "A52 Audio (aka AC3) (a52 )".

![Screenshot from 2020-12-15 09-22-30](https://user-images.githubusercontent.com/50639/102250158-0d1f6d00-3eb8-11eb-8e35-ba1f6d3a52be.png)

**Comment by kesselb** [comment]
Closing as per https://github.com/nextcloud/server/issues/5218#issuecomment-499872323. 

If you open a video in Nextcloud the file is streamed to your browser. If the browser supports the video and audio codec it plays.

https://github.com/nextcloud/workflow_script is an app to call external tools (like ffmpeg). It might be possible to convert all movie files automatially to a format supported by most browser. Or format your files locally. There are plenty of good tools available to do that.

**Comment by meonkeys** [comment]
Sounds good, thank you @kesselb for the response, the link to that comment (sorry I missed that) and the idea to check out nextcloud/workflow_script!

**Comment by cwilby** [comment]
I am currently building this out as a third-party package as I wasn't able to configure a solution I liked using workflows/cron triggered shell scripts.

Here's what I have so far:

![image](https://user-images.githubusercontent.com/13686317/121471130-0c055f00-c974-11eb-83c7-956c593ab328.png)

https://github.com/cwilby/nextcloud-automated-media-encoder
