### ISSUE TITLE
When updating app in the apps mgmt, notices don’t hide

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2472]
When you click the »Update to 1.0.22« button on an app in the apps management, the notices about app updates don’t hide:

- Text »This app has an update available.« directly above the button
- showNotification up top: »You have 2 app updates pending«
- Notification »Update for Spreed video calls to version 1.0.22 is available«

All of these should vanish the moment the app is properly updated and the button also hides. cc @nickvergessen @nextcloud/javascript

**Comment by nickvergessen** [comment]
The notification of the Notification app will vanish on the next poll. Currently there is no public JS API to vanish one manually or cause a retrigger. Will have some thoughts on this.

**Comment by jancborchardt** [comment]
Ok, but the other two things definitely need to vanish directly, and at least the text element directly above should be linked to it.
