### ISSUE TITLE
Talk cannot be activated after updating to Nexcloud 21.0.0 beta

### ISSUE THREAD

**Issue by copiis** [nextcloud/server#24722]
Have a v-server with PHP 7.4, four cores 16 GB RAM, Ubuntu 18, MariaDB After updating to Nextcloud 21.0.0 beta, Talk could no longer be activated. I found this error message.

`{"reqId":"fGn58943omZfB6G8B0st","level":3,"time":"2020-12-16T03:26:55+00:00","remoteAddr":"37.201.194.210","user":"Skyadmin","app":"index","method":"POST","url":"/index.php/settings/apps/enable","message":{"Exception":"Exception","Message":"Argument 2 passed to OC\\Comments\\Manager::__construct() must implement interface Psr\\Log\\LoggerInterface, instance of OC\\AppFramework\\Logger given, called in /apps/spreed/lib/Chat/CommentsManager.php on line 46","Code":0,"Trace": /lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"}, /lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"}, /lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"}, /index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":" /lib/private/AppFramework/Http/Dispatcher.php","Line":159,"Previous":{"Exception":"TypeError","Message":"Argument 2 passed to OC\\Comments\\Manager::__construct() must implement interface Psr\\Log\\LoggerInterface, instance of OC\\AppFramework\\Logger given, called in /apps/spreed/lib/Chat/CommentsManager.php on line 46","Code":0,"Trace": /apps/spreed/lib/Chat/CommentsManager.php","line":46,"function":"__construct","class":"OC\\Comments\\Manager","type":"->"},{"function":"__construct","class":"OCA\\Talk\\Chat\\CommentsManager","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"newInstanceArgs","class":"ReflectionClass","type":"->"}, e/lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, e/lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]}, e/lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/DependencyInjection/DIContainer.php","line":431,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":87,"function":"query","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"},{"function":"OC\\AppFramework\\Utility\\{closure}","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->","args":["*** sensitive parameters replaced ***"]}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":101,"function":"array_map"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":109,"function":"buildClass","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/Utility/SimpleContainer.php","line":126,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/AppFramework/DependencyInjection/DIContainer.php","line":459,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"}, /lib/private/ServerContainer.php","line":146,"function":"queryNoFallback","class":"OC\\AppFramework\\DependencyInjection\\DIContainer","type":"->"}, /lib/private/Repair.php","line":127,"function":"query","class":"OC\\ServerContainer","type":"->"}, /lib/private/legacy/OC_App.php","line":1047,"function":"addStep","class":"OC\\Repair","type":"->"}, /lib/private/Installer.php","line":164,"function":"executeRepairSteps","class":"OC_App","type":"::"}, /apps/settings/lib/Controller/AppSettingsController.php","line":448,"function":"installApp","class":"OC\\Installer","type":"->"}, /lib/private/AppFramework/Http/Dispatcher.php","line":218,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"}, /lib/private/AppFramework/Http/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"}, /lib/private/AppFramework/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"}, /lib/private/Route/Router.php","line":301,"function":"main","class":"OC\\AppFramework\\App","type":"::"}, /lib/base.php","line":1008,"function":"match","class":"OC\\Route\\Router","type":"->"}, /index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":" /lib/private/Comments/Manager.php","Line":77},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Linux; Android 10; ONEPLUS A6013) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.107 Mobile Safari/537.36","version":"21.0.0.8","id":"5fd98fb9463c5"}`

**Comment by kesselb** [comment]
Hello @nextcloud/talk

**Comment by nickvergessen** [comment]
There is currently no compatible release.
