### ISSUE TITLE
After deleting profile picture, delete button should vanish

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2473]
After deleting the profile picture:
![capture du 2016-12-02 14-19-08](https://cloud.githubusercontent.com/assets/925062/20835348/5d1f4440-b89a-11e6-96e3-d154e223b668.png)
That button should vanish again, cc @icewind1991

**Comment by schiessle** [comment]
... and if you upload a profile picture for the first time the delete button should directly appear, not only after page reload. 😉
