### ISSUE TITLE
Problem with update

### ISSUE THREAD

**Issue by Matze1116** [nextcloud/server#24736]
Whats front with my update ?
___________________________________________
Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by Vinceg76** [comment]
Hello, same problem here, 

when I look up for similar problems I only find answers like this : 

[mysqld]

innodb_large_prefix=on
innodb_file_format=Barracuda
innodb_file_per_table=1

but mysql is already configured that way, any ideas ?

Regards

**Comment by shameerariff** [comment]
The same here, Totally confused :-<

**Comment by acsfer** [comment]
Check if all your tables are InnoDB: https://github.com/nextcloud/server/issues/17975#issuecomment-575337500
If not: https://www.ryadel.com/en/mysql-convert-all-tables-of-one-or-more-databases-to-myisam-or-innodb/

**Comment by Vinceg76** [comment]
Hello,
Mysql was set up correctly, but the tables where still Il antelope format, In the client, I set the file type to Barracuda and the innodb_large_prefix to 1 and it worked.
