### ISSUE TITLE
WebDav

### ISSUE THREAD

**Issue by jmruas** [nextcloud/server#24733]
Hi,

I can't use WebDav with FairNote app.
I get this error message:

[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Could not open file at <<closure>>

0. /home/m3jmr/public_html/ncl/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
   OCA\DAV\Connector\Sabre\File->get()
1. /home/m3jmr/public_html/ncl/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
2. /home/m3jmr/public_html/ncl/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
3. /home/m3jmr/public_html/ncl/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
4. /home/m3jmr/public_html/ncl/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
5. /home/m3jmr/public_html/ncl/apps/dav/appinfo/v1/webdav.php line 82
   Sabre\DAV\Server->exec()
6. /home/m3jmr/public_html/ncl/remote.php line 167
   require_once("/home/m3jmr/pub ... p")

GET /ncl/remote.php/webdav/fairnote/20200524_143313_fairnote_7d4.db?downloadStartSecret=nvhk43noyvl
from 84.91.158.63 by jmruas at 2020-11-04T17:04:04+00:00

Is this problem in your side?

Thank you.
JMRuas

**Comment by szaimen** [comment]
I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
Thank you!
