### ISSUE TITLE
Can't run OCC commands via CLI (getScriptName() must be of the type string)

### ISSUE THREAD

**Issue by toxpal** [nextcloud/server#24735]
I have exactly the same issue with all my installations of NC for years, but I was able to use OCCWeb app to run OCC commands via web interface of NC, so I didn't care much. Now, when OCCWeb is abandoned, I have lots of problems with my NC installations because I need to run OCC commands, but they always fail with the same error:

Command:
`sudo -u someuser php /path/to/nc/occ ANY_COMMAND_HERE`

Error:
```
Content-type: text/html; charset=UTF-8
An unhandled exception has been thrown:
TypeError: Return value of OC\AppFramework\Http\Request::getScriptName() must be of the type string, null returned in /path/to/nc/lib/private/AppFramework/Http/Request.php:837
Stack trace:
#0 /path/to/nc/lib/base.php(163): OC\AppFramework\Http\Request->getScriptName()
#1 /path/to/nc/lib/base.php(576): OC::initPaths()
#2 /path/to/nc/lib/base.php(1091): OC::init()
#3 /path/to/nc/console.php(49): require_once('/path/to...')
#4 /path/to/nc/occ(11): require_once('/path/to...')
#5 {main}
```

I run cPanel (have full access to server), and latest versions of Apache 2.4 + PHP 7.4, but had the same issue for years (which means older versions of Apache, PHP and NC itself). Right now, I'm running copies of NC 19.0.6 and NC 20.0.4 if that matters.

P.S. In the past, I had a very similar issue with cronjobs on cPanel servers, which was fixed later (https://github.com/nextcloud/server/issues/13038). But OCC still doesn't work for me (tested on 2 different cPanel servers).

**Comment by kesselb** [comment]
Added "needs info" because the issue template is missing. For such a "weird" issue we need as much information as possible. Just posting the error message does not help.

> Content-type: text/html; charset=UTF-8

I suspect you are using a wrong php binary to run occ. Please share `php -v`.

```
PHP 7.4.13 (cli) (built: Nov 28 2020 06:25:16) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
    with Xdebug v3.0.1, Copyright (c) 2002-2020, by Derick Rethans
```

The important information is **(cli)**. If your php binary reports something different that's the issue.

**Comment by toxpal** [comment]
Thank you, that was indeed the issue. After I launched "**/usr/bin/php**" instead of just "**php**", it started working. Strange, because it works with other PHP-based scripts.

Anyways, thank you again for super-fast response. Hope someone else will also find it useful.
