### ISSUE TITLE
Shared calendar not showing in Evolution

### ISSUE THREAD

**Issue by meaz** [nextcloud/server#24747]
Someone shared a calendar with me. I see it from webclient and from my andorid thanks to davx5. I have added my account into gnome account online, but this shared calendar doesn't appear in the list of available calendars in Gnome calendar. I have tried to add it as an external calendar in Gnome calendar, using the provided link in the webclient, so something like : http://cloud.server.com:443/remote.php/dav/calendars/meaz/calname_shared_by_user/
It asks my credential and then the name "calname" appears in the list of available calendars, but no events appear.
Any idea? Is that a bug Nextcloud side?

**Comment by j-ed** [comment]
This is the Nextcloud issue tracker of the developers only and not the [Nextcloud help forum](https://help.nextcloud.com/). Please address all configuration problems in that forum.
