### ISSUE TITLE
Upgrade PHP-opencloud to support Swift DLO

### ISSUE THREAD

**Issue by hanserasmus** [nextcloud/server#2474]
### Steps to reproduce
1. Install new version of Nextcloud
2. Connect to functioning Openstack Swift Cluster
3. Try to upload a file larger than 5Gig.

### Expected behaviour
Nextcloud should upload the file with success, as it would a 10MB file for example.

### Actual behaviour
Nextcloud gives an error stating it was unable to upload the file.

### Server configuration
**Operating system**:
CentOS 7.2
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
10
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
From tar ball from Nextcloud site.

**Are you using external storage, if yes which one:** local/smb/sftp/...
Yes: Openstack Swift v2 API
**Are you using encryption:** yes/no
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
LDAP

The current version of PHP-opencloud is 1.9. The newest release of php-Opencloud is 1.14, and this version supporst DLO.  If Nextcloud could get this version in it's core, all possibility is there that DLO will be supported.

**Comment by MorrisJobke** [comment]
@icewind1991 Didn't you already prepared something to upgrade php-opencloud?

**Comment by MorrisJobke** [comment]
Was done with #4410 and also backported to 12.0.4
