### ISSUE TITLE
NC20 dont save previous versions of txt and md file.

### ISSUE THREAD

**Issue by vgdh** [nextcloud/server#24745]
### Steps to reproduce
1. Create new text document 
2. Make changes in this txt or md 
3. You dont will see any versions of file.

### Expected behaviour
i want see all previous versions of this file

### Actual behaviour
 You dont will see any versions of file.

### Server configuration

**Operating system:** ubuntu 18 Docker, image - 20.0.3-apache

**Database:** mysql:latest

**Nextcloud version:** 20.0.3

**Comment by SimplyCorbett** [comment]
Works for me on 20.0.4

**Comment by vgdh** [comment]
For unknown for me reason it's wasn't work when i try it yesterday, but now it works perfectly.
close
