### ISSUE TITLE
TBsync don't work with tutorial

### ISSUE THREAD

**Issue by PrzemekSkw** [nextcloud/server#24753]
I try to do everything with that tutorial [https://docs.nextcloud.com/server/19/user_manual/pim/sync_thunderbird.html](url) 
_

> In the account manager choose “Add account / CalDAV / CardDAV account“
> In the next window, go with the default called Automatic configuration and click next
> Enter an an account name, which you can freely choose, user name, password and the URL of your server and click next

_

and when I  choose new account name, new user and password it dont work:
```
URL:
https://mojserver.ddns.net/nextcloud/.well-known/caldav (PROPFIND)

Request:
<d:propfind xmlns:d="DAV:"><d:prop><d:current-user-principal /></d:prop></d:propfind>

Response:
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
         "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
 <head>
  <title>403 Forbidden</title>
 </head>
 <body>
  <h1>403 Forbidden</h1>
 </body>
</html>
```
Do I have to make application and generate new password in my Nextcloud?

Regards,
Przemek

**Comment by kesselb** [comment]
Hi,

please head over to https://help.nextcloud.com for support.
