### ISSUE TITLE
Proposal: Non-wipe&rebuild-all or re-install approach to oc_filecache cleanup

### ISSUE THREAD

**Issue by someone-somenet-org** [nextcloud/server#24754]
The `oc_filecache` table seems to always be the biggest table on instances I run and/or I have seen their databases, containing entries for long gone and not returning files.

It seems that there is no cleaup of old entries except for `occ files:cleanup` which, [unlike what some people think](https://help.nextcloud.com/t/occ-files-cleanup-does-it-delete-the-db-table-entries-of-the-missing-files/20253), does **not** check the file-system for existing files and it seems this command is only of interest when deleting users or migrating storages - so imho almost never.

Especially there doesnt seem to be any way to automatically purge entries of files that are long gone from the filesystem.

The only way to reduce the table size seems to be to basically wipe everything and rescan all, at which point it might make sense to fully wipe the instance and set up a new one, as you lose the file sharing configuration anyway and some other tables also never remove old garbage (calendar & contacts sync for example) and when you start meddling with things you can just go for the fully nuclear option.
You can keep some tables - so for example user accounts ... I just recently reinstalled because of #22482 so this is obviously a possible way, yet totally undesirable.

### Proposal and notes
The Proposal is: Add a way to automatically scan small batches of the oc_filecache table for removed files and slowly cleanup `od_filecache` with short cronjobs.

I propose a 2-pass expirity system with 2 different grace periods to 
1) not put much burden on the server while slowly cleaning files that no longer exist and are not coming back, incrementally, with a cronjob 
2) not to remove file entries that were just missing at the moment of the scan (for example due to not mounted data directory, network outage). 

I am not really an expert on NC-source code, but I expect `mtime` and `storage_mtime` to be timestamps at which a file was definitely present in the file-system and where NC successfully modified these files.

### Details
+ add a new column `expire_time DEFAULT 0` - once this timestamp is past us, delete the row from the db.
+ add a new column `last_seen_time DEFAULT NOW()` - timestamp where we have last seen a file in the file-system.
  + this is to prevent putting unnecessary load on the server.
  + Setting default to now() solves the problem of initially rolling out this change while giving every file the benefit of doubt to exist.

+ add a cronjob that runs like once a every hour.
  + iterate over: `select from oc_filecache where expire_time != 0`
      + try accessing these files on the file-system.
      + if successful, set `oc_filecache.last_seen_time = NOW()` and set `oc_filecache.expire_time = 0`
      + else if: `expire_time < NOW()`: remove entry from db.
      + else: do nothing.

  + iterate over: `select from oc_filecache where expire_time = 0 and last_seen_time < (NOW() - INTERVAL '1 month') and mtime < (NOW() - INTERVAL '1 month') and storage_mtime < (NOW() - INTERVAL '1 month') LIMIT 5000`
    + If we do not know that this file existed the last month and modify timestamps are also older than a month, consider to check this file in the file-system.
    + select up to 5000 (or so/configurable?) file entries to not burden the server too much.
  + try accessing them in the file-system.
  + if successful, set `oc_filecache.last_seen_time = NOW()`
  + else set `oc_filecache.expire_time = (NOW() + INTERVAL '2 week')`
     + Mark this file entry to be removed after another grace period of 2 weeks - this is to prevent the deletion of file entries that were inaccessible during the scan due to temp. issues like mount-points failing to mount.

### Considerations
https://help.nextcloud.com/t/occ-files-cleanup-does-it-delete-the-db-table-entries-of-the-missing-files/20253 notes that only local and home storages should be scanned because of temp. network issues. 
I think I solved the issue here by the second pass grace period as local file-systems can have the same problems as remote, for example when something goes wrong with mounting.

If there are many not-changing files on the server a `limit 5000` may not be enough to scan fast enough thru all files, leading to delayed cleanup. Therefore it might make sense to make the limit dynamic or configurable.OTOH: even a delayed cleanup is better than no cleanup.

**Comment by kesselb** [comment]
files:scan --all remove files from filecache which are no longer present on the hard disk.

**Comment by someone-somenet-org** [comment]
> files:scan --all remove files from filecache which are no longer present on the hard disk.

Unfortunately it takes forever on bigger instances and is therefore not really a solution as its missing the automatic, backgroundy self-healing part.

But what I seem to have missed: When deleting files they seem to get deleted from oc_filecache immediately in at least NC 20.0.4, which is better than my proposal.

**Comment by bill-mcgonigle** [comment]
> files:scan --all remove files from filecache which are no longer present on the hard disk.

n.b. for others debugging this, as of 23.0.4.1:

```
$ php occ files:scan --all 
...
+---------+-------+--------------+
| Folders | Files | Elapsed time |
+---------+-------+--------------+
| 1179    | 3618  | 00:00:37     |
+---------+-------+--------------+
```

```
MariaDB [nextcloud]> select count(path) from oc_filecache;
+-------------+
| count(path) |
+-------------+
|     1346983 |
+-------------+
```
So the desired table cleanup isn't happening.
