### ISSUE TITLE
Add an option to delete forever subscription notifications

### ISSUE THREAD

**Issue by ogarcia** [nextcloud/server#24752]
**Is your feature request related to a problem? Please describe.**
I have installed a NextCloud instance for a small number of users but connected to a large LDAP. It is warning me about _Your server has not a enterprise subscription_, everytime and is annoying.

**Describe the solution you'd like**
Add an option to disable these notifications forever in config file. I understand that Nextcloud is an application that should earn money, but killing the user with notifications will not get new subscriptions.

**Comment by kesselb** [comment]
> killing the user with notifications

How often do you see this notification?

cc @MorrisJobke

**Comment by j-ed** [comment]
> It is warning me about Your server has not a enterprise subscription, everytime and is annoying.

Please make sure that you've disabled the **Support app** which usually generates such a message if an enterprise subscription is missing 😉

**Comment by ogarcia** [comment]
> How often do you see this notification?

With the last stable version (20.0.4) is continuously. I dismiss it and it appears again and again :cry:

**Comment by ogarcia** [comment]
> Please make sure that you've disabled the **Support app** which usually generates such a message if an enterprise subscription is missing

I do the change and seems that the notification stopped :1st_place_medal:
