### ISSUE TITLE
Drop-down menus in sidebar scroll with file listing

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#24766]
Tested with Nextcloud 20.0.2.

Steps to reproduce:

1. Go to a folder which has more files than what fits on one page.
2. Open the sidebar and for example create a public link and open the "..." menu:

![image](https://user-images.githubusercontent.com/1589737/102617164-04899980-4139-11eb-9ec1-32aeab61bf1b.png)

3. Now use the mouse wheel to scroll down the file listing

Expected behavior: No changes in the sidebar

Actual behavior:  The drop-down menu on the sidebar scrolls up:

![image](https://user-images.githubusercontent.com/1589737/102617290-3dc20980-4139-11eb-96c7-159fd8027e2b.png)

**Comment by skjnldsv** [comment]
Duplicate, can't find the other ticket
