### ISSUE TITLE
Show the editor name(s) in file versioning

### ISSUE THREAD

**Issue by TQxTim** [nextcloud/server#24769]
As of now file versioning does not show the name of the editor(s) for each version.

I would like to request a feature which shows the editor for uploaded files and all editors for files edited via onlyoffice (collaboration feature) in the version control tab.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
