### ISSUE TITLE
Icon in unshare dropdown broken

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2477]
A recent change broke the icon+text layout of the »Unshare« action in the right sidebar:
![capture du 2016-12-02 14-45-37](https://cloud.githubusercontent.com/assets/925062/20836517/016c3d5a-b8a0-11e6-96dd-1a72d35d394d.png)

**Comment by jancborchardt** [comment]
cc @nextcloud/designers

**Comment by schiessle** [comment]
I can't reproduce this on master (tested with firefox and chromium)

**Comment by MorrisJobke** [comment]
Works for me in german and english:

![bildschirmfoto 2016-12-02 um 15 51 59](https://cloud.githubusercontent.com/assets/245432/20838099/58c85a28-b8a7-11e6-8bcc-ec03409eb041.png)
![bildschirmfoto 2016-12-02 um 15 52 15](https://cloud.githubusercontent.com/assets/245432/20838100/58c8915a-b8a7-11e6-8cbc-8ab1bbce3a4d.png)

**Comment by skjnldsv** [comment]
I can reproduce!
![capture d ecran_2016-12-02_17-06-47](https://cloud.githubusercontent.com/assets/14975046/20840795/ba989ca4-b8b1-11e6-8318-cd872236fcb4.png)

The span used can't have a width/height defined as it's not a block element. We should use display: inline-block or change it to a div :)

**Comment by skjnldsv** [comment]
2d91831b5092c9d04a20cbe55a31cc41cec10fbe broke it!

**Comment by skjnldsv** [comment]
Working on it

**Comment by skjnldsv** [comment]
Fix in #2483

**Comment by jancborchardt** [comment]
@skjnldsv thanks a lot! :) Weird that this commit broke it because that was the one we introduced it with and also tested it :?

**Comment by skjnldsv** [comment]
@jancborchardt since the span isn't displayed as block, the only thing that showed the icon background was the padding. Removing the padding resulted in an empty element of width 0! :)
