### ISSUE TITLE
Caledar elements in db missing/corrupt?

### ISSUE THREAD

**Issue by morbificagent** [nextcloud/server#24784]
Hi together,

have installed the calendar app yesterday on an nextcloud installation which is there for 2 years now and which was updated from 18 to 19 to 20 in the past.
eventualy the calendar app was installed in the past.

But something seems to be problematic with the calendar part of the database.
if i try to enter an entry in the calendar i get this message and it doesnt work.
Has someone an idea how to repair this part of the db?

like i said no calendars are used at the Moment...
many thanks!

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO `oc_calendarobjects` (`calendarid`, `uri`, `calendardata`, `lastmodified`, `etag`, `size`, `componenttype`, `firstoccurence`, `lastoccurence`, `classification`, `uid`, `calendartype`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params ["9", "DA7F5590-4638-4D54-8C72-964E5416B099.ics", "BEGIN:VCALENDAR\r\nPRODID:-\/\/IDN nextcloud.com\/\/Calendar app 2.1.2\/\/EN\r\nCALSCALE:GREGORIAN\r\nVERSION:2.0\r\nBEGIN:VEVENT\r\nCREATED:20201220T075728Z\r\nDTSTAMP:20201220T075738Z\r\nLAST-MODIFIED:20201220T075738Z\r\nSEQUENCE:2\r\nUID:a90a19e5-bf34-447d-bed0-08f04e9ff0b7\r\nDTSTART;TZID=Europe\/Berlin:20201220T090028\r\nDTEND;TZID=Europe\/Berlin:20201220T100028\r\nSUMMARY:test\r\nEND:VEVENT\r\nBEGIN:VTIMEZONE\r\nTZID:Europe\/Berlin\r\nBEGIN:DAYLIGHT\r\nTZOFFSETFROM:+0100\r\nTZOFFSETTO:+0200\r\nTZNAME:CEST\r\nDTSTART:19700329T020000\r\nRRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU\r\nEND:DAYLIGHT\r\nBEGIN:STANDARD\r\nTZOFFSETFROM:+0200\r\nTZOFFSETTO:+0100\r\nTZNAME:CET\r\nDTSTART:19701025T030000\r\nRRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU\r\nEND:STANDARD\r\nEND:VTIMEZONE\r\nEND:VCALENDAR", 1608451035, "7f8982f88caa4f707f459606a89f01f2", 724, "VEVENT", 1608451228, 1608454828, 0, "a90a19e5-bf34-447d-bed0-08f04e9ff0b7", 0]: SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: 'BEGIN:VCALENDAR PRODID:-//IDN nextcloud.com//Calendar app 2.1.2//EN CALSCALE:GREGORIAN VERSION:2.0 BEGIN:VEVENT CREATED:...' for column `nextcloud_db`.`oc_calendarobjects`.`calendardata` at row 1

**Comment by j-ed** [comment]
I've extracted the listed VCalendar record and checked it using several iCal validators on the internet but didn't get any errors displayed. @skjnldsv Do you have an idea what's going wrong here?
```
BEGIN:VCALENDAR
PRODID:-//IDN nextcloud.com//Calendar app 2.1.2//EN
CALSCALE:GREGORIAN
VERSION:2.0
BEGIN:VEVENT
CREATED:20201220T075728Z
DTSTAMP:20201220T075738Z
LAST-MODIFIED:20201220T075738Z
SEQUENCE:2
UID:a90a19e5-bf34-447d-bed0-08f04e9ff0b7
DTSTART;TZID=Europe/Berlin:20201220T090028
DTEND;TZID=Europe/Berlin:20201220T100028
SUMMARY:test
END:VEVENT
BEGIN:VTIMEZONE
TZID:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;BYMONTH=3;BYDAY=-1SU
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;BYMONTH=10;BYDAY=-1SU
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
```

**Comment by morbificagent** [comment]
Have found this:

https://help.nextcloud.com/t/nextcloud-talk-broken-after-upgrade-to-20-0-0-mysql-invalid-datetime-format-1366-incorrect-string-value/95228/15

They used this for adressing a problem like mine i think:

    set your mariadb mysql.cnf
    from
    init-connect='SET NAMES utf8'
    to
    init-connect='SET NAMES utf8mb'

But i havent 'SET NAMES utf8' in my mysql config and setting 'SET NAMES utf8mb' doesnt resolve the problem.

But eventually it can show the right way?
Any Ideas?

**Comment by morbificagent** [comment]
OK, found it... lookks like calendardata shouldnt be int ;-)
How could that happened.....

Has anyone the oc_calendarobjects from nextcloud 20 and can post them?

**Comment by j-ed** [comment]
```
]> describe oc_calendarobjects;
+----------------+---------------------+------+-----+---------+----------------+
| Field          | Type                | Null | Key | Default | Extra          |
+----------------+---------------------+------+-----+---------+----------------+
| id             | bigint(20) unsigned | NO   | PRI | NULL    | auto_increment |
| calendardata   | longblob            | YES  |     | NULL    |                |
| uri            | varchar(255)        | YES  |     | NULL    |                |
| calendarid     | bigint(20) unsigned | NO   | MUL | NULL    |                |
| lastmodified   | int(10) unsigned    | YES  |     | NULL    |                |
| etag           | varchar(32)         | YES  |     | NULL    |                |
| size           | bigint(20) unsigned | NO   |     | NULL    |                |
| componenttype  | varchar(8)          | YES  |     | NULL    |                |
| firstoccurence | bigint(20) unsigned | YES  |     | NULL    |                |
| lastoccurence  | bigint(20) unsigned | YES  |     | NULL    |                |
| uid            | varchar(255)        | YES  |     | NULL    |                |
| classification | int(11)             | YES  |     | 0       |                |
| calendartype   | int(11)             | NO   |     | 0       |                |
+----------------+---------------------+------+-----+---------+----------------+
13 rows in set (0.00 sec)
```

**Comment by morbificagent** [comment]
@j-ed Thanks, now its working 👍 

I whish nice christmas days
