### ISSUE TITLE
remote.php does not handle // correctly

### ISSUE THREAD

**Issue by PhilippMundhenk** [nextcloud/server#24781]
First of all: Great software! Only recently started using it but loving it already!

When using reverse proxy and accidentally configuring it to redirect to `http://xyz.com/` instead of `http://xyz.com`, Nextcloud will at first look work without any issues. However, files are not shown. This is due to remote.php seemingly having issues with being called as //remote.php instead of /remote.php. A PROPFIND on loading the files view returns with HTTP 500, so does a manual GET to //remote.php, while /remote.php works fine.

Technically, one could argue that this is a configuration mistake of the user/admin, especially since it is already documented in the forums (https://help.nextcloud.com/t/reverse-proxy-and-data-directory/24603). However, if this is the only place causing trouble, which seems to be the case, since everything else seems to be working fine, it might be worth adding an extra check in remote.php

**Comment by kesselb** [comment]
Closing as configuration issue. It's the expected behaviour that the router does not resolve `//remote.php` to `/remote.php`.
