### ISSUE TITLE
Sharing contacts

### ISSUE THREAD

**Issue by Eric-Sparks** [nextcloud/server#24788]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It would be nice to be able to share contacts like one does with files.

**Describe the solution you'd like**
Add a share function to each contact or group with changes tracked.

**Describe alternatives you've considered**
Now I have to share contacts manually; changes not being tracked.

**Comment by simonspa** [comment]
There are a few related tickets in the "Contacts" component of Nextcloud already:

* Full addressbook: https://github.com/nextcloud/contacts/issues/1718
* Share with circles: https://github.com/nextcloud/contacts/issues/1299
* Share single contact: https://github.com/nextcloud/contacts/issues/111
