### ISSUE TITLE
Apps can't be installed

### ISSUE THREAD

**Issue by PhilippMundhenk** [nextcloud/server#24782]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install any large app

### Expected behaviour
App should install

### Actual behaviour
Install fails with timeout ( e.g.: cURL error 28: Operation timed out after 120000 milliseconds with 2123345 out of 2690108 bytes received (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) )

With increased timeout in Client.php everything works fine, until the app is too large again, as reported on forums, e.g.: https://help.nextcloud.com/t/solved-nc-18-0-1-default-timeout-limit-for-app-download-still-too-tight-override-is-being-ignored/70985

Might make sense to start counting timeout only when download is hanging and no more data is coming through.

### Server configuration
latest nextcloud docker image

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/18103
