### ISSUE TITLE
Dashboard does not start with IE 11

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24797]
### Steps

1. Checkout server master (97f2de0262601b579b0768863ce664df51eed639)
2. Grab the IE 11 Win8.1 VM from modern.ie
3. Login with IE 11

### Expected result

Dashboard page loads.

### Actual result

Only the title bar loads but not the contents.

As I understood, apps should at least load with IE 11 with NC 21.

**Comment by PVince81** [comment]
it is possible to manually switch to the files app by entering its URL. the files app works fine with IE 11.
then possible to switch to other apps that work.

**Comment by szaimen** [comment]
https://github.com/nextcloud/server/issues/20855 ?

**Comment by PVince81** [comment]
after checking the errors in the log I saw they are caused by the talk app https://github.com/nextcloud/spreed/issues/4820.
closing in favor of that ticket
