### ISSUE TITLE
User sharing rules affects also NC Admin since NC 20

### ISSUE THREAD

**Issue by sirdrakeistda** [nextcloud/server#24801]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. chose sharing rules (e.g. only allowed to share to user in the same group)
2. Try to share a file or folder as admin violating these rules
3.

### Expected behaviour
I expected an admin is allowed to share to every person on the server (it worked like this until NC19) and I expected the sharing config affects only non admin user.

I'm not sure if it's a real bug or a feature ;-). The change came unexpected for me.

### Actual behaviour
There is no option search and share with a user as admin, if the rule is violated.

### Server configuration

**Operating system:** Raspbian

**Web server:** apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** 19.0.6

**Where did you install Nextcloud from:** NCP

**Comment by kesselb** [comment]
cc @rullzer @nickvergessen

**Comment by skjnldsv** [comment]
> I expected an admin is allowed to share to every person on the server (it worked like this until NC19) and I expected the sharing config affects only non admin user.
> 
> I'm not sure if it's a real bug or a feature ;-). The change came unexpected for me.

Hey! We indeed changed a lot and enforced quite a lot of rules now
The admin is not exempt from those rules are they are security/privacy rules for most parts.

We will continue to simplify and make sure those rules are are transparent as possible for all users, including admins :)
