### ISSUE TITLE
Contacts menu, more intuitive link to contact details

### ISSUE THREAD

**Issue by th23x** [nextcloud/server#24807]
Would suggest to make the contact name the link to the detailed contact page, instead the additional "i" which then would be obsolete. Which would give room to link multiple mail addresses directly and/or link first mail address + first phone number in quick search.

Thanks for considering :-)

![quick-search-details-link](https://user-images.githubusercontent.com/13735303/102722575-3dc13580-4302-11eb-8a30-c98db4d6805e.jpg)

**Comment by krishna0303** [comment]
I would like to work on this issue

**Comment by szaimen** [comment]
> I would like to work on this issue

Then feel free to go ahead 👍 :)

**Comment by xbrutus254** [comment]
Hi, is that issue still open?

**Comment by szaimen** [comment]
> Hi, is that issue still open?

Yes

**Comment by devsekar-1992** [comment]
I fixed this issue. but i can't push my branch and shows permission to nextcloud/server.git
