### ISSUE TITLE
Can't change LDAP display name field 

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#24809]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Open LDAP Advanced Settings
2. Try to change displayname field

### Expected behaviour

You should be able to change the displayname field.

### Actual behaviour

Can't change the display name field as the input is flickering. This also seems to apply to some other fields. 

https://user-images.githubusercontent.com/878997/102882223-5cccde00-444e-11eb-895c-d8e121311714.mp4

### Server configuration

**Operating system:** Debian 10

**Web server:** Apache 2

**Database:** SQLite

**PHP version:** 7.3.19

**Nextcloud version:** 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Web

### Client configuration
**Browser:** Chrome 86

**Operating system:** ChromeOS

#### Browser log
<details>
<summary>Browser log</summary>

Ton of the following:

```
$ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
```

</details>

**Comment by szaimen** [comment]
cc @nextcloud/ldap I suppose this is still valid?
