### ISSUE TITLE
CSS issue (I think) in Sharing

### ISSUE THREAD

**Issue by STaRDoGG** [nextcloud/server#24804]
Using NC version 20.04 Stable in Docker

When going to share a folder there's an overlap (at #3 in the screenshot). Also  where you type in the name there's a bright white underline that looks like it's not meant to look that way in a dark theme.

![image](https://user-images.githubusercontent.com/1524526/102838019-c56e7900-43c2-11eb-8548-87b160b5f95f.png)

**Comment by simonspa** [comment]
Cannot confirm here with NC 20.0.4 / Firefox 84:

![image](https://user-images.githubusercontent.com/1677436/104592691-e26b3480-566e-11eb-9163-fe282ff1a566.png)

![image](https://user-images.githubusercontent.com/1677436/104592773-029af380-566f-11eb-9637-16804e70dd8c.png)

Did you make sure to drop your browser cache after switching theme? (ctrl+f5)

**Comment by STaRDoGG** [comment]
@simonspa Just checking in; I'll test it once the pc with NC is back up again (right now the PC is down until I fix it) but it's not likely a cache issue, as I frequently do ctrl+f5 during development (probably a dozen times a day or so) and I've had NC set to the dark theme since I installed it a long time ago.

Also, I forgot to mention it in my OP but I got that on the latest Chrome; I'll give it a try in FF as well once the PC is back up.

**Comment by STaRDoGG** [comment]
@simonspa Just tried it in Firefox on one machine:

![image](https://user-images.githubusercontent.com/1524526/104848563-2b0f3180-58ab-11eb-83b5-f122d0b895a1.png)

and in Chrome (latest) on a different machine that wasn't the machine used in the first Chrome screenshot):

![image](https://user-images.githubusercontent.com/1524526/104848582-4bd78700-58ab-11eb-9804-cbd2055e14ab.png)

and I'm still getting it. Here's the version of NC:

![image](https://user-images.githubusercontent.com/1524526/104848610-7295bd80-58ab-11eb-9c85-08c41087362d.png)

Here's my list of Apps (both enabled and disabled):

```
occ $ app:list

Enabled: 
- accessibility: 1.6.0 
- activity: 2.13.4 
- admin_audit: 1.10.0 
- analytics: 3.2.0 
- audioplayer_editor: 0.3.0 
- bruteforcesettings: 2.0.1 
- cloud_federation_api: 1.3.0 
- comments: 1.10.0 
- contacts: 3.4.3 
- contactsinteraction: 1.1.0 
- dav: 1.16.2 
- documentserver_community: 0.1.8 
- duplicatefinder: 0.0.4 
- federatedfilesharing: 1.10.2 
- federation: 1.10.1 
- files: 1.15.0 
- files_external: 1.11.1 
- files_external_dropbox: 1.4.3 
- files_external_gdrive: 0.4.0 
- files_fulltextsearch: 20.0.0 
- files_mindmap: 0.0.24 
- files_pdfviewer: 2.0.1 
- files_rightclick: 0.17.0 
- files_sharing: 1.12.2 
- files_trashbin: 1.10.1 
- files_versions: 1.13.0 
- files_videoplayer: 1.9.0 
- fulltextsearch: 20.0.0 
- fulltextsearch_elasticsearch: 20.0.0 
- groupfolders: 8.2.0 
- logreader: 2.5.0 
- lookup_server_connector: 1.8.0 
- metadata: 0.12.0 
- nextcloud_announcements: 1.9.0 
- notifications: 2.8.0 
- oauth2: 1.8.0 
- occweb: 0.0.7 
- ocr: 6.0.58 
- onlyoffice: 6.2.0 
- openhab: 0.9.4 
- password_policy: 1.10.1 
- phonetrack: 0.6.5 
- photos: 1.2.3 
- previewgenerator: 3.1.0 
- privacy: 1.4.0 
- provisioning_api: 1.10.0 
- ransomware_protection: 1.8.0 
- recommendations: 0.8.0 
- serverinfo: 1.10.0  
- settings: 1.2.0  
- sharebymail: 1.10.0  
- socialsharing_email: 2.1.0  
- support: 1.3.0  
- survey_client: 1.8.0  
- systemtags: 1.10.0  
- text: 3.1.0  
- theming: 1.11.0  
- twofactor_backupcodes: 1.9.0  
- twofactor_totp: 5.0.0  
- updatenotification: 1.10.0  
- viewer: 1.4.0  
- weather_status: 1.0.0  
- workflowengine: 2.2.0

Disabled: 
- dashboard 
- encryption 
- firstrunwizard 
- user_ldap 
- user_status
```

**Comment by STaRDoGG** [comment]
Stale perhaps; fixed? Nein.

**Comment by szaimen** [comment]
Hm... works for me on 20.0.8.
Maybe try to update to that version?
