### ISSUE TITLE
Search files by multiple words

### ISSUE THREAD

**Issue by k-ooshiro** [nextcloud/server#24803]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

----

**Is your feature request related to a problem? Please describe.**

It would be great to be able to search for files with multiple words in the search bar.
If large numbers of files are kept, the current search with partial matches may hit thousands of files. 
If it can be filtered by multiple words, we can find files more easily.

The community has a similar request.
https://help.nextcloud.com/t/file-name-search-using-multiple-words/94479

Thanks in advance.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/24169
