### ISSUE TITLE
'Add to my Nextcloud' arrow greyed out for .txt / .md public link

### ISSUE THREAD

**Issue by michielbdejong** [nextcloud/server#24808]
Sorry if this is a duplicate, I didn't know exactly what terms to search for.
Compare:
<img width="745" alt="Screenshot 2020-12-22 at 11 16 36" src="https://user-images.githubusercontent.com/408412/102877592-4a02db00-4447-11eb-91ea-21659d624b66.png">
I can click the arrow next to 'alice@nc1.pdsinterop.net'.
To:
<img width="766" alt="Screenshot 2020-12-22 at 11 18 42" src="https://user-images.githubusercontent.com/408412/102877721-7dde0080-4447-11eb-8df8-813d45fe3606.png">
The arrow next to 'alice@nc1.pdsinterop.net' is greyed out.

I've tried this in quite a few combinations but my conclusion is that the arrow stays greyed out if the file is a text/markdown document (.txt or .md).

**Comment by szaimen** [comment]
I could reproduce this on c.nc.c with `22.0.0 beta 5`

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by michielbdejong** [comment]
Confirmed fixed in latest master (at least for .txt files)
