### ISSUE TITLE
Nextcloud install Error while trying to initialise the database

### ISSUE THREAD

**Issue by vipera7** [nextcloud/server#24811]
### Steps to reproduce
1. Move the Nextcloud directory to the the web server, create data folder and adjust the right permission
2. Install Nextcloud version 17, 18 or 20 (not tested other version) using the command:

```
sudo -u apache php occ maintenance:install --database "mysql" --database-host MY_DB_HOST --database-name MY_DB_NAME  --database-user MY_DB_USER --database-pass MY_DB_PASS --admin-user ADMIN_NC --admin-pass ADMIN_PASS
```
**Output:**

```
Error while trying to initialise the database: An exception occurred while executing 'CREATE TABLE oc_migrations (app VARCHAR(255) NOT NULL, version VARCHAR(255) NOT NULL, PRIMARY KEY(app, version)) DEFAULT CHARACTER SET UTF8 COLLATE utf8_bin ENGINE = InnoDB':

SQLSTATE[HY000]: General error: 1005 Can't create table 'MY_DB_NAME.oc_migrations' (errno: -1)
 ->
```

### Expected behaviour
The installation should be successfull

### Actual behaviour
Failed to install and no table are created in the database

### Server configuration

**Operating system:**
CentOS 7

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7.2.34

**Nextcloud version:** (see Nextcloud admin page)
17,18,20

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
From the official repo of sourceforge

**Comment by kesselb** [comment]
> General error: 1005 Can't create table 'MY_DB_NAME.oc_migrations' (errno: -1)

I don't see a bug here. Your sql server responds with some error message. Try to figure out why and installation will work. The CI installs Nextcloud on MySQL, MariaDB and Postgres multiple times a day.
