### ISSUE TITLE
An unhandled exception has been thrown: OCP\AppFramework\QueryException: Could not resolve OCA\Settings\AppInfo\Application!

### ISSUE THREAD

**Issue by JochenMehlich** [nextcloud/server#24818]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
 - No Idea - 

### Expected behaviour
I updated from 19.0.4.2 to 19.0.6.2. I wanted a normal update

### Actual behaviour
Nextcloud Error / Class not found

### Server configuration

**Operating system:**
Debian Buster
**Web server:**
Apache 2.4.38

**Database:**
Mariadb 10.3.27

**PHP version:**
php 7.4

**Nextcloud version:** (see Nextcloud admin page)
19.0.6.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
19.0.4.2

**Where did you install Nextcloud from:**
setup-nextcloud.php (Webinstaller)

```
Server Error
```
</details>

**List of activated apps:**
Contacts
Talk
Calendar
occweb
documents
twofactor 
onlyoffice
tasks
<summary>App list</summary>

```
Error
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '#####',
  'passwordsalt' => '#####',
  'secret' => '#####',
  'trusted_domains' => 
  array (
    0 => '#####',
    1 => '#####',
  ),
  'datadirectory' => '/var/www/cloud/data',
  'dbtype' => 'mysql',
  'version' => '19.0.6.2',
  'overwrite.cli.url' => '####',
  'dbname' => '####',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => '####',
  'dbpassword' => '####',
  'installed' => true,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
  'filesystem_check_changes' => 1,
  'app_install_overwrite' => 
  array (
    0 => 'occweb',
    1 => 'twofactor_rcdevsopenotp',
    2 => 'twofactor_yubikey',
    3 => 'documents',
    4 => 'twofactor_email',
  ),
  'mail_from_address' => 'noreply',
  'mail_smtpmode' => 'smtp',
  'mail_sendmailmode' => 'smtp',
  'mail_domain' => '####',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '####',
  'mail_smtpname' => '#####',
  'mail_smtppassword' => '####',
  'mail:smtptimeout' => 30,
  'maintenance' => true,
  'config_is_read_only' => false,
  'theme' => '',
  'loglevel' => 3,
  'mysql.utf8mb4' => true,
  'mail_smtpport' => '25',
  'mail_smtpdebug' => false,
  'updater.release.channel' => 'stable',
  'mail_smtpsecure' => 'tls',
  'updater.secret' => '####',
);

```

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
 MySQL returned an empty result set (i.e. zero rows). (Query took 0.0010 seconds.)
```
</details>

### Client configuration
**Browser:**
Brave
**Operating system:**
Ubuntu
#### Web server error log
<details>
<summary>Web server error log</summary>

```
No Error
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
"reqId":"###","level":3,"time":"2020-12-22T16:35:42+00:00","remoteAddr":"###","user":"--","app":"remote","method":"GET","url":"/status.php","message":{"Exception":"OCP\\AppFramework\\QueryException","Message":"Could not resolve OCA\\Settings\\AppInfo\\Application! Class OCA\\Settings\\AppInfo\\Application does not exist","Code":0,"Trace":[{"file":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","line":116,"function":"resolve","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/private/ServerContainer.php","line":149,"function":"query","class":"OC\\AppFramework\\Utility\\SimpleContainer","type":"->"},{"file":"/var/www/cloud/lib/base.php","line":737,"function":"query","class":"OC\\ServerContainer","type":"->"},{"file":"/var/www/cloud/lib/base.php","line":1093,"function":"init","class":"OC","type":"::"},{"file":"/var/www/cloud/status.php","line":37,"args":["/var/www/cloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/cloud/lib/private/AppFramework/Utility/SimpleContainer.php","Line":107,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows) mirall/3.0.3stable-Win64 (build 20201125) (Nextcloud)","version":"19.0.6.2"}
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
No Error
```
</details>

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Without steps to reproduce there is not much we can do. Maybe https://help.nextcloud.com/ has some ideas how to recover from such a state.

**Comment by JochenMehlich** [comment]
Okay,

i tried already to migrate the static folders (lib, core, etc.) but everytime it comes with the same error. When i setup a new cloud on the same server it has no error.

**Comment by JochenMehlich** [comment]
Fixed. I went back to an backup for all files (except the data directory) and rerun the update without crash.
