### ISSUE TITLE
Missing columns after OC 10.5 -> NC 21.0.0beta2 upgrade

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24813]
## Steps to reproduce
1. Upgrade from OC 10.5.0 to NC 21.0.0beta2 by replacing the source code and keeping config and data
2. Run `occ upgrade` => no errors
3. Run `db:convert-filecache-bigint`

### Expected behaviour
Success

### Actual behaviour
Error about missing columns "oc_share_external.parent"

## Expected from NC 21.0.0beta2
```
MariaDB [nextcloud_beta]> describe oc_share_external;
+-----------------+---------------+------+-----+---------+----------------+
| Field           | Type          | Null | Key | Default | Extra          |
+-----------------+---------------+------+-----+---------+----------------+
| id              | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| parent          | bigint(20)    | YES  |     | -1      |                |
| share_type      | int(11)       | YES  |     | NULL    |                |
| remote          | varchar(512)  | NO   |     | NULL    |                |
| remote_id       | varchar(255)  | YES  |     |         |                |
| share_token     | varchar(64)   | NO   |     | NULL    |                |
| password        | varchar(64)   | YES  |     | NULL    |                |
| name            | varchar(64)   | NO   |     | NULL    |                |
| owner           | varchar(64)   | NO   |     | NULL    |                |
| user            | varchar(64)   | NO   | MUL | NULL    |                |
| mountpoint      | varchar(4000) | NO   |     | NULL    |                |
| mountpoint_hash | varchar(32)   | NO   |     | NULL    |                |
| accepted        | int(11)       | NO   |     | 0       |                |
+-----------------+---------------+------+-----+---------+----------------+
```

## Actual
```
MariaDB [owncloud]> describe oc_share_external;
+-----------------+---------------------+------+-----+---------+----------------+
| Field           | Type                | Null | Key | Default | Extra          |
+-----------------+---------------------+------+-----+---------+----------------+
| id              | bigint(20)          | NO   | PRI | NULL    | auto_increment |
| remote          | varchar(512)        | NO   |     | NULL    |                |
| share_token     | varchar(64)         | NO   |     | NULL    |                |
| password        | varchar(64)         | YES  |     | NULL    |                |
| name            | varchar(64)         | NO   |     | NULL    |                |
| owner           | varchar(64)         | NO   |     | NULL    |                |
| user            | varchar(64)         | NO   | MUL | NULL    |                |
| mountpoint      | varchar(4000)       | NO   |     | NULL    |                |
| mountpoint_hash | varchar(32)         | NO   |     | NULL    |                |
| remote_id       | varchar(255)        | NO   |     | -1      |                |
| accepted        | int(11)             | NO   |     | 0       |                |
| lastscan        | bigint(20) unsigned | YES  |     | NULL    |                |
+-----------------+---------------------+------+-----+---------+----------------+
```

=> need to:
- add "parent" column
- remove "lastscan" column
- [x] PR for share_external here: https://github.com/nextcloud/server/pull/24829

@juliushaertl not sure how these were missed, maybe some of the migrations did not run

**Comment by PVince81** [comment]
- [ ] systemtag.assignable column not properly deleted: https://github.com/nextcloud/server/pull/23044/files#r547282236

**Comment by PVince81** [comment]
- [ ] oc_comments.reference_id is missing
- [ ] oc_comments_read_markers index differences
- [ ] oc_dav_properties not deleted?

**Comment by PVince81** [comment]
- [ ] oc_federated_reshares:
   - remote_id default is different
   - index is not primary key

is:
```
CREATE TABLE `oc_federated_reshares` (
  `share_id` bigint(20) NOT NULL,
  `remote_id` varchar(255) COLLATE utf8mb4_bin NOT NULL COMMENT 'share ID at the remote server',
  UNIQUE KEY `share_id_index` (`share_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;
```

should be:
```
CREATE TABLE `oc_federated_reshares` (
  `share_id` bigint(20) NOT NULL,
  `remote_id` varchar(255) COLLATE utf8mb4_bin DEFAULT '',
  PRIMARY KEY (`share_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;
```

**Comment by nickvergessen** [comment]
> oc_comments.reference_id is missing

That's an optional column which can be added with an occ command

**Comment by PVince81** [comment]
- [ ] oc_filecache missing mtime and size keys

**Comment by PVince81** [comment]
- [ ] oc_notifications, missing icon column: but this is because I had the notifications app disabled for many many versions and now when enabling the NC notifications app, the column did not get added. Not sure if / how we want to support such cases...

**Comment by PVince81** [comment]
- [ ] should we delete oc_privatedata ?

- [ ] oc_properties differences in field length and defaults:

is:
```
CREATE TABLE `oc_properties` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `userid` varchar(64) COLLATE utf8mb4_bin DEFAULT '',
  `propertyname` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `propertyvalue` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  `propertypath` varchar(255) COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;
```

should be:
```
CREATE TABLE `oc_properties` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `userid` varchar(64) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `propertypath` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `propertyname` varchar(255) COLLATE utf8mb4_bin NOT NULL DEFAULT '',
  `propertyvalue` longtext COLLATE utf8mb4_bin NOT NULL,
  PRIMARY KEY (`id`),
  KEY `property_index` (`userid`),
  KEY `properties_path_index` (`userid`,`propertypath`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin ROW_FORMAT=COMPRESSED;
```

**Comment by PVince81** [comment]
I could not run the index occ yet due to the bigint one blocking, so maybe some of the index discrepancies will be solved there.

**Comment by PVince81** [comment]
I have a local solution for the first bits (share_external and assignable)

**Comment by PVince81** [comment]
dropping assignable is more tricky as it will require adjusting the indices, so I abandoned that one for now and focussed on share_external.

**Comment by PVince81** [comment]
after patching my server with https://github.com/nextcloud/server/pull/24829 the occ commands all ran fine!

additionally to the list from https://github.com/nextcloud/server/pull/23044#issue-492972923 the setup checks told me to run "occ db:add-missing-primary-keys" which worked as well.

**Comment by PVince81** [comment]
I redid a diff and went through the items on top, most of the index differences were solved by the occ command.

Here a few more I found:
- [ ] oc_activity.app length different (was known before, probably still pending)
- [ ] oc_activity indices are different:
ist:
```
  PRIMARY KEY (`activity_id`),
  KEY `activity_user_time` (`affecteduser`,`timestamp`),
  KEY `activity_filter_by` (`affecteduser`,`user`,`timestamp`),
  KEY `activity_filter_app` (`affecteduser`,`app`,`timestamp`),
  KEY `activity_object` (`object_type`,`object_id`)
```
soll:
```
  PRIMARY KEY (`activity_id`),
  KEY `activity_user_time` (`affecteduser`,`timestamp`),
  KEY `activity_filter_by` (`affecteduser`,`user`,`timestamp`),
  KEY `activity_filter` (`affecteduser`,`type`,`app`,`timestamp`),
  KEY `activity_object` (`object_type`,`object_id`)
```

**Comment by nickvergessen** [comment]
> oc_systemtag.assignable column not properly deleted

https://github.com/nextcloud/server/pull/25001**

**Comment by PVince81** [comment]
#25001 likely broke the upgrade.

we need to adjust the key before deleting the column:

Here's the diff:
OC:
```
  UNIQUE KEY `tag_ident` (`name`,`visibility`,`editable`,`assignable`)
```

NC:
```
  UNIQUE KEY `tag_ident` (`name`,`visibility`,`editable`)
```

So we need to delete the "tag_ident" key and then recreate it without the "assignable" column.
And only then we can delete the column.

**Comment by PVince81** [comment]
Should the key be adjusted directly as part of the migration or be part of the occ command ? The latter would be tricky as we'd need to delete the column afterwards in a subsequent update/migration.

**Comment by PVince81** [comment]
Also unclear: what to do if the "assignable" had a value ? Some tags might become duplicate so we need to make sure that there is no error when "merging" the tags during an upgrade. Tricky stuff :-/

**Comment by PVince81** [comment]
I've pushed a PR for updating tag_ident before removing the column: https://github.com/nextcloud/server/pull/25068

**Comment by PVince81** [comment]
I grepped for "assignable" and saw that we do have code that works with it, so might need to delete that as well: https://github.com/nextcloud/server/blob/master/apps/systemtags/lib/Activity/Provider.php#L333

In any case, it seems the "assignable" column needs further careful consideration and handling.

For now to avoid blocking NC 20, this PR removes assignable column removal during upgrade, for now. We can handle it in a later minor release: https://github.com/nextcloud/server/pull/25069

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by PVince81** [comment]
@szaimen this isn't really an issue / bug per se, but a diff of the DB schema from OC to NC to help migration

so far I haven't heard of any critical issues there due to missing indices or so in the past years, so the ticket itself is not critical

we can either convert to "tech debt" or close
