### ISSUE TITLE
Log is full of "OCP\Encryption\Exceptions\GenericEncryptionException: Bad Signature"

### ISSUE THREAD

**Issue by warren-ru** [nextcloud/server#24817]
### Steps to reproduce
1. Enable server side encryption module (Default encryption module)
2. Enable S3 primary storage
3. Set [Yandex Object Storage](https://cloud.yandex.com/services/storage) as a S3 provider

### Actual behaviour
Files are accessible, but there a lot of messages in the log:

Error | no app in context | OCP\Encryption\Exceptions\GenericEncryptionException: Bad Signature

Error | no app in context | Couldn't re-calculate unencrypted size for files/График смен 2.0.xlsx

### Server configuration

**Operating system:**
Ubuntu 18.04.5 LTS
**Web server:**
nginx/1.14.0
**Database:**
MariaDB 10.4.17
**PHP version:**
PHP 7.4.13
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.4
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh
**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-20.0.4.tar.bz2

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - encryption: 2.8.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.7.2
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - richdocuments: 3.7.11
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.4
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - contacts
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "REMOVED SENSITIVE VALUE"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "defaultapp": "files",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "overwrite.cli.url": "REMOVED SENSITIVE VALUE",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "objectstore": {
            "class": "\\OC\\Files\\ObjectStore\\S3",
            "arguments": {
                "bucket": "REMOVED SENSITIVE VALUE",
                "key": "***REMOVED SENSITIVE VALUE***",
                "secret": "***REMOVED SENSITIVE VALUE***",
                "hostname": "storage.yandexcloud.net",
                "port": 443,
                "use_ssl": true,
                "region": "ru-central1",
                "use_path_style": true
            }
        },
        "maintenance": false,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "mysql.utf8mb4": true,
        "skeletondirectory": "",
        "data-fingerprint": "ab84cd3d8735f163e489bdf685b1245f"
    }
}
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** yes

**Are you using an external user-backend, if yes which one:** no

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

I'm not aware of a solution. Closing your report in favour of https://github.com/nextcloud/server/issues/22077.
