### ISSUE TITLE
NC 21.0.0beta2 missing initial card index

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#24814]
### Steps

1. Setup NC 21.0.0beta2 from tarball
2. Go to admin settings
3. Run system checks in the overview section

### Expected result
No DB related errors

### Actual result
Missing index:
<img width="677" alt="image" src="https://user-images.githubusercontent.com/277525/102894944-25692c00-4464-11eb-9efd-1ceec5aebf0a.png">

We should add it right away when setting up from scratch.

### Version
NC 21.0.0beta2 from tarball

@juliushaertl @rullzer

**Comment by PVince81** [comment]
not critical as there is a workaround, but still not nice

**Comment by juliushaertl** [comment]
Was fixed with 3d66d68327e299264579bbc29e012df884e3e012
