### ISSUE TITLE
Docker "stable" Version tagging

### ISSUE THREAD

**Issue by tilllt** [nextcloud/server#24828]
Apparently NC 20 has been given the stable tag on the non Docker Version. Since i keep running the "stable" docker version, it wants to update. On the docker registry, "stable" is still considered to be 19.0.4 ... i guess for coherency  it would be a great idea if "stable" means the same thing on all channels, so apparently 20.0.4 and not 19.0.4

**Comment by kesselb** [comment]
https://github.com/nextcloud/docker/issues is the repository for the docker image. The image is maintained by the community. They might pick a different way to tag releases. Closing the report as unrelated to nextcloud/server.

**Comment by tilllt** [comment]
https://github.com/nextcloud/docker/issues/1343
