### ISSUE TITLE
Files tag rule makes files:scan fail (and automatic deletion fails too)

### ISSUE THREAD

**Issue by GuiGuiSoft** [nextcloud/server#24822]
### Steps to reproduce
1. As a normal user create a folder `Titi` and a `toto.md` file in your workspace
2. As an administrator define those tagging rules (in order to tag every file/folder except some identified folders)
![tags](https://user-images.githubusercontent.com/8069239/102922359-362e9780-448e-11eb-9218-b9de6410db9e.png)
3. As an administrator, run a `files:scan` on the previous user account

### Expected behaviour
No error in log

### Actual behaviour
![error](https://user-images.githubusercontent.com/8069239/102922506-6c6c1700-448e-11eb-845d-06b5faa2fc95.png)

### Server configuration

**Operating system:** Ubuntu 18.04 LTS

**Web server:** Apache 2.4

**Database:** MySQL 8

**PHP version:** 7.3

**Nextcloud version:** 19.0.4 (also tested on 18.0.7)

**Where did you install Nextcloud from:** sources

As suggested [here](https://help.nextcloud.com/t/files-tag-rule-makes-files-scan-fail-and-automatic-deletion-fails-too/101944) I don't fill all the details of my installation by I can if needed.

Regards.

**Comment by kesselb** [comment]
cc @blizzz @juliushaertl

**Comment by juliushaertl** [comment]
We probably should just disable request based checks on cli execution.

**Comment by GuiGuiSoft** [comment]
Hello,

Just a "curious question".

If request based checks on cli execution are disabled, will it fix the automatic deletion pb I have ?
i.e. is the automatic deletion executed via CLI (when the cron is launched with CLI too) ?

Regards.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
