### ISSUE TITLE
Getting Rid of http-equiv "X-UA-Compatible" tags

### ISSUE THREAD

**Issue by ACAVJW4H** [nextcloud/server#24841]
**Is your feature request related to a problem? Please describe.**
When I search the codebase I see the http-equiv tag is only used for IE compatibility, which is phasing out. Going through the meta requires to interpret the beginning of the HTML page, which is slower than going through the HTTP headers in terms of performance

**Describe the solution you'd like**
Deploying a server already requires full access to server configuration so if there is still a need to provide this functionality we can do this in nginx or apache as defining the meta <meta http-equiv="content-type"/> is the same as sending the HTTP Content-Type header.

**Describe alternatives you've considered**
Either omit the X-UA-Compatible tags or move it to the webserver

**Comment by kesselb** [comment]
Thank you for reporting :+1: 

> omit the X-UA-Compatible tags

I added a note to: https://github.com/nextcloud/server/issues/20855#issuecomment-751255907


> Deploying a server already requires full access to server configuration

That's not correct.
