### ISSUE TITLE
Error message instead of playing video with special characters in file name only(!) with shared links for folders

### ISSUE THREAD

**Issue by maidstein** [nextcloud/server#24848]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a new folder
2. Upload / copy / move a mp4 file to this folder.
3. Change file name by giving a special chracter like '+' or '&' or whatever.
4. Create a shared link for this folder. With or without password doesn't matter. Do not create a shared link for the mp4 file directly because this works.
5. Open the shared link in a new browser tab.
6. Try to play the mp4 file inside your browser. Do not download the mp4 file because this works.

### Expected behaviour
A window should open and playing video / mp4 file.

### Actual behaviour
A window opens and shows a message: "Fehler beim Laden von [file name]" (Maybe: "Error while loading [file name]")

This error message only occurs if you call up video / mp4 file inside a folder which is shared by a link!  

### Server configuration

**Operating system: Linux 4.15.0-128-generic x86_64

**Web server:**

**Database: MySQL 5.7.28

**PHP version: 7.4.10

**Nextcloud version: 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install: 17, 18, 19

**Where did you install Nextcloud from: All-Inkl.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '************',
  'passwordsalt' => '******************************',
  'secret' => '************************************************',
  'trusted_domains' => 
  array (
    0 => '********.**',
    1 => 'www.********.**',
  ),
  'datadirectory' => '/www/htdocs/w0152ded/bibliothek/data',
  'dbtype' => 'mysql',
  'version' => '20.0.4.0',
  'overwrite.cli.url' => 'http://********.**/bibliothek',
  'dbname' => '********',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'ffYaX_',
  'mysql.utf8mb4' => true,
  'dbuser' => '********',
  'dbpassword' => '********',
  'installed' => true,
  'tempdirectory' => '/www/htdocs/********.**/bibliothek/tmp/',
  'mail_smtpmode' => 'sendmail',
  'mail_sendmailmode' => 'pipe',
  'mail_from_address' => 'mn',
  'mail_domain' => '********.**',
  'maintenance' => false,
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'theme' => '',
  'loglevel' => 2,
  'updater.secret' => '*********************************************************************',
);

```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** probably no

### Client configuration
**Browser: probably doesn't matter

**Operating system: probably doesn't matter

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Please contact if you really need more information!
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Please contact if you really need more information!
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Please contact if you really need more information!
```
</details>

**Comment by luzrain** [comment]
I have the same problem.

More info about this issue. If I open the console and looking at network activity, I see that the request and a name of the file in that is not url encoded:
`http://localhost/s/12345678/download?path=/&files=test file & with special symbol.mp4=`
Therefore special symbol, `&` in this case, breaks the link and give 404 error, instead of file.
If I url encode file name by hand:
`http://localhost/s/12345678/download?path=%2F&files=test%20file%20%26%20with%20special%20symbol.mp4`
This link is works.

**Comment by szaimen** [comment]
I think this was fixed in NC21.0.2
