### ISSUE TITLE
update from 19.0.6 to 20.0.4 failed

### ISSUE THREAD

**Issue by in3mug** [nextcloud/server#24842]
Hello, i am a newbie,
trying to update there was an error message, telling me to inform the Nextcloud community.
Thank you very much. Kind regards.
![update-nextcloud-failed](https://user-images.githubusercontent.com/76586255/103133233-9baaa000-46a9-11eb-9205-a21eaf06f8ed.png)

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
