### ISSUE TITLE
Open debug prompt and report an error

### ISSUE THREAD

**Issue by 849159061** [nextcloud/server#24851]
Open debug, the file page prompts to report an error，look:
filelist.js:386 Uncaught TypeError: Cannot read property 'on' of null
    at FileList.initialize (filelist.js:386)
    at new FileList (filelist.js:32)
    at Object.initialize (app.js:82)
    at app.js:363
    at delay.js:7
why?What should we do?

 'version' => '21.0.0.10',

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
