### ISSUE TITLE
SMB folder on REFS can not be used in external storage

### ISSUE THREAD

**Issue by ldwnt** [nextcloud/server#24859]
### Steps to reproduce
1. input SMB folder on REFS in external storage

### Expected behaviour
SMB folder added

### Actual behaviour
Red exclamation mark appears on this REFS one, while other SMB folders on NTFS can be added successfully.

### Server configuration

**Operating system:** ubuntu 20.04

**Web server:** apache 2.4.41

**Database:** MariaDB 10.3.25

**PHP version:** php 7.4

**Nextcloud version:** 20.0.3

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
