### ISSUE TITLE
Nextcloud - Too many redirections

### ISSUE THREAD

**Issue by HeyWatchOutDude** [nextcloud/server#24868]
Hi,

I have checked my nextcloud with "ssllabs" somehow im getting a redirect LOOP.
I think its a bug because my apache2 configuration is correct.

https://imgur.com/a/1AEL2tD

My configuration:
Nextcloud: 20.0.4
OS: Ubuntu 20.04 LTS (64Bit)
Hardware: RaspberryPi 4 (8GB)
Apache2: 2.4.46 (no reverse proxy)

My apache2 configuration:
(etc/apache2/sites-enabled/nextcloud.conf) 
```
<VirtualHost *:80>
  ServerName HOSTNAME.DOMAIN.COM
  Redirect permanent / https://HOSTNAME.DOMAIN.COM/
</VirtualHost>

<VirtualHost *:443>
  ServerAdmin ADMIN@DOMAIN.COM
  DocumentRoot /var/www/nextcloud/
  ServerName HOSTNAME.DOMAIN.COM

  Alias /nextcloud "/var/www/nextcloud/"
  
  <Directory "/var/www/nextcloud/">
    Options +FollowSymlinks
    AllowOverride All

    <IfModule mod_headers.c>
       Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
    </IfModule>

    <IfModule mod_dav.c>
       Dav off
    </IfModule>

    SetEnv HOME /var/www/nextcloud
    SetEnv HTTP_HOME /var/www/nextcloud
  </Directory>

ErrorLog ${APACHE_LOG_DIR}/error.log
CustomLog ${APACHE_LOG_DIR}/access.log combined

Include /etc/letsencrypt/options-ssl-apache.conf
SSLCertificateFile /etc/letsencrypt/live/HOSTNAME.DOMAIN.COM/fullchain.pem
SSLCertificateKeyFile /etc/letsencrypt/live/HOSTNAME.DOMAIN.COM/privkey.pem
</VirtualHost>
```

access.log:
(var/log/apache2/access.log)
```
64.41.200.108 - - [28/Dec/2020:14:05:51 +0000] "GET / HTTP/1.1" 302 4768 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
64.41.200.108 - - [28/Dec/2020:14:05:52 +0000] "GET /index.php/login HTTP/1.1" 302 4611 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
64.41.200.108 - - [28/Dec/2020:14:05:53 +0000] "GET /index.php/login HTTP/1.1" 302 4615 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
64.41.200.108 - - [28/Dec/2020:14:05:54 +0000] "GET /index.php/login HTTP/1.1" 302 4621 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
64.41.200.108 - - [28/Dec/2020:14:05:55 +0000] "GET /index.php/login HTTP/1.1" 302 4621 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
64.41.200.108 - - [28/Dec/2020:14:05:56 +0000] "GET /index.php/login HTTP/1.1" 302 4629 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"
64.41.200.108 - - [28/Dec/2020:14:05:59 +0000] "GET /?SSL_Labs_Renegotiation_Test=User_Agent_May_Not_Show HTTP/1.0" 400 3131 "-" "-"

```

Note: I don't have a redirect in the .htaccess file. (Default configuration)

If something is missing let me know please.

**Comment by skjnldsv** [comment]
Hey!

Does that happens for all users? Or for some once in a while?
Please also share your config.php (obfuscated)

**Comment by HeyWatchOutDude** [comment]
> Hey!
> 
> 
> 
> Does that happens for all users? Or for some once in a while?
> 
> Please also share your config.php (obfuscated)

Hi,

when I clear the cache of the browser the redirect takes kinda long. Sometimes I wait like 8-15 seconds until the login gets displayed.

Here is my config.php file:

```
<?php
$CONFIG = array (
  'instanceid' => 'PRIVATE',
  'passwordsalt' => 'PRIVATE',
  'secret' => 'PRIVATE',
  'trusted_domains' =>
  array (
    0 => 'HOSTNAME.DOMAIN.COM',
    1 => 'IP',
  ),
  'datadirectory' => '/media/cloud/nextcloud',
  'overwrite.cli.url' => 'https://HOSTNAME.DOMAIN.COM/',
  'htaccess.RewriteBase' => '/',
  'dbtype' => 'mysql',
  'version' => '20.0.4.0',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'PRIVATE',
  'dbpassword' => 'PRIVATE',
  'installed' => true,
  'default_language' => 'de',
  'default_locale' => 'de_AT',
  'twofactor_enforced' => 'true',
  'twofactor_enforced_groups' =>
  array (
    0 => 'user',
    1 => 'admin',
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'redis' =>
  array (
    'host' => 'localhost',
    'port' => 6379,
  ),
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'ssl',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => 'PRIVATE',
  'mail_domain' => 'gmail.com',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => 'smtp.gmail.com',
  'mail_smtpport' => '465',
  'mail_smtpauth' => 1,
  'mail_smtpname' => 'PRIVATE',
  'mail_smtppassword' => 'PRIVATE',
  'preview_libreoffice_path' => '/usr/bin/libreoffice',
  'enable_previews' => true,
  'enabledPreviewProviders' =>
  array (
    0 => 'OC\\Preview\\TXT',
    1 => 'OC\\Preview\\MarkDown',
    2 => 'OC\\Preview\\OpenDocument',
    3 => 'OC\\Preview\\PDF',
    4 => 'OC\\Preview\\MSOffice2003',
    5 => 'OC\\Preview\\MSOfficeDoc',
    6 => 'OC\\Preview\\PDF',
    7 => 'OC\\Preview\\Image',
    8 => 'OC\\Preview\\Photoshop',
    9 => 'OC\\Preview\\TIFF',
    10 => 'OC\\Preview\\SVG',
    11 => 'OC\\Preview\\Font',
    12 => 'OC\\Preview\\MP3',
    13 => 'OC\\Preview\\Movie',
    14 => 'OC\\Preview\\MKV',
    15 => 'OC\\Preview\\MP4',
    16 => 'OC\\Preview\\AVI',
  ),
  'preview_max_x' => 480,
  'preview_max_y' => 858,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 2,
  'log_type' => 'file',
  'logtimezone' => 'Europe/Berlin',
  'logfile' => '/var/log/nextcloud_fail2ban.log',
  'syslog_tag' => 'Nextcloud',
);
```

**Comment by chrisfoster121** [comment]
I am having a similar issue I think. After a fresh install and setting up port forwarding (temporarily on 80) I get this:

![Capture](https://user-images.githubusercontent.com/36481654/103447621-a80b9b80-4c5b-11eb-986a-cdb19ac66fdd.PNG)


When I try to log into the android app it says "Malformed Server configuration". The only thing I have changed is the config.php file to include trusted domains:

![Capture](https://user-images.githubusercontent.com/36481654/103447688-98d91d80-4c5c-11eb-9445-82c8c08e0db7.PNG)

Is this an error on my end or is this a bug?

**Comment by HeyWatchOutDude** [comment]
Any update on this?

**Comment by skjnldsv** [comment]
Yes, you need to change your configs and make sure your webserver is using the same configs as in our docs.

If you have a redirect loop, it's either one of those configs that are incorrect.
Please try a curl and see what is it being redirected to. Then you'll find what the issue is:

```bash
15:58 [admin@workstation] ~% curl -I http://cloud.nextcloud.com
HTTP/1.1 301 Moved Permanently
Date: Mon, 04 Jan 2021 14:58:06 GMT
Server: Apache/2.4.41 (Ubuntu)
Location: https://cloud.nextcloud.com/
Content-Type: text/html; charset=iso-8859-1
```

**Comment by skjnldsv** [comment]
It's redirecting you again to `https://hostname.domain.com/index.php/login`. What does the curl says? 

PS: please do `curl -I ....` so we only have the headers, we don't need the content

**Comment by HeyWatchOutDude** [comment]
curl -i http://HOSTNAME.DOMAIN.COM OUTPUT:
``
HTTP/1.1 301 Moved Permanently
Date: Mon, 04 Jan 2021 15:13:16 GMT
Server: Apache/2.4.46 (Ubuntu)
Location: https://HOSTNAME.DOMAIN.COM/
Content-Length: 317
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="https://HOSTNAME.DOMAIN.COM/">here</a>.</p>
<hr>
<address>Apache/2.4.46 (Ubuntu) Server at HOSTNAME.DOMAIN.COM Port 80</address>
</body></html>
``

curl -i https://HOSTNAME.DOMAIN.COM OUTPUT:
``
HTTP/1.1 302 Found
Date: Mon, 04 Jan 2021 15:13:22 GMT
Server: Apache/2.4.46 (Ubuntu)
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
Set-Cookie: ocfqwdonh2nk=io7igs8fqtd255al41ashn6t4s; path=/; secure; HttpOnly; SameSite=Lax
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=oUBrnSqy8am7F1gdB%2Fvqxzal5ye7XWBY05YA4uzq%2BP4HeC2jG%2B9LgLKsGzvQS4LY8EXSPNTJDbXW6mRrrrlocdBj3tHnhoper%2B3vQJlWPKrxej6jdLyXAKPu0YPSD4yN; path=/; secure; HttpOnly; SameSite=Lax
Set-Cookie: ocfqwdonh2nk=8f10o167urjbhm2o5lb9e8asaf; path=/; secure; HttpOnly; SameSite=Lax
Content-Security-Policy: default-src 'self'; script-src 'self' 'nonce-ZW1ZUVNqZWh3WEhNVTd1dWg3Nmh6Y0dMaTlDWXU3ckZ4TU5DSUNPM3U3MD06RGxNbEdIQ1dzZ21PQitIQTBjM01odTdCMFlMTXkvTzh0NW9VWlVUMWd0RT0='; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *; object-src 'none'; base-uri 'self';
Set-Cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Location: https://HOSTNAME.DOMAIN.COM/login
Content-Length: 0
Content-Type: text/html; charset=UTF-8
``

**Comment by skjnldsv** [comment]
Yeah, it looks like you have a index.php config issue.
It keeps redirecting between the two.

Please check your config against our docs https://docs.nextcloud.com/server/20/admin_manual/installation/source_installation.html#apache-web-server-configuration
And pretty urls https://docs.nextcloud.com/server/20/admin_manual/installation/source_installation.html#pretty-urls

**Comment by HeyWatchOutDude** [comment]
I have used that guide.

**Comment by skjnldsv** [comment]
I mean, can you use your nextcloud properly?
Maybe it's just ssllabs then?

**Comment by HeyWatchOutDude** [comment]
> I mean, can you use your nextcloud properly?
> 
> Maybe it's just ssllabs then?

Kinda but it takes long to load the login page.

After inserting the default apache2 configuration (from guide) + ssl configuration.

I get the following output:

https://hostname.domain.com/index.php

404 not found

But on the other hand I get at ssllabs "HTTP/1.0 200 OK".

**Comment by chrisfoster121** [comment]
I am having a similar issue with the nginx server

```
curl -I http://xxx.xx.xxx.xx/index.php/login

HTTP/1.1 200 OK
Server: nginx
Date: Tue, 05 Jan 2021 02:47:44 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 4665
Connection: keep-alive
Vary: Accept-Encoding
Expires: Tue, 05 Jan 2021 02:48:44 GMT
Pragma: no-cache
Set-Cookie: oc_sessionPassphrase=aZ7lE7%2FILpM2d6MXr6K9qAfVNfKIhpgu5qjC22qIuQ4%2Fz8StLtvAYK63c0%2BenQDvQHQ8IdZUuDTDTVjr8RkYvwkfBcuhwqPLvY05esqZfyWwfX7UtfTxnLmVBHYSW0ns; path=/; HttpOnly; SameSite=Lax
Set-Cookie: ocji7x53qd9o=eph6k5367j49qj5m571rbrd17e; path=/; HttpOnly; SameSite=Lax
Set-Cookie: nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
Set-Cookie: nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
Cache-Control: max-age=60
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';script-src 'self';style-src 'self' 'unsafe-inline';img-src 'self' data: blob:;font-src 'self' data:;connect-src 'self';media-src 'self';frame-ancestors 'self';form-action 'self'
Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'none';microphone 'none';payment 'none'
X-Robots-Tag: none
Strict-Transport-Security: max-age=15768000; includeSubDomains; preload;
Referrer-Policy: no-referrer
X-Content-Type-Options: nosniff
X-Download-Options: noopen
X-Frame-Options: SAMEORIGIN
X-Permitted-Cross-Domain-Policies: none
X-Robots-Tag: none
X-XSS-Protection: 1; mode=block
```

**Comment by HeyWatchOutDude** [comment]
> > I mean, can you use your nextcloud properly?
> 
> > 
> 
> > Maybe it's just ssllabs then?
> 
> 
> 
> After inserting the default apache2 configuration (from guide) + ssl configuration.
> 
> 
> 
> ```
> 
> Alias / "/var/www/nextcloud/"
> 
> 
> 
> <Directory /var/www/nextcloud/>
> 
>   Require all granted
> 
>   AllowOverride All
> 
>   Options FollowSymLinks MultiViews
> 
> 
> 
>   <IfModule mod_dav.c>
> 
>     Dav off
> 
>   </IfModule>
> 
> 
> 
> </Directory>
> 
> 
> 
> Include /etc/letsencrypt/options-ssl-apache.conf
> 
> SSLCertificateFile /etc/letsencrypt/live/hostname.domain.com/fullchain.pem
> 
> SSLCertificateKeyFile /etc/letsencrypt/live/hostname.domain.com/privkey.pem
> 
> ```
> 
> 
> 
> options-ssl-apache.conf:
> 
> ```
> 
> # This file contains important security parameters. If you modify this file
> 
> # manually, Certbot will be unable to automatically provide future security
> 
> # updates. Instead, Certbot will print and log an error message with a path to
> 
> # the up-to-date file that you will need to refer to when manually updating
> 
> # this file.
> 
> 
> 
> SSLEngine on
> 
> 
> 
> # Intermediate configuration, tweak to your needs
> 
> SSLProtocol             -all -SSLv3 -TLSv1 -TLSv1.1 +TLSv1.2 +TLSv1.3
> 
> SSLCipherSuite          ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:EC>
> 
> SSLHonorCipherOrder     on
> 
> SSLSessionTickets       off
> 
> SSLCompression          off
> 
> 
> 
> SSLOptions +StrictRequire
> 
> 
> 
> # Add vhost name to log entries:
> 
> LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vhost_combined
> 
> LogFormat "%v %h %l %u %t \"%r\" %>s %b" vhost_common
> 
> 
> 
> #CustomLog /var/log/apache2/access.log vhost_combined
> 
> #LogLevel warn
> 
> #ErrorLog /var/log/apache2/error.log
> 
> 
> 
> # Always ensure Cookies have "Secure" set (JAH 2012/1)
> 
> #Header edit Set-Cookie (?i)^(.*)(;\s*secure)??((\s*;)?(.*)) "$1; Secure$3$4"
> 
> ```
> 
> I get the following output:
> 
> 
> 
> https://hostname.domain.com/login
> 
> Loading time 45 seconds till I see the login page. (I think that's not normal)

Any update on this?

**Comment by HeyWatchOutDude** [comment]
Update: I have found out why my nextcloud is so slow (45-60 seconds for each request) ... after disabling the following apps my NC was snappy again:

- Collabora Online - Built-in CODE Server (ARM64) 
- Collabora Online

The ssllabs error "Too many redirections" is still present .... Any idea how I can get rid of it?


My current apache2 configuration:
```
    <VirtualHost *:80>
      ServerName hostname.domain.com
      Redirect permanent / https://hostname.domain.com/
    </VirtualHost>
    
    <VirtualHost *:443>
      ServerAdmin admin@domain.com
      DocumentRoot /var/www/nextcloud
      ServerName hostname.domain.com
    
      Alias / "/var/www/nextcloud/"
    
      <Directory /var/www/nextcloud/>
        Options +FollowSymlinks
        AllowOverride All
    
        <IfModule mod_headers.c>
           Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains; preload"
        </IfModule>
    
        <IfModule mod_dav.c>
           Dav off
        </IfModule>
    
        SetEnv HOME /var/www/nextcloud
        SetEnv HTTP_HOME /var/www/nextcloud
      </Directory>
    
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined
    
    Include /etc/letsencrypt/options-ssl-apache.conf
    SSLCertificateFile /etc/letsencrypt/live/hostname.domain.com/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/hostname.domain.com/privkey.pem
    </VirtualHost>
```

**Comment by skjnldsv** [comment]
> The ssllabs error "Too many redirections" is still present .... Any idea how I can get rid of it?

I have no idea how sslabs does their checks. But you can test your webserver manually with the curl commands and make sure the loop is not here.
If it works, ignore sslabs. They might be checking some specific url that doesn't work here.
Nextcloud is not responsible for this :)

**Comment by panzerscope** [comment]
Hey guys, 

Please excuse the bumping of this old topic. I have the same issue with my NextCloud. I believe that I am suffering from a redirect loop. I am running my NextCloud on TrueNas Scale, so via docker. I am trying to locate my "nextcloud.conf" file to scrutinize it, but I am running into a roadblock and I am not sure where to find it, so far as a TrueNas Scale environment. Could someone point me in the right direction ? 

Many thanks,
P

**Comment by matthiasbeyer** [comment]
I am running into this issue as well, with nextcloud27 and nextcloud28 behind nginx.

**Comment by dukekautington3rd** [comment]
Same issue has been happening for me which caused many hours of troubleshooting.  I'm running nginx ingress to front-end the SSL on k8s.  Funny thing is that there was one browser that would never exhibit the problem, but all new browsers or incognito would fail to load the login screen and report something like "too many redirects"

After much troubleshooting with the help of ChatGPT and ultimately [this](https://help.nextcloud.com/t/appliance-disable-https-redirect/89187/9#:~:text=And%20edit%20the%20config.php%20in%20/var/www/nextcloud/config/config.php%20and%20comment%20the%20line%20%3A%20%27overwrite.cli.url%27%20%3D%3E%20%27https%3A//nextcloud/%27%2C) thread, I finally found that the config.php parameter `'overwrite.cli.url' => 'https://mydomain.tld'` was causing a redirect back to https.

It is not indicated that this is expected behavior in the docs [here](https://docs.nextcloud.com/server/19/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=overwrite%20cli%20url#:~:text=%27overwrite.cli.url%27%20%3D%3E%20%27%27%2C)

Seems like a bug or a flaw in documentation.  I expect I will have problems running upgrades in the future using `occ` which, I believe, was the original reason for having that setting.

**Comment by matthiasbeyer** [comment]
I just checked: For me, running nginx as reverse proxy in front of nextcloud, the `overwrite.cli.url` setting is set to `http://localhost`, which should be correct in this stance, right? And I am experiencing the same issue.
