### ISSUE TITLE
Dashboard loading -> Performance Issues after Upgrading from NC 19.0.6 to 20.0.4

### ISSUE THREAD

**Issue by Githopp192** [nextcloud/server#24869]
### Actual behaviour

NC 20.0.4 is a big Milesstone with many enhancements.

Since we are on NC 20.0.4 - some users reports huge loading time when logging in to the new Dashboard.
Some users are reporting, they need about 1 minutes to see the Dashboard.

I did check the users network speed - one of them has got about 25Mbps Download- & 10Mbps Upload Speed, which should not be the culprit.

I did also collect some broswer (Mac Safari) performance reports (JSON- & HAR Files), which are security "sensitive" .. 
so i do not upload them yet. If you wish to analyse them, pls tell me.

### Steps to reproduce

I did these performance tests with several users - not all users have got the same load issue (>1 minute), but the Dashboard
Load time goes from 10 secs. to 60 secs.).

### Expected behaviour

After user login, the user should see the Dashboard in a couple of seconds.
That now users login take til one minute to get to the landing page is some kind of a new behave, which i did not see on previous versions of Nextcloud.

### --------------------------------

different .. Mac- & Windows 10 Users

### --------------------------------

Memory : 16GB
vCPUs: 4
Enterprise Class Server
Version: Intel(R) Xeon(R) E-2136 CPU @ 3.30GHz
Max Speed    : 4300 MHz
Current Speed: 3300 MHz

Operating System: CentOS Linux release 8.3.2011

Upstream OS : Derived from Red Hat Enterprise Linux 8.3

Webserver: Apache/2.4.37 (centos)

Database: mysql 10.3.17-MariaDB,

PHP version: PHP Version => 7.4.13

[PHP Modules] apcu bcmath bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext gmp hash iconv igbinary imagick intl json ldap libsmbclient libxml mbstring memcached msgpack mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline redis Reflection session shmop SimpleXML smbclient sockets sodium SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer xml xmlreader xmlwriter xsl Zend OPcache zip zlib [Zend Modules] Zend OPcache

Nextcloud: - version: 20.0.4.0
### Signing status:

Login as admin user into your Nextcloud and access http://example.com/index.php/settings/integrity/failed
paste the results here.

No errors have been found.

{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "dbtype": "mysql",
        "version": "20.0.4.0",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "updater.release.channel": "stable",
        "auth.bruteforce.protection.enabled": true,
        "check_for_working_htaccess": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauth": 1,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "session_lifetime": 1200,
        "session_keepalive": false,
        "logfile": "\/media\/log\/nextcloud.log",
        "knowledgebaseenabled": false,
        "log_rotate_size": 3145728,
        "mail_sendmailmode": "smtp",
        "app_install_overwrite": [
            "passman",
            "dicomviewer",
            "radio",
            "cookbook"

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - analytics: 3.1.0
  - announcementcenter: 4.0.0
  - apporder: 0.11.0
  - audioplayer: 3.0.0
  - audioplayer_editor: 0.3.0
  - audioplayer_sonos: 1.2.0
  - bookmarks: 4.0.5
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.2
  - circles: 0.20.6
  - cloud_federation_api: 1.3.0
  - cms_pico: 1.0.12
  - comments: 1.10.0
  - contacts: 3.4.2
  - contactsinteraction: 1.1.0
  - cookbook: 0.7.6
  - cospend: 1.2.7
  - dashboard: 7.0.0
  - data_request: 1.7.0
  - dav: 1.16.2
  - deck: 1.2.2
  - dicomviewer: 1.2.2
  - documentserver_community: 0.1.8
  - drawio: 0.9.8
  - event_update_notification: 1.1.0
  - extract: 1.2.5
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_3d: 0.3.3
  - files_antivirus: 3.1.1
  - files_automatedtagging: 1.10.1
  - files_downloadactivity: 1.9.0
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_photospheres: 1.20.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - flow_notifications: 1.0.2
  - flowupload: 1.1.2
  - forms: 2.0.4
  - gpxmotion: 0.1.0
  - gpxpod: 4.2.4
  - groupfolders: 8.2.0
  - health: 0.1.3
  - impersonate: 1.7.0
  - integration_discourse: 0.0.5
  - integration_dropbox: 0.0.12
  - integration_github: 0.0.14
  - integration_gitlab: 0.0.9
  - integration_google: 0.1.2
  - integration_jira: 0.0.11
  - integration_mastodon: 0.0.11
  - integration_moodle: 0.0.5
  - integration_onedrive: 0.0.5
  - integration_reddit: 0.0.6
  - integration_suitecrm: 0.0.4
  - integration_twitter: 0.0.6
  - integration_zammad: 0.0.14
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - passman: 2.3.6
  - password_policy: 1.10.1
  - photos: 1.2.1
  - polls: 1.6.2
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quicknotes: 0.6.3
  - quota_warning: 1.9.1
  - rainloop: 7.0.3
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - social: 0.4.2
  - socialsharing_diaspora: 2.1.0
  - socialsharing_email: 2.1.0
  - socialsharing_facebook: 2.1.0
  - socialsharing_twitter: 2.1.0
  - spreed: 10.0.4
  - support: 1.3.0
  - suspicious_login: 3.2.1
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - terms_of_service: 1.6.1
  - text: 3.1.0
  - theming: 1.11.0
  - timemanager: 0.1.6
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - video_converter: 0.1.5
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflow_ocr: 1.20.1
  - workflow_pdf_converter: 1.5.0
  - workflow_script: 1.5.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - breezedark
  - drop_account
  - encryption
  - end_to_end_encryption
  - external
  - files_accesscontrol
  - files_external
  - files_fulltextsearch
  - fulltextsearch
  - fulltextsearch_elasticsearch
  - gpxedit
  - issuetemplate
  - joplin
  - passwords
  - registration
  - side_menu
  - socialsharing_googleplus
  - survey_client
  - user_ldap
  - weather

**Comment by Giel538** [comment]
I had the same problem. After installing 20.04 on my new pc the load time from the dashboard pages is like 30 - 60 seconds to load.

I find out that after disabling the Collabora Online  and the Collabora Online - Built-in CODE Server apps the problem is gone.

My old setup didnt had this problems (Ubuntu 18  + intel celeron cpu) and my new system had this problem (Ubuntu 20 + intel core i5). I'm running this docker compose setup: https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml

**Comment by Githopp192** [comment]
Hey Giel538 
Thx 4 the Hint. I already did disable all the Collabora Apps .. so there must be another reason for.

On the other hand i did enable all the possible twelve (12!) Apps for Dashboard .. maybe this could also be one reason, than the Dashboard load is taking so long by some users.

**Comment by Githopp192** [comment]
After Upgrading to HC 21.0.1 - Users do report of about 1 Minute wait time to get on the new Dashboard.
So, there is still some improvement to do. Or can this have to do with their Internet Connection speed ?
I don't know.

**Comment by szaimen** [comment]
It tales 3,5 seconds to load the dashboard for me when logging in so this sounds like a configuration issue.
You could try to disable some dashboard apps (maybe this already resolves this issue) or maybe some other apps.
Either way, it sounds like a configuration issue to me. 
So please open a new thread on https://help.nextcloud.com if not already done and link to it here.

**Comment by Githopp192** [comment]
yes .. also my login is quicker (takes about 5-10secs).
That's why i supposed, that's may have to do with the user configuration (internet speed ..)

**Comment by szaimen** [comment]
> That's why i supposed, that's may have to do with the user configuration (internet speed ..)

Yes that's likely possible and hence not a bug if it works for you.

**Comment by Githopp192** [comment]
just did some tests on my hand .. in a **stage of 10,** i did disable all "**non-featured"** apps .. 
There was some little progess in loading .. i think about **0.5 - 1 sec performance improvement per stage (10 Apps).**

As i've got **120 Apps !!** on the Cloud - one could imagine .. that this may have an impact loading the **Dashboard**.
It could be an explanation, why: 

1. the load of the Dashboard needs some time
2. some users (there are several !) report, that the load of the dashboard needs **up to one minute.**
    When a user has got a slow internet connection, this may be one reason, he needs more time to load the whole stuff.

I am not a developer - but I could imagine (Microsoft does this with the Edge browser), it could possibly help:

- that certain dashboard content is pre-loaded and that the user experience is better 
   (I know, that's why the apps write to the appdata folder - in my case the appdata folder is on a SSD Storage - so this should be     
   fast enough).

- that certain dashboard content is cached on the end devices of the users (I know, that's what the brower caches are for); but 
  maybe there would be some recommendations related to that or other improvements on the end device side.

**Comment by szaimen** [comment]
Since I cannot reproduce this I still think that this is a configuration issue or dependant on the users internet speed which we both cannot fix. So again my advice to open a new thread on https://help.nextcloud.com to get help for this. Thanks!
