### ISSUE TITLE
App with id spreed has invalid signature

### ISSUE THREAD

**Issue by PaperMan013** [nextcloud/server#24863]
Can't update or install any apps. Always throws error "App with id **** has invalid signature". 
Problem appeared after upgrade to version 20.0.4
![Снимок](https://user-images.githubusercontent.com/60776064/103225465-058da880-493b-11eb-9966-a92c69022e46.JPG)

**Comment by drpetersen** [comment]
For me, this happened after upgrading to version 21.0.0 beta5, whereas the stable version 20.0.4 on a different deployment works fine. If any fix for the OP's problem is found, I'll report if it also applies to mine.

**Comment by PaperMan013** [comment]
I don't know what happened but after one hour or something all disappeared without any special action from my side. I just tried to update apps again and all processed successfully. I have no idea what it was and why disappeared.

**Comment by drpetersen** [comment]
For me, it also works again since I upgraded to version 21.0.0 beta6.
