### ISSUE TITLE
Missing sudo mode checks

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2487]
- [x] OCS API
  - [x] Provisioning API #2505 
- [x] App management (https://github.com/nextcloud/server/pull/2509)
  - [x] Enable app (https://github.com/nextcloud/server/pull/2509)
  - [x] Disable app (https://github.com/nextcloud/server/pull/2509)
  - [x] Change groups for app (https://github.com/nextcloud/server/pull/2509)
- … ? 

FYI @nickvergessen

**Comment by MorrisJobke** [comment]
All merged
