### ISSUE TITLE
NC 21 Beta 3 and 4 | Systemconfig has errors because of "webfinger" and "nodeinfo"

### ISSUE THREAD

**Issue by Lars1963** [nextcloud/server#24877]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Fresh Install of NC 21.0.0 Beta3
2. Config set as before under NC 20.0.4

### Expected behaviour
No errors on admin page

### Actual behaviour
Config-errors are shown and linking on documentation not working.

Bug or change? Is this by any chance related to https://github.com/nextcloud/server/pull/24860 ?

How to resolve this under NGINX?

See screenshots

![nc_21_0_0_b3_a](https://user-images.githubusercontent.com/45886938/103285727-358e8780-49df-11eb-9463-3f652a64ea36.png)

![nc_21_0_0_b3_b](https://user-images.githubusercontent.com/45886938/103285746-43dca380-49df-11eb-89fd-5be834ba499f.png)

**Comment by Lars1963** [comment]
Adapt this https://github.com/nextcloud/server/pull/24860 to the existing `.htaccess`-file in my nextcloud-root didn't solve this.

**Comment by AlexG-78** [comment]
Remove the corresponding entries in the .htaccess file as webfinger and nodeinfo are triggered in a new API.
I updated to beta4, config page does not show any errors

**Comment by Lars1963** [comment]
> Remove the corresponding entries in the .htaccess file as webfinger and nodeinfo are triggered in a new API.
> I updated to beta4, config page does not show any errors. See #24702

I'm using nginx, not apache. Therefore my webserver isn't using `.htaccess`-files (only the file in the nc-rootfolder which is a standard) and my `nextcloud. conf` has no entries for `.wellknown` what so ever. NC 21 beta 2 doesn't show this error. I'll update to beta4 tomorrow and see if that solves the problem.

**Comment by Lars1963** [comment]
Happa New Year to you all!

I now have found time to update. The same error as in the provided screenshot still exists. 
So now my question is: is this a bug or do I have to change my NGINX `nextcloud.conf`? If I need to change. please provide the documentation/howto for the necessary changes.

**Comment by AlexG-78** [comment]
Hi,
Do you have a nodeinfo and a webfinger  location rewrite rule enabled in your nginx config?
If so, just remove them and reload nginx. As of the new api indies requests are handeled internally and do not need any external Webserver config anymore. 

Hope this helps.

**Comment by ChristophWurst** [comment]
> If I need to change, please provide the documentation/howto for the necessary changes.

https://github.com/nextcloud/documentation/pull/5825 as linked in my PR.

**Comment by Lars1963** [comment]
> Hi,
> Do you have a nodeinfo and a webfinger location rewrite rule enabled in your nginx config?
> If so, just remove them and reload nginx. As of the new api indies requests are handeled internally and do not need any external Webserver config anymore.
> 
> Hope this helps.

@AlexG-78 As I stated before, I have no `.wellknown`-Entries in my nginx-config what so ever. So there is nothing to delete.

I'll have to investigate @ChristophWurst hint a little further, as it seems to be a nginx-specific issue.

**Comment by Lars1963** [comment]
> > If I need to change, please provide the documentation/howto for the necessary changes.
> 
> [nextcloud/documentation#5825](https://github.com/nextcloud/documentation/pull/5825) as linked in my PR. You can even find it online: https://docs.nextcloud.com/server/master/admin_manual/installation/nginx.html

Thx for the hint. I'll will investigate this further.

**Comment by Lars1963** [comment]
@ChristophWurst works now as expected and as a nice side-effect my `nextcloud.conf` now has become even smaller and besser to read.
