### ISSUE TITLE
The 'overwriteprotocol' => 'https' in config.php doesn't work.

### ISSUE THREAD

**Issue by RuofengX** [nextcloud/server#24871]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Local machine: Apache2+Nextcloud+Frp
Remote machine(NAT Server): Nginx+Frp
User browser(HTTPS) <=> Remote machine Nginx:19443(HTTPS) <=> Remote Machine Frp:18981 <=> Local machine Frp:8081 <=> Local machine Apache&Nextcloud
Set the config.php with: overwriteprotocol' => 'https',

### Expected behaviour
Open the nginx's page with HTTPS  it should work well.

### Actual behaviour
Open the webpage directly on Remote machine's Frp port(18981) with HTTP, everything works well.
After configure the nextcloud reverseproxy setting(https://docs.nextcloud.com/server/20/admin_manual/configuration_server/reverse_proxy_configuration.html?highlight=reverse), open the webpage on Nginx's HTTPS login page it also works well, but after entering the login button it redirects to a HTTP page. Actually, I found that the browser sent a post request to the login page and its respond header 's location is start with HTTP, like: http://$my_domain:19443/nextcloud/index.php/apps/dashboard/. And it cause a 400 error, of cause.

### Server configuration

**Operating system:**
Ubuntu2004.1
**Web server:**
Apache2
**Database:**
Pgsql
**PHP version:**
Latest apt
**Nextcloud version:** (see Nextcloud admin page)
20.0.4.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install
**Where did you install Nextcloud from:**
Official site's ZIP file.
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
	- FILE_MISSING
		- .user.ini

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => 49b882eed84d95bc41965468746c9183a665b02a0a7e4814dd2c74930f8da878aa9d845a3735c0cbe472c01ded4005c3d46cf83fb5bf80bb351d226c7fa78ffe
                            [current] => cf83e1357eefb8bdf1542850d66d8007d620e4050b5715dc83f4a921d36ce9ce47d0d13c5d85f2b0ff8318d2877eec2f63b931bd47417a81a538327af927da3e
                        )

                )

            [FILE_MISSING] => Array
                (
                    [.user.ini] => Array
                        (
                            [expected] => 4843b3217e91f8536cb9b52700efb20300290292cf6286f92794d4cec99df286afeb7dd6c91b1be20bc55eda541eef230a5c5e7dcd46c189edd0ed1e80c6d3f5
                            [current] => 
                        )

                )

        )

)
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
POSThttps://stream.ruofengx.cn:19443/nextcloud/index.php/login
[HTTP/1.1 303 See Other 103ms]

	
POST
	https://stream.ruofengx.cn:19443/nextcloud/index.php/login
状态303
See Other
版本HTTP/1.1
传输1.25 KB（大小 280 字节）
Referrer 政策no-referrer

    	
    HTTP/1.1 303 See Other

    Server: nginx/1.14.0 (Ubuntu)

    Date: Tue, 29 Dec 2020 05:36:26 GMT

    Content-Type: text/html; charset=UTF-8

    Content-Length: 0

    Connection: keep-alive

    Expires: Thu, 19 Nov 1981 08:52:00 GMT

    Cache-Control: no-cache, no-store, must-revalidate

    Pragma: no-cache

    Set-Cookie: ocxm6jhbt5j0=lbtslgkgf940l2j8g3ablskfvb; path=/nextcloud; HttpOnly; SameSite=Lax

    Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self';frame-ancestors 'none'

    Referrer-Policy: no-referrer

    X-Content-Type-Options: nosniff

    X-Download-Options: noopen

    X-Frame-Options: SAMEORIGIN

    X-Permitted-Cross-Domain-Policies: none

    X-Robots-Tag: none

    X-XSS-Protection: 1; mode=block

    Set-Cookie: ocxm6jhbt5j0=k8hjcaiudcrcogdmbh3lpmnm5v; path=/nextcloud; HttpOnly; SameSite=Lax

    Location: http://stream.ruofengx.cn:19443/nextcloud/index.php/apps/dashboard/

    Feature-Policy: autoplay 'none';camera 'none';fullscreen 'none';geolocation 'none';microphone 'none';payment 'none'

    Front-End-Https: off
    	
    Accept
    	text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	zh-CN,zh;q=0.8,zh-TW;q=0.7,zh-HK;q=0.5,en-US;q=0.3,en;q=0.2
    Cache-Control
    	no-cache
    Connection
    	keep-alive
    Content-Length
    	185
    Content-Type
    	application/x-www-form-urlencoded
    Cookie
    	nc_username=ruofeng; nc_token=lefKwR4QCGeFNO%2FkEWCQ%2F4gELB6Ix0d%2F; nc_session_id=hudcs9vkhki911l8cc269u0gij; ocxm6jhbt5j0=nhlu3i13e6ec5la22ldcht47jt; nc_username=ruofeng; nc_token=GybA0QUNnos%2FDvuNBUhbgRHP%2F9kSHM7R; nc_session_id=bft4724c2rlaq3ovshus3n78oi; ocxm6jhbt5j0=702d3ibu6dri1fdvto9aobkomq; nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=ruofeng; nc_token=nvp%2BorHmCXXGmo1lxzGpX56c8tiuaH4P; nc_session_id=7f988qfejg9pl7iiha1bcpgjek; ocxm6jhbt5j0=0ghqm374v4h3f9u9v5qeoup64o; oc_sessionPassphrase=xMN%2FtsGSkhpQdCcH2O1xbYAWnEHbb%2BLb9JTfiddMhEj3%2BJkeu0U5Eh0Yu52t17MDvbFLWKmp0okd%2FG%2FAH6vdqMkIOUAXFJ1sdREDFPkGAW2yIGl77Hq0GkmtDGJXyc2q
    DNT
    	1
    Host
    	stream.ruofengx.cn:19443
    Origin
    	null
    Pragma
    	no-cache
    Upgrade-Insecure-Requests
    	1
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

GEThttp://stream.ruofengx.cn:19443/nextcloud/index.php/apps/dashboard/
[HTTP/1.1 400 Bad Request 71ms]

HTML 文档的字符编码未声明。如果该文件包含 US-ASCII 范围之外的字符，该文件将在某些浏览器配置中呈现为乱码。页面的字符编码必须在文档或传输协议层声明。 dashboard
GEThttp://stream.ruofengx.cn:19443/favicon.ico
[HTTP/1.1 400 Bad Request 56ms]

</details>

**Comment by RuofengX** [comment]
I found a solution, just rewrite the nginx reverse proxy config file, add ` proxy_redirect http:// https://;` in the location /nextcloud {}.
It works in Chrome but still doesn't work in Firefox. In firefox, after login, the browser will redirect to `https://stream.ruofengx.cn:19443/nextcloud/index.php/login?redirect_url=/nextcloud/index.php/apps/dashboard/`, which show another login webpage, which is annoying me.

**Comment by RuofengX** [comment]
Oh god, I just reset all the cache in Firefox, and it return to normal. To conclude, to solve 400 ERROR on a NAT reverse proxy with localized nextcloud is: use nginx config ` proxy_redirect http:// https://;`, and reset all the caches of the browser.

**Comment by RuofengX** [comment]
Okey, the config file actually doesn't work. I can only open the website but I can't connect my the client apps to the server.
I encournt the same issue [nextcloud-desktop-issue](https://github.com/nextcloud/desktop/issues/1817) 
I OPENED the overwriteprotocol => 'https', but it seems like just doesn't work.

**Comment by skjnldsv** [comment]
Hey!

Can you make sure you properly setup your nginx config with our documentation
The fact that you have index.php in your urls tells me you're not on te default config.

You can try by running curl on your instance and see if the https redirect is working.
![Capture d’écran_2020-12-30_15-21-36](https://user-images.githubusercontent.com/14975046/103357136-b9657400-4ab2-11eb-8463-32b6af402117.png)

**Comment by RuofengX** [comment]
Thanks for attention!
I just tried the curl command to the frp reverse proxy-port at my server. It returns a http location, not https. In fact, the instance is deployed by apache on my local network, nginx is a rever-proxy server on the cloud server.
`HTTP/1.1 301 Moved Permanently
Date: Wed, 30 Dec 2020 14:43:28 GMT
Server: Apache/2.4.41 (Ubuntu)
Location: http://my.domain:http-port/nextcloud/
Content-Type: text/html; charset=iso-8859-1`
Here is my apache2 config:
<details>
<summary>nextcloud.conf</summary>
<VirtualHost *:8081>

        DocumentRoot </var/www/nextcloud/>
        Alias /nextcloud "/var/www/nextcloud/"

        <Directory />

                Require all granted
                AllowOverride All
                Options FollowSymLinks MultiViews
                Satisfy Any

                <IfModule mod_dav.c>
                        Dav off
                </IfModule>


        </Directory>

</VirtualHost>
</details>

**Comment by RuofengX** [comment]
I will soon reconfigure the nginx reverse proxy config file, and test again.
Thanks for attention.

**Comment by RuofengX** [comment]
I've done it!!!
It is the nginx reverse proxy config that goes wrong.

**Comment by gruentee** [comment]
Hi!
I know I'm digging up the issue again, but I seem to have (at least) a similar problem: Despite using `'overwriteprotocol' => 'https'` Nextcloud frontend still makes request beginning with `http://…`, specifically on the password reset page, which prevents users from resetting their password, because the browser does not allow unsecure requests when already on a secured page.
