### ISSUE TITLE
Disable copy option for documents shared with editing, creating, deleting and re-sharing options are forbidden 

### ISSUE THREAD

**Issue by elhananjair** [nextcloud/server#24882]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I wanted to secure my PDF files that I have shared with other users, and get every activities they have been doing, like downloading and other staffs, so that I can ask them why they do that. But unfortunately there is no such activity report for "copy" option. First of all I would like to have that option that I can prohibit users I have shared the document not to copy the file, or just have that activity property.

**Describe the solution you'd like**
An option to disable copy button on the file I have shared with limited access rights. Other wise someone can just copy the file some where else and do whatever I prohibited on the original file I have shared. 

**Describe alternatives you've considered**
Maybe having activity report for copy option is better, but now I couldn't fix this problem, there is no alternative options too.

**Additional context**
Just I want to see allow Copy option in sharing menu!

Thanks

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
