### ISSUE TITLE
Dashboard Onlyoffice Issues

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#24889]
When you open a doc via the dashboard, it opens fine with OnlyOffice when if you click on the left or right side of the doc it just keep s going throw other documents.  Please see attached video. only happens when you open the documents via the dashboard. 

Nextcloud 20.0.4, Ubuntu 20.0.4 PHP, Version: 7.4.3, MariaDB Version: 10.3.25, OnlyOffice App Version 6.2.0, OnlyOffice Server version 6.1.0.83

https://user-images.githubusercontent.com/59488153/103297216-7a092b80-49bd-11eb-85ed-ce27793a9b2c.mp4

**Comment by axheli** [comment]
Same issue on Nextcloud 20.0.8

**Comment by juliushaertl** [comment]
As mentioned in https://github.com/nextcloud/nextcloud-vue-dashboard/issues/195 this is something for the ONLYOFFICE repo as they most likely set a group when registering the viewer.

**Comment by andyxheli** [comment]
@juliushaertl thank you for letting me know I'll open a ticket with onlyoffice 😄
