### ISSUE TITLE
No email notification for new file in favourites folder

### ISSUE THREAD

**Issue by Elvis2000NC** [nextcloud/server#24883]
I do not receive an email when a file is added to my favourites folder.
I have marked a folder as "Favourite" and also put a tick in my settings that I would like to receive an email notification when someone puts a file in that folder. However, I do not receive an email no matter what time slot I set. My email account (SMTP) works because I receive test emails.
The aim is that I would like to receive an email when new data is placed in this folder, so that I don't always have to check "Activities" to see if something is new in this folder.

![grafik](https://user-images.githubusercontent.com/76623282/103293123-8dcd8580-49ef-11eb-9df5-2ecb776c4ec0.png)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
