### ISSUE TITLE
Proper blacklisting of files

### ISSUE THREAD

**Issue by dk-zero-cool** [nextcloud/server#24897]
Hi. 
So I am currently setting up a home based backup server using NextCloud. It's working fine so far, after some tweaks. However there are files that I would like to exclude, like .git folders, .lock files etc. For some reason .git was rejected before altering the fate of .htaccess (I changed the setup to allow these), but simply adding .git to the blacklisted files list, fixed this problem. The .lock files however was a different story. I tried adding them as *.lock, but this did not work. So I looked at the code and found that this filter does a simple [array lookup](https://github.com/nextcloud/server/blob/f9941347e24f6514c664c7b6b2646723453c705d/lib/private/Files/Filesystem.php#L623)? I made a small change to this, so that my sync goes the way I want, thought that I would put it here. Spending some time on this, one could properly do a much better filter function, but at least this is a lot more than what this function does currently.

```php
/**
 * @param string $filename
 * @return bool
 */
public static function isFileBlacklisted($filename) {
        $filename = self::normalizePath($filename);

        $blacklist = \OC::$server->getConfig()->getSystemValue('blacklisted_files', ['.htaccess']);
        $filename = basename($filename);

        foreach ($blacklist as $target) {
             if ( fnmatch($target, $filename, \FNM_CASEFOLD) ) {
                 return true;
             }
        }

        return false;
}
```

**Comment by szaimen** [comment]
> Spending some time on this, one could properly do a much better filter function

Hi there, would you mind creating a PR with this patch?
Thank you!

**Comment by andriusr** [comment]
I think this little extra functionality would be very useful. Also blacklisting directories. I can prepare merge request, if nextcloud developers agrees.

**Comment by szaimen** [comment]
Yes, please do 👍
I don't know if we will merge it but even for better discussion it makes sense :)
