### ISSUE TITLE
[RFE] Optionally disable filesystem ownership permissions check in console.php

### ISSUE THREAD

**Issue by e-minguez** [nextcloud/server#24913]
Related to https://github.com/nextcloud/docker/issues/1344

The console.php file has a check to ensure the ownership... that fails if using nextcloud in containers with NFS as backend storage for /var/www/html with proper `all_squash,anonuid=82,anongid=0` to match www-data:root ownership.

Modifying the check (just disabling the 'exit') works.

https://github.com/nextcloud/server/blob/47b4efca542b70e015ff5f16ff9f4d2f3b9ac5bb/console.php#L68-L75

**Comment by alhaddar** [comment]
Hi
I tried to understand the method in order to get a solution to this problem, but I am a beginner in the Linux world and I do not have enough knowledge
Can you help me solve this problem?

step by step

Regards
