### ISSUE TITLE
Doctrine\DBAL\Exception\DriverException

### ISSUE THREAD

**Issue by jet76** [nextcloud/server#24920]
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

Detailed logs 
Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

The update was unsuccessful. Please report this issue to the Nextcloud community.

**Comment by jet76** [comment]
sudo -u www-data php occ maintenance:repair
seems to have fixed the issue

**Comment by Ixtalo** [comment]
> sudo -u www-data php occ maintenance:repair
> seems to have fixed the issue

This did not work for me.
However, the solution by @roswitina did work: https://github.com/nextcloud/server/issues/24526#issuecomment-738016163
