### ISSUE TITLE
Ability to play music in Files

### ISSUE THREAD

**Issue by jancborchardt** [nextcloud/server#2492]
Just like you can view pictures, PDFs, movies etc you should also be able to do basic music playing in the Files app as it’s a basic file action – opening it.

Especially when sharing stuff this is cool so the other person doesn’t need to download everything first before listening to it.

cc @nextcloud/javascript is this feasible?

**Comment by MariusBluem** [comment]
What I've found: https://github.com/biosonic/folderplayer

**Comment by Rello** [comment]
Thank you @MariusBluem 
yes I have :-)

Audio Player has the "one click play" from files app and also the integration into the sharing screen (incl. cover art).
Also usable without using the core of AP as ID3 indexing and so on...

https://apps.nextcloud.com/apps/audioplayer
https://github.com/Rello/audioplayer

**Comment by MorrisJobke** [comment]
Also pinging @gnarula and @paulijar ;)

**Comment by rullzer** [comment]
So there is an app for that! => Close

**Comment by paulijar** [comment]
Also the Music app has this kind of feature coming very soon. See https://github.com/owncloud/music/pull/577.

**Comment by jancborchardt** [comment]
@paulijar are you interested in moving over the repository to the Nextcloud organization? :) Considering it was started by @MorrisJobke and designed by me, would be cool. :)

**Comment by paulijar** [comment]
@jancborchardt I'm not against moving the repository, and considering your and @MorrisJobke 's large role in the development of the app, I see the fairness behind that. On the other hand, I'm not sure if it really makes any practical difference. I would anyway like to support both ownCloud and Nextcloud as long as it's technically feasible.

How would the moving happen in practice? Would it basically mean creating a new github project under Nextcloud and uploading the sources there? Can at least the git history be preserved in the move?

**Comment by jancborchardt** [comment]
@paulijar yep, all history, tags and branches would be preserved. :) Depending on the Owncloud folks, you can simply move the whole repository and even issues etc would be preserved. You would need to ask if it’s ok to move though.
