### ISSUE TITLE
there's no options to share a folder to a group

### ISSUE THREAD

**Issue by zimocode** [nextcloud/server#24933]
The version (20) I currently use does not have this option, but the previous version has (19).

**Comment by acsfer** [comment]
The option still exists. Here with 20.0.4.

![image](https://user-images.githubusercontent.com/12234510/103440530-b8fde200-4c46-11eb-9ab1-c90a93047656.png)

**Comment by kesselb** [comment]
For support: https://help.nextcloud.com
