### ISSUE TITLE
Broken CSS when accessing via reverse proxy. MIME mismatch error

### ISSUE THREAD

**Issue by c0fe** [nextcloud/server#24943]
### Actual behaviour
I have an installation where Nextcloud is sitting behind an NGiNX reverse proxy that performs SSL termination. As a result I am getting broken CSS when trying to access the website via it's domain `https://www.subdomain.domain.com` with an error message of:

`Refused to apply style from 'https://www.subdomain.domain.com/apps/files_rightclick/css/app.css?v=46c85d58-0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

If I am to access the site with the hosting server's IP address `192.168.4.202` then the CSS loads correctly.
### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
NGiNX 1.18
**Database:**
MariaDB 10.5
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
20
**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh  Install (server included)
**Where did you install Nextcloud from:**
Nextcloud

**web config:**

```
server {
    listen                  443 ssl http2;
    listen                  [::]:443 ssl http2;
    server_name             www.subdomain.domain.com;
    root                    /var/www/subdomain.domain.com;

    # SSL
    ssl_certificate         /etc/letsencrypt/live/subdomain.domain.com/fullchain.pem;
    ssl_certificate_key     /etc/letsencrypt/live/subdomain.domain.com/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/subdomain.domain.com/chain.pem;

    # security
    include                 nginxconfig.io/security.conf;

    # logging
    access_log              /var/log/nginx/subdomain.domain.com.access.log;
    error_log               /var/log/nginx/subdomain.domain.com.error.log debug;

    # index.php
    index                   index.php;

    # index.php fallback
    location ~ ^/api/ {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # reverse proxy
    location / {
        proxy_pass http://192.168.7.202;
        include    nginxconfig.io/proxy.conf;
    }

    # additional config
    include nginxconfig.io/general.conf;
}

# HTTP redirect
server {
    listen      80;
    listen      [::]:80;
    server_name subdomain.domain.com;
    include     nginxconfig.io/letsencrypt.conf;

    location / {
        return 301 https://www.subdomain.domain.com$request_uri;
    }
}

server {
    listen      80;
    listen      [::]:80;
    server_name www.subdomain.domain.com;
    include     nginxconfig.io/letsencrypt.conf;

    location / {
        return 301 https://www.subdomain.domain.com$request_uri;
    }
}
```

**security.conf**

```
# security headers
add_header X-Frame-Options           "SAMEORIGIN" always;
add_header X-XSS-Protection          "1; mode=block" always;
add_header X-Content-Type-Options    "nosniff" always;
add_header Referrer-Policy           "no-referrer-when-downgrade" always;
add_header Content-Security-Policy   "default-src 'self' http: https: data: blob: 'unsafe-inline'" always;
add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

# . files
location ~ /\.(?!well-known) {
    deny all;
}
```

**proxy.conf**

```
proxy_http_version                 1.1;
proxy_cache_bypass                 $http_upgrade;

# Proxy headers
proxy_set_header Upgrade           $http_upgrade;
proxy_set_header Connection        "upgrade";
proxy_set_header Host              $host;
proxy_set_header X-Real-IP         $remote_addr;
proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host  $host;
proxy_set_header X-Forwarded-Port  $server_port;

# Proxy timeouts
proxy_connect_timeout              60s;
proxy_send_timeout                 60s;
proxy_read_timeout                 60s;

# Additional settings
proxy_max_temp_file_size 16384m;
client_max_body_size 0;
    proxy_hide_header Upgrade;
```

**general.conf**

```
# favicon.ico
location = /favicon.ico {
    log_not_found off;
    access_log    off;
}

# robots.txt
location = /robots.txt {
    log_not_found off;
    access_log    off;
}

# assets, media
location ~* \.(?:css(\.map)?|js(\.map)?|jpe?g|png|gif|ico|cur|heic|webp|tiff?|mp3|m4a|aac|ogg|midi?|wav|mp4|mov|webm|mpe?g|avi|ogv|flv|wmv)$ {
    expires    7d;
    access_log off;
}

# svg, fonts
location ~* \.(?:svgz?|ttf|ttc|otf|eot|woff2?)$ {
    add_header Access-Control-Allow-Origin "*";
    expires    7d;
    access_log off;
}

# gzip
gzip            on;
gzip_vary       on;
gzip_proxied    any;
gzip_comp_level 6;
gzip_types      text/plain text/css text/xml application/json application/javascript application/rss+xml application/atom+xml image/svg+xml;
```

**config.php**

```
<?php
$CONFIG = array (
  'instanceid' => 'REDACTED',
  'passwordsalt' => 'REDACTED',
  'secret' => 'REDACTED',
  'trusted_domains' => 
  array (
    0 => 'www.subdomain.domain.com',
    1 => '192.168.4.202',
  ),
  'datadirectory' => '/var/www/cloud/data',
  'dbtype' => 'mysql',
  'version' => '20.0.4.0',
  'overwrite.cli.url' => 'http://www.subdomain.domain.com',
  'dbname' => 'REDACTED',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'REDACTED',
  'dbpassword' => 'REDACTED',
  'installed' => true,
);
```

Is this no longer supported by Nextcloud? it's a bit odd since I was able to run this on version 17. I used nginxconfig.io to generate the reverse proxy and adjusted it to match to what I had previously.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by c0fe** [comment]
@kesselb i have read that, i tried it, posted on the forums but got no responses. I think this is a bug.

**Comment by kesselb** [comment]
> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

As explained in the issue template. I closed the issue as configuration issue because you provided no evidence that it's a bug. A nginx for ssl termination is a super common setup many people use. 

https://github.com/search?q=org%3Anextcloud+is+not+a+supported+stylesheet+MIME+type%2C+and+strict+MIME+checking+is+enabled&type=issues there are 10 reports with this error message on GitHub (for the Nextcloud organization). If ssl termination with nginx should be broken somehow we had tons of issue reports.
