### ISSUE TITLE
Upgrade to 20.0.4

### ISSUE THREAD

**Issue by spartiate59500** [nextcloud/server#24947]
Nextcloud installed on a Debian 10.07

Upgrade Nextcloud to 20.0.4

I have this issue : 
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'UPDATE `oc_filecache` SET `mimetype` = ? WHERE (`mimetype` <> ?) AND (`mimetype` <> ?) AND (`name` COLLATE utf8mb4_general_ci LIKE ?)' with params [70, 70, 2, "%.ott"]: SQLSTATE[HY000]: General error: 1206 The total number of locks exceeds the lock table size

How to solve it please ?

**Comment by j-ed** [comment]
The purpose of this repository is to track bugs and feature requests for the development only. Therefore please address your question in the [**Nextcloud help forum**](https://help.nextcloud.com/) which has explicitly been created for that purpose.
