### ISSUE TITLE
Bug With Uploading Contents to NC Server

### ISSUE THREAD

**Issue by RHQ-Rusty** [nextcloud/server#24942]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Fresh Install of NC
2. Log In for First Time
3. Attempt File Upload

### Expected behaviour
The test file (~5KB) should end up in NextCloud.

### Actual behaviour
Regardless of Filesize, it doesn't upload. It always returns "upload failed, unknown server error."

### Server configuration

**Operating system:** Linux x86/x64

**Web server:** Routed through [my host](https://elhosting.com/)

**Database:** MySQL 5.7.32-cll-lve

**PHP version:** 7.3.21

**Nextcloud version:** Latest (just downloaded and installed today)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install (x5)

**Where did you install Nextcloud from:** `setup-nextcloud.php`

**Signing status:**
<details>
<summary>Signing status</summary>

```
Several errors appear, but as it was broken, I've uninstalled it yet again. If this is _truly_ needed, I can re-install and obtain this list.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Tried with No Apps and All Apps. Same Result.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config Report</summary>

```
Left it Blank / As-Is. Nothing was changed.
```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** No

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Tested on Several (Chrome, Firefox, IE / Edge)

**Operating system:** Tested on Several (Win10, MacOSX)

### Logs
No logs were generated, or I cannot find them.

#### Web server error log
<details>
<summary>Web server error log</summary>

```
No errors from the webserver; only from PHP (which I've resolved now; it was a `php.ini` issue)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No logs were generated, or I cannot find them.
```
</details>

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
