### ISSUE TITLE
Sqlite support

### ISSUE THREAD

**Issue by somenxavier** [nextcloud/server#2494]
Please support sqlite in nextcloud as your [parent does](https://doc.owncloud.org/server/7.0/admin_manual/configuration/database_configuration.html). Sqlite is useful for embed devices such as rasperrypi for example and local environment,

**Comment by MariusBluem** [comment]
We do ;) ... Simple answer 😜😅

**Comment by somenxavier** [comment]
So the bug is against documentation: in [yours](https://docs.nextcloud.com/server/10/admin_manual/configuration_database/linux_database_configuration.html) you just comment MariaDB and Postgresql but not sqlite. And your parent [does](https://doc.owncloud.org/server/7.0/admin_manual/configuration/database_configuration.html). On the other hand, you say in docs that sqlite is the [default option in wizard](https://docs.nextcloud.com/server/10/admin_manual/installation/installation_wizard.html#database-choice). So you do. Incongruent information

**Comment by MariusBluem** [comment]
ownCloud does nothing different on their documentation as you can see over here: https://doc.owncloud.org/server/latest/admin_manual/configuration_database/linux_database_configuration.html

The link you are providing is from a old and unsupported ownCloud 7 documentation.

Bugs in the documentation should be discussed over here: github.com/nextcloud/documentation

THX! 😉
