### ISSUE TITLE
Using NextCloud as a 'facade' for a non-publicly reachable second instance

### ISSUE THREAD

**Issue by AndreasVS** [nextcloud/server#24952]
**Is your feature request related to a problem? Please describe.**

NextCloud is a fabulous software to share data (and more) and cares about security. My opinion as a non-security-expert is, that a hosted platform from a trusted company (which i use) is far safer than my own installation with possible forgotten things which break the security (wrong database config, firewall, port-forwaring in router, ...).  

So i use a hosted account which i pay for. And it is expensive so i have only limited storage. Adding storage like S3 is possible but not cheap and it is not seamlessly integrated.

**Describe the solution you'd like**

What i think about for some time is a two-part solution: First the open and accessible hosted plattform with limited space. Second the non-reachable (no portforwarding or similar) own-hosted instance with massive space in my house.

The idea is to configure NextCloud (hosted) to act like a cache, which don't use the own filesystem except for caching and to confige NextCloud (own-system) to permanently hold a connection to the other system without the need of changing the router config. If this is technically possible, there is no need for a VPN or a port forwarding or so...

So my network is safe and NextCloud (hosted) could get all the fileinformations needed. When someone logs in to NextCloud (hosted) it shows the files from NextCloud (own) and gets them, when needed. When someone uploads new files to NextCloud (hosted), the data will be cached for a short time and instantly be transferred to the second instance.

I think this could be a good solution for smaller installations (aka home-user) where the user don't want an unsecure home-network but want lots of data available.

**Describe alternatives you've considered**

Using external storage is possible, i know, but it is implemented like mounting on linux. Its an own folder in the big filesystem. A better solution (or a missing second option) would be to overlay the "main"-storage completely (which could be also used as a cache).

Second: using only an own system like a rasperry-pi or so with open ports is also possible, too. Additionally the installation whould be easy. But it is my opinion that is is impossible to get a really secure system without caring permanently and without getting part of an network/security-expert. This solution impacts the router, linux. apache, database and obviously NextCloud. All parts together must be secure and beeing honest: that is not possible for 'normal people'.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by sunjam** [comment]
My recommendation is to route your traffic through OpenVPN / Wireguard.  Since you are on a Raspberry Pi look into HomelabOS.  Good luck.
