### ISSUE TITLE
Unable to log in after upgrade from 10 to 11 beta2

### ISSUE THREAD

**Issue by rigrig** [nextcloud/server#2495]
This happened just after updating from NC 10 to 11 beta 2.
After the upgrade I am still logged in, but trying to log in in a private browser window fails.

### Steps to reproduce
1. While not logged in, go to the login page
2. Enter valid credentials
3. Press "Log in"

### Expected behaviour
I should be logged in

### Actual behaviour
I get an error message:
> Internal Server Error
> The server encountered an internal error and was unable to complete your request.
> Please contact the server administrator if this error reappears multiple times, please include the technical details below in your report.
> More details can be found in the server log.
> 
> Technical details
> Remote Address: 82.75.158.124
> Request ID: tzO+phP7/ZpglP5oQvrg

### Server configuration
**Operating system**: 4.7.0-1-amd64 #1 SMP Debian 4.7.8-1 (2016-10-19) x86_64 GNU/Linux

**Web server:** Apache/2.4.10 (Debian)

**Database:** psql (PostgreSQL) 9.4.9

**PHP version:** PHP 7.0.13-1~dotdeb+8.1

**Nextcloud version:** 11.0 beta 2 (beta)

**Updated from an older Nextcloud/ownCloud or fresh install:** Up[dated from 10

**Where did you install Nextcloud from:** beta channel from https://updates.nextcloud.com/updater_server/

**Signing status:**
Integrity checker has been disabled. Integrity cannot be verified.

**List of activated apps:**
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - apporder: 0.3.3
  - calendar: 1.4.1
  - contacts: 1.5.2
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 1.3.1
  - lookup_server_connector: 1.0.0
  - news: true
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - richdocuments: 1.1.14
  - serverinfo: 1.1.1
  - sharebymail: 1.0.0
  - survey_client: 0.1.5
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1

Disabled:
  - comments
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_retention
  - mail
  - systemtags
  - templateeditor
  - twofactor_totp
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "instanceid": "ocaed749a93a",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "dbtype": "pgsql",
        "version": "11.0.0.5",
        "installed": true,
        "forcessl": true,
        "loglevel": 2,
        "theme": "",
        "maintenance": false,
        "defaultapp": "news",
        "enable_previews": true,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enabledPreviewProviders": [
            "OC\\Preview\\PNG",
            "OC\\Preview\\JPEG",
            "OC\\Preview\\GIF",
            "OC\\Preview\\BMP",
            "OC\\Preview\\XBitmap",
            "OC\\Preview\\MP3",
            "OC\\Preview\\TXT",
            "OC\\Preview\\MarkDown",
            "OC\\Preview\\Illustrator",
            "OC\\Preview\\Movie",
            "OC\\Preview\\MSOffice2003",
            "OC\\Preview\\MSOffice2007",
            "OC\\Preview\\MSOfficeDoc",
            "OC\\Preview\\OpenDocument",
            "OC\\Preview\\PDF",
            "OC\\Preview\\Photoshop",
            "OC\\Preview\\Postscript",
            "OC\\Preview\\StarOffice",
            "OC\\Preview\\SVG",
            "OC\\Preview\\TIFF",
            "OC\\Preview\\Font"
        ],
        "trusted_domains": [
            "fnp.tubul.net",
            "public.tubul.net",
            "tubul.net",
            "webmail.tubul.net",
            "cloud.tubul.net"
        ],
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "mail_from_address": "nextcloud",
        "mail_smtpmode": "php",
        "mail_domain": "tubul.net",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "updater.release.channel": "beta",
        "apps_paths": [
            {
                "path": "\/var\/www\/nextcloud\/public\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "appstoreenabled": true,
        "appcodechecker": false,
        "appstore.experimental.enabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "trashbin_retention_obligation": "auto",
        "asset-pipeline.enabled": true,
        "overwrite.cli.url": "https:\/\/fnp.tubul.net",
        "htaccess.RewriteBase": "\/",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Chromium Version 53.0.2785.143 Built on 8.6, running on Debian 8.5 (64-bit)

**Operating system:** LMDE, 4.6.0-1-amd64 #1 SMP Debian 4.6.4-1 (2016-07-18) x86_64 GNU/Linux

#### Web server error log
empty

#### Nextcloud log (data/nextcloud.log)
I think the relevant entry is this one: (it's the only one showing up right when I try logging in)
```
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO "oc_authtoken"("uid","login_name","password","name","token","type","remember","last_activity") VALUES(?,?,?,?,?,?,?,?)' with params ["richard", "richard", "***PASSWORD REMOVED***", "Mozilla\/5.0 (X11; Linux x86_64) AppleWebKit\/537.36 (KHTML, like Gecko) Chrome\/53.0.2785.143 Safari\/537.36", "***TOKEN REMOVED***", 0, false, 1480799738]: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for integer: "f"
/var/www/nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractPostgreSQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
/var/www/nextcloud/public/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOPgSql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'INSERT INTO "oc...', Array)
/var/www/nextcloud/public/lib/public/AppFramework/Db/Mapper.php - line 252: Doctrine\DBAL\Statement->execute()
/var/www/nextcloud/public/lib/public/AppFramework/Db/Mapper.php - line 126: OCP\AppFramework\Db\Mapper->execute('INSERT INTO `*P...', Array)
/var/www/nextcloud/public/lib/private/Authentication/Token/DefaultTokenProvider.php - line 97: OCP\AppFramework\Db\Mapper->insert(Object(OC\Authentication\Token\DefaultToken))
/var/www/nextcloud/public/lib/private/User/Session.php - line 561: OC\Authentication\Token\DefaultTokenProvider->generateToken(*** sensitive parameters replaced ***)
/var/www/nextcloud/public/core/Controller/LoginController.php - line 243: OC\User\Session->createSessionToken(Object(OC\AppFramework\Http\Request), 'richard', 'richard', '***START OF PASSWORD REMOVED***...', false)
[internal function] OC\Core\Controller\LoginController->tryLogin(*** sensitive parameters replaced ***)
/var/www/nextcloud/public/lib/private/AppFramework/Http/Dispatcher.php - line 160: call_user_func_array(Array, Array)
/var/www/nextcloud/public/lib/private/AppFramework/Http/Dispatcher.php - line 90: OC\AppFramework\Http\Dispatcher->executeController(Object(OC\Core\Controller\LoginController), 'tryLogin')
/var/www/nextcloud/public/lib/private/AppFramework/App.php - line 114: OC\AppFramework\Http\Dispatcher->dispatch(Object(OC\Core\Controller\LoginController), 'tryLogin')
/var/www/nextcloud/public/lib/private/AppFramework/Routing/RouteActionHandler.php - line 47: OC\AppFramework\App main('OC\\Core\\Control...', 'tryLogin', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
[internal function] OC\AppFramework\Routing\RouteActionHandler->__invoke(Array)
/var/www/nextcloud/public/lib/private/Route/Router.php - line 299: call_user_func(Object(OC\AppFramework\Routing\RouteActionHandler), Array)
/var/www/nextcloud/public/lib/base.php - line 1010: OC\Route\Router->match('/login')
/var/www/nextcloud/public/index.php - line 40: OC handleRequest()
{main}
```

**Comment by LukasReschke** [comment]
This should be fixed by https://github.com/nextcloud/server/pull/2428, could you test if applying that patch solves your problem?

**Comment by rigrig** [comment]
It does, thanks!
