### ISSUE TITLE
Invalid Domainname

### ISSUE THREAD

**Issue by MaxBenn** [nextcloud/server#24950]
### Steps to reproduce
1. Go to Setting -> Theming
2. Change internal Link to föck.it (not my url)

### Expected behaviour
Tell us what should happen:
It should let me save this link, since it is a valid link. 

### Actual behaviour
Tell us what happens instead:
It tells me, that it is a invalid Link

**Operating system:**
Any

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
nextcloud.com

**Comment by j-ed** [comment]
> **Steps to reproduce**
> 
>     Go to Setting -> Theming
>     Change internal Link to föck.it (not my url)

Please try to use a punycode encoded url to prevent unicode characters, e.g. "**`https://xn--fck-sna.it`**"

**Comment by szaimen** [comment]
As j-ed pointed out, you should use a punycode encoded url to prevent unicode characters.
