### ISSUE TITLE
DAV ServiceUnavailable

### ISSUE THREAD

**Issue by galaxyrun** [nextcloud/server#24977]
**Describe the bug**
I can't sync my Photos with nextcloud. When i create a folder on my phone (lespas app) it will show up in my lespas folder. The already existing folders will not show up in the app.

**OS**
 - Nextcloud 20.0.4
 - Lespas 1.3
 - PHP 7.3.19
 - mysql 10.3.27
 - NextCloudPi version v1.34.1

***Error message 1***

[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable: Could not open file at <<closure>>

0. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
   OCA\DAV\Connector\Sabre\File->get()
1. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
   Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
2. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
   Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
3. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
   Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
4. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
   Sabre\DAV\Server->start()
5. /var/www/nextcloud/apps/dav/lib/Server.php line 332
   Sabre\DAV\Server->exec()
6. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
   OCA\DAV\Server->exec()
7. /var/www/nextcloud/remote.php line 167
   require_once("/var/www/nextcl ... p")

***Error message 2***

[PHP] Error: Error: fopen(/media/1d39d588-0b92-6a47-bc86-0b4da013189a/ncdata/USERNAME/files/lespas/Photos from 2012/CAM00064.jpg): failed to open stream: No such file or directory at /var/www/nextcloud/lib/private/Files/Storage/Local.php#355 at <<closure>>

 0. <<closure>>
    OC\Log\ErrorHandler::onError(2, "fopen(/media/1d ... y", "/var/www/nextcl ... p", 355, {path: "files/le ... "})
 1. /var/www/nextcloud/lib/private/Files/Storage/Local.php line 355
    fopen("/media/1d39d588 ... g", "r")
 2. /var/www/nextcloud/lib/private/Files/Storage/Wrapper/Wrapper.php line 300
    OC\Files\Storage\Local->fopen("files/lespas/Ph ... g", "r")
 3. /var/www/nextcloud/lib/private/Files/View.php line 1165
    OC\Files\Storage\Wrapper\Wrapper->fopen("files/lespas/Ph ... g", "r")
 4. /var/www/nextcloud/lib/private/Files/View.php line 1001
    OC\Files\View->basicOperation("fopen", "/lespas/Photos from 2012/CAM00064.jpg", ["read"], "r")
 5. /var/www/nextcloud/apps/dav/lib/Connector/Sabre/File.php line 434
    OC\Files\View->fopen("lespas/Photos from 2012/CAM00064.jpg", "r")
 6. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 90
    OCA\DAV\Connector\Sabre\File->get()
 7. /var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpGet(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 8. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:GET", [Sabre\HTTP\Requ ... }])
 9. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
10. /var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
11. /var/www/nextcloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
12. /var/www/nextcloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
13. /var/www/nextcloud/remote.php line 167
    require_once("/var/www/nextcl ... p")

GET /remote.php/dav/files/USERNAME/lespas/Photos%20from%202012/CAM00064.jpg

**Comment by dermitdemwolf** [comment]
same problem here

Nextcloud 20.0.7

**Comment by mukesh120** [comment]
Same here!

**Comment by mukesh120** [comment]
Ok, it worked for me. Basically, I was transferring all my nextcloud files from one server to another, so I installed nextcloud on both and imported the old MySQL files into the new server. Then, it was showing me the files however I had the same error when clicked. So, the problem was that there were no files in the folder. Basically, the file I was clicking, it was showing in Nextcloud due to the SQL database, however, it wasn't present in the nextcloud>files folder.... So, in a nutshell, make sure the file you are trying to access is present in nextcloud>files folder. And if there is no files folder, create one and put the file inside, and then try.

**Comment by nlg35** [comment]
Or scan the files :
`sudo -u nextcloud php /var/www/nextcloud/occ files:scan --all`

**Comment by szaimen** [comment]
So seems like this was a configuration issue. Please continue the discussion in the forum https://help.nextcloud.com
Thanks!
