### ISSUE TITLE
Provide a URL with a file name for downloading a shared file

### ISSUE THREAD

**Issue by benks-io** [nextcloud/server#24975]
As discussed in #3776 for downloading a share, a file name will be send within the header. Anyway in advance you cannot see the file Type or Name when you see a URL e.g. in a chat or mail. Also wget needs the Flag "--content-disposition" to give it the right name in the file system after downloading. Without it the file name is "download".

For transparency, recognizability and convenience, providing a complete URL with the file name booth in the share front end for external users and in the share dialogue of the file owners sidebar, would be an improvement.

e.g. https://cloud.foo.com/s/Bbpdhdd7d7qHYim/download/mydocument.pdf

**Comment by szaimen** [comment]
I think this was implemented with https://github.com/nextcloud/server/pull/22843

**Comment by benks-io** [comment]
Great. I can see this is true for Single File Shares. The download button in the upper right corner now has a full URL with file name.
Anyway, when sharing a Folder, The download button in the file listing has a URL without:

![image](https://user-images.githubusercontent.com/57667105/122903258-8314fd00-d34f-11eb-9aaf-f7ee1c6eb750.png)

**Comment by szaimen** [comment]
cc @skjnldsv
