### ISSUE TITLE
Make federation retry stop when failing

### ISSUE THREAD

**Issue by pixel8383** [nextcloud/server#24983]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I inserted a wrong address to create a federation (a local one instead of a public dns) and obviously on the public server side, the federation failed.

Since then my nextcloud.log is continuously fullfilled by this:

`{"reqId":"7MzEpBG2iHucoQJlwnj3","level":2,"time":"2021-01-05T19:15:02+00:00","remoteAddr":"","user":"--","app":"no app in context","method":"","url":"--","message":"Host nextcloud.home.local was not connected to because it violates local access rules","userAgent":"--","version":"20.0.4.0"}`

I have tried to remove the Federation plugin but didn’t solve. How can I stop Nextcloud to try to connect to that server?

Thank you.

### Steps to reproduce
1. Create a federation with a local server
2. The local server will be able to connect but the remote server which can't resolve the address will not
3. Remove the federation

### Expected behaviour
Federation retries to stop when failing after a reasonable amount of time/retries.

### Actual behaviour
Federation is counted forever and the log is fullfilled by fails.

### Server configuration

**Operating system:** FreeBSD

**Web server:** nginx

**Database:** MariaDB

**PHP version:** 7.4

**Nextcloud version:** (see Nextcloud admin page) 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from older

**Where did you install Nextcloud from:** curl download

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by pixel8383** [comment]
Any idea on how to stop nextcloud retry to connect to an unreachable federation server?

**Comment by szaimen** [comment]
Lets trackt his in https://github.com/nextcloud/server/issues/23619
