### ISSUE TITLE
Printing option available in Secure View

### ISSUE THREAD

**Issue by ashishwadekar** [nextcloud/server#24998]
Printing option is available when Secure mode is turned on for a PDF file

NextCloud Version: 20.0.4

### Steps to reproduce
1. Upload a PDF to Nextcloud
2. Share it via sharing menu
3. Select Hide Download button in sharing menu to enable Secure view

### Expected behaviour
The shared document when accessed via URL should not display download button nor printing button

### Actual behaviour
The shared document when accessed via URL does not display download button nor but displays printing button

This will create issues & potential data theft for documents shared over to third parties.

Regards,
Ashish

**Comment by ediazcomellas** [comment]
I've just discovered your bug report. This morning I filed a similar one in the files_pdfviewer repo:

https://github.com/nextcloud/files_pdfviewer/issues/311
