### ISSUE TITLE
Support custom fields in Contacts

### ISSUE THREAD

**Issue by chepec** [nextcloud/server#250]
I guess this is more of a feature request than a bug.

Coming from Google Contacts, I couldn't avoid noticing that the Nextcloud Contacts app lacks the ability to customise the field labels. 

![Field labels](https://luxor.chepec.se/nextcloud/index.php/s/QTH0gzenT8nNpuh/download)

I did some research, and if I read [this DavDroid forum post ](https://forums.bitfire.at/topic/357/custom-labels-on-phone-numbers-get-lost-on-sync) correctly, the CardDav standard supports custom field labels.

That leads me to believe that custom field labels could be added in the Nextcloud Contacts web UI. Please correct me if I'm wrong, or if this is the wrong place to report this.

### Expected behaviour
Please consider enabling custom field labels in the Nextcloud Contacts web UI. It would be a tremendously useful addition to the contacts UI.

### Actual behaviour
Field labels are restricted to certain options (`Home`, `Work`, `Mobile`, etc.).

### Server configuration
**Operating system**: Ubuntu server 14.04.4

**Web server:** Apache 2.4.7

**Database:** `mysql  Ver 14.14 Distrib 5.5.49`

**PHP version:** PHP 5.5.9-1ubuntu4.17 

**Nextcloud version:** 9.0.51

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh install

**Where did you install Nextcloud from:** `https://download.nextcloud.com/server/releases/nextcloud-9.0.51.tar.bz2`

**Signing status (Nextcloud 9.0 and above):**

**List of activated apps:** Gallery, Documents, Contacts, Calendar, Notes.

**Are you using encryption:** yes

### Client configuration
**Browser:** Tested on Firefox 47, and Google Chrome 51.0.2704.106 (64-bit).

**Operating system:** Ubuntu Linux 14.04.4 desktop

**Comment by schiessle** [comment]
Please open the issue here https://github.com/owncloud/contacts

This needs to be implemented in the contacts app, the server already supports it

**Comment by mar1u5** [comment]
FYI @Henni @nextcloud/contacts

**Comment by schiessle** [comment]
I copied the issue over to the correct repository, @chepec please follow up there. Thanks!

**Comment by crti** [comment]
Sorry but isn't the Contact App now forked off from the oC one meaning they are not sharing anymore the same edits/code? 
https://github.com/nextcloud/contacts
https://github.com/owncloud/contacts 1.5.2
