### ISSUE TITLE
WebDAV Passwort with "§" char not connectable

### ISSUE THREAD

**Issue by nobe80** [nextcloud/server#25002]
Hi,

when you have a user passwort that has a § char in there then it is not possible to connect to the nextcloud server via Webdav. The Webinterface accept the Passwort but not the Webdav connection. Other chars like % $ & !  will accepted. I have tested this ẃith the newest version 20.0.4 and Windows 10.

regards, 
Betei

**Comment by acsfer** [comment]
Does it work with the [Nextcloud Desktop client](https://nextcloud.com/install/#install-clients) and/or with [Cyberduck](https://cyberduck.io/download/)?

**Comment by nobe80** [comment]
I have tried Cyberduck and it works there with the "§" char. This seems to be Windows related. I saw also that if you try to connect via Windows 10 file explorer, the login attempt is notice in the oc:bruteforce_atempts table.
So it seems that Windows coding that "§" char wrong or on another wise.

**Comment by szaimen** [comment]
As this seems to be a bug in Windows, there is nothing that we can do here.
