### ISSUE TITLE
Share with others: wrong group avatar

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#25014]
- share a file to a group
- Shares -> shares with others
- see that group icon in file list is "?", but it should be correct char with background color
![image](https://user-images.githubusercontent.com/5836855/103906682-8f3e3280-5100-11eb-875d-73ffced537d3.png)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by tobiasKaminsky** [comment]
Still true on latest master:
![image](https://user-images.githubusercontent.com/5836855/215096040-b92332bd-1d80-42ef-af1d-da8751d2395d.png)

**Comment by joshtrichards** [comment]
No longer relevant in >=28.
