### ISSUE TITLE
android & firefox: search popup not visible (out of screen)

### ISSUE THREAD

**Issue by alexanderdd** [nextcloud/server#25037]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. open Nextcloud on firefox mobile 84.1.3 on android 8.0.0 (maybe other browsers/platforms too)
2. tap the search icon and type something

### Expected behaviour
search popup is centered, search results are visible

### Actual behaviour
search popup is beyond the screen on left side, can't see the search results

### Server configuration
Nextcloud 20.0.4

Tell me if you need more info.

**Comment by szaimen** [comment]
I can reproduce this on NC22 beta 5
![image](https://user-images.githubusercontent.com/42591237/122905554-9cb74400-d351-11eb-91d4-991c9c7cd093.png)
cc @nextcloud/designers
