### ISSUE TITLE
Samba Share - Icewind\SMB\Exception\NotFoundException: Invalid request for... (NotFoundException) NC-20

### ISSUE THREAD

**Issue by Uwe-MrT** [nextcloud/server#25045]
Hi, after Update NC 18 to NC 20.0.4 in my error.log i found this entrys on Mass.

Icewind\SMB\Exception\NotFoundException: Invalid request for **PATH-TO-FILE** (NotFoundException)

But the Share seems to work...

May be this Error was also on NC 18 or NC 19, i dont know.
I made an NC Update

cd /var/www/html/ (my Nextcloud)
sudo -u www-data php occ maintenance:mode --on
sudo -u www-data php updater/updater.phar

from 18.0.12 to 19.0.6 
and from 19.0.6 to 20.0.4

Debian 10 (Buster)
PHP 7.3 (php-fpm)
Apache2

**Comment by N3m3515** [comment]
I am facing the same issue

**Comment by Uwe-MrT** [comment]
Hi, i made all Updates.
Debian... some Packages (apt update, apt upgrade)
PHP from 7.3 to 7.4 and all changes in /etc/php/7.4/...
NC from 20.0.5 to 20.0.6
and a Fix like here subscribed about encoding
https://help.nextcloud.com/t/invalid-encoding-on-file-names-in-nc19/83835/5

The Error is gone away.
