### ISSUE TITLE
Conflict between mail and fulltextsearch_elasticsearch apps

### ISSUE THREAD

**Issue by jernst** [nextcloud/server#25042]
Nextcloud 20.0.4, with apps `mail` 1.7.2, `fulltextsearch_elasticsearch` 20.0.0, `files_fulltextsearch` 20.0.0, `fulltextsearch` 20.0.0 on UBOS (like Arch) on x86_64.

I'm running 
```
sudo -u http php -d memory_limit=512M occ fulltextsearch_elasticsearch:configure '{
    "elastic_host": "http://localhost:5001/",
    "elastic_index": "nextcloud-a412f14cc997d1d3de69dae416a811ce1e21a7bd8"
}
' 
```

This works fine when app `mail` is **not** installed. However, when `mail` is installed I am getting 
```
An unhandled exception has been thrown:
TypeError: Return value of "OCA\FullTextSearch_Elasticsearch\Command\Configure::execute()" must be of the type int, "null" returned. in /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/apps/mail/vendor/symfony/console/Command/Command.php:266
Stack trace:
#0 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/core/Command/Base.php(169): Symfony\Component\Console\Command\Command->run()
#1 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/apps/mail/vendor/symfony/console/Application.php(920): OC\Core\Command\Base->run()
#2 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/apps/mail/vendor/symfony/console/Application.php(266): Symfony\Component\Console\Application->doRunCommand()
#3 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/apps/mail/vendor/symfony/console/Application.php(142): Symfony\Component\Console\Application->doRun()
#4 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/lib/private/Console/Application.php(215): Symfony\Component\Console\Application->run()
#5 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/console.php(100): OC\Console\Application->run()
#6 /ubos/http/sites/s7febb0b4cd348d86f95b47eb8b1292e220460321/next/occ(11): require_once('/ubos/http/site...')
#7 {main}
```
Looking at the stack trace, it appears that when attempting to configure `fulltextsearch_elasticsearch` somehow `mail` code is being invoked. This code path, obviously, doesn't exist when `mail` is not installed, and so it works fine when then.

I don't understand the internal mechanics enough to have a guess as to why this might be happening, and I cannot tell whether this might be a problem with `mail`, `fulltextsearch_elasticsearch` or the server core itself, so I decided to report this here.

**Comment by acsfer** [comment]
What do you think @ChristophWurst ? Is this a `mail` stuff?

**Comment by ChristophWurst** [comment]
Mail might make this problem more obvious, but it's up to the elastic search APP to stay compatible with Nextcloud. This change was documted at https://docs.nextcloud.com/server/latest/developer_manual/app_publishing_maintenance/upgrade-guide.html#symfony-update. All commands have to return an int. This will also fail without Mail in upcoming versions of Nextcloud when we upgrade Symfony further.

**Comment by jernst** [comment]
The thing that confuses me is that when I configure `fulltextsearch_elasticsearch`, some `mail` code gets invoked. What business does `mail` have in the configuration of `fulltextsearch_elasticsearch`?

**Comment by ChristophWurst** [comment]
> What business does `mail` have in the configuration of `fulltextsearch_elasticsearch`

None. It's a simple dependency conflict. Mail unintentionally ships its own version of the Symfony console and the autoloader picks up the one from Mail instead of server because that is how php behaves.

That is why I said even without Mail this will break as soon as Symfony is also updated in Nextcloud server. This breaking change was documented well for the previous major release of Nextcloud.

**Comment by jernst** [comment]
Filed as separate issue https://github.com/nextcloud/mail/issues/4342.

Might make sense to have some kind of "conforms to the rules" process for the app store which checks for this kind of code duplication.

**Comment by ChristophWurst** [comment]
> Might make sense to have some kind of "conforms to the rules" process for the app store which checks for this kind of code duplication.

That doesn't help at all. It could be totally legit for an app to ship a dependency. Then it's confirm with Nextcloud. But what if another apps (also confirm) ships the same dependency in a slightly different version? This problem isn't solvable with php, sadly.

**Comment by jernst** [comment]
I didn't mean with php. Some kind of "lint" in the submission process into the app store.

**Comment by ChristophWurst** [comment]
Again, not really possible. You'd have to try every possible combination of Nextcloud apps out there. Apps might be fine in isolation but conflict with each other. Or conflict with Nextcloud server.

**Comment by szaimen** [comment]
Looks like this was fixed in both apps.
