### ISSUE TITLE
Upload size limited by Nginx configuration for shared links

### ISSUE THREAD

**Issue by klorydryk** [nextcloud/server#25043]
### Steps to reproduce
1. log-in
2. create a directory
3. Upload a big file (more than authorized by Nginx, like 5Go) -> it should work
3. share this directory via sharing link with upload right
4. open this link in a private browser session or another browser
5. Upload the same file -> it doesn't work with "unknown error" as Nextcloud notification

### Expected behaviour
It should work either in logged session and with the shared link

### Server configuration

**Operating system:**
debian

**Web server:**
Nginx

**Database:**
mysql

**PHP version:**
7.3.25

**Nextcloud version:** (see Nextcloud admin page)
20.0.2

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
-> No errors have been found.

**List of activated apps:**
<details>
<summary>App list</summary>
- Contact
- Calendar
- BigBlueButton
- Collabora online
- and obviously... File sharing, etc.
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
keycloack

### Client configuration
**Browser:**
Firefox opera Chrome Safari

**Operating system:**
Debian, MacOS

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No error in the Nextcloud log
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
The error in the webpage: "Une erreur inconnue est survenue" (unknown error)
</details>

a) The javascript console log
```
{…}
​
currentTarget: <input id="file_upload_start" class="hiddenuploadfield" type="file" name="files[]" multiple="multiple">
​
data: undefined
​
delegateTarget: <input id="file_upload_start" class="hiddenuploadfield" type="file" name="files[]" multiple="multiple">
​
handleObj: Object { type: "fileuploadfail", origType: "fileuploadfail", guid: 55, … }
​
isTrigger: 3
​
jQuery22409849321979658258: true
​
namespace: ""
​
result: undefined
​
rnamespace: null
​
target: <input id="file_upload_start" class="hiddenuploadfield" type="file" name="files[]" multiple="multiple">
​
timeStamp: 1610135896322
​
type: "fileuploadfail"
​
<prototype>: Object { constructor: Event(e, t), isDefaultPrevented: ue(), isSimulated: false, … }
 
Object { classes: {}, disabled: false, create: null, dropZone: {…}, replaceFileInput: true, singleFileUploads: true, limitMultiFileUploadSizeOverhead: 512, sequentialUploads: false, forceIframeTransport: false, multipart: false, … }
 undefined file-upload.js:1085:15
```

**Comment by szaimen** [comment]
Thank you for taking the time to report a bug! 👍

As this seems to be a setup issue I would like to ask you to raise your question in the forums: https://help.nextcloud.com 
If you wish support with setup issues from Nextcloud GmbH we offer this as part of the Nextcloud subscription. Learn more about this at https://nextcloud.com/enterprise/
