### ISSUE TITLE
The dashboard welcoming message should show the complete display name

### ISSUE THREAD

**Issue by sudwhiwdh** [nextcloud/server#25040]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
For example, if a display name contains a substring, neither the comma nor the display name is currently displayed.

### Actual behaviour
I would expect at least the selected display name to be shown, including the comma.

Although I wonder if the comma shouldn't be deleted and the whole string replaced by a format like "time of day + display name + exclamation mark". It's not a complete sentence otherwise.

### Server configuration

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.3

**Comment by simonspa** [comment]
I cannot reproduce this on NC 20.0.4. Setting user name to `Mar_cus, the test user!` will show the full name on the dashboard:

![image](https://user-images.githubusercontent.com/1677436/104591874-a1265500-566d-11eb-8818-87e2f4c78a4a.png)
