### ISSUE TITLE
Can't make share in external storage mounted by rclone

### ISSUE THREAD

**Issue by wodexiaobai322** [nextcloud/server#25052]
### Steps to reproduce
1.Use rclone to mount a storage
2.Create a external storage(local,usable for everyone),pointing to the storage mounted by rclone,enable sharing
3.Admin tries to make sharing any files(or folders)

### Expected behaviour
Sharing works well

### Actual behaviour
It shows 'Unable to load the shares list'.It seems that nextcloud opens the file in a fault directory(nextcloud/data/user/files/xxx),but the correct directory is in (nextcloud/xxx).Viewing or downloading files is OK,and sharing files out the external storage is also working fine.

### Server configuration

**Operating system:
Debian 8.7

**Web server:
nginx 1.12.2

**Database:
mysql 5.6.38

**PHP version:
php7.2.32

**Nextcloud version:
v20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:
Fresh install

**Where did you install Nextcloud from:
Downloaded from offical website

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => 'xxx',
  'passwordsalt' => 'xxx',
  'secret' => 'xxx',
  'trusted_domains' =>
  array (
      0 => 'xxx',
      1 => 'xxx',
      2 => 'xxx'
  ),
  'datadirectory' => '/data/wwwroot/nextcloud/data',
  'dbtype' => 'mysql',
'version' => '20.0.4.0', 'overwrite.cli.url' => 'https://xxx', 'dbname' => 'nextcloud', 'dbhost' => 'localhost:3306', 'dbport' => '', 'dbtableprefix' => 'oc_', 'dbuser' => 'oc_wodexiaobai31', 'dbpassword' => 'xxx', 'installed' => true, ); 
```
</details>

**Are you using external storage, if yes which one:
local

**Are you using encryption:
no

**Are you using an external user-backend, if yes which one:
no

### Client configuration
**Browser:chrome/firefox

**Operating system:windows10/android10

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2021/01/01 00:10:00 [notice] 24596#0: signal process started
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
ErrorPHP2021-01-03T23:08:57+0800
Error: imagecreatefromstring(): Empty string or invalid image at /data/wwwroot/nextcloud/lib/private/legacy/OC_Image.php#624
ErrorPHP2021-01-03T23:08:57+0800
Error: file_get_contents(/data/wwwroot/nextcloud/data/wodexiaobai322/files/rclone/Amatsukaze/README.png): failed to open stream: No such file or directory at /data/wwwroot/nextcloud/lib/private/Files/Storage/Local.php#272
ErrorPHP2021-01-03T23:08:57+0800
Error: exif_imagetype(): Read error! at /data/wwwroot/nextcloud/lib/private/legacy/OC_Image.php#547
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by szaimen** [comment]
Hi there, it looks like you didn't run `occ files:scan --all` after mounting the external storage. Please do that and report back if it fixes this issue. Thanks!
