### ISSUE TITLE
order of apps in the menu bar is changed after updating an app

### ISSUE THREAD

**Issue by j-ed** [nextcloud/server#25058]
### Actual behavior
The app order in the menu bar is changed after an app update has been forced. As soon as you leave the app menu, the menu bar is refreshed an all apps are shown in the configured order (AppOrder app!) again.

### Expected behavior
The app order in the menu bar should be changed if you force an app update.

### Steps to reproduce
1. Open the Nextcloud web GUI.
   -> The app order is displayed correctly ✅ 

   ![20210109_nc_menubar_01](https://user-images.githubusercontent.com/2572764/104128606-e9d9c780-5368-11eb-84a8-f13a51f949da.png)

2. Select the Apps menu to administer all installed apps.
   -> The app order is displayed correctly ✅ 
   
   ![20210109_nc_menubar_02_apps_menu_opened](https://user-images.githubusercontent.com/2572764/104128641-29a0af00-5369-11eb-9289-d5d2bf1d1c3f.png)

3. Select an app for which an update is available and press the update button.
   -> The app is updated and the app order is displayed in a different order ❎ 

   ![20210109_nc_menubar_03_apps_menu_after_app_update](https://user-images.githubusercontent.com/2572764/104128672-4937d780-5369-11eb-98a3-9f54d9431899.png)

4. Leave the Apps menu and return to the main view.
   -> The app order is displayed correctly again ✅ (See point 1.)

#### Server Configuration
OS: Linux 4.9.245
Web server: Apache2 2.4.46
Database: MariaDB 10.3.23
PHP version: 7.4.11
Nextcloud version: 20.0.4
Additional apps: **AppOrder v0.11.0**

#### Client Configuration
Browser: Mozilla Firefox 84.0.2
Operating system: Windows 10

**Comment by szaimen** [comment]
I can reproduce this on NC21.0.2
cc @juliushaertl does this need to be fixed in the apporder app or in the server repository?

**Comment by juliushaertl** [comment]
Yes, something for app order, though with the current way the app hijacks the app icons i don't see a way to resolve that. But let's move it there.

**Comment by juliushaertl** [comment]
There is already one so closing in favor of https://github.com/juliushaertl/apporder/issues/79
