### ISSUE TITLE
Confusing share dialog

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#25067]
When I want to share a file with my colleague I get this option in the share dialog:

![image](https://user-images.githubusercontent.com/14975046/122911367-82806480-d357-11eb-8af0-096ebaff3861.png)

Five options and I'm more or less lost. 

The first one is probably the right one because it also shows his avatar and status. But the email address below could also indicate that it is a share by mail even that the envelop icon on the right is missing. And imagine he wouldn't have a custom avatar. Than it would be even harder to guess.

What about the second option, what is this?

Option 3 is the real share by mail than. But maybe we shouldn't offer it at all if the user has a internal account?

Option 4 is a federated share, right? But again, why offering it if it would go back to the same instance (cloud.nextcloud.com)? And maybe we could also have a icon for it on the right?

Option 5 is the one-to-one chat with him. But again you need to know a lot about Nextcloud in order to get it. Maybe there should be some explanation text on hover.

I was really lost and at the end decided to just quickly send the file by mail.

Before I tried the web interface I wanted to share the file on the desktop. There it is even more confusing:

![image](https://user-images.githubusercontent.com/14975046/122911497-a6dc4100-d357-11eb-8c3b-05031f695b66.png)

My gut feeling would tell me that option 1 and 3 has something to do with email, so skip it.
"(conversation)" indicates the Talk room share relatively nicely. At least when I know Talk and that I can share directly to room I get it

At the end I got stuck with option 2 and 5 and wondered if one of those might be the right one....

I didn't tested the mobile clients but I could imagine that I would have had similar issues. Maybe @tobiasKaminsky and @marinofaggiana can double check it.

cc @nextcloud/designers 
cc @nextcloud/desktop

**Comment by Spartachetto** [comment]
Maybe related to #4643 ?

**Comment by wiswedel** [comment]
related: https://github.com/nextcloud/calendar/issues/2685

**Comment by szaimen** [comment]
I think this was improved with https://github.com/nextcloud/server/pull/26550

**Comment by szaimen** [comment]
So for me it looks like this is resolve don NC22 beta 5:
![image](https://user-images.githubusercontent.com/42591237/122910984-1a318300-d357-11eb-8f0e-ba1fcb20cd64.png)
