### ISSUE TITLE
Allow to register instances of IAlternativeLogin

### ISSUE THREAD

**Issue by zorn-v** [nextcloud/server#25060]
In social login app may be many alternative logins with no determined parameters or even names, so it is impossible to just create "class" for all providers.

**Comment by ChristophWurst** [comment]
could you point me to the code please?

the problem with *objects* (class instances) as opposed to class names is that objects are very heavy and the registration happens on *every single request* while the alternative login is only required for any request that actually handles login, right?

I'm wondering if it would be possible to register a proxy class that then delegates to your real implementations …

**Comment by zorn-v** [comment]
I did not find a way to dynamic pass parameters in "container". I get all alternative logins from app settings so it is not "static" (known) info. 
Check https://github.com/zorn-v/nextcloud-social-login/blob/dc76af81d44b10eca273f04ae35b1993d2e1fe10/lib/AppInfo/Application.php#L91-L95

**Comment by zorn-v** [comment]
> that objects are very heavy and the registration happens on every single request 

In my case I do it only on login page.

**Comment by zorn-v** [comment]
> objects are very heavy

Really ? 1-10 more SIMPLE objects ? Lazy loading is for REALLY heavy objects/instances.
PHP 7 is not so stupid as you think )

**Comment by zorn-v** [comment]
Anyway this feature used only by me and registration app. 
I did not concoct in mind how it may compromise nextcloud. 
If you install app, it has full access in any way.
