### ISSUE TITLE
Unknown error occured

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#25072]
Hi! I've set up limitation in nginx: 
`client_max_body_size 10G`
Everything is fine, users cannot upload files >10Gb. But if they are trying, they see abstract message `Unknown error occurred`. Is it possible to show them notification like `Upload error - file XYZ is too large, max size is 10GB` instead of error? 
I understand, that nextcloud cannot directly read this value from nginx config, but, may be, it can be set through nextcloud's config? 

There is one way I see: remove this parameter from nginx config and put it into php config `upload_max_filesize`. Than nextcloud could be able to read this value and print it in any messages to users.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
