### ISSUE TITLE
Talk: DeadlockException

### ISSUE THREAD

**Issue by svseidel** [nextcloud/server#25075]
### Setup

* Nextcloud 20.0.4
* custom coturn-sever
* Talk App 
* Ubuntu 18.04, PHP 7.2.24
* MariaDB 10.4.17; `SELECT @@GLOBAL.tx_isolation, @@tx_isolation;` gives

> +-----------------------+----------------+
> | @@GLOBAL.tx_isolation | @@tx_isolation |
> +-----------------------+----------------+
> | READ-COMMITTED        | READ-COMMITTED |
> +-----------------------+----------------+

### Problem
I receive an error message, while having a voice call (no video) with more then 8-10 users:

> Doctrine\DBAL\Exception\DeadlockException: An exception occurred while executing 'UPDATE `oc_talk_participants` SET `last_ping` = ? WHERE (`user_id` = ?) AND (`session_id` = ?) AND (`room_id` = ?)' with params [1610366995, "…", "…", 39]: SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction

Then users randomly have to reconnect to the call (if possible).

I have searched a lot and found similar issues but not quite the same (e. g. files app). The most given answer referirng to the transaction isolation level does not work. Is there a fix?

**Comment by simonspa** [comment]
This has been reported already here: https://github.com/nextcloud/spreed/issues/4093
