### ISSUE TITLE
Tag filter: Slideshow doesn't respect filter

### ISSUE THREAD

**Issue by niko** [nextcloud/server#25082]
### Steps to reproduce

1. Go to the Files -> Tags view
2. Filter for a tag that's present on some images. You'll see images with this tag. 
3. Click on an image. You'll see the slideshow view of that image.
4. Use the arrow navigation of the slideshow.

### Expected behaviour
Only see images with the selected tag.

### Actual behaviour
See images without the selected tag, too.

### Server configuration

I'm so sorry I don't have access to the admin page as I'm using a hosted nextcloud instance. Is there any way I can find this information as a user?

**List of activated apps:**
<details>
* Files
* Tasks
* Photos
* E-Mail
* Calendar
* Activity
* Bookmarks
* Notes
* Deck
* Talk
* Surveys
* Forms
</details>

**Comment by kesselb** [comment]
cc @skjnldsv sounds like viewer? ;)

**Comment by niko** [comment]
Oh, sorry. It really seems to be the viewer. I didn't realize the viewer is a separate project. Should I open this bug there?

**Comment by niko** [comment]
Turns out it's a duplicate to https://github.com/nextcloud/viewer/issues/390
