### ISSUE TITLE
Searching with shared folders

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#25083]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Shared folders with thousands of files are nearly impossible to search through. You can organize by name but it's not efficient.

**Describe the solution you'd like**

Either:

A) A search box

or

B) Load all files at once instead of scrolling and waiting for more to appear. This way the user can search through their web browsers search function.

**Comment by SimplyCorbett** [comment]
Example:

https://my.filerot.com/s/jXSf39AiG44JYt6

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
