### ISSUE TITLE
smb fails, if at least one dir exists without permission (+ a performance gap, which may trigger the problem)

### ISSUE THREAD

**Issue by sh-dvl** [nextcloud/server#25081]
nextcloud 20.0.4: even with "preview disabled" on the external-storage all entries in the share are opened once (and closed immediately), which is a big performance-gap and if there is any directory without read-permission, the whole access is canceled, leaving an empty window with no files shown.

changing permission on the directory makes it work again (even with the performance-gap mentioned above)

well, if there's any access-restriction on any files/directories, at least all others should be shown normally and if there's no reason to open a file/directory, it shouldn't be done...

if you need further information/traces or similar, please specify, how to get it, because currently I've not the power to go deeper into it on myself.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by sh-dvl** [comment]
sorry, can't check this, because an update to 21.0.3 broke my nextcloud, so I've to repair it now.
(first it claimed to faild access memcache/APCu, then after disabling this for the moment, it segfaults...)
