### ISSUE TITLE
SSO-set displayname cannot be changed from Nextcloud nor user backend

### ISSUE THREAD

**Issue by Perdex** [nextcloud/server#25097]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

1. Set up SSO login with SSO/SAML backend, with displayname mapped to givenName
2. Log in to Nextcloud with user, whose givenName is "My old name"
3. Change name in the LDAP backend to "My new name"
4. Go to account settings --> "Full name" (AKA displayname) is still "My old name"
5. The "Full name" cannot be changed here either by the user, nor in admin users list

### Expected behaviour
The displayname (*NOT* username which most issues refer to) should either
- Update when updated in the LDAP backend
- Be editable in Nextcloud

### Actual behaviour
Name cannot be changed

### Server configuration

**Operating system:** Ubuntu

**Web server:** apache

**Database:** mysql

**PHP version:** 7.2.24-0

**Nextcloud version:** 20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated automatically by Snap for a couple years

**Where did you install Nextcloud from:** Snap

**Signing status:**

```
No errors have been found.
```

**List of activated apps:**
<details>
<summary>App list</summary>

```
  - accessibility: 1.6.0
  - activity: 2.13.4
  - breezedark: 20.0.2
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - drawio: 0.9.8
  - event_update_notification: 1.2.0
  - external: 3.7.1
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_markdown: 2.3.1
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_readmemd: 1.2.0
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.1
  - files_texteditor: 2.14.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - impersonate: 1.7.0
  - integration_gitlab: 0.0.9
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - metadata: 0.12.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - polls: 1.6.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - rainloop: 7.0.3
  - recommendations: 0.8.0
  - richdocuments: 3.7.11
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - theming: 1.11.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.9.0
  - user_saml: 3.3.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - whiteboard: 0.0.3
  - workflow_pdf_converter: 1.5.0
  - workflowengine: 2.2.0
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** saml / ldap

**Comment by Perdex** [comment]
Update: on the next day the name has changed to what was set in the backend. So this seems to be a caching issue. However there is no info on it, so could there be a way to manually refresh the cache?

**Comment by schiessle** [comment]
It updates the next time you login because only during login the IDP tells Nextcloud the value of the parameters.
