### ISSUE TITLE
Nextcloud Icon keep defaulting to the dashabord icon

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#25099]
Hello, even if you setup a custom  favicon, logo, header logo what happens is if you save it under your tool bar to any browser 
is keep retains the logo that you saved or the default that nextcloud uses but once you login and it send you the the dashboard fav icon changes to the default dashboard icon with the circle not only if you save it under your fav but even most recent websites visited it wont show the default nextcloud icon or your custom icon it shows the below icon. 

![image](https://user-images.githubusercontent.com/59488153/104360042-152df500-54d6-11eb-9a87-d869105e8ec3.png)

Nextcloud  20.0.4
PHP Version: 7.4.3
MySQL 8.0.22

libapache2-mod-php7.4                           install
php-apcu                                        install
php-apcu-bc                                     install
php-common                                      install
php-igbinary                                    install
php-imagick                                     install
php-ldap                                        install
php-mysql                                       install
php-redis                                       install
php7.4-bcmath                                   install
php7.4-cli                                      install
php7.4-common                                   install
php7.4-curl                                     install
php7.4-gd                                       install
php7.4-gmp                                      install
php7.4-intl                                     install
php7.4-json                                     install
php7.4-ldap                                     install
php7.4-mbstring                                 install
php7.4-mysql                                    install
php7.4-opcache                                  install
php7.4-readline                                 install
php7.4-xml                                      install
php7.4-zip                                      install

**Comment by axheli** [comment]
Looks like when installing libmagickcore-6.q16-3-extra or libmagickcore-6.q16-6-extra it starts to show the logo that i showed in the first comment once i removed libmagickcore-6.q16-3-extra or libmagickcore-6.q16-6-extra the normal logos came back. not sure if this helps.

**Comment by andyxheli** [comment]
dup of #27502

**Comment by dR3b** [comment]
Please add `libmagickcore-6.q16-6-extra` to the Docker image!
