### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by ne20002** [nextcloud/server#25095]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

I have an error in the logfile when displaying meta data for quicktime mov file:

### Steps to reproduce
In files browser, select mov file, display side bar, display meta data. No error shown in UI, but log entry.

### Expected behaviour
No log entry

### Actual behaviour
[PHP] Error: Error: Undefined index: gps_longitude at /var/www/nextcloud/apps/metadata/lib/GetID3/AudioVideo/getid3_quicktime.php#152 at <<closure>>

 0. /var/www/nextcloud/apps/metadata/lib/GetID3/AudioVideo/getid3_quicktime.php line 152
    OC\Log\ErrorHandler::onError(8, "Undefined index: gps_longitude", "/var/www/nextcl ... p", 152, {info: {GETID3_V ... 3})
 1. /var/www/nextcloud/apps/metadata/lib/GetID3/getID3.php line 636
    OCA\Metadata\GetID3\AudioVideo\getid3_quicktime->Analyze()
 2. /var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php line 125
    OCA\Metadata\GetID3\getID3->analyze("/mnt/usbdrive/n ... v")
 3. /var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php line 47
    OCA\Metadata\Service\MetadataService->readId3("/mnt/usbdrive/n ... v")
 4. /var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php line 24
    OCA\Metadata\Service\MetadataService->getMetadata("/Photos/2021/01 ... v")
 5. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
    OCA\Metadata\Controller\MetadataController->get("/Photos/2021/01 ... v")
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Metadata\Con ... {}, "get")
 7. /var/www/nextcloud/lib/private/AppFramework/App.php line 152
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Metadata\Con ... {}, "get")
 8. /var/www/nextcloud/lib/private/Route/Router.php line 308
    OC\AppFramework\App::main("OCA\\Metadata\\ ... r", "get", OC\AppFramework\ ... {}, {action: null,_r ... "})
 9. /var/www/nextcloud/lib/base.php line 1008
    OC\Route\Router->match("/apps/metadata/get")
10. /var/www/nextcloud/index.php line 37
    OC::handleRequest()

GET /index.php/apps/metadata/get?source=%2FPhotos%2F2021%2F01%2F21-01-07+14-16-20+7013.mov
from fd42:0:0:41::383 by ag at 2021-01-12T14:48:16+00:00

### Server configuration

**Operating system:**
Raspbian OS buster
**Web server:**
Apache 2.4
**Database:**
MariaDB
**PHP version:**
php7.3-fpm
**Nextcloud version:** (see Nextcloud admin page)
20.0.4.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated
**Where did you install Nextcloud from:**

**Comment by kesselb** [comment]
> /var/www/nextcloud/apps/metadata

apps = directory where apps installed
metadata = name of the app

Report the problem to: https://github.com/gino0631/nextcloud-metadata
