### ISSUE TITLE
20.0.4 cannot set user quota to 0 B

### ISSUE THREAD

**Issue by neeral85** [nextcloud/server#25094]
### Steps to reproduce
1. set user quota to 0 B (e.g if quota is based on folder and user should not have any right to upload data elsewhere)

### Expected behaviour
before user quota was set to 0 Byte

### Actual behaviour
Error

{"reqId":"X-2xaY3U5PkA3TR66E-SGAAAAAQ","level":3,"time":"2021-01-12T15:25:45+01:00","remoteAddr":"172.17.10.10","user":"bigboss","app":"no app in context","method":"PUT","url":"/ocs/v2.php/cloud/users/bigboss","message":{"Exception":"Exception","Message":"Argument 1 passed to OC\\EventDispatcher\\ServiceEventListener::__invoke() must be an instance of OCP\\EventDispatcher\\Event, instance of OC\\EventDispatcher\\GenericEventWrapper given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264","Code":0,"Trace":[{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"editUser"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","editUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"userId":"bigboss","_route":"ocs.provisioning_api.Users.editUser"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/bigboss"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\EventDispatcher\\ServiceEventListener::__invoke() must be an instance of OCP\\EventDispatcher\\Event, instance of OC\\EventDispatcher\\GenericEventWrapper given, called in /var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264","Code":0,"Trace":[{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->","args":[{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"},"OCP\\IUser::changeUser",{"__class__":"Symfony\\Component\\EventDispatcher\\EventDispatcher"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"OCP\\IUser::changeUser",{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"}]},{"file":"/var/www/nextcloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[[{"__class__":"Closure"},{"__class__":"Closure"}],"OCP\\IUser::changeUser",{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"}]},{"file":"/var/www/nextcloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":85,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->","args":[{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"},{"__class__":"OC\\EventDispatcher\\GenericEventWrapper"}]},{"file":"/var/www/nextcloud/lib/private/User/User.php","line":497,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->","args":["OCP\\IUser::changeUser",{"__class__":"Symfony\\Component\\EventDispatcher\\GenericEvent"}]},{"file":"/var/www/nextcloud/lib/private/User/User.php","line":440,"function":"triggerChange","class":"OC\\User\\User","type":"->",**"args":["quota","0 B","1 B"**]},{"file":"/var/www/nextcloud/apps/provisioning_api/lib/Controller/UsersController.php","line":555,"function":"setQuota","class":"OC\\User\\User","type":"->","args":["0 B"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"editUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->","args":["bigboss","quota","0 B"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"editUser"]},{"file":"/var/www/nextcloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->","args":[{"__class__":"OCA\\Provisioning_API\\Controller\\UsersController"},"editUser"]},{"file":"/var/www/nextcloud/lib/private/Route/Router.php","line":308,"function":"main","class":"OC\\AppFramework\\App","type":"::","args":["OCA\\Provisioning_API\\Controller\\UsersController","editUser",{"__class__":"OC\\AppFramework\\DependencyInjection\\DIContainer"},{"action":null,"userId":"bigboss","_route":"ocs.provisioning_api.Users.editUser"}]},{"file":"/var/www/nextcloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->","args":["/ocsapp/cloud/users/bigboss"]},{"file":"/var/www/nextcloud/ocs/v2.php","line":24,"args":["/var/www/nextcloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/EventDispatcher/ServiceEventListener.php","Line":63},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0","version":"20.0.4.0","id":"****"}

PHP version: 7.2
Nextcloud version: 20.0.4

**Comment by marcojarjour** [comment]
Maybe related to this https://github.com/nextcloud/server/issues/25056 ?

**Comment by neeral85** [comment]
fixed with 20.0.5
