### ISSUE TITLE
Device not wiped if fail2ban is used as described in Hardening and security guidance

### ISSUE THREAD

**Issue by ne20002** [nextcloud/server#25096]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Install nextcloud with fail2ban according to nextcloud documentation 'Hardening and security guidance'.
Try to wipe a device

### Expected behaviour
Device will be wiped

### Actual behaviour
Device is not wiped, instead, a number of login errors occur and device is banned by fail2ban.

### Server configuration

**Operating system:**
Raspbian OS buster
**Web server:**
Apache 2.4
**Database:**
MariaDb
**PHP version:**
php7.3-fpm
**Nextcloud version:** (see Nextcloud admin page)
20.0.4.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
updated

**Comment by szaimen** [comment]
> Try to wipe a device

Only applications that have implemented this feature will be wiped but access should be revoked nonetheless. What was the remote application?
