### ISSUE TITLE
Error when upgrading ONLYOFFICE 6.2.0 on NextCloud 19.0.3

### ISSUE THREAD

**Issue by off41** [nextcloud/server#25106]
Hello,

I asked ONLYOFFICE upgrade 6.0.2 on NEXTCLOUD 19.0.3
When the upgrade run there is this error

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_onlyoffice_filekey ADD PRIMARY KEY (`id`)': SQLSTATE[42S02]: Base table or view not found: 1932 Table 'nextcloud.oc_onlyoffice_filekey' doesn't exist in engine

Could you help me please or is there a solution to stop upgrading because when I'm connecting to nextcloud portal it always ask me to run upgrade

![image](https://user-images.githubusercontent.com/77382848/104434385-749a0c80-558b-11eb-81ba-9b60c38090e0.png)
![image](https://user-images.githubusercontent.com/77382848/104434466-8976a000-558b-11eb-920e-e2109b69e083.png)

Regards

**Comment by acsfer** [comment]
You should ask at https://github.com/ONLYOFFICE/onlyoffice-nextcloud not here as this is the SERVER repo. Thanks 👍
