### ISSUE TITLE
Dashboard weather time display 

### ISSUE THREAD

**Issue by axheli** [nextcloud/server#25100]
It would be nice to see the weather on the dashbaord sync with the local time or dont even have the time there it dosent make sense that it says 32.7 F Clear sky at 5:00 PM the current time is 1:34PM so it should say  32.7 F Clean sky at 1:34PM or just remove the time and only get frequent updates on the weather 

![image](https://user-images.githubusercontent.com/59488153/104363303-99827700-54da-11eb-8d11-7ff7977facf4.png)

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/23399
