### ISSUE TITLE
Upgrade NC 10.0.1 to 11 beta 2: Incorrect schema migration on Postgres (9.6)

### ISSUE THREAD

**Issue by umgfoin** [nextcloud/server#2510]
### Steps to reproduce
1. Upgrading NC from 10.0.1 to 11 beta 2
2. sudo -u www_nc php occ upgrade
3. upgrade succeeds - no error reported
4. nc-mainpage login not possible due to wrong table definition in oc_authtoken

### Expected behaviour
Datatype of column "oc_authtoken.remember" should be 'boolean' after this upgrade.

### Actual behaviour
Datatype is 'smallint' thus not accepting INSERTs of data expressions "false" or "true" (There's no default cast in Postgres from 'boolean' to 'smallint').

Manually correcting the datatype to 'boolean' fixes the problem.

### Server configuration
**Operating system**:
CentOS 6

**Web server:**
Nginx/Apache

**Database:**
PostgreSQL 9.6.1

**PHP version:**
7.0.13

**Nextcloud version:** (see Nextcloud admin page)
11 beta 2

**Updated from an older Nextcloud/ownCloud or fresh install:**
10.0.1

**Where did you install Nextcloud from:**
ZIP-Archive

bg,
umgfoin.

**Comment by MorrisJobke** [comment]
@umgfoin Thanks for the report - we fixed this with #2428 and it will be available via the next pre-release of Nextcloud
