### ISSUE TITLE
[20.04] error with nginx listening unix domain socket

### ISSUE THREAD

**Issue by kirin10000** [nextcloud/server#25118]
HI.
I'm using `Haproxy <------ unix domain socket ------> Nginx <------  unix domain socket ------> php-fpm`.
1.The Nginx configure is same as  https://docs.nextcloud.com/server/20/admin_manual/installation/nginx.html , but turn off tls and set
```
listen unix:xxx;
listen unix:xxx http2;
```
2.The Haproxy set listening port 443 with https. and unix fallback to nginx.

When I open nextcloud first, I can set my admin name and password. Then when I flash it,  It say `
INTERNAL SERVER ERROR` with IP : `unix:`. 
When I change `Haproxy <------ unix domain socket ------> Nginx` to `Haproxy <------ tcp ------> Nginx` . It is OK.

I try to change the nginx config file. from
```
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;

        fastcgi_param modHeadersAvailable true;         # Avoid sending the security headers twice
        fastcgi_param front_controller_active true;     # Enable pretty urls
        fastcgi_pass php-handler;

        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }
```
to
```
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;

        try_files $fastcgi_script_name =404;

        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $path_info;
        fastcgi_param HTTPS on;

        fastcgi_param modHeadersAvailable true;         # Avoid sending the security headers twice
        fastcgi_param front_controller_active true;     # Enable pretty urls
        fastcgi_param REMOTE_ADDR 127.0.0.1;
        fastcgi_pass php-handler;

        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }
```
That is , I add `fastcgi_param REMOTE_ADDR 127.0.0.1;` . And it seems to be OK using `Haproxy <------ unix domain socket ------> Nginx`

**Comment by simonspa** [comment]
Do I understand correctly, that

a) you solved your problem
b) it is not related to Nextcloud (what this repo is about) but your infrastructure?

**Comment by kirin10000** [comment]
> Do I understand correctly, that
> 
Sorry. My english is not good. I'm from China.(May be I should use a translater)

> a) you solved your problem

Yes. I temporarily solved the problem. But I think this should not occur. So I think this is a bug.

> b) it is not related to Nextcloud (what this repo is about) but your infrastructure?

The nextcloud's php file use $_SERVER['REMOTE_ADDR']; to get the IP. When the IP is `unix:`, then nextcloud can't work. When the ip is `127.0.0.1`,or other ipv4, it work. so I think it is related to nextcloud

**Comment by szaimen** [comment]
Hi there, does this issue still happen with NC21.0.2 and the correct haproxy and nginx configuration?
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/reverse_proxy_configuration.html#haproxy
https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html

**Comment by kirin10000** [comment]
Thanks for your work.
I am bussy recently. I will take time to try. I took a look at it. The haproxy can work in two mode, tcp mode and http mode. I'm using it on the tcp mode(It only decrypt then send the data to nginx without any process), so it can't send the real ip to nginx through `X-Forwarded-For`. And I think it is not necessary for me to let nextcloud get the real client ip, I'm caring about effectiveness more than safety in my application.

And then I want to say some thing about `https://docs.nextcloud.com/server/stable/admin_manual/installation/nginx.html`, when using haproxy forword, the nginx configure like this:
```
        location = /.well-known/carddav { return 301 /remote.php/dav/; }
        location = /.well-known/caldav  { return 301 /remote.php/dav/; }
```
should change to
```
        location = /.well-known/carddav { return 301 https://$host/remote.php/dav/; }
        location = /.well-known/caldav  { return 301 https://$host/remote.php/dav/; }
```
. if not change ,it will return `http://$host/remote.php/dav/`, and this will make waring in the nextcloud checking(in the nextcloud admin page).

**Comment by kirin10000** [comment]
this is my nginx configure now, I have used it for a long time, seen very good:
```
server {
    listen unix:/var/run/haproxy/default.sock;
    listen unix:/var/run/haproxy/http2.sock http2;
    server_name cloud.example.com;
    client_max_body_size 512M;
    fastcgi_buffers 64 4K;
    gzip on;
    gzip_vary on;
    gzip_comp_level 4;
    gzip_min_length 256;
    gzip_proxied expired no-cache no-store private no_last_modified no_etag auth;
    gzip_types application/atom+xml application/javascript application/json application/ld+json application/manifest+json application/rss+xml application/vnd.geo+json application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/bmp image/svg+xml image/x-icon text/cache-manifest text/css text/plain text/vcard text/vnd.rim.location.xloc text/vtt text/x-component text/x-cross-domain-policy;
    add_header Referrer-Policy                      "no-referrer"   always;
    add_header X-Content-Type-Options               "nosniff"       always;
    add_header X-Download-Options                   "noopen"        always;
    add_header X-Frame-Options                      "SAMEORIGIN"    always;
    add_header X-Permitted-Cross-Domain-Policies    "none"          always;
    add_header X-Robots-Tag                         "none"          always;
    add_header X-XSS-Protection                     "1; mode=block" always;
    fastcgi_hide_header X-Powered-By;
    root /var/www/nextcloud;
    index index.php index.html /index.php$request_uri;
    location = / {
        if ( $http_user_agent ~ ^DavClnt ) {
            return 302 https://$host/remote.php/webdav/$is_args$args;
        }
    }
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location ^~ /.well-known {
        location = /.well-known/carddav { return 301 https://$host/remote.php/dav/; }
        location = /.well-known/caldav  { return 301 https://$host/remote.php/dav/; }
        location /.well-known/acme-challenge    { try_files $uri $uri/ =404; }
        location /.well-known/pki-validation    { try_files $uri $uri/ =404; }
        return 301 https://$host/index.php$request_uri;
    }
    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)(?:$|/)  { return 404; }
    location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console)                { return 404; }
    location ~ \.php(?:$|/) {
        fastcgi_split_path_info ^(.+?\.php)(/.*)$;
        set $path_info $fastcgi_path_info;
        try_files $fastcgi_script_name =404;
        include fastcgi.conf;
        fastcgi_param PATH_INFO $path_info;

        # fix the $_SERVER['REMOTE_ADDR'] problen
        fastcgi_param REMOTE_ADDR 127.0.0.1;
        fastcgi_param SERVER_PORT 443;

        fastcgi_param HTTPS on;
        fastcgi_param modHeadersAvailable true;
        fastcgi_param front_controller_active true;
        fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
        fastcgi_intercept_errors on;
        fastcgi_request_buffering off;
    }
    location ~ \.(?:css|js|svg|gif)$ {
        try_files $uri /index.php$request_uri;
        expires 6M;
        access_log off;
    }
    location ~ \.woff2?$ {
        try_files $uri /index.php$request_uri;
        expires 7d;
        access_log off;
    }
    location /remote {
        return 301 https://$host/remote.php$request_uri;
    }
    location / {
        try_files $uri $uri/ /index.php$request_uri;
    }
}
```

**Comment by szaimen** [comment]
Thanks but I am not sure if this issue is a bug report or enhancement idea for the documentation. 
Could you please clarify this? 
Thanks!

**Comment by kirin10000** [comment]
yep, it is an enhancement idea for the documentation may be better

**Comment by simonspa** [comment]
Great, thanks for the quick response, @kirin10000 ! I'm closing this issue then - would you mind adding your documentation suggestion (maybe as a pull request) to the documentation https://github.com/nextcloud/documentation/tree/master/admin_manual ? Thanks! :)

**Comment by kirin10000** [comment]
@simonspa 
No problem
