### ISSUE TITLE
xml mime type failed with application/octet-stream

### ISSUE THREAD

**Issue by blivanu-dev** [nextcloud/server#25115]
### Steps to reproduce
1. Create a flow that will deny the custom mime type application/octet-stream
2. Upload a xml file
3. Try to access (preview) xml file you will get file not found error

### Expected behaviour

file can be access(preview)

### Actual behaviour

any xml files are seen as application/octet-stream (in nextcloud MariaDB files are seen as type 149 - application/xml)

### Server configuration

**Operating system**:
CentOS Linux release 8.2.2004 (Core) 
**Web server:**
httpd-2.4.37-21
**Database:**
mariadb-server-10.3.17-1
**PHP version:**
php-fpm-7.4.9-1
**Nextcloud version:** (see Nextcloud admin page)
19.0.3 (but test with all 19.0.x)
**Where did you install Nextcloud from:**
official page
**Signing status:**

No errors have been found.

**List of activated apps:**

Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.0
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - federation: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.1
  - files_pdfviewer: 1.8.0
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - firstrunwizard: 2.8.0
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - nextcloud_announcements: 1.8.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - recommendations: 0.7.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - support: 1.2.1
  - survey_client: 1.7.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - user_ldap

**Nextcloud configuration:**

{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "test.blivanu.ro"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "19.0.3.1",
        "overwrite.cli.url": "https:\/\/test.blivanu.ro",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "has_internet_connection": false,
        "data-fingerprint": "f6c34a326dd0f5fb00ba53189d6aafb9",
        "loglevel": 2,
        "maintenance": false,
        "theme": ""
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
### Client configuration
**Browser:**
any (ie , edge,chrome,firefox)
**Operating system:**
windows , linux
#### Nextcloud log (data/owncloud.log)
```

{"reqId":"X2HfH9F5ma4c3wsgN-CekwAAAMo","level":3,"time":"2020-09-16T09:47:12+00:00","remoteAddr":"10.65.137.4","user":"user-suceava","app":"no app in context","method":"GET","url":"/remote.php/webdav/test/demo.xml","message":{"Exception":"Symfony\\Component\\Routing\\Exception\\RouteNotFoundException","Message":"Unable to generate a URL for the named route \"photos.page.index\" as such route does not exist.","Code":0,"Trace":[{"file":"/var/www/html/nextcloud/lib/private/Route/Router.php","line":338,"function":"generate","class":"Symfony\\Component\\Routing\\Generator\\UrlGenerator","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/URLGenerator.php","line":83,"function":"generate","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/NavigationManager.php","line":294,"function":"linkToRoute","class":"OC\\URLGenerator","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/NavigationManager.php","line":115,"function":"init","class":"OC\\NavigationManager","type":"->"},{"file":"/var/www/html/nextcloud/apps/theming/lib/ThemingDefaults.php","line":183,"function":"getAll","class":"OC\\NavigationManager","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_Defaults.php","line":263,"function":"getShortFooter","class":"OCA\\Theming\\ThemingDefaults","type":"->"},{"file":"/var/www/html/nextcloud/lib/public/Defaults.php","line":169,"function":"getLongFooter","class":"OC_Defaults","type":"->"},{"file":"/var/www/html/nextcloud/core/templates/layout.guest.php","line":55,"function":"getLongFooter","class":"OCP\\Defaults","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/Template/Base.php","line":178,"args":["/var/www/html/nextcloud/core/templates/layout.guest.php"],"function":"include"},{"file":"/var/www/html/nextcloud/lib/private/Template/Base.php","line":150,"function":"load","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_Template.php","line":182,"function":"fetchPage","class":"OC\\Template\\Base","type":"->"},{"file":"/var/www/html/nextcloud/lib/private/legacy/OC_Template.php","line":213,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Files/BrowserErrorPagePlugin.php","line":109,"function":"fetchPage","class":"OC_Template","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/lib/Files/BrowserErrorPagePlugin.php","line":86,"function":"generateBody","class":"OCA\\DAV\\Files\\BrowserErrorPagePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php","line":89,"function":"logException","class":"OCA\\DAV\\Files\\BrowserErrorPagePlugin","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":254,"function":"emit","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php","line":319,"function":"start","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php","line":82,"function":"exec","class":"Sabre\\DAV\\Server","type":"->"},{"file":"/var/www/html/nextcloud/remote.php","line":167,"args":["/var/www/html/nextcloud/apps/dav/appinfo/v1/webdav.php"],"function":"require_once"}],"File":"/var/www/html/nextcloud/3rdparty/symfony/routing/Generator/UrlGenerator.php","Line":143,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.18363","version":"19.0.3.1"}


#### Browser log
```

demo.xml:1 GET https://test.blivanu.ro/remote.php/webdav/test/demo.xml 404 (Not Found)
demo.xml:29 Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-AHz3B65iWD0y/1DhE4/mk7Mdz0ZY2DG8GH4gYyjj6no='), or a nonce ('nonce-...') is required to enable inline execution.

jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
get @ globals.js:92
(anonymous) @ backgroundjobs.js?v=dddfe408-0:23
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
get @ globals.js:92
(anonymous) @ searchprovider.js?v=dddfe408-0:413
session-heartbeat.js:97 session heartbeat polling started
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
get @ globals.js:92
(anonymous) @ backgroundjobs.js?v=dddfe408-0:24
c @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
get @ globals.js:92
(anonymous) @ backgroundjobs.js?v=dddfe408-0:26
c @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
get @ globals.js:92
(anonymous) @ searchprovider.js?v=dddfe408-0:414
c @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
globals.js:61 $ is deprecated: The global jQuery is deprecated. It will be updated to v2.4 in Nextcloud 20 and v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
$ @ globals.js:61
get @ globals.js:92
(anonymous) @ searchprovider.js?v=dddfe408-0:415
c @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433
jquery.js:8630 GET https://test.blivanu.ro/remote.php/webdav/test/cron.php 404 (Not Found)
send @ jquery.js:8630
ajax @ jquery.js:8166
m.each.m.<computed> @ jquery.js:8311
(anonymous) @ backgroundjobs.js?v=dddfe408-0:24
c @ jquery.js:3099
fireWith @ jquery.js:3211
ready @ jquery.js:3417
P @ jquery.js:3433

**Comment by blizzz** [comment]
Transfered to server, because there is where the mimetype detections happens.

I cannot reproduce wrong detection of them. 

What does `select * from oc_mimetypes` report for you?
