### ISSUE TITLE
Notifications from past events are not automatically dismissed

### ISSUE THREAD

**Issue by RafalLukawiecki** [nextcloud/server#25111]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Expected behaviour
Events from the past should not generate reminder notifications in the future, and definitely not every hour.

### Actual behaviour
Desktop app continues to issue reminder notifications for events from the past. The notification text clearly states that the event was "2 hours ago" etc. There is no way to dismiss them to stop them from coming back.

The user's dashboard on the server also shows the events from the past, eg:

<img width="347" alt="Screenshot 2021-01-13 at 11 12 11" src="https://user-images.githubusercontent.com/22912705/104445501-15d79180-5591-11eb-953b-b04a6a56f0f1.png">

### Steps to reproduce
1. Create an event in Nextcloud Calendar using iOS Apple Calendar app using default settings.
2. Wait till the event time or date passes.
3. Make sure Nextcloud macOS app is running.
4. Within the next hour, and then again every hour, a notification will be generated by the Nextcloud desktop app reminding you about the event from the past.
5. To stop this, you need to delete the event. Removing reminders from the event sometimes helps but the only way to be sure is to delete the event itself.

### Client configuration
Client version:

Nextcloud Desktop Client Version 3.1.1 (macOS)

Operating system:
macOS Catalina 10.15.7

OS language:
English

Installation path of client:
/Applications/nextcloud

### Server configuration

Nextcloud version: 20.0.4

### Logs

I will submit relevant logs if and when someone decides to debug this issue.

**Comment by nickvergessen** [comment]
They can be expired on rendering by the provider.just throw an `OCP\Notifications\AlreadyProcessedException`

**Comment by RafalLukawiecki** [comment]
Thank you @nickvergessen and @tcitworld for taking this up. From end-user perspective the notification that the app generates is prominent enough to warrant no further re-notifications. If the end user wishes this notification to be even more prominent there are options both in iOS and macOS to persist the notifications from Nextcloud app until dismissed. Normally, however, I would not expect notifications to keep recurring once they have been served.

It sounds to my novice ears that expiring them on rendering makes sense.
