### ISSUE TITLE
Migrate from Nextcloud internal auth to LDAP

### ISSUE THREAD

**Issue by viggy96** [nextcloud/server#25113]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I'm very frustrated by the lack of the ability to migrate users from Nextcloud's internal authentication to something external, like LDAP. 

**Describe the solution you'd like**
Nextcloud should map existing users to LDAP when LDAP is configured. Perhaps there could be an extra checkbox in the LDAP settings that would force Nextcloud to map existing users to matching ones in LDAP. Also, it should map local groups to matching ones in LDAP. Currently, Nextcloud will show internal groups and LDAP groups separately, even though they are named the same. For example, I see two admin groups, one from Nextcloud, another from LDAP. 

**Describe alternatives you've considered**
I have seen posts like this one: https://help.nextcloud.com/t/migration-to-ldap-keeping-users-and-data/13205
on the Nextcloud forum, but in my opinion, that does not represent a real solution. Telling production users to run various database commands isn't a solution, its a downright pain. I can't imagine that there hasn't been anyone who wanted to do exactly this before. I see many posts on this very subject on the forum.

**Comment by spychodelics** [comment]
I am currently trying the same. 
I have about 50 Users in NC locally and i try to connect NC to my AD LDAP Server. 
To not to touch NC in production mode, i made a fresh test install of NC 20. 
Added 10 of my Users local and 20 users in ldap (10 same as local, 10 new, with different (local/ldap)) passwords.
Connection to LDAP stands, i can connect to NC with LDAP credentials. 
I would also love to have some kind of an automap option.

**Comment by all-rounder-eng** [comment]
I also need LDAP authentication. It should be possible for an account to verify against an AD via switch instead of locally. With moodle you can easily set this for each user without mapping. I want to convert a NC instance with about 200 users. There are numerous shares and groups.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by Aquariu** [comment]
Dear all, (@szaimen  in particular),
As the [user_external app](https://github.com/nextcloud/user_external) is not seeing much action (well, it looks a bit abandonned to my inexperienced eyes) and Nextcloud 32 doing some [breaking change](https://github.com/nextcloud/user_external/issues/266). There might be a renewed interest for a safe way to switch existing users (in the Nextcloud users table) from the existing auth backend to **whatever else**.

Exemples:
- Switching my users from the IMAP backend I currently use to the LLDAP community container provided by nextcloud-aio. (and then switching my dovecot install from a mysql user table to lldap as well down the road but that's out of topic). <-- that's my personal use case.
- Switching my users from a xmpp backend to internal users and using the future auth provider function by Nextcloud 32 as a central auth authority.
- ...

I'd be willing to test things/scripts/SQL commands to that effect. (currently on Nextcloud 31)

Kind regards,
Olivier

**Comment by Aquariu** [comment]
Dear all, as NC31 is the last that works correctly with the (abandonned?) user_external app, it would be a good idea to collectively write a nice little "how to convert your users to LDAP". I can test proposals/methods on a test instance.

Currently, with NC31, the last available user_external and a working lldap container (provided by aio) I can safetly create new users that only work with ldap, but I need to map those users with their old (email) login to that they keep their apps' histories, etc...
