### ISSUE TITLE
API - inconsistencies between POST user and PUT user

### ISSUE THREAD

**Issue by guillemfondin** [nextcloud/server#25125]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I've a client who consume nexcloud API to create and update nextcloud users based on users from an external service.
When I want POST a new user, to define the displayName, I use the key "displayName". But, if I want to update the user's displayName, I must send a PUT request with the key "displayname". It's an inconsistency that is the source of error...

**Describe the solution you'd like**
Change the PUT request key to "displayName" like the POST request.

**Describe alternatives you've considered**
Change the POST request key to "displayname" like the PUT request.

**Additional context**
Nothing

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
