### ISSUE TITLE
Manage group visibility

### ISSUE THREAD

**Issue by gildas-decadoudal** [nextcloud/server#25139]
We use technical groups to limit access of users to applications.
For example we have created a group HasCalendar which is assigned to application Calendar.
But this group is technic and irrelevant for users when it appears in search (every where in backend, but in talk android app too).

We suggest to allow admin to specifiy if a group is visible or not to users whose à not admin or admin of that group.

Maybe usage of the interface IHideFromCollaborationBackend could be suffisant or not.

**Comment by Baptistou** [comment]
Related issue : #19903

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/19903
