### ISSUE TITLE
20.0.5 - groups display at buttom "Keine Benutzer vorhanden" even if there are users

### ISSUE THREAD

**Issue by kinimodmeyer** [nextcloud/server#25133]
### Steps to reproduce
when i go through my user-groups at "https://xyz/index.php/settings/users" some groups show "Keine Benutzer vorhanden" at the bottom even when there are users in the groups.

### Expected behaviour
"Keine Benutzer vorhanden" should not be there.

### Actual behaviour
"Keine Benutzer vorhanden" get displayed at button even if there are users.

**Nextcloud version:** 20.0.5

**Comment by chiefbrain** [comment]
This message is also shown under users if there are more than 25 users thus only the first 25 users are shown.

**Comment by chiefbrain** [comment]
In 21.0.1, the message is still shown if there are less than 25 users in a group.

**Comment by CodeAlDente** [comment]
Same here, we do only have a couple of users (< 10) managed internally.

```json
Nextcloud
Version: 21.0.3

PHP
Version: 7.4.21

MySQL
Version: 10.3.30
```
