### ISSUE TITLE
You cannot disable/delete users

### ISSUE THREAD

**Issue by danielepercivaldi** [nextcloud/server#25134]
### Steps to reproduce
Go to "Users".
Try to delete or disable a user.

### Expected behaviour
The user is disabled/deleted

### Actual behaviour
The user is not disabled/deleted and the popup message "An error occured during the request. Unable to proceed." appears.

## Server configuration detail

**Operating system:** Linux 4.4.0-198-generic #230-Ubuntu SMP Sat Nov 28 01:30:29 UTC 2020 x86_64

**Webserver:** Apache/2.4.18 (Ubuntu) (apache2handler)

**Database:** mysql 5.7.32

**PHP version:** 

7.4.14
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, standard, sodium, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, enchant, mbstring, FFI, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, exif, mysqli, pdo_mysql, apc, posix, pspell, readline, redis, shmop, SimpleXML, sockets, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlrpc, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.5 - 20.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from NC 20.0.4

**Where did you install Nextcloud from:** From the official website

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - announcementcenter: 4.0.0
 - audioplayer: 3.0.0
 - audioplayer_editor: 0.3.0
 - audioplayer_sonos: 1.2.0
 - bruteforcesettings: 2.0.1
 - camerarawpreviews: 0.7.10
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contactsinteraction: 1.1.0
 - data_request: 1.7.0
 - dav: 1.16.2
 - drop_account: 1.0.1
 - extract: 1.3.0
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_automatedtagging: 1.10.1
 - files_downloadactivity: 1.9.0
 - files_external: 1.11.1
 - files_pdfviewer: 2.0.1
 - files_retention: 1.9.0
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_texteditor: 2.14.0
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextbackup: 20.9.0
 - nextcloud_announcements: 1.9.0
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - piwik: 0.7.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quota_warning: 1.9.1
 - ransomware_detection: 0.10.0
 - ransomware_protection: 1.8.0
 - registration: 0.6.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - sociallogin: 4.0.3
 - socialsharing_email: 2.1.0
 - socialsharing_facebook: 2.1.0
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - dashboard
 - encryption
 - recommendations
 - text
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "rdc.larivistadelcolore.com"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "overwrite.cli.url": "https:\/\/rdc.larivistadelcolore.com\/",
    "htaccess.RewriteBase": "\/",
    "dbtype": "mysql",
    "version": "20.0.5.2",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "logdateformat": "r",
    "logtimezone": "Europe\/Rome",
    "loglevel": 2,
    "forcessl": true,
    "forceSSLforSubdomains": true,
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "remember_login_cookie_lifetime": 1296000,
    "session_lifetime": 86400,
    "session_keepalive": true,
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379
    },
    "maintenance": false,
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\MarkDown",
        "OC\\Preview\\MSOfficeDoc",
        "OC\\Preview\\MSOffice2003",
        "OC\\Preview\\MSOffice2007",
        "OC\\Preview\\OpenDocument",
        "OC\\Preview\\StarOffice",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Epub",
        "OC\\Preview\\FB2",
        "OC\\Preview\\Illustrator",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\Postscript",
        "OC\\Preview\\SVG",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\Font"
    ],
    "trashbin_retention_obligation": "auto",
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "appstore.experimental.enabled": false,
    "updater.release.channel": "stable",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "25",
    "theme": "",
    "mail_sendmailmode": "smtp",
    "mysql.utf8mb4": true,
    "onlyoffice": {
        "jwt_header": "AuthorizationJwt"
    },
    "app_install_overwrite": [
        "drop_account"
    ],
    "updater.secret": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** sftp

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** No

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
85.36.215.178 - - [14/Jan/2021:18:01:30 +0100] "PUT /ocs/v2.php/cloud/users/a%20paloschi/disable HTTP/1.1" 404 1459 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36"
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"RAnofsQ2MhSqoXqYQA5M","level":3,"time":"Thu, 14 Jan 2021 17:39:03 +0100","remoteAddr":"85.36.215.178","user":"administrator","app":"no app in context","method":"PUT","url":"/ocs/v2.php/cloud/users/Adrian%20Soto/disable","message":{"Exception":"Exception","Message":"Argument 1 passed to OC\\EventDispatcher\\ServiceEventListener::__invoke() must be an instance of OCP\\EventDispatcher\\Event, instance of OC\\EventDispatcher\\GenericEventWrapper given, called in /var/www/owncloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264","Code":0,"Trace":[{"file":"/var/www/owncloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/owncloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/owncloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/owncloud/ocs/v2.php","line":24,"args":["/var/www/owncloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php","Line":110,"Previous":{"Exception":"TypeError","Message":"Argument 1 passed to OC\\EventDispatcher\\ServiceEventListener::__invoke() must be an instance of OCP\\EventDispatcher\\Event, instance of OC\\EventDispatcher\\GenericEventWrapper given, called in /var/www/owncloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php on line 264","Code":0,"Trace":[{"file":"/var/www/owncloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":264,"function":"__invoke","class":"OC\\EventDispatcher\\ServiceEventListener","type":"->"},{"file":"/var/www/owncloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":239,"function":"doDispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/owncloud/3rdparty/symfony/event-dispatcher/EventDispatcher.php","line":73,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/owncloud/lib/private/EventDispatcher/SymfonyAdapter.php","line":85,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"->"},{"file":"/var/www/owncloud/lib/private/User/User.php","line":497,"function":"dispatch","class":"OC\\EventDispatcher\\SymfonyAdapter","type":"->"},{"file":"/var/www/owncloud/lib/private/User/User.php","line":388,"function":"triggerChange","class":"OC\\User\\User","type":"->"},{"file":"/var/www/owncloud/apps/provisioning_api/lib/Controller/UsersController.php","line":712,"function":"setEnabled","class":"OC\\User\\User","type":"->"},{"file":"/var/www/owncloud/apps/provisioning_api/lib/Controller/UsersController.php","line":675,"function":"setEnabled","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php","line":169,"function":"disableUser","class":"OCA\\Provisioning_API\\Controller\\UsersController","type":"->"},{"file":"/var/www/owncloud/lib/private/AppFramework/Http/Dispatcher.php","line":100,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/owncloud/lib/private/AppFramework/App.php","line":152,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"/var/www/owncloud/lib/private/Route/Router.php","line":309,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"/var/www/owncloud/ocs/v1.php","line":88,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"/var/www/owncloud/ocs/v2.php","line":24,"args":["/var/www/owncloud/ocs/v1.php"],"function":"require_once"}],"File":"/var/www/owncloud/lib/private/EventDispatcher/ServiceEventListener.php","Line":63},"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36","version":"20.0.5.2"}
```
</details>

<details><summary>Browser log</summary>

No OC found
t.getLanguage @ index.js:46
jquery-migrate.min.js:2 JQMIGRATE: Migrate is installed, version 1.4.1
globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
4globals.js:60 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
2globals.js:60 jQuery is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
ie @ globals.js:60
4capabilities.js:32 OC.getCapabilities is deprecated and will be removed in Nextcloud 21. See @nextcloud/capabilities
getCapabilities @ capabilities.js:32
session-heartbeat.js:97 session heartbeat polling started
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
util.js:120 OC.Util.formatDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
formatDate @ util.js:120
util.js:130 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
relativeModifiedDate @ util.js:130
/ocs/v2.php/cloud/users/Adrian%20Soto/disable:1 Failed to load resource: the server responded with a status of 404 (Not Found)
index.js:43 Object Object
API_FAILURE @ index.js:43
</details>

**Comment by danielepercivaldi** [comment]
"Solved": I disabled https://framagit.org/framasoft/nextcloud/drop_account and everything has backed to working fine.

**Comment by kesselb** [comment]
cc @tcitworld

**Comment by tcitworld** [comment]
@danielepercivaldi This is https://framagit.org/framasoft/nextcloud/drop_account/-/issues/18 for reference
