### ISSUE TITLE
Downloading NextCloud doesn't work

### ISSUE THREAD

**Issue by DomWhite92** [nextcloud/server#25144]
Hello,

just wanted to say downloading NextCloud on this webpage doesn't work well:

https://nextcloud.com/install/

The download starts, but it never ends it.

Regards
DomWhite

**Comment by PVince81** [comment]
please try again, there were some load issues.

in my case it took about 20 minutes for downloading the zip

**Comment by kesselb** [comment]
It seems that operations are back to normal.
