### ISSUE TITLE
Update 20.0.4 to 20.0.5 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by Bandulf63** [nextcloud/server#25156]
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT DISTINCT(TABLE_NAME) AS `table` FROM INFORMATION_SCHEMA . COLUMNS WHERE TABLE_SCHEMA = ? AND (COLLATION_NAME <> 'utf8mb4_bin' OR CHARACTER_SET_NAME <> 'utf8mb4') AND TABLE_NAME LIKE 'oc_%'' with params ["nextclouddb"]: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
