### ISSUE TITLE
Playing MP4 videos without image when HTTP/2 is used via built-in player

### ISSUE THREAD

**Issue by colyro** [nextcloud/server#25154]
MP4 files are not playing when are opened by builtin media playere while they are accessed via HTTP/2 protocol from a windows10 with chrome/mozilla/internet explorer/edge.
If apache is configure for HTTP/1, then it works.

### Steps to reproduce
1. Configure Apache to use HTTP/2
2. upload an MP4 video
3. try to play it from a win10 with chrome/internet explorer via built in player

### Expected behaviour
The video should show picture and audio.

### Actual behaviour
Video has a black screen and only voice is playing

### Server configuration

**Operating system:**
CentOS Linux release 8.3.2011
**Web server:**
httpd-2.4.37-30.module_el8.3.0+561+97fdbbcc.x86_64
**Database:**
mariadb-server-10.3.27-3.module_el8.3.0+599+c587b2e7.x86_64
**PHP version:**
php-7.4.14-1.el8.remi.x86_64
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.5
**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded from a freshed install of NC 20.0.4
**Where did you install Nextcloud from:**
original website
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
File not found.

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - auto_groups: 1.2.0
  - bruteforcesettings: 2.0.1
  - caniupdate: 0.2.0
  - cloud_federation_api: 1.3.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - duplicatefinder: 0.0.4
  - end_to_end_encryption: 1.6.2
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - flowupload: 1.1.2
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - nextbackup: 20.9.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - calendar
  - comments
  - contacts
  - encryption
  - facerecognition
  - federation
  - files_external
  - firstrunwizard
  - gpxmotion
  - integration_onedrive
  - mail
  - richdocuments
  - sharebymail
  - spreed
  - user_ldap
  - user_status

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```

"system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.100.108",
            "dan.go.ro"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.5.2",
        "overwrite.cli.url": "http:\/\/192.168.100.108\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "app_install_overwrite": [
            "dropit",
            "files_external_gdrive",
            "caniupdate"
        ],
        "updater.release.channel": "stable",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "password": "***REMOVED SENSITIVE VALUE***",
            "timeout": 1.5
        },
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "theme": "",
        "loglevel": 2
    }
}

</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no
#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
chrome / internet explorer 11/edge
**Operating system:**
windows 10 pro 64bit
#### Web server error log
<details>
<summary>Web server error log</summary>

```
[Fri Jan 15 14:12:34.591799 2021] [autoindex:error] [pid 1799:tid 140422974252800] [client 209.17.96.106:35944] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Fri Jan 15 16:36:44.553339 2021] [proxy_fcgi:error] [pid 34697:tid 140214173431552] [client 45.155.205.108:42428] AH01071: Got error 'Primary script unknown'
[Fri Jan 15 16:36:46.267871 2021] [autoindex:error] [pid 34695:tid 140213334554368] [client 45.155.205.108:52832] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Fri Jan 15 18:30:26.626226 2021] [autoindex:error] [pid 34695:tid 140213326161664] [client 60.217.72.12:50248] AH01276: Cannot serve directory /var/www/html/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive
[Fri Jan 15 18:50:49.913055 2021] [proxy_fcgi:error] [pid 34697:tid 140215004825344] [client 188.25.154.180:61568] AH01071: Got error 'Primary script unknown'
[Fri Jan 15 18:51:42.725837 2021] [proxy_fcgi:error] [pid 34909:tid 140214979647232] [client 192.168.100.112:61575] AH01071: Got error 'Primary script unknown'
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"X-HPQqTu51FUWOl1WTNTAAAAAIE","level":2,"time":"2021-01-03T14:05:54+00:00","remoteAddr":"192.168.100.19","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":""}
{"reqId":"X-HPQqTu51FUWOl1WTNTAAAAAIE","level":2,"time":"2021-01-03T14:05:54+00:00","remoteAddr":"192.168.100.19","user":"--","app":"no app in context","method":"GET","url":"/nextcloud/","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":""}
{"reqId":"X-HPb7tXPJx39BHW1rW7pAAAAEA","level":2,"time":"2021-01-03T14:06:39+00:00","remoteAddr":"192.168.100.19","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in http:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":""}
{"reqId":"X-HPb7tXPJx39BHW1rW7pAAAAEA","level":2,"time":"2021-01-03T14:06:39+00:00","remoteAddr":"192.168.100.19","user":"--","app":"no app in context","method":"POST","url":"/nextcloud/index.php","message":"Could not detect any host in https:///nextcloud/data/htaccesstest.txt","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36","version":""}

```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by acsfer** [comment]
Can't reproduce it, with any of files at https://test-videos.co.uk/bigbuckbunny/mp4-h264

**Comment by colyro** [comment]
Seems that HEVC codec was missing on my win 10 browser. 
Strange that with http/1 was functioning on my mobile phone. 

I did not find anywhere in help docs of NC that this codec is needed in order to watch on win10 the videos with the builtin player. 
If there is anywhere specified this, then my bad. otherwise, please adapt the documentation as i saw other people having the same issue and reported it as a BUG.
thanks and may be close as it is not a BUG.
