### ISSUE TITLE
Group shared calendars missing (20.0.5)

### ISSUE THREAD

**Issue by derBobby** [nextcloud/server#25165]
### Steps to reproduce
0.) User A and User B are member of Group G
1.) User A has shared a calendar with group G
1a.) The shared calendar name contains a SPACE.
2.) User B can't see the shared calendar in the calendar web app 
3.) User B can't sync the shared calendar on his devices

### Expected behaviour
Group sharing of calendar should work
Group shared calendars should be visible for users shared with

### Actual behaviour
Group shared calendars are not visible / syncable

## Server configuration detail

**Operating system:** Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** hub.docker.com: mariadb:10.4.10-bionic

**PHP version:** 

7.4.14
Modules loaded: Core, date, libxml, openssl, pcre, sqlite3, zlib, ctype, curl, dom, fileinfo, filter, ftp, hash, iconv, json, mbstring, SPL, PDO, session, posix, Reflection, standard, SimpleXML, pdo_sqlite, Phar, tokenizer, xml, xmlreader, xmlwriter, mysqlnd, apache2handler, apcu, bcmath, exif, gd, gmp, imagick, intl, ldap, memcached, pcntl, pdo_mysql, pdo_pgsql, redis, sodium, zip, Zend OPcache

**Nextcloud version:** 20.0.5 - 20.0.5.2

**Updated from an older Nextcloud/ownCloud or fresh install:** 20.0.4

**Where did you install Nextcloud from:** hub.docker.com: nextcloud:20.0.5

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.3
 - documentserver_community: 0.1.8
 - drawio: 0.9.8
 - event_update_notification: 1.2.0
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - forms: 2.1.0
 - groupfolders: 8.2.0
 - impersonate: 1.7.0
 - issuetemplate: 0.7.0
 - keeweb: 0.6.4
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.2
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - onlyoffice: 6.2.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - previewgenerator: 3.1.0
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - registration: 0.6.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - spreed: 10.0.5
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "memcache.local": "\\OC\\Memcache\\APCu",
    "apps_paths": [
        {
            "path": "\/var\/www\/html\/apps",
            "url": "\/apps",
            "writable": false
        },
        {
            "path": "\/var\/www\/html\/custom_apps",
            "url": "\/custom_apps",
            "writable": true
        }
    ],
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": [
        "removed",
        "removed"
    ],
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.5.2",
    "overwrite.cli.url": "https:\/\/removed",
    "overwriteprotocol": "https",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "loglevel": 0,
    "mail_sendmailmode": "smtp",
    "mail_smtpmode": "smtp",
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "tls",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpdebug": false,
    "mail_smtptimeout": 10,
    "maintenance": false,
    "allow_user_to_change_display_name": false,
    "auth.bruteforce.protection.enabled": true,
    "trashbin_retention_obligation": "730, auto",
    "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
    "forwarded_for_headers": [
        "HTTP_X_FORWARDED_FOR",
        "X-Real-IP"
    ],
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "theme": "",
    "app_install_overwrite": [
        "keeweb"
    ]
}
```
</details>

**Are you using external storage, if yes which one:** NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

## Client configuration

**Browser:** Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0

**Operating system:** Windows 10

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```

```
</details>

<details><summary>Browser log</summary>

</details>

**Comment by derBobby** [comment]
might be related to #25165

**Comment by nursoda** [comment]
Same issue here. No changes except for the core update.

In one case I could work around the issue by unsharing and resharing the calendar.

In another case on the same inscance when doing so it _seemed_ (from the result in the actual sharing dialog) that it succeeded but a reload of calendar showed that the shared-to group vanishes from the list. So again: When I enter the sharing user's calendar, I see that the calendar is shared to the group. I delete that sharing. I re-add it (and see that it "is"). Then reload the web page and it's gone.

I can reliably share to users though. So in some cases it may be a (cumbersome) workaround to temporarily share to affected users directly.

**Comment by nursoda** [comment]
> might be related to #25165

self-ref – I guess you meant another issue?

**Comment by derBobby** [comment]
Thank you. Updated.

**Comment by jmechnich** [comment]
In our case this issue is restricted to groups containing a whitespace in their name. Another user reports similar problems when an umlaut is used. I can confirm that this issue exists since we upgraded to 20.0.5 on Friday evening.

**Comment by derBobby** [comment]
Thank you @jmechnich !

Do you know if it is enough to rename to group in the UI or would it be necessary to rename the gid?

```
MariaDB [nextcloud]> select * from groups;
+------------------+------------------+
| gid              | displayname      |
+------------------+------------------+
...
+------------------+------------------+
```

**Comment by jmechnich** [comment]
> Do you know if it is enough to rename to group in the UI or would it be necessary to rename the gid?

Is this even possible via the UI? :D
I have only seen a trash symbol so far...

At this point I am still trying to avoid modifying the database directly. The `groups` table is not the only one where the gid seems to come into play (e.g. `dav_shares`).

**Comment by jmechnich** [comment]
There was a merged pull request related to DAV shares and URL de-/encoding which might be related: https://github.com/nextcloud/server/commit/25143fc87b814df93405e6de6ce18434de4f8bde

**Comment by jmechnich** [comment]
> There was a merged pull request related to DAV shares and URL de-/encoding which might be related: [25143fc](https://github.com/nextcloud/server/commit/25143fc87b814df93405e6de6ce18434de4f8bde)

After reverting those changes things seem to be working properly on my test server. Still a bit reluctant to implement them on our production machine as there might be side effects.

**Comment by jmechnich** [comment]
I can confirm that reverting https://github.com/nextcloud/server/commit/25143fc87b814df93405e6de6ce18434de4f8bde also fixes the issue on our production machine.

**Comment by tflidd** [comment]
So, this is related to PR https://github.com/nextcloud/server/pull/24515

@blizzz worked on that...

**Comment by derBobby** [comment]
Updated the whitespace hint to my initial post.

@jmechnich 
Thank you, I appreciate your analysis! :-) Is the rollback to the old file safe?

**Comment by regenpfeifer** [comment]
Same issue here, c.f.: https://help.nextcloud.com/t/probleme-mit-kalender-freigabe/104490
Calendars are not shareable to groups containing a SPACE. Existing shares to such groups have disappeared.

**Comment by jmechnich** [comment]
> @jmechnich
> Thank you, I appreciate your analysis! :-) Is the rollback to the old file safe?

@derBobby It should be quite safe in my opinion but would still advise you to create a backup of your cloud... ;)

**Comment by JB1985** [comment]
Does this [patch](https://github.com/nextcloud/server/commit/25143fc87b814df93405e6de6ce18434de4f8bde) fix the problem? Has anyone tested that?

**Comment by simonspa** [comment]
@JB1985 if I understand the issue correctly then the patch you referring to is the cause, not the remedy of this. The patch you linked has been included in 20.0.5, which is the version from which on users experience this problem.

**Comment by JB1985** [comment]
Then the solution should be to take the files from 2.0.4?!

apps/dav/lib/CalDAV/CalDavBackend.php 
apps/dav/lib/CardDAV/CardDavBackend.php
apps/dav/lib/DAV/GroupPrincipalBackend.php 
apps/dav/lib/DAV/Sharing/Backend.php

Has anyone tested that?

**Comment by jmechnich** [comment]
@JB1985 https://github.com/nextcloud/server/issues/25165#issuecomment-761617302

**Comment by k00ni** [comment]
Is the root cause maybe also responsible for https://github.com/nextcloud/contacts/issues/2023?

I have the same behavior for address books. If target group contains a white space, a share can be created but users of the group don't see it.

**Comment by jmechnich** [comment]
> Is the root cause maybe also responsible for [nextcloud/contacts#2023](https://github.com/nextcloud/contacts/issues/2023)?
> 
> I have the same behavior for address books. If target group contains a white space, a share can be created but users of the group don't see it.

@k00ni  That is very likely the case.

**Comment by kevinkk525** [comment]
fix a bug and create 2 more..
How about releasing a hotfix version?

**Comment by manu-p** [comment]
Same issue for us without any space characters in group names: "salariés" and "bénévoles"...

**Comment by nursoda** [comment]
> Same issue for us without any space characters in group names: "salariés" and "bénévoles"...

In my case "…ä…" I was able to un-share and re-share, that fixed it. As long as there are no space chars. If there are, it's not saved or displayed/used after re-sharing. Might be a quick and easy workaround.

**Comment by etr999** [comment]
I do not recommend this workaround for unexperienced or very scared people! 
Anyway, it worked in our case ;)
Make a backup of your database (at least the tables mentionned below)
Enabel nextcloud maintainance mode.

If you have access to your nextcloud database, you can rename/transliterate the critical field contents.  

AFAIK the DAV-sharing stuff is spread over 3 tables: 

oc_groups
oc_dav_shares
oc_group_user

Replacing the spaces with underscores solved the problem:

<sql>
update oc_groups SET gid = REPLACE(gid,' ','_');
update oc_dav_shares SET principaluri = REPLACE(principaluri,' ','_');
update oc_group_user SET gid = REPLACE(gid,' ','_');
</sql>

Replace space with any arbitrary "critical" character.

Watch out and have fun!

**Comment by blizzz** [comment]
How old where those calendar shares, i.e. when did you create them?  I failed to do so in 20.0.4.

**Comment by nursoda** [comment]
> How old where those calendar shares, i.e. when did you create them? I failed to do so in 20.0.4.

In my case NC19.0.x or NC20.0.x

**Comment by jmechnich** [comment]
> How old where those calendar shares, i.e. when did you create them? I failed to do so in 20.0.4.

@blizzz Not very recently (some of them older than 2 years).

**Comment by manu-p** [comment]
@blizzz same as @jmechnich for us, at least in 18.x

**Comment by kevinkk525** [comment]
my instance is so old, it was owncloud once.. does that mean I have to be careful and test each minor update before updating my production instance?? Nextcloud should learn how to do proper automated testing of their code to detect errors like that.

**Comment by mklemme1** [comment]
@ kevinkk525 We also recently migrated from OC.
I fixed the issue by

**Comment by blizzz** [comment]
Sounds like there were changes on the way. I'll investigate this.

**Comment by JB1985** [comment]
> @kevinkk525 We also recently migrated from OC.
> 
> I fixed the issue by replacing the 4 files as described by @JB1985 yesterday.


Yes it works!

**Comment by blizzz** [comment]
> Sounds like there were changes on the way. I'll investigate this.

Okay, I tested with group names containing semicolon, question mark, slash, ampersand, hash, and arrow brackets. Kind of mean to have boring whitespaces as party pooper 🤦‍

The issue is that before 20.0.5 the uri of the shared calendar was saved unencoded. Spaces stay spaces and umlauts stay umlauts, while it  failed to create the share of the group id contained one of the afore mentioned characters.

The underlying problem her is that principal uris in the dav share table were saved un-uri-encoded (if they made it this far). There was an old "fix" that just compared them in this style. 

The solution is going to be to repair these entries. Delicate.

**Comment by k00ni** [comment]
For what its worth, Nextcloud showed me group names with white spaces like: `Foo%2bBar` in the share setting (whereas `%2b` is the white space).

**Comment by jmechnich** [comment]
> For what its worth, Nextcloud showed me group names with white spaces like `Foo%2bBar` in the share setting (whereas `%2b` is the white space).

But that's kind of weird, as %2b is a + sign. Could it be that urlencode (" " -> "+") and rawurlencode (" " -> "%20") are used inconsistently?

**Comment by JB1985** [comment]
> 
> The solution is going to be to repair these entries. Delicate.

How shall this be understood?

Does that mean users have to find a solution or will there be a fix?

**Comment by blizzz** [comment]
> > The solution is going to be to repair these entries. Delicate.
> 
> How shall this be understood? @blizzz
> 
> Does that mean users have to find a solution or will there be a fix?

Of course we'll have to fix it. I looked into  this extensively today but the whole topic is a little bit bigger than this. But this issue uncovered it. Finding a good way to repair the entries is what I am working on.

**Comment by blizzz** [comment]
For now as a workaround you can apply this patch: 

```diff
diff --git a/apps/dav/lib/CalDAV/CalDavBackend.php b/apps/dav/lib/CalDAV/CalDavBackend.php
index ea1a30c629..21f570ffce 100644
--- a/apps/dav/lib/CalDAV/CalDavBackend.php
+++ b/apps/dav/lib/CalDAV/CalDavBackend.php
@@ -346,6 +346,9 @@ class CalDavBackend extends AbstractBackend implements SyncSupport, Subscription
        $principals = $this->principalBackend->getGroupMembership($principalUriOriginal, true);
        $principals = array_merge($principals, $this->principalBackend->getCircleMembership($principalUriOriginal));
 
+       foreach ($principals as $principal) {
+           $principals[] = urldecode($principal);
+       }
        $principals[] = $principalUri;
 
        $fields = array_values($this->propertyMap);
diff --git a/apps/dav/lib/CardDAV/CardDavBackend.php b/apps/dav/lib/CardDAV/CardDavBackend.php
index d5c3609695..2946b9dd34 100644
--- a/apps/dav/lib/CardDAV/CardDavBackend.php
+++ b/apps/dav/lib/CardDAV/CardDavBackend.php
@@ -192,6 +192,9 @@ class CardDavBackend implements BackendInterface, SyncSupport {
        $principals = $this->principalBackend->getGroupMembership($principalUriOriginal, true);
        $principals = array_merge($principals, $this->principalBackend->getCircleMembership($principalUriOriginal));
 
+       foreach ($principals as $principal) {
+           $principals[] = urldecode($principal);
+       }
        $principals[] = $principalUri;
 
        $query = $this->db->getQueryBuilder();
```

Basically it adds those three lines in two files each. No changes in the database.

The principal is then tested against group principals as they are fetched and decoded. There is the theoretical danger that a user will get access to shares to a group they are not member of – when you have group names at the same time that would be identical after decoding. For example:

* Friends & Family
* Friends+%26+Family

Both must exists and have different users.

**Comment by k00ni** [comment]
Thank you @blizzz. You wrote:

> The principal is then tested against group principals as they are fetched and decoded. **There is the theoretical danger that a user will get access to shares to a group they are not member of** – when you have group names at the same time that would be identical after decoding.

Does that mean, that there is more code to come or does your code fix the problem entirely?

**Comment by blizzz** [comment]
> Thank you @blizzz. You wrote:
> 
> > The principal is then tested against group principals as they are fetched and decoded. **There is the theoretical danger that a user will get access to shares to a group they are not member of** – when you have group names at the same time that would be identical after decoding.
> 
> Does that mean, that there is more code to come or does your code fix the problem entirely?

This is rather a hotfix you can apply right now.

**Comment by RafalLukawiecki** [comment]
I can add that in addition to calendars, none of our users can see any group-shared reminders/task lists either. This happened after update to 20.0.5.

All our group names have a space in them. Group names were created when the initial Nextcloud was installed, the last 18 release. Server was then regularly updated, through 19 and 20, and everything worked well till 20.0.4.

This is a major inconvenience as it prevents collaboration since no one can see each other’s tasks and calendars, something essential to our daily workflow.

**Comment by wscheicher** [comment]
> For now as a workaround you can apply this patch:
> [...]

Hmm ... i'm on 20.0.5 and this change didn't seem to help. Is this supposed to fix existing shares? Would this also cover if the group in question is a ldap group? ("Domain Users")

**Comment by RafalLukawiecki** [comment]
The comment from the [workaround above](https://github.com/nextcloud/server/issues/25165#issuecomment-764943233) is important, thank you for sharing it @blizzz

> There is the theoretical danger that a user will get access to shares to a group they are not member of – when you have group names at the same time that would be identical after decoding. For example:
> 
> * Friends & Family
> * Friends+%26+Family
> 
> Both must exists and have different users.

I would be concerned that this creates opportunity for intentional attacks. Someone could arrange to have multiple groups with specially chosen characters, and all would be granted access whilst only one of them should have been. This would be a notifiable vulnerability, and it needs to be avoided. A security principal must not resolve to more identities than the one it is defined for. I hope a fix to this problem is possible without causing such issues.

I suspect any solution would need to take care of older principals that have spaces etc in their names and either force a conversion with the significant negative side-effect of breaking any other apps that relied on them, or deal with the "version" of the principal by checking its creation date. In general, this is a case for versioning of the security principal to avoid exactly such issues in the future, and to reconsider using display names as the underlying principals—but it may be too late for such a NC-wide decision...

**Comment by RafalLukawiecki** [comment]
The [workaround](https://github.com/nextcloud/server/issues/25165#issuecomment-762140026) from @JB1985 has worked for me.

> Then the solution should be to take the files from 2.0.4?!
> 
> apps/dav/lib/CalDAV/CalDavBackend.php
> apps/dav/lib/CardDAV/CardDavBackend.php
> apps/dav/lib/DAV/GroupPrincipalBackend.php
> apps/dav/lib/DAV/Sharing/Backend.php
> 
> Has anyone tested that?

However, if you have tried re-sharing a calendar (or task list) whilst in v20.0.5, perhaps while troubleshooting, then that calendar will not appear for the group members. You need to share it again, using the same name etc, and then it will reappear for the group members. Calendars which I have not touched while troubleshooting have just reappeared after putting those files back without any further action. Thank you @JB1985.

**Comment by blizzz** [comment]
> The comment from the [workaround above](https://github.com/nextcloud/server/issues/25165#issuecomment-764943233) is important, thank you for sharing it @blizzz
> 
> > There is the theoretical danger that a user will get access to shares to a group they are not member of – when you have group names at the same time that would be identical after decoding. For example:
> > 
> > * Friends & Family
> > * Friends+%26+Family
> > 
> > Both must exists and have different users.
> 
> I would be concerned that this creates opportunity for intentional attacks. Someone could arrange to have multiple groups with specially chosen characters, and all would be granted access whilst only one of them should have been. This would be a notifiable vulnerability, and it needs to be avoided. A security principal must not resolve to more identities than the one it is defined for. I hope a fix to this problem is possible without causing such issues.

The groups have to exist and the calendar (or address book) have to be shared with it. All in all I think it is more a hypothetical risk. Group creation is limited to admins. Admins don't need hacks like these.

But anyways, that's why I pointed it out.

> I suspect any solution would need to take care of older principals that have spaces etc in their names and either force a conversion with the significant negative side-effect of breaking any other apps that relied on them

That's goes all via the DAV app and API, no direct DB access. It should not lead to breakage of other apps.

> or deal with the "version" of the principal by checking its creation date. In general, this is a case for versioning of the security principal to avoid exactly such issues in the future, and to reconsider using display names as the underlying principals—but it may be too late for such a NC-wide decision...

Currently it's only stored which resources was shared to which principal.

**Comment by blizzz** [comment]
> > For now as a workaround you can apply this patch:
> > [...]
> 
> Hmm ... i'm on 20.0.5 and this change didn't seem to help. Is this supposed to fix existing shares? Would this also cover if the group in question is a ldap group? ("Domain Users")

Yes. How does its `principaluri` in `SELECT * FROM oc_dav_shares` look like? `principals/groups/Domain Users`?

**Comment by wscheicher** [comment]
> Yes. How does its `principaluri` in `SELECT * FROM oc_dav_shares` look like? `principals/groups/Domain Users`?

Hmm - no, this is missing. And the share is now not in the webinterface anymore (and recreating the entry vanishes on page reload)

**Comment by blizzz** [comment]
> > Yes. How does its `principaluri` in `SELECT * FROM oc_dav_shares` look like? `principals/groups/Domain Users`?
> 
> Hmm - no, this is missing. And the share is now not in the webinterface anymore (and recreating the entry vanishes on page reload)

None of this code would remove existing shares.

**Comment by tims-adb** [comment]
Last night came the update to NC 20.0.6 and I can confirm the problem persists. 

Temporary workaround: Manually replacing the files from 20.0.4 again did it for us:
apps/dav/lib/CalDAV/CalDavBackend.php
apps/dav/lib/CardDAV/CardDavBackend.php
apps/dav/lib/DAV/GroupPrincipalBackend.php
apps/dav/lib/DAV/Sharing/Backend.php

**Comment by JB1985** [comment]
> Last night came the update to NC 20.0.6 and I can confirm the problem persists.

Why is a new version released and this issue not resolved? This bug affects a lot of users.

I think this will be a never-ending story. I don't think the problem will be fixed.

@blizzz pls replace the 4 Files for 20.0.7  until a solution to the problem is found.

**Comment by nursoda** [comment]
Before I update to 20.0.6: In certain cases (like umlauts) it helped to remove and re-add a calendar share. Will updating to 20.0.6 reinstate the issue, so that I have to re- "remove&re-add" after the upgrade?

**Comment by manu-p** [comment]
On my side, after updating to 20.0.6, no group shared calendars/contacts again.
Just replaced the 4 php files with the previously patched ones and it was ok.
No need to re-share any calendar/contacts.

**Comment by blizzz** [comment]
> Before I update to 20.0.6: In certain cases (like umlauts) it helped to remove and re-add a calendar share. Will updating to 20.0.6 reinstate the issue, so that I have to re- "remove&re-add" after the upgrade?

Recreated and newly created shares in 20.0.5 remain intact.

**Comment by fenvarien** [comment]
Sharing calendars with a group is quite important. Why ist 20.0.6 released without a proper fix for this issue?

**Comment by julian70400** [comment]
> Then the solution should be to take the files from 2.0.4?!
> 
> apps/dav/lib/CalDAV/CalDavBackend.php
> apps/dav/lib/CardDAV/CardDavBackend.php
> apps/dav/lib/DAV/GroupPrincipalBackend.php
> apps/dav/lib/DAV/Sharing/Backend.php
> 
> Has anyone tested that?

It works like a charm, thanks dude !

**Comment by k00ni** [comment]
@blizzz Thank you for your work. After looking into the PR, can I assume this fix is part of the next minor release for 20.x? Is it fixing my broken shares or do I have to re-create all of them manually?

**Comment by simonspa** [comment]
It is scheduled for 20.0.8 and will repair existing shares.

**Comment by mtippmann** [comment]
fwiw applied https://github.com/nextcloud/server/pull/25448 manually against 20.0.7 and ran the repair-script but it didn't work - only reverting to 20.0.4 files worked.

**Comment by k00ni** [comment]
> fwiw applied #25448 manually against 20.0.7 and ran the repair-script **but it didn't work** - only reverting to 20.0.4 files worked.

@mtippmann thank you for the feedback. Can someone else pleae confirm that?

**Comment by MegaS0ra** [comment]
Hi,
Using Nextcloud 20.0.7
Just extracted the following files from a Nextcloud 20.0.4 zip and copy/paste to my working Nextcloud :
apps/dav/lib/CalDAV/CalDavBackend.php
apps/dav/lib/CardDAV/CardDavBackend.php
apps/dav/lib/DAV/GroupPrincipalBackend.php
apps/dav/lib/DAV/Sharing/Backend.php

And it works !
I can now share calendars with groups that have spaces in their name.

**Comment by nursoda** [comment]
I could share a calendar to a group with spaces with 20.0.7 also, without modifying these files.

**Comment by MegaS0ra** [comment]
> I could share a calendar to a group with spaces with 20.0.7 also, without modifying these files.

Sorry if it does not correspond to the original issue, I was sent here from #17610 
and the workaround of replacing the files fixed it for me.

**Comment by jmechnich** [comment]
Apparently this is still not resolved. I just upgraded from 20.0.5 to 20.0.7 and the group calendars vanished again, so I restored the previous state of the above mentioned file.

Could we maybe get a recipe for manually resolving this, i.e. should the relevant table entries be encoded in some other way? At least for me, the changes in https://github.com/nextcloud/server/pull/24515 don't seem to fix anything but just cause the problems described in this thread. In other words: what is the goal of this exercise ? Thanks in advance.

**Comment by tcitworld** [comment]
The fix is to be backported in 20.0.8 and 19.0.9. Please be patient. https://github.com/nextcloud/server/pull/25393

**Comment by walley** [comment]
20.0.8 is out, can anyone confirm this is fixed?

**Comment by Flachzange** [comment]
> 
> 
> 20.0.8 is out, can anyone confirm this is fixed?

I can confirm this is fixed for 19.0.9 (Calendar 2.0.5). Just did the update.

**Comment by ximex** [comment]
If i didn't do anything wrong i couldn't confirm that it is fixed for 20.0.8. I still couldn't add new calender shares with groups with "space" and "&" in the name.

**Comment by Flachzange** [comment]
Unfortunately, I musst confirm what @ximex said. It works for existing shares. It does NOT work if you want to add a new share.

**Comment by tcitworld** [comment]
cc @blizzz

**Comment by blizzz** [comment]
> If i didn't do anything wrong i couldn't confirm that it is fixed for 20.0.8. I still couldn't add new calender shares with groups with "space" and "&" in the name.

Mh, that's two things mixed up here. The report originally is about existing shares that disappeared. That's fixed. I'll revisit the space and ampersand issue.

**Comment by nursoda** [comment]
Shoudn't this bug stay **open** then?

BTW, the bug is still present in NC **21.0.0**.18 with current calendar and contacts apps.
And, YES it also applies to sharing an **address book** in Contacts to a group that contains whitespace character(s).

**Comment by quentinDupont** [comment]
I confirm that the bug is still in NC 20.0.8 for sharing calendar with space in his name.

**Comment by chatlumo** [comment]
Hello, I updated to NC 20.0.8 and that bug is still here.

**Comment by alasserr** [comment]
Well, I even installed the last NC 21 version .. and still here !

**Comment by nursoda** [comment]
@rullzer could you please reopen this bug?

**Comment by fenvarien** [comment]
The problem with group shared calendars still exists with NC 21.0.1 - this bug really needs to be reopened, please. @rullzer

**Comment by k00ni** [comment]
I know that NC dev's might work on many other things, but this issue is affecting a customer of mine. Where do you need a hand to fix it?

CC @blizzz @tcitworld

**Comment by Magicrafter13** [comment]
Don't have much to add, but I'm wondering if this bug is related? https://github.com/nextcloud/files_pdfviewer/issues/381

Seems spaces in paths/names break a lot of things in our wonderful world of technology...

**Comment by JB1985** [comment]
Why is the bug not fixed? It has now been 6 months ago ... Are Nextcloud not interested in solving the problem?

**Comment by JB1972de** [comment]
who f***d that up? It worked before and now spaces are a problem within files and whatelse. Worst: Obviously nobody cares for months - that's how you destroy reputation of a product.

**Comment by nursoda** [comment]
I hate to beak the news to you, but this is not commercial software you paid for and have some "right" to receive some working software in return. (Not that you get that in most commercial software either ;) ) I'm not saying that it would be nice that this bug got fixed (as many others), but still this is a community project. So somebody must step up and fix it. That's the way OSS is "paid" for. I think that your tone is inappropriate here as it doesn't motivate anyone to work on the issue nor does it provide new insights to help find out why it broke. Please delete your last comment, and I'll delete mine.

**Comment by stweil** [comment]
@nursoda, but there exists also a commercial product called Nextcloud Enterprise which claims to be "optimized and tested for mission critical environments". Does that product contain the same bugs, or does it use different code? Which one?

"Open source" and "free software" is no excuse for bad quality. I'd expect that contributions which introduce new bugs are either reverted or that the contributor fixes it.

**Comment by llucax** [comment]
Please keep discussing the philosophical and ethical implications of this issue in the forum: https://help.nextcloud.com/

This is not the place for debate, you are spamming everyone subscribed to this issue (sorry everyone about this one too 😬).

**Comment by jospoortvliet** [comment]
@stweil you get what you pay for. If you pay nothing, then you get only what volunteers are willing and able to do for you - and most volunteers I know respond a lot better to friendly requests than angry demands. Anyhow, I don't think we're getting anywhere so please discuss these things on help.nextcloud.com or do something more productive - contribute, for example.

**Comment by stweil** [comment]
I am sorry if my comment caused misunderstandings. I asked several questions which I think might help solving this issue. Which release is used by Nextcloud Enterprise?

And personally I contribute a lot to open source, also to Nextcloud code (that's why I have member status). Therefore quality issues in Nextcloud are a personal challenge for me, too.

**Comment by blizzz** [comment]
I think we have a wrong and/or double encoding in the frontend code. I am looking at the calendar here. Upon searching for a group containing a space, say "Rock Roll", the URI is reported from the server as such.

When initiating the share, the URI ends with "Rock%2bRoll", which is "Rock+Roll". Somewhere the encoding is done. It might not even be calendar, but in the cdav library, because when processing the results from search (which is done via cdav lib) we do already see that the encoding has happened. Needs further digging.

**Comment by ChristophWurst** [comment]
Please see https://github.com/nextcloud/calendar/pull/3232 for a potential fix.
