### ISSUE TITLE
Update Maintenance and Release Schedule in the wiki

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/server#25166]
The [Maintenance and Release Schedule](https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule) page of the wiki was only partially updated after the release of Nextcloud 20.0.5 (#25102) and of Nextcloud 19.0.7 ( #25103).

These two releases appear **correctly** in the _current version_ column but they also appear **incorrectly** in the _next version_ column.

HTH

**Comment by Spartachetto** [comment]
now the page is updated

**Comment by pm-pm** [comment]
Now again with old release dates from the past.
