### ISSUE TITLE
Config file truncated when low on disk space

### ISSUE THREAD

**Issue by simon816** [nextcloud/server#25175]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### The bug

When the disk that Nextcloud is installed on is full (an admittedly unpredictable scenario), the config file is truncated. This happened during an update in my case.

### Steps to reproduce
1. `cat config/config.php`, observe config values
2. Fill up disk space, e.g. `dd if=/dev/zero of=file.dat bs=1024 count=10000000`
2. Perform action that changes config file, e.g. `occ maintenance:mode --on`
3. `cat config/config.php` observe an empty file

### Expected behaviour
Config file is not truncated when no disk space.

### Actual behaviour
Config is left empty, Nextcloud believes it is no longer installed and wants a CAN_INSTALL file.

### Server configuration

**Operating system:**
Ubuntu 18.04.5 LTS

**Web server:**
apache2 2.4.29-1ubuntu4.14 

**Database:**
mariadb 10.1.44

**PHP version:**
PHP 7.2.24-0ubuntu0.18.04.6

**Nextcloud version:** (see Nextcloud admin page)
20.0.5

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by simon816** [comment]
Can confirm on NC 21.0.2.1

Created an Ubuntu 20.04 VM with Nextcloud installed and filled the disk:
![image](https://user-images.githubusercontent.com/1497508/126727711-d4efacf1-e1a5-42e1-87bf-e851ec8efc0a.png)

**Comment by szaimen** [comment]
cc @nextcloud/server seems like this is still happening

**Comment by juliushaertl** [comment]
I think we should probably write the new content to a temp file next to the existing one and the do a rename as any other checks for available space might still lead to scenarios where the check passes but the write then fails if the disk runs out of space in the meantime.

**Comment by stefan123t** [comment]
What about the file permissions associated with the original config.php ?
Are facls carried over too ?
Would it be better to first append the necessary bytes (eg comment or newlines) to the file and later write the new contents ince the file is large enough ?

**Comment by come-nc** [comment]
Fixed by #34009

**Comment by come-nc** [comment]
> Fixed by #34009

Reverted https://github.com/nextcloud/server/pull/34137

**Comment by szaimen** [comment]
Hi @simon816 can you please check if https://github.com/nextcloud/server/pull/36691 fixes the issue for you? Thanks a lot! :)

**Comment by simon816** [comment]
Hi @szaimen, indeed it does, thanks. Of course there's a TOCTOU race condition there but I expect it's fine for the majority of cases.

**Comment by nursoda** [comment]
I see these messages in log for each web directory access in NC26beta3:
```shell
disk_free_space(): No such file or directory at …/lib/private/Files/Storage/Local.php#421
```

<details>
<summary>full nextcloud.log entry</summary>

```shell
{
  "reqId": "xucm63dW56R2nOpKqqUD",
  "level": 3,
  "time": "2023-02-15T14:59:17+01:00",
  "remoteAddr": "192.168.1.2",
  "user": "MYUSER",
  "app": "PHP",
  "method": "PROPFIND",
  "url": "/remote.php/dav/files/SOMEPATH",
  "message": "disk_free_space(): No such file or directory at /DATAFOLDER/lib/private/Files/Storage/Local.php#421",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/110.0",
  "version": "26.0.0.5",
  "data": {
    "app": "PHP"
  }
}
```
</details>

Is that related with this enhancement? This is not a race condition, this happens on each access and should be fixed.

**Comment by szaimen** [comment]
> Is that related with this enhancement?

It is not included in nc26beta3 yet so unrelated.

**Comment by nursoda** [comment]
OK, so I'll open a new issue.
