### ISSUE TITLE
files downloaded from shared folder are corrupt 

### ISSUE THREAD

**Issue by ajay-gh** [nextcloud/server#25171]
Downloading files from an anonymously shared folder ( e.g. from https://cloudprovider.com/s/charstring ) works without generating any errors or warning. Nevertheless the files get truncated in the process to roughly 5kb, regardless of actual size. When downloading the same files through the user interface (after login) the files arrive complete and uncorrupted. 

File types, sizes, flags etc. , or browser used to access the shared folder do not seem to matter. In the cloud the correct file sizes are shown.

(the cloud operator's webpage shows "latest" nextcloud version installed, but does not provide a nextcloud version number, sorry)

**Comment by kesselb** [comment]
Hi @ajay-gh,

thanks for reporting an issue. I would suggest to contact your cloud operator and ask them for advice. I created a test account at https://try.nextcloud.com/, uploaded a movie (~10mb), created a public link share, opened the link in a another browser in a private window, downloaded the file. Size and Checksum are the same.

**Comment by CamZie** [comment]
@kesselb thank you for the information and tests. We hope that maybe you could help us with this issue. More information about this issue could be found here: https://github.com/nextcloud/files_pdfviewer/issues/207 .

**Comment by ajay-gh** [comment]
Hi there,

I could reproduce your results on try.nextcloud. So the problem is
really a problem on the provider's side.

BUT ...  could it be that issue 207 from August
(https://github.com/nextcloud/files_pdfviewer/issues/207)
is related ? In this case more providers have problems.

Thanks - AJ


Hi @ajay-gh <https://github.com/ajay-gh>,

thanks for reporting an issue. I would suggest to contact your cloud
operator and ask them for advice. I created a test account at
https://try.nextcloud.com/ <https://try.nextcloud.com/>, uploaded a
movie (~10mb), created a public link share, opened the link in a another
browser in a private window, downloaded the file. Size and Checksum are
the same.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nextcloud/server/issues/25171#issuecomment-761838351>,
or unsubscribe
