### ISSUE TITLE
An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `pupdate to 20.0.5;  SQLSTATE[42000]: ... Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by rarisoft** [nextcloud/server#25170]
oops, just tries to run the update via the webinterface on a Netgear READYNAS and got this log.
---->
Update to 20.0.5

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: All tables already have the correct collation -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

The update was unsuccessful. Please report this issue to the Nextcloud community.
<----

The system was only setup last week, so one can say it is not yet used, its still in its setup phase.

What is required to get it working properly?
regards, rari.

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
