### ISSUE TITLE
Handle external calendars and address books like external storage

### ISSUE THREAD

**Issue by despens** [nextcloud/server#252]
It would be nice if the nextcloud calendar and address book were able to subscribe to other sources, as for example provided by employers or public services like Google.

A way to "mount" external calendars and address books just like it is possible to mount external storage would be a great way to create a sustainable/hybrid infrastructure.

**Comment by Bugsbane** [comment]
As far as I can tell, this is a nextcloud duplicate issue for https://github.com/owncloud/calendar/issues/132 (which I add here to reference the discussion there)

**Comment by BloodyIron** [comment]
I'd really like to use the Calendar app to aggregate a whole bunch of calendars that are provided by external servers (Zimbra/Exchange/Gmail, etc).

Now, I can't seem to find a way to do this, so I suspect this isn't currently baked in.

My understanding is the Calendar app primarily relies on CalDAV, but I would like it if it could also interface via EAS (Exchange ActiveSync). An open-source example of EAS serving is Z-push.

Is there any way we could get something like this going on? I'd love it if we could! :D

**Comment by Hoeze** [comment]
Any updates on this?

**Comment by BloodyIron** [comment]
Ya I'm totally still interested! :D

**Comment by poVoq** [comment]
I think this is basically already supported by SabreDAV, but it would need an interface for configuration. See:
http://sabre.io/dav/davclient/

**Comment by BloodyIron** [comment]
I'd rather have EAS support than DAV, but I know WebDAV can work for people too.

**Comment by Haidafraid** [comment]
EAS support would be highly appreciated, indeed!

**Comment by grumbens** [comment]
It is still in development? We really need use external CalDav calendars in NextCloud :-)

**Comment by georgehrke** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.

If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by afavata** [comment]
As Nextcloud is becoming day by day more popular  ... is it possible to reopen this ... CalDAV sync with other external calendar is a very useful function which Nextcloud should not miss.

**Comment by Hoeze** [comment]
@georgehrke?

**Comment by meichthys** [comment]
At least for calendars we have the option to subscribe to read-only calendars. 
For contacts, we have no option to subscribe to a remote address book :(

**Comment by BloodyIron** [comment]
Can we please have this re-opened?

**Comment by MalcomMcCane** [comment]
With the focus on the current progress in using alternative solutions for sync and for managing business data, I also guess it might be a very good idea to reopen this

**Comment by jacotec** [comment]
+1 for reopening this! I need my groupware calendar(s) in Nextcloud (i.e. Appointments App), but also in write direction. Currently I'm working around with vdirsyncer, but that's just a workaround ...

**Comment by Juasmis** [comment]
This would be a great addition, I am trying to get some workmates to use nextcloud but is hard to get them out of their current habits, if they could keep using their tools (Zimbra for calendar) but also be able to use it in Nextcloud it would allow to ease the transition

**Comment by play113** [comment]
no sync external carddav sources, no use nextcloud ;(
