### ISSUE TITLE
Mailing Private key to users

### ISSUE THREAD

**Issue by pavit04** [nextcloud/server#25209]
When we disable master key on nextcloud encryption and use user password based keys, in such scenario when we reinitialize keys for users who does not have private key then encrypting the user's file gives us a password for that private key and further on instructs that **"Do you want to send the passwords directly to the users by mail? (y/n)"**

After accepting the above we get the following error 
**" image not found: image:logo-mail.png webroot: serverroot:/var/www/html/nc_code"**

What exactly is the issue ?
A solution is appretiated
![nextcloud](https://user-images.githubusercontent.com/62113548/105039270-5b5ef780-5a86-11eb-8e69-592fd2730a3b.png)

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
