### ISSUE TITLE
Password by which private key is encrypted is not being sent to user's email

### ISSUE THREAD

**Issue by pavit04** [nextcloud/server#25208]
In the case where we disable master key and we use per user encryption keys, when the keys of user are removed then re-encryption of data gives us a private key which further asks "Do you want to send the passwords directly to the users by mail?".
After that accepting this line, it results into following error:

**" image not found: image:logo-mail.png webroot: serverroot:/var/www/html/nc_code"**

What is the exact issue for this ?
A solution is appreciated.

**Comment by szaimen** [comment]
It seems that the issue you have created is lacking the essential information to help us understand your problem. Please either open a new one and use the appropriate template, or edit your first comment to ensure that we can continue to work with you.
