### ISSUE TITLE
Notification when creating an additional account for an existing e-mail address

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/server#25228]
Hey,

it happened several times now that groupadmins created an account for someone who had already an account on our Nextcloud, using even the same e-mail address.

I would find it helpful if there would be a notification of some kind to avoid unwanted duplicates.

Regards!

**Comment by acsfer** [comment]
We were having the same issue, ended up using the emails as the username.
As usernames can't be duplicate, "problem solved". 🚶

**Comment by hansimausisteffiwurstbrot** [comment]
> We were having the same issue, ended up using the emails as the username.
> As usernames can't be duplicate, "problem solved". walking

Thanks! Might be feasible workaround in some cases, but privacy IS an issue. :)

**Comment by szaimen** [comment]
Sry but this is nothing we can solve as reusing the same mail address is allowed by design.
You should probably educate your admins to search before creating new accounts for users or do it as suggested here https://github.com/nextcloud/server/issues/25228#issuecomment-763787825
