### ISSUE TITLE
Defining a CSP through AddContentSecurityPolicyEvent is overridden for some policies

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/server#25226]
I noticed when developing https://github.com/nextcloud/app-certificate-requests/pull/361 that the `allowInlineScript`, `allowEvalScript` and `allowInlineStyle` policies weren't being applied when defined through `AddContentSecurityPolicyEvent`.

The policy added through `AddContentSecurityPolicyEvent` gets merged here:
https://github.com/nextcloud/server/blob/a7a60de228358841eb0d50ba387e027691491afb/lib/private/Security/CSP/ContentSecurityPolicyManager.php#L59-L68

And that is fine, and works properly but then it gets merged a second time there:
https://github.com/nextcloud/server/blob/a7a60de228358841eb0d50ba387e027691491afb/lib/private/AppFramework/Middleware/Security/CSPMiddleware.php#L65-L82

Policies which are arrays (`allowedFontDomains`, `allowedImageDomains`, ...) get merged properly, but policies which are booleans (for instance `allowEvalScript`, `allowInlineScript`) get overridden by the response policy defined by the app (either custom, either default one when using `TemplateResponse`, ...), or by the default fallback to `OCP\AppFramework\Http\ContentSecurityPolicy` (line 66).

I'm not sure whether this is an acceptable behaviour or not, and I don't care much about defining these ones, and on top of that the `allowInlineScript` and `allowEvalScript` methods are deprecated, but this behaviour isn't much expected or documented.

cc @rullzer because of CSP stuff.

**Comment by szaimen** [comment]
Hi @tcitworld I suppose this is still valid?

**Comment by tcitworld** [comment]
Yes. Asking @nickvergessen @LukasReschke if this is worth it to look into.

**Comment by nickvergessen** [comment]
Makes sense I think. The problem is: we merge the others. It's not overwriting. We can only merge booleans with `&&` or `||` and the question is what is correct or intended.
