### ISSUE TITLE
 Why can't we share the direct link so that other websites can directly load the pictures and videos in the network disk?

### ISSUE THREAD

**Issue by junglerule** [nextcloud/server#25227]
Why can't we share the direct link so that other websites can directly load the pictures and videos in the network disk?

I want to share the absolute path so that my website can use these images directly

**Comment by szaimen** [comment]
https://apps.nextcloud.com/apps/sharingpath

**Comment by junglerule** [comment]
> https://apps.nextcloud.com/apps/sharingpath

I still don't know where the "open shared path" button is. Can I take a screenshot

**Comment by szaimen** [comment]
Please ask this in the forum. Thanks!
https://help.nextcloud.com
