### ISSUE TITLE
Error during update. Doctrine\DBAL\Exception\DriverException:

### ISSUE THREAD

**Issue by dustdancer** [nextcloud/server#25231]
first of all, sorry, i'm not a native speaker. When I tried to upgrade my Nextcloud server which is running on my Qnap server to 20.0.5.0 I got this error:

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TABLE oc_health_ces_contexts (id INT AUTO_INCREMENT NOT NULL, description LONGTEXT DEFAULT NULL, insert_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, lastupdate_time DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET UTF8 COLLATE `utf8_bin` ENGINE = InnoDB': SQLSTATE[42000]: Syntax error or access violation: 1067 Invalid default value for 'insert_time'

Sorry if i forgot important details but i'm pretty new to bug reports.

Best regards

dustdancer

**Comment by acsfer** [comment]
This seems an error with a 3rd party app, not Nextcloud core.

Check here (it seems that your database is too old?) https://github.com/datenangebot/health/issues/31 and fill a bug report there if needed.
