### ISSUE TITLE
Moving from S3 primary storage back to filesystem

### ISSUE THREAD

**Issue by krakazyabra** [nextcloud/server#25232]
Hello. This is not issue. Question about migration _from_ S3 storage, which was primary storage, back to filesystem with converting user's data. 
All files on S3 have their own names, which are not related with original names. Same with buckets. 
Is there some tool, using which I can migrate data from S3 to filesystem? 
In my mind, this tools should read bucket name, find in DB info, who is owner of this bucket, create folder in ./nextcloud/data, and copy files one-be-one, changing name to original.

**Comment by acsfer** [comment]
It seems more appropriate to ask at https://help.nextcloud.com

> Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.
