### ISSUE TITLE
Allow to lock login information per user (disable password change and 2fa)

### ISSUE THREAD

**Issue by Bleuzen** [nextcloud/server#25239]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I use Nextcloud for working together with other people, for example my class mates at school. I want all of them, that I allow, to access and edit the files related to our projects as well as upload new ones.

Three options came to my mind:
1.) Create a public share with a password
this works for basic file sharing.
However, it does not display the storage quota nor allow to use apps.
-> not a great solution, so I kept searching for alternatives

2.) Create multiple user accounts (one for each of my class mates and others who want access).
I would have to create many, many users, only to have access to a shared folder, which feels kind of clunky.
Also it is not comfortable to give new users access. (have to create new accounts all the time)
-> too much effort + that many users are overkill for this task

3.) Create one user and give the username/password to anyone needing access
This turned out to be the closest option for now.
It is low effort, everyone that I want can get in easily, all apps work, I don't have to create a bunch of new users, it displays the storage quota, ...
As a bonus, nobody can forget their password and if one does, it is the same for everyone, so we can help out each other without me needing to login as admin and reset the password.
-> seems nearly perfectly suited for what I want

... But only nearly!

Because if using option 3, some troll may come along and change the password of the shared user or enable 2FA to lock out all the others.
I want to avoid that.

**Describe the solution you'd like**
I'd like to have an option to take away the ability to change the login credentials per user. Something like a "locked" checkbox for every user on the user administration page.
If this "locked" checkbox is checked, the user should not be able to change login information (the password or enable 2fa).

**Describe alternatives you've considered**
(already above)

**Additional context**
(described above)

**Comment by szaimen** [comment]
Hi there,

you could use the guests app together with internal shares for this.
https://apps.nextcloud.com/apps/guests

Please refer to the forum https://help.nextcloud.com for further discussion on this.
Thank you!

**Comment by Bleuzen** [comment]
@szaimen The guest app doesn't work for this. A guest user can still change its password.
Also shares do not work, because as I wrote in the initial post, I want to be able to see the storage quota.

Since what I want seems not possible as of now, I see this issue more like a feature request, so should it be reopened?
