### ISSUE TITLE
web upload: remaining time strings have letters on different line, depending on background

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#25235]
See the position of the s on the screenshot:

![Screenshot_20210120_152221](https://user-images.githubusercontent.com/2184312/105188208-efd36380-5b33-11eb-891c-80be5705cc92.png)

Its pixels were pushed just too hard!

All letters are a bit lower when the blue bar is not behind them, they will be lifted up with the progress.

Seen on 21 with Firefox 84.

@nextcloud/designers

**Comment by szaimen** [comment]
I can reproduce this on NC22 beta 5

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by skjnldsv** [comment]
Fixed 28
