### ISSUE TITLE
Usage of variables for mount paths not working

### ISSUE THREAD

**Issue by cgraaaj** [nextcloud/server#25237]
Hi All,

I wanted to create folder based on user name in the external storage,as suggested below 
![image|690x358](upload://xvunmciWKbsZrqNLYd98pMAaa8f.png) 
But  i couldn't able to achieve it, am getting the below error
![image|690x197](upload://bqK67ygsFeroYbn2RfhnotNZoqM.png) 
without **$user** variable there is no error
![image|690x208](upload://veiAjFOJe3Ri1yuHrsPNSQCiYSv.png)

**Comment by j-ed** [comment]
Unfortunately your report misses essential information about your environment, the used software versions etc., etc. The issue template has been created to help you providing this information. Please provide the missing information. Additionally please insert any pictures directly into the report. The provided links don't work and are referring to the issue ticket itself.

**Comment by cgraaaj** [comment]
Am extremely sorry for that,
Am using  nextcloud 20.0.5 in docker 20.10.2

I wanted to create folder based on user name in the external storage, as suggested in [this] doc (https://docs.nextcloud.com/server/latest/admin_manual/configuration_files/external_storage_configuration_gui.html)
![image](https://user-images.githubusercontent.com/36030305/105217603-161bf200-5b7a-11eb-82d8-c469f6a70835.png)
But i couldn't able to achieve it, am getting the below ! mark
![image](https://user-images.githubusercontent.com/36030305/105217623-1ddb9680-5b7a-11eb-8213-9cf8dc01d0ca.png)
without $user variable there is no error
![image](https://user-images.githubusercontent.com/36030305/105217641-2502a480-5b7a-11eb-848d-e37946ca6e15.png)

Thanks
