### ISSUE TITLE
Users page: "Done" button useless / no way of canceling changes

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#25248]
On the users page, you need to hit the pencil in order to change a user's details:

![image](https://user-images.githubusercontent.com/1804221/105333671-472a1000-5bd6-11eb-864c-f519ac4334b3.png)

Once hit, the pencil turns into a check button (tooltip: "done"):

![image](https://user-images.githubusercontent.com/1804221/105333735-59a44980-5bd6-11eb-9eb6-445760827e9c.png)

#### Problem

Regardless of whether I hit the "done" button or not, the changes will get saved, even if I leave the page before hitting "done".
So why have that button in the first place?

Side effect: there is no "cancel" option in case you messed something up with the user's details.

**Comment by szaimen** [comment]
It is still like this on NC21.0.2

**Comment by szaimen** [comment]
cc @nextcloud/designers
