### ISSUE TITLE
20.0.5 onwards: Certificate is not valid on all apps

### ISSUE THREAD

**Issue by LecrisUT** [nextcloud/server#25243]
After the upgrade to 20.0.5 all apps fail integrity check with:
```
Results
=======
- core
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Certificate is not valid.
......
Raw output
==========
Array
(
    [core] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Certificate is not valid.
                )

        )

```
The [documentation page](https://docs.nextcloud.com/server/20/admin_manual/issues/code_signing.html) does not give any hints on how to fix this issue.
### Server configuration

**Operating system:** CentOS Stream

**Web server:** Caddy 2.3.0

**Database:** MariaDB 10.3.17

**PHP version:** 7.4.14

**Nextcloud version:** 20.0.5++

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:** In the main body
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by muhviehstah** [comment]
same here on latest 21 beta

**Comment by layz89** [comment]
Exactly, the same in version 21 beta 7

**Comment by AlexG-78** [comment]
Same here on 21. Beta 7

**Comment by AnnabellaRenee87** [comment]
Getting the same thing on 21, beta 7 as well.

**Comment by tcitworld** [comment]
Should be fixed by https://github.com/nextcloud/server/pull/25214 for 21, not sure about 20.0.5

**Comment by LecrisUT** [comment]
Seems like it would be fixed as early as 21 beta 8. If 21 is still a long way from release, either the breaking changes in 20.0.5 should be reverted, or all of the changes for this PR should be merged.

It is becoming a breaking bug, since some apps can have bugs (e.g. I am not able to login via social login due to a bug) and we cannot update them due to the certificate issue, leaving us in a limbo until then.

**Comment by tcitworld** [comment]
I meant the 21 release cycle, so 21 beta 8, not 21's final first release.

**Comment by LecrisUT** [comment]
For now just applying these 2 commits will solve this issue:
- d751fedffb110aca956e9f786cd9ecdafdfa6ecd
- fcbbcacab4dc0178c7fdf1a61cfb81f922c60209
I suggested these to be integrated in 20.0.6 #25294

**Comment by bmunro-peralex** [comment]
So it looks like those commits didn't make it to 20.0.7 either, by looking at the source

**Comment by fuomag9** [comment]
Same here after updating to next cloud 25

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**Comment by wiesty** [comment]
Same after 25 update:
`Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- .htaccess
	- EXTRA_FILE
		- .htaccess.old
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [.htaccess] => Array
                        (
                            [expected] => d9cab0f077161bf043d6d85f5bcacbdfaf82913968b7
                            [current] => 5b462bc8c1c1da259
                        )

                )

            [EXTRA_FILE] => Array
                (
                    [.htaccess.old] => Array
                        (
                            [expected] => 
                            [current] => ab4cb3a5cb7c839ece26775ab5b38bb575aa7bc8660490cf6
                        )

                )

        )

    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)`

**Comment by muhviehstah** [comment]
same here after 25 update

`- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.`

**Comment by MarslMarcello** [comment]
> same here after 25 update
> 
> ```
> - related_resources
> 	- EXCEPTION
> 		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
> 		- Signature data not found.
> 		
> ```

+1

**Comment by zenhighzer** [comment]
same here after 25 update (via docker container)

- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

**Comment by xenophil90** [comment]
Same here.

Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by codewithelvin** [comment]
The same issue here with NC 25 Docker

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)
```

**Comment by MitchT1966** [comment]
...and: same here. NC 25.0.0 with Docker. Any idea how this can be fixed and when?


Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- related_resources
	- EXCEPTION
		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
		- Signature data not found.

Raw output
==========
Array
(
    [related_resources] => Array
        (
            [EXCEPTION] => Array
                (
                    [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
                    [message] => Signature data not found.
                )

        )

)

**Comment by wiesty** [comment]
> Same after 25 update:
> 
> Technical information
> 
> ```
> =====================
> The following list covers which files have failed the integrity check. Please read
> the previous linked documentation to learn more about the errors and how to fix
> them.
> Results
> =======
> - core
> 	- INVALID_HASH
> 		- .htaccess
> 	- EXTRA_FILE
> 		- .htaccess.old
> - related_resources
> 	- EXCEPTION
> 		- OC\IntegrityCheck\Exceptions\InvalidSignatureException
> 		- Signature data not found.
> Raw output
> ==========
> Array
> (
>     [core] => Array
>         (
>             [INVALID_HASH] => Array
>                 (
>                     [.htaccess] => Array
>                         (
>                             [expected] => d9cab0f07716234242423432rf23f23f34faf82913968b7
>                             [current] => 5b462bc8c1c1da259
>                         )
>                 )
>             [EXTRA_FILE] => Array
>                 (
>                     [.htaccess.old] => Array
>                         (
>                             [expected] => 
>                             [current] => ab4cb3a5cb7c839ece26775ab5b23r3223f2fce233ff23
>                 )
>         )
>     [related_resources] => Array
>         (
>             [EXCEPTION] => Array
>                 (
>                     [class] => OC\IntegrityCheck\Exceptions\InvalidSignatureException
>                     [message] => Signature data not found.
>                 )
>         )
> )
> ```

**successfully updated to 25.0.1 RC1 and it fixed all errors.**

**Comment by MitchT1966** [comment]
A question: is there a way to install rc1 (or any other beta) in docker and if so, how? Sorry if this doesn't fit into this stream - any help appreciated

**Comment by muhviehstah** [comment]
> A question: is there a way to install rc1 (or any other beta) in docker and if so, how? Sorry if this doesn't fit into this stream - any help appreciated

for me updating the apps fixed the Problem without updating to RC1
