### ISSUE TITLE
Wrong option set in "Authentication required" modal

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#25247]
When an admin wants to perform sensitive actions and hasn't confirmed their password for some time, they get asked for their password just to confirm that action.

The password entry modal offers two buttons that don't make sense in this dialog:

![image](https://user-images.githubusercontent.com/1804221/105331654-ffa28480-5bd3-11eb-8c43-6032879afb0f.png)

Suggestion: Cancel/OK (default to OK)

**Comment by heyvickywiz** [comment]
Based on user journey in this context, a simple Confirm button might do. And as far as Cancel action is concerned, the 'x' icon on top-right might do the work. Else that can be removed and a cancel button added beside Confirm button. A just did a small UI design for same. 
![Modal Auth-2](https://user-images.githubusercontent.com/80255081/119484015-3bf91380-bd73-11eb-8b28-1397ca7fb9be.jpg)

**Comment by szaimen** [comment]
I think this was fixed in the meantime. Please reopen if you can still reproduce this. Thanks!
