### ISSUE TITLE
Group removal too easy (confirmation modal has "yes" as default)

### ISSUE THREAD

**Issue by wiswedel** [nextcloud/server#25246]
When attempting to remove a group from the users page, there comes a confirmation modal if I really want to remove the group.

![image](https://user-images.githubusercontent.com/1804221/105326633-3ecdd700-5bce-11eb-8477-a1de2e14b721.png)

Usually the default action when I hit Enter on such a dialog would be the non-lethal option.
Here however, "yes" is the pre-selected one, resulting in possibly regretable heat actions.

**Comment by wiswedel** [comment]
cc @nextcloud/accessibility

**Comment by szaimen** [comment]
In my opinion pre-selecting `Yes` makese sense. But I am interested in more opinions on that.
