### ISSUE TITLE
Wrong Content-Type on PROPFIND breaks modsecurity exception ruleset for Nextcloud

### ISSUE THREAD

**Issue by fzipi** [nextcloud/server#25250]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

We come across this one in our ruleset exceptions for Nextcloud. We had a bug submitted about something being incorrectly detected, and this happens because the query is not using the proper content type. See https://github.com/coreruleset/coreruleset/issues/1838.

### Steps to reproduce
1. You'll need the same installation using the latest coreruleset nextcloud exceptions.
2. See related issue in coreruleset. The usage seems standard.

### Expected behaviour
It should not detect a problem, because exceptions are properly set. Client should send `text/xml` when content is XML.

### Actual behaviour
The client should send the proper content-type, so it is parsed by the correct body processor in modsecurity. Propfind sends XML, but the content-type is marked as `text/plain` by default.

**Comment by szaimen** [comment]
Hi, please fill out the issue template. Thank you!

**Comment by fzipi** [comment]
Hi @ntimo! Can you help me with this request from @szaimen?

**Comment by pmetras** [comment]
I have a similar problem when wanting to see the Information of a shared folder in Nextcloud v21 (the initial reporter was when displaying pictures, I think).

Here is a snippet from the request sent to the server:
```
PROPFIND /cloud/index.php/apps/dashboard/ HTTP/2.0
Content-Length: 641
Sec-Ch-Ua: "Chromium";v="94", ";Not A Brand";v="99"
Requesttoken: MwCGmD3xs0nTG49UGdhjSw/lxaxGzOVzGH2lgnhXyxo=:SVm3rna9gjyHIr81MqwAOmmRlNt32NUZWRzP+FcfvCw=
Dnt: 1
Sec-Ch-Ua-Mobile: ?0
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.114 Safari/537.36
Content-Type: text/plain;charset=UTF-8
Accept: application/json, text/plain, */*
Sec-Ch-Ua-Platform: "Windows"
Origin: https://www.example.com
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Accept-Encoding: gzip, deflate, br
Accept-Language: fr;q=0.8,en;q=0.5
Cookie: nc_sameSiteCookielax=true; nc_sameSiteCookiestrict=true; nc_username=john; oc_sessionPassphrase=xxx; ocxxx=xxx; nc_token=xxx; nc_session_id=xxx; language=fr;
Host: www.alterna.tv

--a6ef367a-C--
<?xml version="1.0"?>
                        <d:propfind  xmlns:d="DAV:"
                                xmlns:oc="http://owncloud.org/ns"
                                xmlns:nc="http://nextcloud.org/ns"
                                xmlns:ocs="http://open-collaboration-services.org/ns">
                        <d:prop>
                                <d:getlastmodified />
                                <d:getetag />
                                <d:getcontenttype />
                                <d:resourcetype />
...
```

According to [original ticket](https://github.com/coreruleset/coreruleset/issues/1838), the problem is that the `PROPFIND` response is sent with `Content-Type: text/plain;charset=UTF-8` instead of an XML content type. The original ticket contains links to the possible origin of the problem.
