### ISSUE TITLE
Enhancement: Configurable File Versioning

### ISSUE THREAD

**Issue by mattewan** [nextcloud/server#25254]
As it stands currently, when versioning is enabled on the nextcloud instance it applies to every file on all accounts.

It would be great if versioning could be configured on a per-folder basis so that it could be applied to important folders/files instead of globally.  A particular problem with the current implementation is that large files can chew through space when versioning is enabled, especially if the retention periods have been set to a long time.

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/22456
