### ISSUE TITLE
PDF viewer on public links doesn't work

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#25251]
Tested with c.nc.c (Nextcloud 21 beta 6)

When I share a PDF as public link it doesn't open the PDF reader. For large files I only see the download button:

![image](https://user-images.githubusercontent.com/1589737/105349909-a560ee00-5bea-11eb-9a72-5281fd7a4cb1.png)

For smaller PDFs I get a preview but only from the first page.

I would expect that the PDF Viewer opens and I can read the whole document in the browser

**Comment by szaimen** [comment]
Do you have richdocumentscode enabled? This could be the issue.

**Comment by megothub** [comment]
+1
Even on password protected shares

On my side Latest NC 20.0.7
Ubuntu 20.04.2

The only workaround is to disable PDF Viewer

here is the related ticket
https://github.com/nextcloud/files_pdfviewer/issues/286

**Comment by Daywalker01** [comment]
Same here
NC 20.0.07 on Ubuntu 20.04 (non docker)
Firefox on Ubuntu 20.04


Warning: getHexString - ignoring invalid character: 33 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 79 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 84 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 89 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 80 pdf.worker.js:1705:13
Warning: getHexString - ignoring additional invalid characters. pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 104 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 116 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 109 pdf.worker.js:1705:13
Warning: getHexString - ignoring invalid character: 108

Error in app.js:817:16
    _callee7$/</< app.js:817
    promise callback*_callee7$/< app.js:815
    promise callback*_callee7$ app.js:776
    Babel 8
    webViewerOpenFileViaURL app.js:1947
    webViewerInitialized app.js:1917
    promise callback*run app.js:478
    webViewerLoad viewer.js:218
    EventListener.handleEvent* viewer.js:228
    Webpack 3

No Problem when you are logged in.
Test can be done, by sharing a folder, and opening that link in a Private Browsing session.

**Comment by Daywalker01** [comment]
Issue can be closed.
Was fixed in 20.0.8

https://nextcloud.com/changelog/#20-0-8 (Fix opening pdf files in public folder shares (files_pdfviewer#321))
https://github.com/nextcloud/files_pdfviewer/pull/321

Sorry for the inconvenience

**Comment by szaimen** [comment]
there was a new pdf issue on NC21.0.2 but it will be fixed with NC21.0.3
