### ISSUE TITLE
Show latest stable version on upgrade page

### ISSUE THREAD

**Issue by GutHib** [nextcloud/server#25266]
Hi,

For many months now, I was completely unaware that there's a version 19 and (gasp!) even a version 20 of Nextcloud.

The reason is that, when you're running an older version of Nextcloud, the update page will only show you updates for that version. E.g. when you're running NC18.0.6 that page will tell you there's an 18.0.7 to upgrade to, but there's no info telling you to come back after the update to fetch version 19 and (ultimately) version 20.

Small step, but giving that info right away would definitely make it more user-friendly.

Thanks, and keep up the great work! :)

**Comment by kesselb** [comment]
I just upgraded to Nextcloud 19.0.7 and see:

![image](https://user-images.githubusercontent.com/3902676/105476475-f6cbb480-5ca0-11eb-8f27-a87f262ff317.png)

**Comment by GutHib** [comment]
But if you are on Nextcloud 19.0.5 you will see:

A new version is available: **Nextcloud 19.0.7**
**All** apps have an update for this version available.

No info whatsoever that there are newer versions beyond Nextcloud 19.0.7.
