### ISSUE TITLE
Minor design issues with browser sessions and device passwords

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#2526]
Just updated my private installation to beta2 and notice some minor design issues on the personal settings page:

- [ ] multiple popover menu of sessions/passwords can be opened (they should close if I click somewhere outside the menu, there's a ``OC.registerMenu`` helper or similar)
- [ ] the popover's arrow is not aligned to the three dots, it's too much on the right

![bildschirmfoto von 2016-12-06 11-23-32](https://cloud.githubusercontent.com/assets/1374172/20922111/4ef966e2-bba7-11e6-9b1c-9b75b3d0c023.png)

cc @icewind1991 @nextcloud/designers

**Comment by MorrisJobke** [comment]
Similar to #2329

**Comment by MorrisJobke** [comment]
> Similar to #2329

Fixed with #2363 by @blizzz

**Comment by phsc** [comment]
Also similar to https://github.com/nextcloud/calendar/pull/212
