### ISSUE TITLE
nextcloud does not show app updates on arm processors

### ISSUE THREAD

**Issue by tigernero79** [nextcloud/server#25260]
i noticed that dub last nextcloud 20.0.5 uodate to applications are not detected du many instances nextcloud on arm processors, while everything works on x86 / x64 installation

for example I uninstalled the mail application and I no longer find it among the applications in order to reinstall it.  i am forced to manually load application into apps folder.  how to solve?

**Comment by kesselb** [comment]
No bug report's without issue template. Probably https://github.com/nextcloud/server/issues/25137 but without logs don't know.
