### ISSUE TITLE
Feature request : Declare LDAP group admin to nextcloud admins

### ISSUE THREAD

**Issue by luclis** [nextcloud/server#25272]
Hi, I'm running an AD and I would like to use the group *Nextcloud Admin* to administrate the server. 
Right now, I can just put each users in the local *admins* group. 
Make somes recherche and found this : 
>Currently there is no way to declare an LDAP group admin, only adding the LDAP users to the admin group. I cannot think of any changes that would effect your  hack however.
>_Originally posted by @blizzz in https://github.com/nextcloud/server/issues/21951#issuecomment-662967177_

Can you add this feature ?

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
