### ISSUE TITLE
Search provider names in unified search hint do not respect localized language rules

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#25282]
Fits:

![Screenshot_20210122_182232](https://user-images.githubusercontent.com/2184312/105523563-ce62ab00-5cde-11eb-95ac-52b5e62a64ae.png)

Should be capitalised:

![Screenshot_20210122_182352](https://user-images.githubusercontent.com/2184312/105523701-023dd080-5cdf-11eb-8ba7-22cb5120eb0f.png)

It is not a translation issue. The search providers only have to provide a `getName()` method for a translated string. The provides all return it in capitalized fashion ("Apps", …). In `core/src/views/UnifiedSearch.vue:47` they are hard-lowercased. 

The best distinction is done by the translators however. 

My suggestion would be to add another method (as another interface to avoid breakage) that would return a string to be used within a sentence. And fall back to `getName()`. The hard lowercasing in the view would be removed.

The alternative would be to only remove the forced lower cased, which would end up in a strange picture at least in English:

![Screenshot_20210122_183238](https://user-images.githubusercontent.com/2184312/105524656-3796ee00-5ce0-11eb-94b7-af9725bb631d.png)

@ChristophWurst @skjnldsv @jancborchardt   what do you think?

**Comment by nickvergessen** [comment]
https://github.com/nextcloud/server/blob/bfe87e501d83ff4dc9e5057c07464a598d951b4b/core/src/views/UnifiedSearch.vue#L47

We already agreed on this before to drop the lower

**Comment by ChristophWurst** [comment]
:+1: I actually thought we had fixed that during Nextcloud 20 development
