### ISSUE TITLE
Allow customisation of Regional Settings

### ISSUE THREAD

**Issue by kenfallon** [nextcloud/server#25292]
NextCloud does not provide any way to customise the date format used. This is possible in other systems like Google Calendar. 

In my case I live in the Netherlands but would like to have ISO8601 Date (YYYY-DD-MM HH:MM:SS), Euro as currency, '.' as decimal separator.

It is correct to use regional locates for the initial default settings for dates, numbers, currency, languages etc. however just because most people in any given location on the planet follow those conventions, will not mean all want/can to do so.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by eterps** [comment]
I just did a demo of Nextcloud to my company, this is the first thing that people noticed and complained about.

**Comment by markcst** [comment]
> As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

Hi, this feature would be really useful, please take in consideration to implement it. `ISO8601` should be included by default as an option in a big software like Nextcloud, it's very strange it isn't yet there.
Also, make sure to give the option to chose between 12/24 hour format, cause having only the 12 hour format "standardized" is quite helpless.
Thanks, anyway for your work

**Comment by wdburgdorf** [comment]
Absolutely essential. Currently, for file dates it does not even show the regional format, but "November 2025", which is pretty useless. Each company has their own rules for this. I can hardly offer setting up Nextcloud for a client if I cannot even set the date format correctly.
