### ISSUE TITLE
Use the Viewer to open files in filtered view (shares)

### ISSUE THREAD

**Issue by eneiluj** [nextcloud/server#25314]
Hey @skjnldsv @PVince81. When selecting the "Shares" filter in Files app left sidebar, files are not opened with the Viewer. How hard would it be to use the Viewer there? Could you point me to the right direction so I can maybe do it some day?

**Comment by skjnldsv** [comment]
It's because there is no default actions registered here
This would require a fair amount of work and lots of potential backfire.
I would advise against until there is a new files app

**Comment by szaimen** [comment]
So is this feasible?
