### ISSUE TITLE
Error after update - fedora 33

### ISSUE THREAD

**Issue by jeffersonmfs** [nextcloud/server#25327]
After the nextcloud update, you need to hit 3 files

The first 

nextcloud-auth-any.inc

# Apache config snippet. To be used by /etc/httpd/conf.d/*.conf files

to

# Apache config snippet. To be used by /etc/httpd/conf.d/ *.conf files

The string '/*' is the start comment mark and changes the functionality of the file

The same operation must also be done on the files:

nextcloud-auth-local.inc

nextcloud-auth-none.inc

**Comment by kesselb** [comment]
Thanks :+1: Closing as unrelated to nextcloud/server. Talk to the package maintainer. We do not maintain any configuration files for fedora here.
