### ISSUE TITLE
Cannot login and expired cookie

### ISSUE THREAD

**Issue by LecrisUT** [nextcloud/server#25328]
The main symptom of this issue is that users cannot login via the web interface. Currently logged in users are still able to access everything inside, e.g. the desktop client still operates, and I don't want to risk logging out atm. Looking into the web-console, a big red flag I keep receiving the same expired cookie even when I change the cache setup, e.g. `'remember_login_cookie_lifetime' => 0`.
![Screen Shot 2021-01-26 at 12 38 41](https://user-images.githubusercontent.com/25577083/105797584-9e175700-5fd3-11eb-89e0-be7589e594f9.png)
If there are any hints on how to further debug this problem let me know. The only less standard setup I have is I'm using caddy as a web-server.

Other thing I've noticed is that the `oc_sessionPassphrase` is the same everytime, even when I use incognito.

**Operating system:** CentOS Stream

**Web server:** Caddy

**Database:** MariaDB

**PHP version:** 7.4.14

**Nextcloud version:** 20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:** Updates

### Client configuration
**Browser:** Firefox, but persistent symptoms on other browsers

### Logs
![Screen Shot 2021-01-26 at 12 45 19](https://user-images.githubusercontent.com/25577083/105797983-72e13780-5fd4-11eb-91f7-1c97c6cef375.png)

**Comment by LecrisUT** [comment]
I forgot this is an issue of my configuration with `caddy` + `php` not having the appropriate permissions.

**Comment by crt-boi** [comment]
i have the same issue on my centos server ... but i dont remember installing anything expect the php modules it needs and php mysql, tried the exact same thing with my ubuntu server and it worked even tho the same modules are installed, how did you fix it?

**Comment by LecrisUT** [comment]
For me it was due to my own setup using `caddy` and `php socket` rather than `php port`. What I had was I have created a new socket for `caddy` user, and I forgot to change the permission to `/var/log` and other similar folders. So you can try to check the permissions. The symptoms I had for php not working was that any action I tried to do wouldn't do anything, which makes sense since php could not do anything.

Otherwise check the logs of your web-server/browser console and then php logs for some clues. If you can provide more on the symptoms, and your setup, we can troubleshoot this issue.
