### ISSUE TITLE
Image Viewer Download Button

### ISSUE THREAD

**Issue by a1pilot** [nextcloud/server#25330]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
It would be really useful to have a direct download button in the image viewer.

If I go to a folder full of images and open one to view, then use the navigation buttons to scroll through and view them, there's no way to download the current image being viewed without remebering the name and then trawling through the list of items to find it.

You can't right click and save-as, due to that only downloading the preview generator image.

**Describe the solution you'd like**
In an equivalent environment such as Google Drive, there's a download icon up with next to the share / sidebar buttons.

It seems reasonable to have a similar feature.

**Describe alternatives you've considered**
Aside from the above described manual effort, I don't see an alternative.

**Comment by szaimen** [comment]
https://github.com/nextcloud/viewer/pull/702
