### ISSUE TITLE
oauth2 login flow asks for "grant access" repeatedly

### ISSUE THREAD

**Issue by MichaelDaum** [nextcloud/server#25334]
As has been mentioned in at least #17165, the login process currently consists of three steps:

1. connect your account
2. login
3. grant access

This happens every time a user logs in using oauth2, i.e. when the user already did connect the accounts and granted access.
The Devices & Sessions section of the user is amassing endless entries, for each call to the authorization endpoint.
This probably is not correct.

Instead, once the account is connected to the oauth2 client and access has been granted, only step (2) is required, the login.
The server should know that this oauth2 client and this user have already been authorized and skip any unnecessary dialog.

Given the user is already authenticated on the nextcloud side, none of the dialogs (1), (2), (3) should be visible to the user. Just forward the authentication, nothing more. Thanks.

**Comment by szaimen** [comment]
Lets us track this in https://github.com/nextcloud/server/issues/17165
