### ISSUE TITLE
Attach a name or email address to anonymous upload

### ISSUE THREAD

**Issue by leoncpa1** [nextcloud/server#25355]
In Nextcloud 
<we created an upload link that we send to our customers so they can upload at will to us  However, we would like them to be forced to enter their name or email address so we know who the file is from (some files are uiploaded without proper identification of the sender in the file)  so now when they click on the upload they get 
![image](https://user-images.githubusercontent.com/78118747/106067482-be770c80-60cc-11eb-828b-c6f6b98d104c.png)
if they could type in their name & it could appear somewhere in the comments of the file that would be so useful
 !--
Thanks for reporting issues back to Nextcloud!

Note: This is the **issue tracker of Nextcloud**, please do NOT use this to get answers to your questions or get help for fixing your installation. This is a place to report bugs to developers, after your server has been debugged. You can find help debugging your system on our home user forums: https://help.nextcloud.com or, if you use Nextcloud in a large organization, ask our engineers on https://portal.nextcloud.com. See also  https://nextcloud.com/support for support options.

Nextcloud is an open source project backed by Nextcloud GmbH. Most of our volunteers are home users and thus primarily care about issues that affect home users. Our paid engineers prioritize issues of our customers. If you are neither a home user nor a customer, consider paying somebody to fix your issue, do it yourself or become a customer.

Guidelines for submitting issues:

* Please search the existing issues first, it's likely that your issue was already reported or even fixed.
    - Go to https://github.com/nextcloud and type any word in the top search/command bar. You probably see something like "We couldn’t find any repositories matching ..." then click "Issues" in the left navigation.
    - You can also filter by appending e. g. "state:open" to the search string.
    - More info on search syntax within github: https://help.github.com/articles/searching-issues
    
* This repository https://github.com/nextcloud/server/issues is *only* for issues within the Nextcloud Server code. This also includes the apps: files, encryption, external storage, sharing, deleted files, versions, LDAP, and WebDAV Auth
  
* SECURITY: Report any potential security bug to us via our HackerOne page (https://hackerone.com/nextcloud) following our security policy (https://nextcloud.com/security/) instead of filing an issue in our bug tracker.  

* The issues in other components should be reported in their respective repositories: You will find them in our GitHub Organization (https://github.com/nextcloud/)
-->

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by elalann** [comment]
Well, theoretically "anonymous" are "anonymous" indeed, as a workaround you could maybe implement some kind of frontend before redirecting the user to the upload page.

**Comment by leoncpa1** [comment]
Seems crazy that the only choices are either making an account for everyone who uploads docs to you, or accepting anonymous uploads & you may not know who they are from

**Comment by j-ed** [comment]
> Seems crazy that the only choices are either making an account for everyone who uploads docs to you, or accepting anonymous uploads & you may not know who they are from

I think the guest account feature has exactly been created for the purpose of identifying users 😉

**Comment by leoncpa1** [comment]
You would think that anonymous upload would have been created in order not to force a person to create an account in nextcloud if they occasionally send files to you  but its still important to somehow tag the file as to who the sender is

**Comment by leoncpa1** [comment]
Guest accounts can’t upload  & the whole point is to not force occasional uploaders to register for an account. However, the system should somehow tag the files as to who uploaded them

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by leoncpa1** [comment]
What would it cost to implement

This feature.

Sent from my Verizon, Samsung Galaxy smartphone



-------- Original message --------
From: szaimen ***@***.***>
Date: 6/23/21 6:41 AM (GMT-05:00)
To: nextcloud/server ***@***.***>
Cc: Leon Schenker ***@***.***>, Author ***@***.***>
Subject: Re: [nextcloud/server] Attach a name or email address to anonymous upload (#25355)


As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by szaimen** [comment]
Please ask this question here: https://help.nextcloud.com/c/nextcloud-freelancing/looking/49
Thanks! :)

**Comment by furchtlos76** [comment]
Hi, i switched from Dropbox to Nextcloud, and i am missing this feature, too. Using nextcloud uploadfolder so Cutomers can send me big pictures or files, but never know HOW send them. Dropbox ascks for e-mail and name, so adds this to filenames. Is there any way to let Nextcloud also ad a name field to the uploader to be able to add his name to the uploaded files?

**Comment by joeu1998** [comment]
I know this is closed, but I'd also really love to see this. Usecase: we are planning to use a Nextcloud "Request files" folder to allow guests at our wedding to upload photos and videos that they capture. We'd love to know who uploaded what, even if it's just a name field before they can select files to upload, with Nextcloud then tagging each file somehow with whatever name they enter. WeTransfer does this by requiring an email address from anyone uploading files, except WeTransfer then creates an account for that user which is not a good system. Most of our wedding guests are not technically minded enough to create, or want, a Nextcloud account just to send us any images or videos they capture - but we'd really like to know who has sent us what.
