### ISSUE TITLE
Error opening PDF files in public share when filename contains '+'

### ISSUE THREAD

**Issue by TheColin21** [nextcloud/server#25357]
Steps to reproduce
1. Share a folder via link (in my case password protected)
2. put a PDF file containing a '+' in there
3. try to open it via the share

Expected behaviour
PDF viewer opens file

Actual behaviour
PDFjs somehow get's a 404 trying to open the file, says "missing PDF <path>"

Server configuration
Operating system: Ubuntu 20.04

Web server: Apache

Database: MariaDB

PHP version: 7.4

Nextcloud version: 20.0.5

Updated from an older Nextcloud/ownCloud or fresh install: updated since (guessed) NC 17

Where did you install Nextcloud from: .... nextcloud download server?

List of activated apps:

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - breezedark: 20.0.3
  - bruteforcesettings: 2.0.1
  - camerarawpreviews: 0.7.10
  - checksum: 1.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - documentserver_community: 0.1.8
  - extract: 1.3.0
  - facerecognition: 0.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_antivirus: 3.1.1
  - files_downloadactivity: 1.9.0
  - files_external: 1.11.1
  - files_fulltextsearch: 20.0.0
  - files_markdown: 2.3.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_texteditor: 2.14.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - fulltextsearch: 20.0.0
  - fulltextsearch_elasticsearch: 20.0.0
  - imageconverter: 1.3.1
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - maps: 0.1.8
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - passwords: 2020.12.2
  - phonetrack: 0.6.5
  - photos: 1.2.3
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - ransomware_protection: 1.8.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.5
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - audioplayer
  - encryption
  - metadata
  - nextcloud_announcements

Nextcloud configuration:

Config report
Are you using external storage, if yes which one: local/smb/sftp/...
yes, but not for this share (the others are SFTP/Nextcloud/local)
Are you using encryption: yes/no
no
Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
no

Client configuration
Browser:
Edge Chromium and Firefox
Operating system:
Windows 10 20H2
Logs
Web server error log

2021-01-28 12:52:38 | Error | 84.62.142.194 | 404 | GET /index.php/s/RSGieNqM3TX4zX4/download?path=/path/&files=filename_with_a_+.pdf HTTP/1.0

Nextcloud log does not show errors.

**Comment by kesselb** [comment]
Closing in favour of: https://github.com/nextcloud/viewer/issues/415
