### ISSUE TITLE
Sharing limited to only their group - except admins

### ISSUE THREAD

**Issue by blackerking** [nextcloud/server#25362]
We have different partner and several projects. Sometimes partner should not know from each others involving.
We often use groups and groupfolders but sometimes there are user which are only involved for a short time.
As admin I have to disable the limiting while I add the share to such user. After that I have to enable it again.

It would be faster and a lot safer if admins could share to any user inside the cloud. Not just as long the setting is enabled.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
