### ISSUE TITLE
[Feature request]: create a public folder to host HTML files

### ISSUE THREAD

**Issue by jm-andonegi** [nextcloud/server#2537]
I work with a HTML editor (eXeLearning), so I need an easy way to publish HTML files and I would like to work and publish my files with NextCloud. I know it is not possible to publish files directly in NextCloud, but I was wondering how easy/difficult would be to develop something like this:

1. Use Local storage system to synchronize a folder in NextCloud and a public folder in the server.
2. A configuration option to create a Public folder for an user or a group (both in NextCloud and in the real public folder)
3. A right-click menu to offer to the user the public URL of the file.

It would be something like the (disappeared) Public Folder in Dropbox or Drive. Do you see feasible?

Thanks!

**Comment by nickvergessen** [comment]
I don't think we should do this?

@LukasReschke

**Comment by nickvergessen** [comment]
See https://github.com/nextcloud/server/issues/2523#issuecomment-265115448

**Comment by jancborchardt** [comment]
This would be very interesting and useful indeed. I think the reason it's not done is similar to the direct image link #2523: Without a separate domain this would make your instance vulnerable.

cc @Nextcloud/security for elaboration

**Comment by nickvergessen** [comment]
The response from lukas is at https://github.com/nextcloud/server/issues/2523#issuecomment-265115448

**Comment by jm-andonegi** [comment]
I know this is a closed FR, but I found this service for Google Drive and I think it is an interesting feature:

[https://www-drv.com/index.html](https://www-drv.com/index.html)

**Comment by maneeshsethi** [comment]
Dropbox used to do this, and got rid of it because it wasn't as profitable as requiring a dropbox-logoed download page.

I think this feature could be the killer feature for nextcloud to differentiate (storage-wise) from dropbox.

**Comment by jm-andonegi** [comment]
+1 😊

**Comment by nickvergessen** [comment]
There now is https://apps.nextcloud.com/apps/cms_pico

**Comment by jm-andonegi** [comment]
Hi Nick:

Looks nice, but it's for markdown and my contents are HTML..

**Comment by georgedorn** [comment]
If you are on a host where you have access to shell or some other cron job manager, there's a stop-gap solution.  Create a public web space (a la `public_html`) and a cron job to copy files into that space every X minutes.  It may also need to set permission correctly.  It's a hack, but it works.

**Comment by jm-andonegi** [comment]
Hi George:

This is a [demo](http://exelearning.euskaldunak.eus/DurangokoAzoka/es/carpeta_pblica.html) and an a [paper for CEDEC](http://exelearning.euskaldunak.eus/CEDEC/CEDEC_NextCloud/website_cmo_crear_una_carpeta_pblica_para_los_contenidos_de_exelearning.html) (an institution promoting free software in Education), both in Spanish.

Having an easy way to publish HTML content is an interesting feature. It can be done using tricks or, may be, it could have some kind of help from the tool. Of course, there are so many ideas and other features could be a higher priority but I don't understand the mentioned dangers (I am not a web manager or similar).

Thanks for the tip. :)
