### ISSUE TITLE
Text on 2FA page hard to read

### ISSUE THREAD

**Issue by ChristophWurst** [nextcloud/server#2538]
On the two-factor page, "Log out" and "Use backup codes" are hard to read, especially on bright or contrasty backgrounds:
![bildschirmfoto von 2016-12-06 22-04-35](https://cloud.githubusercontent.com/assets/1374172/20943677/d8b8ebe2-bc00-11e6-8491-ad74b1f6982f.png)
![bildschirmfoto von 2016-12-06 22-05-03](https://cloud.githubusercontent.com/assets/1374172/20943678/d8b931f6-bc00-11e6-80e3-f62b741e4d63.png)

cc @nextcloud/designers

**Comment by Espina2** [comment]
I already post a solution for that here. https://github.com/nextcloud/server/issues/1615

**Comment by jancborchardt** [comment]
We need to simply experiment with the opacity of the black container, make it less transparent. Unfortunately the CSS blur function isn't really there yet cross-browser cause that would be perfect here. cc @nextcloud/designers

(@Espina2 not sure why you keep mentioning that complete overhaul. It would be more helpful to propose fixes issue-specifically instead of making one big change mainly for the sake of change.)

**Comment by jancborchardt** [comment]
@ChristophWurst regarding the other text below, can you put that inside of the container?

**Comment by skjnldsv** [comment]
@jancborchardt svg blur are supported by all browsers! ;)
http://caniuse.com/#feat=svg-filters

**Comment by Espina2** [comment]
I mention that because one of the changes proposed in that issue is for this particular case.

**Comment by skjnldsv** [comment]
@Espina2 could you point it precisely? Because the other thread is kind has kind of too much data! 😆

**Comment by jancborchardt** [comment]
@skjnldsv do we want to go for that then? And put the other text items below (except the footet) in the container?

**Comment by Henni** [comment]
What do we gain from blur, in case of the "worst case scenario" (a completely white background)?

**Comment by skjnldsv** [comment]
@Henni a more or less smooth area in terms of saturation and colours :)

**Comment by jancborchardt** [comment]
@Henni blur will improve the readability of the text because regardless of what’s in the background, the sharpness and noise will be reduced. Currently we use the only slightly transparent dark container to achieve a similar result, but additional blur is even more elegant.
