### ISSUE TITLE
Missing Guest Users in user-management

### ISSUE THREAD

**Issue by Uwe-MrT** [nextcloud/server#25381]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen
/settings/users
if i go into users, there shold be 156 users to delete / modify / etc

### Actual behaviour
/settings/users
Tell us what happens instead
If i go to settings and into my Users, on the Left side i have 156 users on Jeder (everybody)
If i click on Jeder, on the right side i have maybe 35 users
where are the rest of the users ?
most of them are guest users.
i also miss the Group "guests" in this section

/settings/admin/guests
If i go into settings guests
There are all my guests, but i can not delete / modify 

### Server configuration

**Operating system:**
Debian Buster
**Web server:**
Apache2
**Database:**
mysql
Version: 10.3.27
Größe: 114,6 MB
**PHP version:**
Version: 7.4.14
**Nextcloud version:** (see Nextcloud admin page)
20.0.6
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated NC 18 -> NC 19 -> NC 20
**Where did you install Nextcloud from:**
Downloaded from Nextcloud
**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
No errors have been found.
```
</details>

**List of activated apps:**

<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
Enabled:
  - activity: 2.13.4
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - documentserver_community: 0.1.8
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - groupfolders: 8.2.0
  - guests: 1.6.2
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_email: 2.1.0
  - survey_client: 1.8.0
  - text: 3.1.0
  - theming: 1.11.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0

from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "datenportal.penne-pabst.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "https:\/\/datenportal.penne-pabst.de",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "timeout": 0,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "skeletondirectory": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "loglevel": 2,
        "htaccess.RewriteBase": "\/",
        "overwriteprotocol": "https",
        "filesystem_check_changes": 1,
        "theme": ""
    }
}


or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
SMB

**Are you using encryption:** yes/no
NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
Chrome + Edge

**Operating system:**
Windows 10
#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here

```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by Angedestenebres** [comment]
Hey :cat: 

We also noticed the same thing on TeDomum instance with the version 20.0.6.
We use the SSO login (user_saml) and hereafter some information about our server:

- Running on Debian & Docker
- PHP: 7.4.14
- PostgreSQL 11.10

I also noticed we can find missing user in everybody list by using the search feature on the top menu. With that, we are able to manage them, so we have a workaround for the moment :)

**Comment by ngamanye** [comment]
Hello,
we have the same problem.
1. nextcloud 20.0.6
2. php 7.4
3. mariadb
4. ubuntu 20.04

**Comment by rustic** [comment]
I am having the same issue. It looks like the first 27 users are listed alphabetically, the the bottom of the page says "No users in here". I have 58 users and can search for the missing ones but clicking 'Everyone' only shows the first 27.

Nextcloud 20.0.7 (Latest Docker)
Apache/2.4.38 (Debian)
PHP 7.4.15
MariaDB 10.5.8
Users provisioned by SAML

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
