### ISSUE TITLE
Nexcloud 21, NGINX and PHP 8.0.1 doesn't pass the Apps installation step

### ISSUE THREAD

**Issue by squid-f** [nextcloud/server#25395]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.Install NGINX (1.18) & PHP-FPM (PHP8.0.1)
2.Set your database (MariaDB or PostgreSQL lead to the same issue)
3.Adjust php and php-fpm conf files according to nextcloud requirement
4.Create the nextcloud vHost conf file for NGINX (admin manual one) for nextcloud running in a sub-folder and installed in /var/www/nextcloud
5.Go to http://localhost/nextcloud
6.The installation wizard page is reached
7.Create admin user and enter database credentials
8.Click on Finish setup  -> the wheel spins and and internal server error is displayed.

### Expected behaviour
The page showing apps installation should appear.
=> It worked with the same configuration files and php8.0.0  <=

### Actual behaviour
Internal Server Error
![Screenshot_nc_app-step_error](https://user-images.githubusercontent.com/11743181/106312572-2a8d7800-6267-11eb-87db-5f8f4396d965.png)

### Server configuration

**Operating system:**
Mageia 8 beta2
**Web server:**
NGINX 1.18

**Database:**
postgres (PostgreSQL) 13.1
or 
mysql  Ver 15.1 Distrib 10.5.8-MariaDB, for Linux (x86_64) using readline 5.1

**PHP version:**
PHP 8.0.1 (cli) (built: Jan 26 2021 17:45:10) ( ZTS )
Copyright (c) The PHP Group
Zend Engine v4.0.1, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.1, Copyright (c), by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 21 beta6 or beta7 or beta8 (I have not tested older beta)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.   

404 not found  - NGINX

```
</details>

**List of activated apps:**

step not reached

<details>
```
 Command "app:list" is not defined.
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

=> Nextcloud is not installed - only a limited number of commands are available
         There are no commands defined in the "config" namespace.  

or config.php :

<?php
$CONFIG = array (
  'instanceid' => 'ocv5i6fqt6mf',
  'passwordsalt' => 'oX098//z/nVkljPy//2Rwo08u/Tt79',
  'secret' => 'KN8jh3UwCjHHQB0AMPWG+5Ej7Ld0WKjgSsQfEH32MP8CsvNL',
  'trusted_domains' => 
  array (
    0 => 'localhost',
  ),
  'datadirectory' => '/data/ncdata',
  'dbtype' => 'pgsql',
  'version' => '21.0.0.15',
  'overwrite.cli.url' => 'https://localhost/nextcloud',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'adminpgsql',
  'dbpassword' => 'pwd-nc',
);


```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

### Client configuration
Firefox 78.6.1esr 64bit 
or
Falkon 3.1.0

**Operating system:**
Mageia 8 beta

#### Web server error log
<details>
<summary>Web server error log</summary>

```
2021/01/28 10:24:07 [error] 1269#1269: *2 FastCGI sent in stderr: "PHP message: {"reqId":"WzDNqxBLH706baE3w1l8","level":3,"time":"2021-01-28T09:24:07+00:00","remoteAddr":"::1","user":"--","app":"PHP","method":"GET","url":"/nextcloud/","message":{"Exception":"Error","Message":"session_start(): Ignoring session_start() because a session is already active at /var/www/nextcloud/lib/private/Session/Internal.php#207","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::","args":[8,"session_start(): Ignoring session_start() because a session is already active","/var/www/nextcloud/lib/private/Session/Internal.php",207]},{"function":"session_start","args":[{"cookie_samesite":"Lax"}]},{"file":"/var/www/nextcloud/lib/private/Session/Internal.php","line":207,"function":"call_user_func_array","args":["session_start",[{"cookie_samesite":"Lax"}]]},{"file":"/var/www/nextcloud/lib/private/Session/Internal.php","line":217,"function":"invoke","class":"OC\\Session\\Internal","type":"->","args":["session_start",[{"cookie_samesite":"Lax"}],true]},{"file":"" while reading response header from upstream, client: ::1, server: localhost, request: "GET /nextcloud/ HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php-fpm/php-fpm.sock:", host: "localhost"
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
No nextcloud.log created at this point
```
</details>

#### Browser log
n/a

**Comment by acsfer** [comment]
It may be because of https://github.com/nextcloud/server/issues/25398
Please retry once the appstore is back again.
