### ISSUE TITLE
External storage support folder will replace Nextcloud's folder with same name

### ISSUE THREAD

**Issue by weiw11** [nextcloud/server#25397]
### Steps to reproduce
1. Create an external storage with same name as a folder in your Nextcloud instance.
2. Nextcloud will show the external storage folder instead of the Nextcloud folder.

### Expected behaviour
Nextcloud should create a new folder appending a number (#) to the end of the folder, as sharing a folder with the same name will append a number.

### Actual behaviour
Nextcloud shows external storage folder instead of Nextcloud folder and essentially "replaces" the existing folder. Renaming the external storage folder will bring the Nextcloud folder back.

### Server configuration

**Operating system:**  Ubuntu 20.04

**Web server:** Nginx

**Nextcloud version:** 20.0.4

**Where did you install Nextcloud from:** Snap

**Comment by szaimen** [comment]
Sry but this is not fixable from our side. The better way is to configure a share_folder for your instance.
![image](https://user-images.githubusercontent.com/42591237/123082203-110be900-d41f-11eb-844e-41aed5e424b0.png)
https://docs.nextcloud.com/server/20/admin_manual/configuration_server/config_sample_php_parameters.html#:~:text='share_folder'%20%3D%3E%20'%2F'%2C
