### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by HLFH** [nextcloud/server#25396]
### Steps to reproduce
Update PHP to PHP 8.
Then you get the bug:
> This version of Nextcloud is not compatible with > PHP 7.4.
> You are currently running 8.0.1.

### Expected behaviour
Nextcloud 20.0.6 should be compatible with PHP 8

### Actual behaviour
Nextcloud 20.0.6 is not compatible with PHP 8

### Server configuration

**Operating system:** Arch Linux

**Web server:** Nginx

**Database:** MySQL

**PHP version:** 8.0.1

**Nextcloud version:** 20.0.6

**Comment by go2sh** [comment]
Nextcloud 21 will be supporting PHP8. ArchLinux does provide a php7 package like a few days ago. Install that and you are good to go. :-)

**Comment by HLFH** [comment]
I am not a fan of PHP downgrades. I have done a [manual upgrade](https://docs.nextcloud.com/server/latest/admin_manual/maintenance/manual_upgrade.html) to Nextcloud 21.

**Comment by go2sh** [comment]
No downgrade. Arch introduced side-by-side php packages for php7 and php8 exactly to support nextcloud and other apps, that are not compatible with php8 yet.

**Comment by debian-user-france1** [comment]
I downloaded the newest version of nextcloud https://download.nextcloud.com/server/releases/nextcloud-23.0.2.zip, using php 8.1.3 and it doesn't work. Can I work-around by changing a configuration file?

**Comment by go2sh** [comment]
@debian-user-france1 PHP8.1 is not supported. See #29287

**Comment by HLFH** [comment]
@go2sh Thanks btw. I am currently using both php7 and php8 so I can run Nextcloud and other apps. Best advice ever ;)
