### ISSUE TITLE
Apps do not appear in the App Store - https://apps.nextcloud.com timeout

### ISSUE THREAD

**Issue by borjapazr** [nextcloud/server#25398]
I have deployed Nextcloud (20.0.6) using Docker and when I access the apps menu the App Store apps are not loaded. Only installed and recommended apps are displayed.

A few days ago it worked correctly, but now it does not. I have seen that https://apps.nextcloud.com is not accessible, which may be the cause. Is there a problem with this resource or is it a version problem?

![image](https://user-images.githubusercontent.com/9295713/106337677-14e17800-6292-11eb-8166-a1b0104dfb05.png)

**Comment by AfroUSApl** [comment]
Yes, I have the same thing.
![Screenshot_20210129-234926_Firefox](https://user-images.githubusercontent.com/33943666/106338839-bbc31580-628c-11eb-8dc5-65e809c37a33.jpg)
![Screenshot_20210129-234957_Firefox](https://user-images.githubusercontent.com/33943666/106338842-bf569c80-628c-11eb-9c36-4362889dfca8.jpg)

**Comment by chenxiaoqino** [comment]
This is a duplicate bug of #23334

**Comment by tabp0le** [comment]
> 
> 
> This is a duplicate bug of #23334

No, it's not. This Issue is an actual outage of https://apps.nextcloud.com.

**Comment by chenxiaoqino** [comment]
A similar and related bug is #23349

**Comment by borjapazr** [comment]
Who maintains apps.nextcloud.com?

**Comment by davoud-najjari** [comment]
outage of https://apps.nextcloud.com
When it will be accessible?

**Comment by acsfer** [comment]
Time to move to a CDN; Nextcloud can't grow it's users base constantly a keep it's distribution services (apps, updates...) in a VPS 🦘

**Comment by barrydegraaff** [comment]
Also the installer should abort if apps.nextcloud.com is down, or warn the user. Upgrading from zip/tgz results in an installation w/o apps. No TOTP no SAML == no login.

**Comment by acsfer** [comment]
Let's move this discussion into https://github.com/nextcloud/appstore/issues/761 as there are more details there and a possible solution to deploy a appstore cache with Docker. Read the comments there.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/appstore/issues/761 as the original issue is solved.
