### ISSUE TITLE
Installer should check if apps.nextcloud.com is online before removing apps on upgrade

### ISSUE THREAD

**Issue by barrydegraaff** [nextcloud/server#25407]
Ran the installer over GUI and CLI, to upgrade from 20.0.0.4 to 20.0.0.5 (on multiple installations), all went fine, but since apps.nextcloud.com was down, apps where not installed after the upgrade.

As a result the TOTP and SAML apps could not be downloaded and I was unable to login.

Found back-up codes only to find a Nextcloud instances with files tab only. No calendar, no contacts etc etc.

The installer should pre-download the apps before removing them from the local installation OR abort if apps.nextcloud.com is down.

Additionally the documentation to compile apps from Github source is poor.

**Comment by kesselb** [comment]
> Additionally the documentation to compile apps from Github source is poor.

https://github.com/nextcloud/user_saml/releases
https://github.com/nextcloud/twofactor_totp/releases

Might be easier than compiling yourself. To compile yourself have a look at the Makefile's.

**Comment by barrydegraaff** [comment]
Thanks for pointing out the releases page, I forgot to look there.


I looked at the make files, but they do require some set-up to work. 
Anyways, good to have the releases page :-p

**Comment by szaimen** [comment]
cc @nextcloud/server-triage is this feasible?
