### ISSUE TITLE
https://apps.nextcloud.com/ seems to be down.

### ISSUE THREAD

**Issue by davoud-najjari** [nextcloud/server#25406]
https://apps.nextcloud.com/ seems to be down.

**Comment by acsfer** [comment]
Time to move to a CDN; Nextcloud cant grow it's users base constantly a keep it's distribution services (apps, updates...) in a VPS 🦘

**Comment by acsfer** [comment]
Closing in flavour of https://github.com/nextcloud/server/issues/25398
