### ISSUE TITLE
Login with Client Mac not possible on 10.0.1

### ISSUE THREAD

**Issue by reinerj** [nextcloud/server#2540]
We upgraded our install from 10.0 to 10.0.1. Login from browser work as excepted. Wth the desktop client it does not work anymore. 

### Expected behaviour
Client should be able to connect

### Actual behaviour
Secure connect not possible. Also http not possible 

### Server configuration
**Operating system**:
Nextcloud in Docker

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.6

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Update from 10.0

**Where did you install Nextcloud from:**
Download from th project site and installed on our image

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - comments: 1.0.0
  - dav: 1.0.1
  - encryption: 1.3.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_automatedtagging: 1.1.1
  - files_retention: 1.0.0
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - firstrunwizard: 1.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - external
  - federation
  - files_external
  - files_pdfviewer
  - files_videoplayer
  - gallery
  - user_external
  - user_ldap
  - user_saml

**The content of config/config.php:**
{
    "system": {
        "datadirectory": "\/var\/www\/data",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "installedat": "1330942568.9122",
        "lastupdatedat": "1337418792.0236",
        "dbname": "xxxxxx",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "allowZipDownload": true,
        "maxZipInputSize": 102400000,
        "log_type": "owncloud",
        "instanceid": "508930ea5d155",
        "loglevel": 0,
        "maintenance": false,
        "theme": "",
        "forcessl": true,
        "trusted_domains": [
            "www.xxxxx",
            "xxxx"
        ],
        "0": [
            "www.xxxxx"
        ],
        "secret": "***REMOVED SENSITIVE VALUE***",
        "forceSSLforSubdomains": true,
        "mail_from_address": "do-not-reply",
        "mail_smtpmode": "smtp",
        "mail_domain": "xxxxxx",
        "memcache.local": "\\OC\\Memcache\\ArrayCache",
        "trashbin_retention_obligation": "auto",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "mail.xxxxx",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
NO
**Are you using encryption:** yes/no
yes

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
NO

### Client configuration
**Browser:**
FF, Safari

**Operating system:**
Mac

#### Nextcloud log (data/nextcloud.log)
{"reqId":"nbQr4EglfrhHDporKQnd","remoteAddr":"79.248.xxx.xxx","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No 'Authorization: Basic' header found. Either the client didn't send one, or the server is mis-configured\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#1 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#2 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#3 \\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/lib\\\/Server.php(184): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/apps\\\/dav\\\/appinfo\\\/v2\\\/remote.php(30): OCA\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/html\\\/remote.php(165): require_once('\\\/var\\\/www\\\/html\\\/a...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php\",\"Line\":188,\"User\":\"xxxx\"}","level":0,"time":"2016-12-06T15:00:27+00:00","method":"PROPFIND","url":"\/remote.php\/dav\/principals\/users\/\/","user":""}
#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

Browser is working ...

**Comment by reinerj** [comment]
just updated to 10.0.2 and still the same issue ...

**Comment by reinerj** [comment]
and the update to 11.0.0. <still the same problem, someone?

**Comment by nickvergessen** [comment]
Sorry you got no reply. Can you check again with 11.0.1 or 10.0.3?

**Comment by nickvergessen** [comment]
Which link are you trying to connect to?

**Comment by reinerj** [comment]
It did not work with 11.0.0  but we can try it again with 11.0.1 and come back with the result

**Comment by reinerj** [comment]
works now, thanks
