### ISSUE TITLE
Allow multiple accounts to sync the same local folder

### ISSUE THREAD

**Issue by kudumi** [nextcloud/server#2541]
when using the multi-account feature it's not possible to sync the same folder to multiple servers.

I think, owncloud users use symlinks to get it working but it doesn't work with nextcloud.
https://github.com/owncloud/client/issues/3764

any working solution would be great!

**Comment by nickvergessen** [comment]
Currently the nextcloud sync client is only a themed version of the owncloud sync client.
So the issue you linked is what will keep track of the request.
