### ISSUE TITLE
Additional folder move option 

### ISSUE THREAD

**Issue by thomasgg23** [nextcloud/server#25410]
Would be nice to have the "move or copy" folder option also within the folder which I want to move.

Right now if you want to move the folder you have to move up one folder, search the folder you have been working in and than move the folder.
When you have a lot of folders you have to search the right folder.

Would be a cleaner workflow, if you can move the "folder from inside the folder".

![image](https://user-images.githubusercontent.com/2633051/106380031-fffb0680-63af-11eb-9220-58d5eb2f692e.png)

**Comment by szaimen** [comment]
cc @nextcloud/designers does this make sense?

**Comment by thomasgg23** [comment]
If you are inside a folder you can move a file / folder with clicking on the three dots (or right click) and choose the "move or copy" option.

But you cannot move the current folder when you are inside the folder. You have to go to the parent folder and there you have the option to move the folder with the three dots (or right click).

It would be nice to have the same option in the top bar (breadcrum navigation) perhaps in the sharing option.

**Comment by skjnldsv** [comment]
@jancborchardt

**Comment by bes1002t** [comment]
This is quite different as most file browsers work and I don't see a strong reason why this redundancy is needed. You don't move directories that  often, it would be no pain to go one directory up to move the child directory.

**Comment by jancborchardt** [comment]
Doesn’t seem to be that much need for it, and as was said other file browsers don’t do it either.

For sharing, it was really evident and annoying that this was missing inside the folder. For moving, not really.
