### ISSUE TITLE
The #rich-workspace overlaps the upload menu on link share

### ISSUE THREAD

**Issue by enaut** [nextcloud/server#25416]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. create a share by link with upload permission
2. go to the link and try to upload a file
3. see the issue (screenshot)

### Expected behaviour
It should look like this: 
![grafik](https://user-images.githubusercontent.com/290005/106396981-78db7c00-640b-11eb-9c3f-da2552daec42.png)

### Actual behaviour
It looks like this (notice how the buttons are partially hidden... if the path is longer the buttons are hidden completely and an upload is not possible anymore):
![hidden-menu](https://user-images.githubusercontent.com/290005/106396943-4893dd80-640b-11eb-87de-323757fe269d.png)

### Possible Fix

using a custom css extension I added the following rule which might break something else but solved this problem:

```css
#rich-workspace {
  z-index: 0;
}
```

### Server configuration

**Operating system:** Ubuntu

**Web server:** Nginx

**Nextcloud Version:** 20.0.6 (I think this only happened after the update from 20.0.5)

[...]
I don't think  any of this matters... but I can provide it if requested.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/27588
