### ISSUE TITLE
NC21: Impossible to identify DBAL UniqueConstraintViolation exception

### ISSUE THREAD

**Issue by paulijar** [nextcloud/server#25415]
I already had the Music app running smoothly on NC21 beta5, but now I tested beta8 and noticed that the compatibility is broken again, due to the commit 2c9cdc1cd. In the Music app, I have around 10 occasions where I need to catch the `UniqueConstraintViolationException` and act upon it. Now, this is no longer directly possible as this exception from DBAL is wrapped by `\OCP\DB\Exception`.

As I understood it, the way to handle such situations should now be like
```
try {
	// some database operation
} catch (\OCP\DB\Exception $e) {
	if ($e->getReason() == \OCP\DB\Exception::REASON_UNIQUE_CONSTRAINT_VIOLATION) {
		// handle the exception
	} else {
		throw $e;
	}
}
```

However, this doesn't work either. This is because the `UniqueConstraintViolationException` is actually inherited from `DriverException`, and hence, the returned reason will be very generic `REASON_DRIVER`.

In the commit message 2c9cdc1cd, it is stated that reason-specific exception types could be added later, but that even the current system is "better than the dependency on dbal". As an application developer, I strongly feel that this is not better but worse. It *may* save some problems later, but it *will* cause problems right now. 

So I really hope that the reason-specific exception type at least for the unique constraint violation will happen before the NC21 is released. Writing code like the snippet shown above 10 times into my code would make me throw up a little into my mouth. If the reason-specific exceptions are added by some later NC version, then I still would have to keep that ugly code around as long as I want to support NC21 which is probably many years.

ping @ChristophWurst

**Comment by dartcafe** [comment]
As far as I can notice `Doctrine\DBAL\Exception\UniqueConstraintViolationException` is still throws, even in NC21-beta8.

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/blob/2c9cdc1cdbf900a8578c80075f5ea2da479c4f80/lib/private/DB/Exceptions/DbalException.php#L78-L89

I guess it should work if you move the generic checks to the end. Mind to sent a pull request?

**Comment by ChristophWurst** [comment]
> I guess it should work if you move the generic checks to the end. Mind to sent a pull request?

:+1: Yes please

And sorry @paulijar for this regression. This dbal migration hit us really bad but without it Nextcloud 21 wouldn't support php8.

Additionally we can have a dedicated exception for unique constraint violations :v:

**Comment by dartcafe** [comment]
If TableNotFoundException could also be added, would help us in polls. 
But can anyone explain, why we can still catch these exception?

**Comment by paulijar** [comment]
> Additionally we can have a dedicated exception for unique constraint violations ✌️

Great, I would like that.

**Comment by paulijar** [comment]
@ChristophWurst
I see there's still no dedicated exception for unique constraint violation (or others) in NC21 PR2. Does this mean that it shall not be there in 21.0.0 either? According to https://github.com/nextcloud/server/wiki/Maintenance-and-Release-Schedule, the release is already right around the corner. Would it change anything if I made a PR?

**Comment by ChristophWurst** [comment]
Yeah, this one didn't make it into Nextcloud 21. We can have it in 22 at the earliest. A PR for this would be highly appreciated.

**Comment by paulijar** [comment]
@ChristophWurst 
That displeases me greatly :(. It means that if I ever want to support NC versions >20, then I just have to live with the currently available API. I can't claim support for NC versions "13-20 and 22". This is a lost game for me.

I'm now planning to add some kind of custom wrapper for `IDBConnection` within my app. There, I could catch the exceptions from NC and throw my own exceptions instead, and this would prevent the horrors of the current API from spreading all over my code. But this will leave me with zero incentive to make the PR for the NC server. If the dedicated platform exception is not there in NC21, then it will do me no good to have it in some later version.

**Comment by ChristophWurst** [comment]
To be fair anything older than Nextcloud 19 is EOL and therefore supporting it doesn't really make any sense IMO.

While I understand the disappointment there is nothing I can do. This migration wasn't smooth but I hope you can see that we didn't really have much of a choice. The old dbal exception was moved with the dbal upgrade. And the old leaked type was never intended. Sorry.

**Comment by ChristophWurst** [comment]
I would, however, highly appreciate if you could actively help improve the API.
