### ISSUE TITLE
Option: Limit apps to users

### ISSUE THREAD

**Issue by hansimausisteffiwurstbrot** [nextcloud/server#25411]
Hi,

it's good to be able to limit apps to groups. It would be helpful to limit the apps to users.

Any thoughts on this?

Cheers!

**Comment by szaimen** [comment]
This is already doable:
1. Create a group with people that shall have access to certain apps
2. Limit certain apps to this group via the appstore

**Comment by hansimausisteffiwurstbrot** [comment]
> This is already doable:

Thanks for your hint. I know about this way but it's not what I'm proposing as it's based on groups. So I see it as a workaround if you actually want to manage the app-access on an individual basis.

I don't want people that don't have any connection in the same group.

**Comment by Mirokko** [comment]
One group per user could help.

**Comment by kurn77** [comment]
Hello, I fully agree with your proposal > I don't understand why limitation is done only to a group instead of being possible to a group or a single user.

Sometimes, we cannot let people have any connection in the same group, and one group per user is not very user friendly as groups are not managed efficiently as a list easily manageable.

Just beeing able to limit apps to one user in addition to a group could be really helpfull.

**Comment by hansimausisteffiwurstbrot** [comment]
> 
> 
> One group per user could help.

Thanks for the though, but: So I end up having hundreds of groups? I Like groups being groups and not another level of complexity for setting the app-access for users.

Yeah, might work in some small cases but it's a workaround, too.

**Comment by jfp62** [comment]
Does anyone know where it is documented or demonstrated how to limit available apps to a group resp. a user ?
Thanks in advance
Joe

**Comment by hansimausisteffiwurstbrot** [comment]
> 
> 
> Does anyone know where it is documented or demonstrated how to limit available apps to a group resp. a user ?

Do you know how to do it?

Create group -> Add user -> Go to 'Apps' -> Select the desired App -> Select 'Limit to groups' (if available) -> Select desired group

![grafik](https://user-images.githubusercontent.com/71875177/109231444-e9857680-77c6-11eb-85f5-418d6751a62a.png)

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by zak39** [comment]
Hi ! :wave: 

Do it exists an API to check the `Limit to groups` case and fill it sending a group list ? :slightly_smiling_face:

**Comment by szaimen** [comment]
Hi, please ask your question at https://help.nextcloud.com/c/dev/11
Thanks!

**Comment by madeinsa** [comment]
Hello, first I would like to thank you for this great effort with all love. Thank you.

I wish I could give a user access to just one app


For example, I have clients that I want to have only the Dock

Is there a way to do this?

**Comment by 4jNsY6fCVqZv** [comment]
@szaimen More than three years later, I would like to ask whether you can imagine reopening the issue and putting it on your roadmap.

**Comment by Ruthalas** [comment]
Just wanted to chime in and agree that this feature makes sense.
I'd like to add users and only give them access to Talk, for example.
