### ISSUE TITLE
Update to 19.0.8 stops because of already existing table: c1nextcloud.oc_recent_contact

### ISSUE THREAD

**Issue by bgn68** [nextcloud/server#25419]
Update to 19.0.8 stops because of already existing table: c1nextcloud.oc_recent_contact

Complete messasges:

Nextcloud
Aktualisierung auf 19.0.8

Doctrine\DBAL\Schema\SchemaException: The table with name 'c1nextcloud.oc_recent_contact' already exists.
Detaillierte Protokollmeldungen

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

Reparaturschritt: Drop account terms table when migrating from ownCloud

Das Datenbankschema wird aktualisiert

Datenbank aktualisiert

"activity" aktualisiert auf 2.12.1

Suche nach einer Aktualisierung für die App "accessibility" im App-Store

App-Store auf Aktualisierung für die App "accessibility" geprüft

Suche nach einer Aktualisierung für die App "activity" im App-Store

App-Store auf Aktualisierung für die App "activity" geprüft

Suche nach einer Aktualisierung für die App "calendar" im App-Store

App-Store auf Aktualisierung für die App "calendar" geprüft

Suche nach einer Aktualisierung für die App "checksum" im App-Store

App-Store auf Aktualisierung für die App "checksum" geprüft

Suche nach einer Aktualisierung für die App "cloud_federation_api" im App-Store

App-Store auf Aktualisierung für die App "cloud_federation_api" geprüft

Suche nach einer Aktualisierung für die App "comments" im App-Store

App-Store auf Aktualisierung für die App "comments" geprüft

Suche nach einer Aktualisierung für die App "contacts" im App-Store

App-Store auf Aktualisierung für die App "contacts" geprüft

Suche nach einer Aktualisierung für die App "dav" im App-Store

App-Store auf Aktualisierung für die App "dav" geprüft

Suche nach einer Aktualisierung für die App "drawio" im App-Store

App-Store auf Aktualisierung für die App "drawio" geprüft

Suche nach einer Aktualisierung für die App "federatedfilesharing" im App-Store

App-Store auf Aktualisierung für die App "federatedfilesharing" geprüft

Suche nach einer Aktualisierung für die App "federation" im App-Store

App-Store auf Aktualisierung für die App "federation" geprüft

Suche nach einer Aktualisierung für die App "files" im App-Store

App-Store auf Aktualisierung für die App "files" geprüft

Suche nach einer Aktualisierung für die App "files_markdown" im App-Store

App-Store auf Aktualisierung für die App "files_markdown" geprüft

Suche nach einer Aktualisierung für die App "files_pdfviewer" im App-Store

App-Store auf Aktualisierung für die App "files_pdfviewer" geprüft

Suche nach einer Aktualisierung für die App "files_rightclick" im App-Store

App-Store auf Aktualisierung für die App "files_rightclick" geprüft

Suche nach einer Aktualisierung für die App "files_sharing" im App-Store

App-Store auf Aktualisierung für die App "files_sharing" geprüft

Suche nach einer Aktualisierung für die App "files_trashbin" im App-Store

App-Store auf Aktualisierung für die App "files_trashbin" geprüft

Suche nach einer Aktualisierung für die App "files_versions" im App-Store

App-Store auf Aktualisierung für die App "files_versions" geprüft

Suche nach einer Aktualisierung für die App "files_videoplayer" im App-Store

App-Store auf Aktualisierung für die App "files_videoplayer" geprüft

Suche nach einer Aktualisierung für die App "firstrunwizard" im App-Store

App-Store auf Aktualisierung für die App "firstrunwizard" geprüft

Suche nach einer Aktualisierung für die App "gpxpod" im App-Store

App-Store auf Aktualisierung für die App "gpxpod" geprüft

Suche nach einer Aktualisierung für die App "logreader" im App-Store

App-Store auf Aktualisierung für die App "logreader" geprüft

Suche nach einer Aktualisierung für die App "lookup_server_connector" im App-Store

App-Store auf Aktualisierung für die App "lookup_server_connector" geprüft

Suche nach einer Aktualisierung für die App "metadata" im App-Store

App-Store auf Aktualisierung für die App "metadata" geprüft

Suche nach einer Aktualisierung für die App "nextcloud_announcements" im App-Store

App-Store auf Aktualisierung für die App "nextcloud_announcements" geprüft

Suche nach einer Aktualisierung für die App "notifications" im App-Store

App-Store auf Aktualisierung für die App "notifications" geprüft

Suche nach einer Aktualisierung für die App "oauth2" im App-Store

App-Store auf Aktualisierung für die App "oauth2" geprüft

Suche nach einer Aktualisierung für die App "password_policy" im App-Store

App-Store auf Aktualisierung für die App "password_policy" geprüft

Suche nach einer Aktualisierung für die App "photos" im App-Store

App-Store auf Aktualisierung für die App "photos" geprüft

Suche nach einer Aktualisierung für die App "polls" im App-Store

App-Store auf Aktualisierung für die App "polls" geprüft

Suche nach einer Aktualisierung für die App "provisioning_api" im App-Store

App-Store auf Aktualisierung für die App "provisioning_api" geprüft

Suche nach einer Aktualisierung für die App "serverinfo" im App-Store

App-Store auf Aktualisierung für die App "serverinfo" geprüft

Suche nach einer Aktualisierung für die App "settings" im App-Store

App-Store auf Aktualisierung für die App "settings" geprüft

Suche nach einer Aktualisierung für die App "sharebymail" im App-Store

App-Store auf Aktualisierung für die App "sharebymail" geprüft

Suche nach einer Aktualisierung für die App "spreed" im App-Store

App-Store auf Aktualisierung für die App "spreed" geprüft

Suche nach einer Aktualisierung für die App "support" im App-Store

App-Store auf Aktualisierung für die App "support" geprüft

Suche nach einer Aktualisierung für die App "survey_client" im App-Store

App-Store auf Aktualisierung für die App "survey_client" geprüft

Suche nach einer Aktualisierung für die App "systemtags" im App-Store

App-Store auf Aktualisierung für die App "systemtags" geprüft

Suche nach einer Aktualisierung für die App "tasks" im App-Store

App-Store auf Aktualisierung für die App "tasks" geprüft

Suche nach einer Aktualisierung für die App "text" im App-Store

App-Store auf Aktualisierung für die App "text" geprüft

Suche nach einer Aktualisierung für die App "theming" im App-Store

App-Store auf Aktualisierung für die App "theming" geprüft

Suche nach einer Aktualisierung für die App "twofactor_backupcodes" im App-Store

App-Store auf Aktualisierung für die App "twofactor_backupcodes" geprüft

Suche nach einer Aktualisierung für die App "updatenotification" im App-Store

App-Store auf Aktualisierung für die App "updatenotification" geprüft

Suche nach einer Aktualisierung für die App "viewer" im App-Store

App-Store auf Aktualisierung für die App "viewer" geprüft

Suche nach einer Aktualisierung für die App "workflowengine" im App-Store

App-Store auf Aktualisierung für die App "workflowengine" geprüft

Doctrine\DBAL\Schema\SchemaException: The table with name 'c1nextcloud.oc_recent_contact' already exists.

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/21293
