### ISSUE TITLE
Use local storage as a given user

### ISSUE THREAD

**Issue by chmeeedalf** [nextcloud/server#25413]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Describe the solution you'd like**
Something I haven't found, but would be really nice to have, is a way to use local storage, as on a NAS, as a specific user.  For instance, 3 users on a Nextcloud instance, each one has an account on the NAS the instance is hosted on, each has his/her own home directory from the NAS as a "local" external storage, written to from Nextcloud as his/her own UID. 

**Describe alternatives you've considered**
Could use a SMB connection to the same box, but that seems a little silly.

I haven't found another issue opened related to this, so I hope this isn't a duplicate issue.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by chmeeedalf** [comment]
Hi @szaimen is there any guide to writing my own backend?  I've looked, but all I've found thus far are other backends as examples, rather than a basic skeleton or reference.  I would love to contribute a backend if I'm able to write one myself.

**Comment by szaimen** [comment]
Hi there, please use localhost SFTP storage with that because otherwise your users would be able to mount any directory on your server to itself which would be a huge security issue.

**Comment by szaimen** [comment]
Apart from that if there is a folder structure that has the same user id you could also use the placeholder for that and just mount /local/$user

**Comment by chmeeedalf** [comment]
Interesting idea, I hadn't thought of that, thanks!

My thought was for something that only the administrator would be able to configure, like: permit only /home/$NAME for the user, or a set of directories, which I believe is already supported for some backends (I don't have a nextcloud instance setup currently, my instance died a month ago, so I could be wrong on that memory?), and the user can enable it.
