### ISSUE TITLE
Custom Emoji Support

### ISSUE THREAD

**Issue by SethFalco** [nextcloud/server#25428]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
My understanding is that currently Nextcloud only supports emotes via copying over the UTF-8 characters right now.  
I've also noticed some issues exist requesting for emoji support, such as #10293 for Twemoji.

Unfortunately, this doesn't give users the ability to use their own set of emotes, though.

**Describe the solution you'd like**
As well as the above, it'd be great if Nextcloud could allow users to use custom emotes, I think the best way to do this would be to use a folder in Files.

This could either be:
* /Emojis/
* /Photos/Emojis/

For example if I have the following emotes:
* /Emojis/pandaAww.png ![pandaAww](https://user-images.githubusercontent.com/22801583/106547340-56318c00-650d-11eb-83bd-a029336afa5d.png)
* /Emojis/pandaThink.png ![pandaThink](https://user-images.githubusercontent.com/22801583/106547515-9f81db80-650d-11eb-9add-7c08d46e1d16.png)
* /Emojis/pandaShock.png ![pandaShock](https://user-images.githubusercontent.com/22801583/106547543-b1fc1500-650d-11eb-8bd2-e3dd1f3ba348.png)

Then one could do :pandaAww: to refer to the emote in other apps that use Markdown like Deck, and have it appear in the emote picker under a custom section.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by felda** [comment]
My community would like to move away from Discord and to a self-hosted NextCloud instead. 

The one thing that turns most of my community off to NextCloud Talk is the lack of custom emoji and custom stickers which are used for many different purposes. Definitely interested in this for sure.

**Comment by ninaran** [comment]
Yup, we have also moved from Discord to a self-hosted Nextcloud and the lack of custom emotes is currently our main pain point with it. Sure, nothing important, but it does give a chat service some soul.

**Comment by bwyard** [comment]
We would also like custom emojis, our company uses nextcloud to maintain data soverirngity for us and clients and custom emojis would be a very high pleasing addition
