### ISSUE TITLE
Avatar.php Garbled code

### ISSUE THREAD

**Issue by 0xblack** [nextcloud/server#25427]
Avatar.php When the avatar is generated automatically, if the character string is Chinese, the scrambled avatar image will appear.

**Comment by hanfeicode** [comment]
how to fix it ?
 if the character string is Chinese, the scrambled avatar image will appear

**Comment by hanfeicode** [comment]
1、copy windows C:\Windows\Fonts\SIMSUN.TTC     to docker 	/usr/share/fonts
```
root@d8e51f6e7c8f:/var/www/html# du -sh /usr/share/fonts/*
18M	/usr/share/fonts/SIMSUN.TTC
```
![image](https://user-images.githubusercontent.com/10413864/119340754-84f28e80-bcc5-11eb-9e8a-7ccc5b03df14.png)

2、vim ./lib/private/Avatar/Avatar.php
    $font = '/usr/share/fonts/SIMSUN.TTC'; # redefined $font
```
        protected function generateAvatar($userDisplayName, $size) {
                $text = $this->getAvatarText();
                $backgroundColor = $this->avatarBackgroundColor($userDisplayName);

                $im = imagecreatetruecolor($size, $size);
                $background = imagecolorallocate(
                        $im,
                        $backgroundColor->r,
                        $backgroundColor->g,
                        $backgroundColor->b
                );
                $white = imagecolorallocate($im, 255, 255, 255);
                imagefilledrectangle($im, 0, 0, $size, $size, $background);

                $font = __DIR__ . '/../../../core/fonts/NotoSans-Regular.ttf';
                $font = '/usr/share/fonts/SIMSUN.TTC'; # redefined $font
```
 
and then retrun false in  function  generateAvatarFromSvg
```
        protected function generateAvatarFromSvg(int $size) {
                        return false;

```

3、reason

generateAvatarFromSvg use svg , 
generateAvatar use GD
GD  effect is batter then svg,
![image](https://user-images.githubusercontent.com/10413864/119341472-617c1380-bcc6-11eb-8028-ef07a439d92d.png)
![image](https://user-images.githubusercontent.com/10413864/119341537-7c4e8800-bcc6-11eb-90ab-ff0f259f2788.png)


4、if you use generateAvatarFromSvg,
```
redefined $font ok ,only bad effect ,233333
                $font = '/usr/share/fonts/SIMSUN.TTC'; # redefined $font
``` 

@0xblack

**Comment by 0xblack** [comment]
ok,thank you so match

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.3?
