### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by weinic** [nextcloud/server#25439]
Hello, 
I have several errors of this type in my logs. 
Unfortunately I don't know where these come from.

My guess is that the bug has to do with this thing: #17610

[PHP] Error: Error: Undefined index: {http://owncloud.org/ns}owner-principal at /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php#1789 at <<closure>>

0. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php line 1789
   OC\Log\ErrorHandler::onError(8, "Undefined index ... l", "/srv/dev-disk-b ... p", 1789, {0: "And 11 more ... ]})
1. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/apps/dav/lib/Search/TasksSearchProvider.php line 108
   OCA\DAV\CalDAV\CalDavBackend->searchPrincipalUri("principals/users/admin", "Biotonne", ["VTODO"], ["SUMMARY","DESCRIPTION","CATEGORIES"], [], {limit: 5,offset: null})
2. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Search/SearchComposer.php line 162
   OCA\DAV\Search\TasksSearchProvider->search(OC\User\User {}, OC\Search\SearchQuery {})
3. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/core/Controller/UnifiedSearchController.php line 110
   OC\Search\SearchComposer->search(OC\User\User {}, "tasks", OC\Search\SearchQuery {})
4. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 169
   OC\Core\Controller\UnifiedSearchController->search("tasks", "Biotonne", null, null, null, "/apps/calendar/dayGridMonth/now")
5. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 100
   OC\AppFramework\Http\Dispatcher->executeController(OC\Core\Controll ... {}, "search")
6. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/AppFramework/App.php line 152
   OC\AppFramework\Http\Dispatcher->dispatch(OC\Core\Controll ... {}, "search")
7. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/lib/private/Route/Router.php line 309
   OC\AppFramework\App::main("OC\\Core\\Contr ... r", "search", OC\AppFramework\ ... {}, {providerId: "ta ... "})
8. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/ocs/v1.php line 88
   OC\Route\Router->match("/ocsapp/search/providers/tasks/search")
9. /srv/dev-disk-by-label-DatenSSDraid1/websites/nextcloud/ocs/v2.php line 24
   require_once("/srv/dev-disk-b ... p")

GET /ocs/v2.php/search/providers/tasks/search?term=Biotonne&from=%2Fapps%2Fcalendar%2FdayGridMonth%2Fnow
from 84.136.155.175 by admin at 2021-02-01T16:10:34+01:00

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

**Comment by kesselb** [comment]
Sorry!

**Comment by weinic** [comment]
> Thank you for reporting this issue 👍 Please check #15058 for more details.
> 
> Usually there are two ways to fix this:
> 
> A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).
> 
> B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).

Does this affect my mistake now? 
Or was that accidentally posted in this thread?

**Comment by kesselb** [comment]
> accidentally posted in this thread?

Yes
