### ISSUE TITLE
files starting with a "." not shown in web-frontend (e.g. .gitignore)

### ISSUE THREAD

**Issue by mpopp** [nextcloud/server#2543]
### Steps to reproduce
1. try to add a file via web-frontend (drag and drop) which starts with a "." in the filename (e.g. .gitignore)

### Expected behaviour
The file should be shown in the web-frontend just like any other file.

### Actual behaviour
Activity feed says "you created file .." but the file isn't shown in the frontend (even after refresh)

### Server configuration
**Operating system**:
Ubunut 16.04 LTS 

**Web server:**
Apache 2.4
**Database:**
Mysql
**PHP version:**
7.0
**Nextcloud version:** (see Nextcloud admin page)
10.0.1 stable
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install
**Where did you install Nextcloud from:**
official page
**Signing status:**
<details>
<summary>Signing status</summary>

No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

no access at the moment
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one: no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one: 

### Client configuration
**Browser:** chrome (newest version)

**Operating system:** win10

#### Nextcloud log (data/nextcloud.log)
no log entries relating to file upload (just failed logins and connection attempts)

**Comment by LukasReschke** [comment]
Check the settings in the lower left and enable "Show hidden files".

**Comment by mpopp** [comment]
sry... just found the settings... never mind I was to stupid to look at the bottom of the page :)
