### ISSUE TITLE
Calendar not showing events

### ISSUE THREAD

**Issue by aramirezverbio** [nextcloud/server#25437]
### Steps to reproduce
1. Subscribe to this calendar: https://aramirez.net/3ewmFLHW/test/ics-good
2. Subscribe to this other calendar: https://aramirez.net/3ewmFLHW/test/ics-bad

### Expected behaviour
Both calendars should work fine. They work fine in other clients like Google Calendar and the Android Calendar app.

### Actual behaviour
Both subscriptions are successful (no errors are shown), but one of the calendars does not display any events. Both calendars contain the exact same data (though some response headers differ, perhaps that's the issue).

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** Nextcloud Calendar, Google Calendar, Android Calendar app.

### Client configuration
**Browser:** Brave Version 1.19.88 Chromium: 88.0.4324.96 

**Operating system:** Arch Linux

### Server configuration

**Operating system**: Arch Linux (armv7l)

**Web server:** Nginx 1.18.0

**Database:** PostgreSQL 13.1

**PHP version:** 7.4.14

**Nextcloud Version:** 20.0.6

**Updated from an older installed version or fresh install:** Updated

**List of activated apps:**
* Accessibility
* Activity
* Brute-force settings
* Calendar
* Collaborative apps
* Comments
* Contacts
* Contacts interaction
* Dashboard
* Deck
* Deleted files
* External sites
* External user authentication
* Extract
* Federation
* File sharing
* First run wizard
* Log reader
* Mail
* Markdown editor
* Monitoring
* News
* Nextcloud announcements
* Notes
* Notifications
* PDF viewer
* Photos
* Privacy
* Recommendations
* Right click
* Share by mail
* Theming
* Update notifications
* User status
* Versions
* Video player
* Weather status

**Nextcloud configuration:**

```
<?php
$CONFIG = array (
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'asset-pipeline.enabled' => true,
  'datadirectory' => '/usr/share/webapps/nextcloud/data',
  'dbtype' => 'pgsql',
  'version' => '20.0.6.1',
  'dbtableprefix' => 'oc_',
  'logtimezone' => 'UTC',
  'installed' => true,
  'defaultapp' => 'news',
  'default_language' => 'es',
  'enable_avatars' => true,
  'theme' => '',
  'loglevel' => 0,
  'updater.release.channel' => 'stable',
  'app_install_overwrite' => 
  array (
    0 => 'calendar',
    1 => 'extract',
    2 => 'external',
  ),
  'maintenance' => false,
);
```

#### Web server error log (e.g. /var/log/apache)
There is nothing relevant in `/var/log/nginx/error.log`.

#### Log file (data/nextcloud.log)
No lines were written to this log file during my testing.

#### Browser log
No lines were written to the javascript console during my testing.

Response headers for `ics-good`: https://aramirez.net/3ewmFLHW/test/ics-good2.txt

Response headers for `ics-bad`: https://aramirez.net/3ewmFLHW/test/ics-bad2.txt

**Comment by aramirezverbio** [comment]
They are in the first message, at the bottom.

**Comment by tcitworld** [comment]
Possibly related to the duplicated headers.

**Comment by aramirezverbio** [comment]
Sorry, there was a copy-paste error. Here are the right headers:
* https://aramirez.net/3ewmFLHW/test/ics-good2.txt
* https://aramirez.net/3ewmFLHW/test/ics-bad2.txt

There are still some duplicates, though.

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.2?

**Comment by tcitworld** [comment]
The log files are gone.

**Comment by aramirezverbio** [comment]
I tried with NextCloud 21 a while ago and the issue persisted, but I'm afraid I've moved on and I don't use those calendars anymore. I can't run any more tests on this.

**Comment by tcitworld** [comment]
No worries, I'll try to generate some with `lpil/icalendar` to see if reproductible.
