### ISSUE TITLE
Folder View not refreshed 

### ISSUE THREAD

**Issue by Galileon-venta** [nextcloud/server#25434]
### Steps to reproduce
1. Select Move File
2. Create Folder via Move File Dialog
3. After File Move, newly created folder does not show up

### Expected behaviour
Newly Created Folder shows up (folder list view is refreshed)

### Actual behaviour
You need to reload page to see newly created folder

Reproducable on any Nextcloud installation (e.g. Demo.nextcloud.com)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Galileon-venta** [comment]
Yes, can still reproduce on demo

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
