### ISSUE TITLE
Popover menu is in the wrong place in some apps

### ISSUE THREAD

**Issue by juliushaertl** [nextcloud/server#2544]
The 3-dots menu seems to be some pixels off in some apps.

Calendar:
![2016-12-07-101810_152x192_scrot](https://cloud.githubusercontent.com/assets/3404133/20961766/d0a4c672-bc66-11e6-87a2-0f2938912a90.png)

News:
![2016-12-07-101848_267x143_scrot](https://cloud.githubusercontent.com/assets/3404133/20961768/d269a5c2-bc66-11e6-97ad-7784aec0a6b9.png)

In the new spreed app it works fine here.

Seems like this was introduced with b75ef0f8b3dea718b52b0dedcac16b504374b7cd

@nextcloud/designers @skjnldsv

**Comment by skjnldsv** [comment]
Fixing asap.
