### ISSUE TITLE
Nextcloud 21 regression: Dashboard background doesn't fit on large screens

### ISSUE THREAD

**Issue by jospoortvliet** [nextcloud/server#25447]
There's a white space under the dashboard, which is new in 21:
![Screenshot_20210202_205404](https://user-images.githubusercontent.com/551757/106656329-d81bc680-659a-11eb-989a-1e42eeb70e98.png)

This CSS change fixes it (100VH instead of 100% height)
![Screenshot_20210202_205439](https://user-images.githubusercontent.com/551757/106656323-d6ea9980-659a-11eb-8924-659800dd26d4.png)

To test/debug try the 'christine' user on our tech preview test server (internal).

**Comment by ethancedwards8** [comment]
Can confirm, really annoying.

**Comment by jospoortvliet** [comment]
@nextcloud/designers

**Comment by juliushaertl** [comment]
Cannot reproduce on latest 21/20. On master this seems to have been fixed by https://github.com/nextcloud/server/pull/26212 but I also cannot reproduce the issue with reverting that :shrug:

**Comment by szaimen** [comment]
@jospoortvliet Can you please validate if this is still an issue on NC22? Thanks!
