### ISSUE TITLE
Update to 20.0.6s causes calender rights via group to disappear

### ISSUE THREAD

**Issue by SprickW** [nextcloud/server#25459]
### Steps to reproduce
1. Update to 20.0.6s
2. have all modules up to date
3. give rights to a calendar via group

### Expected behaviour
Access to calendar as before

### Actual behaviour
Calender not to be seen via web and no replication possible (Thunderbird or others).

Gave access right to account directly and everything works again. So it seems to have something to do with calendars shared via groups.

### Server configuration

**Operating system:**
Ubuntu 20.04 LTS

**Web server:**
Appache

**Database:**
mySQL

**PHP version:**
unchanged
**Nextcloud version:** (see Nextcloud admin page)
20.0.6s

**Updated from an older Nextcloud/ownCloud or fresh install:**
Automatic Upgrade

**Comment by firlevapz** [comment]
I have the same problem, installed and updated via snap. 

The same problem exists also for contacts.

When shared to a group nothing is visible, but when shared to single users, it works. There are no entries in the `oc_dav_shares` table for any group-shares.

**Comment by firlevapz** [comment]
I've downgraded to version `20.0.4snap2` and the calendar/contact shares with groups are working again. 

On the working version `20.0.4snap2` the table `oc_dav_shares` has some entries for various groups in column `principaluri` like `principals/groups/mygroup`, but these entries are missing after the upgrade...

**Comment by oliverweidel** [comment]
See https://github.com/nextcloud/server/issues/25165

**Comment by octlabs** [comment]
In version 20.0.7, after the update from 20.0.3, we also have the bug that all group sharing of the calendars no longer works. Only the right share for each User's manual work as usual.
