### ISSUE TITLE
Logo not correctly displayed in share mails in Outlook

### ISSUE THREAD

**Issue by KuenzelIT** [nextcloud/server#25463]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Share a file in nextcloud and view the mail in Outlook.

### Expected behaviour
The logo should be displayed correctly and with a nice design.

### Actual behaviour
The logo is not displayed correctly because Outlook does not support border-radius. This makes the shared with you mails look bad,

### Server configuration

**Operating system:**
Debian 10

**Web server:**
Apache

**Database:**
Mysql

**PHP version:**
7.3.19

**Nextcloud version:** (see Nextcloud admin page)
20.0.5

**Updated from an older Nextcloud/ownCloud or fresh install:**
yes

**Where did you install Nextcloud from:**
tarball

**Comment by Gomez** [comment]
A customer had issues with the buttons and outlook (desktop only). I used this generator https://buttons.cm/ to improve the buttons. Maybe there is something similar for the logo?

Warning: Improving the email template and testing is not fun :( 


Old:
![Screenshot 2021-02-21 091916](https://user-images.githubusercontent.com/48724/108620806-d709e680-742e-11eb-8ec2-39dd7044b64c.png)

New:
![Screenshot 2021-02-21 092150](https://user-images.githubusercontent.com/48724/108620807-d7a27d00-742e-11eb-83d5-ab0d543b416d.png)

**Comment by szaimen** [comment]
I suppose this is still valid?
