### ISSUE TITLE
update to 20.0.7 caused failure-message

### ISSUE THREAD

**Issue by reinhardwilhelm1972** [nextcloud/server#25469]
Good evening,

I tried to update from the last release toward 20.0.7. I've download the .zip-file from nextcloud. Unzipped it and copied it to the /var/www/html/nextcloud -folder. I started with mozilla the cloud and started on the webside the updater.

I got the message:

Reparaturinformation: Change collation for oc_mail_messages ...

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE `oc_mail_messages` CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;': SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect string value: '\xF0\x9F\x92\xB3 A...' for column `cloud`.`oc_mail_messages`.`subject` at row 13

Das Update ist fehlgeschlagen. Bitte melden Sie dieses Problem an die Nextcloud Community.

Is there a solution. Thank you very much for taking time to solute my problem.

### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**

linux debian 10.0

**Web server:**

apache2.0

**Database:**

mysql

**PHP version:**

php7.3

**Nextcloud version:** (see Nextcloud admin page)

20.0.7 bevor 20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

nextcloud

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/mail/issues/4299
