### ISSUE TITLE
Resetting password with encryption enabled shows spinning wheel forever

### ISSUE THREAD

**Issue by GitHubUser4234** [nextcloud/server#2546]
When encryption is enabled and a user resets his password by clicking the "Reset password" button, an error message is displayed and a spinning wheel which spins forever. The password is successfully changed though.  It would great if the user could be informed about the successful change and the error could be for example an appropriate warning instead. 

Sceenshots:

1)
![image](https://cloud.githubusercontent.com/assets/16538178/20999819/308ed762-bd52-11e6-8640-d71dd1bcfe4e.png)
All fine here, let's tick the checkbox and click Reset password"

2)
![image](https://cloud.githubusercontent.com/assets/16538178/20965347/2c3b4648-bcb0-11e6-92e0-484a93e7483a.png)
Ooops, unexpected error message and spinning wheel spinning forever. But password was changed successfully.

Tested with the latest master.

**Comment by schiessle** [comment]
fix is here https://github.com/nextcloud/server/pull/2563

Please test, Thanks!

**Comment by GitHubUser4234** [comment]
Thanks a lot for the quick fix. I saw there is a level 3 log for the PrivateKeyMissingException though, is this something to stay? Thanks :)
