### ISSUE TITLE
Change notifications on "Log-in credentials, save in database" SMB shares

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2548]
I've stumbled upon the fact that change notifications require a password passed via OCC if one uses 
""Log-in credentials, save in database". Is there any real reason for doing so @icewind1991? Can't we just take one available credential and take that? 

cc @MorrisJobke FYI – Ticket 96020

**Comment by icewind1991** [comment]
There is no guarantee that different credentials give access to the same files (with the same permissions etc) so there is a risk in guessing which set of credentials to use

**Comment by LukasReschke** [comment]
Good point! I'll pass that forward.

Is there any way that we can automatically start new listeners for every user that this applies to? Like have the admin start it via OCC and from there on it will automagically do all right for all users?

**Comment by MorrisJobke** [comment]
> Is there any way that we can automatically start new listeners for every user that this applies to? Like have the admin start it via OCC and from there on it will automagically do all right for all users?

Ref https://github.com/nextcloud/documentation/issues/249

**Comment by szaimen** [comment]
I suppose this issue is still valid? If not, please close this issue!

**Comment by joshtrichards** [comment]
Further clarified in nextcloud/documentation#652
