### ISSUE TITLE
Overview gives incorrect information

### ISSUE THREAD

**Issue by mrtree4** [nextcloud/server#25481]
I get this errors on Overview section:
![image](https://user-images.githubusercontent.com/60297404/106904330-200e2b00-670c-11eb-908c-a56c9ad055e7.png)
Or in text:
```
• It was not possible to execute the cron job via CLI. The following technical errors have appeared:
        ○ Your data directory is invalid Ensure there is a file called ".ocdata" in the root of the data directory.
• PHP configuration option output_buffering must be disabled
```
But a file called ".ocdata" in the root of the data directory exist:
```
$ sudo ls -la Nextcloud/data | grep .ocdata
-rw-r--r--  1 www-data www-data      0 Feb  3 19:56 .ocdata
```
And option output_buffering is disabled:
```
$ sudo cat /var/www/html/nextcloud/.user.ini | grep output_buffering
output_buffering=0
```

Nextcloud version 20.0.7

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by kesselb** [comment]
I don't see a general issue with the output buffering check. Lot of people already complained about it. But in the end the check was always right. I'm happy to reopen this report if it's really a bug.

**Comment by mrtree4** [comment]
Ok, thank you.
