### ISSUE TITLE
Missing german translation - Settings of a share

### ISSUE THREAD

**Issue by blackerking** [nextcloud/server#25490]
Missing german translation if you change settings of share:
![grafik](https://user-images.githubusercontent.com/2019363/107007480-e03e5680-6792-11eb-9749-cee413b3fffd.png)

**Comment by kesselb** [comment]
Code https://github.com/nextcloud/server/blob/6846a83d56d9f825b06e6395bcdeae3404d5ec43/lib/private/Share20/Manager.php#L545

Example how to translate a exception message

https://github.com/nextcloud/server/blob/6846a83d56d9f825b06e6395bcdeae3404d5ec43/lib/private/Share20/Manager.php#L291-L292

**Comment by rakekniven** [comment]
This can be closed, or?

**Comment by szaimen** [comment]
looks like it, yes 👍
