### ISSUE TITLE
External storage support

### ISSUE THREAD

**Issue by guymass** [nextcloud/server#25510]
After latest update I have now version 1.9.0. When trying to access the plugin page I get the following error:

![Screen Shot 5781-05-23 at 21 43 21](https://user-images.githubusercontent.com/58882903/107081450-61313880-67fb-11eb-9c1f-0218d6429173.jpg)

The only way I can manage mounts is with occ.

**Comment by kesselb** [comment]
Logs missing => needs info. See the issue template how to write a proper bug report.
