### ISSUE TITLE
Nextcloud 21RC2 - apps in custom_apps doesn't work

### ISSUE THREAD

**Issue by helmut72** [nextcloud/server#25527]
### Steps to reproduce
1. install custom apps to configured custom_apps

### Expected behaviour
Apps installed in configured custom_apps should work.

### Actual behaviour
Apps installed in configured custom_apps doesn't work.

### Server configuration

**Operating system:**
Host OS: Ubuntu 20.04
Docker Containers: separate Containers for Apache, PHP and Redis on Alpine 3.13, Ubuntu for MariaDB

**Web server:**
apache2-http2-2.4.46

**Database:**
mariadb:10-focal

**PHP version:**
php8-8.0.1

**Nextcloud version:** (see Nextcloud admin page)
21RC2

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/prereleases/nextcloud-21.0.0RC1.zip

**Nextcloud configuration:**
```
  'apps_paths' => 
  array (
    0 => 
    array (
      'path' => '/var/www/html/apps',
      'url' => '/apps',
      'writable' => false,
    ),
    1 => 
    array (
      'path' => '/var/www/html/custom_apps',
      'url' => '/custom_apps',
      'writable' => true,
    ),
  ),
```

When moving app folder (eg. `/calendar`) from `/var/www/html/custom_apps` to `/var/www/html/apps`, the app works.

Update: same with NC21RC2

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by LeoColman** [comment]
I'm experiencing this issue with NC 23
