### ISSUE TITLE
Improve cli output during upgrade

### ISSUE THREAD

**Issue by radoeka** [nextcloud/server#25523]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upgrade nextcloud at the command line
2. Watch the output generated by the update command
3.

### Expected behaviour
Tell us what should happen

Nicely formatted output, e.g.:
```
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking appstore for update of app accessibility
Checked  appstore for update of app accessibility
Checking appstore for update of app activity
Checked  appstore for update of app activity
Checking appstore for update of app admin_audit
etc
```
The above layout is easier to read, and more consistent compared to the current layout, see below.

### Actual behaviour
Tell us what happens instead

```
Setting log level to debug
Turned on maintenance mode
Updating database schema
Updated database
Checking for update of app accessibility in appstore
Checked for update of app "accessibility" in appstore
Checking for update of app activity in appstore
Checked for update of app "activity" in appstore
Checking for update of app admin_audit in appstore
```

### Server configuration

**Operating system:** Linux, but I don't think it is relevant

**Web server:** Irrelevant

**Database:** Irrelevant

**PHP version:** 7.x, but  Irrelevant

**Nextcloud version:** 20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** older

**Where did you install Nextcloud from:** nextcloud.com

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
