### ISSUE TITLE
sqlite: There is no column with name 'parent' on table 'oc_share_external'.

### ISSUE THREAD

**Issue by ralovich** [nextcloud/server#25525]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. occ  -n db:convert-filecache-bigint

### Expected behaviour
Conversion succeeds.

### Actual behaviour
In SchemaException.php line 85:

  There is no column with name 'parent' on table 'oc_share_external'.

### Server configuration

**Operating system:**
Ubuntu 18.04
**Web server:**
Apache
**Database:**
sqlite3
**PHP version:**
7.2
**Nextcloud version:** (see Nextcloud admin page)
20.0.7.1
**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by gotros** [comment]
When I execute the occ command I can reproduce the error.

I also get an error as follows:
On the admin page under Security & setup warnings I get a general error message saying "There are some errors regarding your setup. Error occurred while checking server setup"

In the log I get the following output:
![Screenshot_20210208_201744](https://user-images.githubusercontent.com/66696861/107271707-e5c6c580-6a4c-11eb-853a-549625c6d72f.png)

**Comment by ralovich** [comment]
https://help.nextcloud.com/t/after-upgrade-no-column-with-name-parent-on-table-oc-share-external/104411/7 discusses the same issue but using mysql.

**Comment by gotros** [comment]
> https://help.nextcloud.com/t/after-upgrade-no-column-with-name-parent-on-table-oc-share-external/104411/7 discusses the same issue but using mysql.

Indeed. The manual steps fixed the problem for me.
Thx for sharing.

**Comment by ralovich** [comment]
Managed to resolve the issue using the following commands (based on https://github.com/nextcloud/server/issues/25414):

```
# sudo -u www-data -g www-data php occ app:install files_sharing
# sudo -u www-data -g www-data php occ app:update files_sharing
# sudo -u www-data -g www-data php occ app:enable files_sharing
```

**Comment by mrtnmtth** [comment]
Thanks for the update. This resolved the issue for me as well. Afterwards I simply disabled file sharing again.
