### ISSUE TITLE
" object_update_event" & "object_add_event"

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2553]
@nickvergessen on c.nc.c in the activity app when filtering for calendar I see the following:

![2016-12-07_17-10-43](https://cloud.githubusercontent.com/assets/878997/20975543/177a76b2-bca0-11e6-80c7-76b00ac94413.png)

**Comment by nickvergessen** [comment]
This happens for activities that were created before RC1. Sadly we can not recover those events, because the information was not stored correctly. Should not happen anymore (also tested by creating a new event/calendar and activities work fine, even on c.nc.c
