### ISSUE TITLE
Very slow job when user use ldap account

### ISSUE THREAD

**Issue by DimentR** [nextcloud/server#25534]
### Main
Small installation nextcloud.

Configured user authorization via LDAP
`(&(|(objectclass=person))(|(|(memberof=CN=NCGroup,DC=org,DC=local)(primaryGroupID=222))(|(memberof=CN=Domain Admins,CN=Users,DC=org,DC=local)(primaryGroupID=111))))`

Configured a user group that is available in NextCloud 
`(&(|(objectclass=group))(|(cn=Domain Admins)(cn=NCGroup)))`

22 users in access groups.

2 non-ldap users store about 200 GB (167080 files and 131742 directories)

### Steps to reproduce
When a non-ldap user comes to the site everything works quickly.

When an ldap user login the site, everything slows down. 

### Debug
In the process of debugging, I found out that NС makes a big request to the database 
`SELECT "f".* FROM "oc_filecache" "f" WHERE ((("f"."storage" = $1) AND ("f"."path" LIKE $2)) OR (("f"."storage" = $3) AND ("f"."path" LIKE $4) OR .............` 
The size of this request is approximately 40MB in text-log equivalent 

I also noticed that if I refine the search for ldap groups to a non-existent directory, then everything again works quickly. 

It looks like the problem is in non-optimal file search algorithm groups files.

### Server configuration
8GB
2-core CPU

**Operating system:**
Ubuntu 20.04, Freebsd 

**Web server:**
Nginx, php-fpm

**Database:**
Mysql, Postgresql

**PHP version:**
7.4

**Nextcloud version:** (see Nextcloud admin page)

19 - 20.0.6.1

**Updated from an older Nextcloud/ownCloud or fresh install:**

The problem was on version 19, updating and changing the platform did not help 

**Where did you install Nextcloud from:**

Docker

**List of activated apps:**
<details>
<summary>App list</summary>
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notes: 3.5.1
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - text

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
{
    "system": {
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "password": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "overwriteprotocol": "https"
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by DimentR** [comment]
After upgrade to 23 or 22 versions nextcloud - problem is actual.
App eat all memory  (no matter how much)

`app_1    | NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 4096 bytes) in /var/www/html/3rdparty/doctrine/dbal/src/Driver/PDO/Statement.php on line 92
app_1    | NOTICE: PHP message: PHP Fatal error:  Allowed memory size of 1073741824 bytes exhausted (tried to allocate 20480 bytes) in /var/www/html/lib/private/Files/Cache/Cache.php on line 187
`
@szaimen
