### ISSUE TITLE
NC 20.0.7 - 20.0.7.1 Update: Calendar, Addressbook etc disabled

### ISSUE THREAD

**Issue by tracing-home** [nextcloud/server#25559]
I am not sure if this a bug or new "feature": running the update inside an freenas/truenas/freebsd iocage the relevant apps were disabled as incompatible. Checking for new apps via UI, nothing was available. It appears many apps are gone.
Considering that CalDAV and CardDAV are my key reasons for using Nextcloud, this a dead end. Yes, the file/cloud section still is there. 

What is going on? Core features gone by updating? What to do to get out of the mess?

Now I tried to attach the "Server configuration detail" file I could generate, that fails, either with md or txt ending. Some basics copied in:

## Server configuration detail

**Operating system:** FreeBSD 12.2-RELEASE-p2 FreeBSD 12.2-RELEASE-p2 663e6b09467(HEAD) TRUENAS amd64

**Webserver:** Apache/2.4.46 (FreeBSD) OpenSSL/1.1.1h-freebsd (fpm-fcgi)

**Database:** mysql 5.7.33

**PHP version:** 7.4.15

Modules loaded: Core, date, libxml, pcre, hash, Reflection, SPL, session, standard, cgi-fcgi, mysqlnd, apcu, bcmath, bz2, ctype, curl, dom, mbstring, fileinfo, filter, gd, gmp, iconv, imagick, intl, json, ldap, exif, mysqli, openssl, PDO, posix, SimpleXML, xml, xmlwriter, zip, zlib, pdo_mysql, redis, xmlreader, xsl, Zend OPcache

**Nextcloud version:** 20.0.7 - 20.0.7.1

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
