### ISSUE TITLE
Use hardlinks instead of copy when possible

### ISSUE THREAD

**Issue by GAS85** [nextcloud/server#25562]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
When user copy file to different folder in local Storage, then it is copied and not hard linked, that will increase space consumption by the cloud Server.
Those are the same files, but different Inodes.
```
ls -lai Da*.txt Shared/Datenschutzerklärung.txt
134284604 -rw-r--r-- 1 www-data www-data 4783 Oct  7  2019 Datenschutzerklärung.txt
134352533 -rw-r--r-- 1 www-data www-data 4783 Feb 10 10:30 Shared/Datenschutzerklärung.txt

md5sum Da*.txt Shared/Datenschutzerklärung.txt
3712399a1ddddc19b088bd805407b361  Datenschutzerklärung.txt
3712399a1ddddc19b088bd805407b361  Shared/Datenschutzerklärung.txt
```

**Describe the solution you'd like**

- First try to create hardlink to the file in new location on local storage, only if it is fails then try to use copy command.
- Make Hardlinks creation optional, e.g. not relevant for S3 Storage on AWS.

**Describe alternatives you've considered**
Currently I use `rdfind -makehardlinks true` to find same files and reduce space usage. This will also use other users folder, e.g. common Family Videos from different users will be hardlinked.

**Additional context**
Similar behavior implemented e.g. in Sonarr. https://github.com/Sonarr/Sonarr/wiki/Completed-Download-Handling
You can setup if Hardlink should be used instead of copy and If the hardlink creation fails, Sonarr will fall back to the default behavior and copy the file.

Also related to #19948

**Comment by kesselb** [comment]
> When user copy file to different folder in local Storage, then it is copied and not hard linked

If the source file is deleted what happens to the hard link?

**Comment by GAS85** [comment]
You right, good question, because content of all hard links will be updated in case of direct change. It needs to be tracked (in NC DB), and e.g. on change create another copy of file with different inode, e.g.:
```
cp -p filename filename.tmp && mv -f filename.tmp filename
```

**Comment by faust64** [comment]
As a user, when I copy a file from one place to another, I would expect further editions to either copy not to affect the other one -- as pointed out in previous comment, rewriting a file, we would have to "break" that link.

Now you don't necessarily need to change your DB schema for that: you may `stat` the target file before opening it (https://www.php.net/manual/en/function.stat.php). The stat struct does include a count of links pointing to a given inode:

```
$ stat index.php 
  File: index.php
  Size: 2960      	Blocks: 8          IO Block: 4096   regular file
Device: fe04h/65028d	Inode: 2612455     Links: 1
```

**Comment by GAS85** [comment]
I do check and we do not change anything in current NC file updating process. Files change via NC will cause:
1. Moving original file to the Versions.
2. Creating of a new file on the place of an old file.

I have 2 hardlinked files FileA and FileB. When I update FileA NC will generate FileC with anew content, move FileA to the Versions and keep FileC on a place of FileA.

In this case even change file with the same inode will not cause any change on a hardlinked files, because NC will not directly update them.

**Comment by szaimen** [comment]
So @kesselb is this feature request feasible?

**Comment by GAS85** [comment]
Ping the bot!

**Comment by kesselb** [comment]
> is this feature request feasible?

In theory yes. But the feature is not on the roadmap and the complexity seems high (at least with my basic understanding of the files api). 

Some filesystems already support deduplication. I would say that's the better approach.
