### ISSUE TITLE
Update status based on the users calendar entries

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#25564]
If the Nextcloud calendar is used it would be a nice enhancement if my status would switch automatically to "busy" for the time span of the appointments in my calendar.

**Comment by szaimen** [comment]
cc @nextcloud/designers

**Comment by tcitworld** [comment]
AFAIK We can't program status to be busy at a certain datetime in the future so the only option would be to run a background job to check.

**Comment by jancborchardt** [comment]
Closing this in favor of https://github.com/nextcloud/server/issues/27990 which has more info on this now, including a design spec. :)
