### ISSUE TITLE
Missing user rights for shared folders after update to 20.0.7

### ISSUE THREAD

**Issue by Oreonan** [nextcloud/server#25565]
After updated from 20.0.6 to 20.0.7, user rights for shared folders are lost.
I've must have to stop sharing and recreate share for all shared folders.
More specifically, checkboxes are still checked, but, for example, users don't can anymore delete or move a file from a subfolder to another.

**Comment by skjnldsv** [comment]
cc @rullzer @nickvergessen @MorrisJobke

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
