### ISSUE TITLE
Webdav: changing calendar event recurrence causes error 

### ISSUE THREAD

**Issue by teemue** [nextcloud/server#25572]
When moving recurring event and upcoming events, the operation is not processed and an error occurs. Using calendar on Android via davx5, not sure if this issue is related to nc or davx.
NC 20.0.7.

___

 Sabre\VObject\Recur\NoInstancesException: This recurrence rule does not generate any valid instances

/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 2443:

Sabre\VObject\Recur\EventIterator->__construct()

/var/www/nextcloud/apps/dav/lib/CalDAV/CalDavBackend.php - line 1196:

OCA\DAV\CalDAV\CalDavBackend->getDenormalizedData()

/var/www/nextcloud/3rdparty/sabre/dav/lib/CalDAV/CalendarObject.php - line 107:

OCA\DAV\CalDAV\CalDavBackend->updateCalendarObject("*** sensiti ... *")

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1143:

Sabre\CalDAV\CalendarObject->put()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 515:

Sabre\DAV\Server->updateFile("*** sensiti ... *")

/var/www/nextcloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php - line 89:

Sabre\DAV\CorePlugin->httpPut()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 474:

Sabre\DAV\Server->emit()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 251:

Sabre\DAV\Server->invokeMethod()

/var/www/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 319:

Sabre\DAV\Server->start()

/var/www/nextcloud/apps/dav/lib/Server.php - line 332:

Sabre\DAV\Server->exec()

/var/www/nextcloud/apps/dav/appinfo/v2/remote.php - line 35:

OCA\DAV\Server->exec()

/var/www/nextcloud/remote.php - line 167:

require_once("/var/www/ne ... p")

___
Davx5 gives this information:
___
LocalEvent=[eTag=39bc9e4280981d0d680014518f0df8fe, fileName=58f39eb8-58af-4fcb-a08b-ea882c688fe7.ics, flags=1, scheduleTag=null, weAreOrganizer=true, calendar=at.bitfire.davdroid.resource.LocalCalendar@b80df96, event=Event=[alarms=[], attendees=[], categories=[], classification=CLASS:PUBLIC, color=null, description=null, dtEnd=DTEND;TZID=Europe/Helsinki:20201223T210000, dtStart=DTSTART;TZID=Europe/Helsinki:20201223T190000, duration=null, exDates=[EXDATE;TZID=Europe/Helsinki:20201223T190000
, EXDATE;TZID=Europe/Helsinki:20210106T190000
, EXDATE;TZID=Europe/Helsinki:20210120T190000
, EXDATE;TZID=Europe/Helsinki:20210203T190000
], exRules=[], exceptions=[], lastModified=null, location=null, opaque=true, organizer=null, rDates=[], rRules=[RRULE:FREQ=WEEKLY;WKST=SU;UNTIL=20210217T165959Z;INTERVAL=2;BYDAY=WE
], recurrenceId=null, status=STATUS:CONFIRMED, summary=Tapahtuma, unknownProperties=[X-APPLE-TRAVEL-ADVISORY-BEHAVIOR:AUTOMATIC
, CREATED:20201215T065716Z
], userAgents=[ws.xsoh.etar], sequence=4, uid=58f39eb8-58af-4fcb-a08b-ea882c688fe7], id=71190]

**Comment by skjnldsv** [comment]
cc @ChristophWurst @tcitworld

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by tcitworld** [comment]
It would be nice to have the full exported ICS file. Otherwise it's probably same as https://github.com/nextcloud/server/issues/5641 and a client issue.

**Comment by teemue** [comment]
I couldn't recreate this error anymore, I'd consider it fixed.

**Comment by teemue** [comment]
Happened again. Looks like #5641. How could I help to solve this ? Not sure if it's nextcloud's bug though.

**Comment by szaimen** [comment]
Could you please share the full exported ICS file? Thanks!

**Comment by teemue** [comment]
Sure! (Had to upload it zipped because github won't accept ics files).

[event.zip](https://github.com/nextcloud/server/files/6808636/event.zip)

**Comment by tcitworld** [comment]
You'll find informations on the issue in the lasts comments from https://github.com/nextcloud/server/issues/28477#issuecomment-899301983

Closing as duplicate from #5641
