### ISSUE TITLE
video preview image completly unscaled

### ISSUE THREAD

**Issue by mightyBroccoli** [nextcloud/server#2557]
### Steps to reproduce
1. upload a video with high resolution
2. click on the video in the webui to access the share comment eg sections
3. see the preview image completly unscaled and lagging the browser to oblivion

### Expected behaviour
Seeing a preview image in this case video should be scaled to see the whole picture and note the bottom left corner.

### Actual behaviour
a preview video that is displayed in normal resolution

### Server configuration
**Operating system**:
Distributor ID: Debian
Description:    Debian GNU/Linux 8.6 (jessie)
Release:        8.6
Codename:       jessie

**Web server:**
Server version: Apache/2.4.10 (Debian)
Server built:   Sep 15 2016 20:44:43

**Database:**
mysql  Ver 14.14 Distrib 5.5.53, for debian-linux-gnu (x86_64) using readline 6.3

**PHP version:**
PHP 7.0.13-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.13-1~dotdeb+8.1, Copyright (c) 1999-2016, by Zend Technologies

**Nextcloud version:** (see Nextcloud admin page)
   version: 11.0.0.6
   versionstring: 11.0 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:**
upgraded from 9 to 10 to 10.0.1 to 11beta to 11beta2 to 11RC1

**Where did you install Nextcloud from:**
official website till 10.0.1 then updater

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.4.1
  - admin_audit: 1.1.0
  - announcementcenter: 3.0.0
  - apporder: 0.3.3
  - audioplayer: 1.3.1
  - calendar: 1.4.1
  - comments: 1.1.0
  - dav: 1.1.1
  - direct_menu: 0.9.3
  - federatedfilesharing: 1.1.1
  - federation: 1.1.1
  - files: 1.6.1
  - files_external: 1.1.2
  - files_pdfviewer: 1.0.1
  - files_retention: 1.0.1
  - files_sharing: 1.1.1
  - files_texteditor: 2.2
  - files_trashbin: 1.1.0
  - files_versions: 1.4.0
  - files_videoplayer: 1.0.0
  - firstrunwizard: 2.0
  - gallery: 16.0.0
  - logreader: 2.0.0
  - lookup_server_connector: 1.0.0
  - news: 10.0.0
  - nextcloud_announcements: 1.0
  - notifications: 1.0.1
  - password_policy: 1.1.0
  - provisioning_api: 1.1.0
  - serverinfo: 1.1.1
  - sharebymail: 1.0.1
  - systemtags: 1.1.3
  - templateeditor: 0.2
  - theming: 1.1.1
  - twofactor_backupcodes: 1.0.0
  - twofactor_totp: 0.5.0
  - updatenotification: 1.1.1
  - workflowengine: 1.1.1
Disabled:
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - survey_client
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "ocdwzxwi729i",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.magicbroccoli.de"
        ],
        "datadirectory": "\/var\/www\/magicbroccoli.de\/data",
        "version": "11.0.0.6",
        "installed": true,
        "cipher": "AES-256-CFB",
        "dbtype": "mysql",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "default_language": "de",
        "defaultapp": "files",
        "enable_avatars": true,
        "allow_user_to_change_display_name": true,
        "remember_login_cookie_lifetime": 1296000,
        "session_lifetime": 86400,
        "auth.bruteforce.protection.enabled": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nextcloud",
        "mail_domain": "magicbroccoli.de",
        "mail_smtpauth": 1,
        "mail_smtpauthtype": "LOGIN",
        "mail_smtphost": "mail.server-speed.net",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "updatechecker": true,
        "updater.server.url": "https:\/\/updates.nextcloud.com\/updater_server\/",
        "upgrade.disable-web": false,
        "has_internet_connection": true,
        "check_for_working_htaccess": true,
        "check_for_working_webdav": true,
        "check_for_working_wellknown_setup": true,
        "logdateformat": "d.m.Y - H:i:s",
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 52428800,
        "loglevel": 2,
        "logfile": "\/var\/log\/nextcloud\/nextcloud.log",
        "appstoreenabled": true,
        "appstoreurl": "https:\/\/apps.nextcloud.com\/api\/v0",
        "appstore.experimental.enabled": true,
        "appcodechecker": false,
        "apps_paths": [
            {
                "path": "\/var\/www\/magicbroccoli.de\/nextcloud\/apps",
                "url": "\/apps",
                "writable": true
            }
        ],
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": "true",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "enable_previews": true,
        "preview_max_x": 1024,
        "preview_max_y": 1024,
        "preview_max_filesize_image": 25,
        "overwrite.cli.url": "https:\/\/cloud.magicbroccoli.de",
        "htaccess.RewriteBase": "\/",
        "trashbin_retention_obligation": "auto, 60",
        "versions_retention_obligation": "auto",
        "activity_expire_days": 80,
        "filesystem_check_changes": 0,
        "theme": "",
        "maintenance": false,
        "singleuser": false,
        "updater.release.channel": "beta",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
yes 
dropbox gdrive local

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Mozilla Firefox 50.0.2

**Operating system:**
Windows 10 Ultimate

Do I get a chance to win a tshirt now? I was searching like crazy to find stuff to get a chance to win that tshirt :D

**Comment by nickvergessen** [comment]
Which binary do you use for the video thumbnail generation? ffmpeg?

**Comment by mightyBroccoli** [comment]
@nickvergessen I am quite unsure how to find out which one is getting used. I do have both installed 
ffmpeg 
```
ffmpeg version 3.2-2~bpo8+2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)
```
php-gd
`php7.0-gd                      7.0.13-1~dotdeb+8.1`

How do I find out which one is getting used?

**Comment by nickvergessen** [comment]
ffmpeg and avconv are the options for Movie previews.

**Comment by mightyBroccoli** [comment]
I have ffmpeg installed and they deny each other on debian so i think i got that covered.

> ffmpeg

ffmpeg version 3.2-2~bpo8+2 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Debian 4.9.2-10)

**Comment by icewind1991** [comment]
server side previews are unrelated here, this is the video being played back as preview on the client

**Comment by MorrisJobke** [comment]
This was reverted in the files_videoplayer: https://github.com/nextcloud/files_videoplayer/pull/14
