### ISSUE TITLE
Cannot unshare a file shared as a link

### ISSUE THREAD

**Issue by andrzej-r** [nextcloud/server#25583]
### Steps to reproduce
1. Share a file (tested with a .jpg file) as a public link
2. Continue using Nextcloud for a while (the issue does not occur when moving to the step 3 immediately)
3. Locate the shared file and attempt to click on the "..." menu to unshare the file

### Expected behaviour
A popup menu should appear giving the user an option (among others) to unshare the file.

### Actual behaviour
A popup menu does not appear. The "..." button becomes grey. After double-clicking or multiple fast clicks on it, the user can make the menu to show up and then unsharing the file works as expected.
Potentially related: the popup menu is offset with respect to the "..." button (it is shown up at the top of the page).

### Server configuration

Same as #25581

**Comment by jospoortvliet** [comment]
Look in the side bar. There you can see the share links you created and remove them. You can have any number of share links, so putting a 'unshare file' in the `...` menu would not work - the menu would get very long as you can have many separate shares.

![Screenshot_20210315_081514](https://user-images.githubusercontent.com/551757/111116766-c567ba80-8566-11eb-8288-dde7adf88717.png)

Please, going forward, ask questions like these in help.nextcloud.com, don't file them as issues in github. We are of course happy with feedback on our user interface, but it is often better to first discuss it with others as they can explain why the UI works the way it does.

**Comment by andrzej-r** [comment]
It is a bug report, not a request for help. As explained above, the menu does not appear when clicking on the "..." button.

Please treat bug reports more seriously. Nextcloud would greatly benefit from having fewer rough edges.

**Comment by ckvtz** [comment]
unshare not working for Public link shares. This is a show stopper now even after more than 2 years of this issue getting reported!

**Comment by jospoortvliet** [comment]
@ckvtz I can not reproduce it, it works just fine here. You will have to dig in the error log and find out what makes your install different from others that this doesn't work, otherwise the devs have nothing to go on. Once you identified at least some hints as to what is wrong (or a sure way to reproduce this on any system, not just yours) it might be fixable. Sorry, I wish I could say some volunteer is willing to spend hours on figuring out what is wrong, but I really doubt that so you'll have to do that yourself - I can guarantee that this is NOT a problem many people have.

**Comment by ckvtz** [comment]
Hi Jos Poortvliet, Thank you for your response. I will try on a few other machines. Can you let me know how i can get you the error log of our install so you can help us. Thanks much.

**Comment by ckvtz** [comment]
I have tested the same in multiple devices and browsers. I get the following popup which displays "Error deleting the share"  when unshare option is clicked

**Comment by ghost** [comment]
For anyone still looking at this, there are 3 solutions.
1 - disable the maps app <-- this worked for me
2 - enable the share by email app
3 - disable other apps 1 by 1 until you find the culprit.
