### ISSUE TITLE
Upgrade process stops with an error

### ISSUE THREAD

**Issue by bjadel** [nextcloud/server#25598]
Intended to upgrade with Web-Updater from
Nextcloud 19.0.8 -> Nextcloud 20.0.7
But stops with an error.

Update vorbereiten
Log-Level auf "debug" gesetzt
Wartungsmodus eingeschaltet
Reparaturschritt: Repair MySQL collation
Reparaturinformation: All tables already have the correct collation -> nothing to do
Reparaturschritt: Repair SQLite autoincrement
Reparaturschritt: Copy data from accounts table when migrating from ownCloud
Reparaturschritt: Drop account terms table when migrating from ownCloud
Das Datenbankschema wird aktualisiert
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_authtoken CHANGE `password_invalid` password_invalid TINYINT(1) DEFAULT '0'': SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

What happend before the Upgrade?

* Made Upgrades from 19.0.0 up to 19.08 without problems
* used 1 occ commands as told from nextcloud for mysql database optimization (bigint and so on)
```
sudo -u www-data php /var/www/nextcloud/occ db:convert-filecache-bigint
```

**Operating system:**
Raspberry Pi 3

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7.3.25-1+0~20201130.73+debian9~1.gbp042074

What can I do now? Thanks in advance.

**Comment by kesselb** [comment]
Thank you for reporting this issue :+1:  Please check https://github.com/nextcloud/server/issues/15058 for more details.

Usually there are two ways to fix this:

A) Configure your database server to support utf8mb4 (https://docs.nextcloud.com/server/latest/admin_manual/configuration_database/mysql_4byte_support.html).

B) If the database server does not support utf8mb4 disable it by setting 'mysql.utf8mb4' => false in your config.php (emojis in filename, calendar events, etc. are not possible than and you have to accept the warning).
