### ISSUE TITLE
Desktop Client - Shared Folder does not sync deletes across machines

### ISSUE THREAD

**Issue by reidcanavan** [nextcloud/server#2559]
### Steps to reproduce
1. Create a file and let it sync via the desktop client on multiple computers
2a. Delete the file via web browser OR
2b. Delete the file via desktop client OR
2c. Delete the file via direct file system access
3. Desktop will sync the file back to the server during its next sync cycle.  Other desktops will eventually get the file back as well.

### Expected behaviour
Delete should sync across all devices.

### Actual behaviour
It will delete on the one desktop, or online, but when the desktop client syncs the file gets put back in place and synced back across all devices.

### Server configuration
**Operating system**: CentOS 7 - Fully patched as of December 7, 2016

**Web server:**  Apache 2.4

**Database:**  MariaDB

**PHP version:** 5.4

**Nextcloud version:** 10.0.1 (stable)

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh Install

**Where did you install Nextcloud from:** https://download.nextcloud.com/server/releases/nextcloud-10.0.1.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - comments: 1.0.0
  - dav: 1.0.1
  - external: true
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_accesscontrol: 1.1.2
  - files_external: 1.0.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - firstrunwizard: 1.1
  - notifications: 0.3.0
  - ownnote: 1.08
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - richdocuments: 1.1.15
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - user_external: 0.4
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - bookmarks
  - calendar
  - documents
  - encryption
  - files_automatedtagging
  - files_retention
  - files_videoplayer
  - gallery
  - tasks
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

...
{
    "system": {
        "instanceid": "ocl10vx6kshh",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nc.example.com"
        ],
        "datadirectory": "\/srv\/www\/nextcloud_data",
        "overwrite.cli.url": "https:\/\/nc.example.com",
        "dbtype": "mysql",
        "version": "9.1.1.5",
        "dbname": "nextcloud",
        "dbhost": "localhost",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "UTC",
        "installed": true,
        "mail_smtpmode": "smtp",
        "mail_from_address": "nc",
        "mail_domain": "example.com",
        "mail_smtphost": "192.168.1.10",
        "mail_smtpport": "25",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false
    },
    "apps": {
        "activity": {
            "enabled": "yes",
            "installed_version": "2.3.2",
            "types": "filesystem"
        },
        "backgroundjob": {
            "lastjob": "15"
        },
        "bookmarks": {
            "enabled": "no",
            "installed_version": "0.9.0",
            "ocsid": "168710",
            "types": ""
        },
        "calendar": {
            "enabled": "no",
            "installed_version": "1.4.1",
            "ocsid": "168707",
            "types": ""
        },
        "comments": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "logging"
        },
        "core": {
            "backgroundjobs_mode": "cron",
            "installedat": "1480303772.1661",
            "lastcron": "1481160603",
            "lastupdateResult": "[]",
            "lastupdatedat": "1481159325",
            "oc.integritycheck.checker": "[]",
            "public_documents": "documents\/public.php",
            "public_files": "files_sharing\/public.php",
            "public_richdocuments": "richdocuments\/public.php",
            "public_webdav": "dav\/appinfo\/v1\/publicwebdav.php",
            "shareapi_allow_mail_notification": "yes",
            "shareapi_allow_public_notification": "yes",
            "shareapi_allow_public_upload": "no",
            "shareapi_default_expire_date": "yes",
            "shareapi_exclude_groups": "no",
            "shareapi_exclude_groups_list": "[\"\"]",
            "shareapi_expire_after_n_days": "60",
            "umgmt_send_email": "true",
            "umgmt_show_backend": "true",
            "umgmt_show_email": "true",
            "umgmt_show_last_login": "true",
            "umgmt_show_storage_location": "true"
        },
        "dav": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        },
        "documents": {
            "enabled": "no",
            "installed_version": "0.13.1",
            "ocsid": "168711",
            "types": ""
        },
        "external": {
            "enabled": "yes",
            "installed_version": "",
            "ocsid": "166046",
            "types": ""
        },
        "federatedfilesharing": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": ""
        },
        "federation": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "authentication"
        },
        "files": {
            "cronjob_scan_files": "500",
            "default_quota": "none",
            "enabled": "yes",
            "installed_version": "1.5.2",
            "types": "filesystem"
        },
        "files_accesscontrol": {
            "enabled": "yes",
            "installed_version": "1.1.2",
            "types": "filesystem"
        },
        "files_external": {
            "allow_user_mounting": "no",
            "enabled": "yes",
            "installed_version": "1.0.2",
            "ocsid": "166048",
            "types": "filesystem",
            "user_mounting_backends": "ftp,dav,owncloud,sftp,amazons3,dropbox,googledrive,swift,smb,\\OC\\Files\\Storage\\SFTP_Key,\\OC\\Files\\Storage\\SMB_OC"
        },
        "files_pdfviewer": {
            "enabled": "yes",
            "installed_version": "0.8.1",
            "ocsid": "166049",
            "types": ""
        },
        "files_sharing": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_texteditor": {
            "enabled": "yes",
            "installed_version": "2.1",
            "ocsid": "166051",
            "types": ""
        },
        "files_trashbin": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "filesystem"
        },
        "files_versions": {
            "enabled": "yes",
            "installed_version": "1.3.0",
            "types": "filesystem"
        },
        "files_videoplayer": {
            "enabled": "no",
            "installed_version": "0.9.8",
            "types": ""
        },
        "firstrunwizard": {
            "enabled": "yes",
            "installed_version": "1.1",
            "ocsid": "166055",
            "types": ""
        },
        "gallery": {
            "enabled": "no",
            "installed_version": "15.0.0",
            "types": ""
        },
        "notifications": {
            "enabled": "yes",
            "installed_version": "0.3.0",
            "types": "logging"
        },
        "ownnote": {
            "enabled": "yes",
            "installed_version": "1.08",
            "ocsid": "168512",
            "types": ""
        },
        "password_policy": {
            "enabled": "yes",
            "enforceNumericCharacters": "1",
            "enforceUpperLowerCase": "1",
            "installed_version": "1.0.0",
            "minLength": "8",
            "types": ""
        },
        "provisioning_api": {
            "enabled": "yes",
            "installed_version": "1.0.0",
            "types": "prevent_group_restriction"
        },
        "richdocuments": {
            "enabled": "yes",
            "installed_version": "1.1.15",
            "ocsid": "174727",
            "types": "",
            "wopi_url": "https:\/\/nc.example.com:443"
        },
        "serverinfo": {
            "enabled": "yes",
            "installed_version": "1.1.1",
            "types": ""
        },
        "survey_client": {
            "enabled": "yes",
            "installed_version": "0.1.5",
            "last_sent": "1480475946",
            "types": ""
        },
        "systemtags": {
            "enabled": "yes",
            "installed_version": "1.0.2",
            "types": "logging"
        },
        "tasks": {
            "enabled": "no",
            "installed_version": "0.9.3",
            "ocsid": "164356",
            "types": ""
        },
        "templateeditor": {
            "enabled": "yes",
            "installed_version": "0.1",
            "types": ""
        },
        "theming": {
            "cachebuster": "4",
            "enabled": "yes",
            "installed_version": "1.0.1",
            "name": "Example File Cloud",
            "slogan": "File sharing system",
            "types": "logging",
            "url": "https:\/\/nc.example.com"
        },
        "updatenotification": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "richdocuments": "1.1.15",
            "types": ""
        },
        "user_external": {
            "enabled": "yes",
            "installed_version": "0.4",
            "ocsid": "166060",
            "types": "authentication,prelogin"
        },
        "workflowengine": {
            "enabled": "yes",
            "installed_version": "1.0.1",
            "types": "filesystem"
        }
    }
}
...

</details>

**Are you using external storage, if yes which one:** local and smb

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Chrome

**Operating system:** Windows 10

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Could not locate in the log file any reference to the Testing.odt file.  Also could not find a nextcloud.log in the smb directories.
```
</details>

**Comment by MorrisJobke** [comment]
cc @rullzer @schiessle

**Comment by MorrisJobke** [comment]
We fixed a lot in 11 and 12 for share change detection. Please update and check if it works now. Thanks
