### ISSUE TITLE
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

### ISSUE THREAD

**Issue by gthbbr** [nextcloud/server#25597]
What happend?:
Intended to upgrade with Web-Updater from
Nextcloud 19.0.8 -> Nextcloud 20.0.7
But stops with an error.
-----------------------
Web Updater output:
```
[...]
Reparaturschritt: Repair mime types

Doctrine\DBAL\Exception\UniqueConstraintViolationException: An exception occurred while executing 'INSERT INTO `oc_mimetypes` (`mimetype`) VALUES(?)' with params ["application\/vnd.oasis.opendocument.text-template"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY'

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.
```
-----------------------
What happend before the Upgrade?
- Made Upgrades from 17.0.10 up to 19.08 without problems
- used 3 occ commands as told from nextcloud for mysql database optimization (bigint and so on)
-----------------------
Webhosting with PHP 7.3 and MySQL 5.7...
What to do? Thanks in advance!

**Comment by gthbbr** [comment]
![image](https://user-images.githubusercontent.com/20505508/107708032-1fa10180-6cc3-11eb-9c81-d074431fa69c.png)

**Comment by kinimodmeyer** [comment]
the "id" column missing the "AUTO_INCREMENT"

**Comment by skjnldsv** [comment]
Yes, for some reason there is a missing param to your db. Please alter it manually.
Make backups

**Comment by abdullah-pgl** [comment]
I have the same problem!
when i added a new table and i use the firs id as primary key in the new table and i face that problem.
if i make constraint = false may i face problem in hosting.
i work on maintenances of already in use project.
