### ISSUE TITLE
Upgrade via web **without** user authentification

### ISSUE THREAD

**Issue by langfingaz** [nextcloud/server#25606]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Set up a Nextcloud instance
2. Do not update it in a while
3. In a private browser window, access the instance
4. There should be a "Update needed" warning. You should not see the login page.
5. Click on "Upgrade via web on my own risk"
6. The upgrade will be performed (and may fail) without you being an administrator or logged in

### Expected behaviour
Non-logged in users should see the login page. There could be a warning at the login page that this instance is outdated and one should contact the administrator. But one should not see the "Upgrade via web on my own risk" button!

### Actual behaviour
Anyone can start the upgrade.

![screenshot](https://user-images.githubusercontent.com/10504672/107771788-9679e100-6d3b-11eb-8c6c-90daba86c425.png)

### Server configuration

Nextcloud version 19.
Docker setup:
* mariadb
* redis:alpine
* nextcloud:stable-fpm-alpine
* nginx-alpine

**Comment by kesselb** [comment]
If your instance shows update needed the files are already replace but the changes to the database are not done. At this point it's not possible to load the authentication apps.

You may disable the web based upgrade: https://github.com/nextcloud/server/blob/7e6d69d166cbc92fb457fc72efc9abe850a0bbe4/config/config.sample.php#L1806-L1809

**Comment by langfingaz** [comment]
Ok, I understand. Thanks for clarification and the hint to disable web upgrade!
