### ISSUE TITLE
Nextcloud Download big files problem ( zero bytes)

### ISSUE THREAD

**Issue by Zantag** [nextcloud/server#25601]
Hi guys,

I have nextcloud on truenas jail  which i access  via reverse proxy (UBUNTU_VM>>>DOCKER>>>NGINX PROXY MANAGER)>>>. 
I cant download big files >5gb  they start to download after that stopped...
I thought that maybe the problem is that i don't config memcaching.

So i install and config Redis .... Now when i try to download big files more than 5 gb from web UI,  the file is immediately downloaded with zero bytes... Any ideas how to fix this problem...   
It's terrible to have your own cloud and cant use it like you want ;(

**Comment by mikimike93** [comment]
Hi Zantag,

on my Raspberry pi4 it was a problem related to so 32bit, rar32 could not generate archives for folders larger than 4GB, I solved it by telling it to use the .tar archive for bigger files, now it works perfectly and I manage the .tar in the same way as .rar with winrar

nano /nextcloud/lib/private/ Streamer.php 
old:
public function __construct(IRequest $request, int $size, int $numberOfFiles){
new (remove the first int):
public function __construct(IRequest $request, $size, int $numberOfFiles){

Old:
                if ($size > 0 && $size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
                        $this->streamerInstance = new ZipStreamer(['zip64' => false]);
                } elseif ($request->isUserAgent($this->preferTarFor)) {
                        $this->streamerInstance = new TarStreamer();
                } else {
                        $this->streamerInstance = new ZipStreamer(['zip64' => PHP_INT_SIZE !== 4]);
                }

New (check only the last line )

                if ($size > 0 && $size < 4 * 1000 * 1000 * 1000 && $numberOfFiles < 65536) {
                        $this->streamerInstance = new ZipStreamer(['zip64' => false]);
                } elseif ($request->isUserAgent($this->preferTarFor)) {
                        $this->streamerInstance = new TarStreamer();
                } else {
                        $this->streamerInstance = **new TarStreamer();**
                }

**Comment by skjnldsv** [comment]
@Zantag does the solution above fixes your issue?
