### ISSUE TITLE
Timezone not saved anymore on login

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/server#2560]
### Steps to reproduce
1. Login with username + password

### Expected behaviour
 oc_preferences should hold a row with `core` + `timezone`

### Actual behaviour
Works in 9, but in 10 and 11 this was killed by the auth rework?

@ChristophWurst @LukasReschke 

This causes issues for new users with activity emails and other stuff that uses the timezone not in JS only.
Ref: https://help.nextcloud.com/t/activity-timestamp-wrong-in-mail-notification/5818

**Comment by blizzz** [comment]
Seems so. In Nc 9 it was written to the preferneces in lib/base::tryFormLogin();

Looks like it is missing now in LoginController::tryLogin(), which is already a pretty long method. Like the login_token generation it can move to the user session.
