### ISSUE TITLE
NC 21 unique column option is not supported

### ISSUE THREAD

**Issue by sualko** [nextcloud/server#25607]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Try to enable app (bbb) which is working in NC 20
2. You get an error

### Expected behaviour
No error :smile:

### Actual behaviour
Error message in internal app store: `The "unique" column option is not supported.`

I found no notice about this in #23210, so what is the proper way of defining an unique column?

### Server configuration

**Operating system:** Ubuntu 20.04

**Web server:** php -S

**Database:** sqlite

**PHP version:** 7.4

**Nextcloud version:** 21

**Updated from an older Nextcloud/ownCloud or fresh install:** fresh

**Where did you install Nextcloud from:** Git

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"Exception":"Doctrine\\DBAL\\Schema\\Exception\\UnknownColumnOption","Message":"The \"unique\" column option is not supported.","Code":0,"Trace":[{"file":"\/opt\/nextcloud\/21\/3rdparty\/doctrine\/dbal\/src\/Schema\/Column.php","line":84,"function":"new","class":"Doctrine\\DBAL\\Schema\\Exception\\UnknownColumnOption","type":"::"},{"file":"\/opt\/nextcloud\/21\/3rdparty\/doctrine\/dbal\/src\/Schema\/Column.php","line":68,"function":"setOptions","class":"Doctrine\\DBAL\\Schema\\Column","type":"->"},{"file":"\/opt\/nextcloud\/21\/3rdparty\/doctrine\/dbal\/src\/Schema\/Table.php","line":355,"function":"__construct","class":"Doctrine\\DBAL\\Schema\\Column","type":"->"},{"file":"\/home\/klaus\/Repos\/cloud_bbb\/lib\/Migration\/Version000000Date20200416124731.php","line":31,"function":"addColumn","class":"Doctrine\\DBAL\\Schema\\Table","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/DB\/MigrationService.php","line":455,"function":"changeSchema","class":"OCA\\BigBlueButton\\Migration\\Version000000Date20200416124731","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/DB\/MigrationService.php","line":418,"function":"migrateSchemaOnly","class":"OC\\DB\\MigrationService","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/Installer.php","line":163,"function":"migrate","class":"OC\\DB\\MigrationService","type":"->"},{"file":"\/opt\/nextcloud\/21\/apps\/settings\/lib\/Controller\/AppSettingsController.php","line":448,"function":"installApp","class":"OC\\Installer","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":218,"function":"enableApps","class":"OCA\\Settings\\Controller\\AppSettingsController","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/AppFramework\/Http\/Dispatcher.php","line":127,"function":"executeController","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/AppFramework\/App.php","line":157,"function":"dispatch","class":"OC\\AppFramework\\Http\\Dispatcher","type":"->"},{"file":"\/opt\/nextcloud\/21\/lib\/private\/Route\/Router.php","line":302,"function":"main","class":"OC\\AppFramework\\App","type":"::"},{"file":"\/opt\/nextcloud\/21\/lib\/base.php","line":993,"function":"match","class":"OC\\Route\\Router","type":"->"},{"file":"\/opt\/nextcloud\/21\/index.php","line":37,"function":"handleRequest","class":"OC","type":"::"}],"File":"\/opt\/nextcloud\/21\/3rdparty\/doctrine\/dbal\/src\/Schema\/Exception\/UnknownColumnOption.php","Line":18,"CustomMessage":"--"}
```
</details>

**Comment by gioulisapo** [comment]
Exactly the same bahviour. Fresh install 
* Server version: Apache/2.4.38 (Raspbian)
* PHP 7.4.15 (cli) (built: Feb 20 2021 05:32:12) ( NTS )
* Nexcloud version
* Where did you install Nextcloud from: occ app install

**Comment by snevas** [comment]
Same for maps app in NC21

Using docker fpm alpine image + sqlite db

**Comment by cverstege** [comment]
Can confirm running a fresh install on Ubuntu Server 20.04 with

* Apache/2.4.41 (Ubuntu)
* PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
* Nextcloud Version 21.0.0
* MariaDB: 8.0.23-0ubuntu0.20.04.1 (Ubuntu)

And trying to install the maps app.

**Comment by toopaq** [comment]
Same here trying to install Maps.

- Nextcloud 21.0.0 (web-latest, fresh install)
- nginx version: nginx/1.18.0 (Ubuntu)
- PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
- 10.3.25-MariaDB-0ubuntu0.20.04.1 Ubuntu 20.04
- Redis server v=5.0.7

**Comment by odea** [comment]
Same for me, unable to install the maps extension :
Server version: Apache/2.4.41-4ubuntu3.1
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Nexcloud version: 21
Database: MariaDB 1:10.3.25-0ubuntu0.20.04.1
Where did you install Nextcloud from: tar.gz

When could we have an idea about a possible commit ? I'm waiting to install the maps extension for about 1 month now... that's the only thing that keeps me attached to Google...
I'm sure we are a lot in this situation, how can we tell the devs to look at this issue ?
Sorry I know it's easy to just ask and not propose a fix, but I'm not sure I could be able to code that.
Thanks !

**Comment by PixsaOJ** [comment]
Same, with latest nextcloud:latest, mysql, redis

**Comment by ElijahHW** [comment]
Same here with the latest nextcloud installment on mysql

**Comment by nickvergessen** [comment]
> I found no notice about this in #23210, so what is the proper way of defining an unique column?

I guess this is from the doctrine update, the only possible solution is to manually set a unique index on the column:
https://github.com/nextcloud/spreed/blob/f0220343e4f212f5f0fd1c21a1f4d108cc365596/lib/Migration/Version10000Date20200819121721.php#L58

We abstracted a lot away on the database handling, but not the schema thing yet, so the `unique` option was exposed by accident and no core app used it so no one noticed when we had to do the update the lib in a rush to fix php8 compatibility.
