### ISSUE TITLE
Ability to dis/enable external storages entries

### ISSUE THREAD

**Issue by g6094199** [nextcloud/server#25614]
Hi,

iḿ running a 20.x install of NC with several external storages attached (webdav, federation). Sometimes a external storage goes down and is unaccessible for a while. 
I wondered that my desktop clients stops to sync to NC in this case. I found in the forums that this depends on the non accessible external drives.
So i just want to disable the down storage provider but there is no setting to do this. Now i have to delete the whole entry and add it again when the drive comes up again. Thats very time wasting/anoying!

Can we have a simple checkbox to dis/enable single external storage enrties?!

Sash

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by wonx** [comment]
I'd also be interested in this feature. I'm using an app that by scans all files for all users. I have a "test" user that I use for testing different ways of accessing external storage, but there's a lot of redundant files in there, so the scan takes far too long (apart from being unnecessary). I'd love if I could just disable an external storage, or assign it to no one (if I don't specify a user, it's automatically assigned to everyone).

**Comment by Phils80** [comment]
I'm voting to implement this feature too. I have few external drives working as solid archive, my intention is to keep those disks completely off (they are connected through usb hub with power managment) to keep them allive as long as possible and use them only occasionally in case it is neccessary. Unfortunetly I have same problem as wonx, mounting them from outside means long time for scanning, especially for hdd's. It could be perfect to be able to deactivate them as external storages and activate in case of need after turning them on and mounting in file system...
