### ISSUE TITLE
Outer Join

### ISSUE THREAD

**Issue by vrtulka23** [nextcloud/server#25631]
Hello,

how come, that there is no possibility to do OUTER FULL JOIN in the Query Builder.
Or at least a possibility to send custom SQL queries.

Could you please add it to the next version of the NextCloud.

Cheer
Vrtulka23

**Comment by kesselb** [comment]
Hello :wave: 

> how come, that there is no possibility to do OUTER FULL JOIN in the Query Builder.

Our query builder is an wrapper of doctrine/dbal. They don't support full outer join: https://github.com/doctrine/dbal/pull/665

> Or at least a possibility to send custom SQL queries.

https://github.com/nextcloud/server/blob/946430862e63a2b1fdbb49ced4942b1534292606/lib/public/IDBConnection.php#L116
