### ISSUE TITLE
Improve performance with new SQL INDEX

### ISSUE THREAD

**Issue by tonychagas** [nextcloud/server#25630]
Slow query reported many times by mariadb:

```
# Time: 210213 17:00:04
# User@Host: nextclouduser[nextclouduser] @ localhost []
# Thread_id: 699  Schema: nextcloud_db  QC_hit: No
# Query_time: 2.029429  Lock_time: 0.011585  Rows_sent: 0  Rows_examined: 152893
# Rows_affected: 0  Bytes_sent: 11
use nextcloud_db;
SET timestamp=1613246404;
DELETE FROM `oc_activity` WHERE  `timestamp` < '1581710402'  LIMIT 100000;
```
Solved when i created the index: 

`CREATE INDEX activity_timestamp ON oc_activity (timestamp ASC);`

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by tonychagas** [comment]
for my case, I apply the index, but I haven't seen it in the script in the latest updates. If it has been added, we can consider it resolved, otherwise, it follows as a suggestion for performance
