### ISSUE TITLE
Have a group called "Any" so we don't need to add every group manually for permissions

### ISSUE THREAD

**Issue by luminous706** [nextcloud/server#25633]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**

Yes, to make it easier to manage users and groups, and related permissions, it would be great to have a default group called "any". Having such group would avoid NextCloud administrators to add groups to objects such as shared folders every time a new group is added and a folder or file needs to be shared automatically.

**Describe the solution you'd like**
When sharing a file, folder, or anything shareable such as To-Do lists, group chats, etc, have a group named "Any" or "*" to match any group. A default group named "any" would automatically add shared objects into that group for anyone to use.

**Describe alternatives you've considered**
The only alternative right now, is to add new groups to shared objects one by one, it is a tedious process.

**Additional context**
N/A

**Comment by szaimen** [comment]
Hey, please have a look at this app:
https://apps.nextcloud.com/apps/group_everyone

**Comment by luminous706** [comment]
> Hey, please have a look at this app:
> https://apps.nextcloud.com/apps/group_everyone
> Edit: If it doesn't fit your usecase, please reopen!

Hey that seems like a great solution, but quick question: Will this put any user in the Everyone group also in the Admin group?

**Comment by szaimen** [comment]
I cannot say for sure since I am not using this app. But you can test it and uninstall again it if it doesn't work for you.

**Comment by luminous706** [comment]
> I cannot say for sure since I am not using this app. But you can test it and uninstall again it if it doesn't work for you.

Thanks for the help, I just tested the addon and it's actually not the same thing as my use case.

The Everyone plugin is actually just a normal/passive group called "Everyone" that is automatically assigned to every user on the system.

Whereas my issue is more like a * pattern that would allow an object to "match" every existing group on the system. Could be "any" or "*", when adding groups to the object to be part of.
