### ISSUE TITLE
Version number in `config.php`

### ISSUE THREAD

**Issue by StyXman** [nextcloud/server#25639]
I already described the situation here: https://help.nextcloud.com/t/exception-updates-between-multiple-major-versions-and-downgrades-are-unsupported/107831

In short, the NC version is both stored in the config file and the database, leading to possible inconsistencies and problems.

I think the best solution is to remove the version number from the config file, leaving it more open to config management that still leaves NC to be upgraded internally. Currently I have to change the version in my config file template.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
