### ISSUE TITLE
Updating 20.0.6 -> 20.0.7 (MariaDB 10.5.8: MySQL server has gone away)

### ISSUE THREAD

**Issue by DSG5TRDD** [nextcloud/server#25640]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update Nextcloud 20.0.6 to 20.0.7 via webupdater
2.
3.

### Expected behaviour
Aktualisierung auf 20.0.7 

### Actual behaviour
Error while updating to 20.0.7 -> MySQL server has gone away

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'ALTER TABLE oc_music_playlists ADD "updated" DATETIME DEFAULT NULL': SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

Detaillierte Protokollmeldungen

    Update vorbereiten
    Log-Level auf "debug" gesetzt
    Wartungsmodus eingeschaltet
    Reparaturschritt: Repair MySQL collation
    Reparaturinformation: All tables already have the correct collation -> nothing to do
    Reparaturschritt: Repair SQLite autoincrement
    Reparaturschritt: Copy data from accounts table when migrating from ownCloud
    Reparaturschritt: Drop account terms table when migrating from ownCloud
    Das Datenbankschema wird aktualisiert
    Datenbank aktualisiert
    Reparaturschritt: Drop any incompatible music database entries

    Doctrine\DBAL\Exception\DriverException:
    An exception occurred while executing 'ALTER TABLE oc_music_playlists ADD `updated` DATETIME         
    DEFAULT NULL': SQLSTATE[HY000]:
    General error: 2006 MySQL server has gone away

Das Update ist fehlgeschlagen. Bitte melde dieses Problem an die Nextcloud Community.

### Server configuration

**Operating system:**

Betriebssystem: | Linux 4.15.0 x86_64
Prozessor: | Intel(R) Xeon(R) CPU E5-2680 v3 @ 2.50GHz (4 cores)
Speicher: | 4.00 GB

**Web server:**
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2020-08-12T21:33:25

**Database:**
Art: mysql (MariaDB)
Version: 10.5.8
Größe: 99,5 MB

**PHP version:**
Version: 7.4.14
Arbeitspeicher-Grenzwert: 2 GB
Maximale Ausführungszeit: 3600
Maximale Größe zum Hochladen: 32 MB

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.5

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
--> No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trackdownloads: 1.9.0
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - firstrunwizard: 2.9.0
  - groupfolders: 8.2.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - music: 0.17.3
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_admin: 3.0.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_videoplayer
  - survey_client
  - user_ldap


```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.6.1",
        "overwrite.cli.url": "https:\/\/***REMOVED SENSITIVE VALUE***.de\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filesystem_check_changes": 1,
        "allow_user_to_change_display_name": false,
        "updater.release.channel": "stable",
        "theme": "",
        "loglevel": 4,
        "log_rotate_size": 104857600,
        "mysql.utf8mb4": true,
        "maintenance": false
    }



or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no
--> NO

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

--> There are no commands defined in the "ldap" namespace.

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**
--> FireFox 

**Operating system:**

--> Microsoft Windows 10

### Logs

I had have restored the Backup after the crash, so there no log files.

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
