### ISSUE TITLE
Nextcloud architecture

### ISSUE THREAD

**Issue by d0niek** [nextcloud/server#25648]
Hi!

First I want to say BIG thank you for a great job doing a Nextcloud ;-)

Now I'm going directly to the topic. I use Nextcloud, I follow it on reddit and I see that there are lot of people that complain a NC performance. I have to say that sometime is TRUE... Everyone complain that the problem is with a language, php. There was a time that I believe in that, php is slow... But! As soon as I found [phabricator](https://github.com/phacility/phabricator), see it is a php, install it and check how it works I stop saying that php is slow! Sorry but programmers business logic is slow :-/

I don't know Nextcloud architecture, I don't know phabricator architecture and I know that is not easy to change it but maybe you can find something that will help to improve NC performance? For example each app (?) in phabricator has it's own database (https://secure.phabricator.com/book/phabflavor/article/so_many_databases/) what help with scale.

As I said, I use NC, I really like it, for me it's a great app(s). As I can I want to help to improve it. I use and like phabricator too. For me it's a php app which shows that language (php) is not a bottleneck.

Maybe I'm wrong that NC architecture is bad. Sorry. I just I want to help :-)

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com

**Comment by Spartachetto** [comment]
@kesselb my impression is that @d0niek is just trying to give suggestions to improve Nextcloud architecture...

He is trying to help by suggesting to have a look at something he think it could be a good model.

It is clear that the suggestion is not a deep analysis of the architecture and you were right in closing it, yet I'd like to thank @d0niek for the food for thought :slightly_smiling_face:
