### ISSUE TITLE
Favourites list is not updated in real time

### ISSUE THREAD

**Issue by oparoz** [nextcloud/server#2567]
### Steps to reproduce

1. Make 2 files your favourite
2. Nothing happens
3. Leave the folder and come back
1. They are now at the top
1. Make more files your favourite

### Expected behaviour

Since we have a "feature" which pins favourites to the top, the list should be re-arranged when I make a file or folder my favourite.

### Actual behaviour

Nothing happens, I have some favourites at the top and some scattered around in my list of files

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:** 7.0

**Nextcloud version:** 11

-----
@ChristophWurst  @jancborchardt @skjnldsv

**Comment by jancborchardt** [comment]
cc @ryanwr who implemented it in https://github.com/nextcloud/server/pull/1860. Also @nextcloud/javascript :)

**Comment by danxuliu** [comment]
This was fixed for Nextcloud 13 in #5621. However [it was decided to not backport it to Nextcloud 12](https://github.com/nextcloud/server/pull/5621#issuecomment-313112795), and this issue is reported against Nextcloud 11, so... close?

**Comment by skjnldsv** [comment]
Agreed

**Comment by rullzer** [comment]
Yep
