### ISSUE TITLE
An exception occurred while executing when updating

### ISSUE THREAD

**Issue by ansred** [nextcloud/server#25674]
### Steps to reproduce
Regular updates from the Ui

### Expected behaviour
Update should be complete

### Actual behaviour

`Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'CREATE TEMPORARY TABLE __temp__oc_filecache AS SELECT fileid, storage, path, path_hash, parent, name, mimetype, mimepart, size, mtime, storage_mtime, encrypted, unencrypted_size, etag, permissions, checksum FROM oc_filecache': SQLSTATE[HY000]: General error: 11 database disk image is malformed`

![image](https://user-images.githubusercontent.com/5244872/108025054-c4894a80-6ff3-11eb-9940-a57f173b9e7c.png)

### Server configuration
Docker - Synology NAS

**Database:**
sqlite

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
