### ISSUE TITLE
Setting 'log_query'=true breaks at least spreed and deck/tasks apps

### ISSUE THREAD

**Issue by p5n** [nextcloud/server#25682]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
* 'log_query' => true,
* open tasks application. it fails on deck tasklists
* open talk application, it fails on loading comments

```
Object of class DateTime could not be converted to string
```

I was able to work around deck/tasks apps replacing in `lib/private/Comments/Manager.php:578`:

```
- ->setParameter('notOlderThan', $notOlderThan, 'datetime');
+ ->setParameter('notOlderThan', $notOlderThan->format('Y-m-d H:i:s'), IQueryBuilder::PARAM_STR);
```

### Server configuration

**Operating system:**
Archlinux

apache 2.4.46-3
php7 7.4.15-1
postgresql 13.2-1

nextcloud 20.0.7-1
nextcloud-app-deck 1:1.2.4-1
nextcloud-app-tasks 0.13.6-1
nextcloud-app-spreed 1:10.1.1-1

**Updated from an older Nextcloud/ownCloud or fresh install:**
from 20.0.3

**Where did you install Nextcloud from:**
archlinux packages

**Comment by kesselb** [comment]
Fixed by https://github.com/nextcloud/server/pull/24500 for Nextcloud 21. As log_query is a debugging feature no backport.
