### ISSUE TITLE
user can't change language in personal settings

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2568]
A normal user can't change the language in the personal settings (for admins it works).

The user gets a 403 but the method is set to "@NoAdminRequired". After some debugging I found out that here: https://github.com/nextcloud/server/blob/master/lib/private/AppFramework/App.php#L91 the "PersonalController" is not found, but only for non-admins.

Any ideas? Maybe @rullzer as the original author of the controller?

**Comment by nickvergessen** [comment]
Can not reproduce, works just fine here.
Anything in the log or browser console?

**Comment by schiessle** [comment]
No, nothing in the log. I just get a 403 if I check the network console and a "access forbidden" error page as response. Can be reproduce it on my dev system (master) and on our internal Nextcloud by multiple people.

**Comment by nickvergessen** [comment]
Ah I tested with admin, will have a look since non-admins fail indeed.
