### ISSUE TITLE
[Feature] Email-2FA link share

### ISSUE THREAD

**Issue by josh-hemphill** [nextcloud/server#25686]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
No, not really.

**Describe the solution you'd like**
I recently got exposed to a really interesting secure share workflow.
Generate link and set allowed email addresses > external user navigates it > enters their email > if they're allowed, they receive an email with a one-time password to obtain access for a single session.

I'm not sure exactly how something like this would end up looking in NextClound, but having an email-based, 2FA, link share, would make it much easier to get non-technical users to adopt. It could easily be set to `x number of emails can be sent` effectively allowing it to be a one-time/one-session link.

**Describe alternatives you've considered**
An external service would be rather cumbersome to use, and hard to push adoption in a larger company. 
Creating a NextCloud app to accomplish this might be possible, but adding an additional session tracking/management layer might be a duplication of effort if a lot of the same core share functionality can be used for parts of it.

**Additional context**
Sort of relates to, and might close:
https://github.com/nextcloud/server/issues/6841

**Comment by JazMTaz** [comment]
This would be very helpful

**Comment by szaimen** [comment]
Hi 👋

We are currently cleaning up our issue tracker. The feature described in this issues sounds like a good idea for a dedicated app. Feel free to post it in our "App ideas" section in the forum, to find a developer that wants to work on it:
https://help.nextcloud.com/c/apps/app-ideas/21

We are closing this issue here now, so the "issue tracker" of the server repository can be used better to track issues instead.

Cheers
