### ISSUE TITLE
"All Apps" page and filtering out untested apps

### ISSUE THREAD

**Issue by summersab** [nextcloud/server#25698]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
There is no way to show all apps available in the store on a single page. Instead, apps must be viewed category-by-category. Since most apps are in multiple categories, this makes it time-consuming to browse all apps.

Also:
- I don't believe there is a way to filter out untested apps when browsing available apps.
- There is no way for admins to prevent users from installing untested apps.

(I can split this out into a separate requests if you would prefer).

**Describe the solution you'd like**
There should be an "All Apps" section right above "Featured apps" that lists all available apps on a single page.

There should be a way to filter out untested apps (both in the "All Apps" section and in existing individual category views).

There should also be a setting to allow administrators to prevent the installation of untested apps.

**Comment by summersab** [comment]
I wrote a script that provides a rough workaround to implement these features. However, it would be nice to have these options available by default.

Also, my script doesn't allow users to filter out untested apps when browsing apps in the GUI - if untested apps are turned off using my script, they are permanently hidden. It would be nice to have a filter option in the web interface.
https://gist.github.com/summersab/363c753c4936f0bc563ea88a85de6241

Close if you wish, but it would be nice to add this as a feature request.

**Comment by szaimen** [comment]
Thanks!
Lets track this here: https://github.com/nextcloud/server/issues/21566
