### ISSUE TITLE
Incomplete list of users in the Users view

### ISSUE THREAD

**Issue by hriekehof** [nextcloud/server#25695]
### Steps to reproduce
1. Sync users via Actice Directory or LDAP
2. Go to the Users Page in the Admin Panel

### Expected behaviour
That the users Tab shows all users Synced via LDAP.

### Actual behaviour
Some Users are missing. But it seems that only the webinterface is affected. When i check the users using occ users:list everyone is shown.  The Users View in the Everyone group ends like this:

![image](https://user-images.githubusercontent.com/9348635/108223300-f4db0100-7139-11eb-93e2-84cb0f3765fb.png)

### Server configuration

nextcloud:20-apache Docker image in full configuration

**Nextcloud version:** 20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Update from 20.0.6

**Where did you install Nextcloud from:** Dockerhub

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - announcementcenter: 4.0.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_accesscontrol: 1.10.2
  - files_automatedtagging: 1.10.1
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - onlyoffice: 6.2.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_ldap: 1.10.2
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - groupfolders
  - sharebymail
  - spreed
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
Sorry this will take a while. If this is okay i would upload it if needed
```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** ActiveDirectory

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

+-------------------------------+-------------------------------------------------------------------+
| Configuration                 | s01                                                               |
+-------------------------------+-------------------------------------------------------------------+
| hasMemberOfFilterSupport      | 0                                                                 |
| homeFolderNamingRule          |                                                                   |
| lastJpegPhotoLookup           | 0                                                                 |
| ldapAgentName                 | cn=nextcloud,ou=org,ou=benutzer,ou=schoeps,dc=schoeps,dc=local    |
| ldapAgentPassword             | ***                                                               |
| ldapAttributesForGroupSearch  |                                                                   |
| ldapAttributesForUserSearch   |                                                                   |
| ldapBackupHost                |                                                                   |
| ldapBackupPort                |                                                                   |
| ldapBase                      | dc=schoeps,dc=local                                               |
| ldapBaseGroups                | ou=mitarbeiter,ou=benutzer,ou=schoeps,dc=schoeps,dc=local         |
| ldapBaseUsers                 | ou=mitarbeiter,ou=benutzer,ou=schoeps,dc=schoeps,dc=local         |
| ldapCacheTTL                  | 600                                                               |
| ldapConfigurationActive       | 1                                                                 |
| ldapDefaultPPolicyDN          |                                                                   |
| ldapDynamicGroupMemberURL     |                                                                   |
| ldapEmailAttribute            | mail                                                              |
| ldapExperiencedAdmin          | 0                                                                 |
| ldapExpertUUIDGroupAttr       |                                                                   |
| ldapExpertUUIDUserAttr        | sAMAccountName                                                    |
| ldapExpertUsernameAttr        | sAMAccountName                                                    |
| ldapExtStorageHomeAttribute   |                                                                   |
| ldapGidNumber                 | gidNumber                                                         |
| ldapGroupDisplayName          | cn                                                                |
| ldapGroupFilter               |                                                                   |
| ldapGroupFilterGroups         |                                                                   |
| ldapGroupFilterMode           | 0                                                                 |
| ldapGroupFilterObjectclass    |                                                                   |
| ldapGroupMemberAssocAttr      | uniqueMember                                                      |
| ldapHost                      | xxx.local                                                |
| ldapIgnoreNamingRules         |                                                                   |
| ldapLoginFilter               | (&(|(objectclass=person)(objectclass=user))(samaccountname=%uid)) |
| ldapLoginFilterAttributes     |                                                                   |
| ldapLoginFilterEmail          | 0                                                                 |
| ldapLoginFilterMode           | 0                                                                 |
| ldapLoginFilterUsername       | 1                                                                 |
| ldapMatchingRuleInChainState  | unknown                                                           |
| ldapNestedGroups              | 0                                                                 |
| ldapOverrideMainServer        |                                                                   |
| ldapPagingSize                | 500                                                               |
| ldapPort                      | 389                                                               |
| ldapQuotaAttribute            |                                                                   |
| ldapQuotaDefault              |                                                                   |
| ldapTLS                       | 0                                                                 |
| ldapUserAvatarRule            | default                                                           |
| ldapUserDisplayName           | displayname                                                       |
| ldapUserDisplayName2          |                                                                   |
| ldapUserFilter                | (|(objectclass=person)(objectclass=user))                         |
| ldapUserFilterGroups          |                                                                   |
| ldapUserFilterMode            | 0                                                                 |
| ldapUserFilterObjectclass     | person;user                                                       |
| ldapUuidGroupAttribute        | auto                                                              |
| ldapUuidUserAttribute         | auto                                                              |
| turnOffCertCheck              | 0                                                                 |
| turnOnPasswordChange          | 0                                                                 |
| useMemberOfToDetectMembership | 1                                                                 |
+-------------------------------+-------------------------------------------------------------------+
</details>

### Client configuration
**Browser:** Google Chrome

**Operating system:** Win10

#### Web server error log
<details>
<summary>Web server error log</summary>
Would take me a while to strip sensitive information from it. It would be ok for me to email it to someone.
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Same as with the other log. when i can email it to someone thats fine
```
Insert your Nextcloud log here
```
</details>

**Comment by kesselb** [comment]
Thanks for reporting :+1: 

Most likely fixed in 20.0.8: https://github.com/nextcloud/server/issues/25442 / https://github.com/nextcloud/server/pull/25443.
