### ISSUE TITLE
Transfer Ownership: "Share with id XX points at deleted file, skipping" and shares lost during transfer

### ISSUE THREAD

**Issue by mseiwald** [nextcloud/server#25693]
Hi,

I want to transfer files/folders and the existing shares on those folders from one user to the other using the command:

```su -p www-data -s /bin/sh -c "php /var/www/html/occ files:transfer-ownership --path oldUser newUser";```

This is an example output:

```Validating quota
Analysing files of oldUser ...
    0 [->--------------------------]
Collecting all share information for files and folders of oldUser ...
    4 [============================]
Transferring files to newUser/files/transferred from oldUser on 2021-02-17 12-33-27 ...
Restoring shares ...
Share with id 27 points at deleted file, skipping
 1/4 [=======>--------------------]  25%Share with id 28 points at deleted file, skipping
Share with id 29 points at deleted file, skipping
Share with id 30 points at deleted file, skipping
 4/4 [============================] 100%
```

First of all I don't know what the error `Share with id XX points at deleted file, skipping` means. I found previous reports related to quota etc. In my case both users have a large enough quota and there are no deleted files. I'm getting this error everytime even with an empty test folder.

Furthermore, shares on the transferred folders are lost.

I would appreciate any hint on how to troubleshoot this issue and fix it.

Thanks!

Nextcloud version: 20.0.5

**Comment by acsfer** [comment]
> Furthermore, shares on the transferred folders are lost.

Check the doc: https://docs.nextcloud.com/server/20/admin_manual/configuration_server/occ_command.html#file-operations

> Incoming shares are not moved because the sharing user holds the ownership of the respective files and therefore owns the decision which actual users/groups to be shared with.

**Comment by mseiwald** [comment]
Sorry if I wasn't clear enough, I was only referring to outgoing shares (i.e. shared folders **owned** by the old user) which are also lost but shouldn't be according to the documentation:

> Outgoing shares are moved as well.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by pierreozoux** [comment]
We experience the same with a Nc22. We'll share details in a moment.

**Comment by unteem** [comment]
I was also thinking about an alternative to transfer ownership.

Instead of copying a new file and deleting the original one (at least in the database)

in the filecache table changing the storageID to the new one could be enough
then for shares uid_owner should be changed and we are done 

I guess this for a scenario that correspond the `-move` option of the transfer-ownership command as there could be conflict if files are in the same path in the receiver path.

**Comment by unteem** [comment]
I forgot to mention that I'm using S3 as primary storage and issue seems to come from there.
Just tried with filesystem storage and it is working 

@mseiwald are you also using S3 as primary storage ?

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
