### ISSUE TITLE
autocomplete drop-down broken on master with Firefox

### ISSUE THREAD

**Issue by schiessle** [nextcloud/server#2569]
The auto-complete drop down for the user name at the login screen is broken for Firefox.

This is how it looks like for me:

![login](https://cloud.githubusercontent.com/assets/1589737/21013967/4e0c8da2-bd5c-11e6-8cb9-d151adf81caf.png)

@nextcloud/designers

**Comment by MorrisJobke** [comment]
I can't reproduce:

![bildschirmfoto 2016-12-08 um 15 52 46](https://cloud.githubusercontent.com/assets/245432/21014456/68df26f6-bd5e-11e6-869e-48ec889c3333.png)


Also this is nothing we can style. This is the overlay the browser brings in. This is no HTML we even can reach. I tried to tweak it, but it's not within the DOM.

**Comment by MorrisJobke** [comment]
Most likely an issue with this Firefox version 🙈

**Comment by schiessle** [comment]
all other webforms work so I don't think it is a general browser issue

**Comment by skjnldsv** [comment]
Can't either.
![kazam_screenshot_00002](https://cloud.githubusercontent.com/assets/14975046/21014553/d2838ffc-bd5e-11e6-88e5-018578c75201.png)

**Comment by MorrisJobke** [comment]
> all other webforms work so I don't think it is a general browser issue

But I have no idea how we could tweak this -.-

**Comment by MorrisJobke** [comment]
> But I have no idea how we could tweak this -.-

Beside turning it off:

```html
<input autocomplete="off" />
```

**Comment by jancborchardt** [comment]
Yeah, this looks like a browser bug. Maybe due to resizing, or a special version or whatnot. What do you exactly use @schiessle?
