### ISSUE TITLE
DAV properties are not handled when renaming/moving/deleting/sharing containing folder

### ISSUE THREAD

**Issue by hschletz** [nextcloud/server#25717]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a folder.
2. Create a file or folder within that folder with DAV properties (using PROPPATCH or extended MKCOL).
3. Rename, move or delete the parent folder.

Step 2 will create a row like this in the "properties" table:

````
 id |  userid  |         propertypath        | propertyname | propertyvalue 
----+----------+-----------------------------+--------------+---------------
 42 | username | files/username/parent/child | {foo}bar     | baz
````

### Expected behaviour
The rows in the "properties" table that correspond to elements **below**  the parent folder should be updated/deleted.

### Actual behaviour
Only rows for the parent folder itself (if any) are updated/deleted, but not those of any object below that folder.

This leaves us with orphaned rows. Additionally, in case of renaming/moving, all objects within that folder lose their properties. If a folder and child object with the original names are created later, child objects would inherit the previously orphaned properties out of the blue.

### Server configuration

**Operating system:** Arch Linux

**Web server:** Apache 2.4.46

**Database:** PostgreSQL 11.10

**PHP version:** PHP 7.3.25

**Nextcloud version:** (see Nextcloud admin page) 20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from 18 through 19

**Where did you install Nextcloud from:** Initially from git, upgraded from ZIP archive

**Signing status:**
<details>
<summary>Signing status</summary>
No results
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
  - a private app I'm developing
Disabled:
  - activity
  - admin_audit
  - encryption
  - files_external
  - files_rightclick
  - firstrunwizard
  - text
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "20.0.7.1",
        "overwrite.cli.url": "http:\/\/nextcloud",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "debug": true,
        "logtimezone": "Europe\/Berlin",
        "log_rotate_size": 1048576,
        "maintenance": false,
        "app_install_overwrite": [
            "files_rightclick"
        ],
        "ldapIgnoreNamingRules": false,
        "ldapProviderFactory": "OCA\\User_LDAP\\LDAPProviderFactory",
        "theme": "",
        "loglevel": 2,
        "defaultapp": "files",
        "allow_local_remote_servers": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Firefox 85.0.2

**Operating system:** Arch Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
Nothing logged.
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Nothing logged.
</details>

#### Browser log
<details>
<summary>Browser log</summary>
Nothing relevant logged.
</details>

One way to solve this problem would be traversing the filesystem tree and delete/update properties for every contained element. This could be slow for large trees and introduce a lot of pitfalls on its own.

As a simpler approach, instead of storing the path in the "properties" table, it could simply reference the corresponding row in the "filecache" table which does get updated correctly. Of course this would only work for filesystem resources. Any other resources should store the path as usual. This would also make the property storage much more robust because non-DAV-operations (via Nextcloud's PHP API, for example) would still be recognized.

**Comment by hschletz** [comment]
I got a solution working for me. It takes the same path-based approach as the existing implementation, but accounts for child elements below the parent element's path.

It's not a general purpose solution yet. The SQL statements below work with PostgreSQL, but may need to be adapted for portability. I'm posting this as a hint what would need to be done for a full fix.

Properties are handled in OCA\DAV\DAV\CustomPropertiesBackend. The SQL statements in delete() and move() need to be changed:

I *changed* the statement in delete() to:

```php
$statement = $this->connection->prepare(
    'DELETE FROM `*PREFIX*beoportal_properties` WHERE `userid` = ? AND (`propertypath` = ? OR starts_with(`propertypath`, ?))'
);
$statement->execute([
    $this->user->getUID(),
    $path,
    $path . '/', // add slash to path prefix so that deleting /path/to/something would not touch /path/to/something_else
])->closeCursor();
```

I *added* a second statement to move():
```php
$statement = $this->connection->prepare(
    'UPDATE `*PREFIX*beoportal_properties` ' .
    'SET `propertypath` = ? || right(`propertypath`, ?) ' . // target path prefix + source path suffix
    'WHERE `userid` = ? AND starts_with(`propertypath`, ?)'
);
$statement->execute([
    $destination . '/',
    -1 - mb_strlen($source),
    $this->user->getUID(),
    $source . '/',
])->closeCursor();
```

This approach always requires the full path in properties.propertypath. The existing implementation has a length constraint on that column, and long paths get hashed. The constraint has to be removed (change column type to TEXT) and paths must no longer be prepared via formatPath().

Another caveat: the properties table has references to users in the userid column. Deleting users would leave orphaned rows behind. This can be prevented either by a foreign key constraint on users.uid with ON DELETE CASCADE, or a listener on UserDeletedEvent.

The problem with non-DAV file operations is still unsolved.

**Comment by szaimen** [comment]
Hi @heschletz,
do you mind creating a PR with your patch for discussion?
Thank you!

**Comment by hschletz** [comment]
I had trouble backporting my reimplementation into the master branch. I also discovered another major flaw in the user/path-based approach: when a filesystem object gets shared, every user sees their own path to the same object, but only
the original path is stored in the properties table.

Having properties stored per user seems to be an intentional design decision, but does not make sense to me. One could argue that each user sees files under their own user-specific URI, making them unique resources with a unique set of properties. On the other hand, system properties and the content are already identical for shared objects, so why not handle custom properties consistently?

To summarize, the user/path based implementation is extremely fragile for filesystem objects:

- Renaming/moving objects requires taking care of updating the property paths.
- Deleting objects and users requires deleting corresponding rows in the "properties" table.
- Filesystem operations via the Nextcloud PHP API bypass the DAV implementation, leaving properties in an inconsistent state.
- Properties can't be shared between users, which may or may not be desired. This feature is crucial for my application.

For these reasons, I have reimplemented the backend for my own app:

- For a file URI, properties are stored in a new table referencing filecache.fileid. This solves all of the above problems.
- Everything else is forwarded to the existing backend.

I will try to turn that into a PR.

**Comment by szaimen** [comment]
@hschletz any update here?

**Comment by hschletz** [comment]
As mentioned, I have successfully implemented a sabre/dav plugin in my own app which replaces the existing backend. This is easier to maintain than an unofficial Nextcloud patch. For a full solution, this should better be implemented in the DAV core.

ATM I don't have the time for this. If there is interest, I could post my code here for someone else to pick up.
