### ISSUE TITLE
WEBDAV file locking

### ISSUE THREAD

**Issue by emc02** [nextcloud/server#25718]
Will, I know it's already mentioned in #1308, but that Issue is closed and not solved and it would be very important in business environments to have an working file lock for Microsoft Office Documents!
I know nextcloud works on other solutions and wants to go with collaborate, but in fact in business Microsoft Office is used a lot and so file locking on webdav should not be the show stopper.

**Comment by Flobster1804** [comment]
Yeah, I agree. I have talked to a few Next Cloud partners / resellers and they are all frusted not to be able to offer a solution. Open/Libreoffice and working in the browser are only a niche solution. The majority of the market uses Microsoft Office. I actually wonder what people do if they use NextCloud in a larger team with Microsoft Office? Do they never work on the same files? Without proper file locking in webdav it is simply not an option for us to work with Nextcloud - which is real pity. 

Please finde a solution!

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/files_lock/issues/27
