### ISSUE TITLE
installed_version is 0 in oc_appconfig

### ISSUE THREAD

**Issue by pbek** [nextcloud/server#2572]
### Steps to reproduce
1. I installed NC 11 from git
2. I run `ocdev server --port 8081`
3. I installed <https://github.com/pbek/qownnotesapi> and <https://github.com/pbek/ownbackup> directly from the NC app store by clicking the `Activate` buttons
4. When I looked into the table `oc_appconfig` the `installed_version` for both apps was `0`

Note: I had that also reported from other users with previous versions of NC from time to time, like [here](https://github.com/pbek/QOwnNotes/issues/262).

### Expected behaviour
I expected `installed_version` to contain the actual version number of `info.xml`.

### Actual behaviour
`installed_version` was `0` for both apps

### Server configuration
Ubuntu Linux 16.04
Apache
MySQL
PHP 7.0.8-0ubuntu0.16.04.3
fresh NC 11.0 RC 1 from git

**Comment by sfurey** [comment]
I can confirm and reproduce this as well

**Comment by MorrisJobke** [comment]
same here

@LukasReschke Mind to have a look? ;)

**Comment by LukasReschke** [comment]
Can reproduce but only on qownnotesapi. Let me see…

**Comment by LukasReschke** [comment]
Gotcha. So this happens when the app does not yet exist locally. Proposed patch is at https://github.com/nextcloud/server/pull/2594 – tests and review welcome! 🚀

**Comment by pbek** [comment]
I can confirm that now after the installation of `qownnotesapi` the correct version `16.9.0` was stored in the database. Thanks a lot!
