### ISSUE TITLE
session_lifetime dependency on PHP's session.gc_maxlifetime is not documented

### ISSUE THREAD

**Issue by drebs** [nextcloud/server#25724]
In [code](https://github.com/nextcloud/server/blob/24d436cb600a725ba162a5387552a996a6fc486f/lib/private/Template/JSConfigHelper.php#L186), `session_lifetime` is defined as `min(NC's session_lifetime, PHP's session.gc_maxlifetime)`, but:

- there's no indication in [the documentation](https://docs.nextcloud.com/server/20/admin_manual/configuration_server/config_sample_php_parameters.html?highlight=session_lifetime) that PHP config influences the maximum value for `session_lifetime`; and
- `php occ config:list` will show whatever is in `config.php` files, independent of PHP config.

I bumped into this problem while trying to increase the auto logout time in one NC installation I manage, and had to read source code to find what was wrong. If this was documented, it could save some debugging time.

This only started to be a real problem for our users after turning on `auto_logout`.

EDIT: found the reason why the problem started expressing itself.

**Comment by skjnldsv** [comment]
docs adeed https://github.com/nextcloud/server/pull/26007!
Thanks!
