### ISSUE TITLE
WebDAV not working if running webserver and reverse proxy in ports different from standard

### ISSUE THREAD

**Issue by anonimou0** [nextcloud/server#2573]
### Steps to reproduce
1. Run a nginx reverse proxy, receiving connections on port, let's say, 5000. It will take the request (on example.com/nextcloud) an forward to apache which will be running the nexcloud. Nginx take care of ssl certificate.
2. Run the apache on http-only, on a port different from default (80 and 443), let's say 5432.
3. Try to connect with DAVDroid to example.com/nextcloud/remote.php/webdav/ .

### Expected behaviour
It was expected to connect at the nextcloud and able to share contacts and calendar, for example. 

### Actual behaviour
DAVDroid get stuck on `Configuration detection. Wait, looking for server...` . Even if I enter a wrong password it get stuck on this message. If I enter the right user/password, under nextcloud Admin, it shows that DAVDroid got connected but gets stucked on this message.. 
The nextcloud app works. "davs:// on linux" works..

### Server configuration
**Operating system**: Armbian Jessie
**Web server:** Apache + nginx (reserve proxy)
**Database:** MySQL
**PHP version:** PHP5
**Nextcloud version:** 10.1
**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install
**Where did you install Nextcloud from:** downloaded from nextcloud.com
**Signing status:**
No errors have been found.

**List of activated apps:**
Default Apps + External Storage

**The content of config/config.php:**
Here's the relevant part:
<details>
`
'trusted_arrays' => array ( 0 => '192.168.1.98'),
'datadirectory' => '/media/data/nextcloud/',
'overwrite.cli.url' => 'https://example.com:5000/nextcloud/',
'overwritehost' => 'example.com:5000',
'overwriteprotocol' => 'https',
'overwritewebroot' => '/nextcloud',
`
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

### Client configuration
**Browser:**
Acessing via any browser the referece link (example.com:5000/nextcloud/remote.php/webdav):
`This is the WebDAV interface. It can only be accessed by WebDAV clients such as the ownCloud desktop sync client.`

Checking on similar issues, people got it working redirecting the WAN port to the 443 ou 80 port, in LAN port or making hosts redirecting to localhost `127.0.0.1 example.com` .
When connecting to nextcloud, I got sometimes:
`Your web server is not yet properly setup to allow files synchronization because the WebDAV interface seems to be broken. Please double check the installation guides.`

If I try the `overwritehost` option, changing it to `192.168.1.98` some links get the hardlink (as external download or logout). That's why I'm using the http link on  `overwritehost`.

Some reference:
https://github.com/owncloud/core/issues/2495
https://github.com/owncloud/core/issues/2511

**Comment by anonimou0** [comment]
A little bit more:
Accessing `https://example.com:5000/nextcloud/remote.php/carddav` and `/caldav,` I get the following:

`<d:error>`
`<s:sabredav-version>3.0.9</s:sabredav-version>`
`<s:exception>Sabre\DAV\Exception\NotImplemented</s:exception>`
`<s:message>There was no handler found for this "GET" method</s:message>`
`</d:error>`

Accessing other random links on `remote.php` says that the app isn't installed.

**Comment by nickvergessen** [comment]
Can you check whether the proxy settings help?
https://github.com/nextcloud/server/blob/bf043deba39af2b7586b3617aa1bc534df98b6ee/config/config.sample.php#L339-L375

**Comment by anonimou0** [comment]
@nickvergessen , actually, I already had those setted. 
However, after messing arrowing yesterday, I was able to get it working. Not sure exactly what I did (if in DAVDroid or Nextcloud)
I don't remember changing anything aside from using example.com/nextcloud/remote.php/**dav/** {{intead of example.com/nextcloud/remote.php/**webdav/** }}.

Anyway, it seems fixed. Not sure exactly why.
Many thanks.
