### ISSUE TITLE
[NC 21] WebGUI issues. Deadlock errors, chunk errors.

### ISSUE THREAD

**Issue by SimplyCorbett** [nextcloud/server#25749]
**None of these issues happen over webdav,** only in the web GUI.

Firstly, uploading a folder with many files (hundreds to thousands) causes deadlock errors.

![ShareX_BpKX2ieWfy](https://user-images.githubusercontent.com/7935624/108739401-755a8280-74e9-11eb-855f-776321b0060f.png)

![ShareX_MnMEMo5FRg](https://user-images.githubusercontent.com/7935624/108739458-85726200-74e9-11eb-8856-c04d4700f5aa.png)

Secondly, uploading a multi-file folder with several GB of files results in chunk 500 errors along with "problem writing to storage".

In NC 20 when chunk 500 errors occurred the files were slowly put together with php and appeared after a few minutes. This does not happen on NC 21. The files do not appear.

**Uploading individual files from that folder works fine.** so it's only when uploading multiple files...

![MobaXterm_C3vNyENjIP](https://user-images.githubusercontent.com/7935624/108739648-b357a680-74e9-11eb-9042-766622c58a59.png)

### Server configuration

**Operating system:**
Debian 10 64bit

**Web server:**
Nginx mainline

**Database:**
Postgresql

**PHP version:**
PHP 7.4-FPM with redis and apcu.

**Nextcloud version:** (see Nextcloud admin page)
21

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh install

**Where did you install Nextcloud from:**
Nextclouds website. Baremetal install, no SNAP.

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'filerot.com',
  ),
  'datadirectory' => '/var/www/data',
  'dbtype' => 'pgsql',
  'version' => '21.0.0.18',
  'overwrite.cli.url' => 'https://filerot.com',
  'dbname' => 'filerot',
  'dbhost' => '10.0.2.40',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'filerot',
  'dbpassword' => '',
  'installed' => true,
  'filelocking.enabled' => false, //occurs with or without this disabled.
  'memcache.local' => '\OC\Memcache\APCu',
  'memcache.distributed' => '\OC\Memcache\Redis',
  'memcache.locking' => '\OC\Memcache\Redis',
  'redis' => array(
     'host' => '/var/run/redis/redis-server.sock',
     'port' => 0,
     'timeout' => 1.5,
      ),
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No.

**Are you using encryption:** yes/no
No.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No.
</details>

### Client configuration
**Browser:**
Latest firefox with ublock and origin. Happens on chrome as well.

**Operating system:**
Windows 10

**Comment by szaimen** [comment]
I suppose this issue is still valid on NC21.0.2?
