### ISSUE TITLE
Removing a user from a group unexpectedly deletes their files, even if the share is owned by someone else

### ISSUE THREAD

**Issue by flokli** [nextcloud/server#25755]
### Steps to reproduce
1. Create a folder F by user R
2. Make users A.B member of group I
3. Share the folder F to group I
4. Have users collaboratively create subfolders inside F, and files in there
5. Have user A leave group I

### Expected behaviour
Reading https://nextcloud.com/blog/what-happens-to-your-data-when-a-user-account-is-deleted/, I'd assume Case 4 would apply:

> Case 4: Files created by the user, but which are stored in a folder created by another user and shared with others: here the origin of the folder determines what happens – if someone else created it (and shared it with the account to be deleted), the files remain.

Beacuse of this, folder F was created by user R on purpose, avoiding any file removal when accounts get deleted or members leave groups.

### Actual behaviour
All files and folders created by A inside F were removed. This is especially critical, given most of the folder structure below folder F was created by user A, dragging pretty much everything into the void.

### Server configuration

**Operating system:**
Linux

**Web server:**
N/A

**Database:**
mysql 10.3.27

**PHP version:**
 Version: 7.4.13 

**Nextcloud version:** (see Nextcloud admin page)
20.0.4

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from older

**Where did you install Nextcloud from:**
Hetzners hosted Nextcloud.

```
No errors have been found.
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
unknown

**Are you using encryption:** yes/no
no

**Comment by flokli** [comment]
Screenshot from the Event log as user A.

As can be seen there, they only removed themselves from the group, but did not manually start removing files.

![image](https://user-images.githubusercontent.com/183879/108771936-9f00c180-755c-11eb-8bd5-6badc3cc4b88.png)

Screenshot from the Event log (seen as user R):

![image](https://user-images.githubusercontent.com/183879/108772596-804efa80-755d-11eb-8934-359406af0485.png)

Maybe this helps understanding which code paths triggered this.

There are backups, but nothing currently prevents this from happening again.

**Comment by flokli** [comment]
I'm not even sure how A could leave the group - they're not an admin of that group.

**Comment by flokli** [comment]
I received some server logs, and those show some `DELETE` requests sent from the client (`mirall/3.1.2stable-Win64`) - which suggests it might be some buggy client implementation, similar to https://github.com/nextcloud/desktop/issues/1433.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by flokli** [comment]
@szaimen it's hard to know, as we don't know how this was caused.

Was this a simple triage request, or are you referring to a specific commit in NC21.0.2 that should have fixed this?

**Comment by flokli** [comment]
Still waiting on feedback from @szaimen, not stale.

**Comment by szaimen** [comment]
former

**Comment by flokli** [comment]
Not stale.

**Comment by szaimen** [comment]
So you can reproduce this on NC21.0.4?

**Comment by flokli** [comment]
@szaimen as written in https://github.com/nextcloud/server/issues/25755#issuecomment-885728293, this is not easily reproducable.

Were there any changes in the meantime that might have fixed this?
