### ISSUE TITLE
Downloading from share via Chrome for Android fails

### ISSUE THREAD

**Issue by jasonbayton** [nextcloud/server#2575]
When trying to download via Chrome for Android on any public share, it fails after a few moments with the error:

> example.zip download failed due to server issues

This happens on my own server and the public demo server, here's an example: https://demo.nextcloud.com/index.php/s/gmZEm3i00Dx3Qyr/download

I see no errors in Apache or NC logs to suggest an issue.

Android 6.0 (though replicated on 5.x , 4.4 and 7.0) with latest Chrome 54.0.2840.85

Context: https://help.nextcloud.com/t/appending-download-to-shared-files-unsuccessful-download-on-chrome-android/5574

NC 10.0.1

**Comment by nickvergessen** [comment]
Ref https://github.com/nextcloud/server/pull/1456

I though it was fixed with Chrome 54? @LukasReschke

**Comment by jasonbayton** [comment]
That reference indicates 10.0.2? I'm still on 10.0.1 until the final for 11 drops.

**Comment by jasonbayton** [comment]
I've upgraded to 11, but unfortunately the issue remains

**Comment by nickvergessen** [comment]
Yes, because it's basically something your Chrome and/or the download manager fuck up.

**Comment by jasonbayton** [comment]
If it were just mine it'd be manageable, but it appears to fail on every Android device I've managed to get my hands on recently, running the latest version of Chrome through various manufacturers. I saw a mention related to cookies on the 11 announcement so hoped something might have changed.

BTW, your notifications come through as Joas Schilling?

**Comment by MorrisJobke** [comment]
I tested this on two Android 4.1 devices, an Android 6 and an Android 7. It works now. They fixed this in a recent version of chrome.
