### ISSUE TITLE
Dashboard app to respect Theming app settings by default

### ISSUE THREAD

**Issue by pieter-groeneweg** [nextcloud/server#25760]
In noticed dahsboard to follow default NC theme even when theming has a different setting.

It would be very nice if DashBoard would respect the Themin app settings.

**Comment by kesselb** [comment]
Please add more details.

**Comment by pieter-groeneweg** [comment]
When I make changes to Theme app (color, logo, image) this stands for all apps.
(but for the the background image)
When dashboard app is enabled, the default  is blue and clouds.. 

imho this should respect the Theme settings by default.
