### ISSUE TITLE
File listing loading does not allow searching

### ISSUE THREAD

**Issue by jkufner** [nextcloud/server#25767]
### Steps to reproduce
1. Open a folder with a lot of files using web interface.
2. Scroll down, more files will load.
3. Try to find a file of a given name by pressing ctrl+f.

### Expected behaviour
Browser will find the file in the current folder, just like any text in a page.

Nexcloud should show all files in the folder, but it may lazy load file details as user scrolls down. This way the scrolling will work as expected, but server load would be still low (Gitlab does this).

### Actual behaviour
File list is incomplete (loads on scroll) so the search finds nothing.

### Server configuration
**Nextcloud version:** 20.0.7

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
