### ISSUE TITLE
"Storage full" notification on read-only external storage

### ISSUE THREAD

**Issue by jkufner** [nextcloud/server#25766]
Nextcloud shows notifications for read-only external storages that the storage is almost full.

It is completely useless, because the storage is read-only anyway and we cannot write anything even if there is space available.

Note the storage itself is writable, but it is registered in Nextcloud as read only.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by jkufner** [comment]
Version 21.0.3 is still broken.

**Comment by joshtrichards** [comment]
Duplicate of #18552
