### ISSUE TITLE
Error upgrading to Nextcloud 21 - Segfault

### ISSUE THREAD

**Issue by TheColin21** [nextcloud/server#25761]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. try to manually update nextcloud
2. unzip v21, insert config file
3. try to run php occ upgrade (or any other occ command)

### Expected behaviour
Tell us what should happen
The command runs

### Actual behaviour
Tell us what happens instead
A segmentation fault appears after a few seconds, EDIT: before the segfault is shown, the process consumes as much RAM and CPU as possible

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache behind Nginx Reverse Proxy
**Database:**
MariaDB 10.5.9
**PHP version:**
7.4 and 8.0 (tried both)
**Nextcloud version:** (see Nextcloud admin page)
21.0.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
tried to update from 20.0.7
**Where did you install Nextcloud from:**
nextcloud.com
<details>

Insert your config.php content here. 
```
<?php
$CONFIG = array (
   'trusted_domains' => 
  array (
    ),
  'datadirectory' => '/var/www/vhosts/xxxxx/cloud_files',
  'dbtype' => 'mysql',
  'version' => '20.0.7.1',
  'overwrite.cli.url' => 'https://cloud.clnp.eu',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud',
  'dbpassword' => 'xxxx',
  'installed' => true,
  'mail_smtpmode' => 'sendmail',
  'mail_from_address' => 'administrator',
  'mail_domain' => 'clnp.eu',
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'updater.release.channel' => 'stable',
  'loglevel' => 0,
  'maintenance' => false,
  'theme' => '',
  'app_install_overwrite' => 
  array (
    0 => 'camerarawpreviews',
    1 => 'files_texteditor',
    2 => 'extract',
    3 => 'documentserver_community',
    4 => 'ocdownloader',
  ),
  'ldapIgnoreNamingRules' => false,
  'ldapProviderFactory' => 'OCA\\User_LDAP\\LDAPProviderFactory',
  'default_language' => 'de',
  'default_locale' => 'de',
);

```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
sftp, nextcloud
**Are you using encryption:** yes/no
no

**Comment by morph027** [comment]
Jip, same here. Using PSQL instead.

**Comment by harveytj03** [comment]
I found that replacing "php" in the command with "php7.4" sorta fixes it. It seems OCC is not liking the new PHP version.
If you have PHP 7.4 still setup, Use "sudo -u www-data php7.4 occ" instead. Typically it seems PHP 7.X and PHP 8 are installed commonly together.

**Comment by morph027** [comment]
@TheColin21 and me tried both versions, none worked

**Comment by cscholz** [comment]
Downgrade to NC 21.0.017 (RC2) fixed it temporary for me. #25769

**Comment by TheColin21** [comment]
> Downgrade to NC 21.0.17 (RC2) fixed it temporary for me. #25769
> So the issue is locate somewhere in the changes between 21.0.17 and 21.0.18 (final version)

Is rc2 stable?

**Comment by m4lvin** [comment]
It seems for running the occ command now apcu has to be enabled. This also worked for me:

> I had APCu activated in the nextcloud config.php. It seems I didn’t have apc.enable_cli=1 in /etc/php/8.0/cli/conf.d/20-apcu.ini. After I added that line to the file occ worked and there was no segmentation error anymore.

-- andreasus from https://help.nextcloud.com/t/solved-occ-command-php-fatal-error-allowed-memory-size-of-xxx-bytes-exhausted/108521/17

**Comment by morph027** [comment]
> It seems for running the occ command now apcu has to be enabled. This also worked for me:
> 
> > I had APCu activated in the nextcloud config.php. It seems I didn’t have apc.enable_cli=1 in /etc/php/8.0/cli/conf.d/20-apcu.ini. After I added that line to the file occ worked and there was no segmentation error anymore.
> 
> -- andreasus from https://help.nextcloud.com/t/solved-occ-command-php-fatal-error-allowed-memory-size-of-xxx-bytes-exhausted/108521/17

That did the trick for me, thank you!

**Comment by cscholz** [comment]
> It seems for running the occ command now apcu has to be enabled. This also worked for me:
> 
> > I had APCu activated in the nextcloud config.php. It seems I didn’t have apc.enable_cli=1 in /etc/php/8.0/cli/conf.d/20-apcu.ini. After I added that line to the file occ worked and there was no segmentation error anymore.
> 
> -- andreasus from https://help.nextcloud.com/t/solved-occ-command-php-fatal-error-allowed-memory-size-of-xxx-bytes-exhausted/108521/17

I can also confirm that it's working.

**Comment by TheColin21** [comment]
adding `apc.enable_cli=1` seems to work, still a bug in Nextcloud tho so I'm keeping the issue open

**Comment by abelbabel** [comment]
Same issue on FreeBSD 11.4-RELEASE with package `nextcloud-php73-21.0.0`. `apc.enable_cli=1` in `/usr/local/etc/php.ini` did the trick ... waiting eagerly for "real" solution ;)

**Comment by cvbkf** [comment]
Same problem on Ubuntu 20.04 with MySQL 8, PHP 7.4 and Nginx.
Running occ or the cron job quickly consumes all availabable RAM and SWAP  (24 / 24 GB)

enabling php-apcu for php-cli fixed the problem

**Comment by cedricbonhomme** [comment]
Same for me.

And If I increase the value of ```memory_limit```, the scripts get killed:

```bash
cedric@ssh1:~/www/cloud$ php /home/cedric/www/cloud/cron.php
Killed
cedric@ssh1:~/www/cloud$ php occ db:add-missing-indices
Killed
```

I just updated to 21.0.1.

For the database upgrade issue, the exception (Allowed memory size...) is raised on line 133 of /lib/private/AppFramework/Utility/SimpleContainer.php.

**Comment by rhonda** [comment]
> Same problem on Ubuntu 20.04 with MySQL 8, PHP 7.4 and Nginx.
> Running occ or the cron job quickly consumes all available RAM and SWAP (24 / 24 GB)
> 
> enabling php-apcu for php-cli fixed the problem

Unfortunately php-apcu doesn't fix it for me, I'm still running into the segfault because of running out of mem.

I am on Debian 10 here, with MariaDB 10.3, php 7.3 and apache2, so it seems to be only losely connected to the environment used.

**Comment by Githopp192** [comment]
Fortunately, i was not affected by this issue (i did the Upgrade from version 20.0.6 to 21.0.1 some days ago).
I did check PHP on my side : i've got the following cli-related config:

apc.enable_cli =>         On => On
opcache.enable_cli => On => On

Server Info:
-------------

Operating System: CentOS Linux release 8.3.2011
Upstream OS : Derived from Red Hat Enterprise Linux 8.3
Webserver: Apache/2.4.37 (centos)
Database: mysql 10.3.27-MariaDB,
PHP version: PHP Version => 7.4.16

**Comment by szaimen** [comment]
So yeah, how to proceed with this one @nextcloud/server ?
