### ISSUE TITLE
Failed to create tasks- or events-only calendars from DAVdroid

### ISSUE THREAD

**Issue by marc0s** [nextcloud/server#2576]
I'm trying to create a tasks-only calendar from a DAVdroid setup from my phone. I don't know if they're even supported, but they fail to be created.

### Steps to reproduce
1. Set up a DAVdroid account
2. Create a new tasks-only calendar (or events-only one)
3. Sync

### Expected behaviour
Calendar is created in server

### Actual behaviour
A SabreDAV exception: 404 not found.

### Server configuration
Debian stable

**Web server:**
nginx

**Database:**
Postgresql 9.5.3

**PHP version:**
PHP 5.6.27-0+deb8u1

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 9 (previously from OC)

**Where did you install Nextcloud from:**
tar file

From my logfile:
```
{"reqId":"8WZQxX+kvNfLKflWwfWL","remoteAddr":"127.0.0.1","app":"admin_audit","message":"Login successful: \"marc0s\"","level":1,"time":"December 08, 2016 22:16:46","method":"DELETE","url":"\/remote.php\/caldav\/calendars\/marc0s\/69ca09ce-d37e-4621-8664-111df3d6d38f\/","user":"marc0s"}
{"reqId":"8WZQxX+kvNfLKflWwfWL","remoteAddr":"127.0.0.1","app":"caldav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 404 Node with name '69ca09ce-d37e-4621-8664-111df3d6d38f' could not be found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotFound\",\"Code\":0,\"Trace\":\"#0 \\\/srv\\\/http\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(76): OCA\\\\DAV\\\\CalDAV\\\\CalendarHome->getChild('69ca09ce-d37e-4...')\\n#1 \\\/srv\\\/http\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Tree.php(178): Sabre\\\\DAV\\\\Tree->getNodeForPath('calendars\\\/marc0...')\\n#2 \\\/srv\\\/http\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(285): Sabre\\\\DAV\\\\Tree->delete('calendars\\\/marc0...')\\n#3 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpDelete(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/srv\\\/http\\\/nextcloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/srv\\\/http\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:DELETE', Array)\\n#6 \\\/srv\\\/http\\\/nextcloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/srv\\\/http\\\/nextcloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/caldav.php(84): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/srv\\\/http\\\/server\\\/remote.php(139): require_once('\\\/srv\\\/http...')\\n#9 {main}\",\"File\":\"\\\/srv\\\/http\\\/nextcloud\\\/apps\\\/dav\\\/lib\\\/CalDAV\\\/CalendarHome.php\",\"Line\":105,\"User\":\"marc0s\"}","level":0,"time":"December 08, 2016 22:16:46","method":"DELETE","url":"\/remote.php\/caldav\/calendars\/marc0s\/69ca09ce-d37e-4621-8664-111df3d6d38f\/","user":"marc0s"}
```
(IP address redacted)

Just noticed the DELETE request, don't know if this has something to do (DELETEing a resource while creating it...). Might it be a DAVdroid issue?

Thanks.

**Comment by jancborchardt** [comment]
Any idea here @nextcloud/calendar or @nextcloud/tasks?

**Comment by georgehrke** [comment]
No, never seen this before.
I don't have an Android device, would be good if someone else could sniff and post the requests between DavDroid and Nextcloud.

**Comment by tcitworld** [comment]
Two strange things here : 
* the delete request
* the `69ca09ce-d37e-4621-8664-111df3d6d38f` name

cc @rfc2822

**Comment by eppfel** [comment]
I don't know if it is related, but I had to manually fiddle in the database once, after I created a new calendar in the calendar app and it popped up as a list/calendar in my todo list app. (if I remember correctly)

**Comment by jancborchardt** [comment]
Ref @rullzer and @LukasReschke for dav too.

**Comment by marc0s** [comment]
Apologize for the late response.

I was going to attach the davdroid log, and while trying to reproduce the issue I couldn't do so, it worked flawlessly.  Might it be related to the fact that I added the redirection suggested in this other issue https://github.com/nextcloud/server/issues/2747#issuecomment-268111108 ?  I was hitting that same bug and that redirection fixed it.

Thanks.

**Comment by georgehrke** [comment]
>  I couldn't do so, it worked flawlessly. 

Closing since neither we nor the original reporter can still report the issue.
