### ISSUE TITLE
Nextcloud 21.0.0 - ./occ segmentation fault

### ISSUE THREAD

**Issue by cscholz** [nextcloud/server#25769]
### Steps to reproduce
Unsure if reproducable

### Expected behaviour
./occ should run without segmentation fault

### Actual behaviour
Nextcloud 20.0.0 - occ segmentation fault
Feb 23 18:40:45 mx02 kernel: php[18855]: segfault at 7ffc03f89fe8 ip 000055b4e1ac2d13 sp 00007ffc03f89ff0 error 6 in php8.0[55b4e18cf000+279000]
Feb 23 18:41:18 mx02 kernel: php[18983]: segfault at 7ffc37e61ff8 ip 0000557cf09144da sp 00007ffc37e62000 error 6 in php8.0[557cf0823000+279000]

### Server configuration

**Operating system:**
Debian GNU/Linux 10 (buster)

**Web server:**
nginx-full (1.14.2-2+deb10u3)

**Database:**
mariadb-server-10.3 (1:10.3.27-0+deb10u1)

**PHP version:**
PHP 8.0.2
php8.0-common (8.0.2-5+0~20210220.13+debian10~1.gbpb043fe)

**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 21 (final release)

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updates from old nextcloud version

**Where did you install Nextcloud from:**
nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
Results
=======
- core
	- EXTRA_FILE
		- core/doc/user/_static/underscore-1.3.1.js

Raw output
==========
Array
(
    [core] => Array
        (
            [EXTRA_FILE] => Array
                (
                    [core/doc/user/_static/underscore-1.3.1.js] => Array
                        (
                            [expected] => 
                            [current] => e133872bad7dbc99f3caec29e662fc67ac90024018b61ed4061b5a52d10ebca5a00f6841c9ca599715c18fc123c89f30c9615dc5d2caef9ea3e55a448ba4086a
                        )

                )

        )

)```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Alle apps are disabled. 
sudo -u www-data php occ app:list crashed with segmentation fault
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>
<?php
$CONFIG = array (
  'instanceid' => '123',
  'passwordsalt' => '345',
  'trusted_domains' =>
  array (
    0 => 'cloud.domain.tld',
  ),
  'datadirectory' => '/../data',
  'dbtype' => 'mysql',
  'version' => '21.0.0.18',
  'dbname' => 'db_sql_3',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'db_sql_3',
  'dbpassword' => 'password',
  'installed' => true,
  'forcessl' => true,
  'mail_smtpmode' => 'smtp',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtphost' => '127.0.0.1',
  'mail_smtpport' => '587',
  'mail_smtppassword' => 'password',
  'mail_smtpname' => 'noreply@domain.tld',
  'trashbin_retention_obligation' => 'auto,30',
  'mail_from_address' => 'noreply',
  'mail_domain' => 'domain.tld',
  'log_type' => 'syslog',
  'loglevel' => 0,
  'logdateformat' => 'F d, Y H:i:s',
  'logtimezone' => 'Europe/Berlin',
  'log_query' => false,
  'log_authfailip' => true,
  'log_rotate_size' => '104857600',
  'session_lifetime' => 3600,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpauth' => true,
  'secret' => '1234567890',
  'updatechecker' => true,
  'check_for_working_htaccess' => false,
  'updater.release.channel' => 'stable',
  'overwrite.cli.url' => 'https://cloud.domain.tld',
  'enable_certificate_management' => true,
  'versions_retention_obligation' => '14,auto',
  'filelocking.enabled' => true,
  'filelocking.debug' => true,
  'default_phone_region' => 'DE',
  'twofactor_enforced' => 'false',
  'twofactor_enforced_groups' =>
  array (
  ),
  'onlyoffice' =>
  array (
    'verify_peer_off' => true,
  ),
  'twofactor_enforced_excluded_groups' =>
  array (
    0 => 'admin',
    1 => 'users',
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Memcached',
  'memcached_servers' =>
  array (
    0 =>
    array (
      0 => 'localhost',
      1 => 11211,
    ),
  ),
  'app_install_overwrite' =>
  array (
    0 => 'admin_notifications',
    1 => 'files_trackdownloads',
    2 => 'twofactor_email',
    3 => 'metadata',
    4 => 'spreedme',
    5 => 'breezedark',
    6 => 'uploaddetails',
    7 => 'rainloop',
    8 => 'checksum',
    9 => 'spreed',
    10 => 'files_retention',
  ),
  'mysql.utf8mb4' => true,
);
```
</details>

**Are you using external storage, if yes which one:** local...

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** No backend...

**Comment by shyim** [comment]
You should try this https://bugs.php.net/bugs-generating-backtrace.php
Mostly its related to php opcache module

**Comment by cscholz** [comment]
@shyim: I'll give it a try and give feedback.

But even if it is not supported I've downgraded from NC 21.0.18 (final version) to 21.0.17 (RC2) and the segfault error is gone.

What I have seen on 21.0.18 is that occ or to be more precise the php process starts consuming 22GB ram before the process crashes.

**Comment by tcitworld** [comment]
Seems like a duplicate from #25761
