### ISSUE TITLE
add functionality to display a list of users who are disabled occ user:

### ISSUE THREAD

**Issue by gorsing** [nextcloud/server#25765]
Dissemination of functionality. I really need the functionality to display a list of users who are disabled

occ user:list now

occ user:list --all -->> occ user:list
occ user:list --disable -->> list user disable after used occ user:disable uid

**Comment by gorsing** [comment]
How get a list of users who are disabled ???

**Comment by kesselb** [comment]
Sounds good to me. 

Unless one implemented it you may use: `occ user:list --info --output json |jq '.[] | select(.enabled==false)'`.

https://jqplay.org/s/XkQftQSYwk

**Comment by gorsing** [comment]
A good option. If registered without using LDAP. And I have 50/50

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.2?
