### ISSUE TITLE
PHP 7.1 support

### ISSUE THREAD

**Issue by brainfoolong** [nextcloud/server#2577]
Hi!

PHP 7.1 is stable since beginning of december 2016.
When we can expect offical nextcloud support for this?

The current RC or master github repository don't seem to work either.

**Comment by LukasReschke** [comment]
Please file dedicated issued if you experience something broken in 7.1 - while not officially supported yet the unit tests are already executed against 7.1

**Comment by perfect7gentleman** [comment]
updated to php_7.1 and nc_11rc1.

> Can't write into config directory!

This can usually be fixed by giving the webserver write access to the config directory.

>
