### ISSUE TITLE
Event "Date of death" is reported / displayed as birthday

### ISSUE THREAD

**Issue by Dieter15** [nextcloud/server#25779]
vCard object with a valid DEATHDATE:yyyy-mm-dd is accepted in NC Contacts app.
In NC birthday-calendar there is an entry displayed for the given month and day, but the text says "birthday" instead of "day of death".

Furthermore, the event is further described by "from dd.mm.yyyy ... to dd.mm.yyyy" (a range of days).
However, the event death refers to s single day, not to a range of days.

Sample VCF file for input to Contacts app and afterwards for viewing the information in NC Calendar app (change values according to your needs for reproduction):

BEGIN:VCARD
VERSION:3.0
FN:Smith\, John
N:Smith;John;;
BDAY:19370411
ADR;type=home:;;Wall street 1;New York;New Jersey;123456;USA
DEATHDATE:2021-02-22
REV:20210222T080324Z
END:VCARD

### Steps to reproduce
1. Deploy vCard object (see above)
2. Check in NC Calendar app

### Expected behaviour
1. Display event "date of death" as such, not as "birthday"
2. Drop superfluous information like "from dd.mm.yyyy ... to dd.mm.yyyy" (a range of days); see above

### Actual behaviour
Detailed description above

### Calendar app
**Calendar app version:** (see apps admin page, e.g. 2.0.1)
Calendar app 2.1.3  / Contacts app 3.4.3

**CalDAV-clients used:** (Thunderbird Lightning, DAVx5, Evolution, macOS Calendar, etc)
DAVx5

### Client configuration
**Browser:** (e.g. Firefox 48)
Firefox 78

**Operating system:** (e.g. Arch Linux)
Debian 10.8

### Server configuration

**Operating system**: (e.g. Debian 8)

**Web server:** (e.g. Apache, Nginx,...)
Apache 2.4.38

**Database:** (e.g. MariaDB, SQLite or PostgreSQL)
MariaDB

**PHP version:** (e.g. 7.0.3)
PHP 7.3.27

**Nextcloud Version:** (see admin page, e.g. 17.0.2)
NC 20.0.7

**Updated from an older installed version or fresh install:**
Fresh install

**Comment by eibex** [comment]
#24742

**Comment by Dieter15** [comment]
Hi eibex,

#24742 refers to the situation where a user does not want that the corresponding contact is still valid / activated after the person's death date has been entered.
But why did the user enter the person's date of death? It would be straightforward to DELETE that contact.

My issue is:
i want to have the person's birth date AND also the same person's date of death (where applicable), in order to be always reminded by NC calendar about these two dates.

Please allow for such a solution.

Kind regards
Dieter

**Comment by Dieter15** [comment]
Hi eibex,

the bug described by me is difficult to trace - at least it seems so.

Obviously the bug arises under the following conditions:
1. Create a VCF file. It should contain some valid vCard objects. Some of them should contain both UID and BDAY entries.
2. Create a new address book in NC
3. Import the VCF file into the newly created address book. **No problems at all.**
4. Delete the newly created address book (I had to do for some reasons; I know that this is not a usual action)
5. Recreate the address book with the same name as before. Do it all in the same NC session
6. Import the VCF file. Now the bug shows up: as described in my first report (see above). As many errors are reported as there are BDAY entries in the VCF file.

Evidence:
1. Though the import of the VCF file mentions errors, there are no entries in the various log files
2. No errors / warnings in /var/html/nextcloud/data/nextcloud.log
3. No errors / warnings in /var/log/apache2/error.log
4. No errors / warnings in /var/log/apache2/access.log

Questions I cannot answer:
1. Is information retained in NC (or MariaDB) when deleting an address book, thus becoming an obstacle when re-importing the VCF file?
2. As I cannot provide sufficient evidence for this bug except describing the circumstances for it, what can I do now?
3. Where are errors stored which relate to the import of an VCF file?

Kind regards
Dieter

**Comment by szaimen** [comment]
I suppose this is still valid on NC21.0.2?
