### ISSUE TITLE
Deprecate OCP\Remote?

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#25780]
I don't find any usage of these classes in our GitHub organization as per https://sourcegraph.com/search?q=repo%3Agithub.com%2Fnextcloud%2F+OCP%5CRemote+count%3A1000&patternType=literal

Can we deprecate it so we have one less API to maintain? :)

Ref https://github.com/nextcloud/server/pull/6651

**Comment by LukasReschke** [comment]
@icewind1991 thoughts? You seem to have added them and probably have the most context if we need to keep them or not.

**Comment by szaimen** [comment]
Any update here?

**Comment by icewind1991** [comment]
fine by me
