### ISSUE TITLE
No Changelog for 20.0.8

### ISSUE THREAD

**Issue by stamfest** [nextcloud/server#25792]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Go to the Updater
2. Check the changelog
3. Search for 20.0.8 by eyeball and fail

### Expected behaviour
There should be a changelog for 20.0.8

### Actual behaviour
There is no changelog for 20.0.8

### Server configuration

**Operating system:** N/A

**Web server:** N/A

**Database:** N/A

**PHP version:** N/A

**Nextcloud version:** 20.0.7

**Updated from an older Nextcloud/ownCloud or fresh install:** N/A

**Where did you install Nextcloud from:** N/A

**Signing status:**
<details>
<summary>Signing status</summary>
</details>

**Comment by kesselb** [comment]
Similar to https://github.com/nextcloud/server/issues/23219. Changelog is coming soon.
