### ISSUE TITLE
Groups with External Users

### ISSUE THREAD

**Issue by kaffeeringe** [nextcloud/server#25795]
It would be cool, if I could add external users (users on other instances) to a group and thus share stuff with them.

**Comment by szaimen** [comment]
Please use federation for this. Thanks!

**Comment by kaffeeringe** [comment]
That is what I meant. Sorry that I kept my suggestion so short. I didn't have much time then. 

Example: I work on cloud1.example.com. There is a group of local users called "Group A". And there is user1@cloud2.example.com. I would like to add this external user to Group A and grant this group permissions on a folder and a calendar.

Imagine there is a group of Nextcloud admins from several clouds. I want to have a group of these admins and give this group permissions on several folders. It would be pretty easy to add another external admin without having to add her to all folders.

Is that clearer?
