### ISSUE TITLE
occ config:system:set trusted_domains "destroy" config.php

### ISSUE THREAD

**Issue by 0xOGeek** [nextcloud/server#25798]
### Steps to reproduce
1.  sudo -u www-data php occ config:system:set trusted_domains 1 test.yourdomain.com
2. Open config.php and see result
3.

### Expected behaviour
In config.php should apear:

  array (
    0 => '192.168.1.10',
    1 => 'test.yourdomain.com',
  ),

### Actual behaviour

  array (
    0 => '192.168.100.105',
    1 =>
    array (
      'test.yourdomain.com' => '',
    ),
  ),

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache2

**Database:**
MySQL

**PHP version:**
7.4.3

**Nextcloud version:** (see Nextcloud admin page)
20.0.8.1 / 20.0.6

**Updated from an older Nextcloud/ownCloud or fresh install:**

Updated and on fresh installations.

**Where did you install Nextcloud from:**
https://download.nextcloud.com/server/releases/nextcloud-*.zip

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>

```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by ggeorgg** [comment]
Try 
sudo -u www-data php occ config:system:set trusted_domains 1 --value=test.yourdomain.com
instead of 
sudo -u www-data php occ config:system:set trusted_domains 1 test.yourdomain.com

Does this make a difference?

**Comment by 0xOGeek** [comment]
With "--value=test.yourdomain.com" it works!
Magical! Thanks a lot! :)

Did i missed something in the manual?

**Comment by ggeorgg** [comment]
https://docs.nextcloud.com/server/21/admin_manual/configuration_server/occ_command.html#setting-a-single-configuration-value

**Comment by 0xOGeek** [comment]
Looks like i just exchanged GET with SET at somepoint.
"sudo -u www-data php occ config:system:get trusted_domains"

Head -> Table.

Thanks again, that was a pain. Closing.
