### ISSUE TITLE
nextcloud21.0 creat new users   Invalid language&& 'default_locale' => 'zh_CN',  not work

### ISSUE THREAD

**Issue by a937287837** [nextcloud/server#25791]
### Steps to reproduce
1.config.php setting,like this
 'default_phone_region' => 'CN',
  'default_language' => 'zh',
  'default_locale' => 'zh_CN',
2. creat new user 
Invalid language
3.new user first
![1](https://user-images.githubusercontent.com/13633977/109087375-4ee65280-7748-11eb-97bb-40b7f4c38dc8.JPG)
![2](https://user-images.githubusercontent.com/13633977/109087377-50b01600-7748-11eb-8f86-e317dda236bd.JPG)
![3](https://user-images.githubusercontent.com/13633977/109087379-50b01600-7748-11eb-8587-1adbea3f6812.JPG)

 login
default_language is chinese ,it's ok
but default_locale is English（United States）,it's ng

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:**centos 7

**Web server:** httpd 2.4.6

**Database:** mysql 10

**PHP version:** 7.3

**Nextcloud version:** (see Nextcloud admin page) 21

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Comment by szaimen** [comment]
Hm... does `zh_CN` work as language, too?
