### ISSUE TITLE
ImagickException: FailedToExecuteCommand ..

### ISSUE THREAD

**Issue by wallenium** [nextcloud/server#2579]
### Steps to reproduce
1. Just go to the Admin area

### Error Message
`ImagickException: FailedToExecuteCommand 'inkscape' '/tmp/magick-10857XI3tNBMKkA5E' --export-png='/tmp/magick-10857gQzvFK4Rmpsm' --export-dpi='90,90' --export-background='rgb(0%,0%,0%)' --export-background-opacity='0' > '/tmp/magick-108573FwCVBAeAeP3' 2>&1' (-1) @ error/delegate.c/ExternalDelegateCommand/463`

Nextcloud 11.0.0.6, PHP 7.0.10, Database MariaDB
Updated NC10.0.1 to RC1 by using the beta channel

**Are you using encryption:** yes

#### Nextcloud log (data/nextcloud.log)

```
"reqId":"WEl4NSUR4EMAADVS85kAAAAD","remoteAddr":"194.77.12.2","app":"index","message":"Exception:\"Exception\":\"ImagickException\",\"Message\":\"FailedToExecuteCommand 'inkscape' '\\\/tmp\\\/magick-13650St2Emo6tBIYO' --export-png='\\\/tmp\\\/magick-13650-_FazPvcHiMb' --export-dpi='90,90' --export-background='rgb(0%,0%,0%)' --export-background-opacity='0' > '\\\/tmp\\\/magick-13650iRehEVAM0Szy' 2>&1' (-1) @ error\\\/delegate.c\\\/ExternalDelegateCommand\\\/463\",\"Code\":415,\"Trace\":\"#0 \\\/home\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/IconBuilder.php(157): Imagick->readimageblob('<?xml version=\\\"...')\\n#1 \\\/home\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/IconBuilder.php(55): OCA\\\\Theming\\\\IconBuilder->renderAppIcon('files', 32)\\n#2 \\\/home\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/Controller\\\/IconController.php(127): OCA\\\\Theming\\\\IconBuilder->getFavicon('files')\\n#3 [internal function]: OCA\\\\Theming\\\\Controller\\\\IconController->getFavicon('files')\\n#4 \\\/home\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getFavicon')\\n#6 \\\/home\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Theming\\\\Controller\\\\IconController), 'getFavicon')\\n#7 \\\/home\\\/www\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('IconController', 'getFavicon', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#8 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#9 \\\/home\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#10 \\\/home\\\/www\\\/nextcloud\\\/lib\\\/base.php(1010): OC\\\\Route\\\\Router->match('\\\/apps\\\/theming\\\/f...')\\n#11 \\\/home\\\/www\\\/nextcloud\\\/index.php(40): OC::handleRequest()\\n#12 {main}\",\"File\":\"\\\/home\\\/www\\\/nextcloud\\\/apps\\\/theming\\\/lib\\\/IconBuilder.php\",\"Line\":157}","level":3,"time":"2016-12-08T15:11:50+00:00","method":"GET","url":"\/index.php\/apps\/theming\/favicon\/files?v=4","user":"--","version":"11.0.0.6"}
```

**Comment by nickvergessen** [comment]
@juliushaertl

**Comment by juliushaertl** [comment]
@wallenium Thanks for your report. Can you please give some more information on the setup?

**Operating system**:

**Web server:**

**Database:**

**What packages are installed for ImageMagick:**

**Comment by wallenium** [comment]
**Operating system:** Linux xxxxx.host 4.7.0-0.bpo.1-amd64 #1 SMP Debian 4.7.5-1~bpo8+2 (2016-10-01) x86_64
**Web server:** Apache 2.0 Handler
**Database**: MariaDB, not sure which Version. Would Need to open a ticket to see that.
###ImageMagick:
**Version:** 3.4.3RC1 
**imagick classes:** Imagick, ImagickDraw, ImagickPixel, ImagickPixelIterator, ImagickKernel 
**ImageMagick number of supported formats:**  234  

Do you Need more Information?

**Comment by juliushaertl** [comment]
@wallenium Ok, thanks. Could there be an issue with your ImageMagick setup? Are you using packages or do you build it from source?

Can you post the output of the following two commands:
```
convert -list format | grep SVG
convert  -list delegate | grep svg
```

**Comment by wallenium** [comment]
> web@xxx ~ # convert -list format | grep SVG
> convert: error while loading shared libraries: libMagickCore-7.Q16HDRI.so.0: cannot open shared object file: No such file or directory
> web@xxx ~ # convert -list delegate | grep svg
> convert: error while loading shared libraries: libMagickCore-7.Q16HDRI.so.0: cannot open shared object file: No such file or directory

**Comment by juliushaertl** [comment]
@wallenium Imagemagick tries to use inkscape to convert svg images but it fails for some reason. I guess you should try to contact the support of your hosting provider. This doesn't seem to be a server issue, so I'm closing this for now.

**Comment by wallenium** [comment]
Anbei die Antwort von Webgo24
> Der Alias ist dem Fall nicht korrekt verbunden, wenn Sie die Binary direkt ansprechen, funktioniert es:
> 
>  xxx@xxx ~ # /usr/bin/convert -list format | grep SVG
>       MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
>        SVG  SVG       rw+   Scalable Vector Graphics (RSVG 2.40.5)
>       SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (RSVG 2.40.5)
>  web120@s67 ~ # /usr/bin/convert -list delegate | grep svg
>  convert: unable to access configure file `delegates.xml' @ warning/configure.c/GetConfigureOptions/706.
>          svg =>          "rsvg" "%i" "%o"
> 
>  Derzeit ist convert an /usr/bin/convert-im6 angebunden, dies verarbeitet libMagickCore-7.Q16HDRI.so nicht korrekt.
> 
Mit der aktuellen RC2 trat der Fehler bisher nicht auf.
