### ISSUE TITLE
Nextcloud 21 - Warning	no app in context	 "Invalid data provided to provideInitialState by files"

### ISSUE THREAD

**Issue by fate8383** [nextcloud/server#25790]
I am having this warning, and exhausted my search ability to find out what it is 

Warning | no app in context | Invalid data provided to provideInitialState by files

Every time file app is open, logs generate this

Is this a bug or can be ignored or what can i do?

**Comment by v1r0x** [comment]
I got the same error and a blank files app (only left sidebar is visible). Don't know if that is related, but that's the only error I get

**Comment by amatteo78** [comment]
on NC21 same on my side, follow

**Comment by ramirooliveiracg** [comment]
Me too

**Comment by huangy10** [comment]
Same problem here. NC 21.

This error occurs each time when I try to upload a large file (about 3.5GB).

**Comment by huangy10** [comment]
Same problem here. NC 21.

This error occurs each time when I try to upload a large file (about 3.5GB).

**Comment by huangy10** [comment]
Same problem here. NC 21.

This error occurs each time when I try to upload a large file (about 3.5GB).

**Comment by amatteo78** [comment]
on my side I can upload large file, I upload upto 6GB single file. But every 30min about, I receive this message on log.

**Comment by v1r0x** [comment]
I tried to investigate where this is coming from and if it is (for my case) the reason I have a blank files app.
And in my case it happens here: https://github.com/nextcloud/server/blob/master/apps/files/lib/Controller/ViewController.php#L297
That's because I don't have a template directory (know nothing about it and couldn't find out how to set it :shrug:) and `null` is passed to the `provideInitialState` function, IMHO either the logged warning is misleading or passing `null` is wrong, because it passes `null` (thus invalid data) on purpose.
When replaced with something different than `null` the logged warning disappears, but my problem with a blank page is still present.

**Comment by zedpr0** [comment]
I solved it by going into the files app and clicking the + icon that you would use to create a new file and selecting "Set up Templates Folder". That removed the error for me.

**Comment by kostyainmadness** [comment]
> 
> 
> I solved it by going into the files app and clicking the + icon that you would use to create a new file and selecting "Set up Templates Folder". That removed the error for me.

Working solution, thank you

**Comment by v1r0x** [comment]
> I solved it by going into the files app and clicking the + icon that you would use to create a new file and selecting "Set up Templates Folder". That removed the error for me.

Good to hear it's fixed for you! 🎉 
Unfortunately, I have a blank page in files app and don't see the + icon 😆 But maybe that's a different bug...

**Comment by AndyFx12** [comment]
>I solved it by going into the files app and clicking the + icon that you would use to create a new file and selecting "Set up Templates Folder". That removed the error for me.

Less errors - but in my case, everyday I see again this warning once per user.

**Comment by Cardes** [comment]
I would be happy if there could be another solution to this, those directories are less than ideal if every user has to have lets say "Talk, Notes, Templates..." in his homedirectory. Perhaps there could be something like a hidden / system folder like the trash accessible via menu or a possibility to hide those folders away.

That beeing said, thanks for your work on this :)

**Comment by fabikroeger** [comment]
Hi people,

so same issue for me. The workaround does not work for me.

**Comment by amatteo78** [comment]
on my side, workaroung fixed.

**Comment by tomcatcw1980** [comment]
Hello,

got the same error message. But IMHO it cannot be the solution that every user has to add a template folder by himself. So ther must be an option in the config.php to set it globally for all users.

Is there a solutions available yet?

Greetings

**Comment by skjnldsv** [comment]
Fix in https://github.com/nextcloud/server/pull/26131
