### ISSUE TITLE
NC 21.0.0 shared folder name not translated

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/server#25800]
NC 21.0.0 final
language Arabic or any other lauguage

1- Share file or folder from user 1 to user 2
2- login to user 2 you will find the shared file inside (Freigaben) folder

![16143176141726224010483622681455](https://user-images.githubusercontent.com/74250574/109259485-5d4a7200-780d-11eb-80b6-02a23122c71c.jpg)

**Comment by szaimen** [comment]
This is working correctly.
