### ISSUE TITLE
NC 21 final get hang if type password wrong multiple times

### ISSUE THREAD

**Issue by FALErwi** [nextcloud/server#25808]
NC 21 final
PHP 7.4
Fresh installation based on reiger it services instruction. 

When you login to your account and leave it for some time it will not sign you out automatically but when you try to change the language for example will ask you to enter your password. Try to Type your password wrongly for about 6 times so your NC instance will get hang and never you can access your instance till you change the IP address for the server and restart it. 

Also I have tried to type any user and password wrongly for about 5 times in the login page, same issue.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
