### ISSUE TITLE
NC 21 Error: filesize(): stat failed for /data/flow.log at /lib/public/Log/RotationTrait.php#62

### ISSUE THREAD

**Issue by andyxheli** [nextcloud/server#25813]
Getting below error ever since updated to NC 21 from NC 20

Apache 2.4
PHP 7.4.15
MySQL 8.0.23

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"HobPfumnXkOgMUyRtcdT","level":3,"time":"2021-02-26T17:00:06+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"filesize(): stat failed for /var/data/flow.log at /var/www/nextcloud/lib/public/Log/RotationTrait.php#62","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/public/Log/RotationTrait.php","line":62,"function":"filesize"},{"file":"/var/www/nextcloud/apps/workflowengine/lib/BackgroundJobs/Rotate.php","line":49,"function":"shouldRotateBySize","class":"OCA\\WorkflowEngine\\BackgroundJobs\\Rotate","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\WorkflowEngine\\BackgroundJobs\\Rotate","type":"->"},{"file":"/var/www/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/var/www/nextcloud/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.0.18","id":"603949b8db38c"}
```
</details>

**Comment by ukjohnd** [comment]
Same here NC21

Webserver: Apache/2.4.46 (Unix) OpenSSL/1.1.1i PHP/8.0.2 mod_fcgid/2.3.9 (apache2handler)
Database: mysql 10.5.8
PHP version: 8.0.2

<details>
  <summary>Error Message</summary>
  {"reqId":"rhNwrCTIJla5pyTF7jqF","level":3,"time":"2021-02-26T20:06:20+00:00","remoteAddr":"","user":"--","app":"PHP","method":"","url":"--","message":{"Exception":"Error","Message":"filesize(): stat failed for /usr/share/webapps/nextcloud/data/flow.log at /srv/http/nextcloud/lib/public/Log/RotationTrait.php#62","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/srv/http/nextcloud/lib/public/Log/RotationTrait.php","line":62,"function":"filesize"},{"file":"/srv/http/nextcloud/apps/workflowengine/lib/BackgroundJobs/Rotate.php","line":49,"function":"shouldRotateBySize","class":"OCA\\WorkflowEngine\\BackgroundJobs\\Rotate","type":"->"},{"file":"/srv/http/nextcloud/lib/private/BackgroundJob/Job.php","line":52,"function":"run","class":"OCA\\WorkflowEngine\\BackgroundJobs\\Rotate","type":"->"},{"file":"/srv/http/nextcloud/lib/private/BackgroundJob/TimedJob.php","line":59,"function":"execute","class":"OC\\BackgroundJob\\Job","type":"->"},{"file":"/srv/http/nextcloud/cron.php","line":128,"function":"execute","class":"OC\\BackgroundJob\\TimedJob","type":"->"}],"File":"/srv/http/nextcloud/lib/private/Log/ErrorHandler.php","Line":92,"CustomMessage":"--"},"userAgent":"--","version":"21.0.0.18","id":"60399874a210a"}
</details>

**Comment by MastaG** [comment]
Same here using NC21 on Fedora 33 with nginx 1.18 and php 8.0.3

**Comment by steadybright** [comment]
Same here on new install of NC21:

Nextcloud 21.0.0-9 (Arch Linux package)   *config.php shows 21.0.0.18
Arch Linux 5.11.2.arch1-1
nginx 1.19.7-1
PHP 8.0.3-1
MariaDB 10.5.9-1

**Comment by radoeka** [comment]
I've the same, but at 20.0.8.

**Comment by kiv57** [comment]
Same here after upgrade from 20.xx to 21.0.1

NC 21.0.1
PHP 8.0.3

**Comment by Happyfeet01** [comment]
Same also here 

NC 21.01
Php 7.4
Debian 10

**Comment by prismopensource** [comment]
Same here with a fresh 21.0.1 install on Debian 10 with PHP 8.0 running as php-fpm with Apache 2.4.46 and MariaDB 10.5.9.

**Comment by turtlak69** [comment]
same here:
NC 21.01
PHP 7.4.16
MySQL 10.0.38
Apache 2.4.18
Ubuntu 16.04.7 LTS
