### ISSUE TITLE
Bug discovered when changing username - previous username still accessible.

### ISSUE THREAD

**Issue by crispywisp** [nextcloud/server#25812]
Hi!

Ok, I think I've finally found where I can report this issue I recently discovered.

I'm not sure if this is already a known issue -- so if you change the login name or username of a user, the user can still access their account using the previous username account. Let's say the user's account is "user@yahoo.com". If the user updates it to "user@gmail.com", the user can still access the account using the "user@yahoo.com" -- as well as the "user@gmail.com". The user can access the account using two logins.

Also after updating a username to a new one (user@gmail.com), creating a new app password still reflects the previous username (user@yahoo.com) -- and there's no way of updating this username.

The only way I could prevent the user from accessing the account using the old username is by deleting the entire account and creating a new account with the new username.

I hope this info can be useful for you.

Thanks.

**Comment by j-ed** [comment]
Can you please provide PRECISE information about the used Nextcloud version, how you've tested it (using a web browser and app etc.) and provide a DETAILED step-by-step description how the problem can be reproduced.

**Comment by crispywisp** [comment]
Hi. Yes. Sorry about the lack of detail.

I discovered this on Nextcloud 20. But I'm testing it now on Nextcloud 21 after upgrading, and it still exists.

I have the Registration app installed on Nextcloud. And I do have the "force user to use e-mail as username" enabled in the settings.

To reproduce this bug:
1. Create a new account by registering an e-mail, and completing the process.
2. Login to the newly created account.
3. Go to Settings and change the e-mail address in the Personal Info tab.
4. Log out, and login using the previous e-mail address --> this will STILL work.
5. NOW, log out, and login using the new e-mail address --> this will also work.
6. Another thing. Go to Settings, and then go to the Security tab.
7. Scroll down to the Devices & Sessions, and create an app password.
8. The "username" is preset to the previous e-mail address, and you can't edit this even after changing your username (new e-mail).

The current version of Nextcloud I tested this on is: 21.0.0
OS I'm using to test this is: Windows 10 ver. 10.0.19042.804.
Browser I'm using is: Vivaldi ver. 3.6.2165.40 (64-bit).

**Comment by skjnldsv** [comment]
cc @MorrisJobke @rullzer @blizzz

**Comment by blizzz** [comment]
> so if you change the login name or username of a user

There is no support for changing the user id. What did you do?

**Comment by blizzz** [comment]
> The "username" is preset to the previous e-mail address, and you can't edit this even after changing your username (new e-mail).

The user id is immutable, and for local user also acts as login name (case-insensitive).
