### ISSUE TITLE
Chunked uploading not working in nextcloud:latest docker image

### ISSUE THREAD

**Issue by ncw** [nextcloud/server#25829]
I'm trying to make chunked uploading work using the `nextcloud:latest` docker image.

This is so I can add a [chunked upload feature to rclone](https://github.com/rclone/rclone/pull/4865) and have it tested in the integration tests.

I'm pulling my hair out though, I just can't get it to work.

I wrote two small scripts so anyone should be able to reproduce this - first start the container

```sh
#!/bin/bash

set -e

NAME=nextcloud-test
USER=rclone
PASS=ArmorAbleMale6

docker run --rm -d --name $NAME \
       -e "SQLITE_DATABASE=nextcloud.db" \
       -e "NEXTCLOUD_ADMIN_USER=rclone" \
       -e "NEXTCLOUD_ADMIN_PASSWORD=$PASS" \
       -e "NEXTCLOUD_TRUSTED_DOMAINS=*.*.*.*" \
       -p 127.0.0.1:3080:80 \
       nextcloud:latest
```

Now do the chunked upload. This is lifted almost straight from [the docs](https://docs.nextcloud.com/server/20/developer_manual/client_apis/WebDAV/chunking.html):

```sh
#!/bin/bash

truncate -s 10M chunk1
truncate -s 15728639 chunk2

AUTH='-u rclone:ArmorAbleMale6'
SERVER='http://127.0.0.1:3080/remote.php/webdav'

echo "mkdir"
curl -X MKCOL $AUTH ${SERVER}/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0

echo "chunk1"
curl -X PUT $AUTH ${SERVER}/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/000000000000000-000000010485759 -d @chunk1

echo "chunk2"
curl -X PUT $AUTH ${SERVER}/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/000000010485760-000000015728640 -d @chunk2

echo "assemble"
curl -X MOVE $AUTH --header "Destination:${SERVER}/file.zip" ${SERVER}/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/.file

echo "delete"
curl -X DELETE $AUTH ${SERVER}/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/
```

Running that script gives the output

```
$ ./test-chunked.sh
mkdir
chunk1
chunk2
assemble
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/.file could not be located</s:message>
</d:error>
delete
```

Indicating that the assemble failed.

The same thing happens when I try the new rclone code - the `.file` is not found.

Any ideas?

Is this a bug in the Docker image or maybe the chunked upload docs?

Apologies in advance if this is a config error by me.

**Comment by kesselb** [comment]
Hi, cool to have support for chunks in rclone :tada: 

```
#!/bin/bash

truncate -s 10M chunk1
truncate -s 15728639 chunk2

AUTH='-u rclone:ArmorAbleMale6'
SERVER='http://127.0.0.1:3080/remote.php/dav'

echo "mkdir"
curl -X MKCOL $AUTH ${SERVER}/uploads/rclone/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0

echo "chunk1"
curl -X PUT $AUTH ${SERVER}/uploads/rclone/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/000000000000000-000000010485759 -d @chunk1

echo "chunk2"
curl -X PUT $AUTH ${SERVER}/uploads/rclone/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/000000010485760-000000015728640 -d @chunk2

echo "assemble"
curl -X MOVE $AUTH --header "Destination:${SERVER}/files/rclone/file.zip" ${SERVER}/uploads/rclone/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/.file

echo "delete"
#curl -X DELETE $AUTH ${SERVER}/uploads/rclone/myapp-e1663913-4423-4efe-a9cd-26e7beeca3c0/
```

If assembled it's not possible to delete the chunks. The use case for delete is that a user cancels the upload and to do clean up.

**Comment by ncw** [comment]
> Hi, cool to have support for chunks in rclone

:-)

> If assembled it's not possible to delete the chunks. The use case for delete is that a user cancels the upload and to do clean up.

It never gets assembled though because the `curl -X MOVE` returns an error :-(

**Comment by kesselb** [comment]
https://github.com/nextcloud/server/issues/25829#issuecomment-787186861 is the fixed version of your script. The url's were missing uploads/$userId an files/$userId.

**Comment by ncw** [comment]
> [#25829 (comment)](https://github.com/nextcloud/server/issues/25829#issuecomment-787186861) is the fixed version of your script. The url's were missing uploads/$userId an files/$userId. Sorry for not making that more clear in my post

Thank you - I missed that!

I can see I missed the same thing in the docs too.

I note 3 things I missed!
- you are using the `/dav` endpoint not the `/webdav` endpoint
- you are using `/files/rclone/`
- you are using `/uploads/rclone`

The users configure the URL as the `/webdav` endpoint - can I do this multipart file assembly via the `/webdav` endpoint?

If I can't then I'll have to either ask for a new config option or munge the `/dav` URL from the `/webdav` URL.

Thank you for your help :-)

**Comment by kesselb** [comment]
You are welcome. Afaik /dev is the endpoint for all dav operations (https://docs.nextcloud.com/server/20/developer_manual/client_apis/WebDAV/basic.html). I don't know why we have this /webdav endpoint :man_shrugging:

**Comment by PVince81** [comment]
"/webdav" is legacy, please don't base any future work on this

**Comment by ncw** [comment]
I think `/webdav` is what has been in previous versions. From rclone's point of view it is great because it just points to the user's files which is all rclone is interested in.

Hower I looked at the settings in the latest version and it does indeed recommend `/dav/files/USER` as the endpoint to use with webdav.

If all I have is `/dav/files/USER` is it safe to make up the upload endpoint by replacing the `/files/` with `/upload/`?

Or is there a better way of working out these endpoints?

Thanks

**Comment by PVince81** [comment]
Note: as far as I remember the "uploads" endpoint (aka chunked upload ng) only works with "/dav/files/USER". So you might not be able to MOVE an assembled file from the "/dav/uploads/USER" to "/webdav".

> If all I have is /dav/files/USER is it safe to make up the upload endpoint by replacing the /files/ with /upload/?

Yes, you should be able to safely replace the base "/dav/files/" with "/dav/uploads/" to get to the uploads base URL.

**Comment by ncw** [comment]
> Note: as far as I remember the "uploads" endpoint (aka chunked upload ng) only works with "/dav/files/USER". So you might not be able to MOVE an assembled file from the "/dav/uploads/USER" to "/webdav".

I did try that, and I couldn't get it to work.

> > If all I have is /dav/files/USER is it safe to make up the upload endpoint by replacing the /files/ with /upload/?
> 
> Yes, you should be able to safely replace the base "/dav/files/" with "/dav/uploads/" to get to the uploads base URL.

Ok I'll do that.

Thank you all for your help.

I'll close this now since we've established the problem was my terrible docs reading skills all along ;-)
