### ISSUE TITLE
Avoid infinite scrolling in viewers

### ISSUE THREAD

**Issue by andrzej-r** [nextcloud/server#25824]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Nextcloud Files (but also Photos) browsing performance is poor, partly because of use of an infinite scrolling in the view. Infinite scrolling requires extra http+database query and reallocation of the view area every time a user reaches the bottom of the page. While it has some uses for content like blogs or search results, where users are likely to be interested only in the top-most results, that is *not* applicable to listings of files or photos where the total number of elements to display is known and users are likely to access them in any order.

In addition to performance issues, infinite scrolling also reduces usability, as users cannot quickly move to the bottom of the page or to an estimated point in the middle of the listing (for example if files are sorted alphabetically).

**Describe the solution you'd like**
I'd like the view to be pre-allocated based on total number of elements to display. This would avoid extra queries and reallocation of the view every page scroll and would work well with the browser scrolling mechanism. 

**Describe alternatives you've considered**
Leaving the current design as is.

**Additional context**
This reference https://medium.com/google-design/google-photos-45b714dfbed1 may be useful.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
