### ISSUE TITLE
Weird and constant logs

### ISSUE THREAD

**Issue by dotlineX** [nextcloud/server#25827]
First off, I have asked this question on the nextcloud community but got no answer

I have a raspberrypi running nextcloud 20.0.4 and I have my logs getting constantly spammed with 
`Storage wrapper 'sharepermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.`
I have looked it up but couldn't find a good solution. Can anyone help?

**Comment by kesselb** [comment]
Issue template missing => needs info

**Comment by dotlineX** [comment]
My excuses

### Steps to reproduce
Installed nextcloud from nextcloudpi
???


### Expected behaviour
No logs

### Actual behaviour
Lots of logs


## Server configuration detail

**Operating system:** Linux 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l

**Webserver:** Apache (fpm-fcgi)

**Database:** mysql 10.3.27

**PHP version:** 

7.3.27-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, sodium, session, standard, cgi-fcgi, mysqlnd, PDO, xml, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, igbinary, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_sqlite, Phar, posix, readline, redis, shmop, SimpleXML, smbclient, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, libsmbclient, Zend OPcache

**Nextcloud version:** 20.0.8 - 20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - announcementcenter: 4.0.1
 - audioplayer_sonos: 1.2.0
 - breezedark: 20.0.7
 - calendar: 2.1.3
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_pdfviewer: 2.0.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - firstrunwizard: 2.9.0
 - geoblocker: 0.4.6
 - groupfolders: 8.2.0
 - integration_google: 0.1.10
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - mail: 1.8.3
 - music: 1.0.2
 - nextcloud_announcements: 1.9.0
 - nextcloudpi: 0.0.1
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - password_policy: 1.10.1
 - photos: 1.2.3
 - previewgenerator: 3.1.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - recommendations: 0.8.0
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - sharepermissions: 1.0.1
 - spreed: 10.0.6
 - support: 1.3.0
 - survey_client: 1.8.0
 - systemtags: 1.10.0
 - text: 3.1.0
 - theming: 1.11.0
 - twofactor_backupcodes: 1.9.0
 - twofactor_totp: 5.0.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - workflowengine: 2.2.0
Disabled:
 - encryption
 - files_external
 - user_ldap

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "trusted_domains": {
        -redacted-
    },
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.8.1",
    "overwrite.cli.url": "https:\/\/schepers.ignorelist.com\/",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbport": "",
    "dbtableprefix": "oc_",
    "mysql.utf8mb4": true,
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "installed": true,
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "memcache.local": "\\OC\\Memcache\\Redis",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 0,
        "timeout": 0,
        "password": "***REMOVED SENSITIVE VALUE***"
    },
    "tempdirectory": "\/media\/myCloudDrive\/ncdata\/tmp",
    "mail_smtpmode": "smtp",
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "maintenance": false,
    "logfile": "\/media\/myCloudDrive\/ncdata\/nextcloud.log",
    "loglevel": "2",
    "log_type": "file",
    "mail_sendmailmode": "pipe",
    "htaccess.RewriteBase": "\/",
    "mail_smtpsecure": "tls",
    "mail_smtpauthtype": "LOGIN",
    "mail_smtpauth": 1,
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 
No
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (Linux; Android 10) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.182 Mobile Safari/537.36

**Operating system:** 
Debian
## Logs

<details><summary>Web server error log</summary>

```
Empty
```
</details>

<details><summary>Nextcloud log</summary>

```
{"reqId":"YDzVPBzHSYsd2XtiDrBzDQAAAA0","level":2,"time":"2021-03-01T11:51:24+00:00","remoteAddr":"192.168.0.1","user":"luna","app":"filesystem","method":"PROPFIND","url":"/remote.php/dav/files/-redacted-/","message":"Storage wrapper 'sharepermissions' was not registered via the 'OC_Filesystem - preSetup' hook which could cause potential problems.","userAgent":"Mozilla/5.0 (Windows) mirall/3.1.3stable-Win64 (build 20210218) (Nextcloud)","version":"20.0.8.1"}
```
</details>

<details><summary>Browser log</summary>


</details>

**Comment by nsturtz** [comment]
I have the same issue

**Comment by nsturtz** [comment]
I am using Nextcloud 21

**Comment by kesselb** [comment]
@nsturtz next time use GitHub reactions. "I have the same issue" does not add any value to a bug report. 

The warning is most likely caused by https://apps.nextcloud.com/apps/sharepermissions.

The app does register a storage wrapper in a deprecated way. Please report to issue at https://github.com/rullzer/sharepermissions/issues.
