### ISSUE TITLE
NC21 occ does not start

### ISSUE THREAD

**Issue by CWBudde** [nextcloud/server#25822]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. start from command-line sudo -u www-data php occ 

### Expected behaviour
occ should start, probably listing all available commands or show an error message. Anything

### Actual behaviour
It does nothing except to show a blinking cursor in the very next line

### Server configuration

**Operating system:**
Ubuntu 20.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
PHP 7.4.3

**Nextcloud version:** (see Nextcloud admin page)
21

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.08

**Where did you install Nextcloud from:**
Website / Online Updater

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>List of activated apps</summary>

```
Accessibility
Activity
Analytics
Antivirus for files
Audio Player
Auditing / Logging
Calendar
Collaborative tags
Comments
Contacts
Contacts Interaction
Custom CSS
Dashboard
Deleted files
Federation
File sharing
First run wizard
Log Reader
Mail
Markdown Editor
Monitoring
Nextcloud announcements
Notifications
Password policy
Passwords
PDF viewer
Photos
Polls
Privacy
Recommendations
Right click
Share by mail
Support
Talk
Tasks
Text
Theming
Two-Factor U2F
Update notification
Usage survey
User status
Versions
Video player
Weather status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
<?php
$CONFIG = array (
  'instanceid' => '***',
  'passwordsalt' => '***',
  'secret' => '***',
  'trusted_domains' => 
  array (
    0 => '***,
    1 => '***',
    2 => '***',
  ),
  'datadirectory' => '/var/www/cloud/data',
  'dbtype' => 'mysql',
  'version' => '21.0.0.18',
  'overwrite.cli.url' => '***',
  'dbname' => 'nextcloud',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'nextcloud_user',
  'dbpassword' => '***',
  'installed' => true,
  'maintenance' => false,
  'theme' => '',
  'loglevel' => 1,
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'mail_smtpmode' => 'smtp',
  'mail_smtpsecure' => 'tls',
  'mail_sendmailmode' => 'smtp',
  'mail_from_address' => '***',
  'mail_domain' => '***',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtphost' => '***',
  'mail_smtpport' => '587',
  'mail_smtpname' => '***',
  'mail_smtppassword' => '***',
  'default_phone_region' => 'DE',
  'updater.release.channel' => 'beta',
);
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
--> nothing related above
{"reqId":"MwlCbGxxvC8sINOiir5e","level":1,"time":"2021-02-27T02:21:27+00:00","remoteAddr":"91.3.118.74","user":"Admin","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_PRIMARY_KEYS: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"21.0.0.18"}
{"reqId":"MwlCbGxxvC8sINOiir5e","level":1,"time":"2021-02-27T02:21:29+00:00","remoteAddr":"91.3.118.74","user":"Admin","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_INDEXES: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"21.0.0.18"}
{"reqId":"MwlCbGxxvC8sINOiir5e","level":1,"time":"2021-02-27T02:21:30+00:00","remoteAddr":"91.3.118.74","user":"Admin","app":"no app in context","method":"GET","url":"/index.php/settings/ajax/checksetup","message":"Deprecated event type for OCP\\IDBConnection::CHECK_MISSING_COLUMNS: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:85.0) Gecko/20100101 Firefox/85.0","version":"21.0.0.18"}
```
</details>

Some debugging showed that it does enter:

    $hookConnector = $this->get(HookConnector::class);

in the function boot() in Server.php

but it never returns.

**Comment by CWBudde** [comment]
I forgot to mention: Running occweb seems to work :-/

**Comment by CWBudde** [comment]
For some reason it works now. Haven't done anything lately except installing xdebug. Maybe it cleared some cache?!?

**Comment by much-doge** [comment]
I have the same issue with the cli when attempting upgrade from 20 to 21

running any occ command results in this message

```
server:/var/www/nextcloud# sudo -u www-data php occ 
Terminated
```
I'm using php7.4

**Comment by s644** [comment]
Maybe have a look here https://github.com/nextcloud/server/issues/25742

**Comment by much-doge** [comment]
@CWBudde I've found the solution. Enabling apc on php cli fix the problem. This is indeed issue #25742 

> I confirm that adding apc.enable_cli=1 into /etc/php/7.4/mods-available/apcu.ini on my Debian/testing solved this issue.

https://github.com/nextcloud/server/issues/25742#issuecomment-784076813

**Comment by CWBudde** [comment]
I can confirm that I have the APCu cache running and maybe installing xdebug cleared the cache as I did not needed to add apc.enable_cli=1 to make it work in the end. However, I have done this now, just to make sure that it will keep working.

**Comment by CWBudde** [comment]
I just wondered about the missing (or unclear) error message. Maybe it would be good to add a better error in this case?

**Comment by nickvergessen** [comment]
The resolution of #25742 will make a clear error message
