### ISSUE TITLE
add support for 'prefers-color-scheme' for dark mode / light mode browser preference detection

### ISSUE THREAD

**Issue by foss-** [nextcloud/server#25823]
Nextcloud supports dark and light mode in User > Settings > Accessibility.

1. This is a bit unexpected as dark / light mode is not really an accessibility feature and in most software found under design or general settings.
2. Discoverability is not great. I am using dark mode on macOS which results in Firefox following that system preference (as expected). As Firefox supports `prefers-color-scheme` I would expect NextCloud to pick up on that and follow the user preference.

This would result in a UI which integrates nicely with the rest of the system the user is using. Fairly low hanging fruit with nice impact.

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/12276
