### ISSUE TITLE
Can't write into config directory! This can usually be fixed by giving the webserver write access to the config directory.

### ISSUE THREAD

**Issue by perfect7gentleman** [nextcloud/server#2583]
### Server configuration
**Operating system**:
Gentoo
**Web server:**
Nginx
**Database:**
MariaDB
**PHP version:**
7.1
**Nextcloud version:** (see Nextcloud admin page)
11 RC1
**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install or update from 10.0.1, it doesn't matter
**Where did you install Nextcloud from:**
from ebuild

**Comment by LukasReschke** [comment]
Please check the permissions of the config folder and post a `ls -lah` result. Also we don't officially support the ebuild.

**Comment by perfect7gentleman** [comment]
` $ ls -lah config/
total 52K
drwxrwxr-x  2 nginx nginx   66 Dec  9 17:17 .
drwxr-xr-x 15 nginx nginx 4.0K Dec  9 17:15 ..
-rw-r--r--  1 nginx nginx    0 Dec  9 17:17 config.php
-rw-rw-r--  1 nginx nginx  41K Dec  9 17:15 config.sample.php
-rw-rw-r--  1 nginx nginx  225 Dec  9 17:15 .htaccess`

**Comment by MorrisJobke** [comment]
@perfect7gentleman As the config.php is empty: simply delete it. Then run the setup via web browser and everything should work, because the folder has the correct permissions.

Please ask for help in the forums: https://help.nextcloud.com/ because this is not a bug in the software itself with with the setup process of this package.

Thanks :)

**Comment by perfect7gentleman** [comment]
it didn't help

> Can't write into config directory! This can usually be fixed by giving the webserver write access to the config directory.
```
$ ls -lah
total 52K
drwxrwxr-x  2 nginx nginx   48 Dec  9 21:37 .
drwxr-xr-x 15 nginx nginx 4.0K Dec  9 17:15 ..
-rw-rw-r--  1 nginx nginx  41K Dec  9 17:15 config.sample.php
-rw-rw-r--  1 nginx nginx  225 Dec  9 17:15 .htaccess

**Comment by MorrisJobke** [comment]
@perfect7gentleman What is the user the webserver is running with?

**Comment by perfect7gentleman** [comment]
nginx.
Everything worked before that update to php_7.1. I've updated packages to php_7.1 and nextcloud_10.0.1 said that it doesn't support php_7.1, and i updated nexcloud to 11rc1 manually as before i migrated from owncloud to nextcloud.

**Comment by MorrisJobke** [comment]
@LukasReschke Haven't you said, that you tested the PHP 7.1? Could it be caused by a tiny change in PHP 7.1 APIs?

**Comment by perfect7gentleman** [comment]
sorry, my fault, i've forgotten to modify setting for php_7.1

**Comment by EddieOne** [comment]
You are the worst @perfect7gentleman

**Comment by ShapeShifter499** [comment]
> sorry, my fault, i've forgotten to modify setting for php_7.1

What exactly did you do here?
