### ISSUE TITLE
Blank page in files app after upgrade from NC20 to NC21

### ISSUE THREAD

**Issue by v1r0x** [nextcloud/server#25830]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Update from 20.0.x to 21.0.0
2. Open files app

### Expected behaviour
Files app content should be visible

### Actual behaviour
Only the sidebar on the left is loaded, nothing else (no files, not even the + icon the create new files/folders)
Syncing works find

### Server configuration

**Operating system:**
Linux

**Web server:**
Apache

**Database:**
MySQL/MariaDB 10.5

**PHP version:**
7.4.15

**Nextcloud version:** (see Nextcloud admin page)
21.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.x (Docker)

**Where did you install Nextcloud from:**
Docker (nextcloud:apache extended with cron support)

**Signing status:**
<details>
<summary>Signing status</summary>
No errors have been found.
</details>

**List of activated apps:**
<details>
<summary>App list</summary>
  - accessibility: 1.7.0
  - activity: 2.14.3
  - admin_audit: 1.11.0
  - announcementcenter: 5.0.0
  - audioplayer: 3.1.0
  - calendar: 2.1.3
  - cloud_federation_api: 1.4.0
  - comments: 1.11.0
  - contacts: 3.4.3
  - contactsinteraction: 1.2.0
  - dashboard: 7.1.0
  - dav: 1.17.1
  - deck: 1.3.0
  - federatedfilesharing: 1.11.0
  - federation: 1.11.0
  - files: 1.16.0
  - files_external: 1.12.0
  - files_pdfviewer: 2.1.0
  - files_rightclick: 1.0.0
  - files_sharing: 1.13.1
  - files_trashbin: 1.11.0
  - files_versions: 1.14.0
  - files_videoplayer: 1.10.0
  - firstrunwizard: 2.10.0
  - integration_github: 0.0.20
  - integration_whiteboard: 0.0.14
  - logreader: 2.6.0
  - lookup_server_connector: 1.9.0
  - mail: 1.8.3
  - news: 15.3.2
  - nextcloud_announcements: 1.10.0
  - notes: 4.0.2
  - notifications: 2.9.0
  - oauth2: 1.9.0
  - password_policy: 1.11.0
  - passwords: 2021.2.0
  - photos: 1.3.0
  - polls: 1.7.5
  - privacy: 1.5.0
  - provisioning_api: 1.11.0
  - recommendations: 1.0.0
  - richdocuments: 4.0.1
  - riotchat: 0.7.2
  - serverinfo: 1.11.0
  - settings: 1.3.0
  - sharebymail: 1.11.0
  - social: 0.4.2
  - spreed: 11.0.0
  - support: 1.4.0
  - survey_client: 1.9.0
  - systemtags: 1.11.0
  - tasks: 0.13.6
  - text: 3.2.0
  - theming: 1.12.0
  - twofactor_backupcodes: 1.10.0
  - twofactor_nextcloud_notification: 3.1.0
  - twofactor_totp: 6.0.0
  - updatenotification: 1.11.0
  - user_ldap: 1.11.0
  - user_status: 1.1.1
  - viewer: 1.5.0
  - weather_status: 1.1.0
  - workflowengine: 2.3.0
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***",
        ],
        "version": "21.0.0.18",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "installed": true,
        "updatechecker": false,
        "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
        "enable_previews": true,
        "mail_smtpmode": "php",
        "loglevel": 0,
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "ldapIgnoreNamingRules": false,
        "app.mail.imaplog.enabled": true,
        "trashbin_retention_obligation": "auto",
        "ldapProviderFactory": "\\OCA\\User_LDAP\\LDAPProviderFactory",
        "updater.release.channel": "stable",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "overwriteprotocol": "https",
        "mysql.utf8mb4": true,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "default_phone_region": "DE"
    }
}

</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** LDAP

### Client configuration
**Browser:** Firefox & Chromium (latest)

**Operating system:**
Windows 10 & Ubuntu LTS

#### Web server error log
<details>
<summary>Web server error log</summary>
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
Debug | files_sharing | /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead. -- | -- | --

Debug | files_external | /appinfo/app.php is deprecated, use \OCP\AppFramework\Bootstrap\IBootstrap on the application class instead. -- | -- | --

Debug | scss_cacher | SCSSCacher::process ordinary check follows -- | -- | --

</details>

#### Browser log
<details>
<summary>Browser log</summary>
23:36:59.337 Uncaught TypeError: OCA.Files is undefined
    <anonymous> systemtagsfilelist.js:23
    Webpack 5
systemtagsfilelist.js:23:7
23:36:59.342
Uncaught TypeError: OCA.Files is undefined
    <anonymous> versionstabview.js:18
    Webpack 3
versionstabview.js:18:7
23:36:59.390
Uncaught TypeError: OCA.Files is undefined
    343 sharedfilelist.js:28
    Webpack 5
sharedfilelist.js:28:5
23:36:59.682 Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf eval blockiert ("script-src"). global.js:10:10
23:37:00.187
Uncaught TypeError: OCA.Files.DetailTabView is undefined
    <anonymous> https://example.tld/js/activity/activity-sidebar.js?v=d52dedd8-2:603
    <anonymous> https://example.tld/js/activity/activity-sidebar.js?v=d52dedd8-2:803
activity-sidebar.js:603:24
23:37:01.032
Uncaught TypeError: OCA.Files.FileList is undefined
    <anonymous> https://example.tld/apps/files_external/js/mountsfilelist.js?v=d52dedd8-2:29
    <anonymous> https://example.tld/apps/files_external/js/mountsfilelist.js?v=d52dedd8-2:149
mountsfilelist.js:29:2
23:37:01.033
Uncaught TypeError: OCA.Files.FileList is undefined
    <anonymous> filelist.js:47
    <anonymous> filelist.js:11
    Webpack 5
filelist.js:47:1
23:37:01.317
Please do NOT wait for the DOMContentLoaded before registering your viewer handler Viewer.vue:235
23:37:01.319
The following mime is already registered text/csv 
Object { id: Getter & Setter, group: Getter & Setter, mimes: Getter & Setter, component: Getter & Setter, … }
Viewer.vue:529
23:37:01.335
Unable to register vcf import action files-action.js:43:9
23:37:01.358
Please do NOT wait for the DOMContentLoaded before registering your viewer handler
</details>

**Comment by dmt0** [comment]
Only seeing this in Firefox, works fine in Chrome.
cloudamo
macOS

**Comment by v1r0x** [comment]
I get this in both Firefox and Chromium

**Comment by rostwald** [comment]
We have the same issue on all windows (7 & 10) clients with firefox(-esr), chrome and edge for Files and Talk. Only the header menu is shown but the rest of the site stays blank.

FreeBSD with Firefox-esr works fine.

Nextcloud 21.0.1
Talk  11.2.1 (problem was already present with at least the last two 10.x Versions)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by rostwald** [comment]
We still have some users (i.e. all users created before the update except the initial admin user) which only get a blank page after login instead of the file manager.
Logging in with another user from the same Client/Browser works, logging in with one of the faulty accounts from other Clients shows the same problem.

Users created after the upgrade (or better say first login after the upgrade, as we're using SASL), don't have this problem.
Even deleting the user and its directory to have it re-created at the next login doesn't work, so it seems there still is some (broken) user-data left after deletion...

**Comment by szaimen** [comment]
Do other apps work for said users? Can you please provide the Nextcloud log and especially the browser log for said users? Thank you!

**Comment by rostwald** [comment]
Sure! I hope to find some time tomorrow to gather some logs and narrow down the affected apps (IIRC it was the filemanager and talk).

**Comment by pledou** [comment]
Hello, I've the same issue with firefox, edge but not vivaldi(chromium based browser) and nextcloud 24.0.2.
