### ISSUE TITLE
Upgrade from 20.0.7 to 21.0.0 failed due to extra files in user_ldap

### ISSUE THREAD

**Issue by lambda-a** [nextcloud/server#25831]
Had to manually delete 

(_path removed_)/apps/user_ldap/appinfo/install.php
(_path removed_)/apps/user_ldap/appinfo/register_command.php

(File date: Feb  7 13:16 install.php) before upgrade was successful.

Tried on another server to first disable the user_ldap app by running
`sudo -u www-data php occ app:disable user_ldap`
before upgrade, but this did not help. Same issue, only the manual removal of the files specified  above helped. 

Error messages as reported by OCC
`Too few arguments to function OCA\User_LDAP\Helper::__construct(), 1 passed in (_path removed_)/apps/user_ldap/appinfo/install.php`

Hopefully this helps others with similar issue.

**Comment by skjnldsv** [comment]
cc @blizzz @juliushaertl

**Comment by blizzz** [comment]
> (path removed)/apps/user_ldap/appinfo/install.php
> (path removed)/apps/user_ldap/appinfo/register_command.php

The release does not contain these files:

![Screenshot_20210322_095928](https://user-images.githubusercontent.com/2184312/111964805-4be74380-8af5-11eb-9ca2-8702218a10db.png)

this points at the upgrade done incorrectly. Please check out https://docs.nextcloud.com/server/20/admin_manual/maintenance/upgrade.html
