### ISSUE TITLE
List apps compatibility with all NC versions in Apps GUI (Admin)

### ISSUE THREAD

**Issue by archont00** [nextcloud/server#25832]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
Before upgrade of NC server, I have to manually check installed apps one by one in App Store to see if they are already released for the new NC version.
This task is even more complicated because the built-in apps are not available in App Store - however, it is not possible to find out which apps are built-in (e.g. Deleted Files) and which are extra (e.g. Full text search - Elasticsearch Platform).

**Describe the solution you'd like**
In `https://.../settings/apps`, I would like to be able to choose a particular server version (including higher released versions) and see which of my installed apps do not officially support it (yet) or support is "unknown".

**Alternative solution**
In `https://.../settings/apps`, I would like to see a list of supported NC server versions for each app - e.g. in the sidebar "details" for the app.

**Comment by fa-ribeiro** [comment]
Also would be great to be able to filter apps list and search results to show only compatible versions with current NC version. TIA!

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
