### ISSUE TITLE
make items in "Security > Devices&Sessions" deleteable via selector or clearall

### ISSUE THREAD

**Issue by trueshanti** [nextcloud/server#25864]
**Is your feature request related to a problem? Please describe.**
not really - just a pain to delete devicesessionlists with a houndred items

**Describe the solution you'd like**
i would like to see a way to multiselect items from session-list to delete ( select all / reverse selection / select none )
 
**Describe alternatives you've considered**
a "clear all" botton ?

Thank you for this gorgeous tool !!
br

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/11655
