### ISSUE TITLE
Use only remote.php/dav instead of remote.php/webdav

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#25867]
- [x] Android @tobiasKaminsky https://github.com/nextcloud/android/issues/8705
- [x] Desktop @nextcloud/desktop 
- [x] iOS @marinofaggiana 

As title says: With NC23 only use remote.php/dav.

@nextcloud/server-triage can we log this for NC22 so that we see which clients are using this?
This is good for all other 3rd party clients.

**Comment by tobiasKaminsky** [comment]
@Ivansss do you use also old remote.php/webdav endpoints?

**Comment by Ivansss** [comment]
In Talk iOS app we use `remote.php/dav` but we also use the [communication library](https://github.com/nextcloud/ios-communication-library).
@marinofaggiana Do you use `remote.php/webdav` somewhere in the communication lib?

**Comment by marinofaggiana** [comment]
I use the webdav for the PROPFIND.
The remote.php/dav for PROPFIND is compatible from which  version of NC ?

**Comment by tobiasKaminsky** [comment]
remote.php/dav exists since a very long time, at least for all our supported server versions (which is currently NC16).

**Comment by marinofaggiana** [comment]
@Ivansss NCCommunication lib >= 0.99.3

**Comment by tobiasKaminsky** [comment]
All done 💪💪💪

**Comment by dkocher** [comment]
We offer [connection profiles](https://cyberduck.io/nextcloud/) that default to use `/remote.php/webdav/`. Having a dynamic URI with username is problematic in particular for larger enterprise deployments. Can you clarify if this existing (deprecated?) endpoint is to be removed in a future version and only `/remote.php/dav/files` is available?

**Comment by tobiasKaminsky** [comment]
This is currently only removed on client side.

@skjnldsv for server plans ^

**Comment by slu-010101** [comment]
> We offer [connection profiles](https://cyberduck.io/nextcloud/) that default to use `/remote.php/webdav/`. Having a dynamic URI with username is problematic in particular for larger enterprise deployments. Can you clarify if this existing (deprecated?) endpoint is to be removed in a future version and only `/remote.php/dav/files` is available?

Same here, we use pam_mount and need a static URL without username.
Is /remote.php/webdav/ still possible with new versions?
