### ISSUE TITLE
OCA\Activity\BackgroundJob\EmailNotification: The given timestamp is invalid

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#2586]
Appeared at December 9th 2016, 13:15:02.000

> Error while running background job (class: OCA\Activity\BackgroundJob\EmailNotification, arguments: ): {"Exception":"InvalidArgumentException","Message":"The given timestamp is invalid","Code":0,"Trace":"#0 \/var\/www\/html\/apps\/activity\/lib\/MailQueueHandler.php(242): OC\\Activity\\Event->setTimestamp('1479379826')\n#1 \/var\/www\/html\/apps\/activity\/lib\/BackgroundJob\/EmailNotification.php(123): OCA\\Activity\\MailQueueHandler->sendEmailToUser('lukas', 'lukas@nextcloud...', 'en', 'Europe\/Berlin', 1481285701)\n#2 \/var\/www\/html\/apps\/activity\/lib\/BackgroundJob\/EmailNotification.php(81): OCA\\Activity\\BackgroundJob\\EmailNotification->runStep(500, 1481285701)\n#3 \/var\/www\/html\/lib\/private\/BackgroundJob\/Job.php(53): OCA\\Activity\\BackgroundJob\\EmailNotification->run(NULL)\n#4 \/var\/www\/html\/lib\/private\/BackgroundJob\/TimedJob.php(54): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#5 \/var\/www\/html\/cron.php(121): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 {main}","File":"\/var\/www\/html\/lib\/private\/Activity\/Event.php","Line":188}

cc @nickvergessen

**Comment by LukasReschke** [comment]
I do see these multiples times in the logs and all to me as recipient.

**Comment by nickvergessen** [comment]
> setTimestamp('1479379826')

should be
> setTimestamp(1479379826)

will have a look, but sounds familiar

**Comment by LukasReschke** [comment]
Log from @icewind1991's clonecloud which somehow is still in our logging manager… 🙈 

@MorrisJobke Can we remove them?

**Comment by nickvergessen** [comment]
Was fixed 14 days ago: https://github.com/nextcloud/activity/pull/80/files
