### ISSUE TITLE
Upgrade from 20.0.8 to 21.0.0

### ISSUE THREAD

**Issue by mprofi** [nextcloud/server#25888]
OC\DB\Exceptions\DbalException: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

OC\DB\Exceptions\DbalException: Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

**Comment by acsfer** [comment]
Duplicate of #25748
