### ISSUE TITLE
Collabora share from Public Link

### ISSUE THREAD

**Issue by clement850** [nextcloud/server#25906]
Hello, 

I have a Nextcloud instance with Collabora and OnlyOffice. When i want to edit `docx` file, it opens with OnlyOffice (that's what we want).

But if I want to share it via public link, the external user can modify with Collabora (and not OnlyOffice), therefore the collaboration isn't possible.

Is it possible to set default editor for public users in terms of file formats?

Is that a bug? Or a conflict between OnlyOffice and Collabora?

Many thanks

**Comment by szaimen** [comment]
Please install either OnlyOffice or Collabora which will fix this issue. Thanks!
