### ISSUE TITLE
Version 21 Upgrade Error 

### ISSUE THREAD

**Issue by NextFreak** [nextcloud/server#25907]
When starting the Updater, it says:
OC\DB\Exceptions\DbalException: Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027
Platform may not support it.

**Comment by NextFreak** [comment]
Her is the detailled message:

Update vorbereiten

Log-Level auf "debug" gesetzt

Wartungsmodus eingeschaltet

Reparaturschritt: Repair MySQL collation

Reparaturinformation: All tables already have the correct collation -> nothing to do

Reparaturschritt: Repair SQLite autoincrement

Reparaturschritt: Copy data from accounts table when migrating from ownCloud

OC\DB\Exceptions\DbalException: Unknown database type enum requested, Doctrine\DBAL\Platforms\MariaDb1027Platform may not support it.

**Comment by kesselb** [comment]
Duplicate of https://github.com/nextcloud/server/issues/25748
