### ISSUE TITLE
Flow: define time conditions (Feature Request)

### ISSUE THREAD

**Issue by Spartachetto** [nextcloud/server#25914]
I think it would be really useful to have the possibility to define time interval conditions for Flow.

Here are some examples of what I mean:
- send a talk message to every attendee **5 minutes before the scheduled talk**
- put a task "write the minutes" in my task list **2 working days after every meeting with title like "Astronomy club"** 

This would require the possibility to define a time interval either from a time the user inserted (e.g.: an event in a calendar) or the time of some action in nextcloud (e.g.: five minutes after the file was saved)

**Comment by skjnldsv** [comment]
cc @juliushaertl @blizzz

**Comment by juliushaertl** [comment]
I agree that this would be a nice enhancement. However such a time check would depend on the entity itself (e.g. start time of a scheduled talk conversation or due date of the task) so this is nothing that generally applies to all flow rules and would need to be implemented by the apps that provide those entities. So this would be something to file in the individual app issue trackers.

**Comment by Spartachetto** [comment]
juliushaertl first of all thank you for the feedback.

I have to say that I find it a bit counterintuitive. My idea was to have the possibility to define time intervals in relation to an event. It is true that the event can be dependent by an app, yet the functionality of defining time intervals should not. This seems also true because the event could be of the server.

Some simple examples could be:
• send a talk message to self five days after a file was tagged with "urgent" saying This shouldn't be urgent any more!!!

**Comment by juliushaertl** [comment]
Ok for that case it would be the server as the file entity is located there, however we'd need to have separate checks for all date based types there then like:

- creation date
- modification date
- tag date (we don't store that yet, so without extending the systemtagging functionality there is no way to achieve that as of now)

**Comment by Spartachetto** [comment]
@juliushaertl thank you again for considering it!

**Comment by szaimen** [comment]
So @juliushaertl is this feasible?

**Comment by Spartachetto** [comment]
@szaimen wouldn't it be possible to have at least the tag "_nice to have_ "?

I still think that this would be an interesting feature and I hope that @juliushaertl (or others) will clarify its feasibility.

**Comment by Spartachetto** [comment]
@szaimen thank you!
