### ISSUE TITLE
[dashboard] main menu icons hard to see on bright backround

### ISSUE THREAD

**Issue by mokkin** [nextcloud/server#25939]
### Steps to reproduce
1. Use image with bright backround in the upper left corner
2. open dashboard

### Expected behaviour
App colour should adapt to the colour in the backround to get more contrast or simply put the regular top bar in the top like in all other apps.

### Actual behaviour
App Icons are hardly visible in the dashboard (start page) because of the picture in the backround. 

### Server configuration

**Operating system:** Linux

**Web server:** Apache

**Database:** mysql

**PHP version:** 7.4

**Nextcloud version:** 20.0.8

</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here. 
Make sure to remove all sensitive content such as passwords. (e.g. database password, passwordsalt, secret, smtp password, …)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

![grafik](https://user-images.githubusercontent.com/2938748/110019777-21417080-7d29-11eb-8df4-07beb9907eae.png)

**Comment by niziak** [comment]
I can confirm. Background color is set to #FFFFFF.
After upgrade from 20.0.6 to 20.0.8 dashboard icons are white and are completely not visible.  Clicking on "Files" button show files and menu icons are displayed correctly (as black). 
Temporary workaround is to do not use white background.

**Comment by szaimen** [comment]
It was decided to make the app-bar invisible for the dashboard app because it looks much nicer in most situations.
So please fix it yourself by don't using a white background image.
Thanks!

**Comment by DC7IA** [comment]
Please reopen. Not using a white or bright background image does not work if you have to use a bright background image.

There should at least be an option to not have a transparent menu bar.

Please also think about accessibility, not everyone might see as well as you do.
