### ISSUE TITLE
Request checksum of file via endpoint

### ISSUE THREAD

**Issue by tobiasKaminsky** [nextcloud/server#25949]
Coming from https://github.com/nextcloud/android/pull/7894#discussion_r585950545

On Android an user wants to upload a file
- client detects that file with same name already exists
- we do not know if it is the same file
- client requests only for this file via new(?) endpoint a checksum
- client compares it
- only if this differs, it presents conflict resolution dialog

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/11138

**Comment by tobiasKaminsky** [comment]
> Lets track this in #11138

That is different. This one is for "on-demand" checks.
If you want to combine it, then please also c&p this scenario to the other issue.

**Comment by szaimen** [comment]
Done 👍
