### ISSUE TITLE
UX: Placement of application settings shows poor performance with naive users

### ISSUE THREAD

**Issue by marcelklehr** [nextcloud/server#25953]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### UX issue
In the usability study of the bookmarks app I've been conducting, the nextcloud-style application settings in the bottom left corner show really bad performance, being hard to discover for naive users that had never used nextcloud before. Maybe that's something to rethink in the general app design conventions.

**Update:**

Excerpt:
> ![image](https://user-images.githubusercontent.com/986878/123796454-6cd5e680-d8e5-11eb-8ef1-d96f583c9ffc.png)

The particular task may be somehwat unhelpful, as sort order options are not usually found in application settings, but since many participants did not even notice the settings button until made aware of it, I think it warrants further exploration.

**Comment by kesselb** [comment]
cc @jancborchardt

**Comment by szaimen** [comment]
cc @nextcloud/designers what would be a better place for the settings?

**Comment by szaimen** [comment]
Here is an idea where the settings button could be positioned
https://github.com/nextcloud/tasks/issues/1665 (presupposes that the settings are moved into a modal)

**Comment by raimund-schluessler** [comment]
Reading that study, I think it is more about the placement of the sortorder switch in the application settings, than about the application settings itself being at the bottom left.

Having the sort order switch at the bottom left sure is unexpected. But that just means, don't place it in the settings (which happen to be bottom left), and rather show the sort order switch where it is expected (at the top of the list). The general settings can stay where they are imho.

If your task is to set a sort order, you don't look for general settings. So I don't find it so surprising that the users didn't click (or find) the settings button (why would they).

**Comment by marcoambrosini** [comment]
> Here is an idea where the settings button could be positioned

I'm not convinced by it, because normally anything that goes in the app content is related to the active element in the navigation and this would be global app settings. For example in talk we're using that space in the top-bar for the current active conversation's settings. Putting the global app settings does create a bit of confusion in my opinion.

**Comment by marcoambrosini** [comment]
Let's take look at it next Tuesday's design @marcelklehr 
for those who want to join, the call is open and happening at 2pm CEST here https://cloud.nextcloud.com/call/gqff69i8

**Comment by marcelklehr** [comment]
Current proposal is now to have the settings button flow up if there are less menu items in the list than the screen height, and have it sticky on the bottom if the list is full / overflowing. Prerequisite for this is using the settings modal instead of the original expanding settings.
