### ISSUE TITLE
Analytics App Icon visible for all users although App is limited to group

### ISSUE THREAD

**Issue by benks-io** [nextcloud/server#25958]
### Steps to reproduce
1. Install Analytics App
2. Limit to Group
3. Login as user not member of the group

### Expected behaviour
The Icon should not be visible.

### Actual behaviour
Tell us what happens instead

### Server configuration

**Operating system:** Debian Buster

**Web server:** Apache

**Database:** MySQL

**PHP version:** 7.4

**Nextcloud version:** 20.0.8

**Comment by acsfer** [comment]
Duplicate of https://github.com/Rello/analytics/issues/73
