### ISSUE TITLE
Dashboard options

### ISSUE THREAD

**Issue by CWBudde** [nextcloud/server#25952]
**Is your feature request related to a problem? Please describe.**
Yes, if the login screen is (nearly) all white, the icons are invisible in the top bar.

**Describe the solution you'd like**
Have at least one option to set the default dashboard mode for the default (login) image (light / dark)

**Describe alternatives you've considered**
Even better would be a way to also set the default dashboard background image.

**Additional context**
I would like to fix this by myself, but I'm not sure about the steps. Should I fork, patch and create a PR or is there another workflow established? Has there been done anything already in this regards?

**Comment by Lumrenion** [comment]
I have also documented this in the vue-dashboard project with a screenshot:
https://github.com/nextcloud/nextcloud-vue-dashboard/issues/160

I am not sure either if the problem should be solved in PHP or in JS. 
- In `settings/admin/theming`, there could be a switch for dark/light theme added
- Another solution I could imagine is to determine automagically, if the dark or the light theme should be applied, by calculating the brightness of the background:
  https://stackoverflow.com/questions/11867545/change-text-color-based-on-brightness-of-the-covered-background-area

But how is it done on literally all other pages, like files, where the class `inverted` is added to `#appmenu`? I think, the solution should be consistent throughout all nextcloud pages.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.

**Comment by szaimen** [comment]
On a sidenote: you can change the background image with this option:
![image](https://user-images.githubusercontent.com/42591237/123437391-ea40e480-d5cf-11eb-9a96-f1db1675b63d.png)

**Comment by CWBudde** [comment]
If I change the background image there, it will affect other parts as well. However, I've solved it with a local patch. Not the best solution as I have to readd the patch for every update, but I just don't update that often.
