### ISSUE TITLE
Calendar Import: "Create Calendar" option fails.

### ISSUE THREAD

**Issue by charlescurley** [nextcloud/server#2597]
### Steps to reproduce

1. Attempt to import a calendar. "Settings" -> "Import Calendar". Select a calendar file.

2. In the resulting pop-up, select "New Calendar" from the pull-down menu.

3. Click on the check mark.

### Expected behaviour
Tell us what should happen

I expect some sort of further dialog to create the new calendar, similar to the regular creation dialog.

### Actual behaviour
Tell us what happens instead

The pop-up hangs with the message "Import Scheduled".

### Server configuration
**Operating system**:

root@jhegaala:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
root@jhegaala:~# 

**Web server:**

apache2	2.4.10-10+deb8u7

**Database:**

sqlite3:

root@jhegaala:~# pre sqlite
libaprutil1-dbd-sqlite3	1.5.4-1		amd64
libdbd-sqlite3-perl	1.44-1		amd64
libqt4-sql-sqlite	4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1		amd64
libsqlite3-0	3.8.7.1-1+deb8u2		amd64
php5-sqlite	5.6.27+dfsg-0+deb8u1		amd64
sqlite3	3.8.7.1-1+deb8u2		amd64
sqlitebrowser	3.2.0-1		amd64
root@jhegaala:~# 

**PHP version:**

root@jhegaala:~# php --version
PHP 5.6.27-0+deb8u1 (cli) (built: Oct 15 2016 15:53:28) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
root@jhegaala:~# 

**Nextcloud version:** (see Nextcloud admin page)

Nextcloud 10.0.1 (stable) (and this item could use better instructions!)

**Updated from an older Nextcloud/ownCloud or fresh install:**

Fresh.

**Where did you install Nextcloud from:**

???? If you mean, where did I get the software, from the NextCloud web site.

**Signing status:**
<details>
<summary>Signing status</summary>

Huh?

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed
paste the results here.

I get redirected to the login page:

http://nextcloud/nextcloud/index.php/login?redirect_url=%252Fnextcloud%252Findex.php%252Fsettings%252Fintegrity%252Ffailed

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
root@jhegaala:/var/www/nextcloud# sudo -u www-data php occ app:list
Enabled:
  - activity: 2.3.2
  - calendar: 1.4.0
  - comments: 1.0.0
  - contacts: 1.4.0.0
  - dav: 1.0.1
  - documents: 0.13.1
  - federatedfilesharing: 1.0.1
  - federation: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_versions: 1.3.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.0
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - provisioning_api: 1.0.0
  - serverinfo: 1.1.1
  - survey_client: 0.1.5
  - systemtags: 1.0.2
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - admin_audit
  - encryption
  - external
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - templateeditor
  - user_external
  - user_ldap
  - user_saml
root@jhegaala:/var/www/nextcloud# 

</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

root@jhegaala:/var/www/nextcloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "oc2u0vw0qwrd",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "nextcloud.localdomain",
            "nextcloud",
            "localhost"
        ],
        "datadirectory": "\/var\/www\/nextcloud\/data",
        "overwrite.cli.url": "https:\/\/nextcloud\/nextcloud",
        "dbtype": "sqlite3",
        "version": "9.1.1.5",
        "logtimezone": "UTC",
        "installed": true,
        "mail_from_address": "owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "jhegaala"
    }
}
root@jhegaala:/var/www/nextcloud# 


or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

No.

**Are you using encryption:** yes/no

Yes.

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

No.

### Client configuration
**Browser:**

Firefox ESR 45.5.1

firefox-esr	45.5.1esr-1~deb8u1

**Operating system:**

root@hawk:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 8.6 (jessie)
Release:	8.6
Codename:	jessie
root@hawk:~# 

#### Web server error log
<details>
<summary>Web server error log</summary>
```

Give me a hint on what to look for.

Insert your webserver log here
```

Give me a hint on what to look for.

</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
No entries on the relevant date.

</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```

None available.

</details>

**Comment by nickvergessen** [comment]
Please insert the browser log as requested by the issue template

**Comment by charlescurley** [comment]
On Sat, 10 Dec 2016 07:40:42 -0800
Joas Schilling <notifications@github.com> wrote:

> Please insert the browser log as requested by the issue template
> 

There is no browser log. I have the Web Developer extension installed.
I pulled up the browser console. No logs, no errors reported.

-- 

The right of the people to be secure in their persons, houses, papers,
and effects, against unreasonable searches and seizures, shall not be
violated, and no Warrants shall issue, but upon probable cause,
supported by Oath or affirmation, and particularly describing the
place to be searched, and the persons or things to be seized.
-- U.S. Const. Amendment IV

Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB

**Comment by nickvergessen** [comment]
What does the network log say?

**Comment by charlescurley** [comment]
On Sat, 10 Dec 2016 08:42:38 -0800
Joas Schilling <notifications@github.com> wrote:

> What does the network log say?

Which network log? Or perhaps, what network log?

-- 

The right of the people to be secure in their persons, houses, papers,
and effects, against unreasonable searches and seizures, shall not be
violated, and no Warrants shall issue, but upon probable cause,
supported by Oath or affirmation, and particularly describing the
place to be searched, and the persons or things to be seized.
-- U.S. Const. Amendment IV

Key fingerprint = CE5C 6645 A45A 64E4 94C0  809C FFF6 4C48 4ECD DFDB

**Comment by georgehrke** [comment]
@charlescurley The network log inside your web browser.

**Comment by MorrisJobke** [comment]
In the web developer tools of your browsers there is a network tab. Open it and then do the import again. 😉 

I will close this ticket until the needed information is available.

**Comment by charlescurley** [comment]
Ah, found it. Thank you.

Try this. The silly software wouldn't accept the .har extension, so I added the .txt.

[Archive 17-01-24 14-30-41.har.txt](https://github.com/nextcloud/server/files/728001/Archive.17-01-24.14-30-41.har.txt)

**Comment by MorrisJobke** [comment]
@nickvergessen @georgehrke Mind to have a look? ;)

**Comment by charlescurley** [comment]
I upgraded nextcloud, and the problem appears to have gone away.

`'version' => '9.1.3.2'`

**Comment by MorrisJobke** [comment]
> Hmm... config.php says:
> 'version' => '9.1.3.2'
> 
> But the admin server settings page says "Nextcloud 10.0.3 (stable)".

All fine. 9.1 is our internal version number for 10 🙈
