### ISSUE TITLE
Sidebar icon

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#25976]
Select "Applications" from the NC menu. The sidebar icon overlaps the application icon.

![obraz](https://user-images.githubusercontent.com/47037905/110207258-8d83b780-7e82-11eb-87dd-c14d379e5d55.png)

### Server configuration

**Nextcloud version:** (see Nextcloud admin page) 20.0.6

### Client configuration
**Browser:** Firefox 86.0

**Comment by kesselb** [comment]
cc @nextcloud/designers

**Comment by dartcafe** [comment]
see https://github.com/nextcloud/server/issues/16934

**Comment by kesselb** [comment]
Thanks @dartcafe :+1: 

I could not find it :see_no_evil:
