### ISSUE TITLE
Leapster Birthday wrong date in leap years

### ISSUE THREAD

**Issue by 2EyeTec** [nextcloud/server#25979]
### Steps to reproduce
1.  Create a contacts birthday on February 29th 

### Expected behaviour
In a leap year (with February 29th, eg. 2020) the birthdays should be displayed on Feb. 29th

### Actual behaviour
It's always on Mar. 1st - even if Feb. 29th exists

**Comment by mattian** [comment]
Please see #19218, it seems to be the same issue.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/19218
