### ISSUE TITLE
E-mail notifications for read-only calendars (contacts, subscription, ...)

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#25977]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

**Is your feature request related to a problem? Please describe.**
I primarily collect all the things I need to be notified about in my e-mail, not via dozen apps and services. I also do not want to have to remind myself to read my calendar every day.

**Describe the solution you'd like**
I want to be be able to configure timed e-mail notifications for read-only calendars (birthdays, subscription, ...) in the same fashion as self made calendars.

**Describe alternatives you've considered**
There are no alternatives.

**Additional context**
None.

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
