### ISSUE TITLE
[Resolved I think]Nextloud doesn't work when MTU is set to 9000

### ISSUE THREAD

**Issue by jimmyfi** [nextcloud/server#25980]
Ping on higher packet sizes works just fine and everything else works as it should Except Nextcloud.

When i set MTU to 1500 Nextcloud works as well..  Solution shouldn't be "set MTU 1500" 

### Steps to reproduce
1. Set network mtu 9000 between your server and Client machine.

### Expected behaviour
everything should work normally with MTU set to 9000

### Actual behaviour
Either nextcloud client nor website are accesable. All other websites are working just fine on the Server

### Server configuration

**Operating system:**
Debian 11
**Web server:**
Nginx 1.18
**Database:**
Ver 15.1 Distrib 10.5.9-MariaDB, for debian-linux-gnu
**PHP version:**
PHP 7.4.15
**Nextcloud version:** (see Nextcloud admin page)
Nextcloud 20.0.8
**Updated from an older Nextcloud/ownCloud or fresh install:**
~
**Where did you install Nextcloud from:**
~
**Signing status:**

Thanks

**Comment by kesselb** [comment]
Logs?

**Comment by jimmyfi** [comment]
> 
> 
> Logs?

There was nothing on access nor error logs from my client

**Comment by jimmyfi** [comment]
![kuva](https://user-images.githubusercontent.com/11514773/110233707-77333580-7f2e-11eb-9b6d-4d8110356507.png)
I made a network graph of my setup

**Comment by jimmyfi** [comment]
I think i fixed it by enabling cloudflare Proxy. No idea how that is the fix but it seemed to take away the issue and MTU is still 9000

**Comment by kesselb** [comment]
I'm not aware of any configuration / code that uses the MTU for something. I guess it's something with the server configuration. If one finds something feel free to open a new issue here and provide information how to reproduce.
