### ISSUE TITLE
Year 2038 Problem When Executing occ security:certificates:import

### ISSUE THREAD

**Issue by ghost** [nextcloud/server#25989]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. ``sudo -u www-data php -f occ security:certificates:import /path/to/cacert.crt``
2. ``sudo -u www-data php -f occ security:certificates``
3. ``sudo -u www-data php -f occ news:feed:add User https://example.com/jsonfeed.json``

### Expected behaviour
The CA certificate should be valid until 2043/8/24.

### Actual behaviour
The CA certificate has been expired on 1907/7/19, over a century ago.

### Server configuration

**Operating system:**
Alpine Edge

**Web server:**
nginx/1.18.0

**Database:**
mariadb  Ver 15.1 Distrib 10.5.9-MariaDB, for Linux (armv8l) using readline 5.1

**PHP version:**
PHP 7.4.15

**Nextcloud version:** (see Nextcloud admin page)
20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from older Nextcloud since 20.0.2.

**Where did you install Nextcloud from:**
Nextcloud Official.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - audioplayer: 3.1.0
  - bookmarks: 4.1.0
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - checksum: 1.1.1
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - files: 1.15.0
  - files_external: 1.11.1
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - issuetemplate: 0.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - news: 15.3.2
  - nextcloud_announcements: 1.9.0
  - notes: 4.0.2
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - passwords: 2021.2.0
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - activity
  - admin_audit
  - bookmarks_0
  - encryption
  - federation
  - files_trashbin
  - sharebymail
  - support
  - user_ldap
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "http:\/\/localhost",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "default_language": "ja_JP",
        "default_locale": "ja_JP",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "maintenance": false,
        "theme": "",
        "loglevel": 2
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

#### Web server error log
<details>
<summary>Web server error log</summary>

```
(No Web server error.)
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
(No error recorded.)
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
(No Browser used.)
```
</details>

**Comment by kesselb** [comment]
Luckily we have  ~2 decades to fix this issue ;)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by HouraisanNEET** [comment]
Yes, I have reproduced it on 21.0.3.

Certificate Infomations on Firefox:

```
Not Before 2021/7/5
Not After 2516/7/4
```

Outputs of ``sudo -u www-data php -f /var/html/www/nextcloud/occ security:certificates``

```
+--------------+-----------------+-----------------------+--------------+-----------------+
| File Name    | Common Name     | Organization          | Valid Until  | Issued By       |
+--------------+-----------------+-----------------------+--------------+-----------------+
| Flandre.crt  | Flandre Scarlet | Scarlet Devil Mansion | 1972年2月5日 | Flandre Scarlet |
+--------------+-----------------+-----------------------+--------------+-----------------+

```

**Comment by HouraisanNEET** [comment]
I figured out why it happens. I am not sure if I should close it or not.

## armv7
```
+--------------+-----------------+-----------------------+--------------+-----------------+
| File Name    | Common Name     | Organization          | Valid Until  | Issued By       |
+--------------+-----------------+-----------------------+--------------+-----------------+
| Flandre.crt  | Flandre Scarlet | Scarlet Devil Mansion | 1972年2月5日 | Flandre Scarlet |
+--------------+-----------------+-----------------------+--------------+-----------------+
```

## x86_64
```
+--------------+-----------------+-----------------------+--------------+-----------------+
| File Name    | Common Name     | Organization          | Valid Until  | Issued By       |
+--------------+-----------------+-----------------------+--------------+-----------------+
| Flandre.crt  | Flandre Scarlet | Scarlet Devil Mansion | 2516年7月4日 | Flandre Scarlet |
+--------------+-----------------+-----------------------+--------------+-----------------+
```

**Comment by szaimen** [comment]
As armv7 (32bit) only is affected and only he seems to be affected and he left GitHub, I am closing this.
