### ISSUE TITLE
ExternalStorage: 503-faile, when open files by connectivity with smb/cifs from NAS

### ISSUE THREAD

**Issue by mysap01** [nextcloud/server#25986]
### How to use 
I use ExternalStorage for connectivity my NAS into Nextcloud with change to Buster, i see the same directories and files, like before. When i will open any files like Excel, i will get the fails message 503-Service Unavailable withou any nextcloud-log information. At the time from chessie was that no problem, and i have never change any at the NAS.

### Steps to reproduce
1. Install raspberry with buster
2. Install nextcloudpi
3. Use app external-storage for connectivities the NAS
4. See all files and directories from NAS
5. 503-fail, when i open a file .txt, .xlsx

### Server configuration

NextCloudPi version | v1.34.7
distribution | Raspbian GNU/Linux 10 \n \l
automount | no
USB devices | none
datadir | /var/www/nextcloud/data
data in SD | yes
data filesystem | ext2/ext3
data disk usage | 8.3G/15G
rootfs usage | 8.3G/15G
swapfile | /var/swap
dbdir | /var/lib/mysql
Nextcloud check | ok
Nextcloud version | 20.0.4.0
HTTPD service | up
PHP service | up
MariaDB service | up
Redis service | up
Postfix service | up
internet check | ok
NAT loopback | no
</details>

**Comment by kesselb** [comment]
Issue Template and especially logs are missing => needs info

**Comment by mysap01** [comment]
No nc, no apacha-log. Only follow nc-access:
192.168.1.114 - - [08/Mar/2021:20:21:36 +0100] "GET /remote.php/webdav/daten/Rezeptbuch.xlsx HTTP/2.0" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.1.114 - - [08/Mar/2021:20:21:36 +0100] "GET /remote.php/webdav/daten/Rezeptbuch.xlsx HTTP/2.0" 503 358 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"

**Comment by mysap01** [comment]
> 
> 
> Issue Template and especially logs are missing => needs info

No nc-log, no apacha-log. Only follow nc-access:
192.168.1.114 - - [08/Mar/2021:20:21:36 +0100] "GET /remote.php/webdav/daten/Rezeptbuch.xlsx HTTP/2.0" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.1.114 - - [08/Mar/2021:20:21:36 +0100] "GET /remote.php/webdav/daten/Rezeptbuch.xlsx HTTP/2.0" 503 358 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"

**Comment by mysap01** [comment]
@kesselb
No nc-log, no apacha-log. Only follow nc-access:
192.168.1.114 - - [08/Mar/2021:20:21:36 +0100] "GET /remote.php/webdav/daten/Rezeptbuch.xlsx HTTP/2.0" 200 0 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"
192.168.1.114 - - [08/Mar/2021:20:21:36 +0100] "GET /remote.php/webdav/daten/Rezeptbuch.xlsx HTTP/2.0" 503 358 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:86.0) Gecko/20100101 Firefox/86.0"

**Comment by mysap01** [comment]
Answered

**Comment by mysap01** [comment]
What can i do to get forward?
