### ISSUE TITLE
Remove deprecated Server::getDb() and Db class

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#2599]
https://github.com/nextcloud/server/blob/master/lib/private/Server.php#L1207 is deprecated and the code comment announces the removal for the first version next year. So, time to get rid of it in 12, what do you think? @nickvergessen @MorrisJobke @BernhardPosselt

**Comment by rullzer** [comment]
yes :tada:

**Comment by nickvergessen** [comment]
PR at https://github.com/nextcloud/server/pull/2665 and https://github.com/nextcloud/user_saml/issues/58

Only other app that still uses this has been notified: https://github.com/nextcloud/mail/issues/237
