### ISSUE TITLE
Option to remove social links on user settings page

### ISSUE THREAD

**Issue by devnull4242** [nextcloud/server#26006]
Is it possible to remove the social links like facebook, twitter, mastodon, blogs and newsletter?
I do not like them. I do not need them. My users are not allowed to use them at work.

Here a thread to the theme.  

https://help.nextcloud.com/t/how-can-i-get-rid-off-the-note-to-licence-sourcecode-and-community/78742

**Comment by tessus** [comment]
Same is true for the “Reasons to use Nextcloud in your organization” section.

I don't need ads on my setup. At least give people a choice to get rid of them.

**Comment by nsturtz** [comment]
Yes please, I do not want to have to edit the file every time i update

**Comment by Caro-m** [comment]
inputting the following css code on the custom css app removes the whole section
 
.development-notice {
display: none;
}

![no social](https://user-images.githubusercontent.com/30080135/110516638-e66d7d00-811a-11eb-83f7-3ea7d073383f.PNG)

**Comment by nsturtz** [comment]
But updating breaks it.

**Comment by tessus** [comment]
@Caro-m The custom css is loaded for every single web page. Yes, they're not a lot of characters, especially when using brotli, but still. Coming from a performance background I have to say that this is not the best approach.
Also, I don't find it ok that I have to install a 3rd party app to get rid of stuff that shouldn't be there in the first place.

**Comment by Caro-m** [comment]
> @Caro-m The custom css is loaded for every single web page. Yes, they're not a lot of characters, especially when using brotli, but still. Coming from a performance background I have to say that this is not the best approach.
> Also, I don't find it ok that I have to install a 3rd party app to get rid of stuff that shouldn't be there in the first place.

I agree its no the best fix.

**Comment by nsturtz** [comment]
> > @Caro-m The custom css is loaded for every single web page. Yes, they're not a lot of characters, especially when using brotli, but still. Coming from a performance background I have to say that this is not the best approach.
> > Also, I don't find it ok that I have to install a 3rd party app to get rid of stuff that shouldn't be there in the first place.
> 
> I agree its no the best fix.

The best fix would be for someone a nextcloud to fix it.

**Comment by jancborchardt** [comment]
Just to copy what I said over at https://github.com/nextcloud/server/pull/26035#issuecomment-795524256 FYI

> My take is: Nextcloud is an open source project available for free, and our goal is to offer an alternative to as many people as possible. This small reference to the code & community along with license, prompt to promote, and feature document is absolutely fine. The more people who know about it, the more people can also participate, and the software can also become better.
>
> If someone really wants to hide it, they can do it via a simple line of CSS as @caro-m commented at https://github.com/nextcloud/server/issues/26006#issuecomment-794244863
>
> But introducing settings for this means the opposite, as usual for settings: This needs to be maintained and ensured it always works, resulting in more busywork rather than time for enhancements and fixes.

**Comment by nsturtz** [comment]
Nobody in my family cares about the source code, BUT it is just annoying, and to quote  https://github.com/nextcloud/server/pull/26035#issue-588708820, 
> php occ config:app:set settings show_reasons_use_nextcloud --value=no
> php occ config:app:set settings show_social_buttons --value=no

If I knew how to I would just add it

**Comment by MorrisJobke** [comment]
Closing as per the comment of @jancborchardt and @jospoortvliet (see also https://github.com/nextcloud/server/pull/26035#issuecomment-795524256)

**Comment by akinola-mi** [comment]
It is easy to apps/settings/templates/settings/personal/development.notice.php

The PDF file is in apps/settings/data

That is how I edited mine

**Comment by akinola-mi** [comment]
To remove the Help Us Translate link under Language in the settings page, go to **apps/settings/templates/settings/personal//personal.info.php**

The Help menu can be edited in **apps/settings/templates/help.php**

**Comment by akinola-mi** [comment]
> Is it possible to remove the social links like facebook, twitter, mastodon, blogs and newsletter? I do not like them. I do not need them. My users are not allowed to use them at work.
> 
> Here a thread to the theme.
> 
> https://help.nextcloud.com/t/how-can-i-get-rid-off-the-note-to-licence-sourcecode-and-community/78742

I just posted mu solution here, you can check it

**Comment by KaiBuskirk** [comment]
> 

only worked on admin...  
need it for all users...

or i need help creating a custom app...
DM me if you can help...

tyia
kai buskirk
