### ISSUE TITLE
No built-in updater button on 17.0.9

### ISSUE THREAD

**Issue by Sick-Andrew** [nextcloud/server#26008]
### Steps to reproduce
1. Login with Webbrowser into your NC
2. Settings
3. Overview

### Expected behaviour
There should be an update check/button for a never version

### Actual behaviour
It only shows: "The update check is not yet finished. Please refresh the page."

### Server configuration

**Web server:**
Apache on shared hosting

**Database:**
MySQL 5.0

**PHP version:**
7.3.21

**Nextcloud version:** (see Nextcloud admin page)
17.0.9

I wanted to Update our NC 17.0.9 but there is just no way for checking for a new version. I tried several resolutions that helped other users but nothing worked. The log does not really provide any errors that are connected to something with updates. Is there a way I can "restart" the update check by FTP oder web interface? As mentioned I use shared hosting so no full access via SSH. 
Thank you

![ncerror](https://user-images.githubusercontent.com/39406635/110350773-581ecb80-8034-11eb-93fd-d46db7b011ec.jpg)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
