### ISSUE TITLE
Problems when Nextcloud is installed on a NFS share

### ISSUE THREAD

**Issue by Prog1563** [nextcloud/server#26016]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Install Nextcloud with a locally mounted NFS share as the data directory.
2. Observe logs

### Expected behaviour
I am not quite sure what is going on here. The file gets made, and gets removed best I can tell. I wouldn't expect this error.

### Actual behaviour
When OC_Util.php gets called for a server check, it creates a temporary file and then checks to see if it exists, then deletes it.
However, oddly enough, even though the file got deleted, I receive this error: `Error: unlink(/mnt/nextcloud/data_dir_writability_test_6046710b122b3.tmp): No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Util.php#814`

### Server configuration

**Operating system:** Debian 10

**Web server:** NGINX 1.14.2

**Database:** MariaDB 10

**PHP version:** 8.0

**Nextcloud version:** 21.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:** This server has been updated from 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, and 10 and was previously migrated from OwnCloud. It was only recently moved to an NFS share as we have expanded.

**Where did you install Nextcloud from:** The Nextcloud website.

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - admin_audit: 1.10.0
  - apporder: 0.12.0
  - bookmarks: 4.1.0
  - breezedark: 20.0.7
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - carnet: 0.23.8
  - cloud_federation_api: 1.3.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.4
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - drawio: 0.9.9
  - duplicatefinder: 0.0.6
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - groupfolders: 8.2.0
  - imageconverter: 1.3.1
  - impersonate: 1.7.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - notes: 4.0.4
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - passwords: 2021.3.0
  - photos: 1.2.3
  - provisioning_api: 1.10.0
  - richdocuments: 3.7.15
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_nextcloud_notification: 3.1.2
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - workflowengine: 2.2.0
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "***REMOVED SENSITIVE VALUE***"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "***REMOVED SENSITIVE VALUE***",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "memcache.local": "\\OC\\Memcache\\APCu",
        "filelocking.enabled": true,
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 0,
            "dbindex": 0,
            "timeout": 1.5
        },
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "tls",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "maintenance": false,
        "debug": false,
        "loglevel": 2,
        "updater.release.channel": "stable",
        "defaultapp": "dashboard",
        "logfile": "\/mnt\/nextcloud\/nextcloud.log",
        "logfilemode": 416,
        "log_rotate_size": 10485760,
        "knowledgebaseenabled": false,
        "has_rebuilt_cache": true
    }
}
```
</details>

**Are you using external storage, if yes which one:** Locally mounted NFS

**Are you using encryption:** Yes, the drives are LUKS encrypted.

**Are you using an external user-backend, if yes which one:** No

### Client configuration
**Browser:** Multiple different browsers and clients trigger this event.

**Operating system:** Multiple different systems trigger this event.

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
{"reqId":"RbSYJhTb0KhlYCDKKK4y","level":3,"time":"2021-03-08T18:46:35+00:00","remoteAddr":"**REMOVED SENSITIVE VALUE**","user":"--","app":"PHP","method":"POST","url":"/index.php/apps/passwords/api/1.0/tag/list","message":{"Exception":"Error","Message":"unlink(/mnt/nextcloud/data_dir_writability_test_6046710b122b3.tmp): No such file or directory at /var/www/nextcloud/lib/private/legacy/OC_Util.php#814","Code":0,"Trace":[{"function":"onError","class":"OC\\Log\\ErrorHandler","type":"::"},{"file":"/var/www/nextcloud/lib/private/legacy/OC_Util.php","line":814,"function":"unlink"},{"file":"/var/www/nextcloud/lib/base.php","line":660,"function":"checkServer","class":"OC_Util","type":"::"},{"file":"/var/www/nextcloud/lib/base.php","line":1091,"function":"init","class":"OC","type":"::"},{"file":"/var/www/nextcloud/index.php","line":35,"args":["/var/www/nextcloud/lib/base.php"],"function":"require_once"}],"File":"/var/www/nextcloud/lib/private/Log/ErrorHandler.php","Line":91,"CustomMessage":"--"},"userAgent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36","version":"20.0.8.1","id":"604679ce48d4f"}
```
</details>

Edit 05/06/2021 -> Upgraded to NC 21.0.1 by accident instead of 20.0.9

**Comment by Prog1563** [comment]
I have taken some troubleshooting steps that were offered up by the forums over the years... But nothing seemed to make a difference.

I have tried:
 - Making sure that the www-data user has the same UID on both the NAS and the box that Nextcloud is running on. It is.
 - Making sure that the permissions are set correctly and that PHP has all necessary permissions. Yup.
 - Making my own PHP test file that accomplishes the same task, result was no errors produced.

I have not tried:
- modifying the unlink out of the code to see if the files stick around (Don't want to break something on production).
- moving the server back away from NFS (I don't own any drive big enough to try this as we moved to NFS so we could get more space).

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by Prog1563** [comment]
We only just updated to 21.0.3 this morning. I will come back to this issue in a couple of days.

**Comment by Prog1563** [comment]
Just poked a look into the logs since I had some time, I can confirm this issue is still valid for 21.0.3 @szaimen

I was also able to confirm that it is not a PHP8.0 issue, as we downgraded to 7.4 because of the compatibility issues in Nextcloud.

**Comment by szaimen** [comment]
So it seems like a problem when Nextcloud is installed on a NFS share...

**Comment by Prog1563** [comment]
@szaimen I have been playing around with NC in a test environment that is also NFS and I have found some strange behavior that, I think, is more related to PHP than it is to Nextcloud. What I have found is that if I remove the unlink() in the code at line 819, the file is created and stays in the data directory, however, if I add the unlink() back, it does in fact delete the file, but ALSO says that there is no such file or directory... Very strange.

After some more playing around, I also found that adding a sleep(1) after the fclose() and before the unlink() it works just fine with no error. (This is hideous, though, and I would never deploy that in production...)

With that being said, I think I am going to close this issue as not related to Nextcloud, but instead either a PHP bug (PHP seems to really hate NFS) or a filesystem configuration issue.

The file in question is <NC Root>/lib/private/legacy/OC_Util.php
```
if ($config->getValue('installed', false)) {
        if (!is_dir($CONFIG_DATADIRECTORY)) {
                $success = @mkdir($CONFIG_DATADIRECTORY);
                if ($success) {
                        $errors = array_merge($errors, self::checkDataDirectoryPermissions($CONFIG_DATADIRECTORY));
                } else {
                        $errors[] = [
                                'error' => $l->t('Cannot create "data" directory'),
                                'hint' => $l->t('This can usually be fixed by giving the webserver write access to the root directory. See %s',
                                        [$urlGenerator->linkToDocs('admin-dir_permissions')])
                        ];
                }
        } elseif (!is_writable($CONFIG_DATADIRECTORY) or !is_readable($CONFIG_DATADIRECTORY)) {
                // is_writable doesn't work for NFS mounts, so try to write a file and check if it exists.
                $testFile = sprintf('%s/%s.tmp', $CONFIG_DATADIRECTORY, uniqid('data_dir_writability_test_'));
                $handle = fopen($testFile, 'w');
                if (!$handle || fwrite($handle, 'Test write operation') === false) {
                        $permissionsHint = $l->t('Permissions can usually be fixed by giving the webserver write access to the root directory. See %s.',
                                [$urlGenerator->linkToDocs('admin-dir_permissions')]);
                        $errors[] = [
                                'error' => 'Your data directory is not writable',
                                'hint' => $permissionsHint
                        ];
                } else {
                        fclose($handle);
                        unlink($testFile);
                }
        } else {
                $errors = array_merge($errors, self::checkDataDirectoryPermissions($CONFIG_DATADIRECTORY));
        }
}
```

**Comment by dumblob** [comment]
@Prog1563 wow, great findings! I'm surprised though that modern PHP behaves like that.

I actually thing this issues shall stay opened until it "ceases to exist".

IMHO now the best way to proceed would be to file this "fclose() followed by unlink() on NFS unreliable" bug on [PHP upstream](https://bugs.php.net/report.php ) - @Prog1563 would you be willing to provide your precious test env setup to PHP devs and file the bug in their bug tracker?
