### ISSUE TITLE
INVALID_HASH: core/js/mimetypelist.js in the list of invalid files

### ISSUE THREAD

**Issue by mixim-mixim** [nextcloud/server#26022]
- execute the occ-command: <sudo -u www-data php> occ maintenance:mimetype:update-js
- this will generate the new file [nextcloud home]/core/js/mimetypelist.js
- go to the menu 'Einstellungen' -> 'Übersicht' (don't know the exact translation, probably 'Settings' -> 'Overview')
- there is a security issue regarding invalid file hash

**Comment by mixim-mixim** [comment]
Nextcloud 21.0.0 (stable)
PHP 8.0.2
MariaDB: 10.3.25
Ubuntu 20.0.4

**Comment by mixim-mixim** [comment]
[mimetypelist.js.txt](https://github.com/nextcloud/server/files/6108656/mimetypelist.js.txt)

**Comment by skjnldsv** [comment]
If the file was manually edited and that was what you expected, then you can ignore.

**Comment by stefan123t** [comment]
I also get this message on the Settings > Administration > Overview page.

Security & setup warnings 
Some files have not passed the integrity check. Further information on how to resolve this issue can be found in the documentation. (List of invalid files… / Rescan…)

@mixim-mixim I got the same error and compared the mimetypelist.js you attached with mine: they are matching exactly.
Could you double check the hashes that were reported on your side ?

@skjnldsv I am not aware that I changed anything on the mimetypelist.js manually. 
So I guess this is a problem on the nextcloud version 21.0.1 I am using.
Please consider reopening this issue.

Here is the output from the List of invalid files… https://hostname.tld/nextcloud/settings/integrity/failed 

```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
    [core] => Array
            [INVALID_HASH] => Array
                    [core/js/mimetypelist.js] => Array
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 86c1f1b719b65bf02b1dca9b061ef310c8dfface25c9ccfa243c4090665fa6f305d8a4143d7410350af27b1d9e14968c7d999a965d1e110bc674d30ed5dee4e8

```

**Comment by mig5** [comment]
I am getting the same as the above post (same hash difference). All I did was run a NextCloud upgrade from 22.2.0 to 22.2.5. I did not manually edit the JS file or manually run the update-js command, just did a standard NextCloud upgrade via the command line.

**Comment by pierr0t** [comment]
Same here, got that error after upgrading from 22.2.3 to 22.2.5 and I didn't manually edit those files ... Unfortunately I am not proposed yet with 23.

**Comment by gianks** [comment]
> Same here, got that error after upgrading from 22.2.3 to 22.2.5 and I didn't manually edit those files ... Unfortunately I am not proposed yet with 23.

Same here!

**Comment by kilrau** [comment]
Same issue, also happened with update from  22.2.3 to 22.2.5. Did not manually edit `mimetypelist.js`.

Please reopen @skjnldsv

**Comment by tapsel07** [comment]
> Same here, got that error after upgrading from 22.2.3 to 22.2.5 and I didn't manually edit those files ... Unfortunately I am not proposed yet with 23.

Same here!

**Comment by marius-lupu** [comment]
I have the same issue here. I also tried to add the file from Github but with the same result, saying that the hash is invalid.

**Comment by geramaya** [comment]
Pls reopen this bug 
Version 23.0.2
php: 8.0.14


Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js
		
Pls recheck code changes and create a valid md5 checksum and a patch for it.

**Comment by chagwood** [comment]
Same here. Just upgraded. Got error about mimetypelist.js

**Comment by meinrecht** [comment]
Just experienced the same error during an upgrade of the app Mind map. 

According to this comment:
https://help.nextcloud.com/t/solved-invalid-hash-for-mimetypelist-js/40680/6
the error is actually caused by this app.

To fix the error I copied the original file from this repsitory to my docker image and restarted the scan in 
`${HOSTNAME}/settings/admin/overview`. 

The diff of the changed mindmap to the original one is:
```
diff mimetypelist.js mimetypelist.js.new 
113,117c113
<     "application/vnd.xmind.workbook": "mindmap",
<     "image/targa": "image/tga",
<     "": "x-office/document",
<     "application/vnd.openxmlformats-officedocument.wordprocessingml.document.docxf": "x-office/document",
<     "application/vnd.openxmlformats-officedocument.wordprocessingml.document.oform": "x-office/document"
---
>     "application/vnd.xmind.workbook": "mindmap"
147a144
> 
```
The location of the file in a directory named "core" sounds like apps are not supposed to change it. So this actually looks like an issue of Mind map.

**Comment by andreapx** [comment]
I've just updated my docker installation and I have the same problem. I don't have the app MindMap installed.
It's pretty strange that the devs didn't notice this problem in the docker.

**Comment by pecuna** [comment]
> I've just updated my docker installation and I have the same problem. I don't have the app MindMap installed. It's pretty strange that the devs didn't notice this problem in the docker.

I have the same issue with manual installation. NO MindMap app installed..

**Comment by szaimen** [comment]
See https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/600

**Comment by pjft** [comment]
Same on 21.0.9. Never touched that file. I'm running it straight from Apache, no docker.

Regenerated it. Exact same hashes as https://github.com/nextcloud/server/issues/26022#issuecomment-840484033 .

**Comment by andreapx** [comment]
> See [ONLYOFFICE/onlyoffice-nextcloud#600](https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/600)

I've disabled and removed the onlyoffice app, but the alert persists.

**Comment by kilrau** [comment]
And restarted Nextcloud?

**Comment by kilrau** [comment]
Anyhow, anyone without OnlyOffice connector installed facing this issue speak up, other than that the fix is to be done on OnlyOffice's side: https://github.com/ONLYOFFICE/onlyoffice-nextcloud/issues/600

**Comment by andreapx** [comment]
> And restarted Nextcloud?

I've stopped, removed and recreated the container but I still has that warning

**Comment by andreapx** [comment]
> You'll need to execute the following in your container:
> 
> ```
> cp -av /usr/src/nextcloud/core/js/mimetypelist.js core/js/
> ```

Done, but I still get the same warning.

**Comment by frankmaszinek** [comment]
I have the same problem too.   Just upgraded from 20.0.11 to 20.0.14 after Ubuntu did a very convenient automatic upgrade of MySQL 5.7 to 8.0.

No MindMap installed.

Copied the mimetypelist.js from the nextcloud download to my running server. 

OCC updated js.

still have message.  

I believe it may take  time to clear though after doing all this.  Will keep checking.

**Comment by modzilla99** [comment]
Can't be, I've done that for the latest update as well and it does what it's supposed to. Don't forget to click the recheck Button at the end of the line. It doesn't calculate the hashes automatically again

**Comment by masterwishx** [comment]
Having this for first time after nextcloud 24.0 update in Unraid Linux linuxserver/nextcloud .
after copyed file from lasted nextcloud arhve v24 there is no error.
but if running occ maintenance:mimetype:update-js the problem return ...

**Comment by Intenos** [comment]
Same here. It also appeared after updating Nextcloud to 24.0.0. I use also the docker linuxserver/nextcloud. But actually the problem appeared only by one installation, by another one using the same docker it didn´t show up.

**Comment by masterwishx** [comment]
> Same here.

**Comment by drizzer** [comment]
remove the file and download the latest version then it works,
here are the commands just adjust your installation directory if you have it somewhere else

```
sudo rm /var/www/nextcloud/core/js/mimetypelist.js
sudo wget https://raw.githubusercontent.com/nextcloud/server/master/core/js/mimetypelist.js -P /var/www/nextcloud/core/js
```

**Comment by meonkeys** [comment]
Related (for me): https://github.com/jgraph/drawio-nextcloud/issues/26

**Comment by flotpg** [comment]
Same issue here on Nextcloud 28.0.4.
```
Technical information
=====================
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results
=======
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output
==========
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201
                            [current] => 5b121122c0bec0580402c04605700056ee06eb553a4692bfc085ad3fc17aa49af43ca7795e98cbd22383020bfa9809bf3cc824b1673595f461479afb602bcec4
                        )

                )

        )

)
```
When I download https://raw.githubusercontent.com/nextcloud/server/master/core/js/mimetypelist.js and do a shasum -a 512 I get the same as the currently installed file:
`5b121122c0bec0580402c04605700056ee06eb553a4692bfc085ad3fc17aa49af43ca7795e98cbd22383020bfa9809bf3cc824b1673595f461479afb602bcec4`

The file you (@trivialkettle) linked 550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201 results in a different hash, so I'm asking myself how this could have worked for you ;) because it's not the expected hash `550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201 `. 
In my case (tried on different machines with differen ISPs :) ) it's `dc88d7cd149e8b6ca383edd11716ea97aa30255a57b970c9649b7cda4c4d17f82afa841c79d12e74522560ad46c9127573889860c1c30fb68c6d93f57f5430ea`

Thansk for any hint and best regards, Flo.

**Comment by flotpg** [comment]
I made some progress and it looks like the released zip file for 28.0.4 contains mimetypelist.js with the expected sha512 hash:

https://github.com/nextcloud/server/archive/refs/tags/v28.0.4.zip
`550ab566d30693bfa24ec4b15d9df87731ae8a3be8f79dabf94757e5b8b20eec6e4b678f17af1718297f2872f6b04519eeb024d1dff11947f29da431c7f11201`

But the one from the repo has a different hash:

- https://github.com/nextcloud/server/blob/master/core/js/mimetypelist.js
- https://raw.githubusercontent.com/nextcloud/server/master/core/js/mimetypelist.js
`5b121122c0bec0580402c04605700056ee06eb553a4692bfc085ad3fc17aa49af43ca7795e98cbd22383020bfa9809bf3cc824b1673595f461479afb602bcec4`

I'm took the file from the released zip file and it fixed the issue for me! ✅

**Comment by flotpg** [comment]
Hm, I don't understand, what do you mean with "from the correct tag"?
When taking the one from the zip file it works :)

**Comment by KaronShell** [comment]
Having same issue since manual update from 30.0.6 to 31.0.0 on a docker version.
I'm sure i downloaded the true one file from github docker, but it that the expected one stil don't match 

```
[core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 83befc51175b6888bc37997804057c6c8a42d7f6acab0f698e00d64b2d3b6b71e43ef4c59086b9cdd5154b0ed86aae1153ea68770b34cc78e446cac6af86d0ac
                            [current] => 246f864815189e28d25ff0bd94d9647eda1abc6aa0182cde52714819b848dcdabec2c0e01f2e468d3154b91a400cbec24420f33f0181665aa5094e8cc468f1b9
                        )
```

**Comment by BrandonG777** [comment]
Good to know, I'm not the only one fighting this mimetypelist.js/mimetype.js invalid hash issue. What is odd, I've replaced the files but it's just ignoring the changes...

`root@4c8f9e706a7f:/app/www/src/core/js# occ integrity:check-core
  - FILE_MISSING:
    - core/js/mimetype.js:
      - expected: 98749a18db46961b48a04287d76c6e60675559bb5a2b114140e5145722bb4d23329a2d2108aeb68c5e3bdda70dbb0a92c0178417b118dbe59b2eb3768c51b49d
      - current: 
  - INVALID_HASH:
    - core/js/mimetypelist.js:
      - expected: 83befc51175b6888bc37997804057c6c8a42d7f6acab0f698e00d64b2d3b6b71e43ef4c59086b9cdd5154b0ed86aae1153ea68770b34cc78e446cac6af86d0ac
      - current: 67d26d9518a7635208867e426472c5bb47368280684d33ca8e0bcca9c175293655c63fb7da4c12e5577fd1095fe1c4027e36c53bd441b31472f2d18c04f20c8a
root@4c8f9e706a7f:/app/www/src/core/js# ls
core.json  merged-template-prepend.json  mimetypelist.js     select2-toggleselect.js  tests
login      mimetype.js                   publicshareauth.js  setupchecks.js           update.js
root@4c8f9e706a7f:/app/www/src/core/js# `

**Comment by Coven82** [comment]
``> Having same issue since manual update from 30.0.6 to 31.0.0 on a docker version. I'm sure i downloaded the true one file from github docker, but it that the expected one stil don't match
> 
> ```
> [core] => Array
>         (
>             [INVALID_HASH] => Array
>                 (
>                     [core/js/mimetypelist.js] => Array
>                         (
>                             [expected] => 83befc51175b6888bc37997804057c6c8a42d7f6acab0f698e00d64b2d3b6b71e43ef4c59086b9cdd5154b0ed86aae1153ea68770b34cc78e446cac6af86d0ac
>                             [current] => 246f864815189e28d25ff0bd94d9647eda1abc6aa0182cde52714819b848dcdabec2c0e01f2e468d3154b91a400cbec24420f33f0181665aa5094e8cc468f1b9
>                         )
> ```

I got the same error after updating Nextcloud from version 30.x to 31.
