### ISSUE TITLE
email invitation contains buggy link instead of response controls when inviting via iOS 

### ISSUE THREAD

**Issue by britzke** [nextcloud/server#26024]
### Steps to reproduce
1. Create an event using an iOS device
2.Add a participant
3.Save the event

### Expected behaviour
An email should be sent to the participant(s) with response controls (accept, decline, other options), like it is, when I create the event via the web interface of Nextcloud.

### Actual behaviour
instead of those controls only a buggy Link `<a href=""></a>` is shown in the email

### Calendar app
**Calendar app version:** 2.1.3

**CalDAV-clients used:** iOS Calendar

### Client configuration
**Browser:** safari

**Operating system:** iOS

### Server configuration

**Operating system**: ubuntu 20.10

**Web server:** Nginx 

**Database:** MariaDB

**PHP version:** 7.4.x

**Nextcloud Version:** 20.0.8.1

**Updated from an older installed version or fresh install:**
updated from an older installed version

**List of activated apps:**

```
sudo -u www-data php occ app:list
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - admin_audit: 1.10.0
  - analytics: 3.3.3
  - announcementcenter: 4.0.1
  - apporder: 0.12.0
  - breezedark: 20.0.7
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - camerarawpreviews: 0.7.10
  - circles: 0.20.7
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - cookbook: 0.8.4
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - drawio: 0.9.9
  - epubreader: 1.4.5
  - event_update_notification: 1.2.0
  - facerecognition: 0.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.1.0
  - groupfolders: 8.2.0
  - integration_github: 0.0.20
  - integration_gitlab: 0.0.15
  - integration_reddit: 0.0.11
  - integration_twitter: 0.0.10
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - mail: 1.9.1
  - maps: 0.1.8
  - music: 1.0.3
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - piwik: 0.8.0
  - previewgenerator: 3.1.1
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - quota_warning: 1.9.1
  - radio: 1.0.2
  - recommendations: 0.8.0
  - registration: 0.7.0
  - richdocuments: 3.7.16
  - richdocumentscode: 6.4.607
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - socialsharing_diaspora: 2.1.0
  - spreed: 10.0.6
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - encryption
  - files_external
  - pride
  - talk_matterbridge
  - theming_customcss
  - user_ldap
```

**Nextcloud configuration:**

```
sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.britzke.berlin"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "https:\/\/cloud.britzke.berlin",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "LOGIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "25",
        "theme": "",
        "loglevel": 0,
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "updater.release.channel": "stable",
        "mysql.utf8mb4": true,
        "mail_smtpsecure": "tls",
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379
        },
        "app_install_overwrite": [
            "files_ebookreader"
        ],
        "enable_previews": true,
        "enabledPreviewProviders": [
            "OC\\Preview\\Image",
            "OC\\Preview\\Movie",
            "OC\\Preview\\TXT"
        ]
    }
}
```

#### Web server error log (e.g. /var/log/apache)
```
192.168.3.48 - bubi [09/Mar/2021:13:35:38 +0100] "PROPFIND /remote.php/dav/addressbooks/users/bubi/ HTTP/1.1" 207 690 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:35:39 +0100] "PROPFIND /remote.php/dav/addressbooks/users/bubi/z-app-generated--contactsinteraction--recent/ HTTP/1.1" 207 329 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:35:39 +0100] "REPORT /remote.php/dav/addressbooks/users/bubi/kontakte/ HTTP/1.1" 207 287 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
...
192.168.3.48 - - [09/Mar/2021:13:35:45 +0100] "REPORT /remote.php/dav/principals/users/ HTTP/1.1" 401 569 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:35:45 +0100] "REPORT /remote.php/dav/principals/users/ HTTP/1.1" 401 569 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:35:46 +0100] "REPORT /remote.php/dav/principals/users/ HTTP/1.1" 207 833 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:35:46 +0100] "REPORT /remote.php/dav/principals/users/ HTTP/1.1" 207 833 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:35:46 +0100] "REPORT /remote.php/dav/principals/users/ 

192.168.3.48 - - [09/Mar/2021:13:39:40 +0100] "PUT /remote.php/dav/calendars/bubi/test/F5AC58E1-FCB4-4D9F-A127-9E31F870B0A2.ics HTTP/1.1" 201 0 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:39:40 +0100] "REPORT /remote.php/dav/calendars/bubi/test/ HTTP/1.1" 207 707 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:39:40 +0100] "REPORT /remote.php/dav/calendars/bubi/test/ HTTP/1.1" 207 1398 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:39:40 +0100] "PROPFIND /remote.php/dav/calendars/bubi/inbox/ HTTP/1.1" 207 259 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:39:40 +0100] "PROPFIND /remote.php/dav/calendars/bubi/inbox/ HTTP/1.1" 207 1772 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:39:41 +0100] "REPORT /remote.php/dav/calendars/bubi/inbox/ HTTP/1.1" 207 23708 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - - [09/Mar/2021:13:39:41 +0100] "POST /remote.php/dav/calendars/bubi/outbox/ HTTP/1.1" 401 569 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:39:41 +0100] "POST /remote.php/dav/calendars/bubi/outbox/ HTTP/1.1" 200 282 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:39:42 +0100] "POST /remote.php/dav/calendars/bubi/outbox/ HTTP/1.1" 200 282 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
192.168.3.48 - bubi [09/Mar/2021:13:39:42 +0100] "POST /remote.php/dav/calendars/bubi/outbox/ HTTP/1.1" 200 282 "-" "iOS/14.4 (18D52) dataaccessd/1.0"
```

#### Log file (data/nextcloud.log)
```
{"reqId":"IBHMQDeA1HxVTX29UPBl","level":1,"time":"2021-03-09T12:39:40+00:00","remoteAddr":"192.168.3.48","user":"bubi","app":"no app in context","method":"PUT","url":"/remote.php/dav/calendars/bubi/test/F5AC58E1-FCB4-4D9F-A127-9E31F870B0A2.ics","message":"Deprecated event type for \\OCA\\DAV\\CalDAV\\CalDavBackend::createCalendarObject: Symfony\\Component\\EventDispatcher\\GenericEvent is used","userAgent":"iOS/14.4 (18D52) dataaccessd/1.0","version":"20.0.8.1","id":"60476d33126d7"}
```

#### Browser log
```
not appropriate
```

**Comment by tcitworld** [comment]
Could you post the anonymized content of the attached `event.ics` file? Seems like the event has an URL property is [not properly handled](https://github.com/nextcloud/server/blob/45cfeefd1be33b50805151b10d58647c51d80244/apps/dav/lib/CalDAV/Schedule/IMipPlugin.php#L548-L556).

**Comment by britzke** [comment]
[event.ics.txt](https://github.com/nextcloud/server/files/6111268/event.ics.txt)

**Comment by britzke** [comment]
Now Nextcloud Server 20.0.9.
It seems not to be the empty URI in the URL. Apple puts the URL into the ICS even if it is not filled with a value. I tested to fill the value but the invitation mail still does not contain the buttons to handle the invitation.
I checked with an ICS from a valid invitation and found differences in the ATTENDEE attribute:

**Apple ICS**: (two ATTENDEE attributes are found in the ICS):
```ATTENDEE;CN=participant 1;CUTYPE=INDIVIDUAL;EMAIL=paricipant1@
 email.org;PARTSTAT=NEEDS-ACTION:mailto:participant1@email.org
ATTENDEE;CN=organizer name;CUTYPE=INDIVIDUAL;EMAIL=organizer@email.org;PARTSTAT=ACCEPTED:mailto:organizer@email.org
```
**valid invitation ICS**
```
ATTENDEE;CN=participant 1;CUTYPE=INDIVIDUAL;PARTSTAT=NEEDS-ACTION;R
 OLE=REQ-PARTICIPANT;RSVP=TRUE:mailto:participant1@email.org
ORGANIZER;CN=organizer:mailto:organizer@email.org
```
It shows that apple iOS handles the organizer in an extra ATTENDEE attribute while Nextcloud Calendar App puts the Organizer into the same ATTENDEE attribute.

**Comment by Lionel-cl** [comment]
Hello,
with:
- NC 24.0.5
  - calendar: 3.5.0
  - contacts: 4.2.1
  - contactsinteraction: 1.5.0
  - dashboard: 7.4.0
  - dav: 1.22.0
  

I checked this morning :
- no problem with google calendar
- ok with ios calendar but style not so good.  the buttons (accept, Decline, may be) are one above the other (in column) and not in line
- Problem with Teams : no button, no link, nothing to answer

Thanks for your action.

**Comment by throwabird** [comment]
I can also confirm this issue. Sending the invitation from the calendar web interface works perfectly fine. Sending it from iOS breaks the invite. For me I still have the buttons and link, however the link only contains:
```html
<a href=""></a>
```
![Screenshot_20221123_020653](https://user-images.githubusercontent.com/88376487/203451189-79547b3c-c80f-4440-9cfb-92ca72e4e1de.png)

When I press the invite accept/decline/more options button I get:
![Screenshot_20221123_020236](https://user-images.githubusercontent.com/88376487/203451065-28881882-17d2-4633-952e-82c07926ed65.png)

I am using:
* Nextcloud 25.0.1
* Calendar 4.1.0
* Postgres
* Redis

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+

**Comment by britzke** [comment]
Nextcloud 25.0.3
Calendar 4.2.1

The link is broken, too.

Using the  Accept button, everything works fine. But using the "more options" link below and selecting "accept", I get the same error Message.

<img width="673" alt="Bildschirmfoto 2023-01-24 um 19 07 47" src="https://user-images.githubusercontent.com/2329617/214373471-0066163a-eb65-4679-9b88-8cb26fd0b755.png">

**Comment by britzke** [comment]
No it is not as easy reproducible. Some times the second and third click works well, too.  I am working on it, to get the rule, where the error occurs.

BTW: the original error which I announced in 2021 states that "invitation contains buggy link instead of response controls". The invalid link is also there but the correct response controls are, now there. And they are working (most of the times). And may be that it is a total different error.

**Comment by SebastianKrupinski** [comment]
Tested on version 30. Work correctly.
