### ISSUE TITLE
NC 21 with PHP 8.x Internal Server Error

### ISSUE THREAD

**Issue by Jolopu** [nextcloud/server#26034]
Steps to reproduce
1. NC 21
2. PHP 8.0.2

Expected behaviour
Login into server

Actual behaviour
Internal server error when trying to login. After switching back to PHP 7.4 everything is ok. 

Server configuration
Debian

Web server:
Apache

Database:
MariaDB

PHP version:
8.0.2

Nextcloud version:
21.0.0

Updated from an older Nextcloud/ownCloud or fresh install:
19.x

Log:

Error	index	Exception: Call to undefined function OC\Files\Storage\disk_free_space()
/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/base.php - line 993:

OC\Route\Router->match()

/var/www/clients/client311/web3228/web/cloud.mysite.com/index.php - line 37:

OC::handleRequest()

Verursacht durchError: Call to undefined function OC\Files\Storage\disk_free_space()
/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/Files/Storage/Wrapper/Quota.php - line 111:

OC\Files\Storage\Local->free_space()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/Files/Storage/Wrapper/Wrapper.php - line 335:

OC\Files\Storage\Wrapper\Quota->free_space()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/legacy/OC_Helper.php - line 530:

OC\Files\Storage\Wrapper\Wrapper->free_space()

/var/www/clients/client311/web3228/web/cloud.mysite.com/apps/files/lib/Controller/ViewController.php - line 148:

OC_Helper::getStorageInfo()

/var/www/clients/client311/web3228/web/cloud.mysite.com/apps/files/lib/Controller/ViewController.php - line 197:

OCA\Files\Controller\ViewController->getStorageInfo()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/AppFramework/Http/Dispatcher.php - line 218:

OCA\Files\Controller\ViewController->index()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/AppFramework/Http/Dispatcher.php - line 127:

OC\AppFramework\Http\Dispatcher->executeController()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/AppFramework/App.php - line 157:

OC\AppFramework\Http\Dispatcher->dispatch()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/private/Route/Router.php - line 302:

OC\AppFramework\App::main()

/var/www/clients/client311/web3228/web/cloud.mysite.com/lib/base.php - line 993:

OC\Route\Router->match()

/var/www/clients/client311/web3228/web/cloud.mysite.com/index.php - line 37:

OC::handleRequest()

**Comment by Jolopu** [comment]
Dieser Fehler ist auch bei NC 21.0.1 noch immer präsent. Der Webserver wirft diesbezüglich keine Fehler aus. So wie es aussieht handelt es sich um einen NC bug.

**Comment by Jolopu** [comment]
Der Fehler tritt übrigens nur in der Dateiansicht auf. Aktivität, Fotos, Kontakte, Kalender usw. funktioniert alles. Man kann aber nicht in die Einstellungen rein. Es kommt folgende Fehlermeldung:

Interner Serverfehler
Der Server konnte die Anfrage nicht fertig stellen. Sollte dies erneut auftreten, sende bitte die nachfolgenden technischen Einzelheiten an Deinen Server-Administrator. Weitere Details können im Server-Protokoll gefunden werden.

Technische Details
Entfernte Adresse: 84.17.53.167
Anfragekennung: YHCmOzhmOVA@JQKV0-38AQAICAA

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3 with PHP7.4? If not, please close this issue. Thanks! :)

**Comment by Jolopu** [comment]
This issue is only valid with PHP8.x.
I updated NC to 21.0.3 and the issue persists with PHP 8.0.2.
I have also a test fresh install of NC22.0.0 beta 4. It has the same issue.
It runs on Linux 4.19.0-16-amd64 x86_64 MariaDB 10.3.28
If it helps I can provide you with admin access and FTP access to have a look into it.




If you

**Comment by andyxheli** [comment]
@szaimen yes issue still remains with 21.0.3

**Comment by Jolopu** [comment]
Issue still remains with NC 21.0.4

**Comment by Ravisdo** [comment]
> Issue still remains with NC 21.0.4
Same issue

4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64 GNU/Linux
PHP 8.0.8
NC 21.0.3

**Comment by Jolopu** [comment]
Just updated to 21.1.1
Issue still persists.

**Comment by tardar** [comment]
On the update to 22.2.3 the problem still persists.

**Comment by szaimen** [comment]
This should be fixed with #29758. Backport is in https://github.com/nextcloud/server/pull/29799

**Comment by Jolopu** [comment]
Confirmed. I applied this patch to my installation and the issue is resolved:
https://github.com/nextcloud/server/commit/152e2bfdaa2cc860b3fb456d6a9bc675c00e6b39
