### ISSUE TITLE
Updater problem with permissions trying to update from 10.0.1 to 10.0.2

### ISSUE THREAD

**Issue by jmartin17** [nextcloud/server#2604]
### Steps to reproduce
1.  
2.
3.

### Expected behaviour
Tell us what should happen
should have run update to Nextcloud 10.0.2
### Actual behaviour
Tell us what happens instead
Got the following permission errors and don't know the command to change the permissions?

Check for write permissions
The following places can not be written to   /snap/nextcloud/173/htdocs/updater/../.
    /snap/nextcloud/173/htdocs/updater/../.htaccess
    /snap/nextcloud/173/htdocs/updater/../.user.ini
    /snap/nextcloud/173/htdocs/updater/../3rdparty/.
    /snap/nextcloud/173/htdocs/updater/../3rdparty/.gitignore
    /snap/nextcloud/173/htdocs/updater/../3rdparty/LICENSE INFO
    /snap/nextcloud/173/htdocs/updater/../3rdparty/README.md
    /snap/nextcloud/173/htdocs/updater/../3rdparty/autoload.php
    /snap/nextcloud/173/htdocs/updater/../3rdparty/bantu/.
    /snap/nextcloud/173/htdocs/updater/../3rdparty/bantu/ini-get-wrapper/.
 **.
.       too many to list....
.**
    /snap/nextcloud/173/htdocs/updater/../updater/.
    /snap/nextcloud/173/htdocs/updater/../updater/index.php
    /snap/nextcloud/173/htdocs/updater/../version.php

### Server configuration
**Operating system**:

**Web server:**

**Database:**

**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by kdo-razer** [comment]
same here... running Nextcloudbox out oh the box...

**Comment by LollenJumplan** [comment]
I'm experiencing the same issure while trying to go 10.0.1 -> 10.0.2 through the web updater. I remember setting the permissions according to the NC10 admin manual, so everything should be in working order.

**Comment by LollenJumplan** [comment]
I was able to circumvent the problem.
Before upgrading, I did a chown -R www-data: /var/www/nextcloud
(only chowning the necessary files would probably be enough, but whatever)
Then I let it upgrade, and after that I ran the script for strong directory permissions again:
https://docs.nextcloud.com/server/10/admin_manual/installation/installation_wizard.html#setting-strong-directory-permissions
That way you don't keep possibly insecure permissions after the upgrade.

**Comment by jmartin17** [comment]
I don't know what changed but when I sign on the my NextCloudBox I see Version 11.0 stable installed completely unattended.

**Comment by nickvergessen** [comment]
So the problem is gone now?

**Comment by jmartin17** [comment]
Yes, for me it is gone.
