### ISSUE TITLE
Double text string in information

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#26043]
When an error occurs, there is a double text string: `An exception occurred while executing a query:`.

![obraz](https://user-images.githubusercontent.com/47037905/110599988-bd350700-8183-11eb-9fb9-67b57f446fab.png)

**Nextcloud version:** (see Nextcloud admin page)
21.0.0

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by Valdnet** [comment]
I don't know because I can't make this error.
