### ISSUE TITLE
Refusal to create a link in the navigation panel

### ISSUE THREAD

**Issue by Fastereus** [nextcloud/server#26054]
It would be nice to be able to disable link creation in the "places" panel, this is very inconvenient if I want to sync several different folders [Image](https://drive.google.com/open?id=1bUyaLNTWSSYG5e6jer8DtBH0LgEuVrlI)

**Comment by kesselb** [comment]
Context missing, Image is private => needs info

**Comment by Fastereus** [comment]
Uploaded the picture to another place:
[Image at new hosting](https://ibb.co/pzjs6Zt)

**Comment by kesselb** [comment]
https://github.com/nextcloud/desktop/issues is the right repository. Please create a new report over there. Try to include as much information as possible. Make it easy for other people to understand what you are talking about. Upload images directly to GitHub. Thanks :+1:
