### ISSUE TITLE
How can I wipe all users files?

### ISSUE THREAD

**Issue by kasperireland** [nextcloud/server#26055]
Hi there, I currently use the latest version of Nextcloud and was wondering how I can clear every single user's files at once, aka delete all their files with the click of a button or two. Thanks!

**Comment by skjnldsv** [comment]
If you want to reset all your users data, the fastest would be probably to remove the files locally and do an `occ files:scan --all` Might take a while though.
If you want to remove the users from the database you can bulk-process them from an occ command (see docs)
