### ISSUE TITLE
Who created file?- activity empty

### ISSUE THREAD

**Issue by giovannixyz** [nextcloud/server#26065]
Why I cannot see who created file in Nextcloud web interface?
Not as admin or as normal user. 
Under activity is empty
![image](https://user-images.githubusercontent.com/3385978/110795358-05812180-8277-11eb-8609-25683c7baeb8.png)

**Comment by Spartachetto** [comment]
A lot of information is missing.

Does it happen for all the files or just some? Can you provide any clue to try to reproduce the issue? Which Nextcloud version are you using?

In addition, did you consider that if this is a configuration issue you could seek for help in the user forum help.nextcloud.com?

**Comment by giovannixyz** [comment]
I found out that only on files I created- Activity is populated. Login as admin on all other files under activity everthing is empty.
Is this configuration problem?
I hope this is not normal feature?

**Comment by Spartachetto** [comment]
I am not sure I get what you mean. Each user sees his/her own activity: what he did and what other users shared with him.

You could be interested in this app: https://apps.nextcloud.com/apps/files_trackdownloads . Not sure if it fully covers your needs

**Comment by giovannixyz** [comment]
In any document system or sharing system (Dropbox, Google Drive, SharePoint, Windows FileShare, etc.) you can see who created or at least modified a file - as a normal end user.
In our Nextcloud configuration, I only see files that I have uploaded. For all other files, there is nothing to see under activity.
Even when I log in as admin, nothing is visible under activity for files I haven't uploaded.

I hope this is not normal behaviour and I have problems with the configuration?

**Comment by Spartachetto** [comment]
In Nextcloud you see the files you have access to. If a file belongs to an user or it is shared with that user then he can see the activity both in the activity app and in the activity tab of the single file.

An example: **Alice** shares the file _foo.txt_ with **Bob** and **Bob** modifies it

**Comment by nmolinski** [comment]
I can confirm I have the same issue as @giovannixyz with files uploaded to an external storage. 

I am admin to my server and I can see activity to files on my server's native filesystem. Unfortunately, all files that are uploaded to my external NAS do not feature any file history (see attached). Where is file history stored? Would this be in a db on the native filesystem, or, does this try to create a activity log in the external NAS for external files?

I am running the nextcloud snap on Ubuntu Server 20.04. 

![Selection_999(762)](https://user-images.githubusercontent.com/10121517/118994148-15db0a00-b954-11eb-9d56-d73825971133.png)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)

**Comment by giovannixyz** [comment]
This issue is for Public folder extensions and it is still issue.
But it is not problem of NC server but Public folder, So I will close issue.

**Comment by giovannixyz** [comment]
Public folder issue not Server.
