### ISSUE TITLE
General error: 2006 MySQL server has gone away

### ISSUE THREAD

**Issue by adamlove86** [nextcloud/server#2607]
### Steps to reproduce
Pressed the update to 10.0.2 button on nextCloud page that looks similar to the login page.
I wonder if this is due to me having the snap version?
Let me know if you need any more info.

### Expected behaviour
Should update to 10.0.2 smoothly

### Actual behaviour
Error message as per below

### Server configuration
Ubuntu 14 image on Dreamcompute. 

**Web server:**
Dreamcompute

**Database:**
mySQL that was included in the snap image.
**PHP version:**

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Updated from an older Nextcloud/ownCloud or fresh install:**
Fresh

**Where did you install Nextcloud from:**
Snap image

**Signing status:**
Not sure what this is, but if you need it let me know the details and I'll find it.
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```
</details>

**List of activated apps:**
Nothing that isn't in the apps section (no manual installs of owncloud apps etc)
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your Nextcloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)
<details>
<summary>LDAP config</summary>

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your Nextcloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```
</details>

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
<details>
<summary>Web server error log</summary>
```
Insert your webserver log here
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
Insert your Nextcloud log here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log
c) ...
```
</details>

**Comment by LukasReschke** [comment]
@jospoortvliet Yours. No idea about the snap.

**Comment by adamlove86** [comment]
Strange. It worked today when I tried to get the error logs to show - after many tries & restarts yesterday. I'd also found the /snap/nextcloud/169/my.cnf and changed max_allowed_packet= to 100M (instead of 10). Perhaps it needed some time to think & grumble about it before it actually implemented the 100M?
My question now - shall I drop it back down to 10, or even another amount?

**Comment by MorrisJobke** [comment]
> General error: 2006 MySQL server has gone away

We sadly can't do much here. The MySQL server is somehow gone. This is properly suited in the snaps repo (as it already is).

Closing here now.

@adamlove86 Thanks for the report anyways :)
