### ISSUE TITLE
Acitivty monitor for large link-shared file shows multiple download events

### ISSUE THREAD

**Issue by JohannesStroebel** [nextcloud/server#26075]
The Activity Page for a large via a link shared file (e.g. 500MB MP4) shows multiple download activities, even though it only got downloaded once. 

![NextcloudBugReport](https://user-images.githubusercontent.com/47080541/110830413-7a655300-8299-11eb-98d5-e06b0000790b.JPG)
The file in the picture got downloaded multiple times, but not as often as shown.

**Comment by skjnldsv** [comment]
Maybe the browser staled and started/resumed the download again ?
Iirc we're just iterating over the GET of the file, so we can't really determine what went wrong in between :/
