### ISSUE TITLE
Nextcloud 11 RC1 slow loading after update from Nextcloud 10 via the admin panel.

### ISSUE THREAD

**Issue by ruscogit** [nextcloud/server#2608]
### Steps to reproduce
1. Update Nextcloud to Beta 11 RC1
2. Navigate to Nextcloud installation using Firefox

### Expected behaviour
Loading quickly and without transfer issues.

### Actual behaviour
It seems to hiccup a lot when trying to transfer data to the web browser. Image example. 
![example](https://cloud.githubusercontent.com/assets/13407145/21077817/1665ef3a-bf26-11e6-99de-6f928e9e2b9f.gif)
It does load and render the page fine, but it takes 10-12 seconds instead of 2 or 3.

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** mysql

**PHP version:** 7

**Nextcloud version:**  11 RC1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated from latest nextcloud 10 stable release.

**Where did you install Nextcloud from:** In the admin panel via the updater.

**Signing status:**
<details>
<summary>Signing status : No errors have been found.</summary>
</details>
**Are you using external storage, if yes which one:** no

**Are you using encryption:** it is enabled

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:**
Firefox
**Operating system:**
Windows 10
#### Web server error log
<details>

**Comment by LukasReschke** [comment]
Could you post the link to your instance so we can check the caching headers?

**Comment by ruscogit** [comment]
https://rusco.me/storage/ 

Thanks!

**Comment by rullzer** [comment]
I can't reproduce that here. It is snappy....

**Comment by ruscogit** [comment]
I solved this issue by clearing my server cache with the following command.

`free && sync && echo 3 > /proc/sys/vm/drop_caches && free`
