### ISSUE TITLE
Download link of audio file shared via public link is displayed also when 'hide download' option is enabled

### ISSUE THREAD

**Issue by fstorz** [nextcloud/server#26086]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Upload an audio file to Nextcloud
2. Click on the share icon for that file
3. Click on "Share Link"
4. Click on the 3 dots next to the entry "Share Link"
5. Enable the option "Hide download" in the popup
6. Open the copied link in a new tab
7. On the new tab, click on the 3 dots next to the "audio line"
8. Option to download the file is displayed

### Expected behaviour
When the option, to hide the download, is selected for a public link, the ui should not display a link to download the file.

### Actual behaviour
When the option, to hide the download, is selected for a public link, the ui displays a link to download the file.

### Server configuration

**Operating system:** Docker Image

**Nextcloud version:** 20.0.8

### Screenshots
***Create share link***
![image](https://user-images.githubusercontent.com/27813536/110921568-fbb2f900-831e-11eb-87e7-fc460d62ec91.png)
***Open Share link and download the file***
![image](https://user-images.githubusercontent.com/27813536/110921684-23a25c80-831f-11eb-9dcd-743e855ef64b.png)

**Comment by 1819Ranjith** [comment]
Don't send any messages ..
Any more

**Comment by fstorz** [comment]
Relevant code might be in [this](https://github.com/nextcloud/server/blob/master/apps/files_sharing/templates/public.php) file on line 66.
```
<?php if ($_['previewEnabled'] && substr($_['mimetype'], 0, strpos($_['mimetype'], '/')) == 'audio'): ?>
					<div id="imgframe">
						<audio tabindex="0" controls="" preload="none" style="width: 100%; max-width: <?php p($_['previewMaxX']); ?>px; max-height: <?php p($_['previewMaxY']); ?>px">
							<source src="<?php p($_['downloadURL']); ?>" type="<?php p($_['mimetype']); ?>" />
						</audio>
					</div>
				<?php else: ?>
```

The following audio tag attribute should be added when `$_['hideDownload']` is set.
`controlsList="nodownload"`

**Comment by szaimen** [comment]
Hi @fstorz Would you be able to create a PR for this? Would be great!
