### ISSUE TITLE
Possible security issue using Nextcloud Dashboard and OnlyOffice

### ISSUE THREAD

**Issue by IteDas** [nextcloud/server#26082]
### Steps to reproduce
1. Have 2 .xlsx files in same nextcloud folder
2. Edit them with differenct content
3. Open files from Recommended Files in Dashboard
4. Watch as Onlyoffice triggers between the two files while editing (only happens from Recommended Files)

### Expected behaviour
You shouldn't be able to access files unintended

### Actual behaviour
Random changes in between files

### Server configuration

**Operating system:** Debian Buster 64-bit 10.8

**Web server:** Apache

**Database:** mysql 20.5.5

**PHP version:** 7.14.15

**Nextcloud version:** (see Nextcloud admin page)

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:** Official Nextcloud Docker Container

**Comment by szaimen** [comment]
looks like https://github.com/nextcloud/server/issues/24889
