### ISSUE TITLE
[S3] 'verify_bucket_exists' instead of 'autocreate' in S3 config

### ISSUE THREAD

**Issue by tsnmcloud** [nextcloud/server#26093]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
Test according to documentation:
1. Configure `autocreate => true` as shown in S3 configuration
    Bucket is automatically created   => OK
2. Configure `autocreate => false` as shown in S3 configuration
    Bucket is automatically created => NOK
Test according to (intended implementation) from code:
3. Configure `verify_bucket_exists => true`
    Bucket is automatically created. => OK
4. Configure `verify_bucket_exists => `false`
    Bucket is automatically created. => NOK

### Expected behaviour
Configuration parameter 'autocreate' is consistently used for all object storage variations. and shoould behave according to given value.

### Actual behaviour
S3 configuration uses 'verify_bucket_exists` inconsistently to the other object store implementations (swift, azure,...)
False configurations have not the expected effect.

### Server configuration

**Operating system:**
Ubuntu 20.04
**Web server:**
Apache2
**Database:**
MySQL 8.0.20
**PHP version:**
Php8

**Nextcloud version:** (see Nextcloud admin page)
21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:**
Updates from 20.0.17

**Where did you install Nextcloud from:**
NextCloud package.

**Nextcloud configuration:**
```
<?php
$CONFIG = array (
  'objectstore' => 
  array (
    'class' => '\\OC\\Files\\ObjectStore\\S3',
    'arguments' => 
    array (
      'bucket' => 'test-bucket',
      'verify_bucket_exists'/'autocreate' => true,
      'key' => 'VHN***, 
      'secret' => 'NiZv9Z***',
      'hostname' => 'obs.eu-de.otc.t-systems.com',
      'port' => 443,
      'use_ssl' => true,
      'region' => 'eu-de',
      'use_path_style' => true,
    ),
  ),
```

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
