### ISSUE TITLE
External storages "blink" on the home file page

### ISSUE THREAD

**Issue by 1ndeed** [nextcloud/server#26107]
I mounted 3 `local` external storages. Functionally, they work perfectly. But since external storages "Check for changes
 On Every Direct Access". Every time I firstly enter my nextcloud homepage, which is the File. The three items just ... blink!!! They become black, then quickly become white again as if they blink. I know they are just refreshing database. But it's just so annoying. And it looks like a bug or something to other people's eyes. Just not elegant.

Please fix this. Thank you.

**Comment by szaimen** [comment]
Duplicate of https://github.com/nextcloud/server/issues/18685
