### ISSUE TITLE
Large federated shares are inaccessible and their size is "pending"

### ISSUE THREAD

**Issue by ford--prefect** [nextcloud/server#26108]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Have two Nextcloud instances, A and B, and have a folder of significant size (e.g. 100GB) in instance A
2. Share A/folder to instance B and accept incoming share on B
3. Instance B shows the share with size "pending" (which will never change) and when entering the share, a notification comes up: "this folder is temporarily not available".
(error notes are translated and might differ slightly)

### Expected behaviour
The share should be available for browsing, copying etc.

### Actual behaviour
The share is not available.

### Server configuration
I'm just a user on both systems, and have no admin or even server admin right, hence I cut the below info a bit short.
Also, the issue seems to be [version independent ](https://help.nextcloud.com/t/federated-shares-showing-size-of-pending-storage-is-temporarily-unnavailable/57826/11) and has been reported before in the user community.

**Operating system:**
(partly copied from the german user interface)
Nextcloud 20.0.4
Betriebssystem:	Linux 5.4.0-56-generic x86_64
Prozessor:	Intel(R) Xeon(R) CPU E5-1650 v2 @ 3.50GHz (6 cores)
Speicher:	62.78 GB
PHP 7.4.13
Maximale Größe zum Hochladen: 10 GB
database: mysql
Version: 10.3.27

When looking at that, maybe the "maximum upload size" of 10GB fits roughly to what size of folders can still be copied (and might also explain why others see the capping at other sizes, e.g. 1GB).
Größe: 143,7 MB

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by ford--prefect** [comment]
Since the instances in question are still on 20.0.9 I can confirm neither state. I'll report back as soon as the instances are updated (the timing is not my choice, it might take a while).
