### ISSUE TITLE
User edit action buttons

### ISSUE THREAD

**Issue by Valdnet** [nextcloud/server#26106]
Action buttons cover the last column of user settings in User Settings for Admin (Settings -> Users):

![obraz](https://user-images.githubusercontent.com/47037905/111064826-94c84800-84b6-11eb-920e-bb48b23aa77f.png)

This causes, for example, cutting off the warehouse occupation bar and obscuring a longer text value (other languages). The text is not complete (truncated):

![obraz](https://user-images.githubusercontent.com/47037905/111032462-a6551580-840c-11eb-9c55-944071565751.png)

![obraz](https://user-images.githubusercontent.com/47037905/111032583-372bf100-840d-11eb-90ae-efe8365aad2f.png)

**Nextcloud version:** (see Nextcloud admin page)
20.0.8

### Client configuration
**Browser:**
Firefox 86.0.1

**Comment by szaimen** [comment]
I think this changes based on the zoom level. It is just like the user settings were designed.
Maybe we should track this in https://github.com/nextcloud/server/issues/18561?

**Comment by Valdnet** [comment]
It's hard for me to say if the topics are related to the same problem. I only know one thing that this error should be corrected 😉.
