### ISSUE TITLE
serverinfo not working with "-" in db name

### ISSUE THREAD

**Issue by emiglio** [nextcloud/server#2611]
Hi,
 
### Steps to reproduce
1. Install NC 10.1 or 10.2 with a databasename with a "-" in the Name
2. Open Server info in Administration
3. see nothing :-)

### Expected behaviour
Tell us what should happen
You should see the Serverinfo

I already had a solution but it doesnt seem to be in the 10.2 Version:

https://github.com/nextcloud/serverinfo/issues/54

best emiglio

**Comment by MorrisJobke** [comment]
cc @schiessle

**Comment by MorrisJobke** [comment]
closing in favor of https://github.com/nextcloud/serverinfo/issues/54
