### ISSUE TITLE
External files not updateing.

### ISSUE THREAD

**Issue by wwwwiii** [nextcloud/server#26114]
### Steps to reproduce
1.Sync a new share
2. Updates files within the share
3. Force a sync
 sudo -u www-data php occ files:scan --all
 sudo -u www-data php occ files_external:notify 4

### Expected behaviour
Files are not being synchronised.

### Actual behaviour
Files not updateing

### Server configuration

**Operating system: Ubuntu 18 or ubuntu 20 lts

**Web server:** Nginx, php 7.4 

**Database:MariaDB

**PHP version:*php 7.4 

**Nextcloud version:** 20.4

**Updated from an older Nextcloud/ownCloud or fresh install:**

**Where did you install Nextcloud from:Orginal site.

Installations either quite new or few versions old.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)
