### ISSUE TITLE
Very annoying welcome message issue with data-user-displayname

### ISSUE THREAD

**Issue by oriolo** [nextcloud/server#26113]
Hi to all,
can you suggest me how to solve this encoding problem (letters with accents in data-user-displayname)?
it is present only on the welcome message, not anywhere.
Thanks a lot.

<img width="672" alt="Screen Shot 2021-03-15 at 08 40 01" src="https://user-images.githubusercontent.com/7412862/111119202-1fb64a80-856a-11eb-981a-0732656f33ae.png">

**Comment by skjnldsv** [comment]
cc @juliushaertl @eneiluj

**Comment by eneiluj** [comment]
@oriolo Thanks for the bug report.

@skjnldsv Problem is we've got something like
``` javascript
// there's a single quote in the name
user.displayName = 'my name\''
// somewhere, there's a translation 
const greeting = t('dashboard', 'Good morning, {n}', { n: user.displayName })
// in Vue template
<h2>{{ greeting }}</h2>
```

How could we solve that?
Easy solution would be to use `v-html` but it's not very safe :grin:.
Any clue?

**Comment by skjnldsv** [comment]
What about html decode?

**Comment by eneiluj** [comment]
@skjnldsv Thanks. Is there any html decode function included in a `@nc` package? If not, can I use this?
``` javascript
htmlDecode(s) {
	return s.replace(/&#(\d+);/g, (match, code) => {
		return String.fromCharCode(code)
	})
},
```

**Comment by juliushaertl** [comment]
This should already be possible with setting the escape option on the existing translate function like this: `t('foo', 'Hello, {s}', {s: 'Hello ê a \' s'}, null, { escape: false })`

It would not escape the HTML any longer but vue will just render this as a text and it would still be sanitized with DOMpurify.

**Comment by oriolo** [comment]
Hi, could you tell me which is the translate function on which I can apply what you mentioned? thanks.

**Comment by juliushaertl** [comment]
Those would be in https://github.com/nextcloud/server/blob/master/apps/dashboard/src/App.vue#L180-L198

**Comment by oriolo** [comment]
thanks

**Comment by oriolo** [comment]
@juliushaertl yes this is the App.vue source but Is there a way to modify some run-time files (php, js..) in order "to hack" the running code in the meanwhile the bug will be officially solved?
