### ISSUE TITLE
big federation shares remain in state "pending" and block access to "Shared" folder

### ISSUE THREAD

**Issue by ferdiga** [nextcloud/server#26112]
### Steps to reproduce
share a big folder with  complex structure

related to
https://github.com/nextcloud/server/issues/6707
but with complete / hopefully better description

### Expected behaviour
show up in target system WITH size immediately calculated

### Actual behaviour
share remains "pending" (forever?? as size is not calculated in time ?)
**Share folder is not accessible any more, spinning wheel forever**

it seems to me that this error message is related to this
[core] Warning: Login failed: 'me' (Remote IP: '196.xxx.xxx.xxx')

## Server configuration detail

**Operating system:** Linux 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64

**Webserver:** Apache/2.4.38 (Debian) (apache2handler)

**Database:** mysql 10.3.25

**PHP version:** 

7.3.19-1~deb10u1
Modules loaded: Core, date, libxml, openssl, pcre, zlib, filter, hash, Reflection, SPL, session, sodium, standard, apache2handler, mysqlnd, PDO, xml, apcu, bcmath, bz2, calendar, ctype, curl, dom, mbstring, fileinfo, ftp, gd, gettext, gmp, iconv, imagick, intl, json, ldap, exif, mysqli, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, apc, posix, readline, shmop, SimpleXML, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, wddx, xmlreader, xmlwriter, xsl, zip, Phar, Zend OPcache

**Nextcloud version:** 20.0.8 - 20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** 

**Where did you install Nextcloud from:** unknown

<details><summary>Signing status</summary>

Array
(
)

</details>

<details><summary>List of activated apps</summary>

```
Enabled:
 - accessibility: 1.6.0
 - activity: 2.13.4
 - admin_audit: 1.10.0
 - analytics: 3.4.1
 - announcementcenter: 4.0.1
 - apporder: 0.12.0
 - audioplayer: 3.1.0
 - bruteforcesettings: 2.0.1
 - calendar: 2.1.3
 - carnet: 0.23.8
 - circles: 0.20.7
 - cloud_federation_api: 1.3.0
 - comments: 1.10.0
 - contacts: 3.4.3
 - contactsinteraction: 1.1.0
 - dashboard: 7.0.0
 - dav: 1.16.2
 - deck: 1.2.5
 - external: 3.7.2
 - federatedfilesharing: 1.10.2
 - federation: 1.10.1
 - files: 1.15.0
 - files_automatedtagging: 1.10.1
 - files_external: 1.11.1
 - files_external_gdrive: 0.4.0
 - files_fulltextsearch: 20.0.1
 - files_fulltextsearch_tesseract: 20.0.1
 - files_pdfviewer: 2.0.1
 - files_photospheres: 1.20.1
 - files_rightclick: 0.17.0
 - files_sharing: 1.12.2
 - files_trashbin: 1.10.1
 - files_versions: 1.13.0
 - files_videoplayer: 1.9.0
 - fulltextsearch: 20.0.0
 - fulltextsearch_elasticsearch: 20.0.0
 - groupfolders: 8.2.0
 - integration_google: 0.1.10
 - issuetemplate: 0.7.0
 - logreader: 2.5.0
 - lookup_server_connector: 1.8.0
 - metadata: 0.13.0
 - nextcloud_announcements: 1.9.0
 - notes: 4.0.4
 - notifications: 2.8.0
 - oauth2: 1.8.0
 - ocr: 6.0.58
 - password_policy: 1.10.1
 - phonetrack: 0.6.7
 - photos: 1.2.3
 - previewgenerator: 3.1.1
 - privacy: 1.4.0
 - provisioning_api: 1.10.0
 - quickaccesssorting: 1.1.2
 - quicknotes: 0.6.3
 - quota_warning: 1.9.1
 - rainloop: 7.1.2
 - recommendations: 0.8.0
 - richdocuments: 3.7.17
 - richdocumentscode: 6.4.608
 - serverinfo: 1.10.0
 - settings: 1.2.0
 - sharebymail: 1.10.0
 - socialsharing_email: 2.1.0
 - spreed: 10.0.6
 - support: 1.3.0
 - survey_client: 1.8.0
 - suspicious_login: 3.2.1
 - systemtags: 1.10.0
 - tasks: 0.13.6
 - text: 3.1.0
 - theming: 1.11.0
 - theming_customcss: 1.8.0
 - twofactor_backupcodes: 1.9.0
 - updatenotification: 1.10.0
 - user_status: 1.0.1
 - user_usage_report: 1.4.2
 - viewer: 1.4.0
 - weather_status: 1.0.0
 - whiteboard: 0.0.3
 - workflow_ocr: 1.20.2
 - workflow_pdf_converter: 1.5.1
 - workflow_script: 1.5.1
 - workflowengine: 2.2.0
Disabled:
 - dashboardcharts
 - drawio
 - emlviewer
 - encryption
 - files_accesscontrol
 - files_downloadactivity
 - files_retention
 - firstrunwizard
 - mail
 - ocsms
 - ojsxc
 - printer
 - registration
 - user_ldap
 - wopi

```
</details>

<details><summary>Configuration (config/config.php)</summary>

```
{
    "instanceid": "***REMOVED SENSITIVE VALUE***",
    "passwordsalt": "***REMOVED SENSITIVE VALUE***",
    "datadirectory": "***REMOVED SENSITIVE VALUE***",
    "dbtype": "mysql",
    "version": "20.0.8.1",
    "dbname": "***REMOVED SENSITIVE VALUE***",
    "dbhost": "***REMOVED SENSITIVE VALUE***",
    "dbtableprefix": "oc_",
    "dbuser": "***REMOVED SENSITIVE VALUE***",
    "dbpassword": "***REMOVED SENSITIVE VALUE***",
    "debug": false,
    "installed": true,
    "enable_previews": true,
    "forcessl": true,
    "theme": "",
    "maintenance": false,
    "mail_smtpmode": "smtp",
    "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
    "mail_smtpport": "587",
    "mail_smtptimeout": 10,
    "loglevel": 2,
    "allow_local_remote_servers": true,
    "share_folder": "\/Shared",
    "trusted_domains": [
        "service.chricar.at"
    ],
    "mail_from_address": "***REMOVED SENSITIVE VALUE***",
    "mail_domain": "***REMOVED SENSITIVE VALUE***",
    "secret": "***REMOVED SENSITIVE VALUE***",
    "singleuser": false,
    "forceSSLforSubdomains": true,
    "trashbin_retention_obligation": "auto",
    "filelocking.enabled": "true",
    "filesystem_check_changes": 1,
    "mail_smtpauthtype": "PLAIN",
    "mail_smtpsecure": "tls",
    "mail_smtpauth": 1,
    "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
    "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
    "auth.bruteforce.protection.enabled": true,
    "overwriteprotocol": "https",
    "overwrite.cli.url": "https:\/\/service.chricar.at\/owncloud",
    "updater.release.channel": "stable",
    "memcache.local": "\\OC\\Memcache\\APCu",
    "memcache.locking": "\\OC\\Memcache\\Redis",
    "redis": {
        "host": "***REMOVED SENSITIVE VALUE***",
        "port": 6379,
        "password": "***REMOVED SENSITIVE VALUE***",
        "timeout": 1.5
    },
    "preview_max_x": 512,
    "preview_max_y": 512,
    "preview_max_scale_factor": 1,
    "preview_libreoffice_path": "\/usr\/bin\/libreoffice",
    "enabledPreviewProviders": [
        "OC\\Preview\\Image",
        "OC\\Preview\\MP3",
        "OC\\Preview\\TXT",
        "OC\\Preview\\PDF",
        "OC\\Preview\\Movie",
        "OC\\Preview\\Photoshop",
        "OC\\Preview\\TIFF",
        "OC\\Preview\\SVG",
        "OC\\Preview\\OpenDocument"
    ],
    "has_rebuilt_cache": true,
    "mysql.utf8mb4": true,
    "app_install_overwrite": [
        "files_clipboard",
        "files_accesscontrol",
        "issuetemplate",
        "dashboard",
        "files_external_gdrive",
        "ojsxc",
        "quickaccesssorting",
        "ocr",
        "files_fulltextsearch_tesseract"
    ],
    "0": {
        "verify_peer_off": true
    },
    "data-fingerprint": "2e5954a0f3c41d5dc2c0cd22b19dc1e0"
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** 

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

## Client configuration

**Browser:** Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36

**Operating system:** 

## Logs

<details><summary>Web server error log</summary>

```
Insert your web server log here 
```
</details>

<details><summary>Nextcloud log</summary>

```

[webdav] Fatal: Sabre\DAV\Exception\ServiceUnavailable:  at <<closure>>

 0. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Tree.php line 80
    OCA\DAV\Connector\Sabre\Directory->getChild("Temp_federation")
 1. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php line 976
    Sabre\DAV\Tree->getNodeForPath("files/gass/Shared/Temp_federation")
 2. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1678
    Sabre\DAV\Server->getPropertiesIteratorForPath("files/gass/Shared/Temp_federation", ["{DAV:}getlastm ... "], 1)
 3. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php line 1661
    Sabre\DAV\Server->writeMultiStatus(Sabre\Xml\Writer ... ]}, Generator {}, false)
 4. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php line 363
    Sabre\DAV\Server->generateMultiStatus(Generator {}, false)
 5. /var/www/owncloud/3rdparty/sabre/event/lib/WildcardEmitterTrait.php line 89
    Sabre\DAV\CorePlugin->httpPropFind(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 6. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php line 474
    Sabre\DAV\Server->emit("method:PROPFIND", [Sabre\HTTP\Requ ... }])
 7. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php line 251
    Sabre\DAV\Server->invokeMethod(Sabre\HTTP\Request {}, Sabre\HTTP\Response {})
 8. /var/www/owncloud/3rdparty/sabre/dav/lib/DAV/Server.php line 319
    Sabre\DAV\Server->start()
 9. /var/www/owncloud/apps/dav/lib/Server.php line 332
    Sabre\DAV\Server->exec()
10. /var/www/owncloud/apps/dav/appinfo/v2/remote.php line 35
    OCA\DAV\Server->exec()
11. /var/www/owncloud/remote.php line 167
    require_once("/var/www/ownclo ... p")

PROPFIND /owncloud/remote.php/dav/files/gass/Shared/Temp_federation
from 196.20.177.179 by gass at 2021-03-15T03:22:20+00:00
```
</details>

<details><summary>Browser log</summary>

Insert your browser log here, this could for example include:

	a) The javascript console log
	b) The network log
	c) ...
</details>

**Comment by ferdiga** [comment]
comments from Hetzner   translation below

ich:
... oder das Login wird geblockt, weil WEBDAV beim Transfer zu viele 
requests in zu kurzer Zeit schickt ?
Hetzner:
... danke für Ihre Recherche. Leider sind wir zu selbigen Issue gekommen, als wir das untersucht haben. Die verwendete Nextcloud Software wird nicht von uns entwickelt, daher sind uns hier die Hände gebunden und können nur ein Update abwarten.
Grundsätzlich empfehlen wir aber, nicht die WebDAV-Schnittstelle direkt zu nutzen, sondern immer die Weboberfläche oder einen der Clients, da diese Chunking einsetzen und Sie somit nicht an Softwareseitige Limits stoßen, vor allem bei diesen Datenmengen.

me:
... or the login is blocked because WEBDAV sends too many requests in too short a time during the transfer ?
Hetzner
... thank you for your research. Unfortunately, we came to the same issue when we investigated this. The Nextcloud software used is not developed by us, so our hands are tied here and we can only wait for an update.
However, we generally recommend that you do not use the WebDAV interface directly, but always the web interface or one of the clients, as these use chunking and you therefore do not come up against software limits, especially with this amount of data.

Translated with www.DeepL.com/Translator (free version)

**unfortunately this means that the federation feature is not working well enough for big installations**

**Comment by ferdiga** [comment]
BTW
https://docs.nextcloud.com/server/latest/developer_manual/client_apis/WebDAV/chunking.html
is chunking used for transfers of federation shares ???

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by ferdiga** [comment]
I have to wait until the provider of the target System updates to 21.x.x to answer your question
