### ISSUE TITLE
Non interactive app navigation entry

### ISSUE THREAD

**Issue by Henni** [nextcloud/server#2612]
I stumbled over a problem during the development of nextcloud/notes#28

There is currently no way to introduce entries to the app-navigation which aren't links.
I hotfixed this by duplicating code from core, introducing a new class `.nav-entry`:
[fix in notes](https://github.com/nextcloud/notes/blob/1324ff8f1760dc1c1dd19ab92169c2a4ce6e025b/css/notes.css#L17-L34)
[source in core/apps.css](https://github.com/nextcloud/server/blob/master/core/css/apps.css#L67-L88)

@nextcloud/designers what do you think? should we move this fix into core?

**Comment by skjnldsv** [comment]
Clearly!
I think we should add span to the a. So we can do whatever we want :)

**Comment by Henni** [comment]
@skjnldsv tried that. Only problem: `span` is also used for the navigation utils.
So simply adding `span` to the current rules would break the actions menu (see https://github.com/nextcloud/server/blob/master/core/css/apps.css#L191).

**Comment by skjnldsv** [comment]
Is it used directly after app-navigation?
If not we should be fine with  `> span`

**Comment by Henni** [comment]
@skjnldsv at least it is an issue in case of the [notes app](https://github.com/nextcloud/notes/blob/master/templates/main.php#L50)

Other apps **might** not be affected by simply using `> span`, but I think it is bad practice to apply such styles to anything else than a class.

**Comment by skjnldsv** [comment]
Yeah, i agree with you, let's go with a `.nav-entry` class :)

**Comment by eppfel** [comment]
If I remember correctly in the Mail app the account name is not a link. Might be worth a look...

**Comment by jancborchardt** [comment]
In the Mail app we did have the account name not being a link, by being a h2. But now even that is a link, opening the specific inbox of that account. :)

cc'ing other app devs @ChristophWurst @BernhardPosselt @georgehrke @raghunayyar @raimund-schluessler  probably makes sense to move this fix to core, right?

**Comment by BernhardPosselt** [comment]
Would make sense to check the use case and add an additional element (separator?)

**Comment by skjnldsv** [comment]
@jancborchardt there is a lot of "common" stuff we should rebuild and move to core, like he popover, or the nav entry for example.
it could be good to discuss a proper and universal way to implement stuff like this with css rules and html trees :)

**Comment by skjnldsv** [comment]
closed in #3024
