### ISSUE TITLE
TXT files not completely visible in web view.

### ISSUE THREAD

**Issue by tolotos-rgu** [nextcloud/server#26140]
Hi,

in version 20.0.7 the web view of txt files will not display the whole text if the lines are longer than the visible area. 
The long line runs out of the area and I found no option for an virtual line break.

Yours, Rüdiger

**Comment by lunar-debian** [comment]
I believe this is https://github.com/nextcloud/text/issues/1407
@tolotos-rgu There’s a workaround in the bug description.

**Comment by tolotos-rgu** [comment]
Yes your right. I close this duplicate.
