### ISSUE TITLE
Out of range value for column 'last_activity'

### ISSUE THREAD

**Issue by gpanders** [nextcloud/server#26156]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

I'm not sure how to reproduce this. I did `docker pull nextcloud:20.0-fpm-alpine` today to update the Docker minor version to match my installation and now when I log in I get a server error. The log file shows this:

```
{"reqId":"1dImoGmEOPz3ZFnNb1m4","level":3,"time":"2071-05-02T03:31:52+00:00","remoteAddr":"172.24.0.2","user":"gpanders","app":"index","method":"POST","url":"/login","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_authtoken` (`uid`, `login_name`, `public_key`, `private_key`, `password`, `name`, `token`, `type`, `remember`, `last_activity`, `last_check`, `version`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"gpanders\", \"gpanders\", \"-----BEGIN PUBLIC KEY----- OMITTED\", \"Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko\\/20100101 Firefox\\/86.0\", \"b00cb70cef58eb885dbbac3eeddcd5346e27776f2f0e1606a5169f0bec12c7e499f1840693d48846af1d05f080c7a8132705ef1190950ddb2d935626a6c6c452\", 0, 1, -1097204168, -1097204168, 2]:\n\nSQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'last_activity' at row 1"
```

It looks like the value being inserted for the `last_activity` column is `-1097204168` and is failing validation. I don't know where this number comes from.

I've done quite a bit of digging around trying to figure this out, but unfortunately I am a total noob when it comes to PHP and only know a little SQL. I did see this though:

```
$ php occ user:info gpanders
  - user_id: gpanders
  - display_name: Gregory Anders
  - email: REDACTED
  - cloud_id: REDACTED
  - enabled: true
  - groups:
    - admin
    - users
  - quota: none
  - last_seen: 1935-03-26T21:03:52+00:00
  - user_directory: /var/www/html/data/gpanders
  - backend: Database
```

The `last_seen` key says I was last seen way back in 1935, so maybe that has something to do with it? I don't know how to reset that though.

### Expected behaviour

I should be able to log in.

### Actual behaviour

Logging in gives an Internal Server Error. See problem description above.

### Server configuration

**Operating system:**

Raspbian, with Nextcloud running in Docker.

**Web server:**

Nginx

**Database:**

MariaDB

**PHP version:**

7.4.16

**Nextcloud version:** (see Nextcloud admin page)

20.0.8.1

**Updated from an older Nextcloud/ownCloud or fresh install:** Updated

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

Can't log in

</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.4.3
  - contactsinteraction: 1.1.0
  - dav: 1.16.2
  - end_to_end_encryption: 1.6.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - twofactor_totp: 5.0.0
  - twofactor_u2f: 6.1.0
  - updatenotification: 1.10.0
  - viewer: 1.4.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - dashboard
  - encryption
  - files_external
  - mail
  - notes
  - spreed
  - survey_client
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "***REMOVED SENSITIVE VALUE***",
            "port": 6379,
            "password": "***REMOVED SENSITIVE VALUE***"
        },
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.gpanders.com"
        ],
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "http:\/\/cloud.gpanders.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "maintenance": false,
        "theme": "",
        "loglevel": 2,
        "overwriteprotocol": "https",
        "twofactor_enforced": "true",
        "twofactor_enforced_groups": [
            "users"
        ],
        "twofactor_enforced_excluded_groups": [],
        "memcache.distributed": "\\OC\\Memcache\\Redis",
        "trashbin_retention_obligation": "30, 90",
        "mail_smtpmode": "smtp",
        "mail_smtpsecure": "tls",
        "mail_sendmailmode": "smtp",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "587",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***"
    }
}

```
</details>

**Are you using external storage, if yes which one:** No

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

### Client configuration
**Browser:** Mozilla Firefox

**Operating system:** macOS

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
```
{"reqId":"1dImoGmEOPz3ZFnNb1m4","level":3,"time":"2071-05-02T03:31:52+00:00","remoteAddr":"172.24.0.2","user":"gpanders","app":"index","method":"POST","url":"/login","message":{"Exception":"Doctrine\\DBAL\\Exception\\DriverException","Message":"An exception occurred while executing 'INSERT INTO `oc_authtoken` (`uid`, `login_name`, `public_key`, `private_key`, `password`, `name`, `token`, `type`, `remember`, `last_activity`, `last_check`, `version`) VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)' with params [\"gpanders\", \"gpanders\", \"-----BEGIN PUBLIC KEY----- OMITTED\", \"Mozilla\\/5.0 (Macintosh; Intel Mac OS X 10.15; rv:86.0) Gecko\\/20100101 Firefox\\/86.0\", \"b00cb70cef58eb885dbbac3eeddcd5346e27776f2f0e1606a5169f0bec12c7e499f1840693d48846af1d05f080c7a8132705ef1190950ddb2d935626a6c6c452\", 0, 1, -1097204168, -1097204168, 2]:\n\nSQLSTATE[22003]: Numeric value out of range: 1264 Out of range value for column 'last_activity' at row 1"
```
```
</details>

**Comment by gpanders** [comment]
I was able to find where the source of the `last_seen` entry in `occ user:list` comes from:

```
MariaDB [nextcloud]> select * from oc_preferences where userid = 'gpanders' and configkey = 'lastLogin';
+----------+-------+-----------+-------------+
| userid   | appid | configkey | configvalue |
+----------+-------+-----------+-------------+
| gpanders | login | lastLogin | -1097204168 |
+----------+-------+-----------+-------------+
```

I tried updating this manually but when I try to login I still get the server error and the `lastLogin` value in the `oc_preferences` table is negative again. So it's being written by something else.

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.2? If not, please close this issue. Thanks! :)

**Comment by gpanders** [comment]
I'm not sure, I couldn't get Nextcloud back up in running because of this error so I just nuked the database and started over. I'll close it since I can't reproduce it anymore.

**Comment by metala** [comment]
I have just upgraded the docker image from 20.0 -> 21.0 and got this error. The setup is similar -> armv7, Asus Thinkerboard, running Nextcloud in Docker. I will look into it.
