### ISSUE TITLE
update 19.0.3> 20.0.7 was unsuccessful. 

### ISSUE THREAD

**Issue by perina** [nextcloud/server#26157]
Doctrine\DBAL\Schema\SchemaException: The table with name 'perinane_nc2.nc_user_status' already exists.

**Comment by j-ed** [comment]
Duplicate of https://github.com/nextcloud/server/issues/24217

BTW, this is the bug and feature tracker of the developers only. The [Nextcloud help forum](https://help.nextcloud.com/) exists to help you getting general problems solved. Next time please raise this kind of question in the forum first 😉
