### ISSUE TITLE
首次资源请求canceled

### ISSUE THREAD

**Issue by zhengxianyu** [nextcloud/server#26158]
每个nextcloud模块，Network勾选上Preserve log，首次加载资源，总是显示canceled
![image](https://user-images.githubusercontent.com/12377531/111423619-88005a00-872b-11eb-888a-f43329a48b7f.png)

**Comment by Spartachetto** [comment]
Via Google translate I get:
For each nextcloud module, check the Preserve log on the Network, and load the resource for the first time, always show canceled 

Hope that helps

**Comment by skjnldsv** [comment]
Can you give us where did this request originated from? Is it an original document GET, or an xhr request?
