### ISSUE TITLE
NC21: Memleak when do "occ db:add-missing-indices"

### ISSUE THREAD

**Issue by TheRaven500** [nextcloud/server#26154]
### Steps to reproduce
1. sudo -u www-data ./occ db:add-missing-indices

### Expected behaviour
Database should be fixed

### Actual behaviour
Memory grow up and up until it crashes

### Server configuration

**Operating system:**
Debian 10
**Web server:**
Abache2
**Database:**
Mariadb
**PHP version:**
7.4
**Nextcloud version:** (see Nextcloud admin page)
21.0.0.18
**Updated from an older Nextcloud/ownCloud or fresh install:**
Updated from 20.0.0.8

Never had problems before. I think it is a problem with NC21.

![peng](https://user-images.githubusercontent.com/63654062/111383948-32836900-86a9-11eb-8781-958c6ed3deac.png)
![peng2](https://user-images.githubusercontent.com/63654062/111384031-547ceb80-86a9-11eb-8f80-465f3c5a6c2b.png)

**Comment by kesselb** [comment]
Logs?

**Comment by TheRaven500** [comment]
What for logs are needed?
I don't think that you see a "memleak" in the "normal" logs. Maybe in a debug log?

**Comment by TheRaven500** [comment]
The bug is still present in NC21.0.1 RC1.
What logs are needed?

**Comment by vorlon** [comment]
I stumbled upon the same issue after a fresh upgrade to 21.0.1 from 20.x. Then I noticed that even just calling `occ` without arguments leads to an OOM situation.
This might be the same as described in #26184 . In my case commenting out
`'memcache.local' =>  '\\OC\\Memcache\\APCu'` in config.php helped to succesfully run `occ` again.

**Comment by TheRaven500** [comment]
Ha! Thx! Has also worked for me. Job completet in few seconds after commenting out the cache option in config.php!

**Comment by caugner** [comment]
ping @rullzer and @MorrisJobke as top committers in the [Memcache namespace](https://github.com/nextcloud/server/commits/master/lib/private/Memcache). Do you have any guess what might cause memory leaks when running `occ` with enabled APCu cache?

**Comment by kesselb** [comment]
Closing in favour of https://github.com/nextcloud/server/issues/26184
