### ISSUE TITLE
New updater fails due to workflowengine

### ISSUE THREAD

**Issue by augustseptember** [nextcloud/server#2617]
### Steps to reproduce
1. Start the update (from 10.0.1 to 10.0.2) from admin area in web interface
2. Select to not use the occ script

### Expected behaviour
Update should finish without errors

### Actual behaviour
Update fails with "workflowengine: Failed to enable app workflowengine"

On the command line with occ the update finishes at least but has the same error as output.

### Server configuration
**Operating system**:
Ubuntu 16.04.
**Web server:**
Apache 2.4.18
**Database:**
10.0.28-MariaDB

**PHP version:**
7.0.8

**Nextcloud version:** (see Nextcloud admin page)
10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
updated from 10.0.1

**Where did you install Nextcloud from:**

**Signing status:**
<details>
<summary>Signing status</summary>

```
Login as admin user into your Nextcloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.

No errors have been found.

```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your Nextcloud installation folder
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

**Comment by LukasReschke** [comment]
Can you post your log file?

**Comment by augustseptember** [comment]
Not quite sure if this is all, because the logfiles are so confusing:

`{"reqId":"5wJrOms8oTP78ZlaUAg3","remoteAddr":"178.12.108.146","app":"core","message":"starting upgrade from 9.1.1.5 to 9.1.2.2","level":0,"time":"2016-12-12T08:26:05+01:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=An1DdBkYIR14PwEFcxI2BiJ9A2BFNx1xHQYqDCAbGBM%3D%3AR%2F1BrBnVHIQc1ZERG5iX2ntCviEFXnojKQVbL7rzEUM%3D","user":"--","version":"9.1.1.5"}
{"reqId":"5wJrOms8oTP78ZlaUAg3","remoteAddr":"178.12.108.146","app":"workflowengine","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app workflowengine\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Installer.php(535): OC\\\\Installer::installShippedApp('workflowengine')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(289): OC\\\\Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.2.2', '9.1.1.5')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/core\\\/ajax\\\/update.php(194): OC\\\\Updater->upgrade()\\n#4 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Installer.php\",\"Line\":571}","level":3,"time":"2016-12-12T08:26:28+01:00","method":"GET","url":"\/core\/ajax\/update.php?requesttoken=An1DdBkYIR14PwEFcxI2BiJ9A2BFNx1xHQYqDCAbGBM%3D%3AR%2F1BrBnVHIQc1ZERG5iX2ntCviEFXnojKQVbL7rzEUM%3D","user":"--","version":"9.1.1.5"}
{"reqId":"tAmjNcmHkxcIjDoAZC76","remoteAddr":"","app":"core","message":"starting upgrade from 9.1.1.5 to 9.1.2.2","level":0,"time":"2016-12-12T08:27:41+01:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}
{"reqId":"tAmjNcmHkxcIjDoAZC76","remoteAddr":"","app":"workflowengine","message":"Exception: {\"Exception\":\"OC\\\\HintException\",\"Message\":\"Failed to enable app workflowengine\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Installer.php(535): OC\\\\Installer::installShippedApp('workflowengine')\\n#1 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(289): OC\\\\Installer::installShippedApps(true)\\n#2 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Updater.php(151): OC\\\\Updater->doUpgrade('9.1.2.2', '9.1.1.5')\\n#3 \\\/var\\\/www\\\/nextcloud\\\/core\\\/Command\\\/Upgrade.php(292): OC\\\\Updater->upgrade()\\n#4 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Command\\\/Command.php(259): OC\\\\Core\\\\Command\\\\Upgrade->execute(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#5 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(844): Symfony\\\\Component\\\\Console\\\\Command\\\\Command->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#6 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(192): Symfony\\\\Component\\\\Console\\\\Application->doRunCommand(Object(OC\\\\Core\\\\Command\\\\Upgrade), Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#7 \\\/var\\\/www\\\/nextcloud\\\/3rdparty\\\/symfony\\\/console\\\/Application.php(123): Symfony\\\\Component\\\\Console\\\\Application->doRun(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#8 \\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Console\\\/Application.php(146): Symfony\\\\Component\\\\Console\\\\Application->run(Object(Symfony\\\\Component\\\\Console\\\\Input\\\\ArgvInput), Object(Symfony\\\\Component\\\\Console\\\\Output\\\\ConsoleOutput))\\n#9 \\\/var\\\/www\\\/nextcloud\\\/console.php(98): OC\\\\Console\\\\Application->run()\\n#10 \\\/var\\\/www\\\/nextcloud\\\/occ(11): require_once('\\\/var\\\/www\\\/nextcl...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/nextcloud\\\/lib\\\/private\\\/Installer.php\",\"Line\":571}","level":3,"time":"2016-12-12T08:27:49+01:00","method":"--","url":"--","user":"--","version":"9.1.1.5"}`

**Comment by mercury1337** [comment]
I have the same issue - is there a solution available?

**Comment by augustseptember** [comment]
Same occurs when updating from NC 11.0 to 11.0.1. 
That means it was not possible to update with the web-updater. Only on commandline with "occ upgrade" it works.

**Comment by LukasReschke** [comment]
cc @nickvergessen

**Comment by nickvergessen** [comment]
This happens when the update was already done before, but then a backup was restored without clearing the database. Therefor the database is in an inconsistent state, where it thinks the app is not enabled, but the database tables already exist.

You can confirm this, by running the following script: https://gist.github.com/nickvergessen/94b57082a5ab83e47bbbd1bef6d13f66

If that is what you did, you can replace `lib/private/Installer.php`:
```php
				throw new HintException(
					'Failed to enable app ' . $app,
					'Please ask for help via one of our <a href="https://nextcloud.com/support/" target="_blank" rel="noreferrer">support channels</a>.',
					0, $e
				);
```
with:
```php
OC_DB::updateDbFromStructure("$appPath/appinfo/database.xml");
```
and then the update should work.

**Comment by jcklpe** [comment]
Having a similar issue but I'm not quite experienced enough with PHP to understand your instructions @nickvergessen   am I just replacing that quoted bit of text with the second bit of text?

**Comment by nickvergessen** [comment]
In case there is still a problem, please ask for help in the forum (or open a new issue) instead of a two year old issue.
