### ISSUE TITLE
Transfer/redirect file sharing links to other files/folders

### ISSUE THREAD

**Issue by hul51u** [nextcloud/server#26180]
Sometimes I'd like to redirect my nextcloud sharing link to another file/folder.
At the moment you have to overwrite the shared file to keep the sharing link address. Or you have to share a folder and update the files contained.

In sharing options could be added "redirect/transfer link (to another file/folder)".

I hope this could be implemented to Nextcloud some day. Thanks

**Comment by szaimen** [comment]
As this sounds like a nice feature, the requests for this are quite low. Currently there are no plans to implement such a feature. Thus I will close this ticket for now. This does not mean we don't want this feature, but it is simply not on our roadmap for the near future. If somebody wants to implement this feature nevertheless we are happy to assist and help out.If you wish to have this feature implemented by the Nextcloud GmbH there is the option for consulting work on top of your Nextcloud Enterprise subscription to get your features implemented.
