### ISSUE TITLE
Update was unsuccessful

### ISSUE THREAD

**Issue by carlo-fontanos** [nextcloud/server#26186]
We got this error while trying to perform an update.
The URL is: https://cyber.owncube.com/index.php

![image](https://user-images.githubusercontent.com/12164593/111567349-c5232580-87d9-11eb-9c19-7861f12fba90.png)

**Comment by aqzaxs** [comment]
i have the same errror:

"
Update to 20.0.8

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "filecache"."fileid", "storage", "path", "path_hash", "filecache"."parent", "name", "mimetype", "mimepart", "size", "mtime", "storage_mtime", "encrypted", "etag", "permissions", "checksum", "metadata_etag", "creation_time", "upload_time" FROM "oc_filecache" "filecache" LEFT JOIN "oc_filecache_extended" "fe" ON "filecache"."fileid" = "fe"."fileid" WHERE ("storage" = ?) AND ("path_hash" = ?)' with params [2, "2bc9c268724ea0d9bb1b895be0e8ba7e"]: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block
Detailed logs

Preparing update

Set log level to debug

Turned on maintenance mode

Repair step: Repair MySQL collation

Repair info: Not a mysql database -> nothing to do

Repair step: Repair SQLite autoincrement

Repair step: Copy data from accounts table when migrating from ownCloud

Repair step: Drop account terms table when migrating from ownCloud

Updating database schema

Updated database

Checking for update of app "accessibility" in appstore

Checked for update of app "accessibility" in appstore

Checking for update of app "activity" in appstore

Checked for update of app "activity" in appstore

Checking for update of app "admin_audit" in appstore

Checked for update of app "admin_audit" in appstore

Checking for update of app "analytics" in appstore

Update app "analytics" from appstore

Checked for update of app "analytics" in appstore

Checking for update of app "apporder" in appstore

Update app "apporder" from appstore

Checked for update of app "apporder" in appstore

Checking for update of app "audioplayer" in appstore

Checked for update of app "audioplayer" in appstore

Checking for update of app "audioplayer_editor" in appstore

Checked for update of app "audioplayer_editor" in appstore

Checking for update of app "audioplayer_sonos" in appstore

Checked for update of app "audioplayer_sonos" in appstore

Checking for update of app "calendar" in appstore

Checked for update of app "calendar" in appstore

Checking for update of app "cloud_federation_api" in appstore

Checked for update of app "cloud_federation_api" in appstore

Checking for update of app "comments" in appstore

Checked for update of app "comments" in appstore

Checking for update of app "contacts" in appstore

Update app "contacts" from appstore

Checked for update of app "contacts" in appstore

Checking for update of app "contactsinteraction" in appstore

Checked for update of app "contactsinteraction" in appstore

Checking for update of app "dashboard" in appstore

Checked for update of app "dashboard" in appstore

Checking for update of app "dav" in appstore

Checked for update of app "dav" in appstore

Checking for update of app "deck" in appstore

Update app "deck" from appstore

Checked for update of app "deck" in appstore

Checking for update of app "encryption" in appstore

Checked for update of app "encryption" in appstore

Checking for update of app "end_to_end_encryption" in appstore

Checked for update of app "end_to_end_encryption" in appstore

Checking for update of app "federatedfilesharing" in appstore

Checked for update of app "federatedfilesharing" in appstore

Checking for update of app "federation" in appstore

Checked for update of app "federation" in appstore

Checking for update of app "files" in appstore

Checked for update of app "files" in appstore

Checking for update of app "files_external" in appstore

Checked for update of app "files_external" in appstore

Checking for update of app "files_fulltextsearch" in appstore

Update app "files_fulltextsearch" from appstore

Checked for update of app "files_fulltextsearch" in appstore

Checking for update of app "files_fulltextsearch_tesseract" in appstore

Checked for update of app "files_fulltextsearch_tesseract" in appstore

Checking for update of app "files_markdown" in appstore

Update app "files_markdown" from appstore

Checked for update of app "files_markdown" in appstore

Checking for update of app "files_mindmap" in appstore

Checked for update of app "files_mindmap" in appstore

Checking for update of app "files_pdfviewer" in appstore

Checked for update of app "files_pdfviewer" in appstore

Checking for update of app "files_rightclick" in appstore

Checked for update of app "files_rightclick" in appstore

Checking for update of app "files_sharing" in appstore

Checked for update of app "files_sharing" in appstore

Checking for update of app "files_trashbin" in appstore

Checked for update of app "files_trashbin" in appstore

Checking for update of app "files_versions" in appstore

Checked for update of app "files_versions" in appstore

Checking for update of app "files_videoplayer" in appstore

Checked for update of app "files_videoplayer" in appstore

Checking for update of app "firstrunwizard" in appstore

Checked for update of app "firstrunwizard" in appstore

Checking for update of app "flowupload" in appstore

Checked for update of app "flowupload" in appstore

Checking for update of app "forms" in appstore

Update app "forms" from appstore

Checked for update of app "forms" in appstore

Checking for update of app "fulltextsearch" in appstore

Checked for update of app "fulltextsearch" in appstore

Checking for update of app "fulltextsearch_elasticsearch" in appstore

Checked for update of app "fulltextsearch_elasticsearch" in appstore

Checking for update of app "gpxmotion" in appstore

Checked for update of app "gpxmotion" in appstore

Checking for update of app "gpxpod" in appstore

Update app "gpxpod" from appstore

Checked for update of app "gpxpod" in appstore

Checking for update of app "health" in appstore

Checked for update of app "health" in appstore

Checking for update of app "logreader" in appstore

Checked for update of app "logreader" in appstore

Checking for update of app "lookup_server_connector" in appstore

Checked for update of app "lookup_server_connector" in appstore

Checking for update of app "mail" in appstore

Update app "mail" from appstore

Repair step: Add a generated message-id to all Mail messages that have none

Repair info: Looking up messages without a message-id

Repair info: 0 messages need an update

Repair step: Purify and migrate collected mail addresses

[0 / 0]: Purify and migrate collected mail addresses

Repair step: Insert background jobs for all accounts

[0 / 0]: Insert background jobs for all accounts

Repair step: Make Mail itinerary extractor executable

Repair step: Migrate Mail provisioning config from config.php to the database

Repair info: No old config found

Repair step: Add sieve defaults to provisioning config

Repair step: Create or update provisioned Mail accounts

Repair info: No Mail provisioning config set

Checked for update of app "mail" in appstore

Checking for update of app "maps" in appstore

Checked for update of app "maps" in appstore

Checking for update of app "music" in appstore

Checked for update of app "music" in appstore

Checking for update of app "news" in appstore

Checked for update of app "news" in appstore

Checking for update of app "nextcloud_announcements" in appstore

Checked for update of app "nextcloud_announcements" in appstore

Checking for update of app "notifications" in appstore

Checked for update of app "notifications" in appstore

Checking for update of app "oauth2" in appstore

Checked for update of app "oauth2" in appstore

Checking for update of app "onlyoffice" in appstore

Checked for update of app "onlyoffice" in appstore

Checking for update of app "password_policy" in appstore

Checked for update of app "password_policy" in appstore

Checking for update of app "phonetrack" in appstore

Checked for update of app "phonetrack" in appstore

Checking for update of app "photos" in appstore

Checked for update of app "photos" in appstore

Checking for update of app "podcast" in appstore

Update app "podcast" from appstore

Checking for update of app "privacy" in appstore

Checked for update of app "privacy" in appstore

Checking for update of app "provisioning_api" in appstore

Checked for update of app "provisioning_api" in appstore

Checking for update of app "radio" in appstore

Update app "radio" from appstore

Checked for update of app "radio" in appstore

Checking for update of app "recommendations" in appstore

Checked for update of app "recommendations" in appstore

Checking for update of app "richdocuments" in appstore

Update app "richdocuments" from appstore

Checked for update of app "richdocuments" in appstore

Checking for update of app "serverinfo" in appstore

Checked for update of app "serverinfo" in appstore

Checking for update of app "settings" in appstore

Checked for update of app "settings" in appstore

Checking for update of app "sharebymail" in appstore

Checked for update of app "sharebymail" in appstore

Checking for update of app "support" in appstore

Checked for update of app "support" in appstore

Checking for update of app "survey_client" in appstore

Checked for update of app "survey_client" in appstore

Checking for update of app "systemtags" in appstore

Checked for update of app "systemtags" in appstore

Checking for update of app "text" in appstore

Checked for update of app "text" in appstore

Checking for update of app "theming" in appstore

Checked for update of app "theming" in appstore

Checking for update of app "twofactor_backupcodes" in appstore

Checked for update of app "twofactor_backupcodes" in appstore

Checking for update of app "updatenotification" in appstore

Checked for update of app "updatenotification" in appstore

Checking for update of app "user_status" in appstore

Checked for update of app "user_status" in appstore

Checking for update of app "video_converter" in appstore

Checked for update of app "video_converter" in appstore

Checking for update of app "viewer" in appstore

Checked for update of app "viewer" in appstore

Checking for update of app "weather_status" in appstore

Checked for update of app "weather_status" in appstore

Checking for update of app "workflow_ocr" in appstore

Checked for update of app "workflow_ocr" in appstore

Checking for update of app "workflow_pdf_converter" in appstore

Checked for update of app "workflow_pdf_converter" in appstore

Checking for update of app "workflow_script" in appstore

Checked for update of app "workflow_script" in appstore

Checking for update of app "workflowengine" in appstore

Checked for update of app "workflowengine" in appstore

Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'SELECT "filecache"."fileid", "storage", "path", "path_hash", "filecache"."parent", "name", "mimetype", "mimepart", "size", "mtime", "storage_mtime", "encrypted", "etag", "permissions", "checksum", "metadata_etag", "creation_time", "upload_time" FROM "oc_filecache" "filecache" LEFT JOIN "oc_filecache_extended" "fe" ON "filecache"."fileid" = "fe"."fileid" WHERE ("storage" = ?) AND ("path_hash" = ?)' with params [2, "2bc9c268724ea0d9bb1b895be0e8ba7e"]: SQLSTATE[25P02]: In failed sql transaction: 7 ERROR: current transaction is aborted, commands ignored until end of transaction block

The update was unsuccessful. Please report this issue to the Nextcloud community.
"

**Comment by kesselb** [comment]
cc @onny :wave: 

@aqzaxs you have a different issue. Please visit https://help.nextcloud.com.

**Comment by aqzaxs** [comment]
this is my next page update error
![image](https://user-images.githubusercontent.com/22727675/111609563-1d125a00-87e3-11eb-8e69-e439ed5cd3ce.png)

**Comment by kesselb** [comment]
Please report this issue to https://git.project-insanity.org/onny/nextcloud-app-podcast/-/issues. Thanks :+1:
