### ISSUE TITLE
sharing a folder triggers event, even if disabling such events

### ISSUE THREAD

**Issue by sh-dvl** [nextcloud/server#26183]
### Steps to reproduce
1. disable for user A in Settings-Activity events for sharing files/folders
2. create as user B a folder and share it with user A

### Expected behaviour
nothing should happen, except that user A has now access to this folder

### Actual behaviour
user A get's an eMail, that user B has shared a folder

### Server configuration

**Operating system:**
devuan beowulf

**Web server:**
nginx

**Database:**
mariadb

**PHP version:**
7.3

**Nextcloud version:** (see Nextcloud admin page)
19.0.9

**Updated from an older Nextcloud/ownCloud or fresh install:**
fresh install

**Where did you install Nextcloud from:**
orignal tar-archive from nextcloud.com

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.5.0
  - activity: 2.12.1
  - admin_audit: 1.9.0
  - bruteforcesettings: 2.0.1
  - cloud_federation_api: 1.2.0
  - comments: 1.9.0
  - contactsinteraction: 1.0.0
  - dav: 1.15.0
  - federatedfilesharing: 1.9.0
  - files: 1.14.0
  - files_accesscontrol: 1.9.3
  - files_rightclick: 0.16.0
  - files_sharing: 1.11.0
  - files_trashbin: 1.9.0
  - files_versions: 1.12.0
  - files_videoplayer: 1.8.0
  - gpgmailer: 0.0.3
  - impersonate: 1.6.1
  - logreader: 2.4.0
  - lookup_server_connector: 1.7.0
  - notifications: 2.7.0
  - oauth2: 1.7.0
  - password_policy: 1.9.1
  - photos: 1.1.0
  - privacy: 1.3.0
  - provisioning_api: 1.9.0
  - serverinfo: 1.9.0
  - settings: 1.1.0
  - sharebymail: 1.9.0
  - systemtags: 1.9.0
  - text: 3.0.1
  - theming: 1.10.0
  - twofactor_backupcodes: 1.8.0
  - updatenotification: 1.9.0
  - viewer: 1.3.0
  - workflowengine: 2.1.0

```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "daten.gestochen-scharf.de"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "tempdirectory": "\/import\/tmp",
        "logfile": "\/var\/log\/web\/nextcloud.log",
        "loglevel": 2,
        "debug": false,
        "version": "19.0.9.1",
        "overwrite.cli.url": "https:\/\/daten.gestochen-scharf.de",
        "installed": true,
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***",
        "upgrade.disable-web": true,
        "maintenance": false,
        "dbtype": "mysql",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "mysql.utf8mb4": true,
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "mail_from_address": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpmode": "smtp",
        "mail_sendmailmode": "smtp",
        "mail_domain": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpsecure": "ssl",
        "mail_smtpauthtype": "PLAIN",
        "mail_smtpauth": 1,
        "mail_smtphost": "***REMOVED SENSITIVE VALUE***",
        "mail_smtpport": "465",
        "mail_smtpname": "***REMOVED SENSITIVE VALUE***",
        "mail_smtppassword": "***REMOVED SENSITIVE VALUE***",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "forwarded_for_headers": [
            "HTTP_X_FORWARDED_FOR"
        ],
        "defaultapp": "files",
        "theme": "",
        "default_language": "de",
        "default_locale": "de_DE",
        "session_lifetime": 86400,
        "session_keepalive": true,
        "auto_logout": false,
        "lost_password_link": "disabled",
        "trashbin_retention_obligation": "auto",
        "enable_previews": false
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/...

no

**Are you using encryption:** yes/no

no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

no

### Client configuration

not relevant.

### Logs

no errors are logged

#### Web server error log
<details>
<summary>Web server error log</summary>

```
empty
```
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>

```
nothing relevant here
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>

```
nothing relevant here
```
</details>

**Comment by kesselb** [comment]
> user A get's an eMail, that user B has shared a folder

is the expected behavior. 

https://github.com/nextcloud/server/blob/dd39f5e871636c038fab03e75cf53668efc50963/config/config.sample.php#L1469-L1472

to disable the emails for a new share.

**Comment by sh-dvl** [comment]
thanks for soon reply and solution for problem.

but: shouldn't this perhaps be noted in activity-overview in gui, that there's a default-setting, which overwrites the user-setting?

**Comment by kesselb** [comment]
> shouldn't this perhaps be noted in activity-overview in gui, that there's a default-setting, which overwrites the user-setting?

No. If enable_share_mail is false you can still receive the activity notifications. The settings are not connected to each other.

**Comment by sh-dvl** [comment]
mmh, but if they weren't connected, then we hadn't have the problem...

of course: you might be right, if 'sharing.enable_share_mail' is false, that then the user-setting works, but what I mean is, that the default of 'sharing.enable_share_mail' is true, and then the user-setting is meaning-less (else we hadn't have that problem) and this should be noted (else others might also think, that's a bug, or might drop it, because of this "mal-function" ...)

please, note: this is only a suggestion, I didn't want to force a discussion or similar about it.
