### ISSUE TITLE
Expiration date error tooltip is getting in the way

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#26199]
### Steps

1. Follow the steps from https://github.com/nextcloud/server/issues/26197 on https://github.com/nextcloud/server/commit/a186d084713fa494eea94febf2d585a34222b992 (before the fix) or anything to make an error popup appear
2. Select an invalid expiration date, see error tooltip
3. Try selecting another one

### Expected result
When clicking on the field or outside, the error tooltip disappears.

### Actual result
The tooltip stays, forever!

And when in the following situation:
![share-popover-error-tooltip](https://user-images.githubusercontent.com/277525/111656580-f36d2900-880a-11eb-8943-4b3929c37037.gif)

If I move the cursor up to reach the expiration date dropdown to pick another one, it will disappear! This is because I first need to traverse the tooltip, which is outside of the field. So it's impossible to change the date.

And clicking outside the popover closes the actions popover, but upon reopening the tooltip is still here!

Fortunately it is seldom that such errors will appears.

### Version
22.0.0 alpha git master a186d08

### Analysis

I tried to fix this by adding `autoHide: true` or `hideOnTargetClick: true` to those tooltips but the behavior didn't change at all.
Also, I think we need to reconsider this UI / UX. Having three overlapping layers like this doesn't look good. @nextcloud/designers

**Comment by ma12-co** [comment]
> Also, I think we need to reconsider this UI / UX. Having three overlapping layers like this doesn't look good.

Yes, in my opinion we do way too much popover based interactions and editing. I think in the long run we should remove things like date-pickers and input fields from popovers... And maybe just keep buttons, radios and switches

**Comment by skjnldsv** [comment]
Yes, we should most likely put the message just above the input :)

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
