### ISSUE TITLE
Updating enforced expiration date validation mixed up between user and link shares

### ISSUE THREAD

**Issue by PVince81** [nextcloud/server#26197]
### Steps

1. Go to the settings page
2. For internal shares, set expiration days to "7" and enable enforcement
3. For link shares, set expiration days to "3" (a lower value) and enable enforcement.
4. Go to files app
5. Create a folder "test"
6. Share "test" with another user
7. Check expiration date and confirm that it's 7 days in the future from today
8. Now edit the date and set it to 6 days and confirm

### Expected result
6 days is allowed too

### Actual result
Error messages from the **link** share appears with a 3 day limit:
<img width="224" alt="image" src="https://user-images.githubusercontent.com/277525/111651562-9ff8dc00-8806-11eb-8ad4-2e651fa2a2bc.png">

### Version

22.0.0 alpha git master a186d084713fa494eea94febf2d585a34222b992

### Analysis

The reason is because of a code mix up in Share20/Manager.php where the wrong validator is used: https://github.com/nextcloud/server/blob/master/lib/private/Share20/Manager.php#L978

`validateExpirationDate` is actually for links.
`validateExpirationDateInternal` is for user and group shares.
Due to confusing name

Found while working on https://github.com/nextcloud/server/pull/25320#issuecomment-800269537

**Comment by PVince81** [comment]
PR here: https://github.com/nextcloud/server/pull/26200

**Comment by PVince81** [comment]
stable19 also contains the same code, so will need backporting

**Comment by kurn77** [comment]
Hello @PVince81 : 
> I just updated on NC20.0.9 and correction seems not working (same behaviour than NC20.0.8).
> Moreover, the expiration date is not enforced even if checkbox is activated (text box is kept empty)
> Share by link is perfectly working and expiration date enforced as expected
> Would you know if we missed someting on correction for NC20 ?

Many thanks for your feedback and investigations already done on this topic !

PS : Below, share parameters on my NC20.0.9

![image1](https://user-images.githubusercontent.com/74493472/116299810-708ea500-a79e-11eb-9d74-7f95b6ece613.png)

**Comment by PVince81** [comment]
works for me in NC 20.0.9
<img width="249" alt="image" src="https://user-images.githubusercontent.com/277525/116357457-c7c36280-a7fc-11eb-83c3-cdd183d27363.png">

<img width="246" alt="image" src="https://user-images.githubusercontent.com/277525/116357530-d7db4200-a7fc-11eb-9873-c11cf0cc43de.png">

make sure to shift+refresh the page in case you have cached assets.
otherwise please raise a separate ticket as specify your exact steps (the order is important and where exactly you click)

**Comment by kurn77** [comment]
Hello @PVince81 thanks for you feedback. I tested again and I understood. To recap :
- Share by link : expiration date is automatically enforced and setted => OK
- Share to another account (in same group) : expiration date is automatically enforced and setted => OK
- Share by mail : expiration date is **not** automatically enforced and setted => **NOK**

If you try to set expiration date manually for a share by mail, max expiration date is indeed taken from link share parameter but just not setted automatically.

Conclusion : my bad, your commit is correctly fixing the issue you mentionned in NC20.0.9. I have to open a new separate ticket for expiration date not setted automatically for a share by mail as it is correctly done for a share by link.

**Comment by PVince81** [comment]
> Conclusion : my bad, your commit is correctly fixing the issue you mentionned in NC20.0.9. I have to open a new separate ticket for expiration date not setted automatically for a share by mail as it is correctly done for a share by link.

Yes, please. Share by mail has yet another code path.
