### ISSUE TITLE
[stable9] Server-to-server sharing is broken

### ISSUE THREAD

**Issue by LukasReschke** [nextcloud/server#262]
1. Create user "admin" on localhost
2. Create user "test" on localtest.me (both are on the same instance for me with different hostnames just)
3. Share from user "test" to user "admin" via "admin@http://localhost/"
4. Try to access the folder.
5. It won't work

In the proxy logs I see:

```
POST /server/index.php/apps/files_sharing/shareinfo?t=wdqbHBREI7o8VeR HTTP/1.1
Host: localhost
User-Agent: Nextcloud Server Crawler
Content-Type: application/x-www-form-urlencoded
Content-Length: 9
Connection: close

password=
```

This returns a:

```
Unspecified share exception
```

This is caused by [`\OC\Share20\DefaultShareProvider`](https://github.com/nextcloud/server/blob/9120448302e627846ad2e4a83e36ebdc83b040e2/lib/private/share20/defaultshareprovider.php#L720-L746), it matches for a share type of "3" but actually in the DB it is set to 6:

![2016-06-30_14-48-04](https://cloud.githubusercontent.com/assets/878997/16488900/22090094-3ed3-11e6-856d-be69feacbf05.png)

When changing that also to match 6 it works fine… So there seems to be a problem somewhere 🙈 

@rullzer or @schiessle Please take a look if possible. THX.

**Comment by schiessle** [comment]
Fix merged. Will be released with 9.0.52
