### ISSUE TITLE
Translation of app description (from info.xml) is not shown in app management

### ISSUE THREAD

**Issue by rakekniven** [nextcloud/server#26207]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Login as admin with admin interface language in german (works with any other non-english language).
2. Open app management
3. Select one installed app
4. See app description on the left sidebar
5. Language of app description is english

### Expected behaviour
Open app management in german language and see app description of installed apps in german.

### Actual behaviour
App description is displayed in english.
Just checked that app description is translated at Transifex and translation is part of the app package.

### Server configuration
**Operating system:** Ubuntu 20.04 LTS

**Web server:** Apache 2.24.0

**Database:** PostgreSQL 10

**PHP version:** 7.4

**Nextcloud version:** 21.0.0

**Updated from an older Nextcloud/ownCloud or fresh install:** Upgrade from 20.0.7

**Where did you install Nextcloud from:** source

### Client configuration
**Browser:** FF 86

**Operating system:** Mac OS Mojave

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/20753
