### ISSUE TITLE
Add new file menu is hidden under the preview of a readme.md from an shared link.

### ISSUE THREAD

**Issue by cscgeiche** [nextcloud/server#26232]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Create a share link with write permission
2. Open it
3. click on the (+)-Icon at the top
![Bug_Nextcloud_Add_new_file](https://user-images.githubusercontent.com/74933424/111876600-bab28880-899f-11eb-8ff3-32bd41b6cd0c.png)

### Expected behaviour
All entrys should be available to select

### Actual behaviour
The entrys behind the Markdown-Preview aren't selectable by mouse

### Server configuration

**Operating system:** Debian

**Web server:** Nextcloud-DockerImage Stable

**Database:** MariaDB

**PHP version:** ? I guess PHP 7

**Nextcloud version:** (see Nextcloud admin page) 20.0.8

**Updated from an older Nextcloud/ownCloud or fresh install:** Fresh install

**Where did you install Nextcloud from:** Docker

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**

<details>
<summary>App list</summary>

```
Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - apporder: 0.12.0
  - breezedark: 20.0.9
  - bruteforcesettings: 2.0.1
  - calendar: 2.1.3
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contacts: 3.5.1
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - deck: 1.2.5
  - documentserver_community: 0.1.9
  - epubreader: 1.4.5
  - external: 3.7.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_external: 1.11.1
  - files_mindmap: 0.0.24
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - forms: 2.2.2
  - keeweb: 0.6.5
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - notifications: 2.8.0
  - oauth2: 1.8.0
  - ocr: 6.0.58
  - onlyoffice: 6.3.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - polls: 1.7.5
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - spreed: 10.0.6
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - talk_simple_poll: 1.3.0
  - tasks: 0.13.6
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - unsplash: 1.2.1
  - updatenotification: 1.10.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - whiteboard: 0.0.3
  - workflow_ocr: 1.20.2
  - workflow_pdf_converter: 1.5.1
  - workflow_script: 1.5.1
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - mail
  - user_ldap
```
</details>

**Nextcloud configuration:**

<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "cloud.eichehome.com"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "mysql",
        "version": "20.0.8.1",
        "overwrite.cli.url": "http:\/\/cloud.eichehome.com",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "app_install_overwrite": [
            "ocr"
        ],
        "maintenance": false,
        "loglevel": 0,
        "theme": "",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... No

**Are you using encryption:** yes/**no**

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No

### Client configuration
**Browser:** Firefox 86.0.1

**Operating system:** Fedora

### Logs
As it's a interfac bug I will not include logs if they are needed really, I'm willing to provide them.

**Comment by szaimen** [comment]
Lets track this in https://github.com/nextcloud/server/issues/27588
