### ISSUE TITLE
New updater in 10.0.1 stops on expected files

### ISSUE THREAD

**Issue by Rouzax** [nextcloud/server#2624]
### Steps to reproduce
1. Update from 10.0.1 to 10.0.2 using the new updater

### Expected behaviour
Update 😄 

### Actual behaviour
Stops on files that are there.
I use Let's Encrypt that is the .well-known the error_log is just the php error log
![image](https://cloud.githubusercontent.com/assets/4103090/21101870/9a925928-c07b-11e6-9db2-af3725b12388.png)

### Server configuration
**Operating system**:
2.6.32-673.8.1.lve1.4.3.1.el6.x86_64

**Web server:**
Apache 2.4.23

**Database:**
MySQL

**PHP version:**
7.0

**Nextcloud version:** (see Nextcloud admin page)
10.0.1

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**Comment by LukasReschke** [comment]
That is the expected behaviour. We do not support having other files in the Nextcloud folder than the ones we ship. For LetsEncrypt we recommend doing this on the VirtualHost layer and I'd advise against storing the error_log in the webroot.

**Comment by Rouzax** [comment]
That is not always up to the user 😄

**Comment by LukasReschke** [comment]
Well. Then they have to manually update. I'm afraid but we won't support those cases. We value data security too much to randomly delete files and folders.
