### ISSUE TITLE
Nextcloud sends the oc<id> cookie twice

### ISSUE THREAD

**Issue by 42l-neil-tmp** [nextcloud/server#26267]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce
1. Setup a Nextcloud instance.
2. Check with `curl http://DOMAIN/status.php` that your instance is working as intended.
In my case, this command returns the following:
`{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"21.0.0.18","versionstring":"21.0.0","edition":"","productname":"42l Forms","extendedSupport":false}`

3. Run `curl -v http://DOMAIN/status.php 2>&1 | grep -i cookie`.

### Expected behaviour

Your Nextcloud instance should give you 4 cookies:
- oc_sessionPassphrase
- oc<10-character id>
- nc_sameSiteCookielax
- nc_sameSiteCookiestrict

Example:
```
< set-cookie: oc_sessionPassphrase=rYU%2FP9U6Hm4KxXN....; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: ocvu3p67fwg7=tf1uif0j5h72dsvhdal...; path=/; secure; HttpOnly; SameSite=Lax
< set-cookie: __Host-nc_sameSiteCookielax=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< set-cookie: __Host-nc_sameSiteCookiestrict=true; path=/; httponly;secure; expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
```

### Actual behaviour

Under certain circumstances, the Nextcloud instance returns 5 cookies instead of 4:

- oc<10-character id>
- oc_sessionPassphrase
- **an additional oc<10-character id> with a different value**
- nc_sameSiteCookielax
- nc_sameSiteCookiestrict

Example:
```
< Set-Cookie: occ6b2mwnq7y=3e37734a143f6a1eff5e...; path=/; HttpOnly; SameSite=Lax
< Set-Cookie: oc_sessionPassphrase=XLZn%2BzLFyYf4CVMRyw7...; path=/; HttpOnly; SameSite=Lax
< Set-Cookie: occ6b2mwnq7y=fa22760f54a33e7b809dac...; path=/; HttpOnly; SameSite=Lax
< Set-Cookie: nc_sameSiteCookielax=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=lax
< Set-Cookie: nc_sameSiteCookiestrict=true; path=/; httponly;expires=Fri, 31-Dec-2100 23:59:59 GMT; SameSite=strict
```

This behavior is breaking parts of [my software](https://git.42l.fr/neil/sncf). Nextcloud should only send the second oc<10-character id> cookie, not the first one (the browser will probably ignore the first one anyway).

I believe this breaking change has been introduced a minor release, either Nextcloud 20.0.2 or Nextcloud 20.0.3.

I tested on a local instance and I'm able to reproduce this bug on a production server. Feel free to test by yourself: `curl -vvv https://nextcloud.42l.fr/status.php 2>&1 | grep -i cookie`
Both setups uses the `nextcloud:apache` Docker image.

I couldn't reproduce the bug on a public instance such as `demo1.nextcloud.com`, so it *may* be a Docker issue.

### Server configuration

**Operating system:** Debian GNU/Linux Bullseye (Testing)

**Web server:** Apache/2.4.38 (Docker `nextcloud:apache` version). Also tested the same setup under a Nginx reverse-proxy.

**Database:** Postgresql 12.3. Also tested this bug with Postgresql 13.2.

**PHP version:** PHP/7.4.16 (Docker `nextcloud:apache` version).

**Nextcloud version:** 21.0.0.18

**Updated from an older Nextcloud/ownCloud or fresh install:** updated from previous Nextcloud versions, not tested with a fresh install.

**Where did you install Nextcloud from:** Docker `nextcloud:apache` image

**Signing status:**
<details>
<summary>Signing status</summary>

```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - cloud_federation_api: 1.4.0
  - dav: 1.17.1
  - federatedfilesharing: 1.11.0
  - files: 1.16.0
  - forms: 2.2.2
  - lookup_server_connector: 1.9.0
  - oauth2: 1.9.0
  - provisioning_api: 1.11.0
  - settings: 1.3.0
  - theming: 1.12.0
  - theming_customcss: 1.8.0
  - twofactor_backupcodes: 1.10.0
  - viewer: 1.5.0
  - workflowengine: 2.3.0
Disabled:
  - accessibility
  - activity
  - admin_audit
  - apporder
  - comments
  - contactsinteraction
  - dashboard
  - encryption
  - federation
  - files_external
  - files_pdfviewer
  - files_rightclick
  - files_sharing
  - files_trashbin
  - files_versions
  - files_videoplayer
  - firstrunwizard
  - logreader
  - nextcloud_announcements
  - notifications
  - password_policy
  - photos
  - privacy
  - recommendations
  - serverinfo
  - sharebymail
  - support
  - survey_client
  - systemtags
  - text
  - updatenotification
  - user_ldap
  - user_status
  - weather_status
```
</details>

**Nextcloud configuration:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "htaccess.RewriteBase": "\/",
        "memcache.local": "\\OC\\Memcache\\APCu",
        "apps_paths": [
            {
                "path": "\/var\/www\/html\/apps",
                "url": "\/apps",
                "writable": false
            },
            {
                "path": "\/var\/www\/html\/custom_apps",
                "url": "\/custom_apps",
                "writable": true
            }
        ],
        "instanceid": "***REMOVED SENSITIVE VALUE***",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "*"
        ],
        "datadirectory": "***REMOVED SENSITIVE VALUE***",
        "dbtype": "pgsql",
        "version": "21.0.0.18",
        "trusted_proxies": "***REMOVED SENSITIVE VALUE***",
        "overwrite.cli.url": "http:\/\/localhost:18080",
        "dbname": "***REMOVED SENSITIVE VALUE***",
        "dbhost": "***REMOVED SENSITIVE VALUE***",
        "dbport": "",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "simpleSignUpLink.shown": false,
        "maintenance": false,
        "loglevel": 0
    }
}
```
</details>

**Are you using external storage, if yes which one:** local/smb/sftp/... **No.**

**Are you using encryption:** yes/no **No.**

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... **No.**

### Client configuration
**Browser:** Mozilla/5.0 (X11; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0

**Operating system:** Debian GNU/Linux Bullseye (Testing)

### Logs

No logs to provide.

#### Web server error log

No errors.

#### Nextcloud log (data/nextcloud.log)

No errors, even in debug mode.

#### Browser log

No errors.

**Comment by kesselb** [comment]
I can reproduce it.

**Comment by szaimen** [comment]
Hi, please update to 24.0.9 or better 25.0.3 and report back if it fixes the issue. Thank you!

My goal is to add a label like e.g. 25-feedback to this ticket of an up-to-date major Nextcloud version where the bug could be reproduced. However this is not going to work without your help. So thanks for all your effort!

If you don't manage to reproduce the issue in time and the issue gets closed but you can reproduce the issue afterwards, feel free to create a new bug report with up-to-date information by following this link: https://github.com/nextcloud/server/issues/new?assignees=&labels=bug%2C0.+Needs+triage&template=BUG_REPORT.yml&title=%5BBug%5D%3A+
