### ISSUE TITLE
LDAP user and group backend does not add users to nextcloud

### ISSUE THREAD

**Issue by msuhr123** [nextcloud/server#26280]
Hello,
since the last week our nextcloud server 20.0.8 does not import new LDAP-User to nextcloud. The LDAP configuration test tells me no problems and the "user verification and count" shows the right number of users. But no new user is shown in the user list.
The existing accounts works like a charm. So what can be the reason for this malfunction?
Thank you.

**Comment by C-Duv** [comment]
Same issue on a fresh install of Nextcloud 21.0.2 (using `nextcloud:21.0-apache` Docker image).

**Comment by szaimen** [comment]
I suppose this is still happening on NC21.0.3?
