### ISSUE TITLE
Nextcloud 21 fresh install Collabora doesn't work 

### ISSUE THREAD

**Issue by egpgit** [nextcloud/server#26288]
Hi, 
When I try to open or create a new collabora document in nextcloud, i get this error: "Failed to load Colabora Online, - please try again later"

I have open bug in Collabora too: https://github.com/CollaboraOnline/online/issues/827#issuecomment-805859763

![fTHvRmLUi7](https://user-images.githubusercontent.com/64414923/112324916-88609e00-8cb3-11eb-8700-53e87b6b2405.png)

![uPH0Rx0tTF](https://user-images.githubusercontent.com/64414923/112430677-c2c34d00-8d3e-11eb-9eda-de0ef237c33f.png)

This happends in two different fresh nextcloud21 installations, and settings apear be correct:
![firefox_v9aZzfPxlg](https://user-images.githubusercontent.com/64414923/112325476-00c75f00-8cb4-11eb-8df0-7d004ab1e5aa.png)

![firefox_4XSsqm4i00](https://user-images.githubusercontent.com/64414923/112325499-06bd4000-8cb4-11eb-93da-c488bdf62ec7.png)

![cfOEDQkbp3](https://user-images.githubusercontent.com/64414923/112430710-cf47a580-8d3e-11eb-9226-2071da3f0095.png)

OS: CentOS 7.9
Web Server: Apache 2.4.6
NextCloud 21
SELINUX: Disabled
CollaboraOnline 4.0.4
Collabora Online - Built-in CODE Server 6.4.705

Could you help me?
Thanks a lot

**Comment by kesselb** [comment]
Thank you for taking the time to report a problem :+1: 

As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
