### ISSUE TITLE
Encryption migration failed (Class not Found)

### ISSUE THREAD

**Issue by freddyb** [nextcloud/server#2628]
### Steps to reproduce
0. (Updated to latest stable)
1. Tried to upload file via Android app but failed. Log:
> Installation is in transit between the old Encryption (ownCloud <= 8.0) and the new encryption. Please enable the "Default encryption module" and run 'occ encryption:migrate' 
2. Tried to migrate via web interface
> Error   PHP       Class 'OCA\Encryption\Migration' not found at /var/www/virtual/freddyb/html/owncloud/settings/Controller/EncryptionController.php#97  2016-12-12T14:58:22+00:00        freddyb

### Expected behaviour
Migration/Uploading should not fail

### Actual behaviour
Failure (see log output above)

### Server configuration
**Operating system**: CentOS 6.8
**Web server:** Apache/2.2.15 (CentOS)
**Database:** mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
**PHP version:** PHP 5.6.21 (cli) (built: May  4 2016 12:03:47) 
**Nextcloud version:** latest stable, 10.0.2

**Updated from an older Nextcloud/ownCloud or fresh install:**
Yeah, started with an 8.x ownCloud, migrated to Nextcloud via the suggested method. I don't know the version numbers by heart but have the old folders in a backup and could take a look if you can suggest which file to look into.

**Where did you install Nextcloud from:** ZIP installer?

**Signing status:**
<details>
<summary>Signing status</summary>
```
No errors have been found.
```
</details>

**List of activated apps:**
<details>
<summary>App list</summary>

```
Enabled:
  - activity: 2.3.2
  - admin_audit: 1.0.0
  - dav: 1.0.1
  - federatedfilesharing: 1.0.1
  - files: 1.5.2
  - files_pdfviewer: 0.8.1
  - files_sharing: 1.0.0
  - files_texteditor: 2.1
  - files_trashbin: 1.0.0
  - files_videoplayer: 0.9.8
  - firstrunwizard: 1.1
  - gallery: 15.0.1
  - notifications: 0.3.0
  - password_policy: 1.0.0
  - systemtags: 1.0.2
  - templateeditor: 0.1
  - theming: 1.0.1
  - updatenotification: 1.0.1
  - workflowengine: 1.0.1
Disabled:
  - comments
  - encryption
  - external
  - federation
  - files_accesscontrol
  - files_automatedtagging
  - files_external
  - files_retention
  - files_versions
  - provisioning_api
  - serverinfo
  - survey_client
  - user_external
  - user_ldap
  - user_saml
```
</details>

**The content of config/config.php:**
<details>
<summary>Config report</summary>

```
{
    "system": {
        "instanceid": "oc3l4hxd9ic8",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "freddyb.dubhe.uberspace.de"
        ],
        "datadirectory": "\/var\/www\/virtual\/freddyb\/html\/owncloud\/data",
        "overwrite.cli.url": "https:\/\/freddyb.dubhe.uberspace.de\/owncloud",
        "dbtype": "mysql",
        "version": "9.1.2.2",
        "dbname": "freddyb_owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "forceSSLforSubdomains": false,
        "mail_from_address": "freddyb-owncloud",
        "mail_smtpmode": "php",
        "mail_domain": "dubhe.uberspace.de",
        "theme": "",
        "maintenance": false,
        "loglevel": 2,
        "trashbin_retention_obligation": "auto",
        "updater.release.channel": "stable",
        "updater.secret": "***REMOVED SENSITIVE VALUE***"
    }
}
```
</details>

**Are you using external storage, if yes which one:** local

**Are you using encryption:** Yes

**Are you using an external user-backend, if yes which one:** None

### Client configuration
**Browser:** Firefox
**Operating system:** Linux

#### Web server error log
<details>
<summary>Web server error log</summary>
N/A
</details>

#### Nextcloud log (data/nextcloud.log)
<details>
<summary>Nextcloud log</summary>
```
    Error   PHP       Class 'OCA\Encryption\Migration' not found at /var/www/virtual/freddyb/html/owncloud/settings/Controller/EncryptionController.php#97  2016-12-12T14:58:22+00:00        freddyb
    Warning         no app in context       Installation is in transit between the old Encryption (ownCloud <= 8.0) and the new encryption. Please enable the "Default encryption module" and run 'occ encryption:migrate'        2016-12-12T14:58:19+00:00      freddyb
    Warning         no app in context       Installation is in transit between the old Encryption (ownCloud <= 8.0) and the new encryption. Please enable the "Default encryption module" and run 'occ encryption:migrate'        2016-12-12T14:56:13+00:00      freddyb 
```
</details>

#### Browser log
<details>
<summary>Browser log</summary>
N/A
</details>

**Comment by LukasReschke** [comment]
cc @schiessle THX

**Comment by josh4trunks** [comment]
Any chance this would cause user to lose access to all their files in the web-interface?

I'm kinda worried, I just logged in as  a user and all the files are gone, and only the demo Nextcloud files appear. (Documents / Photos...) This didn't happen to my admin user, but did to all my other users =[

**Comment by mozfreddyb** [comment]
Is there anything I can do as a workaround? It's pretty annoying that uploads from mobile don't work.
I'm happy to help with more log files btw :)

**Comment by freddyb** [comment]
Uploading with the ownCloud Linux application works though. I get this new line in the web interface under *Logging*:
> Encryption module "" not found, file will be stored unencrypted (No default encryption module defined)

**Comment by schiessle** [comment]
Is this still an issue with newer versions of Nextcloud?
