### ISSUE TITLE
NC 21 - occ Exception TypeError: Return value ... Request::getScriptName()

### ISSUE THREAD

**Issue by Dubidubiduu** [nextcloud/server#26284]
### Steps to reproduce
1. Upgraded to nc 21 via web, tried to do last step via ./occ upgrade as I usual do, so first chmod +x for occ, then ./occ upgrade
2. ./occ didn't send me any output, deactivated maintenance via config/config.php, go to web, finished update

### Expected behaviour
Since then, ./occ gives me nothing, but should give me an output

### Actual behaviour
It doesn't give any output, only if I add php or usr/bin/php. It then shows me it has thrown an exception of course.
```

$ /usr/bin/php occ
Content-type: text/html; charset=UTF-8

An unhandled exception has been thrown:
TypeError: Return value of OC\AppFramework\Http\Request::getScriptName() must be of the type string, null returned in /home/xxx/subdomains/cloud/lib/private/AppFramework/Http/Request.php:838
Stack trace:
#0 /home/xxx/subdomains/cloud/lib/base.php(163): OC\AppFramework\Http\Request->getScriptName()
#1 /home/xxx/subdomains/cloud/lib/base.php(569): OC::initPaths()
#2 /home/xxx/subdomains/cloud/lib/base.php(1076): OC::init()
#3 /home/xxx/subdomains/cloud/console.php(49): require_once('/home/xxx/...')
#4 /home/xxx/subdomains/cloud/occ(11): require_once('/home/xxx/...')
#5 {main}
```

Looks similar to #24735, but the solution there didn't worked for me.

### Server configuration

**Operating system:**

**Web server:**
litespeed

**Database:**
Type: mysql
Version: 10.3.27
Size: 289,4 MB

**PHP version:**
`$ php -v
PHP 7.4.15 (cli) (built: Feb  4 2021 22:31:48) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.15, Copyright (c), by Zend Technologies`
**Nextcloud version:** (see Nextcloud admin page)
NC 21.0
**Updated from an older Nextcloud/ownCloud or fresh install:**
update

**Comment by Dubidubiduu** [comment]
Also my /usr/local/bin/ea-php73 -f /home/xxx/subdomains/cloud/cron.php` isn't working any longer

**Comment by kesselb** [comment]
> Content-type: text/html; charset=UTF-8

You are using a wrong php binary to run occ. As this seems to be a setup issue I would like to ask you to raise your question at https://help.nextcloud.com
