### ISSUE TITLE
Error Conflict files and error "the server did not acknowledge the last chunk. (No e-tag was present)""

### ISSUE THREAD

**Issue by smcto** [nextcloud/server#26295]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are affected by the same issue.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments. 

### Steps to reproduce

 1.   Save a file (for example just a simple .txt file (1ko) from desktop client (windows)
 2.  The sync lauch… and we receive an error " The server did not acknowledge the last chunk. (No e-tag was present)"" in the NC client panel admin
 3.  We modify the file (we have frequent updates of the same files) since it’s still in “error” (the update is ok in the webserver)
 4.   sync retry… successfully, but it create a conflict files, because NC think that there is a conflict

### Expected behaviour
Do no create conflict files ;-)

### Actual behaviour
we have a problem with Conflict files.
And the error : " The server did not acknowledge the last chunk. (No e-tag was present)"

We have read (all ?) the post from this error, which seems to exist for years.
We have :

    deactived Mod_security, Deflate…
    we don’t use encyption
    files:scan,  files:scan-app-data, files:cleanup.. already done 

We use Redis for the cache, we have tried to change it too…

### Server configuration

**Operating system:**
debian9~1.gbpb21322 

**Web server:** 
 Apache 2.4.25

**Database:**
Mariadb 

**PHP version:**
PHP 7.2.34

**Nextcloud version:** (see Nextcloud admin page)
20.0.8 

**Updated from an older Nextcloud/ownCloud or fresh install:**
new update client Nextcloud 3.1.3

**Signing status:**
<details>
<summary>Signing status</summary>

```
"No errors have been found."
```

</details>

Enabled:
  - accessibility: 1.6.0
  - activity: 2.13.4
  - cloud_federation_api: 1.3.0
  - comments: 1.10.0
  - contactsinteraction: 1.1.0
  - dashboard: 7.0.0
  - dav: 1.16.2
  - federatedfilesharing: 1.10.2
  - federation: 1.10.1
  - files: 1.15.0
  - files_pdfviewer: 2.0.1
  - files_rightclick: 0.17.0
  - files_sharing: 1.12.2
  - files_trashbin: 1.10.1
  - files_versions: 1.13.0
  - files_videoplayer: 1.9.0
  - firstrunwizard: 2.9.0
  - logreader: 2.5.0
  - lookup_server_connector: 1.8.0
  - nextcloud_announcements: 1.9.0
  - oauth2: 1.8.0
  - password_policy: 1.10.1
  - photos: 1.2.3
  - privacy: 1.4.0
  - provisioning_api: 1.10.0
  - recommendations: 0.8.0
  - selfizeehooks: 0.0.1
  - serverinfo: 1.10.0
  - settings: 1.2.0
  - sharebymail: 1.10.0
  - support: 1.3.0
  - survey_client: 1.8.0
  - systemtags: 1.10.0
  - text: 3.1.0
  - theming: 1.11.0
  - twofactor_backupcodes: 1.9.0
  - user_status: 1.0.1
  - viewer: 1.4.0
  - weather_status: 1.0.0
  - workflowengine: 2.2.0
Disabled:
  - admin_audit
  - encryption
  - files_external
  - notifications
  - updatenotification
  - user_ldap
```

**Nextcloud configuration:**

<?php
$CONFIG = array (
  'debug' => true,
  'trusted_domains' => 
  array (
    0 => 'XXXX.domain',
  ),
  'datadirectory' => '/home/path/to/public_html/dev',
  'dbtype' => 'mysql',
  'version' => '20.0.8.1',
  'overwrite.cli.url' => 'https://domain.url',
  'dbname' => 'db_name',
  'dbhost' => 'localhost',
  'dbport' => '',
  'dbtableprefix' => 'oc_',
  'mysql.utf8mb4' => true,
  'dbuser' => 'user_db,
  'dbpassword' => 'pass,
  'installed' => true,
  'mail_from_address' => 'smtp',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'domain,
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => 1,
  'mail_smtpport' => '25',
  'mail_smtphost' => 'localhost',
  'mail_smtpname' => 'smtp_name,
  'mail_smtppassword' => 'pass',
  'log_type' => 'file',
  'logfile' => '/path/to/log/nextcloud.log',
  'logfilemode' => 416,
  'loglevel' => '2',
  'logdateformat' => 'F d, Y H:i:s',
  'updatechecker' => false,
  'log_query' => true,
  'memcache.local' => '\\OC\\Memcache\\Redis',
  'redis' => 
  array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0.0,
  ),
  'filelocking.enabled' => true,
  'memcache.locking' => '\\OC\\Memcache\\Redis',
  'filelocking.debug' => true,
  'filelocking.ttl' => 1200,
  'filelocking.debug' => true,
  'updater.secret' => 'key,
  'maintenance' => false,
  'app_install_overwrite' => 
  array (
    0 => 'mycustomhooks',
    1 => 'admin_notifications',
  ),
);

```
</details>

**Are you using external storage, if yes which one:** no 

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:**  no 

### Client configuration
**Browser:**

**Operating system:**
Windows 10 (but same problem for example with Mac : just for the test..)

#### Web server error log

unfortunelly, no log with this issue

#### Nextcloud log (data/nextcloud.log)

no log (level debug is 2)

**Comment by szaimen** [comment]
Is this Issue still valid in NC21.0.3? If not, please close this issue. Thanks! :)
