### ISSUE TITLE
Sharing: review node fix + add regression test

### ISSUE THREAD

**Issue by blizzz** [nextcloud/server#2630]
With the fix in https://github.com/nextcloud/server/pull/2615 we have an open question about the node data and a fired hook and need a regression test:

> in ``emitAccessShareHook()`` 
>
> ```php
>				$itemType = $share->getNodeType();
>				$itemSource = $share->getNodeId();
>```
>
> will get the original node's data. My gut feeling is to have this adjusted, too. 

> With regard to [above] the hook is caught by the auditing app only (within the Nextcloud org on Github), but uses the node type. Probably it's OK to continue with the fix as is and if necessary adjust for 11.0.1. Along with a regression test.

@rullzer volunteered at least for the tests in https://github.com/nextcloud/server/pull/2615#pullrequestreview-12503699 :)

**Comment by skjnldsv** [comment]
Fixed @blizzz ?

**Comment by blizzz** [comment]
Didn't track, maybe. It's almost 4 years → closing.
